### PR TITLE
Jetpack Cloud Pricing page | Update Jetpack Complete description

### PR DESCRIPTION
**Pull request by manzoorwanijk**
Jetpack Complete includes Social Basic with unlimited shares but the description on the pricing page says, "Social: Basic with 1,000 shares/mo". This PR updates the description to reflect the change.

#### Proposed Changes

* Update description for **Security** and **Complete** comparison table
* Update description of **Jetpack Complete** inside lightbox

#### Testing Instructions

- Do any one of these
    - Click on Jetpack Cloud live link below and wait for the redirect to complete, then go to `/pricing`
    - or boot up this PR 
        - Run `git fetch && git checkout fix/jetpack-complete-description`
        - Run `yarn start-jetpack-cloud`
        - Goto [http://jetpack.cloud.localhost:3000/pricing](http://jetpack.cloud.localhost:3000/pricing)
- Under the comparison table for Security and Complete, confirm that you see "Social: Basic with unlimited shares" instead of "Social: Basic with 1,000 shares/mo" under the **Growth** section.
- For the Complete plan, click on the **More about Complete** link to open the lightbox
- Confirm that you see "Social: Basic with unlimited shares" instead of "Social: Basic with 1,000 shares/mo" under the **Includes** section.

#### Pre-merge Checklist

- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

Fixes 1198218726984184-as-1203245280300155/f

| BEFORE | AFTER |
| - | - |
| Screenshot 2022-11-22 at 1 11 05 PM 1 | Screenshot 2022-11-22 at 1 14 35 PM |
| Screenshot 2022-11-22 at 1 15 30 PM | Screenshot 2022-11-22 at 1 16 05 PM |

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1203245280300155

### CODE REVIEW

**Review by jkguidaven — APPROVED** [review]
work as expected. LGTM 👍

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/7634527

Thank you @manzoorwanijk for including a screenshot in the description! This is really helpful for our translators.

**Review by niranjan-uma-shankar — COMMENTED** [review]
This PR modifies strings and as a result, existing translations break when the page is viewed in a non-EN locale.
Screenshot 2022-11-22 at 3 51 52 PM

Screenshot 2022-11-22 at 3 57 27 PM


Can you please revert this PR and merge this back after ensuring that translations are complete? Alternatively, you can use `i18n.hasTranslation()` to expose the new string only to `en` locales and selectively expose to non-EN as translations complete. cc @Automattic/i18n

**Comment by manzoorwanijk** [comment]
> Can you please revert this PR and merge this back after ensuring that translations are complete? Alternatively, you can use `i18n.hasTranslation()` to expose the new string only to `en` locales and selectively expose to non-EN as translations complete.

Thank you for reporting that. I will preferably go with `i18n.hasTranslation()` approach.

**Comment by manzoorwanijk** [comment]
@niranjan-uma-shankar I have reverted the changes in #70279 and I have created a separate PR #70280 with these changes. We will merge that PR only when the strings are translated.

**Comment by niranjan-uma-shankar** [comment]
Thank you for the quick action! 🙇‍♂️

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/7634527).

**Pull request merged**
