### PR TITLE
Update issue templates

### PR DESCRIPTION
**Pull request by worldomonation**
Changes:
Include `Reproducibility` information in the bug report as per discussion in pciE2j-cJ-p2.

### CODE REVIEW

**Comment by p-jackson** [comment]
Nice idea! I wonder if it's somehow possible to tie it in to the

**Comment by p-jackson** [comment]
Lol I meant to cancel my comment, not close the PR!

Edit: since you're probably curious what I was going to say now, I was thinking about how "reproducibility" and "browser" are sort of related (like is it only reproducible on a particular browser). But then I reconsidered my comment because I didn't think we should make it harder for folks to enter issues, like implying that we expect they've tested the bug on multiple browsers before reporting.

**Comment by worldomonation** [comment]
> Lol I meant to cancel my comment, not close the PR!
> 
> Edit: since you're probably curious what I was going to say now, I was thinking about how "reproducibility" and "browser" are sort of related (like is it only reproducible on a particular browser). But then I reconsidered my comment because I didn't think we should make it harder for folks to enter issues, like implying that we expect they've tested the bug on multiple browsers before reporting.

I think that's a good point you bring up - in a lot of cases, the relationship between browser used and reproducibility are clear. 

An example that shows otherwise is the issue cited as an example in P2 (#49648) where it is a non-browser specific intermittent issue. That's one reason why I decided not to tie the two fields together. 

I appreciate the feedback :)

**Review by cathymcbride — APPROVED** [review]
LGTM!

**Pull request merged**
