### PR TITLE
Modularise editor state

### PR DESCRIPTION
**Pull request by sgomes**
This PR is one of many working on modularising state in Calypso. This one handles editor state.

For more details on state modularisation, see the [modularised state documentation](https://github.com/Automattic/wp-calypso/blob/master/docs/modularized-state.md) and p4TIVU-9lM-p2.

Apologies for the size of the PR, but I had no way of making it smaller, as all users of editor state need to be updated.

Note: I added all the reviewers that GitHub suggested. Please feel free to ignore the review request or pull in someone else if you're not comfortable reviewing this PR. Thank you!

#### Changes proposed in this Pull Request

* Move editor state from `ui/editor` to a new top-level `editor` entry.
* Modularise editor state.
* Update all code accordingly.

#### Testing instructions

* Install [Redux DevTools](https://chrome.google.com/webstore/detail/redux-devtools/lmhkpmbekcpmknklioeibfkpmmfibljd?hl=en).
* Open DevTools and switch to the Redux tab.
* Open `/log-in` on the live branch or your local copy of this branch.
* Click `State` on the top right to ensure you see all state, and not just the diff for the last action: 
image
* Analyse the tree and note that there's no `editor` key, even if you expand the list of keys. This indicates that the editor state hasn't been loaded yet.
* Open `/read` on the live branch or your local copy of this branch.
* Verify that an `editor` key is present with the editor state. This indicates that the editor state has been loaded.
* Verify that editor-related functionality works normally, particularly in the classic editor. This indicates that I didn't mess up.

### CODE REVIEW

**Comment by sgomes** [comment]
Note: the linting errors are expected, since I'm modifying the root reducer, which uses linting errors to point out unmodularised state in an attempt to prevent more of it from being created. In addition to this, I'm touching a number of files with existing linting issue, which would cause the PR to massively increase in scope if they were to be fixed.

**Comment by sgomes** [comment]
Note that this PR doesn't introduce any bundle savings, since editor state is widely used across the UI, being tied to the logged int masterbar. Separating it may allow for future improvements, though, and contributes to a cleaner `ui` state, which will hopefully only include Calypso-wide concerns rather than being a collection of miscellaneous UI-related state.

**Comment by simison** [comment]
FYI @Automattic/explorers who have been looking into deprecating Calypso editor.

**Comment by sgomes** [comment]
Rebased on master.

**Comment by creativecoder** [comment]
> FYI @Automattic/explorers who have been looking into deprecating Calypso editor.

Thanks for the heads up! We haven't started the code deprecation part of that project yet, so I don't think there's any immediate impact on us with this change.

❤️ seeing this kind of infrastructure improvement!

**Comment by sgomes** [comment]
Rebased to fix conflict.

**Comment by sgomes** [comment]
Rebased to pick up recent changes to `lib/media`.

**Comment by sgomes** [comment]
Rebased again to pick up changes in #43680.

**Comment by sgomes** [comment]
Hey folks, any chance of a review? This PR touches a lot of files, so it'll likely keep needing frequent rebasing while it's open.

**Review by Copons — APPROVED** [review]
I've smoke tested Calypso for a while.
I can confirm that:
- `/log-in` doesn't initialize the `editor` state.
- `/read`, `/home`, and both Calypso Classic and Gutenframe initialize it.
- There are no obvious issues with both editors.
- There are no remaining `ui.editor` occurrences in the code (except a `ui.editorDeprecationDialog` which is unrelated — although we could move it over to the new state in a follow up).

**Comment by sgomes** [comment]
Thank you so much for the review, @Copons, you rock! 🙇 👍

**Pull request merged**
