### PR TITLE
Experiment: build a Sidebar mini-app using Calypso framework and SDK

### PR DESCRIPTION
**Pull request by jsnajdr**
Attempt to build a sidebar mini-app, similar to the sidebar on WP.com frontend, out of Calypso components and with Calypso SDK.

It shows just the sidebar (with somewhat broken styling) and the site selector:

screenshot 2019-02-28 at 14 45 40
screenshot 2019-02-28 at 14 45 26

Functionality-wise, it doesn't do much, but that wasn't the goal.

The gzipped production `build.min.js` is exactly 300kB, with these contents:
screenshot 2019-02-28 at 12 23 04

There are several initiatives in progress (especially the moment.js refactoring) that will make it even smaller. Some dependencies are unneeded, but will require some untangling work to remove them.

With such a small app, the fact that we're shipping all CoreJS polyfills is significant, and so is the monolithic Lodash. Using the ESM-enabled and tree-shakable `lodash-es` could remove a lot of code.

Another monolithic library is `wpcom.js` and its `wpcom.undocumented` extension. No matter how few methods you actually use, we always bundle the whole WP.com client. Data Layer attempted to fix that, but the transition is far from finished.

Finishing the CSS migration to webpack and properly componentizing the stylesheets is crucial to get reasonable CSS assets generated for each mini-app.

**How to run:**
1. `CALYPSO_ENV=production npm run sdk -- sidebar`
2. `serve -l 3000 public`
3. `open http://calypso.localhost:3000/sidebar-app`

### CODE REVIEW

**Comment by sgomes** [comment]
@jsnajdr I feel like I'm missing some context here, possibly as a result of not being subscribed to the right places :) Is this an experiment to help assess bundle bloat, or is there a different goal behind it?

**Comment by simison** [comment]
>There are several initiatives in progress (especially the moment.js refactoring) that will make it even smaller. Some dependencies are unneeded, but will require some untangling work to remove them.
>
> With such a small app, the fact that we're shipping all CoreJS polyfills is significant, and so is the monolithic Lodash. Using the ESM-enabled and tree-shakable `lodash-es` could remove a lot of code

Noting that `moment`, `lodash` and some (all relevant?) polyfills are available as externals in WP 5.0.

**Comment by sgomes** [comment]
Do we know where the jQuery dependency is coming from? It's thankfully being lazily loaded, but it'd still be a nice win to drop it.

**Comment by sgomes** [comment]
> Using the ESM-enabled and tree-shakable `lodash-es` could remove a lot of code.

A big +1 on switching to `lodash-es`. The major downside on that switch is making sure you get it all in one go, in order to avoid a situation where you end up shipping both.

Is this perhaps doable with some WebPack alias magic? Even if the mapping results in all of `lodash-es` being shipped initially, it would then be possible to later go in and rewrite imports across the application to do the tree-shaking.

**Comment by sgomes** [comment]
> With such a small app, the fact that we're shipping all CoreJS polyfills is significant

CoreJS polyfills are added in automatically based on the lowest common denominator in your `browserslist` supported browsers. If multiple builds (#30768) proves to be a good approach, it could be interesting to have two builds of the mini-app too, the evergreen version of which would have barely any CoreJS polyfills.

**Comment by blowery** [comment]
@sgomes We could also take a look at using the [`usage` variant of `useBuiltIns`](https://babeljs.io/docs/en/babel-preset-env#usebuiltins). That would let us only ship the polyfills we actually use. Though I think it's still a bit experimental...

**Comment by sgomes** [comment]
`react-dom` is taking up a significant chunk there too.

Depending on the eventual usage of the mini-app, it may be worth exploring the possibility of building with `preact` + `preact-compat` instead as an exploratory project. This would almost certainly require code changes for compatibility (`preact-compat` is not perfect and it doesn't implement things like synthetic events), but it would make a huge difference.

Still, it's a long shot with some big downsides:
- Time investment is large
- It's not guaranteed it'll work
- Changed components would have to be made compatible with both React and Preact (there are always edge cases)
- It would add delays in terms of adopting new React features, as we must wait until they come to Preact

The gains are pretty appealing, though:
- `react` + `react-dom` (gzipped): 35.6kB
- `preact` + `preact-compat` (gzipped): 7.5kB

**Comment by blowery** [comment]
> A big +1 on switching to `lodash-es`. The major downside to that switch is making sure you get it all in one go, in order to avoid a situation where you end up shipping both.

> Is this perhaps doable with some WebPack alias magic?

We're [currently](https://github.com/Automattic/wp-calypso/blob/master/webpack.config.js#L245) doing [the opposite](https://github.com/Automattic/wp-calypso/tree/master/server/bundler/babel/babel-lodash-es). 😄

**Comment by jsnajdr** [comment]
> Do we know where the jQuery dependency is coming from?

Some parts of Calypso, e.g., some payment gateways and other 3rd party integrations, depend on the `$`/`jQuery` global. So we need to load jQuery.

In the web version of Calypso, we load it from WordPress.com CDN. Webpack is not involved.

In the Desktop app, we bundle it as a webpack chunk and that's what you see in the treemap image above.

See the [lib/load-script](https://github.com/Automattic/wp-calypso/blob/6533329441cb2f83fbe924eb8f5eaa16b127b197/client/lib/load-script/index.js#L44-L70) code.

The code that loads the chunk looks like this:
```js
if ( config.isEnabled( 'desktop' ) ) {
  import( 'jquery' ).then( $ => window.$ = $ );
}
```
That has one unfortunate consequence: the `config.isEnabled( 'desktop' )` question cannot be answered at compile time and webpack always creates the `jquery` chunk, even for non-desktop builds and even though it's guaranteed to never be loaded.

If we could use the webpack `DefinePlugin` to define a compile-time constant:
```js
new DefinePlugin( { 'process.env.IS_DESKTOP': JSON.stringify( config.isEnabled( 'desktop' ) ) } )
```
and then use it:
```js
if ( process.env.IS_DESKTOP ) {
  import( 'jquery' ).then( $ => window.$ = $ );
}
```
then webpack would be able to eliminate that branch completely and never create the `jquery` chunk.

**Comment by jsnajdr** [comment]
This PR served its purpose and can be closed now. It inspired a lot of shipped work on CSS migration, Sidebar refactoring and other entrypoints like Login.

**Pull request closed without merging**
