### PR TITLE
Activity log: make circle styles more robust

### PR DESCRIPTION
**Pull request by keoshi**
#### Changes proposed in this Pull Request

* Add a fixed width/height to circles that contain icons.
* Ensure the circles and timestamps are horizontally centered.
* Reorder styles for better readability.

#### Screenshots

Before | After
--|--
image | image
image | image

#### Testing instructions

* Spin up this PR.
* Open the Activity Log on an active site.
* Confirm all circles are round and look consistent across multiple devices.

Fixes issue reported in p1HpG7-9xQ-p2#comment-40285

### CODE REVIEW

**Comment by folletto** [comment]
It seems this made the circle not centered in the line anymore, if we can adjust that quickly it's probably ideal. We can also push this in, and do a separate PR to fix the alignment if it takes more time.

**Comment by scottsweb** [comment]
Screenshot 2020-06-24 at 11 29 28

All looks good to me.

**Comment by keoshi** [comment]
Thanks for catching that, @folletto — it was partially due to a bad auto-complete on what should have been `align-items`, but also an adjustment that needed to be made to ensure equal spacing on smaller screens. Should all be fixed now:

image

**Comment by folletto** [comment]
Excellent 👍

**Pull request merged**
