### PR TITLE
Me: Improve "Change Username" Account Settings

### LINKED ISSUE #94464: Account Settings: The Account Information card needs UI polish
### Quick summary

When attempting to update the username, the card changes to the following:

Screenshot 2024-09-12 at 12 03 57 PM

The "Would you like a matching blog address too?" and "Please Read Carefully" sections doesn't seem to follow the current design system.

### Steps to reproduce

1. Head to /me/account.
2. Update the username field.

### What you expected to happen

The new card state UI should feel consistent with the rest of the design.

### What actually happened

The new card state UI has a mixture of different font sizes, line heights, etc.

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### If the above answer is "Yes...", outline the workaround.

_No response_

### Platform (Simple and/or Atomic)

_No response_

### Logs or notes

_No response_

### LINKED ISSUE #94465: Account Settings: Don't show the Confirm Username error banner.
### Quick summary

Currently, the availability of the new username is checked as users type in the field. At the same time, we show an error banner below the "Confirm Username" field that says "Please re-enter your new username to confirm it".

Screenshot 2024-09-12 at 12 03 57 PM

Since the "Save username" button is disabled until both "Username" and "Confirm Username" have the same value, there is no need to display this error banner. As an alternative, consider updating the "Confirm new username" description to indicate that they need to confirm for the save button to be enabled.

### Steps to reproduce

1. Head to /me/account.
2. Update the username field.

### What you expected to happen

Only see the error banner when I haven't confirmed my username.

### What actually happened

See the error banner while I was still typing the new username.

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### If the above answer is "Yes...", outline the workaround.

_No response_

### Platform (Simple and/or Atomic)

_No response_

### Logs or notes

_No response_

### PR DESCRIPTION
**Pull request by Aurorum**
Fixes #94464; fixes #94465

## Proposed Changes

* Improves the "Change username" settings under Me > Account Settings

## Why are these changes being made?

See original issue - this section currently feels 'off' because it doesn't match the Calypso design guidelines. I'd argue that the `Notice` component should really be used to emphasise the important information (ie. the actual warning), and that `FormInputValidation` should inform the user whether their username is valid. 

## Testing Instructions

Navigate to Me > Account Settings and try changing your username. Verify that you still need to confirm your username for this change to work, and that you are still warned about the consequences for this change.

| Current | Proposed |
|--------|--------|
| Screenshot 2024-09-17 at 20 28 41 | Screenshot 2024-09-17 at 20 28 46 | 

cc @taipeicoder, @okmttdhr, @m1r0

### CODE REVIEW

**Comment by Aurorum** [comment]
I have updated this PR in-line with @javierarce's feedback in #94465 so that it now includes a confirm modal and a success notice when completed. This should be ready for review now!

Screenshot 2024-09-28 at 12 43 49

**Comment by javierarce** [comment]
Nice work, @Aurorum! 

I just noticed a couple of things:

- Could we hide the "Joined September 2024" line? That line is not helpful in this context.
- Could we change the label of the main button to "Change username"?

CleanShot 2024-09-30 at 11 53 16@2x

There's a strange edge case where the main username field is invalid, and the confirmation below is valid. It's probably out of the scope of this PR, and it's non-critical, but I'll just mention it:

CleanShot 2024-09-30 at 11 54 59@2x

Here's how to reproduce the bug:

1. Enter a new username in the username field
2. Confirm the username
3. Remove the username in the top field
4. Remove the username in the bottom field

**Comment by Aurorum** [comment]
Thanks @javierarce! 

> Could we hide the "Joined September 2024" line? That line is not helpful in this context.

Done - though I'm not sure if it should be moved elsewhere? I've removed it entirely for now.

> Could we change the label of the main button to "Change username"?

Done!

> There's a strange edge case where the main username field is invalid, and the confirmation below is valid.

Nice spot! I've fixed this now. 

Let me know if there's anything else to address. :)

**Comment by javierarce** [comment]
> Done - though I'm not sure if it should be moved elsewhere? I've removed it entirely for now.

Oh, no, I meant to hide it from the change username step, not completely. That information is helpful in the general context of the page, but not so much when you are updating your username.

> Let me know if there's anything else to address. :)

Just the submit button to "Change username" instead of "Save username". Thanks!

And finally, we should also update this page: https://wordpress.com/support/change-your-username. I'll find someone that can update it.

**Comment by Aurorum** [comment]
Oh, whoops, apologies - I misunderstood! Both of those should be fixed now. :)

Screenshot 2024-10-01 at 11 09 39

**Comment by Aurorum** [comment]
@Addison-Stavlo @DustyReagan I noticed that you were working on similar settings in #94683 so wondered if you might be interested in reviewing this one too? No worries if not! :)

**Review by Addison-Stavlo — COMMENTED** [review]
Thanks @Aurorum! 

This looks reasonable at first glance. Although we have a merge conflict in the css file that could use resolving.

Il be able to look closer and test more a bit later as well, and will try to re-trigger the builds and tests for this PR as needed.

**Comment by Aurorum** [comment]
Thanks @Addison-Stavlo! I've resolved those styling conflicts now. :)

**Comment by Addison-Stavlo** [comment]
calypso live link for this build: [https://calypso.live?image=registry.a8c.com/calypso/app:build-121386](https://calypso.live/?image=registry.a8c.com/calypso/app:build-121386)

**Comment by Addison-Stavlo** [comment]
This tests well on my end! pinging @davemart-in in case there are any other thoughts on the design side.

**Comment by davemart-in** [comment]
I created a brand new test account and tested this flow before and after this PR. I have two observations:

**1 - Since these are radio buttons, should one of these be checked by default?**

CleanShot 2024-10-08 at 09 00 21@2x

I'd probably lean towards `No, don't create a matching blog address.` being the default

**2 - When I tested this out, it didn't actually change my site address:**

CleanShot 2024-10-08 at 09 02 09@2x

After I confirmed the change, I still saw my old site address:

CleanShot 2024-10-08 at 09 02 32@2x

But the display name did update:

CleanShot 2024-10-08 at 09 03 08@2x

Is the intent of that radio option to update the site address, or the display name?

**Comment by davemart-in** [comment]
@Aurorum I stand corrected on my second point. I just checked my sites dashboard and I see:

CleanShot 2024-10-08 at 09 10 15@2x

So that second one does work as expected.

**Comment by Addison-Stavlo** [comment]
> Is the intent of that radio option to update the site address, or the display name?

I THINK it is supposed to create a NEW blog altogether (newusername).wordpress.com ?

I don't think this functionality has been altered on this PR, here is how it looks on production currently:

Screenshot 2024-10-08 at 9 11 50 AM

**Comment by Addison-Stavlo** [comment]
> So, if we make the "No" radio option the default, this should be good to go from my perspective.

Sounds good! Everything else looks good from my end too. I just need to look into the translation checks for the new copys.

**Comment by Aurorum** [comment]
It would be great to change that radio (see #95071), but it looks like that's returned by the API, so I can't edit it. But yes, that functionality isn't touched here.

**Comment by Addison-Stavlo** [comment]
We can create a follow up issue to track it.

**Comment by Addison-Stavlo** [comment]
@Aurorum I merged this into https://github.com/Automattic/wp-calypso/pull/95221 so the translations can build from this repository before we merge into trunk. We can continue from there 😄

**Comment by Aurorum** [comment]
Sounds good - thanks @Addison-Stavlo! :)

**Comment by Addison-Stavlo** [comment]
And thank you as well for your contributions here! 😄

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/16898997

Some locales (Hebrew, Japanese) have been temporarily machine-translated due to translator availability. All other translations are usually ready within a few days. Untranslated and machine-translated strings will be sent for translation next Monday and are expected to be completed by the following Friday.

Thank you @Aurorum for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/16898997).

**Pull request merged**
