### PR TITLE
FSE: Release 1.9

### PR DESCRIPTION
**Pull request by sirreal**
Bump FSE plugin for 1.9 release.

Includes:
- https://github.com/Automattic/wp-calypso/pull/43084 (@noahtallen)
- https://github.com/Automattic/wp-calypso/pull/42911 (@kwight)
- https://github.com/Automattic/wp-calypso/pull/39328 (@noahtallen)
- https://github.com/Automattic/wp-calypso/pull/43070 (@akirk)
- https://github.com/Automattic/wp-calypso/pull/42885 (@artpi)
- https://github.com/Automattic/wp-calypso/pull/42583 (@akirk)
- https://github.com/Automattic/wp-calypso/pull/42996 (@ianstewart)
- https://github.com/Automattic/wp-calypso/pull/42761 (@ockham / @p-jackson)
- https://github.com/Automattic/wp-calypso/pull/43116 (@sirreal)

Testing:
- Apply D44727-code to sandbox
- Test editor
- Check features in release notes are present

### CODE REVIEW

**Comment by p-jackson** [comment]
I've added more release notes. I left out the donations block from #42911 because it's still a8c only.

Also [alphabetized and updated contributors](https://github.com/Automattic/wp-calypso/pull/42996#discussion_r437053958) @vindl :)

**Comment by ramonjd** [comment]
Tested with D44727-code

- https://github.com/Automattic/wp-calypso/pull/43084  ✅ 
- https://github.com/Automattic/wp-calypso/pull/42911  ✅  Took me a while to work out that `fse-donations-block` sticker had to be applied :)
- https://github.com/Automattic/wp-calypso/pull/39328 ❓ I can't test wp-env does not work for me at all. @p-jackson I noticed you got it to work. If you think it's okay, then this PR LGTM
- https://github.com/Automattic/wp-calypso/pull/43070  ✅ 
- https://github.com/Automattic/wp-calypso/pull/42885  ✅ 
- https://github.com/Automattic/wp-calypso/pull/42583 ✅ 
- https://github.com/Automattic/wp-calypso/pull/42996 ✅ 
- https://github.com/Automattic/wp-calypso/pull/42761 ✅ 
- https://github.com/Automattic/wp-calypso/pull/43116 ✅

**Comment by p-jackson** [comment]
>     * #39328 ❓ I can't test this. `wp-env` does not work for me at all. @p-jackson I noticed you got it to work. If you think it's okay, then this PR LGTM

Not a blocker to shipping I don't think because as a dev tool it's not included in the release, and the change is already on `master` where devs work.

Did you do a `yarn install`? Using `npx wp-env` is to make sure it uses the version in the dependencies.

**Comment by ramonjd** [comment]
> Did you do a yarn install? Using npx wp-env is to make sure it uses the version in the dependencies.

Yeah. I think it's me. I've never been able to get it to work. Lots of `filemtime(): stat failed` and `PHP Fatal error:  Uncaught RuntimeException` in the docker container. 🤷

**Comment by p-jackson** [comment]
I've gotten `filemtime()` errors when I've forgotten to build the fse plugin first, 'cause it's complaining the built files don't exist. But it could be other things.

**Comment by ramonjd** [comment]
> I've gotten filemtime() errors when I've forgotten to build the fse plugin first, 'cause it's complaining the built files don't exist. But it could be other things.

Okay, I'm going to 🤦  on a public channel. Thanks @p-jackson !!!!!

I forgot to build. And probably all the other times I saw errors and was too lazy to check the docs. :(

**Pull request merged**
