### PR TITLE
FSE: expose additional themes in signup

### PR DESCRIPTION
**Pull request by vindl**
#### Changes proposed in this Pull Request

Adds Morden, Stow, and Hever to the theme selection step
in the signup flow.

Screenshot 2019-12-04 at 16 38 15

#### Testing instructions

1. Navigate to http://calypso.localhost:3000/start/test-fse/fse-themes
2. Verify that you can see all of the newly supported FSE themes: Alves, Maywood, Morden, Stow, Hever, Exford, Shawburn.

### CODE REVIEW

**Comment by noahtallen** [comment]
Should we also add Alves now?

**Comment by vindl** [comment]
> Should we also add Alves now?

Yes, thanks for pointing it out. 👍

**Comment by noahtallen** [comment]
And that can be easily changed later if we want to merge this now

**Comment by vindl** [comment]
> The only thing is what @Copons noticed, with the 7 themes looking a bit weird with only one theme on the last line. Maybe we only need to expose 6? Probably a call for @apeatling

We can easily remove one if needed later. Also we'd need to decide which one.

**Comment by p-jackson** [comment]
@vindl any reason Alves, Morden, Stow and Hever were removed from the list of template first themes? This removed them from the `design-first` flow and just checking whether that was intentional.
Themes can appear multiple times in the array.

**Comment by vindl** [comment]
> @vindl any reason Alves, Morden, Stow and Hever were removed from the list of template first themes? This removed them from the design-first flow and just checking whether that was intentional.
Themes can appear multiple times in the array.

@p-jackson It wasn't intentional. Since fse themes are a strict subset of template first themes, I thought they would end up being reused. I'll spin up a patch to add duplicate entries for them.

**Comment by vindl** [comment]
@p-jackson should be fixed in https://github.com/Automattic/wp-calypso/pull/38194.

**Pull request merged**
