### PR TITLE
Try: Full Width

### PR DESCRIPTION
**Pull request by alternatekev**
With the advent of the sticky sidebar, the T-shaped layout we've got going on now feels a little odd to me, especially on wide computer screens:

screen shot 2015-12-16 at 1 10 57 pm

This PR is more or less a place for me to sketch some ideas on how we can start to use the space a little more effectively, which I've done with some hacky SCSS changes. This branch looks like this:

screen shot 2015-12-16 at 1 12 27 pm
screen shot 2015-12-16 at 1 12 41 pm
screen shot 2015-12-16 at 1 12 47 pm
screen shot 2015-12-16 at 1 13 00 pm
screen shot 2015-12-16 at 1 13 06 pm
screen shot 2015-12-16 at 1 13 13 pm
screen shot 2015-12-16 at 1 17 39 pm

It doesn't fix all of each page's problems but I honestly don't see anything show-stopping here in that regard. I'm probably disagreed-with.

What I mostly affected:
- SectionNav: This is fixed to right beneath the MasterBar, and goes all the way to the right edge of the screen, mirroring the MasterBar, since it also sticks in place on top of content now.
- Needed some exemptions made for non-SectionNav sections which should be distributed to components instead of being baked into the Main component like how I did here.
- It was hard to figure out which margins to use in some places. I'm sure there are some adjustments to make there.
- Certain page, like Insights and Blog Posts look super weird now. We'd have to pretty quickly update those layouts to make better use of the stretchy space, including some of their responsive strategies (particularly the "more" swap-a-roo that happens for Blog Posts).

Paging @rickybanister @MichaelArestad @justinkropp @jeffgolenski @mtias @folletto @shaunandrews @kellychoffman

### CODE REVIEW

**Comment by jeffgolenski** [comment]
@alternatekev Thanks for digging into this. Perhaps you've recently seen my gripes about the experience on larger screens. I appreciate this is being looked into.

Just a question though. There are a few places where simply extending the width of elements really doesn't make sense. I feel we could make much better use of space if we stacked some elements on their x axis. 

For instance: Publicize

The length of these doesn't really serve much practical purpose:

screen shot 2015-12-16 at 3 56 07 pm


What if, if the window was greater than a certain width we did something like this:

screen shot 2015-12-16 at 3 58 14 pm

Just a super rough mock, but I just think it would made user of horizontal space better.

Just another super rough idea for the reader on a super wide imac or something:

screen shot 2015-12-16 at 4 01 30 pm

**Comment by alternatekev** [comment]
Yep, totally. This is simply the first step in getting these ideas possible, I think.

**Comment by alternatekev** [comment]
Maybe this is really a proposal for how to handle the SectionNav in full-width mode more than anything else.

**Comment by jeffgolenski** [comment]
@alternatekev Awesome. Sounds great to me mang. Carry on!

**Comment by folletto** [comment]
> It doesn't fix all of each page's problems but I honestly don't see anything show-stopping here in that regard.

I have just one thing that is imho a show stopper: any line of text that goes **over about 700px**. Longer lines with the size and line height we use gets unreadable, and we need to avoid that, because it would mean to sacrifice readability. 

I would personally keep the ~700px limit as a rough rule of thumb: if a UI goes beyond that, can't ship without a redesign that fixes it. That rule in general also would loosely address the notes above by Jeff. :)

> Editor

On the Editor specifically, we already have a design done, App Style, and that's upcoming next. :)

**Comment by shaunandrews** [comment]
Honestly, the last thing I want is full width Reader cards; It just makes the line-lengths insane and stretched images beyond a reasonable amount. Also, the side-by-side Reader cards suggested above may work for places where your browsing (My Likes, for example) but in a stream (like Followed Sites) it just breaks the chronology of the stream.

**Comment by kellychoffman** [comment]
Cool. We have a similar design in mind for a full width editor:

screen shot 2015-12-17 at 5 16 02 pm

**Comment by alternatekev** [comment]
@shaunandrews is this a crazy idea? I know the blurring makes it hard to see what's going on, but basically we could surface more content from other pages into a columns, if we wanted to limit the line widths. Just an idea.

screen-shot-2015-12-17-at-7 53 07-pm

**Comment by folletto** [comment]
I think that's a good idea but since that's the "Following" page, should be all new stuff coming to me, not my activity (My Likes). Maybe comments received? Likes received? :)

**Comment by shaunandrews** [comment]
I think a third column is likely a better solution. Not sure My Likes is the best thing to put there — or even incoming activity as Davide suggested above. We're working on the recommendations section now, building out recommended sites and (hopefully) posts. I think recommendations would make a ton of sense in the Followed Sites stream.

**Comment by folletto** [comment]
>  We're working on the recommendations section now, building out recommended sites and (hopefully) posts. I think recommendations would make a ton of sense in the Followed Sites stream.

Good idea. :)

**Comment by rickybanister** [comment]
I was discussing this with @mtias a bit. I feel like in most cases the fullscreen layout feels like it's 2009 and you accidentally visited `m.somewebsite.com` and got the mobile stylesheet all stretched to the desktop screen. 

What if we just show the picker open all the time at extremely wide widths? That's more in line with the architecture of calypso. On mobile you see one column, on laptops you see two, on @jeffgolenski's screen you see all three. 

I can certainly see value in doing a fluid layout for something like stats, but I don't think we should try to find ways to fill the space for other sections. I rather like our line length as it is. 

If you have a ludicrously wide screen we could even pop open notifications or something (that was @mtias's idea, can't take credit).

It seems like it'd be a lot easier to maintain more breakpoints if we didn't add any more styles for content, just toggled visibility of already-existing elements.

**Comment by mtias** [comment]
So, I think we should leave sections as they are, I don't think there's a compelling reason to make them wider just because there's space yet.

Instead, what if we go back to the core IA of Calypso and look at exposing it better when you go wide above 1600px or so. We have `sites -> site sections -> content` — with a wide screen we can show all three levels at once:

calypso-ai-model

That means showing the site picker all the time to the very far left. Another thing could also be keeping the notifications panel open in really wide cinema-display full-screen sizes, to the far right as a fourth column.

------

As for the content itself, I think we could go with just two layouts.

* Standard single-column document.
* Grid-like for sections like Themes and maybe a new incarnation of Stats.

Each section can declare which of these they'll work with, and that's it.

**Comment by alternatekev** [comment]
The thing about the site picker though is that it's nearly always irrelevant to what you're doing in the main part of the screen. Don't most of our users have 1-2 sites? Showing the site picker the entire time seems like _more_ of a way to just fill up the screen with something we already have, no matter the relevance to the task. The site picker is hidden by default for a reason, I presume, probably because it's simply a waste of space at normal resolutions. 

Why would having a wider screen make the site picker more relevant to me? Having a choice for each section's team to make between 1-up/2-up is a little closer to what I was envisioning, though.

What about a `FullWidthGrouping` component that knows how to float things next to each other at wide resolutions? I could wrap them around anything I wanted, so if I wanted Cards to float next to each other, I could do that, or if I wanted groupings of form fields within a Card to wrap next to each other, I could do that, too?

I'm not trying to push an agenda here regarding full-width content. It's just that I've been using this branch to do some work and it's pointed out to me how awkward the T-shaped layout really is, especially given the docked sidebar. 

I just don't see how the site picker adds any value to the user when they're trying to change their site settings or turn on two-factor auth or write a blog post.

**Comment by alternatekev** [comment]
> keeping the notifications panel open in really wide cinema-display full-screen sizes, to the far right as a fourth column.

This would be something cool to try. At least we know notifications are by definition relevant to the user.

**Comment by folletto** [comment]
I agree the sites on the left would add little value, and wouldn't make wider screen really more valuable. On the other side I don't also want to push too-long lines just because we want to go full screen.

I'd leave each section to design their own, now that's possible, without pushing too heavy right now to go everywhere full screen.

> keeping the notifications panel open in really wide cinema-display full-screen sizes, to the far right as a fourth column.

This is interesting. :)

**Comment by Mikewaite** [comment]
It seems a bit odd to me that this discussion is about how these components should be laid out in a view specifically per component. 

Instead, I would instantiate a 12/16 column grid of containers, apply that grid to the available content space, and finally figure out how each of these specific components behave across multiple widths which should inform the design of the css of which breakpoints are needed across all components.

**Comment by lancewillett** [comment]
@alternatekev What's the next steps for this pull request? Archive, close, keep open, needs more fixes or design review?

**Comment by alternatekev** [comment]
I’d say it could use a new tag; experimental/ignore :)

**Comment by lancewillett** [comment]
Haha, noted. Thank you.

**Pull request closed without merging**
