### PR TITLE
Update newspack blocks to v1.2

### PR DESCRIPTION
**Pull request by noahtallen**
### Changes proposed in this Pull Request
* v 1.2 update to fix duplicate posts issue

cc @obenland

### CODE REVIEW

**Comment by obenland** [comment]
Either D40741-code doesn't actually include v1.2.0 of the block, or v1.2.0 of the block doesn't contain the duplicate posts fix. Either way, store.js is still the old file in D40741

**Review by obenland — CHANGES_REQUESTED** [review]
Just double-checked, and the update is in v1.2.0. So something doesn't work in resolving that dependency.

On the upside, the SPT store fix is working.

**Comment by noahtallen** [comment]
It appears that `npm i` is not updating the package lock, so `npm ci` won't pick up on the latest changes to the block 🙃

**Comment by noahtallen** [comment]
@obenland It should be fixed now. I removed it and ran npm i, then added it back and ran npm i. So now it should be in the packagelock

**Review by obenland — APPROVED** [review]
Thank you! BPB works as expected now

**Pull request merged**
