### PR TITLE
composite-checkout: Jump to payment method step if contact details are prefilled

### PR DESCRIPTION
**Pull request by nbloomf**
#### Changes proposed in this Pull Request

This adds code such that if you load checkout when the contact details form fields are valid, we skip the contact details step and go directly to the review step (step 2 in the current flow).

#### Testing instructions

- Enter checkout as an established user with stored domain details. Verify that the contact details step is collapsed on page load, displaying the summary and green checkmark, and that you can complete the purchase.
- Enter checkout as a user with an existing plan only (stored zip and country, but not complete domain details) to purchase a domain. Verify that the contact details step is not collapsed on page load and that you can complete the purchase.
- Enter checkout as a user with no previous purchases with a domain in the cart. Verify that the contact details step is not collapsed and that you can complete the purchase.

### CODE REVIEW

**Comment by nbloomf** [comment]
I tried buying a plan only (no domain) for a user with cached details. The purchase worked with no errors. Here's what it looked like on the page:

Screen Shot 2020-05-29 at 1 12 49 PM

The only odd things I see are that (1) the details summary isn't shown, and (2) the phrasing of the step title is a little odd now, asking me to "Enter your billing details" when I don't need to.

**Comment by nbloomf** [comment]
Tried again with a brand new user, with both plan only and plan+domain+gsuite. Checkout loads with the details step not in summary mode (as expected) and validation works as expected.

**Comment by sirbrillig** [comment]
This exposes a race condition edge case: If we send off the validation request to the server (when the form loads), but the request takes a long time, by the time it comes back the user may have already started editing the form. This is hard to solve, though. Reasons:

If we want to avoid doing anything when the validation comes back if the user has started editing, we need to know the edited state of the contact details when that async call completes, not when it starts.

The other direction is to disable the form while the validation loads, but that's hard because when it finishes loading, we may or may not want to enable the form, depending on if something else has currently disabled the form.

This may just be edge casey enough to allow for the time being.

**Comment by nbloomf** [comment]
Works as described. We'll definitely need to keep an eye on the possible race condition, but it should be pretty rare in practice.

**Comment by nbloomf** [comment]
I do see one bug- to reproduce:

- Enter checkout as a user with an existing plan, but not a domain, so your stored details cache has a country and zip code but not the complete details.
- On page load I see the contact details failure notification:

Screen Shot 2020-05-29 at 3 46 23 PM

We should only show this if the validation fails after clicking on the submit button.

**Comment by sirbrillig** [comment]
Thanks! To solve that issue, I refactored the contact details validation (pretty heavily, so we'll want to test both the domain and G Suite versions) to separate out the validation itself from the error saving and reporting. Still testing now, but it should work in theory. We could possibly move that refactoring to its own PR; what do you think?

**Comment by sirbrillig** [comment]
Contact details changes moved to https://github.com/Automattic/wp-calypso/pull/42821 although I will leave them here too until that is merged.

**Comment by nbloomf** [comment]
Testing again:

- User with a plan+domain, purchasing a domain: on load, the contact details step flashes in the uncollapsed state before the details load. Editing and validation work as expected and I can complete a purchase.
- User with plan only, purchasing a domain: contact details section is not collapsed on page load. Editing and validation work as expected and I can complete a purchase.
- User with no purchases, purchasing a domain only: contact details section is not collapsed on page load. Editing and validation work as expected and I can complete a purchase, _however_ -

I had a 504 error (timeout) on the call to /me/transactions while processing the purchase, even though the transaction did complete. Trying to complete the purchase again resulted in an "invalid product" error because the domain was no longer available. I am pretty sure this is unrelated to this PR, and probably related to the extremely slow responses from my sandbox.

**Comment by sirbrillig** [comment]
Rebased after #42821. Going to test one more time before merging.

**Comment by nbloomf** [comment]
I tested again as a user with cached details purchasing a plan and domain. The contact details step was expanded but not editable on page load, and shortly entered the collapsed state. Editing and validation worked as expected, and only one email address was shown in the summary step (as expected).

Looks great!

**Pull request merged**
