### PR TITLE
Stats: Update traffic page layout

### PR DESCRIPTION
**Pull request by jsnmoon**
#### Proposed Changes

Reflows the Traffic page layout to adhere to the design specified in #68975. Specifically, this PR:
- Grids the modules list
- Grids the country module
- Flexboxes all stats modules
- Reorders module declarations within the modules list

#### Testing Instructions

* Spin up this change on a Calypso live branch.
* Navigate to the Traffic Stats page with `?flags=-stats/new-stats-module-component` appended to the URL to **mimic the current production interface**.
* Ensure that the page looks reasonable at all breakpoints. Note that the SVG map in the country module does not handle resizing well.
* (Bonus) Ensure that the Insights, Store, and Ads pages remain unaffected.
* (Bonus) Ensure that the "post details" and "post summary" pages remain unaffected.

#### Pre-merge Checklist

- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React, or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?

#### Screenshot

calypso 2

### CODE REVIEW

**Review by grzegorz-cp — APPROVED** [review]
It looks really good. I tested it on the `Traffic` and `Insights` pages. Changes to `stats-card` are fine as well.
The only thing I noticed is that when resizing (and being close to a breakpoint), the labels for the `Authors` component get their toggle arrow covered. This is something to be handled by the horizontal bar component, similar to improving the map that should be handled by the `countries` component.

**Comment by keoshi** [comment]
This looks absolutely great! This reflow makes all the difference in the world, bringing a whole new dynamic to this page — thank you for it!

#### Country list aligment

- [x] On large desktop, would it be possible to align the country list with the referrers list?

image

#### Responsive styles

- [x] Some item titles are being hidden behind the overflow gradient.

image
image

- [x] Country list is overflowing to the right, outside of the card.

image

_Disclaimer: most likely unrelated to this PR, let me know if I should create a new issue for this._
On the smallest resolutions, we should adjust the card styling:

- [ ] Set `border-radius` to `0px`.
- [ ] Set `border-left` and `border-right` to `0px` so the card is flush with the window and only has border on the top and bottom.

image

**Comment by jeffgolenski** [comment]
@jsnmoon  Besides the feedback from @keoshi, I'm wondering if we can adjust the card to be dynamic span the given area? Example: on My personal site, the videos card sits by itself on its own row and occupies a small area of the grid. Where-as on Jetpack.com File Downloads shows and the layout is more balanced. 

Screen Shot 2022-11-11 at 12 43 26 PM
Screen Shot 2022-11-11 at 12 40 02 PM

**Comment by jsnmoon** [comment]
>  On large desktop, would it be possible to align the country list with the referrers list?

I couldn't align it quite as you specified, but I got it pretty close!

> [Design feedback]

@keoshi: I addressed all items except for those for card styling. I think it'll make more sense to address with #69044 :)

@jeffgolenski: The videos module should dynamically expand to take up the whole row now.

**Review by keoshi — APPROVED** [review]
Looks great to me! :shipit:

**Comment by keoshi** [comment]
> I addressed all items except for those for card styling. I think it'll make more sense to address with https://github.com/Automattic/wp-calypso/issues/69044 :)

Makes absolute sense, added a note on that issue. Thank you!

**Comment by simison** [comment]
FYI, I'm seeing some sass warnings in trunk — perhaps from this PR? Might've been pre-existing, too. Would be great if someone can take a look! Thanks.

```
DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($stats-sections-max-width, 2)

More info and automated migrator: https://sass-lang.com/d/slash-div

   ╷
56 │             padding: 0 max(calc(50% - #{$stats-sections-max-width / 2}), 32px);
   │                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
    client/my-sites/stats/style.scss 56:32  root stylesheet

DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.

Recommendation: math.div($stats-sections-max-width, 2)

More info and automated migrator: https://sass-lang.com/d/slash-div

   ╷
60 │             margin: 0 max(calc(50% - #{$stats-sections-max-width / 2}), 32px);
   │                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   ╵
    client/my-sites/stats/style.scss 60:31  root stylesheet
```

**Comment by jsnmoon** [comment]
Thanks for the heads up, @simison -- I introduced that regression here. This is being fixed in #70229.

**Pull request merged**
