### PR TITLE
Reader a8c convos: modify copy of intro box

### PR DESCRIPTION
**Pull request by samouri**
Modifies the copy of the a8c intro box and adds link to point to internal call for testing.

To Test
-----
go to a8c convos and manually copy/paste this into the console
```
dispatch( {
	type: 'PREFERENCES_SET',
	key: 'has_used_reader_conversations_a8c',
	value: false
} );
```

cc @fraying

### CODE REVIEW

**Comment by jancavan** [comment]
Small nit: I think the space should be added after the second sentence. Currently, the link includes a space.

**Comment by michelleweber** [comment]
Do y'all need anything from Editorial here?

**Comment by samouri** [comment]
circle ci failed with an issue that i think is transient.  rerunning...

**Comment by samouri** [comment]
> Do y'all need anything from Editorial here?

Thanks for asking @michelleweber ! I think we are all good though

**Pull request merged**
