### PR TITLE
Update/package whats new wp data

### PR DESCRIPTION
**Pull request by donlair**
#### Changes proposed in this Pull Request
* This PR moves implements Redux state management for the What's New component.
* Migrates the ETK version of What's New to the package component version.

#### Testing instructions

* Checkout this PR and start Calypso.
* Sync ETK to your sandbox.
* Sandbox a test site.
* Load the post editor using the sandboxed and synced version of ETK.
* navigate to the MC What's New admin tool and add a new announcement.
* Wait for the endpoint cache to update (max of 10 minutes)
* In the editor sidebar, click What's New
* Confirm that the Announcements from the MC tool are displayed.

Related to #
* 50224
* D57620-code

### CODE REVIEW

**Comment by noahtallen** [comment]
cc @sarayourfriend Does this make more sense as a component rather than a package? (context: It's a modal which displays screenshots and text showing new features. In the future it might connect to an API too.)

**Comment by donlair** [comment]
@noahtallen @sarayourfriend this is a continuation of the work in #50926. That components pulls the announcements from a WPcom endpoint so we won't need to deploy ETK to add new What's New slides.

In that PR, which I'll deploy today, state is managed w/ useState, but that didn't work well for actual implementation since the container components didn't have access to the state and couldn't trigger the component.

CC @tyxla

**Comment by sarayourfriend** [comment]
It's hard to see the changes with the PR as it stands today. Do you mind targeting the previous branch on this PR (changing `trunk` to `add/calypso-whats-new-self-contained` for the base branch)? That would make it easier to see what the issues were so we can help (or merge the `add/calypso-whats-new-self-contained` branch and rebase this one).

**Comment by donlair** [comment]
> It's hard to see the changes with the PR as it stands today. Do you mind targeting the previous branch on this PR (changing `trunk` to `add/calypso-whats-new-self-contained` for the base branch)? That would make it easier to see what the issues were so we can help (or merge the `add/calypso-whats-new-self-contained` branch and rebase this one).

Yep, I'll deploy the original and will get them lined up so you can see the updates clearly!

**Comment by donlair** [comment]
@sarayourfriend okay it was a little messy with the rebase, but you can see the file changes highlighted now!

**Comment by sarayourfriend** [comment]
Just so I understand the issue that is being addressed here is that the `showWhatsNew` needs to be able to be triggered by parent components?

This is technically feasible without using `wp/data` FWIW, I think you could do it using `useImperativeHandle` and put a `toggleWhatsNew` function on the `ref` inside the `WhatsNew` component, but I'm not sure that is a better solution than what you have here. Then again, I'm not keyed into the particularities of whether using `wp/data` for such a simple situation is good/bad or neutral.

I've requested a review from @tyxla to see what Marin thinks about this.

From me this is fine though.

**Comment by donlair** [comment]
> Just so I understand the issue that is being addressed here is that the `showWhatsNew` needs to be able to be triggered by parent components?
> 
> This is technically feasible without using `wp/data` FWIW, I think you could do it using `useImperativeHandle` and put a `toggleWhatsNew` function on the `ref` inside the `WhatsNew` component, but I'm not sure that is a better solution than what you have here. Then again, I'm not keyed into the particularities of whether using `wp/data` for such a simple situation is good/bad or neutral.
> 
> I've requested a review from @tyxla to see what Marin thinks about this.
> 
> From me this is fine though.

@sarayourfriend the other issue that I was thinking about was that the parent component should know whether the modal has been subsequently closed, that way the use could reopen the modal if they wanted to. I haven't used `useImperativeHandle` before - would that address this piece as well?

**Comment by sarayourfriend** [comment]
I'm not sure that would be possible without a lot overly complex code to accomplish it with `useImperativeHandle`. You'd probably want to use React's `context` at that point but then you might as well use `data` I think, at least `data` is easier to grok for most applications I think and would be for this one.

**Comment by tyxla** [comment]
@donlair could you please elaborate on what are the data and state needs for the **What's New** package? On top of what is already visible in the PR, what kind of data is being planned to be stored, and what would be the actions performed with it? 

I'm asking because I'm not convinced that we really need to use Redux if the scenario is just "fetch this single piece of data once, and that's all". 

We've been consciously avoiding Redux (and consequently `@wordpress/data` too) for such simple scenarios. `react-query` has demonstrated to be working great for scenarios where we even have pagination, infinite scrolling, and additional arguments, while it has also helped keep away all of the boilerplate that Redux and `@wordpress/data` stores require.

**Comment by donlair** [comment]
> @donlair could you please elaborate on what are the data and state needs for the **What's New** package? On top of what is already visible in the PR, what kind of data is being planned to be stored, and what would be the actions performed with it?
> 
> I'm asking because I'm not convinced that we really need to use Redux if the scenario is just "fetch this single piece of data once, and that's all".
> 
> We've been consciously avoiding Redux (and consequently `@wordpress/data` too) for such simple scenarios. `react-query` has demonstrated to be working great for scenarios where we even have pagination, infinite scrolling, and additional arguments, while it has also helped keep away all of the boilerplate that Redux and `@wordpress/data` stores require.

Thanks @tyxla - there's just one speed bump here that led me to Redux. Giving the parent container awareness of whether the What's New modal is open or closed. In particular the use case where somebody opens the modal, then closes it, and tries to open it again. It's that third step that I _think_ requires global state (or something like it). @sarayourfriend mentioned one possibility, but that Redux may be easier. I looked into useContext a bit as well and that didn't seem quite right. Happy to explore other options as well.

The most likely future state for this is tracking which announcements a user has seen and putting some new of "unread" icon on the button that pops the modal (the red circle). In that case, I think we'd dispatch actions as the user sees new announcements to record the activity.

**Comment by tyxla** [comment]
> @sarayourfriend mentioned one possibility, but that Redux may be easier. I looked into useContext a bit as well and that didn't seem quite right. Happy to explore other options as well.

I think `useContext` does feel like a better option in that scenario, and easier to implement, with much less boilerplate. At first glance, this actually looks simple enough so we could even use `useState` to implement the "modal open or closed" state. Have you considered that?

> The most likely future state for this is tracking which announcements a user has seen and putting some new of "unread" icon on the button that pops the modal (the red circle). In that case, I think we'd dispatch actions as the user sees new announcements to record the activity.

That can be a good reason to create a Redux or `@wordpress/data` implementation eventually, although it might also be unnecessary, depending on the consumption and complexity. I guess, we could discuss that when the need comes, and for now, we could follow the YAGNI strategy 😉 

What are your thoughts?

**Pull request closed without merging**
