### PR TITLE
[WIP] Explore adding safety checks for Stepper signup flows

### PR DESCRIPTION
**Pull request by daledupreez**
## Proposed Changes

This PR explores adding integration tests to make sure that Stepper flows flagged with `isSignupFlow: true` correctly redirect users to the appropriate login URLs, and ensure that the flows correctly trigger `calypso_signup_start` events. There are some important things to note in terms of what I've built:
 * Not all signup flows are covered by the login redirect logic yet, as a number of flows only redirect to a login UI when specific steps are submitted, and some don't ever redirect to a login UI. Those flows are:
   - `entrepreneur` - from submit() call
   - `import-focused` - no redirects!
   - `link-in-bio` - from submit() call
   - `link-in-bio-domain` - from submit() call
   - `link-in-bio-tld` - from submit() call
   - `videopress` - from submit() call
 * The login redirect checks are _very_opinionated, especially for other locales.
   - As a baseline, the redirect checks require all of the following:
     * `toStepper=true` is included in the URL
     * `variationName=<flowName>` is included
     * `redirectTo` points at `/setup/<flowName>`, with a possible step name in the path if we're looking at a specific step. (This is particularly relevant for flows that redirect after an intro step.)
    - When the locale is specified in the incoming URL, we also verify that the locale is specified in the login URL _and_ that the `redirect_to` URL includes the same locale value.
      * @Automattic/i18n, I would love your input on what rule we should be aiming for. I think the best default is to retain the `locale` throughout, but there are cases where someone may switch locale in the login UI, and I am not sure what the best practice for the downstream logic would be at that point. Can we safely assume that the user has a locale assigned and we don't need to rely on the URL parameter?
 * The tests verify that we correctly call `recordSignupStart()` with the flow name and `ref` parameter, for both logged-in and logged-out users.
 * The tests verify that we don't call `recordSignupStart()` when we view a step later in the flow.

* My work on the tests also uncovered a number of areas where we could be using simpler, more centralised logic, but likely didn't have those things available at the time. As a result, the PR as written includes _way_ too many semi-related functional changes, which should likely be split out into separate, smaller PRs.

## Testing Instructions

*

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [x] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Comment by ddc22** [comment]
@daledupreez the simplification efforts look great so we should look to get them merged in a focussed PR.

However I am not sure if the unit tests really cover the essence of the core issue that's troubling us. I think it would be better to focus more on E2E tests. @travisw built a great [foundation](https://github.com/Automattic/wp-calypso/pull/86024) for this. Basically set up a tests and make sure tracks events appear in the order expected.


Just to be clear I think these tests are definitely valuable. But it will not solve the exact problem of broken events hollisticaly which I would argue can be solved only via E2E tests.

I was thinking of diving into this a bit this week. Apologies if I commented too quickly on a WIP PR :)

**Comment by travisw** [comment]
> I think it would be better to focus more on E2E tests. @travisw built a great https://github.com/Automattic/wp-calypso/pull/86024 for this. 

Thanks for the ping, @ddc22. Something I realized that I hadn’t thought about when setting up that foundation is that if we add e2e tests for signup flows then the tests would create new users and sites in the production database. There have understandably been some wastefulness concerns with this approach in the past. So this is something we should be aware of and work around if possible.

Some background: pMz3w-dAG-p2, p58i-gh5-p2, PCYsg-TWW-p2, PCYsg-jvX-p2

**Comment by daledupreez** [comment]
> However I am not sure if the unit tests really cover the essence of the core issue that's troubling us. I think it would be better to focus more on E2E tests. @travisw built a great https://github.com/Automattic/wp-calypso/pull/86024 for this. Basically set up a tests and make sure tracks events appear in the order expected.

While my tests aren't checking for the Tracks events (yet), I am verifying that all signup flows are correctly passing `toStepper=true` to the use flow. And I do plan to add tests for Tracks functionality within the flows (I am just not there yet).

More broadly, however, I fundamentally disagree with using E2E tests as the primary testing approach. My concern with the E2E tests is that they need to be written and maintained by someone for specific flows where we think it's worth keeping the events correct. The likelihood of new Stepper flows being added to that suite is really low, especially by teams who aren't familiar with the E2E testing framework _or_ the specific Tracks event sequences we expect for signup flows. The goal of my tests in this PR is to try and automate the testing so it applies to all Stepper flows _without any developer intervention_. If you're doing it wrong, the tests should fail before you deploy your code, and in a test suite that you can easily run in a "normal" Calypso environment, and debug without too many complications.

**Comment by ddc22** [comment]
@daledupreez I don't think we are on the same page on this. I agree with you 100% that unit tests are far superior and I myself would love to avoid the nightmares of E2E. But the current issue specifically is with the flow switching frameworks. 

In any case unit tests that monitor events at the stepper/framework level will be a great addition as I mentioned above.

Just so we do not step on each other's toes, I will focus more on fixing the other issue related to the erroneous occurrence of the step event before logging in. Then I will explore how practical it is to setup a minimal set of E2E tests to make sure the critical flows across frameworks.

> some wastefulness concerns 

Yep they have been a thorn in our overall dev workflow. Not sure how much we should avoid it. I will ask around a bit.

**Comment by daledupreez** [comment]
@ddc22 and @travisw, I've now expanded the tests to make sure we're (not) calling `calypso_signup_start` correctly for all Stepper flows, as well as making sure we're redirecting to a login page with `toStepper=true` for most signup flows, which should help reduce some bugs across switching.

I think we still have a functional/existing gap in the code around detecting when we shouldn't trigger a signup start event (e.g. when coming back from the user flow), but I still think this constitutes progress around simulating that the code is doing the right thing when users hit `/setup/<flow>` in various states.

e2e tests would also be a good thing, but I think they'll catch different failure modes, and may be harder to run in a blanket fashion.

**Comment by dlind1** [comment]
> @Automattic/i18n, I would love your input on what rule we should be aiming for. I think the best default is to retain the locale throughout, but there are cases where someone may switch locale in the login UI, and I am not sure what the best practice for the downstream logic would be at that point. Can we safely assume that the user has a locale assigned and we don't need to rely on the URL parameter?

A logged-in user should have a locale in their profile, but until then the locale should be taken from the URL. The login page can suggest switching a locale based on your browser language if it doesn't match the URL locale, but that'd simply go to the URL with the new locale. For example, https://wordpress.com/log-in/es should show a prompt to go to https://wordpress.com/log-in/en if your primary browser locale is English.

**Comment by daledupreez** [comment]
I am going to close this PR, as some of the key improvements in this PR are addressed by the features in https://github.com/Automattic/wp-calypso/pull/91241, and we're still in the process of rolling those improvements out as part of the broader tracking issue in https://github.com/Automattic/dotcom-forge/issues/7643.

**Pull request closed without merging**
