### PR TITLE
Stop test and translate new strings

### PR DESCRIPTION
**Pull request by richardmuscat**
Stopping copy test and translating strings so that it can be available to all users.

### CODE REVIEW

**Comment by richardmuscat** [comment]
@yoavf -- first time asking for translations here. is the status label enough?

**Comment by yoavf** [comment]
@richardmuscat yes - that's good. It was labeled after we sent our most recent weekly kit yesterday, so the strings will only go out for translation next Monday. If it's important to rush this, let us know.

**Comment by yoavf** [comment]
Oh, but there aren't any new strings in this branch.

**Comment by tyxla** [comment]
@yoavf I believe the strings in question were introduced in #16716, @richardmuscat feel free to correct me if I'm wrong.

Also, I've rebased the PR to resolve any existing conflicts.

**Comment by yoavf** [comment]
@fditrapani Since #16716 was merged a while ago, everything has been translated already.
See https://translate.wordpress.com/localci/status/automattic/wp-calypso/add/jetpack-plans-copy-test

**Comment by fditrapani** [comment]
Great. Thanks @yoavf.

**Comment by richardmuscat** [comment]
@yoavf / @fditrapani -- what are next steps here?

**Comment by yoavf** [comment]
Nothing blocking on the i18n side

**Comment by fditrapani** [comment]
We should be good to merge @richardmuscat

**Comment by richardmuscat** [comment]
@tyxla -- is this something you can give me a hand with?

**Comment by tyxla** [comment]
@richardmuscat sure thing, will happen in the next hour or so.

**Pull request merged**
