### PR TITLE
Checkout: fix full credits payment method behavior

### PR DESCRIPTION
**Pull request by sirbrillig**
#### Changes proposed in this Pull Request

The shopping-cart endpoint, prior to D52836-code, will report the total without _any_ credits applied if the number of credits equals or exceeds the cart subtotal. With the above diff, those inconsistencies are no longer present.

Because of this, we can remove some of the hacks that were in place on the front-end (many of which were added in https://github.com/Automattic/wp-calypso/pull/47305). This PR does that. We also will need to more clearly differentiate between "free" and "full credits" because now with a 0 total, full credits will also be free. Because we want to always display full credits differently, this PR modifies the logic where free purchases are concerned and makes it more explicit.

Fixes 56-gh-Automattic/payments-shilling

Before, with full credits (enough to completely cover the total + taxes):

before-taxes-changes

After, with full credits (enough to completely cover the total + taxes):

Screen Shot 2020-11-18 at 5 28 06 PM

Before, with just taxes (enough credits to cover the subtotal, but not taxes):

Screen Shot 2020-11-17 at 6 31 37 PM

After, with just taxes (enough credits to cover the subtotal, but not taxes):

just-enough-credits-except-taxes-after

Before and after, with partial credits:

before-partial-credits-taxes

Before, with a free purchase and credits:

Screen Shot 2020-11-16 at 7 21 37 PM

After, with a free purchase and credits:

Screen Shot 2020-11-16 at 7 20 20 PM

#### Testing instructions

- Apply D52836-code.
- Visit checkout without any credits, proceed to the last step, and verify that the subtotal, taxes, and total lines look correct and no credits are listed.
- Visit checkout with some credits (but not enough to cover the entire transaction), proceed to the last step, and verify that the subtotal, taxes, credits, and total lines look correct.
- Visit checkout with enough credits to cover the subtotal, excluding taxes, proceed to the last step, and verify that the subtotal, taxes, credits, and total lines look correct (the total should be just the taxes and you should be required to use a real payment method).
- Visit checkout with enough credits to cover the entire transaction, including taxes, proceed to the last step, and verify that the subtotal, taxes, credits, and total lines look correct (the total should be 0 and you should see the "pay with credits" payment method).
- Visit checkout with just a free product in your cart (the simplest thing is probably to use a coupon with a 100% discount) and with some credits (but not enough to cover the entire transaction or you won't see the button to add a coupon); verify that the subtotal, taxes, and total lines look correct, there are no credits listed, and that you see the "free purchase" payment method, not the "pay with credits" payment method.

### CODE REVIEW

**Review by fditrapani — COMMENTED** [review]
The screenshots look great! Nice update. 

I'm trying to test this with the patch and my credits don't seem to be showing while I'm sandboxed.

**Review by fditrapani — APPROVED** [review]
Thanks to Cain, I got my sandbox working — Looking good on the front-end!

**Review by wp-desktop — CHANGES_REQUESTED** [review]
WordPress Desktop CI Failure for job "wp-desktop-mac".

@sirbrillig please inspect this job's build steps for breaking changes at [this link](https://circleci.com/gh/Automattic/wp-calypso/954849). For temporal failures, you may try to "Rerun Workflow from Failed".

Please also ensure this branch is rebased off latest Calypso.

**Comment by nbloomf** [comment]
- 0 = credits < product = product+taxes:

DN55 1PT (Doncaster):
Screen Shot 2020-11-18 at 5 35 58 PM

21212 (Baltimore):
Screen Shot 2020-11-18 at 5 37 16 PM

- 0 = credits < product < product+taxes:

77001 (Houston):
Screen Shot 2020-11-18 at 5 39 13 PM

- 0 < credits < product = product+taxes:

DN55 1PT (Doncaster):
Screen Shot 2020-11-18 at 5 44 14 PM

21212 (Baltimore):
Screen Shot 2020-11-18 at 5 45 28 PM

- 0 < credits < product < product+taxes:

77001 (Houston):
Screen Shot 2020-11-18 at 5 46 26 PM

- 0 < product < credits < product+taxes:

77001 (Houston):
Screen Shot 2020-11-18 at 5 48 58 PM

- 0 < product = product+taxes < credits: (Only the full credits method is available)

DN55 1PT (Doncaster):
Screen Shot 2020-11-18 at 5 51 23 PM

21212 (Baltimore):
Screen Shot 2020-11-18 at 6 03 33 PM

- 0 < product < product+taxes < credits: (Only the full credits method is available; I list this under nonzero taxes because normally this zip code has taxes applied even though the line is zero here)

77001 (Houston):
Screen Shot 2020-11-18 at 6 02 00 PM

- 0 = product = credits: (Redeeming a domain credit; only the free purchase method is available)

DN55 1PT (Doncaster):
Screen Shot 2020-11-18 at 5 56 54 PM

21212 (Baltimore):
Screen Shot 2020-11-18 at 5 58 10 PM

77001 (Houston):
Screen Shot 2020-11-18 at 5 59 03 PM

- 0 = product < credits: (Redeeming a domain credit; only the free purchase method is available)

DN55 1PT (Doncaster):
Screen Shot 2020-11-18 at 5 53 36 PM

21212 (Baltimore):
Screen Shot 2020-11-18 at 5 55 17 PM

**Review by nbloomf — APPROVED** [review]
Looks good and works as expected.

**Comment by DavidRothstein** [comment]
Impressive testing, @nbloomf!

I tested a much smaller variety of these (mostly because I was looking into how these changes affected the amount actually charged on receipts) and for one of the common cases I saw a different result than you which actually looks problematic.

For this one:

>- 0 < product < product+taxes < credits: (Only the full credits method is available; I list this under nonzero taxes because normally this zip code has taxes applied even though the line is zero here)
>
>77001 (Houston):
>Screen Shot 2020-11-18 at 6 02 00 PM

I think the reason you saw no taxes might actually be because this was a domain purchase, and domains aren't taxable in Texas?

I tried with a Premium Plan and a Pennsylvania ZIP code and got this:
credits-equal-to-or-greater-than-total

Which doesn't add up :)  It should have shown `-$101.76` for the credits, since that is what was actually charged.

Overall, this pull request definitely makes things better, and in the above scenario it doesn't necessarily make things worse -- so I wouldn't necessarily hold it up over this.  But paying with full credits is one of the most common scenarios so if it's an easy fix hopefully it can be addressed.

**Comment by sirbrillig** [comment]
Hah, good find, @DavidRothstein. I had one commit locally that I hadn't pushed to the branch, and guess what it was? So that should be fixed now.

**Comment by DavidRothstein** [comment]
Perfect -- works as expected now!

Seems like this is good to go, although I'm not sure if it's safe to push out before D52836-code.

**Pull request merged**
