### PR TITLE
A4A-Partner Directory: Add common selector components: Industry, Languages, Products, Services

### PR DESCRIPTION
**Pull request by cleacos**
Resolves https://github.com/Automattic/automattic-for-agencies-dev/issues/628

## Proposed Changes

This PR adds some common components to select some Agency data:

- IndustrySelector
- LanguagesSelector
- ProductsSelector
- ServicesSelector

They are wrapper components for the `FormTokenField` and `SelectControl`.

**Update - Screenshot**

image

## Why are these changes being made?

*

## Testing Instructions

- Check the code
- 

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Comment by jkguidaven** [comment]
I attempted to rebase this in the trunk and used it in the Expertise form, but this is what happened. Can we fix the styling for this first?


Screenshot 2024-06-05 at 10 18 04 PM

**Review by jkguidaven — APPROVED** [review]
I could fix the styling issue in my PR. LGTM

**Comment by cleacos** [comment]
Re-approved! LGTM!

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/14130305

Some locales (Hebrew, Japanese) have been temporarily machine-translated due to translator availability. All other translations are usually ready within a few days. Untranslated and machine-translated strings will be sent for translation next Monday and are expected to be completed by the following Friday.

Hi @cleacos, could you please edit the description of this PR and add a screenshot for our translators? Ideally it'd include all of the following strings:
- `Agricultural services`
- `Transportation services`
- `Utility services`
- `Retail outlet services`
- `Clothing shops`
- `Miscellaneous shops`
- `Business services`
- `Professional services and membership organisations`

Thank you in advance!

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/14130305).

**Pull request merged**
