### PR TITLE
Tweak locale suggestion look

### PR DESCRIPTION
**Pull request by coreh**
This has been a pet peeve of mine for a while. The locale suggestion notice has no max-width, so it looks kinda broken on a large monitor.

screen shot 2016-05-24 at 17 14 45

I've set a max-width for it matching the survey's (500px) and also tentatively added the globe icon, and removed the `is-info` class, that way it doesn't compete as much with the top bar visually.

screen shot 2016-05-24 at 17 19 05

Here's how it looks like on the context of the whole window:

screen shot 2016-05-24 at 17 14 48

### CODE REVIEW

**Comment by bisko** [comment]
If the survey isn't the first step, the width wouldn't be right.

screen shot 2016-05-26 at 18 05 16

Is there a way to make it work for different widths?

Love the new look! ❤️

**Comment by bisko** [comment]
This is related to #622

**Comment by michaeldcain** [comment]
If there's not a way to make it work for the variable widths of different Signup steps, I'm happy with the way the new `max-width: 500px` notice looks, or we can pick something slightly wider. 

We'll want to make sure that a similar style is applied to any other global Signup notices (i.e. unverified users that re-enter Signup are given a notice).

**Comment by coreh** [comment]
Now that all the basic flows start with `'survey'` we don't really need to worry about the variable first step widths anymore.

**Comment by shaunandrews** [comment]
I dig the 500px max-width everywhere for the notice. 👍

**Pull request merged**
