### PR TITLE
Consolidate Redux SocketIO API 

### PR DESCRIPTION
**Pull request by nosolosw**
Master issue: https://github.com/Automattic/wp-calypso/issues/18670

This PR implements the idea of modeling the whole system flow as Redux actions. See `lib/happychat/connection/README.md` for the API rationale and design walkthrough. This also minimizes the API surface, enabling us to introduce changes quickly and safely. See a real [example](https://github.com/Automattic/wp-calypso/pull/18817#issuecomment-339589421).

Commit message includes a full description of the changes, should you want to compare the before/after.

## Test

`npm run test-client happychat`

Manually open a happychat connection and test that it works.

* is the operator
  - receiving the user info msg?
  - receiving the user messages?
  - receiving the page changes?
  - receiving other event/log actions? (test, for example, to change a theme in a ongoing chat session)
  - receiving the typing events?
  - receiving the user change locale?
* can the user
  - send/receive messages?
  - receive transcripts?

### CODE REVIEW

**Comment by nosolosw** [comment]
This has been rebased from the latest master and now I'm testing everything again, to make sure nothing got drop in the integration.

**Comment by nosolosw** [comment]
This works as expected and it's ready to review. cc @mattwondra in case you are up to do it.

**Comment by nosolosw** [comment]
An example of how these changes will help us to evolve the SocketIO API:

- Before: see this PR https://github.com/Automattic/wp-calypso/pull/18487/files The current setup forces us to introduce the same changes in the SocketIO connection library, middleware, and the action creator (besides any action creator callers). 

- After: we would only need to change the Redux action creator. See:

change

I believe this simplicity would help us to increase the speed of development and have fewer bugs!

**Comment by mattwondra** [comment]
@nosolosw Is it possible to break this down into smaller PRs? It's really intimidating to review something with thousands of changed lines, it actually makes it difficult to keep all the changes in your head and understand the greater goals...

@omarjackman @unDemian could you give this a quick look to see if you have thoughts on this overall approach?

**Comment by nosolosw** [comment]
The lib/happychat/README has written down the overal goal for the API. The first commit has a looong comment with the before/after changes. Would those be helpful?

I know is a lot, but I did it this way hoping it would speed up review by taking less of your time than having one small PR for every action. Also, it helps me to continue my work building on this without failing into integration hell.

@mattwondra Please, do let me know if it's too much to ask so I should prepare smaller PRs.

**Comment by mattwondra** [comment]
Our team has actually found that multiple smaller PRs speeds up the review process compared to one large PR. You'll have about the same amount of lines of code to review either way, but splitting 1000 line changes into 10 100-line changes makes it much simpler on each PR to understand the specific intent, and follow the code paths to ensure no mistakes were made.

As a reviewer, when I'm planning my day it's much easier to bite off a small PR than a large one. So small PRs probably also improve expediency of reviews. When I see `+1,000 -1,000`, I know it's going to take me a long sitting to get through so it's easier to procrastinate on it.

I'd bet that smaller PRs increase code review accuracy too. Halfway through a big PR I lose focus, but I can't stop reviewing because I've got all the context loaded in my head and I don't want to lose it. I'm sure that I get lazier, gloss over "unimportant code like tests", and don't bring my best simply because I get fatigued.

I know the strategy doesn't work great for every type of change, but I think I could see ways of splitting this up without it becoming a dozen daisy-chained branches that all need to rebase when something changes near the root. For instance, one PR could set up this new `send( action )` interface which is a good way to understand your intent behind the new structure by seeing the interface alone. Since it's small, it's likely to merge quickly (or if it's contentious, it's good it got out before a lot of other code was written on top of it). You could then make a bunch of parallel (not chained) branches to bring each of the custom connection methods into the new system, one at a time.

I'll let @unDemian @omarjackman and @southp weigh in on whether they feel like their review could benefit from this being broken down (I promise I don't want to create extra work, I really want to make sure everyone groks the idea and can carefully review). Thanks for your patience!

**Comment by nosolosw** [comment]
I agree 100% with that rationale and totally understand what you mean, Matt. I was worried that if I'd prepare X PRs it'd take > X days to integrate this. Besides, in practice, while PRs are in review I need to continue working on _something_ (and it's going to be related somehow to one of the happychat core files :integrationhell: :party: )! I wanted to reduce reviewing times to increase my delivering throughput, so I just tried _something different_. Sometimes, trying counter-intuitive things is surprisingly effective.

It seems that, in this case, this approach is not helping, so I shall prepare smaller PRs.

**Comment by nosolosw** [comment]
I've prepared a PR with the gist of the proposal here https://github.com/Automattic/wp-calypso/pull/19216/files

**Comment by mattwondra** [comment]
Thanks for the flexibility @nosolosw 💯

**Pull request closed without merging**
