### PR TITLE
DesignPreview: Enable in staging env

### PR DESCRIPTION
**Pull request by ehg**
This enables:
 - Showing (preloaded) sites in an iframe, when the site card is clicked
 - The preview steps in GuidedTours

Before this PR is merged, you can test out the current behaviour on https://wpcalypso.wordpress.com — and the tour at https://wpcalypso.wordpress.com?tour=main

/cc @lsinger & @mcsf — also looping in @mtias

### CODE REVIEW

**Comment by lsinger** [comment]
Tried both the tour and preview again on desktop and mobile (iPhone 6). LGTM.

**Comment by ehg** [comment]
Also looping in @shaunandrews, and @folletto. A baby step to Preview Everywhere :)

**Comment by mtias** [comment]
I want to give this a run through but won't have time in the immediate future. Are there any remaining concerns around performance of loading in the bg?

**Comment by ehg** [comment]
> Are there any remaining concerns around performance of loading in the bg?

I've tested on throttled connections, and it seems OK. There could be a concern over data usage, for which we may want to 'preload-on-hover'. I'm hoping enabling this for internal testing will give us some better insight as to whether that's needed. /cc @auth & @sirbrillig

**Comment by folletto** [comment]
Give it a go on Chrome, Firefox, Safari, Edge, IE11 — both look very good, works nicely. 👍 

Three tiny tiny bits, not blockers, but worth a mention:

1. Middle clicking / Cmd-clicking the site badge doesn't open a new tab as expected, always opens the preview. 
2. The spinner inside the preview at mobile sizes is a bit too high, and in the tour gets hidden behind the dialog ([screenshot](https://cloud.githubusercontent.com/assets/4389/15682448/9f52ee88-2755-11e6-8760-5aa4135d64bd.png) without dialog).
3. The "Theme" steps feels to me it should be a pulsating dot like the other steps. But maybe I'm not considering some variables.

**Comment by sirbrillig** [comment]
> I'm hoping enabling this for internal testing will give us some better insight as to whether that's needed.

Worth a try, I'd say.

**Comment by shaunandrews** [comment]
This is so awesome.

**Comment by ehg** [comment]
> Three tiny tiny bits, not blockers, but worth a mention

Split off issues [one](https://github.com/Automattic/wp-calypso/issues/5695) and [two](https://github.com/Automattic/wp-calypso/issues/5696). Deferring 3 to @shaunandrews's judgement. 

Gonna merge this now and see how well it performs on staging.

**Comment by lsinger** [comment]
> The "Theme" steps feels to me it should be a pulsating dot like the other steps. But maybe I'm not considering some variables.

I think we'll move to "arrows whenever we have a target element" instead of "pulsating dots for a few special things". /cc @shaunandrews, and also see #5689.

**Comment by melchoyce** [comment]
Nice!

Can we add a Customize button to it? 😛

**Comment by ehg** [comment]
> Can we add a Customize button to it? 😛

Yep. Could you add an issue for that, so we don't forget? :)

**Pull request merged**
