### PR TITLE
Add data attribute for e2e testing

### PR DESCRIPTION
**Pull request by brbrr**
To test: Ensure that Theme cards in ThemeList(e.g. [here](https://wordpress.com/themes)) have `data-e2e-theme` attribute and its matching `theme.id` (lowercased theme name)

### CODE REVIEW

**Comment by brbrr** [comment]
I've moved from `theme.id` to `theme.name` due to inconsistency between some themes

**Comment by alisterscott** [comment]
@brbrr I would probably avoid name as it can be different in different cultures and we run tests in different languages

**Comment by alisterscott** [comment]
Actually, maybe not, I changed culture to 'es' and theme names appeared to remain the same 👍

**Comment by brbrr** [comment]
Yeah, I checked with Russian and it remains the same. The problem with `theme.id` is that some themes id's(all `twenty *`) are just joining words without `-`. So instead of expected `twenty-fifteen` it appear as `twentyfifteen`

**Pull request merged**
