### PR TITLE
Reader Refresh: always use last scroll position

### PR DESCRIPTION
**Pull request by samouri**
Currently I think its a little strange that when clicking around different streams your scroll history isn't used to bring you back to where you were unless you've enabled the feature by clicking back. e.g.:

INSERT_EXAMPLE

This PR aims to make it so that scroll position is always remembered.

What are peoples thoughts?
Do you think this UX is better? worse?

### CODE REVIEW

**Comment by blowery** [comment]
This is also used by the post streams in my sites, need to verify we're not breaking them. Should check and see who all's using InfiniteList in the app.

**Comment by fraying** [comment]
I wouldn't call this a bug, exactly. Clicking "Followed Sites" in the sidebar has always bumped you to the top of the stream. People are probably used to it working that way. Either way, let's circle back to this post-refresh?

**Comment by fraying** [comment]
My finger is hovering over the close button. Is there a problem here? I'm not convinced. Any passion on this either way?

**Comment by samouri** [comment]
while i initially thought it was a big deal + super noticeable, i was wrong.  

closing

**Comment by fraying** [comment]
"I was wrong" is one of my favorite things to say (and hear). Bravo!

**Pull request closed without merging**
