### PR TITLE
bulk domains page - update domains table checkbox and font size

### PR DESCRIPTION
**Pull request by Addison-Stavlo**
Related to # Automattic/dotcom-forge#7073

## Proposed Changes

* Updates the font size of the domain name to .875 REM (14px)
* Updates the checkbox size to 16px
* This is all applied underneath the parent selector of `.is-bulk-domains-page`

BEFORE
Screenshot 2024-05-10 at 9 18 33 AM

AFTER

Screenshot 2024-05-10 at 9 18 19 AM

## Testing Instructions

* Run this calypso branch
* test the bulk domains page next at /domains/manage
* verify the checkbox input is reduced to 16px and name font size to 14px.

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Review by DustyReagan — COMMENTED** [review]
The font and checkbox sizes are smaller, but when you check a box, the checkmark and dash are no longer centered.

Screenshot 2024-05-10 at 9 23 33 AM

**Comment by Addison-Stavlo** [comment]
> The font and checkbox sizes are smaller, but when you check a box, the checkmark and dash are no longer centered.

Good catch, thank you!  😅  That should be resolved now.

**Review by DustyReagan — APPROVED** [review]
Looks great! 🎉

**Comment by taipeicoder** [comment]
Note: I noticed that the checkbox size is 20px in mobile resolution, I'll address this before merging.
Screenshot 2024-05-13 at 7 25 39 AM

**Pull request merged**
