### PR TITLE
Store|Woo: Hide deprecated Store menu item for sites with Business plan subscriptions after Store was deprecated

### LINKED ISSUE #48424: Store|Woo: Hide deprecated Store menu item for Business plan sites that have never used Store
If a site is created with the Business plan (or an existing site upgrades to the Business plan), and has never used Store, after the Store has been deprecated, the Store menu item in the My Sites sidebar should not be shown. Only the new WooCommerce menu item should be available.

From pbIJXs-sE-p2:

>> What happens when sunset is in effect (prior to complete removal of Store) and a new Business customer signs up? I assume they should only get the WooCommerce Core experience, right?
> 
> Yes, that’s correct. 

Acceptance criteria:

- A site with a Business plan subscription after Store is deprecated must not have the Store menu item available
- A site with a Business plan subscription before Store was deprecated must have the Store menu item available
- A site with the eCommerce plan must have the Store menu item available

### PR DESCRIPTION
**Pull request by mattsherman**
Part of the "Sunset Store on WordPress.com" epic (https://github.com/woocommerce/woocommerce-admin/issues/5816) -- see that for more context.

#### Changes proposed in this Pull Request

* Updates to `canCurrentUserUseCalypsoStore` (was `canCurrentUserUseStore`) and `canCurrentUserUseWooCommerceCoreStore` (new) selectors
* Updates My Sites sidebar to hide "Store" menu item for sites with Business plan subscriptions started after Store was deprecated

##### Automated testing

- Check out branch
- Verify that all automated tests for selectors pass:

```
yarn run test-client client/state/sites/test/selectors.js
yarn run test-client client/my-sites/sidebar/test/sidebar.js
```

##### Manual testing

_Note: to change the deprecation start date when testing, in `client/lib/plans/constants.js`, edit the `STORE_DEPRECATION_START_DATE` constant. (I don't like giving manual testing instructions that involve editing code, but this is the easiest way. There might also be a way to change the subscription date in the database/state tree.)_

- Check out branch

###### Verify that "Store" and "WooCommerce" menu items appear correctly for sites when Store is deprecated:

```
ENABLE_FEATURES=woocommerce/store-deprecated yarn start
```

- "Store" available for sites with Business plan subscriptions started before Store was deprecated
- "Store" not available for sites with Business plan subscriptions started after Store was deprecated
- "Store" (linking to WooCommerce Core) available for sites with eCommerce plan subscriptions
- "WooCommerce" available for sites with Business plan subscriptions

###### Verify that "Store" and "WooCommerce" menu items appear correctly for sites when Store is removed:

```
ENABLE_FEATURES=woocommerce/store-removed yarn start
```

- "Store" not available for sites with Business plan subscriptions
- "Store" (linking to WooCommerce Core) available for sites with eCommerce plan subscriptions
- "WooCommerce" available for sites with Business plan subscriptions

Fixes #48424

### CODE REVIEW

**Comment by mattsherman** [comment]
Looking at failed TC build...

**Comment by mattsherman** [comment]
This is ready for review -- I'll have to fix the conflicts in sidebar/index.jsx before a second pass of review, but I don't want to delay getting this in front of others any longer!

**Review by ilyasfoo — COMMENTED** [review]
Changes LGTM, tested well! It was kind of tricky to follow all the code logic pathways manually, but I think your tests covered them pretty well.

However, I would like to wait for the conflict resolution before 🚢  since the changes to WooCommerce menu item is affected.

**Comment by mattsherman** [comment]
> Changes LGTM, tested well! It was kind of tricky to follow all the code logic pathways manually, but I think your tests covered them pretty well.

 Do you have any specific places that you found tricky to follow? Any suggestions on how things could be improved? (Even if outside of the scope of this PR, it would be good to know!)

> However, I would like to wait for the conflict resolution before 🚢 since the changes to WooCommerce menu item is affected.

Definitely. Conflicts are addressed now, and ready for re-review!

**Comment by mattsherman** [comment]
Thanks for reviewing and testing @ilyasfoo !

**Comment by becdetat** [comment]
I found that with `woocommerce/store-removed` I'm still getting both 'Store' and 'WooCOmmerce' on a business plan:
image

Both lead to wp-admin but the 'Store' link has the `calypsoify` param and no `from-calypso` param.

Is this expected?

**Comment by ilyasfoo** [comment]
>Do you have any specific places that you found tricky to follow? Any suggestions on how things could be improved? (Even if outside of the scope of this PR, it would be good to know!)

@mattsherman The only tricky part was to follow all the prior logic moving to the new selectors to make sure no unintended logic changes, not anything of particular in the code in this PR (so it's a review only thing). The logic in new selectors was pretty easy to reason about 👍 .

>I found that with woocommerce/store-removed I'm still getting both 'Store' and 'WooCOmmerce' on a business plan:
>Both lead to wp-admin but the 'Store' link has the calypsoify param and no from-calypso param.
>Is this expected?

@becdetat I have tested this again and this was not the case for me. I confirmed the Store menu is gone and `calypsoify` is not applied, and `from-calypso` is. Can you confirm if your local has the latest?
image

**Comment by becdetat** [comment]
@ilyasfoo I did have the latest, but I just realised I had the `deprecated` flag set instead of the `removed` flag - I must have copied and pasted the wrong command. Everything looks great @mattsherman 👍

**Review by ilyasfoo — APPROVED** [review]
LGTM 🚢 !

**Pull request merged**
