### PR TITLE
Site Settings: Move stylesheets into dedicated bundle

### PR DESCRIPTION
**Pull request by stephanethomas**
This pull request fixes https://github.com/Automattic/wp-calypso/issues/18488 by reverting https://github.com/Automattic/wp-calypso/pull/18477/ and taking a different approach which consists in extracting the stylesheets used by the `Site Settings` section from the main CSS bundle, and moving them into a dedicated bundle that is only loaded when the section is accessed (thanks to the new CSS splitting feature introduced in https://github.com/Automattic/wp-calypso/pull/17988). This allows loading the media modal styles only for this specific section as well as the `Post Editor` section. Finally, this pull request makes sure only the necessary stylesheets, variables, and mixins are imported from all the new CSS section bundles.

#### Testing instructions

1. Run `git checkout update/css-bundles` and start your server, or open a [live branch](https://calypso.live/?branch=update/css-bundles)
2. Open the [`Signup` page](http://calypso.localhost:3000/start)
3. Assert that this section displays as before
4. Open the [`Login` page](http://calypso.localhost:3000/log-in)
5. Assert that this page displays as before
6. Open the [`General Settings` page](http://calypso.localhost:3000/settings/general)
7. Assert that the page (and any other subsection) displays as before
8. Click the `Change` button in the `Site Profile` section
9. Asserts that the media library displays normally
10. Click the `Write` button in the top bar to access the post editor
11. Click the cross icon to open the media library
12. Click any image and assert that the `Edit`  and trash buttons are correctly aligned

You may want to check these steps again by toggling the mobile device view in your browser's devtools.

#### Reviews

- [ ] Code
- [x] Product

### CODE REVIEW

**Comment by hoverduck** [comment]
I'm unable to publish, the confirmation button is hidden - 

screenshot_2017-10-03_14-25-19

**Comment by stephanethomas** [comment]
@hoverduck: I've fixed the problem you mentioned as well as another with the same root cause. Could you give this pull request another try?

**Comment by hoverduck** [comment]
@stephanethomas - Tests looked much better this time :smile:

**Comment by Tug** [comment]
There is one problem with our approach of loading the section css though. It's that, as this exemple demonstrate, we might want to use components from different sections on the same page. Given this, it doesn't make sense imo to have only a `<link id="section-css" .../>`, we should just load a section css if it's not already loaded, so only check the url, not the id.

**Comment by stephanethomas** [comment]
> we should just remove this limitation and let the section loader handle the css loading.

The problem with this approach - if I understood what you're proposing correctly - is that we're going to load an additional CSS section bundle just because we needed styles from one component. Let's say the user is accessing the [`General Settings` page](https://wordpress.com/settings/general). The `site-settings` CSS bundle is then loaded, but we would also load the `post-editor` CSS bundle because we've declared it as a dependency? 

I kind of feel we're just dealing with a semantic issue here. I agree that we shouldn't require a component from another section, but on the other hand I don't see a problem with having two sections using the same component. We obviously have a set of shared components, and maybe `post-editor/media-modal` should simply be moved to `client/components`.

The current CSS splitting mechanism is far from being perfect, but I'm not sure we should put too much effort into it since Webpack 4 will offer a brand new CSS workflow. In any case since this pull requests does the job, I would recommend merging it - we can iterate on the CSS splitting mechanism in another pull request. What do you think?

**Comment by Tug** [comment]
> The problem with this approach - if I understood what you're proposing correctly - is that we're going to load an additional CSS section bundle just because we needed styles from one component. Let's say the user is accessing the General Settings page. The site-settings CSS bundle is then loaded, but we would also load the post-editor CSS bundle because we've declared it as a dependency?

I don't think this is a problem, if you need a component from another section you're going to simply `require` that component in your code. What happens in the background shouldn't be of your concern as a calypso developer.

We have decided to split the CSS at the section level, we should then autoload CSS along with the section code imo. In this case the whole `post-editor` section code is going to be preloaded, it seems natural to me that we load its styling along with it (that's what would have happened with css modules as well).

So yeah we're going to load a whole section just for one component but it's not all bad, that section will be preloaded for the user. In theory we could even have an heuristic for preloading all chunks in the background so users don't see any delay when navigating in calypso, it's just super hard to do it right.

**Comment by stephanethomas** [comment]
> In this case the whole post-editor section code is going to be preloaded, it seems natural to me that we load its styling along with it

Well that's not true, we only [load the `EditorMediaModal` component](https://github.com/Automattic/wp-calypso/blob/b855b7a8a7e9f6a24e4fc87e8fe251cfd10603fd/client/my-sites/site-settings/site-icon-setting/index.jsx#L225) in that case.

I'm going to merge this pull request as it is since it addresses the original issue, and I'd like to be able to spend time on our primary focuses. However we can circle back on any potential improvements in another one.

**Pull request merged**
