### PR TITLE
Domain Management i1: Refactor domain links into their own module

### PR DESCRIPTION
**Pull request by p-jackson**
Just a quick follow up from https://github.com/Automattic/wp-calypso/pull/80998#discussion_r1305109197

## Proposed Changes

* Refactors functions for calculating domain links into their own module
* Use `@wordpress/url` to encode URL query params

## Testing Instructions

* There should be no change from previous behaviour

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

**Comment by vykes-mac** [comment]
Similar to the `/utils/paths.ts` you mentioned in this PR https://github.com/Automattic/wp-calypso/pull/80993.

**Comment by p-jackson** [comment]
Moved the path functions into `utils/paths.ts` now that https://github.com/Automattic/wp-calypso/pull/80993 has merged.

**Comment by zaguiini** [comment]
I think that now that we moved the code from `client/domains` over to our `domains-table` package, we can use that version instead?

**Review by zaguiini — APPROVED** [review]
Yep 👍 

A good next step would be to drop the [Calypso file](https://github.com/Automattic/wp-calypso/blob/trunk/client/my-sites/domains/paths.js) and refer to this version instead of having duplicated implementations.

After that, we can do the same thing for the [`resolveDomainStatus` function from Calypso](https://github.com/Automattic/wp-calypso/blob/trunk/client/lib/domains/resolve-domain-status.tsx#L52).

**Comment by mpkelly** [comment]
> Yep 👍
> 
> A good next step would be to drop the [Calypso file](https://github.com/Automattic/wp-calypso/blob/trunk/client/my-sites/domains/paths.js) and refer to this version instead of having duplicated implementations.
> 
> After that, we can do the same thing for the [`resolveDomainStatus` function from Calypso](https://github.com/Automattic/wp-calypso/blob/trunk/client/lib/domains/resolve-domain-status.tsx#L52).

I created https://github.com/Automattic/dotcom-forge/issues/3628

**Pull request merged**
