### PR TITLE
Signup: Add testimonials and background decoration

### PR DESCRIPTION
**Pull request by sixhours**
#### Changes proposed in this Pull Request

* Experiment with balancing the two-columns layout using background elements and the addition of a testimonial in the lower right.
* See also #27862 

Before: 

46971801-fcca9800-d08a-11e8-940c-1bf5b9a85b9e

After:

screen shot 2018-10-19 at 11 57 31 am

#### Testing instructions

* Switch to this PR and navigate to `/start`
* Check `/about` and `/user` (user-first signup when logged out, may need to check for the A/B test to see it) to see visual changes.
* Note visual changes and testimonial addition.

### CODE REVIEW

**Comment by sixhours** [comment]
[Add new layout to signup flow](https://trello.com/c/4sP7mBr4/127-add-new-layout-to-signup-flow)

**Comment by fditrapani** [comment]
Thanks for putting this together @sixhours. It helps to see it like this. The background and added elements definitely help with the balance. The spacing above the title + progress indicator are still throwing things off though. I went into the inspector and moved things around a little. What do you think of this: 

screen shot 2018-10-19 at 8 42 48 am

The alignment of the title to the top of the card squares things nicely and moving the progress indicator to the top helps when you move from step to step. I also moved the continue button inside the card so the testimonial align nicely with it at the bottom. 

Another small note, is the testimonial feels very prominent with such a bold type face. Maybe we can tone it down a bit with a font-weight of 400?

One other note to consider is how this looks on Mobile:

image

Is there any way we can get that testimonial to show after the form?

**Comment by shaunandrews** [comment]
Even with @fditrapani's tweaks, I can't help but think the balance is totally off with the left aligned text, and the right aligned card. I'd suggest swapping the order (card on left, text on right), but thats just weird.

I've come to the conclusion that a centered heading/subheading is the way to go.

--

Also, I'm pretty sure the original intention for the placement of the testimonial was to be anchored to the bottom-left of the browser window, and then wrap underneath the card when the window gets too narrow.

**Comment by fditrapani** [comment]
> I've come to the conclusion that a centered heading/subheading is the way to go.

This might be the case so I'm glad we're working through it here to test it out.

**Comment by fditrapani** [comment]
Nice update @sixhours . When you click through from step 1 > step 2 it doesn't feel so bad when the layout changes with the steps staying in place. There's probably a little more tweaking we need to do to the testimonial and adding the continue button in the card but overall, this is feeling better. Anyone else have any thoughts? cc @shaunandrews 

https://hash-90314bc6e424f308104428fac9d3107af62eead8.calypso.live/start/about

**Comment by iamtakashi** [comment]
I think a consistent layout throughout the signup is a way to go. What problem we're trying to solve with the 2 column layout? Seeing the domain and the plan steps, it might be hard to adapt the steps to the 2 column layout, and that makes me think it's best to stick to the centred-align layout.

**Comment by danhauk** [comment]
Looking good @sixhours, thanks for powering through all of this while we're still working through it.

I agree the progress steps staying in place is great for consistency between steps, but it just feels off for me on the two-column layout. The progress indicator feels disconnected and floaty there between the two columns, which I think actually draws my attention to it more than it should.

Other than that I don't mind the two column layout and think it balances well. This could be because it fills out my smaller 13" screen vs. a larger screen.

The testimonial seems a bit large. It's fighting the hierarchy of the rest of it. Where I think this should be more secondary content, it keeps pulling my attention away from other things. Maybe try reducing the size of the image and copy a little bit there?

> Also, I'm pretty sure the original intention for the placement of the testimonial was to be anchored to the bottom-left of the browser window, and then wrap underneath the card when the window gets too narrow.

This was my interpretation as well though I would have to see it. It will break the left aligned grid which might not work well.

Nitpick: on mobile, what do you think about reducing the size of the main heading and bringing everything up closer to the step indicator? It feels overpowering to me, especially holding it in my hand.

Before | After
------------ | -------------
screen shot 2018-10-22 at 15 29 37 | screen shot 2018-10-22 at 15 30 48

**Comment by sixhours** [comment]
Dropping a quick note here to say, the two-column layout works better on smaller screens; we noticed during a user interview today that on a small screen, the large heading + content makes for a lot of scrolling on desktops.

**Comment by shaunandrews** [comment]
I noticed that today, too, @sixhours — maybe we take both. Show the two-column at tablet and smaller laptop/desktop screens, then jump to centered at larger widths/heights.

**Comment by fditrapani** [comment]
> I noticed that today, too — maybe we take both. Show the two-column at tablet and smaller laptop/desktop screens, then jump to centered at larger widths/heights.

This still wouldn't solve some screens being two column and others being single. I also worry about it adding more complexity for us to maintain. Maybe it is best to stick with a single column. Adding the squares in the background does give it a little more texture which is nice. @sixhours can we pull those out into a separate PR. (The colour work is in progress and coming really soon).

**Comment by sixhours** [comment]
Background decor has been added in #28056; I'm going to close this since I'll plan to split Testimonials into their own PR.

**Pull request closed without merging**
