### PR TITLE
Reader: Update Back button in Tag streams

### PR DESCRIPTION
**Pull request by jancavan**
**Before:**
screenshot 2016-11-30 14 40 59

**After:**
screenshot 2016-11-30 14 41 28

### CODE REVIEW

**Comment by jancavan** [comment]
Need help with:

- [ ] Adding a custom class for those with a "Back" button to assign custom positioning for it
- [ ] Should this only be applied specifically to Tags streams? `is-tag-stream` in `main`?

**Comment by jancavan** [comment]
In https://github.com/Automattic/wp-calypso/pull/9743/commits/bcec56ee31e45eb7a2ea22931b8ac87643d6cd79:

**Before:**
screenshot 2016-12-01 10 36 32

**After:**
screenshot 2016-12-01 10 37 19

If no "Back" button:
screenshot 2016-12-01 10 37 43

**Comment by fraying** [comment]
👏 Love it!

**Comment by bluefuton** [comment]
Looks great above 960px width! But still has a border and is a touch too high on narrower viewports:

screen shot 2016-12-02 at 11 46 12

**Comment by jancavan** [comment]
Good catch @bluefuton. Fixed in: https://github.com/Automattic/wp-calypso/pull/9743/commits/50520991a5ecc9f780191627a8f0afba51fe5074

screenshot 2016-12-01 15 56 25

screenshot 2016-12-01 15 56 21

@bluefuton Would it be easy to just move the back button inside the tag header itself? I'm not liking the relative positioning in each breakpoint. This solution works for now, but I'd like to eventually revisit it.

**Comment by bluefuton** [comment]
> Would it be easy to just move the back button inside the tag header itself?

Yep! We should just be able to shuffle `HeaderBack` into the header component.

**Pull request merged**
