### PR TITLE
Enable new migration instructions screen for everyone

### PR DESCRIPTION
**Pull request by renatho**
Related to #91815
Based off of #92766

## Proposed Changes

* Remove English check and open feature for any user.
* Remove old files.

## Why are these changes being made?

* We are waiting for translations to remove this check. When they are done, this PR will be deployed.

## Testing Instructions

* Change your language to something different than English (`https://wordpress.com/me/account `).
* Test the 3 flows, and make sure the new site instructions is properly displayed:
  * `http://calypso.localhost:3000/start`
  * `http://calypso.localhost:3000/setup/migration-signup`
  * `http://calypso.localhost:3000/setup/hosted-site-migration?from={FROM_URL}`

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Comment by renatho** [comment]
I'm already opening this for review, but it should be merged only when the new translations are complete. I'll check them July 25th.

**Comment by m1r0** [comment]
Hey, Renatho. It tests well, but could you solve the conflicts so I can re-test it again?

**Comment by renatho** [comment]
Thank you for the review, Miro!

> On the site picker screen (http://calypso.localhost:3000/setup/hosted-site-migration/sitePicker), the calypso_signup_actions_submit_step event is failing.

I noticed it's called in a few different parts of the codebase, so I preferred to not touch it and just open an issue, so it can be escalated to who has more knowledge about this part.

https://github.com/Automattic/wp-calypso/issues/92850

> On the site instructions page, the site preview image is not scrollable. This is a minor thing but it might be a nice touch.

It's expected now that we changed from an `iframe` to an `image`. We could take a bigger screenshot, but the problem is that we don't know the size of the sites, so if we have a scroll with an empty part, I think it would be more weird than a preview without a scroll. Make sense?

**Review by m1r0 — APPROVED** [review]
All good!

**Pull request merged**
