### PR TITLE
Fix quick action styling when jetpack is not connected

### PR DESCRIPTION
**Pull request by mpkelly**
Screenshot 2567-06-18 at 17 53 47

I stumbled upen this when testing a site with a broken Jetpack connection, which is currently the only way to reproduce it. As there is no connection, `activeThemeData` is unavailable, so there is no link, resulting in a `button` output instead of a `a`. The button does nothing so I have disabled it and fixed the styling. 

## Proposed Changes

https://github.com/Automattic/wp-calypso/assets/6851384/8d69197b-c585-41f1-b89e-f84091a645b3

* Fix styling and disable the button when no editor link is available. I used `opacity: .5` as that's common for `disabled` elements. 

## Testing Instructions

* I have a broken Jetpack site, but if you don't, you can null the `href` instead
* Reproduce then apply the PR and see it's fixed
* Verify other links continue to work

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Review by Addison-Stavlo — COMMENTED** [review]
Thanks for working at this @mpkelly ! Il also add a couple other teams to the reviewers for visibility here.

First thought: When we have a broken jetpack connection, I feel like we should be raising some larger flag or banner before this point to prompt getting that fixed? Im not sure what we currently do for users in this case, but it seems like we are fixing things for a scenario they shouldn't be in. Thats still great to fix it and cover our bases, this just makes me wonder if we do / should be doing something else in this disconnected case as well? 🤔 

Second thought: I kind of wish core could redirect non-block themes from the site editor to the customizer, and vice versa.. so we could just hardcode one url and have it magically cover all cases. Unfortunately it doesn't and I think there are probably some blockers to that idea.

WRT to the fix here, disabling the item makes sense to me. The one thing I am noticing is that for all sites we go through this disabled state on initial load (every time we load a new site in the overview panel):

flicker-jumpy

We see the color of the font change, but also the layout spacing jumps a little bit. If we can get rid of the spacing shifting here I think the rest of this would be fine.

**Comment by Addison-Stavlo** [comment]
Noting this bug was brought up in slack p1719843274282079-slack-C06DN6QQVAQ

**Comment by Addison-Stavlo** [comment]
So I noticed the button version `li` had 47 px height while the anchor version had 45px height. It looks like the layout differences were a result of both differing line-height (using the same line height changed this to 46px height) and display options (inline-flex instead of flex seemed to add an extra pixel in the height as well.

I pushed [116837a](https://github.com/Automattic/wp-calypso/pull/91890/commits/116837aaea9c42495c25d5d939a02d9f7ecd4999) to use the same styles for the anchor and button versions, which seems to get rid of the jumpyness and work well, and added the new disabled styles there as well.

This should be ready for another look.

Additional instructions:

* You will want to ensure the initial loading looks good and isnt jumpy. These values are cached so you may need to clear this to test.
* In browser dev tools clear the calypso indexedDB. (application tab -> indexedDB -> calypso -> right click and clear)
* Go to the sites dashboard and switch between a few sites in the overview (atomic sites may help to see this easier? unsure). Since the value is not cached we should see an initial loading state where the button is disabled before we can supply the HREF (gif below).
* Verify the transition from the disabled state of the button to the enabled state of the button does not shift the layout.

no-jump

Alternatively, you can inspect the dom, find one of the quick-links items and change one of the anchor elements into a button element. Verify the layout is good and that the element heights of `li`s using a's and buttons have the same height (45px including padding and margin)

**Review by davemart-in — APPROVED** [review]
Looks good in my testing. Here's a before/after:

**Before**

CleanShot 2024-07-01 at 11 21 52@2x

**After**

CleanShot 2024-07-01 at 11 22 52@2x

**Comment by mpkelly** [comment]
Thanks for updating and merging this PR, @Addison-Stavlo. 

>First thought: When we have a broken jetpack connection, should we raise some larger flag or banner before this point to prompt getting that fixed? 

You're right. We do have a banner, but you have to go to /home to see it. 

Screenshot 2567-07-02 at 06 29 14

In the new /sites flyout panel, maybe the same banner could be shown here:

Screenshot 2567-07-02 at 06 31 11

I see we have @davemart-in here. Do you have any objections to a follow-up PR (by me) that shows this banner in the location above? Alternatively, I can open a ticket somewhere, and a different solution can be considered.

**Comment by davemart-in** [comment]
> Do you have any objections to a follow-up PR (by me) that shows this banner in the location above?

No objections. I wouldn't put any other banners there, but this seems important enough to surface there.

**Pull request merged**
