### PR TITLE
Update FSE to version 1.3

### PR DESCRIPTION
**Pull request by p-jackson**
#### Changes proposed in this Pull Request

Deploys fixes for #41380 and #41793

* Version bump and changelog
* Updated "Tested up to" field to 5.4, since that's what we'll be testing this against.

Not a big list of changes, but still keen to deploy so #41793 can be fixed before the soft launch of gutenboarding.

#### Testing instructions

Instructions for deploying changes to sandbox and atomic: PCYsg-ly5-p2

Test that fixes are present #41380 and #41793

### CODE REVIEW

**Comment by frontdevde** [comment]
It would be great if we could get the changes in https://github.com/Automattic/wp-calypso/pull/41937 into this release as well.

It's an upstream dependency update for the `newspack-blocks` 1.5.0 release that fixes some of the issues that were logged in the Posts Carousel CfT (wp-p7DVsv-8An).

**Comment by noahtallen** [comment]
I also know @eoigal and @ianstewart are merging some plugin changes soon

**Comment by obenland** [comment]
#41822 should be going in momentarily as well

**Comment by ianstewart** [comment]
We also have https://github.com/Automattic/wp-calypso/pull/41893

**Comment by jeryj** [comment]
Merged https://github.com/Automattic/wp-calypso/pull/41893. Adds a few new block patterns and sets their order.

**Comment by obenland** [comment]
Rebased to include #41822.

**Comment by andrewserong** [comment]
I've just done one final rebase to include https://github.com/Automattic/wp-calypso/pull/41901 and updated the readme with all the changes include in this release.

I'll do some smoke testing on this version, and aim to merge it in and deploy within the next hour or two.

**Comment by andrewserong** [comment]
All deployed now and to .org: https://wordpress.org/plugins/full-site-editing/#developers 🎉

**Pull request merged**
