### PR TITLE
Jetpack Plans: add new features to features table

### PR DESCRIPTION
**Pull request by johnHackworth**
This PR adds the two new jetpack plans features to the features table:

image

image

How to test
========
1. Go to https://calypso.live/plans/?branch=add/jeptack-plans-new-features and select a jetpack site
2. Go to http://calypso.live/jetpack/connect/vaultpress?branch=add/jeptack-plans-new-features
3. In both places, you should see videopress support & "monetize your site" as features for the business and pro plans, both in the yearly and in the monthly versions

### CODE REVIEW

**Comment by johnHackworth** [comment]
@richardmuscat  ^

**Comment by richardmuscat** [comment]
❤️

**Comment by oskosk** [comment]
Works as expected. LGTM

**Comment by tyxla** [comment]
I've tested this as well, works just as described 👍

**Comment by johnHackworth** [comment]
This will be punted and not be merged until jetpack 4.5 is released (it was intended for today's release, but it has been delayed a couple of weeks)

**Comment by lancewillett** [comment]
@johnHackworth This needs conflict resolution maybe... pending upcoming Jetpack 4.5 launch.

**Comment by johnHackworth** [comment]
@lancewillett  yup, I will let this as "in progress" until we have a date for jetpack 4.5 release and I'll fix the conflicts the day before so we can merge it once it's out. Thanks for noticing!

**Comment by richardmuscat** [comment]
@johnHackworth: as JP 4.5 is due to go out tomorrow we need to get back to this. I looked at the live branch again and it looks good, but I'd also like to make a few small additional changes:

- [ ] Remove the "Advanced Polls and Ratings" item from the Professional plan
- [ ] Change the text description of Premium Plan (see below)
- [ ] Change the text description of Professional Plan (see below)
- [ ] Needs to take into account that we changed the position of "Priority Support" and also included it in the Personal Plan column

**New text for Premium Plan**

> ~~Advanced security features to keep your site safe and sound. With daily backups, malware scanning, and spam defense.~~

> Generate income and save on video hosting costs. Improve security with daily backups, malware scanning, and spam defense.


**New text for Professional Plan**

> ~~More powerful security tools, including malware removal and realtime content backup, for the ultimate peace of mind.~~

> Real-time backups, unlimited archives, and one-click threat resolution. Also includes SEO tools, and unlimited video hosting.

**Comment by johnHackworth** [comment]
ok, new version: 
image

**Comment by richardmuscat** [comment]
@johnHackworth noticed also that we are incorrectly displaying Google Analytics in the Pro col. This needs to go.

Most likely I had asked you to include it before it was decided to delay that feature until 4.6 next month

**Comment by johnHackworth** [comment]
@richardmuscat oh, that's there only because the screencap is from my local environment, and google analytics is whitelisted there. It won't show on production (it's under a feature flag)

**Pull request merged**
