### PR TITLE
NpsSurvey: migrate CSS to webpack and remove always-true feature flag

### PR DESCRIPTION
**Pull request by jsnajdr**
How to test:
- go to Calypso with `?flags=nps-survey/dev-trigger` query string
- type `npsSurvey()` in console
- verify that the dialog styling is OK

### CODE REVIEW

**Comment by blowery** [comment]
From the diff, it appears this was _not_ set to true on desktop? I'm guessing that's just oversight, but we may want to validate this this works acceptably on desktop.

**Comment by jsnajdr** [comment]
That's true, the NPS survey apparently wasn't showing on Desktop. But is there any reason not to? It's a very simple "rate us on a 1-10 scale" popup.

**Comment by blowery** [comment]
> But is there any reason not to? 

I don't think so? How does it capture the response and submit the form?

**Comment by jsnajdr** [comment]
> How does it capture the response and submit the form?

It's all React UI and REST API requests. I don't know why you're asking about this specifically, but there are no embeded iframes or form submission with navigation to another page or anything like that.

**Comment by jsnajdr** [comment]
@blowery I just tested the NPS survey UI in Desktop/Electron and it works flawlessly. Responses are sent to a REST endpoint (`/rest/v1.2/nps/...`)

**Review by blowery — APPROVED** [review]
👍

**Pull request merged**
