### PR TITLE
eslint-plugin-wpcalypso: Add rule `i18n-translate-identifier`

### PR DESCRIPTION
**Pull request by yuliyan**
Related to 560-gh-Automattic/i18n-issues

## Proposed Changes

Add new rule `i18n-translate-identifier` in `eslint-plugin-wpcalypso` to check whether the identifiers of the variables referring to translate functions from `i18n-calypso` and `@wordpress/react-i18n` match the original translation function name.

The reason why translate functions should not be aliased is because string extraction tools are based on static code analysis and thus expect the original translate function names. 

## Testing Instructions

* Code review.
* Run tests for the new `i18n-translate-identifier` rule with `node packages/eslint-plugin-wpcalypso/lib/rules/test/i18n-translate-identifier.js`

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

**Comment by sdnunca** [comment]
image
I'm getting no output when running the tests. Am I doing something wrong?

**Comment by yuliyan** [comment]
> image I'm getting no output when running the tests. Am I doing something wrong?

@sdnunca, it only outputs the errors. I'm not sure if that's the correct way of running the tests, but I couldn't find anything else.

**Review by noahtallen — APPROVED** [review]
This tested well for me in my IDE. I'd recommend expanding the message to explain why it needs to be these variables, but that's non-blocking

**Review by dlind1 — APPROVED** [review]
LGTM! I ran the tests with `yarn run test-packages packages/eslint-plugin-wpcalypso/lib/rules/test/i18n-translate-identifier.js` and got:
Screenshot 2023-02-17 at 00 44 37

**Comment by yuliyan** [comment]
Updated the error message and added docs for the new rule.

Failing e2e tests are unrelated, so I'll proceed with merging the PR.

**Pull request merged**
