### PR TITLE
Add ccTLD Support

### PR DESCRIPTION
**Pull request by deBhal**
This PR updates the Domains UI to improve support for `.ca`, `.de` and `.fr` Top Level Domains, and aims to make it easier to accommodate more TLDs in the future.

Different TLDs, especially country code, can have quite varied requirements. To support the three mentioned, we need to support:

- Free Privacy that defaults on
- Whois privacy being unavailable
- Asking users to scroll through and then acknowledge the CIRA agreement before registering (for `.ca`)
- Additional fields (for `.fr`) that depend on the value of another field ( individuals need to provide personal details, while organizations need to supply tax details)
- "presence" requirements (addresses within a specific area for each domain)

In addition, there is significant duplication of functionality between `my-sites/upgrades/checkout/` (buying domains) and `/domains/manage/*` (managing domains). This complicates upgrading the code, so we want to unify these components as much as possible.

### CODE REVIEW

**Comment by deBhal** [comment]
The DomainDetailsForm seems the most recalcitrant, so I'm starting there, trying to figure out what I need to put in the UI, and what the API should be sending through.

One interesting problem is conflicting constraints, like if two domains have presence requirements in incompatible locations.

To start with, I'm thinking about a very simple system where we attach any special requirements to fields as messages for the user, and push the burden of resolving conflicts onto the user and provide the blunt instrument of adding additional addresses:
checkout_ _julesauspremiumtest_ _wordpress_com

**Comment by wensco** [comment]
@deBhal based on your mock-up of the contact form, it looks like you're proposing to allow a registrant to have more than one physical address. Is that right?

**Comment by klimeryk** [comment]
While being compliant with all the requirements is of course very important, we should be very careful when making changes to this form. It's already causing many users to abandon the purchase. Have you consulted the changes you want to implement with a designer?

**Comment by deBhal** [comment]
> @deBhal based on your mock-up of the contact form, it looks like you're proposing to allow a registrant to have more than one physical address. Is that right?

@wensco: I was been thinking that, without realizing that we might be limited in that area. All three domains we're looking at have presence requirements for different regions, but if we have to say "only one" then users are still better off than they are now (only having to map one domain instead of two), so multiple addresses would be nice, but is not an important requirement.

> we should be very careful when making changes to this form. It's already causing many users to abandon the purchase. Have you consulted the changes you want to implement with a designer?

@klimeryk: Good point! Getting design input is already on our radar, but the focus is the technical challenges right now. Is there someone already working on the UX around domains that would be good to reach out to?

**Comment by yoavf** [comment]
Reiterating here that getting the registration form to handle multiple ccTLDs at once is at the bottom of the priority list.

**Comment by wensco** [comment]
@deBhal thanks for the reply. :) 

I don't think it will be feasible for us to allow users to list multiple physical addresses for a domain. We don't currently have a way to store that internally (which can be fixed) but the bigger issue is that I don't think this is a good solution for a variety of reasons, including the points @klimeryk mentioned (pinging @mikeshelton1503 for design input since @breezyskies is afk). Given that there are various regulations that apply based on a registrant's country of residence, having multiple physical addresses muddies things.

Perhaps a different option would be to add a validation check based on the ccTLD and highlight address and phone fields on the contact form with a message that [example.ccTLD] has specific residency requirements. We could perhaps create a support page with the details and link to it instead of listing the requirements inline since that can be cumbersome.

In the event that a user wants to purchase more than one domain with different residency requirements, we may have to display a contact form for each domain. It would be worth taking a look to see how other registrars handle this sort of thing. HTH!

**Comment by mikeshelton1503** [comment]
>Good point! Getting design input is already on our radar, but the focus is the technical challenges right now. Is there someone already working on the UX around domains that would be good to reach out to?

@deBhal Feel free to ping me for any design questions/feedback. I second @klimeryk and @wensco thoughts about so I'll withhold any feedback for you now to see where we head with this next.

**Comment by hewsut** [comment]
Chiming in here on the contact thing as I'm being pulled into this space -- I too lean toward an address form per ccTLD when that's necessary vs doing anything additional to the existing UI because that should scale "easily" horizontally.

Tacking on sequential contact forms is somewhat at the user's expense, but 1) I don't think it has to be too awful with some smart pre-filling, 2) probably won't happen too often anyways, and 3) should be less complicated for us to build than any sort of address book-y/multiple contact selector setup.

**Comment by klimeryk** [comment]
> Getting design input is already on our radar, but the focus is the technical challenges right now.

That's what I gathered, but IMHO it should be the other way around :) As can be seen from this ongoing discussion, how you proceed to design this flow has a huge impact on how it will have to be implemented (and how hard it will be, given our current flow/implementation). Checkout is an area that has been heavily tested in the past and it'd be a shame not to pick @mikeshelton1503's brain ;)
The outcome might that we don't need to change the contact form at all (for example, if it will be decided that we're sticking to one address per purchase or @hewsut's idea).

**Comment by deBhal** [comment]
We discussed this more, and we've tried the build-a-form approach in this PR before, and it wasn't good, so I'm going to close this and try a different direction.

**Pull request closed without merging**
