### PR TITLE
Move Dialog and RootChild to the components package

### PR DESCRIPTION
**Pull request by jsnajdr**
After `RootChild` got rid of its Calypso-specific dependencies in #32899, both `Dialog` and `RootChild` are ready to become nice additions to `@automattic/components`.

I updated all imports instead of creating stubs in `client/components`.

### CODE REVIEW

**Review by sirreal — APPROVED** [review]
Thanks! I don't see any issue pending e2e passing.

I haven't done any smoke testing, I'll leave that to e2e.

When building the app locally, I don't get any missing import warnings, so the updated imports should be good 👍

**Review by ockham — CHANGES_REQUESTED** [review]
Thanks Jarda! :tada:

Could you mention the newly added components in the package's Changelog please? (Under the `@automattic/components 1.0.0` heading, we haven't released that version yet, only an alpha.)

**Comment by jsnajdr** [comment]
@ockham I added a mention into the changelog. Please review and approve, so that I can keep deploying 😉

**Review by ockham — APPROVED** [review]
Thanks Jarda! :ship:

**Pull request merged**
