### PR TITLE
Framework: Remove CSS modules

### PR DESCRIPTION
**Pull request by drewblaisdell**
This reverts all of the commits from https://github.com/Automattic/wp-calypso/pull/10590 and https://github.com/Automattic/wp-calypso/pull/11185

### CODE REVIEW

**Comment by drewblaisdell** [comment]
`renderPage` is used in `/me/purchases/controller` and `/my-sites/site-settings/controller` but this PR reverts changes to the order of parameters and the latter uses a different `renderPage` function entirely.

**Comment by ehg** [comment]
Looping in @alisterscott

**Comment by alisterscott** [comment]
Tested locally and LGTM 👍

**Comment by mtias** [comment]
Thanks for taking care of this!

**Pull request merged**
