### PR TITLE
PatternPicker: migrate to use swiperjs

### LINKED ISSUE #67679: Task: Link in bio - Investigate using Swiperjs (or any good lib) for pattern picker
### Details

The pattern picker is still laggy unsmooth on some devices :( 

Consider using https://swiperjs.com/react or https://iscrolljs.com/ or any library that does it well.

### Checklist

_No response_

### Related

_No response_

### PR DESCRIPTION
**Pull request by heavyweight**
#### Proposed Changes

* To mitigate some of the issues of the pattern picker it was suggested to investigate using swipperjs
* This PR wires swiperjs with the pattern picker to provide the same visual experience as before minus the issues

#### Testing Instructions
- Checkout this branch
- Run `yarn start`
- Visit the link in bio flow
- Go to the patten picker step
- Compare visually against production to detect inconsistencies
- Test using different viewports and devices

Related to #67679

### CODE REVIEW

**Comment by heavyweight** [comment]
brought this back from draft since the etk errors is not related to the PR
seems that the new version published for `@automattic/newspack-blocks` `1.57.0` is causing PHP lint errors

**Comment by escapemanuele** [comment]
I don't really understand why now, but there are random moments when it doesn't go in the right direction 🤔 
https://user-images.githubusercontent.com/52076348/191035755-4c2dc95f-f70c-4b3b-bb36-0bef3e6908a8.mov

**Comment by renancarvalho** [comment]
@escapemanuele, Interesting that you also faced it. I noticed it but It was very random and I had difficulties to record a video with it. Then I realizes that maybe I was doing a very little scroll instead of a click with my track pad... perhaps it is the same for you? In any case I think it is an issue.

**Comment by escapemanuele** [comment]
@renancarvalho In my case I'm using a magic mouse and just clicking around, no scrolling! Anyway it seems really random 🤔

**Comment by heavyweight** [comment]
@escapemanuele I reproduced the issue and changed the config to handle this.
Switched to use native slide on click and added a threshold value.
The threshold value should prevent this from happening. Basically, a swipe was detected with the click and it lead to the unpredictable behavior

**Comment by escapemanuele** [comment]
Thank you @heavyweight!
I see there are problems with Unit tests, could you take a look? 😄

**Comment by heavyweight** [comment]
> Thank you @heavyweight! I see there are problems with Unit tests, could you take a look? 😄

I'm aware of it.
ATM this PR is not mergeable. Was just wondering if the glitch is gone for you?

Fails for the same reason as https://github.com/Automattic/wp-calypso/pull/67870#issuecomment-1249386734
Even though bumped the library to the latest version. This has to be fixed for sure before merging...

**Comment by heavyweight** [comment]
Work continued on https://github.com/Automattic/wp-calypso/pull/68840

**Pull request closed without merging**
