### PR TITLE
Onboarding: Adjust styles according to design feedback

### PR DESCRIPTION
**Pull request by arthur791004**
#### Changes proposed in this Pull Request

As design feedback EuqfSnWpfYx8fgiBlVmbuA-fi-2875%3A1519, adjust styles as followed:
* Replace illustration image and add margin-top to the content for both of intent and give your blog a name
* Intent
  * styles of button
  * opacity of separating line
* Give your blog a name
  * styles of the label, input, and tips
  * styles of button
* Design preview
  * margin-top of title

#### Testing instructions

* Go to `/start/setup-site?siteSlug=<your_site>&flags=signup/hero-flow`
* Check the design in each page 

Related to https://github.com/Automattic/wp-calypso/issues/55603, https://github.com/Automattic/wp-calypso/issues/56957

### CODE REVIEW

**Comment by roo2** [comment]
Everything LGTM I think we just need to add margin top on the site-options step
Screen Shot 2021-10-13 at 3 17 50 pm
.

**Comment by arthur791004** [comment]
@roo2 Hmmm...it looks strange that I already added margin-top to site-options 🤔 Let me check

**Comment by arthur791004** [comment]
Oops...I only add to intent screen 😅

**Review by roo2 — APPROVED** [review]
LGTM!

**Pull request merged**
