### PR TITLE
Full Site Editing: Update Site Description block attributes

### LINKED ISSUE #36604: Full Site Editing: Add styling options to the Site Description block
Currently, the Full Site Editing's Site Description block doesn't have any styling options (except the wide/full block width), and simply reuses the theme CSS `.site-description` class styles.

We should keep the theme CSS as default and fallback, but also let the user set their own styling options, like they already do for other blocks like Heading or Paragraph.

In particular we should allow:
- Text alignment (not the same as "block alignment", e.g. wide/full).
- Font size (predefined list and custom).
- Text color (theme palette and custom).
- Background color (theme palette and custom).

And we should prevent:
- Markup (unsupported by default in the site description).
- Multiline (hitting enter should create and focus a paragraph after the block).

### PR DESCRIPTION
**Pull request by Copons**
#### Changes proposed in this Pull Request

* Replace `PlainText` with `RichText` in the Full Site Editing's Site Description block.
* Add visual styling attributes:
  - Text alignment (separate from block alignment)
  - Font size (predefined list and custom)
  - Text color (palette and custom)
  - Background color (palette and custom)

This change, along with #36675 and Automattic/themes#1500, removes the hardcoded styling of the Site Title and Description blocks, allowing the user to customize them in the Block Editor, in roughly the same way as the Heading and Paragraph block respectively.

| Editor | Front End |
| - | - |
| Screenshot 2019-10-08 at 15 13 43 | Screenshot 2019-10-08 at 15 13 58 |

(Please disregard the Site Title font size difference, it's not related to this PR.)

#### Testing instructions

* Apply this change on an FSE site.
* Edit a template and make sure the Site Description block has all the options listed above.
* If you also want to visually see all the changes, also apply https://github.com/Automattic/themes/pull/1500.
Otherwise, just check that the rendered block has all the expected classes and styles.

Fixes #36604

### CODE REVIEW

**Comment by noahtallen** [comment]
Looking like great progress!!

> that the height of the textarea is automatically calculated

So when I initially set the background color of the description block, it got super narrow until I refreshed the page, which is definitely weird. Honestly, I think RichText would be better even not having onEnter support.

Screen Shot 2019-10-08 at 11 01 21 AM

Also, I see that the Title is aligned strangely in the editor. I guess that will be handled in a followup once alignment options are added to that block?

Also, will we have to update the demo site template data to make sure that the alignment option is included in the block metadata?

**Comment by Copons** [comment]
> > that the height of the textarea is automatically calculated
> 
> So when I initially set the background color of the description block, it got super narrow until I refreshed the page, which is definitely weird. Honestly, I think RichText would be better even not having onEnter support.

Yeah, today I'll give `RichText` another try, maybe nagging some Core folks. 🙂
TBH replacing `PlainText` with `RichText` is not a big deal per se, and most of the props would remain the same, so I'd love to figure out a good way to handle the newline in this PR.

> Screen Shot 2019-10-08 at 11 01 21 AM
> 
> Also, I see that the Title is aligned strangely in the editor. I guess that will be handled in a followup once alignment options are added to that block?

The theme PR removes the overrides from both Site Description and Site Title, but of course there is no Title PR yet (the idea is to finalize this and then basically copypaste everything into Site Title).

I plan to keep the theme PR on hold until we are ready to update the plugin, and deploy both sides at the same time.

> Also, will we have to update the demo site template data to make sure that the alignment option is included in the block metadata?

No need, the text alignment attribute defaults to `center`.
(But again, Site Title doesn't have this yet, so it automatically aligns to the left)

**Comment by Copons** [comment]
@noahtallen I've accidentally stumbled upon the trick for the newline! 😅

`RichText` doesn't accept `onKeyDown` as prop, so we can't listen to the keyboard event.
Instead, it uses two methods whose names didn't resonate with me enough: `onSplit` and `onReplace`.
`onSplit` is triggered when the content is split in "segments", for example after an `ENTER` and it's used to decide what to do with these segments. Typically, segments with value will be put in the same block type, while empty segments in a new Paragraph block.
`onReplace` is usually inherited from `BlockListBlock` and simply replaces the current single block with all the blocks containing the various segments.

I did try using `onSplit` but I didn't notice the fine print in the readme, telling me that it only worked if `onReplace` was defined as well.

So, now, my approach here is very simple: `onSplit/onReplace`, instead of doing any fancy replacements, we just insert a new default (Paragraph) empty block. Exactly as we did before in `PlainText` while listening to `ENTER`.
This is not the perfect solution, but it's the simplest.

The perfect solution would entail poking around `onSplit` and `onReplace`, making sure that only the first segment will remain a Site Description, while the others will be converted into a Paragraph.
Unless I'm missing something very obvious, it's not as simple as it sounds.

Should we really want it we could tackle it in a follow up, but at this point I'd probably _punt to Core_ 😛

**Comment by noahtallen** [comment]
I think that's an awesome way to handle it, especially if behavior is the same :D

**Comment by Copons** [comment]
> especially if behavior is the same

@noahtallen Yeah I've tried some edge-ish cases, and the new Site Description behave in the same way as the old Site Title.

**Comment by Copons** [comment]
(Btw this is ready for another review! 🙂)

**Comment by apeatling** [comment]
Confirmed that alignment works correctly once I used this theme branch: https://github.com/Automattic/themes/pull/1500

**Comment by Copons** [comment]
Thanks for the reviews!

I'm putting this on hold in order to replicate these changes for the Site Title block as well, and then ship both together along with https://github.com/Automattic/themes/pull/1500 at the same time to avoid visual regressions and inconsistencies.

**Pull request merged**
