### PR TITLE
Check if ETK is disabled using a site option

### PR DESCRIPTION
**Pull request by jsnajdr**
This PR reimplements the "is Editing Toolkit disabled on an Atomic site" checks from #47569.

It's a part of the `InlineHelp` extraction experiment in #55189 and removes one of Redux dependencies (`state.plugins`) of the `SiteSelector` component.

Companion PR for the server D65864-code patch that updates the `is_coming_soon` site option calculation and adds a new `editing_toolkit_is_active` site option.

When displaying the "Coming Soon" badge on a site, we use the updated `is_coming_soon` site option, where the server itself does the editing-toolkit-disabled check and sends `false` value when ETK is indeed disabled. Thanks to that, we don't need to do any additional check (and plugin info fetching) in Calypso. The `is_coming_soon` option value is the entire truth.

In Settings > General for an Atomic site, we want to disable the "Coming Soon" privacy option when ETK is disabled. To do that, we use the new `editing_toolkit_is_active` site option. Again, only the `state.sites` Redux subtree is needed for that, and we don't need to depend on `state.plugins`.

**How to test:**
- apply the D65864-code patch to your sandbox and sandbox `public-api.wordpress.com`
- start Calypso with this PR applied
- switch your Atomic site into a "Coming Soon" mode and then disable ETK
- in the site selector, verify that the Atomic site _doesn't_ have the "Coming Soon" badge
- in Settings > General, verify that the "Coming Soon" privacy option is not available when ETK is disabled
- after enabling ETK again, verify that "Coming Soon" badge is back and that the "Coming Soon" setting is available in settings

### CODE REVIEW

**Review by ramonjd — APPROVED** [review]
This works as described. Thank you for making this feature leaner! 🙇 

✅ apply the D65864-code patch to your sandbox and sandbox public-api.wordpress.com
start Calypso with this PR applied
✅ switch your Atomic site into a "Coming Soon" mode and then disable ETK
✅ in the site selector, verify that the Atomic site doesn't have the "Coming Soon" badge
in Settings > General, verify that the "Coming Soon" privacy option is not available when ETK is disabled
✅ after enabling ETK again, verify that "Coming Soon" badge is back and that the "Coming Soon" setting is available in settings

**Comment by andrewserong** [comment]
This is testing nicely for me, too, thanks @jsnajdr! I needed to reload the settings page for my test Atomic site a couple of times before it picked up the new setting, which meant that after deactivating and re-activating the ETK plugin, my site was in Coming Soon mode for a little while but the settings page showed that it was set to Public. After reloading, I couldn't recreate the issue, so I imagine it was just the old settings being cached in the browser. I haven't been able to recreate the issue since.

**Comment by ramonjd** [comment]
> After reloading, I couldn't recreate the issue, so I imagine it was just the old settings being cached in the browser. I haven't been able to recreate the issue since

I noticed this too, but in my testing the badge and setting does update if you stare at your screen for a few seconds longer.

If it makes you feel any better, I think this is way it's always been. I noticed this behaviour [a while back](https://github.com/Automattic/wp-calypso/pull/48153). I assumed at the time it was an option race (between public and coming soon) but still not sure.

**Comment by andrewserong** [comment]
Thanks for confirming, Ramon! Sounds like it isn't a blocker for this PR 🙂

**Comment by jsnajdr** [comment]
> I needed to reload the settings page for my test Atomic site a couple of times before it picked up the new setting

The "is plugin active" check is done by looking at the Jetpack shadow data on WP.com servers, and these need to be first synced from the actual Jetpack/Atomic site to WP.com. So it's expected that there is some delay before the information propagates.

The old implementation should have the same behavior: the `/sites/:site/plugins` endpoint also looks at the shadow database.

**Comment by andrewserong** [comment]
> So it's expected that there is some delay before the information propagates.

Excellent, thanks Jarda!

**Pull request merged**
