### PR TITLE
data-stores: Add missing properties to SiteDetails type

### PR DESCRIPTION
**Pull request by sirbrillig**
#### Proposed Changes

The `SiteDetails` TypeScript type in the `@automattic/data-stores` package appears to be the same type referred to by [SiteData](https://github.com/Automattic/wp-calypso/blob/2d6bf7416c800955578f831a3131fb1c407db6f1/client/state/ui/selectors/site-data.ts#L3) and [SitesItem](https://github.com/Automattic/wp-calypso/blob/2d6bf7416c800955578f831a3131fb1c407db6f1/client/state/selectors/get-sites-items.ts#L6). However, all three types have properties missing from the others.

This PR adds all properties from the other two types to the `SiteDetails` type because, as a type defined outside of the calypso package, it seems like the natural place for an authoritative definition. Future PRs (https://github.com/Automattic/wp-calypso/pull/66729) could migrate the other types to `SiteDetails`, but that will not be an easy task.

By filling out the `options` record, this allows us to use `SiteDetails` in other places like https://github.com/Automattic/wp-calypso/pull/66778 and https://github.com/Automattic/wp-calypso/pull/66779

#### Testing Instructions

Make sure all tests pass.

### CODE REVIEW

**Review by alshakero — APPROVED** [review]
Thanks a lot!

**Review by alshakero — COMMENTED** [review]
I think it's worth running `Sort Lines Assending` in VS code on these props to sort them alphabetically. <kbd>cmd</kbd> + <kbd>P</kbd> `> Sort Lines Assending`.

**Review by taipeicoder — APPROVED** [review]
Nice refactor! 🙂

**Comment by sirbrillig** [comment]
> I think it's worth running Sort Lines Assending in VS code on these props to sort them alphabetically. cmd + P > Sort Lines Assending.

Thanks! I did already sort them (using `:sort` in vim) but I'll double-check that things didn't get out of place.

**Comment by sirbrillig** [comment]
The failing e2e test (clicking the "Renew now" button at mobile width for an expiring plan) is [known](https://github.com/Automattic/wp-calypso/pull/66813) and is not an issue.

**Pull request merged**
