### PR TITLE
Marketplace: Adds usePlugins hook

### PR DESCRIPTION
**Pull request by Rolilink**
#### Changes proposed in this Pull Request

* Adds the `usePlugins` hook to encapsulate the `wpcom` and `wporg` plugins fetching logic.

#### Testing instructions

* Smoke test the marketplace, everything should work fine.

Related to:
#63256
#62935

### CODE REVIEW

**Review by lsl — COMMENTED** [review]
Will test when you're ready for it but the direction you're going here looks really good.

It's quite a big change but I don't think its worth breaking down smaller, needed to happen.

I like that you've left the complexity of juggling different query types in there as is but just moved it all into the hook, makes testing and approving such a big change much easier. Nice work.

Is there anything more to do? Looks like it might be ready to ship after testing.

**Review by lsl — APPROVED** [review]
Didn't want to block you merging tomorrow so giving it a quick test now, all looks good, noticed one small surface bug in the plugin result count that needs a fix before merging:

https://user-images.githubusercontent.com/811776/166915814-1fb68744-ed42-45b9-bc67-f1196d21f33b.mp4

**Comment by Rolilink** [comment]
Added @gcsecsey as a reviewer since he is working on something related.

**Comment by Rolilink** [comment]
This works really fine as a initial refactor but I think we can add the filtering of blocked plugins here as well.

**Review by lsl — APPROVED** [review]
Lets do that in a follow up.

**Pull request merged**
