### PR TITLE
Hide Unseen Count in Reader

### LINKED ISSUE #57015: Reader: Unseen post count does not decrease after reading posts
### Quick summary

After reading a post from a followed blog in Reader, the count of unread posts does not decrease.

### Steps to reproduce

1. Go to wordpress.com/read with at least one blog followed, and choose a feed to read.
2. Read posts: scroll through the reader, click on a post to open it and read it in full, etc.

### What you expected to happen

The number of unread posts in that feed/all feeds should go down.

### What actually happened

Reading the post does not mark the post as seen/gray it out, and the unread count on the left never goes down.

### Context

4364364-zen

All of the HEs who have worked on the ticket so far are able to replicate this while logged in as this user. One HE also noticed this on his account; I don't notice it with my own A8C account. (I also see that I have additional options for manually marking posts as seen. Are general users supposed to have those? If they are, the user in the ticket does not.)

I can replicate when I log into a non-A8C personal account, however—no controls for marking posts as seen, and my unread count doesn't go down when I read a post.

### PR DESCRIPTION
**Pull request by arcangelini**
#### Changes proposed in this Pull Request

* Add checks to the reader sidebar "Followed" tab to hide unseen count for non-eligible users.
* This uses the `isEligibleForUnseen` method to check if the user should be able to see the unseen count. 

#### Testing instructions

* Go to http://calypso.localhost:3000/read and login with an A8C account
* Click 'Following' tab and verify the counts are all visible
* Log out and log in again as a NON-A8C user
* Click 'Following' tab and verify the counts are *NOT* visible

#### Screenshot

**NON**
Markup 2021-11-20 at 19 03 23

**A8C**
Markup 2021-11-20 at 19 03 04

Related to #57015

### CODE REVIEW

**Review by yansern — APPROVED** [review]
Apologies for the late review. Rebased and retested. I'm approving this PR as this PR works as described.

However, I have concerns as this doesn't really fix the real issue where unseen counts are not working for end users, my understanding from p9lV3a-1UT-p2 is that unseen counts are unavailable for the public due to concerns on load issues. I guess rather hide it than ship something broken until seen counting is working for all users.

**Comment by yansern** [comment]
@unDemian and @aerych, any thoughts on this PR based on the prior discussions on p9lV3a-1UT-p2#comment-2717?

**Comment by unDemian** [comment]
Sorry for the late response I was AFK.

> However, I have concerns as this doesn't really fix the real issue where unseen counts are not working for end users, my understanding from p9lV3a-1UT-p2 is that unseen counts are unavailable for the public due to concerns on load issues. I guess rather hide it than ship something broken until seen counting is working for all users.

I think there are two issues here, the regression that shows unseen counts to all users which is fixed by this PR. 
On the other hand we have the issue described here https://github.com/Automattic/wp-calypso/issues/57015#issuecomment-985644722 for which we started getting reports a couple of weeks ago. We are working with systems on a fix, but it might take a couple of weeks as we have to retroactively fix all data going back 18 months.

If you think that hiding the unseen counts for everybody makes sense go for it, I would say that even though a bit broken if it is only displayed to P2 users and automatticians and considering the fact that the decreasing bug is not affecting all cases we could keep it around and in a couple of weeks all visible counts would be fixed and properly decreasing.

**Comment by arcangelini** [comment]
Thanks @unDemian, to clarify this PR only hides the unseen count for `All Sites` it doesn't hide it on P2s or A12s. From my testing, the unseen count is working properly in these places. Given the poor user experience most WordPress.com users would have I feel like it may be best to hide this. Unless you think the Calypso Reader Unseen Counts is on the horizon (a couple of weeks away) of being launched to `All Sites`. In which case we could just update the GH issue to let the users know.

But please correct me if I am wrong @yansern and @unDemian : )

**Comment by unDemian** [comment]
> Unless you think the Calypso Reader Unseen Counts is on the horizon (a couple of weeks away) of being launched to All Sites. In which case we could just update the GH issue to let the users know.

Unfortunately, I don't think that will happen in the near future as our focus has shifted away from improving the Reader. I would say we can safely hide them for All Sites for now.

**Review by unDemian — APPROVED** [review]
Looks great, thanks for tackling this.

**Pull request merged**
