### PR TITLE
Reader: Whitelist me.sh

### PR DESCRIPTION
**Pull request by blowery**
This allows the me.sh iframe to work.

### CODE REVIEW

**Comment by blowery** [comment]
test site: https://wordpress.com/read/blogs/77147075

vs http://calypso.localhost:3000/read/blogs/77147075

**Comment by blowery** [comment]
me.sh shows the first picture without the whitelist, but the full gallery works with it.

**Comment by blowery** [comment]
cc @mkaz

**Comment by mkaz** [comment]
Awesome! 👍

**Comment by bluefuton** [comment]
:ship:

**Comment by TooTallNate** [comment]
The JavaScript in the iframe appears to be being blocked so the gallery doesn't work. Intentional?

**Pull request merged**
