### PR TITLE
Update/improved getSitesItems selector

### PR DESCRIPTION
**Pull request by jorgefilipecosta**
This PR makes 2 improvements to getSitesItems selector proposed in PR's https://github.com/Automattic/wp-calypso/pull/17364 and https://github.com/Automattic/wp-calypso/pull/17694.

1. Updates the automated tests to use an Id different from 1 because using 0 or 1 as test value may lead to false positives as they are the default numbers for many algorithms.

2. Change selector to use a static shared frozen empty object because it avoids creating objects frequently, and may improve caching on dependent memoized selectors.

Thank you @dmsnell and @aduth for the inputs that orgined this PR.

Use cases:
This selector is going used in PR #17364.

To test:
This PR just updates a selector that is not used yet so executing automatic tests that include this selector should be enough.
npm run test-client client/state/selectors/test

### CODE REVIEW

**Comment by dmsnell** [comment]
Thanks for circling back on this - I like the changes! ✅

**Comment by jorgefilipecosta** [comment]
Thank you for your review @dmsnell!

**Comment by lancewillett** [comment]
Hi @jorgefilipecosta — is this one ready to merge?

**Comment by jorgefilipecosta** [comment]
Hi @lancewillett as it does a small change in tests and given that today there were big changes, I  will rebase it and test it again, before merging. I don't expect any change to be required.
Right now, I already have the permissions to deploy so after the tests I will land this PR.

**Pull request merged**
