### PR TITLE
Sites Management Page: optimise banner that promotes tailored flows

### LINKED ISSUE #68760: Sites Management Page: add support for promoting tailored flows - additional improvements
### Details

This issue will address something remaining requirements that were discussed in PR https://github.com/Automattic/wp-calypso/pull/68483

### Checklist

- [ ] Optimise images, so they load faster on slow networks. See [here](https://github.com/Automattic/wp-calypso/pull/68483#pullrequestreview-1130930739). 
- [ ] Change banner type according to available space: double-tile should become tile. See [here](https://github.com/Automattic/wp-calypso/pull/68483#issuecomment-1268852466).
- [ ] Don't show the banner when it wraps onto a line by itself. See [here](https://github.com/Automattic/wp-calypso/pull/68483#pullrequestreview-1130930739).

### PR DESCRIPTION
**Pull request by mpkelly**
Fixes https://github.com/Automattic/wp-calypso/issues/68760

#### Proposed Changes

- [x] Optimise images, so they load faster on slow networks. See [here](https://github.com/Automattic/wp-calypso/pull/68483#pullrequestreview-1130930739). 
- [x] Change banner type according to available space: double-tile should become tile. See [here](https://github.com/Automattic/wp-calypso/pull/68483#issuecomment-1268852466).
- [x] Don't show the banner when it wraps onto a line by itself. See [here](https://github.com/Automattic/wp-calypso/pull/68483#pullrequestreview-1130930739). 

#### Testing Instructions

Note: I've included the temporary URL param again for this PR: you can control the site count with `?sitecount=<number>`

* navigates to `/sites` without a Link in Bio site as one of your sites
* You can simulate slow networks with Chrome. I set up a 4G profile and used that. (see [comment](https://github.com/Automattic/wp-calypso/pull/68805#issuecomment-1272912184))
* Try resizing your browser and verify that 
   - the `double-tile` banner is converted to a `tile` banner below `960px`
   - if there are two sites and the screen width is below `960px` the banner is no longer rendered to save it wrapping
* Create a Link in Bio site and retest
* check for regressions 

#### Pre-merge Checklist

- [x] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [x] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?

Related to #

### CODE REVIEW

**Comment by mpkelly** [comment]
I have made these changes. For the image optimisation, I chose to replace transparency with the banner `background-color` and then converted the `png`s to `jpg`. I tested this with a simulated 4G network with the cache disabled and it seems fairly good. 

image

image

Are we ok with this approach to image optimisation? And, if yes, I think we should also optimise the other related images in the `onboarding` folder in a separate PR - please let me know what you think.

**Comment by danielbachhuber** [comment]
@mpkelly With one site on `row` view, here's what I see:

image

Is this expected? It seems to display as expected on `grid` view:

image

> Optimise images, so they load faster on slow networks

Out of curiosity, did you try clipping the images with CSS, to avoid needing to apply the background color to the image?

**Comment by mpkelly** [comment]
Thanks, @danielbachhuber!

The ugly tile issue happens when the width is low but not quite within the mobile breakpoint (`480px`). I think it looks passable down to about `720px`:

image

After that, it starts to look ugly, as per your screenshot. I guess the question is how many users will see the banner in the `480px` - `720px` range, and do we want to add special handlings for those?

Regarding `clip-path`, I did consider this. If the paths were available in Figma, then I'd have used them, but I thought it would have been fiddly to make them myself, so I took the easy option.

**Comment by danielbachhuber** [comment]
> After that, it starts to look ugly, as per your screenshot. I guess the question is how many users will see the banner in the `480px` - `720px` range, and do we want to add special handlings for those?

@mpkelly I think I'd have it switch to this layout much sooner:

image

We could have the background color extend full width, and constrain the text content width if we wanted.

> Regarding `clip-path`, I did consider this. If the paths were available in Figma, then I'd have used them, but I thought it would have been fiddly to make them myself, so I took the easy option.

Makes sense. I think that's fine then, although there might be a slight border artifact.

**Comment by zaguiini** [comment]
>Are we ok with this approach to image optimisation?

Works for me 👍 If there aren't huge losses in the quality we should be good to proceed with it. Though we're gzipping the images, so I'm not sure if we'll see real gains.

**Comment by mpkelly** [comment]
> @mpkelly I think I'd have it switch to this layout much sooner:

@danielbachhuber, I tried this but by default the tile stretches and the image is too big. I have hidden the image and reduced the text size when the screen width is between mobile and desktop breakpoints. Let me know what you think.

**Comment by danielbachhuber** [comment]
> I have hidden the image and reduced the text size when the screen width is between mobile and desktop breakpoints. Let me know what you think.

@mpkelly Yep, that seems to work pretty well:

image

**Review by danielbachhuber — APPROVED** [review]

**Comment by mpkelly** [comment]
The temp code was removed and PR was deployed just now.

**Pull request merged**
