### PR TITLE
Reader: Update popover position to prevent cutoff in narrower viewports

### PR DESCRIPTION
**Pull request by jancavan**
This fixes: https://github.com/Automattic/wp-calypso/issues/2725

**Before:**

iOS:
ios-share-before

Android:
android-share-before

**After:**

iOS:
ios-share-after

Android:
android-sharing-after

**EDIT:**
The Share popover gets cut off much more in narrow screens - meaning, there's a much larger crop on an iPhone 5 vs a 6, but I tested on both. For Android, tested on a Samsung Note 4.

### CODE REVIEW

**Comment by blowery** [comment]
I'm seeing this bleed off the right edge how on iOS (6+) for posts that don't have likes or comments.

screenshot

post http://calypso.localhost:3000/read/post/feed/7035081/936241404

**Comment by jancavan** [comment]
@blowery Good catch! 

I just noticed the same issue happening on the live version as well  for those that don't have Likes and Comments. It pushes the entire content area to the left:

img_7669

That's also fixed here: https://github.com/Automattic/wp-calypso/commit/da4106f11f80bfc95bcfdcc84d73c85bd9a5ddc3

**Comment by blowery** [comment]
nice work @jancavan ! I'll give it a go.

**Comment by blowery** [comment]
:ship: nice!

**Pull request merged**
