### PR TITLE
Login: Fix empty_two_step_nonce errors because of network failures

### PR DESCRIPTION
**Pull request by stephanethomas**
This pull request fixes https://github.com/Automattic/wp-calypso/issues/16456 by handling network failures correctly. More specifically, it makes sure the nonce stored in the global state tree is only updated when one is returned by the API. Previously it would be reset because of an `undefined` value, resulting in `empty_two_step_nonce` error.
  
##### SMS and Authenticator methods

1. Run `git checkout fix/empty-nonce-error` and start your server, or open a [live branch](https://calypso.live/?branch=fix/empty-nonce-error)
2. Open the [`Login` page](http://calypso.localhost:3000/log-in)
3. Submit credentials for an account with 2FA (SMS or Authenticator) enabled
4. Click the `Continue` button on the `Two-Step Authentication` page
5. Assert that a `Please enter a verification code.` error is displayed
6. Check the [`Offline` feature](https://developers.google.com/web/tools/chrome-devtools/network-performance/reference#offline) in the `Network` panel of the Chrome DevTools
7. Click the `Continue` button again
8. Assert that a `Request has been terminated [...]` error is displayed
9. Uncheck the `Offline` feature
10. Click the `Continue` button again
11. Assert that a `Please enter a verification code.` error is displayed
12. Submit a valid code
13. Assert that you are logged in successfully and redirected to the `Reader` page

##### WordPress.com app method

1. Run `git checkout fix/empty-nonce-error` and start your server, or open a [live branch](https://calypso.live/?branch=fix/empty-nonce-error)
2. Open the [`Login` page](http://calypso.localhost:3000/log-in)
3. Submit credentials for an account with 2FA (WordPress.com app) enabled
4. Assert that the [`Waiting Notification Approval` page](http://calypso.localhost:3000/log-in/push) is displayed
5. Check the `Offline` feature in the `Network` panel of the Chrome DevTools
6. Wait a few seconds ()
7. Uncheck the `Offline` feature
8. Approve the request from the WordPress.com app
9. Assert that you are logged in successfully and redirected to the `Reader` page

#### Reviews
 
- [x] Code
- [x] Product
- [ ] Tests

### CODE REVIEW

**Comment by pento** [comment]
Rather than having to put special handler logic in every request (including future requests), would it be better to alter `updateTwoStepNonce()` to check that `twoStepNonce` isn't empty?

The only downside of this approach is that you can't set the nonce to an empty value, but it doesn't seem like we ever do that.

**Comment by stephanethomas** [comment]
> Rather than having to put special handler logic in every request (including future requests), would it be better to alter `updateTwoStepNonce()` to check that `twoStepNonce` isn't empty?

That's a valid point indeed. The way it works now is that it doesn't trigger any `TWO_FACTOR_AUTHENTICATION_UPDATE_NONCE` event though (which would be the case with your approach). I don't care too strongly one way or another.

**Comment by pento** [comment]
👍🏻 on the code.

I like the look of this. I'm not too worried about an extra event being thrown - a couple of ms on top of a network failure probably won't be noticed.

**Comment by fabianapsimoes** [comment]
Product :+1:

**Pull request merged**
