### PR TITLE
Reader: Update small post layout to put title first, simpler style

### PR DESCRIPTION
**Pull request by blowery**
Use a layout with the title on top, site name, author below

Test live: https://calypso.live/?branch=update/small-post-layout

### CODE REVIEW

**Comment by blowery** [comment]
_a_moment_between_sisters _ _reader_ _wordpress_com

**Comment by blowery** [comment]
cc @fraying

**Comment by blowery** [comment]
I tried working in either the gravatar for the post author, or the site icon for the site, but it never looked very good. The simple text of the title and the byline seemed like enough? Maybe if we flew the graphic out to the left of the text, like we do for the site header, it would look better?

**Comment by drw158** [comment]
Ah I see, so this is related reading? I think this is looking good, although I don't know what it looked like before. Except, it looks strange when the site name is the author. I don't think you need the gravatar or blavatar.

screen shot 2016-06-17 at 3 09 35 pm

**Comment by fraying** [comment]
First off: Squee! My first assigned ticket. :)

I really like this. Some thoughts:

Just to make it clear what's what, I'd suggest reformatting the text to be: 

> By First Last in Blog Name

If no First Last, then: By **Username** in Blog Name
If no Blog Name, then: By First Last **on siteurl.com**
And, if First Last = Blog Name, then just: By First Last

Thoughts? Opinions?

**Comment by jancavan** [comment]
Made some changes in: https://github.com/Automattic/wp-calypso/pull/6129/commits/6492735dcd3617dd7e181da98f8b49288cfb1168

This is so the other link doesn't change color as you hover over the other.

**Before:**
screenshot 2016-06-17 14 59 10

**After:**
screenshot 2016-06-17 14 57 56

**Comment by blowery** [comment]
@fraying Sounds good. I'll make up an new Author component that handles the name work. 

We do have a display_name property that the user can set to control how their name displays.. Maybe we should default to that? See https://wordpress.com/me for the setting. 

It appears that if it's empty, we default to the username, not some combo of first / last. Hrm.

**Comment by fraying** [comment]
@blowery Oh yeah! I forgot about Display name.

So: If Display Name, use that. If not, First Last. If no First Last, use Username. Yeah?

**Comment by blowery** [comment]
@fraying looks like display_name is calculated server side, so we have no way to differentiate between setting it to your username and having it "blank". Looking around the code base, we use it blindly in the profile and other places; we should probably just trust it here too, if only for consistency.

**Comment by fraying** [comment]
Ah, okay.

So, if the name is blank, could we then use this text?

If no person name:
If Blog Name, then: In Blog Name
If no Blog Name, then: On siteurl.com

**Comment by blowery** [comment]
I'd rather not complicate the wording based on the presence or lack of a name.. It's pretty hard to detect when it's one or the other reliably, and it's just more complication in the generation. 

The latest patch uses "By {author} on {site}", unless the author and the site are identical, in which case it drops the site name to "By {author}".

**Comment by blowery** [comment]
OK, found one with an empty author (yay laughing squid). Added a special case of "On {site}" for a missing author name.

**Comment by gibrown** [comment]
"By {author} in {site}" reads a bit oddly to me. "By {author} on {site}" ? Better matches "On {site}" too.

**Comment by fraying** [comment]
My goal was, and correct me if this runs counter to any established vernacular, that when we say a blog name, it should be "in" (as in, "By Derek in Boing Boing"), but when the blog is unnamed and we have to use the URL, it should be "on" (as in, "By Derek on powazek.com). 

This language is consistent with how people generally talk about tech terms.

**Comment by fraying** [comment]
If we're unable to discern when we'll be showing a blog name or URL, we could avoid the problem entirely by using a comma instead. As in:

By Derek, Boing Boing
By Derek, powazek.com

**Comment by gibrown** [comment]
@fraying interesting, I would tend to say "By Derek on Boing Boing". As in, you are writing "on" Boing Boing. "in" to me would be appropriate if we were referring to you writing within a Topic.

**Comment by fraying** [comment]
@gibrown Yeah, it may be a regionalism. Both are correct. Some just sound better than others to certain ears.

**Comment by blowery** [comment]
@gibrown do you stand `in line` or `on line`? ;)

**Comment by gibrown** [comment]
Getting rid of the prepositions and just using a separator works for me also.

Regardless, this PR LGTM and seems to work well.

**Comment by blowery** [comment]
I like the comma idea. Working that in.

**Comment by blowery** [comment]
toby_ _reader_ _wordpress_com

**Comment by blowery** [comment]
Hrm. The comma works, but it's easy to get lost in the overall color of the text. Italics work to separate the site name, but look funky to me. `at`, `on`, and `in` all work as separators but feel wordy. 

Going with commas.

**Pull request merged**
