### PR TITLE
Update copy and connect flow for Blaze plugin on non-woo sites

### PR DESCRIPTION
**Pull request by Alameen688**
Related to #blaze-ads/pull/19

## Proposed Changes

* As part of the work to extend the Blaze for WooCommerce plugin to non-WooCommerce sites. This PR updates related copies and properties to the Blaze Ads plugin

## Why are these changes being made?

* Update copy for Blaze plugin
* Rename Woo DNA key from `blaze-ads` to `blaze-ads-on-woo` for Blaze Ads running on Woo
* Enable Jetpack magic link flow for Blaze on non-Woo sites

## Testing Instructions

* Checkout to D158244-code patch on your sandbox
* Point `widgets.wp.com` to your WP Sandbox.
* Run `yarn start` to start calypso 
* cd `apps/blaze-dashboard` and RUN `yarn dev --sync` to sync changes to your dashboard.
* In the blaze-ads plugin repo, set `define( 'WOOCOMMERCE_CALYPSO_ENVIRONMENT', 'development' );` in `blaze-ads.php`
* Generate the release plugin build from the blaze-ads plugin repo and install it in your test blog OR run locally as described in the repo readme.

Test for Woo sites
* Create a WooCommerce site, and make sure the Jetpack plugin is deactivated or not installed and Jetpack is disconnected
* In WP Admin, Go to `Marketing` -> `Blaze Ads`
* You should see the updated "Blaze Ads" name on the connect page
* Click the `Connect now` button to see the updated name in the Woo DNA-based Jetpack connect flow.
* Clicking the  "Get help setting up Blaze Ads" link should take you to the Woo documentation site

plugin dashboard

jp connect

Test for non-Woo sites
* In your test site, make sure WooCommerce is not installed/set up, the Jetpack plugin is deactivated or not installed and Jetpack is disconnected
* On your test site, ensure that WooCommerce is not set up and that the Jetpack plugin is either deactivated or not installed. Additionally, confirm that Jetpack is disconnected from your site.
* In WP Admin, Go to `Tools` -> `Advertising`
* You should see the updated "Blaze Ads" name on the connect page
* Click the `Connect now` button should take you to the default Jetpack connect flow.

jetpack logged in

For non-loggedin/new users, they should see the magic link flow.

jetpack magic link
jetpack magic link confirmation
jetpack magic link email

## Pre-merge Checklist

- [x] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [x] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [x] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Review by sbarbosa — APPROVED** [review]
The changes look good 👍

I am getting a wrong redirection at the end of the non-woo connect flow. I am landing on the Jetpack plans page instead of the dashboard. But that is not specific to this change; it's probably a configuration on the plugin side. 

You can deploy this change without breaking anything we have in production right now.

**Comment by Alameen688** [comment]
> I am landing on the Jetpack plans page instead of the dashboard.

Thanks a lot for the review!

We already discussed this but I'm adding a note here for context:

I didn't experience the issue because my test site previously had a Jetpack plan, so I was getting redirected back to my admin correctly. However, it turns out that if your site doesn't have a plan you land on the plans page. I have updated the code to redirect back to the site admin regardless.

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/16488584

Some locales (Hebrew, Japanese) have been temporarily machine-translated due to translator availability. All other translations are usually ready within a few days. Untranslated and machine-translated strings will be sent for translation next Monday and are expected to be completed by the following Friday.

Thank you @Alameen688 for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/16488584).

**Pull request merged**
