### PR TITLE
My Home: Update start learning picture

### PR DESCRIPTION
**Pull request by arthur791004**
#### Changes proposed in this Pull Request

* Update the picture of the “Blog like an expert from day one” section to align with https://github.com/Automattic/wp-calypso/issues/58763#issuecomment-995484867.

image

#### Testing instructions

* Go to `/home/<your_site>`
* Check the picture of the “Blog like an expert from day one” section is the latest one.

Related to https://github.com/Automattic/wp-calypso/issues/58763

### CODE REVIEW

**Comment by kwight** [comment]
Hm, I still see it cut off on the initial page load (although going back and forth in the slider still corrects it):

Screen Shot 2022-01-04 at 7 24 22 AM

**Review by kwight — APPROVED** [review]
This is great for updating the image, it just doesn't correct the cut-off loading state. Feel free to merge for the updated image. ✨

**Comment by andres-blanco** [comment]
The cutoff is being worked on by @enejb here https://github.com/Automattic/wp-calypso/pull/59645

**Comment by arthur791004** [comment]
> Hm, I still see it cut off on the initial page load (although going back and forth in the slider still corrects it):

@kwight Hmmm, it's weird as I don't see the cutoff after updating the picture. Let me check it again.

> The cutoff is being worked on by @enejb here #59645

@enejb Cool, I'll check that PR, thanks 👍

**Comment by arthur791004** [comment]
This PR will focus on updating the picture. The cutoff issue will be fixed by https://github.com/Automattic/wp-calypso/pull/59645

**Pull request merged**
