### PR TITLE
Nav Unification: Remove old sidebar (part 1)

### PR DESCRIPTION
**Pull request by mmtr**
Part of https://github.com/Automattic/wp-calypso/issues/47051.

#### Changes proposed in this Pull Request

This PR is the first part (more to come!) of a cleanup task which seeks to remove no longer used code as of the Nav Unification launch:
- 949a578252062645587a9149309fd1a898a6863d removes the `MobileBackToSidebar` component since it doesn't render anything when Nav Unification is enabled.
- e7fca17f559710946594285a75f7a05ffdaa56ed removes the `MeSidebarNavigation` component since it doesn't render anything when Nav Unification is enabled.
- 13bbfa0d45eeaec613bd4ef6646dfe191b9ff192 ensures that the `MySitesSidebarNavigation` component only gets rendered on `cloud.jetpack.com` pages.
- 43c0f7c2e4f8d12a03efedfb5ec1c2d9a79cb166 refactors the `SidebarNavigation` component so we no longer need `MySitesSidebarNavigation`.

#### Context

Last year, we introduced new components for the navigation sidebar as part of the Nav Unification project. However, we've been falling back to the old sidebar components in these scenarios:
- As an escape hatch using [the `?disable-nav-unification` query param](https://github.com/Automattic/wp-calypso/blob/c7e06d5e2fe1ca94643d16855209704c39452f30/client/state/selectors/is-nav-unification-enabled.js#L9-L12).
- For self-hosted Jetpack sites [not updated to Jetpack 9.8](https://github.com/Automattic/wp-calypso/blob/c7e06d5e2fe1ca94643d16855209704c39452f30/client/state/selectors/is-nav-unification-enabled.js#L14-L19).
- [In Jetpack Cloud](https://github.com/Automattic/wp-calypso/blob/c7e06d5e2fe1ca94643d16855209704c39452f30/client/my-sites/navigation/index.jsx#L24-L25).

We no longer need to support the first two scenarios, since the escape hatch was meant to be temporary and Calypso does not need to support lower Jetpack versions than 9.8 anymore.

As for the third scenario, Jetpack Cloud only needs a small subset of the old components.

That gives us a good opportunity to remove a lot of unused code which would simplify the overall Calypso codebase.

#### Testing instructions

- Use the Calypso live link below.
- Make sure there are no regressions in the navigation sidebar after a site is selected or when visiting the `me` section.
- Use the Jetpack Cloud live link below.
- Make sure there are no regressions in the navigation sidebar.
- Make sure that we still display a navigation header on mobile viewports that toggles the sidebar: Screen Shot 2022-02-28 at 12 33 16

### CODE REVIEW

**Comment by cpapazoglou** [comment]
Thanks for wrangling this Miguel!

On a site with Jetpack < 9.8:
✅  I can confirm that the secondary menu doesn't show
❗ The menu though doesn't open

CleanShot 2022-02-28 at 14 24 29@2x

**Comment by mmtr** [comment]
Thanks for testing, @cpapazoglou! Can you replicate the issue on Jetpack sites with Jetpack >= 9.8? I do get the same behavior when comparing production with this branch:

Before (prod) | After (this branch)
--- | ---
Screen Shot 2022-02-28 at 15 52 11 | Screen Shot 2022-02-28 at 15 52 20

If the issue is specific to sites with Jetpack < 9.8, then that's fine since AFAIK we don't need to support these sites.

**Comment by cpapazoglou** [comment]
> Thanks for testing, @cpapazoglou! Can you replicate the issue on Jetpack sites with Jetpack >= 9.8? I do get the same behavior when comparing production with this branch:
> 
> Before (prod)	After (this branch)
> Screen Shot 2022-02-28 at 15 52 11	Screen Shot 2022-02-28 at 15 52 20

It works fine on the latest Jetpack. 

> If the issue is specific to sites with Jetpack < 9.8, then that's fine since AFAIK we don't need to support these sites.

I can understand this, but these Users won't be able to even change site if their Jetpack < 9.8 is a primary site.

**Review by cpapazoglou — APPROVED** [review]
Tested this and works as advertised. There are no regressions to Calypso Live or Jetpack Live except than the fact that users with Jetpack `<9.8-alpha` will not be able to open the sidebar. Since we don't support these sites, I would suggest removing the condition 

https://github.com/Automattic/wp-calypso/blob/7655b6d1f326371990851da10ebb97f133fbdc17/client/state/selectors/is-nav-unification-enabled.js#L16-L19

which will turn on nav unification in them and sidebar (at least) will work.

(nitpick) We can safely remove this comment (we still need the padding for `>660px`
https://github.com/Automattic/wp-calypso/blob/949a578252062645587a9149309fd1a898a6863d/client/reader/search-stream/style.scss#L23

**Comment by mmtr** [comment]
> I would suggest removing the condition

Good call! I removed it in f7ab320, along with the `?disable-nav-unification` check since that would result on a not such a great experience similar to Jetpack < 9.8 escenario.

**Comment by cpapazoglou** [comment]
> > I would suggest removing the condition
> 
> Good call! I removed it in [f7ab320](https://github.com/Automattic/wp-calypso/commit/f7ab320ab1249e4ee65498440d9ec34b25b2b77f), along with the `?disable-nav-unification` check since that would result on a not such a great experience similar to Jetpack < 9.8 escenario.

🚢 🚢 🚢

**Pull request merged**
