### PR TITLE
Framework: enable redux persistence on horizon and dev

### PR DESCRIPTION
**Pull request by gwwar**
This PR turns on redux-persistence for horizon and development environments. 

## Before Merging:
- [x] #3267 update our approach to data doc
- [x] #3271 simple max age mechanism to throw out data
- [x] #3343 separate server state hydration

### State Tree Status

- [x] application - never persisted
- [x] current-user - persisted with schema checks
- [x] notices - never persisted
- [x] plugins - not persisted, needs schema PR
- [x] post-types - persisted with schema checks
- [x] posts - not persisted, in progress schema PR #3487
- [x] receipts -  not persisted, needs a schema PR
- [x] sharing/publicize - not persisted, in progress schema PR #3357
- [x] site-settings/exporter - not persisted, needs a schema PR
- [x] sites/plans - not persisted, schema PR blocked by #2757
- [x] sites - not persisted, see: #3624 #2757. Themes currently expects decorated sites decorated sites, and needs to be refactored.
- [x] support - not persisted, needs a schema PR
- [x] themes - not persisted, schema PR #3403
- [x] ui - never persisted #3337
- [x] users - not persisted, needs a schema PR

cc @rralian

### CODE REVIEW

**Comment by mtias** [comment]
@gwwar any reason why enabling this for horizon and not wpcalypso?

**Comment by gwwar** [comment]
Ah thanks, I think I forgot to turn this on for wpcalypso. :)

**Comment by rralian** [comment]
@gwwar We should probably enable in staging as well. I think it gets more usage than horizon so we'll probably surface issues faster.

**Comment by mtias** [comment]
@gwwar heh, no worries :) I think in general it's good to have it in wpcalypso for a bit before hitting staging.

**Pull request merged**
