### PR TITLE
Users Reduxification: add delete method

### PR DESCRIPTION
**Pull request by lamosty**
In this PR, we add functionality to delete a user in Redux way.

## Testing

Tests should pass.

### CODE REVIEW

**Comment by lamosty** [comment]
Thanks for the review @samouri! Could somebody from @Automattic/team-calypso continue working on this, please? I think I won't have availability, unfortunately.

**Comment by jsnajdr** [comment]
No problem @lamosty, we'll take care of this :) Thanks for working on the issue!

**Comment by jsnajdr** [comment]
@lamosty I'm afraid that the new `USER_DELETE` action and the whole `state.users.items` Redux store are not really useful in their current form.

The Redux store is supposed to keep a list of users separately for every site, not one big list. And the `USER_DELETE` action should remove the user from just one site. The REST API call is correct, but the Redux state is not.

Before `state.users.items` can be used as a replacement for the `lib/users` Flux store, we need to:
1. Move the "current user", i.e., information about "me", away from `state.users` into `state.currentUser`.
2. Rewrite the `state.users.items` store to be keyed by `siteId`.

**Comment by jsnajdr** [comment]
We'll need to approach this differently. Closing.

**Comment by blowery** [comment]
related to #24004

**Pull request closed without merging**
