### PR TITLE
step-container: Stop blocking click events (Redux)

### PR DESCRIPTION
**Pull request by mreishus**
#### Proposed Changes

Steps in stepper are in an absolute positioned div, where the middle of it is transparent:

If you try to select text in the title, you cannot, because the absolute positioned div is blocking the title under it:

https://user-images.githubusercontent.com/937354/180883364-83d0d333-e262-4fbe-8751-1e160e47f9b9.mp4

The same mechanism is blocking the mouseover for the tooltip in ( #65944 ).
This PR puts `pointer-events: none;` on the main absolute positioned div, and restores `pointer-events: auto;` on all descendants of that div.

**Implementation change vs last PR**: Instead of using wrapper divs to restore `pointer-events: auto`, we use CSS to select all descendants by putting a rule on `.step-container__navigation *`.

#### Testing Instructions

* Visit `http://calypso.localhost:3000/setup/designSetup?siteSlug=YOURSITE.wordpress.com`
  * Click on a theme
  * You should now be able to click on and select the text in the title. On production, this will not work.

* [Important] Regression check
  * Try to use a variety of stepper features. The buttons at the top, like "Back", "Next",  "skip for now", "start with [theme]", and whatever else can display should always work
  * The biggest risk of this PR is that it inadvertently makes something that used to work in stepper now unclickable.
  * Also try different browser widths
* [Important] The regression reported here should no longer exist: https://github.com/Automattic/wp-calypso/pull/65971#issuecomment-1196908494
  * "Skip to Dashboard" on the `/setup/goals?siteSlug=YOURSITE.wordpress.com` page should continue to be on the top right

Related to #65944

### CODE REVIEW

**Comment by markbiek** [comment]
One oddity that I noticed:

I could click "Skip to dashboard" and "Skip for now" but couldn't select any of that text. Not sure if that matters.

Aside from that, everything seemed to work properly at a variety of window sizes. If the above oddity is acceptable, I can approve.

**Comment by yansern** [comment]
> I could click "Skip to dashboard" and "Skip for now" but couldn't select any of that text. 

I think that is an OK compromise. Also tested with tabbing to make sure they are accessible with tabs.

I'm going to give another round of testing before giving the approval.

In the meantime, this got me wondering if there is an alternative approach where the navigation bar `.step-container__navigation` actually doesn't have a height, and the buttons on them are floating bits on the left & right corners. Something for later exploration.

**Comment by yansern** [comment]
> I'm going to give another round of testing before giving the approval.

Okay, I came back to retest this on specifically mobile views to make sure there's no regression when it's at the bottom. 

> In the meantime, this got me wondering if there is an alternative approach where the navigation bar .step-container__navigation actually doesn't have a height, and the buttons on them are floating bits on the left & right corners. Something for later exploration.

To follow up on this one, I tried the following and it achieved the same effect without using pointer-events.

```
.step-container .step-container__navigation.action-buttons { 
    top: -60px; 
}

.step-container .step-container__navigation.action-buttons > * { 
    position: relative; 
    top: 60px;
}
```

Anyway, approving this PR for the pointer-events approach! :)

**Review by yansern — APPROVED** [review]

**Comment by mreishus** [comment]
> I could click "Skip to dashboard" and "Skip for now" but couldn't select any of that text. Not sure if that matters.

I'm also seeing this in production, before this PR.

**Pull request merged**
