### PR TITLE
Update newspack blocks to v1.20

### PR DESCRIPTION
**Pull request by noahtallen**
- bump newspack blocks to v1.20
- includes fix for specific posts selection
- includes fixes for all phpcs issues

Test plan:
1. load these changes on a sandbox and verify that newspack blocks works, and that the issues mentioned in this PR (https://github.com/Automattic/newspack-blocks/pull/689) are fixed.

### CODE REVIEW

**Comment by dkoo** [comment]
@noahtallen The updated package looks good on my sandbox. I also pushed a fix in 798f7c4 which will close https://github.com/Automattic/newspack-blocks/issues/687 for Atomic sites. To test, run `yarn run build` first and make sure it pulls down the new `amp/homepage-posts/view.js` file into the `synced-newspack-blocks` folder. Then:

1. On a test or ephemeral Atomic site, `rsync` or manually zip the contents of `/apps/editing-toolkit/editing-toolkit-plugin` and install/activate as a plugin.
2. Activate the AMP plugin (should be installed on Atomic sites by default) and turn on Standard or Transitional mode.
3. Create a post and add a Blog Posts block in query mode. Turn on the "load more" option and make sure there are enough posts loading to show the load more functionality.
4. View the post's front-end with AMP on and confirm that the "load more" button works as expected.

**Comment by noahtallen** [comment]
Cool, I'll also give that a test!

**Comment by dkoo** [comment]
Adding to note that this will address #49707 (but will not close it until ETK is fully redeployed).

**Review by dkoo — APPROVED** [review]
Approving for 84f1d2d—if the Atomic fix looks good to you, feel free to merge, or @jeffersonrabb can also review if we need a third set of eyes.

**Pull request merged**
