### PR TITLE
Rename Anti-spam to Akismet Anti-spam

### PR DESCRIPTION
**Pull request by monsieur-z**
### Changes proposed in this Pull Request

This PR updates the last references to `Anti-spam` to `Akismet Anti-spam`.

It is a follow-up of #69954 and #69955.

Context: p1HpG7-j1R-p2

### Testing instructions

_Note: it's difficult to find all the places in the UI where these changes are reflected. Since only static strings are updated, reviewing the code should be sufficient._

- Review code, and check that only strings were updated.
- Check that no test is failing.

### CODE REVIEW

**Comment by jkguidaven** [comment]
Not sure this one does not need Akismet branding?

https://github.com/Automattic/wp-calypso/blob/update/rename-antispam/client/jetpack-cloud/sections/pricing/jpcom-masterbar/index.tsx#L64

**Review by jkguidaven — APPROVED** [review]
Changes looks good to me 💯  . I also tried to search 'anti-spam' keyword in the codebase with `origin/trunk` branch and double check if all translations are covered and it looks to me it is. nice work.. 👍

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/7626329

Hi @monsieur-z, could you please edit the description of this PR and add a screenshot for our translators? Ideally it'd include all of the following strings:
- `Akismet Anti-spam`
- `Akismet Anti-spam*`
- `Akismet Anti-spam API key`

Thank you in advance!

**Comment by niranjan-uma-shankar** [comment]
If these pages can be loaded in locales other than english, then translations would break across all the strings modified in this PR. Non-en users would see english language language text in the middle of other translated content.

To provide a good experience for non-EN users, I would recommend that you revert this PR, restart this PR with `String freeze` label, await translations to complete, and then deploy the change. Alternatively, deploy the string change only for `en` locales or if a translation already exists (using [hasTranslation()](https://github.com/Automattic/wp-calypso/blob/a93b7275a2cc78c48ee6f5ab0b13be07788f235e/packages/i18n-calypso/README.md#hastranslation-method)).

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/7626329).

**Pull request merged**
