### PR TITLE
Split `lib/domains` index

### PR DESCRIPTION
**Pull request by sgomes**
This PR splits up `lib/domains/index.js` from a single monolithic file, to an index that re-exports individual functions. This allows `webpack` to tree-shake the library more effectively.

#### Changes proposed in this Pull Request

* Split up the index file for `lib/domains`

#### Testing instructions

There are no significant code-changes, only moving things around. The unit tests and a successful build should be enough to verify that everything still works correctly.

### CODE REVIEW

**Comment by sgomes** [comment]
Rebased on master to pick up changes in #42268

**Comment by sgomes** [comment]
The E2E desktop failure seems unrelated, as it appears to be specific to its build process.

**Review by klimeryk — APPROVED** [review]
Tested as much as I could think of from domains perspective - did not notice any regressions 👍

**Comment by sgomes** [comment]
Thank you for the review, @klimeryk! 👍

**Pull request merged**
