### PR TITLE
Jetpack Partner Portal: implement URL support to show more info modal about the license in the issue license page 

### PR DESCRIPTION
**Pull request by yashwin**
#78955 had some failing pre-release e2e tests we didn't catch earlier. A URL parsing error caused it. The full discussion can be found here: p1688975846269469-slack-C02DQP0FP

Related to 1202619025189113-as-1204953498074085

mobile (23)

## Proposed Change
This PR modifies the logic to use the existing `getQueryArg` helper function to extract the **page** query param. Please see the exact changes on this [commit](https://github.com/Automattic/wp-calypso/pull/79173/commits/bdbd97d4998693570a289b1f3b09e022065ce1c6).

## Testing Instructions
To test the original PR. please refer to #78955 test instructions.

Additionally please test the Videopress setup flow where the issue was caught.
* Use the Calypso live link below and append `/setup/videopress` to start the setup
* Fill in some site information to complete the setup.
* the page should redirect to the checkout page at the end of the setup.
* Confirm that the checkout page is rendered properly without any issues.

## Pre-merge Checklist

- [x] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [x] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

**Comment by yashwin** [comment]
I have tested the changes, and it LGTM! Thanks for taking care of this one. I cannot approve this as I'm the author.

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/8361010

Thank you @yashwin for including a screenshot in the description! This is really helpful for our translators.

**Comment by yashwin** [comment]
@sirbrillig - Do you mind taking a look at this PR? We had to revert my [previous PR](https://github.com/Automattic/wp-calypso/pull/78955) because of an issue. There is a [tiny change](https://github.com/Automattic/wp-calypso/pull/79173/commits/bdbd97d4998693570a289b1f3b09e022065ce1c6) made on top of this PR.

**Review by sirbrillig — APPROVED** [review]
I don't see any problems. 👍 Thanks for the ping.

**Review by jkguidaven — APPROVED** [review]

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/8361010).

**Pull request merged**
