### PR TITLE
Add built by wp marketing card

### LINKED ISSUE #72350: Upsells: Add Built By upsell to marketing/tools
Figma: pebzTe-Fg-p2#comment-1122

Acceptance criteria:
- [x] We've added a new card for Built By to marketing/tools.
- [x] It's the first card.
- [x] Clicking the CTA should take the user to: https://builtbywp.com/?utm_campaign=theme-all&utm_medium=automattic_referred&utm_source=WordPresscom
- [x] We should track clicks and make sure we can compare them to other cards on the page.
- [x] String freeze label has been applied.

### PR DESCRIPTION
**Pull request by DustyReagan**
#### Proposed Changes

* This PR adds a new "Built by WP" card to `/marketing/tools`

new-built-by-wp-card

#### Testing Instructions

* Load this PR and go to `/marketing/tools`
* Ensure this card loads (see picture above)
* Ensure the card matches the Figma pebzTe-Fg-p2#comment-1122
* Ensure that clicking the button sends you to `https://builtbywp.com/?utm_campaign=theme-all&utm_medium=automattic_referred&utm_source=WordPresscom`
* Ensure the clicks are Tracked. PCYsg-cae-p2

#### Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

Related to #

### CODE REVIEW

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/7786474

Thank you @DustyReagan for including a screenshot in the description! This is really helpful for our translators.

**Review by lupus2k — APPROVED** [review]
LGTM 🚀

**Review by paulopmt1 — APPROVED** [review]
Thanks for adding String/Freeze. Everything working great across browsers. I'm assuming we don't want a specific view track as we can use the calypso_page_view for that.

Good job!

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/7786474).

**Pull request merged**
