### PR TITLE
Pages: Add "Set as Homepage" action to the pages list

### LINKED ISSUE #35043: FSE: Add a "Set as Front Page" option to /pages
Any site using a full site editing compatible theme will have the customizer hidden (see https://github.com/Automattic/wp-calypso/issues/34791). There is one major setting that this hides from users that is not present in Calypso.

Setting the front page, and setting the post listing page.

We do not need to keep the post listing page setting because this is replaced with a static page and the "Blog" template (with the latest posts blog).

We do need to allow users to set which page is their front page.

I suggest the following changes for any site with a FSE compatible theme enabled:

Screen Shot 2019-07-31 at 8 55 00 PM

Selecting "Set as Front Page" on any other page will do just that.

/cc @shaunandrews

### PR DESCRIPTION
**Pull request by Copons**
#### Changes proposed in this Pull Request

Complete the work started in #24087 that allows setting a page as homepage directly from the pages list.

Screenshot 2019-08-05 at 18 52 52

Previously, this PR took advantage of the site settings infrastructure by adding the front page settings to the settings endpoint.
Though, this would have meant waiting for the next JP release, and adding version checks.

Now, instead, this PR uses the `sites/:site/homepage` endpoint, which was already available.
The request is sent through the data layer as usual, and the response is then used to update the `siteSettings` store.

For this reason, I've updated the front page selectors to take advantage of the`site-settings` store, instead of relying to the site options which aren't kept updated.

#### Follow Ups

- Since this changes the selectors to look into `siteSettings` instead of `sites`/`pages`.
This means that we should move them away from there and, possibly, into the generic `selectors` folder.
- Once #35106 lands, we should use the new `isSiteUsingFullSiteEditing` selector to hide the unnecessary `BlogPostsPage` component.
- Last but not least, we should also add a "Set as Blog Page" action to the page list (not available for FSE sites), which would take advantage of this PR.

#### Testing instructions

* Navigate to `/pages/:site`.
* In the ellipsis menu of a page (that is neither the homepage nor the blog page), locate the "Set as Homepage" action, and click it.
* Make sure that page immediately becomes the site's homepage (notice the label in the page card, and check on the frontend of the site).
* Make sure the "Set as Homepage" action is only available for published pages, and unavailable for the current homepage and blog page.

Fixes #35043

### CODE REVIEW

**Comment by Copons** [comment]
Just FYI @apeatling, compared to the original issue, I have not removed the "blog page" section, as the selector to check if the site is FSE-compatible is not merged yet (https://github.com/Automattic/wp-calypso/pull/35106).
I'll update this as soon as it gets merged, or even better I'll open a follow-up.

**Comment by Copons** [comment]
Note to self: I'll also need to figure out why the tests fail, when they seem to work for me locally after afda06e

**Comment by Copons** [comment]
Reverting to WIP because this solution entails a JP change, and I think there's a way to avoid that.

**Comment by vindl** [comment]
> Reverting to WIP because this solution entails a JP change, and I think there's a way to avoid that.

To avoid delays while waiting on next Jetpack release, we could land this for Simple sites and infer FSE status on Atomic sites based on other factors that are already available for both platforms - one thing that comes to my mind is checking whether FSE plugin and FSE theme is active. Once we land proper Jetpack fix in next release, we could circle back and clean that up. Although if you think there is an easier way to avoid that, feel free to purse it.

> Should we switch entirely to the block based approach of showing blog post excerpts and ditch the concept of a "blog posts page" (which is confusing) entirely?

I think that's what we are aiming for, at least for FSE sites.

**Comment by vindl** [comment]
Regarding inferring FSE availability on Atomic, this issue could be relevant too https://github.com/Automattic/wp-calypso/issues/34791 (similar needs I think).

**Comment by noahtallen** [comment]
>  think that's what we are aiming for

Awesome! Do we need an issue for it?

**Comment by vindl** [comment]
> Awesome! Do we need an issue for it?

I think it's out of scope for this milestone, but feel free to create one and add it to FSE project board if you'd like. 👍

**Comment by Copons** [comment]
@vindl Yeah I know there were other solutions, but since we already have a `/sites/:site/homepage` doing what we need, I'd rather use that than update the `/settings` one to support the front page options, create multiple conditional blocks in the code, update JP, and wait for it to be released. 🙂 

@noahtallen Technically, WP does not allow to have the same value for the front and posts page, because in fact it's not really necessary.
Basically we have two choices:
- Latest posts in home (the old school WP default): we don't need to assign them to a specific page, because they are handled automagically.
- A specific page in home, and we can also choose _another_ page to display the posts. If we wanted them to be the same, then why not choosing to straight up displaying the posts in home instead? (and in fact, this is how WP expects these options internally).

But anyway, this change affects all sites, not just FSE ones.
With the new `isSiteUsingFullSiteEditing` we can do more interesting stuff for FSE only. 💥

**Comment by ramonjd** [comment]
Just FYI, the [checklist](https://github.com/Automattic/wp-calypso/blob/master/client/my-sites/checklist/wpcom-checklist/component.jsx#L1049) relied on `getSiteFrontPage` (with the old options-based selector)

Do you recommend that we use `<QuerySiteSettings />` or are we safe to reinstate a selector based on site options removed [here](https://github.com/Automattic/wp-calypso/pull/35141/files#diff-2853c1244c63aaa890f55ecc807382a0L14)

**Pull request merged**
