### PR TITLE
Domains: Use Ellipses for Lengthy Labels

### LINKED ISSUE #44982: Site Domains - Translated labels not aligned
Under `Manage > Domains > Site Domains`, here's the display in English:

english

Here's the display when the translations are longer, like in French:

french

### PR DESCRIPTION
**Pull request by Aurorum**
#### Changes proposed in this Pull Request

* Use ellipses for lengthy labels under Domains, as suggested by @fditrapani 

It appears that there's a few formatting issues that were automatically taken care of by Prettier too.

#### Testing instructions

Set your language to French in Account settings and visit `/domains/manage/site`

**Before:**
Screenshot 2020-08-18 at 18 20 29

**After:**
Screenshot 2020-08-18 at 19 27 27

Fixes #44982

### CODE REVIEW

**Comment by fditrapani** [comment]
Thanks for putting this together so quick @Aurorum! Just looking at the screenshots, is there any way we can include the info tooltip after the ellipses? This will allow people to read what each column is about. It might require us to reduce the character count for each column.

**Comment by Aurorum** [comment]
Oh, yikes, I'm not sure how I missed that. Yep, fixing that now! :)

**Comment by Aurorum** [comment]
Should be fixed now - sorry about that! 👍 

Screenshot 2020-08-18 at 19 27 27

**Comment by fditrapani** [comment]
Thanks for the update! I tested this with multiple languages and it doesn't break :) It would be good to get @hambai to take a closer look from the code perspective.

**Review by mmtr — APPROVED** [review]
Thanks @Aurorum! This looks good to me both functional and code wise. Can you rebase in order to solve the conflicts? I can land this for you afterwards.

**Comment by Aurorum** [comment]
Sorry about the delay - conflicts resolved! :)

**Pull request merged**
