### PR TITLE
Reader: Fix the check for using a excerpt

### LINKED ISSUE #7673: Fullpost: Add "Visit Full Site" notice for RSS excerpts
Test post: https://wordpress.com/read/feeds/166857/posts/1132123511

Current live site displays a "Visit [Site Name] for the full post" message at the end of RSS feed items that don't show the whole post.

screen shot 2016-08-25 at 10 53 24 am

This is omitted in the fullpost refresh.

screen shot 2016-08-25 at 10 53 36 am

Let's add it back in. Use existing styling, except: 1, the box should be the same width as the content column, and 2, the sentence should end with a period.

### PR DESCRIPTION
**Pull request by blowery**
Fixes how we show the excerpt notice.

Fixes #7673

Test live: https://calypso.live/?branch=add/reader-refresh/full-post-summary-notice

To test, visit http://calypso.localhost:3000/read/feeds/34575 and click through into a post. Notice the new notice below the post excerpt that lets you know you can see the full post on the actual site, just like in prod. 

http://calypso.localhost:3000/read/feeds/34575/posts/1136173740

### CODE REVIEW

**Comment by tyxla** [comment]
This LGTM, the only thing I noticed was that the notes from #7673 by @fraying haven't been applied yet:

>  1, the box should be the same width as the content column, and 2, the sentence should end with a period.

**Comment by blowery** [comment]
@tyxla fixed

**Comment by fraying** [comment]
Thanks for the reminder, @tyxla! And thanks, @blowery!

**Comment by blowery** [comment]
wordpress_com

**Comment by blowery** [comment]
Looks like we have some spacing and font size issues too with excerpts. I'll fix that in another PR.

**Comment by fraying** [comment]
Excerpt notice looks great - thanks.

Yeah, I mentioned the spacing issue here: https://github.com/Automattic/wp-calypso/issues/7669

**Pull request merged**
