### PR TITLE
Themes: Prefix ambiguous filter terms with taxonomy

### PR DESCRIPTION
**Pull request by seear**
Some theme filter terms, for example _video_, _light_, and _dark_, belong to more than one taxonomy. We can disambiguate these terms by prefixing them with the taxonomy in the URL.

**Before**

screen shot 2016-10-11 at 16 38 36

**After**

screen shot 2016-10-12 at 17 19 25

**Todo**
- [x] unit test
- [x] associated API change to handle prefixes

Needs associated endpoint change D3019-code

cc @budzanowski

### CODE REVIEW

**Comment by budzanowski** [comment]
:+1:

**Comment by folletto** [comment]
I'm not sure on the `taxnomy__name` syntax. Can we do something more natural language like? Would `:` work? or just `taxonomy-name`?

**Comment by budzanowski** [comment]
We can only use ` $ - _ . + ! * ' ( ) , , ` as they are not reserved chars in url. I kind of like `$` for taxonomy end as it reminds me the word `tax` but that is just a silly idea :) `taxonomy$compound-term`.

**Comment by folletto** [comment]
I'd then go for either `-` or `.` as more intuitive to read. :)

**Comment by seear** [comment]
Let's try using `:` (after some discussion where we remembered that a colon is already used in Calypso for jetpack sites in subdirectories).

**Pull request merged**
