### PR TITLE
Themes Showcase: Display the page for the user without any site

### PR DESCRIPTION
**Pull request by arthur791004**
Related to https://github.com/Automattic/wp-calypso/issues/82839

## Proposed Changes

* Enable `enableNoSites` to allow the Theme Showcase to display the content for the user without any site
* Create the `renderThemes` function to determine which layout we should render - LoggedOut vs. LoggedIn
* Support rendering the logged-in Theme Showcase without the site ID as the user might not have any site now
* Go to the signup flow when the user picks the theme without any site
* Go to the signup flow with the preselected plan when the user clicks the Upsell banner without any site

| Theme Showcase | Theme Details Page |
| - | - |
| image | image |

## Testing Instructions

**Logged-in Theme Showcase for the user without any site**

* Go to /themes
* Ensure you can see the theme list UI
* Click `...` on any site, and you will see the options below
  image
* Select any theme to ensure you can see the theme details page
  * Ensure the action buttons on the theme details page are followed
    image
  * If you select the premium theme, ensure the upsell banner brings you to the sign up flow with the premium theme

**Logged-in Theme Showcase for the user with sites**

* Go to /themes
* Ensure you can see the site selection UI
* Select any site
* Ensure you can see the theme list

**Logged-in Theme Showcase for the user with the specific site**

* Go to /themes/<your_site>
* Ensure everything works as expected

**Logged-out Theme Showcase**

* Go to /themes
* Ensure everything works as expected

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

**Comment by taipeicoder** [comment]
@arthur791004 could you check if the no results screen throws an JS error? Try something like `/themes/all?s=testtesttest`.

**Comment by taipeicoder** [comment]
The Assembler CTA also didn't work for me:
Screenshot 2023-10-16 at 6 10 33 PM

Is it possible to link users to `/start/with-theme-assembler/user?ref=calypshowcase` instead?

**Comment by arthur791004** [comment]
> could you check if the no results screen throws an JS error? Try something like /themes/all?s=testtesttest.
> The Assembler CTA also didn't work for me:

@taipeicoder Nice catch! I've addressed the above issues, thanks 👍

**Comment by fushar** [comment]
@arthur791004: I found one issue with premium flow. Steps:

1. Open the live branch with a user with no site.
2. Open /themes.
3. Select Enroute.
4. Go through domain step.
5. On the plan step, click `start with another theme`.
   - Expected: we go to the Design Picker
   - Actual: nothing happens.

image

**Comment by arthur791004** [comment]
> I found one issue with premium flow. Steps:

@fushar I cannot reproduce the issue. When I clicked `start with another theme`, the new site was created, and the page went to the Design Picker. I've rebased onto the latest trunk and maybe the issue is resolved 🤔

**Comment by fushar** [comment]
> @fushar I cannot reproduce the issue. When I clicked start with another theme, the new site was created, and the page went to the Design Picker. I've rebased onto the latest trunk and maybe the issue is resolved 🤔

Okay, that's weird, I checked it again and can't reproduce it, too. Maybe because it's somehow "fixed" on latest trunk 🤔 
I'll continue testing this!

**Review by fushar — APPROVED** [review]
Tested the following:

✅ Logged-in, no site
✅ Logged-in, with sites
✅ Atomic
✅ Jetpack-connected
✅ Logged-out

All work. Nice 👍

**Comment by fushar** [comment]
> @fushar I cannot reproduce the issue. When I clicked start with another theme, the new site was created, and the page went to the Design Picker. I've rebased onto the latest trunk and maybe the issue is resolved 🤔

Sorry, @arthur791004, after further investigation, it's my Chrome's fault 🤦 I somehow got hit with this [bug](https://support.google.com/chrome/thread/239510768/cannot-click-in-top-right-corner-when-in-full-screen). After doing the workaround in the forum, it's fixed 🤦 

It's all good now!!

**Pull request merged**
