### PR TITLE
Login: Improve magic link component style

### LINKED ISSUE #84041: Passwordless flow: fix line-height and margin
The heading and first paragraph on the passwordless flow (magic link) doesn't look right.

### Current

Image

Image

### Proposal
* Change h1's line-height from a fixed `57px` to `120%`
* Change margin to `margin: 4px 0 24px 0` on the p below the heading (`.magic-login__form .logged-out-form p`)

Image

### PR DESCRIPTION
**Pull request by renancarvalho**
Fixes #84041 

## Proposed Changes

* Add suggestions on magic link `/link` screen, suggested https://github.com/Automattic/wp-calypso/issues/84041

## Testing Instructions

* Use live link and navigate to `/log-in/link`
* Check if styles are matching with the suggested https://github.com/Automattic/wp-calypso/issues/84041

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

**Comment by renancarvalho** [comment]
@crisbusquets, would you be kind and check it? Thank you. 🙇

**Comment by crisbusquets** [comment]
> @crisbusquets, would you be kind and check it? Thank you. 🙇

Yes, sure! It works for me. Thank you 🚀 

image

image

**Comment by crisbusquets** [comment]
Sorry, I just realized that the second image has more space between the heading and the paragraph.
Can we reduce that `.card` padding to 4px on top? This way it'll match the prev. screen.

**Comment by renancarvalho** [comment]
Thank you so much for checking it out @crisbusquets I really appreciate, :) I have added `margin-top: 4px;` on `.card` 👍

**Review by agrullon95 — APPROVED** [review]
## Tests:

- [x]  Verify header line-height is set to `120%`
- [x]  Verify paragraph underneath header (.logged-out-form) margin has been updated to `margin: 4px 0 24px 0;`. Only affects the first screen, right? @renancarvalho 
- [x] Verify the promo card has a margin-top of `4px`

**Comment by renancarvalho** [comment]
@agrullon95 Correct, that style's change only affects magic-login.

**Pull request merged**
