### PR TITLE
Personal Plan: A/B Test Cleanup

### PR DESCRIPTION
**Pull request by rodrigoi**
This PR removes all the references to the A/B test and keeps the feature flag.

cc: @apeatling @roundhill @gwwar 

Test live: https://calypso.live/?branch=update/personal-plan-ab-test-cleanup

### CODE REVIEW

**Comment by rralian** [comment]
Thanks for the heads-up @apeatling. I am using this code for the skip-for-free-plan test in #6701. @rodrigoi have you followed the pings about this? We want to test a version of the NUX plans page that presents the "free" option as a sort of "skip this step" link rather than as a prominent plan option (see #6701).

This makes the most sense when the personal plan is active, so part of my PR is to re-launch the personaPlan, which I am doing by re-enabling the config settings in all environments and modifying the abtest settings to launch personalPlan at 100%. I could do this differently, for example it could be governed by the config setting alone and just launch personalPlan to everyone via the config setting. But we should be on the same page about what we're doing here.

**Comment by rodrigoi** [comment]
Depends on https://github.com/Automattic/wp-calypso/pull/6701. This will have to be rebased taking `skipPlansLinkForFree` test into consideration.

**Comment by rralian** [comment]
Actually @rodrigoi, it's probably easier to merge this one and rebase #6701 on top of it to rely upon the config value instead of the abtest setting.

**Comment by roundhill** [comment]
Code looks good 👍

**Comment by rralian** [comment]
I made some changes to #6701 so it should be a little easier to refactor when you get to it.

**Comment by rralian** [comment]
FYI #6701 is merged and launched.

**Comment by rodrigoi** [comment]
@rralian I gave it a fair shake an everything seems to be in order. Let me know how you feel about the changes I've made.

**Comment by rralian** [comment]
LGTM!

**Pull request merged**
