### PR TITLE
Social | Add Threads to social connections UI

### PR DESCRIPTION
**Pull request by manzoorwanijk**
## Proposed Changes

* Update Threads UIs for social connections

## Why are these changes being made?

* We are adding support for [threads.net](https://threads.net) in Social

## Testing Instructions

* Sandbox D152810-code and follow the instructions given there
* Point `public-api.wordpress.com` to your sandbox
* Goto `/marketing/connections/:site`
* Confirm that you see Threads in the connections list
* Confirm that you see "New" badge on it
* Confirm that you don't see "New" badge on Nextdoor
* Confirm that the descriptions are corrected both in collapsed and expanded form
* Connect a Threads account
* Confirm that it works as expected
* Confirm the same for Jetpack Cloud

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

image

Screenshot 2024-06-21 at 1 28 07 PM

### CODE REVIEW

**Review by pablinos — APPROVED** [review]
I think this might be related to the backend changes, but without a profile image, I get a black square. I seem to remember a similar problem for the Instagram Basic Display API, which this looks very similar too. 

@spsiddarthan just in case this is something that can be fixed.

CleanShot 2024-06-21 at 12 28 14@2x

**Comment by pablinos** [comment]
> I think this might be related to the backend changes

Actually, I don't think that's the case. We're handling the lack of profile image fine on the Jetpack side. Perhaps we need to create a default profile image for the service?

**Comment by manzoorwanijk** [comment]
> I think this might be related to the backend changes, but without a profile image, I get a black square. I seem to remember a similar problem for the Instagram Basic Display API, which this looks very similar too.


Fixed in https://github.com/Automattic/wp-calypso/pull/92018/commits/6253e039db8649274e7ceb11b1fc9e7b30c36cf2
image

**Comment by pablinos** [comment]
> Fixed in https://github.com/Automattic/wp-calypso/commit/6253e039db8649274e7ceb11b1fc9e7b30c36cf2

Nice! Thank you. :shipit:

**Review by pablinos — APPROVED** [review]
Thanks for updating the examples.

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/15318108

Some locales (Hebrew, Japanese) have been temporarily machine-translated due to translator availability. All other translations are usually ready within a few days. Untranslated and machine-translated strings will be sent for translation next Monday and are expected to be completed by the following Friday.

Thank you @manzoorwanijk for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/15318108).

**Pull request merged**
