### PR TITLE
A4A: Modifying SectionNav NavTabs component to consider navigation using horizontal scroll

### PR DESCRIPTION
**Pull request by coder-karen**
Related to #https://github.com/Automattic/automattic-for-agencies-dev/issues/123

## Proposed Changes

* This PR modifies the SectionNav NavTabs component to allow an additional prop - `hasHorizontalScroll` - which helps prevent the dropdown being displayed only when the navigation tabs width is greater than the width of it's parent section-nav-group. This makes sense if horizontal scroll for the navigation isn't enabled, but not otherwise.
* Horizontal scroll for the preview pane section nav wasn't currently enabled though, but is now. With the ever increasing amount of navigation tabs this makes sense imo.
* In doing so, I've added a max width which is the generic mobile max width. By adding this, the other issue with the dropdown showing unnecessarily is also prevented: https://github.com/Automattic/automattic-for-agencies-dev/issues/244.
* That said, we could add another prop to set that width. I'm wary about modifying the SectionNav components too much though.

## Testing Instructions

For the below testing steps, make sure to run `yarn start-a8c-for-agencies` locally and then visit `http://agencies.localhost:3000/sites`.

* Open the preview pane in different screen widths, and the dropdown should now only display on mobile (or on screens smaller than 480px).
* You should see horizontal scroll for the navigation menu now as well, where it otherwise would be chopped off.
* Note when modifying the screen size, consider whether that screen size would show the preview pane in it's current state if opening the pane (or opening the page via URL using a URL that would ordinarily open the pane in full screen). Sometimes just manually  changing the width results in a display which wouldn't happen normally at that screen size.

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Comment by rcanepa** [comment]
Thank you for taking a stab at improving this issue, @coder-karen.

Overall, I like this approach. It eliminates the unreliable timeout and makes the experience smoother when changing the viewport width.

I would like to know if it is possible to display the scrollbar only when absolutely necessary. For example, the scrollbar is visible in the following recording even when all tabs fit the screen, and there is extra free space on the right side.

https://github.com/Automattic/wp-calypso/assets/3418513/4239d6c6-3988-40fd-8f39-114e9201268a

Improving this would make this solution much more applicable.

**Comment by coder-karen** [comment]
> I would like to know if it is possible to display the scrollbar only when absolutely necessary. For example, the scrollbar is visible in the following recording even when all tabs fit the screen, and there is extra free space on the right side.

@rcanepa yes it turns out this was, in the end, an 'easy' fix. The class `section-nav-tabs__list` needed it's width unset. I removed some padding as well as it isn't needed as much with the overflow in place. I say 'easy' as I spent a good bit of time working out how to compare the two widths (child and parent element) to see if I could catch when one was smaller / larger than the other and remove the overflow, but that wasn't needed in the end.

**Review by rcanepa — APPROVED** [review]
LGTM.

It works and looks much better now. Thank you for improving it!

**Comment by cleacos** [comment]
Great! That issue was starting to annoy me a lot.

**Comment by cleacos** [comment]
It seems that the issue is still there:

image

**Comment by coder-karen** [comment]
@cleacos looks like I never followed up here, but to close the loop the linked PR solved the new issue.

**Pull request merged**
