### PR TITLE
AnchorFM: Headstart Annotations

### PR DESCRIPTION
**Pull request by ramonjd**
#### Changes proposed in this Pull Request

Gilbert and Riley use pub/spearhead as their underlying themes. Updating JSON and images to reflect that

#### Testing instructions

1. Apply this diff D55324-code
2. Checkout this branch or use Calypso Live
3. Go to http://calypso.localhost:3000/new?anchor_podcast={anchor_podcast_id}
4. Enter a podcast name
5. Choose a design
6. Choose a font pairing and click continue
7. Pick a site name, plan, and domain. Launch this site.
8. The website created should be flagged as as "headstart" theme with designs similar to the Gilbert or Riley theme

#### GIFs

Fixes 393-gh-Automattic/dotcom-manage

### CODE REVIEW

**Comment by blackjackkent** [comment]
I'm not sure if this is expected (or some quirk in my environment) but some of the default styling on these themes looks wonky.

image
image

Also, how do I verify that the website is flagged as "headstart"?

**Comment by ramonjd** [comment]
> I'm not sure if this is expected (or some quirk in my environment) but some of the default styling on these themes looks wonky.

I think this might be a conflict/issue with the theme CSS? I've seem similar things before and it was the underlying theme.

This was a test PR originally, passing it off to @krymson24, who has more context. Thanks!

**Comment by krymson24** [comment]
> I'm not sure if this is expected (or some quirk in my environment) but some of the default styling on these themes looks wonky.

Good catch @blackjackkent ! I'm seeing the same. I don't recall seeing this before, but I also see it on the Riley Starter and Gilbert Starter site. @ianstewart -- has something changed about these designs/websites?

> Also, how do I verify that the website is flagged as "headstart"?

You can go to BlogRC with the blog ID. There should be a "headstart" blog sticker.

**Review by mreishus — APPROVED** [review]
I approve because I independently came up with the same PR: https://github.com/Automattic/wp-calypso/pull/49018/ :)
Currently headstart is not being run, which causes newly created sites to not have the anchor option or sticker set, which is hampering dev and testing of other issues.  I recommend this be merged and any further refinement be done in a separate step.

**Comment by kwight** [comment]
@mreishus Yep, looks good – go ahead and merge to keep yourself moving. Thanks @ramonjd and @krymson24 !

**Comment by ianstewart** [comment]
> has something changed about these designs/websites?

No changes that I know of. cc @alaczek

**Pull request merged**
