### PR TITLE
Sharing: Add sharing defaults back into sites requests

### PR DESCRIPTION
**Pull request by ehg**
Quick PR to fix https://github.com/Automattic/wp-calypso/issues/14853

See testing instructions there.

### CODE REVIEW

**Comment by mtias** [comment]
@aduth do you see a way of not having to rely on these attributes and fetching them via a settings/sharing endpoint instead?

**Comment by aduth** [comment]
`default_likes_enabled` is available from `GET /sites/%s/settings` as `! disabled_likes`

`default_sharing_status` is available from `GET /sites/%s/sharing-buttons` as `some( sharing_buttons, { visibility: 'visible' } )`

**Comment by mtias** [comment]
Does that sounds we can have a couple query-components and not rely on site anymore?

**Comment by aduth** [comment]
Yes.

**Comment by ehg** [comment]
Let's merge this for now. Feel free to revert when we have some saner QueryComponents :)

**Comment by ehg** [comment]
Also thanks @hoverduck for testing :)

**Pull request merged**
