### PR TITLE
Partner Portal: Split utils into their own files

### PR DESCRIPTION
**Pull request by mattgawarecki**
This pull request splits all the functions and constants in `client/jetpack-cloud/sections/partner-portal/utils.ts` into their own separate files inside a `lib/` directory at the same level. It also adds test coverage for many of these functions.

## Proposed Changes

* As described above. Every effort was made to avoid changes in logic, so basically every function's code should be identical to what it was before this PR. **See the commit log for in-depth details. *(NOTE: Reviewing commit-by-commit is probably the easiest approach.)***

## Testing Instructions

Regression testing in the Partner Portal. Some example areas to explore:

* the agency signup form
* viewing product licenses (with and without search/filters)
* issuing and assigning product licenses
* unassigning and revoking product licenses
* product download form
* product and bundle lightboxes
* updating company details

### CODE REVIEW

**Review by yashwin — COMMENTED** [review]
Code changes LGTM. Thanks for including the test cases.

I haven't tested the changes yet. I'll do that and leave a comment here.

**Comment by yashwin** [comment]
@mattgawarecki: Apologies, I couldn't test this PR. Could you please someone else do that? Thanks!

**Comment by vitozev** [comment]
I'll do the manual testing tomorrow.

**Review by vitozev — APPROVED** [review]
Thank you for working on this refactoring, @mattgawarecki!

I've tested manually (and compared with staging) all the flows below:
- the agency signup form
- viewing product licenses (with and without search/filters)
- issuing and assigning product licenses
- unassigning and revoking product licenses
- product download form
- product and bundle lightboxes
- updating company details

Everything is working as expected, and the code changes also makes sense to me.

**Pull request merged**
