### PR TITLE
Importers: update wording for other platforms.

### LINKED ISSUE #17631: Atomic: Import from Medium displays in Calypso but doesn't work
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/settings/general/
2. Check the page, you can read as follows:

```
Import
Import content from another WordPress or Medium site.
```

#### What I expected

To be able to import from Medium as can be seen in the support docs here: https://en.support.wordpress.com/import/import-from-medium/

#### What happened instead

I'm redirected to https://domain.com/wp-admin/import.php where the Medium import option is not available.

#### Screenshot / Video

screen shot 2017-08-30 at 15 24 06

cc: @katinthehatsite

### PR DESCRIPTION
**Pull request by lancewillett**
Fixes #17631

To test:

1. Switch to the branch.
2. Navigate to Settings, General and scroll down to Import area.
3. Notice the text says `Import content from another WordPress site and other platforms.`

screen shot 2018-04-06 at 09 07 27

### CODE REVIEW

**Comment by lancewillett** [comment]
Hmm, is the `package.json` file update automated? I can revert that.

**Comment by lancewillett** [comment]
Re-building the failed Canary test (looks like it failed to check out the branch).

**Comment by marekhrabe** [comment]
I think we should remove the package.json file. I don't see why it should update (or be installed locally in Calypso instead of global scope)

**Comment by marekhrabe** [comment]
Other than that (+ canary), the subtitle change looks good.

**Comment by lancewillett** [comment]
OK, thanks! Reverted.

**Comment by marekhrabe** [comment]
Thanks for a quick fix! :)

**Pull request merged**
