### PR TITLE
Activity: transform rewind/download backup button into ellipsis menu

### PR DESCRIPTION
**Pull request by keoshi**
This PR replaces the primary Rewind button and the dropdown option for a subtler ellipsis menu that contains both. The goal is to reduce the repetition of such a powerful element, which was making it lose its semantic effect.

Ref: p9rlnk-wF-p2 #comment-2892

Additionally, this fixes a couple of related things:

- Improves the copy for the restore option: “Rewind” is now ”Rewind to this point”, to aptly manage expectations from the get go.
- Fixes an issue where the text on the confirmation dialogs (rewind/download backup) went outside its boundaries.
- The ellipsis menu is now vertically centered.

### Before

image

### After

image

image

### How to test

- Fire this PR up.
- Navigate to a site that has Rewind enabled.
- Check if the ellipsis menu behaves as expected.
- Try to click either the Rewind or Download backup options. Does everything work?

### CODE REVIEW

**Comment by keoshi** [comment]
Thanks for that, @joanrho. It looks much better, but since that's a global component, that changes affects much more than just this UI, it affects all of Calypso.

If we think that change would benefit the overall patterns, then let's push it upstream on a separate PR.

If it's a change just for our particular scenario, then let's target it specifically by using an existing class; e.g.: `.activity-log-item__action .popover__menu-separator`.

**Comment by joanrho** [comment]
Thanks for the heads up @keoshi! I do think we should change the global component, as this has come up before: coincidentally, the same issue arose in your old "Add new site" selection popover ([23186](https://github.com/Automattic/wp-calypso/pull/23186)), which we then only fixed specifically there. It'd be best to go ahead and make the change on the global component once and for all so we don't have to keep fixing it in isolated places here and there.

**Comment by keoshi** [comment]
@joanrho yep, it's way more noticeable when we have only two items. See the menu on Site Pages, for instance, and the visual imbalance is reduced.

I'll go ahead and merge these AL changes, and we can open a new PR for this issue.

**Comment by seear** [comment]
Thanks @keoshi, this is great, and feels much more appropriate.

I was going to ask if we should let mobile apps design know to see if they wanted to make a similar change, but I see now that they already have a tasteful little rewind icon rather than a prominent button, which also feels appropriate.

**Pull request merged**
