### PR TITLE
Plans: Allow purchasing of plans on trial from Plan Overview page

### PR DESCRIPTION
**Pull request by stephanethomas**
This pull request addresses part of https://github.com/Automattic/wp-calypso/issues/1151 by adding a button in the header of the `Plan Overview` page to allow users to purchase the plan they subscribed to as part of a free trial:

screenshot

This pull request also makes sure the page display correctly on small viewports:

screenshot

#### Testing instructions

1. Get a new test account and blog
2. Enable your sandbox and proxy
3. Select a plan by clicking the `Start Free Trial` button on the [`Plans` page](http://calypso.localhost:3000/plans)
4. Click the `Start 14 Day Free Trial` button on the `Secure Payment` page
5. Check that the purchase was successful
6. Navigate back to the `Plans` page and make sure the `Plan Overview` variant is displayed
7. Click the `Purchase Now` button and make sure the corresponding plan is added to the shopping cart

#### Additional notes

I decided to move the `Purchase Now` button above the progress bar for small viewports as [the opposite](https://github.com/Automattic/wp-calypso/issues/1151#issuecomment-163036162) seemed almost impossible to achieve using a flexbox layout. 

- [x] Code review
- [x] Product review

### CODE REVIEW

**Comment by spncrb** [comment]
Product Tested :+1:

Could still use a code review...

**Comment by Tug** [comment]
Code LGTM :+1: 

In a user perspective, I would expect to be redirected to the checkout page and pay for my plan after clicking the "Purchase Now" button. Having a cart here enforces the user to take a few extra step:
- Understand what happened (the product was added to the cart)
- Find the cart in the page (small icon with only a counter on it, a notice could say "item added to your cart"

I'm not sure there is anything to add to the cart, most user would want to go to the checkout page at this point.

**Comment by spncrb** [comment]
I agree that the purchase now button should go straight to the payment method/checkout form instead of adding to the cart.

**Comment by stephanethomas** [comment]
I have updated the button according to your feedback. This is ready for a last look.

**Comment by Tug** [comment]
Ok :ship:

**Pull request merged**
