### PR TITLE
Checkout: Add plan upsell when non primary domain is purchased

### PR DESCRIPTION
**Pull request by eltongo**
#### Changes proposed in this Pull Request

This PR adds a plan upsell card after the purchase of a domain by free users as part of this test: p99Zz8-10j-p2

#### Testing instructions

Recommended to use Store Sandbox:

* Select a site that is on a free plan
* Purchase a domain
* Right after the purchase, in the Thank You page, you should see this card among others:

Screenshot 2020-02-26 at 3 08 54 PM

Also verify that the functionality works, and that clicking the button takes you to the right page.

### CODE REVIEW

**Comment by fditrapani** [comment]
I just made a purchase, while sandboxed, and didn't see the card. This is what I got:

image

Do I need to apply any patches or anything? and should I have seen the upgrade nudge in a cart (or has that not merged yet?)? I didn't see it.

**Comment by eltongo** [comment]
> I just made a purchase, while sandboxed, and didn't see the card. This is what I got:
> 
> image
> 
> Do I need to apply any patches or anything? and should I have seen the upgrade nudge in a cart (or has that not merged yet?)? I didn't see it.

Probably you need to update your sandbox.

**Comment by daledupreez** [comment]
Functionally, this works as documented.

The one thing I found was that the text wasn't that easy to read, and I found it hard to pick out the domains that were involved. For me, the text was really dense and low-contrast, so I didn't pick up on the underlying CTA on my first pass. Maybe splitting the text up into three clear paragraphs would help with making it easier to read? Giving the domains some emphasis, like making them bold, could also help on that front.

@fditrapani, please feel free to weigh in on the design side of things. We can easily iterate on this if you'd prefer.

**Comment by fditrapani** [comment]
> Maybe splitting the text up into three clear paragraphs would help with making it easier to read? Giving the domains some emphasis, like making them bold, could also help on that front.

Good points @daledupreez. Splitting it up into paragraphs can definitely help with the radibility. The bolding might be much with three domain names listed there. I would split it up like this:

> Your existing domain, name.wordpress.com, is the primary domain people see when they visit your site. domain.tld will redirect to name.wordpress.com. 

> Upgrade to a paid plan to make domain.tld the domain people see when they visit your site.

**Comment by fditrapani** [comment]
I got my sandbox updated and was able to test this. This works as described!

**Comment by fditrapani** [comment]
Here's a quick mockup to help with breaking up the copy:

image

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/2830213

Thank you @eltongo for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/2830213).

**Pull request merged**
