### PR TITLE
Update ecommerce in /components

### PR DESCRIPTION
**Pull request by obenland**
#### Changes proposed in this Pull Request

* TODO: banner color & plan icon for ecommerce plan

#### Testing instructions

* Automated tests

### CODE REVIEW

**Comment by jhnstn** [comment]
@obenland can you get a screen shot of the banner and where you need the icon?
We can then get @dezzie to help us out with the design review

**Comment by obenland** [comment]
https://wpcalypso.wordpress.com/devdocs/design/banner shows the colors and also plan icons well.
Existing icons live in `/calypso/images/plans/plan-${ planName }-circle.svg`, existing banner colors are defined in https://github.com/Automattic/wp-calypso/blob/0f251755988c2b05f395b25e67d4e102228c06b3/client/components/plans/plan-icon/style.scss

/cc @dezzie

**Comment by jancavan** [comment]
> TODO: banner color & plan icon for ecommerce plan

@obenland  @jhnstn Updated banner component colors in: https://github.com/Automattic/wp-calypso/pull/28715#issuecomment-440763788

**Comment by sararosso** [comment]
@obenland I think this PR is now old? Can we close?

**Comment by obenland** [comment]
I think there are still new things in there. I was waiting on #28715 to go in. Let me rebase and go from there

**Comment by obenland** [comment]
Out of date, closing.

**Pull request closed without merging**
