### PR TITLE
Hosting Metrics: Modernize the header

### PR DESCRIPTION
**Pull request by danielbachhuber**
Fixes https://github.com/Automattic/dotcom-forge/issues/3389

## Proposed Changes

Modernizes the header according to design.

### Desktop

CleanShot 2023-08-10 at 15 34 12@2x

### Mobile

CleanShot 2023-08-10 at 15 36 37@2x

## Testing Instructions

1. Navigate to `/site-monitoring/<site>`.
2. Verify the header appears expected.

### CODE REVIEW

**Comment by danielbachhuber** [comment]
@javierarce Can you give this a look in calypso.live and let me know if there are additional tweaks you'd like?

**Comment by javierarce** [comment]
Thanks, @danielbachhuber, it looks good to me! There are just two things I would change: the distance between the subtitle and the tabs should be 24px, and we decided to use #EEEEEE for the bottom border.

image

cc: @nuriapenya @crisbusquets so you are aware of this implementation of the new page header ✨

**Comment by javierarce** [comment]
I just noticed one thing, the top margin/padding in mobile is too tight:
Screenshot 2023-08-10 at 10 38 06

**Review by sejas — COMMENTED** [review]
Working good. The only exception is the mobile version that @javierarce [commented](https://github.com/Automattic/wp-calypso/pull/80388#issuecomment-1672803205).

**Comment by nuriapenya** [comment]
@javierarce We introduced some changes last week per feedback: p9Jlb4-8ec-p2#comment-8802, one of them was removing the bottom border. But I guess here you mean the border on the tabs, right? Not sure if it's necessary either, as there's enough contrast with the background.

**Comment by javierarce** [comment]
> But I guess here you mean the border on the tabs, right? Not sure if it's necessary either, as there's enough contrast with the background.

Yes, I meant that border. For the PR version that has a dark background we could remove the border, but the original idea (7LKer2QaciNxdOgX7O9oqP-fi-104_16124) was to use a full white page, and then we'll need that bottom border to avoid the tabs floating in the page.

**Comment by danielbachhuber** [comment]
@javierarce @sejas This is ready for another look.

As a word of warning, the CSS is really dodgy. I'm not sure how much time I want to spend perfecting this implementation. I'd rather invest the time in producing the replacement component, and then swapping that in (although it might be a heavy investment in itself).

**Review by sejas — APPROVED** [review]
Nice!, It looks good to me!

## Screenshot of mobile version
Screenshot 2023-08-11 at 14 18 27

**Pull request merged**
