### PR TITLE
CPT: Adjust placement of thumbnail and action items on list screen

### LINKED ISSUE #6540: CPT: List View: Ellipsis more popover should have actions in the same order as Blog Posts actions
On Blog Posts we have the actions in the following order:

postslist-actions

I think the CPT posts list popover menu should be ordered in the same way (and eventually have the same actions): Edit, View, Stats, and Trash.

cpt-list-more

cc/ @aduth

### LINKED ISSUE #6542: CPT: List View: Canonical Image size, position, and crop adjustment
The Canonical Image is a little inconsistent right now and needs a little position adjustment, it should be spaced away from the ellipses 24px to be consistent with our grid. I'd also like it to move out of the 16px padding -8px (so it's 8px away from the edges of the card). It should be cropped in a square, so that there's more consistency in the list. The canonical image serves as just a visual indicator, so a crop should be fine.

cpt-list-canonicalimage

cc/ @aduth @mtias @folletto

### PR DESCRIPTION
**Pull request by aduth**
Closes #6540 
Closes #6542 

This pull request seeks to...

- Adjust the position of the post thumbnail relative to the action menu
- Reorder the action menu items to mirror that of the posts screen
- Use "Preview" as View action label unless post is published

Incidentally, it also increases the clickable area of the menu toggle button.

Before|After
---|---
Before|After

__Testing instructions:__

1. Navigate to the [custom post types list screen](http://calypso.localhost:3000/types/post)
2. Confirm that layout of thumbnail and menu match that as described in #6542
3. Toggle the action menu for a post
4. Confirm that menu items show in same order as on the [posts screen](https://wordpress.com/posts)
5. Verify that "Preview" is shown for drafts or scheduled posts, and that "View" is shown for published or privately published posts (and is not an option for trashed posts)

/cc @hugobaeta 

Test live: https://calypso.live/?branch=update/6540-6542-cpt-list-layout

### CODE REVIEW

**Comment by folletto** [comment]
Tested on Chrome, Safari, Firefox 👍 

Design wise it's good. Excellent enlargement of the ••• area.

A transversal comment not related to this PR: would be ideal that the image, when present, was clickable too. :)

**Comment by aduth** [comment]
>would be ideal that the image, when present, was clickable too. :)

I agree! #6327

**Comment by hugobaeta** [comment]
@aduth U agree, but not to enlarge the thumbnail. Clicking it should do the same as clicking the title: go to the edit screen. What do you think @folletto?

**Comment by folletto** [comment]
> Clicking it should do the same as clicking the title: go to the edit screen.

Yep! 👍

**Comment by folletto** [comment]
Actually @mtias pointed out that would be a regression. I added then a quick iteration on #6327 to keep the feature in for the new design, if you want to review it. :)

**Pull request merged**
