### PR TITLE
Bump WordPress.com Editing Toolkit plugin to v2.3

### PR DESCRIPTION
**Pull request by razvanpapadopol**
#### Changes included in this release

* https://github.com/Automattic/wp-calypso/pull/43980 (added to notes)
* https://github.com/Automattic/wp-calypso/pull/45280
* https://github.com/Automattic/wp-calypso/pull/45429 (added to notes)
* https://github.com/Automattic/wp-calypso/pull/44888
* https://github.com/Automattic/wp-calypso/pull/45423 (added to notes)
* https://github.com/Automattic/wp-calypso/pull/45502
* https://github.com/Automattic/wp-calypso/pull/45054 (added to notes)
* https://github.com/Automattic/wp-calypso/pull/45561 (added to notes)

#### Testing instructions

* Apply generated diff to sandbox
* Test changes listed in release notes are present
* Install build on an atomic site
* Test that editor works on atomic with and without gutenberg plugin enabled

### CODE REVIEW

**Comment by p-jackson** [comment]
Just confirming that #44888 is safe to merge because it doesn't do anything unless `WPCOM_PUBLIC_COMING_SOON` is defined (which it's not unless a dev does so for testing).

**Comment by p-jackson** [comment]
Added release notes for #45429, heads up in case you want to push something again.

**Review by p-jackson — APPROVED** [review]
Smoke tested editor on simple and atomic site. Changes I expected to see are included.

**Comment by ramonjd** [comment]
Adding in a teensy change to the sidebar nav: https://github.com/Automattic/wp-calypso/pull/45561

**Comment by p-jackson** [comment]
Rebased and added release notes for new features. Haven't written notes for things that don't impact the user.

**Comment by p-jackson** [comment]
Oops, 2.3 was released in D49336-code but this PR wasn't merged and I've ended up adding extra changes to it 🤦. I think I should be able to rearrange the commits to fix it up and also insert a 2.4 version bump as well.

**Review by wp-desktop — CHANGES_REQUESTED** [review]
WordPress Desktop CI Failure for job "wp-desktop-mac".

@p-jackson please inspect this job's build steps for breaking changes at [this link](https://circleci.com/gh/Automattic/wp-calypso/889126). For temporal failures, you may try to "Rerun Workflow from Failed".

Please also ensure this branch is rebased off latest Calypso.

**Comment by p-jackson** [comment]
2.4 PR #45660

**Pull request merged**
