### PR TITLE
Adds meatball menu to promote content in the Post and Page list

### PR DESCRIPTION
**Pull request by jjolmo**
#### Proposed Changes

A new entry to "Promote Post" in the meatball menu on "Post List" and "Page List" entries. Once the user clicks on this new entry the "Promote a Post" widget will display on the screen with the post information of the selected post (or page). It has some similarities to the entry point on the Stats page to open this "Promote a Post" widget.

Post list:
image

Page list:
image

#### Testing Instructions

- Enable the feature flag promote-posts either on [startup](https://wpcalypso.wordpress.com/devdocs/config/README.md#feature-flags:~:text=Testing%20Feature%20Flags,reader%20yarn%20start) or [via url](https://wpcalypso.wordpress.com/devdocs/config/README.md#feature-flags:~:text=Testing%20Feature%20Flags%20via%20URLs,and%20disables%20feature%20bar.) using the ?flags=promote-post query string on the following urls
- Visit the "Post list" page. Click on the meatball menu and click on "Promote Post" button. 
image

- The "Promote Post" widget should display in screen
- Only Posts and pages that are published will display this new entry menu.
- clicking the button should open the widget. However, this is not in production yet so without setting up your environment you can check the network tab and notice that it's trying to hit the script widget.js - this will repeatedly fail. In a working dev environment - it only ever loads the script once.
- This operation can be done also in "Pages List"

#### Pre-merge Checklist

- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [x] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [x] Have you checked for TypeScript, React or other console errors?
- [x] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [x] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?

Related to #

### CODE REVIEW

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/7467664

Thank you @jjolmo for including a screenshot in the description! This is really helpful for our translators.

**Review by benzhu56 — APPROVED** [review]
works like a charm!

**Comment by jjolmo** [comment]
Had issues with e2e. I will squash all the verbose from commits

**Review by gravityrail — APPROVED** [review]
I tried it and it works great. I will merge and deploy now.

**Comment by gravityrail** [comment]
(Looks like the squash fixed the e2e issues)

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/7467664).

**Pull request merged**
