### PR TITLE
Calypso UI Components: DateRange: firefox alignment fix

### PR DESCRIPTION
**Pull request by annacmc**
Related to #

## Proposed Changes

* Fixes the issue in FireFox only where the calendar is not centre aligned, creating an odd spacing/gap to the right. 

## Why are these changes being made?

* Use the Jetpack Cloud live link **using FireFox (important!)**
* Navigate to the `Activity Log`
* Check that the odd alignment issue is resolved
* Check in other browser to ensure consistency & no regressions

## Testing Instructions

| Before  | After |
| ------------- | ------------- |
| image  | image  |

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Comment by kangzj** [comment]
It seems to month switching buttons are out of position:

image

**Comment by kangzj** [comment]
When I set the max-width of the inputs to 224px, everything looks aligned with other browsers:

image

**Comment by ederrengifo** [comment]
Ideally it would be great if this spacing doesn't exist on Firefox so calendar and buttons are aligned with the rest of the elements as it happens in Chrome, however if that's not possible as Jasper suggests, it would be great to align the button with the calendar 🙏  Besides that, all looks good!

**Review by kangzj — APPROVED** [review]
It works well. Thanks for the fix! 🚀

**Pull request merged**
