### PR TITLE
Migrate help search fully to React Query

### PR DESCRIPTION
**Pull request by jsnajdr**
Finished migration of Help Search to React Query by migrating the `client/me/help/help-search` component away from the Redux implementation.

The `useHelpSearchQuery` hook is moved to `client/data/help` as it's imported from multiple places. I'm removing the `select` option that selects `data.wordpress_support_links` field because some consumers use the entire results, with all the fields. Components need to do the `wordpress_support_links` selection themselves.

The `withInlineHelpSearchResults` HOC is being removed and the `PopupSearch` component is migrated to use the hook directly (it was already a functional component)

The Redux state (`QueryHelpLinks`, `state.help.links`, `getHelpLinks`, data layer handler) is completely removed.

**How to test:**
Test all three places where help search happens:
- inline help popup
- My Home page
- `/help` page
- action search in masterbar with the `wordpress_support_links` feature flag enabled

### CODE REVIEW

**Comment by flootr** [comment]
@jsnajdr have you seen https://github.com/Automattic/wp-calypso/pull/56502? Happy to close that in favor of your PR. I put it back in to _progress_ state because I planned on more changes in `HelpSearch` but they can easily be a follow up, too.

**Comment by jsnajdr** [comment]
> have you seen #56502?

Oops I didn't 🙁 I worked on this because I wanted to remove data layer from the Inline Help widget -- it's used only at 4 places there and the entire middleware can be removed after these 4 places are migrated.

I'll compare both versions. Seems that my PR is mostly identical to yours, I only do one extra thing: remove the `withInlineHelpSearchQuery` HOC and migrate the `PopUpSearch` not to use it.

**Comment by flootr** [comment]
No worries. Let's continue with yours 🙂👍🏻

**Comment by jsnajdr** [comment]
> Let's continue with yours

I did the opposite: I rebased my PR onto your one. There were almost no conflicts, as we changed the same code identically. Then I pushed several more commits to #56502. This one can be closed.

**Pull request closed without merging**
