### PR TITLE
Remove processing: enable flag

### PR DESCRIPTION
**Pull request by andres-blanco**
Related to #

## Proposed Changes

This effectively removes the processing step in `site-migration` and directs the user to the new instructions screen with the inline spinners.
This should be merged after https://github.com/Automattic/wp-calypso/pull/90328

## Testing Instructions

Run ` yarn feature-search migration-flow/remove-processing-step` and verify this is the output

image

Go through the site migration flow and verify you see the new instructions screen in the end.
## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Comment by andres-blanco** [comment]
@gabrielcaires tests fail here because we changed the flow. I tried adjusting the tests to exercise both paths without success. I've bumped into all kinds of strangeness when mocking the isEnabled function. What do you think the correct approach in this case is? I've linked below to a PR with the actual mocking, but feels strange. I've made this Slack discussion about this: p1715024871796379-slack-C0Q664T29

**Comment by daledupreez** [comment]
I am having issues with the post-checkout flow. Investigating further.

**Comment by andres-blanco** [comment]
> I am having issues with the post-checkout flow. Investigating further.

This is the branch you started: https://github.com/Automattic/wp-calypso/pull/90433, probably we should get that in before this one

**Comment by markbiek** [comment]
Noting that there's an update to the email verification redirect that should be deployed once this has shipped.

D148071-code

**Review by markbiek — APPROVED** [review]
LGTM!

**Pull request merged**
