### PR TITLE
Global Styles: Add error handling to avoid the page crash

### PR DESCRIPTION
**Pull request by arthur791004**
Related to p1691576959289179-slack-C02FMH4G8

## Proposed Changes

* Made `@automattic/calypso-sentry` package so we can send messages to sentry outside the client scope
* Wrap `useGlobalStylesOutput` hook to catch any internal error and send logs to sentry

## Testing Instructions

* Revert D118678-code on your sandbox, and disable the cache
* Go to Theme Showcase
* Search for "Zaino"
* Go to the Theme Details Page of the “Zaino” theme
* Ensure the page won't crash

## Pre-merge Checklist

- [x] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [x] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [x] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [x] Have you checked for TypeScript, React or other console errors?
- [x] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [x] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [x] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

**Comment by taipeicoder** [comment]
The theme Alonso currently has issues with global styles, see: p1692103707648319-slack-C04DZ8M0GHW

**Comment by arthur791004** [comment]
I think I got the root cause that the base global styles we used in the Theme Details Page have the wrong format, e.g.: Missing `styles.blocks`, etc. So it makes `useGlobalStylesOutput` crash [here](https://github.com/WordPress/gutenberg/blob/f57fa043b126625840a0e95018318ab56545cf00/packages/block-editor/src/components/global-styles/use-global-styles-output.js#L1208).

I prefer to deploy this one to avoid the crash and propose another PR to fix the issue. WDTY?

**Review by taipeicoder — APPROVED** [review]
LGTM 🎉 

Screenshot 2023-08-16 at 11 25 38 AM

**Comment by taipeicoder** [comment]
> I think I got the root cause that the base global styles we used in the Theme Details Page have the wrong format, e.g.: Missing `styles.blocks`, etc. So it makes `useGlobalStylesOutput` crash [here](https://github.com/WordPress/gutenberg/blob/f57fa043b126625840a0e95018318ab56545cf00/packages/block-editor/src/components/global-styles/use-global-styles-output.js#L1208).
> 
> I prefer to deploy this one to avoid the crash and propose another PR to fix the issue. WDTY?

Sounds good! Let's merge this one, and fix the underlying issue in another PR. There's already an issue tracking this https://github.com/Automattic/dotcom-forge/issues/3476

**Pull request merged**
