### PR TITLE
State: Move inline help selectors

### LINKED ISSUE #42697: (5P) Port existing Inline Help state selectors to global state directory
There can be a follow up janitorial to move the rest the selectors in inline-help, since we don't want these to grow in the file.

_Originally posted by @gwwar in https://github.com/_render_node/MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDQzMDc1MDA3MQ==/comments/review_comment_

-------------

Move all the selectors currently in `client/state/inline-help/selectors.js` to individual selector files in the global state directory in `client/state/selectors`.

Add unit test coverage (or migrate existing).

### PR DESCRIPTION
**Pull request by retrofox**
#### Changes proposed in this Pull Request

This PR moves all the selectors currently in `client/state/inline-help/selectors.js` to individual selector files in the global state directory in client/state/selectors, and update where these selectors are imported. Also, it moves and updates the currents tests.

#### Testing instructions

* Execute Unit tests for all global selectors.

```
> cd test/client
> yarn run test-client client/state/selectors/
```

* Check that either `Get Help` section in the customer home page is working as expected, as well as the `Inline Help Popover`. Check it records tracks events too.

* A visual code inspection is also a welcomed to test this PR

Fixes https://github.com/Automattic/wp-calypso/issues/42697

### CODE REVIEW

**Review by obenland — COMMENTED** [review]
Testing My Home, `/help`, and the FAB on calypso.live looks good, no errors that I could tell.
I don't know what the lint CI test is trying to tell us, any idea?

Before I ✅  it, let's give @getdave a chance to look it over, too

**Comment by retrofox** [comment]
> I don't know what the lint CI test is trying to tell us, any idea?

👀 

> Before I ✅ it, let's give @getdave a chance to look it over, too

👍 to me

**Comment by retrofox** [comment]
> I don't know what the lint CI test is trying to tell us, any idea?

I think 🤞 they have been addressed here 26492b07d96051065c813c5363c20ba1f47f9a38

**Review by getdave — APPROVED** [review]
I also manually tested in both locations in Calypso and everything still works.

That said this is a perfect example of where [having e2e tests to cover this](https://github.com/Automattic/wp-calypso/pull/43381) would provide a lot more confidence in making changes.

I also ran unit tests and they all still passed!

**Comment by sgomes** [comment]
Hey @retrofox!

I just saw this PR as it was being discussed in Slack, and noticed that while the selector modularisation is a great improvement (it makes it easier for the bundler to tree-shake effectively), it's taking a small step back with regards to file organisation. Due to the ongoing [state modularisation effort](https://github.com/Automattic/wp-calypso/blob/master/docs/modularized-state.md), the best practice that emerged is actually to have selectors live within their branch of the state tree, rather than in one gigantic folder with all selectors. This reflects the structure used for action creators as well and helps to keep things organised.

You can take a look at the [modularised state documentation](https://github.com/Automattic/wp-calypso/blob/master/docs/modularized-state.md) and [our approach to data](https://github.com/Automattic/wp-calypso/blob/master/docs/our-approach-to-data.md) for some background, but here's the relevant suggested structure:

```
client/state/
├── index.js
├── action-types.js
└── { subject }/
    ├── actions/
    |   ├── index.js
    |   ├── action1.js
    |   └── action2.js
    ├── init.js          (for modularized state)
    ├── package.json     (for modularized state)
    ├── reducer.js
    ├── schema.js
    ├── selectors/
    |    ├── index.js
    |    ├── selector1.js
    |    └── selector2.js
    └── test/
        ├── actions.js   (or actions/)
        ├── reducer.js
        └── selectors.js (or selectors/)
```

Again, this is not an issue at all; having things in `state/selectors/` doesn't stop or slow down modularisation, and that's still the case for a ton of state, both modularised and unmodularised. I'll probably do a large pass on that once modularisation is complete. This is more of a heads-up in case you were planning any similar future work! 🙂

**Pull request merged**
