### PR TITLE
Client: Move PostCSS config to client dir

### PR DESCRIPTION
**Pull request by ockham**
#### Changes proposed in this Pull Request

Client: Move PostCSS config to client dir, to co-locate it more with the code it's actually for.

Follow-up to https://github.com/Automattic/wp-calypso/pull/38190#issuecomment-575546666

#### Testing instructions

Verify that the app still builds and runs.

### CODE REVIEW

**Comment by sirreal** [comment]
How do we verify this is working? I tried to force it to break, but it worked fine so I'm not confident in just starting the app as a good test. This works:

```diff
diff --git a/client/webpack.config.js b/client/webpack.config.js
index e69ec5950d..8edca4918b 100644
--- a/client/webpack.config.js
+++ b/client/webpack.config.js
@@ -154,7 +154,7 @@ const webpackConfig = {
 			} ),
 			SassConfig.loader( {
 				includePaths: [ __dirname ],
-				postCssConfig: { path: __dirname },
+				postCssConfig: { path: path.join( __dirname, 'foo.js' ) },
 				prelude: `@import '${ path.join( __dirname, 'assets/stylesheets/shared/_utils.scss' ) }';`,
 			} ),
 			{
```

**Comment by ockham** [comment]
> How do we verify this is working? I tried to force it to break, but it worked fine so I'm not confident in just starting the app as a good test. This works:
> 
> ```diff
> diff --git a/client/webpack.config.js b/client/webpack.config.js
> index e69ec5950d..8edca4918b 100644
> --- a/client/webpack.config.js
> +++ b/client/webpack.config.js
> @@ -154,7 +154,7 @@ const webpackConfig = {
>  			} ),
>  			SassConfig.loader( {
>  				includePaths: [ __dirname ],
> -				postCssConfig: { path: __dirname },
> +				postCssConfig: { path: path.join( __dirname, 'foo.js' ) },
>  				prelude: `@import '${ path.join( __dirname, 'assets/stylesheets/shared/_utils.scss' ) }';`,
>  			} ),
>  			{
> ```

:thinking: 

Maybe it's truncating the filename? (So maybe try with a different directory, rather than a file path?) FWIW, it did break _without_ that line.

(The docs say that it needs a dir rather than a file: https://github.com/postcss/postcss-loader#path)

**Review by sirreal — APPROVED** [review]
👍 Working well. In my initial testing, config cascade would look up in the directory hierarchy and find the config under `client`. Changing it to point to the `bin` directory does break.

**Review by jsnajdr — APPROVED** [review]
Works for me. Before this patch, the `postcss.config.js` was in a path where a cascading parent directory lookup would find it for all compiled SCSS files, including these in `packages/`. Now the path needs to be specified explicitly :+1:

**Comment by ockham** [comment]
Thanks for reviewing, @sirreal and @jsnajdr!

**Pull request merged**
