### PR TITLE
Fix whitespace (spaces to tabs)

### PR DESCRIPTION
**Pull request by p-jackson**
#### Changes proposed in this Pull Request

* Fixes whitespace

#### Testing instructions

*

Related to #

### CODE REVIEW

**Review by roo2 — COMMENTED** [review]
Thanks for catching this! It looks like other files I touched in https://github.com/Automattic/wp-calypso/pull/54059 were affected. I'm trying to workout why my editor added spaces, it seems to use tabs when I retest now... If you're not already working on it, I'll add fixes to other files to this PR.

**Comment by p-jackson** [comment]
> If you're not already working on it, I'll add fixes to other files to this PR.

Please do

**Review by roo2 — APPROVED** [review]
ok, I've added other affected files and set my editor to run format on save for modified lines which should prevent this kind of whitespace error in the future 😅

**Comment by p-jackson** [comment]
Thanks 👍 
I'm about to log off so feel free to deploy, otherwise I'll do it Monday 👋

**Comment by roo2** [comment]
sounds good, thanks for noticing this, and enjoy! 👋

**Pull request merged**
