### PR TITLE
My Home: Update return copy for site title guided tour to reference My Home

### PR DESCRIPTION
**Pull request by sixhours**
#### Changes proposed in this Pull Request

* Updates "Return to the checklist" to say "Return to My Home" for more consistent naming in navigation
* Do we need to include `context` in the translation for the section name `My Home`?

**Before**

Screen Shot 2020-03-25 at 9 59 42 AM
Screen Shot 2020-03-25 at 9 59 32 AM

**After**

Screen Shot 2020-03-25 at 10 00 47 AM
Screen Shot 2020-03-25 at 10 32 35 AM

#### Testing instructions

* Switch to this PR
* Activate the guided tour by going to `/settings/general/{site}/?tour=checklistSiteTitle`
* The first prompt has a return link that should say "Return to My Home"
* Update the site title and follow the remaining prompts
* The last prompt's primary action should read "Return to My Home" rather than "Return to the checklist"

### CODE REVIEW

**Comment by sixhours** [comment]
I'd like to follow up with a PR to remove that underline on the button on the last tour section, since that doesn't line up with our current button styles. Saving it for a separate PR since that will affect other guided tours, though.

**Review by gwwar — APPROVED** [review]
Thanks @sixhours, this tests well for me!

Screen Shot 2020-03-25 at 10 18 31 AM
Screen Shot 2020-03-25 at 10 19 07 AM

**Comment by sixhours** [comment]
It looks like this is still waiting on strings for translation, is that right?

**Comment by gwwar** [comment]
It's 94% translated. @sixhours I think it's fine to land this after rebasing and fixing conflicts.

**Pull request merged**
