### PR TITLE
Comments: Replace the like button with the LikeButton component

### LINKED ISSUE #13910: Comments: like
When we click on a like button, the user likes the current moderation comment.

(Does the comment need to be approved before it can be liked?)

### PR DESCRIPTION
**Pull request by Copons**
Closes #13910

Alternative to #15932

In the previous PR started by @rodrigoi and continued by me, we created a new `CommentLikes` component from scratch to add to Comment Management a multi-state like button that also showed the like count.
Initially it was a fully connected component, pulling the like information from the state and autonomously dispatch the like and unlike actions.
To reduce the additional burdens on the data layer, I've removed the dispatches but left the Redux connection for the state.

I had some doubts about creating a new `CommentLikes` component, considering we already have several similar components around, used by the Reader and the Post List.
On top of that, at some point I realized that `CommentDetail` already has all the like information we need, de facto removing the need to pull them from the state.

So, instead of creating `CommentLikes`, I'm proposing to simply reuse `LikeButton`, which already takes care of showing the like count and even has a nice little animation (it can be disabled, if it looks too different compared to the other actions).

There are two possible downsides though:

- `LikeButton` has quite a different structure, and required a bit of CSS rework.
Nothing major, and in my opinion is better to have ~30 new CSS lines than a whole new component that might be confusing.

- Even if `LikeButton` _has_ the "Liked" label state (that should appear when the comment has only one like, and that like is from the current user), it's only displayed if we choose to _not_ display the like count (making the button a "Like/Liked", which is basically what we currently have).
Instead, it appears as "1 Like" with the orange highlight color.
It's worth noting that this is the current behaviour of both the Reader and the Post List.
Though, we could make some minor changes to `LikeButton` to make it display "Liked" anyway.

---

Props to @rodrigoi for introducing the like count in Comment Management and @kwight for making me realize we already had a `LikeButton` component.

cc @Automattic/lannister

### CODE REVIEW

**Comment by drw158** [comment]
One Like button to rule them all?

Let's keep the current behavior:

- Like/Liked
- no like count
- probably no animation to be consistent with the other buttons

**Comment by rodrigoi** [comment]
I wake for my slumber to say: LikeButton is a mess. I think we should remove LikeButton from Posts and the Reader in favor of a simpler, happier implementation.

**Comment by kwight** [comment]
> I think we should remove LikeButton from Posts and the Reader in favor of a simpler, happier implementation.

If `LikeButton` is this bad, it sounds like a bigger project after Comments M1 is out the door. (All of my comments these days are about getting M1 out the door 😜)

**Comment by kwight** [comment]
The animation of unliking is different (and more awkward) than liking; did I hear @drw158 say at some point not to have the animation at all?.. May be making that up. :)

**Comment by Copons** [comment]
Ah! Sorry people, I was too slow to close this as well as the other because...

> Closing this PR because it turned out we don't really want the like count to be shown in the Comment Management.

And yeah: we can tackle a new like button, but it's outside the Comment Management scope.

**Comment by drw158** [comment]
probably no animation to be consistent with the other buttons

**Pull request closed without merging**
