### PR TITLE
TinyMCEDropZone Plugin: Remove sites-list

### PR DESCRIPTION
**Pull request by ehg**
Ignoring createClass error.

Part of https://github.com/Automattic/wp-calypso/issues/8726

### CODE REVIEW

**Comment by mtias** [comment]
@ehg yo, how's this one looking?

**Comment by ehg** [comment]
Open for review, as are all my other tiny ones. Again, ignoring eslint, because — yeah, codemods.

**Comment by alisterscott** [comment]
Closing as this PR is stale - please reopen if necessary

**Comment by jsnajdr** [comment]
Oops, I duplicated this PR in #20095 (already merged). Didn't notice this one before.

**Pull request closed without merging**
