### PR TITLE
TokenField: Add snapshot test

### PR DESCRIPTION
**Pull request by sirreal**
While looking at #19003 I was inspired to add a snapshot test. Also for my own benefit to explore snapshot testing now that we use Jest.

/cc @seear

### CODE REVIEW

**Comment by seear** [comment]
That is a large snapshot. Be interesting to see how hard it is to decipher if `<TokenField />` changes.

**Comment by seear** [comment]
If this was merged without rebasing, presumably the test would fail on master because #19003 has landed?

**Comment by sirreal** [comment]
> If this was merged without rebasing, presumably the test would fail on master because #19003 has landed?

I just rebased and pushed. Let's see what happens 😁 

Locally, snapshot passes. The changes in #19003 shouldn't affect the tree structure, so that's as expected.

**Comment by ockham** [comment]
Oh, so maybe I should've waited for this to land before merging #19003. Oops.

**Comment by seear** [comment]
> Oh, so maybe I should've waited for this to land before merging #19003. Oops.

Well it is no trouble to rebase this one. I was more interested about the situation where a snapshot test PR cannot flag up that a rebase is needed. Same goes for any testing PRs, though.

**Pull request merged**
