### PR TITLE
Notifications: Relative Sizing for Header Elements

### LINKED ISSUE #46111: Notifications: Heading blocks need relative sizing.
While alignment works for Heading blocks, their size and styling is all the same when rendered in notifications.

Screen Shot 2020-10-01 at 3 23 26 PM

### PR DESCRIPTION
**Pull request by krymson24**
#### Changes proposed in this Pull Request
* I initially took a mathematical approach. p tags on the browser are normally 16px, but on WordPress, it is 14px. I took the size of the headers that the browser set by default, and then reduced them at the same rate. I only applied these to h1 to h3, since by some competitive research, h4-h6 are ignored.
* I got this linting error:

```
36:14  ✖  Expected "2.742rem" to be one of "0.75, 0.875, 1, 1.25, 1.5, 2, 2.25, 3, 3.375" with unit "rem"   scales/font-size
 40:14  ✖  Expected "2.057rem" to be one of "0.75, 0.875, 1, 1.25, 1.5, 2, 2.25, 3, 3.375" with unit "rem"   scales/font-size
 44:14  ✖  Expected "1.542rem" to be one of "0.75, 0.875, 1, 1.25, 1.5, 2, 2.25, 3, 3.375" with unit "rem"   scales/font-size
```

So I tried each bounds of constraints that were closer to my calculations.

Option A | Option B
--- | ---
Screen Shot 2020-10-06 at 6 56 07 PM | Screen Shot 2020-10-06 at 6 57 20 PM

The latter seems more reasonable in this case, given the constraints and relative to the other text sizes, so I chose Option B.

#### Testing instructions
1. Checkout this branch
2. See the"Creating post notification" section in README at apps/notifications/src/doc/note-rendering.md
3. Use the "Follow" button that appears in the bottom right corner of the blog to add it to your Reader subscriptions. Then navigate to https://wordpress.com/following/manage and enable "Notify me of new posts" for the blog. With this enabled, future posts on that blog will appear as notifications in your masterbar.
4. Create a post for the blog you're following with the header tags h6, h5, h4, h3, h2 and h1.
5. Go to your masterbar and select the notification that contains the styling. Confirm the headers are styled with relative sizing (h1 being the largest, h6 being the smallest)

Before | After
--- | ---
Screen Shot 2020-10-06 at 5 20 18 PM | Screen Shot 2020-10-06 at 6 57 20 PM

Fixes #46111

### CODE REVIEW

**Comment by kwight** [comment]
> I read through the suggestions in the issue and initially applied sizing suggests for each header tag, however, found that the sizes were very arbitrary and would introduce code that would result in unexpected behaviour

What was the unexpected behaviour?

> I found that browsers apply their own header styles, and found that we're "resetting" those styles.

Indeed, but also very common when creating your own text ratio contexts (like how we reset `p` font sizes and apply our own appropriate to our notifications designs).

I'd still stick to applying our own nicer styles on top of the reset, as opposed to modifying the reset stylesheet for one set of tags. This approach will also allow `h5` and `h6` to have a font size not smaller than the paragraph size, and all-caps to still stand out.

**Comment by krymson24** [comment]
> > I read through the suggestions in the issue and initially applied sizing suggests for each header tag, however, found that the sizes were very arbitrary and would introduce code that would result in unexpected behaviour
> 
> What was the unexpected behaviour?
> 
> > I found that browsers apply their own header styles, and found that we're "resetting" those styles.
> 
> Indeed, but also very common when creating your own text ratio contexts (like how we reset `p` font sizes and apply our own appropriate to our notifications designs).
> 
> I'd still stick to applying our own nicer styles on top of the reset, as opposed to modifying the reset stylesheet for one set of tags. This approach will also allow `h5` and `h6` to have a font size not smaller than the paragraph size, and all-caps to still stand out.

The approach I initially took was to add font sizes for every header class -- `wpnc__h1`, etc.

**Review by kwight — APPROVED** [review]

**Review by sixhours — COMMENTED** [review]
Option B looks good to me! 

Not a blocker, but you can also use Sass variables instead of rems (so if we update the type scale in the future, these values will change, too). `/devdocs/typography` has more info at the very bottom about the scale and the variables.

**Review by sixhours — APPROVED** [review]
Huzzah!

Screen Shot 2020-10-08 at 1 36 46 PM

**Pull request merged**
