### PR TITLE
Update FSE to version 1.4

### PR DESCRIPTION
**Pull request by Addison-Stavlo**
#### Changes proposed in this Pull Request

* Version bump and changelog.

Remaining PRs for this release:
- [x] https://github.com/Automattic/wp-calypso/pull/42027
- [x] https://github.com/Automattic/wp-calypso/pull/41966
- [x] #42077

#### Testing instructions

* Apply this build, test changes since the last release found at: https://github.com/Automattic/wp-calypso/commits/master/apps/full-site-editing.
*  Test on atomic sites as well as outlined here: PCYsg-ly5-p2

We can rebase this PR as more changes are merged if necessary.

### CODE REVIEW

**Comment by sirreal** [comment]
Rebased, we should have both #42027 #41966 included now.

**Comment by sirreal** [comment]
Added https://github.com/Automattic/wp-calypso/pull/42077 to the list.

**Comment by Addison-Stavlo** [comment]
Rebased for #42077

**Comment by sirreal** [comment]
e2e failures are unrelated. These are changes to files that aren't deployed in Calypso.

**Pull request merged**
