### PR TITLE
Link the Let's work on your site button to the full screen launchpad

### PR DESCRIPTION
**Pull request by TimBroddin**
Related to #85197

## Proposed Changes

This changes the href of the Let's work on your site button you see after you've upgraded your plan:
- If you still have tasks to be completed on the Launchpad, it links to the full screen launchpad
- Else it links to `/home`

## Testing Instructions

- Start on https://wordpress.com/start
- Start a free site, choose an intent that lands you in the build intent (other, promote, ...), choose a design and skip somewhere during the launchpad (click Skip for now)
- Upgrade your site to a paid plan (give yourself some free credits through User RC)
- You'll land on the Thank You screen. Replace `https://wordpress.com/ `in your address bar with `http://calypso.localhost:3000`

Please verify that the button links to the launchpad while there are still tasks open, and links to home when the launchpad is completed.

Beware that two tasks can't be finished in the launchpad itself:
- Write first post
- Launch your site

However, when linking to the launchpad with these tasks still open, the launchpad will redirect to /home, which is the behavior we want.

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

**Comment by TimBroddin** [comment]
Hey @daledupreez 👋

I've added you as a reviewer since I'm not 100% confident that this is the way to go, to load the full-screen launchpad after it's been skipped:

```js
// when launchpad is off or skipped, we need to update the launchpad_screen option to full
// otherwise the full screen launchpad will redirect to /home straight away
saveSiteSettings( siteID, { launchpad_screen: 'full' } ).then( () => {
	setLetsWorkButtonBusy( false );
	window.location.assign( letsWorkHref );
} );
```

**Comment by JuanLucha** [comment]
Hi, @TimBroddin !
The behavior is correct, but there is a visual glitch:

https://github.com/Automattic/wp-calypso/assets/3832570/86755cbd-1f19-43e5-8b34-f25961b3ca17

**Comment by TimBroddin** [comment]
> Hi, @TimBroddin ! The behavior is correct, but there is a visual glitch:
> 
>  Screen.Recording.2024-01-10.at.14.11.19.mov

I wouldn't call that a glitch, it's a redirect that happens when you try to navigate to the launchpad and it shouldn't be shown (because it's disabled, ...). This shouldn't happen.

Could you add a debugger statement at line 33 here to see why it redirects? 

`client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/index.tsx`

**Review by JuanLucha — APPROVED** [review]
Very nice! The launchpad is not shown anymore before the redirection to home 👍

**Comment by TimBroddin** [comment]
> Hey @daledupreez 👋
> 
> I've added you as a reviewer since I'm not 100% confident that this is the way to go, to load the full-screen launchpad after it's been skipped:
> 
> ```js
> // when launchpad is off or skipped, we need to update the launchpad_screen option to full
> // otherwise the full screen launchpad will redirect to /home straight away
> saveSiteSettings( siteID, { launchpad_screen: 'full' } ).then( () => {
> 	setLetsWorkButtonBusy( false );
> 	window.location.assign( letsWorkHref );
> } );
> ```

Hey @daledupreez 👋 

Is this (see above) something we can do?

**Comment by TimBroddin** [comment]
This needs a rebase because of refactoring changes in https://github.com/Automattic/wp-calypso/commit/a465130effe7b05e5afcf8a9fd980ff8982fa380

**Comment by TimBroddin** [comment]
Somehow my merge got screwed up. Sorry for anyone who was notified 🫠

**Comment by TimBroddin** [comment]
New PR: https://github.com/Automattic/wp-calypso/pull/86575

**Pull request closed without merging**
