### PR TITLE
Add evergreen A/A test to /pages

### PR DESCRIPTION
**Pull request by jessie-ross**
#### Changes proposed in this Pull Request

This PR adds an "evergreen" A/A test to `/pages`.
- A/A tests are special experiments that help us ensure our Experimentation Platform is working smoothly.
- "Evergreen" as it automatically changes every week, providing a new experiment name.
- This change is intended to stay in place long term and allows us to continually perform 
   A/A tests on this code without needing to PR them.

This change should not affect the behaviour/structure of the page, it only ensures that an assignment API request is called at least one time. The request is performed async and it occurs at most one time.

See the core issue at 449-gh-experimentation-platform

And the previous A/A test https://github.com/Automattic/wp-calypso/pull/42093

#### Testing instructions

* There are currently no other tests running so we can confirm that this change causes a call to experiments API - easy to check by searching for `experiment` in the dev console.
* An `<Experiment>` component should show in React DevTools, check that the name attribute is correct.

### CODE REVIEW

**Review by withinboredom — APPROVED** [review]
Looks simple enough :)

**Review by yanirs — APPROVED** [review]
Nice and simple! :ship:

**Review by aaronyan — APPROVED** [review]
Cool, our very first evergreen experiment! 🌲  Love the name!

**Comment by jessie-ross** [comment]
Moved to https://github.com/Automattic/wp-calypso/pull/46514 per p1602827396225600-slack-C02DQP0FP

**Pull request closed without merging**
