### PR TITLE
Quick links: list Jetpack functionalities for Business or Commerce sites

### PR DESCRIPTION
**Pull request by mpkelly**
Related to https://github.com/Automattic/dotcom-forge/issues/2665

## Proposed Changes

* List Jetpack features in Quick Links to help promote plan. Changes have been made for devs and non-devs with Business or eEcommerce sites. Simple sites remained unchanged. 
* Speed up your site -> `https://${ siteSlug }/wp-admin/admin.php?page=jetpack-boost` 
* Restore a back -> `/backup/${ siteSlug }`

| Simple | Devs with Atomic | Non-devs with Atomic |
| ------------- | ------------- | ------------- |
| Screenshot 2566-06-26 at 16 34 41 | image  | image  |

## Testing Instructions

* Try visiting `/home` for 
    - Atomic site with Dev account
        * with Boost
        * without Boost 
    - Atomic site without Dev account
        * with Boost
        * without Boost 
    - Simple site
* I had to add some extra styling for the Jetpack logo - can you think of a better way to render this icon?
* Are the links pointing to where you expect them to?
* Should we show these links even if the Jetpack user hasn't got Boost and Backup?
* Try it with a RTL language or with a different theme

image

## Pre-merge Checklist

- [x] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [x] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

**Comment by zaguiini** [comment]
Works fine! Waiting for @ederrengifo's blessings in case he'd like to reorder the items.

**Comment by mpkelly** [comment]
I spoke to @ederrengifo on Slack. 

>Are the links pointing to where you expect them to?

I am waiting for them to confirm this

>Should we show these links even if the Jetpack user hasn't got Boost and Backup?

They said these should only be shown if these features are enabled, so I will use additional checks like `productHasBoost`.

**Comment by mpkelly** [comment]
I made another commit which shows the links only if the features are available.

An atomic plan without Boost

image

An Atomic plan with Boost

image

I've been speaking with  @ederrengifo on Slack and he thinks this can be merged. @Automattic/quake, please give a review and then feel free to merge it.

**Review by p-jackson — APPROVED** [review]
The way the jetpack icon is handled seems fine to me. `<ActionBox>` already has multiple ways it supports icons, so adding a new "arbitrary component" way to the list seems fine.

I thought, why not also guard the backup button behind a `jetpack_connection_active_plugins` check? The backup feature is just another Jetpack feature that can be disabled. However as far as I can tell there doesn't seem to be a way to turn it of on a WoA site. So checking if it's in the plan is fine.

**Comment by mpkelly** [comment]
Thanks for working on this, @p-jackson. 

> However as far as I can tell there doesn't seem to be a way to turn it of on a WoA site. So checking if it's in the plan is fine.

At first, I was going to use `isAtomic`, which I figured was enough. But checking for a specific feature seems more future-proof and doesn't assume backups will always be free on Business.

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/8244222

Thank you @mpkelly for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/8244222).

**Pull request merged**
