### PR TITLE
100-year-plan: Style thank you step and handle on appointment schedule event

### PR DESCRIPTION
**Pull request by bogiii**
Related to #

## Proposed Changes

- Matched "Thank You" step design

Figma: Qn8lSkQCQHwd2xZPaMTYjI-fi-5910_3400

## Testing Instructions

* Go to /setup/hundred-year-plan/diy-or-difm?flags=100year%2Fvip
* Select a time slot
* Check if there is "Thank you" step at the end of the flow
* Check the if "View guide" button leads to support doc page

NOTE: The button style has not been updated to match the design; I wanted to be consistent and use it from the `@wordpress/components` package. But I'll check with the designer and probably match it in the next PR.

Screenshot 2024-10-09 at 23 11 12

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Review by ouikhuan — APPROVED** [review]
LGTM!

**Comment by fditrapani** [comment]
Nice work on this @bogiii! Looks great! I have two very minor things:
- When you reach the end of the flow we're showing an image of the earth. My intention there was to use an existing video that we use after you complete the 100 year plan purchase. Let me know if you need help tracking it down. 
- The button styles look fine. Any chance we can remove the grey border from here:
  image

**Comment by bogiii** [comment]
> When you reach the end of the flow we're showing an image of the earth. My intention there was to use an existing video that we use after you complete the 100 year plan purchase. Let me know if you need help tracking it down.

Sure, I just saw it for the first time. I can reuse it.

> The button styles look fine. Any chance we can remove the grey border from here:

Yes, we can do it. 👍

**Comment by fditrapani** [comment]
Thank you @bogiii!

**Comment by bogiii** [comment]
It's covered here: https://github.com/Automattic/wp-calypso/pull/95291

**Pull request closed without merging**
