### PR TITLE
Publicize: Change design for disabled publicize

### PR DESCRIPTION
**Pull request by artpi**
Before

After
screen shot 2016-12-30 at 14 16 35 pm

Turns out, that issue is only for internal sites, private sites are behaving as usually

### CODE REVIEW

**Comment by beaulebens** [comment]
While this works, would it make more sense to completely disable the "Share" icon/link? If sharing of all kinds are disabled for the site, then there's no point really allowing any clicking/interacting there, right?

Either way though, this works, and I guess it's a pretty edge-case.

**Comment by artpi** [comment]
> While this works, would it make more sense to completely disable the "Share" icon/link?

I was thinking about it, but I am not sure is a good UX, because the UI would be inconsistent then, User could be left with "Did share stop working?" question and there the case of appearing / disappearing share button would be a conundrum.
Also, it would make post list look inconsistent. 
I would like some design input on all this @drw158  ?

**Comment by beaulebens** [comment]
Oh! I definitely don't mean remove it, for the reasons you mention above. I was thinking more along the line of greying it out or something. Maybe have one of those tooltips if you click it, explaining why it's disabled. Something like:

screen shot 2017-01-02 at 8 40 49 am

**Comment by gziolo** [comment]
> I definitely don't mean remove it, for the reasons you mention above. I was thinking more along the line of greying it out or something. 

Sounds like a better approach 👍

**Comment by drw158** [comment]
> While this works, would it make more sense to completely disable the "Share" icon/link?

I like that idea! Just disabling the button seems better to me.
👍 

As far as the text goes, what makes it "permanently" disabled? Can't they change the site to public? Is that message just for a8c sites?

**Comment by gziolo** [comment]
Final solution as discussed. We display `Share` link in the disable state:

screen shot 2017-01-13 at 11 48 33

**Comment by drewblaisdell** [comment]
LGTM and works as expected. :+1:

**Pull request merged**
