### PR TITLE
A4A > Feedback: Handle save feedback

### PR DESCRIPTION
**Pull request by yashwin**
Related to https://github.com/Automattic/automattic-for-agencies-dev/issues/1246
Previous PRs:
* https://github.com/Automattic/wp-calypso/pull/96934
* https://github.com/Automattic/wp-calypso/pull/97100

## Proposed Changes

* Handle sending feedback data to the API

## Why are these changes being made?

*

## Testing Instructions

* Follow the testing instructions in https://github.com/Automattic/wp-calypso/pull/97100
* Also check the following:
  * After submitting feedback, you see a success notice.
  * The feedback is posted to Slack (see D168071-code).
  * The feedback is saved to the db (see D168071-code).

Screenshot 2024-12-09 at 2 49 06 PM

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
    - [ ] For UI changes, have we tested the change in various languages (for example, ES, PT, FR, or DE)? The length of text and words vary significantly between languages. 
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Comment by travisw** [comment]
This now works with the `/marketing/survey` endpoint mentioned in pfunGA-3Nb-p2#comment-6828.

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/17058498

Some locales (Hebrew, Japanese) have been temporarily machine-translated due to translator availability. All other translations are usually ready within a few days. Untranslated and machine-translated strings will be sent for translation next Monday and are expected to be completed by the following Friday.

Thank you @yashwin for including a screenshot in the description! This is really helpful for our translators.

**Review by andrii-lysenko — APPROVED** [review]
Works great and changes look good to me!

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/17058498).

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/17058498).

**Pull request merged**
