### PR TITLE
Reader: Fixes post excerpt link going under the help icon

### PR DESCRIPTION
**Pull request by Kuzmanov**
Adds more padding from the right side so the text will not go underneath the help icon.

Issues #950 #709

### CODE REVIEW

**Comment by blowery** [comment]
Thanks for the PR @Kuzmanov! Would you mind rebasing this down to just the patch from 6981124? We like to keep pulls as focused as possible.

**Comment by blowery** [comment]
Did the rebase myself (pulled this PR, then `git fetch && git rebase -i origin/master` and squashed everything down to one commit. Moved to #1154

**Comment by Kuzmanov** [comment]
Thanks @blowery. I tried, but obviously I was doing something wrong. Gotta learn more about using git through the command line :)

**Comment by blowery** [comment]
Yeah, squashing is a weird one. http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html is a pretty good intro.

**Pull request closed without merging**
