### PR TITLE
My home upsell: Add dismiss button

### LINKED ISSUE #73956: My home upsell: add a way to dismiss it
Add an "X" to the My Home upsell so that users can dismiss it.

Acceptance criteria:
- [ ] There's an X dismiss button in the upper right. It dismisses the upsell for the same amount of time as the X on the post editor upsell.

### PR DESCRIPTION
**Pull request by lupus2k**
Fixes https://github.com/Automattic/wp-calypso/issues/73956

## Proposed Changes

Add an `X` to dismiss the My Home Upsell, and it should act like the post editor upsell (each site is independent & the same amount of time).
Also, it tracks the dismiss click with `calypso_my_home_domain_upsell_dismiss_click`

image

## Testing Instructions

- Use a site that shows the My Home Upsell (no custom domain, free or yearly plan for now).
- Go to `/home`
- The domain upsell should show an `X` on the top right corner
- Clicking should track `calypso_my_home_domain_upsell_dismiss_click` & dismiss the upsell.

To re-show the banner, you should post this (with your site id), to `https://public-api.wordpress.com/rest/v1.1/me/preferences?http_envelope=1`
```
{
    "calypso_preferences": {
        "calypso_my_home_domain_upsell_dismiss-YOURSITEID": false,
    }
}
```

## Pre-merge Checklist
- [x] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [x] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [x] Have you checked for TypeScript, React or other console errors?
- [ ] ~~Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)~~
- [ ] ~~Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?~~
- [ ] ~~For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?~~

### CODE REVIEW

**Review by paulopmt1 — APPROVED** [review]
Nice work! Each site has its own control, and it's firing events when clicked. It's working as expected @lupus2k!

**Review by allilevine — COMMENTED** [review]
@lupus2k I'm seeing the upsell for a second on a site that isn't eligible for it (already has a domain). Then it disappears. Can you replicate that?

Maybe we need to default to not showing the upsell, or change the order we're checking for preference and eligibility in?

**Comment by lupus2k** [comment]
> Maybe we need to default to not showing the upsell, or change the order we're checking for preference and eligibility in?

I think the problem is when the preference didn't exist yet. I'll take a look

**Comment by allilevine** [comment]
> > Maybe we need to default to not showing the upsell, or change the order we're checking for preference and eligibility in?
> 
> I think the problem is when the preference didn't exist yet. I'll take a look

It's now fixed, thanks! 🙌

**Pull request merged**
