### PR TITLE
Security: Verify phone number given when selecting 2FA by app.

### LINKED ISSUE #31: Me/Security: Current 2FA flow lets users to file unverified phone number
To reproduce
- Click two step `Get started`
- Enter a valid phone number that you don’t have access to
- Click `Verify via App`

This flow will let users to have unverified phone number in file. We should either
- Verfiy phone number before allow to use the app
- Don’t require phone number for users who use the app

### PR DESCRIPTION
**Pull request by kwight**
Even when selecting to use an app for 2FA, we require a user to give us a backup phone number. Currently, this number is simply saved straight into the user attributes, with no verification. This PR ensures that if the given number is unverified, the user has to go through the verification process, just like adding a number under Account Recovery.

Fixes #31 .

### CODE REVIEW

**Comment by kwight** [comment]
It looks like this will need some work in `Security2faEnable`. We'll want to insert a step equivalent to the SMS verification, but for the backup number verification before moving on to the QR code verification. The SMS verification content will need to be different, depending on whether we're in the SMS verification process, or verifying the backup number in the Verify via App process, but I think everything else can be used mostly as-is.

screen shot 2018-03-27 at 2 42 02 pm

I can factor out the buttons into their own component, which will make handling them a little easier.

**Comment by kwight** [comment]
New flows proposed: https://github.com/Automattic/wp-calypso/issues/31#issuecomment-380266069

**Comment by gwwar** [comment]
How's this going @kwight are you blocked by design atm?

**Comment by gwwar** [comment]
>  if nothing comes back in the next day or so, I'll just move forward with it;

Yeah, this one would be good to get out. I can see if code is ready in the meantime. Is this ready for a look?

**Comment by kwight** [comment]
@gwwar I'll get this first button part done and ping for review 👍

**Comment by gwwar** [comment]
Looks like we forgot about this one @kwight, shall we hand this off to someone else?

**Comment by kwight** [comment]
No, it's not forgotten; I look wistfully at it every few days while moving on to higher-priority things 🙃 

I'm still hoping to get back to it over the next two weeks; if not, I'll toss it back.

**Comment by gwwar** [comment]
Since Kirk will be away for a while, anyone who's interested in taking #31 on may take over the PR.

**Comment by alisterscott** [comment]
@gwwar is it worth keeping this PR open?

**Comment by gwwar** [comment]
Let's close this for now

**Pull request closed without merging**
