### PR TITLE
Framework: Base Docker image on node base image

### PR DESCRIPTION
**Pull request by ockham**
Based on @dmsnell's #8603.

Related: pMz3w-7rt-p2

To test: Follow FG instructions to build and run a local Docker image of Calypso.

### CODE REVIEW

**Comment by dmsnell** [comment]
This is looking good to me but I'm not sure how exactly to test it out for production…

**Comment by ockham** [comment]
> What would be the impact here?
> - significantly smaller images?
> - fast img build times?

Yeah, one less build step, so that should speed up build times. Seemed kind of backwards to build our own `node` image if we can just fetch one from the Docker Hub.

**Comment by samouri** [comment]
> This is looking good to me but I'm not sure how exactly to test it out for production…

deploy it? if it works in staging it should work in production.

**Comment by samouri** [comment]
Measurements
------

| type | before | after |
|-----|-------|------|
| size | 1.47 GB | 991MB |
|build time|4:53.67|2:08.70|
 
Thats a savings of a whopping 479MB and 2 minutes.
Lets ship this yesterday.

**Comment by dmsnell** [comment]
> Lets ship this yesterday.

please note that we _did_ ship it yesterday and it broke in the deploy for an unknown reason :wink:

**Comment by ockham** [comment]
Since the base image already includes `node` and `npm`, maybe we can drop the `git` installation step, too.

**Comment by ockham** [comment]
This works, if I use the regular `node` image instead of `node:slim`.

What's interesting: It seems like previously, the image for the `apt-get install` would be rebuilt every time anyway (probably because of some internal timestamp Debian creates when running `apt-get`?) _even if Calypso code was untouched_.

Dropping the `apt-get` stuff allows for the image to be cached at a later stage, yielding an even faster build.

**Comment by ockham** [comment]
> What's interesting: It seems like previously, the image for the `apt-get install` would be rebuilt every time anyway (probably because of some internal timestamp Debian creates when running `apt-get`?) _even if Calypso code was untouched_.

I might've been wrong about this -- looks like my Docker cache just wasn't primed.

**Comment by ockham** [comment]
(Merged as per conclusion of pMz3w-7rt-p2.)

**Pull request merged**
