### PR TITLE
Fix stylelint and prettier CSS autoformatting

### PR DESCRIPTION
**Pull request by alisterscott**
Created these changes running:

1. `./node_modules/.bin/prettier --write "**/*.scss"`
2. `./node_modules/.bin/stylelint "**/*.scss" --fix`

This reduces down the list of remaining stylelint errors which I'll manually correct

This will allow us to automatically run stylelint in CircleCI builds in the future

**Testing Instructions**

Make sure everything looks okay 🤔

### CODE REVIEW

**Comment by jsnajdr** [comment]
Did the `stylelint --fix` run actually fix anything? Ideally it shouldn't, because everything was formatted correctly by Prettier.

**Comment by alisterscott** [comment]
@jsnajdr Prettier broke one of the scss files like so:

screen shot 2018-08-01 at 7 24 44 pm

**Comment by alisterscott** [comment]
> Did the stylelint --fix run actually fix anything? Ideally it shouldn't, because everything was formatted correctly by Prettier.

Yes, 222 changes after Prettier was already run were done by Stylelint

I broke this commits up on a separate branch if you'd like to see. 

Most of them are scss specific things like removing px from 0px, and making sure pseudo selectors aways use :: 

I'm not sure prettier handles all of these scss specific things?

**Comment by alisterscott** [comment]
@jsnajdr these are the stylelint fixes _after_ prettier has been run:

https://github.com/Automattic/wp-calypso/commit/e75d2c3e53289b06b25673ebc2a8ee8fa2e45a89

**Pull request closed without merging**
