### PR TITLE
Dependencies: Bump wpcom.js and slightly improve webpack config

### PR DESCRIPTION
**Pull request by samouri**
Master PR with more background: https://github.com/Automattic/wp-calypso/pull/22630

Sister pull request to the `wpcom.js` upgrade: https://github.com/Automattic/wpcom.js/pull/217.
Once the wpcom.js change lands, we can take away the "beta" from `wpcom.js` and merge this PR after testing.

**testing instructions**
try to add media to your media library from within calypso.

### CODE REVIEW

**Comment by samouri** [comment]
Weird that calypso.live cannot find this branch. I'll open up an issue in dserve

**Comment by blowery** [comment]
Tested out fine for me

**Comment by nylen** [comment]
Strangely, I am not able to upload media files from a local dev environment.  Network tools shows that the AJAX request to `/media/new` is `canceled` as soon as it occurs.

This is an issue in `master` as well as on this branch, though, and I can see that the `wpcom.js` code is appearing as expected in this PR:

2018-02-28t23 30 59-0600

So I agree this is good to ship.

**Comment by samouri** [comment]
> Strangely, I am not able to upload media files from a local dev environment. Network tools shows that the AJAX request to /media/new is canceled as soon as it occurs.

very strange since I've been able to without a problem. I wonder if you have any special proxy/sandboxing setup locally

**Pull request merged**
