### PR TITLE
Untangling: introduce /sites/overview/:site route

### PR DESCRIPTION
**Pull request by fushar**
Related to:

- https://github.com/Automattic/dotcom-forge/issues/9152

## Proposed Changes

This PR adds a `/sites/overview/:site` route, which is the old `/overview/:site` route. This is so that all routes under sites dashboard have a `/sites/*` prefix consistently.

## Why are these changes being made?

pbxlJb-6ye-p2

## Testing Instructions

1. Go to /sites
2. Click any site
3. Verify it opens the Overview panel correctly with the new route
4. REGRESSION: Test also with `?flags=-untangling/hosting-menu`; verify it still opens the old `/overview/:site` route.

## Pre-merge Checklist

- [x] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [x] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [x] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [x] Have you checked for TypeScript, React or other console errors?
- [x] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [x] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
    - [ ] For UI changes, have we tested the change in various languages (for example, ES, PT, FR, or DE)? The length of text and words vary significantly between languages. 
- [x] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Comment by taipeicoder** [comment]
I noticed that this link will lead to an empty tab.

Screenshot 2024-11-26 at 9 52 48 AM

**Comment by taipeicoder** [comment]
Both menu items lead to empty tabs.

Screenshot 2024-11-26 at 10 08 25 AM

**Comment by fushar** [comment]
@taipeicoder Those are not related to this PR -- it's already happening on wpcalypso. This is because we haven't done the redirection / fixed the links, which I'm about to do soon 😄

**Comment by taipeicoder** [comment]
Ah ok, I misunderstood the PR 🙂

**Review by taipeicoder — APPROVED** [review]

**Pull request merged**
