### PR TITLE
Components: Add a Highlight Cards component

### PR DESCRIPTION
**Pull request by jsnmoon**
#### Proposed Changes

image

Adds new `<HighlightCards>` and `<HighlightCard>` components for future use on the Stats dashboard.

#### Testing Instructions

* Check out this branch locally.
* Spin up Storybook via `yarn workspace @automattic/components run storybook`.
* Check the Highlight Cards stories. Ensure they behave as expected.

#### Pre-merge Checklist

- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?

Related to #69224

### CODE REVIEW

**Review by grzegorz-cp — APPROVED** [review]
Looks good. 
What do you think about extending `HighlightCards` with a `className` prop and adding it to the parent? It would allow consumers to add a class and make some minor CSS changes.

**Comment by jsnmoon** [comment]
> What do you think about extending `HighlightCards` with a `className` prop and adding it to the parent? It would allow consumers to add a class and make some minor CSS changes.

Addressed in ead8dcd 👍 

Also executed and saved the results of `yarn dedupe` as recommended by the most recent unit test failure log.

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/7605861

Thank you @jsnmoon for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/7605861).

**Pull request merged**
