### PR TITLE
Update Google My Business designs

### PR DESCRIPTION
**Pull request by scruffian**
This pull request updates several things on the Google My Business page.

1. The buttons are now always beneath the text, rather than moving to the right. This keeps the experience consistent between different screen sizes.

2. The font headings and body text are consistent in each section, which reduces visual clutter

3. Declarations which were already inherited have been removed

4. Removes rules which made this page deviate from Calypso patterns (like additional padding)

5. Added a max-width rule on the text for legibility

6. Removes element level selectors in favour of class names as this is what we prefer in Calypso (it generates smaller CSS and reduces inheritance issues)

7. Removes the gap between CTA cards

screen shot 2018-02-28 at 10 56 46

screen shot 2018-02-28 at 11 03 46

#### Testing instructions
  
1. Run `git checkout update/gmb-select` and start your server
2. Open the [`Google My Business` page](http://calypso.localhost:3000/google-my-business)
3. Check that the layout matches the screenshot above
  
#### Reviews
  
- [ ] Code
- [x] Product
   
@cburton4

### CODE REVIEW

**Comment by Tug** [comment]
LGTM 👍

**Comment by cburton4** [comment]
- Let's add more space between the illustration and the headline for the mobile screen
- Make the illustration smaller for the mobile screen, in my designs I was able to get the Online Only option to peek above the bottom of the screen
- Less space between the headline and the body text
2 2x

**Comment by yurynix** [comment]
screen shot 2018-02-28 at 17 15 42

How about that @cburton4 ?

**Comment by mikeshelton1503** [comment]
Changes look good 👍 Let's get this up asap.

@scruffian I noticed (only because I didn't see you latest changes at first and started doing it myself) that to set the max-width: 720px, other areas in Calypso use the `main` tag for the section container ('.select-business-type` in this case) and add a class of `.main` to set the max-width. Probably should use for consistency?

**Comment by scruffian** [comment]
@mikeshelton1503 - I added the main tag, but I don't think we should add the `.main`class to the CSS unless we need it. It's best to keep a local scope where possible.

**Comment by mikeshelton1503** [comment]
@scruffian The '.main' class carries the global max-width setting (although really not the best way/naming for setting a global parameter like that). So if in the future we want to change all sections in Calypso to be 900px, for example, just changing it on `.main` would change it everywhere.

**Comment by scruffian** [comment]
> @scruffian The '.main' class carries the global max-width setting (although really not the best way/naming for setting a global parameter like that). So if in the future we want to change all sections in Calypso to be 900px, for example, just changing it on .main would change it everywhere.

@mikeshelton1503 good point, I removed those rules, thanks.

**Comment by mikeshelton1503** [comment]
Awesome let's get this up today.

**Comment by yurynix** [comment]
Looks good, LGTM 🚢

**Pull request merged**
