### PR TITLE
Add follow sources for search results and recommendations

### PR DESCRIPTION
**Pull request by bluefuton**
Add a followSource to the follow button for search results and recs in Following Manage (URL input already has one).

Part of https://github.com/Automattic/wp-calypso/issues/13830.

### To test

Follow a site in http://calypso.localhost:3000/following/manage with analytics logging in your console. Make sure the follow button events have the correct follow source included.

screen shot 2017-05-22 at 12 10 57

### CODE REVIEW

**Comment by gibrown** [comment]
Does this also make sure that we bump the "reader_follows" stat? Would be good to keep bumping those stats for comparison purposes.

**Comment by bluefuton** [comment]
> Does this also make sure that we bump the "reader_follows" stat?

Yep! It's bumped in the follow button itself. It's part of `recordFollowTracks`, called here:

https://github.com/Automattic/wp-calypso/blob/master/client/reader/follow-button/redux.jsx#L21

**Comment by blowery** [comment]
👀

**Comment by blowery** [comment]
Added a follow source for mc in https://github.com/Automattic/wp-calypso/pull/14315/commits/7b9ce5d262c78fbb869fa365a06a521287140656

LGTM

**Pull request merged**
