### PR TITLE
Reader: Increase gray text contrast

### PR DESCRIPTION
**Pull request by drw158**
This updates a few blocks to use the $gray-text-min variable for text, which is the mimmim contrast needed to pass WCAG 2.0 AA tests on a white background.

I went through all [blocks](https://wpcalypso.wordpress.com/devdocs/blocks) that are related to the Reader, and update all gray text that did not pass AA.

To test:

- go to Reader
- make sure all text looks consistent
- try hover states

cc @fraying 

Before:
screen shot 2017-02-14 at 12 01 37 pm
screen shot 2017-02-14 at 12 01 18 pm

After:

https://github.com/Automattic/wp-calypso/pull/11387#issuecomment-280079328

### CODE REVIEW

**Comment by fraying** [comment]
If the action link text color is going to change, the icons beside them should change to match. We may also want to darken the hover state as well, so it doesn't have less contrast on hover.

**Comment by drw158** [comment]
@fraying updated screenshots

- Updated text color of action links to $gray (affects the reader stream as well as full post)
- Updated hover color of action links to $blue-medium

Personally I like icons to be a shade lighter than the text, otherwise the icons look too dark.

screen shot 2017-02-14 at 3 13 14 pm

**Comment by fraying** [comment]
I'm okay with these changes. What's the purpose of having the icons slightly lighter? If it's just personal preference, I'd suggest keeping them the same. Having the colors match exactly helps people see that they're connected without thinking. One less variation = one less thing to notice.

If we're gonna launch this, we should make sure the rest of the links match. I think the links in the stream in the card headers (date, tag) are currently darker than the action links ($grey).

**Comment by drw158** [comment]
The purpose is to normalize the balance between the text and the icon so that the icon is not weighted more so than the text (happens easily with solid icons like Gridicons).

Here are the action links with the text + icon using the same color:

screen shot 2017-02-14 at 4 58 25 pm

Before:

screen shot 2017-02-14 at 3 13 14 pm

Yep, the meta info is using $gray-text-min. This info is separate from the actions, so I did not lighten them to $gray.

Current screenshot of the post stream in this PR:

screen shot 2017-02-14 at 5 01 24 pm

**Comment by fraying** [comment]
My two cents: Icons should be the same color as the text. I get the idea behind lightening them, but I think it makes them more visually complicated than they need to be, especially given the thinness of the like and share icons.

Meta info links should be the same color as the action links. Because they're so close now, it doesn't make sense to have them almost-but-not-exactly the same.

**Comment by drw158** [comment]
Ok, here is a screenshot after all of the changes. I believe all the text that was previously $gray-text-min is now $gray. Icons are the same color as the text. Hover state on actions are now $blue-medium.

screen shot 2017-02-15 at 11 28 18 am
screen shot 2017-02-15 at 11 28 03 am

**Comment by fraying** [comment]
👍 Looks good to me! Thanks for being on top of this.

**Comment by Copons** [comment]
👍

**Pull request merged**
