### PR TITLE
 Reader: add OPML Export button for following feed

### PR DESCRIPTION
**Pull request by TooTallNate**
This is my initial take at #943.

First time with Calypso, React, webpack etc. Bound to be something not right :dancers: 

screen shot 2016-03-08 at 7 11 36 pm

[Video](https://cloudup.com/iJgIKTS5w6m)

### CODE REVIEW

**Comment by TooTallNate** [comment]
Note: placement of this button was basically an educated guess. If @jancavan or anyone else has a better suggestion for placement / copy, please let me know.

**Comment by jancavan** [comment]
Thanks @TooTallNate still working on mocks for this one.

**Comment by jancavan** [comment]
@TooTallNate I've posted mockups for this, but that requires redoing a lot of the UI which we can tackle in future iterations. In the meantime, here are some suggestions which still uses existing Calypso components:

1. We move the site count, date/name sorter, and search to their own section header. This is where we also add the import/export buttons. The site search will be its own search component where you don't have to click a button to get it to show up:
import-export001

2. When you click on the search following icon (second lens icon that's blue), it'll display the search component where you can search sites you're already following. This is an already existing component as well:
import-export002

This is less confusing than what we currently have.

**Comment by TooTallNate** [comment]
Superseded by #4015.

**Pull request closed without merging**
