### PR TITLE
Plan: Add description to SFTP feature and not show empty tooltip

### LINKED ISSUE #70078: Plans: Missing tooltip description for developer tools
#### Steps to reproduce

1. Starting at URL: https://wordpress.com/plans
2. Click on the "SFTP, SSH, WP-CLI, and Database access" info tooltip

#### What I expected

The description text to show. We can coordinate the copy with @that-mike-bal and/or our PAs.

#### What happened instead

An empty tooltip box appears.

#### Browser / OS version

All.

#### Screenshot / Video

Screenshot 2022-11-16 at 5 55 10 PM

### PR DESCRIPTION
**Pull request by vykes-mac**
#### Proposed Changes

* Add description for SFTP feature.
* Do not show popover icon if feature description is unavailable.

#### Testing Instructions

* Go to` /plans/siteSlug` .
* Find feature `SFTP, SSH, WP-CLI, and Database access`.
* Click popover icon to see description,.

* Remove description from `client/lib/plans/features-list.js`.
* Verify popover icon is not shown for that feature.

**Before**
Screenshot 2022-11-16 at 5 55 10 PM

**After**
image

#### Pre-merge Checklist

- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

Related to https://github.com/Automattic/wp-calypso/issues/70078

### CODE REVIEW

**Review by sejas — APPROVED** [review]
Tested it and it's working good.

I've also tested in different languages and the tooltip is hidden if the translation doesn't exist in this row 👌 .

Screenshot 2022-11-17 at 14 34 36

**Review by niranjan-uma-shankar — APPROVED** [review]
Looks good!

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/7633843

Thank you @vykes-mac for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/7633843).

**Pull request merged**
