### PR TITLE
DO NOT MERGE: Update font sizes to CSS vars

### PR DESCRIPTION
**Pull request by sixhours**
#### Changes proposed in this Pull Request

* Use CSS vars for font sizes and replace existing hard-coded font sizes with variables.
* We may want to use mixins to set line heights and variables rather than setting these independently. I need to investigate more.

#### Testing instructions

* Switch to this PR
* Navigate around WP.com and look for visual bugs. Nothing should have changed from master, this is a straightforward find and replace.

### CODE REVIEW

**Comment by simison** [comment]
Why CSS vars instead of sass vars? :-)

**Comment by sixhours** [comment]
> Why CSS vars instead of sass vars? :-)

My thought was to follow a similar setup/pattern to colors, which use CSS vars. But ultimately I think we'd want to use Sass mixins to create pre-formatted text (maybe these use the same CSS vars) combining font size, weight, and line heights.

What are your thoughts?

**Comment by sixhours** [comment]
(Need to scrap this PR, too many conflicts; the original branch was old. Easier to just start a new branch from an updated master.)

**Comment by sixhours** [comment]
Moving in a different direction here: #42629

**Pull request closed without merging**
