### PR TITLE
Third-Party Themes: Add the product query to theme showcase

### LINKED ISSUE #69470: Task: Update kebab menu on theme showcase for third party themes
### Details

We need to update the menu items in the kebab menu to ensure that we communicate the correct purchase path to users. We may want to use "Subscribe" instead of "Purchase", as the actions are distinct for first-party and third-party themes.

Note that this is blocked by #69420.

CleanShot 2022-10-24 at 11 30 26

### Checklist

- [x] If a user already has a business plan, offer them a "Subscribe" option, which will add the premium theme subscription to their cart
   * We will need a way to pick the appropriate term for the subscription (i.e. monthly or annually)
- [x] If a user doesn't have a business plan, the menu item should be "Upgrade and subscribe", or possibly "Upgrade and purchase"
   * As above, we should consider how we can pick an appropriate subscription term

### Related

#69420

### PR DESCRIPTION
**Pull request by valterlorran**
#### Proposed Changes

* Add the product query to the theme showcase so we can have the products available. This will allow us to find the product slug we should use to add the marketplace theme to the cart.
https://github.com/Automattic/wp-calypso/blob/56293b8c9f15ff2e887e18a40ca19b94bcf04785/client/state/themes/actions/add-external-managed-theme-to-cart.tsx#L74-L85
* The marketplace themes can have different billing cycles. Meaning that some themes can have monthly and yearly billing cycles, but some can have only monthly or yearly. We use the billing slug to find all the products that represent the different billing cycles for the same theme.
* This branch depends on #69616 - merge after the 

#### Testing Instructions

* On a free site, navigate to the theme showcase page.
* Find Makoney and click on the kebab menu. 
* Then you will see the option to "Upgrade to subscribe"; click on it.
* It should take you to checkout with the Business plan and the theme subscription added.
* You can also test this flow on a Business site and expect only to add the theme subscription to the cart.

Closes #69470

### CODE REVIEW

**Comment by sixhours** [comment]
~~I'm able to get the correct behavior with a free site, but on a freshly created Business site, I don't see the option to subscribe or activate at all:~~

NVM, I had an active filter to reassign Tsubaki as a different theme type in my sandbox. 🙃 

Screen Shot 2022-12-06 at 10 40 27 AM

**Comment by blackjackkent** [comment]
Weirdly, for me on an existing business plan, I see an indication that "This WooCommerce is included in your plan" and the option to activate, not purchase. O.o

image

I will try testing with a fresh business site and see what that gives me.

**Comment by blackjackkent** [comment]
Same on a fresh business site - I think this is the expected behavior? (Not sure why @sixhours isn't seeing it though.)

**Comment by mreishus** [comment]
> Weirdly, for me on an existing business plan, I see an indication that "This WooCommerce is included in your plan" and the option to activate, not purchase. O.o
> 

Seeing the same thing, is there an additional testing step that's missing that makes Tsubaki act like a subscribed theme instead of its current behavior in prod? (Maybe something in 0-sandbox?)

**Comment by sixhours** [comment]
> (Maybe something in 0-sandbox?)

LOL exactly something in 0-sandbox:

```
function test_theme_type( $theme ) {
        if ( $theme['id'] === 'tsubaki' ) {
                $theme['theme_type'] = 'managed-external';
        }

        return $theme;
}
add_filter( 'wpcom_theme_api_meta', 'test_theme_type', 1000 );
```

Testing again with that removed.

**Comment by sixhours** [comment]
> Weirdly, for me on an existing business plan, I see an indication that "This WooCommerce is included in your plan" and the option to activate, not purchase. O.o

Ditto (tritto?) Tried with both fresh and existing Business plan sites.

**Comment by valterlorran** [comment]
I moved this PR back to in progress. We need to make changes to show the correct actions on the kebab menu. I think it was shown before because Tsubaki was also a premium theme. Now that we have Makoney to test, some things need to be fixed. @markbiek 

https://github.com/Automattic/wp-calypso/issues/71174
https://github.com/Automattic/wp-calypso/issues/71173

**Comment by valterlorran** [comment]
The changes in this PR were incorporated in https://github.com/Automattic/wp-calypso/pull/71191

**Pull request closed without merging**
