### PR TITLE
Playwright: remove migrated Selenium tests

### PR DESCRIPTION
**Pull request by worldomonation**
#### Changes proposed in this Pull Request

This PR proposes to remove more migrated tests from the Selenium side of things.

#### Testing instructions

- [x] TeamCity tests continue to pass for Playwright.
- [x] TeamCity tests continue to pass for Selenium.

### CODE REVIEW

**Comment by worldomonation** [comment]
@dpasque I know you just merged #54858 - was the spec you wrote a combination of several different specs from the Selenium side?

**Comment by dpasque** [comment]
> @dpasque I know you just merged #54858 - was the spec you wrote a combination of several different specs from the Selenium side?

Yes! Three of them:

- `wp-plan-purchase__comparing-spec.js`
- `wp-plan-purchase__renew-spec.js`
- `wp-plan-purchase__upgrade-spec.js`

**Comment by worldomonation** [comment]
> > @dpasque I know you just merged #54858 - was the spec you wrote a combination of several different specs from the Selenium side?
> 
> Yes! Three of them:
> 
>     * `wp-plan-purchase__comparing-spec.js`
> 
>     * `wp-plan-purchase__renew-spec.js`
> 
>     * `wp-plan-purchase__upgrade-spec.js`

Great, I'll add them to the delete list - let's monitor how the new specs do for several days, then let's move to remove them from Selenium if we're happy with the stability.

**Review by bsessions85 — APPROVED** [review]
🚢

**Pull request merged**
