### PR TITLE
Social: Added new plan constants for the v1 plan

### PR DESCRIPTION
**Pull request by spsiddarthan**
## Proposed Changes

* Added the new social v1 plan constants

## Why are these changes being made?

* To be able to checkout the new plans for social 

## Testing Instructions

* Be able to check out the monthly, yearly, and bi-yearly plans. Go to /checkout/jetpack/jetpack_social_v1_monthly on the local calypso or the live build to checkout the plan on this branch to checkout the yearly plan. Finishing checking out successfully.
* Be able  to switch between the yearly/bi-yearly/monthly variants on the checkout page.
* Ensure Jetpack Cloud pricing loads fine by booting up a live Jetpack Cloud branch. Ensure logged-out view works fine as well.

Screenshot 2024-05-29 at 5 11 36 PM

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Review by manzoorwanijk — COMMENTED** [review]
Should we use a feature flag to show the new plan instead of the old plans?

**Comment by spsiddarthan** [comment]
>Should we use a feature flag to show the new plan instead of the old plans?

The plans are in production already, so only anyone who knows this URL will be able to buy it. We can use feature flags when we rework the pricing modal, perhaps?

Or did you have something else in mind?

**Comment by manzoorwanijk** [comment]
> The plans are in production already, so only anyone who knows this URL will be able to buy it. We can use feature flags when we rework the pricing modal, perhaps?

Yeah, sounds good

> Or did you have something else in mind?

Nope, all good. Thanks

**Review by manzoorwanijk — APPROVED** [review]
Works as expected. I was able to complete the checkout.

**Comment by spsiddarthan** [comment]
Thanks for the quick review. :D

**Pull request merged**
