### PR TITLE
Fix conditions for ecommerce trial plan

### PR DESCRIPTION
**Pull request by heavyweight**
For users on the ecommerce trial plan we were showing theme badges related to the business plan instead of the ecommerce plan.

| Before  | After |
| ------------- | ------------- |
|Screenshot 2024-09-19 at 14 00 53  | Screenshot 2024-09-19 at 14 00 39 |
|  Screenshot 2024-09-17 at 13 37 19 | Screenshot 2024-09-17 at 13 38 18  |
| Screenshot 2024-09-17 at 13 36 59 | Screenshot 2024-09-17 at 13 36 16 |

Related to #
https://github.com/Automattic/wp-calypso/issues/94541

## Proposed Changes

* Add checks in relevant code to show ecommerce or business plan info on the theme badges

## Why are these changes being made?

* Users on the ecommerce trial plan should be lead to update to the full plan instead of the business plan

## Testing Instructions
- Go to [wordpress.com/ecommerce](https://wordpress.com/ecommerce/)
- Press Get Started and proceed all the way through the flow
- Go to wordpress.com/themes/:siteSlug
- Look for themes that require update and hover on "Upgrade and Subscribe". The tooltip should show ecommerce link leading to the checkout page with the ecommerce plan in the cart.
- Search for "Construction Firm" in the theme filter field.
- Check the "Upgrade" badge on community themes. The tooltip should show ecommerce link leading to the checkout page with the ecommerce plan in the cart.

**Testing Theme Details**
- Visit: /theme/kubrick-2024/:siteSlug
- The primary button should say: "Upgrade to activate"
- When clicking it you should land to checkout with the ecommerce plan in the cart
- For a site that is not on the ecommerce trial the checkout item should be the business plan

- Finally test for regressions.

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Review by candy02058912 — COMMENTED** [review]
I feel the copy here is a bit misleading since, for Community and Partner themes, it is for Business and Commerce plans as stated in our [support docs](https://wordpress.com/support/themes/#browse-the-available-themes).

> Partner: [Partner themes](https://wordpress.com/support/themes/partner-themes/) are available to sites on our [Business and Commerce plans](https://wordpress.com/plans/). These themes are created by third-party theme developers specifically for WordPress.com and require an annual or monthly subscription.

> Community: Community themes are available on sites in our [Business and Commerce plans](https://wordpress.com/plans/). These themes are created by third-party theme developers unaffiliated with WordPress.com. Popular themes such as [Astra](https://wordpress.com/theme/astra/), [OceanWP](https://wordpress.com/theme/oceanwp/), and many more can be found here to install on your WordPress.com website.

So the user can get the theme with a Business plan and isn't required to have to go all the way up to a Commerce plan as said by the updated copy in this PR:

```
This community theme can only be installed if you have the Commerce plan or higher on your site.
```
Which isn't 100% true.

Maybe we can adjust the copy to what @dsas mentioned in the issue. Perhaps the copy should be more geared towards "Upgrade to activate" for Commerce Trial plans.

For a site that's on `PLAN_ECOMMERCE_TRIAL_MONTHLY`, perhaps something like this:
```
This community theme can be installed after you purchase the <Link>%(planName)s plan</Link>.
```

**Comment by dsas** [comment]
I'm unsure on what the best way of communicating which plan to upgrade to is. Telling people they need the Business plan or higher is technically correct but I don't know what the user-facing impact is of having a site move from the ecommerce trial plan to the business plan. Might be worth talking to a designer who worked on the ecommerce trial plan?

While it's worth thinking about the wording of that notice, #94541 wasn't really supposed to be about that. It was about a bigger problem - the CTA on the theme detail page is wrong.

Screenshot 2024-09-19 at 00 09 52

**Comment by heavyweight** [comment]
> I'm unsure on what the best way of communicating which plan to upgrade to is. Telling people they need the Business plan or higher is technically correct but I don't know what the user-facing impact is of having a site move from the ecommerce trial plan to the business plan. Might be worth talking to a designer who worked on the ecommerce trial plan?
> 
> While it's worth thinking about the wording of that notice, #94541 wasn't really supposed to be about that. It was about a bigger problem - the CTA on the theme detail page is wrong.
> 
> Screenshot 2024-09-19 at 00 09 52

Updated the PR and testing steps to fix this as well.
I'm thinking we should merge this without worrying about the copy since it doesn't require us to wait for translations and fixes the issue. We could follow up with design and open another issue for the copy. WDYT @candy02058912  @dsas

**Review by candy02058912 — APPROVED** [review]
Tested with a Commerce Trial site

### Partner
image

### Community
image

### Upgrade to activate

upgrade

**Comment by candy02058912** [comment]
> I'm thinking we should merge this without worrying about the copy since it doesn't require us to wait for translations and fixes the issue.

Yes, I agree with this.

Created a follow-up issue: https://github.com/Automattic/wp-calypso/issues/94748

**Pull request merged**
