### PR TITLE
Add `packages/wpcom-proxy-request`.

### PR DESCRIPTION
**Pull request by sgomes**
This PR deals with importing the source code (and history) only, while keeping it inactive. Subsequent PRs will build on top of this to modernise the code and integrate it with `calypso-build`.

Marking the package as private to avoid publishing for now.

Note: the intention is to merge this PR as a merge commit, following what was done with `wpcom`. This accurately reflects the fact that we are merging the histories of two projects.

#### Changes proposed in this Pull Request

* Import source code for `wpcom-proxy-request`.
* Mark package as private.

#### Testing instructions

None of this code is active, so it should be sufficient to test that the build does not break.

### CODE REVIEW

**Comment by sgomes** [comment]
Any chance of a quick review for this one? All it does is import the source and history for `wpcom-proxy-request` into the monorepo, and it would unlock further work in making builds smaller.

**Comment by sgomes** [comment]
Friendly ping. All this PR does is import the existing source and history for `wpcom-proxy-request` to unlock future work. The code will stay inert until it's activated in a later PR.

**Review by tyxla — APPROVED** [review]
LGTM 👍 Excited to see what's coming for this one.

**Comment by sgomes** [comment]
Thank you so much for the review, @tyxla! 🙏

**Comment by sgomes** [comment]
Merged with a merge commit, to preserve the history of the imported repository.

**Pull request merged**
