### PR TITLE
Editing Toolkit: Fix phpunit tests

### PR DESCRIPTION
**Pull request by sirreal**
#### Changes proposed in this Pull Request

*

#### Testing instructions

*

Fixes #

### CODE REVIEW

**Comment by noahtallen** [comment]
I'm not sure why this test is breaking -- this is one of the default config settings: https://github.com/WordPress/gutenberg/blob/3d5c413c541f16ff6a6a3cd6678ad140f7fdca5a/packages/env/lib/config/config.js#L82

**Comment by sirreal** [comment]
Over in #47498 this error is reported:

```
Error: The required WP_TESTS_EMAIL constant is not defined. Check out `wp-tests-config-sample.php` for an example.
```

https://github.com/Automattic/wp-calypso/pull/47498/checks?check_run_id=1450609800

**Comment by sirreal** [comment]
I can't reproduce the failures locally 🤷

**Comment by noahtallen** [comment]
wft

I'll try to toubleshoot as well. I have one hunch about wp-phpunit (the composer dep pulling in the wordpress tests lib), but if it's working locally...

**Comment by noahtallen** [comment]
So the tests lib is reporting a problem in this file: https://github.com/wp-phpunit/wp-phpunit/blob/master/includes/bootstrap.php on line 100. Firstly, line 100 does not reference that constant. Secondly, the file hasn't been updated since August, so it's unlikely to have changed in composer. Thirdly, early in the file, it checks that the required constants are defined. So it should be throwing an error there if the constants are not set.

So, I think it's possible that the dependency is out of date, or something else is off with composer. I took a shot at this here: #47772

If that's the case, this reminds me of a wp-env issue I've been meaning to fix: https://github.com/WordPress/gutenberg/issues/23171

**Comment by noahtallen** [comment]
Closing in favor of #47979

**Pull request closed without merging**
