### PR TITLE
Add site profiler site metrics API hook

### PR DESCRIPTION
**Pull request by agrullon95**
Related to https://github.com/Automattic/wp-calypso/issues/88971

## Proposed Changes

* Add site profiler metrics API hook to be used in the Migration upgrade plan step.

## Testing Instructions

* Checkout branch or use live link to verify Calypso isn't broken
* You can also optionally checkout the branch and test out the hook in a random component.

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Comment by escapemanuele** [comment]
Thanks for working on this @agrullon95!
I looked at the repository, maybe it is a good idea to put all the hooks regarding `site-profiler` in [this](https://github.com/Automattic/wp-calypso/tree/trunk/client/data/site-profiler) folder? Wdyt?

**Review by epeicher — COMMENTED** [review]
Hi @agrullon95, you can benefit from an almost identical hook in this file https://github.com/Automattic/wp-calypso/blob/trunk/client/data/site-profiler/use-url-basic-metrics-query.ts. All the other hooks to query data are located in that folder so I agree with @escapemanuele that it looks a proper location for the site-profiler API hooks

**Comment by escapemanuele** [comment]
Oh well, @epeicher, it looks like we were late for a day!
@agrullon95  let's use the existing hook and proceed with the dynamic stats!

**Comment by agrullon95** [comment]
@epeicher - Thanks for the update.
I'm closing this PR since the hook already exists in the codebase.

**Pull request closed without merging**
