### PR TITLE
Help: Show Happychat button for all paid plan users in Help contact form

### PR DESCRIPTION
**Pull request by oskosk**
Adds a check for paid plans when checking elegibility for Happychat support in Contact form. 

The Happychat button will be shown only for sites with Paid Plans.

Note: _Even when this PR makes the Happychat button be shown for all paid plans, .org plans chats are still being routed to .com queues. 

#### Testing instructions

1. Start by logging into the staging HUD (this will make you an available operator).
1. Get to the help section in the live branch.
1. Click the "Contact us" button (this will lead you to the contact form.
1. Select a Jetpack site with a free plan (you should see the "Email us" form.
1. Select a Jetpack site with a paid plan (You should see the Happychat form)
1. Select a .com site on a free plan (you should see the Email us form).
1. Select a .com site with a paid plan (You should see the Happychat form)

**The problem right now is that even when you select a Jetpack site, you're still routed to the .com queue for chat support**

### CODE REVIEW

**Comment by oskosk** [comment]
Pinging @unDemian for thoughts on the routing. 

This PR works as expected for me only if I set my self available for the WP.com queue in the HUD. Otherwise, the Happychat is not shown in the contact form.

**Comment by unDemian** [comment]
I pushed some updates to update the routing. 

@oskosk can you please take a look at the code.
@dllh after you land the diff I think we are in a good shape.

I tested all scenarios I could imagine, I can provide test accounts to cover all these scenarios
**The scenarios assume that there are Happychat operators available for WP.COM/JPOP groups, having no operators should just show email form in all scenarios**
- [ ] Select `All sites` in the picker -> Contact form should use primary site
- [ ] AT sites should be routed to WP.com operators and act like WP.com sites even though they are jetpack
- [ ] Refresh the contact page -> Form and chat availability should behave as expected
- [ ] WP.com free with a paid jetpack site, selecting the jetpack site show Happychat (route to JPOP)
- [ ] WP.com free with a free jetpack, should show Forum no matter what site is selected
- [ ] WP.com paid, selecting a site that has a paid plan should show Happychat 
- [ ] WP.com paid, selecting a site that has no plan should show Email
- [ ] WP.com paid with a paid jetpack site, selecting the jetpack site show Happychat (route to JPOP)
- [ ] WP.com paid with a free jetpack site, selecting the jetpack site show Email
- [ ] Logout and clearing app storage -> `/help/contact` should work as expected after login
- [ ] WP.com paid account with only 1 site should show Happychat but the site selector should not be displayed.

**Comment by dllh** [comment]
I've tested:

* unpaid (got forums/Directly)
* wp.com business plan (got WP.com -- confirmed that toggling availability of my operator toggled in calypso too)
* jpop business plan (got JPOP -- also played with toggling availability)

So far so good.

**Comment by oskosk** [comment]
LGTM!

**Pull request merged**
