### PR TITLE
DevEx: use yarn instead of npm for installing dependencies

### LINKED ISSUE #23348: Framework: Avoid churn in npm-shrinkwrap.json
Our `npm-shrinkwrap.json` which lists the exact versions of all of our dependencies has gotten a bit crazy.  Here is a history of commits that changed this file with the number of lines added/removed in each commit:

```
$ git log --oneline npm-shrinkwrap.json | cut -d' ' -f1 | while read i; do git show --text "$i" npm-shrinkwrap.json | grep -Po '^[+-]' | sort | uniq -c | tr -d '\n'; echo -n '    '; git log --oneline "$i" -n 1 | cat; done | pbcopy
    808 -     17 +    de96853 Bump to Gridicons 3.0.1 (#23306)
      3 -    794 +    4901875 package.json: Bump `notifications-panel` to v2.1.8 (#23278)
      9 -      9 +    52b3577 Revert "Update to gridicons 3 (#23171)" (#23304)
    801 -     22 +    113841d Update to gridicons 3 (#23171)
    167 -    377 +    0a930af Framework: Use qs module instead of querystring (#23265)
     25 -     24 +    0fceb6d package.json: Bump `notifications-panel` to v2.1.6. (#23182)
     76 -     90 +    a5ea162 PR Tweak: Less hacky approach with an extended DelayRender component
    249 -    255 +    28febda Upgrade moment library to 2.21.0 (#23023)
      8 -    176 +    a560773 Webpack: strictly verify imports and disable nodejs polyfilling (#22630)
    123 -   1274 +    6eb73cd Dependencies: Bump wpcom.js and slightly improve webpack config (#22854)
     95 -     84 +    366ad7b Framework: Update Gridicons to v.2.1.3 (#22732)
    202 -     22 +    de953d7 Framework: eliminate pug (#22348)
    100 -    894 +    eb1ed86 Remove dependency on the 'numeral' NPM package
   1094 -    309 +    74ed256 Fix the "analyze-bundles" and "build-client" commands in Windows
... and many many more
```

You can see that there is a lot of churn in this file recently.  Some of it is related to intentional dependency changes, but there are also these changes of about 800 lines that flip back and forth fairly consistently.

On my computer, depending on how I update the lock file in `master`, I can get one of several different results:

```
    738 -    118 +    093f7c7 Update shrinkwrap again (with --no-optional flag)
    114 -    734 +    24b4a25 Update shrinkwrap using `npm run update-deps`
     10 -     10 +    e23c7cf Update shrinkwrap using `npm run update-deps` (3rd time's the charm!)
```

This file changes dramatically depending on who updates it, apparently depending on the OS and configuration they are using to develop Calypso.  For example: the optional dependency `fsevents` is only installed on OS X, so my computer doesn't install it.  Some history on this issue:  https://github.com/Automattic/wp-calypso/pull/12370#issuecomment-298791026, https://github.com/Automattic/wp-calypso/pull/18767#issuecomment-336281221

But ideally, we just want a package lock file that **ensures reliable builds** in Docker and on the Calypso servers, so it shouldn't change across different kinds of machines or configurations.  We also shouldn't be committing a lot of these spurious diffs to git.

I'm not sure the best way to fix or improve this, but seeing big `npm-shrinkwrap.json` diffs in PRs makes me a bit nervous.

### PR DESCRIPTION
**Pull request by samouri**
# Use Yarn

We've [considered](https://github.com/Automattic/wp-calypso/pull/8660) switching to yarn in the past, but held off due to major improvements coming to npm.  npm 5 is here, and was undoubtably much better than npm 3 and 4.  So the question has become: is `npm5` better than yarn.

Here are the features `yarn` supports that make it a no-brainer for me:

- `yarn` can work offline with the command `yarn install --offline`. this is huge
- We never need to manually update our shrinkwrap. As of now, updating the shrinkwrap requires deleting and reinstalling `node_modules` which is slow and forces us to halt working while it runs. `yarn` handles its lockfile automatically
- `yarn install` runs faster than `npm install` for the most common cases
- yarn will recognize if nothing in `package.json` has changed, and can early-return out of the install.

**performance comparison of yarn install vs. npm install**

|                             | yarn | npm  |
| --------------------------- | ---- | ---- |
| no cache, no node_modules   | 114s | 65s  |
| yes cache, no node_modules  | 25s  | 31s  |
| yes cache, yes node_modules | 1s   | 23s  |
| update lockfile             | n/a  | 60s  |

**To test**
```
# install yarn
npm install -g yarn

# start calypso. npm start still technically works
yarn start
```

Note: fixes https://github.com/Automattic/wp-calypso/issues/23348

### CODE REVIEW

**Comment by gwwar** [comment]
As a general note yarn does not recommend installing from `npm`.

> Note: Installation of Yarn via npm is generally not recommended. When installing Yarn with Node-based package managers, the package is not signed, and the only integrity check performed is a basic SHA1 hash, which is a security risk when installing system-wide apps. For these reasons, it is highly recommended that you install Yarn through the installation method best suited to your operating system.

https://yarnpkg.com/lang/en/docs/install/

Likely for OSX
```
brew install yarn --without-node
```
Or for anyone with apt-get:
```
curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
sudo apt-get update && sudo apt-get install --no-install-recommends yarn
```

**Comment by gwwar** [comment]
Did we also end up testing against `npm ci`? That's likely to be available to Node LTS soon.

**Comment by samouri** [comment]
> Did we also end up testing against npm ci ? That's likely to be available to Node LTS soon.

I personally couldn't get the new version of `npm` to work locally. It kept [failing to npm install](https://github.com/npm/npm/issues/19989#issuecomment-374005342)

**Comment by samouri** [comment]
To do: 
- [ ] yarn engine to make it so that everyone is on the same version of yarn
- [ ] restrict it so that `npm install` fails with an error to use yarn

**Comment by sirreal** [comment]
Let's tie in this relevant discussion: https://github.com/Automattic/jetpack/pull/8718 (thanks @simison)

**Comment by simison** [comment]
### Offline support
Both yarn and npm5 have offline support.

`npm i --offline` (without `./node_modules`) fails on Calypso due [using direct git-dependencies](https://github.com/Automattic/wp-calypso/blob/0cb3ce4d41d3c0a71501bf8ebdec864c36800e6c/package.json#L118) instead of using a registry. Works great if you already have `./node_modules` though.

### Lockfile
Since Calypso is using npm shrinkwrap (updated manually), comparisons would be fairer if we'd assume a move to npm lockfile (updated automatically). More about these two: https://docs.npmjs.com/files/package-locks

This is a nice read about differences between `yarn.lock` and npm `package-lock.json`: https://yarnpkg.com/blog/2017/05/31/determinism/

In short:

- devex is the same: both get updated when adding/removing/updating modules

- yarn lockfile is more compact, less likely causing merge conflicts. It relies on lockfile+package.json

    → I don't have much experience with yarn lockfiles but I sure remember trying to solve some nasty npm-lockfile merge conflicts. Might be this can be avoided by using exact version requirements in package.json (i.e. avoiding `~`/`^`). Seems like npm 5.7 [has a helper tool](https://docs.npmjs.com/files/package-locks#resolving-lockfile-conflicts) to resolve these, too.

- npm lockfile is more likely guaranteeing you expected versions between installs. It doesn't rely on package.json

    → Again using strict version requirements in package.json might make yarn lockfile behave the same?

### Speed
There used to be a huge difference in speed but it seems like the differences are getting smaller.

@Viper007Bond has a nice speed comparison script you can run: https://github.com/Viper007Bond/npm-yarn-benchmark

Noting that NPM shrinkwrap and npm lockfile are equal in terms of output so speed comparisons using Calypso should still be valid.

### Getting started -devex
Arguably, `yarn` is one more dependency to install, update and learn to use. Consider that [installing it](https://yarnpkg.com/lang/en/docs/install/) might not be very straightforward if you just want to quickly contribute or test Calypso.

You could also keep using `npm` commands and use `yarn` [as a dependency](https://www.npmjs.com/package/yarn) under the hood. ;-)

---

Aight, hope this info helps to decide! :-)

**Comment by DanReyLop** [comment]
> Since Calypso is using npm shrinkwrap (updated manually), comparisons would be fairer if we'd assume a move to npm lockfile (updated automatically).

I'd love to see this misconception die eventually. `package-lock.json` is **exactly the same** as `npm-shrinkwrap.json`. Just because it's "the new thing", it doesn't make it better. See the first section of [this document](https://github.com/npm/npm/blob/latest/doc/spec/package-lock.md). The only difference between the 2 of them is that `package-lock.json` is supposed to be packaged when you upload your project to `npm` and `npm-shrinkwrap.json` is not (maybe I'm paraphrasing). In short, `shrinkwrap` is for apps, `package-lock` is for libraries, and `wp-calypso` is an app.

In theory, when you have a `shrinkwrap` (or `package-lock`) and do `npm install foo --save` (I think the `--save` flag is the default now, but I digress), it will add `foo` to the `package.json`'s `dependencies` **and** autonatically update the `shrinkwrap/package-lock`. Same with any other command that changes `package.json`, such as `npm remove foo`. The reasons why we have that convoluted `npm run update-deps` command are:
* That doesn't always work. Specially with older versions of `npm`, `npm install foo --save` would install the package, update `package.json`, but fail regenerating the `shrinkwrap`. Then, the only options would be to manually edit the `shrinkwrap`, or nuking `node_modules` and starting again from scratch.
* Updating transitive dependencies. Suppose we depend on `foo 1.2.3`, and `foo` depends on `bar 1.0.x`. When we generated the `shrinkwrap`, the latest version of `bar` available was `1.0.0`. A day later, `bar 1.0.1` is released with a critical fix. Running `npm run update-deps`, since it reinstalls everything from scratch, will pick all the latest versions of the sub-dependencies that match the `semver` patterns, so it would pick `bar 1.0.1`.

All that said, I don't know if we still have to nuke the `shrinkwrap` every time we install a package, I thought this had improved in `npm 5`. If `yarn` improves that, I'd say that's reason enough to switch.

**Comment by simison** [comment]
Ah, thanks @DanReyLop! I stand corrected:

Both `npm-shrinkwrap` and `package-lock` indeed get updated for operations modifying `./node_modules`.

**Comment by gwwar** [comment]
> The only difference between the 2 of them is that package-lock.json is supposed to be packaged when you upload your project to npm and npm-shrinkwrap.json

Yeah, almost! _package-lock.json_ is never published, but a shrinkwrap will be. Libraries use to use the package-lock.json to not force consumers into using exact dependencies, whereas a shrinkwrap is desirable for applications for repeatibility.

See docs: https://docs.npmjs.com/files/package-lock.json
>One key detail about package-lock.json is that it cannot be published, and it will be ignored if found in any place other than the toplevel package.

**Comment by gwwar** [comment]
> All that said, I don't know if we still have to nuke the shrinkwrap every time we install a package

We don't need to if the npm install save works, but it does tend to fail a decent amount for us in wp-calypso. Folks also tend not to notice/understand the error message so it was safer to instruct folks to always use the our update-deps script.

**Comment by samouri** [comment]
> whereas a shrinkwrap is desirable for applications for repeatibility.

I don't think I understand that point.  How could it be desirable for applications considering the difference only matters once published to npm?  Applications don't get published to npm, they get deployed to servers

**Comment by gwwar** [comment]
> Applications don't get published to npm

We don't with wp-calypso but other folks might. Imagine, instead if our docker file instead did a `npm install wp-calypso@x.x.x` instead of a clone from master.

**Comment by DanReyLop** [comment]
> One key detail about package-lock.json is that it cannot be published, and it will be ignored if found in any place other than the toplevel package.

Ok I remember now. Since we use `wp-calypso` as a dependency in `woocommerce-services`, we prefer that we keep `npm-shrinkwrap.json` so all the `wp-calypso`'s transitive dependencies will be locked down. If Calypso moved to `package-lock.json`, `woocommere-services` would have it a bit harder to "pin" versions of the `wp-calypso` dependency, since both the `wp-calypso` commit SHA **and** the moment you changed it would influence the final dependency tree. It's not a major thing and it only affects a small team, but since there's absolutely no other difference between the 2 files that applies to `wp-calypso`, please keep the `shrinkwrap` if you stay with `npm` :)

**Comment by samouri** [comment]
@DanReyLop: if `woocommerce-services` is using Calypso as a dependency and adhering to its shrinkwrap, doesn't that introduce a lot of bloat into your `node_modules`?

**Comment by DanReyLop** [comment]
> if woocommerce-services is using Calypso as a dependency and adhering to its shrinkwrap, doesn't that introduce bloat into it's node_modules?

It does, but we live with it. `woocommerce-services/node_modules` is basically 90% Calypso, 10% everything else, but everything we aren't using isn't included in the final JS bundle so we're OK with that. Also, now our extension is "hybrid", with most of the code living in `wp-calypso/extensions/woocommerce/woocommerce-services`, so it's too late to change it to `dops-components` (which is deprecated anyways) or  splitting parts of Calypso using `lerna`.

**Comment by samouri** [comment]
closing this due to a lack interest

**Pull request closed without merging**
