### PR TITLE
Starter Page Templates: Update layout groupings and auto-selection

### PR DESCRIPTION
**Pull request by Copons**
#### Changes proposed in this Pull Request

* Switch the order of Starter Page Templates categories, showing homepage layouts first, and then the others.
* Homepage layouts always show the current theme's layout if it exists, and then all the others sorted by title.
* Auto-select the current theme's layout if it exists, or Maywood's, or Blank (which always exists, as it's created by the plugin itself).

| Front Page | Regular Page |
| - | - |
| Screenshot 2019-11-18 at 18 35 43 | Screenshot 2019-11-18 at 18 36 02 |

#### Testing instructions

* Apply D35170-code and sandbox the API.
* Build this PR on an FSE test site.
* Set a static front page in Settings -> Reading, or Customizer -> Homepage Settings.

With the Maywood theme:
* Create a new page.
  * The default layouts should be the first category.
  * The Blank layout is auto-selected.
  * The homepage layouts are sorted by title.
* Edit the front page and change its layout.
  * The homepage layouts should be the first category.
  * The Maywood layout is first, and all the other homepage layouts are sorted by title.
  * The Maywood layout is auto-selected.

With any other template-first theme (e.g. Exford):
* Create a new page.
  * The default layouts should be the first category.
  * The Blank layout is auto-selected.
  * The homepage layouts are sorted by title.
* Edit the front page and change its layout.
  * The homepage layouts should be the first category.
  * The current theme's layout is first, and all the other homepage layouts are sorted by title.
  * The current theme's layout is auto-selected.

With any other non-template-first theme (e.g. Twenty Twenty):
* Create a new page.
  * The default layouts should be the first category.
  * The Blank layout is auto-selected.
  * The homepage layouts are sorted by title.
* Edit the front page and change its layout.
  * The homepage layouts should be the first category.
  * The Maywood layout is first, and all the other homepage layouts are sorted by title.
  * The Maywood layout is auto-selected.

### CODE REVIEW

**Comment by apeatling** [comment]
We should only display these first for front/home page creation/edits.

**Comment by apeatling** [comment]
I'm not very comfortable with the labels:

"Choose a layout..." and "Other layouts"

* One is a call to action, the other is not.
* One label includes ... the other does not.
* It's unclear what the difference between the top section layouts and other layouts actually is.

"Front page layouts:" and "Other page layouts:" seems better to me. /cc @olaolusoga @shaunandrews

**Comment by shaunandrews** [comment]
> Auto-select the current theme's layout if existing, or Maywood's, or Blank (which always exists, as it's created by the plugin itself).

Could we move the current layout to the first option as well as selecting it?

> We should only display these first for front/homepage creation/edits.

Just want to confirm that we only show the homepage layouts on the top when editing the homepage — not for all new page creation.

**Comment by apeatling** [comment]
> Just want to confirm that we only show the homepage layouts on the top when editing the homepage — not for all new page creation.

Yes, only homepage edits. Any other page it should not be at the top.

> Could we move the current layout to the first option as well as selecting it?

+1

**Comment by Copons** [comment]
Updated the PR and the testing instructions! Wouldn't mind some new 👀

**Comment by noahtallen** [comment]
But I'm also seeing some weird stuff locally trying to open an arbitrary page:

Screen Shot 2019-11-18 at 4 45 38 PM

**Comment by noahtallen** [comment]
@copons I hope you don't mind -- I pushed a small change in 03de965 which fixes the last comment I noticed.

I also made a tweak to the selector such that it uses template that was previously used for the page if it exists, instead of just defaulting to the theme's homepage template.

**Comment by noahtallen** [comment]
I did some digging around to see if I could figure out what was causing this so that you could merge it quickly tomorrow, but I'm clueless. I don't understand why the API request works in docker, but not wpcom :/

**Comment by Copons** [comment]
Thanks for the `undefined` fix @noahtallen!

The other issue is unrelated to this change, and caused by how we _sandbox our sandboxes_.
Those console errors are not caused by SPT but by the sandboxed API, since our call comes from PHP and not JS.
The missing layouts instead are because we sandbox the API locally, but the sandbox calls production.
@vindl managed to make it call the sandbox instead, and to successfully return the layouts. ✨

**Pull request merged**
