### PR TITLE
Plugins: fix google-analytics link

### LINKED ISSUE #4993: Plugins (wpcom): GA feature page back button goes to compare page
#### Steps to reproduce
1. Starting at URL: https://wpcalypso.wordpress.com/plugins/site.wordpress.com
2. Click on the Google Analytics plugin
3. Goes to the GA feature page
4. Click Back button
5. It goes to the plans compare page

Not sure what the behavior should be. I just know that it was unexpected.

#### What I expected
I expected it to go back to the Plugins page

#### What happened instead
It went to the plans compare page

#### Screenshot / Video

screen recording 2016-04-25 at 02 11 pm

@retrofox

### PR DESCRIPTION
**Pull request by retrofox**
Fix #4993

* Fix link in google-analytics link: `'/plans/features/google-analytics/{siteSlug}'`
* Fix `back` link in the header cake in the plans page
* Remove unused business-plugin.jsx file

[Here](https://github.com/Automattic/wp-calypso/issues/4993#issue-150954562) description and testing.

cc @drw158 @dmsnell

### CODE REVIEW

**Comment by drw158** [comment]
Hm, the link works, but now the inactive plugin styles are broken (the lower opacity and gray color).

https://github.com/Automattic/wp-calypso/pull/4995#issue-150970994 For reference

**Comment by drw158** [comment]
Master also has the same problem though. I'm not sure what happened. wpcalypso looks fine though.

Shall I create a new issue for the disabled plugins problem?

**Comment by drw158** [comment]
Hah, actually, I was looking at a site that had the Business plan. Never mind!

**Comment by dmsnell** [comment]
> Hah, actually, I was looking at a site that had the Business plan. Never mind!

I wondered if that might have been the case :smile:

**Comment by dmsnell** [comment]
@retrofox :shipit:

**Comment by retrofox** [comment]
thanks guys for the review

**Pull request merged**
