### PR TITLE
Comments: Add author Gravatar in reply field

### LINKED ISSUE #15806: Comments: add avatar to reply field
Similar to the Reader. Avatar can disappear once the field is focused, or the reply field will have to be not 100% width.

### PR DESCRIPTION
**Pull request by Copons**
Closes #15806 

Add the author Gravatar in the reply field.

sep-20-2017 19-25-46

The idea is that both elements "extraneous" to the textarea slide in and out.
The Gravatar slides out when the textarea gets focus, to leave as much room as possible to the actual content.
The Send button slides in when the textarea gets focus, and stays in as long as the textarea contains some content.

The textarea padding slides accordingly so that there's a sort of "everything slides left on focus" / "everything slides right on blur" movement.

### Testing

- Open the Comments section in Calypso (`comments/approved/{ siteSlug }`).
- Expand a comment.
- Play around the Reply field, focusing, blurring, adding and removing content.
- Check that the behaviour is smooth on both desktop and mobile.

### CODE REVIEW

**Comment by folletto** [comment]
Looks good to me, but I'd like Shaun's opinion before merging this.

Code wise, I think `translateX` isn't GPU accelerated (should use `translate3d`?) but I can't find a reliable source on the current, up-to-date status of which properties trigger GPU on which platform.

**Comment by Copons** [comment]
@folletto I think you're correct, and yes it's kinda odd that apparently there are no resources about it anymore. 🤔

**Comment by gwwar** [comment]
> which properties trigger GPU on which platform.

Let's avoid over-optimizing here. Each browser may change it's implementation details of when to use the GPU pipeline, so our CSS hacks today may change tomorrow. Please, stick with clear CSS unless we've identified this as a bottleneck.

Note that if we do trigger the hardware acceleration, remember to test this pretty well. The GPU pipeline tends to be much more buggy with ( gpu x desktop combinations ). I've seen canvas bugs for example that only ever happened on particular hardware.

**Comment by gwwar** [comment]
If you're curious when things get another compositing layer in Chrome check out https://www.chromium.org/developers/design-documents/gpu-accelerated-compositing-in-chrome it's a bit out of date, but explains the details well.

**Comment by folletto** [comment]
> Let's avoid over-optimizing here. 

I agree we shouldn't over optimize — It's however common practice to trigger the GPU in these instances and use `translate3d`, which is still clear to write and explicit.

> Note that if we do trigger the hardware acceleration, to test this pretty well.

This is the case either way: without GPU it can stutter on low-end CPU machines with GPU, with it can stutter in mobiles. It's not clear cut in either direction, that's why I highlighted it and asked for testing in the other issue ([ref](https://github.com/Automattic/wp-calypso/issues/15806#issuecomment-330942477)). ;)

Note that `canvas` is different as it's an entirely separate rendering pipeline from the page layout engine.

**Comment by folletto** [comment]
Actually I just realized this is a separate PR, so @shaunandrews wasn't already pinged here. Doing the ping explicitly. Sorry!

**Comment by kwight** [comment]
@shaunandrews any comments about the animation?

**Comment by gwwar** [comment]
Note, that my comments were not meant to be blocking. 

I think the 2d or 3d transform here is fine, but I honestly don't think we should care about if this is explicitly triggered unless there is a noticeable bottleneck. I think browsers have gotten a lot better, but whenever I see a strange browser bug my first inclination is to turn off hardware acceleration to see if it still exists. I've even answered a few stackoverflow [questions](https://stackoverflow.com/questions/17949782/complex-webkit-bug-relative-position-z-index-overflow-hidden-css3-transfo/18176009#18176009 ) way back when  about it. 

The chromium doc explained how hardware compositing worked in chrome, but I think folks may find this one https://www.smashingmagazine.com/2016/12/gpu-animation-doing-it-right/ a bit more accessible. As you noted @folletto there are trade offs for attempting to trigger hardware acceleration that we should consider.

**Pull request merged**
