### PR TITLE
Signup: Remove unused rebrand-cities flow

### PR DESCRIPTION
**Pull request by tyxla**
#### Changes proposed in this Pull Request

The `rebrand-cities` signup flow is unused (see the `?32169/2021-11-15/to/2021-12-15` tracks funnel).

This PR removes it, along with some related components, utilities, styles and illustrations.

#### Testing instructions

* Smoke test signup and checkout.
* Verify the removed code is not in use.
* Verify tests pass.

### CODE REVIEW

**Comment by jsnajdr** [comment]
The rebrand.city website is still up, but apparently our collaboration agreement has been ended in Nov 2019: p9qBZ1-mu-p2. That confirms it's a good idea to remove this flow.

**Review by jsnajdr — APPROVED** [review]
Good job, `git grep -i rebrand` returns zero results on this branch 🙂

**Comment by tyxla** [comment]
> Good job, `git grep -i rebrand` returns zero results on this branch 🙂

How convenient that this flow was using such an unique keyword in its naming 😉

**Review by p-jackson — APPROVED** [review]
Thanks for the tidy up. I've smoke tested the signup flow and everything's working as expected. I also double checked there aren't any signup flow features that were only used by the rebrand-cities flow.

**Pull request merged**
