### PR TITLE
Checkout: Remove Jetpack thank you

### PR DESCRIPTION
**Pull request by sirreal**
Companion to #33734

With the Jetpack checklist live, folks should never arrive at the post-checkout thank you view for a Jetpack purchase. A redirection has been added in case they do.

Remove stale plans/jetpack-config-v2

This is cleanup and should include no behavioral changes.

#### Testing instructions

* Checkout with different purchase types: Simple, Atomic, Jetpack, non-site (domain?)
* The flows should all remain unchanged.

### CODE REVIEW

**Comment by simison** [comment]
Won't have time to review before Monday but just wanted to celebrate this already now:

image

**Comment by simison** [comment]
Rebased in case, since this was a few days old.

**Comment by ockham** [comment]
I'll rebase again to fix the (unrelated) lint error which was fixed by #33787 since the last rebase.

**Comment by ockham** [comment]
Gonna merge, since failing e2e tests are unrelated (see p1560169158009200-slack-jetpack-crew)

**Pull request merged**
