### PR TITLE
Sidebar Navigation: increase font size for a11y

### PR DESCRIPTION
**Pull request by drw158**
This is an effort to increase all important UI elements to at least a font size of 14px. Currently, the sidebar item text is 13px. 14px makes it more consistent with the text in the filterbar, buttons, masterbar, etc.

The 3 major changes here:
- font size of sidebar items and buttons have increased
- the vertical centering of the buttons and icons is now done with flex (was absolute positioning). This allows for dynamic centering if we ever change the font size in the future. ([exaggerated example](https://user-images.githubusercontent.com/618551/27978723-c9a15f08-6336-11e7-903f-681dc790ed40.png))
- mobile sidebar styles have changed quite a bit. The rows are now smaller in height, but still are within the recommended touch target size

Many things needed to be tweaked for the mobile styles and the reader.

Things to test:
- My Sites
- Me
- Reader
- mobile

Before|After
---|---
before|after

Before and after gif:

jul-07-2017 16-47-58

and for mobile:

jul-07-2017 16-45-57

TODO

- [x] mobile sidebar styles
- [x] "Site Preview" button
- [x] reader sidebar styles
- [x] my sites sidebar styles
- [x] me sidebar styles
- [ ] frontend sidebar styles 😱

### CODE REVIEW

**Comment by folletto** [comment]
Overall seems working well. 

I just noticed this bug on Chrome when resizing the window. Might not appear on Mobile (I haven't tested) but could be an issue:

screen shot 2017-07-10 at 09 51 03

Also, might be a problem with centering at the current sizes, but they all look off a little bit, more evidente with Pages:

screen shot 2017-07-10 at 09 52 54

I agree should be a little lower to balance the capitalization, but seems about 1-2px too low? What do you think?

**Comment by drw158** [comment]
Looks like I forgot to commit, sorry about that. Ready for another look.

**Comment by folletto** [comment]
Did a check on Chrome, Firefox, Safari iOS. 
Apart from the above mentioned alignment matter, seems good now :)

**Comment by drw158** [comment]
Line height seems to do the trick 

screen shot 2017-07-12 at 11 11 28 am

**Comment by drw158** [comment]
Up for another review

**Comment by folletto** [comment]
Tested in Chrome, design wise 👍 
Code also looks good — and simpler too 🚢

**Pull request merged**
