### PR TITLE
Stop section changes from re-rendering SiteNotice

### PR DESCRIPTION
**Pull request by mreishus**
Alternate implementation of #46676

#### Changes proposed in this Pull Request

* Stop messagePath changes from rerendering `SiteNotice`

#### Testing instructions

See #46676

### CODE REVIEW

**Review by getdave — COMMENTED** [review]
Thanks for the alternative implementation 👍 

This is actually quite similar to the route I _was_ taking (ie: just pass the final parameter of the `messagePath` and leave `JITM` component to build the rest) before I changed tack to use a function. I went for a function because:

1. It caused minimal change to the original component API.
2. Backwards compatible by default. Requires no changes to existing components' usage.
3. Very flexible should `messagePath` need to evolve in future.

I have few questions about your approach:

1. What happens if I need a custom `messagePath` that doesn't involve `sectionPath`? 
2. Does this test as per https://github.com/Automattic/wp-calypso/pull/46676/? Do we see the same results when profiling...etc?
3. Does the `calypso:theme:admin_notices` in `main.jsx` definitely always end up being correct now we're not hard coding the `theme` portion of `messagePath`

Also what are the pros/cons of this approach vs https://github.com/Automattic/wp-calypso/pull/46676 ?

**Comment by mreishus** [comment]
>What happens if I need a custom messagePath that doesn't involve sectionPath?

Using the new component `<JITMLoader>`, it isn't possible.  I don't think it's needed, and sometimes it can be an advantage to be less flexible.  If you needed to, you could refactor the `<JITMLoader>` or call `<JITM>` directly and pass your own messagePath.

>Does this test as per #46676? Do we see the same results when profiling...etc?

Yes, I'm seeing the same reduction in rendering, both from removing `messagePath` from the `SiteNotice`'s props.  Basically the same thing in the react profiler.

>Does the calypso:theme:admin_notices in main.jsx definitely always end up being correct now we're not hard coding the theme portion of messagePath

It was the same in my testing.


>Also what are the pros/cons of this approach vs #46676 ?

Pros:
- I consider this approach simpler for the caller.  (Imagine a second, new component needing to add JITM). They render `<JITMLoader messagePathSuffix="sidebar_notice">` and they're done.  They don't have to consider:
  - Why does the messagePath prop take both string and function forms?
  - Which one should I use and why?
  - Passing a function as a prop (which isn't that bad on its own, but is incremental complexity)
  - How do I need to compose a messagePath (which parts go into in which order?)
- Overall, I hope to extract the "work" of building a messagePath into a simple component which is reusable, and can be used without knowing the details of how to build a messagePath without messing up your own rendering times.


Cons:
- On the other hand, this approach is less flexible as you're forced into a `calypso:section:suffix` path.
- The complexity isn't removed, just rearranged.  So a caller using #46688 could easily ask themselves, why do both `<JITM>` and `<JITMLoader>` components exist?  Which should I use and why?
- I'm not entirely happy with the name `<JITMLoader>`, doesn't seem to describe it properly.

I'll leave it up to you as to what to go with.

**Comment by getdave** [comment]
Thanks, @mreishus for such a solid response. Much easier now to appreciate the benefits of your alternative approach.

> I don't think it's needed, and sometimes it can be an advantage to be less flexible. 

Agreed. Sometimes adding a new API for a use case that hasn't yet materialised (ie: needing to build a `messagePath` that doesn't involve `sectionName`) can unnecessarily increase complexity.

-----

Overall I prefer your approach because:

1. It abstracts the complexity of _building_ the `messagePath` to the component which cares about it (ie: `JITM`).
2. Keeps the props API simple for `JITM` - no need to worry about functions.
3. Retains the same benefits as my original approach.

TBH, I probably shouldn't have become sidetracked with a more complex function-based idea so I appreciate you taking the time to review the original PR and raise this alternative 👍 👍

**Comment by getdave** [comment]
# Update

We may end up going with a hybrid approach https://github.com/Automattic/wp-calypso/pull/46713

**Comment by mreishus** [comment]
See #46713

**Pull request closed without merging**
