### PR TITLE
Adds reskinning signup flow for domains step

### PR DESCRIPTION
**Pull request by aneeshd16**
#### Changes proposed in this Pull Request

* Adds redesigned domains step screen to the reskinning signup flow project. More details can be found in #44223

#### Testing instructions

* Go to /start/new
* Make sure you're assigned to the reskinned group of reskinSignupFlow a/b test.
* Follow the signup flow till you are on the domains step.
* The screens should look like these:

Domain (unfocused)
Domain (unfocused)
Domain (focused)
Domain (focused)
Filters
unfocused)
Domain (extensions)
Domain (extensions)
Domain (options)
Domain (options)
Domain (search)
Domain (search)
Domain (selection hover)
Domain (selection hover)

### CODE REVIEW

**Comment by taggon** [comment]
@aneeshd16 This PR works great except for the focused color. If I understand correctly, the background color of the search field should be white when it has a focus. Can you fix it?

Create_a_site_—_WordPress_com

**Comment by niranjan-uma-shankar** [comment]
Also, when I reload the page sometimes, I see the old UI, same as what @claudiucelfilip reported in another PR.

**Comment by aneeshd16** [comment]
Thank you for the detailed review @niranjan-uma-shankar! This is great attention to detail, and there is much to learn for me here. :)

> It looks to me from the Figma that the hostname part of the domain in the suggestions list has a font weight that makes it look slightly bolder but this is missing in the PR:
> Also, the font weight for the hostname part of the domain needs to be higher.

The designs have used a font-weight of `500` in several places. But the allowed font-weights according to our linter are `400, 600, 700`, so for now I have kept these as they were.

These were the changes requested:
- [ ] When a filter is applied, it is highlighted in pink(check screenshot after point 2). d8f7b6f9786041e2c04047b93959566803195fb3
- [ ] From the Figma, the background color for the search input box should be white. 765e6631856ed3b37a535001944932c6afabac9f
- [ ] Review our plans to get started » does not need the double angle quotation mark 52508bf421e2486252a689d4a778a590006be424
- [ ] In the More Extensions section, I think that the on-hover highlight should be in blue too: b0ab2586c36bd274e1884386709a1868aa469a8f
- [ ] When I hover over the free *.wordpress.com domain and then move to the custom domains, it feels a little jumpy and slightly distracting. I also get a slightly jumpy experience when moving the mouse over the other domains: 289fc679c2d2442aa23493cb87570fb71d4d57c9
- [ ] The "Use a domain I own" part has a slight animation to it, not sure if it's intended but might probably need a design check: 289fc679c2d2442aa23493cb87570fb71d4d57c9
- [ ] The select button state on clicking it is in pink. It's not clear from the Figma what should be the colour though:
- [ ] The "Free" text for the *.wordpress.com domain needs to be in green as per Figma 289fc679c2d2442aa23493cb87570fb71d4d57c9
- [ ] It looks to me from the Figma that the hostname part of the domain in the suggestions list has a font weight that makes it look slightly bolder but this is missing in the PR:
- [ ] The mobile view is missing the Select buttons. Also, the font weight for the hostname part of the domain needs to be higher. 11168f16e0c8b9c5c7f4fb0536a79c7336fbd62c
- [ ] The "Get a free one-year domain ..." section in mobile needs to be without line breaks, together as one para(from Figma). a482b01f227faf9ec8ca2a7a90b1d1c406ea19ff
- [ ] When an extension is selected from the "More Extensions" section, it is to be highlighted in blue per Figma. In the PR, there is no highlight getting applied: b0ab2586c36bd274e1884386709a1868aa469a8f

**Comment by niranjan-uma-shankar** [comment]
Thanks for making all those changes! 

> I think we can use the "60" version of our blue color instead of --color-accent-60 and it should be okay. I will check with the design team to make sure though.

Yup, makes sense to check with design. I know this is still WIP but I noticed that if I click Select on the domain search results list, it no longer shows the is-busy state. Please ignore if you are aware of it:

reskin-domain


> The "Free" text for the *.wordpress.com domain needs to be in green as per Figma

Confirming that the colour change works. It looks like the font size is smaller than the "Free" appearing other search results. Should that be fixed?

Screenshot 2020-07-30 at 10 56 28 AM

> When I hover over the free *.wordpress.com domain and then move to the custom domains, it feels a little jumpy and slightly distracting. I also get a slightly jumpy experience when moving the mouse over the other domains

Thanks for fixing this, it feels smooth now 👌🏼

> The mobile view is missing the Select buttons

Clicking the Select button in mobile view is selecting the next domain instead of the one I clicked. In the gif below, I clicked on crystallball.games but crystallball.hockey got selected.

reskin-domain

> The designs have used a font-weight of 500 in several places. But the allowed font-weights according to our linter are 400, 600, 700, so for now I have kept these as they were.

Good point. I like the bold highlight of the hostname but @ollierozdarz would be able to advise on the best way to move forward on this.

**Comment by aneeshd16** [comment]
Thanks for the follow up review, appreciate it! 👍 
- [ ]
  > Yup, makes sense to check with design

I did, thanks @ollierozdarz https://github.com/Automattic/wp-calypso/pull/44463/commits/fcca8adb11a67268a9686297664a21ffa335954b
New design: (The animation is smooth, the jerk in the GIF is due to its looping)
Kapture 2020-07-30 at 12 59 56


- [ ]
  > I know this is still WIP but I noticed that if I click Select on the domain search results list, it no longer shows the is-busy state. 

https://github.com/Automattic/wp-calypso/pull/44463/commits/c856baa98459d4bee945ea23d1d8099a53fe679e
- [ ]
  > It looks like the font size is smaller than the "Free" appearing other search results. Should that be fixed?

https://github.com/Automattic/wp-calypso/pull/44463/commits/df8126ce5f1df5be7692da20ea1561edfd5bc24a
- [ ]
  > Clicking the Select button in mobile view is selecting the next domain instead of the one I clicked. In the gif below, I clicked on crystallball.games but crystallball.hockey got selected.

This was a great catch! In mobile, on clicking the button, the `hover` state got activated which changed the height of the block and resulted in the click event getting fired on the next button in the list. Solved this by enclosing the hover CSS in a breakpoint. https://github.com/Automattic/wp-calypso/pull/44463/commits/4fcad4122b402e136db07d63fd9dfa8aae770e94

**Comment by aneeshd16** [comment]
Rebased.

**Comment by aneeshd16** [comment]
> WordPress Desktop CI Failure for job "wp-desktop-source".
> 
> @aneeshd16 please inspect this job's build steps for breaking changes at [this link](https://circleci.com/gh/Automattic/wp-calypso/831551). For temporal failures, you may try to "Rerun Workflow from Failed".
> 
> Please also ensure this branch is rebased off latest Calypso.

The error is in the checkout step,

```
fatal: Couldn't find remote ref add/reskinning-signup-flow-domains-step
```

I think we can safely ignore this message.

**Comment by nsakaimbo** [comment]
@aneeshd16 Looks like this failure is occuring in at least one other PR: ([link](https://github.com/Automattic/wp-calypso/pull/44392))

```
add/reskinned-user-step:remotes/origin/add/reskinned-user-step
```

It appears that for some reason Circle is trying to check out a branch that was already deleted?

**Comment by aneeshd16** [comment]
> @aneeshd16 Looks like this failure is occuring in at least one other PR: ([link](https://github.com/Automattic/wp-calypso/pull/44392))
> 
> ```
> add/reskinned-user-step:remotes/origin/add/reskinned-user-step
> ```
> 
> It appears that for some reason Circle is trying to check out a branch that was already deleted? (maybe the branch was merged and auto-deleted prior to CI completing)

@nsakaimbo yes, that seems to be the case. We created https://github.com/Automattic/wp-calypso/pull/44223 as the "parent" branch and then created these 4 PRs based on the parent branch:
 Signup step (#44392)
 Domain step (#44463)
 Plans step (#44325)
 Processing screen (#44453)

Merging the "child" branches caused them to be auto-deleted. Possible that some builds were still running when we merged these to the parent branch. Thanks for clarifying this here!

**Pull request merged**
