### PR TITLE
Jetpack Connect: Activate Jetpack Manage

### PR DESCRIPTION
**Pull request by roccotripaldi**
Activating Jetpack's Manage module after the authorization is complete, and a user clicks to browse upgrades.

To test:
- Apply this PR to a Jetpack site: https://github.com/Automattic/jetpack/pull/3733
- Turn off 'Manage' and disconnect Jetpack
- Apply this PR to your local Calypso
- In your console, run `localStorage.setItem( 'debug', 'calypso:jetpack-connect:*' )`
- Visit calypso.localhost:3000/jetpack/connect, and go through the steps to connect your Jetpack site
- In the final step click 'Browse Available Upgrades'
- Note that the debug messages in your console say that Manage is activated
- Check your site and make sure Manage is activated

Note: The UI is still primitive. @rickybanister has some mocks that will make it clear to the user that they are turning on the Manage module

CC @johnHackworth

### CODE REVIEW

**Comment by johnHackworth** [comment]
woooooooooooooooooooooooo \o/

works great! I just found a small bug: When you activate manage, we should force again a fetch of the sites list: I went to /plugins/ after going to plans, and I got to see the jetpack-manage error page for a couple of seconds, until the site list got refreshed

**Comment by ebinnion** [comment]
I haven't looked at code or tested, but why are we making it conditional on whether the user clicks "Browser upgrades"? What if the user clicks any of Masterbar nav or clicks "I'm not interested in upgrades"?

**Comment by roccotripaldi** [comment]
@ebinnion - it is conditional. It only happens when you click 'Browse Upgrades' - I think we will soon make it more clear to the user what they are getting themselves into :)

**Comment by johnHackworth** [comment]
I've rebased this to master and updated & solved all the conflicts. My previous comment about fetching sites is probably not longer relevant, because we are changing the flow... since this works ok even if the jetpack PR is not merged (obviously without that the manage part doesn't work), let's merge it! :)

:ship:

**Comment by roccotripaldi** [comment]
thanks for the rebase @johnHackworth

**Pull request merged**
