### PR TITLE
AB test: Plans: Remove the skipForFree test

### PR DESCRIPTION
**Pull request by scruffian**
This test has finished running now, so we can remove it.
 
#### Testing instructions

1. Run `git checkout delete/skip-for-free-test` and start your server
2. Open the [`Start` page](http://calypso.localhost:3000/start) in a private window
3. Check that the signup flow works as expected

#### Reviews

- [x] Code
- [x] Product

### CODE REVIEW

**Comment by stephanethomas** [comment]
Code looks good to me.

**Comment by fabianapsimoes** [comment]
Product :+1:

**Comment by drewblaisdell** [comment]
I rebased this branch.

Shouldn't we remove the other code associated with this test, like the `upgrade` flow and `select-plan-or-skip` step?

**Comment by drewblaisdell** [comment]
I discussed this with @scruffian, and based on the performance of the current test, opened an issue for removing the dead code here: #3734

**Pull request merged**
