### PR TITLE
VideoPress: Onboarding intent as flow intro

### PR DESCRIPTION
**Pull request by thedebian**
## Proposed Changes

* Replaces the current VideoPress intro with our temporary "onboarding intent" page
* Creates the onboarding intent page with bare minimum things
* Add change behind feature flag

## Testing Instructions

* Apply PR
* `yarn start`
* Go to `/setup/videopress`
* ✅ You should still be redirected to /setup/videopress/intro
* ✅ The onboarding intent page should be displayed instead of the normal intro
* Click on a bunch of intent buttons
* Wait for about 5 minutes
* Go to tracks live view
* Search for calypso_videopress_onboarding_intent_clicked
* ✅ The clicks should be registered there (should appear within 5 minutes or so)

### CODE REVIEW

**Review by jgcaruso — APPROVED** [review]
Looks good and clicks are counted and match up with the correct intent string.

The feature flag is working as expected... test url at `https://container-pedantic-torvalds.calypso.live/setup/videopress` shows old onboarding Intro, and `calypso.local` development shows the new User Intent screen.

I noticed the screen wasn't keyboard accessible, but I created a separate card to address that instead of adding it here and making this PR larger https://github.com/Automattic/greenhouse/issues/1836

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/8815375

Hi @thedebian, could you please edit the description of this PR and add a screenshot for our translators? Ideally it'd include all of the following strings:
- `Share your work with the world.`
- `The easiest way to upload videos and create a community around them.`
- `Just put a video on the internet.`
- `Add video to an existing site`
- `All the advantages and features from VideoPress, on your own WordPress site.`
- `Start a blog with video content`
- `Use advanced media formats to enhance your storytelling.`
- `What are you looking for? Let us know!`
- `Choose an option to continue, or let us know what you’re looking for.`
- `The best blogging system with the best video.`
- `Create a new blog on WordPress.com with unmatched video capabilities out of the box.`
- `The best premium themes at your disposal.`
- `Get started with premium`
- `A home for all your videos.`
- `VideoPress TV is the easiest way to upload videos and create a community around them.`
- `Ready to go! No setup needed.`
- `The easiest way to upload your videos.`
- `Earn money through subscriptions.`
- `Foster and engage with your community.`
- `Which additional features are you looking for?`
- `Add videos to your existing site.`
- `Already have a self-hosted WordPress site? Enable the finest video with Jetpack VideoPress.`
- `High-quality, lightning-fast video hosting.`
- `Drag and drop videos directly into WordPress.`
- `1TB of storage and unlimited users.`
- `Discover Jetpack VideoPress`
- `Get started - from %s/month`
- `Your video portfolio, with no hassle.`
- `The fastest way to share a video.`
- `All the power of VideoPress, simplified.`
- `Upload a video file and obtain a share link. That’s it.`
- `Embed your video anywhere.`
- `Are you interested in specific features?`
- `Coming soon!`
- `In the meantime, you can {{a}}create a video portfolio{{/a}}, {{b}}a blog with video{{/b}}, or {{c}}add videos to your existing site{{/c}}.`
- `Answer the survey`
- `Coming soon`
- `Send your feedback and help us shape the future of VideoPress by answering this short survey.`
- `Showcase your work`
- `Create a community`
- `What would you like to use video for?`

Thank you in advance!

**Comment by dlind1** [comment]
@thedebian :wave: in string `Answer a short survey and you’ll have the chance to win $50.`, does it remain $50 in other countries as well or should it be localized somehow?

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/8815375).

**Pull request merged**
