### PR TITLE
Enable the new pricing page in horizon, staging, and production.

### PR DESCRIPTION
**Pull request by southp**
## Proposed Changes

This PR enables the new pricing grid to all the production environment, including horizon, staging, and the production.

## Testing Instructions
Mainly code review and E2E tests to make sure nothing obviously broken. It's possible to mimic the production environment by running a docker container and pointing wpcom domain to it, but the effort would arguably outweigh the gain in this case.

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

**Comment by worldomonation** [comment]
@Automattic/kitkat Heads up.

**Comment by worldomonation** [comment]
@southp Do all E2E tests pass? I've triggered a run of the Pre-Release Tests against this branch, because Pre-Release Tests don't actually incorporate changes on the feature branch by default - see PCYsg-JGn-p2 for more information.

Edit: Pre-Release Tests passed.

**Comment by southp** [comment]
Ah, thanks for checking @worldomonation . I do have once again forgot that the pre-release tests need to be triggered manually 🤦🏼 Really appreciate your help.

**Review by aneeshd16 — APPROVED** [review]
LGTM! 😄

**Review by ddc22 — APPROVED** [review]
🥁 LGTM 🚢

**Pull request merged**
