### PR TITLE
Gutenberg: Placeholder PR for testing Gutenberg 6.7.0 on Horizon. [WIP]

### PR DESCRIPTION
**Pull request by kwight**
**Do Not Merge**

A PR against which to run Horizon e2e tests on `6.7.0-alpha`.

### CODE REVIEW

**Comment by gwwar** [comment]
Part of https://github.com/Automattic/wp-calypso/issues/36576

**Comment by kwight** [comment]
Retesting this to piggyback e2e tests for CoBlocks, which is now 1.15.0 on Horizon.

**Comment by kwight** [comment]
Rerunning tests after updating 6.7.0-alpha to https://github.com/WordPress/gutenberg/tree/401ed2308de86f4b3efd849d3cc4ac52c92b928c.

**Comment by kwight** [comment]
Testing with `6.7.0-rc.1`.

**Comment by kwight** [comment]
Testing with 6.7.0 final.

**Comment by kwight** [comment]
Gutenberg 6.7.0 final is now running in production.

**Pull request closed without merging**
