### PR TITLE
WIP: Replace draft-js with contentEditable for title format editor

### PR DESCRIPTION
**Pull request by dmsnell**
**Work in Progress!**

This patch intends on removing the dependency on `draft-js` for
the Custom Title Format editor in the **Traffic** settings for a site.

There are some fundamental tradeoffs that I think we would have
to accept in order to cut out the dependencies on `Immutable` and
`draft-js` that this patch opens up: namely that there appears to
be no way to make backspacing and arrow-keying around tokens
work in Firefox. In order to overcome this major obstacle then I think
we'd end up recreating most of `draft-js` or accept other oddities
across other platforms, such as messed-up undo/redo or missing
things like certain updates.

State is a bit weird in order to prevent reversing the input (odd but
I can explain later if you don't know what I'm talking about) and in
order to preserve native undo/redo. Again, to fix this would probably
involve significant work recreating what `draft-js` provides.

It appears like `draft-js` is placing an additional 40 KB of gzip'd code
on the settings bundle, but as we remove other dependencies on
`Immutable.js` that will also be freed up by this PR and could result
in more savings.

Originally we chose `draft-js` as a test for the reasons that it normalizes
browser behavior, works well, and its additional size is limited to the
**Traffic** bundle. It may very well be that these reasons still hold but
it would be even better if we could figure out that we can reliably replace
it. Probably if we can it will be on account of our aggressive browser version
deprecation policy.

### CODE REVIEW

**Comment by ockham** [comment]
> namely that there appears to be no way to make backspacing and arrow-keying around tokenswork in Firefox. 

Hmm, can we use our own [`TokenField` component](https://wpcalypso.wordpress.com/devdocs/design/token-fields)? Key handling seems to work fine there...

**Comment by dmsnell** [comment]
> Hmm, can we use our own TokenField component? Key handling seems to work fine there...

that was another immeasurable obstacle when the `draft-js`-based component was originally introduced. `TokenField` was doing something way different (at least at the time) when we wanted "plain text + scattered tokens"

I'll double-back soon to make sure it didn't drastically change, but it's code was terrifying to me and its behavior different.

we have no good options on this one

**Comment by ockham** [comment]
> I'll double-back soon to make sure it didn't drastically change, but it's code was terrifying to me and its behavior different.

FWIW, I did a bit of a refactor of `TokenField` about a month ago to change some of its gratuitous use of  `refs` into more semantic `state` handling (and passing to child components); however, that didn't mean overhauling the entire component, so it's still rather complex. But yeah, do give it a quick look if you have a few minutes.

**Comment by dmsnell** [comment]
Closing due to no time to continue working on this. It's still probably holding on to immutable.js and will need to be updated in the future. Hopefully someone can latch onto this work.

**Pull request closed without merging**
