### PR TITLE
Build: update to node 6.7.0

### PR DESCRIPTION
**Pull request by gwwar**
This PR updates Calypso to node v6.7.0 for the following [security fixes](https://nodejs.org/en/blog/vulnerability/september-2016-security-releases/) . Since this update includes security fixes across all active Node lines, we'll forgo desktop testing.

### Local Dev
- Switch to node version 6.7.0 (npm 3.10.3)
- `make distclean`
- `make run`
- No functional changes to Calypso

### Local Docker Image
- Follow image instructions at: PCYsg-5XR-p2

### Desktop (optional)
- Clone the wp-desktop project
- Follow install instructions
- In the calypso submodule checkout this branch
- Desktop behaves normally

cc @matias @blowery @lamosty @gziolo @rralian @aduth @mkaz @sendhil

### CODE REVIEW

**Comment by gwwar** [comment]
I tested this locally and on the docker 🐳 image and there doesn't seem to be any regressions.

Note that there may be some existing visual bugs (#8160) that are being fixed in other PRs

**Comment by dmsnell** [comment]
@gwwar I tested this locally and everything seemed to work fine! I give it my 👍

**Comment by sendhil** [comment]
Desktop seems ok, 👍 .

**Comment by gziolo** [comment]
I tested this locally, too.

I see some new warnings when executing unit tests:

> (node:54498) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 210): Error: Driver not found.
(node:54498) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 213): Error: No available storage method found.
(node:54498) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 215): Error: Driver not found.
(node:54498) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 218): Error: No available storage method found.

**Comment by lamosty** [comment]
I get the same warnings/errors as @gziolo after running `make test`. However, the tests all pass.

I just tested this in both local Calypso and Docker image. Both working fine.

If we don't mind the tests errors, I would say :shipit:.

**Comment by gwwar** [comment]
Thanks for the reviews! Let's 🚢 this today, and I'll open up issues to follow up on the new test warnings.

**Pull request merged**
