### PR TITLE
Plans: Header price-discounting refactors

### PR DESCRIPTION
**Pull request by chriskmnds**
Related to https://github.com/Automattic/martech/issues/3403

## Proposed Changes

- Follow-up on https://github.com/Automattic/wp-calypso/pull/96357 to improve the logic around discounting price display - in particular, how non-discounted prices are displayed when another discounted price is rendered.
- Explored a couple of ideas, all depicted across the first few distinct commits:
  - use the `wpcom-plans-ui` wp-data store
  - a localised `userEffect` hook
  - a header-price context provider
- Header-price context seems to lead to the least amount of ambiguity and code duplication

## Why are these changes being made?

The goal is to (1) centralize the logic outlined above, (2) reduce processing, (3) avoid code duplication.

## Testing Instructions

- Go to `/plans/:site?flags=plans/term-savings-price-display` and `/start/plans?flags=plans/term-savings-price-display`
- Ensure for yearly and above the savings are displayed as per media above
- Try the same with a coupon (need to find one) or active intro offer (need to mock/code it) and ensure those discounts render instead for the respective plans

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Comment by chriskmnds** [comment]
@jeyip still WIP and something to ship last. Let me know if you get a chance to review the code at least. The functionality should be the same. The changes circle around how we align the header price for a non-discounted plan in a grid with discounts e.g. the "Free" plan's price when term-savings are enabled or intro offers (like first-year currency) for the other plans.

**Comment by jeyip** [comment]
Thanks for tagging. I'll check this out first thing tomorrow morning 👍

**Comment by jeyip** [comment]
## Testing
### Requirements

For each of the flows listed below:
- Ensure for yearly and above the savings are displayed as per media above
- Can still purchase multi-year plans, annual plans, and monthly plans
- Try the same with a coupon ( Ex. federate 25 ) or active intro offer (need to mock/code it) and ensure those discounts render instead for the respective plans in the features + comparison grid
  - Used coupon `federate25` which applies only to annual business and ecommerce plans
  - Visited url http://calypso.localhost:3000/start/plans?flags=plans%2Fterm-savings-price-display&coupon=federate25

Flows:
- [ ] /start
- [ ] /plans

### Browsers
- [x] Chrome

**Comment by jeyip** [comment]
Updated the PR description with some testing instructions for posterity

**Comment by chriskmnds** [comment]
@jeyip thanks for reviewing!

> There's something that I'm not quite clear on -- would you mind explaining a bit more about the change between [wrap header discounting logic in a hook](https://github.com/Automattic/wp-calypso/pull/96492/commits/5ada27f9dfebb667d3d9df19ebebfd2076dc76dc) and [move it to header-price context](https://github.com/Automattic/wp-calypso/pull/96492/commits/9ece3ab483241ebbacf83657e78ff6b9f10c2f63)?

One of the points was to eliminate side effects/knowledge stemming from the component traversing all the grid plans to determine if another header price is discounted. The hook method merely centralised the logic inside an internal hook, but it still needed all the extra knowledge to determine if something else (another instance of the component) has been discounted. With context (or the external store) the component simply "announces" that it has been discounted, and the rest can deal with that. That's the essence pretty much. It also reduces all the traversals happening on rerenders.

> I think I'm missing something, because it seems like we could avoid the extra file and header price context provider by keeping the `const [ isAnyVisibleGridPlanDiscounted, setIsAnyVisibleGridPlanDiscounted ] = useState( false );` hook in the header-price component. Is it because we're going to reuse the logic outside of the component in the near future?

I think what you are missing is the component being rendered in a list. A local variable will be local to each instance.

**Comment by jeyip** [comment]
> I think what you are missing is the component being rendered in a list. A local variable will be local to each instance.

Ah yes that's it. Thanks for elaborating 👍

**Review by jeyip — APPROVED** [review]

**Comment by jeyip** [comment]
There are some [failing unit tests](https://teamcity.a8c.com/buildConfiguration/calypso_calypso_WebApp_Run_All_Unit_Tests/13751551?expandBuildDeploymentsSection=false&hideTestsFromDependencies=false&expandBuildTestsSection=true&hideProblemsFromDependencies=false&expandBuildProblemsSection=true&expandBuildChangesSection=true), but judging by the failures, they're simple reference errors. Things lgtm after those are addressed 🙂

**Pull request merged**
