### PR TITLE
Update Core Profiler loader styles for responsiveness and disable animation

### LINKED ISSUE #89283: Woo core profiler Jetpack connect screen mobile UI issues
### Issue description

When viewing WooCommerce Core profiler Jetpack connect UI via mobile, some parts screens have overflows:

<br>

#### To reproduce:

1. Ensure you're logged in to WordPress.com
2. Set up a fresh JN site
3. Using a mobile browser (tested with Safari/iPhone), go to WooCommerce setup wizard
4. Go through all steps until the plugin step
5. Ensure Jetpack is selected, click Continue
6. Observe the `Connect` button and the text below it is not centered to the screen
7. Click `Connect your account`
8. In the loading screen, observe it's not fullscreen and the loading images are not perfectly centered

### Acceptance criteria

1. UI issues should be fixed

### PR DESCRIPTION
**Pull request by chihsuan**
Closes https://github.com/Automattic/wp-calypso/issues/89283 and related to https://github.com/Automattic/wp-calypso/issues/96420

This PR addresses various mobile UI issues in the WooCommerce Core Profiler’s Jetpack connect screens. These fixes ensure proper alignment and prevent content overflow, improving the user experience on smaller screens. Besides, this PR disables the modal animation to prevent jankiness in the transition to the loader.

## Proposed Changes

* Disable the modal animation to prevent jankiness in the transition to the loader
* Update the Jetpack connect screens to ensure proper alignment and prevent content overflow on smaller screens

## Why are these changes being made?

* Improve the user experience on smaller screens

## Testing Instructions

1. Set up a fresh JN site and log in to WordPress.com.
2. On a mobile browser (e.g., Safari on iPhone) or using DevTools to simulate a mobile device, go to the WooCommerce setup wizard.
3. Proceed through the wizard steps until the plugin step.
4. Select Jetpack, click Continue, and observe:
5. The Connect button and text are now centered.
6. No content overflow issues are present.
7. Click Connect your account and observe the loading screen:
- The screen should be displayed without delay/animations.
- The screen should be fullscreen.
- The loading images should be perfectly centered.

https://github.com/user-attachments/assets/564f2b7f-286f-4f0e-9608-74cf729e3ef0

https://github.com/user-attachments/assets/2e1f3fa5-0139-4af9-bc20-3ec1e2225b19

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
    - [ ] For UI changes, have we tested the change in various languages (for example, ES, PT, FR, or DE)? The length of text and words vary significantly between languages. 
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Comment by psealock** [comment]
@chihsuan, how do you land on the Calypso powered pages? Its all just JN for me.

**Review by moon0326 — APPROVED** [review]
LGTM and tested well 👍 🚀

**Comment by moon0326** [comment]
> @chihsuan, how do you land on the Calypso powered pages? Its all just JN for me.

I think you need to set up https://github.com/woocommerce/woocommerce-start-dev-env to point wordpress.com to your local wp-calypso.

**Review by ilyasfoo — APPROVED** [review]
Tests well! LGTM 🚢

**Pull request merged**
