### PR TITLE
Pages: show pseudo blog page in list

### LINKED ISSUE #3905: Pages: Create a pseudo blog page and add the home icon to it by default
This probably needs to be fleshed out more... maybe a mock and some notes about how this impacts the pages area? Are you able to "edit" the pseudo page? What if you want your blog page elsewhere?

/cc @retrofox @mtias @adambbecker @drw158

### PR DESCRIPTION
**Pull request by mtias**
If site doesn't have a static front page set, show a pseudo-page for the blog indicating it's the current frontpage.

image

Fixes #3905.

### CODE REVIEW

**Comment by rickybanister** [comment]
This is great, we should have done it a year ago.

Could we make the copy say 'Your front page is displaying your latest posts.' instead?

**Comment by mtias** [comment]
Tweaked the message.

**Comment by folletto** [comment]
:100:

**Comment by drw158** [comment]
Sorry a little bit confused. This text refers to the page with the home icon, right?

> Your front page is displaying your latest posts.

This text makes me think that it is referring to another page somewhere else.

**Comment by rickybanister** [comment]
That's true @drw158 

I suppose I just wanted it to mention both 'front page' since we're calling the page title 'blog posts' and mention why your posts are there. I understand why it would be confusing though.

How about:

`Front page—currently displaying latest posts.`

**Comment by drw158** [comment]
I have a slight preference for `Front page and displaying your latest posts`, but I think either would work well.

**Comment by folletto** [comment]
We can also already consider this in the "future" state where we mark both the Front page and the Blog page. The descriptive text should state that "this item IS the front-page" and "this item IS the blog page".

So uhm... maybe:
```
[ Icon ] Blog Posts                                      ( Current home page )
```

?

**Comment by rickybanister** [comment]
Part of the confusion here is the chronological layout. If the front page were the first page and all the others were indented beneath it we would not need to tell you which page is your front page. 

We could also display the page slugs for all pages, which would be helpful since pages can have duplicate names. 

In that world I think we'd just have a little compact notice (flag) that says '[Latest Posts]' or similar floated to the right instead of a sentence.

**Comment by folletto** [comment]
> In that world I think we'd just have a little compact notice (flag) that says '[Latest Posts]' or similar floated to the right instead of a sentence.

Wait, the status isn't "Latest posts" however, that's the content (i.e. the actual page). The status variation is "front page". :) 

Agreed on the rest, we need a next iteration up with hierarchy and proper syntax for single-site pages. Let's ship this one first, since it's simple :D

**Comment by rickybanister** [comment]
I have no idea what 'status variation' means. The home icon indicates that it is the front page. Nothing but the title being set to 'Blog Posts' indicates the function of the page (in this case the function is to display latest posts). I could manually set a page title to the string 'Blog Posts' and get pretty confused. That's why I mentioned displaying a flag representing the front page's status as 'latest posts'.

**Comment by folletto** [comment]
Ah sorry, I'll clarify what I mean. The pages here (in the future, in a hierarchy) represent each one a content item. If we include "Blog List" as we agree it's wise, the blog list itself is one of the possible contents. It's a special one, sure, but that's at the same level of any other page. So, ignoring for a moment the discussion about front-page, it means:

* Blog List
* Page Lorem
* Page Ipsum
* Page Gaium

Where only "Blog list" is a special one.

If we consider the blog list as just another page as the design above is doing (correctly) then it also has a URL, say, `/blog`. 

Which translates to these URLs:

* Blog List `/blog`
* Page Lorem `/lorem`
* Page Ipsum `/ipsum`
* Page Gaium `/gaium`

Up until here all is good. Each one of this is a page, each has a URL, nice and clean.

Then, we have just one variation (the "state" I mentioned above): *being front-page*.

Doing that simply flags one of the pages above, and moves it being the root level one. So for example:

* Blog List `/` (Front-Page State)
* Page Lorem `/lorem`
* Page Ipsum `/ipsum`
* Page Gaium `/gaium`

If we move that somewhere else (in a future PR) we get:

* Blog List `/blog`
* Page Lorem `/lorem`
* Page Ipsum `/` (Front-Page State)
* Page Gaium `/gaium`

In this way we have a clean and effective way to toggle front-pages. :) 

So, to loop back at my advice above: what we need to communicate is a marker (the label copy we were discussing) that describes that "front-page state" in a clear way. It's not about the content, it's about being or not front-end.

**Comment by rickybanister** [comment]
I think I understand, but I think your paradigm above reverses the more intuitive metaphor. 

If we create a placeholder page for the front-page when it displays blog posts, I think we should just leave that placeholder in the pages list all the time. Your site always has a root. It is simply up to you to decide what goes there, another page from your site or your latest posts. 

Asking users to select 'front page' as a status on a page feel backwards. Currently in the reading settings we ask them to select a page to fill the front page—I think we should stick with that paradigm. 

So (when we make this page hierarchical) the front page is always first and to the right we have a drop down allowing users to select either 'Latest Posts' or any of the pages below to serve as the front page's content.

**Comment by folletto** [comment]
I think the placeholder approach is analogous. It's mostly a different way to set the same status. I'd be ok for it with a good UI.

However when we reviewed that in the past, we highlighted that it has an extra disadvantage compared to the "Make this the homepage" one: once you set a different page as the homepage using a "root" dropdown option, then we need a way to show the then appearing "blog list" page, which needs to be accessible. I don't have in mind a way to deal with it better than instead using the approach described above, but if we can design a solution for it, we should be good. :)

**Comment by rickybanister** [comment]
So what should the sentence say?

**Comment by folletto** [comment]
Well, it probably could be better, but the marker has to mean "This is the front page", so either that verbose, or just "Front page".

**Comment by rickybanister** [comment]
Perhaps if the sentence mapped to the language used in selecting a page in the customizer it would help.

like 

:house: Blog Posts     [Your Latest Posts]
:house: About             [Static Front Page]

Here we'd rely on the house icon to designate the front page (as we already do) and we'd use the label from the customizer to help explain.

Another thing I realize, if you make a static page the posts page, we don't display any indicator in /pages. It's quite confusing. We should show a posts icon to the left of the posts page if it's not the front page perhaps.

**Comment by folletto** [comment]
> Here we'd rely on the house icon to designate the front page (as we already do) and we'd use the label from the customizer to help explain.

Ah that's a good point in reusing that text for now! :)

However I'm not sure... would you always show the text on the blog list? Can you do a text demo of a sample list like I did above of the various configurations?

> Another thing I realize, if you make a static page the posts page, we don't display any indicator in /pages. It's quite confusing. We should show a posts icon to the left of the posts page if it's not the front page perhaps.

I think that's up next in Matias' plan :)

**Comment by rickybanister** [comment]
I think I understand, here are some examples:

**Example 1**

:house: Blog Posts    `/`       [Your Latest Posts]
About                        `/about` 
Contact                     `/contact`

**Example 2**

:house: About            `/`      [Static Front Page]
:page_facing_up: My Journal     `/journal`      [Your Latest Posts]
Contact Me                    `/contact`
Biography                     `/bio`

**Comment by folletto** [comment]
Looks good to me! :100:

**Comment by mtias** [comment]
@rickybanister @folletto @drw158 here's latest version:

image

**Comment by folletto** [comment]
:+1:

**Comment by rickybanister** [comment]
Looks good to me!

Excited to see more happen to /pages.

**Pull request merged**
