### PR TITLE
Site Importer: Auto start when coming up from Signup

### PR DESCRIPTION
**Pull request by bisko**
This PR is part of series to extract more focused changes out of #32449 

This diff adds the following:
* A temporary "loading" screen similar to the in-progress screens for imports while the import section properly loads.
* The ability to auto-start the import with a query parameter (`autoStartSiteImport`) if there's a need.

At the start the imports won't auto start, unless specified with the query parameter mentioned above in order to preserve the current behavior and we work out proper design/flow.

# To test Signup flow - autostart
* Checkout branch (won't work on Calypso.live as it requires code edit)
* Go to `client/signup/config/flows-pure.js` -> function `importDestination`
* Change `autoStartSiteImport` to `1` 
* Build Calypso
* Go to Create New site on the local Calypso instance
* Choose `Already have a site?` option
* Follow the flow and try with a Wix and a GoDaddy site
* Finish signup
* Make sure the import auto starts and completes

# To test Signup flow - no autostart
* Checkout branch or use Calypso.live link
* Go to Create New site
* Choose `Already have a site?` option
* Follow the flow and try with a Wix and a GoDaddy site
* Finish signup
* Make sure the import DOES NOT auto start

# To test normal Import flow

* Checkout branch or use Calypso.live link
* Go to Imports
* Choose Wix
* Enter a site URL
* Continue through the Preview step
* Make sure the import auto progresses after clicking Next on the Preview screen
* Make sure there are no JS errors in the Developer console.
* Repeat for a GoDaddy site

### CODE REVIEW

**Comment by andfinally** [comment]
I'm not getting the spinner stuck state I came up against yesterday... I did experience a tangled state with my first test on local, which seemed like issues we've previously seen.

* Started import from preview.
* Got the spinner.
* The preview came back.
* Tried to start import from preview - got "Simultaneous imports are not permitted" error.
* Logstash confirmed an import session had started.
* Refreshing imports page showed no import active.
* Tried a second time - import completed normally.

It feels like some state from a previous import hangs around. We can look at that separately.

After that first glitch my imports on local and calypso.live proceeded like they do on prod. I'm not seeing the `FromSignupLandingPane` loading screen though - the import goes from preview to spinner to progress bar to finish.

**Comment by andfinally** [comment]
Oh wow, this auto-starts import from the signup flow too! When I begin at `/start` and follow the signup flow with pre-existing Wix and GoDaddy sites the flow skips the preview and goes straight to import.

I was a bit confused by the titles in the test plan - my idea of signup flow has been going to `/start` URLs, but this is clicking "Add new site" in the sidebar.

Tests work as predicted, except that in "To test Signup flow - no autostart", I'm finding the import autostarts even when `autoStartSiteImport` is `0`.

Now I'll have another look at the code!

(Looks like we need a rebase.)

**Comment by andfinally** [comment]
I've just tried the signup flow entering the URL of a self-hosted WP site in the URL form, and the flow ends up on the importer `http://calypso.localhost:3000/import/humbleself09809889876544444.wordpress.com?signup=1&autoStartSiteImport=0`, without showing the file upload input.

image

**Comment by bisko** [comment]
Seems the auto starting and the broken file uploads are two separate issues. 

The auto starting issue should be fixed with 56e5e6b .

The broken file uploads is due to a broken state in their instantiations. The file uploader component doesn't understand the `FROM_SIGNUP` state and gets into this half-broken behavior.

**Comment by andfinally** [comment]
Sorry, the import still seems to be auto-starting for me with `autoStartSiteImport` at `0` and also in the `calypso.live` signup flow. 😔 This is what I'm doing:

* Go to `/start`.
* Click "Already have a website? Import your content here."
* Enter URL of Wix site.
* Click "Continue" button on import preview.
* Choose site in domains step.
* Choose free plan in plans step.
* Get "Awesome" page, then Wix importer with import running.

**Comment by bisko** [comment]
With the latest update in fd57022 file based importers should work properly again.

@andfinally I just tested this on the Calypso.live version and it is working as intended - when you enter a Wix site, you land on the Site Preview step in the import (after a quick loader screen) and you have to manually click the button to continue the import.

It's possible Calypso.live was caching something. Can you check again? 

Both cases - Site Importer and File based importers should work as expected.

I noticed another issue - when you start the Site Import after the preview Calypso crashes with a ` Error: Dispatch.dispatch(...): Cannot dispatch in the middle of a dispatch.` error, which wasn't happening before. I'm suspecting stale state, but I'm going to give it another pass tomorrow, to figure out where this nested dispatch is happening. 

@jonathansadowski the PR is rebased to the latest master. Can you check again if it's still causing issues with the preview step?

**Comment by bisko** [comment]
9fa526c should stabilize the Site Importer flow and it should properly auto start the import if the flag is present and set to truthy value.

Just noticed that the File based uploaders are broken in this patch, guessing due to the state not being properly set. The file upload zone is visible and you can choose a file, but nothing happens if you choose the file.

**Comment by bisko** [comment]
> @bisko Is this still the case? It is unclear whether or not this is ready for re-review.

Yes, it's still the case, hence the status being back to `In Progress`. There is still some weirdness in how the import component state is updated that prevents the state to properly update.

I think it's a leftover from how we used Flux here and how it was ported to Redux.

It works properly when going through the normal flow, but we are missing something key when we come from Signup that prevents the normal state flow. 

Still investigating how to fix it.

**Comment by bisko** [comment]
Closing this as we're not actively working on it at the moment.

**Pull request closed without merging**
