### PR TITLE
Selectors: Add getMenusUrl() selector, use in Sidebar

### PR DESCRIPTION
**Pull request by ockham**
I'm moving this to a separate function since I also want to use it from #13082.

To test:
* Check the different scenarios that are also covered by the unit test:
  * No site selected: 'Menus' item shouldn't show up in sidebar
  * Jetpack site: 'Menus' item should point directly to JP site's Customizer
  * User with unverified email: 'Menus' item should point to top-level Customizer (not the Menus panel)
  * Regular user: 'Menus' item should point to Customizer's Menus panel
    * Also try regular user with only one site

### CODE REVIEW

**Comment by ockham** [comment]
Hmm, multi-site mode shows the item. One sec...

**Comment by ockham** [comment]
Waiting for a PR that introduces a  `getSites()` selector so I can add back a check whether a user has exactly one site.

**Comment by ockham** [comment]
Solved using `getCurrentUser( state ).site_count`. Should work now.

**Comment by kwight** [comment]
An unverified email user is getting a link of `https://kwight1231.wordpress.com/wp-admin/customize.php?url=https%3A%2F%2Fkwight1231.wordpress.com%2F&autofocus%5Bpanel%5D=nav_menus`, which should be just `https://wordpress.com/customize/<site>`, on their first view of the sidebar. After clicking around, I noticed it was corrected at some point (now pointing to `https://wordpress.com/customize/kwight1231.wordpress.com`). After verifying the address, the link is correct too. Otherwise, looks good!

**Comment by mcsf** [comment]
> Waiting for a PR that introduces a `getSites()` selector so I can add back a check whether a user has exactly one site.

#13111 !

**Comment by mcsf** [comment]
> No site selected: 'Menus' item shouldn't show up in sidebar

Steps:
1. Load Calypso at `/`
2. Go to My Sites
3. Primary/last site is selected. Confirmed that Menus item points to `/customize/menus/:slug`
4. Switch site to All Sites
5. **Unexpected:** Menus item still pointing to `/customize/menus/:slug` from 3).

Steps:
1. Load Calypso at `/stats/day`
2. **Unexpected:** Menus item pointing to `/customize/menus/null`
3. After a few seconds, item points to `/customize/menus/:slug`

**Comment by ockham** [comment]
@mcsf _Zut alors!_ I had fixed that last night, but on the wrong branch :man_facepalming: Should be fixed now.

**Comment by ockham** [comment]
@kwight I _think_ due to the redirects that happen after signup, the bug you're seeing is actually in production. In any case, it's present when I start from production. OTOH, landing directly on `calypso.localhost:3000` produces the right menus URL for logged-out users for me.

Considering merging soon given the above :slightly_smiling_face:

**Pull request merged**
