### PR TITLE
Add duplicate backup notice to composite checkout

### PR DESCRIPTION
**Pull request by monsieur-z**
#### Changes proposed in this Pull Request

This PR introduces the duplicate backup notices implemented in the current checkout to the composite checkout.

#### Implementation notes

Depends on #44181 

Somehow, `getSitePurchases` seems to return an empty array when composite checkout is enabled, which leads the links in the notice to point to `/me/purchases/` instead of the more specific `/me/purchases/:site-slug/:purchase-id/`. It's good enough for this PR.

#### Testing instructions

- Download the PR
- Follow the instructions in  #44181
- Make sure to activate the composite checkout (append `?flags=composite-checkout-force` to the URL)

#### Screenshots

**Mockup**
Screen Shot 2020-07-16 at 3 00 50 PM

**Implementation**
Screen Shot 2020-07-16 at 3 14 28 PM

### CODE REVIEW

**Comment by sirbrillig** [comment]
The code here looks fine, although it makes me wonder: why embed a notice directly into the UI rather than use the notices system to just display a normal notice?

> Somehow, getSitePurchases seems to return an empty array when composite checkout is enabled, which leads the links in the notice to point to /me/purchases/ instead of the more specific /me/purchases/:site-slug/:purchase-id/. It's good enough for this PR.

That's interesting... I suppose this means that there's a query component missing for the purchases state in redux in composite checkout. If we can figure out what that is, it should be easy to add it in [with the other query components](https://github.com/Automattic/wp-calypso/blob/c133301bb30cf3c230a985636c2e35ca423aa2c7/client/my-sites/checkout/composite-checkout/composite-checkout.js#L569). I'm guessing it's either `QueryUserPurchases` or `QuerySitePurchases`.

**Comment by monsieur-z** [comment]
> The code here looks fine, although it makes me wonder: why embed a notice directly into the UI rather than use the notices system to just display a normal notice (for example, as we do in checkout)?

I believe the rationale from the design team was that it would be harder to ignore inside the box.

> I suppose this means that there's a query component missing for the purchases state in redux in composite checkout

Thanks for the tip! I'll take a look at it.

**Review by wp-desktop — CHANGES_REQUESTED** [review]
WordPress Desktop CI Failure for job "wp-desktop-mac".

@monsieur-z please inspect this job's build steps for breaking changes at [this link](https://circleci.com/gh/Automattic/wp-calypso/820352). For temporal failures, you may try to "Rerun Workflow from Failed".

Please also ensure this branch is rebased off latest Calypso.

**Comment by monsieur-z** [comment]
> I'm guessing it's either `QueryUserPurchases` or `QuerySitePurchases`.

Your hunch was good @sirbrillig. I addressed that in https://github.com/Automattic/wp-calypso/pull/44564.

**Pull request merged**
