### PR TITLE
chore(framework): Switch to file refs for packages

### PR DESCRIPTION
**Pull request by blowery**
#### Changes proposed in this Pull Request

* Switch to `file:` refs for internal packages
* Stop using `lerna bootstrap` for `npm ci`
* Ditch the package level locks, they're now part of the main lock
* Update circle and docker builds

#### Testing instructions

* `npm ci` in the main repo should work
* `npm start` should work
* `npm run build-docker` should build a docker instance
* Tests should pass
* Validate that this doesn't bloat the build bundle with duplicated dependencies

### CODE REVIEW

**Comment by blowery** [comment]
This is also going to update all of our transitive deps to the most recent available version.  That could be ... bad.

**Comment by jsnajdr** [comment]
> This is also going to update all of our transitive deps to the most recent available version.

I don't understand. That typically happens when regenerating the lockfile from scratch, because transitive deps are not pinned. This PR doesn't have any such change in the lockfile though.

**Comment by blowery** [comment]
This will need a companion PR in wp-desktop to update the scripts there.

**Comment by blowery** [comment]
> I don't understand. That typically happens when regenerating the lockfile from scratch, because transitive deps are not pinned. This PR doesn't have any such change in the lockfile though.

@jsnajdr I rebuilt the lockfile from scratch :)

We may be able to get away with switching the refs to `file:` and then running `npm install` to affect fewer things. I'll give that a shot.

**Comment by blowery** [comment]
> We may be able to get away with switching the refs to `file:` and then running `npm install` to affect fewer things. I'll give that a shot.

Worked! Much nicer diff now.

after updating the refs, I just ran
```
npm install
npm dedupe
```

**Review by jsnajdr — APPROVED** [review]
`npm-shrinkwrap.json` got switched from tabs to spaces. Other than that, the patch is flawless :+1:

**Comment by blowery** [comment]
@jsnajdr i think you might be on an old patch. the current one (726 changes) seems to maintain tabs.

**Comment by jsnajdr** [comment]
I had and have the latest version of the branch, and still get spaces. Node 10.15.0, NPM 6.5.0.

**Pull request merged**
