### PR TITLE
Purchases: Make renew buttons use checkout URL rather than addItems

### LINKED ISSUE #40260: Cart race condition when adding renewals
If I click to renew a product, I sometimes get redirected to the plans page.

I believe what's happening is that the "renew" button is adding the product to the cart (via the cart synchronizer) and then redirecting to checkout; checkout then loads the cart from the endpoint, but the cart synchronizer hasn't finished sending the updated cart to the endpoint yet, so the cart endpoint says it is empty. When composite checkout sees that the cart is empty, it redirects to the plans page, and then the cart synchronizer completes and the cart now contains the renewal.

### PR DESCRIPTION
**Pull request by sirbrillig**
When pressing the "renew" buttons on products in the purchases section
of Calypso, the intended action is to add the renewal product to the
cart, and then redirect to the checkout pages.

However, these two actions can cause race conditions since the redirect
does not wait for the cart modification to be complete. (Nor can it, in
any easy way, since modifying the cart is an async dispatched action
with no response.)

This commit removes the code that adds the product to the cart and
instead modifies the redirect URL so that it includes the product to be
renewed, thus allowing checkout itself to add the product to the cart
while it loads.

Fixes #40260 

#### Testing instructions

We'll need to test every type of product that can be renewed (at least, those that renew via the `handleRenewNowClick` function) and make sure that after clicking the renew button, the product ends up in the cart correctly.

Screen Shot 2020-03-18 at 7 16 51 PM

Here's the ones I could find:

- Plan
- Domain registration
- Domain mapping
- Google Apps
- Site Redirect
- No Ads
- Custom Design
- Video Press
- Unlimited Space
- Unlimited Themes
- Space Upgrade

### CODE REVIEW

**Comment by fditrapani** [comment]
I tried this from the following locations and still got taken to the plans page:

- Sidebar nudge for expired domain. Link copied reads: `checkout/domain_map:filippodt.blog/renew/7370000/fditrapani.wpcomstaging.com`. This doesn't work in production either.
- Renewed a domain from `/domains/manage/fdi-trapani.com/edit/fditrapani.wpcomstaging.com`. This takes me to `/me/purchases` which is different than production which takes me to the plans page with the product in the cart. In this branch, if I make my way back to the plans page, the product is in the cart. 
- Renewed plan from manage purchase screen. Takes me to `/me/purchases` which is different than production which takes me to the plans page with the product in the cart. In this branch, if I make my way back to the plans page, the product is in the cart. 

Unfortunately I'm not seeing anything in my console.

**Comment by sirbrillig** [comment]
> Sidebar nudge for expired domain. Link copied reads: checkout/domain_map:filippodt.blog/renew/7370000/fditrapani.wpcomstaging.com. This doesn't work in production either.

Could you take a screenshot of this button and the context around it? When you say "this doesn't work in production either", do you mean the nudge goes to the same link in production and also doesn't work? If it's something broken in production we could create an issue for it but it shouldn't block this PR because the cause is likely unrelated.

> Renewed a domain from /domains/manage/fdi-trapani.com/edit/fditrapani.wpcomstaging.com. This takes me to /me/purchases which is different than production which takes me to the plans page with the product in the cart. In this branch, if I make my way back to the plans page, the product is in the cart.

Hm... renewing a domain _registration_ from that page works for me. I had a different broken experience: when I renewed a domain _mapping_ from there, I was taken to checkout with the _plan_ in the cart (rather than the domain mapping), but that's how it works in production too, so I don't think that particular issue is a blocker. I can't find a path that would lead to the purchases page... I wonder what's going on there?

I added a debug line to this PR just now which will log everything that the function knows when generating a link; can you try the failures you encountered again and see what the debug line says? To see it, enter `localStorage.setItem('debug', 'calypso:purchases')` and reload the page before clicking the button. You'll see four pieces of data:

1. The full product object passed to the function; this is what the function is trying to renew. If this is incorrect, the bug has nothing to do with this PR.
2. The site slug.
3. The shopping-cart-formatted item we're trying to renew. This is what would have been passed to the cart store. It should match the full product in step 1, but it's a lot simpler. If this is incorrect, the bug has nothing to do with this PR.
4. The URL we're about to redirect to. This is the only thing changed by this PR; if it goes to an invalid URL (that is, if you copy/paste that URL manually and it doesn't go to the cart with the appropriate product in the cart), then it's a bug in this PR.

**Comment by fditrapani** [comment]
> Could you take a screenshot of this button and the context around it? When you say "this doesn't work in production either", do you mean the nudge goes to the same link in production and also doesn't work? If it's something broken in production we could create an issue for it but it shouldn't block this PR because the cause is likely unrelated.


sorry, I should have shared a screenshot. Here it is:

image

The notice appears when you have a domain that's expiring or already expired. In production it points here: "/checkout/domain_map:filippodt.blog/renew/7370000/fditrapani.wpcomstaging.com" and clicking on it takes you right to the composite checkout. It seems to be working in this PR now too.


> Hm... renewing a domain registration from that page works for me.

That's weird, it's still behaving weird for me. It might be a calypso.live issue and the way I'm enabling the flags. This is what I see after pressing the renew button:

image

>  I had a different broken experience: when I renewed a domain mapping from there, I was taken to checkout with the plan in the cart (rather than the domain mapping), but that's how it works in production too, so I don't think that particular issue is a blocker. I can't find a path that would lead to the purchases page... I wonder what's going on there?

The behaviour with mapping works right because mapping is free with plans. When you renew for mapping, it renews the plan. I can see how this might be confusing now and we should consider removing the renew button.

**Comment by sirbrillig** [comment]
> That's weird, it's still behaving weird for me. It might be a calypso.live issue and the way I'm enabling the flags. This is what I see after pressing the renew button:

Thank you for the screenshot, it was _very_ helpful! It still works for me, even in calypso.live (no flags), but I'm sure there's any number of differences between our accounts. We probably need a third tester to see if one of us is doing something differently. @michaeldcain ? If we can't figure it out, we can try a screen share to see what might be going on.

**Comment by fditrapani** [comment]
Yeah, good call. Sounds good!

**Comment by michaeldcain** [comment]
> We probably need a third tester to see if one of us is doing something differently. @michaeldcain ? If we can't figure it out, we can try a screen share to see what might be going on.

I haven't tested it yet this morning, but yesterday the renew button worked for me correctly the first time I pressed it, but then failed on every subsequent click (from the same and different areas of Calypso). I can test again today, but I think a screen share might be required.

**Comment by sirbrillig** [comment]
So one point of confusion was: this is a modification of existing checkout behavior; this does not (and will not) work with composite checkout. It should be fine in production because composite checkout is not used when adding renewal items, but if you use the `composite-checkout-force` flag, it definitely won't work.

For the record, @fditrapani is still seeing one case where the renewal button does not work correctly. It generates what looks like the correct URL, but (old) checkout for some reason uses that URL to redirect to `/me/purchases`. This does not happen for anyone else so far so we're trying to debug what might be going on.

**Comment by fditrapani** [comment]
This is what I'm seeing in the console after clicking on the renew button for a domain:

image

**Comment by sirbrillig** [comment]
That's very strange, as it doesn't seem to even be reaching checkout. I added more logging lines to see where you're being routed. Try it with full debugging on calypso: `localStorage.setItem('debug', 'calypso:*')`

**Comment by fditrapani** [comment]
Sure thing. Here's a file I exported from the console after pressing the renew button: https://cloudup.com/cut2CjRIaOp

**Comment by sirbrillig** [comment]
Thank you. That was very helpful. So what the logs show is happening is that you visit the checkout URL to add the plan, then _something_ redirects from the correct URL `.../renew/7370000/fditrapani.wordpress.com` to `.../renew/7370000?site=fditrapani.wordpress.com`. Since that URL is invalid, the router redirects to `/me/purchases`.

I'm looking to see what code might be performing that `site=` redirect.

**Comment by fditrapani** [comment]
Nice! glad to hear it was helpful.

**Comment by sirbrillig** [comment]
I found one place that might be performing the redirect in a controller. Could you try to reproduce the issue again? Specifically now we are just looking for logs with the `calypso:my-sites-controller` prefix.

**Comment by sirbrillig** [comment]
I added some extra debugging so that if I'm right about where the redirect is happening we'll get a little more data about why your site is not found.

**Comment by fditrapani** [comment]
I tried it again. Here's another log: https://cloudup.com/cVXnsEnYVyi

**Pull request merged**
