### PR TITLE
Fix/30610 contact info p

### LINKED ISSUE #30609: Contact Info: Textareas in the editor
When editing on this block on WordPress.com, the fields look like textareas. It's fine locally....

screenshot 2019-02-06 at 11 39 00

### PR DESCRIPTION
**Pull request by enejb**
#### Changes proposed in this Pull Request
* Fixes the calypso block editor styling
* Removed the empty address div then no address is added.

Before:
See #30609

After:
screen shot 2019-02-11 at 2 53 49 pm

#### Testing instructions
Navigate to  https://calypso.live/?branch=fix/30610-contact-info-p&flags=-calypsoify/iframe
and then go the block editor using the feature flag. 
Add the contact info block. Notice that it looks as expected.

Fixes #30609 and Removes the empty address div.

### CODE REVIEW

**Comment by scruffian** [comment]
Code looks good. Not sure how we can test it really as it never happens locally. Maybe just merge and test in staging?

**Comment by scruffian** [comment]
Closed by mistake!

**Comment by enejb** [comment]
Do you mind testing it on the calypso side. Does it still work as expected?

**Comment by scruffian** [comment]
Yeah I tested locally and it works fine; no change from before :)

**Pull request merged**
