### PR TITLE
Render empty layout structure during initialization.

### PR DESCRIPTION
**Pull request by mtias**
Example:

screen shot 2017-01-20 at 15 14 16

### CODE REVIEW

**Comment by ehg** [comment]
Noting here that we could add some conditionals for pages with no sidebar here.

**Comment by mtias** [comment]
From a design standpoint, if user is logged in, we could render the menu items in a disabled state? cc @folletto

**Comment by mtias** [comment]
Something like:

image

**Comment by folletto** [comment]
It would work. My only question about that: we pluralize "My Sites" when there are more than one, and/or translate that. Are we already able to do that in pre-rendering, or we need to avoid text so we can just show a rectangle?

**Comment by mtias** [comment]
Yes, that's why I just left it blue.

**Comment by mtias** [comment]
Yes. The flash of a sidebar is for the root URL?

**Comment by ehg** [comment]
> Yes. The flash of a sidebar is for the root URL?
Yep.

Also, for desktop, there's a `desktop.jade`.

**Comment by mcsf** [comment]
@mtias could we extend this to be aware of and render for the following? In order of importance:
- My Sites (currently)
- Reader (entry point for `wordpress.com/`)
- Editor
- Sidebar-less sections

**Comment by mtias** [comment]
@mcsf it should already be rendering for all those. There's a specific one for the editor, because layout is different, but all the rest should be handled by hasSidebar.

**Comment by mcsf** [comment]
@mtias oh, the Editor one is cool, nice. However, in practice, the behavior is weird for the Reader, since there's a jump from the pale background to the Reader white.

**Comment by mtias** [comment]
Yes, I'm not sure how the reader is doing it. If it used the `is-group-reader` to achieve ti would work.

**Comment by mcsf** [comment]
^ Tentatively pinging @bluefuton

**Comment by blowery** [comment]
> Yes, I'm not sure how the reader is doing it. If it used the is-group-reader to achieve it would work.

`is-reader-page` up on the body element. I think we did it this way because of the refresh and something about specificity... Either way, it appears that moving it to the `.layout` element should work just fine. And we can drop `reader-main` too.

cc @bluefuton

**Comment by blowery** [comment]
Spinning up a PR to move to `.is-group-reader`

**Pull request merged**
