### PR TITLE
Hosting Command Palette: Update the highlighted color to match the accent color of the dashboard color scheme

### PR DESCRIPTION
**Pull request by katinthehatsite**
Related to https://github.com/Automattic/dotcom-forge/issues/4496

## Proposed Changes

This PR changes the color of the items on the command palette available on the `/sites` page to match the color of the **Dashboard color scheme** that is set on https://wordpress.com/me/account

Screenshot 2023-11-15 at 11 16 50 AM

## Testing Instructions

* Pull changes from this PR or navigate to Calypso live link
* Navigate to `/sites` page
* Press `cmd + k` on Mac or `ctr + k` on Windows
* Observe that the command palette color matches the accent color of the dashboard theme and is consistent with the dashboard color scheme selected:

Screenshot 2023-11-15 at 11 16 20 AM

* Navigate to `https://wordpress.com/me/account`
* Select a couple of different themes and confirm the command palette colors are consistent with the theme selected and with colors in the Gutenberg command palette:

Screenshot 2023-11-15 at 11 16 50 AM

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

**Review by sejas — COMMENTED** [review]
Thanks for this PR and your investigation about matching the hover color between the command palette on Calypso and Gutenberg.

I tested different pages holistically and the command palette on all the 17 themes, and here are the results.
Themes: `Default`, `Aquatic`, `Blue`, `Classic Blue`, `Classic Bright`, `Coffee`, `Contrast`, `Ectoplasm`, `Light`, `Midnight`, `Modern`, `Nightfall`, `Ocean`, `Powder Snow`, `Sakura`, `Sunrise`, `Sunset`.
I confirm the color between the Gutenberg command palette and the Calypso version match the hover color, except for the `Classic Bright` theme. Is it something we can fix?



|  |  |  |  |
| ---------- | --------- | ---------- | ---------- |
| **Default:** | **Aquatic:** | **Blue:** | **Classic Blue:** |
| Default | Aquatic | Blue | Classic Blue |
| ❌☠️ **Classic Bright:** | **Coffee:** | **Contrast:** | **Ectoplasm:** |
| Classic Bright | Coffee | Contrast | Ectoplasm |
| **Light:** | **Midnight:** | **Modern:** | **Nightfall:** |
| Light | Midnight |  Modern | Nightfall |
| **Ocean:** | **Powder Snow:** | **Sakura:** | **Sunrise:** |
| Ocean | Powder Snow | Sakura | Sunrise |
| **Sunset:** |  |  |  |
| Sunset |  |  |  |

**Comment by katinthehatsite** [comment]
Hi @sejas  - thanks for the detailed review. I looked through this is what I am seeing:

* firstly, there is no `_classic-bright.scss` file that [I could find anywhere](https://github.com/Automattic/wp-calypso/tree/trunk/packages/calypso-color-schemes/src/shared/color-schemes)
* then, I looked through the CSS and noticed that we are applying default theme when Classic Bright is activated:

Screenshot 2023-11-20 at 4 12 34 PM

* It seems that when you are applying Classic Bright, we are activating the default instead. I am also not seeing any visual difference between the Classic Bright and the Default themes in terms of colors...

**Classic Bright**: 

Classic Bright is supposed to have a blue masterbar but it does not as you can see on the screenshot below:

Screenshot 2023-11-21 at 9 57 43 AM

**Default**:

Screenshot 2023-11-21 at 9 57 58 AM

This makes me wonder why the Classic Bright is still available in the choices of themes and whether we should remove it completely if we are activating the default theme instead when this option is selected?

**Comment by sejas** [comment]
> This makes me wonder why the Classic Bright is still available in the choices of themes and whether we should remove it completely if we are activating the default theme instead when this option is selected?

This is a great point that I didn't think about it, and it make a lot of sense.
Let me try to investigate what happened with that "unusable" theme.

**Comment by katinthehatsite** [comment]
@sejas I researched it a bit and this post specifying that the plan was to remove it: p9Jlb4-4qv-p2ee 
I see that there was a mention of editing classic bright files but I don't see these files anymore. I am wondering if whoever removed it might have forgotten to handle the removal from the choice selection or if it was done intentionally to leave the Classic Bright choice in there.

**Comment by sejas** [comment]
@katinthehatsite , you are awesome.

Let's skip the customization for the Classic Bright since it's a different scope. I'll ask on slack and create a backlog issue to remove the Classic Bright theme separately.

My understanding, after my investigation, is that the Classic Bright become Classic blue and the option was left there. Eventually the classic bright and classic dark converged becoming the default theme.

**Some findings**

**2018**
The classic bright become classic blue

https://github.com/Automattic/wp-calypso/pull/29449

**2019**

```
once we replace the current default theme with Classic Bright, we can remove these and increase consistency by using the sidebar colors instead
```

https://github.com/Automattic/wp-calypso/pull/30526/files#diff-58c47641d87eb48ee2f6e0e4cf3220dff93d7fe363aa6d84af8102020d25bba9R461

The colors were divided into different files:

https://github.com/Automattic/wp-calypso/commit/05655fee9a0372f71a90ebf66b47358a6b167130#diff-afe17d9a85c71aeb4f221c23abd639fc693457b2f518071a1830ac019da3ed3eR121-R123

The Readme `docs/color.md` was [updated](https://github.com/Automattic/wp-calypso/commit/b8539eff34080f0f1efea4f3a1888fa90b51fd27) and it's still [saying the same](https://github.com/Automattic/wp-calypso/blob/116ba36bccb7fbcadd9cd432b52331ca825c5663/docs/color.md#adding-a-new-scheme) nowadays:

```
New color schemes overwrite the theme properties defined by the default theme called Classic Bright. Not every single property has to be redefined by a new scheme, but please remember to include the -rgb counterpart for each overwritten theme property.
```

**2020**

- https://github.com/Automattic/wp-calypso/pull/49710

**2021**

The default theme option was added and replaced the Classic Dark

https://github.com/Automattic/wp-calypso/pull/53554

**2022**

There was an attempt to replace all the background colors in themes for Nav unification.

- https://github.com/Automattic/wp-calypso/pull/62436

p4TIVU-a5z-p2

**Review by sejas — APPROVED** [review]
Great work Kat!

**Comment by katinthehatsite** [comment]
Sounds good @sejas - I will go ahead with merging this. Feel free to assign the backlog issue to me.

**Comment by sejas** [comment]
For now I started the conversation here p1700576123536129-slack-C7YPUHBB2

**Comment by sejas** [comment]
- I reported the issue we found on the Classic Bright theme https://github.com/Automattic/dotcom-forge/issues/4581  . An old bug not related to this PR.

**Comment by Aurorum** [comment]
Hey @katinthehatsite 👋 I'm currently also going down the "what happened to Classic Bright" rabbit-hole, but I stumbled across the colour variable here. I was a little confused by this PR though.

I'm sure that I'm almost certainly missing something, but was there no reason why the colour schemes couldn't rely on `--color-accent` rather than adding a new `--wp-admin-theme-color` variable? Are there some schemes for which it's different? 

Thanks! :)

**Comment by katinthehatsite** [comment]
Hi @Aurorum  - thanks for the question. I don't recollect the details exactly but if I remember correctly, the palette was using the `--wp-admin-theme-color` as a variable (I think that was coming from one of the dependencies e.g. `@wordpress/components` that was used to build command palette) and it was the most straightforward way I was able to find to change the color of the command palette to be consistent with dashboard color scheme. 

It does not mean though that it is the only way 😅 - if you have any suggestions, I would be happy to look into them.

**Comment by Aurorum** [comment]
Thanks @katinthehatsite! Makes total sense if that variable is coming from a Core component :) No worries at all, it was literally just me being curious after re-adding the variables for Classic Bright.

**Pull request merged**
