### PR TITLE
Revert "Revert "Add instructional 'Fonts' section to customizer when fonts are only modifiable from 'Global Styles' (#54191)" (#54658)"

### PR DESCRIPTION
**Pull request by DanielSmithMichigan**
This reintroduces pull request [#54191](https://github.com/Automattic/wp-calypso/pull/54191)

This was originally reverted in order to fix linting errors.

#### Simple Site Testing Instructions

1. Host a calypso app locally: `cd wp-calypso; yarn && yarn start`
2. Host the editing toolkit plugin as well. `cd wp-calypso/apps/editing-toolkit; yarn dev --sync`
3. Make sure your hosts file is pointing wordpress.com and public-api.wordpress.com to your sandbox, as well as the specific site you're about to test with.
4. Make sure you have an active SSH connection to your sandbox
4. Perform all the following steps using your locally hosted calypso app.
3. Activate the theme: twenty-twenty one
4. Go to customizer
5. Expand the 'Fonts' section
7. Click the link which says 'Click here to open the Block Editor and change your fonts.'
8. It should open your homepage and expand the global styles section

#### Atomic Testing Instructions

1. Create an atomic site
2. Make sure your hosts file is pointing to production servers
3. Download the zipped version of the editing toolkit plugin from the build for this pull request
4. Install/activate this plugin (You may need to deactivate the existing editing toolkit plugin first)
3. Activate twenty twenty-one
4. Go to customizer
5. Expand the 'Fonts' section
7. Click the link which says 'Click here to open the Block Editor and change your fonts.'
8. It should open your homepage in the block editor (the global styles sidebar may or may not be open)
1. `?openSidebar=globalStyles` should be present in your current URL

### CODE REVIEW

**Comment by DanielSmithMichigan** [comment]
Confirmed this patch will be accepted by phabricator: D64209-code

**Comment by sixhours** [comment]
👋 This is working on my local simple site, but I can't get the Fonts tab to show up on my ephemeral Atomic site after downloading the artifact and activating it:

Screen Shot 2021-07-16 at 4 21 10 PM

Screen Shot 2021-07-16 at 4 20 53 PM

I suspect this is not your PR but my missing something about the testing instructions. Any ideas?

**Review by sixhours — APPROVED** [review]
Tested on a regular `*.wpcomstaging.com` site and it worked fine :) I would probably wait 'til Monday to re-deploy this, but I think it's ready to go!

**Comment by DanielSmithMichigan** [comment]
> Tested on a regular `*.wpcomstaging.com` site and it worked fine :) I would probably wait 'til Monday to re-deploy this, but I think it's ready to go!

Thank you! I will wait until Monday.

**Pull request merged**
