### PR TITLE
Stats: Apply new styling to the WordAds earnings table

### LINKED ISSUE #72676: Stats: Restyle the earnings history table in the Ads page
# Development

Please reuse the work done for [Annual highlight table](https://github.com/Automattic/wp-calypso/issues/70608) and #71761.

# Design
|Before|After|
|-|-|
|Image|Image|

### PR DESCRIPTION
**Pull request by jsnmoon**
Fixes #72676.

## Proposed Changes

Before|After
-|-
image|image
image|image

- Applies new styling to the earnings table on the WordAds Stats and WordAds Earn dashboards.
- Moves `HighlightCardSimple` into the component package.
- Removes code from the `WordAdsEarnings` made redundant by the WordAds highlights section.

## Testing Instructions

* Spin up this live branch and ensure that the new styling has been applied to these pages:
    * Stats -> Ads
    * Tools → Earn → View ad dashboard

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

**Review by kangzj — APPROVED** [review]
It works well and looks good 👍

**Review by a8ck3n — COMMENTED** [review]
Just wanted to note that updating this table also updates the styling under **Tools → Earn → View ad dashboard**. Probably not a big deal but the header styling doesn't match up with the styling there.

I'm also seeing that the Earnings history H1 doesn't have any padding/margin on mobile so it isn't lining up with the other headers on the page.

**Comment by jsnmoon** [comment]
@a8ck3n: Thanks for the heads up, Kevin! I refactored our WordAds components and reused them in the WordAds dashboard in the Earn section.

**Review by kangzj — APPROVED** [review]
LGTM

**Review by kangzj — APPROVED** [review]

**Review by grzegorz-cp — APPROVED** [review]

**Pull request merged**
