### PR TITLE
Copy of #92835 that should generate desktop app artifacts in CI 

### PR DESCRIPTION
**Pull request by mokagio**
The CI configuration is such that if one wants a build for the Desktop app, they need certain branch names or tags. 

So, one way to get CI to build artifacts so we can verify the new icons introduced by #92835 by @matt-west is to have a branch starting with `desktop/`.

We also need a dedicated PR, because of the CircleCI configuration:

image

The build is currently running here https://app.circleci.com/pipelines/github/Automattic/wp-calypso/236710/workflows/6fdfc3f9-c125-407b-87ba-b5c65b7feab7

cc @wojtekn 

_Notice that we haven't shipped a WordPress.com Desktop version in almost a year. I wouldn't be surprised if something broke in CI in the meantime._

### CODE REVIEW

**Comment by matt-west** [comment]
@mokagio Thanks for letting me know! I’ll be sure to start branch names with `desktop/` in the future.

It seems the linux tests are still failing. I don't have CircleCI access to dig into it further, but looks like it's errs when building `wp-calypso@workspace`.

**Comment by mokagio** [comment]
> It seems the linux tests are still failing. [...] looks like it's errs when building `wp-calypso@workspace`.

Is this something you verified running locally @matt-west ?

The CI logs were as follow:

```
➤ YN0000: · Yarn 4.0.2
➤ YN0000: ┌ Resolution step
➤ YN0000: └ Completed in 0s 633ms
➤ YN0000: ┌ Fetch step
➤ YN0000: └ Completed in 1s 551ms
➤ YN0000: ┌ Link step
➤ YN0007: │ v8-profiler-next@npm:1.10.0 must be built because it never has been before or the last one failed
➤ YN0007: │ swiper@npm:8.4.5 must be built because it never has been before or the last one failed
➤ YN0007: │ dtrace-provider@npm:0.8.8 must be built because it never has been before or the last one failed
➤ YN0007: │ core-js-pure@npm:3.30.1 must be built because it never has been before or the last one failed
➤ YN0007: │ core-js@npm:2.6.11 must be built because it never has been before or the last one failed
➤ YN0007: │ core-js@npm:3.31.1 must be built because it never has been before or the last one failed
➤ YN0007: │ msw@npm:2.2.14 [5deca] must be built because it never has been before or the last one failed
➤ YN0007: │ playwright@npm:1.37.0 must be built because it never has been before or the last one failed
➤ YN0007: │ core-js-bundle@npm:3.16.2 must be built because it never has been before or the last one failed
➤ YN0007: │ flag-icon-css@npm:3.4.5 must be built because it never has been before or the last one failed
➤ YN0007: │ electron@npm:26.2.4 must be built because it never has been before or the last one failed
➤ YN0007: │ esbuild@npm:0.18.20 must be built because it never has been before or the last one failed
➤ YN0007: │ @sentry/cli@npm:1.77.1 must be built because it never has been before or the last one failed
➤ YN0007: │ lzma-native@npm:8.0.6 must be built because it never has been before or the last one failed
➤ YN0007: │ @swc/core@npm:1.3.96 [f6bbe] must be built because it never has been before or the last one failed
➤ YN0007: │ es5-ext@npm:0.10.63 must be built because it never has been before or the last one failed
➤ YN0000: │ v8-profiler-next@npm:1.10.0 STDOUT Writing config.gypi:
➤ YN0000: │ v8-profiler-next@npm:1.10.0 STDOUT {
➤ YN0000: │ v8-profiler-next@npm:1.10.0 STDOUT   "variables": {
➤ YN0000: │ v8-profiler-next@npm:1.10.0 STDOUT     "action_after_build": "true"
➤ YN0000: │ v8-profiler-next@npm:1.10.0 STDOUT   }
➤ YN0000: │ v8-profiler-next@npm:1.10.0 STDOUT }
➤ YN0000: │ v8-profiler-next@npm:1.10.0 STDOUT 
➤ YN0000: │ v8-profiler-next@npm:1.10.0 STDOUT [32;1mnode-pre-gyp install --fallback-to-build[0m
➤ YN0000: │ v8-profiler-next@npm:1.10.0 STDOUT 
➤ YN0000: │ dtrace-provider@npm:0.8.8 STDERR gyp info it worked if it ends with ok
➤ YN0000: │ dtrace-provider@npm:0.8.8 STDERR gyp info using node-gyp@8.2.0
➤ YN0000: │ dtrace-provider@npm:0.8.8 STDERR gyp info using node@20.8.1 | linux | x64
➤ YN0000: │ v8-profiler-next@npm:1.10.0 STDERR node-pre-gyp info it worked if it ends with ok
➤ YN0000: │ v8-profiler-next@npm:1.10.0 STDERR node-pre-gyp info using node-pre-gyp@1.0.11
➤ YN0000: │ v8-profiler-next@npm:1.10.0 STDERR node-pre-gyp info using node@20.8.1 | linux | x64
➤ YN0000: │ @sentry/cli@npm:1.77.1 STDERR [sentry-cli] Downloading from https://downloads.sentry-cdn.com/sentry-cli/1.77.1/sentry-cli-Linux-x86_64
➤ YN0000: │ dtrace-provider@npm:0.8.8 STDERR gyp info find Python using Python version 3.10.6 found at "/usr/bin/python3"
➤ YN0000: │ v8-profiler-next@npm:1.10.0 STDERR node-pre-gyp info check checked for "/home/circleci/wp-calypso/node_modules/v8-profiler-next/build/binding/Release/node-v115-linux-x64/profiler.node" (not found)
➤ YN0000: │ v8-profiler-next@npm:1.10.0 STDERR node-pre-gyp http GET https://github.com/hyj1991/v8-profiler-next/releases/download/v1.10.0/profiler-v1.10.0-node-v115-linux-x64.tar.gz
➤ YN0000: │ dtrace-provider@npm:0.8.8 STDERR gyp http GET https://nodejs.org/download/release/v20.8.1/node-v20.8.1-headers.tar.gz
➤ YN0000: │ playwright@npm:1.37.0 STDOUT Downloading Chromium 116.0.5845.82 (playwright build v1076)[2m from https://playwright.azureedge.net/builds/chromium/1076/chromium-linux.zip[22m
➤ YN0000: │ dtrace-provider@npm:0.8.8 STDERR gyp http 200 https://nodejs.org/download/release/v20.8.1/node-v20.8.1-headers.tar.gz
➤ YN0000: │ v8-profiler-next@npm:1.10.0 STDERR node-pre-gyp info install unpacking node-v115-linux-x64/profiler.node
➤ YN0000: │ v8-profiler-next@npm:1.10.0 STDERR node-pre-gyp info extracted file count: 1 
➤ YN0000: │ v8-profiler-next@npm:1.10.0 STDOUT [v8-profiler-next] Success: "/home/circleci/wp-calypso/node_modules/v8-profiler-next/build/binding/Release/node-v115-linux-x64/profiler.node" is installed via remote
➤ YN0000: │ v8-profiler-next@npm:1.10.0 STDERR node-pre-gyp info ok 
➤ YN0000: │ @sentry/cli@npm:1.77.1 STDERR [sentry-cli] Checksum validation passed.
➤ YN0000: │ playwright@npm:1.37.0 STDOUT |                                                                                |   0% of 148.1 Mb
➤ YN0000: │ playwright@npm:1.37.0 STDOUT |■■■■■■■■                                                                        |  10% of 148.1 Mb
➤ YN0000: │ playwright@npm:1.37.0 STDOUT |■■■■■■■■■■■■■■■■                                                                |  20% of 148.1 Mb
➤ YN0000: │ playwright@npm:1.37.0 STDOUT |■■■■■■■■■■■■■■■■■■■■■■■■                                                        |  30% of 148.1 Mb
➤ YN0000: │ playwright@npm:1.37.0 STDOUT |■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■                                                |  40% of 148.1 Mb
➤ YN0000: │ playwright@npm:1.37.0 STDOUT |■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■                                        |  50% of 148.1 Mb
➤ YN0000: │ playwright@npm:1.37.0 STDOUT |■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■                                |  60% of 148.1 Mb
➤ YN0000: │ playwright@npm:1.37.0 STDOUT |■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■                        |  70% of 148.1 Mb
➤ YN0000: │ playwright@npm:1.37.0 STDOUT |■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■                |  80% of 148.1 Mb
➤ YN0000: │ playwright@npm:1.37.0 STDOUT |■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■        |  90% of 148.1 Mb
➤ YN0000: │ playwright@npm:1.37.0 STDOUT |■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■| 100% of 148.1 Mb
➤ YN0000: │ dtrace-provider@npm:0.8.8 STDERR gyp http GET https://nodejs.org/download/release/v20.8.1/SHASUMS256.txt
➤ YN0000: │ dtrace-provider@npm:0.8.8 STDERR gyp http 200 https://nodejs.org/download/release/v20.8.1/SHASUMS256.txt
➤ YN0000: │ dtrace-provider@npm:0.8.8 STDERR gyp info spawn /usr/bin/python3
➤ YN0000: │ dtrace-provider@npm:0.8.8 STDERR gyp info spawn args [
➤ YN0000: │ dtrace-provider@npm:0.8.8 STDERR gyp info spawn args   '/home/circleci/wp-calypso/node_modules/node-gyp/gyp/gyp_main.py',
➤ YN0000: │ dtrace-provider@npm:0.8.8 STDERR gyp info spawn args   'binding.gyp',
➤ YN0000: │ dtrace-provider@npm:0.8.8 STDERR gyp info spawn args   '-f',
➤ YN0000: │ dtrace-provider@npm:0.8.8 STDERR gyp info spawn args   'make',
➤ YN0000: │ dtrace-provider@npm:0.8.8 STDERR gyp info spawn args   '-I',
➤ YN0000: │ dtrace-provider@npm:0.8.8 STDERR gyp info spawn args   '/home/circleci/wp-calypso/node_modules/dtrace-provider/build/config.gypi',
➤ YN0000: │ dtrace-provider@npm:0.8.8 STDERR gyp info spawn args   '-I',
➤ YN0000: │ dtrace-provider@npm:0.8.8 STDERR gyp info spawn args   '/home/circleci/wp-calypso/node_modules/node-gyp/addon.gypi',
➤ YN0000: │ dtrace-provider@npm:0.8.8 STDERR gyp info spawn args   '-I',
➤ YN0000: │ dtrace-provider@npm:0.8.8 STDERR gyp info spawn args   '/home/circleci/.cache/node-gyp/20.8.1/include/node/common.gypi',
➤ YN0000: │ dtrace-provider@npm:0.8.8 STDERR gyp info spawn args   '-Dlibrary=shared_library',
➤ YN0000: │ dtrace-provider@npm:0.8.8 STDERR gyp info spawn args   '-Dvisibility=default',
➤ YN0000: │ dtrace-provider@npm:0.8.8 STDERR gyp info spawn args   '-Dnode_root_dir=/home/circleci/.cache/node-gyp/20.8.1',
➤ YN0000: │ dtrace-provider@npm:0.8.8 STDERR gyp info spawn args   '-Dnode_gyp_dir=/home/circleci/wp-calypso/node_modules/node-gyp',
➤ YN0000: │ dtrace-provider@npm:0.8.8 STDERR gyp info spawn args   '-Dnode_lib_file=/home/circleci/.cache/node-gyp/20.8.1/<(target_arch)/node.lib',
➤ YN0000: │ dtrace-provider@npm:0.8.8 STDERR gyp info spawn args   '-Dmodule_root_dir=/home/circleci/wp-calypso/node_modules/dtrace-provider',
➤ YN0000: │ dtrace-provider@npm:0.8.8 STDERR gyp info spawn args   '-Dnode_engine=v8',
➤ YN0000: │ dtrace-provider@npm:0.8.8 STDERR gyp info spawn args   '--depth=.',
➤ YN0000: │ dtrace-provider@npm:0.8.8 STDERR gyp info spawn args   '--no-parallel',
➤ YN0000: │ dtrace-provider@npm:0.8.8 STDERR gyp info spawn args   '--generator-output',
➤ YN0000: │ dtrace-provider@npm:0.8.8 STDERR gyp info spawn args   'build',
➤ YN0000: │ dtrace-provider@npm:0.8.8 STDERR gyp info spawn args   '-Goutput_dir=.'
➤ YN0000: │ dtrace-provider@npm:0.8.8 STDERR gyp info spawn args ]
➤ YN0000: │ dtrace-provider@npm:0.8.8 STDERR gyp info spawn make
➤ YN0000: │ dtrace-provider@npm:0.8.8 STDERR gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
➤ YN0000: │ dtrace-provider@npm:0.8.8 STDOUT make: Entering directory '/home/circleci/wp-calypso/node_modules/dtrace-provider/build'
➤ YN0000: │ dtrace-provider@npm:0.8.8 STDOUT   TOUCH Release/obj.target/DTraceProviderStub.stamp
➤ YN0000: │ dtrace-provider@npm:0.8.8 STDOUT make: Leaving directory '/home/circleci/wp-calypso/node_modules/dtrace-provider/build'
➤ YN0000: │ dtrace-provider@npm:0.8.8 STDERR gyp info ok 
➤ YN0000: │ playwright@npm:1.37.0 STDOUT Chromium 116.0.5845.82 (playwright build v1076) downloaded to /home/circleci/.cache/ms-playwright/chromium-1076
➤ YN0000: │ playwright@npm:1.37.0 STDOUT Downloading FFMPEG playwright build v1009[2m from https://playwright.azureedge.net/builds/ffmpeg/1009/ffmpeg-linux.zip[22m
➤ YN0000: │ playwright@npm:1.37.0 STDOUT |                                                                                |   0% of 2.6 Mb
➤ YN0000: │ playwright@npm:1.37.0 STDOUT |■■■■■■■■                                                                        |  10% of 2.6 Mb
➤ YN0000: │ playwright@npm:1.37.0 STDOUT |■■■■■■■■■■■■■■■■                                                                |  20% of 2.6 Mb
➤ YN0000: │ playwright@npm:1.37.0 STDOUT |■■■■■■■■■■■■■■■■■■■■■■■■                                                        |  30% of 2.6 Mb
➤ YN0000: │ playwright@npm:1.37.0 STDOUT |■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■                                                |  40% of 2.6 Mb
➤ YN0000: │ playwright@npm:1.37.0 STDOUT |■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■                                        |  50% of 2.6 Mb
➤ YN0000: │ playwright@npm:1.37.0 STDOUT |■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■                                |  60% of 2.6 Mb
➤ YN0000: │ playwright@npm:1.37.0 STDOUT |■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■                        |  70% of 2.6 Mb
➤ YN0000: │ playwright@npm:1.37.0 STDOUT |■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■                |  80% of 2.6 Mb
➤ YN0000: │ playwright@npm:1.37.0 STDOUT |■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■        |  90% of 2.6 Mb
➤ YN0000: │ playwright@npm:1.37.0 STDOUT |■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■| 100% of 2.6 Mb
➤ YN0000: │ playwright@npm:1.37.0 STDOUT FFMPEG playwright build v1009 downloaded to /home/circleci/.cache/ms-playwright/ffmpeg-1009
➤ YN0000: │ playwright@npm:1.37.0 STDOUT Downloading Firefox 115.0 (playwright build v1422)[2m from https://playwright.azureedge.net/builds/firefox/1422/firefox-ubuntu-22.04.zip[22m
➤ YN0000: │ playwright@npm:1.37.0 STDOUT |                                                                                |   0% of 79.1 Mb
➤ YN0000: │ playwright@npm:1.37.0 STDOUT |■■■■■■■■                                                                        |  10% of 79.1 Mb
➤ YN0000: │ playwright@npm:1.37.0 STDOUT |■■■■■■■■■■■■■■■■                                                                |  20% of 79.1 Mb
➤ YN0000: │ playwright@npm:1.37.0 STDOUT |■■■■■■■■■■■■■■■■■■■■■■■■                                                        |  30% of 79.1 Mb
➤ YN0000: │ playwright@npm:1.37.0 STDOUT |■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■                                                |  40% of 79.1 Mb
➤ YN0000: │ playwright@npm:1.37.0 STDOUT |■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■                                        |  50% of 79.1 Mb
➤ YN0000: │ playwright@npm:1.37.0 STDOUT |■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■                                |  60% of 79.1 Mb
➤ YN0000: │ playwright@npm:1.37.0 STDOUT |■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■                        |  70% of 79.1 Mb
➤ YN0000: │ playwright@npm:1.37.0 STDOUT |■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■                |  80% of 79.1 Mb
➤ YN0000: │ playwright@npm:1.37.0 STDOUT |■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■        |  90% of 79.1 Mb
➤ YN0000: │ playwright@npm:1.37.0 STDOUT |■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■| 100% of 79.1 Mb
➤ YN0000: │ playwright@npm:1.37.0 STDOUT Firefox 115.0 (playwright build v1422) downloaded to /home/circleci/.cache/ms-playwright/firefox-1422
➤ YN0000: │ playwright@npm:1.37.0 STDOUT Downloading Webkit 17.0 (playwright build v1883)[2m from https://playwright.azureedge.net/builds/webkit/1883/webkit-ubuntu-22.04.zip[22m
➤ YN0000: │ playwright@npm:1.37.0 STDOUT |                                                                                |   0% of 82.2 Mb
➤ YN0000: │ playwright@npm:1.37.0 STDOUT |■■■■■■■■                                                                        |  10% of 82.2 Mb
➤ YN0000: │ playwright@npm:1.37.0 STDOUT |■■■■■■■■■■■■■■■■                                                                |  20% of 82.2 Mb
➤ YN0000: │ playwright@npm:1.37.0 STDOUT |■■■■■■■■■■■■■■■■■■■■■■■■                                                        |  30% of 82.2 Mb
➤ YN0000: │ playwright@npm:1.37.0 STDOUT |■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■                                                |  40% of 82.2 Mb
➤ YN0000: │ playwright@npm:1.37.0 STDOUT |■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■                                        |  50% of 82.2 Mb
➤ YN0000: │ playwright@npm:1.37.0 STDOUT |■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■                                |  60% of 82.2 Mb
➤ YN0000: │ playwright@npm:1.37.0 STDOUT |■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■                        |  70% of 82.2 Mb
➤ YN0000: │ playwright@npm:1.37.0 STDOUT |■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■                |  80% of 82.2 Mb
➤ YN0000: │ playwright@npm:1.37.0 STDOUT |■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■        |  90% of 82.2 Mb
➤ YN0000: │ playwright@npm:1.37.0 STDOUT |■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■| 100% of 82.2 Mb
➤ YN0000: │ playwright@npm:1.37.0 STDOUT Webkit 17.0 (playwright build v1883) downloaded to /home/circleci/.cache/ms-playwright/webkit-1883
➤ YN0007: │ wp-calypso@workspace:. must be built because it never has been before or the last one failed
➤ YN0007: │ @automattic/newspack-blocks@npm:2.0.0 [cd6b3] must be built because it never has been before or the last one failed
➤ YN0000: │ wp-calypso@workspace:. STDOUT [@automattic/calypso-color-schemes]: Process started
➤ YN0000: │ wp-calypso@workspace:. STDOUT [@automattic/calypso-config]: Process started
➤ YN0000: │ wp-calypso@workspace:. STDOUT [@automattic/calypso-products]: Process started
➤ YN0000: │ wp-calypso@workspace:. STDOUT [@automattic/create-calypso-config]: Process started
➤ YN0000: │ wp-calypso@workspace:. STDOUT [@automattic/data-stores]: Process started
➤ YN0000: │ wp-calypso@workspace:. STDOUT [@automattic/format-currency]: Process started
➤ YN0000: │ wp-calypso@workspace:. STDOUT [@automattic/jetpack-ai-calypso]: Process started
➤ YN0000: │ wp-calypso@workspace:. STDOUT [@automattic/languages]: Process started
➤ YN0000: │ wp-calypso@workspace:. STDOUT [@automattic/plans-grid-next]: Process started
➤ YN0000: │ wp-calypso@workspace:. STDOUT [@automattic/social-previews]: Process started
➤ YN0000: │ wp-calypso@workspace:. STDOUT [@automattic/urls]: Process started
➤ YN0000: │ wp-calypso@workspace:. STDOUT [@automattic/verbum-block-editor]: Process started
➤ YN0000: │ wp-calypso@workspace:. STDOUT [@automattic/viewport]: Process started
➤ YN0000: │ wp-calypso@workspace:. STDOUT [@automattic/zendesk-client]: Process started
➤ YN0000: │ wp-calypso@workspace:. STDOUT [@automattic/calypso-color-schemes]: Process exited (exit code 0), completed in 6s 370ms
➤ YN0000: │ wp-calypso@workspace:. STDOUT [@automattic/calypso-config]: Process exited (exit code 0), completed in 7s 641ms
➤ YN0009: │ wp-calypso@workspace:. couldn't be built successfully (exit code 129, logs can be found here: /tmp/xfs-afb28174/build.log)
➤ YN0000: └ Completed in 1m 51s
➤ YN0000: · Failed with errors in 1m 58s
```

Which is indeed in line with your finding.

> I don't have CircleCI access to dig into it further,

I'll send you a DM with an invite.

**Comment by mokagio** [comment]
I'll wait to close this till #92835 lands

**Comment by mokagio** [comment]
@matt-west @wojtekn I made a typo when writing `92835` in the comment above and wrote `92865` instead. Between that #92865 and #92835 I'm getting the impression that there is some new work going into the WordPress Desktop app.

Is that the case? And if so would having the build infrastructure in Buildkite help you iterate?

**Comment by wojtekn** [comment]
> I'm getting the impression that there is some new work going into the WordPress Desktop app.

@mokagio it's correct. @matt-west and YOLO are working on a few fixes based on the review from p58i-hGx-p2.

> Is that the case? And if so would having the build infrastructure in Buildkite help you iterate?

It would help in the long run. However, as we are now working only on small fixes here and there, and the current infrastructure seems to work fine, we can hold off on the move for now, especially since I expect it could take a significant amount of time for everyone.

**Comment by wojtekn** [comment]
> Is this something you verified running locally @matt-west ?
> The CI logs were as follow:
> [...]

@mokagio we checked that locally on Linux, and it worked fine. I thought it might be a one-time issue or some quirk related to the cache or dist directory not being cleaned. I wanted to re-run builds but I don't have an access to project in CircleCI (yet).

**Comment by wojtekn** [comment]
Closing, I tested the related PR using artifacts from this PR's build.

**Pull request closed without merging**
