### PR TITLE
Reader post card: turn off the link indicator in the Card component

### PR DESCRIPTION
**Pull request by bluefuton**
@shaunandrews noticed that Reader post cards had gained a mysterious chevron on the right-hand side:

screen shot 2017-10-31 at 13 39 39

This was caused by a slight change in behaviour to the Card component in https://github.com/Automattic/wp-calypso/pull/19272/files.

This PR adds a new prop to Card called `showLinkIndicator`. It defaults to true. When showLinkIndicator is specified as false, no link indicator will be shown. Reader post cards now provide this prop.

### To test

Check a Reader stream and make sure no chevrons appear on the right of post cards.

Also check the Card component in Devdocs, to ensure that the linkable cards still have their icon on the right-hand side:

http://calypso.localhost:3000/devdocs/design/cards

### CODE REVIEW

**Comment by blowery** [comment]
Code looks good, testing now.

**Comment by ockham** [comment]
Sry bout that, thanks for fixing @bluefuton!

**Comment by bluefuton** [comment]
No worries @ockham! Hope the solution makes sense. We have a couple of places where we use `onClick` and also want to hide the link indicator.

**Comment by ockham** [comment]
@bluefuton I was wondering, do you also have any instances of `onClick` (but no `href`) where you want to _show_ the link indicator? I was considering if maybe the link indicator should only be displayed iff there was an `href`.

**Comment by ockham** [comment]
(Also discussed here: https://github.com/Automattic/wp-calypso/pull/19272#issuecomment-340798396)

**Comment by bluefuton** [comment]
@ockham we never show it :) If the logic changes back to only show the indicator when there's an `href`, that would work for us.

**Comment by ockham** [comment]
Talk about side effects: https://github.com/Automattic/wp-calypso/pull/19272#issuecomment-341084524 :slightly_frowning_face:

**Comment by tyxla** [comment]
And a fix for that: #19384

**Comment by samouri** [comment]
we sometimes show both an href and an onClick.  
we do that for situation where we want to retain fully native behavior for meta-click and ctrl-click

**Comment by bluefuton** [comment]
> we sometimes have both an href and an onClick (and never want to show a link indicator)
we do that for situation where we want to retain fully native behavior for meta-click and ctrl-click

... but not using the `Card` component as far as I can see. 🕵️

**Comment by ockham** [comment]
> ... but not using the `Card` component as far as I can see. :male_detective: 

😌

**Pull request merged**
