### PR TITLE
Site Assembler: Improve the global styles gating experience

### PR DESCRIPTION
**Pull request by arthur791004**
Related to https://github.com/Automattic/wp-calypso/issues/74946

## Proposed Changes

* Updated copy in the modal
  * Added `You've selected a premium color or font for your site.` as the first sentence.
  * Added `You can also continue with your selected color or font and upgrade later."` as the last sentence.
  * Replaced `Included with your purchase` with `Included with your Premium plan`
  * Replaced `Try it out` with `Upgrade later` and have it close the modal
* When the modal closes
  * The button in the side nav changes to `Continue`
  * The description above the button changes to `Ready? Keep your styles and go to the Site Editor to edit your content. You’ll be able to upgrade to the Premium plan later.`

### Screenshots

image

image

Screenshot 2023-03-29 at 5 21 09 PM

### Demo

https://user-images.githubusercontent.com/13596067/228487833-e67c6052-4f03-4287-9e5c-47ca0fd53b95.mov

## Testing Instructions

* Go to /setup/site-setup?siteSlug=<your_site>
  * Note that the site should be the site with a free plan
* Continue until you land on the Design Picker
* On the Design Picker screen, scroll down to the bottom and select BCPA CTA
* On the Pattern Assembler screen
  * Select any color or font variation
  * Click on `Unlock this style`
  * Ensure the copy is updated as mentioned above
  * Click on `Upgrade later`
  * Ensure the modal is close
  * Ensure the copy at the bottom of the sidebar changes to `Continue`
  * Ensure the copy above that button changes as mentioned above
  * Click on `Continue`, and ensure you're going to the site editor directly
* Test that the modal in other flows (in Design Picker themes, Showcase themes, or the Editor) continue to show the previous text.

## Pre-merge Checklist

- [x] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [x] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [x] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [x] Have you checked for TypeScript, React or other console errors?
- [x] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [x] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [x] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

**Comment by autumnfjeld** [comment]
@davewhitley @ianstewart  Just an FYI on this improvement.   We expect refinement on copy from Pablo or Dave or others in the coming weeks, but I made the call to have these changes done before the CfT, changes  to both copy and the UX flow.

Thank you @arthur791004 for the very clear visuals that show the change to copy.

Also thank you to to @dsas for the little "push" of approval to make changes appropriate to the modal.

**Comment by autumnfjeld** [comment]
✅  Verified modal is correct in Design Picker
image

✅  I like how this combo of text ties in the usage of "color or font" with "styles" .... for those new users who might not be as familiar with "website lingo", it ties it together.
image


🚫  When I selected "Upgrade plan" I was redirected to Goals screen after checkout:
* Started with new site
* Did not select any goals
* Did not select any vertical
* Chose the BCPA CTA
* Chose a premium color
* Clicked Unlock this style
* Clicked Upgrade plan
* Was directed to checkout
* Completed checkout
* Landed back on the Goals screen

**Comment by arthur791004** [comment]
> When I selected "Upgrade plan" I was redirected to Goals screen after checkout:

This is expected for now as it requires both https://github.com/Automattic/wp-calypso/pull/75056 and https://github.com/Automattic/wp-calypso/pull/75057

**Comment by arthur791004** [comment]
@autumnfjeld If the new copy looks good, I'll add the label to request translation. WDYT?

**Review by taipeicoder — APPROVED** [review]
LGTM 👍

**Review by okmttdhr — APPROVED** [review]
✅

**Comment by autumnfjeld** [comment]
@arthur791004  I think the font selection isn't working properly, some of the fonts don't seem to update. 
https://files.slack.com/files-pri/T024FN1V2-F050ZC0RSMC/image.png


https://user-images.githubusercontent.com/5665959/229022830-c83f38ac-6f86-4e36-a2c6-bc811ad3dad0.mp4

**Comment by autumnfjeld** [comment]
> @autumnfjeld If the new copy looks good, I'll add the label to request translation

Let's wait til after the walkthrough call.    The only possible change I see is if we want to add an "Upgrade now" link somewhere in this text.  Not sure.....

image

**Comment by arthur791004** [comment]
> I think the font selection isn't working properly, some of the fonts don't seem to update.

@autumnfjeld hmmm...interesting since it works for me 😂 Looks like the related font-face CSS is not loaded correctly on your site.

https://user-images.githubusercontent.com/13596067/229025813-a0c256d7-e4ee-44c4-b0ca-282f5dd5994d.mov

**Comment by autumnfjeld** [comment]
> @autumnfjeld hmmm...interesting since it works for me 😂 Looks like the related font-face CSS is not loaded correctly on your site.

It could be due to my spotty internet.  It cuts out a lot.  :( 

The "Upgrade flow" looks good!  
* clicked upgrade in the modal
* went through checkout
* landed back in Assembler with data saved as it was before checkout

Do you want to merge this into horizon before our walkthrough call?

**Comment by arthur791004** [comment]
Okay! We can keep tracking the font issue if anyone also encounters the same one

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/7897581

Thank you @arthur791004 for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/7897581).

**Pull request merged**
