### PR TITLE
Sites Management Dashboard: Add shadow to site previews on hover

### PR DESCRIPTION
**Pull request by p-jackson**
#### Proposed Changes

Alternative to #66837, no zoom, just shadow.

https://user-images.githubusercontent.com/1500769/186060015-dbaa9579-f711-4ccd-9f05-496ef9f6a504.mov

#### Testing Instructions

*

#### Pre-merge Checklist

- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?

Related to #

### CODE REVIEW

**Comment by SaxonF** [comment]
Prefer the shadow hover over scaling 👍

**Comment by vykes-mac** [comment]
Yeah shadow definitely looks better. 👍

**Comment by zaguiini** [comment]
It works well and looks much better than zooming 👍 

Implementation-wise, what do you think of:

1. Creating a styled component, on a dedicated file, called `SiteTileLeading` (an `a`nchor) that would contain the styles defined in `sitePreviewHoverClass`;
2. Use that component as the `leading` prop in both `SitesGridItem` and `SitesTableRow`;
3. Apply the current styling of `ListTileLeading` on top of the table row's `SiteTileLeading` instance:

```tsx
const inlineEndMarginOnMobile = css( {
  [ MEDIA_QUERIES.mediumOrSmaller ]: {
    marginInlineEnd: 12px,
  },
} )

leading={ <SiteTileLeading className={ inlineEndMarginOnMobile } { ...props } /> }
```

**Review by zaguiini — APPROVED** [review]
Looks great 👍

**Review by danielbachhuber — COMMENTED** [review]
I'm noticing a little artifact at the bottom of the thumbnail:
CleanShot 2022-08-24 at 09 51 06@2x

Notably, there's an extra pixel of white at the bottom and squared off white corners.

The problem is that we're adding the box shadow to the parent element, and the border and border radius are on the child element:

image

This seems like an easy fix with CSS selectors (simply apply the box shadow to the `.site-thumbnail ` class). I'm not sure what the proper "React refactor" should be, though.

**Comment by p-jackson** [comment]
Ah I see, it's because the site thumbnail has a border radius but the `::after` has crisp sharp corners. The white pixels you're seeing are the `::after` element peeking from behind the thumbnail.

Since the shadow transition depends on having the separate `::after` element it means we can't just move the rules to the `.site-thumbnail` element itself.

I tried an OTT fix that inset the edge of the `::after` element (68f98f00f08885104094e3fd8ad6667281082d7d). It looks like this if you hide the thumbnail.
CleanShot 2022-08-25 at 14 17 00@2x

But I ended up going with a simpler fix in 25069b973f39e4a261aa38fb34315dc2dc826a75 which is just to put an identical border radius on the `::after`. It's not as robust because the radius values could go out of sync. But much more understandable.

**Pull request merged**
