### PR TITLE
Plugin Details: Show a banner asking for reviews on Marketplace Plugins

### LINKED ISSUE #86408: Plugin Details: Show a nudge to ask for new Reviews
- When a user has an active subscription for a given plugin
- And the user has not yet written a review
- Show a nudge on the top of the page, asking the user to leave a review
- The nudge should be clickable and must open the Reviews Modal

CleanShot 2024-01-15 at 10 24 30@2x

### PR DESCRIPTION
**Pull request by WBerredo**
Fixes https://github.com/Automattic/wp-calypso/issues/86408

## Proposed Changes

Show a banner asking reviews on the Plugin Details page when:
- The user has not left a review yet
- Its a Marketplace plugin
- The user has an active subscription

## Testing Instructions

* Go to the plugin details page of a plugin where you haven't left a review yet. Ex: `/plugins/woocommerce-subscriptions/:site`
* Purchase it if you don't have an active subscription yet.
* Go back to the plugin details page
* Check if the banner is shown for you and if clicking open the Reviews Modal

CleanShot 2024-01-18 at 11 58 53

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

**Review by gcsecsey — APPROVED** [review]
Changes LGTM and work as described
CleanShot 2024-01-18 at 18 57 00@2x

Nit: maybe we should reduce the top padding when the banner is shown?
CleanShot 2024-01-18 at 18 57 56@2x

**Comment by WBerredo** [comment]
> Nit: maybe we should reduce the top padding when the banner is shown?

Agreed, updated at https://github.com/Automattic/wp-calypso/pull/86598/commits/61f4f1356ce210e526a7bcb5ef1f4cab17200af5

CleanShot 2024-01-19 at 09 35 09@2x

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/10868994

Some locales (Hebrew, Japanese) have been temporarily machine-translated due to translator availability. All other translations are usually ready within a few days. Untranslated and machine-translated strings will be sent for translation next Monday and are expected to be completed by the following Friday.

Thank you @WBerredo for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/10868994).

**Pull request merged**
