### PR TITLE
WP for Teams: add descriptions to user roles and special handling for WP4Teams sites

### PR DESCRIPTION
**Pull request by lamosty**
Fixes https://github.com/Automattic/wp-for-teams/issues/172.

In this PR, we add descriptions to most common user roles for the `people/new` Calypso page. We also add a check if site is a WP for Teams one and if yes, modify the descriptions a bit to match them for WP for Sites needs.

## Testing

Navigate to http://calypso.localhost:3000/people/new with a WP for Teams site and verify the role descriptions match the ones described in the above issue. Now, select a standard WP.com site and verify the role descriptions are more generic.

/cc @evilluendas for design improvements.

### CODE REVIEW

**Comment by evilluendas** [comment]
I just pushed a tiny tweak to the new CSS:

*Before*
image

*After*
image

We would need to hide the Contributor role from the list if the site is a Team site, since it goes against what the tool is for.

**Comment by lamosty** [comment]
Thanks for the updated design and the feedback @evilluendas! Updated in bc66273.

What do you think about sites with non-standard roles like this: https://d.pr/i/KogwDQ ? They will be missing the descriptions and not sure if it's too ugly or okay. Also, I guess we could add descriptions to the shop manager and customer as those look to be standard for a Woo site (need to double check) but I think a site can have some other custom roles introduced by plugins (for like Atomic).

**Comment by lezama** [comment]
@lamosty let's push the improvement and open an issue about those descriptions missing

**Comment by lamosty** [comment]
> @lamosty let's push the improvement and open an issue about those descriptions missing

Alright, will do.

**Pull request merged**
