### PR TITLE
Merge release/desktop/3.9.0 into Master

### PR DESCRIPTION
**Pull request by loremattei**
Merge release/desktop/3.9.0 into Master.

### CODE REVIEW

**Comment by blowery** [comment]
@loremattei I'm confused here. I thought the patch that fixed onboarding already landed in calypso?

**Comment by loremattei** [comment]
@blowery yes, it did. I cherry-picked it from master. 
Though cherry-picking creates a different commit hash in the target branch, so I usually merge it back to keep the repository consistent. If we delete this branch without merging it, the Calypso commit referenced in the WPDesktop release would be deleted. 

Tbh, I expected a merge with no diffs. Probably I have to merge master in this branch to fix the conflict and keep the latest version of Calypso.

Does it make sense?

**Comment by blowery** [comment]
Yeah the explanation makes sense. Just need to figure out why there's a diff here.

Looks like https://github.com/Automattic/wp-calypso/commit/2cbd54810b14965bf25b866286ac0f9603686c37 fixed this in a different way.

**Comment by blowery** [comment]
OK, so we don't actually want any of the code from the release branch, this was fixed another way.

**Comment by loremattei** [comment]
Thank you very much @blowery!

**Pull request merged**
