### PR TITLE
Stepper: Implement style picker in LIB flow

### PR DESCRIPTION
**Pull request by alshakero**
#### Proposed Changes

* This implements the style-picker for LIB. It's a much lighter version than design picker.
* It uses native scroll snapping to enable touch-enabled carousel on phones.

#### Desktop
1. Go to https://container-trusting-chaplygin.calypso.live/setup/patterns?flow=link-in-bio&siteSlug=YOUR_SITE
2. The carousel should have buttons for moving it left and right.
3. The buttons should be more opaque when you hover the carousel.
4. Clicking a blurred item should bring it in focus.
5. Using arrows should move the carousel as you'd expect.

#### Mobile
1. Go to https://container-trusting-chaplygin.calypso.live/setup/patterns?flow=link-in-bio&siteSlug=YOUR_SITE
2. The carousel should be receptive to touch gestures.
3. The buttons mentioned above should be hidden. 
4. Clicking a blurred item should bring it to front.

### Screenshot
image

### CODE REVIEW

**Comment by renancarvalho** [comment]
@alshakero, super cool 🏅 , thank you! I did a very small push, added cursor pointer on the nav button to give a better feel for the user.

**Review by escapemanuele — COMMENTED** [review]
Oh man, it's awesome and really fluid! I left just a couple of suggestions.

Is it possible that we need the cards to be bigger?
| Design | Now |
| ------------- | ------------- |
| image  | image  |

Text in the button is not centered.

Do we need to add the dots under the card, as in the designs?

It seems that we automatically select the first card, blurring out the others, while in the designs there is not card selected in the beginning!

**Comment by alshakero** [comment]
Note that all feedback back and forth happened here: p1660161266360479-slack-C03E1LGV796

**Review by escapemanuele — APPROVED** [review]
This is awesome @alshakero! 💯 🚢

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/7477734

Thank you @alshakero for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/7477734).

**Pull request merged**
