### PR TITLE
Apply Autofix For "no-package-relative-imports" in client/my-sites

### PR DESCRIPTION
**Pull request by Aurorum**
#### Changes proposed in this Pull Request

I basically just ran `./node_modules/.bin/eslint-nibble --ext .js,.jsx,.ts,.tsx,.md.js,.md.javascript,.md.jsx client/my-sites` because my PR in #46538 was failing, so I wasn't sure if I should just open this instead.

@flootr @scinos Would you prefer this to be done in individual files, like the PR linked above, or just one big chunk like this?

Apparently also includes a typo fix in one README document...

#### Testing instructions

* Verify there's no errors when actually using the My Sites section in Calypso (there will inevitably be Lint errors here though) 

Part of #44602

### CODE REVIEW

**Comment by sirbrillig** [comment]
Conceptually this seems like a great idea! My only concerns are:

- It's probably worth also running Prettier on those same files to fix the lint errors.
- It's basically impossible to review the code changes (too many lines, of course they _should_ be safe since it's automated) and also very hard to manually test the changes (there's quite a lot of components in my-sites which this touches). In which case, I'm not sure this really needs a review at all.
- It also probably is going to be tricky to keep up-to-date since it touches so many files which might conflict.

I think I'd be confident enough to approve it if we can get the tests to all pass.

**Comment by Aurorum** [comment]
Thanks @sirbrillig - I've resolved the conflicts and will aim to do so regularly! I believe that [this commit](https://github.com/Automattic/wp-calypso/pull/46550/commits/7b9ccacbcd5570066428550a18df6847baffea46) ran Prettier on the affected files (along with some stylesheets in this section) so they should be included within this branch. 

As for the tests, I believe `wp-desktop-source` failing is expected (all my PRs have this issue regardless of what they touch!), and that this PR shouldn't be introducing any new Lint issues, though please let me know if there's something which I need to adjust or work on! :)

**Comment by sirbrillig** [comment]
Oh right, I forgot that some tests always fail for OSS PRs now. 😩

**Comment by sirbrillig** [comment]
Woah, not sure how I accidentally closed this. Sorry about that. I was looking at the linting errors reported in CircleCI (there are 326 of them) and it looks like most of them are warnings, rather than errors, which is strange and may also be related to being an OSS PR. I do see some Prettier errors (eg: `/home/circleci/wp-calypso/client/my-sites/stats/wordads/index`), undefined variable errors (eg: `/home/circleci/wp-calypso/client/my-sites/stats/summary/index`), and other things that might be real, though, and I'd feel badly if I merged this without investigating them. I'll see if I can do that soon.

**Comment by Aurorum** [comment]
Oops, looks like there were some files Prettier had touched that weren't committed; they should all be now - let me know if not!

**Comment by sirbrillig** [comment]
Thank you! 

Most of the remaining lint errors look harmless. I did some parsing on the results and here's the unique error codes:

```
(@typescript-eslint/ban-types)
(@typescript-eslint/no-unused-vars)
(@typescript-eslint/no-use-before-define)
(jsdoc/check-param-names)
(jsdoc/newline-after-description)
(jsx-a11y/alt-text)
(jsx-a11y/anchor-is-valid)
(jsx-a11y/click-events-have-key-events)
(jsx-a11y/heading-has-content)
(jsx-a11y/mouse-events-have-key-events)
(jsx-a11y/no-autofocus)
(jsx-a11y/no-noninteractive-element-interactions)
(jsx-a11y/no-static-element-interactions)
(no-extra-boolean-cast)
(no-restricted-imports)
(no-shadow)
(no-undef)
(prefer-const)
(react/no-string-refs)
(react/prefer-es6-class)
(wpcalypso/jsx-classname-namespace)
(wpcalypso/redux-no-bound-selectors)
```

However... 😬  I'm still nervous about this. Mainly I'm worried that if we commit these changes with the linting errors in place that it might cause future PRs to also report those errors? Probably not, since I think we only report errors for lines changed in the specific PR, but I'd really like some guidance from @Automattic/team-calypso (maybe @flootr @scinos since they were pinged originally?).

**Comment by scinos** [comment]
It should be fine to merge.

Unfortunately we have many existing lint errors but they only get reported when the file is changed. A PR that touches many files (like this one) is expected to surface some of them.

I'll fix the conflicting files and run the required builds to unblock this PR.

**Comment by Aurorum** [comment]
Thank you! I've fixed the conflicting files and will check again this evening to see if there's any new ones that need fixing.

**Comment by sirbrillig** [comment]
The CI unit tests passed according to the CI but it looks like the signal didn't make it here, so the merge button is still blocked. Re-running the tests 🤞

**Comment by Aurorum** [comment]
Thanks @sirbrillig! :)

**Pull request merged**
