### PR TITLE
Editor: Remove toolbar left border when floating

### PR DESCRIPTION
**Pull request by sendilkumarn**
#4173  Removed toolbar left border when floating in editor

### CODE REVIEW

**Comment by sendilkumarn** [comment]
screen shot 2016-03-20 at 11 07 02 am

**Comment by sendilkumarn** [comment]
@nylen

**Comment by nylen** [comment]
Thanks for contributing, @sendilkumarn!  Please fix the indentation (use 3 hard tab characters) and this should be good to go!

**Comment by nylen** [comment]
Still some issues with indentation here.

- Spaces at the beginning of the line (should be tab characters only)
- Indented too far (the `top:` line is a special case, indented one level more than `position` above it, see [CSS.md](https://github.com/Automattic/wp-calypso/blob/master/docs/coding-guidelines/css.md#positioning))

There should be 3 tab characters and no space characters at the beginning of the line you've added.

**Comment by sendilkumarn** [comment]
@nylen i will check n recommit. Thanks

**Comment by nylen** [comment]
No problem.  Looking at this again, if you want to set `border-right-width: 0;` too, that would be fine.

image

**Comment by sendilkumarn** [comment]
Is there any way to check the identation. My atom / code shows correctly. Do you have any hacks or plugins for this
@nylen

**Comment by sendilkumarn** [comment]
@nylen

**Comment by nylen** [comment]
The spaces are gone now, that's good.  This comment still stands, though:

> Indented too far (the `top:` line is a special case, indented one level more than `position` above it, see [CSS.md](https://github.com/Automattic/wp-calypso/blob/master/docs/coding-guidelines/css.md#positioning))

> There should be 3 tab characters and no space characters at the beginning of the line you've added.

**Pull request closed without merging**
