### PR TITLE
Add contributor role back

### PR DESCRIPTION
**Pull request by unDemian**
#### Changes proposed in this Pull Request

* Add the contributor back

#### Testing instructions

* Go to Manage -> People -> Invite
* The Contributor role should be available

Fixes 1364-gh-p2

### CODE REVIEW

**Comment by annemirasol** [comment]
Weird, but I'm not seeing the Contributor role, both in Calypso live or local tests 🤔

**Comment by unDemian** [comment]
> Weird, but I'm not seeing the Contributor role, both in Calypso live or local tests 🤔

In which view?

**Comment by annemirasol** [comment]
> > Weird, but I'm not seeing the Contributor role, both in Calypso live or local tests 🤔
> 
> In which view?

Screen Shot 2020-11-16 at 5 53 49 PM

**Comment by annemirasol** [comment]
Could it be this? https://opengrok.a8c.com/source/xref/trunk/wp-content/mu-plugins/wpforteams.php#128

**Comment by unDemian** [comment]
Good catch, I think I was testing the wrong site (non p2) D52782-code and 1397-gh-p2 should be applied.

**Review by annemirasol — APPROVED** [review]
Looks good!

**Pull request merged**
