### PR TITLE
Embed Gutenberg in Calypso

### PR DESCRIPTION
**Pull request by jsnajdr**
Experiment in progress. To update this branch to latest version of Calypso or Gutenberg:

1. Copy Gutenberg sources to `vendor/gutenberg`. Be careful to not include the `.git` and `node_module` directories. They are huge and useless 😜
2. Apply the remaining patches from this branch to the pristine Calypso + Gutenberg sources and resolve conflicts if needed.
3. Start Calypso and enjoy `calypso.localhost:3000/gutenberg`!

### CODE REVIEW

**Comment by dmsnell** [comment]
Only adds about 4.5 MB to the editor page! 🙃 

http://iscalypsofastyet.com/branch?branch=try/gutenbergify

**Comment by mtias** [comment]
It's an MB party, everyone can bring their own MBs.

**Comment by jsnajdr** [comment]
I updated the PR description with instructions how to update the branch to latest Calypso and Gutenberg sources and how to rebase the patches. Thanks @dmsnell for this suggestion.

> Only adds about 4.5 MB to the editor page! 🙃

Come on, Gutenberg is totally worth waiting for 4.5 MB of JavaScript! 🥇

**Comment by ockham** [comment]
> It's an MB party, everyone can bring their own MBs.

BYOMB

**Comment by jsnajdr** [comment]
I updated this branch with the latest version of Gutenberg. In the 3 weeks since it was originally created, many integration issues were solved!

- thanks to @iseulde there's a new `@wordpress/shortcode` module. No more references to the `wp.shortcode` global.
- thanks to @aduth and the `babel-plugin-import-jsx-pragma` transform, most issues with transpiling JSX and referencing the `wp.element` global were solved. I just added an "override" declaration to Calypso's Babel config.
- previously we had to patch the `editor/deprecated.js` file to get rid of a `wp.blocks` global reference. That code was recently removed by @aduth and we no longer need to patch it.

We still need to patch a few things:

There's still a `wp.element` reference in the `Dashicon` component. It should be trivial to replace it with a `@wordpress/element` import, but I'm not sure if I can edit the `dashicon/index.js` file. Was it generated by the Dashicons build process, including the `wp.element` reference? Or is it OK to patch it manually in the Gutenberg repo? @aduth

There are many references to `wp.api` global. Typical pattern is:
```js
const path = wp.api.getSomeRoute( slug );
apiRequest( { path: `/wp/v2/${ path }` } );
```
We might want to provide some data-layer-ish abstraction for that. The implementation for `apiRequest` is very likely to be provided by Calypso. Even the REST routes might be different if we decide to use the WP.com APIs. @youknowriad 

I had to upgrade Calypso's TinyMCE to 4.8.0, because Gutenberg uses `editor.hasFocus` method that was added only in 4.7.10. Calypso is still on 4.6.3. After #25648 is merged, this patch will no longer be a part of the Gutenberg branch.

After all the global references are eliminated and a `@wordpress/editor` NPM package is published, the biggest integration task will be integrating the data stores and REST API requests. Calypso will most likely provide its own implementation of some stores' interfaces. The Gutenberg data system seems to be mostly ready for that, but there will be many issues for sure.

**Comment by aduth** [comment]
>There's still a wp.element reference in the Dashicon component. It should be trivial to replace it with a @wordpress/element import, but I'm not sure if I can edit the dashicon/index.js file. Was it generated by the Dashicons build process, including the wp.element reference? Or is it OK to patch it manually in the Gutenberg repo?

This was updated upstream in https://github.com/WordPress/dashicons/pull/305 , and probably just needs a new copy of Dashicons copied over into Gutenberg.

**Comment by jsnajdr** [comment]
Another two great updates in last 24 hours:
- @aduth solved the Dashicons issue really quickly
- @gziolo upgraded Gutenberg's Babel to version 7. Less Babel magic is now needed to compile the vendored Gutenberg and after we upgrade Calypso to Babel 7.0.0 beta 52+, all Babel custom patches can be removed

**Comment by alisterscott** [comment]
This PR needs a rebase - are we continuing with it?

**Comment by jsnajdr** [comment]
> This PR needs a rebase - are we continuing with it?

This is an experimental branch that's not intended to be ever merged. I'll keep it open for a while though in case I wanted to update it for some reason, e.g., to do some other Gutenberg experiment.

**Comment by jsnajdr** [comment]
This experimental branch is no longer needed, closing.

**Pull request closed without merging**
