### PR TITLE
Automattic for Agencies: Redesign the Referrals page

### PR DESCRIPTION
**Pull request by yashwin**
Resolves https://github.com/Automattic/jetpack-genesis/issues/333

## Proposed Changes

This PR redesigns the Referrals page.

NOTE: Please ignore the status badge for now. This will be implemented in another PR.

## Testing Instructions

1) Open the A4A live link.
2) Go to Referrals > Verify that you can see the UI as shown below:

Screenshot 2024-04-25 at 11 04 31 AM

3) Go to /sections/referrals/primary/referrals-overview/index.tsx > Change the `hasPayeeAccount` to true  > Refresh the page > Verify that you can see the UI as shown below. Notice the button.

Screenshot 2024-04-25 at 11 44 16 AM

Other screen sizes:

Screenshot 2024-04-25 at 4 17 21 PM

Screenshot 2024-04-25 at 4 17 33 PM

## Pre-merge Checklist

- [x] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [x] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Review by jkguidaven — APPROVED** [review]
the changes is working as per test instructions. Overall the changes looks good to me.

I have noticed that the button size is too small on the mobile screen, making it hard to press. As there is a standard size for mobile buttons, perhaps we can increase the button's size to make it bigger and easier to hit when in mobile view. I suggest we address this improvement through a separate PR.

Screenshot 2024-04-25 at 4 30 37 PM

**Review by madebynoam — CHANGES_REQUESTED** [review]
Looking great, @yashwin! Thank you for the super quick turn around!

Just 2 small notes:
On the large breakpoint, could we apply the "70% max widths" on all cards (instead of just the ones that have a status pill):

image

On the mobile size, could we swap the pill to be on top?
image

Otherwise, looks great!

**Comment by madebynoam** [comment]
> the changes is working as per test instructions. Overall the changes looks good to me.
> 
> I have noticed that the button size is too small on the mobile screen, making it hard to press. As there is a standard size for mobile buttons, perhaps we can increase the button's size to make it bigger and easier to hit when in mobile view. I suggest we address this improvement through a separate PR.

Good catch, thanks, @jkguidaven. Usually the minimum is a 40px hit area. We are currently at 28px it seems. 
@jeffgolenski and @keoshi let's tackle this at a system level, and propose the change.

**Comment by yashwin** [comment]
Thanks for the review, @jkguidaven & @madebynoam: 

I have made some adjustments. Could you please another look? TIA 🙇 


Screenshot 2024-04-25 at 4 17 21 PM

Screenshot 2024-04-25 at 4 17 33 PM

Screenshot 2024-04-25 at 4 17 52 PM

**Review by madebynoam — APPROVED** [review]
Thanks, Yashwin!

Lgtm. Just leaving a small note: if we could bump up the description font-size to 14px with 24px line-height to match the Overview page.

image

**Comment by yashwin** [comment]
> Lgtm. Just leaving a small note: if we could bump up the description font-size to 14px with 24px line-height to match the Overview page.

Done: https://github.com/Automattic/wp-calypso/pull/89886/files#diff-208c14349ad412c4703d3c975569c85e655d4be8f26a6ee657842e443478635dR31-R32

**Pull request merged**
