### PR TITLE
Help Center: Update the forums copy

### LINKED ISSUE #84874: Feature Request: Update Forum support option text in Help Center
### What

Update the text of the forum support option in Help Center.

### Why

As requested in p5gXjh-5iR-p2#comment-12410 the aim of this change is to add more clarity on who is providing the support and that it is public.

### How

Update the current title from "Public Forums" to "Community Forums"
Update the description from "Ask our WordPress.com Community" to "Your question and any answers will be public."
Update the description on the form from "Please do not provide financial or contact information when submitting this form." to "Please do not share financial or contact information. Your question and any answers will be public."

Here are the affected UIs:

Screenshot 2023-12-05 at 10 10 12 AM
Screenshot 2023-12-05 at 10 10 18 AM

Thanks!

### PR DESCRIPTION
**Pull request by alshakero**
Fixes: https://github.com/Automattic/wp-calypso/issues/84874

image

image

### CODE REVIEW

**Comment by kriskarkoski** [comment]
@alshakero Support options list looks good. Seeing the line breaks on the form can we do this for readability

Screenshot 2023-12-05 at 10 34 52 AM

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/9901357

Some locales (Hebrew, Japanese) have been temporarily machine-translated due to translator availability. All other translations are usually ready within a few days. Untranslated and machine-translated strings will be sent for translation next Monday and are expected to be completed by the following Friday.

Thank you @alshakero for including a screenshot in the description! This is really helpful for our translators.

**Comment by alshakero** [comment]
@kriskarkoski updated it!
image

**Comment by kriskarkoski** [comment]
Looks great, thank you! Do I need to do anything to formally review/approve it or are you good to proceed?

**Comment by alshakero** [comment]
You're set. I'll deploy once translations finish. We're almost there.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/9901357).

**Pull request merged**
