### PR TITLE
Post normalizer: detect Polldaddy embeds and link to each poll

### LINKED ISSUE #698: Reader: polls do not show up in the single-post view
Steps to reproduce:

1. Start a post at https://wordpress.com/post
1. Add a poll ([related help page](https://en.support.wordpress.com/polls/))
1. Publish the post and view it in the Reader

<strong>Result:</strong> the poll doesn't show up.

Example post:

screen shot 2015-11-24 at tue nov 24 5 45 46 pm
<sup>Testing with Firefox 42.0 on Mac OS X 10.10.5</sup>

Same post in the Reader:

screen shot 2015-11-24 at tue nov 24 5 46 46 pm
<sup>Seen at https://wordpress.com/read/post/id/72040772/1919 using Firefox 42.0 on Mac OS X 10.10.5</sup>

/hat tip vparkhere for the original report

### PR DESCRIPTION
**Pull request by bluefuton**
As noted in #698, we currently don't display anything when a Polldaddy poll is embedded in a post.

As a basic solution, this PR changes the post normalizer to look for Polldaddy polls in the post content, and adds an external link to any polls found with the text 'Take our poll' (which can be translated).

There is no wrapper element around the Polldaddy markup, so we replace the `noscript` tag with our `p` containing an external link.

Before:

screen shot 2016-02-18 at 14 12 57

After: 

screen shot 2016-02-18 at 14 11 25

Test posts:
http://calypso.localhost:3000/read/post/feed/40474296/932431000
http://calypso.localhost:3000/read/post/id/72040772/1919 (from the issue ticket)

Fixes #698.

### CODE REVIEW

**Comment by blowery** [comment]
Nice!

Maybe we could figure out the magic for the iframe embed variant? http://support.polldaddy.com/how-do-i-embed-my-survey-into-my-website/

**Comment by bluefuton** [comment]
> Maybe we could figure out the magic for the iframe embed variant?

Yeah, that'd be nice! Doesn't look like Polldaddy officially support the straightforward iframe variant any more, though:

screen shot 2016-02-18 at 15 07 44

**Comment by bluefuton** [comment]
I think getting the link in there will be a good start. At least users will be able to access the poll, whereas at the moment, it just vanishes without trace...

**Comment by blowery** [comment]
bummer. but :+1:

**Pull request merged**
