### PR TITLE
Social Login: refactor login/signup button logic

### PR DESCRIPTION
**Pull request by arcangelini**
Welcome Ladies and Gentlemen! This one is going to be fun so let's buckle up and enjoy the ride. 🚗 

## Proposed Changes

In general this refactors the social login buttons along with the social login/signup component to make the buttons more self-sufficient.

1. In the social forms - make the handlers and onClicks agnostic and collect the necessary data from the component. There are now just two functions in each `handleLogin|Signup` and `trackLoginAndRememberRedirect`. A byproduct of this change is that we no longer need the `socialService` property since we are saving it to sessionStorage on click. During my testing `google` was not always being set and it caused issues during login.
2. There is a new utils that has all the functions that were shared across signup and login. These now get called within the the buttons.
3. There were general things that seemed to be leftover from previous refactors that I moved and deleted. For example, we were passing in `config( 'apple/google_client_id' )` rather than using it in the button directly where the config was already being called. There were various places that had `triggeredByUser ` that no longer exists but was defaulted to `true`.
4. Added a new component `<LastUsedSocialButton />` that will be utilizing all the buttons and the cookie set in the users browser to determine what button they should see. This is only in place for personal testing and is not being used anywhere yet.

## Why are these changes being made?

This is the last refactor of the login/signup buttons before I use the newly adjusted components to handle the last used login method. In order to simplify this and prevent code duplication across Calypso we needed to move more of the logic into the buttons or utility functions. This will allow us to use the login buttons in a simpler and more consistent manner.

## Testing Instructions

These should all be tested from localhost. I have been using the mocked WordPress.com version
We need to be testing Apple, Google, and GitHub for each of them.

### SIGNUP

[WooCommerce](https://wordpress.com/start/wpcc/oauth2-user?ref=oauth2&oauth2_redirect=https%3A%2F%2Fpublic-api.wordpress.com%2Foauth2%2Fauthorize%2F%3Fresponse_type%3Dcode%26client_id%3D50916%26state%3Dc92cfd0e05c2bf6e176a5ed1fbf185a99cf22a08cddf2bd631e1362b240d24f1%26redirect_uri%3Dhttps%253A%252F%252Fwoo.com%252Fwc-api%252Fwpcom-signin%253Fnext%253D%25252Fstart%25252F%252523%25252Finstallation%2526source%253Dsignup_menu%26blog_id%3D0%26wpcom_connect%3D1%26wccom-from%26calypso_env%3Dproduction%26jetpack-code%26jetpack-user-id%3D0%26action%3Doauth2-login%26from-calypso%3D1&oauth2_client_id=50916)
[Jetpack CLoud](https://wordpress.com/start/wpcc/oauth2-user?oauth2_client_id=69040&oauth2_redirect=https%3A%2F%2Fpublic-api.wordpress.com%2Foauth2%2Fauthorize%3Fresponse_type%3Dtoken%26client_id%3D69040%26redirect_uri%3Dhttps%253A%252F%252Fcloud.jetpack.com%252Fconnect%252Foauth%252Ftoken%253Fnext%253D%25252F%26scope%3Dglobal%26blog_id%3D0)
[Crowdsignal](https://wordpress.com/start/crowdsignal/oauth2-name?oauth2_client_id=978&oauth2_redirect=https%3A%2F%2Fpublic-api.wordpress.com%2Foauth2%2Fauthorize%3Fclient_id%3D978%26response_type%3Dcode%26blog_id%3D0%26state%3D51d5e1b0d7358dee3de65c45f4b4dc37a3d6e37dab8d6047545f636c2659d104%26redirect_uri%3Dhttps%253A%252F%252Fapp.crowdsignal.com%252Fconnect%253Fsource%253Dlogin%2526action%253Drequest_access_token%26wpcom_connect%3D1)
[P2](https://wordpress.com/start/p2/user)
[WordPress](https://wordpress.com/start/user-social)
[WordPress - ES](https://wordpress.com/start/user-social/es)
[VideoPress](https://wordpress.com/start/videopress-account/user)
[WordPress Hosting](https://wordpress.com/start/hosting/user-social)

### LOGIN

[WordPress - ES](https://wordpress.com/log-in/es)
[WordPress](https://wordpress.com/log-in)
[P2](https://wordpress.com/log-in?redirect_to=https%3A%2F%2Fwordpress.com%2Fstart%2Fp2%2Fp2-confirm-email&from=p2&signup_url=%2Fstart%2Fp2%2Fuser)
[Jetpack](https://wordpress.com/log-in/jetpack?site=https%3A%2F%2Ffalse-shrike.jurassic.ninja)
[Crowdsignal](https://wordpress.com/log-in?client_id=978&redirect_to=https%3A%2F%2Fpublic-api.wordpress.com%2Foauth2%2Fauthorize%3Fclient_id%3D978%26response_type%3Dcode%26blog_id%3D0%26state%3D51d5e1b0d7358dee3de65c45f4b4dc37a3d6e37dab8d6047545f636c2659d104%26redirect_uri%3Dhttps%253A%252F%252Fapp.crowdsignal.com%252Fconnect%253Fsource%253Dlogin%2526action%253Drequest_access_token%26wpcom_connect%3D1)
[Jetpack Cloud](https://wordpress.com/log-in?client_id=69040&redirect_to=https%3A%2F%2Fpublic-api.wordpress.com%2Foauth2%2Fauthorize%3Fresponse_type%3Dtoken%26client_id%3D69040%26redirect_uri%3Dhttps%253A%252F%252Fcloud.jetpack.com%252Fconnect%252Foauth%252Ftoken%253Fnext%253D%25252F%26scope%3Dglobal%26blog_id%3D0)
[WooCommerce](https://wordpress.com/log-in?redirect_to=https%3A%2F%2Fpublic-api.wordpress.com%2Foauth2%2Fauthorize%2F%3Fresponse_type%3Dcode%26client_id%3D50916%26state%3Dc92cfd0e05c2bf6e176a5ed1fbf185a99cf22a08cddf2bd631e1362b240d24f1%26redirect_uri%3Dhttps%253A%252F%252Fwoo.com%252Fwc-api%252Fwpcom-signin%253Fnext%253D%25252Fstart%25252F%252523%25252Finstallation%2526source%253Dsignup_menu%26blog_id%3D0%26wpcom_connect%3D1%26wccom-from%26calypso_env%3Dproduction%26jetpack-code%26jetpack-user-id%3D0%26action%3Doauth2-login%26from-calypso%3D1&client_id=50916&signup_url=%2Fstart%2Fwpcc%2Foauth2-user%3Fref%3Doauth2%26oauth2_redirect%3Dhttps%253A%252F%252Fpublic-api.wordpress.com%252Foauth2%252Fauthorize%252F%253Fresponse_type%253Dcode%2526client_id%253D50916%2526state%253Dc92cfd0e05c2bf6e176a5ed1fbf185a99cf22a08cddf2bd631e1362b240d24f1%2526redirect_uri%253Dhttps%25253A%25252F%25252Fwoo.com%25252Fwc-api%25252Fwpcom-signin%25253Fnext%25253D%2525252Fstart%2525252F%25252523%2525252Finstallation%252526source%25253Dsignup_menu%2526blog_id%253D0%2526wpcom_connect%253D1%2526wccom-from%2526calypso_env%253Dproduction%2526jetpack-code%2526jetpack-user-id%253D0%2526action%253Doauth2-login%2526from-calypso%253D1%26oauth2_client_id%3D50916)
[Mailpoet](https://wordpress.com/log-in?client_id=79002&redirect_to=https%3A%2F%2Fpublic-api.wordpress.com%2Foauth2%2Fauthorize%3Fresponse_type%3Dcode%26redirect_uri%3Dhttps%253A%252F%252Faccount.mailpoet.com%252Flogin%252Fwpcom%252Fcallback%26scope%3Dauth%26client_id%3D79002)

### CODE REVIEW

**Review by escapemanuele — APPROVED** [review]
A big change, wow!

I left a couple of things that will need to be looked at, while I continue testing

**Review by escapemanuele — CHANGES_REQUESTED** [review]
Approved by error!

**Comment by renancarvalho** [comment]
Just to keep track of this one, we've found when huddling

- Using apple sign up on video press

image

**Comment by arcangelini** [comment]
Fixed the notice...

Screen Shot 2024-08-26 at 14 15 01

**Review by heavyweight — APPROVED** [review]
Tested and didn't find any issues.
Maybe we wait for one more approval on this one?

**Pull request merged**
