### PR TITLE
(Do not merge) Rename FSE plugin

### PR DESCRIPTION
**Pull request by noahtallen**
#### Changes proposed in this Pull Request
* Rename FSE plugin to "WordPress.com Editing Experience"
* Change directory from `apps/full-site-editing/full-site-editing-plugin` to `apps/wpcom-editing-experience/plugin`
* Rename `full-site-editing-plugin.php` to just `index.php`
* Update all build/dev tooling to point to new directory

#### Testing instruction

Note: you must now use `npx lerna run dev --scope='@automattic/wpcom-editing-experience' --stream` to build the plugin

1. All CircleCI stuff should work as expected
2. Smoke test everything
3. Search for mentions of FSE in the codebase and see if I missed anything

Wpcom: apply D36573-code and use `./bin/calypso/build-wpcom-editing-experience $job_id 0.18` with the job ID from _build-wpcom-editing-experience_ in the circle CI build

### CODE REVIEW

**Comment by noahtallen** [comment]
I spent some time thinking about deployment order for all the renaming, and came up with this:

Deployment order for main plugin:
1. Merge wp-calypso update
2. Create version bump PR
3. SVN: new build script, new folder for editing experience
4. SVN: version bump diff to new folder
5. SVN: Update mu-plugins loader file to load the version in the new editing experience folder.
6. SVN: delete everything in full-site-editing-plugin except for the root php file.


Mu-plugins (should not change what plugin is loaded). Can happen at any point.
1. SVN: duplicate mu-plugins/full-site-editing files to wpcom-editing-experience folder also duplicate full-site-editing.php to wpcom-editing-experience.php and deploy (make sure having two files won’t be problematic. It shouldn’t be.)
2. SVN: Deploy wpcom-editing-experince.php with paths pointing to the editing experience folder and delete full-site-editing.php
3. SVN: Delete full-site-editing folder.

**Comment by Copons** [comment]
> Rename full-site-editing-plugin.php to just index.php

It's convention to name the main plugin file like the plugin itself: `wpcom-editing-experience.php`.
I'm not entirely sure it's an actual _requirement_, in the sense that the main file _needs_ to be named like that to work. 🤔 

I wonder if it would be easier to have a simplified structure with one less folder:

```
/wpcom-editing-experience
    /bin
    /test

    /full-site-editing
    /global-styles
    /all-other-plugins...

    /node_modules
    package.json
    all-build-configs.js...

    readme.txt
    wpcom-editing-experience.php
```

To keep the sync procedure simple, we would have a whitelist of folders (e.g. `[ 'full-site-editing', 'global-styles' ]` in order to exclude the unnecessary stuff.
All new plugins would need to be added to the whitelist, but I don't expect this to happen very often.

**Comment by noahtallen** [comment]
> It's convention to name the main plugin file like the plugin itself: wpcom-editing-experience.php.

Gotcha. I don't like it because the path is disgusting, but if that's convention I guess we can go with it 😄

**Comment by noahtallen** [comment]
> I wonder if it would be easier to have a simplified structure with one less folder:

Yeah, that actually makes a lot of sense to me. I'll try to figure out how to make it work.

> To keep the sync procedure simple, we would have a whitelist of folders 

IMO this bit should be done outside of the rename since the rename already involves a lot of code 😋 I would just keep the build as similar as possible

**Comment by Copons** [comment]
> > I wonder if it would be easier to have a simplified structure with one less folder:
> 
> Yeah, that actually makes a lot of sense to me. I'll try to figure out how to make it work.

Wait for some other opinions though, I'm usually bad at structuring folders 😄 

> > To keep the sync procedure simple, we would have a whitelist of folders
> 
> IMO this bit should be done outside of the rename since the rename already involves a lot of code 😋 I would just keep the build as similar as possible

Well, if we end up changing the folder structure we also need to tell Circle to create artifacts from each sub-plugin folder, instead of just grabbing `full-site-editing-plugin` as a whole. 🤔

**Comment by noahtallen** [comment]
> Well, if we end up changing the folder structure we also need to tell Circle to create artifacts from each sub-plugin folder, instead of just grabbing full-site-editing-plugin as a whole

🙅‍♂

**Comment by noahtallen** [comment]
Closing since this has gobs of conflicts. We can reference this in the future to see the different things which would need changed

**Pull request closed without merging**
