### PR TITLE
Layout: match Masterbar height on the front-end / wp-admin

### PR DESCRIPTION
**Pull request by Visovsiouk**
Changed the `$masterbar-height` and the subsequent affected sub items as discussed in (#18561), so it would reflect the layout in front-end. However, I did not adjust anything on the <480px breakpoint, as it would brake the overall layout logic.

### CODE REVIEW

**Comment by lsinger** [comment]
Cool, @Visovsiouk! That's good to see. I've labeled your PR with "[Status] In Progress" so everyone knows it's not done. When you feel like you're done, feel free to ping me and change the "Status" label to "[Status] Needs Review" and "[Status] Needs Design Review". 

Here are two improvements that could still be made:

When you have drafts for the current site, the number of drafts will show next to the "Write" button and reveal a menu for easy access to the drafts. The height is still off here:

screen shot 2017-10-17 at 8 29 31 am

The whole content area I think still needs to move up. It's especially visible looking at the sidebar with its different background color: 

screen shot 2017-10-17 at 8 29 36 am

**Comment by Visovsiouk** [comment]
@lsinger Fixed the issues you mentioned, but cannot change the labels accordingly.

**Comment by lsinger** [comment]
Pinging @shaunandrews.

**Comment by vindl** [comment]
cc @folletto @drw158

**Comment by folletto** [comment]
I'm not in favor of this change, so I don't think I should be one reviewing for this one.

**Comment by vindl** [comment]
> I'm not in favor of this change, so I don't think I should be one reviewing for this one.

@folletto FWIW I prefer the current version too. If anything, I think we should adjust the front-end facing masterbar to conform to Calypso.

**Comment by folletto** [comment]
This seems a small change (and I agree it would be ideal) but it's a massive discussion with lots of consequences. 

To mention one: it's a big undertaking as it would need to fix all the themes. Also, would break from Core's, which will mean permanent extra maintenance. It's not an easy problem.

**Comment by drw158** [comment]
The masterbar is more usable at a larger size (the current size). Easier to click.

**Comment by lsinger** [comment]
We've decided to not go forward with this one for now. Sorry @Visovsiouk! Closing.

**Pull request closed without merging**
