### PR TITLE
Build: Update Node to 8.9.4

### PR DESCRIPTION
**Pull request by gwwar**
This PR updates Calypso to node v8.9.4. This brings us to the [latest of the Carbon LTS line](https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V8.md#8.9.4).

### Local Dev
- Switch to node version 8.9.4 (npm 5.6.0)
- `npm run distclean`
- `npm start`
- No functional changes to Calypso
### Local Docker Image
- Follow image instructions at: PCYsg-5XR-p2 or
- Setup docker locally and add the following host entry:
  ```
  127.0.0.1 wpcalypso.wordpress.com
  ```
- `npm run build-docker`
- `npm run docker`

### Desktop
- Clone the wp-desktop project
- Follow install instructions
- In the calypso submodule checkout this branch
- Desktop behaves normally

### CODE REVIEW

**Comment by gwwar** [comment]
Is Desktop being super strict now? 

> Unsupported engine for WordPressDesktop@3.1.0: wanted: {"node":"8.9.3","npm":"5.5.1"} (current: {"node":"8.9.4","npm":"5.6.0"})

**Comment by gwwar** [comment]
Smoke tested in Docker/local 👍

**Comment by gwwar** [comment]
Thanks for the review @sirreal!

@astralbodies should we make the Node version check in desktop a bit more lenient, or should I spin up Desktop Node bump PR in tandem?

**Comment by astralbodies** [comment]
@gwwar You can get the canary to pass if you create a branch of an identical name in wp-desktop, update the calypso branch to point at yours and then remove/add the needs review label. The canary should then re-run using your wp-desktop branch instead of develop!

**Pull request merged**
