### PR TITLE
VideoPress Onboarding: Add style to choose a domain step filters

### PR DESCRIPTION
**Pull request by thedebian**
#### Proposed Changes

This PR add style to choose a domain step filters.
@evilluendas don't hesitate to give your opinion on this one, I can update accordingly, here is a screenshot: 
Capture d’écran 2023-01-03 à 11 29 48

#### Testing Instructions

* Apply PR
* Go to /start/videopress
* Follow the onboarding flow until choose a domain
* Click on "filter"
* ✅ The popup should be stylized

Fixes Automattic/greenhouse#1430

### CODE REVIEW

**Review by jgcaruso — APPROVED** [review]
Css changes look good and the filter component still works as expected. Filter look match the screenshot, but the mix of black and grey just looks a little "off" to my non-designer eye. Not sure what can be done though, it can always be tweaked later if necessary I suppose now that this base work to style it has been done.

**Comment by evilluendas** [comment]
Nice! I think I'd make the background slightly darker than the boxes below but not as dark as the background (I'm using `#161616` in the screenshot), and then make the background of the list not as dark (`#111` here) with a lighter border (`#333`).

image

I'd also make the border of the token and the X inside a bit more transparent, and the text itself (`.com`) completely white. The border of the "Clear" button is also lighter, like the secondary buttons in the background.

It's a bit hard to see where the box ends when seen in a static screenshot, but I think it's more discernible when you open it yourself clicking the button. Otherwise, we can make the background brighter than the boxes and lift all the grays a bit so there's more contrast, or make the shadow behind brighter (although I don't like that, generally it makes UIs feel a bit muddy)... or even just leave the white background as it is by default.

Here's how it looks making the shadow brighter:

image

**Comment by thedebian** [comment]
@evilluendas Here is how it looks like now
Capture d’écran 2023-01-16 à 09 58 24

**Comment by thedebian** [comment]
@evilluendas Here is how it looks like now :

Capture d’écran 2023-01-16 à 10 09 31

**Review by evilluendas — APPROVED** [review]

**Pull request merged**
