### PR TITLE
Invites: Improve invalid invite messages

### LINKED ISSUE #4065: People: Make invalid invite errors more understandable
It's been reported to me several times that users are having an issue with the invalid invite message that shows when we pre-validate an invite.

I think the big issue here is that we show a generic error message for several flows. For example, a user will see the same error for copying/pasting incorrectly as accepting an invite that they sent to themself.

This leads to confusion for users and surely makes invites more difficult to support for HEs. Let's be nice.

cc @darnelldibbles who is the latest HE to report this to me.

### PR DESCRIPTION
**Pull request by ebinnion**
Closes #4065.

After being pinged me a few times due to confusing invalid invite error messages, it's time that we make the messages reflect why the invite is invalid, instead of returning a generic message.

To test:
- Checkout `update/invite-accept-errors` branch
- Proxy and send an invite to yourself
  - Unproxy and try to accept the invite
- Send an invite to a test user
  - In the invite URL, change the blog ID
- On a blog that you're already a member of, send an (editor | author | admin) invite to an email you control
  - Open that invite while logged in
- Follow the same step for a site you're already following with a follower invite

### CODE REVIEW

**Comment by ebinnion** [comment]
Here are some screenshots:

screen shot 2016-03-16 at 11 33 47 am

screen shot 2016-03-16 at 11 34 37 am


screen shot 2016-03-16 at 11 31 45 am

screen shot 2016-03-16 at 11 31 08 am

**Comment by rickybanister** [comment]
Those all sound much improved. Nice work @ebinnion, we'll make a copywriter of you yet.

The only change I'd suggest is to say 'that invite is not valid' for the two appropriate errors instead of 'your invite'. 'That' feels more accurate since the error displays because it was not meant for the current user.

**Comment by lezama** [comment]
Looks good code wise :+1:

**Comment by ebinnion** [comment]
Thanks for the reviews. I updated the default wording to use "that invite" instead of "your invite".

**Pull request merged**
