### PR TITLE
Fix E2E tests for Gutenberg 6.4.0

### PR DESCRIPTION
**Pull request by mmtr**
Amend the E2E tests to work with the Gutenberg 6.4.0 upgrade.

### CODE REVIEW

**Comment by mmtr** [comment]
@kwight all the found regressions have been fixed ini Gutenberg, so let's run the e2e test again tomorrow after updating Horizon to the stable release

**Comment by mmtr** [comment]
One of the tests is failing because the publish sidebar is automatically closed after publishing a post:

Aug-30-2019 09-54-17

The test needs that sidebar to be opened in order to get the post link from the "_Post title_ is now live." message:

Screen Shot 2019-08-30 at 09 57 31

Seems to be caused by the editor being in an `isDirty` state after publishing the post ([Gutenberg closes the sidebar automatically if the post contains unsaved changes](https://github.com/WordPress/gutenberg/blob/02c5f3950dda05ffbba532d285e58be9232c0acf/packages/editor/src/components/post-publish-panel/index.js#L37-L39)).

I confirmed this doesn't occur on a self-hosted site, so I guess it's related to the WP.com integration. But somehow this is happening only in Horizon, so it's either caused by a change in Gutenberg 6.4.0 or by other plugins we have only active in Horizon (like FSE).

**Comment by mmtr** [comment]
Apparently the dirty state is caused by an extra space added at the end of the `img` tag when saving a post, which is removed by the editor:

Screen Shot 2019-08-30 at 10 40 52

**Comment by mmtr** [comment]
I verified the extra whitespace is also added on production by the server and removed by the editor, but Gutenberg 6.2.0 (the current version used on prod) ignores that whitespace when checking if the editor is in a dirty state. However, Gutenberg 6.4.0 doesn't ignore that anymore.

The behavior in 6.4.0 seems right to me (any change, even a whitespace should be considered an unsaved change), so we should fix the underlying issue on the server that's adding the extra whitespace. So far, I can confirm that the whitespace is being added by our KSES filter.

**Comment by mmtr** [comment]
Turned out to be an issue in core as well. To reproduce it we need to activate Gutenberg 6.4.0 on a multisite install (or test with a user not having the `unfiltered_html` capability). I reported the issue there: https://github.com/WordPress/gutenberg/issues/17264

In the meantime, I think we can change the E2E tests so the post link is retrieved from the snackbar notice.

**Comment by kwight** [comment]
> Timed out waiting for element with css selector of 'span.is-saved' to be present and displayed

I noticed on my sandbox test site the `saved` button appears for a split second before turning to `save draft` again, which might explain something like this? It only happened on my sandbox (FSE-enabled) site though, and not on other regular test sites.

> Timed out waiting for element with css selector of '.editor-post-publish-panel__header' to be present and displayed

Couldn't replicate (the element appeared fine when publishing a password-protected page).

> The post is not set as draft

This may be a selector mismatch; `gHeaderComponent.revertToDraft()` is looking for `button.edit-post-status__revert-to-draft`, but it looks like the element is now button.components-button editor-post-switch-to-draft`.

**Comment by mmtr** [comment]
Alright, seems the last commit fixed the "revert to draft" test (it wasn't a selector problem after all, we just needed to wait a bit more for the needed elements to be present).

All the remaining failing tests look related to the already known `invalid session id`/`session deleted because of page crash` issues that are being worked on by @Automattic/e2e-test-reviewers, so I'd say Gutenberg 6.4.0 is good to go.

**Comment by kwight** [comment]
We've deployed a custom build of 6.4.0 to Horizon that includes https://github.com/WordPress/gutenberg/pull/17317 (shows as `6.4.0-a8c` in `wpcomGutenberg.pluginVersion`).

**Comment by kwight** [comment]
We'll be skipping 6.4 paYKcK-fj-p2

**Pull request closed without merging**
