### PR TITLE
Jetpack Onboarding: update intro messaging

### PR DESCRIPTION
**Pull request by keoshi**
#### Changes proposed in this Pull Request

* Jetpack Onboarding: update intro messaging to be more Security and Performance focused.
* `Boost your WordPress site with Security, Performance, and Customization features all in one service.` => `High performance. Solid security. Your site, just better.`

#### Testing instructions

* Fire up this PR.
* Try adding a new Jetpack site or go to `/jetpack/connect/site-type/SITE_URL`.
* Check if the title on the site type step is correct.

#### Before

wordpress com_jetpack_connect_site-type_mutelife com(Calypso)

#### After

image

Fixes https://github.com/Automattic/wp-calypso/issues/31354

### CODE REVIEW

**Comment by michelleweber** [comment]
Am I allowed to say that I don't love "boost," because it doesn't really say anything about what happens to your site, and we use it in a funny way -- "boost your site" is kind of an odd phrase that doesn't communicate much. 

So! The copy is technically fine as-is except that "Security" and "Performance" shouldn't be capitalized because they're not being used as proper nouns in this case, but I would love it if we could go super simple and direct: "High performance. Solid security. Your website, just better." or "Better performance, better security, a better website," or "Your website, more efficient and secure."

**Comment by keoshi** [comment]
> Am I allowed to say that I don't love "boost"

Of course! And I should say I’m not a fan either but wanted to get something going to start the discussion. 

I absolutely love your first suggestion, Michelle! Will make those changes tomorrow morning. Thank you so much!

**Comment by keoshi** [comment]
I've updated the copy in the title as per @michelleweber's suggestion, but I wasn't a fan of how the tagline was breaking on larger screens (see below), so I've made a small tweak: `website` is now `site`. This also aligns to the rest of the page, where we're using the `site` term.

image

image

If that's ok with you, Michelle, I'll go ahead and merge this, since it's a simple string update.

**Comment by michelleweber** [comment]
Works for me!

**Comment by shaunandrews** [comment]
I can appreciate shortening the copy down, but I question its existence at all now. Its three tiny sentences jammed into a single line. It reads awkwardly, and visually competes with the step title.

If we do want to keep it, I think we could make some more tweaks to the copy and use hierarchy to help keep the focus on the step title — which is the instructions most important for completing the step.

Here's a quick idea:

image

**Pull request merged**
