### PR TITLE
Me: Remove LinkedStateMixin where obsolete

### PR DESCRIPTION
**Pull request by ockham**
While these components are using `valueLink`, they're using a custom handler instead of `this.linkState()`, so they don't actually make use of `LinkedStateMixin`. (FWIW, I couldn't find any such cases outside `/me`.)

Quoting from #5951:

>  Note that some of our components have been importing the `LinkedStateMixin` even though they weren't really using `this.linkState()`but only `valueLink`. Those are two separate things: `valueLink` is a custom prop added to `input` by React which will be removed as of React 16. It can be used with `LinkedStateMixin` (through the `linkState()` method which the latter provides), but also without. See https://facebook.github.io/react/docs/two-way-binding-helpers.html for different ways to implement the same functionality.

Code review:
* Verify that the affected files don't refer to `this.linkState()`, and that any `valueLink` props are set to custom handlers instead.

To test:
* Verify that the affected components still work.

### CODE REVIEW

**Comment by jsnajdr** [comment]
@ockham Do you think it's a good idea to also remove the usage of `valueLink` from `formBase`-based components in this PR? I've been intending to do that for some time.

**Comment by jsnmoon** [comment]
Pushed up a lint fix commit.

**Comment by ockham** [comment]
> @ockham Do you think it's a good idea to also remove the usage of `valueLink` from `formBase`-based components in this PR? I've been intending to do that for some time.

It's definitely a good idea 😁 Just tackling `LinkedStateMixin` in this PR seemed like a quicker win, since getting rid of `valueLink` will require more manual intervention (some of those are propagated thru `Form...` components; there's even a custom `checkedLink` somewhere :roll_eyes: ). Which is why I opted to do it piecemeal. 😄

**Comment by ockham** [comment]
As discussed with @jsnmoon in Slack, I'm going to drop the `eslint-disable` bits even tho that means CircleCI will go red on us. I think it's okay for eslint to remind us that we have some legacy/deprecated code there that we should get rid of eventually.

**Comment by tyxla** [comment]
Awesome cleanup  ❤️

**Pull request merged**
