### PR TITLE
Try/codemods/mass client codemod

### PR DESCRIPTION
**Pull request by sirreal**
Just an exploratory PR for massively codemodding `client`.

I tweaked `runmods.sh` a bit in 763dd2b before running.

I manually edited a few files in d90b681 to stop `prettier` from unquoting `default`, which was causing lint errors.

Related: #18250

### CODE REVIEW

**Comment by samouri** [comment]
@sirreal: i looked into the unquoting issue awhile back. we should remove the eslint rule.  unquoted special chars as keys to an object has a ton of backcompat.

**Comment by sirreal** [comment]
> i looked into the unquoting issue awhile back. we should remove the eslint rule. unquoted special chars as keys to an object has a ton of backcompat.

Let's do this!

**Comment by sirreal** [comment]
This exploration has served its purpose.

**Comment by samouri** [comment]
unquoting issue: https://github.com/Automattic/eslint-config-wpcalypso/pull/11

**Pull request closed without merging**
