### PR TITLE
State: Move themes action types out

### PR DESCRIPTION
**Pull request by tyxla**
This PR moves the theme action types out of the monolithic file with action types. This won't bring immediate results in reducing size of main entry point, because there are still other pieces of state that are using these action types (sites, UI, notices), but once those are also modularized, the effect will be even bigger!

#### Changes proposed in this Pull Request

* State: Move themes action types out

#### Testing instructions

* Verify that the "themes" functionality works well both when logged in and logged out.

### CODE REVIEW

**Review by noahtallen — APPROVED** [review]
Thanks, @tyxla! This is great. All of the code makes sense to me. I also tested the `themes` page both logged in and logged out. All of the interactions worked as I expected, and themes appear to activate correctly. FSE and Gutenberg-related flows also work correctly. I'm not all that familiar with the changes to automated transfer or notices, but everything else looks good!

**Review by sgomes — APPROVED** [review]
LGTM, sorry for the delay!

I find it odd how moving the action types out appears to increase the size of the entry points, but I guess that's down to quirks in webpack heuristics. In any case, I'm more than ok with these numbers 👍

**Comment by tyxla** [comment]
Thanks @sgomes and @noahtallen!

Could I get another ✅ ? I had to rebase this one after landing #39724.

**Comment by sgomes** [comment]
Code still LGTM, and the build still works 👍 ✅ 🚢

**Pull request merged**
