### PR TITLE
Framework: bump social-logos to 1.0.1

### PR DESCRIPTION
**Pull request by gwwar**
Pairs with https://github.com/Automattic/social-logos/pull/43 to update the social-logos npm dependency. In 1.0.1 we remove the `classname` peer dependency and use the component example from the package.

### Testing
- No functional changes
- Social Logos should appear correctly in http://calypso.localhost:3000/devdocs/design/social-logos
- On http://calypso.localhost:3000/sharing/:siteId:
- In Publicize

## Tasks
- [x] Land and publish https://github.com/Automattic/social-logos/pull/43
- [x] Bump to 1.0.1 instead of alpha before merging

cc @aduth @lamosty @retrofox

### CODE REVIEW

**Comment by aduth** [comment]
Works well tested with https://github.com/Automattic/social-logos/pull/43 👍

**Comment by gwwar** [comment]
I updated the PR to point at the final 1.0.1 version of social-logos. This branch is now ready for another 👀

**Comment by gwwar** [comment]
> I can confirm that the changes here work well though, and perhaps would be fine to continue cleaning above worries in a separate pull request.

I'd think it'd be fine to follow up on this in another PR, since I'd need to publish another version anyway to correct this.

Looks like there's decent support for [currentColor](http://caniuse.com/#feat=currentcolor) we could inline the style in the component, or export a css file in the npm package.

Any opinions here @mtias @jasmussen @folletto @drw158 ?

**Comment by gwwar** [comment]
cc @artpi and @gziolo to verify publicize icons look ok

**Comment by gziolo** [comment]
I can confirm that Facebook, LinkedIn, Twitter and Google Plus work properly :)

**Comment by folletto** [comment]
> Looks like there's decent support for currentColor we could inline the style in the component, or export a css file in the npm package.
 
I'm not entirely sure I can give at this time an informed answer. How is Gridicons dealing with that? In theory the two things should be identical in architecture... ^^'


> There's only a single style in that file, to assign the color of the icon to the current text color. Is this something that should be included in the npm package (either as stylesheet or inlined style)?

The only comment I can make in abstract is that I would find weird for the package to inline a Calypso color in a generic NPM package — but maybe I misunderstood the suggestion. :)

**Comment by aduth** [comment]
`fill: currentColor` isn't really a Calypso-specific style. It's essentially saying: "treat the coloring of this SVG as though it were text by inheriting the parent's text color". Still overridable if need be, but a pretty safe default imo.

**Comment by folletto** [comment]
Thanks! Now I connected the details again. :D
 
Is there any elegant way to include `fill: currentColor` in the NPM package for both social logos and Gridicons?

**Comment by aduth** [comment]
I think it was mentioned elsewhere, but given that the workflow between `social-logos` and `gridicons` is nearly identical, ideally we could consolidate the build tooling to ensure that they're consistent in what's generated.

**Comment by gwwar** [comment]
> Is there any elegant way to include fill: currentColor 

Since there's only a single rule here, I'd probably say add this as an inline style unless we're concerned about the higher CSS specificity, otherwise we can add the css file in the npm package.

> ideally we could consolidate the build tooling to ensure that they're consistent in what's generated.

I'm planning on updating GridIcons once we have a good model here. Next pieces would be: choose how to bundle any specific component styles, and adding a component test and ci loop to the social-logos repo directly

**Comment by gwwar** [comment]
Thanks for the reviews! I'll go ahead and merge this one and follow up in social-logos to deal with exporting that single css rule.

**Pull request merged**
