### PR TITLE
theme-showcase: seller-upgrade: WooCommerce theme specific upsell

### PR DESCRIPTION
**Pull request by mreishus**
#### Proposed Changes

* When browsing the theme showcase with seller-upgrade-modal on, update the upsell message for themes with plugins bundled. They will now be called "WooCommerce themes", and the message will indicate that they need to upgrade to business, not premium.  The reference to individual purchase is removed.

**Before PR**

**After PR**

There are a lot of changes that need to be done in the showcase. Trying to do small steps.

**Are we OK with the branding of "WooCommerce themes"?** Internally, we've been calling them "bundled themes", but a user won't know what that is.

#### Testing Instructions

* Use calypso localhost or an environment where `themes/plugin-bundling` is turned on
* Manually turn on `signup/seller-upgrade-modal` by editing `config/development.json` or add `?flag=signup/seller-upgrade-modal` to your urls
* Visit `http://calypso.localhost:3000/themes/YOURFREESITE?flags=signup/seller-upgrade-modal` or simply `http://calypso.localhost:3000/?flags=signup/seller-upgrade-modal` then navigate to Appearance->Themes
* Make sure you are on a free site
* Search for baxter, the only theme that has a bundled plugin
* Note the difference in the upsell messaging when hovering over the star
* The other premium themes should have unchanged upsell messaging 

Related to #

### CODE REVIEW

**Comment by mreishus** [comment]
Saxon said showing as WooCommerce is good for now: p1662339947934069/1662148534.112419-slack-C0Q664T29

**Review by markbiek — APPROVED** [review]
LGTM!

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/7513539

Thank you @mreishus for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/7513539).

**Pull request merged**
