### PR TITLE
Desktop manual check for updates

### PR DESCRIPTION
**Pull request by nsakaimbo**
### Description

This PR adds a manual "Check for Updates" menu item. If an update is available, this feature will follow the established updater flow for each platform (download and install on Mac, Windows; and navigate to WordPress Desktop homepage for Linux). If an update is not available, an "Update not available" dialog is displayed to the user.

<p align="center">
check-for-updates-menu
<br>
check-for-updates-update-available
<br>
check-for-updates-no-update
</p>

### To Test

Build and run this branch and amend the version number in `desktop/package.json` to verify behavior for update available/not available. (When testing locally, don't forget to set `CONFIG_ENV === release`.),

### CODE REVIEW

**Comment by mokagio** [comment]
@nsakaimbo hey there 👋 

I've been trying to test this, but I can't get it to build.

From the `desktop/` directory, I tried `make build` and it fails with:

```
Config file config/secrets.json does not exist. Please create one.
```

I tried `make config`. It failed with the same error.

I took my chances and `cp config/empty-secrets.json config/secrets.json` from the repo root. The failure changed to 

```
desktop_oauth_client_id must be 43452 in secrets.json in release build
```

From what I can see, I need to have some secrets in my repo. I can see CI decrypts some stuff too, by I don't have that key.

What can I do to get past this?

**Comment by nsakaimbo** [comment]
Hi, @mokagio! Thanks for helping test!

Hopefully these steps should help:

1. Generate correct secrets.json with: `openssl aes-256-cbc -md md5 -d -in desktop/resource/calypso/secrets.json.enc -out config/secrets.json -k "${CALYPSO_SECRETS_ENCRYPTION_KEY}"` [as we do in Circle](https://github.com/Automattic/wp-calypso/blob/59a8324698080382bcc3805e32ba55550a9f64ba/.circleci/config.yml#L194) (we need better documentation for this, or a separate item in the Makefile to generate these keys)
2. `export CONFIG_ENV=release`
3. `make -f desktop/Makefile config`
4. `yarn run build-desktop` to build the app

**Comment by nsakaimbo** [comment]
Update: just opened PR #45856 that adds a convenience script to generate the app secrets.

**Review by mokagio — APPROVED** [review]
Built on `HEAD`, got this

image

Changed the version to `5.0.0` and clicked "Check for Updates...", got this

image

So, all good 👍 

A refinement suggestion for another day, maybe it was my network connection, but it took a while between me clicking the menu item and the sheet being presented. Maybe we could have a loading UI, to let the users know _something_ is happening?

**Comment by mokagio** [comment]
This is probably related to me opening the WordPress binary from the `.dmg` a few times and not closing it properly before trying out a new version, but I just noticed my Mac was super slow (the fans were also about to fly away, but I had my headphones on and didn't notice) and the reason turned out to be this

Screen Shot 2020-09-23 at 11 47 05 am

Look at the CPU load drop once I killed those "WordPress.com Helper (Renderer)" processes:

image

**Comment by nsakaimbo** [comment]
> A refinement suggestion for another day, maybe it was my network connection, but it took a while between me clicking the menu item and the sheet being presented. Maybe we could have a loading UI, to let the users know something is happening?

This is a good observation and I had the same thought. As an improvement, hopefully there's some sort of spinner or loading-indicator element in Calypso we can use to let provide the user more feedback.

**Comment by nsakaimbo** [comment]
Re: the CPU usage of the Desktop app - I haven't encountered this before, but I wouldn't be terribly surprised as Calypso (renderer process) itself is fairly heavy. Definitely something we're going to want to take a look at, sooner rather than later.

**Comment by mokagio** [comment]
@nsakaimbo in regards to the update. If the Calypso route doesn't work, we could always do something native like [Sparkle](https://sparkle-project.org/) does:

**Pull request merged**
