### PR TITLE
Components: Unify Gridicon styles within LoggedOutFormLinkItem

### PR DESCRIPTION
**Pull request by tyxla**
This PR unifies the `Gridicon` styles within `LoggedOutFormLinkItem`. This combination occurs mostly within the Jetpack Connect flow, once in the disconnection flow and only in one instance in the signup with store flow.

In order to keep everything consistent, the PR adds necessary `size` to `Gridicon` instances where previously we were resizing them with CSS, and adds spaces after icons where necessary to align them all properly.

This PR helps resolve issues like this one: https://github.com/Automattic/wp-calypso/pull/19327#issuecomment-340787245

To test:
* Checkout this branch
* Verify gridicons in footer links are properly aligned vertically and horizontally while testing each step of the following flows:
  * Go through all steps of the /jetpack/connect flow
  * Go through all steps of the /jetpack/connect/store flow
  * Go to /start/store/design-type-with-store and click on "Start with an online store"
  * Go to /settings/disconnect-site/:site

### CODE REVIEW

**Comment by ockham** [comment]
There are two failing tests :slightly_frowning_face:

**Comment by ockham** [comment]
Talk about timing 😄

**Comment by tyxla** [comment]
Yup, just updated the snapshots and waiting for CI again.

**Comment by tyxla** [comment]
Yeah, I agree, but I'll stick to it for the purpose of this PR, because we also have instances of spaces (` `) between two elements on the same line, and these are tricky to find. Would be happy to revisit those in the future.

**Comment by sirreal** [comment]
I updated the snapshots and pushed a commit.

[The snapshot diff](https://github.com/Automattic/wp-calypso/pull/19346/files#diff-3bd25561005c629287e8e9bfb75633c3) looks good according to the changes we'd expect from this changeset.

**Comment by tyxla** [comment]
Thanks @sirreal!

**Pull request merged**
