### PR TITLE
chore(eslint): Enforce import order

### PR DESCRIPTION
**Pull request by scinos**
EXPERIMENT, DO NOT MERGE

#### Changes proposed in this Pull Request

* Turn off `wpcalypso/import-docblock` for packages. No more mandatory `/* External dependencies */` comment blocks.
* Remove all usages of `/** * External dependencies */`, `/** * Internal dependencies */` and similar blocks
* Turn on [`import/order`](https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/order.md)
* Apply auto-fix for `import/order`

The changes were introduced using automated tools:

1. Search instances of `/**\n* External dependencies\n*/` and replace it by an empty line. Same for `Internal dependencies`, `WordPress dependencies`, `Module dependencies` and `Type dependencies`.
2. Run `prettier` to get rid of the extra new lines.
3. Enable `import/order` in `.eslintrc.js` and apply the auto-fix.

#### Next steps

If we like it, decide how to apply this to the repo. We can do one massive PR for all the repo, many small PRs (eg: one per package/dir), or anything in between.

Alternative: there is an improved version of the rule in Gutenberg: https://github.com/WordPress/gutenberg/blob/trunk/packages/eslint-plugin/rules/dependency-group.js. We could adopt that as well. I'm not sure if it will work together with `import/order` to enforce a specific order inside each group.

### CODE REVIEW

**Comment by noahtallen** [comment]
I personally liked having internal/external dependencies separated since it seemed more organized. I also personally don't think that import order is very important in terms of DevX. I wonder what others think though -- I don't know any practical reasons to go either way.

**Comment by scinos** [comment]
My opinion about these rules:

I don’t really care about the `import` order, when I search for a package I either `cmd+click` on the usage to follow the import, or `cmd+f` to find them by name. I don’t get any value from imports being sorted or grouped. This applies to both rules, of course.

What I don’t like is the `wpcalypso/import-docblock` rule, for a few reasons:

* It forces you to write the bad kind of comments: document what is already in expressed in the code (eg: I don’t get any value from a comment saying “internal dependencies”, I can already see they import things using a relative path)
* It doesn’t actually check that your “internal dependencies” are, in fact, internal, the comment can get out of sync (to be fair, this has been fixed in the Gutenberg version).
* It doesn’t have auto-fix, so I have to manually type the doc block over and over again (also fixed in the Gutenberg version).
* It reports the whole file as ‘failing’ potentially covering more useful and relevant eslint errors until I type the docblock.

My guess is that `wpcalypso/import-docblock` was useful when we had package-relative imports (eg: `import foo from 'state/foo'`) as you don't know if `state` is an external dependency or a directory inside `./client`. But that pattern is gone now. Looking at the origin of this rule in Gutenberg (https://github.com/WordPress/gutenberg/pull/716), looks like that was the original intention.

**Review by tyxla — COMMENTED** [review]
Thanks for bringing this up, @scinos. 

Personally, I don’t care much about the docblocks, as long as we’re consistent throughout the codebase. I personally used to see some value in splitting the imports to internal and external, as it made things more readable, but at the same time, more and more of the repo code is in packages now, so it all ends up being external anyway…

Regarding sorted imports, for my brain this improves readability and I prefer having it, it does make the code more readable in my opinion - especially if you scan through code like you diagonally read through a page of a book (that's what I often do). I’ve preferred sorting the imports in my code, but I’m not sure it will be as preferred by all calypso devs, thus I’m not sure enforcing a rule for that would make sense.

In any case, this is worth trying out IMHO but will have to be very short-lived PR.

**Comment by jsnajdr** [comment]
I like the `import/order` sorting more. The docblocks don't add any value subjectively, and I've never seen anything similar used outside the Calypso/Gutenberg universe.

I think it's valuable though to be aligned with Gutenberg standards. Consider proposing the same change there.

Personally, I feel that import ordering affects my devex very little. It just doesn't matter much. But often I find myself instinctively reordering imports in PRs so that local relative ones (`from './foo'`) are at the end and that same directories (e.g., `from 'calypso/state/...'`) are grouped together. So I can't honestly say I totally don't care 🙂

**Comment by scinos** [comment]
Being done in #54448

**Pull request closed without merging**
