### PR TITLE
FSE: G7.2.0 - replace legacy editor- classes with block-editor-

### PR DESCRIPTION
**Pull request by chriskmnds**
#### Changes proposed in this Pull Request

Gutenberg 7.2.0 & 7.3.0 removed legacy `editor-` classes in WordPress/gutenberg#19050 and WordPress/gutenberg#19489. This PR updates references to any legacy classes found in the FSE app.

#### Testing instructions

Not tested yet.

CC @Automattic/cylon

### CODE REVIEW

**Comment by noahtallen** [comment]
I merged in master to avoid fixing conflicts so much for the rebase

**Comment by noahtallen** [comment]
Well, apparently that didn't work for some reason.

**Comment by noahtallen** [comment]
Since I've totally messed this up, I'm creating a new PR: https://github.com/Automattic/wp-calypso/pull/39157

**Comment by chriskmnds** [comment]
> Since I've totally messed this up, I'm creating a new PR: #39157

Haha ok, sounds good. Just make sure these are looked at: https://github.com/Automattic/wp-calypso/pull/39035/commits/bfc2e8be8ce1fa1c58fb8cfcbf9ec24bdd1faded

**Comment by chriskmnds** [comment]
Closing in favour of https://github.com/Automattic/wp-calypso/pull/39157

**Comment by noahtallen** [comment]
I added some comments on https://github.com/Automattic/wp-calypso/commit/bfc2e8be8ce1fa1c58fb8cfcbf9ec24bdd1faded to explain why some of the things weren't copied over

**Comment by noahtallen** [comment]
@chriskmnds Just a heads up that I've done an audit of everything in the FSE plugin (minus the newspack posts block) and all cases where we used the old selectors should be fixed

**Comment by chriskmnds** [comment]
Thanks for keeping this PR and myself informed @noahtallen ! Good job on investigating things.

**Pull request closed without merging**
