### PR TITLE
Domains: Update DNS setup required language to be more user-friendly

### LINKED ISSUE #39939: Domains: Language around DNS fixes could be simplified
Originally brought up in Slack by @amamujee : p1583516414300400-slack-dotcom-manage

signup___creating_a_new_site_notes (1)

"DNS Configuration required" is a bit jargon-y. Could this notice language be simplified to something like, "Set up your domain"?

/cc @Automattic/cobalt and @fditrapani since I know you're working on domains-related flows at the moment!

### PR DESCRIPTION
**Pull request by sixhours**
#### Changes proposed in this Pull Request

* Average user probably doesn't know what DNS means right off. We can make this language more user-friendly with a quick copy update.

**Before**

**After**

Screen Shot 2020-03-16 at 1 23 50 PM

#### Testing instructions

* Switch to this PR.
* Add a subdomain to a domain that is not yet set up properly. You can add any random domain to an account to do this (and just don't set up any DNS for it).
* Note the copy changes.

Fixes #39939

### CODE REVIEW

**Comment by kwight** [comment]
Not a blocker at all, but I've no idea if this phrase should have a period or not.

**Comment by sixhours** [comment]
Marking this on hold until strings get approved/translated. I think we also want to get final approval from domains folks.

**Comment by jancavan** [comment]
Not that big of a deal, but I feel like the CTA "Fix" gives a sense of urgency, or maybe "Complete domain setup" (still a CTA of "Go") gives a sense that something needs to be completed? Not sure if that'll be too long though.

**Comment by michelleweber** [comment]
Which ever phrase you go with (I lean toward "Complete domain setup," fwiw), I'd go no period in this case :)

**Comment by sixhours** [comment]
Good call! I've updated to `Complete domain setup`. :)

**Comment by gwwar** [comment]
This one is no longer blocked, right?

**Comment by sixhours** [comment]
That's correct, although I think we need to wait for translations to come through since the wording is new. Do those go out on Monday?

**Comment by gwwar** [comment]
Progress of translation can be seen if you click on the Details link of the ci/i18n job. @Automattic/i18n are we smart about using old translated strings, or do we need to wait for all to complete?

**Comment by sixhours** [comment]
Looks like we have 6 translations of the new text so far; is there a baseline for when we should deploy this?

**Comment by akirk** [comment]
It should be our 16 languages, most of the 5 are community translations. The first version of the other translations should trickle until tomorrow.

**Pull request merged**
