### PR TITLE
Add docs on how to use the monorepo

### PR DESCRIPTION
**Pull request by blowery**
#### Changes proposed in this Pull Request

* Add docs on how to use the monorepo

### CODE REVIEW

**Comment by simison** [comment]
I like how Gutenberg has a template for `package.json` in their docs:

https://github.com/WordPress/gutenberg/tree/9f5f1c363b6c78e864ab38a662c23ba0da75abf1/packages

**Comment by blowery** [comment]
> I like how Gutenberg has a template for `package.json` in their docs:

That would be a nice touch. Ideally I think we'd have some scaffolding, or handle the builds with a tool like [pika pack](https://github.com/pikapkg/pack).

**Comment by blowery** [comment]
@simison added a sample package.json

**Review by simison — APPROVED** [review]
To me this seems like a great first iteration already; really helpful!

**Comment by simison** [comment]
Oh hai there's a file here too: https://github.com/Automattic/wp-calypso/tree/3803afe7d987e8ebe93e79be350a7cd917a87d56/packages#readme

**Comment by simison** [comment]
>Oh hai there's a file here too: https://github.com/Automattic/wp-calypso/tree/3803afe7d987e8ebe93e79be350a7cd917a87d56/packages#readme

Follow up https://github.com/Automattic/wp-calypso/pull/31203

**Pull request merged**
