### PR TITLE
Jetpack onboarding: Avoid access by index, use zipped array

### PR DESCRIPTION
**Pull request by sirreal**
This PR _zips_ two arrays so that iteration ocurrs over an array of arrays, as opposed to `map` on a single array and expecting the index to match a second array, which seems more fragile.

## Testing
1. Complete the onboarding flow
1. Ensure that the links remain correct.

### CODE REVIEW

**Comment by sirreal** [comment]
Just a suggestion 🙂 

To me, this seems clearer and more robust. I tried the flow and get `…/null/…` rather than the site URL, which may be related to the comment about selectors:

> // If we're not connected, we cannot use selectors from `sites/selectors`.

This should work, but I'm unfamiliar with this project 😅  Feel free to 👎  if you disagree with the changes 🙂

**Comment by ockham** [comment]
Looks familiar 😁 https://github.com/Automattic/wp-calypso/pull/21728/commits/78b5c67951f1150f5abd6b58137ce34f69e002ed

Great minds, huh? :smile:

**Comment by ockham** [comment]
As discussed via DM, I'm kind of a named properties fanboy, so I'd like to go with the object-of-objects approach in https://github.com/Automattic/wp-calypso/commit/78b5c67951f1150f5abd6b58137ce34f69e002ed rather than the array-of-~arrays~tuples approach here. Hope you're okay with that, and kudos for finding and fixing a data structure worthy of improvement! 😄

**Comment by sirreal** [comment]
Perfect!!

**Pull request closed without merging**
