### PR TITLE
composite-checkout: Add Bancontact payment method

### PR DESCRIPTION
**Pull request by sirbrillig**
#### Changes proposed in this Pull Request

This adds the Bancontact Stripe redirect payment method to composite checkout.

#### Screenshots

Old checkout:

old-bancontact

New checkout (closed):

new-bancontact-closed

New checkout (open):

new-bancontact-open

#### Testing instructions

- Apply D45443-code to force Bancontact to be available.
- Sandbox the store.
- Change your user's currency to `EUR`.
- Add a plan to your cart and visit checkout. 
- Add `?flags=composite-checkout-force` to the query string in the URL and reload the page because currently it is disabled for international currencies.
- Verify that "Bancontact" is an option displayed in the final payment step.
- Verify that you cannot pay if the "Name" field is empty.
- Fill out the "Name" field and submit the payment.
- Verify that you are redirected to a Stripe test page.
- Click to accept the payment and verify that the payment completes successfully and that the plan is purchased.

### CODE REVIEW

**Comment by fditrapani** [comment]
Updated the logo here too so that it's 16px high:

image

**Comment by sirbrillig** [comment]
Rebased to fix conflicts (and hopefully tests).

**Comment by nbloomf** [comment]
I was able to test this by manually setting my geo to BE on the backend. Bancontact loaded as expected and validation on the name field worked. I tested both successful and failed purchases, and both worked as expected - the successful purchase provisioned a site and generated a receipt.

I do see a couple of things- one is ours, and another I'm not sure about:

1) Both Sofort and Bancontact are available in Belgium, which leads to this warning about non-unique IDs:
image

2) After the successful purchase, the redirect to `/checkout/offer-quickstart-session/pending/$site/$id` loads a blank calypso page with the `Secure checkout` header. Nothing in the console indicates why that is. But if I manually remove the `$id` path component, the quickstart upsell page loads correctly. Might there be an issue with the redirect URL?

**Comment by sirbrillig** [comment]
> Both Sofort and Bancontact are available in Belgium, which leads to this warning about non-unique IDs:

Thanks! I'm surprised this hasn't come up before. I've pushed a fix.

> After the successful purchase, the redirect to /checkout/offer-quickstart-session/pending/$site/$id loads a blank calypso page with the Secure checkout header. Nothing in the console indicates why that is. But if I manually remove the $id path component, the quickstart upsell page loads correctly. Might there be an issue with the redirect URL?

Hm... I wasn't able to reproduce this issue. However, I have definitely seen similar behavior in the past. My suspicion is that there is some unexpected states that can come out of the redirect URL function (unfortunate, but not be related to this PR) or there's some strange state that can occur on test accounts using a sandboxed connection. Would you be willing to try it again to see if the problem recurs for you?

**Comment by yoavf** [comment]
> Both Sofort and Bancontact are available in Belgium

👋 Reminder that wf never launched Sofort publicly, and should probably not be ported to the new checkout...

**Comment by sirbrillig** [comment]
> Reminder that wf never launched Sofort publicly, and should probably not be ported to the new checkout

Oops, that was already merged in https://github.com/Automattic/wp-calypso/pull/43710! Well, it will only be activated if the server returns it as an available payment method, which hopefully it won't do if it's deactivated.

**Comment by sirbrillig** [comment]
The Stripe redirect payment methods (iDEAL, Sofort, Giropay, Bancontact, etc.) all have to submit a `success_url` to the `/me/transactions` endpoint which is then passed along to Stripe. Then the page gets redirected to confirm the payment, and when it comes back, it uses that `success_url` (slightly modified by the `/rest/v1/me/transactions/source-payment` endpoint to replace receipt placeholder text and append the order ID) to tell calypso what page to show next.

For some of these payment methods (notably Bancontact), the receipt placeholder text is replaced with `pending`. In a "regular" thank-you page url like `/checkout/thank-you/example.com/pending/12345`, that causes calypso to display a "please wait" page which polls the server until the order is complete or fails. However, some conditions can cause the thank-you url to be an upsell page instead, creating a url like `/checkout/offer-quickstart-session/pending/example.com/12345` which is an invalid calypso route, causing the user to see a blank page.

In old checkout, Stripe redirect payment methods customize the `success_url` by taking what the url would be and then placing it in a `redirectTo` query string after a regular thank-you `pending` page url. New checkout does not have this behavior, causing the user to be redirected to a blank page after payment is complete or if there is an error.

Big props to @nbloomf for discovering this issue. I've pushed a commit which will recreate the `redirectTo` query behavior in new checkout.

**Comment by nbloomf** [comment]
Looks good! Now after either a successful or a failed purchase I see the pending thank you page before being redirected to either the `/offer-quickstart-session` upsell page or back to checkout.

image

**Pull request merged**
