### PR TITLE
Assembler: Load rendered patterns by category

### PR DESCRIPTION
**Pull request by arthur791004**
Related to #

## Proposed Changes

* Refactor how we load the rendered patterns. Instead of loading them in sequence, this PR changes to load them by category.
* Additionally, now we use react-query to load them so we can cache the rendered patterns

## Testing Instructions

* Go to the Assembler
* Browse all categories to ensure the patterns are still rendered correctly

## Pre-merge Checklist

- [x] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [x] https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md for your changes?
- [x] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [x] Have you checked for TypeScript, React or other console errors?
- [x] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [x] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [x] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

**Review by taipeicoder — APPROVED** [review]
> Browse all categories to ensure the patterns are still rendered correctly

👍

**Review by fushar — APPROVED** [review]
Works well, thanks!

I like that we removed custom pagination computation, which could be buggy.

**Comment by fushar** [comment]
@arthur791004 @taipeicoder Sorry, I think this broke the Add pages screen as the page patterns are not fetched: 

image

**Comment by arthur791004** [comment]
Oops... I didn't notice that. Proposing https://github.com/Automattic/wp-calypso/pull/83794 to resolve the issue.

**Pull request merged**
