### PR TITLE
Reader: Update conversation icon

### PR DESCRIPTION
**Pull request by shaunandrews**
Over in #33995 we updated the Reader's sidebar icon to use Material icons. This PR updates the Conversations icon from the "chat" icon to the "question_answer" icon.

Before:
Screen Shot 2019-06-17 at 12 03 58 PM

After:
Screen Shot 2019-06-17 at 12 04 11 PM

### CODE REVIEW

**Comment by blowery** [comment]
@shaunandrews do we want to update the icon used elsewhere in the UI too? See the Follow Conversation button near the comments on https://hash-f72180288dd7c8a7f6997e12af5812a52ab13e0a.calypso.live/read/blogs/16956016/posts/34785

**Comment by blowery** [comment]
Screen Shot 2019-06-17 at 1 23 02 PM

**Comment by shaunandrews** [comment]
Hmmm, maybe worth a look. I'm not entirely sure what icon we'd use, as Material doesn't have anything like that (the comment with the plus). I'll dig in tomorrow and see what I can come up with.

**Comment by bluefuton** [comment]
Looks like this has been shipped in a separate PR - I'm seeing the Material icon in the Reader sidebar.

Screen Shot 2019-08-29 at 14 28 02

**Pull request closed without merging**
