### PR TITLE
Stats: Change support links to open in a new tab

### PR DESCRIPTION
**Pull request by jwebbdev**
Related to https://github.com/Automattic/red-team/issues/199

## Proposed Changes

* Updating external jetpack.com and wordpress.com support links to open in a new tab

## Why are these changes being made?

* This is a problem because interrupts the ongoing experience and, in some cases, the support link doesn’t allow users to go back using the browser “Back” action.

## Testing Instructions

* verify that the inline support links open in a new tab

Screenshot 2024-11-19 at 11 02 05 PM

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Comment by kangzj** [comment]
It looks good to me. I just wonder why the builds are failing for e2e tests🤔

**Comment by jwebbdev** [comment]
@kangzj I hadn't run the `install-plugin.sh $pluginSlug update/stats-external-support-links` items referenced.  Not sure if that was the issue as after doing that and rerunning the failed TeamCity jobs they still failed.  So I merged trunk and pushed to trigger another full workflow and it seemed to work.

**Review by kangzj — APPROVED** [review]
lgtm🚀

**Comment by kangzj** [comment]
nah you don’t need to run that command. The command is for Odyssey Stats testing. 

Thanks for fixing these! Very much appreciated! 🙇

**Pull request merged**
