### PR TITLE
WIP: Gutenpack availability

### PR DESCRIPTION
**Pull request by sirreal**
Sketching some Gutenpack block availability work.

Part of https://github.com/Automattic/jetpack/issues/10198

Companion: https://github.com/Automattic/jetpack/pull/10327

##### 👍 All good
active-connected

##### 👎 Module deactivated
deactivated

##### 😕 Disconnected Dev mode
devmode

##### 👎 No connection
no-connection

### CODE REVIEW

**Comment by gititon** [comment]
Hi @sirreal,

I tried to test this yesterday and today (using both this wp-calypso branch and it's Jetpack counterpart linked to above), and both times I have the Markdown block available in Gutenberg even though I have the markdown feature disabled in Jetpack settings. 

screen shot 2018-10-22 at 5 12 18 pm
screen shot 2018-10-22 at 5 13 01 pm

Can you please advise what else I may need to do to test this properly? Thanks!

**Comment by sirreal** [comment]
> Can you please advise what else I may need to do to test this properly? Thanks!

Noting that we spoke off-GH and this was testing well.

**Comment by roccotripaldi** [comment]
Note: squashed and rebased to resolve conflicts

**Comment by roccotripaldi** [comment]
so strange! this only works when i disable modules via the cli, but does not work when disabling them through the Jetpack UI

**Comment by sirreal** [comment]
@roccotripaldi That's strange… what do Jetpack debug output `wp jetpack module list` say? Do they confirm module (de)activation?

**Comment by roccotripaldi** [comment]
@sirreal - deactivating markdown via the UI doesn't actually activate / deactivate the module! I'd say that's a separate issue. This is working as expected when the module is truly deactivated.
I'm going to try to play around here to see if i can figure out a way to dynamically register the block based on module status / connection status.

**Comment by sirreal** [comment]
This work has been picked up elsewhere. Closing.

**Pull request closed without merging**
