### PR TITLE
Themes: Use promises for wpcom responses

### PR DESCRIPTION
**Pull request by ockham**
Rationale: because we can. :trollface:

No visual changes

To test -- Theme Showcase, everything. Single'n'multisite, logged-out, Jetpack; activate, purchase, details.

### CODE REVIEW

**Comment by ockham** [comment]
Note -- we should merge this only after #3774 (and rebasing), since `master` currently has one more `wpcom.undocumented().themeDetails()` invocation, which #3774 removes.

**Comment by ehg** [comment]
Looks good, although as you mentioned, should we wait for #3774 before a full review?

**Comment by ockham** [comment]
Hmm right. Then again, I love :ship:ping stuff, so I'm inclined to fix the remaining wpcom call in this PR and rebase the other one...

**Comment by ehg** [comment]
Haha, OK. Well code LGTM, and e2e tests pass ( I think they hit all code paths here? ). :+1:

**Comment by ockham** [comment]
Thx for the review!

**Pull request merged**
