### PR TITLE
Use stable color for .stats-sparkline__bar so bars are always visible.

### PR DESCRIPTION
**Pull request by mpkelly**
#### Proposed Changes

* Use a stable `color` value for the `.stats-sparkline__bar`. By default it uses the Calypso theme variable `--color-stats-sparkline` which is sometimes the same colour as the `/sites` page background. 

This was flagged here https://github.com/Automattic/wp-calypso/pull/68731#issuecomment-1273197254 but looks it didn't get fixed before that PR was deployed. 

#### Testing Instructions

* Reproduce the issue with the Modern theme. Retry using the Calypso Live link. 

#### Pre-merge Checklist

- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?

Related to #

### CODE REVIEW

**Comment by wojtekn** [comment]
@mpkelly I've tested it in Chrome, the bars are slightly darker, but I couldn't reproduce the original issue using the Modern theme:

Screen Shot 2022-10-24 at 08 40 51

**Review by wojtekn — APPROVED** [review]

**Comment by mpkelly** [comment]
Thanks, @wojtekn. I just tried prod again and it's still broken for me. I will deploy this now anyway. 

image

**Comment by sejas** [comment]
I could reproduce the issue using the Modern theme.

Screenshot 2022-10-24 at 10 15 48

This PR fixes it 👍 , Well done @mpkelly .

**Comment by danielbachhuber** [comment]
Thanks for fixing this up, @mpkelly !

**Pull request merged**
