### PR TITLE
A4A: Fix the mobile responsiveness issue with the new Hosting page v3.

### PR DESCRIPTION
**Pull request by jkguidaven**
This PR addresses several UI issues regarding mobile responsiveness for the new hosting page v3.

## Proposed Changes

* Change the header collapse animation duration to 0.25 seconds for better user perception.
* Improve the responsiveness of the header for different screen sizes. To address this, we need to hide the Migration Offer banner on smaller screens, as it causes issues with the sticky position. When the banner is expanded, it tends to take up 100% of the viewport, which does not work well with the sticky header.  Additionally, some of the font sizes are reduced to better fit on a narrower screen, and the 'Hosting' text is hidden as well to provide more space for header action buttons.

| Before | After |
|--------|--------|
| Screenshot 2024-12-17 at 9 20 01 PM | Screenshot 2024-12-17 at 9 20 09 PM | 

* Fixed some spacing issues in the Hosting Plan section on smaller screens.

| Before | After |
|--------|--------|
| Screenshot 2024-12-17 at 9 26 05 PM | Screenshot 2024-12-17 at 9 26 30 PM | 

* Fixed the Pressable plan slider to work with smaller screens.

| Before | After |
|--------|--------|
| Screenshot 2024-12-17 at 9 28 35 PM | Screenshot 2024-12-17 at 9 28 20 PM | 

## Why are these changes being made?

* This is part of the In-product hosting page v3 project.

## Testing Instructions

* Use the A4A live link and go to the `/marketplace/hosting` page.
* Verify that the fixed and improvements above are working as expected.

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
    - [ ] For UI changes, have we tested the change in various languages (for example, ES, PT, FR, or DE)? The length of text and words vary significantly between languages. 
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Comment by andrii-lysenko** [comment]
There are small notes, though I not sure if it's becuase I use browser dev tools. But for Iphone 12 Pro I see some cut words:

Screenshot 2024-12-18 at 1 01 16 PM

Screenshot 2024-12-18 at 1 01 41 PM

**Review by cleacos — APPROVED** [review]
It works well on mobile. 

The only "issue" is the tab:

image

Other than that, LGTM!

**Comment by jkguidaven** [comment]
@andrii-lysenko @cleacos Thank you for the review. I have resolved the cutoff and misalignment of the navigation on certain viewport sizes.

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/17068675

Some locales (Hebrew, Japanese) have been temporarily machine-translated due to translator availability. All other translations are usually ready within a few days. Untranslated and machine-translated strings will be sent for translation next Monday and are expected to be completed by the following Friday.

Thank you @jkguidaven for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/17068675).

**Pull request merged**
