### PR TITLE
Reader: Hide like and share labels on mobile

### PR DESCRIPTION
**Pull request by shaunandrews**
Hiding the share and like labels (not like count) on mobile to avoid an overflow in the post footer in streams.

Before on `master`:
screen shot 2016-01-27 at 4 07 16 pm

After:
screen shot 2016-01-27 at 4 07 27 pm

### CODE REVIEW

**Comment by bluefuton** [comment]
Do we need to target this just at the share bar?

We get this for comment likes, which feels a bit odd:

screen shot 2016-01-28 at 11 50 42

**Comment by shaunandrews** [comment]
Pushed some updates to only show the like count when its higher than 0, and to force the like status to show for comments on mobile.

**Comment by blowery** [comment]
The share popover on full post comes from an odd place when the label is hidden:

screenshot

**Comment by shaunandrews** [comment]
Ah, good catch. Fixed:

screen shot 2016-01-28 at 4 38 28 pm

**Comment by bluefuton** [comment]
LGTM :shipit: 

The left of the share menu sometimes gets cropped, but it looks like that's also happening on master (#2725).

screen shot 2016-01-29 at 14 54 32

**Pull request merged**
