### PR TITLE
Dev: Open Calypso automatically during build

### PR DESCRIPTION
**Pull request by artpi**
I am a very lazy person. Opening new browser window is just SO MUCH WORK.
I made this modifications to webpack config to open Calypso for me when the build is finished.

Please share your opininions about this, I just wanted to start discussion.

### CODE REVIEW

**Comment by artpi** [comment]
A case where this could be usefull:
I have an Automator service in OSX that fires any branch:
```
cd /Users/Artpi/GIT/calypso && git fetch && git checkout $arg1 && make run
```

So when I select a branch name and click right click -> services I can fire it up
This is the last step in making it much easier to test branches

**Comment by blowery** [comment]
It's handy, but I definitely wouldn't want to always have it on. There are lots of cases where I restart calypso and don't want to open a new browser window.

If we keep it, maybe hide it behind an ENV variable?

**Comment by brandonscott** [comment]
+1 to @blowery 's suggestion.  It would be a very situation-based feature.

**Comment by artpi** [comment]
I completely agree, I will make it into environmental variable

**Comment by artpi** [comment]
Clearly I did something wrong here... 
I rebased and all of these commits happened

**Comment by artpi** [comment]
I am not trying to repair this mess, will move changes to another PR :)

**Pull request closed without merging**
