### PR TITLE
Posts: Fix how we detect images in posts

### PR DESCRIPTION
**Pull request by blowery**
Also, teach detectImages about natural height and width and about the magic data-orig-size attribute

### CODE REVIEW

**Comment by blowery** [comment]
Fixes #9284

**Comment by lancewillett** [comment]
I'm testing on a few different sites on the live branch. Seems fixed on a few like lance.blog (w00t!) —seeing images for posts.

Also blackeoutrims.com is working correctly now. This is Safari 9.1 on OS X 10.11.4.

screen shot 2017-02-10 at 21 51 49

Nice work. 🎉

**Comment by samouri** [comment]
Code + Functionality LGTM! 
🚢 

For my own enlightenment:
 - in which cases do the three different forms of height/width appear?

**Comment by blowery** [comment]
@samouri 
1. when an image tag has a height and width attribute
2. when an image object has been loaded from the network and the browser has it locally
3. when an image appears as part of a `[caption]` shorttag on a wordpress site

**Comment by blowery** [comment]
@lancewillett @rralian i'm currently in transit. if y'all want to land this before I return on monday, please feel free.

**Comment by rralian** [comment]
I am able to intermittently get Calypso into a state where images never load. But I think it might just be a memory issue with the javascript in general. Tends to happen when I have a million tabs open and my computer's fan kicks in. I can also occasionally get the browser tab to freeze up completely while I'm scrolling through the list. But I can get this to happen in production too. So I can't really confirm these issues are new to this branch. For the most part this branch works as expected and fixes the image issue, so I'm inclined to say 🚢  it.

I think going forward we should put time/effort into handling this on the back-end. The determination of which image to display should be done async on the back-end when a post is saved/updated, stored somewhere (elasticsearch?) so it can just be returned by the API along with the rest of the post info, so we can avoid the front-end logic.

**Comment by blowery** [comment]
> I think going forward we should put time/effort into handling this on the back-end. The determination of which image to display should be done async on the back-end when a post is saved/updated, stored somewhere (elasticsearch?) so it can just be returned by the API along with the rest of the post info, so we can avoid the front-end logic.

I'm a little wary of embedding calypso-specific logic into the API, but... yeah. I pretty much agree.

**Comment by lancewillett** [comment]
This seems to be broken again. :/

Opened new issue #12609 with details. But it's the same as here.

**Pull request merged**
