### PR TITLE
Implement Help-Center contact form

### PR DESCRIPTION
**Pull request by alshakero**
First: Terribly sorry for the big  PR. It's just the irreducible complexity of dependencies pulling each other. The majority of the changes (in file count, I mean), are one-liners to update the import path.

#### Changes proposed in this Pull Request

* This PR introduces a new Calypso-independent site-picker component. This picker is keyboard navigable and works on mobiles. The Calypso version is insanely entangled with Calypso state, and I couldn't take it out without breaking things. And it pulled 100KB worth of deps with it.
* It also moves `Gravatar`, `HappinessEngineersTray`, and `useHappinessEngineersQuery`, `safeImageUrl`,  to packages. 
* Implements the Help-Center contact form with three modes `CHAT`, `EMAIL`, and `FORUM`.

#### Testing instructions
- Checkout the branch
- yarn dev --sync from apps/editing-toolkit
- Go to https://YOUR_SITE. wordpress.com/wp-admin/post-new.php?enable-help-center
- Go to this file https://github.com/Automattic/wp-calypso/blob/add/help-center-contact-form/apps/editing-toolkit/editing-toolkit-plugin/help-center/src/contents.js#L70 and change the `mode` prop from CHAT, EMAIL, and FORUM. All modes should be supported by the form.
- Smoke test Calypso (My home, help/contact, etc..).

### CODE REVIEW

**Review by escapemanuele — CHANGES_REQUESTED** [review]
Tested in calypso and not and it's working! What an amazing job.
I think that this could be good to go, once CI errors get solved!

**Review by arcangelini — APPROVED** [review]
Tested this as well, smooooooooth!! and it looks like it is passing all the tests now. Amazing job @alshakero

**Review by escapemanuele — APPROVED** [review]

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/7282303

Hi @alshakero, could you please edit the description of this PR and add a screenshot for our translators? Ideally it'd include all of the following strings:
- `Start live chat`
- `Our WordPress experts will be with you right away`
- `Send us an email`
- `Our WordPress experts will get back to you soon`
- `Ask in our community forums`
- `Please do not provide financial or contact information when submitting this form.`
- `How can we help you today?`
- `Don’t display my site’s URL publicly`

Thank you in advance!

**Comment by noahtallen** [comment]
Cool! I'm curious what the plan is for this on Atomic sites. Iirc, we shouldn't load account-level data on sites where we can't control what other code is running. As an example, if the site list data is present in PHP on an Atomic site, any plugin could access it. And if it was present in the client side, anything other client script could access it.

This is one of the reasons that other JS Calypso apps served over widgets.wp.com have been necessary (some more discussion here about it p9oQ9f-19W-p2). If the code is loaded in an iframe, the browser will block access from other top-level scripts on the site, meaning the information is safe.

**Comment by alshakero** [comment]
Hi Noah! This is aware of that, it doesn't list the users' sites, only two options, "This site", "Other site" options.

**Comment by noahtallen** [comment]
Awesome, that's great to hear! I'm sorry for not testing it more in depth before commenting :)

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/7282303

Hi @alshakero, could you please edit the description of this PR and add a screenshot for our translators? Ideally it'd include all of the following strings:
- `Start live chat`
- `Our WordPress experts will be with you right away`
- `Send us an email`
- `Our WordPress experts will get back to you soon`
- `Ask in our community forums`
- `Please do not provide financial or contact information when submitting this form.`
- `How can we help you today?`
- `Don’t display my site’s URL publicly`
- `Connecting to chat`
- `Something went wrong, please try again later.`

Thank you in advance!

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/7282303).

**Pull request merged**
