### PR TITLE
Plans: update messaging and design to clarify upgrade discounts

### PR DESCRIPTION
**Pull request by danhauk**
Attempting to clarify the messaging around upgrade discounts. They are now presented more as an account credit rather than a straight discount (since the user has already paid $99 for Premium).

Before | After
------------ | -------------
screen shot 2016-01-15 at 12 37 25 pm | screen shot 2016-01-15 at 2 09 04 pm

### CODE REVIEW

**Comment by mikeshelton1503** [comment]
Looking good, I only noticed a couple minor things:

On the smallest mobile devices (320px) the copy runs into the arrow. Should probably build in some padding to prevent that regardless of the length of the copy or width of the screen.

image

On the compare plans page, should the `$199` price also be green?
image

**Comment by danhauk** [comment]
Good catch on both of those. I just pushed fixes for both issues.

**Comment by mikeshelton1503** [comment]
There is a new issue now:

image

**Comment by danhauk** [comment]
Thanks @mikeshelton1503. Somehow I missed the smallest breakpoint, I was testing at > 450px.

Should be all good now.

**Comment by mikeshelton1503** [comment]
LGTM :+1:

**Pull request merged**
