### PR TITLE
i18n: Use bundeled momentjs data instead of our own

### PR DESCRIPTION
**Pull request by yoavf**
In the current i18n process, we overwrite the bundled momentjs [locale data](https://github.com/moment/moment/tree/develop/locale), with our own data generated  in our exports from translate.wordpress.com. While this has the benefit of some flexibility around fixing localization issues, it also comes with some major disadvantages:
- Duplicate translation work: momentjs already has this translated in many locales. 
- Loss of advanced functionality, like the ability to define a translation via a function ([example](https://github.com/moment/moment/blob/develop/locale/he.js#L69))
- Developers expect the translations to match the examples from momentjs (see #2642). Diverging from that creates confusion.
- Bigger locale files

This PR switches to using the default bundled data, and removes the custom strings from our translations process (Calypso side):

**Considerations:** 
- We now add the locales file to the webpack bundle. I'm not sure how to verify the difference in file size. All locale files take about 0.5MB on disk.
- If we find ourselves in a situation where the momentjs locale data is incomplete or wrong, we can overwrite in code, while pushing fixes uprstream.

**Testing**
- Switch to translated non english locale (i.e 'es' or 'fr')
- Check that localized dates are still localized. For example, the date on hover over a post human date in the reader.

### CODE REVIEW

**Comment by yoavf** [comment]
Now depends on #5280 landing first

**Comment by dmsnell** [comment]
@yoavf would you mind rebasing this and then giving a brief summary of what, if anything, you need from reviewers to move this forward?

is this ready now that #5380 was merged?

**Comment by dmsnell** [comment]
@yoavf I rebased locally and then tested - the date strings translated fine.

if you don't need further review, please feel free to rebase and then merge!

**Comment by Tug** [comment]
#5477 happened first so we won't be able to merge this PR now.
Instead, I'm planning to port this change to `i18n-calypso` soon.

**Comment by Tug** [comment]
@yoavf I have just rebased to master and moved your changes on `lib/mixins/i18n` to `i18n-calypso` https://github.com/Automattic/i18n-calypso/commit/3bd8440796cc1c0a434a2e88b9d49a97c32b2baa

I believe this is ready for another review :)

**Comment by Tug** [comment]
Closing, changes from this PR are now obsolete. Let's review #5923 instead!

**Pull request closed without merging**
