### PR TITLE
Auto-fix eslint curly errors.

### PR DESCRIPTION
**Pull request by mpkelly**
**Note**: this PR should be merged before https://github.com/Automattic/wp-calypso/pull/69071

Related to https://github.com/Automattic/wp-calypso/pull/68939

#### Proposed Changes

* Fix `eslint` `curly` errors in the `client` folder. 

This is worth doing in itself but I needed to clear these errors so I can then clear `react/jsx-curly-brace-presence`.  See discussion [here](https://github.com/Automattic/wp-calypso/pull/68939#issuecomment-1277273891). 

#### Testing Instructions

* Please review the changed files. 

#### Pre-merge Checklist

- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?

### CODE REVIEW

**Comment by mpkelly** [comment]
I am going offline now. Ideally, we can get this into the trunk quickly without merge issues. I will do the other auto-fix PR for JSX brackets tomorrow. The reviewer can merge this one if they are happy.

**Comment by mpkelly** [comment]
I also created a second PR for the JSX brackets here https://github.com/Automattic/wp-calypso/pull/69071

Any chance of getting these reviewed today or is it too late?

**Comment by mpkelly** [comment]
I noticed that as well as 24 `curly` errors in https://github.com/Automattic/wp-calypso/pull/69071 there is also 1 `react/no-string-refs` error. I have fixed that in this smaller PR. I couldn't find where this `ref` was being used so just removed it. 

Errors in https://github.com/Automattic/wp-calypso/pull/69071 that will be fixed by this PR:

image

**Review by jsnajdr — APPROVED** [review]
Looks good, all the changes seem to be perfectly harmless :+1:

**Comment by mpkelly** [comment]
Thanks, @jsnajdr. I am going to merge this into trunk when the CI is done.

**Pull request merged**
