### PR TITLE
Stats: Inconsistent blog_id in calypso_page_view stats

### PR DESCRIPTION
**Pull request by donpark**
`blog_id` should be null for paths without `:site`, like `/me` or `/read/search`.

Addresses first part of issue #16900 

Test Plan:

1. Open console and enable stat event tracking
```
localStorage.setItem('debug', 'calypso:analytics:tracks')`
```
2. Click on user avatar to navigate to `/me`.
3. Find console line starting with `calypso:analytics:tracks Recording event "calypso_page_view" with actual props` and expand it.
4. You should **not** see `blog_id`.
5. Click on "Reader" then "Search" to navigate to `/reader/search`.
6. Repeat step 3 and 4.
7. Navigate to a post and repeat 3 and 4 except now `blog_id` should be present.

### CODE REVIEW

**Comment by yanirs** [comment]
Thanks @donpark, but it looks like this only solves the first half of the problem reported in #16900:
> For example, when visiting /me or /read/search, blog_id should always be reported as null, while it should always be reported as non-null for /posts/:site and /stats/day/:site.

We will still get null `blog_id`s for some paths.

It'd be good to look deeper into why `selectedSite` doesn't always match the path.

**Comment by donpark** [comment]
@yanirs which paths are not working for you. This is what I see when `path` is `/posts/:site`.

screenshot_337

**Comment by donpark** [comment]
OK. Looks like reverse side of the bug hasn't been address. Switching to `in progress`.

**Comment by donpark** [comment]
@yanirs I have not been able to reproduce `selectedSite` being null when `path` has path variable `:site`.

Let's just merge this partial fix for now.

**Comment by yanirs** [comment]
@donpark I think we're better off not merging this partial fix, as the issue is deeper. In my opinion we need to completely move away from using `selectedSite`, as it's often wrong.

**Comment by donpark** [comment]
Makes sense. Could you make a note of it in the original issue?

I'll close this PR.

**Comment by yanirs** [comment]
@donpark Thanks! I added a note in the original issue.

**Pull request closed without merging**
