### PR TITLE
Bulk Plugin Management: Improve mobile navigation

### PR DESCRIPTION
**Pull request by paulopmt1**
pet6gk-1CP-p2.
Closes https://github.com/Automattic/dotcom-forge/issues/9854

## Proposed Changes
This PR adds the grid view layout to the plugins page when it's displayed on mobile.

* Include the dataview grid layout
* modify the grid item similar to the [patterns page](https://github.com/Automattic/dotcom-forge/issues/9854)

## Why are these changes being made?

* To provide a better mobile experience for the bulk plugins page

## Testing Instructions

* Go to `/plugins/manage` in mobile view of devtools
* Verify you can switch to grid view and it renders properly
* Verify plugin status is rendered properly
* Click site count and verify sites modal is shown
* Verify header and footer remain fixed when scrolling

image

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
    - [ ] For UI changes, have we tested the change in various languages (for example, ES, PT, FR, or DE)? The length of text and words vary significantly between languages. 
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Comment by autumnfjeld** [comment]
@p-jackson  Do you think you can review this today? Hopefully then ready to merge by @paulopmt1 or @vykes-mac  when they wake up. 😄

**Comment by vykes-mac** [comment]
> @p-jackson  Do you think you can review this today? Hopefully then ready to merge by @paulopmt1 or @vykes-mac  when they wake up. 😄 

Also feel free to make changes

**Comment by p-jackson** [comment]
> Also feel free to make changes

Currently this PR _adds_ support for grid view when switching to mobile layout. But given the feedback we're addressing is about fixing the mobile layout, I almost think we should force the user into a different layout on small screens. That is: table on wide screens, something else on narrow screens. That way it'd behave more like a media query. Otherwise weirdness happens: you shrink your browser, choose grid, grow your browser, you're still on grid layout but they control for changing the layout has disappeared.

I also think that using `grid` on mobile isn't the right idea. I think the mobile layout of the current (in production) layout of the plugins list is much better than grid.

CleanShot 2024-11-25 at 13 19 53@2x

I think the `list` layout fits this much better. For example, see the `DataView` storybook https://wordpress.github.io/gutenberg/?path=/docs/dataviews-dataviews--docs

| *table* | *list* |
| --- | --- |
| CleanShot 2024-11-25 at 13 23 45 | CleanShot 2024-11-25 at 13 24 10 |

The fields wrap when using this layout.

**Comment by paulopmt1** [comment]
We're planning to other changes on mobile. Follow-up task: https://github.com/Automattic/dotcom-forge/issues/9936

**Pull request closed without merging**
