### PR TITLE
Store: label settings into label purchase sidebar

### PR DESCRIPTION
**Pull request by dechov**
Generalizes label purchase `paperSize` selection view + state to make all settings adjustable per individual "Buy & Print" action (or technically, per order, as encoded in client state.) `<LabelSettings>` now accepts both data and a change handler as props, so that it can work in the proper context of either the old settings view or the label purchase sidebar.

screen shot 2018-02-28 at 3 09 41 pm

In particular, this makes it possible to present the label purchase dialog even if a payment hasn't been selected (see https://github.com/Automattic/woocommerce-services/issues/1115, "Solution 2"). It should no longer be _necessary_ to visit settings, except to modify default values. (Just an idea, but an alternative possibility for modifying defaults may be to present a small "Set as default" button next to each selection that diverges from the default.)

Blockers for release:
- Payment selection is currently ignored. Don't show payment section if plugin won't accept payment method passed in this way, which requires a plugin release. (To actually make the purchase go through with the selected card, comment out this line in the plugin: https://github.com/Automattic/woocommerce-services/blob/ed893cc72acbe7096cc31da857b4243e6f7bca03/classes/class-wc-rest-connect-shipping-label-controller.php#L38.) Alternatively, we can pass a differently named parameter, and accept it on the server, with the existing parameter as fallback.
- Sidebar form `errors` are currently ignored, but we probably want to expand these — for instance, if a payment method wasn't selected.
- Appearance: Fix sidebar background not extending past available height when scrolling. Had trouble with this so far, assuming we care to keep the available height as a minimum.
- Appearance: Make `<LabelSettings>` blend in with other settings. Or, add "email details" and "fulfill order" to label settings, so long as there's no reason they need to be treated differently.
- Appearance: Rebase on https://github.com/Automattic/wp-calypso/pull/22504 for more compact payment method options.

Other next steps are to present label purchase dialog even if there isn't a selected payment method, as long as user can manage payments. Can be a separate wp-calypso PR, and will need to be an equivalent WCS PR as well.

High-level feedback welcome, as well as code review on what's there so far.

### CODE REVIEW

**Comment by jeffstieler** [comment]
Punting until we can have design vet this.

**Comment by gwwar** [comment]
@dechov are we still working on this PR? If not, let's close this out with a reason in the summary on why it was punted. If we need to pick up work again, it's not much work to reopen this PR.

**Comment by dechov** [comment]
@gwwar This is still something I intend to move forward with or continue the discussion around. (Would have gotten to it sooner but was on support rotation last week.)

Will most likely address the above comments in separate small PRs — since they are for the most part independent of the changes in this PR (correct me if I'm wrong @kellychoffman) — and then seek further review if there is no other design feedback in the meantime.

Removing 'Punted' label, and if it stalls again, will re-add the label and close with summary. Thanks!

**Comment by alisterscott** [comment]
This branch needs a rebase. Is this PR still required?

**Comment by alisterscott** [comment]
Closing due to inactivity - please reopen if necessary

**Pull request closed without merging**
