### PR TITLE
Checkout v2: Show discounts for each line item and introductory offer detail

### PR DESCRIPTION
**Pull request by sirbrillig**
The discount list in v2 checkout can sometimes create confusion because the discounts are displayed summarized far away from the line items they apply to. This is fine for simpler discounts but for complex discounts this can be impossible to understand.

## Proposed Changes

In this PR we refactor the discount list in checkout v2 to show each discount next to the line item to which it applies, with a few exceptions like coupon discounts which will still be shown below the line item list.

In addition, this PR adds additional detail to introductory offer discounts where the billing term length of the discount is different from the term length of the product. For example, a 3 month discount for an annual product. This discount is misleading because while the user may indeed be "saving" $X today, they will owe ($X / 12) * 3 in 3 months. This PR hides those discount amounts, instead showing the line item price crossed-out with today's price adjacent to it (or just the crossed-out price if the discount is 100%). It also adds text like `Due XXXX-MM-YY: $X` below the line item to clarify when and how much the user will next be charged.

Before             |  After
:-------------------------:|:-------------------------:
before-another | after-another

Fixes https://github.com/Automattic/payments-shilling/issues/2410
Fixes https://github.com/Automattic/payments-shilling/issues/2437

## Testing Instructions

- Add a plan, a domain, and a Professional email product to your cart and visit checkout.
- Add a coupon to the cart.
- Compare checkout (v1) on this branch to production and verify that there are no changes.
- Add `?checkoutVersion=2` to the checkout URL on this branch and verify that the changes described above look correct, particularly the "Due" date and price.

### CODE REVIEW

**Comment by michaeldcain** [comment]
Fixes: https://github.com/Automattic/payments-shilling/issues/2437

**Comment by jjchrisdiehl** [comment]
Looks great! Just a few optional changes:

Should we include a bit more row-gap between the discount text and due date? 

image

As for the 12px font-size, I think that's fine and helps break up the line items a bit better.

As for the coupon field, I think changing the margin-bottom on the `order-review-line-items` area to `12px`  and the padding-bottom on the coupon component itself to `12px` would create a tighter look here.

| Before | After |
| ----- | ----- |
| image | image |


Looks good on mobile too!

image

**Review by jjchrisdiehl — APPROVED** [review]

**Comment by sirbrillig** [comment]
> Should we include a bit more row-gap between the discount text and due date?

I couldn't find an elegant way to do this so I haven't yet, but we can adjust it later.

> As for the coupon field, I think changing the margin-bottom on the order-review-line-items area to 12px and the padding-bottom on the coupon component itself to 12px would create a tighter look here.

Good suggestion. Done.

@DavidRothstein suggested changing the wording from "Due May 20..." to "Billed May 20..." to avoid making it seem like buy-now-pay-later, so I've made that change too.

**Comment by sirbrillig** [comment]
Also fixes https://github.com/Automattic/payments-shilling/issues/2410

**Comment by jjchrisdiehl** [comment]
Functionally works and looks great!

306812104-e45f5937-f109-4c0b-b94d-f3fa67814404

For now I think this is good to ship. I think we would want to ask our designers to take another pass at it in the future to see if they can make the "due today" portion more prominent, but it works for our purposes now.

**Review by jjchrisdiehl — APPROVED** [review]

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/11393665

Some locales (Hebrew, Japanese) have been temporarily machine-translated due to translator availability. All other translations are usually ready within a few days. Untranslated and machine-translated strings will be sent for translation next Monday and are expected to be completed by the following Friday.

Thank you @sirbrillig for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/11393665).

**Pull request merged**
