### PR TITLE
Signup: Remove simple flow

### PR DESCRIPTION
**Pull request by arthur791004**
#### Changes proposed in this Pull Request

* Remove `simple` flow as it seems not to get any traffic. Also for `passwordless` step.

#### Testing instructions

* Go to `/start`
* Check existing flows work well

Related to https://github.com/Automattic/wp-calypso/issues/60281

### CODE REVIEW

**Comment by roo2** [comment]
@donlair and @enejb I see you've been working on passwordless signup in https://github.com/Automattic/wp-calypso/pull/60368 and other PRs, are you currently using or planning on using this `'simple'` signup flow? or are you just implmenting passwordless signup on the login page or other flows?

**Comment by arthur791004** [comment]
As I know, they implement the [PasswordlessSignupForm](https://github.com/Automattic/wp-calypso/blob/b65f297d7ef684a90e9560db33e54911f618fdb5/client/blocks/signup-form/index.jsx#L1048) rather than `passwordless` step

**Comment by enejb** [comment]
The new passwordLess sign up flow that only applies to mobile is not the same as the 'simple' flow. Let's remove the simple flow if it is not being used anymore. We could also redirect users to the main flow in case they land here somehow.

**Review by roo2 — APPROVED** [review]
LGTM!

**Pull request merged**
