### PR TITLE
Gutenboarding: Add reCAPTCHA to signup form

### LINKED ISSUE #42181: Gutenboarding: Enable recaptcha
We should look at enabling recaptcha for Gutenboarding.

Tasks:

- [ ] Get in touch with data to see if there are any special requirements

Related PR: https://github.com/Automattic/wp-calypso/pull/39269

Context: 900&cid=CRNF6A9DX-slack-CRNF6A9DX

### PR DESCRIPTION
**Pull request by andrewserong**
Add reCAPTCHA to Gutenboarding signup form, with the same behaviour as found in the legacy signup flow at `/start`.

This uses the [reCAPTCHA "invisible" badge](https://developers.google.com/recaptcha/docs/versions#recaptcha_v2_invisible_recaptcha_badge) on desktop viewports, and paragraph text on mobile.

##### Desktop

image

##### Mobile

image

#### Changes proposed in this Pull Request

* Add reCAPTCHA code from Calypso to Gutenboarding, with minimal types (this isn't DRY, but I assume it's preferable to importing the existing code directly from Calypso)
* Add reCAPTCHA to signup form
* Tweak the signup form styling a little bit to include the text-based reCAPTCHA TOS notice, make the links grey and bring back the underline to get a bit closer to the designs.
* Re-use the same signup action name as is used in /start: `'calypso/signup/formSubmit'`

Note: the signup form styling still needs work to match the designs, but I thought the bulk of this could wait until we turn the modal into a proper page, and leave it out of this PR. For the moment, I'm mostly concerned with trying to make the reCAPTCHA notice look okay, but I'm keen for feedback / direction on the styling.

#### Testing instructions

* Go to `/new` while logged out and complete the flow until you reach the signup form
* Notice that there is now a reCaptcha badge at the bottom right of the screen that you can hover over
* Resize to mobile layout and check that the badge gets hidden, that there are no horizontal scrollbars, and that the paragraph text displays correctly beneath the `Create account` button
* Open up the developer console, and make sure you have `Preserve log` checked on the network tab
* Complete creating an account, and for the request to `users/new`, check that the correct `g-recaptcha-response` token is being sent (really just check that a random-looking string is being sent)

* Repeat the above steps with an ad-blocker that blocks anything from google.com and complete the above steps, and check that for the `users/new` request, a `g-recaptcha-error` param is sent (should be `recaptcha_didnt_load`)

To be especially sure, check that there isn't anything in the original reCAPTCHA for signup PR that I've missed here (https://github.com/Automattic/wp-calypso/pull/39269)

Fixes #42181

### CODE REVIEW

**Comment by yansern** [comment]
> Repeat the above steps with an ad-blocker that blocks anything from google.com and complete the above steps, and check that for the users/new request, a g-recaptcha-error param is sent (should be recaptcha_didnt_load)

@andrewserong What ad-blocker are you using and how did you configure it for this to happen?

**Comment by yansern** [comment]
Went through the testing process, I can see the recaptcha response in the net panel.
image

Others matches test descriptions.

image

image

At first I thought the horizontal scrollbar is still showing but now I see you're trying to hide the inner horizontal scrollbar. So it's all good.

**Comment by andrewserong** [comment]
Thanks for reviewing @yansern!

@dubielzyk do you have any concerns or feedback on the text styling on mobile for this one?

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/3576010

Thank you @andrewserong for including a screenshot in the description! This is really helpful for our translators.

**Pull request merged**
