### PR TITLE
Signup: Add Business Vertical Themes A/B Test i1

### PR DESCRIPTION
**Pull request by sirbrillig**
Work in Progress. Needs to avoid stepping on other tests in the same way as #3367

Also needs actual theme choices added (the ones in there now are just an example).

### CODE REVIEW

**Comment by iamtakashi** [comment]
Made it A/B test ready with themes we'd like to test with.

I'm adding details about the test and testing instruction shortly.

**Comment by iamtakashi** [comment]
Currently users coming from WordPress.com two-button homepage are going through a two-step vertical survey as a part of signup process (#2774). At the moment, the data from the survey is only used for user analysis; they have no effect on the signup process. 

To explore the possibilities of providing more tailored signup experience with the survey, we could display different themes based on the answer given to the survey.

As i1, this flow will display a set of 9 business oriented themes when you select `Business & Services` and all subcategories of it.

screen shot 2016-02-25 at 02 51 13

<h2>Hypothesis</h2>

If a user who selected `Business & Services` in the survey sees more business oriented themes in the theme step, the following metrics could indicate positive outcome.

* Conversion rate
* Theme step completion rate
* 1-week retention

Note that we might see a drop in retention because those business oriented themes tend to be difficult to setup like demo sites. But that's what Headstart is trying to solve and now it's been tested and it's close to launch. If we see a drop in the retention, we should test as i2 with Headstart.


<h2>Control / Variants</h2>

* Control: The current WP.com homepage flow
* Variation: The tested flow; If you choose `Business & Services` in the survey, the flow displays the vertical oriented themes.
* Not Tested: Receives the current WP.com homepage flow, becomes available to other signup tests


<h2>Traffic Allocation</h2>

* Control: 20%
* Variation: 20%
* Not Tested: 60%


<h2>Testing Instruction</h2>

1. Run `git checkout [branch]` and start your server.
2. Visit `/start/website/en/?ref=homepage` or `/start/blog/en/?ref=homepage`
3. Run this in your console to assign yourself to the test.
`localStorage.setItem('ABTests','{"altThemes_20160215":"notTested","headstart_20160215":"notTested","verticalThemes_20160223":"verticalThemes"}');`
4. Visit the same url in the step 2 again in case you've been already redirected to one of running tests; Either `/start/website/en/?ref=homepage` or `/start/blog/en/?ref=homepage`
5. Assert you see the survey and the url is now either `start/website-vertical-themes/survey/en` or `/start/blog-vertical-themes/survey/en`
6. Click `Business & Services` in the first step of the survey
7. Click any subcategory in the second step of the survey (it doesn't matter which category)
8. See the business oriented themes (see the screenshot above) in the theme step
9. Complete the rest of signup and see you have a site with the chosen theme.

**Comment by iamtakashi** [comment]
> Note that we might see a drop in retention because those business oriented themes tend to be difficult to setup like demo sites. But that's what Headstart is trying to solve and now it's been tested and it's close to launch. If we see a drop in the retention, we should test as i2 with Headstart.

A slight change of plan. Headstart is ready to use for this test and to avoid the potential drop in 1-week retention, I'm going to test with Headstart.

**Comment by kwight** [comment]
Annotations we don't have that will need to be generated:

 - [ ] Gateway
 - [ ] Motif
 - [ ] Goran
 - [ ] Pique
 - [ ] Big Brother

**Comment by kwight** [comment]
Noting that this shouldn't be merged until Headstart and bkismet are playing nicely together. cc/ @westi

**Comment by kwight** [comment]
@iamtakashi noting that each theme has to be verified for GPL-compatible images.

**Comment by iamtakashi** [comment]
> @iamtakashi noting that each theme has to be verified for GPL-compatible images.

It's confirmed by theme designers. Good to go.

**Comment by kwight** [comment]
> Noting that this shouldn't be merged until Headstart and bkismet are playing nicely together

We're good to go here too.

All annotations are done and committed now – they should all get a once-through though to be sure.

**Comment by kwight** [comment]
LGTM :+1: 

Tested that the variations redirected properly, but didn't test every theme.

**Comment by iamtakashi** [comment]
> Tested that the variations redirected properly, but didn't test every theme.

Tested annotations for all 9 themes, no issue. Good to go!

**Pull request merged**
