### PR TITLE
Site Settings: Remove unreleased theme setup interface

### PR DESCRIPTION
**Pull request by tyxla**
#### Changes proposed in this Pull Request

The theme setup interface never got it to staging or production - it only got to wpcalypso in #11914. That was almost 5 years ago, and nothing has changed ever since. I think it's time to remove that interface already, together with state and feature flag.

Question: should we maintain a redirect from `/settings/theme-setup` to `/settings/general`, or since the feature never landed, we can actually remove that route completely?

#### Testing instructions

* Verify the removed code is not in use.
* Verify Calypso builds properly and tests still pass.
* Go to `/settings/theme-setup` and verify you're redirected to `/settings/general`
* Go to `/settings/theme-setup/:site` (where `:site` is one of your sites) and verify you're redirected to `/settings/general/:site`.
* Go to `/settings/general/:site` (where `:site` is one of your sites) and verify the Site Tools menu looks well.

### CODE REVIEW

**Comment by noahtallen** [comment]
cc @kwight if you have any thoughts?

**Comment by kwight** [comment]
Sure, rip it all out!

**Comment by tyxla** [comment]
Thanks @noahtallen @kwight! I'll wait for a review before sending it to the history books 😉

**Comment by tyxla** [comment]
I'd love to get a review of this one. Just rebased to keep it fresh.

**Review by kwight — APPROVED** [review]

**Comment by kwight** [comment]
I tested with the calypso.live link, everything looks great to me. Thanks for cleaning this up! ✨

**Pull request merged**
