### PR TITLE
Signup: DSS: Show loading overlay during image preloading

### LINKED ISSUE #1163: Signup: DSS: Don't show images until they're loaded
Right now images load slowly. We try to handle this by waiting ~250ms before showing the preview, but depending on the browser and the connection speed, that may not be enough. It would be nice to avoid this guessing game, though.

This is tricky, but it may be possible. My idea is to try loading the image outside of the viewport, [tracking its `onload` event](http://blog.teamtreehouse.com/learn-asynchronous-image-loading-javascript), then updating the images in the previews. 

Tracking the `onload` event of the images in the previews themselves seemed at first like it may make more sense, but there are a few problems:

1. From what I can tell, the `onload` event can only be tracked when injecting the image via javascript (doubly tricky in React, see [this module](https://github.com/hzdg/react-imageloader)). That would be a lot of extra work for each preview.
2. Some previews use CSS backgrounds instead of `img` elements, and AFAIK that can't be tracked.

My hope is that if the image is loaded elsewhere on the page, the browser will be intelligent enough to cache it locally and just use the cached copy inside the previews.

### PR DESCRIPTION
**Pull request by sirbrillig**
Fixes #1163 

## Testing

Load http://calypso.localhost:3000/start/dss/ and try searching for words. Make sure that the images load correctly and with very little or no flicker of unstyled previews.

Try the following types of search events to look for strange behavior:

1. Type a search very slowly.
2. After typing a multi-word search, press backspace several times to delete the last word.
3. Clear the search field either with the 'X' or with select-all + backspace.
4. Slowly type a search for one word (e.g., "favorite") and then add another word (e.g, "favorite meal").
5. Search for one word, then search for a different word.
6. Search for one word, then search for a different word, then repeat the search for the first word again.
7. Search for one noun (e.g., "game"), then pluralize it (e.g., "games").
8. Search for something that returns no results (e.g., "asdasdlkjasdljs").

### CODE REVIEW

**Comment by sirbrillig** [comment]
ping @kwight for review

**Comment by kwight** [comment]
SUH-WEET. Looks great. :+1:

**Comment by kwight** [comment]
Oh @sirbrillig , you've replaced tabs with spaces in `style.scss`.

**Comment by sirbrillig** [comment]
> you've replaced tabs with spaces in style.scss.

@kwight the other way around. https://github.com/Automattic/wp-calypso/commit/da405c57308a16cd4dfd5760f7524e18d00fb7a2

**Comment by sirbrillig** [comment]
Also, I found a race condition having to do with how `ImagePreloader` works: try typing `games` very slowly. The overlay sticks around forever. I'm working on that now.

**Comment by sirbrillig** [comment]
There. That should fix it.

**Comment by kwight** [comment]
Hm, now I get a flash of the default screenshots right before the white overlay kicks in :| And yep, I hadn't pulled to see the tabs.

**Comment by sirbrillig** [comment]
hm... now I'm seeing that too. back to research...

**Comment by sirbrillig** [comment]
ok, I have a few possibilities I've tried, but they all flicker one way or another:

1. Show the image previews behind the white overlay as they are loading.
2. Show the default screenshot behind the white overlay any time loading is going on.
3. Show an opaque overlay during any loading.

I think we need to decide what we want it to look like while the search is in-progress. Ideally I'd say we want no image changes while the search is in-progress, and no flickering as it renders the searched image, but what does that look like, exactly? How does the code know when the user has actually stopped typing? We may need to disable search-as-you-type to get it.

**Comment by sirbrillig** [comment]
With the last commit I went with option 1 in my list above

> Show the image previews behind the white overlay as they are loading.

It's actually looking pretty good.

**Comment by kwight** [comment]
With the latest changes, we don't go back to seeing the default screenshots while the results image loads in, but I prefer this. Seeing the new image load over the old image (and not confusing people by flashing the default screenshots) is a better experience.

**Comment by kwight** [comment]
LGTM :+1:

**Pull request merged**
