### PR TITLE
A4A: improve referral dashboard cards layout

### PR DESCRIPTION
**Pull request by andrii-lysenko**
Resolves https://github.com/Automattic/automattic-for-agencies-dev/issues/1579

## Proposed Changes

This PR refactors Referral Dashboard Cards UI to be more responsive and aligned with designs: fuufP6VNfZXYmvLsTRWRlG-fi-8332_118153

If you notice better ways to organise styles please let me know.

Note: tooltips, info are not yet consistent and will be addressed in a separate task.

| Desktop | Mobile |
| --- | --- |
| Screenshot 2024-12-16 at 10 12 09 AM | Screenshot 2024-12-16 at 1 35 45 PM |
| Screenshot 2024-12-16 at 1 58 30 PM | Screenshot 2024-12-16 at 1 58 22 PM |

## Testing Instructions

- Using live link below navigate to `/referrals/dashboard` and check cards responsiveness and compare with designs. 

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
    - [ ] For UI changes, have we tested the change in various languages (for example, ES, PT, FR, or DE)? The length of text and words vary significantly between languages. 
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Review by travisw — COMMENTED** [review]
I haven't looked very closely yet but it's looking good in my testing so far. I can look more first in the morning. 

One thing that's a little confusing to me is the "footer" naming (eg. `FooterInfo`). Maybe I'm missing something but are these cards or popovers somehow shown near the bottom as a footer in some contexts?

**Review by tiagonoronha — APPROVED** [review]
This seems to works as described, so I'm approving it. 

But I think @travisw is right, perhaps we could use a name like `CardTooltip` instead of `FooterInfo`. :)

**Comment by andrii-lysenko** [comment]
Thank you both for review. 
As per footer, my thought was that it's a `footer` of the card, but apparently it's not look that way, so I will change to something like `CardInfo`.

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/17067148

Some locales (Hebrew, Japanese) have been temporarily machine-translated due to translator availability. All other translations are usually ready within a few days. Untranslated and machine-translated strings will be sent for translation next Monday and are expected to be completed by the following Friday.

Thank you @andrii-lysenko for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/17067148).

**Pull request merged**
