### PR TITLE
List Views: Correct Copy Link styling.

### PR DESCRIPTION
**Pull request by kwight**
This PR makes the styling for the Copy Post menu item a little more resilient to `.button` changes elsewhere.

**Master**
Screen Shot 2019-10-31 at 1 56 10 PM

**This branch**
Screen Shot 2019-10-31 at 1 57 24 PM

#### Testing instructions

1. Load this branch locally or with `calypso.live`.
2. Go to a site's posts or pages list view (eg. `/posts/my`).
3. Open an ellipsis menu, and verify the Copy Link item is styles correctly (on hover too).

### CODE REVIEW

**Comment by shaunandrews** [comment]
The link icon and the text look slightly misaligned to my eye. Like, maybe the icon should go up 2-4px?

Otherwise, 🚢

**Comment by olaolusoga** [comment]
+1 to Shaun's comment. Also, it doesn't look "Copy Link" doesn't look absolute left aligned with the other text (see screenshot below—red line). The screenshot also move the icon up a few pixels like Shaun suggests.

alignment

**Comment by olaolusoga** [comment]
+1 to Shaun's comment. Also, it doesn't look like "Copy Link" is absolutely left aligned with the other text (see screenshot below—red line). The screenshot also moves the icon up a few pixels like Shaun suggests.

alignment

**Comment by kwight** [comment]
Yep, alignment was off because of some line height and padding inconsistencies – fixed in cad4105e50c4290ad6949969da00bb5787b85200.

Screen Shot 2019-11-05 at 1 35 18 PM

**Pull request merged**
