### PR TITLE
Components: Provide methods for retrieving back/forward URL to Wizard

### PR DESCRIPTION
**Pull request by tyxla**
This PR updates the `Wizard` component to pass the `getBackUrl` and `getForwardUrl` methods to the step components.

This is pretty useful for being able to navigate back/forward within a wizard from within the step itself.

To test:
* You can use #20360 (it contains this PR) and follow its test instructions.

### CODE REVIEW

**Comment by ockham** [comment]
cc @donnapep :slightly_smiling_face:

**Comment by AnnaMag** [comment]
Thanks @tyxla, tested 👍 💯 

IMHO it is a handy and clean solution, and adds to flexibility ( step size can vary and we could re-use in subsequent -UX improved- iterations). This change would save us from storing prev/next urls in the state or refs etc, am I grasping it fully?

**Comment by ockham** [comment]
I'm slightly torn on this. It imposes an API on step components. If possible, I'd rather keep things isolated and encapsulated (i.e. rely on `Wizard` to take care of all things navigation). Can you remind me what was the use case for this?

**Comment by tyxla** [comment]
@ockham the rationale behind this is to allow steps to blindly navigate backward or forward, without having to include any logic for "next" or "previous" step. It will be useful for the in-step buttons that lead to the next step, and will allow us to have the logic for determining the steps only in 1 place (without the necessity to have prev/next step logic in the steps themselves).

Also, we still rely on `Wizard` to take care of the navigation; we only allow steps to access it too.

**Comment by ockham** [comment]
Okay, let's go with this then!

**Pull request merged**
