### PR TITLE
Ensure that all email management views send Tracks page views

### PR DESCRIPTION
**Pull request by fredrikekelund**
#### Proposed Changes

* Send Tracks page view events for all email management pages (two pages were previously missing these).
* Lift `PageViewTracker` components higher up in the component tree. There is a fairly intricate co-dependence between `index.js`, `controller.js`, `paths.js` and the different page components. To reduce the components' dependence on `paths.js`, I found it logical to put `PageViewTracker` at the `controller.js` level. This is already being practiced in [`calypso/my-sites/domains/controller.jsx`](https://github.com/Automattic/wp-calypso/blob/trunk/client/my-sites/domains/controller.jsx)

#### Testing Instructions

Most email management views were already submitting page view events, but since I've modified the placement of `PageViewTracker`, I have tested all affected views within the email management section.

The [Tracks Vigilante browser extension](https://github.com/Automattic/tracks-chrome-extension) is helpful when testing these changes – it sniffs the network traffic and displays Tracks requests in a more readable manner than the DevTools Network panel.

To test these changes, ensure that each of the following slugs submit a `calypso_page_view` event:

##### Doesn't require an existing subscription
/email/:domain/purchase/:site
/email/:domain/compare/:site

##### Requires any subscription
/email/:site
/email/:domain/manage/:site

##### Requires a Google Workspace domain
/email/:domain/google-workspace/add-users/:site

##### Requires a Titan domain
/email/:domain/titan/manage-mailboxes/:site
/email/:domain/titan/new/:site
/email/:domain/titan/set-up-mailbox/:site
/email/:domain/titan/manage/:site (**did not submit page view events previously**)
/email/:domain/titan/set-up-mailbox/thank-you/:site (**did not submit page view events previously**)

##### Requires an email forwarding domain
/email/:domain/forwarding/add/:site

### CODE REVIEW

**Review by stephanethomas — APPROVED** [review]
Changes look good, and work great!

> To test these changes, ensure that each of the following slugs submit a calypso_page_view event:

I've also tested the upsell in the domain purchase flow at `/domains/add/:domain/email/:site`.

> Lift PageViewTracker components higher up in the component tree.

I like the idea of having all page view trackers in the controller, so it's easy to locate them, and to make sure they are consistent. However, one thing to keep in mind with that approach is that we may count views for certain pages even if we don't end up displaying them - in the following two pages we indeed redirect users to another page if some data is missing or invalid:

https://github.com/Automattic/wp-calypso/blob/9fb7ac149e55361c0c3a9639ad0caa5e15fc88b0/client/my-sites/email/titan-add-mailboxes/index.jsx#L247-L248

https://github.com/Automattic/wp-calypso/blob/27ac28a2346dcfa88e3e152ac63b04d4ea3e9176/client/my-sites/email/titan-set-up-mailbox/index.js#L54-L58

I'm not sure if that's really an issue though. I guess it depends on how you define what a page view is, something that I don't think we have a good definition for. After all, even if the user is redirected they were trying to load a specific page, and it's useful to know that.

**Comment by fredrikekelund** [comment]
Good point about the redirection logic in those components! 

I guess both of those conditions are edge cases and you could argue that they're kinda irrelevant in the big picture of page view stats...

But one possible (and fairly simple) solution would be to pass `PageViewTracker` as a child of `TitanAddMailboxes` instead of as a sibling. That way, it won't render if `TitanAddMailboxes` redirects and returns early. WDYT?

```js
emailManagementNewTitanAccount( pageContext, next ) {
	pageContext.primary = (
		<CalypsoShoppingCartProvider>
			<TitanAddMailboxes
				source={ pageContext.query.source }
				selectedDomainName={ pageContext.params.domain }
			>
				<PageViewTracker
					path={ paths.emailManagementNewTitanAccount( ':site', ':domain' ) }
					title="Email Management > Add Titan Mailboxes"
				/>
			</TitanAddMailboxes>
		</CalypsoShoppingCartProvider>
	);

	next();
},
```

**Comment by stephanethomas** [comment]
> But one possible (and fairly simple) solution would be to pass PageViewTracker as a child of TitanAddMailboxes instead of as a sibling. That way, it won't render if TitanAddMailboxes redirects and returns early. WDYT?

That is a very elegant solution. I'm not sure if it's worth the effort though, you made a good point about fixing cases that are probably insignificant:

> > I guess both of those conditions are edge cases and you could argue that they're kinda irrelevant in the big picture of page view stats...

**Comment by fredrikekelund** [comment]
Let's opt for simplicity then and keep it the way it is!

**Pull request merged**
