### PR TITLE
Add/filterbar scafolding to the activity log

### PR DESCRIPTION
**Pull request by enejb**
Testing out the new filterbar. 

screen shot 2018-09-11 at 11 00 14 am

### CODE REVIEW

**Comment by MichaelArestad** [comment]
How do I test this? Do I need to be on a particular kind of site?

I'm not seeing it on my site's Activity Feed.

**Comment by MichaelArestad** [comment]
After initial testing, I think it looks pretty dang nice.

Some styling suggestions:
* I would make the border radius 5px on the tokens
* I think @keoshi might have some tweaks for the checkbox list in the popover (particularly spacing), but I think it largely looks great.

As for functionality, I am starting to think we'll want to change the text/format of the "All activity types" checkbox into something that selects or deselects everything. However, I think we can save that for a future PR once we have had more time with this version.

**Comment by keoshi** [comment]
Here's how the date range selection could work:

al-date-range

**Prototype** here: https://automattic.invisionapp.com/share/43O0FO4KJUZ

More context in p9rlnk-vb-p2 #comment-2787

**Comment by joanrho** [comment]
>We might want to experiment with populating the token, but a) having a click outside the popover confirm the selection or b) add a button to the popover once the selection is changed.

@keoshi How about an "apply" button or text link, like in one of the examples we shared on the hangout?

**Pull request merged**
