### PR TITLE
Make it harder to break Calypso

### PR DESCRIPTION
**Pull request by dmsnell**
- Stop transforming imports from `state/selectors`
 - Makes import paths explicit
 - Allows IDEs to do their job indicating when an import is or isn't valid
 - Enables auto-completing selector imports
 - Reconnects the disconnection between source code and filesystem
 - Speeds up the build process by doing less

See #21811 for previous work.

How's this for a **size diff**?
http://iscalypsofastyet.com/branch?branch=framework/stop-transforming-imports
```js
Delta:
chunk                                                                                          stat_size    parsed_size    gzip_size
async-load-blocks-inline-help-popover~help                                                          +0 B           +0 B         -1 B  (-0.0%)
async-load-components-web-preview-component~async-load-design-blocks~posts-custom~posts-pages       +0 B           +0 B         -4 B  (-0.1%)
async-load-design-blocks                                                                            +0 B           +0 B         -2 B  (-0.0%)
async-load-post-editor-media-modal~media~post-editor                                                +0 B           +0 B         +1 B  (+0.0%)
async-load-reader-feed-stream~async-load-reader-site-stream                                         +0 B           +0 B         +1 B  (+0.0%)
build                                                                                               +0 B           +0 B         +5 B  (+0.0%)
checklist                                                                                           +0 B           +0 B         -2 B  (-0.0%)
checkout~customize~plugins~purchases~settings~theme~themes                                          +0 B           +0 B         -9 B  (-0.1%)
checkout~plugins                                                                                    +0 B           +0 B         -2 B  (-0.0%)
manifest                                                                                            +0 B           +0 B         +1 B  (+0.0%)
plugins                                                                                             +0 B           +0 B         -2 B  (-0.0%)
post-editor                                                                                         +0 B           +0 B         +1 B  (+0.0%)
reader                                                                                              +0 B           +0 B         -2 B  (-0.0%)
settings~settings-discussion~settings-security~settings-traffic~settings-writing                    +0 B           +0 B         +1 B  (+0.0%)
stats                                                                                               +0 B           +0 B         -4 B  (-0.0%)
themes                                                                                              +0 B           +0 B         +1 B  (+0.0%)
woocommerce                                                                                         +0 B           +0 B         -1 B  (-0.0%)
```

### CODE REVIEW

**Comment by aduth** [comment]
IMO: The explicit import paths are needlessly verbose, and make for a degraded developer experience.

Not sure where Calypso stands these days on proper tree-shaking, but named imports from an index of selectors seems like it should be an end-goal. 

`transform-imports` is no good, but it was always meant as a temporary bandaid fix. IDEs should support the native import semantics. Unsure if that's an issue introduced by `transform-imports` or simply unsupported by the editors themselves.

**Comment by dmsnell** [comment]
> make for a degraded developer experience.

thanks for reviewing @aduth!

actually I've felt like the mangled import statements are a major degraded developer experience since they went in. it breaks my IDEs and it wipes out my auto-complete, makes it easy to make mistakes on imports, further it's strange that we're making matches to functions via an implicit filename mapping.

> IDEs should support the native import semantics

IDEs _do_, which is why the import transform breaks them, because the transform breaks native import semantics.

> Not sure where Calypso stands these days on proper tree-shaking, but named imports from an index of selectors seems like it should be an end-goal.

This is the third iteration of my attempt to kill the transform. Webpack doesn't tree-shake appropriately. `webpack4` was magically supposed to have fixed the bug that made `export * from …` not bloat the build but it didn't. Magically `webpack5` is supposed to solve it…that is, each time I tried it bloated `build` by over 100 KBgz.

Once webpack doesn't choke I'd be happy to make `state/selectors/index.js` with a big list of re-exports and at that point we can do `import { [autocomplete] } from 'state/selectors'` but until then it's either stay with lying source code or be explicit.

---

obviously I feel strongly about this so please don't mistake my tone for more than it is - trying to make my case when I think that the arguments in favor of keeping the transform don't actually hold their weight.

**Comment by aduth** [comment]
Sure, it all seems to stem from the import transform, which was added for the purpose of assuming and enabling an end-goal of `import { getFoo } from 'state/selectors';`. It's unfortunate it's lived as long as it has, and if there's not an immediate solution to the noted incompatibilities, it's certainly worth reevaluating. Maybe worth highlighting that there is a cost associated with this change: reeducation of developers in applying the new semantics (and once more if it's ever changed back), and the time spent _typing all those letters_ 😪 .

**Comment by dmsnell** [comment]
> and the time spent typing all those letters

aha! time _saved_ by using auto-complete 😉 

> for the purpose of assuming and enabling an end-goal of import { getFoo } from 'state/selectors';

I'm pretty sure we hav the same end-goal. in fact my thinking was that with all of this stuff normalized and honest then we can more easily update the code automatically.

we can probably just import the `default` as-is. I think I'm hung on how I had to re-export them which was `export { default as … } from '…'` - let me update and make sure it works…

**Comment by dmsnell** [comment]
> I like the idea of this, but I think this PR should include a state/selectors/index.js so that import syntax can stay the same.

@nylen I wanted this too but including that is what made `build` bloat by over 100 KBgz. There are either bugs or oddities preventing that from being practical but as soon as it's available we can switch over. We thought it would have worked by now but it still bloats.

I've tried adding the pure-module pragma to a `state/selectors/package.json` config as well with no luck - the re-exports bloat.

**Comment by jsnajdr** [comment]
Is there a consensus that we'd prefer to keep `state/selectors` as the umbrella module to import from?

If yes, the Babel transform should be replaced with `state/selectors/index.js` that reexports the individual selectors. Together with `sideEffects: true` in `package.json`, bundle size shouldn't get inflated with Webpack 4.

@dmsnell attempted this in #21811 and didn't succeed, but that was before the Webpack 4 and Babel 7 upgrades.

After spending 40 minutes on the issue now, I couldn't make the `index.js` work: I'm getting some mysterious errors I don't understand. But if we agree that we want to keep the `state/selectors` import, it's worth investigating and making it work.

**Comment by dmsnell** [comment]
> @dmsnell attempted this in #21811 and didn't succeed, but that was before the Webpack 4 and Babel 7 upgrades.

slight correction: I tried this after webpack4 and babel 7 upgrades and it didn't work. I just never pushed the code out that did it since it failed and I had to move along.

**Comment by jsnajdr** [comment]
Thanks for the correction! Did you create an `index.js` file with lines like this?
```js
export getSitesItems from './get-sites-items';
```
I don't know why, but I'm getting errors like this:
```
/Users/jsnajdr/src/wp-calypso/build/bundle.js:140690
    return _getSitesItems2.default;
                           ^
TypeError: Cannot read property 'default' of undefined
```

**Comment by dmsnell** [comment]
> Did you create an index.js file with lines like this?

Those are going to be invalid re-exports. As far as I understand we need to re-export the default exports…

```js
export { default as getSitesItems } from './get-sites-items';
```

**Comment by jsnajdr** [comment]
> Those are going to be invalid re-exports.

That's a source of some confusion for me. Reading the [MDN article](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/export) and the [spec](https://tc39.github.io/ecma262/#sec-exports), I get the impression that `export { default as x }` and `export { x as default }` are not compliant. If anything, they work with a regular named export whose name is "default", not the default export. With some build tools it works, with others it doesn't.

When I tried the `export { default as getSitesItems }` syntax, it didn't work.

There is a [proposal](https://github.com/tc39/proposal-export-default-from) to make the following syntax valid:
```js
export getSitesItems from './get-sites-items';
```
There is a Babel transform `@babel/plugin-proposal-export-default-from` that implements this proposal and it's in our `.babelrc.js`. So it should work. But it doesn't and I don't yet know why.

**Comment by dmsnell** [comment]
> When I tried the export { default as getSitesItems } syntax, it didn't work.

That's odd. It worked for me when I did this stuff before. Admittedly I don't know the spec well enough to have any confidence in my understanding. What broke for you?

**Comment by sirreal** [comment]
> Reading the [MDN article](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/export) and the [spec](https://tc39.github.io/ecma262/#sec-exports), I get the impression that `export { default as x }` and `export { x as default }` are not compliant. If anything, they work with aegular named export whose name is "default", not the default export.

I've spent a bit of time with these specs and I believe these are fine. My interpretation is that a "regular named export whose name is `default`" is exactly what the default export is. I understand that reading [around here](https://tc39.github.io/ecma262/#sec-exports-static-semantics-boundnames):

> _ExportDeclaration_ : **`export`** **`default`** _HoistableDeclaration_
> 1. Let declarationNames be the BoundNames of HoistableDeclaration.
> 1. If declarationNames does not include the element "*default*", append  "*default*" to declarationNames.
> 1. Return declarationNames.

`export default [HoistableDeclaration | ClassDeclaration | AssignmentExpression]` are just ways of binding a local name to the export whose name is `default`. The only reasons I know of to treat `default` as a special export are the following:

- You can bind the export with the special syntax `export default …`.
- You can import the default without braces `import DefaultExport from …`.

Sometimes I question the benefit of even using the default as it seems to add little benefit other than being able to export things that may not have local names, like classes and functions (`export default function() {}`).

Given all of this, `default` should behave just like any other export when used inside the braces of an export clause.

---

> There is a [proposal](https://github.com/tc39/proposal-export-default-from) to make the following syntax valid:
> ```js
> export getSitesItems from './get-sites-items';
> ```

This is something I noticed in the spec, the [only export variations](https://tc39.github.io/ecma262/#sec-exports) that include a from clause are those of the following forms:

- **`export`** **`*`** _FromClause_ **`;`**
- **`export`** _ExportClause_ _FromClause_ **`;`**

There's no special syntax for binding the default from another module to a different exported name, but that should be achievable like this:

```js
export { default as whateverExportedName } from '…';
```

**Comment by blowery** [comment]
@jsnajdr some similar work in #24049, I ran into the same issue with re-exports breaking.

**Comment by jsnajdr** [comment]
I tried to implement a `state/selectors/index.js` umbrella package with reexports and a `sideEffects = false` flag in #24913.

Bundle size is not inflated. [ICFY](http://iscalypsofastyet.com/branch?branch=add/selectors-package) reports some random reshuffling of code between shared chunks, but the whole `state/selectors` directory is not bundled into `build` chunk as we fear and as would happen with Webpack 4.

But there is a bigger problem: the built app crashes when dereferencing some imports. Imports that should be defined are not. It's because the umbrella package creates circular dependencies between packages. Consider this example:

_numbers.js:_
```js
export { default as two } from './two';
export { default as one } from './one';
```

_one.js:_
```js
export default 1;
```

_two.js:_
```js
import { one } from './numbers';
export default one + one;
```

_app.js:_
```js
import { two } from './numbers';
console.log( two );
```

One would expect to see "2" logged to the console, but it will either log "NaN" or will crash, depending on Webpack version and config.

There is a circular dependence: _app.js_ imports _numbers.js_ that imports _two.js_ that imports _numbers.js_.

Modules are evaluated when they are imported for the first time and exports are bound to their names. When _two.js_ imports _numbers.js_, _numbers.js_ is in the middle of being evaluated and the `one` import is not yet bound. That's why `one` is not `1`, but, depending on the implementation, either `undefined` or a getter call that crashes.

The same thing happens inside `state/selectors`, too: a selector in `state/selectors` depends on another one in `state/selectors` and if the order in the _index.js_ is not right, the app crashes.

The `state/selectors/index.js` idea won't work unless the reexports are ordered very precisely.

And even if the order is right, there is another round of circular dependencies, where a `state/selectors` selector depends on a selector from `state/sites/selectors` and vice versa.

It's possible to keep the dependency graph right in a small app (like @aduth's [dones project](https://github.com/aduth/dones/blob/master/src/state/selectors/index.js) he mentioned in the p4TIVU-8KD-p2 discussion) but it won't work on Calypso scale.

**Comment by nylen** [comment]
Following up on my original comment:

> I like the idea of this, but I think this PR should include a `state/selectors/index.js` so that import syntax can stay the same.

Thanks for investigating - it seems like this isn't feasible for several reasons.

Reiterating the original points from the PR, I think all are valid and are good improvements:

> - Makes import paths explicit
> - Allows IDEs to do their job indicating when an import is or isn't valid
> - Enables auto-completing selector imports
> - Reconnects the disconnection between source code and filesystem
> - Speeds up the build process by doing less

This PR also simplifies things by removing a custom layer that is "doing more than necessary" and is unexpected behavior for developers new to our codebase.

**Comment by blowery** [comment]
> I'm afraid that Webpack would have to understand the actual code to detect cycles reliably.

Maybe I'm missing something, but both examples are cycles, it's just that one works and one is broken. I'd be happy to avoid cycles entirely, even if they "work".

**Comment by blowery** [comment]
> well I'm sad that in the end we probably won't be able to get what we want but I'm still in favor of merging this to simplify the build and match our code with the reality more explicitly.

totally agreed, sorry to take this off on a tangent.

**Comment by dmsnell** [comment]
- Stop transforming imports from state/selectors
 - Makes import paths explicit
 - Allows IDEs to do their job indicating when an import is or isn't valid
 - Enables auto-completing selector imports
 - Reconnects the disconnection between source code and filesystem
 - Speeds up the build process by doing less

See #21811 for previous work.

**Comment by jsnajdr** [comment]
> Maybe I'm missing something, but both examples are cycles, it's just that one works and one is broken. I'd be happy to avoid cycles entirely, even if they "work".

The example cycle that works does so because it's a specified behavior: it's supposed to work if the binding is used that way. ES modules try to support cycles if possible. Unlike Common JS, where neither example would work.

I understood "teach webpack to yell at us" as getting a Webpack bug fixed. But there is no bug.

Using an extra plugin to detect cycles and fail the build is not a bad idea. I'm not sure if it will work -- in some large C++ and Java project I've seen in the past it was impossible to get rid of circular dependencies -- but it's definitely worth trying.

**Pull request merged**
