### PR TITLE
Media library Accessibility enhancements

### PR DESCRIPTION
**Pull request by jakejones1984**
media_a11y

Enhances the Media library gallery view to make it more accessible. The follow updates have been included

- Ability to use `TAB` to move between the photos in the list - `tabIndex` attribute applied to bring thumbnails into the page's focusable elements
- Ability to use `ENTER` or `SPACE` to select a photo
- `aria-role` added to item to denote it as a button-like interactive element
- `aria-pressed` attribute set according to items "selected" status

### CODE REVIEW

**Comment by jakejones1984** [comment]
Hi @ryelle. Sorry for the delay in coming back. I've been away.

> The only thing I'd ask to be fixed before merge is a focus style on selected items. If I have multiple items selected, I don't know which I'm currently focused on without just trying to toggle it.

Resolved with a subtle tweak. Do you think this is obvious enough?

media_selected_focus_style

> On sites with a lot of media, I need to tab through all the items before I can hit insert (you can replicate by selecting the "Free photo library" and searching for "tech" - it seems to infinitely load more items). This issue is too broad for this PR, but could use some thought.

Absolutely agreed. There is a [strong argument that Infinite Scrolling is not at all good for a11y](http://simplyaccessible.com/article/infinite-scrolling/). I'm not sure I will have time remaining to complete a deeper review into this issue but it should be raised as an issue.

 
> Disabling eslint for this line shouldn't be necessary anymore, since the div has been remapped to role=button

I've removed that line and all was well. Thanks for the catch!

**Comment by alisterscott** [comment]
The desktop tests are failing because the node version is different - doesn't matter

**Comment by drw158** [comment]
I think the focus style would be a bit better if you adjusted the selected style. I would do this for the selected style:

- increase border size 1 or 2 px
- make it an inside border (this might be hard to do actually...maybe use outline or boxshadow)

and for the focused style just just keep the outside border and maybe make the shadow a bit bigger.

**Comment by jakejones1984** [comment]
media_selected_hover_focus_style

Updated styles as per conversion with @drw158.

**Comment by drw158** [comment]
looks good

**Comment by getdave** [comment]
Still intending to land this at next available opportunity. Will resolve conflict first.

**Pull request closed without merging**
