### PR TITLE
Seller Experience: Add initial translations for updated Woo landing page

### PR DESCRIPTION
**Pull request by markbiek**
#### Changes proposed in this Pull Request

This contains the `translate` calls for all of the new copy on the Woo landing page.

image

Related to #61472

### CODE REVIEW

**Review by sixhours — APPROVED** [review]
LGTM!

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/7171439

Thank you @markbiek for including a screenshot in the description! This is really helpful for our translators.

**Comment by dlind1** [comment]
@markbiek We've received a comment from one of our localization reviewers that it would be more flexible to provide different context for `Upgrade your store` in the header and `Upgrade your store` in the button, e.g.
```
translate( 'Upgrade your store', {
	context: 'Header text',
} );
translate( 'Upgrade your store', {
	context: 'Button text',
} );
```
It's possible to have just one string in both places, but the additional context the translation could sound more natural.

**Comment by markbiek** [comment]
@dlind1 Didn't realize the `translate` function had that option!

I can take care of that shortly.

**Comment by markbiek** [comment]
@dlind1 That's done in #61737

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/7171439).

**Pull request merged**
