### PR TITLE
Reader: Truncate recommendation titles

### LINKED ISSUE #10023: Reader: inline recommendations with very long titles look odd on narrow viewports
We may want to truncate very long titles:

screen shot 2016-12-14 at 14 03 42

### PR DESCRIPTION
**Pull request by raoulwegat**
Limit reader recommendation titles on narrow screens to two lines using line clamping. Resolves #10023.

screen shot 2017-01-12 at 10 32 43 pm

cc @bluefuton

### CODE REVIEW

**Comment by bluefuton** [comment]
@raoulwegat looks good! Can we add a clamp to 3 lines on larger viewports too? Bit of an edge case, but if we did get a monster title it would do this:

screen shot 2017-01-13 at 14 16 22

**Comment by fraying** [comment]
If we do this here, we should also do it on the search page default and the fullpost page More blocks, so that it's consistent.

**Comment by raoulwegat** [comment]
@bluefuton Three line clamp on larger viewports done in 1cd5954

**After**
screen shot 2017-01-18 at 12 09 49 am

@fraying: the selector I've made these changes to also make the changes to the search page default and the fullpost page More blocks. :-)

**Search Page default**
screen shot 2017-01-18 at 12 19 56 am

**Fullpost More block**
screen shot 2017-01-18 at 12 19 02 am

**Comment by samouri** [comment]
@raoulwegat is the use of `16` everywhere as a value for line-height good practice? (not that its you, we've been doing it forever).  I was thinking recently that it would be a major headache if Calypso changed its line-height.

Would it be better to turn this into a variable?
`$reader-line-height 16px`

**Comment by samouri** [comment]
This worked great for me! Good job @raoulwegat!

Tested:
- [x] long content titles on all breakpoints. fades after two lines for small breakpoints and 3 for larger breakpoints.

**Comment by fraying** [comment]
LGTM!

**Comment by raoulwegat** [comment]
@samouri: I'm a massive fan of SASS variables. Not only in giving flexibility to update multiple values from one place, but I think they also improve code readability. Well structured variable names can be like code comments on each declaration's value :-) They can give context too. Seeing something like `$header-font-size__medium` says a lot more than `18px`. It can also imply that there's likely a `__small` and `__large`. It's like bringing the typographic hierarchy directly into code in a way that anyone can understand.

**Pull request merged**
