### PR TITLE
JPC: add instructions link

### PR DESCRIPTION
**Pull request by johnHackworth**
Fixes https://github.com/Automattic/wp-calypso/issues/9307

This PR adds a link that mirrors the modal window button action to the example screenshots of the jetpack install / activation instructions 

image

How to test
=========
0. You need a self-hosted site without an installed jetpack (or a not active one)
1. Go to http://calypso.localhost:3000/jetpack/connect and enter the url of your site
2. You should get a modal window with some instructions on how to get your jetpack on
3. Click on any of the images. They should take you to the first step of the process in your wp-admin

ping @rickybanister @keoshi @jeffgolenski

### CODE REVIEW

**Comment by keoshi** [comment]
Works beautifully on my end!

**Comment by rickybanister** [comment]
Can we add a hover state to the cards? 

It could be nice to use the hover style we used to use on Reader cards for this.

@keoshi do you have another idea for a card hover style based on your new 'add new site' designs?

**Comment by keoshi** [comment]
@rickybanister hm, what are trying to solve by having a card hover state? Shouldn't the button still be the primary action on this view? Speaking of which, we should probably add more `margin-top` to it, so it has more whitespace around and better visibility?

**Comment by johnHackworth** [comment]
@rickybanister @keoshi  I added the reader cards hover shadow:

image

**Comment by keoshi** [comment]
I see a different styling, but looks good to me!

screen shot 2016-11-22 at 12 39 09

**Comment by rickybanister** [comment]
@keoshi are you still concerned with styling the hover state? My thought was we might as well make the entire page an anchor since there is only one way forward from here. I don't care if users click the primary button or the images as long as they are able to do what they want to do. 

We're also talking about trying other approaches than manual install, so let's just see how this goes for now? We can track clicks on the images as well.

**Comment by rickybanister** [comment]
Ah, you're totally right. We can adjust that. @johnHackworth I'll handle moving the hover to the image—it should only wrap the browser. I forgot that we had other links in our descriptive text.

**Comment by johnHackworth** [comment]
ping @rickybanister ! did you manage to free some time to work on this?

**Comment by rickybanister** [comment]
@johnHackworth I'm going to have @keoshi take a look now, sorry for the massive delay.

**Comment by keoshi** [comment]
Updated the styles to reflect the hover state only on the browser portion:

image

Would appreciate if you could give this a quick review when you have time, @johnHackworth.

**Comment by rickybanister** [comment]
I think this is definitely a better solution, sorry for suggesting the previous boondoggle. 

The darker blue/gray border might be a little heavy however. What if we used more of the diffuse shadow that you (@keoshi) used in your recent Add New WordPress landing page?

**Comment by keoshi** [comment]
@rickybanister tried it with a subtler yet larger `box-shadow` and it really didn't work or/and wasn't visible enough. I can try refining it further though.

**Comment by rickybanister** [comment]
Sounds good @keoshi, this is much better than what we have so let's get it merged.

**Pull request merged**
