### PR TITLE
Jetpack Plans: New UI & switch to redux process for the automated setup

### PR DESCRIPTION
**Pull request by ryelle**
This adds a much nicer UI for automatically setting up plugins purchased in a wordpress.org plan. After purchasing a plan, the user will be redirected to this page (redirect not set up yet), where we will try to install & set up the plugins they've just bought.

Preview: https://cloudup.com/cLIJ99_Njhu

This depends on #4878 being merged first, as it uses the redux state/actions set up there.

The most basic test:

- Have a connected Jetpack site with Premium or Business, and no VaultPress, Akismet, or Polldaddy installed.
- Visit http://calypso.localhost:3000/plugins/setup/{site}
- Watch as it installs VaultPress, Akismet, and (if you're Business) Polldaddy _(the plugins installed are controlled by a wp.com API response, and can be configured if plans change)_
- Visit your website's wp-admin, you should see a "Welcome to VaultPress" message, and Akismet & Polldaddy will be (silently) set up.
- If you'd rather check this in your database, you'll see the `vaultpress`, `wordpress_api_key`, and `polldaddy_api_key` are all set with your keys.

cc @johnHackworth @rickybanister

### CODE REVIEW

**Comment by rickybanister** [comment]
This is looking really great.

We don't need to redirect here after the plan purchase—the thank you page will offer a link to get going with the auto configuration.

The only other nit I saw was the 'successful configuration' notice—in /plugins we don't use a notice for the 'last updated' messages, it is just text with the same font styles as a compact notice (no background color or icon). To be clearer, we don't need to use a notice once a plugin is successfully installed—we can, but we should omit the icon then remove the background color with style overrides.

**Comment by ryelle** [comment]
> We don't need to redirect here after the plan purchase—the thank you page will offer a link to get going with the auto configuration.

Right, thanks for catching that -- still thinking about how we were doing this before. In any case, the new thank you page isn't set up, so to test you still need to manually visit the page.

> we don't need to use a notice once a plugin is successfully installed

Ah, ok - PR's been updated :)

**Comment by johnHackworth** [comment]
found a not-so-important bug! If you do a localStorage.clear() (so user's sites list is not cached and available when the page loads), it crashes:

image

Probably we should need to control that case and wait until the sites are fetched to render something here. Anyway, when we follow a proper flow (in contrast to just loading /plugins/setup/ directly) this shouldn't happen in any case

**Comment by johnHackworth** [comment]
Related with my previous comment, we probably want to force a sites.fetch when loading this:

image

I already went and enabled manage in my site, and this is going to work after a while, once the sites lists is refreshed and the calypso info about my site is updated, but it would be could if, meanwhile, we can show a placeholder or something

**Comment by johnHackworth** [comment]
Well, I have commit some changes dealing with the cases I talked about up there:

https://github.com/Automattic/wp-calypso/pull/5244/commits/1ef3fd8a743a08a80d5b355f16b3bb2e607d0b7e

This is how it looks when you go to /plugins/setup now with an empty sites list:

untitled screencast 13
( video for better quality... you can't tell the titles placeholder in the gif: https://cloudup.com/cmLhQmS_W72 )


And the same, with a localStorage-cached sites list:
untitled screencast 14

If you see anything wrong or you have any other idea on how to deal with that problem, please, don't  hesitate to rollback my commit :)

**Comment by ryelle** [comment]
@johnHackworth thanks, this looks great! the placeholders are a great touch (imo).

**Comment by ryelle** [comment]
Leaving this as "Needs Review", even with the conflicts. Once #4878 is merged, this can be rebased on master (rather than `add/premium-service-redux`), which should fix the conflicts.

**Comment by ryelle** [comment]
I can't switch the target branch to master, so we need a new PR: #5320

**Pull request closed without merging**
