### PR TITLE
Update large google photos logo

### PR DESCRIPTION
**Pull request by mreishus**
#### Changes proposed in this Pull Request

* Update the large google photos logo used in the media library
  * Splitting this up into multiple PRs since some parts of it aren't straightforward

#### Testing instructions

* Visit the Media Library, then Google Photos

* Before:

* After:

Spacing is slightly different, due to the way the .svg is constructed vs the original .png, I can look into if necessary. 

Related to #56251

### CODE REVIEW

**Comment by obenland** [comment]
That calypso.live environment doesn't work for me, once I authenticated with 2FA it redirects me back to a logged-out state :(

**Comment by mreishus** [comment]
> That calypso.live environment doesn't work for me, once I authenticated with 2FA it redirects me back to a logged-out state :(

Shot in the dark, could you try Firefox to see if it works? I'm seeing the same thing on Chromium incognito, but FF incognito lets me log in.

**Review by obenland — APPROVED** [review]
It turns out it was user error. Looking good, thank you!

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/6644222

Thank you @mreishus for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/6644222).

**Pull request merged**
