### PR TITLE
Add a page navigation dropdown to gutenberg

### PR DESCRIPTION
**Pull request by johnHackworth**
WORK IN PROGRESS:

This PR adds a page navigation dropdown in top of the block editor top bar when the user is editing one of their site's pages

### CODE REVIEW

**Comment by vindl** [comment]
I tried testing this locally but I can't spot the Page navigation dropdown in the header. Is there anything that I might be missing in terms of testing instructions?

**Comment by noahtallen** [comment]
> Is there anything that I might be missing in terms of testing instructions

Maybe some of the newer Gutenberg updates are changing the format of the top bar?

**Comment by johnHackworth** [comment]
oh, folks, sorry for the lack of instructions, I wasn't thinking anyone would try to test this yet!! I'll add some better description today or tomorrow

**Comment by vindl** [comment]
> Maybe some of the newer Gutenberg updates are changing the format of the top bar?

I don't think that would necessarily affect the display since it looks like this should be rendered on top of the iframe. At worst new updates would cause it to be slightly misplaced imo. 🤔

**Comment by sirreal** [comment]
@johnHackworth Can this be closed?

**Comment by noahtallen** [comment]
Closing, since we have the page navigation sidebar now

**Pull request closed without merging**
