### PR TITLE
Jetpack Connection: rename 'skip_user' parameter

### PR DESCRIPTION
**Pull request by sergeymitr**
#### Changes proposed in this Pull Request

Replacing the `skip_user` term with `allow_site_connection` and `SiteOnly`.

#### Testing instructions

Please set the constant `define( 'JETPACK_SHOULD_NOT_USE_CONNECTION_IFRAME', true );` to skip the In-Place flow and go straight to Calypso.
You can also set `define( 'CALYPSO_ENV', 'development' );` to make Jetpack use your local Calypso domain.
You also need to checkout and build Jetpack PR https://github.com/Automattic/jetpack/pull/19734

##### Login page
1. Create a WordPress user with your WP.com email, but log out from WP.com
2. Disconnect Jetpack.
3. Initiate the connection process. You should get redirected to the Calypso login page.
4. Add the GET-parameter `&allow_site_connection=1` to the URL.
4. You should see the "Continue without user account" link in the bottom of the page, click it.
5. You should get redirected to Jetpack Cloud plans page. Start with the free plan.
6. Confirm that you're redirected to Jetpack Dashboard connected on the site level.

##### Approve page
1. Please log into WP.com and disconnect Jetpack.
2. Go to Jetpack and initiate the connection flow. You should get redirected to the "Approve" page.
3. Add the GET-parameter `&allow_site_connection=1` to the URL.
3. Confirm that the button "Continue without user account" **does not** show up.
4. Click "Approve".
5. You should get redirected to Jetpack Cloud plans page. Start with the free plan.
6. Confirm that you're redirected to Jetpack Dashboard fully connected.

##### Registration page
1. Log out of WP.com and disconnect Jetpack.
2. Change your WordPress (not WP.com) email to something random.
3. Go to Jetpack and initiate the connection flow. You should get redirected to the registration form.
4. You should see the "Continue without user account" link in the bottom of the page, click it.
5. You should get redirected to Jetpack Cloud plans page. Start with the free plan.
6. Confirm that you're redirected to Jetpack Dashboard.
7. Disconnect Jetpack, initiate the connection flow again.
9. Find the link "Already have an account? Sign in" below the registration form, click it.
10. You should get redirected to the login form. Confirm the "Continue without user account" button still shows up, click it.
11. You should get redirected to Jetpack Cloud plans page. Start with the free plan.
12. Confirm that you're redirected to Jetpack Dashboard connected on the site level.

Related to #52303

### CODE REVIEW

**Comment by leogermani** [comment]
It all tested well for me, just with a small observation.

On the last test, when I clicked "Already have an account? Sign in" and went to the login page, I had to add `&allow_site_connection=1` to the URL in order to see the option to skip user authentication.

Is that expected?

**Comment by sergeymitr** [comment]
Hi @leogermani.
That's not ok at all, it likely means that the parameter gets lost somewhere along the way.
However, I wasn't able to reproduce the issue. Could you please try it out again?

**Comment by leogermani** [comment]
> Hi @leogermani.
> That's not ok at all, it likely means that the parameter gets lost somewhere along the way.
> However, I wasn't able to reproduce the issue. Could you please try it out again?

Isn't it just because we didn't deploy the wpcom patch yet?

**Comment by sergeymitr** [comment]
@leogermani 
The WP.com patch only affects the login page, which requires explicit passing of the GET-parameter.
The registration page passes it through automatically, and when you click on the "Already have an account" link, the GET-parameter `allow_site_connection` should also get passed there.
This is exactly what happens in my tests, with no WP.com sandbox involved.

**Comment by leogermani** [comment]
Tested it again and it all worked! I must have done something wrong last time.

**Review by leogermani — APPROVED** [review]

**Pull request merged**
