### PR TITLE
Media: fix uploads with # or ? in filename

### LINKED ISSUE #4726: Editor: Media: media files with with non-standard characters cannot be uploaded
When a media file contains a non-standard character the message "file could not be uploaded because the file type is not supported" message is displayed.  However, the same file can be uploaded in both the WP Admin editor and Media Library without issue.

I have found the following characters (which Mac OS will let you use) when present in the filename, will not upload in the editor, but there may be others:

- #
- ?

For example, a filename like `myawesomeimage-1.jpg` can be uploaded but `myawesomeimage#1.jpg` cannot.

#### Steps to reproduce
1. Starting at URL: wordpress.com/post or /page
2. Click Add Media button in editor and try to upload file with # or ? in the filename
3. See error message
4. Open new post or page in WP Admin and try to add the same file
5. Success

### PR DESCRIPTION
**Pull request by gwwar**
Fixes the regression introduced in #5218 Closes #4726 

## Testing Instructions
- Navigate to /post or /page
- Click Add Media button in editor
- Try to upload file with # or ? in the filename

cc @aduth @robobot3000 @rralian @BandonRandon

### CODE REVIEW

**Comment by lamosty** [comment]
Working fine. I just uploaded an image `#3_2nd_Color_flip.jpg` sent to us in #2647763-t and upload was successful.

**Comment by aduth** [comment]
Will this break behavior when `file` is in the shape of a blob wrapper, since `MediaUtils.getFileExtension( file );` may not be capable of determining its extension? Perhaps we need to extend the [`getFileExtension`](https://github.com/Automattic/wp-calypso/blob/bccfe5c45c1aaff1fddd91710c112ddc8edcca8d/client/lib/media/utils.js#L74-L107) and [`getMimeType`](https://github.com/Automattic/wp-calypso/blob/bccfe5c45c1aaff1fddd91710c112ddc8edcca8d/client/lib/media/utils.js#L146-L180) functions to support these objects?

**Comment by gwwar** [comment]
> Perhaps we need to extend the getFileExtension and getMimeType functions to support these objects?

@aduth Seems like a reasonable approach. I assume the logic error here is that we assume any string is a url without checking any uri protocols. I can update the util methods and add units, but if you have any test files handy that'd be useful.

**Comment by aduth** [comment]
@gwwar : Else you might consider adding a condition for when the file is an object including `fileContents` property to pass that property through to `getFileExtension` and `getMimeType` instead.

**Comment by gwwar** [comment]
@aduth Since we accept url fragments I went ahead and added a check to see if our string was a simple filename before parsing it as a url. I'll see if adding blob support isn't too difficult.

**Comment by robobot3000** [comment]
Works fine. Tested adding an image with non-standard chars in the filename via drop, image editor and the file open dialog.

**Comment by gwwar** [comment]
Thanks for the reviews!

**Pull request merged**
