### PR TITLE
Reader Conversations: pass more props down to PostComment children

### PR DESCRIPTION
**Pull request by samouri**
This PR fixes two issues related to Reader `PostComment` replies:
1. commenting
2. the appearance of `Read More`

### CODE REVIEW

**Comment by samouri** [comment]
This regression was introduced here: https://github.com/Automattic/wp-calypso/commit/d0523cc763c189a5afacc8fa39665a4c652b1ff9#diff-5cb2450d6ab45a6e32637779b316cde3L206

a `{...props}` was transformed into individual keys.

**Comment by samouri** [comment]
To test:
1. [ ] ensure you see Read More on long comment-replies in convos tool (but not in fullpost)
2. [ ] ensure you can reply to replies in convos tool.  and cancel the reply. and submit the reply.

**Comment by blowery** [comment]
👀

**Comment by jancavan** [comment]
> ensure you can reply to replies in convos tool. and cancel the reply. and submit the reply.

This is working for replies now, but when I leave a top-level comment, nothing happens. My comment doesn't show up until after a refresh. I can see that it's being added to the caterpillar, but shouldn't that just show up immediately?

Video: https://cloudup.com/c3OCR7qKgnx

**Comment by samouri** [comment]
@jancavan: thanks for the find! We should make it appear instantly and I'll do that in a new pr

**Pull request merged**
