### PR TITLE
Design Picker: Add a site slug fallback for the destination URL

### PR DESCRIPTION
**Pull request by WBerredo**
Fixes https://github.com/Automattic/dotcom-forge/issues/4264

## Proposed Changes

Add a fallback for the site slug when the current selector returns `null`.

## Testing Instructions

* The onboarding flow should behave the same for Partner themes and should land well on the Thank You page
* Test the same flow for custom domains

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

**Comment by epeicher** [comment]
I am testing this PR but I cannot find any Partners themes anymore. Should I select some specific goals during onboarding?

**Comment by WBerredo** [comment]
You should be able to see Solarone and Folio when no goal is selected, both are Partner themes.

**Comment by epeicher** [comment]
> You should be able to see Solarone and Folio when no goal is selected, both are Partner themes.

That's correct, I am going to use one of those for my testing. Thanks!

**Review by epeicher — APPROVED** [review]
I have tested before and after with one of my sites, and I can confirm that the issue was happening before and it is now fixed. Changes LGTM! 🚢 

CleanShot 2023-10-26 at 16 13 52@2x

**Pull request merged**
