### PR TITLE
Checkout: Add Pix payment method

### PR DESCRIPTION
**Pull request by sirbrillig**
## Proposed Changes

This adds a new payment method, Pix, to the list of payment methods available in checkout. Like other payment methods, this will only be available if the shopping cart allows it, so it is not currently enabled.

Payment form             |  Confirmation modal
:-------------------------:|:-------------------------:
Screenshot 2024-01-30 at 6 06 59 PM | Screenshot 2024-02-01 at 3 34 52 PM

~Requires D130371-code~ (That has been merged)

## Testing Instructions

- To use Pix as a payment method option in checkout, first you'll need to have BRL as your currency, and then you'll need to select "Brazil" as the country inside checkout (and a Brazilian postal code like `61919-230`).
- Use Ebanx [test customer info](https://developer.ebanx.com/docs/resources/testCustomerData/) to fill out the Pix form. "CEP" means "Postal code" and "CPF" means "Taxpayer Identification Number".
- Click to submit the payment.
- Use the Ebanx dashboard (you must be an Ebanx account admin) to confirm the payment.
- Verify that the purchase completes successfully.

### CODE REVIEW

**Comment by sirbrillig** [comment]
I also added Jetpack and Akismet logos to the modal:

Screenshot 2024-01-31 at 5 36 50 PM

Screenshot 2024-01-31 at 5 37 36 PM

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/11174947

Some locales (Hebrew, Japanese) have been temporarily machine-translated due to translator availability. All other translations are usually ready within a few days. Untranslated and machine-translated strings will be sent for translation next Monday and are expected to be completed by the following Friday.

Thank you @sirbrillig for including a screenshot in the description! This is really helpful for our translators.

**Comment by sirbrillig** [comment]
Merging this even though the translations are not complete because the payment method is disabled on the backend for now and this will help us get our Call for Testing out.

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/11174947

Thank you @sirbrillig for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/11174947).

**Pull request merged**
