### PR TITLE
Notice component: es6 class refactor

### PR DESCRIPTION
**Pull request by sirreal**
* Update `Notice` to es6 class
* Order properties
* Add `defaultProps.status = 'is-info'` (suggested in https://github.com/Automattic/wp-calypso/pull/13501#issuecomment-301927752)
* Add `defaultProps.icon = null`
* Add `defaultProps.text = null`
* Add linter required `className`
* General cleanup

To test:
* Use this branch
* Ensure tests pass
* Test notices
  * A good place is http://calypso.localhost:3000/jetpack/connect/?url=wordpress.com
  * Pay with [these lines](https://github.com/Automattic/wp-calypso/blob/c56a81d1f44170c10e8599c770c8ebd80e611bcf/client/signup/jetpack-connect/jetpack-connect-notices.jsx#L79-L84)
* Test available props:
  * `className`
  * `duration`
  * `icon` - any valid Gridicon or omit
  * `isCompact`
  * `onDismissClick`
  * `showDismiss`
  * `status`
  * `text`
  * `children`
* Ensure all the behaviour is maintained and new regressions, warning or errors have been introduced.

This component should have no functional changes. This PR simply updates to es6 class and clarifies some internal workings.

### CODE REVIEW

**Comment by timmyc** [comment]
Looks like we have some failing tests here now.

**Comment by sirreal** [comment]
> Looks like we have some failing tests here now.

@timmyc I noticed that, it looks pretty strange. Did you look at the full test output? There's a lot of strange stuff in there that ostensibly shouldn't be affected by this PR. I wonder if something else is broken...

**Comment by timmyc** [comment]
No I was just looking at the circleci output at https://circleci.com/gh/Automattic/wp-calypso/49819 - perhaps try clicking the rebuild button there - I didn't run the tests locally yet.

**Comment by sirreal** [comment]
I broke the tests by removing the named `Notice` export 🤦‍♂️

Should pass now 😅

**Comment by oskosk** [comment]
:shipit:

**Pull request merged**
