### PR TITLE
Suggestions to clarify instructions on installing Calypso locally

### PR DESCRIPTION
**Pull request by Avizc**
Oh golly hi! So I don't expect my suggestions to be fully (or if at all) implemented but today has been my first time ever attempting to do a pull request on a repo that's not my own. Please let me know if this is out of line with how to contribute/where else I should ask or bring this up to oh gosh. 

In hindsight I should have known right away that since I'm not an added collaborator I can't add branches to the main repo since I don't have permissions of course. On the other hand I was feeling uncertain on how to contribute, was following the [contributing guide](https://github.com/Automattic/wp-calypso/blob/master/.github/CONTRIBUTING.md) step-by-step, and accidentally forgot plain logic that oh yeah, I can't just do this to a repo that's not mine. I figure by just at least briefly mentioning forking in there it'll help some other folks remember to do that first, too.

Hopefully this is a little bit helpful but otherwise have a darling day!

### CODE REVIEW

**Comment by gwwar** [comment]
Sorry for the late response @Avizc! I think it makes a lot of sense to update `.github/CONTRIBUTING.md` with your suggestion. I think the other two docs can remain as is. 

Would you also find it helpful if we also added tips on how to rebase with master from the fork?

**Comment by Avizc** [comment]
It's okay @gwwar, thank you so much for responding! I actually forgot I did this PR since it was the second one I did ever (still going whoa at that!). I reverted the first commit I did which had changed three files (I've learned since to do much smaller commits) and re-did the `.github/CONTRIBUTING.md` with my change from before. I absolutely think it'd definitely help to add in tips on how to rebase with master from the fork. I still haven't done that myself yet because I've been rather terrified of doing it and accidentally breaking it since it's not clear on how to do it right now. 

Thank you so much for responding again, this was definitely unexpected!

**Comment by gwwar** [comment]
Thank you @Avizc!

>  I absolutely think it'd definitely help to add in tips on how to rebase with master from the fork. I still haven't done that myself yet because I've been rather terrified of doing it and accidentally breaking it since it's not clear on how to do it right now.

I'll try to spin up another PR, but let's see if these steps work for you!

First we can check to see what remotes are available:
```
[kerryliu@bmo ~/checkouts/wp-calypso] (master)$ git remote -v
origin	git@github.com:Automattic/wp-calypso.git (fetch)
origin	git@github.com:Automattic/wp-calypso.git (push)
```

If you don't see a remote pointing to `git@github.com:Automattic/wp-calypso.git` we can add that with:
```
git remote add remotename git@github.com:Automattic/wp-calypso.git
```

Rebase with the Automattic wp-calypso remote master:
```
git rebase -i remotename/master
```

And in this case I would recommend picking `c1f1f96` and use fixup on `c1f1f96` and `7e51782`

After we've rewritten history, we can then force push to our remote fork branch, which is okay in this case since there's only one person working this branch.
```
git push --force
```

Let me know if you're comfortable with rebasing. I can help land when you're ready.

**Comment by apeatling** [comment]
@Avizc Thanks for your contribution, if you decide to finish this one off, please re-open.

**Pull request closed without merging**
