### PR TITLE
Framework: Use `he` package for string decoding in all environments

### PR DESCRIPTION
**Pull request by aduth**
Currently, we split the implementation for `lib/formatting`'s `decodeEntities` by environment, using the [`he` package](https://www.npmjs.com/package/he) on the server and a `<textarea>`-based solution in the browser. Upon further investigation, it was found that including `he` in the browser [would not cause a significant size increase to the base bundle](https://www.diffchecker.com/npaqhvu7), and would provide a consistent decoding solution, eliminating the potential for differences between environments.

This pull request seeks to remove the browser-specific implementation of `decodeEntities`, instead importing the `he` package `decode` method in the base `lib/formatting` module.

__Testing instructions:__

Confirm newly introduced Mocha tests pass by running `make test` from the project root directory, or directly from `client/lib/formatting`.

Verify that sections making use of `decodeEntities` remain unaffected (e.g. Reader post titles).

/cc @blowery , @ehg

### CODE REVIEW

**Comment by ehg** [comment]
As discussed on Slack, ~30KB gzipped is a bit steep.

**Comment by aduth** [comment]
@ehg : Yeah, I had misinterpreted the results, miscalculating by an extra zero. In testing the effect it would have in production, it was more severe than I had anticipated, a difference between 1.49MB and 1.55MB in production, minified and gzipped, so an increase of about ~60kb.

**Comment by aduth** [comment]
Twice mistaken :confounded: 

In my above results, I was not serving the bundles as gzipped. With minification and gzipping of production bundles, the size difference comes to 401kb (`master`) vs. 429kb (`remove/decode-entities-browser`) which is not negligible, but also not extreme.

**Comment by aduth** [comment]
28kb is still significant, so I've opted against including the package for browser clients. While poking around, I found opportunity for enhancement to the existing behavior, merged in #3227.

**Pull request closed without merging**
