### PR TITLE
Hosting Configuration: Improve adding SSH key language

### PR DESCRIPTION
**Pull request by danielbachhuber**
## Proposed Changes

Tweaks the language associated with adding a SSH key to a Site:

**Before**

CleanShot 2023-10-26 at 10 50 26@2x

**After**

CleanShot 2023-11-01 at 13 15 59@2x

## Testing Instructions

N/A

### CODE REVIEW

**Comment by javierarce** [comment]
If we could make the sentence fit on one line, it would be better. I also think we could explain why the user needs to create the key. Here's a counter-proposal:

"To access the site through SSH, first add an SSH key and then attach it to the site."

image

cc: @michaelpick in case you have a better proposal.

**Comment by javierarce** [comment]
Now that I think about it, my suggestion isn't great, because what attaching a key allows you to do is access the site without using a password, right? Maybe this alternative is better:

"To enable passwordless login, first add an SSH key, and then attach it to the site."

I think this is not well explained in the support documentation 🤔

**Comment by wojtekn** [comment]
@danielbachhuber  if the problem we are trying to solve here is that CTA doesn't show a clear reason to add an SSH key, maybe we could go with this one:

> <a>Add an SSH key to your account</a> to attach it to this site.

**Comment by danielbachhuber** [comment]
@wojtekn I'm trying to communicate that it's a two-step process (add to the account, then attach). What about this?

> Add an SSH key to your account first, and then attach it to this site.

**Comment by javierarce** [comment]
That's better. I'm still missing an explanation for less tech-savvy users, but I guess they are not the target for this feature, and in any case, they have a link to learn more above.

**Comment by wojtekn** [comment]
> Add an SSH key to your account first, and then attach it to this site.

@danielbachhuber  I think this one looks good.

> That's better. I'm still missing an explanation for less tech-savvy users, but I guess they are not the target for this feature, and in any case, they have a link to learn more above.

@javierarce I thought we say more about the reason to add a key in [SSH Key](https://wordpress.com/support/connect-to-ssh-on-wordpress-com/#ssh-key) docs linked by "Learn more", but we don't. We could add a note about benefits in the paragraph.

**Comment by javierarce** [comment]
> @javierarce I thought we say more about the reason to add a key in [SSH Key](https://wordpress.com/support/connect-to-ssh-on-wordpress-com/#ssh-key) docs linked by "Learn more", but we don't. We could add a note about benefits in the paragraph.

That's why I thought we could mention 'passwordless' in the sentence to succinctly explain the benefit:

"To enable passwordless login, first add an SSH key, and then attach it to the site."

**Comment by michaelpick** [comment]
> "To enable passwordless login, first add an SSH key, and then attach it to the site."

This LGTM! A few alternatives for coverage:

### Action-required first

- Add an SSH key and attach it to your site to enable password login.
- Add and attach an SSH key to your site to enable passwordless login.

### Prerequisite-first
- To enable passwordless login you'll need to to add an SSH key and attach it to the site.
- Passwordless login is available when you add an SSH key and attach it to the site.

**Comment by javierarce** [comment]
Thanks, @michaelpick!

I'd personally go with your first suggestion: "Add an SSH key and attach it to your site to enable password login." The reason is that this sentence is short enough to fit on one line, the link will appear at the beginning of the sentence, and it clearly explains the benefit. The other versions are good, but they don't meet these requirements.

@danielbachhuber's version hinted more noticeably at the idea that the attaching would occur at a different stage, but since we explain that to the user on the next screen, I think that this line could work.

image

**Comment by wojtekn** [comment]
> I'd personally go with your first suggestion: "Add an SSH key and attach it to your site to enable password login." The reason is that this sentence is short enough to fit on one line, the link will appear at the beginning of the sentence, and it clearly explains the benefit. The other versions are good, but they don't meet these requirements.

LGTM too, however, I assume there is a typo and it should be "Add an SSH key and attach it to your site to enable passwordless login."

**Comment by javierarce** [comment]
> LGTM too, however, I assume there is a typo and it should be "Add an SSH key and attach it to your site to enable passwordless login."

Oops, yes, sorry.

**Comment by danielbachhuber** [comment]
@javierarce @michaelpick @wojtekn Thanks for the input! I'm happy with the final suggestion 😊

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/9580095

Some locales (Hebrew) have been temporarily machine-translated due to translator availability. All other translations are usually ready within a few days. Untranslated and machine-translated strings will be sent for translation next Monday and are expected to be completed by the following Friday.

Thank you @danielbachhuber for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/9580095).

**Pull request merged**
