### PR TITLE
Support: Add state for Support Level

### PR DESCRIPTION
**Pull request by mattwondra**
#### Changes proposed in this Pull Request

From the Chat configuration endpoint, receive a new property `supportLevel` and save it in Redux state.

This PR does not make use of this property, but prepares it to be ready to ship on quick notice, for example to show Contact Form notices only to users with certain levels of support.

#### Testing instructions
Go to http://calypso.localhost:3000/help/contact, and see the "Limited chat availability" notice at the top.

Change [this line](https://github.com/Automattic/wp-calypso/pull/45207/files#diff-bfbe01f0a66b1aa6a6708379328f1d66R55) to:
```
import getSupportLevel, { SUPPORT_LEVEL_PERSONAL } from 'state/selectors/get-support-level';
```

Change [this line](https://github.com/Automattic/wp-calypso/blob/master/client/me/help/help-contact/index.jsx#L600) to:
```
{ isUserAffectedByLiveChatClosure && this.props.supportLevel === SUPPORT_LEVEL_PERSONAL && (
```

Go back to http://calypso.localhost:3000/help/contact — you should only see the notice if the highest paid plan you own or are an admin of is Personal. (Try this with the other support levels as well.)

### CODE REVIEW

**Comment by jeherve** [comment]
This appears to be triggering a notice for me:

screenshot 2020-08-26 at 13 44 08

**Comment by gravityrail** [comment]
Me too ^^

**Comment by mattwondra** [comment]
@jeherve @gravityrail Any chance you’ve got the API sandboxed without very recent `svn up`? This code pulls a new API property I committed yesterday. 

I’ll look into adding a guard in case the property is missing, to prevent this situation.

**Comment by jeherve** [comment]
@mattwondra That was it, my bad. All good for me now.

**Pull request merged**
