### PR TITLE
Address accessibility issues related to Calypso color scheme

### PR DESCRIPTION
**Pull request by jameskoster**
Discussed internally here; p5fxDp-sI-p2

- [x] Placeholder needs to be lighter
- [ ] FAQs (See plans screen)
- [ ] Gray text on off-white bg. See plans screen (https://cloudup.com/cS6xzMWJ901)
- [ ] Decide whether icons in links are incidental and adjust colors accordingly
- [ ] Buttons
- [ ] Figure out branding implications of changing blues

### CODE REVIEW

**Comment by jameskoster** [comment]
So far I've addressed many of the text-on-white-background contrast issues.

Before;

before

After;

after

Still lots to do...

**Comment by folletto** [comment]
I gave it a go and overall I haven't seen instances where the change isn't working.

As you mention however loses a bit of balance in some details.

1. Icons, when complementary to labels, shouldn't change in gray — as they act as decoration, while the label is the main actuator. I think some of the instances where it changed can be easily reset to a lighter tone.
2. We are losing the contrast for links. However, I also think that was an issue earlier too, as we were relying on color to convey links and the contrast wasn't enough. We should probably rethink links. Ideas?
3. The filter/tab bar requires probably a thinking on its own being one of the most important navigation systems. We are lacking `:focus` and `:hover` styling there. As for the text color, we can probably just use the normal text color, even if I'd run a couple of tests to see if it gets perceived as a navigation unit better/worse than the current one (my guess: won't perform differently, so it's ok). We might want to fix the missing states in a separate PR before working on contrast, or after, either way... we should.
4. Placeholders are too dark, they look like normal text. [@](https://cloud.githubusercontent.com/assets/4389/19882380/4a16c6e4-a048-11e6-9e75-48d908fadf97.png)
5. The loading pulsating skeleton got too dark, or is my impression? (I wasn't able to hold the UI in a loading state to check)
6. The decorative (W) at the end of some lists got too dark too.

**Comment by jameskoster** [comment]
> Icons, when complementary to labels, shouldn't change in gray — as they act as decoration, while the label is the main actuator. I think some of the instances where it changed can be easily reset to a lighter tone.

I'm not 100% sure I agree, mainly because I see icons as a method of communication rather than decoration. Might be incidental though. I suppose we can say this one is a design decision. 

> We are losing the contrast for links. However, I also think that was an issue earlier too, as we were relying on color to convey links and the contrast wasn't enough. We should probably rethink links. Ideas?

Yeah this one is very tricky and there are a few things working against us. The main one being that to use blue for text, it needs to be quite dark to satisfy AA guidelines. And at this darkness, blue starts to look quite grey. To compound that issue, our `$gray` color is actually very blue. 

Totally desaturating `$gray` does help the contrast quite a bit I think, although it's definitely still not perfect. The filter/tab bar isn't so bad;

contrast

Links in descriptions however...

contrast2

Maybe inline links like this are underlined?

contrast3 

> The filter/tab bar requires probably a thinking on its own being one of the most important navigation systems. We are lacking :focus and :hover styling there. As for the text color, we can probably just use the normal text color, even if I'd run a couple of tests to see if it gets perceived as a navigation unit better/worse than the current one (my guess: won't perform differently, so it's ok). We might want to fix the missing states in a separate PR before working on contrast, or after, either way... we should.

Agreed.

> Placeholders are too dark, they look like normal text. 

Probably got caught in the find/replace. I'll tweak that.

> The loading pulsating skeleton got too dark, or is my impression? (I wasn't able to hold the UI in a loading state to check)

I'm not sure what that is? xD Assuming it's a loading indicator while waiting for the page? If it has a `color` declaration then yes it might have changed.

> The decorative (W) at the end of some lists got too dark too.

Trying to find one of these. Please point me in the right direction :)

**Comment by jameskoster** [comment]
Noticed we can use a slightly lighter blue for links etc while still passing AA which helps a little. I still feel our grays need to be less blue, though.

**Comment by folletto** [comment]
> Maybe inline links like this are underlined?

Lacking better ideas, I'd go with that.


> I'm not sure what that is? xD Assuming it's a loading indicator while waiting for the page? If it has a color declaration then yes it might have changed.

Haha yes it's hard to catch. These skeletons:

screen shot 2016-11-02 at 12 14 53

**Comment by jameskoster** [comment]
Ah, those! They _shouldn't_ have changed as I haven't touched any `background-color` declarations just yet, and haven't changed any vars.

I'll double check though. Will be picking this up again next week I think.

**Comment by drw158** [comment]
Thanks for working on this. First off, it is absolutely better to choose a different percentage of gray, rather than changing the hex value of $gray. 👍 

Unfortunately, $gray has because the standard for gray sub text. I'm guilty of that too. It might be simpler just to start a new guideline of darken( $gray, 20% ) being the standard gray for sub text. 18% passes, but might just be easier to go with 20% ease of use.

I don't really think a blanket search and replace is best here. I would prefer to start with the components and just the gray colors to start (alert colors also don't pass). It will take longer, but more methodical and easier to review. If we reviewed this PR as is, I'm sure we would miss some important details. One big PR would probably take longer to merge and address all the concerns/comments.

It doesn't make sense to me to adhere to WCAG guidelines for icons. They should be visible, of course, but our icons are a different quality than text (solid, blocky). Also, as stated before a lot of icon are secondary. For example, the icons used in the notices and most instances of social icons. It goes without saying that, bigger icons should be valued differently than small ones.

Really bad example that should have a darker icon:

screen shot 2016-11-02 at 10 16 43 am

The $blue-wordpress is quite a problem. Just darkening it doesn't solve the issue. As y'all have discovered, it seems to solve one problem, but causes another. It looks almost the same color as our gray. Not sure if just making the links underlined would solve every instance. Totally off brand, but here is an example of a blue that passes AA:

screen shot 2016-11-02 at 10 12 46 am

Another thing to consider, $blue-wordpress is actually AA 18pt+ compliant, which means if the font is larger than **14pt** and **bold** it passes. We could do this to make the buttons pass. This is another example of why search/replace might not be good. We can bold some text to make it pass.

Also, imo I don't think _everything_ has to pass AA. Examples include disabled form elements, placeholder text. Also things like notifications, where the gray text can be see in full after clicking.

screen shot 2016-11-02 at 11 13 43 am

**Comment by folletto** [comment]
> I don't really think a blanket search and replace is best here. I would prefer to start with the components and just the gray colors to start (alert colors also don't pass). It will take longer, but more methodical and easier to review. If we reviewed this PR as is, I'm sure we would miss some important details. One big PR would probably take longer to merge and address all the concerns/comments. I think component-first would have a high impact.

I'm happy to proceed in this way too.

Just: how do we make sure we progress with a consistent approach, changing all the bits that require changing?

Draft idea:

* Define a couple of guidelines (that I think we can get from the experience of this PR)
* Define new variables if needed
* Get a list of all components
* Use the guidelines and start fixing all the components

Does it make sense?

**Comment by jameskoster** [comment]
That sounds good to me. Should make the task much more manageable and easier to share the load! 

> Define a couple of guidelines

Can we do this now? Or do we wait for the outcome of the .com branding meeting(s)?

> It looks almost the same color as our gray.

Regarding this issue, I think it makes more sense to desaturate our gray a little rather than change the blue, especially if we can make the blue pass by adjusting the weight.

**Comment by drw158** [comment]
I wouldn't wait on the meetings. Because of a tight deadline, they are mostly for defining some secondary colors for our outside partners to use in marketing materials.

**Comment by drw158** [comment]
Ok, I experimented with some different grays. Nothing else about the colors were changed except for the $gray hex value.

### Original:

cxmqmqaamqgactolj04oc6 dl h3kky eav9lqaaaaaelftksuqmcc

### WordPress.org gray

plrszgmuomwaaaabjru5erkjggg


### Totally Neutral:

w8 jqv7pj9ifwaaaabjru5erkjggg

### Simplenote Gray

pvwc9mfylnx4f7h3mwzodm3xrkz8xfyiihl6ufiiqhsellqq2 a5deslmsakdkv4qs0nj0sraqt0mqks65teiabeiabeigyqiul1wzzzuaxwvzzqznrqi8ks41qajme3alcvkdnarnuqgktrjcljfqko3uqdq7ekaqukncba5biyjqevbtvb61aqi1fydok9zkvswbmw tgigavkmdwrfo9mor6fbcwowpjumabeiabnyyamwlgyfxxup7

### Material Color "Blue Grey"

a5i54t97aaaaaaelftksuqmcc

### My own concoction

caaaaasuvork5cyii

Material generator of the palettes:

screen shot 2016-11-03 at 11 23 35 am

**Comment by drw158** [comment]
Seeing the neutral grays really surfaces how low contrast the whole layout is, not just the text. Reminds me of old WordPress back before MP6 :(

**Comment by jameskoster** [comment]
I like the more neutral schemes. Simplenote gray and your first concoction in particular seem to offer a nice contrast without being too dull.

Do any of those `$gray`s pass AA?

**Comment by drw158** [comment]
Nope, all of the aceesibilty should be the same as in master. I just changed the hue of $gray

**Comment by drw158** [comment]
Change $gray to `8F9EAE`. I've been using that all day, and I like it a lot more than our current grays.

Unfortunately it doesn't don't remedy the blue link problem.

screen shot 2016-11-03 at 4 28 07 pm

**Comment by mtias** [comment]
@drw158 thanks for all these explorations, that's really nice to see in concert. I agree with your initial suggestion that we need to go piece by piece. For example, I would separate the `$gray` issue from the blue link color. We can tackle them separately, open a PR only to change `$gray` and discuss what to do with links elsewhere.

Also, several component have just made sub-par decisions and we should just fix it. (Like post-schedule calendar which should be using dark-gray in more places.)

Separate from the contrast conversation, I like a more subdued palette that has a bit less blue in the grays. Your concoctions or Material Color "Blue Grey" seem interesting to explore further.

**Comment by jameskoster** [comment]
Thanks for the input everyone. I'm going to close out this PR now in favour of the proposed method for tackling this. My understanding of that is;

1. Let's address color issues independently
2. Assess/amend each component individually if it still requires attention after the color updates

Looking at `$gray` in isolation seems to be the perfect starting point. I'm excited to check that out :)

**Pull request closed without merging**
