### PR TITLE
Plans: Remove Google analytics feature page

### LINKED ISSUE #8288: Plans: remove google analytics feature page
We're not using `http://calypso.localhost:3000/plans/features/google-analytics/:siteId:` so let's delete the page, and remove the related routes.

screen shot 2016-09-28 at 9 50 39 am

We should also remember to remove the link to this page from `http://calypso.localhost:3000/plugins/:siteId:` in the following nudge:

screen shot 2016-09-28 at 9 52 31 am

### PR DESCRIPTION
**Pull request by artpi**
- Resolves #8288
- Removes GA feature page
- Changes working route in plugins to `/plans/{siteSlug}/?feature=google-analytics`
- Cleans up dead code from contextualGoogleAnalyticsNudge test
- Removes remaining GA feature page scaffolding

## Testing

- Go to http://calypso.localhost:3000/plugins/{site}
- Click "Google Analytics" in business section
- You should be directed to /plans with GA row highlighted
- Go to http://calypso.localhost:3000/plans/features/google-analytics/:site
- See that you are redirected to /plans with the GA row highlighted

CC @lamosty @gwwar @rralian @retrofox

### CODE REVIEW

**Comment by gwwar** [comment]
We also need to remove the link to the deleted component scss in `_components.scss`

```
{
  "formatted": "Error: File to import not found or unreadable: my-sites/plans/plan-feature/style\n       Parent style sheet: /Users/kerryliu/checkouts/wp-calypso/assets/stylesheets/_components.scss\n        on line 253 of assets/stylesheets/_components.scss\n>> @import 'my-sites/plans/plan-feature/style';\n   ^\n",
  "message": "File to import not found or unreadable: my-sites/plans/plan-feature/style\nParent style sheet: /Users/kerryliu/checkouts/wp-calypso/assets/stylesheets/_components.scss",
  "column": 1,
  "line": 253,
  "file": "/Users/kerryliu/checkouts/wp-calypso/assets/stylesheets/_components.scss",
  "status": 1
}
```

**Comment by gwwar** [comment]
> Should we redirect all /plans/features/:x/:site to /plans/:site/?feature=:x ?

👍 That a good idea

**Comment by artpi** [comment]
> 👍 That's a good idea

Done

> We also need to remove the link to the deleted component scss in _components.scss

Done

**Comment by gwwar** [comment]
:shipit:

**Pull request merged**
