### PR TITLE
Themes: Fix try&customize for jetpack and atomic sites

### LINKED ISSUE #19241: Themes: Try & Customize feature (Preview) not working for Atomic sites
#### Steps to reproduce
1. Open the Themes panel for any Atomic site
2. Click the three dots icon in a thumbnail from the library and click 'Try & Customize'

#### What I expected

This should open a preview of the new theme in the Customizer.

#### What happened instead

Nothing.

#### Browser / OS version

Chrome Version 61.0.3163.100 / OS X El Capitan Version 10.11.6

#### Screenshot / Video

https://cloudup.com/cJa_90gSykU

#### Context / Source

#user-report

Discovered during Business 1:1 session.

### PR DESCRIPTION
**Pull request by seear**
Fixes #19241

`page()` call to go to the customizer will not work with external links, so the "try and customize" action is not working for jetpack and atomic sites, where the customizer is hosted by the site.

Use window.open() instead for exernal links, which opens a new tab/window. Alternative would be to go with `window.location.href=...` to open in same tab.

**To Test**
Follow #19241 (Is broken for jetpack sites as well as atomic)

### CODE REVIEW

**Comment by seear** [comment]
> I guess it would be nicer to do what the Customize button does in the sidebar, which is to use an a href to handle the redirect

Yes, agree. I believe we need to use a function because we have [composed actions](https://github.com/Automattic/wp-calypso/blob/076a43a8516c9e6dffe8ea14bd187c8c10d00588/client/state/themes/actions.js#L537) (due to needing to install theme on jp/atomic sites before trying them) which means we can't use a simple href.

**Comment by seear** [comment]
Thanks for review @sirbrillig!

**Comment by nylen** [comment]
@seear this PR merged a large, spurious file `lintout.tmp` - can you remove it please?

**Comment by seear** [comment]
> this PR merged a large, spurious file lintout.tmp - can you remove it please?

@nylen on it...

**Pull request merged**
