### PR TITLE
Stats: Move Components to Folder Structure

### PR DESCRIPTION
**Pull request by alternatekev**
This PR moves modules around within the `my-sites/stats/` section to a little more sane of a folder structure. 
- Moved `my-sites/stats/xyz-module.jsx` files and put them in a `modules` folder.
- Moved `my-sites/stats/stats-xyz.jsx` files and moved them into `my-sites/stats/stats-xyz/index.jsx`
- Moved `/assets/stylesheets/sections/stats.scss` to `/client/my-sites/stats/style.scss` and updated `_components.scss` imports

### CODE REVIEW

**Comment by alternatekev** [comment]
Pinging @jonathansadowski @jblz and @timmyc

**Comment by alternatekev** [comment]
Thinking about grouping these into a folder together:
screen shot 2015-11-25 at 1 43 58 pm

and also these:
screen shot 2015-11-25 at 1 43 52 pm

**Comment by timmyc** [comment]
I think `stats-list` should be its own component/folder, with `stats-list-item` inside of that directory as well.  I don't think anything else uses `stats-list-item` besides a `stats-list`.

The `action-xxx` components likewise are consumed by the stats-list-item, so possibly it might make sense for them to be in that directory as well.

The balance of them I think should just live in their own directories.

**Comment by mtias** [comment]
Nice to see the removal of `sections/stats.scss` :)

Some things to consider:

* `/stats/action-spam/` should be `/stats/stats-action-spam/` — likewise `/stats/follows/`. This is moving from a sub-component (`follows.jsx`) to a component, which should carry a namespace adjust (since it's global). (<a href="https://github.com/Automattic/wp-calypso/tree/master/client/post-editor">Example of components in post-editor section</a>.)
* Instead of moving all the folders at once I'd suggest we just move one at a time, taking the time to update the classes to <a href="https://github.com/Automattic/wp-calypso/blob/master/docs/components.md">the latest guidelines</a>, and having specific `style.scss` files for each component.

**Comment by timmyc** [comment]
> Instead of moving all the folders at once I'd suggest we just move one at a time, taking the time to update the classes to the latest guidelines, and having specific style.scss files for each component.

I agree with @mtias on this point too.  Also this would keep the PR's a bit more compact and make testing a bit easier as well.

**Comment by alternatekev** [comment]
Closing this PR in order to do these one by one including sass changes.

**Pull request closed without merging**
