### PR TITLE
Add Popup Jetpack Checkout Scheduling

### PR DESCRIPTION
**Pull request by cbauerman**
##### Brief

Calendly offers a pretty good pop-up widget, that works around some aesthetic issues with the embedded widget.

* Modify Route for existing scheduling page to send to thank-you page and trigger widget
* Tweak thank-you page to make link a button.
* Trigger scheduling widget on button press.

calypso localhost_3000_checkout_jetpack_thank-you_no-site_jetpack_backup_daily

#### Testing instructions

* Navigate to `checkout/jetpack/thank-you/no-site/jetpack_backup_daily` on branch
* Verify the "Schedule a 15 minute call now" link is now a button that triggers a pop-up widget one the same page, as in the screenshot above.
* Navigate to `/checkout/jetpack/schedule-happiness-appointment` on branch
* Verify you are taken to the same thank you page, but that the scheduling widget immediately opens

### CODE REVIEW

**Comment by rcanepa** [comment]
Works and looks great.

However, I noticed that the email link to schedule an appointment doesn't work (it uses the URL we removed in this PR). Without thinking much about it, I guess we could add a query parameter to the email link to tell the app to show the modal.

**Comment by keoshi** [comment]
I'm not able to test this one; getting this error:

```
ERROR in ./my-sites/checkout/checkout-thank-you/jetpack-checkout-siteless-thank-you.tsx 10:0-49
Module not found: Error: Can't resolve 'react-calendly' in '/Users/keoshi/Documents/repos/wp-calypso/client/my-sites/checkout/checkout-thank-you'
```

Is there anything I can do?

**Comment by rcanepa** [comment]
> I'm not able to test this one; getting this error:
> 
> ```
> ERROR in ./my-sites/checkout/checkout-thank-you/jetpack-checkout-siteless-thank-you.tsx 10:0-49
> Module not found: Error: Can't resolve 'react-calendly' in '/Users/keoshi/Documents/repos/wp-calypso/client/my-sites/checkout/checkout-thank-you'
> ```
> 
> Is there anything I can do?

@keoshi, try running `yarn` before you run `yarn start`. I think you're missing that package and `yarn` should install it.

**Comment by keoshi** [comment]
@rcanepa 🤯 hahaha, why have I never thought of doing that?

**Review by keoshi — APPROVED** [review]
I hate to be the bearer of bad news, but the scrollbar is still visible on the last step using this method:

image

However, this is a minor detail at this point — I do prefer the Calendly options appearing on a modal, it behaves very well on smaller devices, and the scroll might not even be noticeable in most cases.

Approving because this shouldn't be a blocker for all the great work the divison has been doing! 🙌

**Review by rcanepa — APPROVED** [review]
LGTM. 

I like very much that we use the same component for both routes.

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/6276675

Thank you @cbauerman for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/6276675).

**Pull request merged**
