### PR TITLE
Add checkout included features list for new Stats products

### PR DESCRIPTION
**Pull request by elliottprogrammer**
This PR adds the list of "Included features" displayed on the checkout page, for the new Stats products. (See screenshot):

#### Screenshots:

**Stats paid products (Commercial and PWYW):**

Markup 2023-06-30 at 18 54 08

Markup 2023-06-30 at 19 00 31

** Stats Free product ($0): **

Markup 2023-06-30 at 18 58 42

Stats "Included features" items discussion: p1HpG7-ngN-p2#comment-64474
Asana task: 1201210512993648-as-1204939720795290/f

## Proposed Changes

- Adds the new Jetpack Stats products constants to the `calypso-products` package.
- Add the "Included features" list for Jetpack Stats products on the Checkout page.
- Update unit tests.

## Testing Instructions

- Checkout this PR & spin up Calypso blue (`git fetch && git checkout add/checkout-stats-included-features && yarn start`)
- Go to: http://calypso.localhost:3000/checkout/jetpack/jetpack_stats_monthly
- Verify the Stats (Commercial) product is in the cart and the "Included features" list items are displaying and look like the screenshots above.
- Remove the product from the cart (unless code-D115101 is already deployed, which prevents concurrent products in cart).
- Go to: http://calypso.localhost:3000/checkout/jetpack/jetpack_stats_pwyw_yearly:-q-12
- Verify the Stats (Paid) product is in the cart for $12 dollars and the "Included features" list items are displaying and look like the screenshots above.
- Remove the product from the cart (unless code-D115101 is already deployed, which prevents concurrent products in cart).
- Go to: http://calypso.localhost:3000/checkout/jetpack/jetpack_stats_free_yearly
- Verify the Stats (Free non-commercial license) product is in the cart and there are only 2 "Included features" list items and they look like the screenshots above.
- 
## Pre-merge Checklist

- [X] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [X] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

**Comment by kangzj** [comment]
Thanks for working on this @elliottprogrammer 👍 

----1----

> ** Stats Free product ($0): **

The features shown for Free do NOT work as described or I'm missing something (Do I need sandbox public api?):

image


----2----


TS checking is failing for the PR which broke the type check in the unit tests:

```
error TS2739: Type '{ jetpack_ai_monthly: { product_name: ExistingReactNode; product_slug: "jetpack_ai_monthly"; type: "jetpack_ai_monthly"; term: "TERM_MONTHLY"; bill_period: 31; categories: never[]; getFeatures: () => never[]; getProductId: () => number; getStoreSlug: () => "jetpack_ai_monthly"; }; ... 36 more ...; jetpack_backup_add...' is missing the following properties from type 'Record<"jetpack_ai_monthly" | "jetpack_boost_yearly" | "jetpack_boost_monthly" | "jetpack_backup_t0_yearly" | "jetpack_backup_t0_monthly" | "jetpack_backup_t1_yearly" | "jetpack_backup_t1_bi_yearly" | ... 33 more ... | "jetpack_backup_realtime_monthly", Product>': jetpack_stats_monthly, jetpack_stats_pwyw_yearly, jetpack_stats_free_yearly
```

https://github.com/Automattic/wp-calypso/blob/4ce2d2155cfb9153dab8a742e7b1d02a72681e95/packages/calypso-products/src/products-list.ts#L88



----3----

I'm working on [support check for the Stats products](https://github.com/Automattic/wp-calypso/pull/78657). The products checks are pretty straight forward, but I'm not very sure about the feature checks. I noticed the diffs on WPCOM added the Plans as features, for example D113814-code, so I'm [checking plans on the features](https://github.com/Automattic/wp-calypso/pull/78657/files#diff-33f595ec94a08400dced3f7f16b4e2a4f1887078e12d581e36f45764a72ac692R96) too. I'm wondering if you have any advice please? Thanks in advance.

**Comment by elliottprogrammer** [comment]
> Thanks for working on this @elliottprogrammer 👍
> 
> ----1----
> 
> > ** Stats Free product ($0): **
> 
> The features shown for Free do NOT work as described or I'm missing something (Do I need sandbox public api?):

Thanks for reviewing @kangzj! 
My apologies, looks like I did not push my last commit that separates the "included features" of Stats Free and the other Stats paid products.  It should be fixed now and should now work as described. 👍
> ----2----
> 
> TS checking is failing for the PR which broke the type check in the unit tests:
> 
> ```
> error TS2739: Type '{ jetpack_ai_monthly: { product_name: ExistingReactNode; product_slug: "jetpack_ai_monthly"; type: "jetpack_ai_monthly"; term: "TERM_MONTHLY"; bill_period: 31; categories: never[]; getFeatures: () => never[]; getProductId: () => number; getStoreSlug: () => "jetpack_ai_monthly"; }; ... 36 more ...; jetpack_backup_add...' is missing the following properties from type 'Record<"jetpack_ai_monthly" | "jetpack_boost_yearly" | "jetpack_boost_monthly" | "jetpack_backup_t0_yearly" | "jetpack_backup_t0_monthly" | "jetpack_backup_t1_yearly" | "jetpack_backup_t1_bi_yearly" | ... 33 more ... | "jetpack_backup_realtime_monthly", Product>': jetpack_stats_monthly, jetpack_stats_pwyw_yearly, jetpack_stats_free_yearly
> ```
> 
> https://github.com/Automattic/wp-calypso/blob/4ce2d2155cfb9153dab8a742e7b1d02a72681e95/packages/calypso-products/src/products-list.ts#L88

Ahh yes, thank you!  Ok, adding the Stats products to `products-list.ts` fixes this and all tests should now be passing.

> ----3----
> 
> I'm working on [support check for the Stats products](https://github.com/Automattic/wp-calypso/pull/78657). The products checks are pretty straight forward, but I'm not very sure about the feature checks. I noticed the diffs on WPCOM added the Plans as features, for example D113814-code, so I'm [checking plans on the features](https://github.com/Automattic/wp-calypso/pull/78657/files#diff-33f595ec94a08400dced3f7f16b4e2a4f1887078e12d581e36f45764a72ac692R96) too. I'm wondering if you have any advice please? Thanks in advance.

@kangzj , AFAIK, I don't think the Features in diff D113814-code have anything to do with the feature-checks in Calypso. If I'm not mistaken the Calypso feature-checks are just independent constants that you can add, although I haven't fully confirmed this, so don't quote me on that, but I believe from memory that this is the case. 😉

@kangzj, this should be ready for re-review again, if you don't mind and have time. Much appreciated. 🙂

**Review by IanRamosC — APPROVED** [review]
Tests well!

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/8144637

Thank you @elliottprogrammer for including a screenshot in the description! This is really helpful for our translators.

**Pull request merged**
