### PR TITLE
Nav Unification: Update image assets and CSS classes for new positioning

### LINKED ISSUE #50038: Nav Unification: Announcement modal assets updates
**What**

Update the announcement modal images for different environments

**Why**

As per p1HpG7-bcl-p2#comment-44591 comment we should not mention WP.com for Jetpack sites in the announcement modal.

### LINKED ISSUE #50322: Nav Unification: Announcement modal copy updates
**What**

Update the announcement modal copy for different environments

**Why**

As per p1HpG7-bcl-p2#comment-44591 comment we should not mention WP.com for Jetpack sites in the announcement modal.

**Acceptance criteria**

### PR DESCRIPTION
**Pull request by tjcafferkey**
#### Changes proposed in this Pull Request

* Update image assets
* Update modal copy

#### Testing instructions

* Visit generated live Calypso link below
* Remove preference `nav-unification-modal` using the debug badge in the bottom right
* Observe new image assets for both mobile and desktop, should reflect below (in order)

<table>
<tr>
<td>Desktop</td><td>Mobile</td>
</tr>
<tr>
<td>Desktop - Modal 4</td>
<td>Mobile - Modal 7</td>
</tr>
<tr>
<td>Desktop - Modal 5</td>
<td>Mobile - Modal 8</td>
</tr>
<tr>
<td>Desktop - Modal 6</td>
<td>Mobile - Modal 9
</td>
</tr>
</table>

Fixes https://github.com/Automattic/wp-calypso/issues/50038
Fixes https://github.com/Automattic/wp-calypso/issues/50322

### CODE REVIEW

**Review by mmtr — DISMISSED** [review]
LGTM :shipit: 

On a side note, I'm a bit concerned about the images used on the 2nd step:

Mobile | Desktop
--- | ---
 | 

They look pretty informational so the new toggle setting in Account Settings is more discoverable, but since the image is not translatable, non-English speaking users may get confused. cc @sfougnier @obenland 

Anyway, that can be followed up later.

**Comment by ghost** [comment]
### Image Assets & Copy

> They look pretty informational so the new toggle setting in Account Settings is more discoverable, but since the image is not translatable, non-English speaking users may get confused.

Thanks for calling this out @mmtr ! This is a very good point. I've taken a second pass at the assets to make these a little more universal and remove any language. @tjcafferkey can we update those assets again, please? [New_Modal_Assets.zip](https://github.com/Automattic/wp-calypso/files/6025567/New_Modal_Assets.zip)

I also have updated copy. Check [Figma](https://www.figma.com/file/9cy0DIowQkPAu0rodb9jsL/WP-Admin-for-Dotcom?node-id=1166%3A75340) as well as the screenshots below:

<table>
<tr>
<td>Desktop</td><td>Mobile</td>
</tr>
<tr>
<td>Desktop - Modal 4</td>
<td>Mobile - Modal 7</td>
</tr>
<tr>
<td>Desktop - Modal 5</td>
<td>Mobile - Modal 8</td>
</tr>
<tr>
<td>Desktop - Modal 6</td>
<td>Mobile - Modal 9
</td>
</tr>
</table>


### Padding & Line-height

I'm also noticing that the header line-height in the modal still feels quite tall, and the vertical padding feels tight between the top of the modal and the text and between the header and body copy. I see the welcome tour modal uses `line-height: 1.19;` in the header, and has a bit more breathing room between the elements. Can we match this @tjcafferkey ?

<table>
<tr> 
<td>Nav unification</td>
<td>Welcome tour</td>
</tr>
<tr>
<td>Screen Shot 2021-02-22 at 5 39 30 PM</td>
<td>Screen Shot 2021-02-22 at 5 36 13 PM</td>
</tr>
</table>

**Review by mmtr — COMMENTED** [review]
I'm loving the new images ❤️ .

I noted the spacing is still different when compared to the "Welcome to your site" modal:

Nav Unification welcome modal | New site welcome modal
--- | ---
Screen Shot 2021-02-23 at 12 34 26 | Screen Shot 2021-02-23 at 12 34 36

I guess we could solve this by replicating the same markup and styles we use in the new site welcome modal?

https://github.com/Automattic/wp-calypso/blob/ba0e5f813a936a820e279eca486d78c188997d6d/apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nux/src/welcome-modal/wpcom-nux.js#L136-L149

https://github.com/Automattic/wp-calypso/blob/trunk/apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nux/src/welcome-modal/style.scss

Also noted that the images are not immediately loaded when compared to the new site welcome modal:

Nav Unification welcome modal | New site welcome modal
--- | ---
Feb-23-2021 12-39-15 | Feb-23-2021 12-39-26

I wonder if that's related to the markup differences. The nav unification welcome modal [uses some `picture`/`source` tags](https://github.com/Automattic/wp-calypso/blob/708088769e812ac2675e1a3c0e186ce132642918/client/blocks/nav-unification-modal/index.jsx#L83-L86), while the new site welcome modal simply [uses an `img` tag](https://github.com/Automattic/wp-calypso/blob/ba0e5f813a936a820e279eca486d78c188997d6d/apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nux/src/welcome-modal/wpcom-nux.js#L141-L148).

**Comment by tjcafferkey** [comment]
@mmtr Hmm possibly. The reason for the picture element is because I need different assets loading for different viewports (Welcome modal does not have this problem) and I didn't want to load in both desktop & mobile assets if I was only going to be showing one or the other.

I will investigate this further and see if I can find a suitable solution. I will also address those spacing issues you've noted.

**Comment by mmtr** [comment]
> I will investigate this further and see if I can find a suitable solution.

Maybe it can be solved by setting a `key` property? Seems it was also needed in the new site welcome modal:

https://github.com/Automattic/wp-calypso/blob/ba0e5f813a936a820e279eca486d78c188997d6d/apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nux/src/welcome-modal/wpcom-nux.js#L142-L143

**Comment by tjcafferkey** [comment]
>Maybe it can be solved by setting a key property? Seems it was also needed in the new site welcome modal:

@mmtr thanks for pointing this out you potentially saved me a lot of time! 🙇🏻 

Ready for another review

**Review by mmtr — APPROVED** [review]
Awesome, this works perfectly now. Nice job, @tjcafferkey.

**Comment by ghost** [comment]
Looking good! 

One thing: I took a look at how the images are scaling for smaller viewports. I see the images are getting cut off in smaller screens:

Screen Shot 2021-02-23 at 11 27 03 AM

In the editor modal though the images seem to scale.

https://user-images.githubusercontent.com/67021691/108874583-4962fe00-75ca-11eb-9385-b80308aceff2.mov

Can we align with the treatment in the editor modal?

**Comment by tjcafferkey** [comment]
@sfougnier I've just pushed a change for this. Please can you re-review those when you get a chance? Thanks

**Comment by ghost** [comment]
> I've just pushed a change for this. Please can you re-review those when you get a chance? 

The mobile image scaling looks good now. Thanks!

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/5544188

Thank you @tjcafferkey for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/5544188).

**Pull request merged**
