### PR TITLE
Use the fallback build for desktop.

### PR DESCRIPTION
**Pull request by sgomes**
Always use the fallback build for the desktop app.

Electron may not be able to guarantee all the features that the evergreen build relies on.

#### Changes proposed in this Pull Request

* Use the fallback build for the desktop app.

#### Testing instructions

* None on this repo.

### CODE REVIEW

**Comment by sgomes** [comment]
Rebased on master.

**Comment by sgomes** [comment]
Any chance of a review? This is mostly configuration, so it should be straightforward enough. I'd like to avoid subtle breakage in the desktop app if Electron is unable to provide the native functionality that the evergreen build expects.

**Review by jsnajdr — APPROVED** [review]
An optimal setup for Desktop would be to have a separate `desktop` environment in browserslist, specifying:
```
desktop: [
  'electron 1.7.16'
]
```
And then the Desktop build would build for this target.

The sources in the wp-desktop repo are [already transpiled this way](https://github.com/Automattic/wp-desktop/blob/59b0dc6be0c7c12fc773d6979bddb9d1cec22a93/babel.config.js#L3).

This PR looks like a good step forward nevertheless.

**Comment by sgomes** [comment]
> An optimal setup for Desktop would be to have a separate `desktop` environment in browserslist, specifying:
> 
> ```
> desktop: [
>   'electron 1.7.16'
> ]
> ```
> 
> And then the Desktop build would build for this target.
> 
> The sources in the wp-desktop repo are [already transpiled this way](https://github.com/Automattic/wp-desktop/blob/59b0dc6be0c7c12fc773d6979bddb9d1cec22a93/babel.config.js#L3).
> 
> This PR looks like a good step forward nevertheless.

That's a good idea, although at this point it would involve a fair number of changes, across `package.json`, WebPack configs, and run-time server code. Definitely something to consider for the future, though, perhaps in conjunction with a larger overhaul of the desktop app's build process.

**Comment by sgomes** [comment]
Thank you for the approval, @jsnajdr !

**Comment by jsnajdr** [comment]
> Definitely something to consider for the future, though, perhaps in conjunction with a larger overhaul of the desktop app's build process.

Totally agreed :+1:

**Pull request merged**
