### PR TITLE
Try: Replace classnames with clsx

### PR DESCRIPTION
**Pull request by tyxla**
## Proposed Changes

This PR attempts to replace `classnames` with `clsx` across Calypso, which is a faster and lighter alternative.

Originally brought up by @DaniGuardiola in a recent discussion about merging classes in Gutenberg.

## Testing Instructions

* All should be green.

### CODE REVIEW

**Comment by tyxla** [comment]
@jsnajdr and the rest of @Automattic/team-calypso - do you feel like this is worth moving forward with?

**Comment by gabrielcaires** [comment]
> @jsnajdr and the rest of @Automattic/team-calypso - do you feel like this is worth moving forward with?

Can you add a link to the discussion? 

Is it possible, at least temporally, to use a webpack alias to replace the modules, so we can easily test and revert if necessary?

**Comment by tyxla** [comment]
> Can you add a link to the discussion?

Sure, it was a Slack discussion though: p1713950904813489-slack-C7YPUHBB2

> Is it possible, at least temporally, to use a webpack alias to replace the modules, so we can easily test and revert if necessary?

It's definitely possible, although I'm not convinced is necessary. Why do you think we need it?

**Review by DaniGuardiola — APPROVED** [review]
lgtm

**Comment by tyxla** [comment]
I'll wait until we make the decision to land it in Gutenberg first. I'm not worried about merge conflicts - this PR took like a few minutes to create, so it will be painless to redo it if necessary.

**Comment by DaniGuardiola** [comment]
@tyxla FYI the change has landed in Gutenberg so I think we can go ahead and get this PR updated and merged: https://github.com/WordPress/gutenberg/pull/61138

**Comment by tyxla** [comment]
> @tyxla FYI the change has landed in Gutenberg so I think we can go ahead and get this PR updated and merged: [WordPress/gutenberg#61138](https://github.com/WordPress/gutenberg/pull/61138)

That's mostly true, but we'll need to wait a bit more: the `clsx` update will land in the next version of the `@wordpress` packages (I just updated to the latest versions in #90243 and they still use `classnames`), and after updating to that, I'll refresh this PR again and move forward with the `clsx` change.

**Comment by tyxla** [comment]
This one is quite obsolete, I'm closing in favor of #91408.

**Pull request closed without merging**
