### PR TITLE
Assembler - Remove the patterns list screen (Homepage list)

### PR DESCRIPTION
**Pull request by miksansegundo**
## Proposed Changes

* Remove the patterns list screen (Homepage list)
 * The action to replace patterns is removed too but not the logic

|Before|After|
|--|--|
|<video src="https://github.com/Automattic/wp-calypso/assets/1881481/84ba7191-ae42-49ad-a476-d8f76b482b97">|<video src="https://github.com/Automattic/wp-calypso/assets/1881481/aeae2144-6048-4074-868a-031a45ffd605">|

### Follow-up tasks
- [X] Update the Tracks events on PekYwv-WG-p2 to remove all the events related to the patterns list screen 

## Testing Instructions

* Access the assembler `/setup/with-theme-assembler/patternAssembler?siteSlug={ YOUR SITE }&theme=blank-canvas-3`
* Click on "Homepage" to add patterns
* Click on "Save" or "<" back icon

## Pre-merge Checklist

- [X] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [X] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [X] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [X] Have you checked for TypeScript, React or other console errors?
- [X] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [X] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [X] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

**Review by fushar — APPROVED** [review]
🔥 🧹

**Comment by miksansegundo** [comment]
Do you think we should remove more code related to the replace pattern action? Maybe the `replacePatternMode` prop in [screen-category-list.tsx](https://github.com/Automattic/wp-calypso/blob/3ed8c7a856d67e555ac13aa8c723c53e27f49bb6/client/landing/stepper/declarative-flow/internals/steps-repository/pattern-assembler/screen-category-list.tsx#L30)?

**Comment by fushar** [comment]
Oh, I thought it was intentional that we left the code untouched. If we're sure that this is going to be permanent, let's remove every related unused code 😄

**Comment by miksansegundo** [comment]
I think we are still not sure about the future of the "Replace pattern" action. I raised a [PR](https://github.com/Automattic/wp-calypso/pull/79112) to test it from the canvas. cc: @taipeicoder @lucasmendes-design

**Review by arthur791004 — APPROVED** [review]
🧹

**Comment by lucasmendes-design** [comment]
It's way better now :) about the replace action, I'll comment there.

**Comment by miksansegundo** [comment]
I tested the Tracks events and updated them in the code and PekYwv-WG-p2. I'll merge this PR and leave the code for the replace action for now.

**Pull request merged**
