### PR TITLE
Theme Showcase: Add tabbed navigation

### PR DESCRIPTION
**Pull request by sixhours**
#### Changes proposed in this Pull Request

* Add tabbed navigation for "All" and "Recommended" themes to the Showcase.
* This takes advantage of existing filter behavior by setting a `filter` state and navigating to the filter's unique path `/themes/filter/[tag-slug]/[site]`.
* New tabs can be added by tagging themes in the Showcase with a specific tag, then pointing the new tab to that tag.

This is not 100% yet -- trying to go back and forth between tabs can cause the wrong themes to show, but I'm not sure why. 🤔 

**Before**

screencapture-calypso-localhost-3000-themes-caroauditsimple-wordpress-com-2021-06-29-12_31_17

**After**

Screen Shot 2021-06-29 at 12 26 40 PM

#### Testing instructions

* Switch to this PR
* Navigate to `/themes/site`
* Check out the tabs above the search bar! Click around and make sure they work as expected
* Check the showcase when logged out to make sure the tabs appear and work as expected
* Check the styles on mobile to make sure they work and nothing visually breaks

Related to #54083

### CODE REVIEW

**Comment by mreishus** [comment]
The issue seems to be that the "/filter/auto-loading-homepage" mechanism works by setting the initial search string in the text input to be "feature:auto-loading-homepage", but this only works on initial page load. After the page has already loaded, the search string in the text input is not automatically changed by props anymore. [Transfer on load](https://github.com/Automattic/wp-calypso/blob/5cb116f4c12d65091e57583c88ba3a6395715bb3/client/my-sites/themes/themes-magic-search-card/index.jsx#L59)

Debugging
```diff
diff --git a/client/my-sites/themes/theme-showcase.jsx b/client/my-sites/themes/theme-showcase.jsx
index 48c42e8f7b..875a5a5f8d 100644
--- a/client/my-sites/themes/theme-showcase.jsx
+++ b/client/my-sites/themes/theme-showcase.jsx
@@ -276,7 +276,6 @@ class ThemeShowcase extends React.Component {
 						<UpworkBanner location={ 'theme-banner' } />
 					) }
 					<QueryThemeFilters />
-
 					<SectionNav className="themes__section-nav">
 						<NavTabs>
 							<NavItem onClick={ () => this.onFilterClick( '' ) } selected={ ! filter }>
@@ -290,7 +289,6 @@ class ThemeShowcase extends React.Component {
 							</NavItem>
 						</NavTabs>
 					</SectionNav>
-
 					<ThemesSearchCard
 						onSearch={ this.doSearch }
 						search={ filterString + search }
@@ -299,7 +297,7 @@ class ThemeShowcase extends React.Component {
 						select={ this.onTierSelect }
 					/>
 					{ this.props.upsellBanner }
-
+					Themes Showcase props.filter: [{ filter }]
 					<ThemesSelection
 						upsellUrl={ this.props.upsellUrl }
 						search={ search }
diff --git a/client/my-sites/themes/themes-magic-search-card/index.jsx b/client/my-sites/themes/themes-magic-search-card/index.jsx
index c9b504eb11..e02089327c 100644
--- a/client/my-sites/themes/themes-magic-search-card/index.jsx
+++ b/client/my-sites/themes/themes-magic-search-card/index.jsx
@@ -305,6 +305,11 @@ class ThemesMagicSearchCard extends React.Component {
 		return (
 			<div className={ magicSearchClass }>
 				<StickyPanel>
+					<div>
+						Search Prop: [{ this.props.search }] <br />
+						SearchInput State: [{ this.state.searchInput }] <br />
+						The Search -&gt; SearchInput transfer only happens on initial page load
+					</div>
 					<div
 						className={ themesSearchCardClass }
 						role="presentation"
diff --git a/client/my-sites/themes/themes-selection.jsx b/client/my-sites/themes/themes-selection.jsx
index c4767c1ade..51c83bc611 100644
--- a/client/my-sites/themes/themes-selection.jsx
+++ b/client/my-sites/themes/themes-selection.jsx
@@ -162,6 +162,10 @@ class ThemesSelection extends Component {
 
 		return (
 			<div className="themes__selection">
+				<div>
+					ThemeSelection props.filter: [{ this.props.filter }] | props.filterString:{ ' ' }
+					{ this.props.filterString }
+				</div>
 				<QueryThemes query={ query } siteId={ source } />
 				{ ! this.props.recommendedThemes && this.props.isLoggedIn && (
 					<ThemesSelectionHeader
@@ -228,6 +232,7 @@ export const ConnectedThemesSelection = connect(
 			number,
 		};
 
+		console.log( 'Filter String: ' + prependThemeFilterKeys( state, query.filter ) );
 		return {
 			query,
 			source: sourceSiteId,
@@ -262,12 +267,14 @@ class ThemesSelectionWithPage extends React.Component {
 	};
 
 	UNSAFE_componentWillReceiveProps( nextProps ) {
+		console.log( 'This: ' + this.props.filter + ' Next: ' + nextProps.filter );
 		if (
 			nextProps.search !== this.props.search ||
 			nextProps.tier !== this.props.tier ||
 			! isEqual( nextProps.filter, this.props.filter ) ||
 			! isEqual( nextProps.vertical, this.props.vertical )
 		) {
+			console.log( 'Calling reset page' );
 			this.resetPage();
 		}
 	}
diff --git a/client/sections.js b/client/sections.js
index c3fa608176..57c601186a 100644
--- a/client/sections.js
+++ b/client/sections.js
@@ -216,7 +216,7 @@ const sections = [
 		module: 'calypso/my-sites/themes',
 		enableLoggedOut: true,
 		group: 'sites',
-		isomorphic: true,
+		isomorphic: false,
 		title: 'Themes',
 	},
 	{
@@ -225,7 +225,7 @@ const sections = [
 		module: 'calypso/my-sites/theme',
 		enableLoggedOut: true,
 		group: 'sites',
-		isomorphic: true,
+		isomorphic: false,
 		title: 'Themes',
 		trackLoadPerformance: true,
 	},
```

Load `http://calypso.localhost:3000/themes/premium/<site>` -> Click recommended tab -> Press f5 to see changes.

I don't have a solution at this time.

**Comment by kathrynwp** [comment]
What do you think about defaulting the view to Recommended and putting it first, instead of All?

**Comment by sixhours** [comment]
@blackjackkent I've been testing this as I make small changes and I don't think the addition of `doSearch()` is working. Sometimes it pulls up the Recommended themes as I'd expect, sometimes it doesn't. 

* Open `/themes`; you'll land on All Themes first
* Click Recommended; you should see the recommended themes as expected
* Click back to All Themes; themes should start to load as expected
* Click back to Recommended; the themes don't change :(

I'm going to keep looking at it; I wonder if the empty/blank filter value is causing issues since it's not a proper filter? 🤷‍♀️

**Comment by sixhours** [comment]
Since the tab functionality is so connected to the Search bar, I wonder if it makes sense to move the SectionNav into themes-magic-search-card.jsx. Then we can take advantage of clearSearch and other functions that manipulate the search bar. I'll give that a try.

**Comment by sixhours** [comment]
Going with the approach in #54212, closing this out.

**Pull request closed without merging**
