### PR TITLE
Reader: Fix missing follow button on tag streams

### PR DESCRIPTION
**Pull request by blowery**
Also fix how bad sidebar batches are processed.

### CODE REVIEW

**Comment by blowery** [comment]
To test, follow some tags, then reload the app. Click between the tags after the sidebar loads. You should always see a follow button with the appropriate state in the tag stream header. 

On production, the follow button will disappear when you click into a tag you already follow.

**Comment by blowery** [comment]
cc @bluefuton

**Comment by bluefuton** [comment]
I'm unable to reproduce the "missing follow button when following a tag" case above. @blowery suggested this may have happened because his 2FA token was expire.

However, the follow button is missing for me on production if I _don't_ follow the tag. For example:

https://wordpress.com/tag/wolverine

... and this PR fixes that:

screen shot 2016-04-19 at 14 45 51

**Comment by bluefuton** [comment]
Looks good to me 🚢

**Pull request merged**
