### PR TITLE
Allow lazy build of messagePath prop to reduce SiteNotice re-renders

### PR DESCRIPTION
**Pull request by getdave**
This PR is part of [a wider effort to optimize the `SiteNotices` and `JITM` components to avoid the "jumpiness" of the sidebar navigation experience](https://github.com/Automattic/wp-calypso/issues/46091) both on the current production version of Calypso sidebar menu _and_ the upcoming "Unified Navigation" version of the menu.

Currently `SiteNotice` will render often due to x2 props which change frequently:

* `hasJITM`
* `messagePath`

Each time these props change the entire component renders which causes the entire "Notices/Nudges" area to be removed from the DOM and then reinserted a few seconds later. This causes the entire nav to "jump".

This PR seeks to optimize the `messagePath` case. The `hasJITM` issue ~will be~ is [being addressed in another PR](https://github.com/Automattic/wp-calypso/pull/46677).

As `messagePath` changes on each route change (due to the string being built using `sectionName` - eg: `calypso:${ sectionName }:sidebar_notice`) we need to avoid passing this as a prop to `SiteNotice` (which then passes it to `JITM`) in order to avoid it [`SiteNotice`] re-rendering.

This currently happens here

https://github.com/Automattic/wp-calypso/blob/dc10a93c1defa5f222275ef9554b888c0a9d45fe/client/my-sites/current-site/notice.jsx#L314

To do this this PR updates `JITM` to accept a _function_ as the `messagePath` prop (whilst also retaining the existing string based API as the default). This function is then called internally with `JITM` to lazily produce the `messagePath`. 

We can now remove the `messagePath` prop from `SiteNotice` and instead pass an instance method (function) _directly_ to `JITM` in order to dynamically build the `messagePath` on a per route basis. With this change `SiteNotice` renders much less frequently.

Note that the existing string-based API for `messagePath` is retained in `JITM` in order to preserve backwards compatibility with the following existing implementations:

* https://github.com/Automattic/wp-calypso/blob/dc10a93c1defa5f222275ef9554b888c0a9d45fe/client/my-sites/theme/main.jsx#L348
* https://github.com/Automattic/wp-calypso/blob/dc10a93c1defa5f222275ef9554b888c0a9d45fe/client/layout/index.jsx#L201

## Changes proposed in this Pull Request

* Update `JITM` to accept a function as `messagePath`. 
* Update the `messagePath` in `JITM` to be built from props to account for the above.
* Remove `messagePath` prop from `SiteNotice`.
* Pass a function as `messagePath` to `JITM` from `SiteNotice` which builds the `messagePath`.

#### Profiling

*  `yarn && yarn start`. Wait for Calypso to boot.
* Goto `http://calypso.localhost:3000/home/` and select your test site.
* Add `?flags=nav-unification` to the end of the URL. Hit `Enter` to reload the page.
* Wait for the Notices/Nudges panel to appear. Close all other notifications that appear.
* Open React DevTools and go to the Profiler tab.
* Click the record button and start profiling.
* Click on `Pages` - wait for load, then click on `Posts`.
* Stop profiling.
* Analysis the flame chart and look for the `SiteNotice` component in the tree. Click to focus.
* Move through the timeline and watch for the `SiteNotice` component re-rendering (it will do this a few times).
* In the React DevTools sidebar look for the reasons why the component re-rendered. You should see that each time the `SiteNotice` re-renders both `messagePath` is one of the props that changed. 

Screen Shot 2020-10-22 at 11 04 34

#### Profiling

*  `yarn && yarn start`. Wait for Calypso to boot.
* Goto `http://calypso.localhost:3000/home/` and select your test site.
* Add `?flags=nav-unification` to the end of the URL. Hit `Enter` to reload the page.
* Wait for the Notices/Nudges panel to appear. Close all other notifications that appear.
* Open React DevTools and go to the Profiler tab.
* Click the record button and start profiling.
* Click on `Pages` - wait for load, then click on `Posts`.
* Stop profiling.
* Analysis the flame chart and look for the `SiteNotice` component in the tree. Click to focus.
* Move through the timeline and watch for the `SiteNotice` component re-rendering (it will do this a few times).
* In the React DevTools sidebar look for the reasons why the component re-rendered. You should see that each time the `SiteNotice` re-renders only the `hasJITM` prop changes. The `messagePath` prop should only change infrequently.

Screen Shot 2020-10-22 at 11 02 16

#### Test JITM requests continue to fire on _per section_ basis

This is to check that with the change to `SiteNotice` the `messagePath` _built_ within JITM is still changing on a per section basis.

* Goto http://calypso.localhost:3000/home/ and select your test site.
* Add ?flags=nav-unification to the end of the URL. Hit Enter to reload the page.
* Wait for the Notices/Nudges panel to appear. Close all other notifications that appear.
* Open Chrome Devtools Network tab and search for jitm jetpack to filter requests.
* Using the sidebar menu, navigate between a few menu sections.
* You should see requests being triggered. Click on one, go to the Header tab and scroll to the Query String Parameters at the bottom. You should see the query includes a messagePath with the middle portion that changes on each new route you click (eg: `calypso:pages:sidebar_notice`, `calypso:posts:sidebar_notice`...etc).

Screen Shot 2020-10-22 at 12 00 43

#### Test existing hardcoded JITM requests continue to fire

This is to check that components using the existing string-based `messagePath` for `JITM` still work:

* Goto `http://calypso.localhost:3000/home/` and select your test site.
* Add `?flags=nav-unification` to the end of the URL. Hit `Enter` to reload the page.
* Goto a Theme detail page (eg: `http://calypso.localhost:3000/theme/seedlet/{{YOUR_TEST_SITE_HERE}}?flags=site-unification`)
* Open Chrome Devtools Network tab and search for `jitm jetpack` to filter requests.
* You should a request being triggered. Click on one, go to the `Header` tab and scroll to the `Query String Parameters` at the bottom. You should see the `query` includes a `messagePath` equal to `calypso:theme:admin_notices`. This marries up with that hardcoded in https://github.com/Automattic/wp-calypso/blob/dc10a93c1defa5f222275ef9554b888c0a9d45fe/client/my-sites/theme/main.jsx#L348.

Screen Shot 2020-10-22 at 12 08 49

-----

Addresses part of https://github.com/Automattic/wp-calypso/issues/46091

### CODE REVIEW

**Review by cpapazoglou — APPROVED** [review]
Works well for me from a performance & UI perspective.
It seems that the `SiteNotice` doesn't rerender while profiling

I flashes though on each route change (until the route is once loaded). I assume this will be resolved in the JITM PR.

This PR enhances the performance so ✅ from me.

**Comment by mreishus** [comment]
- I want to try a different approach that solves the problem of `sectionName` changing causing the entire `SiteNotice` component to re-render without introducing the complexity of a string-or-function prop.  Give me a moment and I'll make a PR to be examined.
- I didn't think that `SiteNotice` rerendering was causing the messages to jump in and out.  I thought it was because `JITM` was looking for messages in a new part of state that corresponded to the new page, and it didn't have any messages yet (so they disappeared).  When the JITM ajax request to the backend resolved, then it had messages again (so they reappeared).  I thought the cache introduced in another PR was solving this problem?

**Comment by getdave** [comment]
> I thought the cache introduced in another PR was solving this problem?

That PR is now available in improved form here https://github.com/Automattic/wp-calypso/pull/46677

It's highly probable that `messagePath` is a red herring. If so, so much the better!

**Comment by sixhours** [comment]
In testing this, I haven't been able to see `messagePath` or `hasJITM`, I think because my test site is showing [different notices that are not JITMs that are hard-coded into Calypso](https://github.com/Automattic/wp-calypso/blob/b8d5d2b355072390301b26c8c04d8529c3c2378f/client/my-sites/current-site/notice.jsx):

Screen Shot 2020-10-22 at 11 18 58 AM

Is there an easy way to trigger JITMs for testing purposes?

**Comment by mreishus** [comment]
@getdave : Can you check out #46688? I'm not married to it, but my thinking was, if SiteNotice is rerendering due to some responsibility it has - offload that responsibility to a different component instead of using a function passthrough.  Any thoughts?

**Review by mreishus — APPROVED** [review]
This works and avoids SiteNotice re-renders :heavy_check_mark:

**Comment by getdave** [comment]
> In testing this, I haven't been able to see `messagePath` or `hasJITM`, I think because my test site is showing [different notices that are not JITMs that are hard-coded into Calypso](https://github.com/Automattic/wp-calypso/blob/b8d5d2b355072390301b26c8c04d8529c3c2378f/client/my-sites/current-site/notice.jsx):
> 
> Screen Shot 2020-10-22 at 11 18 58 AM
> 
> Is there an easy way to trigger JITMs for testing purposes?

@sixhours Thanks for looking at the PR. The PR description of https://github.com/Automattic/wp-calypso/pull/46677 has some instructions for doing this. Apologies this wasn't included here but I didn't know how to do it until I wrote that other PR.

**Comment by getdave** [comment]
# Update

We may end up going with a hybrid approach https://github.com/Automattic/wp-calypso/pull/46713

**Comment by getdave** [comment]
Closing. See https://github.com/Automattic/wp-calypso/issues/46091#issuecomment-715294931 for details.

**Pull request closed without merging**
