### PR TITLE
Rewind: update notice for VP is running so it takes user to the flow to switch to Rewind

### LINKED ISSUE #22697: Rewind: Incorrect link in notice?
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/stats/activity/{site-url}
2. Make sure site is on a Rewind-capable plan
3. Click the banner titled "VaultPress is running"

#### What I expected
A way to switch.

#### What happened instead
1. I was taken to https://wordpress.com/settings/security/{site-url}
2. There is no mention of VaultPress/Rewind
3. There is not mention of Backups at all!

### PR DESCRIPTION
**Pull request by eliorivero**
Fixes #22697

This PR:
- updates the link of the `VaultPress is running.` notice so when the site has VP running but can be switched to Rewind, the link takes the user to the flow to switch to Rewind
- updates the heading and body of the notice

### Previous wording
captura de pantalla 2018-02-22 a la s 10 36 02

### New wording
captura de pantalla 2018-02-27 a la s 10 41 45

### Testing

Use a site where VP is active but can be switched, that is, where Rewind is not active due to the reason `vp_can_transfer`:
- go to Activity Log and make sure the notice is shown with the updated text
- click the notice and make sure you're taken to the flow to enter creds

### CODE REVIEW

**Comment by beaulebens** [comment]
Needs copy-review to make sure that the message being displayed makes full sense given the context, and is consistent with others (e.g. no period on the title).

It feels like this should be more of an enticing offer to upgrade/switch to the new system, rather than something that sounds like an error/problem.

**Comment by eliorivero** [comment]
@nicoleckohler can you please review the copy and provide one that follows Beau's requirement?
Thanks!

**Comment by nicoleckohler** [comment]
@eliorivero @beaulebens happily!

Just considering the other message we use to prompt users to migrate from VP -> Rewind, we may want to stick with something somewhat similar that makes it clear a switch will occur:

> **Try our new backup service**
> Get real-time backups with one-click restores to any event in time.

Does this work for y'all? Would you prefer a bit including that this will deactivate and replace VaultPress or is this mentioned at some point in the flow?

**Comment by keoshi** [comment]
> *Try our new backup service*

Do we want to tie this more closely with Jetpack? We could refer to this as Jetpack backups, as we already do in [some places](https://github.com/Automattic/wp-calypso/search?utf8=%E2%9C%93&q=%22jetpack+backups%22&type=). If so, this could be reworded to:

> *Try the new Jetpack backups*

cc @nicoleckohler

**Comment by nicoleckohler** [comment]
@keoshi The user is already (pretty deep) within Jetpack in this context so I'm not sure there's much of an advantage to bringing the name up again.

**Pull request merged**
