### PR TITLE
Summary: Show clearer number of users imported/failed after import

### PR DESCRIPTION
**Pull request by lezama**
Fixes https://github.com/Automattic/jetpack-roadmap/issues/1898

## Proposed Changes

* Simplifies summary screen copy for clarity and simplified translations, and improves code structure
Screenshot 2024-11-06 at 11 18 40

Screenshot 2024-11-06 at 14 53 36
Screenshot 2024-11-06 at 14 59 56

## Testing Instructions

* Import and try skipping content and subscribers separately, and one run where you don't skip either one.

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Comment by simison** [comment]
In a follow-up let's add the tooltip visible in Figma after "not imported": 

Screenshot 2024-11-06 at 14 46 21

**Comment by simison** [comment]
I was able to get the import to this state after multiple retries (no subs details listed):

Screenshot 2024-11-06 at 15 07 14

Meta:
```
{
    "id": 1395165,
    "status": "failed",
    "scheduled_at": "2024-11-06 15:04:40",
    "timestamp": "1730898279",
    "email_count": "9",
    "subscribed_count": 0,
    "already_subscribed_count": 0,
    "failed_subscribed_count": 0,
    "paid_subscribers_count": "1",
    "platform": "substack",
    "paid_subscribed_count": 0,
    "paid_already_subscribed_count": 0,
    "paid_failed_subscribed_count": 0
}
```

**Comment by simison** [comment]
I removed this gap for now and will look a bit how to add it back either in this PR or in a follow-up:

image

**Review by lezama — COMMENTED** [review]
Looks much better and feels safe to merge. Let’s go ahead with the merge and look into follow-ups afterward!

**Review by simison — APPROVED** [review]

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/16988359).

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/16988359).

**Pull request merged**
