### PR TITLE
Advanced SEO: refactor seo settings page

### PR DESCRIPTION
**Pull request by vindl**
Remove Search Preview code that is no longer needed - it was replaced with `Show Previews` button. 
Also fixes CSS related lint warnings.

### CODE REVIEW

**Comment by vindl** [comment]
@roundhill @dmsnell

**Comment by roundhill** [comment]
Might not be related to this PR, but I've noticed that the Front page meta description I've set for the site doesn't show up in the preview, it is instead showing the site's tagline.

**Comment by vindl** [comment]
@roundhill I've reproduced it too and verified that it is not related to this PR. Filed a separate PR that fixes that issue here: #8455

**Comment by dmsnell** [comment]
@vindl looks good to me. I'm going to remove myself from this in case @roundhill has further comments. You have my 👍

**Comment by roundhill** [comment]
I'm a go :shipit:

**Pull request merged**
