### PR TITLE
Import in Signup: Set the site to private by default

### PR DESCRIPTION
**Pull request by jblz**
Note: We should land this in conjunction w/ the account activation change proposed in D20847-code. 

#### Changes proposed in this Pull Request

* Set the `public` param to `-1` when the flow name is `import` & a URL is provided
* Unnest the logic for setting new site params so it's easier to read
  * `prettier` changes d/t the unnesting

#### Testing instructions

* Run this branch
* Complete an import via `/start/import`
* Confirm the new site is private and unlaunched
* Confirm the site is only launchable when account is verified

### CODE REVIEW

**Comment by scruffian** [comment]
Tested this, and it works great. It would be good to refactor this file a bit more, so that we don't have two different calls to `sitesNew`.

**Comment by alisterscott** [comment]
@jblz this broke our e2e tests for signing up with an import - it looks like it doesn't land to the right place anymore. I will disable the test to keep things green - would you mind taking a look?

**Comment by jblz** [comment]
@alisterscott I think it was actually D20847-code that broke the test. Will fix.

Thanks for the ping!

**Comment by alisterscott** [comment]
Oh, I see - which explains why all the e2e tests passed against this PR 👍

**Comment by alisterscott** [comment]
Thanks @jblz 

I've disabled that e2e temporarily whilst either the tests are updated or there is a fix made - I'm still not sure whether production behaviour for this is desired or not

https://github.com/Automattic/wp-e2e-tests/pull/1630

**Pull request merged**
