### PR TITLE
Relax domain forwarding restrictions

### LINKED ISSUE #81323: Domain Forwarding: Allow forwarding to the same domain
We have [previously blocked redirects to the same domain](https://github.com/Automattic/wp-calypso/pull/80665) to avoid infinite loops. Since allowing users to redirect a subdomain to a specific page on their domain is a highly requested feature from HEs, now it's time to support it.

Feature request for more context: pb5gDS-3ig-p2#comment-4068

Image

### Acceptance criteria:

- [ ] We still want to block redirects from the main domain to the same domain
- [x] Allow subdomain redirects to the main domain or a sub-path of it

### PR DESCRIPTION
**Pull request by candy02058912**
Fixes https://github.com/Automattic/wp-calypso/issues/81323

## Proposed Changes

* Add matching logic to D121450-code
* Allow forwardings to same domain
* The validation is to prevent infinite redirects and certificate errors at a basic level (no cycle checks and such, users should take care of that on their end)

We can now set domain forwarding to something.example.com -> www.example.com/test

## Testing Instructions

* sandbox and patch diff D121450-code
* Go to /domains/manage
* Select a domain
* Add subdomain forwarding and domain forwarding and try to break things

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

**Comment by paulopmt1** [comment]
We just got that check removed @candy02058912 🥳 pMz3w-ijD-p2#comment-112289

**Review by paulopmt1 — APPROVED** [review]
It's looking good @candy02058912, Thanks for addressing this, now we met all the requirements we expected to have on Domain Forwarding v2!

I added a non-blocking suggestion here: p1694607767750459-slack-CKZHG0QCR

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/8934380

Hi @candy02058912, could you please edit the description of this PR and add a screenshot for our translators? Ideally it'd include this string: `Forwarding to a further nested domain is not allowed.`

Thank you in advance!

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/8934380).

**Pull request merged**
