### PR TITLE
Intent Step: Updates copy for DIFM

### PR DESCRIPTION
**Pull request by aneeshd16**
#### Changes proposed in this Pull Request

* Updates the description for the DIFM intent on the Intent step. (p1653979921409979/1653915402.250519-slack-C028NRBP2AU)

#### Testing instructions

* Go to `/setup/intent?siteSlug=<site slug>`
* Confirm that the copy matches `Hire our experts to create your dream site`.
image

### CODE REVIEW

**Comment by aneeshd16** [comment]
Going ahead with the merge, since this is only a copy change.

**Review by ciprianimike — COMMENTED** [review]
Approved the updated copy

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/7351379

Thank you @aneeshd16 for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/7351379).

**Pull request merged**
