### PR TITLE
Reader: only show following intro to users with an odd user ID

### PR DESCRIPTION
**Pull request by bluefuton**
As discussed with @aaronyan and @fraying, this PR shows the following intro banner only to users with an odd user ID. Users with an even user ID will never see the banner.

screen shot 2017-05-12 at 20 51 01

The aim here is to provide a simple A/B test where we can measure a user's behaviour across platforms and browsers after seeing the banner.

### To test

Create a brand new user account, and make sure you are only shown the banner if your user ID is odd. You might like to set a breakpoint on the following line, to see what your user ID is:

screen shot 2017-05-12 at 20 53 09

### CODE REVIEW

**Comment by samouri** [comment]
whats the logic here as opposed to an actual ab test?

**Comment by bluefuton** [comment]
> whats the logic here as opposed to an actual ab test?

From the description: "measure a user's behaviour across platforms and browsers after seeing the banner."

**Comment by aaronyan** [comment]
>whats the logic here as opposed to the usual method for an ab test?

**Comment by samouri** [comment]
Code LGTM.  I'm surprised i couldn't find any `isEven` anywhere 🤷‍♂️ .

Testing now

**Comment by aaronyan** [comment]
> whats the logic here as opposed to the usual method for an ab test?

Good question @samouri. To add to @bluefuton's point, using the userid to govern the ab test assignment ensures the user will receive the same test assignment.

The usual method for an ab test randomly assigns an ab test and then uses the browser local storage to keep track of the ab test assignment. This means that many of our users will get assigned multiple (and possibly different) ab test assignments under the following conditions:

- uses incognito/private browsing
- uses multiple devices/ logins with different device
- uses multiple browsers (Safari, Firefox, Chrome)

By assigning the abtest by userid, we can ensure the user gets the same ab test independent of the browser or device. This is because when a user uses another browser, the ab test will reassign the same ab test because ab test assignment is based on userid (immutable).

**Comment by samouri** [comment]
@aaronyan, that seems like a solid argument for _always_ using user_id!

**Comment by samouri** [comment]
there has to be a better way of testing this than creating a new accounts and 🤞 your fingers than you get an odd and an even. exploring alternatives now

**Comment by samouri** [comment]
tested:
- created a single new account.  it was even and did not see the intro banner
- locally modified the isEven call to add 1 to the number first (flipping the even/oddness).  then that same user _did_ see the intro banner

🚢

**Pull request merged**
