### PR TITLE
Copy changes for performance plan

### LINKED ISSUE #74955: Performance plan copy changes
We need to update copies and images in various places, mostly in calypso and one in WPCOM backend.

## Acceptance criteria

1. Update the following copies:

### Upgrades > Plans

URL: `/plans/{sitename}`

- Update highlighted copies

Image

- Remove copies

Image

- Update copy

Image

### Checkout screen

URL: `/checkout/{sitename}`

Update copy

Image

### Plans upgraded 

URL: `/plans/my-plan/trial-upgraded/{sitename}`

- Update copies
- Update images

Image

### Post upgrade plans page

URL: `/plans/{sitename}`

- Update sidebar copy (handled by p1679918610140949/1679659379.416929-slack-C03Q87XT1QF)
- Update other copies

Image

### Expiry page

URL: `/plans/my-plan/trial-expired/{sitename}`

Image

### PR DESCRIPTION
**Pull request by ilyasfoo**
Fixes https://github.com/Automattic/wp-calypso/issues/74955

## Proposed Changes

* Copy updates for performance plan

Figma: lD0gTB4IqGsmSmsnjZNaP6-fi-2157-19583

For screenshots, please refer to issue https://github.com/Automattic/wp-calypso/issues/74955

## Testing Instructions

Please see https://github.com/Automattic/wp-calypso/issues/74955 for the changes in this PR. URL is included in the issue, review and make sure the screenshots with highlighted portion matches with this PR.

- Plans screen before purchase
- Checkout screen
- Plans upgraded screen
- Plans screen after purchase
- Free trial expiry screen

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

**Review by chihsuan — APPROVED** [review]
Thanks for working on this! LGTM and tested well with Calypso Live.

**Comment by chihsuan** [comment]
@ilyasfoo 👋  It seems that there are some conflicts that need to be resolved.

**Comment by ilyasfoo** [comment]
Thanks, @chihsuan! I've resolved the conflict

**Review by rjchow — APPROVED** [review]
LGTM! Thanks! There's a e2e test failure but I don't think its related to this PR

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/7894850

Hi @ilyasfoo, could you please edit the description of this PR and add a screenshot for our translators? Ideally it'd include all of the following strings:
- `Launch your store`
- `Share your store with the world and start accepting orders.`
- `Woo! Welcome to Woo Express`
- `Manage the return process, add warranties to products and let customers request/manage returns from their account.`

Thank you in advance!

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/7894850).

**Pull request merged**
