### PR TITLE
Reader: Fix padding around Search suggestions

### PR DESCRIPTION
**Pull request by jancavan**
## Current Search stream

**Recs:**
screenshot 2017-06-16 15 46 39

**Post results:**
screenshot 2017-06-16 15 46 54

## Wanted to make sure this didn't affect the new Search stream with Site Results:

screenshot 2017-06-16 15 50 46

screenshot 2017-06-16 15 51 03

### CODE REVIEW

**Comment by blowery** [comment]
Looks good on the search stream, but on the following stream, it's giving too much top padding.

**Comment by blowery** [comment]
screenshot 2017-06-19 12 22 06

from https://calypso.live/?branch=fix/reader/search-suggestions-padding

**Comment by jancavan** [comment]
Good catch @blowery. Fixed!

## Following:
screenshot 2017-06-19 10 36 37

screenshot 2017-06-19 10 39 31

## Search with recs:
screenshot 2017-06-19 10 37 15

screenshot 2017-06-19 10 40 26

## Search with post results:
screenshot 2017-06-19 10 37 58

screenshot 2017-06-19 10 40 11

Following (in new Search) and new Search is unaffected with this change:
screenshot 2017-06-19 10 45 12

screenshot 2017-06-19 10 45 44

screenshot 2017-06-19 10 46 27

**Comment by fraying** [comment]
@jancavan LGTM

**Pull request merged**
