### PR TITLE
Stats: Update stats-download component

### PR DESCRIPTION
**Pull request by timmyc**
Part of the stats maintenance project, this branch is a quick clean-up and rename of the directory for the `download-csv` component.

__To Test__
- Open up a site stats page for a site with a good amount of traffic
- Click "View All" in a component footer, like Posts & Pages
- On the subsequent Summary Page, verify the download csv button at the bottom indeed downloads a csv file

__Further Improvements__
There are a few patterns in this file that could be further abstracted as they are re-used often in stats, just noting here for myself:

- `module-content-text`
- `ul.documentation`

### CODE REVIEW

**Comment by jancavan** [comment]
@timmyc Tested and this works, but we probably shouldn't be using a `<ul>` here since this isn't really a list. I'll fix this.

**Comment by jancavan** [comment]
@timmyc updated in https://github.com/Automattic/wp-calypso/commit/d0ab772c71a67b5f79152f73b5e1271cd27b1118 to use just `<span>` tags in `module-content-text` instead of a `<ul>`.

**Comment by jancavan** [comment]
@timmyc Used `<span>` instead of `<ul>`. Updated in https://github.com/Automattic/wp-calypso/commit/8883463991b5945f732d90b6fc824e2b07e7017c.

**Comment by timmyc** [comment]
@jancavan your changes LGTM, I think this one is good to merge.

**Pull request merged**
