### PR TITLE
fix(deps): update wordpress monorepo (take 2)

### PR DESCRIPTION
**Pull request by sirreal**
Second attempt at https://github.com/Automattic/wp-calypso/pull/41207 after it was reverted in Automattic/wp-calypso#41974

Reverted due to:

```
Uncaught TypeError: Cannot read property 'parentNode' of null
```
Apparently Coming from here:
 https://github.com/WordPress/gutenberg/blob/c9ce32fb147b864d7f1d15df8ede97699ded4e91/packages/components/src/popover/index.js#L331-L335

### CODE REVIEW

**Comment by sirreal** [comment]
Rebased.

**Comment by sirreal** [comment]
This seems to have been introduced here:

https://github.com/WordPress/gutenberg/commit/ef73ed07bd59bdcbbe77cc1c537299d8e39167b1#diff-ccdf667da5123277e79748286c32fda7R328-R333

```js
			if ( __unstableBoundaryParent ) {
				boundaryElement = containerRef.current.closest(
					'.popover-slot'
				).parentNode;
			}
```

There's a bug, `.closest` can (and does in this case) return `null`.

**Comment by sirreal** [comment]
I've opened https://github.com/WordPress/gutenberg/pull/22264 for the the Popover issue.

**Comment by Addison-Stavlo** [comment]
Nice, with WordPress/gutenberg#22264 now merged this should be about ready for another chance at deployment?

Looking at the conflict in `yarn.lock`:

Master:
```
"@wordpress/icons@*":
  version "1.4.0"
  resolved "https://registry.yarnpkg.com/@wordpress/icons/-/icons-1.4.0.tgz#805732a5527eb2178bd97b53decac67451b2b1b3"
  integrity sha512-YNW1ocZddZ6c40QHiR/Q3yIPYzh4Fdcq/J4sJIkegwqEXltVknYa90RNaDG9xr+qMvXN5/wotYaLA+AP6pUfHA==
  dependencies:
    "@babel/runtime" "^7.9.2"
    "@wordpress/element" "^2.13.1"
    "@wordpress/primitives" "^1.4.0"

"@wordpress/icons@1.2.0", "@wordpress/icons@^1.2.0":
  version "1.2.0"
  resolved "https://registry.yarnpkg.com/@wordpress/icons/-/icons-1.2.0.tgz#734c8d684c8a02d688e8d96e5ce57de574d5c388"
  integrity sha512-9QuXr1FA4byrlQ5SQWoVE/BMzoDqhX1AYuzZeZh9aa9dlHLo8cMQ0hGhbgtrv8GsztRniRZ/ms7UqlkFxXgD8g==
  dependencies:
    "@babel/runtime" "^7.8.3"
    "@wordpress/element" "^2.12.0"
    "@wordpress/primitives" "^1.2.0"
```

Here:
```
"@wordpress/icons@*", "@wordpress/icons@1.4.0", "@wordpress/icons@^1.4.0":
  version "1.4.0"
  resolved "https://registry.yarnpkg.com/@wordpress/icons/-/icons-1.4.0.tgz#805732a5527eb2178bd97b53decac67451b2b1b3"
  integrity sha512-YNW1ocZddZ6c40QHiR/Q3yIPYzh4Fdcq/J4sJIkegwqEXltVknYa90RNaDG9xr+qMvXN5/wotYaLA+AP6pUfHA==
  dependencies:
    "@babel/runtime" "^7.9.2"
    "@wordpress/element" "^2.13.1"
    "@wordpress/primitives" "^1.4.0"
```

Rebased in favor of the latter.

Is there anything else this needs to wait on at this point?

**Comment by scinos** [comment]
Rebased to solve conflicts in `yarn.lock`

**Comment by sirreal** [comment]
> Is there anything else this needs to wait on at this point?

We need a new release of `@wordpress/packages`. The fix hasn't been published yet.

I check https://unpkg.com/browse/@wordpress/components/src/popover/index.js to see whether it includes that change we need (latest is `9.5.0`)

**Comment by sirreal** [comment]
Somehow I've apparently managed to mangle this. Let's proceed with Renovate's https://github.com/Automattic/wp-calypso/pull/42031

**Pull request closed without merging**
