### PR TITLE
Theme Discovery: Launch Partner Collection on LoTS

### PR DESCRIPTION
**Pull request by rcrdortiz**
Related to:
- https://github.com/Automattic/dotcom-forge/issues/4442

## Proposed Changes

* Changed config keys to launch the Partner collection on the LoTS

## Testing Instructions

* Checkout this branch locally.
* Run this command: `yarn feature-search themes/discovery-lots `
* You should see that the feature is enabled everywhere.
* You can also check the Calypso live link and it should be available.

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

**Comment by rcrdortiz** [comment]
Do not merge until we get an OK from @Copons & @ianstewart

**Comment by Copons** [comment]
@rcrdortiz We decided to wait until the LiTS side is ready, as it was part of a specific stakeholder request.

**Comment by rcrdortiz** [comment]
> @rcrdortiz We decided to wait until the LiTS side is ready, as it was part of a specific stakeholder request.

Sure, are we going to release just on LoTS when everything is ready or both LoTS & LiTS at the same time? Should I update the PR to activate the LiTS too?

**Comment by Copons** [comment]
> > @rcrdortiz We decided to wait until the LiTS side is ready, as it was part of a specific stakeholder request.
>
> Sure, are we going to release just on LoTS when everything is ready or both LoTS & LiTS at the same time?

Release on both LoTS and LiTS together.

> Should I update the PR to activate the LiTS too?

Yes, thanks! 🙇‍♂️ 

I guess at this point we could just drop the two separate flags and keep a single one for convenience? It would also simplify all the conditions (e.g. just `discovery-flag` instead of  `(is-logged-in && lits-flag) || (logged-out && lots-flag)`).

**Comment by rcrdortiz** [comment]
> > > @rcrdortiz We decided to wait until the LiTS side is ready, as it was part of a specific stakeholder request.
> > 
> > 
> > Sure, are we going to release just on LoTS when everything is ready or both LoTS & LiTS at the same time?
> 
> Release on both LoTS and LiTS together.
> 
> > Should I update the PR to activate the LiTS too?
> 
> Yes, thanks! 🙇‍♂️
> 
> I guess at this point we could just drop the two separate flags and keep a single one for convenience? It would also simplify all the conditions (e.g. just `discovery-flag` instead of `(is-logged-in && lits-flag) || (logged-out && lots-flag)`).

We now only have one config key. I've also enabled it everywhere. I'll leave this as blocked until we fix the remaining LiTS issues.

**Review by Copons — APPROVED** [review]

**Pull request merged**
