### PR TITLE
Theme Detail Page: Theme preview should not block the logged-out footer

### PR DESCRIPTION
**Pull request by taipeicoder**
## Proposed Changes

As reported in p1682626513803089-slack-CRWCHQGUB, the fixed theme preview in the Theme Detail page blocks the logged-out footer. Note that only themes with style variations have the fixed theme preview.

image

## Testing Instructions

* Head to the logged-out Theme Showcase.
* Scroll to the bottom of the page and ensure that the theme preview doesn't block the logged-out footer.
* Optional: Check the logged-in Theme Showcase, and ensure that the fixed theme preview works as before.
* Optional: Check the mobile view, and ensure that the theme preview works as before.

## Pre-merge Checklist

- [x] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [x] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [x] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [x] Have you checked for TypeScript, React or other console errors?
- [x] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [x] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [x] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

**Comment by arthur791004** [comment]
I guess we can simply introduce a new class name to overwrite the position with `sticky` here and support something like `offsetTop` to customize the top position. WDYT?

https://github.com/Automattic/wp-calypso/blob/23f14e47d2e30197bea4aba5f4d370edcf89ed51/client/components/sticky-panel/style.scss#L16

**Comment by arthur791004** [comment]
Not related to this PR but I found I cannot scroll inside the iframe on mobile. Is it the correct behavior (I forgot)?

Also, I feel a bit confused about this section on mobile. It's not clear to let user know this is a live preview of the current theme 😓

image

**Comment by taipeicoder** [comment]
> I guess we can simply introduce a new class name to overwrite the position with `sticky` here and support something like `offsetTop` to customize the top position. WDYT?
> 
> https://github.com/Automattic/wp-calypso/blob/23f14e47d2e30197bea4aba5f4d370edcf89ed51/client/components/sticky-panel/style.scss#L16

I was hesitant of using `position: sticky` since one of the main div (`layout__content`) in the page has `overflow: hidden` set. See: https://stackoverflow.com/questions/43909940/why-does-overflowhidden-prevent-positionsticky-from-working

I changed `overflow: hidden` to `overflow: clip` in order to avoid the said div turning into a scrollable container. See: https://www.terluinwebdesign.nl/en/css/position-sticky-not-working-try-overflow-clip-not-overflow-hidden/

**Comment by taipeicoder** [comment]
> Not related to this PR but I found I cannot scroll inside the iframe on mobile. Is it the correct behavior (I forgot)?
> 

Yes, there was a discussion of disabling interaction with the iframe on mobile. The reason being that it would be easy for users to accidentally scroll the iframe instead of scrolling the page. I tried finding the discussion but couldn't find it 😅

> Also, I feel a bit confused about this section on mobile. It's not clear to let user know this is a live preview of the current theme 😓

Agreed! I think since it's not interactable, it looks more of a screenshot image. @lucasmendes-design do you have any thoughts on this?

**Review by arthur791004 — APPROVED** [review]
Tested and it looks great 🎉

**Comment by lucasmendes-design** [comment]
Hi @taipeicoder, I tested and agreed that the site preview on mobile feels confused. It's because we changed how we show that compared to the Desktop preview. Some suggestions are below: 

**Mobile view:** ([Figma file](https://www.figma.com/proto/Tv3pYqA3EcRfiXC31IxrXE/Site-Assembler-part-2?page-id=1%3A71&node-id=331-10751&viewport=1190%2C-2327%2C0.71&scaling=min-zoom&hide-ui=1))
image

**Desktop Preview:** we have a drop shadow and also rounded corners. 
image

**Remove the button Live Demo:**
image

**On mobile, I couldn't change the styles.** 
image

I also think that when we scroll the page on mobile we can have a sticky header or footer showing the theme name and the CTAs. Not sure if it's for now, but we can iterate later :)

**Pull request merged**
