### PR TITLE
Domains: Create Breadcrumbs component

### PR DESCRIPTION
**Pull request by leonardost**
#### Changes proposed in this Pull Request

This PR creates a Breadcrumbs component which will be used throughout the domain pages redesign project detailed in pcYYhz-m2-p2.

Example screenshot (desktop view):

Annotation on 2021-10-15 at 12-51-55

And in mobile view:

Annotation on 2021-10-15 at 13-05-50

#### Testing instructions

I'd suggest cloning this PR to your local environment and hacking the `render` method of some component (e.g. `my-sites/domains/domain-management/list/index.jsx`) to render the `Breadcrumbs`. Replace the `render` method's contents with:

```
const helpBubble = (
	<>
		<span>Manage the domains connected to your site.</span> <a href="#">Learn more</a>
	</>
);
const items = [
	{ label: 'Domains', helpBubble }, // simple breadcrumb item with help bubble
	{ label: 'travellingwithkids.com' }, // breadcrumb with help bubble
	{ label: 'DNS records', href: '#' }, // breadcrumb with link
];
const mobileItem = {
	label: 'Back',
	href: '#',
	showBackArrow: true,
	helpBubble,
};

const buttons = [
	<Button primary>Add a domain</Button>,
	<Button disabled>Site domains</Button>,
	<Button>...</Button>,
];
const mobileButtons = [ <Button primary>Add a domain</Button>, <Button>...</Button> ];

return (
	<Main fullWidthLayout>
		<Breadcrumbs
			items={ items }
			mobileItem={ mobileItem }
			buttons={ buttons }
			mobileButtons={ mobileButtons }
		/>
		<SidebarNavigation />
	</Main>
);
```

Also add these two imports:

```
import { Button } from '@automattic/components';
import Breadcrumbs from 'calypso/my-sites/domains/domain-management/components/breadcrumbs';
```

Then, if you run Calypso and access "Upgrades > Domains" you should see the Breadcrumbs component like in the screenshots above. Try changing the component's properties to see how different items are rendered. Also please test in mobile view.

### CODE REVIEW

**Comment by leonardost** [comment]
Rebase

**Review by hambai — APPROVED** [review]
Okay this looks and works great but there is one thing that concerns me a little. The `mobileItems` and `mobileButtons` properties - can't we generate those from the regular `items` and `buttons` instead? I think it's fine doing that in a separate PR as it can technically be done outside the component itself

**Comment by leonardost** [comment]
@hambai

**Comment by leonardost** [comment]
> can't we generate those from the regular items and buttons instead?

@hambai that's a good question! I thought about doing it that way, but from analyzing the designs, the desktop and mobile views can differ in many ways - for example, the "All domains" desktop view has the filter button in the breadcrumbs section, but the mobile does not:

Screen Shot 2021-10-18 at 13 42 51
Screen Shot 2021-10-18 at 13 43 11

The DNS page mobile view only has a "Back" button

Screen Shot 2021-10-18 at 13 44 04
Screen Shot 2021-10-18 at 13 44 19

But the DNS record creation/update page has a "Back to DNS records" label:

Screen Shot 2021-10-18 at 13 43 43
Screen Shot 2021-10-18 at 13 43 30

Because of these divergences I thought it was better to create separate properties for the mobile view, but I'm open to other suggestions 🙂

**Pull request merged**
