### PR TITLE
Fix themes count

### PR DESCRIPTION
**Pull request by unDemian**
## Summary
This PR fixes the counts on the themes page. They get mixed up when filters are used https://github.com/Automattic/wp-calypso/issues/15833 . In order to fix this a new flag (`adjustCounts`) was added to the `QueryManager` which lets us disable the updates of the`found` field for previous matching request. Also its `matches` method was implemented for themes section.

## Testing
The steps from https://github.com/Automattic/wp-calypso/issues/15833 should not be reproducible anymore.

### CODE REVIEW

**Comment by sirreal** [comment]
I've looked the code over, but I'd like to get some background on _why_ this is the right approach. Can you help me understand why `adjustCounts` needed to be added to `QueryManager`?

Based on the issues described, it seems likely that there's an issue with the implementation which would affect all classes extending `QueryManager`.

**Comment by unDemian** [comment]
Thanks for your time, and sorry for not adding more context to the description. I'll try to explain my findings and hopefully paint a clearer picture of what the problem is and why I chose to add a new flag.

It seems to me that the problem described in the issue is not surfacing an underlying `QueryManager` bug but more it's of a misuse of the library. What happens is that by design whenever `QueryManager` receives new items goes through all previous (cached) queries and if a newly received item matches a previous query it will add/remove the item and also update the `found` counts (https://github.com/Automattic/wp-calypso/blob/master/client/lib/query-manager/index.js#L329). 

I guess this was added because there are endpoints that do not have a reliable `found` field. However that is not the case for themes endpoints where the server side `found` field reflects the exact number of filtered themes.

There were two issues fixed by this PR. 

The first one is that the matching mechanism was not implemented for themes. By default the `QueryManager` exposes an interface-like comparing method (https://github.com/Automattic/wp-calypso/blob/master/client/lib/query-manager/index.js#L80) that has to be implemented when extending the class. Example of its implementation for other entities https://github.com/Automattic/wp-calypso/blob/master/client/lib/query-manager/post/index.js#L29. This method was not implemented so whenever the `QueryManager` would check if an item is part of a previous query, the `matches` method would say yes.

The second problem issue is the presence of incorrectly updated found counts. Which is partially fixed by properly matching items to previous queries, but for the themes filters use case where we also have correct server side `found` fields we don't need the logic that updates the previous queries found counts.

Example of the bug reported in the issue

| Action | Effect |
| ------------- | ------------- |
| 1. Customer requests All themes  | A mix of 20 the free and premium themes are quested |
|  | The total number of themes is received from the server |
| 2. Customer then filters only `Free` themes  | 20 free themes are requested from the server |
|  | The newly received themes are going to match the previous `All` query  |
|  | The total number of themes will be incremented by the number of newly requested free themes that were not part of the 20 `All` themes initially requested |

From my tests, this issue is not present (visible) in other implementations of the query manager, either because the query found counts are not used, or endpoints/filters behave a bit different.

I added the flag because the logic that updates previous queries' found field didn't seem to have a flawed calculation or other kind of obvious bug it just did not match how themes filters and endpoints work. I did not have enough time to go into the details of all `QueryManager` implementation to see why the "update counts" logic was needed but it seemed to be there by design and it is not needed in the themes use case.

Let me know what you think about my approach, maybe I missed some obvious bug or a better way to use the `QueryManager` or maybe we could add some new functionality to it so we can fit the requirements of themes filters and endpoints. If not, I think that bypassing not needed logic should suffice.

**Comment by sirreal** [comment]
Whoa! Thanks for that excellent run-down @unDemian 👏 🏆 ⭐️ 

> I guess this was added because there are endpoints that do not have a reliable found field.

> I did not have enough time to go into the details of all QueryManager implementation to see why the "update counts" logic was needed but it seemed to be there by design and it is not needed in the themes use case.

It seems like this is a source of confusion. While I wasn't involved during the conception of `QueryManager` (QM), I'll try to shed some light on the reasons for this. 

The most important point is that QM operates on a single set of data (one big pile of item objects), and associates sets of items with individual queries via some identifier.

There is only one object representing each items, and it is shared across queries. Over time, all of these things mutate – objects change and they match or cease to match queries.

This is especially relevant for posts, here's a hand-wavy example that may or may not reflect reality:

1. A request for "my posts" fires
1. QM does its job…
1. You go off and write a new post
1. A query for "all posts" fires
1. QM again does its job again with the results from all the posts.

In the final step, your new post may well come in with the "all posts" results. The endpoint will likely specify the number of posts coming in, but we have no way of knowing that your new post will be injected into the "my posts" results and it's `found` count needs to be increased by one. _That's_ the point of this client side calculation to the best of my knowledge.

**Comment by sirreal** [comment]
I'll poke at the implementation a little bit and try to get a better understanding.

I don't understand whether you consider `adjustCounts` to be fundamentally necessary, or if it's a sort of optimization in the case of themes that don't appear to need it.

---

> The first one is that the matching mechanism was not implemented for themes. By default the `QueryManager` exposes an interface-like comparing method (https://github.com/Automattic/wp-calypso/blob/master/client/lib/query-manager/index.js#L80) that has to be implemented when extending the class.

My intuition here is that this diagnosis is spot-on. I'd bet that this is the core of the problem and that _all_ subclasses of `QueryManager` should implement the `matches` method. If I'm reading things right, by default any new item that comes in will be added to all queries.

I wonder if it's worth considering a fake abstract method implementation with something like this doodle:

```js
class QueryManager {
  constructor() {
    if ( process.env.NODE_ENV === 'development' && this.constructor.implementMe === QueryManager.implementMe ) {
      throw new Error( `\`${ this.constructor.name }\` must implement static method \`implementMe()\`` ) 
    }
  }

  /* abstract */ static implementMe() { /* 😢 */ }
}

class ThemeQueryManager extends QueryManager { 
}

const tqm = new ThemeQueryManager()
/*
Error: `ThemeQueryManager` must implement static method `implementMe()`
    at new QueryManager …
    at new ThemeQueryManager …
    …
*/
```

**Comment by sirreal** [comment]
@seear I'm working with @ockham trying to understand and recall the motivation for removing the `matches` implementation on `ThemeQueryManager`. Do you have any insights? (0b0bec85c2bc96ee9f5d9b25a4858a40bd147258)

**Comment by seear** [comment]
> trying to understand and recall the motivation for removing the matches implementation on ThemeQueryManager. Do you have any insights?

I think because it was an incomplete client-side duplication of the ElasticSearch query in the endpoint, which is not great for a number of reasons.

**Comment by sirreal** [comment]
@unDemian I've been exploring this and I believe you have uncovered some significant bugs related to found counts and the `receive` implementation in `QueryManager`.

I'll provide more details when I have an opportunity, but I'll say that I do believe the `adjustCounts` approach this PR proposes covers up deeper problems. I think it would be preferable to start adding tests that expose the issues and working to correct the deeper problems.

**Comment by unDemian** [comment]
> I'll provide more details when I have an opportunity, but I'll say that I do believe the adjustCounts approach this PR proposes covers up deeper problems. I think it would be preferable to start adding tests that expose the issues and working to correct the deeper problems.

Thanks for taking the time to look into this. I've worked on this during Hack Week, unfortunately I don't have the necessary bandwidth to continue working on it. I might be poking at it every now and then, but I can't commit to a strong timeline for finding and fixing the `QueryManager`'s bug.

**Comment by unDemian** [comment]
I guess it would be better to close this PR and move the findings in the ticket description.

**Comment by sirreal** [comment]
> I guess it would be better to close this PR and move the findings in the ticket description.

Given there seems to be a larger, I should open a new issue to track that.

I don't think this PR should be abandoned because the `ThemeQueryManager.matches` is most likely worthwhile, although I've been focused on the found counts and haven't looked into that specifically.

**Comment by seear** [comment]
> ThemeQueryManager.matches is most likely worthwhile

I want to caution against this again. Any attempt at this is trying to duplicate an ElasticSearch query in js, which is both futile and wasteful.

**Comment by sirreal** [comment]
> I want to caution against this again. Any attempt at this is trying to duplicate an ElasticSearch query in js, which is both futile and wasteful.

😬 right, forgot that. Thanks @seear.

I wonder if the implementation for `ThemeQueryManager.matches` might just be `return false`. That way only API results would match and no client-side attempts are made to implement the logic.

**Comment by sirreal** [comment]
> I wonder if the implementation for ThemeQueryManager.matches might just be return false.

🤔 That likely won't work either. It will remove matching items that come in on new queries from old queries (and decrement their counts).

The only valid approach I see at this point is to implement `ThemeQueryManager.receive` so that it does not modify any queries other than the current one.

It's a bit unfortunate, but QueryManager doesn't seem to be a great fit for themes or any queries that can't have their logic "duplicated" on the front end.

**Comment by alisterscott** [comment]
This branch needs a rebase. Is this PR still required?

**Comment by unDemian** [comment]
I think we can close this, the fix was mostly a workaround around a bigger issue, which I think was handled in a different ticket.

**Comment by sirreal** [comment]
Yes, I think we can close this. This was a workaround for an issue with `QueryManager` counts. There's some good detective work here that will remain available in this thread.

I don't believe any fix has been proposed or applied at this time. I can still see the bug from #15833 in production.

**Comment by unDemian** [comment]
@sirreal Thanks for stepping, I lost the details about the bug

**Pull request closed without merging**
