### PR TITLE
Framework: Stop transforming selector imports

### PR DESCRIPTION
**Pull request by dmsnell**
Previously we have been transforming selector import paths so that
although it appears like we're importing all selectors from
`state/selectors` Babel actually transforms them into separate paths as
individual modules like `state/selectors/is-this-really-right`

This historically helped us shrink the generated bundle size because it
meant that we needn't import all of the selectors but since we have now
stopped compiling through CommonJS webpack is able to effectively pull
in only those selectors required in each bundle.

This patch replaces the transform with an actual
`state/selectors/index.js` file with the explicit exports.
IDEs and tools should now be able to more reliably interact with
selectors since the magic has been removed.

> It is so nice to be able to jump to the selectors again and benefit
from auto-complete and linting errors on invalid imports.

http://iscalypsofastyet.com/branch?branch=framework/stop-transforming-selector-imports
```
Delta:
chunk                                                                                                          stat_size             parsed_size             gzip_size
account~async-load-design-blocks~async-load-post-editor-media-modal~happychat~help~me~media~notifica~7858008a    -1942 B    (-2.6%)       -297 B    (-0.8%)      -93 B    (-1.0%)
account~happychat~help~me~notification-settings~privacy~purchases~security                                       -6197 B    (-4.3%)      -3288 B    (-4.0%)     -667 B    (-3.5%)
checkout~domains~jetpack-connect~plans~purchases~settings~signup                                                  -106 B    (-0.1%)       -170 B    (-0.5%)      -27 B    (-0.3%)
checkout~customize~plugins~purchases~settings~theme~themes                                                      -11287 B   (-15.7%)      -5265 B   (-20.5%)    -1334 B   (-18.5%)
async-load-design~people~post-editor~settings~settings-writing~woocommerce                                       -1706 B    (-5.1%)      -1129 B    (-5.6%)     -265 B    (-5.3%)
settings~settings-discussion~settings-security~settings-traffic~settings-writing                                 -5056 B    (-9.2%)      -1466 B    (-4.6%)     -211 B    (-3.2%)
async-load-design-blocks~async-load-post-editor-media-modal~media~post-editor~posts-custom~posts-pag~b59c4d6f   -32639 B  (deleted)     -17344 B  (deleted)    -4443 B  (deleted)
accept-invite~async-load-design-blocks~jetpack-connect~login~signup                                              -3379 B    (-9.9%)      -2476 B   (-11.7%)     -566 B   (-10.1%)
accept-invite~checkout~jetpack-connect~signup                                                                       +6 B    (+0.0%)         -5 B    (-0.0%)       -6 B    (-0.1%)
vendors~async-load-design-blocks~async-load-reader-following-manage~async-load-reader-search-stream~~fc38723e       +0 B                    +0 B                  +1 B    (+0.0%)
account~async-load-design~settings~woocommerce                                                                  -31209 B  (deleted)     -14913 B  (deleted)    -4274 B  (deleted)
async-load-design-blocks~post-editor~posts-custom~posts-pages                                                   +27764 B   (+71.0%)     +15724 B   (+80.5%)    +3184 B   (+55.6%)
async-load-design-blocks~checkout~purchases~woocommerce                                                           -376 B    (-0.8%)        -13 B    (-0.1%)       -8 B    (-0.1%)
vendors~async-load-design-blocks~post-editor~wp-job-manager~zoninator                                               +0 B                    +0 B                  +3 B    (+0.0%)
wp-job-manager~wp-super-cache~zoninator                                                                         -30843 B  (deleted)     -15131 B  (deleted)    -3680 B  (deleted)
checkout~domains~plans                                                                                           -1027 B    (-2.7%)       -361 B    (-1.6%)      -67 B    (-1.3%)
post-editor~settings-writing~woocommerce                                                                         -1049 B    (-2.1%)       -860 B    (-3.2%)     -178 B    (-2.7%)
accept-invite~jetpack-connect~signup                                                                              -393 B    (-0.6%)         -9 B    (-0.0%)      -16 B    (-0.2%)
jetpack-connect~plans~signup                                                                                     -2679 B    (-2.6%)      -1051 B    (-1.9%)     -263 B    (-1.9%)
vendors~plans                                                                                                       +0 B                    +0 B                  -1 B    (-0.0%)
async-load-design~stats~woocommerce                                                                                 +0 B                    +0 B                  -1 B    (-0.0%)
async-load-extensions-woocommerce-app-store-stats~google-my-business~stats                                       -1039 B    (-3.1%)       -433 B    (-2.3%)     -112 B    (-2.2%)
async-load-design-blocks~post-editor~woocommerce                                                                    +0 B                    +0 B                  -1 B    (-0.0%)
async-load-design-blocks~posts-custom~posts-pages                                                                -9207 B    (-5.3%)      -2448 B    (-2.9%)     -541 B    (-2.9%)
async-load-post-editor-media-modal~media~post-editor                                                             -2821 B    (-1.2%)       -690 B    (-0.6%)     -139 B    (-0.5%)
async-load-components-web-preview-component~async-load-design-blocks~reader                                      -9047 B    (-3.3%)      -5178 B    (-3.4%)    -1043 B    (-3.0%)
checkout~plugins                                                                                                -30617 B  (deleted)     -16879 B  (deleted)    -4696 B  (deleted)
posts-custom~posts-pages                                                                                          -815 B    (-1.5%)       -363 B    (-1.2%)      -78 B    (-1.0%)
checkout~domains                                                                                                 -3379 B    (-5.6%)      -2476 B    (-7.0%)     -480 B    (-5.8%)
theme~themes                                                                                                     -2781 B    (-3.0%)      -1464 B    (-2.6%)     -249 B    (-2.0%)
async-load-blocks-inline-help-popover~help                                                                      -10229 B    (-8.5%)      -4025 B    (-6.0%)    -1131 B    (-7.4%)
domains~signup                                                                                                   -1596 B    (-0.8%)       -938 B    (-0.8%)     -200 B    (-0.7%)
vendors~post-editor~woocommerce                                                                                     +0 B                    +0 B                  -1 B    (-0.0%)
vendors~async-load-post-editor-media-modal~post-editor                                                              +0 B                    +0 B                  +1 B    (+0.0%)
async-load-design-blocks~reader                                                                                 -30278 B  (deleted)     -18111 B  (deleted)    -4314 B  (deleted)
async-load-design-blocks~domains                                                                                  -385 B    (-1.0%)        -20 B    (-0.1%)       -2 B    (-0.0%)
post-editor~woocommerce                                                                                           -496 B    (-1.1%)       -294 B    (-1.2%)      -73 B    (-1.0%)
vendors~settings-traffic                                                                                            +0 B                    +0 B                  -1 B    (-0.0%)
vendors~woocommerce                                                                                                 +0 B                    +0 B                  +1 B    (+0.0%)
zoninator                                                                                                       +26844 B   (+23.0%)     +12257 B   (+22.8%)    +2224 B   (+18.0%)
wp-super-cache                                                                                                  +29137 B   (+13.9%)     +13941 B   (+14.2%)    +2400 B   (+10.6%)
wp-job-manager                                                                                                  +26511 B   (+22.2%)     +11904 B   (+20.8%)    +2196 B   (+16.3%)
woocommerce                                                                                                     +24407 B    (+1.2%)     +12327 B    (+1.5%)    +3079 B    (+1.7%)
devdocs                                                                                                             +0 B                    -8 B    (-0.0%)       -3 B    (-0.0%)
comments                                                                                                        -10116 B    (-3.4%)      -3471 B    (-2.5%)     -791 B    (-2.3%)
happychat                                                                                                           +0 B                    +0 B                  -1 B    (-0.1%)
posts-custom                                                                                                       -28 B    (-0.4%)        -11 B    (-0.3%)       -8 B    (-0.6%)
auth                                                                                                                +0 B                    +0 B                  +1 B    (+0.4%)
login                                                                                                            -2944 B    (-4.3%)       -765 B    (-2.3%)     -129 B    (-1.6%)
help                                                                                                               -17 B    (-0.0%)        -13 B    (-0.1%)       -9 B    (-0.1%)
reader                                                                                                          +21455 B    (+9.9%)     +13957 B   (+12.2%)    +2371 B    (+8.7%)
account-recovery                                                                                                 -8493 B   (-13.5%)      -2106 B    (-7.5%)     -386 B    (-5.4%)
post-editor                                                                                                     -42039 B    (-4.2%)     -21224 B    (-4.4%)    -4733 B    (-3.9%)
mailing-lists                                                                                                       +0 B                    +0 B                  +1 B    (+0.1%)
ads                                                                                                              -1720 B    (-2.0%)      -1140 B    (-2.2%)     -255 B    (-2.2%)
accept-invite                                                                                                       +0 B                    +0 B                  -1 B    (-0.0%)
plans                                                                                                            -1137 B    (-2.1%)       -338 B    (-1.3%)      -72 B    (-1.1%)
checkout                                                                                                        +23767 B    (+7.0%)     +14294 B    (+8.2%)    +3063 B    (+7.5%)
domains                                                                                                          -3520 B    (-0.7%)       -697 B    (-0.3%)     -191 B    (-0.4%)
theme                                                                                                              -24 B    (-0.1%)        -20 B    (-0.1%)      -10 B    (-0.2%)
themes                                                                                                           -4847 B    (-3.0%)      -2136 B    (-2.8%)     -507 B    (-2.7%)
checklist                                                                                                        -1347 B    (-2.8%)       -922 B    (-3.0%)     -195 B    (-2.6%)
stats                                                                                                           -20900 B    (-4.0%)      -5359 B    (-2.1%)    -1367 B    (-2.4%)
signup                                                                                                           -6142 B    (-1.7%)      -3310 B    (-1.5%)     -541 B    (-1.0%)
jetpack-onboarding                                                                                              -74200 B   (-73.4%)     -34234 B   (-70.6%)    -6890 B   (-62.4%)
jetpack-connect                                                                                                  -2482 B    (-1.1%)      -1154 B    (-0.9%)     -240 B    (-0.8%)
sharing                                                                                                          -8984 B    (-3.5%)      -2839 B    (-2.1%)     -497 B    (-1.8%)
settings                                                                                                        +19847 B    (+7.9%)     +11750 B    (+9.0%)    +2877 B    (+9.2%)
settings-security                                                                                               -12909 B   (-11.2%)      -5591 B    (-8.8%)     -916 B    (-6.8%)
settings-traffic                                                                                                -18182 B    (-8.8%)      -8878 B    (-8.8%)    -1808 B    (-7.9%)
settings-discussion                                                                                              -7390 B   (-11.8%)      -3336 B    (-9.5%)     -545 B    (-7.1%)
settings-writing                                                                                                -10223 B    (-4.4%)      -3278 B    (-2.8%)     -452 B    (-1.7%)
posts-pages                                                                                                       -339 B    (-0.4%)       -254 B    (-0.6%)      -72 B    (-0.7%)
plugins                                                                                                         +19239 B    (+6.6%)     +14001 B    (+9.0%)    +3089 B    (+8.6%)
people                                                                                                           -2202 B    (-0.8%)      -1022 B    (-0.7%)     -190 B    (-0.6%)
media                                                                                                           +27087 B   (+36.3%)     +15388 B   (+39.7%)    +2930 B   (+28.2%)
concierge                                                                                                        -5789 B    (-5.1%)      -2281 B    (-4.3%)     -522 B    (-4.4%)
notification-settings                                                                                             -469 B    (-0.4%)        -36 B    (-0.1%)      -22 B    (-0.2%)
purchases                                                                                                        -7932 B    (-2.3%)      -1317 B    (-0.8%)     -370 B    (-1.0%)
security                                                                                                          -774 B    (-0.4%)        -86 B    (-0.1%)      -15 B    (-0.1%)
account                                                                                                         +29051 B   (+62.3%)     +14381 B   (+48.6%)    +3347 B   (+42.9%)
customize                                                                                                        -1184 B    (-3.7%)       -287 B    (-1.6%)      -84 B    (-1.5%)
async-load-lib-network-connection                                                                                   +0 B                    +0 B                  -1 B    (-0.1%)
async-load-lib-happychat-connection                                                                                 +0 B                    +0 B                  -1 B    (-0.1%)
async-load-my-sites-current-site-domain-warnings                                                                   -24 B    (-1.2%)        -20 B    (-1.4%)      -12 B    (-1.9%)
async-load-layout-masterbar-drafts-popover                                                                         +15 B    (+0.1%)         +0 B                  +0 B
async-load-notifications                                                                                         -1168 B   (-12.1%)       -513 B    (-8.9%)     -123 B    (-6.5%)
async-load-blocks-inline-help-popover                                                                            -1706 B    (-5.7%)      -1129 B    (-7.2%)     -294 B    (-7.2%)
async-load-components-web-preview-component                                                                      -1658 B    (-1.7%)      -1347 B    (-2.4%)     -175 B    (-1.4%)
async-load-lib-rubberband-scroll-disable                                                                            +0 B                    +0 B                  -1 B    (-0.3%)
async-load-reader-feed-stream~async-load-reader-site-stream                                                       -391 B    (-0.8%)       -295 B    (-0.9%)      -66 B    (-1.0%)
async-load-reader-following-manage~async-load-reader-search-stream                                               -2393 B    (-4.5%)      -1075 B    (-3.4%)     -242 B    (-3.5%)
async-load-blocks-calendar-popover~async-load-design-blocks~post-editor                                           -554 B    (-1.8%)       -279 B    (-1.6%)      -53 B    (-1.2%)
vendors~async-load-reader-following-manage~async-load-reader-search-stream                                          +0 B                    +0 B                  +1 B    (+0.0%)
manifest                                                                                                            +0 B                  -411 B    (-3.2%)     -119 B    (-2.2%)
async-load-post-editor-media-modal~post-editor                                                                     -13 B    (-0.0%)        -11 B    (-0.0%)      -15 B    (-0.1%)
async-load-design~async-load-design-blocks                                                                       -2233 B    (-0.3%)       -297 B    (-0.0%)      -80 B    (-0.1%)
async-load-post-editor-media-modal                                                                              +27764 B  (+389.2%)     +15724 B  (+387.1%)    +3534 B  (+212.6%)
async-load-my-sites-site-settings-section-export                                                                    +0 B                    +0 B                  +1 B    (+0.0%)
async-load-my-sites-site-settings-section-import                                                                    +0 B                    +0 B                  +1 B    (+0.0%)
async-load-post-editor-editor-discussion                                                                            +0 B                    +0 B                  -1 B    (-0.1%)
async-load-post-editor-editor-location                                                                              +0 B                    +0 B                  -1 B    (-0.0%)
async-load-featured-image                                                                                           +0 B                    +0 B                  -1 B    (-0.1%)
async-load-post-editor-editor-sharing-accordion                                                                   -873 B    (-2.4%)       -489 B    (-2.4%)     -119 B    (-2.4%)
async-load-post-editor-editor-post-formats-accordion                                                             -1102 B    (-8.3%)       -234 B    (-3.4%)      -82 B    (-4.0%)
async-load-blocks-reader-full-post                                                                                 -25 B    (-0.0%)        -22 B    (-0.0%)      -11 B    (-0.1%)
async-load-reader-following-manage                                                                               -1514 B    (-2.2%)       -489 B    (-1.4%)     -105 B    (-1.2%)
async-load-reader-tag-stream-main                                                                                 -313 B    (-1.1%)        -45 B    (-0.3%)      -11 B    (-0.3%)
async-load-reader-search-stream                                                                                   -129 B    (-0.5%)       -161 B    (-1.1%)      -29 B    (-0.7%)
async-load-reader-list-stream                                                                                      +15 B    (+0.1%)         +0 B                  +0 B
async-load-reader-team-main                                                                                         +0 B                    +0 B                  -1 B    (-0.4%)
async-load-reader-site-stream                                                                                       +0 B                    +0 B                  -1 B    (-0.0%)
async-load-reader-sidebar                                                                                          -26 B    (-0.0%)        -70 B    (-0.2%)      -13 B    (-0.2%)
async-load-blocks-calendar-popover                                                                               -1069 B    (-6.2%)       -599 B    (-5.7%)     -110 B    (-3.5%)
async-load-design-blocks                                                                                       -673908 B   (-54.5%)    -674312 B   (-68.9%)  -114063 B   (-63.7%)
async-load-design                                                                                               +19461 B    (+5.2%)      +7610 B    (+3.6%)    +2534 B    (+6.1%)
async-load-extensions-woocommerce-app-store-stats-listview                                                        -800 B    (-3.7%)        -46 B    (-0.3%)      -33 B    (-0.8%)
async-load-extensions-woocommerce-app-store-stats-referrers                                                      -1598 B    (-4.7%)       -544 B    (-2.6%)     -144 B    (-2.6%)
async-load-extensions-woocommerce-app-store-stats                                                                -1581 B    (-3.1%)       -531 B    (-1.8%)     -150 B    (-2.1%)
build                                                                                                          +282260 B    (+9.6%)     +90671 B    (+6.9%)   +20504 B    (+6.9%)
```

### CODE REVIEW

**Comment by dmsnell** [comment]
why did this bloat `build`?

**Comment by blowery** [comment]
@dmsnell might be worth trying this on top of https://github.com/Automattic/wp-calypso/pull/22860 to see if webpack@4 offered any improvement.

**Comment by dmsnell** [comment]
thanks @blowery - it was easy enough to create that I think I'll just wait until webpack4 is merged. I'm pretty sure the bloat is all due to the issue with webpack@<4 when doing `export * from 'something'`

**Comment by dmsnell** [comment]
strange @blowery that after Webpack4 this is still bloating the build.

**Comment by blowery** [comment]
@dmsnell super strange! 

I'd try to chase this down by telling the minimizer not to compress whitespace (or run the minimized code through prettier) and compare the output. My guess is that something odd is happening with tree-shaking / scope hoisting.

**Comment by jsnajdr** [comment]
@dmsnell Try to add file `client/state/selectors/package.json` with this content:
```json
{
  "sideEffects": false
}
```
It will tell Webpack that the re-exports in `client/state/selectors/index.js` don't have any side effects and can be omitted if unused. That should deliver the optimization effect you're looking for.

**Comment by dmsnell** [comment]
thanks @jsnajdr I forgot about that - this won't mess with things like `createSelector`, right? since it's not pure or side-effect-free?

**Comment by blowery** [comment]
sideEffect here has a bit of a special meaning:

> A "side effect" is defined as code that performs a special behavior when imported, other than exposing one or more exports. An example of this are polyfills, which affect the global scope and usually do not provide an export.

either way, `createSelector` isn't inside the selectors directory, so it's not affected by the flag.

**Comment by samouri** [comment]
@dmsnell: there are really good explanations of what is happening in this thread: https://github.com/webpack/webpack/issues/1750#issuecomment-201651773

I believe @jsnajdr is right about needing to declare the modules `sideEffect` free

**Comment by dmsnell** [comment]
Closing because I have no time to maintain this. It's not hard to recreate.

1. Remove the transform
2. Add re-export statements into `state/selectors.js'
3. Run `npm start` and fix the import errors

For (2) I used a mixture of BASH and RegEx-based replacements but a
simple `node` based script could work

```js
const fs = require( 'fs' );
const _ = require( 'lodash' );

const selectorFiles = fs.readdirSync( './client/state/selectors/', 'utf8' ).filter( f => f.endsWith( '.js' ) );

const output = selectorFiles.map( file => {
	const name = file.split( '.' )[ 0 ];
	return `export { default as ${ _.camelCase( name ) } } from './${ name }';`;
} ).join( '\n' );

fs.writeFileSync( './client/state/selectors.js', output, 'utf8' );
```

**Pull request closed without merging**
