### PR TITLE
Merge Release/desktop/3.0.0 into master

### PR DESCRIPTION
**Pull request by astralbodies**
Merges several desktop-related fixes for WPDesktop 3.0.0 back into master.

### CODE REVIEW

**Comment by ockham** [comment]
Hmm, haven't these been merged to `master` before?
https://github.com/Automattic/wp-calypso/pull/18985 and https://github.com/Automattic/wp-calypso/pull/18966 seem to indicate so.

**Comment by astralbodies** [comment]
I'm following git-flow to merge any changes in a release branch back to master even if the changes were cherry-picked. It's not entirely compatible with the rebase methodology that Calypso follows but doing this ensures no regressions with future releases.

GitHub's diff doesn't really account for things properly because of the rebase technique when merging a PR and the original cherry pick commits evaporating from history.

**Comment by ockham** [comment]
> I'm following git-flow to merge any changes in a release branch back to master even if the changes were cherry-picked.

But are there ever any commits on a release branch that haven't been merged to `master` yet?

**Comment by astralbodies** [comment]
> But are there ever any commits on a release branch that haven't been merged to master yet?

Yup there are - if we're fixing something to get a desktop release out then most likely the PRs for those fixes are aimed at the release branch because it's code-frozen at the time of the release. Sometimes the fixes are made in the mainline/master either by accident (targeted the wrong branch in the PR) or the fix was made after the code freeze.

**Pull request merged**
