### PR TITLE
Design Picker: Theme Card recognizes individual premium theme purchases

### PR DESCRIPTION
**Pull request by mreishus**
#### Proposed Changes

* Design Picker: Theme Card recognizes individual premium theme purchases

#### Note: Interaction with other changes

This will need further update once #66048 + D84731-code is merged.

I'll have to change the format of `purchasedThemes`. It's currently an array of theme names, `[ 'skivers', 'payton' ]`, but it will need to contain both the name and the period.  Maybe `[ {name: 'skivers', period: 'yearly'}, ... ]` ?

#### Testing Instructions

* Have a free site with an individual premium theme purchased
* Go to `/setup/designSetup?siteSlug=<SITE_SLUG>&flags=signup/seller-upgrade-modal` (note the flag)
* Find a Premium theme, and note the pricing information below the theme's name.

Related to #65704 #66135 #66048

### CODE REVIEW

**Comment by mreishus** [comment]
For the screen that appears after you click on one individual theme, see #66239.

**Review by markbiek — APPROVED** [review]
Works as expected and tests pass. LGTM!

**Comment by mreishus** [comment]
Rebased to resolve conflicts with #66239 (they both added `useQuerySitePurchases()`, but different code right after)

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/7464134

Thank you @mreishus for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/7464134).

**Pull request merged**
