### PR TITLE
Performance History: Improve display of Boost Speed Scores

### PR DESCRIPTION
**Pull request by danielbachhuber**
See https://github.com/Automattic/boost-cloud/issues/282

## Proposed Changes

Improves the display of Boost Speed Scores in the Activity Log.

### Before

CleanShot 2023-09-05 at 09 11 28@2x

### After

CleanShot 2023-09-06 at 05 01 47@2x

## Testing Instructions

1. See test instructions in D120696-code

### CODE REVIEW

**Comment by haqadn** [comment]
I tested it on my site, and it looks nice! The design actually had proposed something for the activity log. The changes would be:
- The activity icon.
- The text to include the overall score.
- A CTA to launch Boost.

Activity log

**Review by wojtekn — APPROVED** [review]
Works as expected.

**Comment by danielbachhuber** [comment]
@haqadn @ederrengifo I made some changes to D120696-code, so here's how it looks now:

CleanShot 2023-09-06 at 05 01 47@2x

Notably:
1. I updated the main text to `Overall score: A, mobile 99 / 100, desktop 100 / 100`.
2. I updated the secondary text to `Site performance score recorded`. The proposed `New site performance score` doesn't match the structure of the other activity items.
3. I didn't add a Boost CTA because it's inconsistent with the other activity items. Only the Rewind items have actions, and it's hardcoded into Calypso (i.e. not accessible in apps).
4. I'm still using the 'plans' gridicon and the 'Activity' type. I think we need to use a gridicon for iOS/Android compat.

Is there a different gridicon you'd like to use? Other suggested changes?

**Review by haqadn — APPROVED** [review]
> @haqadn @ederrengifo I made some changes to [D120696-code](https://href.li/?https://code.a8c.com/D120696), so here's how it looks now:
> 
> CleanShot 2023-09-06 at 05 01 47@2x
> Notably:
> 
> 1. I updated the main text to `Overall score: A, mobile 99 / 100, desktop 100 / 100`.
> 2. I updated the secondary text to `Site performance score recorded`. The proposed `New site performance score` doesn't match the structure of the other activity items.
> 3. I didn't add a Boost CTA because it's inconsistent with the other activity items. Only the Rewind items have actions, and it's hardcoded into Calypso (i.e. not accessible in apps).
> 4. I'm still using the 'plans' gridicon and the 'Activity' type. I think we need to use a gridicon for iOS/Android compat.
> 
> Is there a different gridicon you'd like to use? Other suggested changes?

I don't see Boost in gridicons. So, I'll defer to @ederrengifo for that. Otherwise looks good to me.

**Pull request merged**
