### PR TITLE
ESLint: fix some JSDoc comment violations

### PR DESCRIPTION
**Pull request by jsnajdr**
I ran `eslint --fix` for the `jsdoc/check-tag-names` and this diff is what I got.

### CODE REVIEW

**Comment by blowery** [comment]
Looks like at least `rule-content-detect-media.js` got messed up by the autofix...

**Comment by jsnajdr** [comment]
> Looks like at least `rule-content-detect-media.js` got messed up by the autofix...

Not only this file, but also many others ☹️ The `jsdoc/newline-after-description` has a bug: when the description starts right after the two stars:
```js
/** description
 * ...
 */
```
then it incorrectly determines the line where the violation is. Note the misplaced red dot in this editor screenshot:

Screenshot 2019-12-04 at 12 13 16

And then `eslint --fix` adds an extra star at that place that's outside the comment ⚡️ 

Solved by removing `jsdoc/newline-after-description` from this patch and leaving only the two other rules.

**Comment by gwwar** [comment]
Maybe run this against a smaller file set? This is a lot to review at once if we don't trust the output in all cases

**Comment by jsnajdr** [comment]
> Maybe run this against a smaller file set? This is a lot to review at once if we don't trust the output in all cases

Yes, I'm afraid we'll have to do that 🙂

**Comment by blowery** [comment]
https://github.com/Automattic/wp-calypso/pull/38179 has a bunch of fixes regarding carriage returns. After we land that, maybe rerun the fixes here?

**Comment by jsnajdr** [comment]
After some back and forth, this PR ended up only fixing instances of `jsdoc/check-tag-names`, and replaces `@return` with `@returns`. The type names were fixed by @tyxla in #38627, and the autofix for the `jsdoc/newline-after-description` rule turned out to be unreliable.

Ready for review. The PR changes 800+ files. I agree it would be better to create a series of smaller PRs that are easier to review, but I'm not willing to spend my time and energy on that 🤷‍♂

**Comment by tyxla** [comment]
Rebased again as merging #38586 introduced some new conflicts. Will review now.

**Comment by tyxla** [comment]
Fixed remaining instances in https://github.com/Automattic/wp-calypso/pull/38142/commits/c1e0fc20dac7e64b8aaad0e44a6acf84aa3f4d85 and rebased again. This looks great, approving!

**Review by tyxla — APPROVED** [review]
LGTM 🚢 🎉

**Pull request merged**
