### PR TITLE
Fixes a styling issue in the Blaze Dashboard app

### PR DESCRIPTION
**Pull request by sbarbosa**
Fixes some styling issues in the Blaze Dashboard app. 

Screenshot 2023-06-29 at 10 49 17

## Proposed Changes

* Changed the way we solved a conflicting stylesheet to be more generic. The previous version only worked correctly in self-hosted sites (not in atomic).
* Fixed a visibility problem with the Create campaign widget popovers
* Fixed a visibility problem with the Create campaign widget date pickers

## Testing Instructions
You will need a Jetpack local environment running to test this. Also, you will need to be able to execute a code snippet that will open a gate for the Blaze Dashboard. To do so, follow these instructions:
* Install the Plugin Code Snippets
* Create a new snippet with the following content: `add_filter( 'jetpack_blaze_dashboard_enable', '__return_true' );`

---

* Checkout this branch, then open a terminal and navigate to wp-calypso/apps/blaze-dashboard
* Execute `BLAZE_DASHBOARD_PACKAGE_PATH=/path/to/jetpack/projects/packages/blaze yarn dev`
You will need to change the path to your local Jetpack installation.
* In another terminal tab, go to the Jetpack repo directory and execute: `pnpm jetpack build packages/blaze`
* Now open your Jurassic tunnel and enter the wp-admin page for your local site
* Click on Tools->Advertising
* Click on the Promote button next to the Jetpack Blaze header
* Verify that the search input in the **Select post to promote** page is displayed correctly.
* Shrink your screen into a mobile view
* Click on the three-dot menu for one of the rows
* Verify that the popover is displayed correctly
* Click on the Promote button
* Verify that all the inputs of that page are displayed correctly
* Click on the calendar icon in the **Start date** section
* Verify that the Date picker popover is displayed correctly

## Pre-merge Checklist

- [x] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [x] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [x] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

**Review by timur987 — COMMENTED** [review]
Thanks @sbarbosa!

The changes look good but I've found a couple of things I considered as important ones:

1. You've mentioned the calendar icon in the Start date section, but I can't see it at all for a mobile screen (I used a device toggle image):

(How toggled mobile screen hides calendar icon)
image

(How even the screen is 350px wide but device is toggled off shows a calendar icon)
image

2. Also I've noticed that the line under the Posts/Campaigns/Credits tabs is affected when screen size is equals or lower than `480px`:
blazepress-tabs

Or even more detailed:

https://github.com/Automattic/wp-calypso/assets/115007291/4f310b8e-e649-438b-a079-bc279257cc85

Since Jetpack App was not published yet, I see no blockers to merge this RP as-is.

What would you say?

**Comment by sbarbosa** [comment]
Thanks for the feedback @timur987! 
I will take a look at those points. Strange what happened to you about the calendar icon.

**Comment by sbarbosa** [comment]
Nice find with the calendar icon @timur987! On mobile screens, the Create campaign widget removes the icon, and you open the dialog by clicking the date. But it opened differently, so the dialog was hidden because of the z-index issue 😞. 

I will check every link in the Widget to see if there is another dialog option and see that it is displayed correctly in Jetpack.

**Comment by sbarbosa** [comment]
@timur987, I tested all the links and couldn't find another case of a hidden popover. 
Regarding the behavior with the calendar icon, that is happening in prod, and it's inside the Create Campaign widget. 
I just ping Yosel, so he can create a ticket and fix that problem.

I think this PR is ready for a retest. Let me know if you find something more 💪

**Review by timur987 — APPROVED** [review]
Thanks @sbarbosa!

I checked that I was able to click on start date and change it.
Despite we do not have an icon when Chrome emulates mobile device I do not see it as a blocker to merge these changes! 🎉 

blazepress-start-date-click

**Pull request merged**
