### PR TITLE
Jetpack Connect: Remove problematic "blacklist"/"whitelist" language #43395

### PR DESCRIPTION
**Pull request by saramarcondes**
#### Changes proposed in this Pull Request

* Rename `SITE_BLACKLISTED` to `SITE_BLOCKED`
* Rename `isSiteBlacklistedError` to `isSiteBlockedError`
* Rename `MOBILE_APP_REDIRECT_URL_WHITELIST` to `ALLOWED_MOBILE_APP_REDIRECT_URL_LIST`

#### Testing instructions

* Ensure blocked sites still behave as expected (are not allowed to connect to Jetpack, etc).

Addresses part of https://github.com/Automattic/wp-calypso/issues/43395

### CODE REVIEW

**Comment by saramarcondes** [comment]
@sirreal Pinging you as I think the actual person who originally worked on this was Marin but he's still on parental leave. Any chance you could review this or suggest someone else if you're not able?

**Comment by nsakaimbo** [comment]
👋 Seeing this error in the source build for wp-desktop:

`ERROR in ./jetpack-connect/jetpack-connection.jsx 167:17-33
 
"export 'SITE_BLACKLISTED' was not found in './connection-notice-types'
 `

**Comment by saramarcondes** [comment]
Thanks @nsakaimbo, changes are up 👍

**Comment by AnnaMag** [comment]
@saramarcondes, thumbs up that I get an error message in the [error message](https://github.com/Automattic/wp-calypso/pull/43647/files#diff-17da4a3cfe05c89e251f165f833a4d30R198) itself also.

**Pull request merged**
