### PR TITLE
Make sure that current section is always set in router context when changing it

### PR DESCRIPTION
**Pull request by jsnajdr**
Fixes https://github.com/Automattic/wp-calypso/issues/46684 (issue brought up by @sirbrillig in https://github.com/Automattic/wp-calypso/pull/46086#issuecomment-714634933)

Whenever some route handler sets a custom section name/group with `dispatch( setSection() )`, make sure that the new section value is also set in the `RouteContext`. This PR does that by using `setSectionMiddleware` for setting the section.

The suggestion by @tyxla in https://github.com/Automattic/wp-calypso/pull/46086#discussion_r510069167 became urgent much faster than I expected! 🙂 

It turns out that the work in #46086 wasn't really finished, so this PR contains some additional fixes like converting `LoggedOutLayout` to the route context, too.

Also fixes the `BodySectionCssClass` component to remove the `bodyClass` class from `<body>` when the component is unmounted or the `bodyClass` prop changed or removed.

**How to test:**
Go to `/checkout/thank-you/:site` and verify that the `is-section-checkout-thank-you` CSS class is present on `<body>`:
Screenshot 2020-10-23 at 08 54 48

Before this fix, the class wasn't there, there was just `is-section-checkout`:
Screenshot 2020-10-23 at 08 54 48

### CODE REVIEW

**Comment by jsnajdr** [comment]
Another thing worth testing is the registration-less checkout in the logged-out state. I'm personally totally unfamiliar with this area, so help from @niranjan-uma-shankar or @sirbrillig would be very appreciated 🙏

**Review by wp-desktop — CHANGES_REQUESTED** [review]
WordPress Desktop CI Failure for job "wp-desktop-mac".

@jsnajdr please inspect this job's build steps for breaking changes at [this link](https://circleci.com/gh/Automattic/wp-calypso/932329). For temporal failures, you may try to "Rerun Workflow from Failed".

Please also ensure this branch is rebased off latest Calypso.

**Review by sirbrillig — APPROVED** [review]
This resolves the issues I was seeing in checkout!

**Comment by sirbrillig** [comment]
This will also [fix some checkout e2e tests](https://github.com/Automattic/wp-calypso/pull/46734).

**Comment by sirbrillig** [comment]
The wp-desktop tests are failing with `Can log in`, which is odd. Everything else seems ok.

**Comment by nsakaimbo** [comment]
👋 Both the Linux and Mac are failing in the same place. Test artifacts (located [here](https://app.circleci.com/pipelines/github/Automattic/wp-calypso/78226/workflows/cfe7402a-47f5-49cb-8605-cfb69c2b7d80/jobs/932998/artifacts)) indicate a couple of issues:

1. The Desktop landing page is being rendered incorrectly (see screenshot from .mpg video capture).

<p align="center">
Screen Shot 2020-10-23 at 4 32 23 PM
</p>

2. The tests are failing because the login step bombs out with the error: `RESPONSE FindElement no such element: Unable to locate element: {"method":"css selector","selector":".is-section-auth"}` (see chromedriver .log artifact)

**Comment by sirbrillig** [comment]
It seems that this PR inadvertently breaks the `is-section-auth` CSS class somehow.

**Review by sirbrillig — APPROVED** [review]
👍 thanks for fixing the login!

**Comment by jsnajdr** [comment]
> thanks for fixing the login!

I tried to convert the `LoggedOutLayout` to use the new `RouteContext`, but didn't do all the changes that were needed. The result was that the `is-section-*` and `is-group-*` CSS classes were not added to logged-out pages, notably login. It should be fixed now.

**Pull request merged**
