### PR TITLE
Notices: remove site-notice component

### PR DESCRIPTION
**Pull request by artpi**
Part of notices refactor intitiative:
#888 #1094 #1105 #1313 

This component was only used once and didn't add much additional functionality.

Plus, design-wise, after clicking domain name, the user was redirected to domain management, which was kind of confusing.

# Design changes

Before:

After:

### Why would you put so much text there?
This is actually the most important information in the whole site right now.
I am wondering if it should be put in a permanent global notice, because no matter what people change in Calypso, they wont see anything on the frontend.

And when I was searching for a way to turn off redirection, I had to dig around A LOT.
@mtias: Any suggestions how to make this look good?

# Testing

1. Set site redirect
2. Open sidebar
3. Notice the notice (get it?)

### CODE REVIEW

**Comment by mtias** [comment]
This is great, thanks, has been on my list for a while. Once we also convert `flags` into `notice compact` it would be even better.

**Comment by folletto** [comment]
Question: do we need to show the full menu below in this case? Otherwise, the entire side column could be a custom designed component for this instance :)

**Comment by mtias** [comment]
@artpi I think the original text is fine, the only purpose of this notice is to help distinguish between the site that redirects and the site that it redirects to when you have both in your list.

**Comment by mtias** [comment]
I'd keep things as they were, just getting rid of the custom component. And we'll look at any improvements once we work on "flags".

**Comment by artpi** [comment]
Ok, so it will be like this:


But I think in future, we have to make it more usable.
I was looking for a way to turn of redirection for 40 minutes a few days ago :)

**Comment by mtias** [comment]
Sounds good. I'm working on flags now.

**Comment by mtias** [comment]
Squash and :shipit:

**Pull request merged**
