### PR TITLE
Domains: Update all domains view when there are no domains

### PR DESCRIPTION
**Pull request by eltongo**
#### Changes proposed in this Pull Request

This adds a custom prompt to buy domains when there are no domains listed yet in the all domains view.
Screenshot 2020-07-22 at 7 11 29 PM
#### Testing instructions

* For an account with no domains, go to /domains/manage
* Verify you see the view shown in the screenshot above
* Ensure things work as expected when the user has any domains

### CODE REVIEW

**Comment by eltongo** [comment]
> I don't think we need the `firstRender` state at all. We should always render the `QueryAllDomains` component - we just need to move it outside the list contents.

In that case we'd get a flash of the empty view before then showing the loading screen, since the request to query domains has not been sent on the first render. But maybe there is a better way to do this?

**Comment by hambai** [comment]
> In that case we'd get a flash of the empty view before then showing the loading screen, since the request to query domains has not been sent on the first render. But maybe there is a better way to do this?

I see... well in this case I think we can check if the unfiltered `domainsList` is empty or not. Technically it can never be completely empty because that means you won't have any site active and then this page would be inaccessible anyway.

**Comment by hambai** [comment]
> I see... well in this case I think we can check if the unfiltered `domainsList` is empty or not. Technically it can never be completely empty because that means you won't have any site active and then this page would be inaccessible anyway.

The way I see it - only if `domainsList` is not empty and the filtered list is empty we show the `EmptyContent`. Otherwise we render the normal thing which'll show 3 lines of placeholders while `domainsList` is empty or render the actual content otherwise. The `QueryAllSites` component is always rendered just inside `render`.

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/4155029

Thank you @eltongo for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/4155029).

**Pull request merged**
