### PR TITLE
Site: add "lock" badge to private sites.

### PR DESCRIPTION
**Pull request by mtias**
Remove noticon.

image

### CODE REVIEW

**Comment by rickybanister** [comment]
Yay, one less noticon. This is an improvement in my mind—it's easier to scan the picker and see the locks, it uses gridicons finally, and can be enhanced to include a site visibility switcher in the future.

What would be our icon for 'no-follow'? @drw158

**Comment by drw158** [comment]
That's a tough one. I was thinking the crossed out eye, but that's not accurate.

I think a crossed out magnifying glass would be best.

**Comment by rickybanister** [comment]
A cracked magnifying glass :P

**Comment by drw158** [comment]
Hah! Perfect

**Pull request merged**
