### PR TITLE
Editor Welcome Tour: Add close btn in minimized view

### PR DESCRIPTION
**Pull request by chriskmnds**
#### Changes proposed in this Pull Request

Adds a "close tour" btn to the minimized view, along with the tour index in the resume btn label.
Partly addresses #56168

#### Testing instructions

- Sandbox a site, checkout branch, and `yarn dev --sync` from `apps/editing-toolkit` to sync sandbox.
- Go to the editor, open the sidebar, and from there click on "Welcome Guide".
- Focus and minimize the tour: Press Esc in expanded view or click the minimize button in the panel.
- A `X` btn to dismiss the tour should be available. 
- Tour index is suffixed to the resume label.

Screenshot 2021-09-21 at 3 05 47 PM

#### Notes

Without any additional styling, the new button brings some "hover" effect to the mix, which may or may not be what we want. 🤷‍♂️ 

Kapture 2021-09-21 at 15 09 58

CC @poligilad-auto @razvanpapadopol

### CODE REVIEW

**Comment by chriskmnds** [comment]
@poligilad-auto @razvanpapadopol are we ok with the changes to wrap this up? The redesign will obviously strip things out, but we can still ship this in some form. :-)

**Comment by poligilad-auto** [comment]
@chriskmnds can we just remove the hover styling from the close button?

**Review by StefanNieuwenhuis — APPROVED** [review]
Thanks for working on this @chriskmnds!
Tested as per testing instructions and everything works like a charm. The code looks good too. I don't have any feedback on that. 

I approve it in advance, but can you please address the hover button thing that @poligilad-auto mentioned?

**Comment by chriskmnds** [comment]
> @chriskmnds can we just remove the hover styling from the close button?

We can do that @poligilad-auto , yes. We chatted a bit in the background and @razvanpapadopol brought up the thought of actually adding hover effect to both icons (vs just the text changing) might work better? I think it looks a little cleaner. 

So something like:

Kapture 2021-09-29 at 18 03 11

Or maybe keeping the index "(1/8)" stable at gray:

Kapture 2021-09-29 at 18 08 17

**Comment by poligilad-auto** [comment]
> So something like:
> 
> Kapture 2021-09-29 at 18 03 11
> 
I like this option @chriskmnds

**Comment by chriskmnds** [comment]
All done. Thanks for reviewing/commenting.

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/6760392

Thank you @chriskmnds for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/6760392).

**Pull request merged**
