### PR TITLE
Odie Client Refactor

### PR DESCRIPTION
**Pull request by arcangelini**
## Proposed Changes

1. Replaced the Calypso component texatarea with a simple custom version and refactor the send message button component. The current version was rendering the entire component with every keystroke.
2. Switch the translation hook from _x to __. No need for context on all the translations and it was inconsistent across the package.
3. Refactor the Odie mutation and query. Moved them to their own files. Removed redundancies and optimized for readability.
4. Added chatStatus state for better management of component.
5. Moved action items like dislike-feedback, thinking-placeholder, out of the chat message array and into the container managed by the new chatStatus state.
6. Removed unused context props.
7. Consolidated all constants into one location. This includes all the Wapuu responses for easier management.
8. Mirrored the Odie mutation and query for Zendesk. A few other refraction in Zendesk flow.

## Why are these changes being made?

The last pieces that need to be addressed:

- [x] When listening for messages in `useZendeskMessageListener` the metaData is not set so we can't see what conversation the message was sent to.
- [x] Sending dislike feedback is not functioning properly with the API call.

## Testing Instructions

* `yarn start`
* Open the Help Center and interact with Support.
* Test it with adding the feature flag `?flags=help-center-experience`.

## Follow-up issues

- https://github.com/Automattic/dotcom-forge/issues/9476

### CODE REVIEW

**Comment by arcangelini** [comment]
@heavyweight I tried to add an explanation for all the changes in the summary. I likely missed something but this at least explains what's up for 75% or the changes.

**Comment by renancarvalho** [comment]
Just taking notes on issues I am seeing while testing in general 🧵 

When like message:

image

**Review by renancarvalho — APPROVED** [review]
I spent a day testing and reviewing this PR.

1 — It is quite difficult to fully review code changes since it has 42 files changed, but I noticed most of the changes are code re-organization 👍 
I haven't found any weirdness in the code, though.

2 — I tested the HC with the flag using Calypso Live link, Calypso localhost, tested `wp-admin` and the `editor` on my simple site and all looks great.

3 — Without the flag, I haven't noticed any regression or missing anything.

@Automattic/vertex I think we're good to go. WDYT?

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/16939674

Some locales (Hebrew, Japanese) have been temporarily machine-translated due to translator availability. All other translations are usually ready within a few days. Untranslated and machine-translated strings will be sent for translation next Monday and are expected to be completed by the following Friday.

Hi @arcangelini, could you please edit the description of this PR and add a screenshot for our translators? Ideally it'd include all of the following strings:
- `AI profile picture`
- `Icon to expand or collapse AI messages`
- `Loading state, awaiting response from AI`

Thank you in advance!

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/16939674).

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/16939674).

**Pull request merged**
