### PR TITLE
Simple payments block: fix 404ing image due @ character

### LINKED ISSUE #29053: Simple Payments Block: Payment button in preview has broken image
Originally reported at p58i-7sR-p2 #comment-40515 while testing on WP.com

screen-shot-2018-12-04-at-3-39-06-pm

/c @simison @sirreal

### PR DESCRIPTION
**Pull request by simison**
When building Jetpack blocks using the SDK, Webpack+wpcom CDN didn't play nicely with `@` character, thus using `-` is safer.

SDK creates files with `%40` symbol and keeps URLs with `@` symbol. While that works fine with some environments (e.g. in self-hosted Ubuntu/Apache wp-admin), accessing the file path via WordPress.com CDN gives _"404 not found"_. 

I'm not sure if the issue is with the SDK/Webpack or with the CDN.

The URL:
```
paypal-button@2x-fe4d34770a47484f401cecbb892f8456.png
```

Actual filename:
```
paypal-button%402x-fe4d34770a47484f401cecbb892f8456.png
```

This won't fix whatever is the underlying issue but unblocks us for now.

Fixes #29053

### Testing instructions

- Build blocks to your sandbox locally and sync the files up to your sandbox:
   ```
    npm run sdk -- gutenberg client/gutenberg/extensions/presets/jetpack/ \
        --output-dir=YOUR_SANDBOX_PATH/wp-content/mu-plugins/jetpack/_inc/blocks-staging/ \
        --watch
    ```
- Have a site with Premium+ plan
- Insert Simple payments block in Gutenberg
- On hi-density screen, observe 2x image load properly:
    ```
    /wp-content/mu-plugins/jetpack/_inc/blocks-staging/images/paypal-button-2x-fe4d34770a47484f401cecbb892f8456.png
    ```
    
image

### CODE REVIEW

**Comment by sirreal** [comment]
> This won't fix whatever is the underlying issue but unblocks us for now.

Looks like a bug with the loader being used or a problem in configuration.

**Comment by simison** [comment]
Rebased to force a re-run of `a8c/valid-pr` hook (it was stuck in yellow)

**Comment by ockham** [comment]
Thanks for fixing @simison!

>> This won't fix whatever is the underlying issue but unblocks us for now.
>
> Looks like a bug with the loader being used or a problem in configuration.

I did a cursory search for `webpack file-loader at sign` that didn' turn up anything really. (Admittedly not the most thorough research.)

Good to merge IMO :+1:

**Comment by simison** [comment]
>     I did a cursory search for webpack file-loader at sign that didn' turn up anything really. (Admittedly not the most thorough research.)

I also checked their issues/PRs but no dice. We'll hit this again easily in future so good to figure out if it's really in Webpack or somewhere else. Noting that the file works just fine from Ubuntu/Apache on Jetpack Docker and Jurassic-Ninja — I don't think we've heard any bug reports from Jetpack plugin neither?

**Comment by ockham** [comment]
> We'll hit this again easily in future so good to figure out if it's really in Webpack or somewhere else.

I mean you can leave a comment above the `import` line, but not sure people are going to look there if they hit a similar issue because of an 'incompatible' char in a filename. Probably not worth commenting there I guess.

> I don't think we've heard any bug reports from Jetpack plugin neither?

Not that I'm aware of.

**Comment by dmsnell** [comment]
Just for reference I verified in the URL spec and a `@` seems totally legitimate in the path section (also in the login part) of the URL and has no need in URLs to be escaped.

https://www.w3.org/Addressing/URL/url-spec.txt

**Comment by dmsnell** [comment]
Also I was looking through the code flow and wasn't sure why it's getting replaced…

https://github.com/webpack-contrib/file-loader/blob/master/src/index.js#L24
https://github.com/webpack/loader-utils/blob/master/lib/interpolateName.js#L29

related issue in sass-loader: https://github.com/webpack-contrib/sass-loader/issues/89

looks like we might be able to overwrite the behavior though by providing a `customInterpolateName` function to the loader options

- https://github.com/webpack/loader-utils/blob/67499ff3d13c13ef455ec0fede90b714fc16d787/lib/interpolateName.js#L94
 - https://github.com/webpack/loader-utils/issues/53#issuecomment-280579159

**Comment by sirreal** [comment]
Opened #29284 to track the existing issue (this PR applies a workaround, issue continues to exist).

**Pull request merged**
