### PR TITLE
Reader: Add new Conversations icon

### PR DESCRIPTION
**Pull request by jancavan**
Before:
screenshot 2017-08-11 13 47 22

After:
screenshot 2017-08-11 13 47 27

Here are also several other options that I've tried:
conversations-icon-options

- I also updated the current SVG icon since it doesn't align well with the rest of the icons.
- I added this as an SVG just like the previous icon instead of adding it to the Gridicons set. I think we did it this way because it's only used internally?

### CODE REVIEW

**Comment by fraying** [comment]
I dig it! 👍

**Comment by jancavan** [comment]
Flipped Conversations icon so it both icons match: https://github.com/Automattic/wp-calypso/pull/17144/commits/23789caf3741ce504151612f898b4fc4eef83358

screenshot 2017-08-11 14 19 33

**Comment by fraying** [comment]
I REALLY dig it. 👍

**Comment by folletto** [comment]
> I added this as an SVG just like the previous icon instead of adding it to the Gridicons set. I think we did it this way because it's only used internally?

I think it's a good take being internal use.


> Flipped Conversations icon

As for flipping this, I'd update the Gridicon to be flipped. This is just a simple transformation, but might end up being unexpected in more long term maintenance (think for example if we update the icon to be something entirely different). 

My advice here would be to push this live without the flip, then update Gridicons with the updated icon (I guess we can update, doesn't seem to me we need a new one) and do a PR to push the new Gridicon version in — which would automatically change the icon.

**Comment by jancavan** [comment]
> As for flipping this, I'd update the Gridicon to be flipped. 

Just submitted a PR here: https://github.com/Automattic/gridicons/pull/243

**Pull request merged**
