### PR TITLE
Comments: add a timeout for loading

### LINKED ISSUE #15891: Comments: Sites with no comments hang on the placeholder.
If a sites has no comments of any kind, the `/comments` UX will hang on the placeholder:

screen shot 2017-07-05 at 4 37 35 pm

`showPlaceholder` always [evaluates to `true`](https://github.com/Automattic/wp-calypso/blob/master/client/my-sites/comments/comment-list/index.jsx#L234) for a site with no comments, since `isLoading` will always be `true`, being based on `hasSiteComments()` (which [relies](https://github.com/Automattic/wp-calypso/blob/a82dd1af35ec0b211f2918326fb05e1e7e5f558c/client/state/selectors/has-site-comments.js#L17) on `comments.items`).

A fix could be having `isLoading` checking on an empty `comments.totalCommentsCount`, meaning `totalCommentsCount` should be updated to 0 on receiving the API result. `totalCommentsCount` seem broken at this point though, as it's always empty, even with a site with comments.

cc/ @Automattic/lannister

### PR DESCRIPTION
**Pull request by gwwar**
This PR should fix #15891, where we could get infinite placeholders when a site had no comments.

Implementation Notes: Due to how the reducer is currently storing data, I'm having a hard time deriving fetch state without storing more information. To avoid adding `isRequesting` state, I instead opted to show the loader until either we have some comments in the current filter, or we reach our timeout.

Folks are welcome to update this in the future to be more correct.

### Testing Instructions
- Navigate to http://calypso.localhost:3000/comments/pending/
- Select a site that has no comments, or no comments that are pending
- Wait some time, we should see a notice that there are no comments
- Repeat steps above for a site with comments, we should see comments/paging behave normally

### CODE REVIEW

**Comment by gwwar** [comment]
> It does solve the issue on first load, but when we go to another filter and then back to a "no results" filter, we have to wait the two seconds every time.

Yes, that's expected. Note that this artificial wait time will only be incurred for views that have no comments. The alternative would be to add more isRequesting state, or to alter how we're storing comment-tree state currently

**Comment by Copons** [comment]
@gwwar LGTM 🚢 

> It does solve the issue on first load, but when we go to another filter and then back to a "no results" filter, we have to wait the two seconds every time.

@kwight It seems a fair enough trade off at this point, and it's not annoying at all while navigating Comment Management (it takes a couple of seconds to receive the tree and populate a page of comments anyway).

**Comment by kwight** [comment]
True - I'm probably noticing it more than most people, because I'm testing it going back and forth, back and forth. Real users will have something to do 😜

**Comment by gwwar** [comment]
Thanks for the reviews! Let's go with this for now. We can always follow up with a more correct solution after.

**Pull request merged**
