### PR TITLE
Remove Google+ share preview

### PR DESCRIPTION
**Pull request by koralcem**
#### Changes proposed in this Pull Request

* Removes the Google+ menu item from the sharing preview modal

#### Testing instructions

* Follow the instructions in https://github.com/Automattic/wp-calypso/issues/32105
* Verify that the expectation is fulfilled; the Google+ sharing preview is _not_ shown.

Fixes https://github.com/Automattic/wp-calypso/issues/32105

@Copons and/or @jhnstn Could I get your eyes here?

I believe this accomplishes the expectation in the associated issue, but I see references to Google+ in more places, like [here](https://github.com/Automattic/wp-calypso/blob/master/client/blocks/post-share/connection.jsx#L50), [here](https://github.com/Automattic/wp-calypso/blob/master/client/my-sites/marketing/connections/service-description.jsx#L53-L68), [here](https://github.com/Automattic/wp-calypso/blob/master/client/components/vertical-menu/items/social-item.jsx#L22), ... How deep should I be trying to scrub?

Also, I have 1 failing test on my branch. But the same test also fails for me on `master`. Technically that could mean I didn't introduce any new issues, but having failing tests on `master` seems fishy to begin with. Is this expected? Did I just happen to fork at an inopportune time?
fail

### CODE REVIEW

**Comment by arunsathiya** [comment]
>I have 1 failing test on my branch. 

With this PR https://github.com/Automattic/wp-calypso/pull/32507 merged, the failing test should disappear when you rebase against `master`. :)

**Comment by koralcem** [comment]
Thanks @arunsathiya. Did so, and all my CircleCI checks are green indeed.

That said, I still have an actual unit test failing on my box; the one about billing transaction dates whose screenshot I include above. There are 2 things I don't follow at this point:
- My change doesn't seem anywhere near billing stuff. How come it's causing its unit test to fail?
- If I have a test failing locally, how come all checks/tests pass for my branch on CircleCI? Does CI not run the same set of tests I get locally with `npm test`?

**Comment by koralcem** [comment]
@Copons or @jhnstn Any chance you folks have a minute to review? If not, could you suggest someone else with context who can review? Maybe @artpi?

**Comment by koralcem** [comment]
@arunsathiya Are you aware of anyone else who can review here?

**Comment by arunsathiya** [comment]
@koralcem I am sorry about the delay, but I assure someone will get on this as soon as possible.

**Comment by Copons** [comment]
Hi folks! I'm so sorry about the super long wait, this totally fell through the cracks (my cracks, that is: I accidentally marked this as done in my daily planner 🤦‍♂)!

@koralcem Thank you so much for taking care of this!
I've seen that Google+ (as `google_plus`) is mentioned around Calypso a few more times, but this change looks good to me!

I'll go ahead and deploy this myself in the next few minutes!

**Comment by arunsathiya** [comment]
Thanks for the patch, @koralcem!

**Pull request merged**
