### PR TITLE
Document moving Media Library to Redux

### PR DESCRIPTION
**Pull request by jakejones1984**
# Required for Redux

## Current Implementation - Flux

Currently the Media Library is implemented using the Flux pattern. This involves the following key elements:

### MediaListData component

- **file**: `client/components/data/media-list-data/index.jsx`
- a controller view which interacts with the media stores and actions
- accepts a set of props (`source`, `postId`, `filter`, `search`) that help build up a query to be sent to the API (note it does not handle sending HTTP requests)
- passes it's entire `state` as a prop down into the `MediaLibraryList` component
- in addition it passes down the `mediaOnFetchNextPage` prop which is ultimately called by child components of `MediaLibraryList` when they need to request the "next" page of Media items.
- `mediaOnFetchNextPage` is a reference to the `MediaListData.fetchData()` method which itself calls `MediaActions.fetchNextPage()` - it is this action that ultimately triggers a call to the `wpcom` API

### MediaActions

- **file**: `client/lib/media/actions.js`
- contains the actions used to interact with the WPCom API to obtain Media data
- `fetchNextPage` is used to retrieve multiple Media items from either internal or external (eg: Google Photos) API endpoints on WPCom. On success this action dispatches `RECEIVE_MEDIA_ITEMS`.

### Media List Store

- **file**: `client/lib/media/list-store.js`
- stores a reference to all current Media items within the Flux store. This is stored under a `_media` key on the `MediaListStore` object
- `RECEIVE_MEDIA_ITEMS` is handled here. Media is added to the `_media` object keyed by `siteId`

### QueryMedia component

- **file**: `client/components/data/query-media/index.jsx`
- `<QueryMedia />`: a query component used to request either a single Media item or mulitple Media items. It does not render anything.
- accepts a `query` argument which can be used to provide the params required for the WPCom API endpoint in order to retrieve the desired Media item(s)
- the `request` prop appears to be legacy and has been replaced by the instance's `request` method. Can likely be removed.

### MediaActions

- **file**: `client/state/media/actions.js`
- contains the key Redux actions dispatched for media related events
- `requestMedia` is the action dispatched when requesting multiple Media items. It creates an actoin with the type of `MEDIA_REQUEST`

### WPCom Data Layer Media

- **file**: `client/state/data-layer/wpcom/sites/media/index.js`
- Handles dispatching Redux actions describing HTTP requests relating to Media. Note this is part of the Calypso data layer.
- the `requestMedia` function uses the `http` helper to describe the form of the request to the WPCom API Media endpoint.
  - currently it is set up to make requests to `/sites/${ action.siteId }/media`
  - it does not currently pass the `query` parameter to the API. This will likely be required in order to enable more detailed queries to be made (for example refer to the `handleMediaItemRequest` function)
- the default `export` from this file details how requests are ultimately handled by the Calypso data layer. The `MEDIA_REQUEST` key should be studied carefully. Particularly note that the `onSuccess` handler ultimatley dispatches `receiveMedia` and `successMediaRequest` actions from `MediaActions` (see above). Studying the `receiveMedia` action in particular will provide information about the action payload that is passed through to the reducers

#### 1. Add QueryMedia component to MediaLibraryContent component

- **file**: `client/my-sites/media-library/content.jsx`
- main component for most of the Media Library - it's `renderMediaList()` method displays the Media items
- replace `MediaListData` component with `QueryMedia` component - passing the appropriate `props` into the `query` object

```
<QueryMedia
  siteId={this.props.site.ID}
  query={{
    filter: this.props.filter,
    source: this.props.source,
    search: this.props.search
  }}
/>
```

- remember query components do not render anything, they only initiate data fetch.

#### 2. Map Media state to MediaLibraryContent component props

- `QueryMedia` should result in Media items in the Redux state tree
- the state data for Media items resides at `states.media.queries[SITE_ID]` as a `MediaQueryManager` (`client/lib/query-manager/media/index.js`) object ("instance")
- we can use the `getItems()` method to return the Media items
- map this state to the props of the `MediaLibraryContent` component using the `connect` helper from `react-redux`

#### 3. Pass Media into `MediaLibraryList` component

- `MediaLibraryList` is used within `MediaLibraryContent`. It is responsible for rendering the list of Media items. It expects to receive a `media` prop containing the Media items to be rendered
- pass the Media stored in the Redux state which has been mapped to `props` into this component

#### Selected Media Items

- A `MediaLibrarySelectedStore` (`client/lib/media/library-selected-store.js`) tracks the currently selected Media items.
- This functionality will need to be replicated into Redux.
- The selected items need to be passed down into the `MediaLibraryList` as the `mediaLibrarySelectedItems` prop.

#### Other "sources"

- Currently the `requestMedia()` function within `client/state/data-layer/wpcom/sites/media/index.js` is not setup to handle calls to external services.
- within the _call_ to the `http` helper, the `path` will need to be changed based on the query's `source` (eg: for `google_photos` source it may have to call `wpcom.undocumented().externalMediaList` as it currently does in the Flux approach)
- the _call_ to the `http` helper will need to be altered to include the `query`. This will allow the WPCom media endpoint to retrieve the correct data based on the query (eg: the correct `page` in the paginated result set)

### CODE REVIEW

**Comment by alisterscott** [comment]
Is there any update on this?

**Comment by getdave** [comment]
@alisterscott This looks like a fairly major undertaking that won't get completed any time soon. It's doubtful I'm personally going to be able to assign myself to this away from my day-to-day. I'll raise it with @mattsherman however.

**Comment by mattsherman** [comment]
@getdave It is unclear to me what this issue is actually for... is it for documenting what needs to be done to move the Media Library to Redux, or for actually implementing the changes to move the Media Library to Redux? If the former, it seems that this issue accomplishes that. If the later, then I agree that this seems outside of the scope of what we could accomplish in the foreseeable future in @Automattic/delta-samus, but might be good for another team/individual to consider when in the area. 

Could this be broken down into smaller changes that could be implemented, tested, and deployed separately?

**Comment by getdave** [comment]
> It is unclear to me what this issue is actually for..

@ehg Got me to create this during my trial. 

> is it for documenting what needs to be done to move the Media Library to Redux, or for actually implementing the changes to move the Media Library to Redux

It is for documenting only.

> this seems outside of the scope of what we could accomplish in the foreseeable future in @Automattic/delta-samus

Yep I'd agree. 

> Could this be broken down into smaller changes that could be implemented, tested, and deployed separately?

Yes and it should be (by whichever team picks this up).

**Comment by bluefuton** [comment]
@getdave as this is a backlog item and doesn't contain any code, would it be possible to re-create it as an issue rather than a pull request?

**Comment by getdave** [comment]
> @getdave as this is a backlog item and doesn't contain any code, would it be possible to re-create it as an issue rather than a pull request?

Yes that would be fine.

**Comment by lancewillett** [comment]
Closing in favor of #39379

**Pull request closed without merging**
