### PR TITLE
Update holiday support closure messaging

### PR DESCRIPTION
**Pull request by mattwondra**
#### Changes proposed in this Pull Request

Updates Live Chat and Concierge standard closure notices so that:
- They're reusable for single-day and multi-day closures
- They give the exact closure and reopen times in the user's local timezone

Then it also adds the New Year's Day closure notice both for Live Chat and Concierge.

#### Testing instructions
On both `/help/contact` and `/me/concierge`:

* Check that without adjusting anything, you're seeing the "will be closed for Christmas" message
* Adjust your system time to Dec 24 at 0:00 UTC and you should see the "is closed for Christmas" message
* Adjust your system time to Dec 26 at 7:00 UTC and you should see the "will be closed for New Year's Day"  message
* Adjust your system time to Jan 1 at 0:00 UTC and you should see the "is closed for New Year's Day" message
* Adjust your system time to Jan 2 at 7:00 UTC and you should no longer see a closure message

Then reset your system clock, and change your system timezone. The message should reflect your local time according to your system's timezone.

Fixes 686-gh-hg and 687-gh-hg

### CODE REVIEW

**Comment by beaucollins** [comment]
I'm not seeing the notices on the calypso.live deploy. I'm checking local dev environment now.

**Comment by mattwondra** [comment]
@beaucollins For the `help/contact` form you need to make sure you're using a WordPress.com account that has at least one paid plan — free plans are not affected by live chat closures and will not see the notice.

**Comment by beaucollins** [comment]
@mattwondra I can only see the notice on `/help/contact` when using Chrome. Firefox and Safari fail to show any notices.


Here's a log message placed inside the `return null` branch:
```
Object { _isAMomentObject: true, _isUTC: false, _pf: {…}, _locale: {…}, _d: Date 2018-12-19T21:59:17.507Z, _isValid: true, _z: null }
 is not between 2018-12-17 00:00 UTC 2018-12-26 07:00 UTC
```

Both Safari and Firefox do this. Strangely this is saying that

`2018-12-19T21:59:17.507Z` is not between `2018-12-17 00:00 UTC` and `2018-12-26 07:00 UTC` which it absolutely is though. I don't know why `Moment.isBetween` is returning false.

**Comment by beaucollins** [comment]
Here's Firefox showing that it won't show either notice because `Moment.isBetween` is returning false.

image

**Comment by mattwondra** [comment]
Looks like FF and Safari aren't parsing dates in the pattern "2018-12-17 00:00 UTC" as a date. Probably something to do with how `moment` uses the `Date` library under the hood causing issues between browsers. 

Thanks, I'll look into this.

**Comment by beaucollins** [comment]
This fixes it for me

```diff
diff --git a/client/me/help/help-contact/index.jsx b/client/me/help/help-contact/index.jsx
index ce0b9323df..c69d1f9fce 100644
--- a/client/me/help/help-contact/index.jsx
+++ b/client/me/help/help-contact/index.jsx
@@ -530,16 +530,16 @@ class HelpContact extends React.Component {
 						<LiveChatClosureNotice
 							holidayName="Christmas"
 							compact={ compact }
-							displayAt="2018-12-17 00:00 UTC"
-							closesAt="2018-12-24 00:00 UTC"
-							reopensAt="2018-12-26 07:00 UTC"
+							displayAt="2018-12-17T00:00+00"
+							closesAt="2018-12-24T00:00+00"
+							reopensAt="2018-12-26T07:00+00"
 						/>
 						<LiveChatClosureNotice
 							holidayName="New Year's Day"
 							compact={ compact }
-							displayAt="2018-12-26 07:00 UTC"
-							closesAt="2019-01-01 00:00 UTC"
-							reopensAt="2019-01-02 07:00 UTC"
+							displayAt="2018-12-26T07:00+00"
+							closesAt="2019-01-01T00:00+00"
+							reopensAt="2019-01-02T07:00+00"
 						/>
 					</Fragment>
 				) }
```

**Comment by mattwondra** [comment]
I switched to an explicit ISO 8601 format and that works for all browsers (moment's documentation says it checks these formats explicitly).

**Pull request merged**
