### PR TITLE
Checklist: fix typo in "up-to-date"

### LINKED ISSUE #38023: Checklist: fix typo in "up-to-date"
image

> I noticed a wee error in the screenshot just above — “up to date” does not require any dashes between the words

Internal reference:
p8oabR-qW-p2#comment-3595

### PR DESCRIPTION
**Pull request by davidkwan95**
#### Changes proposed in this Pull Request

* Fix typo for up-to-date

#### Testing instructions

*

Fixes #38023

### CODE REVIEW

**Comment by davidkwan95** [comment]
cc @jeherve would you mind taking a look?

Also, would love to contribute to this project. Which labels are indicating that an issue is up for grab? Thanks

**Comment by bluefuton** [comment]
Thanks for your PR @davidkwan95, and great to hear that you're keen to contribute! 

I'd recommend checking out issues labelled with "good first issue":

https://github.com/Automattic/wp-calypso/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22

**Review by bluefuton — APPROVED** [review]
Seems to be some variation on the recommended hyphen usage, but I'd say you're correct on this one. I'll wait for our Editorial team to have the final say.

**Review by jeherve — APPROVED** [review]
This should be good to go, the change was originally suggested by our Editorial team.

Thank you for the contribution!

**Comment by michelleweber** [comment]
I'm pretty sure I was the one who first suggested this change, so I approve this message :)

**Pull request merged**
