### PR TITLE
Rename plans to Personal / Premium / Business / Commerce

### PR DESCRIPTION
**Pull request by niranjan-uma-shankar**
## Proposed Changes

* As per the decision in p58i-hH2-p2, we will revert the plan names to Personal / Premium / Business / Commerce.
* This PR also removes all the experiment related code.

## Why are these changes being made?

* Due to the decision made in p58i-hH2-p2

## Testing Instructions

* First, apply D156184-code and sandbox public-api.wordpress.com
* Verify that in any screen that shows plan names, the new names are visible. Check this in signup flow plan step, `/plans` page, upsells in the Tools section, /themes page, checkout page after adding a plan to cart, and anywhere else you can think of.
* Purchase any plan and verify that the billing emails you receive all mention the new plan name Personal/Premium etc.

### CODE REVIEW

**Comment by chriskmnds** [comment]
I think it looks good. A few parts I confirmed:

- `/start/plans` looks good
- `/plans/:site` looks good
- `/checkout/:site` - looks good
- `/posts/:site` ("post share" when on free plan) - premium upsell looks good
- `/marketing/tools/:site` premium upsell looks good
- `/plugins/:site` business upsell looks good

**Comment by jeyip** [comment]
## Testing
### Requirements

For each of the flows listed below:
- Verified plan names have been changed

Flows:
- [x] /start
- [x] /setup/free
- [x] /setup/newsletter
- [x] /setup/wooexpress
- [x] /start/p2 
- [x] /plans

### Browsers
- [x] Chrome

### Notes

Unrelated to this PR. I'm seeing different font families ( serif and sans serif ) used for the features grid vs the comparison grid

Screenshot 2024-07-29 at 10 48 23 AM

Screenshot 2024-07-29 at 10 48 32 AM

**Review by jeyip — COMMENTED** [review]
Took a look at the code changes. Everything seems generally reasonable to me. 

It's looking like the biggest concern will be making sure we actually find and revert _all_ instances of the new plan name 🙂 I did some cursory searching and didn't see anything obvious, but in my testing above, I spotted some outdated plan names in the help center.

**Review by jeyip — APPROVED** [review]
+1 from me when the help center stuff is fixed

**Comment by oswian** [comment]
Noting a few references to the old plan names:

https://github.com/Automattic/wp-calypso/blob/8716bbd500882f9de90312e1480d158e30e540a3/packages/data-stores/src/plans/types.ts#L26

https://github.com/Automattic/wp-calypso/blob/8716bbd500882f9de90312e1480d158e30e540a3/packages/help-center/src/types.ts#L94

https://github.com/Automattic/wp-calypso/blob/8716bbd500882f9de90312e1480d158e30e540a3/packages/calypso-e2e/src/lib/pages/plans-page.ts#L13

> Purchase any plan and verify that the billing emails you receive all mention the new plan name Personal/Premium etc.

Yes the new plan name was used. Not relevant to this revert (I don't think), however I found the inclusion of the text 'formerly WordPress​.​com Starter' next to every instance of 'Personal' quite repetitive -- seems like added noise with little value for the customer. Perhaps it's a legal requirement?

**Comment by niranjan-uma-shankar** [comment]
Thanks for testing everyone!

> Could you confirm that we're going to coordinate with happiness to have the support docs updated as well?

@jeyip Yes :). Confirming that we'll update the docs soon as all the patches are shipped, dicussed in p2rHU0-25O-p2.

> Noting a few references to the old plan names:

Thanks @oswian. Since those had both old and new plan names, I was a bit unsure if it's safe to remove. On taking a closer look, it looks like it should be safe to remove the old names from the type definition. I'll make that change.

> however I found the inclusion of the text 'formerly WordPress​.​com Starter' next to every instance of 'Personal' quite repetitive -- seems like added noise with little value for the customer. Perhaps it's a legal requirement?

D132629-code has the background on why it was introduced. Maybe there's a way to reduce the repetitiveness, but that will be outside the scope of this effort. If you feel strongly, I would suggest bringing it up with the Payments team.

**Pull request merged**
