### PR TITLE
Framework: Update Gridicons to v2.1.1

### PR DESCRIPTION
**Pull request by jancavan**
Following the recent addition of Zoom in/out icons in https://github.com/Automattic/gridicons/pull/268, this PR updates Gridicons to `v2.1.1`.

Tested locally and the icons show up on Devdocs:

screenshot 2017-12-13 10 47 16

Related: https://github.com/Automattic/gridicons/pull/269

### CODE REVIEW

**Comment by gwwar** [comment]
I'd recommend rebasing with master, and double checking your local node/npm version. The diff in the shrinkwrap file looks too big. Did you generate this using `npm run update-deps`?

**Comment by gwwar** [comment]
We're on Node v8.9.3!

**Comment by jancavan** [comment]
I swear I did it earlier when you had posted the update, no idea why it didn't though 😞  Could it be because I was maybe on a different tab? Anyway, updating sorry!

**Comment by jancavan** [comment]
Closing. Superseded by: https://github.com/Automattic/wp-calypso/pull/20795

**Comment by gwwar** [comment]
No worries!

**Pull request closed without merging**
