### PR TITLE
WooCommerce: Remove disabled store referrers stats

### PR DESCRIPTION
**Pull request by tyxla**
#### Changes proposed in this Pull Request

Since the store in WP.com has been removed (see pbIJXs-Hj-p2), much of the store code was also removed. 

One remaining piece was the store referrers stats section and widgets. They were hidden under a feature flag that was only enabled on development since #21752. It never got to production, and because the feature was sunset, it likely never will. So it's time to clean up that code.

I got to this one while working on #58453. This PR fixes a couple of instances from #58453.

#### Testing instructions

* Verify the removed code is not in use.
* Smoke test `/store/stats/orders/day/:site` where `:site` is a WooCommerce store.
* Verify all tests pass.

### CODE REVIEW

**Comment by tyxla** [comment]
Rebased to fix a conflict. This PR could still use a review 👀

**Comment by tyxla** [comment]
With regards to the recent #60784 I wonder if I could ask folks from @Automattic/explorers to review this one?

**Review by allilevine — APPROVED** [review]
I can verify that the WooCommerce setup flow starting at /woocommerce-installation/< site id > still functions as expected with this removal ✅ 

@tyxla When I visit /store/stats/orders/day/:site I see a store stats page, is that expected?
Screen Shot 2022-02-08 at 10 15 01 AM

**Comment by tyxla** [comment]
Thanks for taking a look @allilevine!

> @tyxla When I visit /store/stats/orders/day/:site I see a store stats page, is that expected? Screen Shot 2022-02-08 at 10 15 01 AM

Totally! We're leaving the store stats page intact because it still can be used for WooCommerce stores. We're only removing the store referrers stats that are disabled throughout the environments.

**Pull request merged**
