### PR TITLE
Framework: Rework how we deal with failed chunk loads

### PR DESCRIPTION
**Pull request by blowery**
Today, when a chunk fails to load, especially a chunk loaded via `asyncRequire` set, the only indication is a console error, "Cannot read property 'call' of undefined" in the manifest. This happens more than one might think; any time we deploy code that changes a chunk hash, any clients that attempt to load the previous chunk hash will fail with a console error.

We used to have a mechanism to alert the user if a chunk load failed (see `client/layout/error.jsx`), but since we switched to requiring many chunks to load a given section, it stopped working. An attempt was made to fix it in e214f01f44121e5e0a01548f489fa362c007226e, but it appears that fix either never worked or has since stopped working.

We have a bit of a chicken-and-the-egg problem with that solution. It'll work if it has successfully loaded, but we can't really know if it's successfully loaded from here. 

An alternative, proposed here, is to try to reload the failed chunk once, and then reload the entire app if that fails, all contained within the loader itself. This has the advantage of being self-contained and not requiring any knowledge of what parts of the app are properly spun up and operating.

The downside is that it's a pretty heavy hammer.

Thoughts?

### CODE REVIEW

**Comment by dmsnell** [comment]
Not my area of expertise @blowery but that does indeed sound like a "heavy hammer"

would it be conceptually hard to create an error component that would display in the event of a failure to load some section? maybe after the retry instead of entirely reloading Calypso we could replace the missing section with a panel that says something like "we were unable to load this part of the app, please try again later"

my worry is that if after attempting to reload the section a refresh of Calypso won't solve the problem and we'll just cycle on that error

**Comment by psealock** [comment]
>### Chunk loading failures
>1. Load Calypso as normal
>2. Go offline (I use Chrome's devtools to do this)

Instead of seeing the "offline" notification, the whole app reloads and inevitably fails. Simply hovering over "My Sites" triggers a request. As someone currently using spotty wifi, it seems to me the hammer is indeed too big in this scenario.

screen shot 2017-04-18 at 7 58 22 pm

Can the service worker detect offline status and avoid the full app refresh `/?retry=1`?

@blowery, I'm happy to further test the cases you mentioned.

**Comment by blowery** [comment]
@psealock I don't think the "offline" notification is currently released to production and we don't expect to work at all when offline. Spotty wifi is indeed an issue..

The bigger problem here is that the chunk loader can't really know what _has_ successfully loaded and executed. The only reliable hammer it has is the big one.

**Comment by blowery** [comment]
Had a think on this. 

What we need is a little framework agnostic channel between the loader and react / redux. Maybe something like what GA uses, a thing that looks like an array that turns into an eventbus once the framework loads.. So the loader could still do the retry to load a chunk, but if the retry fails a few times, then we can do:

```
var loaderErrors = global.calypsoLoaderErrors || [];
loaderErrors.push( { error } );
```

the framework would peek at global.calypsoLoaderErrors and turn those into notices. It would also replace global.calypsoLoaderErrors with a new object that has a `push` method, which would synchronously fire a notice.

**Comment by blowery** [comment]
This gets a little interesting since we don't expose the redux store or it's dispatcher globally. It's available from inside a page context, but unexposed for general purpose handlers. Might need to address that first.

**Comment by mtias** [comment]
@blowery would @gwwar's lib middleware be helpful here? https://github.com/Automattic/wp-calypso/tree/master/client/state/lib

**Comment by blowery** [comment]
@mtias I don't think so, but maybe I'm missing something. That seems like a side-effect library you invoke by dispatching redux actions. The issue here is that we don't have access to the redux dispatcher to do the dispatch.

**Comment by alisterscott** [comment]
Closing as this PR is stale - please reopen if necessary

**Pull request closed without merging**
