### PR TITLE
Notifications: Settings page components update

### PR DESCRIPTION
**Pull request by rodrigoi**
In order to improve the user experience of the page, specifically for users with a large number of blogs, a search bar has been added.

foldable card

Also, some ad-hoc components developed for this page have been replaced with Calypso's standard components.

Depdens on #2073

### CODE REVIEW

**Comment by drw158** [comment]
Nice. I think the upgrades are great.

The main drawback here is that the whole card is not clickable now, you have to click the arrow. I think it would be worth investigating why that's not an option for the component.

What happens if the user only has one site? The search bar wouldn't be needed, and I think we could expand the single card by default.

I have a few tweaks that might need to be a separate PR:

- compact select element for the mobile select
- we need to come up with a better name for Timeline

**Comment by mtias** [comment]
> What happens if the user only has one site?

As a reference, for site-pickers if you have more than 6 sites we don't show search.

**Comment by rodrigoi** [comment]
The single site view is fixed now, and updated the gidicons. Will update the select later.

notifications_single_user

@mtias is that limit used on other lists, or is it a random number?

**Comment by mtias** [comment]
@rodrigoi it's a limit in the UI components that work with `site-selector`, it was set based on the fact less than six sites are always visible in one screen for those components. I think it'd be ok to mimic that behaviour and only show search if site count is greater than 6. Note that if the user has hidden sites search should be shown too.

**Comment by drw158** [comment]
Changes look great, now I'm only concerned with

> The main drawback here is that the whole card is not clickable now, you have to click the arrow. I think it would be worth investigating why that's not an option for the component.

**Comment by apeatling** [comment]
@rodrigoi These PRs are lingering for a long time, can you follow up on them sooner?

**Comment by mtias** [comment]
@rodrigoi what's the status of this one?

**Comment by rodrigoi** [comment]
@mtias bringing this back so I can start "reduxifyng" this section. Would you mind taking a quick look at the code? Thanks!

**Comment by gwwar** [comment]
@rodrigoi is this PR still active?

**Comment by rodrigoi** [comment]
Will revisit when reduxification is done. Closing.

**Pull request closed without merging**
