### PR TITLE
i18n: Allow translations on the server

### PR DESCRIPTION
**Pull request by seear**
Addresses #186

Experimental for now. Excuse the branch name.

Components rendered on the server will need the [i18n mixin](https://github.com/Automattic/wp-calypso/tree/master/client/lib/mixins/i18n) to be initialized and injected.

This PR is exploring the approach of having the language files checked out to the container. Testing requires an SVN checkout of https://wpcom-i18n.svn.automattic.com/calypso/ to `server/lang`

Next steps:
- [ ] Determine the locale to use for the logged-out /design route from the `accept-language` request header
- [ ] do the `i18n.setLocale()` accordingly
- [ ] Add the SVN checkout to the Dockerfile

### CODE REVIEW

**Comment by ockham** [comment]
> use something like [`request-context`](https://www.npmjs.com/package/request-context) for per-request i18n state

Can't we use Redux instead? (I might be missing something here, and haven't really looked into what information the `i18n` mixin state holds other than the current locale.)

**Comment by ockham** [comment]
(Thinking that with Redux, we might be able to use the same `i18n` mixing both client- and server-side.)

**Comment by ehg** [comment]
> For now, maybe cache the requested files for as long as the node instance is running

I think if we're happy with strings not being updated until a deploy for now, then we should just `svn co` the locale files in the Dockerfile.

**Comment by ehg** [comment]
Related: #186

**Comment by seear** [comment]
> Can't we use Redux instead?

Possibly. The problem I want to solve is another request setting a different locale while any async stuff is happening in a request. But I'm thinking now that a better solution would be to make sure any locale setting is always done after any async stuff (i.e. right before the `renderToString()`).

**Comment by lancewillett** [comment]
Closing for now since no activity in a few months — feel free to re-open and continue discussing when the time allows or interest picks back up.

**Pull request closed without merging**
