### PR TITLE
Reader Search: remove tagline on blank search and add the Drake

### PR DESCRIPTION
**Pull request by gibrown**
Feels like the blank search page needed something and since we aren't adding recos, the Drake?

(Unless we have a giraffe around?)

Test live: https://calypso.live/read/search?branch=add/reader-search-remove-tagline

### CODE REVIEW

**Comment by blowery** [comment]
I think we've been trying to avoid drake for anything that's not an error? I think? Maybe?

It does feel pretty blank when blank. @fraying any thoughts on a short term thing to hold that space while we work on getting recommended posts in there?

**Comment by blowery** [comment]
@gibrown also could you please add a before / after screenshot to this pr?

**Comment by fraying** [comment]
Yeah, I was just saying in Slack: Dunno about Drake. I strongly associate him with error states, so this feels like something went wrong.

**Comment by fraying** [comment]
Also note that "Search" should be removed and the placeholder text should be "Search billions of WordPress.com sites..."

(Should I post that as a separate Issue?)

**Comment by blowery** [comment]
@fraying just need to rebase this one to pick that up. It was already done in a different PR.

**Comment by blowery** [comment]
went back to a blank blank slate

**Pull request merged**
