### PR TITLE
A4A: add stats upsell for non jetpack sites

### PR DESCRIPTION
**Pull request by andrii-lysenko**
Related to https://github.com/Automattic/automattic-for-agencies-dev/issues/471

## Proposed Changes

Adding possibility to Add Jetpack stats when we don't have jetpack plugin installed.
This change will appear on Sites Dashboard for non-Atomic and sites with no Jetpack plugin.

Feel free to advice on style update and/or reuse of existing components. I couldn't use `<JetpackProductCard />` because of many changes required.

https://github.com/Automattic/wp-calypso/assets/60262784/6c1c4268-5911-46fe-b212-7fa97f885fba

## Testing Instructions

- Have a site that is connected through Jetpack and at least one that only connected via A4A plugin
- Using live link below, navigate to `/sites` page and check stats column.
- You should see `+Add` button for sites without Jetpack plugin.
- Click the button and check the upsell.

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Comment by jeffgolenski** [comment]
Nice! Thanks @andrii-lysenko! Just a couple of requests:

- [ ] Can we eliminate this awkward breakpoint and switch to the mobile view around this size?
CleanShot 2024-06-11 at 08 35 44

On mobile:
- [ ] Stack the CTA buttons
- [ ] Eliminate the side scrolling in this area
- [ ] Center the image
- [ ] Remove large gap at the top of the card. Please make it the same distance as the side padding.

CleanShot 2024-06-11 at 08 35 30


CleanShot 2024-06-11 at 08 35 16

**Comment by andrii-lysenko** [comment]
@jeffgolenski Thanks for the review. I've addressed some smaller mobile issues, but `Can we eliminate this awkward breakpoint and switch to the mobile view around this size?` is a bit harder to implement. 
Should we address it separately, or we would want to deliver this together?

**Comment by jeffgolenski** [comment]
> is a bit harder to implement.
Should we address it separately, or we would want to deliver this together?

@andrii-lysenko No worries my friend, we can work on that later, since we have bigger priorities this week. 

I do have a couple more small edits (I'm sorry!)

CleanShot 2024-06-12 at 16 18 55

- [ ] Change text above the CTAs to read: 

> Commercial sites require a paid plan, which you can purchase at a discount within the Marketplace.

Can "the Marketplace" link to https://agencies.automattic.com/marketplace/products and automatically load a search for "stats"?

If that's a big ask, bringing them to the marketplace only is fine. 

CleanShot 2024-06-12 at 16 21 07@2x


- [ ] Update "Learn More" CTA to say "Learn more" (lowercase more)
- [ ] Update text color of secondary CTA hover from green to our standard blue. (double checking with @madebynoam & @keoshi on the hover color. I just know it shouldn't be green.) 

CleanShot 2024-06-12 at 16 22 48

- [ ] Text should be flush with the red line in the below screenshot and shouldn't flow below the check marks

CleanShot 2024-06-12 at 16 25 22

**Review by jeffgolenski — DISMISSED** [review]
See conversation for additional edits.

**Comment by andrii-lysenko** [comment]
Thanks @jeffgolenski. We are pushing now to finish referral project, I'll get back to this one right after I deploy some my tasks there.

**Comment by keoshi** [comment]
> Update text color of secondary CTA hover from green to our standard blue. (double checking with @madebynoam & @keoshi on the hover color. I just know it shouldn't be green.)

The color should be Studio Automattic 70, also know as `--color-primary-70` or `--color-primary-dark`:

https://github.com/Automattic/wp-calypso/blob/8f0d0e02f98510d5f94105f2de58386bbb94859b/client/a8c-for-agencies/style.scss#L165

**Comment by andrii-lysenko** [comment]
@jeffgolenski @keoshi I've tried to address all comments above with the `search` query included in the `marketplace` link. Please let me know if I missed any. 
On a side note, this CTA is still bigger than others, so when I open it, there's a possibility to scroll and button are at the very bottom of the page. But don't know if it's the issue.

Screenshot 2024-06-14 at 5 45 52 PM

**Comment by andrii-lysenko** [comment]
@jeffgolenski @keoshi by any chance you have some time to re-visit this?

**Review by madebynoam — APPROVED** [review]
@andrii-lysenko lgtm, thanks for all the changes. What you have now is good to ship.
We can follow up on any items that come up in a separate issue.

**Review by rcanepa — APPROVED** [review]
LGTM.

Code changes look reasonable and safe (I don't see how they could introduce a regression). 

Everything worked as described, and the UX was clearly improved.

Feel free to ship this. Thank you, @andrii-lysenko !

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/16128212

Some locales (Hebrew, Japanese) have been temporarily machine-translated due to translator availability. All other translations are usually ready within a few days. Untranslated and machine-translated strings will be sent for translation next Monday and are expected to be completed by the following Friday.

Hi @andrii-lysenko, could you please edit the description of this PR and add a screenshot for our translators? Ideally it'd include all of the following strings:
- `Track your site visits and other valuable insights, so you can drive more traffic to your website.`
- `Explore real‑time data on visitors, likes, and comments.`
- `And so much more.`
- `Commercial sites require a paid plan, which you can purchase at a discount within {{a}}the marketplace{{/a}}.`
- `Jetpack Stats Logo`

Thank you in advance!

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/16128212).

**Pull request merged**
