### PR TITLE
Registrationless checkout: Show the help icon in the checkout page

### PR DESCRIPTION
**Pull request by niranjan-uma-shankar**
#### Changes proposed in this Pull Request

**This is one among a set of stacked PRs that implements userless checkout A/B test. For more reading on the userless
checkout project, read pau2Xa-1hW-p2.**

* The inline help icon will be loaded but kept hidden beneath the Google Recaptcha logo. This way, clicking the "Read more about plans and purchases" link in the Purchase details section will open the help popover without displaying the floating help icon to the user.

#### Testing instructions

* Go to /start/onboarding-new and select a paid plan to open the checkout page.
* Verify that the Google Recaptcha logo is on the bottom right and the floating help icon is not visible.
* Click `Questions? Read more about plans and purchases` from the order summary and verify that the inline help popover opens.

uc

* Confirm mobile view looks okay

Screenshot 2020-07-30 at 7 57 07 PM

### CODE REVIEW

**Comment by fditrapani** [comment]
From a design perspective, I think we can do away with the floating help because it's available in the summary too:

image

What do you think?

**Comment by niranjan-uma-shankar** [comment]
> From a design perspective, I think we can do away with the floating help because it's available in the summary too

@fditrapani I didn't catch that, sorry. Where is the help section in summary?

Also, we link to the help icon in the "Purchase details" section - "Read more about plans and purchases" currently opens the inline help popover. Should we remove this link?

Screenshot 2020-07-29 at 11 56 35 PM

**Comment by fditrapani** [comment]
> Also, we link to the help icon in the "Purchase details" section - "Read more about plans and purchases" currently opens the inline help popover. Should we remove this link?

Yeah, that's the help I was referring to. We can keep that one and remove the floating one to make space for the captcha.

**Comment by niranjan-uma-shankar** [comment]
@fditrapani I've implemented your suggestion and updated the PR description with a gif of how it looks. Nice suggestion, thanks!

**Comment by fditrapani** [comment]
Awesome. Thanks for the updates @niranjan-uma-shankar!

**Pull request merged**
