### PR TITLE
Framework: Add an nvmrc to auto switch to the correct version

### PR DESCRIPTION
**Pull request by blowery**
This will help nvm to automatically switch to the correct version of node. To test, install nvm and switch into the working directory. `nvm use` should autoswitch to 5.10.1.

To get auto switching, users would also have to install avn or a custom shell integration piece. See https://github.com/creationix/nvm#deeper-shell-integration

### CODE REVIEW

**Comment by folletto** [comment]
Tested from GitHub's app → Open in Terminal: works.

screen shot 2016-05-05 at 14 45 32

**Comment by gwwar** [comment]
Should we update `node-check-version` to try to switch to the correct version if it detects nvm or n? We're already parsing package.json for engine versions in that script.

**Comment by blowery** [comment]
> Should we update node-check-version to try to switch to the correct version if it detects nvm or n? 

I'm not sure. I feel like it should be up to the dev to determine if they want auto switching enabled or not... maybe? Not a strong opinion, but it feels odd to do it. Plus it could conflict with any auto switching stuff a dev already has enabled.

**Comment by gwwar** [comment]
It feels like there isn't much harm in adding an .nvmrc config. The only danger is that it might out of sync with the engine version in package.json, but folks should see a warning in startup when that happens.

🚢

**Pull request merged**
