### PR TITLE
Themes: Remove siteId prop from main.jsx

### PR DESCRIPTION
**Pull request by ockham**
Derive via `this.props.selectedSite.ID` instead.

### CODE REVIEW

**Comment by seear** [comment]
Be sure to test by clearing local storage before loading (`localStorage.clear()` in the console). Previous attempts to stop using the site ID from the route have failed because `sites` loaded to slowly causing the layout to change.

This seems fine to me though, so maybe the site ID is loading much quicker than when using `sites`.

**Comment by seear** [comment]
Rebased from `master`

**Comment by seear** [comment]
>  Previous attempts to stop using the site ID from the route have failed because sites loaded to slowly causing the layout to change.

Since the rebase I can reproduce the changing layout:
1) go to http://calypso.localhost:3000/design/{site}
2) in console: `localStorage.clear()`
3) refresh page
Note that on first load, the _current theme_ bar at the top is missing from the layout, and a re-layout occurs once the site data has loaded.

I vote to stick with the site ID from the route, which is available instantly.

**Comment by ehg** [comment]
AFAICR we decided not to do this? Closing.

**Pull request closed without merging**
