### PR TITLE
Do not translate the concierge forms and add more visible notice

### PR DESCRIPTION
**Pull request by unDemian**
## Summary
This PR disables the translation of concierge forms because we are only accepting english speakers. Also adds a more visible notice that the session will be held in english.

Before for `es` customers: https://cloudup.com/cCSfyghGCSc
After for `es` customers: https://cloudup.com/c4AhWlstlEK

More context: 587-hg-gh

## Testing
1. Make sure booking, rescheduling and cancelling a session works & looks as expected
2. Change your language
3. Make sure concierge forms are shown in english and there is a notice on the first step

### CODE REVIEW

**Comment by lamosty** [comment]
When testing with a non-en language, I see mixed strings on the booking day selection page:

screen shot on 2018-03-02 at 15 37 33

How can I reschedule or cancel a session? When I navigate to `http://calypso.localhost:3000/me/concierge/<my-business-site>`, I always see the form to schedule a session only and no list of my already scheduled sessions.

Lastly, I don't really like the fact that we are removing all the translations/localizations code. What if we decide to support concierge chats in the future in different language than English? We'll have to add the code back. It would be nice if we could specify some option or a flag on a per-file basis to `i18n-calypso` that we don't want to translate right now. /cc @akirk

**Comment by akirk** [comment]
> It would be nice if we could specify some option or a flag on a per-file basis to i18n-calypso that we don't want to translate right now.

This is up to you to decide if it's too much effort to add the translate calls back in. But what you say is correct, you can ignore files or directory using an exclamation mark here: https://github.com/Automattic/wp-calypso/blob/master/package.json#L233

**Comment by lamosty** [comment]
> This is up to you to decide if it's too much effort to add the translate calls back in. But what you say is correct, you can ignore files or directory using an exclamation mark here: https://github.com/Automattic/wp-calypso/blob/master/package.json#L233

Hmm, I see. Thanks for the pointer @akirk. I think we would have to make that a separate file or at least a variable since there are like 12 files; would be too much for that one line. :D

**Comment by unDemian** [comment]
Great catch @lamosty , I updated the code so that moment uses the default locale. I agree and don't really like this approach of removing the localization code especially giving the fact that we have re-usable components that are localized.

There was a workaround for moment but components like `Timezone` or `HeaderCake` will be translated resulting in weird inconsistencies like https://cloudup.com/c0_JjDVgRvA where the title is in English but the back link is translated. cc: @mattwondra

**Comment by unDemian** [comment]
After some feedback on 587-gh-hg I'll close this in favor of https://github.com/Automattic/wp-calypso/pull/23073

**Pull request closed without merging**
