### PR TITLE
Package "page-pattern-modal": publishing to npm

### PR DESCRIPTION
**Pull request by miksansegundo**
## Proposed Changes

Changes to publish [@automattic/page-pattern-modal](https://www.npmjs.com/package/@automattic/page-pattern-modal)
* Update version to `1.1.4`
* Fix dependency error: "Could not find a declaration file for module '@automattic/calypso-build'"
* Fix "Command not found: copy-assets"

## Why are these changes being made?

[ETK Migration: Start Page Templates Feature](https://github.com/Automattic/dotcom-forge/issues/8242) will reuse the package from `jetpack-mu-wpcom`.

## Testing Instructions

* N/A

## Pre-merge Checklist

- [x] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [x] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Review by okmttdhr — COMMENTED** [review]
It seems like we're not using `@automattic/onboarding` at all in `./packages/page-pattern-modal` (CMIIW🙈), so I think we can remove `"@automattic/onboarding": "workspace:^",` from `dependencies`, too: https://github.com/Automattic/wp-calypso/blob/fix/publishing-page-pattern-modal-to-npm/packages/page-pattern-modal/package.json#L30

With this, I don't think we need changes under `packages/onboarding` in this PR (the change itself looks good for the package's independence, though!).

**Comment by miksansegundo** [comment]
This is ready for another review, merge, and then I'll tag the version with `git tag "@automattic/page-pattern-modal@1.1.2"`

**Review by okmttdhr — APPROVED** [review]
👍

**Review by fushar — APPROVED** [review]
I don't see any obvious error in this PR, so I think we can just merge, publish, and iterate later if we find any problem down the road.

This shouldn't break the existing feature in ETK, right?

**Comment by okmttdhr** [comment]
> This shouldn't break the existing feature in ETK, right?

I think so because;

- packages are used via `workspace:^` in Calypso repo (so the "version" matters only when it's used via npm package)
- We're not removing `references` from `onboarding` but adding it so we should not lose anything in build output 
- Tests are passing

**Comment by miksansegundo** [comment]
>This shouldn't break the existing feature in ETK, right?
Right because when running `install-plugin.sh etk fix/publishing-page-pattern-modal-to-npm` in my sandbox, the message is "the given branch does not actually modify the plugin"

Anyways, I'll test it after deploying

**Pull request merged**
