### PR TITLE
Tooling/Building CalypsO: Bump `sharp` dependency version to 0.28 to allow building of Calypso on M1 macs

### PR DESCRIPTION
**Pull request by bisko**
The 0.25.3 version of `sharp` seems to require `libvips` that has no build for M1 macs. This prevents Calypso from completing the `yarn install` step and subsequently is unable to start because of that.

Seems that version 0.28 of `sharp` solves this - https://github.com/lovell/sharp/issues/2460

This only affects native M1 flows, where the terminal/yarn/homebrew is not being ran through Rosetta.

#### Changes proposed in this Pull Request

* Bump `sharp` dependency version to 0.28

#### Testing instructions

* Apply PR
* Build Calypso
* Make sure it builds successfully

### CODE REVIEW

**Comment by worldomonation** [comment]
Hah, it breaks all tests for some reason. I will take a look as to why this is later.

**Comment by worldomonation** [comment]
Tried generating a new `yarn.lock` file.

**Comment by worldomonation** [comment]
There we go, it works.

**Review by worldomonation — APPROVED** [review]
Approved from me since I fixed up the PR, but I'll also wait for another approval.

**Review by noahtallen — APPROVED** [review]
Looks like `sharp` is only used in a node script sometimes, so should be low impact! I think we can trust CI on this one :)

**Pull request merged**
