### PR TITLE
Framework: Refactor away from _.noop()

### PR DESCRIPTION
**Pull request by tyxla**
#### Changes proposed in this Pull Request

Lodash's `noop` is essentially an empty function. This PR replaces all the usage of `noop` with an empty arrow function.

If you want to find out why we're moving away from Lodash, see https://github.com/Automattic/wp-calypso/pull/50368 and p4TIVU-9Bf-p2.

#### Testing instructions

* Verify Calypso builds.
* Verify all tests pass.

#### Notes
Lint errors are expected. Just make sure we're not introducing new ones.

### CODE REVIEW

**Comment by tyxla** [comment]
Would be cool if I can get an expedited review of this one. It tends to get stale quickly 😅

**Review by lynnbgriffith — APPROVED** [review]
👍 LGTM

**Comment by jsnajdr** [comment]
When passing `() => {}` as a React component prop, this change can cause deoptimization of `PureComponent`s and their friends (`React.memo`, `connect()`, ...). I'm unhappy about this 🙁

**Comment by tyxla** [comment]
> When passing `() => {}` as a React component prop, this change can cause deoptimization of `PureComponent`s and their friends (`React.memo`, `connect()`, ...). I'm unhappy about this 🙁

Good point. I think it is a worthy trade-off, though. Many of those instances would end up passing a `noop` as a default when they could have gone with a `null` as a default and execute it later only if it's not `null`. In those terms, I think the `noop` was overused, and removing it is a first step into improving that.

Would you consider this a trade-off we can live with? Can you point me to a particular deoptimization that really feels like one and needs to be addressed? I could follow-up on those.

**Comment by jsnajdr** [comment]
> Many of those instances would end up passing a `noop` as a default when they could have gone with a `null` as a default

But `noop` is much more ergonomic. The code can call `props.onSomething()` and be sure that the target is always a function. It's true however that optional chaining now gives us a very convenient `props.onSomething?.()` helper for that.

Parameter and prop types are also less noisy with `noop` default: no `Function | undefined` everywhere.

> Would you consider this a trade-off we can live with? Can you point me to a particular deoptimization that really feels like one and needs to be addressed?

Not really, but I want to point out that there is a slight chance that this change could break some component's behavior. Some fragile components and their lifecycle methods rely on the fact that they are rerendered only at specific times, e.g., when a specific prop changes. Now we're introducing extra rerenders due to different `noop` instances. And there are new calls to `componentDidUpdate` that didn't occur before.

I've seen things like this in the importers code which relies on React lifecycles to so some very subtle changes in the importer flow.

**Comment by tyxla** [comment]
> It's true however that optional chaining now gives us a very convenient props.onSomething?.() helper for that.

💯  Exactly. That kind of tools of the language are what I'd like to promote by deprecating Lodash.

> I've seen things like this in the importers code which relies on React lifecycles to so some very subtle changes in the importer flow.

I understand. It's a shame if our components are really so fragile. In that case the problem wouldn't be the fact we're using a different `noop` function - the problem is much bigger than that, and likely would occur if we do any other refactor on such a component.

Anyway, I still think this is a worthy trade-off. If we break something, we can fix it later, and that would actually be improving something that was already being fragile. 

That being said, what do you recommend? Do you suggest just closing this, or?

**Comment by scinos** [comment]
> > It's true however that optional chaining now gives us a very convenient props.onSomething?.() helper for that.

> 💯 Exactly. That kind of tools of the language are what I'd like to promote by deprecating Lodash.

For what is worth, we can't use `props.onSomething?.()` _everywhere_ just yet: for example, Node scripts that are not transpiled are run with Node 12, which doesn't support optional chaining.

**Comment by tyxla** [comment]
> For what is worth, we can't use `props.onSomething?.()` _everywhere_ just yet: for example, Node scripts that are not transpiled are run with Node 12, which doesn't support optional chaining.

True. What a good reason to consider upgrading to Node 14 soon 🙈 .

**Comment by sirbrillig** [comment]
FWIW, you could define small `noop` functions per-file (or export and share) and they will prevent breaking pure component comparison. As long as the function is defined at the file-level, it will never change, unlike an inline `() => {}`. It also would mean a smaller changeset for some of these files because you could keep the `noop` and just replace the import with:

```
const noop = () => {}
```

**Comment by noahtallen** [comment]
> Many of those instances would end up passing a noop as a default when they could have gone with a null as a default and execute it later only if it's not null. In those terms, I think the noop was overused, and removing it is a first step into improving that.

If this is the case, should the prop be entirely optional (and therefore `undefined` in the component)?

> this change can cause deoptimization

It does seem like this change would deoptimize _every_ single one of these components. I also don't like this tradeoff, since I'd expect many of those optimizations to be there "on purpose" (though in some cases, I'm sure optimizations were added without really testing if it was an improvement). 

Idea:
- We introduce our own `noop` to JS utils which is just an empty arrow function.
- We instantly deprecate this function, and suggest people fix the root component to handle undefined callback props.
- Over time, we migrate more of these components to allow undefined callback props.

It's a bit weird, but if a bigger short-term priority is removing lodash, maybe it makes sense to add our own `noop` in the short term, while aiming to deprecate it entirely in the long term.

**Comment by jsnajdr** [comment]
> That being said, what do you recommend?

My favorite would be a per-file `noop` as @sirbrillig suggests. Followed by removing it from the components by making the props optional and checking the calls. `material-ui`, for example, uses this pattern consistently:
```js
interface ButtonProps {
  onChange?: ( event ) => void
}

function Button( { onChange } : ButtonProps ) {
  if ( onChange ) {
    onChange( event );
  }
}
```

> for example, Node scripts that are not transpiled are run with Node 12, which doesn't support optional chaining.

Untranspiled Node build scripts are quite rare, and most likely mutually exclusive with files that contain React code. This PR doesn't touch any of the build files. I don't expect any issues here.

**Comment by tyxla** [comment]
Thanks for chiming in, everyone. I'll give a chance to another approach that doesn't cause any side effects.

**Comment by tyxla** [comment]
I've done another take on this where we're declaring per-file `noop`s: #50755

**Pull request closed without merging**
