### PR TITLE
Stats: Release new date filtering to production

### PR DESCRIPTION
**Pull request by dognose24**
Related to https://github.com/Automattic/red-team/issues/274

## Proposed Changes

* Enable the feature flag `stats/new-date-filtering` for all environments.

## Why are these changes being made?

* Release the date filtering project by flipping the feature flag.

## Testing Instructions

* Spin this change up with the Calypso Live branch.
* Navigate to Stats > Traffic page for any site.
* Ensure the Traffic page applies the new design and date filtering functionalities.

截圖 2024-12-04 晚上10 20 58

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
    - [ ] For UI changes, have we tested the change in various languages (for example, ES, PT, FR, or DE)? The length of text and words vary significantly between languages. 
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Comment by grbicsanja** [comment]
In the 'Yesterday' view, I'm unable to click on the Visitors/ Likes/ Comments tabs, see video:


https://github.com/user-attachments/assets/d18fb7ae-4172-464c-8472-068a63504779

**Comment by kangzj** [comment]
> In the 'Yesterday' view, I'm unable to click on the Visitors/ Likes/ Comments tabs, see video:

@grbicsanja good catch! this is expected atm, because we don't have data to show for the chart. We removed the hovering effect if that's the case, which @ederrengifo suggested.

**Comment by grbicsanja** [comment]
> > In the 'Yesterday' view, I'm unable to click on the Visitors/ Likes/ Comments tabs, see video:
> 
> @grbicsanja good catch! this is expected atm, because we don't have single day data to show for the chart. We removed the hovering effect if that's the case, which @ederrengifo suggested.

Thanks @kangzj! Can we instead use the empty state that we usually show for other use cases? Is there a specific reason this view wouldn't work here? 
Screenshot 2024-12-04 at 13 44 14

**Comment by ederrengifo** [comment]
I initially suggested to communicate that the chart is unable within the tooltip, but it seems an empty state could do a be better job since it's a pattern we already use when there is no data to show. We could need to adjust the message though @kangzj cc @grbicsanja

**Comment by grbicsanja** [comment]
Here's the adjusted message:

**No hourly data available**
Try selecting a different time frame.

This will be the second use case. Visitors, comments, and likes were recorded that day, but hourly data is unavailable.

The first use case is an actual empty state where no data was recorded.
.

**Review by ederrengifo — DISMISSED** [review]
I found a couple of issues: 
- When I first load a site, I see lines go beyond the container. It fixes after refreshing the page. Could be something local?
Screenshot 2024-12-06 at 16 14 18

- I notice we are still showing the visitors filter when selecting Today but visitors are not available in the graph. Should we just hide it for that date range?
Screenshot 2024-12-06 at 16 15 51

**Review by kangzj — APPROVED** [review]
Let's do this 🕺

**Comment by kangzj** [comment]
Thanks for the final design review @ederrengifo and the improvements pointed out 👍 

>     I notice we are still showing the visitors filter when selecting Today but visitors are not available in the graph. Should we just hide it for that date range?

Addressed

> 
    When I first load a site, I see lines go beyond the container. It fixes after refreshing the page. Could be something local?

This is due to some interim changes detecting whether a site is internal or not, and will not happen on production.

**Pull request merged**
