### PR TITLE
Logmein etk module

### LINKED ISSUE #54108: Add logmein usage on links rendered in the editor
**Task Details**
#53443 introduced the logmein function but its `attachLogmein` method only works on links rendered by calypso, inside etk there is no such attachment triggered.

I suspect we need to move [this lib](https://github.com/Automattic/wp-calypso/tree/trunk/client/lib/logmein) into a package and consume it by ETK but there might be a better way to do this.

**Related to**
#53443

### PR DESCRIPTION
**Pull request by lsl**
#### Changes proposed in this Pull Request

Replicate logmein from #53443 for ETK

#### Testing instructions

Either 

- Install on sandbox without building:

```
install-plugin.sh notifications add/etk-logmein
```

Or locally,

- Build & watch etk:
```
cd wp-calypso/apps/editing-toolkit
yarn run dev
```
- Sync changes to sandbox:
```
cd wp-calypso/apps/editing-toolkit
yarn run wpcom-sync
```
- Add a sandbox filter to enable the module: `add_filter( 'wpcom_logmein_enable_etk', '__return_true', 11 );`
- Sandbox a simple site with a mapped domain. (Remember to sandbox the unmapped url for GB/etk).
- Open the editor for the site
- Click, right click, ctrl click, middle click, and touch test the permalink in the sidebar (switching from page to block settings and back re-renders the link for a new test, don't need to page reload)
- Also test the snackbar "View Post" that shows up when you save a post as this required a workaround to get working.

Repeat the tests for non-mapped simple sites, and atomic sites (use an ephemeral site and upload the built plugin), both non-mapped simple sites and atomic sites shouldn't have the logmein param applied to links.

Test support page links as well as site links, support page links should not receive logmein params.

Screenshot 2021-07-28 at 20-41-44 Edit Post ‹ c3po - Simple Site - Mapped — WordPress

Fixes #54108

### CODE REVIEW

**Review by p-jackson — COMMENTED** [review]
I haven't tested all the different click methods, but I've tested on simple sites, mapped and unmapped domain. It's working well 👍

It's a bit tricky to test on Atomic because I'd need to create a plugin just to add the hook. Maybe it should be possible to test with just by setting an option or a constant? I did load the built plugin on Atomic to make sure it loads successfully.

It did make me think that perhaps there should eventually be code that prevents the script from being enqueued on Atomic, if it's not going to support the `logmein` param. Maybe you were thinking of leaving the filter there long term, and having a wpcom on wpcom so it only ever worked on simple sites?

**Comment by lsl** [comment]
Thanks! eventually atomic should support logmein so I was hoping to avoid having to make another change to ETK but looks like we probably will need to make a small mod to enable it regardless. At this point the flag is just so its easy to deploy a small change to disable it in production without having to deploy etk everywhere.

**Comment by creativecoder** [comment]
Note that ~38% of Atomic sites don't have ETK active. Have you considered putting this in Jetpack? That's where [WP.com SSO lives](https://github.com/Automattic/jetpack/blob/e10f3fb44622060b38bd1b23acad6582e88cb97f/projects/plugins/jetpack/modules/sso.php); this seems related so it could be a good fit.

**Comment by lsl** [comment]
I wasn't aware of that! good to know. Jetpack is 100% a better place for this in that case. Something similar also needs to be done for wp-admin but I was planning to do that via the unified nav.

**Comment by lsl** [comment]
^

**Pull request closed without merging**
