### PR TITLE
Signup: Add plan specific signup flows for 2Y plans

### PR DESCRIPTION
**Pull request by aneeshd16**
Fixes Automattic/martech#1635

## Proposed Changes

* Adds signup flows for the 2Y Personal, Premium, Business and eCommerce plans. These are similar to the annual plan-specific flows (https://wordpress.com/start/personal)
* The tailored e-commerce flow accepts a `recur` query param which maps to the appropriate eCommerce plan. This PR adds support for 2Y and 3Y recur types. The 3Y recur type was out of scope for this task, but I have added it here since the effort required was low.

### Signup Flows
Test these flows by following these URLs and verifying that:
1. The plans step is not shown.
2. The monthly plan is automatically added to the cart at the end of the flow.
3. (Optional) You are able to complete the purchase.

* /start/personal-2y
* /start/premium-2y
* /start/business-2y
* /start/ecommerce-2y

### Tailored eCommerce Flow
* Go to `/setup/ecommerce?recur=2Y` and confirm that the 2Y plan is in the cart when you reach the checkout page.
* Go to `/setup/ecommerce?recur=3Y` and confirm that the 3Y plan is in the cart when you reach the checkout page.

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

**Review by chriskmnds — COMMENTED** [review]
Thanks, @aneeshd16! TIL these were even a thing 😬 

I tested the flows outlined and it works as described for the 2Y ones at least. I noticed one or two things that _may_ need addressing:

> Go to /setup/ecommerce?recur=3Y and confirm that the 3Y plan is in the cart when you reach the checkout page.

This isn't the case for me 🤔  The 2Y plan is in the cart (but 3Y is visible/selectable from the dropdown):

Screenshot 2023-03-15 at 2 40 06 PM

For this next point, not sure if related or just how things are meant to be. The 2Y flows do not let me select the 1Y plan on checkout (but do let me pick the higher tier 3Y plan):

Screenshot 2023-03-15 at 2 38 29 PM

This is what I get with the normal `/start` flow, with discounting pricing shown. Shouldn't this be the same (same options), just the 2Y plan pre-selected?

Screenshot 2023-03-15 at 2 37 40 PM

**Comment by aneeshd16** [comment]
Thanks @chriskmnds, for the review!

> This isn't the case for me 🤔 The 2Y plan is in the cart (but 3Y is visible/selectable from the dropdown):

I could reproduce this, and it seems to be happening because it assumes that the user is in the same flow when the `recur` param is changed. With the current recur types, here are steps to reproduce this:
1. Go to `/setup/ecommerce?recur=yearly`.
2. Proceed through the steps till you reach checkout.
3. In the same tab, go to `/setup/ecommerce?recur=monthly`.
4. On the domains step, the free option would be hidden, and instead, you would be given a choice to choose the site address you chose previously.
image

5. Select any domain and proceed to checkout.
6. The cart would have the yearly plan instead of the monthly plan.

Fixing this seems to be outside the scope of this PR. Tagging @Automattic/serenity for help in resolving this bug. 🙂 
If you clear IndexedDB and try with the `3Y` recur type, it should work correctly.


> For this next point, not sure if related or just how things are meant to be. The 2Y flows do not let me select the 1Y plan on checkout (but do let me pick the higher tier 3Y plan):

I think this is intentional. Here's the related discussion: https://github.com/Automattic/wp-calypso/issues/69633

**Review by chriskmnds — APPROVED** [review]
Thanks for the clarifications and investigation @aneeshd16 . 

So the issue looks like it's a bug with `/setup` itself as it happens irrespective of what's introduced here i.e. going into the flow after having completed a previous flow with a different `recur` value will end up adding the previous flow's plan variant in the cart. This is what happens on my end too. Other than that, the changes LGTM. Let's create an issue from your [description](https://github.com/Automattic/wp-calypso/pull/74456#issuecomment-1471778465) and tag @Automattic/serenity maybe?


> I think this is intentional. Here's the related discussion: https://github.com/Automattic/wp-calypso/issues/69633

Gotcha. Thanks for the additional context :-)

**Comment by aneeshd16** [comment]
Thanks @chriskmnds, created the issue here: https://github.com/Automattic/wp-calypso/issues/74641

**Pull request merged**
