### PR TITLE
Gutenberg: Move Related Posts to production blocks

### PR DESCRIPTION
**Pull request by tyxla**
DO NOT MERGE: We need to make the block available on Jetpack and WP.com first, and then get it tested:

* [x] Merge https://github.com/Automattic/jetpack/pull/10132
* [x] Merge D19537-code
* [x] Get it tested and proven to be in a stable state.

#### Changes proposed in this Pull Request

* Move Related Posts block to Production blocks.

#### Testing instructions

* Follow test instructions in D19537-code

### CODE REVIEW

**Comment by ockham** [comment]
To clarify, we also want to wait until after the CfT before merging this, correct?

**Comment by tyxla** [comment]
If we manually update the staging blocks on .com, yes. But my plan was to do it automatically by merging this PR. It would also make testing easier, as it wouldn't require beta blocks to be enabled for folks who want to test on Jetpack sites.

**Comment by ockham** [comment]
Merging it before the CfT would essentially mean releasing the block to the public on WP.com already though, no? Which I think is the wrong order :)

Sooner or later, we should just enable beta blocks in staging on WP.com (following a suggestion by @lezama). We just might need to make sure that they don't confuse A12s, so the idea was maybe to add little 'beta' ribbons to them.

**Comment by tyxla** [comment]
Yeah, you're right. Let's merge this when we get some testing and we know it's in a stable state.

**Comment by ockham** [comment]
You're right however that we either need to add a note to the CfT to instruct testers to apply a patch to their sandbox (ugh), or enable beta blocks on staging before posting the CfT.

**Comment by tyxla** [comment]
> enable beta blocks on staging before posting the CfT

Sounds like the best solution - we don't want to overcomplicate testing flows. Any downsides with it? Adding a "beta" ribbon can be done later.

**Comment by ockham** [comment]
I think the major downside is the potential confusion it might add for A12s, but I agree -- willing to incur that for a bit before adding whatever visual indicator later.

**Pull request merged**
