### PR TITLE
Jetpack: Update styles for JP Connect and JP Login

### PR DESCRIPTION
**Pull request by keoshi**
### Changes proposed in this Pull Request

* Updates styles for JP Connect and JP Login, gets rid of dark color scheme.
* This PR touches on files that are used in the Woo onboarding flows, though we expect no differences. cc @josemarques @LevinMedia 

### Testing instructions

- Ensure that all views on all possible flows show the light color scheme.
- Ensure that all views are consistent and display no visual errors.

#### Scenario 1: Connect pre-installed Jetpack + New account

* Starting in an incognito browser, go to wp-admin.
* Click “Set up Jetpack”.
* Replace `wordpress.com` by `calypso.localhost:3000` on the URL.
* Fill out details to create a new account.
* Head to the Plans page.

#### Scenario 2: Connect site with no Jetpack + Log in to existing account

* Starting in an incognito browser, go to http://calypso.localhost:3000/jetpack/connect.
* Enter your site URL and hit Continue.
* Enter your WP username and password, and hit Install Jetpack.
* Enter your username and hit Continue.
* Enter your password and hit Log in.
* Finish off authentication via 2FA, if needed.
* Head to the Plans page.

#### Scenario 3: Connect WooCommerce site

* Starting in an incognito browser, go to wp-admin.
* Make sure you have Jetpack (installed, not activated), WooCommerce (activated) and [WooCommerce Shipping & Tax](https://woocommerce.com/products/shipping/) (activated).
* You should see a prompt banner, click “Activate Jetpack and connect”.
* Replace `wordpress.com` by `calypso.localhost:3000` on the URL.
* Login or create a new account.
* Head to the Plans page.

#### Login

`/log-in/jetpack`
Before | After
--|--
image | image

`/log-in/jetpack/link`
Before | After
--|--
image | image

`/log-in/jetpack/push`
Before | After
--|--
————————————————————————————Couldn't get screenshot———————————————————————————— | image

`/log-in/jetpack/authenticator`
Before | After
--|--
image | image

#### Connect

`jetpack/connect`
Before | After
--|--
image | image

`/jetpack/connect/install`
Before | After
--|--
image | image

`/jetpack/connect/authorize`
Before | After
--|--
image | image

`jetpack/connect/authorize?{params}`
Before | After
--|--
image | image

`/jetpack/connect/plans`
Before | After
--|--
image | image

### CODE REVIEW

**Review by scottsweb — APPROVED** [review]
Test the three scenarios and everything looked good.  I couldn't see any huge issues on the woo one other than a slightly odd button state on the Google button:

Screenshot 2020-10-16 at 14 59 55

This exists in production at the moment though.

**Comment by scottsweb** [comment]
Minor: The border radius we use on the login form does not match the border radius for cards on `/jetpack/connect/store` which I think all became square recently.

**Review by rcanepa — APPROVED** [review]
Everything looks good to me. I saw all pages/steps with the new white style (it took me a while to figure out how to configure WooCommerce – I never did it before).

**Comment by keoshi** [comment]
@scottsweb 

> I couldn't see any huge issues on the woo one other than a slightly odd button state on the Google button

Good catch! https://github.com/Automattic/wp-calypso/pull/46503/commits/7b404d9ac770e9792ced512c1b345bff804556b5 should fix that.

**Comment by keoshi** [comment]
@scottsweb 

> Minor: The border radius we use on the login form does not match the border radius for cards on `/jetpack/connect/store` which I think all became square recently.

The login form you're referring to is the one pictured above under `jetpack/connect/authorize?{params}`, right? Any other I might have missed?

**Comment by keoshi** [comment]
https://github.com/Automattic/wp-calypso/pull/46503/commits/747f8c8a98b1e1950207e585067a5f5b697d15e6 should take care of the `border-radii` inconsistency.

**Comment by scottsweb** [comment]
> The login form you're referring to is the one pictured above under `jetpack/connect/authorize?{params}`, right? Any other I might have missed?

That is correct. I think the others were all good.

**Comment by DanReyLop** [comment]
The Woo flow also looks good 👍

**Pull request merged**
