### PR TITLE
Checkout: Move switching payment methods to tabs

### PR DESCRIPTION
**Pull request by akirk**
Extracted from #17754, changes the UI to switch payment methods to this:

image

Animated view:
checkout

Small screen view:
checkout--mobile

This adds a new component allowing for more than two available payment methods.
ABTest  is included in this PR.

For reference, this is what it looks like before the PR:
screen shot 2017-10-20 at 15 14 00

### CODE REVIEW

**Comment by yoavf** [comment]
Updated the description with new screenshots

**Comment by fditrapani** [comment]
@akirk I made some updates and pushed them to the branch.

**Comment by yoavf** [comment]
Looks great @fditrapani !

**Comment by yoavf** [comment]
Just tested with IE11 and the paypal logo looks cropped instead of resized:
screen shot 2017-10-25 at 14 32 27

It's already the case right now, even without this PR :( 
I'll fix

**Comment by yoavf** [comment]
> With IE11 and the paypal logo looks cropped instead of resized

Fixed by adding a viewbox attribute to the svg, and confirmed there's no regression visually where this file is currently used (one other place: `<PaymentLogo />` ).

👍 from me on 5cbffa9 as well.

**Comment by akirk** [comment]
@yoavf Great, thank you. Let's get it merged!

**Comment by fditrapani** [comment]
Good catch @yoavf. Thanks for fixing it up. Let's ship it. 🚢

**Comment by klimeryk** [comment]
screen shot 2017-10-27 at 22 44 12

^ was this also expected as part of this change? :) IMHO, that header in the middle of the view stands out a bit too much 🤔  cc @mikeshelton1503

**Comment by mikeshelton1503** [comment]
Nope that is a bug. Looks like the section header lost its styles.

**Pull request merged**
