### PR TITLE
Premium themes: Add correct cart item for Atomic sites

### LINKED ISSUE #65285: Premium themes cannot be purchased on Limited Atomic sites
### Quick summary

When trying to purchase a Premium theme on an Atomic site with a lower-tier plan, we trigger this error that prevents the theme from being purchased:

Screen Shot 2022-07-06 at 11 26 22

It only happens when purchasing from the theme details page, and apparently the underlying issue is that it tries to add a Jetpack plan to the cart:

Screen Shot 2022-07-06 at 11 28 36

### Steps to reproduce

- Go to https://wpcalypso.wordpress.com/theme/alonso/
- Select an Atomic sites on lower-tier plan
- Click on the "Pick this design" button

### What you expected to happen

The theme should be added to the cart

### What actually happened

There is an error indicating that the product is not compatible with my site

### PR DESCRIPTION
**Pull request by mmtr**
Fixes https://github.com/Automattic/wp-calypso/issues/65285

#### Proposed Changes

Ensures that the correct product is added to the cart when purchasing a premium theme on an Atomic site with a lower-tier plan.

#### Testing Instructions

- Use the Calypso live link below.
- Go to `/theme/alonso`.
- Select an Atomic site with a lower-tier plan (e.g. Starter plan).
- Click on "Pick this design".
- Make sure the theme is added to the cart correctly and that you can proceed with the purchase.
- Go to `/theme/alonso` again.
- Select a Jetpack site with a Free plan.
- Click on "Pick this design".
- Make sure the Jetpack Complete plan is added to the cart.

### CODE REVIEW

**Comment by mreishus** [comment]
With this PR, when I click on "Pick this design" on my atomic starter site, nothing happens. Also, the `<a>` inside the button is gone:


I think 2 alternate approaches are:
* Changing `needsJetpackPlanUpgrade` such that it doesn't send you on the `upgradePlan` path in this case 
https://github.com/Automattic/wp-calypso/blob/f43c0fd4b0ab3d2714945e06b748e9cccd99aacd/client/my-sites/theme/main.jsx#L836 (emphasizing individual theme purchases)
* OR Changing `getJetpackUpgradeUrlIfPremiumTheme` to return a url for buying a pro plan in this case (emphasizing plan upgrade)

**Comment by mmtr** [comment]
I'd say it was working on my tests, but I definitely can reproduce the same – I don't know what happened. I'll take a look

**Comment by mmtr** [comment]
> Changing needsJetpackPlanUpgrade such that it doesn't send you on the upgradePlan path in this case

That worked liked a charm, thanks!

**Review by mreishus — APPROVED** [review]
LGTM, is now working properly :+1:

**Pull request merged**
