### PR TITLE
Performance Profiler: Fix tooltip positioning

### PR DESCRIPTION
**Pull request by epeicher**
Related to https://github.com/Automattic/wp-calypso/pull/94031#issuecomment-2325563492

## Proposed Changes

* Fix tooltip positioning in the performance profiler history chart

https://github.com/user-attachments/assets/25c243e5-7eab-4672-bfaa-fee9dd3108a3

## Why are these changes being made?

* An additional change was required for the tooltip position after responsive changes

## Testing Instructions

* Apply this changes
* Navigate to the performance profiler tool and check the tooltip in the history chart

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Review by gavande1 — CHANGES_REQUESTED** [review]
Thanks for creating the quick fix. It works as expected. 

I notice when visiting [report without crux history](https://container-thirsty-lewin.calypso.live/speed-test-tool?url=https%3A%2F%2Fdanielbachhuber.com%2F&hash=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6NzAxMn0.1tMvgmxfu3mZTe6dk090DAKjinTp0VZzj1TfMdUU3xI), the tooltip does not render at correct place. 

CleanShot 2024-09-03 at 12 40 33@2x

**Comment by epeicher** [comment]
> Thanks for creating the quick fix. It works as expected.
> 
> I notice when visiting [report without crux history](https://container-thirsty-lewin.calypso.live/speed-test-tool?url=https%3A%2F%2Fdanielbachhuber.com%2F&hash=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6NzAxMn0.1tMvgmxfu3mZTe6dk090DAKjinTp0VZzj1TfMdUU3xI), the tooltip does not render at correct place.
> 
> CleanShot 2024-09-03 at 12 40 33@2x

Well spotted, after a quick look, it seems the event triggered for that is a React `SyntheticEvent` instead of a `d3Event` in [this line of code](https://github.com/Automattic/wp-calypso/blob/f4e4266671743032efed7f5ae0f0c0df6d67565c/client/performance-profiler/components/charts/history-chart.jsx#L140), and that event does not have the `layerX` and `layerY` fields. @gavande1, I cannot work more on this as I need to focus on other high-priority bugs, but you can continue from here. This can also be tackled as a follow-up task.

**Review by gavande1 — APPROVED** [review]
Lets merge this and iterate on it.

**Comment by epeicher** [comment]
> Lets merge this and iterate on it.

Issue created https://github.com/Automattic/dotcom-forge/issues/8998

**Pull request merged**
