### PR TITLE
Vertically center edit icon at different heights

### PR DESCRIPTION
**Pull request by anotheredward**
Fixes: #22445 

Replaced fixed offsets with dynamic height.
This button looks to be the only one that uses this class.

### CODE REVIEW

**Comment by dmsnell** [comment]
Thanks again @anotheredward! @MichaelArestad or @rickybanister would either one of you have some cycles to review this change? I'm having trouble judging the implications of the CSS changes.

**Comment by andfinally** [comment]
Apologies @anotheredward, the IE11 issue I thought I saw seems to have been a Browserstack rendering glitch, because on a VM IE everthing looks fine:

ie11-contact-form

I can also confirm the fix works on iOS 11.2.5 Safari:

ios

I'm new round here so it's probably best to see if anybody else has any views on this. But it looks a good solution to me.

**Comment by anotheredward** [comment]
Appreciate the additional testing @andfinally, thanks for the update.

**Comment by jblz** [comment]
Tests ok for me and is a definite improvement not just on the custom field, but with the builtin fields in small viewports:

## Before

screen shot 2018-02-26 at 2 25 50 pm

Notice the icon in the `Email` field is misaligned at a mobile viewport.

## After

screen shot 2018-02-26 at 2 32 35 pm

The icon seems aligned throughout.

Thanks for the fix!

**Pull request merged**
