### PR TITLE
Editor Media Google Photos: album / folder dropdown selector

### PR DESCRIPTION
**Pull request by jakejones1984**
Adds a dropdown to the Google Photos Modal within the editor in response to 

https://github.com/Automattic/wp-calypso/issues/22771

Allows user to select an existing folder from their Google Photos Library (currently the Picasa API) and filter the list of photos to show only photos from that Album. Also allows user to select to show All Photos.

### CODE REVIEW

**Comment by jakejones1984** [comment]
@johngodley `client/post-editor/media-modal/index.jsx` passes `folder` prop down through component hierarchy so that `MediaListData` has access to `folder` prop. Can we discuss 

1. Creating a new request which just retrieves a list of Folders from the API?
2. How we can pass the API a folder parameter to filter the photos by a given folder.

**Comment by johngodley** [comment]
The last I looked the media library wasn't using redux, and so if you maintain folder state much like it is with search then the value can be passed to the request and passed along when a folder is chosen.

And yep, making an initial request to populate the dropdown sounds like it will be necessary.

I can't remember if albums are implemented in our API (or maybe they are untested), so we'll need to get that working too. They are present in Picasa so it shouldn't be a lot of work either way.

**Comment by jakejones1984** [comment]
Closing in favour of Direct PR from Automattic repo.

**Comment by jakejones1984** [comment]
Moved to

https://github.com/Automattic/wp-calypso/pull/25762

**Pull request closed without merging**
