### PR TITLE
Gutenboarding: upgraded design screenshots

### PR DESCRIPTION
**Pull request by simison**
#### Changes proposed in this Pull Request

Re-ran the script to generate screenshots (while testing https://github.com/Automattic/wp-calypso/pull/43559).

To review, I recommend some tool such as [Github desktop](https://github.com/desktop/) that shows image differences side-by-side. Sadly Github itself doesn't. :-(

Ah screw that, I'm just gonna screenshot all these:

### Preview links, screenshots and notes for each design
<details>
  <summary>See screenshots (these are outdated, see latest comments for fresh ones</summary>

[Vesta](https://public-api.wordpress.com/rest/v1/template/demo/mayland/vesta?font_base=Raleway&font_headings=Cabin&site_title=Vesta)
Screenshot 2020-06-23 at 14 14 28
Bolded title (this is in many designs so I'm not gonna mention it again)

[Balasana](https://public-api.wordpress.com/rest/v1/template/demo/balasana/balasana?font_base=Chivo&font_headings=Open%20Sans&site_title=Balasana)
Screenshot 2020-06-23 at 12 44 59
Different spacing

[Barnsbury](https://public-api.wordpress.com/rest/v1/template/demo/barnsbury/barnsbury?font_base=Chivo&font_headings=Open%20Sans&site_title=Barnsbury)
Screenshot 2020-06-23 at 12 44 21
Underlined title, side-spacing gone.

[Bowen](https://public-api.wordpress.com/rest/v1/template/demo/coutoire/bowen?font_base=Fira%20Sans&font_headings=Playfair%20Display&site_title=Bowen)
Screenshot 2020-06-23 at 12 43 56
Underline

[Coutoire](https://public-api.wordpress.com/rest/v1/template/demo/coutoire/coutoire?font_base=Fira%20Sans&font_headings=Playfair%20Display&site_title=Coutoire)
Screenshot 2020-06-23 at 12 43 02

[Doyle](https://public-api.wordpress.com/rest/v1/template/demo/alves/doyle?font_base=Fira%20Sans&font_headings=Playfair%20Display&site_title=Doyle)
Screenshot 2020-06-23 at 12 42 43
Side margin issue.

[Easley](https://public-api.wordpress.com/rest/v1/template/demo/maywood/easley?font_base=Roboto&font_headings=Space%20Mono&site_title=Easley)
Screenshot 2020-06-23 at 12 42 19
Side margin issue.

[Edison](https://public-api.wordpress.com/rest/v1/template/demo/stratford/edison?font_base=Open%20Sans&font_headings=Chivo&site_title=Edison)
Screenshot 2020-06-23 at 12 41 54

[Rivington](https://public-api.wordpress.com/rest/v1/template/demo/rivington/rivington?font_base=Montserrat&font_headings=Arvo&site_title=Rivington)
Screenshot 2020-06-23 at 12 40 09

[Rockfield](https://public-api.wordpress.com/rest/v1/template/demo/rockfield/rockfield?font_base=Fira%20Sans&font_headings=Playfair%20Display&site_title=Rockfield)
Screenshot 2020-06-23 at 12 39 18
💥 prolly needs similar treatment to D45189-code

[Stratford](https://public-api.wordpress.com/rest/v1/template/demo/stratford/stratford?font_base=Open%20Sans&font_headings=Chivo&site_title=Stratford)
Screenshot 2020-06-23 at 14 18 40
Image showed up.

[Cassel](https://public-api.wordpress.com/rest/v1/template/demo/mayland/cassel?font_base=Fira%20Sans&font_headings=Playfair%20Display&site_title=Cassel)
image

[Camdem](https://public-api.wordpress.com/rest/v1/template/demo/maywood/camdem?font_base=Roboto&font_headings=Space%20Mono&site_title=Camdem)
image

[Reynolds](https://public-api.wordpress.com/rest/v1/template/demo/rockfield/reynolds?font_base=Fira%20Sans&font_headings=Playfair%20Display&site_title=Reynolds)
image

[Overton](https://public-api.wordpress.com/rest/v1/template/demo/alves/overton?font_base=Raleway&font_headings=Cabin&site_title=Overton)
image

[Brice](https://public-api.wordpress.com/rest/v1/template/demo/mayland/brice?font_base=Fira%20Sans&font_headings=Playfair%20Display&site_title=Brice)
image

[Alves](https://public-api.wordpress.com/rest/v1/template/demo/alves/alves?font_base=Montserrat&font_headings=Arvo&site_title=Alves)
image

[Mayland](https://public-api.wordpress.com/rest/v1/template/demo/mayland/mayland?font_base=Cabin&font_headings=Raleway&site_title=Mayland)
image

[Maywood](https://public-api.wordpress.com/rest/v1/template/demo/maywood/maywood?font_base=Fira%20Sans&font_headings=Playfair%20Display&site_title=Maywood)
image

[Leven](https://public-api.wordpress.com/rest/v1/template/demo/leven/leven?font_base=Open%20Sans&font_headings=Chivo&site_title=Leven)
image

[Gibbs](https://public-api.wordpress.com/rest/v1/template/demo/rockfield/gibbs?font_base=Fira%20Sans&font_headings=Fira%20Sans&site_title=Gibbs)
image
</details>

##### The two FSE demos we can probably ignore for now:

- [Reynolds (FSE)](https://public-api.wordpress.com/rest/v1/template/demo/seedlet-blocks/reynolds?font_base=Fira%20Sans&font_headings=Playfair%20Display&site_title=Reynolds%20%28FSE%29)
- [Vesta (FSE)](https://public-api.wordpress.com/rest/v1/template/demo/seedlet-blocks/vesta?font_base=Raleway&font_headings=Cabin&site_title=Vesta%20%28FSE%29)

#### Testing instructions

See designs step at `/new`

@ianstewart could you look these through and see if some of the changes are problems or is everything expected? I didn't have time to look into previews nor real sites yet if the problems are present in those too.

### CODE REVIEW

**Comment by ianstewart** [comment]
> could you look these through and see if some of the changes are problems or is everything expected?

Only the side-margin issues with Doyle and Easly and the giant hand of Rockfield are unexpected.

**Comment by ramonjd** [comment]
> Only the side-margin issues with Doyle and Easly and the giant hand of Rockfield are unexpected.

I had to generate this one manually for https://github.com/Automattic/wp-calypso/pull/42354. I could not escape the giant hand. :(

**Comment by simison** [comment]
@ramonjd do you know what's going on with side margins in some templates? Is it a specific theme broken somehow? Cc @kjellr

**Comment by andrewserong** [comment]
@simison could the side margins be related to the recent Layout Grid version bump? (I haven't checked the changelog, but it just occurred to me because of the issue we had with enqueuing the CSS for the template/demo endpoint)

**Comment by simison** [comment]
> could the side margins be related to the recent Layout Grid version bump?

@Automattic/tinker :wave: know about any changes that might've affected? We had this suspicion once before but [found it to be issue in Gutenberg core instead](https://github.com/Automattic/block-experiments/issues/76#issuecomment-618351710). 

cc @youknowriad any editor margin changes in core that might've broken things?

Example breakage:

**Comment by jasmussen** [comment]
@simison could it be https://github.com/WordPress/gutenberg/pull/23386 or https://github.com/WordPress/gutenberg/pull/22213?

**Comment by simison** [comment]
@jasmussen .com runs Gutenberg 8.3 though — if I understand correct, those would affect only 8.4?

**Comment by jasmussen** [comment]
Indeed :| 

Is that the Layout Grid block used in those screenshots, and does it appear related to that? We have some end-gutter paddings for that block which may have a bug, if it's layout-grid only.

**Comment by johngodley** [comment]
In terms of changes to the grid block, the recent update was fairly minor and focussed on the editor only.

- Fix block inserter to show inside a grid column
- Fix vertical margin in editor so it better matches the display
- Fix CSS loading so it is only added when block is used
- Fix grid lines appearing when inner block is selected

**Comment by sirreal** [comment]
I recall similar issues recently and dug up these diffs that may be related:

- D42350-code
- D42335-code

**Comment by razvanpapadopol** [comment]
@johngodley I can confirm the side margin issue being discussed here is related to Automattic/block-experiments#103

After some investigation I see the following styles are not loaded inside the editor but are loaded on the frontend, as opposed to the comment at the top of the file:
https://github.com/Automattic/block-experiments/blob/master/blocks/layout-grid/style.scss#L16-L17

**Comment by simison** [comment]
@johngodley @jasmussen could you look into style-loading issue in the layout-grid block? A few days ago we had to hot-fix this for the previews too (D45267-code) and in initial investigation it seemed like it would be previews-issue, but perhaps it's more wider problem?

**Comment by johngodley** [comment]
@simison sure, it's being tracked in https://github.com/Automattic/block-experiments/issues/103. It doesn't affect the front end.

**Comment by johngodley** [comment]
Noting that the style difference in the editor for the layout grid is now resolved.

**Comment by simison** [comment]
I regenerated screenshots so this now has latest, and I'm just excluding the "large hand" `rockfield_rockfield_rockfield.jpg`. 

<details>
  <summary>See screenshots</summary>
Screenshot 2020-07-02 at 15 01 35
Screenshot 2020-07-02 at 15 01 28
Screenshot 2020-07-02 at 15 01 17
Screenshot 2020-07-02 at 15 00 53
Screenshot 2020-07-02 at 15 00 50
Screenshot 2020-07-02 at 15 00 47
Screenshot 2020-07-02 at 15 00 42
Screenshot 2020-07-02 at 15 00 39
Screenshot 2020-07-02 at 15 00 30
Screenshot 2020-07-02 at 15 00 26
Screenshot 2020-07-02 at 15 00 22
Screenshot 2020-07-02 at 15 00 18
Screenshot 2020-07-02 at 15 00 12
Screenshot 2020-07-02 at 15 00 07
Screenshot 2020-07-02 at 14 59 59
Screenshot 2020-07-02 at 14 59 54
Screenshot 2020-07-02 at 14 59 48
Screenshot 2020-07-02 at 14 59 44
Screenshot 2020-07-02 at 14 59 40
Screenshot 2020-07-02 at 14 59 35
Screenshot 2020-07-02 at 14 59 31
Screenshot 2020-07-02 at 14 59 26
</details>

**Comment by ramonjd** [comment]
> and I'm just excluding the "large hand"

THE HAND OF DOOM!

**Pull request merged**
