### PR TITLE
Gravatar: Implement magic code signup / login

### PR DESCRIPTION
**Pull request by wellyshen**
Related to 107803-gh-Automattic/gravatar, 107644-gh-Automattic/gravatar, 107645-gh-Automattic/gravatar

## Proposed Changes

* Implement the new Gravatar magic signup / login view
* Implement the new Gravatar secondary email view and flow
* Implement the new Gravatar magic code verification view and flow
* Update the styles of the password login page
* Add / update tracking events
* Support the old magic link signup / login for WP Job Manager
* (Extra) Fix the style of the social login buttons for WP Job Manager

## Why are these changes being made?

* Please refer to p8Slzc-2NM-p2

### Preparation

* Apply this diff: D149234-code
* [Setup Calypso](https://github.com/Automattic/wp-calypso?tab=readme-ov-file#getting-started)
* Check out this PR, and run `yarn start`
* (IMPORTANT) Allow the browsers' 3rd-party cookies (e.g. [Google Chrome](https://support.google.com/accounts/answer/61416?hl=en&co=GENIE.Platform%3DDesktop))

### Sign up for an account

* Ensure the email has not been registered before
* Sign up your account via [this URL](http://calypso.localhost:3000/log-in/link?gravatar_magic_code=true&gravatar_from=signup&client_id=1854&redirect_to=https%3A%2F%2Fpublic-api.wordpress.com%2Foauth2%2Fauthorize%3Fclient_id%3D1854%26response_type%3Dcode%26blog_id%3D0%26state%3D7cb30c204432e20253ec71dda82f83c915bc16d2b1cb057d131cdf48eaecf958%26redirect_uri%3Dhttps%253A%252F%252Fgravatar.com%252Fconnect%252F%253Faction%253Drequest_access_token%26from-calypso%3D1)
* You will be logged in to Gravatar through the magic code flow:

https://github.com/Automattic/wp-calypso/assets/21308003/23f13a47-e4ad-4849-a4f0-54027ee2bb66

* Ensure these UIs are displayed correctly:

| Email | Verification (with ToS) |
| - | - |
| 截圖 2024-06-20 下午4 12 17 | 截圖 2024-06-20 下午4 23 50 |

### Login with a non-2FA account

* Log in your non-2FA account via [this URL](http://calypso.localhost:3000/log-in/link?gravatar_magic_code=true&client_id=1854&redirect_to=https%3A%2F%2Fpublic-api.wordpress.com%2Foauth2%2Fauthorize%3Fclient_id%3D1854%26response_type%3Dcode%26blog_id%3D0%26state%3D7cb30c204432e20253ec71dda82f83c915bc16d2b1cb057d131cdf48eaecf958%26redirect_uri%3Dhttps%253A%252F%252Fgravatar.com%252Fconnect%252F%253Faction%253Drequest_access_token%26from-calypso%3D1)
* You will be logged in to Gravatar through the magic code flow:

https://github.com/Automattic/wp-calypso/assets/21308003/06823fae-2223-433d-8860-5e6fca76b378

* Ensure these UIs are displayed correctly:

| Email | Verification (without ToS) |
| - | - |
| 截圖 2024-06-20 下午4 29 46 | 截圖 2024-06-20 下午4 27 58 |

### Login with a 2FA account

* Log in your 2FA account via [this URL](http://calypso.localhost:3000/log-in/link?gravatar_magic_code=true&client_id=1854&redirect_to=https%3A%2F%2Fpublic-api.wordpress.com%2Foauth2%2Fauthorize%3Fclient_id%3D1854%26response_type%3Dcode%26blog_id%3D0%26state%3D7cb30c204432e20253ec71dda82f83c915bc16d2b1cb057d131cdf48eaecf958%26redirect_uri%3Dhttps%253A%252F%252Fgravatar.com%252Fconnect%252F%253Faction%253Drequest_access_token%26from-calypso%3D1)
* You will be logged in to Gravatar through the magic code flow:

https://github.com/Automattic/wp-calypso/assets/21308003/9fb888af-e34b-44a5-8638-9a9c183356a4

### Login with a Gravatar secondary email

* Ensure the email has been added to your Gravatar profile: https://gravatar.com/profile/avatars
* Log in your account via [this URL](http://calypso.localhost:3000/log-in/link?gravatar_magic_code=true&client_id=1854&redirect_to=https%3A%2F%2Fpublic-api.wordpress.com%2Foauth2%2Fauthorize%3Fclient_id%3D1854%26response_type%3Dcode%26blog_id%3D0%26state%3D7cb30c204432e20253ec71dda82f83c915bc16d2b1cb057d131cdf48eaecf958%26redirect_uri%3Dhttps%253A%252F%252Fgravatar.com%252Fconnect%252F%253Faction%253Drequest_access_token%26from-calypso%3D1)
* During the flow, you can log in to Gravatar using your existing main account or by creating a new account with a secondary email:

https://github.com/Automattic/wp-calypso/assets/21308003/8abaa133-ae66-4979-b67a-2b85fb194f45

* Ensure these UIs are working and displayed correctly:

| Secondary email options (main) | Secondary email options (new) | Verification (main) | Verification (new) |
| - | - | - | - |
| 截圖 2024-06-20 下午4 36 27 | 截圖 2024-06-20 下午4 40 04 | 截圖 2024-06-20 下午4 43 33 | 截圖 2024-06-20 下午4 44 01 |

### UIs, functions, and error handling should work properly

* The email form has the proper validation and UI / API error handling:

截圖 2024-06-20 下午5 05 20

* The code verification form has the proper validation and UI / API error handling:

截圖 2024-06-20 下午5 19 51

* Click the "Sign in another way" should go to the existing password login page:

截圖 2024-06-20 下午4 50 18

* The "Send again" should work correctly, especially for the secondary email case:
  * The user selects the main account: Send it to the main account's email
  * The user selects the new account (the secondary email): Send it to the secondary email
  
截圖 2024-06-20 下午4 55 38

* Click the "Need help logging in?", should link to Gravatar's support page:

截圖 2024-06-20 下午5 00 37

* The styles and footer's wording of [the existing password login page](http://calypso.localhost:3000/log-in?redirect_to=https%3A%2F%2Fpublic-api.wordpress.com%2Foauth2%2Fauthorize%3Fclient_id%3D1854%26response_type%3Dcode%26blog_id%3D0%26state%3D7cb30c204432e20253ec71dda82f83c915bc16d2b1cb057d131cdf48eaecf958%26redirect_uri%3Dhttps%253A%252F%252Fgravatar.com%252Fconnect%252F%253Faction%253Drequest_access_token%26from-calypso%3D1&client_id=1854&gravatar_magic_code=true) should have been updated:

| Before | After |
| - | - |
| 截圖 2024-06-20 下午5 51 42 | 截圖 2024-06-20 晚上11 19 59 |

* WP Job Manager's password login page should look the same, except the missed social buttons' circle has been bringing back:

| Before | After |
| - | - |
| 截圖 2024-06-20 晚上7 55 21 | 截圖 2024-06-20 晚上7 54 34 |

### Test added / updated tracking events

We can check the events through the browser's dev tools, e.g. Google Chrome:

截圖 2024-06-20 下午5 37 07

The following events should be sent correctly:

* View events:
  * Email form: `calypso_gravatar_powered_magic_login_email_form`
  * Secondary email options: `calypso_gravatar_powered_magic_login_secondary_email_options`
  * Code verification: `calypso_gravatar_powered_magic_login_email_code_verification`
 
* API events:
  * `/auth/get-gravatar-info`:
    * `calypso_gravatar_powered_magic_login_gravatar_info_fetching`
    * `calypso_gravatar_powered_magic_login_gravatar_info_success`
    * `calypso_gravatar_powered_magic_login_gravatar_info_failure`
  * `/auth/send-login-email`:
    * `calypso_gravatar_powered_magic_login_email_code_requesting`
    *  `calypso_gravatar_powered_magic_login_email_code_success`
    * `calypso_gravatar_powered_magic_login_email_code_failure`
  
* Clicking events:
  * `Switch email`: `calypso_gravatar_powered_magic_login_click_switch_email`
  * Secondary email options:
    * `Main account`: `calypso_gravatar_powered_magic_login_click_main_account`
    * `New account`: `calypso_gravatar_powered_magic_login_click_new_account`
  * `Send again`: `calypso_gravatar_powered_magic_login_click_resend_email` with the property: `type: code` or `type: link`

### Other products should still work the same

* Gravatar Magic Link
  * [Dev](http://calypso.localhost:3000/log-in/link?client_id=1854&redirect_to=https%3A%2F%2Fpublic-api.wordpress.com%2Foauth2%2Fauthorize%3Fclient_id%3D1854%26response_type%3Dcode%26blog_id%3D0%26state%3D7cb30c204432e20253ec71dda82f83c915bc16d2b1cb057d131cdf48eaecf958%26redirect_uri%3Dhttps%253A%252F%252Fgravatar.com%252Fconnect%252F%253Faction%253Drequest_access_token%26from-calypso%3D1)
  * [Prod](https://wordpress.com/log-in/link?client_id=1854&redirect_to=https%3A%2F%2Fpublic-api.wordpress.com%2Foauth2%2Fauthorize%3Fclient_id%3D1854%26response_type%3Dcode%26blog_id%3D0%26state%3D0ed6fe174c184792b709a49ec6e5ef6366d2739d7f9df738f76f0ec801e407eb%26redirect_uri%3Dhttps%253A%252F%252Fgravatar.com%252Fconnect%252F%253Faction%253Drequest_access_token%26from-calypso%3D1)

* WP Job Manager
  * [Dev](http://calypso.localhost:3000/log-in/link?client_id=90057&redirect_to=https%3A%2F%2Fpublic-api.wordpress.com%2Foauth2%2Fauthorize%2F%3Fclient_id%3D90057%26response_type%3Dcode%26state%3DeyJyZWRpcmVjdF90byI6Imh0dHBzOlwvXC93cGpvYm1hbmFnZXIuY29tXC9teS1hY2NvdW50In0%26redirect_uri%3Dhttps%253A%252F%252Fwpjobmanager.com%252Fwp-json%252Fwpjmcom-auth%252Fv1%252Fcallback%26blog_id%3D0%26from-calypso%3D1)
  * [Prod](https://wordpress.com/log-in/link?client_id=90057&redirect_to=https%3A%2F%2Fpublic-api.wordpress.com%2Foauth2%2Fauthenticate%2F%3Fclient_id%3D90057%26response_type%3Dcode%26state%3D01b7d7bfcfd126450053529ce09fefb5%26redirect_uri%3Dhttp%253A%252F%252Fwpjobmanagercom.vipdev.lndo.site%253A8000%252Fwp-json%252Fwpjmcom-auth%252Fv1%252Fcallback&create_account=1)

* WP.com
   * [Dev](http://calypso.localhost:3000/log-in/link)
   * [Prod](https://wordpress.com/log-in/link)

* Woo
  * [Dev](http://calypso.localhost:3000/log-in/link?redirect_to=https%3A%2F%2Fpublic-api.wordpress.com%2Foauth2%2Fauthorize%2F%3Fresponse_type%3Dcode%26client_id%3D50916%26state%3Dfe6b7fe71924cbd378654e8165ab2b6bf0f2d658065cd27bf038faf6b49a8e9a%26redirect_uri%3Dhttps%253A%252F%252Fwoocommerce.com%252Fwc-api%252Fwpcom-signin%253Fnext%253D%25252F%26blog_id%3D0%26wpcom_connect%3D1%26wccom-from%26calypso_env%3Dproduction%26from-calypso%3D1&client_id=50916)
  * [Prod](https://wordpress.com/log-in/link?redirect_to=https%3A%2F%2Fpublic-api.wordpress.com%2Foauth2%2Fauthorize%2F%3Fresponse_type%3Dcode%26client_id%3D50916%26state%3Dfe6b7fe71924cbd378654e8165ab2b6bf0f2d658065cd27bf038faf6b49a8e9a%26redirect_uri%3Dhttps%253A%252F%252Fwoocommerce.com%252Fwc-api%252Fwpcom-signin%253Fnext%253D%25252F%26blog_id%3D0%26wpcom_connect%3D1%26wccom-from%26calypso_env%3Dproduction%26from-calypso%3D1&client_id=50916)
    
* Jetpack
  * [Dev](http://calypso.localhost:3000/log-in/link?client_id=69040&redirect_to=https%3A%2F%2Fpublic-api.wordpress.com%2Foauth2%2Fauthorize%3Fresponse_type%3Dtoken%26client_id%3D69040%26redirect_uri%3Dhttps%253A%252F%252Fcloud.jetpack.com%252Fconnect%252Foauth%252Ftoken%253Fnext%253D%25252Fpricing%25253Futm_source%25253Dgoogle%252526utm_medium%25253Dcpc%252526utm_campaign%25253D20732627996%252526utm_content%25253D592794838992%252526utm_term%25253Djetpack%252526utm_term%25253Djetpack%252526utm_campaign%25253Dgoogle_jetpack_search_BRAND_other_countries%252526utm_source%25253Dadwords%252526utm_medium%25253Dppc%252526hsa_acc%25253D6173802314%252526hsa_cam%25253D20732627996%252526hsa_grp%25253D160816494928%252526hsa_ad%25253D592794838992%252526hsa_src%25253Dg%252526hsa_tgt%25253Dkwd-298987025683%252526hsa_kw%25253Djetpack%252526hsa_mt%25253De%252526hsa_net%25253Dadwords%252526hsa_ver%25253D3%252526gad_source%25253D1%252526gclid%25253DEAIaIQobChMIl_2KwY3qhgMV2sJMAh0OZgfnEAAYASAAEgIDEvD_BwE%26scope%3Dglobal%26blog_id%3D0%26from-calypso%3D1)
  * [Prod](https://wordpress.com/log-in/link?client_id=69040&redirect_to=https%3A%2F%2Fpublic-api.wordpress.com%2Foauth2%2Fauthorize%3Fresponse_type%3Dtoken%26client_id%3D69040%26redirect_uri%3Dhttps%253A%252F%252Fcloud.jetpack.com%252Fconnect%252Foauth%252Ftoken%253Fnext%253D%25252Fpricing%25253Futm_source%25253Dgoogle%252526utm_medium%25253Dcpc%252526utm_campaign%25253D20732627996%252526utm_content%25253D592794838992%252526utm_term%25253Djetpack%252526utm_term%25253Djetpack%252526utm_campaign%25253Dgoogle_jetpack_search_BRAND_other_countries%252526utm_source%25253Dadwords%252526utm_medium%25253Dppc%252526hsa_acc%25253D6173802314%252526hsa_cam%25253D20732627996%252526hsa_grp%25253D160816494928%252526hsa_ad%25253D592794838992%252526hsa_src%25253Dg%252526hsa_tgt%25253Dkwd-298987025683%252526hsa_kw%25253Djetpack%252526hsa_mt%25253De%252526hsa_net%25253Dadwords%252526hsa_ver%25253D3%252526gad_source%25253D1%252526gclid%25253DEAIaIQobChMIl_2KwY3qhgMV2sJMAh0OZgfnEAAYASAAEgIDEvD_BwE%26scope%3Dglobal%26blog_id%3D0%26from-calypso%3D1)

## Pre-merge Checklist

- [x] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [x] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Review by aaronfc — COMMENTED** [review]
Testing:
- Signup with new email ✅ 
⚠️ @wellyshen I could click the "Send email" multiple times. I remember we had some time-based protection so you could only click it once every minute or so (with a countdown). Do you think we can recover that?
- `gravatar_from=signup` parameter presence displays different title ✅ 
- Login with existing account (no 2fa) ✅ 
- Login with existing account (2fa using authenticator app) ✅ 
- Login with existing account (2fa using sms) ✅ 
- Login with secondary email (using main email) ✅ 
  - Masked email is correctly shown. ✅ 
- Login with secondary email (creating new account) ✅ 
  - Account is unlinked from main.
- Error handling ✅ 
- Sign in in another way 🟡 
  - Login with password ✅ 
  - Create account link brings you to login without `gravatar_magic_code=true` 🟡  – we might want to ignore this since when open in production it shouldn't happen.
- Gravatar magic link works ok ✅ 
- WPJM magic link works ok ✅ 
  - 🟡  There is an error if you use the link the testing steps because it uses `wpjobmanagercom.vipdev.lndo.site` in the redirect, but [this](http://calypso.localhost:3000/log-in/link?client_id=90057&redirect_to=https%3A%2F%2Fpublic-api.wordpress.com%2Foauth2%2Fauthorize%2F%3Fclient_id%3D90057%26response_type%3Dcode%26state%3DeyJyZWRpcmVjdF90byI6Imh0dHBzOlwvXC93cGpvYm1hbmFnZXIuY29tXC9teS1hY2NvdW50In0%26redirect_uri%3Dhttps%253A%252F%252Fwpjobmanager.com%252Fwp-json%252Fwpjmcom-auth%252Fv1%252Fcallback%26blog_id%3D0%26from-calypso%3D1) should work.
- WPCOM:
  - User/password works fine ✅
  - Magic link works fine ✅
  - Magic code **is not available** [[link](http://calypso.localhost:3000/log-in/?gravatar_magic_code=true)] ✅
- Woo:
  - Magic login works fine ✅
- Jetpack:
  - Magic login works fine ✅ 
  
Extra tests:
- Tested after-login redirect with [this url](http://calypso.localhost:3000/log-in/link?gravatar_magic_code=true&client_id=1854&redirect_to=https%3A%2F%2Fpublic-api.wordpress.com%2Foauth2%2Fauthorize%3Fclient_id%3D1854%26response_type%3Dcode%26blog_id%3D0%26state%3D92a99e461b080d3a4d0fff04018f83f2a91604a4633ef1d40656798069ab361c%26redirect_uri%3Dhttps%253A%252F%252Fgravatar.com%252Fconnect%252F%253Fredirect_to%253D%25252Fprofile%25252Fdesign%25252Fbackground%25253Femail%25253Dpotato%252540gmail.com%2526action%253Drequest_access_token%26from-calypso%3D1). ✅ 

Things I noticed:
- 🔴 We must prevent a user from spamming the "Send again" button.
- 🟡 If we type the wrong email there is no easy action to go "back" or cancel. Users can click the "back" browser button, but from mobile it might not be possible.
- 🔴 During code validation we might get a 429 (Too many requests). In this case the button gets stuck and there is no feedback. We must show some error saying that you need to wait a minute to continue.
- 🟡 After 3 failed code verification intents the code is not valid anymore. It would be nice if we told the user about that. So we prevent them from getting blocked due to many errors. This needs changes in the backend, but we could maybe say "Invalid code. If error persists try with a new code." ?


I am now reviewing the code... 👀

**Comment by wellyshen** [comment]
> 🔴 We must prevent a user from spamming the "Send again" button.
> 🔴 During code validation we might get a 429 (Too many requests). In this case the button gets stuck and there is no feedback. We must show some error saying that you need to wait a minute to continue.
> 🟡 we might want to ignore this since when open in production it shouldn't happen.
> 🟡 After 3 failed code verification intents the code is not valid anymore. It would be nice if we told the user about that. So we prevent them from getting blocked due to many errors. This needs changes in the backend, but we could maybe say "Invalid code. If error persists try with a new code." ?

@aaronfc Thank you for such detailed testing 💙. I have addressed the above issues via [this commit](https://github.com/Automattic/wp-calypso/pull/91724/commits/d4d9ee6e9a16e58a8f60f04636ddf6bb285c6f84).

> 🟡 If we type the wrong email there is no easy action to go "back" or cancel. Users can click the "back" browser button, but from mobile it might not be possible.

It needs the design. I have created an issue (108147-gh-Automattic/gravatar) for it. We can address it in the following PR.

**Review by aaronfc — COMMENTED** [review]
Code looks good. Thanks, Welly! Good job!

I have done some tests and in general it looks good except for the 429 HTTP error. See below.

Tests:
- Email is protected from spamming the button ✅ 
- Send again button works correctly after a minute and a half ✅ 
- 'Switch email' works as expected ✅ 
- Custom error when 429 response code 🔴. See screenshot.
image
- New copy hinting to generate a new code if error persists ✅

**Comment by wellyshen** [comment]
> * Custom error when 429 response code 🔴. See screenshot.

We aren't able to get the `429` error status. It seems we need the relevant error response from the API.

**Review by aaronfc — APPROVED** [review]
Looks good and works as described! 🟢 🟢 🟢

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/15716199

Some locales (Hebrew, Japanese) have been temporarily machine-translated due to translator availability. All other translations are usually ready within a few days. Untranslated and machine-translated strings will be sent for translation next Monday and are expected to be completed by the following Friday.

Thank you @wellyshen for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/15716199).

**Pull request merged**
