### PR TITLE
Pull in the 2fa data layer as part of login state init

### PR DESCRIPTION
**Pull request by blowery**
#### Changes proposed in this Pull Request

* Pull in the 2fa data layer as part of login state init
* May make polling for updates work

#### Testing instructions

*

Fixes #

### CODE REVIEW

**Comment by sgomes** [comment]
Thank you for investigating and fixing this, @blowery! 👍

I think this fix was done at the wrong level, though; it's not `state/login/actions/push/index.js` that's using side effects, but rather the file it imports, `state/data-layer/wpcom/login-2fa`.

Is there a good way we could test moving the fix to `state/data-layer` (which should probably all be marked as side-effectful) without potentially breaking things again?

**Comment by designsimply** [comment]
<sup>(internal reference: p4a5px-2z2-p2)</sup>

**Comment by sgomes** [comment]
To follow up on my previous comment, I believe that having to add this declaration for the importer is a webpack bug. I filed an issue at https://github.com/webpack/webpack/issues/10939 based on a simplified reproducible case.

**Comment by sgomes** [comment]
It appears that the `webpack` team disagrees this is a bug. A better solution is still possible, however, and we implement that in #42569.

**Pull request merged**
