### PR TITLE
Themes: Scroll to top of theme sheet on opening

### LINKED ISSUE #5764: Themes: Details page should scroll to top of page on load
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/design/
2. Scroll down in the list of themes
3. Click the ellipsis and select Details

#### What I expected
The details to be displayed as a new page

#### What happened instead
The theme list page's scroll is carried over to the Details page, meaning I can't see the headers at the top

#### Browser / OS version
OSX Chrome

#### Screenshot / Video
themes-scrolling

### PR DESCRIPTION
**Pull request by seear**
Fixes #5764

**To Test**
Follow instructions in #5764 

Test live: https://calypso.live/?branch=fix/theme-sheet-scroll-top

### CODE REVIEW

**Comment by folletto** [comment]
I thought we kept the position to allow the "back" action to not lose the position in the scroll, but I noticed that it doesn't work already.

Tested on Chrome, Safari, Firefox: 👍

**Comment by seear** [comment]
> I thought we kept the position to allow the "back" action to not lose the position in the scroll, but I noticed that it doesn't work already.

Let me think about this a bit.

**Comment by seear** [comment]
> I thought we kept the position to allow the "back" action to not lose the position in the scroll, but I noticed that it doesn't work already.

I'd like to come back to this later, because we really want this to work properly. Ideally we would be able to use a page.back() when possible for the back button, which would maintain the scroll position. For now I think we should add this simple fix in for M4.

**Comment by folletto** [comment]
> I'd like to come back to this later, because we really want this to work properly. Ideally we would be able to use a page.back() when possible for the back button, which would maintain the scroll position. For now I think we should add this simple fix in for M4.


👍

**Comment by budzanowski** [comment]
:+1:

**Pull request merged**
