### PR TITLE
Allow opening site previews in a new tab with Cmd+click or middle click

### PR DESCRIPTION
**Pull request by okmttdhr**
Related to https://github.com/Automattic/dotcom-forge/issues/9969

## Proposed Changes

This PR allows opening site previews in a new tab with Cmd+click or middle click.

## Why are these changes being made?

https://github.com/Automattic/dotcom-forge/issues/9969

## Testing Instructions

* Go to /sites
* Cmd+click any site
* Observe the site opens in a new window

## Pre-merge Checklist

- [x] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [x] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [x] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [x] Have you checked for TypeScript, React or other console errors?
- [x] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [x] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
    - [x] For UI changes, have we tested the change in various languages (for example, ES, PT, FR, or DE)? The length of text and words vary significantly between languages. 
- [x] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Review by arthur791004 — APPROVED** [review]
I'm not sure whether it makes sense to open the site preview in a new tab 🤔 However, tested and looks good to me!

**Comment by okmttdhr** [comment]
>I'm not sure whether it makes sense to open the site preview in a new tab 

Good point. I think the topic here is expectations of the default behavior. We might want to implement this feature using a native `<a>` tag to leverage the browser's built-in behavior for navigation. Here’s an example implementation for handling custom click behavior while preserving native functionality:

```js
function handleClick(event) {
  if (
    event.metaKey || // Cmd+click
    event.ctrlKey || // Ctrl+click
    event.shiftKey || // Shift+click
    event.altKey || // Alt+click
    event.button !== 0 // Middle-click or other non-left clicks
  ) {
    return; // Let the browser handle it natively
  }

  // Otherwise, prevent default behavior and do whatever we want
  event.preventDefault();
  ...
}
```

For this issue: https://github.com/Automattic/dotcom-forge/issues/9969 overall, I will propose adding a "link" type to the action in DataViews in [Core](https://github.com/WordPress/gutenberg/blob/c3ca59b70c9807e78b45d22d0714be777da507fd/packages/dataviews/src/types.ts#L481). 
We can revisit this implementation later to align with that.

**Comment by mirka** [comment]
> We might want to implement this feature using a native `<a>` tag to leverage the browser's built-in behavior for navigation.

Agreed 100%. Any trigger that adds an item to the browser history stack needs to semantically be an `anchor`, otherwise we have an accessibility issue.

I came to this PR because right-clicking the site name caused a browser navigation, which shouldn't happen. The right-click case needs to be handled, but the best way to do that is probably by changing it from a button to an anchor, rather than adding more handler logic.

**Comment by okmttdhr** [comment]
I previously created https://github.com/WordPress/gutenberg/issues/68278, which we now need to address on the Dotcom side in some way.

**Pull request merged**
