### PR TITLE
Stats: Adjust tooltip styles in Stats

### PR DESCRIPTION
**Pull request by dognose24**
#### Proposed Changes

* Check the tooltip applied styles in the `Chart` component.
* Overwrite tooltip styles in Stats styles when necessary to improve the tooltip styling.
* Alter the Visitors icon in tooltips.

#### Testing Instructions

* Open the page `Stats` for certain site `/stats/day/${your-site}`.
* Hover the bar chart of the day traffic.
* Ensure the tooltip displays with new styles in line with the Design.

| Before | After |
| --- | --- |
| 截圖 2022-10-21 上午10 11 57 | 截圖 2022-10-21 上午10 49 22 |

#### Pre-merge Checklist

- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [x] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?

Related to #69178

### CODE REVIEW

**Review by kangzj — APPROVED** [review]
It works as described 👍

**Comment by keoshi** [comment]
Two small nitpicks @dognose24:

- Would it be possible to get rid of the uppercase styling in the text?
- Could we swap out old icons for the new ones? Let me know if you need the SVG code for those.

Leaving the proposed design here for clarity:

image

**Comment by dognose24** [comment]
> Would it be possible to get rid of the uppercase styling in the text?

Sure thing! I was planning to do this change and now I am more confident about it.

> Could we swap out old icons for the new ones? Let me know if you need the SVG code for those.

The codebase is referring to this icon library: [Automattic/gridicons](https://github.com/Automattic/gridicons), and there seems not to be icons `Views`, `Visitors`, `Comments`, and `Post published` used in the Design, which maybe we can import new icons into there.

BTW, is `Copy as SVG` in Figma the proper way to utilize the SVG code?

截圖 2022-10-25 上午4 46 13

cc @jeffgolenski @jsnmoon

**Comment by jsnmoon** [comment]
> > Could we swap out old icons for the new ones? Let me know if you need the SVG code for those.
> 
> The codebase is referring to this icon library: [Automattic/gridicons](https://github.com/Automattic/gridicons), and there seems not to be icons `Views`, `Visitors`, `Comments`, and `Post published` used in the Design, which maybe we can import new icons into there. (@dognose24)

Sounds like a solid plan to me!

> BTW, is `Copy as SVG` in Figma the proper way to utilize the SVG code? (@dognose24)

I'm going to guess "yes." @jeffgolenski can correct me if I'm wrong 🙂

**Pull request merged**
