### PR TITLE
Jetpack Cloud: open checkout in the same tab

### LINKED ISSUE #51106: From Jetpack Cloud: Open check out in the same tab (not a new one)
When you are on Jetpack Cloud and you click a purchase button, let's say you do not have scan and you choose to upgrade and get it, we open the checkout in a separate tab. This takes the user totally out of the flow they were in. If you watch the attached video you will see why this is confusing. Especially if you change your mind and decide to hit close or the back button.

What
Let's open the checkout flow in the same tab to keep content for the users. 

Why
It reduces confusion, it's actually best practice to open in the same tab.

paths

https://user-images.githubusercontent.com/49159284/110977707-15a50980-8328-11eb-877d-6bd8e72728fc.mp4

### PR DESCRIPTION
**Pull request by rcanepa**
#### Changes proposed in this Pull Request

* Make upgrade buttons located at `/scan/:site`, `/backup/:site`, and `/activity-log/:site` open their target link in the same tab.

#### Notes

* ~~Backup's upgrade button points to `https://jetpack.com/upgrade/backup/?site=[site]` rather than to checkout. Should we change this?~~ Yvonne confirmed that we are not changing any link, just making upgrade buttons open their target links on the same tab.
* I'm deleting the `client/my-sites/scan/upsell.jsx` since is a duplicate of `client/my-sites/scan/scan-upsell/index.jsx`.

#### Testing instructions

* Download this PR.
* Start Jetpack Cloud (Calypso Green) with `yarn start-jetpack-cloud`.
* Make sure you have a Jetpack site that doesn't have any paid plan.
* Visit `http://jetpack.cloud.localhost:3000/scan/[site]`.
* Click on the upgrade button.
* Make sure that checkout is opened in the same tab.
* Visit `http://jetpack.cloud.localhost:3000/backup/[site]`.
* Make sure that Jetpack Backup's marketing page is opened in the same tab.
* Visit `http://jetpack.cloud.localhost:3000/activity-log/[site]`.
* Make sure that the plans page is opened in the same tab.

Fixes https://github.com/Automattic/wp-calypso/issues/51106
Related to 1164141197617539-as-1200094501156158

#### Demo
https://user-images.githubusercontent.com/3418513/113446110-80001580-93cd-11eb-8086-7c4a55ce5508.mp4

### CODE REVIEW

**Review by robertf4 — COMMENTED** [review]
Tests well for me. I wonder if this change should apply to Backup and the Activity Log in addition to Scan, it seems inconsistent to open in the same tab for Scan but not the other activities. @eeeeevon13 could you weigh in on this?

**Comment by eeeeevon13** [comment]
> Tests well for me. I wonder if this change should apply to Backup and the Activity Log in addition to Scan, it seems inconsistent to open in the same tab for Scan but not the other activities. @eeeeevon13 could you weigh in on this?
@robertf4  Yes! We should do this on all check out buttons from cloud!

Aside from that it looks great!

**Comment by rcanepa** [comment]
I made the three upgrade buttons open the target link in the same tab and I kept the targets intact. @robertf4 can I have a quick second review?

**Review by elliottprogrammer — APPROVED** [review]
Tested and works as described. All 3 upgrade buttons open the target link in the same tab. Code looks all good. 👍
LGTM!

**Review by robertf4 — APPROVED** [review]
LGTM! 🚢

**Pull request merged**
