### PR TITLE
Release stepper to production 🎉

### PR DESCRIPTION
**Pull request by alshakero**
#### Changes proposed in this Pull Request

This releases Stepper to production.

Context here: pdDR7T-1B-p2

### CODE REVIEW

**Comment by escapemanuele** [comment]
I'm sure you already noted that. I'm leaving this comment only for us to remember to [remove this check](https://github.com/Automattic/wp-calypso/pull/63340/files#diff-9ba754f27ecf58cc3b55d0d053194696397eda7210d9031798dd19167049a66bR386-R389) before deploying this

**Comment by alshakero** [comment]
This is regarding stepper! the help-center will go through a call for testing first ( PCYsg-7T2-p2 ).

**Comment by escapemanuele** [comment]
I was totally into the help center, sorry for misreading 😆

**Comment by enejb** [comment]
Can we add a bit more info to this PR? 
What is a stepper? Why does it need to be production? 

As someone that is not familiar with this project, it is hard to know what is going on here without digging more into the code.

So any link to a P2 or previous PRs would be really helpful here.  :)

**Comment by alshakero** [comment]
Hi @enejb that's totally fair! Updated the PR.

**Comment by enejb** [comment]
Thanks, @alshakero, I appreciate this 🙇

**Pull request merged**
