### PR TITLE
Domain management: Inline status notice

### PR DESCRIPTION
**Pull request by zaguiini**
Related to p58i-fm0-p2#comment-59166.

## Proposed Changes

| Desktop | Mobile |
| --------- | ------ |
| image | image |

## Testing Instructions

Check that the CTAs are showing to the right of the statuses. As a more comprehensive testing method, check the unit tests. They should all pass.

### CODE REVIEW

**Comment by p-jackson** [comment]
@zaguiini  I don't think this is the right approach to inlining the status CTAs. One of the purposes of the redesign is to remove the status banners which increase the row height. p9Jlb4-8BQ-p2#comment-8853 We want everything to look more regularly spaced.

I believe the CTAs @JanaMW27 was referring to (p58i-fm0-p2#comment-59166) were the buttons in the design.

CleanShot 2023-09-18 at 10 41 36@2x

I was sure I'd created a project task to implement this button column (which only appears when one of the status's has a CTA) but alas I can't find it 😭 I must not have created it after all.

**Comment by zaguiini** [comment]
Oh, @p-jackson 😐

To be honest, I don't really like that approach. It squeezes the table even more, and they already have a lot of data...

But I'd like to confirm with @JanaMW27 first anyway, so let's wait. I'll definitely change this if I got this wrong.

**Comment by JanaMW27** [comment]
Yes, the intention is to have the CTA besides the status.
We see an edge case in the above mockup. The most common scenario will be a list without the owner column since we will hide it if all the owners are the same, and that will give more space to the list to feel more balanced.

**Comment by zaguiini** [comment]
Alright @p-jackson @JanaMW27, this is in much better shape now:

image

I will start adding tests and update the testing instructions as there are a lot of cases to try. We'll probably want to rely on automated testing to make sure that the cases are met.

**Comment by mpkelly** [comment]
Tested the missing email and expired plan statuses. It shows the email button first and then a renew button once you fix the email issue ✅ . 

The layout looks acceptable to me on desktop and mobile. On tablet (`768px`), it is squished but passable(?). Or do we want to move the mobile breakpoint? We are showing mobile at `<480px`.  Or maybe we want the status + button to switch from row to column on tablets?

image

**Comment by p-jackson** [comment]
> The layout looks acceptable to me on desktop and mobile. On tablet (768px), it is squished but passable(?). Or do we want to move the mobile breakpoint? We are showing mobile at <480px. Or maybe we want the status + button to switch from row to column on tablets?

Oof, super squishy. The column widths are bit tricky using a `<table>` because we don't have great options for setting responsive widths.

I'm going to attempt a PR which styles the table using CSS grid. I think we want to keep the `<table>` markup because semantically this is correct. But I'm hoping theirs some way we can use the superior CSS grid styling tools so that things rearrange nicer.

**Comment by p-jackson** [comment]
> I'm hoping theirs some way we can use the superior CSS grid styling tools

Looks like it could be possible with `display: contents`!

https://css-tricks.com/get-ready-for-display-contents/

**Review by p-jackson — APPROVED** [review]
😮‍💨 Big change!

Thanks for getting this change in. I quite like the buttons but I know it was quite a bit of rearranging.

The table layout isn't ideal but that's more down to the limitation of styling with `<table>`. I'm going to deploy this change and work on something using CSS grid style.

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/8979619

Thank you @zaguiini for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/8979619).

**Pull request merged**
