### PR TITLE
Fix style of launch confirmation modal for A4A dev sites

### PR DESCRIPTION
**Pull request by candy02058912**
Fixes https://github.com/Automattic/dotcom-forge/issues/9602

## Proposed Changes

* Use Core's Modal: https://wordpress.github.io/gutenberg/?path=/docs/components-modal--docs

| Screen | Before  | After |
| :-------------: | :-------------: | :-------------: |
| Mobile |   | |
| Desktop |   | |

Related discussion: p1731332571284379/1730421945.626839-slack-C9EJ7KSGH

## Why are these changes being made?

* Consistency in Dotcom UI

## Testing Instructions

* Create a new development site in A4A
create a dev site@2x
* Go to /settings/general/:site
* Click on Launch Site
launch site@2x
* Check the style for the modal on mobile/desktop

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Review by matt-west — CHANGES_REQUESTED** [review]
I think we should continue to use Core’s `<Modal>` component here as our goal is to move to using these components across all of Dotcom.

We can remove the [CSS override](https://github.com/Automattic/wp-calypso/blob/1883884dcee66b3fdd25214045d3fb816f769344/client/sites/settings/site/visibility/styles.scss#L24) that’s causing the issue on mobile and set the `size` prop on `<Modal>` to `medium` instead. ([Storybook](https://wordpress.github.io/gutenberg/?path=/story/components-modal--default&args=size:medium))

**Comment by candy02058912** [comment]
@matt-west I've updated the Screenshot in the PR description.

**Review by matt-west — APPROVED** [review]
Looks good! Thanks for making those changes @candy02058912

**Review by p-jackson — APPROVED** [review]
lgtm

**Pull request merged**
