### PR TITLE
Upgrade Babel to version 7.0.0 beta 53

### PR DESCRIPTION
**Pull request by jsnajdr**
Also removes the `stage-2` preset (it's going to be removed from Babel soon) and replaces it
with explicitly configuring the plugins we need:
- `@babel/plugin-proposal-export-namespace-from`
- `@babel/plugin-syntax-dynamic-import`
- `@babel/plugin-proposal-class-properties`

That's not strictly necessary for this particular version, but makes us future-proof.

**Trouble with `package.json`**
Currently, this PR fails to transpile files in `client/extensions` and in other directories where there is a `package.json` file.

Why? This version of Babel tries to find appropriate Babel config for the file and goes up the directory chain to find one. But it stops at "package boundary", i.e., when it finds a `package.json`. Files in `client/extensions/woocommerce` and other dirs are therefore transpiled with empty Babel config -- the root one is not loaded.

See @hzoo's blog post and @loganfsmyth's [Babel PR](https://github.com/babel/babel/pull/7358) to learn the rationale behind that change.

There are several solutions for that:

**Remove our `package.json`s**
One set of use cases is to specify a different index file from the default one, like in our [checkout](https://github.com/Automattic/wp-calypso/blob/master/client/my-sites/checkout/checkout/package.json) module. These are trivial to remove -- just rename `checkout.jsx` to `index.jsx` and remove the `package.json`. Creating these files probably seemed useful back in 2015, but nowadays we never create new ones.

Another set of use cases are extensions. Here we use `package.json` to specify Calypso specific options like `env_id` or `section`. @coderkevin What if we stopped using `package.json` name and started using e.g. `calypso.json`? The extensions are not NPM packages.

**Have each extension have their own Babel config**
As proposed in https://github.com/babel/babel/pull/7358#issue-168100550, each extension could have its own `babelrc.js` or a `babel` field in `package.json`:
```js
{ extends: "../../../.babelrc.js" }
```
Or extract the Babel config into a Calypso preset package and load it from multiple places.

This is a good solution if Calypso extensions were ever published as standalone NPM packages. Then having its own semi-independent Babel config is a good idea.

**The "see the next point" solution**
The https://github.com/babel/babel/pull/7358#issue-168100550 comment mentions "see the next point" as a second solution, but I don't understand what it means. Can our problem be solved by renaming the config file to `babel.config.js` or with the `overrides` config key? Could @hzoo or @loganfsmyth help us?

### CODE REVIEW

**Comment by hzoo** [comment]
Real quick: ya if you have a monorepo type setup we recommend you use a `babel.config.js` file like the Babel monorepo does, and you can use overrides for it as well: https://babeljs.io/blog/2018/06/26/on-consuming-and-publishing-es2015+-packages#selective-compilation-with-overrides. Basically instead of trying to lookup the babelrc per file, it always resolves to the `babel.config.js` file. Overrides is only if you want a different config for a different path.

**Comment by jsnajdr** [comment]
I solved the `package.json` problem by renaming the config file to `babel.config.js`. Thanks @hzoo for the tip: I didn't realize that the lookup behavior is different for `.babelrc` and `babel.config.js`.

I also had to patch the tests for our custom plugins (`babel-lodash-es` and `babel-plugin-transform-wpcalypso-async`) to set explicitly the `configFile: false` option on the `@babel/core` `transform` function: we want to load only the one tested plugin, not the whole configuration.

The PR is not ready for review.

**Comment by jsnajdr** [comment]
Oops, there is something wrong when building Calypso as part of wp-desktop -- that's for the morning to solve.

**Comment by jsnajdr** [comment]
Current status: depends on wp-desktop being upgraded first (Automattic/wp-desktop#477)

**Comment by coderkevin** [comment]
> @coderkevin What if we stopped using package.json name and started using e.g. calypso.json? The extensions are not NPM packages.

Is this still needed? It could probably be done.

**Comment by gziolo** [comment]
I'm not sure what is the context here, but Babel 7 is quite flexible. Some examples how you can prevent loading the default `babel.config.js` file:

https://github.com/WordPress/gutenberg/blob/master/bin/packages/get-babel-config.js#L10-L12
```js
const { options: babelDefaultConfig } = babel.loadPartialConfig( {
	configFile: '@wordpress/babel-preset-default',
} );
```

https://github.com/WordPress/gutenberg/blob/master/packages/babel-plugin-import-jsx-pragma/test/index.js#L13-L19
```js
const { code } = transformSync( source, {
	configFile: false,
	plugins: [
		'@babel/plugin-syntax-jsx',
	],
} );
```

**Comment by ockham** [comment]
> Current status: depends on wp-desktop being upgraded first (Automattic/wp-desktop#477)

@jsnajdr Does this mean that other projects that import Calypso (as a git submodule or otherwise) are also blockers to this PR? There's at least one more project I'm aware of that does that, https://github.com/Automattic/woocommerce-services ([see](https://github.com/Automattic/woocommerce-services/blob/11f375721f0e1d7cda879ffef7ae776e75430a73/package.json#L107)).

**Comment by ockham** [comment]
Rebased.

**Review by ockham — APPROVED** [review]
I smoke-tested various sections, including an extension (WP Job Manager) and SSR (Theme Showcase). Everything seems to work fine. Code looks also good.

I added one [caveat](https://github.com/Automattic/wp-calypso/pull/26020#issuecomment-406347881). Other than that, I think this should be good to merge :+1:

**Comment by ockham** [comment]
Ohh that's because of the automation bot :roll_eyes:

**Comment by blowery** [comment]
Circle is approaching back up. Tickling the badges to get tests to re-run.

**Comment by ockham** [comment]
I assume the desktop build failure is expected (complainging about spread object syntax, which IIRC is ES7) and will be fixed by https://github.com/Automattic/wp-desktop/pull/477, so wie'll have to run CircleCLI again after merging that.

**Comment by gziolo** [comment]
I see there is already `beta.54` :)

**Comment by jsnajdr** [comment]
> Does this mean that other projects that import Calypso (as a git submodule or otherwise) are also blockers to this PR?

@ockham It depends.

**Before Babel beta 53 upgrade:**
wp-desktop's `electron-main` bundle (the server) is built with `babel-loader` that has no configuration. There is no Babel config file in the wp-desktop repo and therefore Babel doesn't do any transpilation. It's an overengineered `cat` :) All sources files in the `desktop` directory are ES5 that Babel understands without any syntax plugins and Node can execute as-is, so it's no problem.

Then some files in the `desktop` directory require modules that are resolved into `calypso/server`. Because there is a `calypso/.babelrc.js` file and Babel searches for the closest config for each transpiled file, files in the `calypso` submodule *are* transpiled with the Calypso Babel config. Everything works.

**Plot twist:**
This PR renames `.babelrc.js` file to `babel.config.js`. That's a novelty introduced in beta 53 that wasn't in 44. The rules for this file are different: it's supposed to be always in the root of the repo and is *ignored* when Babel does the "closest config to the currently transpiled source file" search.

When building wp-desktop with `calypso` submodule that has this PR applied, Calypso sources are transpiled with no Babel config.

That crashes the build because one of the `calypso/server` files uses the object rest spread syntax that Babel can't parse without the corresponding plugin.

**Solution:**
Create a `babel.config.js` file for wp-desktop. This config file uses the `@babel/env` preset with `target: electron` and Calypso server files will be transpiled with this config. It understands object rest spread syntax and everything else that's needed. Build starts working again.

The extra benefit is that now Calypso sources are not transpiled with the browser target that includes compatibility with IE11, but with an Electron target which allows a lot of new syntax to be left untranspiled, because the Node and Chromium bundled in Electron support it.

**What about Woocommerce Services?**
They already do what https://github.com/Automattic/wp-desktop/pull/477 introduced to wp-desktop: their `webpack.config.js` includes a Babel config that's used to transpile the Calypso sources, and has a `babelrc: false` flag that instructs Babel to ignore Calypso's `.babelrc.js`. So renaming the Calypso config file doesn't matter.

The fact that `woocommerce-services` pulls in Calypso as a NPM dependency instead of a Git submodule also doesn't matter: in both cases, Calypso is some subdirectory that Webpack is configured to include in its module resolution path.

**Comment by jsnajdr** [comment]
> I see there is already beta.54 :)

@gziolo It doesn't introduce anything groundbreaking, se we can stay on 53 for a while. The change from 44 to 53 is very different: it introduces the `babel.config.js` file, moves features around in the `env` preset, as some proposals got shipped in ES2018... That's major stuff.

**Comment by jsnajdr** [comment]
I restarted the WP Desktop check and it's all 💚 now! :tada:

**Comment by jsnajdr** [comment]
> Is this still needed? It could probably be done.

@coderkevin It's not urgent: the trouble with `package.json` files was solved by renaming the Babel config file from `.babelrc.js` to `babel.config.js`. The lookup rules are very different for both config types.

**Pull request merged**
