### PR TITLE
Increase click/tap target size for crop handles.

### LINKED ISSUE #8065: Image Editor Crop: make handles larger
While working on adding touch support to our Image Editor, I discovered that the Image Editor Crop handles are quite small and I'm having difficulties dragging them. This is what I have in mind:

selection_154

Instead of dragging a handle, I usually drag the image cropper or just nothing happens when I'm trying to drag the handle.

We should make the handles larger on mobile (ie touch) devices.

### PR DESCRIPTION
**Pull request by obenland**
Makes it easier to drag the crop handles in the Image Editor.

Before:
screen shot 2016-09-26 at 12 06 58 pm

After:
screen shot 2016-09-26 at 12 07 16 pm

Fixes #8065.

### CODE REVIEW

**Comment by gwwar** [comment]
Very clever 😄 The code here looks good. @drw158 do you like how this feels?

**Comment by lamosty** [comment]
Nice work @obenland!

I tested it with my prototype touch-enabled image editor and it works just fine. We can always increase it with this method afterwards if needed. 

LGTM :ship:

**Comment by drw158** [comment]
I'm getting an error on the live branch, so I'll just assume that it's great! Thanks!

**Pull request merged**
