### PR TITLE
Plans grid design tweaks

### LINKED ISSUE #43228: Gutenboarding: Minor fixes to plans page
Mocks:

**Desktop**
image
image

**Tablet 3 columns**
image

**Tablet 2 columns**
image

**Mobile**
image
image

**Plan states**
image

Changes:

- [ ] All features in the highlight section (top part) should have ticks next to them
- [ ] Plans stack instead of having horizontal scroll. On mobile the plans are in an accordion.
- [ ] There's no more Plan selection state. Clicking a plan proceeds
- [ ] First item should be the domain feature (see plan states section underneath)
- [ ] There are some minor spacing changes. Check Figma for the exact measurements.
- [ ] Show the detail comparison list by default. No more hiding behind a button
- [ ] Add CTAs at the bottom of the detail grid

### PR DESCRIPTION
**Pull request by alshakero**
Duplicate of https://github.com/Automattic/wp-calypso/pull/43277 that was merged too early by mistake. 

This PR fixes: https://github.com/Automattic/wp-calypso/issues/43228

#### Changes proposed in this Pull Request

- [x] All features in the highlight section (top part) should have ticks next to them
- [x] Plans stack instead of having horizontal scroll. On mobile the plans are in an accordion.
- [x] There's no more Plan selection state. Clicking a plan proceeds
- [x] Show the detail comparison list by default. No more hiding behind a button
- [x] First item should be the domain feature ([see plan states section underneath](https://github.com/Automattic/wp-calypso/issues/43228))
- [x] Add CTAs at the bottom of the detail grid
- [x] There are some minor spacing changes. Check Figma for the exact measurements.
- [x] Implement "Expand all plans" on mobiles

#### Testing instructions

Compare against every tick from above.

### CODE REVIEW

**Comment by dubielzyk** [comment]
This looks amazing. Such a great job! 👏🏼 Here's a few very minor things:

- [ ] On mobile, [make the "other plans"](https://d.pr/i/oazHVN) font-size: 14px instead of 16px and the plan title should be bold like in the feature section.
- [ ] Let's make sure the domain feature lines up vertically centered with the tick. [Details](https://d.pr/i/6e0N3k)
- [ ] Let's make `.plan-item__details .plan-item__summary .plan-item__price` have margin-bottom 8px instead of 16px
- [ ] Popular badge should have the height of 24px
- [ ] Then let's fix the smaller desktop screen grid horizontal scrolling like mentioned on Slack. [Video](https://d.pr/v/MX6tYP)

**Comment by alshakero** [comment]
@dubielzyk this is ready for another round.

**Review by wp-desktop — DISMISSED** [review]
WordPress Desktop CI Failure (ci/wp-desktop): @alshakero please re-try this workflow ("Rerun Workflow from Failed") and/or review this PR for breaking changes. Please also ensure this branch is rebased off latest Calypso master.

**Review by dubielzyk — CHANGES_REQUESTED** [review]
- [x] Top checkmark [looks a bit weird](https://d.pr/i/jJmJw7)
- [x] The grid is almost there. The [padding to the left is a bit weird though](https://d.pr/i/vo4eOi). Can we make it edge-to-edge when it's mobile with inside padding so that it doesn't look as cut off? It's fine to cut off on the edge though. Again, the way that they do it on wordpress.com/pricing is really nice.

**Comment by alshakero** [comment]
@dubielzyk I think everything is in order now!

**Review by dubielzyk — APPROVED** [review]
👏🏼 Champ!

**Comment by amamujee** [comment]
Thanks y'all!

**Pull request merged**
