### PR TITLE
Adds root components for Offer Reset plan redesign pages

### PR DESCRIPTION
**Pull request by ChaosExAnima**
#### Changes proposed in this Pull Request

* Adds a new folder where components can be wired together.
* Creates the following components: `SelectorPage`, `DetailsPage`, and `UpsellPage`.
* Provides helper function to add paths.
* Starts typing.

#### Testing instructions

* Review code- this isn't loaded anywhere yet. It is intended as a stub for future work.

Fixes 1169247016322522-as-1187480522520329.

### CODE REVIEW

**Comment by rcanepa** [comment]
@ChaosExAnima where do you think we should store the state of the product type filter? The duration filter state lives in the URL, should we put the state of the other filter in Redux?

**Comment by ChaosExAnima** [comment]
> @ChaosExAnima where do you think we should store the state of the product type filter? The duration filter state lives in the URL, should we put the state of the other filter in Redux?

I think it doesn't need to be Redux, it can rely on `useState` as I don't see a need to directly link to a filter like that, and I don't think it needs to be accessible via React Provider like Redux can be.

**Comment by nsakaimbo** [comment]
Desktop build is failing with an `EPIPE` error that is likely unrelated to this PR. It's an out-of-memory error (this has been an issue for some time and for some reason we've been seeing it a little more frequently over the past day or so - looking into it).

**Comment by ChaosExAnima** [comment]
> Desktop build is failing with an `EPIPE` error that is likely unrelated to this PR. It's an out-of-memory error (this has been an issue for some time and for some reason we've been seeing it a little more frequently over the past day or so - looking into it).

@nsakaimbo - Are we good to dismiss and merge, then?

**Comment by nsakaimbo** [comment]
> Are we good to dismiss and merge, then?

Thanks for checking - I think you should be fine to land these changes!

**Pull request merged**
