### PR TITLE
General: Replace Open Sans with system UI fonts.

### PR DESCRIPTION
**Pull request by mattmiklic**
I've had conversations with a few Automattic designers about switching from Open Sans to system fonts over the course of several months. I'm opening this PR to make the discussion public and consolidate it into one thread.

### Why system fonts?
- It's faster. The three weights and two styles of Open Sans add up to 64 KB of extra weight. 
- It's more native. This approach displays our UI text in the user's operating system's standard font for UI elements. Calypso feels more like a native app as a result.
- It further emphasizes that UI text is in the sans-serif face (now a system font), while the user's content is in our custom serif typeface.
- Open Sans is no longer necessary. I originally introduced it into Core via MP6 because there were not good system fonts common to all platforms at the time. In the years since, Windows, Android, OS X, iOS, Firefox OS, and various flavors of Linux have all gotten their own (good) system UI fonts.
- Users in many languages (those in scripts other than latin) already see system fonts; there is no version of Open Sans for them.
- Combined with #2766 this would remove the external dependency on Google Fonts entirely.

### Which fonts?
I based this on the approach <a href="https://www.smashingmagazine.com/2015/11/using-system-ui-fonts-practical-guide/#details-of-approach-b">developed by Medium</a>, with some changes. The linked article provides more detail, but my list now includes:

- `-apple-system` for Safari (iOS & OS X) and Firefox OS X,
- `BlinkMacSystemFont` for Chrome OS X,
- `Segoe UI` for Windows and Windows Phone,
- `Roboto` for Android, Chrome OS, Firefox OS,
- `Oxygen-Sans` for KDE,
- `Ubuntu` for Ubuntu,
- `Cantarell` for GNOME,
- `Helvetica Neue` for pre-El Capitan versions of OS X, and
- `sans-serif`, the standard fallback.

### Known issues?
From the article linked above:

>In Firefox on Mac OS X, San Francisco has tighter letter spacing than on Safari and Chrome.
> It doesn’t render Lucida Grande on pre-Yosemite versions of Mac OS X, falling back to Neue Helvetica. And it might not match the correct font on less popular operating systems or more complicated configurations.

The Firefox issue is a minor concern and we'd want to look at it in more detail to determine whether the tighter spacing hampers legibility in a meaningful way. The issue on pre-Yosemite Macs is not a concern to me, since it falls back to Helvetica Neue.

### What needs to be done?
- [x] Test in GNOME (Cantarell font)
- [x] Test in KDE (Oxygen font)
- [x] Test in Ubuntu (Ubuntu font)
- [x] Test in Windows XP
- [x] Test in Firefox/OS X for potential legibility problems 
- [x] Test in OS X 10.9 (Helvetica Neue system font)
- [x] Review Jetpack-specific screens
- [x] Review Business plan-specific screens
- [x] Review Checkout process screens
- [x] Review Help interface screens

Please take a look and if you find any spots where the replacement looks problematic, add screenshots in the comments below.

Some screenshots are collected in this Cloudup gallery: https://cloudup.com/c6v0htMZ25x

### CODE REVIEW

**Comment by kellychoffman** [comment]
Wow, very cool. Took it for a quick spin and the two issues I see have to do with font size and inputs. 

Widows on plugins and domains page at its widest width (minor)
Before:
screen shot 2016-02-02 at 5 36 24 pm
After:
screen shot 2016-02-02 at 5 36 46 pm
screen shot 2016-02-02 at 5 44 33 pm


Input padding is a bit off:

Before:
screen shot 2016-02-02 at 5 37 20 pm
After:
screen shot 2016-02-02 at 5 36 37 pm

**Comment by alternatekev** [comment]
It's pretty jarring to me to see it the first time but I could definitely get behind it, given the reasoning.

**Comment by mattmiklic** [comment]
Thanks Kelly! I think we can address the widows with non-breaking spaces, and the input padding issue should probably be addressed on its own (long translations would have the same effect, I'd think?) but it brings up a good point; I'm sure there will be things to fix that would be required by this change, and I'm not sure whether it would be best to try fix them all in one big PR or break them apart somehow; would love some ideas there.

**Comment by mattmiklic** [comment]
Just confirmed the same input padding issue is present in most languages other than English, so I think that one could be addressed separately.

**Comment by mattmiklic** [comment]
Made the following changes this evening:

- Removed Fira Sans -- on the Firefox OS simulators I was able to test, the Roboto font is included and because it appears first in the font stack, it's chosen first. Because of the tiny number of Firefox OS users I think Roboto is an acceptable choice there.
- Removed Droid Sans -- older versions of Android will default to this anyway with the `sans-serif` keyword.
- Changed `Oxygen` to `Oxygen-Sans` -- testing on a fresh install of Fedora 23 KDE the system font is named `Oxygen-Sans`; the existing `Oxygen` declaration wasn't working, so it was falling back to Cantarell.

**Comment by kellychoffman** [comment]
I think that if anything is breaking due to this change, the fixes should be part of this PR.

**Comment by mattmiklic** [comment]
For anything specific to the font change we'll include in this PR. I created a new issue, #3050, for the Custom Address button problem above because it needs to be fixed regardless of whether we make the switch to system fonts.

**Comment by melchoyce** [comment]
Any chance we could get a gallery of screenshots from different devices? 

Looking at it on Yosemite, the bolds are feeling _really_ bold. I wonder if there's anything we can do to adjust font-weight based on OS, or if we just need to accept the inconsistencies.

**Comment by mattmiklic** [comment]
> Any chance we could get a gallery of screenshots from different devices?

Yep! I'm collecting them in this Cloudup gallery: https://cloudup.com/c6v0htMZ25x

> Looking at it on Yosemite, the bolds are feeling really bold. I wonder if there's anything we can do to adjust font-weight based on OS, or if we just need to accept the inconsistencies.

Would love to get some screenshots of Yosemite -- I tried to set up a VM to test it last night, then realized that Apple has pulled the links to download all previous versions of OS X, so I couldn't get it running.

The difference is that we specify font-weight 600 (medium/semibold), but Yosemite's system font, Helvetica Neue, doesn't have a 600 weight, so it gets bumped up to 700 (bold). I'm not sure if I'd say we should try to work around it, since it's consistent with what the user would see in a native app. Though, t's possible that we're using bold in so many places that the effect is more pronounced in Helvetica Neue.

**Comment by melchoyce** [comment]
Here are some Yosemite shots: https://cloudup.com/cz-HyIPzGNw

Let me know if there's any other screen you'd like.

Helvetica Neue doesn't have 600, but it does have a nice 500 weight that looks way better than 700: 

500:
screen shot 2016-02-04 at 1 42 25 pm

700:
screen shot 2016-02-04 at 1 42 37 pm

500:
screen shot 2016-02-04 at 1 43 32 pm

700:
screen shot 2016-02-04 at 1 43 40 pm

**Comment by drw158** [comment]
I checked every view I could think of on my machine (Chrome).

I think this is a good decision: :+1:

**Comment by shaunandrews** [comment]
I ran though the upgrade flow a few times in Chrome, Safari, Firefox (Mac/PC), and Edge—all latest. All looks wonderful.

**Comment by mattmiklic** [comment]
After doing some testing of RTL scripts I decided to revert my changes to the $sans-rtl styles in this branch. On the Mac, the default system font for Arabic and Urdu is Geeza Pro and for Hebrew it's Arial; these fonts may introduce changes that I'm not able to accurately judge, so I think we should save them for a separate issue.

With this change, this branch only affects languages that saw Open Sans before. Languages in all other scripts will continue using the existing fallback fonts.

**Comment by mattmiklic** [comment]
Well, tried to rebase and made a big mess. Will try to get some help sorting this out on Monday.

**Comment by mattmiklic** [comment]
Attempted testing with an Android 2.3 device today; Calypso does not work on the device (doesn't make it past the W logo screen).

**Comment by mattwiebe** [comment]
Another perf advantage here is that, on any screen lacking user content (Merriweather), the font won't even be fetched since nothing is set in it, further speeding up performance.

**Comment by mattmiklic** [comment]
Took a look at the letterspacing issue in Firefox mentioned in the linked article above. While it's present in the current version (44) and does affect legibility in some places, the beta version of Firefox (45) fixes the issue. Since it's scheduled for release in a few weeks I think that one is taken care of.

**Comment by mattmiklic** [comment]
Updated this branch since we're loading a local version of Merriweather after merging #2766.

**Comment by mattmiklic** [comment]
I've been doing some testing across devices to narrow down any issues that this change might cause. The most prominent one I've found is with buttons. In testing, I've discovered that our existing button designs are not exactly consistent with regard to size; buttons with icons are 1px taller than buttons without, and their text does not align to the same baseline:

alignment

When we switch to system fonts instead, the issue is actually resolved entirely on iOS/OS X, in the SF typeface. All buttons are the same height:

ios-sf

Unfortunately on Android, in the Roboto typeface, the problem is amplified:

android-roboto

So my question is -- do we need a workaround for Android for this issue? If we do, how should we add styles just for when that typeface is used?

Here is a zoomed-out comparison of Open Sans vs. system fonts on buttons, both in Android and iOS:

buttons 2

**Comment by folletto** [comment]
> So my question is -- do we need a workaround for Android for this issue? If we do, how should we add styles just for when that typeface is used?

I think we do (it might be some form of forcing the height of the button so it's not a specific platform hack). But it's something unrelated to this PR imho since it's something that already happens.

**Comment by mattmiklic** [comment]
> But it's something unrelated to this PR imho since it's something that already happens.

That is what I'm thinking as well, since it's the same basic issue at play, though I think it may be more visually apparent in Roboto because of the baseline shift.

**Comment by jasmussen** [comment]
**About that 1px button height issue**, I think it's already been said in various ways by Davide and yourself MT:

> the button height shouldn't depend on the font size (the fact it "fixes" the problem shows the issue is already there).

This font change has made it clear our buttons have a height bug that needs fixing.

I'd personally be for merging in as-is, with the 1px button offset issue, and then fixing the button height issue in a separate PR. I haven't looked deeply at the code, but it feels to me like some tweaks to line-height and padding could fix this right up in a more permanent way. 

But alternately, yeah sure we can make a Roboto specific workaround, we just have to remember to remove that again when the button height bug is fixed properly.

**Comment by mattmiklic** [comment]
> I'd personally be for merging in as-is, with the 1px button offset issue, and then fixing the button height issue in a separate PR. I haven't looked deeply at the code, but it feels to me like some tweaks to line-height and padding could fix this right up in a more permanent way.

Thank you for weighing in @jasmussen. I think you're right, both about the solution (fixing button heights altogether) and the timing (that it can happen independently of this PR). I think that makes sense, since it's not a new issue, and PRs are meant to be kept as small as possible.

**Comment by mattmiklic** [comment]
I took a look through the rest of the sections I hadn't tested yet (options for a Jetpack site, a Business plan, and the checkout process. Did not find any issues.

I also got a chance to look at it in Yosemite, with the Helvetica Neue system font. My opinion is that the 700 bold weight (mentioned in comments above) isn't so overly bold that it causes any problems. Especially given that the number of users on 10.10 should continue to drop (it's about tied with 10.11 now, according to Google Analytics). I think it would be OK to add some adjustments for 10.10, but I think  it should happen in a separate issue, since we'd want to keep track of them and remove them later once they're no longer needed.

So, that said, I think this is ready, unless anyone has serious reservations.

**Comment by mtias** [comment]
Small one (a bit off vertically):
image

Tooltips in editor toolbar could use some small padding adjustments:
image

This may also be just me, but I think uppercase buttons look a bit suboptimal now:
image

Should we also switch all body text to Merriweather? Devdocs seems a bit harder to read:
image

Reader "Likes" button needs some adjustment:
image

(The above renders fine in the Reader, it just looks buggy in devdocs, so perhaps there's some cleanup to do in the component.)

**Comment by mattmiklic** [comment]
Thanks for taking a look, @mtias!

> Small one (a bit off vertically):
> Tooltips in editor toolbar could use some small padding adjustments:

These were pretty simple to take care of. The tooltip text was already sitting a bit low in the tooltip-inner container because of the inherited styles from tinymce. Here are Mac, Chrome OS (used to get the tooltip, Android will look the same), and Windows screenshots:

mce

> This may also be just me, but I think uppercase buttons look a bit suboptimal now:

We could adjust the button weight down to 500, from 600. On OS X and iOS, 500 and 600 are unique weights, so it will be slightly thinner. On Android and Chrome OS, there is not a medium/semibold weight of Roboto available on the web, so it would drop from bold to regular weight. On Windows, there would be no change, as 500 is rendered the same as 600, in the semibold weight of Segoe.

Mac Before and After:
osx-buttons

Android/Chrome OS Before and After:
android-buttons

Windows (no before and after, since there's no change):
windows-buttons

> Reader "Likes" button needs some adjustment:

It looks like the icon shifts down by 1px when using system fonts, but, as you mentioned, it's only happening in devdocs. In the reader it's fine, so I think that could be addressed as a separate issue.

screen shot 2016-02-18 at 3 22 23 pm

screen shot 2016-02-18 at 3 22 02 pm

**Comment by apeatling** [comment]
This looks good to merge :+1:

**Comment by mtias** [comment]
@apeatling we'd need to align with the rest of WP.com, masterbar, etc, right? At least the iframed customizer I guess.

**Comment by folletto** [comment]
> we'd need to align with the rest of WP.com

Yeah:

1. Front-end masterbar
2. Customizer
3. Action Bar

**Comment by apeatling** [comment]
> @apeatling we'd need to align with the rest of WP.com, masterbar, etc, right? At least the iframed customizer I guess.

Yes, we should do a search and replace for Open Sans. I think we can merge this and tackle that next. /cc @mattmiklic

**Comment by kellychoffman** [comment]
:tada:

**Pull request merged**
