### PR TITLE
Checkout: Display and record errors when adding products to the cart fails

### PR DESCRIPTION
**Pull request by sirbrillig**
#### Changes proposed in this Pull Request

When loading checkout, it's possible to add items to the cart directly from the URL (plans, non-plan products, or renewals). This mechanism has several places that it can fail, but none of those failures generate an error that the user can see. This is most noticeable when the cart is otherwise empty because then one of these failures will result in a silent redirect to the plans page with no explanation.

This PR displays those errors to the user instead. It also prevents the redirect if an error is being displayed (just like other errors).

In addition, this PR records those errors to Tracks and to Logstash so they can be examined later.

(As a side effect of some of the refactoring here, `usePrepareProductsForCart` now will never change its returned products once they've been created. This should have no noticeable effect but is more efficient and should help with other hooks that depend on its return value.)

Screen Shot 2020-09-10 at 6 29 50 PM

Screen Shot 2020-09-10 at 6 31 55 PM

Fixes https://github.com/Automattic/wp-calypso/issues/45521

#### Testing instructions

- Visit calypso and turn on analytics debugging by typing `localStorage.setItem('debug', 'calypso:analytics')` in your console and then reloading the page.
- Visit checkout with a URL like http://calypso.localhost:3000/checkout/example.com/personal and verify that the plan gets added to your cart correctly.
- Visit checkout with a URL like http://calypso.localhost:3000/checkout/example.com/domain-mapping:whatever.com and verify that the product gets added to your cart correctly.
- Visit checkout with a URL like http://calypso.localhost:3000/checkout/example.com/abcd (`abcd` is a non-existent product alias).
- Verify that you see an error message displayed about failing to find the requested product.
- Click to renew an existing product and verify that it gets added to your cart correctly.
- Visit checkout with a URL like http://calypso.localhost:3000/checkout/abcd/renew/10001/example.com (`abcd` is a non-existent product slug).
- Verify that you see an error message displayed about failing to find the requested product.
- Verify that you see a reference to an event like `calypso:analytics Record event "calypso_checkout_composite_products_load_error" called with props` in your console.
- In your browser's devtools network tab, verify that you see a call to the `logstash` endpoint which refers to the same error message you saw on the screen.

### CODE REVIEW

**Comment by sirbrillig** [comment]
🤔  Should we translate these error messages? They should in theory never occur, unless there are bugs or the user types an incorrect URL.

**Comment by fditrapani** [comment]
Just tested this with a non-admin user trying to renew an existing plan and when I tried to go to checkout, I got this error message, which never appeared before, and was redirected back to the plans screen:

image

> 🤔 Should we translate these error messages? They should in theory never occur, unless there are bugs or the user types an incorrect URL.

In this case, I think it might be worthwhile to translate these error messages.

**Comment by sirbrillig** [comment]
Thank you, @fditrapani! That's very interesting for several reasons. Firstly, this PR shouldn't cause or change either of the error messages you're seeing in that screenshot (I believe both of those come from the server and this only adds client-side errors). Secondly, if the cart is displaying any errors, the redirect is designed not to occur (and to remain on the "loading" checkout page).

I'm trying to reproduce what you did. What I tried was this:

- Make a site that has a Premium plan.
- Click to renew the Premium plan and copy the resulting checkout URL for later.
- Add another user to that site as an Editor role.
- As the Editor user, visit the renewal URL I coped above.

Instead of what you saw, I got this:

Screen Shot 2020-09-18 at 7 17 02 PM

I assume I did something differently, though. Can you describe the steps you took?

Also: what is the behavior you see when doing this in production?

**Comment by fditrapani** [comment]
Taking the same steps as you, I saw what you saw for an instant and then was redirected to the plans page. 

> what is the behavior you see when doing this in production?

When I do this in production, I go to the cart then get redirected to the plans page and see that same message as the screenshot I shared.

**Comment by DavidRothstein** [comment]
I see the same results as @fditrapani -- it starts off with checkout loading and the error message displayed there, but then redirects to the plans page and the error message remains.

I see the same behavior for that in production as I do with this diff applied.

**Comment by sirbrillig** [comment]
Thank you! Weird that it doesn't happen to me. In any case it doesn't appear related to this PR so I've made its own issue here: https://github.com/Automattic/wp-calypso/issues/45791

**Comment by sirbrillig** [comment]
> In this case, I think it might be worthwhile to translate these error messages.

Agreed. I've made them translatable strings.

**Review by michaeldcain — APPROVED** [review]
This works as described and LGTM. After merging, can you take a minute to register the new Tracks Event (using the MC tool). 

I did want to note that once Checkout loads with an invalid product (either with the empty cart loading screen or with a cart that already has a valid item) the error message, logstash request, and Tracks event all fire over and over with the shopping cart endpoint polling. I don't think it's a blocker for this PR, and not really an issue for the former case (aside from logging a number of extra requests), but in the latter, it leads to the message being shown again and again while the user is checking out:

https://cloudup.com/cXadRKb2Kl1

**Comment by sirbrillig** [comment]
@michaeldcain I'm glad you saw that! There was a pretty big bug in `useActOnceOnStrings` that I hadn't noticed before. It should be fixed now, if you wouldn't mind trying that particular issue one more time?

**Comment by sirbrillig** [comment]
> After merging, can you take a minute to register the new Tracks Event

🤔 I don't think any of our other events are registered, though perhaps they should be. Perhaps we should create an issue for that so it doesn't get lost, if it's needed.

**Comment by michaeldcain** [comment]
> Perhaps we should create an issue for that so it doesn't get lost, if it's needed.

I think we had one on the old board that kept getting de-prioritized. I was going to start pushing through them, but figured we could help by registering new ones as they're added.

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/4500314

Thank you @sirbrillig for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/4500314).

**Pull request merged**
