### PR TITLE
A4A: update migration offer banners

### PR DESCRIPTION
**Pull request by andrii-lysenko**
Resolves https://github.com/Automattic/automattic-for-agencies-dev/issues/1179#issue-2551204965 and https://github.com/Automattic/automattic-for-agencies-dev/issues/1180

## Proposed Changes

Update offer details as per issue.

## Why are these changes being made?

- We are updating our migration incentives.

## Testing Instructions

Pages to test:
`/overview`
`/marketplace/hosting/`
`/migrations`

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Comment by cleacos** [comment]
The failing E2E tests are unrelated to this PR

**Comment by simonktnga8c** [comment]
We've been asked to add WordPress.com back overnight. @cleacos, Once that copy is updated, feel free to deploy this. I'm working on updating the terms now, and they will be ready soon.

Here's the updated copy to use, please:

> Limited-time offer: Migrate your sites to Pressable or [WordPress.com](http://wordpress.com/) and earn up to $10,000!
>
>From now until the end of 2024, you’ll receive $100 for each migrated site, up to $10,000*. If you’re a WP Engine customer, we’ll also cover any costs of breaking your contract. Full Terms.
>
> * The $10k limit applies to migrations from WP Engine only; it is $3k for migrations from other hosts.

**Review by cleacos — APPROVED** [review]
LGTM!

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/16882956

Some locales (Hebrew, Japanese) have been temporarily machine-translated due to translator availability. All other translations are usually ready within a few days. Untranslated and machine-translated strings will be sent for translation next Monday and are expected to be completed by the following Friday.

Hi @andrii-lysenko, could you please edit the description of this PR and add a screenshot for our translators? Ideally it'd include all of the following strings:
- `Limited time offer: Migrate your sites to Pressable or WordPress.com and earn up to $10,000!`
- `From now until the end of 2024, you’ll receive $100 for each migrated site, up to $10,000*. If you’re a WP Engine customer, we’ll also cover any costs of breaking your contract. {{a}}Full Terms ↗{{/a}}`
- `* The $10k limit applies to migrations from WP Engine only; it is $3k for migrations from other hosts.`
- `From now until the end of 2024, you’ll receive $100 for each migrated site to Pressable or WordPress.com, up to $10,000. If you’re a WP Engine customer, we’ll also cover any costs associated with breaking your contract. {{a}}Full Terms ↗{{/a}}`
- `* The $10k limit is for migrations from WP Engine to Pressable only. For migrations from other hosts the limit is $3k.`

Thank you in advance!

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/16882956).

**Pull request merged**
