### PR TITLE
Streamline "My Sites" nav drawer 

### PR DESCRIPTION
**Pull request by lynnbgriffith**
#### Changes proposed in this Pull Request

This PR supersedes #31742.

We've already merged Material icon support in PR #32364 and expandable sidebar components in #32250.  So this PR is just the actual "My Sites" nav drawer redesign.

#### Testing instructions

* Items in the nav drawer should be shown and hidden based upon the same logic used in the current design.

### CODE REVIEW

**Review by davemart-in — APPROVED** [review]
Looks solid. 👍

**Comment by torres126** [comment]
I can't understand why but it looks like this PR breaks the styling of the ads section badly when navigating to it through the sidebar? 

Screenshot_20190418-235634

This white contrast on mobile is slightly painful too. 

Screenshot_20190419-000026

**Comment by griffbrad** [comment]
@torres126 Thanks for the issue report.  I'm not able to reproduce that issue myself.  Which browser and version are you using when seeing the problem?  Also, just to rule it out, does the problem persist after clearing your browser cache?

**Comment by torres126** [comment]
Chrome 73 on Android. Oddly enough, I actually managed to reproduce it without the new nav drawer as well, not so easily as just clicking the "Earn" link but by refreshing afterwards too. I think this redesign just makes it more noticeable but I don't see how it could affect it, so separate issue for that: #32422 

Since the hover state is a wider issue, granted, extra annoying on the new sidebar nav, I've created #32423 for that! :)

**Pull request merged**
