### PR TITLE
Better click target for domain management three-dot menu

### PR DESCRIPTION
**Pull request by jordesign**
#### Proposed Changes

* Add padding to ellipsis/three-dot menu to increase the click area

Screen Shot 2023-01-04 at 2 14 45 pm

#### Testing Instructions

* Switch to a site with a custom domain
* Go to Upgrades > Domains to see the domain list
* Test that the ellipsis/three-dot menu is 

#### Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

Related to #56230

### CODE REVIEW

**Comment by jordesign** [comment]
pinging @Automattic/dotcom-create-design @Automattic/dotcom-manage-design  for a gut check on the UI/UX of this change

**Review by delputnam — COMMENTED** [review]
Looks good from a domains aspect. Thanks!

**Comment by ollierozdarz** [comment]
@jordesign looks good to me provided it doesn't affect the `100 Mailboxes` text.

**Comment by jordesign** [comment]
@ollierozdarz the '100 mailboxes' text does wrap - but only the same way it already does in product 👍

**Pull request merged**
