### PR TITLE
Subscription Management: Replace `SiteIcon` component and fix its styling

### LINKED ISSUE #78923: Subscription Management: All round site icons should be square.
All round site icons should be square on all Subscription Management pages.

This is because site icons are supposed to be square, and round icons refer to user avatars.

### PR DESCRIPTION
**Pull request by ivan-ottinger**
Fixes https://github.com/Automattic/wp-calypso/issues/78923.

## Proposed Changes

* make all Site icons in Subscription Management squared
* remove the custom Subscription Management's `SiteIcon` component and replace it with the one from `calypso/blocks/site-icon`
* add `alt` attribute to the `SiteIcon` component
* style the default icon using transparent background and `--color-neutral-100` color - to match existing default site icon used in the Reader
* fix styling on the Pending tab

| Before | After |
|--------|--------|
| Markup on 2023-07-14 at 10:53:28 | Markup on 2023-07-14 at 10:58:59 |
| Markup on 2023-07-14 at 10:54:20 | Markup on 2023-07-14 at 10:58:18 |
| Markup on 2023-07-14 at 10:56:45 | Markup on 2023-07-14 at 10:57:38 |
| Markup on 2023-07-14 at 11:01:48 | Markup on 2023-07-14 at 11:00:26 | 

## Testing Instructions

1. Check out the PR branch and build the app.
2. Make sure your WordPress.com and External users are subscribed to some sites / comments.
3. With the WordPress.com user navigate to http://calypso.localhost:3000/read/subscriptions and confirm all site icons are squared. If the site doesn't have a custom icon, the default dark globe icon should be displayed instead.
4. With the External user navigate to http://calypso.localhost:3000/subscriptions/sites and http://calypso.localhost:3000/subscriptions/comments and confirm all site icons are displayed correctly there as well. You can review the Pending tab (http://calypso.localhost:3000/subscriptions/pending) as well.

ℹ️ To test with the External user on local Calypso, the "subkey cookie dance" is necessary. 🙂 

## Pre-merge Checklist

- [x] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [x] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

**Comment by ivan-ottinger** [comment]
This quick PR is now ready for review.

**Comment by mashikag** [comment]
It would be ideal if we could all use `SiteIcon` from `calypso/blocks/site-icon`. This would help us to avoid such situations, where some part of calypso displays site icons differently to another part of calypso.

**Comment by ivan-ottinger** [comment]
> It would be ideal if we could all use SiteIcon from calypso/blocks/site-icon. This would help us to avoid such situations, where some part of calypso displays site icons differently to another part of calypso.

Thanks, Maciej. I am going to take a look at this now.

**Review by TimBroddin — APPROVED** [review]
All site icons render as squares, and the code looks great!

**Pull request merged**
