### PR TITLE
Playground: Replace jsx-to-string

### PR DESCRIPTION
**Pull request by blowery**
[jsx-to-string](https://github.com/grommet/jsx-to-string) does not seem to be maintained. Switch to ~[pretty-format](https://github.com/facebook/jest/tree/master/packages/pretty-format)~ [react-element-to-jsx-string](https://github.com/algolia/react-element-to-jsx-string) which is.

jsx-to-string has a number of dependencies (immutable, react, fbjs) that are out of sync with the rest of our dependencies. 

#### Testing instructions

* Load the playground in devdocs. Components should appear as they usually do.
* After `npm start` you should no longer see duplicate warnings for `react` and `fbjs`. There's still one for `immutable` but it should just be two versions instead of three.

### CODE REVIEW

**Comment by flootr** [comment]
While the initial formatting of components seem to work fine after adding another component e.g. an accordion the formatting looks quite different to what is currently on wpcalypso. Formatting itself shouldn't be much of an issue but it also shows a SyntaxError in the code editor:

```
SyntaxError: Unexpected token (102:13) 98 : forceExpand={false} 99 : initialExpanded={false} 100 : onToggle={[Function]} 101 : status={ 102 : Object { ^
```

Screenshot 2019-03-27 at 12 30 55

There are also additional properties which aren't added with the current version:

Screenshot 2019-03-27 at 12 33 08

vs.

Screenshot 2019-03-27 at 12 33 13

**Comment by scruffian** [comment]
I turned the Accordion Example into a stateless component, which makes it easier to see what's going wrong here; the problem is that we output `Object{}` instead of just `{}`. I'm not sure if there's a way to stop pretty-format from doing that.

**Comment by blowery** [comment]
Changed out the backing library for [react-element-to-jsx-string](https://github.com/algolia/react-element-to-jsx-string) which seems to have behavior more in-line with what we want.

**Review by belcherj — APPROVED** [review]
Code looks good and everything tests well.

**Pull request merged**
