### PR TITLE
Plugins update manager: Fix button busy state colors

### LINKED ISSUE #88231: FE: Primary button color issue
Image

The Figma says the blue color.
Currently, the primary button color is red, which makes sense compared to the other pages on the same level.

Also, when the button is in a busy state, the busy state has a blue color.

Let decide what is the primary color and fix the busy state.

### PR DESCRIPTION
**Pull request by bogiii**
Closes https://github.com/Automattic/wp-calypso/issues/88231

## Proposed Changes

* Fixed button busy state color

| Before | Now |
|--------|--------|
| Screen Capture on 2024-03-11 at 17-53-29 | Screen Capture on 2024-03-11 at 17-54-17 | 

## Testing Instructions

* Go to `/plugins/scheduled-updates`
* Select the site
* Create or edit a schedule
* Check the button color (see gifs above)

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Comment by obenland** [comment]
Is there are standardized button state that accounts for the various color schemes? I just tested it with ectoplasm and it also looked off. So rather than us having to recreate them for all color schemes, is there something shared we can use?

**Comment by obenland** [comment]
I also noticed there's a delay after clicking and before the animation kicks in—what causes that? Can we make that instant?

**Comment by bogiii** [comment]
> Is there are standardized button state that accounts for the various color schemes? I just tested it with ectoplasm and it also looked off. So rather than us having to recreate them for all color schemes, is there something shared we can use?

Actually, we use a standardized button busy state following [documentation](https://wordpress.github.io/gutenberg/?path=/docs/components-button--docs). The button style relies on the chosen theme CSS variables, so we are not going to handle each case. Currently, the busy state class takes the wrong color variables and that's fixed in this PR.

In the meantime, I found and fixed one more issue when the button combines the busy and hover state.

**ectoplasm** example:
Screen Capture on 2024-03-11 at 19-07-14

Do you see the same?

**Comment by bogiii** [comment]
> I also noticed there's a delay after clicking and before the animation kicks in—what causes that? Can we make that instant?

Hmmm, it's true. It happens only for the "Create" button. The "Edit" works fine.
I'll investigate further.

**Comment by obenland** [comment]
> In the meantime, I found and fixed one more issue when the button combines the busy and hover state.

yeah that looks good now for the edit button in ectoplasm. The Save button when first creating a schedule doesn't have any animation now, though. Just solid dark green.

**Comment by obenland** [comment]
Looks like that behavior is the same across color schemes. ^

**Review by TimBroddin — COMMENTED** [review]
While testing, I found a small typo in the `pendingMutations` filter for the create schedule screen. I fixed it, and it now works as intended.

| | |
|-|-|
| CleanShot 2024-03-12 at 09 19 27 | CleanShot 2024-03-12 at 09 19 49 |

**Review by TimBroddin — APPROVED** [review]

**Comment by bogiii** [comment]
> While testing, I found a small typo in the pendingMutations filter for the create schedule screen. I fixed it, and it now works as intended.

Perfect. Thanks @TimBroddin!

**Pull request merged**
