### PR TITLE
Badge component janitorial updates

### PR DESCRIPTION
**Pull request by adamziel**
This PR incorporates feedback from the previous one here:

https://github.com/Automattic/wp-calypso/pull/23582

Test plan is the same as in the PR listed above

### CODE REVIEW

**Comment by iamtakashi** [comment]
Thanks for working on this! The comment is helpful.

Let's :shipit:

**Comment by adamziel** [comment]
I updated colors accordingly to comments from https://github.com/Automattic/wp-calypso/pull/23582 

Now they adhere to WCAG AA contrast guidelines, and at the same time the green one looks worse and IMHO the dark text is less readable than the white one - what do you guys think? @simison @drw158  

zrzut ekranu 2018-03-26 o 10 36 47
zrzut ekranu 2018-03-26 o 10 38 28

**Comment by simison** [comment]
>Now they adhere to WCAG AA contrast guidelines, and at the same time the green one looks worse and IMHO the dark text is less readable than the white one

I agree — lighter background colour would probably work better here.

You could use `lighten()` helper introduced here https://github.com/Automattic/wp-calypso/pull/22181

**Comment by simison** [comment]
Hmm, that was a bit fast merge... :-) 

How did those badges end up looking, then?

**Comment by adamziel** [comment]
Accidentally merged before 👍 but since it's so small I'm going to keep myself from reverting. Also the lighter green badge is more readable now. I tried to keep the font white but it was hard to keep the background pretty and have the right contrast so it's the best we can do:

zrzut ekranu 2018-03-26 o 12 38 52

**Comment by drw158** [comment]
Just noting here that the white text on green background looks more readable because the "color difference" is greater. The greater the color difference, the greater the readability. "Color difference" isn't as important as contrast, but it's helpful to look at.

**Pull request merged**
