### PR TITLE
Update/add product screen design tweaks

### PR DESCRIPTION
**Pull request by jameskoster**
Padding inconsistency:

padding-inconsistency

Category margin also needs fixing:

category

Border on L / W inputs;

lw

Attribute input spacing and alignment;

attributes

### CODE REVIEW

**Comment by jameskoster** [comment]
@justinshreve could we please move the featured toggle from the details card to the categories card?

**Comment by justinshreve** [comment]
@jameskoster Just saw this. Done! 

I also put a TODO at the top of the category card because we should probably rename it (for our/future devs sake). It now contains more then categories-- and the mock shows it may contain more in the future like tax collections.

**Comment by kellychoffman** [comment]
👍 This is looking snazzy.

**Comment by jameskoster** [comment]
Switched the order, category seems more important than featured.

Is this good to merge @kellychoffman @justinshreve?

**Comment by kellychoffman** [comment]
Yes, good to merge.

**Pull request merged**
