### PR TITLE
Site Logs: Persist site log type between site selection

### PR DESCRIPTION
**Pull request by eoigal**
Fixes https://github.com/Automattic/dotcom-forge/issues/7543

> When we're viewing web server logs in a site, and then switch to another site, we should still be seeing web server logs, not getting back to PHP logs.

## Proposed Changes

* Adds feature for both the PHP and Web site logs to allow the site log type (php/web) to persist when a user changes the site selection
* Uses redux to save the `logType` state so that when we move between sites, the logType will persist.
* The is no redirect on `/site-logs/:site` - it will work from that URL now by either defaulting to rendering 'php' logs or using the logType in state.
* This removes the clearing of filters, not sure if we should do this but it made sense when testing.

## Why are these changes being made?

* Improve the UX

## Testing Instructions

* Go to `/sites` and click on an atomic site and go to the `/site-log/{selected-site}/web` for that site - then select another atomic site (where site logs feature should be supported) and the site management panel should load the `web` site logs for the selected site.

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Review by fushar — CHANGES_REQUESTED** [review]
> it will work from that URL now by either defaulting to rendering 'php' logs or using the logType in state.

I think this is problematic for two reasons:

1. When we're in the `Web server` tab, if the user refreshes the page (e.g. to get the latest logs), they well see the PHP tab back.
2. If the user uses the command palette (Open PHP logs), the URL will have `/php` at the end, but when the user click the other tab, the URL will not change and it is weird.

I can help brainstorm a few ideas later...

**Review by fushar — COMMENTED** [review]
What's wrong with the previous commit (https://github.com/Automattic/wp-calypso/pull/91462/commits/39e4f62c14f8ab402eecab9882cfcd6c9e4cc0b1)? I think the idea is interesting here 😄

**Comment by eoigal** [comment]
> What's wrong with the previous commit ([39e4f62](https://github.com/Automattic/wp-calypso/commit/39e4f62c14f8ab402eecab9882cfcd6c9e4cc0b1))? I think the idea is interesting here 😄

This worked and was simplest approach but it meant we had 2 tabs now for logs, one for PHP and one for Web.

**Comment by eoigal** [comment]
> > it will work from that URL now by either defaulting to rendering 'php' logs or using the logType in state.
> 
> I think this is problematic for two reasons:
> 
>     1. When we're in the `Web server` tab, if the user refreshes the page (e.g. to get the latest logs), they well see the PHP tab back.
> 
>     2. If the user uses the command palette (Open PHP logs), the URL will have `/php` at the end, but when the user click the other tab, the URL will not change and it is weird.
> 
> 
> I can help brainstorm a few ideas later...

Fair points. I'll think on solutions to these. Thanks!

**Comment by eoigal** [comment]
Not sure why the `context.page.replace( redirectTo );` isn't working as I'd expect here. The browser URL does not reflect the value of the `redirectTo`. Any ideas?


https://github.com/Automattic/wp-calypso/assets/5560595/22c6e93c-e23a-4553-b0e5-81e45ce7fe2b

**Comment by fushar** [comment]
I'll spend some time today to help with this PR 👍

**Comment by arthur791004** [comment]
The issue is related to the syncUrl as it doesn't handle the sub-feature...

**Comment by fushar** [comment]
Yes. I'm working on an alternative approach right now.

**Comment by arthur791004** [comment]
> Yes. I'm working on an alternative approach right now.

Maybe https://github.com/Automattic/wp-calypso/pull/91589 is enough for now 😄

**Pull request closed without merging**
