### PR TITLE
E2E: Create a tmp free site for domain tests

### PR DESCRIPTION
**Pull request by WunderBart**
#### Changes proposed in this Pull Request

- Stabilize domain adding & mapping suites
- Make it possible to run them in parallel by creating a temporary site to isolate the shopping cart

This addresses the issue where the shopping cart is shared by a domain causing side effects in other tests that run against the same domain. Creating a temporary site also creates a unique cart which is removed when the site is removed (see the after hook). This basically reverts https://github.com/Automattic/wp-calypso/pull/53333.

#### Testing instructions

Domain specs should pass:
- `wp-manage-domains__add-a-domain-spec.js`
- `wp-manage-domains__map-a-domain-spec.js`

### CODE REVIEW

**Comment by WunderBart** [comment]
One unrelated spec failing that looks like a Calypso issue: https://github.com/Automattic/wp-calypso/issues/53546

**Comment by scinos** [comment]
👍🏼 

There are other tests affected by the domain problem: `wp-invite-users__viewer-spec.js` (skipped in #53333) and `wp-my-home-support-search-spec.js` (skipped in #53460).

Maybe we can move this to a helper that can be reused by those tests?

**Review by scinos — APPROVED** [review]

**Comment by WunderBart** [comment]
> There are other tests affected by the domain problem: `wp-invite-users__viewer-spec.js` (skipped in #53333) and `wp-my-home-support-search-spec.js` (skipped in #53460).
> 
> Maybe we can move this to a helper that can be reused by those tests?

Thanks for bringing those up. Will take a look 👍

**Review by bsessions85 — APPROVED** [review]
Looks good!

**Pull request merged**
