### PR TITLE
Sidebar: Remove payment processing nudge

### PR DESCRIPTION
**Pull request by sixhours**
#### Changes proposed in this Pull Request

* Confirmed with Yoav that this feature can be removed from the sidebar. It's part of a feature that didn't launch: p1578419640017200-slack-dotcom-manage-design

Before and after:
Screen Shot 2020-01-09 at 1 24 30 PM

#### Testing instructions

* Switch to this PR
* Make sure nothing breaks as a result of the removed code.

### CODE REVIEW

**Comment by gwwar** [comment]
@sixhours do you mind adding a before/after screenshot to the summary + how to get into that state for manual testing. Adding in extra detail is usually super helpful when looking back at history

**Comment by sixhours** [comment]
> @sixhours do you mind adding a before/after screenshot to the summary + how to get into that state for manual testing. Adding in extra detail is usually super helpful when looking back at history

Sure! Normally I would add screenshots by default, but I'm not sure how to trigger this event, since the functionality that triggers it never launched. I can fake it locally if that would be helpful? And let me link to the Slack thread in the ticket for some backstory.

**Comment by gwwar** [comment]
@yoavf @lsl is `async-payments` still running as a test? This is enabled on `stage` but not `production` which we usually try to avoid. (It confuses folks on what's live and what's not).

**Comment by kwight** [comment]
I was able to trigger this on `master` by defeating the `config` and `hasPendingPayment` checks; updated the description with before and after screenshots.

**Pull request merged**
