### PR TITLE
Update plan-specific flows to use generic plans step

### PR DESCRIPTION
**Pull request by andrewserong**
This is a temporary fix to avoid the BSOD (blue screen of death) when switching to the `ecommerce-onboarding` flow after selecting the `Online store` site type. It swaps the more specific plans step types for the generic `plans` step.

This makes the onboarding flow slightly longer for users who pre-select a plan from wordpress.com (they need to select the plan again from the `plans` step), however it prevents the BSOD issue of selecting the `Online store` site type and then getting a blank screen.

The underlying issue is tracked in https://github.com/Automattic/wp-calypso/issues/32506 and a potential _proper_ fix is being explored in https://github.com/Automattic/wp-calypso/pull/34885

Once an underlying fix is merged, we can then return to using plans-specific steps for each of these flows.

Screenshot of the BSOD issue:

Aug-01-2019 18-01-23

#### Changes proposed in this Pull Request

* Update the `free`, `personal`, `premium`, and `business` flows to use the generic `plans` step so that the flow is compatible with the `ecommerce-onboarding` flow when a user switches flow after selecting an `Online store` site type.
* Update e2e tests for creating a personal, premium, and business site from the `/create` page of WordPress.com to include the additional plans step.

#### Testing instructions

* From an incognito window, go to http://calypso.localhost:3000/start/personal
* Log in on the user step
* From the Site type step, select `Online store`, and it should take you to the domains step on the `ecommerce-onboarding` flow, and you should see: http://calypso.localhost:3000/start/ecommerce-onboarding/domains in the address bar
* Click back, and you should be on the `site-type` step
* Select any other site type (e.g. blog) and you should be on the `site-topic-with-preview` step (e.g. http://calypso.localhost:3000/start/personal/site-topic-with-preview )

Repeat the above steps for:

* http://calypso.localhost:3000/start/premium
* http://calypso.localhost:3000/start/business
* http://calypso.localhost:3000/start/free

For each flow, ensure that a site can be created, and you arrive on the checklist page after signup.

### CODE REVIEW

**Review by ramonjd — APPROVED** [review]
This is a tough one. On one hand, this PR removes functionality (`addPlanToCart` is no longer called to pre-select a plan), on the other, it fixes a massive and embarrassing bork.

I think we're right to fix signup while temporarily disabling the existing functionality. 👍 

It might be prudent to give a shout out on onboardingp2 and cc folks who are working on a fix. That way it stays on people's radar, and we can come back and explain any stats discrepancies later. What do you reckon?

**Comment by andrewserong** [comment]
@ramonjd good idea. I'll do it as an FYI, so that if anyone wants or needs to, it can be rolled back if need be.

**Comment by p-jackson** [comment]
Yeah, I'm "on board" with this temp fix 👍 :trollface:

**Comment by ramonjd** [comment]
> Yeah, I'm "on board" with this temp fix 

We wouldn't want you to "sign up" to anything you disagreed with. 😎

**Pull request merged**
