### PR TITLE
Assembler First Flow: Handle the launch site task

### PR DESCRIPTION
**Pull request by arthur791004**
Related to https://github.com/Automattic/wp-calypso/issues/83390

## Proposed Changes

* Check whether the site is able to be launched
* Go to the checkout if the user selects a paid plan or a paid domain before launching the site
* Launch the site after the user clicks the “Launch your site” button in the launchpad
* Navigate to the Celebration step after launching 

### Demo

https://github.com/Automattic/wp-calypso/assets/13596067/9d833c1d-4985-4b82-90f4-f010eb114170

### The Celebration step

image

## Testing Instructions

* Apply latest jetpack-mu-wpcom to your sandbox
  ```
  bin/jetpack-downloader test jetpack-mu-wpcom-plugin trunk
  ```
* Go to `/setup/assembler-first?flags=themes/assembler-first`
* Create a new site
* Finish the Assembler step
* Go to the launchpad, `/setup/assembler-first/launchpad?siteSlug=<your_site>`
* Select a plan
* Select a domain
* Click the “Launch your site” button
* Ensure you can see the Celebration step after launching
* Reset jetpack-mu-wpcom on your sandbox
  ```
  jetpack-downloader reset jetpack-mu-wpcom-plugin
  ```

## Pre-merge Checklist

- [x] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [x] https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md for your changes?
- [x] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [x] Have you checked for TypeScript, React or other console errors?
- [x] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [x] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [x] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

**Comment by taipeicoder** [comment]
@arthur791004 when I upgraded to Premium from the Assembler's upsell screen I got this Launchpad task list:

Screenshot 2023-12-06 at 3 56 05 PM

1. The Choose a plan is incomplete, but I already upgraded to Premium. 
2. The Choose a domain task is gone. I think this is expected since instead there's the Customize button next to the domain.

**Comment by arthur791004** [comment]
> The Choose a plan is incomplete, but I already upgraded to Premium.

This is expected for now as we don't have any mechanism to complete the Plan task there. I'm thinking about how to address it as well 😞

**Review by taipeicoder — APPROVED** [review]
Asides from the issue mentioned in https://github.com/Automattic/wp-calypso/pull/84854#issuecomment-1842360819, the PR works as intended 👍

**Comment by taipeicoder** [comment]
> > The Choose a plan is incomplete, but I already upgraded to Premium.
> 
> This is expected for now as we don't have any mechanism to complete the Plan task there. I'm thinking about how to address it as well 😞

Let's create an issue for posteriority 🙂

**Comment by arthur791004** [comment]
> The Choose a domain task is gone. I think this is expected since instead there's the Customize button next to the domain.

Yes, the domain upsell task is invisible if your site has a paid plan.

https://github.com/Automattic/jetpack/blob/d3449551b91cb1b90473a036ec73aeeab63b6066/projects/packages/jetpack-mu-wpcom/src/features/launchpad/launchpad-task-definitions.php#L885

Maybe we can apply the same logic to the plan task 🤔

**Comment by taipeicoder** [comment]
> > The Choose a domain task is gone. I think this is expected since instead there's the Customize button next to the domain.
> 
> Yes, the domain upsell task is invisible if your site has a paid plan.
> 
> https://github.com/Automattic/jetpack/blob/d3449551b91cb1b90473a036ec73aeeab63b6066/projects/packages/jetpack-mu-wpcom/src/features/launchpad/launchpad-task-definitions.php#L885
> 
> Maybe we can apply the same logic to the plan task 🤔

Yes! That makes sense to me since the user already chose a plan.

**Comment by arthur791004** [comment]
Address the Plan task issue here, https://github.com/Automattic/jetpack/pull/34480.

**Pull request merged**
