### PR TITLE
Update/plan features grid shuffle

### PR DESCRIPTION
**Pull request by donlair**
#### Proposed Changes

* This is a fork of #66403 to tweak it based on feedback at pdgrnI-1u2-p2#comment-2760
* It rearranges and trims the product feature list.
* Those changes are in addition to the changes described in the original PR:

> Changes include:

> - adds a parallel set of the features which all the copy amendments which will be used on both the pages
> - adds tooltips to the Signup Plans pages.
> - uses dynamic price to the CSS customization available for $2 extra

#### Testing Instructions

* go to the experiment page for `pricing_packaging_plans_page_quick_improvements` and assign `treatment` and `control` variations to your username

##### Treatment
* Go to `/start/plans`
* The features should match the changes from the spreadsheet
* Tooltips should be visible next to features that have tooltips descriptions

shuffled-shortened-plans

* the `CSS customization available for $2 extra` feature from Personal plan should have localized pricings
* Resize to mobile and make sure everything renders properly

signup-plans-mobile

* Go to `/plans/[SITE_ID]`
* The features should match the changes from the spreadsheet

calypso-plans

* Resize to mobile and make sure everything renders properly
calypso-plans-mobile

##### Control
* Go to `/start/plans`
* The features should be unchanged
* Resize to mobile and make sure everything renders properly

* Go to `/plans/[SITE_ID]`
* The features should be unchanged
* Resize to mobile and make sure everything renders properly

* There shouldn't be any related JS errors.

Related to #66403

### CODE REVIEW

**Comment by donlair** [comment]
Rebased to include @claudiucelfilip's latest updates in the parent PR.

**Review by claudiucelfilip — APPROVED** [review]
LGTM🚀

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/7478231

Thank you @donlair for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/7478231).

**Review by donlair — COMMENTED** [review]
I added some copy tweaks to the items, but this works well for me. No need to wait for another review after these changes - I think this is good to launch once you've got those in place.

**Pull request merged**
