### PR TITLE
Plugin Details: Avoid the shrink of icon when the plugin title is too big

### PR DESCRIPTION
**Pull request by WBerredo**
## Proposed Changes

Avoid the icon to shrink and always use the set width in order to avoid the stretch of the icon.

| Before  | After |
| ------------- | ------------- |
|CleanShot 2023-02-28 at 15 27 29@2x|CleanShot 2023-02-28 at 15 28 14@2x|

## Testing Instructions

* Go to a plugin details page of a plugin with a big name. Ex: `/plugins/trustpulse-api/`
* Check if the icon is stretched as displayed above
* The prod version SHOULD show a stretched icon
* This branch version SHOULD NOT show a stretched icon

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

**Review by epeicher — APPROVED** [review]
I have tested it, and it works as advertised. I tested the mobile and responsive behaviors and they work as expected. 

LGTM! 🚢

**Comment by epeicher** [comment]
I wanted to mention that an alternative could have been to add `flex-shrink: 0;` to the`.plugin-details-header__icon` class [here](https://github.com/Automattic/wp-calypso/pull/73902/files#diff-f1796edbe76ab4075e601120e8deddbc8250a4957e8ad9fa9903bcfa8cb5c9b7R26) but the result is the same so both approaches LGTM 😃

**Comment by WBerredo** [comment]
@epeicher  Thanks for this solution, I preferred your version as it is more explicit about what we want to achieve.

**Review by epeicher — APPROVED** [review]
Thanks for applying the suggestion! I agree it seems more explicit.

An additional round of testing shows that is working as expected. LGTM! 🚀 

CleanShot 2023-03-01 at 15 25 24

**Pull request merged**
