### PR TITLE
Bumping version number and adding latest changes in changelog for privacy-toolset

### PR DESCRIPTION
**Pull request by gmovr**
Related to #Automattic/martech#1898

## Proposed Changes

This bumps the version number to 1.1.1 and adds the latest changes in the changelog file. These changes are related to https://github.com/Automattic/wp-calypso/pull/78805 where we changed the default ticked buckets when the cookie banner is expanded to leave advertising un-ticked.

## Testing Instructions

This does not change any functionality. We just need to merge this before pushing to npmjs, ref: https://github.com/Automattic/wp-calypso/blob/trunk/docs/monorepo.md#publishing

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

**Review by ddc22 — APPROVED** [review]
We have moved to React 18 which is technically a major change. I think this might be a candidate for at least a minor change but I am not sure.

In any case I guess we need to add a line that we migrated react to 18 (PR: #77046)

I will conditionally approve this pending some feedback from others.
https://github.com/Automattic/wp-calypso/commit/8a2800d1c5606ce265d942c1e9f88e60ea47a0d4#diff-9fcbb8bf973925fd282d80241cecafa888d9ea549c830d6a1be64edfcd4ccc6f

@noahtallen @tyxla do you have any thoughts about how to bump versions in relation to the React 18 for automatic packages when being published? I assumed React 18 would be a breaking change but so far it seems like everything has gone pretty smoothly.

**Comment by gmovr** [comment]
> We have moved to React 18 which is technically a major change. I think this might be a candidate for at least a minor change but I am not sure.
> 
> In any case I guess we need to add a line that we migrated react to 18 (PR: #77046)
> 
> I will conditionally approve this pending some feedback from others. [8a2800d#diff-9fcbb8bf973925fd282d80241cecafa888d9ea549c830d6a1be64edfcd4ccc6f](https://github.com/Automattic/wp-calypso/commit/8a2800d1c5606ce265d942c1e9f88e60ea47a0d4#diff-9fcbb8bf973925fd282d80241cecafa888d9ea549c830d6a1be64edfcd4ccc6f)
> 
> @noahtallen @tyxla do you have any thoughts about how to bump versions in relation to the React 18 for automatic packages when being published? I assumed React 18 would be a breaking change but so far it seems like everything has gone pretty smoothly.

Thanks! I've added that to the changelog now. As there are no changes in the code, just a version bump on React, I've kept it at a patch level. Same for the bucket change, as it doesn't add new features, just changing a default value. I can make it a minor version though, if that's the semantic way. :)

**Review by travisw — APPROVED** [review]
LGTM – but I'll defer to others for deciding on the exact version number.

**Comment by tyxla** [comment]
> @noahtallen @tyxla do you have any thoughts about how to bump versions in relation to the React 18 for automatic packages when being published? I assumed React 18 would be a breaking change but so far it seems like everything has gone pretty smoothly.

For most packages, it won't matter since they're used only internally, but for some that are used externally, I'd recommend a major version. React 18 could be a big change for a consumer app and it only makes sense to put the upgrade into a major release.

**Comment by gmovr** [comment]
Thanks for the context @tyxla ! I made it a major version now.

**Review by travisw — APPROVED** [review]

**Pull request merged**
