### PR TITLE
Purchases: Error when no purchases on ConfirmCancelDomain

### PR DESCRIPTION
**Pull request by aidvu**
If purchases are empty, redirect doesn't fire before render and since there is no purchase an error is thrown before page() picks it up.

Fixes: https://github.com/Automattic/wp-calypso/issues/20798

### CODE REVIEW

**Comment by aidvu** [comment]
This runs before we hit `render()`: https://github.com/Automattic/wp-calypso/pull/20800/files#diff-102a63d39fafbfcbac39438b15aa0c32L79, but doesn't redirect on time I guess. :)

**Comment by hoverduck** [comment]
This is better, the browser at least doesn't crash to an entirely blank screen, but it's still not functioning correctly.  I'm now left with this screen saying the domain was cancelled, but I don't see anything else.  Navigating to different routes works, but if I go back to `/me/purchases` it does nothing.  No console errors now.

screenshot_2017-12-13_15-40-57

**Comment by hoverduck** [comment]
I don't have a screenshot of the behavior before the single-tree rendering change, but I believe it left you on the screen saying 'You don't have any sites' with a button to create one.

**Comment by aidvu** [comment]
@scottsweb I'll check. Thanks.

**Comment by aidvu** [comment]
This now renders the `noSiteMessage` even when there are sites. Either it was a racing condition I missed, or something else.

**Comment by aidvu** [comment]
Yeah, but I'm not really sure if it's working properly yet. @ockham said he'll take one more look today.

**Comment by ockham** [comment]
Sorry for the delay.

As suggested by @aidvu in Slack, I tested the following:

1. Create a site
2. Register a domain only (I used a `.live` domain)
3. Cancel the domain only

This gives me the following screen:

image

i.e. the `<PurchasesList /`> component (not the `<NoSites />` one, which would have a `You don't have any WordPress sites yet` text).

So I guess this LGTM -- @aidvu, can you confirm that you were seeing the `<NoSites />` component (and not <PurchasesList />`, which looks somewhat similar)?

**Comment by aidvu** [comment]
@hoverduck safe to re-enable the tests for this again.

**Comment by hoverduck** [comment]
Done!

**Pull request merged**
