### PR TITLE
Jetpack Error UX: Make side indicator use new Jetpack connection health check

### PR DESCRIPTION
**Pull request by wojtekn**
Related to https://github.com/Automattic/dotcom-forge/issues/3459

## Proposed Changes

In this diff, I propose hooking the existing Jetpack error UI with data coming from a new API endpoint that checks Jetpack connection health as well as enable the indicator for Atomic sites.

Screenshot 2023-08-15 at 14 03 49

Screenshot 2023-08-15 at 14 03 57

## Testing Instructions

1. Load the posts page for a blog with a broken connection
2. Confirm that the message in primary part of the page is displayed
3. Confirm that the error indicator is displayed in the sidebar's site card

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

**Review by danielbachhuber — CHANGES_REQUESTED** [review]
Because we'll be showing this notice in more places, it'd be great to improve upon the notice in this PR too.

https://github.com/Automattic/wp-calypso/blob/540132238f60e03244484d4d78e9222d27addb9f/client/my-sites/site-indicator/index.jsx#L201-L211

We can use the generic message and action:

> Jetpack can’t communicate with your site.
>
> Learn how to fix

It can link to our primary support doc.

Let's also add Tracks events for how often this particular indicator is shown and clicked. It'd be great if it distinguished between Atomic and non-Atomic sites: https://github.com/Automattic/dotcom-forge/issues/3491

I think the `recordGoogleEvent` references are dead, so I created a maintenance issue to remove them: https://github.com/Automattic/dotcom-forge/issues/3490

**Comment by wojtekn** [comment]
@danielbachhuber I've applied those changes. It looks like that new copy is longer and doesn't fit into one line. It causes a layout issue for sites that do not have any badges:

Screenshot 2023-08-16 at 11 42 52

Screenshot 2023-08-16 at 11 42 41

@javierarce, any thoughts on how to improve this on the design level?

**Comment by javierarce** [comment]
@wojtekn: could we put the link in the same line as the text?

And here's also a reference for the icon's position with and without badges.

image

**Comment by wojtekn** [comment]
Thanks @javierarce , it did the trick:

Screenshot 2023-08-16 at 12 54 36

**Review by danielbachhuber — APPROVED** [review]
Works well 👍

**Comment by javierarce** [comment]
> Thanks @javierarce , it did the trick:

Fantastic! Would it be possible to match the heights in both cases? Or does it depend on the container div where they are inserted?

**Comment by wojtekn** [comment]
> Fantastic! Would it be possible to match the heights in both cases? Or does it depend on the container div where they are inserted?

@javierarce it depends on the `site__content` container height, and its height varies depending on badge existence, so I think we can't do this unless we set the main container heigh to a fixed one.

**Comment by javierarce** [comment]
It's ok, then. I'll take note to improve this and update notifications in the sidebar.

**Pull request merged**
