### PR TITLE
Stats: allow switch to pwyw if site is personal or not identified yet

### PR DESCRIPTION
**Pull request by kangzj**
Related to #

## Proposed Changes

We are going to default site to the commercial products for new sites that are not identified yet. For those sites, we should allow them to choose personal sites freely, if they satisfy all the requirements.

Site identified as commercial will still need to contact support to be able to be identified as personal.

The next step will be defaulting all unidentified sites to the commercial product, as they'll be able to switch to pwyw now.

## Testing Instructions

* Prepare a fresh JN site and connnect it
* Open `/stats/purchase/:siteSlug`
* Click 'This is not a commercial site'
* Check all the boxes
* Ensure you see button 'Choose a non-commercial license'
* Click the button
* Ensure you are taken to the PWYW page

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

**Comment by grzegorz-cp** [comment]
When testing the Calypso live branch with a freshly connected JN site, I'm redirected to the PWYW purchase page straight away.

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/10754008

Some locales (Hebrew, Japanese) have been temporarily machine-translated due to translator availability. All other translations are usually ready within a few days. Untranslated and machine-translated strings will be sent for translation next Monday and are expected to be completed by the following Friday.

Hi @kangzj, could you please edit the description of this PR and add a screenshot for our translators? Ideally it'd include this string: `Choose a non-commercial license`

Thank you in advance!

**Comment by a8ck3n** [comment]
Just noting I'm unable to test this with the steps provided above. I've also tried overriding the 'isCommercial' value but that results in me seeing the classification wizard instead of the Commercial purchase flow.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/10754008).

**Pull request merged**
