### PR TITLE
Split `lib/analytics/ad-tracking`

### PR DESCRIPTION
**Pull request by sgomes**
This PR splits up `lib/analytics/ad-tracking` from one massive module into multiple modules with an index file.

This should help modularise analytics, so that not everything needs to get loaded upfront.

There are no code changes other than code moving around, and always calling `setupGtag()` on setup.

#### Changes proposed in this Pull Request

* Split `lib/analytics/ad-tracking` into modules

#### Testing instructions

There are little to no code changes, so it should be sufficient to ensure that there are no build or unit test failures, which should pick up a missing or incorrectly named export. For extra peace of mind, a quick check to make sure that ad tracking functionality continues to work correctly could be useful.

### CODE REVIEW

**Comment by sgomes** [comment]
Sadly, there appear to be no performance gains from this PR alone, with a ~0.6KB increase instead, for most entry points. Once it's merged, I'll look for opportunities to take advantage of the split.

**Comment by sgomes** [comment]
E2E failures appear unrelated.

**Comment by sgomes** [comment]
After some investigation into why this PR doesn't immediately result in better tree-shaking, it appears to be because `lib/analytics/index.js` imports a bunch of stuff from `lib/analytics/ad-tracking` and exports it as a single default export. The next step will be to modularise `lib/analytics/index.js`.

As I mentioned before, I still believe this PR stands on its own, however.

**Review by lynnbgriffith — APPROVED** [review]
👍🏻 Makes sense.  Will keep an eye for the subsequent PRs.

**Review by lynnbgriffith — APPROVED** [review]
👍🏻 Makes sense.  Will keep an eye for the subsequent PRs.

**Comment by sgomes** [comment]
Thanks for the review, @griffbrad! 👍

**Pull request merged**
