### PR TITLE
E2E: Rotate secret

### PR DESCRIPTION
**Pull request by WunderBart**
## Proposed Changes

Rotates the store secret we need for e2e tests.

See D128245-code.

## Testing Instructions

Decrypt the file locally and ensure the store secret matches the backend diff.
See PCYsg-vnR-p2 for detailed instructions on how to decrypt.

### CODE REVIEW

**Review by noahtallen — APPROVED** [review]
I've not gotten a chance to test, but if you're confident in this, I think we can move forward with it. We probably need to announce that PRs will need to be rebased, as "merge trunk" doesn't happen for e2e tests, IIRC

I guess the other note is we should only do this once, so if we wanted to change anything else in the file we should do that here

**Comment by fullofcaffeine** [comment]
> I guess the other note is we should only do this once, so if we wanted to change anything else in the file we should do that here

Could you elaborate on this? While not too practical, nothing prevents us from having subsequent PRs changing the contents of the file again? Or am I missing something?

**Comment by WunderBart** [comment]
E2E accounts rotation thread: p1701347563645579-slack-C05U9M2DB0D

cc @Automattic/team-calypso-platform

**Comment by noahtallen** [comment]
> While not too practical, nothing prevents us from having subsequent PRs changing the contents of the file again? Or am I missing something?

You're right, it's just a bit more practical to do it at once. The other side is that existing PRs/branches fail when we update things in the file, which means people have to rebase, so reducing the amount of time we do that would be ideal

**Comment by noahtallen** [comment]
I updated all the e2etestflow passwords with the new value, and re-encrypted the file.

**Comment by noahtallen** [comment]
They are still failing, but now because the credentials are bad. So it is decrypting the file in TeamCity now.

**Comment by noahtallen** [comment]
After rotating several accounts, the main e2e suite is passing. Still more to update, but that's proof the process is working as expected :)

**Pull request merged**
