### PR TITLE
Stepper: Fix navigation UI in Stepper

### LINKED ISSUE #97067: Stepper: Handle User step differencies
[Context](https://github.com/Automattic/martech/issues/3559#issuecomment-2514740967).

Start | Stepper

Image

- Stepper is too low
- Login button is at the bottom in Stepper
- Content is smaller on Stepper due to additional margin

### PR DESCRIPTION
**Pull request by alshakero**
Fixes: https://github.com/Automattic/wp-calypso/issues/97067

## Proposed Changes

* This fixes the navigation buttons and the formatted header in Stepper and makes them consistent with /start.
* It cleans up the never used `shouldStickyNavButtons` property and the CSS that comes with it.

## Why are these changes being made?

To bring consistency.

## Testing Instructions

1. Using incognito, open two tabs one to /setup/onboarding and one to /start.
2. The user step should look 99% identical between the two. **On desktop and on mobile.**
3. Feel free to leave incognito mode. 
5. The domain step should look 99% identical between the two. **On desktop and on mobile.**
6. The plans step should look 99% identical between the two. **On desktop and on mobile.**

### CODE REVIEW

**Comment by escapemanuele** [comment]
I see a big number of improvements!

Can you check this? It happens under 1080px

image

**Comment by alshakero** [comment]
> Can you check this? It happens under 1080px

Fixed in [`b612729` (#97256)](https://github.com/Automattic/wp-calypso/pull/97256/commits/b612729de4894670a84d2141d346d8121c6f13e5)

**Comment by heavyweight** [comment]
Truly minor difference in the way the login button is aligned but I think stepper in correct here

| Stepper  | Start |
| ------------- | ------------- |
| Screenshot 2024-12-10 at 14 48 05  | Screenshot 2024-12-10 at 14 48 16  |

**Comment by heavyweight** [comment]
However here I think we need to fix the header 

| Stepper  | Start |
| ------------- | ------------- |
| Screenshot 2024-12-10 at 14 53 09  |  Screenshot 2024-12-10 at 14 53 17 |

**Review by heavyweight — APPROVED** [review]
LGTM

**Comment by valterlorran** [comment]
I noticed that this changed the whole stepper design. I'm not sure if that was the right call. @fditrapani can you chime on this? I started reporting this here:
p1733858844922699-slack-C0Q664T29

**Comment by fditrapani** [comment]
Thanks for the ping @valterlorran. I have been following this work on the stepper. It does look like the spacing is different than before. I don't think it's a bad thing though. We'll just have to make some adjustments on the non-stepper screens before and after the stepper used in migrations to line everything up.

**Comment by alshakero** [comment]
> Hi everyone! I tried to meticulously copy the spacing of /start into Stepper around StepContainers and FormattedHeaders. I was very careful but please do tell me if you see any mistakes.

**Comment by arthur791004** [comment]
This changed the navigation position on other steps under the stepper flow. Is it exptected 🤔

**Comment by p-jackson** [comment]
CleanShot 2024-12-16 at 20 19 26@2x

It removed some CSS which was needed to to have the goals step actions appear in the footer. My guess is it was assumed that the `shouldStickyNavButtons` prop was for controlling this, however in reality all the footers were sticky regardless of the prop.
I'm working on reinstating the sticky footer but with a prop that can disable it for the signup step.

**Comment by p-jackson** [comment]
Does this fix both issues @alshakero? https://github.com/Automattic/wp-calypso/pull/97503

**Pull request merged**
