### PR TITLE
Delete Site: Redirect to /sites instead of /read after deleting the site

### PR DESCRIPTION
**Pull request by kozer**
Fixes https://github.com/Automattic/dotcom-forge/issues/5101

## Proposed Changes

This pr aims to fix the "default redirect" when we delete a site. Until now, when the user deleted a site and there wasn't one left, it got redirected to `/read` page. We change that now to be the Sites Dashboard ( `/sites` )

## Testing Instructions

1. Open incognito mode, and create a new user.
2. Purchase a new free site.
3. Navigate to `/settings/delete-site/<your site`
4. Press the `Delete Site` button
5. Ensure that you get redirect at `/sites` page and you see the following image

2024-01-12T12:33:40,423523901+02:00

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

**Review by katinthehatsite — APPROVED** [review]
These changes worked as expected for me. I followed the testing steps and was redirected to `/sites` when I deleted a site and had no more sites:

Screenshot 2024-01-12 at 12 50 04 PM

I have also tested `My Sites` and `Reader` links with a regular user with sites present and they worked as expected with no change.

Finally, I added a user with no sites as an editor to another site. Then I checked the view from `/sites` page for that user and saw that they had a site where they are an editor listed instead of seeing a message to create a site.

I did not find anything specific that breaks the current behavior and the redirect worked successfully for me for the described case.

**Review by wojtekn — APPROVED** [review]
@kozer it seems we need to update tests to cover the new behavior.

Adding @p-jackson as a reviewer as he worked on tests for this code.

The code change looks good to me. I couldn't test it yet as I have some oddities in signing in to the account when using Calypso Live or Calypso locally.

**Comment by katinthehatsite** [comment]
> it seems we need to update tests to cover the new behavior.

I took a quick look and it seems that you just need to update this line: 

https://github.com/Automattic/wp-calypso/blob/0eed03aa7e4d0772f2ac0af62500d8128ae43409/client/test/root-section.ts#L45

to:

```
 await waitFor( () => expect( page.current ).toBe( '/sites' ) ); 
```

I ran the test locally after making the changes and it was passing as expected.

**Comment by wojtekn** [comment]
@kozer I fixed local environment issue, tested the feature, and it works as expected - I'm redirect to the Sits page when I delete my last site.

**Comment by kozer** [comment]
> I took a quick look and it seems that you just need to update this line:

Tests updated. Thanks @katinthehatsite !

**Pull request merged**
