### PR TITLE
Hide Gutenframe while it's loading

### LINKED ISSUE #49374: Opening Gutenberg editor sometimes triggers error messages on Chrome and Firefox
### Steps to reproduce the behavior

Prereq. there is an existing Post or Page.
Prereq. on Firefox, enable Enhanced Tracking Protection.

1. Select a site.
2. On the sidebar, click on Posts or Pages.
3. Click on Add New (page or post).
4. Quickly navigate back.
5. Open the existing page or post.

#### What I expected to happen
Clicked page or post opens in the Gutenberg editor as soon as feasible, without user-facing errors or unexpected transitions.

#### What actually happened 
Likely because of the Enhanced Tracking Protection enabled in Firefox, there is an error page that is shown to user that connection could not be made.

Given a few seconds, the browsers reload and is able to render the requested page/post in the block editor.

### Context
User scenario manual testing.

#### Browser / OS version
OS: macOS Catalina 10.15.7
Browser: Firefox Nightly 86.0a1
Chrome 88.0.4324.96 (Official Build) (x86_64) (just twice)

#### Is this specific to the applied theme? Which one?
N/A

#### Does this happen on simple or atomic sites or both?
<strike>Both</strike>
Updated: Atomic only.

#### Is there any console output or error text?
Yes (Firefox):
```
The loading of “https://radicallyrenewedrecordsshop.wpcomstaging.com/wp-login.php?redirect_to=https%3A%2F%2Fradicallyrenewedrecordsshop.wpcomstaging.com%2Fwp-admin%2Fpost.php%3Fpost%3D34%26action%3Dedit%26calypsoify%3D1%26block-editor%3D1%26frame-nonce%3D1611881008%253A6321460%253A943df2a49531be87749e1cc99ce28a5c%26origin%3Dhttps%253A%252F%252Fwordpress.com%26environment-id%3Dproduction%26support_user%3D%26_support_token%3D&reauth=1&calypsoify_cookie_check=true” in a frame is denied by “X-Frame-Options“ directive set to “DENY“.
```

#### Level of impact (Does it block purchases? Does it affect more than just one site?)
N/A

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.
Firefox
Screen Shot 2021-01-27 at 16 37 52

Chrome (reproduced on Simple site only twice)
Screen Shot 2021-01-27 at 16 42 48

Firefox:
https://user-images.githubusercontent.com/6549265/106074200-43a7f480-60c0-11eb-946a-029d7d49d61e.mov

### PR DESCRIPTION
**Pull request by alshakero**
#### Changes proposed in this Pull Request

* This PR implements the change proposed by @jsnajdr [here](https://github.com/Automattic/wp-calypso/issues/49374#issuecomment-802584542). It does the trick perfectly.

#### Testing instructions

I don't really know how to test this PR. This change needs to be under wordpress.com to be tested. 

Fixes #49374

### CODE REVIEW

**Review by ciampo — DISMISSED** [review]
> I don't really know how to test this PR.

I kind-of tested it by introducing an artificial timeout in `onIframeLoaded` and checking that the iframe is effectively hidden.

> This change needs to be under wordpress.com to be tested.

It should be ok to merge this and double-check on production — @alshakero would you be able to provide detailed testing instructions for testing on wordpress.com?

**Review by ciampo — COMMENTED** [review]
Actually, before merging, it would be better to look into e2e tests failures with error

``` Timed out waiting for element with css selector of '.calypsoify.is-iframe iframe' to be present and displayed```

hopefully a rebase will fix those failures

**Comment by ciampo** [comment]
Hey @bsessions85 , I'm trying to understand why this small code change is causing the e2e tests to fail when querying for the `iframe` — would you be able to help with it?

**Comment by bsessions85** [comment]
I played with this some today and it passes locally, but fails consistently in CI. I don't know why that is, and don't have a good understanding of how the editor loads to know what else to check. The CI is running Chrome 84, so it could be specific to slightly older browsers, but I am not sure. I will dig in some more tomorrow and do some debugging on the CI browser.

**Comment by ciampo** [comment]
> I played with this some today and it passes locally, but fails consistently in CI

That's what I noticed in my tests too

> I will dig in some more tomorrow and do some debugging on the CI browser

Thank you for looking into this further!

**Comment by alshakero** [comment]
@jsnajdr Hi Jarda! I tested with opacity instead of clipping and it seems to work. Is there a reason we should use clipping?

**Review by ciampo — APPROVED** [review]
I tested again by introducing an artificial delay and verifying that the `<iframe />` is effectively transparent.

Using `opacity` instead of clipping seems to play nicely with e2e tests.

@alshakero would you be able to provide detailed testing instructions for wordpress.com, especially around reproducing iframe errors and thus making sure that these errors are not being shown to the user ?

As soon as we have them, we can merge and test in production too.

**Comment by alshakero** [comment]
@ciampo IIRC, the issue is quickly reproducible using the steps in [the issue](https://github.com/Automattic/wp-calypso/issues/49374). If you want, try to repro so you'd see how it looks, merge and deploy, then test after merging.

**Pull request merged**
