### PR TITLE
Newsletters: Remove Add Subscribers screen from onboarding

### PR DESCRIPTION
**Pull request by edanzer**
## Proposed Changes

This PR remove the Add Subscribers screen from the normal Newsletter onboarding flow. This screen is now accessible only from the Add Subscriber task/link on Launchpad. It is only visible to those who select "Import existing newsletter" as their goal during the flow.

We also need to update the task completion logic for the Add Subscribers task. The initial state had been true/complete, because users went through that screen on the way to Launchpad. Now the initial state will be false/incomplete, and we've added logic to this PR to ensure the task gets completed when a user visits the Add Subscriber screen. 

**Companion backend PR.** This PR should be tested with [this companion backend Jetpack PR](https://github.com/Automattic/jetpack/pull/31947). This PR sets the initial state of the Add Subscribers task to incomplete. The logic for that initial status is on the backend.

## Testing Instructions

1) Setup
   - Load this branch in your local calypso environment. 
   - Run `bin/jetpack-downloader test jetpack update/newsletter-launchpad-tasks` to load the Jetpack backend PR branch in your sandbox.
   - Be sure to sandbox public-api and the domain of each test site as you go through testing. 
2) Test that the Add Subscribers screen is removed entirely for Free or Paid goals. 
   - Start a newsletter site at http://calypso.localhost:3000/setup/newsletter/intro. Select "Free newsletter" as your goal. Confirm you do not see the Add Subscribers screen before you get to Launchpad. And confirm you do not see the Add Subscribers task on Launchpad. 
    - Start a newsletter site at http://calypso.localhost:3000/setup/newsletter/intro. Select "Paid newsletter" as your goal. Confirm you do not see the Add Subscribers screen before you get to Launchpad. And confirm you do not see the Add Subscribers task on Launchpad. 
3) Test the Add Subscribers screen for the Import goal. 
      - Start a newsletter site at http://calypso.localhost:3000/setup/newsletter/intro. Select "Import existing newsletter" as your goal. Confirm you do NOT see the Add Subscribers screen before you get to Launchpad. Confirm you DO see the Add Subscribers task when you arrive on Launchpad, and the task shows as incomplete.
      - Click the task and go to the Add Subscribers screen. Click 'Skip for now', and when you return to Launchpad, confirm the task now shows as completed.

### CODE REVIEW

**Comment by crisbusquets** [comment]
Hi @edanzer !

I reviewed it using the Calypso Live link.

**Goal: "Free newsletter"**
✅ I didn't see the Add Subscribers screen or the task on the Launchpad

Screenshot 2023-07-19 at 15 34 45


**Goal: "Paid newsletter"**
✅ I didn't see the Add Subscribers screen or the task on the Launchpad
✅ This launchpad had the two paid newsletter tasks (set up Stripe and payment plan)

Screenshot 2023-07-19 at 15 35 05


**Goal: "Import existing newsletter"**
✅ I didn't see the Add Subscribers screen
❌ The task appears `Completed` on the Launchpad

Screenshot 2023-07-19 at 15 33 56

✅ I can click that task and it opens the Add Subscribers screen
✅ If I click "Skip for now" it goes back to the Launchpad

**Comment by crisbusquets** [comment]
Note: I also tested it using my local Calypso environment and saw the same issue I shared in my comment above.

**Comment by edanzer** [comment]
> The task appears Completed on the Launchpad

@crisbusquets - Just want to confirm if you were running the backend Jetpack PR at the same time? This PR by itself won't change the initial completion status - that comes from the backend. You'd need to have that other Jetpack PR loaded in your sandbox, and have both public-api and your test site pointed at your sandbox.

**Review by lezama — APPROVED** [review]
tests well for me, let's merge both PRs!

**Pull request merged**
