### PR TITLE
Email Forwarding: Fix Incorrect Extended Limit

### LINKED ISSUE #82812: Email Forwarding shows warning that 25 of 25 Forwards used on Business and Commerce Plan
### Quick summary

When adding email forwards to a domain, once you reach 25 forwards, the Email Forwarding page mentions you hit the limit of 25 of 25 email forwards.

It is possible to continue adding emails using this direct link: `https://wordpress.com/email/{DOMAIN NAME HERE}/forwarding/add/{DOMAIN NAME HERE}`

Here is a screen recording of how to replicate:

https://github.com/Automattic/wp-calypso/assets/93800099/171150bf-5b3b-48af-a6c3-e7ace6445db6

### Steps to reproduce

1. On a Business or Commerce site, navigate to Upgrades > Emails > Start with Email Forwarding.
2. Add email forwards.
3. Keep repeating step 2, when you get to the 26th one, you'll see this limit at the bottom and won't be able to add more forwards from that page:

EmailForwardLimit

### What you expected to happen

I expected the limit to not show at all until I added 100 email forwards OR for the page to show the current number of email forwards added vs the allotted amount. 

Per our public support doc [Email Forwarding](https://wordpress.com/support/add-email/email-forwarding/), sites on Business and Commerce plans can add up to 100 email forwards for each domain, while sites on lower plans can only add 25.

### What actually happened

A message indicating the limit of 25 of 25 email forwards has been reached.

### Impact

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Atomic

### Logs or notes

I did not test on a simple site on the Business or Commerce plan.

Once the forwards are again under 25 total, the limit message disappears.

Related slack thread: p1696945137463299-slack-C03TY6J1A

### PR DESCRIPTION
**Pull request by Aurorum**
Fixes #82812

## Proposed Changes

* Fix the incorrect Email Forwarding limit preventing users on the Creator plan from adding more email forwards (they can still do so with the direct URL; it's just an interface problem)

## Testing Instructions

* Navigate to My Sites > Upgrades > Email on a site with 25 email forwards (or force this to always appear)
* Confirm that on a site below the Creator plan, the same 25 limit appears, but that limit increases to 100 for sites with the Creator plan.

Screenshot 2024-01-07 at 10 23 16

**Please note:** I do not have a Creator plan with a custom domain that I can test this with. I've only tested it by switching features, but `FEATURE_EMAIL_FORWARDING_EXTENDED_LIMIT` looks to be correctly registered to the Creator plan here so I'm pretty sure this will work. 

https://github.com/Automattic/wp-calypso/blob/b3d3b2cddb177801bff78d165b3deab5e2a47431/packages/calypso-products/src/plans-list.tsx#L1145

cc @ebinnion @wongasy - seems 100 was referenced in #81264 but not included?

### CODE REVIEW

**Review by nightnei — CHANGES_REQUESTED** [review]
The changes are straightforward and really good 👍

But I would like to ask your opinion about IMO tiny improvement - WDYT about excluding such code to `useForwardLimit` hook?

My thoughts:
1) Hypothetically, it can be used inside other components
2) This component is already quite big with a lot of logic, so I would separate such code to own hook. Ideally would be cool to make simple function, but probably it will be hard, so hook IMO would be good approach.

WDYT?

**Comment by Aurorum** [comment]
Hey @nightnei - thanks so much for the review! I totally see the advantages to extracting the logic here. However, all the hooks for this section seem to make their own API requests to endpoints, so perhaps it's a little overkill to add a hook here?

What do you think about adding another selector for consistency instead? I've committed this approach, so please feel free to let me know your thoughts. :)

**Comment by nightnei** [comment]
@Aurorum yeah, creating a selector looks really cool, good idea 🙂👍

First of all - thank you so much for the PR, the code looks good to me, and most likely we will go with it, but before, looks like we need to make changes also to the backend.
I am not very familiar with codebase regarding `features`, so I need to debug a bit more. What I see at the moment:
1) I tested, and your changes don't have any effect on the UI, but they indeed should.
2) AFAIS, this plan configuration (https://github.com/Automattic/wp-calypso/blob/b3d3b2cddb177801bff78d165b3deab5e2a47431/packages/calypso-products/src/plans-list.tsx#L1145) is used only for UI (rendering info about available plans), but actual plan features, looks like received only from backend. Now backend doesn't return `email-forwarding-extended-limit` feature, that's why your changes don't affect UI correctly.
Screenshot 2024-01-11 at 11 36 25

@ebinnion if you know this part of codebase, tell me please - am I right or not?

UPDATE: It seems I am right, it's necessary to update `/rest/v1.1/sites/<SITE_ID>/features` endpoint. I tried to hardcode `email-forwarding-extended-limit` feature at the backend for this endpoint, and now I see it in response, and the UI works well.

@Aurorum I will come back here, as soon as I figure out the backend, and, if necessary, make appropriate changes there, ok? :)

**Comment by Aurorum** [comment]
Serves me right for proposing a change that I’m not actually able to test! I didn’t realise it was checked from the endpoint, so thanks for looking into this. I assume you’ll need to make the relevant changes there.

**Comment by nightnei** [comment]
> Serves me right for proposing a change that I’m not actually able to test! I didn’t realise it was checked from the endpoint, so thanks for looking into this. I assume you’ll need to make the relevant changes there.

@Aurorum First things first - you did a great job, and you specified that you haven't had the opportunity to test it, so the PR and the description are totally good 🙂 And, the Calypso changes are correct. I just have to adjust the backend for them. So in a nutshell - thank you so much for your very valuable effort for WP 🙂

**Comment by nightnei** [comment]
@Aurorum the backend is updated, but a bit another way - we have request to `/emails/accounts/:domainname/mailboxes`, response has property `maximum_mailboxes`:
Screenshot 2024-01-19 at 17 56 07

As a result - for Creator+ plans it's `100`, for lower plans it's `25`. So we should take the value to understand the number of allowed email forwards.

Now we need to adjust Calypso to such changes. If you want, you can adjust these changes and I will review and check it with Creator+ plans :)

**Comment by Aurorum** [comment]
Thanks for taking care of that, @nightnei! I've made the Calypso changes now.

Since this data is being stored in `useGetEmailAccountsQuery` and not at site level, I don't think it's particularly worth extracting it into its own selector, particularly since there's a lot of other data there already. What do you think? :)

**Comment by nightnei** [comment]
>Since this data is being stored in useGetEmailAccountsQuery and not at site level, I don't think it's particularly worth extracting it into its own selector, particularly since there's a lot of other data there already. What do you think? :)

Totally agree 👍

**Review by nightnei — APPROVED** [review]
The code LGTM, and works as expected. Good job, thank you @Aurorum 
The changes are deployed.

**Comment by Aurorum** [comment]
Thanks for all your help!

**Pull request merged**
