### PR TITLE
A4A > Feedback: Logical implementation of in-product feedback mechanism 

### PR DESCRIPTION
**Pull request by yashwin**
Related to https://github.com/Automattic/automattic-for-agencies-dev/issues/1246

## Proposed Changes

This PR makes the logical implementation of the in-product feedback mechanism.

## Why are these changes being made?

* To show the feedback form after specific actions are performed: 

• Sending a referral
• Adding a team member
• Filling out partner directory information

NOTE: The UI is not yet integrated with the API endpoint, as it is in progress.

## Testing Instructions

* Open the A4A live link
* Append the URL with ?flags=-a4a-product-feedback, perform the below actions and verify no feedback form is shown. Please ensure you don't refresh the page, as it will add the feature flag back. 

• Sending a referral (/marketplace/products > Toggle the refer mode on and send a referral)
• Adding a team member (/team/invite > Send invite)
• Filling out partner directory information (/partner-directory/agency-details > Save public profile)

* Remove the feature flag > Refresh the page and perform the below actions and verify the feedback is shown as displayed below. Submitting or skipping the form should hide it and not show again when performing the same action. You can verify it by visiting the page manually with `#feedback` appended, you can find the URLs below. 

• Sending a referral (/marketplace/products > Toggle the refer mode on and send a referral)

Manual testing URL: /referrals/dashboard#feedback

Screenshot 2024-12-05 at 10 28 38 AM

• Adding a team member (/team/invite > Send invite)

Manual testing URL: /team/invite#feedback

Screenshot 2024-12-05 at 10 12 24 AM

• Filling out partner directory information (/partner-directory/agency-details > Save public profile)

Manual testing URL: /partner-directory/agency-details#feedback

Screenshot 2024-12-05 at 10 28 01 AM

How the preferences are stored:

Screenshot 2024-12-05 at 11 06 08 AM

Preferences can be reset from staging

## Pre-merge Checklist

- [x] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [x] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
    - [ ] For UI changes, have we tested the change in various languages (for example, ES, PT, FR, or DE)? The length of text and words vary significantly between languages. 
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Review by cleacos — COMMENTED** [review]
**Side note:** During our initial exploration, I suggested using the feedback data returned from one of our endpoints and not storing it in the app when the feedback form was sent. I mean, the backend would send to the app when the feedback forms were sent. That way, we are storing the information at the account level instead of the browser level. No matter the browser or computer the user uses, if the user already sent the form, it won't show it again.

The show/hide logic is executed in the app, but the information about it is provided inside one of the existing endpoints (i.e. agency). Something like `agency.feedback.forms['the_feedback_reference'].sent_at`.

**Comment by yashwin** [comment]
@cleacos: Thanks for the feedback!

> During our initial exploration, I suggested using the feedback data returned from one of our endpoints and not storing it in the app when the feedback form was sent. I mean, the backend would send to the app when the feedback forms were sent. That way, we are storing the information at the account level instead of the browser level. No matter the browser or computer the user uses, if the user already sent the form, it won't show it again.

We are not storing the data at the browser/app level. We are using the https://public-api.wordpress.com/rest/v1.1/me/preferences API endpoint to store. This is stored at the user level. So, no matter the browser the user uses, it will be shown only once. We already use this in multiple places.

**Comment by cleacos** [comment]
> We are not storing the data at the browser/app level. We are using the https://public-api.wordpress.com/rest/v1.1/me/preferences 

Nice! I was thinking in the app preferences :)

**Review by travisw — APPROVED** [review]
Makes sense and works well 🚀

**Comment by travisw** [comment]
This should be safe to deploy as it's behind a feature flag. I'll go ahead and deploy.

**Pull request merged**
