### PR TITLE
Notifications: Fix orphan text nodes

### PR DESCRIPTION
**Pull request by mmtr**
#### Changes proposed in this Pull Request

Refactors how the empty ranges are handled by notifications in order to properly display the text nodes.

Before | After
--- | ---
Screen Shot 2020-11-09 at 16 29 25 | Screen Shot 2020-11-09 at 16 29 33
Screen Shot 2020-11-09 at 16 30 13 | Screen Shot 2020-11-09 at 16 30 33
Screen Shot 2020-11-09 at 16 31 14 | Screen Shot 2020-11-09 at 16 31 32
Screen Shot 2020-11-09 at 16 31 57 | Screen Shot 2020-11-09 at 16 32 13
Screen Shot 2020-11-09 at 16 32 38 | Screen Shot 2020-11-09 at 16 32 53

#### Testing instructions

- Sandbox the API and apply D52453-code and D52422-code.
- Create a variety of posts containing blocks affected by the issues noted in https://github.com/Automattic/wp-calypso/issues/46961:
  - File block.
  - Blocks with `figcaption` elements (e.g. Gallery block).
  - Separator block.
  - HTML block.
  - Posts without title.
- Make sure they are displayed correctly.

Fixes https://github.com/Automattic/wp-calypso/issues/46961

### CODE REVIEW

**Comment by kwight** [comment]
This is still active in a way – additional research and troubleshooting is happening in https://github.com/Automattic/wp-calypso/issues/46961.

**Comment by krymson24** [comment]
I tried to understand the root cause of the problem @mmtr and documented my findings here: https://github.com/Automattic/wp-calypso/issues/46961

These are the changes I concluded on: D52422-code after attempting to find a stable state with the frontend by reverting a couple of commits, and trying your changes (and working with your changes here).

**Comment by mmtr** [comment]
Thanks @krymson24!

I think the underlying issue is on the parsing logic we have in the notifications JS code and you're right that is not affecting only empty ranges. I found an error on my initial approach trying to fix the issue so I tried to refactor it in my latest commit with a hopefully more simple and robust implementation, and it seems to be working now. Can you take a look at it?

If we manage to fix the parsing logic we wouldn't need the workarounds you added in D52422-code.

**Comment by kwight** [comment]
I'm seeing a mix of success. Broken words are definitely better (and the `figcaption` support helps), but certain things seem more broken, like galleries and maybe CSS clearing?..

Before | After
--- | ---
Screen Shot 2020-11-09 at 9 58 26 AM | Screen Shot 2020-11-09 at 9 58 03 AM
Screen Shot 2020-11-09 at 9 59 26 AM | Screen Shot 2020-11-09 at 9 59 13 AM

**Comment by krymson24** [comment]
Seeing the same with just your branch

Screen Shot 2020-11-09 at 4 56 55 PM

Screen Shot 2020-11-09 at 4 56 48 PM

**Comment by krymson24** [comment]
With both our changes:

Screen Shot 2020-11-09 at 5 05 00 PM
Screen Shot 2020-11-09 at 5 05 06 PM

**Comment by krymson24** [comment]
Just my changes:

Screen Shot 2020-11-09 at 5 13 06 PM
Screen Shot 2020-11-09 at 5 12 48 PM

**Comment by krymson24** [comment]
@mmtr I tested on a post which I'll send to you via Slack DM which throws an error.

It happens here:

```
	ranges_copy.forEach( () => {
		const id = find_largest_range( ranges_copy );
		const range_len = ranges[ id ].indices[ 1 ] - ranges[ id ].indices[ 0 ];
		if ( range_len > 0 ) {
			for ( let i = ranges[ id ].indices[ 0 ]; i < ranges[ id ].indices[ 1 ]; i++ ) {
				t[ i ].index.push( { id: id, len: range_len } );
			}
		} else {
			  t[ ranges[ id ].indices[ 0 ] ].index.push( { id: id, len: range_len } ); // <------------
		}
		// Clear out the currently-selected range so that it won't
		// return as the largest range in the next loop iteration
		ranges_copy[ id ] = null;
	} );
```

I think the fix is 

```
	if ( text.length > 0 ) {
		for ( let i = 0; i <= text.length; i++ ) {
			t[ i ] = { index: [] };
		}
	} else {
		t.push( { index: [] } );
	}
```

which ends up making it not crash the app.

I'm going to push the change up in attempt to help!

**Comment by krymson24** [comment]
I tried a couple of things here:

```
		preg_match_all('/<figure/', $clean_html, $matches, PREG_OFFSET_CAPTURE);
		$split_html = str_split($clean_html);
		foreach ( $matches[0] as $value ) {
			$index = $value[1];
			for ($i = $index; $i < strlen($clean_html); $i++) {
				if ($split_html[$i] === '>' && $split_html[$i + 1] === '<' && substr($clean_html, $i + 1, 9)  !== '</figure>') {
					$split_html[$i] = '>&nbsp;';
				  break;
				}
			}
		}
```

Basically this adds a space for where a `figure` tag ends

```
		preg_match_all('/<figure/', $clean_html, $matches, PREG_OFFSET_CAPTURE);
		$split_html = str_split($clean_html);
		foreach ( $matches[0] as $value ) {
			$index = $value[1];
			// $partial_html = ($clean_html, $index, strlen($clean_html));
			for ($i = $index; $i < strlen($clean_html); $i++) {
				if ($split_html[$i] === '>' && substr($clean_html, $i + 1, 11)  === '<figcaption') {
					$split_html[$i + 1] = '&nbsp;<';
				  break;
				}
			}
		}
```

For when a `figure` is proceeded by a `figcaption`

Neither of these worked or were ideal.

I also removed

```
$clean_html = preg_replace( '/<hr class="wp-block-separator">/', "<hr class='wp-block-separator'>&nbsp;", $clean_html );

```
in favour of @mmtr start index = stop index logic.

```
$clean_html = preg_replace( '/\/a><a/', '/a>&nbsp;<a', $clean_html );
```

was also unnecessary.

I made these changes here: D52422-code and incorporated @mmtr 's changes from here: D52453-code

When you combine it with https://github.com/Automattic/wp-calypso/pull/46965 it all looks pretty good! The unfortunate part is that my changes introduce extra spaces as you'll notice when testing with @kwight 's test notification

**Comment by mmtr** [comment]
Alright, I pushed out a few more updates to this PR and D52453-code in order to fix the root issues. I addressed a bunch of them, but couldn't find out why the notification builder doesn't generate correct ranges for `figure` and `figcaption`. At least I'm sure the issue is on the server, since the API already returns invalid ranges. That means that the rendering logic in the client should be more solid now.

Anyway, D52422-code indeed avoids the issue by adding extra whitespaces so the builder no longer generate invalid builds, making the test post to look great in the notifications:

1 | 2 | 3 | 4 | 5
--- | --- | --- | --- | ---
Screen Shot 2020-11-10 at 17 05 42 | Screen Shot 2020-11-10 at 17 05 50 | Screen Shot 2020-11-10 at 17 05 57 | Screen Shot 2020-11-10 at 17 06 04 | Screen Shot 2020-11-10 at 17 06 12 | Screen Shot 2020-11-10 at 17 06 19

**Comment by krymson24** [comment]
🔥 
Screen Shot 2020-11-10 at 12 26 50 AM
Screen Shot 2020-11-10 at 5 53 56 PM
Screen Shot 2020-11-10 at 5 54 01 PM
Screen Shot 2020-11-10 at 5 53 35 PM
Screen Shot 2020-11-10 at 5 53 40 PM
Screen Shot 2020-11-10 at 5 53 45 PM
Screen Shot 2020-11-10 at 5 53 49 PM

**Review by krymson24 — APPROVED** [review]

**Pull request merged**
