### PR TITLE
Components: Move search into @automattic/components

### PR DESCRIPTION
**Pull request by sarayourfriend**
#### Changes proposed in this Pull Request

* Moves the `search` component into `@automattic/components` package now that the WordPress monorepo update is completed and the SSR issues are resolved.

After this is merged I will open another PR to move the language picker into `@automattic/components`

#### Testing instructions

* Test several entrypoints to ensure that SSR is working
* Test the language picker at `/me/account` and ensure that search continues to work.
* Run storybook and test the search component's story

### CODE REVIEW

**Comment by sarayourfriend** [comment]
Unfortunately it looks like there are still some SSR issues with @wordpress/components so this PR isn't possible yet.

**Comment by scinos** [comment]
Out of curiosity, why we want to do this? In my mind we would want to have more granular packages, not a monolithic one.

**Comment by sarayourfriend** [comment]
@scinos That's a good question and I'm really not sure of the answer. I know this was something that @griffbrad asked me to take care of once we could do it (or at least I thought he asked me to do so). It was originally the plan to move these components into the `components` package too, we only did them outside of that package due to SSR issues with WordPress/components packages.

**Comment by lynnbgriffith** [comment]
We've discussed doing per-component packages and versioning in the past. There are certainly some advantages for consumers of the packages, but it also introduces some complexity. What if component x requires one version of `Button` and component y requires a different version that renders differently? I think those concerns are bigger in the context of wp-admin, where components are externalized rather than bundled and different block authors are building and deploying independently. In the context of Calypso, I'd be open to revisiting that conversation if folks feel strongly about it.

**Pull request closed without merging**
