### PR TITLE
Reader: hide post header for feed and blog streams

### LINKED ISSUE #3639: Reader: post card header should not be clickable in site and feed streams
When in a site or feed stream on the Reader, it is still possible to click the top of the post card, which links to the current page. 

Nothing happens, and the clicks get added to the history, which makes using the '< Back' link quite confusing:

https://cloudup.com/iyvi5ZDMVSw

#### Steps to reproduce
1. Starting at a feed stream, e.g. https://wpcalypso.wordpress.com/read/blog/feed/38960801
2. Click the site name or URL in the header of a post card
3. Try and navigate using the '< Back' link at the top of the page 

#### What I expected

The post card header should not link anywhere if you're browsing a blog or feed stream.

### PR DESCRIPTION
**Pull request by bluefuton**
On feed and blog streams, the post card header has no purpose, and clicking it doesn't take you anywhere. This PR removes it for those streams only.

Before:

screen shot 2016-03-01 at 11 57 06

After:

screen shot 2016-03-01 at 12 46 56
screen shot 2016-03-01 at 12 47 10

Example streams:

http://calypso.localhost:3000/read/feeds/40474296
http://calypso.localhost:3000/read/blogs/82798297

Fixes #3639.

### CODE REVIEW

**Comment by jancavan** [comment]
Design :+1:

**Comment by blowery** [comment]
Wow I dig how this looks. Takes me back to the early visions for calypso reader where the site info was below the feature, not above it. 

This especially looks good on Discover. @kjellr 

:ship:

**Comment by blowery** [comment]
Actually, do we need a touch more margin above the heading if no feature is present?

**Comment by blowery** [comment]
@jancavan could you give this another look? I gave the titles a bit more room on headerless posts that have no feature. Felt too tight. We only use that 16px top padding on cards now because usually the site info is there and 16px looks better than 24. But when it's just the title, 24 looks better to my eye.

**Comment by jancavan** [comment]
@blowery Good call. Made a small adjustment https://github.com/Automattic/wp-calypso/commit/2d2ee701886769ce15c2e840175a074ddf503846.

**Comment by bluefuton** [comment]
Thanks @jancavan! Looks great.

**Comment by apeatling** [comment]
Some back history on this one -- we added headers to everything before because it made it really hard for people with a typical resolution screen to tell where the post before ended and the new post started.

**Pull request merged**
