### PR TITLE
Revert "Plan Overhaul revert "

### PR DESCRIPTION
**Pull request by claudiucelfilip**
Reverts Automattic/wp-calypso#64370

### CODE REVIEW

**Review by gmovr — APPROVED** [review]
Thanks LGTM

**Review by gius80 — APPROVED** [review]
LGTM 👍

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/7450992

Hi @claudiucelfilip, could you please edit the description of this PR and add a screenshot for our translators? Ideally it'd include this string: `With your plan, all WordPress.com advertising has been removed from your site. You can upgrade to a Business plan to also remove the WordPress.com footer credit.`

Thank you in advance!

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/7450992).

**Pull request merged**
