### PR TITLE
Fix the round corners of the design previews are cut

### PR DESCRIPTION
**Pull request by miksansegundo**
#### Proposed Changes

* Fix for the duplicated border on the browser header on the design preview

#### Testing Instructions

- Visit [https://wordpress.com/setup/designSetup?siteSlug={site](https://wordpress.com/setup/designSetup?siteSlug=%7Bsite) slug} with the goal Write and publish.
- Click on a design
- Check that the border on the browser header looks like this
Screen Shot 2565-08-18 at 09 43 00

#### Pre-merge Checklist

- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?

Related to #66596

### CODE REVIEW

**Comment by miksansegundo** [comment]
@arthur791004 I have fixed the issue, but maybe we could remove those styles because they seem duplicated.

The double border is caused by the CSS file for the signup in [client/signup/steps/design-picker](https://github.com/Automattic/wp-calypso/blob/trunk/client/signup/steps/design-picker/preview-toolbar.scss#L60) because we use a different CSS file for the same preview in the landing [client/landing/stepper](https://github.com/Automattic/wp-calypso/blob/trunk/client/landing/stepper/declarative-flow/internals/steps-repository/design-setup/preview-toolbar.scss#L84).

Do you know why we have two different files for the same component?

**Comment by arthur791004** [comment]
I thought the problem is we imported `PreviewToolbar` from [launchpad](https://github.com/Automattic/wp-calypso/blob/trunk/client/landing/stepper/declarative-flow/internals/steps-repository/launchpad/launchpad-site-preview.tsx#L4). Thus, I think we just need to change the import from the `signup` to the `stepper`

```diff
- import PreviewToolbar from 'calypso/signup/steps/design-picker/preview-toolbar';
+ import PreviewToolbar from '../design-setup/preview-toolbar';
```

And you could create a newsletter site from `/setup/newsletterSetup?flow=newsletter` and land on launchpad preview to ensure everything works as before

Here is the screenshot of the result

image

> Do you know why we have two different files for the same component?

The reason is when some team works on the stepper flow, it's a big project to migrate all of the components from signup to stepper. But we're still working on signup flow. Therefore, they copied those components to the stepper flow. I think we could review whether the duplicate components are still in use or not. But I think the "Do it for me" flow (See `/start/website-design-services?siteSlug=<your_site>`) keeps in signup flow and uses the original design picker 😅

cc @Automattic/cylon

**Comment by agrullon95** [comment]
@arthur791004 / @miksansegundo , Thanks for getting back to me. These changes should be good. As long as it fixes your design preview, don't worry about it affecting the launchpad page. We're constantly changing the design for the launchpad, so I can always go back and make changes to the styling.

**Comment by arthur791004** [comment]
Hmmm... I think we have to update the import path instead of changing the styles as it works before that changes 😅

**Pull request merged**
