### PR TITLE
Framework: Downgrade to immutable 3.7.6

### PR DESCRIPTION
**Pull request by blowery**
Matches draft-js and shrinks the bundle that uses draft-js by quite a bit.

### CODE REVIEW

**Comment by blowery** [comment]
sizes after:
```
                     media.d4aab911776e54295156.js   193 kB      20  [emitted]  media
                   commons.0f8539e1b908002b2917.js   618 kB       0  [emitted]
               post-editor.c81c33c447be28539f9b.js  3.05 MB       2  [emitted]  post-editor
               posts-pages.a144157f59d36f46544f.js   329 kB       3  [emitted]  posts-pages
reader-post-recomendations.e044fec29dcdbed0bec0.js    25 kB       4  [emitted]  reader-post-recomendations
                  upgrades.61ebf8c39b4369eb1a21.js   780 kB       5  [emitted]  upgrades
                    signup.978cf566909fe70e1d02.js   633 kB       6  [emitted]  signup
               reader-tags.698e65d12840f4792834.js    14 kB       7  [emitted]  reader-tags
              settings-seo.df56f82259e9630aa4ac.js   510 kB       8  [emitted]  settings-seo
                  settings.f42a0ddf96aedc6314a4.js   505 kB       9  [emitted]  settings
                   plugins.4e037a13b1d7ba8c222f.js   531 kB      10  [emitted]  plugins
                     stats.3656b0e61abe269cb532.js   356 kB      11  [emitted]  stats
                     plans.3912d15438fd208891e9.js   253 kB      12  [emitted]  plans
                  security.0035575a5c951a28b58a.js   327 kB      13  [emitted]  security
                 purchases.18294f8e237bd86c0895.js   322 kB      14  [emitted]  purchases
                     menus.b1e28fd3d896fc973ee9.js   331 kB      15  [emitted]  menus
                      help.f19d3730b6f474ec4f7c.js   229 kB      16  [emitted]  help
     notification-settings.9c75dae7e3060f6e9492.js   213 kB      17  [emitted]  notification-settings
                    people.867577671c4942423b83.js   231 kB      18  [emitted]  people
              posts-custom.1b8cb5b4e1e115b15f64.js   187 kB      19  [emitted]  posts-custom
                    reader.647fa3a0c1bf7cdc1cb9.js   219 kB       1  [emitted]  reader
                   sharing.be6749686ed49dcc1baa.js   204 kB      21  [emitted]  sharing
                   billing.b2750c5af9f85ac72009.js   153 kB      22  [emitted]  billing
                    themes.ccd4c54854341d78b4e7.js   155 kB      23  [emitted]  themes
           payment-methods.86c533a73b649f06a91a.js   151 kB      24  [emitted]  payment-methods
                   account.6b31443cec8daddb0485.js   139 kB      25  [emitted]  account
          reader-following.845242c1af58d956d7b8.js   102 kB      26  [emitted]  reader-following
                     theme.fc9de75f2b7a286048db.js   113 kB      27  [emitted]  theme
              reader-start.7b725bb27f18976e7ac4.js   131 kB      28  [emitted]  reader-start
             accept-invite.d2ee3a7bc1b0aafd43d7.js   125 kB      29  [emitted]  accept-invite
                        me.39c07e319fd701fe4841.js    99 kB      30  [emitted]  me
               reader-list.c825de41992f5398f662.js  66.7 kB      31  [emitted]  reader-list
                       ads.153264644752846a7d77.js  68.7 kB      32  [emitted]  ads
                 customize.ae066c01e3e503537798.js    28 kB      33  [emitted]  customize
             reader-search.74d4c2ab512a1aea34b5.js  26.3 kB      34  [emitted]  reader-search
         reader-activities.e6f43b38e5fa6f24c326.js  5.58 kB      35  [emitted]  reader-activities
             mailing-lists.534057fa02bb97b3d915.js  10.8 kB      36  [emitted]  mailing-lists
                   paladin.f7609d84c7ee834e6fa8.js  3.07 kB      37  [emitted]  paladin
                  discover.a69837ff2738707008c3.js  3.15 kB      38  [emitted]  discover
                    vendor.0f8539e1b908002b2917.js   458 kB      39  [emitted]  vendor
          build-production.0f8539e1b908002b2917.js  4.87 MB      40  [emitted]  build-production
```

**Comment by blowery** [comment]
before:
```
                     media.427329c8e9348fd8c7dc.js   193 kB      20  [emitted]  media
                   commons.4ed7053a9db4d6429638.js   618 kB       0  [emitted]
               post-editor.92875af8298f9f666e26.js  3.05 MB       2  [emitted]  post-editor
               posts-pages.3f031a6d31a136fe43e1.js   329 kB       3  [emitted]  posts-pages
reader-post-recomendations.edd45996e3f4adad9996.js    25 kB       4  [emitted]  reader-post-recomendations
                  upgrades.503e488be7b852f6d012.js   780 kB       5  [emitted]  upgrades
                    signup.484f5005054a447a14d1.js   633 kB       6  [emitted]  signup
               reader-tags.3b1be946095153350ff6.js    14 kB       7  [emitted]  reader-tags
              settings-seo.494447991c57c211b08d.js   657 kB       8  [emitted]  settings-seo
                  settings.e7fd42ca5d4c1edd0945.js   505 kB       9  [emitted]  settings
                   plugins.8faab09b90fe31591a88.js   531 kB      10  [emitted]  plugins
                     stats.e71881d7688a15d85768.js   356 kB      11  [emitted]  stats
                     plans.ce09c8842d1baf9eaf46.js   253 kB      12  [emitted]  plans
                  security.3922725904ef776aeaec.js   327 kB      13  [emitted]  security
                 purchases.b075fa7575f8a81f2892.js   322 kB      14  [emitted]  purchases
                     menus.4e6e0dad2747dde7515b.js   331 kB      15  [emitted]  menus
                      help.e3482619c3cba334526c.js   229 kB      16  [emitted]  help
     notification-settings.4ee838c15d50f39f0b9c.js   213 kB      17  [emitted]  notification-settings
                    people.61b88d2f1f986e852c7a.js   231 kB      18  [emitted]  people
              posts-custom.7aa51b4afdbbbc82761b.js   187 kB      19  [emitted]  posts-custom
                    reader.3de91da60d897f536d91.js   219 kB       1  [emitted]  reader
                   sharing.3b71060e08255151a760.js   204 kB      21  [emitted]  sharing
                   billing.d8d99cf550a902b7546d.js   153 kB      22  [emitted]  billing
                    themes.060cd6ad50e3cf23ea5c.js   155 kB      23  [emitted]  themes
           payment-methods.88649c67aee5c5977585.js   151 kB      24  [emitted]  payment-methods
                   account.75712b476b1ff2de1530.js   139 kB      25  [emitted]  account
          reader-following.532125c4cfabe77c4f3a.js   102 kB      26  [emitted]  reader-following
                     theme.7ba46992c72f4955989b.js   113 kB      27  [emitted]  theme
              reader-start.d2487efb069dc136c58e.js   131 kB      28  [emitted]  reader-start
             accept-invite.9677be1894e6da5d89c3.js   125 kB      29  [emitted]  accept-invite
                        me.5a1ce654bbb55b2af080.js    99 kB      30  [emitted]  me
               reader-list.e4f5cbdecfba2f18a5d9.js  66.7 kB      31  [emitted]  reader-list
                       ads.c6f10955dae7bfbe0556.js  68.7 kB      32  [emitted]  ads
                 customize.e307bb6dfaa006377d24.js    28 kB      33  [emitted]  customize
             reader-search.d81a1e9446c2ba71b60e.js  26.3 kB      34  [emitted]  reader-search
         reader-activities.9c63aa03bf985a1a150b.js  5.58 kB      35  [emitted]  reader-activities
             mailing-lists.49f4769b79b9be7afd4c.js  10.8 kB      36  [emitted]  mailing-lists
                   paladin.24850a4293f2e30a3529.js  3.07 kB      37  [emitted]  paladin
                  discover.38bb8607528ac7e3771e.js  3.15 kB      38  [emitted]  discover
                    vendor.4ed7053a9db4d6429638.js   458 kB      39  [emitted]  vendor
          build-production.4ed7053a9db4d6429638.js  4.87 MB      40  [emitted]  build-production
```

**Comment by blowery** [comment]
The relevant drop is in `settings-seo.494447991c57c211b08d.js`

657kb before
510kb after

**Comment by aduth** [comment]
Are we losing much from the bugfixes / improvements in more recent versions?

https://github.com/facebook/immutable-js/releases

Otherwise I'd agree it'd be a good idea to keep these in sync so we're not pulling in more than one version.

**Comment by blowery** [comment]
It's apparently not enough to get draft to bump up to latest... Honestly /shrug. Not sure how to evaluate it.

**Comment by aduth** [comment]
>Not sure how to evaluate it.

Pull request to draft-js for an upgrade there?

Otherwise, ran through a few of the new features and bug fix items in recent versions and can't find any cases where we're using or would otherwise obviously benefit from them in current codebase. Should be fine?

**Comment by blowery** [comment]
> Should be fine?

Yup, think so.

**Comment by gwwar** [comment]
LGTM :shipit:

**Comment by blowery** [comment]
I'm going to re-rebuild the shrinkwrap before I land this. Been a while.

**Comment by aduth** [comment]
To keep an eye on: https://github.com/facebook/draft-js/pull/760

**Comment by gwwar** [comment]
I tested it locally with a rebase and another shrinkwrap generation, nothing interesting besides a few minor package bumps.

**Comment by blowery** [comment]
@gwwar thanks!

**Pull request merged**
