### PR TITLE
Decrease grid gap sizes to increase image size in design view

### LINKED ISSUE #49382: New Onboarding: Improve design preview layout
#49170 introduced landscape design previews for onboarding's `/new/designs`. @simison [noticed](https://github.com/Automattic/wp-calypso/pull/49170#issuecomment-767476316) that the spacing between designs and size of the images displayed at different breakpoints could use some debugging to avoid tiny images in some situations.

#### What we need:
Images to be legible at as many breakpoints as possible

#### How:
I suspect you'll need a mix of both reworking breakpoints, and reducing the column [gap size.](https://github.com/Automattic/wp-calypso/blob/ed3e91545e431da92beeffcbe80289eadde067c0/client/landing/gutenboarding/onboarding-block/design-selector/style.scss#L67)

#### Why:
At some breakpoints the design previews become very small where as they eventually snap larger at a smaller breakpoint with less columns. It isn't possible to remove this effect completely but currently images get way too small to be reasonable, we'd like them to jump to the larger size / less columns sooner. 

https://user-images.githubusercontent.com/87168/105838025-3283b880-5fd8-11eb-95a1-66e5221d0c9a.mov

### PR DESCRIPTION
**Pull request by lsl**
#### Changes proposed in this Pull Request

* Decrease grid gap sizes to increase image size in design view

#### Testing instructions

* View design grid at various screen breakpoints and make sure image sizes are suitable.

Fixes #49382

### CODE REVIEW

**Comment by ollierozdarz** [comment]
@lsl I think this gap size change is looking good! The only recommendation I'd make is that it would feel nicer to snap to the 2-col design grid from 1024px and smaller (right now it's at 960px).

**Comment by lsl** [comment]
https://user-images.githubusercontent.com/811776/106560554-4fd9f900-657b-11eb-9f3f-1238cf7965bd.mp4

This look better?

I tried dropping down to a single column earlier too but prefer what we have, even if things do get a little small. I could try to set a max width for those situations if you'd prefer that otherwise lets go with this.

**Comment by ollierozdarz** [comment]
@lsl this feels great, nice job! 🙂 We can always iterate on it after we properly use it for a while.

**Comment by simison** [comment]
Nice! Definitely good to ship already as-is.

Looking at screencapture, it felt a bit like last 4 columns could be skipped and just kept at 3 — curious for your thoughts @ollierozdarz.

**Comment by ollierozdarz** [comment]
> Looking at screencapture, it felt a bit like last 4 columns could be skipped and just kept at 3 — curious for your thoughts @ollierozdarz.

@simison yeah, I agree. I looked at all our competitors and the most they ever seem to show is 3-cols of designs (for their showcases at least). So at the biggest viewport we could show 3-cols instead of 4-cols and just expand the size of the cards if needed 🙂

**Review by ramonjd — APPROVED** [review]
Checked in Chrome, FF, and IE Edge and IE 11 at different browser widths

There's a slight regression in IE11, where the third col isn't displaying:

**Before**
Screen Shot 2021-02-03 at 11 49 31 am

**After**
Screen Shot 2021-02-03 at 11 49 26 am

Microsoft s[topped supporting Internet Explorer 11 in November, 2020 ](https://techcommunity.microsoft.com/t5/microsoft-365-blog/microsoft-365-apps-say-farewell-to-internet-explorer-11-and/ba-p/1591666) so I think it's good to go

**Comment by ramonjd** [comment]
I wanted to return to make sure that WordPress.com isn't too fussed about IE 11. 

We do have information for the user about browser support here: https://wordpress.com/support/browser-issues/#supported-browsers It recommends to use the latest from browsehappy.

Also, browser stats on the `calypso_signup_complete` event, for example, show a very low (I mean very low, actually, the lowest) frequency of IE compared with Edge.

**Comment by lsl** [comment]
> So at the biggest viewport we could show 3-cols instead of 4-cols and just expand the size of the cards if needed

@ollierozdarz I took a look at this and didn't like the result too much, if you think we do need this I'm happy to look at it in a follow up. We would need to increase the image size we fetch from mshots because at 3 columns the images stretch to a blurred state when the window is too large.

**Comment by ollierozdarz** [comment]
@lsl no problems. I don't think this is critical at all, more so just a nice end state 🙂

**Comment by simison** [comment]
@ramonjd we do support IE11 still (important e.g. for screen-readers) but it's enough for it to be functional, it's okay if it doesn't look the same pixel-to-pixel.

**Pull request merged**
