### PR TITLE
Emails: Update features and pricing on email providers comparison page 

### PR DESCRIPTION
**Pull request by eltongo**
#### Changes proposed in this Pull Request

This PR updates the price and features of Titan in the email providers comparison page.

Screenshot 2020-10-07 at 4 45 19 PM

#### Testing instructions

* Load Calypso with the `email/titan-mvp` flag enabled (append `?flags=email/titan-mvp` to the URL)
* Go to your site domains, and click "Add" under the email column for one of your domains
* Confirm you see the same thing as the screenshot above

### CODE REVIEW

**Review by fditrapani — APPROVED** [review]
The updates look good thanks!

This is unrelate to this PR but is there anyway we can update the features so that the we don't get any single words appearing on a line on their own. These single words are referred to as [orphans](https://www.fonts.com/content/learning/fontology/level-2/text-typography/rags-widows-orphans) and have an impact on reducing readability. 

We typically fix this in regular HTML by adding a `nbsp;` between the last two words but I'm not sure if we would do that due to the translations here. 

image

**Comment by eltongo** [comment]
> The updates look good thanks!
> 
> This is unrelate to this PR but is there anyway we can update the features so that the we don't get any single words appearing on a line on their own. These single words are referred to as [orphans](https://www.fonts.com/content/learning/fontology/level-2/text-typography/rags-widows-orphans) and have an impact on reducing readability.
> 
> We typically fix this in regular HTML by adding a `nbsp;` between the last two words but I'm not sure if we would do that due to the translations here. This would be the ideal outcome:
> 
> image

Thanks for your review. In the meantime I'll see what we can do about the orphan words.

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/4879211

Thank you @eltongo for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/4879211).

**Pull request merged**
