### PR TITLE
Guided Tours: Remove obsolete simple payments tour

### PR DESCRIPTION
**Pull request by tyxla**
We're currently loading an obsolete simple payments tour that expects that the good old Calypso editor is there. But we removed the editor, so that tour is now obsolete and can be removed. This PR removes it.

#### Changes proposed in this Pull Request

* Guided Tours: Remove obsolete simple payments tour

#### Testing instructions

* Nothing to test, so just verify we're removing all references of the simple payments guided tour.

### CODE REVIEW

**Review by jsnajdr — APPROVED** [review]
Nice :+1:

There's also `editorBasicsTour` that's never active after the Classic Editor removal. Its steps target CSS class names specific for the Classic Editor and TinyMCE.

**Comment by tyxla** [comment]
Thanks, Jarda!

> There's also `editorBasicsTour` that's never active after the Classic Editor removal. Its steps target CSS class names specific for the Classic Editor and TinyMCE.

💯 Yup, that's the next one on my list 😉  I'm just planning to tackle them one by one; maybe we can salvage something instead of deleting them all.

**Comment by jsnajdr** [comment]
> I'm just planning to tackle them one by one; maybe we can salvage something instead of deleting them all.

Actually, removing all Calypso Guided Tours sounds very attractive 🙂 And possibly replacing them with some NUX based on Core/Gutenberg. I don't know what's the state-of-art there.

**Comment by tyxla** [comment]
> Actually, removing all Calypso Guided Tours sounds very attractive 🙂 

😬

> And possibly replacing them with some NUX based on Core/Gutenberg. I don't know what's the state-of-art there.

I think the [NUX package](https://github.com/WordPress/gutenberg/tree/master/packages/nux) is a way to do similar things, but I haven't tried it myself. The [guide section](https://github.com/WordPress/gutenberg/tree/master/packages/nux#triggering-a-guide) seems very reminiscent of what guided tours are doing. Definitely worth exploring.

**Comment by jsnajdr** [comment]
The `nux` package is now deprecated in favor of the `Guide` component in `components`: https://github.com/WordPress/gutenberg/blob/master/packages/nux/CHANGELOG.md#310-2019-06-03 That's all I know, and agree that `Guide` is still worth exploring in Calypso.

**Pull request merged**
