### PR TITLE
Framework: Remove keyboard shortcuts

### PR DESCRIPTION
**Pull request by tyxla**
#### Changes proposed in this Pull Request

Calypso's keyboard shortcuts feature is an artifact of its pre-OSS era, started in February 2015 and developed in the following months. It was never finished, though, and was never even put for broader testing. It has never been enabled in staging/production and is currently available only on dev and wpcalypso environments. 

My brief research displayed that nobody was using keyboard shortcuts, and there were folks who ended up inadvertently doing something with a shortcut. So it's time to clean that feature up. If we ever decide to have a keyboard shortcuts feature, we'd likely use the Gutenberg [Keyboard Shortcuts](https://github.com/WordPress/gutenberg/tree/trunk/packages/keyboard-shortcuts) package for a base.

This PR cleans all keyboard shortcuts functionality altogether, as well as some related reader state that was used only for keyboard shortcuts.

#### Testing instructions

* Verify Calypso builds with no errors.
* Smoke test Reader and inline help.
* Verify the removed code is not in use.
* Verify tests pass.

### CODE REVIEW

**Comment by tyxla** [comment]
@jsnajdr if this is right, it looks like it has a nice impact on the inline help extraction project:

```
name                                      parsed_size            gzip_size
async-load-calypso-blocks-inline-help     -12080 B   (-47.8%)    -3981 B   (-48.1%)
```

**Comment by flootr** [comment]
There's also a bunch of keyboard shortcut related code in `apps/notifications`. Shall we remove it from there as well?

**Comment by tyxla** [comment]
> There's also a bunch of keyboard shortcut related code in `apps/notifications`. Shall we remove it from there as well?

Yes, we could, but it's completely separate and unrelated to the keyboard shortcuts module in Calypso. I think that if we consider removing it, we should do it in another PR.

**Review by flootr — APPROVED** [review]
Reader and Inline Help work great for me 👍🏻 I also couldn't find any left occurrences of keyboard usage in Calypso.

**Comment by sirbrillig** [comment]
>  It has never been enabled in staging/production and is currently available only on dev and wpcalypso environments.

I'm not certain, but I think this might have removed the `j/k/enter/escape` (next/previous/select/back) keyboard shortcuts in the Reader, which were definitely available in production. We may want to consider if that's a UX change we really want to make since now I think there's no longer a way to navigate the Reader without a mouse.

**Comment by tyxla** [comment]
> I'm not certain, but I think this might have removed the `j/k/enter/escape` (next/previous/select/back) keyboard shortcuts in the Reader, which were definitely available in production. We may want to consider if that's a UX change we really want to make since now I think there's no longer a way to navigate the Reader without a mouse.

Yes, it did. FWIW, this was never deemed a tested and working feature and I believe it was inadvertently put to production. Any other keyboard shortcut functionality was behind the dedicated feature flag. A user had no real way to know those shortcuts exist, and could sometimes inadvertently trigger them, not understanding how and what happened. I'm happy to discuss, but I still believe that this should have gone with the rest of the unpolished keyboard shortcuts functionality.

**Comment by sirbrillig** [comment]
I suppose that's fair. I'll miss this feature myself since it's been available for so long (intentionally or not) 😢. It's similar to the GMail shortcuts and made it quick to burn through my p2s, but maybe I'm the only one who was using it heavily and I understand that the architecture was very old. 

Still worth noting here that it was available in production in case anyone else comes looking for where it went.

Here's me hoping for a replacement Reader keyboard shortcut system in the future! 🤞

**Comment by pento** [comment]
Oh, this is why keyboard shortcuts in the reader suddenly stopped working today. 😕

I don't think this was quite as undiscoverable as you might think. Just because it isn't documented doesn't mean that people won't try it: `j/k` are also available as shortcuts in p2, and are commonly used as next/previous shortcuts in many web apps (it works in 4 of the first 5 relevant tabs I have open: Gmail ✅, Newsblur ✅, Reader ❌, Twitter ✅, P2 ✅). Similarly, Gutenberg uses `arrows/enter/escape` for navigating between, in, and out of blocks.

I appreciate the desire to remove crufty old code, but we should ideally aim to have a replacement ready to drop in, particularly for otherwise harmless accessibility features.

**Comment by tyxla** [comment]
I'm surprised this is used that much (considering that the rest of those shortcuts were disabled in staging/production), but I'm happy to explore a more modern and simplistic approach to support those shortcuts. In any case, we needed to migrate the old module, and building the necessary features from scratch will actually be easier.

**Comment by tyxla** [comment]
Okay, @pento @sirbrillig, I'm re-implementing Reader keyboard shortcuts in #60812. It's in progress, but it'll be ready soon. Thanks for bringing this up!

**Comment by pento** [comment]
Awesome, thanks for jumping on it so quickly, @tyxla! 🎉

**Comment by tyxla** [comment]
#60812 was reverted, but I just opened take 2 in #61112.

Also, just realized we no longer use `keymaster`, so I'm removing it in #61114.

**Pull request merged**
