### PR TITLE
MagicSearch: add terms and filters to analytics on search.

### PR DESCRIPTION
**Pull request by budzanowski**
### Info
We want `calypso_themeshowcase_search` in MagicSearch to be backwards compatible and store new information. 
 - Backward compatibility requires that we store full entered search string in `search_term` field. We are doing a simplified version of that because we are recreating this from search and filter values. After recreating the string if functionally equivalent to the one from input ( only the order of elements may be different ). Befor this PR we have storred only the non taxonomy:filter part. 
 - The new implemented feature is the `search_taxonomies` field is a string with all taxonomy:filter values.

This is how it looks on tracks:
image

### Testing
Search using filters and text and observe tracks( you need to wait a couple of minutes )

### CODE REVIEW

**Comment by seear** [comment]
By the way, you can use `localStorage.setItem('debug', 'calypso:analytics:tracks');` for testing.

**Comment by folletto** [comment]
Tested both in console (thanks Steve) and Live:

screen shot 2017-03-20 at 14 29 08

screen shot 2017-03-20 at 14 33 42

**Comment by seear** [comment]
We need to update call for [theme activation](https://github.com/Automattic/wp-calypso/blob/240c2291b978fdbe339b9256bad49ca55376e526/client/state/themes/actions.js#L415) and [theme click](https://github.com/Automattic/wp-calypso/blob/240c2291b978fdbe339b9256bad49ca55376e526/client/my-sites/themes/themes-selection.jsx#L73).

**Comment by budzanowski** [comment]
I think that null just hides the field in tracks. At least this is how it always was used so I kept it.

**Comment by budzanowski** [comment]
[Themes: Update analytics for M5 (2)](https://trello.com/c/J7iZntJm/859-themes-update-analytics-for-m5-2)

**Pull request merged**
