### PR TITLE
wp-admin Site Default: Card tweaks

### PR DESCRIPTION
**Pull request by danielbachhuber**
From pdKhl6-2cJ-p2#comment-5186

## Proposed Changes

Couple of tweaks to the admin interface style card:
* Changes the description text to clarify that the setting is site-wide.
* Deep links to the relevant documentation.

CleanShot 2024-01-12 at 15 28 12@2x

## Testing Instructions

1. Create a Business site and take it Atomic.
2. Navigate to Hosting Configuration and verify the Admin interface style card looks as expected.

### CODE REVIEW

**Review by katinthehatsite — APPROVED** [review]
The changes look good to me - the wording was updated and the page jumps to a relevant section when clicking "Learn more" link: 

Screenshot 2024-01-15 at 9 23 25 AM

**Review by javierarce — APPROVED** [review]
LGTM too

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/10819302

Some locales (Hebrew, Japanese) have been temporarily machine-translated due to translator availability. All other translations are usually ready within a few days. Untranslated and machine-translated strings will be sent for translation next Monday and are expected to be completed by the following Friday.

Thank you @danielbachhuber for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/10819302).

**Pull request merged**
