### PR TITLE
Make task title clickable

### PR DESCRIPTION
**Pull request by fditrapani**
Every time I look at a task title I want to click on it because it's blue and the phrase is a command. This PR makes the task title clickable and directs user to the same location as the do it button.

rover

## Testing
* Create a new site
* Visit the checklist by going to the stats and clicking on the view checklist link
* Click on a task title and compare it it's accompanying do it button

@taggon @markryall

### CODE REVIEW

**Comment by taggon** [comment]
Yes, the title should be clickable. However, can you make the title an `<a>` element wrapped in `<h5>` instead of `Button`? It would be better if the semantic markups remain.

**Comment by fditrapani** [comment]
@taggon I sure can. Are there any issues if I use an `<a>` without an `href`?

**Comment by markryall** [comment]
Yeah good call - `<Button>` is a react component that sometimes renders an `<a>` but in this case is rendering a `<button>`. :)

**Comment by fditrapani** [comment]
All fixed up @taggon. Mind taking another look?

**Pull request merged**
