### PR TITLE
Extensions: WPJM - Eliminate use of success and failure actions for saving

### PR DESCRIPTION
**Pull request by donnapep**
This PR seeks to eliminate the `WP_JOB_MANAGER_SAVE_SUCCESS` and `WP_JOB_MANAGER_SAVE_ERROR` actions.

## How It Currently Works

When any of the _Save Settings_ buttons are clicked on a WP Job Manager form, the `WP_JOB_MANAGER_SAVE_SETTINGS ` action is dispatched, which consequently disables all of the form fields. They are re-enabled when the API request either succeeds (i.e. `WP_JOB_MANAGER_SAVE_SUCCESS` is dispatched) or fails (i.e. `WP_JOB_MANAGER_SAVE_ERROR` is dispatched).

## How This PR Works

`redux-form` has a [`submitting`](http://redux-form.com/7.0.0/docs/api/Props.md/#-submitting-boolean-) prop that indicates whether or not a form is currently submitting. This prop will only work if you pass an `onSubmit` function that returns a promise. Because we're using the data layer, our [`onSubmit` function](https://github.com/Automattic/wp-calypso/blob/70cb0daa89bf4a2767604452852f6e9d6263dfc5/client/extensions/wp-job-manager/components/settings/index.jsx#L30) doesn't return a promise; it [returns an action](https://github.com/Automattic/wp-calypso/blob/70cb0daa89bf4a2767604452852f6e9d6263dfc5/client/extensions/wp-job-manager/state/settings/actions.js#L44).

Fortunately, there are [`startSubmit`](http://redux-form.com/7.0.0/docs/api/ActionCreators.md/#-startsubmit-form-string-) and [`stopSubmit`](http://redux-form.com/7.0.0/docs/api/ActionCreators.md/#-stopsubmit-form-string-errors-object-) functions that we can use to toggle the `submitting` prop. We call `startSubmit` before dispatching the save request and `stopSubmit` once the save has completed (whether successfully or not).

By doing this, we can keep save success and failure actions out of the data layer, and don't have to get component state involved at all.

## Testing

The form fields on the _Job Listings_ and _Job Submission_ tabs should disable while saving, and re-enable once saving has completed.

### CODE REVIEW

**Comment by donnapep** [comment]
@dmsnell Further to your comment on PR #15727:

> I think in a case like forms where we want to indicate positively that we haven't heard back from our save operation then we have some local state which can help us out. We issue the action (in this case probably just SAVE_SETTINGS) and then start the indicator until the props match the local state. 

I'm using this PR to try to work through what that would look like. I see how we could get rid of one of the actions, but I don't see how we could eliminate both. I don't completely follow this bit in particular:

> ...start the indicator **until the props match the local state**.

The settings-related props are not going to change unless we explicitly fetch them again after saving. Is that what you propose we do, or something else entirely?

**Comment by dmsnell** [comment]
@donnapep at a high level the way I see it happening is something like this…

Component loads:
	 - Load settings props into local state

User changes settings:
	- Change settings in local state
	- If updates from props come, reconcile but prefer local state when the two differ

Save button clicked:
	- Update local state to indicate that we have started saving settings
	- Fire something like `SETTINGS_SAVE_REQUEST`
	- This action triggers something in the data layer to send the network call to update the settings.

API call success:	
	- When the response comes in we should probably have updated settings from the server, maybe not. Either way we finally issue `SETTINGS_UPDATE` with the changed settings.
	- The component notices the props change, compares to local state, and now that they are identical updates to show that the process has completed.

**Comment by donnapep** [comment]
@dmsnell Thanks for your thoughtful reply!

I'm not sure if you're aware, but we've started using [Redux Form](https://calypsop2.wordpress.com/2017/07/06/redux-form-for-faster-form-building/) for building forms. Managing form state locally required a good amount of boilerplate, which is one of the reasons we moved away from building forms that way.

Looks like we really only need two actions for saving a form - `WP_JOB_MANAGER_SAVE_SETTINGS` to fire off the save request and `WP_JOB_MANAGER_???`.  (I haven't come up with a suitable name just yet since it's really only needed for re-enabling the form. Suggestions welcome!) At this point though, I don't think we want to go back to trying to use component state for storing form data, especially when Redux Form has been pretty easy to use thus far and gives us bonus stuff like validation.

**Comment by dmsnell** [comment]
I've seen that Redux Form @donnapep but haven't read too deeply into it. Seems like it could still be possible to use the same idea.

We have two general types of data interactions the way I figure: we have resources we can simply retrieve and set, and we have resources that have intrinsic transition states for retrieving and setting. You seem to get all the funs ones :wink:

If we say that we need to give the extra confidence boost for someone that their settings are saved before they navigate away it falls into that camp. Otherwise a setting could be in the first category: just change it internally in Calypso and assume it works. If it comes back as a failure we can raise a notification indicating the failure and provide a retry link.

Therefore for simple interactions I think that all we need is `SETTINGS_CHANGE` to make the change and then let something in the data layer synchronize off of that action and a `SETTINGS_REQUEST` action to indicate that we need the data (when first loading the page).

For these transitional operations on save we need something more: we don't want to update global state until the customer is as confident as we are that the settings have been changed. I think we can stick with `SETTINGS_UDPATE_REQUEST` to indicate that "we really do want to change these settings," but then on return? On return it's just backwards. With simple interactions we are confident first and update; with transitional interactions we request first and then once we have confidence we `SETTINGS_UPDATE` without any suffix.

What if the internet connection were instant? We wouldn't show a spinner or anything: we'd just make the change. What action would we use? `SETTINGS_UPDATE` or something like that. Here I think the logic is the same even though the connection lags. If `SETTINGS_UPDATE` actually hits the reducer and makes the change then it's a good candidate for follow-up while practically every reducer should ignore practically every `_REQUEST` action.

This is going to make it easy to test and inject fake states into the app. Also, if we haven't made any settings changes but dispatch the `_REQUEST` it should still know that we're not waiting because app state matches the local state (even if it's in a wrapper). However, when we issue a `SETTINGS_UPDATE` then the reducers change and the wrapper changes and our components change.

**Comment by donnapep** [comment]
@dmsnell I opted for a different solution than what was originally proposed. In the end though, it achieves the intended goal of keeping the save `SUCCESS` and `_FAILURE` actions out of the data layer.

**Comment by ockham** [comment]
Overall, this sounds like a very good way out of the saving state conundrum 😄 

One question:

> `redux-form` has a [`submitting`](http://redux-form.com/7.0.0/docs/api/Props.md/#-submitting-boolean-) prop that indicates whether or not a form is currently submitting. This prop will only work if you pass an `onSubmit` function that returns a promise. Because we're using the data layer, our [`onSubmit` function](https://github.com/Automattic/wp-calypso/blob/70cb0daa89bf4a2767604452852f6e9d6263dfc5/client/extensions/wp-job-manager/components/settings/index.jsx#L30) doesn't return a promise; it [returns an action](https://github.com/Automattic/wp-calypso/blob/70cb0daa89bf4a2767604452852f6e9d6263dfc5/client/extensions/wp-job-manager/state/settings/actions.js#L44).

Do we actually need/use that returned action? What's relevant to us is that it's being dispatched -- we don't care so much that `onSubmit` actually returns an action, do we? Wondering if we could write some sort of promise factory that's able to listen to actions such as `announceSuccess`/`announceFailure`, and that we'd use from within `onSubmit`.

The main advantage I'd see would be that it'd enable us to remove redux-form specific code from our own actions (and passing no `form` arg), which could be argued this PR couples rather tightly. Also, that promise factory could be abstracted to be a fairly generic helper.

My suggestion sounds admittedly a bit complex (given that I for one am not fully comfortable writing promises). LMK if you think it sucks 😄

**Comment by ockham** [comment]
^ That principle question aside, looks good and tests well 👍

**Comment by donnapep** [comment]
> Wondering if we could write some sort of promise factory that's able to listen to actions such as announceSuccess/announceFailure, and that we'd use from within onSubmit.

I get it, and I did investigate something similar originally. I took another shot today , but I can't figure out how to detect when `announceSuccess` or `announceFailure` is called. These are essentially callback functions, not actions, so no help there. I suppose I could listen for `NOTICE_CREATE`, but that's pretty ugly. At this point I'm not sure what else to try. 🙁

**Comment by donnapep** [comment]
@ockham Given the Slack discussion last week about the data layer, there doesn't seem to be a good way of achieving this. Can we move forward with what we've got for now?

**Comment by ockham** [comment]
> @ockham Given the Slack discussion last week about the data layer, there doesn't seem to be a good way of achieving this. Can we move forward with what we've got for now?

Sure, go for it!

**Pull request merged**
