### PR TITLE
Reader: launch refreshed full post to everyone

### PR DESCRIPTION
**Pull request by bluefuton**
The new Reader full post view is currently being served to 50% of users in an A/B test.

This PR removes the A/B test and serves the new full post view to everyone.

### To test

Open your Following stream at http://calypso.localhost:3000/ and open a selection of posts in full post view. Ensure you see the refreshed full post view and everything works as expected:

screen shot 2016-10-27 at 16 05 11

### CODE REVIEW

**Comment by jancavan** [comment]
@bluefuton Does this get rolled out to all languages or everyone that has their languages set to English? https://github.com/Automattic/wp-calypso/issues/8791#issuecomment-255727673

**Comment by bluefuton** [comment]
> @bluefuton Does this get rolled out to all languages or everyone that has their language set to English?

All languages, all users :)

**Comment by blowery** [comment]
so much red. checking this out.

**Comment by blowery** [comment]
sizes before:
```
reader-post-recomendations.813192e76b512918b7c0.js  26.1 kB       5  [emitted]  reader-post-recomendations
               reader-tags.615940a449d52cbe8ae1.js    14 kB       8  [emitted]  reader-tags
                    reader.a2f8630d62d0e8e6b15f.js   204 kB       1  [emitted]  reader
          reader-following.40dcc6bc77b77fc602b8.js   102 kB      24  [emitted]  reader-following
              reader-start.ee3b981fa584fdf0341d.js   130 kB      27  [emitted]  reader-start
               reader-list.dc8fc029e0981191b872.js  66.7 kB      29  [emitted]  reader-list
             reader-search.a1f73898f784c372152f.js  26.3 kB      32  [emitted]  reader-search
         reader-activities.38c435a87e5e499aa356.js  5.58 kB      33  [emitted]  reader-activities
```

sizes after:
```
reader-post-recomendations.984fe6169606c481d001.js  26.1 kB       5  [emitted]  reader-post-recomendations
               reader-tags.5c6762d8dbe0473403a7.js  13.9 kB       8  [emitted]  reader-tags
                    reader.f0ec5c8e168e125321dd.js   126 kB       1  [emitted]  reader
          reader-following.b931cc981b955e3d9c69.js   102 kB      24  [emitted]  reader-following
              reader-start.9b222b5f7297e7bace4f.js   130 kB      27  [emitted]  reader-start
               reader-list.603ce14a066af0d79ab4.js  66.6 kB      29  [emitted]  reader-list
             reader-search.09573d892e256def8a9c.js  26.3 kB      32  [emitted]  reader-search
         reader-activities.99be06e063b136006f54.js  5.55 kB      33  [emitted]  reader-activities
```

**Comment by blowery** [comment]
Noticed we're not setting the title in the refreshed full post. Will file a new PR to fix.

**Comment by blowery** [comment]
#8984

**Comment by blowery** [comment]
@bluefuton pulled a bunch of unneeded code out. could you peek please?

**Comment by bluefuton** [comment]
Even more red!

**Pull request merged**
