### PR TITLE
Add PlantUML display cart diagram and infrastructure

### PR DESCRIPTION
**Pull request by pottedmeat**
#### Changes proposed in this Pull Request

* A diagram of the sequence for displaying a shopping cart using WordPress.com APIs
* A diagram of the sequence for setting the shopping cart using WordPress.com APIs

Display cart

Set cart

#### Testing instructions

* Ideally, install a [PlantUML plugin](https://plantuml.com/running) in your preferred IDE and view `client/my-sites/checkout/docs/get-cart.puml`
* View `client/my-sites/checkout/README.md` if your IDE supports it and verify the SVGs are embedded

### CODE REVIEW

**Review by wp-desktop — DISMISSED** [review]
WordPress Desktop CI Failure for job "wp-desktop-mac".

@pottedmeat please inspect this job's build steps for breaking changes at [this link](https://circleci.com/gh/Automattic/wp-calypso/903545). For temporal failures, you may try to "Rerun Workflow from Failed".

Please also ensure this branch is rebased off latest Calypso.

**Review by sirbrillig — COMMENTED** [review]
I don't think this necessarily belongs in the composite-checkout package, because it includes a lot of wpcom-specific information, and the package is unaware of the environment in which it is used. You might consider putting it into the composite-checkout directory of calypso, or making a more general version for the composite-checkout package that ignores things like the shopping cart.

**Comment by sirbrillig** [comment]
Nice work! If we can get the tests to pass, I'd say this is good to go.

From TC, tests are running into this problem:

```
[18:04:00][Step 1/2] [5/5] Building fresh packages...
[18:04:09][Step 1/2] info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
[18:04:09][Step 1/2] error /home/teamcity-1/buildAgent/work/c4a9d5b38c1dacde/node_modules/node-plantuml: Command failed.
[18:04:09][Step 1/2] Exit code: 1
[18:04:09][Step 1/2] Command: node scripts/get-vizjs.js
[18:04:09][Step 1/2] Arguments: 
[18:04:09][Step 1/2] Directory: /home/teamcity-1/buildAgent/work/c4a9d5b38c1dacde/node_modules/node-plantuml
[18:04:09][Step 1/2] Output:
[18:04:09][Step 1/2] events.js:292
[18:04:09][Step 1/2]       throw er; // Unhandled 'error' event
[18:04:09][Step 1/2]       ^
[18:04:09][Step 1/2] 
[18:04:09][Step 1/2] Error: spawn java ENOENT
```

It looks like maybe the `node-plantuml` package might require java to be installed?

**Comment by pottedmeat** [comment]
Updated to match the latest composite checkout code, limited to just get/set for now, and removed the build script.

**Review by sirbrillig — APPROVED** [review]
This looks good to me!

**Pull request merged**
