### PR TITLE
Changing logo maker logo and copy to Fiverr.

### PR DESCRIPTION
**Pull request by donlair**
We're testing Fiverr as the logo partner for our customers. This PR changes the logo and copy for the logo maker cards in Calypso. Those two cards are a small rectangle on My Home and a full card on the Marketing Tools page.

The updated card on My Home looks like:
image

And the updated card on Marketing Tools looks like:
image

The link is unchanged and still points to https://wp.me/logo-maker

The link on that page will be updated in a separate WPcom patch. Check pau2Xa-2bi-p2 for additional details.

#### Testing instructions

* Checkout this PR and start Calypso.
* Navigate to Calypso using any account.
* Click on My Home if you're not already there and check the Quick Links section on the right.
* Confirm that the correct copy and logo is there. Click the link and confirm that you're routed through the redirect (the redirect itself isn't updated yet).
* Navigate to the Marketing pages under Tools in the left nav.
* Confirm that the logo maker card shows the Fiverr logo and that the copy mentioned Fiverr.
* Click the link and confirm that you're routed through the redirect.

### CODE REVIEW

**Comment by travisw** [comment]
The image isn't loading for me on the Marketing page (404 error).
Maybe this has something to do with me testing using the calypso.live URL?
Screen Shot 2020-10-30 at 6 41 25 PM
Screen Shot 2020-10-30 at 6 55 36 PM


One thing to point out is that the new strings won't be translated by early Monday (when we'd like to deploy) so non-English users will see a mix of languages. I'm not sure how you'd like to handle that, we can't really keep the old copy for non-En users in this case.
Screen Shot 2020-10-30 at 6 48 20 PM

I'm not sure if there is any concern with introducing the green logo on either page given that the other icons are all grey. I'll let the Manage folks chime in on that.

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/5077884

Thank you @donlair for including a screenshot in the description! This is really helpful for our translators.

**Comment by donlair** [comment]
@travisw ah, I see what was happening. It's working on calypso.live now as well. 

I agree with you about the translations. Not ideal, but I'm guessing that landing page isn't translated anyways so it's going to be a weird experience either way. Probably worth figuring out a long-term localization solution for that if we continue these partnerships.

**Comment by sixhours** [comment]
👋 I took this for a spin! I noticed the logo is getting verrrrry slightly cropped on the Marketing screen:

Screen Shot 2020-11-02 at 11 09 50 AM

It's showing at 69.59px square rather than 70px square. 

I agree we should use a gray color for the logo on My Home (like we have with Looka) rather than the green, since that page is already so busy. I've tagged Manage Design in case they have a different opinion.

**Comment by kwight** [comment]
Works great @donlair – I'd agree with others about switching the green for grey.

**Comment by donlair** [comment]
I swapped the My Home logo out to gray, matching the color of the other icons. It looks darker to me, but I assume that's because there's more of the color. 

@sixhours good eye, I never would have seen that cropping. I tweaked the CSS and it fixed the issue for most zoom levels, but there was one zoom level where it still cropped for me. Let me know if you have a suggestion for a different fix. At first I thought it may be related to the `circle` element in the SVG, but tweaking those settings, and even removing the element altogether, didn't affect the icon.

**Comment by donlair** [comment]
@sixhours @kwight any other issues jump out at you? If not, are you comfortable with us deploying the changes?

**Review by sixhours — APPROVED** [review]
This is looking good! 👍

**Review by travisw — APPROVED** [review]
Looks good from my end. 🚀

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/5077884).

**Pull request merged**
