### PR TITLE
Style selection: Update style variation UI

### PR DESCRIPTION
**Pull request by taipeicoder**
#### Proposed Changes

This PR updates the style preview UI in the design preview component. Previously, we couldn't update the style preview UI without updating the package `@wordpress/edit-site`, which is a complicated ordeal (see p1666235331775949-slack-C03DY3RJ5 and pbxlJb-2gk-p2#comment-1952). Also, see the abandoned PR that attempts to do so: #69272.

As an alternative solution, instead of updating `@wordpress/edit-site`, we make a local copy of the [component](https://github.com/WordPress/gutenberg/blob/7005d47340dd9fc6657f2a1c188c6dbf3f3d6dfb/packages/edit-site/src/components/global-styles/preview.js) `<StylesPreview />` instead of directly importing it from `@wordpress/edit-site`. The downside of this approach is that we no longer benefit from the abstraction provided by the package, by the upside is that we can now update the style preview UI without needing to bump `@wordpress/edit-site` and its dependencies across Calypso. This approach can also potentially prevent us from having to update `@wordpress/edit-site` each time the style preview UI changes.

#### Testing Instructions

* Head to the design picker `setup/designSetup?siteSlug=${site_slug}`
* Open any design with style variation.
* Ensure that the style preview UI is updated to match the one in the site editor (wordpress.com/site-editor/${site_slug})

#### Pre-merge Checklist

- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?

### CODE REVIEW

**Comment by arthur791004** [comment]
> the upside is that we can now update the style preview UI without needing to bump @wordpress/edit-site and its dependencies across Calypso.

I think it's still case by case. If issues are introduced from any of `useSetting`, `useStyle`, or `useGlobalStylesOutput`, we still need to bump `@wordpress/edit-site` 😅

As a result, I'd prefer to use the same workaround of https://github.com/Automattic/wp-calypso/pull/69318 again when we encounter a similar issue next time. What do you think?

**Comment by taipeicoder** [comment]
> > the upside is that we can now update the style preview UI without needing to bump @wordpress/edit-site and its dependencies across Calypso.
> 
> I think it's still case by case. If issues are introduced from any of `useSetting`, `useStyle`, or `useGlobalStylesOutput`, we still need to bump `@wordpress/edit-site` 😅
> 
> As a result, I'd prefer to use the same workaround of #69318 again when we encounter a similar issue next time. What do you think?

Agreed! Which is why I wrote - "This approach can also _potentially_ prevent us from having to update @wordpress/edit-site each time the style preview UI changes." It's definitely not a cure-all solution, but it gives us more leeway.

This approach mainly addresses these feedbacks pdtkmj-Ad-p2#comment-1007 and p1666215740390499-slack-CRWCHQGUB which updates the style preview hover presentation.

| Before | After |
| --- | --- |
| Screen Shot 2022-10-25 at 9 42 54 AM | Screen Shot 2022-10-25 at 9 43 49 AM | 

Unfortunately, we couldn't achieve this UI update with #69318 🥲

**Comment by arthur791004** [comment]
> This approach mainly addresses these feedbacks pdtkmj-Ad-p2#comment-1007 and p1666215740390499-slack-CRWCHQGUB which updates the style preview hover presentation.

Oh yes, that's a fair point 🙃 Let's go with this way first and see whether there is a better solution later. For example, make `global-styles` an independent package like `@wordpress/global-styles` or fork a sub-package in the mono-repo to wp-calypso

**Review by arthur791004 — APPROVED** [review]
Work nicely 👍

Minor feedback is to make a new package for it and we could keep `@automattic/design-preview` simpler. But it's optional 🙂

**Review by fushar — APPROVED** [review]
Works nicely 😄 

As now we have a local copy of the component, we might be able the fix bug in this local copy as described here: pbxlJb-2ow-p2 (in the future).

**Comment by taipeicoder** [comment]
> Works nicely 😄
> 
> As now we have a local copy of the component, we might be able the fix bug in this local copy as described here: pbxlJb-2ow-p2 (in the future).

That's a good point! I'm up for looking into that, and make it a new package as @arthur791004 suggested, if bandwidth allows 🙂

**Pull request merged**
