### PR TITLE
Reader: show likes on hover

### PR DESCRIPTION
**Pull request by samouri**
Wouldn't it be great if you could see who liked a post when hovering your mouse over the likes button?

implements: https://github.com/Automattic/wp-calypso/issues/17607.

To Do:
- [ ] make scrollable
- [ ] handle just-liked and just-unliked case
- [x] mobile. what to do, what to do: https://github.com/Automattic/wp-calypso/pull/18807#issuecomment-336490685

### CODE REVIEW

**Comment by samouri** [comment]
>  handle just-liked and just-unliked case

this doesn't work right now because liking posts + unliking them is still fluxified :(

**Comment by fraying** [comment]
Thanks for taking this on, @samouri! We can skip mobile for v1 and add an issue to track it.

**Comment by samouri** [comment]
Tracking issue: https://github.com/Automattic/wp-calypso/issues/18847

**Comment by samouri** [comment]
Current progress:

**Comment by apeatling** [comment]
@samouri Does this one still have a future?

**Comment by samouri** [comment]
@apeatling: yes, but its blocked by https://github.com/Automattic/wp-calypso/pull/22024

**Pull request closed without merging**
