### PR TITLE
Marketplace: Add footer with static info to plugin details

### LINKED ISSUE #67663: Marketplace: add footer with static data to Plugin Details page
Related to pdh6GB-sk-p2 we should add a footer with static text

Image

We can reuse the component already used in https://wordpress.com/plugins.

@vinimotaa can you provide the copy?

### PR DESCRIPTION
**Pull request by epeicher**
#### Proposed Changes

* Add the same footer existing in  https://wordpress.com/plugins to plugin details page

|Before | After|
|-------|------|
|  CleanShot 2022-09-16 at 11 02 24@2x       |CleanShot 2022-09-22 at 11 52 19@2x|

For reference, the previous style was: [Initial before screenshot](https://user-images.githubusercontent.com/3519124/190599962-9984690a-3a37-4bd7-9e5b-55c00c162640.png)

#### Testing Instructions

* Navigate to a plugin details page, e.g. `/plugins/wordpress-seo-premium` and make sure the added footer exists and it matches the expected style

~@vinimotaa Could you please confirm if the following differences with the Figma design of the footer are expected or they should be changed?~
~- The main title reads `WordPress.com is the best place to get your plugins.` in the design but the current footer contains the text `Add additional features to your WordPress site. Risk free.`~
~- The paragraphs titles are slightly different in the design than in the current implementation~
~- The font-size of the 3 paragraphs are 14px in the design but 16px in the current footer~
~- There is a 21px margin at the bottom of the paragraphs that do not exist in the design~

~Please note that the content of the paragraphs is a _lorem ipsum_ so I assume the existing ones are correct~

**Note:** The above questions ⬆️  are already being handled as part of:
The more generic task 
- https://github.com/Automattic/wp-calypso/issues/65574

And most of the design updates have been done as part of:
- https://github.com/Automattic/wp-calypso/pull/67636

#### Pre-merge Checklist

- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?

Fixes #67663

### CODE REVIEW

**Comment by cpapazoglou** [comment]
@epeicher, not sure but I assume the original intention was to have different content in the plugin details oriented to increase chances to buy this plugin. We will _probably_ need to make this component dynamic - accepting the texts from a parent component.

Also, this footer section (at least with that content) should appear only for premium plugins - not for free.

**Comment by epeicher** [comment]
> @epeicher, not sure but I assume the original intention was to have different content in the plugin details oriented to increase chances to buy this plugin.

Ok, thanks for the clarification. @vinimotaa could you please confirm the content of the paragraphs of the new footer?

> Also, this footer section (at least with that content) should appear only for premium plugins - not for free.

Important point, I will add a condition there. Thanks for pointing it out!

**Comment by vinimotaa** [comment]
@SaxonF can you help us with this? I guess the idea was to have the same footer we have on the landing page within the Plugin page? Harris has a good point, are we having that only on Premium Plugins?

**Comment by vinimotaa** [comment]
A complete grid system and padding specifications for the entire landing page on this [Figma file](https://www.figma.com/file/f84fqtCG4pCnCh2Hq0But5/Marketplace-Refinements?node-id=4273%3A39668).

**Comment by epeicher** [comment]
Thanks @vinimotaa for the specs 👍. As part of this task, I can update the design of the footer regarding margin, padding and font size. That component will be shared between the plugin details and the plugin list screens.

@SaxonF please confirm if the text contents should be the same between plugin detail and plugin list screens and if in the plugin details screen, the footer should only be displayed for _premium_ plugins.

**Comment by epeicher** [comment]
Hi @vinimotaa and @SaxonF, I have some questions about the design. 
1. The footer title has a font size of 26px but in the Calypso docs ([link here](https://wpcalypso.wordpress.com/devdocs/typography)) there is no variable for 26px, there are either:

   Sass Variable | Pixels | Rems
    -- | -- | --
    $font-title-large | 32 | 2
    $font-title-medium | 24 | 1.5

   Which one should I use? At the moment, I have left the existing 32px

2. Also, I would like to confirm the following changes:
- Change the color of the footer paragraphs text from gray to white
- Reduced top/bottom margin and paddings
- Reduced a bit the column gap

Please find _before_ and _after_ screenshots below:
|Before | After|
|-------|------|
|CleanShot 2022-09-19 at 11 57 14@2x|CleanShot 2022-09-19 at 11 41 24@2x|

**Comment by epeicher** [comment]
**Important Update:** Most of the changes suggested have been done as part of https://github.com/Automattic/wp-calypso/pull/67636 so this PR will be used only to display the footer  only if the plugin is a Marketplace product

**Review by cpapazoglou — CHANGES_REQUESTED** [review]
Clearing the indexed db cache and reloading a marketplace plugin page, I get

CleanShot 2022-09-22 at 14 48 13@2x

which isn't very pleasant to the eye. Should we apply a [sticky footer](https://philipwalton.github.io/solved-by-flexbox/demos/sticky-footer/) solution?

**Comment by epeicher** [comment]
> Clearing the indexed db cache and reloading a marketplace plugin page, I get

Just to discard other investigations, that is displayed during a split second, right? If so, I will check your solution, thanks for that!

**Comment by epeicher** [comment]
@cpapazoglou I have added an additional flag `showPlaceholder` in latest commit https://github.com/Automattic/wp-calypso/pull/67898/commits/f68a5c0fce3139a6a468f2d6b53ec60a1799c6be that is used in other places in the component to hide/show the content. 

I have investigated the sticky footer but it implied updating the HTML `body` element so I was concerned about potential regressions

**Review by cpapazoglou — APPROVED** [review]
Thanks for resolving the feedback! LGTM!

**Pull request merged**
