### PR TITLE
Plans overhaul Phase 1: apply new design changes

### PR DESCRIPTION
**Pull request by claudiucelfilip**
#### Changes proposed in this Pull Request

More info: pdgrnI-kt-p2

This adds visual changes to the /plans and /start/plans pages to match the new designs for the overhauled Plans.
On top of the design, a few other changes have been included, based on this discussion p1646677120279239-slack-C036P6ULFNU 
- updated the first 6 features: 
  - Custom domain name: Not included / Free for one year!
  - Premium themes
  - Premium support
  - Plugins
  - Storage
  - Sell products with WooCommerce
- the other features are hidden behind a toggle
- the tabs on /plans pages will reflect the behavior from #61656 

https://user-images.githubusercontent.com/2749938/157418490-80170130-d02a-4db3-adaa-8aa8c0fe3ddc.mov

#### Testing instructions
* checkout this branch to enable the Plans overhaul

##### New site plans
* go to /start/plans
* the page should match the design on all screens sizes
Screenshot 2022-03-09 at 12 04 18
Screenshot 2022-03-09 at 12 04 29
* make sure the `Show full plan comparison` toggle works

##### Free Plans
* go to the /plans page on a Free plan site
* you should see the overhauled Plan comparison table
* make sure the `Show full plan comparison` toggle works

Screenshot 2022-03-09 at 12 03 03
Screenshot 2022-03-09 at 12 02 53
Screenshot 2022-03-09 at 12 02 26

##### Paid Plans
* go to the /plans page on a new Managed plan site
Screenshot 2022-03-09 at 12 03 21

* similar behavior is expected with an old Plan site (ex. eCommerce) but a placeholder notification should show
Screenshot 2022-03-09 at 12 10 04

##### Staging
* you should not see any changes in any non-development environments

### CODE REVIEW

**Comment by claudiucelfilip** [comment]
[Make visual adjustments to the Calypso Plans presentation to match the design](https://trello.com/c/bFJ7kBLB/13-make-visual-adjustments-to-the-calypso-plans-presentation-to-match-the-design)

**Review by southp — APPROVED** [review]
I've gone through the test plan and it works as expected. The code also LGTM.
One thing to note is that the new My Plans page doesn't show on an Atomic site for me:
image
It can be a hairy calypso vs wp-admin issue, so let's not hold for this but iterate it in a follow-up PR.

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/7173399

Thank you @claudiucelfilip for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/7173399

Thank you @claudiucelfilip for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/7173399).

**Pull request merged**
