### PR TITLE
State: Remove unused gsuite users state tree

### PR DESCRIPTION
**Pull request by tyxla**
#### Proposed Changes

This PR is a follow-up cleanup after #65088 that removes the unused gsuite users state tree and related data layer and query component.

#### Testing Instructions

Verify removed code is not in use.

### CODE REVIEW

**Review by flootr — APPROVED** [review]
LGTM 🚀 thanks for the cleanup!

**Comment by stephanethomas** [comment]
Thanks for working on this Marin! I've added that pull request to our board, we'll review those changes today or tomorrow.

**Comment by tyxla** [comment]
Thank you both! Don't worry @stephanethomas, I already got approval from @flootr so I can ship it. You're welcome to have a look, and suggest further cleanup of course! 😅

**Comment by AllTerrainDeveloper** [comment]
That's been a nice clean up! (I'm also surprised that those things were not used!)

**Comment by olaseni** [comment]
Thanks for the cleanup @tyxla! Looks good.

**Pull request merged**
