### PR TITLE
chore: Tidy up version check string creation

### PR DESCRIPTION
**Pull request by tofumatt**
Make some tweaks to the version check script based on https://github.com/Automattic/wp-calypso/pull/22237#pullrequestreview-95611152

### CODE REVIEW

**Comment by tofumatt** [comment]
@dmsnell I remember you mentioning a few cleanup ideas for this in the original PR, if these look better just let me know and I'll get this merged 😄

**Comment by tofumatt** [comment]
(This can obviously be closed if #23225 is merged.)

**Comment by Copons** [comment]
Changes LGTM.
Are there any reasons why it's not merged yet? 🤔

**Comment by tofumatt** [comment]
Oh sorry, I just missed this 😓

**Pull request merged**
