### PR TITLE
Fix: site thumbnails update state when unmount

### LINKED ISSUE #73163: Sites Management Page: "Can't perform a React state update" error for Site Thumbnails
If you quickly start a search after the Sites page is loaded, you can see this error in the console:

image

I think the problem is that this async fetch isn't completed yet and needs to be cleaned up:

https://github.com/Automattic/wp-calypso/blob/4bde28dc50cd16ab95e5b9830f35b26bac754636/packages/components/src/site-thumbnail/use-mshots-img.tsx#L80-L92

https://github.com/Automattic/wp-calypso/blob/4bde28dc50cd16ab95e5b9830f35b26bac754636/packages/components/src/site-thumbnail/fetch-await-redirect.ts#L1-L7

**Done is:**
* It's no longer possible to reproduce the error.

### PR DESCRIPTION
**Pull request by kozer**
Fixes https://github.com/Automattic/wp-calypso/issues/73163

## Proposed Changes

This pr proposes early return when the component is unmounted and thus avoiding updating the state, creating the following warning:
```
Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
```

## Testing Instructions

1. Copy a text (eg: `abcdefghijklmno` ). (You need to make sure that the text doesn't let any site visible under your sites list after a search )
2. Load Sites page ( by visiting `/sites` )
3. Quickly paste the text you copied.
4. Ensure that you don't get the following warning

```
Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in a useEffect cleanup function.
```

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

**Comment by katinthehatsite** [comment]
I was attempting to review this but I have not found a reliable way to reproduce the error so far yet. I will take a closer look later today to see if I can reproduce the warning.

**Comment by kozer** [comment]
> I was attempting to review this but I have not found a reliable way to reproduce the error so far yet. I will take a closer look later today to see if I can reproduce the warning.

Yeah, me too @katinthehatsite . You can take a look at why this pr has been created [here](https://github.com/Automattic/wp-calypso/issues/73163#issuecomment-1613843687)

**Comment by wojtekn** [comment]
I couldn't reproduce the original issue anymore too, I tried on the local and staging environments.

**Comment by danielbachhuber** [comment]
> I couldn't reproduce the original issue anymore too

Me neither, I just get this error instead 😁

image

**Review by danielbachhuber — APPROVED** [review]
Seems fine to land this change. We can see if the error manifests again.

**Pull request merged**
