### PR TITLE
remove prettier pragma from sass files

### PR DESCRIPTION
**Pull request by flootr**
#### Changes proposed in this Pull Request

* Remove prettier pragma `@format` from any sass file in /assets and /client

#### Testing instructions

* code: make sure the only code changes are removing the prettier pragma

stacked on https://github.com/Automattic/wp-calypso/pull/29403

### CODE REVIEW

**Comment by jsnajdr** [comment]
Hi @flootr 👋 Did you do something to prevent re-adding the pragma when formatting a SCSS file? Prettier is configured to add it to the beginning of every formatted file.

We should set `insertPragma: false` in `.prettierrc`. The `requirePragma` option is already false, i.e., Prettier will format even if the pragma is not present.

And we could remove the pragma also from JS files. The times when we needed it, during the gradual adoption, are gone. @sirreal might want to correct me if I'm wrong.

**Comment by flootr** [comment]
> Did you do something to prevent re-adding the pragma when formatting a SCSS file? Prettier is configured to add it to the beginning of every formatted file.

@jsnajdr this PR is stacked on https://github.com/Automattic/wp-calypso/pull/29403 which takes care of this.

**Comment by jsnajdr** [comment]
> this PR is stacked upon #29403 which takes care of this.

I'm sorry, I didn't notice that. And I didn't get a GitHub notification for #29403 either ☹️

**Comment by sirreal** [comment]
> The times when we needed it, during the gradual adoption, are gone. @sirreal might want to correct me if I'm wrong.

I'm all for running prettier on everything all the time, but I think there are a few things we do need to ignore:

> we do have some code in the repo (editor plugins) that we may not want to munge too much, as they come from core

via @blowery p4TIVU-8Ud-p2 #comment-8921

I'm not sure what the status is here or whether this continues to be true.

**Comment by jsnajdr** [comment]
Can we add a `.prettierignore` file that excludes certain files based on their path, rather that a pragma presence? Would it work in our case?

**Review by blowery — APPROVED** [review]
LGTM, assuming it lands on the prettier pragma branch

**Comment by blowery** [comment]
A note that we've since found that prettier has a few unfortunate bugs that can break our SASS files, mostly around how it handles single line comments.

See https://github.com/Automattic/wp-calypso/pull/29566#issuecomment-448710423

**Pull request merged**
