### PR TITLE
Notifications: Buttons and YouTube Preview Image Clickable

### LINKED ISSUE #46295: Notifications: The core YouTube embed block is rendered as a literal shortcode.
The core YouTube embed block is rendered as a literal shortcode in a notification. It should either be a functioning embed, or at least a preview image linking to the post.

Front-End | Notification
--- | ---
Screen Shot 2020-10-08 at 2 57 34 PM | Screen Shot 2020-10-08 at 3 12 36 PM

### PR DESCRIPTION
**Pull request by krymson24**
#### Changes proposed in this Pull Request

* Currently, Button blocks and YouTube embeds created in a post, and subsequently rendered in a notification in the master bar renders as a unclickable. This change makes it so that they redirect to the appropriate content.
* `a` tags are now rendered with the appropriate `href`.

#### Testing instructions

1. Use the Calypso live link, or checkout this branch
2. See the"Creating post notification" section in the README at https://github.com/Automattic/wp-calypso/blob/master/apps/notifications/src/doc/note-rendering.md
3. Use the "Follow" button that appears in the bottom right corner of the blog to add it to your Reader subscriptions:
4. Then navigate to https://wordpress.com/following/manage and enable "Notify me of new posts" for the blog. With this enabled, future posts on that blog will appear as notifications in your masterbar.
5. Create a post for the blog you're following with a button block with a link and a separate YouTube embed.
6. Go to your masterbar and select the notification that contains the buttons and YouTube embed. Confirm that when clicking on the button, or the YouTube preview image, it redirects you to the appropriate content. You can also confirm via the Chrome Inspector that the `a` tag contains an `href`
#### Screenshots and GIFs
Before | After
--- | ---
Screen Shot 2020-10-20 at 1 14 56 AM | Screen Shot 2020-10-20 at 1 13 01 AM
Screen Shot 2020-10-20 at 1 15 09 AM | Screen Shot 2020-10-20 at 1 13 16 AM

Fixes #46295

### CODE REVIEW

**Review by mmtr — APPROVED** [review]
Works like a charm! 🚀

**Comment by krymson24** [comment]
> Works like a charm! 🚀

Thanks for the review @mmtr !

**Comment by mmtr** [comment]
Quick reminder that we need to deploy this as well to the `wpcom` codebase: PCYsg-elI-p2

**Comment by krymson24** [comment]
> Quick reminder that we need to deploy this as well to the `wpcom` codebase: [PCYsg-elI-p2](https://href.li/?PCYsg-elI-p2)

Totally forgot -- will do!

**Pull request merged**
