### PR TITLE
Jetpack Manage: Retire Partner portal 'Prices' page. 

### PR DESCRIPTION
**Pull request by jkguidaven**
This page has become outdated and redundant with the introduction of license bundles and the plan to add a higher level **'Pricing'** tab in the sidebar. 

Screen Shot 2024-01-17 at 4 31 49 PM

Closes https://github.com/Automattic/jetpack-manage/issues/234

## Proposed Changes

* Remove the **'Purchases > Prices '** menu item in the sidebar.
* Remove `/partner-portal/prices` as a valid URL and remove related codes (context, components, etc.)

## Testing Instructions
Since these changes are made specifically for agencies, you must set yourself(partner) as an agency - 2c49b-pb.

* Use the Jetpack cloud live link below and Go to the Overview page (`/overview`)
* Confirm that in the sidebar, the **'Purchases > Prices'** menu is no longer visible.
* Confirm that when accessing `/partner-portal/prices`, the page no longer loads.

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

**Comment by simonktnga8c** [comment]
Nice one @jkguidaven 👍

You may have already done this, but incase someone has that old URL bookmarked, can redirect it to `/partner-portal/issue-license` also please. Thanks!

**Review by keoshi — APPROVED** [review]
Works as expected! 🚢

**Review by oikeme — APPROVED** [review]
Code changes/deletions look good and things work as expected

**Comment by jkguidaven** [comment]
> You may have already done this, but incase someone has that old URL bookmarked, can redirect it to /partner-portal/issue-license also please. Thanks!

Good point! made some adjustment to redirect the old URL to the Issue licenses page. 👍

**Pull request merged**
