### PR TITLE
Validate reduxStore interface in non production environment

### PR DESCRIPTION
**Pull request by samuelclemens**

### CODE REVIEW

**Comment by blowery** [comment]
@aduth any thoughts on this?

**Comment by aduth** [comment]
@samuelclemens : Can you describe what prompted these changes? Are there situations in which we're calling `renderWithReduxStore` without a proper Redux store instance?

**Comment by samuelclemens** [comment]
@aduth I think that in dev env it's a good idea checking that we're getting what we're expecting to get =) That way we can catch it while in dev env. I haven't encountered such case, I just thought it's a good idea while working on #2932

**Comment by aduth** [comment]
While I can appreciate the potential debugging advantage if it were ever to come to the point of being an issue, my personal opinion is that the added verbosity (especially if these types of validations became more widespread) harm readability of the code more than it helps us.

**Pull request closed without merging**
