### PR TITLE
Enable VideoPress Onboarding trial for videomaker.

### PR DESCRIPTION
**Pull request by pgk**
Related to https://github.com/Automattic/greenhouse/issues/1958

## Proposed Changes

* Enable videomaker trial from the VideoPress flow in all other envs, except test.
* Run e2e tests locally with `CALYPSO_BASE_URL=http://calypso.localhost:3000 yarn workspace wp-e2e-tests test -- specs/onboarding/signup__videopress-tailored.ts`.

## Testing Instructions

* Check that you get the trial flow in the container and locally. The flow starts from `/setup/videopress`

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

**Review by gikaragia — APPROVED** [review]
Looks good, works well! Out of curiosity, why is it disabled in test?

**Comment by pgk** [comment]
> Looks good, works well! Out of curiosity, why is it disabled in test?

@gkaragia because e2e tests are testing the vanilla flow, and this is a temporary (?) change

**Comment by pgk** [comment]
@gkaragia I added another wee thing, could you rereview?

**Review by gikaragia — APPROVED** [review]
👌

**Review by jgcaruso — CHANGES_REQUESTED** [review]
Tested well, just a couple of things:

1. If you click "Learn More" at the intro, the button label in the modal doesn't say "Start trial"
image

2. We have a lot of conditional code in the onboarding for trial checking, but the test only supports the new flow. If we ever revert the setting the test won't pass. Given we're trying to wrap this up, its probably fine but I wonder if there is something we can do to at least make this obvious to someone who is trying to fix the test in the future? Maybe reference the PR in a comment to show where you can get the original test back from?

**Comment by pgk** [comment]
Done!

**Review by jgcaruso — APPROVED** [review]
New changes LGTM!

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/9733997

Some locales (Japanese) have been temporarily machine-translated due to translator availability. All other translations are usually ready within a few days. Untranslated and machine-translated strings will be sent for translation next Monday and are expected to be completed by the following Friday.

Hi @pgk, could you please edit the description of this PR and add a screenshot for our translators? Ideally it'd include this string: `After trial, plans start as low as %s per month, %s billed annually`

Thank you in advance!

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/9733997).

**Pull request merged**
