### PR TITLE
Performance Profiler: Add link to recommendations on CWW section

### PR DESCRIPTION
**Pull request by WBerredo**
Fixes [Performance Profiler: add link to jump to recommendations](https://github.com/Automattic/dotcom-forge/issues/9048)

## Proposed Changes

Add a link to the recommendations section on the CWW section.
The link should redirect to the section with using the current metric as filter.

CleanShot 2024-09-11 at 14 27 38

PS: If there are no recommendations for a given metric, this section shouldn't be shown.

## Why are these changes being made?

[Performance Profiler: add link to jump to recommendations](https://github.com/Automattic/dotcom-forge/issues/9048)

## Testing Instructions

* Go to `speed-test-tool?url=https%3A%2F%2Fwordpress.com%2F&hash=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6NzQ2N30.LOelpUBxFDxMytpSYeB3EBNdBnHeYTvonyZ6zE7aqSM`
* On the CWW section check if there is a button with `View recommendations`
* Click on this button 
* Check if you the page scroll to the recommendations section with the selected metric on the filter.
* Check if the section is not shown for some metrics
  * It shouldn't be shown where are no recommendations for a given metric.

### CODE REVIEW

**Comment by gcsecsey** [comment]
I added a small change in https://github.com/Automattic/wp-calypso/pull/94439/commits/04f99942ad9bacc56864b2db0cd48b9d90e39a55 to fix the hover styles for the dropdown items:

| Before | After |
|--------|--------|
| CleanShot 2024-09-12 at 12 07 42@2x | CleanShot 2024-09-12 at 12 17 51@2x |

**Review by gcsecsey — APPROVED** [review]
Changes LGTM and work great :shipit:

**Comment by gavande1** [comment]
The changes look good to me. However, there is a minor concern. 

There is a noticeable white space between the explanation and the suggestions for improvement. While I understand why it is there, we could get rid of it by increasing the length of the text.  What do you think?

CleanShot 2024-09-13 at 11 47 26@2x

**Comment by gcsecsey** [comment]
> The changes look good to me. However, there is a minor concern.
> 
> There is a noticeable white space between the explanation and the suggestions for improvement. While I understand why it is there, we could get rid of it by increasing the length of the text. What do you think?
> 
> CleanShot 2024-09-13 at 11 52 28@2x

Agreed. I made some minor tweaks in [6bcdd06](https://github.com/Automattic/wp-calypso/pull/94439/commits/6bcdd06bc01d589d8147c8cdaf34abba3f2a0c1a) to match the designs better:

| Figma | Calypso |
|--------|--------|
| CleanShot 2024-09-13 at 11 01 39@2x | image |

**Review by gavande1 — APPROVED** [review]
LGTM 👍

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/16716981

Some locales (Hebrew, Japanese) have been temporarily machine-translated due to translator availability. All other translations are usually ready within a few days. Untranslated and machine-translated strings will be sent for translation next Monday and are expected to be completed by the following Friday.

Thank you @WBerredo for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/16716981).

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/16716981).

**Pull request merged**
