### PR TITLE
Update/store reviews styling

### PR DESCRIPTION
**Pull request by jameskoster**
Updates review styling.

Pending review:

pending

Approved review:

approved

open-review

Mobile styles to follow.

### CODE REVIEW

**Comment by justinshreve** [comment]
@jameskoster Just a note that #18377 adjusts the UI for the reply textarea so that it looks like the comments screen:

* The Gravatar and text are visible when the textarea is unfocused, but the submit button is not.
* When focused, the text and submit button are visible.

Just a note that depending on what is ready to go in first, we might have some slight rebasing to do. I can help with that.

**Comment by kellychoffman** [comment]
I know this is in progress, but I noticed a couple things: 

Alignment issue:
screen shot 2017-09-28 at 5 28 23 pm
Verified owner icon is off: 
screen shot 2017-09-28 at 5 29 00 pm
Verified owner badge is off:
screen shot 2017-09-28 at 5 28 38 pm

**Comment by kellychoffman** [comment]
Verified badges lookin' good now!

**Comment by justinshreve** [comment]
@jameskoster I have rebased this branch after merging the reply creation PR. Hopefully I didn't screw anything up with the textarea CSS and lose any changes you wanted. Can you take a look?

I also think we need to link the product image back to the product form. I think it would also be a good idea to have the actual name of the product, but I'm not exactly sure where I should put it.

**Comment by jameskoster** [comment]
Fixed up the styling.

As for adding the product name - something like this makes the most sense to me; 

name

It reduces the preview size a bit though, and more importantly will look odd with really long product titles. If we're including the name we could probably lose the thumbnail as its superfluous and disconnected over there on the right of the preview. 

Alternatively, to remedy the long-product-name issue we could add it beneath the review content instead;

review

But that doesn't feel great. The name seems a bit random there. Any thoughts @kellychoffman ?

**Comment by kellychoffman** [comment]
> But that doesn't feel great. The name seems a bit random there. Any thoughts @kellychoffman ?

What about only in the expanded view? I don't think its necessary in the initial list view.

**Comment by kellychoffman** [comment]
Looking good. Just one odd thing I noticed: the spacing around the initial review and the reply isn't consistent: 

screen shot 2017-10-02 at 12 13 21 pm

**Comment by justinshreve** [comment]
I've dropped the product image and added the product name to the expanded view. I added the name under the action bar, above the review info to match what is done on the comments view.

screen shot 2017-10-02 at 2 16 31 pm

**Comment by jameskoster** [comment]
> Looking good. Just one odd thing I noticed: the spacing around the initial review and the reply isn't consistent:

@kellychoffman did you fix this before the merge?

**Comment by kellychoffman** [comment]
I didn't, I thought you did 🙃

**Pull request merged**
