### PR TITLE
A4A: add estimated payout date card on referrals dashboard

### PR DESCRIPTION
**Pull request by andrii-lysenko**
Resolves https://github.com/Automattic/automattic-for-agencies-dev/issues/1577

## Proposed Changes

This PR adds 'Estimated Payout Date' card to referrals dashboard. 
Screenshot 2024-12-13 at 2 17 26 PM

The logic is added separately to calculate the closest payout date.
We pay these out quarterly, on March, June, September and December first day. 

Additionally added tests to check logic through the year.

cc @simonktnga8c I know we postponed this payout to Dec 31, should we for now display Dec 31?

## Testing Instructions

- Using live link below navigate to `/referrals/dashboard` and check if they date displayed correctly.
- Checkout this branch locally
- Run tests: `yarn test-client client/a8c-for-agencies/sections/referrals/lib`

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
    - [ ] For UI changes, have we tested the change in various languages (for example, ES, PT, FR, or DE)? The length of text and words vary significantly between languages. 
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Review by travisw — APPROVED** [review]
Works great! Tests pass 🚀 

One tiny non-blocking thing. The period after the "learn more" link looks a little funny in my opinion.
Screenshot 2024-12-13 at 3 43 35 PM

**Comment by travisw** [comment]
And thanks for adding those tests - super helpful!

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/17065954

Some locales (Hebrew, Japanese) have been temporarily machine-translated due to translator availability. All other translations are usually ready within a few days. Untranslated and machine-translated strings will be sent for translation next Monday and are expected to be completed by the following Friday.

Thank you @andrii-lysenko for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/17065954).

**Pull request merged**
