### PR TITLE
Comment: add comment counts next to filters

### LINKED ISSUE #19308: Comments: add comment counts next to filters
Let's investigate if we can add accurate comment counts to each filter. 

If this requires more endpoint work, let's document what's required and target this for M4

### PR DESCRIPTION
**Pull request by vindl**
Closes #19308

Show count next to comment filters in navigation bar provided that they are larger than 0.

### Visual changes

screenshot from 2017-11-02 18-05-32

### Testing instructions

1. Start Calypso with: `ENABLE_FEATURES=comments/management/m3-design npm start`.
2. Navigate to `comments/all` and verify that you are getting the correct count for each section.
3. Test on sites with large number of comments.

### CODE REVIEW

**Comment by Copons** [comment]
Unfortunately this is not that simple. 🙁 

We only requests the comments tree for the current status, so, for example, if you open the Comments section on the `/all` list, you get both the trees - and therefore their counts - for `approved` and `unapproved`.

Though, if you open on the `/approved` list, you get only the approved count.
This doesn't only mean that all other status filters will be without count, but also that the count for All will be likely wrong (it being a sum of `approved` and `unapproved`, which in this example has not been loaded yet).

To clarify...

### Example 1

- Open on `/all`. (notice that All, Pending, and Approved counts are all loaded, thanks to the fact that `/all` is the "join" of `/approved` and `/pending`)<br>screen shot 2017-11-02 at 17 33 07

### Example 2

- Open on `/approved`. (notice that the All count is wrong)<br>screen shot 2017-11-02 at 17 32 32

- Change to `/pending`. (notice how the All count changed, and it's now correct)<br>screen shot 2017-11-02 at 17 32 42

- Change to `/spam`.<br>screen shot 2017-11-02 at 17 32 48

- Change to `/trash`.<br>screen shot 2017-11-02 at 17 32 53

**Comment by rodrigoi** [comment]
With my 🔮 I see a new endpoint in your future @vindl, much like the `post-counts` endpoint. Or you can add said total counts to an existing endpoint... or add state to the comments tree (I think we've talked about this at some point) to always request `all`...

**Comment by vindl** [comment]
> With my :crystal_ball: I see a new endpoint in your future @vindl, much like the post-counts endpoint. Or you can add said total counts to an existing endpoint... or add state to the comments tree (I think we've talked about this at some point) to always request all...

Ideally these counts should be returned via endpoint, but that would mean pushing this feature to December, and I was trying to see if we can squeeze it in M3 with what we've got now. Any objections to changing things on front end so we always load all comments regardless of current status?

**Comment by gwwar** [comment]
> Any objections to changing things on front end so we always load all comments regardless of current status?

Provided that we can still provide reasonable performance.

**Comment by kwight** [comment]
I much prefer @rodrigoi 's suggestion of a `comments-count` endpoint; it solves the precise issue we want to solve, has a precedent in `posts-count`, and doesn't involve calls for data we don't need yet.

**Comment by gwwar** [comment]
It's fine to target this for M4 too. I'll spin up an M4 endpoint p2 post tomorrow.

**Comment by drw158** [comment]
I'd like to see some sort of abbreviation for popular blogs.

en.blog has 127,397 All comments, and around the same for Approved 

maybe something like `127k` and `3.4k`, similar to Twitter's likes and retweets.

**Comment by vindl** [comment]
Ok, I think we all agree that it would be better to implement this via `comments-count` endpoint. I'll close this PR and create a separate issue for this in M4. 

> I'd like to see some sort of abbreviation for popular blogs.

Good point. I'll make note of it in new issues.

**Pull request closed without merging**
