### PR TITLE
Passwordless Auth Core Profiler - Add `source` param when sending an email

### PR DESCRIPTION
**Pull request by moon0326**
This PR adds `source` param to `sendEmailLogin` function.

This is needed in WPCOM to identify the JPC flow and its product (Jetpack, Woo Payments, and Woo Order Attribution). We use this value to use a different email template for the signup and magic link. I'll open a WPCOM PR soon.

## Why are these changes being made?

* To identify JPC flow in WPCOM so we can use a different email template for the sign up and magic link.

## Testing Instructions

1. Checkout this branch locally and open `config/development.json`.
2. Enable `woocommerce/core-profiler-passwordless-auth` feature flag and run `yarn start`
3. Once the build is ready, visit this [link](http://calypso.localhost:3000/log-in/jetpack?redirect_to=http%3A%2F%2Fcalypso.localhost%3A3000%2Fjetpack%2Fconnect%2Fauthorize%3Fclient_id%3D236381464%26redirect_uri%3Dhttps%253A%252F%252Fnoisily-fortunate-toucan.jurassic.ninja%252Fwp-admin%252Fadmin.php%253Fhandler%253Djetpack-connection-webhooks%2526action%253Dauthorize%2526_wpnonce%253D32ab4c9508%2526redirect%253Dhttps%25253A%25252F%25252Fnoisily-fortunate-toucan.jurassic.ninja%25252Fwp-admin%25252Fadmin.php%25253Fpage%25253Dwc-admin%26state%3D1%26scope%3Dadministrator%253A2ca8ea2582da1c066074563a12cc8b22%26user_email%3Dmoon.kyong%2540automattic.com%26user_login%3Dmoon0326%26jp_version%3D13.7%26secret%3DQFoaAXaOIPZTr9p6Z5Hqf6RWkCboPylJ%26blogname%3DNoisily%2520Fortunate%2520Toucan%26site_url%3Dhttps%253A%252F%252Fnoisily-fortunate-toucan.jurassic.ninja%26home_url%3Dhttps%253A%252F%252Fnoisily-fortunate-toucan.jurassic.ninja%26site_icon%3D%26site_lang%3Den_US%26site_created%3D2024-08-26%252019%253A40%253A51%26allow_site_connection%3D1%26calypso_env%3Dproduction%26source%3D%26_as%3Dsearch-term%26_ak%3Djetpack%26from%3Dwoocommerce-core-profiler%26_ui%3D254662545%26_ut%3Dwpcom%253Auser_id%26purchase_nonce%3DlbtPaOlO%26_wp_nonce%3D69744335dc%26redirect_after_auth%3Dhttps%253A%252F%252Fnoisily-fortunate-toucan.jurassic.ninja%252Fwp-admin%252Fadmin.php%253Fpage%253Dwc-admin%26site%3Dhttps%253A%252F%252Fnoisily-fortunate-toucan.jurassic.ninja&from=woocommerce-core-profiler) in an incognito session.
4. Open your browser's inspector -> Network
5. Enter a passwordless auth enabled email and click on `Continue` button.
6. Search for `send-login-email` request and check the payload.
7. Confirm the payload has `source` value.

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Review by ilyasfoo — APPROVED** [review]
Tests well for login and sign up!

One question, it seems the source field also exists on Jetpack `Email me a login link` flow, but it's empty. Is this expected?

Pre-approving!

https://github.com/user-attachments/assets/521c52d2-cde2-403d-af79-9f8b0a9c8cb1

**Comment by psealock** [comment]
I'm only see the `send-login-email` request made after the second "Send link" button is  clicked and the payload has `source: ""`. Is this normal?

**Comment by moon0326** [comment]
> 3\. link

Where do you see `Send link` button 🤔 ?

You should see `Connect your account` first
Screenshot 2024-11-13 at 10 27 54 AM

then `Check your email` page.

Screenshot 2024-11-13 at 10 27 51 AM

**Comment by moon0326** [comment]
> Tests well for login and sign up!
> 
> One question, it seems the source field also exists on Jetpack `Email me a login link` flow, but it's empty. Is this expected?
> 
> Pre-approving!
> 
>  8bWiln.mp4

Thanks!

I realized we never worked on `Email me a link` page as it's not on Figma. We don't have it on the sign up page either. For now, I've [Disable email me a link](https://github.com/Automattic/wp-calypso/pull/96321/commits/f620b7258742c2735ecebbe914e617584bbc21e3) it from the login page, as it's essentially performs the same function as the main form. I'll check with Veronica to see if we can style the page.

**Pull request merged**
