### PR TITLE
Stats: Update URLs for Empty state actions

### PR DESCRIPTION
**Pull request by grzegorz-cp**
Related to https://github.com/Automattic/red-team/issues/86

## Proposed Changes

* update links for all Empty actions to point to the final resources
* updating empty card strings and inline links

## Why are these changes being made?

* a part of the empty states project

## Testing Instructions

* go to the live branch
* apply `stats/empty-module-traffic` feature flag
* verify that modules with action links point to resources that make sense
* test Jetpack and other environments

SCR-20240712-kcoy

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Review by annacmc — COMMENTED** [review]
Looks great! I just found two links (inline links rather than action links) to be updated:

- The UTM I think we want to link to `#harnessing-utm-stats-for-precision-tracking` rather than `#utm-stats`

- The Search link should be `#search-terms` rather than `#search`

**Review by annacmc — APPROVED** [review]
LGTM! 😄 👍

**Review by kangzj — APPROVED** [review]
It looks good to me!

One thing I don't quite understand is the reason behind showing support URL for Odyssey, but landing page for Calypso. Can you explain more please? Thanks 🤔

**Comment by grzegorz-cp** [comment]
> One thing I don't quite understand is the reason behind showing support URL for Odyssey, but landing page for Calypso. Can you explain more please? Thanks 🤔

My perspective on that proposal was that Calypso users might not be as familiar with Jetpack products as Odyssey users so it made sense for me to show a landing page.

**Pull request merged**
