### PR TITLE
Plans: add upgrade link to top masterbar

### LINKED ISSUE #7288: Plans: add upgrade link to top masterbar
This is a very simple idea, to add a link that says "upgrade" in the top bar for existing users who have a single site without a paid plan. @apeatling may have more specific ideas for how to implement this. But I think a text link that sits right next to the "reader" tab, rendered as a link (rather than as a tab) would be a good start. I don't believe this will work for the mobile view, so for now we can just try this in the desktop view. The link should point to the plans page.

We may want to try this with a limited test, say for users who have registered after the test start date.

### PR DESCRIPTION
**Pull request by lamosty**
Fixes #7288. WIP.

### Width < 480px => no Upgrade link

selection_026

### Width 480px-500px => no Upgrade link (doesn't fit, not enough space)

selection_027

### Width > 500px

selection_028

Test live: https://calypso.live/?branch=add/upgrade-link-masterbar

### CODE REVIEW

**Comment by shaunandrews** [comment]
If we _have_ to try it in the masterbar, I think it needs to be separated from the main two tabs. Here's a quick mockup:

screen shot 2016-08-05 at 10 10 43 am

Would it be asking to much to not show this to brand new users? Can we limit it to display until their second (or third, or fifth?) session? I'd really hate to see up aggressively upsell brand new users before we have the chance to get them "hooked" and coming back.

**Comment by rralian** [comment]
> Would it be asking to much to not show this to brand new users? Can we limit it to display until their second (or third, or fifth?) session? I'd really hate to see up aggressively upsell brand new users before we have the chance to get them "hooked" and coming back.

I think it only seems aggressive because we've never done it before. If a user goes through and picks a free plan initially, I think we should make it easy to upgrade, and right now that's pretty buried. Your design seems pretty unobtrusive to me. I would not hide this from brand new users, as our retention from that first signup session isn't where we want it to be yet. My two cents.

**Comment by shaunandrews** [comment]
> I think it only seems aggressive because we've never done it before.

Its aggressive because we've already tried to "upsell" them a number of times before and during signup. To do it again immediately after signup just feels too pushy.

> I think we should make it easy to upgrade, and right now that's pretty buried.

I don't disagree. My point is simply that we should time our upsell to be more effective — do it after we've proven out worth, not before. New users will have already been presented many opportunities to upgrade before they land in Calypso for the first time.

**Comment by folletto** [comment]
> I think it only seems aggressive because we've never done it before.

It's aggressive because it's in the main, top, primary navigation of the site. It doesn't have to be done before to know it's aggressive. It's always there, always visible, and cheapens the experience. Makes people feel bad.

**Comment by apeatling** [comment]
I think we need to take a step back here. There is no design for this right now, and no explanation as to why we are doing it. It's easy to strongly react against a change like this, but give us some time to work on this further and explain our reasoning.

**Comment by folletto** [comment]
> It's easy to strongly react against a change like this

True, but let me add a second one thing: the masterbar is a **critical** piece of the overall navigation, where even to add functional, useful, structural pieces we discuss months. It's visible all the time, everywhere. 

_Nothing_ should be added lightly there.

**Comment by apeatling** [comment]
@folletto You know how I feel about the masterbar :)

**Comment by meremagee** [comment]
Do we think this needs the most prominent location in our application because:
- it's not discoverable in its current `Plans` home? Perhaps we should test changing the language in the sidebar.
- contextual nudges are ill-timed and so we need something persistent to catch users when they're most likely to upgrade?
- the design and extensive thought put into the master bar development was misguided and needs to be reexamined?

**Comment by apeatling** [comment]
I would actually prefer to move forward with a different approach to this. I will write up a P2 post about it. I don't think having a button in Calypso, where we already have a fairly prominent plans link in the sidebar is as beneficial as something on the logged out front end.

**Comment by karmatosed** [comment]
Placing aside I strongly agree with what @shaunandrews says:

> Its aggressive because we've already tried to "upsell" them a number of times before and during signup. To do it again immediately after signup just feels too pushy.

To a user, it's such a delicate balance and this feels like we're tipping it.

From a purely functional view point I would actually also be against adding more to the masterbar. My thoughts are simply how it adapts to other devices and keeping a constant point visually for users. More clutter and the harder something becomes to understand and actually often then it's ignored more.

**Comment by apeatling** [comment]
Let's close this one for now, thanks for the feedback here, it's a touchy area and understandably so. We'll present this in more of a thought out way on a P2 post first.

**Pull request closed without merging**
