### PR TITLE
Theme: preload highres screenshot before rendering if client is HIDPI

### PR DESCRIPTION
**Pull request by budzanowski**
### Info
The Theme component used in ThemesList in `/design` endpoint fetches the high resolution screenshot on client when it notices that the screen is HIDPI. This happens by change to `img src=...` param. Because image is not initially loaded we see a short (depending on connection speed ) flash of screenshot image. Pre-loading the image should minimize this effect.
This is basically a question does this makes sense and is this correct/better?

### Testing
I don't really know how to test it in dev mode where a lot of stuff is happening on start.

### CODE REVIEW

**Comment by seear** [comment]
Not completely sure what I should be looking for?

On master, we see this react reconciliation problem on retina:
screen shot 2017-03-31 at 14 55 49

And on this branch, we have a different reconciliation problem:
screen shot 2017-03-31 at 15 01 38

**Comment by budzanowski** [comment]
@seear This was a check if it is would be possible to "easy" fix the after load screenshots flash on Retina screens when we change the size from 340 to 680 :)

**Comment by seear** [comment]
> This PR is a quick check if it is would be possible to "easy" fix the after server load screenshots flash on Retina screens when we change the size from 340 to 680 :)

Gotcha 👍 

I don't think we will be able to tell visually until we fix all the reconciliation errors, because as long as there is a checksum mismatch, the client will re-render everything, giving a content flash.

**Comment by ockham** [comment]
Could we circumvent the issue altogether by using a `srcset`?

**Comment by budzanowski** [comment]
Closed in favor of #12785

**Pull request closed without merging**
