### PR TITLE
Goals Capture: Update styling to match i1 UI.

### PR DESCRIPTION
**Pull request by yansern**
#### Proposed Changes

* Updates Goals Capture styling to match i1 UI.

#### Testing Instructions

* Go to `calypso.localhost:3000/setup/goals?siteSlug=test153716255.wordpress.com&flags=signup/goals-step`.
* Check for any layout issues in both desktop & mobile view.

### CODE REVIEW

**Comment by ivan-ottinger** [comment]
I noticed that the new design has different Goals' labels when compared to the old design:

Markup on 2022-06-21 at 13:28:00

Wondering if this is accidental or maybe on purpose (?) 🤔 @saygunnyc

**Comment by yansern** [comment]
**Decided on for now:**
Write & Publish
Sell online
Promote myself or business
Other

**Review by phcp — APPROVED** [review]
I tested locally and it's working as expected.
image

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/7389106

Thank you @yansern for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/7389106).

**Pull request merged**
