### PR TITLE
WIP: Industry Step

### LINKED ISSUE #59766: Woo Installer: Industry Step
Create the about your business step in the new woo installer. seen in the original flow
Screen Shot 2022-01-04 at 11 58 41 AM

This component needs to:
- [ ] Show a list of industries so the user can select multiple ones.
- [ ] Save the user selection.
- [ ] Show the user selection when visited after the user have saved a selection (?).
- [ ] Let the user add its own industries using the "other" option with details.

This component also probably needs some design feedback @SaxonF.

Branch/Draft PR: https://github.com/Automattic/wp-calypso/pull/59826

### PR DESCRIPTION
**Pull request by Rolilink**
#### Changes proposed in this Pull Request

*

#### Testing instructions

*

Fixes #59766

### CODE REVIEW

**Comment by retrofox** [comment]
About folder name: `client/signup/steps/woocommerce-install/industry-step/index.tsx`
We need to be consistent with the step names. The [woocommerce-install](https://github.com/Automattic/wp-calypso/tree/trunk/client/signup/steps/woocommerce-install/) folder is getting unorganized.
I suggest adding the `step-` prefix to all signup step folders. 
That's why I defined `step-store-address` in the last step that worked.
We should rename the other steps to`step-confirm` and `step-transfer`, too
I prefer prefix vs suffix because the step folders will end up together.

Take it just as a suggestion :-)

**Comment by Rolilink** [comment]
> About folder name: `client/signup/steps/woocommerce-install/industry-step/index.tsx` We need to be consistent with the step names. The [woocommerce-install](https://github.com/Automattic/wp-calypso/tree/trunk/client/signup/steps/woocommerce-install/) folder is getting unorganized. I suggest adding the `step-` prefix to all signup step folders. That's why I defined `step-store-address` in the last step that worked. We should rename the other steps to`step-confirm` and `step-transfer`, too I prefer prefix vs suffix because the step folders will end up together.
> 
> Take it just as a suggestion :-)

Sounds like a good suggestion will do that!

**Comment by lsl** [comment]
Don't need this for now, [added a note here](https://github.com/Automattic/wp-calypso/issues/57422#issuecomment-1014879589).

**Comment by obenland** [comment]
Skipping this one as it's not needed for launch for now

**Pull request closed without merging**
