### PR TITLE
Users management: Invite form revamp

### PR DESCRIPTION
**Pull request by bogiii**
#### Proposed Changes

* Redesigned Invite form
* Rewritten and simplified the `InvitePeople` component.
  * Divided into smaller components for easier maintenance
  * Moved some API integration into invites redux store

#### Testing Instructions

**Invite form**
* Go to `/people/new/{SITE_SLUG}`
* Move between different role
* Check if sending invites works as expected
* You can compare with the old one accessible from route: `/people/new/{SITE_SLUG}?flags=-user-management-revamp`

**Invite link form**
* Go to `/people/new/{P2_SITE_SLUG}`
* Check if generating link work properly

**Known issue**
The button "Invite to the workspace instead." has `null` value in `href` link. The issue exists on the current invite-people integration and will be fixed in future PRs.

#### Screenshots
Markup on 2022-12-22 at 12:25:42

Screenshot 2022-12-21 at 14 28 25

Screenshot 2022-12-22 at 09 19 33

Screenshot 2022-12-22 at 09 19 22

#### Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

Related to #70697

### CODE REVIEW

**Review by vishnugopal — APPROVED** [review]
Two small niggles that I hope can be fixed: 
https://user-images.githubusercontent.com/533/209282021-aeeaa2d8-8805-4f7f-a321-e2353efded9a.mp4

1. The 1Password popup, can that be removed? Think it can be done by setting a `autocomplete` attribute?
2. It's a bit jarring that once we have a successful entry, a new field comes at the bottom with no indication of success. Perhaps we can have a tickbox at the right?

Both of these seem minor, so approving! I tested this with end to end inviting a bunch of folks and it worked.

**Comment by vishnugopal** [comment]
Please fix the (minor) unit test error here which seems genuine!

**Comment by bogiii** [comment]
> The 1Password popup, can that be removed? Think it can be done by setting a autocomplete attribute?

It can not be removed. They suggest trying with the autoComplate="off" attribute, but it doesn't work.
It depends on the input field name and label name. If the name contains "email" or "password" word, it will add 1password by default. More info here -> https://1password.community/discussion/comment/606453/#Comment_606453

**Comment by bogiii** [comment]
> It's a bit jarring that once we have a successful entry, a new field comes at the bottom with no indication of success. Perhaps we can have a tickbox at the right?

The validation "tick" icon has been added on the right side of the input.
Screenshot 2022-12-23 at 15 21 30

**Pull request merged**
