### PR TITLE
Reader: remove Cold Start

### PR DESCRIPTION
**Pull request by bluefuton**
We stopped sending users to Reader Cold Start back in November '16: https://github.com/Automattic/wp-calypso/commit/62a64628494c05887874f84922c37af573ad6991.

This PR removes all outstanding code related to Cold Start.

What's been removed?
- Cold Start stylesheet
- Recommendations query component (`client/components/data/query-reader-start-recommendations`)
- Cold Start components and controller in `client/reader/start`
- Stats: `/recommendations/start` path removed from `client/reader/stats.js`
- Cold Start Redux malarkey in `client/state/reader/start`
- Config keys and feature flag
- `react-masonry-component` package and regenerated shrinkwrap
- Cold Start-specific Redux action types (thanks @blowery)

### CODE REVIEW

**Comment by samouri** [comment]
@bluefuton, is there anything in particular I should test?

**Comment by bluefuton** [comment]
> is there anything in particular I should test?
I just scrolled around a couple feeds + discover + mylikes and clicked into posts and it LGTM.

None of the Cold Start code is currently active, so "Reader functions as normal" is a pass :)

**Comment by blowery** [comment]
Could ditch the `READER_START_*` action types too?

**Comment by blowery** [comment]
just for posterity:

```
130K accept-invite					      |	131K accept-invite
102K accept-invite.min						102K accept-invite.min
241K account							241K account
179K account.min					      |	178K account.min
67K ads								67K ads
51K ads.min						      |	52K ads.min
236K async-load-components-post-schedule			236K async-load-components-post-schedule
159K async-load-components-post-schedule.min			159K async-load-components-post-schedule.min
187K async-load-featured-image				      |	186K async-load-featured-image
122K async-load-featured-image.min				122K async-load-featured-image.min
87K async-load-my-sites-drafts-draft-list			87K async-load-my-sites-drafts-draft-list
60K async-load-my-sites-drafts-draft-list.min			60K async-load-my-sites-drafts-draft-list.min
12K async-load-post-editor-drafts-button			12K async-load-post-editor-drafts-button
7.2K async-load-post-editor-drafts-button.min			7.2K async-load-post-editor-drafts-button.min
126K async-load-post-editor-editor-author			126K async-load-post-editor-editor-author
88K async-load-post-editor-editor-author.min			88K async-load-post-editor-editor-author.min
66K async-load-post-editor-editor-discussion			66K async-load-post-editor-editor-discussion
45K async-load-post-editor-editor-discussion.min		45K async-load-post-editor-editor-discussion.min
75K async-load-post-editor-editor-location			75K async-load-post-editor-editor-location
51K async-load-post-editor-editor-location.min			51K async-load-post-editor-editor-location.min
74K async-load-post-editor-editor-post-formats-accordion	74K async-load-post-editor-editor-post-formats-accordion
51K async-load-post-editor-editor-post-formats-accordion.min	51K async-load-post-editor-editor-post-formats-accordion.min
70K async-load-post-editor-editor-seo-accordion			70K async-load-post-editor-editor-seo-accordion
48K async-load-post-editor-editor-seo-accordion.min		48K async-load-post-editor-editor-seo-accordion.min
113K async-load-post-editor-editor-sharing-accordion		113K async-load-post-editor-editor-sharing-accordion
80K async-load-post-editor-editor-sharing-accordion.min		80K async-load-post-editor-editor-sharing-accordion.min
572K async-load-post-editor-media-modal				572K async-load-post-editor-media-modal
394K async-load-post-editor-media-modal.min			394K async-load-post-editor-media-modal.min
3.9M build-production						3.9M build-production
2.5M build-production.min					2.5M build-production.min
717K commons						      |	264K commons
525K commons.min					      |	177K commons.min
49K customize							49K customize
32K customize.min					      |	31K customize.min
3.1K discover						      |	456K discover
2.5K discover.min					      |	349K discover.min
168K happychat							168K happychat
129K happychat.min					      |	128K happychat.min
308K help							308K help
235K help.min							235K help.min
11K mailing-lists						11K mailing-lists
8.2K mailing-lists.min						8.2K mailing-lists.min
8.8K manifest						      |	8.7K manifest
6.3K manifest.min						6.3K manifest.min
166K me							      |	165K me
127K me.min						      |	126K me.min
277K media						      |	276K media
205K media.min							205K media.min
363K menus							363K menus
240K menus.min							240K menus.min
277K notification-settings				      |	276K notification-settings
215K notification-settings.min					215K notification-settings.min
3.0K paladin							3.0K paladin
2.4K paladin.min						2.4K paladin.min
230K people							230K people
181K people.min							181K people.min
256K plans							256K plans
198K plans.min							198K plans.min
649K plugins						      |	648K plugins
495K plugins.min					      |	494K plugins.min
2.6M post-editor						2.6M post-editor
1.6M post-editor.min						1.6M post-editor.min
182K posts-custom						182K posts-custom
124K posts-custom.min						124K posts-custom.min
374K posts-pages						374K posts-pages
266K posts-pages.min						266K posts-pages.min
448K purchases							448K purchases
352K purchases.min						352K purchases.min
5.4K reader-activities					      |	458K reader-activities
4.4K reader-activities.min				      |	351K reader-activities.min
100K reader-following					      |	553K reader-following
75K reader-following.min				      |	422K reader-following.min
18K reader-list						      |	471K reader-list
15K reader-list.min					      |	362K reader-list.min
26K reader-post-recomendations				      |	478K reader-post-recomendations
21K reader-post-recomendations.min			      |	368K reader-post-recomendations.min
21K reader-search					      |	474K reader-search
16K reader-search.min					      |	363K reader-search.min
187K reader-start					      |	682K reader-tags
103K reader-start.min					      |	496K reader-tags.min
229K reader-tags					      |	627K reader
149K reader-tags.min					      |	472K reader.min
174K reader						      <
125K reader.min						      <
450K security							450K security
338K security.min						338K security.min
503K settings-seo						503K settings-seo
277K settings-seo.min						277K settings-seo.min
846K settings						      |	841K settings
620K settings.min					      |	615K settings.min
244K sharing							244K sharing
177K sharing.min						177K sharing.min
679K signup						      |	680K signup
540K signup.min							540K signup.min
468K stats						      |	462K stats
345K stats.min						      |	340K stats.min
154K theme						      |	152K theme
110K theme.min						      |	109K theme.min
278K themes						      |	276K themes
208K themes.min						      |	206K themes.min
1.1M upgrades							1.1M upgrades
844K upgrades.min						844K upgrades.min
1.7M vendor.production.js					1.7M vendor.production.js
985K vendor.production.min.js					985K vendor.production.min.js
```

**Comment by blowery** [comment]
For posterity, here's how I generated that:

```
rm -f public/*.js
CALYPSO_ENV=production make build
( cd public; ls -hl *.js > ../master.txt )
cat master.txt | tr -s ' ' | cut -d' ' -f5,9 | tee master-trimmed.txt
git checkout remove/reader/cold-start
# repeat above, but name the files no-cold-start.txt
# edit the -trimmed files, removing the hashes from the filenames
# could probably do that step with awk, but I need to learn awk
diff -y master-trimmed-no-hash.txt no-cold-start-trimmed-no-hash.txt
```

**Comment by blowery** [comment]
Saw a massive drop in commons.js and a sizeable jump in the reader chunks.

**Pull request merged**
