### PR TITLE
Reader: Use dropdown for email delivery frequency

### LINKED ISSUE #96584: Reader: Email periodicity labels overflow in Spanish
### Quick summary

These buttons need more room or the ability to overflow to a second row/line.

Image

### Steps to reproduce

1. Set you account to Spanish
2. Visit the subscription settings
3. Notice how the email periodicity labels overflow

### What you expected to happen

They should fit

### What actually happened

They did not

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### If the above answer is "Yes...", outline the workaround.

Buttons are still clickable but they look bad.

### Platform (Simple and/or Atomic)

_No response_

### Logs or notes

_No response_

### PR DESCRIPTION
**Pull request by taipeicoder**
Fixes https://github.com/Automattic/wp-calypso/issues/96584

## Proposed Changes

This PR updates the email frequency component to use dropdown instead of segment controls. There are 3 affected areas:

/read/feeds/:feedId
| Current | Proposal | Proposal (expanded) |
| --- | --- | --- |
| Screenshot 2024-12-24 at 2 58 10 PM | Screenshot 2024-12-24 at 2 58 21 PM |  Screenshot 2024-12-24 at 2 58 16 PM |

/read/subscriptions/:subscriptionId
| Current | Proposal | Proposal (expanded) |
| --- | --- | --- |
| Screenshot 2024-12-24 at 2 58 33 PM | Screenshot 2024-12-24 at 2 58 40 PM | Screenshot 2024-12-24 at 2 58 45 PM|

/read/subscriptions

| Current | Proposal | Proposal (expanded) |
| --- | --- | --- |
| Screenshot 2024-12-24 at 2 59 12 PM | Screenshot 2024-12-24 at 2 59 19 PM | Screenshot 2024-12-24 at 2 59 26 PM |

## Why are these changes being made?

Contributes to the overall polish of WordPress.com.

## Testing Instructions

* Head to /read/subscriptions
* Click on the ellipsis icon and ensure that the email frequency setting has been updated to dropdown
* Ensure that setting can be updated properly
* Click on any site title to land on the /read/subscriptions/:subscriptionId page
* Ensure that the email frequency setting has been updated to dropdown and can be updated properly
* Click on the site icon to land on the /read/feeds/:feedId page
* Click on the settings icon and ensure that the email frequency setting has been updated to dropdown and can be updated properly

## Pre-merge Checklist

- [x] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [x] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [x] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [x] Have you checked for TypeScript, React or other console errors?
- [x] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [x] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
    - [x] For UI changes, have we tested the change in various languages (for example, ES, PT, FR, or DE)? The length of text and words vary significantly between languages. 
- [x] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Comment by crisbusquets** [comment]
Thanks for sharing, @taipeicoder !

I like how this approach allows us to support more languages. I'm not convinced with how `/read/subscriptions/:subscriptionId` looks.

Can we adapt the dropdown to the length of the longest text? In the screenshots, that would be `Instantly`. Having it at 100% width feels too much.

Like how GitHub handles this, for example:
github-emails

**Comment by taipeicoder** [comment]
@crisbusquets thanks for the review. Just to confirm, is it just for /read/subscriptions/:subscriptionId in particular or should all three dropdowns adapt to the length of the longest text?

**Comment by crisbusquets** [comment]
> @crisbusquets thanks for the review. Just to confirm, is it just for /read/subscriptions/:subscriptionId in particular or should all three dropdowns adapt to the length of the longest text?

If it's easier to implement, let's do it for the three of them.

**Comment by taipeicoder** [comment]
Sounds good, I've updated them 🙂

Screenshot 2024-12-24 at 6 51 52 PM

Screenshot 2024-12-24 at 6 51 47 PM

Screenshot 2024-12-24 at 6 51 42 PM

**Comment by taipeicoder** [comment]
Merging this PR, @Automattic/loop @nuriapenya @crisbusquets let me know if there are further concerns. We can iterate if that's the case.

**Pull request merged**
