### PR TITLE
Using UTC rather than local time for the post-streak

### PR DESCRIPTION
**Pull request by spentay**
Hi All!

I'm running unit tests here in Australia and finding that certain tests fail due to my timezone.
Investigating these tests have led to finding a couple of potential bugs.

### Issue

It appears that when posts are shown on the post-streak graph, they are done so relative to the user's current time-zone. If the user changes their time zone or another account member looks at this graph in a different location there could be inconsistencies.

For example, when testing this I posted 2 posts yesterday, one was earlier than 11PM local time, one was shortly after 11PM local time (both on the 3rd of Oct).

When I changed my time-zone to be 1 hour ahead of my local time-zone the 11PM+ post appeared on the graph as being published on the 4th of Oct (In the future!) as shown below:

Actual local time:

local-time

Manually set TZ to 1 hour ahead:

one-hour-ahead

### Reproducing Functionality

Post a number of posts at different times (over different hours)

Note that these posts will appear on your graph as being posted on the same day as each other as expected.

Change your timezone to be far enough ahead of the last post time to push this in to the next day (if you posted at 14:30, make sure the TZ is 10 hours ahead of your local TZ)

Now note that that post is now listed as being authored the next day.

### Reproducing Failing Tests.

Manually set your timezone to be far in to the Western hemisphere (choosing Eastern Australia would be a exact match).

run client tests (npm run test-client)

Note that some tests now fail.

### Solution

To fix this I've updated the the line where moment.js is used to compare utc-based times rather than the local with the UTC value from the server.
This fixes the tests and, I believe, the functionality.

### Notes:

There will still be 1 test failing after applying this PR as this only fixes 2 out of 3.
I have a PR up for the other 1 @ #8462

### CODE REVIEW

**Comment by dmsnell** [comment]
Thanks again @SpenUK for this great work. Just to confirm, after we aggregate the stats by their UTC times, do we still track properly in the local time display? In other words, if the UTC post times are 11pm and 1am but local we are UTC-2, we _should_ see posts posted on the same day at 1am and 3am, but if we are UTC+0 we should see one post each on two days at 11pm and 1am, right?

**Comment by SpenUK** [comment]
I'll take a closer look at some edge cases after work this evening and draw up some scenarios to compare - These timings can be a bit confusing but once I have a few scenarios down on paper it should all make sense :D

(Thanks for taking a look over this PR btw!)

**Comment by timmyc** [comment]
@SpenUK thanks for taking the time to submit this PR, much appreciated!  So the "standard" that was taken with stats ( though looks like not in this component ) is to utilize the site's offset [example](https://github.com/Automattic/wp-calypso/blob/master/client/my-sites/stats/controller.js#L279).

I do think that it might be best to simply put this fix in at the API level as well.

**Comment by SpenUK** [comment]
Hi @timmyc, that makes sense to me!
Just to be sure of the intended logic - no matter the timezone of the reader they always see the date/time in relation to the post's site (the current settings of that site).

I've pushed another commit that works and has tests passing although I would rather have used a spy than have had to add in a 'sites' object to each test that calls 'getSiteStatsPostStreakData()'.
I couldn't seem to get spies working with mockery/sinon but I'll be giving that another go later today :D

Using the offset also makes it easier to test the more _edge_ cases, which could help towards documenting the behaviour - so I can add more test cases for that too.

Also you mention that this would be best fixed at the API level... Would that be done as part of Calypso or elsewhere?

**Comment by dmsnell** [comment]
@SpenUK we wouldn't be able to fix the API here inside of Calypso. Maybe @timmyc knows where to hit it up. Are you suggesting that the API currently returns local time according to the user setting and we could fix it if we returned UTC time from the API?

**Comment by timmyc** [comment]
Funny enough the API *does* currently calculate the streak based upon ` get_blog_option( $site_id, 'gmt_offset' )` - but for the raw post numbers it is returning a GMT based timestamp count - sorry had to go refresh my memory of this endpoint.

As such I think the approach here is the right direction.  One item that I'm not sure about is calling the `getSite` selector within the stat selector itself.  How about grabbing the `gmt_offset` via [`getSiteOption`](https://github.com/Automattic/wp-calypso/blob/master/client/state/sites/selectors.js#L277), and passing it in as part of the `query` object passed to `getSiteStatsPostStreakData`?  From there we can default `gmt_offset` to 0 if `getSiteOption` is null.

**Comment by SpenUK** [comment]
Hey @timmyc ! Thanks for pointing me toward getSiteOption.
I was a little hesitant with the approach as it could be missed if the call was being made in multiple places each with it's own query argument - turns out there's only one right now :)

I made a few changes to the unit tests: using different timestamps that represent times at both ends of the day (00:30 and 23:30) to better test cases where setting the gmt_offset causes those timestamps to fall outside of the UTC day.
I've also left comments by these timestamps to help future readers understand what times are being tested and help them more quickly understand why the tests expect certain behaviour.

Let me know if I can improve any of this further :D

**Comment by SpenUK** [comment]
Another question...

When making the edits to 'my-sites/stats/post-trends/index.jsx' the linter raised warnings, presumably because that code was written before the introduction of those offending lint rules.

Should I make the updates as part of this PR or request a new PR with those changes in isolation?
I'm keen to make the changes - just not sure how best to organise the PR(s) in this case :)

**Comment by dmsnell** [comment]
@SpenUK it's fine to just fix the time issues here in this PR. You're welcome to address the linting issues, but you are right in that it's raising them since they already existing and you are now just updating the file.

**Comment by SpenUK** [comment]
Thanks @dmsnell! - I've got that pretty much good to go in another branch :P

**Comment by dmsnell** [comment]
@timmyc do we have any reason not to go ahead and merge this?

**Comment by timmyc** [comment]
Took it for one last spin.  Looks good.  Thanks again @spentay

**Comment by spentay** [comment]
Thanks @timmyc & @dmsnell for helping to get this landed!
I'm working on putting together a tracking issue for the other areas that would benefit from being UTC-ified - I'll reference this PR once that's done :D

**Pull request merged**
