### PR TITLE
Gutenberg: Redirect to Calypsoify

### PR DESCRIPTION
**Pull request by Copons**
#### Changes proposed in this Pull Request

* Redirect sites that have opted-in to Gutenberg to the Calypsoified WP-Admin Gutenberg editor.

Replaces #27317
Uses parts of @kwight's #27793 and @mmtr's 78ddbe6.

#### Testing instructions

* Opt-in to Gutenberg by:
  - Opening a Calypso Classic editor, click on the "Try our new editor and level-up your layout." message in the sidebar, and "Try the new editor".
  - Or... `dispatch( { type: 'EDITOR_TYPE_SET', siteId: 12345678, editor: 'gutenberg' } )`.

* Test these routes and make sure they redirect to the expected destinations:

| Routes to test | Expected Destinations |
| - | - |
| `/post/{ site }` | `/wp-admin/post-new.php?calypsoify=1` |
| `/page/{ site }` | `/wp-admin/post-new.php?calypsoify=1&post_type=page` |
| `/edit/{ customPostType }/{ site }` | `/wp-admin/post-new.php?calypsoify=1&post_type={ customPostType }` |
| `/post/{ site }/{ postId }` | `/wp-admin/post.php?calypsoify=1&post={ postId }&action=edit` |
| `/page/{ site }/{ postId }` | `/wp-admin/post.php?calypsoify=1&post={ postId }&action=edit` |
| `/edit/{ customPostType }/{ site }/{ postId }` | `/wp-admin/post.php?calypsoify=1&post={ postId }&action=edit` |

Notes:
- All routes with post ID "ignore" the post type.
- The network request to set the editor type might fail, but Calypso should honor the request anyway.
- The Gutenberg editor might not look Calypsoified yet.

### CODE REVIEW

**Comment by kwight** [comment]
@Copons hopefully this helps. I've merged in the bits from #27793 that involved using a data getter to determine the site's editor, before doing a redirect (or not). It's rough, but seems to work as we expect. I've kept the commits simple so that you can see what I've done, and of course, feel free to roll back if this is only muddying the waters 😜

**Comment by alisterscott** [comment]
I know this is still marked in progress but I wanted to give some early feedback in case this is unknown

1. All routes worked for me except `http://calypso.localhost:3000/edit/feedback/eatkibbeling6.wordpress.com` which redirected to `https://eatkibbeling6.wordpress.com/wp-admin/&post_type=feedback` which was not found
2. Clicking edit on a post or page was sluggish, I'm not sure if this is expected:

editing post or page

**Comment by Copons** [comment]
> I know this is still marked in progress but I wanted to give some early feedback in case this is unknown
> 
> 1. All routes worked for me except `http://calypso.localhost:3000/edit/feedback/eatkibbeling6.wordpress.com` which redirected to `https://eatkibbeling6.wordpress.com/wp-admin/&post_type=feedback` which was not found
> 2. Clicking edit on a post or page was sluggish, I'm not sure if this is expected:

Thank you @alisterscott, those are both great catches!

1. It was a typo, fixed with 582a234.

2. This is a totally annoying one!
When changing section, immediately (before anything loads) some CSS classes are applied to the main layout div.
The (classic) `post-editor` section's classes hide masterbar and sidebar, and so there's that weird jankiness, only noticeable when changing from a Calypso section with masterbar/sidebar visible (e.g. not the classic editor) to the Calypsoified Gutenberg redirect.

**Comment by Copons** [comment]
@gwwar I've added the feature flag (only enabled in `dev` and `wpcalypso`) in 2969357.
Could you please check if the change sounds good to you?

**Comment by kwight** [comment]
Redirect works well for me too 👍 

It's super slow; not sure what we can do to follow up about that at this point (we're waiting on first the `siteId` to be available and useful, then waiting again for the `/gutenberg` call 🙃 ).

**Comment by kwight** [comment]
It feels like there should be a way to combine the two waiting operations; `waitForData` can take multiple job, but requires promises (which selectors like `getSelectedSiteId` don't have).

**Comment by gwwar** [comment]
> not sure what we can do to follow up about that at this point

@kwight One thing we can do is update literal edit links in sidebar and other high traffic areas to point at /wp-admin which avoids a redirect ;)

Note that we still need this code for folks who visit /post directly

**Comment by gwwar** [comment]
Should be good to land once we get a green run on canaries, re-adding needs review to trigger tests.

**Comment by alisterscott** [comment]
The canary tests were failing because our test site (e2eflowtesting3.wordpress.com) was set to use Gutenberg (I'm not sure why), but I've disabled Gutenberg on that site so our existing editor tests (and canary) passes still for this PR and when it's merged.

**Pull request merged**
