### PR TITLE
Sites Dashboard: Hide actions on a deleted site

### PR DESCRIPTION
**Pull request by okmttdhr**
Related to https://github.com/Automattic/dotcom-forge/issues/9903, https://github.com/WordPress/gutenberg/pull/67218

## Proposed Changes

This PR hides actions except "Restore" on a deleted site. 

before

https://github.com/user-attachments/assets/3f7686d0-b6ea-4e9f-8bd5-f593779a5b59

after

https://github.com/user-attachments/assets/01e9e78e-1713-4b30-bf4a-c259abcffc09

I removed the loading state, as the loading status in action items doesn’t seem to be natively supported. I don't think it will be a big issue, because after a success or failure, a notification will be displayed. We can follow up with [ActionWithModal](https://github.com/WordPress/gutenberg/blob/ed66cc50e3c0b6785a48c15230c090790c0b0e6c/packages/dataviews/src/components/dataviews-item-actions/index.tsx#L166) to handle actions' states, but I consider displaying a state for restoration to be a low priority at this time. CCing: @oandregal @youknowriad in case you have insight.

<details><summary>ver. 1</summary>
<p>

after

https://github.com/user-attachments/assets/35f8bf5a-ba7d-467f-b9fb-27456b7ae2e8

I retained the loading spinner in the status column, as loading status in actions doesn’t seem to be natively supported. This might be worth revisiting in a follow-up. 

</p>
</details> 

## Why are these changes being made?

https://github.com/Automattic/dotcom-forge/issues/9903

## Testing Instructions

* Go to /sites
* Test the Restore action for a deleted site

## Pre-merge Checklist

- [x] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [x] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [x] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [x] Have you checked for TypeScript, React or other console errors?
- [x] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [x] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [x] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Review by fushar — COMMENTED** [review]
Hmm, I found that restoring a site will make all deleted sites' spinner to be spinning:


https://github.com/user-attachments/assets/68e5c533-b670-46a3-9896-31657f3a3a3f

**Review by taipeicoder — APPROVED** [review]

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/17012540).

**Comment by candy02058912** [comment]
@okmttdhr came across this today, and we'd probably need to update the docs here: https://wordpress.com/support/delete-site/#restore-a-deleted-site

**Comment by okmttdhr** [comment]
> @okmttdhr came across this today, and we'd probably need to update the docs here: [wordpress.com/support/delete-site#restore-a-deleted-site](https://wordpress.com/support/delete-site/#restore-a-deleted-site)

Thanks for pointing it out! I filed an issue: https://github.com/Automattic/en.support-docs-content/issues/3006.

**Pull request merged**
