### PR TITLE
Settings/Framework: Remove HelloVote setting and notice

### PR DESCRIPTION
**Pull request by nylen**
Removes the HelloVote setting introduced in #8436 and notice introduced in #8423 (plus refinements in a few follow-up PRs).

### Screenshot: Setting

image

### Screenshot: Notice

image

### To test

Visit `/settings/general/$site` for a non-Jetpack site.  Verify that the setting disappears and the other settings still work.

Visit almost any site-specific page for a non-Jetpack site (editor, posts listing for example).  Verify that the HelloVote notice is not active and the main layout is not broken.  See #8423 for more detailed testing instructions for this feature.

### Note

There's still one instance of HelloVote-related code: the [`helloVoteDismissed` user preference](https://github.com/Automattic/wp-calypso/blob/f6127fb/client/state/preferences/schema.js#L18) in the user preferences schema.  I left this here to avoid unnecessarily invalidating saved state.

### CODE REVIEW

**Comment by gwwar** [comment]
@nylen it should be safe to remove `helloVoteNoticeDismissed`. Unless we specify `additionalProperties: false`, the schema will ignore extra props by default.

**Comment by gwwar** [comment]
LGTM Let's get rid of that last reference in the schema, then 🚢

**Comment by aduth** [comment]
We should also (separately) think about a mechanism for purging deprecating preferences when they're detected in the response payload.

**Comment by nylen** [comment]
Done, and good to know.  Thanks for taking a look!

I still have `mediaItemsPerRow` in my preferences from early development of the media slider.  I agree it would be good to get rid of those.

**Pull request merged**
