### PR TITLE
Sync translatable strings from the widget

### PR DESCRIPTION
**Pull request by kthai15**
## Proposed Changes

- BlazePress: Add new English originals for translation.

## Testing Instructions

- Code review

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

**Comment by kthai15** [comment]
@dlind Please review when you get a chance 😃 . Also once this is merged, does it actually need to be deployed, since it's just changing the translations file?

**Review by dlind1 — APPROVED** [review]
LGTM!
Once its merged, the deployment would have to follow shortly, otherwise the bot in #calypso would start complaining about undeployed staged revision.

**Comment by kthai15** [comment]
Hi @dlind1, it seems that the unit tests are failing, I think because the `strings.ts` file generated for the DSP client doesn't contain the `{ count: <count> }` option for plurals translation when running `yarn translate`. Would you be able to take a look at that? Thanks! cc @benzhu56

**Comment by dlind1** [comment]
> Hi @dlind1, it seems that the unit tests are failing, I think because the `strings.ts` file generated for the DSP client doesn't contain the `{ count: <count> }` option for plurals translation when running `yarn translate`. Would you be able to take a look at that? Thanks! cc @benzhu56

Fixed in https://github.tumblr.net/Tumblr/a8c-dsp/pull/261, sorry for the delay.

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/8606161

Hi @kthai15, could you please edit the description of this PR and add a screenshot for our translators? Ideally it'd include all of the following strings:
- `Redirecting to my campaigns…`
- `Learn more about the {{linkAdvertisingPolicy}}Advertising Policy{{/linkAdvertisingPolicy}}.`
- `Fetching pages…`
- `Fetching more pages…`
- `Fetching more posts…`
- `Drop an image here to upload.`
- `Click or drag an image here to upload.`
- `Future reach is unavailable`
- `Credits: %(creditsUsed)s (%(remainingCredit)s remain)`
- `There was an error with the address. Please, check that the Zip code exists, is valid for the country, and corresponds for the given address`
- `Loading site…`
- `Preparing the wizard…`
- `Fetching subscriptions…`
- `hours ago`
- `1 day ago`
- `$%(creditUsed)s ($%(remainingCredit)s remain)`
- `Credits`

Thank you in advance!

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/8606161).

**Pull request merged**
