### PR TITLE
Login: Allow the user to resend their 2FA code

### PR DESCRIPTION
**Pull request by drewblaisdell**
WIP follow-up to #14539.

### CODE REVIEW

**Comment by stephanethomas** [comment]
@drewblaisdell: a heads-up that I amended your commit to remove an occurrence of `TWO_FACTOR_AUTHENTICATION_UPDATE_NONCE` left.

**Comment by drewblaisdell** [comment]
I updated this to separate the logic for starting/stopping polling into a new component, `PushNotificationApprovalPoller`, as we want to be able to poll from any sub-page of `log-in`. This seems preferable to passing a callback in an action to me, as:
   - The push poll reducer no longer needs to be concerned about the `log-in` route.
   - It is easier to tell when we are polling (whenever that component is mounted).
   - Ideally, we keep functions out of the global store since it should be serializable.

This also simplifies the second commit, which probably contained a little too much refactoring to the existing polling logic for this PR or a single commit. Apologies if I missed anything.

I think now we need to decide whether we really want to re-send the push notification (I commented about that [here](https://github.com/Automattic/wp-calypso/issues/14153#issuecomment-305363595)), and if we do:

- Handle the case where it is throttled.
- Handle the race condition if a push notification is re-sent while a poll request is in progress (these requests share a nonce).

**Comment by pento** [comment]
I'm strongly inclined to continue the behaviour of `wp-login.php` - don't resend the push notification, fall back to requesting an auth code if the push notification isn't available for any reason.

**Comment by gziolo** [comment]
Let's just remove link to resend push notification and we are all done. If the user has change auth type, there still can get push notification and tap the dialog on their mobile device. If they rejected it then they should use different method to make this flow bulletproof.

**Comment by fabianapsimoes** [comment]
As I mentioned in https://github.com/Automattic/wp-calypso/issues/14153#issuecomment-305363595, I'm also in favor of keeping the behavior of `wp-login.php` and remove the links back to `/login/push` from the other routes.

**Comment by fabianapsimoes** [comment]
cc @danhauk and @scruffian since this is a bit of a departure from the idea of always providing a way to reach all authentication methods available for a given user. It seems for the push notification case this is just not worth the complexity.

**Comment by danhauk** [comment]
This sounds like a good solution. I'm cool with removing the links back to `/push` on other auth methods.

**Comment by drewblaisdell** [comment]
Closing in favor of #14659

**Pull request closed without merging**
