### PR TITLE
Removes CSS %container @extends as they were only used once. Also @ex…

### PR DESCRIPTION
**Pull request by MichaelArestad**
Also, @extends are bad. There should be no visual changes.

I'm not sure how to test this one. It's used on the posts and welcome page according to the sass comment, but I think it's only used once in the NUX.

```
/**
* Welcome Messages (currently on stats and post pages)
*/
```

### CODE REVIEW

**Comment by mtias** [comment]
Thanks!

**Comment by lancewillett** [comment]
Needs conflict resolved...

**Comment by MichaelArestad** [comment]
@lancewillett ready for review.

**Comment by lancewillett** [comment]
🚢 LGTM

Before/after screenshots in Firefox stable on OS X 10.12.1.

screen shot 2016-11-11 at 23 49 44

screen shot 2016-11-11 at 23 51 35

**Pull request merged**
