### PR TITLE
Domains step: Improve domain title spacing on smaller screens

### LINKED ISSUE #94426: Stepper: Offer sticker overlaps domains
### Details

Reported in https://github.com/Automattic/wp-calypso/issues/94394

image

This happens in both /start and Stepper.
To trigger the offer I found that it is helpful to add a paid domain to the cart

### Checklist

_No response_

### Related

_No response_

### PR DESCRIPTION
**Pull request by renancarvalho**
Related to #94426
Fixes #94426

## Proposed Changes

* There are spacing issues when users choose excessively long domain names or titles. This affects both mobile and desktop views, with the main problem being the content growing too large to fit properly.

This PR addresses the issue by repositioning the 'deal' badges above the title and ensuring that overly long titles are automatically broken into multiple lines for better readability and layout.

Issue
image

Fix
image

## Why are these changes being made?

* Fixes this layout issue 
 
image

## Testing Instructions

* Navigate to any flow (e.g., /setup/onboarding/domains) and proceed to the domains step.

* Select an excessively long domain name and verify that the layout remains intact (compare it with the production version).
* Ensure the domain grid matches the provided screenshots.
* Compare it with the /start/onboarding flow and confirm that the horizontal scroll issue has been resolved, especially on mobile or smaller screens.

### CODE REVIEW

**Comment by renancarvalho** [comment]
@JanaMW27 or @nuriapenya would you be interested in taking a look at this one? You can easily do that with the live link and following the testing steps.
🙇

**Review by escapemanuele — COMMENTED** [review]
Thanks for working on this!

In the en version I see the sale text on two lines

image

That is probably breaking the design (as the price should be in line with the domain)

**Comment by renancarvalho** [comment]
> Thanks for working on this!
> 
> In the en version I see the sale text on two lines
> 
> image
> 
> That is probably breaking the design (as the price should be in line with the domain)

Addressed. Thank you!

**Comment by escapemanuele** [comment]
Trying with a long domain name I now see it like this. Maybe 3 rows is too much?

image

Max length of the domain in the input is 60 characters, can we have it in 2 rows? 

And the price [should](https://github.com/Automattic/wp-calypso/issues/94426#issuecomment-2349140913) be in line with the domain name, with the offer copy in line with the `Sale` text.

**Comment by JanaMW27** [comment]
I think setting up a max width for the domain and then domain name to other lines is a good logic to put in place to cover this edge cases.

**Review by escapemanuele — CHANGES_REQUESTED** [review]
Stepper now works great!

image

On /start there is some visual error though 

image

**Review by escapemanuele — APPROVED** [review]
Now it is working great! 👏

**Pull request merged**
