### PR TITLE
Swapping in new Facebook card content on Marketing Tools

### PR DESCRIPTION
**Pull request by donlair**
#### Changes proposed in this Pull Request

* Updating the Facebook card on Marketing Tools
* Additional context in pbBQWj-Hz-p2
* This will show EN only so doesn't need to wait for translations.

Here's a screenshot of the updated card:
Screen Shot 2021-03-12 at 10 07 13 AM

#### Testing instructions
* Checkout this PR and spinup Calypso.
* Navigate to marketing/tools/SITESLUG
* Confirm that the Facebook slug reflects the changes outlines in the P2 post above.

### CODE REVIEW

**Review by jaswrks — APPROVED** [review]
LGTM 🚢 
- Confirmed Tracks event not used in any funnels, so seems OK to change it.
- @donlair confirmed the CTA for free conditions will be added in a follow-up.

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/5578460

Thank you @donlair for including a screenshot in the description! This is really helpful for our translators.

**Comment by anitabonita** [comment]
très bien...

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/5578460).

**Pull request merged**
