### PR TITLE
Gravatar: Fix resend email not working for new user & Add countdown time for the resending email function

### PR DESCRIPTION
**Pull request by wellyshen**
Related to:

* 105699-Automattic/gravatar
* 105691-Automattic/gravatar

## Proposed Changes

* Enable `createAccount` for the resending email function
* Add countdown time for the resending email function
* Remove duplicated state selector (`[get-magic-login-is-fetching-email.js](https://github.com/Automattic/wp-calypso/pull/81544/files#diff-50db5d70f7263f2beaa955104b06e4e2c09dbd1a9da16f52b9214f0144c0398e)`), which was created from [this PR](https://github.com/Automattic/wp-calypso/pull/81258/files#diff-50db5d70f7263f2beaa955104b06e4e2c09dbd1a9da16f52b9214f0144c0398e)

## Testing Instructions

* Setup Calypso by following [this doc](https://github.com/Automattic/wp-calypso#getting-started), and check out this PR
* Log out your account
* Run `yarn start`, and create a new account via [this URL](http://calypso.localhost:3000/log-in/link?client_id=1854&redirect_to=https%3A%2F%2Fpublic-api.wordpress.com%2Foauth2%2Fauthorize%3Fclient_id%3D1854%26response_type%3Dcode%26blog_id%3D0%26state%3D434cd756529bcf3f73f447f1a358128078b4180858d4b8d59bf82cf108d799e1%26redirect_uri%3Dhttps%253A%252F%252Fen.gravatar.com%252Fconnect%252F%253Faction%253Drequest_access_token%26from-calypso%3D1)
* You will see the resending email countdown:
截圖 2023-09-08 下午3 37 09

* After the countdown finishes, click the resend email function, you will receive the signup email
* Log out of your account, and try to log in to your account, the resend email function should still work the same

## Pre-merge Checklist

- [x] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [x] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

**Comment by wellyshen** [comment]
@aaronfc Could you mind taking a look at this PR, thanks!

**Comment by wellyshen** [comment]
@aaronfc I think I will also need to let the user resend the email immediately once there's an API error.

**Review by aaronfc — COMMENTED** [review]
Hey, this is looking good. Unfortunately I couldn't get it working for a new email.

See the following video. Did I do something wrong?

https://github.com/Automattic/wp-calypso/assets/799065/09827135-0524-4904-a010-922da993b080

**Comment by wellyshen** [comment]
> Hey, this is looking good. Unfortunately I couldn't get it working for a new email.
> 
> See the following video. Did I do something wrong?
> 
>  Screen.Capture.on.2023-09-11.at.12-11-06.mp4

I didn't see the countdown in your video. Did you check this PR out by `git checkout update/gravatar-login-page`?

**Review by aaronfc — APPROVED** [review]
> I didn't see the countdown in your video. Did you check this PR out by git checkout update/gravatar-login-page?

You were right! I missed an error when pulling because of divergent heads :)

Looks good, and works well!

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/8922362

Thank you @wellyshen for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/8922362).

**Pull request merged**
