### PR TITLE
Premium Content: Add missing migrations for margin fix

### PR DESCRIPTION
**Pull request by apeatling**
#### Changes proposed in this Pull Request

* In https://github.com/Automattic/wp-calypso/pull/46579 margin issues were fixed, but the block migration functions were missed. This PR adds them.

#### Testing instructions

* Check out commit `570a7c788e02d36bccc13f220076bd856466713f`.
* Sync to your sandbox using `yarn dev --sync`
* Insert a Premium Content block on your sandboxed site and save the post/page.
* Check out this branch and resync.
* Reload the editor and confirm the migration worked (you should see this in the browser console).

Fixes invalidations in https://github.com/Automattic/wp-calypso/issues/46917

### CODE REVIEW

**Review by glendaviesnz — APPROVED** [review]
Following the test instructions the the migrations successfully ran for both subscriber view and logged out view:

```
Block successfully updated for `premium-content/subscriber-view` ({name: "premium-content/subscriber-view", icon: {…}, keywords: Array(0), attributes: {…}, providesContext: {…}, …}).

New content generated by `save` function:

<div class="wp-block-premium-content-subscriber-view entry-content"></div>

Content retrieved from post body:

<div class="wp-block-premium-content-subscriber-view"></div>
```

```
Block successfully updated for `premium-content/logged-out-view` ({name: "premium-content/logged-out-view", icon: {…}, keywords: Array(0), attributes: {…}, providesContext: {…}, …}attributes: {className: {…}}category: "design"deprecated: (2) [{…}, {…}]description: "Logged Out View."edit: ƒ (e)icon: {src: {…}}keywords: []name: "premium-content/logged-out-view"parent: ["premium-content/container"]providesContext: {}save: ƒ Save()styles: []supports: {inserter: false, html: false}title: "Logged Out View"usesContext: ["premium-content/planId"]__proto__: Object).

New content generated by `save` function:

<div class="wp-block-premium-content-logged-out-view entry-content"></div>

Content retrieved from post body:
<div class="wp-block-premium-content-logged-out-view">
</div>
```

**Review by stacimc — APPROVED** [review]
Tested well for me -- I can see the successful migration in the console.

**Comment by stacimc** [comment]
When I tested this, I see the successful block migration in the console, but the Premium Content block now renders with two sets of Subscribe/Log In buttons:

Screen Shot 2020-10-29 at 12 44 14 PM

**Comment by glendaviesnz** [comment]
Also double checked and the migration does result in a second instance of the block with fresh button settings - below shows my original block with button colour and radius changed and the second block that appears after migration with the default button settings:
Screen Shot 2020-10-30 at 8 56 30 AM

**Review by stacimc — APPROVED** [review]
Looks good to me! Confirmed that the buttons are no longer getting duplicated.

**Pull request merged**
