### PR TITLE
Reader: fix follow count for Tracks events

### LINKED ISSUE #14470: Reader: sending incorrect subscription_count for all stats
As @bluefuton found in https://github.com/Automattic/wp-calypso/pull/14383#issuecomment-304002025, 

> Works well! One thing I noticed is that we're no longer sending along the correct `subscription_count` with the event - need to change it to look at Redux state I think:

screen shot 2017-05-25 at 14 46 50

### PR DESCRIPTION
**Pull request by bluefuton**
#### Changes proposed in this Pull Request

In the pre-Redux days, Tracks events sent by Reader used to send the current user's follow count as an event property. This has not been working since 2017. As the code notes, the plan was to move this to Redux middleware:

https://github.com/Automattic/wp-calypso/blob/61acc957638fc7009632af4c0c058aa6bc0e82b7/client/reader/stats.js#L106-L109

The corresponding issue is https://github.com/Automattic/wp-calypso/issues/14470, and the missing count has recently been brought up by @martinremy in in p5PDj3-4WA-p2.

#### Testing instructions

Turn on Analytics logging in your console with:

`localStorage.setItem('debug', 'calypso:analytics*');`

Go to http://calypso.localhost:3000/read/conversations and try unfollowing and following an existing conversation via the ellipsis menu. The resulting Tracks events should contain a `subscription_count` key:

Screen Shot 2020-11-27 at 14 48 38

Partly fixes #14470 (we'll need to migrate all of the existing `recordTrack()` uses in a followup PR).

### CODE REVIEW

**Comment by bluefuton** [comment]
@Automattic/team-calypso @blowery I'd love your feedback on the general approach here. As far as I could see, I had three options, and for the moment I've got with the first one:

1. Add a separate analytics action and middleware for Reader that includes the follow count from state.
2. Add the follow count to the existing analytics middleware, perhaps checking for `reader` in the event name in order to decide when to add it.
3. Just pass the follow count in each case as an event property. This is simplest but would mean updating 20+ uses of `recordTrack` to fetch the follow count value in components.

**Comment by jsnajdr** [comment]
@bluefuton The middleware solution looks very complex and it's also undesirable to add new Redux middlewares. They add Reader-specific code to the common code that's loaded by all section, even when the user never navigates to Reader. We'd like to remove most middlewares eventually.

Creating a Redux thunk could be much simpler and is specific for the `reader` chunk:
```js
const recordReaderTracksEvent = ( name, properties ) => ( dispatch, getState ) => {
  const followsCount = getReaderFollowsCount( getState() );
  dispatch( recordTracksEvent( name, {
    subscription_count: followsCount,
    ...properties,
  } ) );
}
```

Would that work?

> This is simplest but would mean updating 20+ uses of `recordTrack` to fetch the follow count value in components.

I see that your patch updates only two usages in a single `handleFollowToggle` method. Are you going to update another 18+ usages at other places? I'm a little confused by what I see here 🙂

**Comment by bluefuton** [comment]
> Creating a Redux thunk could be much simpler and is specific for the reader chunk

Thanks @jsnajdr! That's much better. I wasn't happy with the complexity of the middleware solution or adding Reader-specific code in that spot.

Can we adapt this approach to be used with React hooks too?

> Are you going to update another 18+ usages at other places?

Correct 🙂 I wanted to settle on an approach before updating the many calls to `recordTrack()` sprinkled throughout Reader. I updated the conversation follow button only so we had a component to test.

**Comment by jsnajdr** [comment]
> Can we adapt this approach to be used with React hooks too?

Yes, the thunk is a dispatch-able Redux action like any other. It can be used with `useDispatch`:
```js
function UI() {
  const dispatch = useDispatch();

  const onClick = () => {
    dispatch( recordReaderTrackEvent( name, properties ) );
  };

  /* ... */
}
```

**Comment by blowery** [comment]
+1 to the thunk approach.

**Comment by bluefuton** [comment]
Thanks for the guidance @jsnajdr - the thunk works a treat :)

I've put this up for review and suggest we merge it with just the conversation follow button switched over. There are quite a lot of `recordTrack()` uses to change, so a handful of followup PRs would be easiest to test I think.

**Review by jsnajdr — APPROVED** [review]
Nice! 👍

**Review by tyxla — APPROVED** [review]
Looks and works great, thanks @bluefuton! 🚢

**Pull request merged**
