### PR TITLE
Jetpack Complete+Business provide unlimited premium themes

### PR DESCRIPTION
**Pull request by mreishus**
#### Changes proposed in this Pull Request

* Jetpack Complete and Jetpack Business provide unlimited premium themes
* On a Jetpack site, if you are viewing the theme info page for a premium theme and you do not have access, the Upgrade button will link you to Jetpack Complete instead of Realtime Security
  * See p1639518247313000/1639516498.305800-slack-C0113HTN28N

#### Testing instructions

* Be on the list of special users that can see the softlaunched themes (ask me or @sixhours)
* Create a test JP site (with say, JN)
  * While creating the site, use the extra options to use Jetpack Beta
  * Change the JN jetpack site to point to your sandbox (see: p9dueE-3Ih-p2#comment-6965 )
  * On sandbox, `sudo global-http enable`
* Link to WP.com
* Check out this branch
* Disable isomorphic attribute
```diff
diff --git a/client/sections.js b/client/sections.js
index 628832adfd..b1cceaf469 100644
--- a/client/sections.js
+++ b/client/sections.js
@@ -210,7 +210,7 @@ const sections = [
                module: 'calypso/my-sites/themes',
                enableLoggedOut: true,
                group: 'sites',
-               isomorphic: true,
+               // isomorphic: true,
                title: 'Themes',
        },
        {
@@ -219,7 +219,7 @@ const sections = [
                module: 'calypso/my-sites/theme',
                enableLoggedOut: true,
                group: 'sites',
-               isomorphic: true,
+               // isomorphic: true,
                title: 'Themes',
                trackLoadPerformance: true,
        },
```
* Run calypso locally
* Change to JP site
* Visit the theme showcase with `?flags=themes/premium`
* You should be able to **see** premium themes
* You should not be able to **use** premium themes
* If you try to purchase or activate a premium theme, it should send you to buy JP complete
* After buying JP complete, you should be able to use the premium theme

Related to #59156

### CODE REVIEW

**Comment by mreishus** [comment]
Created  Theme Showcase: Re-add banner advertising Jetpack plans that include premium themes #59210

**Comment by sixhours** [comment]
Testing this, I'm seeing "Theme not yet available for this site" when I try to activate any of the premium themes on my personal Jetpack site:
Screen Shot 2021-12-15 at 1 44 29 PM

I was sent through the correct check-out flow so now I do have Jetpack Complete, and I'm using the `themes/premium` flag, but any of the premium themes do not activate. Free themes still do.

**Comment by mreishus** [comment]
Seeing the same thing

Posting to `https://public-api.wordpress.com/rest/v1.1/sites/<sitenum>/themes/byrne/install`
```
{"code":404,"headers":[{"name":"Content-Type","value":"application\/json"}],"body":{"error":"theme_not_found","message":"This theme does not exist"}}
```

This is ultimately coming [from jetpack](https://github.com/Automattic/jetpack/blob/ed4b1e01b5f0151dc94b949d6a01fce717ec05fe/projects/plugins/jetpack/json-endpoints/jetpack/class.jetpack-json-api-themes-install-endpoint.php#L141).  It could be that when jetpack looks for the WPCOM theme, it's running into the softlaunch filter because it's not asking "as me".


----

Posting to `https://public-api.wordpress.com/rest/v1.1/sites/<sitenum>/themes/mine` with body `{"theme":"byrne"}`
```
{"code":404,"headers":[{"name":"Content-Type","value":"application\/json"}],"body":{"error":"theme_not_found","message":"The specified theme was not found."}}
```
Also coming [from jetpack](https://github.com/Automattic/jetpack/blob/ed4b1e01b5f0151dc94b949d6a01fce717ec05fe/projects/plugins/jetpack/json-endpoints/jetpack/class.jetpack-json-api-themes-active-endpoint.php#L35). 

----

I think next I should try a local jetpack docker site instead of JN.

**Comment by mreishus** [comment]
Regular theme install+activations through calypso aren't working on my Jetpack docker site. I'm not sure why, and nothing is being logged. https://github.com/WordPress/WordPress/blob/88b1019dc36550ba777cbc90ea7dc54c59035a45/wp-admin/includes/class-theme-upgrader.php#L230 is returning false most likely. Regular theme install+activations do work on my JN site, so this is a dev environment issue that has to be fixed before looking at the real problem

`tools/docker/wordpress/wp-content/debug.log` - has nothing

**Comment by mreishus** [comment]
I cannot install any wpcom theme on my local jetpack docker. Example:


The culprit seems to be that in jetpack, `validate_theme()` [looks to see if a theme name ends in `-wpcom`](https://github.com/Automattic/jetpack/blob/764969960e6e361f6cb7d587503ae5b2ad9ee089/projects/plugins/jetpack/json-endpoints/jetpack/class.jetpack-json-api-themes-install-endpoint.php#L115) to determine if it's a wpcom theme. Here, it sees the theme name `quadrat`, which is not `quadrat-wpcom`, so [it looks for the theme on .org](https://github.com/Automattic/jetpack/blob/764969960e6e361f6cb7d587503ae5b2ad9ee089/projects/plugins/jetpack/json-endpoints/jetpack/class.jetpack-json-api-themes-install-endpoint.php#L127) and fails.
I do not know why this works on JN.

To move forward I need to either:
1. Find out how to make installing wpcom themes through calypso to my jetpack docker site work, or
2. Modify a JN site so it accesses the themes available through the softlaunch filter

**Comment by mreishus** [comment]
I've found that even activating free themes on jetpack sites can act strangely when installing through calypso.

In this clip, I try to activate Quadrat Green, and I'm told that it's not available for my site. Then I visit the info page for it, and now I'm able to activate the same theme on the same site.


https://user-images.githubusercontent.com/937354/147983508-2aec8eed-6054-4cea-ac5b-83084bf1921c.mp4

The first time I try to activate, `isDownloadableFromWpcom()` cannot find the download location for `quadrat-green`, so the themeId used is `quadrat-green`.
The second time I try to activate, `isDownloadableFromWpcom()` finds the download location to be `https://public-api.wordpress.com/rest/v1/themes/download/quadrat-green.zip`, so the themeId used is `quadrat-green-wpcom`. The `-wpcom` suffix is an indication to jetpack that the theme is from wpcom and can be downloaded there.
The root cause is probably that visiting the info page caused some extra attributes about the theme to be fetched, like `.download`.

I have not tried this for premium themes yet - but if they are not downloadable, this may be the mechanism that is breaking.

**Comment by mreishus** [comment]
As suspected, premium themes do not have download links:


On WPCOM, this looks to be controlled by `wp-content/lib/wpcom-themes.php`'s  `get_public_download_url()` and `is_downloadable()`, which checks the database on the special site that we use for themes. Stylesheets like `pub/hever` are downloadable, but ones like `premium/baxter` are not.

Additionally, https://public-api.wordpress.com/rest/v1/themes/download/blockbase.zip downloads the theme, but https://public-api.wordpress.com/rest/v1/themes/download/baxter.zip provides a `theme_not_found` error.

If jetpack sites will install premium wpcom themes, they will need a way to download them.
However, `class.wpcom-json-api-get-theme-download-endpoint.php` does have an allowance for jetpack sites with the appropriate plan downloading premium themes. So it looks like that part is already built.

I think what remains is to let Jetpack know that there is a download link in certain cases. I wonder if this was working before and there was some code that I'm not seeing or that was removed in `wp-content/lib/wpcom-themes.php`, or whatever in calypso processes the results there.

Edit: I found that after disabling the `self::is_downloadable` and `self::get_download_info` checks in `get_public_download_url` in `wp-content/lib/wpcom-themes.php`, calypso now tries to tell the jetpack site to download `baxter-wpcom` with the url `https://public-api.wordpress.com/rest/v1/themes/download/baxter.zip`, but the jetpack site is not successful. I'm seeing error: `problem_fetching_theme`. I'm not sure exactly what's happening as the logs on the JN site don't explain more.

Edit2: It looks like `class.wpcom-json-api-get-theme-download-endpoint.php` is not able to find a theme matching the theme id `baxter-wpcom` and errors out early, before it reaches any of the premium stuff.. In comparison, it is able to translate
`( [theme_id] => geologist-blue-wpcom )`  to `(    [stylesheet] => pub/geologist-blue )`.

**Comment by mreishus** [comment]
Even though we're holding off on fixing the premium themes in jetpack flow, I think these changes are safe to go in right now.

* It changes the URL for the scenario of "You have jetpack, but need to upgrade your plan to activate premium themes" from "Buy Jetpack Realtime Security" to "Buy Jetpack Complete".
  * Jetpack Marketing told us they want to trim down what's offered in realtime security and remove non-security features like premium themes.
* It adds the "Premium Themes" capability to the Jetpack Complete and Jetpack Business plans
  * ac5375125 will still hide premium themes from standalone jetpack sites.
  * If a user on one of these plans was able to see the premium theme, they would not be prompted to buy a plan upgrade
  * The marketing copy is not changed.

The end result is that Jetpack users can still not see premium themes, but Calypso will now consider jetpack complete and jetpack business plans as having premium theme capabilities.

**Comment by sixhours** [comment]
Tested this again and nothing breaks, so I agree, it's probably safe to push out.

I wonder if the missing piece is generating the download for the premium theme in MC.

**Review by sixhours — APPROVED** [review]

**Pull request merged**
