### PR TITLE
Bump webpack and shrinkwrap

### PR DESCRIPTION
**Pull request by samouri**
Webpack just released [V3.7](https://github.com/webpack/webpack/releases) which has significant performance boost for anyone with cyclic dependencies in their chunks.

I noticed this shaving a few seconds from the client webpack build (for me its ~39s-->34s).

To Test:
- `npm start`. see if it works

### CODE REVIEW

**Comment by samouri** [comment]
magically solves: https://github.com/Automattic/wp-calypso/issues/16043
cc @gwwar

**Comment by samouri** [comment]
why is `fsevents` appearing and disappearing depending on who shrinkwraps (i know mac vs. ubuntu, but still not sure what to do about it).

**Comment by dmsnell** [comment]
> why is fsevents appearing and disappearing depending on who shrinkwraps (i know mac vs. ubuntu, but still not sure what to do about it).

you kind of answered your own question there. for reference check out https://github.com/npm/npm/issues/2679

**Comment by samouri** [comment]
Thanks for the thorough testing @blowery !

Much appreciated 🎉

**Pull request merged**
