### PR TITLE
Marketplace Reviews: Show pending review warning

### PR DESCRIPTION
**Pull request by WBerredo**
Fixes https://github.com/Automattic/dotcom-forge/issues/4824

## Proposed Changes

* Only display the write a review card if the user doesn't have a review (not even pending)
* On the Reviews list, show the user review even if its pending
  * Put a warning on the top when pending

CleanShot 2024-01-03 at 13 31 33@2x

## Testing Instructions

* Add a review on pending state on a plugin. You can use `/marketplace/test/:site` to add a review.
* Go to the plugin details page
* Confirm the review is not displayed on the cards
* Click on `Read all reviews`
* Check if your review is displayed but with a warning added above.
* Enable the flag `"marketplace-reviews-notification"` and check the message  is appended with `You will be notified once it is published.`. This should be released as soon as this feature is ready.

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

**Comment by gavande1** [comment]
I have tested this and works as described. I noticed few things that I would like to highlight. 

First, I noticed an upgrade nudge on the reviews modal. Is that what was expected? I have already submitted a review for the product. There might be a situation where a user buys the product on a different site. However, it still seemed out of place to me.

CleanShot 2024-01-04 at 12 02 00@2x

I enabled the flag and noticed some unnatural spacing between the sentences. We might want to correct it. It's a small thing, but I believe we should fix it.

CleanShot 2024-01-04 at 12 07 36@2x

**Comment by WBerredo** [comment]
>  enabled the flag and noticed some unnatural spacing between the sentences.

Thanks for catching this, fixed at https://github.com/Automattic/wp-calypso/pull/85956/commits/e109d463a5fd1c246179179d96f9185be7eb6a6a

> First, I noticed an upgrade nudge on the reviews modal. Is that what was expected? I have already submitted a review for the product. There might be a situation where a user buys the product on a different site. However, it still seemed out of place to me.

That's a good point, we can add a new validation to check if the user has already submitted a review, but I'm not sure if it would hurt to just keep this CTA there.

**Review by gcsecsey — APPROVED** [review]
Changes LGTM and work well.

WIth the notification flag enabled:
CleanShot 2024-01-04 at 15 46 39@2x

With the flag disabled:
CleanShot 2024-01-04 at 15 48 59@2x

**Comment by gcsecsey** [comment]
> > First, I noticed an upgrade nudge on the reviews modal. Is that what was expected? I have already submitted a review for the product. There might be a situation where a user buys the product on a different site. However, it still seemed out of place to me.
> 
> That's a good point, we can add a new validation to check if the user has already submitted a review, but I'm not sure if it would hurt to just keep this CTA there.

I also feel that the purchase CTA is a bit weird on the reviews modal from a UX standpoint. I think it could be confusing for users if it's displayed on top of the header section of the page because the regular CTA will be visible behind the modal. 

Maybe we can iterate a bit on how we display the CTA here, or how best to educate the user about what is required to add a review:
CleanShot 2024-01-04 at 15 55 42@2x
CleanShot 2024-01-04 at 15 58 19@2x

**Comment by WBerredo** [comment]
Agreed, adding @vinimotaa to the discussion for this topic but proceeding with the merge of this task and any agreement can be done in a follow-up task.

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/10671173

Some locales (Hebrew, Japanese) have been temporarily machine-translated due to translator availability. All other translations are usually ready within a few days. Untranslated and machine-translated strings will be sent for translation next Monday and are expected to be completed by the following Friday.

Thank you @WBerredo for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/10671173).

**Pull request merged**
