### PR TITLE
Framework: update to React 16, try 2

### PR DESCRIPTION
**Pull request by samouri**
take 2.

this broke the last go around because `webpack.config.node.js` had this code:
```js
// Map React and redux to the minimized version in production
if ( config( 'env' ) === 'production' ) {
    externals[ 'react-with-addons' ] = 'commonjs react/dist/react-with-addons.min';
    externals.react = 'commonjs react/dist/react.min';
    externals.redux = 'commonjs redux/dist/redux.min';
}
```

Turns out within node-modules we react was renamed from `react.min` to `react.min.js`

Easy enough to fix, but why are we even doing this?
- If we care about minifying on the server, lets uglify the whole bundle.
- If we don't care about it, then why are we hand-selecting specific packages to be minified?

To test:
- [ ] docker
- [x] local

### CODE REVIEW

**Comment by samouri** [comment]
fix for breakage is in: 47e0d46400f19c69c2a9694d649781dee49b372c

**Comment by ockham** [comment]
Also, do we still need `react-with-addons` at all?

**Comment by samouri** [comment]
> Docker build is failing for me…

really weird. 
no idea why it appears to have moved again (but built once for me).
Can you try again?

> Also, do we still need react-with-addons at all?

no we don't which is why i removed the line 👍

**Comment by sirreal** [comment]
👍 Docker is building now 🎉 

The build took a _very_ long time, I was about to abort when it completed. I don't believe it took that long before.

Everything looks good once I get everything running. I'll try to do some more extensive testing tomorrow.

**Comment by ockham** [comment]
>> Also, do we still need react-with-addons at all?

> no we don't which is why i removed the line 👍 

Meh, was misreading the PR desc :man_facepalming: Sry, should've checked the diff!

**Comment by gwwar** [comment]
Verified that the Docker image builds + did a bit of smoke testing. 

@alisterscott, @hoverduck  or @bsessions85 would it be possible to run the full e2e suite against this branch? ❤️

**Comment by samouri** [comment]
@gwwar: the flow folks E2E tested the previous branch and all thats changed since are jest files (https://github.com/Automattic/wp-calypso/pull/19083#issuecomment-341331532). 

That said, can't hurt to be extra careful!

**Comment by alisterscott** [comment]
All good for e2e tests 👍

**Comment by blowery** [comment]
docker run worked for me as well! ship it.

**Comment by samouri** [comment]
i just retested in docker after the shrinkwrap update and LGTM

**Pull request merged**
