### PR TITLE
Extensions: WPSC - Fix for directly cached files not saving

### PR DESCRIPTION
**Pull request by donnapep**
This PR fixes an issue with _Directly Cached Files_ not saving on the _Advanced_ tab.

## Testing

- Test that a new direct page is added to the _Existing Direct Pages_ section when a value is entered into the (first) empty tex tbox. This should work after pressing the Enter key or by clicking the _Save Settings_ button.
- Test that an existing direct page can be removed by clearing the value in the corresponding text box.

### CODE REVIEW

**Comment by donnapep** [comment]
@ockham This was a difficult one to figure out. If ever there was a case against using an HOC, this is it!

**Comment by ockham** [comment]
Removing entries by making text fields blank is kinda weird, UX-wise (even more so given that a user could also try and edit the contents). What about turning that into a read-only list with delete buttons next to them? (I can file a separate PR for that.)

**Comment by donnapep** [comment]
@ockham Yup, it is weird. I'd be down with your suggestion.

**Comment by ockham** [comment]
Tracking a bug I found:

1. Add `/about/`
2. Add `/jobs/`
3. Delete `/about/`
4. Add `/about/`

`/about/` isn't created -- need to reload page.

**Comment by ockham** [comment]
Found a more general scenario: 

1. Delete an existing directly cached page
2. Add a new one -- it doesn't show up.

**Comment by ockham** [comment]
I tried to diagnose this some more, even tho I'm still not perfectly familiar with `wrap-settings-form`. What seems to be going on is that `cache_direct_pages` fields are kept in 'dirty' state even after saving. I'm not yet entirely sure why, but all the more inclined to work on an alternative PR using buttons instead of input fields, which seem to be better both from a UX and code POV.

**Pull request closed without merging**
