### PR TITLE
Plans overhaul: Add Google Analytics for Starter

### PR DESCRIPTION
**Pull request by chriskmnds**
#### Changes proposed in this Pull Request

1. Adds the Google Analytics feature to the plans grid
2. Adds the Google Analytics feature block to `plans/my-plan`
3. Adds the Google Analytics feature block to the checkout thank-you page

(this will also be included in the about-to-be-obsolete "free vs pro" grid, but I guess that's fine - it will just be marked with "not included")

#### Media

`start/plans`

Screenshot 2022-05-18 at 4 37 24 PM

`plans/my-plan`

Screenshot 2022-05-18 at 4 37 55 PM

#### Testing instructions

* Go to `/start/plans` and select "show full plan comparison"
    * confirm feature is included in list as in media above
* Go to `/plans/[SITE_ON_FREE_OR_STARTER]` and select "show full plan comparison"
    * confirm feature is included in list as in media above
* Go to `/plans/my-plan/[SITE_ON_STARTER]` and confirm a GA block is there
    * Click on it and confirm the form that opens is working as expected (the backend parts should be in place)
* Go to `/start/plans` and purchase a Starter plan. Complete the checkout
    * Confirm the "thank you" page includes a block with GA info (same as with Pro)
* Disable the flag (e.g. `/start/plans?flags=-plans/starter-plan`) and ensure nothing breaks. 
    * The GA feature should still be in the list, and marked as "not included" for the free plan. (assuming this is ok)

#### TODO

- [ ] Let's reorder the features list and make any other contextual updates to the list in this PR. Not sure if the final order has been settled yet. See Slack thread: p1652878563789739/1652865158.458459-slack-C031TFM2NKC
- [ ] Let's update the subtitle of the Starter plan also once it's finalized/settled. Same Slack thread: p1652878563789739/1652865158.458459-slack-C031TFM2NKC

Related to Automattic/martech#741
Fixes Automattic/martech#741

### CODE REVIEW

**Comment by chriskmnds** [comment]
@claudiucelfilip @southp I'm guessing we'll do the recording and the Starter subtitle update in this PR (added to the TODO list).

**Review by claudiucelfilip — APPROVED** [review]
Works as described.
LGTM🚀

**Comment by southp** [comment]
@claudiucelfilip the required change is now consolidated in https://github.com/Automattic/martech/issues/747. Please incorporate the proposed change into this PR 🙇🏼

**Comment by southp** [comment]
The remaining updates are now consolidated in 747-gh-Automattic/martech. Please incorporate them into this PR 🙇🏼

**Comment by claudiucelfilip** [comment]
> The remaining updates are now consolidated in 747-gh-Automattic/martech. Please incorporate them into this PR 🙇🏼

@southp The changes are pushed to this PR.

Screenshot on 2022-05-19 at 11-40-15

**Review by southp — APPROVED** [review]
I've confirmed that the new order and the new plan description are implemented as expected. LGTM 🚢

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/7320581

Thank you @chriskmnds for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/7320581).

**Pull request merged**
