### PR TITLE
Reader: improve performance of conversations

### PR DESCRIPTION
**Pull request by samouri**
**summary**
Conversations are dependent upon a single posts's comments and not the entire collection of comments. Therefore the current `createSelector` approach is less effective than it could be. This PR improves the performance by utilizing  [treeSelector](https://github.com/Automattic/wp-calypso/pull/20547).

I tested for fewer re-renders by using this unmerged  [performance](https://github.com/Automattic/wp-calypso/pull/21081) tool.

below is the result of loading conversations and clicking "more comments" a couple times.

**before**
screen shot 2018-01-11 at 4 00 02 pm

**after**
screen shot 2018-01-11 at 4 43 25 pm

---
**summary of results**
By using `treeSelect` instead of `createSelector` I was able to get the wasted render count down from ~351 to 8.   These numbers were just after a few second after loading -- I'm sure it would get wayy more drastic if i used conversations for much longer.

### CODE REVIEW

**Comment by bluefuton** [comment]
Nice one @samouri!

I'm seeing some failing tests for the `getParentComment` selector:

`TypeError: Invalid value used as weak map key`

**Comment by samouri** [comment]
The failing test raises an interesting question: what should treeSelect do when dependencies are undefined?

**Comment by samouri** [comment]
dserve link: https://dserve.a8c.com/?branch=update/conversations-perf

**Comment by samouri** [comment]
blocked on merge of: https://github.com/Automattic/wp-calypso/pull/21625

**Comment by blowery** [comment]
@samouri i'd love to land this. Could you take a look at the failed tests?

**Comment by samouri** [comment]
Failed test should be fixed by #21625 which landed yesterday!

**Pull request merged**
