### PR TITLE
Fix cart items lint errors take 2

### PR DESCRIPTION
**Pull request by deBhal**
I reverted #14947 after a false alarm, so this PR is just applying those changes, which got the thumbs up in that PR.

(It's not related to this PR, but for completeness, the false alarm was the `upgrades/domain-search` feature missing on horizon, which leads to the entire domain search page not rendering at all if you go to My Sites->Domains->Add (no primary or secondary bar, which usually means a JS crash pretty early in the render).

### CODE REVIEW

**Comment by apeatling** [comment]
@yoavf, @deBhal I would really love to see you both get better at reviewing each other's PRs. There seems to be a lot of PRs just gathering dust because it's not happening in a timely fashion.

**Comment by klimeryk** [comment]
I wonder if this is not obsolete now, we've run quite a few codemods in the meantime, and https://github.com/Automattic/wp-calypso/pull/18838 should fix the exports too.

**Comment by apeatling** [comment]
Okay, let's close, we can reopen if it becomes relevant in the future.

**Comment by deBhal** [comment]
Yeah, the code mods and prettify overlap almost all of it, so closing is definitely the way to go.

I'll have a talk to @yoavf and see if we can come up with something to prevent letting things drag.

**Pull request closed without merging**
