### PR TITLE
Signup: Add squares to background

### PR DESCRIPTION
**Pull request by sixhours**
#### Changes proposed in this Pull Request

* Alternate title: Just the squares, m'am
* Trying another approach (similar to #27938) in just adding the background decoration to signup for a bit of visual interest.

Before:

screen shot 2018-10-24 at 12 21 06 pm

After: 

screen shot 2018-10-24 at 12 19 44 pm

#### Testing instructions

* Switch to this PR, navigate to `/start`
* Check out the fancy squares!

### CODE REVIEW

**Comment by fditrapani** [comment]
Nice small PR — I love these! Only thing I noticed was on mobile, the steps appear under the squares:

screen shot 2018-10-24 at 12 55 05 pm

**Comment by sixhours** [comment]
I ran into some weirdness with the `z-index` function not being available from the main signup stylesheet file, so I imported it manually. I tried to trace the imports back through our shared CSS files but got lost. I'm not sure what's up with that. Let me know if there's a better method for getting access to that function.

**Comment by fditrapani** [comment]
That seemed to do the job for me. There are definitely some weird z-index things happening all round in Calypso.

**Comment by sixhours** [comment]
[Add new layout to signup flow](https://trello.com/c/4sP7mBr4/127-add-new-layout-to-signup-flow)

**Comment by ramonjd** [comment]
Also LGTM.

`signup.css` is bundled as a separate section. It might be better (organizationally-speaking) to add the `z-index` function here:
 https://github.com/Automattic/wp-calypso/blob/40f9d93/assets/stylesheets/sections/signup.scss

That is, 

```
...
@import '../shared/typography';
@import '../shared/functions/z-index';
...
```

**Pull request merged**
