### PR TITLE
Revert "Remove site icon when 'icon' prop is not present in new attributes coming from API"

### PR DESCRIPTION
**Pull request by lamosty**
Reverts Automattic/wp-calypso#5628

We need to test if this PR causes #5963.

Please checkout this branch and test locally.

Test live: https://calypso.live/?branch=revert-5628-fix/remove-site-icon-from-site-attrs

### CODE REVIEW

**Comment by ehg** [comment]
:+1:

**Comment by aduth** [comment]
This pull request is causing sites-list computed attributes to be stored in Redux state, which were intended to be removed by #4060. `slug`, `is_previewable`, and `is_customizable` are not attributes on the [raw site response object](https://developer.wordpress.com/docs/api/1.2/get/sites/%24site/), but rather added by the `lib/site/index.js` module:

- https://github.com/Automattic/wp-calypso/blob/181c45f/client/lib/site/index.js#L98
- https://github.com/Automattic/wp-calypso/blob/181c45f/client/lib/site/index.js#L119-L124
- https://github.com/Automattic/wp-calypso/blob/181c45f/client/lib/site/index.js#L125-L128

The site module is legacy, and keeping the attributes deepens our ties with it. In fact, I only came across this pull request as another was trying to use `slug` from a Redux site object.

We should remove these properties from state and find all occurrences where any of these computed attributes are used, encouraging them to use state selectors instead (e.g. [`getSiteSlug`](https://github.com/Automattic/wp-calypso/blob/181c45f8feeeaabefdf24b56d637d8252dfd9ca6/client/state/sites/selectors.js#L79-L97)).

cc @mtias @gwwar

**Comment by aduth** [comment]
Sorry, I think I may be misappropriating blame here.

Looks like `slug`, `is_previewable`, and `is_customizable` were originally added to the sites schema in #4747, #5625, and #5665 respectively (cc @artpi @ehg @lsinger ). See my comment above for why we shouldn't be adding computed properties to our state schema. Implement selectors instead if we need the equivalent logic ported from `lib/site`.

We should probably then add a comment to discourage people from tampering with the sites schema.

**Comment by mtias** [comment]
Curious when `is_previewable` would be false as well, doesn't seem like an attribute to me at all.

**Comment by lamosty** [comment]
@aduth Thanks for the heads-up. However, I did **not** add these attributes. I just reverted a PR of mine which broke site previews as I **removed** the `is_previewable` attr from site schema in it.

**Comment by aduth** [comment]
Right, clarified in https://github.com/Automattic/wp-calypso/pull/5966#issuecomment-229644199.

**Comment by ehg** [comment]
> is_previewable, and is_customizable were originally added to the sites schema

Yep. We did this as we thought it'd be the cleanest way to have those attributes available both in the Redux state, and in `sites-list`. I guess we could duplicate the logic into selectors. Or try getting the my-sites sidebar connected via Redux :)

> Curious when is_previewable would be false as well, doesn't seem like an attribute to me at all.

When a site URL isn't https, is VIP etc.

**Comment by ehg** [comment]
> is_previewable, and is_customizable were originally added to the sites schema

Yep. We did this as we thought it'd be the cleanest way to have those attributes available both in the Redux state, and in `sites-list`. I guess we could duplicate the logic into selectors. Or try getting the my-sites sidebar connected via Redux :)

> Curious when is_previewable would be false as well, doesn't seem like an attribute to me at all.

When a site URL isn't https, is VIP etc.

**Comment by ehg** [comment]
> Or try getting the my-sites sidebar connected via Redux :)

Tried this here: https://github.com/Automattic/wp-calypso/commit/5f8ee1ee6d328b09e5b0664bc3a603ccfcae2442 — then had a chat with @mtias — who mentioned computed attrs polutting the state was the main problem. So we came up with a plan for that, and I should have a PR up soonish.

**Comment by ehg** [comment]
> I should have a PR up soonish.

https://github.com/Automattic/wp-calypso/pull/6477

**Pull request merged**
