### PR TITLE
Comments: Prettier on My Sites / Comments

### PR DESCRIPTION
**Pull request by Copons**
Applied Prettier on `my-sites/comments`.

### Test

Check that the new Comment Management section is not broken.

### CODE REVIEW

**Comment by gwwar** [comment]
What's adding the format block?

**Comment by dmsnell** [comment]
> What's adding the format block?

@gwwar that's something @samouri put in to keep prettified files prettified

**Comment by Copons** [comment]
@gwwar We run Prettier on commit on all files marked with `/** @format */`.
Though, there are some conflicting rules between Prettier and our Eslint, and I had to manually un-Prettify a bunch of changes to make the files compliant with Eslint.
But, if I keep the format block in, those files get re-Prettified on commit, breaking Eslint on CI tests.

**Comment by samouri** [comment]
> there are some conflicting rules between Prettier and our Eslint

This is something that @jsnajdr and @nosolosw are actively working on addressing: https://github.com/Automattic/eslines/pull/6

**Comment by Copons** [comment]
@samouri cool! Then I'll wait for that to ship and rebase/re-prettify this later. :)

**Comment by Copons** [comment]
Closing for now: we're already working on Comment Management m2, and I'd rather wait for the Prettier/eslint conflicts to be fixed instead of pushing an incomplete PR.
I'll update later on. Thanks you all!

**Pull request closed without merging**
