### PR TITLE
Media library: add a token failure error state

### PR DESCRIPTION
**Pull request by johngodley**
As part of an upcoming Picasa => Google Photos migration, introduce an additional error state to the media library.

The `keyring_token_error` will indicate that an authentication error occurred when using an external service. We detect this when a media operation has been performed, and convert it to `SERVICE_AUTH_FAILED`. This can then be used elsewhere for additional migration logic.

Note there are a bunch of linting changes in this PR because it's forcing me to make them

#### Testing instructions

The change is fairly small and adds an extra case to a switch. The existing unit tests + new test should cover the change.

No visible changes should be seen.

### CODE REVIEW

**Comment by georgeh** [comment]
LGTM, any way for me to test with the server-side changes?

**Comment by johngodley** [comment]
And to see the error:
- Ensure connected to Google Photos from the Sharing page (in sidebar)
- Go to the Media page (in sidebar)
- Click the dropdown in top left of the media library, pick Google Photos

**Comment by johngodley** [comment]
Actually, you'll see the generic error regardless of this PR. There's no easy way of visually testing this right now. The follow-up PR to this (#29937) adds a specific message, and is visually testable. My plan was to get this change in, rebase #29937 (which contains this PR), and then get the error message in. However you could just go for #29937 and do them both at the same time.

https://github.com/Automattic/wp-calypso/pull/

**Comment by georgeh** [comment]
I made the changes per Slack. I confirmed that I got `keyring_token_error` in the JSON xhr request and it showed the original error message. I also merged `add/picasa-migration-media-notice` from #29937 into this branch and saw the new error message. 

:shipit:

**Pull request merged**
