### PR TITLE
GuidedTours: Enable on staging

### PR DESCRIPTION
**Pull request by ehg**
Merge when comfortable.

### CODE REVIEW

**Comment by lsinger** [comment]
Let's also give the `main` tour a versioned name like `main_20160421`? In `client/state/ui/actions.js` and `client/state/ui/test/selectors.js`.

**Comment by ehg** [comment]
> Let's also give the main tour a versioned name like main_20160421?

Not in this PR, maybe this one: #4932

**Comment by lsinger** [comment]
Yup, makes sense! 👍

**Comment by mcsf** [comment]
\o/

**Pull request merged**
