### PR TITLE
Avoid className collisions in sidebar of My Sites

### PR DESCRIPTION
**Pull request by marekhrabe**
Reported in #13395

I'm not sure about implications when we remove the className, but I haven't found any CSS rule targeting those classes. They also don't follow our class guidelines and can easily collide with other generic (and unrelated) CSS classes like `.design`. We should be fine with them gone for now and we can easily bring them back later in some prefixed form, once we have a use for them.

### To test:
 
1. Have a site with custom post types
2. Visit My Sites
3. Sidebar should have no glitches like in the original issue
4. Make sure when you click the post type, it is highlighted as active

| Before | After |
| --- | --- |
| screen shot 2017-05-08 at 16 21 12 | screen shot 2017-05-08 at 16 22 23 |

### CODE REVIEW

**Comment by folletto** [comment]
Nice take on the problem. I did a cursory test in the My Sites sidebar in Chrome and all seems working but...

---

This odd thing when I click Sharing (the screen blanks):

screen shot 2017-05-08 at 21 31 12

It happened to me when I first clicked through the whole sidebar (from top to bottom, clicking each time), but I seem to be able to reproduce by clicking around a whole lot of times across different items in the sidebar. 

It also happens in production, so it's not a regression. Might be wort its own issue if anyone can reproduce.

**Comment by marekhrabe** [comment]
@aduth Good point, all gone now :)

**Comment by folletto** [comment]
Tested again on Chrome, for both My Sites (all links, CPTs included) and just to play it safe Reader and Me too. Everything seems working well.

---

Tiny detail: oddly there's still a lingering `class` empty attibute. I'm not sure, can we remove it?

screen shot 2017-05-09 at 11 18 47

**Comment by mtias** [comment]
Looks good to me.

**Comment by marekhrabe** [comment]
@folletto: We still use the `class` attribute for cases when the item is active (selected in the sidebar). I think it's no problem at all to keep it like that.

**Comment by folletto** [comment]
Ok, thanks for the clarification! I was curious why it was still rendering empty ones :)

**Pull request merged**
