### PR TITLE
Bring back the "W"

### PR DESCRIPTION
**Pull request by fditrapani**
As per p9GxdL-4x-P2 we're brining back the "W" icon to the WordPress word mark. This PR makes the necessary updates. 

## Before
image

image

## After
image

image

## Testing
- Visit `/start` or `/themes` in an incognito browser to see the new logo for tablet and desktop views.

cc @jancavan @danhauk @ashleighaxios @sixhours

### CODE REVIEW

**Comment by jancavan** [comment]
Looks good! I think we can still minify the svg?

**Comment by fditrapani** [comment]
This was minified and then copied and pasted into a component. I went with the component route to prevent the file from flashing to existence (I have noticed that when using CSS to include SVGs).

**Comment by jaswrks** [comment]
Ditto. LGTM too!

**Comment by ockham** [comment]
> This was minified and then copied and pasted into a component. I went with the component route to prevent the file from flashing to existence (I have noticed that when using CSS to include SVGs).

Hmm, we already have a [`WordPressLogo` component](https://github.com/Automattic/wp-calypso/tree/master/client/components/wordpress-logo) that does pretty much that -- would you consider using that instead so we don't duplicate inlined SVG? :sweat_smile:

**Comment by fditrapani** [comment]
@ockham the component you're referring to only has the W icon and not the word mark like the one I updated.

**Comment by ockham** [comment]
> @ockham the component you're referring to only has the W icon and not the word mark like the one I updated.

Well can we use composition to... compose logo plus word mark? :smile:

**Comment by fditrapani** [comment]
> Well can we use composition to... compose logo plus word mark?

It's a bit more work but we could consolidate the logos into one component and use CSS to do some cropping magic.

**Pull request merged**
