### PR TITLE
Fix redirect to WooCommerce home WooCommerce related plans

### PR DESCRIPTION
**Pull request by ilyasfoo**
Related to https://github.com/Automattic/wc-calypso-bridge/issues/1214

## Proposed Changes

* Adds `isSiteOnWooExpressEcommerceTrial` plan selector to detect Woo Express, Ecommerce, free trial plans
* Fix redirect to WooCommerce home for all mentioned plans

### Positive test

1. Using a site with a free trial plan, go to `https://calypso.localhost:3000/home/site_url`
2. Observe that you're redirected to WooCommerce homescreen
3. Repeat the test using a site with Woo Express medium or small plan, and Ecommerce plan

### Negative test

1. Using a site without Woo Express or Ecommerce plan, go to `https://calypso.localhost:3000/home/site_url`
2. Observe that you're not redirected to anywhere else

### Test with SSO disabled

- Navigate to **Settings > Security** and disable the "_Allow users to log in to this site using WordPress.com accounts_" option.
- Navigate to the site's home (`wordpress.com/home/[site_suffix]`) that has SSO disabled.
- Notice that you get redirected to WooCommerce Home (or the wp-admin login page, depending on the login cookie).
- Apply this PR.
- Navigate to home again and ensure that the redirection is removed; therefore, you should see the Calypso home.

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

**Review by chihsuan — APPROVED** [review]
Thanks for the fix. LGTM and tested well! 👍

**Comment by PanosSynetos** [comment]
Thanks @ilyasfoo for the fix and the swift response - I'd love to manually test this too, along with @xristos3490 before it gets merged :) We'll run through the tests today and let you know.

**Comment by xristos3490** [comment]
Thank you so much for tackling this, @ilyasfoo! Looks great and tested well! 

I wanted to bring to your attention that there is some pending work related to the redirection and Jetpack's SSO. 
The issue is that when the SSO is off, this entire process is obsolete, and the admin menu is a "normal" self-hosted-like menu.

Perhaps we can address both of these issues at the same time. If we can land on proper handling of the SSO here, then SWW can work on The Bridge side on https://github.com/Automattic/wc-calypso-bridge/pull/925

Here's the related PR of mine that it's blocked because I couldn't bypass the flash of content: https://github.com/Automattic/wp-calypso/pull/72698 

Let me know what you think! 

By the way, I'm not sure how the launchpad fits into the scenario, specifically the URL redirect on new sites with the format `setup/build/launchpad?siteSlug=xxx`. It might be worth collaborating with the team responsible for this and determining whether we should prioritize the launchpad redirection over this one. However, this could be a separate matter altogether.

**Comment by ilyasfoo** [comment]
>Here's the related PR of mine that it's blocked because I couldn't bypass the flash of content: https://github.com/Automattic/wp-calypso/pull/72698
> Let me know what you think!

@xristos3490  Gotcha, thanks for highlighting this use case! I've shamelessly copied your work and moved the fetching to happen earlier in 5483a6e. I think that resolved the flashing of content.

> By the way, I'm not sure how the launchpad fits into the scenario, specifically the URL redirect on new sites with the format setup/build/launchpad?siteSlug=xxx. It might be worth collaborating with the team responsible for this and determining whether we should prioritize the launchpad redirection over this one. However, this could be a separate matter altogether.

I'm also unsure of how launchpad fits into our scenario here. I think it's better to handle it separately.

**Review by xristos3490 — APPROVED** [review]
I did another round of testing on a wpcom ecommerce site to perform a negative test without using SSO. This was because Woo Express sites did not redirect before, regardless of the SSO state. Either way, this works on all ecom and woox sites.

This looks and works great! Also, amazing work on reducing the flash of content! 🙇

**Review by JessBoctor — APPROVED** [review]
I did a functional review and the redirect works as described. 

screencapture-woo-quickly-inner-kryptonite-wpcomstaging-wp-admin-admin-php-2023-07-11-13_53_39

LGTM 👍

**Pull request merged**
