### PR TITLE
ci: Add build step to forbid duplicated packages

### PR DESCRIPTION
**Pull request by scinos**
#### Changes proposed in this Pull Request

Adds a build step to check there are no duplicated packages

#### Testing instructions

Fork this branch, introduce a duplication in `yarn.lock`. The fastest way is to revert #c32e02f (run `git revert c32e02f`). Commit and push the changes, and verify TeamCity fails in your forked branch with:

image

### CODE REVIEW

**Comment by tyxla** [comment]
Canaries are failing, could it be related somehow?

**Comment by scinos** [comment]
> Canaries are failing, could it be related somehow?

I don't think so. The screenshots show a 500 error from `calypso.live`, I'll investigate.

Edit: looks like it was a temporary problem in `calypso.live`, as a few branches failed because the error 500. Seems to be fine now.

**Review by noahtallen — APPROVED** [review]
LGTM 🚀

**Review by fullofcaffeine — APPROVED** [review]
This tests well!

**Pull request merged**
