### PR TITLE
Analytics: removes set anonymous user id

### PR DESCRIPTION
**Pull request by rodrigoi**
~~Depends on #23911~~

This PR removes the no longer used middleware to handle the `ANALYTICS_TRACKS_ANONID_SET` action, along with its action creator.

### CODE REVIEW

**Comment by kwight** [comment]
To test this, I checked out #23911 and then cherry-picked these two commits. I ran into a problem with `setAnonymousUserId` still being defined in the `/client/state/analytics/middleware.js` (it triggered a `no-unused-vars` linting problem), but it's not present in this PR, so it may be getting dealt with somewhere else? Other than that, I went through and followed the same path you probably did, and everything looks great 👍

**Comment by Copons** [comment]
This indeed wasn't used anywhere because, if I'm correct, we moved the anonymous user tracking from `window._tkq` to `cookies.tk_ai`.

After a smoke test nothing seems broken, and can't find any occurrences of the removed stuff left over anywhere in the code.

I'd say 🚢

**Comment by kwight** [comment]
Took another spin through for funsies, I think we're good to go 👍

**Comment by gwwar** [comment]
Did y'all verify we didn't need this? The original flow is for Jetpack connect and is something not usually smoke tested https://github.com/Automattic/wp-calypso/pull/17591

cc @bperson @gravityrail

**Comment by rodrigoi** [comment]
@gwwar I did double and triple check that neither `analytics.tracks. setAnonymousUserId` nor `setTracksAnonymousUserId` are used anywhere in Calypso. Or that `ANALYTICS_TRACKS_ANONID_SET` has a rogue dispatch somewhere that skips the action creator.

All the anonymous functionality relies on `analytics.tracks.anonymousUserId`, and in the case of Jetpack Connect, the files that used `setTracksAnonymousUserId` no longer exist.

I've been keeping an eye out for error on the Calypso JS error log, and everything look OK so far 🙂 .

**Pull request merged**
