### PR TITLE
Enable Plugins Details page SSR

### PR DESCRIPTION
**Pull request by claudiucelfilip**
#### Proposed Changes

Similar to #69366 and #70064, this allows logged-out Plugins Details pages to be Server Side Rendered on production

#### Testing Instructions

* Log out and disable JS
* Go to a category page, ex: `/plugins/wordpress-seo-premium`, `/plugins/elementor`
* Make sure the Plugins Details content is rendered

* Log in and double-check for regressions in the Plugins section

#### Pre-merge Checklist

- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

Related to #

### CODE REVIEW

**Review by tyxla — COMMENTED** [review]
On production, when I land on the plugin details page, without a site, as a logged in user, it will start updating that plugin on all sites I have it installed and it's outdated. I didn't see that with this branch - is that expected? 

Also, same as https://github.com/Automattic/wp-calypso/pull/70064, I'm curious about why the breadcrumbs don't render on SSR.

Other than that, this tested as expected 👍

**Comment by claudiucelfilip** [comment]
> On production, when I land on the plugin details page, without a site, as a logged in user, it will start updating that plugin on all sites I have it installed and it's outdated. I didn't see that with this branch - is that expected?

Interesting, I haven't tried this and I'm not sure how I can test it out now.
On the other hand, SSR shouldn't be enabled for logged-~~out~~-in users, yet it is running here because of the user bootstrapping is not working properly in this environment: so I don't see how this would be affected.

> Also, same as #70064, I'm curious about why the breadcrumbs don't render on SSR.

The breadcrumbs are defined within a `useEffect` hook which never gets the chance to get called on SSR. A workaround has been proposed in #69785 by ensuring the code gets called on the server (through a custom [useServerEffect](https://github.com/Automattic/wp-calypso/blob/trunk/client/my-sites/plugins/utils.js#L153) hook).
There's still a problem with this solution as the breadcrumbs don't get translated: will need to figure out why or a different solution.

**Comment by noahtallen** [comment]
>  On the other hand, SSR shouldn't be enabled for logged-out users, yet it is running here because of the user bootstrapping is not working properly in this environment: so I don't see how this would be affected.

This is a great point. (Also, I think there was a typo here: SSR is _only_ enabled for logged-out users.) But yeah, you would need to enable wpcom user bootstrapping in calypso.localhost to really test logged-in behavior. (Though I also think user bootstrapping works correctly in calypso.live) More on that here: PCYsg-5YE-p2

**Comment by tyxla** [comment]
FWIW I'm happy to pass on the breadcrumbs for the first version and implement them later. 

> On the other hand, SSR shouldn't be enabled for logged-in users, yet it is running here because of the user bootstrapping is not working properly in this environment: so I don't see how this would be affected.

I haven't investigated but it might be caused by a seemingly unrelated change. For the protocol, the scenario I'm describing doesn't have to do anything with SSR since in both environments I was testing as a logged-in user.

**Comment by noahtallen** [comment]
> For the protocol, the scenario I'm describing doesn't have to do anything with SSR since in both environments I was testing as a logged-in user.

This actually does unfortunately have an impact. The Calypso server sees _every_ request as a "logged out" request in development mode, because it can't authenticate you to wordpress.com. So if you visit `/themes`, the SSR pipeline _does_ run, even if you are logged in. But once it gets to the client, the normal logged-in client-side themes behavior starts working.

It's a very weird situation and only applies in development mode. So you can only _really_ test logged-in behavior on these routes with the wpcom user bootstrapping set up

**Comment by tyxla** [comment]
It's funny though because I didn't test in `development` - I tested in `wpcalypso` and `staging`.

**Comment by noahtallen** [comment]
in that case, this isn't the problem 😅

**Comment by tyxla** [comment]
Just gave this another round of testing, and there seems to be a regression for the logged-in users. For a brief moment, the logged-out masterbar is being displayed, before the logged-in one is shown:

https://user-images.githubusercontent.com/8436925/204249315-c08291fe-f5a0-4bb5-8230-dc01e3288f59.mov

This doesn't occur when testing on `staging`/`production`.

**Comment by claudiucelfilip** [comment]
> Just gave this another round of testing, and there seems to be a regression for the logged-in users. For a brief moment, the logged-out masterbar is being displayed, before the logged-in one is shown:

Thanks for retesting!
I think this is expected and it's caused by the incorrect user boostrapping on the server.
The masterbar is shown for logged-out users, therefore, the server sees you're logged-out and renders the blue masterbar, but the client replaces it with the correct logged-in version. 
This behavior should be noticeable on `trunk` as well.

**Comment by tyxla** [comment]
> incorrect user boostrapping on the server

Could you elaborate on what that means? Do you mean that it's because user bootstrapping works only on staging/production?

I've double-checked and that makes sense.

Not my intention to block this PR, but in a separate PR, could we try finding a way around this?

**Review by tyxla — APPROVED** [review]
Let's 🚀

**Comment by claudiucelfilip** [comment]
>> incorrect user boostrapping on the server

> Could you elaborate on what that means? Do you mean that it's because user bootstrapping works only on staging/production?

Yes, the development server is unable to bootstrap the user. As @noahtallen pointed out earlier, you need to set up your dev environment as described PCYsg-5YE-p2 to get it working properly.

**Pull request merged**
