### PR TITLE
Device Switcher: Adjust spacing to align with Figma

### PR DESCRIPTION
**Pull request by arthur791004**
#### Proposed Changes

* Adjust the spacing between devices and the frame to align with 7l53h5fxAUNjVRBQ82YFwn-fi-1603%3A58763

| Before | After |
| - | - |
| image | image |

#### Testing Instructions

* Go to /setup?siteSlug=<your_site>
* Click the "Continue" button until you land on the Design Picker step
* Preview any design with style variation or select Blank Canvas CTA
* When you're previewing the design, verify the spacing is correct.

#### Pre-merge Checklist

- [x] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [x] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [x] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [x] Have you checked for TypeScript, React or other console errors?
- [x] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [x] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [x] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

Related to #

### CODE REVIEW

**Comment by taipeicoder** [comment]
Could you check again the spec's link? It didn't get converted for me 🥲

**Review by bangank36 — APPROVED** [review]
LGTM

**Comment by bangank36** [comment]
> Could you check again the spec's link? It didn't get converted for me 🥲

It is text without link for me too

**Comment by arthur791004** [comment]
How about 0EogtxvlmxMGcnEEaMVECv-fi-2010%3A64893&t=l3ylXoSZRGJpVbN1-0? Recently, I found the encoded Figma link cannot get converted...

**Comment by taipeicoder** [comment]
> How about 0EogtxvlmxMGcnEEaMVECv-fi-2010%3A64893&t=l3ylXoSZRGJpVbN1-0? Recently, I found the encoded Figma link cannot get converted...

~~No...  0EogtxvlmxMGcnEEaMVECv-fi-2010%3A64893 works though.~~ Nvm, it only works in the preview.

**Comment by arthur791004** [comment]
hmmm...looks like `&t=xxx` make it unable to be converted

**Review by taipeicoder — APPROVED** [review]
👍

**Pull request merged**
