### PR TITLE
ActivityLog: Add support for posts nested filters

### PR DESCRIPTION
**Pull request by Initsogar**
Resolves https://github.com/Automattic/jetpack-backup-team/issues/216

⚠️ This PR depends on D127934-code being applied in your WPCOM sandbox. That PR enables the nested filter support in WPCOM API.

## Proposed Changes

* Add support for Activity Type nested filters UI
  * When selecting a parent filter, it should autoselect all children filters.
  * When unselecting a parent filter, it should autoselect all children filters.
  * ìndeterminate` status for parent filter checkboxes is not yet implemented. It will be addressed in another PR as it requires refactoring to use [CheckboxControl](https://wordpress.github.io/gutenberg/?path=/docs/components-checkboxcontrol--docs) instead of FormCheckbox.

| Before | After |
|---|---|
| CleanShot 2023-11-08 at 18 06 58@2x | CleanShot 2023-11-08 at 18 08 00@2x |

### Demo
CleanShot 2023-11-08 at 18 09 26

## Testing Instructions
* Apply D127934-code in your sandbox.
* Spin up a Calypso and Jetpack Cloud live branch
* Navigate to the Activity Log with a site that has recent posts published, updated, deleted and/or trashed.
* On the `Activity Type` filter, ensure that you see `Posts and Pages` and indented, another filters like `Published`, `Trashed`, `Deleted` and/or `Updated`.
* Play around with the filters and ensure it filters the results as expected.
* Ensure clicking on `Posts and Pages` check (or uncheck) all children filters.

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

**Comment by jwebbdev** [comment]
I think this is all good.  It does highlight a couple existing UI issues though.

https://github.com/Automattic/wp-calypso/assets/1992658/d91986f1-37ff-4109-be6d-fd944f383230

I think @keoshi has mentioned similar, and we fixed some of it when we have more than one type selected but it seems we probably need a better solution here.  I think if we can work out a design solution we can fix this in another PR because it is pre-existing in both cases (moving around while selecting and breaking out on long strings).

Screenshot 2023-11-15 at 8 50 46 AM

**Review by jwebbdev — APPROVED** [review]

**Comment by Initsogar** [comment]
> I think this is all good. It does highlight a couple existing UI issues though.
> 
>  Screen.Recording.2023-11-15.at.8.48.58.AM.mov 
> I think @keoshi has mentioned similar, and we fixed some of it when we have more than one type selected but it seems we probably need a better solution here. I think if we can work out a design solution we can fix this in another PR because it is pre-existing in both cases (moving around while selecting and breaking out on long strings).
> 
> Screenshot 2023-11-15 at 8 50 46 AM

Thanks for the feedback! Indeed we have some spacing issues on Jetpack Cloud given the main content has a max of 660px width. I'm looking forward on reduce these kind of issues by implementing the new redesign of the filterbar as part of https://github.com/Automattic/jetpack-backup-team/issues/217.

CleanShot 2023-11-15 at 09 08 06@2x

The new design includes removing `Filter by` and also the `X` at the end that clears all filters and the components will look more _compact_.

**Comment by Initsogar** [comment]
> I think if we can work out a design solution we can fix this in another PR because it is pre-existing in both cases (moving around while selecting and breaking out on long strings).

Regarding this, I would suggest to also display the number of activities selected when only 1 is selected instead of the name of the activity selected. @keoshi what do you think?

Related to: https://github.com/Automattic/wp-calypso/pull/83786

**Comment by keoshi** [comment]
> display the number of activities selected when only 1 is selected instead of the name of the activity selected

Just to be clear, this would change the behavior we defined in https://github.com/Automattic/wp-calypso/pull/83786, correct? To me the solution we reached in that PR seems better than to immediately show a count. We could even apply a `max-width` and trim the activity name with `...` if needed.

If we're struggling with space, there seem to be a few solutions we could exhaust before using a count.

**Pull request merged**
