### PR TITLE
Reader: sort 'Followed Sites' by latest update, not alphabetical

### PR DESCRIPTION
**Pull request by mreishus**
* Requires a wpcom patch: D67552-code to provide information from the backend

#### Changes proposed in this Pull Request

* Followed Sites in the reader are now sorted by last updated order

#### Testing instructions

* Apply D67552-code to sandbox
* Sandbox public-api
* Make sure you are following some wordpress.com blogs
* Make sure you are following some RSS feeds
  * Visit https://wordpress.com/following/manage
    * Add `http://wirecutter.com`
    * Add `http://www.loc.gov/rss/pao/news.xml`
    * Add `http://feeds.feedburner.com/euronews/en/home/`
* Visit http://calypso.localhost:3000/read
* Expand "followed sites" on the left hand sidebar
* They should be in most recently updated order, with the most recently updated sites on the top

Related to #43592

### CODE REVIEW

**Comment by mreishus** [comment]
@sixhours : Added a missing file which was causing this PR to crash if you tried it earlier.

**Comment by sixhours** [comment]
I still need to add localization to the timestamp but this is a visual:

**Before**

Screen Shot 2021-09-29 at 2 22 39 PM

**After**

Screen Shot 2021-09-29 at 2 21 51 PM


If this feels too crowded, I think we could do something like show a "Last updated: a day ago" on hover.

**Comment by mreishus** [comment]
The backend is currently providing `last_updated` dates for 10% of users and `last_updated: null` for everyone else; given how this currently works, it should be OK to deploy when we're ready even if the backend isn't fully released; the users receiving `last_updated: null` should continue to see the old behavior.

**Comment by mreishus** [comment]
We're now providing the `last_updated` date for all users

**Comment by obenland** [comment]
image

I love how we get translated "time since" strings for free as well

**Review by sixhours — APPROVED** [review]
This is working for me!

**Review by obenland — APPROVED** [review]
Looks good in my testing

**Comment by bluefuton** [comment]
The sorting by last updated date is a really nice improvement 👏 

> If this feels too crowded, I think we could do something like show a "Last updated: a day ago" on hover.

I do find that list is pretty difficult to scan and would prefer the suggestion of including the date in a tooltip. We could also surface in the header of a blog or feed stream (like https://wordpress.com/read/feeds/45690270) underneath the title and description perhaps?

> We're now providing the last_updated date for all users

Mine is missing dates (using the production API):

Screen Shot 2021-10-04 at 14 01 54

**Comment by mreishus** [comment]
> Mine is missing dates (using the production API):

Is it sorted in last updated date order but not displaying the dates?
If you visit https://developer.wordpress.com/docs/api/console/ and use [WP.COM API | v1.2 | GET] `/read/following/mine`, do the individual subscriptions returned have last_updated information in them?


Are there any javascript errors in the console on the page?
Are you using a non-English language? If so, does switching back to English make the dates display?
Which browser?

**Comment by mreishus** [comment]
We determined this was a color scheme issue.

https://user-images.githubusercontent.com/937354/135892539-79be8d48-cb1c-4b5f-9f6d-775417e96770.mp4

Today, if you select the "default" color scheme, your body tag gets the `is-classic-dark` class. But some accounts still have the `is-default` class, which has a differing definition of `--color-sidebar-text-rgb`, which blends into the sidebar.

**Comment by mreishus** [comment]
The color scheme issue has been fixed in #56761.

**Pull request merged**
