### PR TITLE
Jetpack: Change text and layout in my-plan's HE card for jetpack free…

### PR DESCRIPTION
**Pull request by johnHackworth**
fixes https://github.com/Automattic/wp-calypso/issues/21053

Right now, when a user on jetpack free plan sees their "my plan" page, we are telling them that they already have priority support, which is not true.

This PR changes the text and the layout of the support card in "my-plan":

image

how to test
========
0. You need a connected jetpack site with a free plan
1. Go to https://calypso.live/plans/my-plan?branch=fix/jetpack-free-documentation-card (or http://calypso.localhost:3000/plans/my-plan/) and select said site (If you get redirected directly to the plans page, click on "my plan" )
2. The support card should be shown like in the example image here
3. Test the same page with sites with paid plans (both jetpack and wp.com) and check it still shows the old card

### CODE REVIEW

**Comment by annezazu** [comment]
Do we want to fully remove access to support here? We do support free users but I defer to @beaulebens  about how he'd want to handle this. In my mind, we just don't want to advertise priority support to free folks.

**Comment by johnHackworth** [comment]
@annezazu Beau mentioned removing that button in the original issue. I don't really have a clear picture of what level of support we want to provide for free users here, but I'm happy to restore the button if we think it should still be there.

**Comment by johnHackworth** [comment]
Also, if that's the case and we end removing the button... maybe we should change the illustration, @rickybanister  ?

**Comment by nicoleckohler** [comment]
@annezazu I'm iffy on completely removing the option to contact us as well. I think it'd be best if searching the docs was the _first_ step (which is, IMO, what Beau was proposing)

However all our docs should have one or more "contact us" links on the page (on the sidebar, in the footer...) so that's another thing we may want to think about.

@AnnaMag your eye for consistency always brings me joy :D

**Comment by beaulebens** [comment]
Leaving the contact button there is fine, as long as we're not mentioning priority support in any way for these users. Agree that at the very least, it should not be the first option though.

**Comment by johnHackworth** [comment]
ok, I added some code to show the button again, but as the second option of that card:

image

**Comment by johnHackworth** [comment]
Since the requested changes have been done and everybody's fine with the rest of changes, I'm going to merge this PR

**Pull request merged**
