### PR TITLE
Bug: getSiteFragment checks second-to-last segment first

### PR DESCRIPTION
**Pull request by adamziel**
I would like to be able to link to a URL like `/domains/add/suggestion/mytestsite.com/mytestsite.wordpress.com` and see the domain suggestion page pre-populated with `mytestsite.com`. What happens now, is `getSiteFragment()` picks `mytestsite.com` as the actual site domain because it checks last two segments of the URL, but starts with **second to last** segment. This commit makes it look into the **last** segment first.

### CODE REVIEW

**Comment by jsnajdr** [comment]
Isn't such a patch going to break routes like `/comments/all/:site/:post`? The post ID could be incorrectly interpreted as site ID.

The domain suggestion problem could be solved by using URL in format `/domains/add/suggestion/mytestsite.wordpress.com?s=mytestsite.com`.

Yet another approach is used by the `my-sites/domains` controller: the second-last position is used for the "action slug":
```
/domains/manage/mytestsite.com/name-servers/mytestsite.wordpress.com
```
The analogous route for domain suggestions could be:
```
/domains/add/mytestsite.com/suggestion/mytestsite.wordpress.com
```

**Comment by Copons** [comment]
> Isn't such a patch going to break routes like `/comments/all/:site/:post`? The post ID could be incorrectly interpreted as site ID.

Thanks @jsnajdr I was going to point out exactly that. 🙇 

Though, I'm not sure which would be the best approach for site fragment checks, so I'll leave now with just the reminder to smoke test all Calypso when doing such changes. 🙂

**Comment by adamziel** [comment]
@jsnajdr @Copons Actually for urls like `/comment/all/:site/:post` the logic is different - there's another for loop in the same function looking for numeric segments - and it still starts at second-to-last segment. Here you will find a test case checking exactly this:

https://github.com/Automattic/wp-calypso/blob/master/client/lib/route/test/index.js#L102

There are also other test cases related ot extracting the site URL:

https://github.com/Automattic/wp-calypso/blob/master/client/lib/route/test/index.js#L136

All tests are passing, calypso seems fully functional on my end after this change - so I think we are on the safe side here. Also, I just added a test case to this PR to verify if the change works.

Of course - we can discard this PR and I can just make the URL different like suggested (`/domain/add/example.com/suggestion/mysite.wordpress.com`) and it will also work - but I think the current behaviour of `getSiteFragment()` in regard to site address is just confusing and this change could save other developers some confusion and head scratching.

**Comment by lamosty** [comment]
Haven't reviewed the PR but just wanted to say we should be very careful when changing how siteFragment is computed. It's affecting the whole app.

**Comment by ockham** [comment]
I thought it was a deliberate decision to check the second-to-last arg first. I'll try to find that PR...

**Comment by ockham** [comment]
Can't find any right now -- it might be mainly for the reasons that @jsnajdr and @Copons pointed out.

**Comment by adamziel** [comment]
@ockham fully agreed in regard to numerical IDs - that's a different code path than scanning for a domain name though. This PR doesn't break any existing test cases.

**Comment by ockham** [comment]
I tend to agree with Jarda tho that `/domains/add/suggestion/mytestsite.com/mytestsite.wordpress.com` isn't that obvious anyway in what it's doing -- his alternative suggestions seemed to make sense to me.

> I think the current behaviour of `getSiteFragment()` in regard to site address is just confusing and this change could save other developers some confusion and head scratching.

You're probably right about this, but apparently, a bunch of us are really kinda wary we might be inadvertently breaking something, simply because there are so many routes, and routing isn't really covered by any tests (other than some e2e ones). So if we were to do this, it deserves the full testing treatment (ask flow patrol in advance to help with testing, block deploys for a while, let sit in staging for a while)...

Also, I'm not totally convinced that treating numerical `siteId` route fragments differently from string `siteSlug`s is actually making things that much clearer, TBH...

**Comment by ockham** [comment]
Maybe the UX argument is actually the strongest here: routes ending in `mytestsite.com/mytestsite.wordpress.com` are unclear in expressing which is which to the user, so maybe we should avoid them, and thus avoid logic that specifically accounts for these cases. 

(This still doesn't mean I'm completely and totally opposed, it's just to demonstrate one way to look at things.)

**Comment by ockham** [comment]
This might be a good candidate PR to try out the new e2e testing feature. I'll add the label.

**Comment by jsnajdr** [comment]
The numeric site ID has been always a valid way to identify a site, too. Consider the following URL:
```
/domains/add/suggestion/mytestsite.com/12345
```
If I'm not wrong, the patched `getSiteFragment` will return `mytestsite.com` as the site fragment, which is a mistake -- it's supposed to be the numeric `12345` site ID.

As you can see, the site-detection code in routing is an established member of the Dark Arts Department and attempts to change it usually don't inspire much enthusiasm. If you want to enjoy some schadenfreude, read about my failed attempt to "fix" Calypso URLs in p4TIVU-721-p2 :smile:

A long term solution is to stop using `getSiteFragment` at all -- it uses heuristics and guesswork to retrieve information that should be available with 100% reliability.

The "right way" is to get the site fragment is accessing `context.params.site` and consistently naming all site variables in routes as `:site`, not `:site_id` or anything else.

The site selection code [already does that](https://github.com/Automattic/wp-calypso/blob/master/client/my-sites/controller.js#L310), but, unfortunately, there are many other places that rely on `getSiteFragment`. Some are easily fixable (the ones that have access to `context`), some are not (the ones that only know the `path` string).

My recommendation is to craft your route URLs in such a way that `getSiteFragment` works on them without change.

**Comment by nylen** [comment]
> If you want to enjoy some schadenfreude, read about my failed attempt to "fix" Calypso URLs ...

Hey, I tried to do that once too :smile: 

+1 for `/domains/add/suggestion/mytestsite.wordpress.com?s=mytestsite.com`.  If this PR doesn't break any existing test cases, that means we need to add one.

**Comment by adamziel** [comment]
Okay, I'll leave this PR here to serve as something to test with E2E tests, and to add the feature I need I'll just issue another one that will not touch any core features :-)

---

> If I'm not wrong, the patched getSiteFragment will return mytestsite.com as the site fragment, which is a mistake -- it's supposed to be the numeric 12345 site ID.

Actually those two lookups are separate from each other, it attempts to find the site fragment first so it returns mytestsite.com even before this patch. There's a test case for that here:

https://github.com/Automattic/wp-calypso/blob/master/client/lib/route/test/index.js#L135

> Also, I'm not totally convinced that treating numerical siteId route fragments differently from string siteSlugs is actually making things that much clearer, TBH...

Good point!

> Maybe the UX argument is actually the strongest here: routes ending in mytestsite.com/mytestsite.wordpress.com are unclear in expressing which is which to the user

That's true! Actually I think that the current way of formulating URL with site always as a last segment is confusing by itself. URLs like `/site/mysite.wordpress.com/post/edit/180` can be read from left to right and are pretty clear in meaning as opposed to `/site/post/edit/180/mysite.wordpress.com`. But I guess there's no benefit in obfuscating things even further.

**Comment by nylen** [comment]
> That's true! Actually I think that the current way of formulating URL with site always as a last segment is confusing by itself.

FWIW, I agree with this.  `/site/post/edit/180/mysite.wordpress.com` doesn't make sense because you're not ever going to be editing post ID `180` on multiple sites at once.

The intent behind site ID coming last is that you can view all sites at once first, then tack a site ID on to the end.  I think in most cases this model breaks down or just isn't implemented.  However, this was a decision that was made early in the history of Calypso, and now we are stuck with it in a lot of places.

**Comment by Copons** [comment]
I've opened #24256 as a sort-of-reminder issue for adding route tests, so I'm going to close this PR.

**Pull request closed without merging**
