### PR TITLE
Gutenberg: Add icon to Jetpack block category

### PR DESCRIPTION
**Pull request by tyxla**
This PR adds support for additional classes to our Jetpack logo component, and uses that component in our custom Jetpack block category. 

This will probably also be useful for https://github.com/Automattic/wp-calypso/issues/27773.

#### Changes proposed in this Pull Request

* Jetpack Logo component: Add support for adding additional `className`.
* Gutenberg: Add a `<JetpackLogo />` to our custom Jetpack block category.

#### Testing instructions

* For **design review**, the preview above should be enough (no need to go through the complicated setup process).
* Make sure you have Jetpack's Docker dev environment working and is exposed publicly (with `ngrok` for example).
* Make sure your site is connected.
* Checkout this branch.
* Spin up the following PR on your local Gutenberg: https://github.com/WordPress/gutenberg/pull/10651
* Build Gutenberg (you can use `npm run build`).
* Open a new post.
* Open the inserter.
* Have a look at the Jetpack category, verify it has the icon and it looks as shown on the preview.
* Build Calypso locally.
* Verify different parts that use the Jetpack logo are unaffected (compare with production):
  * `/jetpack/new`
  * `/jetpack/connect`
  * `/stats/:site`

gutenpack-jn

### CODE REVIEW

**Comment by MichaelArestad** [comment]
Could the icon be to the left of the name?

**Comment by mapk** [comment]
> Could the icon be to the left of the name?

My only concern here is that if some categories have an icon and others don't, the text begins to jump back and forth horizontally and becomes more difficult to scan.

**Comment by MichaelArestad** [comment]
Good point. Looks good to me!

**Comment by tyxla** [comment]
Ah, also @mapk @MichaelArestad you'll notice there was a convo about icon positioning and why we chose to keep it on the right: https://github.com/WordPress/gutenberg/pull/10651#issuecomment-430257035

**Pull request merged**
