### PR TITLE
Add page while creating menu fix

### LINKED ISSUE #4871: Menu: Create a new page for this menu item does not work for child pages
#### Steps to reproduce
1. Starting at URL: WordPress.com/menus
2. Click any + to add a new menu item, then 'Add item to children'
3. Name the item, select 'Page' then 'Create a new page for this menu item'
4. Click OK, followed by Save

#### What I expected
A new page (top level or child? would probably have to depend on context) should be created when the menu is saved.

#### What happened instead
The menu item is added, but no actual page is created. The link in the menu is not clickable, but it does show up on the site.

#### Browser / OS version
Chrome 49.0.2623.112 on OSX 10.11.3 

#### Screenshot / Video
child page

### PR DESCRIPTION
**Pull request by artpi**
This PR fixes #4871
Which is a bug created by a mess I introduced in #4034

Problem was, I forgot menus have a tree-like structure.

CC @mcsf @mtias @chad1008 @ockham @lancewillett @rralian

### CODE REVIEW

**Comment by mcsf** [comment]
I only got the ping today. Has bug #4871 still been around since last week? That's not good.

If this works and gets OK'd by someone else (maybe @chad1008, since you reported the issue?), my unorthodox recommendation would be to merge this _now_ *under the condition* that a follow-up PR is immediately opened to refactor the fix.

Notably, the [tree-convert](https://github.com/Automattic/wp-calypso/blob/master/client/lib/tree-convert/README.md) library and its [tree-traverser](https://github.com/Automattic/wp-calypso/blob/master/client/lib/tree-convert/tree-traverser.js) module were born out of the initial Menus work and its need for sound tree manipulation tools, and they should be used. It should be said that Menus — despite its now outdated look and data structure — has been one the most reliable pieces in Calypso, in that it has barely been the target of maintenance since its inception, and these tools have been properly tested. Which is why I'm reticent about introducing any new — and untested — traversal functions in the code.

cc @mtias @rralian

**Comment by rralian** [comment]
I've tested this and it fixes the problem. @mcsf's plan sounds good to me for merging this and following up with a refactor PR. 👍

**Comment by mcsf** [comment]
Cool. Let's take the opportunity to address the rest of the tech debt generated in #4034 (see discussion; [example](https://github.com/Automattic/wp-calypso/pull/4034#discussion_r57066422)) in the new PR, @artpi.

**Comment by artpi** [comment]
> Cool. Let's take the opportunity to address the rest of the tech debt generated in #4034 (see discussion; example) in the new PR, @artpi.

#4034 Did not **introduce** any technical debt. BECUSE of technical debt, certain things had to be implemented in a certain way.
But I agree, lets make it properly!

**Comment by artpi** [comment]
Also, this PR fixes 2 of 4 of these issues ( 3483d933257cd7aa7c8eab242524e72daba852e8 and  34b2073c3a0fc21f49931d0f540f52322e4dc5f1) , so basically we are well on the way :)

**Comment by chad1008** [comment]
I didn't see these notes until now, but it looks amazing :) @artpi you are a genius.

**Comment by artpi** [comment]
> @artpi you are a genius.
Well, Im the chap that introduced that and still feel bad about it.. :/

@mcsf:
As promised: #5061

**Pull request merged**
