### PR TITLE
Search: switch to onInput in input to fix react15 ie11 error.

### PR DESCRIPTION
**Pull request by budzanowski**
### Info
This is exact PR as #8901. The change from that PR  was reverted by #11357

Will fix: #12186. 

See both PRs for more details.

@samouri Hey, can you comment on that?

### CODE REVIEW

**Comment by seear** [comment]
We might be able to avoid future changes by adding a comment explaining why we need `onInput`.

**Comment by folletto** [comment]
cap-


Tested on Edge, IE11 — works 👍 


🚢

**Comment by folletto** [comment]
> We might be able to avoid future changes by adding a comment explaining why we need onInput.

Let's do this, good idea 👍

**Comment by folletto** [comment]
I also tested Reader to check there's no regression from the issue that #11357 fixed:

cap-

It's good 👍

**Comment by samouri** [comment]
I remember I switched it because of a warning I was getting in the console that went something like: "React inputs must be controlled".

I'll see if it still happening here or if I went crazy.

> We might be able to avoid future changes by adding a comment explaining why we need onInput.

👍 +100.  Its also fixed in React16 so lets keep that in the comment as well

**Pull request merged**
