### PR TITLE
Testing: Replace Mocha legacy methods with Jest alternatives

### PR DESCRIPTION
**Pull request by gziolo**
Another step to have tests API closer to Jest and therefore more consistent code.

This is an automated refactoring performed with `jest-codemods` assisted with `prettier` run. It boils down to the following transformations:
* `before` -> `beforeAll`
* `after` -> `afterAll`
* `context` -> `describe`
* `it` -> `test`
* use arrow function wherever applicable

### Testing

Make sure all existing tests pass:
* `npm run test-client`
* `npm run test-integration`
* `npm run test-server`

**Please note** that linter fails in a few places, but all of them existed before. I don't plan to tackle those issues as part of this PR.

### CODE REVIEW

**Comment by gziolo** [comment]
@skovhus - I see some improvements in how `jest-codemods` work. I had to fix 1 test manually because it was using `test` method from `sinons. Otherwise everything went perfectly fine with 1 000+ tests. Cheers :)

**Comment by skovhus** [comment]
@gziolo so happy to hear. Please let me know which cases you needed to manual fix. Would be awesome if you could create an issue here https://github.com/skovhus/jest-codemods

When looking at you tests it might makes sense to keep `it` instead of `test`. Might want to revisit https://github.com/skovhus/jest-codemods/issues/64 if you feel for it.

**Comment by gziolo** [comment]
> Please let me know which cases you needed to manual fix. Would be awesome if you could create an issue here https://github.com/skovhus/jest-codemods

@skovhus it was this file: https://github.com/Automattic/wp-calypso/blob/4a6ff2c0d6c509996fe054a4c341f372683b193a/client/components/token-field/test/index.jsx - this link is to the version before I updated it manually. There are 2 root causes:
* `import { test } from 'sinon';` which overrides `test` from Jest.
* `test` from Sinon does some trick which exposes Sinon API inside the test using `this.` notation, e.g. `this.clock.tick( 100 );`

If you think it's something you want to fix, I can open an issue or comment on the existing one for Sinon.

> When looking at you tests it might makes sense to keep it instead of test. Might want to revisit skovhus/jest-codemods#64 if you feel for it.

It would be nice to have a choice, but honestly speaking, it's closer to the official docs. I'm fine with that as long as it's automated :)

**Comment by skovhus** [comment]
> If you think it's something you want to fix, I can open an issue or comment on the existing one for Sinon.

Thanks for explaining. Seems like rather special case... Was it hard to figure out what went wrong?

**Comment by gziolo** [comment]
> Thanks for explaining. Seems like rather special case... Was it hard to figure out what went wrong?

It was very easy to fix. Cross-commented here: https://github.com/skovhus/jest-codemods/issues/68#issuecomment-335530465.

**Comment by skovhus** [comment]
Thanks for letting me know. : )

**Comment by jsnmoon** [comment]
Seeing the following integration test failures:

> - devdocs › should return documents
> - devdocs › should return documents with relative paths
> - devdocs › should return the README.md by default
> - devdocs › should not allow viewing files outside the Calypso repo
> - devdocs › should not allow viewing JavaScript files
> - devdocs › components usage stats endpoint › should return stats

Should be pretty easy to replicate these failures by running `npm run test-integration`.

**Comment by gziolo** [comment]
> Should be pretty easy to replicate these failures by running npm run test-integration.
>
> EDIT: It looks like these tests fail on master too... Fixing this might be outside the scope of this PR.

It's strange. It works locally for me even after I execute `npm run distclean`.

**Comment by gziolo** [comment]
Thanks for review 💯

**Pull request merged**
