### PR TITLE
Implement calypso_checkout_premium_upsell experiment

### PR DESCRIPTION
**Pull request by taipeicoder**
Related to https://github.com/Automattic/wp-calypso/issues/93961

## Proposed Changes

This PR implements the calypso_checkout_premium_upsell experiment, where the treatment group bypasses the upsell nudge screen.

## Why are these changes being made?

A/B test.

## Testing Instructions

* Assign yourself to different test groups via 22105-explat-experiment
* Go to /start.
* Continue until the Plans page.
* Select the Premium plan.
* Complete the purchase in the checkout screen.
  * If in the control group, ensure to see the upsell nudge screen.
  * If in the treatment group, ensure to be redirected to the goals screen.

## Pre-merge Checklist

- [x] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [x] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [x] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [x] Have you checked for TypeScript, React or other console errors?
- [x] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [x] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [x] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Review by arthur791004 — APPROVED** [review]
Looks good to me!

**Comment by aaronyan** [comment]
@necronet, when you have a chance can you please review this experiment code implementation? The PR was merged already, which is fine. It would be good to validate the implementation looks correct since the experiment hasn't launched yet.

**Comment by necronet** [comment]
Yeah, it looks good I would only point out that this experiment is setup for:

`(new + existing + anonymous)`,  just not sure if anonymous would qualified for upsell page in this case, I am unfamiliar with the upsell process, but as describe in the [setup](https://a8cexperiments.wordpress.com/2024/11/14/experiment-calypso_checkout_premium_upsell/) seems fair to assume anonymous users here?:


>    control: Users will see the upsell screen above when they checkout with a Premium plan.
>    treatment: Users will complete their orders without seeing the upsell screen when they checkout with a Premium plan.

**Comment by necronet** [comment]
Yeah, it looks good I would only point out that this experiment is setup for:

`(new + existing + anonymous)`,  just not sure if anonymous would qualified for upsell page in this case, I am unfamiliar with the upsell process, but as describe in the setup (`experiment-calypso_checkout_premium_upsell`) seems fair to assume anonymous users here?:


>    control: Users will see the upsell screen above when they checkout with a Premium plan.
>    treatment: Users will complete their orders without seeing the upsell screen when they checkout with a Premium plan.

**Comment by taipeicoder** [comment]
Hi @necronet, appreciate for the review. This upsell is only accessible for signed-up users, so there won't be anonymous users. Please let me know if there's any follow-up I need to do on my end. Thanks!

**Comment by necronet** [comment]
@taipeicoder nothing on your end I'll follow up with experiment reviewer! no worries

**Pull request merged**
