### PR TITLE
Framework: Switch to named imports from qs

### PR DESCRIPTION
**Pull request by ockham**
Mostly to give us a better grasp of what parts of `qs` we're using, for #23259.

To test:
* This is all over the place, so probably a bit unwieldy to test.
* Maybe verify that both `parse` and `stringify` work for one occurrence each.
* CircleCI going green should prove that I didn't miss any occurrences of `qs.something` in a file where I've changed the default import to a named one.
* Do a grep for `from 'qs'` to verify I've replaced all default imports by named ones.
* Let's merge, deploy, and stick around in case things go 💥?

### CODE REVIEW

**Comment by ockham** [comment]
Oh we're also using a `querystring` npm to do the... exact same kind of thing? Goody. Not updated in 5 years. I'll go PR. Sigh.

**Comment by ockham** [comment]
> I'll go PR. Sigh.

#23265

**Review by blowery — APPROVED** [review]
Looks good!

**Comment by samouri** [comment]
> Mostly to give us a better grasp of what parts of qs we're using, for #23259.

Do you also intend on merging this? Whats the reason for merging this PR?
Did you know that `webpack` is just as good at tree shaking imports that look like `import * as qs from 'qs` as it is at named imports?

**Comment by blowery** [comment]
> Did you know that webpack is just as good at tree shaking imports that look like import * as qs from 'qs as it is at named imports?

`qs` and `querystring` are common JS modules. I don't think any tree shaking is going on here.

Named imports give us a couple things:
- they prevent typos at the invocation point. If you tried to `stringgify()` eslint would fail
- if / when querystring decides to use es modules, we'll get tree shaking.

**Review by samouri — APPROVED** [review]

**Comment by ockham** [comment]
What Ben said :grin:

**Pull request merged**
