### PR TITLE
Simple Payments: deactivate EOY Guided Tour

### PR DESCRIPTION
**Pull request by lsinger**
Deactivate the Simple Payments EOY Guided Tour. 

To test:
- make sure you cannot trigger the Simple Payments EOY Guided Tour anymore

*Note*: please don't merge before Monday, Dec 18 2017. 

/cc @iamtakashi

### CODE REVIEW

**Comment by lsinger** [comment]
@mcsf thanks, great points! Will do. 

I'd know that we can get things back, but at the same time I'd like to document somehow what things / examples we've had in the past so future GT users can get a head start. Any thoughts on what a good way to document the existence of past tours (and selectors) could be? You suggested commenting things out, but I'd like to find a more documentation-like solution that will scale better. 

Just add more examples to the docs? ¯\_(ツ)_/¯ Other ideas besides that? Thanks!

**Comment by mcsf** [comment]
Hm, I might consider the following structure:

```
guided-tours/docs/
|- examples/
|  |- README.md (a)
|  |- simple-payments-end-of-year.js (b)
|
|- API.md
|- ARCHITECTURE-FUTURE.md
|- ARCHITECTURE.md
|- DEBUGGING.md
|- TUTORIAL.md (c)
```

- (a): README is optional, but could be a good place to provide common directives, e.g. the idea that, in order to try an example, one has to patch `config.js`.
- (b): The filename could reflect something more focused on the Guided-Tours-specific functionality achieved with that example, rather than a domain-specific name such as `simple-payments`.
- (c): Add a mention with a link to the examples.

**Comment by lsinger** [comment]
Thanks for those suggestions, @mcsf. I think I've now addressed them all in a3637c5. 

Any chance you can give this another look? Thanks!

**Comment by lsinger** [comment]
@mcsf Thanks! 

About the two directories: I actually like that selectors are in tours now, since that makes it easier to just try out the tour. You don't have to fiddly around with any selectors it might need. OTOH the example tours could just import the example selectors. We'd just need to make sure that people understand not to use those directly.

**Comment by iamtakashi** [comment]
Thank you, both!!

**Pull request merged**
