### PR TITLE
Me: CreditCardForm: Refactor as functional component

### PR DESCRIPTION
**Pull request by sirbrillig**
#### Changes proposed in this Pull Request

As part of modifying the "Add new card" form in #34848, some changes need to be made to the `CreditCardForm` which is used by that flow and several others. That component has several large methods, keeps some of its state in an external persistent object, and has several pieces of unused state. In this PR I've refactored the component into a simpler version which breaks it up into multiple smaller components, helper functions, and simpler state. This should not have any functional change, but it is a large refactor so it bears a lot of testing.

#### Testing instructions

Visit the "Add Card" form at http://calypso.localhost:3000/me/purchases/add-credit-card. Verify that typing in the fields works as expected (without any lag or jumping that might occur if the state object is not working well), that validation errors are displayed if using an invalid card or if there are missing details, and that a valid card can be added successfully.

Here's a list of all the components that use `CreditCardForm` and should be tested in the manner described above:

– `AddCreditCard`: http://calypso.localhost:3000/me/purchases/add-credit-card
– `AppComponents` in devdocs: http://calypso.localhost:3000/devdocs/blocks
– `EditCardDetails`: make sure you have purchased something, then visit http://calypso.localhost:3000/me/purchases, click on a purchase, and then click on "Change Payment Method"
– `AddCardDetails`: follow `EditCardDetails` instructions, but then change the end of the URL so that instead of `/payment/edit/123456` it reads `/payment/add`
– `AddCardDialog` in woocommerce-services: I'm not familiar with Woo, but the URL we need to arrive at is http://calypso.localhost:3000/store/settings/shipping/:site

## Screenshots

An example of some validation errors:

Screen Shot 2019-07-29 at 5 58 35 PM

### CODE REVIEW

**Comment by yoavf** [comment]
Unrelated, but seems like EditCardDetails lets you add a card with an invalid CVV, while AddCreditCard won't. 🤦‍♂

**Comment by yoavf** [comment]
Tested all the flows mentioned, and all work as expected 👍. Haven't had the chance to look at the code yet. 

>  AddCardDialog in woocommerce-services: I'm not familiar with Woo, but the URL we need to arrive at is http://calypso.localhost:3000/store/settings/shipping/:site

On a business site, you should have the ability to set up a store. If the store is in the US, you can create shipping labels with cards on file/add new cards.

**Comment by sirbrillig** [comment]
Thanks! I moved the stand-alone functions to their own file which hopefully should help when looking at the code.

I'll try to set up a store to test that flow.

**Comment by budzanowski** [comment]
The code looks great :) I ❤️ Context API and Hook.

**Pull request merged**
