### PR TITLE
Help Center: Move Whats New boolean to store

### LINKED ISSUE #70752: Help Center: Inconsistency between icon dot and What's New dot
### What

It may happen that the dot next to the Help Center icon and the one next to `What's New` are not aligned. This is wrong and can lead to some confusion.

image

### Why

The dot next to the icon depends on Calypso's Query Provider, while the one in the HC depends on the Help Center's Query Provider.

We could try moving the check for what's new updates to the Help Center store, instead of using React Query.

### PR DESCRIPTION
**Pull request by escapemanuele**
#### Proposed Changes

It may happen that the dot next to the Help Center icon and the one next to What's New are not aligned. This is wrong and can lead to some confusion.

This PR moves the check to see if the user has seen the What's New modal from react-query ( `useHasSeenWhatsNewModal`) to the Help Center store.

#### Testing Instructions

* Open Live Link
* Check that there is consistency between the HelpCenter icon and the More Resources link
* If you need to update the boolean value for testing, you can update your meta with `wp user meta update your-account has_seen_whats_new_modal false` in your sandbox 

Fixes #70752

### CODE REVIEW

**Review by alshakero — CHANGES_REQUESTED** [review]
Why don't we call the selector in `Help Icon` and delete the code from everywhere else, isn't that easier?

**Comment by escapemanuele** [comment]
Thank you @alshakero, I moved the logic for showing or not the dot into the Help Icon. This way I was able to remove a lot of code, simplifying things 👍

**Review by alshakero — CHANGES_REQUESTED** [review]
Brilliant. Functionality is perfect in the Editor in Calypso. Just the color of the dot is broken in the Editor.

It's due to this CSS:

```css
fill: var(--studio-gray-20);
margin-left: auto;
```

image


I'll test Atomic shortly. Also, for some reason, the value is not cached and whenever you open the Help Center it's fetched again.

**Review by alshakero — APPROVED** [review]
Tested in Atomic and works too! We'll just need to fix the color and optionally the caching.

**Comment by escapemanuele** [comment]
@alshakero I tried again and was able to see the correct updated version in the Editor ( as you see in the URL ) 🤔 

image

Have you tried the Editor while syncing ETK?

Also, thank you for catching the cache thing; I'll try to see what is wrong!

**Comment by escapemanuele** [comment]
@alshakero, if you have time, could you record the problems you found? I have trouble reproducing them, even the caching issue.

**Review by arcangelini — CHANGES_REQUESTED** [review]
This doesn't take into account the icon for `/wp-admin` (admin screens NOT editor). There is a separate icon that lives in https://github.com/Automattic/wp-calypso/blob/trunk/apps/editing-toolkit/editing-toolkit-plugin/help-center/src/help-icon.svg

To be fair, I think this currently is broken right now in production as well as in this PR. I know this is a small percentage of people getting this location, but it would still be nice to offer some consistencies as you click around.

Screen Capture on 2022-12-07 at 11-29-53

**Comment by alshakero** [comment]
I think we should put as little effort as possible on wp-admin masterbar. It can stay as-is.

**Review by alshakero — APPROVED** [review]
All works, I didn't have the last commit.

**Comment by arcangelini** [comment]
> All works, I didn't have the last commit.

Great call, I think we probably slim things down a little in the admin plugin if that is the case, in another PR. Remove the excess svg, stylings, and other crumbs from when I tried to get this working. I think this was my ball drop, it wasn't fully functional when I merged. I missed this in testing.

**Pull request merged**
