### PR TITLE
Build: Move PostCSS dependencies to calypso-build package

### PR DESCRIPTION
**Pull request by ockham**
#### Changes proposed in this Pull Request

See title :) Follow-up from #31363.

#### Testing instructions

The usual:

```
npm run distclean
npm ci
npm start
```

Verify that styling doesn't look odd.

Also:

```
npm run build-css
```

Verify that that doesn't break :slightly_smiling_face:

### CODE REVIEW

**Comment by ockham** [comment]
> A lot of scripts continue to depend on these packages in the root:
> 
> [wp-calypso/package.json](https://github.com/Automattic/wp-calypso/blob/60830a0799deda48cd5166c5c4be273226ba298c/package.json#L219-L220)
> 
> Lines 219 to 220 in [60830a0](/Automattic/wp-calypso/commit/60830a0799deda48cd5166c5c4be273226ba298c)
> 
>  "autoprefixer": "postcss -u autoprefixer -r --no-map --config packages/calypso-build/postcss.config.js", 
>  "postcss": "postcss -r --config packages/calypso-build/postcss.config.js", 

Curiously, `npm run build-css` (which uses the `postcss` `script`) seemed to wfm when I tested it :thinking: I _think_ the reason might be that it's using `--config packages/calypso-build/postcss.config.js` which is in the package dir that has the dependencies available?

As for the `autoprefixer` script, I'm not sure if that's even still used anywhere. Quick grepping didn't seem to suggest so.

> The postcss CLI continues to exist on the root:
> 
> [wp-calypso/package.json](https://github.com/Automattic/wp-calypso/blob/60830a0799deda48cd5166c5c4be273226ba298c/package.json#L161)
> 
> Line 161 in [60830a0](/Automattic/wp-calypso/commit/60830a0799deda48cd5166c5c4be273226ba298c)
> 
>  "postcss-cli": "6.1.2", 
> It seems that all these should move together, what do you think?

I was on the fence about this one. It's arguable that we're using the CLI to build some fairly Calypso-app specific style files (rather than relying on Webpack for them), indicating that it might make sense to keep the CLI stuff there.

**Comment by sirreal** [comment]
> Curiously, npm run build-css (which uses the postcss script) seemed to wfm when I tested it 🤔

That makes sense, the dependency is still included and node can find it. However, those root scripts are using those dependencies via `postcss-cli` and therefore should remains as root dependencies (possibly devDeps). Let's add the deps to the `calypso-build` package, but as long as these scripts live on the root package also keep the deps on the root.

> As for the autoprefixer script, I'm not sure if that's even still used anywhere. Quick grepping didn't seem to suggest so.

Seems so, we should remove it (not necessarily here).

**Comment by lezama** [comment]
we tried this with @enejb and noticed that things break, we didn't explore further on why, thanks for working on it @ockham

**Comment by ockham** [comment]
Amended the commit to add back dependencies to the root `package.json`.

**Pull request merged**
