### PR TITLE
Data Layer: Fix POSTing data in data layer

### PR DESCRIPTION
**Pull request by donnapep**
Passing empty objects for `body` and `query` causes form data to not be POSTed correctly, since wpcom runs explicit checks against `undefined`, or missing, parameters. Not passing these parameters to wpcom at all resolves the problem.

### CODE REVIEW

**Comment by dmsnell** [comment]
Looks like a reasonable fix @donnapep - I'm less familiar with the POST requests and `wpcom.js` in general. Let's test this but I think it's all looking great

**Comment by donnapep** [comment]
@dmsnell Looks like only Plans is using the HTTP layer. I've tested that and it's still working. Reader has some code to use it for tags, but it doesn't actually look like it's being called from anywhere yet. So I think we're good!

**Comment by dmsnell** [comment]
@donnapep is the `size` -> `total` thing a part of `superagent`? MDN shows that the `XMLHttpRequest` `onprogress` event should have a property called `total`. also, if we have some browser incompatibility issues here we'll need to handle those properly

https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequestEventTarget/onprogress

**Comment by donnapep** [comment]
@dmsnell Looks like the info at that link is incorrect. The [spec](https://xhr.spec.whatwg.org/#interface-progressevent) indicates `total` and makes no mention of `size`. The example in [this MDN doc](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/Using_XMLHttpRequest#Monitoring_progress) also uses `total`.

I tested uploading on Chrome, FF, Safari and IE and it all works well.

Cheers!

**Comment by donnapep** [comment]
Updated the MDN documentation. That was easy!

**Pull request merged**
