### PR TITLE
chore(deps): Upgrade TypeScript

### PR DESCRIPTION
**Pull request by sirreal**
#### Changes proposed in this Pull Request

* Upgrade TypeScript to 4.0.3

Manually did this because renovate can't be bothered 😆 

#### Testing instructions

* This should be covered by CI. Do all jobs complete?

### CODE REVIEW

**Comment by scinos** [comment]
Do we know why it reduced the size of `entry-gutenboarding` that much? And why it didn't reduce other entrypoints that use TS?

**Review by scinos — APPROVED** [review]

**Comment by sgomes** [comment]
This is a build tool, so it's not a huge priority, but is there any chance we could figure out what's still requesting the `3.9` range and upgrade it to `4.0` as well? It may be a problem to use new `4.x` features if there's still part of the build process that's on an older version.

**Comment by sirreal** [comment]
> This is a build tool, so it's not a huge priority, but is there any chance we could figure out what's still requesting the `3.9` range and upgrade it to `4.0` as well? It may be a problem to use new `4.x` features if there's still part of the build process that's on an older version.

Thanks, I overlooked this was adding another version. Cleaned up!

**Comment by sirreal** [comment]
> Do we know why it reduced the size of entry-gutenboarding that much? And why it didn't reduce other entrypoints that use TS?

I don't know exactly where, but I suspect it's where we're using some `tsc`-compiled packages. The compiler output has likely had some changes.

Not all of the TypeScript pacakges are compiled by `tsc`, quick search suggests these:

* `browser-data-collector`
* `calypso-analytics`
* `components`
* `composite-checkout`
* `data-stores`
* `domain-picker`
* `media-library`
* `onboarding`
* `plans-grid`
* `react-i18n`

I believe they're most heavily used in gutenboarding, so there's more likelihood that we observe the compiler change there.

**Pull request merged**
