### PR TITLE
Premium Squared: Allow elligible premium themes to be activated (take two)

### PR DESCRIPTION
**Pull request by mendezcode**
Currently, themes included in the Premium Squared bundle can't be activated from the Calypso theme showcase. This PR adds the necessary bits of code to allow theme activation of Premium Squared themes (e.g. Automattic + WooThemes themes).

**Note:** This PR is actually a fix of #11112, which was reverted on #11178 because of errors.

The code is mostly the same as #11112, but with a minor fix introduced in 2a94588365696eb34c4c2d8c842183bf86d1259b, which gets rid of the `FEATURE_PREMIUM_SQUARED` constant from `client/state/lib/plans/constants.js`, and instead checks for the Premium Plan directly via `getSitePlanSlug`.

- - - 

**Testing Instructions**

On a site with the Premium Upgrade, you should be able to install Automattic and WooThemes Premium themes without having to purchase them.

Here are the themes you should be able to activate:
- Automattic: https://theme.wordpress.com/?theme_shop=automattic
- WooThemes: https://theme.wordpress.com/?theme_shop=woothemes

### CODE REVIEW

**Comment by mendezcode** [comment]
@lancewillett @gwwar  I would love your help testing this one to make sure it's working as it should, and to make sure I didn't miss anything critical...

Thanks a lot in advance! 😄

**Comment by lancewillett** [comment]
I'm testing manually in the live branch. @hoverduck Could you run an e2e test for a sanity check?

Last time this broke some plans pages (JS error, see https://github.com/Automattic/wp-calypso/pull/11112#issuecomment-277383529).

**Comment by hoverduck** [comment]
e2e tests ran clean

**Comment by lancewillett** [comment]
🚢 No JS errors I could see in manually testing, especially looking on the `/plans` views.

**Pull request merged**
