### PR TITLE
GS on Personal A/B: Pattern Assembler to show correct copy when font and/or color are used

### PR DESCRIPTION
**Pull request by rcrdortiz**
Related to https://github.com/Automattic/dotcom-forge/issues/2861

## Proposed Changes

* Propagate the `globalStylesInPersonalPlan` property to the necessary component in the `design-preview` package and made the necessary components GS A/B aware, they'll now return the corresponding text based on the required plan.
* Updated Calypso's `screen-color-palettes` and `screen-font-pairings` to be GS A/B aware and display the upsell text accordingly.

| Before | After |
-----|-----
Captura de Pantalla 2023-07-05 a las 16 47 46|Captura de Pantalla 2023-07-05 a las 16 46 42
Captura de Pantalla 2023-07-05 a las 16 47 53|Captura de Pantalla 2023-07-05 a las 16 46 55

## Testing Instructions

* Use Calypso live link
* Make sure you belong to the treatment group.
* Go through the /start process on a free plan until you reach the Pattern Assembler.
* Go to the bottom and use the assembler CTA.
* It should have a nav item that says Colors, click that and select a premium color.
* Just under the `Colors` title you should see a text that reads `Choose from our curated color palettes when you upgrade to the Personal plan or above.`
* Repeat for fonts.

You can change your group here (21268-explat-experiment), you also need to clear the cache when switching between groups by executing this command in your sandbox:
`wp_cache_delete( 'global-styles-on-personal-{siteId}', 'a8c_experiments' );` 
## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

**Comment by mmtr** [comment]
To test the changes in the `useScreen` hook we need to enable the `signup/design-picker-preview-colors` flag and select a non-virtual theme without style variations.

**Review by mmtr — APPROVED** [review]
LGTM 🚀

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/8352100

Thank you @rcrdortiz for including a screenshot in the description! This is really helpful for our translators.

**Comment by mmtr** [comment]
Unit test seems to fail for legit reasons:

```
client/landing/stepper/declarative-flow/internals/steps-repository/design-setup/unified-design-picker.tsx(662,4): error TS2322: Type '{ designs: Design[]; locale: string; onSelectBlankCanvas: (blankCanvasDesign: Design, shouldGoToAssemblerStep: boolean) => void; onPreview: (design: Design, styleVariation?: StyleVariation | undefined) => void; ... 7 more ...; getBadge: (themeId: string, isLockedStyleVariation: boolean) => Element; }' is not assignable to type 'IntrinsicAttributes & UnifiedDesignPickerProps'.
```

**Comment by rcrdortiz** [comment]
> Unit test seems to fail for legit reasons:
> 
> ```
> client/landing/stepper/declarative-flow/internals/steps-repository/design-setup/unified-design-picker.tsx(662,4): error TS2322: Type '{ designs: Design[]; locale: string; onSelectBlankCanvas: (blankCanvasDesign: Design, shouldGoToAssemblerStep: boolean) => void; onPreview: (design: Design, styleVariation?: StyleVariation | undefined) => void; ... 7 more ...; getBadge: (themeId: string, isLockedStyleVariation: boolean) => Element; }' is not assignable to type 'IntrinsicAttributes & UnifiedDesignPickerProps'.
> ```

I'll have a look

**Review by mmtr — APPROVED** [review]

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/8352100

Thank you @rcrdortiz for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/8352100).

**Pull request merged**
