### PR TITLE
DocumentHead: Remove setUnreadCount and unreadCount props

### PR DESCRIPTION
**Pull request by ockham**
See #24977 for background:

> 1. Remove the dedicated `unreadCount` handling from the `DocumentHead` component and state. Arguably, `DocumentHead` should reflect the contents of the HTML head. `unreadCount` is simply reflected in the `<title />`, and it's not a very generic or widely used thing -- I think only the Reader uses it. Hence, I think it's fair to put the burden of managing `unreadCount` state on the consuming component rather than `DocumentHead`.

What's more is that by definition, the `unreadCount` isn't needed on the server side: We only show the `unreadCount` indicator in the title to indicate how many new posts have been published since the reader was first loaded. This is reflected by `<DocumentHead />`'s `unreadCount` prop only having been used in one place -- the `UpdateNotice` component (the orange visual indicator telling the user that there are new posts).

Hence, this PR:
* Changes `UpdateNotice` to handle unread count state internally
* Removes `unreadCount` related `DocumentHead` props and Redux state stuff

To test:
* Verify that Reader still properly shows the correct unread count in the site title (in parens). (Question for Reader folks: What Redux action do we need to dispatch in the console in order to easily simulate new posts?)
* Verify that navigating away properly updates the site title (particularly, that it removes the unread count)

### CODE REVIEW

**Comment by Copons** [comment]
There is a little bug: when a new post appears, the "1 New Post" button pops up in the top right corner.
Clicking on it should scroll to the top, load the new post and remove the `(1)` counter from the title.
On this branch, it does everything right except removing the counter.

**Comment by blowery** [comment]
@westi @bluefuton Could you please take a peek at this?

**Comment by Copons** [comment]
Just pointing out that [my previous comment](https://github.com/Automattic/wp-calypso/pull/24980#issuecomment-391384629) is still valid.

**Comment by westi** [comment]
I have lighted test this and it looks like it works, I would prefer @bluefuton reviewed the code as he is most likely at least somewhat familar with it.

It looks like some of the e2e ie11 tests failed which need investigating and we should address @Copons' feedback too before merging.

**Comment by ockham** [comment]
Thanks everyone for testing! Happy to fix the issue that @Copons pointed out, but I'm actually on the fence on closing this PR altogether. The issues that originally motivated it have been fixed differently, so at this points its largely an architectural question on whether or not we want to track something app specific (section specific, even) in `document-head` Redux state which otherwise simply reflects HTML `<head />` elements.

Arguments I can think of:
* Pro removal of `unreadCount`:
  * Better conceptual mapping of `<head />`

* Contra removal of `unreadCount`:
  * Makes `unreadCount` handling a bit uglier (see diff)

**Comment by jsnajdr** [comment]
@ockham Does this patch just refactor the code to improve its design, or does it fix any issues? You mention that:

> The issues that originally motivated it have been fixed differently

But I don't understand what these issues were.

If it's only a refactoring, I liked the original design better: all information was in state and the title was derived from state by concatenating the pieces together. That's the declarative React philosophy.

On the other hand, the new code is similar to how we built UIs before React: look at the current rendered UI and modify it by adding and removing DOM elements. Very error prone, as the number of possible transitions grows exponentially. It's ironic that the new code has a typical bug where the title is not correctly updated when `unreadCount` goes from 1 to 0.

If `unreadCount` is not generic enough, what about maintaining a "title prefix" value instead?

**Comment by blowery** [comment]
@ockham did you still want to continue this?

**Comment by jsnajdr** [comment]
Sooner or later, as we continue the frameworkization of Calypso, `unreadCount` should be a plugin that registers into some `documentTitle` hook when Reader is activated and unregistered when it's deactivated.

**Comment by bluefuton** [comment]
Closing this one for the moment.

**Pull request closed without merging**
