### PR TITLE
Support: Add chat closure for company meetup

### PR DESCRIPTION
**Pull request by klimeryk**
As requested on pdm0RZ-ni-p2

#### Proposed Changes

Use the component provided by @alshakero in https://github.com/Automattic/wp-calypso/pull/69523 in the old contact form/FAB.

Screenshot 2022-10-28 at 19 15 32
Screenshot 2022-10-28 at 19 15 40
Screenshot 2022-10-28 at 19 16 32

#### Testing Instructions

See https://github.com/Automattic/wp-calypso/pull/69523. Make sure to disable the Help Center: `return false` in `shouldShowHelpCenterToUser` (`packages/help-center/src/utils.ts`).

### CODE REVIEW

**Comment by klimeryk** [comment]
@obenland @mreishus, as the authors of https://github.com/Automattic/wp-calypso/pull/63681, could you please have a look here? The plan features check does not seem to be working as expected. When I inspect the site items, the `plan` property is missing the expected `features` property:
Screenshot 2022-10-26 at 10 43 55
Which in turn makes all users be on the "privateSupport" (no live chat) variant. I'm guessing we need to somehow load the features somehow but I could not find the way skimming through the code.

**Comment by obenland** [comment]
Features are a sibling property to site items (`state.sites.features` to `state.sites.items`), [the selector here](https://github.com/Automattic/wp-calypso/blob/52d08454444f793d2127940f096f61f8692d7d01/client/me/help/gm-closure-notice/index.jsx#L21-L25) just grabs site IDs to use them in feature checks that access `state.sites.features` directly. Logging the value of `hasLiveChat` returns true for me locally.

This is what I'm seeing once I disable the date check in line 35:
image

Is that what you're looking for?

**Comment by mreishus** [comment]
In my testing, I'm seeing it load the features for my currently selected site most of the time. Here's what I'm using:

```diff
diff --git a/client/me/help/gm-closure-notice/index.jsx b/client/me/help/gm-closure-notice/index.jsx
index 02a5d64ba3..5f4140b32b 100644
--- a/client/me/help/gm-closure-notice/index.jsx
+++ b/client/me/help/gm-closure-notice/index.jsx
@@ -8,6 +8,7 @@ import FormSectionHeading from 'calypso/components/forms/form-section-heading';
 import { useLocalizedMoment } from 'calypso/components/localized-moment';
 import getSitesItems from 'calypso/state/selectors/get-sites-items';
 import siteHasFeature from 'calypso/state/selectors/site-has-feature';
+import getSiteFeatures from 'calypso/state/selectors/get-site-features';
 
 import './style.scss';
 
@@ -18,11 +19,24 @@ export default function GMClosureNotice( { compact, displayAt, closesAt, reopens
 	const translate = useTranslate();
 	const moment = useLocalizedMoment();
 
+	const debug = useSelector( ( state ) => {
+		const siteItems = getSitesItems( state );
+		for ( const item of Object.values( siteItems ) ) {
+			const { ID } = item;
+			const features = getSiteFeatures( state, ID );
+			if ( features ) {
+				console.log( JSON.stringify( { ID, features } ) );
+			}
+		}
+		return 5;
+	} );
+
 	const hasLiveChat = useSelector( ( state ) =>
 		Object.values( getSitesItems( state ) ).some( ( { ID } ) =>
 			siteHasFeature( state, ID ?? 0, WPCOM_FEATURES_LIVE_SUPPORT )
 		)
 	);
+	console.log( { hasLiveChat } );
 
 	const currentDate = moment();
 	const guessedTimezone = moment.tz.guess();
diff --git a/client/me/help/help-contact/index.jsx b/client/me/help/help-contact/index.jsx
index 39014661d5..9b9330086c 100644
--- a/client/me/help/help-contact/index.jsx
+++ b/client/me/help/help-contact/index.jsx
@@ -584,7 +584,7 @@ class HelpContact extends Component {
 						/>
 						<GMClosureNotice
 							compact={ compact }
-							displayAt="2022-10-29 00:00Z"
+							displayAt="2022-09-29 00:00Z"
 							closesAt="2022-11-05 00:00Z"
 							reopensAt="2022-11-14 07:00Z"
 						/>
diff --git a/packages/help-center/src/utils.ts b/packages/help-center/src/utils.ts
index d81d9894ae..a9b3f55170 100644
--- a/packages/help-center/src/utils.ts
+++ b/packages/help-center/src/utils.ts
@@ -6,6 +6,7 @@ import { isWpMobileApp } from 'calypso/lib/mobile-app';
 // only a certain percentage of users.
 // eslint-disable-next-line @typescript-eslint/no-unused-vars
 export function shouldShowHelpCenterToUser( userId: number ) {
+	return false;
 	const isNonProdEnv =
 		[ 'stage', 'development', 'horizon' ].includes( config( 'env_id' ) ) || isCalypsoLive();
 
```

--> Visit a url like `http://calypso.localhost:3000/plans/mysite.wordp ress.com` -> Click ? -> Click contact us -> See live chat is true -> Expand limited support -> Click learn more --> I'm now on `/help/contact` --> Still see live chat is true

--- 

However, I did find one workflow that stops it from loading.
* Remove all localstorage / IndexedDB data
* Visit `/help/contact` directly

In this case, the layout doesn't query the currently selected's site data, and livechat is unavailable.

**Comment by mreishus** [comment]
One possible fix for the above scenario: bd8677d506533cc3ccec0a9738c2ae7e0fca1272
This isn't always great, since it makes one web request per site, and for someone like me with 100 sites that's quite a lot :)
It may be the best fix though. I tried to get only the current site's features here, 2e1663a66a647d1109dcd1b1c5de0778bbc720e5, and this does not work when loaded on `/help/contact` with all locastorage/indexdb gone: No site is selected.

**Comment by klimeryk** [comment]
@obenland @mreishus, many thanks for quickly looking at this and helping me troubleshoot it.
We needed to do this in Help Center (the new contact form created by Vertex) and @alshakero created a separate component for it in https://github.com/Automattic/wp-calypso/pull/69523 that I ended up using here. It uses a flag from the backend that with 100% accuracy tells us if the user is eligible for chat or not.

The reason why @obenland could not reproduce the issue was because the features are loaded only for the current site. And I'm guessing your current site had a paid plan that gave you access to chat. However, my test setup is different: current site is on free plan, however I have different sites that give me access to chat. On WordPress.com you're eligible for the best support out of all your sites, not just based on the current one. So, you'd have to indeed load features of all sites to have an accurate check for the `WPCOM_FEATURES_LIVE_SUPPORT` feature.

The alternative that is more performant (but maybe less "proper" from an architectural/design point of view) is use [`isHappychatUserEligible` selector](https://github.com/Automattic/wp-calypso/blob/trunk/client/state/happychat/selectors/is-happychat-user-eligible.js).

I'm now worried that reliance on the `WPCOM_FEATURES_LIVE_SUPPORT` feature as implemented here (and in other places in Calypso) is not accurate and not always giving our users the best support they should get. I'd love to chat more on what do you think would be the best way forward. I don't want to undo your work of relying on site's features, but I also want to make sure the decisions we make based on them are meeting our (and user's) expectations of support.

**Comment by obenland** [comment]
It looks like `WPCOM_FEATURES_LIVE_SUPPORT` is only used [twice](https://github.com/Automattic/wp-calypso/search?q=WPCOM_FEATURES_LIVE_SUPPORT) in Calypso, [one of them seems to be a legitimate site-based context](https://github.com/Automattic/wp-calypso/blob/f05cb71413871ada10ab62805f5d265dedfd8bb6/client/state/marketplace/selectors.ts#L46).

I agree, [this place](https://github.com/Automattic/wp-calypso/blob/ca341441b5ecbce0b97983b1bee47ffd211c651f/client/me/help/gm-closure-notice/index.jsx#L21-L25) would probably be better served by `isHappychatUserEligible`.

**Pull request merged**
