### PR TITLE
Build: Do not remove local node_modules when building docker

### PR DESCRIPTION
**Pull request by sirreal**
The `.dockerignore` excludes `node_modules` from copy:

https://github.com/Automattic/wp-calypso/blob/2ed4bd06e8d2136ccedba9cd259f33074bdcfb58/.dockerignore#L4

Docker performs `npm install --prod` as part of the build:

https://github.com/Automattic/wp-calypso/blob/2ed4bd06e8d2136ccedba9cd259f33074bdcfb58/Dockerfile#L30

Removing `node_modules` from local environment via `distclean` only serves to make subsequent work with the repo more painful, requiring a reinstall.

This PR changes the `prebuild-docker` script to run `clean` over `distclean`, the only difference being the removal of `node_modules`:

https://github.com/Automattic/wp-calypso/blob/80d182c5c0932711fa82de58a520a5769db62bbf/package.json#L196

https://github.com/Automattic/wp-calypso/blob/80d182c5c0932711fa82de58a520a5769db62bbf/package.json#L203

**Update**

I've also added `npm-debug.log*` to `.dockerignore` after seeing its inclusion (https://github.com/Automattic/wp-calypso/pull/19801#issuecomment-344624349).

## Testing
1. `npm run build-docker`
1. Ensure build completes successfully and the result is functionally the same as current builds.
1. `node_modules` should not be removed from your local environment.

### CODE REVIEW

**Comment by sirreal** [comment]
I've verified that local `node_modules` are not copied by applying the following diff:

```patch
diff --git a/Dockerfile b/Dockerfile
index ef6e5e6128..aa50524462 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -19,27 +19,4 @@ ENV        NODE_PATH=/calypso/server:/calypso/client
 COPY       ./env-config.sh /tmp/env-config.sh
 RUN        bash /tmp/env-config.sh
 
-# Build a "dependencies" layer
-#
-# This layer should include all required npm modules
-# and should only change as often as the dependencies
-# change. This layer should allow for final build times
-# to be limited only by the Calypso build speed.
-COPY       ./package.json ./npm-shrinkwrap.json /calypso/
-RUN        true \
-           && npm install --production \
-           && rm -rf /root/.npm \
-           && true
-
-# Build the final layer
-#
-# This contains built environments of Calypso. It will
-# change any time any of the Calypso source-code changes.
 COPY       . /calypso/
-RUN        true \
-           && CALYPSO_ENV=production npm run build \
-           && chown -R nobody /calypso \
-           && true
-
-USER       nobody
-CMD        NODE_ENV=production node build/bundle.js
```

and running the following to see whether `node_modules` is present (it is not):

```sh
$ docker run -it --name wp-calypso-eight --rm -p 80:3000 -e NODE_ENV=wpcalypso -e CALYPSO_ENV=wpcalypso wp-calypso /bin/ls -l

total 668
-rw-r--r--  1 root root   2510 Sep 14 22:01 CODE-OF-CONDUCT.md
-rw-r--r--  1 root root  75701 Oct 31 12:48 CREDITS.md
-rw-r--r--  1 root root    523 Nov 15 15:13 Dockerfile
-rw-r--r--  1 root root  15174 Aug 11 06:50 LICENSE.md
-rw-r--r--  1 root root   3186 Aug 11 06:50 README.md
-rw-r--r--  1 root root    401 Aug 11 06:50 Vagrantfile
-rw-r--r--  1 root root    847 Aug 11 06:50 Vagrantfile-boot2docker
drwxr-xr-x  3 root root   4096 Aug 11 06:50 assets
drwxr-xr-x  5 root root   4096 Nov 15 13:58 bin
-rw-r--r--  1 root root   1768 Nov 15 13:58 circle.yml
drwxr-xr-x 26 root root   4096 Nov 15 13:58 client
drwxr-xr-x  2 root root   4096 Nov 15 13:58 config
drwxr-xr-x  5 root root   4096 Oct 25 16:48 docs
-rw-r--r--  1 root root      0 Nov 15 15:13 env-config.sh
-rw-r--r--  1 root root   1554 Sep 28 10:30 index.js
-rw-r--r--  1 root root    250 Aug 11 06:50 jsconfig.json
-rw-r--r--  1 root root   1387 Oct 31 16:36 npm-debug.log.1283760180
-rw-r--r--  1 root root   1029 Oct 31 19:43 npm-debug.log.181704183
-rw-r--r--  1 root root   3610 Nov 10 13:08 npm-debug.log.3728101807
-rw-r--r--  1 root root   1029 Nov 10 11:30 npm-debug.log.3745233072
-rw-r--r--  1 root root 470349 Nov 15 13:58 npm-shrinkwrap.json
-rw-r--r--  1 root root  13238 Nov 15 14:45 package.json
-rw-r--r--  1 root root     97 Oct 31 12:48 postcss.config.json
drwxr-xr-x  8 root root   4096 Nov 10 12:25 public
drwxr-xr-x 15 root root   4096 Aug 11 06:50 server
drwxr-xr-x  7 root root   4096 Oct  4 12:48 test
-rw-r--r--  1 root root   7970 Nov 10 09:52 webpack.config.js
-rw-r--r--  1 root root   5805 Oct 31 12:48 webpack.config.node.js
```

**Comment by ockham** [comment]
I've recently seen some weird Docker build errors https://github.com/Automattic/wp-calypso/pull/19697#issuecomment-343958188 that could be fixed by removing `node_modules/` prior to running `npm run build-docker` (even tho that's been supposed to do that for me anyway). I haven't quite tracked it down yet but wanted to bring it on the record here.

**Comment by gwwar** [comment]
@ockham is the .dockerignore not being respected? Seems like something we'd want to look into.

@sirreal changes here make sense. Let's verify that .dockerignore is working.

**Comment by ockham** [comment]
Quoting some more info I just added to https://github.com/Automattic/wp-calypso/pull/19697#issuecomment-344709456:

> Some more discussion here p1510613672000075-slack-opers: Apparently `/usr/local/bin/npm cache clean` is run on the systems side, i.e. outside the `Dockerfile`.

**Comment by samouri** [comment]
This would save me so much time if it pans out!

**Comment by sirreal** [comment]
> Let's verify that .dockerignore is working.

That's what I've ostensibly done in this comment https://github.com/Automattic/wp-calypso/pull/19801#issuecomment-344624349

In a bit more detail:

1. Remove `npm install` section from `Dockerfile`
1. Stop after `COPY . /calypso/` command in `Dockerfile`
1. At this point, we have copied the local directory to the Docker container at `/calypso/`. I assert that if `node_modules` were included in the copy, we would see it there.
1. Print contents of Docker container `/calypso/`. Verify that `node_modules` is not included.

It's not clear to me how local `node_modules` could affect the Docker container.

---

This exploration has lead me to the conclusion that we should be _explicit_ with the `COPY` instructions. Note that prior to 28885d3, `npm-debug` files were included in the image! Any files that are sitting around in my local environment will be included in the image, this affects the image and could force unnecessary intermediate images to be created.

I'll open a PR for this in the near future.

**Comment by sirreal** [comment]
Here is some more detailed output performing the same operations to verify behavior:

Apply the diff so that we create the image and copy files without `npm install` on the container:

```patch
diff --git a/Dockerfile b/Dockerfile
index ef6e5e6128..1df8384ce2 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -26,20 +26,11 @@ RUN        bash /tmp/env-config.sh
 # change. This layer should allow for final build times
 # to be limited only by the Calypso build speed.
 COPY       ./package.json ./npm-shrinkwrap.json /calypso/
-RUN        true \
-           && npm install --production \
-           && rm -rf /root/.npm \
-           && true
 
 # Build the final layer
 #
 # This contains built environments of Calypso. It will
 # change any time any of the Calypso source-code changes.
 COPY       . /calypso/
-RUN        true \
-           && CALYPSO_ENV=production npm run build \
-           && chown -R nobody /calypso \
-           && true
 
 USER       nobody
-CMD        NODE_ENV=production node build/bundle.js
```

Verify container contents at `/calypso/`

```
# Build the image
$ npm run build-docker

> wp-calypso@0.17.0 prebuild-docker /Users/jonsurrell/a8c/calypso
> npm run -s clean && ( touch env-config.sh || type nul >> env-config.sh )


> wp-calypso@0.17.0 build-docker /Users/jonsurrell/a8c/calypso
> docker build -t wp-calypso .

Sending build context to Docker daemon  191.1MB
Step 1/9 : FROM node:8.9.1
 ---> 1934b0b038d1
Step 2/9 : MAINTAINER Automattic
 ---> Using cache
 ---> 3f79d404c96f
Step 3/9 : WORKDIR /calypso
 ---> Using cache
 ---> 0ab7f55a43df
Step 4/9 : ENV NODE_PATH /calypso/server:/calypso/client
 ---> Using cache
 ---> 8e88e547e2b5
Step 5/9 : COPY ./env-config.sh /tmp/env-config.sh
 ---> Using cache
 ---> f19050e859a5
Step 6/9 : RUN bash /tmp/env-config.sh
 ---> Using cache
 ---> b61e19a5c9f7
Step 7/9 : COPY ./package.json ./npm-shrinkwrap.json /calypso/
 ---> Using cache
 ---> 1965310c7861
Step 8/9 : COPY . /calypso/
 ---> Using cache
 ---> 09846e4b58da
Step 9/9 : USER nobody
 ---> Using cache
 ---> 15b054d222d9
Successfully built 15b054d222d9
Successfully tagged wp-calypso:latest

# Execute `ls -la`on the created image's /calypso directory
$ docker run -it --name wp-calypso-eight --rm -p 80:3000 -e NODE_ENV=wpcalypso -e CALYPSO_ENV=wpcalypso wp-calypso ls -la /calypso/

total 148736
drwxr-xr-x  1 root root      4096 Nov 16 08:31 .
drwxr-xr-x  1 root root      4096 Nov 16 08:33 ..
-rw-r--r--  1 root root       621 Nov 16 07:44 .babelrc
-rw-r--r--  1 root root        47 Nov 16 08:28 .dockerignore
-rw-r--r--  1 root root       344 Aug 11 15:41 .editorconfig
-rw-r--r--  1 root root         8 Jun 12 12:03 .env
-rw-r--r--  1 root root      1839 Apr 11  2017 .esformatter
-rw-r--r--  1 root root       356 Sep 19 20:41 .eslines.json
-rw-r--r--  1 root root       120 Jun 12 14:54 .eslintignore
-rw-r--r--  1 root root       816 Nov  6 09:01 .eslintrc.js
-rw-r--r--  1 root root        27 Nov 15 07:30 .gitattributes
drwxr-xr-x  2 root root      4096 Sep 25 19:29 .github
-rw-r--r--  1 root root       784 Nov  6 09:01 .gitignore
-rw-r--r--  1 root root      1851 Apr 11  2017 .jsfmtrc
-rw-r--r--  1 root root        39 Nov 16 07:44 .npmrc
-rw-r--r--  1 root root        20 Jun  5 10:50 .nvimrc
-rw-r--r--  1 root root         7 Nov 16 07:44 .nvmrc
-rw-r--r--  1 root root        73 Apr 11  2017 .rtlcssrc
-rw-r--r--  1 root root      2169 Apr 11  2017 .stylelintrc
-rw-r--r--  1 root root      2510 Sep 25 19:29 CODE-OF-CONDUCT.md
-rw-r--r--  1 root root     75701 Nov  6 09:01 CREDITS.md
-rw-r--r--  1 root root       985 Nov 16 08:28 Dockerfile
-rw-r--r--  1 root root     15174 Apr 11  2017 LICENSE.md
-rw-r--r--  1 root root      3186 Aug 11 15:41 README.md
-rw-r--r--  1 root root      1836 Jun  5 12:42 Session.vim
-rw-r--r--  1 root root       401 Apr 11  2017 Vagrantfile
-rw-r--r--  1 root root       847 Apr 11  2017 Vagrantfile-boot2docker
drwxr-xr-x  3 root root      4096 Jul 10 08:32 assets
drwxr-xr-x  5 root root      4096 Nov 16 07:44 bin
-rw-r--r--  1 root root    730219 Nov 10 10:00 calypso-strings.pot
-rw-r--r--  1 root root      1768 Nov 16 07:44 circle.yml
drwxr-xr-x 26 root root      4096 Nov 16 07:44 client
drwxr-xr-x  2 root root      4096 Nov 16 08:28 config
drwxr-xr-x  5 root root      4096 Nov  6 09:01 docs
-rw-r--r--  1 root root         0 Nov 16 08:29 env-config.sh
-rw-r--r--  1 root root      1554 Sep 29 12:35 index.js
-rw-r--r--  1 root root       250 Aug 11 15:41 jsconfig.json
-rw-r--r--  1 root root    470349 Nov 16 07:44 npm-shrinkwrap.json
-rw-r--r--  1 root root     13238 Nov 16 08:28 package.json
-rw-r--r--  1 root root        97 Nov  6 09:01 postcss.config.json
drwxr-xr-x  8 root root      4096 Nov 15 12:21 public
drwxr-xr-x 15 root root      4096 Aug 11 15:41 server
-rw-r--r--  1 root root 150818545 Nov 10 09:46 stats.json
drwxr-xr-x  7 root root      4096 Nov  6 09:01 test
-rw-r--r--  1 root root      7970 Nov 16 08:28 webpack.config.js
-rw-r--r--  1 root root      5805 Nov 16 08:28 webpack.config.node.js
```

**Comment by ockham** [comment]
This change would however mean that if in local development we switched to a branch that includes changes to `package.json` (and thus, `node_modules/`), we'd have to manually `npm run distclean` if we were to build that branch in Docker (by running `npm run build-docker`), right?

**Comment by samouri** [comment]
I have a separate question:

why does our docker file depend on _anything_ on the local fs?
would it be better to start out with `RUN git clone ...`?

**Comment by sirreal** [comment]
> This change would however mean that if in local development we switched to a branch that includes changes to package.json (and thus, node_modules/), we'd have to manually npm run distclean if we were to build that branch in Docker (by running npm run build-docker), right?

@ockham I think the answer is no. The difference between `clean` and `distclean` is the complete removal of `node_modules`, but `node_modules` on the host machine should have no impact whatsoever on the docker images.

The intermediate docker images starting at ` COPY ./package.json ./npm-shrinkwrap.json /calypso/` will be rebuilt, meaning `npm install --production` will be run on the container, and the new branch's modules installed.

https://github.com/Automattic/wp-calypso/blob/1de6747db617294548afd535b758b365ea8caa2e/Dockerfile#L28-L32

---

@samouri Definitely not dumb questions and worth considering. I will venture some speculative answers as I'm no authority as to why our Docker setup is the way it is.

> why does our docker file depend on anything on the local fs?
> would it be better to start out with RUN git clone ...?

The strength is that we can work locally, but see how code behaves in a context that is nearly identical to production without actually deploying. I don't think there's much safety in requiring you to commit something in order to see it run on Docker.

> or if we wanted to go 100% in the other direction (would be much faster) we could go as far as building locally and then just copying over the public and executable files.

This doesn't provide much safety over just building and testing via `calypso.localhost:3000`, does it?

The advantage of Docker is the consistent, reproducible, reliable, production-environment-like builds. And we can make them locally. If we start building locally and copying over, we sacrifice the isolated, consistent, reproducible build environment.

This advantage is weakened by `COPY . /calypso/` as local environment easliy leaks in, but that can be mitigated by explicit `COPY ./client ./server ./build […] /calypso/`.

**Comment by sirreal** [comment]
Closing in favor of #20004, we do not need any cleaning before building docker images.

**Pull request closed without merging**
