### PR TITLE
IE/Edge fix for React15 onChange error.

### PR DESCRIPTION
**Pull request by budzanowski**
This uses onInput instead of onChange. This is temporary until
next version of React will fix this. It "should" not make a difference in Search scenarios
but there is no guarantee. Without this in some cases there is a race condition that makes onChange fire up in wrong moment and it returns previous string from input.

Test:
1. open `/design`using IE11 in wpcalypso - it has Suggestions module connected to Search using onChange
2. start typing in ThemesSearch input - keys, some of them or even all are lost.
3. open `/design` on this branch
4. start typing - it works

### CODE REVIEW

**Comment by folletto** [comment]
Can you add testing instructions? :)

**Comment by budzanowski** [comment]
Instructions added.

**Comment by folletto** [comment]
Tested on IE11, Edge — the problem seems resolved 👍  

Cross checked on Chrome to see if there are no regressions too, all good.

**Comment by lancewillett** [comment]
@budzanowski Any reason not to merge this fix? Seems abandoned since end October.

**Comment by budzanowski** [comment]
@lancewillett  Same answer as https://github.com/Automattic/wp-calypso/pull/8900#issuecomment-270245564 - just no capacity to tie up loose ends :/

**Pull request merged**
