### PR TITLE
Adjust jetpack connect screen for wpcom migration plugin case

### PR DESCRIPTION
**Pull request by bogiii**
Related to #76331

## Proposed Changes

* Adjusted jetpack connect screen for wpcom migration plugin case

Markup on 2023-05-09 at 00:09:44

Screenshot 2023-05-10 at 16 27 53

## Testing Instructions

* Create a `jurassic ninja` website with the installed `Move to WordPress.com` plugin
* Click on "Get Started" button
* Replace `wordpress.com` with `http://calypso.localhost:3000/` if you are testing it locally
* or replace it with the live link domain
* Check the new adapted design of the authorization screen
* Click on `Sign in as a different user`
* Check if the new adapted design of the login screen (without Jetpack branding)

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

**Review by ouikhuan — APPROVED** [review]
LGTM!

**Comment by ouikhuan** [comment]
@bogiii , this looks great! But when I click `Sign in as a different user` it shows the Jetpack branding again, will you solve this in the same PR? Or you'll create another one to address this? I think we can check the link and make sure it's pointing to `log-in` and not `log-in/jetpack`.

**Comment by bogiii** [comment]
> will you solve this in the same PR?

Yes, I will.
I've prepared this PR, so Javier can review it as soon as possible since we did not match the proposed design 1 to 1.

**Review by ouikhuan — COMMENTED** [review]
Out of curiosity, shouldn't we re-use `/log-in` here instead of tweaking `/log-in/jetpack` when click on `Sign in as a different user` ? Or is there any other reason we're not using it in this case?

**Comment by vishnugopal** [comment]
We discussed this during the team call and we thought we shouldn't tweak anything in the main `/log-in` page. 

Pinging @javierarce for a review.

**Comment by javierarce** [comment]
This looks good to me, nice work! 

I have just a couple of small comments:

- Could we set the color of the "By connecting your site, you agree to share details between WordPress.com" line to Gray 50.
- `.jetpack-connect__logged-in-form-user-text` has an extra bottom margin of 1.5em that we could remove.

And I have a question: does this PR modifies this screen too?


Screenshot 2023-05-12 at 10 45 42

**Comment by javierarce** [comment]
And I just found a minor thing. This is barely noticeable, but there's a horizontal white line under the main box (if you manually set a darker color is easier to spot):

Screenshot 2023-05-12 at 11 19 04

I think it's because of this CSS:

`.logged-out-form__links::before {
    content: "";
    display: block;
    width: 80px;
    background: rgba(var(--color-surface-rgb), 0.3);
    height: 2px;
    margin: 0 auto 8px;
}`

**Comment by javierarce** [comment]
> And I have a question: does this PR modifies this screen too?

@bogiii confirmed this to me. I think we should try to get as closer as we can to https://wordpress.com/log-in. I think just by tweaking the background color, the text color, and bringing back the OR divider we could be there.

**Comment by bogiii** [comment]
Feedback resolved:

Markup on 2023-05-18 at 00:09:07

Screenshot 2023-05-18 at 09 59 35

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/7996268

Thank you @bogiii for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/7996268).

**Pull request merged**
