### PR TITLE
Gutenboarding: Use Card and CardMedia from @wordpress/components

### PR DESCRIPTION
**Pull request by ockham**
#### Changes proposed in this Pull Request

and remove local copy of Card component.

PR based on #38554. Rebase branch (and base PR on `master`) once that PR has been merged.

#### Testing instructions

Verify that Gutenboarding still works.

### CODE REVIEW

**Comment by ockham** [comment]
The TypeScript check is currently failing since this also needs an update of `@types/wordpress__components` (to include `Card`, `CardMedia`, and friends) -- possibly upstream.

**Comment by ockham** [comment]
> types/wordpress__components

Just checked https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/wordpress__components/, and nope, `card` ain't there. Nor could I find a PR or issue.

Do we have infrastructure in Gutenberg in place already that produces typedefs for us? Haven't kept track lately :grimacing: /cc @sirreal @gziolo @aduth

**Comment by ockham** [comment]
> Do we have infrastructure in Gutenberg in place already that produces typedefs for us? Haven't kept track lately  /cc @sirreal @gziolo @aduth

Ah here: https://github.com/WordPress/gutenberg/pull/18942.

**Comment by ockham** [comment]
Adding type defs for `Card` here: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/41448 (WIP)

**Comment by sirreal** [comment]
Rebased and pushed an improvement to align with types in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/41448

**Comment by sirreal** [comment]
Rebased

**Comment by sirreal** [comment]
Rebased

**Comment by sirreal** [comment]
With merge/rebase/auto-closing/changing target branch, this got into a state where I couldn't open or change the base branch…

I've move it to a new PR: #38802

**Pull request closed without merging**
