### PR TITLE
PrivacyPolicy: enable in stage

### PR DESCRIPTION
**Pull request by retrofox**
This patch just enables the privacy policy banner on stage environment.

### CODE REVIEW

**Comment by gwwar** [comment]
Did you already enable on wpcalypso and horizon?

**Comment by retrofox** [comment]
> > Did you already enable on wpcalypso and horizon?
> Seems like that's not the case. @retrofox can we enable this in other environments up to stage too?

Yes, for sure.

**Comment by retrofox** [comment]
@gwwar @vindl added horizon and wpcalypso. Sorry, I've rebased the branch :-/.

**Comment by gwwar** [comment]
Next time, please add testing instructions for folks on what to expect. In this case I happened to review your other PRs as well ;)

**Pull request merged**
