### PR TITLE
Marketplace Install Dialog: Update error messages

### LINKED ISSUE #68363: Improve the error messages at the modal
Improve the error messages at the modal:

Screen Shot 2022-09-27 at 20 27 06

### Requirements

- [ ] It should follow the design
- [ ] When we have errors that disable the CTA button, we should hide the warning messages (to avoid too much information on the screen)

Context: pdh6GB-26h-p2
Figma: HOg65lHD0QOfaq0QtzKQbC-fi-1183%3A11200

### PR DESCRIPTION
**Pull request by lupus2k**
#### Proposed Changes

* Improve the error messages at the modal

#### Testing Instructions

1. Using a non-business site or a business site without domain change (still using .wordpress.com as domain)
2. Try to install a paid plugin you should see a dialog as in [after screenshot](https://user-images.githubusercontent.com/402286/192870506-3e789026-6680-4f5f-bd58-a0e46dbddbe0.png)

| Before | After |
| --- | --- |
| image | image |

#### Acceptance criteria
- [x] It should follow the design
- [ ] When we have errors that disable the CTA button, we should hide the warning messages (to avoid too much information on the screen)

#### Pre-merge Checklist

- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?

Fixes #68363

### CODE REVIEW

**Comment by lupus2k** [comment]
About `When we have errors that disable the CTA button, we should hide the warning messages (to avoid too much information on the screen)`
This already happens because the warning message is already a "fake message"

image

**Comment by lsl** [comment]
Moved css to cta button so it only modifies the modal and not the other use cases. (We have no designed changes for these yet)

Screenshot 2022-09-29 at 16-57-49 Bussiness Simple — WordPress com

Screenshot 2022-09-29 at 16-58-19 MailPoet – emails and newsletters in WordPress Plugin ‹ Bussiness Simple — WordPress com


> About When we have errors that disable the CTA button, we should hide the warning messages (to avoid too much information on the screen) This already happens because the warning message is already a "fake message"

The EligibilityWarnings component renders three sections:

- Blocking Holds (notice banner / alerts + grey out / opacity drop)
- Holds (to continue you need to do ... )
- Warnings (e.g. domain changes)

The eligibility endpoint is returning two types of warnings:

- Holds - these are things that prevent an simple => atomic transfer from working (e.g. missing business plan or not being the right user role)
- Warnings - these are things that do not prevent a transfer but should be highlighted to the user (e.g. domain will change or widgets won't be available)

Blocking holds are just holds that need alerts to be shown. I think when a blocking hold is the only hold, we end up with this weird looking output:

Screenshot 2022-09-28 at 18-48-07 MailPoet – emails and newsletters in WordPress Plugin ‹ Bussiness Simple — WordPress com

I think this is due to some filtering out so we only show the hold once?

When there are other holds we see more here:

Screenshot 2022-09-29 at 17-07-09 MailPoet – emails and newsletters in WordPress Plugin ‹ Bussiness Simple — WordPress com

But due to [this line](https://github.com/Automattic/wp-calypso/blob/70b266d3a45a67bedc5763b6643affd664292e5d/client/blocks/eligibility-warnings/index.tsx#L85), we check for any blocking holds (alert notices) and warnings are hidden.

If there are both non blocking holds and warnings, we get this output:

Screenshot 2022-09-29 at 17-09-34 MailPoet – emails and newsletters in WordPress Plugin ‹ Bussiness Simple — WordPress com

Which I think is what the original requirement refers to, hiding warnings when any holds are shown. In other words, changing [this line](https://github.com/Automattic/wp-calypso/blob/70b266d3a45a67bedc5763b6643affd664292e5d/client/blocks/eligibility-warnings/index.tsx#L85):

```diff
-	const showWarnings = warnings.length > 0 && ! hasBlockingHold( listHolds );
+	const showWarnings = warnings.length > 0 && listHolds.length === 0;
```

Also worth pointing out:

The design over in https://github.com/Automattic/wp-calypso/issues/68250 has both holds, blocking holds, and warnings all displayed in the same warning section list. The only thing a hold (or blocking hold) will change is the disabling of the proceed button. i.e. no more alert notices to show or text grey out to worry about.

It might be worth just skipping this for now and focusing on https://github.com/Automattic/wp-calypso/issues/68250 which should hopefully remove some of this complexity.

**Review by lsl — APPROVED** [review]
LGTM

**Review by candy02058912 — APPROVED** [review]
LGTM 👍

**Review by paulopmt1 — APPROVED** [review]
LGTM, good job!

**Pull request merged**
