### PR TITLE
Sign Up: Paid only plans step merged into the plans step

### PR DESCRIPTION
**Pull request by rodrigoi**
Since the plans step is back and now knows whether to show or hide the _Free Plan_, this component is redundant and can be removed.

Related: https://github.com/Automattic/wp-calypso/pull/5929

Test live: https://calypso.live/?branch=update/signup-select-plan-cleanup

cc: @apeatling @umurkontaci

### CODE REVIEW

**Comment by gwwar** [comment]
Let's 🚢 after a rebase

**Comment by lancewillett** [comment]
Hi @rodrigoi — was this one merged?

**Comment by lancewillett** [comment]
Re-ping @rodrigoi

**Comment by rodrigoi** [comment]
@lancewillett not merged yet. Will rebase and retest today, and merge if everything works fine.

**Pull request merged**
