### PR TITLE
Framework: use gridicons package

### PR DESCRIPTION
**Pull request by gwwar**
Instead of manually copying from https://github.com/Automattic/gridicons this PR pairs with https://github.com/Automattic/gridicons/pull/188 to use it as an external dependency.

There are no functional changes to usage, but gridicons expects React to be available as a peer dependency

### Testing Instructions
- No functional changes
- Gridicons should appear correctly in http://calypso.localhost:3000/devdocs/design/gridicons
- Gridicons is used heavily throughout the code base so please be on the lookout for missing or strange looking icons.

### CODE REVIEW

**Comment by aduth** [comment]
I might have mentioned this in the previous social logos revisions, but... what are the steps we would need to take for our icons to be tree-shakeable? In other words, how can we ensure we're only including the icons we're using in the respective bundles? Is this something we care to pursue? 

I have a feeling it would require us to at least change the import syntax to not import the default, but rather the specific icons used:

```js
import { PencilIcon } from 'gridicons';
```

**Comment by gwwar** [comment]
> but... what are the steps we would need to take for our icons to be tree-shakeable?

In the gridicons project, I'd we think we'd need to update the generation of the component files to export as individual components in their own files. Then maybe create another babel transform plugin so we can do:
```javascript
import { PencilIcon } from 'gridicons';
```

instead of
```javascript
import PencilIcon from 'gridicons/pencilicon';
```

I'd think it'd be good to follow up on, though I'd like to do that outside of this PR.

**Comment by gwwar** [comment]
As is we'll get a minor decrease in size moving from components to node_modules in the production bundle:
screen shot 2017-01-18 at 2 28 42 pm

screen shot 2017-01-18 at 2 32 30 pm

**Comment by gwwar** [comment]
Just a moment, I'll back out the inline fill rule. It looks like the specificity is too high for Calypso styles.

**Comment by gwwar** [comment]
Styles should be correct now.

**Comment by blowery** [comment]
@gwwar are you using the unlanded variant of `analyze-bundles` that included minimization via webpack? If not, the sizes you're seeing are comparisons of the unminified bundles, which can be a bit misleading.

See https://github.com/Automattic/wp-calypso/pull/10634

Thanks for taking this on!

**Comment by gwwar** [comment]
> are you using the unlanded variant of analyze-bundles that included minimization via webpack?

Just the existing one. I can try again with that patch

**Comment by aduth** [comment]
A remaining reference to legacy file no longer present: https://github.com/Automattic/wp-calypso/blob/70d5dc30/Makefile#L128

If we're treating Gridicon as an external dependency, do styles overriding its defaults belong at `client/components/gridicon/style.scss`? Especially odd because it's the only file in that directory. I might imagine some vendor-specific overrides file/folder in `assets/stylesheets`.

**Comment by gwwar** [comment]
Maybe add `assets/stylesheets/vendor-overrides.scss` then?

**Comment by aduth** [comment]
Yeah, that or even simpler as `assets/stylesheets/vendor.scss` if it's clear enough (maybe even move some of our [existing vendor imports](https://github.com/Automattic/wp-calypso/blob/42a1532f6053e85d6f07a11ba3f7ec54fabf66cd/assets/stylesheets/style.scss#L1-L3) there). Doubtful we'll have too many styles there, but if there's a scalability concern, could even extend to `assets/stylesheets/vendor/gridicon.scss` ?

**Comment by gwwar** [comment]
Thanks @aduth I've updated that in fc6406d. It looks much tidier now. I also moved the dangling social-icon styles as well.

**Pull request merged**
