### PR TITLE
Remove current theme section.

### PR DESCRIPTION
**Pull request by mendezcode**
This PR removes the "Current Theme Section" in Calypso,  seen below:

screen shot 2018-04-03 at 6 13 42 pm

- - -

This has been proposed by @mapk in #23694.

The Current Theme UI is shown for both WPCOM sites, as well as Jetpack sites. Therefore, I would appreciate some help with the review from some of the following superstars,  to get this shipped:

Design: @mapk @kjellr 
Code: @ockham 
Jetpack Testing: @zinigor 
Extra Testing: @lancewillett 

- - -

### Test Instructions

1) Open _My Sites > Themes_ with both WPCOM and Jetpack sites.
2) Make sure everything works as expected without the _Current Theme UI_.

- - -

Thank you all for your help in advance, let's get this rolling!

### CODE REVIEW

**Comment by mapk** [comment]
The "Current Theme" bar is indeed gone! Awesome. But the active theme also needs to be highlighted and in the first position of the grid as well. I double checked one of my sites, and the current theme in the grid is not highlighted. I outlined it in red. Maybe some styling got lost in the deletion of the Current Theme section?

wordpress themes walking without rhythm wordpress com

These two changes should probably happen within the same PR because I don't think we can get rid of one without making the other more obvious. It should look like this still (but positioned to the first spot in the grid)

1wordpress themes walking without rhythm wordpress com


Also, on a side note, let's make sure we AB test this.

**Comment by mendezcode** [comment]
@mapk Oh right, I didn't actually notice the active theme style, was focused on the removal of the UI instead of the rest of the elements.

On the upcoming changes, I will:

1) Make sure the active theme is highlighted
2) Put the A/B testing code in place

Thanks for the input!

**Comment by scruffian** [comment]
One concern with this change is that it removes a big link to the customizer. Is there another way to surface that, as it already feels like its too hard to find?

**Comment by ockham** [comment]
> One concern with this change is that it removes a big link to the customizer. Is there another way to surface that, as it already feels like its too hard to find?

(Same for the support docs links, i.e. 'Info' and 'Setup'.)

Another UX concern I've heard brought up: If a user searches for a string or activates a filter and the results list doesn't include the currently active theme, there won't be any visual indication of what their current theme is -- unless we forcibly keep it around, but that might be confusing as well.

I realize we want to cut down on banners and boxes, just stating these concerns here to make sure we're aware of the consequences of removing one of the IMO more informative ones.

**Comment by ockham** [comment]
If we're positive we want to go ahead with this, I'd strongly suggest to prepare a separate PR first that takes care of moving the currently active theme to the first position in the results list, as that change is a) orthogonal to _this_ PR, and b) probably non-trivial -- and thus deserving of a separate one 🙂

**Comment by budzanowski** [comment]
Pushing current theme to the first position will probably require modifying how view interacts with query manager and prepares the themes list for display. It may also interfere with the mechanism for fetching next themes set. So :+1: for additional PR that @ockham suggests.

**Comment by kjellr** [comment]
> One concern with this change is that it removes a big link to the customizer. Is there another way to surface that, as it already feels like its too hard to find?
> (Same for the support docs links, i.e. 'Info' and 'Setup'.)

Agreed on those points — we should figure out another solution for those before removing this altogether. Regarding the Customizer button, it's worth noting PR #22959, which would potentially move to put that link in a more prominent place globally. 

---

A small bug I noticed in this PR: The margin is missing in between the showcase banner and the search bar: 

screen shot 2018-04-04 at 9 49 14 am

**Comment by mendezcode** [comment]
> If we're positive we want to go ahead with this, I'd strongly suggest to prepare a separate PR first that takes care of moving the currently active theme to the first position in the results list, as that change is a) orthogonal to this PR, and b) probably non-trivial -- and thus deserving of a separate one 

@ockham: Agreed, this makes sense. I think while things are figured out on the design world, I can get to work with this PR to get it rolling, and by the time it ships, we can now proceed and iterate with the removal of the current theme UI.

@budzanowski: Good point about the internals of the theme showcase items, thanks!

@kjellr: Thanks for spotting the issue with the banner margin, I'll fix this, thanks!

- - - 

Next steps are:

1) Work with PR to make sure active theme is displayed as first in the showcase.
2) Figure out UI to make sure we keep the buttons for the Customizer, as well as Info & Support. I'll leave that to you @mapk and @kjellr
3) Proceed with the banner removal PR.

**Comment by mapk** [comment]
> One concern with this change is that it removes a big link to the customizer. Is there another way to surface that, as it already feels like its too hard to find?

> (Same for the support docs links, i.e. 'Info' and 'Setup'.)

Based on this HE video by @samjhamdy, it appears that customers don't notice those buttons, or at least don't click on them for reasons.  https://cloudup.com/cUdNfel3hXz Is that fair to say, @samjhamdy? 

> If a user searches for a string or activates a filter and the results list doesn't include the currently active theme, there won't be any visual indication of what their current theme is -- unless we forcibly keep it around, but that might be confusing as well.

Excellent point. My initial thought was to keep it in place at all times, but you're right, that could be confusing as well. Let's think on this some more. 

Do we need multiple ways to click to the Customizer (ie. sidebar button, and button in main view)? 
Does the "Current Theme" need to be its own bar?

Perhaps the fact that its a "bar" makes it less noticeable because it blends with everything else in the Showcase right now. Hierarchy of elements seems to be missing. 

And there's just too many buttons styles going on.
screen shot 2018-04-04 at 10 56 13 am


@kjellr and anyone else, thoughts on this?

**Comment by kjellr** [comment]
> it appears that customers don't notice those buttons, or at least don't click on them for reasons.

That may be true, but we should also weigh that against the volume of user support requests from users that could be solved if they _could_ find those buttons. Do we hear from a lot of users who don't know where to find the Customizer? Maybe not. But do we hear from a lot of users who can't find the Info/Setup pages? I don't know for sure, but my gut says yes. 🙂 

> Perhaps the fact that its a "bar" makes it less noticeable because it blends with everything else in the Showcase right now. Hierarchy of elements seems to be missing.

Yeah — I  think it's worth exploring an alternate solution that doesn't hide this bar entirely, but rethinks that top area so that it's more prominent. Maybe it introduces more whitespace? More type hierarchy? I shared a related note [over on the original issue](https://github.com/Automattic/wp-calypso/issues/23694#issuecomment-378608827).

**Comment by mendezcode** [comment]
This PR is going to require some more design work and thinking. Closing this for now until we reach to a working point on this.

**Pull request closed without merging**
