### PR TITLE
Sites: request only the fields we are consuming.

### PR DESCRIPTION
**Pull request by mtias**
This reduces the processing time of `/me/sites` significantly as well as reducing the overall data weight we incur and store.

### Needs further testing as it's very likely missing other attributes we rely on.

Also, we should take a deeper look at things we added for convenience that only affect an individual section or feature of Calypso. What we load with `/me/sites` should be only the critical bits for structural navigation and site handling.

- Can we clean up the `seo` related attributes and request them on demand? @dmsnell 
- Can we reduce the `plan` object to its barest minimum? @artpi @gwwar 
- Can we request `allowed_file_types` on demand for media need? @aduth @rralian 
- Can we have a single object for Jetpack modules? @lezama @johnHackworth 
- Can we move `software_version` check to a specific settings request in "plugins"? @oskosk @johnHackworth 
- Can we request `default_post_format` and friends separately for the editor? @aduth @timmyc 
- Do we need `publicize_permanently_disabled`?
- Can we move `podcasting_archive` elsewhere? @youknowriad

### CODE REVIEW

**Comment by rralian** [comment]
I'm really glad to see you're working on this. I've been thinking about this too, but I would come at this a bit differently.

Our problem stems from using `/me/sites` as the source of truth for all site information. So whenever we needed more data, we added it to the `/me/sites` response. But for 99% of that extra info, we only need it for the currently active site in order to render the page.

I suggest we strip down `/me/sites` to contain only the data necessary to build the site-switcher. I would actually make this the next version of that endpoint rather than using the "field" parameter, so we strictly enforce this pattern and idea. We separate the storage of this data completely from the storage of full `:site` objects used to render a page. This should never be used to populate anything outside of the switcher.

And we issue a second request to the `/sites/:site` endpoint on any page with `:site` in the URL to get the full `:site` object. This becomes the source of truth for site data to render our pages.

If `/me/sites` responds with some small number of sites (say, five or less), we can optimistically request the site data for unselected sites as well in order to make site-switching immediate. Or we can optimistically request the last five selected sites. And if it's more, that's fine... the `/sites/:site` endpoint is pretty fast, around ~200ms in my testing.

I think this would give us the fastest time-to-render without having to rewrite our data needs for sites.

**Comment by mtias** [comment]
I thought about that but I see several problems with it, outside of increasing network requests a fair bit. The current setup is the ideal for users with less than ten sites between data requested and network requests, and I don't think we should disrupt that.

> I suggest we strip down /me/sites to contain only the data necessary to build the site-switcher.

The amount of data needed is not trivial—we need several attributes to handle conflicts, domain, permissions, visibility, etc, which is basically what my query above looks like outside of the items listed to be fixed.

> We separate the storage of this data completely from the storage of full :site objects used to render a page.

This doesn't solve the problem of us storing a bunch of data in the tree for a site that we don't need nor use (a lot of what is returned for a site object is not relevant to us). So we still need to use the `fields` query string and clean up the above items. Using the fields also means we are _expressing_ what we need instead of implicitly relying on the shape of an API endpoint outside of the client control. This is a good thing and puts us in a path towards more independence from the API, which would help if we plan to move towards a graphql-like interface.

That is to say, I could still see us having a direct site request triggered in parallel for a `:site` route just to optimize that initial render. But I'd still do it through `/me/sites` and with fields, and still trigger an all-sites request at the same time. In any case, the least disruptive step is to utilize fields and options arguments and see how much we improve. The fact it'd also clean up some of the convenience dependencies we have introduced is an added bonus.

**Comment by dmsnell** [comment]
> Can we clean up the seo related attributes and request them on demand?

@mtias doesn't seem like it would be a problem, even if all we did were to create a new endpoint. I don't think we need any of that information until we navigate to **Settings** > **Traffic**

**Comment by johnHackworth** [comment]
> Can we move software_version check to a specific settings request in "plugins"? @oskosk @johnHackworth

I guess there's no reason to not do it like that... what's the plan here? Should we create issues for this changes or do you want them to be implemented over this branch?

**Comment by mtias** [comment]
Doing a separate PR for not relying on `software_version` would be good.

**Comment by gwwar** [comment]
@alisterscott @hoverduck would it be possible to run e2e tests to see if anything is breaking in this branch?

**Comment by gwwar** [comment]
Thanks @hoverduck!

**Comment by aduth** [comment]
What was the methodology used for deciding which fields are to be included here?

**Comment by dmsnell** [comment]
Related exploration on declarative explicit data models in Calypso at #14595

**Comment by hoverduck** [comment]
@gwwar / @mtias - I tried running the e2e tests against this branch, but I'm away from my main laptop and am running into lots of network issues trying to get them to run remotely.  But from the runs I was able to complete I saw a lot of failures....but couldn't troubleshoot them to see whether they were real problems or just due to my connection.

**Comment by mtias** [comment]
@aduth what is currently in use. The first goal is to only request what we are using, the next step is trying to lower the amount of things we need.

**Comment by aduth** [comment]
>what is currently in use

What I mean is how did you determine what it is we're using?

**Comment by mtias** [comment]
Combination of navigating around and searching for attributes. I'm missing stuff, which is why I want to see what the e2e tests can surface.

**Comment by artpi** [comment]
I honestly don't see how we can make `plan` object leaner.
We can of course, get stuff like `id` out of the way, but stuff like:
- `expired `
- `plan_slug`
Is necessary to calculate various features everywhere in calypso and waiting everywhere to know if user has access to specific features will be much more terrible in terms of performance.

Since we stopped giving out free trials, we could get rid of `free_trial ` I guess.

We need fast and reliable way to know what features user has active and what to nudge him about.

**Comment by aduth** [comment]
We should probably update the sites state schema to include only the fields here.

This has a dual effect of preventing additional keys from being included in state:

https://github.com/Automattic/wp-calypso/blob/42f7dc7/client/state/sites/reducer.js#L42-L47

**Comment by mtias** [comment]
> This has a dual effect of preventing additional keys from being included in state.

I don't think this is enabled for the actual attributes.

**Comment by gwwar** [comment]
> I don't think this is enabled for the actual attributes.

The sites tree is a special case. We pick from the keys listed in the schema only in this reducer. This was done before because we were receiving sites with computed properties from the sites list.

https://github.com/Automattic/wp-calypso/blob/42f7dc7/client/state/sites/reducer.js#L88

**Comment by hoverduck** [comment]
@gwwar / @mtias - I was finally able to run the e2e tests against this branch and came back with no issues

**Comment by gwwar** [comment]
Thanks @hoverduck !

**Comment by dbspringer** [comment]
Howdy @mtias, it appears your update has killed the site.options.wordads field that Ads needs for its various Calypso bits. Is there any chance we can get that back in there?

**Pull request merged**
