### PR TITLE
Anchor: Show 3 grid columns for onboarding designs at xlarge screen sizes

### PR DESCRIPTION
**Pull request by allilevine**
#### Changes proposed in this Pull Request

* Changes the Anchor onboarding design grid to display three grid columns at xlarge screen sizes (1080px and wider)
* This is a change to the shared `DesignPicker` component but currently the `isGridMinimal` prop that triggers these styles is only used by Anchor.

Before | After
------- | -----
Screen Shot 2021-04-07 at 11 30 57 AM | Screen Shot 2021-03-26 at 5 37 50 PM

#### Testing instructions

* Start the Anchor onboarding flow (/new?anchor_podcast=40a166a8)
* View the columns on the design select step

Related to #

### CODE REVIEW

**Comment by pablinos** [comment]
I tried to resolve the conflict with this, but it looks like the grid layout has gone through a big refactor, and I wasn't able to quickly see what the equivalent change is.

**Comment by allilevine** [comment]
> I tried to resolve the conflict with this, but it looks like the grid layout has gone through a big refactor, and I wasn't able to quickly see what the equivalent change is.

Thanks! I'll take a look.

**Comment by allilevine** [comment]
> > I tried to resolve the conflict with this, but it looks like the grid layout has gone through a big refactor, and I wasn't able to quickly see what the equivalent change is.
> 
> Thanks! I'll take a look.

The styles were moved to a new component. I rebased and added the change there.

**Review by ollierozdarz — APPROVED** [review]
The visual change looks good to me.

**Comment by simison** [comment]
> component but currently the isGridMinimal prop that triggers these styles is only used by Anchor.

Instead of being Anchor specific, should we just do this any time there is X number of designs? (e.g. up to 4 or 6)

That way we'd have same treatment for (currently internal) FSE flow: 

image

Note that we're also looking into making these screenshots taller again, which would likely impact how this works visually: https://github.com/Automattic/wp-calypso/pull/51261#issuecomment-810859671 cc @deBhal @autumnfjeld 

Also don't let this hold from merging, just food for thought! :-)

**Review by ghost — APPROVED** [review]
Looks good!

**Comment by allilevine** [comment]
Merged, thanks all!

> Instead of being Anchor specific, should we just do this any time there is X number of designs? (e.g. up to 4 or 6)

That makes sense! Opened a follow-up issue here: https://github.com/Automattic/wp-calypso/issues/51816

**Pull request merged**
