### PR TITLE
Domains: Make "show more results" a button on domain search

### LINKED ISSUE #32516: Domains: While searching for domains, "show more" should be a button
Screen_Shot_2019-03-06_at_10 40 10_AM

"Show more results" should look like a standard button, either a text or contained button. If it remains a text button, it should probably be a color.

### PR DESCRIPTION
**Pull request by danhauk**
#### Changes proposed in this Pull Request

* Change "Show more results" on domain search to use a proper button component

image

#### Testing instructions

* Start from http://calypso.localhost:3000/domains/add/
* Select a site
* Search for a domain
* Confirm the "Show more results button looks ok
* Confirm the button works as expected and shows more results when clicked

Fixes #32516

### CODE REVIEW

**Comment by danhauk** [comment]
@drw158 Do you think the button should be `--color-accent`? It's mentioned on #32516 that it should be a color. I'm using `--color-primary` here. I'm not sure the accent color would look best since this action is of low importance, but interested to hear your thoughts.

**Comment by drw158** [comment]
Hm, this is a hard one since it breaks our "system" for color. I suppose it's ok to have several pink text buttons even if they are not that important. I think keeping them blue is good for now. Thanks for the ping.

**Comment by scruffian** [comment]
I noticed another issue:
Screenshot 2019-04-24 at 12 58 04

This wasn't an issue before. I'll add a fix if I can find one...

**Comment by scruffian** [comment]
Actually this is more complex than I had anticipated. This is what the loading state looks like right now:
domainsnow

I think it would be better to use a busy button here, but that means not using a borderless button, like this:
domains

Thoughts?

**Comment by danhauk** [comment]
The busy state button could work. It also removes the need for the CSS show/hide of the spinner which is a bonus. My only concern with using a regular outlined button is there's already so many on the screen, but that's just a personal preference.

**Comment by drw158** [comment]
In this case I think using a outlined button is ok (in an effort to fix this issue and make the code cleaner).

**Comment by sixhours** [comment]
In testing this, I found a weird bug where, if you hover directly over the text of the button, you can't click it:

Screen Shot 2019-04-24 at 3 34 20 PM

The cursor becomes an arrow rather than a hand. You have to click *around* the text somewhere for it to activate.

This doesn't happen on master, and seems to be a side effect of this branch.

**Comment by scruffian** [comment]
> if you hover directly over the text of the button, you can't click it:

That's the thing I was referring to very poorly here: https://github.com/Automattic/wp-calypso/pull/32536#issuecomment-486198806

**Comment by danhauk** [comment]
I pushed up some changes to make it an outlined button and use the busy state. Seems to also fix the hover/click bug reported above

image

**Comment by sixhours** [comment]
This iteration works much better! 👍

**Comment by scruffian** [comment]
Simplicity FTW 🚢

**Pull request merged**
