### PR TITLE
Reader: should not serialize queued requests

### PR DESCRIPTION
**Pull request by samouri**
~~This component currently uses the deprecated SiteStore. This PR seeks to move it off of SiteStore and onto redux via `connect`.~~

~~I also removed a needless call to bindActionReducer.~~

Along the way I found a bug in sites reducer where we are saving queued requests (meant it was easy to get in a state where a site would never be requested)

### CODE REVIEW

**Comment by bluefuton** [comment]
Looks like the only place we use this is in x-posts. Perhaps we could switch that to use the `ReaderAvatar` block instead?

**Comment by samouri** [comment]
I'll check if its a drop-in replacement

**Comment by bluefuton** [comment]
Trying to switch to ReaderAvatar in #12459 so we can ditch this component completely.

**Comment by samouri** [comment]
🐰 🕳 🥇

**Comment by bluefuton** [comment]
@samouri if we close this out in favour of #12459, is there anything in this PR we want to keep?

**Comment by samouri** [comment]
we can change it to deleting everything instead :)

**Pull request merged**
