### PR TITLE
Domains: improve transfer-desired-when-cancel verification copy

### LINKED ISSUE #17124: .fr: Update confirm-cancel-domain for non-ICANN domains
The text on the confirm cancel screen is incorrect for .fr domains. It's not clear whether .FR domains prevent transfers inside 60 days, but they are definitely not bound by ICANN.

purchases_ _cancel_domain_ _wordpress_com

### PR DESCRIPTION
**Pull request by hewsut**
screen shot 2017-08-14 at 4 15 50 pm

Link leads to: https://support.wordpress.com/transfer-domain-registration

Fixes #17124

### CODE REVIEW

**Comment by klimeryk** [comment]
Nice catch! cc'ing @ranh for copy check, however since the wording "causes the domain to become available for general purchase, possibly resulting in its loss" could be a bit ambiguous IMHO. It's hard to shortly describe that "yes, you may cancel the domain, it will become available for purchase again... but at a window of time in the future, not sure precisely when - and there's no guarantee you'll be the first one to re-register it since there are bots and people automatically registering such domains to get you to pay to get them back.... so tread carefully".

**Comment by deBhal** [comment]
It looks good, and is a vast improvement for a domain like .fr where you can transfer immediately, but I'm not sure that the copy is quite that easy.

Most of our customers are going to have bought a .com, and if they understand enough of the docs to get to `transfer/out`, they'll be looking at roughly the same message there that we're trying to improve here:
transfer_domain_ _julesauspremiumtest_ _wordpress_com

What actually happens when you cancel a domains? It depends on the domain, right? For some tlds, it won't be available for the whole year after cancelling, so at least for them it won't become available for a long time.

So for something generic, we need to allude to the dangers, but be very ambiguous about how long the domain will be unavailable for, and how long you might need to wait to transfer. As a rough draft, maybe something like "Canceling a domain name causes the domain to become unavailable for a period of time. Afterward, anyone can repurchase, which might result in it's permanent loss. It's generally better to <a>transfer</a> the domain to another registrar, even if you need to wait for the domain to be old enough to do so."?

If it's not much work, it seems like a much better experience for the user if we can check here in the the page and give them the information they need - if the domain is too new to transfer, tell them how long they need to wait, and if the domain is old enough, send them directly to the transfer out page (which also has a link to the docs).

**Comment by hewsut** [comment]
> Most of our customers are going to have bought a .com, and if they understand enough of the docs to get to transfer/out, they'll be looking at roughly the same message there that we're trying to improve here

I'm not sure I'm following. You mean that they (may) run into ICANN stuff again? That's ok on the transfer out screen.

> What actually happens when you cancel a domains? It depends on the domain, right? For some tlds, it won't be available for the whole year after cancelling, so at least for them it won't become available for a long time.

> So for something generic, we need to allude to the dangers, but be very ambiguous about how long the domain will be unavailable for, and how long you might need to wait to transfer. As a rough draft, maybe something like "Canceling a domain name causes the domain to become unavailable for a period of time. Afterward, anyone can repurchase, which might result in it's permanent loss. It's generally better to transfer the domain to another registrar, even if you need to wait for the domain to be old enough to do so."?

Yes. That's why I left it "concerning but vague on the details" on this page to be a simple as possible and work for all cases (hopefully?).

> If it's not much work, it seems like a much better experience for the user if we can check here in the the page and give them the information they need

That would indeed be nice but it'd be a lot more work than this. So, for now, I'm angling for this. Another iteration can dynamicize as desired as far as I'm concerned.

**Comment by ranh** [comment]
Thanks for the ping @klimeryk. I agree that "possibly resulting in its loss" is not the most compelling reason for not cancelling a domain.

We usually do say something more general, as @deBhal suggested. For example:

> If you cancel this domain, it may take a long time before it can be purchased again, and someone may purchase it before you get a chance.

I also like to say:

> If you think you may want to use this domain again in the future, don't cancel it."

Or, alternatively:

> Only cancel this domain if you're sure you won't need it again in the future. If you do, it may not be possible to purchase it again, or someone else may purchase it before you.

There's also quite a bit of prior art about this in other messaging related to domain cancellation, as well as in support, predefs etc.

**Comment by hewsut** [comment]
Thanks @ranh. How about this?

screen shot 2017-08-15 at 1 01 16 pm

**Pull request merged**
