### PR TITLE
Dashboard - Ready to promote - Adapt mobile version

### PR DESCRIPTION
**Pull request by ernestoSk13**
Related to #

## Proposed Changes

* In this PR I'm adapting the new mobile layout for the Posts list inside the Advertising section.

m-rtp-dropdown
* Proposed mock from Figma

Note: We are waiting for some feedback on how to display the subtitles in WPCom rows cc @bartoszbak 

### Woo

- [ ] Open a woo store that you have available
- [ ] Navigate to Tools> Advertising
- [ ] Append the flag 'is_running_in_woo_site'
- [ ] Open "Inspect" and then change into a mobile layout
- [ ] Verify it looks similar to the mock above

### WPCom

- [ ] Repeat the same steps above but with a WPCom blog and without the woo flag

## Screenshots

Woo
Screenshot 2024-02-16 at 4 48 42 p m

WPCom
Screenshot 2024-02-16 at 4 49 23 p m

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Review by sbarbosa — COMMENTED** [review]
Hi @ernestoSk13. I found a couple of small design issues to fix:

Screenshot 2024-02-19 at 10 22 16


And also, I noticed that we lost the tooltip with the full title. Maybe we can ask Bart if we could maintain it, or if its Ok to remove it.
Screenshot 2024-02-19 at 10 31 32

**Comment by ernestoSk13** [comment]
@sbarbosa  I've fixed the paddings and the font weight. I'll just wait for @bartoszbak  to check if the tooltips are staying or not :)

**Review by sbarbosa — APPROVED** [review]

**Review by therocket-gr — APPROVED** [review]
tested locally and it LGTM

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/11469916

Some locales (Hebrew, Japanese) have been temporarily machine-translated due to translator availability. All other translations are usually ready within a few days. Untranslated and machine-translated strings will be sent for translation next Monday and are expected to be completed by the following Friday.

Thank you @ernestoSk13 for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/11469916).

**Pull request merged**
