### PR TITLE
Activity Log: update styles for smaller devices

### PR DESCRIPTION
**Pull request by keoshi**
This PR introduces minor changes to how we handle the activity log UI in smaller screen devices.

List of changes:

- Compress the rewind button so we can have smaller day blocks, and dates in a single line.
- Truncate the text of the button so it's much shorter in smaller screens.
- Reorder and tweak styles of activity actor, to present a cleaner event block.
- Minor tweaks to bring all elements together in terms of margins and paddings.

### Before

image

image

### After

image

### How to test

- Go to https://calypso.live/?branch=update/activity-log-mobile-tweaks
- Open Stats > Activity

### CODE REVIEW

**Comment by beaulebens** [comment]
I like the handling of the main body part, but looks like there are some more improvements that could be made here, specifically:

- text wrapping in the rewind button
- placement of the `...` menu (any reason why that shouldn't be further over to the right, giving us some more space for the main content?)

**Comment by keoshi** [comment]
> text wrapping in the rewind button

Not sure what we can do there except for bringing it down into a new row.

> any reason why that shouldn't be further over to the right

The area on the right will have the down facing chevron for expanding each event.

**Comment by folletto** [comment]
@keoshi what if we keep the avatar / name at the top, and align the controls to that, so below the description can go full width? Something like:

screen shot 2017-09-21 at 13 29 22

Would be too annoying when it gets toggled open?

**Comment by rickybanister** [comment]
I think definitely 'outdenting' the text to the left would help, but it perhaps shouldn't interfere with the card actions (ellipsis and chevron) if possible. 

For the rewind button, I'd almost rather have the text truncate to simply 'Rewind' and drop the 'to this day' text. That part will be apparent in the confirmation dialog. 'Undo' is always just 'undo'—the context hopefully can be inferred from the surroundings. 

Could we also shrink the event type icon to the left down a bit—elsewhere in calypso cards are full-screen-width. We could have the day cards be full width and the event cards only have a left margin with the reduced-size icon dots, that would buy us some space.

**Comment by keoshi** [comment]
That's a good proposal, I like it.

I'm wary of getting rid of that right most column for expanding items though, which applies to days and events. Also think the actor is secondary information so it should always follow the item description and not the other way around. Arguably, this is a different paradigm than what we have in desktops, but having the description in the center of the item helps achieving that goal.

**Comment by keoshi** [comment]
@rickybanister Pushed a new commit to truncate the button label which now looks like this:

image

As for the left column it's not the icon that is defining that width, but actually the timestamp. Breaking that into two lines looks very weird, and reducing the font further makes it nearly illegible.

**Comment by rickybanister** [comment]
That makes sense. What about the right margin next to the cards?

**Comment by rickybanister** [comment]
And could we perhaps reduce the chevron size down from what I assume is 24px?

**Comment by keoshi** [comment]
> What about the right margin next to the cards?

Yeah, we can further reduce the margins of the container on both sides.

> reduce the chevron size down from what I assume is 24px

I assume so. Right now what we have is the default foldable card styles.

**Comment by rickybanister** [comment]
I'm still confused by 'reduce' the margins—what I meant to share was there are 0 margins to the left and right of cards in just about all sections of WordPress.com:

image

**Comment by keoshi** [comment]
We're talking about the same thing: we've added those margins to make each block more distinguishable from the next. I don't recall any UI in Calypso that has this constant repetition of similarly styled, small cards, so this extra padding felt important.

**Comment by rickybanister** [comment]
Perhaps the 'day' cards have no margin and the event cards have a very small one to show that you are 'within' a day?

**Comment by keoshi** [comment]
It would look something like this:

image

**Comment by rickybanister** [comment]
I think that works pretty well. We can probably also tighten up the margins left and right of the event icons, at least making those margins match the margin to the right of the event card. We might also be able to slightly reduce the padding inside the cards (as long as we don't deviate too far from the standard).

**Comment by keoshi** [comment]
@rickybanister @jeffgolenski Added a few tweaks, hopefully it looks good right now. Do you mind taking a look and reviewing so we can push live?

**Comment by rickybanister** [comment]
Just tested this, I like the new changes. Ship it.

**Comment by jeffgolenski** [comment]
I agree with ricky!

**Pull request merged**
