### PR TITLE
Domains: Add new "Disconnect" button for domain management pages

### PR DESCRIPTION
**Pull request by rafaelgallani**
Adds a "Disconnect" button to the domain management page - the button should convert a regular domain to a domain-only site:

image

## Testing Instructions
- Click on the "disconnect" button;
- Click on "disconnect" button on the confirmation dialog;
- Ensure that the domain will be converted to a domain-only site and that the navigation looks correct;
- Additionally, ensure that the "disconnect" button/section/card isn't displayed for domain-only sites.

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

**Review by ebinnion — COMMENTED** [review]
This is functional. 💪 

But, it seems really slow. After clicking to disconnect, I had to wait 44 seconds my domain to disconnect.

It might be more ideal if we can async the backend work here and immediately respond to the user that their change will be reflected shortly.

**Comment by ebinnion** [comment]
I'm not sure about showing the user this view and removing all other UI. 

Screenshot 2023-09-13 at 11 58 38 AM

**Comment by delputnam** [comment]
> I'm not sure about showing the user this view and removing all other UI.

@ebinnion  Do you have any other suggestions about what to display there? We could show all of the cards, but disable the ability to make any changes until the flag is removed.

**Comment by delputnam** [comment]
This works, except that once we've disconnected the domain the current URL will never work again.  I can't think of another way to make this work without some significant changes though.

@rafaelgallani Any chance you can think of a way to automatically redirect once the new site/domain data is available?

**Comment by rafaelgallani** [comment]
> This works, except that once we've disconnected the domain the current URL will never work again. I can't think of another way to make this work without some significant changes though.
> 
> @rafaelgallani Any chance you can think of a way to automatically redirect once the new site/domain data is available?

@delputnam The only options I can think of are either removing the `siteSlug` from the route or polling updates on whether the operation is completed - and fetching the site data once it finishes... 

These seem substantially more complicated than what we have on this PR, so I'd say we deploy this one and maybe do some more work on a follow-up PR deciding which of these would suit us best.

**Comment by delputnam** [comment]
@rafaelgallani I think this looks good now.  Using that site-less link is a good approach. 👍

**Review by delputnam — APPROVED** [review]
Looks good.  Let's get this shipped and we can iterate from here.

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/8968085

Thank you @rafaelgallani for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/8968085).

**Pull request merged**
