### PR TITLE
WIP Upgrade @wordpress/edit-site to 4.9.0

### PR DESCRIPTION
**Pull request by arthur791004**
Related to https://github.com/Automattic/wp-calypso/issues/71038, https://github.com/Automattic/wp-calypso/pull/71917

## Proposed Changes

Referring to https://github.com/Automattic/wp-calypso/pull/71917, when we're working on adding the font pairings variations to the site assembler, we need to `"@wordpress/edit-site: ^4.9.0"` and `"@wordpress/blocks: ^11.11.0"` to support changing the font family of the heading via the `elements.heading`. So, this PR proposes to upgrade those 2 packages first

TODOs

- [ ] Fix unit tests

## Testing Instructions

* TBD

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

**Comment by arthur791004** [comment]
@tyxla @noahtallen I'm trying to upgrade both `@wordpress/edit-site` and `@wordpress/blocks` packages to get the latest features, do you have any test cases or instructions to ensure everything works as before? thanks

**Comment by tyxla** [comment]
From my understanding, it's not a good idea to update only package X and Y but keep the other packages behind. Often packages have their interconnected dependencies and using different versions can lead to subtle bugs. That's why I'd recommend upgrading all packages at the same time, and if the upgrade is too big, just do it incrementally and upgrade to an older version for all packages in a single PR. I know it's troublesome, but we're currently quite behind on the `@wordpress` packages since Renovate was disabled over a year ago. 

cc @noahtallen for feedback as well.

**Comment by arthur791004** [comment]
> Often packages have their interconnected dependencies and using different versions can lead to subtle bugs.

Yes, I totally agreed! But I think `@wordpress/edit-site` and `@wordpress/blocks` are not used in calypso widely, so it might be okay to do the partial upgrading 🤔

Or do we have any plans to upgrade `@wordpress` packages?

**Comment by tyxla** [comment]
> Or do we have any plans to upgrade `@wordpress` packages?

Yes, this is something that both @Automattic/team-calypso-platform and @Automattic/team-calypso-frameworks are interested to tackle in the short term.

**Comment by tyxla** [comment]
I've started some early experiments in https://github.com/Automattic/wp-calypso/pull/73155 but they're far from where we should be. I'll continue next week and keep y'all posted.

**Comment by arthur791004** [comment]
That's really nice, thanks 👍

**Comment by tyxla** [comment]
@arthur791004 just a heads up that we're working on the mass `@wordpress` package upgrade in a second approach in #73890.

**Comment by arthur791004** [comment]
@tyxla Thanks for the reminder! I've also noticed that 😆

**Comment by arthur791004** [comment]
Closing it in favor of https://github.com/Automattic/wp-calypso/pull/73890

**Comment by tyxla** [comment]
👍 

Thanks for your testing of #73890 @arthur791004 🙌

**Pull request closed without merging**
