### PR TITLE
Illustrations: Replace "No Sites" drake with new illustration

### LINKED ISSUE #13044: Replace our Drake "No Sites" illustration to new style
We need to update our Drake "No Sites" illustration to match the new WordPress.com illustration style. Used when you have no sites configured and also in the calypso devdocs.

Current:
no-sites-drake

New:
no-sites

### PR DESCRIPTION
**Pull request by drw158**
Wip

fixes #13044

To test, you need an account with no sites. If you are willing to test and don't have an account, message me and I can lend you my test account creds.

Removed `title` because uses of this image are decorative.

Before|After
---|---
screen shot 2017-05-18 at 4 18 29 pm|screen shot 2017-05-18 at 4 15 39 pm

### CODE REVIEW

**Comment by drw158** [comment]
@folletto @kjellr 

Any tips on testing this? I can't seem to get this illustration to show up for me in Calypso.

**Comment by mtias** [comment]
I suggest using this as a component instead of an asset request.

**Comment by drw158** [comment]
White shapes removed, darkened background elements.

**Comment by folletto** [comment]
> I suggest using this as a component instead of an asset request.

What do you mean?

**Comment by folletto** [comment]
> Any tips on testing this? I can't seem to get this illustration to show up for me in Calypso.

Try creating a user-only account: wordpress.com/start/account

**Comment by mtias** [comment]
I mean not doing a network request to get the svg, and just inlining it when rendering.

**Comment by roundhill** [comment]
IE 11 (sidenote: what's up with the left side of the blue button in IE?):

screen shot 2017-05-19 at 4 01 20 pm

**Comment by drw158** [comment]
Weird, no idea. My only guess is because it's not on a whole pixel.

screen shot 2017-05-22 at 10 02 21 am

**Comment by folletto** [comment]
Note that this image should have been placed in `illustrations`, not replacing Drake, as now there's one "drake" image which is not part of the new set.

**Pull request merged**
