### PR TITLE
Backup: Make the storage usage bar more visible/readable

### PR DESCRIPTION
**Pull request by mattgawarecki**
Resolves `1164141197617539-as-1202079046529162`.

I realize this PR could probably be broken up into two (styling in one, refactors in the other), but since the changes are so related, I chose to combine them. If anyone would rather they still be split, let me know and I can try to accommodate.

##### Visual changes

*For reference/source designs, see `XBBg9tWPg31yJZjaYDjetd-fi-1%3A29`.*

* Render storage usage elements vertically on all screen layouts, not just small screens.
* Increase the height of the storage usage progress bar from 9 to 24px, for visibility.
* Change the border radius behavior on the filled portion of the storage usage progress bar (see screenshots).
* Add a link to **Upgrade** backup storage next to the storage usage display text, if an upgrade is possible.
* Decrease font size for text elements surrounding the storage usage progress bar.
* Slightly change storage usage text copy, from `X of Y used` to `X used of Y`.

##### Refactoring

* Create a new selector to get the storage upgrade URL for Jetpack sites, `getJetpackStorageUpgradeUrl`.
* Use the aforementioned selector in all React components that render a link to upgrade a Jetpack site's storage.
* Convert `StorageUsageLevels` from an `enum` to a `const` object and a string-based union type, pursuant to `p7H4VZ-3sK-p2`.
* Remove styling rules from the My Plan storage usage card that are no longer necessary.

#### Testing instructions

***NOTE:** To test thoroughly, go through the following steps on the **Backup** page in both Calypso Blue and Calypso Green, and the **My Plan** page on Calypso Blue. Try sites with various levels of storage usage and availability (i.e., both 10GB and 1TB).*

##### Progress bar: mobile/tablet

Screen Shot 2022-04-12 at 08 01 35 Screen Shot 2022-04-12 at 08 01 17

##### Usage levels: desktop

Screen Shot 2022-04-12 at 08 01 46 Screen Shot 2022-04-13 at 09 25 29
Screen Shot 2022-04-13 at 09 26 16 Screen Shot 2022-04-13 at 09 26 42

##### No upgrade link for 1TB

Screen Shot 2022-04-13 at 09 27 56

##### Usage levels: My Plan

Screen Shot 2022-04-13 at 09 49 18 Screen Shot 2022-04-13 at 09 48 11

### CODE REVIEW

**Comment by grbicsanja** [comment]
It's looking great @mattgawarecki!
The only thing I notice is the color is off on the grey bar, which should be lighter (Gray 0, #F6F7F7).
I wasn't able to check the yellow and red use case (they seem fine, but can't be exactly sure from the screenshots), those should be Red 40 and Yellow 20. The dark grey loader is correct 👌.

**Comment by mattgawarecki** [comment]
> It's looking great @mattgawarecki! The only thing I notice is the color is off on the grey bar, which should be lighter (Gray 0, #F6F7F7). I wasn't able to check the yellow and red use case (they seem fine, but can't be exactly sure from the screenshots), those should be Red 40 and Yellow 20. The dark grey loader is correct 👌.

Awesome @grbicsanja! Thanks for pointing those out. I just updated the colors for the progress bar background and the yellow warning, since neither matched the design. Here's an updated screenshot demonstrating both:

image

**Review by grbicsanja — APPROVED** [review]

**Review by manzoorwanijk — APPROVED** [review]
Works good both on mobile and desktop.

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/7225217

Thank you @mattgawarecki for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/7225217).

**Pull request merged**
