### PR TITLE
Storage Add Ons: Create new Add Ons Package

### PR DESCRIPTION
**Pull request by jeyip**
Related to https://github.com/Automattic/wp-calypso/pull/79041#discussion_r1279224891
Tracking https://github.com/Automattic/martech/issues/2023

## Proposed Changes

* Initializes a new `add-ons` package to house any logic related to Calypso add-ons

## Testing Instructions

* Ensure that the Calypso bundle can still be generated properly ( check out this branch and run `yarn start` )

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

**Review by chriskmnds — COMMENTED** [review]
Nice to see something shaping up. How did we arrive at the decision to create a new package? It's an option, but have we considered others?

We have a couple (all of which will probably require changes):

1. Use the existing data-stores package. This would be the case for data-layer logic to live on NPM, like a hook for putting together product and other metadata. This is what the README mentions, so it does feel a little misplaced to me (the PR).
2. (Extension to the above) A combination of new package for UI parts and the existing data-stores package (I'd start with data-stores until you need the other). This would be the case where UI parts are separated from data and also exposed on NPM. You could have `packages/add-ons` (for the UI parts under `my-sites` - if/when those are needed) and `packages/data-stores/add-ons`. 
3. Use a single package for both data and UI parts (you'd need to make this clear in README). I feel this would be justified if the data parts are only really relevant to said UI (that lives in same package) i.e. there is no expected use outside. Or the data pertains too much to said UI maybe. Otherwise, something under data-stores package might feel more standardized.
4. There are more options.

Maybe put some perspective on these and see which justifies the work better.

p.s. I think of data-stores as a general host for data-layer logic (like React Query hooks, etc.), and that's how it's come to evolve (for better or worse).

**Comment by jeyip** [comment]
> Nice to see something shaping up. How did we arrive at the decision to create a new package? It's an option, but have we considered others?

Thanks for chiming in! A few reasons -- I intended to migrate existing use-add-on hooks into the `add-ons` package ( see https://github.com/Automattic/wp-calypso/pull/81051 ). I also wanted to start off discussions with tangible PRs, and your suggestion https://github.com/Automattic/wp-calypso/pull/79041#discussion_r1284709541 seemed like a good way to begin. See below:

> Speaking of which - @jeyip - I don't think plan ui package (plans-features-2023-grid) should host that hook. As a pointer for https://github.com/Automattic/wp-calypso/pull/80114 , I would suggest a separate add-ons package in the monorepo and export the hook from there. Maybe data-stores, but separate one can also exist to migrate rest of add-ons section there (I wonder when that will be put on pedestal for reuse). Definitely not under plans ui package though IMO. But lets this convo there / https://github.com/Automattic/wp-calypso/pull/80114

I also wanted to get a better sense of whether or not folks had strong opinions about the direction of the add-ons data layer in this P2 pdvytD-iS-p2 and through this PR.

> We have a couple (all of which will probably require changes):

> 1. Use the existing data-stores package. This would be the case for data-layer logic to live on NPM, like a hook for putting together product and other metadata. This is what the README mentions, so it does feel a little misplaced to me (the PR).
> 2. (Extension to the above) A combination of new package for UI parts and the existing data-stores package (I'd start with data-stores until you need the other). This would be the case where UI parts are separated from data and also exposed on NPM. You could have packages/add-ons (for the UI parts under my-sites - if/when those are needed) and packages/data-stores/add-ons.
> 3. Use a single package for both data and UI parts (you'd need to make this clear in README). I feel this would be justified if the data parts are only really relevant to said UI (that lives in same package) i.e. there is no expected use outside. Or the data pertains too much to said UI maybe. Otherwise, something under data-stores package might feel more standardized.
> 4. There are more options.

It sounds like there are thoughts we'd like to explore, and since we have so many options, this is a really good place to start a design doc or Architectural Digest Record. I'll set one up soon, document my thoughts and opinions, gather others' thoughts, and we can collaboratively hash out what that might look like. As someone who, from the looks of it, was able to work on the original add-ons hooks @chriskmnds, it'll be especially good to get your feedback on how what we design can better support add-ons moving forward 👍

**Comment by jeyip** [comment]
Closing for the time being pdvytD-iS-p2#comment-100

This is something we can always return to in the future

**Comment by chriskmnds** [comment]
> Closing for the time being pdvytD-iS-p2#comment-100
> 
> This is something we can always return to in the future

Not sure I follow why you are closing this and linking to my comment in the P2. This (pdvytD-iS-p2#comment-87 ) holds and should guide the work forward. I should remove my follow-up comment if closing this work is the interpretation that resulted from it. Not a blocker for the time being, but being that we are pulling in prices for add-ons then these need to be refactored out of Calypso state.

I do feel a little discontent that I have to repeat this again, but here's the gist of it: The add-ons data/pricing will need to be ported to an NPM package (ideally data-stores from my reading) as part of NPM Refactor PT (pau2Xa-59h-p2). That work is tracked in a milestone here: https://github.com/Automattic/wp-calypso/milestone/458 The alternative would mean passing add-on pricing as a prop to the features and comparison grid, which isn't ideal code wise, and not effective otherwise i.e. if prospective use outside of Calypso, like rendering these in logged-out pages.

^ Is this not clear? 🤔

**Comment by jeyip** [comment]
> Not sure I follow why you are closing this and linking to my comment in the P2. This (pdvytD-iS-p2#comment-87 ) holds and should guide the work forward. I should remove my follow-up comment if closing this work is the interpretation that resulted from it. Not a blocker for the time being, but being that we are pulling in prices for add-ons then these need to be refactored out of Calypso state.

> I do feel a little discontent that I have to repeat this again, but here's the gist of it: The add-ons data/pricing will need to be ported to an NPM package (ideally data-stores from my reading) as part of NPM Refactor PT (pau2Xa-59h-p2). That work is tracked in a milestone here: https://github.com/Automattic/wp-calypso/milestone/458 The alternative would mean passing add-on pricing as a prop to the features and comparison grid, which isn't ideal code wise, and not effective otherwise i.e. if prospective use outside of Calypso, like rendering these in logged-out pages.

> ^ Is this not clear? 🤔

Thanks for raising this and expressing your thoughts -- this PR actually creates a brand new add-ons package, so it seemed unnecessary to keep it open for now.  I have an explicit issue to track the migration of existing add-ons hooks into the data-stores package https://github.com/Automattic/wp-calypso/issues/81374. I also have a different draft PR that kicks off add-on hook migration ( although it was drafted before we'd resolved our discussion, so it needs to be updated to move hooks into the `data-stores` package instead of an `add-ons` package https://github.com/Automattic/wp-calypso/pull/81051 )

There’s a flurry of work being done on storage add-ons, so I’m sure it’s a little harder to track current progress. Apologies on my end if closing that PR gave the wrong impression 🙏  What you’ve described so far for our current direction is not confusing, and I still fully intend on migrating the existing hooks into packages/data-stores

**Pull request closed without merging**
