### PR TITLE
Themes: update magic search styling

### PR DESCRIPTION
**Pull request by folletto**
search-underline

This PR contains experiments for styling of the magic search component to find a combination that works given the technical restraints of the overlaid layers.

### CODE REVIEW

**Comment by lancewillett** [comment]
@folletto Still in progress? (Came up for in a scrub for pulls with no updates in 60 days.)

**Comment by folletto** [comment]
We are on hold for M* milestones due to the work on AT. All the issues/PRs have been abruptly frozen due to that, but we are back to them once AT wraps up. Please don't close them ^^

**Comment by folletto** [comment]
screen shot 2017-03-07 at 18 12 30

Rebased and tested on Chrome, Firefox, Safari. Still works.
It's misaligned in Edge on long strings and scrolling (and a little bit in IE11), but that's an issue already present before this PR.

_Note: this is still on hold until we wrap up our previous milestone, but I just wanted to check if it was still ready to go._

**Comment by folletto** [comment]
Yep, that's the issue with the current search approach: there's always text behind. 
Once this is merged I'll try a different styling to see if I can find another design that minimizes that. :)

**Pull request merged**
