### PR TITLE
Add Blogger Plan Thank You screen

### PR DESCRIPTION
**Pull request by dzver**
#### Changes proposed in this Pull Request

We recently restarted the Blogger Plan hide test. There is, however, a small problem with the Blogger plan that might've impacted the results. This plan does not have a proper thank you screen.

Before this change:

Screenshot 2019-06-28 at 15 53 49

After this change:

Screenshot 2019-06-28 at 17 15 07

#### Testing instructions

1. Buy a Blogger plan
2. Make sure the Thank You screen looks okay

### CODE REVIEW

**Comment by jaswrks** [comment]
@dzver What is the right way to go about triggering this thank-you page? I've tried a few times and I can't seem to find my way yet. I tried pulling myself out of some A/B tests, but no luck so far.

```
localStorage.setItem( 'ABTests', '{"conciergeUpsellDial_20190429":"noOffer", "improvedOnboarding_20190314": "main"}' );
```

In one test I was seeing this, but I got rid of that with the above.
Screen Shot 2019-06-28 at 12 42 09

---

When trying to upgrade an existing site I'm seeing this:
Screen Shot 2019-06-28 at 12 38 28

---

When buying the Blogger plan from the start (i.e., when creating a new site), I'm being taken right into the checklist page and not to a thank-you page.

**Comment by dzver** [comment]
It has to be tested with a logged in existing user that does not have a plan.

blogger

I retested several times and noticed that user_is_owner is sometimes there and sometimes not there leading to the .blog promotion not being rendered. It's also assembled as userIsOwner. Instead of trying to figure out why we have 2 different ownership flags none of which reliably working, I removed the check because a user can't get to the purchase thank you screen without having the right to purchase products, and they won't be allowed to complete the next purchase if they lost the right in the meantime.

**Comment by niranjan-uma-shankar** [comment]
@southp Good catch! The concierge upsell nudge is in a 50/50 AB test, so when the upsell nudge is shown, following problems could arise:

1. If the user clicks the `Skip` button on the concierge upsell nudge, then they will be taken to the checklist. They won't see the Blogger Thank You page.
2. If the user clicks `Accept` button and then purchases the concierge session, then they will be shown a [concierge Thank You page](https://user-images.githubusercontent.com/1269602/56818552-7971d680-6865-11e9-8a28-17aa14b60f82.png) instead of the Blogger Thank You page.

For point (1) above, it is a bug which should get fixed by the refactoring work done in #33996.

For point (2) above, it is a bit tricky. After purchasing a concierge session, the Thank You page has no knowledge of the previous Blogger plan purchase. 

@dzver The conclusion is that the Blogger Thank you page will only be visible to the 50% of upgrading users who will not be shown the concierge upsell. When  #33996 deploys, a partial solution will be in place. Point (2) from above still need to be addressed.

**Comment by niranjan-uma-shankar** [comment]
Verified that #33996 shows the Blogger Thank You page when Skip button is clicked on concierge upsell:

https://cloudup.com/conZbrH9xlj

**Comment by travisw** [comment]
> The concierge upsell nudge is in a 50/50 AB test

@niranjan-uma-shankar was another test introduced that scaled this back? That upsell page was rolled out to 100% of users a couple months back. It should show to everyone buying a Blogger, Personal, or Premium plan (new purchase or upgrade from another plan), as long as there isn't a domain also being purchased.

**Comment by niranjan-uma-shankar** [comment]
Ah I must have missed that we dialled it back.

**Pull request merged**
