### PR TITLE
Signup: Use the provided Site Title to pre-fill suggested domains

### LINKED ISSUE #25214: Signup: prefill domain search with site name if entered on About page
Per: https://www.useronboard.com/how-wordpress-onboards-new-users/?slide=30

If customer enters a site name on the about page prefill this on the domain search page

screen shot 2018-06-01 at 2 39 52 pm

### PR DESCRIPTION
**Pull request by jblz**
When you go through a signup flow that asks you to name your site before choosing a domain:

screen shot 2018-06-05 at 3 33 01 pm

...we do not use that value at all when it comes to domain suggestions & customers have to type their site title again before results are shown:

screen shot 2018-06-05 at 3 35 02 pm

## This change

When there are no domain `suggestion`s from other sources, attempt to get the siteTitle out of the state tree, so we can instantly provide suggestions based on the data already provided.

signup-prefill-domain-suggesstions

Fixes #25214

### CODE REVIEW

**Comment by jblz** [comment]
If the provided value is blank it comes through as `Site Title` which isn't a great experience.

signup-prefill-domain-suggesstions-blank-bad

Looking at the best way to work around that w/o doing a straight string comparison.

**Comment by jblz** [comment]
Fixed the [above](https://github.com/Automattic/wp-calypso/pull/25284#issuecomment-394836358) by pulling the site title out of redux -- it's not `Site Title` there if not provided

**Comment by aidvu** [comment]
This was tested before already: https://github.com/Automattic/wp-calypso/pull/22376
Any reasoning why do it again? :)

**Comment by jblz** [comment]
Just noticed something similar has been tried before and reverted:

https://github.com/Automattic/wp-calypso/pull/23646

Will read up on the history & see if this is substantially different enough to re-test.

**Comment by jblz** [comment]
Thanks for taking a look, @aidvu.

> This was tested before already: #22376

Ya, I didn't see that before I started hacking :)

> Any reasoning why do it again w/o a test? :)

This issue (#25214) comes out of the flow review from UserOnboard that recently made the rounds.

See: https://www.useronboard.com/how-wordpress-onboards-new-users/?slide=30

Additionally, this one of those things that has just felt "off" to me for some time. As a user, I expect that the information I've provided as the "name" of my site would be used to provide domain suggestions. 

I've not yet digested the test results, but, I think it's at least worth attempting this again -- perhaps with different conversion criteria.

Anecdotally, seeing domain suggestions pre-filled from info I've already provided makes for a delightful experience and helps me speed through the flow.

**Comment by aidvu** [comment]
I'd suggest touching base with @lucasartoni and running this as a test, if you feel the results are going to be different this time. :)

**Comment by lucasartoni** [comment]
@jblz I’d be happy to support you for a new test. We can run it again and see if the new interface we deployed helps conversions with this type of variation. However, I don’t understand the “perhaps with different conversion criteria” part. The goal of sign-up is signing up people. What other conversion would you test against?

**Comment by jblz** [comment]
@lucasartoni Thanks for taking a look & for the offer of support :)  Much appreciated!

> I don’t understand the “perhaps with different conversion criteria” part. The goal of sign-up is signing up people.

From the post on the previous test (p7jreA-1vS-p2), it looks like the funnel backing the test looked like this:
1. `calypso_domain_search`
2. `calypso_domain_registration`

I'm not 💯, I _think_ the latter only hits with a "premium" domain subscription -- not a "free" domain. So, the test was essentially optimizing for conversion into a plan.  That's fine, but completing signup successfully is another possible metric to investigate.

Also, potentially concerning about the previous methodology: if you invert the steps in the funnel, a significant number of customers are present in the second step.  That is `calypso_domain_registration` happened, then `calypso_domain_search` happened.  It's definitely possible that this really did happen organically, but the # seems high for that to me.  I'll DM you a link to that funnel.

**Comment by alisterscott** [comment]
This branch needs a rebase. Are we continuing with this PR?

**Comment by jblz** [comment]
I'll go ahead and close -- new initiative => new branch

**Pull request closed without merging**
