### PR TITLE
Social Previews | Add Post and Link preview for Twitter and Linkedin

### PR DESCRIPTION
**Pull request by manzoorwanijk**
## Proposed Changes

This PR adds the link and post preview for Twitter and LinkedIn which previously were in Jetpack. This is to make the component API consistent.

## Testing Instructions

- Make sure you have a self-hosted site connected to Jetpack, with a subscription that includes Social.
- Spin up Calypso, by running this branch locally or using a live link below.
- Ensure that you have Social Media accounts connected for a self-hosted WP Site
- Go to `/posts/:site` for a self-hosted WP site or a JN site
- Click on the 3 dots for any post and Click "Share"
- Click on "Preview"
- Confirm that the Facebook, Tumblr and Google preview look as before.
- Confirm that Twitter and LinkedIn preview now shows both the "Your post" and "Link preview" sections

| BEFORE | AFTER |
|--------|--------|
| Screenshot 2023-05-11 at 12 58 36 PM | Screenshot 2023-05-11 at 12 59 10 PM |
| Screenshot 2023-05-11 at 12 59 30 PM | Screenshot 2023-05-11 at 12 59 49 PM |

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

**Comment by danielpost** [comment]
I'm getting some strange spacing on the Twitter preview. I'm not sure if that was there before but it doesn't look right.

Review-wise, most of the code has already been reviewed and is just being ported, right? Is there anything in specific I should take a closer look at?

image

**Comment by manzoorwanijk** [comment]
> I'm getting some strange spacing on the Twitter preview. I'm not sure if that was there before but it doesn't look right.
> 

Is it calypso or wp-admin?

**Comment by manzoorwanijk** [comment]
> I'm getting some strange spacing on the Twitter preview. I'm not sure if that was there before but it doesn't look right.

Yes, I can confirm that the issue has there been before this PR but it doesn't look right. Let me fix it in this PR.
Thank you @danielpost

**Comment by manzoorwanijk** [comment]
@danielpost I have fixed the issue, please check again.

**Comment by pablinos** [comment]
It's probably not for this PR, but I notice that we're showing the old previews when accessed through `/marketing/traffic`. It wouldn't make sense to show the Your Post section there, and it's difficult to know what post to use as an example. It might be that we should use the homepage of the site?

**Comment by manzoorwanijk** [comment]
> 

@pablinos It shows the site homepage preview there.

**Review by danielpost — APPROVED** [review]
Works as expected now!

**Review by danielpost — APPROVED** [review]
Works as expected now!

**Pull request merged**
