### PR TITLE
Completion of the next step of the plugin details page in 3 simplest flows

### PR DESCRIPTION
**Pull request by ddc22**
#### Changes proposed in this Pull Request
Implement plugin details page buttons
image

Completed the next step of the plugin details page for the flows 1, 8, 9, 10 in flow variations shown below
image

#### Testing instructions
Flow 1
* Prepare an account on a business plan with a custom domain set as the primary domain
* Go to the yoast plugins page with the feature flag enabled `/plugins/wordpress-seo/{siteUrl}?flags=marketplace-yoast`
    - eg: http://calypso.localhost:3000/plugins/wordpress-seo/awesome.com?flags=marketplace-yoast
* Click on  Buy Yoast Premium, you should be directed to checkout

Flow 8
* Prepare an account on a business plan **without** a custom domain purchased 
* Go to the yoast plugins page with the feature flag enabled `/plugins/wordpress-seo/{siteUrl}?flags=marketplace-yoast`
    - eg: http://calypso.localhost:3000/plugins/wordpress-seo/awesome.com?flags=marketplace-yoast
* Click on  Buy _Yoast Premium_ 
* you should be directed to the domains page with Yoast premium added to the basket

Flow 9,10
* Same as above but
* Click on  buy _Yoast free_ 
* you should be directed to the domains page with nothing added to the basket

### CODE REVIEW

**Comment by ddc22** [comment]
[Implement plugin/product price mapping and show price on current plugin page under a feature flag](https://trello.com/c/eoXoHMAO/1-implement-plugin-product-price-mapping-and-show-price-on-current-plugin-page-under-a-feature-flag)

**Comment by dzver** [comment]
PR needs rebasing and merge conflict to be resolved.

Works fine

Testing with D61538-code leads to the domain credit actually working for .blog domains
Screenshot 2021-05-21 at 11 52 25

The domain search component incorrectly shows that non-.blog domains will also be free for use but that's not subject of this change.

LGTM, happy to have a quick look after rebasing 🚢

**Comment by dzver** [comment]
After the rebase, on a site without Business, clicking the first button leads to this:
Screenshot 2021-05-24 at 9 23 01

I tried adding a Business plan and manually set a primary domain to be a domain mapping. I still see it.

**Comment by dzver** [comment]
The error that I observed is when the domain is not provided - it happened to me because I tested the case without a primary domain set first, and then changed it.

I don't think it's relevant but you can still check it and confirm.

**Review by dzver — APPROVED** [review]

**Pull request merged**
