### PR TITLE
Add share menu to post card

### PR DESCRIPTION
**Pull request by mjuhasz**
This PR adds the `Share` action menu item to the post in the new post listing, and reveals the in-line sharing options. It also bumps a stat indicating that the menu item was used.

screen shot 2017-08-14 at 11 29 30 pm

share2

This PR is part of a larger epic and behind the `posts/post-type-list feature flag`.
See p8F9tW-hL-p2.

To test:
- Check out this branch
- `ENABLE_FEATURES=posts/post-type-list npm start`
- Navigate to Blog Posts
- Click on the ellipsis menu for a post
- Click Share
- Verify that the Share panel is visible
- Verify that the Share panel can be closed by clicking the X
- Verify that the Share panel can be closed by selecting clicking the Share menu item

### CODE REVIEW

**Comment by nylen** [comment]
I've been looking at the row height calculations for the `PostShare` component.  There are a few issues that were confusing us but shouldn't be too difficult to actually solve.

Here is what this component looks like while it's loading:

2017-08-18t17 49 06-0500

Looks broken, right?  It's actually not that bad:  the `PostShare` component ends with a margin, and and `clientHeight` doesn't take margins into account.  We should probably fix the height calculation instead of changing the CSS, but changing this margin to padding in 9bb8518cf5eec50fd89b12ab2182bc9ad90899ef fixes the issue:

2017-08-18t17 47 07-0500 bordered

Then, the `PostShare` component needs a loading placeholder - right now it is just empty.

Finally, if we attach the height calculation to `componentDidUpdate` on `PostItem`, everything appears to be working with no timeouts needed (aebdf6021291975220bcc52ec419eaf22d0446b1).

We may still want to avoid doing this height calculation work if not necessary (if the share dialog is not shown, then we can just use the default height).

**Comment by nylen** [comment]
Added a loading placeholder to `PostShare` in 15ac811:

> 

There is still an awkward loading state (or maybe a bug in the height calculation) when the sharing message form has not loaded yet:

> 

Then, the "Scheduled / Published" UI at the bottom of the component will also need to be reworked a bit for this use case:

>

**Comment by jonathansadowski** [comment]
> There is still an awkward loading state (or maybe a bug in the height calculation) when the sharing message form has not loaded yet

> Then, the "Scheduled / Published" UI at the bottom of the component will also need to be reworked a bit for this use case

These were the issues that the timeout was addressing. An interval attached to the component's lifecycle methods would would tackle both of them, but that's clearly not ideal.

@aduth, do you have any suggestions here? @nylen mentioned that you might have more familiarity with the component. The issue we're having is that [React Virtualized List](https://github.com/bvaughn/react-virtualized/blob/master/docs/List.md) requires rows of fixed height. This is giving causing us issues implementing a that expands the `PostItem` to display the share component.

This is the design we're aiming for:

posts_row_sharing

**Comment by aduth** [comment]
There's a few different ways you can retrieve height of an element. You might try the value from [`Element#getBoundingClientRect`](https://developer.mozilla.org/en-US/docs/Web/API/Element/getBoundingClientRect), or optionally offset using values from [`window.getComputedStyle`](https://developer.mozilla.org/en-US/docs/Web/API/Window/getComputedStyle) (padding/margin, converted from `px` values to number by `parseInt( '5px', 10 )`).

**Comment by aduth** [comment]
It might also be worth reevaluating how much benefit we're getting from using React Virtualized. The premise makes sense: long lists can be expensive to render, but I find the implementation of using React Virtualized is not only complex, but itself not having trivial performance characteristics.

**Comment by jonathansadowski** [comment]
> It might also be worth reevaluating how much benefit we're getting from using React Virtualized.

Thanks -- I think this may be what we want to consider. Given the desire to further add variable height to `PostItem`, and the fact we're probably negating some of the benefits of the component by having to juggle the height values around, I certainly think it's worth exploring the removal.

**Comment by nylen** [comment]
I definitely think we should avoid an interval-based solution.

The reason resizing is not working yet (and the reason for several of the specific bugs noted above) is because we are catching `componentDidUpdate` in the parent `PostItem` component, but this is not guaranteed to be called if an ancestor (or potentially a direct child) component is updated.

Two possible solutions:

- I am generally in favor of getting rid of `react-virtualized` because the code would be cleaner.  However, this seems like a potentially large refactoring that could break things, it's not clear to me how we would handle load-on-scroll without this existing solution, and it could cause performance regressions with large numbers of posts.
- We could use a [`MutationObserver`](https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver) to react to changes in the DOM and update post item row heights accordingly.  We could use one for each visible `PostItem`, or it's possible that we would only need one of these for the entire posts list.  This technique is already used [in a few places](https://github.com/Automattic/wp-calypso/search?utf8=%E2%9C%93&q=MutationObserver&type=) in Calypso, where we can look for inspiration.

**Comment by nylen** [comment]
I think the height calculation is now fully working.  Here is a recording of the current state of this PR:

post-list-variable-height

Minor annoyances:

- When expanding a post item, the scroll position jumps.  This seems like a bug in `ReactVirtualized`.
- The extra margin for an expanded post item doesn't look the best because this margin still has a border.  [Here's why](https://github.com/Automattic/wp-calypso/blob/d95ee54cab4e4825145a3c762d09e76889a00ed6/client/my-sites/post-type-list/style.scss#L2).  I tried to change this, but I had some [trouble](https://i.imgur.com/Q3cUg29.gif) getting all the pieces to work well together.

**Pull request merged**
