### PR TITLE
Signup reskin: UI changes for the user step

### PR DESCRIPTION
**Pull request by niranjan-uma-shankar**
#### Changes proposed in this Pull Request

This PR is towards implementing the reskinned signup experiment. For more context on the experiment, read pbxNRc-IO-p2.

NOTE:

This PR implements reskin UI changes for the user step. Being the final PR of the batch, this PR also represents the end to end reskinned signup flow experience. 

Here's the [Figma file](https://www.figma.com/file/gnYBUOBthTMckJRJr3pZmk/Control-Experiments?node-id=1114%3A536) for reference.

For the record:
Parent PR: https://github.com/Automattic/wp-calypso/pull/51611 and root PR: https://github.com/Automattic/wp-calypso/pull/50512

### Desktop

Screenshot 2021-04-02 at 8 30 12 PM

### Tablet

tab

### Mobile

calypso localhost_3000_start_user(Pixel 2)

#### Testing instructions

* Assign yourself to treatment from Abacus, and visit /start.
* Verify that the user step UI matches with the [Figma design](https://www.figma.com/file/gnYBUOBthTMckJRJr3pZmk/Control-Experiments?node-id=1114%3A536) in desktop, tablet, and mobile viewports.
* Verify that the log in link in user registration step redirects to the login page.
* Verify that all the signup steps - including the domains and plans steps - match the Figma design for reskinned UI, in desktop, tablet, and mobile views.
* Assign yourself to control in Abacus, and verify that the control group experience is unaffected.

### CODE REVIEW

**Review by taggon — CHANGES_REQUESTED** [review]
@niranjan-uma-shankar The panels look left aligned to me on desktop. Can you add `justify-content: center` to `.signup-form` on desktop to fix the alignment?

**Before**
Create_a_site_—_WordPress_com

**After**
Create_a_site_—_WordPress_com

**Comment by ollierozdarz** [comment]
Hi @niranjan-uma-shankar, this is coming along well! 

The first thing that sticks out to me is that we should remove the white background in the form containers, since they're not in the design:

**PR:**
Screen Shot 2021-04-06 at 8 39 54 am

**Figma:**
Screen Shot 2021-04-06 at 8 41 00 am

**Then a few small things:**

- Form label name updates: Size, color and naming to match design
- Left aligning the left container text: Terms of service paragraph needs to be left aligned
- Apple and Gmail icons seems larger than in the designs

**Comment by niranjan-uma-shankar** [comment]
@taggon @ollierozdarz I've implemented the changes requested. It's ready for review once again :)

**Comment by taggon** [comment]
@niranjan-uma-shankar Not sure if we care about this screen size but it would be better to hide the vertical bar when the screen size is about 700px.
Create_a_site_—_WordPress_com

**Comment by niranjan-uma-shankar** [comment]
@taggon I've addressed your feedback, It's ready for review again :)

**Review by taggon — APPROVED** [review]
LGTM 🚢

**Pull request merged**
