### PR TITLE
Domains: Adapt domain registrant verification page to be used with DSAPI reseller domains

### PR DESCRIPTION
**Pull request by leonardost**
## Proposed Changes

This PR updates the domain registrant verification landing page (`/domain-services/registrant-verification/`) to be used with DSAPI reseller domains.

A new `reseller=reseller-name` query parameter can be added to the URL. When that's added, references to WPCOM links and support pages are removed. If the reseller is `tumblr`, the Tumblr logo is shown in place of the WordPress logo.

### Screenshots

- Success

Screenshot 2023-04-11 at 20 46 10

- Email already verified

Screenshot 2023-04-11 at 21 02 58

- Expired email

Screenshot 2023-04-14 at 14 56 47

- Mismatched email address

Screenshot 2023-04-11 at 20 56 18

- Error message

Screenshot 2023-04-11 at 20 45 31

## Testing Instructions

- Open the live Calypso link or build this branch locally
- Hack your backend's `/domains/{domain}/verify-email` endpoint to return different success and error responses
- Access the registrant verification landing page with some example query parameters, e.g. `/domain-services/registrant-verification?domain=example.com&email=example@example.com&token=1234&reseller=tumblr_ote`
- Ensure the different backend responses' show pages as shown in the screenshots above

## Pre-merge Checklist

- [x] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [x] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

**Review by hambai — CHANGES_REQUESTED** [review]
Nice! I think we should also hide the button in `getExpiredState` as I'm pretty sure we won't be able to resend the verification email. But other than that I think it's working great!

**Comment by leonardost** [comment]
Thanks for the review @hambai, and that's a good point! I've updated that page to hide the button and changed the message accordingly.

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/7931307

Thank you @leonardost for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/7931307).

**Pull request merged**
