### PR TITLE
A4A: add referrals guide content

### PR DESCRIPTION
**Pull request by andrii-lysenko**
Related to https://github.com/Automattic/jetpack-genesis/issues/355

## Proposed Changes

Adding content to the Referral Modal. Images are stored locally within Calypso, while videos are in wp cdn.
Note: there's a slight "jump" between steps we are aware of. It will be fixed in the future.

https://github.com/Automattic/wp-calypso/assets/60262784/3c61187c-ae09-4201-8c81-b4731e9e2977

## Testing Instructions

- Using live link below navigate to any `/marketplace` link and open referral modal using `i` button on the Referral toggle in the top right corner.
- Check all steps of the Modal

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Review by madebynoam — COMMENTED** [review]
Looking great, thanks @andrii-lysenko!

Can we make the video not loop. It should only play when they user enters the section via next or back (the Gutenberg guide does the same).

I'll work on updating the videos to stop jumping today.

**Review by yashwin — APPROVED** [review]
Everything looks good & it works as expected!

One question to the design:

Should we change the numbers on the first & last step: Commissions expected this month & All time commissions?

Maybe keep it $X? 

CC: @madebynoam?

**Comment by andrii-lysenko** [comment]
Thank you @madebynoam, removed loop from the video.
@yashwin That's a good question. From one hand it might be a bit confusing, but, from other the number looks better than X. Let's see what design team have to say.

**Comment by madebynoam** [comment]
> Thank you @madebynoam, removed loop from the video. @yashwin That's a good question. From one hand it might be a bit confusing, but, from other the number looks better than X. Let's see what design team have to say.

Great question! Let's leave it as is for now. I checked other sites, and they show numbers in promotional material too. Given the context and background, it should be clear that's it's more for display purposes.

**Comment by jeffgolenski** [comment]
Let's always show numbers in these onboarding sample videos, for sure!

**Comment by jeffgolenski** [comment]
@andrii-lysenko I created a new issue to propose a few small language changes to each card. The imagery is perfect, so this shouldn't be a big lift. https://github.com/Automattic/automattic-for-agencies-dev/issues/614

**Pull request merged**
