### PR TITLE
Modularise sites state

### PR DESCRIPTION
**Pull request by sgomes**
This PR is one of many working on modularising state in Calypso. This one handles sites.

For mode details on state modularization, see #39261 and p4TIVU-9lM-p2.

Unfortunately, sites state seems to be loaded by most routes, so there likely won't be any meaningful size savings, at least from modularising alone. It's an important step in making things less monolithic, however, and perhaps as preparation for flattening the state tree somewhat by moving some branches out of `state/sites/foo` to `state/foo`.

#### Changes proposed in this Pull Request

* Modularise sites state
* Minor lint fixes to touched files

#### Testing instructions

Since sites state seems to be loaded by most routes, there's no easy way to check that modularization is working. To ensure correctness, try to use site functionality as much as possible and see if anything breaks. The unit tests and E2E tests should add a good measure of confidence.

### CODE REVIEW

**Comment by sgomes** [comment]
Looks like the PR makes login start depending on sites. Investigating.

**Comment by sgomes** [comment]
> Looks like the PR makes login start depending on sites. Investigating.

Looks like this is due to analytics having a dependency on sites, due to e.g. `state/analytics/actions/enhance-with-site-type.js`. This is ok to ignore in login (since there will never be a selected site when you're logged out), but not easily achievable through the current mechanism.

**Comment by tyxla** [comment]
Hey, @sgomes this is quite a big PR (it touches over 100 files!). Sites are also easily the most heavily used state tree in Calypso. I wonder if we could split this PR into pieces, and tackle reducer, actions, and selectors separately. Would it add too much overhead for you?

In any case, let me know when this one is ready for a review.

**Comment by sgomes** [comment]
Thanks, @tyxla! 👍 I think I'm going to close this PR, as it introduces an issue for which we don't have a good answer at the moment. There are other parts of state we can benefit more from tackling first.

**Pull request closed without merging**
