### PR TITLE
Store: Try wideLayout on <Main />

### PR DESCRIPTION
**Pull request by timmyc**
I've been wanting to give this a _Try_ for a while now, so I figured I'd get it out there for the rest of the team to checkout. This branch updates all usages of the `<Main />` component within the woocommerce extension directory to use the `wideLayout` prop. The result of this is, on wider viewports, the `.is-wide-layout` bumps the max-width of the main div from 740px to 1040px which makes some screen much less cramped ( _i'm looking at you variant table_ ).

I thought this might add an interesting wrinkle to the dashboard/widget redesign too @jameskoster 

Various Screens, Top is Current, Bottom is Wide:

store_ _care_for_animals_ _wordpress_com_and_store_ _care_for_animals_ _wordpress_com_and_wp-calypso_ _npm_start_ _node_ _npm_term_program_apple_terminal_shell__bin_zsh_ _209x56

orders_ _care_for_animals_ _wordpress_com_and_orders_ _care_for_animals_ _wordpress_com_and_wp-calypso_ _npm_start_ _node_ _npm_term_program_apple_terminal_shell__bin_zsh_ _209x56

order_details_ _care_for_animals_ _wordpress_com_and_order_details_ _care_for_animals_ _wordpress_com_and_wp-calypso_ _npm_start_ _node_ _npm_term_program_apple_terminal_shell__bin_zsh_ _209x56

products_ _care_for_animals_ _wordpress_com_and_products_ _care_for_animals_ _wordpress_com_and_wp-calypso_ _npm_start_ _node_ _npm_term_program_apple_terminal_shell__bin_zsh_ _209x56

edit_product_ _care_for_animals_ _wordpress_com_and_edit_product_ _care_for_animals_ _wordpress_com_and_wp-calypso_ _npm_start_ _node_ _npm_term_program_apple_terminal_shell__bin_zsh_ _209x56_and_listview_js_ _client

### CODE REVIEW

**Comment by kellychoffman** [comment]
We tried this earlier and it didn't feel right because of the then sparse UI. Now that we've filled things out a bit, this is feeling really nice. I especially like the variations table.

Also, now the save action button is in closer proximity to the content cards which feels like the biggest win; we've gotten negative feedback about that in the past. 

The only issues I see are the shipping notice in orders is a bit short and the dashboard design looks a bit off but we are planning on cleaning that up and adding some additional widgets to that as well.

**Comment by timmyc** [comment]
I noticed the... uhh.. notice too 😆  - but just wanted to get this out there for discussion... interesting to hear the backstory too.

Store stats already uses the wide layout, as does normal stats, which in the standard calypso-flow is the screen users are likely on prior to hitting the store dashboard.

I totally agree that the dashboard might need further re-imagining if we bump to the wide layout.  In stats we ultimately went with a 3 column widget grid on the wide break point.

**Comment by allendav** [comment]
Dialogs are still narrow, maybe a separate issue for that though.

screen shot 2017-11-06 at 8 54 12 am

**Comment by timmyc** [comment]
Re-based and removed all `max-width: 600px` limitations on dialogs within the extension directory, and let the notice on the order detail page grow to 100% of the container now.

**Comment by timmyc** [comment]
@jameskoster & @kellychoffman are we okay with this getting merged?

**Comment by kellychoffman** [comment]
I am. I think it solves a lot of problems. @jameskoster - do you want to take another look to make sure all is a-okay?

**Comment by jameskoster** [comment]
I like the idea in principle, but to me the text all feels very small now. There's lots of space between column content in tables and some line-lengths feel too long. 

Having said that, changing font sizes would throw the rest of the UI (nav, header bar etc) out. So I guess this is fine.

One change request though; See the shadow on the right-hand-side of the variations table? Now that it doesn't _always_ scroll, that should appear conditionally.

**Comment by jameskoster** [comment]
Working on the issues I highlighted above. Want to get this in!

**Comment by jameskoster** [comment]
Worked on the main issues from above; 

order

gallery

catandfeatured

**Comment by jameskoster** [comment]
Worked on a few more bits this morning. I reckon this is good to go. Take it for a spin please @kellychoffman !

**Comment by kellychoffman** [comment]
Groooovy. 

The only thing I'm noticing is the top padding (in between the search + top action bar) is larger than the left and right padding. 

screen shot 2017-11-24 at 8 39 41 am

**Comment by jameskoster** [comment]
Good catch. Fixed that!

**Comment by timmyc** [comment]
With that update @kellychoffman is this good to merge?

**Comment by kellychoffman** [comment]
Yep! Let’s merge this puppy.

**Pull request merged**
