### PR TITLE
Reader: fix misaligned Follow buttons on list items

### PR DESCRIPTION
**Pull request by jancavan**
Small fix for visual bug pointed out here: https://github.com/Automattic/wp-calypso/issues/5118#issuecomment-220588825 /cc @folletto 

> the button is not vertically centered. See current / with tweaks:

**Before:**

In Following edit:
screenshot 2016-05-20 14 39 57

In Recommendations:
screenshot 2016-05-20 14 40 14

**After:**

In Following edit:
screenshot 2016-05-20 14 40 32

In Recommendations:
screenshot 2016-05-20 14 40 50

> I also noticed that the overall typeface there is a bit bigger than everywhere else in the UI

I think it's fine to make an exception for this button as this is a higher-value action.

Also, just want to mention that the icons within buttons default to `18px`, but we had to make an exception for Reader/Follow/Following (they're using `24px` currently) as assigning the default size doesn't look great. The only place where this is much smaller than desired is on the Authors module on Stats.

More info here: https://github.com/Automattic/gridicons/pull/152#issuecomment-217579472

### CODE REVIEW

**Comment by psealock** [comment]
Changes look good visually, and fit in the context of [your last PR](https://github.com/Automattic/wp-calypso/pull/5256). 👍 from me.

If you have to revisit this code, I would suggest using a layout that doesn't rely so heavily on ```position: absolute;``` and containers with margin. This layout is likely to break from changes to elements or containers. Also classes cannot easily be reused.

Here's an [example of the layout](https://jsfiddle.net/r3uda4kd/1/) which makes use of [vertical-alignment](http://zerosixthree.se/vertical-align-anything-with-just-3-lines-of-css/) (flex-box also works). Any changes (such as font-size or line-height) to contents or containers maintain the desired layout.

**Comment by rickybanister** [comment]
I respect that the follow button is a high value action, but on the following/edit page the button is repetitive. In that case the larger text/icon make it look a bit horsey. Is there a way to shrink it when more than one appear on a page?

**Comment by jancavan** [comment]
Thanks for your review @psealock! Definitely agree on those points as pointed out on my comment here: https://github.com/Automattic/wp-calypso/pull/4817#issuecomment-213058232. It's old code that we'll have to revisit and clean up.

@rickybanister We can use the default `18px`, although it makes the icon kinda blurry on 1x display as mentioned [here](https://github.com/Automattic/gridicons/pull/152#issuecomment-217579472). Although we don't really have a solution for it. Thoughts?

**Comment by folletto** [comment]
> We can use the default 18px, although it makes the icon kinda blurry on 1x display as mentioned here. Although we don't really have a solution for it. Thoughts?

I'm not sure I understand the question: the default button has `24px` icon and `14px` font size, so it should perfect, no? :)

For reference: the current live "Follow" button at [/following/edit](https://wordpress.com/following/edit) has instead `24px` icon and `16px` font size. If we don't reset font size in all that page, we should be ok. :)

**Comment by jancavan** [comment]
@folletto Sorry, I was referring to the buttons on the [Dev Docs](https://wpcalypso.wordpress.com/devdocs/design) where the icons are `18px`. I think that's the default?

**Comment by folletto** [comment]
Ah, no "sorry": you're right. I've been misled because the borderless ones are `24px`, while the button ones are `18px`. I thought they were the same, sorry!

So... that's our standard. If we want to change it, we should address it everywhere with a new proposal on buttons. I'd try to avoid changing the font / icon size in a single place, which will make also maintenance harder later. :)

**Comment by blowery** [comment]
Are we happy here?

**Comment by jancavan** [comment]
If we used the default button style/size, it makes the icon look kinda blurry on 1x, but perhaps this is forgivable in this case.
screenshot 2016-05-23 11 46 57

@blowery This PR was to just fix the button alignment on list items. I'll have to create a separate PR for cleanup and button icon sizes.

**Comment by folletto** [comment]
> If we used the default button style/size, it makes the icon look kinda blurry on 1x, but perhaps this is forgivable in this case.

It's fine imho, in the sense that's what we have currently as a standard. 
It happens on all out buttons. If we want to fix it we should fix it at the standard level. :)

Another alternative would be here to use the borderless buttons, which use the `24px` icon if you feel the compromise is better.

**Comment by rickybanister** [comment]
The alignment issue has been resolved here it seems, ship it!

**Pull request merged**
