### PR TITLE
Add Storybook in the root directory

### PR DESCRIPTION
**Pull request by okmttdhr**
Related to https://github.com/Automattic/wp-calypso/issues/75167

## Proposed Changes

This PR is part of #75167, and add Storybook in the root directory.

For the first step, it only collects stories under the `client/` directory. We can **incrementally** add stories here. We might be able to integrate other Storybooks (e.g. `@automattic/components`) here in the future (c.f. https://github.com/Automattic/wp-calypso/issues/75167#issuecomment-1499148310, pdKhl6-1hu-p2#comment-1419).

But I personally think there are also some cons to that. 

- Increased complexity: Combining multiple Storybook projects into one can lead to a more complex setup and configuration. We will need to manage dependencies, configurations, and customizations for all projects in a single place, which might make it harder to maintain.
- Slower build and startup times & Larger bundle size

Anyway, this PR adds a simple Storybook project in the root directory, and I'm sure we can sort other things out later.

### TODO

After this PR, these should be considered.

- [ ] Add some stories
	- There are several stories that I would like to add as examples, including a component that has images and a component that uses redux store. The settings in preview.js will change accordingly.
- [ ] Deploy to GitHub pages (or something)
	- We want to see a live Storybook on PR.
- [ ] Tips & Documentation

## Testing Instructions

* Run `yarn storybook:start` locally
* Access to http://localhost:6006/?path=/story/client-components-automatticlogo--default

Screen Shot 2023-04-14 at 15 39 15

## Pre-merge Checklist

- [x] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [x] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [x] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [x] Have you checked for TypeScript, React or other console errors?
- [x] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [x] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [x] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

**Review by danielbachhuber — COMMENTED** [review]
Exciting!

It seems to launch for me as-expected:

image

I don't have any strong opinions about the underlying implementation.

As a Calypso developer, it would be nice to have:
* A couple reference implementations to follow (particularly something that interacts with Redux)
* Direction on how best to use Storybook.

Also, once this PR lands it would be great to update https://github.com/Automattic/wp-calypso/blob/trunk/docs/component-libraries.md too

**Comment by okmttdhr** [comment]
@danielbachhuber CC: @Automattic/team-calypso-platform 
Thank you for your comment! That sounds good.
I have added the `Tasks` section in the issue https://github.com/Automattic/wp-calypso/issues/75167. Let me know if it's better to create a separate issue. 🙂

**Review by miksansegundo — APPROVED** [review]
LGTM 🙌 Looks fun! I don't have experience creating stories. 

Screenshot 2566-04-18 at 09 46 30

**Comment by noahtallen** [comment]
> We will need to manage dependencies, configurations, and customizations for all projects in a single place, which might make it harder to maintain.

IMO, it's normally harder to maintain when there are multiple dependencies, configurations, and customizations! I guess that changes if one of the sub projects needs to be so much different that it's difficult to maintain in the same place, but I'm not sure that'd be the case for calypso

**Comment by okmttdhr** [comment]
I'm about to merge this PR, but I'll keep the issue https://github.com/Automattic/wp-calypso/issues/75167 open, and I'd love to see any comments anytime :slightly_smiling_face:

I'm not sure when I will be able to start the rest of the task, but at least we can incrementally change it.
If we ever write a document/guidelines about this, we may also post it to code P2 to be widely discussed.

**Comment by okmttdhr** [comment]
>IMO, it's normally harder to maintain when there are multiple dependencies, configurations, and customizations! I guess that changes if one of the sub projects needs to be so much different that it's difficult to maintain in the same place, but I'm not sure that'd be the case for calypso

I'm glad to know that, let's try it!
Also, it'd be nice to use Storybook Composition, as @javierarce suggests. https://github.com/Automattic/wp-calypso/issues/75167#issuecomment-1512738335

**Comment by tyxla** [comment]
Thank you @okmttdhr, exciting to see this materializing 👏

**Pull request merged**
