### PR TITLE
i18n: Fix translatable strings as discovered by our translators (Week 13)

### PR DESCRIPTION
**Pull request by akirk**
These strings are hard to translate, this improves them.

### CODE REVIEW

**Comment by akirk** [comment]
@shaunandrews could you check if my check still prevents the widows while keeping the translatable string free of the `\xa0`? Thanks!

**Comment by akirk** [comment]
re-ping @shaunandrews thanks!

**Comment by dmsnell** [comment]
@shaunandrews and @akirk - is there any status update on this PR? Could one of you rebase it against the current **master** and let us know what, if anything, it needs to move forward?

**Comment by akirk** [comment]
I have rebased it. @shaunandrews could you check? Thanks!

**Comment by shaunandrews** [comment]
Sorry, my bad. I understood the thumbs up as a go-ahead. But now I'm unsure if emoji reactions generate notifications or are significant enough.

:shipit: 👍 🚢

**Comment by akirk** [comment]
Thanks! :)

**Pull request merged**
