### PR TITLE
Fixes the relative date shown in Promote post

### PR DESCRIPTION
**Pull request by sbarbosa**
Related to SELFSERVE-628

## Proposed Changes

This PR fixes the relative time shown on the Advertising page. It uses a similar function to the one used on the posts page.
This way, it will feel normal to the users.

**NOTE:** This PR needs to be merged after this diff: D114400. If not, it will show incorrect relative times. 
We already are showing an incorrect time, but this change it make it more noticeable,

Screenshot 2023-08-10 at 14 25 27

Screenshot 2023-08-10 at 14 19 31

## Testing Instructions

* Open the live preview and navigate to Tools->Advertising
* Verify that the correct relative time is shown when the difference is less than a week

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

**Comment by timur987** [comment]
Thanks for the changes, @sbarbosa. They work as advertised but I doubt about the way on how we describe the age of the post. Last time I used the same approach as you but then I got a [comment](https://github.com/Automattic/wp-calypso/pull/78501#issuecomment-1601882470) from @kthai15 with a suggestion to use the same approach for dashboard as in the widget (not as it was done in Calypso before). I see you returned back showing the age as it was in Calypso.

That's why I suggest to be on the same page on how we should show the age of the post.

**Review by jjolmo — APPROVED** [review]
LGTM! Tested locally
image

**Comment by kthai15** [comment]
What I was trying to say what that the relative date should be consistent between dashboard and widget. I wasn't sure of the exact logic of how it constructs this date in the Calypso dashboard, so I invented some arbitrary logic in the widget.

```
// dateDiff is in days
{dateDiff === 0 && translate("hours ago")}
{dateDiff === 1 && translate("1 day ago")}
{dateDiff > 1 && isWithinCurrentYear && moment(date).format("MMM DD")}
{dateDiff > 1 && !isWithinCurrentYear && moment(date).format("MMM DD, YYYY")}
```

I'm sure this differs from the logic currently in the dashboard, so let us know what we need to change in the widget for it to behave in the same manner. 😄

**Comment by sbarbosa** [comment]
Thanks @timur987 for letting me know about that discussion. 
I will start a slack discussion related to this, and we can come up with a solution on both ends.

I created this bug/PR because the "hours ago" didn't sound correct for me, but I may be wrong. 
I prefer to be a little more specific, like 1 hour ago, 1 minutes ago. Maybe we can get a common ground and don't go past minutes. 

But I think we use moment in both applications, and the fromNow method already solves this problem, so it may be a good idea to apply this same change in the widget.

I will leave this PR open for now until we decide how the final solution would be.

**Comment by jjolmo** [comment]
I've created a purposal in the Widget side using this strategy and the last notes added by Bart: check PR no 331

**Comment by sbarbosa** [comment]
To match the changes made in the widget, I added a change to show `Now` instead of `a few seconds ago`.

**Pull request merged**
