### PR TITLE
WooExpress Flow: Add ecommerce background to WooExpress flow steps

### LINKED ISSUE #72170: WooExpress Flow: Add step background images
We need to add background images on each step. These are the same background images we use in the `/setup/ecommerce` flow.

image

### PR DESCRIPTION
**Pull request by markbiek**
#### Proposed Changes

This adds the background image from `/setup/ecommerce` to the processing steps of the WooExpress flow.

image

#### Testing Instructions

* Apply this branch.
* Visit http://calypso.localhost:3000/setup/wooexpress/.
* Verify that the `processing` and `assignTrial` steps have the background image shown above.
* Visit http://calypso.localhost:3000/setup/ecommerce.
* Verify that the ecommerce flow still has the same background images.

#### Pre-merge Checklist

- [x] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [x] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

Fixes #72170

### CODE REVIEW

**Review by sixhours — CHANGES_REQUESTED** [review]
During the assignTrialPlan step the background/header does this (note the whitespace at the top):

Screen Shot 2023-01-18 at 10 06 38 AM

Everything pops back into alignment once that step is done.

**Comment by markbiek** [comment]
> During the assignTrialPlan step the background/header does this (note the whitespace at the top):

Oh weird! That doesn't seem to appear on my small screen but I definitely see it on the big one.

**Comment by markbiek** [comment]
@sixhours Fixed!

**Review by sixhours — APPROVED** [review]
:shipit:

**Pull request merged**
