### PR TITLE
Checkout: Move free and full credits payment methods to calypso

### PR DESCRIPTION
**Pull request by sirbrillig**
#### Changes proposed in this Pull Request

The `free-purchase` and `full-credits` payment methods as used in Calypso are very WordPress.com-specific. Back when they were created, however, we had wanted to keep all payment methods in the `@automattic/composite-checkout` package, so we made them modular enough to have their content easily overridden when they were used in Calypso code.

In the meantime, we've moved and created many payment methods inside Calypso directly because they are WordPress.com-specific. It therefore makes sense to move these payment methods as well, allowing us to remove the unused code and simplifying the payment methods' creation. This PR does just that.

Depends on https://github.com/Automattic/wp-calypso/pull/47199

#### Example

Prior to this PR, here's the function to create the free payment method:

```js
function useCreateFree() {
	const freePaymentMethod = useMemo( createFreePaymentMethod, [] );
	freePaymentMethod.label = <WordPressFreePurchaseLabel />;
	freePaymentMethod.inactiveContent = <WordPressFreePurchaseSummary />;
	return freePaymentMethod;
}
```

And here's the same function after this PR:

```js
function useCreateFree() {
	return useMemo( createFreePaymentMethod, [] );
}
```

#### Testing instructions

- Test free payment method
  - Add a coupon to your cart that gives a 100% discount.
  - Attempt a purchase using composite checkout with the "free" payment method.
  - Verify that the purchase is successful.
- Test full credits payment method
  - Attempt a purchase using composite checkout when you have sufficient credits to cover the entire transaction.
  - Verify that the transaction completes successfully.

### CODE REVIEW

**Comment by nbloomf** [comment]
This looks good. However I will hold off on testing and approving until after it is rebased, since #47199 also touches both the free and full credits methods.

**Comment by sirbrillig** [comment]
Rebased after #47199

**Comment by nbloomf** [comment]
Looks like this slipped in to the full credits method:

Screen Shot 2020-11-11 at 12 33 29 PM

**Comment by nbloomf** [comment]
Other than the format string issue above, this is working great.

**Comment by sirbrillig** [comment]
Thanks for noticing! Fixed it. The trouble with moving between translation libraries...

Screen Shot 2020-11-11 at 4 30 13 PM

**Review by michaeldcain — APPROVED** [review]

**Pull request merged**
