### PR TITLE
2FA Reauth Required Screen: Design Improvements

### LINKED ISSUE #23549: Enhancement request for the SMS Verification code screen in Calypso
#### Steps to reproduce

There are a couple spots in the Calypso user flow, where users are asked to revalidate their identity. One spot is when managing subscriptions here:
https://wordpress.com/me/notifications

#### What I expected

Why is the "Send SMS" button, below the empty "Verification Code" field? 

It implies that you need the field to be filled in before clicking the button, when actually, you need to click the button, (receive the code via SMS) and then fill in the field. It would be better to have the SMS button alone in the panel first, or, if those two components need to be in the same panel for some reason, then to have the "Send SMS Code" button above the empty "Verification Code" field. It's especially confusing because the empty field has focus and not the button. Could we make this a bit more intuitive?

#### Browser / OS version

OSX/Chrome

#### Screenshot / Video

screen shot 2018-03-22 at 22 mar 07 13 08

### PR DESCRIPTION
**Pull request by Aurorum**
#### Changes proposed in this Pull Request

This provides a series of design enhancements to the Reauth Required flow, so fixes #23549. (cc @cafenoirdesign, @drw158)

### _First opening the screen_

> Why is the "Send SMS" button, below the empty "Verification Code" field?

It isn't anymore with this PR! :) 

> It would be better to have the SMS button alone in the panel first

This PR proposes this, it doesn't make sense to offer the option of verifying a code which the user doesn't have access to yet. 

> It's especially confusing because the empty field has focus and not the button. Could we make this a bit more intuitive?

I'd strongly argue that the best way to do this is to make this a primary button. To proceed, the user **must** press the button to enter that page of Calypso, and that feels like a pretty reasonable usage for a primary button.

As such, throughout this flow, I feel like that there should be a button which is primary (see below this screenshot)

> I would expect just one button, "Send SMS Code", maybe with the input field disabled, or not shown at all.

Disabled in this screen - after all, the user doesn't have the information to input. They need to click the button itself to get it, which they're more likely to do now that it's primary. 

Screenshot 2019-04-06 at 23 11 30

FWIW, here's a comparison without the buttons changing position. This isn't currently what's proposed in this PR, but it can be easily switched to this.

Screenshot 2019-04-07 at 10 52 22

### _Requesting a code_

The Resend Button will be disabled for sixty seconds until the next code is entered. The Verify code button will also be disabled until the moment the user enters the digits required for the code to be valid.

Once the minimum required digits has been entered, it turns primary.

Screenshot 2019-04-06 at 23 14 43

### _Requesting a resend of the code_

After sixty seconds, the Resend Button will *not* be primary again. I feel that it seems odd to have two primary buttons on one screen. 

Screenshot 2019-04-06 at 23 15 42

**Other:** This PR also proposes following removing the additional space between the four digits and the comma which is currently the case - this has seemed odd to me for a while, and I'm assuming it's unintentional since the four digits themselves are already bold.

## Authenticator Flow

> if those two components need to be in the same panel for some reason

This is a flow where the two components need to be in the same panel, as the user doesn't need to request a verification code to proceed unlike with the SMS flow - they could just obtain one from their authenticator app.

As such, the Authenticator Flow is not touched by these changes, since there's no need to receive a code.

Screenshot 2019-04-06 at 23 19 15

And of course, with either flow, the code should still work.

#### Testing instructions

Visit `/me/notifications` to trigger the reauth flow and try both. Try triggering an error as well (eg. wrong code) and ensure nothing is broken. Are codes still received? (I filled my text messages inbox working on this 😅)

This is pretty much my first time doing something like this, so I've almost certainly done something wrong! I'd appreciate any feedback on this! 

Not quite sure who to ping, but going to cc @rodrigoi, @gwwar, @kwight and @vindl as involved in #22195.

Fixes #23549

### CODE REVIEW

**Comment by torres126** [comment]
Question: would this also work better if the input field is disabled until an SMS code is requested? Should be an easy but effective adjustment.

Screenshot 2019-04-06 at 22 20 57

(Ignore the screenshot above being for the Authenticator flow, it should be just for the SMS flow only)

**Comment by drw158** [comment]
Thank you @torres126. This definitely needs an in-depth design and UX review because of its complexity.

**Comment by Aurorum** [comment]
I refactored the changes in this PR because I think there's a better way of implementing them than I initially committed.

@drw158 any way to get this reviewed? :)

**Comment by Aurorum** [comment]
This screen was subsequently improved within the last two years, so this PR probably isn't necessary now.

**Pull request closed without merging**
