### PR TITLE
Signup: Add Radcliffe 2 to the signup

### PR DESCRIPTION
**Pull request by laurelfulford**
Instructions for local testing:
* Switch to this PR
* Go to calypso.local:3000(?)/start/
* Click "Start with a website"
* Make sure that Radcliffe 2 appears (it may take some back and forth to get it instead of the other themes)

Thanks!

### CODE REVIEW

**Comment by mapk** [comment]
@laurelfulford After talking with @fditrapani, we were thinking that it might be a good idea to limit the amount of themes for each 'site type' to 3. Right now we have like 10 for 'blog', 9 for 'page', and 3 for 'grid'.

What do you think?
Should something like that become its own PR?

**Comment by fditrapani** [comment]
The reason for limiting it down to 3 themes is that we only display 3 themes at signup so if there are 9, it will randomly pick 3 out of the 9. If we only have 3, it will always show those 3.

Probably makes sense for another PR for sure.

**Comment by apeatling** [comment]
@laurelfulford Is this one still relevant? It's been sitting for a while now.

**Comment by mapk** [comment]
Radcliffe 2 is in the signup flow already now. Maybe we just close this PR? What do you think, @laurelfulford ?

**Comment by kwight** [comment]
Closing, looks like #18721 got there first.

**Pull request closed without merging**
