### PR TITLE
Theme showcase: Update the layout on the Global Site View

### PR DESCRIPTION
**Pull request by BogdanUngureanu**
Related to https://github.com/Automattic/wp-calypso/issues/94950

## Proposed Changes

* Update the layout of the Theme showcase (header and theme content)

## Why are these changes being made?

* This PR makes the themes layout more consistent with the rest of the sections (Sites and P2)

## Testing Instructions

* Use the calypso live link
* Go to /sites and then /themes global pages
* Notice that the "Themes" and the "Design your own" elements are aligned with the rest of the global pages (Sites is leading)
* Make sure that no regressions are affecting /themes/site-name and the logged out showcase

| Before  | After |
| ------------- | ------------- |
Screenshot 2024-10-22 at 12 52 40  | Screenshot 2024-10-22 at 12 51 12  |
 Screenshot 2024-10-22 at 12 52 10 | Screenshot 2024-10-22 at 13 06 56 |

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Comment by BogdanUngureanu** [comment]
@lucasmendes-design can you have a look at these changes (with the live link)?

**Review by xavier-lc — COMMENTED** [review]
Shouldn't the `Themes` title be aligned with the content?

image

**Comment by BogdanUngureanu** [comment]
@xavier-lc not sure. The Sites looks aligned but it's not actually aligned (the most obvious one is on the right side of the page where the scrollbar is not aligned with the action button)

Screenshot 2024-10-09 at 19 55 43

Lucas, any thoughts? :)

**Comment by mmtr** [comment]
> The Sites looks aligned but it's not actually aligned (the most obvious one is on the right side of the page where the scrollbar is not aligned with the action button)

We don't have an equivalent button for Themes on the right side, so I don't think that's relevant.

But the page title is definitely aligned differently. In both pages should be aligned with the search bar:

Screenshot 2024-10-11 at 15 52 35
Screenshot 2024-10-11 at 15 52 43

**Review by mmtr — COMMENTED** [review]
There is a separator in other pages like Sites, Plugins, or Domains:

Screenshot 2024-10-17 at 11 00 44
Screenshot 2024-10-17 at 11 01 26
Screenshot 2024-10-17 at 11 01 52

Can we add it to the Themes page, too?
Screenshot 2024-10-17 at 11 02 16


Also noted a weird padding change on mobile when scrolling:



https://github.com/user-attachments/assets/ffb54fd2-256d-4dc3-a3b3-3b6ea18ddc4b

The distance between the title and the search bar on mobile seems bigger on Themes than other pages too:

Themes | Sites | Domains | Plugins
--- | --- | --- | ---  
Screenshot 2024-10-17 at 11 10 32 | Screenshot 2024-10-17 at 11 10 26 | Screenshot 2024-10-17 at 11 10 19 | Screenshot 2024-10-17 at 11 07 51

Finally, the themes are no longer aligned to the search bar:

Before | After
--- | ---
Screenshot 2024-10-17 at 11 13 01 | Screenshot 2024-10-17 at 11 13 28

**Comment by BogdanUngureanu** [comment]
Thanks @mmtr! Turns out, centering a div with a scrollbar is a bit more complicated than I expected since its behavior can be different depending on the context:
- (MacOS) On smaller screens (even laptops) the scrollbar is inside the div while on larger screens it's always visible
- On mobile devices, it's always hidden and displayed on scroll

Instead, I now moved the scrollbar directly to the theme list. This way, the Ui is more consistent with the domains. I also disabled the sticky bar entirely because it causes more problems with centering. 

I also made more adjustments to the mobile version: now both portrait and landscape have the scrollbar on the entire page since there isn't much space for the sticky navbar.

**Review by mmtr — APPROVED** [review]
Nice job!

**Comment by Copons** [comment]
@BogdanUngureanu before you merge is a good moment to add before/after screens to the PR description. 🙂

**Comment by BogdanUngureanu** [comment]
@copons Done :)

**Pull request merged**
