### PR TITLE
Remove code related to the Videopress flows

### PR DESCRIPTION
**Pull request by xavier-lc**
Related to https://github.com/Automattic/dotcom-forge/issues/9333

## Proposed Changes

* On https://github.com/Automattic/wp-calypso/pull/95751 I removed the code related to the Videopress TV and Videopress TV purchase flows, and on this PR I'm tackling the Videopress flow.
* I also found some old code related to [the now unused `/start/videopress` flow](https://github.com/Automattic/wp-calypso/pull/66411), so I removed it as well

## Testing Instructions

* Open the live preview
* Go to `/setup/videopress`
* Check that you are redirected to `/start/domains`
* Repeat the previous steps with `/start/videopress`
* Check that `/start/videopress-account/user` still works:

|Logged in|Logged out|
|---|---|
|image|image|

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Comment by rcrdortiz** [comment]
With respect to:
> Check that /start/videopress-account/user still works:

Do we know if this flow is needed? I'm signed in, and clicking on the continue button, takes me to wp-admin of my main site. Not sure how much value this adds.

**Review by rcrdortiz — APPROVED** [review]
The code changes seem to make sense. I couldn't find anything wrong with the removed code.

**Comment by tyxla** [comment]
Folks, is there a reason to keep the `videopress-account` flow? Stats show that it's no longer in use, so we might as well delete it? Suggested in https://github.com/Automattic/wp-calypso/pull/99866

**Comment by xavier-lc** [comment]
@tyxla thanks for checking the stats. No reason to keep the flow if it's unused.

**Pull request merged**
