### PR TITLE
Fix theme showcase button overlapping.

### PR DESCRIPTION
**Pull request by budzanowski**
See issue #5803 that this PR addresses.

Header Cake has the second button `spacer` disabled and mobed to back. 
This button is not used/visible in Theme Sheet and when layout changes
from two pane to one pane it brakes `Pick this design` button functionality
by overlapping it. 

To test: 

1. Open Theme Sheet.
2. Reduce width of browser window to the point when layout changes from two panes to one pane
3. Inspect `Pick this design` button to check that it links to only one place

Test live: https://calypso.live/?branch=fix/5803-theme-showcase-button-behavior

### CODE REVIEW

**Comment by seear** [comment]
Would it be possible to use the existing `spacer` back prop to determine the value of `disabled` for the button? Then we would not need to touch `header-cake/index.jsx` at all.

**Comment by budzanowski** [comment]
I think this is what you are thinking.

**Comment by seear** [comment]
> I think this is what you are thinking about.

Yep, that's it. Though, I think `disabled` needs to be an input prop to `<Button/>`, rather than a css class?

**Comment by budzanowski** [comment]
That is true :( although it worked.

**Comment by seear** [comment]
👍

**Pull request merged**
