### PR TITLE
A4A: update marketplace product cards

### PR DESCRIPTION
**Pull request by andrii-lysenko**
Resolves https://github.com/Automattic/automattic-for-agencies-dev/issues/524

## Proposed Changes

Updating Product cards in Marketplace

Screenshot 2024-05-21 at 3 37 07 PM

## Testing Instructions

- Navigate to `/marketplace/products` and check the Products cards look, function and scale normally. 

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Review by yashwin — COMMENTED** [review]
It works great in general & code changes look reasonable.

But, I noticed some alignment issues:

At 375px:

Screenshot 2024-05-22 at 11 39 47 AM

At 960px:

Screenshot 2024-05-22 at 11 39 21 AM

Is this expected & will be fixed in another PR?

**Comment by cleacos** [comment]
image

It seems that this layout breakpoint doesn't make too much sense for that size... Maybe we should break to mobile view before. The issue happens with a size width `673px`.

In general, at some point, we will have to review our breakpoints... for instance, this happens at 660px, the sidebar menu hides the content:

image

**Comment by andrii-lysenko** [comment]
@yashwin @cleacos Thanks for your comments.

> Is this expected & will be fixed in another PR?
Definitely doesn't look ideal, though I'm not sure on how best to address that. Maybe we should after some breakpoint just move `flex` to `column`. Though, I don't think it's much a concern now, as there are slight imperfections on different pages with different screens, but major screen sizes should work normally.

> In general, at some point, we will have to review our breakpoints... for instance, this happens at 660px, the sidebar menu hides the content:

Interestingly, I don't see this happening for me.

**Comment by cleacos** [comment]
> Interestingly, I don't see this happening for me.

It happens in any section with a submenus (i.e. Marketplace)

**Comment by cleacos** [comment]
I think that the breakpoint (edge case) issue is low priority, and I'd say that the external icon issue at 673px is low too. There are a lot of issues around that width in other pages/sections, and probably the best way to fix all of them will be to break to the mobile view before, so... I suggest moving forward. Thoughts? cc: @keoshi @vitozev

**Review by yashwin — APPROVED** [review]
Thanks for addressing my comment.

LGTM!

**Comment by keoshi** [comment]
This is looking very good!

One change that I'd request would be to remove the `white-space: normal` property from `.license-lightbox-link__text`. Without it, the "View details" + icon stay on the same line.

image

The buttons feel slightly large on this resolution, I wonder if we could change them to the `is-compact` version. This feels a bit more balanced to me:

image

Finally, regarding @cleacos comment above:

> It seems that this layout breakpoint doesn't make too much sense for that size... Maybe we should break to mobile view before. 

We could solve this by adding the rail at some point in the future. Here's the related P2: pfunGA-S0-p2

image

**Pull request merged**
