### PR TITLE
Reader: Fix styles for Discover sidenotes

### PR DESCRIPTION
**Pull request by blowery**
The side class changed to alignleft and alignright for recent articles

### CODE REVIEW

**Comment by blowery** [comment]
before
screenshot

after
screenshot

**Comment by blowery** [comment]
cc @jancavan

**Comment by jancavan** [comment]
The sidenotes break in viewports `<1132px`. Fixed that in this changeset: https://github.com/Automattic/wp-calypso/commit/5bd85c5a47c1412ef7561bc7df1297c3c0137c7d

**Before:**
screenshot 2016-02-23 18 25 01

**After:**
screenshot 2016-02-23 18 30 50

**Comment by jancavan** [comment]
Otherwise, everything LGMT :+1:

**Comment by blowery** [comment]
Waiting on the build, then I'll merge it

**Comment by blowery** [comment]
Chatted with michelle about this, it was a mistaken class on their part. We can revert it tomorrow. 

Not sure what to do about the weird wrapping just yet.

**Comment by kjellr** [comment]
Thanks for jumping on this in any case! 👍

**Pull request merged**
