### PR TITLE
Use ProductIcon from @automattic/components instead of internal components

### PR DESCRIPTION
**Pull request by delawski**
This PR is a follow-up work to recently deployed #38253 (see: pbtFFM-11-p2).

It replaces all usages of Calypso-specific `ProductIcon` and `PlanIcon` components with a common `@automattic/components` `ProductIcon` component.

#### Changes proposed in this Pull Request

* Introduce a utility `getProductIconSlug()` function for getting a mapping between plan or product slug and icon slug (af2b05f)
* Use common `ProductIcon` in `MyPlanCard` (af2b05f)
* Replace `PlanIcon` with `ProductIcon` in `PlanFeaturesHeader` (4f328d0)
* Replace `PlanIcon` with `ProductIcon` in `Banner` (69c3711) 
* Replace `PlanIcon` with `ProductIcon` in `PurchaseItem` (6901f67)
* Replace `PlanIcon` with `ProductIcon` in `ManagePurchase` (51b0abf)
* Revert some of the changes done in #37448 to `PurchaseItem` and `ManagePurchase` (6901f67 and 51b0abf) since now Jetpack Backup icons are supported by the `ProductIcon`.
* Replace `PlanIcon` with `ProductIcon` in `PlanThankYouCard` (441fd7c)
* Replace `PlanIcon` with `ProductIcon` in `UpgradeNudgeExpanded` (831a537)
* Remove unused `PlanIcon` and `ProductIcon` components (1aa994d  and f056782)

#### Testing instructions

Go to each of the following pages and confirm that the plan icons are displayed as expected (no regression):
* http://calypso.localhost:3000/devdocs/design/banner
Screenshot 2019-12-17 at 17 27 35
 
* http://calypso.localhost:3000/devdocs/blocks/plan-thank-you-card
Screenshot 2019-12-17 at 17 26 35

* http://calypso.localhost:3000/devdocs/blocks/upgrade-nudge-expanded
Screenshot 2019-12-17 at 17 26 15

* http://calypso.localhost:3000/me/purchases
Screenshot 2019-12-17 at 17 25 24

* http://calypso.localhost:3000/me/purchases/[site]/[purchase] (go to individual purchases of various plans and products)
Screenshot 2019-12-17 at 16 27 57

* http://calypso.localhost:3000/plans/[site] (small icons in the plans grid on desktop)
Screenshot 2019-12-17 at 16 03 17

* http://calypso.localhost:3000/plans/my-plan/[site] (icons in the My plan/My Products lists)
Screenshot 2019-12-17 at 16 03 24

Fixes n/a

### CODE REVIEW

**Comment by simison** [comment]
Since you anyway use `getProductIconSlug()` everywhere:
```js
<ProductIcon slug={ getProductIconSlug( plan ) } />
```

...would it make sense to have component do it for you and do `<ProductIcon plan={ plan } />` 

Something named `getProductIconSlug`  feels like it would fit `ProductIcon` just fine? :-)

**Review by tyxla — COMMENTED** [review]
This is looking really great, nice work @delawski!

I tend to agree with @simison though - from a component usability perspective, I think it would make more sense to support all those additional product slugs. It would be much easier, than having to port that `getProductIconSlug` between codebases when reusing the component here and there.

What do you think?

**Comment by jsnajdr** [comment]
@simison @tyxla `getProductIconSlug` is a part of and uses data from `lib/products-values`. If the `ProductIcon` component in `@automattic/components` did the `getProductionIconSlug` itself, it depends on that data and the package needs to ship them somehow.

So, the question is: is it a good idea to ship a module like `lib/products-values` as a part or as a dependency of a React component library?

When something is used only inside the Calypso app, anything can depend on anything else without visible consequences. But when extracting standalone packages, we need to think about dependencies more carefully.

**Comment by tyxla** [comment]
Well, the only thing `getProductIconSlug` does is handle the case for some more slugs. If we just had those slugs defined in the component, without any dependency from `lib/products-values`, I don't see why we would need to ship `lib/products-values` as a module. I think about it as what we already have, but for twice more slugs, and don't see a good reason not to go that way. Perhaps I'm misunderstanding something?

**Comment by jsnajdr** [comment]
> I think about it as what we already have, but for twice more slugs, and don't see a good reason not to go that way.

The main job that `getProductIconSlug` is doing now is to map the `_MONTHLY`, `_YEARLY` and `_2_YEARLY` variations to one product slug. The product icons don't care about the subscription length.

So you're proposing to use the constants from `lib/plans/constants` directly as `ProductIcon` slugs?

The structure of the product constants doesn't seem to follow any unified convention. There are values like:
- `business-bundle-2y`
- `ecommerce-bundle`
- `jetpack_premium_monthly`

Sometimes there are dashes (`-`), sometimes underscores (`_`), WP.com plans use the `-bundle` suffix...

**Comment by tyxla** [comment]
Yeah, that's what I'm proposing. I know we're not very consistent with the product slug naming, and I'm not super happy about it, but it's a done deal anyway, and we can't fix it easily 😉

It's not about convention, it's about the fact that these are product slugs, and it makes sense for them to match existing products for a product icon component. In other words, I'd expect to pass any product slug from the WP.com store, and get an icon for it from that component. If we need to have an adapter or facade between the slug and the component, then it's likely a bad component design because it's a bit more difficult to use.

I don't have super strong feelings about it, but I just think that having the component handle this is in favor of a more intuitive component design. And as long as we have good documentation for the product slugs, we should be good. After all, those product slugs are used in all of our products and platforms, so we can't run away from them 😉

**Comment by tyxla** [comment]
In short, here's a user story of why I think what I'm suggesting makes sense: 

> As a `ProductIcon` component user, I expect to pass a product slug, and get an icon in return.

rather than:

> As a `ProductIcon` component user, I expect to pass an icon slug, and get an icon in return.

because if this `slug` is not a product slug, then why are we calling the component `ProductIcon`?

Just my $0.02 😉

**Comment by delawski** [comment]
I was torn a bit while implementing the `getProductIconSlug` function because of the reasons you raised here yesterday.

There are 2 valid points raised here, 2 options we can choose from:

1. Since `ProductIcon` is part of the `@automattic/components`, it should ideally be agnostic of any third-party libraries or naming conventions. It's up to the `ProductIcon`'s consumers to accommodate to the interface it exposes, even though it lives within the same organization and in most cases only A8c codebases will use it. It's how we have it right now.
2. Since `ProductIcon` is meant to be used to display A8c product icons, it's expected that the consumer shouldn't care about the particular interface the component provides. The consumer wants to get an icon for an arbitrary product or plan slug. Given the fact that those slugs are common to the whole organization, it'd be relatively safe to hardcode them inside the `ProductIcon` component.

**Pros for option 1:**
- simple interface of the `ProductIcon`
- independence of other libraries and subscription length
- pretty slugs 😉

**Pros for option 2:**
- simple interface for the consumers (Calypso, Jetpack)
- partial independence of other libraries (slugs are hard-coded)
- no need for a facade in the consumer codebase

So far I was convinced that we should keep the `ProductIcon` interface as simple as possible and make it "pretty". Right now I can see that from the practical point of view the second option is more viable.

We don't have any real control over the product and plan slugs used throughout the organization, and there's no way to make them "pretty". Since we can't fight the chaos, let's embrace it.

While the A8c product slugs don't seem stick to any naming convention and are rather ugly, the good part about them is that they are _the same_ across all codebases.

My inclination right now is to use the actual product slugs inside the `ProductIcon` so that consuming the component is as easy as it can be. Let's encapsulate the complexity inside the component instead of delegating this task to consumers.

What do you all think?

**Comment by tyxla** [comment]
Thanks @delawski I think that's a pretty good summary of where we stand there 👍 

> My inclination right now is to use the actual product slugs inside the ProductIcon so that consuming the component is as easy as it can be. Let's encapsulate the complexity inside the component instead of delegating this task to consumers.

As I already suggested above, I lean towards this too. I think that if we make a list of the cons, it will be even easier to make a decision 😉

**Comment by delawski** [comment]
I've updated the `ProductIcon` component in #38536

**Comment by tyxla** [comment]
Marking this as "in progress" and "blocked" by #38536

**Comment by delawski** [comment]
After deploying #38536 I've rebased this PR and got rid of `getProductIconSlug` usages across the codebase (in db3d97a).

This is now ready for another round of review and testing.

**Review by tyxla — APPROVED** [review]
This test well and LGTM 🚢 really nice work! 🙌

**Comment by jsnajdr** [comment]
@delawski Can you please test the PR on IE11 before merging? I suspect that the usage of `Array.prototype.flat` will break it. Because we still use CoreJS 2 that doesn't polyfill this function. There is a CoreJS 3 upgrade PR by @sgomes in #38660.

**Comment by jsnajdr** [comment]
Indeed, I see this error in console (and no Calypso UI) in IE11 when using the calypso.live link:

Screenshot 2020-01-07 at 12 33 59

The easiest temporary fixup is to use `.reduce( ( a, b ) => a.concat( b ) )` instead of `.flat()`.

**Comment by delawski** [comment]
@jsnajdr I can't find a usage of `flat()` method in this PR. Can you point me to the specific location?

**Comment by jsnajdr** [comment]
@delawski At the module's top-level initialization here: https://github.com/Automattic/wp-calypso/blob/master/packages/components/src/product-icon/config.js#L46

This PR introduces usage of `ProductIcon` in Calypso for the first time, that's why IE11 starts to fail.

**Comment by delawski** [comment]
Gotcha, thanks @jsnajdr! I'll use the fix you suggested based on the `reduce()` method.

**Comment by delawski** [comment]
@jsnajdr I've updated the code so that it no longer uses the `Array.prototype.flat` method. The calypso.live seems to work well on IE11, but please double check on your end as well.

While testing IE11 I also noticed that the SVG images are incorrectly sized like this:

Screenshot 2020-01-07 at 15 16 15

The issue was there before (i.e. is currently in production).

In order to fix this issue, I've replaced `width` and `height` properties with `viewBox` in each SVG that was affected:

Screenshot 2020-01-07 at 15 33 26

**Comment by tyxla** [comment]
It would be so awesome if we could land this one @delawski @jsnajdr. What do we need to make it happen?

**Comment by delawski** [comment]
I'm going to rebase this and do a smoke test on IE11. I'd like to have someone else doing a smoke test on IE11 as well before merging since a potential issue may bring the production down on IE.

**Comment by delawski** [comment]
I've rebased and tested the calypso.live site on Win10/IE11 (BrowserStack. Everything seems to be working as expected. Having a second check done by someone else would be perfect.

**Comment by enejb** [comment]
In my testing this PR looks good on IE 11. :shipit:

**Comment by delawski** [comment]
It seems the e2e tests fail for a reason. I'll try to have a look into this tomorrow.

**Comment by delawski** [comment]
@enejb @tyxla I've udpated the e2e tests affected (`wp-e2e-tests-full-desktop` and `wp-e2e-tests-full-mobile`) and they are passing now.

However, another test (`wp-e2e-tests-full-jetpack`) fails. After reviewing the log it looks like none of the errors is related to the updates I've done in this PR.

In this case, do you think it's safe to deploy?

**Comment by tyxla** [comment]
I gave this some testing and it looks/works great! I'm going to rebase, retest, and 🚢

Thanks a lot for it @delawski!

**Comment by tyxla** [comment]
Fixed the desktop and mobile e2e tests with https://github.com/Automattic/wp-calypso/pull/38474/commits/b019798c14009b35f57853c7c1b76650c5300d70. The Jetpack e2e test failures are unrelated and are currently consistently failing on master and other branches, too. 

This works well and LGTM 🚢

**Review by tyxla — APPROVED** [review]

**Pull request merged**
