### PR TITLE
Taxonomies: Add/Edit Categories from the Writing settings page

### PR DESCRIPTION
**Pull request by youknowriad**
Use the TermFormDialog component to allow editing and adding categories right from the Settings writing page.

**testing instructions**
- Go to the /settings/taxonomies/$site/category page
- Click "Add Category" and add new categories
- Click on a category to display the edition dialog. You should be able to edit the term and the related posts should be updated correctly.
- Try to edit the description, the parent item, the name
- Try to edit terms with children
- Try to add/edit tags as well

cc @timmyc

### CODE REVIEW

**Comment by timmyc** [comment]
Very nice!  This is testing out well for me - I can edit tags and categories and things behave as expected.  Couple of things I noticed

1- When closing the dialog, there is a bit of a "jump" that happens in the `primary` container area - its almost as if the dialog is expanding that area somehow, and when the dialog closes it shirnks back down.  Not sure if this happens on all dialogs across calypso, but this is the first time I have noticed it:

jumpy

2- When searching, the "clear" x in the search card looks visually odd to me due to the 'Add New' button also being in the header.  Not sure if it is "just me" thinking it looks strange so /cc @folletto 

site_settings_ _testingtimmy2_wordpress_com_ _wordpress_com

3- When accessing the edit dialog via the ellipsis menu, the menu stays open in the background - seems to me like we should close it out:

site_settings_ _testingtimmy2_wordpress_com_ _wordpress_com

**Comment by youknowriad** [comment]
tks for the review @timmyc 

> 1- When closing the dialog, there is a bit of a "jump"

I'm not experiencing this "jump" myself, but I think, this happens because you have the "show scollbars" enabled on your browser, so when you leave the dialog, the window scrollbars are back and that causes the "jump". I'm not sure we can do anything about this.

> 2- When searching, the "clear" x in the search card looks visually odd to me

Yes, that's the drawback of having them on the same line. I personally think it's ok, but a more "designy" eye will certainly be better here. 

> 3- When accessing the edit dialog via the ellipsis menu, the menu stays open in the background - seems to me like we should close it out:

Fixed in 5c1b3d9

**Comment by timmyc** [comment]
Took this for another spin and it is looking good to me.  🚢

**Comment by folletto** [comment]
> 2- When searching, the "clear" x in the search card looks visually odd to me due to the 'Add New' button also being in the header. Not sure if it is "just me" thinking it looks strange so /cc @folletto

Yes, it's the way it's currently built as a component. I wouldn't try to fix it here, as it requires some rework "higher up" in the component hierarchy. :)

**Pull request merged**
