### PR TITLE
Update desktop to Electron v11

### PR DESCRIPTION
**Pull request by nsakaimbo**
### Description

Update to Electron v11 to support Apple Silicon.

This is ready-to-go but hold off on merging so we can stagger this into our next desktop release.

#### CI

- [x] Mac
- [x] Linux (Circle)
- [x] Linux (TeamCity)

#### Manual Smoke Testing

- [x] Mac
- [x] Linux
- [x] Windows

### CODE REVIEW

**Review by wp-desktop — DISMISSED** [review]
WordPress Desktop CI Failure for job "wp-desktop-mac".

@nsakaimbo please inspect this job's build steps for breaking changes at [this link](https://circleci.com/gh/Automattic/wp-calypso/954440). For temporal failures, you may try to "Rerun Workflow from Failed".

Please also ensure this branch is rebased off latest Calypso.

**Comment by nsakaimbo** [comment]
Update:

CI is passing (save for TeamCity), and all platforms seem to be working as expected during manual smoke-testing.

TeamCity CI is failing with the error:

```
[22:23:39]v12.18.4 is already installed.
[22:23:40]_XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.
[22:24:16]Error: Command failed: npx mocha /home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/desktop/e2e/tests/e2e.js --timeout 20000 --exit --reporter mocha-multi-reporters --reporter-options configFile=/home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/desktop/e2e/mocha-reporter.json
[22:24:16]    at checkExecSyncError (child_process.js:630:11)
[22:24:16]    at execSync (child_process.js:666:15)
[22:24:16]    at run (/home/teamcity-3/buildAgent/work/c4a9d5b38c1dacde/desktop/e2e/run.js:139:3) {
[22:24:16]  status: 2,
[22:24:16]  signal: null,
[22:24:16]  output: [ null, null, null ],
[22:24:16]  pid: 558,
[22:24:16]  stdout: null,
[22:24:16]  stderr: null
[22:24:16]}
[22:24:16]error Command failed with exit code 1.
[22:24:16]Process exited with code 1
```

**Comment by scinos** [comment]
I'd try `--disable-dev-shm-usage`. When working on the migration, I saw it used somewhere in CircleCI docker images (I can't find it right now). It is also [recommended by Google](https://developers.google.com/web/tools/puppeteer/troubleshooting#running_puppeteer_in_docker) itself

**Comment by nsakaimbo** [comment]
I gave `--disable-dev-shm-usage` a try but the TC build bombed, however with a more specific error message:

```
[452:1119/155121.617675:FATAL:setuid_sandbox_host.cc(158)] The SUID sandbox helper binary 
was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. 
You need to make sure that /home/teamcity-0/buildAgent/work/c4a9d5b38c1dacde/desktop/node_modules/electron/dist/chrome-sandbox 
is owned by root and has mode 4755.
```

**Comment by scinos** [comment]
I think that is caused by the missing `--disable-setuid-sandbox`, I remember getting that error before.

**Comment by nsakaimbo** [comment]
Tried `--disable-setuid-sandbox` and still no dice, but did get the error message:

```
[452:1119/221402.136001:FATAL:zygote_host_impl_linux.cc(117)] No usable sandbox! 
Update your kernel or see https://chromium.googlesource.com/chromium/src/+/master/docs/linux/suid_sandbox_development.md 
for more information on developing with the SUID sandbox. 
If you want to live dangerously and need an immediate workaround, 
you can try using --no-sandbox.
```

Trying --no-sandbox now, but wondering if it will conflict with the `sandbox: false` security setting that we're enabling as part of this upgrade ([link](https://github.com/Automattic/wp-calypso/pull/47513/commits/ebcdc139e6ea0679284d0155db2df6444309e628)).

**Comment by nsakaimbo** [comment]
Update: Based on last CI run, adding `--no-sandbox` breaks Circle, and the TC build looks like it's attempting to run but fails with the error:

```
_XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.
```

Some cursory web searching seems to indicate this is also a permissions-related error. Reverting e2e app arguments so at least the Circle build is working while we look into an alternate solution for the TC build.

**Comment by nsakaimbo** [comment]
Update: TeamCity build is working and these changes are now ready to land.

**Review by mokagio — APPROVED** [review]
> Update: TeamCity build is working and these changes are now ready to land.

👍

**Pull request merged**
