### PR TITLE
Add-Ons: Add Jetpack AI card to Add-Ons page

### PR DESCRIPTION
**Pull request by nunyvega**
Related to p1688046982126439-slack-C054LN8RNVA
p1HpG7-nrG-p2

## Proposed Changes

* Add Jetpack AI card to Add-ons page(wordpress.com/add-ons/yoursite.com)
* It should only be available on a dev environment, the card is hidden behind the `jetpack/ai-assistant-request-limit` feature flag

## Testing Instructions

* Checkout this branch and follow the [getting started instructions to have Calypso running locally](https://github.com/Automattic/wp-calypso#getting-started)
* Once it's running locally, on the menu, go to "Upgrade > Add-ons"
* Confirm the Jetpack AI card is showing:

Screen Shot 2023-07-12 at 18 58 50

* Add the following parameter to the end of the URL and load the page again; it will disable the feature flag, so we can check if it's working as expected: `?flags=-jetpack/ai-assistant-request-limit` (notice the `-` signal, it's necessary)
   * Example: `http://calypso.localhost:3000/add-ons/my-test-site.wordpress.com?flags=-jetpack/ai-assistant-request-limit`
* In this case, the add-on should not show up:

Screen Shot 2023-07-12 at 19 11 46

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

**Review by dhasilva — APPROVED** [review]
LGTM
With the added flag removal it is not displayed. Working as intended :rocket:

**Review by jsnmoon — APPROVED** [review]
These changes look reasonable and work as expected!

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/8552054

Thank you @nunyvega for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/8552054).

**Pull request merged**
