### PR TITLE
Remove legacy passwordlessSignup A/B test and associated components and styles

### PR DESCRIPTION
**Pull request by andrewserong**
This is a clean-up PR to remove the old passwordless sign up flow and A/B test since we haven't been using it for a long time (re: pbmo2S-Bv-p2#comment-1372)

#### Changes proposed in this Pull Request

* Remove `passwordlessSignup` A/B test since it is no longer used
* Also remove the separate `PasswordlessSignupForm` component
* Update a couple of style rules to make the linting happy

#### Testing instructions

* Make sure that creating an account via the `/start` flow works as expected.
* Double-check that I've removed all of this A/B test, and that I haven't removed anything that's needed elsewhere. Note: there is a passwordless component in the repo, that was never used for this A/B test so I've decided to keep removing it out of this PR to keep thing cleaner.

CC: @niranjan-uma-shankar and @taggon as I know you've both been working in the /start flow more than I have lately, just wanted to get a confidence check if either of you get the chance to take a look! I updated a tiny bit of CSS for the `reskinSignupFlow` to keep the linter happy, but I believe the text size is unchanged.

Fixes #

### CODE REVIEW

**Review by p-jackson — COMMENTED** [review]
fwiw lgtm, but I think you're right to let martech take a look; I feel like they've made more use of this feature than us!

One downside of dropping this experiment is that this is a convenient way to create test passwordless accounts, since they are an account type we need to support. Does the mobile app still create passwordless accounts? Maybe that should be our goto now.
The other option is to replace the ab test with a config flag so that we can still create test accounts with `/start?flags=passwordlessSignup`

**Comment by andrewserong** [comment]
Thanks for taking a look @p-jackson!

If we're just concerned with ensuring we can easily create passwordless accounts, but aren't worried about preserving a UI flow to do it, we can use `wp.data.dispatch( 'automattic/user' ).createAccount()` (https://github.com/automattic/wp-calypso/blob/trunk/packages%2Fdata-stores%2Fsrc%2Fuser%2Factions.ts#L46) via the console in Gutenboarding, which will default to a passwordless account. So there's always that!

**Comment by p-jackson** [comment]
> If we're just concerned with ensuring we can easily create passwordless accounts

Yeah I don't think we care about preserving a UI. This console trick seems fine since `wp` is available in production so we wouldn't have to tell testers to get a local build of calypso. This is fine imo.

**Comment by andrewserong** [comment]
@Automattic/martech I've added you as reviewers — I just wanted to double check with you that this is a safe removal, it's been a long time since I've touched the /start signup flow and I know there have been some changes since I last worked on the passwordlessSignup A/B test. Does this all look okay to remove?

**Review by niranjan-uma-shankar — APPROVED** [review]
LGTM.

I also tested the following for added safety:
1. Logging in via an existing passwordless account
2. Social signup

Both worked well.

**Comment by andrewserong** [comment]
Thanks @niranjan-uma-shankar, much appreciated! 👍

**Pull request merged**
