### PR TITLE
Editor Deprecation: Consolidate the editor URL selectors v2

### PR DESCRIPTION
**Pull request by pablinos**
#### Changes proposed in this Pull Request

This is an updated version of #47344 which needed to be reverted as it
didn't take into account the patch that had been added to prevent us
from Calypsoifying Jetpack 9.2 sites #47925.

As the Jetpack version test needs to happen in two places, I've
abstracted it to a new selector.

Having this in place should simplify the process of disabling
Calypsoify.

#### Testing instructions

* Check that links to edit posts and pages don't change for simple sites, and sites that are eligible for Gutenframe, with this change.
* For Jetpack (including Atomic) sites that are ineligible for Gutenframe, check that the calypsoify=1 parameter is added to the editor URLs.
* Check that Jetpack sites with version 9.2 use standard /wp-admin/post.php and post-new.php URLs to load the editor, with no `calypsoify` parameter. Atomic sites were unaffected by the problem, but they will no longer be running 9.2

### CODE REVIEW

**Comment by retrofox** [comment]
- [x] Check that links to edit posts and pages don't change for simple sites, and sites that are eligible for Gutenframe, with this change.

- [x] For Jetpack (`9.5`) (including Atomic) sites that are ineligible for Gutenframe, check that the calypsoify=1 parameter is added to the editor URLs.

image

* State/Prod (wordpress.com):
`https://isolated-octopus.jurassic.ninja/wp-admin/post.php?post=1&action=edit`

* calypso.live (hash-fadfe41e3d711b64e985eea6bca9c44f4b3d0834.calypso.live):
`https://isolated-octopus.jurassic.ninja/wp-admin/post.php?post=1&action=edit&calypsoify=1`

* development (localhost):
`https://isolated-octopus.jurassic.ninja/wp-admin/post.php?post=1&action=edit&calypsoify=1`

**Comment by retrofox** [comment]
- [x] Check that Jetpack sites with version 9.2 use standard /wp-admin/post.php and post-new.php URLs to load the editor, with no calypsoify parameter.
Tested with Jetpack 9.2, and confirm that the `calypsoify` is not added in the query string.

`https://isolated-octopus.jurassic.ninja/wp-admin/post.php?post=1&action=edit`

Added some console.log() to check the conditions:

**Review by retrofox — APPROVED** [review]
I've tested and it LGTM. Simple and Jetpack sites, activating denied plugins to make the sites eligible/ineligible, etc.
An extra couple  👀 will be welcomed before merge/ ship, bt I haven't seen any bug in the testing process. 👍

**Comment by pablinos** [comment]
@allilevine I know you were having a look at this. How do you feel about it?

**Comment by allilevine** [comment]
> @allilevine I know you were having a look at this. How do you feel about it?

@pablinos Everything tests well, except when I upgrade to the latest bleeding edge Jetpack using beta tester. Then editor links with the `calypsoify` param like `/wp-admin/post-new.php?post_type=post&calypsoify=1` won't load. Is that something we need to address here?

**Review by allilevine — APPROVED** [review]
Looks good with https://github.com/Automattic/jetpack/pull/19204
- Simple site editor links don't change
- Atomic sites ineligible for Gutenframe get the `calypsoify=1` param
- JN site with Jetpack 9.2 doesn't get the `calypsoify=1` param, even if it's ineligible for Gutenframe

**Pull request merged**
