### PR TITLE
Advanced SEO: grandfather Website Meta

### PR DESCRIPTION
**Pull request by vindl**
Do not merge - requires API changes to be deployed first.

Allow non-business users that have already set Website Meta to
continue viewing and editing it on SEO settings page.

Test live: https://calypso.live/?branch=update/seo-front-page-meta

### CODE REVIEW

**Comment by vindl** [comment]
cc @roundhill @dmsnell @rodrigoi

**Comment by dmsnell** [comment]
Looks good to me @vindl

**Comment by roundhill** [comment]
> Looks good to me @vindl

Me too!

**Comment by roundhill** [comment]
Note: We won't merge this until the feature is launched to all users.

**Pull request merged**
