### PR TITLE
Implement minor tweaks, fixes and improvements for the new Pricing Plans block

### PR DESCRIPTION
**Pull request by msurdi-a8c**
#### Proposed Changes

* This Pull Request addresses the issues discussed in 116-gh-Automattic/lighthouse-forums for the new Pricing Plans block.

And additionally:
- Adds the `wp_enqueue_script` dependencies which were missing
- Changes the block category to ' embed' 
- A fix for 119-gh-Automattic/lighthouse-forums

#### Testing Instructions

* Run `yarn dev --sync` in `apps/happy-blocks` to sync code to your sandbox
* Create a new topic, in the editor press `/` and search for "Upgrade" block.
* Verify the issues discussed in 116-gh-Automattic/lighthouse-forums have been resolved.

#### Pre-merge Checklist

- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [x] Have you checked for TypeScript, React or other console errors?
- [x] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

Related to #

### CODE REVIEW

**Review by lamosty — CHANGES_REQUESTED** [review]
Nice fixes Matias!

I tested and everything seems to work fine, no errors, except this:

Markup 2022-11-23 at 13 52 13

The site is not showing up in the "for" field.

**Comment by msurdi-a8c** [comment]
> I tested and everything seems to work fine, no errors, except this:

@lamosty I've just fixed this. Thanks for your help :)

**Review by lamosty — APPROVED** [review]
LGTM! 🚀

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/7636553

Hi @msurdi-a8c, could you please edit the description of this PR and add a screenshot for our translators? Ideally it'd include this string: `month, billed annually`

Thank you in advance!

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/7636553).

**Pull request merged**
