### PR TITLE
Single plugin view: added missing placeholder for image and fixed stray W

### PR DESCRIPTION
**Pull request by MichaelArestad**
This PR adds a placeholder block for images by changing the header to a `div` with a background image instead of an `img`.

There is still a problem with the logic that I could use some help with. I don't know why, but it doesn't show up until after some data loads. Can we fix that? @tyxla

### CODE REVIEW

**Comment by MichaelArestad** [comment]
CC @rickybanister I have it mostly working, but I am not sure of the best way to make the image rectangle show up right away.

**Comment by rickybanister** [comment]
The W is gone, things are looking better, and if we can preserve the space of the banner it will really feel a lot smoother. Thanks for jumping on this @MichaelArestad

**Comment by tyxla** [comment]
@MichaelArestad not sure about how I can help with this one. Can you please clarify the issue you're having? Thanks.

**Comment by MichaelArestad** [comment]
@tyxla When in the loading placeholder state, the image block isn't in with the rest of the placeholders for some reason. Can you make it show up right away rather than after the content has started to load?

**Comment by tyxla** [comment]
@MichaelArestad gotcha.

In https://github.com/Automattic/wp-calypso/pull/13099/commits/92e38e5e39cc9b1368f6809fbe627069814665ed I've updated the banner logic, so the banner will always be shown, regardless of whether it'll be empty or not. 

You can easily add a default placeholder image there if you wish by adding an extra `|| placeholderImageUrl` case to `highBanner || lowBanner` (if we assume `placeholderImageUrl` is the URL of your placeholder).

Let me know if that helps.

**Comment by MichaelArestad** [comment]
After some discussion with @rickybanister, I think we want to split this to get at least the W fix in. The placeholder image might be problematic. I'll see if I can get the W fix into its own PR.

**Comment by alisterscott** [comment]
Closing as this PR is stale - please reopen if necessary

**Pull request closed without merging**
