### PR TITLE
BBE Landing: Update EN showcase images

### PR DESCRIPTION
**Pull request by aneeshd16**
Related to pdh1Xd-1DL-p2#comment-2228

## Proposed Changes

* Updates the images of the site build showcase on the BBE landing page.
* Also updates the document title to `Let us build your site`.
image

## Testing Instructions

* Go to `/setup/site-setup/difmStartingPoint?siteSlug=`.
* Confirm that the new images are displayed in the slide show.
* Confirm that the document title has been updated.

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/7918157

Thank you @aneeshd16 for including a screenshot in the description! This is really helpful for our translators.

**Review by gmovr — APPROVED** [review]
LGTM - Not sure if the i18n test is a blocker, or if we can deploy it before translations are in?

**Comment by aneeshd16** [comment]
> LGTM - Not sure if the i18n test is a blocker, or if we can deploy it before translations are in?

Thanks for the review! We can safely deploy when ES translations are in. Same for #75460 as well.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/7918157).

**Pull request merged**
