### PR TITLE
Plans: update navigation

### PR DESCRIPTION
**Pull request by mtias**
This PR cleans up the way we construct the plans section navigation, adds an item for "My Plan" if the site has a plan that is not the free one, and rewords the Jetpack item menu from the long "Add-ons for Jetpack sites" to just "Plans".

It also renders the navigation in the "My Plan" page:

image

image

Test live: https://calypso.live/?branch=update/plans-navigations

### CODE REVIEW

**Comment by rickybanister** [comment]
This fixes a number of navigational issues when jumping around the sidebar. Thanks @mtias!

**Comment by lamosty** [comment]
Working fine, nice work! :+1: 

selection_047

Went through the code and it seems alright. I particularly liked simplifying `client/my-sites/upgrades/navigation.jsx`. Seems like it was over-engineered. :)

Let's :shipit:

**Comment by apeatling** [comment]
Looks good, much better exposure of those screens. This is good to merge.

A couple of follow up things. Should the "Plans" section be more of a call to action here? "Compare Plans", or "Change Plan"?

Also another thing I noticed is the vertical spacing on the google apps section looks like it doesn't adjust to the size of screen:

image

**Comment by mtias** [comment]
> A couple of follow up things. Should the "Plans" section be more of a call to action here? "Compare Plans", or "Change Plan"?

Perhaps, yes. I'm not sure about what to label it though in a way that makes sense when you already have a plan, etc. Perhaps we figure it out with the redesign PRs?

**Comment by rickybanister** [comment]
This closes #6305

**Comment by rickybanister** [comment]
This didn't get configured 100% correctly for Jetpack plans

screen shot 2016-07-14 at 12 10 35 pm

There is no 'My Plan' item in the nav.

cc @ryelle @mtias

**Comment by mtias** [comment]
@rickybanister it's explicitly disabled for Jetpack plans since the My Plan page didn't exist at the time.

**Comment by rickybanister** [comment]
They do now, so we should bring it back.

**Pull request merged**
