### PR TITLE
Advanced SEO: tweaking styles in title editor

### LINKED ISSUE #8328: Advanced SEO: form elements not standard
The text inputs and form labels appear to have different styles applied to them. They don't seem to be using standard components. Maybe because it's using draft.js?

Specifically:

- there is no focus style
- border is darker
- form label is slightly bigger I think
- no disabled state too I think

Current:

screen shot 2016-09-29 at 10 49 40 am

Standard components:

screen shot 2016-09-29 at 10 49 51 am

@dmsnell

### PR DESCRIPTION
**Pull request by drw158**
Tweaks styling to be more consistent with other components:

- input border color
- text size and weight of label
- padding on token and input field

fixes #8328 

Before:
screen shot 2016-09-30 at 11 19 12 am

After:
screen shot 2016-09-30 at 12 19 11 pm

### CODE REVIEW

**Comment by drw158** [comment]
@roundhill I added some padding to the left and right, but I'd like to do some more testing with the cursor (with/without padding and with/without extra space). Padding + extra space character might be the best.

**Comment by roundhill** [comment]
@drw158 Yeah I think if you add padding in the token you'll have problems with the cursor, try moving it with the arrow keys to see what I mean.

**Comment by roundhill** [comment]
Corrected the padding by adding more spaces around the token text in d5e17a0.

**Comment by roundhill** [comment]
@drw158 did you have a chance to look at the additional spaces?

**Comment by drw158** [comment]
Nope, I think whatever here will be good enough

**Comment by roundhill** [comment]
OK! @dmsnell this is ready for a review. Note that I added an additional space character on each side.

**Comment by dmsnell** [comment]
:shipit:

**Pull request merged**
