### PR TITLE
FSE: Rename BPB to Newspack blocks

### PR DESCRIPTION
**Pull request by obenland**
#### Changes proposed in this Pull Request

* Does most of the renaming of things.

#### Testing instructions

* See #41423 for extensive testing instructions
* Sync command has changed to `$ yarn config set branch master && yarn run sync:newspack-blocks`

### CODE REVIEW

**Comment by obenland** [comment]
Open to ideas how to rename the synced blocks folder currently named `newspack-homepage-articles`.

We should also come up with a backwards compatible way to disable the blog posts block

**Comment by retrofox** [comment]
> Open to ideas how to rename the synced blocks folder currently named `newspack-homepage-articles`.

`newspack-blocks` sounds good to me

**Comment by obenland** [comment]
yeah same here, but that would lead to this folder structure:
`/full-site-editing-plugin/newspack-blocks/newspack-blocks/`

**Comment by retrofox** [comment]
There are still more string to replace in `./index.php` and README.md files.

**Comment by retrofox** [comment]
> yeah same here, but that would lead to this folder structure:
> `/full-site-editing-plugin/newspack-blocks/newspack-blocks/`

what about `newspack-source-code` or `newspack-source`, or `newspack-src-code`...

**Comment by marekhrabe** [comment]
What about something that screams the code is synced? We've had the feedback before to make sure this fact is apparent but we've only added it to the readme. `newspack-blocks/synced/` or something related that has similar meaning

**Pull request merged**
