### PR TITLE
Reader: Consolidate sections, move to async loading

### PR DESCRIPTION
**Pull request by blowery**
Alternative approach to #11287

### CODE REVIEW

**Comment by mtias** [comment]
What's the rationale that a single bundle is preferred for all the subsections of the Reader? It pushes it to be one of the biggest bundles we have again and the provided reasons (flux stores) should be fixed by getting rid of the stores in the first place.



The other comparable bundles—upgrades and settings—are in need of breaking down into smaller chunks as well but no one has done it yet.

**Comment by mtias** [comment]
It also puts a burden on people loading the root of WP.com that may just want to navigate elsewhere and not consume the reader, discover, search, recommendations, tags lists, etc.

**Comment by blowery** [comment]
@mtias we've been running into a "bug" more and more consistently where the flux stores we use end up in each of the reader bundles. That means that we end up with an instance of the feed-stream-store and feed-post-store for each chunk. Our singletons are suddenly not and that leads to a variety of bad effects. We double (triple / quad / ... ) count views, normalize posts, storage, etc. We can't safely remain split. 

This also came with a substantial reduction in the size of the commons bundle, as most of it was Reader code.

The plan is to use asyncRequire / AsyncLoader to split off safe parts inside the reader bundle. Also, we're going to be removing the recommended posts / cold start code entirely, as it's no longer used. But we can't do that until we can safely drop a section from the section config.

**Comment by blowery** [comment]
@mtias separately, I've been digging at figuring out a way to pull all of our flux stores (anything that calls `Dispatcher.register`) into a new async or vendor-style chunk to ensure they're singletons. Have not had much luck though. We could also pull them all up into the build chunk with `require.include`...

**Comment by mtias** [comment]
Thanks for the broader explanation. This approach seems much better than #11287 since we can tweak, group, and go back more easily.

In general the smaller bundles, even if we duplicate some code, could end up in a faster perceived experience when we bring preloading into the picture. (Example: preloading a sub 150KB bundle would very likely fall under the threshold of preloading-hover-to-click.)

**Comment by blowery** [comment]
base reader load with this change:
```
434427 public/build-production.b85af9fa5e40f766dd2c.m.js.gz
 11593 public/commons.0cd2c0bfdea43bf6dec6.m.js.gz
125903 public/reader.6657fec56914d3e3196f.m.js.gz
158697 public/vendor.production.m.js.gz
======
~731K
```

before
```
434675 public/build-production.f71015445d8b9aaa5e21.m.js.gz
 82542 public/commons.f1d1f02ec6f2ddf8968e.m.js.gz
 20027 public/reader.7a2e84b3d2f220e013c5.m.js.gz
158697 public/vendor.production.m.js.gz
======
~ 695k
```

So we've tacked 36k onto the `/` load. I bet we can get that out with a few strategic async requires.

**Comment by blowery** [comment]
> In general the smaller bundles, even if we duplicate some code, could end up in a faster perceived experience when we bring preloading into the picture.

Yes, totally agreed. However, we can't break the app by duplicating things that _have_ to be singletons. This is really really important.

**Comment by blowery** [comment]
```
-rw-r--r--  1 blowery  staff  430257 Feb 10 15:04 public/build-production.1728b513f129c71b5218.m.js.gz
-rw-r--r--  1 blowery  staff   11597 Feb 10 15:03 public/commons.f00a1fa93d29e9601749.m.js.gz
-rw-r--r--  1 blowery  staff   63956 Feb 10 15:03 public/reader.0ea01d24e3bb06fa1c45.m.js.gz
-rw-r--r--  1 blowery  staff  158697 Feb 10 15:05 public/vendor.production.m.js.gz
======
664K
```

We're down 27K (plus 4k from an unrelated change) from the original method of breaking up the reader using sections, and we're now safe. Yay!

**Comment by samouri** [comment]
I'm testing this out in docker now

**Comment by samouri** [comment]
LGTM 🚢.

**Comment by blowery** [comment]
> That means that we end up with an instance of the feed-stream-store and feed-post-store for each chunk. Our singletons are suddenly not and that leads to a variety of bad effects. We double (triple / quad / ... ) count views, normalize posts, storage, etc. We can't safely remain split.

@mtias I did a bunch more digging on this and my original presumption was incorrect. Duplicate modules that are loaded by separate chunks are ignored; the first one to load remains live while the others are dropped. For example, if `chunk A` and `chunk B` both contain module `foo`, and we load `A`, then `B`, the module `foo` in `B` is effectively dropped by webpack, though we still incur the download cost.  So the singleton worry isn't actually a worry. One less thing, I suppose, but does make me question what I was seeing originally.

**Pull request merged**
