### PR TITLE
Jetpack Backups: Pre-filter backups activity log request

### PR DESCRIPTION
**Pull request by jwebbdev**
#### Changes proposed in this Pull Request

* This adds a backup action filter to the request so we have less results to parse

#### Testing instructions

* Visit a site with backups on both WordPress.com and Jetpack Cloud
* Working Backup screens should remain unchanged
* Sites with over 1000 requests in a day should display backups with this change

Example site that failed to display backups due to many entries in the activity log in a single day:

Before:
Screen Shot 2021-12-15 at 4 12 01 PM

After:
Screen Shot 2021-12-15 at 4 10 49 PM

### CODE REVIEW

**Comment by rcanepa** [comment]
I don't fully understand what these hooks do, but couldn't we be filtering out real restore points that are not necessarily backups by limiting the type of actions requested? Cc @mattgawarecki because he has a good grasp of this part of the codebase.

**Comment by jwebbdev** [comment]
> but couldn't we be filtering out real restore points that are not necessarily backups by limiting the type of actions requested

@rcanepa I was wondering this as well.  It may be that we just need this for the Realtime Status portion and not the deltas, but I've also tried this on sites where I do see multiple restore points for a single day, so it appeared to be working, but if we have some sites with many realtime backups we can compare results on it would be great.

**Comment by mattgawarecki** [comment]
First let me say you have my full appreciation for tackling this @jwebbdev -- the Backup page is pretty hairy and could generally use all the help it can get. In particular dealing with lots of requests within one calendar day is a problem we've been fighting for a while, in one form or another.

Looking at things from a per-hook perspective:

- ✅  **`useRawBackupDeltas`**: I don't expect any changes here to affect users, since the return value would only be visible if the `jetpack/backup-simplified-screens-i4` flag is enabled (which, it's universally disabled and probably indicates some opportunities for code cleanup).
- ⚠️ **`useBackupDeltas`**: Limiting which actions we query here would only have an effect on sites with Backup Daily; specifically, the summary of what changed between daily backups. If you have access to a site with Backup Daily and at least a day or two of history, I would encourage testing to make sure this screen still captures what's actually been backed up:



- ⚠️ **`useRealtimeBackupStatus`**: This is probably where it's worth focusing most of our testing effort. With real-time backups becoming the norm, this hook is going to be called _a lot_. I only see two causes for concern, but it's been a while since I played with either this page or the Rewind API, so my knowledge could be outdated:
  - The `BACKUP_ACTIONS` array doesn't include `rewind__backup_error`, which we use this Rewind event to detect when there's been a failed backup and show the correct status.
  - In the past, restricting results to only include complete backups would mean that rewindable events like `post__published` wouldn't be returned, meaning we wouldn't have a full view of all the incremental backup events for a given date, only the full ones. For real-time backups this is particularly noticeable when there's a lot of activity but a complete backup job hasn't run yet on the selected date, so customers might end up in a state where we've done an incremental backup but the UI says "not yet today."

**Comment by mattgawarecki** [comment]
@jwebbdev Just checking back to see if there's anything you need on this?

**Comment by jwebbdev** [comment]
> @jwebbdev Just checking back to see if there's anything you need on this?

We were working on a new end point that I thought we may be able to utilize here, so I held off. Ends up it's not a great fit in its current state since it doesn't handle real-time, just completed backups.

I'm looking into this to solve a case similar to:
> For real-time backups this is particularly noticeable when there's a lot of activity but a complete backup job hasn't run yet on the selected date, so customers might end up in a state where we've done an incremental backup but the UI says "not yet today."

The situation though is that if they have enough real-time events, or events we're pulling from the activity log that it maxes out the number sent and we don't get the completed backup due to volume we also see the "not yet today" screen.

Priorities have pulled me away from this, but hopefully I'll be able to do some more testing of the cases you mentioned soon.

**Comment by manzoorwanijk** [comment]
Do we have any update on this?

**Comment by mattgawarecki** [comment]
In light of @andrii-lysenko's recent optimizations on the Backup page, I wonder if he might be interested in this PR as well?

**Comment by andrii-lysenko** [comment]
@mattgawarecki Thanks for the ping here. I remember trying something like this with passing actions and it wasn't working quite well in some situations and missing some activities, though not remember precisely. If it's not urgent I can take this into account during my next iteration of changes to Backup page, meanwhile, this PR I think can be closed, or sit till I check? What do you guys think?

**Comment by mattgawarecki** [comment]
@andrii-lysenko Not urgent 🙂 I'll leave it up to y'all whether you want to close this PR or keep it open for revisions. cc/ @jwebbdev

**Comment by jwebbdev** [comment]
Yeah I think it can be closed as well, it seemed like it needed more love than I could give it at the time based on feedback, and could be that the approach just won't work given the things Matt mentioned earlier.

**Comment by andrii-lysenko** [comment]
Thank you! I will close this PR and will try to address this issue in the future!

**Pull request closed without merging**
