### PR TITLE
Localize the support links on Developer Features page

### PR DESCRIPTION
**Pull request by dlind1**
## Proposed Changes

Localize the links on /me/developer Developer Features page by switching to absolute URLs, which can be handled by `localizeUrl`.

## Testing Instructions

1. Go to /me and switch to a Mag-16 locale, like Spanish, German, Korean etc.
2. Navigate to /me/developer and confirm that all the links to support pages are localized there.

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Review by oswian — APPROVED** [review]
Works as described  ✅

**Review by Aurorum — COMMENTED** [review]
I might be missing something and I'm not sure whether it's a big deal, but this seems to distort the current analytics tracking for this section.

**Current:**
Screenshot 2024-02-15 at 07 35 09

**This branch:**
Screenshot 2024-02-15 at 07 35 17

You might need to change this:

https://github.com/Automattic/wp-calypso/blob/d90432c97bdbc5af33b56b51a579d7cd060861b5/client/me/developer/features/use-handle-click-link.tsx#L9

**Comment by dlind1** [comment]
> I might be missing something and I'm not sure whether it's a big deal, but this seems to distort the current analytics tracking for this section.

Thanks! I've updated it to remove the slashes from the featureSlug, which should now work as before.

**Review by Aurorum — APPROVED** [review]
Not sure if you'll need an a11n review for this, but this looks great - thanks for fixing the analytics! :)

**Review by oswian — APPROVED** [review]
Nice catch regarding the analytics, @Aurorum.

It would be great to add a test to cover this.

**Comment by wongasy** [comment]
@Aurorum @oswian Analytics does appear to be impacted by this change. I'm seeing some inconsistent data, although they might just be test data. @nightnei Could you take a look at this to ensure links are indeed tracked properly?

**Comment by Aurorum** [comment]
I can't actually reproduce that, but I've proposed hardcoding them in #87808. Either way, it saves code and makes the analytics more robust if the link structure changes in future! :)

**Comment by nightnei** [comment]
@wongasy I don't see the reason to remove leading slash, but anyway it's not critical. The code looks good, `feature` properties are the same, as previously.

**Pull request merged**
