### PR TITLE
Gutenboarding: Always enroll in FSE when creating a site

### LINKED ISSUE #60253: FSE Rollout: remove opt-in screen from the /new flow
### Details

The goal of this task is to default all English-speaking existing customers to FSE. It's currently already at 100% but we are still showing an opt-in screen that needs to be removed. While doing this we need to be mindful of preserving the existing stats tracking.

### Checklist

- [x] Remove the opt-in screen, everyone gets FSE beta by default
- [x] Ensure that the FSE beta tracks event is preserved for everyone that enters the flow

### Related

_No response_

### PR DESCRIPTION
**Pull request by zaguiini**
#### Changes proposed in this Pull Request

General clean-up of Gutenboarding, removing everything related to FSE opt-in and forcing `enable_fse` in the new site request `options` object.

It also lets the user pick a classic AnchorFM theme if necessary, following the discussion in p1642621207111500-slack-CHN6J22MP.

Closes #60253.

#### Testing instructions

Create a site through `/new`. You'll notice only Universal Themes show up in the design picker and that you're FSE eligible as soon as the site is created.

Creating a site by having [AnchorFM as a referer](pdgAPm-1G-p2) displays only Anchor classic themes in the design picker, even though the site will get enrolled in FSE.

#### Next steps

Merge [this commit](https://github.com/Automattic/wp-calypso/commit/28c45a937dd52f6f72ffb8127bd58e9375724834) putting Anchor themes at the top while displaying Universal Themes below them. Reference:  p1642633206135400/1642621207.111500-slack-CHN6J22MP

### CODE REVIEW

**Comment by vindl** [comment]
@kwight 👋 could you or someone from your team verify that the AnchroFM flow is still working as expected with this PR?

**Comment by vindl** [comment]
@zaguiini this tests well for me 👍 One thing I noticed is that the `selected_fse_beta_opt_in` -> `true` tracks even is no longer being recorded, which kind of makes sense since it was tied to the opt-in button action. However, we still need it for some time to preserve the existing Tracks funnels and monitor the stats during the rollout. Would it be possible to fire it automatically when users land on the intent gathering screen of `/new`?

Here is how it currently looks in production if you turn on the logging with `localStorage.setItem( 'debug', 'calypso:analytics*' );` in the console:

Screenshot 2022-01-20 at 19 54 44

**Review by vindl — APPROVED** [review]

**Comment by kwight** [comment]
When I test with `https://container-determined-knuth.calypso.live/new?anchor_podcast=22b6608` in an incognito window, it fails with an auth warning on site creation (this doesn't happen on `wordpress.com`):

Screen Shot 2022-01-20 at 1 24 33 PM


I'm not doing anything unusual to test; just adding that query param (which is a known existing podcast). If you'd like other testing info or background, this might help: p58i-a3Z-p2

**Comment by jeyip** [comment]
> When I test with https://container-determined-knuth.calypso.live/new?anchor_podcast=22b6608 in an incognito window, it fails with an auth warning on site creation (this doesn't happen on wordpress.com):

I can reproduce this issue in containers staged with other builds. Take, for example, https://container-relaxed-bassi.calypso.live/new?anchor_podcast=22b6608, which was spun up for [an entirely different PR](https://github.com/Automattic/wp-calypso/pull/60314).

I could also reproduce the problem in a number of other containers 
- https://container-relaxed-meninsky.calypso.live created for [a themes showcase PR](https://github.com/Automattic/wp-calypso/pull/60251)
- https://container-keen-lichterman.calypso.live/ created for [a P2 PR](https://github.com/Automattic/wp-calypso/pull/60284)

Screen Shot 2022-01-20 at 3 05 54 PM

The authorization problem appears to be unrelated to changes made in this PR.

**Comment by jeyip** [comment]
## Testing
### Requirements
- [x] Remove "opt in" step for the FSE beta when users go through the `/new` flow

### Browsers
- [x] Edge
- [x] Firefox
- [x] Chrome

**Comment by zaguiini** [comment]
@kwight,

@jeyip and I figured out what's wrong.

Chrome blocks 3rd-party cookies by default in Incognito mode and that's exactly what we're doing after the user creates a new account in the Anchor FM flow: we're setting a cookie into wordpress.com through the container URL (which is not wp.com).

Setting `Allow all cookies` in  `Settings > Security and Privacy > Cookies and other site data` fixes the problem. We might need to find another way of setting the cookies in wordpress.com 😬 

Created a P2 post: p58i-bYi-p2

**Pull request merged**
