### PR TITLE
Reader: Migrate Images to Webpack

### PR DESCRIPTION
**Pull request by Aurorum**
#### Changes proposed in this Pull Request

As part of #36097, the images need to be migrated over to Webpack so the colour changes are reflected, but also the changes in #30255. I think the best thing to do is to do this per folder, so here's the Reader one.

#### Testing instructions

On an account that's never used the Reader before, verify that the banner still works the same. This is probably the least straightforward change in this PR:
Screenshot 2019-10-15 at 20 39 19

Verify that the App Block uses the new logo instead of the old one (I found it and migrated it from the `/wordpress` folder, it's not used anywhere currently. You can force it to appear by modifying this line to something that always returns true, like 2 > 1: 
https://github.com/Automattic/wp-calypso/blob/34f354c3440d8e4e86fd304756fa265ec3dabdae/client/reader/sidebar/promo.jsx#L28
Screenshot 2019-10-15 at 19 59 05

Verify the Conversations image is the same at `/conversations`
Screenshot 2019-10-15 at 20 16 34

Verify that the Reader image with a new account is the same, including with the Conversations empty content.
Screenshot 2019-10-15 at 20 36 12

This same image existed twice for some reason, with no difference but some extra space. I think it's best to just use CSS to recreate that space, so I deleted one.
Screenshot 2019-10-15 at 21 06 10

Verify that `/start/reader/reader-landing` still has the same images

fasdfsdafadsaf

Verify that the play icon is the same (I just searched "video" in the Reader, this was the first video that appeared)

Screenshot 2019-10-16 at 20 15 16

Aaaand confirm that the images aren't used anywhere other than what's been updated in this PR. :)

### CODE REVIEW

**Review by p-jackson — COMMENTED** [review]
I've looked at and tested the changes to signup (`/start/reader`) and it lgtm 👍

**Review by bluefuton — CHANGES_REQUESTED** [review]
Thanks for looking at this @Aurorum :)

The `/start/reader` signup images look good, but the intro banner shows a giant image for me in Firefox v70. 

This branch:

Screen Shot 2019-10-25 at 14 28 39

`master`:

Screen Shot 2019-10-25 at 14 29 26

**Comment by Aurorum** [comment]
Thanks! I've added a commit to fix that, it should ensure the image now looks good in Firefox too (and still the same in Chrome).

Screenshot 2019-10-25 at 11 42 27

**Review by blowery — APPROVED** [review]
LGTM! Thanks for doing this!

**Pull request merged**
