### PR TITLE
Reader: Remove immutable usage from feed-post-store

### PR DESCRIPTION
**Pull request by blowery**
No functional changes

To test, load up the reader in the past (http://calypso.localhost:3000/?at=2017-09-15T00:00:00Z), wait for the update pill to appear, accept updates. You should see new posts load in one by one.

### CODE REVIEW

**Comment by blowery** [comment]
Part of https://github.com/Automattic/wp-calypso/pull/18518

**Comment by bluefuton** [comment]
@blowery currently giving me "this.postsToFetch.delete is not a function":

screen shot 2017-10-09 at 14 29 03

**Comment by blowery** [comment]
Fixed up all the problems I could find. Thinking about adding tests... Means mocking off a couple things, but likely worth the work.

**Comment by bluefuton** [comment]
Works as desired now 💯 

+1 to adding tests if it's not too much faff.

**Comment by samouri** [comment]
Code looks great! Very clean

**Comment by blowery** [comment]
@samouri @bluefuton added tests

**Pull request merged**
