### PR TITLE
Nav Redesign: add external links for home page

### PR DESCRIPTION
**Pull request by roo2**
Simply makes the link on v2 `/sites` page into an external link like in `/sites` v1

Before | After
--- | ---
Screenshot 2024-05-16 at 16 54 20 | Screenshot 2024-05-16 at 16 54 28

7180-gh-Automattic/dotcom-forge

### Test instructions

/sites page

### CODE REVIEW

**Comment by taipeicoder** [comment]
@roo2 let's follow the same hover state and the icon in the fly-out panel. WDYT?

Screenshot 2024-05-15 at 1 51 14 PM

**Review by candy02058912 — COMMENTED** [review]
> @roo2 let's follow the same hover state and the icon in the fly-out panel. WDYT?

I think the hover state is matching the `My Home` `WP Admin` hover state for the sidebar. Do you mean to make all hover links consistent to the fly-out panel @taipeicoder?

I agree on using the same icon as in the fly-out panel to keeps things consistent.

**Comment by taipeicoder** [comment]
Sorry! Let me clarify:

The hover in the site list in the PR looks like this:
Screenshot 2024-05-16 at 3 25 25 PM

And the hover in the site management panel looks like this:
Screenshot 2024-05-16 at 3 25 28 PM

I suggested using the same style. We can defer that decision to https://github.com/Automattic/dotcom-forge/issues/7181.
In the meantime, I think using the same external link icon for consistency would be good.

**Comment by mmtr** [comment]
Just pushed an updates to use the same external icon as the site management panel:

Before | After
--- | ---
Screenshot 2024-05-16 at 16 54 20 | Screenshot 2024-05-16 at 16 54 28

**Review by mmtr — APPROVED** [review]

**Review by Addison-Stavlo — APPROVED** [review]
WFM! Will send this shortly.

**Pull request merged**
