### PR TITLE
Stats: Support dismissible Tier Upgrade notice with the API

### PR DESCRIPTION
**Pull request by dognose24**
Related to #85122 

## Proposed Changes

* Update the Tier Upgrade notice id to `tier_upgrade`.
* Apply the notice mutation to `TierUpgradeNotice` for 7 days postponement.

## Testing Instructions

* Apply the Diff D132557-code and sandbox public API.
* Spin this change on local Calypso.
* Edit code to show the Tier Upgrade notice:
https://github.com/Automattic/wp-calypso/blob/eaf4f1ace57675c73b1110467b809220560f7930/client/my-sites/stats/stats-notices/tier-upgrade-notice.tsx#L25-L26
* Click the close button on the top right of the Tier Upgrade notice banner.
* Ensure the notice disappears after dismissal.
* Reload the page.
* Ensure the `tier_upgrade` of the notice API endpoint response is `false`.

截圖 2023-12-20 上午12 45 12

* Ensure the notice does not show for 7 days.

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

**Comment by grzegorz-cp** [comment]
On the second to last step I still get `true` for `tier_upgrade` from the API, but the notice doesn't show up.

**Comment by dognose24** [comment]
Did you see the notice before all those testing steps?

**Comment by grzegorz-cp** [comment]
Yes, I forced it like you described in the third step.

**Review by grzegorz-cp — APPROVED** [review]
Works fine after testing on a fresh site.

**Pull request merged**
