### PR TITLE
Cards: Fix compact card margins

### LINKED ISSUE #14310: FoldableCard: Compact version bottom margin inconsistency
#### Steps to reproduce
1. Starting at URL: https://wpcalypso.wordpress.com/devdocs/design/foldable-card
2. Click on a "This is a compact card" expand icon

#### What I expected
It should either to stay glued to the next element, or to be split

#### What happened instead
It changes distance from next element when it's expanded or closed

#### Browser / OS version
Chrome / Ubuntu 14.04

#### Screenshot / Video
Collapsed
screenshot from 2017-05-21 21 58 59
Expanded
screenshot from 2017-05-21 21 59 23

### PR DESCRIPTION
**Pull request by mknepprath**
Fixes #14310 - Adds a top margin to compact cards in a list.

**The original behavior** here can be viewed here (Sharing, Plans, Connected Applications):
before-sd

**@folletto suggested using adjacency CSS** - unfortunately this didn't yield consistent results due to the cards sometimes being nested within other elements in their containing list.
- Sharing page - top margin never kicks in due to each card being the only item within their containing `li` element.
- Plans page - top margin kicks in when it shouldn't. This seems to be an edge case where the Foldable card isn't being used in a list at all - but because it's not the first-child of it's parent element, the top margin is added.
- Connected Applications page - works the way we want.

See all three here:
after-sd

**My proposed solution:** Don't use adjacency CSS, do add a prop when the card isn't being used in a list. I added a `solitary` prop which puts an `is-solitary` class on the card, which indicates that the `top-margin` should stay at `0`.
View the results below after adding this prop to the Plans page:
final-sd

Example:
final-sd

Notes: I wasn't sure how to access the other pages this is located on for testing/updating. If I could get help with that, that'd be great...
- `client/components/tinymce/plugins/contact-form/dialog/field`
- `client/extensions/wp-super-cache/components/contents/cache-stats`
- `client/my-sites/plugins/plugin-site-jetpack`

Testing Instructions:

Check the pages mentioned above:
Sharing: http://calypso.localhost:3000/sharing/
Plan: http://calypso.localhost:3000/plans/
Connected Apps: http://calypso.localhost:3000/me/security/connected-applications

And the devdocs:
http://calypso.localhost:3000/devdocs/design/foldable-card

Thanks!

### CODE REVIEW

**Comment by folletto** [comment]
I'm a bit uncomfortable on a solution that relies on an explicitly set variable, but sometimes it's the simplest and most efficient way out. 

Have you looked in other approaches that might be able to achieve the same result without requiring an explicit configuration?

In terms of this specific solution, if we think it's the best idea, I'd suggest to use a more explicit variable, as `is-solitary` isn't massively obvious. Maybe we can use a negative one? `is-list` with a default to `true`, so has to be explicitly set to `false`?

**Comment by mknepprath** [comment]
@folletto Have to agree - it's not ideal. I've committed option #2: using `:first-child` and adding divs to enforce the correct behavior where necessary. Details below.

**Plan page:** Added a div around `FoldableCard` so that the `FoldableCard` is the first child in that div, therefore no top margin is applied.

**Connected Apps page:** Works as expected with no change.

**Sharing page:** Added a div around the component preceding `FoldableCard` (`AccountDialogue`). This makes it so that `FoldableCard` is never the `:first-child`, because there will be a div preceding it whether `AccountDialog` `isVisible` or not. This is a bit of a hack, but it works - and this is where `:first-child` could never work in the way we'd like... Ideally, the `top-margin` would be removed based on if a `FoldableCard` precedes the current `FoldableCard`, but here `FoldableCard` is nested within a `<li>`st with `AccountDialog`.

========

I'll note, again, that this only handles the pages I've figured out how to view - I think there are more that contain `compact` `FoldableCard`s, but I'd need a hand figuring out how to test those. Thanks! 👍🏼

**Comment by folletto** [comment]
This seems an interesting approach!
And it's ok if this is a partial first take, and we'll fix the other instances as we find them. In general I think that if there's a component refactoring that is effective, it's better to go for it and fix the instances where it's used (such as the `<li>` wrapping you mention), even if it requires some extra checking.

---

This approach however made me think: yes `:first-child`... then `:first-of-type`... but it doesn't work on classes... but there's a [workaround](https://stackoverflow.com/questions/2717480/css-selector-for-first-element-with-class/8539107#8539107).

Would the workaround allow us to take the same approach, without the need for wrapping? Have you already tried maybe?

**Comment by mknepprath** [comment]
@folletto Thanks for the link! Tried out some approaches like that workaround - but the Sharing page seems to the Achilles heel for all of these solutions. I pushed a possible super simple solution that you can check out, though...

Turns out, there was already a `margin` in the styles for the Plans page that was meant to override the `FoldableCard`'s `bottom-margin`. **My new proposal -** have a top & bottom margin apply to all expanded `FoldableCard`s, and expand that override to remove the top & bottom margin on that page.

All cards expand the way we want with this small change... let me know if you'd like another gif showing it. :)

**Comment by folletto** [comment]
This looks like the best approach so far! :D 
_(Btw: GIFs and screenshot always welcome as they help a lot also for historical record)_

I tested on Chrome:

1. `/plans` (mobile size) ✅ 
2. `/sharing` ✅ 
3. `/me/security/connected-applications` ✅ 
4. `/me/notifications` (even if it doesn't seem to use this, still, checked) ✅ 

Would be good to have a test on IE and the other browsers too, but apart from that, looks good! Simple and effective. 👍

**Comment by mknepprath** [comment]
@folletto Tested latest Chrome, Safari, FF, Edge - all looking good to me! :)

Edge:
aug-10-2017 09-26-55-sd

**Comment by folletto** [comment]
Wonderful! :)

**Pull request merged**
