### PR TITLE
Test: Port over feed-stream-store, follow-list, like-store

### PR DESCRIPTION
**Pull request by blowery**
Tests should pass. No functional changes.

### CODE REVIEW

**Comment by blowery** [comment]
cc @gziolo

**Comment by blowery** [comment]
Part of #3942

**Comment by gziolo** [comment]
I'm off today, can take a look tomorrow. Pinging @umurkontaci, maybe he could help :)

Grzegorz Ziółkowski | JavaScript Wrangler | grzegorz.ziolkowski@automattic.com

Dnia 26.03.2016 o godz. 21:21 Ben Lowery <notifications@github.com> napisał(a):

**Comment by umurkontaci** [comment]
:+1: :shipit:

**Pull request merged**
