### PR TITLE
Stepper: Add check in the site-setup flow for site ownership

### LINKED ISSUE #63687: Stepper: verify siteSlug belongs to logged in user
We should verify that the user has the capability to manage the site in siteSlug. 

If the user cannot edit redirect them to `/start`.

### PR DESCRIPTION
**Pull request by andres-blanco**
The following change will add a check to see if the logged in user has `manage_options` capabilities on the site that's being used in the site-setup flow. If it doesn't it will redirect the user to `/start`.

#### Testing
1. Apply this PR or go to the calypso.live link.
2. Navigate to any step of the flow with a site you own. Eg: `/setup/businessInfo?siteSlug=[YOUR_SITE]`.
3. Verify you are not redirected.
4. Navigate to any step of the flow with a site you **don't** own. Eg: `/setup/businessInfo?siteSlug=[NOT_YOUR_SITE]`.
5. Verify you are redirected to `/start`.

Besides getting technical approval it would be good to double check from a functional POV that this is what we want. Keep in mind that this affects all the site-setup flow.

Closes https://github.com/Automattic/wp-calypso/issues/63687

### CODE REVIEW

**Comment by valterlorran** [comment]
It seems to be working, but I noticed that some endpoints are returning information about sites that are not mine. Can you confirm if that's ok? For example, if you access `/setup/?siteSlug=<someone-elses-site>` the endpoint `https://public-api.wordpress.com/rest/v1.1/sites/<someone-elses-site>` returns the site's information.

**Comment by sixhours** [comment]
Good to note, in testing this while logged in as an Automattician, I don't get redirected even when using a URL to a site I don't own because I have Super Admin access. I think that's expected, though. If I log into a non-a11n account it works as expected!

**Comment by andres-blanco** [comment]
> 

I don't think this is an error, the info doesn't seem confidential, but I couldn't find confirmation wether this is by design 🤔

**Comment by andres-blanco** [comment]
> Good to note, in testing this while logged in as an Automattician, I don't get redirected even when using a URL to a site I don't own because I have Super Admin access. I think that's expected, though. If I log into a non-a11n account it works as expected!

mmm, I can't replicate this. 
This is what I see when I try to go to a step with a site a do not own (while logged in as an automattician).

**Comment by andres-blanco** [comment]
I've rebased this PR over [this one](https://github.com/Automattic/wp-calypso/pull/64170) to use a the new assert capabilities provided by it.

**Comment by sixhours** [comment]
> mmm, I can't replicate this. This is what I see when I try to go to a step with a site a do not own (while logged in as an automattician).

Oh, weird! Maybe I wasn't actually running this branch when I tested it, because I'm seeing the same thing now. 🤷‍♀️

**Review by sixhours — APPROVED** [review]
Still working for me! 👍

**Pull request merged**
