### PR TITLE
Site Settings: Display warning dialog in `DeleteSite` when deleting a site with active subscriptions

### LINKED ISSUE #3117: Site settings: Deleting a site: Hide delete button
In Calypso, users who want to delete their site first have to visit /settings/general/:site. We don't show the delete site link until we have loaded the user's purchases. If the user has purchases then when they click this link they see a modal which prevents them from navigating to the delete site section until they have deleted their active purchases.

In WordPress.com, wp-admin users now get redirected to Calypso to delete their site, irrespective of whether they have active purchases. This means users can get to the delete site page while having active purchases on their site. Currently we show the user an error message after they try to delete their site while it has active purchases.

Ideally we should <a href="https://github.com/Automattic/wp-calypso/issues/2300">let them cancel their purchases and delete the site at the same time</a>. However as an interim solution we can check whether the user has any active purchases and in this case show them a message saying that they need to remove these purchases, and hide/disable the delete site button until the purchases have been removed.

See #3076 for context.

### PR DESCRIPTION
**Pull request by drewblaisdell**
This PR:

- Moves the warning dialog from `DeleteSiteOptions` into a new component.
- Removes logic to fetch site purchases from `DeleteSiteOptions`.
- Adds a data component, `SitePurchasesData`, and uses it to provide site purchases data to `DeleteSite` and `DeleteSiteOptions`.
- Updates the site settings controller to use JSX.

Fixes #3117.

screen shot 2016-03-30 at 5 47 45 pm

**Testing**
*Sites without active subscriptions*
- Visit `/settings/general/:site` for a site without active subscriptions.
- Assert that the "Delete Site" link at the bottom of the page appears after purchases have loaded.
- Click the "Delete Site" link.
- Assert that you are taken to `/settings/delete-site/:site`.

*Sites with active subscriptions*
- Visit `/settings/general/:site` for a site with active subscriptions.
- Assert that the "Delete Site" link at the bottom of the page appears after purchases have loaded.
- Click the "Delete Site" link.
- Assert that the dialog above appears.
- Visit `/settings/delete-site/:site` for a site with active subscriptions in a new session.
- Assert that the "Delete Site" button at the bottom is disabled until purchases have loaded.
- Click "Delete Site" once it is enabled.
- Assert that the dialog above appears.

**Note:** Actually deleting a site is buggy, right now. I opened [an issue](https://github.com/Automattic/wp-calypso/issues/4444) for this.

- [x] Product review
- [x] Code review

### CODE REVIEW

**Comment by scruffian** [comment]
Code looks good.

I tested the cases above too and they work well, with one exception. If I have a site with a premium theme I can still delete the site. I guess this is because site purchases don't include themes. I'm looking into it...

**Comment by scruffian** [comment]
Since this issue with themes is already existing there's no need to block this PR on it.

@folletto - currently users can delete a site with Premium Themes. We may want to at least warn them before allowing this to happen. I'll leave this for you to decide.

**Comment by folletto** [comment]
> We may want to at least warn them before allowing this to happen. I'll leave this for you to decide.

Doesn't the message above apply also to Premium Themes?

**Comment by scruffian** [comment]
> Doesn't the message above apply also to Premium Themes?

No premium themes are not in the list of upgrades in this case, so users can delete their site with premium themes on it without a warning.

**Comment by folletto** [comment]
Ok then 200% should be noted somewhere. :)
How can we do that?

**Comment by scruffian** [comment]
I guess we need to create a new issue for it...

**Pull request merged**
