### PR TITLE
Media: Update video/audio uploads upsell nudge

### PR DESCRIPTION
**Pull request by taipeicoder**
## Proposed Changes

This PR updates the video/audio uploads upsell nudge in the following ways:

1. The upsell UI uses a button instead of a banner.
2. The upsell description displays the plan needed for the upload.
3. The CTA action takes users to the checkout page instead of the plans page.
4. Upon checkout completion, the user is redirected to the media page instead the thank you page.

Before

https://github.com/user-attachments/assets/8c2dcf2a-dfd1-4e74-8fb4-261746b90e6e

After

https://github.com/user-attachments/assets/f6b777ba-9f5c-4236-acf9-1af47ee02c0d

## Why are these changes being made?

Contributes to the overall polish of WordPress.com

## Testing Instructions

* Head to /media/:domain
* Ensure that the user experience is updated as described above and working as intended

## Pre-merge Checklist

- [x] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [x] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [x] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [x] Have you checked for TypeScript, React or other console errors?
- [x] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [x] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [x] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Comment by taipeicoder** [comment]
@nuriapenya I'm planning to do a series of small improvements to the upsell UIs, could you let me know who would be available for some quick reviews? If the design discussion in question becomes a rabbit hole, happy to close the PR and move on to the next one. Let me know if this approach makes sense to you, thanks!

**Comment by nuriapenya** [comment]
@taipeicoder awesome! Thanks for doing this. 

In general, I like the approach. Especially removing the banner, placing a CTA and linking directly to the Checkout. I find it way more clear and actionable for the users.

I'd ensure that if users "close" the Checkout (click the back button) are brought to the same section they were before.

> Upon checkout completion, the user is redirected to the media page instead the thank you page.

I am a bit unsure about this part. I understand we want to get rid of unnecessary modals/pages like the 'Thank you' one, but I feel the flow is incomplete, and users don't have any feedback or acknowledge the process was done. Some ideas:

Maybe we could use the [success notice](https://wpcalypso.wordpress.com/devdocs/design/notice)?

I guess it must be the test environment, but the loading is quite slow and the "Upgrade" button is visible after completing the checkout:

screen 2024-11-04 at 17 42 37

I also feel we should use the [secondary button ](https://wpcalypso.wordpress.com/devdocs/design/button)for "Upload media" after completing the checkout. I had a moment of confusion, thinking it wasn't upgraded. 

screen 2024-11-04 at 17 36 41

**Comment by taipeicoder** [comment]
@nuriapenya thanks for the feedback!

> I'd ensure that if users "close" the Checkout (click the back button) are brought to the same section they were before.

Yes, this is the current behavior.

> I am a bit unsure about this part. I know we want to remove unnecessary modals/pages like the 'Thank you' one, but I feel the flow is incomplete, and users don't have any feedback or acknowledge the process was done.
> Maybe we could use the [success notice](https://wpcalypso.wordpress.com/devdocs/design/notice)?
> I guess it must be the test environment, but the loading is quite slow, and the "Upgrade" button is visible after completing the checkout:

In the interest of quick iterations, I have reverted to the existing behavior. Users will land on the thank-you screen instead of the media library.

> I also feel we should use the [secondary button ](https://wpcalypso.wordpress.com/devdocs/design/button)for "Upload media" after completing the checkout. I had a moment of confusion, thinking it wasn't upgraded.

+1! I've updated the button so that it doesn't use the primary variation.

In sum, the flow has been updated to as follows:


https://github.com/user-attachments/assets/830e55bc-831a-4fef-95e0-86e27e5d0634

**Review by okmttdhr — APPROVED** [review]
Worked well for me!

**Review by fushar — APPROVED** [review]
It works as described!

**Comment by nuriapenya** [comment]
Awesome!

>In the interest of quick iterations, I have reverted to the existing behavior. Users will land on the thank-you screen instead of the media library.

I'd be happy to follow up on this on a side issue btw. I think there's potential on bringing the users back to where the upgrade nudge was originally placed (in this case ☝🏽  the media library) but we need a way to "confirm" the success of checkout.

**Comment by taipeicoder** [comment]
Created https://github.com/Automattic/wp-calypso/issues/96058 as the follow-up issue!

**Comment by simison** [comment]
Screenshot 2024-11-05 at 11 09 48

Screenshot 2024-11-05 at 11 07 56


WP-Admin version of this upsell mentions only Premium plan for Videos, and not the Personal/Audio, in case you'd like to improve it too:

Screenshot 2024-11-05 at 11 05 32

**Comment by taipeicoder** [comment]
Great catch! I'll create an issue for this as well.

**Pull request merged**
