### PR TITLE
Stats: Prevent scroll to top on UTM modal open

### PR DESCRIPTION
**Pull request by dhasilva**
Fixes #https://github.com/Automattic/red-team/issues/255

## Proposed Changes

* Prevents the scroll to the top when opening the modal by immediately scrolling back
* Locks the background on Calypso as well

Screenshot from 2024-11-13 18-12-21

## Why are these changes being made?

* UX enhancements

## Testing Instructions

* Go to the UTM button and click it
* Check that the page is not scrolled to the top, remaining exactly where it was
* Check that it is not possible to scroll the background
* Close the modal
* Check that the scroll position remains unchanged and scrolling is available again
* Check on mobile, Jetpack and Calypso. To test on Calypso you'll need to run Calypso locally to be able to enable the feature by changing [the code](https://github.com/Automattic/wp-calypso/blob/a53c506111658b38f62ed8ce0e64799bf6d9da86/client/state/sites/selectors/get-env-stats-feature-supports.ts#L48-L50).

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Review by kangzj — APPROVED** [review]
It'll be even better if the sidebar doesn't flicker but it still feels a great improvement to me! thanks for working on this one! 👍

**Comment by dognose24** [comment]
The sidebar even disappears when the body is set to `overflow: hidden` because its position changes from `fixed` to `absolute` when the sidebar height exceeds the window height.

截圖 2024-11-14 晚上8 41 51

**Comment by dhasilva** [comment]
> I noticed that the sidebar even disappears when the body is set to overflow: hidden and its position changes from fixed to absolute, which is caused by the scrollable sidebar.

Changing the body's `position` was the the first thing I tried. The sidebar is sticky, so it stays on top and it looks like it disappears. I think scrolling back programatically is the safest approach to avoid causing side effects, specially on `body`.

**Comment by dhasilva** [comment]
> It'll be even better if the sidebar doesn't flicker
I can't reproduce this flickering. Testing on Firefox and Brave on Linux and there is no flickering :thinking:

**Review by CGastrell — APPROVED** [review]
This works fine! :shipit:

**Pull request merged**
