### PR TITLE
Add Earn features to /plans listing

### PR DESCRIPTION
**Pull request by n3f**
#### Changes proposed in this Pull Request

* 1161597846291279-as-1172482234779891 (D42533-code)
* Update the language on the plans page to highlight all the Earn blocks' features.

#### Testing instructions

* Verify that the plans includes the following:

   image

   image

### CODE REVIEW

**Comment by fditrapani** [comment]
I'll defer to @anneforbush when it comes to copy, and suggest waiting for her input before we make changes, but here are some of my suggestions:

- Change "Recurring payments" to "Accept recurring payments" as the feature because it feels more like something you're getting and then the info popup looks good to me.
- Change "Premium content block" to "Paywall content" as the feature and for the info pop up "Limit content to paying subscribers".
- Placing them so high on the list doesn't seem right to me. Can we reorder the options so they're clustered with Simple payments?

**Comment by n3f** [comment]
> * Placing them so high on the list doesn't seem right to me. Can we reorder the options so they're clustered with Simple payments?

Not really? But yes? -- The sticking point is the "Blogs and Personal Sites" tab.  Simple Payments isn't on the personal one and there's supposed to be an easy comparison across the columns, so I'm afraid of introducing confusion by having the premium content line be in one place and then suddenly drop down several rows. (We could move Simple Payments up?)

**Comment by fditrapani** [comment]
yeah, we can move simple payments up or move the entire group down around the same area. Let's see what Anne thinks.

**Comment by anneforbush** [comment]
Thanks for looping me in! A few thoughts:

- +1 to grouping the payments features together and for moving Simple Payments up!
- A couple other naming suggestions to simplify the name of the "Premium Content Block" feature: 1) "Subscribers-only content", or 2) "Sell subscriptions". The latter more obviously implies that this is a feature that customers can use to make money. 
- +1 to @fditrapani's tooltip copy suggestions

**Comment by n3f** [comment]
I pulled these from the personal vs. premium tab, since that's where simple payments gets added.

image

image

**Comment by fditrapani** [comment]
Nice — the screenshots look great!

**Pull request merged**
