### PR TITLE
Update Twemoji to 2.3

### PR DESCRIPTION
**Pull request by pento**
This adds support for all Unicode 10 and Emoji 5 emoji.

Static assets have already been updated on WP.com.

### CODE REVIEW

**Comment by pento** [comment]
Do I need to update `npm-shrinkwrap.json` as well, or is that an automagic thing?

**Comment by yurynix** [comment]
Could you please provide a step-by-step scenario for testing this? Where can I see the difference?
to generate `npm-shrinkwrap.json` you can run `make shrinkwrap`

**Comment by pento** [comment]
To reproduce:

- Create a new post, with a Unicode 10 emoji as content. You can copy one [here](https://emojipedia.org/bearded-person/). (No emoji keyboards have been updated for Unicode 10 yet). Note that the emoji doesn't render in your browser.
- View the post detail view in the reader. I.e., http://calypso.localhost:3000/read/feeds/:blogid/posts/:postid . The emoji should render as an image.

**Comment by stephanethomas** [comment]
The code looks good and works fine.

**Pull request merged**
