### PR TITLE
Marketplace: Combine collections and categories

### LINKED ISSUE #68943: Marketplace Collections: Plugin data loading investigation
In https://github.com/Automattic/wp-calypso/pull/68884 I made some assumptions about the way we want to store this data plugin data for collections. Collections are currently [hardcoded](https://github.com/Automattic/wp-calypso/blob/ba0b00eaa561a6ebf7b507133cc82b389b357ab9/client/my-sites/plugins/plugins-browser/collection-list-view/index.tsx#L21) along with all their plugin information (Names, descriptions, icons, availability etc)

While I think we do want to keep the list of plugin slugs hardcoded and the collection title/descriptions along side them, I suspect we want to load plugin titles, descriptions and icons via the api (`usePlugins`).

There is going to be some cross over in this issue with the other issue we have open about whether collections are categories or not. See https://github.com/Automattic/wp-calypso/issues/68945 for more on that. 

If possible, lets try limit the scope of this issue to just loading plugin info directly via usePlugins in order to only store a list of plugin slugs as a collection.

Acceptance:

- [ ] Confirm with design if the figma detail (like plugin descriptions / icons) is expected to stay the same or if we can use a truncated plugin short description from the endpoint 

If we need to keep descriptions as is:
- [ ] Investigate whether it's worth it or decide if we should create a new field in a woocommerce.com product field and store it there

If we can use truncated descriptions:

- [ ] Investigate whether we can specify a list of plugins per collection and offload name, icon and descriptions to the api endpoint.

### LINKED ISSUE #68945: Marketplace Collections: Browse all links and pages
To get https://github.com/Automattic/wp-calypso/pull/68884 out early we made the assumption that collections were not the same thing as categories as we define them per the [`useCategories` hook](https://github.com/Automattic/wp-calypso/blob/62b9e0938a340fff7119cfde9d56daf37cc17c27/client/my-sites/plugins/categories/use-categories.tsx#L36).

This resulted in the creation of a very similar looking [`useCollections` hook](https://github.com/Automattic/wp-calypso/blob/ba0b00eaa561a6ebf7b507133cc82b389b357ab9/client/my-sites/plugins/plugins-browser/collection-list-view/index.tsx#L21).

We'd like to figure out whether it makes sense to keep these as separate things or whether it makes sense to merge collections into categories.

I'm not quite sure what the acceptance criteria here is yet. It might not be something we need to do if collections don't expand to include more plugins so that we need the browse collection links. It might also depend on whether we are able to load a thin list of plugin slugs per https://github.com/Automattic/wp-calypso/issues/68943 or if we need to hardcode the full list of data. (In that case I think we should leave them separate to avoid getting involved with switching off `usePlugs` when in loading from a collection)

Here are some tentative things we want to figure out:

- [ ] Where do the "Browse Collection" links go as defined in the figma https://www.figma.com/file/f84fqtCG4pCnCh2Hq0But5/?node-id=4273%3A39668
- [ ] What list of plugins are those links loading, are they hard coded as we have now or are we loading a customized category like other category pages?

### PR DESCRIPTION
**Pull request by lsl**
#### Proposed Changes

* Moves `useCollections` into `useCategories`
* Split category name into category menu (and nav) text and title text shown on the page. This was required to mix ecommerce category and ecommerce collection appropriately
* Added menu titles for paid/popular/featured so it shows up in the breadcrumbs in a shorter / more appropriate form (Had to make some assumptions here but I think it looks ok)
* Enables browse all links and points them at category pages
* Split business tags category out from ecommerce category + dropped business directory tag, didn't look too helpful.

#### Testing Instructions

* View /plugins
* Should see the same collections and sections as before with the same titles
* Browse all links should now be available on collections and they should take you to an appropriate browse page
* Category pages should now render the title and description on the page but the menu text should be shown in the breadcrumb and the menu selector.
* Ecommerce category page should have a new title and description 
* Ecommerce category page should have the old title "Ecommerce & Business" seen in breadcrumbs and the menu selector

Category page: `/plugins/browse/ecommerce`
Screenshot(40)

Discover page: `/plugins`
Screenshot(39)

Fixes #68945
Fixes #68943

### CODE REVIEW

**Review by candy02058912 — APPROVED** [review]
LGTM
I like this approach. It's straightforward.

**Review by paulopmt1 — APPROVED** [review]
> Enables browse all links and points them at category pages

Loved this strategy. Everything looks as expected. Good job @lsl!

**Review by lupus2k — APPROVED** [review]
LGTM 🎉

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/7579155

Thank you @lsl for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/7579155).

**Pull request merged**
