### PR TITLE
Site Profiler UI polishing

### PR DESCRIPTION
**Pull request by candy02058912**
Related to https://github.com/Automattic/dotcom-forge/issues/9269

#### pdtkmj-2Z1-p2#comment-5721 and pdtkmj-2Z1-p2#comment-5723

| Before  | After |
| :-------------: | :-------------: |
|   | |  |

#### pdtkmj-2Z1-p2#comment-5724

| Before  | After |
| :-------------: | :-------------: |
|   | |

#### pdtkmj-2Z1-p2#comment-5725

| Before  | After |
| :-------------: | :-------------: |
|   | |

## Why are these changes being made?

* Polishing the design

## Testing Instructions

* Go to  `calypso.localhost:3000/sites/performance/:site` and `calypso.localhost:3000/speed-test-tool?url=<site>`
* Check UI on various screen sizes

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Comment by matt-west** [comment]
Thanks for tackling this @candy02058912! The loader and dropdown now look great. 👍 

We now have too much top margin on the AI banner on desktop. We’ll only need that margin once the boxes stack at smaller screen sizes.

Screenshot 2024-09-27 at 10 30 55

Screenshot 2024-09-27 at 10 31 11


This isn’t mentioned on the original issues, but can we extend the `Did you know?` box to fill the full-width of the screen once the boxes stack. At the moment it looks a bit odd.

We’ll need to add a `max-width` on the content to avoid ending up with really long lines of text at larger screen widths.

**Current**
Screenshot 2024-09-27 at 10 31 22

**Desired**
Screenshot 2024-09-27 at 10 33 33

**Review by matt-west — CHANGES_REQUESTED** [review]
Pending changes to the AI banner spacing.

**Review by vykes-mac — APPROVED** [review]
LGTM

**Comment by matt-west** [comment]
@vykes-mac The `Did you know?` banner is now broken on mobile.

Screenshot 2024-09-30 at 09 27 12

The `max-width` set on the text also doesn't match the design. It should be `430px`.

Please test changes thoroughly on both desktop and mobile before merging PRs. cc @autumnfjeld

**Comment by vykes-mac** [comment]
@candy02058912 Could you take a look at fixing this?

**Pull request merged**
