### PR TITLE
Reader Refresh: character count looks at better_excerpt instead of dom.tex…

### PR DESCRIPTION
**Pull request by samouri**
Attempting to solve #9185 where image captions are being counted as wel

### CODE REVIEW

**Comment by fraying** [comment]
Assuming you mean character count, not word count, but yay!

**Comment by samouri** [comment]
welp, correct

**Comment by fraying** [comment]
Thanks! And sorry. Not trying to be pedantic. Just making sure we're all on the same page. (I made this same mistake earlier.)

**Comment by blowery** [comment]
I think we can drop the whole word-count / character-count rule (it's not used afaik) and just check the length of `post.better_excerpt_no_html` when necessary.

**Comment by samouri** [comment]
To test:
- compare: https://wpcalypso.wordpress.com/read/feeds/41934482 and
- https://calypso.live/read/feeds/41934482?branch=fix/reader/refresh-photo-only-character-count

**Comment by fraying** [comment]
Much better! 👍

**Pull request merged**
