### PR TITLE
Update terser to 5.2.1

### PR DESCRIPTION
**Pull request by sgomes**
Optional chaining will start making its way into the minification phase of the pipeline once Safari 14 ships (since this will mean all browsers in the `evergreen` build support optional chaining). Unfortunately, the current version of Terser we use does not support this syntax and will start failing.

This PR updates to the latest version of Terser, so that we're ready ahead of time.

#### Changes proposed in this Pull Request

* Update `terser` to 5.2.1
* Update `terser-webpack-plugin` to enable using the new `terser`.

#### Testing instructions

Smoke-test the live branch and ensure that the new Terser doesn't introduce any unexpected breakage.

### CODE REVIEW

**Comment by sgomes** [comment]
Looks like Terser somehow got worse, and now produces larger output 😞 Sadly, I think we'll need to just live with these new costs.

**Comment by sgomes** [comment]
Note: the output is now actually **smaller** than before, since I enable 2 passes on the compression. This only appears to add ~ 30s build time on the `Calculate ICFY stats / Build ICFY stats`, for reference.

**Comment by jsnajdr** [comment]
> Looks like Terser somehow got worse, and now produces larger output

@sgomes When I'm looking at the original ICFY comment, before it was updated after `passes: 2`, I see that most sections were getting smaller by ~80 bytes and gzipped sizes were getting larger by ~5 bytes. Was that the larger output you are referring to?

I'd like to reproduce the "output got larger" problem.

**Comment by sgomes** [comment]
@jsnajdr: The original comment has everything getting larger **in gzipped size** except for some async chunks. If you check the original comment in the history it's still there. E.g.:

```
name                   parsed_size           gzip_size
entry-gutenboarding        -1797 B  (-0.1%)     +487 B  (+0.1%)
entry-login                 -892 B  (-0.1%)     +265 B  (+0.1%)
entry-domains-landing       +387 B  (+0.1%)     +895 B  (+0.6%)
entry-main                  +350 B  (+0.0%)     +923 B  (+0.3%)
``` 

```
name                    parsed_size           gzip_size
post-editor                 -1470 B  (-0.1%)     +482 B  (+0.1%)
woocommerce                 -1406 B  (-0.1%)     +698 B  (+0.1%)
wp-super-cache              -1265 B  (-0.5%)      +76 B  (+0.1%)
domains                      -762 B  (-0.1%)     +113 B  (+0.0%)
purchases                    -671 B  (-0.1%)      +55 B  (+0.0%)
zoninator                    -633 B  (-0.2%)     +198 B  (+0.2%)
home                         -562 B  (-0.1%)      +65 B  (+0.1%)
plans                        -470 B  (-0.1%)      +43 B  (+0.0%)
checkout                     -403 B  (-0.0%)      +62 B  (+0.0%)
jetpack-connect              -336 B  (-0.0%)      +31 B  (+0.0%)
account                      -283 B  (-0.1%)       +5 B  (+0.0%)
reader                       -277 B  (-0.1%)      +94 B  (+0.1%)
people                       -256 B  (-0.1%)      +83 B  (+0.1%)
stats                        -234 B  (-0.0%)      +55 B  (+0.0%)
comments                     -207 B  (-0.0%)      +24 B  (+0.0%)
gutenberg-editor             -188 B  (-0.0%)      +43 B  (+0.0%)
help                         -167 B  (-0.0%)       +4 B  (+0.0%)
pages                        -163 B  (-0.1%)      +16 B  (+0.0%)
themes                       -151 B  (-0.0%)      +11 B  (+0.0%)
theme                        -151 B  (-0.0%)      +11 B  (+0.0%)
earn                         -140 B  (-0.0%)      +17 B  (+0.0%)
accept-invite                -140 B  (-0.0%)      +85 B  (+0.1%)
...
```

There are a lot of chunks getting smaller in parsed size but larger in gzipped size; I'm not sure if that's real or an artifact of how the bundle analyzer measures things.

If you want to reproduce locally, you can try commit f2d883876cf0347a030d7a2c28ee15dcd93f95a6.

**Comment by jsnajdr** [comment]
@sgomes Thanks for confirming! I was curious what part of `terser` compression comes from the syntax transforms, and what part comes from the mere variable name mangling and whitespace/comments removal. So I disabled compression in #45244. The result is that disabled compression inflates most chunks by ~7%, and the gzipped sized by ~4%.

**Comment by sgomes** [comment]
> @sgomes Thanks for confirming! I was curious what part of `terser` compression comes from the syntax transforms, and what part comes from the mere variable name mangling and whitespace/comments removal. So I disabled compression in #45244. The result is that disabled compression inflates most chunks by ~7%, and the gzipped sized by ~4%.

Oh, that's good data, thank you @jsnajdr! 👍

**Comment by jsnajdr** [comment]
Did some Terser learning today and I have some findings why we see the changes we do.

Suppose we have code like this:
```js
s.getItem("jetpack_cloud_redirect_path_expires_in");
s.setItem("jetpack_cloud_redirect_path_expires_in");
```

Since 5.2.0, Terser has a slightly different criteria whether to extract or inline variables and newly transforms this code into:
```js
let k = "jetpack_cloud_redirect_path_expires_in";
s.getItem(k);
s.setItem(k);
```

This makes the unzipped code shorter, but steals come compression opportunities from the gzip algorithm. The result is that the gzipped size is a few bytes bigger.

This gzip paradox is not new or rare: last year, we were experimenting with a webpack plugin that would optimize the `React.createElement` statements (that every React app has thousands of) and the [result was similar](https://github.com/Automattic/wp-calypso/pull/32445#issuecomment-485083894): unzipped code size is smaller, gzipped is bigger.

**What benefits do the two passes give us:**
I've seen two kinds of optimizations:

1. Coalescing `var` declarations:
```js
var a = 1; var b = 2;
// into
var a = 1, b = 2;
```
2. Doing innocuous code moves to save semicolons:
```js
a(1);function b() { return 1; };
// into
function b() { return 1; }a(1);
```

Apparently, some of these opportunities are created only after other code transforms are done: they were not in the original code.

**Review by jsnajdr — APPROVED** [review]
Looks ready to :ship:

I'm not excited about the `passes: 2` change. Build times and occasional Terser OOM errors are a big problem for us. On the other hand, I'd argue that adding a few bytes to the output, where the addition is a rather random coincidence, is not a _that big_ problem 🙂

**Comment by sgomes** [comment]
> I'm not excited about the `passes: 2` change. Build times and occasional Terser OOM errors are a big problem for us.

Yeah, I totally see where you're coming from. The gains are quite good on some chunks, though (2.7KB gzipped), so I think we should give it a fair shot. If `terser` is properly coded, the second pass won't take up any more memory than the first; it'll only take a bit more time.

**Comment by sgomes** [comment]
Thank you for the review, @jsnajdr! 👍

**Pull request merged**
