### PR TITLE
Interim update to ecommerce trial features

### PR DESCRIPTION
**Pull request by daledupreez**
Related to:
* #74099

## Proposed Changes

* This PR implements two interim changes to the features list for free eCommerce trials:
  - It replaces the current Google Analytics card with a Payment setup card
  - It removes the CTA links for each of the cards, as the links weren't implemented
    * We are working on the CTAs and tracking for these items in #74099

### Screenshot

Free trial features

## Testing Instructions

* Run this branch locally for via Calypso.live
* For a site on the free eCommerce trial, navigate to _Upgrades_ -> _Plans_ and then click on the "Free trials" tab
* Verify that none of the cards includes a CTA link
* Verify that you don't see a _Google Analytics_ card
* Verify that you see a _Get ready to be paid_ card -- it should appear in the second row

## Pre-merge Checklist

- [x] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [x] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [x] Have you checked for TypeScript, React or other console errors?
- [N/A] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)? _We want to get the change out ASAP, so we are not waiting for new strings_.
- [N/A] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

**Review by markbiek — APPROVED** [review]
Working as expected!

Not sure if this is a blocker but it goes to three rows on my screen and the spacing of last row is a little funky.

image

**Comment by verofasulo** [comment]
Hello 👋 

I just updated [the design to be implemented](https://www.figma.com/file/lD0gTB4IqGsmSmsnjZNaP6/Free-Trial---E2E-Experience?node-id=470%3A15526&t=tPB4bM1L2CipWIoq-4) - Changed the copy a bit to make it work with all the other cards as it was too long. Thank you!

**Comment by daledupreez** [comment]
@verofasulo, I've just pushed up the copy update in f5e82be.

@markbiek, we're tracking the spacing issue in https://github.com/Automattic/wp-calypso/issues/73319.

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/7845498

Thank you @daledupreez for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/7845498).

**Pull request merged**
