### PR TITLE
Plans & FAQ: Improve Colour Contrast

### LINKED ISSUE #35095: Plans: Poor contrast on subheadings
screen-shot-2019-07-08-at-1 08 04-pm

#### Steps to reproduce
1. Starting at URL: http://wordpress.com/plans/
2. View subheadings on each plan, as in the image above; note the lack of contrast between foreground text and white background.
3. These subheadings can probably use the CSS var `--color-text-subtle` for adequate contrast.

### PR DESCRIPTION
**Pull request by Aurorum**
#### Changes proposed in this Pull Request

This improves the plans contrast in three places by switching the variable to --text-subtle

1. The plans heading
Screenshot 2019-08-05 at 21 09 01

2. The discount text in Jetpack Connect
Screenshot 2019-08-05 at 21 07 59

3. The FAQ headings on the Plans page
Screenshot 2019-08-05 at 21 09 42

#### Testing instructions

Check the new colours and make sure the new variables are correctly assigned.

Fixes #35095

### CODE REVIEW

**Comment by Aurorum** [comment]
Conflicts resolved :)

**Review by millerf — DISMISSED** [review]
It needs some rebase.


And I think this one is already partly resolved:

Screenshot 2020-05-03 at 13 58 12


Also, where is the "The discount text in Jetpack Connect"?

**Comment by Aurorum** [comment]
Thanks @millerf - conflicts resolved! If you spawn a WP.org site with Jetpack (easiest way is by going to https://jurassic.ninja) then follow the prompts to connect Jetpack, you'll be taken to `/jetpack/connect/plans/site`. It's that tablet which contains the discount phrase.

Screenshot 2020-05-03 at 19 39 04

**Review by sixhours — APPROVED** [review]
This works well for me! Thanks for the fix. :)

**Pull request merged**
