### PR TITLE
Add Jetpack manual activation step with license key clipboard

### PR DESCRIPTION
**Pull request by rcanepa**
#### Changes proposed in this Pull Request

* Adds the last step of the Jetpack manual activation flow which shows users their license key.

#### Testing instructions

* Download this PR.
* Start Calypso with `yarn start`. 
* Go to `http://calypso.localhost:3000/checkout/jetpack/thank-you/licensing-manual-activate/jetpack_backup_daily` (you can try with other product slugs).
* Continue the flow until you arrive at `http://calypso.localhost:3000/checkout/jetpack/thank-you/licensing-manual-activate-license-key/:product`.
* Verify the product mentioned in the title matches the one in the URL.
* Verify you can copy the license key by clicking on the `Copy` button.
* Verify the UI looks fine in different viewport sizes.

**Notes**
- The license key is hardcoded. We still need to wire up some parts of the flow to carry the license key from the start to this step.
- I added support for a loading state in the `<LicensingActivating />` component that can be activated by passing the `isLoading` boolean prop.

Related to 1201096622142517-as-1201096622142548

##### Loading state
image

##### Loading finished
image

### CODE REVIEW

**Review by elliottprogrammer — APPROVED** [review]
Everything looks awesome. I don't see any issues.
LGTM! 👍

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/6946991

Thank you @rcanepa for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/6946991

Thank you @rcanepa for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/6946991).

**Pull request merged**
