### PR TITLE
Jetpack Cloud: display the filter section only if there are threats to show

### PR DESCRIPTION
**Pull request by rcanepa**
#### Changes proposed in this Pull Request

* Remove the filter section when there are no threats to show in Scan -> History.

#### Testing instructions

* Go to `http://jetpack.cloud.localhost:3000/`
* Go to Scan and select a site that **doesn't have** threats that have been fixed or ignored
* Verify the filter section doesn't show up
* Go to Scan and select a site that **has** at least one threat that has been fixed or ignored
* Verify the filter section does show up

##### With threats
image

##### Without threats
image

### CODE REVIEW

**Comment by ChaosExAnima** [comment]
While it seems to be okay, that area looks empty. @Automattic/jetpack-design, what are your thoughts about this?

**Comment by folletto** [comment]
Yes, that page needs an empty state. :)

**Comment by keoshi** [comment]
What super-fast @folletto said!

**Comment by rcanepa** [comment]
> Looking it over, I see it shows the filters in the loading state:
> Screen Shot 2020-05-12 at 11 20 43 AM
> 
> Can we hide those or replace them with a loading icon?

Good catch @ChaosExAnima ! I'll do that.

**Comment by rcanepa** [comment]
Placeholder added. Please let me know what you think @ChaosExAnima because it's the first time I add a placeholder and I'm not sure if I did it right. I had to introduce a div to be used as a placeholder simple because making the `SimplifiedSegmentedControl` component a placeholder made the placeholder appear too tall and I couldn't fix that (not sure why).

image

**Comment by rcanepa** [comment]
> Looks good, thanks @rcanepa!

🙇

**Pull request merged**
