### PR TITLE
SiteSettingsSecurity: Add Blurred Styling to Individual Settings

### PR DESCRIPTION
**Pull request by ockham**
Broken out of #25416.

Also, point the Jetpack Checklist items for Jetpack Monitoring and Jetpack Credentials directly to the corresponding settings.

### Testing Instructions

(Preferably use a JP site for which you haven't set up backup credentials yet so that option will actually be visible.)

* Land at `calypso.localhost:3000/settings/security/<jpSite>` and verify that no setting is blurred, and that everything works as before.
* Land at `calypso.localhost:3000/settings/security/<jpSite>#jetpack-credentials` and verify that the 'Jetpack Monitor' setting is blurred.
* Land at `calypso.localhost:3000/settings/security/<jpSite>#jetpack-monitor` 
and verify that the 'Jetpack Credentials' setting is blurred.
* Land at `calypso.localhost:3000/settings/security/<jpSite>#foo` and verify that no setting is blurred for an invalid `#fragment`.
* Finally:
  * Land at `calypso.localhost:3000/checklist/<jpSite>`
  * Click the 'Do it!' button next to the 'Jetpack Monitor' item.
  * Verify that you land at `calypso.localhost:3000/settings/security/<jpSite>#jetpack-monitor`, i.e. with the JP Credentials setting blurred.
  * Do the same for the checklist's 'Jetpack credentials' item.

_Note that the settings below 'Downtime Monitoring' aren't blurred yet -- that's blocked by #25444, #25445, and #25448._

### Design(ish) Question

Do we want `jetpack` in the `#fragment` names? Or rather just `#uptime-monitor` and `#credentials`?

### Screenshots

`#jetpack-credentials`:

image

`#jetpack-monitor`:

image

### CODE REVIEW

**Comment by ockham** [comment]
Needs some more tweaking...

**Comment by joanrho** [comment]
See p6TEKc-1TR#comment-4967.

**Comment by sirreal** [comment]
Does this PR need to be reviewed as it now, or is it being broken down?

**Comment by ockham** [comment]
> Does this PR need to be reviewed as it is now, or is it being broken down?

Actually closing this, see the discussion Joan linked to.

**Pull request closed without merging**
