### PR TITLE
Checkout: Update redirect processor to use explicit error handling

### PR DESCRIPTION
**Pull request by sirbrillig**
#### Changes proposed in this Pull Request

Currently payment processor functions have implicit error handling; if they throw an Error during their run, it's assumed that the error is a response from the payment processing service. The error is displayed to the user and that's it. If the error is a bug in the code, however, then the error needs to be reported to our dev teams, which will only happen if a React error boundary is hit. In order for this to work, we need to differentiate between "expected" errors (errors from the payment service) and "unexpected" errors (errors in the code that prepares the transaction data). To that end I've added a new explicit "error" response type for payment processors that can be used for expected errors. Once this has been added to all processors we can make the remaining errors trigger the error boundaries, which is prepared in https://github.com/Automattic/wp-calypso/pull/51427

This PR adds the explicit error response type to the redirect processors: Stripe redirect and WeChat Pay.

#### Testing instructions

There are two things to test: the regular Stripe redirects, and the WeChat Pay mobile redirects.

- Apply D45443-code to your sandbox to force Bancontact to be available.
- Set your user currency to EUR.
- Make a new purchase in checkout and select Bancontact as the payment method, entering any string in the "name" field.
- Verify that you are redirected to the Stripe test page, that it reads "Bancontact", and that the total is correct. (No need to complete the payment.)
- Set your user currency to USD.
- Apply D45650-code to your sandbox to force WeChat to be available.
- Apply https://gist.github.com/sirbrillig/17fc953647b2df974e8d975a5d4e160a to calypso to force the mobile-only redirect to run.
- Make a new purchase in checkout and select WeChat as the payment method, entering any string in the "name" field.
- Verify that you are redirected to the Stripe test page, that it reads "WeChat Pay", and that the total is correct. (No need to complete the payment.)

### CODE REVIEW

**Comment by nbloomf** [comment]
When I attempt a Bancontact purchase, I get a "Missing shopping cart parameter" which seems to be coming from the transactions endpoint:

Screen Shot 2021-04-01 at 3 48 12 PM

The style of the error notification is also wonky, but I don't think that is related. Here's the response from the transaction endpoint:

Screen Shot 2021-04-01 at 3 57 33 PM

**Comment by nbloomf** [comment]
I see the same error with WeChat.

**Comment by nbloomf** [comment]
Digging in a bit, it looks like the payload being passed to `submitWpcomTransaction` is a `Promise`, when the type indicates it should be a `WPCOMTransactionEndpointRequestPayload`:

Screen Shot 2021-04-01 at 4 14 09 PM

**Comment by nbloomf** [comment]
Works as expected now!

**Review by nbloomf — APPROVED** [review]

**Comment by sirbrillig** [comment]
Test failures ("failed to download chromium") are unrelated.

**Pull request merged**
