### PR TITLE
Nav redesign: Show masterbar and tidy up global sidebar

### PR DESCRIPTION
**Pull request by eoigal**
Fixes https://github.com/Automattic/dotcom-forge/issues/8040
Fixes https://github.com/Automattic/dotcom-forge/issues/8150
Fixes https://github.com/Automattic/dotcom-forge/issues/8151
Fixes https://github.com/Automattic/dotcom-forge/issues/8152

Combining PRs here to make it simpler to test and deploy.

https://github.com/Automattic/wp-calypso/assets/5560595/9a2264b3-f348-43f0-897d-6959fc44a241

## Proposed Changes

* This updates the layout to render the masterbar on the global pages (All sites, Reader and Me/Profile)
* This also updates the styles to move the pages content to make room for the masterbar
* This hides the global sidebar header & footer that should be no longer needed when we are showing the masterbar on all pages
* Removes back links from Reader and Me pages

## Why are these changes being made?

* Tidying up UX

## Testing Instructions

* Go to calypso.live and confirm masterbar loads and behaves on all global pages
* Confirm the sidebar works and is styled correctly at different dimensions

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Review by Addison-Stavlo — COMMENTED** [review]
Works as advertised! Im seeing 2 smaller layout issues with this change.

On the reader (both stream and full post page) we may need to update the content frame size. This change seems to just push it down, creating an extra scrollbar on the right:

content-frame-scroll

On the /sites area I noticed the frame borders are different sizes on each side, most exaggerated on the bottom edge

Screenshot 2024-07-08 at 12 33 22 PM

On production the top, right, and bottom borders of the content frame seem even. Here it seems like we have 3 different sizes.

**Comment by eoigal** [comment]
> This change seems to just push it down, creating an extra scrollbar on the right:

This should be fixed now, thanks for review!

https://github.com/Automattic/wp-calypso/assets/5560595/d48e6cec-118d-402b-9cc6-344d93159a11

**Review by fushar — CHANGES_REQUESTED** [review]
On hosting dashboard, the top of the page is cut off and there are erroneous paddings on the bottom of the page:

image

**Review by fushar — COMMENTED** [review]
If you click Domains, AND THEN refresh the page, the top padding is gone:

image

It's super weird. Seems like CSS the different when you refresh the page vs when you come from /sites.

It's happening on site hosting dashboard as well when I'm trying to debug the previous issue, which makes it very hard to fix... 😭

**Review by fushar — COMMENTED** [review]
So, another key issue here is that somehow, in this PR, it loses the padding-bottom, but somehow the sites table has a gap at the bottom. This caused, as soon as I want to fix the Domains / Plugins page by introducing a padding-bottom, things start falling apart, e.g. a vertical scrollbar is shown where it shouldn't be...

|Production|This PR|
|-|-|
|image|image|

**Comment by taipeicoder** [comment]
Jotting down some regression issues I noticed.

Plugins Marketplace sticker header.
| Before | After |
| --- | --- |
| Screenshot 2024-07-10 at 2 53 42 PM |  Screenshot 2024-07-10 at 2 53 56 PM|

Theme Showcase needs horizontal padding.
Screenshot 2024-07-10 at 3 04 28 PM

Extra right/bottom spacing in the smaller screens.
| Before | After |
| --- | --- |
| Screenshot 2024-07-10 at 3 05 39 PM |  Screenshot 2024-07-10 at 3 05 29 PM|

**Review by fushar — DISMISSED** [review]
Looking good now, nice collaboration!

**Comment by fushar** [comment]
@taipeicoder Ah, didn't see your message in my browser tab before I hit the approve button. Looking at them now!

**Review by davemart-in — APPROVED** [review]
Went through and tested everything I could think to test. Looks good enough to ship from my perspective. There are a few minor things, but we can fix them up after this PR.

**Review by fushar — APPROVED** [review]

**Comment by Addison-Stavlo** [comment]
I pushed a change to the global masterbar that appears in mobile breakpoints that toggles the global sidebar. This should allow us to ship this early, but is also very temporary as will be overridden by the other[ unified masterbar PR](https://github.com/Automattic/wp-calypso/pull/92472/).

I have removed the site card and command prompt buttons here, and added items for the reader, me, and help center (since these used to exist within the global sidebar before this PR, and these users would not have access to these items without adding them here).

BEFORE (site overview selected to show the conditional site card item)

Screenshot 2024-07-10 at 9 45 28 AM



AFTER

Screenshot 2024-07-10 at 10 07 45 AM


The two removed items seem less necessary here now. And don't seem to fit in place with the necessary items we are adding, as there isnt enough room for all/ items get pushed off the screen with too many, ex:

Screenshot 2024-07-10 at 9 44 47 AM

(no access to notes, and this is also without having the reader link).

**Pull request merged**
