### PR TITLE
Translate and extract features for eCommerce trial plans page

### PR DESCRIPTION
**Pull request by daledupreez**
Related to #72797

## Proposed Changes

This PR involves two core changes:
* The list of eCommerce plan features has been refactored into a new `getECommerceFeatureSets()` function in `client/my-sites/plans/ecommerce-trial/ecommerce-features.ts`, which also involved renaming the existing `TrialFeatureCardProps` type to `ECommercePlanFeatureSet`, and wrapping retrieval of the features list in `useMemo()`
* Translating all the strings in the feature list so we can get this queued up for next week's translation bundle, which will go out super-early on Monday morning (see p1676020817196269/1676019525.391739-slack-C02AED43D)
  - This also involved updating some of the types in `ECommercePlanFeatureSet`

## Testing Instructions

* Run this branch locally or via the Calypso.live branch
* For a site with the eCommerce Trial plan, navigate to _Upgrades_ -> _Plans_
* Verify that all the plan features are visible and can be looked at directly
* Verify that there are no console errors

## Pre-merge Checklist

- [x] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [x] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [x] Have you checked for TypeScript, React or other console errors?
- [x] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [N/A] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)? -- _We'll queue these up either by adding the label later today, or by merging as this feature hasn't launched yet._
- [N/A] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

## Screenshots

Screenshot 2023-02-10 at 12 23 39
Screenshot 2023-02-10 at 12 24 19
Screenshot 2023-02-10 at 12 24 01

### CODE REVIEW

**Review by nelsonec87 — APPROVED** [review]
LGTM

Only have two comments:
1. The "Marketing & Growth" picture is wrong. I'm making a PR to fix that (https://github.com/Automattic/wp-calypso/pull/73231) 
2. Maybe change the `ECommercePlanFeatureSet` component folder name to match the component name?

**Comment by daledupreez** [comment]
Thanks for the review, and for catching that issue with the image, @nelsonec87!

> 2. Maybe change the `ECommercePlanFeatureSet` component folder name to match the component name?

Regarding this comment, I am not sure which component folder you're referring to. I changed the name of the prop's type, but not the component name -- that is still `TrialFeatureCard`, and the getter function is neutral, but could also be changed. I am not sure which one you thought should be changed.

**Comment by nelsonec87** [comment]
> Thanks for the review, and for catching that issue with the image, @nelsonec87!
> 
> > 2. Maybe change the `ECommercePlanFeatureSet` component folder name to match the component name?
> 
> Regarding this comment, I am not sure which component folder you're referring to. I changed the name of the prop's type, but not the component name -- that is still `TrialFeatureCard`, and the getter function is neutral, but could also be changed. I am not sure which one you thought should be changed.

Nvm, I misread the change!

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/7806840

Thank you @daledupreez for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/7806840).

**Pull request merged**
