### PR TITLE
NUX Signup: consolidate site topic submission code.

### PR DESCRIPTION
**Pull request by southp**
#### Changes proposed in this Pull Request

There are currently two ways of submitting a site topic during sign up: one via a query string and one via the site topic step. This PR attempts to de-duplicate the code for filling site topic info.

#### Parent PR
#28871 .

#### Testing instructions

1. Go through the improved onboarding flow from http://calypso.localhost:3000/start/onboarding and the site topic step should work as expected.
1. Accessing http://calypso.localhost:3000/start/onboarding?vertical=foo, `getState().signup` should show that the site topic, the dependency store, and the progress store are all filled in as expected.

### CODE REVIEW

**Comment by scruffian** [comment]
This looks good. 🚢 

Not related to this, but should we allow users to submit an invalid vertical?

**Comment by southp** [comment]
@scruffian About
> Not related to this, but should we allow users to submit an invalid vertical?

I think the reason that we allow users to enter arbitrary verticals is mainly because we don't have a comprehensive list just yet. Once the list is there, we can surely revisit if we want to restrict it or not. From a gut feeling, I think we should restrict it. However, maybe we'd still not want to restrict it so that we can collect more inputs that we'd want to make them into the list.

cc @michaeldcain and @adamziel here for more insights :)

**Comment by ramonjd** [comment]
> should we allow users to submit an invalid vertical?

A _kind of_ related question:

**Comment by ramonjd** [comment]
screen shot 2018-12-07 at 4 42 48 pm

Was about to comment and tabbed to the wrong button :(

**Pull request merged**
