### PR TITLE
Components: remove the data-stores dependency

### PR DESCRIPTION
**Pull request by jsnajdr**
Removes the `data-stores` dependency from the `components` package. The only component that was using it was `HappinessEngineersTray`, and that component can be now removed because it was used only in HappyChat-related Help Center code, which is now deleted.

There was also a `data-stores` query in a devdocs demo for `Gravatar`, easily replaced with "generic user" from existing `Gravatar` tests.

Finally, the `useHappinessEngineersQuery` hook can be removed from `data-stores`, too.

### CODE REVIEW

**Comment by jsnajdr** [comment]
I'll have to rework this, the `HappinessEngineersTray` is actually used at a lot of places 🙁 Strange my vscode search didn't find them.

It'll be better to call the query from `data-stores` in userland code, and the component in `components` will only render the data. That removes the `data-stores` dependency as well.

**Comment by tyxla** [comment]
Yeah, the `HappinessEngineersTray` component is solely used in Calypso's client, so we should be able to move it back to the `components` dir there (rather than removing it).

Note that that component was moved to `@automattic/components` because it was used in the help center, but it's no longer the case since https://github.com/Automattic/wp-calypso/pull/63459.

**Comment by tyxla** [comment]
Suggested moving the component in #86538

**Comment by tyxla** [comment]
This can be closed in favor of #86538

**Pull request closed without merging**
