### PR TITLE
Tests: Move TinyMCE plugin tests to single test runner

### PR DESCRIPTION
**Pull request by aduth**
Related: #3942

This pull request updates and moves the tests contained within the following directories to be compatible with and run by the single test runner:
- `client/components/tinymce/plugins/contact-form`
- `client/components/tinymce/plugins/media/restrict-size`
- `client/components/tinymce/plugins/wpcom-sourcecode`

__Testing instructions:__

Verify all tests pass by running `npm run test-client`.

/cc @gziolo

### CODE REVIEW

**Comment by gziolo** [comment]
@umurkontaci @blowery could you help here? I'm off today, code changes look good, though I didn't test this one at all. It looks like it needs to be rebased.

**Comment by umurkontaci** [comment]
@aduth Code :+1: Tests :+1: . Needs a rebase and good to go.

**Comment by blowery** [comment]
hah, i ran over these. rebasing to pick out the bits that still apply.

**Comment by aduth** [comment]
@blowery : Was it intentional to omit changes to `client/tests.json` ?

**Comment by gziolo** [comment]
I don't think so :)

**Comment by blowery** [comment]
They're already there in https://github.com/Automattic/wp-calypso/pull/4341 which landed just before this

**Comment by aduth** [comment]
Ah, I understand now. Thanks for clarifying.

**Comment by blowery** [comment]
Yeah, sorry for running over your toes with that PR.

**Comment by aduth** [comment]
>Yeah, sorry for running over your toes with that PR.

Better too much effort porting than too little :laughing:

**Comment by gziolo** [comment]
They landed before, nice! I better focus on being off for the rest of my day off :D

**Pull request merged**
