### PR TITLE
Plans 2023: Update WooCommerce plans to use PlansFeaturesMain and intent system

### LINKED ISSUE #78472: Plans 2023: Update WooExpress to use PlansFeaturesMain for plans
WooExpress currently imports and uses `plans-features-2023-grid` directly (presumably to render a tailored plans mix). This should be updated to go through `PlansFeaturesMain` in line with everything else, especially since the introduction of "intent" system in https://github.com/Automattic/wp-calypso/pull/77667. 

`plans-features-2023-grid` should/will go through a series of "simplifications" next to become a proper package, and this may be the main blocker from doing so.

### PR DESCRIPTION
**Pull request by chriskmnds**
Fixes https://github.com/Automattic/wp-calypso/issues/78472
Parent: https://github.com/Automattic/wp-calypso/pull/78731

> WooExpress currently imports and uses plans-features-2023-grid directly (presumably to render a tailored plans mix). This should be updated to go through PlansFeaturesMain in line with everything else, especially since the introduction of "intent" system in https://github.com/Automattic/wp-calypso/pull/77667.
> 
> plans-features-2023-grid should/will go through a series of "simplifications" next to become a proper package, and this may be the main blocker from doing so.

## Proposed Changes

- WooExpress plans page is now synced along with the rest to use `PlansFeaturesMain` and the new "intent" system
- ~`hideUnavailableFeatures` used previously also removed as it's redundant now in new framework~

### Need to confirm

There are some deviations from production that need clarifying (not sure which one is correct actually):

- **(Now) `Free domain for one year` and `Live chat support` not "ticked" in comparison grid for monthly plans:**

Screenshot 2023-07-03 at 1 09 51 PM

- **(Now) Plan type selector shown above comparison grid (wasn't visible previously):**

Screenshot 2023-07-03 at 1 08 55 PM

### TODO

- [x] Tune the default "intents" used or mark with a TODO to inform upcoming work

## Testing Instructions

* Go through `/setup/wooexpress` and grab the site created in the end
* Go to `/plans/[woo site]` and observe/test plans grids work as before (given any deviations mentioned above)

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

**Comment by chriskmnds** [comment]
@daledupreez @sixhours (or someone else from @Automattic/serenity ?) can you please review and confirm direction with parts under "**Need to confirm**" in the description?

**Comment by jeyip** [comment]
## Testing
### Requirements
- [x] Go to /plans/[woo site] and observe/test plans grids work as before ( noting deviations below )
  - Free domain for one year and Live chat support not "ticked" in comparison grid for monthly plans
  - Plan type selector shown above comparison grid (wasn't visible previously) @chriskmnds I see the plan type selector rendered in both production and this branch 🤔 From what I can tell it doesn't appear to be a deviation anymore.
- [x] Can still purchase plans
- [x] Plans feature grid has the same listed features
- [x] Plans comparison grid has the same listed features and the same check marks
- [x] Plans prices remain unchanged

### Notes
For others testing, there were several differences I saw between Calypso dev on this branch and production. I was, however, seeing the same differences when switching to Calypso dev `trunk`, so I don't believe that those are deviations that are caused by this PR 

1. I'm seeing the `Plus` plan being displayed in Calypso dev while it isn't being displayed in production. I'm also, however, seeing `Plus` in Calypso dev **trunk**
2. The Plans pricing header fonts are different in the plans comparison grid. Again, seeing the same differences in `trunk`
3. There is an Enterprise ecommerce banner that appears at the bottom of the plans page in production.

### Browsers
- [x] Chrome

Gentle nudge for @daledupreez @sixhours. When y'all or team Serenity have time, could any of you take a look? The testing looks good on my end

**Review by jeyip — APPROVED** [review]
+1 from me

For others testing, I had questions about removal of the `AsyncLoad` component, but there's more context and explanation here p1688400095564729-slack-CV2TX2PAN

**Comment by chriskmnds** [comment]
Thanks @jeyip . It should be aligned with production now. Folks removed the plus plan in a recent commit 🤷‍♂️
I'll do a round of testing and ship Monday midday.

**Pull request merged**
