### PR TITLE
Inline Help: Adding internal Calypso links to inline help search results.

### PR DESCRIPTION
**Pull request by ramonjd**
## About this PR

This is an experimental feature that enables 'admin section' search results, that is, it surfaces sections of Calypso based on a search in the inline help field.

Screen Shot 2019-04-02 at 5 03 45 pm

The _down-the-track-some-day-blue-sky_ idea is to create a stand alone filter library that might we employ in other features, for example, to filter the sidebar menu items:

Screen Shot 2019-04-01 at 10 56 11 am

## Testing instructions

This feature is currently behind a development feature flag `help/admin-section-search`.

Open the inline help, making sure you have a site selected. For example, start here:

`http://calypso.localhost:3000/view/{yoursweettestsite}.wordpress.com`

Also search when no site is selected, e.g., `http://calypso.localhost:3000/me` 

You should be asked to select a site should you click on a section that requires one.

The list of admin sections is incomplete, but you can search for terms such as `'Add a domain'`, `'user'`, `'analytics'` and whichever other terms tickle your fancy, bearing in mind the [current definitions](https://github.com/Automattic/wp-calypso/pull/31903/files#diff-5cf1c6b9497fdc569ac7d61cb67e6958R18).

Clicking on a search results should also trigger a tracks event – `calypso_inlinehelp_admin_section_search` – with the following data:

```
{
    link: 'https://the-link-you-clicked-on.com',
    search_term: 'the search term',
}
```

## Notes

We might be able to extend and continue with #27173 (localizing the help text and links) after this PR. At the moment, help text and support doc links are in English.

### CODE REVIEW

**Comment by shaunandrews** [comment]
This is a pretty cool idea.

- I'm not sure about the "Support documentation:" heading. It might just be the visuals, but I'm not sure its needed.
- The "Go to directly to:" heading might be better worded. Maybe something like "Navigate to"? (Eh, thats not great either...)
- Keyboard navigation is broken. Up/Down arrows navigate through both lists when they're displayed.
- Maybe we could add the icon for the relevant sections? So if its a settings screen, show the cog. (This might be strange when the new navigation work goes live.)

**Comment by ramonjd** [comment]
Thanks for checking this PR out @shaunandrews 

This was an experiment really, so I'm happy that it has received any feedback at all!

> I'm not sure about the "Support documentation:" heading. It might just be the visuals, but I'm not sure its needed.

Gone!

> The "Go to directly to:" heading might be better worded. Maybe something like "Navigate to"? (Eh, thats not great either...)

Definitely. I'll get rid of the typo too :)

> Keyboard navigation is broken. Up/Down arrows navigate through both lists when they're displayed.

Nice catch. Thanks!

> Maybe we could add the icon for the relevant sections? 

Easy to try this. Wondering if it might look cluttered. Only one way to tell :)

**Comment by shaunandrews** [comment]
> Show me where I can:

Oooh, this is nice. A little wordy, maybe, but I like that it helps describe what the navigation links do.

I really dig the icons. It helps separate the navigation links from the support doc links.

The list is rather long. I wonder if we restrict the number of navigation links to 2 or 3, with a way to expand.

**Comment by ramonjd** [comment]
> I wonder if we restrict the number of navigation links to 2 or 3

Sounds possible. I might add a weighting and sort function to the results perhaps... I'll give it a go. 

Thanks!!

**Comment by ramonjd** [comment]
Will revive when the spirit reawakens

**Comment by lancewillett** [comment]
Big +1 for this feature. It's a power feature, yet still a good addition as it can help both power users move quickly, and newer folks discover settings they didn't know about.

The most helpful pathway to me is that you don't need to know the name of the top-level menu — and since we started collapsing the sections, it's much harder to find things now.

CC @davemart-in

**Comment by davemart-in** [comment]
@ramonjd what is the status of this feature? Do you still have plans to come back to it? I think this could be impactful for a number of use cases.

**Comment by davemart-in** [comment]
> The most helpful pathway to me is that you don't need to know the name of the top-level menu — and since we started collapsing the sections, it's much harder to find things now.

I'd say that it's always been hard to find things within WP. I do feel strongly that adding search/filter functionality would be a big win for both power users and newbies. 

Starting this out in the inline help popup seems like a smart move. If we see promising results, we might consider proposing a top-level search field in the masterbar that would return a variety of results (like posts, pages, links to functionality, links to help docs, etc...) similar to Mac spotlight search.

**Comment by ramonjd** [comment]
Hi @davemart-in ! 

> what is the status of this feature?

This was something I just whipped up in my spare time, which means it has a status of `purgatory` :)

Needs a rebase, and the results is static so it probably needs updating too.

> Do you still have plans to come back to it?

Other work booted it off my radar, and I don't have the spare time to revive it in the nearish future.

However it works (for English), and has synonym matchers too, so if someone has the time and motivation to update the results list it could be easy to A/B test. 🤞 

cc @Automattic/start-dev

**Comment by lcollette** [comment]
Super useful, @ramonjd! I'm going to pull this into the Manage team's focus as we consider search within Calypso.

**Comment by gwwar** [comment]
@lcollette I'm going to create a tracking issue in favor of a closed PR

**Comment by gwwar** [comment]
Added https://github.com/Automattic/wp-calypso/issues/38860 for tracking

**Comment by amamujee** [comment]
@gwwar did we decide not to merge this?

**Pull request closed without merging**
