### PR TITLE
Gutenboarding: Use Card component from package

### PR DESCRIPTION
**Pull request by sirreal**
#### Changes proposed in this Pull Request

Remove duplicated/copied `Card` and use it from `@wordpress/components`.

Replaced #38607.

#### Testing instructions

Verify that Gutenboarding still works.

### CODE REVIEW

**Comment by chriskmnds** [comment]
Still getting some console errors in live preview:

Screenshot 2020-01-13 at 3 08 04 PM

and a SASS error locally (?) - this in particular:

```
    SassError: SassError: Error: Specified z-index `.edit-post-editor-regions__header` does not exist in the mapping
            on line 133 of node_modules/@wordpress/base-styles/_z-index.scss, in function `z-index`
```

**Comment by sirreal** [comment]
> Still getting some console errors in live preview:
> 
> Screenshot 2020-01-13 at 3 08 04 PM

This should be fixed by using `as` prop over `withComponent` method, which doesn't exist as we'd expected 😬 

> and a SASS error locally (?) - this in particular:
> 
> ```
>     SassError: SassError: Error: Specified z-index `.edit-post-editor-regions__header` does not exist in the mapping
>             on line 133 of node_modules/@wordpress/base-styles/_z-index.scss, in function `z-index`
> ```

I suspect this is from a stale package version you have locally. I don't see the issue.

This will create a typecheck error that can safely be ignored, the type definitions need to be updated.

**Comment by sirreal** [comment]
Fixing/updating type defs: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/41566

**Comment by sirreal** [comment]
Rebased.

**Comment by sirreal** [comment]
Rebased.

**Pull request merged**
