### PR TITLE
VideoPress site options step (WIP)

### PR DESCRIPTION
**Pull request by thedebian**
#### Proposed Changes

This PR adds the site options step in the videopress flow.

#### Testing Instructions
* Apply this PR
* Go to http://calypso.localhost:3000/setup/intro?flow=videopress
* ✅ If you're logged in, you should be redirected to the options step
* ✅ If you're not logged in, you should be redirected to the account creation step, then to the options step

Fixes Automattic/greenhouse#1290

### CODE REVIEW

**Review by roundhill — CHANGES_REQUESTED** [review]
Works pretty well, but noticed a few things. There's a grey bar at the top that is some kind of progress bar but I'm not sure why it looks like that. It could be because the steps progress is added in #67552? Also, the WordPress logo disappeared next to the `VideoPress` text at the top. I think we wanted to call this `Video Portfolio` as well.

Screen Shot 2022-09-09 at 2 13 40 PM

**Comment by thedebian** [comment]
> There's a grey bar at the top that is some kind of progress bar but I'm not sure why it looks like that. It could be because the steps progress is added in #67552? 

Probably, regarding visuals, I didn't look much into doing anything else than basic styling, so we could still have the full stepper before starting to integrate things beautifully (mainly because it seems things are not fully settled yet).

> Also, the WordPress logo disappeared next to the `VideoPress` text at the top. I think we wanted to call this `Video Portfolio` as well.

That's one of the moving things I was talking about :D : pxWta-1vr-p2#comment-5911

**Comment by pgk** [comment]
> Works pretty well, but noticed a few things. There's a grey bar at the top that is some kind of progress bar but I'm not sure why it looks like that. It could be because the steps progress is added in #67552?

Yes this will be ok once the blue progress bar (added in #67552) is merged I think. The pr will also address the Video Portfolio thing, so no worries there!

**Review by pgk — APPROVED** [review]
worked great for me after an initial yarn hiccup. I think most of the points Dan made will be addressed by https://github.com/Automattic/wp-calypso/pull/67552 and his points there by this one!

**Pull request merged**
