### PR TITLE
Gutenberg: Include App Banner

### LINKED ISSUE #34460: App Banner: Nudge to the mobile app doesn't show on block editor (Gutenberg)
#### Steps to reproduce
1. Starting on a mobile device at URL: https://wordpress.com/post
2. Select a site to start a new post. Note whether you see an app banner at the bottom of the screen.
3. Switch to the other editor. (If you started in the block editor, tap the 3-dot menu in the top right and select "Switch to Classic Editor." If you started in the classic editor, tap the Settings icon in the top menu to open the sidebar, select "Learn more" on the block editor prompt, and select "Try the block editor.")
4. When the other editor loads, note whether you see an app banner at the bottom of the screen.

#### What I expected

I expect the block editor to include an app banner like the one seen in the classic editor:

#### What happened instead

The block editor shows no app banner:

#### Browser / OS version

Safari on iPhone XS, iOS 12.3.1

#### Context / Source
#manual-testing

### PR DESCRIPTION
**Pull request by Aurorum**
#### Changes proposed in this Pull Request

Includes the App Banner in Gutenberg

Screenshot 2019-07-10 at 22 01 43

#### Testing instructions

#16124 describes getting the banner to appear more eloquently than I could, but full disclaimer, I just removed the bit of logic and I'm not exactly sure how to test to make sure it leads to the right place. Would appreciate verification that it does. :)

Fixes #34460

### CODE REVIEW

**Comment by Aurorum** [comment]
Resolved conflicts and made sure the PR works with the image migration changes. :)

**Comment by simison** [comment]
Does this banner appear when customers first time land on block editor? (asking because there's already a lot of things competing of attention there)

**Comment by noahtallen** [comment]
@simison yes, I think it can if they haven't dismissed it yet. It does not seem to show up if they already dismiss it elsewhere. (you're right, there will probably be plenty to clean up around the onboarding experience into the editor. perhaps a page could go into the welcome guide instead?)

**Comment by simison** [comment]
>It does not seem to show up if they already dismiss it elsewhere. 

Right, but these would be mostly new users who never dismissed anything in wpcom before. :-)

**Comment by noahtallen** [comment]
wouldn't they see a banner on a calypso screen before they get to the editor?

**Comment by rachelmcr** [comment]
> wouldn't they see a banner on a calypso screen before they get to the editor?

There are banners on the Reader, Notifications, and Stats screens in Calypso, as well.

For any changes to the banners, please loop in the Apps division in the conversation as these banners are our biggest source (by far) for encouraging WordPress.com customers to try the apps.

**Pull request merged**
