### PR TITLE
Reader Exploration: vertical redesign

### PR DESCRIPTION
**Pull request by samouri**
_wip_ - playing with sidebarless topbar nav

example:
screen shot 2017-07-26 at 11 00 27 am

original design credits @fraying

### CODE REVIEW

**Comment by samouri** [comment]
open question: tags/lists? how do they fit.

**Comment by fraying** [comment]
I love this so much I could cry.

Here's some stuff we'd have to figure out to move this forward:

- How it works at all possible screen widths.
- Changes to the internal pages to make it all look/work right.
- Scrolling behavior. Should the nav scroll with the page and then reappear on scroll up?
- TAGS: How to follow a new tag?
- Lists: How to show? Or time for them to disappear?

And probably other things I'm missing.

Also: Would want to try this as a small percentage AB test to see how the metrics change.

**Comment by samouri** [comment]
>How it works at all possible screen widths.

I'm thinking that at the smallest width we convert the search bar to just a search icon so there is room for both tags/lists.

>  Changes to the internal pages to make it all look/work right.

besides for small css tweaks to various top-margins, is there anything else that looks funky?


> Scrolling behavior. Should the nav scroll with the page and then reappear on scroll up?

I like it as it is now (fixed), but I'd be happy to test it out the other way as well.

> TAGS: How to follow a new tag?

No ideas yet. Will need to ponder

> Lists: How to show? Or time for them to disappear?

Same showing mechanism as tags.

**Comment by aaronyan** [comment]
This is so beautiful. And exciting! Thanks @samouri for exploring this.

**Comment by samouri** [comment]
another question: what do we do about follow by url? current visuals would be strange

**Comment by fraying** [comment]
@samouri Not sure what you mean

**Comment by fraying** [comment]
@samouri Ah! Now I getcha. Thanks.

**Comment by samouri** [comment]
decided to punt on this for awhile

**Comment by apeatling** [comment]
@samouri Does this one still have a chance of being relevant in the future?

**Comment by blowery** [comment]
Closing while punted.

**Pull request closed without merging**
