### PR TITLE
Framework: Rename .jsx files to .js

### PR DESCRIPTION
**Pull request by ockham**
To play more nicely with http://2ality.com/2017/06/pkg-esnext.html, which I'm going to enable soon (for Project Hubris, and general tree-shaking goodness). Plus, the whole `.jsx` extension stuff is kinda obsolete anyway these days. (Edit: Okay, it's possible to use Webpack's `resolve.extensions` to work around this. Still obsolete.)

In a nutshell, untranspiled `.js` files are recognized by tools that can handle ES6(+) code (such as webpack), while untranspiled `.jsx` files aren't.

To test:
* `make clean && make run`. Takes a while.
* Test all the things! Specifically:
  * A Calypso section you know well
  * `/devdocs/design`
  * SSR: Check `/themes` and `/theme/mood` while logged out. Verify that the Page Source contains theme description etc.

### CODE REVIEW

**Comment by aduth** [comment]
Does changing `.jsx` to `.js` affect syntax highlighting in GitHub? Something I've been meaning to check, since we standardized `.js` as well in Gutenberg.

**Comment by ockham** [comment]
> Does changing `.jsx` to `.js` affect syntax highlighting in GitHub? Something I've been meaning to check, since we standardized `.js` as well in Gutenberg.

Hmm, doesn't look great :slightly_frowning_face: 

https://github.com/Automattic/wp-calypso/blob/e73e74cd0d5d9f90f9f8f178a696fdd33799ae10/client/account-recovery/reset-password-form/index.jsx#L100 vs https://github.com/Automattic/wp-calypso/blob/96e7d665a27de120d873007cd5f9746f1a553dfe/client/account-recovery/reset-password-form/index.js#L100

**Comment by apeatling** [comment]
@ockham Is this something we still want to do?

**Comment by ockham** [comment]
Nah, let's close it. Losing GH formatting would kinda suck. Easy enough to use Webpack's `resolve.extensions` setting.

**Pull request closed without merging**
