### PR TITLE
Migrate Notice styles to webpack

### PR DESCRIPTION
**Pull request by arunsathiya**
#### Changes proposed in this Pull Request

- Import `Notice` style with webpack. Details on https://github.com/Automattic/wp-calypso/issues/27515

#### Testing instructions

- Visit `/devdocs/design/notice` on the live branch available below
- Ensure the design/visual appearance for all notices looks the same as this page's view on `master` branch / before this PR

### CODE REVIEW

**Comment by arunsathiya** [comment]
https://github.com/Automattic/wp-calypso/blob/175d60b4d6b798f4fec3e0bc76c6d43575eec51c/client/components/notice/style.scss#L214 

Should we define `margin-bottom: 24px;` here, for these compact notices to match the styling that normal notices have? 

Currently when two compact notices are used, they appear to be mashed together. 

Screenshot 2019-04-01 at 11 07 32
Screenshot 2019-04-01 at 11 07 38

**Comment by arunsathiya** [comment]
https://github.com/Automattic/wp-calypso/blob/175d60b4d6b798f4fec3e0bc76c6d43575eec51c/client/components/notice/index.jsx#L127

Okay to disable the linter warnings here for now? I am not sure how to fix these warnings currently. Need to read up. 🙃Also, I feel that, that would be a task for a separate PR.

**Comment by blowery** [comment]
Notice is a fun one to review. It's a commonly used component and also a bit of a specificity nightmare. Notice itself often relies on `(0, 2, 0)` specificity to establish styles, like `.notice.is-success { margin: 0 }`. When components that override notice styles do so, they should up their specificity to ensure their overrides take, regardless of the rule order. So a good override would be `.my-component .notice.is-my-component { ... }`. Unfortunately many Notice overrides take the form `.my-component .notice { ... }`, which has the same specificity as many notice rules. We have to check each one in turn to make sure things work as expected, even if the component css loads before the notice css.

**Comment by arunsathiya** [comment]
I have a feeling this is half-baked and not tested properly. :) I am going to close this PR, allowing other contributors to attempt a proper work.

**Pull request closed without merging**
