### PR TITLE
Gridicons: Add ecommerce gridicons

### PR DESCRIPTION
**Pull request by kellychoffman**
Adds 11 new ecommerce Gridicons that were part of the latest commit to the Gridicons repo: https://github.com/Automattic/gridicons/commit/6e8baf2467df3ecb41c177d1fa1645dd8b7573d8

- coupon
- cross-circle
- ellipsis-circle
- money
- pause
- product-downloadable
- product-external
- product-virtual
- product
- refund
- shipping

Check them out by going to: http://calypso.localhost:3000/devdocs/design/gridicons

Test live: https://calypso.live/?branch=add/ecommerce-gridicons

### CODE REVIEW

**Comment by rickybanister** [comment]
These look good!

Unrelated to this PR, but we should probably display the icons on the icons specific page of the devdocs.

**Comment by drw158** [comment]
Hm I think a few other icons should have been updated, like the Help icon and the Briefcase icon.

screen shot 2016-06-16 at 10 49 40 am

**Comment by kellychoffman** [comment]
Updated help icons, and added the read more icon. Briefcase is already in.

**Comment by drw158** [comment]
Briefcase is already in but it was updated. Is there a way to copy and paste the whole file just to make sure we get everything?

**Comment by drw158** [comment]
Or maybe the devdocs just are out of sync. The briefcase shown there is not the most recent one.

**Comment by kellychoffman** [comment]
Briefcase updated.

**Comment by drw158** [comment]
I just pushed a change that updated a lot of changes we've made to gridicons. Looks like we haven't updated it on calypso in awhile. 

@jancavan Have you been using the gridicon component for the new Reader follow icon? I noticed that those icon have been added either.

**Comment by drw158** [comment]
cc @folletto just to make sure we are doing this right

**Comment by jancavan** [comment]
@drw158 I think so. Is there something I'm missing?

**Comment by drw158** [comment]
@jancavan It looks like the example file (the one the devdocs uses) was never updated with the new Reader icons, but the component Gridicon file _was_ updated with the new icons at some point. I was just making sure that the new Reader icons were using the Gridicon component (the icons were not showing up on devdocs).

Looks like the 2 files are now completely up to date with this PR though.

**Comment by jancavan** [comment]
> It looks like the example file (the one the devdocs uses) was never updated with the new Reader icons

Oh that's right. Thanks for updating it.

**Comment by drw158** [comment]
This is good to 🚢 

Appears to be working correctly

**Pull request merged**
