### PR TITLE
Add Jetpack Cloud Settings Host Credentials Status

### PR DESCRIPTION
**Pull request by cbauerman**
#### Changes proposed in this Pull Request

**Motivation**: Add component for top status durning new host-specific credential flow

* Add `<ConnectionStatus />` component to new credentials settings page
* A couple file org changes

Untitled 10

#### Testing instructions

1. boot `env ENABLE_FEATURES=jetpack/server-credentials-advanced-flow yarn run start-jetpack-cloud`
2. verify the `settings` page now matches the "after" screenshot above

### CODE REVIEW

**Review by rcanepa — APPROVED** [review]
LGTM!

On a small viewport, the Providers container is wider than the rest of the pieces of the UI. Is that expected?

**Comment by cbauerman** [comment]
> LGTM!
> 
> On a small viewport, the Providers container is wider than the rest of the pieces of the UI. Is that expected?

There are a couple outstanding issues w/ styling, especially at the narrower screen sizes. The strategy is too get the functionality done first then circle back to pick up those sort of issues

**Comment by rcanepa** [comment]
> > LGTM!
> > On a small viewport, the Providers container is wider than the rest of the pieces of the UI. Is that expected?
> 
> There are a couple outstanding issues w/ styling, especially at the narrower screen sizes. The strategy is too get the functionality done first then circle back to pick up those sort of issues

Agree! I would do the same. Just pointing them out in case you didn't see them 🙂

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/4348350

Thank you @cbauerman for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/4348350).

**Pull request merged**
