### PR TITLE
Reader: Turn on refreshed streams on wpcalypso

### PR DESCRIPTION
**Pull request by blowery**
No code changes, just turns on refresh streams on wpcalypso.

### CODE REVIEW

**Comment by fraying** [comment]
Woot! 👍

**Comment by lancewillett** [comment]
@blowery For historical reference could you point to (or upload here) before and after screenshots?

Here's what I'm seeing in Mac-n-Chrome, in wpcalypso 

(before)

screen shot 2016-10-28 at 13 57 31

(after)

screen shot 2016-10-28 at 13 56 57

**Comment by lancewillett** [comment]
Note: when I looked at https://wpcalypso.wordpress.com/read/a8c (internal updates) it looked broken. :/ (But could be because many P2 posts have no images.) Not posting screenshots here since it's private content.

**Comment by blowery** [comment]
read/a8c is working for me, find me on slack and show me what's busted?

We don't usually post before / after shots on feature flag flips. At least I've never seen it done.

**Comment by fraying** [comment]
Note: we have design work to do on the crosspost inserts. 

This whole thing is in process.

**Comment by lancewillett** [comment]
> We don't usually post before / after shots on feature flag flips.

Visual records are hugely important, especially for testers. "Here's what it should look like." "Here's what it was before."

**Pull request merged**
