### PR TITLE
Domains: Update illustration on G Suite offer

### PR DESCRIPTION
**Pull request by danhauk**
This PR updates the G Suite offer screen to use the new illustration style. There were also some concerns about possibly infringing on Google's trademark by using the colorful G logo (as stated in their [branding guidelines](https://docs.google.com/presentation/d/1woCMr2x9BnSOuDbfYtghC2VEJI7dHxsRLYq1v4p-DDY/edit#slide=id.g1e6d2a35db_0_63)).

screen shot 2017-06-26 at 11 33 12

This also fixes some weird spacing around the illustration at the breakpoint between `960px` and `1040px`.

Before | After
------------ | -------------
screen shot 2017-06-26 at 11 42 52 | screen shot 2017-06-26 at 12 14 53

#### Testing Instructions
1. Checkout `update/g-suite-illustration` or open a [live branch](https://calypso.live/?branch=update/g-suite-illustration)
2. Go to a site that has a custom domain but no email through G Suite
3. Click `Domains > Email` or visit `http://calypso.localhost:3000/domains/manage/email/:domain`
4. Assert the new illustration is shown as above.

### CODE REVIEW

**Comment by danhauk** [comment]
cc @drw158 who initially suggested updating the illustration to match the new style

**Comment by klimeryk** [comment]
I think you missed the other place:
screen shot 2017-06-28 at 15 31 47

That's the upsell we show when you try to add a domain to an existing site (Domains -> Add -> click on any suggestion).

**Comment by danhauk** [comment]
@klimeryk That upsell never had the illustration (see #14478). However, I don't really see why these necessarily need to be any different other than having an opt-out link on the add domain flow.

**Comment by klimeryk** [comment]
Ah, good point, didn't notice that they were different.. And, no, I don't know why they are different 😅

**Pull request merged**
