### PR TITLE
Update importer tests to run in single-runner

### PR DESCRIPTION
**Pull request by dmsnell**
See #3942

This patch removes the Makefile from the ithe importer test suite and
adds the tests into the single-test-runner white-list. No changes to the
tests themselves were needed.

**Testing**

From the project root run make test

cc: @blowery

### CODE REVIEW

**Comment by dmsnell** [comment]
@blowery or @aduth could one of your review my use of `nock` here? I don't think I will mess with other tests because I think `nock` only affects the next request instead of persisting but I'm not super fluent in it

**Comment by blowery** [comment]
Just need to move the nock setup down into a `before` block for the suite and clean it up in an `after` with  a `nock.cleanAll`

We should probably add a use style thing to handle the cleanup and provide a nock instance to hang requests off of.

**Comment by dmsnell** [comment]
> Just need to move the nock setup down

Hmmm…I don't think I have any setup. I'm just running a `nock` call from within the `it()` functions themselves.

I will add `nock.cleanAll()` though

**Comment by dmsnell** [comment]
thanks again @blowery - I updated by adding `nock.cleanAll()`, though I'm still a bit confused if that's actually doing anything. not sure exactly what a `use-nock` would give me here too unless it just made sure to clean things up in case some test failed in an unclean state. ready for a review again

**Comment by blowery** [comment]
i say :ship: 

the nock helper can be a different PR. :)

**Pull request merged**
