### PR TITLE
Signup: Cleanup processing screen.

### PR DESCRIPTION
**Pull request by shaunandrews**
After signup, we show a processing screen that currently looks like this:

screen shot 2016-04-15 at 3 18 13 pm

This PR cleans up the layout a bit; Aligning the list items, replacing the noticon with a Gridicon, using a card, and reducing the size of the illustration.

Here's the new screen in action:
processing demo

### CODE REVIEW

**Comment by folletto** [comment]
Nice touch! Well done, feels more cohesive in this way. I like the animation choice too, you're always top-notch on that. :)

A couple very very small things, mostly for consideration:

1. Maybe the text could be slightly smaller?
2. With the card layout, feels to me that we might even drop the title above.
3. Have you tried a pulsating dot (similar to the one we have on load at the top, or the one used in Tours) instead of the circling arrows?

**Comment by shaunandrews** [comment]
> Maybe the text could be slightly smaller?

Hmm, its really the only thing on the page (right now), so I think its fine as-is.

> With the card layout, feels to me that we might even drop the title above.

The card and title match the rest of the signup. I tried to make the screen feel part of the full flow.

> Have you tried a pulsating dot (similar to the one we have on load at the top, or the one used in Tours) instead of the circling arrows?

Made some updates to stop using the arrow gridicon:

processing demo

**Comment by folletto** [comment]
👍

**Comment by jblz** [comment]
Ran through a test & code looks good to me. Nice work!

**Pull request merged**
