### PR TITLE
State: Refactor extendAction to handle thunks recursively

### PR DESCRIPTION
**Pull request by aduth**
This pull request seeks to slightly refactor the `extendAction` state utility to recursively call itself when passed a thunk. This achieves two goals:

- Consolidates merging logic in case we choose to update it in the future
- Accounts for nested thunk action creators (yes, this is possible, but I'm unaware of any case which would justify their use)

Just happened to stumble across this in reviewing #10287 (cc @dmsnell)

__Implementation notes:__

I battled with the unit tests. I'd hoped not to have pulled in Redux, but struggled to wrap my head around testing it otherwise. Suggestions welcome.

__Testing instructions:__

Verify tests pass:

```
npm run test-client client/state/test/utils.js
```

### CODE REVIEW

**Comment by dmsnell** [comment]
This is a good update @aduth.

Could testing not simply be done with spies for dispatch?

```js
const dispatch = spy();
const action = { type: 'BURN_CPU' };
const extendo = { duration: 1337 };
const expected = merge( {}, action, extendo );

dispatch( extendAction( action, extendo ) );
expect( dispatch ).to.have.been.calledWith( expected );

const thunk = dispatch => dispatch( action );
const thunkstended = extendAction( thunk, extendo );
thunkstended( dispatch )
expect( dispatch ).to.have.been.calledWith( expected );
```

**Comment by aduth** [comment]
@dmsnell If I understand correctly, this is how the [test for the basic thunk](https://github.com/Automattic/wp-calypso/blob/1cdd7380bb457dd4653fad1f27a6a53065d64c24/client/state/test/utils.js#L64-L88) is written, but I'm having a hard time formulating how this would look for a nested thunk, e.g.:

```js
const nestedThunk = ( dispatch ) => dispatch( ( nestedDispatch ) => nestedDispatch( action ) );
```

**Comment by dmsnell** [comment]
I may be missing something here, but the nested thunk somewhat libearizes on dispatch, so the output of the first dispatch is just another think. With a dispatch spy returning identity, I think we could just run the output through dispatch a second time and it's output should be the original action.

**Comment by dmsnell** [comment]
@aduth is there anything you need from me on this?

**Comment by aduth** [comment]
@dmsnell If you're happy, I'm happy. I can get this shipped today.

**Pull request merged**
