### PR TITLE
Update the wpcom-proxy-request package to v5.0.0

### PR DESCRIPTION
**Pull request by jsnajdr**
It will start loading the `v=2.0` version of the rest proxy that's a much smaller download. Check out D9537 to see the server-side changes.

### CODE REVIEW

**Comment by dmsnell** [comment]
Let's make sure we don't merge this until we have had some pretty hefty testing! Thanks for removing jQuery though @jsnajdr !

**Comment by alisterscott** [comment]
I'll run the full set of e2e tests against this and report back

**Comment by alisterscott** [comment]
All the e2e tests passed against this PR ✅

**Comment by lamosty** [comment]
Make sure to rebuild Calypso if you switch to this branch.

**Comment by lamosty** [comment]
I've found out some issues with some requests. Noted them in the patch. Btw, how is it possible the e2e tests pass while requests fail? @alisterscott are you sure the e2e tests use the new rest proxy? I had to rebuild calypso for it to work. You can check that in Network tab: http://cld.wthms.co/ZZGfaa

**Comment by jsnajdr** [comment]
> are you sure the e2e tests use the new rest proxy?

That's a good point: the e2e tests are using the old proxy, the only difference that there is a `?v=2.0` query param in the proxy URL and it's ignored. We should re-run the tests once the wpcom patch is deployed and `v=2.0` will start returning the new proxy version.

**Comment by jsnajdr** [comment]
I rebased this PR and resolved the conflicts in `npm-shrinkwrap.json`.

The v2.0 REST Proxy was deployed on `wpcom`, so it now makes sense to run the full e2e test suite again, this time against the real 2.0 version of the proxy. @alisterscott, could you please run them?

@lamosty Please test again and approve if you can. We're pretty close to landing this work 🥇

**Comment by jsnajdr** [comment]
I did a little more testing now, including logged-out state and signup and things look good. Going to merge.

**Pull request merged**
