### PR TITLE
Stats: release traffic page and highlights module settings

### LINKED ISSUE #77863: Stats: remove feature flag and deal with compatibility
We not only need to remove the feature flags but also need to test the version of `stats-admin` or Jetpack to determine whether the settings are supported for Odyssey.

Versions could be found at:

https://github.com/Automattic/jetpack/blob/3c59762c353f78aafb3d26ba13e62b8e3c05d9fa/projects/packages/stats-admin/src/class-odyssey-config-data.php#L92

### PR DESCRIPTION
**Pull request by kangzj**
Related to #77863 

## Proposed Changes

The PR proposes to 
- Remove feature flags for traffic page and highlights module settings.
- Test Stats Admin package version - if version < 0.9.0-alpha, disable both settings.

## Testing Instructions

Please test for both Calypso and also Odyssey

**Calypso**

- Open Calypso live
- Ensure tooltips for settings are shown properly
- Ensure tooltips are not shown again after dismissed
- Ensure module settings stick and is respected
- Ensure Highlights settings stick and is respected

**Odyssey**

- Build the branch for Odyssey `STATS_PACKAGE_PATH=~/path/to/jetpack/projects/packages/stats-admin yarn dev`
- Build Jetpack if necessary `jetpack build plugins/jetpack`
- Open `/wp-admin/admin.php?page=stats`
- Ensure tooltips for settings are shown properly
- Ensure tooltips are not shown again after dismissed
- Ensure module settings stick and is respected
- Ensure Highlights settings stick and is respected

**Old Odyssey**

- Change version of `stats-admin` to < `0.9.0-alpha` [here](https://github.com/Automattic/jetpack/blob/3c05799e6811f48b1352a1cd38a669272e4a92cf/projects/packages/stats-admin/src/class-main.php#L25) - for example `0.8.2` or just test with an old Jetpack installation
- Ensure neither settings or tooltips is shown
- Ensure all pages work okay
## Pre-merge Checklist

- [x] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [x] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [x] Have you checked for TypeScript, React or other console errors?
- [x] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

**Review by keoshi — COMMENTED** [review]
This is looking great, friends! Thanks for all your work so for on getting all of the pieces together.

Spotted some things I'd love to see improved, and was pretty extensive with the list below, so please ignore them for now if we need to merge soon.

### Accessibility

- [ ] **There's no focus highlight/style on the global settings icon**


https://github.com/Automattic/wp-calypso/assets/390760/484d6bcb-8709-4cd5-952c-50323016afbf

- [ ] **There's no focus highlight/style on the dual choice popover**

image

- [ ] **There's no keyboard navigation continuity between the popover triggers and the popover options**

https://github.com/Automattic/wp-calypso/assets/390760/c873b87a-eebd-4365-8da9-6d4a509391b8

### Usability

- [x] **Opening a popover should dismiss the other one immediately**

https://github.com/Automattic/wp-calypso/assets/390760/f9f17746-11c9-49a3-94cf-101aaa95e09e


- [x] **Clicking outside the popovers should dismiss them**

https://github.com/Automattic/wp-calypso/assets/390760/764a716a-ed99-43c0-9cfa-aeac46522ccf

### Style

- [x] **On mobile, it would be nice to keep the global settings icon on the right side**

image

**Review by jsnmoon — APPROVED** [review]
Everything works as expected on Calypso, Odyssey, and legacy Odyssey. All code related to these features appears sound. Like @keoshi, I will also defer to your judgments on which design corrections are necessary before launching.

Great work, @kangzj and @dognose24.

**Comment by dognose24** [comment]
Hey @keoshi, thanks for the design feedback. I have updated those `Usability` and `Style` issues you commented on with marking checked, which are ready to review! About those remaining accessibility issues, let's iterate them after the release. 🙂

> There's no focus highlight/style on the dual choice popover

I confirm there is `focus` styling on the highlight panel launch button. Could you take a look at it by clicking on the button?

https://github.com/Automattic/wp-calypso/assets/6869813/bfb23d97-bbac-484f-9c9c-f7036ca3f1b5

**Comment by keoshi** [comment]
> I confirm there is focus styling on the highlight panel launch button. Could you take a look at it by clicking on the button?

@dognose24 Sorry for being unclear, I meant the buttons inside the popover.

**Review by keoshi — APPROVED** [review]
Excellent stuff, @dognose24 & @kangzj ! And thanks for always being accommodating of requested changes.

Thank you!

**Comment by dognose24** [comment]
> I meant the buttons inside the popover.

Yes, the options are not given focus styling for now. Do you mean the background color changes with the `primary` color of the theme schemes?

截圖 2023-06-15 上午12 32 03

**Comment by dognose24** [comment]
> I meant the buttons inside the popover.

@keoshi Yes, the options are not given focus styling for now. Do you mean the background color changes with the `primary` color of the theme schemes?

截圖 2023-06-15 上午12 32 03

**Comment by keoshi** [comment]
@dognose24 Yes, those options! Style-wise, I think we should follow Dotcom's styling here, and do a border or inner box-shadow instead of a full background to achieve the same effect as other focused elements; few examples below:

image

image

image

So pretty much the same as we have right now in the ellipsis icon above:

image

**Comment by kangzj** [comment]
I'm going ahead to merge this and we'll tackle the other issues in followup PRs.

**Comment by worldomonation** [comment]
Hi, this PR was reverted in https://github.com/Automattic/wp-calypso/pull/78252 because it caused E2E tests to fail at a very high rate. See https://github.com/Automattic/wp-calypso/issues/78255 and conversation at p1686824034437589-slack-C02DQP0FP and p1686831294859149-slack-C1A1EKDGQ. Thanks!

**Pull request merged**
