### PR TITLE
Sharing Settings: Add Information for Likes & Comment Likes

### LINKED ISSUE #32217: Sharing Settings: Clarify Like button activation settings
Screen_Shot_2019-03-20_at_7 09 12_PM

Problem: There are two adjacent settings where Likes can be enabled (one for Posts/Pages, one for Comments).

What should be seen here: 
—A clearer instruction and/or prompt as to what those two settings mean because they sound similar. 
—As an WP expert I can imagine why that's the way they are — but I imagine there's a better way.

### PR DESCRIPTION
**Pull request by torres126**
#### Changes proposed in this Pull Request

* Uses this SupportInfo component to clarify the differences between Likes and Comment Likes, and links to the support articles on them. 

Screenshot_2019-04-22_at_12 56 21
Screenshot_2019-04-22_at_12 57 59
Screenshot_2019-04-22_at_12 57 52

Is this design and copy ideal? I've based the copy on the ones in the support articles, but there's probably a better copy. cc @michelleweber 

cc @sixhours 

Resolves #32217

### CODE REVIEW

**Comment by torres126** [comment]
Conflicts resolved (which also fixed the second test failure!) :)

**Comment by donpark** [comment]
Good. Still needs OKs from Copy and Design folks.

**Comment by michelleweber** [comment]
I think we can get even a little clearer by specifying exactly who is using each option: 

Comment likes: Encourage community by giving readers the ability to show appreciation for one another's comments. (Or just "Give readers the ability to show appreciation for one another's comments.")

Likes: Give your readers the ability to show appreciation for your posts

**Comment by torres126** [comment]
Thank you @michelleweber! Copy updated. :)

**Comment by sixhours** [comment]
Thanks so much for pulling this together! Apologies that I'm just now getting around to reviewing it. 😅 

The only feedback I have is that the info icons feel a bit like they're floating in space and not connected to the items they're meant to define. I would move them closer to the checkbox labels so they're more clearly associated.

**Comment by donpark** [comment]
> The only feedback I have is that the info icons feel a bit like they're floating in space and not connected to the items they're meant to define. I would move them closer to the checkbox labels so they're more clearly associated.

I felt the same so I tinkered with the layout but there wasn't much that could be done. Visual shortcomings stem from how Calypso's SupportInfo component is implemented. How about merging this PR as is and creating a separate issue to fix SupportInfo ?

**Pull request merged**
