### PR TITLE
PostSchedule: improve Timezone settings

### LINKED ISSUE #10522: Post Schedule: Add more info to clarify timezone setting
We’ve had feedback saying the timezone info is confusing specially when it comes to schedule a post #7253, and this keeps coming up. I suppose this is largely because many users have never changed their site timezone setting and have left it default, UTC+0.

Let’s say, if I’m in Madrid (UTC+1), and I’m one of those new users who isn’t aware of the setting, I’ll see this:

screen shot 2017-01-10 at 13 25 40

The info currently focuses on the delta which is helpful, and it’s clean and minimal. However, I wonder if we can afford to be a more verbose to clarify and make users aware of the setting at the same time. Also, we could clarify which timezone will be used for scheduling/publishing. This is another feedback we’ve had from our users.

I’ll leave the exact copy with someone else, but I was wondering if something like this would be helpful.

screen shot 2017-01-10 at 14 15 33

We could add more info and a nudge into the popover rather than the current value of your site timezone.

screen shot 2017-01-10 at 14 19 34

cc @rralian @meremagee

### PR DESCRIPTION
**Pull request by retrofox**
The main purpose of this patch is fix #10522, which improve the timezone piece of the PostSchedule component. Also, this fixes some ESlint warning and tidies the code in general.

### Testing

1) Be sure the site has a different timezone that your computer. The timezone can be edited from General Settings: http://calypso.localhost:3000/settings/general/<site-id>

2) Start to create/edit a post: http://calypso.localhost:3000/post/<site-id>
3) Play changing the post date through of the PostSchedule component.

4) Take a look to the timezone area opening the (i) popover as well.

5) You could go straight to the General Settings page from there.

Depending on the timezone the information there will change. For instance, if you set a UTC zone, you should see something like the following:

### CODE REVIEW

**Comment by retrofox** [comment]
cc @iamtakashi @folletto

**Comment by retrofox** [comment]
I've added this suggestion. It adds the user offset so in this ways it's easier (IMO) understand what means those values:



Difference: -5h
Your local offset: -03:00
Site timezone: Los Angeles / -08:00

**Comment by folletto** [comment]
I wouldn't add it, but I understand the idea. If you want that in however, add in the "(i)" box and not under the message, which is meant to be as short and linear as possible. If you show two numbers, it makes it harder to understand.

**Comment by iamtakashi** [comment]
I'm actually confused by seeing the numbers....

I agree with @folletto, the number for "Your local offset" seems to add a complexity, and it doesn't seem to be necessary.  

Regarding the number in (i), I guess I wasn't fully understanding @folletto's idea in #10522, but I had the impression of the number being the time difference between the site timezone and your local timezone, which in this case `-5:00`. I have a feeling that it becomes even more confusing if the number changes depending on the scheduled time.... The default value is `UTC +00:00` which already has numbers, and adding the difference on top of that might be even confusing. ex. `UTC +00:00 -8:00`. In my opinion, it's less confusing if we keep it just the value of the setting.

**Comment by retrofox** [comment]
The commit with my suggestion https://github.com/Automattic/wp-calypso/pull/10558#issuecomment-272967954  was removed.

**Comment by folletto** [comment]
> Regarding the number in (i), I guess I wasn't fully understanding @folletto's idea in #10522, but I had the impression of the number being the time difference between the site timezone and your local timezone, which in this case -5:00. I have a feeling that it becomes even more confusing if the number changes depending on the scheduled time.... The default value is UTC +00:00 which already has numbers, and adding the difference on top of that might be even confusing. ex. UTC +00:00 -8:00. In my opinion, it's less confusing if we keep it just the value of the setting.

My suggestion was to make explicit the entire timezone definition (as this PR does): name and number, instead of just name. No additional complexity. :) 

The reason is that the name alone is very hard to grok. If I tell you:

* Europe/Lisbon
* Europe/Rome
* Europe/Paris
* Europe/Helsinki

without any number indication, even as an European, it's not intuitive to know which one of these cities is +00, +01 or +02. :)

So yes, I think the current solution is good:

screen shot 2017-01-18 at 11 41 35

screen shot 2017-01-18 at 11 41 27

**Comment by iamtakashi** [comment]
I've tested in calypso.live and I can see the number in (i) and the message are always the same regardless of the scheduled time. That's how I initially understood @folleto's idea, and I'm ok with it as I understand the benefit.

One last thing I've spotted, we probably should add `+` in the message if the site timezone is ahead of your local timezone. Like... 

"This site timezone is +9h from your local timezone."

**Comment by retrofox** [comment]
> we probably should add + in the message if the site timezone is ahead of your local timezone. Like...

> "This site timezone is +9h from your local timezone."







It's added in this commit: cbddf9868855c7013dfcbcb9ab6d47793a5ff35f. I'll rebase if we agree, if not let's get rid of this.

**Comment by folletto** [comment]
Let's ship. :shipit:

**Comment by iamtakashi** [comment]
👍 I can see the `+` now. Let's ship it!

**Comment by retrofox** [comment]
Thanks folks for the review.

**Comment by KristinaKay** [comment]
User says "I'm having problems publishing articles. Is the server down? Everytime I publish a post it says Oops cant be found?"

The URL on the post was showing us this: 
https://theplayfulparent.org/2019/11/20/thanksgiving-dining-entertaining-guide-2

But user is in NY and it’s the 20th. Their time zone is set for NY but the URL is using UTC time.

The problem is that in NY,  the 21st hasn’t happened yet so the URL does not work because the post does not exist.

What I did:

When I changed this date to November 20 and set the time to 12:23 PM on the post, it worked.

New URL:
https://theplayfulparent.org/2019/11/20/thanksgiving-dining-entertaining-guide/

#16803974-hc

**Pull request merged**
