### PR TITLE
Add detection of Gutenberg paragraphs and try to work around

### PR DESCRIPTION
**Pull request by mkaz**
Adds a new utility function, hasGutenPs which detects if the content
contains Gutenberg Paragraph block. This function is then used to no run
the wpautop and removep functions that modify the content in away that
breaks Gutenberg blocks.

### CODE REVIEW

**Comment by mkaz** [comment]
See current changes - they almost fix the issue, however when their are multiple paragraphs (or spaces between Gutenberg tags) additional `<p> </p>` are inserted between the comments causing issues.

This can be tested with a Jetpack site that has Gutenberg loaded, create new post with paragraphs tags in Gutenberg. Load post in Calypso and edit, if you switch between Visual and HTML modes you can see the behavior of `<p>` tags being added/removed.

For issue #21973

**Comment by aduth** [comment]
Related: https://github.com/WordPress/gutenberg/pull/4874 (trying to be more durable to these modifications from the block implementation itself)

**Comment by mkaz** [comment]
@aduth tested out a build of Gutenberg your PR#4874 and it kinda works. Calypso still strips out the paragraph tags on save. So viewing the post after Calypso edited, there are no paragraphs. 

Your fix does work when the post is then edited in Gutenberg, the paragraph tags get re-added.

**Comment by aduth** [comment]
>@aduth tested out a build of Gutenberg your PR#4874 and it kinda works. Calypso still strips out the paragraph tags on save. So viewing the post after Calypso edited, there are no paragraphs.

Yeah, I can see how this is still problematic, since because the comment demarcations remain, `wpautop` will be skipped for the post.

https://github.com/WordPress/gutenberg/blob/98d6c7e/lib/compat.php#L159-L174

I'm not sure what more there can be done here, since it's really the fault of the external editor mangling the content. What we've added in https://github.com/WordPress/gutenberg/pull/4874 allows Gutenberg to repair the paragraph when editing the post later in Gutenberg, but until then, as you've noted, the front-end rendering of the block will be broken.

Of course, this is only an issue so long as users are switching back and forth between Gutenberg and a `removep` editor, which ideally does not occur into the long-term.

**Comment by alisterscott** [comment]
This PR needs a rebase - is this PR still required?

**Comment by alisterscott** [comment]
Closing due to inactivity - please reopen if necessary

**Pull request closed without merging**
