### PR TITLE
Assembler Flow: Prepare the Celebration step

### PR DESCRIPTION
**Pull request by arthur791004**
Related to https://github.com/Automattic/wp-calypso/issues/80672

## Proposed Changes

* Introduce the `SitePreview` component so we're able to re-use it between the launchpad and celebration step
* Introduce the `useCelebrationData` hook to handle the data across different flows
* Use the `submit` function when navigating to the destination in the Celebration step so the `calypso_signup_actions_submit_step` will be fired
* ~Navigate to the Celebration step after you finish the last screen of the Assembler step~ We will do it in the follow-up PR. See p1693463978245139/1693271935.462679-slack-CRWCHQGUB

**Demo**

https://github.com/Automattic/wp-calypso/assets/13596067/eb30c8ad-6b44-4a64-b481-43d277188ff2

**Screenshots**

| - | Assembler Flow | Start Writing Flow | Design First Flow | Launchpad |
| - | - | - | - | - |
| Desktop | image | image | image | image |
| Mobile | image | image | image | image |

## Testing Instructions

**Assembler Flow**

* Go to Theme Showcase
* Scroll down to select the Assembler CTA
* Finish the Assembler flow
* Ensure you see the Celebration step
* Ensure each button works as expected

**Start Writing Flow**

* Head to `/setup/start-writing/celebration-step?siteSlug=<your_site>`
* Ensure it works as expected

**Design First Flow**

* Head to `/setup/design-first/celebration-step?siteSlug=<your_site>`
* Ensure it works as expected

**Launchpad**

* Head to `/setup/<flow>/launchpad?siteSlug=<your_site>`. For example,
  * /setup/site-setup/launchpad?siteSlug=<your_site>
  * /setup/start-writing/launchpad?siteSlug=<your_site>
  * /setup/design-first/launchpad?siteSlug=<your_site>
* Ensure it works as expected

## Pre-merge Checklist

- [x] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [x] https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md for your changes?
- [x] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [x] Have you checked for TypeScript, React or other console errors?
- [x] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [x] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [x] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

**Comment by arthur791004** [comment]
@lucasmendes-design I made the Celebration step below after the Activation screen of the Assembler since we have to apply the selected patterns and styles first. We can iterate to deprecate the previous Activation screen and add the new Activation step in the future if needed.

Hence the current flow is
1. Theme Showcase
2. The Assembler fow
  1. The `Design your own` screen
  2. The `Pick your styles` screen
  3. The `Upsell` screen if needed
  4. The `Activation` screen
  5. The `Celebration` step introduced from this PR

Also, when people see the Celebration step, their site is ready. So I don't enable the back button on this step. But people can still use the browser back button to go to the previous page.

Do you think it makes sense?

| The Activation screen | The Celebration step |
| - | - |
|  |  |

Note that the screenshots are from different sites

**Comment by miksansegundo** [comment]
The acceptance criteria in the issue https://github.com/Automattic/wp-calypso/issues/80672 says that this screen appears after the checkout for users who have upgraded their site plan to get custom styles. Can you confirm this?

This PR shows it for existing sites (Theme Showcase CTA) that complete the flow when they upgrade the plan and without upgrade too.

Here are the flows for reference:

image

**Comment by arthur791004** [comment]
> The acceptance criteria in the issue https://github.com/Automattic/wp-calypso/issues/80672 says that this screen appears after the checkout for users who have upgraded their site plan to get custom styles. Can you confirm this?

Yes, I asked https://github.com/Automattic/wp-calypso/pull/81203#issuecomment-1698775817. I thought this was for the people who go through the activation screen of the Assembler flow. But after re-reading https://github.com/Automattic/wp-calypso/issues/80679#issuecomment-1692133623, I think I'm wrong. We have to show this no matter whether the site is newly created or not. However, we don't have the activation step below, so for now I think we still need to display the “Great job” or “Activation” screen of the Assembler after checkout, and then navigate to this celebration step. 

image

cc @lucasmendes-design

**Comment by miksansegundo** [comment]
I forgot to say that the celebration screen is looking great 🙂 and I think users will appreciate it. I wasn't expecting it after the activation.

> We can iterate to deprecate the previous Activation screen and add the new Activation step in the future if needed.

I got it. In this PR, I'm missing the new Activation screen.

Screenshot 2566-08-30 at 20 03 24

This new screen says `Ready to activate your theme` because the assembler activates Creatio theme. Only for existing sites, the button `Activate this theme` shows a modal to confirm the Homepage replacement.

Screenshot 2566-08-30 at 20 15 37

I liked the idea of showing the Activation screen with confetti directly after the checkout so users can celebrate it before the processing screen (which takes 7~18 seconds). See video demo:

https://github.com/Automattic/wp-calypso/assets/98343583/fbab47b0-5770-4eed-8bee-00a4570bda1a

Here is a different proposal for the flows including the Celebration screen and new Activation screen. WDYT? cc: @lucasmendes-design @Automattic/lego  

[](https://mermaid.live/edit#pako:eNqFU8Fu2zAM_RVWlzlAm0OPPqwYmqLbYUXQtIcCvmgSk6i1pUKk2xlx_r2yZCdOkKC-iKT4Hh9paiOU0yhysSzdp1pLz_A0KyyEby6Z0VvKBmMCV1c_YcFNiZSlY5JSkxOvZ6gMGWdTaPNbEqwkowaKgZttQhymdcj2wbW78N1_Q2zsamEYDwHjmx3s1tml8ZXkkJDde5QMr-7fRa9ufBs1zr1TSBRY4KyaF6QWnt8JyzJLR8-WnMjTdjiNUIYG_Wnxmz8E2PtAITAMYERzu0b15mrOBmPQ3bup1lw2FVoGqlUnvoVfis1Hanlv9tBRh7GCsysvuS5jDmVHPpDyiDaHF1d7ijJ_EIQx6maY4dnxxzmdlAKLnvWxIwJ2INMdQhPqAK-xwp5-hBov0bja9dlRnsze7cZ-FNnenE6nk-_AR539dVqW4_ZiIB8yMPRj6ExTMfVo9Xa7efAn4gsLEu60YefFpagwbK7R4YVuOkQhYoVC5MHU0r8VorDbkCdrdovGKpGzr_FS1O86iJoZGegrkS9lSbj9AoEmX8s)

**Comment by arthur791004** [comment]
> Here is a different proposal for the flows including the Celebration screen and new Activation screen. 

The problem with the new activation screen is that the screen might not be under the Stepper Framework (paYJgx-3TE-p2). So, we have to think about how to re-use the screen in the Assembler flow as we discussed.

**Comment by lucasmendes-design** [comment]
> I liked the idea of showing the Activation screen with confetti directly after the checkout so users can celebrate it before the processing screen (which takes 7~18 seconds). 

> WDYT?

It makes sense to me 👍🏼

---- 

Btw, not related to this issue but if you all have some ideas of how to approach the atomic transfer, I would appreciate it :) Currently, this transfer could take 20-30 seconds to minutes ( paYJgx-3TE-p2#comment-4095 ). The current loader inside the button will not work in this case. I put some ideas here ( paYJgx-3TE-p2#comment-4085 )

**Review by miksansegundo — APPROVED** [review]
👍 Tested:

- ✅ All Assembler flows no longer redirect to the Celebration screen:
  - New site
  - Existing site
  - With/out checkout 
- ✅ Blog and Design first flows show the screen with confetti, looks good on desktop and mobile and all buttons work as expected
- ✅ LaunchPad screen works as expected
  - Note that the URL `/setup/site-setup/launchpad` doesn't exist but I think that's fine because the correct one is `/setup/build/launchpad` and works as expected

**Comment by taipeicoder** [comment]
@lucasmendes-design please refer to p1693271935462679-slack-CRWCHQGUB for more discussion on the Assembler navigation flow. We decided to remove code related to the Assembler flow in this PR until we have a more concrete path forward.

**Comment by taipeicoder** [comment]
@arthur791004 I started a new site in the `site-setup` flow. I skipped the onboarding by clicking the Skip for now in the Goals screen. When I landed in the Launchpad, I was redirected to `https://${site_slug}/?iframe=true&theme_preview=true&hide_banners=true&preview=true&do_preview_no_interactions=false` which I believe happens when the iframe encounters an error. I couldn't reproduce it in production.

Is this something reproducible on your end?

**Comment by arthur791004** [comment]
> https://${site_slug}/?iframe=true&theme_preview=true&hide_banners=true&preview=true&do_preview_no_interactions=false

The redirection is due to the timeout of getting the preview. When the network is unstable or the preview takes a long time to load, the page will be redirected to the iframe... I guess we might need to disable this behavior (provide a refresh button instead) or increase the timeout

**Comment by taipeicoder** [comment]
> > https://${site_slug}/?iframe=true&theme_preview=true&hide_banners=true&preview=true&do_preview_no_interactions=false
> 
> The redirection is due to the timeout of getting the preview. When the network is unstable or the preview takes a long time to load, the page will be redirected to the iframe... I guess we might need to disable this behavior (provide a refresh button instead) or increase the timeout

That could be it! But I think it's a bit strange that I can't reproduce it on production (and wpcalypso), while in both environments the API is proxied 🤔 I've attached a recording for reference:

https://github.com/Automattic/wp-calypso/assets/797888/b6c8a9ca-d0de-4ac9-bbdc-e75650c9a8ca

**Review by taipeicoder — APPROVED** [review]
In any case, I don't think the issue is directly related to this PR. After some time, the problem is gone, so I assume that it's related to site creation.

I'm attaching the logging for both scenarios for posteriority:

| With redirect issue | Without redirect issue |
| --- | --- |
| Screenshot 2023-08-31 at 6 12 08 PM| Screenshot 2023-08-31 at 6 12 37 PM|

The message `preview loading timeout` is indeed what's causing the redirect.

**Pull request merged**
