### PR TITLE
Activity log: update banners

### PR DESCRIPTION
**Pull request by keoshi**
#### Changes proposed in this Pull Request

* Remove credentials banner
* Remove backup status banner
* Update upgrade banner
* Update intro banner
* Update intro banner associated styles

#### Testing instructions

* Fire up this PR
* Create a new site, select the free Jetpack plan, and ensure you only see one intro banner on the AL. When dismissed, you should see the permanent upgrade nudge.
* Create a new site, select any paid plan with Backup, and ensure you only see one intro banner on the AL. When dismissed, you should see no banners.

Fixes https://github.com/Automattic/wp-calypso/issues/45735
See p6TEKc-3U2-p2

#### Screenshots

Before, free plan:
image

After, free plan:
image

Before, paid plan (missing the credentials and backup status banner):
image

After, paid plan:
image

### CODE REVIEW

**Comment by jeffgolenski** [comment]
@keoshi I'm seeing a bunch of circleci fails. I reran things on Friday afternoon, but they're still failing. I'll have to revisit on Monday!

**Comment by keoshi** [comment]
Thanks for highlighting that @jeffgolenski ! Seems like those tests are all failing on unrelated files, but I've pushed some improvement regardless.

Hopefully @Automattic/jetpack-voyager can help us with those fails and/or let us know how to proceed.

**Comment by rcanepa** [comment]
@keoshi, I'm taking a look at this.

**Comment by rcanepa** [comment]
@keoshi, almost all tests passed and the ones that failed don't seem to be related to your changes (they related to Themes). Also, those same failed tests passed on the `ci/wp-e2e-tests-full-desktop` test suite. I would say you're good to go now.

**Comment by keoshi** [comment]
Thanks a bunch for jumping in and helping out, @rcanepa — really appreciate it!

**Comment by jeffgolenski** [comment]
Marvelous work, @keoshi 

The only issue I could see (for both banners), is the illustration sizing at weird breakpoints. I'm wondering if we should just hide it completely below "tablet" size. What do you think?

Screen Shot 2020-09-21 at 10 26 43 AM
Screen Shot 2020-09-21 at 10 26 32 AM
Screen Shot 2020-09-21 at 10 26 17 AM
Screen Shot 2020-09-21 at 10 26 08 AM

**Comment by keoshi** [comment]
> I'm wondering if we should just hide it completely below "tablet" size.

Sounds perfect to me!

**Review by jeffgolenski — APPROVED** [review]
yaaaaaaaaaaaa

**Comment by monsieur-z** [comment]
I'm going through the open PRs that require our attention. Do you need a review from Voyager before merging?

**Comment by keoshi** [comment]
Yes please, @monsieur-z ! Thank you.

**Comment by monsieur-z** [comment]
I just updated the upgrade links to the Jetpack Security selection screen. Other than that, looking good!

**Review by monsieur-z — APPROVED** [review]

**Comment by keoshi** [comment]
Thanks so much, @monsieur-z ! Is it safe to merge with both e2e tests failing above?

**Comment by keoshi** [comment]
Test fails seem unrelated to the changes on this PR — moving ahead with the merge.

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/4625577

Thank you @keoshi for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/4625577).

**Pull request merged**
