### PR TITLE
Domains: Show transfer error description for failed domain transfers

### PR DESCRIPTION
**Pull request by leonardost**
## Proposed Changes

This PR shows an improved error description for failed domain transfers. Before this PR, only a generic message asking the user to try again was shown, but no details were shared.

Depends on D116663-code

### Screenshots

- Before
> Screenshot 2023-07-21 at 00 25 45

---

> Screenshot 2023-07-21 at 00 30 05

- After

> Screenshot 2023-07-21 at 12 37 33

---

> Screenshot 2023-07-27 at 17 20 14
 
## Testing Instructions

Please follow the same testing instructions of D116663-code, as they're a tad complex.

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [x] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

**Review by gius80 — APPROVED** [review]
LGMT! Thanks for the update!

**Review by candy02058912 — APPROVED** [review]
Thank you for the thorough instructions in the diff, tested and LGTM
domains

**Comment by ramynasr** [comment]
I tested this, and it works as expected. I noticed that after clicking on the "see the details or retry" link from `domains/manage`, I have this screen with the same link at the top linking to the same page I am viewing, which can be a little confusing.

image

Also, in the screen above, the `restart the transfer` link does the same as the `Restart transfer` button. The `Restart transfer` button was disabled but clickable (I also saw that elsewhere; I think it's not specific to this PR?)

Once I click on `Restart transfer`, I go to the following screen:

image

It says the domain is not transferable, but I see no information here related to why that's the case (probably that's not related to this PR, either?

**Comment by leonardost** [comment]
Thanks for the review @ramynasr!

> I noticed that after clicking on the "see the details or retry" link from domains/manage, I have this screen with the same link at the top linking to the same page I am viewing, which can be a little confusing.

I agree 😕 that's because it's the same component in both places. I think we can iterate on that later

> the restart the transfer link does the same as the Restart transfer button

That's a good point, I've removed the link in the text as it's redundant

> The Restart transfer button was disabled but clickable

I don't think that's related to this PR, I've seen it somewhere else too 🤔 it's due to the transfer subscription purchase not being loaded yet - we usually have a lot of subscriptions in our sites, so that can take a while to load

> It says the domain is not transferable, but I see no information here related to why that's the case

Yeah, we should iterate on that too in a later diff/PR

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/8631157

Thank you @leonardost for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/8631157).

**Pull request merged**
