### PR TITLE
Vdimitrakis/try/download stats report

### PR DESCRIPTION
**Pull request by therocket-gr**
Relates to
- 2644-gh-tumblr/a8c-dsp
- D167420-code

## Proposed Changes
The PR adds a download data button in the campaign item details page (for blaze advertising)

Screenshot 2024-11-21 at 1 04 03 PM

When clicked a loading text will appear with text generating report (adding this for translators use)

Screenshot 2024-11-21 at 1 04 06 PM

internally we call 3 DSP endpoints 

1. Creating a report (`POST /stats/:campaignId/report`) which returns `report_id`;
2. Getting a report status (`GET /stats/:campaignId/report/:reportId/status`), since all the reports are generated using a BullMQ, so we have to know the status of their readiness before being able to download;
3. Getting the actual report (`GET /stats/:campaignId/report/:reportId`), its result has `text/csv` as a Content Type

Nope, we can't just provide a URL of a report to a customer because we use WPCOM proxy, so the request to fetching the report should contain blog- and user-related data.

So, to achieve providing a user with a report we:
- Start report generation by launching its creation,
- Wait until the report is ready by periodically asking for status,
- Fetching the report as text,
- Creating a URL Object to let user download it as a file.

## Testing Instructions
1. Sandbox WPCOM;
2. Apply the diff D167420-code;
3. Run DSP API locally;
4. Run DSP Client locally with `:wpcom: postfix;
5. Adjust Calypso to use the local widget;
6. Make sure you have a campaign with some stats;

If you don't have one, please use this [PR](https://github.tumblr.net/Tumblr/a8c-dsp/pull/2868) from James as an example. In short, you need to:
- have a campaign locally, 
- change its ID to `110111` and start/end dates to be `2024-11-24` and `2024-11-27` respectively,
- run SQL queries from James' PR,
- you can also test that you have data by opening a [link](http://localhost:3003/api/v1.1/stats/110111?start_date=2024-11-24&end_date=2024-11-27&tz=Europe/London&resolution=day) (it should show data for 4 days);

7. Run Calypso locally which is connected to local DSP widget and DSP API is proxied with your WPCOM sandbox;
8. Open the Campaign details in Calypso for "your" campaign `110111`;
9. Click on the "Download" button;
10. Make sure that the title was changed to "Generating a report";
11. Next, your browser should show file downloading;
12. The file is accessible and has correct data.

Demo walk through

https://github.com/user-attachments/assets/1aaaae11-acc1-4fc2-8617-e123a24429c0

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Comment by jjolmo** [comment]
I managed to download a file, although it doesn't contain any data, but probably it is something specific at my mockup campaign. The file seems correct based on the information coming from the endpoint

image


I also tested the error by mocking an error response
image


LGTM

**Review by jjolmo — APPROVED** [review]
LGTM

**Comment by j6ll** [comment]
The functionality works great for me on the whole:

Screenshot 2024-12-02 at 11 40 53

One strange thing I noticed is that "unknown" is always zero in my report. Is there a way we could skip these?

Screenshot 2024-12-02 at 11 43 51


Another thing I'd like to see (in a future iteration) is perhaps better handling of "unknown", I think this could cause confusion amongst users - maybe a rewording of "Not available" would be clearer.

Screenshot 2024-12-02 at 11 40 59

**Comment by j6ll** [comment]
Realise the changes Im suggesting need to be done in the API though, not here. So lets ship this and iterate :shipit:

**Review by j6ll — APPROVED** [review]

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/17041464).

**Pull request merged**
