### PR TITLE
Jetpack Cloud: move the log out functionality to the master bar

### PR DESCRIPTION
**Pull request by rcanepa**
#### Changes proposed in this Pull Request

* Move the log out functionality to the master bar. 

#### Questions

* Is "Log out of Jetpack Cloud" the right title for the avatar?

#### Testing instructions

* Run this PR
* Go to `http://jetpack.cloud.localhost:3000/`
* Select any site
* Click on the avatar on the top right corner of the screen (master bar)
* Verify the dropdown is closed when you press the Escape key
* Open the dropdown again
* Verify the dropdown is closed when you click outside of it
* Open the dropdown again and click Log out
* Verify you were logged out of the app

Fixes 1169345694087188-as-1176971703839350

#### Demo
LogOutDropdown

### CODE REVIEW

**Comment by cleacos** [comment]
Same here on mobile view

**Comment by rcanepa** [comment]
Updated to make the dropdown appear regardless of the screen size.
image

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/3672367

Thank you @rcanepa for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/3672367).

**Pull request merged**
