### PR TITLE
Store: match credit card selection appearance to billing page

### PR DESCRIPTION
**Pull request by dechov**
Before | After
-- | --
screen shot 2018-02-12 at 9 44 54 pm | screen shot 2018-02-12 at 9 44 58 pm

Changes:
- Uses `<StoredCard>` component from `my-sites`
- Uses radio buttons instead of checkboxes to control a single selection among options
- Uses a `<label>` instead of handling parent's event, for properly assigning DOM focus
- Eliminates spacing between cards

Concerns:
- `<StoredCard>` is a component inside `my-sites`, instead of `components` — should we be wary of reusing it? Or should we move it into `components` upon reusing it?
- The `getPaymentMethodTitle` function is now only used to describe the selected card, not in the selection. The `<StoredCard>` component uses an identical format except that it doesn't map the `card_type` to a display name (i.e. 'visa' -> 'VISA', 'amex' -> 'American Express', etc). Should this be brought into `<StoredCard>`?

### CODE REVIEW

**Comment by jeffstieler** [comment]
> `<StoredCard>` is a component inside `my-sites`, instead of `components` — should we be wary of reusing it? Or should we move it into `components` upon reusing it?

It looks like a nice simple component - it makes sense to move it to `/components/`. 👍 

Re: `getPaymentMethodTitle` - yes I think that should be brought into `StoredCard` - it's doubtful that the lowercase object-property-representation of the payment methods was the desired display name.

Also - Is some of the style not working? It looks like the selected card is supposed to use the full color logo: https://github.com/Automattic/wp-calypso/blob/5f15f3365213253724ca0d8798c6cb8160f00bc9/client/my-sites/checkout/checkout/stored-card.scss#L48

**Comment by dechov** [comment]
Rebased on https://github.com/Automattic/wp-calypso/pull/22840 to take advantage of existing credit card selector code and design. Now matches selector in WP.com plans' checkout view, and looks like:

Before | After
-- | --
screen shot 2018-02-26 at 11 13 59 pm | screen shot 2018-02-26 at 11 26 26 pm

cc @kellychoffman for design review and/or sign-off

**Comment by kellychoffman** [comment]
Love it! So much more clear. :shipit:

**Comment by kellychoffman** [comment]
I tested this out on one of my sites without a credit card. When I added one, it didn't automatically select it for me, but it wasn't really obvious: 

screen shot 2018-03-01 at 4 44 04 pm

Could we automatically select it? When there's only one card selected in the billing page, it looks the same as above, so perhaps we should abandoned the green highlight I was initially excited about. In the name of consistency. The billing page for example: 
screen shot 2018-03-01 at 4 49 56 pm

Seems like the best option is to go back to your original idea of aligning with the billing page, radios and all.

**Comment by dechov** [comment]
@kellychoffman Just in case it wasn't totally clear, the newer changes align with the credit card selector on the WP.com plan checkout screen (https://wordpress.com/checkout/:site, after choosing to upgrade a plan at https://wordpress.com/plans):

screen shot 2018-03-02 at 12 08 32 am

...but they do also align with the billing page, insofar as those two are aligned with each other (shared component & duplicate styling, even prior to https://github.com/Automattic/wp-calypso/pull/22840). The billing page doesn't have a concept of selection, so all of the cards appear deselected, by checkout page standards.

The radio buttons aren't currently used for payment methods anywhere AFAIK — they were simply a revision of the checkboxes — but we can bring them back if we do need to clearly represent a "nothing is selected" state.

> Could we automatically select it?

🎉 https://github.com/Automattic/woocommerce-services/issues/1315 tracks this question, and I think we should — especially in the case you mention, where a card was just added. I actually don't see why there should ever be cards in the list without one selected, except that we had wanted to avoid implicitly selecting a card for the merchant (https://github.com/Automattic/woocommerce-services/issues/779, https://github.com/Automattic/woocommerce-services/pull/1076). I expect https://github.com/Automattic/wp-calypso/pull/22890 (if/when it lands) to make it more acceptable to always default to the first available card, since the payment method would always be confirmed at the point of purchase, but I'm not sure whether it moots the issue entirely.

**Comment by kellychoffman** [comment]
Can we fix the "selected" issue here? Especially when there's only one card added. Its an important part of the flow that feels broken.

**Comment by v18** [comment]
@dechov hey, I noticed that this PR is marked to be merged into `update/credit-card-list-item-into-reusable-component`, but that branch no longer exists. I see that the work is now being done in https://github.com/Automattic/wp-calypso/pull/24485

Should this branch eventually be rebased on that work?

It sounds like this PR is waiting on the credit card component changes, so I marked it in progress so it's easier for our team to see which PRs can be reviewed right now. Feel free to update the status if 
I got it wrong :)

**Comment by alisterscott** [comment]
Is this one still in progress?

**Comment by alisterscott** [comment]
Closing due to inactivity - please reopen if necessary

**Pull request closed without merging**
