### PR TITLE
Take two: Implement white login for all /log-in routes

### PR DESCRIPTION
**Pull request by niranjan-uma-shankar**
Re-implements Automattic/wp-calypso#69598 and fixes the pre-release test that failed during deployment.

### CODE REVIEW

**Comment by niranjan-uma-shankar** [comment]
@worldomonation Heads up that I've updated two e2e test files because the new login page no longer has a "Sign Up" button in the masterbar, and this caused the pre-release tests to fail while merging https://github.com/Automattic/wp-calypso/pull/69598.

**Comment by tyxla** [comment]
Hey, @niranjan-uma-shankar I know it's a bit late, but I'd generally never recommend merging without explicit approval unless it's exceptionally urgent or extremely trivial with zero percent to break something. This PR definitely looks like a high-impact one and a change I'd want to get someone's eyes on before merging, even if the difference to the last take was just an e2e test fix. Just my $0.02.

**Comment by niranjan-uma-shankar** [comment]
The only reason I went ahead was that this was a direct revert of a revert for a previously [approved PR](https://github.com/Automattic/wp-calypso/pull/69598) and the only addition was to an e2e test file. I've noted your feedback and though it's late now, I'll definitely keep it in mind for the next time. Thanks for letting me know!

**Comment by tyxla** [comment]
I understand, and thanks for confirming that was the case, but it's worth emphasizing that with many folks committing in the same repo it's easy for those things to get out of place and people to commit without approvals. Even if we haven't enforced it yet, our [official policy](https://github.com/Automattic/wp-calypso/blob/cd3603a9fb92f58f8167c39a61e5ecdcd95f6933/docs/CONTRIBUTING.md#pull-requests) is still that every PR should be approved before merging:

> Every PR should be reviewed and approved by someone other than the author, even if the author has write access. Fresh eyes can find problems that can hide in the open if you’ve been working on the code for a while.

**Comment by simison** [comment]
@tyxla while the login page itself is very high-impact, and was indeed reviewed & tested thoroughly like you said, I think E2E tests _aren't_ high impact on production/customers. That's why I think it was fine to merge E2E tests like this to keep moving, but I appreciate you folks as repo maintainers have differing opinion and we should respect that going forward! :-)

**Comment by simison** [comment]
How come pre-release tests failed on deploy even if they passed in PR? 

I rebased the PR before testing locally, but I didn't push the rebase to the branch and it was somewhat stale. Is that why?

From https://github.com/Automattic/wp-calypso/pull/69598#event-7853551364:

image

**Comment by simison** [comment]
> How come pre-release tests failed on deploy even if they passed in PR?

Anyone from @Automattic/kitkat has insights here?

**Comment by worldomonation** [comment]
> How come pre-release tests failed on deploy even if they passed in PR?

> Anyone from https://github.com/orgs/Automattic/teams/kitkat has insights here?

This is because Pre-Release Tests triggered on branch is not targetting the calypso.live container, but rather the production `wpcalypso.wordpress.com`. Which means that your changes aren't actually reflected when you run Pre-Release Tests on branch.

I wrote a handy tutorial on how to run Pre-Release Tests against the changes [here](PCYsg-JGn-p2).

Edit: as an addendum, E2Es - and tests in general - should be treated as high impact, as the introduction of failing test will certainly confuse developers at best and block deploys at worst.

Edit x2: looking at the login page for the first time since this change was merged, I would say this was a very risky proposition to merge without any reviews or approvals. Thankfully the copy and CSS (where critical for E2E) didn't change, but this easily could have led to a permanent failure for everyone across the board in TeamCity.

**Comment by niranjan-uma-shankar** [comment]
> Thankfully the copy and CSS (where critical for E2E) didn't change, but this easily could have led to a permanent failure for everyone across the board in TeamCity.

I'm not sure I understand how this could have led to a permanent failure, unless the deploy was followed through in spite of failing pre-release tests after merge? Is there a scenario of pre-release giving a false positive _after_ the PR is merged? I assume not from the diagram shared in the field guide page, since after merge the tests would correctly target the updated image in wpcalypso environment.

The deploy would have been halted if the pre-release tests had failed after merge. This was why https://github.com/Automattic/wp-calypso/pull/69598 was reverted with https://github.com/Automattic/wp-calypso/pull/70220 while the changes were still in staging/wpcalypso environment since pre-release had failed after merge. There would have been a period of temporary failure for developers while the revert PR was still waiting to be merged (and in this period, Calypso channel was turned red to limit further merges).

**Comment by worldomonation** [comment]
> I'm not sure I understand how this could have led to a permanent failure, unless the deploy was followed through in spite of failing pre-release tests after merge? Is there a scenario of pre-release giving a false positive after the PR is merged? I assume not from the diagram shared in the field guide page, since after merge the tests would correctly target the updated image in wpcalypso environment.

Yes, Pre-Release Tests should not start failing if the merged changes are tested and found to be okay. 

The Pre-Release Tests and the Calypso E2E are not the only tests that run on CI however:
- P2 suite of tests also run on a predetermined schedule and involve the login process.
- Gutenberg/Editor suites of tests also run on a predetermined schedule.
- lastly and at most risk was the Authentication suite of tests, also in a separate build configuration and is on a schedule instead of being triggered for every commit, testing authentication with SMS/TOTP, Google and Apple logins.

So while the statement of "permanent failure across the board in TeamCity" is an overstatement, the changes do impact more than just the commonly used build configurations.

**Comment by simison** [comment]
> and is on a schedule instead of being triggered for every commit, testing authentication with SMS/TOTP, Google and Apple logins.

Is there a way to trigger these manually in PRs? We could also determine a list of files which automatically trigger these tests. I don't think reviews can really replace just running the test suite in CI env.

**Comment by worldomonation** [comment]
> > and is on a schedule instead of being triggered for every commit, testing authentication with SMS/TOTP, Google and Apple logins.
> 
> Is there a way to trigger these manually in PRs? We could also determine a list of files which automatically trigger these tests. I don't think reviews can really replace just running the test suite in CI env.

IIRC it is possible to [match on files that are changed](https://jetbrains.com.xy2401.com/help/teamcity/configuring-vcs-triggers.html#ConfiguringVCSTriggers-GeneralSyntax). 

However, the challenge stems not from the technical aspect of TeamCity, but rather from the current limitation of our SMS plan with Mailosaur. Currently, we most likely use the [Business plan](https://mailosaur.com/pricing/) which includes 500 SMS per month. This is just enough to cover the execution of Authentication E2E once every 6 hours.

In order to trigger Authentication E2E outside of the regularly scheduled cadence, we would need to upgrade to the Professional plan for $20/month/seat, we would gain 2000 more messages at the expense of $4/month/seat. Coupled with a tightly controlled list of files to monitor and it would be possible to trigger Authentication E2E every time the files are changed.

Edit: I've inquired with Accounts Payable folks to check how much we spend on Mailosaur, and if we could bump up SMS numbers feasibly. p1669152161310669-slack-CNFSK9HFV

**Pull request merged**
