### PR TITLE
Fix the alignment of domain suffix for Professional Emal

### PR DESCRIPTION
**Pull request by dlind1**
#### Changes proposed in this Pull Request

When purchasing a new Professional Email subscriptions, the @ sign in @your-domain.tld should always appear to the left of the domain, but shows to the right in RTL languages. This fix wraps it in LRM/PDF characters to force the text to appear as LTR and makes sure that the input field suffix is always to the right of the email address.

Before:
Image 2021-10-01 at 5 19 02 PM

After:
Image 2021-10-01 at 5 26 58 PM

#### Testing instructions

Testing instructions

1. Change your language in Calypso to Arabic or Hebrew.
2. Checkout the branch and navigate to `http://calypso.localhost:3000/email/your-domain-name` for a site with a domain or `http://calypso.localhost:3000/domains/add/some-very-random-domain-name.uk/email/your-site-name.wordpress.com` if you don't have a domain.
3. Confirm that all the @your-domain-name strings appear correctly on the page for Titan/GSuite forms.
4. Change the language to an LTR locale and test for regression issues.

Fixes 312-gh-Automattic/i18n-issues

### CODE REVIEW

**Review by jornp — COMMENTED** [review]
The change works great! 

I was wondering, additionally, should the entire "@Domain" suffix be placed on the right-hand side of the input instead of the left (to make the entire email address read left-to-right)? That's what I understand from the related issue.

**Comment by daledupreez** [comment]
@dlind1, does it make sense to do this in `client/components/gsuite/gsuite-new-user-list/new-user.tsx` as well? We're using the same component for Google Workspace email addresses.

**Comment by dlind1** [comment]
@jornp @daledupreez Thanks! I've implemented both suggestions.

**Review by yuliyan — APPROVED** [review]
Tested and it works good, LGTM!

**Pull request merged**
