### PR TITLE
FSE Plugin: New (updated) patterns

### PR DESCRIPTION
**Pull request by ianstewart**
This PR should add 10 new patterns to the FSE Plugin. Replaces https://github.com/Automattic/wp-calypso/pull/42175

### CODE REVIEW

**Comment by ianstewart** [comment]
There's an issue with the layered images and call to action pattern on simple sites …

image

**Comment by p-jackson** [comment]
The coming soon template is barfing on an atomic site.

Screenshot 2020-06-02 at 2 44 43 PM

The issue appears to be the line height rule. If I create my own paragraph block with custom styling it works, but curiously the line height doesn't appear as an inline style! 😕

**Comment by p-jackson** [comment]
Screenshot 2020-06-02 at 2 54 38 PM

The custom typography settings aren't all being reflected in the blocks inline style. In the above image the line-height is 4.7 but that's not in the html's `style=""` attribute.

The documents markup looks like:
```html
<!-- wp:paragraph {"style":{"typography":{"lineHeight":"4.7","fontSize":34},"color":{"text":"#0a5e82"}}} -->
<p class="has-text-color" style="font-size:34px;color:#0a5e82">Me making a paragraph from scratch</p>
<!-- /wp:paragraph -->
```
So the line height is there in the block settings.

I wonder if this is a known bug, which is why it's working in simple sites? Atomic is running Gutenberg `8.1.0` but simple sites is running `8.1.0-wpcom` which I believe means we've patched it with some of our own fixes. I wonder if this is one of those fixes.

Other possibility is that it's something like Coblocks (which has it's own typography settings) is overwriting what the paragraph block is supposed to do. Atomic and simple run different versions of Coblocks.

**Comment by p-jackson** [comment]
The line-height issue has already been reported to CoBlocks: godaddy-wordpress/coblocks#1500

The following patterns all add broken markup to the document because of the line height issue, and they're all fixed with CoBlocks is disabled.
- `coming-soon.php`
- `contact-04.php`
- `list.php`
- `numbered-list.php`

I don't know if it's possible to work around the issue by achieving the desired layout with using line height?

I haven't gotten any further on why the `layered-images-and-call-to-action.php` pattern is broken, but it's broken on simple and atomic. I can't see what's wrong with the column markup that it complains about. As far as I can tell it matches the markup generated for a new column block. It also renders correctly after saving and refreshing the page.

**Comment by simison** [comment]
Watch out for categories PR in case it gets merged first https://github.com/Automattic/wp-calypso/pull/42761

**Comment by ianstewart** [comment]
> Atomic is running Gutenberg 8.1.0 but simple sites is running 8.1.0-wpcom which I believe means we've patched it with some of our own fixes. I wonder if this is one of those fixes.
> Atomic and simple run different versions of Coblocks.
> yup, disabling CoBlocks [on Atomic] fixes the issue with the coming soon pattern

_Is it_ a patch in 8.1.0-wpcom that's fixing this issue? Is that something we can contribute back to Coblocks? And/or patch with Atomic sites?

**Comment by ockham** [comment]
> Thanks for looking at this @p-jackson!
> 
> > Atomic is running Gutenberg 8.1.0 but simple sites is running 8.1.[0-wpcom](https://href.li/?https://wpcom.trac.automattic.com/ticket/0) which I believe means we've patched it with some of our own fixes. I wonder if this is one of those fixes.
> > Atomic and simple run different versions of Coblocks.
> > yup, disabling CoBlocks [on Atomic] fixes the issue with the coming soon pattern
> 
> _Is it_ a patch in 8.1.[0-wpcom](https://href.li/?https://wpcom.trac.automattic.com/ticket/0) that's fixing this issue? Is that something we can contribute back to Coblocks? And/or patch with Atomic sites?

FWIW, `8.1.0-wpcom` is just `8.1.0` with [this commit](https://github.com/WordPress/gutenberg/pull/22028/commits/12e24f0beeda1286be143a8c13b75226c3d37fa7) reverted as a workaround to issues with the VideoPress block that we later fixed in the Jetpack repo (more info: pbAok1-107-p2). _tl;dr_ -- nothing we could/should contribute to Core :slightly_smiling_face:

**Comment by simison** [comment]
I think new Jetpack ships today (June 2nd) and we just shipped Gutenberg 8.2.0 to simple sites (and soon to Atomic). From what I understand, that all should solve those issues.

**Comment by p-jackson** [comment]
> > Atomic is running Gutenberg 8.1.0 but simple sites is running [8.1.0-wpcom](https://href.li/?https://wpcom.trac.automattic.com/ticket/0) which I believe means we've patched it with some of our own fixes. I wonder if this is one of those fixes.
> > Atomic and simple run different versions of Coblocks.
> > yup, disabling CoBlocks [on Atomic] fixes the issue with the coming soon pattern
> 
> _Is it_ a patch in [8.1.0-wpcom](https://href.li/?https://wpcom.trac.automattic.com/ticket/0) that's fixing this issue? Is that something we can contribute back to Coblocks? And/or patch with Atomic sites?

Sorry @ianstewart the `8.1.0-wpcom` was a red herring, unfortunately the bug lies with CoBlocks.

> I think new Jetpack ships today to Atomic (June 2nd) and we just shipped Gutenberg 8.2.0 to simple sites (and soon to Atomic). From what I understand, that all should solve those issues.

Unfortunately the Jetpack and Gutenberg upgrades don't resolve the issue (tested on an ephemeral site). It's not that we've fixed the issue on simple sites somehow, it's that our custom simple sites build of CoBlocks [comments out some of the CoBlocks code](https://github.com/Automattic/coblocks-builder/blob/3d0a1095d5434a2f3c80f227e357ff8d54641f04/blocks.js#L20), so we don't have a fix we can push upstream. (I haven't confirmed that the exactly commented out line I linked to is the thing that resolves the issue).

**Comment by p-jackson** [comment]
FYI @ianstewart @iamtakashi this would 🤞 fix the issues with the line heights in paragraph blocks godaddy-wordpress/coblocks#1526

**Comment by ianstewart** [comment]
@p-jackson that's great!

**Comment by p-jackson** [comment]
CoBlocks 2.0 has just shipped, so I actually think this is unblocked now. It was never broken on simple sites and Atomic sites pick up the new version.

Actually I'll need to check whether existing Atomic sites get the new CoBlocks version or whether it's only newly provisioned sites that get it 🤔 

Actually I also just noticed that a bunch of the new patterns are appearing in the "uncategorized" category. So we should add them to categories now that that's shipped.

**Comment by p-jackson** [comment]
Just checked my existing atomic test site: it's been updated to CoBlocks 2.0 🎉

**Comment by p-jackson** [comment]
I've added each of the new patterns to a category.
| Pattern | Categories |
|-----|-------|
| `call-to-action-03.php` | call to action |
| `coming-soon.php` | contact **and** text |
| `contact-04.php` | contact |
| `images-with-titles.php` | gallery |
| `list.php` | text |
| `numbered-list.php` | text |
| `portraits-and-text.php` | images |
| `tiled-mosaic-gallery.php` | gallery |
| `two-column-text-and-image.php` | images |

**Comment by iamtakashi** [comment]
@p-jackson @ianstewart Can we change the category like the following? I've only listed the patterns I'd like to be categorised differently, I think the rest is perfect.

| Pattern | Categories |
|-----|-------|
| `coming-soon.php` | call to action |
| `images-with-titles.php` | gallery **and** lists |
| `list.php` | lists |
| `numbered-list.php` | lists |
| `portraits-and-text.php` | gallery **and** lists |

**Comment by p-jackson** [comment]
Made the above adjustments. Added a new "List" category. Went with the singular, instead of "Lists", to match the other categories e.g. Gallery, Text, Blog.

**Comment by iamtakashi** [comment]
@p-jackson Thanks! In terms of categorization, LGTM 👍

**Comment by jeyip** [comment]
This ticket looks ready to me. @ianstewart what do you think?

**Comment by ianstewart** [comment]
Agreed. I'm going to merge and hopefully 🤞 we can get it into an FSE update soon!

**Pull request merged**
