### PR TITLE
Add `reformat-files:css` script

### PR DESCRIPTION
**Pull request by simison**
Adds `reformat-files:css` script that runs `stylelint --fix` on files.

There's this note [in the docs](https://github.com/stylelint/stylelint/blob/master/docs/user-guide/cli.md#autofixing-errors):

>It's an experimental feature. It currently does not respect special comments for disabling stylelint within sources (e. g. `/* stylelint-disable */`). Autofixing will be applied regardless of these comments.
>
>If you're using both these special comments and autofixing, please run stylelint twice as a temporary solution. On the first run, some violations could be missed, or some violations might be reported incorrectly.

Solution might be not run this together with `reformat-files` command and let folks run this only manually.

#### Changes proposed in this Pull Request

* Add new `reformat-files:css` script which always exists with `0` — otherwise if there are errors left, `--fix` [will exit with `2`](https://github.com/stylelint/stylelint/blob/master/docs/user-guide/cli.md#exit-codes) and make it seem like `reformat-files` failed. `-c` in `reformat-files` is meant to let `reformat-files:js` finish even if `:css` would exit with non-0 earlier, so I'm fine also changing it to throw an error at the end.
* Add `.json` to config file so that it'll get run through Prettier ([docs about `.json` support](https://stylelint.io/user-guide/configuration/#loading-the-configuration-object))
* Run some files through it.

#### Testing instructions
Run:
- `npm run reformat-files`
  - Observe `reformat-files:js` finish even if `:css` finishes earlier
  - Linter throws some errors/warnings about stuff it cannot autofix but doesn't fail the NPM script with error. 
  - A bunch of files have changed (happy to include these in the PR, but I made a separate: https://github.com/Automattic/wp-calypso/pull/32386)
- `npm run reformat-files:css`

### CODE REVIEW

**Comment by blowery** [comment]
rebased this and resolved the conflicts in package.json::scripts

**Comment by simison** [comment]
Rebased. Still not sure if this is helpful or too risky (see the warning I added in description).

This would be handy if we'd switch e.g. to this from [our custom Stylelint config](https://github.com/Automattic/wp-calypso/blob/46a9eafeda1d2d74871b527b25765fd7a9f7ae1e/.stylelintrc):
```json
{
	"extends": "stylelint-config-wordpress/scss"
}
```

**Comment by scinos** [comment]
This PR has been open for a while. Is it still relevant?

**Comment by simison** [comment]
Autofixer might be now safe enough to use: https://github.com/stylelint/stylelint/issues/2643

**Comment by simison** [comment]
Considered closing this, but checked with Team Calypso (p1623060403258400-slack-team-calypso) and I think we can keep open until someone picks the stylelint work at some point. This will work as a good starting off point:

> fine to keep open by me. Running stylelint as part of CI is something I’d like to do eventually

**Comment by simison** [comment]
@noahtallen is this PR needed for the recent stylelint work or shall I close? Feel free to just hit close button yourself! :-)

**Comment by noahtallen** [comment]
Yeah, I think it's worth closing!

**Comment by noahtallen** [comment]
I didn't add a reformat files script, but that'd be incredibly easy to add if we need it. And just adding `--fix` to `yarn lint:css` is very easy too

**Pull request closed without merging**
