### PR TITLE
Hosting dashboard: remove initial selected site hack

### PR DESCRIPTION
**Pull request by fushar**
Fixes:

- https://github.com/Automattic/wp-calypso/issues/93827

## Proposed Changes

This PR removed the hack which "clicks" the initial selected site in the hosting dashboard. We can now pass an initial selection to the DataViews component.

## Why are these changes being made?

We have upgraded DataViews package to the latest version which support controlled mode.

## Testing Instructions

1. Go to /sites.
2. Click a site.
3. Verify that the preview pane is open.
4. Verify that the clicked site is in the selected state in the left "sidebar".

## Pre-merge Checklist

- [x] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [x] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [x] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [x] Have you checked for TypeScript, React or other console errors?
- [x] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [x] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [x] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Comment by fushar** [comment]
@allilevine @cleacos: I am not super happy with this solution; seems like the more "proper" solution is to actually get rid of `dataViewsState.selectedItem` and replace it with "native" `selection` prop. And then move the logic of maintaining the selected (single) item to `onSelectionChange`, instead making it a noop like what I do in this PR.

But I'm not very sure. That would seem to touch more things than needed. Any thoughts?

**Review by Addison-Stavlo — APPROVED** [review]
The no-op is a bit odd, but with the comment it makes sense! Overall the changes here are great, getting rid of that query selector click hack hook and it seems to test well on my end.

> I am not super happy with this solution; seems like the more "proper" solution is to actually get rid of dataViewsState.selectedItem and replace it with "native" selection prop. And then move the logic of maintaining the selected (single) item to onSelectionChange, instead making it a noop like what I do in this PR.

Perhaps? 🤔 It does sound more "proper" indeed.

Either way, it seems like it could potentially be a follow up to explore from here as well. This PR currently seems to be a good step in that direction whether we decide to explore that approach or not.

**Comment by allilevine** [comment]
>  I am not super happy with this solution; seems like the more "proper" solution is to actually get rid of dataViewsState.selectedItem and replace it with "native" selection prop. And then move the logic of maintaining the selected (single) item to onSelectionChange, instead making it a noop like what I do in this PR.
> But I'm not very sure. That would seem to touch more things than needed. Any thoughts?

@fushar I agree that we should use `selection` as intended, but I looked for a way to use the prop without `dataViewsState` and I'm not sure how that would work with the current component structure. I kept ending up back at setting some kind of state in /hosting/sites/components. 

Would `onSelectionChange` (or `onChangeSelection`) replace [the useSyncSelectedSite hook](https://github.com/Automattic/wp-calypso/blob/dataviews-selected-site-hack/client/hosting/sites/hooks/use-sync-selected-site.ts#L7)?

Adding @oandregal and @youknowriad for your thoughts.

**Comment by fushar** [comment]
> @fushar I agree that we should use selection as intended, but I looked for a way to use the prop without dataViewsState and I'm not sure how that would work with the current component structure. I kept ending up back at setting some kind of state in /hosting/sites/components.

Same!!

After exploring the codebase, I think the reason is as follows:

1. The DataViews table layout won't allow `onSelectionChange` callback on a table row, unless the table has "bulk actions" on it: https://github.com/WordPress/gutenberg/blob/82bc72dedd2815fbc0d407782fde2a12c4139a7e/packages/dataviews/src/dataviews-layouts/table/index.tsx#L173-L187.
2. This means we still need to pass the `openSitePreviewPane` callback manually: https://github.com/Automattic/wp-calypso/blob/692b14d7e3749141337ec9cd45bf2358f508546a/client/hosting/sites/components/sites-dataviews/index.tsx#L111
3. This means we need to keep track of `selectedItem` manually somewhere. We put that it inside the `dataViewsState` state.
4. When a site row is clicked, we transform the layout to a list layout (as the sites list sidebar). Here, I think we can use a "proper" `onSelectionChange` logic; however, it's not necessary since we already have the `openSitePreviewPane` callback on the site name cell.

I believe the above items lead to the existing logic that we have today.

**Comment by fushar** [comment]
> Would onSelectionChange (or onChangeSelection) replace [the useSyncSelectedSite hook](https://github.com/Automattic/wp-calypso/blob/dataviews-selected-site-hack/client/hosting/sites/hooks/use-sync-selected-site.ts#L7)?

I think it would... partially. The second direction of the logic is to make sure that whenever our own redux store's "selected site ID" is updated, the selection gets updated too. I don't think this part can be achieved using `onSelectionChange` alone. 🤔

**Comment by youknowriad** [comment]
If `dataViewsState` is the source of truth of the selectedID, I would just expect `onSelectionChange` to call `setDataViewsState` to change the selectedID. Why can't we do that?

**Comment by fushar** [comment]
> If dataViewsState is the source of truth of the selectedID, I would just expect onSelectionChange to call setDataViewsState to change the selectedID. Why can't we do that?

Because we already tracked the currently selected item as `dataViewsState.selectedItem` (I'm not sure why we did this in the first place).

I can try timebox some time tomorrow to replace that with `selection`.

**Comment by youknowriad** [comment]
> Because we already tracked the currently selected item as dataViewsState.selectedItem (I'm not sure why we did this in the first place).

What I'm saying is that if an interaction on the dataviews component is supposed to change the selected item (so a call to `onSelectionChange`) why aren't actually calling `setDataViewsState` to change `dataViewsState.selectedItem`

**Comment by fushar** [comment]
> What I'm saying is that if an interaction on the dataviews component is supposed to change the selected item (so a call to onSelectionChange) why aren't actually calling setDataViewsState to change dataViewsState.selectedItem

@youknowriad I had explained my finding on my previous comment https://github.com/Automattic/wp-calypso/pull/94295#issuecomment-2337100613, does that answer your question?

**Comment by youknowriad** [comment]
I think I understand better and it seems to relate to what @oandregal raised separately about the difference in behavior between "click to select" or "click to navigate" and the need to settle on one. I guess we can probably ship this and iterate on that decision separately.

**Comment by fushar** [comment]
Thanks all. Yeah, at this point I think it's better to ship this first and iterate later as needed.

**Pull request merged**
