### PR TITLE
composite-checkout: Allow removing coupons from cart

### PR DESCRIPTION
**Pull request by sirbrillig**
#### Changes proposed in this Pull Request

This adds a trash button next to coupon items in the review order step in composite checkout. It is hooked up to the cart manager so that coupons can be removed from the cart, if desired.

coupon-delete-button

#### To do

- [x] When deleting a coupon immediately after adding it, the coupon field still contains the coupon code and also displays an error as though the coupon failed to add. I'm not sure what's causing this.
- [x] The copy in the confirmation dialog is not very applicable to coupons. Maybe we should change it? It currently reads: "You are about to remove your product from the cart; When you press Continue, we will remove your product from the cart and your site will continue to run without it." Honestly that wording is a little confusing anyway. What if we changed it to: "You are about to remove a product from your cart; Press Continue if you are sure you want to remove it."
- [x] If you remove a coupon and you're on the last step, the payment method gets set to the first available one but with invalid data. We should instead switch back to the first step.

#### Testing instructions

Add a coupon to your cart (in either version of checkout), then, using composite checkout, click to remove it from your cart in the review step. Make sure that after you confirm the dialog, the coupon is removed.

### CODE REVIEW

**Comment by sirbrillig** [comment]
Thanks. I had noted that in the description but I finally figured out why it was happening. I rebased this on top of #39856 and discovered a new issue: when you remove a coupon, the payment method gets reset to credit card, but there might not be anything in the credit card form.

I'm not sure what the best UX is here, but it might be best to redirect back to the first step in that case. I'm working on it.

**Comment by fditrapani** [comment]
> I'm not sure what the best UX is here, but it might be best to redirect back to the first step in that case. I'm working on it.

Yeah, I think taking people back to the payment method step makes sense. Another option could be to use the dialogue to explain that so it's not as abrupt. We can see how it feels first before going that extra step though.

**Comment by fditrapani** [comment]
Looks like we already show that message but yeah, just taking people back to the top of the screen and opening the first step would be great.

**Comment by sirbrillig** [comment]
Got it. Now the only issue (that I can find) is the dialog text (see the PR description). Any thoughts on that?

**Comment by fditrapani** [comment]
Tried this out again and it functionally works better. There's still a little weirdness when we transition to show all the other steps. This isn't a blocker, and can be done in a separate PR, but could we make that transition before we hide the modal. Imagine pressing the button, then it becomes a busy button, and then when the modal clears you see the updated form? 

> Honestly that wording is a little confusing anyway. What if we changed it to: "You are about to remove a product from your cart; Press Continue if you are sure you want to remove it."

That does sound a little better but maybe we should change the title as well. How does this sound:

Title: "Remove {product name}"
Copy: "You are about to remove {product.name} from your cart. Press **Continue** if you are sure you want to remove it."

> Now the only issue (that I can find) is the dialog text

Can we do something unique for coupons? 

Title: "Remove Coupon"
Copy: "You are about to remove your coupon from the cart. When you press **Continue** we will need you to confirm your payment details."

**Comment by sirbrillig** [comment]
I agree about the transition being awkward, but in the interest of letting users delete coupons, I think this is a good 1.0. We'll take a look at that later.

I modified the modal for coupons to look like this:

Screen Shot 2020-03-09 at 3 18 52 PM

We can do more iterations, including improving the copy for this and other delete modals, in a separate PR.

**Comment by michaeldcain** [comment]
I tested this in both checkouts and it LGTM. 

Unrelated, I noticed that we don't submit a coupon if there's whitespace in the textfield and we could do a better job with our discount rounding - I'll open up some new tickets.

**Comment by fditrapani** [comment]
Thanks for bringing those up. I just test this again and it looks good with 100% discounts for now. I'll add a couple cards to change the messaging for partial discounts and not take people back to the payment step because it works a little different — I'll add it.

**Pull request merged**
