### PR TITLE
Add headers to main reader pages

### PR DESCRIPTION
**Pull request by davemart-in**
## Description

The name “Reader” is only visible on the top tab, but the page itself doesn’t have a header or description to explain what a visitor is looking at. This PR aims to add a header and sub header description to the following primary reader pages:

- Search
- Recent
- Discover
- Likes
- Conversations

### Before

before

### After

After

## Related

https://github.com/Automattic/loop/issues/69

## Testing

- Apply this PR
- Visit the following pages:
  - http://calypso.localhost:3000/read/search
  - http://calypso.localhost:3000/read
  - http://calypso.localhost:3000/discover
  - http://calypso.localhost:3000/activities/likes
  - http://calypso.localhost:3000/read/conversations
- Test various resolutions for each page

### CODE REVIEW

**Review by Addison-Stavlo — COMMENTED** [review]
Testing now, the code looks good but my only question there is whether some of these repeated CSS rules can be consolidated to a more shared css file - but not a blocker.

**Review by Addison-Stavlo — APPROVED** [review]
This tests well and looks good!

I imagine it will look better when we fit other designs that have the gray background and white post cards. Right now everything kind of blends and I almost wonder if we should have a `<hr/>` or something below the new header to separate?

**Comment by davemart-in** [comment]
Thanks for the review! Yeah, I considered combining the CSS, but there were enough tiny differences that it didn't make sense. I do agree that things will likely look much better once we add the grey background. It all feels rather washed out right now.

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/8602713

Thank you @davemart-in for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/8602713).

**Pull request merged**
