### PR TITLE
keyedReducer: remove global actions, add explicit code for {DE}SERIALIZE

### PR DESCRIPTION
**Pull request by jsnajdr**
Removes support for `globalActions` from `keyedReducer` because of zero usage.

Replaces the `globalActions` by explicit code for handling `SERIALIZE` and `DESERIALIZE`, as these actions are very special.

The `SERIALIZE` code will be further updated in #27415 to work with the `SerializationResult` class.

The `SERIALIZE` handler in `keyedReducer` has one new feature: if the serialized state of the `keyedReducer` is empty object (`{}`), we return `undefined` instead and therefore avoid storing the empty state in IndexedDB. Keys that are empty are not stored at all.

#### Testing instructions

Verify that state for keyed reducers is persisted as expected when it has data. Verify that the reducer's  state is omitted from the persisted state object if it's empty.

One good reducer to test is `state.posts.likes`. If you load Calypso with Reader or Stats, `state.posts.likes` should be empty and the persisted state object shouldn't have that key at all.

Now if you go to stats for a particular post (`/stats/post/:post/:site`), likes for that posts are fetched and stored in Redux. If you inspect your IndexedDB after a while, you should see the persisted `posts.likes.items` object there.

### CODE REVIEW

**Comment by blowery** [comment]
screenshot 2018-11-13 11 31 17

Loaded with stats in dev after a sympathy clear and I'm still seeing an empty `state.posts.likes.items` object in state. Is that expected?

**Comment by jsnajdr** [comment]
@blowery If you expand the `items` key, is it really empty or is there some content? I think I saw the Chrome devtools showing a `{}` "preview" and the object having nested keys after expanding. I cannot reliably reproduce that though.

**Comment by blowery** [comment]
Can repro it now. If I load the site totally fresh, there's no posts.likes key at all.

**Review by blowery — APPROVED** [review]
LGTM. State serializes and deserializes as expected.

**Pull request merged**
