### PR TITLE
People: Open Jetpack Invites for all Jetpack Sites

### PR DESCRIPTION
**Pull request by lezama**
**This PR completely removes `'jetpack/invites'` feature flag.**

Since Jetpack 5.0, Jetpack has the required endpoints to make invites work on JP sites. 

Jetpack Invites has been open and tested on AT sites since 4.9

If a site is running an old JP version, users will be prompted to upgrade when trying to Add new users:
screen shot 2017-06-21 at 11 47 37

## Testing instructions

For Jetpack running 5.0 
- make sure "People - Add" button works
- try inviting a user

4.9 and below
- make sure you are prompted to upgrade when trying to use "People - Add"

### CODE REVIEW

**Comment by oskosk** [comment]
I've just tested the following
1. Visiting `/people/new` for a site with Jetpack 4.9
1. Clicked the Update button in the banner that prompted me to update
1. Updated the plugin successfully.
1. Clicked the People Add button
1. Still saw the Upgrade banner.
1. Refreshed the page, it still shows the banner
1. Hard-refreshed the page, it still showed the banner.
1. Refreshed once again and received the `Skipping initial state rehydration to recreate first-load experience.` message in the console, meaning, calypso wouldn't be using old data. The banner was not there and the controls were enabled. Probably we're not re-querying data in that screen?

**Comment by oskosk** [comment]
After accepting an invitation and become an administrator, went back to the inviting user's people page in calypso and switched from one page to another (Sharing and then People again) and the Team list didn't refresh to reflect the new user. Again, this may be out of the scope of this PR

**Comment by oskosk** [comment]
@lezama besides the comments I left, this one is ready to go as it does what's expected.

I introduced 2 commits here:
* One removing unused vars that were making the linter to error.
* Another one, removing the usage of the `target=` prop on the button to add an user. This assumes that our intention is to lead the user always into the Calpso UI for adding an user (as opposed to deciding whether lead them to wp-admin or to Calypso).

**Comment by lancewillett** [comment]
This is *super* exciting and cool. Thank you everyone who worked on this! It was a major gap in the Calypso user flows. 👏

**Pull request merged**
