### PR TITLE
Update related post demo images

### PR DESCRIPTION
**Pull request by davemart-in**
## Changes proposed in this Pull Request

This PR simply updates the demo images shown on Settings > Traffic > Related Posts > (switch show related content after posts) (switch show a thumbnail imaged where available)

Props to @johnmaeda for coming up with these three new images.

## Testing instructions

- Check out this branch
- Compile changes
- View http://calypso.localhost:3000/settings/traffic/{YOUR-DOMAIN}

Fixes https://trello.com/c/ryDVvl2C/105-antique-images-for-related-posts

### CODE REVIEW

**Comment by johnmaeda** [comment]
Every edit that gets us 1% better makes a difference. Good to go.

**Comment by arunsathiya** [comment]
Should we update the Jetpack side of things as well? Currently I don't see the new images on Jetpack settings on wp-admin. // cc @kraftbj

**Comment by keoshi** [comment]
Yeah, we should absolutely do that, @arunsathiya — thanks for catching this. Do you want me to create the PR?

**Comment by keoshi** [comment]
Here's an example of references to the images used in the Jetpack plugin: https://github.com/Automattic/jetpack/search?utf8=%E2%9C%93&q=1-wpios-ipad-3-1-viewsite.png&type=

**Comment by davemart-in** [comment]
> Do you want me to create the PR?
@keoshi that would be awesome.

**Comment by keoshi** [comment]
@davemart-in I've gone ahead and created the PR for the Jetpack plugin here: https://github.com/Automattic/jetpack/pull/11623

I ran the images through Optimage and ended up saving a few KBs, so I've also created another PR for Calypso to use the compressed images: https://github.com/Automattic/wp-calypso/pull/31593

Would appreciate your review on those — thanks in advance!

**Pull request merged**
