### PR TITLE
Add storybook instructions for @automattic/components

### PR DESCRIPTION
**Pull request by p-jackson**
There's probably a lot that will need to be said in the `@automattic/components` README about design decisions and other high level things, but I didn't want that to be a hurdle to getting some docs started. Since I just had to figure out how to get Storybook going I thought get the ball rolling.

@jameslnewell wanted to make sure you're aware that I'm adding this, and also to ask if there's a nicer way that you're running Storybook at the moment?

#### Changes proposed in this Pull Request

* Add README to `@automattic/components`
* Add brief instructions for getting Storybook started

### CODE REVIEW

**Comment by andrewserong** [comment]
Thanks for getting this one started @p-jackson, it took me a little while to dig around and find how to start storybook, too! It looks like we can run it from root using `npm run components:storybook:start` which was introduced in https://github.com/Automattic/wp-calypso/pull/38496

**Comment by jameslnewell** [comment]
@p-jackson No worries! Apologies, I should have documented it! @andrewserong is correct, `npm run components:storybook:start` is how I've been running the Storybook.

**Comment by p-jackson** [comment]
Thanks @jameslnewell I've updated the storybook script and also thown in a reference to the `test-packages` script.

**Comment by p-jackson** [comment]
Merged. We can make it perfect as we go :)

**Pull request merged**
