### PR TITLE
Media Data-Source: Update Google Photos: Approach 2

### PR DESCRIPTION
**Pull request by mreishus**
#### See Also
* See also: Approach 1  #56288

#### Changes proposed in this Pull Request

* In the media data source dropdown, move google photos to the "generic multiple image" logo
  * We are not supposed to display the google photos logo on its own (ie, without accompanying text), according to guidelines.
* Move pexels to its own logo

#### Testing instructions

* In the sidebar, visit media
* Examine and use the source dropdown in the top left

Before: 

After:

Related to #56251

### CODE REVIEW

**Comment by mreishus** [comment]
Moving forward with #2 to get unblocked here: See #56251

**Comment by olaolusoga** [comment]
Agree with going with variation 2 for now. We can circle back and improve.

**Comment by obenland** [comment]
> ModuleNotFoundError: Module not found: Error: Can't resolve './pexels-icon' in '/home/runner/work/wp-calypso/wp-calypso/client/my-sites/media-library'

Looks like that new icon is missing?

**Comment by mreishus** [comment]
Ah, that's why it's not building.. fixed

**Pull request merged**
