### PR TITLE
Logged-In Performance Profiler: Add new performance metric UI

### PR DESCRIPTION
**Pull request by vykes-mac**
## Proposed Changes

* This re-adds changes that were reverted https://github.com/Automattic/wp-calypso/pull/94566

## Why are these changes being made?

*

## Testing Instructions

* see https://github.com/Automattic/wp-calypso/pull/94566
* Verify there are no regression in `/speed-tools` - logged-out version

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Comment by vykes-mac** [comment]
cc: @gavande1 can you verify there's no regression for the logged out version?

**Review by gavande1 — APPROVED** [review]
I have tested the logged-out version of the Performance Profiler and can confirm that there are no regressions. Looks good to me! 👍

**Review by gcsecsey — APPROVED** [review]
I tested the logged-out version for regressions as well, and couldn't find any. 👍

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/16855259

Some locales (Hebrew, Japanese) have been temporarily machine-translated due to translator availability. All other translations are usually ready within a few days. Untranslated and machine-translated strings will be sent for translation next Monday and are expected to be completed by the following Friday.

Hi @vykes-mac, could you please edit the description of this PR and add a screenshot for our translators? Ideally it'd include all of the following strings:
- `See calculator ↗`
- `(90–%(to)s)`
- `(%(from)s–%(to)s)`
- `(%(from)s-%(to)s) `
- `Your site‘s Performance Score is good`
- `Your site‘s Performance Score is moderate`
- `Your site‘s Performance Score needs improvement`
- `What is Performance Score?`
- `(PS)`
- `The performance score is a combined representation of your site‘s individual speed metrics.`

Thank you in advance!

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/16855259).

**Pull request merged**
