### PR TITLE
Revert code that force-inserts `Settings > Newsletter` into sidebar

### PR DESCRIPTION
**Pull request by fredrikekelund**
Related to https://github.com/Automattic/dotcom-forge/issues/8069
Complemented by https://github.com/Automattic/jetpack/pull/38232

## Proposed Changes

* Revert redundant code from #81722

## Why are these changes being made?

The original purpose of this PR was to hide the `My Mailboxes` sidebar link on P2 sites (since email isn't supported on P2 sites). However, I later realized that https://github.com/Automattic/jetpack/pull/38232 was enough to achieve this, and we didn't need any changes in Calypso.

Still, this PR removes some old logic from #81722 that was introduced as a temporary measure until https://github.com/Automattic/jetpack/pull/32992 landed in prod. Well, it's landed now, so it makes sense to remove the temporary code from Calypso. 

Since @mashikag is on leave, I'm tagging @yansern and @simison for review here (since they reviewed #81722)

## Testing Instructions

1. Navigate to the local Calypso home page for an Atomic site with the `Admin Interface Style` setting is set to `Classic style`
2. Navigate to the same page on wordpress.com
3. Compare the links sidebar on the two pages. The local version should not have the `Settings > Newsletter` link, but other than that, they should be identical

### CODE REVIEW

**Review by chad1008 — APPROVED** [review]
Nice find! LGTM :rocket: :ship:

**Comment by fredrikekelund** [comment]
Taking a closer look, it seems I messed something up with the sidebar, which is why the E2E tests are breaking… Looking now

**Comment by fredrikekelund** [comment]
Aside from the changes in 8038f7d283554b365c7a8a2ef0600228fb7fe87d, it looks like I also made a mistake in thinking we needed to cover this in Calypso. We don't, actually. https://github.com/Automattic/jetpack/pull/38232 is enough by itself.

**Comment by fredrikekelund** [comment]
https://github.com/Automattic/jetpack/pull/38232 impacts the return value from the `/admin-menu` API endpoint, which is the canonical data we want to use to build the sidebar. `buildFallbackResponse` is (surprise, surprise) for building a fallback menu when the `/admin-menu` API endpoint doesn't work as expected.

**Review by yansern — APPROVED** [review]
Thanks for the ping! Approving this PR.

**Pull request merged**
