### PR TITLE
[PBD interim fix] Collective PR for clean thank you page

### PR DESCRIPTION
**Pull request by adamziel**
#### Changes proposed in this Pull Request

This PR is part of the PBD interim fix (https://github.com/Automattic/wp-calypso/issues/38110).

It updates checkout "thank you" page for users upgrading to Business in order to install a plugin or a theme.

**Before:**

Zrzut ekranu 2019-12-3 o 14 56 52

**After:**

Zrzut ekranu 2019-12-3 o 14 56 41

#### Potential issues

This will **always** say the site has been launched, even if the user already launched their site earlier. It may be a tad confusing for some users, but reliably figuring out if the site was literally just launched adds a lot of complexity (page refreshes and so on). This feels like a good trade-off. I'm curious about everyone's thoughts though - we could always adjust that.

#### Testing instructions

1. Upgrade to personal/premium/business/ecommerce from both signup and /plans, confirm you see the **Before** page
1. Create a free/personal/premium site
1. Go to /plugins and click on the business plan upgrade nudge (both on plugins list and specific plugin's page)
1. Upgrade to business
1. Confirm the thank you page looks like **After** screenshot above
1. Repeat 2-5 from /themes

### CODE REVIEW

**Comment by adamziel** [comment]
cc @jancavan @ianstewart

**Comment by ianstewart** [comment]
> Upgrade to personal/premium/business/ecommerce from both signup and /plans, confirm you see the Before page

Just noting that when I upgrade from Signup in the calypso.live flow as a new user I see this …

image

… as my "congratulations" screen. Which is my expected result.

**Comment by ianstewart** [comment]
Testing from free account, I upgrade to business from /plans on a free account I see the before page as noted above. Works as expected.

**Comment by ianstewart** [comment]
- Create a free/personal/premium site
- Go to /plugins and click on the business plan upgrade nudge on specific plugin's page
- Upgrade to business
- Confirm the thank you page looks like After screenshot above

This works as expected. I tested with Yoast SEO's specific plugin page. I see the new After screenshot.

**Not expected:**

I expected when clicking "Continue Installing Plugin" to go back to the Yoast SEO plugin page. Not the list of all plugins at /plugins where I would have to find that specific plugin again.

**Comment by ianstewart** [comment]
- Create a free site
- Go to /plugins and click on the business plan upgrade nudge on plugins list
- Upgrade to business
- Confirm the thank you page looks like After screenshot above

This variation works as expected.

**Comment by ianstewart** [comment]
- Create a free site
- Go to /themes and click on install theme
- Click on Business Plan nudge
- Upgrade to business
- Confirm the thank you page looks like After screenshot above

This variation works as expected.

**Comment by ianstewart** [comment]
@adamziel I noticed something unexpected while testing. The copy …

image

My site wasn't launched. It was still private. My expectation was that it would be private. That's great. But the copy is wrong — for the Business Plan. That whole line about my site being launched is not needed when upgrading on a Business Plan.

**Comment by jancavan** [comment]
> This will always say the site has been launched, even if the user already launched their site earlier. 

Wait, I'm confused about this one. If they had already launched their sites earlier, why would they see this message? In that scenario, they'll only really have to see the upgrade nudge? @adamziel

**Comment by shaunandrews** [comment]
Very small point of feedback related to the capitalization of the button:

image

I don't think we should use title case. Instead we should use normal sentence-case. So it would be "Continue installing plugin"

**Comment by jancavan** [comment]
Thanks @shaunandrews. I thought there's an existing pattern because when I look around Calypso, they seem to all be title case.

**Comment by shaunandrews** [comment]
It’s inconsistent for sure, but those examples you show seem to be wrong. Here’s the documentation:

https://github.com/Automattic/wp-calypso/blob/83cefb18976d90ddee3ca9518c7cb375b0ff1a14/packages/calypso-ui/src/button/README.md

> Use sentence-style capitalization.

**Comment by p-jackson** [comment]
> My site wasn't launched. It was still private. My expectation was that it would be private. That's great. But the copy is wrong — for the Business Plan. That whole line about my site being launched is not needed when upgrading on a Business Plan.

I think this PR assumes that the changes to the Upgrade&Launch prompt screen have already been made, because it assumes that launching and purchasing at the same time is actually possible.

I was thinking, since we're making changes to the Upgrade&Launch prompt screen, that we could add a new intent. Say a `'plugins_and_launch'` intent. That way we could only show the "launched" message if that's something that was supposed to happen.

**Comment by adamziel** [comment]
@p-jackson is completely right here

**Comment by adamziel** [comment]
@p-jackson we also need the thank you page to know which plugin it should redirect back to. This is getting pretty complex, I think we either need to refactor the intent system to accept arbitrary objects, or somehow leverage redirectTo param

**Comment by adamziel** [comment]
I went down the query string path and this blew up quite a bit. I will split it into some smaller PRs that are going to be easier to reason about

**Comment by adamziel** [comment]
A bunch of follow-up PRs:

* https://github.com/Automattic/wp-calypso/pull/38199
* https://github.com/Automattic/wp-calypso/pull/38201
* https://github.com/Automattic/wp-calypso/pull/38203

This approach removes the need for `upgradeIntent` reducer and I'll remove it in a follow-up PR once all of the above are merged

**Comment by jancavan** [comment]
> It’s inconsistent for sure, but those examples you show seem to be wrong. Here’s the documentation:

> https://github.com/Automattic/wp-calypso/blob/83cefb18976d90ddee3ca9518c7cb375b0ff1a14/packages/calypso-ui/src/button/README.md

@shaunandrews Ah, thanks for that!

I also submitted an issue so the rest of the buttons can get cleaned up: https://github.com/Automattic/wp-calypso/issues/38231

@p-jackson @adamziel Can we please make sure to use sentence-case for the buttons? I've updated the mockups as well. Thanks.

**Comment by jancavan** [comment]
> I expected when clicking "Continue Installing Plugin" to go back to the Yoast SEO plugin page. Not the list of all plugins at /plugins where I would have to find that specific plugin again.

Yes, that should be how it works.

I updated the Figma that's linked from this P2 post to reflect this: paObgF-Mn-p2

> This will always say the site has been launched, even if the user already launched their site earlier.

@adamziel Can you please clarify this? Not sure why this would be the case. https://github.com/Automattic/wp-calypso/pull/38139#issuecomment-561280350

**Pull request closed without merging**
