### PR TITLE
Illustrations: Replace "Empty Results" drake with new illustration

### PR DESCRIPTION
**Pull request by drw158**
Wip 

The current drake illustration is 400px wide, whereas the new illustration did not have dimensions set. In order to keep the same size as the old drake, I'll added width and height declarations.

To test, use a test site with no followers. Go to People > Email Followers

Before|After
---|---
screen shot 2017-05-17 at 4 38 50 pm|screen shot 2017-05-18 at 3 40 39 pm

### CODE REVIEW

**Comment by drw158** [comment]
@folletto @kjellr 

Looks like We'll need to edit the svg to get rid of some white shapes (plants), and also darken the background elements since this is overlaid on the gray background. Should I also get rid of the white shape in the backpack?

**Comment by kjellr** [comment]
I think th backpack can stay white, but everything else sounds perfect. Thanks!

**Comment by drw158** [comment]
Ok, background elements darkened, white shapes removed.

Ran the file with `svgo --pretty`

**Comment by folletto** [comment]
FWIW I want to keep a new-illustration-style Drake on the Theme Empty Results page only, as it was originally the idea before it spread everywhere. Likely a change after this goes in tho. ;)

**Comment by folletto** [comment]
screen shot 2017-05-19 at 12 40 19

Tested, work well 👍

**Comment by drw158** [comment]
Oh yea, hmm. We should also rename these files and folders.

**Comment by drw158** [comment]
@folletto do you think we need title on any of these images?

**Comment by folletto** [comment]
It's a good questions... these are far more "illustrations" than "icons", but I can't imagine any use that isn't either decorative or part of another message already on the page. So probably... no?

**Comment by roundhill** [comment]
@drw158 I checked in IE 11 for you 😄 

screen shot 2017-05-19 at 3 38 17 pm

**Comment by kjellr** [comment]
> Oh yea, hmm. We should also rename these files and folders.

I've been transitioning new illustrations into this folder so we avoid using the drake name when there's no drake present:

`wp-calypso/tree/master/public/images/illustrations`

Other than that, this looks good to me!

**Comment by drw158** [comment]
Sorry for the mangled PR everyone, this branch has been moved to #14296

**Pull request closed without merging**
