### PR TITLE
Add translations for WP Blaze Campaign Goals feature

### PR DESCRIPTION
**Pull request by iamhalldor**
Related to #

## Proposed Changes

* New translations. Generated the file through the DSP

Screenshot 2024-06-04 at 11 12 07 PM

Screenshot 2024-06-04 at 11 12 10 PM

Screenshot 2024-06-05 at 3 25 40 PM

Screenshot 2024-06-05 at 3 27 08 PM

Screenshot 2024-06-05 at 3 25 49 PM

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Comment by halldorbjarni** [comment]
Adding @jjolmo @j6ll for reviewing since they've gone through this process before (old [PR](https://github.com/Automattic/wp-calypso/pull/82772). 

Btw, I didn't add all of these strings. I think maybe we haven't done a translation upgrade in a while. Let me know  if I need to add another reviewer from a specific group! And the string freeze label should be all I need to kickstart the translation process? And then I wait till that's done before merging?

**Comment by j6ll** [comment]
Hey @halldorbjarni, yes probably some got missed.  And now you added the string freeze, it should start happening in the background 🪄 .  You will get pinged in slack when they're finished 👍

**Review by j6ll — APPROVED** [review]

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/14113762

Some locales (Hebrew, Japanese) have been temporarily machine-translated due to translator availability. All other translations are usually ready within a few days. Untranslated and machine-translated strings will be sent for translation next Monday and are expected to be completed by the following Friday.

Thank you @halldorbjarni for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/14113762).

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/14113762).

**Pull request merged**
