### PR TITLE
Refresh Reader's UI

### PR DESCRIPTION
**Pull request by crisbusquets**
Related to: Update the Reader UI based on @osullivanchris's design (Slack thread: p1701969903193519-slack-C03NLNTPZ2T). We've adjusted part of the UI so it looks more modern and aligned with that proposal.

cc/ @davemart-in 

## Proposed Changes
* Update font-family from Serif to Sans
* Update heading text wrapper
* Update background color to white
* Update the "more content" gradient to match background
* Adjust padding and margin as needed

## Testing Instructions

* Visit Reader: Recent, Discover and Single Post View (both desktop and mobile) and ensure that it's rendering as expected

| Before | After |
| - | - |
|reader-before| reader-after|
|post-detail-before|post-detail-after|
|mobile-reader-before|mobile-reader-after|

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Review by eoigal — APPROVED** [review]
Wfm! One thing I noticed is the tags don't have any distinguishing styles - not sure if this is necessary but thought worth pointing out.

**Comment by davemart-in** [comment]
Noticed one minor thing that needs to be updated under lists:

CleanShot 2024-04-18 at 07 40 37@2x

Other than that minor thing, this looks good!

**Comment by crisbusquets** [comment]
> Noticed one minor thing that needs to be updated under lists:
> 
> CleanShot 2024-04-18 at 07 40 37@2x
> 
> Other than that minor thing, this looks good!

Fixed it here https://github.com/Automattic/wp-calypso/pull/89635/commits/700dda30404af7ae50758d62d5dea2fc0f5ccbb2, @davemart-in

**Comment by pkuliga** [comment]
Noticed a similar issue on `/tags`:

Screenshot 2024-04-22 at 11 34 50

**Comment by crisbusquets** [comment]
> Noticed a similar issue on `/tags`:
> 
> Screenshot 2024-04-22 at 11 34 50

Fixed here https://github.com/Automattic/wp-calypso/pull/89635/commits/4353751cd26a1cfca1ad14639088969e45acb311 @pkuliga

**Review by pkuliga — APPROVED** [review]
Looks good, thanks for the fixes!

**Review by davemart-in — APPROVED** [review]
Looks good to go!

**Pull request merged**
