### PR TITLE
Update QS upsell duration on purchases page

### PR DESCRIPTION
**Pull request by claudiucelfilip**
#### Changes proposed in this Pull Request

More info: p7DVsv-9JV-p2#comment-32376

This changes the duration of the purchasable QS upsell banner on /me/purchased.

9aofi9

#### Testing instructions

* Create a new site (lower than eCommerce), or use a site without any purchased QS sessions
* Go to /me/purchases
* QS upsell banner should read: 

Screenshot on 2020-11-04 at 11-26-29

##### eCommerce (regression test)
Used a variable instead of hardcoded 30 for the included QS session banner.
* Create a new site (eCommerce), or use a site with an included QS session
* Go to /me/purchases
* QS upsell banner should be unchanged:

Screenshot on 2020-11-04 at 11-54-26

### CODE REVIEW

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/5114718

Thank you @claudiucelfilip for including a screenshot in the description! This is really helpful for our translators.

**Review by sirbrillig — APPROVED** [review]
From a Shilling standpoint, this looks fine to me.

**Review by travisw — APPROVED** [review]
This looks good to me!

The new strings are even [translated already](https://translate.wordpress.com/deliverables/overview/5114718/).

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/5114718).

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/5114718).

**Pull request merged**
