### PR TITLE
Try restricting what we transpile to the last couple chromes.

### PR DESCRIPTION
**Pull request by blowery**
Only doing this to see if there's a significant size difference.

### CODE REVIEW

**Comment by blowery** [comment]
Interesting. Pretty massive chunk movement: http://iscalypsofastyet.com/branch?branch=try/split-builds-by-ua

vendors~build drops by 2k
build drop by 14k
reader up 2K 
...

**Comment by blowery** [comment]
Poking at the bundle analyzer, I was surprised that the core-js Promise and Map where still being pulled into vendors~build. Turns out this is coming from `wpcom`, which is built using babel and includes the babel-6 runtime itself...

**Comment by dmsnell** [comment]
> Turns out this is coming from wpcom, which is built using babel and includes the babel-6 runtime itself...

Should we try and internalize/transpile wpcom.js the way we do notifications-panel? I don't think it's code is incompatible with ours

**Comment by blowery** [comment]
> Should we try and internalize/transpile wpcom.js the way we do notifications-panel?

I'd rather not, as it makes us a special consumer and changes the expectation of what the library is. I think ideally we redo wpcom.js to explicitly state that clients must polyfill Promise / Set / Map / whatever if they want things to work and publish is as es5 code. It's the same road that React is taking.

**Comment by dmsnell** [comment]
> I think ideally we redo wpcom.js to explicitly state that clients must polyfill Promise / Set / Map / whatever if they want things to work and publish is as es5 code.

Hm. I saw Babel in use for tests but I didn't see any mechanism which loads it for the build. Maybe I'm overlooking something in the code itself? I checked the `Makefile`, `webpack.config.js`, and `package.json` files…

**Comment by blowery** [comment]
@dmsnell that is curious! It looks like the magic is done by `n8-make`:
https://github.com/Automattic/wpcom.js/blob/master/Makefile#L6
https://github.com/TooTallNate/n8-make#extending-the-makefile
https://github.com/TooTallNate/n8-make/blob/master/n8-make-js#L8

**Comment by dmsnell** [comment]
> magic is done by n8-make

ha! I missed that

**Comment by jsnajdr** [comment]
Nice article about the future of transpiling your dependencies: https://babeljs.io/blog/2018/06/26/on-consuming-and-publishing-es2015+-packages

The article mentions a nice trick how to publish two bundles at once and let the browser choose the one it's capable of executing: two `<script>` tags, one `<script type="module">` and one `<script nomodule>`.

**Comment by blowery** [comment]
Yeah, once #26531 lands we can revist this.

**Comment by dmsnell** [comment]
> Yeah, once #26531 lands we can revist this.

Also @blowery - I forgot about this issue - just this week we were discussing the possibility of moving `wpcom.js` into Calypso's source tree itself. I think that if we do that and use the SDK to build the published `npm` version we should be able to reduce our bundle size and preserve the external behaviors from that package.

**Comment by sirreal** [comment]
#26531 landed. Also see #26624

**Comment by blowery** [comment]
Closing in favor of https://github.com/Automattic/wp-calypso/pull/30420

**Pull request closed without merging**
