### PR TITLE
Performance Profiler: Add screenshot & timeline on report

### PR DESCRIPTION
**Pull request by gavande1**
Related to https://github.com/Automattic/dotcom-forge/issues/8560 and https://github.com/Automattic/dotcom-forge/issues/8691

## Proposed Changes

* add the website screenshot on the top of the page
* add a timeline of screenshots as the page loads below the CWV metrics

## Testing Instructions

* Go to `/speed-test-tool?url=example.com`
* Check that the website thumbnail is shown according to Figma
* Check that the screenshot timeline is show according to Figma
* Note that we only receive a limited number of screenshots from the backend, so we won't be able to render screenshots more granularly

| Tab | Preview |
|--------|--------|
| Desktop | CleanShot 2024-08-15 at 16 49 15@2x |
| Mobile | CleanShot 2024-08-15 at 16 49 08@2x |

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Comment by gcsecsey** [comment]
I fixed the build and updated the styling, now this should be ready for review. I'll update the description with testing steps and screenshots soon.

**Review by WBerredo — APPROVED** [review]
LGTM!

Deploying!

**Review by gavande1 — COMMENTED** [review]
I have tested it and works really great. 👍

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/16488248

Some locales (Hebrew, Japanese) have been temporarily machine-translated due to translator availability. All other translations are usually ready within a few days. Untranslated and machine-translated strings will be sent for translation next Monday and are expected to be completed by the following Friday.

Thank you @gavande1 for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/16488248).

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/16488248).

**Pull request merged**
