### PR TITLE
Jetpack Cloud: Allow user to manually re-run a scan after threats are found

### PR DESCRIPTION
**Pull request by mattgawarecki**
#### Changes proposed in this Pull Request

* Add copy and a button to the bottom of the "threats found" page to allow the user to run a scan manually.
* Add copy to unfixable threat descriptions to inform the user they can run a manual scan after resolving the threat manually.

Fixes `1151678672052943-as-1175836339721209`.

##### Implementation notes

Thinking out loud: would it make sense to move `dispatchScanRun` to a constant in file scope, since we're using it in two places now? If I recall, `dispatch` is guaranteed to be constant, but I'm not as certain about the dependency on `site.ID`.

#### Testing instructions

* **Prerequisite:** have a site with Scan enabled and no pre-existing threats.
* **Note**: check styling in both mobile and desktop layouts.
* Create a threat that is unfixable (e.g., add the EICAR string to a plugin).
* Click **Scan now** and wait for the results.
* Verify that you see "threats found" with the following copy below the threat listings
  * > If you have manually fixed any of the threats listed above, you can *run a manual scan now* or wait for Jetpack to scan your site later today.
* Verify that "*run a manual scan now*" displays with link styling and appears clickable.
* Expand the details for your unfixable threat and verify that you see the following copy under "How will we fix it?":
  * > Jetpack Scan cannot automatically fix this threat. You can fix it manually and re-run scan afterwards, or *contact us* for help.
* Manually resolve your unfixable threat.
* Click "*run a manual scan now*" below the threat listing to start a new scan.
* Verify the scan runs and comes back with no threats found.

##### Threats found footer text (below threat listings)

Screen Shot 2020-05-14 at 09 27 10

Screen Shot 2020-05-14 at 09 28 22

##### Unfixable threat text ("How will we fix it?")

Screen Shot 2020-05-14 at 09 27 43

Screen Shot 2020-05-14 at 09 28 35

### CODE REVIEW

**Comment by mattgawarecki** [comment]
My gut is saying we can hide this new copy, since the "threats found + errors" copy addresses the ability to scan manually on its own.

**Comment by keoshi** [comment]
Yep, I agree with Matt. The new copy was just a way to get the manual scanning link in.

**Comment by rcanepa** [comment]
I confirm that the new copy doesn't show up when there are threats an and error. 👍

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/3589798

Thank you @mattgawarecki for including a screenshot in the description! This is really helpful for our translators.

**Pull request merged**
