### PR TITLE
Documentation: Add rationale for FP patterns to JS coding guidelines

### PR DESCRIPTION
**Pull request by mcsf**

### CODE REVIEW

**Comment by nb** [comment]
While I like the rationale and I agree wholeheartedly with it, it would be great if it was both shorter and used simpler language. I have a feeling mostly those already convinced will spend the time to read all of it and will relate to contracts, sophistication, and finesse of expression.

**Comment by mcsf** [comment]
> I have a feeling mostly those already convinced will spend the time to read all of it and will relate to contracts, sophistication, and finesse of expression.

I laughed. :) But you're very right. I'll prioritize some of the more practical pieces, abridge the more esoteric ones.

**Comment by mcsf** [comment]
@nb, I shuffled things around a little, removed a poorly chosen _sophisticated_ in the beginning, and thought about:

> will spend the time to read all of it and will relate to contracts

It felt important to keep the bit about the contract, but merely enumerating some implications of `map` / `filter` and not going on about the idea of contracts in code (though there's a hyperlink in there for the curious ones).

> sophistication, and finesse of expression.

So I moved that sentence to the bottom, which at least means we don't deter the reader from reaching the useful bits. I was thinking of how to reword it. I can simply remove it, but I'd still like to appeal to that ideal of expression. Perhaps a wording centered around us all aiming to be _effective communicators_?

**Comment by marekhrabe** [comment]
I liked the longer version too, but @nb had very valid point that I was already _a fan_. Good job with simplification and the idea in general!

**Pull request merged**
