### PR TITLE
Persist scroll position in the Help Center

### PR DESCRIPTION
**Pull request by alshakero**
Fixes https://github.com/Automattic/dotcom-forge/issues/10075

## Proposed Changes

Persist the scroll position of the article element in memory so minimized the Help Center doesn't destory reading progress.

## Why are these changes being made?
To make reading articles more continuous.

## Testing Instructions

1. Open an article in the HC.
2. Scroll down.
3. Minimize the HC.
4. Maximize it.
5. The article should stay in place.
---
1. Open an article.
2. Scroll down.
3. Go back.
4. Go to another article. 
5. Should be at the top.
---
1. Open an article.
2. Scroll down.
3. Close the Help Center. 
4. Reopen it.
5. Go to an article.
6. Should be at the top.
---
1. Open the article "Getting Started on WordPress.com".
2. Scroll down to "Learn more about the dashboard".
3. Click it.
4. Scroll down in the new article.
3. Minimize the HC.
4. Maximize it.
5. The article should stay in place.
6. Click Back to go back to the original article.
7. Scroll should be preserved.

## Demo

https://github.com/user-attachments/assets/14cb22a2-64ea-4d09-8005-95a2241ead21

### CODE REVIEW

**Review by escapemanuele — COMMENTED** [review]
This doesn't happen for me @alshakero, when I reopen the Help Center and reopen the article, it is where I left it (tested in /home) :)

image

**Comment by heavyweight** [comment]
> This doesn't happen for me @alshakero, when I reopen the Help Center and reopen the article, it is where I left it (tested in /home) :)
> 
> image

Same happens for me but I think that should be the correct behaviour

**Comment by heavyweight** [comment]
When we scroll and minimize, the click on the minimized title does not behave the same.
Maybe we need to fix this one. Should be simple
https://github.com/user-attachments/assets/d355c2c3-1692-44a5-88af-221387f4d896

**Comment by heavyweight** [comment]
The scroll position can get mixed up between articles

https://github.com/user-attachments/assets/4dd63006-a94e-49b2-b71a-266d1a463005

**Comment by escapemanuele** [comment]
Is this ok to be tested again @heavyweight ?

**Comment by heavyweight** [comment]
Yes thanks
Working to fix the e2e which I muted on teamcity but won't change things here

**Review by escapemanuele — APPROVED** [review]
Let's go!

**Pull request merged**
