### PR TITLE
Docs: Coding guidelines: CSS: Typo fix

### PR DESCRIPTION
**Pull request by gurdiga**
Just a typo fix. :o)

There is one other thing that came to my mind while reading this: the [“Media Queries” section](https://github.com/Automattic/wp-calypso/blob/master/docs/coding-guidelines/css.md#media-queries) mentions specific breakpoints. I checked [the source code](https://github.com/Automattic/wp-calypso/blob/53bde8c3f9c4668e62dbd2c670aaacc2bd820427/assets/stylesheets/shared/mixins/_breakpoints.scss)  and found that there is actually one more added: `1040px`.

There is one more similar little issue close to the end of that section where the accepted values for `breakpoint()` mixin are listed.

I was wondering if it’d be a good idea to remove the specific values altogether, so that they don’t have to be kept in sync on one hand, and, on the other hand, if anyone is interested they’d go straight to the source and find the current values.

What do you think? 8-)

### CODE REVIEW

**Comment by lancewillett** [comment]
Thanks for the typo fix — I agree it's probably a good idea to remove specific values there since they could be hard to maintain accurately in the future.

**Comment by gurdiga** [comment]
@lancewillett Thank you for the answer, I will add one more commit to eliminate the specifics. 8-)

**Comment by lancewillett** [comment]
CC @mtias for a 2nd opinion on removing the breakpoint values.

**Comment by mtias** [comment]
Sounds good. Perhaps we could link to: https://github.com/Automattic/wp-calypso/blob/master/assets/stylesheets/shared/mixins/_breakpoints.scss#L6

It's not clear from the doc that we support ranges like 480px-660px or greater/smaller than signs.

**Comment by gurdiga** [comment]
@lancewillett @mtias Thank you for checking this out!

I have replaced the specific breakpoints with a link to ../../assets/stylesheets/shared/mixins/_breakpoints.scss. 8-)

**Comment by lancewillett** [comment]
Thanks @gurdiga.

**Pull request merged**
