### PR TITLE
Try/isomorphic routing

### PR DESCRIPTION
**Pull request by ockham**
**Do not merge.**

The goal of this PR is isomorphic routing and rendering, i.e. having a single middleware for element tree creation for a given route that is used both client- and server-side. That element tree is then rendered by a section-agnostic rendering middleware that is specific to either the server, or the client.

The first section that's going to be isomorphicized is `themes`. We'll need to do the following:

* #3516: Have `my-sites/themes#details` create a full-fledged `Layout` component tree in `context.layout` (instead of just a primary element tree inside `context.primary`), and render that to `#wpcom` in `client/controller#renderElements` (possibly rename). (It's actually sufficient to have a full-fledged layout tree at the end of the `/themes/:slug/:section?/:site_id?` route, so we could have layout creation in a separate middleware, as in `'/themes/:slug/:section?/:site_id?': [ details, detailsLayout ]`)
 * Modify `LayoutLoggedOutDesign` accordingly.
 * Drop the `secondary` unmounting hack.
* #3562: In the `/themes` route in `server/pages`, use `my-sites/themes` to create a theme sheet element tree in `context.layout`, and `renderToString()` that.
 * Adapt `express`'s `req` context to be able to use it with middleware that otherwise operates on `page`'s `context`.
 * Add a `package.json` that sets different entry points on the server and in the browser (not everything required by `my-sites/themes/index.js` is SSR-ready yet, so we need a pruned version for the server).

To make this fully generic, we then need to:
* #4086: Make the above SSR related stuff section-agnostic. Only then will we need the loader (1b86bfe8d1fbc8ec2e0f4cc3ed528a9973837c29).
 * In `server/pages`, filter sections with `routing: 'isomorphic'` and loop over them.

Might make sense to do that in two passes (i.e. PRs, 1 themes-specific, 2 section-agnostic). The current state of this PR was starting from the section-agnostic side, but I think the other way round makes more sense. There might still be some stuff in here that we can re-use even if we start with themes-specific.

### CODE REVIEW

**Comment by ockham** [comment]
As discussed and explored today, getting dynamic [`require`](https://github.com/Automattic/wp-calypso/pull/3302/files#diff-336276ec8a6d8fa6e6ecd99de5a7bab3R81)s to work with Webpack is utterly non-trivial.

We might try using a bundler to work around that issue, but in order to not block us too much on that, I'd suggest 

* hard-coding `client/my-sites/themes` on that line for now, and
* rebasing this branch on master (if you're first to attempt to do this, be sure to `git pull --rebase` first, since I've already slimmed down its history a bit to make rebasing easier).

cc @ehg @mcsf @seear

**Comment by ehg** [comment]
Added a loader that will allow requiring of isomorphic modules here: 196b0a4

**Comment by mcsf** [comment]
I rebased and pushed some commits, notably a157074, which I really hope makes sense and takes us forward, though it's honestly too late to be sure of anything. :zzz:

**Comment by mcsf** [comment]
Oh, and FWIW the concept for `applyMiddlewares` (in a157074) was tested here:
http://codepen.io/mcsf/pen/Ywmajp?editors=0011

**Comment by ockham** [comment]
Amended the description to note that we won't need the loader (1b86bfe8d1fbc8ec2e0f4cc3ed528a9973837c29) until we really make things section-agnostic -- as long as we hard-wire it only to `themes`, webpack won't have any trouble finding that (no dynamic `require`). One more reason to split the roadmap into multiple PRs and go themes-specific first.

**Comment by ockham** [comment]
Closing, now that all the last remaining pieces from this PR have been carried over to #4086.

**Pull request closed without merging**
