### PR TITLE
Gutenberg: enable Calypsoify opt in in staging and production

### PR DESCRIPTION
**Pull request by vindl**
#### Changes proposed in this Pull Request

Launches Calypsoifed Gutenberg to 50% of new WordPress.com users (Simple sites only).
See https://github.com/Automattic/wp-calypso/pull/28499 for details.

#### Testing instructions

1. Verify that opt-in flows and redirects work properly in staging.

### CODE REVIEW

**Comment by mmtr** [comment]
Are not we disabling finally `gutenberg/opt-in` in horizon?

**Comment by vindl** [comment]
> Are not we disabling finally gutenberg/opt-in in horizon?

That was kind of the point of @Copons latest PR (we can preserve it too).

**Comment by mmtr** [comment]
> That was kind of the point of @Copons latest PR (we can preserve it too).

Yeah, but assuming that the `gutenberg/opt-in` flag would be disabled in horizon environments, right?

screen shot 2018-11-13 at 17 56 50

**Comment by Copons** [comment]
Woopsie my fault on not updating the tests on the other PR.

> That was kind of the point of @Copons latest PR (we can preserve it too).

Well not really 😄 
Initially my intention was to disable opt-in on Horizon because I was under the impression that there was no way to opt-out. It is not the case: everybody can always opt-out from wp-admin.

For this reason I've decided to remove the flag change right before pushing the PR, and I forgot to update the test instructions.

**Pull request merged**
