### PR TITLE
Use API endpoints

### PR DESCRIPTION
**Pull request by unDemian**
#### Changes proposed in this Pull Request

- **The counts represent unseen posts since the user subscribed to the feed or this feature's "release date" (07/13/2020) whichever is newer.**
- **For now a post is marked as seen when visited in the Reader or if a "Mark as seen" button is used**
- **Seen status should be persisted**

If there is unseen content in your reader the dot should be visible, currently it will update with new status only on page reload.

Markup on 2020-06-12 at 10:01:36 PM

The  Reader sections should present **unseen counts** for sections and particular blogs. 

Markup on 2020-06-12 at 10:01:52 PM

Sections will have "Mark all as seen" buttons, active only if there is unseen content in the feed.

Markup on 2020-06-12 at 10:02:31 PM

Feeds will have "Mark all as seen" buttons, active only if there is unseen content in the feed.

Markup on 2020-06-12 at 10:03:24 PM

Posts and combined posts will have "Mark as seen/unseen" buttons

Markup on 2020-06-12 at 10:03:08 PM
Markup on 2020-06-12 at 10:02:46 PM

When visiting a post in the Reader there will be a seen icon

Markup on 2020-06-12 at 10:04:15 PM

#### Testing instructions
- Apply D46339-code
- Unseen dot should be visible in main bar
- Unseen counts should be visible in Reader
- Mark as seen/unseen single/combined feed items (counts should be updated)
- Mark as seen entire feed (counts should be updated)
- Mark as seen entire sections like Following/All (counts should be updated)
- Visit a full post in Reader (should mark it as seen)

### CODE REVIEW

**Comment by unDemian** [comment]
Sorry for the pings.

**Comment by lamosty** [comment]
Great work, tests out! 

I'll skim through the code.

**Review by lamosty — APPROVED** [review]
LGTM 🚢

**Review by wp-desktop — DISMISSED** [review]
WordPress Desktop CI Failure for job "wp-desktop-source".

@unDemian please inspect this job's build steps for breaking changes at [this link](https://circleci.com/gh/Automattic/wp-calypso/817465). For temporal failures, you may try to "Rerun Workflow from Failed".

Please also ensure this branch is rebased off latest Calypso.

**Pull request merged**
