### PR TITLE
Add payment fees to plans grid

### PR DESCRIPTION
**Pull request by simison**
Screenshot 2023-06-14 at 11 53 03

Screenshot 2023-06-14 at 11 53 29

## Proposed Changes

* Add commission fees to plans grid for each plan, including free
* Add commission fees to comparison grid

## Testing Instructions

1. Check out this branch and run `yarn` and `yarn start` if needed. 
2. Navigate to the 2023 pricing grid in onboarding http://calypso.localhost:3000/start/plans
3. Verify that payment fees info has been added to the features grid and the comparison grid
4. Navigate to the 2023 pricing grid in the plans page http://calypso.localhost:3000/plans/{SITE_SLUG}
5. Repeat step 3

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

**Comment by simison** [comment]
Currently PR looks like this:


Visible in grid on all plans except "free":

Screenshot 2023-06-08 at 19 12 19

Ideally line are more horizontally at similar place so that it's quick to compare at glance, same as storage. So perhaps good to move under storage? Current version might be fine 1st iteration.

Screenshot 2023-06-08 at 19 12 59

Copy is kinda lengthy for a thing to repeat, so finding something shorter would be ideal. Current one might be fine 1st iteration again.

Free plan is missing 10% fee line, needs adding.

The long comparison grid needs different label and numbers in the grid itself, like storage under it:

Screenshot 2023-06-08 at 19 13 23

_Getting there! :-)_

**Comment by simison** [comment]
Small update:

- Added to Free column
- Shortened label by removing "Stripe", but not sure about this. Figured nobody knows what Stripe is before we actually ask to connect it, and it's the same stripe fee across all plans anyway and point here is to compare.
- Added tooltip

Screenshot 2023-06-09 at 00 25 23

I think the challenging part will be the comparison grid, so might be worth hiding the feature there for 1st iteration:

Screenshot 2023-06-09 at 00 29 00

Storage row is pretty custom code, and didn't seem re-usable for this purpose as-is.

**Comment by southp** [comment]
> I think the challenging part will be the comparison grid, so might be worth hiding the feature there for 1st iteration:

It's a challenge indeed. However, my take is that the plans comparison grid is meant to be a place where all the features are listed and compared in detail, so I wouldn't recommend to hide it.

If we leave out the % out, it's actually the same feature: transaction fee for payments + Stripe fee. What if we list the actual % portion of the fee in the cells we show the checkmarks? 

image

**Comment by simison** [comment]
> If we leave out the % out, it's actually the same feature: transaction fee for payments + Stripe fee. What if we list the actual % portion of the fee in the cells we show the checkmarks?

Yes, sorry not clarifying but that is the goal indeed. Exactly like Storage row is implemented. If we'd leave it out now it's just for short time until we figure how to implement it.

**Comment by chriskmnds** [comment]
> The long comparison grid needs different label and numbers in the grid itself, like storage under it:

Yeah, it won't be easy doing it like storage. I tried but gave up on it. The code is not reusable by any means. 

Thinking whether we can have a canonical slug instead (`FEATURE_PAYMENT_TRANSACTION_FEES`) and add to the featureGroupsMap, might make it easier. Maybe we add a `getShortenedTitle` to the actual features (with just the commission %s) and use those. haven't experimented with this yet, but can take a stab later if u don't

^ and probably also not easy 😆

**Comment by lucasmendes-design** [comment]
Hi folks, what I suggested in this [issue here](https://github.com/Automattic/martech/issues/1744#issuecomment-1582763816) was the copy below:

**Feature name in the comparison grid:** Transaction fees for payments. 
**Tooltip:** Account for WordPress transaction fees. Additional charges apply for payments to your Stripe account.
**In the cell:** X% WordPress fees + Stripe fees. 

This way, we can reduce the copy in the comparison grid.

**Comment by lucasmendes-design** [comment]
I think we can hide the stripe fees in the plans grid and show the tooltip proposed above. In the comparison grid, we can have what I described ( X% WordPress fees + Stripe fees).

**Comment by lucasmendes-design** [comment]
> Ideally line are more horizontally at similar place so that it's quick to compare at glance, same as storage. So perhaps good to move under storage? Current version might be fine 1st iteration.

I understand your point but the current plans grid doesn't allow that pretty well. I'll put more thought into it. Meanwhile, let's keep this version as it is for now and we can think of different ways of adding the fees to the plans grid.

**Comment by simison** [comment]
@lucasmendes-design yep agreed, I think it's fine as now. People who are interested in that info will find it in each plan. It's also helpful to have it last item in the list, it's easier to spot it across plans.

**Comment by chriskmnds** [comment]
@lucasmendes-design can you check with the last commit? it should match your spec above. code-wise different story :D

~here's full page:~ (nah removed. too long. dunno how to shrink with link like Mikael did 😆 )

**Comment by lucasmendes-design** [comment]
Thanks @chriskmnds. It's all good to me. Only one detail here:

I think we can use the same tooltip for both the plans grid and the plans comparison grid. So, users know that there are additional fees related to Stripe. I prefer to have the "Account for Wordpress ..." only. WDYT? 

image
image

**Comment by lucasmendes-design** [comment]
Not related to this PR but the plans comparison grid is not rendering correctly here. 

image

**Comment by jeyip** [comment]
> Not related to this PR but the plans comparison grid is not rendering correctly here.

Aneesh and I have seen this and are currently investigating, but at the moment, we're unable to reproduce the problem consistently https://github.com/Automattic/martech/issues/1824

**Comment by simison** [comment]
@lucasmendes-design latest row:

Screenshot 2023-06-10 at 13 18 17

Note that I moved commissions to "Growth and monetization tools" section:

image

I'll send this already for translation to get things moving but if anyone has adjustments, I'm happy to change anything!

@chriskmnds I'm happy with how code looks now, you?

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/8036549

Thank you @simison for including a screenshot in the description! This is really helpful for our translators.

**Review by chriskmnds — APPROVED** [review]
LGTM. Tested `/start`, `/setup/newsletter`, `/plans`. Also `/plans` with woo site (you get from `/setup/wooexpress`) and haven't noticed regressions. :shipit: when ready

(would be nice to have a single/unified way of grouping features, if it makes sense. but for another time)

**Comment by lucasmendes-design** [comment]
Hi @simison, 

> Credit card fees by apply on top of commission fees. No fixed monthly or annual fees charged. 

Is out there any monthly or annually fees? It's something common to have, and because of that, we're saying that? I didn't understand this part  `No fixed monthly or annual fees charged`. 

Some suggestions:
- Credit card fees are applied in addition to commission fees for payments.

Here is a different approach trying to put more light on the feature. It seems negative the way we're describing it. 
- Facilitate user payments on your site. Credit card fees are applied in addition to commission fees for payments.
- Offer the option for users to make payments. Applying credit card fees on top of commission fees.
- Facilitate seamless user payments. Applying credit card fees on top of commission fees.

WDYT?

**Comment by jeyip** [comment]
Added testing instructions to the PR description for posterity

**Comment by simison** [comment]
> Is out there any monthly or annually fees? It's something common to have, and because of that, we're saying that? I didn't understand this part No fixed monthly or annual fees charged.

I've copied the text from Earn page; it's fair to question it and do something that feels better.

I'll update to _"Credit card fees are applied in addition to commission fees for payments."_ — I do like abbreviating.

> Here is a different approach trying to put more light on the feature. 

The feature is the one above, so should we need to explain it out in the commission fee row?

Screenshot 2023-06-13 at 12 46 34
Screenshot 2023-06-13 at 12 46 37

**Review by edanzer — APPROVED** [review]

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/8036549).

**Pull request merged**
