### PR TITLE
Marketplace: updates installed plugin checkmark.

### PR DESCRIPTION
**Pull request by cpapazoglou**
Relates to p58i-g1B-p2#comment-60617

## Proposed Changes

* makes the checkmark more visible

## Testing Instructions

- Search for jetpack backup
- Inspect the installed icon

|Before | After|
|-------|------|
|CleanShot 2023-12-08 at 16 24 15@2x|CleanShot 2023-12-08 at 16 23 38@2x|

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

**Comment by annezazu** [comment]
Thanks for opening this! In this case, I was noting how strange the checkmark looks. It feels cramped and hard to decipher a checkmark. Perhaps this is the chosen component but I'd expect something more like this (this is a random example):

green-check-mark-icon-tick-symbol-in-green-color-illustration-free-vector

**Review by gavande1 — APPROVED** [review]
I think, choosing another icon is different issue then this PR is trying to do. I think, the current changes are good to resolve existing problem with colour. I don't know what other feels about this. But In my opinion the changes looks good to me.

**Comment by cpapazoglou** [comment]
> Thanks for opening this! In this case, I was noting how strange the checkmark looks. It feels cramped and hard to decipher a checkmark. Perhaps this is the chosen component but I'd expect something more like this (this is a random example):
> 
> green-check-mark-icon-tick-symbol-in-green-color-illustration-free-vector

@jrdnhllr can you consider this for your redesign in p9Jlb4-9Yh-p2#comment-10142 ?

**Comment by annezazu** [comment]
>I think, choosing another icon is different issue then this PR is trying to do. I think, the current changes are good to resolve existing problem with colour. I don't know what other feels about this. But In my opinion the changes looks good to me.

To clarify, I brought this up as feedback and this PR was opened to address it. I commented to clarify what my feedback actually is. You're right - This doesn't address that. Commented in hopes we can eventually do so :)

**Pull request merged**
