### PR TITLE
Reader: Remove old unused icons

### PR DESCRIPTION
**Pull request by tyxla**
#### Proposed Changes

This PR removes a few old Reader icons that became unused and obsolete since #70659.

Blocked by https://github.com/Automattic/wp-calypso/pull/71010.

#### Testing Instructions

Verify the removed icon components are not in use. Usually, it's enough to verify that there are no bundle size changes reported by the bot.

### CODE REVIEW

**Comment by davemart-in** [comment]
Note: some of these icons are used in #71010 which I still plan to update and ship (possibly later today).

**Comment by tyxla** [comment]
Fantastic, I'll punt this and revisit it later. I'm happy to close if you're planning to use all of them in the future.

**Comment by davemart-in** [comment]
Let's keep it open. I'll do another quick audit and comment here once I've shipped my other PR. Thanks!

**Comment by davemart-in** [comment]
Looks like we used all of these icons in #71010. Going to go ahead and close this PR out.

**Comment by tyxla** [comment]
Thanks, Dave!

**Pull request closed without merging**
