### PR TITLE
Framework: Remove react-tap-event-plugin

### PR DESCRIPTION
**Pull request by ockham**
https://github.com/facebook/react/issues/436#issuecomment-241781187 indicates that it's no longer needed.

Consequently, this PR also replaces all occurrences of `onTouchTap` (which is no longer available without the plugin) with `onClick`.

This is straight-forward in almost all cases except for the `Site` block which was already using both for apparently different purposes. Turns out that only one consumer -- `reader/stream/post` was using `onClick`, which was introduced by https://github.com/Automattic/wp-calypso/commit/6973c70177958044039db6ad689040c7d1a776d3. I've removed it and modified the consuming code correspondingly -- hopefully correctly. cc @blowery 

To test: Check that tap works as expected on _mobile Chrome_ and _Safari_ with the following blocks and components (links go to corresponding devdocs pages on calypso.live where available). (Actually, we should probably also check that click still works as before in desktop browsers.)

* [CommentButton](https://calypso.live/devdocs/blocks/comment-button?branch=remove/react-tap-event-plugin)
* [DailyPostButton](https://calypso.live/devdocs/blocks/daily-post-button?branch=remove/react-tap-event-plugin)
* [LikeButton](https://calypso.live/devdocs/blocks/like-button?branch=remove/react-tap-event-plugin)
* [Accordion](https://calypso.live/devdocs/design/accordion?branch=remove/react-tap-event-plugin)
* MobileBackToSidebar
* [Search](https://calypso.live/devdocs/design/search?branch=remove/react-tap-event-plugin)
* [SectionNav](https://calypso.live/devdocs/design/section-nav?branch=remove/react-tap-event-plugin)
* [SegmentedControl](https://calypso.live/devdocs/design/segmented-control?branch=remove/react-tap-event-plugin)
* SidebarNavigation
* [Site and AllSites](https://calypso.live/devdocs/blocks/sites?branch=remove/react-tap-event-plugin)
* MenuName (My Sites > Menus)
* DailyPost (Reader)
* ListGap (Reader)
* UpdateNotice (Reader)

cc @mtias because of affected generic components

### CODE REVIEW

**Comment by gwwar** [comment]
Tested this on my iPad, looks like tap events work on both. Could you rebase + fixup the test? I can take another 👀

**Comment by ockham** [comment]
17 more occurrences of `onTouchTap`. Some more work ahead here 😄

**Comment by ockham** [comment]
Okay, should be ready for another look. Has indeed grown a bit in size 😕

**Comment by gwwar** [comment]
I can test next week when I get back from the Stark meetup. Maybe some other folks could help test in the meantime? cc @hoverduck

**Comment by hoverduck** [comment]
I checked it out on Android Chrome and iOS Safari (iPad only) and didn't see any problems.  I tried to hit all of the components listed in the original post, but the Reader wasn't loading any entries on https://calypso.live/?branch=remove/react-tap-event-plugin so I wasn't able to verify any of those.

I also ran the e2e test suite against this branch on desktop Chrome at mobile screen width and didn't see any issues.

**Comment by blowery** [comment]
Testing this out.

**Comment by blowery** [comment]
@hoverduck yeah, looks like the comment button is busted. Checking.

**Comment by aduth** [comment]
From https://github.com/facebook/react/issues/436#issuecomment-241781187:

>Since Chrome and Safari have both removed their tap delays for mobile pages

Is this true by default, or does this apply only with [`touch-action: manipulation;`](https://developer.mozilla.org/en-US/docs/Web/CSS/touch-action) styling?

This article seems to indicate that iOS is smart about how it determines when to apply fast tapping (based on whether page is scaled well for mobile viewports), which is pretty neat: https://webkit.org/blog/5610/more-responsive-tapping-on-ios/

**Comment by gwwar** [comment]
Did some more tests and looks pretty good. Let's resolve conflicts and get a few more folks to 👀 for regressions.

**Comment by ockham** [comment]
Rebased, again. This has been cooking for too long, so I'm aiming for a merge tomorrow.

@blowery Reader seems to have diverged the most (b/c Reader Refresh), maybe you could give this a quick spin to see if nothing's broken?

**Pull request merged**
