### PR TITLE
Reader: Following Manage UI nits

### PR DESCRIPTION
**Pull request by jancavan**
- [x] Fix alignment of Follow(ing) buttons:

**Before:**
screenshot 2017-05-08 21 46 56

**After:**
screenshot 2017-05-08 21 47 27

- [x] Fix white popover arrow

**Before:**
screenshot 2017-05-08 21 56 10

**After:**
screenshot 2017-05-08 21 56 51

- [x] Follow(ing) icons alignment
- [x] Limit Site Title, byline, and URL to a single line in Site Results

### CODE REVIEW

**Comment by jancavan** [comment]
**To dos:**

- [ ] Add search term to error message: `Sorry, no sites match _yourquery_.`
- [ ] Add error class to the search field

screenshot-2017-05-09-11 03 03

The following filter needs to display an error message as well just like it does currently:

- [ ] Add search term to error message: `Sorry, no followed sites match _yourquery_.`
- [ ] Add error class to the search field

screenshot-2017-05-09-10 54 39

/cc @samouri

**Comment by samouri** [comment]
> Add search term to error message: Sorry, no sites match _yourquery_.
added in https://github.com/Automattic/wp-calypso/pull/13834

**Comment by fraying** [comment]
@jancavan Is this #13433 possible?

**Comment by fraying** [comment]
@jancavan Also, can the carrot in the popover be aligned with the icon, not the text? Like so?
settingspopover

**Comment by jancavan** [comment]
Fixed https://github.com/Automattic/wp-calypso/issues/13433 in https://github.com/Automattic/wp-calypso/pull/13787/commits/55b654f3e6337cce11b5976d8e24fe02cc2677a4.

> Also, can the carrot in the popover be aligned with the icon, not the text? Like so?

The positioning is being generated dynamically, but @samouri is this possible?

**Comment by samouri** [comment]
> The positioning is being generated dynamically, but @samouri is this possible?

done in https://github.com/Automattic/wp-calypso/pull/13787/commits/3affcf6fbaa6fc94d3f31ddaf5d76dde3894c1a1

**Comment by jancavan** [comment]
Thanks @samouri, that was clever 😄 

> Fixed #13433 in Automattic/wp-calypso@55b654f.

This misaligned those without gravs/blavs. Taking a look at it again.

**Comment by jancavan** [comment]
I don't know why I didn't think of this solution the last time, but https://github.com/Automattic/wp-calypso/issues/13433 is fixed in: https://github.com/Automattic/wp-calypso/pull/13787/commits/e3beee8f32378aa5b8deadcff0ed6fd04258cdc4

screenshot 2017-05-10 12 21 40

**Comment by samouri** [comment]
```
                 _-====-__-======-__-========-_____-============-__
               _(                                                 _)
            OO(              DEPLOY TRAIN                         )_
           0  (_                                                   _)
         o0     (_                                                _)
        o         '=-___-===-_____-========-___________-===-dwb-='
      .o                                _________
     . ______          ______________  |         |      _____
   _()_||__|| ________ |            |  |_________|   __||___||__
  (         | |      | |            | __Y______00_| |_         _|
 /-OO----OO""="OO--OO"="OO--------OO"="OO-------OO"="OO-------OO"=P
#####################################################################

```

**Comment by jancavan** [comment]
@samouri One issue I noticed about the popover is clicking on the word "Settings" displays it, but clicking again doesn't make it go away (unlike the cog). Any way to fix that?

**Comment by samouri** [comment]
seeing some weirdness still at small-medium widths like: 

But that wasn't caused by this PR so 🚢

**Comment by jancavan** [comment]
Thanks @samouri. Happens in wide widths. it’s also tricky to correct it in Devdocs since we wrap it around a `card` width paddings. We don't have those paddings in SoM.

**Pull request merged**
