### PR TITLE
Build: update Node to 6.11.5

### PR DESCRIPTION
**Pull request by gwwar**
This PR updates Calypso to node v6.11.5. This brings us to the [latest of the Boron LTS line](https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V6.md#6.11.5) and contains a [security](https://nodejs.org/en/blog/vulnerability/oct-2017-dos/) fix.

### Local Dev
- Switch to node version 6.11.5 (npm 3.10.10)
- `make distclean`
- `make run`
- No functional changes to Calypso
### Local Docker Image
- Follow image instructions at: PCYsg-5XR-p2 or
- Setup docker locally and add the following host entry:
```
127.0.0.1 wpcalypso.wordpress.com
```
- `npm run build-docker`
- `npm run docker`

### Desktop
- Clone the wp-desktop project
- Follow install instructions
- In the calypso submodule checkout this branch
- Desktop behaves normally

### CODE REVIEW

**Comment by gwwar** [comment]
Tested in local + docker so far. Will land tomorrow since it's a security patch.

**Comment by samouri** [comment]
I tested local, LGTM.
I tried testing `wp-desktop` but I'm not sure what the steps there are. I know there are a bunch of hotfixes in the `release/3.0.0` and i tried `make run` from there and still couldn't get a build working.

I'd still say 🚢 because the risk that this change breaks desktop seems tiny (and even if it does break then better to fix desktop later than delay the release of this).

**Comment by gwwar** [comment]
@samouri Yeah my thoughts too, though we'll want to be more careful on the v8 bump. I tried it on the develop branch, but I don't think fixes from the latest release desktop branch have made it back yet.

**Comment by gwwar** [comment]
Thanks for the review @samouri !

**Pull request merged**
