### PR TITLE
FSE: Add a "frame" around the document in the editor

### PR DESCRIPTION
**Pull request by shaunandrews**
This PR attempt to add some spacing around the editable area of the document.

Before:

Screen Shot 2019-07-16 at 2 11 48 PM

After:

Screen Shot 2019-07-16 at 2 12 37 PM

### CODE REVIEW

**Comment by glendaviesnz** [comment]
I like this concept - I think it will give the user more of a feel for their actual site/page look than border than the lack of framing in the border to border white editor page.

When I switch on the FSE plugin the content is pushed very close to the edges:
page-border
 
Which is probably related to https://github.com/Automattic/wp-calypso/issues/34558. 

Also, as you can see above the handles for moving the blocks hang over the grey border - is this where we want these to sit? (incidentally it fixes https://github.com/Automattic/wp-calypso/issues/34430).

**Comment by noahtallen** [comment]
I really love this! @glendaviesnz I have a PR up which hopefully fixes both of those alignment issues you mentioned. ;)

I was actually thinking of how nice this would be earlier today. Especially when looking at the header and footer, this gives you a really nice distinction between Calypso and your own site content.

Here's what it looks like with the alignment fixes:
Screen Shot 2019-07-16 at 4 26 39 PM

**Comment by noahtallen** [comment]
I think one place this could be improved  is in the template part editor. There's a lot of extra whitespace in this view:
Screen Shot 2019-07-16 at 4 29 57 PM

**Comment by shaunandrews** [comment]
> Actually, I think we shouldn't display the frame when editing a template part.

The designs I've been working on use the document frame for both editing a page, and a template part (Header/Footer). The thinking is that the frame gives us a way to encapsulate the _thing_ you're editing. It helps separate the editors UI (top bar and sidebar) from the content a user is editing. Here's a screenshot showing the frame in action on both a page and a template part:

Document Frame Examples

Notice how the canvas (the white area) shrinks up when editing a part of a site (in this case, the Header).

**Comment by gwwar** [comment]
The space framing the editing space is pretty cool @shaunandrews. I'll defer to folks here, but I do like this. 

Document Frame Examples

If folks had time, any thoughts on some of the chrome changes/notice suggestions there? Some things to point out in the mocks:

* Use of 'x' vs < chevron
Screen Shot 2019-07-17 at 3 07 04 PM
* Button within the top Chrome "Back to new page"
* Use of top notice as a warning.

cc @jasmussen @mtias @karmatosed @melchoyce 

Feel free to ignore the ping if y'all are too busy, but I'd be interested to see if you had thoughts.

**Comment by gwwar** [comment]
What sort of feedback are you looking for @shaunandrews? Overall I think we're pretty favorable to the idea. Should we open a new issue related to your other mocks?

What's in this PR gives us a good idea, but might not be solid enough to land yet. I wanted to note a few corner cases with blocks going off into the extra space/sticky notice behavior.
behavior

**Comment by shaunandrews** [comment]
> Use of 'x' vs < chevron

I haven't made an issue for this yet, I'm waiting to hear more about the decision that went into the chevron before I suggest we switch it to a close ("X") icon.

> Button within the top Chrome "Back to new page"
> Use of top notice as a warning.

I made a propose over on #34728 that covers these two things. Sorry for the confusion.

**Comment by vindl** [comment]
@shaunandrews I've re-tested after the new push and I'm still noticing the issue from https://github.com/Automattic/wp-calypso/pull/34684#pullrequestreview-264891501. If you want we could land this and address that in a follow-up.

**Comment by shaunandrews** [comment]
I think this is a "nice to have," but not a requirement. Lets not let it distract us from the other work at hand.

**Comment by apeatling** [comment]
@shaunandrews Hopefully you don't mind, i'm going to close this one in place of https://github.com/Automattic/wp-calypso/pull/35116 where a bunch of the above is fixed up. I created a new branch from latest master rather than modifying this branch.

**Pull request closed without merging**
