### PR TITLE
Hide recommended themes when query present.

### LINKED ISSUE #38061: Themes:  Hide "more themes" button change if filter is present.
Follow-up to PR #37696 and Issue #37285.

After placing a "Recommended Themes" section at the top of the themes page and hiding the search functionality behind a "Show More" button, we see that it may be desired to hide these changes when a search filter is present.  This will allow HEs and users to share URLs with themes search results, without the results being hidden behind a button and beneath a recommended section.

#### Steps to reproduce
1.  With PR #37696 active.  Visit wordpress.com/themes (or calypso.localhost:3000/themes) while logged in, open the "More Themes" button, and add a search criteria to the search bar.
2.  Reload this URL now with the predefined search criteria.
3.  Notice that the "Recommended Themes" section appears first, and that you must click the "More Themes" button to view the search results you were trying to "share".

#### Thoughts on solving
My first thought to solving this issue is to make it so that if search filters are present, Recommended Themes does not render and the All Themes search section is open.  This would mean that in the normal flow of visiting my-sites/themes section a user would:
* See the Recommended Themes section.
* Scroll down to open "More Themes"
* Apply a filter in the search bar.
* At this point the Recommended Themes section at the top would now disappear.

Does this seem like a reasonable behavior?  @apeatling , @shaunandrews

### PR DESCRIPTION
**Pull request by Addison-Stavlo**
#### Changes proposed in this Pull Request

* alternative solution to PR #38086

#### Testing instructions

* Run this branch with `npm start`
* Navigate to `calypso.localhost:3000/themes` while logged in.
* Open the "More Themes" Section and apply a search critera.
* Verify Recommended Themes section disappears.
* Reload the browser window.
* Verify that the All Themes search section is open and that the page auto scrolls to this area.
* Clear the search criteria rom the input.
* Reload the browser and confirm that Recommended Themes and the "More Themes" button are present.
* Test this same process with a site selected through the my-sites/themes section.

Fixes #38061

### CODE REVIEW

**Comment by apeatling** [comment]
There's a bug with scrolling to the top in this PR. If I select "Feature" in the search options, the page scrolls to the top.

**Comment by apeatling** [comment]
When I reload a filter link, I'm missing the sidebar and things in the masterbar look broken.

**Comment by Addison-Stavlo** [comment]
> When I reload a filter link, I'm missing the sidebar and things in the masterbar look broken.

Yeah I noticed this as well, and I was thinking it may be a quirk of the development environment?  That is, this is reproducible on the master branch as well locally, but if you try it with what is live on WordPress.com it does not seem to have this issue.   So it seems to be isolated to the local development environment.

I also noticed this would happen at "random times" when I first started working off the initial master branch before making any of the back-button changes.  I was not able to pinpoint the cause.  Now after working on it further, it seems that any time the page is reloaded with a filter present and without any search present, it does this very odd behavior.  I wonder if the router or whatever is being used to determine if the sidebar/masterbar should appear has some quirk in local development when the URL contains filter and no search?

**Comment by apeatling** [comment]
Thanks, the scroll top is fixed. I'm noticing other scrolling jankiness related to not consistently seeing the scroll top to the top of the "Adavanced Themes" title. For example after hiting a dropdown filter, it scrolls top, instead of staying at the top of the title:

**Comment by apeatling** [comment]
The same when I hit the X in the theme filter box and reset the filter. It scrolls the search box to the middle of the page, but it should scrolltop to the top of the "Advanced Themes" title.

**Comment by Addison-Stavlo** [comment]
Great catch!  I have updated the scroll-to to be more consistent across these cases.  It should be loading to the same place every time now.  

 Except on reload.  I am having some issues getting the page to load to "Advanced Themes" as opposed to the Top of page when "reloaded" or "back" button'd.  But maybe this is ok behavior since the search filter is still visible at this point?  I can keep trying to find a fix for this but there seem to be some quirks that make the first pass solutions not work.

**Comment by apeatling** [comment]
This looks good to ship. I think we need to revisit how we separate new and old themes in a future iteration (probably via page sections/tabs), but this fixes the filtering for now.

**Comment by Stojdza** [comment]
@Addison-Stavlo This PR caused one of the e2e tests to fail ([example](https://circleci.com/gh/Automattic/wp-e2e-tests-for-branches/36258)). I guess it wasn't caught earlier because `[Status] Needs Review` label wasn't applied? I fixed and pushed change in https://github.com/Automattic/wp-calypso/pull/38128

**Comment by Addison-Stavlo** [comment]
@Stojdza  So sorry for the oversight!

> I guess it wasn't caught earlier because `[Status] Needs Review` label wasn't applied?

My fault, I had a different PR in review where e2e seemed to be passing and opened this as an alternative.  I linked people to it to review as an option but never explicitly added that label here which must be why I missed the e2e failure.

Thanks again for your help with this!  I will be more careful in the future.

**Pull request merged**
