### PR TITLE
A4A: Use Automattic for Agencies logo and text in connection headers

### PR DESCRIPTION
**Pull request by nateweller**
Related to https://github.com/Automattic/automattic-for-agencies-dev/issues/48

## Proposed Changes

* Use the A4A logo in the connection/auth headers when coming from the A4A client plugin.
* Use custom titles when coming from the A4A client plugin.

## Testing Instructions

* While signed in and out, in Calypso, visit the /jetpack/connect/authorize and /log-in/jetpack screens.
  * This link can't be accessed directly, so you will need to start a new site connection from a test site. You can use Jurassic Ninja with the Automattic For Agenceis Client plugin installed via Jetpack Beta, and get a full connection URL by connecting with the A4A plugin.
  * If you've got the A4A plugin running locally in any other form, that will work just as well.
  * Finally, you could also access the URL from any Jetpack connection flow, just manually add the "from=automattic-for-agencies-client" query string value to the URL.

* Validate the connection UI against the screenshots below.

## Pre-merge Checklist

- [x] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [x] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

## Screenshots

| Signed In | Signed Out | Sign Up |
| - | - | - |
| Screenshot 2024-04-16 at 11 58 52 AM | Screenshot 2024-04-16 at 11 53 06 AM | Screenshot 2024-04-16 at 11 52 55 AM |

### CODE REVIEW

**Review by andrii-lysenko — APPROVED** [review]
Looks good and works as described! 👍

**Comment by rcanepa** [comment]
Everything worked as expected except for one UI with the `Jetpack is finishing setup` string on the header.

image

To replicate this, I created a JN site and connected it via the A4A plugin while logged in to WordPress.com. The first UI I was presented with is the one I'm referring to.

Nevertheless, it is a minor issue, so feel free to merge this PR and address it in a follow-up PR.

**Comment by nateweller** [comment]
Addressed the Jetpack subtitle issue with [5640ab5](https://github.com/Automattic/wp-calypso/pull/89557/commits/5640ab5798bd41ad86769e0eb588e1e060c075d8) :+1:

**Comment by andrii-lysenko** [comment]
@rcanepa Thanks for catching this. Missed it somehow.

**Review by rcanepa — APPROVED** [review]
Looks good to me now. 

Thanks for fixing that issue.

**Pull request merged**
