### PR TITLE
TimeSince: Refer to component directly in reader

### PR DESCRIPTION
**Pull request by spen**
### Summary
In #19812 I introduced `TimeSince`, a lift-and-shift from the original `reader/post-time` to a more generalised home in `/components` to allow for use in other areas of Calypso.

This PR looks to remove `reader/post-time` completely and refer to `TimeSince` directly in place of it's usage.

Is this something we'd prefer to do? Or would we rather keep the references as-is and keep `reader/post-time` as a sort of 'proxy' file as @samouri suggests here: https://github.com/Automattic/wp-calypso/pull/19812#discussion_r151202038 ?

### Testing
- Post Comments
  - Go to a post with comments ([calypso.live](http://calypso.localhost:3000/read/blogs/44010780/posts/31489#comments), [local](http://calypso.localhost:3000/read/blogs/44010780/posts/31489#comments))
  - Make sure those comments each show a human readable time/date

- Trackbacks
  - Visit a post that has trackbacks, here's an example: ([calypso.live](read/feeds/27030/posts/1555053762#comments), [local](http://calypso.localhost:3000/read/feeds/27030/posts/1555053762#comments))
  - Make sure those trackbacks show a human readable time/date

- Combined Card Posts
  - Find a 'Combined Card' in reader (bunched posts under one header).
  - Make sure the posts within the combined card show a human readable time/date

- Full Post Header
  - Go to a posts full post view ([calypso.live](http://calypso.localhost:3000/read/blogs/44010780/posts/31489), [local](http://calypso.localhost:3000/read/blogs/44010780/posts/31489))
  - Make sure that the header of the post shows a human readable time/date

- Post Byline
  - Look for the byline of a post
    - screen shot 2017-11-16 at 13 29 33
  - Make sure the byline shows a human readable time/date

### CODE REVIEW

**Comment by bluefuton** [comment]
Ah - I'd forgotten one thing. We do have some styles specifically targeting `.reader__post-time` in Reader. We should check if those are still needed before merging.

**Comment by spen** [comment]
I only see that in use in `reader/stream/post-placeholder.jsx` - Should be a non-issue right?
```
Searching 6582 files for "reader__post-time"

client/reader/_style.scss:
   65  }
   66  
   67: .reader__post-time {
   68  	color: lighten( $gray, 10 );
   69  	font-size: 12px;
   ..
   76  }
   77  
   78: .reader__post-time a {
   79  	color: inherit;
   80  }

client/reader/stream/_style.scss:
  107  		}
  108  
  109: 		.reader__post-time {
  110  			position: relative;
  111  		}

client/reader/stream/post-placeholder.jsx:
   25  							<span className="reader__placeholder-text">Loading Sites</span>
   26  						</h4>
   27: 						<time className="reader__post-time">
   28  							<span className="reader__placeholder-text">10 min</span>
   29  						</time>

4 matches across 3 files
```

**Comment by bluefuton** [comment]
@spen every `<PostTime>` would have had that class (`reader__post-time`) before #19812 merged, and unfortunately `client/reader/_style.scss` is used across Reader, so we'd best double check. I'll add Jan as a reviewer.

**Comment by samouri** [comment]
> Edit: actually, I've just checked in the old reader/post-time and it didn't apply a class at all 🤷‍♂️

opportunity to delete some dead css?

**Comment by bluefuton** [comment]
> opportunity to delete some dead css?

Yep! I'm on it :)

**Comment by spen** [comment]
Awesome - thanks for the quick attention here guyzzz <3

**Comment by bluefuton** [comment]
I've removed those vintage styles, and also fixed the height of the post time in the stream placeholder:

screen shot 2017-11-16 at 15 23 37

**Comment by spen** [comment]
Awesome! Thanks Chris!

**Pull request merged**
