### PR TITLE
People: Wrap label and actions in SectionHeader mobile

### PR DESCRIPTION
**Pull request by jancavan**
#### Changes proposed in this Pull Request

This fixes: https://github.com/Automattic/wp-calypso/issues/33683

#### Testing instructions

1. Find a site with a lot of followers (eg: en.blog)
1. On mobile view, head over to: http://calypso.localhost:3000/people/team/[site]
2. When `SectionHeader` label is long, notice how two columns are still being displayed when it should wrap

**Before:**
Screenshot 2019-06-12 15 27 22

**After:**
Screenshot 2019-06-12 15 27 59

### CODE REVIEW

**Comment by jancavan** [comment]
In: https://github.com/Automattic/wp-calypso/pull/33905/commits/d3d1da9931909f1bdb2e9ec78f653564e12e36ef, I decided to update this at a component level instead.

If label isn't long, there is no change:
Screenshot 2019-06-12 15 44 25

Wrapping only happens if label is long.

**Comment by jeffgolenski** [comment]
@jancavan I'm noticing on small screens (<400) that the white fade is still affecting the legibility of the text. As a quick fix, could you try adding more padding to the right of the text to avoid it?

Screen Shot 2019-06-12 at 4 16 31 PM

**Comment by jancavan** [comment]
If you notice the `SectionNav`'s Search component that has a white bg sticking out, that has been fixed in: https://github.com/Automattic/wp-calypso/pull/33892

**Comment by jancavan** [comment]
> I'm noticing on small screens (<400) that the white fade is still affecting the legibility of the text.

Thanks @jeffgolenski.

In: https://github.com/Automattic/wp-calypso/pull/33905/commits/ffe1b86d01ef09a8e71df41c4deb4ad16be9073e, I removed `long-content-fade`. It doesn't look like its needed since we display the entire label anyway:

**Before:**
Screenshot 2019-06-12 16 38 05

**After:**
Screenshot 2019-06-12 16 38 42

Short labels are still unaffected by this change:
Screenshot 2019-06-12 16 40 05

**Comment by jeffgolenski** [comment]
@jancavan Looks good!

**Pull request merged**
