### PR TITLE
Migrate account recovery styles

### PR DESCRIPTION
**Pull request by blowery**
_Changes proposed in this Pull Request_

* Migrate all styles for account recovery

_Testing instructions_

* Account recvory should look just the same

Part of #27515

### CODE REVIEW

**Review by flootr — APPROVED** [review]
Tested this locally as `/account-recovery` didn't load on calypso.live. Looks ok! 🍏 

Do we actually use the account recovery flow from Calypso? If I load that page on prod it opens `/wp-login.php?action=lostpassword` which apparently isn't the same.

**Comment by jsnajdr** [comment]
> Do we actually use the account recovery flow from Calypso?

That's a good question: it was never shipped. I personally don't know why, there is a master thread in p195om-30Q-p2. @southp and @dllh worked on the project and will certainly know more.

**Comment by dllh** [comment]
We did a lot of work to design the flows and begin some of the plumbing, but in March 2017, we needed to shift our efforts to higher priority things (probably our chat tools, when I look at the timeline). There's a continuation of the master thread leading up to that discontinuation in p85Ezd-30Q-p2. We never revisited it after that point. I would guess that the flows might still be useful, but it's been long enough that the data structures and styles are likely far out of date.

**Comment by jsnajdr** [comment]
Thanks @dllh for the update. If the project is ever revisited, would any of the existing code still be useful? Apparently we're spending some time maintaining the code when migrating away from legacy libraries and APIs. What if we removed `account-recovery` from the codebase? It'll be still there in the repo history, easy to recover.

**Comment by dllh** [comment]
I don't know if the existing code would be useful. I'm a little skeptical, but I've had my hand out of development for over a year now and don't know what all might have changed. My feeling is that maintaining the code is probably not useful effort at this point and that it'd make sense to remove it, but that's without having confirmed that doing so won't break anything and, again, with a very big gap in my knowledge about what may have changed since we last touched the code. The team that was tasked with working on this no longer exists, so it is effectively orphan code at this point.

**Comment by blowery** [comment]
I spent a little time just to see what yanking account recovery would look like. It appears that we have two variants: the "new" stuff in client/account-recovery and the current production stuff in /me/security. Both appear to be bound to the same chunks of the redux store, though it's not totally clear at first glance which parts were added on for the new project. There's also some bits that tie into the notices middleware that we'd need to untangle. 

I think for now, just landing the css move is enough and we can try to remove account-recovery in the future?

**Pull request merged**
