### PR TITLE
Adds Jetpack routing for homepage

### PR DESCRIPTION
**Pull request by ChaosExAnima**
#### Changes proposed in this Pull Request

* Updates routing logic for Jetpack landing page to direct users to primary site.

#### Testing instructions

Expected results:
* With a primary site of WP.com: Redirect to site picker for backups.
* With a primary site of JP:
  * Redirect to backups for site if backups purchased.
  * Redirect to scan for site if scan and **not** backups purchased.
  * Redirect to site picker for backups if neither purchased.

Fixes 1156570014567299-as-1170686186292217.

### CODE REVIEW

**Comment by ChaosExAnima** [comment]
Okay, refactored to use a new `Home` component that pulls data and redirects accordingly. I also refactored the Capabilities API request to return null if request is not complete (f79205c) and fixed a potential issue in d43baa7.

@rcoll, tagging you as requested 😄

**Comment by ChaosExAnima** [comment]
> All tests passed on my end! The only thing that worries me a bit, that has nothing to do with this implementation, is the blink/refresh we get from the redirect. I guess we should have to make the redirection at the server level to avoid it.

Agreed, but I don't think we could do this on the server side without restructuring the way we get the capability API. We could stand to show the loading screen instead of nothing, however?

**Comment by enejb** [comment]
I tested this and it doesn't produce the expected results when the user is not logged in. 
They get redirected to `/backup`

I think that could be addressed in a different PR.

**Comment by ChaosExAnima** [comment]
@enejb - That is definitely an issue, but I just tested on staging in an incognito window and it happens there. I made a ticket to track handling login cases like this: 1156570014567299-as-1172576079504651.

**Pull request merged**
