### PR TITLE
Stepper: Onboarding flow update tracks events

### LINKED ISSUE #94417: Stepper: Domains step - ensure `calypso_signup_actions_submit_step` records the same props as Classic/Start
See the audit by @travisw: https://github.com/Automattic/wp-calypso/issues/94394

Ensure that we meet the criteria for this:

- [ ] `calypso_signup_actions_submit_step` {step: domains} missing some props that exist in Classic (no idea what they're used for). `domain_item`, `signup_domain_origin`, `site_url`, and `last_domain_searched`

### LINKED ISSUE #94418: Stepper: Plans step - ensure `calypso_page_view` Tracks event records the `flow: name_of_flow` prop
See the audit by @travisw: https://github.com/Automattic/wp-calypso/issues/94394

Ensure that we meet the criteria on Plans step:

- [ ] `calypso_page_view` recording correct `flow: name_of_flow` prop

### LINKED ISSUE #94419: Stepper: Plans page - ensure correct props for `calypso_signup_plan_select` when selecting a plan
See the audit by @travisw: https://github.com/Automattic/wp-calypso/issues/94394

Ensure that we meet the criteria for this (selecting "Personal" plan):

- [ ] Fix missing props in `calypso_signup_plan_select` (`product_slug: personal-bundle`, `from_section: default`) - compared to Classic/Start

### LINKED ISSUE #94420: Stepper: Plans page - ensure `calypso_signup_actions_submit_step` Tracks event records the correct props
See the audit by @travisw: https://github.com/Automattic/wp-calypso/issues/94394

Ensure that we meet the criteria for this (selecting "Personal" plan):

- [ ] Fix discrepancy with different prop value in `calypso_signup_actions_submit_step {step: plans}` - (`cart_items: [object Object]` instead of `cart_items: 0:[object Object]`) - compared to Classic/Start

### PR DESCRIPTION
**Pull request by agrullon95**
Fixes: https://github.com/Automattic/wp-calypso/issues/94417
Fixes: https://github.com/Automattic/wp-calypso/issues/94420
Fixes: https://github.com/Automattic/wp-calypso/issues/94419
Fixes: https://github.com/Automattic/wp-calypso/issues/94418

## Proposed Changes

* Adds tracks event for plans and domain page step submit with correct props (https://github.com/Automattic/wp-calypso/issues/94417 and  https://github.com/Automattic/wp-calypso/issues/94420)
* Adds missing props for `calypso_signup_plan_select` when Plan is selected (`product_slug` and `from_section` )
* Adds `flow` prop to `calypso_page_view` event

## Why are these changes being made?

* Align with /start and be able to analyze important user data

## Testing Instructions

* Checkout branch or use live link
* Navigate to `/setup/onboarding`. Go through the flow and verify the correct events are recorded with necessary props.
* Compare to `/start` on production to see the latest state then compare against `/start` on local to ensure both are returning the same events and props.

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Review by escapemanuele — CHANGES_REQUESTED** [review]
## Domains 🔴 

image

I see the `calypso_signup_actions_submit_step` event being fired twice. The second time with [object Object], but that is identical to what happens in prod.

## Plans 🔴 

image

The event is fired three times.

## calypso_signup_plan_select 🟢 

image

## calypso_page_view 🟢

**Comment by renancarvalho** [comment]
Checking on live link 

For https://github.com/Automattic/wp-calypso/issues/94417, the `domain_item` is empty 
For https://github.com/Automattic/wp-calypso/issues/94420 cart items still wrong 
image
https://github.com/Automattic/wp-calypso/issues/94419 is good ✅ 
https://github.com/Automattic/wp-calypso/issues/94418 is good ✅

**Comment by escapemanuele** [comment]
Thank you @renancarvalho!

- Domains: The value is empty when you select the free domain, so that should be fine
- Plans: Yes, we changed to reflect how it is in /start

**Comment by escapemanuele** [comment]
Opened https://github.com/Automattic/wp-calypso/issues/94708 as a follow-up

**Pull request merged**
