### PR TITLE
Billing management: deprecate the "Other Sites" tab

### PR DESCRIPTION
**Pull request by nbloomf**
#### Changes proposed in this Pull Request

* Remove the Upcoming Charges tab from the account level billing management pages and delete any newly unused code.

#### Testing instructions

* Navigate to `/me/purchases` and verify that there is no "Other Sites" tab in the nav bar.
* Manually load `/me/purchases/upcoming` and verify that you are redirected to `/me/purchases`.

Screen Shot 2020-10-22 at 4 11 17 PM

### CODE REVIEW

**Review by sirbrillig — APPROVED** [review]
Code looks good to me and the testing instructions work as described! We may want to wait until https://github.com/Automattic/wp-calypso/pull/46683 merges, but this is 💯

**Review by fditrapani — APPROVED** [review]
So beautiful! With @michaeldcain's PR merging, this looks good to go!

**Comment by nbloomf** [comment]
I think the e2e failures are unrelated.

**Pull request merged**
