### PR TITLE
SDK: Remove legacy SDK files

### PR DESCRIPTION
**Pull request by ockham**
#### Changes proposed in this Pull Request

Remove `bin/sdk-cli.js`, `bin/sdk/*`, and mentions of those files. These are considered legacy, and superseded by tooling provided by the `@automattic/calypso-build` package.

I opted to remove `docs/sdk.md` altogether. It will be superseded by a `README.md` in `calypso-build` (tracking issue: #31679).

#### Testing instructions

Grep to verify there are no more references to:
- `bin/sdk-cli`
- `npm run sdk`
- `docs/sdk.md`

### CODE REVIEW

**Comment by simison** [comment]
We can remove `yargs` dependency as well I think.

**Comment by ockham** [comment]
> We can remove `yargs` dependency as well I think.

I thought so too, but it's apparently still used here: https://github.com/Automattic/wp-calypso/blob/006d96c71bf6e41f070bed44ddb655f634b9c52b/bin/generate-style-variants.js#L1

**Comment by simison** [comment]
Aight! Let's 🚀 it then :-)

FYI @blowery that's pretty minimal use of Yargs compared to how big the package is. ;-)

**Review by simison — APPROVED** [review]
Looking good. :thumbsup:

**Pull request merged**
