### PR TITLE
Themes: Loading placeholders for theme sheets

### PR DESCRIPTION
**Pull request by seear**
Loading placeholders for Theme sheets.

screen shot 2016-03-15 at 13 30 53

screen shot 2016-03-15 at 13 29 37

**To Test**
* Go to http://calypso.localhost:3000/design, and select _Details_ from the ... button for a theme
* Try at different viewport widths

### CODE REVIEW

**Comment by folletto** [comment]
Design reference:

tshowcase-m4-m7-loading-i3

Notes:

* The title / author pulsates (but white color instead of gray)
* The screenshot doesn't (too overwhelming)
* The white box is ideally tall enough to touch the screen edge, if can't be done easily dynamic, then it's just more than a screen (~900px)

**Comment by folletto** [comment]
screen shot 2016-03-15 at 18 13 59


I pushed a small tweak to the title CSS. I think it's good. :shipit:

**Comment by folletto** [comment]
Just a question: do we want to render the text on the tab bar? Should we blank that too? (I've still set this to Merge since we can merge, still).

**Comment by seear** [comment]
> do we want to render the text on the tab bar? Should we blank that too?

Yeah good point. I think blanking it is best and no more complex. Updated in d7ffefe.

**Pull request merged**
