### PR TITLE
Site: add home-link support.

### PR DESCRIPTION
**Pull request by mtias**
Collaborating with @rickybanister on supporting a home link within `<Site>`. It adds a `homeLink` prop you can set to true when using Site component, which renders a home icon when hovering and sets up the href value.

-----

image

image

image

### CODE REVIEW

**Comment by rickybanister** [comment]
It definitely needs to be the blue color to match the hover for the other sidebar items. The orange indicates a problem or warning to my eye.

I also feel like the 18px gridicon half pixel nudge is making the icon sit slightly to the right of the circle—any way to fix this?

Last thing is to make long site titles/urls fade out rather than show ellipsis when they intersect. 

Otherwise I think it's a good solution, it doesn't disrupt the site indicator (which is due for an update #1634)

**Comment by rickybanister** [comment]
cc @jasmussen to perhaps take a look at the gridicon pixel nudging issue I mentioned above ^

**Comment by mtias** [comment]
> Last thing is to make long site titles/urls fade out rather than show ellipsis when they intersect.

We can add this here or do it separately, should be simple.

**Comment by folletto** [comment]
...isn't a bit too evident for a hover state there? :)

Also: how does it work on the front-end? Just stay visible?

**Comment by jasmussen** [comment]
> cc @jasmussen to perhaps take a look at the gridicon pixel nudging issue I mentioned above ^

I recently (#1593) merged in a tweak to how the pixel nudging works — there were edgecases where it wouldn't work previously. I'm hoping/expecting that should fix any issues.

That being said, 18px is never going to look perfect, it'll just look better. In the case of this house, I think it's definitely okay.

**Comment by folletto** [comment]
So, this is how it would look like on front-end. 

I feel should be without hovering, for more clarity. What do you think?

front-end



I also tried with a 12px icon, and I feel it would work well too:

front-end

**Comment by mtias** [comment]
That seems good to me. I'll try 12px here as well, it's definitely a bit more elegant, though I didn't want to blurry of an icon.

**Comment by mtias** [comment]
This is ready for final review.

**Comment by folletto** [comment]
Tested on Chrome, Firefox, Safari, Edge, IE11.

Works, but...

(1) We need a solution for touch devices, since it won't show there. Maybe always visible, but with the house made in gray without circle?
 
(2) There's a strange flicker on Safari when animates. Can you reproduce?

licecap-

(3) Needs to be synced with a patch on the front-end too.

**Comment by mtias** [comment]
Mobile:

image

**Comment by folletto** [comment]
I would have a preference and use the same gray as the icons below, since it's not really active (thus, not blue), but I would be ok with this.

**Comment by folletto** [comment]
The above fixes the badge flickering in Safari, but the sidebar still does, see "Stats" and "Plans":

licecap-

**Comment by mtias** [comment]
This is annoying. I think we may need to disable the transition.

**Comment by folletto** [comment]
:( but understandable. It's not a blocker.

**Comment by adambbecker** [comment]
@mtias, @folletto: I added a small tweak in 69e15e3 that seems to remove that flickering effect. Mind giving it a whirl?

**Comment by mtias** [comment]
That seems to work well!

**Comment by drw158** [comment]
Home icon might mean Dashboard to a lot of people. Alternatives: globe icon or link icon. 

Link icon makes most sense to me.

**Comment by folletto** [comment]
Right now dashboard in the extended community is:
 
screen shot 2015-12-16 at 18 00 39

So I guess home is ambiguous as any icon without label, but I still think that's the closest one.

**Comment by mtias** [comment]
Rebased and squashed a bit.

**Comment by rickybanister** [comment]
I agree with @folletto regarding the house icon. Especially with the unified masterbar on the front-end. You open the mysites dropdown, you see your site name and it's web address, you see the house, you click and you go back to the homepage of your site. That flow continues when you're in calypso. It's really a link to the 'home page' and in that sense it works for me.

**Comment by mtias** [comment]
Ok, folks, going to merge this one now to have a bit of time and see how it feels. And tomorrow look at adjusting the front end.

**Pull request merged**
