### PR TITLE
Tailored Flows: Improve newsletter flow copies

### LINKED ISSUE #75016: Newsletter onboarding: Update copies
Update copies of all the steps of the newsletter onboarding flow.

[Check links here](HSljkKnYECEEegL3DqP2xC-fi-7798-78158).

### PR DESCRIPTION
**Pull request by renancarvalho**
## Proposed Changes

Improve copy on the Newsletter flow.
Copy on the plans step only regards the title, as the content of the page will be addressed in another PR

## Testing Instructions

- Calypso live links
- Check the newsletter flow
- Check the copy

Fixes https://github.com/Automattic/wp-calypso/issues/75016

### CODE REVIEW

**Comment by alshakero** [comment]
I added string freeze label so we don't have to add `hasTranslations` checks.

**Review by alshakero — COMMENTED** [review]
Let's get rid for `hasTranslation` checks to avoid tech debt and wait for them to be translated.

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/7894067

Hi @renancarvalho, could you please edit the description of this PR and add a screenshot for our translators? Ideally it'd include all of the following strings:
- `Your domain. Your identity.`
- `The Newsletter. Elevated.`
- `Unlimited subscribers. Beautiful design. And everything you need to grow your audience. Powered by WordPress.com.`
- `Launch your Newsletter`
- `Give your blog a name`
- `Open Me Carefully`
- `Add a brief description`
- `Letters from Emily Dickinson's garden`
- `Save and continue`
- `Make it yours.`
- `Personalize your newsletter with a name, description, and accent color that sets it apart.`
- `Spreading the news`
- `Folding the letters`
- `Bringing the news to the letter`
- `Add and continue`
- `Ready to add your first subscribers?`
- `Add your first subscribers — or import 100 for free — to start spreading the news.`
- `sue@example.com`
- `thomaswhigginson@email.com`
- `ed.dickinson@email.com`
- `Or upload a CSV file of up to 100 emails from your existing list. Learn more.`
- `Or <uploadBtn>upload a CSV file</uploadBtn> of up to 100 emails from your existing list. <Button>Learn more</Button>.`
- `Or upload a CSV file of emails from your existing list. Learn more.`
- `Or <uploadBtn>upload a CSV file</uploadBtn> of emails from your existing list. <Button>Learn more</Button>.`
- `Now it’s time to let your readers know.`
- `Let’s get you signed up.`
- `Already have a WordPress.com account? {{a}}Log in{{/a}}`

Thank you in advance!

**Comment by escapemanuele** [comment]
Thanks @alshakero! I removed the use of `hasTranslation`!
Also added some changes to Launchpad copy 👍

**Comment by crisbusquets** [comment]
Hi,

Thanks for working on this :)

I checked the Calypso link and found some small issues:

**"Add subscribers" page**
The entire paragraph, including the "Read more" link seems to trigger the hover state on the "upload a CSV file" link:

https://user-images.githubusercontent.com/25607244/228531175-bbda3db7-4c9e-429e-a7bb-98b35e5b8953.mov

The paragraph text has a different color: on Figma, it is Gray 40 and on the preview, it is almost black. The same for the "Read more" link, which appears blue instead of having the same style as the "upload a CSV file" link.

En dashes should be em dashes.

**Input placeholder color**
The input placeholder text has a different color in the "Make it yours" step vs "Add subscribers". I checked the DotCom design system and they should be Gray / 50 (I'll update the Figma file).

**Choose your plan step**
I see there's an additional copy (Unlock a powerful bundle of features for your Newsletter. Or start with a free plan.) compared to the [Figma file](HSljkKnYECEEegL3DqP2xC-fi-7781-95869). I'm not sure if it's because I used a new design that hasn't been implemented yet.

Thank you again!

**Comment by escapemanuele** [comment]
Hey @crisbusquets, I addressed your feedback! Let me know if you find some other issues.

Regarding the plan step, I left the additional copy to let the user go with the free plan, given that the plans available have not yet been updated. We'll do that in a following PR, and remove the subtitle there.

**Review by crisbusquets — APPROVED** [review]
LGTM 💯

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/7894067

Hi @renancarvalho, could you please edit the description of this PR and add a screenshot for our translators? Ideally it'd include all of the following strings:
- `Let’s get you signed up.`
- `Already have a WordPress.com account? {{a}}Log in{{/a}}`

Thank you in advance!

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/7894067

Hi @renancarvalho, could you please edit the description of this PR and add a screenshot for our translators? Ideally it'd include all of the following strings:
- `Let’s get you signed up.`
- `Already have a WordPress.com account? {{a}}Log in{{/a}}`
- `Bring up to 100 subscribers for free — or add some individually — to start spreading the news.`
- `A catchy name, description, and accent color can set a newsletter apart.`

Thank you in advance!

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/7894067).

**Pull request merged**
