### PR TITLE
Update P2 signup 'hooray' screen to new design

### PR DESCRIPTION
**Pull request by msurdi**
Addresses 4797-gh-Automattic/p2 
 
#### Changes proposed in this Pull Request

* Change the design of he P2 Workspace creation loading screen 

from:

image

to:

image

#### Testing instructions

* Run this branch locally or via the Calypso live branch
* Navigate to `/start/p2/p2-site`
* Fill in the two inputs to create a new workspace and submit the form
* Ensure the loading screen looks as in the attached screenshots or the linked issue design files.
* Ensure the workspace name is correctly shown in the loading screen detail text.

### CODE REVIEW

**Review by naxoc — CHANGES_REQUESTED** [review]
I took this for a test spin. I got an empty `""` towards the end of the Hoorays:

https://user-images.githubusercontent.com/193283/157636504-cf5c3061-72f5-4bbc-a9a9-4818f1f1c480.mov

I wonder if we can grab the name from something else or make sure that it doesn't change when it's almost done?


Other than that it is looking good!

**Comment by msurdi** [comment]
@naxoc I've just pushed a commit to fix it, would you give it another try? Thanks for your help with this 👍 👍

**Review by naxoc — APPROVED** [review]
Looks great! 👍

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/7181909

Thank you @msurdi for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/7181909).

**Pull request merged**
