### PR TITLE
Plans 2023: remove route/path checks for 2023 grid eligibility

### LINKED ISSUE #77650: Plans 2023: Remove the path whitelisting for showing the new grid
Related to https://github.com/Automattic/martech/issues/1533

Just remove the whitelisting, so 2023 grid becomes the default grid unless explicitly disabled.

### PR DESCRIPTION
**Pull request by chriskmnds**
Related to https://github.com/Automattic/wp-calypso/issues/76766
Closes https://github.com/Automattic/wp-calypso/issues/77650

## Proposed Changes

Removes the path whitelist (so 2023 grid becomes the default grid unless explicitly disabled) Any new flow in Stepper (`/setup`) or `/start` with a plans step should render the new grid by default.

Not addressed:

- No change for p2 plans stemming from `/start/p2`

## Testing Instructions

- [ ] Test existing flows and admin pages and ensure the new 2023 grid renders:
    - [ ] `/start/plans`
    - [ ] `/plans/[paid|free]`
    - [ ] `/setup/newsletter`
    - [ ] `/setup/link-in-bio`
    - [ ] `/start/hosting`
    - [ ] `/start/domain`
    - [ ] `/setup/domain-upsell`
    - [ ] `/setup/start-writing`
    - [ ] `/setup/design-first`
    - [ ] `/setup/wooexpress` -> complete flow and reach `/plans/[site]` with site created
    - [ ] `/setup/domain-upsell` -> go to `/home` with free site, from there click on "Get this domain"
- [ ] `/start/p2` -> grab site created and go to `/plans`: should render the old pricing grid with two plans

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

**Comment by jeyip** [comment]
## Testing
### Requirements
Verified 2023 grid by opening dev console and searching for "is-pricing-grid-2023" in the element inspector

- Test existing flows and admin pages and ensure the new 2023 grid renders:
    - [x] `/start/plans`
    - [x] `/plans/[paid|free]`
    - [x] `/setup/newsletter`
    - [x] `/setup/link-in-bio`
    - [x] `/start/hosting`
    - [x] `/start/domain`
    - [x] `/setup/domain-upsell/plans`
    - [x] `/setup/start-writing`
    - [x] `/setup/design-first`
    - [ ] `/setup/wooexpress` -> complete flow and reach `/plans/[site]` with site created
    - [x] `/setup/domain-upsell` -> go to `/home` with free site, from there click on "Get this domain"
- [ ] `/setup/p2` -> grab site created and go to `/plans`: should render the old pricing grid with two plans

### Browsers
- [x] Chrome

### Notes

- @chriskmnds  `/setup/p2` redirects to home if I'm a logged in user, and to dev docs if I'm logged out and register as a new user. I couldn't figure out how to load the /plans page. As noted above, this PR is so simple that I'll trust that you tested it successfully.

Screenshot 2023-05-30 at 11 24 08 AM

- I couldn't get `/setup/wooexpress` to load. I would sign into my WordPress.com account and it would repeatedly throw an "Account not found" error. Since this is such a straightforward PR, I trust you if you successfully tested it.

Screenshot 2023-05-30 at 11 18 10 AM

- For posterity, `/setup/domain-upsell -> go to /home with free site, from there click on "Get this domain"` directions didn't work. `/home` continually redirected to the Launchpad. I needed to navigate to plans from the Launchpad itself by clicking on the `Choose a plan` task
 
- I didn't see an obvious flow for `/start/hosting` I ended up using the `Create your first site` button

Screenshot 2023-05-30 at 11 03 57 AM

- For `/start/domain` I used the `Start site` button

Screenshot 2023-05-30 at 11 07 07 AM

**Review by jeyip — APPROVED** [review]
I wasn't able to successfully test some flows because I wasn't able to reach their respective plans pages. This is, however, a straightforward PR, so feel free to merge if you're confident.

**Comment by dzver** [comment]
I covered the test plan but I would appreciate some further instructions about how to test the following cases:

- [ ] /setup/start-writing - could you clarify how to get to /plans here? I didn't see any plans
- [ ] /setup/design-first - the same issue
- [ ] /setup/wooexpress -> complete flow and reach /plans/[site] with site created - no plans visible after completing
- [ ] /setup/p2 - this doesn't seem to do anything for me

Everything else works well, and the code is LGTM

There's a merge conflict though

**Comment by chriskmnds** [comment]
Thanks @jeyip @dzver for testing! Outside of a few flows that we interacted with recently (start, newsletter, link-in-bio, wooexpress) I am really not familiar with the rest either. They've been whitelisted though for showing the grid, so either it was by mistake, or a plans step was later removed, or there's more to this whitelisting than meets the eye. I will go through your comments and test things further.

> /setup/p2 - this doesn't seem to do anything for me

My mistake! It should be `/start/p2`, not "setup".

**Comment by chriskmnds** [comment]
p.s. @dzver the review was just for this PR right? or also for https://github.com/Automattic/wp-calypso/pull/77493 ? https://github.com/Automattic/wp-calypso/pull/77493 has the same test plan and contains most of the critical changes that we want. It would be great to get that out of the way to ease further work.

**Comment by jeyip** [comment]
> I covered the test plan but I would appreciate some further instructions about how to test the following cases:

>  /setup/start-writing - could you clarify how to get to /plans here? I didn't see any plans
>  /setup/design-first - the same issue

@dzver For `start-writing`, you need to navigate to `calypso.localhost:3000/setup/start-writing` as a logged out user. You can then register as a new user, at which point you'll be redirected to the post editor. You'll create a test post, which should prompt you to navigate to the Launchpad ( or it may redirect you automatically )

From there, you'll see some sort of `Choose a plan` task that, when clicked on, will take you to the `/plans` page. You may have to complete the `Choose a domain` task beforehand.

It's a similar set of steps for the `design-first` flow. Navigate to `calypso.localhost:3000/setup/design-first` as a logged out user, register new user, follow design selection onboarding steps, be redirected to the Launchpad,  complete the `Choose a domain` task, and then click on the `Choose a plan` task

**Comment by jeyip** [comment]
For posterity, I created a list of all known instances of the 2023 plans page with instructions about how to navigate to them from the UI PCYsg-RDT-p2

**Comment by chriskmnds** [comment]
> For posterity, I created a list of all known instances of the 2023 plans page with instructions about how to navigate to them from the UI PCYsg-RDT-p2

Thanks, @jeyip. This is really helpful.

I think we missed a couple:

- `/start/import`
- `/setup/new-hosted-site`
- also plans are imported and rendered under `client/my-sites/plugins`. There are a couple of routes there at the bottom that reference plans, but I haven't confirmed if still active (and if not, might be wise to raise it up to cleanup).
- and something about "jetpack-app" that we may need to dig in a little more. There are JP plans, but not sure if they render the same grids (and if not, whether they should)

**Pull request merged**
