### PR TITLE
chore: Remove unused files from packaes/wpcom.js

### PR DESCRIPTION
**Pull request by scinos**
#### Changes proposed in this Pull Request

* Delete makefile, we don't run it.
* Delete tests, they were wrote to run in Mocha in a browser and we want Jest. We were not running them anyway.
* Delete the website. It was used to provide https://wpcomjs.com/, but we don't update the site anymore.

#### Testing instructions

N/A

### CODE REVIEW

**Comment by noahtallen** [comment]
> Delete the website. It was used to provide https://wpcomjs.com/, but we don't update the site anymore.

What will happen to that website? Do we plan to remove it?

**Comment by scinos** [comment]
> > Delete the website. It was used to provide https://wpcomjs.com/, but we don't update the site anymore.

> What will happen to that website? Do we plan to remove it?

That site was published from Github Pages from the old repo (https://github.com/Automattic/wpcom.js). The last update to the page was ~4.5 years ago.

I don't know what are the plans. I think @jsnajdr did the original import from wpcom.js into Calypso, maybe he knows?

**Comment by jsnajdr** [comment]
We can remove the website tests (`webapp/tests`), but let's keep the site in the repo. I.e., the HTML, CSS and JS file and the webpack config. After a little cleanup in #54886, the website can be built and if anyone ever needs to deploy it again, they have a quite good starting point here. The site is still alive, so let's not delete the sources yet.

**Comment by scinos** [comment]
What's the process to update the site? What's even the goal of having the site around?

I strongly think that unless we have a clear purpose for it and a way that deploys it automatically (so we don't rely on people remembering to run anything), we should take the opportunity to simplify things and remove it.

**Comment by jsnajdr** [comment]
> What's the process to update the site? What's even the goal of having the site around?

It's hosted on GitHub Pages and the last person who deployed it was @retrofox a few years ago. It's a homepage for the wpcom.js library, that's all.

If we wanted to decide whether to remove it or not, the criteria should be whether there are incoming links to it (there's at least one in the Calypso README) and how many visitors it has.

Answering these questions means work, and it's a very low-impact thing to work on. That's why I think the cheapest course of action is just to leave the site alone.

As long as the site is alive, I think we should keep the sources it was deployed from.

**Comment by scinos** [comment]
> Answering these questions means work, and it's a very low-impact thing to work on. That's why I think the cheapest course of action is just to leave the site alone.

It doesn't make it a good thing to work on. Following that logic, deleting it is even cheaper. This code (source code for an outdated website with no clear purpose, with no way to measure the impact it has and that we don't actively test or deploy) is plain technical debt.

> As long as the site is alive, I think we should keep the sources it was deployed from.

But we do have those, they are in the archived Git repo. And having the sources in wp-calypso doesn't really help because we don't have a method to deploy the site from here. Nor a process to do it.

Maybe we should kill the site, and redirect the domain `wpcomjs.com` to the wpcom.js package README. Doesn't look like the site provides any benefit that a README can't provide with a fraction of the complexity.

**Comment by jsnajdr** [comment]
> Maybe we should kill the site, and redirect the domain wpcomjs.com to the wpcom.js package README.

Yes, that would be the best solution. We get to keep the site and it would just redirect to npmjs.com/package/wpcom. There are two domains: wpcomjs.com, with a homepage hosted on Fastly, and even more forgotten wpcomjs.io, which points to a non-existent page on GitHub pages. Shall we do a systems request to redirect both to the npmjs.com URL? Then we can delete the legacy site from the repo without any regrets.

**Comment by scinos** [comment]
Done pMz3w-dwe-p2

**Comment by scinos** [comment]
Given this is low-risk and all concerns have been addressed, I'm going to merge it.

**Pull request merged**
