### PR TITLE
Reader: Fix alignnone outside captions

### LINKED ISSUE #8039: Reader: Inline images get block'ed & centered in full page view
#### Steps to reproduce
1. Starting at URL: wordpress.com/post/{siteid}
2. Create a post with a couple small inline images
3. Publish
4. View post in Reader

#### What I expected

That inline images would stay inline

#### What happened instead

Inline images are put on their own line and centered

#### Screenshot / Video

https://cloudup.com/cmTLJ-5ioYG

#### Example post

https://wordpress.com/read/blogs/93107746/posts/83

### PR DESCRIPTION
**Pull request by blowery**
Fixes #8039

### CODE REVIEW

**Comment by blowery** [comment]
cc @meremagee

**Comment by blowery** [comment]
test post: http://calypso.localhost:3000/read/blogs/77147075/posts/195 vs https://wpcalypso.wordpress.com/read/blogs/77147075/posts/195

**Comment by catrymer** [comment]
I tested this and it works for me.

**Comment by jancavan** [comment]
LGTM 👍

**Pull request merged**
