### PR TITLE
Sites Dashboard: Remove layout-related overrides from Dotcom and A4A 

### PR DESCRIPTION
**Pull request by okmttdhr**
Related to https://github.com/Automattic/dotcom-forge/issues/10139

## Proposed Changes

This PR removes layout-related overrides from Dotcom and A4A. 

For details of individual overrides, please refer to this post's  pfYzsZ-15D-p2 "Style Overrides Removal" and "Remaining Style Overrides" sections. 

## Why are these changes being made?

https://github.com/Automattic/dotcom-forge/issues/10139

## Testing Instructions

On both Calypso and A4A Live;

* Go to /sites
* Click any site
* Ensure nothing breaks

A4A Live

* Go to /overview
* Go to /marketplace/assign-license
	* This page has a bit different layout from other A4A pages.
* Ensure nothing breaks

## Pre-merge Checklist

- [x] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [x] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [x] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [x] Have you checked for TypeScript, React or other console errors?
- [x] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [x] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
    - [x] For UI changes, have we tested the change in various languages (for example, ES, PT, FR, or DE)? The length of text and words vary significantly between languages. 
- [x] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Review by fushar — APPROVED** [review]
Tested on wpcom and A4A; works well.

We might need to update other hosting pages like Themes, because now they have different border-bottom:

|Sites|Themes|
|-|-|
|image|image

**Comment by andrii-lysenko** [comment]
Thank you for working on this. 
This seems to work well and I haven't found any issues. The code looks good as well 👍

**Comment by okmttdhr** [comment]
>We might need to update other hosting pages like Themes, because now they have different border-bottom:

I think we should update the <code inline="">border-block-end</code> of <code inline="">.hosting-dashboard-layout__top-wrapper</code> to align with the DataViews border color (i.e., the border color used in Dotcom Sites Dashboard rows).
The issue is that A4A currently uses different border colors for the rows from Core, the same as the `.hosting-dashboard-layout__top-wrapper`. Thus, we should also update A4A's border-color for rows.

The current border-color:

| Dotcom | A4A |
|--------|--------|
| Screenshot 2024-12-30 at 9 12 49 | Screenshot 2024-12-30 at 9 12 58 |

**Comment by okmttdhr** [comment]
Confirmed it's working well even after https://github.com/Automattic/wp-calypso/pull/97773 ✔️

**Pull request merged**
