### PR TITLE
Remove `/me/next-steps/`

### LINKED ISSUE #3224: Signup: Remove /next
With welcome/next replaced in Signup with [the NUX Trampoline](https://github.com/Automattic/wp-calypso/pull/2539) is the /next screen necessary for any flows? Can we remove it from the /me menu? Remove it entirely?

### PR DESCRIPTION
**Pull request by michaeldcain**
`/me/next-steps/` is an old user onboarding/tutorial guide that has been replaced in Signup with the NUX Trampoline (#2539) on the front-end of a new user's site. This removes the page from `/me/` and any legacy occurrences of it in Signup.

Fixes #3224.

### CODE REVIEW

**Comment by mtias** [comment]
Needs a rebase.

**Comment by michaeldcain** [comment]
We might be holding on this until after a new homepage test. I'll update when I know more.

**Comment by lancewillett** [comment]
Hi @michaeldcain — this still on your radar? Can we nudge it along and get that extra section removed now?

**Comment by michaeldcain** [comment]
I'll take a look at getting this PR cleaned up today. There aren't currently any active Signup flows using the page, so traffic should be pretty low. Thanks for the reminder!

**Pull request closed without merging**
