### PR TITLE
Reader: Fix Manage following header cake

### PR DESCRIPTION
**Pull request by jancavan**
#### Changes proposed in this Pull Request

This fixes: https://github.com/Automattic/wp-calypso/issues/33177

Since the link to Manage has been moved from the sidebar to within the following stream, the header cake component has been added to be able to return your stream. However, the alignment looks off.

This PR:
1. Adds back the header cake border
2. Updates copy from "Follow something new" to the actual name of the page, "Manage Followed Sites"

#### Testing instructions

1. Go to Reader
2. Click on Manage: http://calypso.localhost:3000/following/manage

**Before:**
Screenshot 2019-06-11 16 39 21

**After:**
Screenshot 2019-06-11 16 23 18

Another alternative I tried was to add the text as a form label instead, but I think retaining the current header cake style works better:

Screenshot 2019-06-11 15 55 30

We could also make this particular header cake work like the segmented control component with a collapsed Search functionality, but that'll require more work which would have to tackled in a separate PR.
Screenshot 2019-06-11 16 54 48

### CODE REVIEW

**Comment by sixhours** [comment]
Linting error (duplicate instances of `componentWillUnmount`) is unrelated to this PR and should be fixed in a separate PR.

**Comment by bluefuton** [comment]
> Linting error (duplicate instances of componentWillUnmount) is unrelated to this PR and should be fixed in a separate PR.

I quickly fixed this for you in 0d3b59e 👍

**Comment by jancavan** [comment]
Thanks @bluefuton!

**Comment by jancavan** [comment]
@sixhours Can I get another 👀 please? Thanks.

**Pull request merged**
