### PR TITLE
Docs: Allow `git rebase trunk` or `git merge trunk` in Git workflow

### PR DESCRIPTION
**Pull request by danielbachhuber**
## Proposed Changes

Updates `docs/git-workflow.md` to allow `git rebase trunk` _or_ `git merge trunk`.

The original rationale (7+ years ago) for `git rebase trunk` was:

> While it is tempting to merge from `trunk` into your branch frequently, this leads to a messy history because each merge creates a merge commit.

However, this point is moot with GitHub's "Squash and merge" feature.

An [informal Twitter poll](https://twitter.com/dbchhbr/status/1551891815267151872) sez `git merge trunk` is "the best way to keep your branch up to date", by a narrow margin.

Force-pushing a branch has the unfortunate side effect of making a pull request harder to read. All of the commits end up at the end of the pull request, making it more difficult to understand which comments led to which commits.

## Testing Instructions

1. Try using `git merge trunk` and see how much nicer it is to review a pull request.

### CODE REVIEW

**Comment by daledupreez** [comment]
In terms of feedback, the one downside of `git merge trunk` is that any merges that pull in files with assigned reviewers in `.github/CODEOWNERS` will automatically add those reviewers to your PR.

This already generates a bunch of noise for me.

**Comment by danielbachhuber** [comment]
> In terms of feedback, the one downside of `git merge trunk` is that any merges that pull in files with assigned reviewers in `.github/CODEOWNERS` will automatically add those reviewers to your PR.
> 
> This already generates a bunch of noise for me.

@daledupreez That does seem annoying! While I suppose it's the technically correct behavior, I wonder if there's a way to work around it? Can you point me to an example?

Also, I wonder how well `CODEOWNERS` is actually used? I imagine the spectrum of usage is somewhere between `CODEOWNERS is frequently used and the right people actively review relevant code changes` and `CODEOWNERS is infrequently used and/or people mostly ignore the pings`.

**Comment by daledupreez** [comment]
Sure! You can see a nice big review got triggered in #65572 after a merge rather than a rebase, as noted in [this comment](https://github.com/Automattic/wp-calypso/pull/65572#issuecomment-1201769958).

Also, after taking a look at the CODEOWNERS file, it seems like most of the rules are relevant and up-to-date, though some of them do look defunct and/or need updates. But I think there are multiple groups in there who do regular work on the relevant pieces of code:
* Letero looks after email-related code
* Nomado looks after domains-related code
* Shilling looks after payments-related code
* Team Calypso looks after Calypso infrastructure
* The Experimentation Platform team looks after explat
* The i18n team looks after i18n
* The KitKat team looks after e2e tests

It looks like there are config or permissions issues that exist, but those are distinct from the right teams being tagged.

**Comment by lsl** [comment]
Rebasing breaks `git pull`. When you're working on things with other people `git merge` is the better option.

> You can see a nice big review got triggered in https://github.com/Automattic/wp-calypso/pull/65572 after a merge rather than a rebase, as noted in https://github.com/Automattic/wp-calypso/pull/65572#issuecomment-1201769958.

If that's the case it sounds like the `CODEOWNERS` feature is looking at the diff between the PR's commit base and its `HEAD` instead of the diff between the PR target branch `HEAD` and the PR `HEAD`.

Maybe this is something Github could fix? ([posted a discussion](https://github.com/community/community/discussions/28121))

**Pull request merged**
