### PR TITLE
Components: Directly import from `@automattic/components`

### PR DESCRIPTION
**Pull request by ockham**
#### Changes proposed in this Pull Request

For components that are in the `@automattic/components` package, change imports to directly import from there, and drop 'alias' files in `client/components/` that were originally added to facilitate transition (without requiring changes to imports).

An example change would be

```
import Button from 'components/button';
import Card from 'components/card';
```

to 

```
import { Button, Card } from '@automattic/components';
```

(I also ran a [codemod](https://gist.github.com/jukben/17da2376a677cf430e4403a951a29314) to de-duplicate imports.)

The components affected are:

- [x] `Button`
- [x] `Card`
- [x] `ProgressBar`
- [x] `Ribbon`
- [x] `ScreenReaderText`

The other components in the package were already being imported `from '@automattic/components'`.

#### Testing instructions

Verify that the app still builds and runs.

### CODE REVIEW

**Comment by jsnajdr** [comment]
Some Enzyme tests are failing because of mocks like this:
```js
jest.mock( 'components/card/compact', () => 'CardCompact' );
```
I encountered several such mocks lately when upgrading `react-redux` and `i18n-calypso`, and most of the time they can be simply removed.

Our components and libraries are in a much better shape (re SSR and Node compatibility) today than they were when these tests were written, and excessive mocking is not needed.

**Comment by ockham** [comment]
@jsnajdr Thanks! I've fixed `test-client` (mostly by dropping mocks).

The errors in `test-packages` seem unrelated to the import changes; I've filed a fix in #38312.

**Review by jsnajdr — APPROVED** [review]
All tests are green and the lint failure is expected: we touched hundreds of files with preexisting issues. Let's merge before the branch becomes stale! :+1:

**Comment by sirbrillig** [comment]
Unfortunately, this modified imports of files called `button.js`, even if they were not in Calypso. 

Notably, the `composite-checkout` and `composite-checkout-wpcom` packages have their own [Button](https://github.com/Automattic/wp-calypso/blob/master/packages/composite-checkout/src/components/button.js) [components](https://github.com/Automattic/wp-calypso/blob/master/packages/composite-checkout-wpcom/src/components/button.js). This change broke those, which isn't a big deal since that package isn't yet in production, but this could have been much worse if it was since those packages do not have `@automattic/components` in their dependencies. I'll create a PR to restore those imports.

You might want to check the other files modified in this PR to make sure none of them were importing something called `Button`.

**Pull request merged**
