### PR TITLE
Themes - Fix "back" to Themes showcase on empty query.

### LINKED ISSUE #38120: Themes: select a theme, then go back and my place is lost
#### Steps to reproduce
1. Visit wordpress.com/themes
2. Scroll past "Recommended Themes" and click the "More Themes" button.
3.  Do NOT put in any search or filter params.
4.  Scroll down further and view "info" of a theme.
5.  Hit the back button, notice that we are looking at "Recommended Themes" and the search showcase is again hidden behind the "More Themes" Button.

#### What I expected
Expected to land at the "Advanced Themes" section on going back.

#### What happened instead
Landed on "Recommended Themes" with back button hidden.

#### Context / Source

This is a result of recent changes made on the Themes showcase section after adding a "Recommended Themes" section and hiding the search functionality behind the "More Themes" button.  Main PR #37696 and Issue #37285.  And after followup PR #38107 and Issue #38061.

### PR DESCRIPTION
**Pull request by Addison-Stavlo**
#### Changes proposed in this Pull Request

Added showcase boolean to data store:
* Showcase stays open when going "back" with no query params.
* Showcase will automatically be set open on data store if loaded with query params, which allows returning to the themes showcase with no query to already be open even if they had never seen the button due to the original load w/ query.

#### Testing instructions

* Run this PR locally.
* Navigate to themes section.
* Open "More Themes" and do NOT enter any query params.
* Scroll down and select "Info" for some theme.
* Hit the "back" button.
* Verify we are back at the theme we selected with the showcase open.

* STILL TODO - Hit "Info" again, and hit the "Back" button again.  Verify this no longer leads us back to the theme we selected and that we are now facing the top of the page (Recommended Themes).

Fixes #38120 (partial fix currently)

### CODE REVIEW

**Comment by apeatling** [comment]
@Addison-Stavlo Is this one ready for review, or should I wait on further updates?

**Comment by Addison-Stavlo** [comment]
I was looking into it a bit more, but you are welcome to test its current behavior.  The All Themes section is no longer closed going back, which is a nice change on its own and may be worth shipping sooner rather than later.  I just need to throw some tests in for the new action/reducer before I'm ready to merge it in that case.

I have still been looking into that last issue I noted above under "STILL TODO".  I would like to fix that as well but it may be worth doing it in a follow-up PR if we want to get the first part out sooner.

**Comment by apeatling** [comment]
This is fine to ship, assuming we can open an issue for the follow up.

**Review by apeatling — APPROVED** [review]

**Comment by Addison-Stavlo** [comment]
Sounds good!  Im going to move it into "Needs Review" for a minute to try and trigger all the e2e tests to run here again, but I will merge it when all is good and open a followup.

**Pull request merged**
