### PR TITLE
Update/import light screens

### PR DESCRIPTION
**Pull request by bogiii**
#### Changes proposed in this Pull Request

* Updated light importer screens to match a new design: 42PgVsdlQ1v2wpk6lmmrnq-fi-1821%3A54036
* Adjusted/unified  other importer progress bar screens
  * Changed heading font
  * Updated heading margins
  * Updated progress bar styles

#### Testing instructions

* Since the stepper framework currently only show capture screen: `/setup/importLight?siteSlug={SLUG}`
* The other screens are available on the `start` routes:
  * `start/import-light/static`
  * `start/import-light/static/scanning`
  * `start/import-light/static/colors`
  * `start/import-light/static/summary`

#### Screenshots

Screenshot 2022-05-25 at 15 19 51
Screenshot 2022-05-25 at 15 20 32
Screenshot 2022-05-25 at 15 28 15
Screenshot 2022-05-25 at 15 22 11

#### Adjusted  other importer progress bar screens ⬇️ ⬇️ ⬇️

<table>
<tr>
<td width="50%">Before:</td>
<td width="50%">After:</td>
</tr>
<tr>
<td width="50%">
Screenshot 2022-05-24 at 16 48 32
</td>
<td width="50%">
Screenshot 2022-05-24 at 16 43 54
</td>
</tr>
</table>
Screenshot 2022-05-25 at 15 13 06

Related to #63911

### CODE REVIEW

**Review by vishnugopal — COMMENTED** [review]
I'm not sure if it's something related to how I'm testing, but I'm not seeing the new blue progress bar for the import light scanning steps:

CleanShot 2022-05-26 at 10 26 10@2x

It is working for the revised migration flow though, so strange!

**Comment by bogiii** [comment]
Hmmm, strange.
I just checked locally and from the GH generated link.

It looks ok:
- https://container-nostalgic-mirzakhani.calypso.live/start/import-light/static/scanning
- https://container-nostalgic-mirzakhani.calypso.live/start/import-light/static/colors
- https://container-nostalgic-mirzakhani.calypso.live/start/import-light/static/summary

cc @vishnugopal

**Review by zaerl — APPROVED** [review]
LGTM!

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/7338031

Thank you @bogiii for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/7338031).

**Pull request merged**
