### PR TITLE
State: Stop altering the original site schema in reader/sites

### PR DESCRIPTION
**Pull request by blowery**
Properly clone out the pattern object before adding in the new property

Test live: https://calypso.live/?branch=fix/state/reader-sites-schema

### CODE REVIEW

**Comment by blowery** [comment]
cc @mcsf as the spotter

**Comment by mcsf** [comment]
Hm, I'm not convinced that this solves the issue. See:

screen shot 2016-06-29 at 14 15 46

I think we need to change the object at each level of the tree, lest we keep a reference to `siteSchema`'s branches. It's painful, but I think that manually this would look like:

```js
const readerSitesSchema = {
	...sitesSchema,
	patternProperties: {
		...sitesSchema.patternProperties,
		[ '^\\d+$' ]: {
			...sitesSchema.patternProperties[ '^\\d+$' ],
			properties: {
				sitesSchema.patternProperties[ '^\\d+$' ].properties,
				feed_ID: { type: 'number' }
			}
		}
	}
}
```

**Comment by blowery** [comment]
Oof, you're right. have to change it all the way up the tree. Sigh.

**Comment by blowery** [comment]
ok, @mcsf should actually be fixed. yay object comprehensions.

**Comment by mcsf** [comment]
Yay. Btw, I just realized that we still use `react-addons-update` in Calypso. For some reason I thought we were discouraging it (are we?) and so proposed a manual solution, but it would make this a lot easier.

**Pull request merged**
