### PR TITLE
Plans 2024: Code hygiene/cleanup before package extraction

### PR DESCRIPTION
**Pull request by chriskmnds**
Related to #

## Proposed Changes

Some general code hygiene to firm the ground for the plans-grid package extraction next. directory cleanup, removing some redundant dependencies, migrating a few types to be centrally exported, better export/import statements, etc.

Next up from here is the actual package extraction. It should hopefully not be a lot more complicated than moving things under `/packages` (either under the existing package or in a new one), updating the imports, and building it.

## Testing Instructions

* Test that the grids and interval toggle render correctly under `/start/plans`, `/setup/newsletter/plans`, `/plans/[ site ]`
* It would be surprising if other breakage isn't flagged in tests and build
* Maybe do a search for any imports from `my-sites/plans-grid/**` that haven't been updated

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

**Comment by jeyip** [comment]
## Testing
### Requirements

For each of the flows listed below:
- Verified header price and billing timeframe price with production 
- Verified pricing for monthly and yearly pricing
- Can purchase a plan
- Can purchase storage add-ons
- Can purchase multi-year plans and monthly plans ( when the option is provided )
- Clicking on the comparison grid toggle auto-scrolls the grid into view
- Spot check desktop and mobile
- Spot check features listed for each plan

For at least one of the flows listed below:
- Large currencies are displayed appropriately ( tested IDR )
- Foreign languages are displayed appropriately ( tested French )
- Currency discounted pricing displays appropriately
- Pro rated pricing on the /plans page displays appropriately
- Spot checked the spotlight plan on the /plans page
- Can upgrade an existing plan

Additionally for the Newsletter flow:
- Only the free, starter, and explorer plans are rendered
- No storage add-ons can be added
- "View all plans" escape hatch behaves as expected

Flows:
- [x] /start
- [x] /setup/newsletter
- [x] /plans

### Browsers
- [x] Chrome

### Notes

I'm seeing more of a subtle bug unrelated to this PR ( it's present in production ). In the comparison grid, when different plans are selected for display, whenever there is an interaction that causes re-render ( Ex. plan type term selection or storage add-on selection ), it resets what plans are displayed to the default arrangement.





Also unrelated to this PR. The manage add-ons button in the spotlight card isn't vertically centered anymore. Unsure if this is intentional.

Screenshot 2024-01-17 at 1 27 10 PM

I can make Github issues for these tomorrow 👍

**Comment by jeyip** [comment]
> It would be surprising if other breakage isn't flagged in tests and build

 I found several issues so far that I've noted, but they're all existing problems. Things are looking good so far @chriskmnds 🎉 There's no high five emoji, so this will have to do ✋ 5️⃣ 

I can test several more flows and help do some searching with you for missed imports tomorrow 🙂

**Comment by southp** [comment]
@jeyip 

> I'm seeing more of a subtle bug unrelated to this PR ( it's present in production ). In the comparison grid, when different plans are selected for display, whenever there is an interaction that causes re-render ( Ex. plan type term selection or storage add-on selection ), it resets what plans are displayed to the default arrangement.

This has been tracked here already: https://github.com/Automattic/martech/issues/2554

> Also unrelated to this PR. The manage add-ons button in the spotlight card isn't vertically centered anymore. Unsure if this is intentional.

Nope, it's not intentional. It's introduced when I worked on https://github.com/Automattic/wp-calypso/pull/86392. Please feel free to create a tracking issue for it :)

**Comment by chriskmnds** [comment]
Thanks for testing! 🙇 
I will do a few more checks and merge here since none of the issues are related. We need more energy to go into the package extraction - for which I may have to ask you all to rebase your branches over, and to not merge anything new if not super critical until it ships (if the PR looks promising). @jeyip @southp

**Comment by chriskmnds** [comment]
Amazing testing again @jeyip. Thank you! Much much appreciate it ⭐

**Comment by jeyip** [comment]
> Nope, it's not intentional. It's introduced when I worked on https://github.com/Automattic/wp-calypso/pull/86392. Please feel free to create a tracking issue for it :)

https://github.com/Automattic/wp-calypso/issues/86607

**Pull request merged**
