### PR TITLE
Welcome Tour: combine existing and variant tour plugins

### PR DESCRIPTION
**Pull request by ramonjd**
### Background

We kicked off the Welcome Tour redesign A/B test last week. Unfortunately it had to be stopped as it was causing storage issues on the experiment platform. 

Because we were assigning users to the Welcome Tour experiment on `plugins_loaded`, we were storing an assignment for every single WordPress.com user on every single WordPress.com load.

It's preferred to assign users at the appropriate decision point. For the Welcome Tour, that point is when the editor loads. 

To boot, we were also constrained by the Anchor.fm flow, which introduced new content to the existing Welcome Tour; content the variant does not have. We must therefore restrict our test to non-Anchor.fm flows :)

Context: pbxNRc-Cb-p2#comment-1537

### Changes proposed in this Pull Request

This PR does a couple of things:

1. It combines the Welcome Tour control and variant code into one plugin
2. It creates a new component for `registerPlugin` that decides which tour to use
3. We grab the experiment value via the `block-editor/nux` endpoint, which is called only when the editor loads and only once for new users.
4. Ensures that users on the Anchor.fm flow never see the variant (the new one!)

**Existing Welcome Tour**
Screen Shot 2021-01-26 at 10 37 18 pm

**The variant**
Screen Shot 2021-01-26 at 10 41 09 pm

### Testing instructions

Take a deep breath. This might take a while.

Apply `D55985-code` (the experiment)
Apply the diff for this ETK PR `D55998-code`

Before each test, reset your NUX status, clear your Application data (local storage and IndexDB) and enable the NUX tour in your user meta/attributes in wpsh;

```
echo update_user_meta( [YOUR_USER_ID], 'wpcom_block_editor_nux_status', 'enabled' );
echo update_user_attribute( [YOU_USER_ID], 'wpcom-block-editor-preferences', [ 'nux-status' => 'enabled' ] );
```

This ensures the NUX modal will popup

#### Existing Welcome Tour

- [ ] With the experiment set to **control**, open a post. You should see the existing welcome tour
- [ ] Check the tracking events. For example, `calypso_editor_wpcom_nux_open` should fire when the existing tour opens. Check paging through the slides and closing it.
- [ ] Close the tour and refresh the page. You should not see the tour.
- [ ] Open the tour manually by clicking on _Welcome Guide_ in the Editor Options menu. You should see the existing welcome tour

#### Variant Welcome Tour

- [ ] With the experiment set to **treatment**, open a post. You should see the variant welcome tour
- [ ] Check the tracking events. For example, `calypso_editor_wpcom_tour_open` should fire when the variant tour opens. Check paging through the slides and closing it.
- [ ] Close the tour and refresh the page. You should not see the tour.
- [ ] Open the tour manually by clicking on _Welcome Guide_ in the Editor Options menu. You should see the variant welcome tour

#### Anchor.fm flow

Run this branch in Calypso and create a new site at http://calypso.localhost:3000/new?anchor_podcast=22b6608 

- [ ] With the experiment set to **control**, open a post. You should see the existing welcome tour
- [ ] With the experiment set to **treatment**, open a post. You should see the existing welcome tour

### CODE REVIEW

**Comment by autumnfjeld** [comment]
@ramon I caught one error with some variable renaming.  Fixed [here](https://github.com/Automattic/wp-calypso/pull/49296/commits/b4a0e4908c4c22796ee6fab7bbe6f97d2b42f5f2).  This fix didn't come through in the diff when I did `arc patch D55998`.

I went a little farther and cleaned up the variable naming with the idea: https://github.com/Automattic/wp-calypso/pull/49331
1) "nux" should be used for the user preference status
2) "Guide" should be used to refer to the UI Component 
This convention mirrors the [Welcome Guide naming core](https://github.com/WordPress/gutenberg/blob/c88866cd91ea3eb7990a68978e03e2366ed7106c/packages/edit-post/src/components/welcome-guide/index.js) and could be further enforced in the ETK after the experiment.
Not a problem if we leave this hanging, as test this feature is a very labor intensive process.

**Comment by autumnfjeld** [comment]
I haven't been able to get this properly working in my sandbox. I always get shown the new Tour.  For the record:
* I applied both diffs and visually checked files in my sandbox and can see the diffs were applied
* I removed `define( 'SHOW_WELCOME_TOUR', true );` in my 0-sandbox.php
* I've set the experiment to control
yet still I always see the new Tour and cannot get the original NUX modal to show up.  I've been troubleshooting for a couple hours and will come back to this in the morning.

I can confirm on my local dev the feature is working as expected (after [this fix](https://github.com/Automattic/wp-calypso/pull/49296/commits/b4a0e4908c4c22796ee6fab7bbe6f97d2b42f5f2) with both the NUX modal and the new Tour (tracking, opening from Options Menu).

**Comment by autumnfjeld** [comment]
**Existing Welcome Tour**
- ✅  With the experiment set to control, open a post. You should see the existing welcome tour
- ✅   Check the tracking events. For example, calypso_editor_wpcom_nux_open should fire when the existing tour opens. Check paging through the slides and closing it.

- ✅   Close the tour and refresh the page. You should not see the tour.
- ✅   Open the tour manually by clicking on Welcome Guide in the Editor Options menu. You should see the existing welcome tour
   - 🛑  BUT tracking doesn't work for the manual open in my sandbox. It does in my local dev.[ But this fix ](https://github.com/Automattic/wp-calypso/pull/49296/commits/b4a0e4908c4c22796ee6fab7bbe6f97d2b42f5f2)didn't get added in the diff. 

**Variant Welcome Tour**
- ✅  With the experiment set to treatment, open a post. You should see the variant welcome tour
- ✅  Check the tracking events. For example, calypso_editor_wpcom_tour_open should fire when the variant tour opens. Check paging through the slides and closing it.
- ✅  Close the tour and refresh the page. You should not see the tour.
- ✅  Open the tour manually by clicking on Welcome Guide in the Editor Options menu. You should see the variant welcome tour
     - 🛑  BUT tracking doesn't work for the manual open in my sandbox. It does in my local dev.[ But this fix ](https://github.com/Automattic/wp-calypso/pull/49296/commits/b4a0e4908c4c22796ee6fab7bbe6f97d2b42f5f2)didn't get added in the diff. 

I'll check the Anchor.fm tests in the morning.

**Comment by ramonjd** [comment]
>  I caught one error with some variable renaming. Fixed here. 

Great stuff, thank you! I thought there was one I missed 👁️

**Comment by autumnfjeld** [comment]
@ramon 
**Anchor.fm flow**
Run this branch in Calypso and create a new site at http://calypso.localhost:3000/new?anchor_podcast=22b6608

✅  With the experiment set to control, open a post. You should see the existing welcome tour
✅  With the experiment set to treatment, open a post. You should see the existing welcome tour

While I struggled a bit with reliably clearing out settings (which makes me wary of testing results), I can say that I was never able to get to the new tour to show in the anchorfm scenario.  Only the old NUX showed, as desired.

**Review by autumnfjeld — APPROVED** [review]
Refactor looks good.

**Pull request merged**
