### PR TITLE
Add/email open graph ultimate

### PR DESCRIPTION
**Pull request by JuanLucha**
#### Proposed Changes

This PR adds the Email Opens stat graph to the Email Stats page, showing it like this:
Screenshot 2022-12-28 at 13 15 01

This is a WIP, and there are something that doesn't work for now, like clicking on a different period on the graph. This will be added in subsequent PRs. This feature is hidden behind the `newsletter/stats` feature flag.

#### Testing Instructions
1. Checkout this branch and start the application.
2. Go to a URL with this format: `calypso.localhost:3000/stats/email/open/[domain-of-your-blog]/day/[post-id]?flags=newsletter/stats`.
3. You should see the stats showing in the graph. Take into consideration that, in order to see stats, an email should have been sent when the post was created, and some followers should have open that email.
4. You can change the URL param `day` to `week` or `month` and you should see how the increments in the chart change accordingly. `year` is still WIP.

### CODE REVIEW

**Review by TimBroddin — APPROVED** [review]
For an initial PR, this looks good to me! I think you're aware of everything that still needs to be done to have this functionality working, but this can be done in subsequent PR's.

One strange this I've noticed is in the month view:

CleanShot 2022-12-28 at 13 41 12@2x

It seems like the months are being returned twice by the API:

CleanShot 2022-12-28 at 13 45 03@2x

**Comment by JuanLucha** [comment]
Indeed, @TimBroddin , seems to be something in the endpoint. We will check this out with @phcp .
Thanks for the review!

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/7697883

Thank you @JuanLucha for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/7697883).

**Pull request merged**
