### PR TITLE
Editor: use <Button borderless> for sidebar-header items.

### PR DESCRIPTION
**Pull request by mtias**
Simplify styling, better alignment of items.

Before:
image

After:
image

image

cc @aduth @kellychoffman @folletto

### CODE REVIEW

**Comment by mtias** [comment]
What do you think of simplifying the wording to be `<- Posts` instead of `<- All Posts` which has very different results with different languages?

**Comment by folletto** [comment]
> What do you think of simplifying the wording to be <- Posts instead of <- All Posts which has very different results with different languages?

Seems wise given the above. :)

**Comment by mtias** [comment]
image

:)

**Comment by aduth** [comment]
There's a bit of a shift in height when the number of drafts finishes loading:

shift

**Comment by kellychoffman** [comment]
+1 for simplifying to `Posts`

**Comment by aduth** [comment]
Can confirm that the height no longer shifts when draft count loads. There's still inconsistency with the height of the button between the post editor and My Sites, though I'm not sure if you planned to address that separately.

**Comment by mtias** [comment]
Yeah, I don't mind it much now that the buttons look the same but let's see how it feels.

**Pull request merged**
