### PR TITLE
Remove pressable banner from pricing table

### PR DESCRIPTION
**Pull request by vykes-mac**
This PR is an action item from p58i-gcf-p2 to remove the presssable banner from the pricing page

## Proposed Changes

* Remove code related to the pressable banner

## Testing Instructions

* Go to `/start/plans`
* Verify the Pressable banner is no longer present

image

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

**Review by p-jackson — APPROVED** [review]
lgtm 👍 

I also tested the stepper framework (e.g. `/setup/link-in-bio`) which also uses the `<PlansFeaturesMain>` component.

**Review by zaguiini — APPROVED** [review]
LGTM 👍

**Comment by zaguiini** [comment]
@southp we'll merge this. Let us know if you have additional feedback.

**Comment by southp** [comment]
@zaguiini Thanks for the ping. It looks perfectly done to me :)

**Pull request merged**
