### PR TITLE
Signup Actions: Remove `error` argument to `submitSignupStep` 

### PR DESCRIPTION
**Pull request by dmsnell**
While doing some unrelated work I realized with the help of @gwwar
that nothing is passing errors into the `submitSignupStep` function
and at the same time the places passing "no errors" were doing it
in three separate ways:
 - `undefined`
 - `null`
 - `[]`

In this patch I'm removing the error entirely and the corresponding
logic for handling it. If we need to pass an error someday we can
add it back in. It's probably not worth the prime second-position
in which it currently lives.

**Testing**

Audit the code, run the tests.

### CODE REVIEW

**Comment by nylen** [comment]
> I'm not sure if this fixes or even addresses the broken flow

> Audit the code. I'm confident that this is a safe change so smoke-testing is surely enough (haha last words amirite?)

Both of these things make me nervous, at the very least it would be good to test to see if this resolves the broken flow and get a review from someone who is more familiar with signup than me.

**Comment by gwwar** [comment]
@dmsnell could you add steps for the original bug? We can always summon @Automattic/flowpatrol if testing this is particularly tricky.

**Comment by dmsnell** [comment]
The original bug is to go to `get.blog` and move through the signup flow. At the point where we would choose a plan it reverts to an earlier step - this only in Firefox.

`submitSignupStep` explicitly checks for `undefined` as the error and all but two instances of it do that _or_ pass an empty list _or_ omit the prop entirely. These two cases are outliers and I wasn't sure what effect the `null` would cause because I got pretty deep and kept getting lost. That is, this is more like a janitorial PR to harmonize code with a possible side-effect of fixing a bug. I'd like to understand it better myself.

(Originally I didn't include this screen clip because I didn't want to make the qualification for this PR as the bug-fix itself, but here it is for your viewing)

brokenflow mov

**Comment by alisterscott** [comment]
I tested the Firefox bug mentioned above, but this _doesn't_ appear to fix it for me:

Steps followed in Firefox
1. Visit https://wordpress.com/start/domain-first?new=hdjshjshdj.blog
2. Go through steps and redirected back to the start

Re-tested in Firefox with this PR:
1. Visit https://calypso.live/start/domain-first?new=hdjshjshdj.blog&branch=signup/steps-undefined-not-null
2. Go through steps and still redirected back to start :(

@dmsnell is there a wp-calypso bug report for this? Would you like me to raise one?

**Comment by gwwar** [comment]
So dug a bit, and I think this is what we're calling right?
```jsx
	submitSignupStep( step, errors, providedDependencies ) {
		analytics.tracks.recordEvent( 'calypso_signup_actions_submit_step', { step: step.stepName } );

		Dispatcher.handleViewAction( {
			type: 'SUBMIT_SIGNUP_STEP',
			data: step,
			errors: undefined === errors ? [] : errors,
			providedDependencies: providedDependencies,
		} );
	},
```
From the readme it says:
```
If `errors` has a non-zero length, it will be attached to the step and the step's status will be set to `invalid` as it is added to the store.
```

I didn't look too closely but I wasn't able to find any usages of where we pass real errors, but this appears to expect an array of errors. In this case I think it's more appropriate to change `null` to `[]` and also update `errors: undefined === errors ? [] : errors,` to `errors: ! isArray( errors ) ? [] : errors,`

**Comment by dmsnell** [comment]
> So dug a bit, and I think this is what we're calling right?

That's right, @gwwar.

> I didn't look too closely but I wasn't able to find any usages of where we pass real errors, but this appears to expect an array of errors. In this case I think it's more appropriate to change null to [] and also update errors: undefined === errors ? [] : errors, to errors: ! isArray( errors ) ? [] : errors,

That seems like a reasonable change. I'll see if I can do that without making this PR grow too big.

**Comment by dmsnell** [comment]
@nylen @alisterscott and @gwwar I have updated this PR and changed its purpose. At first I was going to standardize calls to pass `[]` for `errors` but since we haven't seemed to ever pass an error I decided to remove it altogether. This was done with the help of a trivial codemod…

```js
export default function transformer( file, api ) {
	const j = api.jscodeshift;

	return j( file.source )
		.find( j.CallExpression )
		.filter( p => p.node.callee.property && p.node.callee.property.name === 'submitSignupStep' )
		.filter( p => p.node.arguments.length > 1 )
		.forEach( p =>
			( p.node.arguments = p.node.arguments.slice( 0, 1 ).concat( p.node.arguments.slice( 2 ) ) )
		)
		.toSource();
}

```

**Comment by gwwar** [comment]
Maybe loop in a few more nux folks if we're planning on ripping it out entirely. If we don't have any recent usages, I think it'd be okay to remove this.

**Comment by alisterscott** [comment]
I tested the new version of this PR and it still doesn't address https://github.com/Automattic/wp-calypso/issues/25261, but since the full e2es pass and if this means simpler, easier to understand code then I'm all for merging this 👍

**Comment by dmsnell** [comment]
Time constraints and lack of decisions means this PR is going to the bitbucket.

**Pull request closed without merging**
