### PR TITLE
Media Section: Style cleanup for action bar

### LINKED ISSUE #11834: Media Section: Action bar style adjustment
- [ ] Give more side margin to the scale range.
image

- [ ] Uneven spacing for buttons.
image

- [ ] Excessive paddings for the header for small screens
image

- [ ] There is a big gap between action bar and images
image

### PR DESCRIPTION
**Pull request by iamtakashi**
Fixes #11834

Bottom part of each screenshot is how it'd look with this PR.

Section (mobile)
mobile

Section (desktop)
large

Modal (mobile)
mobile-2

Modal (desktop)
large-2

### CODE REVIEW

**Comment by retrofox** [comment]
This branch should be targeted to `try/media-section-v2` @iamtakashi

**Comment by retrofox** [comment]
tested `width: 580px`



should we concern with these dimensions?

**Comment by gwwar** [comment]
Padding looks tight with the add url control open:
screen shot 2017-03-08 at 3 51 50 pm

**Comment by retrofox** [comment]
> Padding looks tight with the add url control open:

@gwwar let me rebase again. We've already been working on this section.

**Comment by retrofox** [comment]
After the rebase it produces a flickr switching to upload-by-URL

flickr

**Comment by gwwar** [comment]
We're getting there 😄 but this needs more polish.

I'm not seeing the flicker, but we could use some more padding in both sections. There's also some shadow going on in the modal:

screen shot 2017-03-08 at 4 06 23 pm

screen shot 2017-03-08 at 4 07 17 pm

Error States look a bit off too:

screen shot 2017-03-08 at 4 07 48 pm

screen shot 2017-03-08 at 4 08 14 pm

**Comment by retrofox** [comment]
> There's also some shadow going on in the modal:

https://github.com/Automattic/wp-calypso/pull/11932  ;')

**Comment by iamtakashi** [comment]
Good catch! I'll fix them shortly.

**Comment by retrofox** [comment]
Takashi, just FYI the issues about some shadow going on in the modal as fixed here: https://github.com/Automattic/wp-calypso/pull/11932. You shouldn't concern about this, but maybe you should update your branch.

**Comment by iamtakashi** [comment]
It was quite painful to work with but it now should be good!

**Comment by iamtakashi** [comment]
This isn't ready for review yet, it needs further work since #11932 is merged.

**Comment by gwwar** [comment]
Noticed the that mobile views could use a bit of ❤️ 

screen shot 2017-03-09 at 11 42 10 am

**Comment by gwwar** [comment]
Let's get this PR in and address some of the other issues in future PRs

**Comment by retrofox** [comment]
Thanks a lot @iamtakashi. Let me merge this one for you. 👍

**Pull request merged**
