### PR TITLE
Forms: Updated colors for Counted Textarea Component

### LINKED ISSUE #5904: Forms: Tweak Counted Textarea Footer Color
Per https://github.com/Automattic/wp-calypso/pull/5839#issuecomment-224405810, we should lighten up the background color of the `counted textarea` component.

It should match the search preview color shown here:
screen shot 2016-06-08 at 2 07 05 pm

### PR DESCRIPTION
**Pull request by roundhill**
Updated colors for the `counted-textarea` component.

screen shot 2016-06-08 at 2 46 10 pm

@drw158 

Fixes #5904

Test live: https://calypso.live/?branch=update/5904-counted-textarea-color

### CODE REVIEW

**Comment by rickybanister** [comment]
lookin good

**Comment by drw158** [comment]
alternate design that would align with the prefix component if we updated it as well:

screen shot 2016-06-09 at 12 01 24 pm
screen shot 2016-06-09 at 12 01 14 pm

@rickybanister what do you think? it passes contrast test

**Comment by dmsnell** [comment]
Code is fine, only need here is for design review 👍

**Comment by adambbecker** [comment]
@drw158: I dig the alternate design that aligns with the prefix component. The `$gray-dark` seems, for me, to put the counter on the same hierarchy as the input itself which I don't think is intended.

**Comment by rickybanister** [comment]
@drw158 I do like the slightly-lighter-than-dark-gray color.

The prefix and suffix should definitely match, those look good except for the weird mismatched left/right paddings.

**Comment by drw158** [comment]
Thanks all, colors have been updated to match https://github.com/Automattic/wp-calypso/pull/5911#issuecomment-224960073

the weird padding seems to be flexbox issue in Safari

**Comment by dmsnell** [comment]
@roundhill

**Pull request merged**
