### PR TITLE
i18n: Fix language loading race condition in local dev environment

### PR DESCRIPTION
**Pull request by akirk**
When loading a local install of Calypso with a logged in user that has set a language different than English, the UI only loads up in that language in one out of 10 reloads. This seems to be the case because `state.ui.language` is persisted on the client.

I am no expert the Calypso bootup code but with some experimenting and consulting with @Tug the suggested fix works for me. I'd appreciate any further insights on this to get this merged.

### CODE REVIEW

**Comment by Tug** [comment]
I went ahead and removed the `getCurrentLocaleSlug()` check because it is redundant with `window.i18nLocaleStrings` which is also set for server-side rendered non-engish pages (see https://github.com/Automattic/wp-calypso/blob/master/server/render/index.js#L94)

@akirk  could you check for any potential error?

**Comment by yurynix** [comment]
@akirk Could you please elaborate on steps to reproduce?

I've checked-out `master` on my machine, set my account to `Hebrew` and loaded `http://calypso.localhost:3000/log-in` 10 times, each time I got the page in `Hebrew` AFAIK that is how it should be. 

I've tested the patch as well, `http://calypso.localhost:3000/log-in` loads fine with user bootstrapped and not bootstrapped.

**Comment by yurynix** [comment]
Ok, that reproduced for me while I were testing a different issue,
It was more evident for me on `http://calypso.localhost:3000/me/account` when switched to Espanõl, I've applied the patch manually and it seems to fix it for my scenario 👍

**Comment by stephanethomas** [comment]
If I load http://calypso.localhost:3000/log-in for an account in Spanish the page is presented in the right language, but has many display issues:

screenshot

There is this warning in the browser's console in that case:

> Warning: Expected server HTML to contain a matching <svg> in <a>.

If I load http://calypso.localhost:3000/log-in/fr instead I get:

screenshot

**Comment by stephanethomas** [comment]
The change looks good. And as far I can see it works fine.

**Comment by akirk** [comment]
Thanks @yurynix for merging!

**Pull request merged**
