### PR TITLE
Lint: fix client/reader

### PR DESCRIPTION
**Pull request by bluefuton**
Part of the grand effort to fix all the eslint errors (#24504).

This PR covers client/reader/*. I'm using this to find them:

`npx eslint client/reader/* --ext js,jsx`

Remaining larger issues that we'll address in followup PRs:
- Refactor ReaderSidebar to ES6 component
- Remove componentWillReceiveProps usage
- Remove componentWillMount usage
- Use `button` element in intro banners and update pill

### CODE REVIEW

**Comment by bluefuton** [comment]
Visual fix on the intro banners needed after converting `div`s to `button`s:

screen shot 2018-07-09 at 17 56 17

The update pill arrow needs some minor tuning as well.

**Comment by bluefuton** [comment]
I'll address the button element + position fixes in a followup PR instead.

**Comment by alisterscott** [comment]
I had a click through Reader on this branch and couldn't see any obvious regressions or visual issues

**Review by alisterscott — APPROVED** [review]
LGTM

**Pull request merged**
