### PR TITLE
Add/social logos component

### PR DESCRIPTION
**Pull request by enejb**
Adds the social logo component that could be used to replace the current noticons. 

The component is created from https://github.com/Automattic/social-logos

Much of the work has been based on the current Gridicon component. 

cc: @mtias, @jasmussen, @alternatekev 

screen shot 2016-01-12 at 14 12 05

**To test:**
Go to http://calypso.localhost:3000/devdocs/design/social-logos

### CODE REVIEW

**Comment by rickybanister** [comment]
Are path and pinterest aware they have the exact same logo?

**Comment by kellychoffman** [comment]
:tada: Looks good! Can't wait to update /sharing. 

Also, there's something really nice about seeing these in alphabetical order.

**Comment by jasmussen** [comment]
Very nice work.

**Comment by mtias** [comment]
Looks good!

**Pull request merged**
