### PR TITLE
Limited Global Styles: Fix modal layout

### LINKED ISSUE #76089: Limited Global Styles: Gating modal has incorrect layout
#### Steps to reproduce

1. Create a new site and go to `/wp-admin/site-editor.php?canvas=edit`
2. Open the Styles sidebar

#### What I expected

The Global Styles gating modal should be displayed correctly:

image

#### What happened instead

The modal has an incorrect layout:

Screenshot 2023-04-21 at 16 26 09

#### Context / Source

This is probably a regression caused by a recent Gutenberg release.

### PR DESCRIPTION
**Pull request by mmtr**
Fixes https://github.com/Automattic/wp-calypso/issues/76089

## Proposed Changes

As of [Gutenberg 15.2](https://github.com/WordPress/gutenberg/pull/47426), the `Modal` component no longer renders the passed React nodes as direct children of `.components-modal__content`, effectively breaking the flex layout used by our Limited Global Styles gating modal.

To fix that, we now use a wrapper with a custom class so we can build a flex layout without relying on how Gutenberg renders the `Modal` component.

Before | After
--- | ---
image | Screenshot 2023-04-24 at 13 58 47

## Testing Instructions

- Apply these changes to your sandbox
- Create a new site and sandbox it
- Go to the site editor and open the styles sidebar
- Make sure the modal has the proper layout

### CODE REVIEW

**Comment by BogdanUngureanu** [comment]
Works as expected on desktop. There're some small issues on mobile resolutions (probably there were happening before too).

Screenshot 2023-04-24 at 17 27 27
Screenshot 2023-04-24 at 17 27 56

Notice the scrollbar and the line that cuts the close button.

**Comment by dsas** [comment]
On the vertical phone screenshot should we display the actionable 'half' of the modal above the illustrative half?

**Comment by mmtr** [comment]
Thanks @BogdanUngureanu, it should be fixed now:

Screenshot 2023-04-26 at 13 35 29 Screenshot 2023-04-26 at 13 35 46

> should we display the actionable 'half' of the modal above the illustrative half?

It's intentionally below the image so it looks similar to the Core's welcome modal:

Screenshot 2023-04-26 at 13 31 00

**Comment by BogdanUngureanu** [comment]
Thanks for the updates, Miguel. I had another look and I've noticed that the scrollbar is still appearing for iPhone 12 pro resolutions.

Maybe for low height resolutions we could:
 - Reduce the padding for `wpcom-global-styles-modal__text`
 - Remove the `margin-top: auto` on `wpcom-global-styles-modal__actions` class, this will move the CTA buttons in the visible screen.

By doing this, we will make sure that the CTA buttons are visible on the screen without scrolling.

**Comment by mmtr** [comment]
> the scrollbar is still appearing for iPhone 12 pro resolutions.

I cannot reproduce that, maybe you had some caching issues? This is how I see it:

Gutenberg 15.7.0-rc.1 | Gutenberg 15.6.2
--- | ---
Screenshot 2023-04-27 at 14 16 37 | Screenshot 2023-04-27 at 14 18 16

**Comment by BogdanUngureanu** [comment]
Oh, sorry about that. The issue is in landscape mode, where the height is small and you have to scroll the modal in order to see the upgrade buttons.

**Comment by mmtr** [comment]
Thanks for the extra info. It should be fixed now:

Screenshot 2023-04-27 at 15 34 09

**Review by BogdanUngureanu — APPROVED** [review]
Works great on most mobile devices, in landscape mode. I've noticed that for Galaxy Fold, in landscape mode, the buttons are still not visible, but I guess it's an acceptable tradeoff.

**Pull request merged**
