### PR TITLE
Email Confirmation: Use lighter background and allow notice to be dismissed

### PR DESCRIPTION
**Pull request by shaunandrews**
The current email confirmation notice is really bold, and obnoxiously "undismissable". This PR does a few things:

- Updates the `notice` component to use a `null` default prop for it's `status` prop.
- Updates the `notice` component's styles for default notices to use a slightly darker background color.
- Updates the email confirmation message to use the term "confirm" rather than "verify" to better match the emails we send.
- Updates the email confirmation message so it can be dismissed. The notice comes back if you refresh the page.

The end result looks like this:

screen shot 2016-04-11 at 12 52 24 pm

### CODE REVIEW

**Comment by melchoyce** [comment]
That looks much better.

There are a couple places where this notice appears full-width, with no margins — do you know if that's still the case?

**Comment by michaeldcain** [comment]
:shipit:

**Comment by mtias** [comment]
The only thing here is whether people were relying on `is-info` being the default before for notices.

**Comment by shaunandrews** [comment]
> There are a couple places where this notice appears full-width, with no margins — do you know if that's still the case?

Yup, there's at least one: `/sites/`

screen shot 2016-04-12 at 10 38 05 am

**Comment by mtias** [comment]
More here:

image

Which doesn't look too good.

**Pull request merged**
