### PR TITLE
Persistent Launch Button: enable in all environments

### PR DESCRIPTION
**Pull request by ciampo**
#### Changes proposed in this Pull Request

* Renamed `gutenboarding/persistent-launch-button` feature flag to `create/persistent-launch-button`
* Enable `create/persistent-launch-button` flag on all environments.
* This will show the "Launch" button for all unlaunched sites when editing a page/post in the block editor in calypso. 

Fixes p9Jlb4-1SN-p2
Related: https://github.com/Automattic/wp-calypso/pull/46674, https://github.com/Automattic/wp-calypso/pull/46796

### CODE REVIEW

**Review by yansern — APPROVED** [review]
Approved. Just waiting for the right moment to merge.

**Comment by ciampo** [comment]
@razvanpapadopol PR is ready to be merged

**Comment by ciampo** [comment]
Renamed the flag to `create/persistent-launch-button` as suggested in https://github.com/Automattic/wp-calypso/pull/46686#discussion_r514952668 

(cc @razvanpapadopol )

**Comment by ciampo** [comment]
Rebased on top of master

**Pull request merged**
