### PR TITLE
E2E: Update the configuration file.

### PR DESCRIPTION
**Pull request by kwight**
This PR updates the e2e config file with a new key.

**Testing Instructions**
* Use the new key to decrypt the e2e config file, following instructions at PCYsg-vnR-p2

### CODE REVIEW

**Review by bsessions85 — APPROVED** [review]

**Comment by kwight** [comment]
@bsessions85 I see the e2e tests are failing – would this sort itself out on merge, or is there CI setup involved in changing this key?

**Comment by bsessions85** [comment]
@kwight oh yeah, there is a CI step. I'll have to do some searching since I don't know how TC is set up.

**Comment by bsessions85** [comment]
@scinos Where would I update `CONFIG_E2E_ENCRYPTION_KEY`? I don't see it in TC, but I am also not sure I have the right permissions.

**Comment by scinos** [comment]
@bsessions85 @kwight It is defined in TeamCity in https://teamcity.a8c.com/admin/editProject.html?projectId=calypso&tab=projectParams. I can change it, but I can't give you permissions (you need to post a Systems Requests asking for them)

**Comment by kwight** [comment]
@scinos Ah OK, makes sense – the new key is currently in SS, and just DM me if you need the old one for any reason. 👍

**Pull request merged**
