### PR TITLE
Add anchor to quicklinks

### PR DESCRIPTION
**Pull request by mreishus**
#### Changes proposed in this Pull Request

* In quicklinks, add a link to anchor.fm

#### Testing instructions

* Visit calypso homepage
* Check quicklinks for a link to anchor.fm

Related to 514-gh-Automattic/dotcom-manage

### CODE REVIEW

**Comment by kwight** [comment]
@mreishus I believe that logo is their old branding; it's more of a swoosh thing now (they must have a media page somewhere with new assets).

Screen Shot 2021-03-03 at 12 21 37 PM

**Comment by mreishus** [comment]
Updated logo

**Review by kwight — APPROVED** [review]
:shipit:

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/5557790

Thank you @mreishus for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/5557790).

**Pull request merged**
