### PR TITLE
State: Cleanup unused site products cleanup state

### PR DESCRIPTION
**Pull request by tyxla**
#### Changes proposed in this Pull Request

This PR cleans up the unused site products cleanup state that has been unused since its creation in #40306.

#### Testing instructions

Verify Calypso builds, tests pass and the removed code is not in use.

### CODE REVIEW

**Review by DavidRothstein — COMMENTED** [review]
I don't have a strong opinion on this, but my sense is that it would be better to leave it as is, for API completeness -- as well as to keep things in sync with the site plans code in `client/state/sites/plans`.

It also makes me wonder if this **should** have been used somewhere along the way for the Jetpack plans page, even if it currently isn't....

**Comment by tyxla** [comment]
Thanks for taking a look @DavidRothstein! TBH I'm generally fine to leave things as they are, but if something hasn't been used since its creation, it usually never gets used and just remains dead code that we often end up shipping. If we're considering using this one, I'm happy to close the PR - just let me know.

**Comment by DavidRothstein** [comment]
I tested a bit and it seems like every time you visit the Jetpack plans page, it already fetches updated product data from the server.  Since that's the main page where this would matter, I guess that means `refreshSiteProducts()` isn't needed currently.  I could still imagine it being needed in the future, but if you feel like it is better to remove it, that is definitely OK with me.  Thanks!

**Comment by tyxla** [comment]
> I tested a bit and it seems like every time you visit the Jetpack plans page, it already fetches updated product data from the server. Since that's the main page where this would matter, I guess that means `refreshSiteProducts()` isn't needed currently. I could still imagine it being needed in the future, but if you feel like it is better to remove it, that is definitely OK with me. Thanks!

We're generally trying to keep the codebase clean of unused code; we can always dig it and re-add it if necessary. 

Thanks for taking a look!

**Pull request merged**
