### PR TITLE
A4A > Migrations: Implement card view for commissions & mobile fixes

### PR DESCRIPTION
**Pull request by yashwin**
Closes https://github.com/Automattic/automattic-for-agencies-dev/issues/1463

## Proposed Changes

This PR:

- Implements a card view for commissions on mobile screens.
- Creates component for card view
- Updates the Layout components to support mobile screens.

Note: Clicking on the `Tag sites for commissions` button does nothing. It is being implemented here: https://github.com/Automattic/wp-calypso/pull/96273

## Why are these changes being made?

* To provide a better mobile experience on the Migrations page.

## Testing Instructions

* Open the A4A live link
* Go to Migrations: Commissions > Switch to any mobile screen > Verify everything looks good.
* Go to Migrations: Payment Setting > Verify everything looks good. 

Screenshot 2024-11-13 at 10 32 00 AM

Screenshot 2024-11-13 at 1 16 36 PM

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Review by madebynoam — APPROVED** [review]
Tested it out. Lgtm! Thanks, Yashwin!

**Review by jkguidaven — APPROVED** [review]
Works great! code LGTM 👍

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/17002590

Some locales (Hebrew, Japanese) have been temporarily machine-translated due to translator availability. All other translations are usually ready within a few days. Untranslated and machine-translated strings will be sent for translation next Monday and are expected to be completed by the following Friday.

Thank you @yashwin for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/17002590).

**Pull request merged**
