### PR TITLE
Adds new Blaze origin for atomic sites using classic view

### PR DESCRIPTION
**Pull request by sbarbosa**
With the work done in the menu unification, we now have the possibility of Atomic sites using the Jetpack Blaze version of the dashboard. We want to distinguish those cases from regular self-hosted jetpack-connected sites.

## Proposed Changes
* Added the new Blaze origin `jetpack-atomic` (we use the site option `is_wpcom_atomic` to differentiate atomic sites)
* Fixed some events that triggered a `calypso_dsp_widget_start` (Blaze create campaign modal) when they redirected the user to the Blaze landing page.
* Fixed the entry point in the Stats module for self-hosted sites. I found this error while working on this change, if you click the Promote button shown in the stats module page `stats/day/posts/{SITE}`, you are not getting redirected to the Jetpack Blaze dashboard.

## Testing Instructions

* Open the browser network console, and filter by all request with name `t.gif`
* Navigate to your site's home page (`home/{SITE}`)
* Click on the `Promote with Blaze` quick link, and verify that we trigger a event with the name `calypso_customer_home_my_site_quick_link_blaze`
* Go to the posts page, and click on the Promote with Blaze option for any of your posts
* Verify that the event `calypso_dsp_widget_start ` is triggered with the entrypoint `posts-meatball-menu`
* Click on the Stats, scroll down and click on View details of the Posts & Pages section
* Find a time period were you have some stats, and hover over any of the posts and click the Promote button.
* Verify that the widget is loaded and that the event `calypso_dsp_widget_start ` is triggered with the entrypoint `mysites_stats_posts-and-pages_speaker-button`

**Test the new origin, and specific changes of Jetpack Stats fix in entry point**

You will need a local jetpack environment working.

* Check out this branch
* In a terminal navigate to `wp-calypso/apps/blaze-dashboard`
* Execute `BLAZE_DASHBOARD_PACKAGE_PATH=/PATH_TO_JETPACK_REPO/projects/packages/blaze yarn dev`
You need to change `PATH_TO_JETPACK_REPO` with the path of the jetpack local repository
* Open another terminal and navigate to `wp-calypso/apps/odyssey-stats`
* Execute `STATS_PACKAGE_PATH=/PATH_TO_JETPACK_REPO/projects/packages/stats-admin yarn dev`
You need to change `PATH_TO_JETPACK_REPO` with the path of the jetpack local repository
* In another console, go to the jetpack repository and execute `jetpack build` and then choose plugins -> jetpack. Choose to compile with all of its dependencies. 
* Open a tunnel pointing to your local jetpack environment and access the wp-admin page using the public name of the tunel
* Go to Jetpack->Stats, scroll down and click on View details of the Posts & Pages section
* Find a time period were you have some stats, and hover over any of the posts and click the Promote button.
* Verify that you are correctly redirected to the Jetpack Blaze page -> Create campaign widget for the post you choose.
* In your editor, open [this file](https://github.com/Automattic/jetpack/blob/97931d43cc1d9b8b59f6bd832b250e9b4e3f3a7c/projects/packages/blaze/src/class-dashboard-config-data.php#L76) and add this additional line (this will set your site as atomic):
```
'is_wpcom_atomic' => true,
```
* In your browser, go to Tools->Advertising and verify that thevents we are triggering have the `jetpack-atomic` origin.

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Comment by sbarbosa** [comment]
Hi @kangzj! I added you as a reviewer because I found a bug one in the Stats module. 
In Jetpack, if you click the promote button that we show when you hover over the post section, the user is not getting redirected to Blaze.

Screenshot 2024-03-26 at 4 43 08 PM

I would appreciate your opinion on the change and help testing it. I tested this in a self-hosted site, but I was not able to test it in Atomic (the sandbox didn't work). I ran tests hardcoding the `is_wpcom_atomic`, and it worked, but it would be nice to fully test without the hardcode.

**Review by therocket-gr — APPROVED** [review]
tested locally. i spotted all the correct flags and origins in the t.gif request
code changes LGTM

**Comment by kangzj** [comment]
Hi @sbarbosa sorry, I have been busy wrapping up a project during the last couple of days. I'll take a closer look later today.

**Review by timur987 — APPROVED** [review]
Thanks, @sbarbosa!

Changes LGTM and work as advertised!
Nicely done! 🎉

**Comment by kangzj** [comment]
Note: You should be able to test on a real atomic sites following instructions at: p9o2xV-1r2-p2

**Comment by kangzj** [comment]
>  In Jetpack, if you click the promote button that we show when you hover over the post section, the user is not getting redirected to Blaze.  @sbarbosa

The problem is Stats and Blaze are different apps in Jetpack, which means the Blaze routes don't exist in Stats. As a result, I don't think it is possible to use `page` to open a modal like this:

https://github.com/Automattic/wp-calypso/blob/680131efa7f09ce76465b32a9f7d46eff394fb83/client/lib/route-modal/use-route-modal.tsx#L40

Instead, we need to either register the modal in Stats [routes](https://github.com/Automattic/wp-calypso/blob/trunk/apps/odyssey-stats/src/routes.ts), or we could redirect with absolute path (e.g. `/wp-admin/tools.php?page=advertising#!/advertising/:siteSlug`) set to `location.href`. I would lean to the latter approach if you ask me, as if we register the modal, it will probably bloat the Stats bundle quite a bit, and also it blends the boundary of the apps, which doesn't seem ideal to me.

BTW the changes looks good to me! I didn't test thoroughly tho.

**Comment by sbarbosa** [comment]
Thanks for the feedback @kangzj. 

> Instead, we need to either register the modal in Stats [routes](https://github.com/Automattic/wp-calypso/blob/trunk/apps/odyssey-stats/src/routes.ts), or we could redirect with absolute path (e.g. /wp-admin/tools.php?page=advertising#!/advertising/:siteSlug) set to location.href

Yes, I didn't want to include the blaze modal inside Stats. It will increase the size of the stats app, and we don't really need it. I took the approach you mentioned, the hook `useOpenPromoteWidget` it is checking for the config variable `is_running_in_jetpack_site`, and for that case is doing a redirection. You can check that part [here](https://github.com/Automattic/wp-calypso/pull/88858/files#diff-185dc4e7ae96066f1b5b87784c498cda8df6e8e17def1c6cb2075d7780634ef6L21-L25.)

**Pull request merged**
