### PR TITLE
Build: Do not modify host environment prebuild

### PR DESCRIPTION
**Pull request by sirreal**
I explored not removing `node_modules` before docker build in #19801. This PR goes further.

There's no reason to modify the local environment to build a Docker image. The point of Docker is isolation, we should only bring the parts of our local environment that are relevant to the Docker context.

This PR removes all cleaning scripts from `prebuild-docker` and applies synonymous rules via `.dockerignore`. The end result in the Docker context is the same, but the local envirnoment is untouched, allowing continued and uninterrupted development.

## Testing
1. A simple way to verify is by creating matching files locally and adding `RUN ls` instructions to the `Dockerfile` at the correct place. See the example below.
1. Verify that these rules are synonymous to the `distclean` script currently in place:

https://github.com/Automattic/wp-calypso/blob/e2ce0753730280b5dd0343d82f4c04f1e213413b/package.json#L196-L203

## Example

I've applied this patch:

```patch
diff --git a/Dockerfile b/Dockerfile
index fb92cb0ea6..9012a2ff3a 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -36,6 +36,7 @@ RUN        true \
 # This contains built environments of Calypso. It will
 # change any time any of the Calypso source-code changes.
 COPY       . /calypso/
+RUN        COLUMNS=1 ls public
 RUN        true \
            && CALYPSO_ENV=production npm run build \
            && chown -R nobody /calypso \
```

The run `NODE_ENV=production npm run build`. Compare the output:

### Host environment:

```
$ COLUMNS=1 ls public

audio
directly.css
editor.css
fonts
images
manifest.json
sections
sections-rtl
style-debug-rtl.css
style-debug.css
style-debug.css.map
style-rtl.css
style.css
tinymce
```

### Docker

```
Step 10/13 : RUN COLUMNS=1 ls public
 ---> Running in 6d85cb6a0f94
audio
fonts
images
manifest.json
sections
sections-rtl
tinymce
```

## Follow up
Much of our `.gitignore` should be added to `.dockerignore`.

Supersedes #19801

### CODE REVIEW

**Comment by ockham** [comment]
Ooh, I like that approach!

**Comment by ockham** [comment]
The downside is that we now have to maintain _two_ lists of things to clean: `.dockerignore`, and the `clean` commands.

Can we make our `clean` script use information from `.dockerignore`?

**Comment by sirreal** [comment]
> Can we make our clean script use information from `.dockerignore`?

Maybe, but that could easily be painful down the road. There are things that we may end up adding to the `.dockerignore` that we don't want to remove on `clean`, plus `.dockerignore` implements a special syntax that would be error prone and painful to implement in our clean script.

It's a lot like `.gitignore`, but we don't leverage that from scripts either.

**Comment by samouri** [comment]
I got the same file output after doing the `ls`'s you suggested in testing instructions.
I've also tested the docker image and LGTM.


Thank you for this PR @sirreal!! Its so much nicer running `npm run build-docker` and maintaining my build files for dev.

**Comment by sirreal** [comment]
Build failed, it's unclear why. See take 2: #20096

**Comment by sirreal** [comment]
Successfully deployed now via #20096

**Pull request merged**
