### PR TITLE
Theme Tiers: Enable in all Calypso envs

### PR DESCRIPTION
**Pull request by rcrdortiz**
Related to:
- https://github.com/Automattic/dotcom-forge/issues/5387

## Proposed Changes

* Enabled theme tiers in all Calypso envs

## Testing Instructions
* Run `https://github.com/Automattic/dotcom-forge/issues/5387

* Checkout this branch locally.
* Run this command: `yarn feature-search themes/tiers`
* You should see that the feature is only enabled in development.

Screenshot 2024-01-30 at 15 52 24

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

**Review by mmtr — COMMENTED** [review]
We also need to add it to `test.json`

**Comment by mmtr** [comment]
Are E2E tests are failing because we need to deploy first the backend changes?

**Comment by Copons** [comment]
> Are E2E tests are failing because we need to deploy first the backend changes?

Nay, it is a real fail and the solution is (wait for it) deleting the failing test! 💥 

This is the failing test:
https://github.com/Automattic/wp-calypso/blob/22e755ce04344110be4561c220ca97141605994f/test/e2e/specs/appearance/theme__popover-preview.ts#L55-L59

`clickPopoverItem` opens the theme card's More menu popover, which we have removed within the Tiers project to reduce our reliance on `theme-options.js`.

Demo sites are still accessible from the Theme Details page, but the test is not needed anymore.

Before release, we should quickly remove the test and the helpers here:
https://github.com/Automattic/wp-calypso/blob/22e755ce04344110be4561c220ca97141605994f/packages/calypso-e2e/src/lib/pages/themes-page.ts#L20-L23

https://github.com/Automattic/wp-calypso/blob/22e755ce04344110be4561c220ca97141605994f/packages/calypso-e2e/src/lib/pages/themes-page.ts#L97-L113

**Comment by mmtr** [comment]
> we should quickly remove the test and the helpers here:

Done in https://github.com/Automattic/wp-calypso/pull/87014

**Comment by rcrdortiz** [comment]
> We also need to add it to `test.json`

Why is this? As far as I can see we haven't added any of these features to `test.json`:
- themes/block-theme-previews-premium-and-woo
- themes/discovery
- themes/display-thank-you-page-for-bundle
- themes/subscription-purchases
- themes/text-search-lots
- themes/assembler-first
- themes/tiers

What makes `themes/tiers` different from the rest of features?

**Comment by mmtr** [comment]
I don't know about the other features, we probably missed them, but the `test.json` file is the config used by unit/integration tests, so we should enable the flag there too to ensure the tests are checking the right logic.

**Comment by rcrdortiz** [comment]
> I don't know about the other features, we probably missed them, but the `test.json` file is the config used by unit/integration tests, so we should enable the flag there too to ensure the tests are checking the right logic.

Updated `test.json`

**Comment by mmtr** [comment]
Seems we need to fix some unit tests that were relying in the old UI.

**Comment by Copons** [comment]
@rcrdortiz just a quick reminder to update your local copy after my merge (93228b1)

**Review by mmtr — APPROVED** [review]

**Pull request merged**
