### PR TITLE
Staging Sites: Disable ellipsis menu link for Pro sites

### PR DESCRIPTION
**Pull request by danielbachhuber**
Fixes https://github.com/Automattic/dotcom-forge/issues/2128

## Proposed Changes

Disables the 'Staging site' link for Pro sites:

image

The 'Staging site' link remains for Business sites:

image

## Testing Instructions

1. Navigate to `/sites`.
2. Click on the ellipsis menu for a Pro site and verify the 'Staging site' link doesn't appear.
3. Click on the ellipsis menu for a Business site and verify the 'Staging site' link does appear.

### CODE REVIEW

**Review by katinthehatsite — APPROVED** [review]
Works as expected for me. It is using the same approach as in [Staging Sites: Hide staging sites module on Pro Plan](https://github.com/Automattic/wp-calypso/pull/75127) so definitely makes sense from the consistency point of view.

**Review by katinthehatsite — COMMENTED** [review]
I noticed that there was a dependency missing on[ line 314](https://github.com/Automattic/wp-calypso/pull/75582/files#diff-173bec7d847197dc6a90c47661016102ba95728dab618e17b774c11c7ed1994cR314) in the React hook `useMemo` so I added it in my commit. Other than that, all good.

**Review by sejas — APPROVED** [review]
Works as expected 👍

**Comment by danielbachhuber** [comment]
> I noticed that there was a dependency missing on[ line 314](https://github.com/Automattic/wp-calypso/pull/75582/files#diff-173bec7d847197dc6a90c47661016102ba95728dab618e17b774c11c7ed1994cR314) in the React hook `useMemo` so I added it in my commit. Other than that, all good.

@katinthehatsite Thanks for catching that!

**Pull request merged**
