### PR TITLE
Exposes all Block source files via module entry

### PR DESCRIPTION
**Pull request by getdave**
To allow the JP Blocks to be consumed in their raw form (there are use cases for this - please ask the author) it’s useful to export the unbuilt modules. 

There is no standard for this but both [Webpack](https://webpack.js.org/guides/author-libraries/#final-steps) and [Rollup](https://github.com/rollup/rollup/wiki/pkg.module) support the “module” entry in `package.json`.

This PR adds 

* a file to re-export all the source modules 
* a `module` entry in the `package.json`

#### Todo

- [ ] Explore how to test ability to consume the Block module srcs as an npm module. For example `npm link` might be a good option for testing locally.

#### Testing instructions

None yet.

### CODE REVIEW

**Comment by simison** [comment]
Related convo p1552482105139300-slack-jetpack-gutenberg

I think we'll revisit this once blocks are moved to Jetpack-repo and if I understood correctly, nobody is blocked by this right now?

Sorry for late reply here, I've been AFK. :-)

**Comment by getdave** [comment]
> we'll revisit this once blocks are moved to Jetpack-repo

@simison Can we re-review this now?

**Comment by getdave** [comment]
@simison Could we move this PR to target?

https://github.com/Automattic/jetpack/tree/master/extensions

**Comment by getdave** [comment]
Closed. Jetpack no longer exposes Blocks as a package.

**Pull request closed without merging**
