### PR TITLE
Activity Log: Discard `isDiscarded`

### PR DESCRIPTION
**Pull request by dmsnell**
We have been conditionally rendering events in the Activity Log based
on whether a previous Rewind operation (restore) has _undone_ the
appearance that the event ever occured. That is, imagine that we restore
a site to a point before a post was published. For all practical
purposes that post was never actually published; it would appear in a
disabled state as "discarded" by the restore.

This UI feature is helpful but as we start to implement the ability to
perform partial restores on a site the complexity involved in
maintaining this property surges. Events depend on specific parts of
a partial restore and it's not trivial to know what parts those are.
That is, the post is not discarded by a theme restore, but it would be
discarded by a database restore. Likewise a media item depends on both
the database _and_ the filesystem restores.

Therefore we have decided to remove this calculation for now and stop
showing it in the UI. At some point in time we may bring it back but for
now for practical purposes we are eliminating it in order to remove the
obstacle for moving forward as a project.

Rip. It. Out.

**Testing**

Smoke-test the changes please. We need to verify that there are no longer
any traces of `isDiscarded` in the app. That means we need to test API
calls, restores, and any activity with banners that previously recalculated
the `isDiscarded` state of an event.

**In Master**
withdiscarded mov

**In this PR**
withoutdiscarded mov

Note how the discarded events toggle between disabled and normal states.

### CODE REVIEW

**Comment by beaulebens** [comment]
Can you please post screenshots of before/after so we know what to look for?

**Comment by coderkevin** [comment]
Sorry if I'm being dense here, but what do I have to do to enable the Rewind feature?
stats_ _coderkevin_ _wordpress_com

**Comment by keoshi** [comment]
@coderkevin Check if your site is eligible on P9rlnk-8y-p2 and feel free to ask any additional questions on that P2.

**Comment by coderkevin** [comment]
Hmm, this was strange. I clicked through the security options on the jetpack plan and now my activity log looks completely different.

**Comment by coderkevin** [comment]
stats_ _coderkevin_mystagingwebsite_com_at_pressable_ _wordpress_com

**Comment by coderkevin** [comment]
Okay, all seems to be working now.

**Pull request merged**
