### PR TITLE
Border radius changes for cloud.jetpack.com

### PR DESCRIPTION
**Pull request by scottsweb**
#### Changes proposed in this Pull Request

* Implement sharp corners on all cards
* Implement 3px border radius on buttons

p6TEKc-3Pn-p2#comment-8096

#### Testing instructions

* Use `yarn run start-jetpack-cloud`  and add `jetpack.cloud.localhost` to your hosts file
* Visit: http://jetpack.cloud.localhost:3000/
* Test the following changes:

**Before cards:**

Screenshot 2020-09-07 at 11 29 21

Screenshot 2020-09-07 at 11 47 47

**After cards:**

Screenshot 2020-09-07 at 11 37 56

Screenshot 2020-09-07 at 11 50 12

**Before badges:**

Screenshot 2020-09-07 at 11 39 43

**After badges:**

Screenshot 2020-09-07 at 11 47 17

**After buttons:**

Screenshot 2020-09-07 at 12 33 08

Possible enhancement could be to move these to some CSS variables?

### CODE REVIEW

**Comment by scottsweb** [comment]
cc @Automattic/jetpack-design

**Comment by folletto** [comment]
Looks good.

Just a question: can't we define a `jetpack-corners-sharp` and `jetpack-cormers-soft` variables for these, instead of having in the absolute values?

**Review by keoshi — APPROVED** [review]
This is looking good. I personally feel like a softer card is more user-friendly, but it's also a deviation from our components so in this case I'm all for consistency.

> Possible enhancement could be to move these to some CSS variables?

Yes, please!

**Comment by scottsweb** [comment]
Updated.

**Review by keoshi — APPROVED** [review]
Looking sharp! Ship it.

**Pull request merged**
