### PR TITLE
Add instruction modal for locked google domains

### PR DESCRIPTION
**Pull request by candy02058912**
> [!WARNING]  
> Dependent on this PR: https://github.com/Automattic/wp-calypso/pull/80007

Fixes https://github.com/Automattic/dotcom-forge/issues/3295

## Proposed Changes

* Add instruction modal on how to unlock

https://github.com/Automattic/wp-calypso/assets/6586048/3a1391e1-37a3-469f-a6d7-e3eb8144697b

## Testing Instructions

* Go to `/setup/google-transfer/domains`
* Enter a locked domain
* See if "How to unlock" link renders

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

**Comment by renancarvalho** [comment]
Resolved the merge conflict and pushed 'how to unlock' correct color

**Review by alshakero — APPROVED** [review]
LGTM!

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/8660942

Hi @candy02058912, could you please edit the description of this PR and add a screenshot for our translators? Ideally it'd include this string: `How to unlock`

Thank you in advance!

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/8660942).

**Pull request merged**
