### PR TITLE
composite-checkout: Account for product volume when highlighting discounts

### PR DESCRIPTION
**Pull request by nbloomf**
#### Changes proposed in this Pull Request

* Depends on D44319-code, which exposes the "original subtotal" for each line item in the cart so we can show the correct original price for products with volume (e.g. gsuite).

#### Testing instructions

* Enter checkout with multiple gsuite licenses, as well as the discounted price. (Unfortunately I have not figured out how to trigger this.) You should see the correct pre-discount price in the gsuite line item.

### CODE REVIEW

**Comment by sirbrillig** [comment]
Looks good to me. I somehow also am not able to get a discount to come from the server any more, even though it's definitely showed up previously. 🤔 

Pinging @stephanethomas for a test in case you're able to get a discount to appear.

**Comment by stephanethomas** [comment]
As mentioned on Slack, the two-month discount is only available for new purchases, i.e. when a user purchases a new G Suite account (with whatever number of licenses). This discount won't be applied when adding extra licenses.

I gave this pull request and patch a try, and the right amount for the original price is indeed displayed in the `Your order` section. The `Discount for first year` mention is not shown when purchasing more than one license though.

This is unrelated to your changes but there are still issues when applying coupons though:

PROBLEM

The `$-12` discount is assigned to the coupon whereas it should not be the case. It's even more disturbing when purchasing multiple licenses as the coupon amount would no longer be negative (`$48`). I think it's a known issue, I just wanted to mention it to make sure it is tracked.

Finally, I have encountered again this strange behavior when I clear the shopping cart by removing the last item inside that cart: I'm redirected to the Plans page but the cart is still present. I was able to start again the purchase flow again, and ended up in the checkout with both the former and new G Suite mailboxes.

**Comment by sirbrillig** [comment]
> Finally, I have encountered again this strange behavior when I clear the shopping cart by removing the last item inside that cart: I'm redirected to the Plans page but the cart is still present. I was able to start again the purchase flow again, and ended up in the checkout with both the former and new G Suite mailboxes.

Thanks! This was my fault. Should be fixed by https://github.com/Automattic/wp-calypso/pull/42948

**Comment by sirbrillig** [comment]
Approving conditionally, but there are some failing tests and I think it might be worth looking into the "Discount for first year" notice.

**Comment by nbloomf** [comment]
Finally got the discount to appear for me- turns out it only works if the API is not sandboxed.

Here's what it looks like now- @sirbrillig the last commit could use a second pair of eyes to check that it makes sense.

One email:

Screen Shot 2020-06-03 at 2 10 45 PM

Two emails:

Screen Shot 2020-06-03 at 2 10 36 PM

**Pull request merged**
