### PR TITLE
Theme Showcase Update logged out Theme Showcase header tagline UI

### PR DESCRIPTION
**Pull request by taipeicoder**
## Proposed Changes

As discussed in pdyEEc-xW-p2#comment-667 and p1681939479364529-slack-C048CUFRGFQ, update the logged out Theme Showcase header so that:

1. The word "install" changes to "activate"
2. The tagline text and line-height increase from 16px to 18px, and 24px to 26px respectively.

| Before | After |
| --- | --- |
| Screenshot 2023-04-21 at 10 11 52 AM | Screenshot 2023-04-21 at 10 06 22 AM |

## Testing Instructions

* Head to the logged out Theme Showcase.
* Ensure that the updates are as described as above. 

## Pre-merge Checklist

- [x] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [x] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [x] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [x] Have you checked for TypeScript, React or other console errors?
- [x] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [x] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [x] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

**Review by arthur791004 — APPROVED** [review]
LGTM 👍 Let's wait for the translation.

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/7937107

Thank you @taipeicoder for including a screenshot in the description! This is really helpful for our translators.

**Review by okmttdhr — APPROVED** [review]
💯

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/7937107).

**Pull request merged**
