### PR TITLE
Comments: Replace user more info with a popover

### LINKED ISSUE #18596: Comments: refine animation for revealing user info
When revealing the user info panel on an expanded comment, the scaling animation feels a bit off. 

wonky animations

Could we either:
- Remove the animation 
- Or change the animation to expand the content area and quickly fade the user info in 

@folletto - Out of curiosity is there any standard animation for revealing content in Calypso?

### PR DESCRIPTION
**Pull request by Copons**
Closes #18596

Move the `CommentDetail`'s "User More Info" away from a box inside the details and into an `InfoPopover`.

| Before | After |
| --- | --- |
| screen shot 2017-10-10 at 14 23 51 | screen shot 2017-10-11 at 11 35 36 |

### Variations

screen shot 2017-10-10 at 14 15 46 screen shot 2017-10-10 at 14 16 02

### Information

I've opted for moving the More Info code into its own file for clarity (thus the big changed LOC).
This will inevitably clash with the ongoing [Redux refactor](https://github.com/Automattic/wp-calypso/pull/18406), but at the same time won't add any more hurdles after fixing the conflicts.

### CODE REVIEW

**Comment by folletto** [comment]
Looks good to me 👍 

—

I mentioned to @megsfulton that we might need to add a label later for clarity as the (i) alone doesn't feel too clickable. Not sure if it could be part of this PR, I'm considering something like:

> User Options (i)

Or something similar, but I'll leave up to her as she has the full picture of also future designs. :)

**Comment by kwight** [comment]
What do we use to determine button colours? I felt like the "Block User" button should be red?..

**Comment by megsfulton** [comment]
@folletto trying to work in a label in the next iteration. As @kwight pointed out we have the pending label next to it right now which is making things cramped on mobile. 

@Copons could we use the regular button instead of the compact button and get rid of the icon in the button? 

>What do we use to determine button colours? I felt like the "Block User" button should be red?..

I think the fully red button is a tad too much for this one. We could consider using the gray button w/ the red text that's in the dev docs. If we did that though I don't think we'd want the "Unblock user" button to be red, I think we'd want to toggle it back to the normal style. 

screen shot 2017-10-10 at 10 41 47 am

**Comment by Copons** [comment]
Block User button updated:

screen shot 2017-10-11 at 11 35 36
screen shot 2017-10-11 at 11 36 44

**Comment by folletto** [comment]
> folletto trying to work in a label in the next iteration. As kwight pointed out we have the pending label next to it right now which is making things cramped on mobile.

Yep I understand. Thanks for trying to work that in — will help a huge deal. :)

> We could consider using the gray button w/ the red text that's in the dev docs. If we did that though I don't think we'd want the "Unblock user" button to be red, I think we'd want to toggle it back to the normal style.

💯

**Comment by megsfulton** [comment]
Button looks good! 

When I tested on mobile, if the popover pops down and the card is near the bottom of the screen it can cover up the success message. 

img_9970

**Comment by kwight** [comment]
> When I tested on mobile, if the popover pops down and the card is near the bottom of the screen it can cover up the success message.

Ha, I noticed that too, but figured it could be dealt with later in a review of how we use those notifications (tl;dr, I think we should be using way less of them). I don't think we need to block this PR because of it? Love the button now <3

**Comment by Copons** [comment]
Here you go (012657a):

screen shot 2017-10-11 at 17 55 12

**Comment by Copons** [comment]
I'm not sure of the status of the info button label, but I'll ship this PR anyway because, compared to the current design, the button discoverability isn't changed at all.

**Pull request merged**
