### PR TITLE
ThemesListFetcher: Fix componentWillReceiveProps; Drop `themes-last-query` state subtree

### PR DESCRIPTION
**Pull request by ockham**
Also, remove `key` prop from theme showcase's single-site mode. This was used to force `theme-list-fetcher` to update on site change. However, this was only required because `theme-list-fetcher`'s `componentWillReceiveProps` method had some funky checks which are now fixed.

Turns out we can drop the entire `themes-last-query` state subtree and replace it by more common selectors.

To test:
* In the theme showcase, switch back and forth between different sites (including Jetpack ones). Verify that the correct themes are shown. Furthermore, verify that searching and filtering still works fine.

Required for #9218

### CODE REVIEW

**Comment by ockham** [comment]
At this point, I'm starting to wonder if we can actually drop `themes-last-query` altogether. I don't see much of it used that couldn't probably be replaced by simpler selectors.

**Comment by ockham** [comment]
cc @mcsf for review 😄

**Comment by ockham** [comment]
Thanks a lot!

**Comment by mcsf** [comment]
Steve beat me to it :D but I'll say 🚢 !

**Pull request merged**
