### PR TITLE
Payments management: add flag for new payment methods UX development

### LINKED ISSUE #47929: Payment Methods: add PaymentMethodForm and feature flag
See: #47516

- Create update/payment-methods feature flag (enabled in development)
- Create `PaymentMethodForm` component with current logic of `CreditCardForm` and add to `EditCreditCardDetails` component (using feature flag)

### PR DESCRIPTION
**Pull request by fditrapani**
This is a second take from this PR https://github.com/Automattic/wp-calypso/pull/47932. In this version, rather than duplicating a set of components, I've moved or renamed them and used the flags to display the differences. 

#### Changes proposed in this Pull Request

This PR adds new generic payment method components in preparation for us adding additional payment method options for existing purchases. A couple notes about the PR:
- Adds a new config flag `purchases/new-payment-methods`, enabled on dev, which allows us to ship regularly to production behind the scenes. 
- Updated instances of "edit" to "change" to match our UI closer. 
- Moved the Add and Change payment method components into the `manage-purchase` folder because that's where these components are accessed from. 
- I moved and renamed `CreditCardForm` to `PaymentMethodForm` to the purchases folder since it's primarily used by those components.

**Before**
image

**After**
image

#### Testing instructions

* Add `flags=purchases/new-payment-methods` query string if you're not testing locally
* Visit purchases screens at the site and account level
* Start by visiting the payment method tab and click "Add payment method" button. Confirm that you see the credit card form and the page title says "Add Payment Method". 
* Sandbox to confirm that you can actually add the card.
* Visit the manage purchase screen for an existing purchase that doesn't have a payment method.
* Click on "Add payment method" and confirm that you see the credit card form and the page title says "Add Payment Method".
* Sandbox to confirm that you can actually add the card.
* Visit the manage purchase screen for an existing purchase that does have a payment method attached. 
* Click on "Change payment method" and confirm that you see the credit card form and the page title says "Change Payment Method". 
* Sandbox to confirm that you can actually change the card.

Fixes https://github.com/Automattic/wp-calypso/issues/47929

### CODE REVIEW

**Review by sirbrillig — APPROVED** [review]
The code looks great. Thank you for cleaning this up! Testing works as described. I also tested with the flag disabled (`flags=-purchases/new-payment-methods` will do it) and I see the "credit card" text remains and things seem to works as expected. 👍

**Comment by fditrapani** [comment]
Awesome. Thanks @sirbrillig!

**Review by pottedmeat — APPROVED** [review]
Code looks good

**Comment by fditrapani** [comment]
Thanks @pottedmeat!

**Pull request merged**
