### PR TITLE
Import focused flow: Site picker: Register new step and integrate Sites Grid component 

### PR DESCRIPTION
**Pull request by bogiii**
Related to https://github.com/Automattic/wp-calypso/issues/76332

## Proposed Changes

* Import-focused flow: register a new `sitePicker` step
* sitePicker step: Sites Grid Component integration

## Screenshot
Screenshot 2023-05-16 at 22 38 29

## Testing Instructions

* Go to `/setup/import-focused/sitePicker?siteSlug={SITE_SLUG}`
* Check how filtering works
* Check responsive design

**NOTE:** This PR doesn't contain logic for `Select this site` CTA

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

**Comment by ouikhuan** [comment]
It looks like we're outputting all sites at the moment. Ideally we should only output Simple and Atomic sites and exclude Jetpack sites. Looks like we can achieve this by adding a `filters` params with `filters=atomic,wpcom` to `/sites` API. Does this make sense?

Also the link to create a new site is missing as well. Do we leave out on purpose?

**Comment by bogiii** [comment]
Hey @ouikhuan,

Since this PR is the step setup and site grid integration.
The idea is to have multiple PRs for more straightforward reviews.

Are you ok with that to merge this, and in the following PRs handling of "create site", "flow integration", etc.

**Review by ouikhuan — APPROVED** [review]
Sure, let's do the rest in other PRs. Apart from the problems I mentioned above, everything else is work as expected 👍

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/7998113

Thank you @bogiii for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/7998113).

**Pull request merged**
