### PR TITLE
update Newspack Blocks to v2.0.0

### LINKED ISSUE #80069: Blog Posts block: Post content not initially displayed in page editor
### Quick summary

When opening the editor of a page with an existing Blog Posts block, only generic/placeholder info is listed rather than showing the actual post content.

### Steps to reproduce

1. Create a new page
2. Add the Blog Posts block
3. Click `Save Draft` or `Publish`
4. Leave and reopen the page editor, or refresh the page

### What you expected to happen

The Blog Posts block should display post content:

image

### What actually happened

The Blog Post block loads generic/placeholder content:

image

### Impact

All

### Available workarounds?

Yes, easy to implement

### Platform (Simple and/or Atomic)

Simple, Atomic

### Logs or notes

**Additional Info:**
- Behavior occurs on both Classic and Full Site Editing themes

**Workaround:**
- Making other edits to the page or directly to the Blog Posts block forces post content to load (can take a while, but making multiple edits seems to speed up the process)

Blog Posts block bug workaround

### PR DESCRIPTION
**Pull request by adekbadek**
Similar to https://github.com/Automattic/wp-calypso/pull/81864, this is an update to synced Newspack Blocks. 
Specifically to fix https://github.com/Automattic/wp-calypso/issues/80069

### CODE REVIEW

**Comment by adekbadek** [comment]
Tagging @DustyReagan since you've handled the last update

**Review by DustyReagan — APPROVED** [review]
Looks like it's working! Here's how I tested:

1. Updated the version number using this PR
2. Run `yarn` locally
3. Open up my WPCOM sandbox terminal
4. Back on my local terminal cd to `/apps/editing-toolkit`
5. Run `yarn dev --sync` to update ETK on my sandbox
6. Point URL of my test site and the public API to my sandbox IP address using my host file.
7. Test on http://calypso.localhost:3000/
8. Open up a blog post and try using `/blog` and `/carousel`
9. No errors in console
10. Appears to be working! 🎉

**Comment by dkoo** [comment]
@DustyReagan thanks for reviewing and testing! Can you give us an approval if it looks good to you? Then we can merge and proceed with the sync to ETK.

**Review by DustyReagan — APPROVED** [review]
I retested after the merges. It looks good! 👍

**Pull request merged**
