### PR TITLE
Editing Toolkit: Update Newspack Blocks to v1.19.0

### LINKED ISSUE #404: Blog Posts Block: Load More Posts button doesn't appear even though there are more posts to load
**Describe the bug**
User is using a blog post block to display posts to 5 posts at a time. The Load More button does appear as expected for the next 5 posts, but it doesn't seem to appear after the 2nd time even though there are more posts.

When I tested this on my own site, at a certain point when trying to click on the Load More button for more posts, the Load More button will stop appearing, even though there are still more posts that can load.

**Screenshare/Screenshot**

https://d.pr/i/AjoWdA 
https://d.pr/i/ADm2an

**To Reproduce**
Steps to reproduce the behavior: I tested this on my own site: https://susanjane.blog/testing-blog-posts-block/
1. Click on `Load More Posts` to load next 5 posts, then again, and then again.
2. The last post at the bottom should be `BIRTHDAY BOOK CLUB` which is not the last post published (there are more before this). You won't see the `Load More Posts` button, however, there are 12 published posts before this post, so the `Load More Posts` button should appear to display more posts.

**Expected behavior**
The Load More Posts button should appear at the bottom to load the next 5 posts until there are no more published posts to display. For Reference, on my site, the last published post should be titled `The Coolest Hair`

### LINKED ISSUE #48253: Editing Toolkit: Update newspack blocks (Tracking)
Newspack blocks is getting older and older in Editing Toolkit. We tried to update it in this [PR](https://github.com/Automattic/wp-calypso/pull/48179) but resulted in build errors. It got reverted in this [PR](https://github.com/Automattic/wp-calypso/pull/48186).

We can't update newspack blocks in ET till the tests are fixed. Here is my proposed plan to finally get it updated:

**Plan:**

- [x] - Fix an issue in newspack blocks that's causing some tests to fail: https://github.com/Automattic/newspack-blocks/pull/649
- [x] - Release a new newspack blocks version with the changes above (1.17.1)
- [x] - Create a PR which updates the newspack blocks to the latest version in Editing toolkit
- [x] - Merge newspack blocks update PR even though some tests are failing in TeamCity
- [x] - Create a PR which bumps the Editing Toolkit version
- [x] - Wait for a diff
- [x] - Add these changes to the ET release diff: D54168-code
- [x] - Make sure tests are passing
- [ ] - Commit diff
- [ ] - Merge PR

cc @Addison-Stavlo  @jeffersonrabb  @laurelfulford

### PR DESCRIPTION
**Pull request by dkoo**
#### Changes proposed in this Pull Request

* Editing Toolkit: Update Newspack Blocks to 1.19.0.

This new version of Newspack Blocks includes a much-requested fix for a "Load More" bug. Details on the bug and its resolution are [here](https://github.com/Automattic/newspack-blocks/issues/404) and [here](https://github.com/Automattic/newspack-blocks/pull/672).

Note that v1.18+ of Newspack Blocks also uses a new custom REST endpoint to fetch posts in the editor. For this reason, we needed to add a bit of code to `apps/editing-toolkit/editing-toolkit-plugin/newspack-blocks/index.php` to localize the endpoint URL so that it first gets run through the FSE filter that rewrites the `newspack-blocks/v1` REST namespace to `wpcom/v2`.

#### Testing instructions

* Sync this branch and build it to a sandbox. Make sure to sandbox the public API as well, or the new custom REST route won't work.
* Follow the testing instructions in https://github.com/Automattic/newspack-blocks/pull/672. 

Fixes https://github.com/Automattic/newspack-blocks/issues/404.

Closes https://github.com/Automattic/wp-calypso/issues/48253

### CODE REVIEW

**Comment by dkoo** [comment]
Hi @mmtr, tagging you for a PR here! I've tested with both simple and Atomic sites and all looks good to me so far.

**Comment by apeatling** [comment]
Should this change also be included? https://github.com/Automattic/wp-calypso/pull/48938

**Comment by stacimc** [comment]
@dkoo I'm still seeing the issue on a simple site -- is it possible I'm missing a build step? This is what I'm doing:

* Checkout this branch
* `npm run build` (I built both in the calypso root and within apps/editing-toolkit)
* Sync changes to my sandbox
* Make sure both my test site and the public api are sandboxed

I'm then following the test instructions from Automattic/newspack-blocks#672.

When I use a posts category that contains 10 posts, if I set the "Number of items" to 5, I am able to use the `Load More` button to load in all ten posts. If I set "Number of items" to 2, the `Load More` button disappears after only 6 of the posts have been loaded.

**Comment by dkoo** [comment]
@stacimc I'm unable to reproduce in my sandbox. I'm not sure about this, but I wonder if you need to also run `yarn run sync:newspack-blocks --release=v1.19.0` before running `build` in the calypso root and ETK plugin folders? It's my understanding that this is run as part of the production release build, but maybe you need to run it manually if syncing from a dev directory.

Edit to add: Another way you can tell if your block is running the latest Newspack Blocks code is if you see this sidebar panel to select post types that can appear in the block:

Screen Shot 2021-02-01 at 4 14 23 PM

This is a new feature that was added in v1.18.1, so it wouldn't be present if your sandbox still somehow has the code from v1.17.0.

**Review by stacimc — APPROVED** [review]
Thanks @dkoo, that was exactly what I needed. Re-tested and it looks good to me!

**Pull request merged**
