### PR TITLE
Add google domain owner banner

### PR DESCRIPTION
**Pull request by lsl**
Fixes https://github.com/Automattic/dotcom-forge/issues/3474

## Proposed Changes

* Adds google domain owner banner

## Testing Instructions

* Flag your test user as a google domain owner via sandbox: `update_user_attribute(238083941,'is_google_domain_owner',true);`
* Confirm the banner shows up in both site specific and all domains pages:
  * http://calypso.localhost:3000/domains/manage
  * http://calypso.localhost:3000/domains/manage/testingtesterson2546.blog
* Confirm the banner does not show up on both pages if your test user is missing the flag.

Screenshot_2023-08-30_15-23-08
Screenshot 2023-08-30 at 15-22-46 Domains ‹ Premium site 1 — WordPress com

### CODE REVIEW

**Comment by lsl** [comment]
Switching to this again :slightly_smiling_face:

**Review by candy02058912 — COMMENTED** [review]
✅ Showing for all domains and site domains
✅ calypso_google_domain_owner_impression tracks event
Wasn't able to trigger `calypso_google_domain_owner_click` tracks event for the CTA click, going to look into this a bit.

**Review by candy02058912 — APPROVED** [review]
Fixed the tracks event not showing so LGTM 👍

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/8822580

Thank you @lsl for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/8822580).

**Pull request merged**
