### PR TITLE
Notifications: Move post title to end of line

### LINKED ISSUE #32986: Notifications: Sometimes you can't tell which blog a notification is coming from
Screen_Shot_2019-04-25_at_5 19 37_PM

When you're notified of a new post or comment on a blog you follow and the title of that post or comment is very long it obscured the title of the blog where the notification is originating from. 

e.g. John Doe posted "this is a very long title—it's so long that it will hide the part where It tells the user what blog this was posted on" on The Studio

The "on The Studio" part would probably be hidden. If the title is especially long it's even hidden when you click on the notification and expand the drawer. (see screenshots) 

This might be a very a8c-centric problem since we really push the notification feeds functionality to its limits, but it still feels like the website that a notification is originating from should be put in a spot where it won't get easily hidden.

Originally reported by @dabowman

### PR DESCRIPTION
**Pull request by sixhours**
#### Changes proposed in this Pull Request

* Combine with changes proposed in D29846-code, this moves the post title to the end of the subject to avoid long post titles pushing the blog name off screen.
* You need a WP.com sandbox to test these changes.

**Before**

{Name} posted {Title} on {Blog}

**After**

{Name} posted on {Blog}
{Title}

#### Testing instructions

* Switch to this PR
* Sandbox `public-api.wordpress.com`
* Apply D29846-code on your sandbox
* Check the Notifications panel on the front end and back end of Calypso. Posts should have the new format.

Fixes #32986

### CODE REVIEW

**Comment by kwight** [comment]
Hm, I admit it feels like we're trading one awkwardness for another: now shorter titles look weird spread between two lines, particularly when the notifications panel is full-width:

Screen Shot 2019-06-27 at 11 32 45 AM

Comments also seem to suffer from the same posted issue, but aren't handled by this fix.

Is this approach worth it, from a design/UX point of view?..

**Comment by sixhours** [comment]
> Comments also seem to suffer from the same posted issue, but aren't handled by this fix.

Whoops, that's because my CSS wasn't specific enough and should not have applied to comments in the first place. 😅But comments/likes don't have this problem from the original issue because they don't include the blog name at all.

I could CSS it such that the line break only occurs when we're viewing the smaller window width, or use a colon between the post title and the blog name to bring them onto the same line regardless of window width: 

Screen Shot 2019-06-27 at 5 55 18 PM

So it would read `{Name} posted on {Blog}: {Title}`

The only awkwardness there happens with X-posts and a double colon, but I think it's worth it for more clarity about knowing where the posts are coming from.

**Comment by kwight** [comment]
Seems like a good compromise 👍 D29846-code is all that's needed then. and this can be closed out?

**Comment by sixhours** [comment]
@kwight Yep, no CSS necessary! Closing this out.

**Pull request closed without merging**
