### PR TITLE
Update post "Search and Social" preview components to use @automattic/social-previews

### PR DESCRIPTION
**Pull request by getdave**
Builds upon work in https://github.com/Automattic/wp-calypso/pull/44170 to replace usage of built-in social preview components with those now housed in the new `@automattic/social-previews` package.

## Changes proposed in this Pull Request

* Adds `@automattic/social-preview` as dependency of `client/`.
* Updates x2 components to use the social preview components from the new package.
* Remove the original components from `client/components/seo`.

## Screenshots

Screen Capture on 2020-07-22 at 15-18-48

## Testing instructions

The experience should not change between Master and this PR's branch.

#### On Master 
* Run yarn && yarn start to build all the things. Wait for Calypso to boot. Goto http://calypso.localhost:3000/.
* On a Business site, create a new Post with some content and a title and click "Preview".
* Toggle the Preview to "Search and Social" using the dropdown.
* You should see the post previews and be able to toggle between each type with no errors.
* Go to the Posts listing page. Click on "3 dots" menu on far right hand side of each post item in the list. 
* Click `Share`. Connect FB account with a `Page`.
* See Facebook share preview.

#### On This PR 
* Run yarn && yarn start to build all the things. Wait for Calypso to boot. Goto http://calypso.localhost:3000/.
* On a Business site, create a new Post with some content and a title and click "Preview".
* Toggle the Preview to "Search and Social" using the dropdown.
* You should see the post previews and be able to toggle between each type with no errors.
* Go to the Posts listing page. Click on "3 dots" menu on far right hand side of each post item in the list. 
* Click `Share`. Connect FB account with a `Page`.
* See Facebook share preview.

### CODE REVIEW

**Comment by getdave** [comment]
As discussed in p1595434588407600-slack-ajax @Automattic/ajax will deploy this shortly.

**Comment by marekhrabe** [comment]
Calypso tests are broken and have blocked deploys. I haven't managed to deploy this before my EOD.

**Comment by getdave** [comment]
We're going to need to test this with `CALYPSO_ENV=production make build` as it looks like the CSS isn't being compiled correctly.

**Comment by getdave** [comment]
This was reverted.

**Comment by mreishus** [comment]
Heads up; #44355 (Make usable for outside consumers) was merged into master; so you may want to merge or rebase those changes in before adding work on this branch.

**Pull request merged**
