### PR TITLE
Jetpack Search: Display in My Plans page

### PR DESCRIPTION
**Pull request by jsnmoon**
Partially addressees #39858; the design is not final.

Screen Shot 2020-03-23 at 5 19 09 PM

#### Changes proposed in this Pull Request

* Adds support for showing Jetpack Search in the My Plans page.

#### Testing instructions

1. Spin up this branch locally.

2. Navigate to `/plans/my-plan/` and select a non-Professional Jetpack site with a Jetpack Search product subscription. Ensure that you see a card for Jetpack Search.

### CODE REVIEW

**Comment by jsnmoon** [comment]
@keoshi, can you help me with adding an icon for Jetpack Search in the ProductIcon component?

**Comment by keoshi** [comment]
Absolutely, @jsnmoon ! Just need to add it like so, right?

https://github.com/Automattic/wp-calypso/blob/653a274eb1410f1d7cabec660757e63339e7b7d2/packages/components/src/product-icon/config.js#L4

**Comment by jsnmoon** [comment]
@keoshi Yup! Thanks :)

**Comment by keoshi** [comment]
@jsnmoon Pushed a commit that should add the icon file and change all its instances. Should look something like this:

image

**Comment by jsnmoon** [comment]
PR has been merged; E2E failures are unrelated to these changes.

**Pull request merged**
