### PR TITLE
Framework: Remove remnants of enzyme

### PR DESCRIPTION
**Pull request by tyxla**
#### Proposed Changes

This PR removes what remains from `enzyme` and its adapters/utilities as they're no longer needed.

#### Testing Instructions

Verify all checks are green.

### CODE REVIEW

**Review by noahtallen — DISMISSED** [review]
Noticed this one early and figured I'd give it a pre-emptive approval :)

The tests passing are really the big sign things are working well. I also searched for "enzyme" in the repo. I think there might be one more thing we can remove here:

https://github.com/Automattic/wp-calypso/blob/6c46a2163c13633e572c875f727a596f389d6396/packages/calypso-jest/README.md#L13

I also noticed this comment, but it may not be worth changing at this point:

https://github.com/Automattic/wp-calypso/blob/f2e6f88ae65c8571bbac21b284c29b48ec987598/client/components/bulk-select/index.jsx#L46

Other than those very minor things, I'm excited for this to land!

**Comment by tyxla** [comment]
Thanks, @noahtallen, I'll take care of those. 

Before I ship this, I'd also like to add some documentation for folks who would still like to use Enzyme in a project that uses a Calypso package that used to provide it. We haven't published `@automattic/calypso-jest` yet, but just in case we want to do it, it would be helpful to have it.

Going to address those early next week and ping y'all for a review!

**Comment by tyxla** [comment]
This is ready for review 👀

**Review by noahtallen — APPROVED** [review]
Docs look solid, and everything seems to be working well! Nice work :)

**Pull request merged**
