### PR TITLE
Paid Stats: Adjust payment page styling for WPCOM sites

### PR DESCRIPTION
**Pull request by annacmc**
Related to #81488

## Proposed Changes

* This PR addresses that the current payment page / wizard design might come across as too Jetpack, which might seem a bit inconsistent in a flow for WordPress.com users. It adjusts the colors for WPCOM users as per designs in p1HpG7-orS-p2#comment-65837

* It adjusts the following to match a more WPCOM style:

	* Calypso typography
	* Theme palette used for buttons, links & accents
	* This does not address the "color of the illustration for WordPress.com users" feedback. Which can come in a separate PR

## Testing Instructions

* Load the Calypso live branch
* Go to `stats/purchase/{siteURL}`
* If it is a wpcom simple site, append the flag `flags=stats/paid-wpcom-stats`
* Test on both WPCOM site, and a Jetpack site. Make sure the colors, typography and styling match those in the screenshots below as well as the design iterations at p1HpG7-orS-p2#comment-65837

| step 1.  | personal site | commercial site  |
| ------------- | ------------- | ------------- |
| image | image | image  |
| image  | image  | image  |

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

**Comment by annacmc** [comment]
A note to add: It's not mentioned in the design iterations (these notices are not shown at all), but do we want the following notice on the personal site screen to match the Jetpack green background on the commercial site purchase screen? I think yes, but wanting to double check this as I think a little refactoring on the `stats-purchase-wizard__notice--green` selector could be in order. cc: @kangzj @grzegorz-cp 

| JP Personal Site Purchase Screen | JP Commercial Site Purchase Screen |
| ------------- | ------------- |
| image  | image  |

**Comment by grzegorz-cp** [comment]
> A note to add: It's not mentioned in the design iterations (these notices are not shown at all), but do we want the following notice on the personal site screen to match the Jetpack green background on the commercial site purchase screen? I think yes, but wanting to double check this as I think a little refactoring on the `stats-purchase-wizard__notice--green` selector could be in order. cc: @kangzj @grzegorz-cp

It's great that you noticed this. I don't think we want to align the colours because all of the designs show a yellow background for the personal flow. The other flow had a different colour on purpose, if I remember correctly.
@ederrengifo is that correct?

**Review by grzegorz-cp — APPROVED** [review]
Colours are applied correctly. 👍 

We can also flip this implementation and extract Jetpack colours to a new class (and apply it for Jetpack) because wp colours are applied by default already - with the implementation in the PR we apply them again on top of Jetpack. This could be optimised in the future.

I also noticed that the slider background is black for wp colours on a stand-alone purchase page.

**Review by a8ck3n — APPROVED** [review]
Looking good. I'd maybe push back on coloring the link text though. In some themes the links become very low contrast and difficult to read. I'm also unable to find other examples of plain links in text taking the highlight color from the theme. Example using the Aquatic color scheme:

SCR-20230912-mumr

That link is a bit of a retina burner!

**Comment by dognose24** [comment]
> extract Jetpack colours to a new class (and apply it for Jetpack) because wp colours are applied by default already

Yeah, it is more reasonable to refactor the Jetpack styling overriding upon the Calypso base.

**Review by dognose24 — COMMENTED** [review]
I noticed the header `font-weight` is `700`, and the step title's `font-family` is `SF Pro Text`, which would be different from the design.

截圖 2023-09-12 下午10 32 41

And about the button color adjustment, I found the hover background color of buttons on the wizard is not modified to adapt to the color scheme. That's the reason I tried to [apply the button](https://github.com/Automattic/wp-calypso/blob/update/paid-stats-wizard-color-wpcom/client/my-sites/stats/stats-purchase/stats-purchase-personal.tsx#L93) from `@automattic/components` for WPCOM sites, which would reduce the effort of overriding every state of each button.

https://github.com/Automattic/wp-calypso/assets/6869813/21f18d08-5a02-4631-94b8-4b32eabc6d7c

**Comment by dognose24** [comment]
Unexpectedly, I have [proposed another PR](https://github.com/Automattic/wp-calypso/pull/81616) to tweak the [styling of WPCOM sites](https://github.com/Automattic/wp-calypso/issues/80888) at the same time, which would partially resolve some of the issues above. Since the purchase page for WPCOM sites is still gated behind the feature flag, let's ship this PR first and iterate in the follow-up PR for some tweaks we might miss. 🙂

**Comment by annacmc** [comment]
> Unexpectedly, I have https://github.com/Automattic/wp-calypso/pull/81616 to tweak the https://github.com/Automattic/wp-calypso/issues/80888 at the same time, which would partially resolve some of the issues above. Since the purchase page for WPCOM sites is still gated behind the feature flag, let's ship this PR first and iterate in the follow-up PR for some tweaks we might miss. 🙂

Thanks @dognose24  - sounds like a plan! I've gone ahead and shipped this PR, so now it should be possible to check on what needs to be done after your PR is also shipped 😄

**Comment by annacmc** [comment]
> Looking good. I'd maybe push back on coloring the link text though. In some themes the links become very low contrast and difficult to read. I'm also unable to find other examples of plain links in text taking the highlight color from the theme. Example using the Aquatic color scheme:
> 
> SCR-20230912-mumr
> That link is a bit of a retina burner!

This is a good point, thanks for spotting it! @augurlu what do you think about this. Is there a single color we could opt to use for the link text instead of the theme palette colors?

**Comment by annacmc** [comment]
> Colours are applied correctly. 👍
> 
> We can also flip this implementation and extract Jetpack colours to a new class (and apply it for Jetpack) because wp colours are applied by default already - with the implementation in the PR we apply them again on top of Jetpack. This could be optimised in the future.
> 
> I also noticed that the slider background is black for wp colours on a stand-alone purchase page.

Thanks @grzegorz-cp ! I have created a followup issue for each of these points in #81648 & #81649

**Pull request merged**
