### PR TITLE
Media: Replace MediaActions.sourceChanged with redux action

### PR DESCRIPTION
**Pull request by saramarcondes**
#### Changes proposed in this Pull Request

* Replace calls to `MediaActions.sourceChanged` with the redux action

#### Testing instructions

* Test that changing the "source" of the media library works (move to pexel, google photos, etc) in the main media page.

Part of https://github.com/Automattic/wp-calypso/issues/43664

### CODE REVIEW

**Comment by saramarcondes** [comment]
Blocked by https://github.com/Automattic/wp-calypso/pull/44009

**Comment by saramarcondes** [comment]
Rebased and ready for review @flootr

**Comment by saramarcondes** [comment]
@flootr They aren't I guess, but we can remove them soon when we remove the stores altogether? Or do you prefer doing it incrementally?

**Comment by flootr** [comment]
> we can remove them soon when we remove the stores altogether

fine with me 👍

**Pull request merged**
