### PR TITLE
Writing Settings: disable Mobile Theme UI when feature isn't active

### LINKED ISSUE #36404: Settings: Writing - Mobile Theme options not available in Calypso in simple sites as Atomic sites
#### Steps to reproduce
1. Starting at URL: https://wordpress.com/settings/writing/DOMAIN 
2. Go to "Theme Enhancement" section

#### What I expected
I expected both simple and atomic sites to show the same mobile theme options.

#### What happened instead
Different options show between simple and atomic. For Atomic sites Mobile Theme is in calypso. For simple sites it is wp-admin.

#### Screenshot / Video
Screenshot Simple --  ((WP Admin) https://cld.wthms.co/2Hm5c6 / (Calypso) https://cld.wthms.co/KYLw95
Screenshot Atomic-- https://cld.wthms.co/tDTpJl

#manual-testing

### PR DESCRIPTION
**Pull request by jeherve**
Fixes #36404

Matching Jetpack PR: 
https://github.com/Automattic/jetpack/pull/14101

* Internal references:
    - p1HpG7-84F-p2
    - p6TEKc-3iM-p2
    - p6TEKc-3jj-p2
    - p6TEKc-3l7-p2

#### Changes proposed in this Pull Request

The Mobile theme was developed 8 years ago, back when responsive themes weren't a thing. It isn't as useful today, and can even be harmful when one enables it on their site without realizing the consequences, as outlined in https://github.com/Automattic/jetpack/issues/7602.

*****

This PR comes as a first step to deprecate the Mobile Theme feature. We'll start by greying out Mobile Theme Settings from the Writing Settings UI when the feature is not active. Folks that still use the feature can access its settings and disable it. Folks who do not use it cannot turn it on via the UI.

In addition to those changes, we'll display a notice on top of the settings:
- If the Mobile Theme feature is active on your site and if you run Jetpack 8.1 Alpha or newer, we'll show you a notice inviting you to check the look of the site on mobile devices if you did not run the Mobile Theme feature on your site. We can do so via a Google Tool.
- If you run an older version of the Jetpack plugin, or if the Mobile Theme feature is already off on your site, you'll see a generic notice announcing the deprecation.

******

**Module active**

image

**Module inactive**

screenshot 2019-12-17 at 18 39 37

#### Testing instructions

* Start from a site running Jetpack 8.1 Alpha.
* Run `yarn docker:wp jetpack module activate minileven` to enable the module on your Jetpack site.
* Go to Manage > Settings > Writing.
* Notice that the Mobile Theme settings are there.
* Notice the notice.
* Click the 2 links to check the support docs as well as the Google checking tool.
* Disable the feature.
* The settings should become grey.

### CODE REVIEW

**Comment by ChaosExAnima** [comment]
Can verify that I don't see it with this branch:

Screenshot from 2019-11-22 10-19-06

**Comment by jeherve** [comment]
Moving this back to "in progress" as we may want to add a feature deprecation notice in there. See conversation in the Jetpack PR to find out more.

**Comment by jeherve** [comment]
Noting that we may end up displaying things a bit differently.

Reference: p6TEKc-3iM-p2

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/3986338).

**Pull request merged**
