### PR TITLE
Sites Management Page: Filter site status using drop down instead of tabs

### PR DESCRIPTION
**Pull request by p-jackson**
#### Proposed Changes

Part of @SaxonF's design changes proposed in https://github.com/Automattic/wp-calypso/pull/65871

* Removes site status tabs!
* Filter site status using a drop down.
* Big changes to the `useSitesTableFiltering` hook which no longer returns tab definitions
   * fuzzy search now performed _after_ status filtering so that the counts aren't affected by the query string (this was how Saxon's changes worked)
   * return counts for each status so it can be rendered in `<SitesDashboard>`
   * Updated status labels to match Saxon's design changes
* Update style of search box so it sites nicely beside the drop down
* Moved the "no sites" message so that they appear underneath the filtering controls. Otherwise there's no way to switch the filter to something else that might have sites.
* Add tests for `useSitesTableFiltering` hook and `<NoSitesMessage>` component, since that's where I've changed logic

CleanShot 2022-08-03 at 22 08 24@2x

#### Testing Instructions

* Check it out at `/sites-dashboard`
* Ensure the drop down control is always fully visible (I fixed issues where it was being cropped)
* Status counts shouldn't update as user types in search queries
* Ensure mobile layout is working

#### Pre-merge Checklist

- [x] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [x] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [x] Have you checked for TypeScript, React or other console errors?
- [x] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] ~Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?~

Related to #65871

### CODE REVIEW

**Review by vykes-mac — COMMENTED** [review]
Looks way better in my estimation, works well on mobile also. I was wondering if a slight radius on the search and dropdown might work better with the overall calypso styling than the sharp edges that's there now? 

image

The code looks good to me.

**Comment by p-jackson** [comment]
I'm seeming a radius of `2px` on the search and dropdown controls atm, which matches the radius on the new site button. But I think you're right that some parts in Calypso are a bit smoother.
What do you think @SaxonF? Is the SMP going for agressive and angular or friendly and softer 😆

**Comment by p-jackson** [comment]
@Automattic/build I've resolved the remaining issues I had with the PR and have pushed some tests. I think this is ready to go now.

**Review by danielbachhuber — APPROVED** [review]
🔥 Looks great!

**Pull request merged**
