### PR TITLE
chore(formatting): Remove @format pragma from codebase

### PR DESCRIPTION
**Pull request by blowery**
#### Changes proposed in this Pull Request

* Remove the @format pragma from the codebase
* Fix the pre-commit-script to handle large changes

#### Testing instructions

* e2es should cover this

### CODE REVIEW

**Review by ockham — APPROVED** [review]
Seems about right. Thanks for taking care of this! Merge pending e2e tests :+1:

**Comment by blowery** [comment]
Still a bunch of `@format` pragmas embedded in bigger comment blocks. Working on removing those too.

**Comment by sirreal** [comment]
FYI: I was annoyed by this, tried some sed-style removal and eventually wrote a codemod: https://github.com/Automattic/calypso-codemods/pull/10

I was planning to get that merged, but was waiting on #36645.

No opposition to going ahead with this, just so you're aware that there's an implemented alternative that may make this easy.

**Comment by blowery** [comment]
> No opposition to going ahead with this, just so you're aware that there's an implemented alternative that may make this easy.

Wasn't too bad to replace with a few regexp searches. It's unique enough that it's pretty easy to find and replace.

**Pull request merged**
