### PR TITLE
Business Hours Block: add search keywords

### PR DESCRIPTION
**Pull request by roccotripaldi**
#### Changes proposed in this Pull Request

* adds search keywords to the block so folks can find it more easily in the post editor

```
_x( 'opening hours', 'block search term' ),
_x( 'closing time', 'block search term' ),
_x( 'schedule', 'block search term' ),
```

#### Testing instructions

* do the terms make sense?

### CODE REVIEW

**Comment by lezama** [comment]
I am not sure about “times”, do translators have the context that this is a business hours block?

**Comment by roccotripaldi** [comment]
> I am not sure about “times”, do translators have the context that this is a business hours block?

Good call. @jeffgolenski mentioned 'Schedule' as a possibility too, and i'd be happy to replace 'times' with 'schedule'

I feel like we'd be failing if we don't mention time somewhere / somehow though.

**Comment by lezama** [comment]
maybe “schedule”?

**Comment by lezama** [comment]
hehe, I didn’t see your previuos comment, let’s go with “schedule” instead of “times”

**Comment by roccotripaldi** [comment]
Done!

I updated to
```
_x( 'opening hours', 'block search term' ),
_x( 'closing time', 'block search term' ),
_x( 'schedule', 'block search term' ),
```

I got rid of  'hours of operation' because that is an American term, and it means the same as 'opening hours'. I replaced it with 'closing time' - i know who i want to take me home :)

I replace 'times' with 'schedule'

**Comment by jeherve** [comment]
Cherry-picked to the release branch in 172079fce6ca0cfa895c80df9adce8ab5f52f771

**Pull request merged**
