### PR TITLE
Framework: Move noscript tag to the very bottom

### LINKED ISSUE #3346: Themes: Get rid of "Please enable JavaScript" message
To reproduce -- turn off JavaScript, and navigate to http://calypso.localhost:3000/themes/something

js

We don't want that on a server-side rendered, SEO-targeted page.

### PR DESCRIPTION
**Pull request by ockham**
So it won't get in the way of SEO for server-side rendered pages.

/cc @folletto for styling

Closes #3346

### CODE REVIEW

**Comment by folletto** [comment]
screen shot 2016-02-29 at 14 04 36

screen shot 2016-02-29 at 14 04 24

So:

* Added styling
* Server-side rendering: tested both a page without (`/`) and with (`/themes/x`)
* Made it sticky and semi-transparent so it's visible all the times, but won't impair the use of the page. Seems a good compromise to me.

**Comment by ockham** [comment]
CC MCMC (@mtias, Calypso Emcee)

**Comment by seear** [comment]
@folletto: I don't see the styling commit

**Comment by folletto** [comment]
> I don't see the styling commit

That's because I'm stupid. 

Pushed now.

**Comment by folletto** [comment]
> leave noscript message at top when no content

What's the rationale for this change? :)

**Comment by seear** [comment]
> What's the rationale for this change? :)

This was to make the message more visible when there was no server-rendered content. Removed that commit since it would be better done with a proper empty component should we desire.

This is good to merge :+1:

**Pull request merged**
