### PR TITLE
Atomic: Don't use front page editor for Atomic sites yet

### PR DESCRIPTION
**Pull request by aidvu**
#### Changes proposed in this Pull Request

Don't use front page editor for Atomic sites yet

#### Testing instructions

- Create an atomic site with `brompton` theme
- Visit `/themes/tooloom.jp`

Before:
- Errors in console.

After:
- No errors in console, and page is shown

Reference: p9F6qB-63w-p2

### CODE REVIEW

**Review by jmdodd — APPROVED** [review]
Works as expected.

**Comment by simison** [comment]
I'm not entirely sure what got disabled here and it's not obvious from the code. Could you include screenshots?

@davemart-in @creativecoder is this related to classic editor deprecation project? (based on `shouldUseGutenberg`)

Function description states:

> Returns the URL for opening customizing the given site in either the block editor with Full Site Editing, or the Customizer for unsupported sites. Can be used wherever

@vindl is this related to wpcom-FSE experiment, and this problem was potentially affecting just that small subset of customers?

**Comment by aidvu** [comment]
> I'm not entirely sure what got disabled here and it's not obvious from the code. Could you include screenshots or elaborate more?

A screenshot would be just a blank Calypso screen.

Check this: https://github.com/Automattic/wp-calypso/blob/dac30586cd5253c2bf463635e869a364e24bcdcc/client/my-sites/themes/thanks-modal.jsx#L303

For `hasAutoLoadingHomepage = true` and `isAtomic = true` it was showing a blank themes screen. Because https://github.com/Automattic/wp-calypso/pull/46772/files#diff-4f89fa52f43e9a288c4ec46d04ee1781031227784ded149a7ae97dd01950be34L21 was trying to return a `getFrontPageEditorUrl` which was `false`, and then TypeScript would throw an error because it expects a string. :)

**Comment by vindl** [comment]
> @vindl is this related to wpcom-FSE experiment, and this problem was potentially affecting just that small subset of customers?

As far as I can see this affects both template-first themes and Dotcom FSE. For context this selector was introduced as part of this issue https://github.com/Automattic/wp-calypso/issues/37286.

> Users with a template-first theme should not be prompted to go into the customizer when activating that theme.

**Comment by simison** [comment]
Thanks both! @vindl also shared that this affects this bit of UI, specifically:

image

So we need a follow-up to bring back original behavior instead of changing it like this. Create division folks can own it. 👍

**Comment by aidvu** [comment]
> So we need a follow-up to bring back original behavior instead of changing it like this. Create division folks can own it. +1

I might be wrong, but that also never worked on Atomic. :)

**Pull request merged**
