### PR TITLE
Revert " Framework: Async load all Web Previews"

### PR DESCRIPTION
**Pull request by lamosty**
Reverts Automattic/wp-calypso#20960

### CODE REVIEW

**Comment by dmsnell** [comment]
why?

**Comment by lamosty** [comment]
Because there was a bug which caused editor not working for AT users. Fix in https://github.com/Automattic/wp-calypso/pull/21278/commits/57bf5122081c4fedede44c26f5f15a29a8dee75c

**Comment by dmsnell** [comment]
so did we shadow the default export by spreading the props before the `require`?

**Comment by lamosty** [comment]
The problem was that we spread the props after passing the correct `require` prop. However, when using the component, we also passed `require` (from previous iteration) which pointed to wrong component. Since the `props` were spread after the proper `require`, the wrong `require` got passed to `AsyncLoad` which couldn't find the component and complained that `require` is not a function.

**Pull request merged**
