### PR TITLE
scan: wpcom-upsell: Use feature checks when deciding which promo cards to display

### PR DESCRIPTION
**Pull request by mreishus**
#### Changes proposed in this Pull Request

* scan: wpcom-upsell: Use feature checks when deciding which promo cards to display

#### Testing instructions

* First, we need to get the wpcom-upsell to display for a simple site. `/scan/<site>` 404s on free simple sites. I used this patch:
```diff
diff --git a/client/my-sites/scan/index.js b/client/my-sites/scan/index.js
index abe11c02b3..98548be109 100644
--- a/client/my-sites/scan/index.js
+++ b/client/my-sites/scan/index.js
@@ -25,9 +25,11 @@ const notFoundIfNotEnabled = ( context, next ) => {
        const showJetpackSection = isJetpackSectionEnabledForSite( state, siteId );
        const isWPCOMSite = getIsSiteWPCOM( state, siteId );
 
+       /*
        if ( isWPCOMSite || ( ! isJetpackCloud() && ! showJetpackSection ) ) {
                return notFound( context, next );
        }
+       */
 
        next();
 };
```
Alternatively, there might be something you can do with enabling/disabling the jetpack section with flags.
* Visit `/scan/<site>` for a Free plan site
* You should see both promo cards

* Sandbox public-api, Give your site the activity log feature on sandbox
```diff
diff --git a/wp-content/mu-plugins/wpcom-features/class-wpcom-features.php b/wp-content/mu-plugins/wpcom-features/class-wpcom-features.php
index d3560a340..a8d9a17dc 100644
--- a/wp-content/mu-plugins/wpcom-features/class-wpcom-features.php
+++ b/wp-content/mu-plugins/wpcom-features/class-wpcom-features.php
@@ -521,6 +521,7 @@ class WPCOM_Features {
                        self::WPCOM_ALL_SITES,
                ),
                self::FULL_ACTIVITY_LOG             => array(
+                       self::WPCOM_ALL_SITES,
                        self::JETPACK_BACKUP_DAILY_PLANS,
                        self::JETPACK_BACKUP_REALTIME_PLANS,
                        self::JETPACK_BACKUP_T1_PLANS,
```
* F5, the activity log card disappears
* Give your site the backup feature on sandbox
```diff
diff --git a/wp-content/mu-plugins/wpcom-features/class-wpcom-features.php b/wp-content/mu-plugins/wpcom-features/class-wpcom-features.php
index d3560a340..51f506d94 100644
--- a/wp-content/mu-plugins/wpcom-features/class-wpcom-features.php
+++ b/wp-content/mu-plugins/wpcom-features/class-wpcom-features.php
@@ -399,6 +399,7 @@ class WPCOM_Features {
                ),
                // BACKUPS - Site has *any* kind of backups.
                self::BACKUPS                       => array(
+                       self::WPCOM_ALL_SITES,
                        self::JETPACK_BACKUP_DAILY_PLANS,
                        self::JETPACK_BACKUP_ONE_TIME,
                        self::JETPACK_BACKUP_REALTIME_PLANS,
```
* F5, now neither card appears

Related to p4TIVU-a66-p2

### CODE REVIEW

**Comment by mreishus** [comment]
I see a build failure, but it looks to be related to stepper and not this PR?
```
  client/landing/stepper/declarative-flow/internals/steps-repository/design-setup/index.tsx(86,34): error TS2339: Property 'hasActiveSiteFeature' does not exist on type 'SelectFromMap<typeof import("/home/teamcity-2/buildAgent/work/c4a9d5b38c1dacde/packages/data-stores/dist/types/site/selectors")>'.
```
Edit: Being fixed here: #63581

**Comment by mreishus** [comment]
Rebased

**Comment by mreishus** [comment]
Rebased to solve conflicts

**Review by obenland — APPROVED** [review]
A bit odd that it's unreachable, but ¯\_(ツ)_/¯

**Pull request merged**
