### PR TITLE
Preferences: Fix 2FA issues by using /me/preferences endpoint

### LINKED ISSUE #202: Framework: Account for Preferences settings 2FA refresh response
Raised by @aduth 

When a user's two-factor authentication token is "stale", the `GET /me/settings` endpoint will return a 401 error response.

`{"code":401,"headers":[{"name":"Content-Type","value":"application\/json"}],"body":{"error":"reauthorization_required","message":"A fresh access token must be used to query information about the current user."}}`

When a 2FA token is stale, we won't be able to retrieve from the settings endpoint until the next 2FA refresh, meaning we rely on localStorage exclusively for preferences persistence. This is not a terrible experience, but we should still seek to remove this restriction from the settings endpoint for this particular setting so as to preserve preferences even when localStorage has cleared or the user moves between different computers.

### PR DESCRIPTION
**Pull request by mcsf**
~Requires D5992-code~

Fixes #202 #3666
… as well as its numerous related issues.

### CODE REVIEW

**Comment by mcsf** [comment]
Rebased

**Comment by lancewillett** [comment]
I gave this a spin today (together with sandboxing the API patch) and wasn't able to fully get the new endpoint working. However, testing in the Live Branch I verified the new API call made from to `/me/preferences` even though it resulted in a 404. :)

**Comment by lancewillett** [comment]
Using the new API endpoint on the backend now works (patch updated). 👍 

Testing with the live branch (and sandboxed API requests) I'm able to see a successful call to the new `/me/preferences` endpoint from `https://calypso.live/me`.

```
GET /rest/v1.1/me/preferences?http_envelope=1 HTTP/1.1
Host: public-api.wordpress.com
URL: https://public-api.wordpress.com/rest/v1.1/me/preferences?http_envelope=1
Status code: 200 OK
```

**Comment by mtias** [comment]
Thanks for tackling this one.

**Comment by mcsf** [comment]
Thanks for looking! Removing _Needs Review_ and adding _Hold_ as we work on the endpoint itself.

**Comment by mcsf** [comment]
D5992-code has been deployed. This PR has been rebased and retested. Going to merge this. :)

cc @aduth to keep you in the loop, as you've worked on Preferences a lot

**Comment by folletto** [comment]
YES THANK YOU!!! :D

**Pull request merged**
