### PR TITLE
Light importer flow improvements

### PR DESCRIPTION
**Pull request by bogiii**
#### Proposed Changes

- The UX of the capture screen has been improved. Input field validation, error showing, form submitting, `I don't have a website address` link, etc.
- Improved UX of showing progress from Scanning website to Importing detected colors. (There is a case when scanning last longer than usual, we are aware of it and it will be improved in the future PRs)
- Improved summary screen

#### Testing Instructions

* Go to `/setup/importLight?siteSlug={SLUG}`
* Check if the `Don't have a site address` link redirects you to the importer list and the back button returns back to the capture screen
* Enter a website URL, for example: `https://squealing-cottonmouth.jurassic.ninja/`
* Check if there is progress with showing the palette colors and the final summary screen
* Check if the `Continue` button leads you to the Design picker step

#### Screenshots
Screenshot 2022-06-30 at 14 15 44
Screenshot 2022-06-30 at 14 15 59

Related to #64774

### CODE REVIEW

**Review by vishnugopal — COMMENTED** [review]
Few things I noticed that can possibly be improved (either in this PR or later):

1. Hitting back from the importLight first screen takes you to the Intent page (which is not used anymore). At the minimum, it should redirect to the Goals page, but I think more correctly it should go to the correct Verticals selection flow by Ganon: https://share.cleanshot.com/soy6y8
2. Similarly skip this step also goes to the intent page, this should ideally redirect to the vertical selection flow after import (think it might be the design picker for non-Write flows and the preview page for Write flows).
3. I really feel that the design when you hit Continue without typing in anything can be a source of much confusion here. Having the ability for the user to skip this step easily is essential imo to avoid impacting launch flows: https://share.cleanshot.com/m9XsIe TBD discussion with @saygunnyc 
4. Can we improve the UX of the "fake loader" somehow? What I mean by this is this delay between the first stage of the loader (to ~30%) and the second (where it says "Importing Colors") where it "appears stuck" https://share.cleanshot.com/prnkx5 Perhaps the first stage can be a gentle movement to ~30% (taking say ~10s), and which suddenly completes as we get the result? I feel this is crucial if we are to ship this feature as we never want to give the impression that this is taking a lot of time without feedback. Sites like `theverge.com` really exacerbate this initial delay.

**Comment by bogiii** [comment]
@vishnugopal Thanks for the review and comments.

I've decided to merge this as it is (since the feature is not live yet) and make additional changes based on your comments in future PRs.

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/7408694

Thank you @bogiii for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/7408694).

**Pull request merged**
