### PR TITLE
Components: Add icon to closed state of SelectDropdown

### PR DESCRIPTION
**Pull request by marekhrabe**
This PR adds an icon to the closed state of `SelectDropdown` component. It also updates the color and text-transform of the compact state to the same style as the non-compact version, based on designs from @shaunandrews.

**To test:**
- https://calypso.live/devdocs/design/select-dropdown
- or you can open any preview in My Sites and look at the mode switcher

**New look:**

| Normal | Compact |
| --- | --- |
| screen shot 2017-06-13 at 19 13 23 | screen shot 2017-06-13 at 19 14 57 |

**Usage in Preview:**

screen shot 2017-06-13 at 19 15 48

### CODE REVIEW

**Comment by drw158** [comment]
Did not test, but looks good!

This PR removes the all caps #15023

Do we need to test other areas that use this component?

**Comment by marekhrabe** [comment]
@drw158 

Didn't know about the global all caps effort - awesome stuff! 

I think no other place uses the component in its compact form so we are not really affecting anything but the preview at the moment.

**Comment by jblz** [comment]
Here's a place that uses `compact`:

https://github.com/Automattic/wp-calypso/blob/a70587157b33783ba4d5e0e4a1e136680d459d51/client/my-sites/plugins/plugin-list-header/index.jsx#L294

Not sure how to test, but seems worth a shot.

**Comment by marekhrabe** [comment]
plugin-list-header uses nothing special and renders fine:

screen shot 2017-06-15 at 15 02 05

**Pull request merged**
