### PR TITLE
Comments: Prettier on Redux and Data Layer

### PR DESCRIPTION
**Pull request by Copons**
Applied Prettier on `state/comments` and `state/data-layer/*/comments`.

### Test

Check that the following are not broken:
- the new Comment Management section
- the Reader comments
- the Post List comments

### CODE REVIEW

**Comment by dmsnell** [comment]
@samouri I'm noticing a lack of trailing comma. did we make a decision against this with our fork?

**Comment by Copons** [comment]
@dmsnell I think it strips away the trailing comma from the last function argument, but not from the last array element or object property:

```
function foo (
  arg1,
  arg2
) {}

const obj = {
  foo: 'bar',
};
```

**Comment by samouri** [comment]
@Copons  / @dmsnell: Correct.  We switched to ES5 compatible trailing commas [here](https://github.com/Automattic/calypso-prettier/pull/5).


We still have files that need to be run directly in node and I'm trying to minimize the surprises for people using `prettier`.  

When we upgrade node it may be possible to switch and at that time it should be trivial to change the calypso-prettier setting, and rerun prettier on all files with the format marker.

**Comment by samouri** [comment]
code changes lgtm

**Comment by Copons** [comment]
Closing for now: we're already working on Comment Management m2, and I'd rather wait for the Prettier/eslint conflicts to be fixed instead of pushing an incomplete PR.
I'll update later on. Thanks you all!

**Pull request closed without merging**
