### PR TITLE
Me: Add an 'I am a developer' toggle

### PR DESCRIPTION
**Pull request by danielbachhuber**
Fixes https://github.com/Automattic/dotcom-forge/issues/2333

## Proposed Changes

Adds an 'I am a developer' toggle to `/me`.

image

## Testing Instructions

1. Apply D109738-code to your sandbox.
2. Navigate to `/me`.
3. Verify that enabling the 'I am a developer' option and hitting 'Save' sets the `is_dev_account` user attribute.
4. Verify that disabling the option removes the user attribute.

### CODE REVIEW

**Review by p-jackson — APPROVED** [review]
Great! The copy looks good too 👍 

Since we're not in a rush to deploy this (i.e. there's no other tasks currently blocked by this) should we apply the `[Status] String Freeze` label? That way we'll only merge once translations are complete.

**Review by wojtekn — APPROVED** [review]

**Comment by mpkelly** [comment]
Looks good to me 👍

**Comment by danielbachhuber** [comment]
> Since we're not in a rush to deploy this (i.e. there's no other tasks currently blocked by this) should we apply the `[Status] String Freeze` label? That way we'll only merge once translations are complete.

Sounds good, added.

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/7967342

Thank you @danielbachhuber for including a screenshot in the description! This is really helpful for our translators.

**Comment by that-mike-bal** [comment]
Just dropping by to say you guys are crazy fast and I appreciate you!

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/7967342).

**Pull request merged**
