### PR TITLE
Limit Global Styles: Update the Pre-Save Notice

### PR DESCRIPTION
**Pull request by rcrdortiz**
#### Proposed Changes
Fixes: https://github.com/Automattic/dotcom-forge/issues/1221

* Changed the copy of the pre-save notice.
* Stop showing the reset link in the notice's message.
* Refactor the observer that inserts the notice in the pre-save panel.

| Before | After |
| - | - |
| image | Screenshot 2022-11-30 at 20 58 57 |

#### Testing Instructions

- Setup:
  - Apply these changes to your sandbox: `install-plugin.sh editing-toolkit update/gs-pre-save-panel-notice`
  - Go to https://wordpress.com/start and create a new free site
  - Add the `wpcom-limit-global-styles` blog sticker to the new site: `add_blog_sticker( 'wpcom-limit-global-styles', 'test', <YOUR_USERNAME>, <YOUR_BLOG_ID>)`.
  - Sandbox the new site.
- Open the Site Editor.
- Open the Global Styles sidebar.
- ⚠️ _(check for regression)_ Ensure the paid Global Styles modal appears.
- Do some changes in the canvas (not on Global Styles just yet) and click "Save".
- ⚠️ Ensure the Global Styles notice does not appear.
- Do some changes to Global Styles and click "Save" again.
- ⚠️ Ensure the Global Styles notice appears and is appended to the correct entity.
- Try playing around with the Global Styles customizations and toggling the pre-save panel.
- ⚠️ Ensure the Global Styles notice behaves as expected (appears and disappears when it should).

#### Pre-merge Checklist

- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

Related to #

### CODE REVIEW

**Review by dsas — CHANGES_REQUESTED** [review]
This isn't working for me 🤔 The 'Are you ready to save' prompt displays but it does not display the warning about needing to upgrade for global styles. I do have the sticker enabled.

The console says
```
Uncaught TypeError: path is undefined
    trackGlobalStylesMenuSelected wpcom-block-editor-global-styles-menu-selected.js:18
    __WEBPACK_DEFAULT_EXPORT__ delegate-event-tracking.js:116
    __WEBPACK_DEFAULT_EXPORT__ delegate-event-tracking.js:111
    delegateCaptureListener tracking.js:865
```

**Comment by dsas** [comment]
Console message comes when switching to e.g. colours in the GS menu, so it's probably unrelated.

I get the same behaviour on blog 212978125 and 212976996 when testing via my sandbox.

Weirdly if I checkout out the branch locally and do a `yarn dev --sync` it does work 😕

**Review by dsas — APPROVED** [review]
Tried again after nuking my dev ETK and it works. I think earlier I had some dev ETK content on my sandbox and that was being used rather than the sandbox install (which goes to prod). sorry.

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/7650133

Thank you @rcrdortiz for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/7650133).

**Pull request merged**
