### PR TITLE
SiteAddressChanger: Add support link to notice copy

### PR DESCRIPTION
**Pull request by spen**
### Summary

In an attempt to better inform folks who are looking to change their site address this PR adds some extra wording and a link that should draw attention to the support documentation we have around this feature/flow.
This should hopefully help avoid accidents in the process and save people from losing their site addresses.

### Testing
There's no real functional change here, so all that needs to be tested is that the link works as expected and directs to the most suitable location within our support docs.
To do so, go to: http://calypso.localhost:3000/domains/manage , choose a site, and then look for the link in the bottom left of the site address changer component, click it and take note of where you land.

Relates to: #22906, cc: @benhuberman

### CODE REVIEW

**Comment by benhuberman** [comment]
Hi @spen -- is there new copy to review here? I can't test using the link, so if there is, a screenshot and/or adding the copy here would really help. Thanks!

**Comment by spen** [comment]
Hey @benhuberman , good shout! Here's the current state of the copy:

screen shot 2018-03-29 at 16 04 05

Note that I'm fully expecting this to be way off the mark - looking for to some better suggestions! :)

**Comment by benhuberman** [comment]
Thanks for the screenshot @spen!

I'd suggest a couple of tweaks to your copy:
> Once you change your site address, [current URL] will no longer be available.
[LINKED] Before you confirm the change, please read this important information.

My thinking is that it's better to do this in the active voice, and that if we really want to increase the chance people click on that link, adding a little more urgency is probably warranted (and "support doc" often sounds like "something I don't need to read, ever" :) ).

**Comment by spen** [comment]
> adding a little more urgency is probably warranted

I'd agree there :)

> support doc" often sounds like "something I don't need to read, ever" 

Also agree!!

Thanks for getting back so quickly, changes are a'comin'!

**Comment by spen** [comment]
> the links is set to open in a new tab — iirc convention in Calypso is to let the user decide

That would explain why I found so few examples of `target:_blank` in other cases - change is a-comin'


> we might want to change the URL of the support page (/changing-blog-address/) to /changing-site-address/

Agreed there. There's some copy in the doc that could use an update too.
I'll not make a change here though, when the URL is updated the one referenced here should redirect to the new URL.

**Pull request merged**
