### PR TITLE
Fix/notice styling

### PR DESCRIPTION
**Pull request by jameskoster**
Addresses the notice styling issues outlined in #19910 

notices

### CODE REVIEW

**Comment by ryelle** [comment]
FYI, @drw158 just pushed an compact notice alignment fix in #19921

**Comment by jameskoster** [comment]
@drw158 thanks for jumping in. I originally planned to implement your fix as well but having the icon aligned centrally didn't feel right to me, particularly on longer (taller) notices.

Please take a look at this and let me know what you think.

**Comment by jameskoster** [comment]
Where are you seeing that? I see this;

notice

Fixing that empty icon section now.

**Comment by drw158** [comment]
I'm seeing it at Domains > Add Domain (first screenshot is current, second screenshot is from before the dark notice update).

**Comment by jameskoster** [comment]
Without the icon section the dark notice styling just looked way too heavy here. These aren't really notices anyway. So I tweaked the colors for them;

pills

@drw158 if you're happy let's merge and deploy :)

**Comment by aidvu** [comment]
They were kind-of color coded, and easier to notice. :) @jameskoster

**Comment by klimeryk** [comment]
Thanks for providing a fix for those pills too, @jameskoster. We obviously abused the notices here a bit :/ But as @aidvu mentioned, we should preserve the colors and styling for them, if possible. The reason is (as I've mentioned on Slack) that this section is heavily A/B tested, and these flags were actually increased the conversion rates _a lot_. So any changes to them could result in further changes to CR - which in turn could influence other A/B tests that we current have in this section.

**Comment by jameskoster** [comment]
Spoke with @klimeryk on Slack and agreed to revert these flags to their _original_ colorings as they have been tested and confirmed to increase conversions.

pills

**Comment by klimeryk** [comment]
Just a quick follow-up - @danhauk raised the same issue in https://github.com/Automattic/wp-calypso/issues/19933, we'll fix it separately.

**Pull request merged**
