### PR TITLE
adds the social proof test on the premium plan teaser

### PR DESCRIPTION
**Pull request by lucasartoni**
Adds a test to validate the social proof teaser at the top of the Premium Plan on plans page

### CODE REVIEW

**Comment by lucasartoni** [comment]
screen shot 2016-02-02 at 13 02 02
"Our most popula plan" is the current teaser and default variation
`localStorage.setItem('ABTests','{"plansSocialProof_20160202":"mostPopular"}')`

screen shot 2016-02-02 at 13 01 37
"Best value" is the proposed variation
`localStorage.setItem('ABTests','{"plansSocialProof_20160202":"bestValue"}')`

**Comment by lucasartoni** [comment]
cc @breezyskies

**Comment by mtias** [comment]
What do you think of adding a version without any text at all?

**Comment by lucasartoni** [comment]
@mtias I have nothing against it, however it's outside the scope of the test. We wanted to check if a direct value proposition is stronger than a vague social proof. We can easily add an empty variation.

**Comment by mtias** [comment]
:+1:

**Comment by lucasartoni** [comment]
screen shot 2016-02-02 at 16 24 24
noTeaser variation, without any teaser, as suggested by @mtias 
`localStorage.setItem('ABTests','{"plansSocialProof_20160202":"noTeaser"}')`

**Comment by mikeshelton1503** [comment]
LGTM :+1:

**Pull request merged**
