### PR TITLE
Email stats: update icons

### PR DESCRIPTION
**Pull request by simison**
Part of https://github.com/Automattic/jetpack/issues/40659

Designs:
i1: p1HpG7-v7v-p2
i2: p1HpG7-vch-p2

This isn't yet exactly like in designs but nudges us towards [combining the two tabs](https://github.com/Automattic/jetpack/issues/40659) with less changes.

## Proposed Changes

* Update email stats icons; uses WP icons instead of Gridicons

#### Before
Screenshot 2024-12-23 at 15 22 01
Screenshot 2024-12-23 at 15 22 04

#### After
Screenshot 2024-12-23 at 15 19 57
Screenshot 2024-12-23 at 15 19 53

## Why are these changes being made?

*

## Testing Instructions

* See open/click email tabs.

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
    - [ ] For UI changes, have we tested the change in various languages (for example, ES, PT, FR, or DE)? The length of text and words vary significantly between languages. 
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/17076074

Some locales (Hebrew, Japanese) have been temporarily machine-translated due to translator availability. All other translations are usually ready within a few days. Untranslated and machine-translated strings will be sent for translation next Monday and are expected to be completed by the following Friday.

Thank you @simison for including a screenshot in the description! This is really helpful for our translators.

**Review by edanzer — APPROVED** [review]
Tests as expected and changes look good.

**Comment by edanzer** [comment]
Resolved a small merge conflict following my merge of https://github.com/Automattic/wp-calypso/pull/97726

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/17076074).

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/17076074).

**Pull request merged**
