### PR TITLE
Jetpack Backup: Add backup warnings list

### PR DESCRIPTION
**Pull request by jwebbdev**
#### Proposed Changes

* Adds a list of warnings to the daily backup if warnings exist
* The warning category messages are currently being reviewed

#### Testing Instructions

* Have the backup team give you access to a site with warnings
* Visit the Calypso live links below and access those sites to view the changes
* Review a site without warnings to ensure no warning messaging appears (or other issues)

Screen Shot 2022-06-02 at 4 39 57 PM

### CODE REVIEW

**Review by mavegaf — APPROVED** [review]
Looks nice!

**Review by jeffgolenski — CHANGES_REQUESTED** [review]
@jwebbdev Awesome work. Appreciate the quick changes you made based on feedback! One last item that I noticed in the file list
Screen Shot 2022-06-06 at 11 15 53 AM

Can we just give that list a style of `overflow-x: auto;` instead of `overflow-x: scroll;` - this way the scrollbar holder will be hidden if it's not needed.

**Comment by jwebbdev** [comment]
> Can we just give that list a style of `overflow-x: auto;` instead of `overflow-x: scroll;` - this way the scrollbar holder will be hidden if it's not needed.

Yep, updated.  Thanks for the review.

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/7361042

Thank you @jwebbdev for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/7361042).

**Pull request merged**
