### PR TITLE
Editor: Move the HTML Toolbar methods into their own utility component

### PR DESCRIPTION
**Pull request by Copons**
The Post Editor is not the only editor that uses the HTML Toolbar (see #21663).

This PR moves most of the reusable methods out of `EditorHtmlToolbar` and into an utility folder that includes:
- The `utils.js` file, with all the reusable methods.
- Two reusable Dialog components. 

The `components/html-toolbar` folder does not contain any `index.jsx` file, or, in other words, there is no generic `HtmlToolbar`.
The reason is that the Editor uses a LOT of custom stuff: the Insert menu, the sticky/scroll-y behaviour, etc.
I could have done a more complicated refactor, trying to make the entire toolbar 100% reusable, but I'm not sure it would make sense with Gutenberg around the corner.
On the other hand, it seems weird to just dumbly duplicate half of the Post Editor toolbar into the Comment Editor toolbar.

## Testing instructions

This shouldn't change the behaviour of the Editor in any way, so the idea is to do a smoke test on the Editor in HTML mode, and see if all the buttons still work, and work as expected.

### CODE REVIEW

**Comment by gwwar** [comment]
> On the other hand, it seems weird to just dumbly duplicate half of the Post Editor toolbar into the Comment Editor toolbar.

@Copons I usually like having at least 2 usages before abstracting out pieces, as it can be very difficult to guess what implementations will need. Do you think there's enough overlap here that it'd be worth it?

**Comment by Copons** [comment]
> Do you think there's enough overlap here that it'd be worth it?

@gwwar My reasoning is this: https://github.com/Automattic/wp-calypso/pull/22040
To add the toolbar to the edit comments, I've got to:
- duplicate all the toolbar methods (~200 lines)
- duplicate the style (~90 lines)
- reuse the dialogs with an awkward import from `post-editor/editor-html-toolbar` into `my-sites/comments/comment`, or duplicate them (~300 lines)

That's quite a lot of lines!

On the other hand, there is a reason against this: what will happen to the post editor HTML view when Gutenberg happens?
Will it be replaced by Gutenberg, rendering the HTML toolbar obsolete, and making this whole change unnecessary?

**Comment by Copons** [comment]
> Got a slew of errors I don't see in prod when trying to add an image from "Free photo library":

@kwight I believe it's not related to this change, though.
Basically, when changing the `source` of an `EditorMediaModal`, we do lots of logic, including a `clearSite` here:

https://github.com/Automattic/wp-calypso/blob/master/client/lib/media/list-store.js#L234

which calls this:

https://github.com/Automattic/wp-calypso/blob/master/client/lib/media/list-store.js#L90-L94

For some reasons, in some cases (not always! usually if I click the Free Photo Library button "early" while other stuff is still loading—although, that doesn't happen in WYSIWYG mode) the `MediaListStore._activeQueries[ siteId ]` object is not initialized yet.
So, trying to access its properties (e.g. `MediaListStore._activeQueries[ siteId ].nextPageHandle`) throws the error and kills the page.

It gets fixed by adding to the action handler the `MediaListStore.ensureActiveQueryForSiteId` [helper function](https://github.com/Automattic/wp-calypso/blob/master/client/lib/media/list-store.js#L84-L88) that initializes the object:
```es6
switch ( action.type ) {
	case 'CHANGE_MEDIA_SOURCE':
		MediaListStore.ensureActiveQueryForSiteId( action.siteId );
		clearSite( action.siteId );
		MediaListStore.emit( 'change' );
		break;
	// ...
}
```

Though, is it really needed or is it just an easy workaround?
Looping in @johngodley who authored `clearSite`!

**Comment by gwwar** [comment]
> Will it be replaced by Gutenberg, rendering the HTML toolbar obsolete, and making this whole change unnecessary?

It's pretty likely, though hard to say what the timeline looks like. 

I would say make sure we're okay with coupling this abstraction to both editors. Do we think needs will stay in lockstep, or will we start diverging? (~300 lines of code duplication isn't really a big deal in comparison with an awkward abstraction.)

**Comment by kwight** [comment]
@Copons Ah, OK, I'll remove my blocker.

**Comment by Copons** [comment]
Not relevant anymore.

**Pull request closed without merging**
