### PR TITLE
Stats: Avoid showing low scores in January

### PR DESCRIPTION
**Pull request by grzegorz-cp**
#### Proposed Changes

* show the previous year's annual stats in January

#### Testing Instructions

* open a live branch
* navigate to the Insights page and verify that 2022 is visible in the annual highlight component
* verify that you can still see 2023 when using the arrows on the right-hand side
* go to another blog and check that it loads 2022 instead of 2023

#### Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

Related to #72106

### CODE REVIEW

**Review by annacmc — APPROVED** [review]
Nice one! Tested out & works as expected with the correct 2022/2023 years on multiple different blogs 🙌  LGTM 👍

**Comment by kangzj** [comment]
I have mixed feelings over the approach - it does provide some kind of convenience for user to review the previous year in Jan but it could also be confusing as well 🤔 Wondering what the rest of the team think @Automattic/red

**Comment by wilmersondasilva** [comment]
> I have mixed feelings over the approach - it does provide some kind of convenience for user to review the previous year in Jan but it could also be confusing as well 🤔 Wondering what the rest of the team think @Automattic/red

Maybe we can decide if we go with 2022 or 2023 based on the 2023 data? For instance, if there are at least three properties with a value greater than 0 for 2023, we show 2023 or something similar to this.

**Comment by grzegorz-cp** [comment]
It's not like we are cutting off the people from the data. We are only "automatically clicking the arrow" in January.
It's also a simple logic. In January, we show the previous year for people to reflect on.

I'm afraid that it will be much more arbitrary if we start checking specific stats because we either check for several 0 stats or a number of posts. Even one new post can still result in many "0"s. This feels like a balancing game which will always be bad in some cases.

**Review by kangzj — APPROVED** [review]
LGTM

**Pull request merged**
