### PR TITLE
Update the .eslines.json config file to the new format

### PR DESCRIPTION
**Pull request by jsnajdr**
Update the `.eslines.json` file to use the new format introduced in Automattic/eslines#6. Work in progress intended for testing and review. Before this can be merged, new version of eslines needs to be released and the version in `package.json` bumped.

### CODE REVIEW

**Comment by jsnajdr** [comment]
Updated the config file to use `rulesNotToDowngrade` option of the `downgrade-unmodified-lines` processor instead of adding an extra `enforce` to the pipeline. That option was recently (re)added in  Automattic/eslines#6.

**Comment by nosolosw** [comment]
We'll also need to bump `eslines` version in `eslint-eslines` utility.

I've created two test cases that confirm that `eslines` latest version works in CircleCI as well: https://github.com/Automattic/wp-calypso/pull/17329 and https://github.com/Automattic/wp-calypso/pull/17332 - to be deleted after this is merged. Documented at [eslines/RELEASE.md](https://github.com/Automattic/eslines/blob/master/RELEASE.md).

**Comment by jsnajdr** [comment]
I just pushed a new commit that adds the `filter-when-format` processor to Calypso config.

To test:
1. Checkout this branch in Calypso
2. Install the patched eslines manually: `npm i https://github.com/Automattic/eslines#add/prettier-formatting`
3. Choose some random JS module and add this code to it (it's an example where Prettier and `indent` ESlint rule have different opinions):
```js
export const i = null
  ? {
      a: 1,
      b: 1,
    }
  : {
      c: 1,
      d: 2,
    };
```
4. Format with it Prettier and check that the `/** @format */` was added at the start.
5. Commit the changes and run `npm run lint:js`
6. Check that no `indent` rule errors are reported
7. Remove the `/** @format */`, amend the commit and run `lint:js` again
8. Check that the `indent` error is reported this time

**Comment by samouri** [comment]
This is really exciting! Can't wait to test this out today

**Comment by samouri** [comment]
currently getting an error when trying to follow testing instructions because the `package.json` is technically invalid.   I left a comment [here](https://github.com/Automattic/eslines/pull/5/files#r134311884).


Stacktrace of the error is:
```
➜  wp-calypso git:(update/eslines-config) ✗ npm i https://github.com/Automattic/eslines\#add/prettier-formatting
npm ERR! addLocal Could not install /var/folders/st/xlvkk_ys3xgd1s22w_1x8dg00000gn/T/npm-9614-c31a93ce/git-cache-3dfaf4a1/94663971052a1bb76b55fac1117739a7182f79f5
npm ERR! Darwin 16.6.0
npm ERR! argv "/Users/jake/.nvm/versions/node/v6.11.2/bin/node" "/Users/jake/.nvm/versions/node/v6.11.2/bin/npm" "i" "https://github.com/Automattic/eslines#add/prettier-formatting"
npm ERR! node v6.11.2
npm ERR! npm  v3.10.10
npm ERR! file /var/folders/st/xlvkk_ys3xgd1s22w_1x8dg00000gn/T/npm-9614-c31a93ce/git-cache-3dfaf4a1/94663971052a1bb76b55fac1117739a7182f79f5/package.json
npm ERR! code EJSONPARSE

npm ERR! Failed to parse json
npm ERR! Unexpected token 't' at 25:6
npm ERR!     "test-filter-when-format": "./node_modules/.bin/tape tests/test-filter-when
npm ERR!      ^
npm ERR! File: /var/folders/st/xlvkk_ys3xgd1s22w_1x8dg00000gn/T/npm-9614-c31a93ce/git-cache-3dfaf4a1/94663971052a1bb76b55fac1117739a7182f79f5/package.json
npm ERR! Failed to parse package.json data.
npm ERR! package.json must be actual JSON, not just JavaScript.
npm ERR! 
npm ERR! This is not a bug in npm.
npm ERR! Tell the package author to fix their package.json file. JSON.parse
``

**Comment by jsnajdr** [comment]
@samouri I fixed the typo in the `eslines` PR and merged it. The necessary changes are now in master already!

**Comment by samouri** [comment]
I believe this PR also needs to update our package.json + npm-shrinkwrap right?

I haven't extensively tested but I can confirm this PR + installing latest eslines fixes the indent issue

**Comment by jsnajdr** [comment]
> I believe this PR also needs to update our package.json + npm-shrinkwrap right?

Yes, that's right. We can do that after the new version of `eslines` is released in NPM. @nosolosw said he will do the release on Thursday.

Thanks for testing this, @samouri! 👍

**Comment by nosolosw** [comment]
For the record, I have everything prepared for releasing [eslines v1.0.0](https://github.com/Automattic/eslines/pull/13) and [eslint-eslines v0.0.4](https://github.com/Automattic/eslint-eslines/pull/1). Those are the version we need to update our package with.

I want to coordinate with some happychat devs before publishing this to npm. I'll do that on Monday first thing in the morning.

**Comment by nosolosw** [comment]
Releases are now in npm. We need to update Calypso's package.json with the newest versions and update the shrinkwrap. Is this something you plan to do @jsnajdr or do you want me to help? Happy to do it either way.

**Comment by nosolosw** [comment]
Couldn't test this [as per the instructions provided here](https://github.com/Automattic/wp-calypso/pull/17211#issuecomment-323683575). Tried with Atom 1.19, and the `prettier-atom` package, which I understand it seeks prettier in the `node_modules` folder (in Calypso case, will be `calypso-prettier`). I've got this error when I try to format a simple file or apply the code suggested by Jarda:

prettier-atom-error

As suggested by @jsnajdr and @samouri this seems [a known issue](https://github.com/atom/atom/pull/14761) that will be solved in future releases of Atom. I tried building Atom myself but I ran into some problems on Ubuntu 16.04. Didn't have the time to dig into the root cause.

@jsnajdr would you mind testing this one? Also, would love if you could recreate the shrinkwrap, when I do it, `fsevents` dependency is removed because I'm on a Linux platform.

**Comment by jsnajdr** [comment]
Thanks @nosolosw! I updated the shrinkwrap file on macOS and committed the result. I verified that the only change is adding `fsevents` back and nothing else.

I also tested the pre-commit hook on a file with an `indent` rule violation, with and without `@format`. Works as expected.

@samouri Can you please do one last test round and see if we can finally merge? :tada:

**Comment by samouri** [comment]
tested:
- [] file with `@format` and style violations. should not error.
- [] file with `@format` and style _and_ non-style violations (no-undef). only non-style violations should error
- [] file without `@format` and with style violations.  should error.

**Pull request merged**
