### PR TITLE
Gutenboarding: remove page templates 

### LINKED ISSUE #42917: Sites new endpoint: avoid making a remote request to fetch the mixed template
From pbxlJb-cH-p2:

> The sites/new endpoint is making a remote request to the Template Mill API endpoint. This seems like an unnecessary network request. If the logic for that endpoint largely lived in a helper class, we could call the helper class here instead of making another API request. This would help remove dependencies between API endpoints.

### Tasks:

- ~Create a helper class that can be shared with Template Mill Class and other classes e.g., `site/new` or to return template data.~ Done in https://github.com/Automattic/wp-calypso/issues/42914
- Delete the [page templates in Calypso](https://github.com/Automattic/wp-calypso/tree/master/static/page-templates/templates)

Make sure to advertise this widely so folks know what is going on :)

D45036-code

### PR DESCRIPTION
**Pull request by ramonjd**
## Changes proposed in this Pull Request

In D45036-code we moved the Gutenboarding page template config JSONs to the backend. 

This commit deletes the page templates stored on Calypso as they are no longer being used.

## Testing instructions

Head over to `/new` and create a few sites. 

You should see the corresponding page template content for each design in the preview and the created site.

Fixed #42917

### CODE REVIEW

**Comment by p-jackson** [comment]
This is the code that is trying to load the templates from the front end: 259e8-pb
Not sure if it's able to `require` code from wpcom

**Comment by ramonjd** [comment]
> But maybe we don't care about that tool anymore. 

Thanks for testing @p-jackson ! I have seen no evidence that anyone uses that tool at all. There have been no new page templates or variations of them published. 

> If we did want to save it we could maybe just remove the ability to point at a specific branch and change the implementation so it grabbed the templates from the backend lib?

Good suggestion. We should probably do it just in case, and keep this PR open until it's working.

**Comment by ramonjd** [comment]
> Personally, I think if it doesn't end up being trivial to get the tool to use the backend then I'd just leave it broken.

Easy to do D46153-code

The tool itself is, I think, ready to be retired anyway. :P

**Comment by ramonjd** [comment]
I had to revert this. There was a problem with the demo API endpoint that wasn't apparent during testing: it was still referring to page templates that were in production.

Fixing in D46207-code

**Pull request merged**
