### PR TITLE
Framework: Include HelloVote notice in Layout

### PR DESCRIPTION
**Pull request by aduth**
This pull request seeks to add a new notice to encourage users to manage a yet-to-be-added setting for controlling a vote prompt on their site. The included text and design are very much unfinished and feedback or patches are welcome.

Notice

The intent of the notice is that it be shown only once, and that the user's preference to dismiss it be remembered permanently. This is also a limited-time component, expected to be removed in approximately one month.

__Testing Instructions:__

Verify that the notice is shown when navigating to any site-specific section, and that it is dismissed when clicking either the dismiss button or the Opt In action. The action should navigate you to the site settings screen.

If you need to reset your preference, you should navigate to [the REST API console](https://developer.wordpress.com/docs/api/console/), enter `POST /me/settings` as the URL, and `calypso_preferences={"helloVoteNoticeDismissed":null}` as the body.

cc @nylen

### CODE REVIEW

**Comment by nylen** [comment]
Needs updated text, as you mentioned.  Maybe "Encourage our US-based users to register to vote"?

Also, the notice is shown on the `/settings/general/$site` screen and it probably shouldn't be.  I'm not sure the best way to prevent that.

We should track clicks on both the opt-in button and the dismiss button.  Stat `hello-vote` with value `calypso-opt-in` or `calypso-dismiss` should be fine.

Apart from that, the code looks good & works well.

> This is also a limited-time component, expected to be removed in approximately one month.

Sooner than that - the last set of voter registration deadlines is around October 12th (pb6Nl-bjq-p2).

**Comment by nylen** [comment]
I forgot to mention that we also need to check if the user is a site admin.

**Comment by aduth** [comment]
Thanks for the feedback @nylen !

>Needs updated text, as you mentioned. Maybe "Encourage our US-based users to register to vote"?

See fd4d290, went with: "Encourage your US-based visitors to register to vote by adding a subtle prompt to your site | Manage Settings | X"

>Also, the notice is shown on the /settings/general/$site screen and it probably shouldn't be.

See d2ff44a

>We should track clicks on both the opt-in button and the dismiss button.

See 9b44a9b

>I forgot to mention that we also need to check if the user is a site admin.

See b01479e

---

Apart from above, also added basic geo state, with query component to request and detect if browser is US-based to determine whether notice should be shown. I haven't yet added JSDoc or tests since I wasn't certain if this is the direction we'd want to go (and to have sooner review).

**Comment by nylen** [comment]
I am not sure how many requests/second we can throw at geo.php but it seems worthwhile to me to avoid unnecessary requests there unless all the other conditions for showing the notice are met.  Took a shot at this in 73ebda4.

The code looks good to me and the notice functionality works well.

**Comment by nylen** [comment]
Added a stylesheet to fix a couple of issues: editor sidebar was obscuring the notice, and icons should be vertically centered when the notice goes multiline.

Editor sidebar width logic is based on [`.post-editor__content` styles](https://github.com/Automattic/wp-calypso/blob/e95b557/client/post-editor/style.scss#L33-L41).

### Before

image

### After

image

**Comment by aduth** [comment]
Took another close look after all the recent changes and everything seems to be working well for me. Only issue I noticed was that when switching from site-specific Themes screen to "All Sites" view, the notice does not disappear. This seems to be a general issue where the [`setAllSitesSelected`](https://github.com/Automattic/wp-calypso/blob/da0130902b1e8379628499f0487d8f29e18cabaa/client/state/ui/actions.js#L27-L38) action creator is not being dispatched in the [sites controller](https://github.com/Automattic/wp-calypso/blob/da0130902b1e8379628499f0487d8f29e18cabaa/client/my-sites/controller.js#L164) as would be expected. I don't think it's worth holding up a merge, but @ockham do you have any hints as to why this is an issue? We can plan to open a separate pull request.

**Pull request merged**
