### PR TITLE
BBE : Prevent files being uploaded that are not of allowed types

### PR DESCRIPTION
**Pull request by ddc22**
#### Proposed Changes
* On upload checks the file extension and prevents user from uploading files that are not allowed
image

#### Testing Instructions
- Complete BBE Purchase via /start/do-it-for-me
- On the website content page try to upload a file that is not allowed
- Make sure above error is shown
- Try to upload an allowed file, everything should work as expected.

*

#### Pre-merge Checklist

- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

Related to #

Fixes Automattic/martech#1274

### CODE REVIEW

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/7636791

Thank you @jdc91 for including a screenshot in the description! This is really helpful for our translators.

**Review by aneeshd16 — APPROVED** [review]
LGTM!

**Comment by ddc22** [comment]
Shipping this before translations are completed because this is an edge case and we can afford to show an english error message for this, until the Spanish translation is completed.

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/7636791

Thank you @jdc91 for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/7636791).

**Pull request merged**
