### PR TITLE
Activity log: Use Activity Query Manager

### PR DESCRIPTION
**Pull request by sirreal**
* Move to Activity Query Manager
* Query by days (not by month). Each day queries its own activity and is "aware" of whether it's loading, empty, or has logs.

Empty month views are not yet implemented but can be restored. I'd like to get some initial feedback on the experience.

## Testing
* Visit https://calypso.live/stats/activity?branch=update/activity-log/use-aqm

Replaces #17135

### CODE REVIEW

**Comment by sirreal** [comment]
@keoshi I've been sitting on this for too long. I'd like to get some early feedback on what you think of the experience, specifically the way days load independently.

If the feedback is positive, I'll work to restore the empty month views then land this PR. In the case of the empty month, the days would load, then switch to the empty view after all the day queries resolved.

With something like D7316-code, this could become simpler.

**Comment by keoshi** [comment]
@sirreal Hadn't seen this one before, apologies for giving my feedback just now. My first impressions were:

- Days load up in a random order, so I might get unloaded items between already loaded ones. It's not bad, but it feels weird and could look like a mistake. This could be easily sorted if we can get them loaded exactly in the order they're presented.

image

- On the first try, I got a page flash after all items were loaded. Not sure if it was just a Calypso refresh or if it has anything to do with this issue in particular, but don't remember seeing that before.

**Comment by sirreal** [comment]
@keoshi Thanks for the feedback!

> Hadn't seen this one before, apologies for giving my feedback just now

I hadn't opened it up for feedback yet, no apology necessary 🙂 

> Days load up in a random order, so I might get unloaded items between already loaded ones. It's not bad, but it feels weird and could look like a mistake. This could be easily sorted if we can get them loaded exactly in the order they're presented.

That's actually quite complicated with this implementation, but D7316-code is a proposal to have the API provide daily counts over a range. When and if we land that, it could provide us that "shape" very quickly, then we could load a day's activity as needed.

It sounds like this proposal is a step backwards UX-wise, so I'll probably take a different direction.

> On the first try, I got a page flash after all items were loaded. Not sure if it was just a Calypso refresh or if it has anything to do with this issue in particular, but don't remember seeing that before.

I just noticed that as well, I'll need to look at what's happening.

**Comment by sirreal** [comment]
Closing in favor of #18234

**Pull request closed without merging**
