### PR TITLE
Remove/disconnect from batch edit plugins

### PR DESCRIPTION
**Pull request by enejb**
This PR removes the ability to disconnect Jetpack when in plugin batch edit mode. 

Now we show a dialog with a button that takes the user to manage jetpack. 
The dialog box appears after the deactivation of all the other plugins is done. 

(updated)
screen shot 2017-04-06 at 12 03 11

If only Jetpack is selected then we do not show the activate and deactivate buttons at all. 
screen shot 2017-03-24 at 12 36 55

Also we skip jetpack when we activate and deactivate plugins in batch mode. We don't show any indication that we are performing anything in Jetpack

### CODE REVIEW

**Comment by rickybanister** [comment]
I don't think the dialog is the right way to go here.

Can we show a second global notice after the '10 plugins successfully deactivated' that says 

`Jetpack cannot be deactivated from WordPress.com | Manage connection`

Or similar.

cc @beaulebens for input

**Comment by enejb** [comment]
I was expecting things to change so I didn't put much effort into the dialog. 

Putting a link into the notice is a good idea. Although it might be hard since it is currently used to show that plugins succeeded or failed deactivating. But maybe we can add a separate notice? 

Maybe we can show just a regular link the dialog and make it look nicer?

**Comment by folletto** [comment]
I agree with Rick, however I've an additional question. Given this:

> This PR removes the ability to disconnect Jetpack when in plugin batch edit mode.

Can't we just avoid showing the checkbox so it's not selectable, and this would avoid any notification, error or else?
And if we want to provide a link, change the details line with the text and the link in bulk edit mode?

**Comment by enejb** [comment]
> Can't we just avoid showing the checkbox so it's not selectable, and this would avoid any notification, error or else?

we still want users to be able to bulk set Jetpack to autoupdate across all sites. 
Removing the checkbox would prevent a user from doing just that.

**Comment by rickybanister** [comment]
I think we can either go with my proposal above or we can remove the ability to bulk enable auto-updates for Jetpack like @folletto said. Jetpack is a different kind of plugin in this case since it facilitates the connection to even see this screen. I'm happy to treat it as such. 

I don't see it as a problem to let people try to bulk edit Jetpack and then see a helpful notice really. Let's just make sure we have a tracks event here so we can see how often it's an issue.

**Comment by enejb** [comment]
@rickybanister  and @folletto I updated the screenshot. 
Does it look good design wise?

**Comment by rickybanister** [comment]
I don't think that's going to work. I'll work on an alternate mockup.

**Comment by rickybanister** [comment]
We could do something more like a warning here:

image

And to avoid the awkwardness of the notice-action next to the dismiss X we can use an inline link. We don't want to encourage people to disconnect since they will lose access to WordPress.com. 

If we don't think the notice is working, we could potentially trigger the disconnect dialog from #12401 to appear here, but I think that could be a pretty big distraction. I'd rather this feel verboten.

**Comment by enejb** [comment]
cc: @rickybanister  
Updated to look like this
screen shot 2017-04-06 at 12 03 11

**Comment by rickybanister** [comment]
Looks great, ship it

**Pull request merged**
