### PR TITLE
Theme Details: Add a Site Selector Modal

### PR DESCRIPTION
**Pull request by Copons**
Fixes https://github.com/Automattic/dotcom-forge/issues/5384

## Proposed Changes

* Add a new Site Selector modal in the Theme Details page, intercepting the primary CTA and upsell banner actions, when the section is opened by a logged-in user with multiple sites but without a site selected.

Screenshot 2024-02-07 at 13 11 29

### Changes from Design Specs

This PR introduces several design changes to reduce the complexity to a minimum, and reuse existing components.

It is my opinion that the component remains usable, with a net UX improvement over the status quo. @lucasmendes-design, here are the changes from p9Jlb4-aFy-p2, and my reasons:

* **The Site Selector Component**
   * There are various (many!) implementations of site selector components, from the old one used as interstitial, to the new list on the Sites Dashboard. They rarely share logic, and all of them are very opinionated in their specific use cases.
   * The only one that is designed and developed to be reused is indeed the old one — which is what I've used here (taking advantage of a new-ish optional redesign).
   * The difference is 1 line of code versus several hundred, reimplementing the same stuff for the nth time.
* **The Site Selection UX**
   * Instead of a radio-like selection (toggle radio on site item -> use primary button to confirm the selection), this component lets us select a site by clicking directly on it.
   * IMHO this is more straightforward, and matches the following change...
* **The Theme's Primary Action UX**
   * The design specs proposed this flow: `[click theme CTA -> select site -> click modal CTA -> perform primary theme action]`.
   * Given the complexity of theme actions (largely unnecessary and self-inflicted over the last decade), this would require reimplementing a lot of logic into the modal.
   * My proposed simplification: `[click theme CTA -> select site -> refresh page with the site selected]`; once refreshed with the site selected, the Theme Details page will use all the existing logic to determine the theme's primary action.
* **The Modal Title**
   * I've used the Core Modal component, which is not designed for a restyle of the title (larger Recoleta font).
   * I could use the Calypso Modal component, but I'd personally lean towards using Core components whenever possible.
   * I don't have a strong opinion here, and I'm open to change. 🙂 

## Testing Instructions

* Use a user with multiple sites.
* Enter a Theme Details page without site fragment (e.g. `/theme/pomme`).
* Click on "Select a site to activate".
* Check that the site selection modal appears correctly.
* Select a site.
* Check that the page is refreshed with the site fragment, and that the primary CTA button is updated accordingly (e.g. "Activate this design").
* Check that there's a notice that says "You have selected the site [SITE TITLE]."
* Check that clicking on the notice's "Choose a different site" reopens the site selector modal
* Try the same on themes of different tiers (e.g. Premium, Partner, Community).
* Ensure both the theme's primary CTA and any upsell nudges open the Site Selector modal instead of sending to a with-theme flow.

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

**Comment by lucasmendes-design** [comment]
Hi team, here are some thoughts about the flow: 

- I didn't notice that I switched the site. There is no indication of that.  
- I also waited a bit more, expecting the theme to be activated, but I needed to click it again (button "Activate this design"). 
- What if I select the wrong site by mistake? How can I go back and change the site? I'm not sure. Since we removed the radio button from the original design this could be something common. 
- Once I switch site, if I click on "Back to themes", I would go to the site I selected or the "Main" site?
- Overall, I was a bit confused by this change.

**Comment by xavier-lc** [comment]
Hi @lucasmendes-design,

> I didn't notice that I switched the site. There is no indication of that.
> I also waited a bit more, expecting the theme to be activated, but I needed to click it again (button "Activate this design").

I agree that it's not entirely clear that you need to select a site before being able to activate the theme. I think that while the site is unselected, we could change the text button from `Pick this design` to `Select a site to activate this design`. And then, add a success notice confirming the user which site has been selected.

> What if I select the wrong site by mistake? How can I go back and change the site? I'm not sure. Since we removed the radio button from the original design this could be something common.

It seems a valid concern. What about a `Choose a different site` action inside the notice? 

> Once I switch site, if I click on "Back to themes", I would go to the site I selected or the "Main" site?

Currently, you'd stay on the site you selected.

> Overall, I was a bit confused by this change.

I understand. We're trying to keep the project with a minimal scope, avoiding introducing complex logic into the modal.

**Comment by lucasmendes-design** [comment]
Hi there, 

> from Pick this design to Select a site to activate this design

I think is way too big for a button =/ 
image

> What about a Choose a different site action inside the notice?

Which notice? 

> I understand. We're trying to keep the project with a minimal scope, avoiding introducing complex logic into the modal.

I got it :) but I didn't know that this was a heavy lift and a very complex modal. Maybe we can change the direction and select the option 1 from my post. WDYT? cc: @Copons 

P2 - https://dotcomdesignp2.wordpress.com/2024/01/19/site-selector-page-i1/#site-selector-version-1-full-page 

image

**Comment by xavier-lc** [comment]
> I think is way too big for a button =/

Yup, you're right :/

> Which notice?

A notice like this, for example:

image

**Comment by lucasmendes-design** [comment]
Thanks @xavier-lc 🙏🏽 

I synced with Jacopo this morning and I think we could use the notice you just mentioned. It's a good idea as well. Let me know your thoughts on the changes below: 

**1. Button copy `Select a site to activate`.** 
image

**2. After selecting this option, we show the modal.** 

**3. After site selection, we show the notice and we change the button copy to `Activate this design`.** 
image

**Comment by Copons** [comment]
Thanks @lucasmendes-design!

@xavier-lc some clarifications about the button copy for dev convenience. In bold, the required change.

- These changes are only intended for the "all sites" view (when the user is logged in and has no site selected).
- **In the "all sites" view, the button becomes `Select site to activate` regardless of site plan or theme tier.**
- Once the site is selected, the button will use the original copy depending on site plan and theme tier: `Activate this design`, `Upgrade to activate`, etc.

---

About the notice, it's been a while since I've created one in Calypso!

Do you think we need a full-width notice, or could we just do a simple snackbar? It's less prominent, but also less overbearing. 🤔 

Anyway. Back in the days, we used to use Global Notices, controlled by Redux actions (e.g. `successNotice`).

Here an [ancient example](https://github.com/Automattic/wp-calypso/blob/78137983abfe0da05af83d858f5df46ebbca51b5/client/my-sites/comments/comment/comment-actions.jsx#L107-L115) with an "Undo" button, which could be useful for us too:
```jsx
// dispatch...
successNotice(
  translate( 'You have selected the site {{strong}}%s{{/strong}}.', {
    args: siteTitle, // IMHO the title is better than the slug here, but I don't have strong opinions
    components: { strong: <strong /> },
  } ),
  {
    button: translate( 'Choose a different site' ),
    onClick: () => this.setState( { isSiteSelectorModalVisible: true } ),
  }
);
```

**Comment by xavier-lc** [comment]
@lucasmendes-design @Copons thanks! I'll ping you on Monday with the changes.

**Comment by mmtr** [comment]
I'll move this to "In progress" in our board in the meantime. @xavier-lc feel free to move it back to "Needs review" once your changes are ready.

**Comment by xavier-lc** [comment]
@Copons @lucasmendes-design this is ready for review again

**Comment by Copons** [comment]
To summarize, this is the current flow.
cc @lucasmendes-design 

| 1️⃣ All Sites View | 2️⃣ Select Site Modal | 3️⃣ Single Site View |
|--------|--------|--------|
| Screenshot 2024-02-20 at 14 47 27 | Screenshot 2024-02-20 at 14 47 44 | Screenshot 2024-02-20 at 14 47 52 | 

IMHO, this works well enough, and there are visual clues that _something_ happened after selecting the site from the modal (e.g. the top bar appearing).

Although, I personally got confused by the phrasing of the first CTA and the modal title.

> Select a site **to activate**...

That "to activate" strongly implies that the activation happens along with the site selection, which is incorrect (and, as determined above, very complex from a technical standpoint).

Something like "**First** select a site...", although awful, sounds clearer to me.

ChatGPT suggests changing the preposition to communicate that it's a two-step process: "Select a site **and** activate..."

What do y'all think of:

1. Change the first CTA into **"Select a site and activate"**.
   - This communicates the two-step process. 
2. Change the modal title into **"Select a site"**.
   - Removing "to activate" reinforces that it's the first part of the two-step process, and doesn't set the incorrect expectation of "select site and activate theme" at once.

**Comment by xavier-lc** [comment]
> What do y'all think of:
> 
> 1. Change the first CTA into **"Select a site and activate"**.
>    
>    * This communicates the two-step process.
> 2. Change the modal title into **"Select a site"**.
>    
>    * Removing "to activate" reinforces that it's the first part of the two-step process, and doesn't set the incorrect expectation of "select site and activate theme" at once.

This sounds good to me.

**Comment by mmtr** [comment]
> Change the first CTA into "Select a site and activate"

I think this can still be confusing because it implies the activation can happen after selecting a site, but that's not true if the theme requires an upgrade.

Maybe some of these alternatives can work?
- Select a site to get started
- Select a site to see more
- Select a site to see more options
- Select a site to check access
- Select a site to check eligibility

**Comment by Copons** [comment]
> Select a site to get started

I really like this!

**Comment by xavier-lc** [comment]
@mmtr @Copons copies updated on https://github.com/Automattic/wp-calypso/pull/87260/commits/c56b7fd90fb10da67eb6659c8540171a9d260835

**Review by dsas — COMMENTED** [review]
Minor: It'd be nice if the site selector had the search field focused when it opened. I expected to immediately begin typing.

Probably out of scope: It'd be good if the site selector was more certain about "Some unsupported sites may be hidden.", it should know whether or not it has hidden sites.

Probably out of scope: The dialog size changes as the list is filtered, it's a bit surprising.

**Comment by mmtr** [comment]
Would it be possible to refine the look and feel of the site selector modal? It honestly looks unfinished and disconnected from the rest of wordpress.com :/

Some things I noted:
- Unnecessary gap between the edge of the modal and the list of sites
- Badge too close to the domain
- Search input doesn't look like an input at all because there is no border. The search icon is also missing.
- Weird title popover when hovering a site

While I love shipping small iterations, I think at very least the user interface should feel integrated and complete.

Said that, it seems that the `/themes` path is currently broken in production for logged-in users, so given that this PR improve things, I'm happy to postpone the design changes to a follow-up PR.

**Comment by xavier-lc** [comment]
> Minor: It'd be nice if the site selector had the search field focused when it opened. I expected to immediately begin typing.

Good point, added on https://github.com/Automattic/wp-calypso/pull/87260/commits/36b8c089d5c2805147a090b31b2b6316371c2643

> Probably out of scope: It'd be good if the site selector was more certain about "Some unsupported sites may be hidden.", it should know whether or not it has hidden sites.

I recall seeing a discussion what those unsupported sites are, but can't find it 😓 Do you?

> Probably out of scope: The dialog size changes as the list is filtered, it's a bit surprising.

I'm ok with it. We could set it to `size="fill"` in order to avoid that:

image

**Comment by dsas** [comment]
> I recall seeing a discussion what those unsupported sites are, but can't find it 😓 Do you?

Probably Jetpack sites but I haven't looked.

**Comment by xavier-lc** [comment]
> * Unnecessary gap between the edge of the modal and the list of sites

Do you mean this gap? It seems a reasonable padding to me. Would you have it smaller?

Screenshot from 2024-02-22 14-14-22

> * Badge too close to the domain

👍 I've increased the `margin-right` on https://github.com/Automattic/wp-calypso/pull/87260/commits/84c3e54c44f7e4929cf78c85b948ae335a254439

> * Search input doesn't look like an input at all because there is no border. The search icon is also missing.

I think that's solved by adding `autoFocus` on https://github.com/Automattic/wp-calypso/commit/36b8c089d5c2805147a090b31b2b6316371c2643

> * Weird title popover when hovering a site

I think ti comes from `title` and `aria-label` attributes. I'd rather keep them for a11y purposes. Also, tinkering with the `SiteSelector` component would make this change on many places.

**Comment by xavier-lc** [comment]
@dsas I've made the unsupported sites hidden message conditional on https://github.com/Automattic/wp-calypso/pull/87260/commits/682f27cebb0c6d4a3c06a305de8a7cd2079656da

image

**Comment by mmtr** [comment]
> Do you mean this gap? It seems a reasonable padding to me. Would you have it smaller?

I guess I'm used to the old site selector which has a smaller padding (you can see this in wordpress.com/post for instance):

Screenshot 2024-02-22 at 16 03 07


 If I'm not mistaken, we're re-using the same component here, cannot we just keep the same style so it looks to something like this? 

Screenshot 2024-02-22 at 16 06 02 copy

> 👍 I've increased the margin-right on https://github.com/Automattic/wp-calypso/commit/84c3e54c44f7e4929cf78c85b948ae335a254439

I think I'm missing an increased margin-bottom, since right not is too close to the domain.


> I think that's solved by adding autoFocus on https://github.com/Automattic/wp-calypso/commit/36b8c089d5c2805147a090b31b2b6316371c2643

I think we still need to display a bordered input when it is not focused

> I think ti comes from title and aria-label attributes

Somehow, we're not displaying that on the old site selector visible in wordpress.com/post

**Comment by Copons** [comment]
@mmtr I personally prefer the modal version with paddings, as it's less cramped and more modern.

All in all, I think most differences depend on the `isReskinned` prop, which I used for this PR.

| Vanill<br>(used in interstitial screens) | Reskinned Modal<br>(used here) |
| - | - |
| Screenshot 2024-02-22 at 16 55 07 | Screenshot 2024-02-22 at 16 55 17 |

Still, I've noticed other things that I think shouldn't happen:

- In the modal, site badges are displayed between title and slug, whereas normally they appear below the slug. The various elements' margins suggest it should be the other way around.
- In the modal search icon is invisible (`fill: none`). Inspecting the DOM, everything is there; just it's missing a color. 🤷 

---

This aside, I'd recommend moving forward with this ASAP, leaving additional design details for a future iteration.

**Comment by xavier-lc** [comment]
> If I'm not mistaken, we're re-using the same component here, cannot we just keep the same style so it looks to something like this?

It's the same component, yeah. The difference is that the one on this PR has the ` isReskinned` prop. I'd leave this decision on a designer, though. Wdyt @lucasmendes-design?

> I think I'm missing an increased margin-bottom, since right not is too close to the domain.

https://github.com/Automattic/wp-calypso/pull/87260/commits/bbf8e8ba03ce4d6b9363565dc71dff288fb7a0f0

> I think we still need to display a bordered input when it is not focused

Again, I'd leave this decision on the hands of a designer.

> Somehow, we're not displaying that on the old site selector visible in wordpress.com/post

I think we are:

image

**Review by mmtr — APPROVED** [review]
Let's leave the design changes for a follow-up, but make sure the E2E tests pass (they are failing right now, but it's maybe unrelated).

**Comment by mmtr** [comment]
They are unrelated, see p1708621004097499-slack-C02DQP0FP

If you rebase, they should pass again

**Comment by mmtr** [comment]
I'll merge this myself, since we should fix production ASAP

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/11412212

Some locales (Hebrew, Japanese) have been temporarily machine-translated due to translator availability. All other translations are usually ready within a few days. Untranslated and machine-translated strings will be sent for translation next Monday and are expected to be completed by the following Friday.

Thank you @Copons for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/11412212).

**Pull request merged**
