### PR TITLE
Settings: Podcasting - Remove Mention of "Hidden" Option

### LINKED ISSUE #44780: Writing > Podcasting: Older mention of "Hidden" privacy option, for private and un-launched sites
There's a minor error with some outdated copy in the Writing settings for Podcasting. On Private sites, it references our deprecated "Hidden" privacy settings in order to use the Podcasting feature.
___

#### How to reproduce

_**(NOTE: This will only be visible if the current website either hasn't been launched yet, or the site is set to Private)**_

Starting at URL: https://wordpress.com/settings/writing/
Alternatively, navigate from [WordPress.com > My Sites > Manage > Settings > Writing], then **scroll down to the Podcasting section of the Writing page**, until you see the following screenshot: https://d.pr/i/ryXwCh

The usual heads up about the site being private will appear as expected, but the second line is outdated: "_In order to enable podcasting, you must set the site visibility to **Public** or **Hidden** first._"

The interface no longer has a "Hidden" option that is distinct from Public or Private; instead, it now appears as a toggle to hide a Public website from search engines. The copy should be updated to reflect this change, to maintain consistency and to avoid potential confusion for users.
___

#### Context / Source

During my team's virtual meetup, we were creating a podcasting site for our DIFM project. This was how we discovered this error in the copy. Context in team master thread: p6knfs-29V-p2

#dogfooding #manual-testing

### PR DESCRIPTION
**Pull request by Aurorum**
#### Changes proposed in this Pull Request

* Removes mention of the now replaced "Hidden" privacy mode under the Settings for podcasting

#### Testing instructions

Visit `/settings/writing/` on a private site and scroll to the "Podcasting" card.

**Before:**
Screenshot 2020-08-10 at 08 15 10

**After:**
Screenshot 2020-08-10 at 08 15 04

cc @adamziel, @michaeldcain 

Fixes #44780

### CODE REVIEW

**Review by adamziel — APPROVED** [review]

**Comment by bluefuton** [comment]
@adamziel @michaeldcain are you still happy for this PR to be shipped?

**Comment by michaeldcain** [comment]
@bluefuton: yes - it still looks good to me.

**Comment by bluefuton** [comment]
@Aurorum this looks ready to roll, but would you mind giving it one a quick rebase please? It looks like we'll need to do that for the build to succeed 👍

**Comment by Aurorum** [comment]
I think this PR should be okay now, thank you!

**Pull request merged**
