### PR TITLE
Editing Toolkit: Add ES5 check

### PR DESCRIPTION
**Pull request by david-szabo97**
#### Changes proposed in this Pull Request

After the `build` script it checks the output files to make sure they are ES5 compatible.
Since IE11 doesn't support ES6 we need to make sure all the output files are ES5 compatible.

#### Testing instructions

Make sure build doesn't fail.

### CODE REVIEW

**Comment by ockham** [comment]
Thanks, this is great! Confirming that ES5 validation is run from the [ETP Build job](https://github.com/Automattic/wp-calypso/pull/45502/checks?check_run_id=1091660834):

```
$ yarn validate-es5
$ npx eslint --parser-options=ecmaVersion:5 --no-eslintrc --no-ignore --no-inline-config ./editing-toolkit-plugin/*/dist/*.js
```

**Comment by ockham** [comment]
Noting that this is inspired by https://github.com/Automattic/wp-calypso/pull/36596.

**Comment by ockham** [comment]
Test instructions to run locally:

```
cd apps/editing-toolkit/
yarn build
```

Verify that no errors are returned by `eslint` (run at the end of the build).

Now, revert https://github.com/Automattic/wp-calypso/pull/45433 (which added a few dependencies to be transpiled), and verify that without that commit, `eslint` complains:

```
git revert b9523f1 # There's a merge conflict with calypso-build's Changelog, but we can ignore that
yarn build
```

This should give 

```
./wp-calypso/apps/editing-toolkit/editing-toolkit-plugin/newspack-blocks/dist/carousel-block-editor.js
  6:11006  error  Parsing error: The keyword 'class' is reserved

./wp-calypso/apps/editing-toolkit/editing-toolkit-plugin/newspack-blocks/dist/carousel-block-view.js
  1:2155  error  Parsing error: The keyword 'class' is reserved
```

**Review by ockham — APPROVED** [review]
Great job, thank you!

Merge once all CI jobs are green.

**Comment by david-szabo97** [comment]
@ockham Thank you so much for adding all that extra information. I agree I kept the PR description way too simple 😴

**Pull request merged**
