### PR TITLE
A4A: Add Team member table.

### PR DESCRIPTION
**Pull request by jkguidaven**
This PR implements the Team member table.

Closes  https://github.com/Automattic/automattic-for-agencies-dev/issues/954

Screenshot 2024-08-21 at 4 25 47 PM

## Proposed Changes

* Implement Team member table using the Data view component. The data are temporarily hardcoded and will be replaced with actual data once the backend endpoint is ready. Also, action buttons do not work at the moment.

## Testing Instructions

* Use the A4A live link and go to the `/team` page.
* Confirm you can see the Team member table. 

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Review by tiagonoronha — CHANGES_REQUESTED** [review]
The "Invite Pending/Expired" pills don’t display correctly when resizing the window to a smaller viewport.

Screenshot 2024-08-21 at 11 22 24

**Comment by jkguidaven** [comment]
> The "Invite Pending/Expired" pills don’t display correctly when resizing the window to a smaller viewport.
> 
> Screenshot 2024-08-21 at 11 22 24

Good catch! 👍  I've added some changes so the table also supports smaller screen. Let me know what you think. 

Screenshot 2024-08-21 at 6 44 03 PM

**Review by tiagonoronha — APPROVED** [review]
👍 LGTM!

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/16571605

Some locales (Hebrew, Japanese) have been temporarily machine-translated due to translator availability. All other translations are usually ready within a few days. Untranslated and machine-translated strings will be sent for translation next Monday and are expected to be completed by the following Friday.

Thank you @jkguidaven for including a screenshot in the description! This is really helpful for our translators.

**Pull request merged**
