### PR TITLE
chore: migrate packages/retarget-open-prs to import/order

### PR DESCRIPTION
**Pull request by flootr**
#### Background

See #54448

#### Changes proposed in this Pull Request

Migrate `packages/retarget-open-prs` to use `import/order`

#### Testing instructions

N/A

### CODE REVIEW

**Review by sarayourfriend — APPROVED** [review]

**Comment by sarayourfriend** [comment]
As an aside I believe we can delete this package. It's no longer necessary given that this feature is built into Github now when you rename the main branch of a repository.

**Comment by flootr** [comment]
> As an aside I believe we can delete this package. It's no longer necessary given that this feature is built into Github now when you rename the main branch of a repository.

Agreed 🙂 let's remove it instead. Is it sufficient to just remove the directory from the repo or are there other steps involved?

**Comment by sarayourfriend** [comment]
Just removing the directory. I opened a PR here: https://github.com/Automattic/wp-calypso/pull/54603

**Comment by flootr** [comment]
closing in favor of #54603

**Pull request closed without merging**
