### PR TITLE
Unify/emails and domains css styling

### PR DESCRIPTION
**Pull request by AllTerrainDeveloper**
#### Changes proposed in this Pull Request

The Thank you component has diverged since it's conception, to adapt to different desires from emails & domains team. Many of the code added to domains has been added in to the common styling so it is less likely to create a new Thank you component for a different use case that will need to add different styling.

There has been also a change where I have unified the total width in the thank you page for domains. The width is now the same for any thank you component in the checkout site.

Also I have moved the emails SVG to a different place to match the same place where domains SVG are located.

#### Testing instructions

**Buy a domain**
1. Go to Upgrades -> Domains
2. Add a domain to your site
3. Buy with credits

Check that thank you page looks like the below screenshot with and it resizes correctly on mobile devices.

Static | Responsive
--- | ---
image | domain purchase responsive

**Transfer a domain**
1. Go to Upgrades -> domains
2. Click on the button Add a domain for this site -> Use a domain I own
3. Type the domain you own and start a transfer domain
4. Buy with credits

Check that thank you page looks like the below screenshot with and it resizes correctly on mobile devices.

Static | Responsive
--- | ---
image | domain transfer responsive

**Buy an email subscription**
1. Go to Upgrades -> emails
2. Add Professional Emails for a domain you own
3. Buy with credits

Static | Responsive
--- | ---
image | email buy responsive

**Map a domain**

0. Have an external domain on a domain provider different than WPCOM.
1. Go to Upgrades -> Domains
2. Click on the button Add a domain for this site -> Use a domain I own
3. Buy with credits

**REMARKS**
If you are not allowed to map domains to the site, you need to sandbox and change the function: `function is_exempt_from_domains_with_plans_only( $current_user = false )` to return always true

Static | Responsive
--- | ---
image | domain map responsive

Related to 1200182182542585-as-1201165030390295

### CODE REVIEW

**Comment by olaseni** [comment]
> Buy an email subscription

> Go to Upgrades -> emails
> Add Professional Emails for a domain you own
> Buy with credits

These steps don't work for an Atomic site for some reason. The new "Thank you page" design isn't shown on Atomic sites after purchasing a Professional Email sub. I travailed a lot with this before I figured out that this was the case.


Screenshot 2021-11-02 at 3 15 33 PM

**Comment by olaseni** [comment]
> Map a domain

These steps also don't work for me.

**Review by olaseni — COMMENTED** [review]
I left a couple of comments. Could you take a look?

**Comment by AllTerrainDeveloper** [comment]
> > Buy an email subscription
> 
> > Go to Upgrades -> emails
> > Add Professional Emails for a domain you own
> > Buy with credits
> 
> These steps don't work for an Atomic site for some reason. The new "Thank you page" design isn't shown on Atomic sites after purchasing a Professional Email sub. I travailed a lot with this before I figured out that this was the case.
> 
> Screenshot 2021-11-02 at 3 15 33 PM

Hello @olaseni! Those repro steps works for me, I've just repeated it with an atomic site I own:
image

I am still trying to replicate your issue

**Comment by AllTerrainDeveloper** [comment]
CC: @olaseni @daledupreez 

We have paired on this, to track the issue and the difference is that I owned the domain and Olaseni bought it for the test. So I am going to create an issue so tackle this problem as seems there is some inconsistencies between showing the thank you page on different situations, which also is not the scope of this Pull Request.

I am also specifying in the test that domain should be owned already.

**Review by olaseni — APPROVED** [review]
The CSS and styling changes look good, so I'm approving this since this is the primary focus of the PR.

After pairing with @AllTerrainDeveloper, we have agreed that the test steps that didn't lead to the display of the Thank You page can be wrangled in another PR

**Pull request merged**
