### PR TITLE
Rename happychat route folder

### PR DESCRIPTION
**Pull request by unDemian**
## Summary
For consistency reasones this PR moves files used for mobile chat component `/me/chat` from `/happychat` to `/chat` directory. This is part of a cleanup for integrating `happychat-client`.

## Testing
Make sure `/me/chat` looks and works properly.

### CODE REVIEW

**Comment by lamosty** [comment]
Why do we need to rename `happychat` to `chat`?

**Comment by unDemian** [comment]
Because the route is `me/chat` and the folder is `me/happychat`

**Comment by kwight** [comment]
Code looks good, and `me/chat` appears as expected (by expected, I mean the layout is there but it's non-functional). Does the `/me/happychat` route need any handling at this point? I just got a blank layout, and no redirect at all. It looks like there's a linting test issue too.

**Comment by unDemian** [comment]
Thanks for taking the time.

> Code looks good, and me/chat appears as expected (by expected, I mean the layout is there but it's non-functional). 

Could you elaborate a bit on this, for me it works and looks as expected ( https://cloudup.com/ckannmBMCN4 ) do you get any errors in the console?

> Does the /me/happychat route need any handling at this point? I just got a blank layout, and no redirect at all.

There isn't any `calypso.localhost/me/happychat` route, this PR only renames the calypso folder from `src/client/me/happychat` to `src/client/me/chat` the match the route, which has always been and will remain `calypso.localhost/me/chat`

>  It looks like there's a linting test issue too.

That is fixed in a child branch where this whole component is refactored.

**Comment by kwight** [comment]
Hm, all looks good now ¯\_(ツ)_/¯

screen shot 2018-04-24 at 9 00 18 am

**Comment by unDemian** [comment]
The linting issue was fixed, this is ready for re-review.

**Comment by alisterscott** [comment]
Are we still planning to merge this one? It needs a rebase

**Comment by unDemian** [comment]
Sorry for the late response, I was afk, the Happychat Client Calypso integration was put on hold as our team has other high priority work scheduled. We will most likely come back to this after the GM. So let's keep the PRs around. Thanks

**Comment by alisterscott** [comment]
Closing due to inactivity. Please reopen if necessary.

**Pull request closed without merging**
