### PR TITLE
Domain: Fix suggestion title spacing on narrow screens

### PR DESCRIPTION
**Pull request by hermawan22**
## What i change : 
I add `padding-right: 2em` on `client/components/domains/domain-suggestion/style.scss`

## Why i change : 
To fix this issue :  #25146

### CODE REVIEW

**Comment by sixhours** [comment]
Thanks for contributing! This is a great start.

I would refactor this to ensure the media query is mobile-first. We avoid using `<` media queries when possible: See [Media Queries](https://github.com/Automattic/wp-calypso/blob/master/docs/coding-guidelines/css.md#media-queries).

In this case, we may not need to specify a breakpoint at all; the padding might be fine on all screen widths, but it needs more testing.

I also noticed the line height on the price/year is still an issue at certain screen widths:

screen shot 2018-05-29 at 9 04 27 am

Thanks again! Let us know if you have further questions. :)

**Comment by hermawan22** [comment]
Hi @sixhours , thank u very much for your explanation regarding Media Query and mobile first, it was helpful for me.

Actually i already test it for various screens (responsive with various size, ipad, ipad pro, tablet, mobile and desktop view) through chrome dev tools and firefox and it goes well with / without any breakpoint.
And, this change not affect to placeholder for domain suggestion.
But if possible u need test it again @sixhours . :)

So, i just need to remove media query for this padding (because it will be useless)?

Thanks again. :)

**Comment by sixhours** [comment]
> So, i just need to remove media query for this padding (because it will be useless)?

Yep! That's working for me.

**Comment by hermawan22** [comment]
pushed new commit.

**Comment by jsnmoon** [comment]
Looks decent, although I'd like to recommend two additional styling tweaks:

1. Add `line-height: 1.25;` to `.domain-registration-suggestion__title`.
2. Add `line-height: 1;` to `.domain-product-price`. 

These two changes would address #25146 in its entirety.

**Comment by hermawan22** [comment]
Hi @sixhours @jsnmoon .
Cool, thanks for suggestions. :pray: 

> Add line-height: 1.25; to .domain-registration-suggestion__title.
> Add line-height: 1; to .domain-product-price.
> These two changes would address #25146 in its entirety.

@jsnmoon Yes, it will also work but feels no space and the line height is not same between title and price.

This is my screenshoots with `line-height`
line


And this is with `padding-right`
padding

We can also add `line-height` if u feel the line height is not good, but for the space i think more appropriate to use `pading-right`. cmiiw.

Thanks guys. :pray:

**Comment by sixhours** [comment]
> With both padding-right and line-height

Yes indeed, we're suggesting this -- keep the increased padding, but also decrease the line-height for the selectors Jason mentioned above.

**Comment by hermawan22** [comment]
Got it, will do it now.

**Comment by sixhours** [comment]
@hermawan22 Looks good to me! Nice work!

**Comment by hermawan22** [comment]
Yay, finally.
Thanks @jsnmoon @sixhours .

**Pull request merged**
