### PR TITLE
Framework: bump babel to avoid using left-pad

### PR DESCRIPTION
**Pull request by gwwar**
Updates the babel-core dependency to `5.8.38` to avoid using `left-pad`. We still need a follow up PR to update the babel-eslint dependency.

cc @aduth @rralian @blowery @dmsnell @jkudish

### CODE REVIEW

**Comment by dmsnell** [comment]
sorry @gwwar - I feel like I just did this

**Comment by gwwar** [comment]
Haha, no we just caught it early. Would have been worse if all of our local caches were cleared.

**Comment by gwwar** [comment]
Re: https://twitter.com/seldo/status/712414400808755200

**Comment by gwwar** [comment]
Closing in favor of reverting #4240

**Pull request closed without merging**
