### PR TITLE
Hosting Command Palette: Display message when user doesn't have sites

### PR DESCRIPTION
**Pull request by danielbachhuber**
Fixes https://github.com/Automattic/dotcom-forge/issues/4669

## Proposed Changes

Displays a message when the user doesn't have any sites:

CleanShot 2023-12-20 at 04 32 23@2x

When you have a site but none of your sites support a given feature, you'll see a more tailored message:

CleanShot 2023-12-20 at 04 32 55@2x

CleanShot 2023-12-20 at 04 33 22@2x

This is an improvement upon the current behavior, which simply shows an empty list:

CleanShot 2023-12-18 at 16 25 34@2x

I looked into including an "Add new site" link/button but: 1) there isn't really an existing UI pattern for this, and 2) it was hard/not intuitive to navigate to with the keyboard. I think we should bring it up with https://github.com/Automattic/dotcom-forge/issues/4630

## Testing Instructions

1. Create a new WordPress.com user and eject out of the signup flow before creating a site.
2. Visit the Sites page.
3. Open the command palette and verify "You don't have any sites yet." is displayed when you select "Manage hosting configuration".
4. With your existing WordPress.com user, verify the site list appears as expected because you have sites.

### CODE REVIEW

**Comment by kozer** [comment]
I tested the code and works as expected!
2023-12-19T09:22:28,263693180+02:00

I also played with code to replicate the following use cases:
- No "hostingEnabled" sites:
2023-12-19T09:28:19,076107460+02:00
- No "hostingEnabledAndPublic" sites:
2023-12-19T09:30:04,006763970+02:00
- No "manageDns" sites:
2023-12-19T09:31:33,083792597+02:00

PS: It seems that e2e tests are failing. However, I approved that, to unblock you from merging, as the code works as expected.

**Review by kozer — APPROVED** [review]

**Comment by javierarce** [comment]
Just two comments: The style of the message should be set to 13px (this was an oversight I've just noticed) and we should center the messages. This will match the style in Core.

Regarding the text, we should aim to make it as concise as possible. I propose using something like this instead:

image

- No sites with DNS management available
- No sites with hosting features enabled

cc: @michaelpick in case you have a better proposal.

**Comment by sejas** [comment]
I like the solution. Let's apply the style and copy changes suggested by Javier.

**Comment by danielbachhuber** [comment]
> Let's apply the style and copy changes suggested by Javier.

Sounds good. I applied more concise messages da47741f947 and matched core font size 74ae0878ad6

CleanShot 2023-12-20 at 04 35 54@2x

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/10401479

Some locales (Hebrew, Japanese) have been temporarily machine-translated due to translator availability. All other translations are usually ready within a few days. Untranslated and machine-translated strings will be sent for translation next Monday and are expected to be completed by the following Friday.

Thank you @danielbachhuber for including a screenshot in the description! This is really helpful for our translators.

**Comment by sejas** [comment]
Thank you @danielbachhuber ! 🎉

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/10401479).

**Pull request merged**
