### PR TITLE
Add "Change site address" menu in the domain list menus

### PR DESCRIPTION
**Pull request by hambai**
#### Changes proposed in this Pull Request

* Adds "Change site address" ellipsis menu
* Fixed a bug to show the ellipsis menus in the site specific domains list

#### Testing instructions

* Open a site specific list of domains and verify that there is a "Change site address" menu in the ellipsis menus for the wordpress.com subdomain
* Open a site specific list of domains and verify that you can see the ellipsis menus for all the items (before this PR only "Edit settings" was visible)

### CODE REVIEW

**Comment by fditrapani** [comment]
Thanks for making these changes! I took a look at my atomic site and it rightfully didn't display the option. Then everything looked good for a regular site. My only suggestion would be to replace the icon from the bulleted list perhaps to what we're using for transferring in the other menus since we're already using a pencil for Edit settings.

**Review by olaseni — APPROVED** [review]
Looks good. You should look into the icon suggestions by @fditrapani though.

**Comment by hambai** [comment]
@fditrapani Soo... the icon we use in the `PopoverMenuItem` are gridicons. I changed the icon to the `reblog` one if that's okay with you as implementing material icons in there would require a lot more work. Though I guess if we want to achieve an actual parity between the domains menu and the ellipsis menu we should probably do that?

I also changed the code to disable the "Change primary button" if there are less than 2 domains. It's a relatively small change so decided I can put it in the same PR - hope you don't mind :D

**Comment by fditrapani** [comment]
Yeah, that's perfect. Thanks @hambai!

**Pull request merged**
