### PR TITLE
Fix/switch suggested default locale route

### LINKED ISSUE #61358: [Bug]: locale switcher does not change page content
### Quick summary

The locale switcher banner -- the one that says `Also available in English` or equivalent -- changes the URL but not the page content. I am guessing a reload is needed, but either it does not perform one or it fails while doing so.

### Steps to reproduce

1. While logged out (e.g. in a fresh incognito window), navigate to `https://wordpress.com/log-in/<locale>`, where `<locale>` is some locale different from your browser settings. e.g. https://wordpress.com/log-in/fr (French)
2. You should get the WordPress.com login page, in the locale chosen, with a switcher banner at the top of the form. If not, maybe try another locale.
3. Click the locale switcher.
4. Notice the page did not change.
5. If you check the URL, the locale slug got switched.

### What you expected to happen

I expected the page contents to update to my chosen language when I clicked the switcher.

### What actually happened

The URL got updated, but no reload happened, and no page change happened.

### Context

Discovered while accepting a user invite while logged out

### Browser

Google Chrome/Chromium, Apple Safari

### Simple/Atomic

Simple

### Other notes

This also applies to other paths where the locale switcher pops up, e.g. `https://wordpress.com/accept-invite/<blog-id>/<invite-key>/<locale>` (while logged out).

No browser console errors observed.

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### Workaround details

Since the URL is already correct, the user can manually load this to get the correctly translated page.

### PR DESCRIPTION
**Pull request by sejas**
#### Context
This PR fixes #61358 and avoids the infinite loading `/log-in/en` discovered only in production after releasing this PR  #63271, which I reverted immediately.

The infinite loading in production was because `page.redirect` doesn't work on the server side.

#### Changes proposed in this Pull Request

- Refactor the login Routes middleware to fix the translation in Login.
- Fix the login redirection when the user clicks on the LocalSuggestion to English. From `/log-in/en` to `/log-in`.
- Check if is server side to avoid using `page.redirect`.

#### Screenshots

**Before**

https://user-images.githubusercontent.com/779993/166646033-b927b1ed-b407-4721-b054-dfb438602e7d.mov

**After**

https://user-images.githubusercontent.com/779993/166646040-dbd2d0be-5ec0-48bb-8d87-729de0cc7ead.mov

#### Testing instructions

1. Your browser should have English as your preferred language.
2. Go to the login screen with any locale different from `en` : [`/log-in/fr`](https://wordpress.com/log-in/fr) 
3. Observe the page is rendered in "french"
4. Click on the Locale Suggestion. It contains this text: `Also available in English`
5. Observe that now the page renders correctly in English, and the URL has removed the `/en` from the URL.
6. The switch to the LocalSuggestion component is in multiple places, but I've found that the issue only happened on the log-in screen.
7. Repeat from step 2 in the jetpack log-in URL : [`/log-in/jetpack/fr`](https://wordpress.com/log-in/jetpack/fr)

- Closes #61358

### CODE REVIEW

**Comment by p-jackson** [comment]
Bad luck on #63271, it's not very often to get caught out by a server rendering issue. But really good that it was caught during staging testing!

I think there are some extra steps needed to test this change properly:
- Enable the `wpcom-user-bootstrap` flag in `development.json` because the controller's redirecting logic depends on this flag. Enabling it to match how it works in production.
- Make sure to stop and restart the Calypso development server, otherwise it won't pick up the code changes

**Comment by p-jackson** [comment]
Actually it's a bit trickier to test `wpcom-user-bootstrap` locally than I realised. If you enable the feature in `development.json` then the Node server can still disable the feature if it doesn't have an API key that will forcefully disable that feature.

https://github.com/Automattic/wp-calypso/blob/cc176e634aa227640bc4f95c1fc93c6036dd09a9/client/server/config/parser.js#L81

Without `wpcom-user-bootstrap` enabled then it's not possible to verify that the `/en` suffix gets removed.

https://user-images.githubusercontent.com/1500769/168963966-d8999bdb-c175-45fe-abec-390a097db11b.mov

@jsnajdr do you know if it's possible to generate a `wpcom_calypso_rest_api_key` key so it can be tested locally? The dev docs at P2gHKz-8-p2 don't describe how the `Authorization: X-WPCALYPSO ...` header works.

**Comment by jsnajdr** [comment]
> do you know if it's possible to generate a `wpcom_calypso_rest_api_key` key so it can be tested locally

The key is a shared secret between the production Calypso server and the REST API server. The REST request is authorized with a login cookie (`wordpress_logged_in`) plus something extra that identifies the client as authorized. And that's the `Authorization: X-WPCALYPSO` header that contains the login cookie signed with a secret key. The REST proxy iframe uses an `Authorization: X-WPCOOKIE` with the same idea.

In development environment, you can just disable the `X-WPCALYPSO` check in your sandbox. It's a method called `Public_API_WPCOM_JSON_API::calypso_server_authentication` and the `calypso_is_valid_key` calls in that method.

Then, for your local Calypso, you can generate some random `wpcom_calypso_rest_api_key` key (it won't be verified) and make Calypso use it.

**Comment by sejas** [comment]
Merging this PR to test it in staging.

**Comment by sejas** [comment]
I've deployed it to production since this PR fixes #63609 and doesn't change the current behavior for authenticated users, which contains a language issue different from this issue. And I consider it a corner case.

**Comment by p-jackson** [comment]
I tested this in production too. The logged out case is fixed which is great, but it still seems to be there for the logged in case.

In this video, I'm logged in as a user whose language is set to English, and the browser's default language is set to English. I explicitly navigate to the German version at `/log-in/de` but when I click the language switcher banner the URL changes but the UI doesn't actually change.

https://user-images.githubusercontent.com/1500769/169729193-e5c5901a-917a-4dd3-b7de-f8a1bc2b457d.mov

**Pull request merged**
