### PR TITLE
Reading Settings: Progress feature flag to stage environment

### LINKED ISSUE #70417: Reading Settings: Progress feature flag to stage environment
Feature flag name: settings/modernize-reading-settings

### LINKED ISSUE #70418: Reading Settings: Progress feature flag to horizon environment
Feature flag name: settings/modernize-reading-settings

### PR DESCRIPTION
**Pull request by mashikag**
#### Proposed Changes

* Progress `settings/modernize-reading-settings` feature flag to stage environment so that it can be accessed for testing without having to build calypso locally

#### Testing Instructions

* Should be tested after the merge whether the `https://wordpress.com/settings/reading/<YOUR-BLOG>` displays the new Reading Settings page

#### Pre-merge Checklist

- [x] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [x] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

Related to pdDOJh-17o-p2#comment-950

Closes #70417
Closes #70418

### CODE REVIEW

**Review by ivan-ottinger — COMMENTED** [review]
While the change will do what we expect, when looking at the [readme doc](https://github.com/Automattic/wp-calypso/blob/trunk/config/README.md), I believe we should also consider enabling the flag in `wpcalypso` and on `horizon`.

> For development of WordPress.com, that looks something like:
> development -> wpcalypso -> horizon -> stage -> production

> As we enable a feature through these progressions, left to right, the feature should most likely be enabled on environments to the left. For example, if a WordPress.com feature is currently enabled in horizon, it should likely also be enabled in development and wpcalypso.

Unless we don't want to have the flag enabled in those environments for some reason. 🤔

**Comment by mashikag** [comment]
Thanks for sharing the doc with me and keeping a close eye on my PR @ivan-ottinger! You are 100% right I should update the 2 other feature flags at the same time. I will correct this first thing tomorrow morning. 🙇

**Comment by mashikag** [comment]
I have set the feature flag true for wpcalypso and horizon environments too. 

@ivan-ottinger  Look what I have got up on the wall in my office. 😃
IMG20221215112819 (1)

**Comment by ivan-ottinger** [comment]
> Look what I have got up on the wall in my office. 😃

haha! 😄 Nice!

**Review by ivan-ottinger — APPROVED** [review]
Looking good now! 👍🏼👍🏼

**Pull request merged**
