### PR TITLE
Checkout Modal: Fix styles

### PR DESCRIPTION
**Pull request by arthur791004**
Related to #

## Proposed Changes

* Fix styles of the checkout modal

| Before | After |
| - | - |
| image | image |

## Testing Instructions

* Go to Assembler on your free site
* Select Colors & Fonts
* Continue to checkout
* Make sure the styles look good

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

**Review by taipeicoder — DISMISSED** [review]
LGTM👍

**Comment by taipeicoder** [comment]
@arthur791004 the Visit Help Center didn't work when I clicked on it 🙁

Screenshot 2024-01-02 at 9 41 45 AM

**Comment by arthur791004** [comment]
> the Visit Help Center didn't work when I clicked on it 🙁

Fixed it via https://github.com/Automattic/wp-calypso/pull/85850/commits/c7b1c14751ce80bebeb93e58e91945aa0dc30d54

**Review by taipeicoder — APPROVED** [review]
LGTM! Also tested the Premium theme checkout and the styles and HC worked well 🙂

**Comment by alshakero** [comment]
Hi Arthur! Does it make sense to only load the Help Center for logged in users?

**Pull request merged**
