### PR TITLE
A4A: Implement Hosting page v3 header.

### PR DESCRIPTION
**Pull request by jkguidaven**
This PR implements the new Hosting Page v3 header.

https://github.com/user-attachments/assets/ca21f75e-2566-41c7-a365-b1ab937247b4

Closes https://github.com/Automattic/automattic-for-agencies-dev/issues/1545

## Proposed Changes

* Implement MigrationOfferV3 banner based on the new design.
* Override certain layout styles to enable scrolling in the main layout container. We also implement an onScroll event listener to connect our expanding and compacting header with the scroll position.
* Introduce the new header featuring key animations when switching to compact mode. In this mode, the title and migration offer are hidden at specific scroll positions.

## Why are these changes being made?

*  This is part of the In-product hosting page v3 project.

## Testing Instructions
 
* Use the A4A live link and go to the `/marketplace/hosting` page.
* Confirm you see the new header and scrolling down works.
* Test that the scrolling works. (Note that there are a few responsiveness issues, but this will be addressed in a separate PR).

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
    - [ ] For UI changes, have we tested the change in various languages (for example, ES, PT, FR, or DE)? The length of text and words vary significantly between languages. 
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Comment by madebynoam** [comment]
Looking good, @jkguidaven! Just adding a few notes:
Can we change the transition on `hosting-v3-hero-section` to `.35s` as `.2s` is a bit too fast to perceive it.

As I scroll down, I see z-index issues (in Arc (Chrome)):
image

Also noticing the tab color is different on small breakpoints:
image

Finally, is there a way to bring the content back in once the user scrolls up (similar to the prototype)?

**Comment by jeffgolenski** [comment]
Thanks, James! Just tested and looks good. Thanks for working with Noam to make that scroll behavior more graceful. Just two items I noticed with the header:

1. Migration banner: If I click anywhere on the title it expands the banner (expected). But if I click the chevron, nothing happens.
2. hosting tabs: Currently there isn't a border radius on the top left or top right.  Can we make the tab corners match the radii of the limited time offer banner? 


CleanShot 2024-12-09 at 14 59 45

**Comment by jkguidaven** [comment]
@madebynoam @jeffgolenski thank you both for catching bugs and areas to improve. 

> Can we change the transition on hosting-v3-hero-section to .35s as .2s is a bit too fast to perceive it.
Done ✅ 

> Also noticing the tab color is different on small breakpoints:
Fixed ✅ 

> Finally, is there a way to bring the content back in once the user scrolls up (similar to the prototype)?
Fixed ✅ 

> Migration banner: If I click anywhere on the title it expands the banner (expected). But if I click the chevron, nothing happens.
hosting tabs: Currently there isn't a border radius on the top left or top right. Can we make the tab corners match the radii of the limited time offer banner?

Both are fixed ✅

**Comment by jkguidaven** [comment]
> As I scroll down, I see z-index issues (in Arc (Chrome)):

I plan to address the overlapping issues in a separate PR where I handle the Plan selector component.

**Comment by cleacos** [comment]
The code looks good. I can see the header and the scroll works well, except some overlapping elements and a scroll-down effect that seems the tab is not scrolling synchronous and smoothly.

**Review by cleacos — APPROVED** [review]
LGTM! The current issues will be fixed in a follow-up PR.

**Comment by jkguidaven** [comment]
> The code looks good. I can see the header and the scroll works well, except some overlapping elements and a scroll-down effect that seems the tab is not scrolling synchronous and smoothly.

Thanks for the review 🙇 

Do you have some screencaps with the scrolling issue? I'd like to confirm if this is a performance issue related.

**Comment by jkguidaven** [comment]
> > The code looks good. I can see the header and the scroll works well, except some overlapping elements and a scroll-down effect that seems the tab is not scrolling synchronous and smoothly.
> 
> Thanks for the review 🙇
> 
> Do you have some screencaps with the scrolling issue? I'd like to confirm if this is a performance issue related.

@cleacos  Ohh nvm saw what you mean.. @madebynoam I think the .35s animation kinda makes this more obvious. Should we revert to .2s?

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/17057530).

**Pull request merged**
