### PR TITLE
Jetpack Onboarding: Always show stats step, display different copy if already activated

### PR DESCRIPTION
**Pull request by tyxla**
As @rickybanister suggested in p1HpG7-4WU-p2 #comment-25088 after @rachelmcr and @bsessions85 reported some confusion when hiding the stats step, this PR proposes that we:

* Always show the stats step
* Display a different copy if the Stats module has already been activated.

Also cc @benhuberman for copy review of the new string we're introducing - **Jetpack also provides you with helpful stats about your site visitors.**.

Preview:

**When stats module already activated:**

**When stats module was just activated**

To test:
* Checkout this branch
* Make sure your site is **not** connected to WP.com and has the latest Jetpack.
* Start the flow here: http://yourgroovydomain.com/wp-admin/admin.php?page=jetpack&action=onboard&calypso_env=development where `yourgroovydomain.com` is your Jetpack site.
* Skip to the Stats step. 
* Click the button to activate Stats.
* Go through the connection flow. 
* After connecting verify you can see the "Success!..." message.
* Disable the stats module by running the following WP CLI command: `wp jetpack module deactivate stats`
* Restart the flow, skip to the Stats page again.
* Click the button to activate Stats.
* Verify you can immediately see the "Success!..." message.
* Start a new JN site and initiate the JPO flow for it.
* Skip to the contact form step and connect there to insert a form.
* Skip to the stats page and verify you can see the "Jetpack also provides you with helpful stats about your site visitors." message as the module was previously activated upon connecting.
* Go to other steps, refresh the flow, etc. and verify that in all cases where your site is connected and stats module is activated, you can see the "Jetpack also provides you with helpful stats about your site visitors." message.

### CODE REVIEW

**Comment by rickybanister** [comment]
Wunderbar!

**Comment by benhuberman** [comment]
@tyxla  -- two small things:
- I'm not sure why we need "also" here -- it feels like this is referring to some previous conversation somewhere else, but I don't know that it makes intuitive sense.
- "about your site visitors" sounds slightly off to me, since the stats don't really give much info about the visitors themselves (beyond country). 
So I'd suggest a small tweak:
> Jetpack provides you with detailed stats about your site's performance.
Or, if "performance" is potentially confusing (conflated with uptime, speed, etc.), we could go with:
> Jetpack provides you with detailed stats about your site's reach.

**Comment by tyxla** [comment]
Going to go with:

> Jetpack provides you with detailed stats about your site's reach.

Thanks everybody!

**Comment by tyxla** [comment]
Copy updated in 69082b323a583a7d2d6764e79f47c13c8f14653b.

Merging now 🚢

**Pull request merged**
