### PR TITLE
Videos UI: Add a header component for onboarding.

### PR DESCRIPTION
**Pull request by kwight**
This PR adds a header component for the videos UI, as originally designed for the onboarding hero flow. Since the modal footer component we have in place for My Home is identical in need for onboarding, we'll just use that (possibly confusing when looking at file names, but let's see how it goes).

| Mobile | Desktop |
| --- | --- |
| Screen Shot 2021-11-25 at 10 50 49 AM | Screen Shot 2021-11-25 at 10 49 42 AM |

| Mobile (Course Complete) | Desktop (Course Complete) |
| --- | --- |
| Screen Shot 2021-12-01 at 2 49 17 PM | Screen Shot 2021-12-01 at 2 48 45 PM |

**Testing Instructions**
* First verify that the current "modal" components still look and behave correctly on My Home.
* Load the new onboarding components by altering those pulled in by `<BloggingQuickStartModal />` (see below).
* Verify the elements and behaviour match with the original [Figma](EuqfSnWpfYx8fgiBlVmbuA-fi-2119%3A1111).
* Also check the "course complete" view with the button; this can be triggered by setting the `isCourseComplete` prop to `true` in `modal-footer-bar.jsx`.

Screen Shot 2021-12-01 at 2 45 56 PM

### CODE REVIEW

**Comment by kwight** [comment]
This should be good to go now – with this merged, I believe we'd have all we need for it to be slid into the onboarding flow. cc/ @arthur791004

**Comment by arthur791004** [comment]
Cool 👍

**Comment by andres-blanco** [comment]
The "draft first post" link: image  wasn't showing on mobile.

I've added a prop to the `modal-footer` since I felt this was to small of a change to make an entirely new component. In order to test it you need to add the `showDraftFirstPostLink={ true }` prop in `client/my-sites/customer-home/cards/education/blogging-quick-start/blogging-quick-start-modal.jsx`:

image

**Comment by kwight** [comment]
> The "draft first post" link wasn't showing on mobile.

Oh dang! I _knew_ there was a reason for that footer component. 🙃 

> I've added a prop to the modal-footer since I felt this was to small of a change to make an entirely new component.

Hm, I'd disagree. I'd say it's better to add the onboarding footer component (now allowing the file naming to make sense again), rather than introducing an unrelated prop to a component for a different context. I'll fix it up.

**Review by andres-blanco — APPROVED** [review]
This is working great.
 * The modal behaviour is the same.
 * The onboarding behaviour fits the Figma.

**Pull request merged**
