### PR TITLE
Prettier: wp-prettier-2.0.4

### PR DESCRIPTION
**Pull request by sirreal**
Upgrade to wp-prettier@2.0.4 and run `yarn reformat-files`.

Read the notes about prettier 2: https://prettier.io/blog/2020/03/21/2.0.0.html

https://github.com/Automattic/wp-prettier/releases/tag/wp-2.0.4
https://github.com/Automattic/wp-prettier/tree/wp-prettier-2.0.4

### CODE REVIEW

**Comment by sirreal** [comment]
@scinos Can you take a look at this? It looks like there are a lot of errors from the prettier linter… will that need an update to handle prettier@2 style + config (defaults)?

Thinking of #40118

**Comment by sirreal** [comment]
🤦 My last rebase added a simple `wp-prettier@2.0.4` dev dependency. I'll work through this again…

**Comment by sirreal** [comment]
It sounds like we'll move ahead with this. @scinos can I hand over to you?

I think we should cherry-pick https://github.com/Automattic/wp-calypso/pull/41136/commits/10ee047860ce415332c0b9e2f20971dfe7d0b2d5 here as well and make the reformatting changes in one go.

`arrowParens: always` better aligns with both vanilla prettier and with Gutenberg (still on 1.19). Maybe we should adopt [Gutenberg's prettier config](https://www.npmjs.com/package/@wordpress/prettier-config).

https://github.com/WordPress/gutenberg/blob/8afed75c6f2daa2624b0f91781aa4bee163d4e93/packages/prettier-config/lib/index.js#L25

**Comment by scinos** [comment]
I re-did all commits in this branch to keep all the automatic formatting changes in one single commit. Once we are ok with this PR, I'll add that commit to a `.git-blame-ignore-revs` file (https://www.moxio.com/blog/43/ignoring-bulk-change-commits-with-git-blame)

**Comment by sirreal** [comment]
> Once we are ok with this PR, I'll add that commit to a .git-blame-ignore-revs file (https://www.moxio.com/blog/43/ignoring-bulk-change-commits-with-git-blame)

Then is the plan to temporarily enable and land this as _Rebase and merge_? If that's the case, let's get the first 2 commits into a squashed form like we'd normally have and leave the reformat as an isolated commit.

Can we leave the `.git-blame-ignore-revs` for a follow-up PR? From what I understand, `git` now includes the option to configure a specific file and there are conventions around how to name that file, but no official support for a default name from GitHub or others. It's probably worth having some conversation in a dedicated PR.

**Comment by scinos** [comment]
Branch is ready to be reviewed.

There are two independent commits: bfc2fa727e6f51f1eb1042dfff2ed54d0d57e9a0 with the changes required to upgrade to 2.0.4, and 9e605ad50224b7fe5b462d1b926fc1965706836d with the automatic reformat. The idea is to merge this branch with the 'Rebase and merge' strategy, and in the future add 9e605ad to `.git-blame-ignore-revs` I.e., what @sirreal said.

There will be errors on `ci/circleci: lint-and-translate`. This is because this branch triggers linting for lots of files, and those files contains lots of pre-existing linting errors.

**Comment by sirreal** [comment]
I create the PR so can't approve it, but ✅ from me.

- A scan of the lint errors on the CI job appear to be pre-existing.
- Full e2e test is passing.

🚢

**Review by lynnbgriffith — APPROVED** [review]
🚢 Same here.  LGTM.

**Pull request merged**
