### PR TITLE
Untangling: show unified sidebar for early classic view

### PR DESCRIPTION
**Pull request by fushar**
Part of:

- https://github.com/Automattic/dotcom-forge/issues/6261

## Proposed Changes

This PR shows nav unification for sites early classic Atomic sites. See https://github.com/Automattic/jetpack/pull/36601 where we return the untangled menus.

## Testing Instructions

See pfsHM7-Dn-p2.

## Pre-merge Checklist

- [x] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [x] https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md for your changes?
- [x] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [x] Have you checked for TypeScript, React or other console errors?
- [x] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [x] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [x] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Comment by arthur791004** [comment]
Tested on both simple & atomic sites, and it looks great except for some issues
* The styles on the mobile device and I think we have to fix it
  image
* It's weird that some links under the Jetpack menu point to the plans/settings page
  * Activity Log
  * VaultPress
  * Subscribers

**Comment by arthur791004** [comment]
The masterbar is broken after resizing but it may be an edge case

https://github.com/Automattic/wp-calypso/assets/13596067/d7d40e52-f0a6-4c95-9119-93db0d4f7c7d

**Comment by fushar** [comment]
Thanks @arthur791004 for the review!

> The styles on the mobile device and I think we have to fix it

Fixed!

> It's weird that some links under the Jetpack menu point to the plans/settings page

Fixed!

---

I won't be able to continue on this PR for the week, so anyone is welcome to take this over, or I can take a look again on Monday.

**Review by Addison-Stavlo — COMMENTED** [review]
Tested a little bit and I ran into some weirdness between the mobile masterbar we were showing in global site view, and bringing the old masterbar back as we have done here. Probably related to Arthur's [comment above](https://github.com/Automattic/wp-calypso/pull/88943#issuecomment-2022413911) although I cant get that video to play for some reason.

Its a bit intermittent and often tied to changing the viewport size. As soon as I pulled up the gif capture it stopped happening the way I had been reproducing it. 🤣 But I was able to find an capture a quick slice here:

masterbar-weirdness

at mobile viewports the global site view masterbar shows up (sometimes? it seems sometimes when i load it its the regular masterbar too). When expanding out, it sometimes takes the hight of the old masterbar but items/colors of the GSV one looking a bit broken.

Is the idea now to use the old calypso masterbar in all circumstances at this site level for both mobile and desktop? I imagine the mobile-only masterbar doesn't make sense anymore once we get past the true global levels (/sites, /read, /me), since we have brought back the calypso masterbar to this level on desktop.

**Comment by arthur791004** [comment]
Added the `DO NOT MERGE` label since this change requires https://github.com/Automattic/jetpack/pull/36601 which is still not available on atomic sites.

**Comment by fushar** [comment]
> The masterbar is broken after resizing but it may be an edge case

> Tested a little bit and I ran into some weirdness between the mobile masterbar we were showing in global site view, and bringing the old masterbar back as we have done here.

Thanks @arthur791004 @Addison-Stavlo, I've fixed the issue via https://github.com/Automattic/wp-calypso/pull/88943/commits/d4987e00176a653fe786dbc2517ac16f5c9c8151:

On mobile view,

- When we're in "Hosting" -> {Plans, Domains, Emails, Purchases, Settings}, we will keep showing the original masterbar (not global nav). This is because the user is supposed to be in a "wp-admin" context (just with a nav-unified sidebar).
- When we're in any other Calypso pages (the Global View -> "Dev Tools" pages), we will show the global nav masterbar.

In the future we should probably rename the `getShouldShowGlobalSiteSidebar()` selector though. For now, ignoring the name, it means: whether we're in the global nav with a site selected.

This PR is ready for another round of review!

**Comment by fushar** [comment]
_Ignore my previous comment if you've seen it; I deleted it, this is a newer version_

---

> The masterbar is broken after resizing but it may be an edge case

> Tested a little bit and I ran into some weirdness between the mobile masterbar we were showing in global site view, and bringing the old masterbar back as we have done here.

Thanks @arthur791004 @Addison-Stavlo, I've fixed the issue via https://github.com/Automattic/wp-calypso/pull/88943/commits/ab8e4ae43efcd0028a8375bda0280b2106f5105c.

On mobile view, when we're in one of the "Hosting" menus, we will keep showing the original masterbar (not global nav). This is because the user is supposed to be in a "wp-admin" context (just with a nav-unified sidebar).

Note that later we will show some of the "Hosting" menus to the new "Global Site View". In the above commit, currently all of the Hosting menus will go to the nav unification; we will need to modify the logic when the new GSV is ready. cc: @eoigal 

This PR is ready for another round of review!

**Comment by fushar** [comment]
Also, with the new design, the `getShouldShowGlobalSiteSidebar()` selector only has meaning for mobile masterbar. It's used to determine whether to show the current site name in the masterbar.

In the future, we might want to rename it, but I think it's out of the scope of this PR.

**Review by taipeicoder — DISMISSED** [review]
Works great! The animation of the top bar doesn't feel great, but that's an existing issue on production.

https://github.com/Automattic/wp-calypso/assets/797888/248ae450-66e9-4f86-a4c9-6114b3bf66f6

**Review by taipeicoder — APPROVED** [review]
I found an issue where if user goes from desktop to mobile resolution, the reader sidebar   runs into a height issue. IMO this is an edge case since I don't imagine a lot of users doing this. We can fix this later on.

https://github.com/Automattic/wp-calypso/assets/797888/354f99af-4261-468d-8fb6-ec2bcf47fb27

Approving this PR 🙂

**Comment by taipeicoder** [comment]
While testing this PR, I found the navigation experience from wp-admin to Reader very confusing. Once I land in the Reader, there was no easy way for me to switch back to where I was. I had to go to `/sites` and select the site again.

The top bar icons are also confusing. We use different icons for sidebar toggle, and the WP logo behave differently between wp-admin and Reader.

| wp-admin | Reader |
| --- | --- |
| Screenshot 2024-04-01 at 4 35 21 PM|Screenshot 2024-04-01 at 4 35 27 PM |

Not directly related to this PR, but worth exploring this while nav redesign is underway. cc: @nuriapenya @lucasmendes-design @davemart-in

**Comment by fushar** [comment]
> The top bar icons are also confusing. We use different icons for sidebar toggle, and the WP logo behave differently between wp-admin and Reader.

Don't forget that we have a third topbar; the wp-admin top bar without nav unification 😄 So, the situation is like this:

| wp-admin<br>(core) | wp-admin<br>(nav unification) | Reader |
| --- | --- | --- |
|image| Screenshot 2024-04-01 at 4 35 21 PM|Screenshot 2024-04-01 at 4 35 27 PM |


The most related existing issue is this: https://github.com/Automattic/dotcom-forge/issues/6324. But it is more about wp-admin (core vs nav unification). We need to think about these 3 cases, whether or not it is possible to unify all of them 🤔

**Comment by fushar** [comment]
Jetpack 13.3 (beta) has been released on Atomic (p9o2xV-43r-p2), merging this PR 🚢 thanks for the reviews.

**Pull request merged**
