### PR TITLE
Reader: update Follow button icon size and clean up

### PR DESCRIPTION
**Pull request by jancavan**
This PR updates the Follow/Following buttons in Reader as discussed in: https://github.com/Automattic/wp-calypso/pull/5502#issuecomment-221063242

1. Update icon sizes from `24 x 24` to `18 x 18` to make sure they conform with Calypso design standards
2. Clean up custom positioning values and repeat declaration of Follow/Following button and icon properties in various stylesheets

Updated in:

**Main stream card header:**

Before:
screenshot 2016-07-01 12 40 29

After:
screenshot 2016-07-01 12 40 35

**Site stream:**

Before:
screenshot 2016-07-01 12 48 01

After:
screenshot 2016-07-01 12 47 55

**Full-post view:**

Before:
screenshot 2016-07-01 12 29 00

After:
screenshot 2016-07-01 12 29 04

**List items:**

Before:
screenshot 2016-07-01 12 30 59

screenshot 2016-07-01 12 42 12

After:
screenshot 2016-07-01 12 30 39

screenshot 2016-07-01 12 42 16

**Cold Start:**

Before:
screenshot 2016-07-01 12 36 19

After:
screenshot 2016-07-01 12 36 30

/cc @folletto @rickybanister @jasmussen 

Test live: https://calypso.live/?branch=update/reader/follow-button-icon-sizes

### CODE REVIEW

**Comment by jancavan** [comment]
Reported by @fraying.

Just found out that the current styles actually make the Follow buttons on Devdocs look funky:

screenshot 2016-07-01 14 49 00

But this PR fixes this as well:

screenshot 2016-07-01 14 49 27

**Comment by rickybanister** [comment]
That looks a lot more proportional.

**Comment by folletto** [comment]
Yay! This is good. Nice one, and nice cleanup on the code side! 👍

**Comment by jancavan** [comment]
In Manage Following, I had to add back a few styles so when a URL isn't invalid, the Follow button doesn't get activated. But icons are still also `18 x 18`:

Before:
screenshot 2016-07-05 13 37 13

screenshot 2016-07-05 13 37 22

After:
screenshot 2016-07-05 13 37 29

screenshot 2016-07-05 13 37 40

Note: There seems to be an issue where if the URL is invalid, the supposed invalid button is still clickable. Possibly related to this and is for a separate PR: https://github.com/Automattic/wp-calypso/issues/6537

Can I get another 👀  and maybe 👍  please? @folletto @rickybanister

**Comment by rickybanister** [comment]
Manage Following looks good as well.

**Comment by alisterscott** [comment]
@jancavan our visual tests picked up a difference in mobile mode that the following buttons look like this:

screen shot 2016-07-06 at 9 21 25 am

Is this expected/correct?

**Comment by jancavan** [comment]
@alisterscott Yes, the word Follow/Following are dropped in viewports `<660px`.

**Pull request merged**
