### PR TITLE
Bugomattic: unify the bug reporting template.

### PR DESCRIPTION
**Pull request by worldomonation**
#### Proposed Changes

To support Bugomattic Ragnarok, `wp-calypso`'s bug report templates should be re-unified into one.

Context: pciE2j-1Hh-p2

#### Testing Instructions

Preview the template by navigating to `.github/ISSUE_TEMPLATE/bug_report.yml` in this feature branch.

#### Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

Related to #

### CODE REVIEW

**Review by dpasque — APPROVED** [review]
LGTM! And thank you! 🙇  I assumed you're going to delete the old Happiness template as soon as we move the Bugomattic links over, etc? (In a separate PR?)

**Comment by worldomonation** [comment]
> LGTM! And thank you! 🙇  I assumed you're going to delete the old Happiness template as soon as we move the Bugomattic links over, etc? (In a separate PR?)

Correct, and the repo gardening and other jobs that use or reference these templates must also be updated prior to that time.

**Review by jeherve — APPROVED** [review]
This looks good to me. 🌟 

> the repo gardening and other jobs that use or reference these templates must also be updated prior to that time.

Taking care of that in https://github.com/Automattic/jetpack/pull/28448

**Comment by worldomonation** [comment]
D99359-code has been deployed.

**Pull request merged**
