### PR TITLE
State: Remove more unused editor selectors

### PR DESCRIPTION
**Pull request by tyxla**
In #47095 and #46331 we've been removing lots of unused editor code, but we forgot to remove some unused selectors. This PR removes a couple of them:

#### Changes proposed in this Pull Request

Remove the following unused selectors:
* `areSitePermalinksEditable` - last use was removed in https://github.com/Automattic/wp-calypso/pull/47095
* `getSiteDefaultPostFormat` - last use was removed in https://github.com/Automattic/wp-calypso/pull/46331

#### Testing instructions

* Verify the removed selectors aren't used at all.
* There should be no bundle size changes at all.

### CODE REVIEW

**Comment by jsnajdr** [comment]
This was the only usage of the `permalink_structure` site option, which is explicitly requested when calling `/me/sites`:

permalink_structure

It can be removed from [the `SITE_REQUEST_OPTIONS`](https://github.com/Automattic/wp-calypso/blob/trunk/client/state/sites/constants.js#L54) array. It will make the sites REST requests a few nanoseconds faster 🙂 

Gutenberg doesn't use this site option and looks at the post's `permalink_template` field instead. That field is a fairly recent (WP 5.1) addition and wasn't there when the Calypso Classic Editor was written.

**Review by jsnajdr — APPROVED** [review]
Other than the `SITE_REQUEST_OPTIONS` flag, this is of course totally ready to :ship: 🙂

**Comment by tyxla** [comment]
> It can be removed from [the `SITE_REQUEST_OPTIONS`](https://github.com/Automattic/wp-calypso/blob/trunk/client/state/sites/constants.js#L54) array. It will make the sites REST requests a few nanoseconds faster 🙂

Good catch @jsnajdr! I'll follow-up on this in another PR.

**Comment by tyxla** [comment]
> > It can be removed from [the `SITE_REQUEST_OPTIONS`](https://github.com/Automattic/wp-calypso/blob/trunk/client/state/sites/constants.js#L54) array. It will make the sites REST requests a few nanoseconds faster 🙂
> 
> Good catch @jsnajdr! I'll follow-up on this in another PR.

Removed in #47670 - feel free to take a look when you get a chance.

**Pull request merged**
