### PR TITLE
Duplicate views: Redirect from Calypso to WP Admin (Posts, Testimonials, Portfolio)

### PR DESCRIPTION
**Pull request by mmtr**
Part of https://github.com/Automattic/wp-calypso/issues/95621
Part of https://github.com/Automattic/wp-calypso/issues/96183

## Proposed Changes

Introduces a new util to users participating in the "Remove duplicate views" experiment are redirected from Calypso to WP Admin if they try to access directly a Calypso screen of a removed view.

For now, this new logic only works with Posts, Testimonials, and Portfolio Projects.

https://github.com/user-attachments/assets/01215fa7-934d-49e2-b53b-285e5d4ea995

## Why are these changes being made?

Because we want to remove the custom Calypso implementations in favor of the standard WordPress WP Admin experience.

## Testing Instructions

- Go to the placeholder experiment page: 22124-explat-experiment
- Assign yourself to the `control` variation using the bookmarklets
- Use the Calypso live link below
- Go to `/posts/:site` for a site with the default admin interface
- Make sure you remain in Calypso
- Go to `/types/jetpack-testimonial/:site` for a site with the default admin interface
  - This requires Testimonials to be enabled, you can do that in Settings > Writing.
- Make sure you remain in Calypso
- Go to `/types/jetpack-testimonial/:site` for a site with the default admin interface
  - This requires Portfolio to be enabled, head to Settings > Writing and toggle their options.
- Make sure you remain in Calypso
- Go to the placeholder experiment page: 22124-explat-experiment
- Assign yourself to the `treatment` variation now
- Go to `/posts/:site` for a site with the default admin interface
- Make sure you are redirected to WP Admin
- Go to `/types/jetpack-testimonial/:site` for a site with the default admin interface
  - This requires Testimonials to be enabled, you can do that in Settings > Writing.
- Make sure you are redirected to WP Admin
- Go to `/types/jetpack-testimonial/:site` for a site with the default admin interface
  - This requires Portfolio to be enabled, head to Settings > Writing and toggle their options.
- Make sure you are redirected to WP Admin

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
    - [ ] For UI changes, have we tested the change in various languages (for example, ES, PT, FR, or DE)? The length of text and words vary significantly between languages. 
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Review by BogdanUngureanu — APPROVED** [review]
LGTM! Are you planning to support categories/taxonomies in a separate PR? The back-end implementation already supports it. :)

**Comment by mmtr** [comment]
> The back-end implementation already supports it.

Does it? They use the `edit-tags.php` path, but so far only the `edit.php` has been added to the list of enforced screens.

**Comment by BogdanUngureanu** [comment]
> > The back-end implementation already supports it.
> 
> Does it? They use the `edit-tags.php` path, but so far only the `edit.php` has been added to the list of enforced screens.

I think the switcher implementation propagates it to the other sections. If you start a new site, you'll notice that besides the edit.php, you'll also get the tags and categories in WP-Admin.

**Comment by mmtr** [comment]
> I think the switcher implementation propagates it to the other sections. If you start a new site, you'll notice that besides the edit.php, you'll also get the tags and categories in WP-Admin.

That's not what I see. Only "Posts > All Posts" redirect to WP Admin. "Posts > Categories" and "Posts > Tags" still link to Calypso.

**Pull request merged**
