### PR TITLE
Use akismet plan constants to show benefits at checkout

### PR DESCRIPTION
**Pull request by jboland88**
This diff employs the recently added Akismet plan constants to show plan benefits at checkout and properly classify the plans as akismet plans.

Related to #

## Proposed Changes

* Adds additional `isAkismet...` functions to check for different plan types and show updated plan benefits at checkout for newly added plans.

## Testing Instructions

* Check out this branch locally or use the Calypso live link
* You will need to use the test store for this test plan
* Check all the new products in the checkout `/checkout/akismet/PRODUCT_SLUG`
* Make sure that the product benefits show in right-hand side of the checkout and that each plan shows the correct API limit as one of the product benefits
* Confirm that you can switch between one month, one year and two year subscription periods for each product

Screenshot 2023-10-30 at 4 15 39 PM

Product slugs to test:
- ak_pro5h_monthly
- ak_pro5h_yearly
- ak_pro5h_bi_yearly
- ak_bus5k_monthly
- ak_bus5k_yearly
- ak_bus5k_bi_yearly
- ak_ep15k_monthly
- ak_ep15k_yearly
- ak_ep15k_bi_yearly
- ak_ep25k_monthly
- ak_ep25k_yearly
- ak_ep25k_bi_yearly

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?his

### CODE REVIEW

**Comment by spraveenitpro** [comment]
**Functional Testing:**

<details>
<summary>Without patch: </summary>


</details>

<details>
<summary>With Patch: 🎈 </summary>

When I attempt to hit the list of product_slugs to test, I get this screen:


</details>

**Comment by spsiddarthan** [comment]
>When I attempt to hit the list of product_slugs to test, I get this screen:


@spraveenitpro, This is perhaps because you weren't using the test store. When I used it, the plans loaded fine for me. 

I am trying to debug the failing test on the patch, it looks good otherwise.

**Review by spsiddarthan — APPROVED** [review]
Just made a minor change to the test, so I am approving this.

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/9565239

Thank you @jboland88 for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/9565239).

**Pull request merged**
