### PR TITLE
reader: use '-primary' color for link base, hover and focus states

### LINKED ISSUE #29518: [Classic Bright] - Update link color to `color-primary`
Update color for all links to `color-primary`

screen shot 2018-12-17 at 6 19 12 pm

### PR DESCRIPTION
**Pull request by flootr**
#### Changes proposed in this Pull Request

* use `-primary` color for link base, hover and focus states

#### Testing instructions

* Smoke test _Reader_, you shouldn't find any occurrences of pink for links
  * includes base color, focus and hover states
  * includes buttons, icons, etc which may appear above, below, beneath post cards

fixes #29518

### CODE REVIEW

**Comment by jsnajdr** [comment]
In the Legacy Blue style, links were easy to distinguish from other text:

screenshot 2018-12-18 at 14 34 20

Now after this patch, I can't tell link from non-link without staring at the screen really carefully:

screenshot 2018-12-18 at 14 35 09

Is that what we wanted? (If yes, I can confirm I didn't spot any pink when testing.)

**Comment by jsnajdr** [comment]
Elements with the `.button.is-link` class are still pink. For example, the "Have a coupon code?" link in `/checkout`:

screenshot 2018-12-18 at 14 38 29

**Comment by blowery** [comment]
Pinging @drw158 for thoughts on link text colors

**Comment by blowery** [comment]
Looking through the PR, I wonder if we can just drop most of the color rules and let our defaults work...

cc @bluefuton

**Comment by flootr** [comment]
> Now after this patch, I can't tell link from non-link without staring at the screen really carefully:

I agree it's a bit hard to see. Calling @drw158 for design feedback.

> Elements with the .button.is-link class are still pink. For example, the "Have a coupon code?" link in /checkout

This PR is scoped to reader. I didn't update colors from other sections of Calypso.

**Comment by drw158** [comment]
We can't do too much about the color of the blue. The blue is the new brand color for WordPress.com. It is darker though, and passes contrast tests, unlike the old blue. Let's update the blue, but make note of where it might make the UI less usable and file issues.

**Comment by cburton4** [comment]
I think ideally these links would have underlines moving forward but that is not within the scope of this work. I'll add this to a list of items uncovered that will need iteration for next rounds.

**Pull request merged**
