### PR TITLE
Individual subscriber stats: Show notice when blog is registered before we started collecting data

### PR DESCRIPTION
**Pull request by TimBroddin**
Discussion:p1692262264754989-slack-C02TCEHP3HA

## Proposed Changes

This PR adds a notice when the blog is registered before 2023-08-17.

CleanShot 2023-08-17 at 17 13 00@2x

## Testing Instructions

1. Apply this PR
2. Open Calypso for a site registered before 2023-08-17 
3. Visit Users > Subscribers and click a subscriber
4. You should see the the notice

Repeat with either a newly registered site, or change the date in `client/my-sites/subscribers/components/subscriber-stats/subscriber-stats.tsx`, and verify the notice is gone.

Compare with the design: h8tMpJlCqNFemEerU9owHI-fi 

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

**Review by phcp — APPROVED** [review]
Good job @TimBroddin! Code looks good and it's working as expected.

**Comment by TimBroddin** [comment]
I made a minor type fix that was causing the build to fail. No rereview is necessary.

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/8724488

Thank you @TimBroddin for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/8724488).

**Pull request merged**
