### PR TITLE
WPCOM Block Editor: Remove the switch-to-classic feature

### PR DESCRIPTION
**Pull request by pablinos**
#### Changes proposed in this Pull Request

Now the Calypso editor has been deprecated the 'Switch to Classic Editor' link in the settings menu is defunct. This is still showing for users registered before December 2018 that weren't included in the deprecation email and have their editor set to Gutenberg. 

#### Testing instructions

With a user and site that meets the above criteria, or with D49284-code applied, confirm that you can see the 'Switch to Classic Editor' option in the More Options menu of Gutenberg (the three dots at the top right).

image

Apply the diff associated with this patch and sandbox widgets.wp.com and on reload, the option should be removed.

### CODE REVIEW

**Comment by pablinos** [comment]
Built files for testing D49376-code

**Review by retrofox — APPROVED** [review]
Tested and it works as expected. 👍

**Review by wp-desktop — DISMISSED** [review]
WordPress Desktop CI Failure for job "wp-desktop-mac".

@pablinos please inspect this job's build steps for breaking changes at [this link](https://circleci.com/gh/Automattic/wp-calypso/914308). For temporal failures, you may try to "Rerun Workflow from Failed".

Please also ensure this branch is rebased off latest Calypso.

**Review by creativecoder — APPROVED** [review]
Tested with a user registered before 2018, not in the editor deprecation group, site using the block editor.

The Switch to Classic Editor link is no longer shown with the patch applied.

**Pull request merged**
