### PR TITLE
Automattic for Agencies: Implement fetch agencies & set current agency.

### PR DESCRIPTION
**Pull request by yashwin**
Resolves https://github.com/Automattic/jetpack-genesis/issues/281

## Proposed Changes

This PR implements 

- Fetch agencies when A4A is loaded every time.
- Set the current agency when agencies are fetched, which will allow us to support multiple agencies in the future.

## Testing Instructions

- Switch to the branch `git checkout add/a4a/implement-fetch-agencies`.
- Open the Calyso live link for A4A.
- Follow the steps here to create the agency ID: D139529-code.
- Verify that an API call is being made to fetch all the agencies: `/agency,`, and it returns all the agencies. 
- Click the Marketplace menu item > Select Jetpack Complete and issue it > Verify that the selected licenses are issued > Assign the issued licenses to a site by selecting one from the Assign License page > Verify that the licenses are assigned to the selected site.

## Pre-merge Checklist

- [x] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [x] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Comment by cleacos** [comment]
👀

**Comment by cleacos** [comment]
I got this error:

image

image

I think it's expected in this context... But I would like to highlight that I have a payment method in Jetpack Manage.

It retries the call to the `/license` endpoint 6 times.

**Review by jkguidaven — APPROVED** [review]
I tested it and can confirm that the API is getting called when accessing A4A. Unfortunately, my account has some issues which need to be fixed, so I can't fully test it.

The code also looks good to me. Good job! :+1: 

One comment I have is that we may need to create some route middleware to check if the current user has an agency account. If they don't, then we should redirect them to the appropriate signup page. However, we can address this later on in a separate PR or on the Signup project.

**Comment by yashwin** [comment]
Thanks for the review, @cleacos & @jkguidaven!

> I got this error:
> I think it's expected in this context... But I would like to highlight that I have a payment method in Jetpack Manage.
> It retries the call to the `/license` endpoint 6 times.

Could you please tell me the steps to reproduce this error? I was unable to reproduce this.

Also, since the changes on this PR aren't related to this error & we might need some changes in the backend, I will merge this PR as it is approved by @jkguidaven.

**Pull request merged**
