### PR TITLE
Run wpcom coblocks 1.23.0 E2E tests

### PR DESCRIPTION
**Pull request by marekhrabe**
🏃‍♂️

See #40598.

### CODE REVIEW

**Comment by marekhrabe** [comment]
Failing:

```
1) [WPCOM] Calypso Gutenberg Editor: Pages (desktop)
15:53:30        Password Protected Pages: @parallel
15:53:30          Publish a Password Protected Page
15:53:30            Can enter page title and content and set to password protected:
15:53:30      TimeoutError: Timed out waiting for element with css selector of '[aria-label^="Document settings"], [data-label^="Document"]' to be clickable
15:53:30 Wait timed out after 21939ms
```

From the recording, I suspect that it's trying to edit something in the sidebar but it doesn't expect it to be opened in the first place and clicking the cog actually closes it and prevents from seeing controls inside it. Just a theory. https://64039-102822243-gh.circle-artifacts.com/0/wp-calypso/test/e2e/screenshots/videos/can-enter-page-title-and-content-and-set-to-password-protected-2020-04-20T15-53-30.mpg

Failing:

```
1) [WPCOM] Calypso Gutenberg Editor: Posts (desktop)
15:53:02        Public Posts: Preview and Publish a Public Post @parallel
15:53:02          Can enter post title, content and image:
15:53:02      TimeoutError: Timed out waiting for element with css selector of '.components-textarea-control__input' to be present and displayed
15:53:02 Wait timed out after 22131ms
```

Looks similar to the last one - it clicks the sidebar toggle button and then fails to follow the rest of test plan. https://64039-102822243-gh.circle-artifacts.com/2/wp-calypso/test/e2e/screenshots/videos/can-enter-post-title--content-and-image-2020-04-20T15-53-02.mpg

```
1) [WPCOM] Calypso Gutenberg Editor: Posts (desktop)
15:54:02        Schedule Basic Public Post @parallel
15:54:02          Schedule (and remove) a New Post
15:54:02            Can schedule content for a future date and see correct publish date:
15:54:02      TimeoutError: Timed out waiting for element with css selector of '[aria-label^="Document settings"], [data-label^="Document"]' to be clickable
15:54:02 Wait timed out after 21989ms
```

Third failed test interacting while with a sidebar. https://64039-102822243-gh.circle-artifacts.com/2/wp-calypso/test/e2e/screenshots/videos/can-schedule-content-for-a-future-date-and-see-correct-publish-date-2020-04-20T15-54-02.mpg

Here I have stopped looking at things in detail and skimmed throught the rest of failed tests. All of them seem to involve interacting with a sidebar and they all fail at it.

**Comment by getdave** [comment]
I'll also take a look here.

**Comment by getdave** [comment]
> [aria-label^="Document settings"], [data-label^="Document"]

I can't see this string `Document settings` on the WPAdmin version of the Block Editor on Dotcom. I do see `Editor settings` though. Could that be the issue? I see that t[his PR from `7.9.0` added a tonne of changes to the `@wordpress/interface` package ](https://github.com/WordPress/gutenberg/pull/20698/)that could have caused this.

**Comment by getdave** [comment]
````js
async enterImageAltText( fileDetails ) { 
 	const altTextInputSelector = By.css( '.components-textarea-control__input' ); 
 	await driverHelper.waitTillPresentAndDisplayed( this.driver, altTextInputSelector ); 
 	return await driverHelper.setWhenSettable( 
 		this.driver, 
 		altTextInputSelector, 
 		fileDetails.imageName 
 	); 
 } 
```

**Comment by getdave** [comment]
Screenshot 2020-04-23 at 11 07 56

I rebased the branch, pushed and then everything got closed. No idea how. I didn't merge it!

**Comment by getdave** [comment]
Ok sorry all. Looks like rebasing and pushing closed the PR. So I created a new PR which has a dummy file in it to ensure it won't get closed.

https://github.com/Automattic/wp-calypso/pull/41400

**Pull request closed without merging**
