### PR TITLE
Use new image file to fix blur and cropping

### LINKED ISSUE #74014: Built by upsell: the logo looks cut off on one side, blurry
The logo looks like it's being cut off on the right side:

Image

It's also blurry in desktop Safari:
screenshot-2023-02-27-at-15 05 48

Raised here: pebzTe-Fg-p2#comment-1362

Acceptance criteria:
- [ ] The whole logo is visible.
- [ ] It's not blurry in Safari.

### PR DESCRIPTION
**Pull request by DustyReagan**
Related to https://github.com/Automattic/wp-calypso/issues/74014

## Proposed Changes

* Update Built By WP image to remove blur and cropping on the side of the circle.

Before | After
--|--
built-by-before  | built-by-after

## Testing Instructions

* Load the PR and view /marketing/tools/:site in Safari
* The Built By WP logo should look sharp and clean
* View in Chrome and Firefox. The image should look good in all cases.

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

**Review by paulopmt1 — APPROVED** [review]
Nice work!
One note: I see the new image have height of 61px and is smaller than the previous one which had a height of 75px. If this is intentional, everything LGTM as we're not cutting the image anymore.

**Review by lupus2k — APPROVED** [review]
LGTM!

**Comment by DustyReagan** [comment]
> One note: I see the new image have height of 61px and is smaller than the previous one which had a height of 75px. If this is intentional, everything LGTM as we're not cutting the image anymore.

I'm not sure I see what you mean. Can you screenshot what you're seeing?

**Comment by paulopmt1** [comment]
> > One note: I see the new image have height of 61px and is smaller than the previous one which had a height of 75px. If this is intentional, everything LGTM as we're not cutting the image anymore.
> 
> I'm not sure I see what you mean. Can you screenshot what you're seeing?

Nevermind, I tried to simulate it again, and it's perfect @DustyReagan! I probably had some cache issue last time I tested it.

**Pull request merged**
