### PR TITLE
[e2e] Disable Passwordless signup test

### PR DESCRIPTION
**Pull request by Stojdza**
#### Changes proposed in this Pull Request

Disable `Passwordless signup` test while this option is completely disabled. Related PR: https://github.com/Automattic/wp-calypso/pull/37054

#### Testing instructions

Make sure that test doesn't run anymore. 

cc @andrewserong

### CODE REVIEW

**Comment by bsessions85** [comment]
@Stojdza  Can we remove the package.lock changes since they have nothing to do with the change?

**Comment by Stojdza** [comment]
My mistake. Done!

**Review by bsessions85 — APPROVED** [review]
:shipit:

**Review by andrewserong — APPROVED** [review]
Nice! Thanks for the ping @Stojdza

**Pull request merged**
