### PR TITLE
Reader: don't show 403/404 errors to user in stream

### PR DESCRIPTION
**Pull request by bluefuton**
If a post is unavailable, don't show an error message in the stream. Fixes https://github.com/Automattic/wp-calypso/issues/11008.

Note: the original issue suggests a helpful message be displayed to site owners (and super admins) to potentially help debug the error. After discussion within #reader Slack channel, it was agreed that all users should see the same output.

Todo:
- [ ] fix <kbd>j</kbd>/<kbd>k</kbd> keyboard shortcuts

### To test

Try http://wpcalypso.wordpress.com/read/feeds/52282073. There is a trashed post at the beginning of the feed that displays an error message:

screen shot 2017-01-27 at 17 44 16

Now try http://calypso.localhost:3000/read/feeds/52282073. The trashed post at the beginning should no longer be visible:

screen shot 2017-01-27 at 17 44 22

### CODE REVIEW

**Comment by blowery** [comment]
How does this play with the `j` and `k` keyboard shortcuts...

**Comment by lancewillett** [comment]
Tested and confirmed (with both a user of the site and non-user) that the feed item is hidden now. 👍

**Comment by bluefuton** [comment]
> How does this play with the `j` and `k` keyboard shortcuts...

Not very well, unfortunately.

> We might need to update selectNextItem and selectPreviousItem in the feed-stream-store to know to skip 404 / 403 posts.

Yep. Keyboard shortcut genius @samouri to the floor please...

**Comment by samouri** [comment]
I'm halfway there..I think. I'm hijacking this PR @bluefuton

**Comment by lancewillett** [comment]
@samouri Is this one still in progress?

**Comment by samouri** [comment]
@lancewillett it is but I think it would be best to punt until we complete https://github.com/Automattic/wp-calypso/pull/10710

**Comment by lancewillett** [comment]
Cool, thanks. Closing for now.

**Pull request closed without merging**
