### PR TITLE
Change e2e tests to work with composite checkout

### PR DESCRIPTION
**Pull request by sirbrillig**
#### Changes proposed in this Pull Request

This modifies the e2e tests to work with both new checkout and old checkout.

#### Testing instructions

- For old checkout, the tests will be run by CI on this PR.
- For new checkout, see the CI tests in https://github.com/Automattic/wp-calypso/pull/43238 which includes these commits.

### CODE REVIEW

**Comment by sirbrillig** [comment]
Note that there are some "Invites" tests failing, which are unrelated to these changes. . I investigated that in Slack a bit: p1591990467070900-slack-calypso

**Review by gwwar — APPROVED** [review]
Thanks for the follow up @sirbrillig ! Overall changes look reasonable.

I'd maybe see if @bsessions85 has any other feedback for the component helpers, but otherwise I think this is safe to land if we know any test breakages aren't related to changes here.

**Comment by sirbrillig** [comment]
Rebased after #43251, which should take care of the other failing e2e tests.

**Comment by sirbrillig** [comment]
Hm. Still a bunch of "Inviting new user as an Editor" failures. More than last time, actually.

**Pull request merged**
