### PR TITLE
Editor: update insert content button

### PR DESCRIPTION
**Pull request by jhnstn**
This combines "insert content" and "insert special" into one menu item in the editor. All the options previously available in the "insert special" menu are now accessible from the one single button.

See p3fqKv-5Oi-p2

before:
before

after:
after

**Testing**

The button should open the 4 content types that can be added: media, from Google, Contact Form and Payment Button

### CODE REVIEW

**Comment by donpark** [comment]
I noticed that, if I mouse over *Paragraph Menu Button* while *Insert Content Menu* is displayed, *Paragraph Menu* pops up. **Reverse is not true**. If I mouse over *Insert Content Menu Button* while *Paragraph Menu* is displayed, nothing happens.

**Comment by iamtakashi** [comment]
> If I mouse over Insert Content Menu Button while Paragraph Menu is displayed, nothing happens.

@donpark Actually, all dropdown there is meant to open when it's _clicked_ not hovered. But yes, you spotted a bug. Good catch!

> if I mouse over Paragraph Menu Button while Insert Content Menu is displayed, Paragraph Menu pops up.

untitled2

The text format dropdown should NOT open when it's hovered while the add dropdown is open, and add dropdown should remain opened.

**Comment by lsinger** [comment]
We show the `editorBasicsTour` to every new user when they enter the editor for the first time. With this PR, two of its steps are a bit non-sensical. 

To trigger it, visit a URL like `http://calypso.localhost:3000/post/SITE_URL?tour=editorBasicsTour`

Can we change it along with this change here? Should we just consolidate the two "adding" steps into a single one? What should it say?

**Comment by lsinger** [comment]
Proposal: 

screen shot 2017-10-11 at 5 43 38 pm

In context:

editor-basics-update

(see 5e36f5df)

**Comment by iamtakashi** [comment]
@lsinger Thanks for the info!

> Can we change it along with this change here? Should we just consolidate the two "adding" steps into a single one? What should it say?

I think the necessary changes to the tour would be better in a separate issue/PR to keep this PR easy to review. I'll create an issue and let's start to discuss what needs to be done there.

**Comment by lsinger** [comment]
I left a comment with a solution and also added a commit to this branch, but both seem to be gone now. I don't understand what is happening.

**Comment by iamtakashi** [comment]
@lsinger Thanks for working on the tour so quickly. I'd like to edit some text in the Simple Payments tour, but your proposal to the editor basic tour looks good!

**Comment by jhnstn** [comment]
Thanks for catching that @lsinger !

**Comment by iamtakashi** [comment]
@lsinger I've adjusted the margin a little so it points to the middle of [+], and I also incorporated the copy suggestion in #18754 for this tour as well. Is it ok?

screen shot 2017-10-11 at 21 30 56

**Comment by jhnstn** [comment]
We can follow up on the hover menu bug in a new PR since the new functionality has a high priority.
I have a feeling that it might be deep in the tinyMCE code but I haven't looked yet

**Comment by Copons** [comment]
Nice!

I'll see to replicate this change in the HTML Toolbar as well! 🙂

**Pull request merged**
