### PR TITLE
Reader: Pull config check out of ReaderMain

### PR DESCRIPTION
**Pull request by blowery**
Move to FollowingEdit, where it belongs.

### CODE REVIEW

**Comment by blowery** [comment]
cc @samouri @kjellr

**Comment by blowery** [comment]
To test, `DISABLE_FEATURES=reader/refresh/stream make run` locally, verify that Full Post still has a white background

**Comment by kjellr** [comment]
WFM in full-post view, but the stream also has a white background. Is that intentional?

screen shot 2016-11-17 at 11 38 03 am

**Comment by blowery** [comment]
@kjellr nope, fixing that too. sigh.

**Comment by blowery** [comment]
@kjellr fixed, can you retest?

**Comment by kjellr** [comment]
That fixes it! Thanks @blowery

**Pull request merged**
