### PR TITLE
Add email button to domain only flow

### PR DESCRIPTION
**Pull request by belcherj**
#### Changes proposed in this Pull Request

* Adds a "Manage Email" or "Add Email" button to the domain only screen.

#### Testing instructions

* Have domain only with G Suite
* Goto that site
* Observe "Manage Email" button
* Button should take you to email manage page

* Have domain only without G Suite
* Goto that site
* Observe "Add Email" button
* Button should take you to G Suite CTA

Screen Shot 2019-04-02 at 4 55 43 PM

Screen Shot 2019-04-02 at 2 30 16 PM

### CODE REVIEW

**Comment by wensco** [comment]
Out of curiosity...since it's not mentioned here and I didn't see any posts or references to testing on this topic, is this being done as a test (or a result of a test) to see how this impacts G Suite conversions?

**Comment by belcherj** [comment]
Not being done as a test or as the result of a test.  Since domain only users can now purchase G Suite adding a button to help them do so made sense. If you have concerns happy to hear them out.

**Comment by wensco** [comment]
> Not being done as a test or as the result of a test. Since domain only users can now purchase G Suite adding a button to help them do so made sense. If you have concerns happy to hear them out.

Gotcha. No specific concerns, just a matter of curiosity as I mentioned. :)

**Comment by cbauerman** [comment]
Screen Shot 2019-04-08 at 4 50 51 PM
Got the following error, but it looks to be unrelated to any of our changes.

**Pull request merged**
