### PR TITLE
Happychat: Fix sidebar sizing issues in Editor and other places

### PR DESCRIPTION
**Pull request by jasmussen**
This changes the panel mode to be the base style, and the sidebar mode to be CSS that overrides the panel mode. This allows us to enable the panel mode on larger breakpoints, without having to resort to ugly duplicate CSS hacks.

As part of this, I removed a bunch of old hacks, and simply invoked the panel mode instead. This includes the editor, the reader, and looking at a single theme. It would be nice if we could have the sidebar in the reader, but zooming into a single reader post makes the sidebar overlap the full bleed card.

This also fixes an issue in Happychat with the new editor.

Because it's major CSS surgery, would appreciate a good review, many eyes, and tests in various browsers. Thank you.

**Steps to test:**

- Load up this branch, or the calypso.live version. 
- Open up a chat.
- Visit as many sections of Calypso as you care to. 

Please try the above in as many browsers as you have the energy for, and verify that things look right. And by "looking right" I mean no obvious layout issues. The chat will be in panel mode on some pages, that is intended.

### CODE REVIEW

**Comment by jasmussen** [comment]
Tested in Chrome and Firefox on the Mac. 

I can't seem to load http://calypso.localhost:3000/help at all on Safari (which seems unrelated to the changes in this PR) — anyone else?

**Comment by jasmussen** [comment]
Tested it in Safari via calypso.live. Works fine.

**Comment by nosolosw** [comment]
Tested in chrome on Linux (Ubuntu).

My understanding is that `sidebar` mode means happychat in the right sidebar taking up all the vertical space and `panel` mode means happychat in a floating small window in the right.

Tried several sections (help, customizer, editor, pages, etc) and viewports. All look good. In a big viewport, all sections show the `sidebar` mode except in the editor, where I could only get the `panel` mode.

**Comment by jasmussen** [comment]
> My understanding is that sidebar mode means happychat in the right sidebar taking up all the vertical space and panel mode means happychat in a floating small window in the right.

Correct!

> Tried several sections (help, customizer, editor, pages, etc) and viewports. All look good. In a big viewport, all sections show the sidebar mode except in the editor, where I could only get the panel mode.

Sounds like it works as intended, then. Thanks for testing.

Also tested in Android Chrome, worked fine.

Only Windows browsers, Safari, and perhaps a code review remaining, looks like!

**Comment by kriskarkoski** [comment]
Should the saved message be appearing over the post settings? This is in a narrowed Chrome window:

screen shot 2017-03-17 at 10 33 03 am

And here it is with Happychat opened:

screen shot 2017-03-17 at 10 33 14 am

**Comment by nosolosw** [comment]
Did a bit more testing in the editor with the post settings sidebar **and** the chat panel as well. This is how it looks the transition between medium and large viewports.

medium viewport at maximum size:

vp-medium-max

big viewport at minimum size:

vp-large-min

Could repro the same issue on chrome and FF, on Linux. If either the post settings or the chat pannel is not activated, the editor has a more smooth transition between viewports.

**Comment by kriskarkoski** [comment]
I am not sure if this was a result of these changes, but occasionally the cursor and first line drop behind the toolbar. I haven't been able to reproduce it consistently, but it seems to happen most often after toggling the post settings to hidden:

screen shot 2017-03-17 at 12 29 20 pm

**Comment by jasmussen** [comment]
Thanks for the thorough test results, some interesting findings here. I'll take a look early next week!

**Comment by timmyc** [comment]
@kriskarkoski that likely could be from #12078 - I thought I had fixed all of those lingering issues, but will play around with that in this branch too. By chance do you remember the screen size when you saw this?

**Comment by kriskarkoski** [comment]
@timmyc It should be right around 425-430px wide, I am not sure on the height but it was pretty tall as it was on by Thunderbolt monitor as I was testing changing the width of a bigger window at the time. If you can't repro please let me know and I will be happy to record some testing and note the screen size once I see it.

**Comment by jasmussen** [comment]
The weird viewport sizing issues that were reported here https://github.com/Automattic/wp-calypso/pull/12270#issuecomment-287397354 should be fixed now:

screen shot 2017-03-20 at 09 27 42

@timmyc I'm going to try and get this merged in, hope that's okay. I'll take a look at the footer issues as well as some other bugs in a separate branch, feel free to join in on that one.

**Pull request merged**
