### PR TITLE
Add search spotlight placeholder to JITMs

### PR DESCRIPTION
**Pull request by gcsecsey**
Related to https://github.com/Automattic/dotcom-forge/issues/2743

## Proposed Changes

In #78010 we've passed the search parameters to the WPCOM call, and the JITMs were only returned from the backend. This PR adds a placeholder message to the banner on top of the search results, to avoid layout shifts when the JITM gets rendered. We've tried a similar approach with a default message being returned from the backend, but that has resulted in a noticeable delay. Related thread: pdh6GB-2Ty-p2#comment-3665

## Testing Instructions

* Patch changes in D114133-code and sandbox `public-api.wordpress.com`
* With a simple site, go to `/plugins`
* Visit any category/search for any search term that is matched in the diff
* Verify that before the JITM is loaded from WPCOM, the loading placeholder is being displayed

Video of the banner loading:

https://github.com/Automattic/wp-calypso/assets/11555574/017c7ba2-bf44-4701-804e-3d3124456be7

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

**Review by epeicher — APPROVED** [review]
I have tested it, and it works as described. LGTM! 🚢 

With this code in place, we can iterate over it and decide a good default (or list of good defaults) as suggested in the thread pdh6GB-2Ty-p2#comment-3675

**Comment by gcsecsey** [comment]
I've added styling to the spotlight component to create a loading placeholder similar to the search results. Here is how is looks on desktop and mobile, and a short video showing all breakpoints:
CleanShot 2023-06-26 at 15 23 17@2x
CleanShot 2023-06-26 at 15 23 09@2x

https://github.com/Automattic/wp-calypso/assets/11555574/e6dcb677-0f3e-4829-bc4a-9f622c703399

**Comment by epeicher** [comment]
> I've added styling to the spotlight component to create a loading placeholder similar to the search results.

Thanks for that @gcsecsey, the video looks great! What should be the backend diff that we should use for testing? Is it still `D113284`?

**Comment by gcsecsey** [comment]
> > I've added styling to the spotlight component to create a loading placeholder similar to the search results.
> 
> Thanks for that @gcsecsey, the video looks great! What should be the backend diff that we should use for testing? Is it still `D113284`?

That should still show some test banners, but D114133-code is the one we're going to deploy once we solve the loading state. I've updated the test steps with this diff as well.

**Comment by gcsecsey** [comment]
@epeicher I managed to add the fetching state to the store and the JITM component with fairly minimal changes. Please give it a quick look and let me know what you think about this approach.

**Comment by epeicher** [comment]
After the two last commits [a6ec1e2](https://github.com/Automattic/wp-calypso/pull/78138/commits/a6ec1e2ea6fd70c116ffd9fb604e1b9b0f851be9) and [24beef0](https://github.com/Automattic/wp-calypso/pull/78138/commits/24beef086f797780c4224e3adaefced5be884947) I am able to see the skeleton when doing a search and browsing through categories 🎉 

I will go ahead and do an end-to-end review using the backend code 👍

**Review by epeicher — APPROVED** [review]
I have tested it, and it works as advertised. LGTM! 🚢 

CleanShot 2023-06-28 at 12 33 32@2x

**Pull request merged**
