### PR TITLE
JP Manage: 283 - show pricing page in non-English languages

### PR DESCRIPTION
**Pull request by tbradsha**
Resolves Automattic/jetpack-manage#283 - show pricing page in non-English languages

## Proposed Changes
While the JP Manage pricing page was translated, there was no way to access the translated content. This adds a `:lang` route and uses `setLocaleMiddleware()` so that translated pages show properly.

It also adds a Tracks `path` param and tweaks the CSS for license selector to account for text wrapping:

Without CSS changes:
image

After CSS changes:
image

## Testing Instructions

One can access translated pages from the language picker in the footer, or by directly manipulating the URL.

1. Test the license selector here: `http://jetpack.cloud.localhost:3000/manage/pricing`
2. Test the license selector here: `http://jetpack.cloud.localhost:3000/es/manage/pricing`
3. Test the license selector here: `http://jetpack.cloud.localhost:3000/manage/pricing?lang=fr`
4. Verify this page still loads: `http://jetpack.cloud.localhost:3000/pricing`
5. Verify this page still loads: `http://jetpack.cloud.localhost:3000/es/pricing`

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

**Comment by cleacos** [comment]
Does this PR still make sense after this PR https://github.com/Automattic/wp-calypso/pull/87287 ?

**Comment by cleacos** [comment]
If so, maybe it should be updated and remove the part already addressed in that PR https://github.com/Automattic/wp-calypso/pull/87287

**Comment by tbradsha** [comment]
Yes, this PR enables languages. The other PR simply refines things, and is based on this PR (so would be merged into here).

**Comment by tbradsha** [comment]
@cleacos I'm wrong...I thought I'd adjusted the base for the other PR, but apparently not. As there's been plenty of discussion on the other one, and this one isn't explicitly needed, I'll just close it. Thanks for spotting that!

**Pull request closed without merging**
