### PR TITLE
Browserlist: Use Gutenberg's settings

### PR DESCRIPTION
**Pull request by blowery**
More restrictive than our current settings.

Alternative to #31532

### CODE REVIEW

**Comment by blowery** [comment]
Updated this to use`@wordpress/browserslist-config` instead of duplicating the values.

**Comment by simison** [comment]
This can probably be removed — Babel will pick the list from browsreslist config:

https://github.com/Automattic/wp-calypso/blob/2b2ca2b01466b33add52c533cb6383cef7080be2/babel.config.js#L12

**Comment by simison** [comment]
Babel config is removed in https://github.com/Automattic/wp-calypso/pull/30768 — I noted that the change could be PRed separately: https://github.com/Automattic/wp-calypso/pull/30768/files#r266867535

**Comment by sgomes** [comment]
Good idea, @simison! Created #31561.

**Comment by blowery** [comment]
Ahhhh, yes, that explains why the JS didn't change at all. Good catch @simison! I'd thought the other change had already landed.

**Comment by blowery** [comment]
Rebased and picked up #31561

**Comment by simison** [comment]
Here's the old list: https://browsersl.ist/?q=last+2+versions%2C+Safari+%3E%3D+10%2C+iOS+%3E%3D+10%2C+not+ie+%3C%3D+10%2C+%3E+1%25

New Gutenberg one: https://browsersl.ist/?q=%3E+1%25%2C+ie+%3E%3D+11%2C+last+1+Android+versions%2C+last+1+ChromeAndroid+versions%2C+last+2+Chrome+versions%2C+last+2+Firefox+versions%2C+last+2+Safari+versions%2C+last+2+iOS+versions%2C+last+2+Edge+versions%2C+last+2+Opera+versions

(https://github.com/WordPress/gutenberg/blob/e0cdf6809fd99dab1de2ed11802c42bbf85d4961/packages/browserslist-config/index.js#L3-L12)

**Review by simison — APPROVED** [review]
Global coverage drop from 85.68% to 83.75% seems acceptable considering that we get smaller bundles (and they'll just get smaller as time goes by) _and_ we don't need to maintain this list anymore.

**Comment by simison** [comment]
We just did this same change over at Jetpack https://github.com/Automattic/jetpack/pull/11616 :-)

**Pull request merged**
