### PR TITLE
chore: Update Node to 14.16.0

### PR DESCRIPTION
**Pull request by scinos**
#### Changes proposed in this Pull Request

* Updates Node to 14.16.0

We still have one dependency on `chokidar@2` (which is not compatible with Node 14) from `watchpack`. But looking at the code, they will firs try to use `chokidar@3` if available, and in our case it is. So it should be safe. You can check https://node.green/ to see the differences betwneen Node 14 and Node 12. The most important one is that now we can use nullish operator (`??`) and optional chaining (`?.`) in Node scripts.

### CODE REVIEW

**Comment by scinos** [comment]
TeamCity e2e tests will fail because the base image uses Node 12. We have to manually run 'Build base images' once this is merged.

CircleCI e2e tests will fail because the Node version used for the tests is configured in CircleCI UI. ONce this is merged, we have to change it manually.

**Review by alshakero — APPROVED** [review]
Tested starting Calypso and ETK and all seems to work well. Thanks!

_I needed to run `yarn` to update node_modules_.

**Comment by alshakero** [comment]
wp-env update is now in https://github.com/Automattic/wp-calypso/pull/51134.

**Comment by noahtallen** [comment]
> TeamCity e2e tests will fail because the base image uses Node 12. We have to manually run 'Build base images' once this is merged.

That's unfortunate. Will canary tests still work? I guess we'll have to smoke test a little more carefully in this case 🤔

**Review by noahtallen — APPROVED** [review]
The calypso build also looks good, as does making changes/refreshing.

I did notice this warning in the build log:
Screen Shot 2021-03-17 at 4 26 57 PM

**Comment by scinos** [comment]
> That's unfortunate. Will canary tests still work?

Yes.... if I update the CircleCI env var after merging but before deployment (which I usually do on every Node update).

**Pull request merged**
