### PR TITLE
Account Recovery: Add the reset password is succeeded page

### PR DESCRIPTION
**Pull request by southp**
## Summary
This PR is based on #13362 and adds the final "reset password is succeeded" page:

## Test Plan
Unfortunately there is no quick access to this page, so we would need to modify one line of code here.

1. Open [client/account-recovery/controller.js](https://github.com/Automattic/wp-calypso/blob/master/client/account-recovery/controller.js#L16), find the line 16 and update it as:
```
firstStep={ STEPS.RESET_PASSWORD_SUCCEEDED }
```
1. Save and `make run`
1. Visit http://calypso.localhost:3000/account-recovery , and you should see the "Reset password is succeeded" page as the screenshot above.
1. Click "Log in" button should lead you to the login page.

### CODE REVIEW

**Comment by folletto** [comment]
I was about to suggest to use one of the components we already have for that, but the naming isn't ideal: `EmptyContent`. In theory it does exactly that kind of message structure, so maybe even if it's called "empty" we can use it here too? I'm not 100% sure, but the pattern matches.

I'd also avoid using the WordPress logo, and maybe use `illustration-ok.svg`. :)

/fyi @kjellr for the illustration use

**Comment by kristastevens** [comment]
Simple and straightforward text! Looks fine to me. I'll remove the "needs copy review label."

**Comment by southp** [comment]
@omarjackman @folletto Thanks for pointing out the `<EmptyContent>` component for me! After 9f0cf4c , it now looks like this:
image

Could you two help me take another look? Much appreciated :)

**Comment by folletto** [comment]
Design wise, it's good. 👍 

I'll tag for a copy review. ;)

**Comment by kristastevens** [comment]
Looks great! Thanks for the ping!

**Pull request merged**
