### PR TITLE
Checklist: Janitorial state work

### PR DESCRIPTION
**Pull request by sirreal**
Design type sneaks into checklist state and is never used. It's also available from site options:
D8702-code / #20632

- Remove redundant design type from checklist state (via fromApi, data never enters Calypso)
- Modify selectors to access tasks directly (no more `{ tasks: {}, designType: "" }`)
- Leverage `keyedReducer` over `createSelector`.
- Leverage `getSiteOption` selector.

## Testing

1. **In production**, verify that the site design type is redundant data stored in two places https://wordpress.com/?debug
   1. Load checklists into state for your sites 
      ```js
      Object.keys( state.sites.items ).forEach( siteId => dispatch( { type: 'SITE_CHECKLIST_REQUEST', siteId } ) );
      ```
   1. Wait a moment for requests to complete…
   1. Look at these results and verify that the the design type provided as a site option is identical to the design type provided in the checklist except where one is `null` and the other is `""`.
      The following will produce an array of pairs the design type values from both locations filtered by for differences, e.g. `[ [ 'site', 'blog' ], [ 'blog', 'site' ], /* … */ ]`
      ```js
      Object.keys( state.sites.items ).map( k => [ state.sites.items[k].options.design_type, state.checklist.items[k].designType ] ).filter( ( [ siteDesignType, checklistDesignType ] ) => siteDesignType !== checklistDesignType )
      ```
1. This data, in addition to being redundant, appears to be unused from `state.checklist.items[ siteId ].designType`. Verify this is correct.
1. [**On this branch**](https://calypso.live/?debug&branch=update/checklist-redux-janitorial), query checklists from all your sites and ensure there are no schema warnings:      
   ```js
   Object.keys( state.sites.items ).forEach( siteId => dispatch( { type: 'SITE_CHECKLIST_REQUEST', siteId } ) );
   ```
1. Ensure checklists that depend on this state continue to work correctly. Test the completion toggle on simple sites as well as updating on completion for the checklists.
   - Simple sites
     - checklist banner at `/stats/SITE_SLUG`
     - Simple site checklist banner at `/checklist/SITE_SLUG`
   - Jetpack sites: `/plans/my-plan/SITE_SLUG`

### CODE REVIEW

**Comment by adamziel** [comment]
What do you think about having a unit test or two for `fromApi`?

**Comment by ockham** [comment]
> [1.iii.] 
> Look at these results and verify that the the design type provided as a site option is identical to the design type provided in the checklist except where one is `null` and the other is `""`.
>      The following will produce an array of pairs the design type values from both locations filtered by for differences, e.g. `[ [ 'site', 'blog' ], [ 'blog', 'site' ], /* … */ ]`
>
> ```js
>       Object.keys( state.sites.items ).map( k => [ state.sites.items[k].options.design_type, state.checklist[k].designType ] ).filter( ( [ siteDesignType, checklistDesignType ] ) => siteDesignType !== checklistDesignType )
> ```

> VM613:1 Uncaught TypeError: Cannot read property 'designType' of undefined

> `state.checklist`
> `{items: {…}}`

Trying with `state.checklist.items`:

> ```js
>       Object.keys( state.sites.items ).map( k => [ state.sites.items[k].options.design_type, state.checklist.items[k].designType ] ).filter( ( [ siteDesignType, checklistDesignType ] ) => siteDesignType !== checklistDesignType )
> ```

> VM613:1 Uncaught TypeError: Cannot read property 'designType' of undefined

Seems like my `state.sites.items` and `state.checklist.items` contain different keys for me :slightly_frowning_face:

**Comment by ockham** [comment]
> Does the following produced an error for you in production? I've just tested and produces an array of `[null, ""]` as expected (updated command in testing instructions):
>
> ```js
> Object.keys( state.sites.items ).map( k => [ state.sites.items[k].options.design_type, state.checklist.items[k].designType ] ).filter( ( [ siteDesignType, checklistDesignType ] ) => siteDesignType !== checklistDesignType )
> ```

This works :+1:

**Comment by sirreal** [comment]
Rebased.

**Comment by sirreal** [comment]
Rebased

**Pull request closed without merging**
