### PR TITLE
Adding renewal and upgrade tests

### PR DESCRIPTION
**Pull request by bsessions85**
#### Changes proposed in this Pull Request

* To better ensure we are covering as much of the checkout flow as possible, I have added two new tests that will go through checkout. One is a renewal and one is an upgrade. The tests do not actually complete the payment, but they make sure the correct items are in the cart.

#### Testing instructions

Ensure Renew a Plan and Upgrade a Plan tests pass in desktop and mobile

### CODE REVIEW

**Review by blowery — APPROVED** [review]
LGTM!

**Review by Stojdza — COMMENTED** [review]
Looks good, mobile and desktop 👌

**Comment by brbrr** [comment]
FYI tests added in this PR does not work in Jetpack, which causes failures in CI

**Comment by bsessions85** [comment]
@brbrr  Sorry about that! I didn't even notice the Jetpack label there

**Pull request merged**
