### PR TITLE
Jetpack Plans: Show better error descriptions and Happychat button in Thank You page for paid plans

### PR DESCRIPTION
**Pull request by oskosk**
#### Changes introduced by this PR

This PR implements the changes proposed in p6TEKc-1rT-p2

* Fixes checks of multisite environments (Specifically detection of a primary site in a multisite enviornments)
* Removes white card which previously included error details, link to manual installation and link to contact form.
* Moves error details into ThankYouCard's description section.
* Moves link to action section looking as a regular text link instead of a button. Text reads `"You will ned to set up your plan manually."`.
* Shows Happychat Button in the cards' actions section for all paid Jetpack Plans when an error is encountered (if operators are available).
* Makes the feature listing show features with errors in gray instead of prepending an error-y icon next to it. 
* Updates error details to a simplified version in each case. Stating just the condition that made us not be able to continue with auto config. (As opposed to always stating why akismet and vaultpress are related to our plans before each actual error is described )
* Updates the `PlanThankYouCard` component to accept a different heading instead of defaulting to `"Thank you for your purchase!"`
* Shows the heading `"You're almost there"` if we prompt the user to manual installation. 

#### Testing instructions

**Requirements**: Jetpack 5.3 is needed here to make sure that we're detecting the ability to write files properly. Jetpack 5.3 will do a full sync on connection and this behavior is not present in previous versions. This flag (`canUpdateFiles`) may be out of sync by this point in previous versions unless a full sync is triggered manually

1. Clone this branch and test it locally or use [the live branch](https://calypso.live/?branch=update/jetpack-thank-you-card-happychat-button).
1. **Log in into HappyChat staging as an operator** (this is just to ensure there's at least one operator and the HappyChatButton shows. Otherwise you won't see it).
1. Connect a Jetpack site and acquire a paid plan.
1. Wait until you see the Thank you card.

#### Simpler testing.

Instead of going through plan acquisition, one can go to `/checkout/thank-you/:site/:receiptId`. You can find receipt ids by visiting `/me/purchases/billing`. Clikcing on  `View receipt` link for your site  will take you to an URL with a receipt Id.

### CODE REVIEW

**Comment by rickybanister** [comment]
I still need to do more testing to trigger the error state and whatnot, but I think we should point the 'Visit my site' link to the Jetpack dashboard. @MichaelArestad and @dereksmart are working on a post-purchase welcome view of the dash and that would be a better destination since the user has just paid to unlock features there.

**Comment by rickybanister** [comment]
I just deleted the contents of my akismet and vaultpress plugin folders to trigger the manual install prompt and I saw this:

image


I am pretty positive that there were a handful of operators logged into happychat at the time, but I didn't see the chat button. 

I expected to see this:

image

**Comment by rickybanister** [comment]
Last note, I believe operators were available when I had a successful autoconfig as well, in that event I'd like us to show the chat button next to the 'go to site' button:

image

**Comment by oskosk** [comment]
@rickybanister having a blank directory named `vaultpress` or `akismet` is not an error for the autoconfig process. The config goes on by filling those directories. The first time you reported this, you thought the error you were seeing was not the appropriate for an error condition that you thought was associated to your empty directories. But this perception was not accurate. This was a bug when detecting another error condition which was **always a false positive for sites that are not part of multisite installation**. This PR fixes this bug among other things.

Having the empty directory named as the plugin is not an issue to go on with the installation. 

That said... about the Spam protection feature being reporeted as error-y... There may have been another problem by which we weren't able to install or configure akismet on your site. 

How to check if this is an error or a bug in this PR? If you go to your site and Akismet is working 100% properly, with the proper key, then that's the indicator that this error message was wrong and that a checkbox should have been next to the *Spam Protection* with a success description in the card. 

But the fact that you have empty directories named the same as our plugins is not a blocker for the auto config process. It wasn't a blocker before the changes in this PR either. 

**Regarding the Happychat button**

While testing this branch locally or from the live branches version, you will only see the Happychat button if **anyone** is logged into the **Staging HUD** which is not the same as the production HUD. Operators in the production HUD only get to see users in our production deployments.

**Comment by oskosk** [comment]
@rickybanister could you give this one another check ?

@johnHackworth if you have some time, can you check if we're dealing with the appropriate behavior for autconfig in this PR.

**Comment by johnHackworth** [comment]
I've tested this and it looks good to me ( I didn't run into any error config the plans, though)

**Comment by rickybanister** [comment]
Thanks for the explanation @oskosk, I went back through and it looks good to me. I think our next move is to real-life stress test this thing.

**Pull request merged**
