### PR TITLE
Me HappyChat: Import Missing Styling

### LINKED ISSUE #34181: Chat history layout needs padding.
#### Steps to reproduce
1. Log in to your WordPress.com account
2. Open the chat history at https://wordpress.com/me/chat

#### What I expected
I expected a nice presentation, keeping the same layout style 

#### What happened instead
The layout could use a bit of love. At least, we need left padding there. The text is glued to the left separation line.

#### Browser / OS version
I've seen this problem in both Firefox and Chrome, so I think it is not browser dependent.

#### Screenshot / Video
chat-e28094-wordpress com-2019-06-07-08-29-10

### PR DESCRIPTION
**Pull request by Aurorum**
#### Changes proposed in this Pull Request

* Imports the missing styling that currently is breaking the Chat page in Me. It still feels ugly though and I feel like the inline help at the bottom should be removed - would it be safe to do that?
* Accounts for the 1px margin in the sidebar

#### Testing instructions

Visit `/me/chat`

**Before:**

Screenshot 2019-06-21 at 17 33 07

**After:**

Screenshot 2019-06-21 at 17 30 12

Fixes #34181

cc @blowery, @jsnajdr

### CODE REVIEW

**Comment by blowery** [comment]
> It still feels ugly though and I feel like the inline help at the bottom should be removed - would it be safe to do that?

I'm not sure how we should handle that exactly. @drw158 any thoughts?

**Comment by blowery** [comment]
Added a `Needs Design Review` to get some design ideas here.

**Comment by blowery** [comment]
cc @Automattic/lighthouse

**Comment by Aurorum** [comment]
@blowery do you think that it'd be worth proceeding with just importing the missing styling for this? I still think it's worth addressing the issue of the inline help overlap particularly (an easy solution could just be removing it), but improving the design feels more like an enhancement, when it currently feels completely broken

**Comment by jsnajdr** [comment]
The root cause of the missing Happychat styles is that we cherry-pick components from inside the `components/happychat` folder:
```js
import { Composer } from 'components/happychat/composer';
import { Notices } from 'components/happychat/notices';
import { Timeline } from 'components/happychat/timeline';
```
while the stylesheet is imported only by the root module in `components/happychat/index.jsx`.

The usual solution for that is to:
- either split the monolithic `components/happychat/style.css` into individual stylesheets for each component
- or have only one `components/happychat` entrypoint and import subcomponents from there:
```js
import { Composer } from 'components/happychat';
```

@Aurorum do you want to choose one of these solutions and implement it?

The Inline Help popup is certainly intrusive in the Happychat UI, but it's an independent unrelated issue. Maybe we already have some logic (Redux selector?) to hide the Inline Help in certain sections?

**Comment by Aurorum** [comment]
Thanks @jsnajdr! I've split the stylesheets and removed the inline help. I'm still trying to test Happychat properly though, I'm unable to connect currently. I think all the styling is in place and not being overriden though, from what I have been able to check. 

Screenshot 2019-06-26 at 20 20 43

**Review by jsnajdr — APPROVED** [review]
Looks good, thanks for the fix! :+1:

**Pull request merged**
