### PR TITLE
Add/jetpack connect store

### PR DESCRIPTION
**Pull request by johnHackworth**
This PR adds to the redux store the reducers & associated actions related with jetpack-connect, so we can use the API new endpoint to to check an url and pass its status to the jetpack-connect main component.
With this changeset, jetpack-connect main component already checks the user-entered url and displays warnings based in its status. If the url has a non-connected jetpack, starts the connection process, and if it has no jetpack installed, shows the dialog explaining that the plugin need to be installed first.

Some screen caps:
Trying to connect an already connected site:
image

Trying to connect a site with a deactivated jetpack:
image

Trying to connect a site with no jetpack:
image

Non-existent url:
image

How to test
==========
1. Go to http://calypso.localhost:3000/jetpack/connect
2. Enter different urls: non existent ones, existent but not wordpress site, wordpress sites without jetpack, worpress site with an inactive jetpack, wordpress site with an active but unconnected jetpack
3. All the urls should trigger a notice telling what the problem is, except for the site without jetpack (Should open a dialog telling you how to install it) and the active but unconnected (should start the remote auth process... if your jetpack is not using the correct branch, it will redirect you to a non-working url)

What's missing:
==========
I need to add the redux actions & reducers tests yet. This PR was already quite large, so I'll add them in the next one

ping @roccotripaldi @oskosk @ryelle @rickybanister @alternatekev

### CODE REVIEW

**Comment by ryelle** [comment]
I feel like I'm not yet familiar enough with redux to give this a proper code review, but here are some "using it" notes, which are hopefully useful :)

- It looks like the parsed url's path is defaulting to `/`, which is throwing off the `isJetpackActive` check for my sites (where the path should be empty, you can see this with `https://ryelle.codes`).
- It's not catching wordpress.com sites (domain mapped and not), and telling me to install Jetpack.

**Comment by johnHackworth** [comment]
@ryelle thanks for the review, kelly!

I've fixed the default / issue and it should work right now for sites without any path. About the WordPress.com sites... yeah, I need to add a new filter to the API endpoint to check if the site is a .com one (once I figure out how to do it) so we can detect it from calypso too

**Comment by roccotripaldi** [comment]
Good stuff Javi! For certain sites, I get unexpected results, but after some digging, I figured out that it was my server config that was causing the results, and not this PR. I'd say you can ship it, and we can add exceptions for edge cases on the API.

**Comment by roccotripaldi** [comment]
I added a small commit to account for `isWordPressDotCom` - if it looks ok, let's merge it.

**Pull request merged**
