### PR TITLE
Dialog: migrate CSS to webpack 

### PR DESCRIPTION
**Pull request by jsnajdr**
Migrates `Dialog` styles to webpack and merges the `DialogBase` component into `Dialog`. The result is just one `Dialog` component instead of two.

**How to test:**
- verify that all modals still work and look good
- verify that the removed transition styles are really not used anywhere (most probably with `react-transition-group`)

### CODE REVIEW

**Comment by jsnajdr** [comment]
Fixed unit test failures and picked up a few `Dialog` improvements (remove `onClosed`, `appElement` initialization) from #32899 (the WIP `RootChild` modernization).

Should be all green and ready for review now.

**Comment by diegohaz** [comment]
Tested the Media modal (probably others have the same problem). With this change, the backdrop disappeared and pressing ESC or clicking outside doesn't close the modal anymore.

**Before**


**After**

**Comment by jsnajdr** [comment]
@diegohaz Thanks for catching that! When removing the transition CSS styles (`dialog-enter`, `dialog-leave`), I removed too much: including the `background-color` rule that's under the `&` selector. Fixed.

**Review by Stojdza — COMMENTED** [review]
@jsnajdr Modals look good. I re-ran tests and they are green now 👍 Also, I ran tests locally and they work as expected.

**Pull request merged**
