### PR TITLE
Gutenframe: remove unused Gutenlypso extensions

### PR DESCRIPTION
**Pull request by vindl**
#### Changes proposed in this Pull Request

After the removal of Gutenlypso (https://github.com/Automattic/wp-calypso/pull/31416) and migration of Jetpack blocks (https://github.com/Automattic/wp-calypso/pull/31759) this code is no longer used in Calypso.

#### Testing instructions

- Smoke test Calypso and Gutenframe editor.

### CODE REVIEW

**Comment by simison** [comment]
This code is (probably?) still used to build these blocks for P2s using the SDK builder, but I'd rather remove them completely than try to keep them around.

See https://github.com/Automattic/wp-calypso/pull/31927

**Comment by kwight** [comment]
@simison I'm not familiar with the whole SDK process; are you suggesting we do remove them here, or to abandon this PR in favour of #31927?..

**Comment by simison** [comment]
In #31927 I'm trying to ask if we need any of these blocks anymore. I've confirmed trial+trials blocks can be removed.

If any of the block _need_ to stay, #31927 is the right approach.

**Comment by simison** [comment]
cc @dmsnell who knows about these blocks and how they're deployed more than I do. :-)

**Comment by ockham** [comment]
> This code is (probably?) still used to build these blocks for P2s using the SDK builder

Yeah, that's correct. As long as we want those blocks, we should keep their code somewhere.

Let's wait for Dennis to chime in :slightly_smiling_face:

**Comment by dmsnell** [comment]
> Let's wait for Dennis to chime in 🙂

I'm sure y'all can figure out some solution without me.

Historically speaking these blocks _were_ built with the SDK and deployed to internal P2s. It is unclear to me how this fits in with the <abbr title="Jetpack Development Kit">JDK</abbr>. The existing blocks won't disappear if you remove this code while at the same time there will be no clear way to maintain them or update them or add to them.

**Comment by gwwar** [comment]
> It is unclear to me how this fits in with the JDK. 

Did the a8c blocks not move to Jetpack with everything else? I still really want to add my emoji todo list and misc internal blocks. I think all blocks should live where our maintained block build tooling is. We can remove these from the final plugin bundle.

**Comment by sirreal** [comment]
> Did the a8c blocks not move to Jetpack with everything else?

They did not, only the shippable extensions moved.

> I think all blocks should live where our maintained block build tooling is.

The tooling in Jetpack is based on packages that are being published out of Calypso. We should be able to keep the o2 blocks here and use up to date tools.

I would discourage pushing everything into the Jetpack repo. Changes there may be subject to concerns around the Jetpack release cycle and require intervention from @Automattic/jetpack-crew.

**Comment by vindl** [comment]
Thank you all for chiming in! 👍 Closing this according to feedback.

**Comment by gwwar** [comment]
> The tooling in Jetpack is based on packages that are being published out of Calypso. We should be able to keep the o2 blocks here and use up to date tools.

I'm fine with this as long as we don't diverge with how we build blocks 👍

**Pull request closed without merging**
