### PR TITLE
Add/plan selection design

### PR DESCRIPTION
**Pull request by dadish**
#### Proposed Changes

* Updates the SensePlan step design to look like in the designs.
* Adds a basic error handling for SenseiPlan step.

#### Testing Instructions

* Start Sensei Tailored Flow
* Get to the Plan Selectoin Step.
* Confirm that it looks according to the design. km0MaMdbZMb5ySnGP2RSxg-fi-20021306%3A34108
* Confirm that it looks according to the design for smaller screens. km0MaMdbZMb5ySnGP2RSxg-fi-20021480%3A46366
* Disable your network and select a plan.
* Confirm that it has basic error handling.

#### Pre-merge Checklist

- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [x] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?

Related to [#Automattic/sensei-pro/1868](https://github.com/Automattic/sensei-pro/issues/1868)

### CODE REVIEW

**Comment by gikaragia** [comment]
Codewise looks good! There are a couple of issues with how it looks:
Screenshot 2022-11-18 at 16 32 45

The 'Included with Annual Plans' appears twice. Also I would prefer for the extra features of the annual plan to appear on the bottom.

Screenshot 2022-11-18 at 16 34 01

In mobile the 'Save up to..' message appears twice.

**Comment by dadish** [comment]
Thank you very much for the review @gkaragia !

> The 'Included with Annual Plans' appears twice. Also I would prefer for the extra features of the annual plan to appear on the bottom.

According to our designs and on par with other flows, the extra features are displayed on top. See how it looks for the Newsletter flow below. The "**Included with Annual Plans**" text also appears above each extra feature. It's the same as other flows on wordpress.com.

newsletter-plan-selection

Although, it looks like that text is displayed only when user selects monthly plan. I updated it so it shows only when monthly is chosen. 6378567f42e177b409431c26f01a6fd90c117b29

> In mobile the 'Save up to..' message appears twice.

Fixed 6378567f42e177b409431c26f01a6fd90c117b29 See below


https://user-images.githubusercontent.com/2578542/202993386-e996ac8d-cfb8-46a1-9743-0b0afc2da846.mp4

**Review by gikaragia — COMMENTED** [review]
> According to our designs and on par with other flows, the extra features are displayed on top. See how it looks for the Newsletter flow below. The "Included with Annual Plans" text also appears above each extra feature. It's the same as other flows on wordpress.com.

Ah cool! I think that my confusion came from the fact that 'Pick a free domain' is bold and the added 'Included with annual plans' headers appear like they both refer to that one.

Comparing it with the newspack one, there seems to be more spacing between each list item which looks a bit nicer. Can we do something similar.

Also in the designs, the 'Live chat support' appears bold. Also the items themselves are different. Am I looking at the wrong designs? Or there was an update somewhere which I missed? I am comparing it with [i3 here](km0MaMdbZMb5ySnGP2RSxg-fi-20022450%3A35960&t=ecIM0TQDZwXU8Otk-1).

**Comment by dadish** [comment]
> Ah cool! I think that my confusion came from the fact that 'Pick a free domain' is bold and the added 'Included with annual plans' headers appear like they both refer to that one.

👍 

> Comparing it with the newspack one, there seems to be more spacing between each list item which looks a bit nicer. Can we do something similar.
> Also in the designs, the 'Live chat support' appears bold.

Yes. Updated. 495d10be48610f52a36b087d6682840e4c5e3c86

> Also the items themselves are different. Am I looking at the wrong designs? Or there was an update somewhere which I missed? I am comparing it with [i3 here](km0MaMdbZMb5ySnGP2RSxg-fi-20022450%3A35960&t=ecIM0TQDZwXU8Otk-1).

That's odd. I don't know where I took those texts from. 😄 Updated the feature list texts with the correct ones. 67ca07811f8f1f1ab55ee9ec7a19dbdf56bad077

**Review by gikaragia — APPROVED** [review]
Looks great now! 

A minor issue, when you select a monthly plan the '<domain> is included>' text is clickable. Previously the text with the strikethrough was a link which was okish. I think that if it is clickable it should look like a link otherwise it shouldn't be clickable but I am also ok with how it is now.

**Comment by dadish** [comment]
> A minor issue, when you select a monthly plan the ' is included>' text is clickable. Previously the text with the strikethrough was a link which was okish. I think that if it is clickable it should look like a link otherwise it shouldn't be clickable but I am also ok with how it is now.

That part is rendered by the the internal calypso component. I try not to deviate their component designs too much. That way if they do some changes it will not break our flow.

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/7683362

Hi @dadish, could you please edit the description of this PR and add a screenshot for our translators? Ideally it'd include all of the following strings:
- `Priority live chat support`
- `Unlimited courses and students`
- `Interactive videos and lessons`
- `Quizzes and certificates`
- `Sell courses and subscriptions`
- `200GB file and video storage`
- `Advanced Jetpack features`
- `Choose Monthly or Annually`
- `Sensei + WooCommerce + Jetpack + WordPress.com in the ultimate Course Bundle`
- `Get Sensei Pro Bundle`

Thank you in advance!

**Comment by dadish** [comment]
Screen Shot 2022-12-22 at 11 57 13

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/7683362).

**Pull request merged**
