### PR TITLE
upgrade storybook

### PR DESCRIPTION
**Pull request by jameslnewell**
#### Changes proposed in this Pull Request

* Upgraded Storybook from `v5.2` to `v5.3` which introduces a new configuration format 
  - [Migration Guide](https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#from-version-52x-to-53x) 
  - [Medium Article](https://medium.com/storybookjs/declarative-storybook-configuration-49912f77b78)

#### Testing instructions

* Run `npm run components:storybook:start` and confirm the Storybook starts

Fixes #

* Sets the correct `tsconfig.json` file for `fork-ts-checker-webpack-plugin` preventing unrelated errors from the `client` from being shown

### CODE REVIEW

**Comment by blowery** [comment]
Looks good! This probably needs a rebase, I'm seeing it still has the duplicate redux from late last week.

**Comment by blowery** [comment]
Fixes https://github.com/Automattic/wp-calypso/pull/38887

**Comment by jameslnewell** [comment]
Thanks @blowery. A duplicate of `redux` where? I already rebased this morning 🤷‍♂

**Comment by blowery** [comment]
@jameslnewell I must have been on the previous commit. Looks good now!

**Review by blowery — APPROVED** [review]

**Pull request merged**
