### PR TITLE
Reader: add video cards expanded state to redux

### PR DESCRIPTION
**Pull request by samouri**
Follow up to https://github.com/Automattic/wp-calypso/pull/12339.

This PR aims to add video card's expanded state to redux at `ui.reader.cardExpansions`.
 - [x] Make work with videos cards (`showEmbed` --> `isExpanded`)
 - [x] verify all the stats are working as expected. Add `calypso_reader_video_expanded

To test:
1. make sure that photo cards still emit a metric when expanded
2. make sure video cards will still expand/unexpand as expected
3. make sure that video cards emit a new metric `calypso_reader_video_expanded`

### CODE REVIEW

**Comment by jancavan** [comment]
Thanks @samouri. Would it be possible to apply the class `.is-expanded-video` when it's actually expanded? `.reader-post-card__post` set to `flex-direction: row;` works great with video thumbnails, but once it's expanded, it needs to change to `column`.

**Comment by samouri** [comment]
@jancavan, should be working now

**Comment by jancavan** [comment]
@samouri Works great 🚢

**Comment by blowery** [comment]
posts in https://calypso.live/read/feeds/34277 are not expanding to full width...

**Comment by samouri** [comment]
@blowery, which browser? do you have any particular repro steps? I am not seeing that

**Comment by blowery** [comment]
@samouri chrome / latest / open feed / click on play / video only takes up part of the card.

screenshot 2017-04-13 17 05 04

**Comment by jancavan** [comment]
Took a look at this again and can confirm that `is-expanded-video` is being added. Videos are displaying as they should, but I'll have someone else look at the code.

**Pull request merged**
