### PR TITLE
Jetpack Pricing Cart Integration - Handle CTA Label

### PR DESCRIPTION
**Pull request by vikneshwar**
#### Proposed Changes

- Make changes to masterbar-cart-button to have the state in redux instead of inside the component so that we can control the state from other components - create cartOpen state in ui redux
- Changes to show the correct button label with icon when an item is added to cart
- Dispatch state update to open the cart on click of View Cart CTA on any items

#### Testing Instructions

* click on Jetpack Cloud live link below
    * Goto `/pricing`
* or boot up this PR 
    * Run `git fetch && git checkout fix/jetpack-cart-product-cta`
    * Run `yarn start-jetpack-cloud`
    * Goto http://jetpack.cloud.localhost:3000/pricing
* Switch to Bundle section and confirm the button Label on the card is the same as before and confirm that clicking on it takes you to checkout page
* Switch to the Product section and confirm the following
    * All the product cards (except the one already purcahsed) CTA label is **Add to Cart** instead of **Get**
    * Clicking on the CTA adds the item to the cart in header and button label for the item changes to **View Cart**
    * Make sure the **View Cart** CTA matches the design
    * Click on **View Cart** to open the cart and make sure the item is there in the cart
 
##### Before
Screenshot 2022-12-12 at 5 58 29 PM

##### After
Screenshot 2022-12-12 at 5 57 44 PM

#### Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

Related to #

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1203534015891085

### CODE REVIEW

**Comment by noahtallen** [comment]
Just a quick drive-by comment: the ETK (and possibly the stats) builds are "changing" because the action-types file is modified. Since it's shared by nearly everything, these plugin builds see themselves changing and send the notifications -- but in reality, the end user code likely hasn't meaningfully changed. You can probably ignore them :)

**Comment by spraveenitpro** [comment]
Hi @vikneshwar I am able to checkout `fix/jetpack-cart-product-cta` but not `feature/cloud-cart-feature-flag` as mentioned in the testing instructions due to `error: pathspec 'feature/cloud-cart-feature-flag' did not match any file(s) known to git`. Is the branch name correct?

**Comment by vikneshwar** [comment]
@spraveenitpro Oops! Looks like I made a typo, I have updated the PR with the right instructions. But I am putting this PR on do not merge ( more instructions [here](https://app.asana.com/0/1203495437860512/1203534015891085/f) ) will create a separate PR with some modifications. Thanks

**Comment by vikneshwar** [comment]
This PR includes 2 changes

1.  Changing the CTA to **View Cart** when an item is added to cart
2. Clicking on the CTA opens the Cart

However, as per the [discussions here](https://app.asana.com/0/1203495437860512/1203534015891085/f)  we decided that for MVP we will just simply redirect the user to checkout instead of opening the cart, once the [stick banner task](https://app.asana.com/0/1203495437860512/1203534015891089/f) is implemented we can have the cart to open on click of the button. So keeping this PR on do-not merge for now and have the first change mentioned above implemented in #71127

**Comment by manzoorwanijk** [comment]
This PR no longer seems relevant.

CC: @elliottprogrammer @andrii-lysenko

**Pull request closed without merging**
