### PR TITLE
Big Sky: chose font and style

### PR DESCRIPTION
**Pull request by artpi**
This is related to Big Sky work.
This will chose font and style for the request
Works with D132519-code

## Proposed Changes

* Make AI chose the color variation and the font variation
* Pass it to assembler
* 

## Testing Instructions

* Apply D132519-code
* Sandbox public-api
* Go to http://calypso.localhost:3000/setup/ai-assembler/
* Write something
* See color scheme being chosen
* Observe `color_variation_title` being set

## Pre-merge Checklist

- [x] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [x] https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md for your changes?
- [x] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [x] Have you checked for TypeScript, React or other console errors?
- [x] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [x] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [x] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

**Review by dereksmart — APPROVED** [review]
Tested, working as expected

**Review by kthai15 — APPROVED** [review]
works for me

I tried asking for a site about the LA Lakers, it suggested purple
`&color_variation_title=Purple+Twilight&font_variation_title=Commissioner+%2B+Crimson+Pro`

**Review by fushar — APPROVED** [review]
Working well.

Note that if a non-default color or font variation is picked, then the user must upgrade to the ~Premium~ Explorer plan or above.

**Comment by autumnfjeld** [comment]
> I tried asking for a site about the LA Lakers, it suggested purple

Nice!!! 🟣

**Review by taipeicoder — APPROVED** [review]
Tested with the following prompts:

"WordPress fan site"
Screenshot 2023-12-20 at 1 05 37 PM

"Jetpack fan site"
Screenshot 2023-12-20 at 1 06 17 PM

"WooCommerce fan site"
Screenshot 2023-12-20 at 1 07 31 PM

**Comment by artpi** [comment]
5 accepts on one PR, wow, thank you!

**Pull request merged**
