### PR TITLE
Reader: Stick the photo overlay in the right place

### LINKED ISSUE #9162: Photo Cards at narrow width problems
This post: https://wpcalypso.wordpress.com/read/blogs/119058704/posts/66

Creates this card: 
screen shot 2016-11-04 at 1 38 29 pm

Issues
• Fade extends beyond photo to the right.
• Whitespace below photo missing.

### LINKED ISSUE #9182: Reader Refresh: Shadow artifact on photo-only card in DevDocs
#### Steps to reproduce
1. Open https://wpcalypso.wordpress.com/devdocs/blocks/refresh-cards with various browsers and compare the look of the photo-only card

#### What happened
It looks fine in Chrome v54, but in Chrome v50, Firefox v46, and Safari v10 there's an odd shadow either to the right of the photo or below.  It may just be an odd behavior in DevDocs, but I wanted to make sure it was looked at.

This is how it appears in Firefox on OSX:
screen shot 2016-11-07 at 10 32 14 am

#### Context / Source
#automated-testing, #visdiff

### PR DESCRIPTION
**Pull request by blowery**
This 'worked' on latest Chrome, but really needs the top and left to be spec compliant.

Fixes #9182

May fix #9162

### CODE REVIEW

**Comment by blowery** [comment]
## before
cuteness__in_all_its_versatility_ _reader_ _wordpress_com

## after
cuteness__in_all_its_versatility_ _reader_ _wordpress_com

**Comment by blowery** [comment]
found the problem in #9162 and fixed that too

## before
sun_may_company_ _reader_ _wordpress_com

## after
sun_may_company_ _reader_ _wordpress_com

**Comment by jancavan** [comment]
Tested and LGTM 👍

**Comment by fraying** [comment]
Thanks, @blowery! LGTMT

**Pull request merged**
