### PR TITLE
Untangling: Apply new card design in Settings -> Caching

### PR DESCRIPTION
**Pull request by fushar**
Related to p9Jlb4-eSF-p2#comment-14122

## Proposed Changes

This PR applies the new card design in Settings -> Caching.

As a consequence, the old Performance Optimization card in Server Settings has a slight change. This page is going away soon; I don't think the effort to 100% retain its IA is worth it...

Also, in this PR, to minimize risk, I tried very hard to not touch the lines containing actual logic.

> [!NOTE]  
> Further UX refinements (such as submit button handling) are out of scope for now.

|Settings -> Caching|
|-|
|image|

|Server Settings (before) |Server Settings (after) |
|-|-|
|image|image|

## Why are these changes being made?

pbxlJb-6ye-p2

## Testing Instructions

1. Go to `/sites`.
2. Click an Atomic site.
3. Go to Settings -> Caching subtab.
4. Verify that the functionality still works.
5. Go to `/sites?flags=-untangling/hosting-menu`.
6. Click an Atomic site.
7. Go to Server Settings tab.
4. Verify that the Performance Optimization card still works.

## Pre-merge Checklist

- [x] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [x] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [x] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [x] Have you checked for TypeScript, React or other console errors?
- [x] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [x] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [x] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Comment by taipeicoder** [comment]
The spacing between the toggle and the button is gone.

Screenshot 2024-11-13 at 9 03 34 AM

**Comment by fushar** [comment]
> The spacing between the toggle and the button is gone.

Thanks, totally missed that, added it back! 🙏

**Review by taipeicoder — APPROVED** [review]
LGTM 👍

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/17001570

Some locales (Hebrew, Japanese) have been temporarily machine-translated due to translator availability. All other translations are usually ready within a few days. Untranslated and machine-translated strings will be sent for translation next Monday and are expected to be completed by the following Friday.

Thank you @fushar for including a screenshot in the description! This is really helpful for our translators.

**Pull request merged**
