### PR TITLE
Enable store email settings in production.

### PR DESCRIPTION
**Pull request by budzanowski**
### Information
Go Live with Emails Settings section in Store.

### Perquisites
- [x] https://github.com/Automattic/wp-calypso/pull/21360
- [x] https://github.com/Automattic/wp-calypso/pull/21327
- [x] https://github.com/Automattic/wp-calypso/pull/21292

### End
Last comments and suggestions are more than welcome.

### CODE REVIEW

**Comment by timmyc** [comment]
All 3 prerequisite PR's are ready to 🚢  - once those have landed I'll give this a test pass, and perhaps @kellychoffman or @jameskoster can do one final design 👀  too. Stoked to see this PR!

**Comment by kellychoffman** [comment]
Question: 

Why is `From address` a value and `Recipients (comma separated)` a placeholder? 

screen shot 2018-01-09 at 4 42 25 pm

**Comment by budzanowski** [comment]
Placeholder is used when there is nothing set - the value indicated by placeholder is the value used by default by woocommerce.

**Comment by kellychoffman** [comment]
> Placeholder is used when there is nothing set - the value indicated by placeholder is the value used by default by woocommerce.

Why aren't we setting the recipients? I think users will not realize the email address isn't set. I think we should change the placeholder to a value.

**Comment by budzanowski** [comment]
We are setting it. If user clicks save. If user does not click save then we are just showing what will be used by woocommerce by default. Placeholder value is shown when API returns empty value for that field.

**Comment by kellychoffman** [comment]
Since it is enabled by default, I would like us to set the value before the user clicks save. This way, it is already up and running. The less work the user has to do, the better.

**Comment by timmyc** [comment]
> Since these settings are enabled by default, I would like us to set the values before the user clicks save. This way, it is already up and running. The less work the user has to do, the better.

FWIW settings in WC core displays the defaults in a similar fashion:

woo-email-settings

**Comment by budzanowski** [comment]
The values are already in use. User has to do nothing. No save needed first time. This is how the system works. All is already there. Why placeholder? - because of the following scenario: 
- there is a email set in `New Orders`
- users deletes the value and saves. 
- placeholder default value is shown inside the input field ( the value woocommerce will use )
- if it would be normal value ( not of a placeholder type ) display then user would be confused and would ask: _But I just deleted stuff from this field, why there is something there?_

Maybe we just need a tooltip or give other type of hint to the user about the default value used. The only way not to send any emails is to disable setting.

**Comment by kellychoffman** [comment]
> if it would be normal value ( not of a placeholder type ) display then user would be confused and would ask: But I just deleted stuff from this field, why there is something there?

If it is a normal value and the user deletes it, it should be deleted and a placeholder should be shown. This is common practice.

**Comment by budzanowski** [comment]
So it works this way. I don't know if I am communicating this wrong or just don't understand what is the issue :smile_cat:

**Comment by kellychoffman** [comment]
I would like the email addresses to be values :) This way the user doesn't have to write them in themselves.

**Comment by budzanowski** [comment]
They do not have to. What is shown as a placeholder is used by woocommerce.

**Comment by timmyc** [comment]
@budzanowski I think Kelly is hoping we can just set what we are showing as the placeholder currently, which is the "default" value used by Woo, and have it appear as the value instead of being displayed as a placeholder.. just to eliminate any potential confusion.

We could get this deployed as-is, and do a follow-up PR for this. What do you think @kellychoffman ?

**Comment by kellychoffman** [comment]
Oh yes, fine to do in a separate PR.

**Comment by budzanowski** [comment]
OK. No problem doing that - but it creates different problem :) Nothing is easy. If user deletes  what is in the field and hits save: what then? What user should see? a placeholder ( requires awkward logic ), a value ( this feels wrong ) After refresh the default value will be visible. I will go with what was decided ^ and we will asses if it is OK or not later when it will be live.

**Comment by timmyc** [comment]
Since it sounds more involved then expected, lets move ahead with what we have now and deploy ( if everyone is okay with that ) - then revisit in a follow-up PR so we can make an informed choice based upon the logic needed.

**Comment by budzanowski** [comment]
This waits for #21648.

**Pull request merged**
