### PR TITLE
State: Add a way to delete a Keyring connection

### PR DESCRIPTION
**Pull request by obenland**
This PR adds the ability to remove a Keyring connection.

For Publicize connection this is done server-side after the last Publicize connection for a Keyring connection was deleted, "other" connections, like Eventbrite for example, can't piggy-back of that and need a direct way of removing a connection.

This PR is a prerequisite to make Eventbrite connections work in #8991.

Please feel free to review this PR, even if not requested.

### CODE REVIEW

**Comment by aduth** [comment]
>"other" connections, like Eventbrite for example, can't piggy-back of that and need a direct way of removing a connection.

Is the idea here to call the Keyring delete endpoint from the client when an Eventbrite connection is removed? If we're not handling that on the server, it sounds like something that would be more reliable to do there.

On a similar note, we should probably seek to recreate the behavior of a Keyring connection being removed within state after all Publicize connections using it have been removed (i.e. in Keyring state).

**Comment by obenland** [comment]
>  Is the idea here to call the Keyring delete endpoint from the client when an Eventbrite connection is removed? If we're not handling that on the server, it sounds like something that would be more reliable to do there.

Yes it is, can you elaborate what handling on the server would look like past calling the delete endpoint?

> On a similar note, we should probably seek to recreate the behavior of a Keyring connection being removed within state after all Publicize connections using it have been removed (i.e. in Keyring state).

Right, for now [it only removes the site id](https://github.com/Automattic/wp-calypso/blob/5c67828b11a1ab0ec3f848d1e9a76edc402b6c0b/client/state/sharing/keyring/reducer.js#L38-L44), we could check if the resulting array is empty and remove it then. Currently it gets updated on the next page load or attempt to create a new connection.

**Comment by aduth** [comment]
>Yes it is, can you elaborate what handling on the server would look like past calling the delete endpoint?

Actually, as-is, I would expect that unsetting the Eventbrite option from the `POST /sites/%s/settings` should already delete the Keyring token if it's no longer in use. If it's not, that might be a bug.

See: r117546-wpcom, r117545-wpcom

**Comment by gwwar** [comment]
The code looks good here, though I think I need to understand when we would fire this action.

> For Publicize connection this is done server-side after the last Publicize connection for a Keyring connection was deleted

@obenland could you provide a bit more context? How does this get triggered currently? i.e. What would the testing steps be if this was fully wired in?

**Comment by obenland** [comment]
> Actually, as-is, I would expect that unsetting the Eventbrite option […] should already delete the Keyring token if it's no longer in use. See: r117546-wpcom, r117545-wpcom

Ahh, I didn't know about that. That also explains the 403 errors I got when I tried to delete connections after updating the eventbrite api token :)

In that case the action would only need to remove the connection from state and wouldn't even need to make a request

**Comment by obenland** [comment]
> could you provide a bit more context? How does this get triggered currently? i.e. What would the testing steps be if this was fully wired in?

[This is how it would look wired in](https://github.com/Automattic/wp-calypso/pull/8991/files#diff-1ff68acddcef35bb640ae9f3a531be1dR155). We'd have an Eventbrite-specific component where the disconnect button disconnects the keyring connection (since Eventbrite doesn't have a Publicize connection). TIL that server-side the keyring connection gets deleted by updating the `eventbrite_api_token` site setting, so it looks like this just needs to handle the state change.

**Pull request merged**
