### PR TITLE
Checkout: update 2-year plan upsell card text

### PR DESCRIPTION
**Pull request by IanRamosC**
Related to 1201210512993648-as-1204738167856704

## Proposed Changes

* Update the text in the plan upsell card for 2-year plans

## Testing Instructions

* Visit the Calypso live link
* Go to /checkout/jetpack/jetpack_security_t1_yearly#step2
* Make sure the card on the right side looks like the one below

image

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

**Review by jboland88 — APPROVED** [review]
Easy peasy - LGTM 🚢

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/8021933

Thank you @IanRamosC for including a screenshot in the description! This is really helpful for our translators.

**Comment by sirbrillig** [comment]
Hey folks, please remember that we support many languages and if you modify a translation it's a good idea to either use the String Freeze label and wait for them to complete or to use the `hasTranslation()` method to fall back to the old string while the new one is being translated.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/8021933).

**Pull request merged**
