### PR TITLE
Notifications: Track opening links in notes

### PR DESCRIPTION
**Pull request by eoigal**
This is part of a project I've been working on to add new notifications for billing events;

* Renewal Success
* Renewal Failure
* Missing payment method prior to renewal
* Credit card has expired prior to renewal
* Manual Renewal Reminder (for users with auto renew disabled)

For all the notes, there is a link to do some action related to the event, i.e For renewal failure, there is a link to manage your purchases.

This PR is necessary to track users clicking these links so we can eventually determine how effective the notifications are in resolving a billing issue.

This notes are already passing the tracks information by setting the link `type` attribute to `tracks` and a `context` attribute to the track event we want to hit when this linked is clicked.

```php
/* translators: %1$s link to manage purchases, %2$s is link type, %3$s is link context used to pass tracks event to front end */
$builder->add_block( sprintf(
    __( '<a href="%1$s" type="%2$s" context="%3$s">Keep your site</a> as-is by updating your credit card information and renewing it now.' ),
    $manage_purchase_url ?? 'https://wordpress.com/me/purchases/', 'tracks', 'open_link_update_expired_card'	) );
```

Those attributes are accessible as `range_info` properties when the note blocks are being rendered in Calypso. This means we can create `data` attributes for the link while being rendered. This means we can pass this data to the `OPEN_LINK` handler that is already in place, to send event to tracks.

To test the PR do the following;

* Go to the Payment Admin Notification Tool
* Click on one of the `post note to me` links in the email details section 
* You should see a note in your notes list like the following

screen shot 2018-09-13 at 17 16 37

* Verify that the `Renew now` link has the data attributes, `date-link-type` and `data-tracks-event`.
* Click the `Renew now` link and verify the tracks event shows up on tracks (a few minutes later) 

Ref: p8hgLy-13f-p2

### CODE REVIEW

**Comment by kwight** [comment]
I'm a little confused here, and probably missing something – it doesn't seem like this work should be necessary, since we'd already be Track-ing links in notes? Not sure if Tracks handling has changed at all since notifications went into Calypso; @dmsnell for a sanity check here.

**Comment by kwight** [comment]
@sirbrillig oh, I restarted the tests because of that timout-ish error, should start seeing them soon.

**Comment by gwwar** [comment]
cc @elibud @loremattei in case the call to action here doesn't make sense in Mobile clients.

Notes are consumed by different environments so the overall approach here looks okay, but will target tracks being fired by Notifications read on Calypso. I'm not sure of tracks support in the iframe, but if we'd like to support tracking while clicking on notes say while reading on your personal front end site, check out `client/notifications/src/standalone/index.js`

Notifications code was recently moved to Calypso so we're a bit behind on documentation, so feel free to pair with someone from Lannister if you need help with testing/understanding how to deploy changes to multiple envs.

**Comment by kwight** [comment]
Oh, another thing to keep in mind in general is that there are two other notification consumers: the mobile apps (p9zg7s-2Y-p2), and the front-end iframed Masterbar notifications; you'll want to make sure you're getting what you need in those case too (for instance, links in notes that can't be accessed from within the mobile app need consideration).

**Comment by elibud** [comment]
@kwonye can you make sure this works correctly in iOS and Android? Thx

**Comment by kwonye** [comment]
@elibud thanks for the ping! Verified working (with links removed) on iOS and Android

**Comment by eoigal** [comment]
@kwonye I've updated the notes to show those links again for mobile. I doubt that they'll work with tracks without some update though.

Anyone know what the e2e status fails are about?

**Comment by kwight** [comment]
> Anyone know what the e2e status fails are about?

They're expected today; keep an eye on p8hgLy-17p-p2.

Moving this forward, you'll want to verify that the stats are also being recorded in the Masterbar notifications on the front-end of WordPress.com sites. With recent changes, we'll figure out our new process for that and let you know.

**Comment by kwight** [comment]
@eoigal we've got some issues with the new notifications iframe testing and deploys; we'll keep on it, and still aim for moving you forward this week 👍

**Comment by rralian** [comment]
@kwight any movement on this? We'll need to wait for trailing numbers to come in even after this PR is merged, so I'm hoping we can get it merged this week and have something to look at after the GM.

**Comment by kwight** [comment]
@rralian Yes! We got one half of prerequisite stuff in late Friday, and now just need to merge #27282, which should happen today. Then we'll have a solid, understandable process with which we can move this forward (in the next day or so, certainly before the end of the week).

**Comment by kwight** [comment]
@eoigal @rralian we now need to get https://github.com/Automattic/wp-calypso/pull/27180 in before us too (should still be a matter of tomorrow).

**Comment by kwight** [comment]
Noting that we have both D18484-code and #27180 in now; we'll now need to get in D18799-code (for an RTL fix) followed by #27282, then we should be unblocked for this 😅

**Comment by kwight** [comment]
D18799-code and #27282 are now in; now I need #27468 and an update to a sandbox script because of consideration for https://github.com/Automattic/wp-calypso/pull/27448/#issuecomment-424807461.

**Comment by kwight** [comment]
Rebased and pushed to trigger the new notifications build. I'll use this today to test the front-end iframe, and see if we can get this in.

**Comment by kwight** [comment]
OK, I've tested this branch with the brand-spanking-new process outlined in PCYsg-elI-p2. I verified the correct changes loaded, and that the `date-link-type` and `date-tracks-event` attributes are there (RTL also looks good). While I haven't seen the event pop up yet in the live Tracks view, we could certainly follow up later on that. Feel free to merge, and I'll deploy what I've got on my sandbox. Thanks for your patience! 🎉

**Comment by kwight** [comment]
Deployed to the front-end iframe 👍

**Comment by kwight** [comment]
@eoigal Just a reminder that I noticed this morning that these don't seem to fire on the iframe front-end ([as mentioned above](https://github.com/Automattic/wp-calypso/pull/27184#issuecomment-425245291)). We're heads-down in other stuff (p7jreA-1PC-p2), so I'll leave the follow-up to your team; now that it's all in production, you should be able to sort it out (I just didn't want it to fall through the cracks). Maybe it's something with the `w.js` script? Thanks! 👍

**Pull request merged**
