### PR TITLE
Hosting: Add static file 404 handling UI

### PR DESCRIPTION
**Pull request by brandonpayton**
#### Proposed Changes

This creates a Web Server Settings card that includes
the ability to set both PHP Version and how the web server
handles requests for nonexistent static assets. Previously,
PHP Version had its own card, but it is now part of the
Web Server Settings card.

Old PHP Version card
php-version-card

New Web Server Settings card
web-server-settings

#### Testing Instructions

1. Pick a WoA test site.
2. In a browser, navigate to "https://your-test-site/nonexistent.js" and note that you see a rich, WordPress-generated 404 page.
3. Open the Calypso hosting page for the test site and scroll to the Web Server Settings card.
4. Change the "Handling Requests for Nonexistent Assets" to "Send a lightweight File-Not-Found Page"
5. Refresh the browser tab for nonexistent.js and observe you get a simple nginx 404 page.
6. Try the other options, refresh nonexistent.js, and observe you get the response you expect. The current Default is to use a WordPress-generated 404 page, but we may change it sometime in the future.

### CODE REVIEW

**Comment by JoshuaGoode** [comment]
Tested, works well.

**Comment by brandonpayton** [comment]
There are a couple of state-related unit tests that need to be updated.

**Comment by brandonpayton** [comment]
> Tested, works well.

Thanks for your help and for such a quick response, @JoshuaGoode!

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/7381365

Thank you @brandonpayton for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/7381365).

**Pull request merged**
