### PR TITLE
Jetpack Connect: modified some instruction copy

### LINKED ISSUE #5143: Jetpack Connect: activate description isn't correct
> Once the plugin is installed, you'll need to click this tiny blue 'Activate' link from your plugins list page.

screen shot 2016-05-02 at 10 57 08 am

If I follow the instructions of the connect flow, I don't need to go to my Plugins list page. After clicking the Install button, I'm redirected to this page:

screen shot 2016-05-02 at 10 58 48 am

I think we should update the description to mention this step.

### PR DESCRIPTION
**Pull request by rickybanister**
Fixed up copy of instructions steps, mainly the activation step and swapped instruction images that were wrong. 

Closes #5143

**Before:**
screen shot 2016-06-17 at 12 19 08 pm
screen shot 2016-06-17 at 12 19 36 pm

**After:**
screen shot 2016-06-17 at 12 18 19 pm
screen shot 2016-06-17 at 12 18 49 pm

cc @roccotripaldi @johnHackworth @richardmuscat @jeherve 

Test live: https://calypso.live/?branch=update/jetpack-connect-activate-link-instructions

### CODE REVIEW

**Comment by drw158** [comment]
👍 

Maybe put a `nbsp` before the end of each word. I noticed the orphan on step 2

**Comment by rickybanister** [comment]
@ebinnion can you point me to that function you found that does the orphan/widow thing?

@drw158 there's apparently some kind of magic thing that does it, we don't really like to stick nbsp's in for translations, right?

It seems to me we should make the function turned on by default, and make disabling it be manual.

**Comment by drw158** [comment]
I have heard of the magic, but I haven't used it. Honestly, I don't know what would happen with translation using nbsp.

**Comment by ebinnion** [comment]
The utility is `preventWidows` and it's part of the `lib/formatting` module:

https://github.com/Automattic/wp-calypso/blob/master/client/lib/formatting/index.js#L50-L81

Here's an example usage:

https://github.com/Automattic/wp-calypso/blob/master/client/signup/step-header/index.jsx#L22-L23

**Comment by ebinnion** [comment]
> It seems to me we should make the function turned on by default, and make disabling it be manual.

Looking at the logic, it looks like it expects a string as input. Other types are simply returned. So, I believe that input that includes components might not get the same treatment. That being said, we could always write some tests and verify that assumption and then attempt to fix it.

**Comment by johnHackworth** [comment]
This looks ok to me ... can we already merge it and add any other improvement (like removing that orphan) in another PR?

:ship:

**Comment by rickybanister** [comment]
@johnHackworth That's fine with me—we should give the whole flow the widow/orphan treatment.

**Pull request merged**
