### PR TITLE
Fix/16440/dont share themes query results

### LINKED ISSUE #16440: Themes Showcase: Incorrect Filter Results While Logged In
#### Steps to reproduce

1. Log into WordPress.com 
2. Starting at URL: https://wordpress.com/themes
3. Click on Premium - https://cloudup.com/c6uhx6DJPJG
4. Scroll down and you will start to see Free themes in the Premium filter. The first one I noticed was Confit - https://cloudup.com/clXevpKSyDF
5. Click on **All** to view all themes
6. Activate the Premium theme Peña and return to https://wordpress.com/themes
7. Click on **Free** to view only free themes
8. Click on **Feature**, and select **Post Slider** - https://cloudup.com/c9vOqffytMg
9. Although Peña is not free, and does not have a Post Slider, it will appear in the results - 
https://cloudup.com/cYauykn9aTQ

Note: The filters work correctly while logged out of WordPress.com.

#### What I expected

- When searching for Premium themes, I expected to only see Premium themes in the filter.
- When searching for Free themes, I expected to only see free themes in the filter.
- When searching for themes with post sliders, I expected to only see themes with post sliders.

#### What happened instead
- Themes showed up under filters they do not belong to.

#### Browser / OS version
Chrome Version 59.0.3071.115 / MacOS 10.12.5 

#### Context / Source

#user-report 3271659-t

### PR DESCRIPTION
**Pull request by DanielSmithMichigan**
Our "QueryManager" merges results from multiple different queries together. But we don't have a way to intelligently determine which themes can be matched to which queries, so all queries results are cumulatively combined and all results are shared.

For example: Searching for premium themes, then free themes results in the "free themes" query results having premium themes in it, since it's cumulative.

Consider this second example:

```
Search: Free themes
What does free themes contain? Free themes

Search: Block based themes
Now what does free themes contain? Free themes and block based themes

Search: Full width themes
Now what does free themes contain? Free themes and block based themes and full width themes
````

Why does this happen?

The line of code which determines which themes match to which queries [might not be complete yet](https://github.com/Automattic/wp-calypso/blob/77108e4414894a996c8976fa368f36c1f72e463a/client/lib/query-manager/index.js#L120)

This pull request creates a new parameter: `dontShareQueryResultsWhenQueriesAreDifferent` which prevents query results from being shared. This parameter will be enabled for themes based queries.

This is probably a temporary solution, since QueryManager will probably be replaced when we use react-query.

| BEFORE  | AFTER |
| ------------- | ------------- |
| before | after |

#### Testing instructions 

1. Go to the /themes page
2. Click the "premium" themes button
3. You should only see premium themes
3. Click the "all" themes button
4. You should see premium and free themes
4. Click the "premium" themes button
5. You should only see premium themes
6. Click the "all" themes button
7. Search for "feature:block-templates"
8. Note down which themes you see
9. Refresh the page
10. You should see the same themes

### CODE REVIEW

**Review by mreishus — APPROVED** [review]
I like the approach; the additional flag minimizes the chance that the change will affect unintended parts of the system. The change itself made looks straightforward as well. The system behaves as expected after the change:

https://user-images.githubusercontent.com/937354/126540875-52be7b57-257b-4fad-8bdd-029665553ba7.mp4

LGTM :+1:

**Comment by kwight** [comment]
Nice, works well for me too – good solution, great job! 🚀

**Comment by DanielSmithMichigan** [comment]
I ran into an issue, which is that after installing a theme on atomic, it was no longer automatically added to the "my themes" tab.

Below is a demonstration of that issue before it was fixed in my most recent commit. You can see that I installed "blank canvas" but it's not in my "My Themes" tab.

https://user-images.githubusercontent.com/10274366/126567475-95a63819-2281-4e60-8743-b9a0341da9e4.mov

The issue was introduced in this pull request, the theme data is updated through the query result sharing mechanism which is modified in this pull request.

I introduced a change to refetch all the themes after installing a theme, and that fixes the issue.

**Comment by DanielSmithMichigan** [comment]
The only other case I can find which causes a theme to be received via a non-related query is installing a theme. But that happens in wp-admin for atomic right now.

**Pull request merged**
