### PR TITLE
Start enforcing & auto-fixing ESLint rule react/jsx-curly-brace-presence

### PR DESCRIPTION
**Pull request by mpkelly**
#### Proposed Changes

* Sometimes this is flagged in code reviews and sometimes it isn't. For consistency, this PR proposes to enforce this rule and also benefit from the auto-fix feature of `eslint`. 

I opted for this rule config based on previous code review feedback:

image

The rule homepage and full config options are [here](https://github.com/jsx-eslint/eslint-plugin-react/blob/master/docs/rules/jsx-curly-brace-presence.md) 

#### Testing Instructions

* Checkout this branch and try to modify some JSX props to be like the **incorrect** format above. Verify they are caught by ESLint and can be auto-fixed. 

#### Pre-merge Checklist

- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?

Related to #

### CODE REVIEW

**Comment by jsnajdr** [comment]
There are indeed 137 new ESLint errors 🙂 

Screenshot 2022-10-12 at 7 43 36

Is there a convenient way to find and fix them all?

**Comment by mpkelly** [comment]
> There are indeed 137 new ESLint errors 🙂

Thanks, @jsnajdr. I only checked the report in this PR and it said it was successful. I am going to try and fix these errors with the `eslint` CLI.

**Comment by tyxla** [comment]
Thanks for this @mpkelly! Those are definitely auto-fixable and doing it in this PR sounds like a good call to me.

**Comment by mpkelly** [comment]
I found a way to easily fix a single rule: [eslint-nibble](https://paul-hands-phd.medium.com/hiring-a-gardener-to-trim-the-weeds-adding-a-linter-halfway-through-building-an-application-194c527db151#:~:text=The%20third%20option%3A%20ESLint%2Dnibble). It was faster than trying to reconfigure `eslint`. However, after running:

```
npx eslint-nibble 'client/**/*.tsx'
npx eslint-nibble 'client/**/*.jsx'
```
It found a lot more issues than our build (if I am reading the message above correctly):

image

There are about 600+ issues fixed (from memory). Are we ok doing a review for those? I will time my commit for about this time tomorrow when more people are online. 

You can let me know if we want to add/exclude any file paths.  

@jsnajdr @tyxla

**Comment by jsnajdr** [comment]
If it's really 600+ fixes of the new JSX curly rule and no other one, then I guess we'll need to review that.

**Comment by tyxla** [comment]
Just ran `./node_modules/.bin/eslint-nibble --ext .js,.jsx,.ts,.tsx,.md.js,.md.javascript,.md.jsx client` and got 680 errors indeed. Happy to help with reviewing the auto-fix PR.

**Comment by noahtallen** [comment]
> I only checked the report in this PR and it said it was successful.

To explain this one (I agree that it's confusing), since we have so many existing eslint issues in Calypso, we don't fail the test if eslint reports errors. Instead, we simply report the number of problems to TeamCity, and TeamCity keeps track of them over time. For example, this page includes a graph of style errors over time: https://teamcity.a8c.com/buildConfiguration/calypso_CheckCodeStyle?buildTypeTab=buildTypeStatistics

This runs on a schedule on the trunk branch, just so we can keep track of errors over time.

We do have another code style check which fails when PRs have errors, but it only runs on files changed in the PR, to improve performance and reduce noise. So when we make the change in this PR, it's only linting the eslintrc.js file, which you can see when you look at the log here: https://teamcity.a8c.com/buildConfiguration/calypso_CheckCodeStyleBranch/8780613?hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandBuildChangesSection=true&showLog=8780613_434_410&logView=flowAware

(As a side note, stylelint for css/sass works a bit differently because we're close to resolving all of the existing stylelint issues.) 

Anyways, I think one way to improve things could be to run eslint in CI for _all_ files when a settings file changes or the elint dependency updates.

Hope that's a useful explanation!

**Comment by mpkelly** [comment]
> Hope that's a useful explanation!

It was! Thanks, @noahtallen.

**Comment by mpkelly** [comment]
I used the following command (thanks, @tyxla):

`npx eslint-nibble --ext .js,.jsx,.ts,.tsx,.md.js,.md.javascript,.md.jsx client`

If anyone is interested, this is the full report for the `client` directory:

```
7776 files checked.  7199 passed.  577 failed.  369 warnings.  833 errors.

? Which rule would you like to view? (Use arrow keys)
❯ @typescript-eslint/no-explicit-any:       170|                                  
  @typescript-eslint/no-non-null-assertion:   2| 
  @typescript-eslint/no-this-alias:           2| 
  curly:                                     83|                 
  import/named:                               1| 
  inclusive-language/use-inclusive-words:     2| 
  jsdoc/check-types:                          1| 
  jsdoc/no-undefined-types:                   1| 
  jsdoc/require-property-description:        57|            
  jsdoc/tag-lines:                            2| 
  jsx-a11y/alt-text:                          5| 
  jsx-a11y/anchor-is-valid:                  19|    
  jsx-a11y/click-events-have-key-events:      9|  
  jsx-a11y/heading-has-content:               3| 
  jsx-a11y/html-has-lang:                     1| 
  jsx-a11y/iframe-has-title:                  2| 
  jsx-a11y/no-autofocus:                      1| 
  jsx-a11y/no-static-element-interactions:   10|  
  no-shadow:                                  1| 
  no-use-before-define:                       7|  
  react-hooks/exhaustive-deps:              136|                           
  react/jsx-curly-brace-presence:           680|                                                                                                                                     
  react/no-danger:                            1| 
  react/no-did-update-set-state:              1| 
  wpcalypso/jsx-gridicon-size:                3| 
  wpcalypso/redux-no-bound-selectors:         1| 
  wpcalyspo/jsx-classname-namespace:          1| 
```
I have added the "reviewer can merge" label. I think we should have a couple of reviewers and the last one can merge. 

Pinging @tyxla  and @jsnajdr

**Comment by mpkelly** [comment]
Looking at the merge issue now 👀

**Comment by mpkelly** [comment]
Some CI `eslint` checks fail:

image

I am going to auto-fix `curly` too. May as well remove as many as possible.

**Comment by jsnajdr** [comment]
> I am going to auto-fix `curly` too. May as well remove as many as possible.

That would be better as a separate PR. Otherwise this one could explode into a monster that's hard to rebase. Cc @noahtallen who recently added `curly` in #68923.

> Merge with trunk

This should have been a rebase, which eliminates all the autofixes in `plansStepFaq.jsx`. The `{ 'foo' }` strings have been changed to `{ translate( 'foo' ) }`.

**Comment by mpkelly** [comment]
> > I am going to auto-fix `curly` too. May as well remove as many as possible.
> 
> That would be better as a separate PR. Otherwise this one could explode into a monster that's hard to rebase. Cc @noahtallen who recently added `curly` in #68923.

Ok, so we can still merge this to trunk even with the failed required CI check?

> > Merge with trunk
> 
> This should have been a rebase, which eliminates all the autofixes in `plansStepFaq.jsx`. The `{ 'foo' }` strings have been changed to `{ translate( 'foo' ) }`.

Right. I will revert that commit and then rebase.

**Comment by jsnajdr** [comment]
> Right. I will revert that commit and then rebase.

The current state of the PR is not good: it reverts the `useTranslate` additions in `plansStepFaq.jsx` that were done in #68957. These need to be kept untouched.

The PR should have just two commits:
- enable the rule in ESLint config
- autofix the rule in 300+ files

> Ok, so we can still merge this to trunk even with the failed required CI check?

Better merge the `curly` autofix first, and then rebase and merge this PR on top of it.

**Comment by mpkelly** [comment]
> > Right. I will revert that commit and then rebase.
> 
> The current state of the PR is not good: it reverts the `useTranslate` additions in `plansStepFaq.jsx` that were done in #68957. These need to be kept untouched.
> 
> The PR should have just two commits:
> - enable the rule in ESLint config
> - autofix the rule in 300+ files
> 
> > Ok, so we can still merge this to trunk even with the failed required CI check?
> 
> Better merge the `curly` autofix first, and then rebase and merge this PR on top of it.

Ok, I'm going to scrap this PR and make the `curly` one followed by a new one for the JSX brackets.

**Pull request closed without merging**
