### PR TITLE
Desktop App: update Electron and related package versions.

### PR DESCRIPTION
**Pull request by worldomonation**
Slack: p1686560269103799-slack-C7YPUHBB2
Supersedes https://github.com/Automattic/wp-calypso/pull/75516.

## Proposed Changes

This PR updates the Desktop app to use more recent versions of packages. The goal is to move off deprecated versions that have security vulnerabilities.

Key changes:
- update `electron` to 25.0.1.
- update `electron-builder` to 23.0.3.
- remove `electron-rebuild`.
- update Windows signing key.

## Testing Instructions

Ensure the following build configurations are passing in TeamCity:
  - [x] Unit Tests
  - [x] Code Style
  - [x] Desktop E2E tests

Additionally, check on CircleCI:
  - [x] wp-desktop-assets
  - [x] wp-desktop-mac
  - [x] wp-desktop-linux
  - [x] wp-desktop-windows

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

**Review by wp-desktop — DISMISSED** [review]
WordPress Desktop CI Failure for job "wp-desktop-mac".

@worldomonation please inspect this job's build steps for breaking changes at [this link](https://circleci.com/gh/Automattic/wp-calypso/1120170). For temporal failures, you may try to "Rerun Workflow from Failed".

Please also ensure this branch is rebased off latest Calypso.

**Review by wp-desktop — DISMISSED** [review]
WordPress Desktop CI Failure for job "wp-desktop-mac".

@worldomonation please inspect this job's build steps for breaking changes at [this link](https://circleci.com/gh/Automattic/wp-calypso/1120250). For temporal failures, you may try to "Rerun Workflow from Failed".

Please also ensure this branch is rebased off latest Calypso.

**Comment by worldomonation** [comment]
[CircleCI builds](https://app.circleci.com/pipelines/github/Automattic/wp-calypso/180386) are passing:

image

**Review by wp-desktop — DISMISSED** [review]
WordPress Desktop CI Failure for job "wp-desktop-mac".

@nsakaimbo please inspect this job's build steps for breaking changes at [this link](https://circleci.com/gh/Automattic/wp-calypso/1120422). For temporal failures, you may try to "Rerun Workflow from Failed".

Please also ensure this branch is rebased off latest Calypso.

**Review by nsakaimbo — APPROVED** [review]
Thanks for helping get this update to the finish line, @worldomonation! I made a couple of small additional tweaks, as well smoke-tested the build on Windows. Looks good. Please 🚢.

**Pull request merged**
