### PR TITLE
General: Replace Merriweather with Noto Serif

### LINKED ISSUE #11614: General: Replace Merriweather typeface with Noto Serif
We discovered many months ago that content written in languages not using the basic latin character set display inconsistently in Calypso, because of our use of the Merriweather typeface. A screenshot comparison is below that illustrates the biggest problems:

- Languages that use an extended latin alphabet (like Vietnamese) are missing characters. On some platforms this results in a system font being substituted for individual characters, leading to a "ransom note" appearance of mixed typefaces. On other platforms, the missing characters are rendered as white rectangles ("tofu", <a href="https://www.google.com/get/noto/">in Google parlance</a>).
- Languages that don't use the latin character set at all are substituted entirely with system fonts. While the system tries to pick the best typeface for the given language, it's generally not a match for the proportions or visual style of Merriweather.

We've been discussing a solution and have decided upon Noto Serif for the following reasons:

- Open source license allows bundling with Calypso and native apps
- Much better character support than Merriweather
- Similar metrics to Merriweather, making for a reasonably simple replacement
- Consistent appearance between all text, regardless of language.

This change is happening simultaneously in our native iOS and Android apps:

- It's been merged into iOS: https://github.com/wordpress-mobile/WordPress-iOS/pull/6692 and will be available in the beta release soon.
- We've opened an issue on Android: https://github.com/wordpress-mobile/WordPress-Android/issues/5205

Here's a before and after using real screenshots from the Reader, not mockups:

before-after

This should be a wholesale replacement of Merriweather for Noto Serif, in every place that serif text currently appears.

### PR DESCRIPTION
**Pull request by drw158**
## This is a redo of #11624

fixes #11614 

**Uses fonts from Google's CDN (Google Fonts)**

After I quick test I found that the Noto fonts we were serving with our CDN are **much** larger than the font files Google generates. 

Fonts that have a lot of subsets need some special font loading.

Some considerations:

- ~Is the google hosted version the best option vs hosting our own?~ **Google CDN appears to be faster**
- ~Is there a bandwidth difference using Noto Serif, because of all the additional glyphs? Does it make a difference?~ **The switch to Noto actually might be faster for some if not most users**
- ~There are some complex font switches that need to happen to get 100% language coverage (I think). Is it best to ship this now, and figure it out it another PR?~ **Yes**
- ~the WP desktop app uses https to load assets, and I don't know if Google Fonts can be loaded over https: https://github.com/Automattic/wp-calypso/pull/12326/files#diff-7a3d2e2c2f14b3738939aef8624eece3L14~ **It should be fine**

Before:
screen shot 2017-02-27 at 4 27 39 pm

After:
screen shot 2017-02-27 at 4 20 24 pm

cc @mattmiklic

### CODE REVIEW

**Comment by drw158** [comment]
Comment from @mattmiklic 

> There are some complex font switches that need to happen to get 100% language coverage (I think). Is it best to ship this now, and figure it out it another PR?

I'd recommend separating that into an issue of its own, since we're currently not doing anything for those languages. Just switching the latin-extended character set to Noto would be an improvement for some users.

I don't know the answers to the first two questions; would be helpful to get a developer to weigh in. But I know that we want the latin-ext, cyrillic, and greek character sets, which are almost definitely going to carry more weight in terms of filesize than Merriweather, which only had latin. How much, and whether we can avoid that by serving specific subsets only to the users who need them, I think a dev can answer for us.

**Comment by blowery** [comment]
> the WP desktop app uses https to load assets, and I don't know if Google Fonts can be loaded over https

I would be surprised if we cannot, but this would affect production calypso (and wpcalypso.wordpress.com, and horizon) as well as the desktop app.

**Comment by marekhrabe** [comment]
I love that with this font I finally don't see replacement characters all over the place for the Czech language ❤️ 

Characters like these`ěščřžýáíéůú` now render correctly. This will make few other countries around us happy too 👍

**Comment by shaunandrews** [comment]
I dig it. Only thing I noticed is that the drafts popover's line-height seems to cut off descendants in two-line excerpts:

screen shot 2017-03-24 at 1 18 57 pm

(Notice the 'y' and 'p' being cut off.)

**Comment by drw158** [comment]
Concerns addressed! Looks like a white border was covering up the descenders.

I think from a code point of view this is ready, but hesitant to launch on a Friday afternoon. I don't know what could go wrong though.

**Comment by Copons** [comment]
Codewise LGTM 🚢

**Comment by roundhill** [comment]
_Hello, Noto!_

**Pull request merged**
