### PR TITLE
Plans comparison: some visual tweaks

### PR DESCRIPTION
**Pull request by chriskmnds**
### Changes proposed in this Pull Request

Partially addresses c/4PHxCS4J-tr 

Visual tweaks and some refactoring.

### Media

**_Vertically align the horizontal line and the "i" icons._**

Screenshot 2022-04-06 at 4 09 53 PM

**_Reduce the line-height by +-10% (64px, from ~72px)_**

Screenshot 2022-04-06 at 4 08 56 PM

**_Remove the space between the "show full comparison" button and the table._**

Looks like this is to be different across mobile & desktop, judging from the P2 comment pdgrnI-tQ-p2#comment-936

Mobile:

Screenshot 2022-04-06 at 4 09 25 PM

Desktop (no change):

Screenshot 2022-04-06 at 4 10 09 PM

### Testing instructions

1. Go to `/start/plans`
2. Confirm the visual changes in the media above.
3. Go to `/plans/[SITE_URL]` with a personal site and ensure the same for 2 above.

#### TODO

- [x] Create respective Landpack PR. 1024-gh-Automattic/landpack
- [ ] Create respective WPCOM diff for Landpack changes. [PHAB] (generated via `yarn deploy`)
- [ ] Create respective WPCOM diff for landing pages. [PHAB]
- [ ] Create respective LOHP diff (regeneration). [PHAB]

Related to #

### CODE REVIEW

**Review by claudiucelfilip — COMMENTED** [review]
I could confirm all tweaks are present except for **Vertically align the horizontal line and the "i" icons** on RTL locales:

**Comment by chriskmnds** [comment]
> I could confirm all tweaks are present except for Vertically align the horizontal line and the "i" icons on RTL locales:

Thanks @claudiucelfilip . It should be addressed now I hope. 

p.s. do we wait for the landpack/wpcom ends to be ready before merging anything Calypso side?
^ (I'm working on those I mean, just not ready)

**Comment by southp** [comment]
> p.s. do we wait for the landpack/wpcom ends to be ready before merging anything Calypso side?

No, I don't think we need to wait for it. I'd prefer iteration than perfection whenever it makes sense :)

**Review by southp — APPROVED** [review]
Confirmed the calypso-side works as expected. Please feel free to ship this individually or to wait for the rest of the WP.com counterparts :)

**Comment by chriskmnds** [comment]
Going to merge this so we can carry on from here for Phase 2 stuff. I guess the same holds for the Landpack parts (1024-gh-Automattic/landpack) and H4 / landing pages (not done yet 🤷 ).

**Pull request merged**
