### PR TITLE
Reader: Fix how we link to the real site in the feed header

### LINKED ISSUE #12509: Reader: Site View: Feeds link to RSS instead of site URL
If the Site View page is for a feed, the link on the main title links to the RSS file.

For Example, click on the main title at the top of the page on these pages:
https://wordpress.com/read/feeds/34127595
https://wordpress.com/read/feeds/5055404

I'm pretty sure these used to link to the correct place (the site's main URL). Is this a regression? 

cc @blowery

### PR DESCRIPTION
**Pull request by blowery**
Use the URL instead of the feed_URL, if present.

Fixes #12509

### CODE REVIEW

**Comment by blowery** [comment]
cc @samouri as this likely will conflict with some of the reduxification PRs.

**Comment by samouri** [comment]
interesting. whats the difference between URL & feed_URL.  Do we ever want to use feed_URL?

**Comment by samouri** [comment]
testing

**Comment by blowery** [comment]
@samouri feed_URL is the key into the subscriptions table. URL is the site URL. They can be different, and often are for externals and jetpack.

**Pull request merged**
