### PR TITLE
Global Sidebar: Fix the icon when collapsed

### PR DESCRIPTION
**Pull request by arthur791004**
Related to https://github.com/Automattic/dotcom-forge/issues/6762

## Proposed Changes

* Fix the icons are misaligned on the collapsed global sidebar

| Before | After |
| - | - |
| image | image |

## Testing Instructions

* Go to /sites
* Select any site to open GSV
* Make sure the icons on the collapsed sidebar look good

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Comment by davemart-in** [comment]
I'm seeing:

CleanShot 2024-04-26 at 09 30 19@2x

**Comment by Addison-Stavlo** [comment]
@davemart-in - I am seeing the items aligned on the live link for this (chrome, firefox, and edge). Any other details that might help repro what you are seeing?

Screenshot 2024-04-26 at 9 47 10 AM

**Comment by davemart-in** [comment]
@Addison-Stavlo I believe we just need to add `align-items: center;` to this style:

CleanShot 2024-04-26 at 09 53 31@2x

Adding that clears up the issue on my end.

**Comment by Addison-Stavlo** [comment]
> align-items: center; to this style:

For me that adds extra space on the right.

BEFORE applying `align-items: center;`

Screenshot 2024-04-26 at 10 13 09 AM

AFTER applying `align-items: center;`

Screenshot 2024-04-26 at 10 13 20 AM

**Comment by Addison-Stavlo** [comment]
I had a screen share with @davemart-in to try to understand what he was seeing.  One of the issues seemed to go away after a hard reload, and [e95b303](https://github.com/Automattic/wp-calypso/pull/89957/commits/e95b30347d62aa5ac38fb9fb09040319c49f0088) should resolve the others.

**Review by davemart-in — APPROVED** [review]
Let's ship these changes. hey look good to me. There is one edge case thing that keeps popping up on my end, but we can watch out for it after this ships.

**Pull request merged**
