### PR TITLE
Add screen-reader-text component

### PR DESCRIPTION
**Pull request by sirreal**
Add `<ScreenReaderText />` component.

There's a tendency to do funny things in JSX to include an element with the class `screen-reader-text`. This component makes the intention explicit and saves class related linter headaches.

To test:
* Visit https://calypso.live/devdocs/design/screen-reader-text?branch=add/component-screenreadertext to see the component in action.
* Verify it renders and behaves as expected.
* Check console for errors and warnings.

Follow up from p1496953957829817-slack-calypso

### CODE REVIEW

**Comment by ryelle** [comment]
Should the CSS for `.screen-reader-text` also be moved here? Or do we continue to consider that a [utility](https://github.com/Automattic/wp-calypso/blob/master/assets/stylesheets/shared/_utilities.scss)?

**Comment by aduth** [comment]
>Should the CSS for `.screen-reader-text` also be moved here?

I think ideally it would, but since it's used so prevalently in a global sense, might make it harder to track down. I'm on the fence.

**Comment by sirreal** [comment]
> Should the CSS for .screen-reader-text also be moved here?

I think it should be moved here. I can't think of any risk of breakage by moving CSS around. That class _shouldn't_ have CSS ordering issues, right? 😅

**Comment by sirreal** [comment]
I've rebased and moved the related styles out of `utilites` and into the component stylesheet in 9fb4dfb. This should be ready to go!

**Pull request merged**
