### PR TITLE
Staging sites: optimize hosting config loading card

### PR DESCRIPTION
**Pull request by sejas**
- Fixes https://github.com/Automattic/dotcom-forge/issues/1943

## Proposed Changes

* Make a first call to fetch the transfer status, which makes the card load faster.
* Avoid showing the transfer progress bar if the transfer is not initiated.

## Testing Instructions

* Create a business site and transfer it to atomic. This is the parent site.
* Go to Settings > Hosting configuration
* Observe the Staging sites card displays the "Create staging site" button.
* Click on it
* Observe the transfer progress bar appears. Wait for a few minutes.
* Observe the staging site info appears and also the button to `Manage staging site`
* Refresh the page
* Observe the staging site info that appears.

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

**Review by danielbachhuber — CHANGES_REQUESTED** [review]
If Redux state is empty, the skeleton screen appears momentarily, and then disappears for a short period before the text finally appears.

I tried capturing it in a video but wasn't able to capture the skeleton screen state:

https://user-images.githubusercontent.com/36432/224753331-7f6d96a1-d1ae-4a2a-8852-21a98b4a4826.mp4

**Comment by sejas** [comment]
@danielbachhuber , I improved the code to show the skeleton until other UI appears 👌

**Review by danielbachhuber — CHANGES_REQUESTED** [review]
The intermediate state seems a little buggy to me now. It shows the skeleton screen briefly and the progress bar goes back occasionally.

https://user-images.githubusercontent.com/36432/224850640-03fd68c5-d766-463f-8ce7-cee39747e3db.mp4

Maybe it would be helpful to write tests around what should be displayed for the various states of data?

**Comment by wojtekn** [comment]
@sejas thanks, it works much smoother for me now. The only thing I noticed is that when I immediately refresh the page after adding the staging site, the progress bar goes to 100% quickly, and then stays in this state until the staging site is added. Do you think we could improve it?

**Comment by sejas** [comment]
@wojtekn, I've improved the progress bar.

**Review by wojtekn — APPROVED** [review]

**Pull request merged**
