### PR TITLE
Checkout: Record Apple Pay status when entering checkout

### PR DESCRIPTION
**Pull request by gziolo**
This PR implements a really great idea shared by @p3ob7o. He suggested to add simple Tracks event fired on the checkout page. It's going allow us to collect information how many users (in %) would be able to use `Apple Pay`. Which in return gives an idea of the priority of the project.

This feature is put behind the feature flag named: `apple-pay`. At the moment enabled only for `development`, `test` and `wpcalypso`. I plan to enable it on `stage`, `horizon` and `production` once we confirm it works proper on other envs. There is no plan to enable it for desktop, because it uses `Chromium` as a browser so there is no chance it would work at the moment.

### Testing requirements
1. **macOS 10.12**. Apple Pay JavaScript is supported in Safari. The user must have an iPhone or Apple Watch that can authorize the payment.
2. **iOS 10**. Apple Pay JavaScript is supported on all iOS devices with a Secure Element. It is supported both in Safari and in SFSafariViewController objects.
3. All pages that include Apple Pay must be served over HTTPS - it's not possible to test in locally, but we can use calypso.live!
4. Apple Pay participating banks: [Canada and the United States](https://support.apple.com/pl-pl/ht204916), [Europe](https://support.apple.com/pl-pl/HT206637) and [Asia-Pacific](https://support.apple.com/pl-pl/ht206638) - we need at least one person that has a credit card added to Apple Pay Wallet :) 

### Test 
1. Open Safari browser.
2. Go to https://calypso.live/?branch=add/record-apple-pay-status.
3. Enabled console debugging: ```localStorage.setItem( 'debug', 'calypso:*' );```
4. Refresh the page.
5. Add any upgrade to the cart.
6. You should see the following entries on the JS console:
screen shot 2016-10-11 at 10 52 58
7. If you have a credit card added to your Apple Pay Wallet, then you should see `canMakePaymentsWithActiveCard` property set to true in the `calypso_apple_pay_status` event.

### CODE REVIEW

**Comment by lsinger** [comment]
I can confirm this works correctly for someone **without** Apple Pay.

**Comment by gziolo** [comment]
Thanks @lsinger for checking :)

**Comment by frosty** [comment]
I've just tested this on both my iPad (running iOS 10) and my Mac (on 10.12). Both are showing `canMakePaymentsWithActiveCard` as `false`, despite me having a credit card added to my account (and I regularly use Apple Pay). Let me know if you need any more info, or to re-test.

**Comment by mattsherman** [comment]
I have tested this on my Mac (10.12). It shows `canMakePaymentsWithActiveCard: false`. I have Apple Pay setup.

**Comment by kwonye** [comment]
@mattsherman @gziolo @frosty can you try again? We've verified the domain.

**Comment by frosty** [comment]
I've just retested on both my MacBook and iPad, and I'm still seeing `false` (even after emptying caches).

**Comment by gziolo** [comment]
It’s a bit complicated, because it probably can work only with the top domain verified in iTunes Connect which is `wordpress.com` at the moment.

**Comment by scruffian** [comment]
The code here looks great 👍

**Comment by gziolo** [comment]
I'm merging this one to do some testing on https://wpcalyspo.wordpress.com.

**Pull request merged**
