### PR TITLE
Experiment: Add tagged mock component testing

### PR DESCRIPTION
**Pull request by sirreal**
This PR adds `makeTaggedMock` to `components`. See [the README](https://github.com/Automattic/wp-calypso/blob/e6c24ca22b469bb8d2c10329999089586a2f0f36/client/components/make-tagged-mock/README.md) for full details.

This component is designed to be used as a mock in snapshot testing. It renders nothing when used outside of a testing environment, but does provide some context which can be valuable when comparing snapshot diffs.

## Testing:
1. Start up tests `npm run test-client:watch`
1. You can apply the patch below to try out snapshot testing:
1. The snapshot tests should fail including the extra `data-mock` attributes.

```diff
diff --git a/client/jetpack-connect/test/plans.js b/client/jetpack-connect/test/plans.js
index 2f9283c5e6..237af949fb 100644
--- a/client/jetpack-connect/test/plans.js
+++ b/client/jetpack-connect/test/plans.js
@@ -14,10 +14,18 @@ import React from 'react';
 import PlansWrapper, { getSitePlans, SELECTED_SITE, SITE_PLAN_PRO } from './lib/plans';
 import { PLAN_JETPACK_BUSINESS } from 'lib/plans/constants';
 
-jest.mock( 'components/data/query-plans', () => require( 'components/empty-component' ) );
-jest.mock( 'components/data/query-site-plans', () => require( 'components/empty-component' ) );
-jest.mock( 'jetpack-connect/happychat-button', () => require( 'components/empty-component' ) );
-jest.mock( 'my-sites/plan-features', () => require( 'components/empty-component' ) );
+jest.mock( 'components/data/query-plans', () =>
+	require( 'components/make-tagged-mock' )( 'components/data/query-plans' )
+);
+jest.mock( 'components/data/query-site-plans', () =>
+	require( 'components/make-tagged-mock' )( 'components/data/query-site-plans' )
+);
+jest.mock( 'jetpack-connect/happychat-button', () =>
+	require( 'components/make-tagged-mock' )( 'jetpack-connect/happychat-button' )
+);
+jest.mock( 'my-sites/plan-features', () =>
+	require( 'components/make-tagged-mock' )( 'my-sites/plan-features' )
+);
 
 describe( 'Plans', () => {
 	test( 'should render with no plan (free)', () => {
```

/cc @seear

### CODE REVIEW

**Comment by seear** [comment]
Very nice. Only downside I can think of if that if we change it in the future, it might change all the snapshots. But it is so simple I don't think that is a big risk.

Maybe just wants a readme then can be merged 👍

**Comment by seear** [comment]
We may not need this. I tried this quick patch on `master`:

```diff
diff --git a/client/jetpack-connect/test/plans.js b/client/jetpack-connect/test/plans.js
index 2f9283c5e6..cae1ad26e5 100644
--- a/client/jetpack-connect/test/plans.js
+++ b/client/jetpack-connect/test/plans.js
@@ -14,7 +14,7 @@ import React from 'react';
 import PlansWrapper, { getSitePlans, SELECTED_SITE, SITE_PLAN_PRO } from './lib/plans';
 import { PLAN_JETPACK_BUSINESS } from 'lib/plans/constants';
 
-jest.mock( 'components/data/query-plans', () => require( 'components/empty-component' ) );
+jest.mock( 'components/data/query-plans', () => 'query-plans' );
 jest.mock( 'components/data/query-site-plans', () => require( 'components/empty-component' ) );
 jest.mock( 'jetpack-connect/happychat-button', () => require( 'components/empty-component' ) );
 jest.mock( 'my-sites/plan-features', () => require( 'components/empty-component' ) );
```

And the result is:

```diff
    - Snapshot
    + Received
    
    @@ -3,11 +3,11 @@
          "attribs": Object {},
          "children": Array [
            Object {
              "attribs": Object {},
              "children": Array [],
    -         "name": "div",
    +         "name": "query-plans",
              "next": null,
              "parent": null,
              "prev": null,
              "root": [Circular],
              "type": "tag",
```

**Comment by sirreal** [comment]
> We may not need this. I tried this quick patch on `master`

That works because `query-plans` is an allowed React tag name. It would actually happily put that directly into the DOM:

```jsx
ReactDOM.render(
  React.createElement('query-plans'),
  document.getElementById('app')
)
```

qp

I believe that's because it's a [valid custom element name](https://w3c.github.io/webcomponents/spec/custom/#valid-custom-element-name), pretty much meaning it starts with a lowercase alpha and includes a `-`.

That's actually not too bad… we could just use some sort of nomenclature to indicate what we're mocking and no need for the added complexity of this component, `require`s, etc. Simplicity and non-existent custom elements FTW!

**Comment by sirreal** [comment]
Interesting, you apparently also get a dump of _whatever_ props were passed to the custom element as attributes:

```diff
                                       Object {
-                                        "attribs": Object {},
+                                        "attribs": Object {
+                                          "baseplanspath": "/jetpack/connect/plans",
+                                          "displayjetpackplans": "true",
+                                          "isinsignup": "true",
+                                          "islandingpage": "false",
+                                          "onupgradeclick": "function (cartItem) {
+                       var checkoutPath = '/checkout/' + _this.props.selectedSite.slug;
+                       // clears whatever we had stored in local cache
+                       _this.props.selectPlanInAdvance(null, _this.props.selectedSiteSlug);
+
+                       if (!cartItem || cartItem.product_slug === _constants.PLAN_JETPACK_FREE) {
+                               return _this.selectFreeJetpackPlan();
+                       }
+
+                       if (cartItem.product_slug === (0, _lodash.get)(_this.props, 'selectedSite.plan.product_slug', null)) {
+                               return _this.redirect(CALYPSO_PLANS_PAGE);
+                       }
+
+                       _this.props.recordTracksEvent('calypso_jpc_plans_submit', {
+                               user: _this.props.userId,
+                               product_slug: cartItem.product_slug });
+
+                       _analytics.mc.bumpStat('calypso_jpc_plan_selection', cartItem.product_slug);
+
+                       (0, _actions2.addItem)(cartItem);
+                       _this.redirecting = true;
+                       _this.props.completeFlow();
+                       _page2.default.redirect(checkoutPath);
+               }",
+                                          "plans": "jetpack_personal,jetpack_premium,jetpack_business",
+                                          "site": "[object Object]",
+                                        },
                                         "children": Array [],
-                                        "name": "div",
+                                        "name": "my-sites--plan-features",
```

**Comment by sirreal** [comment]
Exploring in #19100

**Comment by seear** [comment]
> I'm not sure if the tradeoff is for better or worse

I think dumping the passed props makes sense. A change to the props should always be a conscious decision, so we would be on the lookout for that in the snapshot.

**Pull request closed without merging**
