### PR TITLE
Update drake jetpack illustration

### PR DESCRIPTION
**Pull request by kjellr**
Updating our Jetpack drake illustrations to match the new WordPress.com illustration style.

Issue #13041 

— 

Old illustration: 
jetpack-drake1

New:
jetpack1

### CODE REVIEW

**Comment by kjellr** [comment]
Screenshots & Testing instructions:

---

**Settings > Import:**

Visit Settings, then click into the "Import" section on a jetpack site. Note: Since this usually kicks you out to WP-Admin automatically, you may need to first visit the Import section of a WP.com site, then use the site switcher to choose a Jetpack site instead. 

01-import

---

**Settings > Export:**

Visit Settings, then click into the "Export" section on a jetpack site. Note: Since this usually kicks you out to WP-Admin automatically, you may need to first visit the Export section of a WP.com site, then use the site switcher to choose a Jetpack site instead. 

02-export

---

**Settings > Security:**

On a Jetpack site, visit the "Security" section of the Settings tab. Then use the site switcher to select a WordPress.com site instead. 

03-security

---

**Plugins > Plugins can't be updated...:**

I'm not sure when exactly this message shows up, but I temporarily replaced `L169-173` of `client/my-sites/plugins/main.jsx` with `L188-191`, and visited the Updates tab of a Jetpack site that was all up to date to verify. 

04-plugins

---

**Themes > Not available for multi site:**

Attempt to upload a theme to a Jetpack-connected multi-site installation of WP. Or, temporarily comment out `L311` and `L313-332` in `client/my-sites/themes/theme-upload/index.jsx`. Then visit the Themes tab and click the "Upload theme" button in the top right.

05-themes

---

**Jetpack Manage Error Page README**

I don't think this one actually has a preview since it's just a code example.

---

**Jetpack Referrer Message:**

I'm not sure how to test this one. @foletto or @rickybanister, do you know when this appears?

**Comment by folletto** [comment]
Not sure either about where that appears.

However, I tested the other live instances, and works well. I _think_ this change is safe enough so you can still proceed. 👍

**Comment by rickybanister** [comment]
cc @MichaelArestad 

Looks good to me, but ccing Michael since he's been thinking about these.

**Comment by kjellr** [comment]
Minor note: as per the change in #14371, testing instructions are slightly different. Rather than clicking on the Import/Export tabs, you'll need to select those items from the Site Tools section at the bottom of the page in the General tab. 

Commit eaea2e0 syncs us up with that change. 

screen shot 2017-06-02 at 10 12 29 am

screen shot 2017-06-02 at 10 12 07 am

**Comment by drw158** [comment]
Not a big deal, but I've been removing `title` from the svgs that I touch. Since these are all decorative, it's recommended to not include it.

**Comment by MichaelArestad** [comment]
Beautiful

**Pull request merged**
