### PR TITLE
Remove unused routes and code, styles behind those routes from previous iterations of the Jetpack Checkout

### PR DESCRIPTION
**Pull request by yashwin**
#### Changes proposed in this Pull Request

This PR removes some unused routes and the associated code, styles of those routes from previous iterations of the Jetpack Checkout

These changes remove the unused Jetpack site-less purchase, which was later replaced with the current flow based on user licenses.

#### Testing instructions

- Checkout to `fix/remove-unused-routes` branch and take a pull
- Start Calypso with yarn start.
- Visit https://cloud.jetpack.com/pricing.
- Select any Jetpack product other than Jetpack Search.
- Once you are on the Checkout page, replace https://wordpress.com with http://calypso.localhost:3000 leaving the rest of the URL untouched.
- Check out the product.
- Verify that you land on the activation flow where you can select one of your sites from a dropdown or follow the manual activation flow that ends up with your license key.

also 

- Verify that `jetpack-checkout-siteless-thank-you-completed.tsx` & `jetpack-checkout-siteless-thank-you.tsx` are deleted and the references are removed
- Verify that styles that belong to `jetpack-checkout-siteless-thank-you-completed` and `jetpack-checkout-siteless-thank-you` are removed
- Verify that pages for `/checkout/jetpack/schedule-happiness-appointment`, `/checkout/jetpack/thank-you-completed/no-site/:product` & `/checkout/jetpack/thank-you/no-site/:product` are removed.

Related to 1164141197617539-as-1201624154131998

### CODE REVIEW

**Comment by rcanepa** [comment]
After reviewing the code and testing the different Jetpack purchase flows, I suggest changing this from a draft PR to an official one to test these changes against or test suites.

That being said, everything looked and worked as expected, and I didn't notice any regression.

Finally, I recommend including in the testing instructions these steps:

- Download this PR.
- Start Calypso with `yarn start`.
- Visit `https://cloud.jetpack.com/pricing`.
- Select any Jetpack product other than Jetpack Search.
- Once you are on the Checkout page, replace `https://wordpress.com` with `http://calypso.localhost:3000` leaving the rest of the URL untouched.
- Check out the product.
- Verify that you land on the activation flow where you can select one of your sites from a dropdown or follow the manual activation flow that ends up with your license key.

**Comment by rcanepa** [comment]
For extra content, these changes remove the unused Jetpack site-less purchase, which was later replaced with the current one based on user licenses.

**Review by manzoorwanijk — APPROVED** [review]
Tested and I don't see any regression, thus it looks good to me ✅

**Review by rcanepa — APPROVED** [review]
LGTM.

I tested these changes again and confirmed that everything works as expected.

**Review by sirbrillig — APPROVED** [review]
I haven't tested this but it looks safe to me. 👍  Thank you for the clean-up!

**Pull request merged**
