### PR TITLE
Store: Remove createReducer from ui shipping-zone-methods

### PR DESCRIPTION
**Pull request by sirreal**
#### Changes proposed in this Pull Request

* Removes `createReducer` from a single reducer as part of #36678

#### Testing instructions

I'm unfamiliar with the store and unable to provide manual testing instructions.

### CODE REVIEW

**Review by sgomes — COMMENTED** [review]
From a high-level point of view, this LGTM.

However, be aware that `createReducer` wraps reducers in `withoutPersistence` if they don't have custom persistence (and this one doesn't), which may affect the expected behaviour here. Definitely could use a look by someone more familiar with this bit of state.

**Comment by sirreal** [comment]
I've rebased and reworked this:
- Leave the handlers in place without adding them to a `reducers` object. Each handler becomes a stand-alone function. This simplifies the refactoring given I'm unfamiliar with this area of the application.
- Wrap the reducer in `withoutPersistence`.

Ready for review 🚀

**Review by sgomes — APPROVED** [review]
LGTM, can't find any issues with this type of high-level refactoring 👍 No typos that I could find, either 🙂

**Comment by sirreal** [comment]
I'll need to have a look at the test failures 😕

**Comment by sirreal** [comment]
> I'll need to have a look at the test failures 😕

There were some missing `return` statements in the switch. Fixed now.

**Pull request merged**
