### PR TITLE
Activity Log: Remove credentials footer

### PR DESCRIPTION
**Pull request by MichaelArestad**
Since it was fairly redundant, let's remove the current footer. We should still add one to the credentials form view itself as shown in https://github.com/Automattic/wp-calypso/issues/20116

#### To test
Go to a site that hasn't had credentials entered and make sure the footer is no longer there.

#### Before
image

#### After
image

### CODE REVIEW

**Comment by eliorivero** [comment]
Wouldn't it be possible to add that link and/or an explanation in a popover like the Jetpack Monitor card does below?

In any case, this branch needs rebasing to solve some conflicts.

**Comment by MichaelArestad** [comment]
@eliorivero can you rebase it? I tried and failed

**Comment by eliorivero** [comment]
I've rebased this and solved the conflicts.

**Comment by eliorivero** [comment]
Closing in favor of #21134

**Pull request closed without merging**
