### PR TITLE
Signup: hidden steps that fill signup data

### PR DESCRIPTION
**Pull request by southp**
#### Changes proposed in this Pull Request
This PR attempts to address what @scruffian pointed out in [this comment](https://github.com/Automattic/wp-calypso/pull/29136#issuecomment-449434898) so that we can continue #29136 to make after-signup redirecting cleaner.

In summary, it introduces:

1. The concept of a "hidden" step. A hidden step won't be shown to the user, but will still be processed by `goToNextStep()`, hence the function `getVisibleFlowSteps()`.
1. A new signup step component `AddPlanComponent`, which renders nothing but fill in the signup data store.
1. Update `/personal`, `/premium` and `/business` flow to make use of this new mechanism, so they don't need to go `/plans/select` route anymore.

#### Testing instructions

Go through `/personal`, `/premium` and `/business` flows and see if they all work as expected, especially with / without a domain added.

### CODE REVIEW

**Comment by scruffian** [comment]
Do we need a new step? The way I see it we could just reuse the existing plans and set the dependencies for it.

**Comment by southp** [comment]
@scruffian Would you mind showing me more details? I'm surely all for reusing existing code, but I'm afraid that I'm not quite sure how in this case.

**Comment by scruffian** [comment]
The current plans step looks like this:
```
		plans: {
			stepName: 'plans',
			apiRequestFunction: addPlanToCart,
			dependencies: [ 'siteSlug' ],
			providesDependencies: [ 'cartItem' ],
		},
```

This step provides a `cartItem` to the flow and calls the `apiRequestFunction` when the dependencies are met.

We define flows like this:
```
		personal: {
			steps: [ 'user', 'about', 'themes', 'domains' ],
			destination: function( dependencies ) {
				return '/plans/select/personal/' + dependencies.siteSlug;
			},
			description: 'Create an account and a blog and then add the personal plan to the users cart.',
			dependencies: { // This is new
				cartItem: WPCOM_PERSONAL_PLAN // This obviously wont work!
			}
			lastModified: '2018-11-09',
		},
```

The way I imagine this working is that we could provide dependencies in the flow definition, which would be passed to the flow controller. The step could then be hidden when the dependencies are met. We already do this for dependencies that are set in the query string I believe. Have a look at `providesDependenciesInQuery` and  `submitQueryDependencies` for some ideas on how that works.

Does that help?

**Comment by southp** [comment]
> The step could then be hidden when the dependencies are met. We already do this for dependencies that are set in the query string I believe. Have a look at providesDependenciesInQuery and submitQueryDependencies for some ideas on how that works.

If I'm not overlooking something, they work differently. `submitQueryDependencies()` hides the site topic step and the site type step via [excludeSteps() function](https://github.com/Automattic/wp-calypso/blob/master/client/signup/main.jsx#L312). `providesDependenciesInQuery` is only used in [site-selected flow](https://github.com/Automattic/wp-calypso/blob/master/client/signup/config/flows-pure.js#L301), which doesn't really hide the steps but requires those dependencies to be provided through the query strings and has specialized steps to match the change. In this case, they are `themes-site-selected` and `plans-site-selected`.

Eventually it is the same problem we faced before: how to prefill dependencies and hide the related steps? It might be a good timing to attack it again, so, as you said already, we won't have to work around it again :)

Here are the two major issues from my perspective:

1. We probably couldn't just hide the step with fulfilled dependencies. If we did that, the back navigation wouldn't work since the completed steps would have fulfilled dependencies and disappear. The number of steps would decrease after each step as well, which would be confusing.
1. The `apiRequestFunction` is not called solely based on dependencies. It is called when the [dependencies are met and all the previous steps has been submitted successfully](https://github.com/Automattic/wp-calypso/blob/master/client/lib/signup/flow-controller.js#L228). Thus if we just use [SignupActions.provideDependency()](https://github.com/Automattic/wp-calypso/blob/master/client/lib/signup/actions.js#L86) to fill in dependency store, the apiRequestFunction won't fire even if the dependencies are met.
1. If we use SignupActions.submitSignupStep() to fill in both the progress store and the dependency store before showing the flow to users, there is currently no way to tell if it is filled by users or other ways from the data point of view. Thus I don't know how to hide the steps.

I'm wondering if introduce a new progress state that we could know if it is prefilled somehow or is fulfilled by a user would resolve these problems.

What do you think? Am I overlooking or over-complicating something? I'd love to hear more from you :)

**Comment by southp** [comment]
@scruffian Here is another try using different strategy: https://github.com/Automattic/wp-calypso/pull/30297 . It is so not production level of code, but I'd love to hear you opinion about the general direction. :)

**Comment by southp** [comment]
Removed all reviewers so that this on-hold PR won't clutter anyone's review request queue :)

**Comment by scruffian** [comment]
Thanks @southp. This is still not the way I had imagined it working, sorry :(

Let me try to explain. We already have a plans step which takes care of everything for us in terms of handling the dependencies and API requests. What we need to achieve, I think, is two things:

1. Make sure that the dependency is set before the flow begins
2. Make sure that the plans step doesn't get shown to the user

The simplest way to achieve this seems to me to reuse the plans step we have, but create a new array in the flow to specify "hidden" steps in that flow. This should take care of point 2 above. I think we can take care of point 1 by specifying the dependencies we want to pass at the flow level too, so the flow definition would look like this:

```
		personal: {
			steps: [ 'user', 'about', 'themes', 'domains' ],
			hiddenSteps: ['plans'],
			destination: function( dependencies ) {
				return '/plans/select/personal/' + dependencies.siteSlug;
			},
			description: 'Create an account and a blog and then add the personal plan to the users cart.',
			dependencies: { // This is new
				cartItem: WPCOM_PERSONAL_PLAN // This obviously wont work!
			}
			lastModified: '2018-11-09',
		},

Are there problems with this approach I haven't seen?

**Comment by niranjan-uma-shankar** [comment]
> 1. Make sure that the dependency is set before the flow begins
> 2. Make sure that the plans step doesn't get shown to the user

@scruffian With the method implemented in #30242 to remove fulfilled steps, an alternate approach here could be to to make use of that to achieve points 1 and 2. What's your thought about this? A few points that come to mind:
1. `removeFulfilledSteps()` of #30242  does not fire the `apiRequestFunction` for a removed step. Should we find a way to do that?
    - I think being able to fire the `apiRequestFunction` will come useful when a step is removed due to  dependency getting fulfilled via query (as providesQueryDependencies) or using the dependency prop in flow (as you described in your comment).
    - If we want to fire an `apiRequestFunction` even for removed steps, then we need to modify flow controller, which presently only calls the apiRequestFunction for steps in the flow. We would need to do this work even if we use the `hidden` step approach you outlined in your mock.

I like your hidden step approach and it is a viable solution, but I just wanted to check if it makes sense to use the removeFulfilledStep() method since it almost does the same job as a hidden step but needs a little tweak (in making apiRequestFunction work for removed steps). It also avoids the Back button issue that @southp mentioned. Are there downsides to this approach?

**Comment by niranjan-uma-shankar** [comment]
@scruffian Please check a WIP concept at #30671 . This makes use of the `removeFulfilledSteps` framework to add a personal bundle as a default dependency to the Personal flow. Does this align with how you expected this work?

**Comment by southp** [comment]
Closing this PR to reduce noise

**Pull request closed without merging**
