### PR TITLE
Jetpack Cloud: update pricing and tier information UI

### PR DESCRIPTION
**Pull request by rcanepa**
#### Changes proposed in this Pull Request

- Update pricing and tier information UI according to what was proposed by @keoshi .

#### Testing instructions

- Navigate to http://calypso.localhost:3000
- Go to the Plan -> Plans
- You should see the new buttons in Jetpack Backup/Search/Scan products.

See 1151678672052943-as-1168017254149561.

##### Desktop
image

##### Mobile
image

### CODE REVIEW

**Comment by enejb** [comment]
I tested this and on the latest FF I end up with this view after I select a radio button .
Screen Shot 2020-03-31 at 11 46 05 AM

Also as far as I understand the mobile view should look the same as the desktop view. 
@keoshi can you clarify that?

**Comment by keoshi** [comment]
I've pushed some changes to this PR — feel free to discard them in case they're not solid.

Here's a quick rundown of the tweaks applied:

- Import `Fragment` to wrap the markup on `options.jsx`.
- Move label (`product-card__options-label`) outside the products wrapper div.
- Tweaked the size of the selections and refined flex properties accordingly.
- Changes `is-selected` colors to match the feature highlight on the plans tables (`?feature=search&plan=jetpack_business`).
- Clean up media queries on the various elements.

Looks like this now:

#### Desktop

image

#### Tablet

image

#### Mobile

image


---

One other thing I noticed is that these styles are bleeding into the single product cards, and making currencies green:

https://github.com/Automattic/wp-calypso/blob/ef4e5e9f2e2232d372335ecb6996fe66d992e277/client/my-sites/plan-price/style.scss#L57-L59

**Comment by rcanepa** [comment]
@keoshi , it looks much better now! I have one question. I noticed that on mobile, the color of the price is green. On desktop, only the currency symbol is green, is that intentional?
**Mobile**
image
**Desktop**
image

**Comment by rcanepa** [comment]
> I tested this and on the latest FF I end up with this view after I select a radio button .
Pushed a small fix that solves this issue ^

**Comment by keoshi** [comment]
> the color of the price is green. On desktop, only the currency symbol is green, is that intentional?

Not at all, as [mentioned above](https://github.com/Automattic/wp-calypso/pull/40583#issuecomment-606584219) the currency styling for the plans seems to be bleeding into this section. The green color comes from this property:

https://github.com/Automattic/wp-calypso/blob/ef4e5e9f2e2232d372335ecb6996fe66d992e277/client/my-sites/plan-price/style.scss#L57-L59

Do you prefer to take care of that or should I @rcanepa ?

Thank you!

**Comment by rcanepa** [comment]
> Not at all, as mentioned above the currency styling for the plans seems to be bleeding into this section. The green color comes from this property:

I didn't understand it before and now I get it. I'll take care of it @keoshi !

Thank you!

**Comment by rcanepa** [comment]
@keoshi , I fixed the issue with the green color bleeding from another stylesheet. Let me know if this looks closer to what we are striving for.

**Mobile**
image
**Desktop**
image

**Comment by keoshi** [comment]
That looks great, @rcanepa! Can we do anything about the extra spacing between the price and three periodicity? Anyway, nitpicking at this point. Let’s get this in!

**Comment by rcanepa** [comment]
@keoshi , I decreased the space between the price and the periodicity by half. Let me know what you think!

image
image

**Pull request merged**
