### PR TITLE
Add emails and tab switching functionality in domain revamp screen

### PR DESCRIPTION
**Pull request by Imran92**
Related to https://github.com/Automattic/wp-calypso/issues/96554

## Proposed Changes

- Added tab-switching functionality between Domains and Emails
- Added functionality to the "Close" and "Manage Site" buttons on top
- Show dynamic Domain info in the topbar
- Fixes the issue of un-attached domain not opening the layout and re-routing to the list page
- Show the as-it-is email management view (without changes)

Tests and especially E2E tests will be added in separate PRs under different cards. Switching domains will open the overview tab by default, but we'll have a separate card to open the current tab.

## Why are these changes being made?

* To revamp the domains management

## Testing Instructions

* Go to wordpress.com/domains/manage
* Browse around, check inner functionalities, make sure you see no issues in how the table looks and works
* Open a site's wp-admin area, go to Upgrades -> Emails, browse around and make sure everything works as before
* Also click on a few domains to make sure everything is working as before.
* Now enable the feature flag by entering `window.sessionStorage.setItem('flags', 'calypso/all-domain-management')` in the browser console. Reload the page
* Now click on different domains. They should open in the new layout now.
* Check the new layout has Overview and Email tabs.
* Try switching to the Email tabs and make sure it works and it's showing the contents. Make sure you can switch back to the Overview tab too
* Try clicking on the "Close" and "My Home" button on top and make sure they work as expected

https://github.com/user-attachments/assets/82bd1ca3-0855-4f85-8055-2d4720dc52d5

## Pre-merge Checklist

- [x] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [x] Have you checked for TypeScript, React or other console errors?
- [x] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
    - [ ] For UI changes, have we tested the change in various languages (for example, ES, PT, FR, or DE)? The length of text and words vary significantly between languages. 
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Review by merkushin — APPROVED** [review]
Looks good!

I noticed two issues, but I think they shouldn't be addressed here anyway:
1. I see a horizontal scrollbar in the tab area (sent screenshots in Slack).
2. The title and copy stick to the content in the Email tab (screenshot attached).
CleanShot 2024-12-04 at 07 36 06@2x

This is how it looks in the old UI:
CleanShot 2024-12-04 at 07 47 19@2x

**Comment by Imran92** [comment]
> I see a horizontal scrollbar in the tab area (sent screenshots in Slack).

As we discussed, this can be due to a different setting on your device. But we'll create a issue for it to look into it separately.

> The title and copy stick to the content in the Email tab (screenshot attached).

Yes I've put the Email section there only as placeholder, it'll be properly shown as per design under https://github.com/Automattic/wp-calypso/issues/96819 and other Email tickets

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/17067178

Some locales (Hebrew, Japanese) have been temporarily machine-translated due to translator availability. All other translations are usually ready within a few days. Untranslated and machine-translated strings will be sent for translation next Monday and are expected to be completed by the following Friday.

Hi @Imran92, could you please edit the description of this PR and add a screenshot for our translators? Ideally it'd include this string: `Manage site`

Thank you in advance!

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/17067178).

**Pull request merged**
