### PR TITLE
Data Stores: Persist selectedStyleVariation & selectedGlobalStyles

### PR DESCRIPTION
**Pull request by arthur791004**
Related to https://github.com/Automattic/wp-calypso/issues/97550

## Proposed Changes

* We have to persist `selectedStyleVariation` and `selectedGlobalStyles` and then we can get the value after the checkout

## Why are these changes being made?

*

## Testing Instructions

* Go to /setup/onboarding
* Select goals
* Select any design with a style variation or either colors & fonts
* Continue to finish the flow
* Make sure the selected styles are applied to your site correctly

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
    - [ ] For UI changes, have we tested the change in various languages (for example, ES, PT, FR, or DE)? The length of text and words vary significantly between languages. 
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Review by zaguiini — APPROVED** [review]
Works well 🚀

**Review by p-jackson — CHANGES_REQUESTED** [review]
I got a 500 error during `site-setup` when trying to apply the "LeanCV" theme with "Sapphire" variation. Let me dig into that before merging.

**Comment by p-jackson** [comment]
The error happens while making a request to `https://public-api.wordpress.com/rest/v1.1/sites/philipmjackson05.wordpress.com/themes/mine?_locale=user`

`500` is an odd error code to return. The text of the error message says:

```
{
    "code": "theme_php_incompatible",
    "message": "<strong>Error:<\/strong> Current PHP version does not meet minimum requirements for LeanCV.",
    "data": {
        "status": 500
    },
    "additional_errors": []
}
```

Do we have a problem with the LeanCV theme? I'd better check production.

**Comment by vykes-mac** [comment]
It worked as expected for me, style variation was applied to my site

**Review by p-jackson — APPROVED** [review]
The error happens in production too! Not good! But unrelated to this PR. Which works well.

**Pull request merged**
