### PR TITLE
Fix choosing a domain mapping on signup

### LINKED ISSUE #11937: NUX: Unable to create new site with mapped domain
I am trying to create a new site with a mapped domain but I end up in a loop:

screen shot 2017-03-09 at 12 30 18

screen shot 2017-03-09 at 11 05 25

I enter my domain and get to the plans page.

screen shot 2017-03-09 at 11 05 36

(This shouldn't offer me free. If I pick Free I get thrown back to Step 1!)

I select "Upgrade" on the Personal plan and it takes me back to Step 3:

screen shot 2017-03-09 at 11 05 40

This is for a new user with no site (which I was able to create because I got caught in the signup loop in NUX: throws me back to step 3 like above after creating new user data).

Possibly related to #11900.

### PR DESCRIPTION
**Pull request by Tug**
Fixes #11937 

This fixes the domain mapping step on signup

### Testing Instructions
- Load this branch locally (or use the calypso.live link in matticbot comment)
- (either logged or logged out) Go to `/start/website` and at the domain step choose "Already own a domain". Enter a domain name and verify that you can finish the flow
- On an existing site, go to `http://calypso.localhost:3000/domains/add/:site_slug` and assert that the "Already own a domain" link works. Enter an existing domain name and assert that the "Map it" link works

### Reviews
- [x] Code
- [x] Product

### CODE REVIEW

**Comment by klimeryk** [comment]
I think a simple
```
diff --git a/client/signup/steps/domains/index.jsx b/client/signup/steps/domains/index.jsx
index dc9d925..053b791 100644
--- a/client/signup/steps/domains/index.jsx
+++ b/client/signup/steps/domains/index.jsx
@@ -146,7 +146,7 @@ const DomainsStep = React.createClass( {
        },

        handleAddMapping: function( sectionName, domain, state ) {
-               const domainItem = cartItems.domainMapping( { domain: domain.domain_name } );
+               const domainItem = cartItems.domainMapping( { domain } );
                const isPurchasingItem = true;

                mapDomainAnalytics.recordEvent( 'addDomainButtonClick', domain.domain_name, 'signup' );
```
should suffice here :) I'd rather pass a raw string, instead of packaging it up in an object.

**Comment by Tug** [comment]
Just tested it (and updated usage of `domain.domain_name` in the same function) but it breaks the "Map it" link in the signup flow. Investigating

**Comment by klimeryk** [comment]
I've pushed my changes to a different branch: https://github.com/Automattic/wp-calypso/tree/fix/map-it-signup so that it's better to see the change.
I've tested them with all the cases I could come up with and seems to work fine.

**Comment by klimeryk** [comment]
LGTM! Thanks for working with me on this, @Tug 🙇

**Pull request merged**
