### PR TITLE
Add/domains for all sites page

### PR DESCRIPTION
**Pull request by hambai**
#### Changes proposed in this Pull Request

* Introduce a new path `/domains/manage` where you can see and manage all your domains in one place

#### Testing instructions

* In My Sites click on "Switch site" in the sidebar navigation and then on "All Sites". Then click on Manage -> Domains - you should see all your domains across all the sites that you can manage. Reload the page, check that all the links work

### CODE REVIEW

**Comment by fditrapani** [comment]
Thanks for putting this together @hambai! This is a really good start. At this point do you want any design feedback or are you looking at just putting the plumbing into place?

**Comment by hambai** [comment]
> Once you click on a domain, clicking the back button on Calypso doesn’t send you back to the `/domains/manage` page, but to `/domains/manage/eltgo.wordpress.com` (the domain management page for the site the domain belongs to)

Well - the only solution to fix that is to make a copy of all domain management paths without the site part, and I decided to hold on that part for now since it's much bigger change. My main idea was to merge this since it's hidden behind feature flag and work on the rest of the stuff gradually - otherwise it'll quickly become too big to manage

**Comment by eltongo** [comment]
> My main idea was to merge this since it's hidden behind feature flag and work on the rest of the stuff gradually - otherwise it'll quickly become too big to manage

Fair enough. I approved the changes :)

**Comment by fditrapani** [comment]
> My main idea was to merge this since it's hidden behind feature flag and work on the rest of the stuff gradually - otherwise it'll quickly become too big to manage

Good idea. I also noticed the back button issue.

**Pull request merged**
