### PR TITLE
Plans: Position CRM Free card alongside Jetpack Free

### PR DESCRIPTION
**Pull request by mattgawarecki**
Relates to #56103.

#### Changes proposed in this Pull Request

* On the pricing page:
  * move the Jetpack CRM Free card out of the main product grid, and down onto the same row as Jetpack Free; and
  * update the gap between cards to a uniform 16px all the way around.
* On the Jetpack CRM Free card:
  * update the title from "CRM Free" to "Jetpack CRM Free";
  * update the description (see reference capture);
  * update the call-to-action button from "Get CRM" to "Start for free"; and
  * update the features list (see reference capture).
* On the Jetpack Free card:
  * update the description (see reference capture); and
  * update the features list (see reference capture).
* Add a `min-height` for free product descriptions: at least 2 lines of text, accounting for a line height of 1.5.

#### Testing instructions

**NOTE:** This PR should be tested in both Calypso Blue and Calypso Green.

1. Navigate to the Plans/Pricing page in your testing environment.
2. Verify the following:
  a. Jetpack CRM Free appears at the bottom of the pricing grid;
  b. on Calypso Green: Jetpack CRM Free shares a row with Jetpack Free, each taking up 50% of the page width;
  c. on Calypso Blue: Jetpack CRM Free takes up the full page width;
  d. Jetpack CRM Free has an updated title, description, call-to-action button, and features list compared to production;
  e. Jetpack Free has an updated description and features list compared to production; and
  f. as the screen width changes, cards stretch and squeeze responsively and intuitively.

#### Reference capture

https://user-images.githubusercontent.com/670067/136219488-828bfb4d-1ecf-4daa-b002-c067c6af8cc9.mp4

### CODE REVIEW

**Review by eeeeevon13 — APPROVED** [review]
Looks good

**Review by monsieur-z — CHANGES_REQUESTED** [review]
Looks tip-top in cloud. The Jetpack CRM Free card doesn't take the full width on desktop in Calypso blue, though. Code looks good to me.
Screen Shot 2021-10-06 at 1 54 11 PM

**Comment by monsieur-z** [comment]
I noticed that there was a small viewport range in which the two free cards don't align, in cloud. This might be obvious at more viewport widths in other locales.

Screen Shot 2021-10-06 at 1 46 35 PM

**Comment by mattgawarecki** [comment]
@monsieur-z Thanks for the valuable feedback and for lending your eagle eye 🐦 👁️ 

> The Jetpack CRM Free card doesn't take the full width on desktop in Calypso blue, though.

Fixed in d834dbc 👍 

> I noticed that there was a small viewport range in which the two free cards don't align, in cloud. This might be obvious at more viewport widths in other locales.

I agree, and I'm all for fixing it -- I'm just not sure how to do it right now in a way that's not super fragile. Is this a problem we've solved elsewhere?

**Comment by monsieur-z** [comment]
> I agree, and I'm all for fixing it -- I'm just not sure how to do it right now in a way that's not super fragile. Is this a problem we've solved elsewhere?

In the above grid, I believe.

Regarding the "free products" grid, which uses flex box, removing the `height: 100%` rule (or rather, overwriting it with `height: auto`) from the 2 flex items seems to do the trick. But that's actually quite counterintuitive. Maybe a cleaner solution would be to use CSS grids as well? Anyway, feel free to deploy this as is.

**Review by monsieur-z — APPROVED** [review]
LGTM! :shipit:

**Pull request merged**
