### PR TITLE
A4A > Marketplace: Add VIP content for the new hosting page

### PR DESCRIPTION
**Pull request by yashwin**
Closes https://github.com/Automattic/jetpack-genesis/issues/453
Closes https://github.com/Automattic/jetpack-genesis/issues/454

## Proposed Changes

This PR:

- Adds VIP hosting capabilities 
- Adds VIP hosting testimonials 

## Why are these changes being made?

* For the new hosting page

## Testing Instructions

* Open the A4A live link
* Go to Marketplace > Hosting > Click the Enterprise tab > Verify the UI looks as shown below:

screencapture-agencies-localhost-3000-marketplace-hosting-2024-07-26-11_59_00

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Comment by jkguidaven** [comment]
Can we fix the cards so they properly align? We could probably just align the content of the card with flex space-between, so the profile details are always anchored at the bottom. wdyt?

Screenshot 2024-07-26 at 2 54 03 PM


Other than that, I think everything looks good! 👍

**Comment by yashwin** [comment]
> Can we fix the cards so they properly align? We could probably just align the content of the card with flex space-between, so the profile details are always anchored at the bottom. wdyt?

Thanks for the review, @jkguidaven! Fixed it now: https://github.com/Automattic/wp-calypso/pull/93000/commits/368c78f113b8af04cfa6be99328955f2eeb3d9a1

**Review by jkguidaven — APPROVED** [review]
Thanks for addressing my comment. Looks good now 💯

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/16428286

Some locales (Hebrew, Japanese) have been temporarily machine-translated due to translator availability. All other translations are usually ready within a few days. Untranslated and machine-translated strings will be sent for translation next Monday and are expected to be completed by the following Friday.

Thank you @yashwin for including a screenshot in the description! This is really helpful for our translators.

**Pull request merged**
