### PR TITLE
Reader: Use three-line clamped excerpts

### PR DESCRIPTION
**Pull request by blowery**
Use the three-line clamped excerpts like the old post-excerpt component. This will have an ellipsis when cut off on webkit / blink browsers, and just truncate on everything else.

### CODE REVIEW

**Comment by blowery** [comment]
### before
following_ _reader_ _wordpress_com

### after
_1__following_ _reader_ _wordpress_com

**Comment by fraying** [comment]
I'm seeing the ellipsis appear in the middle of words, like:

screen shot 2016-11-11 at 12 57 43 pm

That last word is "of" but it's truncating as "o..."

I don't remember this being the case before. Thoughts, @blowery?

**Comment by blowery** [comment]
That's just how the browser does it.

**Comment by blowery** [comment]
We can use the fade instead, but it'll still start the fade mid-word.

**Comment by fraying** [comment]
Okay. If we can't limit the ellipses to where spaces appear, let's go back to the fade (doesn't matter where it appears, grammatically).

**Comment by blowery** [comment]
_1__following_ _reader_ _wordpress_com

**Comment by blowery** [comment]
how far do we want the fade to extend into the content? right now it's 5 times the line height.

**Comment by fraying** [comment]
Looks good to me. @jancavan?

**Comment by jancavan** [comment]
Looks good :shipit:

**Pull request merged**
