### PR TITLE
Themes Selectors: Use theme ID instead of object as arg

### PR DESCRIPTION
**Pull request by ockham**
Bit of New Year's Housekeeping. Needed a bit of a change after staring at  #11326 for too long.

Apart from changing `getTheme...Url()` selectors to accept `themeId` (instead of a `theme` object) as an arg, this PR also changes the implementation of `getThemeCustomizeUrl()` a bit to fix failing lookups for Jetpack sites (see https://github.com/Automattic/wp-calypso/pull/10434#issuecomment-284489457).

Passing around only `themeId`s has some advantages:
* It's more symmetric wrt `siteId`s (which we're already using in selectors, instead of `site` objects)
* It's more symmetric wrt actions (where we're already passing around `themeId`s)
* It will allow us to replace the remaining uses of the `getDetailsIUrl` helper from `my-sites/themes/helpers` easily with the corresponding selector, and drop the former.
* It paves the road for the `Theme` component to become an actual block (for some definition of block 😄 ) -- i.e. if we want, we can only pass the `themeId` to it, and it will fetch everything else on its own.

To test:
* The entire showcase. This touches all `getTheme...Url` selectors and then some, so we need to test extensively.
* Don't forget to test the signup flow! It has a theme selection step that uses the `ThemesList` component, which this PR changes!
* http://calypso.localhost:3000/devdocs/blocks/theme (try clicking on the screenshot and the '...' menu items, watch browser console)
* http://calypso.localhost:3000/devdocs/blocks/themes-list (same)

### CODE REVIEW

**Comment by budzanowski** [comment]
Rough list of things to check:
- [ ] Theme on screenshotClick
- [ ] ThemeMoreButton popoverAction(s) for pure actions
- [ ] ThemeMoreButton popoverAction(s) for actions that use url
- [ ] CurrentTheme bar
- [ ] ThemesSiteSelectorModal
- [ ] ThemesThanksModal
- [ ] ThemeSheet actions
- [ ] LivePreview actions

Please expand if there is more.

**Comment by budzanowski** [comment]
Purchase action in all-sites:
```
`Uncaught TypeError: Cannot read property 'ID' of undefined
    at Object._react2.default.createElement._react2.default.createElement.getMainUrl (themes-site-selector-modal.jsx:144)`
```

**Comment by budzanowski** [comment]
Activate action on Theme Sheet in all-sites:
```
Uncaught TypeError: Cannot read property 'name' of undefined
    at Object.render (index.jsx:158)
```
In file. client/components/theme/index.jsx

**Comment by budzanowski** [comment]
Checked on Jetpack site:
- Customize on active theme when accessed through CurrentTheme bar works.
- When going through CurrentTheme `Info` -> ThemeShee -> customize I see:
```The theme directory "[object Object]-wpcom" does not exist.``` - I see that on screen.
- When clicking on active theme screenshot in `design` ( on hover Customize shows ) it leads to ThemeSheet and not Customize

**Comment by budzanowski** [comment]
I don't know if this is from this PR but I get a lot of 
```
Do not pass complex objects as arguments for a memoized selector
```
warnings in console while testing this PR.

**Comment by ockham** [comment]
> Activate action on Theme Sheet in all-sites:
> ```
> Uncaught TypeError: Cannot read property 'name' of undefined
>    at Object.render (index.jsx:158)
> ```
> In file. client/components/theme/index.jsx

Can't repro. You did pull the latest changes from this branch, did you? 😉

**Comment by ockham** [comment]
(Can't repro the purchase bug either...)

**Comment by ockham** [comment]
> I don't know if this is from this PR but I get a lot of 
> ```
> Do not pass complex objects as arguments for a memoized selector
> ```
> warnings in console while testing this PR.

I'm seeing those too, but I don't think that's related to this PR. I'll check `master`, to be sure.

**Comment by seear** [comment]
We can now drop this [whole lookup and error check part](https://github.com/Automattic/wp-calypso/blob/85b0a23af4b1b9d8deb984b4952ddef4ed118a79/client/state/themes/actions.js#L547L554)

**Comment by seear** [comment]
> We can now drop this whole lookup and error check part

#11796 was a fix for the problem of lookups failing on Jetpack sites now that we properly filter wpcom theme. I'll close it in favour of this one.

**Comment by ockham** [comment]
> We can now drop this [whole lookup and error check part](https://github.com/Automattic/wp-calypso/blob/85b0a23af4b1b9d8deb984b4952ddef4ed118a79/client/state/themes/actions.js#L547L554)

Okay, that'll leave us only with `page( getThemeCustomizeUrl( ... ) )`. Sounds like I'm going to inline that 😄

**Comment by ockham** [comment]
> We can now drop this [whole lookup and error check part](https://github.com/Automattic/wp-calypso/blob/85b0a23af4b1b9d8deb984b4952ddef4ed118a79/client/state/themes/actions.js#L547L554) 

Just gave this a try, and it looks like it would inflate this PR quite considerably (mostly since a couple of dependent unit tests would need to be redone). Opting to do it in a separate PR.

**Comment by ockham** [comment]
>> I don't know if this is from this PR but I get a lot of 
>> ```
>> Do not pass complex objects as arguments for a memoized selector
>> ```
>> warnings in console while testing this PR.

> I'm seeing those too, but I don't think that's related to this PR. I'll check `master`, to be sure.

I was wrong about those. We were actually seeing them since in some instances, I was erroneously passing a theme object as `themeId` to `getTheme` (which is a memoized selector 😄 ).

**Comment by ockham** [comment]
@budzanowski Thanks for testing! You were right about every single error 😅 
I think I've fixed them all now.

There's one caveat: The purchase flow (starting at a multi-site theme sheet) is still broken. It's no longer the issue you reported, which I fixed. But now, it doesn't redirect you to checkout but instead just to the single-site theme sheet without the sidebar (looks pretty broken). However, AFAICS, that issue pre-exists on `master` (but fortunately not in production).

**Comment by seear** [comment]
Tested and working on AT site:
* customize active theme from current theme bar
* activate both uploaded and wpcom themes
* try&customize both uploaded and wpcom themes
* activate both uploaded and wpcom from details sheet

**Comment by seear** [comment]
Failing (on any site):
* Opening live demo from theme sheet

console:
screen shot 2017-03-07 at 13 34 18

**Comment by ockham** [comment]
> Failing (on any site):
> * Opening live demo from theme sheet

Great catch, should be fixed by 9f17745 (I also checked preview from themes list, and everything in both single- and multi-site mode).

**Comment by seear** [comment]
Wow, nice fixin'.

Verified live demo plus try&customize and activation from theme sheets on AT.

Also tested theme delete on AT.

**Comment by seear** [comment]
Verified theme uploads working fine.

**Comment by seear** [comment]
Tested signup with premium theme purchase. Worked fine.

Saw this but it is not related to the PR:
screen shot 2017-03-07 at 14 56 10

**Comment by folletto** [comment]
Checked on Chrome:

1. All Sites → List / Scroll — ✅ 
2. All Sites → Search string — ✅ 
3. All Sites → Free / Premium toggle — ✅ 
4. All Sites → ••• → Live Demo — ✅ 
5. All Sites → ••• → Activate — ✅ 
6. All Sites → ••• → Try & Customize — ✅ 
7. All Sites → ••• → Info / Support — ✅ 
8. Single Site → List / Scroll — ✅ 
9. Single Site → Search string — ✅ 
10. Single Site → Free / Premium toggle — ✅ 
11. Single Site → ••• → Live Demo — ✅ 
12. Single Site → ••• → Activate — ✅ 
13. Single Site → ••• → Try & Customize — ✅ 
14. Single Site → ••• → Info / Support — ✅ 
15. Direct → Sheet → Pick (Free) — ✅ 
16. Direct → Sheet → Pick (Premium) — ✅ 
17. Single Site → Sheet → Pick (Free) — ✅ 
18. Single Site → Sheet → Pick (Premium) — ✅ 
19. Registration Funnel → Theme showcase → theme list — ✅ 
20. Registration Funnel → Homepage → theme list — ✅ 

Phew! :D 

Let's gooooooo! 🚀

**Comment by ockham** [comment]
Woohoo! Thanks for testing, all!

**Comment by ockham** [comment]
Reverted by #11846.

**Pull request merged**
