### PR TITLE
Bluehost Plans: Remove dummy plan definitions from Calypso

### PR DESCRIPTION
**Pull request by jeyip**
Related to p7fD6U-f9O-p2#comment-28410 and https://github.com/Automattic/wp-calypso/pull/87545 

## Proposed Changes

* Removes dummy bluehost plan definitions

## Why are these changes being made?

* Although Bluehost plans were originally meant only for landing pages, we added definitions for Bluehost plans to Calypso to prevent plans grid errors ( because they share the same endpoint /plans ).
* Now that the bluehost plans have been removed from the landing page pricing grids, we may be able to remove any references to it in our codebase

## Testing Instructions

* Smoke test the plans grid PCYsg-RDT-p2

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Review by niranjan-uma-shankar — APPROVED** [review]
LGTM. Feel free to ship once the tests pass. Thank you for the code cleanup!

**Comment by southp** [comment]
@jeyip Is there anything preventing this from shipping? It looks like a great clean-up and 🌎 will thank you :)

**Comment by jeyip** [comment]
Hi @niranjan-uma-shankar nothing is stopping this PR from shipping. It fell off my radar in a flurry of incoming shaping discussions, but I'll leave a note to myself to smoke test and deploy the code by the end of this week ( probably earlier ) 🙂

**Review by jeyip — COMMENTED** [review]
Merging this shortly. I noticed that there's still one instance of the `'bluehost-cloud-bundle-monthly'` slug being fed from [the plans endpoint](https://github.com/Automattic/wp-calypso/blob/trunk/packages/data-stores/src/plans/queries/use-plans.ts#L30-L37).

I'll take a closer look at that soon as well for removal.

**Comment by jeyip** [comment]
I'm seeing what look liked related test failures for the importer flow. Taking a closer look https://teamcity.a8c.com/buildConfiguration/calypso_calypso_WebApp_Calypso_E2E_Playwright_desktop/13600873?expandBuildDeploymentsSection=false&hideTestsFromDependencies=false&expandBuildTestsSection=true&hideProblemsFromDependencies=false

**Comment by jeyip** [comment]
It looks like _all_ of the bluehost plans are still fed from the plans endpoint and that there's an exception when we remove the definitions from the plans list 🤔

**Comment by southp** [comment]
Good catch. @jeyip . Since the Bluehost plan instance itself was removed in D155816-code already, I don't think there is any dangling usage for it. Let's go with option #1 unless there is any critical concern raised :)

**Comment by niranjan-uma-shankar** [comment]
I had a long pending cleanup patch which I just deployed: D157629-code. The Bluehost plan should now no longer appear in the /plans endpoints.

**Comment by jeyip** [comment]
Wonderful thanks @niranjan-uma-shankar! I'll smoke test this PR again, but I believe with your phab diff the e2e test failures should resolve

**Comment by jeyip** [comment]
E2E specs now pass and I'll be merging this PR momentarily

**Pull request merged**
