### PR TITLE
Magic links: First pass at adding magic link button to get-apps.

### PR DESCRIPTION
**Pull request by aerych**
#### Changes proposed in this Pull Request

Adds a button to me/get-apps allowing a user to request a magic link to log in to one of the mobile apps.  The email sent includes a link that will detect the user's mobile platform and redirect them to the appropriate app store.  See the thread at p9OQAC-cl-p2 for more information. 

Requires changes in D30681-code

#### Testing instructions

- Apply the patch. 
- Tap the button. Confirm you receive the magic link email. 
- Resize the screen.  Confirm that the UI resizes as expected. 
- Confirm that the new analytic is logged. 

calypso-magic-link-demo

### CODE REVIEW

**Comment by aerych** [comment]
@rachelmcr @SylvesterWilmott, what do y'all think of the above?  

Rachel I know we briefly talked about just showing the magic link option.  I'd be game to try but I'd like to see a design pass on that approach first.   @SylvesterWilmott what do you think?   In the mean time we could roll with the design we already have.  

@jkmassel could I trouble you for a peek at this one as well?

**Comment by SylvesterWilmott** [comment]
>I'd be game to try but I'd like to see a design pass on that approach first. @SylvesterWilmott what do you think? In the mean time we could roll with the design we already have.

Absolutely. I'll work on a magic link version.

**Comment by rachelmcr** [comment]
I think this is great to start. It worked well for me to install and log in to the app on both Android and iOS devices, and the correct analytic was logged each time I tried it.

> Rachel I know we briefly talked about just showing the magic link option. I'd be game to try but I'd like to see a design pass on that approach first.

Makes sense to me to launch this as is for now. As I think about it more, along with a design pass it seems worth A/B testing or at least carefully considering the analytics to see if a single option works better than multiple options here.

**Comment by aerych** [comment]
Thanks @jkmassel !!

**Pull request merged**
