### PR TITLE
Revert "Skip "Sign up for free subdomain site" test"

### PR DESCRIPTION
**Pull request by spen**
DO NOT MERGE until #33564 is landed.

After that, we should be able to safely start running the test again.

Reverts Automattic/wp-calypso#33517

### CODE REVIEW

**Review by ramonjd — APPROVED** [review]
LGTM (once #33564 is merged)

Also, I added the e2e tests label just as a reminder to re-trigger the e2e tests once this PR is rebased 👍

**Comment by adamziel** [comment]
Moving to Blocked. @spen - is this something you're still looking forward to merge?

**Comment by spen** [comment]
I've triggered the failing tests again and both are still failing. I don't think this ones ready to go yet without addressing the test failures.

**Comment by Stojdza** [comment]
@spen Do you need any help about this one?

**Comment by spen** [comment]
Hi @Stojdza - I might do thanks! 
I've rebased and pushed to see how the e2e test runs - once that's finished I'll gauge what's needed to reinstate it :)

**Comment by Stojdza** [comment]
@spen I've added [missing step ](https://github.com/Automattic/wp-calypso/pull/33570/commits/feee7fcc8684b2d4191ec192780e4e05de9e9a50) to `Sign up for free subdomain site @parallel` test. We probably missed updating test with this step because test was disabled. Plus, I merged the latest changes from master branch and it's all green now. Feel free to merge this anytime :)

**Review by Stojdza — APPROVED** [review]

**Comment by spen** [comment]
Heaps of thanks for grabbing the reins on this one @Stojdza 👌

**Pull request merged**
