### PR TITLE
A4A: Fixing pagination on the sites dashboard

### PR DESCRIPTION
**Pull request by coder-karen**
Related to https://github.com/Automattic/automattic-for-agencies-dev/issues/201

## Proposed Changes

* This PR adds styling to ensure pagination displays on the sites dashboard on different screen sizes and with the preview pane, fixed at the bottom of the dashboard.
* This PR also fixes a scroll issue on screen sizes between 961 to 1400px where it wasn't possible to scroll down a list of sites in the main sites dashboard view.

Figma designs: 1UpoqS1KkCtLXVX68TbMSM-fi-6144_70981

## Testing Instructions

For the below testing steps, make sure to run `yarn start-a8c-for-agencies` locally and then visit `http://agencies.localhost:3000/sites`.

* To test pagination, use the 'View options' icon and select a rows per page option that will allow you see your sites paginated (you may need to add extra Jetpack connected sites to have more than 10 sites for example).
* Then, test pagination with different screen sizes plus on mobile, as well as with the preview pane open. The Figma link above shows some examples of how the pagination should look.

Screenshots:
Screenshot 2024-04-04 at 21 19 24

On mobile:
Screenshot 2024-04-04 at 21 20 38

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Review by cleacos — APPROVED** [review]
Now it works (looks) as expected

LGTM!

**Comment by rcanepa** [comment]
@coder-karen, you wrote a few `!important` in these changes, which we try to avoid as much as possible. Did you add them to style the Dataviews component, given that its internals are outside our control?

**Comment by coder-karen** [comment]
`.dataviews-pagination` is a Dataviews component style and it's styles are outside of our control, yes 😄 

With `.layout__primary .preview-hidden` I'm overwriting a more global Calypso style.

It' possible there may be a better way to style `.sites-overview__content:has(.dataviews-pagination)` and `.main.a4a-layout.sites-dashboard:has(.dataviews-pagination)` though. I could take another look at that.

**Comment by rcanepa** [comment]
> I could take another look at that.

Don't worry about it for now since the Dataviews will likely change in the future, and we might have to change this code again. In other words, I consider it a very low-priority issue, given the circumstances.

**Pull request merged**
