### PR TITLE
Avoid duplicate stats requests by refactoring the QuerySiteStats component

### PR DESCRIPTION
**Pull request by jsnajdr**
When loading the `/stats/day` page, Calypso sends two duplicate requests to the `sites/:site_id/stats/country-views` endpoint. That's because we're rendering `QuerySiteStats` twice with the same query: once in `<StatsModule statType=""statsCountryViews"/> and a second time in `<GeoChart>` inside it.

That should be prevented by the `if ( ! requesting )` check in `QuerySiteStats`, but it isn't.
The sequence of events is:
1. `mapStateToProps` of the 1st component is called, `requesting` is false
2. `mapStateToProps` of the 2nd component is called, `requesting` is also false
3. `cmpDidMount` of the 1st component is called, `this.props.requesting` is false, therefore starts to dispatch request action
4. the `requesting` flag in Redux state is set to `true`, `mapStateToProps` of both query components is called, `setState` gets scheduled on both components.
5. the actual network request is issued from the 1st component.
6. `cmpDidMount` of the 2nd component is called, `this.props.requesting` is still false, because the `setState` from step 4 hasn't been executed yet. Starts to dispatch request action.
7. another pair of `setState` is scheduled and another network request is issued (!)
8. the scheduled `setState` calls are executed and both query components receive a `false` value of `this.props.requesting`. But it's too late.

This patch fixes the bug by replacing `cmpDidMount` and `cmpDidUpdate` with `cmpWillMount` and `cmpWillReceiveProps`, respectively. The difference is that in these lifetime methods, the `setState` calls are executed immediately and the race condition described above is avoided. See React docs for details.

This patch also avoids geting a 'Lifecycle hook scheduled a cascading update' warning from React
that are displayed in the "User Timings" section of Chrome profiler.

**How to test:**
1. Load `/stats/day/:site_id` and watch network requests in Network panel
2. Check that there are two requests to `country-views` before the patch
3. Check that there is only one request after the patch
4. Check that querying stats still works in general and is not broken

### CODE REVIEW

**Comment by jsnajdr** [comment]
> Just a general note that React recommends side-effects be performed in componentDidMount, componentDidUpdate, and componentWillUnmount.

There's also another recommendation: never call `this.setState` in `componentDidMount` and `componentDidUpdate`. The rationale is that it immediately triggers a second rerender. It's even enforced in Calypso with an ESlint rule that will complain about a direct `setState` call in these methods.

The `Query` component dispatches a request action that does both: it issues a request, and indirectly calls `this.setState` in a dispatch -> reduce -> notifyListeners -> mapStateToProps -> setState cycle. That makes it impossible to follow both recommendations at once and we need the one that's more relevant.

> Are we going to see this race condition for other query components that depend on isRequesting state (eg not using the data-layer)?

Yes, all `Query` components that use a Redux `isRequesting` flag to conditionally issue a request are affected. `wpcom`-based components uses it, data-layer doesn't -- it tracks active requests outside Redux.

**Comment by gwwar** [comment]
@jsnajdr I wonder if we should chat about that in framework a bit. You've certainly demonstrated that many of our query components don't work well when we rely on `isFetching` state to stop other instances of the component from starting a request. This sounds more of a concurrency issue, and we should probably try to port as much as we can to the data-layer to keep things simple.

I don't think it's unusual to dispatch from the *Did lifecycles, as this is exactly what happens in Redux's example async app. https://redux.js.org/docs/advanced/ExampleRedditAPI.html#containersasyncappjs

Folks have mentioned that `componentWillUpdate` may be invoked more than once, but I haven't been able to find docs on when it does so. In our case the action should be idempotent but not ideal if the get request fires more than once.

The following may also be of interest: also https://github.com/reactjs/rfcs/pull/6/files

**Comment by jsnajdr** [comment]
> You've certainly demonstrated that many of our query components don't work well when we rely on `isFetching` state to stop other instances of the component from starting a request.

The bug only happens when two identical queries are performed in one render cycle:
```jsx
<div>
  <QueryStuff />
  <QueryStuff />
</div>
```
The expected behavior is that if the first `QueryStuff` issues a request on mount, the second instance will see the updated value of the `this.props.isRequesting` flag and will not issue another request.

But the way how the `isRequesting` update travels from the first component's dispatch to the second component's prop update is partially asynchronous, because it involves `setState`. When the second component mounts, it still has the old value.

> I don't think it's unusual to dispatch from the *Did lifecycles, as this is exactly what happens in Redux's example async app.

I believe that example app has the same potential bug. If the `Root` component rendered two `AsyncApp`s next to each other:
```jsx
<Provider store={store}>
  <AsyncApp />
  <AsyncApp />
</Provider>
```
it would also issue duplicate requests, despite the `isFetching` guard.

I think that the correct way how to handle the `isRequesting` state is outside Redux and the React lifecycle machinery, by simple setting and reading JS object properties. Like our data layer does.

**Comment by gwwar** [comment]
Thanks for adding clarifying examples! That makes a lot more sense. 

> I believe that example app has the same potential bug.

Definitely, but by it's name, I don't believe it was meant to ever have more than one instance. As your examples show, we should be careful when this happens. Especially, if and when React happens to change how its internals work.

> I think that the correct way how to handle the isRequesting state is outside Redux and the React lifecycle machinery, by simple setting and reading JS object properties. Like our data layer does.

💯 agreement on that.

**Pull request merged**
