### PR TITLE
Pages: add author filter

### PR DESCRIPTION
**Pull request by michaeldcain**
This adds an author filter to the Pages and All Sites > Pages lists, and makes use of the `PostTypeFilter` component for post status filtering and searching.

**To test:**
- visit a site's page list (`/pages/{siteSlug}`) on a site with multiple authors
- verify that all published pages for the site are shown by default
- verify that the post status tabs, author filter, and search functionality work as expected
- visit the all sites page list
- verify that all published pages for all of the user's sites are shown by default
- verify that the post status tabs, author filter, and search functionality work as expected

### CODE REVIEW

**Comment by fditrapani** [comment]
I'm seeing the filter but no pages for some reason :P. I also see a wide margin on the right of the filter which I'm thinking is because that's where the search would go? (looking at the code, a class called pinned items is adding the extra padding).

image

**Comment by fditrapani** [comment]
I just saw your other PR that fixes the list of pages. Disregard my previous comment :)

**Comment by michaeldcain** [comment]
> I just saw your other PR that fixes the list of pages

Sorry, I should've linked to #47440. It's what sent me down this rabbit hole.

**Comment by michaeldcain** [comment]
@fditrapani I rebased this after #47440 merged, and fixed the empty padding. Let me know if this works for you.

**Review by fditrapani — APPROVED** [review]
Nice! Looks great. Thanks.

**Pull request merged**
