### PR TITLE
Video UI: Autoplay behaviour

### LINKED ISSUE #57662: Videos UI: Videos are not autoplaying on play button clicks.
Videos should autoplay when the user clicks a "Play video" button.

### PR DESCRIPTION
**Pull request by andres-blanco**
This PR adds auto play to videos when the **Play video** button is clicked.

| Before  | After |
| ------------- | ------------- |
|   |  |

#### Testing
1. Switch to this branch.
1. Add the component to My Home.
1. Verify that the video is initially paused.
1. Verify that after clicking the **Play video** button the corresponding video is played.

### CODE REVIEW

**Comment by kwight** [comment]
This works well! I expected to be able to stop the current video, then click "Play video" for that section and have it start again, but that's a bit of an edge case at this point. Here, we're saying "load this video with autoplay on", as opposed to "play that video" (not sure if there's really a way to do that 🤔 ).

**Review by kwight — DISMISSED** [review]

**Comment by kwight** [comment]
> "play that video" (not sure if there's really a way to do that 🤔 )

Oh, looks pretty straightforward: https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/play We should be able to separate the "load video" and "play video" actions: on click, load the current section's video, if not already loaded – then play whatever video is loaded.

**Comment by andres-blanco** [comment]
> This works well! I expected to be able to stop the current video, then click "Play video" for that section and have it start again, but that's a bit of an edge case at this point. Here, we're saying "load this video with autoplay on", as opposed to "play that video" (not sure if there's really a way to do that 🤔 ).

@kwight this should be working as expected now :)

**Comment by kwight** [comment]
> this should be working as expected now :)

Perfect! <3

**Review by kwight — APPROVED** [review]

**Pull request merged**
