### PR TITLE
Reader: Use the same styles for post comments as post content

### PR DESCRIPTION
**Pull request by sarayourfriend**
#### Changes proposed in this Pull Request

* Use the same we use to render post content in reader to also render post comments

I just copied and pasted the styles but obviously they should be put in a shared location... I'm just not sure of where that should be. Any suggestions?

#### Testing instructions

* Load a post with some comments left using the block editor (for example `/read/feeds/104773847/posts/2656283156`) and ensure that headings, tables, quotes and other blocks all have the expected styles applied to them

### CODE REVIEW

**Comment by bluefuton** [comment]
> I just copied and pasted the styles but obviously they should be put in a shared location... I'm just not sure of where that should be.

The comments block is used outside the Reader too so feels like it should be at the top level. Maybe in `assets/stylesheets` @saramarcondes?

**Review by tyxla — COMMENTED** [review]
There's quite a substantial difference in the vertical spacing between this branch and production. Is that expected?

This branch:


Production:


Post I used for comparison: https://wordpress.com/read/blogs/20115252/posts/106736

**Comment by sarayourfriend** [comment]
@tyxla Oh that's a good catch. It seems we're adding padding top now the div itself. Should be an easy fix.

**Comment by tyxla** [comment]
> @tyxla Oh that's a good catch. It seems we're adding padding top now the div itself. Should be an easy fix.

Thanks for fixing it @saramarcondes. Seems like after fixing the margins, there are some line height differences that became more visible. Is this something we'd need to fix as well?

**Comment by tyxla** [comment]
I've just given this a spin again and I noticed that tests are failing consistently and it appears this is reproducible locally too with:

```
NODE_ENV=production cd apps/notifications/ && yarn build --output-path="../../artifacts/notifications"
```

**Review by tyxla — APPROVED** [review]
LGTM 🚢

**Pull request merged**
