### PR TITLE
Consolidate state shape for happychat.ui

### PR DESCRIPTION
**Pull request by nosolosw**
Master issue: #18670

Previous work to change the Happychat state shape (#18638) was divided into pieces to help in their review. This PR addresses the changes related to `happychat.ui` key.

Note that it also fixes a bug in the custom persistence mechanism: `lostFocusAt.hasCustomPersistence = true;` was `lastActivityTimestamp.hasCustomPersistence = true;`.

### Test

`npm run test-client happychat`

Manually test that happychat works as expected (open a session with an operator, reconnecting after going offline, etc).

### CODE REVIEW

**Comment by unDemian** [comment]
Hmm.. weird I still get the js console error, I tried cleaning cache and all site data (indexdb, cookies..).

**Comment by nosolosw** [comment]
Cannot reproduce it  :/ Rebased again from master, would you mind trying again @unDemian ? @omarjackman @southp could you give it a try and report whether it works for you?

**Comment by southp** [comment]
Hmm, I can't reproduce it, either. Would `npm run distclean` or `git reset --hard origin/update/happychat/state-ui` help? Just some random ideas :)

**Comment by unDemian** [comment]
Force resetting did the trick, thanks. LGTM 👍

**Pull request merged**
