### PR TITLE
Reader: Fix double images on boing boing

### LINKED ISSUE #14686: BoingBoing posts have double images on fullpost pages, missing videos
BoingBoing is behaving strangely. https://wordpress.com/read/feeds/9166444/posts/1480376980

This post (https://wordpress.com/read/feeds/9166444/posts/1480376980) has the same image twice and is missing the YouTube video from the original post: http://boingboing.net/2017/06/01/watch-mind-blowing-close-up.html

Most of the other recent BB posts have the double image problem, too:
https://wordpress.com/read/feeds/9166444/posts/1480298347
https://wordpress.com/read/feeds/9166444/posts/1480292265
https://wordpress.com/read/feeds/9166444/posts/1480287956
https://wordpress.com/read/feeds/9166444/posts/1480287958

cc @blowery

### PR DESCRIPTION
**Pull request by blowery**
Fixes #14686

### CODE REVIEW

**Comment by samouri** [comment]
I'm not the biggest fan of this band-aid. According to [this comment](https://github.com/Automattic/wp-calypso/issues/14686#issuecomment-305582990) it looks like the actual filename part of the url is identical.  

Could it be worthwhile to use that as a heuristic for deduping?

`isTheSameImage( '/a/b/c.jpg', 'c.jpg' ) ` --> true.   

Because we would use this specialized check _just_ for featured images I think the heuristic could make sense

**Comment by blowery** [comment]
> Could it be worthwhile to use that as a heuristic for deduping?

Thing is, I thought we were only matching on the pathname already...

Ah, the problem is that these are photon image urls from the get go. So:

i2.wp.com/media.boingboing.net/...
vs
i2.wp.com/boingboing.net/...

so for photon links, we should probably lop off the text before the first slash in the pathname before doing the compare.

**Comment by samouri** [comment]
I think instead of pathname, do everything from the last slash till the file extension

**Comment by blowery** [comment]
> I think instead of pathname, do everything from the last slash till the file extension

tried that initially, doesn't work in a number of cases

**Comment by blowery** [comment]
taught `isFeaturedImageInContent` about photon in https://github.com/Automattic/wp-calypso/pull/14719/commits/967d2f1693febdd545f045e71039ff8c85dc6d80

**Comment by blowery** [comment]
tests added!

**Comment by fraying** [comment]
This is great. So will this now fix the double image problem for more than just Boing Boing?

**Comment by blowery** [comment]
> So will this now fix the double image problem for more than just Boing Boing?

Yup, should help with any site using photon in their content.

**Pull request merged**
