### PR TITLE
Update/legacy to recommended map 2

### PR DESCRIPTION
**Pull request by TheSteveK**
#### Proposed Changes

* this change adds on to the PR to display plan recommendations to users who try to add a legacy plan to the cart.  Ref https://github.com/Automattic/wp-calypso/tree/fix/missing-plan-recommendations-on-pricing-page
* The plan recommendation page would display no-longer-available products such as backup daily
* This updates what is suggested based on https://jetpack.com/support/jetpack-plan-equivalency-chart/
* This will also render the button for the deprecated plan's card as disabled

Screen Shot 2022-11-09 at 10 03 18 AM

#### Testing Instructions

* Use the calypso.live link below
* Try to visit the checkout page with an old product by appending one of these to the live link:
* /checkout/:site/jetpack_personal
* /checkout/:site/jetpack_premium
* /checkout/:site/jetpack_business
(substitute :site with a valid Jetpack site you own)
* You should see a section above the current Pricing page that informs you the selected plan is not available and offers alternatives:
* Personal should show Backup + Anti Spam
* Premium should show Security + Videopress
* Business/Professional should show Complete
* Verify that you can add the products to the cart when you click on the CTA button
* Verify the button for the current (deprecated) product is disabled

#### Pre-merge Checklist

- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?

Related to #

### CODE REVIEW

**Comment by TheSteveK** [comment]
This is a re-do of the previous commit update/legacy-to-recommended-map which had issues with a rebase.  There was a small change in the code to correct the Backup slug so it shows correctly for the Personal plan.

**Comment by TheSteveK** [comment]
@elliottprogrammer for your re-review, I've updated the test instructions and I've added a small commit to disable the old plan's button since it doesn't do anything as discussed.

**Comment by elliottprogrammer** [comment]
> @elliottprogrammer for your re-review, I've updated the test instructions and I've added a small commit to disable the old plan's button since it doesn't do anything as discussed.

I don't see the small commit to disable the old plan's button. Maybe you didn't **_push_** it?

**Comment by TheSteveK** [comment]
> I don't see the small commit to disable the old plan's button. Maybe you didn't **_push_** it?

Looks like I added it to the parent PR instead. https://github.com/Automattic/wp-calypso/tree/fix/missing-plan-recommendations-on-pricing-page

**Review by elliottprogrammer — APPROVED** [review]
LGTM!! 👍

**Pull request merged**
