### PR TITLE
Add Support Search to Customer Home

### PR DESCRIPTION
**Pull request by getdave**
As per #38860, embeds a "Support Search" section directly onto the Customer Home screen.

This allows users to search support docs directly without having to toggle open the existing floating FAB icon.

Fixes https://github.com/Automattic/wp-calypso/issues/38860

## Screenshots

Screen Capture on 2020-05-22 at 14-32-19

## Testing instructions

* Checkout this PR.
* Boot Calypso locally. `yarn start`. Wait for a long time...
* Navigate to your Site's Customer Home - `http://calypso.localhost:3000/home/{YOUR_TEST_WEBSITE}`
* See Support search "card" as per design in https://github.com/Automattic/wp-calypso/issues/38860#issuecomment-631125518
* Switch to another language and check all UI strings (not search results as this PR doesn't control those) are translated.
* Proceed to testing search and FAB (see below).

### Search testing

Try out the following scenarios to validate searching behaves as expected. For each scenario you _must_ be able to:

1. Click on the search result to open in modal.
2. Use keyboard down arrow to move from the search input into the results and hit ENTER to open the result in the modal.

The scenarios are:

* Search for empty string - should see contextual results immediately (no loading state).
* Search using a string containing multiple SPACE chars only - should see contextual results immediately (no loading state).
* Search for "Podcast" and see API results.
* Clear search input using "X" icon - should see contextual results immediately (no loading state).
* Clear search input using backspace - should see contextual results immediately (no loading state).

### Validate FAB still works

The Customer Home Support Search reuses many of the same components as the original FAB "Help" floating icon. Therefore it is critical we validate the changes made in this PR have not broken that implementation.

Please repeat the above steps but this time navigate to another section of Calypso such as "Pages". Then click on the "?" FAB icon and check that all the of the above functionality works. The only exception should be that the FAB doesn't not _immediately_ open a modal but shows an interstitial view first within the popover.

### Validate Events Fire

* Open devtools console.
* Paste `localStorage.setItem( 'debug', 'calypso:analytics*' );` and hit `ENTER`.
* Refresh the page.

## Todo

- [x] Use existing `getContextualHelpResults` selector within `requestInlineHelpSearchResults` creator to avoid importing all sorts of helpers. Ideally this means we don't need to pass the current route path into the action creator dispatch call.
- [x] Add comments to explain approach to storing contextual results in state and also the purpose of the state flag which indicates whether results came from the API.
- [ ] Raise Issue in Calypso repo regarding a11y issue with `components/search` whereby input loses focus when it is reset via the "X" icon. 
- [x] Add translation for `No results` within `client/blocks/inline-help/inline-help-search-results.jsx`.
- [x] Hide existing FAB icon on Customer Home.
- [x] Add CSS to fix the height of the box.
- [x] Immediately dispatch contextual results if search query is empty.
- [ ] Don't track searches for empty strings.
- [ ] Ensure we differentiate in tracking between the floating FAB and the Customer Support Search.
- [ ] Consider [using route to determine whether the FAB is shown](https://github.com/Automattic/wp-calypso/blob/24bd44e99c33c4b511eaaedbaf6f654c93c38916/client/layout/index.jsx#L106).

### CODE REVIEW

**Comment by getdave** [comment]
@frontdevde Looks like [you worked on this previously](https://github.com/Automattic/wp-calypso/pull/24390). I wonder if you could advise on how I can test for special types of support results such as:

* Video
* Tours

At the moment I can't seem to find any despite copying the text from your PR screencaptures.

Also it would be great if you could help review when it's ready for review.

**Comment by getdave** [comment]
I've found a bug which affects both the original implementation and the Customer Home version.

To replicate:

* Focus search input.
* Use keyboard down arrow to move into the search results. See that you can use up/down to move around.
* Search for "Podcast". Again use arrow keys to move focus around results shown.
* Clear search UI using "X" or deleting text from input.
* Now try to use arrows again and it doesn't work. 

The reason for this is that the results showed when there are "no results" are contextual based on the page. These are statically coded results and not retrieved from an API.

On component mount the static contextual results are set as "search results" in state. However this is the only time they are set to state. On subsequent re-renders (eg: when clearing search UI) the results are rendered to the page without being added to state (missing the call to `setSearchResults`).

**Comment by getdave** [comment]
## Responding to design feedback 

The below is a response to design feedback in the Issue at from https://github.com/Automattic/wp-calypso/issues/38860#issuecomment-632393587. 

> * The links should be identical to the font, size, color, and hover of the other links on customer home. See below:
>   image

✅ I've left the default styling to cascade into these links now so that should be the case.

> * More help link takes you here: https://wordpress.com/help

✅ Done.

> * > The search results are all left aligned with no horizontal padding. However this "breaks" the keyboard navigation (using down arrows) "selected" state visuals. See existing FAB.
> 
> Not sure what this means. The links should have the focus status of other links on the Customer Home, no dark blue background.

To see what I mean:
* Open the existing FAB.
* Click into search box.
* Hit the DOWN arrow on your keyboard.
* You will have selected the first item in the list. You can use arrows to move between items. Note this is NOT the same as focus. This indicates a _selected_ state for that element.

What I'm asking is how the Customer Home Support Search design intends to communicate "selected" state to keyboard users. You've suggested it should be the same as the other links on the page, but I really don't think that communicates the "selected" state. For a11y reasons it should be explicitly clear when an item is selected vs hover/focus as they are conceptually different.

Refer to existing FAB to see the current implementation.

> * Placeholder text is not the replacement for labels, it's not read by screen readers, and the contrast rules don't typically apply there if there are other cues. "Get help" above the search field is an indicator for that. If we observe user confusion post implementation, we will try a more descriptive label.

It is true the placeholder text is not a replacement for a label. The visual cue is certainly useful but I wasn't aware that the contrast of placeholders could be disregarded in the case of contextual clues around the field itself. Indeed, the [WAI guidelines appear to suggest this isn't appropriate](https://www.w3.org/WAI/tutorials/forms/instructions/#styling). Let me know - I'm not going to labour the point if you feel strongly about it.

> * Let's drop the placeholder text on smaller screens altogether.

Are you able to explain why you want to do this? It's just that if anything there is _more_ room on smaller screens. Perhaps I missed something?

Screenshot 2020-05-22 at 14 35 32

> * Let's keep the box height consistent. If there are fewer results, there will be white space. It's temporary tho, so I don't see a problem there, @lcollette any objection to that?

Ok I'll do my best to sort out a fixed box height.

> * Let's max results to five.

✅ Done.

**Comment by getdave** [comment]
@olesyabrk This is now ready for a Design review. Thanks very much.

**Comment by getdave** [comment]
@Automattic/ajax This is ready for an initial team review. Still marked as draft so as not to ping all the Calypso folks.

I still need to implement tracking.

**Comment by gwwar** [comment]
@olesyabrk did you mean to merge this?

**Comment by olesyabrk** [comment]
> @olesyabrk did you mean to merge this?

I didn't, pardon me.

**Comment by olesyabrk** [comment]
@getdave 
> Are you able to explain why you want to do this? It's just that if anything there is more room on smaller screens. Perhaps I missed something?

Yes I was going off a screenshot you posted where it was being cut off, but it looks great in the test environment. Let's leave it as is. 

Placeholder text: let's leave as is for now. 

>What I'm asking is how the Customer Home Support Search design intends to communicate "selected" state to keyboard users. You've suggested it should be the same as the other links on the page, but I really don't think that communicates the "selected" state. For a11y reasons it should be explicitly clear when an item is selected vs hover/focus as they are conceptually different.

Yep, I see what you mean and I agree. Can we expand the selected state to the edge like in the FAB currently?

**Comment by gwwar** [comment]
@getdave we use the support card in other site types. I think it's safer to create a new search card, and see if this fits with the other views. On the server we do have a dev flag for easier development.

Feel free to DM or chat with Serenity if that didn't make sense.

**Pull request merged**
