### PR TITLE
A4A: Use a regular Automattic logo color variation in the 'Add new site' split button.

### PR DESCRIPTION
**Pull request by jkguidaven**
The current split button features the Automattic logo, which is difficult to see when not selected. This pull request addresses this issue by using the regular variation color.

| Before | After |
|--------|--------|
| Screenshot 2024-05-24 at 4 44 45 PM | Screenshot 2024-05-24 at 4 44 30 PM | 

Follow up https://github.com/Automattic/wp-calypso/pull/90883

## Proposed Changes

*

## Why are these changes being made?

*

## Testing Instructions

*

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Comment by cleacos** [comment]
I've noticed that if you click on the Add new site button directly, the zip downloads directly. This is a bit weird because, as a user, I know nothing about it. This is what it looks like now:

image

**Review by andrii-lysenko — APPROVED** [review]
LGTM 👍

**Comment by jeffgolenski** [comment]
> I've noticed that if you click on the Add new site button directly, the zip downloads directly. This is a bit weird because, as a user, I know nothing about it.

Good call out @cleacos - is there a way to make the default action just open the options in this case as a quick solution? 

@jkguidaven - Apologies, but now that I'm testing it, I feel like the fill color within the pill shape of the Automattic logo should change. 

* During resting state when the entire link has a white background, keep the dark pill shape
* On hover, when the link background is blue, have the white pill shape.

CleanShot 2024-05-24 at 16 33 24

CleanShot 2024-05-24 at 16 33 48@2x

**Comment by jkguidaven** [comment]
Thanks everyone for the review ❤️ 

> Apologies, but now that I'm testing it, I feel like the fill color within the pill shape of the Automattic logo should change.
>
> During resting state when the entire link has a white background, keep the dark pill shape
> On hover, when the link background is blue, have the white pill shape.

This has been addressed 👍 

https://github.com/Automattic/wp-calypso/assets/56598660/c7f3a0b4-13cc-4761-8fd0-d8ef8b182447

> is there a way to make the default action just open the options in this case as a quick solution?

I couldn't find a quick solution for this because the Calypso's split button component wasn't designed to handle this. It will require some refactoring, which has some risk of breaking other areas that rely on the same component.

My suggestion for a quick fix would be to disable the main button so that it doesn't trigger any action when clicked. wdyt?

**Comment by keoshi** [comment]
Nice stuff — maybe we can iterate on this further by:

- Changing the button to say “With the A4A Plugin”.
- Having a modal pop up after clicking the button.
- The modal explains what the plugin is and what it does.
- The modal also contains a link to the direct download.

@madebynoam Had a really nice modal design that is close to the plugin UI, and could be a great way to bridge the plugin and the platform.

**Comment by keoshi** [comment]
@jkguidaven Here's the modal that @madebynoam designed for Referrals:

image

Figma link here: https://www.figma.com/design/fuufP6VNfZXYmvLsTRWRlG/Referrals?node-id=7145-73019&t=HUhvlc6oeRLm3N85-11

Worth noting though that this issue is slightly related to a bigger effort of letting customers add sites in multiple ways:

> - Creating new site (Dotcom or Pressable).
> - Adding an existing site via the A4A plugin.
> - Adding an existing site via Jetpack connection.
> - Importing existing sites from Dotcom.

We're tracking this here: https://github.com/Automattic/automattic-for-agencies-dev/issues/562

Over the next couple of days I'm hoping to systematize this “Add site” flow a little bit more, so we can ship this PR and address that bigger push later. What do you think?

**Comment by jeffgolenski** [comment]
@jkguidaven 

> My suggestion for a quick fix would be to disable the main button so that it doesn't trigger any action when clicked or use a regular dropdown menu. wdyt?

Works for me if that's an immediate solution we can ship before Noam and Filipe finalize their concepts mentioned above?

**Comment by jkguidaven** [comment]
> Over the next couple of days I'm hoping to systematize this “Add site” flow a little bit more, so we can ship this PR and address that bigger push later. What do you think?

Yes, I'd love to have a proper way to address this. Will wait on it 👍

**Comment by jkguidaven** [comment]
> Works for me if that's an immediate solution we can ship before Noam and Filipe finalize their concepts mentioned above?

Sounds good to me. 👍

**Comment by jeffgolenski** [comment]
@jkguidaven Sorry my friend, I didn't anticipate this working quite like this. Can we revert this change? With the disabled state + the cursor change, this is communicating that the user isn't able to add new sites, even though the chevron is active. 

We'll just have to prioritize the modal selection screen Filipe mentioned above cc @rcanepa 

CleanShot 2024-05-30 at 14 01 38

**Comment by rcanepa** [comment]
@jeffgolenski, I created a PR that reverts this one: https://github.com/Automattic/wp-calypso/pull/91310

**Comment by jkguidaven** [comment]
@jeffgolenski, I apologize for going ahead and merging this without your final confirmation. Thanks @rcanepa for creating the revert PR 👍

**Comment by rcanepa** [comment]
@jkguidaven, mistakes like this will happen again in the future, and that's okay. I wouldn't like you or anyone else to stop shipping things without Jeff's or someone else's approval! I'm sure Jeff wouldn't like it either!

Next time, I suggest sharing a screenshot or recording of the behavior so stakeholders can better understand the changes' impact.

You're shipping a lot of great work and with great speed. Keep doing it!

**Comment by keoshi** [comment]
@rcanepa +1000!

**Pull request merged**
