### PR TITLE
Cancelation survey: ask import specific questions

### PR DESCRIPTION
**Pull request by jonathansadowski**
#### Changes proposed in this Pull Request

* Updates the "remove purchase" survey to have an additional question about the import quality when the associated site has done an import

#### Testing instructions

* Apply and follow the instructions on D33115-code.
* Complete an import and make a purchase (the order should not matter).
* Visit `/me/purchases` and select your purchase.
* Select "Cancel Subscription and Refund".
* Select "Cancel Subscription".
* Verify that in addition to the 2 default questions, a third question about importing appears.
image
* Answer the question, and verify that you are able to continue. Verify that your answer is recorded (see D33404-code).

### CODE REVIEW

**Comment by mattsherman** [comment]
@jonathansadowski Any update on this?

**Comment by andfinally** [comment]
I'm not getting the extra question.

* Applied D33115-code and sandboxed the API.
* Applied this PR and ran Calypso locally.
* Went to http://calypso.localhost:3000/import/[ site ] and did an import.
* Went to http://calypso.localhost:3000/plans and purchased a Business plan.
* Went to http://calypso.localhost:3000/me/purchases and selected the plan I'd just purchased.
* Saw this. Clicked on "Remove WordPress.com Business".

image

* Got the original popup with two questions.

**Comment by jonathansadowski** [comment]
Thanks @andfinally I think it may be an issue with setting the option in D33115-code. I ran into this once when testing, and then manually set the option -- and I think I may have forgotten I manually set it when retesting. I'll look into D33115-code to verify.

**Comment by andfinally** [comment]
I'd suggest inserting the extra question between the current two, if possible. "Where is your next adventure taking you?" feels like it should be at the end.

Suggested slightly tweaked wording.

```
You imported from another site. How did the import go?
- I was happy.
- Most of my content was imported, but it was too hard to get things looking right.
- Not enough of my content was imported.
- I didn't have the functionality I have on my existing site.
```

**Comment by andfinally** [comment]
It looks like the issue is with the API returning null for `import_engine`. I've added an example to D33115-code.

**Comment by andfinally** [comment]
The issue was a typo in the option name in D33115. With that fixed, the survey appears as expected. I've tweaked the wording, moved the question and added some margin below each question, as it was looking a bit texty. Please feel free to revert that commit if you don't like the changes. The popup now looks like this:

image

**Comment by jonathansadowski** [comment]
Thanks for the review / tweaks @andfinally

**Pull request merged**
