### PR TITLE
Purchase Detail: Improve Colour Contrast

### LINKED ISSUE #35098: My Plan: Feature card headings need higher contrast
screen-shot-2019-07-08-at-12 53 28-pm-1

#### Steps to reproduce
1. Starting at URL: http://wordpress.com/my-plan/
2. The headings on each of the feature cards (as seen above) need more contrast to pass AA WCAG standards
3. We can probably use the CSS var `--color-text-subtle` instead.

### PR DESCRIPTION
**Pull request by Aurorum**
#### Changes proposed in this Pull Request

* Switches the --neutral-light variable to --text-subtle for contrast

#### Testing instructions

Visit `/plans/my-plan/site` and compare the heading colours.

Screenshot 2019-08-05 at 21 14 45

Fixes #35098

### CODE REVIEW

**Comment by Aurorum** [comment]
Conflicts resolved. :)

**Comment by bluefuton** [comment]
Still worth doing I think - `color-neutral-40` appears to fail WCAG AAA:

Screen Shot 2021-03-05 at 15 04 02

**Review by sixhours — APPROVED** [review]
Yep yep! Using variables rather than hard-coded color values is 💯 for color scheme compatibility, too. :D

**Comment by bluefuton** [comment]
On re-testing I see that `color-neutral-40` is the equivalent color to `text-subtle` and the original bug was actually closed in #36119. 

That said, the `text-subtle` naming seems clearer so I'll go ahead and merge this 👍

**Pull request merged**
