### PR TITLE
Signup: Update signup to make it possible to provide dependencies in query

### PR DESCRIPTION
**Pull request by drewblaisdell**
This PR updates signup to allow a flow itself to specify that it provides a dependency in the query string. This allows us to provide a dependency like `siteSlug` to update an existing site with the `/start` flow (instead of creating one).

It also:

- Renames the `theme` dependency to `themeSlugWithRepo` to make it clearer what that dependency contains.
- Adds tests.
- Adds a `site-selected` flow that we can use to test this, and later, update to allow users to set up an existing domain-only site.

**Testing**
*`site-selected`*
- While logged in, visit `/start/site-selected?siteSlug=[site_slug]` where `[site_slug]` is the slug for a site for which your account is the owner.
- Select a theme.
- Once the signup "completes", click `Continue`.
- Assert that you are taken to your site and that it now has the theme you selected in the second step.

*The main flow*
- Visit `/start` in a new browser session.
- Proceed through signup and assert that you can complete it as before.

- [x] Code
- [x] Product

### CODE REVIEW

**Comment by drewblaisdell** [comment]
cc @scruffian who may be interested in this change

**Comment by gziolo** [comment]
I guess @scruffian  should review this PR in first place. It looks okey in my opinion, but I have very little knowledge how it should be updated properly.

We could argue that signup flow code is getting to flexible and a bit off track 😄  My point is that the complexity of the code is growing with every new use case we introduce. Especially if the new flow  doesn't create a new account.

I don't have a better solution for it, so I'm fine with what you have proposed. If Ben likes the changes, then we should definitely test it extensively and merge it as it is.

**Comment by gziolo** [comment]
I see the following error when going through the `domain-first` signup flow:

> Uncaught Error: This step (themes) provides an unspecified dependency [theme]. Make sure to specify it in /signup/config/steps.js, using the providesDependencies property
> at assertValidDependencies (dependency-store.js:55)

It happens when I click `Just buy a domain` on the site or domain page.

**Comment by stephanethomas** [comment]
The code looks good, although I don't understand the meaning of `themeSlugWithRepo`.

I've tested it and it works fine. I agree with @gziolo, the signup code is becoming a White elephant.

**Comment by scruffian** [comment]
Code 👍

**Comment by scruffian** [comment]
I think we already do something similar with the `new` parameter too. It would be good to change that to use this approach too...

**Comment by drewblaisdell** [comment]
This is ready for review again. Thanks for the reviews, @scruffian @stephanethomas @gziolo.

> We could argue that signup flow code is getting too flexible and a bit off track 😄 My point is that the complexity of the code is growing with every new use case we introduce.

I agree. The initial framework was overengineered in order to make it easy to create new/update existing signup flows in `signup/config`. Deviating from the original use case (signup as a series of steps that can appear in any order and satisfy each others' dependencies) now requires increasing the complexity of that framework.

However, if we built it today, I think we would want it be more flexible, given the amount of times we have wanted to deviate from the initial use case. It would be simpler: instead of an array of step names, a signup flow would be a component wrapping a series of step components that are each provided some lifecycle methods. `apiRequestFunction` would become a chain of promises that the framework determines the order in which to run.

> Especially if the new flow doesn't create a new account.

Thankfully, this is an existing use case for signup (see the `get-dot-blog` flow). Users add sites by going through a flow that doesn't create a user, too, and have for over a year.

> I see the following error when going through the `domain-first` signup flow:

Thanks for catching that. I fixed it by removing `themeSlug` entirely - it can be derived from `themeSlugWithRepo`, so we don't need it as a dependency.

> The code looks good, although I don't understand the meaning of `themeSlugWithRepo`.

`themeSlugWithRepo` is a string like `pub/twentysixteen`, whereas the theme slug is just a string like `twentysixteen`. The API requires both, depending on the endpoint.

> I think we already do something similar with the `new` parameter too. It would be good to change that to use this approach too...

The `new` query string populates a field on the domain step, but isn't a dependency, so the changes here aren't relevant to that unfortunately.

**Comment by hafizrahman** [comment]
As this seems more of a structural change, there's nothing I need to check product-wise aside from the fact that it works :) Product LGTM.

**Comment by gziolo** [comment]
I double tested it. It works properly for a regular flow, domain only flow and domain first + plan flow.

**Pull request merged**
