### PR TITLE
Jetpack Connect: Centre Plan Pill

### LINKED ISSUE #32447: Jetpack NUX: "Best value" tag placement could be improved
#### Steps to reproduce 

- Start with a Jetpack site
- Connect to WordPress.com 
- When the Jetpack plans page appears, look for the `Best value` tag

#### What is expected 

The tag is centered. 

#### What happens instead 

The tag currently appears to be placed on the far left, making it look misplaced.

Screenshot 2019-04-20 at 13 58 16

Screenshot 2019-04-20 at 13 58 27

I think this has something to do with matching the `Popular` tag on WordPress.com plans, as shown below (which looks good), but in the case of Jetpack plans I think they are best placed at the center.

Screenshot 2019-04-20 at 14 31 28

#### Notes

Not very sure if Calypso is the best place to report this, but if this needs to be moved to `Automattic/jetpack`, feel free to!

### PR DESCRIPTION
**Pull request by Aurorum**
#### Changes proposed in this Pull Request

* Centres the plan pill during Jetpack Connect, since there's only three columns that appear

#### Testing instructions

Follow the instructions in the original two but note the difference in the plan pill, especially at different screen sizes. Is it possible to make the plan pill look odd and out of place?

**Current:**

Screenshot 2019-04-21 at 13 30 43
Screenshot 2019-04-21 at 13 30 48

**Proposed:**

Screenshot 2019-04-21 at 13 30 15
Screenshot 2019-04-21 at 13 30 30

cc @arunsathiya, @keoshi, @tyxla 

Fixes #32447

### CODE REVIEW

**Comment by arunsathiya** [comment]
Thanks for contributing! I am not the decision maker though, and https://github.com/Automattic/wp-calypso/issues/32447 was intended to be a question. :) 

Let's see what Jetpack Design folks have to say though. 👍🏽

**Review by tyxla — COMMENTED** [review]
Thanks for this one @torres126!

FWIW I can see the same behavior in `/plans/:site`. If we're to change this, we should make sure to be consistent throughout all affected locations.

But I also agree with @arunsathiya - let's hear from the design folks. I'd also expect that  @Automattic/onboarding-design would have an opinion.

**Comment by joanrho** [comment]
Thank you, @torres126! Your design solution is the best fix to the misalignment of elements in this view. 

Some context around why this misalignment happened: the plans page for WordPress.com used to be centered and the "best value" pill used to be a diagonal ribbon-like banner across the top corner of the plan column. The WordPress.com team recently updated this plans view to be left-aligned (hence the placement of the pill to the left), and since we share some, but not all, of our code, Jetpack plans remained centered. In general, things now feel a bit cramped with the pill immediately below the plan name and description, but this is a separate design issue our team will need to resolve in the near future.

Although I approve the design of this, I'd like to save this PR for our new designer, Olesya, to test once she gets set up here. 

**Note to other designers eyeing this for the design meetup "bottle pickup": please don't touch this one! Olesya has dibs!** 😄

**Review by olesyabrk — APPROVED** [review]
Tested it in local and it works.

**Comment by tyxla** [comment]
cc @Automattic/luna - are you folks interested in landing this?

**Review by simison — APPROVED** [review]
Rebased locally + tested, works well. Thanks!

**Comment by simison** [comment]
Oh noooooe, sorry folks for 100 autopings folks. 🤦‍♂

I merged this with `master` (apparently from remote instead of origin). Doing this with a remote that's not owned by me is a bit wonky.

**Comment by gwwar** [comment]
Did folks verify if any recent changes got dropped, or was remote master up to date?

**Comment by simison** [comment]
@gwwar I simply deployed the change via another PR in https://github.com/Automattic/wp-calypso/pull/33870

**Pull request closed without merging**
