### PR TITLE
Change CreateClass and PropTypes

### PR DESCRIPTION
**Pull request by mikkamp**
import CreateClass and PropTypes separately.

### CODE REVIEW

**Comment by ockham** [comment]
Since it's a function, it should be `createClass` (not `CreateClass`) 😉

**Comment by gziolo** [comment]
Good catch @ockham 👍 
@mikkamp can you open a follow up PR and fix this char? Should be easy one :D

**Comment by belcherj** [comment]
@gziolo https://github.com/Automattic/wp-calypso/pull/18047

**Comment by jsnajdr** [comment]
Could we even migrate the `Card` to ES6 class? There doesn't seem anything that would prevent that.

**Comment by ockham** [comment]
Functional component even...

**Comment by gziolo** [comment]
Which is this: https://facebook.github.io/react/docs/components-and-props.html#functional-and-class-components. Good idea :)

**Comment by mikkamp** [comment]
Changed to a functional component: https://github.com/Automattic/wp-calypso/pull/18089

**Pull request merged**
