### PR TITLE
Pricing Page Rework: Add short descriptions into the product cards

### PR DESCRIPTION
**Pull request by elliottprogrammer**
This PR updates the new Pricing Page Rework product cards to display new, shorter product descriptions as per the design.

#### Proposed Changes

* Define short descriptions for all Jetpack "products" in `@automattic/calypso-products`
* Add a `shortDescription` property to the `selectorProduct` object.
* Display the short description in the pricing page displayed products.

Note: Short description for Jetpack Social product is not included in this PR because Jetapck Social product data does not exist yet. We'll need to add Jetpack Social product data in a follow-up PR.

#### Testing Instructions

* click on Jetpack Cloud live link below
    * Goto `/pricing?flags=jetpack/pricing-page-rework-v1`
* or boot up this PR 
    * Run `git fetch && git checkout add/new-product-short-descriptions`
    * Run `yarn start-jetpack-cloud`
    * Goto http://jetpack.cloud.localhost:3000/pricing?flags=jetpack/pricing-page-rework-v1
* View all the product cards and confirm that the product descriptions match the "Products Section" in this doc: https://docs.google.com/document/d/1vvzHYMsaV0EMlF4BLbvVa-dgq--9iS-I59gdic3ZjIA/edit#heading=h.nb3gcjg23dow

#### Screenshots
**BEFORE:**

Markup 2022-08-30 at 19 51 58

-------------------------------

**AFTER:** 
Product cards **with new short descriptions**:

Markup 2022-08-30 at 17 34 12

#### Pre-merge Checklist

- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [X] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - 0-as-1202886227656205

### CODE REVIEW

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/7505239

Thank you @elliottprogrammer for including a screenshot in the description! This is really helpful for our translators.

**Review by jkguidaven — APPROVED** [review]
LGTM 💯 , tested it and working as expected. 👍

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/7505239

Thank you @elliottprogrammer for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/7505239).

**Pull request merged**
