### PR TITLE
Reader SoM: email settings popout ignoreContext

### PR DESCRIPTION
**Pull request by samouri**
When you click the "settings" text twice, the second click should hide the popout.
Functionality was being ruined because the context isn't the right clickTarget.
Setting ignoreContext solved the issue

### CODE REVIEW

**Comment by samouri** [comment]
This took an embarrassing amount of time. I essentially rewrote the functionality of ignoreContext before realizing it was there :(

**Comment by blowery** [comment]
👀

**Comment by blowery** [comment]
This works for the cog, but not for the word `Settings`. Should really work for both.

**Comment by samouri** [comment]
@blowery, you sure you were testing the right branch? Clicking settings works for me

**Comment by blowery** [comment]
checking

**Comment by blowery** [comment]
yup, works, ship it

**Comment by samouri** [comment]
_phew_, thought i might be boonies or that this would become a 🐰 🕳

**Comment by bluefuton** [comment]
Sidenote: I think we should stop using the acronym SoM in issue and PR titles. @designsimply commented that she didn't know what it stood for, and nor will anyone outside Reader Squad, including any open source contributors.

**Pull request merged**
