### PR TITLE
Gutenberg: remove file block

### LINKED ISSUE #27640: Gutenberg: File Block
Verify if a file block is serialized as expected. Note that media uploads on Chrome (local env) will be cancelled.

In addition to that, the file block URL rendered on frontend are also incorrect. The file is pointing to something like https://wpcalypso.wordpress.com/19115187-8f88-4fc7-a40e-6fe12c18b3fa which is a non-existent Calypso page.

### PR DESCRIPTION
**Pull request by vindl**
#### Changes proposed in this Pull Request

File block can't work as expected on WP.com. We are removing it and
will be providing a custom replacement for it.

Please refer to D19851-code for more details.

#### Testing instructions

1. Navigate to http://calypso.localhost:3000/gutenberg/post
2. Verify that File block can't be added.
3. Verify that the rest of the editor works as expected.

Fixes #27640 (temporary fix until we create a custom version).

### CODE REVIEW

**Comment by gwwar** [comment]
Shall we try and coordinate this with another patch from @notnownikki and @georgeh ? We'll want our blocks to match with what's available in wp-admin.

**Comment by vindl** [comment]
Good point @gwwar! I checked this block in `wp-admin` and it works as expected - which was interesting since it wasn't before. Then I checked in Calypso and it works there too! 😄

I suspect someone came up with another way to fix it or... magic. 😄

**Comment by mmtr** [comment]
I guess we need to wait to see if we need to coordinate with wp-admin blocks before merging this 🙂

**Comment by Copons** [comment]
@vindl Just as a heads up: I don't really agree with this, and I'm trying to make my point on D19851-code. 🙂

**Comment by vindl** [comment]
> I guess we need to wait to see if we need to coordinate with wp-admin blocks before merging this 🙂

Since this is not live yet, I think it's safe to merge and wp-admin can catch up later (wp-admin version is similarly broken), but I'll wait for their response just in case.

> Just as a heads up: I don't really agree with this, and I'm trying to make my point on D19851-code. 🙂

Resolved this in the diff. :)

**Pull request merged**
