### PR TITLE
purchases: refactor tests to `@testing-library`

### PR DESCRIPTION
**Pull request by flootr**
#### Changes proposed in this Pull Request

Migrate the following test files to `@testing-library`

- client/me/purchases/billing-history/test/tax.js 
- client/me/purchases/purchase-item/test/index.jsx 
- client/me/purchases/track-purchase-page-view/test/index.js 
- client/me/purchases/manage-purchase/plan-details/test/billing-period.jsx

#### Testing instructions

* Make sure unit tests pass

Related to #63409

### CODE REVIEW

**Review by sirbrillig — APPROVED** [review]
Nice work! TIL about `renderWithProvder`. 

One question I have just for my own learning: is it preferable to use `test()` rather than `it()` in our code? I've been using `it()` because I find it more readable (eg: `it( 'upgrades to a yearly plan when the button is clicked' )`) and because I was used to that syntax from mocha, but I'm curious what other folks are doing.

**Comment by flootr** [comment]
> One question I have just for my own learning: is it preferable to use `test()` rather than `it()` in our code?

I don't think so. As they're both aliases for the same thing I guess it's totally fine to use either of them. Happy to revert those changes as that was more of an automated process without much thinking. 

I usually use `test` because to me it feels more intuitive but as you already said you can make a similar argument for `it`. I guess it's probably up to _how_ you want to describe on what you're doing in that test. No strong opinion on my side.

**Comment by sirbrillig** [comment]
Yeah, no strong opinion from me about using one over the other; I was just curious! Anyway, this still looks great. Thanks!

**Review by noahtallen — APPROVED** [review]
RTL changes look great to me!

**Review by tyxla — APPROVED** [review]
Great work 🚀

**Pull request merged**
