### PR TITLE
Test: Remove missed console.log in analytics tests

### PR DESCRIPTION
**Pull request by blowery**
To test, run `npm run test-client -- --reporter=min` and notice there are no statements about setting pixels at the start of the test run.

### CODE REVIEW

**Comment by blowery** [comment]
cc @umurkontaci , noticed while testing #4111

**Comment by gziolo** [comment]
:+1:

**Comment by blowery** [comment]
@gziolo thanks for merging! i love it when others shepherd my stuff out. :sheep: :raised_hands:

**Comment by gziolo** [comment]
You are welcome, I merged all ready to merge PRs and deployed in one batch. It's also much easier to deploy stuff when there is early morning in Europe ;)

**Pull request merged**
