### PR TITLE
Comments: Emojify all the things

### LINKED ISSUE #17636: Comments: Emojify all the things
Props to this issue #17541, this PR #17634 and the @Automattic/lannister Review Day for making me notice this.

We should use the `Emojify` component to make sure emojis in text look the same.

To put it in a visual context:

| Non-`Emojify`-ed | `Emojify`-ed |
| --- | --- |
| screen shot 2017-08-30 at 16 20 38 | screen shot 2017-08-30 at 16 20 43 |

The change is as simple as:
```js
import Emojify from 'components/emojify';

<Emojify>
  <p>{ content }</p>
</Emojify>
```
but we need to add in quite a lot of places.

- [x] Comment content in the expanded view
- [x] Comment content in the header
- [x] Author display name in the expanded view
- [x] Author display name in the header
- [ ] Author display name in the textarea placeholder
- [x] Author display name in the reply to area (where we also show the post title)
- [x] Post title in the aforementioned area
- [x] Post title in the header
- [x] Maybe in the author's site URL?
- [ ] Other places I missed?

### PR DESCRIPTION
**Pull request by Copons**
Close #17636

Adds the `Emojify` component to all places where we might need to convert emojis.

| Non-`Emojify`-ed | `Emojify`-ed |
| --- | --- |
| screen shot 2017-08-30 at 16 20 38 | screen shot 2017-08-30 at 16 20 43 |

There is one notable place missing: the reply textarea placeholder.
The `Emojify` component doesn't work on that because it replaces the emojis with ``s, and I'm unsure on how to proceed.

cc @Automattic/lannister 
(Please notice that unlike most of the m2 PRs, this goes straight to prod)

---

Author name, site URL, and post title in the comment header:
screen shot 2017-09-06 at 16 28 05

Comment excerpt in the comment header:
screen shot 2017-09-06 at 16 18 14

Parent comment author name and comment content in the expanded view:
screen shot 2017-09-06 at 16 18 22

Parent comment excerpt in the expanded view:
screen shot 2017-09-06 at 16 18 39

Parent post title in the expanded view:
screen shot 2017-09-06 at 16 18 46

Site URL in the expanded view:
screen shot 2017-09-06 at 16 28 47

### CODE REVIEW

**Comment by dmsnell** [comment]
Why do we need this? the _before_ shot looks better to me as it uses native emoji. seems like all of our supported browsers support emoji, don't they?

**Comment by rodrigoi** [comment]
@Copons the list on #17636 has a couple items missing, and I'm too lazy to crosscheck... but I think we are missing one (_Author display name in the textarea placeholder_)

**Comment by Copons** [comment]
@rodrigoi Yup, I mentioned it in the PR description (which is indeed quite messy to read!):

> There is one notable place missing: the reply textarea placeholder.
> The Emojify component doesn't work on that because it replaces the emojis with s, and I'm unsure on how to proceed.

@dmsnell The context, and inspiration for this PR, is this: https://github.com/Automattic/wp-calypso/issues/17541
Reader and Conversations converted the system emoji into a unified standard ([Twitter'](https://github.com/twitter/twemoji)s).
It just makes sense to me to make Comment Management emojis consistent with them.

**Comment by Copons** [comment]
Sorry guys, reverting to WIP for a bit.
I've spoken with the Reader Conversations peeps and it's better to keep `Emojify` as close as the strings as possible and there are a couple of cases I need to update.

**Comment by Copons** [comment]
Updated and tested.
It's also a wee bit smaller, which is always nice!

**Pull request merged**
