### PR TITLE
Logged-in Performance Profiler: Modify core web vitals to match mobile layout.

### PR DESCRIPTION
**Pull request by vykes-mac**
Closes https://github.com/Automattic/dotcom-forge/issues/9198

## Proposed Changes

* Add a new accordion component that matches the new design for mobile layout

## Why are these changes being made?

*

## Testing Instructions

* Go to `sites/performance/{site}` change to mobile layout and verify design

image

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Comment by vykes-mac** [comment]
cc: @matt-west

**Comment by matt-west** [comment]
Thanks @vykes-mac.

I think there’s a breakpoint issue. The mobile view looks great, but there’s an extra border and the status tag is misaligned when you go a little larger.

Screenshot 2024-09-23 at 09 28 04

**Comment by vykes-mac** [comment]
> I think there’s a breakpoint issue. The mobile view looks great, but there’s an extra border and the status tag is misaligned when you go a little larger.

@matt-west at this tablet size, shout it look the same as mobile ? should the status and recommendations be beside each other?

**Comment by matt-west** [comment]
@vykes-mac Yep. Once the tabs change to the single-column accordion layout, we should use the mobile styles.

**Pull request merged**
