### PR TITLE
Build: Make webpack module IDs more stable

### PR DESCRIPTION
**Pull request by blowery**
Use the `webpack-stable-module-id-and-hash` plugin to help webpack generate stable module IDs and better chunk hashes.

Prior, we were using the `OccurenceOrderPlugin`, which assigns module IDs by frequency of occurrence. This kept module ids mostly stable, but there was a catch. Webpack generates the hash for a chunk based on the contents of the chunk, but sometimes does not update the hash of the chunk when only module IDs change.  ( https://github.com/webpack/webpack/issues/1856 )

This means that if the module IDs generated by `OccurenceOrderPlugin` change because we use a module slightly more often, or introduce a new module that's used > 1 place, the hashes of the chunks that reference the module will not change and our CDN won't get the new file.

Refs:
https://github.com/webpack/webpack/issues/1856
https://github.com/webpack/webpack/issues/1315
https://github.com/zhenyong/webpack-stable-module-id-and-hash

### CODE REVIEW

**Comment by samouri** [comment]
Beyond basic building....how can we test this?

**Comment by blowery** [comment]
> Beyond basic building....how can we test this?

Yup! These are kind of a pain. 

Do these both on master and on this branch.

1. Do a build `CALYPSO_ENV=wpcalypso make build`
2. Save the output
3. Open up something branchy. I liked using `async-load-blocks-reader-full-post.js` (in `public`)
4. Take a peek at the module IDs being required
5. Find something that's not included much. `query-reader-related-posts` was my candidate. 
6. import that module in a leaf that doesn't already include it. stats is a good candidate.
7. Rebuild
8. Open up `async-load-blocks-reader-full-post.js` again and take note of the module ID and the chunk hash for the full post chunk.

With the branch, the module ID should not change. With master, it will. If it doesn't, import it in another chunk.

On master,

**Comment by samouri** [comment]
Ok, it took a couple reads but I think I understand how to test this now.  It'll take a bit but I'll start testing now.

**Comment by blowery** [comment]
There's another way to test this. 

1. run a build, move all of the js files in public to a `before` directory
2. clean
3. upgrade to react-redux@5 😄 
4. run a build, move all of the js files in public to a `after` directory
5. run `diff -rqu before after | grep -e "^Files"`. Shouldn't see any output.

**Comment by blowery** [comment]
@ockham as an experiment, can we rebase the react-redux@5 PR on top of this one and see if it fixes the problems we saw?

**Comment by blowery** [comment]
Ran the experiment I suggested. Didn't work the first time, because we were still using `OccuranceOrderPlugin` for vendor. Fixed that in https://github.com/Automattic/wp-calypso/pull/11437/commits/a636c678719ef2a1eca6c5e581215dbf844bbbea, re-ran the tests. No files with the same hash and different contents!

Here's what I ran for reference:
```
# make sure upgrade/react-redux-take-four and try/webpack/hashed-module-ids are up to date
git co upgrade/react-redux-take-four
git rebase try/webpack/hashed-module-ids
# fix conflict by regenerating shrinkwrap
git co try/webpack/hashed-module-ids
CALYPSO_ENV=production make build
cp -r public before
git co upgrade/react-redux-take-four
make clean
CALYPSO_ENV=production make build
cp -r public after
diff -rqu before after
```

**Comment by ockham** [comment]
Here's what I get with those commands:

```
Only in after: manifest.7a52a9c221482608213c.js
Only in after: manifest.7a52a9c221482608213c.m.js
Only in before: manifest.ec773d2ae86769cc006d.js
Only in before: manifest.ec773d2ae86769cc006d.m.js
Files before/style-debug.css and after/style-debug.css differ
Files before/style-debug.css.map and after/style-debug.css.map differ
Files before/style-rtl.css and after/style-rtl.css differ
Files before/style.css and after/style.css differ
Only in after: theme.0-53-49dd7fd78fda240.js
Only in after: theme.0-53-49dd7fd78fda240.m.js
Only in before: theme.0-53-7a3a6b79abb4a8d.js
Only in before: theme.0-53-7a3a6b79abb4a8d.m.js
Files before/vendor.production.js and after/vendor.production.js differ
Files before/vendor.production.m.js and after/vendor.production.m.js differ
```

So this is looking good. Calypso also still runs. Not sure what else to test...
Merge it, then? 😄 (Maybe early next week rather than now.)

**Comment by ehg** [comment]
> Prior, we were using the OccurenceOrderPlugin, which assigns module IDs by frequency of occurrence. This kept module ids mostly stable, but there was a catch. Webpack generates the hash for a chunk based on the contents of the chunk, but sometimes does not update the hash of the chunk when only module IDs change.

Just noting that `OccurenceOrderPlugin` is on by default in webpack2. So this approach may or not work :)

**Comment by blowery** [comment]
> Just noting that OccurenceOrderPlugin is on by default in webpack2. So this approach may or not work :)

On 2, we could use the new https://github.com/webpack/webpack/blob/master/lib/HashedModuleIdsPlugin.js. Since OOP is on by default, adding this to the plugin chain _should_ override what OOP does.

**Pull request merged**
