### PR TITLE
Gutenboarding: Add polyfill

### LINKED ISSUE #38336: Gutenboarding: Ensure polyfills are loaded
Ensure polyfills are loaded in the Gutenboarding entrypoint.

Expected around here:

https://github.com/Automattic/wp-calypso/blob/a809d465aace0c9f691a8667ed1f2006fd5581ef/client/landing/gutenboarding/index.ts#L1-L5

Like other entrypoints:

https://github.com/Automattic/wp-calypso/blob/a809d465aace0c9f691a8667ed1f2006fd5581ef/client/landing/login/index.js#L1-L4

via @sgomes p1575997865196100-slack-luna (thanks!)

### PR DESCRIPTION
**Pull request by sirreal**
Closes #38336 (thanks @sgomes)

#### Changes proposed in this Pull Request

* Add the polyfill to the entrypoint.

#### Testing instructions

* Polyfills are included in the fallback bundle.

### CODE REVIEW

**Comment by simison** [comment]
Feels like we need a "howto separate entrypoint" docs that mention all the little things we shouldn't forget. 😁

**Comment by sirreal** [comment]
> **App Entrypoints** (~12686 bytes added 📈 [gzipped])
> 
> ```
> name                   parsed_size           gzip_size
> entry-gutenboarding       +52948 B  (+2.1%)   +11995 B  (+1.8%)
> entry-main                 +1061 B  (+0.1%)     -119 B  (-0.0%)
> entry-domains-landing       +142 B  (+0.0%)     +436 B  (+0.3%)
> entry-login                  +28 B  (+0.0%)     +374 B  (+0.1%)
> ```
> 
> Common code that is always downloaded and parsed every time the app is loaded, no matter which route is used.
> 
> **Sections** (~198870 bytes added 📈 [gzipped])
> 
> ```
> name         parsed_size            gzip_size
> post-editor    +489276 B  (+34.1%)  +124997 B  (+31.3%)
> plugins        +104552 B  (+28.5%)   +24310 B  (+25.8%)
> import          +82609 B  (+65.9%)   +21314 B  (+66.5%)
> email           +71597 B  (+33.7%)   +14477 B  (+25.0%)
> concierge       +62787 B  (+26.9%)   +16268 B  (+30.4%)
> hosting          -8297 B   (-3.4%)    -2496 B   (-3.8%)
> ```

Whoa, @sgomes / @jsnajdr this is surprising for me, can you make sense of it?

**Comment by sgomes** [comment]
> Whoa, @sgomes / @jsnajdr this is surprising for me, can you make sense of it?

Neither of those looks right.

The bot measures the evergreen build, and there almost all polyfills should be getting aliased to `noop` through webpack (with the exception of the `globalThis` polyfill). Therefore, the bump up in size for the `gutenboarding` entry point is way too big.

As for the sections, those shouldn't be getting affected at all.

@jsnajdr: what do you think? I'm leaning towards a bug in the bot.

**Comment by sgomes** [comment]
I'm currently building the previous commit (dc7b6618d24e48c126de41a974bee67fc1a36667) on `calypso.live` to manually compare sizes between the two.

**Comment by sgomes** [comment]
> I'm currently building the previous commit as per your branch ([dc7b661](https://github.com/Automattic/wp-calypso/commit/dc7b6618d24e48c126de41a974bee67fc1a36667)) on `calypso.live` to manually compare sizes between the two.

Edit: the entry point bump appears to be real. The section ones not so much.

**Comment by jsnajdr** [comment]
The `post-editor` and `plugins` chunks didn't really change at all. Their hashes and stat sizes are the same before and after, and it's only the parsed and gzip sizes that changed.

The first two items are read from webpack build stats, the second two items are read from the built file on file system.

I don't know what happened -- maybe some weird bug in `webpack-analyze-bundles`?

**Comment by sgomes** [comment]
It does look like the 11KB bump in the entry point is real, though. It appears that after this change, the vendors files for all `login`, `main` and `gutenboarding` have merged, resulting in a larger download for `gutenboarding`.

The difference appears to mostly be a bunch of `core-js` stuff, which is odd, since this is the evergreen build. My guess is that dependencies are explicitly pulling this stuff in, instead of relying on it to be polyfilled or shimmed. @jsnajdr: Does that ring a bell, from when you were looking at `core-js` stuff?

**Comment by sirreal** [comment]
Rebased, curious to see if ICFY changes.

**Comment by sgomes** [comment]
> Rebased, curious to see if ICFY changes.

Looks like the results are easier to grok this time around. The gutenboarding entry point gets a 12KB bump. This may go down in the future as we switch Calypso and some opinionated dependencies to `core-js@3`, but in the meantime may go up further still. See #38660

**Comment by simison** [comment]
`core-js@3` is in, do we need changes here or is this good to go?

**Comment by jsnajdr** [comment]
> `core-js@3` is in, do we need changes here or is this good to go?

You can just `import '@automattic/calypso-polyfills'` now.

`client/boot/polyfills` also includes a polyfill for `localStorage` that uses a memory-only store when `localStorage` is not available (old Safaris in private mode). I'm not sure if Gutenboarding needs this. I'd recommend avoiding `localStorage` in new projects.

**Comment by sirreal** [comment]
I've rebased and applied the suggestion to use `@automattic/calypso-polyfills`.

> `client/boot/polyfills` also includes a polyfill for `localStorage` that uses a memory-only store when `localStorage` is not available (old Safaris in private mode). I'm not sure if Gutenboarding needs this. I'd recommend avoiding `localStorage` in new projects.

We use `@wordpress/data` persistence, which relies on `localStorage` but has what seems to be a fallback mechanism similar to what you're describing:

https://github.com/WordPress/gutenberg/blob/master/packages/data/src/plugins/persistence/storage/default.js

I suspect we're fine without `client/boot/polyfills`.

**Comment by sirreal** [comment]
I've just verified polyfill inclusion, the fallback build includes ~20 lines of polyfill modules and the evergreen build includes ~50 lines of polyfill modules.

This should be good to land. The diffs on ICFY also look more sensible.

**Comment by sgomes** [comment]
> the fallback build includes ~20 lines of polyfill modules and the evergreen build includes ~50 lines of polyfill modules

Is it maybe the other way around? I'd be concerned if evergreen includes more polyfills

**Review by jsnajdr — APPROVED** [review]
Looks good!

By the way, it seems that the `landing/domains` entrypoint doesn't include any polyfills and is likely to fail in IE11. I'll try to address that in its own PR.

**Comment by sirreal** [comment]
> Is it maybe the other way around? I'd be concerned if evergreen includes more polyfills

Definitely, the other way around! 😅

**Pull request merged**
