### PR TITLE
Framework: Try out dumping junit style logs

### PR DESCRIPTION
**Pull request by blowery**

### CODE REVIEW

**Comment by blowery** [comment]
cc @gziolo @aduth 

Tried this out, but circle doesn't like it much. Think we need to wait for the single runners.

**Comment by gziolo** [comment]
It doesn't show reporter change prompt, but number of tests doesn't seem to be correct:

screen shot 2016-03-09 at 21 16 44

**Comment by blowery** [comment]
Huh, that's better than what I saw during testing! 

I wonder if it doesn't like all the nested dirs and needs to be flat? Easy to do with the consolidated runners. Not as easy with the current structure.

**Comment by gziolo** [comment]
Maybe we should skip `server/Makefile` and `client/Makefile` when on Circle CI and run them independently from `circle.yml`. Just to check if that would work. What do you think? :)

**Comment by gziolo** [comment]
Based on this PR I managed to setup JUnit reporter on CircleCi in #4038. I found a way to combine outputs for client and server single runners :)

**Comment by blowery** [comment]
woo! closing this one.

**Pull request closed without merging**
