### PR TITLE
Reader: Fix a few places where we use tracks directly

### PR DESCRIPTION
**Pull request by blowery**
Use reader/stats/recordTrack instead to inject the subscription count

### CODE REVIEW

**Comment by bluefuton** [comment]
Related to #3517 .

**Comment by bluefuton** [comment]
Events to check:

- [ ] calypso_reader_infinite_scroll_performed
- [ ] calypso_reader_blog_preview
- [ ] calypso_reader_tag_loaded
- [ ] calypso_reader_list_loaded
- [ ] calypso_reader_discover_viewed
- [ ] calypso_reader_unblock_site
- [ ] calypso_reader_site_followed
- [ ] calypso_reader_site_unfollowed

**Comment by bluefuton** [comment]
Looks good.

Noticed while testing that `calypso_reader_block_site` does not fire an event - worth adding one while we're at it?

**Comment by blowery** [comment]
> Noticed while testing that calypso_reader_block_site does not fire an event - worth adding one while we're at it?

Done

**Comment by bluefuton** [comment]
Looks good! :shipit:

**Pull request merged**
