### PR TITLE
Add in a border to the search input

### PR DESCRIPTION
**Pull request by blowery**
match up the color with the card borders used by other search components around the site

Test live: https://calypso.live/?branch=add/reader/border-on-search-input

### CODE REVIEW

**Comment by blowery** [comment]
cc @fraying

**Comment by blowery** [comment]
before
search_ _reader_ _wordpress_com

after
search_ _reader_ _wordpress_com

**Comment by blowery** [comment]
unreverts #6776, implements #6476 with standard colors in a safe way

**Comment by rickybanister** [comment]
How come this is necessary, way back when I thought you just stuck the search component inside a card to achieve this?

**Comment by blowery** [comment]
@rickybanister that's exactly what i ended up doing?

**Comment by rickybanister** [comment]
Sorry! I was hasty and didn't look at the code, for some reason I misread this to mean copying the shadow css to the search component. As you were :|

**Comment by mtias** [comment]
@blowery @rickybanister we have `SearchCard` precisely for this purpose. (<a href="https://wpcalypso.wordpress.com/devdocs/design/search">See the two in devdocs</a>.)

**Comment by rickybanister** [comment]
Yes, that's what I was thinking of!

**Pull request merged**
