### PR TITLE
Add 2 year breakdown to Akismet checkout

### PR DESCRIPTION
**Pull request by CodeyGuyDylan**
## Proposed Changes

* Generalize the filenames of the updated 2 year breakdown design to encompass more than just Jetpack
* Show updated breakdown of 2 year plans on Akismet checkout

## Testing Instructions

1. Checkout this branch or use the Calypso Live link
2. Checkout this diff on WPCOM: D125628-code
3. In your 0-sandbox.php file, add the following line
```
lang=php
define( 'USE_STORE_SANDBOX', true );
```
4. Go to any of the Akismet 1 year plans or monthly plans in checkout (ex. `/checkout/akismet/ak_plus_yearly_2`)
5. Make sure the 2 year breakdown shows up and that it correctly switches the plan to the bi-yearly plan which the CTA is clicked
image
image

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

**Review by elliottprogrammer — APPROVED** [review]
Tested & works well as described. Code looks all good.

Nitpick on the name though...  `NewCheckoutSidebarPlanUpsell` 🧐
Adding "new" to a function and file name just doesn't seem like good naming convention and not descriptive at all, however I don't really know what would be better.. 🤔
`JetpackAkismetCheckoutSidebarPlanUpsell`?  Although long and maybe too specific? 🤷‍♂️

I don't know, I guess it's fine, not a big deal... Maybe it just my OCD subconsciously nagging at me. 😆
I'm going to approve and leave it to your own judgement. 👍🙂
LGTM! 👍

**Comment by CodeyGuyDylan** [comment]
> Nitpick on the name though... `NewCheckoutSidebarPlanUpsell` 🧐 Adding "new" to a function and file name just doesn't seem like good naming convention and not descriptive at all, however I don't really know what would be better.. 🤔 `JetpackAkismetCheckoutSidebarPlanUpsell`? Although long and maybe too specific? 🤷‍♂️

I actually really don't like it either 😅 , however the old one still exists and is being used on wpcom checkouts and I did think `JetpackAkismetCheckoutSidebarPlanUpsell` sounded unnecessarily long, and if we ever added it to some other checkout we'd have to add that as well. I am not sure, I might try and think of a better one before merging

**Comment by elliottprogrammer** [comment]
> however the old one still exists and is being used on wpcom checkouts and I did think JetpackAkismetCheckoutSidebarPlanUpsell sounded unnecessarily long, and if we ever added it to some other checkout we'd have to add that as well.

Yes totally, because those exact same reasons I couldn't easily think of an alternative name either. 😉 👍

**Review by elliottprogrammer — APPROVED** [review]
LGTM! 👍

**Pull request merged**
