### PR TITLE
Site Migration: Update Plans page for migrations flow

### PR DESCRIPTION
**Pull request by sixhours**
## Proposed Changes

* Add monthly and biennial plans to the importer upgrade step, shown only when the `migration-flow/experiment` feature flag is `true`.
* Since the upgrade step is mostly hard-coded to the Business plan, this adds panels on either side of the main plan with monthly and biennial plan details.
* Updates the loader to better resemble the new content being loaded.
* Lots of visual tweaks to better match the mockup at ay0fZYgdXxPDbZbgPlz3hu-fi-1_3529
* **Still to do**: Consider this a first draft, please. :) Updating tests, making any visual tweaks, etc. still need to be done.

## Why are these changes being made?

* p9Jlb4-fiH-p2 

## Testing Instructions

* Switch to this branch locally or via calypso.live
* Set the feature flag in session storage via the console and reload: `window.sessionStorage.setItem('flags', 'migration-flow/experiment');`
* Go through the migration flow until you get to the upgrade step
* It should look like this with the flag enabled:

calypso localhost_3000_setup_site-migration_site-migration-upgrade-plan_siteId=239588599 siteSlug=testing2026 wordpress com from=https%3A%2F%2Fthemeflailing mystagingwebsite com%2F destination=upgrade how=myself (1)

* Ensure the Monthly/Yearly/Biennially buttons add the correct products to the cart, respectively, and the prices match.
* Disable the flag in session storage: `window.sessionStorage.setItem('flags', false);` and reload the screen.
* You should see the original screen, and it should work as expected:

Screenshot 2024-12-04 at 3 09 18 PM

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
    - [ ] For UI changes, have we tested the change in various languages (for example, ES, PT, FR, or DE)? The length of text and words vary significantly between languages. 
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Comment by fditrapani** [comment]
Thanks for getting this started @sixhours! I saw your comments about the visual tweaks so I'll hold off on those comments. I don't know if you caught this but the back button covers some of the content on mobile. We might need to artificially add some space to account for it:

image

**Comment by sixhours** [comment]
@fditrapani I'll take a look! Feel free to hit me up with any other visual feedback, too.

I had a question about the refund copy placement; it changes depending on the frequency (monthly gets up to 7 days, the others up to 14 days) so I left it in the old spot. Let me know if that should move.

I also wasn't sure if you wanted the plan details auto-expanded like they are right now or not.

**Comment by andres-blanco** [comment]
This is coming along nicely @sixhours !
I noticed screen flicker between the skeletons. Maybe this is due to Calypso not picking up the feature flag on time, but worth looking into it.

https://github.com/user-attachments/assets/4dfdd176-8853-4501-939c-03be5622ef4e

I've also added the string freeze label so translation starts

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/17047877

Some locales (Hebrew, Japanese) have been temporarily machine-translated due to translator availability. All other translations are usually ready within a few days. Untranslated and machine-translated strings will be sent for translation next Monday and are expected to be completed by the following Friday.

Thank you @sixhours for including a screenshot in the description! This is really helpful for our translators.

**Comment by fditrapani** [comment]
> I noticed screen flicker between the skeletons. Maybe this is due to Calypso not picking up the feature flag on time, but worth looking into it.

I didn't see this extra state because mine loaded before it flipped. I agree that we need to not show the old layout. 

> Feel free to hit me up with any other visual feedback, too.

Sure. I'll let you get things closer to finished before getting too fine grained but there were alignment issues and the contents of the plans, and offers, need to be updated for the migration audience. Let me know if you want to pair on a session to go through this stuff together. Happy to do it on a call if it's easier.

> I had a question about the refund copy placement; it changes depending on the frequency (monthly gets up to 7 days, the others up to 14 days) so I left it in the old spot. Let me know if that should move.

Good catch. I didn't notice that. What if we add a "feature" for the refund duration and make the copy below generic like this:
image


> I also wasn't sure if you wanted the plan details auto-expanded like they are right now or not.

I'm fine with leaving that out since I cherry picked the top features this audience. We recently updated our regular plan onboarding flow to show less features and it did better than showing everything.

**Comment by sixhours** [comment]
@fditrapani I think this is ready for another look 👀  :) 

The features are currently served from the same set of feature constants we use for all plans for consistency. If we want to customize them for migrations we'll probably need to hard-code them just for this screen.

**Comment by fditrapani** [comment]
Thanks @sixhours! I don't mind if we do it in a separate PR but let's go ahead and customize them for here only. There are specific differences we want to call out for each option and I hand picked the features to cater to our migration audience too.

**Comment by fditrapani** [comment]
I can take a closer look at the updates a little later today or by tomorrow the latest!

**Comment by sixhours** [comment]
@fditrapani Is the annual savings % discount mentioned in the features consistent or is it dependent on the currency/location? 🤔

**Comment by fditrapani** [comment]
> @fditrapani Is the annual savings % discount mentioned in the features consistent or is it dependent on the currency/location?

That's a good question! @bohdankit07 @niranjan-uma-shankar would either of you know if our annual discounts are consistent across currencies?

**Comment by fditrapani** [comment]
Nice work on this @sixhours! I found two minor things:

1. There's a weird alignment issue that's causing things to be off ever so slightly:
  image
  It's weird because it corrects itself and then goes out of alignment again.

2. The main CTA is using an off white colour:
    image

**Comment by bohdankit07** [comment]
@sixhours, when you say 'consistent', do you mean that discounts are always 50%? They should be because there is no reason for it to be different since we do not offer localized pricing.

**Comment by sixhours** [comment]
> @sixhours, when you say 'consistent', do you mean that discounts are always 50%? They should be because there is no reason for it to be different since we do not offer localized pricing.

Yep, I think that answers my question. If we don't offer localized pricing then the 52% annual savings per year Biennially and 39% annual savings per year Yearly should be the same across currencies. Thank you!

**Comment by sixhours** [comment]
@fditrapani Great eye (as always); I've fixed those!

**Comment by fditrapani** [comment]
@sixhours looks like the annual discount does change from currency to currency:

here's the Canadian dollar:
image

Here's USD:
image

and here's the Australian dollar:
image

**Comment by fditrapani** [comment]
> @fditrapani Great eye (as always); I've fixed those!

No problem. Thanks for the updates! This is looking great. I have one last comment about the skeleton loader, I think the blue draws too much attention. Can we keep the loaders all gray?

**Comment by sixhours** [comment]
> @sixhours looks like the annual discount does change from currency to currency:

D'oh, I worried about that. OK, I'll see if there's a magic formula somewhere so we can make sure those get calculated correctly.

>  Can we keep the loaders all gray?

Sure thing!

**Review by andres-blanco — APPROVED** [review]
LGTM! I removed the String Freeze label since this will be deployed behind a feature flag. We should make sure that everything is translated when this is shipped.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/17047877).

**Pull request merged**
