### PR TITLE
Reader: Add treatment for featured image captions

### PR DESCRIPTION
**Pull request by kjellr**
When a featured image has a caption assigned to it, we'd like to display it in the Reader. Oftentimes these captions include image attribution/licensing details that should be displayed alongside the featured image.

We'd definitely like to do this for the A8C Editorial blogs (En.Blog, Discover, Longreads, The Daily Post), but we should also consider whether it makes sense to apply this to all blogs.

NOTE: I've hardcoded the captions to start off with — we'll need to hook that up. :) 

## Screenshots: 

image-captions--stream

image-captions--full-post

## Test: 

Visit the Discover stream, and view the post illustrated above: 
http://calypso.localhost:3000/read/feeds/41325786?at=2016-03-28T17:00:00Z
http://calypso.localhost:3000/read/blogs/53424024/posts/11801

### CODE REVIEW

**Comment by blowery** [comment]
@kjellr How do you add a caption to a featured image? AFAIK it's just an image URL in the API response...

**Comment by kjellr** [comment]
@blowery Yeah, I hadn't checked, but that's not surprising. In themes, we typically grab the caption by a bit of a roundabout way — usually something like `get_post( get_post_thumbnail_id() )->post_excerpt;`

If these would need to be added to the API, I'm guessing that's a bunch more work?

**Comment by blowery** [comment]
> If these would need to be added to the API, I'm guessing that's a bunch more work?

It's work, but it's probably not too bad. Is this a common thing to do?

**Comment by kjellr** [comment]
It is for all the Automattic editorial blogs. For example: 

- En.Blog (caption in the bottom right): https://en.blog.wordpress.com/2015/01/13/nine-world-photos/
- Discover (caption in the bottom left): https://discover.wordpress.com/2016/04/07/tressie-mcmillan-cottom/
- The Daily Post (caption below the subhead): https://dailypost.wordpress.com/2016/03/24/blogging-wisdom/
- Longreads (caption in the bottom left): https://blog.longreads.com/2016/04/12/fans-fiction-and-representation-a-new-hope/

Those are all stored as captions on the featured image, and pulled in from there.

I asked the VIP team if any of our clients use something similar, and it sounds like it's all over the place... some use captions, some use post meta, some use attachment meta, some post the credit in the post body, etc. Unfortunately featured image credits aren't really standardized at this point. 😞

**Comment by folletto** [comment]
Kjell mentioned there's a new design upcoming, so given this PR also has conflicts, better close it and reopen later once the design is finalized.

**Pull request closed without merging**
