### PR TITLE
Sign Up: Return to `/sites` when that's the original source

### PR DESCRIPTION
**Pull request by danielbachhuber**
From https://github.com/Automattic/wp-calypso/pull/68545#issuecomment-1267587338

## Proposed Changes

If a user with one site enters the signup flow from `source=sites-dashboard`, always show 'Back to Sites':

image

However, if they enter the signup flow from elsewhere, default to 'Back to My Home':

image

## Testing Instructions

1. Sign in as a WordPress.com user with one site.
2. From My Home Sidebar, click 'Add new site'.
3. Verify the back button appears as 'Back to My Home'.
4. Navigate to `/sites` and click 'Add new site'.
5. Verify the back button appears as 'Back to Sites'.

### CODE REVIEW

**Comment by wojtekn** [comment]
@danielbachhuber it fixes this issue for me. Before the change, I could use confusing flow:

1. Log in to a WP.com account that has only one site
2. Open `/sites`
3. Click "Add new site" button
4. click "Back to My Home"
5. I landed on a `/home` which is a different page than I started on.

With your fix, it works fine:

1. Log in to a WP.com account that has only one site
2. Open `/sites`
3. Click "Add new site" button
4. Click "Back to Sites"
5. I landed on `/sites`

However, now when I continue the previous steps, I observe an unusual workflow. It looks as follows:

1. Log in to a WP.com account that has only one site
2. Open `/sites`
3. Click "Add new site" button
4. Click "Back to Sites"
5. I landed on `/sites`
6. Click on the single site on `/sites`
7. I land on my site's home
8. Click "Add new site" button in the sidebar
9. Click "Back to Sites" (I would expect to see "Back to My Home" now)
10. I landed on `/sites` instead of `/home`

The problem goes away when I refresh the page in the browser after the "7. I land on my site's home" step.

Another thing is that I still; experience behavior from 901-gh-Automattic/dotcom-forge:

1. Log in to a WP.com account that has multiple sites
2. Open a single site's home page
3. Click on My Sites -> Switch site
4. Click "Add new site" button
5. Click "Back to Sites"
6. I landed on `/sites` instead of my site's `/home`

**Comment by danielbachhuber** [comment]
> However, now when I continue the previous steps, I observe an unusual workflow. It looks as follows:

@wojtekn Interesting! This is probably some artifact of the signup logic, given my code doesn't touch that at all. I can't imagine a user will encounter it all that often either. Also, because they've already visited 'Sites' once, it's probably fine to send them back there.

> Another thing is that I still; experience behavior from https://github.com/Automattic/dotcom-forge/issues/901:

I only changed the behavior for a user with a single site. However, maybe we always want the back button to appear as 'Back to My Home' when the user clicks 'Add new site' from the My Home Sidebar?

@p-jackson @vindl Thoughts?

**Comment by vindl** [comment]
> I only changed the behavior for a user with a single site. However, maybe we always want the back button to appear as 'Back to My Home' when the user clicks 'Add new site' from the My Home Sidebar?

Yes, that's what I would expect when clicking on that button, or in general, to take me back to the screen I came from.

**Comment by danielbachhuber** [comment]
> > I only changed the behavior for a user with a single site. However, maybe we always want the back button to appear as 'Back to My Home' when the user clicks 'Add new site' from the My Home Sidebar?
> 
> Yes, that's what I would expect when clicking on that button, or in general, to take me back to the screen I came from.

Sounds good.

@wojtekn In 5808cb93f6a37c3ab8b406279d507e72e4b03615, I added `source=my-home&siteSlug=${ siteSlug }` to the Site Selector's 'Add new site' in order to trigger the 'Back to My Home' experience.

**Comment by danielbachhuber** [comment]
> Interesting! This is probably some artifact of the signup logic, given my code doesn't touch that at all.

@wojtekn Even more terrifying:

image

**Comment by wojtekn** [comment]
> @wojtekn In https://github.com/Automattic/wp-calypso/commit/5808cb93f6a37c3ab8b406279d507e72e4b03615, I added source=my-home&siteSlug=${ siteSlug } to the Site Selector's 'Add new site' in order to trigger the 'Back to My Home' experience.

Thanks, it works fine now for both single and multiple sites accounts.

> This is probably some artifact of the signup logic, given my code doesn't touch that at all. I can't imagine a user will encounter it all that often either. 

Right, it may be some artifact and the use case may be rare.

**Review by wojtekn — APPROVED** [review]

**Pull request merged**
