### PR TITLE
Classic Editor: show scheduled post date with site's timezone

### LINKED ISSUE #30533: Post Scheduler Geolocates Publish Time Without Warning (Regardless of Site Time Zone Settings)
#### Steps to reproduce
1. Starting at URL: My Sites in Calypso (any site will work)
2. Go to Settings 
3. Adjust your site's time zone to be a different time zone than the one you're currently in.
4. Create a blog post.
5. Schedule that post to be published in your site's time zone.
6. Calypso geolocates your time in a scheduled post, which means if you're traveling (somewhere outside of your typical/site timezone), you're going to see your time zone when scheduling a post vs your site's time zone. 
7. Requires discovering that your post scheduler is geolocating (there's no warning), then doing the time conversion to schedule a post when you'd actually like it to be scheduled.

#### What I expected
When scheduling a post, for the scheduler to either show my site's time zone, as opposed to my geolocated time zone, or to have a notification/conversion assistance to let the user know that the post schedule time is geolocated, and they'll need to adjust accordingly if they want the post to be scheduled at the site's time zone.

#### What happened instead
The Calypso post scheduler geolocates your time zone, which causes confusion when you're trying to schedule a post to go live based on your site's time zone. You then have to do a conversion to publish the post at your local time zone, converted to your site's time zone.

#### Browser / OS version
All.

#### Context / Source
Optional: share your unique context to help us understand your perspective. You can add context tags such as:  #anxiety  #stresscase #painpoint.

We'd also love to know how you found the bug: #user-report

A user is currently in Singapore on a trip. Their typical home/site is based in London, and they needed to schedule a post to be published at 11am the next day in London's time zone.

Since they're in Singapore, Calypso's post scheduler was geolocating (without telling them) their time zone to Singapore time. So they were scheduling posts in Singapore time (+8) instead of their site's time zone (0), and couldn't find out why their posts were not going to be published at the correct time.

So they had to figure out they were being geolocated, do a manual time conversion, and then schedule posts in Singapore time adjusted for the time they'd like them to be published in London time, even though their site settings are set to London time.

There should be a notification/time conversion available in the post scheduler to let users know specifically what time a post is going to be published vs their site's time zone. It's currently geolocating without telling the user. 

Or, the post scheduler should remain consistent with the time zone set in the site's settings.

### LINKED ISSUE #32173: Editor: Remove or Clarify UTC Time When Scheduling Posts
#### Steps to reproduce
1. In Calypso classic, go to My Site > Blog Posts > Add to create a post.
2. Schedule the post to be published more than 7 days in advance.

#### What I expected

I expected the post's scheduled time to match the timezone in My Site > Settings.

#### What happened instead

If the post is scheduled more than 7 days in advance, only UTC time is shown in the scheduler. There is a small message about this below the UTC time, but it's still confusing.

If the post is scheduled within 7 days, the site's time also appears above the scheduling calendar. This helps a bit, but it's still confusing. The different behaviours depending on how far in advance the post is scheduled also add to the confusion.

#### Screenshot / Video

https://cld.wthms.co/I4tFSb

#### Context / Source

This has been reported by multiple WP.com customers who are **very** confused. They think the posts are being published at the wrong time, and that the scheduled time cannot be changed.

Either changing UTC to their site's timezone or always displaying their site's time above the scheduling calendar (instead of only for posts scheduled within 7 days) would make this more clear.

#user-report #painpoint

### PR DESCRIPTION
**Pull request by jsnajdr**
Fixes the Publish Date control to display the scheduled time in the site's timezone.

Before this fix, the date was in the local timezone. Notice the 9h difference on the following screenshot:

Screenshot 2019-04-10 at 15 53 44

After the fix, both dates are in sync:

Screenshot 2019-04-10 at 14 37 17

There are also few drive-by fixes:
- ignore ESLint a11y warnings
- convert ref to `React.createRef`
- use `withLocalizedMoment` to ensure `this.props.moment` is available

Fixes #32173 and #30533.

### CODE REVIEW

**Review by blowery — APPROVED** [review]
LGTM! Thanks!

**Review by blowery — CHANGES_REQUESTED** [review]
Actually, if I update the date on an already published post, the dates get out of sync. Is that expected? The date at the top is showing my local time, while the picked date and time are in the site's TZ. I kinda find that handy, but I'm not sure it's what we expect to happen.

Screen Shot 2019-05-07 at 4 03 30 PM

**Comment by jsnajdr** [comment]
> Actually, if I update the date on an already published post, the dates get out of sync.

@blowery I revived and rebased this old PR, because the bug reports keep coming. But I can't reproduce the out-of-sync dates on your screenshot. No matter what I do, both dates are always in sync. Can you try again? Maybe something else has changed since May.

**Comment by blowery** [comment]
> Can you try again? Maybe something else has changed since May.

It's still doing it, but I think it's fine. The entry box and calendar appear to be in the site's TZ and the little display in the dropdown section appears to be in my local TZ.

**Comment by jsnajdr** [comment]
> The entry box and calendar appear to be in the site's TZ and the little display in the dropdown section appears to be in my local TZ.

If the bug is still happening, can you post the precise steps to reproduce? It's important to know what was the exact workflow: is the post new, is it an existing draft, is it already published, or already scheduled and you are rescheduling, or some different state. All these state transitions have subtle details and different bugs 🙂

**Comment by blowery** [comment]
Some notes from testing this more:
- I can only repro it when the site has a TZ of UTC-0. Any other TZ and the times match what I enter. This is easiest to see if you schedule the post within a week of the current time, as it then shows both the date and the time. It would be nice if it always did this...
- Tangential, but if you change your site TZ via the Settings page, you have to reload Calypso before the classic editor picks it up

**Comment by jsnajdr** [comment]
> Some notes from testing this more:

These seem to be unrelated bugs:
- the WP.com server seems to not understand "UTC+0" as a valid timezone at all. The REST request to update settings has param `timezone_string: "UTC+0"`, but the response returns `timezone_string: ""`. And the empty value is really saved in the site settings
- we have site settings at two places in Redux: `state.sites.items[ siteId ].options` and `state.siteSettings.items[ siteId ]`. And they get out of sync when updating the settings -- the version in `state.sites` is not updated. We'll need to patch the reducer to handle the `SITE_SETTINGS_RECEIVE` action better.

My proposal is to approve and merge this one and file and fix the bugs you found as separate issues. What do you think @blowery?

**Comment by jsnajdr** [comment]
Closing because the classic Calypso Editor is going to be deprecated in just a few days.

**Pull request closed without merging**
