### PR TITLE
Create a P2 block pattern: New marketplace product

### PR DESCRIPTION
**Pull request by gcsecsey**
#### Changes proposed in this Pull Request

* Create an issue template for adding new products to the Marketplace

#### Testing instructions

* TBD

Related to #

### CODE REVIEW

**Comment by cpapazoglou** [comment]
Let's move the template to another a8c GH repo as mentioned in p1646677858247489/1646369491.076509-slack-C029JEQRVRT

**Comment by cpapazoglou** [comment]
Let's move the template to another a8c GH repo as mentioned in p1646677858247489/1646369491.076509-slack-C029JEQRVRT

**Comment by cpapazoglou** [comment]
@gcsecsey I think there is an even better solution. Creating a pattern block in our P2 containing a checklist. Each checklist item can also have it's unique issue or further explanation / links? How does it sound?

**Comment by cpapazoglou** [comment]
Discussed this in our Sprint planning and agreed that a P2 pattern that contains a checklist like 
https://github.com/Automattic/wp-calypso/issues/61548
and info like 
pdh6GB-tx-p2
would be very valuable. Perhaps we can also add some explanations for example why some slugs have hyphens when other ones have dashes.

**Comment by lsl** [comment]
> Perhaps we can also add some explanations for example why some slugs have hyphens when other ones have dashes.

I haven't found another reason yet so I suspect this mostly comes down to the store_products generation script transforming product catalog slugs to snake_case by default. Yet it looks like many have overridden the default with kebab-case, so the store_product table has a mix of types.

**Comment by gcsecsey** [comment]
@lsl @cpapazoglou I've created a draft P2 pattern. As adding products create no PRs in the wp-calypso repo, I've tried making the pattern so that we can track all changes in P2.

Please take a look and update it/let me know if I can add anything else to it. 🙂

**Comment by lsl** [comment]
Looks great!

I added example links and updated the todo list a bit based on the latest iteration of tracking this process: https://github.com/Automattic/wp-calypso/issues/62005

Also updated the "good example" note a bit as we learned in https://github.com/Automattic/wp-calypso/issues/61548 and https://github.com/Automattic/wp-calypso/issues/61918 that juggling so many small issues when the process can almost be completed in a single day gets quite tedious requiring lots of tab juggling to find the right link to diffs etc.

For onboarding new devs to the process I think it's worth breaking things down but ultimately depends on who's doing the work.

**Pull request closed without merging**
