### PR TITLE
Email stats: add email stats summary page

### LINKED ISSUE #72433: Email stats: add View all button & View all page to the overview.
Related to #[72432](https://github.com/Automattic/wp-calypso/issues/72432)

Add a View All button beneath the list of 10 posts that redirects to a page showing all posts. 

Image

To be checked/discussed with @saygunnyc

### PR DESCRIPTION
**Pull request by TimBroddin**
Closes #72433

## Proposed Changes

This PR adds a very basic email stats summary page. This page is accesible by clicking the `View Details` link at the bottom of the Email card on the stats overview.

CleanShot 2023-02-10 at 10 39 17@2x

The list shown is sorted by Opens descending.

CleanShot 2023-02-10 at 10 41 59@2x

## Testing Instructions

* Apply this patch to your sandbox: D100869-code (make sure to sandbox `public-api.wordpress.com`)
* Apply this PR
* Visit your stats, and add the feature flag: `/stats/day/<yoursite>?flags=newsletter/stats`
* At the bottom you should see the Email card, with a `View Details` link$
* Click this link
* You should be transported to the new list
* This list will show 30 items (at most), and is sorted by opens descending. 

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

**Review by JuanLucha — APPROVED** [review]
Nice job!

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/7806170

Thank you @TimBroddin for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/7806170).

**Comment by staskus** [comment]
@TimBroddin 

Hey. I know it's an old PR but do you remember if there was a reason to show Emails ordered differently in the main Stats page and in the Email Stats page? 
- Ordered by opens on the Email Stats page
- Ordered by post id on main Stats page

Both tables show "Latest emails" as column title no matter the sorting: 
image

Thanks!

**Comment by TimBroddin** [comment]
Hey @staskus 👋

I don't believe there was any particular reasoning behind this. Feel free to change this around as needed.

**Pull request merged**
