### PR TITLE
Happychat: Add notices for abnormal events

### PR DESCRIPTION
**Pull request by jordwest**
Adds notices for when the operator disconnects or user's connection drops.

cc @beaucollins @mkaz 

and @jasmussen and @evilluendas for design thoughts

screen shot 2017-03-07 at 6 22 51 pm

I've just made a guess what the notice text should be, so these are open for discussion. ~~I'm especially unsure what the meaning behind the `pending` status is and what we should ask the user to do in that case.~~ @beaucollins confirmed the notice below works for `pending`

| Status | Meaning | Notice |
| ------ | --------  | ------ |
| `default` | no chat has been started | (No notice) |
| `pending` | chat has been started but no operator assigned | Sorry, we couldn't connect you with a Happiness Engineer. Please check back later. |
| `assigning` | system is assigning to an operator | Connecting you with a Happiness Engineer... |
| `assigned` | operator has been connected to the chat | (No notice) |
| `missed` | no operator could be assigned | Sorry, we missed you! All our Happiness Engineers are currently busy. Please check back later. |
| `abandoned` | operator was disconnected | We're having some connection trouble on our end, please bear with us. |
| (No connection) | No connection to Happychat at all | We're having trouble connecting to chat. Please check your internet connection and refresh the page. |

### How to test

Note that some of these notices will not appear until #11604 is merged - currently client disconnection events are not handled.

An easy way to show the notice is to make yourself available as an operator, start a chat from Calypso, then close the HUD tab. You should then see the `abandoned` message above.

### CODE REVIEW

**Comment by jasmussen** [comment]
Looks good! 

Perhaps tune the colors of the message a bit:

untitled-1

At the very least, there shouldn't be a left border on the white box that shows the message. Then it becomes a double left border.

**Comment by jordwest** [comment]
Weird, I hadn't noticed the double border. It seems to only show when the chat is in popup mode, not as a sidebar.

In any case, removing the border looks good in both states with a dark background:

### Popup
screen shot 2017-03-08 at 12 01 16 pm

### Sidebar
screen shot 2017-03-08 at 12 01 06 pm

**Comment by jordwest** [comment]
@mkaz Would you mind taking a look at this code-wise?

**Comment by kriskarkoski** [comment]
Related: https://github.com/Automattic/happychat/issues/181

Like @mkaz said, I think adjusting the language on "please bear with us" and "Please check back later." to specify what we want them to do would be better, which in most cases I think would be to try refreshing?

**Comment by beaucollins** [comment]
Refreshing wouldn't do anything. Given their internet connection is still good the chat client will be notified immediately when they get assigned to an operator so we can provide UI feedback of some kind.

**Comment by kriskarkoski** [comment]
> Refreshing wouldn't do anything. Given their internet connection is still good the chat client will be notified immediately when they get assigned to an operator so we can provide UI feedback of some kind.

Cool, in that case I think just saying "Please wait while we connect you" or something along those lines makes sense for my understanding of the pending status. Would missed/abandoned reconnect automatically?

**Comment by jordwest** [comment]
I just merged this while we were having problems with the happychat service to keep users informed. Let's open another PR to change the wording.

I was worried that "please wait" might give the user the wrong expectations in times when there are no operators are available (when chat is closed for example) or when we're having issues with the service.

**Pull request merged**
