### PR TITLE
Hosting dashboard: Change the status filter to be primary

### PR DESCRIPTION
**Pull request by allilevine**
## Proposed Changes

* To address call for testing feedback (pdtkmj-2VB-p2#comment-5662) and [previous design feedback](https://github.com/WordPress/gutenberg/issues/64689) that the "add filter" link is confusing and shouldn't show up, change the Status filter to be a "primary" filter. This does mean that "Status" will always be visible. An alternative solution would be to add another filter, like Plan. 

Before | After
---- | -----
Screen Shot 2024-10-01 at 4 34 01 PM | Screen Shot 2024-10-01 at 4 41 18 PM
Screen Shot 2024-10-01 at 4 34 44 PM | Screen Shot 2024-10-01 at 4 34 32 PM

## Why are these changes being made?

* To make filtering less confusing.

## Testing Instructions

* Go to /sites
* Click to filter by status.

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Comment by davemart-in** [comment]
Having "Status" there by default doesn't feel right. @jameskoster can you please help clarify what the default behavior is supposed to be here?

**Comment by jameskoster** [comment]
By default all filter chips are hidden until manually added by the user via the "Add filter" menu. The exception is `primary` filters which are added (unset) automatically and cannot be removed. It's a way of allowing users to bypass the "Add filter" menu so they can apply the most common filters quickly.

**Comment by allilevine** [comment]
> By default all filter chips are hidden until manually added by the user via the "Add filter" menu. The exception is `primary` filters which are added (unset) automatically and cannot be removed. It's a way of allowing users to bypass the "Add filter" menu so they can apply the most common filters quickly.

Thank you! @davemart-in Should we put this on hold / look for another solution instead of showing "Status" by default?

**Comment by davemart-in** [comment]
@allilevine I'd probably side with closing this PR and keeping things the way they are.

**Pull request closed without merging**
