### PR TITLE
Tiled Gallery Block: Add Bottom Margin

### LINKED ISSUE #30432: Tiled Gallery Block: No Margin Beneath Block
#### Steps to reproduce
1. Starting in the editor, add a Tiled Gallery Block
2. Add a paragraph block directly underneath that, as if you were to continue writing
3. Publish

#### What I expected

A bottom margin to be consistent with other blocks, including the Gallery Block. 

#### What happened instead

In the editor:

gsddfsgdgfsgfds

Front end, taken with different themes, compare the margin between the Gallery and the Tiled Gallery Blocks. The Tiled Gallery one looks off. 

fadsfadsasdfsdaf

fdasasfdadsffsda

Found when using the block myself.

### PR DESCRIPTION
**Pull request by torres126**
#### Changes proposed in this Pull Request

Jetpack seems to add a bottom margin of 20px to the end of tiled galleries, so that there's a reasonable space between the end of the gallery and the next bit of content. 

https://github.com/Automattic/jetpack/blob/cb4dcbb88e8331c376d53e7e978bff80dc6a33c6/modules/tiled-gallery/tiled-gallery/tiled-gallery.css#L4-L8

```
.tiled-gallery {
	clear: both;
	margin: 0 0 20px;
	overflow: hidden;
}
```
There's currently no bottom margin for the Tiled Gallery Block. This PR proposes setting one to 20px to match that value. 

#### Testing instructions

Ensure there's a reasonable margin when following the steps in the original issue, regardless of theme. 

**Current:**

gdsfdsfgdsfgsgdf

**Proposed:**

gsdffgsddsfgdfg

(cc @simison) 

Fixes #30432

### CODE REVIEW

**Comment by sirreal** [comment]
Thanks @torres126!

I looked at a post with Twenty Nineteen theme and didn't see this issue from #30432.

The core gallery block doesn't appear to include bottom padding:

https://github.com/WordPress/gutenberg/blob/acb42fac47544c350f05a92db8b6fc428141b7c4/packages/block-library/src/gallery/style.scss

Before making this change, I'd like to understand where the space comes from around the core Gallery block and why it's absent around the Tiled Gallery. Rather than aligning with the legacy Tiled Gallery styling, we should do our best to align with how the core Gallery block is styled.

We'll take a closer look at this sometime soon, thanks again for the report and this PR!

**Comment by torres126** [comment]
Thanks @sirreal! 

> Before making this change, I'd like to understand where the space comes from around the core Gallery block and why it's absent around the Tiled Gallery. 

Here's my thoughts on this, word of warning though: I'm not sure how much of this is actually the case, but I did take a quick look at this. 

I think Twenty Nineteen is the exception. It's one of the few themes which apply a margin to everything instead of individual blocks, several times in fact. Here's one example, but it happens at multiple media queries.

https://github.com/WordPress/twentynineteen/blob/b604f127c2cae10bd48bbbec0fbbbff2cd31f957/style.css#L3447

```
.entry .entry-content > *,
.entry .entry-summary > * {
  margin: 32px 0;
  max-width: 100%;
}

```

Removing those and similar styles does cause this issue to appear. When it comes to the core Gallery Block, I *think* that most themes, at least on WordPress.com, do not do this but favour an individual approach. For example, with Dara: https://github.com/Automattic/themes/blob/cab5413d966b4153012ec90aff33b5a939822e17/dara/blocks.css#L52

```
.wp-block-gallery {
	margin-bottom: 1.6em;
	margin-left: auto;
}

```
But the Gallery Block still seems to fall back on the `ul, ol` styles for the theme, so that there isn't a major difference. This is most notable with a retired theme such as Harmonic, which doesn't have individual block styles but 
```
ul, ol { 
margin: 0 0 20px 40px;
} 
```
means that there isn't an obscure margin beneath the block. That being said, it also looks like the Gallery Block adds a little extra height so that the margin isn't super odd, but regardless it's still noticeable. The main problem which I imagine with relying on themes to include the Tiled Gallery Block is that immediately it becomes a noticeable bug on all retired themes, and also what @simison said in #30432.

> I'd expect this to work just like core gallery and that themes would not need to worry about a block shipped in plugin.

That being said, if the block was wrapped in a `<ul>` tag, themes (at least the WordPress.com ones I've tested with) would probably style it regardless of the amount or lack of Gutenberg support included. For example, with Harmonic.

fasddfsafdasasd

I wonder if that's a better approach.

**Comment by sirreal** [comment]
Thanks for that thorough investigation @torres126 🙂 

@thomasguillot what do you think of this to address #30432?

**Comment by thomasguillot** [comment]
I think it's ok if we add a margin-bottom to the tiled gallery as it's not a Core block and we shouldn't expect all themes to automatically style it. I'd use `1.5em` rather than `20px` though.

**Pull request merged**
