### PR TITLE
Use pattern.html instead of pattern.content and fix the API version of icon setting endpoint

### PR DESCRIPTION
**Pull request by alshakero**
#### Proposed Changes

* This is a follow-up for #67255, namely this [line](https://github.com/Automattic/wp-calypso/pull/67255/files#diff-cd05eac928442f8732bb51e8c35e583155dfc380ac8ad250a7bbcbfe60b60ce5R19).
* It now uses `pattern.html` vs `pattern.content`.
* Use the right API version to set the logo. The previous version only allows updating the site_icon (not site logo).

#### Testing Instructions

1. Go through /setup?flow=link-in-bio.
2. Make sure the pattern you pick is applied when you land in Launchpad.

### CODE REVIEW

**Comment by simison** [comment]
This fixes things _mostly_: now just the site logo was left out:

image

**Comment by simison** [comment]
@alshakero  Also the free domain I ended up seems to be incorrect:

Selected:

image

Actual:

Screenshot 2022-09-07 at 17 14 38

**Comment by escapemanuele** [comment]
I now see the site logo working correctly, but I'm experiencing the same problem with the free domain!

We could also investigate on that in a separate PR

**Comment by heavyweight** [comment]
Issue with free domain has been fixed and merged, deploying now..

**Pull request merged**
