### PR TITLE
Migration: Update upgrade plan screen with CTA and title

### LINKED ISSUE #93297: Step: Upgrade prompt
### Details

Add a new step to the new migration flow to upgrade the plan. This step should also contain a link to the import flow at the right top. Make sure that this link is only displayed in the new flow and the step doesn't get affected in other flows.

Screenshot 2024-08-06 at 17 04 18

### Checklist

- [ ] The step has a link to the import step at the top right only when it's in the new flow. #93461
- ~~The import step also has a link to return to the migration option.~~ This will be handled as part of https://github.com/Automattic/wp-calypso/issues/93463.

### Related

https://github.com/Automattic/wp-calypso/issues/93258

### PR DESCRIPTION
**Pull request by gabrielcaires**
Closes [#93297](https://github.com/Automattic/wp-calypso/issues/93297)

## Proposed Changes
* Add the `I want to import my content only` only when the upgrade step is rendered inside the new migration flow
* Use `Here’s the plan you need`  as title
* Add `MigrationUpgradePlan` to hold the flow-specific props

## Testing Instructions

* Start the new migration flow
* Go to the upgrade plan
* Click on "I want to import my content only" link
* Check if you have been redirected to the "importerWordPress" step
* Click on the back button on the step UI
* Check if you are on the `/migration-upgrade-plan`  selection page.

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Review by renatho — APPROVED** [review]
Looks good and works well!

Just one suggestion to consider. WDYT to use `customizedActionButtons` instead of the skip props from the `StepContainer`?

I'm not sure if semantically that fits as a skip, specially because we'll have the same in the import step to also navigate back. I think it's more like a "switch".

**Comment by gabrielcaires** [comment]
> Looks good and works well!
> 
> Just one suggestion to consider. WDYT to use `customizedActionButtons` instead of the skip props from the `StepContainer`?
> 
> I'm not sure if semantically that fits as a skip, specially because we'll have the same in the import step to also navigate back. I think it's more like a "switch".

@renatho  I liked and updated [41515b2](https://github.com/Automattic/wp-calypso/pull/93461/commits/41515b2e29552c7b8d02b1dcaf1b22dee706e208).

I saw it, but I thought it would be hard to use a custom button.

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/16487502

Some locales (Hebrew, Japanese) have been temporarily machine-translated due to translator availability. All other translations are usually ready within a few days. Untranslated and machine-translated strings will be sent for translation next Monday and are expected to be completed by the following Friday.

Hi @gabrielcaires, could you please edit the description of this PR and add a screenshot for our translators? Ideally it'd include all of the following strings:
- `Here’s the plan you need`
- `I want to import my content only`
- `Upgrade your plan to migrate your site`

Thank you in advance!

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/16487502).

**Pull request merged**
