### PR TITLE
Gutenboarding: Intent Capture update

### LINKED ISSUE #42363: Gutenboarding: Changes to intent capture
As we've discussed, let's do two changes to the first onboarding step:

**Remove the site category/vertical step**
We'll reintroduce this at a later point, but until we've worked out the quirks and functionality properly we should remove this step.

**Make the input field more obvious**
Let's change the look of the input field to this:
image
image

Changes:
- String is now "What's your website called?"
- Input field should have a `gray0` background-color
- Font-size should be changed to `44px` on desktop
- The _I don't know_ button should be changed to _Skip for now_ and moved under the input field on desktop. Once a user has entered a value the Continue button should appear and the skip button should disappear.
- Left padding on the container should be `120px`

Check Figma for mobile mocks and further detailed specs :)

cc/ @olaolusoga @rickybanister @amamujee

### PR DESCRIPTION
**Pull request by razvanpapadopol**
#### Changes proposed in this Pull Request
* Remove vertical select from Intent Capture step in Gutenboarding.
* Update site title input styling and use a regular `<input/>` instead of `contenteditable`.
* Design Selection step (`/new/design` route) can be now accessed with an empty state.

#### Testing instructions
* Go to [/new](https://calypso.live/new?branch=update/gutenboarding-intent-capture-remove-vertical).
* Advancing from Intent Capture should work by:
  * typing at least 3 characters and pressing the primary button _Choose Design_
  * pressing _skip for now_ link below the input. in this case any input will be removed and the header will reflect default state with DomainPicker using the fallback search query _My new site_. 

Fixes #42363

### CODE REVIEW

**Comment by dubielzyk** [comment]
This is looking great! Is it possible to have a growing input field? Otherwise we get this oddly long line: 
image

**Comment by ramonjd** [comment]
@andrewserong Feel free to launch this one if it tests well 

Authority vested in us to do so to found at the end of this thread:

p1589896178251400-slack-CNMU1UHHB

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/3643858

Hi @razvanpapadopol, could you please edit the description of this PR and add a screenshot for our translators? Ideally it'd include all of the following strings:
- `Choose design`
- `My site is called`

Thank you in advance!

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/3643858).

**Comment by roo2** [comment]
this also closed #42389

**Pull request merged**
