### PR TITLE
Adds `nav-unification` query arg flag to menu items' url prop when flag is on

### PR DESCRIPTION
**Pull request by getdave**
Currently when navigating to `wp-admin` urls the `?flag=nav-unification` isn't in the URL and so you loose the "nav unification" context when you navigate.

This PR updates so that all URLs in the menu have the flag appended to their query string. This happens _only_ if the flag has been set to `true` when the page is loaded. This ensures a more seamless experience during development.

This may prove redundant if this gets handle on the REST API (cc @obenland).

## Changes proposed in this Pull Request

* Appends `?flag=nav-unification` to all menu item `.url` props if the config flag for `nav-unification` is set to `true`.

#### On Master

* Load Calypso with flag and sticker.
* Click any menu item that will take you to WPAdmin. 
* Notice the `?flag=nav-unification` query string is now missing in WPAdmin.

#### This PR

* Load Calypso with flag and sticker.
* Click any menu item that will take you to WPAdmin. 
* Notice the `?flag=nav-unification` query string is appended to the WPAdmin URL.

### CODE REVIEW

**Review by marekhrabe — APPROVED** [review]
> Appends ?flag=nav-unification to all menu item .url props if the config flag for nav-unification is set to true.

Works as described and adds the flag to all links.

**Comment by obenland** [comment]
Unless I'm missing something, the `nav-unification` flag doesn't do anything on the wp-admin side, does it?

**Comment by getdave** [comment]
> Unless I'm missing something, the `nav-unification` flag doesn't do anything on the wp-admin side, does it?

When you are in WPAdmin the flag seems to be present on all links back to Calypso. I thought you'd need the flag on WPAdmin but now thinking about it I'm not sure.

**Comment by getdave** [comment]
Not required as it's the WPAdmin side we need to append the query string to.

**Pull request closed without merging**
