### PR TITLE
Plans Next: Fix show-all-features button from moving when clicked

### PR DESCRIPTION
**Pull request by chriskmnds**
Fixes https://github.com/Automattic/martech/issues/2078

## Proposed Changes

Fixes the margin on the foldable card by binding the card to a CSS class.

## Testing Instructions

* Go to `/start/plans` or `/plans/[ site ]`
* Go to mobile view. 
* Click on "show all features" to expand. Click again to close. Ensure it doesn't move up/down.

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Review by oswian — APPROVED** [review]
Works well. 

Not related to this change, however I think the gap here is too large:

CleanShot 2024-03-28 at 12 54 34@2x

The "Show all features" button and the list of features feel disconnected.

**Comment by southp** [comment]
Thanks for polishing the UI here :) 

I can confirm that the logged-in `/plans` is fixed. However, it still presents in `/start/plans`:

https://github.com/Automattic/wp-calypso/assets/1842898/64041006-b931-4a16-93cb-01a2a4ad14ba

Let's also fix it in the same PR if it makes sense.

**Comment by chriskmnds** [comment]
> Not related to this change, however I think the gap here is too large:

Thanks @oswian . It is indeed a little too much of a gap. I reduced it down to half (removing completely complicates things a little).

> I can confirm that the logged-in /plans is fixed. However, it still presents in /start/plans:

Thanks @southp . It should be addressed. Cleaned up the classes while at it and increased specificity. 

If you can spare a cycle, then pls give it another go. I'm running with a bit of a headache again 😐

**Review by southp — APPROVED** [review]
Works perfectly with a cleaner stylesheet. Thanks for the fix :shipit:

**Comment by chriskmnds** [comment]
Perfect. thanks :-)

**Pull request merged**
