### PR TITLE
Gridicons: Try svg loader

### PR DESCRIPTION
**Pull request by sirreal**
Just an experiment. Let's see what ICFY says…

cc: @ockham 

This isn't a viable solution, Gridicons are used in ways that depend on them being inline SVGs for styling.

### Before

bell-b
write-b
sites-b

### After

bell
write
sites

### Size impact

[Full report](https://github.com/Automattic/wp-calypso/pull/26914#issuecomment-416197908)
[ICFY](http://iscalypsofastyet.com/branch?branch=try/gridicons-svg-loader)

|chunk|                                                                                                          stat_size|           parsed_size|           gzip_size|
|--|--|--|--|
|async-load-design                 |                                                                             -24788 B  (-5.3%)   |  -22633 B  (-7.6%)   | -2319 B  (-4.3%)|
|build                                        |                                                                   +19646 B  (+0.6%)  |   +35499 B  (+2.5%) |   +3208 B  (+1.0%)|
|vendors~build                       |                                                                            -96078 B  (-3.5%)  |   -90741 B  (-7.2%) |  -19544 B  (-6.2%)|

### CODE REVIEW

**Comment by ockham** [comment]
> This isn't a viable solution, Gridicons are used in ways that depend on them being inline SVGs for styling.

Hmm, shame. Well, we could use an [inline loader](https://github.com/webpack-contrib/svg-inline-loader) - but that would add to the confusion if we also stuck with `file-loader` for the flags SVGs. Means we'd probably need to reconsider if we'd also switch those to the inline loader...

Should probably do a bit of recon how much we rely on styling inline SVGs and if we can easily work our way around that....

**Comment by ockham** [comment]
/cc @Automattic/team-calypso 

Overall idea here is to possibly ditch the autogenerated JSX from the Gridicons repo and just use a webpack loader to pull 'em in.

**Comment by tyxla** [comment]
> Overall idea here is to possibly ditch the autogenerated JSX from the Gridicons repo and just use a webpack loader to pull 'em in.

In addition to chunk sizes, it's worth seeing whether this will have any negative impact on the build time.

**Comment by sirreal** [comment]
```
Commit: f6424411792d3bc76cbedd731289fae5ba2aa85b
Author: sirreal
At: 2018-08-26T03:23:31Z
Message: FIXME: Remove gridicons import that broke builds
Delta:
chunk                                                                                                          stat_size           parsed_size           gzip_size
accept-invite~checkout~jetpack-connect~signup                                                                       +0 B                 -20 B  (-0.1%)       -4 B  (-0.1%)
accept-invite~jetpack-connect~signup                                                                                +0 B                 -20 B  (-0.1%)       -9 B  (-0.1%)
account                                                                                                             +0 B                 -20 B  (-0.1%)       -9 B  (-0.1%)
account-close                                                                                                       +0 B                 -42 B  (-0.2%)       -8 B  (-0.1%)
account~account-close~async-load-design-blocks~async-load-post-editor-media-modal~happychat~help~me~~f1ee5101       +0 B                 -42 B  (-0.1%)       -7 B  (-0.1%)
account~account-close~happychat~help~me~notification-settings~privacy~purchases~security                            +0 B                -102 B  (-0.1%)      -28 B  (-0.2%)
account~ads~async-load-design~async-load-design-blocks~async-load-design-playground~async-load-guten~16df698c       +0 B                 -80 B  (-0.4%)       -2 B  (-0.0%)
ads                                                                                                                 +0 B                 -42 B  (-0.1%)      -14 B  (-0.1%)
async-load-blocks-calendar-popover~comments~post-editor                                                             +0 B                 -20 B  (-0.1%)      -11 B  (-0.2%)
async-load-blocks-inline-help-popover                                                                               +0 B                 -22 B  (-0.1%)       -8 B  (-0.1%)
async-load-blocks-inline-help-popover~help                                                                          +0 B                -163 B  (-0.1%)      -44 B  (-0.2%)
async-load-blocks-reader-full-post                                                                                  +0 B                 -40 B  (-0.1%)      -10 B  (-0.1%)
async-load-components-community-translator                                                                          +0 B                 -20 B  (-0.2%)       -7 B  (-0.3%)
async-load-components-happychat                                                                                     +0 B                 -20 B  (-0.4%)       -9 B  (-0.6%)
async-load-components-happychat~happychat                                                                           +0 B                  +0 B                -1 B  (-0.0%)
async-load-components-web-preview-component                                                                         +0 B                -104 B  (-0.2%)      -23 B  (-0.2%)
async-load-components-web-preview-component~posts-custom~posts-pages                                                +0 B                 -20 B  (-0.1%)      -13 B  (-0.3%)
async-load-components-web-preview-component~reader                                                                  +0 B                -185 B  (-0.1%)      -26 B  (-0.1%)
async-load-design                                                                                               -24788 B  (-5.3%)     -22633 B  (-7.6%)    -2319 B  (-4.3%)
async-load-design-blocks                                                                                            +0 B               -1063 B  (-0.1%)     -135 B  (-0.1%)
async-load-design-playground                                                                                        +0 B                -231 B  (-0.1%)      -32 B  (-0.1%)
async-load-design~async-load-design-blocks~async-load-design-playground~async-load-gutenberg-blocks~~0742ab94       +0 B                 -20 B  (-0.1%)      -10 B  (-0.2%)
async-load-design~async-load-design-blocks~async-load-design-playground~async-load-gutenberg-blocks~~31e5b9f5       +0 B                 -20 B  (-0.1%)      -11 B  (-0.1%)
async-load-design~async-load-design-blocks~async-load-design-playground~async-load-gutenberg-blocks~~5a1097cf       +0 B                 -80 B  (-0.3%)      -10 B  (-0.2%)
async-load-design~async-load-design-blocks~async-load-design-playground~async-load-gutenberg-blocks~~a0d6e193       +0 B                 -60 B  (-0.3%)      -11 B  (-0.3%)
async-load-design~async-load-design-blocks~async-load-design-playground~checkout~domains~purchases~w~ea89a787       +0 B                 -20 B  (-0.0%)       -9 B  (-0.0%)
async-load-design~async-load-design-playground~async-load-gutenberg-blocks~async-load-gutenberg-comp~d8c00363       +0 B                -262 B  (-0.3%)       +3 B  (+0.0%)
async-load-extensions-woocommerce-app-store-stats                                                                   +0 B                 -20 B  (-0.1%)       -8 B  (-0.1%)
async-load-extensions-woocommerce-app-store-stats-listview                                                          +0 B                 -60 B  (-0.3%)       -9 B  (-0.2%)
async-load-extensions-woocommerce-app-store-stats-referrers                                                         +0 B                 -20 B  (-0.1%)       -5 B  (-0.1%)
async-load-extensions-woocommerce-app-store-stats~async-load-extensions-woocommerce-app-store-stats-~a2cc2cf0       +0 B                 -80 B  (-0.3%)      -21 B  (-0.3%)
async-load-featured-image                                                                                           +0 B                 -20 B  (-0.5%)       -9 B  (-0.7%)
async-load-gutenberg-blocks                                                                                         +0 B                 -20 B  (-0.1%)       -8 B  (-0.1%)
async-load-gutenberg-components                                                                                     +0 B                 -20 B  (-0.1%)       -2 B  (-0.0%)
async-load-layout-guided-tours                                                                                      +0 B                 -22 B  (-0.0%)      -10 B  (-0.1%)
async-load-layout-masterbar-drafts-popover                                                                          +0 B                 -20 B  (-0.2%)      -10 B  (-0.3%)
async-load-my-sites-guided-transfer                                                                                 +0 B                 -22 B  (-0.1%)      -12 B  (-0.2%)
async-load-my-sites-site-settings-section-export                                                                    +0 B                 -42 B  (-0.1%)      -19 B  (-0.3%)
async-load-my-sites-site-settings-section-import                                                                    +0 B                 -62 B  (-0.1%)      -28 B  (-0.2%)
async-load-post-editor-editor-author                                                                                +0 B                 -20 B  (-0.1%)      -10 B  (-0.2%)
async-load-post-editor-editor-location                                                                              +0 B                 -20 B  (-0.2%)       -7 B  (-0.2%)
async-load-post-editor-editor-post-formats-accordion                                                                +0 B                 -20 B  (-0.3%)      -10 B  (-0.5%)
async-load-post-editor-editor-sharing-accordion                                                                     +0 B                 -22 B  (-0.1%)       -8 B  (-0.1%)
async-load-post-editor-media-modal                                                                                  +0 B                 -62 B  (-0.1%)      -18 B  (-0.1%)
async-load-post-editor-media-modal~media~post-editor                                                                +0 B                 -66 B  (-0.1%)      -25 B  (-0.1%)
async-load-post-editor-media-modal~media~post-editor~sharing                                                        +0 B                 -20 B  (-0.1%)       -8 B  (-0.2%)
async-load-reader-conversations-stream                                                                              +0 B                 -20 B  (-0.4%)       -8 B  (-0.5%)
async-load-reader-feed-stream~async-load-reader-site-stream                                                         +0 B                 -80 B  (-0.3%)      -15 B  (-0.2%)
async-load-reader-following-manage                                                                                  +0 B                 -82 B  (-0.2%)       -9 B  (-0.1%)
async-load-reader-following-manage~async-load-reader-search-stream                                                  +0 B                 -20 B  (-0.1%)       -1 B  (-0.0%)
async-load-reader-list-stream                                                                                       +0 B                 -20 B  (-0.2%)       -8 B  (-0.3%)
async-load-reader-search-stream                                                                                     +0 B                 -20 B  (-0.1%)       -4 B  (-0.1%)
async-load-reader-sidebar                                                                                           +0 B                 -24 B  (-0.1%)       -9 B  (-0.1%)
async-load-reader-tag-stream-main                                                                                   +0 B                 -43 B  (-0.3%)      -25 B  (-0.6%)
build                                                                                                           +19646 B  (+0.6%)     +35499 B  (+2.5%)    +3208 B  (+1.0%)
checklist                                                                                                           +0 B                 -60 B  (-0.2%)       +3 B  (+0.0%)
checkout                                                                                                            +0 B                 -62 B  (-0.0%)      -11 B  (-0.0%)
checkout~domains                                                                                                    +0 B                 -20 B  (-0.1%)      -12 B  (-0.1%)
checkout~domains~plans                                                                                              +0 B                 -20 B  (-0.1%)      -14 B  (-0.2%)
checkout~plans                                                                                                      +0 B                 -40 B  (-0.2%)      -19 B  (-0.3%)
checkout~purchases                                                                                                  +0 B                 -20 B  (-0.1%)       +0 B
comments                                                                                                            +0 B                -124 B  (-0.1%)      -20 B  (-0.1%)
concierge                                                                                                           +0 B                 -62 B  (-0.1%)      -21 B  (-0.2%)
customize                                                                                                           +0 B                 -20 B  (-0.1%)      -10 B  (-0.2%)
devdocs                                                                                                             +0 B                 -40 B  (-0.1%)       -8 B  (-0.1%)
domain-connect-authorize                                                                                            +0 B                 -20 B  (-0.2%)       -9 B  (-0.2%)
domains                                                                                                             +0 B                 -62 B  (-0.0%)      -25 B  (-0.0%)
domains~plans                                                                                                       +0 B                 -40 B  (-0.2%)      -11 B  (-0.2%)
domains~signup                                                                                                      +0 B                -127 B  (-0.1%)      -32 B  (-0.1%)
feature-upsell                                                                                                      +0 B                 -62 B  (-0.1%)      -36 B  (-0.4%)
google-my-business                                                                                                  +0 B                 -44 B  (-0.1%)       -7 B  (-0.0%)
google-my-business~stats                                                                                            +0 B                 -40 B  (-0.1%)       -3 B  (-0.0%)
help                                                                                                                +0 B                 -22 B  (-0.1%)      -11 B  (-0.2%)
jetpack-connect                                                                                                     +0 B                -126 B  (-0.1%)      -36 B  (-0.1%)
jetpack-connect~plans~signup                                                                                        +0 B                 -62 B  (-0.1%)       -9 B  (-0.1%)
jetpack-onboarding                                                                                                  +0 B                 -63 B  (-0.1%)       -8 B  (-0.1%)
login                                                                                                               +0 B                 -84 B  (-0.1%)       -4 B  (-0.0%)
mailing-lists                                                                                                       +0 B                 -20 B  (-0.3%)       -9 B  (-0.5%)
manifest                                                                                                            +0 B                  +0 B                +6 B  (+0.1%)
media                                                                                                               +0 B                 -60 B  (-0.2%)      -10 B  (-0.1%)
notification-settings                                                                                               +0 B                 -23 B  (-0.0%)       -8 B  (-0.1%)
people                                                                                                              +0 B                -131 B  (-0.1%)      -29 B  (-0.1%)
plans                                                                                                               +0 B                 -60 B  (-0.1%)      +12 B  (+0.1%)
plugins                                                                                                             +0 B                -222 B  (-0.1%)      -43 B  (-0.1%)
plugins~themes                                                                                                      +0 B                 -80 B  (-0.2%)      -25 B  (-0.3%)
post-editor                                                                                                         +0 B                -379 B  (-0.1%)      -59 B  (-0.0%)
post-editor~settings-writing~woocommerce                                                                            +0 B                 -60 B  (-0.3%)      -18 B  (-0.3%)
posts-custom~posts-pages                                                                                            +0 B                -202 B  (-0.2%)      -80 B  (-0.3%)
posts-pages                                                                                                         +0 B                 -42 B  (-0.1%)      -28 B  (-0.2%)
preview                                                                                                             +0 B                 -20 B  (-0.5%)       -9 B  (-0.5%)
purchases                                                                                                           +0 B                -102 B  (-0.1%)      -27 B  (-0.1%)
reader                                                                                                              +0 B                -135 B  (-0.1%)      -33 B  (-0.1%)
security                                                                                                            +0 B                 -84 B  (-0.1%)      -44 B  (-0.2%)
settings                                                                                                            +0 B                -163 B  (-0.1%)       -1 B  (-0.0%)
settings-security                                                                                                   +0 B                -102 B  (-0.2%)      -30 B  (-0.2%)
settings-traffic                                                                                                    +0 B                 -40 B  (-0.0%)      -12 B  (-0.1%)
settings-writing                                                                                                    +0 B                -176 B  (-0.1%)      -48 B  (-0.1%)
settings~settings-discussion~settings-security~settings-traffic~settings-writing                                    +0 B                 -40 B  (-0.1%)       -1 B  (-0.0%)
sharing                                                                                                             +0 B                 -82 B  (-0.1%)      -19 B  (-0.1%)
signup                                                                                                              +0 B                -150 B  (-0.1%)      -13 B  (-0.0%)
signup~stats                                                                                                        +0 B                 -60 B  (-0.2%)      -19 B  (-0.3%)
stats                                                                                                               +0 B                 -42 B  (-0.0%)      -24 B  (-0.0%)
theme                                                                                                               +0 B                 -22 B  (-0.1%)       -9 B  (-0.1%)
theme~themes                                                                                                        +0 B                -100 B  (-0.2%)      -28 B  (-0.2%)
themes                                                                                                              +0 B                 -24 B  (-0.0%)      -13 B  (-0.1%)
vendors~async-load-design~async-load-design-blocks~async-load-design-playground~async-load-gutenberg~2306410c       -6 B  (-0.0%)         +0 B                +0 B
vendors~async-load-design~async-load-design-blocks~async-load-design-playground~async-load-gutenberg~d451e0fc     +129 B  (+0.0%)       +112 B  (+0.0%)      +20 B  (+0.0%)
vendors~async-load-design~async-load-design-playground~google-my-business~woocommerce                             +228 B  (+0.2%)         -1 B  (-0.0%)       -1 B  (-0.0%)
vendors~async-load-gutenberg-blocks~gutenberg-editor                                                              +446 B  (+0.0%)       +224 B  (+0.1%)      +64 B  (+0.1%)
vendors~build                                                                                                   -96078 B  (-3.5%)     -90741 B  (-7.2%)   -19544 B  (-6.2%)
woocommerce                                                                                                         +0 B                -182 B  (-0.0%)       -8 B  (-0.0%)
wp-job-manager                                                                                                      +0 B                 -62 B  (-0.1%)      -20 B  (-0.1%)
wp-job-manager~wp-super-cache~zoninator                                                                             +0 B                 -20 B  (-0.1%)      -15 B  (-0.4%)
wp-super-cache                                                                                                      +0 B                 -42 B  (-0.0%)       -9 B  (-0.0%)
zoninator                                                                                                           +0 B                 -80 B  (-0.1%)      -25 B  (-0.2%)
```

**Comment by sirreal** [comment]
> we could use an inline loader

A glance looks promising

> Should probably do a bit of recon how much we rely on styling inline SVGs and if we can easily work our way around that

I really don't think loading these as `img` is a good approach. It was an interesting experiment, but inline SVGs offer much more flexibility. I don't see a way around that.

I think two things really need to happen with Gridicons:
- We switch to individual Gridicon imports, probably with a codemod (p7H4VZ-1QM-p2):
   ```js
   import GridiconExternal from 'gridicons/dist/external';
   <GridiconExternal />
   ```
- Gridicons moves here and is built as part of the monorepo

**Comment by sirreal** [comment]
This has served its purpose.

**Pull request closed without merging**
