### PR TITLE
Components: fix text contrast issues in blocks and components

### PR DESCRIPTION
**Pull request by drw158**
This updates a few components to use the $gray-text-min variable for text, which is the mimmim contrast needed to pass WCAG 2.0 AA tests on a white background.

In cases where the text was on a light gray background, the text color was darkened until it passed.

# **Before:**

screen shot 2017-02-17 at 12 22 38 pm
screen shot 2017-02-17 at 12 26 13 pm
screen shot 2017-02-17 at 12 27 48 pm
screen shot 2017-02-17 at 12 27 35 pm

---

# **After:**

screen shot 2017-02-17 at 12 22 03 pm
screen shot 2017-02-17 at 12 31 27 pm
screen shot 2017-02-17 at 12 33 04 pm
screen shot 2017-02-17 at 12 32 46 pm

### CODE REVIEW

**Comment by Copons** [comment]
If we're also aiming to standardize the gray shades, leaving the color functions to edge cases only, this PR sticks out a bit.

There's a `color: darken( $gray, 20% );`, but why not using `$gray-text-min` which is `darken( $gray, 18% )`, just 2% lighter?

About all those `darken( $gray, 10% )`, instead, I don't really have an opinion.
There is no variable for that, so I'm fine with it.
Except, maybe we could use good old simple `$gray`?

If this whole thing poses an a11y problem, would it be _that_ bad using `$gray-text-min` instead of `darken( $gray, 10% )`, and `$gray-text` (or `$gray-dark`, same color) instead of `darken( $gray, 20% )`?

**Comment by folletto** [comment]
> If we're also aiming to standardize the gray shades, leaving the color functions to edge cases only, 

Maybe I missed a conversation, but I don't think we're doing that as our color palette explicitly use function to be explicit about what's happening, instead of an opaque variable. 

That said, I'd agree to try to have every text – as much as possible without forcing – to be `$gray-text` and `$gray-text-min`, and leave the other shades for other UI elements and exceptions.

**Comment by Copons** [comment]
@folletto Sorry, bad wording.

> That said, I'd agree to try to have every text – as much as possible without forcing – to be $gray-text and $gray-text-min, and leave the other shades for other UI elements and exceptions.

I meant exactly this. 🙂

**Comment by drw158** [comment]
I tried to keep the original intent of the design intact. If the original text had a light color, I tried to keep it as light as possible and still pass AA. Some of the colors in this PR are not variables because some text is not on a white background. Also, some text is bold or greater than 18pt, so the color can be lighter in those cases and still pass.

**Comment by Copons** [comment]
Alright then! :shipit:

**Comment by folletto** [comment]
I checked, and I noticed that in some cases the text became lighted, which is a bit odd, see for example "Select your custom domain". 

I'd use `$gray-text` for these bits instead of trying to go on the bare minimum.

**Comment by drw158** [comment]
Oh, yea that text became lightened to create a separation from the text below it. Keeping it the same color made the text very similar (if not the same) color as the body text. In keeping with the original intent of the design, I made the header lighter, and it works since the text is >= 18pt.

**Pull request merged**
