### PR TITLE
Plans: update illustrations in My Plan feature cards.

### PR DESCRIPTION
**Pull request by AnnaMag**
Update to the illustrations of the feature cards (replacing gridicons, repeated icons and use updated illustrations).

## To test:

- checkout this branch on your local Calypso or use calypso.live,
- verify that the illustrations are correct at `http://calypso.localhost:3000/plans/:site` for both .com and JP plans.

 ref: p6TEKc-1SF-p2

### CODE REVIEW

**Comment by AnnaMag** [comment]
/cc @rickybanister 

@joanrho there seems to be a size issue with some of the images, e.g. Business .com plan cards:
screen shot 2018-04-30 at 14 25 40.
All images are sized in the same way.

We have used the last bottom illustration in the remote install notices, where this small version was appropriate. Would the large version we discarded at that time be useful here?

**Comment by AnnaMag** [comment]
@folletto will do! it is still in Progress 👍

**Comment by folletto** [comment]
Yup! :)
It's ok to open with "Before" and "In progress" if it's still on its way — at least when the "design feedback" label is added as it's useful to see it (even just to evaluate if I _can_ review or not :D ).

**Comment by AnnaMag** [comment]
@folletto, added ref to the description.

**Comment by joanrho** [comment]
Just updated the asset dimensions, styling, a few filenames, and also updated the file paths in the corresponding files (e.g., checkout thank you views). 

Before/after screenshots of my changes:

## WordPress.com
(Free has no free view for My Plan)

### Personal
01 wpcom personal

### Premium
02 wpcom premium

### Business
03 wpcom business


## Jetpack
### Free
01 jetpack free

### Personal
02 jetpack personal

### Premium
03 jetpack premium

### Professional
04 jetpack professional


@folletto see above before/after screenshots, which are getting closer to our final states—you can see those final before/after screenshots here: p6TEKc-1SF and in [#22691](https://github.com/Automattic/wp-calypso/issues/22691#issuecomment-371316734). [Mobile apps](https://github.com/Automattic/wp-calypso/issues/23380) and [Simple payments](https://github.com/Automattic/wp-calypso/pull/24535) cards coming soon (we're just about done with those).

There had been some confusion around and duplicates of four assets: Google AdWords, WordAds, Google Analytics, and Ads Removed. I've updated all four, so they no longer repeat anywhere:
screen shot 2018-04-30 at 9 04 33 pm

**Comment by folletto** [comment]
Ace work! 👍

**Pull request merged**
