### PR TITLE
Site Logs: allow downloading logs

### PR DESCRIPTION
**Pull request by mpkelly**
Closes https://github.com/Automattic/dotcom-forge/issues/1998

## Proposed Changes

* Show a download button that can download the currently selected logs locally
* Show download progress to the right side of the button

image

image

## Testing Instructions

* Checkout this branch
* Navigate to `/site-logs/:your-atomic-site`
* Click "Download"
* Confirm a log file is downloaded for the current tab, e.g. PHP
* Confirm the log contents match the UI contents. 

## Pre-merge Checklist

- [x] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [x] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

**Comment by mpkelly** [comment]
Merge conflict resolved.

**Comment by zaguiini** [comment]
Changed the download button to primary:

image

Added download detail to the right of the download button:

image

We're also not displaying the progress message if there is no information about it (if it's just one page). It's not needed as it's always `0/0` anyway and we're making the button busy so there is the feeling of progress.

**Comment by vykes-mac** [comment]
@mpkelly @zaguiini so we no longer showing the modal here? we should update the instructions if that's the case.

**Comment by zaguiini** [comment]
That's right @vykes-mac, I was so focused on the implementation that I forgot to update the PR details 😛 @mpkelly @p-jackson would you mind doing that as I already ended my day? Of course, testing the PR and merging it would be greatly appreciated too!

Worth noting that we're going to download the logs from dates defined in the picker implemented by Kenroy on https://github.com/Automattic/wp-calypso/pull/74914 and the type from the active tab 👍

**Comment by mpkelly** [comment]
@zaguiini , @vykes-mac. Ok, I am testing locally now then will update.

**Comment by mpkelly** [comment]
This is working well. 

I found one issue: when I download the web logs, the record count does not match the UI. I get more in the downloaded file than I see in the UI (10455 vs 10427):

Screenshot 2566-03-29 at 09 48 11

Screenshot 2566-03-29 at 09 48 14

I checked the first records and last records in the downloaded file, and they match the UI :-) So somewhere in between, we get extra records. I will merge this, and have created https://github.com/Automattic/dotcom-forge/issues/2073 to investigate this issue.

**Pull request merged**
