### PR TITLE
Framework: Load extension reducer from it's section bundle

### PR DESCRIPTION
**Pull request by timdream**
A `loadExtensionReducer()` function is implemented in the loader so the reducers from the extensions directory can be loaded only when it needs.

This would allow Webpack to move extension reducers to their own bundles from the build bundle.

It's important to note that the change assumes the rest of Calypso does not access extension states. The extension data-layer loader has already made that assumption, but there is no code guarding that (that I am aware of).

This is part of #19829.

### CODE REVIEW

**Comment by timdream** [comment]
This removes `extensions` directory entirely from the build bundle, which saves ~163 KB (parsed size).

**Comment by jsnajdr** [comment]
Thanks @timdream, this looks promising :+1:

There's one more problem to solve with dynamic reducers: loading and saving the serialized state from and to Indexed DB. When the serialized state is loaded during app boot, the extension reducers are not there yet and the extension state cannot be populated. That needs to happen later, as part of the extension initialization.

Can you please look at how Calypso serializes and unserializes state and how that needs to change in order to support dynamic extensions?

One idea I got was serializing the state not as one giant tree, but divide it into several subtrees. One `root` and many others, one per extension.

Another is to have multiple Redux stores, but I'm afraid that would lead to complexity explosion -- connecting components to multiple stores, being very careful to which stores we dispatch actions and select data from... It doesn't look very attractive at first sight.

Cc: @coderkevin and @gwwar who will likely be very interested in how state serialization can evolve to support extensions.

**Comment by timdream** [comment]
@jsnajdr Thanks for the reminder. Yes, the current commit does not consider persistence. Looking into how persistence is implemented, I can see a few flaws at least:

1. It replaces the reducer function in effect, but the reducer function imported by `initial-state.js` was not updated.
2. the placeholder reducer function occupies the `extensions` namespace did not opt-in persistence; our version of `combineReducers` will result in the default value as the result of deserialization and serialization.
3. Even if we correct (1), the replaced extensions reducer will produce "key not found" error when it encounters states from extension B while we are at extension A page.

I have not make up my mind on the best way to approach this. The state of extensions can't be deserialized w/o its reducers and schema, but they have to appear in the serialized state object to be saved. I should come up with a good enough placeholder reducer function to achieve these requirements before this can move forward.

**Comment by timdream** [comment]
I am closing this since #20542 seems to be what we want.

**Pull request closed without merging**
