### PR TITLE
Jetpack Cloud: Correctly auto-route when the primary site is not Cloud-eligible

### PR DESCRIPTION
**Pull request by mattgawarecki**
#### Changes proposed in this Pull Request

* Create a new route for Jetpack.com called `/landing/:site` that determines the correct "home" page to see for the selected site.
* Create a new site-generic route for Jetpack.com called `/landing` that brings up the site selector and then uses that selection on `/landing/:site`.
* Change the logic in the `/` route to redirect to `/landing/<primary site>`. This should accomplish the following:
  * For people with a primary site that's eligible for Cloud products: automatically go to Backup or Scan, whichever is appropriate.
  * For people with no sites, or an ineligible primary site: automatically go to the site selector. When a site is selected, the above-mentioned logic in `/landing/:site` takes over.
* Modify the `Home` component to work with any given site, not just the primary site.
* Rename `Home` to `Landing`, to match the new `/landing` routes.

#### Implementation notes

* The flow here had my mind in knots as I worked on a fix, so I'll try to explain it as concisely as I can:
  1. When a browser hits `cloud.jetpack.com`, we first check whether their primary site has access to the Jetpack.com interface.
  2. If yes, our goal is to show the "correct" landing page, based on which products the primary site has purchased. For sites with Scan *only*, we show Scan; for sites with Backup, we show the Backup page; and for sites with neither, we show the Backup upsell.
  3. If the primary site is not cleared to access the Jetpack.com interface, we want to allow the user to choose one of their sites to continue with. Only eligible sites are visible in the site selector. For whichever site is selected, we continue as in step 2.

* The biggest wrinkle in accomplishing the flow from above, is that we have two competing flows that each require a page render:
  1. When any site is selected, we need to know if it has Backup and/or Scan. This requires API data we get from the `QueryRewindCapabilities` component.
  2. When the primary site isn't selected (or able to be selected), we need the user to select a site using the site selector.

* I'd love to have done everything on the same page, but the site selector UI is almost (if not always) called as a middleware function instead of being rendered directly. To solve this contention and to avoid a full dive into the innards of how site selection works, I added an extra "in-between" route (`/landing`) to handle where to redirect. I'm not completely satisfied with this approach, but I didn't see another (reasonably easy) way to do it. Feedback definitely welcome if anyone has ideas!
* I wrote the header copy for the site selector to say "Select a site to open Jetpack.com." Is that acceptable?

Fixes `1164141197617539-as-1174896175986471`

#### Testing instructions

**Be on the look-out:** it's possible that you could be asked to select a site even if one's already been selected. I believe this is a separate, ongoing issue caused by a race condition, but I don't know enough about it to create an issue yet. If you encounter this, please mention it on this PR or contact me directly.

**Case 1:**
* On your WordPress.com account, set your primary site to a site that's NOT eligible for Jetpack Cloud (e.g., a WordPress.com Simple site).
* Navigate to `/` on your development instance of Jetpack.com and verify that you're redirected to `/landing`, which shows the site selector.

**Case 2:**
* On your WordPress.com account, set your primary site to a site that's eligible for Jetpack Cloud (Jetpack site, non-Atomic).
* Navigate to `/` on your development instance of Jetpack.com and verify that you're automatically redirected to the correct page: the Backup page if you have Backup, the Scan page if you don't have Backup but do have Scan, or the Backup upsell if you have neither.

**Case 1 and 2:**
* Visit `/landing` and verify that the site selector is displayed.
* Select a site and verify that you're redirected correctly, the same way as above.
* Visit `/landing/<site slug>` directly for a Cloud-eligible site and verify that you're redirected correctly.
* Visit `/landing/<site slug>` for a non-eligible site and verify that you're directed to the site selector.
* Visit `/landing/<site slug>` for a random/non-existent site and verify that you're directed to the site selector.

##### Site selector ("open Jetpack.com")
image

### CODE REVIEW

**Comment by ChaosExAnima** [comment]
Seeing strange indentation:
Screen Shot 2020-07-07 at 2 46 53 PM

Looks like there's this CSS:
```css
.sites__select-heading strong {
   text-transform: capitalize;
}
```
Otherwise, functionality looks okay.

**Comment by mattgawarecki** [comment]
> Seeing strange indentation:
> Screen Shot 2020-07-07 at 2 46 53 PM

Oh wild! The capitalization doesn't show up that way in Firefox, but it does in Chrome. I don't want to disrupt the existing style rules for the site selector, so is there maybe a way to change the copy that gets around CSS capitalization? cc @keoshi

**Comment by ChaosExAnima** [comment]
> I don't want to disrupt the existing style rules for the site selector, so is there maybe a way to change the copy that gets around CSS capitalization?

Perhaps you can wrap it in a `span` with a unique class and target that?

**Comment by mattgawarecki** [comment]
I added an inline style to suppress capitalization for Jetpack.com (with an explanation for future-us in code comments), since this is still very much a one-off case.

Also, interesting discovery: I was still including navigation as a (rendered, but invisible) component on the `/landing` page, so I removed that. Apparently the `h2` styles for the navigation sidebar partially bleed over into the rest of the page? There's a rule for `html h2` in there that was making the entire landing heading bold.

Anyway, here's what the new landing looks like. Much more polished, IMO:

image

**Pull request merged**
