### PR TITLE
Fix/74148 update copies for woo commerce

### PR DESCRIPTION
**Pull request by arjunpotter17**
Related to #74148, woo commerce

## Proposed Changes
Change the heading from Get started in minutes to Let's get started.

Change the description from First, let's create your account. Already registered? Log in to All Woo stores are powered by WordPress.com. Please create an account to continue. Already registered? Log in.

Change the heading from Get started in minutes to Let's get started.

Change the description from First, log in with your WordPress.com account. Don't have an account? Sign up to All Woo stores are powered by WordPress.com! First, select the account you'd like to use.

Change the description from First, select the account you'd like to use. to All Woo stores are powered by WordPress.com! Please, log in to continue. Don't have an account? Sign up.
*

## Testing Instructions

1. Log in `WP` account and log out `WC` account
2. Go to woocommerce.com
3. Click on "Get Started"
4. Replace the host with Calypso Live or your local Calypso host
5. Confirm the changes are as described in the #74148

## Pre-merge Checklist

- [x] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [x] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

account-new-user

account-existing-user-logged-in-1

account-existing-user-logged-out-1

### CODE REVIEW

**Comment by chihsuan** [comment]
Hey @arjunpotter17 Thanks for the contribution! I noticed that the Code Style check is failing. Could you please fix them? 

Screenshot 2023-03-20 at 14 11 35

Besides, the login screen seems incorrect. The description should be `All Woo stores are powered by WordPress.com! Please, log in to continue. Don't have an account? Sign up.`

Screenshot 2023-03-20 at 14 16 58

You can go to this link to test it.

http://calypso.localhost:3000/log-in?redirect_to=https%3A%2F%2Fpublic-api.wordpress.com%2Foauth2%2Fauthorize%2F%3Fresponse_type%3Dcode%26client_id%3D50916%26state%3Db10d8bc2bc2217c45ce98dc6fb8587cc4f2f0c3b23d077472ae7586c535894ef%26redirect_uri%3Dhttps%253A%252F%252Fwoocommerce.com%252Fwc-api%252Fwpcom-signin%253Fnext%253Dstart%2526nuxentrysource%253Dsignup_menu%26blog_id%3D0%26wpcom_connect%3D1%26wccom-from%26calypso_env%3Dproduction%26jetpack-code%26jetpack-user-id%3D0%26action%3Doauth2-login%26from-calypso%3D1&client_id=50916&signup_url=%2Fstart%2Fwpcc%2Foauth2-user%3Fref%3Doauth2%26oauth2_redirect%3Dhttps%253A%252F%252Fpublic-api.wordpress.com%252Foauth2%252Fauthorize%252F%253Fresponse_type%253Dcode%2526client_id%253D50916%2526state%253Db10d8bc2bc2217c45ce98dc6fb8587cc4f2f0c3b23d077472ae7586c535894ef%2526redirect_uri%253Dhttps%25253A%25252F%25252Fwoocommerce.com%25252Fwc-api%25252Fwpcom-signin%25253Fnext%25253Dstart%252526nuxentrysource%25253Dsignup_menu%2526blog_id%253D0%2526wpcom_connect%253D1%2526wccom-from%2526calypso_env%253Dproduction%2526jetpack-code%2526jetpack-user-id%253D0%2526action%253Doauth2-login%2526from-calypso%253D1%26oauth2_client_id%3D50916

**Review by chihsuan — CHANGES_REQUESTED** [review]
Hey @arjunpotter17 Thanks for the contribution! I noticed that the Code Style check is failing. Could you please fix them? 

Screenshot 2023-03-20 at 14 11 35

Besides, the login screen seems incorrect. The description should be `All Woo stores are powered by WordPress.com! Please, log in to continue. Don't have an account? Sign up.`

Screenshot 2023-03-20 at 14 16 58

You can go to this link to test it.

http://calypso.localhost:3000/log-in?redirect_to=https%3A%2F%2Fpublic-api.wordpress.com%2Foauth2%2Fauthorize%2F%3Fresponse_type%3Dcode%26client_id%3D50916%26state%3Db10d8bc2bc2217c45ce98dc6fb8587cc4f2f0c3b23d077472ae7586c535894ef%26redirect_uri%3Dhttps%253A%252F%252Fwoocommerce.com%252Fwc-api%252Fwpcom-signin%253Fnext%253Dstart%2526nuxentrysource%253Dsignup_menu%26blog_id%3D0%26wpcom_connect%3D1%26wccom-from%26calypso_env%3Dproduction%26jetpack-code%26jetpack-user-id%3D0%26action%3Doauth2-login%26from-calypso%3D1&client_id=50916&signup_url=%2Fstart%2Fwpcc%2Foauth2-user%3Fref%3Doauth2%26oauth2_redirect%3Dhttps%253A%252F%252Fpublic-api.wordpress.com%252Foauth2%252Fauthorize%252F%253Fresponse_type%253Dcode%2526client_id%253D50916%2526state%253Db10d8bc2bc2217c45ce98dc6fb8587cc4f2f0c3b23d077472ae7586c535894ef%2526redirect_uri%253Dhttps%25253A%25252F%25252Fwoocommerce.com%25252Fwc-api%25252Fwpcom-signin%25253Fnext%25253Dstart%252526nuxentrysource%25253Dsignup_menu%2526blog_id%253D0%2526wpcom_connect%253D1%2526wccom-from%2526calypso_env%253Dproduction%2526jetpack-code%2526jetpack-user-id%253D0%2526action%253Doauth2-login%2526from-calypso%253D1%26oauth2_client_id%3D50916

**Comment by chihsuan** [comment]
Hey @arjunpotter17 Would you be able to address the PR feedback? Let me know if you have any questions.

**Comment by arjunpotter17** [comment]
Hey @chihsuan, I was a bit busy. I'll look into it today and let you know if I run into any problems. Thanks!

**Comment by arjunpotter17** [comment]
Hey @chihsuan, I fixed the login screen text. Actually, there is a slight error in the screenshots posted in the issues tab. I had followed that. Also, I don't know much about the code style test. Can you tell me more about what the issues could be and and how I can fix them?

**Comment by chihsuan** [comment]
> I fixed the login screen text. Actually, there is a slight error in the screenshots posted in the issues tab. I had followed that. Also, I don't know much about the code style test. Can you tell me more about what the issues could be and and how I can fix them?

Hey @arjunpotter17 Thanks for fixing the text! You can find the code style errors in this screenshot.



If you're using VSCode, I think you use it to reformat the code with prettier. 

https://marketplace.visualstudio.com/items?itemName=esbenp.prettier-vscode

Otherwise, you can run ` ./node_modules/.bin/prettier --ignore-path .eslintignore --write [files you changed]`

**Comment by chihsuan** [comment]
@arjunpotter17 Any updates on this?  🙂

**Comment by arjunpotter17** [comment]
Hey @chihsuan, sorry I couldn't reply. I see that you've added commits. Did you fix the code style issue by yourself? Is there anything you want me to do?

**Review by chihsuan — COMMENTED** [review]
I just helped fix the linting and updated the copies.

@ilyasfoo Could you review this PR when you get a chance? Thanks!

**Review by chihsuan — APPROVED** [review]

**Comment by chihsuan** [comment]
> sorry I couldn't reply. I see that you've added commits. Did you fix the code style issue by yourself? Is there anything you want me to do?

@arjunpotter17 No worries. I've fixed it. 🙂

**Review by ilyasfoo — APPROVED** [review]
Thanks for working on this, @arjunpotter17 and helping out @chihsuan! Tested well, LGTM! 🚢

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/7893634

Thank you @arjunpotter17 for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/7893634).

**Pull request merged**
