### PR TITLE
A4A: Implement the banner section for the new migrations page.

### PR DESCRIPTION
**Pull request by jkguidaven**
This PR implements the banner section on the new migrations page.

Screenshot 2024-10-29 at 4 22 47 PM

Depends on https://github.com/Automattic/wp-calypso/pull/95788
Closes https://github.com/Automattic/automattic-for-agencies-dev/issues/1375 

## Proposed Changes

* The new section utilizes the `SimpleList` component, which I have relocated to the global shared folder, as it is now being used in various sections beyond the Marketplace.
* Implement the Banner based on the new design. Add a new background image for the PageSection to match the new design.

## Why are these changes being made?

* This implements the banner for the new migrations page, which will be the first element visible.

## Testing Instructions

* Use the A4A live link and go to the `/migrations` page.
* Confirm you see the banner and it matches the design.
* Test that the banner is responsive for any device screen.

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Review by yashwin — APPROVED** [review]
Looks good overall!

- I think we can keep the gap the same as the design here? 

Screenshot 2024-11-04 at 12 37 47 PM

- Not related to the PR. It looks like the sidebar navigation is missing on the mobile view

Screenshot 2024-11-04 at 12 36 25 PM

**Comment by jkguidaven** [comment]
> Looks good overall!
> 
> * I think we can keep the gap the same as the design here?
> 
> Screenshot 2024-11-04 at 12 37 47 PM
> * Not related to the PR. It looks like the sidebar navigation is missing on the mobile view
> 
> Screenshot 2024-11-04 at 12 36 25 PM

Thanks for the review. I've made some changes to address your comments. 🙏

**Review by yashwin — APPROVED** [review]
Thanks for addressing my comments. LGTM!

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/16982765

Some locales (Hebrew, Japanese) have been temporarily machine-translated due to translator availability. All other translations are usually ready within a few days. Untranslated and machine-translated strings will be sent for translation next Monday and are expected to be completed by the following Friday.

Thank you @jkguidaven for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/16982765).

**Pull request merged**
