### PR TITLE
Stats: add rel=noopener to stats list actions.

### PR DESCRIPTION
**Pull request by timmyc**
This branch adds `rel=noopener` to external links in stats lists.  While doing the update, I updated the component to ES6 syntax and removed `React.createClass`.

__To Test__
- Open up a site stats page for a period ( day, week, month etc )
- Click on an external link icon under Posts & Pages
- Verify the page or post opens in a new tab and the calypso page remains the same

/cc @bluefuton 

Test live: https://calypso.live/?branch=update/stats/noopener

### CODE REVIEW

**Comment by aduth** [comment]
Related: #7680

**Comment by timmyc** [comment]
Noting also that the probably bigger vulnerability in stats is the referrers list.  Currently, the referrers are opened up using `window.open` [here](https://github.com/Automattic/wp-calypso/blob/master/client/my-sites/stats/stats-list/stats-list-item.jsx#L90-L93) since stats list items are rendered as `<li>`s and not `<a>`s.

**Comment by bluefuton** [comment]
Looks great @timmyc!

Is there a rationale for leaving `noreferrer` out? I've added both in #7680.

**Comment by timmyc** [comment]
> Is there a rationale for leaving noreferrer out?

added in 4a69084

**Comment by bluefuton** [comment]
Looks good to me! 🚢

**Pull request merged**
