### PR TITLE
Import Signup Flow: Remove loading notice

### PR DESCRIPTION
**Pull request by spen**
#### Changes proposed in this Pull Request

This PR removes the loading notice in the importer signup flow from the floating top right. We already show the loading state with the busy styling of the input button.
The plan was originally to move the notice to be underneath the URL input - I've left some of the related code changes in place, as they're still an improvement.

#### Testing instructions

- Start at http://calypso.localhost:3000/start/import/from-url
- Enter an invalid URL
  - Make sure that the error notice still shows in the expected place, below the URL
- Enter a valid, parsable URL & hit enter
  - You should not see a notice now, just the busy styled button

### CODE REVIEW

**Comment by andfinally** [comment]
This is a nice improvement! Tests OK in FF and on iPhone 6S+.

**Comment by shaunandrews** [comment]
I like it better below the input, but I don't think we need this notice at all. Lets remove it.

**Comment by spen** [comment]
Thanks for the review @andfinally, we've been discussing whether or not we really need the notice at all, or whether it's overkill. I'll repurpose this PR to get rid of the notice completely :)

**Comment by spen** [comment]
@andfinally & @shaunandrews - I've updated the code and the description, would you mind giving it another run through please? IMO, it's much better without the notice.

**Comment by spen** [comment]
Thanks for giving this a spin @mattsherman!

> the check seems to take a long time...

Agreed, we _should_ in theory be able to do the check quite quickly for a lot of sites - especially anything without a custom domain. I think the only hold up is cases where we need a first pass of the site-parser and once we have the detection work in place we should see a lot less domains that need to go through that first pass :)

**Pull request merged**
