### PR TITLE
SegmentedControl: migrate CSS to webpack

### PR DESCRIPTION
**Pull request by jsnajdr**
Migrates `SegmentedControl` CSS to webpack and also improves the DX of the component:

First, the `SimplifiedSegmentedControl` is re-implemented in terms of `SegmentedControl` and `SegmentedControlItem`. No duplicate code (like the HTML markup).

Second, make `SegmentedControlItem` a property of the parent component: `SegmentedControl.Item`. They are always used together and the DX is better:

Before:
```jsx
import SegmentedControl from 'components/segmented-control';
import SegmentedControlItem from 'components/segmented-control/item';

return (
  <SegmentedControl>
    <SegmentedControlItem />
  </SegmentedControl>
);
```

After:
```jsx
import SegmentedControl from 'components/segmented-control';

return (
  <SegmentedControl>
    <SegmentedControl.Item />
  </SegmentedControl>
);
```

We need just one `import` statement.

**How to test:**
Verify the various usages of the component. Used at a lot of places, but the refactoring is very straightforward and low-risk.

### CODE REVIEW

**Review by flootr — APPROVED** [review]
I tested various usages and they all seem to work fine! Code changes look good 👍

**Comment by diegohaz** [comment]
Just linking the discussion on the other PR as that relates to these changes as well: https://github.com/Automattic/wp-calypso/pull/35086#issuecomment-520631823

**Review by diegohaz — APPROVED** [review]
Resolved conflicts with master, and e2e tests started failing. But they seem flacky and unrelated to this change.

Code looks good. I tested a few screens with this component and everything seems to work.

**Comment by jsnajdr** [comment]
> Resolved conflicts with master

Thanks for the review @diegohaz! I usually prefer rebasing the branch rather than merging master into it. The commit history is then nicer and easier to work with.

**Comment by simison** [comment]
I'm not entirely sure what's going on but I see this on Jetpack plans grid (https://wordpress.com/plans + choose a Jetpack site):

Screenshot 2019-08-20 at 10 06 28

I see it only occasionally, like every 5th refresh. When it's broken, I see the CSS that I have in the screenshot.

I suspect this PR changed this but I haven't tested yet to confirm.

When it works, I see this instead:

image

Note `margin: 0` which seems to cause the trouble.

Occurs in all screen sizes both on Firefox and Chrome.

**Comment by jsnajdr** [comment]
Thanks for noticing and reporting @simison! Fix is ready for review in #35607.

**Pull request merged**
