### PR TITLE
Reader: Fix action layout in full post view on mobile

### LINKED ISSUE #545: Reader: Top bar doesn't scale well in narrow screens at top of single post view
With the Desktop app at minimum width, there is a styling issue with the TopBar when viewing a post in the reader:

### PR DESCRIPTION
**Pull request by blowery**
The action bar on the top of the full post view in Reader is getting crowded, and causing issues like this:
72ba5de2-560f-11e5-8b17-75ab3ab64c0b

This PR moves the site title out of the action bar and above the feature image (or title, if no image exists):

screen shot 2015-10-29 at 2 01 59 pm

screen shot 2015-10-29 at 2 02 35 pm

Fixes #545

### CODE REVIEW

**Comment by blowery** [comment]
Fixes #942

**Comment by shaunandrews** [comment]
There's currently a problem with the way this works with non-.com blogs (like RSS feeds) and it breaks everything. A little while ago @blowery mentioned he had a way to fix.

**Comment by blowery** [comment]
Yup, we need a new component that can take care of making up the fake site we pass to the site component when we only have a feed. Once we have that, we can use it.

**Comment by shaunandrews** [comment]
Boom, this looks good to me. :+1:

**Pull request merged**
