### PR TITLE
GitHub Deployments: include link to workflow recipes

### PR DESCRIPTION
**Pull request by mpkelly**
Closes https://github.com/Automattic/dotcom-forge/issues/6062

**Before** 

Screenshot 2567-03-18 at 09 35 21

**After** 

Screenshot 2567-03-18 at 10 32 55

## Proposed Changes

* Add a link to workflow recipes
* Remove the previous hint about extending workflow which was combined in this change

## Testing Instructions

* Create a new deployment and choose "advanced" mode
* Check link works

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Comment by zaguiini** [comment]
Looking good!

WDYT of moving the message below the workflow picker?

cc @javierarce for thoughts

**Comment by mpkelly** [comment]
> Looking good!
> 
> WDYT of moving the message below the workflow picker?
> 
> cc @javierarce for thoughts

Here is a preview of what I think you're asking. I wonder if we should only show the `You can start with our basic workflow file then extend it.` when they create a new workflow rather than always. And maybe the `Looking for inspiration? See our workflow recipes` part could be shown separately at the bottom somewhere. 

Screenshot 2567-03-19 at 12 43 43

**Comment by zaguiini** [comment]
>I wonder if we should only show [...] when they create a new workflow

They could have an existing workflow that they wish to extend. If we do that, they won't see the message.

>And maybe the Looking for inspiration? See our workflow recipes part could be shown separately at the bottom somewhere.

It looks nice there. Seems it'd get a bit lost if put elsewhere.

---

I'm starting to think the copy could be improved. What if we went with something like "A workflow file allows you to process the files from the repository before sending them to your WordPress.com site. Wondering what your possibilities are? Check our recipes."

Obviously not exactly that, but the message is clearer. And it could be added below the "Pick your deployment mode" heading 👀

**Comment by javierarce** [comment]
Perhaps we could place it as a dropdown hint so it looks more integrated. I've also changed the wording slightly:

image

> I'm starting to think the copy could be improved. What if we went with something like "A workflow file allows you to process the files from the repository before sending them to your WordPress.com site. Wondering what your possibilities are? Check our recipes."

I believe the information about what a workflow entails fits better in the documentation. We already explain that in the first paragraph when they follow that link, but we could make it even more clear.

**Comment by paulopmt1** [comment]
Sending the latest design suggestion: 

image

**Pull request merged**
