### PR TITLE
Update: Social Logo to the latest version.

### PR DESCRIPTION
**Pull request by enejb**
Added hover styling on the dev/docs
Added Share Icon
Update twitter logo 
Added twitter-alt logo.

The reason why the twitter-alt is more for consistency. 
Most of the services have a box around the logo. 

After:
screen_shot_2016-02-01_at_11_33_26

cc @alternatekev

### CODE REVIEW

**Comment by alternatekev** [comment]
> The reason why the twitter-alt is more for consistency. 

To clarify: the naming convention for the other roundrect logos is this:
- blogger.svg: roundrect
- blogger-alt.svg: no roundrect
- tumblr.svg: roundrect
- tumblr-alter.svg: no roundrect

This PR just adds a roundrect twitter logo in place of the twitter.svg file (which is in accordance with the examples above), and moves what used to be twitter.svg over to twitter-alt.svg.

**Comment by alternatekev** [comment]
Pinging @drw158 and @kellychoffman

**Comment by drw158** [comment]
I'm fine with the naming convention, but maybe we should consider a suffix like "-shape" instead. Some logos wouldn't have a suffixed version because the official logos already have a shape (eventbrite, FB, etc.). I'm fine with the alt suffix for now.

Share icon: In Gridicons intentionally went with a different share icon. https://github.com/Automattic/gridicons/issues/39

I think Gridicons and Social Logos should use the same share icon.

**Comment by kellychoffman** [comment]
Do all the roundrect icons share the same border radius?

**Comment by alternatekev** [comment]
I looked in the AI file and it seems like they’re all 2px border radius except Facebook, which is 1px. I think that’s their guideline.

**Comment by alternatekev** [comment]
When this PR is merged, I'll be able to get #1474 past this stage:

screen shot 2016-02-01 at 2 59 48 pm

**Comment by drw158** [comment]
Yep, Facebook has a smaller border radius; the vector is straight from their brand resources.

**Comment by alternatekev** [comment]
@kellychoffman Is the border radius a blocker for this?

**Comment by kellychoffman** [comment]
Not sure, its hard to tell how they will all look together on the sharing page.

**Comment by alternatekev** [comment]
Code looks good to me, since it's generated in the social-logos repo.

**Pull request merged**
