### PR TITLE
Submit already WPCOM survey to endpoint, route user to survey step when WPCOM detected

### PR DESCRIPTION
**Pull request by Imran92**
Related to https://github.com/Automattic/wp-calypso/issues/95021

## Proposed Changes

* Brings users to the survey step if WPCOM is detected
* Submits the data to the backend after taking survey
* Disable form when submitting data

## Why are these changes being made?

* To understand why the user submitted a site which is already on WPCOM

## Testing Instructions

Note: **_Continue Anyways_** path means if you submit a site with wrong URL, wrong creds (not invalid, only wrong) or a site that's already on WPCOM, we show error messages, but the submit button changes to **_Continue Anyways_** in the Credentials form. Which lets you submit the ticket despite having those errors.

- Apply this patch in your sandbox - 
- Make sure WPCOM requests are pointed to your sandbox
- Proceed through the migration flow.
- On the "How do you want to migrate?" step, choose "Do it for me".
- In the credentials form, test the following scenarios -

# Enter a non WPCOM WordPress site
- Try with wrong credentials and you should be able to submit in the Continue Anyways path.
- Try with the right credentials and the submission should happen without any issue
- You should not see the survey form
- Take the survey by selecting one or more fields, try also adding the Other details and submit
- You should be taken to the next page
- On ZD, you should be able to see a comment with the result of your survey

# Enter a WPCOM site
- Try with right/wrong credentials and you should be able to submit in the Continue Anyways path, you should see an error about the site being on WPCOM already
- If you submit using Continue anyways, it shouldn't farther show you any error even you provide wrong creds
- You should see the survey form

# Enter a non WP site
- You should see an error under the URL field
- You should be able to submit in the Continue anyways path
- You should not see the survey form

https://github.com/user-attachments/assets/ab95f85f-7e44-47c6-ba81-b72c21f3717e

## Pre-merge Checklist

- [x] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [x] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [x] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [x] Have you checked for TypeScript, React or other console errors?
- [x] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Review by fditrapani — COMMENTED** [review]
Thanks for putting this together @Imran92! I noticed two small things: When I get to the new screen, I'm not seeing the site name in the copy under the title:

image

Also, there's a line break between the two sentences. I think that happened co-incidentally in the design. Can we remove the line break so they appear on the same line if there's enough space? 

image

**Review by gabrielcaires — APPROVED** [review]
LGTM!
I updated the PR with some improvements.

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/16898974

Some locales (Hebrew, Japanese) have been temporarily machine-translated due to translator availability. All other translations are usually ready within a few days. Untranslated and machine-translated strings will be sent for translation next Monday and are expected to be completed by the following Friday.

Hi @Imran92, could you please edit the description of this PR and add a screenshot for our translators? Ideally it'd include all of the following strings:
- `Your site is already on {{break}}WordPress.com{{/break}}`
- `Let's figure out your next steps for {{strong}}%(from)s{{/strong}} together. Please complete the form below.`

Thank you in advance!

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/16898974).

**Pull request merged**
