### PR TITLE
Performance Profiler: adds social media share.

### PR DESCRIPTION
**Pull request by cpapazoglou**
Fixes https://github.com/Automattic/dotcom-forge/issues/8822

## Proposed Changes

* Adds sharing popover
* Adds twitter, facebook, linkedin, tumblr services
* Uses `share_link` from the backend

## Testing Instructions

* Visit `http://calypso.localhost:3000/speed-test-tool?url=https%3A%2F%2Fblecyclingclub.gr%2F&hash=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6NzAyOH0.bKYiVrIqTJtq0QP2eeZCsP8wRw1-e6sCAxVDsn89QCg&tab=mobile`
* Click Share Results
* You should land in twitter with a default prompt
* Repeat for facebook, linkedin

CleanShot 2024-09-10 at 15 15 07

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Comment by cpapazoglou** [comment]
The metatags don't seem to be rendered.

**Review by epeicher — APPROVED** [review]
I have tested it, and it works as advertised. I have also checked the popup in different screen sizes and it works great! LGTM :shipit: 

|X | LinkedIn|Tumblr |Facebook|
|-------|------|-------|------|
|    CleanShot 2024-09-10 at 16 39 14@2x |     CleanShot 2024-09-10 at 16 41 43@2x |      CleanShot 2024-09-10 at 16 41 32@2x    |  CleanShot 2024-09-10 at 16 49 00@2x   |

**Review by gavande1 — APPROVED** [review]
Works Great. Thanks Harris!

**Review by epeicher — COMMENTED** [review]
You can ignore this comment, I added it to the wrong PR 🙏

**Pull request merged**
