### PR TITLE
[E2E] Embed block fixes

### PR DESCRIPTION
**Pull request by fullofcaffeine**
#### Changes proposed in this Pull Request

All embed blocks (the ones touched by our E2E tests at least) now follow a similar naming/classification standard. They now all have the same ariaLabel and embed prefix for the .editor-block-list-item CSS class. 

This fixes the selectors so that the elements can be found on the page.

#### Outstanding questions

* Is it a good idea to have identical `aria-labels` for these blocks? They are all "embed" blocks, but they serve different purposes.

### CODE REVIEW

**Comment by fullofcaffeine** [comment]
I don't know if it'll be enough to just change the embed blocks to be selected by the same aria-label as I've done in the first commit here. It seems to be used to select them on the page for a scenario where multiple embed blocks are present. 

I'm waiting for the tests to finish, but if they continue to fail, we will need to think of another way of selecting each block or re-organize the scenario to test a block per time in the editor.

**Comment by ockham** [comment]
> I've looked at the three blocks in the editor, and they now have pretty much the same markup. To test, open a test edge site and add the following blocks to the page: Instagram, Twitter, and Youtube. Now, inspect their markup in the Elements inspector. You'll see all of them have pretty much the same markup, with the only difference being the ID hash.

Yeah, I remember seeing that when I was working on some oEmbeds related stuff in Gutenberg the other day. I agree that we'll probably want to differentiate more between them. This is something we'll need to address in Gutenberg though, and it likely won't make it into v8.9, so we also need a workaround for our e2e tests.

**Comment by ockham** [comment]
I think we can change those selectors to look for and `<iframe />`s with the `title` attribute set to

- `Embedded content from instagram.com`,
- `Embedded content from twitter`, and
- `Embedded content from youtube.com`, respectively.

image

image

image

(Those are coming from https://github.com/WordPress/gutenberg/blob/a610923b7728f1192f9745a55390a7abb0df576e/packages/block-library/src/embed/embed-preview.js#L78)

**Comment by fullofcaffeine** [comment]
> I think we can change those selectors to look for and `<iframe />`s with the `title` attribute set to
> 
>     * `Embedded content from instagram.com`,
> 
>     * `Embedded content from twitter`, and
> 
>     * `Embedded content from youtube.com`, respectively.
> 
> 
> image
> 
> image
> 
> image
> 
> (Those are coming from https://github.com/WordPress/gutenberg/blob/a610923b7728f1192f9745a55390a7abb0df576e/packages/block-library/src/embed/embed-preview.js#L78)

I like that idea, but it seems this changeset is not part of 8.9? I couldn't find this attribute on embed blocks in a test site running 8.9.

That being said, I did start working towards this, there's some initial work I committed today. The upgrade test is still failing just when it starts the edge part of the test, possibly related to https://github.com/Automattic/wp-calypso/blob/master/test/e2e/lib/gutenberg/gutenberg-editor-component.js#L203, but I'll look tomorrow (or you can if you're feeling adventurous).

**Comment by ockham** [comment]
Oh, I was thinking we'd need to change the selectors only in the file I was mentioning, https://github.com/Automattic/wp-calypso/blob/38b51c6665cd2029a6fe6d0eca42893e7eefcf1c/test/e2e/specs/wp-calypso-gutenberg-post-editor-spec.js. Let me see if that does the trick.

**Comment by ockham** [comment]
Yep, that worked :partying_face: The 'Click to Tweet' block seems to be the last remaining issue now.

**Comment by ntsekouras** [comment]
> Yep, that worked 🥳 The 'Click to Tweet' block seems to be the last remaining issue now.

I don't have all the context here, but when working with the `embed` block variations, I used snapshots to make sure they were correct. (https://github.com/WordPress/gutenberg/blob/87c4dc536f52254975b4b5e192e36f7d98b6f0b7/packages/e2e-tests/specs/editor/various/embedding.test.js#L211)

Since @ockham found a workaround for some of the tests, if the click to edit is still a problem, another approach would be to select the `tweet` block with key navigation events. Would that apply here?

**Comment by ockham** [comment]
> > Yep, that worked 🥳 The 'Click to Tweet' block seems to be the last remaining issue now.
> 
> I don't have all the context here, but when working with the `embed` block variations, I used snapshots to make sure they were correct. (https://github.com/WordPress/gutenberg/blob/87c4dc536f52254975b4b5e192e36f7d98b6f0b7/packages/e2e-tests/specs/editor/various/embedding.test.js#L211)
> 
> Since @ockham found a workaround for some of the tests, if the click to edit is still a problem, another approach would be to select the `tweet` block with key navigation events. Would that apply here?

Thanks Nik. A number of misunderstandings here, I'll try to clarify:

- The problem with the embeds has been resolved (by changing e2e selectors).
- The remaining problem is with the "Click to Tweet" block (not the Twitter embed). That block is part of the CoBlocks collection of blocks that we're running on WP.com Furthermore, the failing test is checking for the presence of the rendered block on the frontend (rather than the editor). This seems to happen because we get stuck when attempting to leave the editor because dirty state detection seems broken (see my previous comment).

**Comment by ockham** [comment]
The reason for the "Changes you made may not be saved" warning after publishing a post that contains a "Click to Tweet" CoBlock seems to be that the block has a `url` attribute that contains to the current post's URL (plus that URL is also found in the block's content). If the block is inserted into a newly created post (as it is in e2e tests), that `url` attribute will be set to something like `https:\/\/example.com\/2020\/09\/03\/auto-draft\/`. If the post is saved, it will be updated to use the post's slug (which is based on the post title), e.g. `https:\/\/example.com\/2020\/09\/03\/click-to-tweet-test\/`.

This seems rather inherent in the way the block works. In e2e tests, we could fix it by saving the post before publishing and viewing it, so that is already given the same slug as it would get upon publishing.

**Comment by ockham** [comment]
FWIW, here's the relevant block's code: https://github.com/godaddy-wordpress/coblocks/blob/0d644c66e96292baed08472631c0892b6b71e186/src/blocks/click-to-tweet/edit.js#L37-L43

**Comment by ockham** [comment]
Filed upstream issue: https://github.com/godaddy-wordpress/coblocks/issues/1663

**Comment by fullofcaffeine** [comment]
@ockham Thanks thoroughly documenting the issue as you worked towards fixing it <3 

This looks good, let's 🚢 it!

**Pull request merged**
