### PR TITLE
Performance Profiler: handle null values in history chart

### PR DESCRIPTION
**Pull request by gcsecsey**
Closes https://github.com/Automattic/dotcom-forge/issues/9188

## Proposed Changes

* don't render null values as 0 on the history chart
* add Y axis scales to the chart even when all values are 0

## Why are these changes being made?

https://github.com/Automattic/dotcom-forge/issues/9188

## Testing Instructions

* Go to `/speed-test` and start a new test for a site that doesn't have historical data for all 8 weeks, or use this report:
```
/speed-test-tool?url=https://stitchandstyle.ie/&hash=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6NzgyOX0.3nU626e3YxQ7lpMXD6t_zXCwJpCAKUVXDVpNquLh0eM
```
* Check in the API response that not all dates have values in the report
* Check that the history chart renders only the existing data, and that it's rendered correctly
* Check that on the CLS chart, if all values are 0, the Y axis still has a maximum value of 1

| Issue | Before | After |
|--------|--------|--------|
| Null values | CleanShot 2024-09-20 at 15 28 35@2x | CleanShot 2024-09-20 at 15 28 21@2x |
| Graph scaling | CleanShot 2024-09-20 at 15 28 41@2x | CleanShot 2024-09-20 at 15 28 27@2x |

### CODE REVIEW

**Comment by gavande1** [comment]
The changes introduced in PR look good to me. However, I am concerned that showing partial data points might be perceived as a broken chart, and ultimately, something is wrong with the implementation. I am not sure how we can fix it. We probably need to find a better way to communicate discrepancies in historical data.

**Comment by cpapazoglou** [comment]
Let's discuss this in our meetup.

**Comment by gcsecsey** [comment]
The current implementation looks like this with test data that has missing datapoints in the middle of the range:
CleanShot 2024-10-03 at 12 11 12@2x

**Comment by matt-west** [comment]
Thanks for exploring these solutions @gcsecsey!

I think `Version 1` makes most sense here as it's clearer that there’s no data available for the time period. If we wanted to get really fancy, we could grey-out the date ticks that have missing data too (using `Grey 20`) but I’m not sure if we have that much control over them.

`Version 2` could be interpreted that there was a zero value on those two missingdates. Likewise with `Version 3` where someone could use the connecting grey line to read a value off the chart that’s isn’t correct.

**Comment by gcsecsey** [comment]
Thanks @matt-west, I'm merging Version 1 👍

**Pull request merged**
