### PR TITLE
A4A: Update page view tracker to split base path and query parameters.

### PR DESCRIPTION
**Pull request by jkguidaven**
This PR enhances our page view tracking by separating the base path from query parameters, ensuring accurate grouping of page views by the base path.

Closes https://github.com/Automattic/automattic-for-agencies-dev/issues/1249

## Proposed Changes

* Update the `A4APageViewTracker` to separate the query parameters from the base path during page view tracking.

## Why are these changes being made?

To prevent duplicate track event names on the same page, ensure that the submitted path excludes query parameters, treating it as a single entity.

## Testing Instructions

* Use the A4A live link and go to the `/signup?ref=wordpress.com` page.
* Confirm that the page view tracker correctly captures the base path and the ref parameters.
* You can expect this by filtering the network tab in your browser with `.gif` and looking for requests like the one below.
Screenshot 2024-10-16 at 5 15 54 PM

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Review by yashwin — APPROVED** [review]
LGTM!

It works as expected!

**Comment by simonktnga8c** [comment]
I discussed this with @jkguidaven on Slack. My recommendation is to keep setting the "ref" property for the event if there is a URL parameter but not create any other properties from other parameters (this could be a security issue).

**Comment by jkguidaven** [comment]
@simonktnga8c @travisw Thank you for your feedback. I've implemented changes based on your comments. The PR no longer parses the query parameters and attaches them as properties due to security concerns. Additionally, we explicitly track the ref URL parameter on the Signup page, as discussed with Simon.

**Comment by travisw** [comment]
Thanks for the updates @jkguidaven.
I don't think we need to do anything extra in order to track the `ref` property, as including it is already a part of the default behavior for the `calypso_page_view` event and that's working ok. So I think just tweaking the path property like you have is enough.

You can see that `ref` is already being tracked on production.
Screenshot 2024-10-16 at 9 35 43 AM

**Comment by jkguidaven** [comment]
@travisw good catch! I did not know ref is automatically added as property. This has been addressed. 👍

**Comment by jkguidaven** [comment]
I'll merge the PR now since all comments are addressed. Thanks everyone for the review 🙏

**Pull request merged**
