### PR TITLE
Web Preview: Add clipboard url to toolbar

### PR DESCRIPTION
**Pull request by michaeldcain**
This PR adds a `ClipboardButtonInputer` component to the `WebPreview` toolbar with the current external or preview URL when the `showUrl` prop is set.

**Mock:**
showurl

**To Test:**
- Check out branch.
- `ENABLE_FEATURES=post-editor/delta-post-publish-preview make run`
- Publish a new post.
- The full-screen preview will be shown with the post's url in the toolbar
- Copy the URL to the clipboard.

### CODE REVIEW

**Comment by michaeldcain** [comment]
**Current state:**
screen shot 2017-06-17 at 11 09 46 pm

/cc @shaunandrews for design input - leaving the border and the button gives a clear action for the user, but I can remove it and auto-copy on click.

**Comment by shaunandrews** [comment]
I had just the URL there to help keep things simple. My assumption is that this isn't something people use that often. Having the border and button always visible definite makes this feature more obvious, but I wonder if it comes at a cost.

Maybe we keep the border+button visible for now, and see how many people actually use click the URL or button. If its a small number, than we have some justification for hiding until hover.

**Comment by michaeldcain** [comment]
That sounds good to me. I'll make sure that we're tracking the clicks. The border also helps visualize the truncation of longer URLs.

**Comment by mattsherman** [comment]
I don't see a need to tie this to the `post-editor/delta-post-publish-preview` feature flag.

**Comment by michaeldcain** [comment]
>I don't see a need to tie this to the post-editor/delta-post-publish-preview feature flag.

@mattsherman - it's not limited to the flag, it's just that the only place I've passed the prop is on the full-screen EditorPreview, which is behind the flag. Any `WebPreview` or `WebPreviewContent` implementation can use it.

**Comment by mattsherman** [comment]
@michaeldcain How about making it so the component itself intelligently decides when to show the URL -- anytime `externalUrl` is set? That way, users of the component don't need to worry about passing in so many props and we gain consistency when the component is used throughout the app.

**Comment by marekhrabe** [comment]
I wouldn't go with "visible by default and everywhere" approach just yet. The big problem is that this URL shows only the initial previewed page and does not update when user goes to some other page. That can be fine for previewing posts, as users will generally only preview a single URL but it might not be ideal for site preview, which acts more like a general browser. My suggestion will be to go with opt-in implementation for now in this PR. What do you think?

**Comment by michaeldcain** [comment]
@marekhrabe: that's a fair reason. I was going to mention that it's a prop either way (to enable or to disable), since there are implementations like the Theme Showcase that use WebPreview for things like demo sites, which might not benefit from the URL. 

I like @mattsherman's suggestion for simplicity, but it makes sense to make the feature a little more robust before enabling it by default.

**Comment by mattsherman** [comment]
Opt-in is reasonable for now.

**Comment by michaeldcain** [comment]
**Mobile style:**
showurl-mobile

**Comment by marekhrabe** [comment]
Only thing I wanted to point out is usage of `lighten` in css (I recently had a conversation about making less computations and more variables) but lighten with 20% is all over the place so we good with this one

**Comment by michaeldcain** [comment]
Yeah, I grabbed it from another component, but maybe it being all over the place is just another vote for a variable :).

**Pull request merged**
