### PR TITLE
Purchases: Fix 'Edit Card Details' form failing while checking for input errors

### PR DESCRIPTION
**Pull request by Tug**
This PR fixes a bug reported at p2MSmN-4vV-p2 :
> Unable to update card info on the billing history page?
> User tried updating their card info in Calypso and the Save button did nothing.

#### Testing Instructions
- Checkout this branch and go to http://calypso.localhost:3000/purchases
- Click on a purchase you made using a credit card (do one first if you have none)
- Click on "Edit Payment Method"
- Edit the form, it should not throw errors in the console
- Validate the form, it should work as expected

#### Review
- [x] Product Review
- [x] Code Review

### CODE REVIEW

**Comment by Tug** [comment]
Note: you may be affected by this bug while testing:
https://github.com/Automattic/wp-calypso/pull/3497

**Comment by Tug** [comment]
Rebased, the jQuery bug should be gone!

**Comment by klimeryk** [comment]
LGTM! :+1: 

/cc @umurkontaci - weird that this did not come up during your PR and mine code review :/

**Comment by fabianapsimoes** [comment]
Product :+1: 

Thanks for the quick fix, Tug!

**Pull request merged**
