### PR TITLE
Change domain registration details into contact information

### PR DESCRIPTION
**Pull request by BandonRandon**
This updates the copy as suggested in #2320. 

I'm not sure about the analytics code so if @gziolo could let me know that would be great. It also appears that some of the re-factoring @stephanethomas mentioned has already been done. Such as `validateDomainContactInformation` 

screenshot_22-02-2016-19 33 30

### CODE REVIEW

**Comment by gziolo** [comment]
Looks good at first glance, but I think @stephanethomas has better experience in this area :)

**Comment by stephanethomas** [comment]
This is great. My only concern is that we're renaming the page view event so we're going to lose all the history. However maybe we can now rename events in Tracks, let's check with @mattm.

**Comment by mattm** [comment]
It's true that if you rename the event you'll lose the historical trends; there's no way to rename the old events. You'll have to decide whether you want to keep the old name going forward or rename it and lose the long term trends.

**Comment by BandonRandon** [comment]
>  You'll have to decide whether you want to keep the old name going forward or rename it and lose the long term trends.

Happy to revert the page name back in the PR but would like to leave that decision to someone who is more closely related to the event tracking/tracks on how to best proceed. 

@lucasartoni Do you have any thoughts on this?

**Comment by lucasartoni** [comment]
I think we can afford to lose history on this particular page

**Comment by gziolo** [comment]
Which means it is good to go :)

**Pull request merged**
