### PR TITLE
Signup: Update illustrations in purchase detail components.

### PR DESCRIPTION
**Pull request by taggon**
This will replace icons in Purchase Detail component with new fancy illustrations.

## How to test

You should find the new illustrations in the following two pages:
- Thank you screen
 1. Complete to purchase a paid plan subscription.
 2. There should be a new illustration in every Purchase Detail blocks.
- Current plan screen of a site on any paid plan.
 1. Open Plan page for your website not on a paid plan.
 2. The Purchase Detail cards should show the new illustrations.

Demo:
screenshot-2017-9-29 thank you wordpress com
screenshot-2017-9-29 plans taggon on wordpress wordpress com

This PR is a part of #14863.

cc @cristelrossignol @markryall @fditrapani

### CODE REVIEW

**Comment by fditrapani** [comment]
I'm seeing some gaps on the plans page when I view the business plan:

image

and premium:
image

Not sure if it's on my end, here's my console:
image

**Comment by taggon** [comment]
@fditrapani I think your local server cannot serve those images for a reason. Can you check if the files exist?

**Comment by fditrapani** [comment]
The files do exist in my checkout.

**Comment by travisw** [comment]
@fditrapani do you have an ad blocker on? I bet that's what's blocking them, and it's probably because of the image names "advertising" and "adwords".
Maybe we should rename those to something that won't get caught in ad block filters, assuming that is what's actually happening.

**Comment by fditrapani** [comment]
@travisw that was it. Good catch! I turned off the ad blocker and the images showed. 

I agree, we should rename those files.

**Comment by travisw** [comment]
On smaller screens some of the images seem to be too high and run off of their intended block.
Also, on the Business plan thank you page a couple of them seem to be showing the older icons.
calypso-thankyou-business

**Comment by travisw** [comment]
My full screen capture wasn't working on the plan page but it also showed a similar issue.
screen shot 2017-09-29 at 11 27 07 am

**Comment by taggon** [comment]
@travisw Thanks for reviewing this! I added the missing illustrations and fixed the position bug.
2017-10-02 19 05 27-fullpage

**Comment by taggon** [comment]
@travisw @fditrapani @markryall I think it is ready to go. Did you find any problems on this PR? :)

**Pull request merged**
