### PR TITLE
WIP: NUX: Enter CC info while "Waiting to set up site"

### PR DESCRIPTION
**Pull request by artpi**
> This is exploration PR. Highly volatile.

## Problem

In NUX there is an 8-second wait "Please wait, we're setting up your site". THEN you have to click a button to be able to input CC number

## Solution

# [ 🎆  💵  💸 Current demo 📺 ] ( https://cloudup.com/iuFy5nYt05p )

We'll start with trying to combine "Waiting" screen with inputting CC info. That way we cn input the info while site is being set up.
 
CC @rralian @gwwar @lamosty @retrofox

### CODE REVIEW

**Comment by artpi** [comment]
TODO: 

- [ ] Try to pass plan
- [ ] Get rid of loading phase
- [ ] Test, test, test
- [ ] Inteprate visually

**Comment by gwwar** [comment]
Very cool to see the demo. It looks like we're missing the cart item though which would give the user context to what they're buying. Could you also add a TODO to wire that up?

**Comment by rralian** [comment]
@artpi Good start! Just make sure you're considering/testing the case of a new user. Hopefully that doesn't make a big difference, but that should be our primary user story.

**Comment by lamosty** [comment]
Pretty nice!

Are you reusing the checkout page as a whole or will you have to reuse only the smaller checkout components and create a new checkout step?

**Comment by artpi** [comment]
> Hopefully that doesn't make a big difference, but that should be our primary user story.

I hoped it wouldn't, but its tricky :/ I need to untangle some new layers!

**Comment by rralian** [comment]
> I hoped it wouldn't, but its tricky :/ I need to untangle some new layers!

Right, that's why I'd start with this case, because we may find a solution that doesn't cover it isn't even applicable when we consider this case.

**Comment by artpi** [comment]
> Right, that's why I'd start with this case

100% agree, digging deeper.

**Comment by artpi** [comment]
It is a very sad moment that I have to close this promising PR.
Because Checkout depends on:
- /me/sites
- CartStore
- TransactionStore

The /me/sites requires cookie and user bootstrap which in turn needs a page relaod:
https://github.com/Automattic/wp-calypso/blob/master/server/pages/index.js#L226

Doing this properly would require reimplementing checkout.
I have ideas for hacking this, ( saving CC data in sessionStorage ), but i dont like it.

I'm closing this on favour of https://github.com/Automattic/wp-calypso/pull/7589

**Pull request closed without merging**
