### PR TITLE
Force the iframe to redirect if it fails to reload

### LINKED ISSUE #43068: Add message redirecting Safari users to wp-admin block editor
## Description

#41725 outlines that the Calypso block editor is not loading for Safari users. Here's what they are seeing:

80857163-42fa4300-8c93-11ea-8360-22c20a69ca32

This is likely due to the fact that since [version 13.1 Safari](https://developer.apple.com/documentation/safari_release_notes/safari_13_1_release_notes) has "Added cookie blocking for all cross-site resources by default." 

## Long-term

We are in the process of working with browsers to see if we can white-label 3rd party cookies on WP.com.

## Short-term

We should add a message for Safari users who attempt to load the Calypso block editor which offers to redirect them to the wp-admin editor.

### PR DESCRIPTION
**Pull request by scruffian**
#### Changes proposed in this Pull Request

This is an alternative approach to https://github.com/Automattic/wp-calypso/pull/43127.

In Safari, if you have "Prevent cross-site tracking" enabled, the iframe containing the block editor fails to load - it gets stuck in an infinite loop. Unfortunately this means that the `onLoad` event of the iframe never fires which means that the user is stuck on the placeholder screen.

To fix this I added a `setInterval` which listens for when the `iframe` is ready to load. Then we set a timeout for six seconds (one second longer than the timeout on the `iframe`). If the iframe loads then we cancel the timeout, otherwise we redirect the user to the iframe address.

The advantage of this approach over #43127 is that it ensures that users will never get stuck in the iframed editor, if something else goes wrong, or if other browsers start to block third party cookies.

#### Testing instructions
I haven't found a clean way to test this.

In order to test in Safari with "Prevent cross-site tracking" enabled you have to run Calypso locally on the wordpress.com domain. There are instructions on how to do this on the field guide (I ended up using Charles). The problem is that the block editor always tries to do a redirect to wordpress.com/wp-login.php; if this is pointing at Calypso then it throws a 404. In Safari a 404 does trigger the `onLoad` event for the iframe, so with this setup you won't see the problem.

After the redirect to `wordpress.com/wp-login.php` you are redirected back to `https://wordpress.com/block-editor/post/sitebuilder197760975.wpcomstaging.com?authWpAdmin=true`. If you visit this URL directly then you can skip this step, and load the iframe. However the iframe will still load `wordpress.com/wp-login.php` inside it, which will again throw a 404 and trigger the `onLoad` event.

However if you can replicate an infinite loop locally you can update the iframe URL to point to your local infinite loop, which will then trigger the iframe error state.

I used this: ```<?php header("Location: http://localhost:4444/redirect.php"); ?>```

Of course if you do this you will be redirected to the page with the infinite loop, which will throw an error :)

Given the complexities in testing this, I wonder if it makes more sense to test it in staging...

Fixes #43068

### CODE REVIEW

**Comment by glendaviesnz** [comment]
Will take a look today to see if we can instead modify the code from https://github.com/Automattic/wp-calypso/pull/34902 to prevent the redirect loop from happening and exit early to wpadmin instead.

**Comment by glendaviesnz** [comment]
I managed to replicate this on calypso localhost by:

- Go direct to atomic site custom domain and log in
- Loading calypso on localhost and switch to the same Atomic site with a custom domain in safari with `Prevent Cross Site Tracking` enabled
- It should do a redirect to wpadmin and return to editor with authWpAdmin=true param set
- Now delete all the data/cookies just for this  domain from Safari, but make sure there is still a Session Storage value for calypso for `gutenframe_{site_id}_is_authenticated` for that site
- Try loading the editor again and it should go into the auth loop as calypso thinks site is authenticated due to the session value, when in fact there are no auth cookies

I am not sure if it is the cause of all the issues, but it may be that if a user has a long lasting session `gutenframe_{site_id}_is_authenticated` remains set, but auth cookies have expired, which will then cause the infinite login loop ... maybe we need to add an expires value to the session storage.

**Comment by glendaviesnz** [comment]
This fix works for me. I have spent quite a while looking for an alternative to avoid a 6 second delay, but unfortunately a redirect doesn't fire an onload event in the iframe, so the [likes of this fix](https://github.com/Automattic/wp-calypso/pull/36977) can't be used.

The only alternative I could think if was if the wpcom/jetpack auth loop detects that it is a bounce somehow and emits an `frame_options_header` header instead to block the load so that the [existing detection of the failed load](https://github.com/Automattic/wp-calypso/blob/master/client/gutenberg/editor/calypsoify-iframe.tsx#L552)  kicks in and loads wpadmin.

**Comment by glendaviesnz** [comment]
Another approach we can explore is to try and detect the auth loop from the server side, eg. the iframe loads usersite.foo/wp-admin/post-new.php, which redirects to /usersite.foo/wp-login.php . wp-login.php on the user site will usually try to set the wordpress_test_cookie cookie, we should be able to hook into that check, and perhaps redirect to jetpack.com/redirect with an appropriate flag, which would then redirect to wordpress.com/wp-login.php, where we can break out of the redirect loop and fire off a message to CalypsoIFrame so iframe can be broken out of with a redirect to wp-admin editor.

**Comment by scruffian** [comment]
> Load calypso on localhost with Prevent Cross Site Tracking enabled

I don't understand how you can do this!

**Comment by glendaviesnz** [comment]
> > Load calypso on localhost with Prevent Cross Site Tracking enabled
> I don't understand how you can do this!

The trick is to log direct into the wp-admin for the site first, this sets an auth cookie for the domain. Then when you try and iframe the editor there is already an auth cookie, so it works. Currently Safari only blocks the setting of cookies in an iframe, if a cookie already exists it happily reads it.

**Comment by glendaviesnz** [comment]
> > Load calypso on localhost with Prevent Cross Site Tracking enabled
> I don't understand how you can do this!

For me calypso runs fine in safari with Cross Site Tracking disabled, and the #34902 fix allows Atomic sites to run in iframed editor. It doesn't work for jetpack sites though. What happens when you try it locally?

**Comment by scruffian** [comment]
> What happens when you try it locally?

I can't log into calypso.localhost on Safari unless i disable the "prevent cross site tracking" checkbox. It throws an error when I get to the 2FA step. Are you testing with an automattician account?

**Comment by glendaviesnz** [comment]
@scruffian Since my Safari ITP stopped playing nice as well I spent a bit of time trying to work out how to test this another way, but the only way the worked was your suggested approach of the Charles proxy and fudging the editor iframe url to one with an infinite loop. Doing this the PR works as advertised and breaks out of iframe after 6 seconds and redirects to iframe url. 

I guess it is not a big change so in theory it shouldn't be to hard to merge it, set channel to red and do some testing in staging, and if any issue revert it?

@nsakaimbo are you still wanting to add some design guidelines to this before we do any more with it?

**Comment by nsakaimbo** [comment]
@glendaviesnz Thanks for checking - I actually removed/re-added the `Needs Review` label to kick-start the `ci/wp-desktop` ci job, apologies for any confusion.

That being said, I don't think the `window.location.replace` override will play nice with the wp-desktop app if this call takes the user out of the Calypso iframe context. I'm currently fixing an issue with a similar bug ("View Post" behavior in the editor).

We should check if we're within the desktop context and fire off an event so the iframe context is preserved and the desktop can respond accordingly. You can see an example of this in [this PR](https://github.com/Automattic/wp-calypso/pull/43301/files#diff-59c0336bfc8e2c9de7a26194d97da7eaR280) (currently WIP but will finalize soon).

**Comment by glendaviesnz** [comment]
@nsakaimbo - In theory the case that causes `window.location.replace` to run is due to 3rd party cookie issue, so desktop client shouldn't hit it, but we all know how `in theory` usually pans out, so have added an event for desktop on the off chance that it does hit this - not sure if I have taken the right approach:

- Used existing notifyDesktopCannotOpenEditor action
- Added new `REASON_BLOCK_EDITOR_UNKOWN_IFRAME_LOAD_FAILURE` reason
- Made the wpAdminLoginUrl param optional as we don't have it in this context and didn't make sense to construct as probably unknown exactly what to do in the event of hitting this error
- The url of the wpadmin block editor is available, but not sure if you can do anything with this in the desktop app in the event of this unknown failure so maybe this should be optional for the action as well

**Comment by nsakaimbo** [comment]
> ... but we all know how `in theory` usually pans out

😆 

@glendaviesnz Thanks for making the changes - I think making use of the existing `notifyDesktopCannotOpenEditor` event makes sense - sounds good to me. Could you please open an issue in the desktop repo so we can track the work necessary to make the desktop app respond to the new reason code?

**Comment by glendaviesnz** [comment]
> Could you please open an issue in the desktop repo so we can track the work necessary to make the desktop app respond to the new reason code?

Done - https://github.com/Automattic/wp-desktop/issues/927

**Comment by glendaviesnz** [comment]
@scruffian This still tests ok for me with the desktop action added, do you want to give it another test?

**Comment by scruffian** [comment]
I tested again and this still works for me 👍

**Pull request merged**
