### PR TITLE
Checkout: Hide postalCode field in TaxFields if country does not support it

### PR DESCRIPTION
**Pull request by sirbrillig**
#### Changes proposed in this Pull Request

There are countries that do not have a postal code, and for those we should not require one in checkout. This has already been done in https://github.com/Automattic/wp-calypso/pull/53522 and https://github.com/Automattic/wp-calypso/pull/54327 for domain fields, but the "tax" fields (the contact fields shown when there is not a domain or G Suite in the cart) were not changed. This PR hides the field for the tax form as well if the country does not support postal codes.

Because the decision to display the postal code field depends on the country selection, this PR also reverses the order of the fields so that instead of POSTAL, COUNTRY, it's now COUNTRY, POSTAL.

Requires D68482-code

#### Testing instructions

First apply D68482-code and sandbox the store.

- Visit checkout with a non-domain product in your cart (eg: a plan).
- Verify that the country select list is displayed and looks ok.
- Select a country with a postal code (most of them) and verify that the form now displays the postal code field as well.
- Verify that you cannot complete the step without filling in the postal code, but that once it is filled (and valid), the "Continue" button will move you to the next step.

Next...

- Repeat the above steps but select a country code that does not have postal codes, like Curaçao.
- Verify that the postal code field is not displayed.
- Verify that you can complete the contact step without filling in the field.

### CODE REVIEW

**Comment by sirbrillig** [comment]
This is tricky because the Redux store holds at least three different lists of countries under `state.countries`; it appears that the ones under `state.countries.domains` contain the `has_postal_codes` key, but the ones under `state.countries.payments`, which we use for most of checkout, do not have that key, meaning that it will appear that every country country does not support postal codes.

A separate problem is actually an extension of a longstanding issue: when loading cached contact details from the API, we load all of the ones that are available directly into the `wpcom` Store, then extract them as needed for the forms and for submitting validation and purchase (we also use any of the ones available to update the cart's tax location). If there are cached contact details that we don't want to use for any of that (ie: the postal code for countries that don't support it), then there's no mechanism to conditionally strip them from the `wpcom` Store. It would be nice to modify the Store itself to strip the postal code when the country does not allow it, but the decision requires a list of country data (see above) from another API call, and there's no clear way to inject it into the Store's reducer.

**Comment by sirbrillig** [comment]
> This is tricky because the Redux store holds at least three different lists of countries under state.countries; it appears that the ones under state.countries.domains contain the has_postal_codes key, but the ones under state.countries.payments, which we use for most of checkout, do not have that key, meaning that it will appear that every country country does not support postal codes.

I modified the transactions supported countries endpoint in D68482-code and that seems to resolve that issue.

**Comment by martian77** [comment]
The only problem I spotted is that if you have a postal code filled out, then change the country to one that doesn't support a postal code it doesn't clear the field value and displays it when you continue on to the next step. Otherwise works as described.

billing information

CM is Cameroon, which doesn't require a postcode.

**Comment by sirbrillig** [comment]
> The only problem I spotted is that if you have a postal code filled out, then change the country to one that doesn't support a postal code it doesn't clear the field value and displays it when you continue on to the next step.

Thank you! Yeah, that's a symptom of the second issue described above. I tried various ways to solve it in the reducer, but I think I'm just going to have to handle it at each location instead. That is:

- The inactive tax display that you mentioned.
- Updating the cart tax data.
- Submitting the data for validation.
- Submitting the data for a transaction to both the transactions and the PayPal endpoints.

That is, unless I maybe add a new state in the reducer like `state.are_postal_codes_allowed` and update it any time the country code is updated...

**Comment by sirbrillig** [comment]
I think I figured out a way to do this correctly; whenever the country code is updated or set, we also update the postal code already; I modified that so that if the modified country code does not support a postal code, we actively erase the postal code.

**Review by martian77 — APPROVED** [review]

**Comment by martian77** [comment]
LGTM.

**Pull request merged**
