### PR TITLE
Signup: Add first draft of "Triforce" flow

### PR DESCRIPTION
**Pull request by sirbrillig**
Initial draft of the "Triforce" design selection flow. You can access it currently by visiting http://calypso.localhost:3000/start/layout 

screen shot 2015-12-14 at 6 56 26 pm

Still to do:

- [x] Add stats collection
- [x] Add images to choices
- [x] Make sure theme mapping is what we want
- [x] Decide what to name the flow (currently `/start/triforce`, but probably should be something else)
- [x] Clean up / polish the styles

## Testing

1. Visit http://calypso.localhost:3000/start/layout and make sure that the first step of the signup flow is the "triforce" screen (pictured above). 
2. Try each layout choice to be sure the listed themes on the next page are different from other layout choices (beware: the theme order is randomized). 
3. Complete the signup flow with one of the theme choices and be sure that A) there are no javascript errors (at least, ones not in `master`) and B) the created site has the theme chosen.

### CODE REVIEW

**Comment by melchoyce** [comment]
> Decide what to name the flow (currently /start/triforce, but probably should be something else)

Maybe `/start/homepage-layout`?

**Comment by sirbrillig** [comment]
@melchoyce / @kwight: Nice work! I updated the screenshot and the URL in the PR description.

**Comment by mattwiebe** [comment]
> Maybe `/start/homepage-layout`?

Or even just `start/layout`?

**Comment by sirbrillig** [comment]
> Or even just start/layout

I kind of prefer that. `homepage-layout` is so long-winded ;-)

**Comment by sirbrillig** [comment]
For `getSlugFromName`, we should wait until #1628 is decided.

**Comment by sirbrillig** [comment]
Rebased over #1628

**Comment by sirbrillig** [comment]
Added Testing instructions.

**Comment by kwight** [comment]
LGTM :+1:

**Pull request merged**
