### PR TITLE
Assembler: Update animation in the Pages screen

### PR DESCRIPTION
**Pull request by taipeicoder**
## Proposed Changes

This PR adds animations when the user clicks on a page preview. See the design reference in pbxlJb-4EO-p2.

<ins>Note</ins>: Due to the complexity of keeping the expanded page preview centered, this PR will close the expanded page preview on browser window resize. We can discuss if it's worth supporting windows resize later on.

Before:

https://github.com/Automattic/wp-calypso/assets/797888/76cbbc97-6500-4119-8558-a71b028534a6

After:

https://github.com/Automattic/wp-calypso/assets/797888/18f35803-77e4-4b21-a4e8-dfb1c764f9af

## Testing Instructions

* Head to the Assembler.
* Select any patterns and colors.
* Once in the Pages screen, add some pages.
* Click on the page previews and ensure that they feel great.

## Pre-merge Checklist

- [x] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [x] https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md for your changes?
- [x] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [x] Have you checked for TypeScript, React or other console errors?
- [x] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [x] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [x] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

**Comment by taipeicoder** [comment]
@lucasmendes-design using scaling has two downsides:

1. Scaling might cause the preview to look blurry due to subpixel rendering. I'm not sure if there's a good solution to this.
2. Scaling might look overwhelming/underwhelming depending on the existing preview sizes. This requires some fine-tuning given the responsiveness of the page previews. 

That said, scaling is IMO the only way for the animation to make sense since the growth is done from the center point of the element. I've experimented with adjusting the height/width of the element instead of scaling, but it didn't look great since height/width grows from the top/left of the element rather than the center.

**Comment by lucasmendes-design** [comment]
All good! :) 

> Scaling might cause the preview to look blurry due to subpixel rendering. I'm not sure if there's a good solution to this.

Do we know the maximum size we can have so the images are not pixelated? Knowing that, for big screens, we can have a maximum modal size. Let me know if I understood what you said 🙏🏽


> Scaling might look overwhelming/underwhelming depending on the existing preview sizes. This requires some fine-tuning given the responsiveness of the page previews.

Not sure if I understood this. But I think it's fine to show an almost empty or crowded page.

**Comment by taipeicoder** [comment]
> All good! :)
> 
> > Scaling might cause the preview to look blurry due to subpixel rendering. I'm not sure if there's a good solution to this.
> 
> Do we know the maximum size we can have so the images are not pixelated? Knowing that, for big screens, we can have a maximum modal size. Let me know if I understood what you said 🙏🏽
> 
> > Scaling might look overwhelming/underwhelming depending on the existing preview sizes. This requires some fine-tuning given the responsiveness of the page previews.
> 
> Not sure if I understood this. But I think it's fine to show an almost empty or crowded page.

@lucasmendes-design on the latest commit, the maximum modal size is calculated by scaling to 80% of the viewport height. So the "scaling might look overwhelming/underwhelming depending on the existing preview sizes" is no longer a concern 🙂 

https://github.com/Automattic/wp-calypso/assets/797888/125f0641-0292-4dd7-ba41-ccc653e7aba2

**Comment by arthur791004** [comment]
> Due to the complexity of keeping the expanded page preview centered, this PR will close the expanded page preview on browser window resize. We can discuss if it's worth supporting windows resize later on.

We can add a container to get the position of the page preview during the resizing. See https://github.com/Automattic/wp-calypso/commit/101ee476999a601da538c1f82320da8c37df0b35. But the animation isn't very smooth.

https://github.com/Automattic/wp-calypso/assets/13596067/0fecdf10-08fb-4787-a0ce-1202c96685c9

For better animation, we can try to use the framer-motion here. Here is an example: https://codesandbox.io/p/sandbox/framer-motion-expandable-cards-349bvn

**Review by arthur791004 — APPROVED** [review]
Nice job 👍

**Comment by taipeicoder** [comment]
> > Due to the complexity of keeping the expanded page preview centered, this PR will close the expanded page preview on browser window resize. We can discuss if it's worth supporting windows resize later on.
> 
> We can add a container to get the position of the page preview during the resizing. See [101ee47](https://github.com/Automattic/wp-calypso/commit/101ee476999a601da538c1f82320da8c37df0b35). But the animation isn't very smooth.
> 
>  Screen.Recording.2023-11-28.at.10.14.50.PM.mov 
> For better animation, we can try to use the framer-motion here. Here is an example: https://codesandbox.io/p/sandbox/framer-motion-expandable-cards-349bvn

I'll give this a try in a follow-up PR, thanks for the tip! 🙌

**Pull request merged**
