### PR TITLE
Only load styles and script if the block is in use

### PR DESCRIPTION
**Pull request by josephscott**
When the FSE plugin is activated a site will start loading posts-list-block.css on every page view, even when the block has never been used.

It should only do that on views where the block is in use.

#### Changes proposed in this Pull Request

* Check that the block is in use before loading extra CSS/JS

#### Testing instructions

* Activate the plugin, note that posts-list-block.css starts getting loaded on every page view.
* After change, it should only load on views where the block is being used.

Fixes #

### CODE REVIEW

**Comment by simison** [comment]
Thanks for working on this! 😍  

Could we switch to `render_callback` method instead? https://mkaz.blog/wordpress/conditionally-load-block-assets-part-2/

That would potentially be more performant.

**Comment by josephscott** [comment]
I would be fine with that approach as well.  The goal is to stop making the extra requests and additional bytes when they are not needed.

**Comment by josephscott** [comment]
@obenland anything else I need to do to help get this merged?

**Comment by obenland** [comment]
Not sure how strongly @simison feels about his suggestion, but given that this is a deprecated block I think it's fine to just ship as is!

**Comment by simison** [comment]
Feel free to merge, should've been clearer that I don't wanna block a clear improvement already. 👍

**Pull request merged**
