### PR TITLE
[Domains] Reduce the padding on CTA buttons

### PR DESCRIPTION
**Pull request by jsnmoon**
This change reduces the vertical padding of suggestion buttons. Doing so enables us to squeeze in more suggestions on initial page load before requiring the customer to scroll down.

In addition, this spacing is closer to what the designs had specified.

## Domain Management (Before and After)
domains_-_before
domains_-_after

## Signup (Before and After)
nux_-_before
nux_-_after

# Test Instructions
1. Spin this up locally or using a live branch.
2. Navigate to `/start/domains` or `domains/add`.
3. Verify that you see the visual changes as illustrated above. (The buttons should be shorter.)

### CODE REVIEW

**Comment by jsnmoon** [comment]
Requesting feedback from @lucasartoni and @kelliepeterson: 👍 or 👎?

**Comment by folletto** [comment]
Any reason here to not just use the "Compact" version of the buttons, so we can avoid injecting custom CSS?

**Comment by sixhours** [comment]
I think the narrower buttons work, though I wonder what it would look like with the compact buttons, as Davide suggests.

**Comment by jsnmoon** [comment]
> Any reason here to not just use the "Compact" version of the buttons, so we can avoid injecting custom CSS? (@folletto)

> I think the narrower buttons work, though I wonder what it would look like with the compact buttons, as Davide suggests. (@sixhours)

Here's how the interface looks with compact buttons:

compact_buttons

As you can see, using compact buttons leads to a reduced visual footprint. I would caution against this approach since doing so may diminish the buttons' effectiveness.

Please keep in mind that the intent of this change (and the intent of the original design, as far as I can tell) is to maximize the number of domain suggestions visible on load while preserving the effectiveness of the buttons to encourage conversion.

**Comment by lucasartoni** [comment]
We can A/B test the compact buttons only when we have a solid baseline to compare with. Right now I agree with Jason in keeping the current visual footprint on the CTAs.

**Pull request merged**
