### PR TITLE
Previews: Open external sites in the same window

### PR DESCRIPTION
**Pull request by marekhrabe**
Trying to prevent many opened tabs at once.

To test:

- My Sites
- Click "View Site"
- Click the external icon in top right corner
- It should now open in the **same tab**

### CODE REVIEW

**Comment by nylen** [comment]
If a path like this is taken, please change the icon.  The square + arrow `external` icon universally means "this will open in a new tab" everywhere I have seen on the web.

**Comment by marekhrabe** [comment]
We opened a broader discussion about this in p3Ex-2WN-p2

**Comment by vindl** [comment]
Also, keep in mind that whatever we do here we'll have to replicate in WP.com and Jetpack masterbar, and we should consider if opening a site in the same tab is appropriate there.

**Comment by apeatling** [comment]
I think we should close this one, because it did not come to a resolution, even in the discussion. If someone wants to grab it and make a decision, please re-open.

**Pull request closed without merging**
