### PR TITLE
Update/onboarding import tracking

### PR DESCRIPTION
**Pull request by bogiii**
#### Changes proposed in this Pull Request
Changes provide additional logic to call `recordTracksEvent` methods on the places where are missing, defined by [the Figma doc](https://www.figma.com/file/yKn2XDQWEnAlYksYvpbXOZ/Importer-Flow-Metrics?node-id=0%3A1).

#### Testing instructions
* Go to `/start/importer/capture?siteSlug={YOUR_SITE}.wordpress.com`
* Pass through the onboarding import flow
* Check if tracking is active
* You can use [Tracks Vigilante chrome plugin](https://github.com/Automattic/tracks-chrome-extension) for easier follow

Related to #57131

### CODE REVIEW

**Review by vishnugopal — CHANGES_REQUESTED** [review]
For the `1231243123123.wordpress.com` case, entering an invalid wordpress.com site, I get a blank screen now. The console doesn't show any error.

**Review by vishnugopal — CHANGES_REQUESTED** [review]
I'm unsure if this is something in my configuration, but there are still 2 events that aren't firing correctly in my system:

```
calypso_signup_step_start 
[flow=importer step=ready action=back-to-start]
calypso_signup_step_start 
[flow=importer step=ready action=back-to-start]
```
What I'm getting instead:
CleanShot 2021-12-10 at 10 31 39@2x

**Comment by bogiii** [comment]
<table border="0">
 <tr>
    <td>Screenshot 2021-12-10 at 11 35 31
</td>
<td>
Screenshot 2021-12-10 at 11 39 55
</td>
 </tr>
</table>

I think that we have different expectations. In the Figma document, there are request that we want to track the `back to start` event, and we truly track it.

Maybe you want to track the navigation's `back` button event?
Currently, it's tracked by the StepWrapper component and there is a generic event name `calypso_signup_previous_step_button_click`.

cc @vishnugopal

**Review by vishnugopal — APPROVED** [review]
Ack! I think I was just confused that the event stated in the Figma doc was not firing. I've replaced it with just a plain `calypso_signup_previous_step_button_click` event. That fires ok and should be enough for when we test this with funnels.

**Comment by vishnugopal** [comment]
Let's get this merged! 👏🏽 Thanks for the work here!

**Pull request merged**
