### PR TITLE
Add splash screen to Sensei flow

### PR DESCRIPTION
**Pull request by donnapep**
Related to https://github.com/Automattic/evergreen/issues/170.

## Proposed Changes

Adds a splash screen to the Sensei sign-up flow.

## Testing Instructions

1. Run `yarn start`.
2. Go to `http://calypso.localhost:3000/setup/sensei`.
3. Check that the screen matches the  design - km0MaMdbZMb5ySnGP2RSxg-fi-20024055_54108
4. Test that clicking _Get Started_ moves to the `senseiSetup` step of the flow.
5. Test that clicking _Learn More_ goes to https://wordpress.com/create-a-course/.
6. Test the page at smaller resolutions to ensure it looks good.

## Screenshot
screencapture-wordpress-setup-sensei-intro-2023-07-06-06_57_07

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

**Comment by burtrw** [comment]
Looks good!

Does it load before the required login? I can't tell since it isn't live.

**Review by gikaragia — APPROVED** [review]
Looks great!

**Comment by gikaragia** [comment]
> Does it load before the required login? I can't tell since it isn't live.

Hmm indeed. If the user is logged out, they get redirected to create an account which isn't ideal, especially with the new splash screen. We currently check if the user is logged in on every step in function `useAssertConditions`. 

It makes sense to move the redirection somewhere later and remove the `useAssertConditions` call entirely. The limitation here is that the user has to be logged in before the simple site is created which happens in the loading screen right after the plan selection.

In the VideoPress flow they added the login check in the `submit` method. We could do something similar maybe before `senseiPlan` although we should test what happens if the user goes directly to one of the later steps (i.e. `senseiPurpose` or `senseiLaunch`) without being logged in.

**Comment by donnapep** [comment]
@burtrw Let me know what you'd like to do as per Giannis' comment.

**Comment by burtrw** [comment]
@donnapep could we move the Login to be right after the Pick a style screen? 

image

**Comment by donnapep** [comment]
@gkaragia I've moved the signup page to after the `senseiSetup` step in https://github.com/Automattic/wp-calypso/pull/77979/commits/a31bd0517cef6b251c864e2a90b0bf60ac4783a2 and https://github.com/Automattic/wp-calypso/pull/77979/commits/a4b2d91919d14663d5a16a1b2cf0aa3e5e10f199.

**Review by gikaragia — COMMENTED** [review]
Looking much better now! A few issues:

1. I encountered this issue where the domain search bar is not filled with a suggestion:

Screenshot 2023-06-12 at 12 11 42

This happens consistently when the user enters just one charater as the site title on the first step. However, I also encountered it when entering more characters although I can't do it consistently.

2. Not sure how important this is but If the user navigates to `/setup/sensei/senseiPlan`, he is not logged in and selects a plan, an error happens:

Screenshot 2023-06-12 at 12 17 52

Maybe we should add a check to this step to make sure that they are logged in?

**Comment by donnapep** [comment]
> 1. I encountered this issue where the domain search bar is not filled with a suggestion:

This is happening on `trunk` and with other flows (i.e. VideoPress), so it doesn't seem related to this PR at all. I suspect it can't find a domain because there's not much to go on when trying to find a domain for a single character, for example.

> 2. Not sure how important this is but If the user navigates to /setup/sensei/senseiPlan, he is not logged in and selects a plan, an error happens:

Thanks! I'll look into this one tomorrow.

**Comment by gikaragia** [comment]
> This is happening on trunk and with other flows (i.e. VideoPress), so it doesn't seem related to this PR at all. I suspect it can't find a domain because there's not much to go on when trying to find a domain for a single character, for example.

Yep, the issue with one character is not caused by this PR. But maybe we could easily solve it by enabling the button after the user types two characters in the first step?

And apart from the issue happening with 1 character, I also encountered it with more characters although not consistently. Are you able to reproduce it or is it something with my environment?

**Comment by donnapep** [comment]
@gkaragia I've added a check to ensure that the user is logged in on the Plan step in https://github.com/Automattic/wp-calypso/pull/77979/commits/ca4a178849a1078fe2a7df79de8d9b32c232883b.

I've disabled the Continue button on the setup step until at least 2 characters are entered for the site name in https://github.com/Automattic/wp-calypso/pull/77979/commits/b73bceb1e309a83a690add0c63c3954870ec110b.

> Are you able to reproduce it or is it something with my environment?

I haven't noticed this yet I don't think. Just the single character site name issue.

**Comment by donnapep** [comment]
@gkaragia Also, any idea how to debug the unit test failure? TeamCity isn't that helpful. 🙁 I'm not even sure how to locate what the test file is.

**Comment by gikaragia** [comment]
Did you try logging in as guest @donnapep? It is a bit difficult to find the actual failures:

php

Seems like there are some TypeScript related errors. You probably don't need to define `AssertConditionResult` at all (or maybe import it) and just make sure that the result has the correct type. And `flowName` is not available.

**Comment by donnapep** [comment]
@gkaragia I think this one is ready. 🥳

**Comment by donnapep** [comment]
@gkaragia Any chance this one can get an approval? Note that I'll be AFK from June 23 - July 3, so if you wouldn't mind deploying after approval, that would be 👍🏻.

**Review by gikaragia — APPROVED** [review]
Looks great! Make sure you go [through this page](https://fieldguide.automattic.com/calypso-deployment-process/) before merging.

**Comment by burtrw** [comment]
@gkaragia Donna is AFK now, if you can merge, that'd be great, or we can wait until she is back.

**Comment by burtrw** [comment]
Thank you!

**Comment by gikaragia** [comment]
This is now released to production. Something that I noticed (and it isn't caused by this PR) is that the screen is larger than the viewport and a scrollbar appears:
php

Not sure how much of an issue it is.

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/8063176

Thank you @donnapep for including a screenshot in the description! This is really helpful for our translators.

**Pull request merged**
