### PR TITLE
Query Manager: Use static methods

### PR DESCRIPTION
**Pull request by sirreal**
This PR does some cleanup and improvements around `QueryManager`. The following should not change behavior:

- ~247d31626 Prettier query-manager (isolated in #18004)~
- 1a349f96d Make QueryKey, DEFAULT_QUERY es2015 static class properties
- 10eb1847c Remove redundant in-line class declaration
- e5c6580ac Rename QueryManager.DEFAULT_QUERY to DefaultQuery

These changes are significant. 

- 6d4b3c9e2 **Make `compare` a static method**
- ae93ad49c **Make `mergeItem` a static method**
- 60d1101 **Make `sort` a static method**

## Testing
1. Do the tests pass? They've been updated accordingly. Do the changes make sense?
1. Smoke test parts of Calypso that use the different `QueryManagers`:
   * Media
   * Paginated
   * Post
   * Term
   * Theme

## ~Blockers~
- [x] I'd like to land #18004 first to reduce the size and noisiness of this PR.

### CODE REVIEW

**Comment by sirreal** [comment]
> Have you also thought about doing the same for sort()? Do you think we can fit it in this PR?

@tyxla I did, however [`sort` references `this`](https://github.com/Automattic/wp-calypso/pull/17990/files#diff-90a76f3c723777b1a0c90ea618099ae8R128). It's not obvious to me how to remove that which is why I left `sort` out of this PR and didn't really plan on working on it. If you have suggestions I'd be happy to hear them.

A follow-up that I have been considering that would "solve" sort being an instance method is just dealing with plain objects rather than instances of these classes. I believe the instance creation holds little value and has the disadvantage of being cumbersome to serialize and deserialize when they're inserted directly in the state tree. I doubt I'll get to that soon, however 😉 

_now rebased and conflict free_

**Comment by ockham** [comment]
>> Have you also thought about doing the same for sort()? Do you think we can fit it in this PR?

> @tyxla I did, however [`sort` references `this`](https://github.com/Automattic/wp-calypso/pull/17990/files#diff-90a76f3c723777b1a0c90ea618099ae8R128). It's not obvious to me how to remove that

Sounds like an omission in the JS spec :thinking: -- calling one static method from another.

**Comment by ockham** [comment]
Hmm, what if you make `sort` static and leave that `this.compare()`? Is there any chance `this` will refer to the class (not the instance) in that case?

**Comment by ockham** [comment]
Oh, here's actually an instance of a `this.constructor` call inside another `static` method: https://github.com/Automattic/wp-calypso/pull/17990/files#diff-dd52bc2ad8a3958cd0183292db420d67R31

**Comment by ockham** [comment]
This seems to pass tests:

```diff
diff --git a/client/lib/query-manager/index.js b/client/lib/query-manager/index.js
index 1af04f8..4364e4b 100644
--- a/client/lib/query-manager/index.js
+++ b/client/lib/query-manager/index.js
@@ -115,7 +115,7 @@ export default class QueryManager {
         * @param  {Array}  items Items by which to sort
         * @param  {Object} query Query object
         */
-       sort( keys, items, query ) {
+       static sort( keys, items, query ) {
                keys.sort( ( keyA, keyB ) => {
                        if ( ! items[ keyA ] || ! items[ keyB ] ) {
                                // One of the items has yet to be removed from the
@@ -125,7 +125,7 @@ export default class QueryManager {
                                // method aren't required to implement this check.
                                return 0;
                        }
-                       return this.constructor.compare( query, items[ keyA ], items[ keyB ] );
+                       return this.compare( query, items[ keyA ], items[ keyB ] );
                } );
        }
 
@@ -390,7 +390,7 @@ export default class QueryManager {
                                                );
 
                                                // Re-sort the set
-                                               this.sort( memo[ queryKey ].itemKeys, nextItems, query );
+                                               this.constructor.sort( memo[ queryKey ].itemKeys, nextItems, query );
                                        }
                                } );
 
```

**Comment by tyxla** [comment]
@sirreal well, that's one of the reasons I love JS :wink: 

Calling `this` in a static class method refers to the class itself. I think it was called "autoboxing" or something. Seems to also work properly with inheritance. Handy, eh?

This means that if you have:

```
class Example {
	static do() {
		console.log( this );
	}
}

Example.do();
```

you'll see the `Example` constructor in your console. Similarly, if you have:

```
class A {
	static do() {
		console.log( this );
	}
	
	static make() {
		this.do();
	}
}

class B extends A {
	static do() {
		console.log( this );
	}
}

A.make();
B.make();
```

each of the 2 calls will display the corresponding class constructor. 

But still, if you wish to keep this out of this PR, I'm down for that. Your call :wink:

**Comment by sirreal** [comment]
Thanks for the nudge on `sort` @tyxla!

I've implemented static `sort` in this PR now. Please have another look!

**Pull request merged**
