### PR TITLE
Allow all primary My Home cards to be rendered in secondary

### PR DESCRIPTION
**Pull request by daledupreez**
Related to #83465

## Proposed Changes

* This PR refactors the code for primary and secondary cards in My Home so we can more clearly identify primary-only cards, and allow all of those cards to be rendered in the secondary area.
* The work here is a precursor to some related work where we want to shift My Home to a full two-column layout and show the Site Preview block at the top of the right sidebar, where all cards that were previously in the full-width primary section will be shown in the secondary section next to the sidebar.

  - Actually testing that this works depends on D127655-code, which updates the back end to rearrange the layout so we don't show anything in the primary area, but shift any cards in that location to the top of the secondary area (which is where this PR is needed!)

## Testing Instructions

There are two things we need to test with this PR:
1. That the code works with the current layouts, and
2. That the code works with the new two-column layouts we want to use

### Testing the current layout

* Run this branch via Calypso.live as per [this comment](https://github.com/Automattic/wp-calypso/pull/83828#issuecomment-1791512176), or locally
* For sites in various states, visit My Home for the site, and verify that the UI renders as expected. Valid states we should check include the following:
  - a site with an expired plan
  - a still-Atomic site with an expired plan
  - a site that was Atomic and has been reverted after the plan expired
  - a site with a Launchpad in Customer Home
  - a site where we're showing the site setup options
  - a launched site where the user has completed or skipped the site setup steps, and we're showing general promotional cards in the primary area

### Testing the two-column layout

* Apply D127655-code to your WordPress.com sandbox
* Ensure that requests to `public-api.wordpress.com` are being routed to your sandbox
* Ensure that the following PHP code snippet is running on your sandbox:
```php
add_filter( 'wpcom_my_home_force_two_column_layout', '__return_true' );
```
* Run this branch via Calypso.live as per [this comment](https://github.com/Automattic/wp-calypso/pull/83828#issuecomment-1791512176), or locally
* For sites in various states, visit My Home for the site, and verify that UI renders with two vertical columns, and the right column has the site preview in the first/top position. Note that many of the cards don't look great -- we need to address those cases before we can deploy the proposed layout changes. Valid states we should check include the following:
  - a site with an expired plan
  - a still-Atomic site with an expired plan
  - a site that was Atomic and has been reverted after the plan expired
  - a site with a Launchpad in Customer Home
  - a site where we're showing the site setup options
  - a launched site where the user has completed or skipped the site setup steps, and we're showing general promotional cards in the primary area

## Pre-merge Checklist

- [x] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [x] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [x] Have you checked for TypeScript, React or other console errors?
- [N/A] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [N/A] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [N/A] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

**Comment by valterlorran** [comment]
@daledupreez I rebased this PR and fixed the conflicts, I also tested the A/B experiment and everything seems to be working fine.

**Comment by valterlorran** [comment]
For one of my sites, it rendered a lot of cards that I think it was not supposed to:

### Calypso Live link
Screen Shot 2023-11-23 at 15 24 10

### WordPress.com
Screen Shot 2023-11-23 at 15 24 19

**Comment by daledupreez** [comment]
@valterlorran, that actually ends up being a really good test for rendering all those cards!

However, the bug here stems from the layout being returned from the server, rather than the client-side rendering. The problem stems from a difference between the primary and secondary areas: the primary area will render multiple items using a slider/carousel layout, so only one is visible at a time, while the secondary area will render multiple items in sequence. This is why we have plenty of work to do on D127655-code - there are a number of edge cases we need to handle much better.

**Comment by daledupreez** [comment]
As a quick follow-up, I've updated D127655-code to shift only one card across to the secondary array.

**Review by valterlorran — APPROVED** [review]
I tested and things looks good to me! The only problem is when we show the site setup checklist on the double column, but that will be fixed once we migrate it to the launchpad.

## Without applying the patch I had the following results:

### a site with an expired plan

Screen Shot 2023-11-24 at 10 34 42

### a still-Atomic site with an expired plan

Screen Shot 2023-11-24 at 10 37 36

### a site that was Atomic and has been reverted after the plan expired

Screen Shot 2023-11-24 at 10 40 20

### a site with a Launchpad in Customer Home

Screen Shot 2023-11-24 at 10 41 50

### a site where we're showing the site setup options

Screen Shot 2023-11-24 at 10 44 03

### a launched site where the user has completed or skipped the site setup steps, and we're showing general promotional cards in the primary area

Screen Shot 2023-11-24 at 10 48 23

## Applying the double column, I had the following results:

### a site with an expired plan

Screen Shot 2023-11-24 at 10 49 47

### a still-Atomic site with an expired plan

Screen Shot 2023-11-24 at 10 50 21

### a site that was Atomic and has been reverted after the plan expired

Screen Shot 2023-11-24 at 10 50 40

### a site with a Launchpad in Customer Home

Screen Shot 2023-11-24 at 10 51 04

### a site where we're showing the site setup options

Screen Shot 2023-11-24 at 10 51 24

### a launched site where the user has completed or skipped the site setup steps, and we're showing general promotional cards in the primary area

Screen Shot 2023-11-24 at 10 51 41

**Pull request merged**
