### PR TITLE
AT: temporarily disable new transfers

### PR DESCRIPTION
**Pull request by gwwar**
This temporarily disables new transfers while we fix some things. Existing AT sites should still see AT features.

### CODE REVIEW

**Comment by rralian** [comment]
Why wouldn't we disable the config flags instead?

**Comment by gwwar** [comment]
> isATEnabledForCurrentSite

Because then this function returns false for transferred sites. `isATEnabledForCurrentSite` is used in a number of places and certain features may be using it to display/hide particular components.

**Comment by rralian** [comment]
Then I think we're better off re-ordering the logic in that function to put the environment check after the "is already AT site" check.

**Comment by rralian** [comment]
Let's keep it enabled for local development, but the rest is good to 🚢

**Comment by gwwar** [comment]
👍  updated. I'll 🚢  when tests go green.

**Pull request merged**
