### PR TITLE
Gutenboarding design picker: add Ames, Jackson, and Kingsley themes

### PR DESCRIPTION
**Pull request by creativecoder**
#### Changes proposed in this Pull Request

* Add the recently launched Ames, Jackson, and Kingsley themes to the design step of /new site creation

#### Testing instructions

* Go to /new to create a new site
* Make sure you see Ames, Jackson, and Kingsley themes on the design selection step, for both the FSE Beta and regular flows
* Create a site with each of the themes in the FSE Beta flow and make sure they work as expected with the Site editor

### CODE REVIEW

**Comment by creativecoder** [comment]
I'm noticing a few problems with the new themes. I'll open separate issues if I'm not able to resolve them easily/quickly.

### Kingsley

#### Preview has no text

Screen Shot 2021-12-17 at 13 43 49

#### Block validation error when opening the Site editor

Screen Shot 2021-12-17 at 13 38 39

Screen Shot 2021-12-17 at 13 38 47


### Jackson and Ames

#### Footer text differs in editor vs front-end

| **Editor** | **Front-end** |
| - | - |
| Screen Shot 2021-12-17 at 13 40 36 | Screen Shot 2021-12-17 at 13 42 51 |

**Comment by creativecoder** [comment]
> Kingsley preview has no text

This should be resolved now, by marking the preview as static.

**Comment by creativecoder** [comment]
Fix for the Kingsley footer block validation error: https://github.com/Automattic/themes/pull/5224

**Comment by creativecoder** [comment]
The footer credit issue is not theme related. I've created an issue here: https://github.com/Automattic/wp-calypso/issues/59363

**Comment by creativecoder** [comment]
Block validation issue with Kingsley should be fixed now.

**Comment by jeyip** [comment]
Global Styles background color doesn't appear to apply correctly in Kingsley https://github.com/Automattic/themes/issues/5226

**Review by jeyip — APPROVED** [review]

**Comment by creativecoder** [comment]
Image alignment issue we also noticed while testing this: https://github.com/WordPress/gutenberg/issues/37504

(Visible in the site editor for the Jackson theme)

None of the remaining issues we're seeing look like blockers to me, so I'm going ahead with merging this.

**Pull request merged**
