### PR TITLE
Activity Log: Fixes #26184 and improves upgrade banners

### LINKED ISSUE #26184: Activity Log: add an unavailability notice for Jetpack sites on a free plan
Currently, for wordpress.com sites on a free plan, we show this notice:

screen shot 2018-07-18 at 9 45 55 pm

And for for Jetpack sites where Rewind is available, we have:

screen shot 2018-07-19 at 10 03 11 am

We need a third banner for Jetpack sites where Rewind is not available:

Here is the proposed copy:

`Upgrade to get all of Jetpack's essential features including more detailed activity logs.`

For the wpcom banner, i'd propose we change:

`See 30 days of past activity`

To:

`More detailed activity logs`

### PR DESCRIPTION
**Pull request by roccotripaldi**
This PR adds an upgrade banner for free Jetpack sites where Rewind™ is not available. The banner advertises daily-offsite backups, which will be highlighted when clicked.

screen shot 2018-07-19 at 4 19 19 pm

screen shot 2018-07-19 at 4 19 40 pm

This PR also updates the text on the banner we are using for free wordpress.com sites. This banner now advertises Jetpack's essential features which will be highlighted when clicked.

screen shot 2018-07-19 at 4 20 06 pm

screen shot 2018-07-19 at 4 20 28 pm

This PR also updates the feature-text for Jetpack essential features:

screen shot 2018-07-19 at 4 21 05 pm

Fixes #26184

### CODE REVIEW

**Comment by keoshi** [comment]
Another way to go about this is to replace the title with the longer text (`Get daily off-site backups and ...`) and get rid of the description entirely.

**Comment by keoshi** [comment]
Though I'm not seeing the banner on a free Jurassic Ninja Jetpack site:

image

Site: `formal-sally.jurassic.ninja`
Rewind status: `Rewind is unavailable`

**Comment by roccotripaldi** [comment]
> Though I'm not seeing the banner on a free Jurassic Ninja Jetpack site:

The reason rewind is unavailable is `missing_plan` in this case. Because you are an a12n and the site is jurassic.ninja, if you were to purchase a plan rewind would be active. 

This is expected.

If you were to connect a jurassic.ninja site to a non-a12n account, you'd see the banner added in this PR.

**Comment by michelleweber** [comment]
I agree that the upgrade title + upgrade button is too much upgrade. I'm +1 with replacing the title with the text underneath, or with an alternate word(s) like "Stay safe." For the text underneat, a wee edit:

Protect your data with daily off-site backups, and keep a closer eye on your site with expanded activity logs.

For the free site banner, I'd probably make it one paragraph rather than three bullets -- they feel a little overwhelming in the small space:

Enhance your WP.com experience
Improve your SEO, protect your site from spammers, and keep a closer eye on your site with expanded activity logs.

And for the feature text, I'd tighten up just a smidge:

Improve your SEO, protect your site from spammers, keep a closer eye on your site with expanded activity logs, and automate social media sharing.

**Comment by roccotripaldi** [comment]
Thanks for the thorough review @michelleweber - i went with 'Stay Safe' rather than having no title, because without it, the long, bold title got too cramped.

Screenshots: updated!

**Comment by keoshi** [comment]
Love it!!

**Pull request merged**
