### PR TITLE
Domains: Show filter reset notice when too few results are suggested

### PR DESCRIPTION
**Pull request by jsnmoon**
Suggested by @delputnam in #24718.

This feature will show a call-to-action card below the suggestions when the filters have been set too restrictively. Clicking on this notice will remove all set filters from the search.

restrictive_filters

# Test instructions
1. Check out this branch locally.
2. Navigate to `/start/domains/`. I like to enable the `domains/kracken-ui/filters` feature flag like [so](http://calypso.localhost:3000/start/domains?flags=domains/kracken-ui/filters) to see the TLD filters.
3. Enter a query, enable the exact match filter and the `.com` TLD filter. 
4. Ensure that the `Disable filters to see more results` appear below the suggestions.

### CODE REVIEW

**Comment by klimeryk** [comment]
I like the idea behind this, but the design is a bit confusing to me. It uses the same style of button we want to use to control pagination (`Show more results`). Additionally, it's not clear to me what will happen when I click that item - will it clear all filters? Or is it not clickable?

Maybe just making sure the selected filters are more visible is enough? Like @delputnam mentioned, just changing the color of the button is not enough, so maybe add the number next to the button (like it was previously) or something like that.

**Comment by jsnmoon** [comment]
@aidvu, did you meant to review #24509? @sixhours pointed out the same issue; it has since been fixed in the parent PR.

I'll update this branch soon with the styling fix.

**Comment by aidvu** [comment]
You mean on master the results appear ok? Please rebase and I can test again.

**Comment by klimeryk** [comment]
> I do think that there's some parallel to be made between a Show more button and Disable filters button in that they both provide more results to the user.

Ah, good point, I hadn't thought of it that way. For some reason I thought both buttons can be visible at the same time in the UI, but that's obviously not true. Then I guess this way of presenting it makes sense. I'd just iterate on the copy and figure out what needs to happen when you click on it - should we show the filters popover? TLD filter popover? Both? :D Or just clear the filters - but that's a bit drastic.

**Comment by sixhours** [comment]
This looks good to me from a design standpoint!

**Comment by aidvu** [comment]
Here's the situation I mentioned above, and why I requested changes:
- Go to Calypso
- Domains -> Add
- Type 1
- Filters, length 1
- See a bunch of default suggestions and the message to disable filters
- Endpoint returned `empty_results`

screen shot 2018-05-11 at 18 55 32

**Comment by jsnmoon** [comment]
@aidvu It should be fixed now - I removed rendering default suggestions when the API returns search results.

**Comment by aidvu** [comment]
Now we have a new case: https://github.com/Automattic/wp-calypso/pull/24780/commits/0604c26a7ab192118d5df0dddd8595aa88ba0f4e#diff-f336d76e81595260ad643406929153dfL39

I believe it's an object when we return an error. :) Can explicitly check the response key I guess.

**Pull request merged**
