### PR TITLE
Reader: Add Refresh Feed Header component

### PR DESCRIPTION
**Pull request by jancavan**
This PR adds the new Feed Header component as outlined in: https://github.com/Automattic/wp-calypso/issues/9097

screenshot 2016-11-16 10 00 10

For the blav/grav:
- If single author, show grav
- If multi-author, show blav

**This is v1 so we won't be including a header image:**

screenshot 2016-11-16 09 59 47

### CODE REVIEW

**Comment by jancavan** [comment]
**To dos (last item probably for a separate PR):**

- [ ] Add to Devdocs
- [ ] Grav/blav logic
- [ ] FIx spacing issues
- [ ] Update "Back" button to match mockup

**Comment by jancavan** [comment]
**Examples:**

- No blav/grav: https://calypso.live/read/feeds/50188124?branch=add/reader/refresh-feed-header-component
- No blav/grav/description: https://calypso.live/read/feeds/54262393?branch=add/reader/refresh-feed-header-component
- Long site names, long description: https://calypso.live/read/feeds/55547786?branch=add/reader/refresh-feed-header-component
- No site name (which then displays the site's URL): https://calypso.live/read/feeds/23059853?branch=add/reader/refresh-feed-header-component

I think we can handle the rest of the unchecked items in subsequent PRs.

**Comment by blowery** [comment]
🚢

**Comment by blowery** [comment]
Looks like we should scope it to the refresh. I'll fix it up.

**Comment by blowery** [comment]
scoped to the stream refresh feature flag in https://github.com/Automattic/wp-calypso/pull/9436/commits/de91f0c324184850fc158fe3421330e05867eb77

**Pull request merged**
