### PR TITLE
Separate selectors in `state/ui`.

### PR DESCRIPTION
**Pull request by sgomes**
Moves each `ui` selector to its own module, to improve tree-shaking in future changes. To ease migration, there's still an index file which imports and reexports them all.

This shouldn't have any immediate performance benefits, and the PR may actually slightly increase bundle size, due to the extra modules. It is expected to serve as the basis for future perf improvements, however.

Any perf improvements will likely only take place after dependants start importing individual selector modules, rather than importing from the index.

#### Changes proposed in this Pull Request

* Separate all the selectors in `client/state/ui` into their own modules.

#### Testing instructions

* Use Calypso normally and look out for any issues. There are no code changes to the selectors, so there shouldn't be any behaviour-type bugs introduced. Any bugs would likely be caused by an incorrect import somewhere. E2E tests should help here.

### CODE REVIEW

**Comment by sgomes** [comment]
Note: this PR is similar to #33546, for a different collection of selectors.

**Comment by jsnajdr** [comment]
Hi @sgomes! If you created a `package.json` file in `state/ui/selectors` that has the following content:
```json
{
  "sideEffects": false
}
```
It would start doing all the webpack tree shaking right away. Imports don't need to be changed.

**Comment by sgomes** [comment]
> Hi @sgomes! If you created a `package.json` file in `state/ui/selectors` that has the following content:
> 
> ```json
> {
>   "sideEffects": false
> }
> ```
> 
> It would start doing all the webpack tree shaking right away. Imports don't need to be changed.

😲 Oh wow, I had no idea I could just drop a `package.json` like that in a folder to explicitly declare there are no side effects! That's amazing! Thanks, @jsnajdr!

There may still be no immediate gains here, but the big change I'm working on (separating the login entrypoint) will likely see them.

**Review by jsnajdr — APPROVED** [review]
The [delta before and after](http://iscalypsofastyet.com/push/a1c829be4f27cd8f0fc5e7183fb436ee3c14c8e2/38e969fd002abd90a847474b0cafcadde05a9f42/) the `sideEffects` commit looks a bit weird: I don't undestand why stats size for `build` gets smaller, but in the end the parsed and gzip size of the chunk is bigger.

But I guess that doesn't really matter if this PR opens the door for other, much bigger improvements.

**Pull request merged**
