### PR TITLE
Reader: Use refresh cards everywhere

### PR DESCRIPTION
**Pull request by blowery**
Refactor how we inject refresh cards to support them acros the application, except in search. :/
Also, hook up feed and site info via redux. We do have this info (usually) in the flux store, but rather than making another crazy bridge, just prepare for the future and fetch what we need on demand.

### CODE REVIEW

**Comment by bluefuton** [comment]
Code looks good, and I've tested without the feature flag to make sure there are no regressions.

With the feature flag on, I get some inconsistent behaviour in the post card. Sometimes I receive a `site` object, but never a `feed`. In the cases I'd expect a feed, the site object can look like:

screen shot 2016-10-18 at 10 41 24

I also somehow managed to receive an image attachment's info in `site` on one occasion (and I received it for all posts in the stream):

screen shot 2016-10-18 at 10 42 44

**Comment by bluefuton** [comment]
I added some debugging to the card in 41733fb.

**Comment by bluefuton** [comment]
The issues I experienced were fixed in cc2ce05 👍 

We're preferring `feed` when we render the query selectors, so I've not actually seen a `site` make it to a card yet, but it is working as expected.

I'll clean up the debugging code.

**Comment by bluefuton** [comment]
Good to go I think! 🚢

**Comment by bluefuton** [comment]
@blowery says "should be getting the site info via meta" - apparently there's a bug in how we dispatch meta.

**Comment by bluefuton** [comment]
:ship:

**Comment by bluefuton** [comment]
We chatted in Slack about switching full post over to Redux as well for its `site` and `feed`. Suggest we tackle that in a followup PR.

**Comment by blowery** [comment]
I'll ship it in the morning unless you'd like to baby sit it tonight :)

**Comment by bluefuton** [comment]
I'm happy to shepherd it :) 🐑🐑🐑🐑🐶

**Pull request merged**
