### PR TITLE
Replace Yoast banner with Blaze banner on /marketing/traffic page

### PR DESCRIPTION
**Pull request by DustyReagan**
#### Proposed Changes

* Replace the Yoast SEO banner on marketing/traffic with a banner for Blaze.

Before | After
--|--
marketing-traffic-before  |  marketing-traffic-after

#### Testing Instructions

* Load this PR.
* Ensure clicking the banner CTA takes you to `https://wordpress.com/advertising/{blog-domain}`
* Ensure Tracks are being recorded for impressions and clicks
* Make sure banner appears on Simple, Atomic, and Jetpack connected sites
* Ensure the banner matches the Figma. pb5gDS-2fR-p2

#### Pre-merge Checklist

- [x] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [x] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [x] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [x] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

Related to https://github.com/Automattic/wp-calypso/issues/70835

### CODE REVIEW

**Review by lupus2k — APPROVED** [review]
Tested on Simple site and Atomic site!
Looks like the Figma, linked to the correct page and the tracking information works perfect.

image

image

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/7676363

Thank you @DustyReagan for including a screenshot in the description! This is really helpful for our translators.

**Review by lupus2k — APPROVED** [review]
Review 2.0, LGTM 🎉

**Review by paulopmt1 — APPROVED** [review]
Good job @DustyReagan. It's working as expected!

Tested on simple, Atomic, and Jetpack non-Atomic sites. I double-checked here if we can take advantage of non-Atomic Jetpack sites: p1671455569930669/1671219222.327439-slack-CKZHG0QCR

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/7676363).

**Pull request merged**
