### PR TITLE
ci(teamcity): Add a Keep-Rule for tagged trunk builds

### PR DESCRIPTION
**Pull request by scinos**
#### Changes proposed in this Pull Request

* Excludes successful `trunk` builds tagged by `<release-tag>` from the system clean-up.

Docs: https://www.jetbrains.com/help/teamcity/2020.2/clean-up.html
DSL docs: https://teamcity.jetbrains.com/app/dsl-documentation/jetbrains.build-server.configs.kotlin.v2019_2/-cleanup/index.html

#### Testing instructions

* Functionality can't be tested until merged
* Verify TeamCity builds still work, it will mean there are no syntax errors in the template.

### CODE REVIEW

**Comment by scinos** [comment]
I tried to have the `cleanup` rule in the `PluginBaseBuild` template first, but TC failed with:

```
    DSL script execution failure
06:22:32
    Validation error: Template 'calypso_PluginBaseBuild': Keep rules shouldn't be specified for templates
06:22:32
    Validation error: Template 'calypso_PluginBaseBuild', keep rule [1/1]: ID should be specified for keep rules
```

**Comment by noahtallen** [comment]
Nice find! a253950 attempts to do it at the project level, which seems possible per the docs (:crossed_fingers:)

**Review by noahtallen — APPROVED** [review]
Looks like it's working, so I'll try it out on trunk :)

**Comment by noahtallen** [comment]
Looks like it's working: 
image

**Pull request merged**
