### PR TITLE
Domains: Add better expiration redemption notices in the new domain status screens

### PR DESCRIPTION
**Pull request by hambai**
#### Changes proposed in this Pull Request

* Show if a domain is in redemption or not once it expires and for how long

We're showing a new message when a domain expires. So we might show that a domain has expired and can be renewed at no additional cost (it's within Auto Renew Grace Period) or if it's in redemption we show a slightly different message.

Within ARGP:

Screenshot 2020-02-18 at 16 18 55

In Redemption:

Screenshot 2020-02-18 at 16 18 16

depends on: D39026-code

#### Testing instructions

* The only way to trigger those is to actually hack/mock the response from the `/domains` API  (or just accidentally have a domain that is in ARGP or in redemption...)

### CODE REVIEW

**Comment by fditrapani** [comment]
I have an expired domain in grace period and am still seeing the old message:

image

I'm testing this on Calypso.live and enabled the flag through the url. Is there anything I'm missing?

**Comment by hambai** [comment]
> I'm testing this on Calypso.live and enabled the flag through the url. Is there anything I'm missing?

Yeah - you have to sandbox the public-api and apply D39026-code

**Comment by fditrapani** [comment]
> Yeah - you have to sandbox the public-api and apply D39026-code

aah ok. Sorry I missed that. I'll try again and report back.

**Comment by fditrapani** [comment]
hmmm. I still seem to be having issues getting it working — it's probably my setup. When I sandbox, and apply the patch, the new design is only visible on subdomians for me and I get this error in the console:

image

I'd be fine with merging this (if everyone else is happy with the code) and reviewing the design later.

**Comment by klimeryk** [comment]
That particular console error is unrelated to this PR and comes up normally when you sandbox `public-api`. Can't say for the rest, though, haven't tested the patch myself yet.

**Pull request merged**
