### PR TITLE
Move state.help.supportLevel state to state.happychat.user 

### PR DESCRIPTION
**Pull request by jsnajdr**
Implements part of the idea from https://github.com/Automattic/wp-calypso/pull/58635#issuecomment-982573281

First, moves the `state.help.supportLevel` state to `state.happychat.user.supportLevel`, where it really belongs. It's sourced from Happychat config endpoint and is used by a Happychat button. This change should prevent loading the `state.help` reducer at places unrelated to Help, and load only the Happychat one.

Second, I'm consolidating the three actions used to set stuff in `state.happychat.user` into one. They are called together at one place and they all write only to one reducer. Can be just one action to set them all.

Third, I'm renaming the unwieldy `state.happychat.user.isPresalesPrecancellationEligible` state to just `*.availability`. It's value is an object, so we're accessing fields `.availability.presale` and `.availability.precancellation`. That's a better naming IMO.

### CODE REVIEW

**Review by tyxla — COMMENTED** [review]
In my head, this PR contains 3 different changes that aren't necessarily related. I wonder if it makes more sense to split it further into 3 separate PRs. 

Furthermore, it would be nice if you could add some test instructions. Thanks in advance!

**Comment by jsnajdr** [comment]
Testing instructions: when Calypso loads, verify that it sends a REST request to `/help/olark/mine` and that the response looks like:

Screenshot 2021-12-03 at 12 27 06

and that some fields are stored to `state.happychat.user`, verbatim, the `state` looking like:

Screenshot 2021-12-03 at 12 27 32

Then follow the testing instructions from #58809 to test the presales chat button in Checkout, and from #58815 to test the precancellation chat button.

If you force the `availability.presales` and `availability.precancellation` values to `false`, the chat buttons should never appear.

> I wonder if it makes more sense to split it further into 3 separate PRs.

@tyxla I'd rather keep them together: all three commits are atomic and can be reviewed independently, and they all share common testing instructions. Seems to me that splitting the PR into three would only create more work for both of us?

Since first submitting this PR last week, I tested it thoroughly, leading to #58809 and #58815 getting merged first.

**Comment by tyxla** [comment]
Thanks for the testing instructions @jsnajdr! And yep, let's keep it together in the same PR. I'll review it today 👀

**Review by tyxla — APPROVED** [review]
Looking great! It was easier to review per-commit FWIW 👍

**Pull request merged**
