### PR TITLE
E2E: Simplify the page preview component helper

### PR DESCRIPTION
**Pull request by WunderBart**
#### Changes proposed in this Pull Request

By tweaking the logic behind switching from default content to the preview iframe, this PR reduces the time of the `PagePreviewComponent` initialization from ~20 seconds - which can cause timeout flakiness - to just ~2 seconds.

#### Testing instructions

All tests should pass.

### CODE REVIEW

**Comment by scinos** [comment]
`E2E tests (desktop)` build shows 18 tests that passed after a retry. That's an unusual high number, we usually have 2 or 3. Do you think it could be related to these changes?

I've restarted the build, just in case.

Edit: All 18 flaky tests pass in the re-run. 👍🏼 

image

**Review by noahtallen — APPROVED** [review]
makes sense to me

**Review by yansern — APPROVED** [review]
LGTM.

**Comment by fullofcaffeine** [comment]
Nice improvement in runtime! :) 

> By tweaking the logic behind switching 

Could you elaborate on what was causing the slowdown? 🙇🏻‍♂️

**Comment by WunderBart** [comment]
> Could you elaborate on what was causing the slowdown? 🙇🏻‍♂️

Sure, @fullofcaffeine! Firstly, the [old `switchToIFrame` helper method](https://github.com/Automattic/wp-calypso/pull/51907/files#diff-845cffa481ff3a748cdafa8b4c088c176e15a1010f5f9ca524db6c282dfb7095L57-L69) was doing a kind of backward and unnecessary check where it waited for the iframe content to be available **before** switching to iframe. The `untilAbleToSwitch` waiter is perfectly fine by itself, and any additional presence checks should come afterward if necessary. Secondly, that method was called early in most of the helper methods (not unnecessarily, but adding to the overall delay). And lastly, the same method was also [called synchronously in the constructor](https://github.com/Automattic/wp-calypso/pull/51907/files#diff-845cffa481ff3a748cdafa8b4c088c176e15a1010f5f9ca524db6c282dfb7095L17) which I'm not sure if actually slowed down the initialization, but definitely wasn't switching to the preview iframe 😄. I hope it makes sense!

**Pull request merged**
