### PR TITLE
Add/warning in restore if backup is running

### PR DESCRIPTION
**Pull request by mavegaf**
#### Proposed Changes

This change adds a change in the restores. If you want to do a restore and there is a backup running at that moment, you will see a warning message, and if you accept to do the restore, the backup will be stopped.

Annotation on 2022-10-03 at 20-28-56

#### Testing Instructions

While a backup is in execution, go to "Jetpack/Backup" and select a backup to do a restore. You will see a warning. Start the restore, and after some seconds, the restore will start.

#### Pre-merge Checklist

- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [x] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [x] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?

Related to #

### CODE REVIEW

**Comment by macbre** [comment]
Not a React expert so can't really provide any feedback regarding the code itself.

But I did tested the "backup in currently running" warning for my test site - https://container-zealous-kepler.calypso.live/backup/wptest.macbre.net/restore/1665150141.051 .

It shows up even when the backup has been started AFTER visiting the above page:

Screenshot 2022-10-07 at 16 42 27

And it goes away once the backup is completed 👌🏻 

Performed the restore when the backup was running. [The backup job](https://mc.a8c.com/rewind/logs.php?blogId=210391515&type=backup&order=desc&which=1665157462&when=1665157462) has been stopped and [the restore started](https://mc.a8c.com/rewind/logs.php?blogId=210391515&type=restore&order=desc&which=398332&when=1665157473):

```
info: 0%: Setting status of previously killed job 353130766 to error.
```

**Review by macbre — APPROVED** [review]
But still worth to have someone more React-savvy to jump in.

**Review by Initsogar — APPROVED** [review]
Looks good to me. Tested and working as expected.

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/7575081

Thank you @mavegaf for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/7575081).

**Pull request merged**
