### PR TITLE
Make sidebar footer fixed for “My Sites”, “Reader”

### PR DESCRIPTION
**Pull request by coreh**
This PR makes the sidebar footer (which houses “Help” and “Add New Site” options, depending on your setup) fixed when scrolling the sidebar. This should hopefully make the “Help” option more discoverable .(Right now it's not visible by default on small displays.)

We achieve this by introducing sidebar regions: Groups of elements on the sidebar that scroll together on overflow, while allowing for the other elements to remain fixed. They are useful for implementing static headers/footers.

On small screen devices, the per-region scrolling behavior is disabled, and the entire sidebar scrolls instead.

### CODE REVIEW

**Comment by jasmussen** [comment]
I'm okay with this, provided it works well on mobile also (haven't tested).

CC: @mtias though, who wrote the initial flex code for this.

**Comment by folletto** [comment]
Tested on Chrome, I found two bugs:

1. Both My Sites and Reader have additional space at the top.
2. On reader an horizontal scrollbars shows (please code with [scrollbars on](https://cloud.githubusercontent.com/assets/4389/15742496/2d2991be-28b7-11e6-9a04-5e3fdd30bc73.png))

bug-12

**Comment by coreh** [comment]
Chrome issues fixed. The mobile rendering was also slightly broken on Chrome, it's now fixed as well.

I've also made the desktop app promo fixed along with the footer.



Thought that made sense.

**Comment by bisko** [comment]
LGTM! 👍

**Comment by folletto** [comment]
Tested, works on Chrome, Safari, Firefox, Edge.

On IE11 shows a double scrollbar tho:

screen shot 2016-06-03 at 16 38 35

Which is a regression (currently it does show already a scrollbar, but simply extends when more items are added, doesn't double up).

**Comment by coreh** [comment]
IE11 issue fixed, by adding a class to the sidebar whenever it has regions as children, and disabling `overflow: auto` on the sidebar when it has the class. (And we're not on mobile)

**Comment by folletto** [comment]
Tested, works on Chrome, Firefox, Edge, IE11. Works on these.

However, there's a regression on Safari, the area is stuck in the position it was before starting scroll:

screen shot 2016-06-06 at 12 15 06

**Comment by jasmussen** [comment]
> However, there's a regression on Safari, the area is stuck in the position it was before starting scroll:

This sounds suspiciously like [this Safari flexbox bug](https://github.com/philipwalton/flexbugs#3-min-height-on-a-flex-container-wont-apply-to-its-flex-items), for which I believe in the past I've fixed it by applying `flex-basis: 0;` to the container that won't behave.

**Comment by coreh** [comment]
stp

Good news @jasmussen, is that that Safari flexbox bug seems to be fixed for the next Safari release, then. I'll apply your workaround.

**Comment by coreh** [comment]
Adding `flex-basis: 0;` to the parent container didn't work, but adding `flex-shrink: 0;` to the `.sidebar__region` fixed it on Safari 9. 🔮 ✨ 🎩

**Comment by jasmussen** [comment]
> Adding flex-basis: 0; to the parent container didn't work, but adding flex-shrink: 0; to the .sidebar__region fixed it on Safari 9

Ah that's awesome, I must've misremembered. Glad you worked it out!

**Comment by coreh** [comment]
Tested on:

[ ] Safari 9
[ ] Safari Technology Preview
[ ] Chrome
[ ] Firefox
[ ] IE11
[ ] Edge

**Comment by michaeldcain** [comment]
:shipit:

**Pull request merged**
