### PR TITLE
ThemesSelection: Switch to Redux-based analytics

### PR DESCRIPTION
**Pull request by mcsf**
Prerequisite of #12438 

# Testing

- No changes should be observed from a user's perspective.
- Browsing/using the Theme Showcase should fire analytics events in the console (as before) and in the Redux inspector (new).

### CODE REVIEW

**Comment by mcsf** [comment]
@ockham, was cf3b66e a good move?

**Comment by ockham** [comment]
> @ockham, was cf3b66e a good move?

Looks a bit like we accidentally stopped using that. I'll try to find out when that happened.

cc'ing @folletto in case you think we did that on purpose/are fine dropping it.

**Comment by ockham** [comment]
Hmm, apparently we used it as a prop to `ThemesListFetcher` [which was removed](https://github.com/Automattic/wp-calypso/pull/10019/files#diff-92db9da6cd542d8019e23323409c5c21L74) by #10019.

**Comment by folletto** [comment]
> you think we did that on purpose/are fine dropping it.

It's an important data point in knowing how many people struggled and got to the point of reaching the end before finding a theme that worked. We need to keep it.

**Comment by mcsf** [comment]
> It's an important data point in knowing how many people struggled and got to the point of reaching the end before finding a theme that worked. We need to keep it.

Gotcha. So I'll undo the deletion of the method and y'all can link it back in a separate PR.

**Comment by mcsf** [comment]
Done. Last review? :]

**Comment by ockham** [comment]
Okay, in that case @mcsf better revert cf3b66e, and we'll try to re-enable it.

**Comment by ockham** [comment]
Jinx 😄

**Pull request merged**
