### PR TITLE
Sign Up: Update Reader Images

### PR DESCRIPTION
**Pull request by torres126**
#### Changes proposed in this Pull Request

Looking at #30004, I noticed that the `start/reader/reader-landing` route has some outdated images. Although some of the interface has changed across Calypso since, the most notable change is that the colours are outdated with the new schemes recently added. I think that these two changes justify updating them. 

- Update the images in favour of consistency, to reflect the new colours and designs
- Set the border using CSS - the result shouldn't have any visible differences, but it's far more convenient in case this is ever touched again and should hopefully prevent Laser Black causing any issues
- Remove the borders from the current images so they don't duplicate due to the proposed CSS

I tried to be consistent using Discover but I couldn't find the conversations when searching through Calypso. :/ Either way, that layout has seem to change, so I created something similar instead though. 

#### Testing instructions

Compare the two layouts at `start/reader/reader-landing`

**Current:**

dsgfdgfsdfsgsdgf

**Proposed:**

fasdfsdafadsaf

@drw158, @shaunandrews, @fditrapani (not exactly certain on who to ping for this, sorry!): would you mind please taking a look at this? :) 

cc @bluefuton

### CODE REVIEW

**Comment by fditrapani** [comment]
Nice update. The new images look good to me. 

Something to note for another PR, with the new background colour, and the content in a card, the first CTA looks like it's hovering there at the top. It might fit better with the content outside the card. cc @shaunandrews

**Comment by torres126** [comment]
Started a PR over at #30287 for the button. :+1:

**Comment by torres126** [comment]
Would be a shame to see this one slip away from review as it shouldn't be too tricky since it's just images, so pinging a few more folks who've touched these styles recently in case anyone has some spare time. :) 

cc @bluefuton, @flootr, @blowery

**Comment by bluefuton** [comment]
This is great! Thanks for your contribution @torres126.

Would it be possible to swap the last screenshot ("Lively conversations made easy") with one from Reader Conversations (http://wordpress.com/read/conversations), as in the original version?

**Comment by bluefuton** [comment]
Shall we compress the PNGs with a tool like [TinyPNG](http://tinypng.com) too? The images are fair bit larger than the current ones:

screen shot 2019-02-11 at 10 46 23

**Comment by torres126** [comment]
Neat, I never knew that tab still existed! Thanks @bluefuton, updated and compressed. Looks like the panda's happy too. :)

screenshot_20190210-222437

**Comment by bluefuton** [comment]
Thanks to you and the panda for the changes 🐼

Can we change the crop on the last image to make it a similar height to the others? It feels a bit slender compared to the other three.

Original:

screen shot 2019-02-11 at 14 20 27

This PR:

screen shot 2019-02-11 at 14 20 35

**Comment by torres126** [comment]
Sure thing, addressed. :)

**Comment by bluefuton** [comment]
Thanks @torres126! Looks good to me.

**Pull request merged**
