### PR TITLE
server/pages: Convert Jade to JSX templates

### PR DESCRIPTION
**Pull request by ockham**
WIP, still dysfunctional. Reboot of `10207-gh-calypso-pre-oss`.

Rationale: To get rid of Jade/Pug, and to be able to use components like `EmptyContent` in 404/500.

TODO:
* [ ] Get rid of error
* [ ] Update 404, 500, desktop
* [ ] Perf?

### CODE REVIEW

**Comment by gwwar** [comment]
We should be able to get a smaller shrinkwrap diff with the following:
```
npm uninstall --save jade
clingwrap jade
npm install --save express-react-views@0.10.0
clingwrap express-react-views
```

Let me know if you need any help 😄

**Comment by ockham** [comment]
Thanks @gwwar, that helped already! I made a mistake during the clingwrap procedure (installing a wrong package) and wasn't able to sort it out afterwards. Followed your instructions now, and the diff looks much better!

**Comment by ockham** [comment]
Note to self -- revisit after the Node 6 upgrade (#5595) has been merged.

**Comment by lancewillett** [comment]
Closing as older and possibly abandoned. Feel free to re-open if still valid and in-progress.

**Pull request closed without merging**
