### PR TITLE
Adds e2e tests for My Home “Get help” support search

### LINKED ISSUE #43135: (8P) Write e2e tests to cover basic _existing_ mechanics of support search for FAB and My Home
Currently, there are no e2e tests that cover the support search in:

- [x] the FAB ("?" icon bottom right)
- [ ] the My Home "Get help" card.

We should write these to cover the basic feature set to avoid regressions to a critical element for our users.

## Testing Scenarios

- [x] Can see initial default contextual results and empty search field.
- [x] Can perform a valid search and see resuts.
- [x] Can clear search field and return UI to default state.
- [x] Can perform invalid search and see "No results" indicator in UI and contextual results.
- [x] Can "search" for empty string and see no search has been performed.

### My Home "Get help" card specific scenarios

- [ ] Can see Card appear.

### FAB specific scenarios

- [x] Can see FAB toggle.
- [x] Can toggle open the popover.
- [x] Can close the popover.
- [x] Do not see FAB toggle on Home when switching from another Page.

### PR DESCRIPTION
**Pull request by getdave**
Builds on https://github.com/Automattic/wp-calypso/pull/43381 to add e2e tests to cover the support search instance on the "My Home" page (ie: the "Get help" card).

Screenshot 2020-06-24 at 14 18 19

This also [parallelizes the test runs as per @bsessions85 advice](https://github.com/Automattic/wp-calypso/pull/43625#issuecomment-648977498).

#### Testing instructions

* Configure the Calypso local e2e testing environment [as per the docs](https://github.com/Automattic/wp-calypso/blob/f35d4cc98655259e379fe220be9b9ecee6bac647/test/e2e/README.md).
* Boot Calypso locally - `yarn && yarn start`. Make sure it's running at `http://calypso.localhost:3000/`.
* Run the individual e2e test 
  - `cd` to the `test/e2e` directory.
  - run `./node_modules/.bin/mocha specs/wp-my-home-support-search.js`
* See tests run and verify they all pass.
* Do the same against tablet and mobile using following command syntax - `env BROWSERSIZE=mobile ./node_modules/.bin/mocha specs/wp-support-search`.
* Read through tests and check there are no missing scenarios that might be helpful to cover.
* ⚠️  **Important:** verify that the tests for the FAB support search still continues to pass as well - `./node_modules/.bin/mocha specs/wp-inline-help-support-search.js`.

Fixes https://github.com/Automattic/wp-calypso/issues/43135

### CODE REVIEW

**Comment by getdave** [comment]
@bsessions85 Before I go too far are you happy with the way this is proceeding?

Note that @retrofox and I intend to refactor out the need to have multiple selectors for the support search by creating 1 unified component that is consumed by both instances (ie: FAB and My Home). This should reduce complexity and ensure the test helper component is responsible for one thing only rather than having multiple selectors for everything.

**Comment by bsessions85** [comment]
@getdave This looks good. It will be nice to combine things later, but this works for now. I did realize that we need to get the parallel tag added to this test and the other test so that it will run in CI. I could have swore I checked last time, but I guess maybe I was dreaming.

**Comment by bsessions85** [comment]
@getdave just add `@parallel` to the describe line [here](https://github.com/Automattic/wp-calypso/pull/43625/files#diff-ee9c2265e132bb01029cbd6575d6cc4cR38) so that it looks like `describe( 'My Home "Get help" support search card @parallel', function () {`

also add it [here](https://github.com/Automattic/wp-calypso/blob/master/test/e2e/specs/wp-support-search.js#L34)

**Comment by getdave** [comment]
@bsessions85 This is ready for another review if you have time. Much appreciated.

**Comment by getdave** [comment]
Failing tests are again due to unrelated problems ongoing with rate limiting. If @bsessions85 says we are good to go then we should be ok to merge this.

**Comment by bsessions85** [comment]
@getdave These look good but they aren't running in CI yet. You'll need to rename the test files to end in -spec.js. Sorry for missing that before.

**Review by bsessions85 — APPROVED** [review]
Looks good! Thanks!

**Comment by getdave** [comment]
I may wait until next week to deploy this now. Also maybe the CI tests will be more stable by then.

**Comment by getdave** [comment]
This will be merged tomorrow UTC.

**Pull request merged**
