### PR TITLE
Editing Toolkit: Update to 2.8.3

### PR DESCRIPTION
**Pull request by Copons**
### Changes proposed in this Pull Request

* Version bump and changelog

### Testing instructions

* Editor close button should deal with situation where experimental GB feature is unavailable (https://github.com/Automattic/wp-calypso/pull/46666)
* Premium Content: Remove double banners (https://github.com/Automattic/wp-calypso/pull/46659)
* Premium Content: Add missing migrations for margin fix (https://github.com/Automattic/wp-calypso/pull/46924)
* Editing Toolkit: Add a workaround to prevent slider blocks breaking the editor at full width (https://github.com/Automattic/wp-calypso/pull/46951)
* Focused Launch: added WIP Focused Launch modal behind a flag (https://github.com/Automattic/wp-calypso/pull/46686)

### CODE REVIEW

**Review by Copons — COMMENTED** [review]
- Editing Toolkit: Add a workaround to prevent slider blocks breaking the editor at full width (#46951)

I've tested my own change, and I can confirm it fixes the issue on Atomic sites (Simple sites are getting the same fix from a Jetpack update synced to WPCOM already)

**Comment by ciampo** [comment]
Added and tested

* Focused Launch: added WIP Focused Launch modal behind a flag (https://github.com/Automattic/wp-calypso/pull/46686)

**Comment by apeatling** [comment]
Tested both my PRs and working :+1:

**Review by apeatling — APPROVED** [review]

**Comment by ciampo** [comment]
Just merged phab patch and released version 2.8.3 to dotorg

**Pull request merged**
