### PR TITLE
Login: improve autofill detection on iOS & Safari

### LINKED ISSUE #47089: Login: improve autofill detection on iOS & Safari
Our login forms are on multiple pages and we can help autofill detect correct inputs with `autocomplete="current-password"` and `autocomplete="username"`.

> Explicitly defining an input element’s autocomplete value lets you support login workflows that couldn’t otherwise be detected by Password AutoFill’s heuristics. For example, the heuristics assume the user name and password inputs are on the same page. If you have a multipage login form, explicitly setting the username and current-password types lets the user tap and fill those inputs, even if they are on separate pages.

via https://developer.apple.com/documentation/security/password_autofill/enabling_password_autofill_on_an_html_input_element

### PR DESCRIPTION
**Pull request by vivianxu1230**
Login forms are on multiple pages and we can help autofill detect correct inputs with autocomplete="current-password" and autocomplete="username".

#### Changes proposed in this Pull Request
* Added type "email" and "password" + autocomplete attributes "current-password" and "username" in accordance with [Apple docs](https://developer.apple.com/documentation/security/password_autofill/enabling_password_autofill_on_an_html_input_element
) to allow detection by Password Autofill's heuristics on multiple login pages.

#### Testing instructions

* Log in with multiple browsers, observe saved passwords correctly load into the fields provided.

Fixes #47089

### CODE REVIEW

**Comment by vivianxu1230** [comment]
This is ready for review

**Review by lsl — CHANGES_REQUESTED** [review]
:wave: Thanks for this PR! I added the "Needs Review" label so that CircleCI will kick off the end to end tests for your change.

This PR needs a couple of changes before it can be merged.

Both `type="..."` attribute additions need to be removed,

- The `type="email"` attribute tells some browsers to validate the field as an email address, this will prevent people logging in with a username instead of email which is something we want to allow with this login form.
- The `type="password"` attribute is something we want here but it is already set by the [underlying component](https://github.com/Automattic/wp-calypso/blob/61acc957638fc7009632af4c0c058aa6bc0e82b7/client/components/forms/form-password-input/index.jsx#L58) so it is not needed here too.

**Comment by vivianxu1230** [comment]
@lsl Thank you for reviewing the changes! I removed both "type" attributes from each input and pushed my changes. Let me know if anything else needs to be changed before it gets merged

**Comment by lsl** [comment]
Thanks @vivianxu1230 appreciate the change, it all LGTM but I'll need defer this to someone that can test password autocomplete in Safari. @p-jackson may be able to fit this in?

**Review by lsl — APPROVED** [review]
LGTM but can't test in safari.

**Review by p-jackson — APPROVED** [review]
Changes LGTM. `autoComplete="off"` was originally added back in e9d51db09ea62ce6c071f52eb673e9f296cdda73, which is so long ago it doesn't look like we were even doing pull requests, so I can't find any discussion about why it was disabled in the first place. Heads up to @stephanethomas in case he happens to remember why it was set to `"off"`. No worries if you can't, it was a long time ago 🙂 

It could just be that the heuristics have changed over time, and I think we should be encouraging users to use password managers, whether that's through extensions or built into browsers.

Manually kicked off the automated tests. Tested on Safari, Edge, Chrome, Firefox and with 1Password. The heuristics still work fine on each 👍

**Comment by vivianxu1230** [comment]
Thank you all for being apart of my first pull request as a newbie citizen
software engineer! I hope to contribute more and more meaningfully :)

Best,
Vivian

**Comment by stephanethomas** [comment]
Thanks for the ping @p-jackson!

> autoComplete="off" was originally added back in e9d51db, which is so long ago it doesn't look like we were even doing pull requests,

That change was part of https://github.com/Automattic/wp-calypso/pull/14363. You can access that pull request from the commit page by clicking the reference in the header:

screenshot

> autoComplete="off" was originally added back in e9d51db. Heads up to @stephanethomas in case he happens to remember why it was set to "off". 

I think the reason was that enabling auto complete on a password field was seen as a bad security practice. Imagine someone using a browser on a shared computer at an Internet coffee: if they don't use incognito mode or forget to clean up the browser, someone else could take over their account by probing the password and user name fields. You should probably check with Secops what they think of this pull request 🙂.

**Pull request merged**
