### PR TITLE
Add devdocs source-code

### PR DESCRIPTION
**Pull request by wilsonpage**

### CODE REVIEW

**Comment by wilsonpage** [comment]
> I can’t select the text in Safari, though it works in other browsers.

@nb which text are you referring to? Source code is selectable for me.

**Comment by wilsonpage** [comment]
> I am missing two more pieces of information – the GitHub link to the component/example and the proper import statement to use the component. Not sure if it’s within scope of the PR, but I still had to look outside of the component page to be able use it in my code.

I agree these two bits will be super useful, but I think they should be landed as a follow-up, just to keep this patch from getting too large and unreviewable :)

**Comment by wilsonpage** [comment]
@nb I've push a few more commits since your feedback. Some things to note:

- The horizontal layout is a bit broken for some examples like the big form example. This is due do some components not scaling down to some widths, especially when a viewport breakpoint is not triggered.
- I've migrated the (preffed off) component-usage-stats logic to the newly created component-detail page. You'll need to flip the `devdocs/components-usage-stats` flag to see this. `form/*` components are not currently showing usage-stats, but shouldn't be too hard to fix this.
- Some examples have toggle controls which look a bit visually misaligned in places. Idealyl we'd have a nice way for examples to define 'example controls' that we can layout differently in different contexts.
- The source tree is not being updated when the example component's state changes.
- Titles on the list view still aren't obviously clickable.

---

I can keep on refining this patch, but interested to know what you think is the best path forward at this stage :)

**Comment by wilsonpage** [comment]
screen shot 2017-05-15 at 18 14 39

**Comment by nb** [comment]
> > I can’t select the text in Safari, though it works in other browsers.
> @nb which text are you referring to? Source code is selectable for me.

It was selecting the source code, but I can’t reproduce it anymore.

**Comment by nb** [comment]
Thanks for addressing the issues from #13380, @wilsonpage.

I agree that we could leave the extra bits of information for later. The only thing I’d like to see before merging this is updating the source code, based on example components’ state.

**Comment by wilsonpage** [comment]
> I agree that we could leave the extra bits of information for later. The only thing I’d like to see before merging this is updating the source code, based on example components’ state.

Is it OK that some of the (less responsive) components (eg form fields) look broken in the detail view?

**Comment by nb** [comment]
Small bit: why on `/devdocs/design/f-a-q` some of the string props are in curly braces?

**Comment by nb** [comment]
It looks like the EllipsisMenu is missing its source code.

**Comment by nb** [comment]
> Is it OK that some of the (less responsive) components (eg form fields) look broken in the detail view?

They don't seem super broken to me and it’s also a good test on how they look in a more narrow field. I am still not sure about the vertical view, but I am sure people will complain if it doesn't work.

Does the source-code-and-state consistency make sense as a blocker, or do you think we should merge without it?

**Comment by wilsonpage** [comment]
> Does the source-code-and-state consistency make sense as a blocker, or do you think we should merge without it?

It's a small change, we may as well include it 😃  Although I'm most concerned about missing examples that aren't showing source; this is due to their components being 'stateless' which for some reason means we can't get hold of an instance `ref` which we need for stringification. But I can do a thorough check before merge.

Did you try the patch with the usage-stats flag on? It's quite a handy addition. I hope we can pref it on by default at some point during this work.

**Comment by wilsonpage** [comment]
@nb after looking into updating code when component updates, it's a little more tricky that I initially thought. AFAIK the only way to get access to a component's `componentDidUpdate()` lifecycle callback is internally. In this case we want to access it externally from the example's parent component which places the example and renders it's source.

There may be a hacky way of doing this, but I'd have to dig in deeper into React internals. The only other way I can think of achieving this in a non-hacky way would be to alter every example component to expose their lifecycle callback so that the outside world can know when it updated, but this would be a lot of work and place this requirement on example authors.

It would be good to brainstorm possible approaches and see what others come up with here :)

**Comment by alisterscott** [comment]
Closing as this PR is stale - please reopen if necessary

**Comment by drw158** [comment]
This is pretty great. Like you stated above, the horizontal layout will break the visuals of some components. In order to make progress, I suggest to first just use a vertical layout (insert code block below the component).

**Pull request closed without merging**
