### PR TITLE
Reader: Make post links and links in content safe

### PR DESCRIPTION
**Pull request by blowery**
Ensure they have a valid protocol (http or https) before allowing them through the normalizer.

### CODE REVIEW

**Comment by samouri** [comment]
This PR is making `feeds` (redux) and `post` (flux / post-normalizer?) objects safe. What about sites?

**Comment by samouri** [comment]
Code Seems good, as do the tests, but its a bit hard to tell through the prettification thats jumbled with it.

@blowery: can you provide testing instructions?

**Comment by blowery** [comment]
> What about sites?

sites are already safe thanks to some backend work. we should ensure their safety, but that's another PR.

**Comment by blowery** [comment]
> can you provide testing instructions?

sure, will do out of band.

**Comment by blowery** [comment]
rebased and forced

**Comment by samouri** [comment]
jakebot: https://calypso.live/?branch=fix/reader/bad-links

**Comment by samouri** [comment]
branch worked for me. fix the unit test and 🚢 at will

**Comment by blowery** [comment]
@samouri test fixed. lost in the rebase.

**Pull request merged**
