### PR TITLE
Update broken links in CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by ro-savage**
The internal links in CONTRIBUTING.md are broken as it was written expecting to be in root.

Fixes issue #4764

### CODE REVIEW

**Comment by lancewillett** [comment]
Looking good, one link is still broken: LICENSE.md has `./` in front of it.

**Comment by ro-savage** [comment]
Thanks Lance. I shouldn't have missed that.

I tried to rebase into one commit, but couldn't get it working (haven't done it before). Hopefully you can just use the pull and squash feature that is now in github.

If you need me to rebase & squash, let me know and I will figure it out.

**Comment by lancewillett** [comment]
Here's how to do it via command line:

1. Make sure your clone is on branch `master` and up to date.
2. Switch to your branch and run `git rebase -i master`
3. This opens an editor, where you can pick the commit(s) to keep, change `pick` to `squash` or just delete lines (edit commit message if needed). For example, change the prefix for all but first line to "fixup".
4. Save the file.
5. In the branch, run `git push -f` to push changes. This will force the history rewrite.
6. Done. :)

**Comment by ro-savage** [comment]
@lancewillett Thanks for the tip lance. I kept trying to rebase from HEAD~2 rather than from master. Great to contribute and learn something new :)

Should now be a single commit and ready to go now.

**Comment by ro-savage** [comment]
My IDE has auto-updated some of the tab/spacing. So fixed that and rebased.

**Comment by lancewillett** [comment]
🚢

**Pull request merged**
