### PR TITLE
Jetpack: update Jetpack Search illustration asset

### PR DESCRIPTION
**Pull request by keoshi**
#### Changes proposed in this Pull Request

* Removes old style illustration.
* Introduces a new illustration asset.

#### Testing instructions

* Test in WordPress.com
  1. Go to `http://calypso.localhost:3000/jetpack-search/SITE_URL` where `SITE_URL` is a Jetpack site with and without a Search subscription.
  1. Go to `http://calypso.localhost:3000/jetpack-search/SITE_URL` where `SITE_URL` is a WordPress.com simple site with and without a Search subscription.
* Test in Jetpack.com
  1. Go to `http://jetpack.cloud.localhost:3001/jetpack-search/SITE_URL` where `SITE_URL` is a Jetpack site (currently connected) with and without a Search subscription.
* Make sure you see the new illustration in all scenarios.

Related to 1199980337313591-as-1200819373070128

#### Screenshots

Before | After
--|--
image | image
image | image

### CODE REVIEW

**Review by Luchadores — APPROVED** [review]
This looks good to me 😊

**Comment by eeeeevon13** [comment]
@keoshi  is that using the wp.com search icon?

**Comment by keoshi** [comment]
@eeeeevon13 It is not — for now I've decided to use the same icon that we have on the Cloud sidebar (Gridicon), so that they're at least consistent with each other:

image

Will add a new card on Asana to update all the sidebar icons on Cloud and, when we do so, we can update this one again.

**Comment by keoshi** [comment]
> Will add a new card on Asana to update all the sidebar icons on Cloud

Added here: 1199980337313591-as-1200907868342144

**Review by cbauerman — COMMENTED** [review]
I'm seeing some interesting behavior as the browser width scales down -

@ ~700px the icon disappears
calypso localhost_3000_jetpack-search_cbauermantesting wordpress com

then it reappears @ ~500

calypso localhost_3000_jetpack-search_cbauermantesting wordpress com (1)

I just wanted to check that is intentional.

**Comment by keoshi** [comment]
@cbauerman Good catch! It does seem like it's intentional indeed: https://wpcalypso.wordpress.com/devdocs/design/promo-section

Even if it's a bug, it should probably be fixed in the [Promo Section component](https://github.com/Automattic/wp-calypso/tree/38c37bbfe35b8c741c4e346637987ddc0fb3ab59/client/components/promo-section) upstream, right?

**Comment by keoshi** [comment]
@Luchadores @eeeeevon13 We've now merged https://github.com/Automattic/wp-calypso/pull/55984 so I've updated this PR to reflect the latest icon from WordPress core.

**Review by rcanepa — APPROVED** [review]
LGTM.

It looks amazing on both Calypso Blue and Green. I also tested these changes on different viewport sizes and it always looked fine.

Great work!

**Pull request merged**
