### PR TITLE
Plans (Pricing): Use data-store pricing for cancel-purchase form

### PR DESCRIPTION
**Pull request by chriskmnds**
Part of addressing https://github.com/Automattic/wp-calypso/issues/86638

## Proposed Changes

We update the cancel purchase form for the marketing survey to utilize the Plans data-store for the plan pricing shown. 

This results in stripping out a few selectors under `client/state/purchases` and gets us a step closer to deprecating/removing completely `getPlanRawPrice` selector.

## Why are these changes being made?

We only need one form of handling plan pricing in the code base, more so one framework. Anything else risks having alternative and differing views of the same data propagating across the code base.

## Testing Instructions

- See https://github.com/Automattic/wp-calypso/pull/92235#issuecomment-2205254146 for the two cases (Premium/Personal) plan
- Ensure the plan purchase is made through a test credit card, not store credits. Just enable store sandbox and use the mocked credit card:

Screenshot 2024-07-04 at 3 23 53 PM

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Comment by chriskmnds** [comment]
@dzver you worked on the underlying code here. Do you mind giving me some high-level instructions on how to trigger the plan upsells in the cancel-purchase form of the marketing survey? There are two (one that references the personal plan and another the monthly)

(I'm trying to make sense of all the conditioning to render the form, but it's quite a bit - perhaps you can save me the hassle if you recall)

**Comment by dzver** [comment]
For the Personal plan upsell:

1. Get a 1-year Premium/Explorer plan
2. Go to the cancellation form and select that the plan was too expensive
3. You should see the offer to switch to Personal/Starter

For the monthly plan upsell:
1. Get a 1-year Personal
2. Go to the cancellation form and select that the plan was too expensive

I would also check what happens if I'm on Explorer and answer that I need plugins in the test plan.

LMK when it's ready and I'll test it as well. I have some time available in the late afternoon.

**Comment by chriskmnds** [comment]
Thanks @dzver 

Here's how my testing goes:

> For the Personal plan upsell:
> 
> 1. Get a 1-year Premium/Explorer plan
> 2. Go to the cancellation form and select that the plan was too expensive
> 3. You should see the offer to switch to Personal/Starter

I am able to see the upsell for this. I notice that we actually don't use the downgrade plan's (personal) price in this case (we just pass it through, but don't actually render the PlanPrice component). I think this is fine. This is where I land (same as production):

Screenshot 2024-07-03 at 1 01 44 PM


> For the monthly plan upsell:
> 
> 1. Get a 1-year Personal
> 2. Go to the cancellation form and select that the plan was too expensive

I am not able to trigger the upsell for this case. I always land on this "sorry to see you go" step when on personal 1-year plan:

Screenshot 2024-07-03 at 1 25 42 PM

I am doing a few more tests. also spotted an error in my code, which i fixed :-)

**Comment by chriskmnds** [comment]
@dzver follow-up to my previous comment:

> I am not able to trigger the upsell for this case. I always land on this "sorry to see you go" step when on personal 1-year plan:

It looks like there is a [canRefund](https://github.com/Automattic/wp-calypso/blob/89432e76c6adb3de607ed7e0c016984859e3238f/client/components/marketing-survey/cancel-purchase-form/get-upsell-type.ts#L61) condition in `get-upsell-type.ts` that is `false` for the personal 1-year plan, which blocks the upsell type from turning into `downgrade-monthly`. Hardcoding that value to `true` will render the upsell after the first step in the survey, as expected with the correct pricing (9 EUR per month):

Screenshot 2024-07-03 at 1 56 04 PM

Do you think this is a bug? We can address it separately, but not sure if it's just intended behavior.

**Comment by dzver** [comment]
> It looks like there is a [canRefund](https://github.com/Automattic/wp-calypso/blob/89432e76c6adb3de607ed7e0c016984859e3238f/client/components/marketing-survey/cancel-purchase-form/get-upsell-type.ts#L61) condition in `get-upsell-type.ts` that is `false` for the personal 1-year plan, which blocks the upsell type from turning into `downgrade-monthly`. Hardcoding that value to `true` will render the upsell after the first step in the survey, as expected with the correct pricing (9 EUR per month):

How do you test? I noticed from your screenshot that you also have a $0 refund, which is also unexpected and looks like a bug.

**Comment by chriskmnds** [comment]
> > It looks like there is a [canRefund](https://github.com/Automattic/wp-calypso/blob/89432e76c6adb3de607ed7e0c016984859e3238f/client/components/marketing-survey/cancel-purchase-form/get-upsell-type.ts#L61) condition in `get-upsell-type.ts` that is `false` for the personal 1-year plan, which blocks the upsell type from turning into `downgrade-monthly`. Hardcoding that value to `true` will render the upsell after the first step in the survey, as expected with the correct pricing (9 EUR per month):
> 
> How do you test? I noticed from your screenshot that you also have a $0 refund, which is also unexpected and looks like a bug.

@dzver i just hardcoded that value to `true` (at that location where the call to `getUpsellType` is made) so that it triggers the condition to return the `downgrade-monthly` upsell. I guess that may have other side effects. I will dig into what creates the `canRefund` flag - it's unclear why it's false on a new plan purchase 🤔

**Comment by chriskmnds** [comment]
@southp @dzver I tagged you both in https://github.com/Automattic/wp-calypso/issues/92374#issuecomment-2208760870 (you worked on that function, you probably know the quickest way around)

**Comment by chriskmnds** [comment]
Confirmed both cases and they look identical to production. 

I attempted to but decided not to make additional refactors (like removing the `downgradePlanToPersonalPrice` when it's never rendered). I am not familiar with the context of it being there. The component itself should be refactored at some point to function form and remove the additional wrapper to communicate with the data-store. cc @southp if worth putting up an issue for it and on which board.

Screenshot 2024-07-08 at 12 13 25 PM

Screenshot 2024-07-08 at 12 15 32 PM

**Pull request merged**
