### PR TITLE
Prevents upsell for Jetpack Backup for multisite installations

### PR DESCRIPTION
**Pull request by ChaosExAnima**
#### Changes proposed in this Pull Request

* Adds an additional state for multisite installations to notify users that Backup is not available.
* Removes unused file `wpcom-upsell.tsx` in the Jetpack Cloud code.
* Fixes a bug with the Scan request code that causes a fail when threats are not an array.

#### Screenshots
Screen Shot 2020-07-15 at 3 00 34 PM

#### Testing instructions

* Create a Jetpack multisite and connect it.
* With this code, visit cloud.jetpack.com and navigate to the Backup nav for the site.
* Verify Backup matches screenshot above.

**Note**: Jetpack Scan may not show the correct state for multisites. This is a known issue and is due to an API issue.

Fixes 1184358343400545-as-1184719508034178.

### CODE REVIEW

**Comment by cleacos** [comment]
Should this PR work for the Jetpack (Calypso) upsells?

**Comment by ChaosExAnima** [comment]
> Should this PR work for the Jetpack (Calypso) upsells?

No, as the Calypso side of things uses different components. It's a good point, and we should implement that in a different PR. :)

**Comment by ChaosExAnima** [comment]
> It works as expected for the Backup section. One question, in the end, should the Scan section have the same/similar message for multisite?

@cleacos whoops, should have updated the testing code. This PR applies to Scan as well!

**Comment by cleacos** [comment]
> This PR applies to Scan as well!
For Scan section it didn't work, I saw the normal upsell page. @ChaosExAnima

**Comment by ChaosExAnima** [comment]
@cleacos - Yes, see the note above under the testing instructions. That is expected.

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/4101660

Thank you @ChaosExAnima for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/4101660).

**Pull request merged**
