### PR TITLE
Plans: Add feature descriptions

### LINKED ISSUE #6568: Plans: Add feature descriptions
Here are popup feature descriptions for our plans:

- **Custom Domain Name**: Get a free custom domain name (mywebsite.com) with this plan to use for your website.
- **Remove WordPress.com Ads**: Allow your visitors to visit and read your website without seeing any WordPress.com advertising.
- **Email & Live Chat Support**: High quality support to help you get your website up and running and working how you want it.
- **Hundreds of Free Themes**: Access to a wide range of professional theme templates for your website so you can find the exact design you're looking for.
- **Unlimited Premium Themes**: Unlimited access to all of our advanced premium theme templates, including templates specifically tailored for businesses.
- **Basic Design Customization**: Customize your selected theme template with pre-set color schemes, background designs, and font styles.
- **Advanced Design Customization**: Customize your selected theme template with extended color schemes, background designs, and complete control over website CSS.
- **3GB/13GB/Unlimited Storage Space**: With increased storage space you'll be able to upload more images, videos, audio, and documents to your website.
- **$100 Advertising Voucher**: $100 Google AdWords credit after spending the first $25. Offer valid in US and Canada.
- **$200 Advertising Voucher**: $100 Google AdWords credit after spending the first $25 (valid in US & Canada), plus a $100 Wordads advertising credit (valid worldwide).
- **Monetize Your Site**: Add advertising to your site through our WordAds program and earn money from impressions.
- **VideoPress Support**: The easiest way to upload videos to your website and display them using a fast, unbranded, customizable player with rich stats.
- **Remove WordPress.com Branding**: Give your site a more professional look by removing the "Powered by WordPress.com" branding in the footer of your website.
- **Google Analytics Integration**: Track website statistics with Google Analytics for a deeper understanding of your website visitors and customers.

### PR DESCRIPTION
**Pull request by lamosty**
Fixes #6568.

## Testing Instructions

1. Run Calypso with `ENABLE_FEATURES=manage/plan-features make run`;
2. Go to `/plans`;
3. See the popup feature descriptions;
4. Read the copy and make sure it matches @apeatling's one in #6568 and/or is typo-free.

## Screenshots

selection_034

## Questions/notes for @apeatling 

We don't have "Basic Design Customization", "Remove WordPress.com Branding" features yet, therefore, I'm not adding the description. Is that okay?

I have not changed the text for "$200 Advertising Voucher" because currently it includes a nice divider. Should I add the new copy and update the divider?

selection_035

```js

getDescriptionWithWordAdsCredit: () => i18n.translate( '$100 Google AdWords credit after spending the first $25. Offer valid in US and Canada. {{hr/}}Business also includes $100 of advertising from WordAds on WordPress.com.', {
	components: {
		hr: <hr className="plans-compare__info-hr"/>
	}
} )
```

@gwwar 

Test live: https://calypso.live/?branch=add/plan-features-descriptions

### CODE REVIEW

**Comment by gwwar** [comment]
@lamosty `custom design` refers to being able to save custom site css, so this should map to 
```text
Customize your selected theme template with extended color schemes, background designs, and complete control over website CSS.
```
@apeatling isn't `Remove WordPress.com Branding` against our TOS?

**Comment by gwwar** [comment]
👍 Everything else looks good here, so feel free to 🚢 when you've added a description for custom design

**Comment by lamosty** [comment]
@gwwar Thanks for the review!

> custom design refers to being able to save custom site css, so this should map to

This maps to `FEATURE_CUSTOM_DESIGN` in `lib/plans/constants`. But what about `Basic Design`? I can add the feature to the constants file but what plans on WPcom support it? Free and Personal?

> isn't Remove WordPress.com Branding against our TOS?

I think it is at the moment but there was a discussion about this a while ago: p1464969077006675-slack-plans-focus. However, I don't know the status of this and will wait for @apeatling's answer.

**Comment by apeatling** [comment]
Remove WordPress branding is a new feature just launched this week.

**Comment by apeatling** [comment]
https://en.blog.wordpress.com/2016/07/06/customize-footer-credit/

**Comment by lamosty** [comment]
I've added the no branding, basic design features; renamed custom design to advanced design and updated all plan features titles to match the ones in @apeatling's issue.

>  Give your site a more professional look by removing the "Powered by WordPress.com" branding in the footer of your website.

Are we sure we want to market this as "more professional look"? Wouldn't users with WP branding think it's a bit derogatory, esp. those who want to have WP.com branding and also VIPs?

**Comment by apeatling** [comment]
Let me run this past editorial and get back to you.

**Comment by apeatling** [comment]
@lamosty Updated wording for remove branding: "Keep the focus on your site's brand by removing the WordPress.com footer branding".

**Pull request merged**
