### PR TITLE
P2: redirect to Home when trying to access Plans

### PR DESCRIPTION
**Pull request by lamosty**
In this PR, we fix a bug with the P2 project in which we allow interacting with the Plans page when navigated to it directly.

We enable using the plans page if the P2+ (P2 paid plan) is enabled. So far it's enabled only on dev and staging so a12s will be able to use it.

We also fix a bug in which if you navigate to the Manage Domains page with a P2 site you are redirected to `/` instead of the site's home as it's very closely related.

## Testing

1. Locally, with the config flag `"p2/p2-plus"` set to whatever as it shouldn't affect this one: Navigate to a non-p2 site's Manage Domains page (under Manage in sidebar). Now, switch to a P2 site. You should be redirected to the site's Home page.
2. Locally, with the config flag `"p2/p2-plus"` set to `true`: Navigate to a non-p2 site's Plans page. Now, switch to a P2 site. You should stay on the Plans page and see the P2+ option.
3.  Locally, with the config flag `"p2/p2-plus"` set to `false`: Navigate to a non-p2 site's Plans page. Now, switch to a P2 site. You should be redirected to the site's Home page.

### CODE REVIEW

**Comment by lamosty** [comment]
@scinos hey, I see you wrote some of the Plans page routing tests. Could you please give this PR a quick look to verify we don't break anything unexpected? Thanks! :)

**Comment by scinos** [comment]
@lamosty I don't have enough context to verify the logic but, overall, the change (including fixing the test, thanks!) seems ok to me 👍

**Review by unDemian — APPROVED** [review]
Tests out as described and code looks like it is not going to affect other use cases.

**Comment by lamosty** [comment]
Thanks for the reviews!

**Pull request merged**
