### PR TITLE
Reader: Fix top margin in streams, z-indexing issues

### PR DESCRIPTION
**Pull request by jancavan**
A top margin was recently added to Discover and Search streams: https://github.com/Automattic/wp-calypso/pull/8160, but this also added a top margin to mobile view which shouldn't be there.

**Before (in all streams):**
screenshot 2016-09-30 14 16 13

**After (also fixed in all streams):**
screenshot 2016-09-30 14 16 45

I've also come across other visual bugs that have been fixed in this PR.

- Featured post titles floating on top sidebar

**Before:**
screenshot 2016-09-30 14 19 36

**After:**
screenshot 2016-09-30 14 20 27

- Search box floating on top of sidebar

**Before:**
screenshot 2016-09-30 14 17 58

**After:**
screenshot 2016-09-30 14 21 22

### CODE REVIEW

**Comment by bluefuton** [comment]
Not sure if this is related, but I do sometimes now get the follow button lurking over the top of the menu in Firefox:

screen shot 2016-09-30 at 16 17 29

**Comment by bluefuton** [comment]
Margin fix looks good 👍

**Comment by jancavan** [comment]
Good catch @bluefuton. I found this happening when you click Tags from the sidebar. Fixed in: https://github.com/Automattic/wp-calypso/pull/8385/commits/11c42985f83adeb09195e0f9d6460f56c3e1949f

**Comment by jancavan** [comment]
> Good catch @bluefuton. I found this happening when you click Tags from the sidebar. Fixed in: 11c4298

Sorry, that caused the Following state to be slightly cut-off. Actual fix is in: https://github.com/Automattic/wp-calypso/pull/8385/commits/458a54ffecdb5370a8d082f18c6ef0a941e2ab6e

Another issue I found was `z-index` in Search photo cards. Example: http://calypso.dev:3000/read/search?q=photography

screenshot 2016-10-03 11 16 58

Also fixed in the same changeset.

**Comment by blowery** [comment]
looks good, ship away

**Pull request merged**
