### PR TITLE
WPCOM: Remove `wpcom.undocumented()` from this world

### LINKED ISSUE #58458: Framework: Refactor away from `wpcom.undocumented()`
### Details

We’re in the process of removing `wpcom-undocumented` in favor of the `wpcom` library. Many have already been removed in recent PRs, but there are still some that need to be refactored and removed.

See p4TIVU-9KX-p2 for more details.

If you need a review or have any questions, please don't hesitate to ping @Automattic/team-calypso-frameworks.

### Checklist

- [x] `undocumented().jetpackLogin()` - @tyxla, #58575
- [x] `undocumented().jetpackAuthorize()` - @tyxla, #58575
- [x] `undocumented().jetpackIsUserConnected()` - @jsnajdr, #58943
- [x] `undocumented().settings()` - @tyxla, #58901
- [x] `undocumented().isDomainAvailable()` - @chad1008, #58243
- [x] `undocumented().checkAuthCode()` - @chad1008, #58956
- [x] `undocumented().getInboundTransferStatus()` - @chad1008, #58315
- [x] `undocumented().startInboundTransfer()` - @jsnajdr, #58945
- [x] `undocumented().getAvailableTlds()` - @tyxla, #58569
- [x] `undocumented().getDomainPrice()` - @tyxla, #58902
- [x] `undocumented().readFeedPost()` - @tyxla, #58650
- [x] `undocumented().readSitePost()` - @tyxla, #58650
- [x] `undocumented().readSitePostRelated()` - @tyxla, #58568
- [x] `undocumented().launchSite()` - @jsnajdr, #58952
- [x] `undocumented().themes()` - @tyxla, #58239
- [x] `undocumented().themeDetails()` - @tyxla, #58239
- [x] `undocumented().jetpackThemeDetails()` - @tyxla, #58239
- [x] `undocumented().installThemeOnJetpack()` - @tyxla, #58239
- [x] `undocumented().deleteThemeFromJetpack()` - @tyxla, #58239
- [x] `undocumented().activateTheme()` - @tyxla, #58239
- [x] `undocumented().uploadTheme()` - @tyxla, #58239
- [x] `undocumented().resendIcannVerification()` - @tyxla, #58990, #59234
- [x] `undocumented().fetchDns()` - @tyxla - #59056
- [x] `undocumented().updateDns()`  - @tyxla - #59056
- [x] `undocumented().applyDnsTemplate()` - @tyxla - #59056
- [x] `undocumented().applyDnsTemplateSyncFlow()` - @chad1008, #59146
- [x] `undocumented().getDnsTemplateRecords()` - @chad1008, #59146
- [x] `undocumented().transferToUser()` - @jsnajdr, #59059
- [x] `undocumented().transferToSite()` - @jsnajdr, #59059
- [x] `undocumented().changeTheme()` - @jsnajdr, #58999
- [x] `undocumented().isSiteImportable()` - @tyxla, #59007
- [x] `undocumented().fetchImporterState()` - @tyxla, #58545
- [x] `undocumented().updateImporter()` - @tyxla, #58545
- [x] `undocumented().uploadExportFile()` - @tyxla, #58545
- [x] `undocumented().getSiteConnectInfo()` - @jsnajdr, #59110
- [x] `undocumented().importReaderFeed()` - @tyxla, #58578
- [x] `undocumented().wordAdsApprove()` - @jsnajdr, #58862
- [x] `undocumented().initiateTransfer()` - @tyxla, #58239
- [x] `undocumented().transferStatus()` - @tyxla, #58897
- [x] `undocumented().oauth2ClientId()` - @jsnajdr, #58896
- [x] `undocumented().getDomainConnectSyncUxUrl()` - @tyxla, #59168
- [x] `undocumented().domainsVerifyRegistrantEmail()` - @tyxla, #58990
- [x] `undocumented().domainsVerifyOutboundTransferConfirmation()` - @tyxla, #59168
- [x] `undocumented().getMigrationStatus()` - @tyxla, #58944
- [x] `undocumented().resetMigration()` - @tyxla, #58944
- [x] `undocumented().startMigration()` - @tyxla, #58944
- [x] `undocumented().getAtomicSiteMediaViaProxy()` - @jsnajdr, #58903
- [x] `undocumented().getAtomicSiteMediaViaProxyRetry()` - @jsnajdr, #58903
- [x] `undocumented().getMatchingAnchorSite()` - @jsnajdr, #58991
- [x] `undocumented().me().getReceipt()` - @tyxla, #58510
- [x] `undocumented().me().getPeerReferralLink()` - @tyxla, #58449
- [x] `undocumented().me().setPeerReferralLinkEnable()` - @tyxla, #58449
- [x] `undocumented().me().sendVerificationEmail()` - @tyxla, #58452
- [x] Remove `wpcom.undocumented()` from `wpcom` - @tyxla, #59237

### PR DESCRIPTION
**Pull request by tyxla**
#### Changes proposed in this Pull Request

This PR does the last cleanup to remove `wpcom.undocumented()` completely. It also removes some legacy references and unnecessary mocks. We're also renaming the `wpcom-undocumented` wrapper to `wpcom-oauth-wrapper`, because that's what the remaining functionality of that wrapper does.  

A good potential follow-up to this PR could be to call that wrapper only when the `oauth` feature flag is enabled, but if it's disabled, just use `wpcom-proxy-request` directly.

Fixes #58458.

#### Testing instructions

* Verify Calypso builds well.
* Smoke test Calypso and verify you can still perform requests properly. 
* Smoke test Jetpack Cloud and verify you can still perform requests properly.
* Go through the user signup flow and verify it still works well.
* Verify all tests pass.

### CODE REVIEW

**Comment by jsnajdr** [comment]
> A good potential follow-up to this PR could be to call that wrapper only when the `oauth` feature flag is enabled

That would break things because the `loadToken` functionality is used in Signup when creating a new user. There, in a logged-out session, things are done in the following order:
1. Initialize the REST proxy without auth info, sending anonymous `public-api` requests.
2. Call `/users/new` which will return a `bearer_token` and also set login cookies
3. But the REST proxy would have to be reloaded and the `iframe` reinitialized to start using these login cookies. It continues to be anonymous until that.
4. Instead of reloading, we call `wpcom.loadToken( bearerToken )` which make the proxy to send `Authorization: Bearer` headers. In other words, Signup uses OAuth after creating a new user.
5. Only after leaving Signup and navigating to Checkout (with full reload, not a history push) the REST proxy is reloaded.

The `loadToken` functionality is used _only_ in Signup for the purpose I just described. Regular OAuth mode (in Jetpack Cloud or in OAuth-enabled Calypso) doesn't use it.

**Comment by jsnajdr** [comment]
One corollary: the user signup flow should be tested before this PR is merged. I'll do that in the next 2 hours.

**Comment by tyxla** [comment]
> One corollary: the user signup flow should be tested before this PR is merged. I'll do that in the next 2 hours.

Good point! I've added that as a separate point in the testing instructions.

**Review by jsnajdr — APPROVED** [review]
Looks good, even the `/users/new` flows work correctly.

**Comment by bluefuton** [comment]
Nicely done! This is a good Christmas present for Calypso 🎅

**Pull request merged**
