### PR TITLE
update wording for cancel/stop campaign

### PR DESCRIPTION
**Pull request by benzhu56**
#### Proposed Changes

* issues/631, cancel/stop campaign should use different wording:

|  cancel |  stop |
|---|---|
|  Screen Shot 2022-09-12 at 12 32 12 |  Screen Shot 2022-09-12 at 11 57 01 | 

#### Testing Instructions
Check the campaigns page and compare the cancel/stop campaign wording against the design.

*

#### Pre-merge Checklist

- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [x] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [x] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?

Related to #

### CODE REVIEW

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/7524963

Thank you @benzhu56 for including a screenshot in the description! This is really helpful for our translators.

**Comment by emilyaudela** [comment]
Hi there! Our translators called out a small grammatical error. There should be a comma after `continue` in the sentences

`If you continue your campaign will immediately stop running.`

and 

`If you continue an approval request for your add will be cancelled, and the campaign won't start.`

Without the comma, it reads like "if you continue your campaign..." and the sentence is confusing.

**Comment by benzhu56** [comment]
thanks, I've just confirmed with the designer and we will add the comma, I'll get a PR soon!

**Comment by benzhu56** [comment]
https://github.com/Automattic/wp-calypso/pull/67838 to fix this.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/7524963).

**Pull request merged**
