### PR TITLE
Signup: Add OAuth in the browser

### PR DESCRIPTION
**Pull request by scruffian**
This replaces the old way of logging the user into the REST Proxy using the bearer token by using OAuth to log the user in during signup in the development environment. 

We well need to enable this in all environments before deploying.

This change will require all developers to log in to calypso.localhost.

To log in in development you need to copy the config settings for the desktop app.

We also need to consider if we should use secure cookies.

### CODE REVIEW

**Comment by Tug** [comment]
This is the error I have when I try to login in development env:
```
Error: config key `desktop_oauth_client_id` does not exist in "development.json"
   at config (/Users/tug/Work/Automattic/wp-calypso/build/webpack:/server/config/index.js:47:8)
   at oauth (/Users/tug/Work/Automattic/wp-calypso/build/webpack:/server/api/oauth.js:14:14)
   at proxyOAuth (/Users/tug/Work/Automattic/wp-calypso/build/webpack:/server/api/oauth.js:30:5)
   at Layer.handle [as handle_request] (/Users/tug/Work/Automattic/wp-calypso/node_modules/express/lib/router/layer.js:95:5)
   at next (/Users/tug/Work/Automattic/wp-calypso/node_modules/express/lib/router/route.js:131:13)
   at Route.dispatch (/Users/tug/Work/Automattic/wp-calypso/node_modules/express/lib/router/route.js:112:3)
   at Layer.handle [as handle_request] (/Users/tug/Work/Automattic/wp-calypso/node_modules/express/lib/router/layer.js:95:5)
   at /Users/tug/Work/Automattic/wp-calypso/node_modules/express/lib/router/index.js:277:22
   at Function.process_params (/Users/tug/Work/Automattic/wp-calypso/node_modules/express/lib/router/index.js:330:12)
   at next (/Users/tug/Work/Automattic/wp-calypso/node_modules/express/lib/router/index.js:271:10)
```

**Comment by scruffian** [comment]
Thanks @Tug I fixed it by coping the config from the desktop app...

**Comment by drewblaisdell** [comment]
It is nice to see Calypso running without `wpcom-proxy-request` with so few changes.

> This change will require all developers to log in to calypso.localhost.

As well:
- The notifications iframe is broken when cookies on set `.wordpress.com` are absent.
- The cookie set during signup lives for one year. We should update this to mirror the current behavior of the `wp-login.php` redirect.
- We can add the secure flag to the cookie by setting the `secure` property ([docs](https://www.npmjs.com/package/cookie#secure)) of the options object we pass to [`cookies.serialize`](https://github.com/Automattic/wp-calypso/blob/master/client/lib/oauth-token/index.js#L24).

**Comment by Tug** [comment]
> We can add the secure flag to the cookie by setting the secure property (docs) of the options object we pass to cookies.serialize.
I'm pretty sure those two properties can only be set from the server.

**Comment by Tug** [comment]
Seems like I was mistaken. I did a few test and it seems the secure attribute does work from the client side (obviously it's not the case for the httpOnly attribute).
We just have to keep in mind that since we're using cookie as a storage mechanism though, the bearer token won't be safe against XSS attacks.
Now I don't think the secure attribute is needed if we have calypso running locally (using the loopback interface), so we could have a condition to set the secure attribute such as:
```
const secure = 'development' !== config( 'env' ) || 'https:' === document.location.protocol;
```
What do you think? Does that solve our problem?

**Comment by scruffian** [comment]
Abandoning this in favour of https://github.com/Automattic/wp-calypso/pull/3561

**Pull request closed without merging**
