### PR TITLE
Remove all createClass instances using codemods

### PR DESCRIPTION
**Pull request by samouri**
This PR seeks to remove all usages of the deprecated `createClass` from the reader codebase.
It does so by taking advantage of the codeshifts defined in [react-codemods](https://github.com/reactjs/react-codemod) (`pure-render-mixin` and `class`).

Notes:
1.  `pure-render-mixin` transform only works on PureRenderMixin if it was `require`ed.  not if it was `import`ed.  Thats why the first step in this process was to do a sed find/replace to transform all of the imports into requires.
2. [wp-prettier](https://github.com/samouri/prettier) is a fork of prettier that keeps all of calypso's spacing. it means that there aren't any extraneous whitespace diffs in this PR

This PR was created by running these commands:

```bash
#  1 use require instead of import for PureRenderMixin
git grep -l "import PureRenderMixin from 'react-pure-render/mixin';" -- client/reader/ | xargs  sed -i '' -e "s|import PureRenderMixin from 'react-pure-render/mixin';|var PureRenderMixin = require( 'react-pure-render\/mixin' );|g"
git commit -anm "require PureRenderMixin instead of importing it"
 
# 2. run the pure-render-mixin transform
git commit -nam "run pure-render-mixin transform"
jscodeshift -t ../react-codemod/transforms/pure-render-mixin.js --extensions=js,jsx client/reader

# 3. run wp-prettier
./../prettier/bin/prettier.js  --write client/reader/*.js* && ./../prettier/bin/prettier.js  --write client/reader/**/*.js*
git commit -anm "run wp-prettier"

# 4. run the createClass codemod
jscodeshift -t ../react-codemod/transforms/class.js --extensions=js,jsx  --mixin-module-name=react-addons-pure-render-mixin --pure-component=true --remove-runtime-proptypes=false client/reader 

#5 run wp-prettier again
# 3. run wp-prettier
./../prettier/bin/prettier.js  --write client/reader/*.js* && ./../prettier/bin/prettier.js  --write client/reader/**/*.js*
git commit -anm "run wp-prettier"

```

### CODE REVIEW

**Comment by samouri** [comment]
output: 

```
client/reader/site-stream/featured.jsx: `` was skipped because of inconvertible mixins.
client/reader/sidebar/index.jsx: `ReaderSidebar` was skipped because of inconvertible mixins.
client/reader/following-edit/index.jsx: `FollowingEdit` was skipped because of inconvertible mixins.
client/reader/following-edit/list-item.jsx: `SubscriptionListItem` was skipped because of invalid field(s) `smartSetState` on the React component. Remove any right-hand-side expressions that are not simple, like: `componentWillUpdate: createWillUpdate()` or `render: foo ? renderA : renderB`.
client/reader/following-edit/notification-settings.jsx: `FollowingEditNotificationSettings` was skipped because of deprecated API calls. Remove calls to getDOMNode, isMounted, replaceProps, replaceState, setProps in your React component and re-run this script.
```

**Comment by samouri** [comment]
Even after this we still have 5 outliers to resolve:

1. [ ] client/reader/site-stream/featured.jsx
2. [ ] client/reader/sidebar/index.jsx
3. [ ] client/reader/following-edit/index.jsx
4. [ ] client/reader/following-edit/list-item.jsx
5. [ ] client/reader/following-edit/notification-settings.jsx

**Comment by samouri** [comment]
@blowery, do you have any idea how to fix this one?
>  client/reader/sidebar/index.jsx -- observeUser

**Comment by samouri** [comment]
I think i'm opting for installing `react-create-class`.  It  needs to happen at some point anyway

**Comment by blowery** [comment]
@samouri should be able to switch over to `state/user-settings/` and friends

**Comment by samouri** [comment]
closing in favor of: https://github.com/Automattic/wp-calypso/pull/13965

**Pull request closed without merging**
