### PR TITLE
Checkout: Do not display contact details form if the cart is only renewals, take 2

### PR DESCRIPTION
**Pull request by sirbrillig**
#### Changes proposed in this Pull Request

This is another attempt at https://github.com/Automattic/wp-calypso/pull/44468, which was reverted in https://github.com/Automattic/wp-calypso/pull/44506

This PR changes the behavior of the new checkout form's contact details so that it will not display if the cart contains only renewal items and the existing cached contact details are valid. This behavior should mostly match [old checkout](https://github.com/Automattic/wp-calypso/blob/096d4759a964ebb19bcf0a068e51d438e9fab080/client/my-sites/checkout/checkout/index.jsx#L917). Previously, we had been displaying the contact details form fields any time that there were domain products in the cart.

In addition, it prevents sending the `domain_details` property to the transactions endpoint (and to paypal, etc.) when the cart contains only renewals.

#### Screenshots

Before:

Screen Shot 2020-07-27 at 2 21 16 PM

After:

Screen Shot 2020-07-27 at 2 17 32 PM

#### Testing instructions

- Add a domain product to your cart (we may want to test this with different domain products for completeness) and visit checkout.
- Verify that you see the full "Contact information" step including name, address, and phone number.
- Complete the purchase. Verify that the purchase is successful. (Bonus: monitor the `/me/transactions` API call and make sure that `domain_details` is sent with the full contact data.)
- Visit http://calypso.localhost:3000/me/purchases and click the domain, then click "Renew now". You'll be redirected to checkout.
- Verify that the "Contact information" step only includes the "tax" information which is just postal code and country.
- Complete the purchase. Verify that the purchase is successful. (Bonus: monitor the `/me/transactions` API call and make sure that `domain_details` is sent with `null`.)

### CODE REVIEW

**Comment by michaeldcain** [comment]
Tested the following:

- Renewed existing (old) domain purchase. Saw country/zip contact details (pre-filled). Renewed successfully. `null` was sent in `domain_details` to `/me/transactions`.
- Created new, free site (existing user), and purchased a domain in Signup. Saw full contact details (pre-filled). Purchased successfully. Full information was sent in `domain_details` to `/me/transactions`.
- Immediately renewed new domain. **Saw "Invalid domain mapping product in cart" notification.** Saw country/zip contact details (pre-filled). Renewed successfully **but "Invalid domain mapping product in cart" notification persisted**. `null` was sent in `domain_details` to `/me/transactions`.
- Created new paid site with paid user and purchased a domain. Saw full contact details. Purchased successfully. Full information was sent in `domain_details` to `/me/transactions`.

In general, everything worked correctly, but on the immediate renewal there was an invalid domain mapping notification. I'm wondering if this happens in old Checkout and we just don't show the error, or if it could be related to how quickly I renewed. I was unable to reproduce it when trying to renew the same domain a second time in either Checkout.

**Comment by sirbrillig** [comment]
Refactored a bit and rebased to fix conflicts. This should be tested again for safety.

**Comment by klimeryk** [comment]
The "Invalid domain mapping product in cart" issue should not be new - I can't remember the details right now, but I definitely remember seeing it with the old checkout. It's of course possible there's something in the new checkout that makes the issue worse, but probably not.

Did some basic testing and all looked good.

**Comment by sirbrillig** [comment]
One of the e2e tests that's failing seems unrelated, but the other one _could_ be an issue. I can't figure out a way to re-run the tests so I'm just rebasing again. ⏳

**Comment by nbloomf** [comment]
I'm testing #44119 after it was rebased on top of this, and I am seeing a calypso error notification in checkout:

"Cannot destructure property 'includeDomainDetails' of 'undefined' as it is undefined."

This is in a checkout where my cart has a plan only. I'm still investigating whether this PR is related.

**Comment by sirbrillig** [comment]
Yeah, I added an options object for each payment processor function so that each can decide if they need to send domain details or not. Sorry about that, @nbloomf. I left some comments on that PR to fix it.

**Pull request merged**
