### PR TITLE
chore: Update isolated-block-editor to use npm

### PR DESCRIPTION
**Pull request by scinos**
#### Background

Since the Yarn v3 update, Docker images have been failing (specifically, the image used as cache for other images). The error is

```
10:55:37   #11 4.480 ➤ YN0000: ┌ Fetch step
10:56:22   #11 49.85 ➤ YN0018: │ isolated-block-editor@https://github.com/Automattic/isolated-block-editor.git#commit=5682ddeb940bfac9c3923491263aaf4ce44aaf0e: The remote archive doesn't match the expected checksum
10:56:33   #11 60.25 ➤ YN0000: └ Completed in 55s 773ms
```

My theory is that when TeamCity tries to download the package from github, it gets an HTTP error (maybe rate limit?), and the checksum of that answer doesn’t match the checksum recorded in `yarn.lock`.

#### Changes proposed in this Pull Request

Changes how we consume `isolated-block-editor` from a GitHub url to an NPM package.

The new version (1.0.2) is like the old 1.0.0 + adding the `@automattic/` prefix (https://github.com/Automattic/isolated-block-editor/compare/1.0.0...v1.0.2).

---

It's worth mentioning that running `yarn build` in `isolated-block-editor` produces transpiled code that doesn't work on IE11. That's what I released as `@automattic/isolated-block-editor@1.0.1`, and therefore it can't be used in Calypso right now.

Interestingly, there is transpiled code commited to the repo (directories `build` and `build-module`), and that code is compatible with IE11. In `@automattic/isolated-block-editor@1.0.2` I published that code (i.e. publish the transpiled code from the repo, without running `yarn build` first)

### CODE REVIEW

**Comment by jsnajdr** [comment]
When looking at the failing e2e tests, I see something is wrong with the fallback build:
```
#15 287.5 [fallback ] /calypso/public/fallback/55005.53996ac2c998f689ff9f.min.js
11:23:58   #15 287.5 [fallback ]   2:549471  error  Parsing error: The keyword 'const' is reserved
```

**Comment by scinos** [comment]
> When looking at the failing e2e tests, I see something is wrong with the fallback build:

Yep :( I did `yarn build` before publishing 1.0.1, and turns out that produces transpiled code incompatible with IE11.

Interestingly, there is transpiled code committed to the repo (https://github.com/Automattic/isolated-block-editor/tree/1.0.x, `build-module` and `build` dirs), and it seems to work on IE11. I don't think it was supposed to be in the repo, but I guess that's what the old git url was pulling in anyway 🤷🏼

**Review by fullofcaffeine — APPROVED** [review]
This builds fine, and I didn't find any breakages by smoke testing Calypso :)

Not a blocker for merging, but the state of the `isolated-block-editor` in Calypso is strange. Is it even used?

It seems that the actual repo _is_ in active development, and that would explain why support for IE11 has been dropped and the old version in Calypso still has it, but why hasn't it been updated? Maybe we should then completely remove it from Calypso? @johngodley @mirka Do you happen to know anything about this? Thanks!

**Review by noahtallen — APPROVED** [review]
Nice, I needed to implement this change for react 17 + wp components as well.

**Pull request merged**
