### PR TITLE
Revert "Theme Showcase: Do away with "Show all themes" button, add tabs, take 2"

### PR DESCRIPTION
**Pull request by sixhours**
Reverts Automattic/wp-calypso#54361 in case something goes wrong. 🙃

### CODE REVIEW

**Comment by worldomonation** [comment]
Hi @sixhours I see that you've reverted the merge. 

We have a task, Playwright E2E, that isn't scheduled to run on branches by default (for load reasons) and I see that this failed when you merged.

I am running the migration project and could help to fix the test. I have dealt with this situation yet so far; should I push to this branch with the fixed tests, or do we create a stack of PRs here to be merged together?

**Comment by worldomonation** [comment]
I've triggered the Playwright E2E test from TeamCity to get a sense of where we are at here.

**Comment by worldomonation** [comment]
The revert passes Playwright E2E tests. PR is approved, but I will still need to work with @sixhours to update the failing spec(s) `wp-themes__` to work with the new Themes page.

**Review by worldomonation — APPROVED** [review]

**Comment by sixhours** [comment]
@worldomonation Hiya! This one did not get reverted, but the first one did in #54359. This PR is just a precaution in case something goes wrong with the Showcase post-launch. Sorry, I should have made that more clear!

**Comment by worldomonation** [comment]
> @worldomonation Hiya! This one did not get reverted, but the first one did in #54359. This PR is just a precaution in case something goes wrong with the Showcase post-launch. Sorry, I should have made that more clear!

Ah, gotcha! Looks like the original change at #54359 does break the Playwright tests related to Themes. I can fix that if you'd like.

**Comment by sixhours** [comment]
> Ah, gotcha! Looks like the original change at #54359 does break the Playwright tests related to Themes. I can fix that if you'd like.

That would be amazing. I thought I regenerated them following instructions in the FG, but it was my first time working with Playwright so I probably didn't quite get it. 😅

**Comment by worldomonation** [comment]
> > Ah, gotcha! Looks like the original change at #54359 does break the Playwright tests related to Themes. I can fix that if you'd like.
> 
> That would be amazing. I thought I regenerated them following instructions in the FG, but it was my first time working with Playwright so I probably didn't quite get it. 😅

I've put up a PR to update how the page object interacts with the Themes page. Currently waiting for the tests to run on TeamCity to verify my changes are good :)

**Pull request closed without merging**
