### PR TITLE
Composite-checkout: Remove "...UI" pattern for styled components

### PR DESCRIPTION
**Pull request by sirbrillig**
#### Changes proposed in this Pull Request

Previously we had been using the "...UI" suffix on React components which were styled using the CSS-in-JS emotion package, particularly when those components' names would clash with the unstyled versions. However, this was never documented and is unclear and inconsistently applied. Moreover, those components were never meant to be part of a public API.

In this PR, we rename all such components to remove that suffix. Mostly this is inside the `@automattic/composite-checkout` package, but also in calypso and in the `editing-toolkit` app (see https://github.com/Automattic/wp-calypso/pull/44821).

Fixes https://github.com/Automattic/wp-calypso/issues/45680

#### Testing instructions

There are three things that will need testing: the composite-checkout package, checkout in calypso, and whatever the editing-toolkit uses these components for.

1. The `@automattic/composite-checkout` package.
- Run `yarn run composite-checkout-demo`.
- Open the demo page and complete the checkout form.
- Verify that there are no errors and that everything looks decent.

2. Calypso checkout.
- Start calypso or use calypso.live.
- Visit checkout with a product in the cart.
- Complete the checkout process.
- Verify that there are no errors and that everything looks decent.

3. Site setup flow in `editing-toolkit` plugin
- Apply D50672-code to your sandbox.
- Create a site starting from [wordpress.com/new](https://www.wordpress.com/new).
- Sandbox the site.
- Click _Complete Setup_ in editor,
- When reaching the the last step in the sidebar (_Launch your site_), the design should match screenshots in https://github.com/Automattic/wp-calypso/pull/44821 description.

### CODE REVIEW

**Comment by sirbrillig** [comment]
@razvanpapadopol I'm not sure how to test the editing-toolkit changes. I'll read up on the info linked in the comment that was automatically added above (very cool, by the way), but if you or someone else who's worked on this code before would be able to provide some specific testing instructions it would be super helpful!

**Comment by razvanpapadopol** [comment]
Thanks for pinging me @sirbrillig! I've updated the description with testing instructions for the usage within Editing Toolkit.

**Review by fditrapani — APPROVED** [review]
I did a walk through of our checkout in calypso.live and it everything appeared to work as expected. Thanks for cleaning this up!

**Review by michaeldcain — APPROVED** [review]
Just wanted to add that I tested the changes to the editor toolkit, and everything looks and works as expected.

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/5054971

Hi @sirbrillig, could you please edit the description of this PR and add a screenshot for our translators? Ideally it'd include this string: `Annual discount`

Thank you in advance!

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/5054971).

**Pull request merged**
