### PR TITLE
Gutenboarding: Update template for Reynolds FSE design

### LINKED ISSUE #44669: FSE: incorrect preview for Reynolds layout in onboarding
#### Steps to reproduce

1. Start the Horizon FSE flow
2. Check out the look of Reynolds layout on "Choose Design" step
3. Notice the big gap before the cover block text starts that's not present on the front end.

Screenshot 2020-07-23 at 16 59 22

This was working fine when we launched the flow but was changed in the meantime. I first noticed it during last week.

### PR DESCRIPTION
**Pull request by jeyip**
The original Reynolds design shared the same template name as the Reynolds FSE design. This led to references to the same starter site and identical thumbnail previews, even though the FSE and non-FSE design had distinct differences.

Requires D48345-code

#### Changes proposed in this Pull Request

* The Reynolds (FSE) design was previously referencing a starter site that was using the `Rockfield` theme. 
* The Reynolds (FSE) design should now point to `https://reynoldsfullsiteeditingstarter.wordpress.com`, which is a site editor enabled site implementing the `seedlet-blocks` theme.

#### Known Issues (aka Help Request 🙂 )
* Changing fonts in the live preview doesn't work. I haven't investigated it yet, * but maybe there's a very simple reason.

#### Testing instructions

* Apply D48345-code and sandbox the API.
* Run Calypso and open `http://calypso.localhost:3000/new?flags=gutenboarding/site-editor`.
* Ensure that creating a site editor site with the Reynolds (FSE) design still works as expected

Fixes #44669

### CODE REVIEW

**Comment by Copons** [comment]
+1 for generating the thumbnail in production.

---

I've tested this and it works as expected — which is exactly like #44972.

There was just one thing missing that I updated myself: the `block-patterns-source-site` blog sticker on the starter site.
This sticker preps the site for being returned by the template demo endpoint, removing a bunch of stuff that aren't supposed to be there.
In this specific case, I realized the sticker was missing because of this marketing bar showing up in the preview. 😄 

Screenshot 2020-08-20 at 18 46 50

**Comment by noahtallen** [comment]
Do we need to do the same thing for the Vesta-fse design, since it wasn't set up to use the starter site approach either?

**Comment by jeyip** [comment]
> Do we need to do the same thing for the Vesta-fse design, since it wasn't set up to use the starter site approach either?

I definitely think we need to. I was planning to make an issue to create a starter site for Vesta, as well as all of the other visual bugs you've pointed out. I wanted to scope the changes **strictly** to Reynolds in this PR because:

1. I see Editing Entity UX as a higher priority. I wanted to refocus on https://github.com/WordPress/gutenberg/pull/24557/files and return to sorting out Vesta when/if there's another lull in the Editing Entity UX project.
2. The Vesta preview isn't accurate, but it isn't broken like Reynolds was.

**Comment by noahtallen** [comment]
Fine by me!

**Pull request merged**
