### PR TITLE
DIFM content form: dialog updates & feedback char limit

### PR DESCRIPTION
**Pull request by aneeshd16**
Fixes https://github.com/Automattic/martech/issues/3432

## Proposed Changes

* Updates copy for the "content submissions guidelines" dialog and the "confirm submission" dialog.
* Adds a character limit for the Feedback text box.

## Why are these changes being made?

* pdh1Xd-2Ue-p2

## Testing Instructions

* Go to `/start/do-it-for-me` and purchase the product.
* After checkout, once on the content submission form, confirm that you see this dialog and confirm that the copy matches the one on https://wordpress.com/support/website-design-service/#content-guidelines
  image
* Go to the "Submit Content" section and confirm that the text box has a character limit of 1000 characters and does not accept any input after 100 characters.
  Screenshot 2024-10-22 at 4 24 35 PM
* Click on the "Submit" button and confirm that the dialog copy is the same as the following:
 Screenshot 2024-10-22 at 4 24 39 PM

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Comment by aneeshd16** [comment]
Hi @dcoleonline, can you please help in testing this PR? To test this PR, go this comment - https://github.com/Automattic/wp-calypso/pull/95600#issuecomment-2430502120 and click on the "direct link" link next to Calypso Live. Then, you can follow the testing instructions.

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/16945587

Some locales (Hebrew, Japanese) have been temporarily machine-translated due to translator availability. All other translations are usually ready within a few days. Untranslated and machine-translated strings will be sent for translation next Monday and are expected to be completed by the following Friday.

Thank you @aneeshd16 for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/16945587).

**Comment by aneeshd16** [comment]
This change has been tested: pdh1Xd-2Ue-p2#comment-2911

**Pull request merged**
