### PR TITLE
Loads Jetpack Scan credentials status into settings page

### PR DESCRIPTION
**Pull request by ChaosExAnima**
#### Changes proposed in this Pull Request

* Fixes a bug where the credentials showed as not set for sites with only Jetpack Scan.

#### Testing instructions

* Create a connected JP site with Scan _only_ purchased.
* Visit Cloud > Site Settings.
* Verify credentials are not set.
* Enter valid credentials and click "Save Credentials".
* Verify that credentials are saved and UI is in state as below:

Screen Shot 2020-10-15 at 12 10 27 PM

Fixes 1164141197617539-as-1198190187182841.

### CODE REVIEW

**Review by cbauerman — APPROVED** [review]
Looks great, LGTM!

**Review by rcanepa — APPROVED** [review]
LGTM. It definitely fixes the bug.

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/5005464

Thank you @ChaosExAnima for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/5005464).

**Pull request merged**
