### PR TITLE
Posts: Remove lib/post-metadata

### PR DESCRIPTION
**Pull request by tyxla**
#### Changes proposed in this Pull Request

Many of the functions in `/lib/post-metadata` are unused. The rest are just used once, and are very simple: they retrieve a meta value by a key that matches certain conditions. Once we remove the unused, we can move the remaining ones to the respective components without repetition, and that would allow us to avoid unnecessarily sharing code between the consumer components.

#### Testing instructions

* Go to `/devdocs/blocks/post-share` and verify it still works as it did before.
* Go to `/posts/:site`
  * Click on the dots of a post, click "Share" and verify the `PostShare` component there still works like before.
  * Click on the dots of a post, click "View", select the "Search and Social" option from the dropdown, and go through all previews (Google search, Facebook, Twitter) and verify they still work like before.

### CODE REVIEW

**Review by sarayourfriend — APPROVED** [review]
Tests fine to me. I'll say that the post share demo in the devdocs is pretty weak though, not much value in testing it compared to testing it on a live site?

**Comment by tyxla** [comment]
> I'll say that the post share demo in the devdocs is pretty weak though, not much value in testing it compared to testing it on a live site?

Agreed. That is why I added the live site testing as well, just in case. Some of those component examples could definitely use some love, especially those that are more interactive.

**Comment by jsnajdr** [comment]
I don't know, the `post-metadata` lib seems justified to me. It works with the messy `post.metadata` structure and abstracts the details (like weird field names) away.

**Comment by tyxla** [comment]
I understand where you're coming from, but to be honest, much of the WP database schema and even many of the WP REST API endpoints can be perceived as messy, depending on where and how we're consuming from them, but we often don't add a bunch of extra abstractions on top. I tend to think that sometimes fewer abstractions are better, especially when there are so few use cases. If anything changes in the future and we end up having more use cases, we could reconsider.

**Pull request merged**
