### PR TITLE
A4A: update referral dashboard cards view and data

### PR DESCRIPTION
**Pull request by andrii-lysenko**
Resolves https://github.com/Automattic/automattic-for-agencies-dev/issues/1578

## Proposed Changes

This PR wraps up UI part of [Referral Dashboard revised commission expected area](https://github.com/Automattic/automattic-for-agencies-dev/issues/900). Descriptions and tooltips were updated.
Payout calculations are based on pfunGA-3Wy-p2#comment-7052
Designs: fuufP6VNfZXYmvLsTRWRlG-fi-8332_118153

https://github.com/user-attachments/assets/33dd282d-64f4-46a0-84bd-74c34c8093f3

## Testing Instructions

- Using live link below, navigate to /referrals/dashboard and check looks according to the designs.
- Check that the data looks good and links in tooltip works

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
    - [ ] For UI changes, have we tested the change in various languages (for example, ES, PT, FR, or DE)? The length of text and words vary significantly between languages. 
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Comment by tiagonoronha** [comment]
@andrii-lysenko I see this on the responsive view:

Screenshot 2024-12-19 at 17 13 47

**Comment by tiagonoronha** [comment]
Also, compared to the designs, there should be some spacing between the tooltip text and the "Learn more" link, margin around the card, and the border radius on the card should be larger.

**Live link:**

Screenshot 2024-12-19 at 17 18 41


**Design:**

Screenshot 2024-12-19 at 17 16 54

**Comment by andrii-lysenko** [comment]
@tiagonoronha Thanks for the comments.
> Also, compared to the designs, there should be some spacing between the tooltip text and the "Learn more" link, margin around the card, and the border radius on the card should be larger.

Yes, I noticed that, but also that there's no gap in desktop version. I would keep these consistent, but it seems better with the gap though so I'll update for both.

**Comment by andrii-lysenko** [comment]
>I see this on the responsive view:

Good catch, pushed some changes. Seems a bit better now.

**Review by tiagonoronha — APPROVED** [review]
LGTM 👍

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/17071040

Some locales (Hebrew, Japanese) have been temporarily machine-translated due to translator availability. All other translations are usually ready within a few days. Untranslated and machine-translated strings will be sent for translation next Monday and are expected to be completed by the following Friday.

Hi @andrii-lysenko, could you please edit the description of this PR and add a screenshot for our translators? Ideally it'd include all of the following strings:
- `The exact amount your agency has been paid out for referrals.{{br/}}{{br/}}{{a}}Learn more{{/a}} ↗`
- `Next estimated payout amount`

Thank you in advance!

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/17071040).

**Pull request merged**
