### PR TITLE
Only show and save shipping label settings for plan owner

### PR DESCRIPTION
**Pull request by dechov**
Fixes https://github.com/Automattic/wp-calypso/issues/16958

If user is not the plan owner, it doesn't save label settings and displays a notice:

screen shot 2017-08-18 at 10 48 26 am

To test, navigate to shipping settings logged in as a second user added to the site.

### CODE REVIEW

**Comment by dechov** [comment]
You did mention the modified endpoint to me but I overlooked it anyway 😑. It now uses the information returned from that request:



I figured "Jetpack user" is an under-the-hood term here, but is there a more apt term than "plan owner" in this context?

**Comment by kellychoffman** [comment]
If you can't perform any actions, we should hide the Shipping label section all together. Only show it to site/plan owners.

**Comment by kellychoffman** [comment]
I think its more confusing to have a notice. Let's just hide it all together.

**Comment by dechov** [comment]
A consequence I just noticed is that by the time `formMeta.can_manage_payments` is loaded, it's too late to control whether the placeholder `LabelSettings` appears, so currently the placeholder appears and then just disappears when the data is loaded. `getSelectedSite( state ).plan.user_is_owner` is available and looks to me like it works fine as an alternative — I'm going off just 2 data points and can't be sure, but @marcinbot said it will work.

@marcinbot What do you think?
cc @jeffstieler re: discussion of who should be allowed to manage label settings

**Pull request merged**
