### PR TITLE
Store Dashboard: Update controls in inventory widget

### PR DESCRIPTION
**Pull request by ryelle**
This PR follows up on the remaining issues in #23410:

- Add click handlers to the +/- around the range element
- Add a cancel button into the popover

screen shot 2018-03-21 at 11 05 43 am

The click elements are intentionally "hidden" from keyboard & screen readers, they can change the values using the text input or moving the range slider with the keyboard, adding the buttons for these users is just another thing to tab through.

**To test**

- View the dashboard: `/store/:site`
- Open the widget control panel by clicking the gear
- Click the +/- next to the range slider
- Watch the values change
- Check that they save
- Open the control panel again
- Make some changes
- Click "Cancel"
- Make sure the changes did not save

### CODE REVIEW

**Comment by ryelle** [comment]
> One very minor style thing for the controls in general - if you use the max range, the input box is not quite big enough

I've changed the max input on the slider to 99, so this shouldn't happen unless the user manually types a larger number

**Comment by jameskoster** [comment]
Perhaps I missed this somewhere, but why do we need the out-of-stock threshold setting? Wouldn't that always be zero?

**Comment by ryelle** [comment]
> Perhaps I missed this somewhere, but why do we need the out-of-stock threshold setting? Wouldn't that always be zero?

It's a setting, not a set value, so it might not be zero - i added the field because it exists in wp-admin:

screen shot 2018-03-23 at 9 59 44 am

**Comment by timmyc** [comment]
> Perhaps I missed this somewhere, but why do we need the out-of-stock threshold setting? Wouldn't that always be zero?

Ha I've wondered the same thing myself. I could see some use case for it where perhaps a store also has a physical location and they want to always have a "block" of stock on hand - akin to how hotels expose only chunks of rooms to online orders.

**Pull request merged**
