### PR TITLE
Woo Onboarding: Add email verification functionality

### LINKED ISSUE #64163: Woo Email Confirmation - Trigger email resend on button click
When the user clicks "Resend verification email" on the [new email confirmation screen](https://github.com/Automattic/wp-calypso/issues/64162), we should trigger a re-send of the verification email to their account email address.

### PR DESCRIPTION
**Pull request by sixhours**
#### Proposed Changes

* Clicking on the "Resend email verification" button should send a verification email.
* If the email has already been verified or if there's another failure, an error message should be displayed.
* The button text should change to provide user feedback.

**Visuals**

https://user-images.githubusercontent.com/2124984/172865663-24e96d9d-70b4-46d9-9413-292a96808bcf.mov

Screen Shot 2022-06-09 at 10 15 48 AM

#### Testing Instructions

* Switch to this PR, navigate to `/setup/wooVerifyEmail?siteSlug=[your site slug]&flags=signup/woo-verify-email`
* Test both with an account that has not yet been verified and one that has.
* If the email needs verification, the button should display "Sending..." then "Request sent!"
* If the email can't be verified, an error message should be shown.

Fixes #64163 #64461

### CODE REVIEW

**Comment by sixhours** [comment]
We may want to break the `sendVerification` function out into a shared hook since we'll need it elsewhere in both Stepper and possibly Calypso.

**Review by markbiek — APPROVED** [review]
Worked as expected. LGTM!

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/7375732

Thank you @sixhours for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/7375732).

**Pull request merged**
