### PR TITLE
Import test/e2e into the monorepo

### PR DESCRIPTION
**Pull request by scinos**
#### Changes proposed in this Pull Request

* Drop `test/e2e` package-lock.json, it will be part of root's `yarn.lock` now
* Import `test/e2e` as a subpackage in the monorepo

#### Testing instructions

1) Checkout the branch. Go to `test/e2e` and run `yarn` to install deps -> it should install all deps even without doing `yarn` in the root first.
2) Run the tests after installing deps. Go to `test/e2e` and run `./run.sh -g -x`. Verify that the tests start and work.

#### Performance

It is worth mentioning this will make installation times slower.

|  | Master  | This PR   | This PR + dedupe |
|---|---|---|---|
| Install deps in root | 1:03.88 | 1:47.50 | 1:35.17 |
| Installing deps in test/e2e with root deps already installed | 9.359 | 1.984 | 1.890 |
| Installing deps in test/e2e without root deps | 9.477 | 1:12.96 | 1:02.45 |

Note that this change will introduce some duplication in `yarn.lock`. Future PRs will remove that duplication, making the installation times better (3rd column in the table above).

#### e2e tests

There are two repos that know how to build calypso e2e tests: `wp-e2e-tests-for-branches` and `wp-e2e-tests-canary` and create CI jobs associated with calypso PRs. Those CI jobs *will fail* once this lands in master.

To fix them, we need to change how those two repos build e2e tests. The PRs with the change are already up:
* https://github.com/Automattic/wp-e2e-tests-for-branches/pull/57
* https://github.com/Automattic/wp-e2e-tests-canary/pull/25

Once this change lands in master, I'll update the git submodule in those two branches to point back to calypso master, and merge them. That should restore e2e.

#### Bundle sizes
(edit)

Bundle sizes will change a bit here and there because some module paths are different now (eg: `../node_modules/lib` to `./node_modules/lib`). It should only be a few bytes.

### CODE REVIEW

**Comment by scinos** [comment]
Looks like this change will break https://github.com/Automattic/wp-e2e-tests-for-branches, https://github.com/Automattic/wp-e2e-tests-canary and https://github.com/Automattic/wp-e2e-canary-for-branches, because their CI config assumes `test/e2e` will be built using `npm` and will have a `package-lock.json`.

**Comment by bsessions85** [comment]
@scinos I pulled this down locally and when I clear out node_modules and run `yarn`, I am not getting all the packages that I need. I can't actually run the tests with what shows up in there. `yarn` completes successfully without errors so I am not sure what I could be doing wrong.

**Comment by scinos** [comment]
I'm investigating why every single chunk got a bit bigger.

**Comment by scinos** [comment]
This looks much better know. Could you check if it is still broken for you @bsessions85 please?

**Review by bsessions85 — APPROVED** [review]
Looks good! 🚀

**Pull request merged**
