### PR TITLE
Jetpack Search: mention request limitation for Complete plan

### PR DESCRIPTION
**Pull request by trakos**
#### Proposed Changes

Search included in new Jetpack Complete subscriptions is limited to 100k records and 100k requests per month.

This is mentioned in support docs on https://jetpack.com/support/search/jetpack-search-product-billing/,
but should also be mentioned in our Complete plan breakdown.
This PR adds those mentions.

It affects https://cloud.jetpack.com/pricing#jetpack_complete:

image

and https://wordpress.com/plans/<your-site-url>#jetpack_complete:

image

I couldn't find any uses of updated strings in `client/lib/plans/features-list.js` and `packages/calypso-products/src/plans-list.tsx`, but I've updated them just in case I've missed one or they'll be used in the future.

Similar changes on jetpack.com: D96281-code
Internal thread: panfyZ-1wq-p2

#### Testing Instructions

* Visit `/pricing#jetpack_complete` on cloud.jetpack.com
* Visit `/plans/<your-site-url>#jetpack_complete` on wordpress.com

#### Pre-merge Checklist

- [x] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [x] Have you checked for TypeScript, React or other console errors?
- [x] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [x] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [x] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/7685116

Thank you @trakos for including a screenshot in the description! This is really helpful for our translators.

**Review by robfelty — APPROVED** [review]
Tested using the live direct links for jetpack and wordpress. com. Looks good. Thanks for the update!

**Comment by trakos** [comment]
Thanks for the review!

I've marked this with https://github.com/Automattic/wp-calypso/labels/%5BStatus%5D%20String%20Freeze, so that we can wait for translations before merging.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/7685116).

**Comment by trakos** [comment]
The translations are finished, so I've rebased this and re-tested it to make sure that it still works as expected. I've confirmed on Slack p1673384007782189-slack-C02DQP0FP that the comments about modified packages should be safe to ignore in this case.

edit: now the check for ci/i18n started failing again for some reason, so I suppose I have to wait longer. Looks like he and ja aren't ready.

**Pull request merged**
