### PR TITLE
Plans: Disable longer plan term default in logged-in plans page

### PR DESCRIPTION
**Pull request by chriskmnds**
Related to https://github.com/Automattic/wp-calypso/pull/96816, https://github.com/Automattic/martech/issues/3403
Related to p1732646141389969-slack-CV2TX2PAN and p1732648406144139-slack-CV2TX2PAN

## Proposed Changes

This is a follow-up to https://github.com/Automattic/wp-calypso/pull/96816 where we disabled the term savings display for the logged-in plans page. That was only a part of the upcoming experiment. We disable the longer plan term default here as that's the main/core of the upcoming experiment, not the term savings display.

## Why are these changes being made?

The same reasoning with https://github.com/Automattic/wp-calypso/pull/96816

> Defaulting to longer term plans leads to a subpar UX experience in the logged in plans page. See this comment specifically p1732652464476219/1732648406.144139-slack-CV2TX2PAN.
> It would also interfere with the Hide Lower Tiers Experiment pbxNRc-4gN-p2

## Testing Instructions

- Assign a treatment variation from pbxNRc-4tx-p2
- Visit `/plans/:site` and ensure it doesn't default to a longer plan term, like 2-yearly or 3-yearly depending on variation

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
    - [ ] For UI changes, have we tested the change in various languages (for example, ES, PT, FR, or DE)? The length of text and words vary significantly between languages. 
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Comment by chriskmnds** [comment]
@jeyip I'm a bit confused how https://github.com/Automattic/wp-calypso/pull/96816 addressed not defaulting to the longer plan term when in logged-in pages. Wasn't that the intention? I am likely missing something from being away from this, but was it disabled without the changes in this PR? 🤔

**Comment by jeyip** [comment]
> @jeyip I'm a bit confused how https://github.com/Automattic/wp-calypso/pull/96816 addressed not defaulting to the longer plan term when in logged-in pages. Wasn't that the intention? I am likely missing something from being away from this, but was it disabled without the changes in this PR? 🤔

Ah yes this was on my radar of personal TODO's. Apologies for not communicating this more clearly in the PR or elsewhere. 

I spotted the code some time after I merged https://github.com/Automattic/wp-calypso/pull/96816 and was planning to do a quick clean up among other things ( happiness heads up, stakeholder heads up, issue creation for bugs and potential refactors etc. ) before deploying to production.

**Comment by jeyip** [comment]
Started updating https://github.com/Automattic/martech/issues/3403 with a more comprehensive list of remaining and optional tasks

**Comment by jeyip** [comment]
## Testing
### Requirements

For each of the flows listed below:
- Assign a treatment variation from pbxNRc-4tx-p2
- Visit /plans/:site and ensure it doesn't default to a longer plan term, like 2-yearly or 3-yearly depending on variation
- Smoke test /start to ensure existing functionality with and without term savings UI and longer plan term defaults

Flows:
- [ ] /start
- [ ] /plans

### Browsers
- [x] Chrome

**Review by jeyip — APPROVED** [review]
Tests well. On my way home from the coffee shop. Merging this when I arrive. Thanks again for drafting this Christos! 😄

**Pull request merged**
