### PR TITLE
Update description on the 'Writing' settings page

### PR DESCRIPTION
**Pull request by jordesign**
#### Changes proposed in this Pull Request

* Update text description on Settings > Writing page to be "Manage settings related to your site's content."

#### Testing instructions

Visit Settings > Writing and confirm string is updated

Related to #55429

Screenshot 2021-08-13 at 9 19 12 PM

### CODE REVIEW

**Review by deBhal — APPROVED** [review]
LGTM!

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/6418368

Thank you @jordesign for including a screenshot in the description! This is really helpful for our translators.

**Comment by arthur791004** [comment]
Oops...I think this one should wait for translation before merging. Currently, it doesn't have translation...

image

**Comment by jordesign** [comment]
Thanks for catching that @arthur791004 ! Something I need to be aware of for future PRs involving text strings. Going to check your PR to see how I can set the fallback in the future till translation is in place

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/6418368).

**Pull request merged**
