### PR TITLE
Photon: try and reduce bundle size

### PR DESCRIPTION
**Pull request by bluefuton**
#### Changes proposed in this Pull Request

Experimenting with imported packages in Photon. We use `photon` in Jetpack Search, and it adds around 20kb to our bundle.

#### Testing instructions

`cd packages/photon && node_modules/.bin/jest .`

### CODE REVIEW

**Comment by bluefuton** [comment]
https://github.com/GoogleChromeLabs/native-url looks promising, but requires a polyfill for IE < 11. This isn't a problem for Calypso, but might be for Jetpack Search or other users of Photon.

**Comment by kraftbj** [comment]
@bluefuton I was thinking about something like https://github.com/Automattic/wp-calypso/pull/37475/commits/c04c09c9ad94310005eb450bcd1a758b10a087d0

**Comment by bluefuton** [comment]
@kraftbj would you be able to point me towards the PHP equivalent code in Jetpack?

**Comment by kraftbj** [comment]
@bluefuton https://github.com/Automattic/jetpack/blob/7.9.1/functions.photon.php#L173

The lines under that are what we are phasing out, just didn't want to rip the bandaid off from the legacy method to avoid too much cache churn in one go. Since the photon.js code is used less often, I think it is fine to do this without that type of mitigation.

**Comment by lancewillett** [comment]
Cleaning up older pull requests as part of a GitHub scrub.

Is this change still valid? What's needed to move this along?

If not valid, please close with a comment. Thanks!

**Comment by bluefuton** [comment]
This was just experimental - happy to close this one out for now.

**Pull request closed without merging**
