### PR TITLE
Ignore visual studio code folder

### PR DESCRIPTION
**Pull request by brunoscopelliti**

### CODE REVIEW

**Comment by dmsnell** [comment]
@brunoscopelliti awesome PR. thanks for the contribution!

**Comment by dmsnell** [comment]
@brunoscopelliti I should have requested this in the current PR, but would you be interested in making sure that the VSCode config also gets ignored by all-the-things? (docker, linters, CIs, etc…)

It would make for a lovely second PR :smile:

**Comment by brunoscopelliti** [comment]
Sorry, I thought it was enough to add it to the .gitignore file.
I added it also to the .dockerignore, and .eslintignore files now... Did I forget something?

**Comment by dmsnell** [comment]
> I thought it was enough to add it to the .gitignore file.

When I responded I didn't mean to say that I knew it needed to be added elsewhere. I mainly wanted to make sure that we covered our bases; to actually figure out for sure where we need to ignore it. It is fine either way I think as long as it doesn't get sucked in to the Docker image etc…

**Comment by brunoscopelliti** [comment]
Ops, I was misled by this one
>It would make for a lovely second PR 😄

😄

**Pull request merged**
