### PR TITLE
Themes: Fix 'more' button links in IE11

### PR DESCRIPTION
**Pull request by seear**
Workaround for #5766

Use only absolute links in the the theme 'more' button.

**To Test**
* Go to /design
* in IE11, the 'details' and 'setup' links in the '...' button menu for a theme should work as intended
* All other links in the '...' menu should work as before, across all browsers

Test live: https://calypso.live/?branch=fix/themes-more-button-links-ie11

### CODE REVIEW

**Comment by ockham** [comment]
Can we use:

* `config( 'hostname' )` plus `config( 'port' )` (and some URL-building function -- MDN?) instead of `window.location.host`
* An `if` clause involving `! isOutsideCalypso()` instead of the RegEx? I'd find that more legible...

Stupid IE :-/

**Comment by seear** [comment]
> config( 'hostname' ) plus config( 'port' ) (and some URL-building function -- MDN?) instead of window.location.host

Yes, this would be better given server-side rendering concerns, but unfortunately messy, since `config()` [_throws an error_](https://github.com/Automattic/wp-calypso/blob/master/server/config/index.js#L21) if a key does not exist, which will be the case for `port` anywhere but dev. Probably simpler just to check if `window` is defined if we need to build this server-side.

> An if clause involving ! isOutsideCalypso() instead of the RegEx? I'd find that more legible...

I really think `string.replace()` is the right tool for the job here, because it handles the match, the logic, and the replace, all in a tried-and-tested fashion. Unfortunately regexs involving slashes always look like some hideous ascii art because of all the escapes. I've annotated it with a comment.

**Comment by ockham** [comment]
Tested this in BrowserStack with IE11 -- but still doesn't seem to work for me. Instead, it still complains about a `SecurityError` because of that double-slash (that the fix prepends before the hostname).

**Comment by ockham** [comment]
(I guess the workaround is to also explicitly prepend `window.location.protocol`)

**Comment by seear** [comment]
> Tested this in BrowserStack with IE11 -- but still doesn't seem to work for me

:o thanks @ockham. Sloppy testing from me. Latest commit uses [`window.location.origin`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLHyperlinkElementUtils/origin) and actually fixes the problem.

Leaving this gif for my own sanity:

ie

**Comment by ockham** [comment]
Okay, looks good. I can’t test it in BrowserStack since calypso.live didn’t pick up the latest commit (cc @Tug), but I can confirm that there are complete URLs :-)

Two requests:
* After merging and deploying, be sure to check if the Details/Setup links to the old showcase in production aren’t broken. (I tested with the `manage/themes/logged-out` flag disabled in development, but just to be sure.)
* Could you create a jsfiddle with a minimal example and use that to report the but to page.js?

**Comment by seear** [comment]
> Could you create a jsfiddle with a minimal example and use that to report the but to page.js?

Whilst doing this, I delved further and discovered that the problem only occurs after we add the onclick handlers to the helper list of A/B tests in the bottom left corner. This led me do discover that the update to React 15 in #5116 makes the problem go away.

Closing this PR in favor of #5116.

**Pull request closed without merging**
