### PR TITLE
Sites Management Page: Restrict Automagical sorting to A12s

### PR DESCRIPTION
**Pull request by zaguiini**
#### Proposed Changes

Let's disable automagical sorting to everyone except Automatticians until it's more mature.

#### Testing Instructions

1. Start Calypso locally and check that Automagical sorting is available;
2. Build Calypso production locally with the instructions defined in PCYsg-5YE-p2 and check that the sorting option is gone.

### CODE REVIEW

**Review by vykes-mac — COMMENTED** [review]
@danielbachhuber What are your thoughts here? I'm off the view that we wanted to release the immature version to capture users data that will be used to determine how this mature over time?

**Comment by danielbachhuber** [comment]
> What are your thoughts here? I'm off the view that we wanted to release the immature version to capture users data that will be used to determine how this mature over time?

@vykes-mac We do, but we're not yet capturing interaction data for non-a12ns. Once we do, we'll enable this for everyone: 909-gh-Automattic/dotcom-forge

**Review by danielbachhuber — APPROVED** [review]
Works as expected ✅

**Comment by wojtekn** [comment]
@zaguiini, when I tested one of the recent branches, I got a JS error related to an incorrect sorting value in the console. The steps that led to the issue looked as follows:

1. I used local Calypso to test the branch that added a new sorting option
2. Calypso saved the sorting value as preference server-side
3. I switched back to the trunk 
4. I've got a type error as sort key received from server didn't match to one from SitesTableSortKey

Could the change from this PR lead to a similar problem? Should we adjust it to account for that?

**Comment by danielbachhuber** [comment]
@wojtekn I ran into that error when testing, too.

We've actually renamed the preference, so I think the problem was related to switching branches while Calypso was loaded and running. The error went away after I restarted Calypso.

I'm not entirely confident on this, though, so I'd be curious to hear @zaguiini's thoughts too.

**Comment by zaguiini** [comment]
It won't affect the value itself as the processing didn't change. The only thing that changed was that we're not showing the option anymore, but all the mechanisms and treatments to the option are still there 🆗 

But the one thing that I did not address was reverting to another sort option if the user is not an A11n. That won't be problematic since the users will still get the automagic sorting, even though it won't show up in the dropdown. Might put up a PR that gives another value if the feature flag is off. Created a PR: https://github.com/Automattic/wp-calypso/pull/68047.

**Pull request merged**
