### PR TITLE
Video UI: add CTA according to Figma

### LINKED ISSUE #57506: Videos UI: Add final call-to-action upon course completion.
Add final call-to-action upon course completion.

Screen Shot 2021-11-01 at 10 15 38 AM

### PR DESCRIPTION
**Pull request by andres-blanco**
This PR adds a CTA to the Video UI according to the [Figma file](EuqfSnWpfYx8fgiBlVmbuA-fi-2266%3A17897).

| Desktop  | Mobile |
| ------------- | ------------- |
| image | image  |

#### Testing instructions

1. Apply this diff to sandbox if not merged: D70171-code
1. Sandbox API
1. Apply this PR
1. In **VideoFooterBar** component in `client/components/videos-ui/index.jsx`:
   * Set `displaySkipLink` to `false`.
   * Set `displayCTA` to `true`.
1. Verify you see the CTA UI display in the bottom of the screen.
2. Verify the track event `calypso_courses_cta_click` is being triggered when clicking the CTA button.

Closes #57506

### CODE REVIEW

**Comment by kwight** [comment]
Is this trying to render before the result of the API call gets back? It looks like I'm getting console errors before the `/courses` endpoint call is even made.

Screen Shot 2021-11-16 at 12 15 41 PM

**Comment by kwight** [comment]
Let's have a base button style (`videos-ui__play-button => videos-ui__button`) so we can share as much styling as possible between the two button types.

**Comment by blackjackkent** [comment]
I sort of feel as if the CTA should be its own component and then we dynamically choose whether to display the `VideoLinksBar` or call to action bar. Having two basically duplicate components in `VideoHeaderBar` and `VideoFooterBar` feels off to me. (And I'm doing some refactoring on the `VideoLinksBar` approach in https://github.com/Automattic/wp-calypso/pull/58146 )

**Comment by andres-blanco** [comment]
> I sort of feel as if the CTA should be its own component and then we dynamically choose whether to display the `VideoLinksBar` or call to action bar. Having two basically duplicate components in `VideoHeaderBar` and `VideoFooterBar` feels off to me. (And I'm doing some refactoring on the `VideoLinksBar` approach in #58146 )

slack thread: p1637169965453900-slack-C029SB8JT8S

**Comment by blackjackkent** [comment]
Looking again at this, it seems as if we've lost the logic that is supposed to prevent the footer from appearing on desktop sizes:

image

Is this intentional?

**Comment by andres-blanco** [comment]
> Looking again at this, it seems as if we've lost the logic that is supposed to prevent the footer from appearing on desktop sizes:
> 
> image
> 
> Is this intentional?

nope! nice catch, it should be fixed by now

**Review by blackjackkent — APPROVED** [review]

**Pull request merged**
