### PR TITLE
Externally redirect support and forums links

### PR DESCRIPTION
**Pull request by travisw**
### Changes proposed in this Pull Request

We recently changed the support site URL from `support.wordpress.com` to `wordpress.com/support`.

Because of that change there’s currently a bug that causes `/support` links not to load when linked from within Calypso. Calypso thinks it’s an internal URL and so tries to load it as such. The main issue is that when sending users support links through Happy Chat they don’t load.

We made the same change to the forums site (forums.wordpress.com --> wordpress.com/forums)
So this would also affect /forums links.

More info: https://wp.me/pau2Xa-fv#comment-3781

---------------------

### Testing instructions

An easy way to test various links is using Happy Chat (which is also how the issue was discovered).

To do that, sign in as an operator on the Happy Chat staging HUD, here:
https://hud-staging.happychat.io/?service=https://happychat-io-staging.go-vip.co/operator
Set yourself to receive "All Chats" (you won't get live chats from users when on staging).

Then, with this branch booted up locally, go to:
http://calypso.localhost:3000/help/contact

When you start a chat as a user, you should be able to accept the chat as a Happy Chat operator, allowing you to talk to yourself.

As the operator you want to send the user links to the support and forums sites (example links below).

As the user you want to click on those links and make sure they open in a new tab with the correct URL. And NOT simply replace the URL in Calypso but not take you anywhere new.

The support and forums pages won't actually load on `calypso.localhost:3000`, but you can replace `calypso.localhost:3000` with `wordpress.com` if you want to test the pages. It shouldn't be necessary though.

**Example**

As an operator:

Screen Shot 2020-03-25 at 4 23 24 PM

As a user:

Screen Shot 2020-03-25 at 4 23 43 PM

Make sure the URLs you test use `calypso.localhost:3000`, they need to match the site the user is on.

#### URLs to check

These **should** open a new window:

http://calypso.localhost:3000/support
http://calypso.localhost:3000/support/
http://calypso.localhost:3000/support/five-step-blog-setup/
http://calypso.localhost:3000/br/support
http://calypso.localhost:3000/br/support/
http://calypso.localhost:3000/br/support/five-step-blog-setup/
http://calypso.localhost:3000/pt-br/support
http://calypso.localhost:3000/pt-br/support/
http://calypso.localhost:3000/pt-br/support/five-step-blog-setup/

http://calypso.localhost:3000/forums
http://calypso.localhost:3000/forums/
http://calypso.localhost:3000/forums/topic/website-launch-6/
http://calypso.localhost:3000/br/forums
http://calypso.localhost:3000/br/forums/
http://calypso.localhost:3000/br/forums/topic/novo-blogue/

These **should not** open a new window:

http://calypso.localhost:3000/supportt
http://calypso.localhost:3000/brr/support
http://calypso.localhost:3000/pt-brr/support
http://calypso.localhost:3000/ptt-br/support
http://calypso.localhost:3000/es/notsupport

#### Other checks

Make sure other Calypso paths work as intended (do not refresh or open a new window).
Examples:
http://calypso.localhost:3000/me
http://calypso.localhost:3000/home/[SITE]
http://calypso.localhost:3000/posts/[SITE]
http://calypso.localhost:3000/marketing/tools/[SITE]
http://calypso.localhost:3000/domains/manage/[SITE]

Click around Calypso to check for other unexpected paths not loading properly.

Make sure there are no JS errors.

#### Questions:
* Do you see any issues with the regex?
* Can you think of anything else that should be tested?

### CODE REVIEW

**Comment by mattwondra** [comment]
@travisw Thanks so much for quickly looking into this!

My primary concern with this fix is, it only works for components that are using `isExternal` to determine whether the link should be passed through Calypso's in-app routing or not. So for Happy Chat it works great, but for links dropped in elsewhere in the app it doesn't.

Here's an example:
- Change the URL in [this line](https://github.com/Automattic/wp-calypso/blob/master/client/my-sites/site-settings/custom-content-types/index.jsx#L146) to `http://calypso.localhost:3000/support/testimonials/`
- Open http://calypso.localhost:3000/settings/writing and pick any site
- Go to the "Content Types" section and click the `testimonials` link.
- The bug is still happening, because there's some overarching link handler that's intercepting the click and `preventDefault()`ing it.

There _is_ a way to fix this on each instance — by adding `target="_blank"`. Arguably all these links _should_ have that anyways (and most that I found in the codebase do). But I worry about the poor developer who comes along and spends a half a day trying to debug why they just added a link to support docs and clicking it doesn't do anything. In my opinion, that higher-level fix should happen instead of this partial fix (though I welcome this to meet the immediate Happy Chat need if the wider fix will take a while).

This PR itself looks pretty safe. `isExternal` is used in these other files, and I haven't checked any of them other than Happy Chat, but on spot-checking the code this probably wouldn't hurt those usages:

```
 $ git grep -l isExternal.*lib/url
client/components/happychat/index.jsx
client/layout/sidebar/button.jsx
client/layout/sidebar/item.jsx
client/lib/checkout/index.js
client/me/happychat/main.jsx
client/my-sites/checkout/checkout-thank-you/index.jsx
client/my-sites/checkout/checkout/composite-checkout-thank-you.ts
client/my-sites/checkout/checkout/index.jsx
client/reader/list-stream/header.jsx
client/state/themes/actions/try-and-customize-theme.js
```

**Comment by travisw** [comment]
Thanks @mattwondra - I'll see if I can track down where we might be able to make a more high-level change to handle this.

**Review by mattwondra — COMMENTED** [review]
@travisw Nice, this definitely looks like the right layer of abstraction to be solving the problem. I can verify this solution works outside of Happy Chat. Everything seems to test out!

There's just one thing preventing me from giving this the :+1: — the browser URL in the Calypso tab is still being changed to the Support link. Here's an example:



It's something we should try to prevent if at all possible. It means that if the user bookmarks, refreshes, copies the URL — it will be to the support page instead of the page they're seeing. Probably would not affect anyone in most instances, but in the cases it did affect it wouldn't be great.

One option is not to open "_blank" and just `window.location.href = context.pathname;`. This solves that problem, and treats the link like a normal link. Developers can also decide whether to open it in a new tab or not (if the `<a>` itself has `target="blank"` it skips all this internal routing anyways). So while we'd expect every instance of these to be opened in a new tab, this is probabaly the route I would go.

**Comment by travisw** [comment]
oooh! good catch @mattwondra.
I'll clean that up.

**Review by mattwondra — APPROVED** [review]
@travisw I made the one-line change that opens these links in the same tab by default. I've run it through testing and seems good to go to me. Once you give it a quick look feel free to deploy. Thanks!

**Comment by mattwondra** [comment]
One more note:

I was considering if it makes more sense to put these regexes in a `lib` somewhere, since it's possible we'll want to use this check in other places as well (like for instance, Happy Chat _should_ open support links in a new tab, so I'll want to separately run the same regex checks for adding `target="_blank"`).

I found [lib/url/is-outside-calypso](https://github.com/Automattic/wp-calypso/blob/master/client/lib/url/is-outside-calypso.ts), which sounds like exactly where we'd want to add these checks. But it turns out that code is over 4 years old ([included in the initial Calypso commit](https://github.com/Automattic/wp-calypso/blame/3ceb3304a8c8be26c82744780779dc632314fdba/client/lib/url/index.js#L15)) and it's [only used in one place](https://github.com/Automattic/wp-calypso/search?q=isOutsideCalypso&unscoped_q=isOutsideCalypso): the [ThemeMoreButton](https://github.com/Automattic/wp-calypso/blob/master/client/components/theme/more-button.jsx#L75).

The existing `isOutsideCalypso` button returns true if the passed-in `url` starts with `//`, or if it starts with anything other than `/`. So `'https://wordpress.com/home/mattwondra.com'` returns true, even though this is _inside_ Calypso.

So extending the existing `isOutsideCalypso` function may not be the right move. It may be better to just move that function to be inline in the `ThemeMoreButton` component (again, the only component that's used this helper after 4 years) and repurpose the `isOutsideCalypso` function to determine whether a path or full URL passed-in is a Calypso URL or not.

In any case — @travisw if you're feeling adventurous and want to make that update please do. But maybe that could be in a followup PR, so we can ship this ASAP to help customers in Happy Chat get their link clicks back. If you don't make that change, I probably will next week so I can get those Happy Chat clicks opening in a new tab again.

**Comment by travisw** [comment]
Thanks for the fix @mattwondra!

Adding those checks to a separate lib sounds like a reasonable change to me.
I don't think I'll have time to get to that today, and would like to finish up another task before jumping back to this.

I'll go ahead and deploy this as is to fix the immediate problem and then circle back sometime next week. If you haven't already made the change I'll pick it up.

Thanks for the direction on this, I appreciate it.

**Pull request merged**
