### PR TITLE
Cart: Allow adding multiple products via URL

### PR DESCRIPTION
**Pull request by sirbrillig**
#### Changes proposed in this Pull Request

There is already a special URL scheme by which you can pre-populate the shopping cart for product renewals: `/checkout/:product/renew/:purchaseId/:domain`.

This change creates a URL scheme which also allows adding multiple products at once.

The only other change this makes is that previously it was not possible to add multiple renewal products to the cart at once; when each one was added, it replaced the one before it. From my research into the pre-oss version of Calypso, this was a hack intended to clear the cart when someone clicked a link to renew a product. Unfortunately, the hack makes the clearing implicit and per-product.

This PR makes it possible to add multiple renewal items via the `Checkout` component by adding them as a group using a new explicit action which replaces the contents of the cart before the adding takes place.

#### Testing instructions

This pattern may need to be changed, but for now try visiting a URL like this: 

`http://calypso.localhost:3000/checkout/value_bundle,domain_reg:example.com/renew/12345,543215/example.com`

Essentially this just changes the `:product` and `:purchaseId` parts of the URL so they can contain multiple comma-separated products. The only catch is that there must be the same number of each and they must match.

So in the example above, for the site `example.com` we're trying to renew a Premium Plan (slug `value_bundle`) with subscription ID `12345` and a .com registration (slug `domain_reg`) with subscription ID `543215`.

I'm open to suggestions for different patterns.

### CODE REVIEW

**Comment by DavidRothstein** [comment]
Overall looks really good. I'm a little unsure about the introduction of `replaceCartWithItems`, mostly because it involves changing the behavior of existing methods (like `addItems`) to **not** clear the cart on renewal.  Is there other code out there that adds items to the cart via a separate method (not via this URL) and that will be missing the cart-clearing behavior as a result?

I wonder if a safer (but uglier) way to do it would be to put some flag on the `cartItem` that says "don't clear the cart just because this is a renewal".  Something like `cartItem.isRenewalAddOn` (to indicate that we are deliberately adding the item to an existing renewal) and put that on the 2nd through Nth items that we are adding here... and then `cartItemShouldReplaceCart` could look for that and not replace the cart in that case?   Not sure how well it would work - just thinking out loud.  The advantage is that it preserves existing behavior except in the one case where we want to change it.

**Comment by sirbrillig** [comment]
Moved the cart clearing to #29565

**Comment by sirbrillig** [comment]
You have a good point. There could be other avenues for adding things to the cart which rely on the old behavior. I'm not sure I like it, but that might be a different issue we should address separately. The real issue here is that when adding multiple items to the cart, they all get added individually and aren't aware of each other; this means that when the add happens, it will check each one to prevent multiple renewal products when what this is really intended to do is to prevent separate additions of renewals to the cart. I'll see if I can adjust that behavior instead.

**Comment by sirbrillig** [comment]
I modified the logic such that the `Checkout` component will explicitly clear the cart before adding the items, and will add them with a new function that will avoid clearing the cart no matter what is added.

While this could in theory affect products which otherwise would have gone through this flow and would not have cleared the cart, I think the risk is quite low since the function which calls this flow is called `addRenewItemToCart()`, and the previous behavior was always to clear the cart if the product being added was a renewal.

**Comment by DavidRothstein** [comment]
I only reviewed the new logic briefly, but it looks reasonable to me.  I think the key thing is that it doesn't affect any other code which would have added products to the cart, which should make it safer than the previous version.

**Pull request merged**
