### PR TITLE
Reader: Fix Search recs card spacing inconsistencies

### PR DESCRIPTION
**Pull request by jancavan**
This fixes: https://github.com/Automattic/wp-calypso/issues/9783 and card spacing inconsistencies.

**Before:**
screenshot 2016-12-09 15 34 48

**After:**
screenshot 2016-12-09 15 35 03

### CODE REVIEW

**Comment by fraying** [comment]
👏

**Comment by fraying** [comment]
Looks good, @jancavan. Just one thing: In another issue, we added 20px to the bottoms of the cards, before the line, to give the page more breathing room. Add another 20px to the bottoms and we're good to go.

**Comment by jancavan** [comment]
@fraying Fixed in: https://github.com/Automattic/wp-calypso/pull/9955/commits/b9472101cc158d977958207a62dec085717238ee

screenshot 2016-12-09 16 08 48

**Comment by fraying** [comment]
Thanks, @jancavan! LGTM! 🚢

**Pull request merged**
