### PR TITLE
Importer: Focus on WordPress WXR Importer

### PR DESCRIPTION
**Pull request by dmsnell**
Importer flows for Ghost, Medium, and Squarespace have been in the plans
for the Calypso importer from its beginning. These three importers never
got the attention or resources they needed and they are too low of a
priority to do sufficiently well to provide a good user experience.

As a result, they are being removed for the first release and this
commit strips them out.

_Before_
screen shot 2016-02-19 at 10 08 19 am

_After_
screen shot 2016-02-19 at 10 06 55 am

I have stripped the code of any mention of the other importers to prevent it from rotting in the repository. If we should pick up the work again, it shouldn't take much effort to start up.

cc: @dllh @lancewillett

### CODE REVIEW

**Comment by dllh** [comment]
The code here seems reasonable. I don't have bandwidth right this minute to test, but if you can wait a bit or if somebody else can pitch in to give it a test-drive, it looks good to me from a purely code standpoint.

**Comment by lancewillett** [comment]
QA for UI checks out, the other importers are gone from the view.

screen shot 2016-02-19 at 10 39 08

Testing with Firefox 44.0.1 on OS X 10.11.3 on `remove/importer/ghost-medium-squarespace` branch, local Calypso install.

**Comment by lancewillett** [comment]
I noticed the "Other Importers" link was gone ^ — back now after a branch pull.

screen shot 2016-02-19 at 10 59 09

:+1:

**Comment by roundhill** [comment]
Nice, this looks a lot cleaner now.

**Comment by lancewillett** [comment]
"I ain't afraid of no Ghost."

"Can you find me a Medium?!"

**Pull request merged**
