### PR TITLE
Site Indicator: Remove border below action buttons

### PR DESCRIPTION
**Pull request by tyxla**
This PR removes the bottom border of site indicator action links, as it's unnecessary - see https://github.com/Automattic/wp-calypso/pull/16350#issuecomment-323813954 for details.

Warning - before: 

Warning - after

Error - before:

Error - after

To test:
* Checkout this branch, or get it going on calypso.live
* Test site indicator in the sidebar with a Jetpack site with updates and verify it looks as on the screenshot
* Test site indicator in the sidebar with a Jetpack site with connection issues and verify it looks as on the screenshot

### CODE REVIEW

**Comment by sirreal** [comment]
Thanks for handling this @tyxla 🙌 

Code is good, I've removed the "need review" label.

I do think the clickable part of these notices need something to make them jump out a little bit, but I'll let our design pros give their feedback 🙂

**Comment by folletto** [comment]
This is a hard one... even if it's a one-liner.

As it's visible from the screenshots above, it's actually important the underline to exist on links, as without it's impossible to tell if they are clickable.

However, the last one is probably using a `button`, so it got the rounded corners... yet, the CSS rule clumps together `a` and `buttons`

Can we try instead with a `border-radius: 0`?

**Comment by rickybanister** [comment]
I was going to say the same thing—I think these simply didn't have the radius before. @folletto 's suggestion should fix that.

**Comment by tyxla** [comment]
Thanks, that's even better!

Done in https://github.com/Automattic/wp-calypso/pull/17421/commits/a6a77285cf2894ed4ae3d266beb74a0b1cbed9d0 - here are updated previews:

Warning - after


Error - after


Let me know if that's good.

**Comment by tyxla** [comment]
Thanks!

doge

**Pull request merged**
