### PR TITLE
Signup: Handle :lang route param in middleware

### PR DESCRIPTION
**Pull request by ockham**
This is entirely particular to signup, so the relevant code should be contained in the signup section instead of spreading special cases over `server/pages` and `client/lib/i18n-utils`.
Which is what this commit does, by making the signup module isomorphic, and adding a server-side route handler and middleware to take care of the `:lang` param.

Will be needed for #5823.

No visual changes. To test:
* Verify that Calypso still works as before.
* Specifically, check that the signup flow, starting at http://calypso.localhost:3000/start/ (in an incognito window) still works
* Furthermore, check that the signup flow with a `lang` param still works.
 * That is, in an icognito window, start at http://calypso.localhost:3000/start/de and verify that every step is displayed in German (with the `/de` suffix param preserved at every step). _Be sure to also verify that in the page source, there's a `<script src="//widgets.wp.com/languages/calypso/de.js"></script>` tag._

Test live: https://calypso.live/?branch=update/signup-handle-lang-route-param-in-middleware

/cc @scruffian for review

### CODE REVIEW

**Comment by scruffian** [comment]
@ockham Have you thought about how i18n will work on other logged out routes?

**Comment by ockham** [comment]
> Have you thought about how i18n will work on other logged out routes?

@scruffian As for other current logged-out routes seen in `server/pages` (e.g. `/jetpack/connect` or `/accept-invite`), none are really using their `locale` param on the server side.

As for future logged-out routes wishing to use i18n (theme sheets are one example), I think we should put some framework-wide deliberation in (maybe worth a hangout?). Using the last route param is unfortunately kinda messy since it either requires all sections to have some sort of parsing logic like `/start` does now (but always tailored to the specific route shape, so not really scaling well), or to blindly rely on heuristically testing the last route param if it's a locale in an earlier middleware -- but that, too is error-prone. One obvious alternative would be a querystring.

**Comment by scruffian** [comment]
@ockham - this was a discussion that we went back and forth on in the early days of Calypso, and the solution we settled with at the time was to use the last slug in the URL. I can dig out the posts for you if you want. A year on, I think my preference would be to use the first route in the URL.

**Comment by ockham** [comment]
Still okay to treat that as a more general issue when more sections start to require it, and move on with this PR for now to contain the special case?

**Comment by scruffian** [comment]
Yes, I think that's a good idea.

I've tested and this LGTM 👍

**Pull request merged**
