### PR TITLE
Add 'goals' state variable into onboard data-store

### LINKED ISSUE #63913: [Data] Add 'goals' into onboard data store.
### Details

Add a new ‘goals’ key into the `ONBOARD_STORE`
- Add selector, reducer, and create the action to set the `goals`
- Resolve ‘intent’ state variable based on the stored `goals` 
(Requires defined logic which is to be applied - [Saygun Erkaraman] - decision matrix)
- Mind the `intent` is used in few other steps of the flow
- Ensure no regression in their behavior

### Checklist

- [ ]
- [ ]

### Related

_No response_

### PR DESCRIPTION
**Pull request by mashikag**
#### Changes proposed in this Pull Request

Add `goals` state variable into `onboard` data-store. This includes creating:
* `goals` reducer
* `getGoals` selector
* `setGoals` action

#### Testing instructions

No real testing instructions for this. 
It should not introduce any changes to the current UI.
It should not regress any current functionality. 

Related to https://github.com/Automattic/wp-calypso/issues/63913

### CODE REVIEW

**Comment by yansern** [comment]
@phcp @ivan-ottinger With just `SET_GOALS/setGoals()` (meaning no `ADD_GOAL/addGoal()` or `REMOVE_GOAL/removeGoal()`), this means the logic of manipulating the goals array is done on the component level. Just need you both to be aware as this differs from the draft data docs.

@mashikag considering the scenario where the user chooses some goals on the page, but gives up and clicks "Skip" to skip the intent step, I imagine what we will do is just dispatch the same `SET_GOALS`/`setGoals()` action, and pass in an empty array, e.g. `setGoals([]);`.

**Review by yansern — APPROVED** [review]
I tested with the Calypso Live link to ensure that `/setup` onboarding flow is still working without breakage. All is good.

**Review by ivan-ottinger — APPROVED** [review]
Looks good to me. 👍🏼

**Review by phcp — APPROVED** [review]
Looks good!

**Pull request merged**
