### PR TITLE
Hosting Configuration: Refresh transfer status on `componentDidMount`

### LINKED ISSUE #61974: [Bug]: Hosting Configuration "please wait" spinner is stuck forever after reverting
### Quick summary

The Hosting Configuration screen can be used to initiate AT. _If_ this is the method that's used to initiate AT _and_ the atomic site is reverted at a later date, then the Hosting Configuration screen gets stuck showing an incorrect message and a spinner that doesn't go away.

### Steps to reproduce

1. Start with a simple business site
2. `/hosting-config/{{ site slug }}`
3. Activate hosting features
4. After AT is complete, revert the site back to a simple site
5. Go back and look at `/hosting-config/{{ site slug }}`

### What you expected to happen

Should see the `Please activate the hosting access to begin using these features.` message, since we've reverted back to simple we'd need to AT again to access them.

Screenshot 2022-03-16 at 7 41 45 PM

### What actually happened

The `Please wait while we activate the hosting features.` message spins forever.

https://user-images.githubusercontent.com/1500769/158531366-28d3e269-2d40-44f9-8201-4418b9c3c9ce.mov

The site does not actually appear to be transferring back to atomic again.

### Context

_No response_

### Browser

_No response_

### Simple/Atomic

Atomic

### Other notes

I suspect there's a piece of state that's been stored in the Redux store that remembers we clicked the activate button but isn't being reset. When the Redux store is cleared by re-logging in (or by switching to another Redux store by testing on `calypso.localhost:3000`) the bug is fixed.

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Workaround details

Log out and log in again.
This clears the locale redux store, which is probably why Calypso thinks it's stuck in the state of activating the hosting features

### PR DESCRIPTION
**Pull request by danielbachhuber**
### Proposed Changes

Refreshes `AutomatedTransferStatus` when loading 'Hosting Configuration' page to avoid edge case behavior.

Fixes #61974

### Testing Instructions

1. Start with a Simple Pro site.
2. Navigate to `/hosting-config/{{ site slug }}`
3. Activate hosting features
4. After AT is complete, revert the site back to a simple site
5. Go back and look at `/hosting-config/{{ site slug }}`.
 * Without the pull request applied, the page will say 'Please wait while we activate the hosting features.'
 * With the pull request applied, the page will say 'Please activate the hosting access to begin using these features.'

### CODE REVIEW

**Review by p-jackson — CHANGES_REQUESTED** [review]
I'm reliably reproducing an issue where the banner immediately switches back to the "Please activate the hosting ..." message after I initiate a fresh transfer.

https://user-images.githubusercontent.com/1500769/173485027-1da3d056-7c0e-4218-a24a-b582cc1708a3.mov

Behind the scenes the transfer has started.

When we peer'd on this earlier were we testing using a site with a custom domain? I wonder if this is happening because of the intermediate warning screen about my domain changing. After I accept the warning message this component will get mounted again triggering a fetch of the status. Probably not needed at this point, but I don't see why it would hurt anything either.

**Comment by danielbachhuber** [comment]
> I'm reliably reproducing an issue where the banner immediately switches back to the "Please activate the hosting ..." message after I initiate a fresh transfer.

Nice catch!

What's happening here is a little bit of a race condition:

1. When the user clicks 'Activate', `transferState=start`. They're taken back to 'Hosting Configuration'.
2. When 'Hosting Configuration' is loaded, `transferState===start`, so we `fetchAutomatedTransferStatus`.

image

3. However, the AT job hasn't started, so `transferState===reverted`, which flips 'Hosting Configuration' back to its initial state:

image

4. As it turns out, `pollThemeTransferStatus` continues to run, so eventually, after the AT job is complete, the UI flips to the expected state:

image

Removing `this.props.transferState === START` out of the conditional (49ee940dd3b2ad5b64d52024aa0feace58d19f5a) restores the expected behavior at the beginning of the process.

However, the end of the process seemingly gets stuck. I would've expected this API response to cause the page to progress:

image

**Comment by danielbachhuber** [comment]
> However, the end of the process seemingly gets stuck. I would've expected this API response to cause the page to progress:

Hm, might've been a one-off. It works all of the way through now.

This pull request in its current form resolves the original issue.

**Comment by mreishus** [comment]
In my testing, the original issue is solved, and the new code does not cause extra requests in regular circumstances.

**Production, bugged state. Site is not actually transferring; it's reverted and simple**


**This branch, state is correctly updated.**

(refresh was caused by new code)

```diff
diff --git a/client/my-sites/hosting/main.js b/client/my-sites/hosting/main.js
index fe9534bf75..f8b4b0cd5d 100644
--- a/client/my-sites/hosting/main.js
+++ b/client/my-sites/hosting/main.js
@@ -55,9 +55,13 @@ class Hosting extends Component {
        componentDidMount() {
                const { COMPLETE } = transferStates;
                // Check if a reverted site still has the COMPLETE status
+               console.log('componentDidMount', this.props.transferState);
                if ( this.props.transferState === COMPLETE ) {
                        // Try to refresh the transfer state
                        this.props.fetchAutomatedTransferStatus( this.props.siteId );
+                       console.log(' --> refresh');
+               } else {
+                       console.log(' x skip');
                }
        }
```

**Comment by danielbachhuber** [comment]
@p-jackson Could you land this pull request once you've had a chance to review it?

**Review by p-jackson — APPROVED** [review]

**Pull request merged**
