### PR TITLE
Stats: Add a plan usage section on the Stats Traffic page

### PR DESCRIPTION
**Pull request by dognose24**
Related to #84485

## Proposed Changes

* Add the Stats plan usage section gated behind the feature flag `stats/plan-usage`.
* Use props `usage`, `limit`, `daysToReset` and `overLimitMonths` to determine the usage status and upgrade text.

## Testing Instructions

* Spin this change with the local Calypso.
* Navigate to **Stats** > **Traffic** page with the feature flag `?flags=stats/plan-usage`.
* Ensure the plan usage section aligns with the design by modifying those parameters.

### Past and current usage all under the limit
截圖 2023-11-28 下午11 21 37

### Usage of the last month exceeds the limit
截圖 2023-11-28 下午11 21 30

### The past two or more consecutive months of usage exceed the limit
截圖 2023-11-28 下午11 45 32

### Current month usage over the limit under any conditions
截圖 2023-11-28 下午11 21 14

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

**Review by kangzj — APPROVED** [review]
A great start! Good job! 👍 

------update--------
The E2E failure doesn't seem to be related.

**Review by kangzj — APPROVED** [review]
:shipit:

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/9789198

Some locales (Japanese) have been temporarily machine-translated due to translator availability. All other translations are usually ready within a few days. Untranslated and machine-translated strings will be sent for translation next Monday and are expected to be completed by the following Friday.

Thank you @dognose24 for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/9789198).

**Pull request merged**
