### PR TITLE
Reader: Fix combined cards styling

### PR DESCRIPTION
**Pull request by raoulwegat**
Fixes design issues in #11913.

After:

screen shot 2017-03-10 at 5 28 29 am

cc @fraying

### CODE REVIEW

**Comment by fraying** [comment]
Nice work, @raoulwegat. Almost there! The excerpt and the byline both need to move down by ~2px until the baseline of the byline aligns with the bottom of the image.

Current:
screen shot 2017-03-09 at 10 43 58 am

Should be:
screen shot 2017-03-09 at 10 43 41 am

**Comment by raoulwegat** [comment]
After adjustment:

screen shot 2017-03-10 at 6 01 39 am

**Comment by fraying** [comment]
@raoulwegat Perfection!

**Comment by samouri** [comment]
css LGTM

**Pull request merged**
