### PR TITLE
DevDocs: Fix broken links to CONTRIBUTING.md 

### PR DESCRIPTION
**Pull request by v3rse**
This aims to fix  issues with links to `CONTRIBUTING.md` within the DevDocs. 

Fixes issue #5037

### CODE REVIEW

**Comment by lancewillett** [comment]
Let's not move the file please — instead, let's fix the link reference.

**Comment by lancewillett** [comment]
Thanks for the changes, v3rse — I'm not sure the devdocs changes are needed, though. In my testing the sidebar and in-body links work as expected right now (they point to `https://wpcalypso.wordpress.com/devdocs/.github/CONTRIBUTING.md`).

Testing with https://wpcalypso.wordpress.com/devdocs?term=contributing

screen shot 2016-04-29 at 9 22 29 am

**Comment by lancewillett** [comment]
I can't seem to repeat any of the broken links now... maybe they were fixed already.

**Comment by v3rse** [comment]
True. Noticed. Thanks for the help though.

**Pull request closed without merging**
