### PR TITLE
New hosted site flow: remove site options step

### PR DESCRIPTION
**Pull request by zaguiini**
Related to p1696297881912539-slack-C04H4NY6STW.

## Proposed Changes

Removes the site options step from the `/setup/new-hosted-site` flow. It’s a distraction, something that can be configured later by the user after they finish their purchase.

This PR also changes the site creation code so that the username isn't sent as a fallback sub-domain for the new site.

This PR works in conjunction with D129390-code which sets the newly created site's sub-domain to something the user would have gotten by using the "Generate" button in the site options step. That way new sites still have a "nerdy" sub-domain, but without having to go through the extra step.

## Testing Instructions

Apply D129390-code

Use the test store and go through the `/setup/new-hosted-site` flow after applying this code. You should not be inquired for a site title and a preferred data center.

You can test other flows to ensure their behaviour for choosing sub-domains hasn't changed. Try these for example
- `/setup/link-in-bio`
- `/setup/hundred-year-plan`

### CODE REVIEW

**Review by mpkelly — APPROVED** [review]
Now the flow starts at `setup/new-hosted-site/plans`. LGTM.

**Review by vykes-mac — APPROVED** [review]
g2g

**Comment by p-jackson** [comment]
@Automattic/quake I'm putting this back out for another code review. I've made further changes so that the username isn't sent along with the `/sites/new` request in the hosting flow as a hint for what the sub-domain should be. We don't want to send any hint because the backend will select a sub-domain for us. D129390-code.

This also involved refactoring the `getNewSiteParams` function. It would have been nice to simply add our logic and be done with it, but I was about to add a ternary, to a boolean logic fallback, nested inside another ternary. And that was just too much for me. I added unit tests before making the refactor so help confirm I haven't broken anything 🤞

Please re-read the PR description.

**Comment by zaguiini** [comment]
Not working for me :( I see the creating site step, and then I'm immediately sent to the transferring to Atomic page.

**Comment by p-jackson** [comment]
Thanks for finding. This only happens sometimes so I'm glad you discovered it before we merged! This took a lot of trying to reproduce and then track down 😫

Sometimes the `/sites/new` endpoint returns this error.

```
{
    "code": 400,
    "headers": [
        {
            "name": "Content-Type",
            "value": "application\/json"
        }
    ],
    "body": {
        "error": "blog_name_exists",
        "message": "Sorry, that site already exists!"
    }
}
```

I haven't found the fix yet, but I suspect that even though we're passing the `find_available_url` flag, the endpoint is still returning an error if the randomly generated subdomain matches an existing one. That's not what I would have expected, usually it just appends a number if there's a collision.

Feels like we should expand the dictionary a lot if we're running into this not infrequently.

Looking at the necessary backend change now.

**Comment by p-jackson** [comment]
Found the issue. I misunderstood the flag that controls generating available subdomains.
D129509-code

**Comment by zaguiini** [comment]
Works great @p-jackson 🚀 🚢

**Pull request merged**
