### PR TITLE
Gutenberg 6.9.0 / CoBlocks 1.17.1: Placeholder PR for running E2E tests against Horizon

### PR DESCRIPTION
**Pull request by mmtr**
**DO NOT MERGE**

Placeholder PR for running E2E tests checking new Gutenberg and Coblocks versions against Horizon

### CODE REVIEW

**Comment by mmtr** [comment]
Interesting, a rebase automatically closes the PR when there are no commits to push 🤔

**Comment by mmtr** [comment]
There are some failing sign up E2E tests unrelated to the Gutenberg upgrade. I thought we were not running them on Horizon, but maybe that has changed due to p4TIVU-9k4-p2? cc @bsessions85

**Comment by bsessions85** [comment]
@mmtr It looks like we had some new tests added that aren't excluded on Horizon. I'll get those changed.

**Comment by bsessions85** [comment]
actually, those already have the excluded piece like the other tests, it is just failing because of a recent change. It is unrelated.

**Comment by kwight** [comment]
Re-running for CoBlocks 1.17.1-wpcom.

**Comment by kwight** [comment]
Wut. Force-pushing a rebase merged and closed this PR 🙃

**Pull request closed without merging**
