### PR TITLE
VideoPress User intent: some affordances for keyboard navigation

### PR DESCRIPTION
**Pull request by jgcaruso**
Related to # https://github.com/Automattic/greenhouse/issues/1836

## Proposed Changes

* add hover state on keyboard focus of Intent items
* allow `esc` key to be used to dismiss the modal
* add label to the modal Close button

This may not be exhaustive, but it makes it a little better when using keyboard navigation. Given the short lifespan of this screen it may not be entirely necessary? But I wanted it to be a little better if possible.

## Testing Instructions

* `yarn && yarn start`
* `/setup/videopress`
* use `tab` to move around the intent items, they should highlight (new)
* `enter` or `space` (existing functionality) should open the modal
* `esc` should close the modal (new)

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

**Review by thedebian — CHANGES_REQUESTED** [review]
It's working well, but the content of the modal is not accessible though (buttons and inputs), which defeats the purpose of this PR.
Maybe adding tabindex can do the trick without too much effort ?

**Comment by jgcaruso** [comment]
> It's working well, but the content of the modal is not accessible though (buttons and inputs), which defeats the purpose of this PR.
> Maybe adding tabindex can do the trick without too much effort ?

So, it is being very weird. Buttons and inputs do have focus for me (at least on the "Coming Soon" ones), but for some reason the `a href` links don't 🤷‍♂️ in Firefox, but its fine in Chrome. Safari doesn't seem to want to focus anything with the keyboard.  Adding `tabindex=0` doesn't seem to have any affect for the links in Firefox.

The very least I was trying to accomplish with this PR was if you did select one of the Intents with keyboard nav (it was working before, just didn't show you what was focused) then opened it with `space` or `enter` (also working before) you then wouldn't get stuck in there (which was happening if you tried it) which is why I added the `esc` handler. So at least that seems to be working everywhere.

**Comment by jgcaruso** [comment]
I feel like I knew this before, but completely forgot.

> Firefox works similarly, with the exception that on OS X a elements aren’t tab-accessible by default, with or without tabindex. You can access a elements with the keyboard in Firefox two ways. You can hold down the option key while pressing tab, or you can change your system preferences. Firefox respects an option called “Full Keyboard Access” in your keyboard preferences, which controls which types of controls can be accessed with tab on your computer. If you toggle that option to “All Controls”, Firefox will focus on links like nobody’s business.

https://www.alexlande.com/articles/cross-browser-tabindex-woes/

So I think for the purpose of this PR we can either just test in Chrome, or ensure that you enable that setting so that tab focus works as expected (the hold down `option` method didn't work for me, not sure why).

I've also fixed an issue where once the modal was open, the tab focus still made you cycle through the rest of the options before jumping into the modal. So it should feel a lot better now.

**Review by thedebian — APPROVED** [review]
Worked well in Chrome.
I noticed the flow after this page can't be navigated with the keyboard though 😅

**Pull request merged**
