### PR TITLE
Data Layer: Stop `next()`ing actions

### PR DESCRIPTION
**Pull request by dmsnell**
In #14354 we introduced a transitional `next()` function into the data
layer API which would only ever call the real `next()` once for each
action. This patch removes manual use of `next()` and replaces those
cases where we legitimataly need to pass an action along and bypass the
data layer with a call to `dispatch()` using `local()`

`local()` is the wrapper which adds meta data to an action to cause it
to bypass the data layer.

This should not cause any change in behavior. For those few handlers
calling `next()` to pass along the action there should be no change. For
those calling `next()` to skip the data layer the behavior should be
equivalent with `dispatch( local( ... ) )`

**Testing**
As this is a big PR please test the parts which you were a part of writing
and leave some comment here. This will make it much easier to test. We
can test with the live branch.

### CODE REVIEW

**Comment by seear** [comment]
tested:
```
client/state/data-layer/wpcom/activity-log/*
client/state/data-layer/wpcom/sites/activity/*
client/state/data-layer/wpcom/theme-filters/*
```

All fine 👍

**Comment by samouri** [comment]
I vote we rename `local` to `skipDataLayer` :)

cc @blowery

**Comment by dmsnell** [comment]
> I vote we rename local to skipDataLayer :)

can do, later :smile:

**Comment by gwwar** [comment]
> I vote we rename local to skipDataLayer :)

Hah sounds familiar https://github.com/Automattic/wp-calypso/pull/14025#issuecomment-302463210

@dmsnell I think you may have missed updating a few tests. 

@alisterscott or @hoverduck if we could get e2e tests run on this branch it's be much appreciated ❤️ .

**Comment by samouri** [comment]
Reader functionality LGTM.

**Comment by hoverduck** [comment]
e2e tests clean and green 💚

**Comment by donnapep** [comment]
Video poster functionality is also working fine. Cheers!

**Pull request merged**
