### PR TITLE
o2-blocks: Update project status block

### PR DESCRIPTION
**Pull request by dmsnell**
**Do not merge until rebased against `master` or until #44153 is merged**

Replaces #40841 
~Built upon #44153 but doesn't need to be~ (edited to only include block updates)

Updates the **Project Status** `o2-block` for a few small refinements:
 - rounds percentages to avoid rendering values like `5.33333333333%`
 - prevents divide-by-zero leading to `NaN%`
 - save a usable rendering of the status for a fallback render that still conveys information (vs. a void block that completely disappears)
 - report how many tasks are in-progress rather than how many are not completed. previously we showed (total tasks / # completed / # not completed) whereby the last two were two were redundant

#### Before, no tasks

Screen Shot 2020-07-15 at 12 14 31 PM

#### After, no tasks

Screen Shot 2020-07-15 at 12 15 17 PM

#### Before, tasks

Screen Shot 2020-07-15 at 12 14 05 PM

#### After, tasks

Screen Shot 2020-07-15 at 12 14 39 PM

### Before

The block is missing because it's a void element.

Screen Shot 2020-07-15 at 12 16 05 PM

### After

Although we lack styling we have a usable representation of the status at the last time of editing the post.

Screen Shot 2020-07-15 at 12 15 47 PM

---

This PR does not address the **Task** block as that will be addressed in a separate PR.

### CODE REVIEW

**Comment by dmsnell** [comment]
**Update on this PR:** I've retargeted it off of `master` so we can avoid the problems created by the introduction of the block playground. The code is identical to before though and I tested/confirmed on a local sandbox inside `wp-admin` using the built artifacts.

```bash
npx lerna run build --scope="@automattic/o2-blocks" -- --output-path=/path/to/where/sandbox/is/synced/
```

Thanks @mirka for prodding me on this.

**Comment by noahtallen** [comment]
Not sure why github actions thinks this PR affects `apps/editing-toolkit` (or why it duplicated all those checks), so I guess you can ignore the `Editing Toolkit Plugin` checks. I think it can be weirded out by rebases and changing base branches? 🤷

**Comment by dmsnell** [comment]
yes @noahtallen - it's confused and running the tests off of another branch. I'm waiting for someone to merge something into `master` so I can rebase again and see if that clears things up. if not I'll probably have to create a new PR. thanks for stopping by~!

**Comment by mirka** [comment]
Thanks Dennis! 🙏

**Pull request merged**
