### PR TITLE
Social signup: Update designs to match /log-in

### PR DESCRIPTION
**Pull request by scruffian**
This pull request updates the designs of /start/social to be inline with /log-in:
  
screen shot 2017-06-20 at 11 44 55
screen shot 2017-06-20 at 11 44 51

  
#### Testing instructions
  
1. Run `git checkout update/social-signup` and start your server
2. Open the [`Social signup` page](http://calypso.localhost:3000/start/social)
3. Check that the footer area matches the screenshot above
4. Try doing a social signup with an email that is already associated to a wordpress.com account
5. Check that you see the error as in the screenshot above
  
#### Reviews
  
- [ ] Code
- [ ] Product

cc @danhauk, since you suggested these changes :)

### CODE REVIEW

**Comment by fabianapsimoes** [comment]
There's quite a bit of space between the password field and the Terms of Service copy. Is that intentional?

space

I think the size of the copy in the social options section should be the same for Login and Signup.

Login:
fontsizelogin

Signup:
fontsizesignup

> Try doing a social signup with an email that is already associated to a wordpress.com account

You mean already associated but not through social signup, right? I only see the message if I use an account that isn't social, otherwise I'm logged in (which is what I expected, but mentioning here to make sure we're on the same page).

In this error message, should we have a link to login like when you manually enter an email? 

error

**Comment by scruffian** [comment]
> There's quite a bit of space between the password field and the Terms of Service copy. Is that intentional?

This is to give space for errors relating to the password, so that the rest of the form doesn't move.

**Comment by danhauk** [comment]
I think I remember talking about combining the copy for the social section too. Maybe something like

> Or create an account using your existing social profile to get started faster. We'll never post without your permission.

I also agree with @fabianapsimoes that a link to log in would be a nice addition to the notice, at least until we implement connecting Google accounts where the email address is already registered.

**Comment by scruffian** [comment]
I have made the suggested changed, except the log-in link, which I think we won't need, since we are going to handle this case differently anyway.

**Comment by fabianapsimoes** [comment]
Code and Product :+1:

**Pull request merged**
