### PR TITLE
A4A > Referrals: Automated Referrals UI enhancements & mobile view improvements

### PR DESCRIPTION
**Pull request by yashwin**
Closes https://github.com/Automattic/jetpack-genesis/issues/385
Closes https://github.com/Automattic/jetpack-genesis/issues/339

## Proposed Changes

This PR 

- Makes some UI enhancements & mobile view improvements to automated referrals.
- Adds some event tracking

## Testing Instructions

- Open A4A live link
- Visit the Referral Dashboard (/referrals/dashboard) > Verify that the UI looks as shown below:

Updated the max-width to 700px
Removed the underline from the icon
Updated the heading from `Find out more about the program` to `Find out more`

Screenshot 2024-06-18 at 12 50 53 PM

- Go to Payment Settings (/referrals/payment-settings) and verify that the UI looks as shown below:

Removed the underline from the icon

Screenshot 2024-06-18 at 12 52 24 PM

- Go to FAQ (/referrals/faq) and verify that the UI looks as shown below:

Updated the max-width to 700px

Screenshot 2024-06-18 at 12 51 03 PM

- Visit the Referral Dashboard (/referrals/dashboard) > Click the `Make a referral` button > Add WPCOM hosting and any products to the cart > Go to checkout > Enter the client's email address (you will need to create a new account using this email ID later) and a custom message > Click the `Request payment from client` button > You will be redirected to the Referral Dashboard once the request is complete.

-  Verify the UI looks as shown below:

Removed the per-page filter

Screenshot 2024-06-18 at 1 02 59 PM

Updated the mobile view

Screenshot 2024-06-18 at 1 01 38 PM

**Switching to client view**

- Check the email ID that you used for the referral earlier for an email that starts as `Payment requested..` and copy the link address from the `Pay Now` button and open that link in an incognito window:

Screenshot 2024-06-18 at 2 11 13 PM

- Verify that you are redirected to the checkout after logging in > Verify the UI looks good on mobile view > Click the `Add my payment method` button > Notice that you are redirected to the payment method page > Verify the UI looks good on mobile view > Add a new card by entering your payment details > Once you are redirected to the checkout > Verify the UI looks good on mobile view > Click the `Submit my payment information` button > You will be redirected the Subscriptions page once the request is successful. 

Screenshot 2024-06-18 at 12 54 36 PM

- Verify the mobile view looks as shown below:

Screenshot 2024-06-18 at 2 19 47 PM

- Visit the Payment methods and verify everything looks good.

More testing for designers:

- Go to your agency view
- Go to /purchases/licenses and verify that the client licenses show the email ID as shown here: https://github.com/Automattic/wp-calypso/pull/91840
- Go to /sites/need-setup and verify that the client licenses show the email ID as shown here: https://github.com/Automattic/wp-calypso/pull/91756
- Visit /referrals/dashboard and verify that the paid referral shows `Active` status 
- Click on the client > On the `Purchases` screen > Click the `Assign to site` button > Assign the license to a site 
- Once done, Visit /referrals/dashboard > Click on the same client > On the `Purchases` screen, verify that the assigned site is shown for the purchase, and clicking on the site URL should redirect the user to the site details.
- Visit /referrals/dashboard >Click on the same client > On the `Purchases` screen > Click the `Create site` button > Verify that the license of the client you wanted to create a site for shows up as the first item ([screenshots](https://github.com/Automattic/wp-calypso/pull/91756)) > Click the `Create new site` button > Once the site is created > Visit /referrals/dashboard >Click on the same client > On the `Purchases` screen > Verify that the site name appears. 

## Pre-merge Checklist

- [x] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [x] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Comment by madebynoam** [comment]
@jeffgolenski pinging you here, in case you want to test as well.

**Comment by madebynoam** [comment]
in the payments screen, there is an extra space between the link and icon. Let's fix it so that it looks like this:
image

**Comment by madebynoam** [comment]
Let's fix the hanging word here, known as a 'runt', as well with a `nbsp;`
image

**Comment by jkguidaven** [comment]
With a long client email. The mobile view does horizontal scrolling.

https://github.com/Automattic/wp-calypso/assets/56598660/42af55db-ffbd-41b7-b18b-6f796c7460a5

**Comment by madebynoam** [comment]
Lets also remove the space between the link and icon here:
image

**Comment by madebynoam** [comment]
Clicking this Learn more link, just takes me to an empty cart:
image

**Comment by yashwin** [comment]
@madebynoam @jkguidaven: Thanks for the review.

I have addressed all the [comments](https://github.com/Automattic/wp-calypso/pull/91874/commits/5f3c7b4d5862af8ddda93e5dbe1c463010e61d78) until now. Could you please take another look? I have also added some event tracking. Thanks!

**Comment by madebynoam** [comment]
Thanks, Yashwin!
I'll continue testing now.
First note:
The chevron is too low and not aligned with the row:
image

**Review by jkguidaven — APPROVED** [review]
Thanks for addressing my comments. Other than Noam's feedback. LGTM 👍

**Comment by yashwin** [comment]
@madebynoam: I'm merging this PR as it is behind a feature flag. If you have feedback, I'll address it in a different PR, as you are unable to test the changes.

**Comment by jeffgolenski** [comment]
Just noting for posterity. After these PRs were merged, extensive testing has been conducted and videos uploaded to slack (since this is a public repo)

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/14880739).

**Pull request merged**
