### PR TITLE
Jetpack Manage: add Get Help nav to overview page

### PR DESCRIPTION
**Pull request by tbradsha**
Resolves Automattic/jetpack-manage#150

## Proposed Changes

This adds the "Get Help" links to the overview page.

Technical scope: pf36In-mf-p2#get-help

image

## Testing Instructions

* Review the code.
* Verify the `expanded` state is preserved upon refresh.
* Verify tracks events fire when clicking a link.
* Verify tracks events fire when expanding/collapsing the component.

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

**Review by coder-karen — COMMENTED** [review]
Tracks and functionality all work well!

I was looking at the Figma design, and it appears that the Get Help title and links should all should align with the Quick Links heading and icons above, and all have a greater margin.

With the nav links, it seems they should open in a new tab, similar to the Get Help link in the bottom left of all pages currently.

Related to that link, I've also left a question around the external link icons and whether we ought to use those, on the P2 post here: pf36In-mf-p2#comment-602

**Comment by tbradsha** [comment]
> I was looking at the Figma design, and it appears that the Get Help title and links should all should align with the Quick Links heading and icons above

Discussed this a bit with @coder-karen; they align as per the Figma.

> and all have a greater margin.

This will be easier to adjust once all components are in place on the page, so deferring to a future point.

> With the nav links, it seems they should open in a new tab, similar to the Get Help link in the bottom left of all pages currently.
>Related to that link, I've also left a question around the external link icons and whether we ought to use those, on the P2 post here

Thanks! Fair points!

**Review by coder-karen — APPROVED** [review]
Looks good to me :) I know we're possibly pending design follow-up but approving now in case we want to follow up with any changes later.

**Comment by tbradsha** [comment]
Gonna merge for now, and we can follow up in a future PR as needed.

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/10048175

Some locales (Hebrew, Japanese) have been temporarily machine-translated due to translator availability. All other translations are usually ready within a few days. Untranslated and machine-translated strings will be sent for translation next Monday and are expected to be completed by the following Friday.

Thank you @tbradsha for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/10048175).

**Pull request merged**
