### PR TITLE
Quick Start: Remove concierge banner from purchases list

### PR DESCRIPTION
**Pull request by obenland**
#### Changes proposed in this Pull Request

* Deletes the concierge-banner component
* Removes references to the concierge-banner component from the purchases list

#### Before
Screen Shot 2021-11-19 at 11 03 35 AM

#### After
Screen Shot 2021-11-19 at 11 05 00 AM

Related to pc4ICr-mc-p2

### CODE REVIEW

**Comment by daledupreez** [comment]
@obenland, I am not sure if it makes sense to remove this banner yet. I say this because we want users who already have Quick Start sessions to schedule them so we have fewer outstanding sessions.

**Comment by obenland** [comment]
Sure, happy to wait. I just saw it in the todo list and thought it could be a good way for me to contribute. Glad to follow your lead on this

**Comment by joelwills** [comment]
Is it possible only to show this banner to those who have already purchased a session (either directly or included in their eCommerce Plan)? Or does it already only show to them?

**Comment by daledupreez** [comment]
Quick note: in #57638, I removed the upsell CTA from this location, but kept all the reminders for already-purchased sessions. For the time being, I think it makes sense to remind/prompt users with outstanding sessions.

**Comment by obenland** [comment]
Sounds good! Closing for now.

**Pull request closed without merging**
