### PR TITLE
Atomic: overhaul eligibility hold warnings copy

### PR DESCRIPTION
**Pull request by ranh**
This PR updates copy on the eligibility holds screen – the screen we show when there are blockers to convert a site to Atomic. 

The copy changes focus on reducing jargon and maintaining consistency. This table summarizes all changed strings:

| Before                                                       | After                                                        |
| ------------------------------------------------------------ | ------------------------------------------------------------ |
| The errors above must be resolved before proceeding. Have questions? Please contact support. | Please clear all the above issues to proceed. Questions? [Contact support](#) for help. |
| **Installation in progress**<br/>Please wait for the other installation to complete, then try again.<br/>https://wordpress.com/help | **Installation in progress**<br/>Just a minute! Please wait until the installation is finished, then try again.<br/>(no link) |
| **Jetpack site not supported**<br/>Try using a different site.<br/>(no link) | **Not available for Jetpack sites**<br/>Try using a different site.<br/>(no link) |
| **VIP site not supported**<br/>Try using a different site.<br/>(no link) | **Not available for VIP sites**<br/>Try using a different site.<br/>(no link) |
| **Private site not supported**<br/>Make your site public or hidden to resolve.<br/>/settings/general/${ siteSlug } | **Public site needed**<br/>Change your site's Privacy settings to "Public" or "Hidden" (not "Private") to clear this issue.<br/>https://en.support.wordpress.com/settings/privacy-settings/ |
| **Flagged site not supported**<br/>Contact us to review your site's standing to resolve.<br/>https://en.support.wordpress.com/suspended-blogs/ | **Ongoing site dispute**<br/>Contact us to review your site's standing and resolve the dispute.<br/>https://en.support.wordpress.com/suspended-blogs/ |
| **Site owner access required**<br/>Only site owners are allowed to use this feature.<br/>https://en.support.wordpress.com/user-roles/ | **Site owner only**<br/>Only the site owner can use this feature.<br/>https://en.support.wordpress.com/user-roles/ |
| **Not a custom domain owner**<br/>You must be the owner of the primary domain subscription to use this feature.<br/>https://en.support.wordpress.com/domains/ | **Domain owner only**<br/>The primary domain on this site is owned by a different user. Change the primary domain to one that you own, or contact support to have this domain transferred to you.<br/>https://en.support.wordpress.com/domains/ |
| **Domain not using WordPress.com name servers**<br/>Your domain must use WordPress.com name servers to support custom code. Ask your domain provider to update your DNS settings.<br/>https://en.support.wordpress.com/domains/map-existing-domain/#2-ask-your-domain-provider-to-update-your-dns-settings | **Domain should use WordPress.com name servers**<br/>This domain is not using WordPress.com name servers, so it\'s not pointing to your site. Change your name servers over at your domain provider\'s. If you\'re not sure how to do that, contact them for help.<br/>https://en.support.wordpress.com/domains/map-existing-domain/#2-ask-your-domain-provider-to-update-your-dns-settings |
| **Domain not pointing to WordPress.com servers**<br/>We cannot manage your site because your domain does not point to WordPress.com servers. Follow the instructions to reset your domain's A records to resolve this.<br/>https://en.support.wordpress.com/move-domain/setting-custom-a-records/ | **Domain pointing to a different site**<br/>Your domain is not properly set up to point to your site. Reset your domain's A records in the Domains section to fix this.<br/>https://en.support.wordpress.com/move-domain/setting-custom-a-records/ |
| **Security certificate required**<br/>We are setting up a security certificate for your domain now. Please try again in a few minutes.<br/>(no link) | **Certificate installation in progress**<br/>Hold tight! We are setting up a digital certificate to allow secure browsing on your site, using "HTTPS". Please try again in a few minutes.<br/>(no link) |
| **Unconfirmed email**<br/>You must have verified your email address with WordPress.com to install custom code. Please check your email to confirm your address.<br/>(no link) | **Confirm your email address**<br/>Check your email for a message we sent you when you signed up. Click the link inside to confirm your email address. You may have to check your email client\'s spam folder.<br/>(no link) |
| **We can't proceed with this upload**<br/>This site is not currently eligible for installing themes and plugins. Please contact support to straighten things out.<br/>https://en.support.wordpress.com/help-support-options/ | **Upload not available**<br/>This site is not currently eligible to install themes and plugins. Please contact our support team for help.<br/>https://wordpress.com/help/contact |

An easy way to get to this screen is to try to upload a plugin on a free (Simple) site. Here's what it looks like now:

image

Thanks @michelleweber and @obi2020 for humanizing this more.

### CODE REVIEW

**Comment by obi2020** [comment]
A couple general comments:

- There's some visual context I don't have here, so not sure how links are implemented. Are you linking text or is the entire URL exposed? Linking text is preferred and in that case, just be sure the linked text sets expectations for where the user will land. 

- Also, I wonder if "to clear this issue" is necessary in the few places it exists. For example in the "Confirm your email address" warning it doesn't seem necessary. Again, I don't know what the screen looks like, so maybe it relates to some other part of UI?

Otherwise copy changes look good!

**Comment by ranh** [comment]
Thanks @obi2020! 

To answer your question, the links are shown as buttons with the label "Learn More". You can find a few good screenshots of this screen in this previous round of copy updates: https://github.com/Automattic/wp-calypso/pull/17469

I'll update the description with a screenshot of the page and with more information about how to get to it.

**Comment by ranh** [comment]
> Also, I wonder if "to clear this issue" is necessary in the few places it exists. For example in the "Confirm your email address" warning it doesn't seem necessary. Again, I don't know what the screen looks like, so maybe it relates to some other part of UI?

Good note. I wasn't sure about it either. My thinking was that it sets apart the issues that can actually be resolved by customers, and makes it clear that there's an action they can do. It also ties into the note at the bottom of the screen: "Please clear all the above issues to proceed". Also, you'd never see all these issues at the same time, so overall it will be less overwhelming and repetitive.

**Comment by michelleweber** [comment]
- I think "resolve" is a better word choice than "clear" in this case -- in English, it's the word more people would expect to see, and is less ambiguous. ("Clear" could mean "close this message," but that doesn't mean anything's actually been resolved.)
- I agree that you don't need the "to clear this issue" in the individual messages; the title, design of the message, and message itself all make clear that there's an action you need to take.

On individual messages, I think we have some opportunities to make a few of them a little warmer and more natural-language and offer a little more detail:
- Just a minute! Please wait until the installation is finished, then try again.
- Contact our support team -- they'll review your site's standing and help you resolve the dispute.
- Either change the primary domain to one that you own, or contact support to have this domain transferred to you.
- This domain isn't actually connected to WordPress.com yet --it needs to be updated to use WordPress.com name servers. If you're not sure what that means or how to do it, your domain provider can help.
- Your domain isn't set up properly at the moment. To fix this, head to My Site > Domains to reset your A records. Here are step-by-step instructions:
- Hold tight! We're setting up the digital certificate that will allow secure browsing on your site with "HTTPS". Try again in a few minutes.
- You should have received an email with a a link to confirm your email address right after you signed up. Check your email and click the link -- and if you didn't get it, contact our support folks.
- This site isn't currently eligible to install themes and plugins. Please contact our support team to learn more and get things sorted out.

**Comment by ranh** [comment]
Thanks for the edits @michelleweber, great stuff! I wanted to avoid the term "resolve" because I felt it had a negative connotation. Ambiguity is not really a concern here, resolving the issue / closing the message are essentially the same thing. That said, overall your edits get around this issue much better :)

I'll also update the table in the PR description with this new copy.

**Comment by ranh** [comment]
Thanks @donpark! For now I changed the label to "Help" so it doesn't wrap. This is not an ideal solution as in other locales there may still be a long label that wraps. We can start a separate PR for that if necessary.

**Pull request merged**
