### PR TITLE
Signup: add AB test for horizontal/vertical plans table

### PR DESCRIPTION
**Pull request by keoshi**
Adds a new AB test to evaluate the performance of horizontal vs vertical plans tables on smaller screens.

AB test name: `mobilePlansTablesOnSignup`.
Allocations: `50/50`.

e2e tests PR: https://github.com/Automattic/wp-e2e-tests/pull/1058

Some background here: p6TEKc-1T2-p2

### Before

**WordPress.com**

image

**Jetpack**

image

### After (`mobile` variant)

**WordPress.com**

image

**Jetpack**

image

### How to test

- Login to WP.com and using a smaller device/screen (<660px):
  - For WP.com: head to http://calypso.localhost:3000/start
  - For JP: create a site, head to http://calypso.localhost:3000/jetpack/connect
- Follow along the steps until you:
  - For WP.com: reach step 3 "Pick a plan".
  - For JP: enter the URL of your site and hit “Connect now”.
- Set up the variant in your console and refresh your browser: `localStorage.ABTests = 'localStorage.setItem( 'ABTests', '{"mobilePlansTablesOnSignup_20180320":"mobile"}' )’`.
- You should see the plans tables oriented vertically.

### CODE REVIEW

**Comment by keoshi** [comment]
No problem, @fditrapani — pushed some changes for JP and adding extra testing instructions too.

**Comment by johnHackworth** [comment]
I'm not sure what's happening, but when I test this in calypso.live and a jetpack site, WITHOUT running the command to activate the test, I just get an empty plans screen:

image

**Comment by johnHackworth** [comment]
(the test version looks good, though)

**Comment by keoshi** [comment]
This is more complex that I thought, lots of page variations to test. :)

Here's what I've come up with, where:

- `X` represents where the `mobileView` shouldn't be visible.
- `V` represents where it should be.

```
+--------------------------------------------+
|            |   "original"   |   "mobile"   |
|   signup   |        X       |      V       |
|   /plans/  |        V       |      V       |
+--------------------------------------------+
```

This is valid for both WordPress.com and Jetpack views, so be sure to check the table above twice.

**Comment by keoshi** [comment]
@fditrapani @johnHackworth Would appreciate another check here, now that I'm pretty sure all scenarios are covered.

**Pull request merged**
