### PR TITLE
Reader: Only check the path when comparing canonicals to features

### PR DESCRIPTION
**Pull request by blowery**
Better prevents dupe images from appearing in content. May over prevent, but better that than the alterative.

### CODE REVIEW

**Comment by blowery** [comment]
before
wordpress_com_launches_vr_content__coming_soon_to_jetpack_ _wordpress_tavern_ _reader_ _wordpress_com


after
wordpress_com_launches_vr_content__coming_soon_to_jetpack_ _wordpress_tavern_ _reader_ _wordpress_com

**Comment by fraying** [comment]
👍

**Comment by bluefuton** [comment]
@blowery shall we add a unit test for this?

**Comment by blowery** [comment]
@bluefuton yes, but not in this PR? norm-rules has no test coverage right now and could use some, classifyPost especially. I'd rather do that in a targeted PR than a one-off here.

**Pull request merged**
