### PR TITLE
Reader: use `react-masonry-component` for StartCards

### PR DESCRIPTION
**Pull request by TooTallNate**
Uses [Masonry](masonry.desandro.com) for layout in Cold Start (see https://github.com/eiriklv/react-masonry-component).

This renders the StartCards from left to right, rather then top to bottom via columns.

#### Example:

screen shot 2016-06-09 at 1 13 20 pm

(Note that "TechnoScience as if People Mattered" is the 2nd entry in the DOM list, and is being rendered to the right of the first StartCard, as expected).

This is expected to make the interaction of loading more recs (#5652) be more pleasant.

/cc @jancavan @bluefuton 

Test live: https://calypso.live/?branch=add/reacy-masonry-component

### CODE REVIEW

**Comment by jancavan** [comment]
This is awesome Nate! 👏  

Added a small update here: https://github.com/Automattic/wp-calypso/pull/5944/commits/949a989cb21cd25460fca90b35112abda4163ed4, just made margin around cards equal.

**Comment by jancavan** [comment]
Fixed a breakpoint issue in: https://github.com/Automattic/wp-calypso/pull/5944/commits/df6faa4f39dd876f40b8f018b58c15efd3cb35fb

@TooTallNate it seems like the gap between columns stays the same regardless of the size of the cards - even with the original width of `350px`. Is there a way to make the gap between columns same size as the gap above cards?

screenshot 2016-06-09 14 21 20

**Comment by mtias** [comment]
@jancavan @TooTallNate can't we achieve this just with flexbox these days (with `flex-wrap`)? I found [this link](http://thenewcode.com/844/Easy-Masonry-Layout-With-Flexbox) with a quick search.

**Comment by bluefuton** [comment]
The cards don't appear in exact source order (e.g. the final card is on the bottom left for me), but should be close enough to vastly improve the loading experience for new cards :+1:

**Comment by bluefuton** [comment]
@jancavan has experimented with Flexbox and Columns, and ultimately we've not found a solid solution (yet) that offers:
- variable height cards
- variable number of cards (so hard to set fixed height on container)
- cards flowing horizontally in HTML source order

Horizontal flow seems to be the trickiest part.

**Comment by bluefuton** [comment]
Looks good to me :ship:

**Pull request merged**
