### PR TITLE
A4A: Sites Dashboard - Fix last site item (row) in the table being cut off

### PR DESCRIPTION
**Pull request by gogdzl**
Related to https://github.com/Automattic/automattic-for-agencies-dev/issues/299

## Proposed Changes

* This PR adjusts the margin for the site dashboard table. Our previous margin setting did not account for the pagination's bottom bar.

## Testing Instructions

For the below testing steps, make sure to run `yarn start-a8c-for-agencies` locally and then visit `http://agencies.localhost:3000/sites`.

* To test, add a sufficient number of sites to trigger pagination while simultaneously filling the entire window.
* Verify that the last site is not being cut off.

Before
image

After
image

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Review by coder-karen — CHANGES_REQUESTED** [review]
Thanks for following up on this!

Works well in the main sites dashboard view (no preview pane open).

If you open the preview pane whilst pagination is in place, the sites list is still getting chopped off (I don't see the last result when paginating by 10 for example).

**Comment by gogdzl** [comment]
> If you open the preview pane whilst pagination is in place, the sites list is still getting chopped off (I don't see the last result when paginating by 10 for example).

Nice catch! Fixed in d96047f.

@coder-karen

**Comment by cleacos** [comment]
As we've discussed, we will eventually have to fix the issue with the `height` and vertical scrolling. It seems tricky, but maybe @keoshi, as a CSS expert, could know how to fix it.

**Review by coder-karen — APPROVED** [review]
Works well now with the preview pane open!

**Pull request merged**
