### PR TITLE
Add in-app domain transfer instructions

### PR DESCRIPTION
**Pull request by mtias**
Adds a simple in app modal showing step by step instructions for unlocking domains.

- [x] Add images.
- [x] Add translation functions.
- [ ] Allow selecting different registrar instructions (or make conditional to GD only).
- [x] Move modal to a component so it can be reused in later screens.

image

### CODE REVIEW

**Comment by pablohoneyhoney** [comment]
Nice. 

Shall the arrows be wp/components?

**Comment by ebinnion** [comment]
In its current state, the steps don't match the screenshots.

**Comment by ebinnion** [comment]
The user doesn't have to unlock the domain first. They can click "Get auth code" and then unlock it as part of that flow. I would expect that this is the slightly easier option for us to explain.

**Comment by alshakero** [comment]
Merging into https://github.com/Automattic/wp-calypso/pull/79995

**Pull request merged**
