### PR TITLE
Move help-center to its own widgets app

### PR DESCRIPTION
**Pull request by alshakero**
#### Proposed Changes

* This is a failed (so far) attempt to move the help center Gutenberg plugin into its own JS module. That could be imported by any WordPress plugin, be it ETK or Jetpack, to have the help center functionality. 
* I couldn't get it running for reasons I can't figure out. What I know so far though, is that `registerPlugin` isn't calling the `render` function of the plugin I'm registering. However, when I register the plugin using `wp.data.plugins.registerPlugin` (vs `registerPlugin from '@wordpress/plugins`, `render` function does get called, but other issues emerge.

#### Starting Instructions
1. Go to `apps/help-center` and run `yarn dev --sync`.
2. Go to `apps/editing-toolkit` and run `yarn dev --sync`.
3. Sandbox a site and widgets.wp.com.
4. Visit the editor in the site, success would be seeing the help center icon next to Jetpack on the top bar.

### CODE REVIEW

**Comment by noahtallen** [comment]
### Why doesn't it work as is?
Ok, so the exact problem was that the webpack config didn't have dependency extraction. After adding it and making a couple tweaks, Help Center does load correctly from widgets.wp.com! (More on why that's the case later!)

Screen Shot 2022-06-04 at 2 28 27 PM

### How to actually sandbox the valuable data?
That said, if our goal is to basically sandbox all "important" data inside widgets.wp.com, we unfortunately need to go a level deeper and actually load the important stuff via an iframe. As an example, notifications can be directly accessed via https://widgets.wp.com/notifications/. We deploy a (very basic autogenerated) HTML file which points at the JS bundles for notifications, and then when we load an iframe to https://widgets.wp.com/notifications/, the panel loads and all the data is sandboxed.

To also sandbox help center in the same way, we would need to do the same thing, where the content is loaded inside an iframe.

This is actually exactly why the existing Calypso apps on widgets.wp.com _don't_ use dependency extraction and why the copied webpack config didn't work. Because they are loaded in iframes, they don't have access to the `wp.*` global by design. This makes sense: because the code in the iframe is sandboxed, it can't access the top-level frame which includes WordPress and Gutenberg. And vice-versa, the potentially untrusted code in the top-level frame can't access a widget running in an iframe. This is what provides the security, but it also makes the dependency extraction plugin useless. 

The current approach in the PR just loads the scripts like any other WordPress script, which doesn't provide any protection.

### What should be in Gutenberg and what should be in an iframe?

This leads us to another interesting problem: is there information the help center expects to access which wouldn't be available in an iframe? For example, does it read information out of Gutenberg's data stores?

Honestly, we haven't _really_ had to solve this problem yet. The only existing example is Notifications, but that doesn't need to interact with info in the top-level frame. So there's not much if any post messaging going on to share info. And it definitely doesn't interact with Gutenberg.

Does this mean we need two separate scripts? One operating inside of Gutenberg, not sandboxed. This one can interact with the data stores in Gutenberg, and can access any public information, or information about the current site. And then would we need a script to load more private information like chat? Do we just need to load happychat in an iframe if that's the only more protected piece of data?

### How to move forward
I think the path forwards depends on answers to some questions which I'm not completely clear on:
- Does Help Center need direct access to Gutenberg? E.g. does it need to interact with Gutenberg by dispatching actions and reading selectors?
- What private information is going in Help Center? Is it a critical, common part of the design, or is it just a small part of the functionality, like happychat?

For example, if Help Center doesn't use much info that needs to be private, the current approach is probably fine. if only a single feature needs to sandbox data, that single feature could be iframed. This lets help center access gutenberg more directly.

If it's the other way around, and more information should be sandboxed, then we should probably put most of help center in an iframe and then use post message to interact with gutenberg. With that approach, we'd have a really minimal script to register the plugin and the icon, and then the iframe could load when you click on the icon. 
 
What are your thoughts?

**Comment by escapemanuele** [comment]
Hi @noahtallen, thanks for the time spent explaining all of this!

> Does Help Center need direct access to Gutenberg?

As you can see [here](https://github.com/Automattic/wp-calypso/blob/trunk/apps/editing-toolkit/editing-toolkit-plugin/help-center/src/CalypsoStateProvider.js#L25), the help center registers and uses `currentUser` and `sites` stores from Calypso, and uses its own `help-center` [data store](https://github.com/Automattic/wp-calypso/blob/trunk/packages/data-stores/src/help-center/index.ts#L2-L3). So it shouldn't need direct access to Gutenberg data stores.

> What private information is going in Help Center?

Sorry, with private information do you mean the requests we make for user data? 😄 
Not being sure, I'll list them:
- [useSupportAvailability](https://github.com/Automattic/wp-calypso/blob/trunk/packages/data-stores/src/support-queries/use-support-availability.ts#L9) requests user availability for [chat](https://github.com/Automattic/wp-calypso/blob/trunk/packages/help-center/src/hooks/use-should-render-chat-option.tsx#L10) or [email](https://github.com/Automattic/wp-calypso/blob/trunk/packages/help-center/src/hooks/use-should-render-email-option.tsx#L0-L1).
- In [this file](https://github.com/Automattic/wp-calypso/blob/trunk/packages/happychat-connection/src/use-happychat-auth.ts#L44) we make requests to get the user authentication data ( jwt and others ), and we use that to [communicate](https://github.com/Automattic/wp-calypso/blob/trunk/packages/help-center/src/happychat-window-communicator.ts#L33) 
to the [iframed happychat](https://github.com/Automattic/wp-calypso/blob/trunk/packages/help-center/src/components/help-center-inline-chat.tsx#L6).
- In the chat, we also [make a request](https://github.com/Automattic/wp-calypso/blob/trunk/packages/help-center/src/happychat-window-communicator.ts#L27-L29) to get the current site

Please tell me if you wanted to know something different, or just if you want to ask other things, your help would be invaluable 🙇‍♂️

**Comment by noahtallen** [comment]
Thanks for that info!

> In [this file](https://github.com/Automattic/wp-calypso/blob/trunk/packages/happychat-connection/src/use-happychat-auth.ts#L44) we make requests to get the user authentication data ( jwt and others ), and we use that to [communicate](https://github.com/Automattic/wp-calypso/blob/trunk/packages/help-center/src/happychat-window-communicator.ts#L33)
to the [iframed happychat](https://github.com/Automattic/wp-calypso/blob/trunk/packages/help-center/src/components/help-center-inline-chat.tsx#L6).

I think this is what we need to be cautious about. If this auth data has a broad scope, it needs to be stored somewhere that a "rogue" script couldn't access it and use it maliciously. This is something I don't quite know as much about. For example, if it is truly dangerous, would the request to get auth info from `/me` even work from Atomic sites in that 3rd party domain context in wp-admin? If it's dangerous for that to work, wouldn't it be blocked? (These are questions I'm not sure about!)

Anyways, if this is the scenario:
- That auth data needs to be sandboxed
- Most of the help center can run isolated from the editor

Then I think implementing the help center as a widgets app would be the best path. In this approach, we would basically be able to load the help center UI as an independent app just pointing at `widgets.wp.com/help-center`. We would then add a light wrapper script which opens an iframe and loads that UI. Then the help center can access as much privileged information as it needs.

I wonder if @jsnajdr could provide some further advice here. Does my suggestion make sense?

**Comment by escapemanuele** [comment]
Thanks again @noahtallen!

> implementing the help center as a widgets app would be the best path.

This indeed seems to be the right path to follow. Could you be able to show me how you added dependency extraction and other tweaks? Asking because I see that you already solved the issue in your tests 😄 In my last commit I added `DependencyExtractionWebpackPlugin` to the webpack plugins and it is indeed able to load the help center, but it throws error when clicking on `Still need help?`. Probably some problem retrieving Sybil articles.

I'm not sure about the iframe part though. 
It would work at this point, as we don't rely much on the editor, but in the next iterations we'll need to work with tours (and the editor), and that would be a problem. Sorry, I hadn't thought about this in my previous answer.

Is there a possibility of not having the help center in an iframe? :)

**Comment by noahtallen** [comment]
> Could you be able to show me how you added dependency extraction and other tweaks?

I think I just did what you did in the PR -- not sure I tested it much further than it loading the basic UI! (I also want to point out again that dependency extraction is only important if the help center scripts are loaded in the editor context. We wouldn't want to do that if we iframe the help center)

>  It would work at this point, as we don't rely much on the editor, but in the next iterations we'll need to work with tours (and the editor), and that would be a problem. Sorry, I hadn't thought about this in my previous answer.

Yeah, that's a good point! In that case, maybe it doesn't all need to be iframed. At the same time, we could still use post message to communicate with tours and stuff like that which live in the top frame.

I mean, what we need is to sandbox sensitive data. If _all_ of the help center uses that sensitive data, then all of the help center would need to be sandboxed. If it's just like a single feature (e.g. the user auth stuff needed for happychat), then just happychat could be iframed. Then most of help center could work like normal, assuming it doesn't process any auth data or other sensitive information. 

And when you click "chat now" or something like that, we could load an  iframe pointed at `widgets.wp.com/happychat` just for the chat. Of course, 3rd party cookie concerns still apply, but I think that would be a problem no matter what. We might need to do some extra work to make sure happychat can load auth info from widgets.wp.com or something like that, but everything on widgets.wp.com should share the same cookies and access to local storage, so it shouldn't be a huge problem.

**Comment by escapemanuele** [comment]
> dependency extraction is only important if the help center scripts are loaded in the editor context

Would dependency extraction be useful if we succeed in only sandboxing auth and the happychat part, and not the help center? ( and auth, retrieved from [useHappychatAuth](https://github.com/Automattic/wp-calypso/blob/trunk/packages/happychat-connection/src/use-happychat-auth.ts#L44), is used for happychat and not in other parts of the help center )

> If it's just like a single feature (e.g. the user auth stuff needed for happychat), then just happychat could be iframed

I think this may be a nice thing to try! As you said, post message is of course a possibility here, but I fear it could add complexity to more advanced things that we want to add to the help center in the future. Or maybe not, but I think it may be a possibility, so I'd be happy to investigate this other way :)

> We might need to do some extra work to make sure happychat can load auth info from widgets.wp.com or something like that

We already load the happychat [in an iframe](https://github.com/Automattic/wp-calypso/blob/trunk/packages/help-center/src/components/help-center-inline-chat.tsx#L0-L1), and we pass the auth object to it ( and the 3PC problem should be solved ). 

So, for what I understand, the problem is the request for the user auth ( [useHappychatAuth](https://github.com/Automattic/wp-calypso/blob/trunk/packages/happychat-connection/src/use-happychat-auth.ts#L44) ), that is not sandboxed.

What are you proposing is to extract the request and have it sandboxed? Don't know if it is possible to move it to `https://widgets.wp.com/calypso-happychat/` where happychat lives?

**Comment by alshakero** [comment]
@escapemanuele I fixed the error by simply adding keys. There is an underlying problem that we can slip under the carpet for now, but it seems there is some disagreement between Emotion and React. When React tries to log an error about missing keys, it studies the JSX element to tell you where the missing keys are. When it comes to study the JSX element coming from Emotion, it fails due to this mismatch and breaks.

Ironically, React is trying to generate a helpful innocuous error about missing keys, but ends up breaking the app. So adding keys fixed it.

**Comment by noahtallen** [comment]
> We already load the happychat [in an iframe](https://github.com/Automattic/wp-calypso/blob/trunk/packages/help-center/src/components/help-center-inline-chat.tsx#L0-L1), and we pass the auth object to it ( and the 3PC problem should be solved ).
> So, for what I understand, the problem is the request for the user auth ( [useHappychatAuth](https://github.com/Automattic/wp-calypso/blob/trunk/packages/happychat-connection/src/use-happychat-auth.ts#L44) ), that is not sandboxed.
> What are you proposing is to extract the request and have it sandboxed? Don't know if it is possible to move it to https://widgets.wp.com/calypso-happychat/ where happychat lives?

Yes to each of these! That is my concern, that the auth data is not sandboxed in the current form. If we could have that happen in calypso-happychat, it'd be sandboxed. I think the main question is what auth information is already available on widgets.wp.com. For example, when a user loads notifications, does it store a cookie or auth token for that domain? If it does, that could also be used for happychat, I'd think. The 3rd party cookie issue will be that browsers will block calypso-happychat from accessing its local storage and cookies when it's loaded in an iframe like we're proposing here.

Though I'm also still a bit confused on how the current approach works around 3rd party cookies! Does the request to `/me` to get the cookie "just work" from wp-admin on a domain like foo.wpcomstaging.com?

**Comment by noahtallen** [comment]
> Would dependency extraction be useful if we succeed in only sandboxing auth and the happychat part, and not the help center?

Yes! We'd definitely want to use it in this case, so that WordPress can provide packages and we don't duplicate anything :)

**Comment by escapemanuele** [comment]
Well, yes, currently happychat (that we use behind an iframe) works in the help-center in a site like foo.wordpress.com with 3PC disabled :) So requests to /me and the following ones work!

But not sure if that's the case if we put those requests in an iframe!

**Comment by noahtallen** [comment]
> foo.wordpress.com with 3PC disabled :) So requests to /me and the following ones work!

I was curious about wpcomstaging sites, because IIRC they work a little differently. So while auth cookies and everything is available on *.wordpress.com, that's not the case on *.wpcomstaging.com because Atomic sites can run 3rd party code

**Comment by alshakero** [comment]
> Then I think implementing the help center as a widgets app would be the best path. In this approach, we would basically be able to load the help center UI as an independent app just pointing at widgets.wp.com/help-center. We would then add a light wrapper script which opens an iframe and loads that UI. Then the help center can access as much privileged information as it needs.

That sounds great, and I like the centralization of it. But I think it won't work when 3PCs are blocked. How would widgets.wp.com know who the user is if they don't send cookies?

**Comment by alshakero** [comment]
I wrote my thoughts in a P2 pdDR7T-8r-p2

**Comment by noahtallen** [comment]
> But I think it won't work when 3PCs are blocked. How would widgets.wp.com know who the user is if they don't send cookies?

You're right, it'd only work in that context if we used the [storage access API](https://developer.mozilla.org/en-US/docs/Web/API/Storage_Access_API). In that case, the browser prompts the user for permission, and if the user approves, then widgets.wp.com can access its cookies and local storage as normal

**Comment by alshakero** [comment]
Closing as no longer the plan.

**Pull request closed without merging**
