### PR TITLE
Privacy Policy Banner: Style policy text for a better readability

### PR DESCRIPTION
**Pull request by iamtakashi**
The privacy text inside the modal is hard to read since there is no useful style attached to the HTML tags used there.

screen shot 2017-12-04 at 14 45 07

There are two thing that improves the readability.
- [x] Add styles to `h3`
- [x] Add `p` tag to each paragraph

### CODE REVIEW

**Comment by lamosty** [comment]
When returning the privacy policy content from the API, we could run it first through the `the_content` WP filter so it's formatted as it would be on a site's front-end:

```
$content = apply_filters('the_content', $post->post_content);
```

**Comment by retrofox** [comment]
> Add p tag to each paragraph

just FYI, Handled in the `WP REST API` endpoint.

**Comment by retrofox** [comment]
**before**

image

**after**
image

**Comment by iamtakashi** [comment]
I found we need to style `h4` as well. Also, I adjusted paddings around the scrollable area.

I don't like the big gap above the "Privacy Policy", but that's from the source, and I think it should be removed from there.

**Comment by retrofox** [comment]
`<h4>`.
image

LGTM

**Pull request merged**
