### PR TITLE
Gutenboarding: Remove page-templates.json

### PR DESCRIPTION
**Pull request by ockham**
#### Changes proposed in this Pull Request

This file seems unused.

#### Testing instructions

Make sure this file isn't used anywhere in Calypso, and that Gutenboarding runs properly.

Note that this file _was_ used for a while outside of Calypso, in a REST API endpoint that we use for Gutenboarding. However, I believe that I removed the only part of code where it was evaluated in D41177-code, and @sirreal removed the LOCs that loaded it in D41281-code (Ctr+F `page-templates` in both diffs).

This means we'll need to exercise some extra caution when landing this (test it properly while it's on staging etc).

### CODE REVIEW

**Review by lsl — APPROVED** [review]
LGTM - thanks for this and the related diffs.

**Comment by ockham** [comment]
e2e tests are failing repeatedly. I'll try once more, but maybe this file is still referenced somewhere :thinking: :confused:

**Review by razvanpapadopol — COMMENTED** [review]
This file is currently used only in Verticals MC tool as mentioned in https://github.com/Automattic/wp-calypso/pull/42354#discussion_r441886143

@johnHackworth Are we planning to maintain that and maybe update it to use the [current design config file](https://github.com/Automattic/wp-calypso/blob/master/client/landing/gutenboarding/available-designs-config.json)?

**Comment by ramonjd** [comment]
> This file is currently used only in Verticals MC tool as mentioned in #42354 (comment)

@razvanpapadopol Not any more 😄 D48129-code

> This means we'll need to exercise some extra caution when landing this (test it properly while it's on staging etc).

@ockham Thanks for looking at this.

We were tracking the "clean up" over here: https://github.com/orgs/Automattic/projects/147#card-43574014

I created a PR that goes further than this, removing all the JSON files we don't use (and probably never have used) in production

https://github.com/Automattic/wp-calypso/pull/44932

I can rebase if you decide to go ahead with this one (LGTM by the way), or feel free to duplicate and close mine. However you see fit.

🙏

**Pull request merged**
