### PR TITLE
PostShare: Add PostShare devdocs instance

### PR DESCRIPTION
**Pull request by retrofox**
This PR adds a devdocs example page for the `<PostShare />` component. For this, also, it moves the component from `./my-sites` to `./blocks` and updates all dependencies where the component is imported.

### Testing
Test the component either from the posts list/ Share tab as the new devdocs page: http://calypso.localhost:3000/devdocs/blocks/post-share

### CODE REVIEW

**Comment by artpi** [comment]
I don't think this should be in devdocs.
Would we use this somewhere else? This is not a reusable component.

On top of that, I think this can spam people's accounts when not careful

**Comment by retrofox** [comment]
> The works as expected but I am not sure this should be fully enabled in the dev docs. 

 AFAIK We don't have another place to test blocks.

> I couldn't find any other dev doc blocks that trigger a live action without some other confirmation first

Let's take over of this.

> Would we use this somewhere else? This is not a reusable component.

Adding this page if mainly for testing purpose. At least for me, it gets easier use this page instead of going to posts page, click Share tab, etc. There are many cases similar to this one where the blocks there aren't reusable.







... and so on.


> On top of that, I think this can spam people's accounts when not careful

I don't consider it dangerous because it's a page for developers so we should know what are we doing here and the worst scenario is just sharing a post. It's pretty easy to fix this "potential" problem.

**Comment by retrofox** [comment]
>  I think this can spam people's accounts when not careful
> > I don't consider it dangerous because it's a page for developers so we should know what are we doing here and the worst scenario is just sharing a post.

Thinking well ... you're right. Let's definitely block the ability to share from this testing page

**Comment by retrofox** [comment]
Added `disabled` property.



Just FYI there is some work to do around of this. [I created an issue yesterday](https://github.com/Automattic/wp-calypso/issues/15037) but let's tackle it in another PR but I created an issue.

**Comment by retrofox** [comment]
Let's wait for shipping #15045 and #15103 before to this one. Setting `In progress`.

**Pull request merged**
