### PR TITLE
Checkout: Remove "onInitialize" arguments from useShoppingCartManager

### PR DESCRIPTION
**Pull request by sirbrillig**
#### Changes proposed in this Pull Request

In preparation to separate the shopping cart management from the main checkout page so it can be used elsewhere in calypso, we need to be able to add the products and coupons from the URL to the cart after the cart has been initially fetched.

This has presented a problem in the past because until these items have been added (and the cart refreshed), we cannot be sure that checkout is "ready", even though the cart has technically loaded. This has major implications for other parts of checkout, notably `useRedirectIfCartEmpty`, which needs to wait for this process before deciding if it should redirect (the cart may be empty when the page loads just as we're beginning to add products from the URL).

Here, we add a new hook, `useAddProductsFromUrl`, which handles the process of completing this initialization, and which keeps its own state that it uses to determine if the process has completed. Other components and hooks can then rely on this state to know if the cart is "ready" for use.

With that in place, it's possible to remove `productsToAddOnInitialize`/`couponToAddOnInitialize` from `useShoppingCartManager`, which becomes less complex and less tightly coupled to running inside checkout.

#### Testing instructions

- Visit calypso, enable record-analytics debugging by typing `localStorage.setItem('debug', 'calypso:composite-checkout:record-analytics')` into your console, and then reloading the page.
- Visit checkout with a product in the URL like `/checkout/example.com/premium`.
- Verify that checkout loads without errors and that you see the product added to your cart.
- When loading checkout, make sure that the `CART_INIT_COMPLETE` event happens in the console, that it happens after the cart is initialized, and that it only happens once.
- When loading checkout, make sure that the `CART_ADD_ITEM` event happens in your console, that it has the correct product listed, and that it happens only once.
- Remove all products from your cart.
- Verify that you are redirected to the `/plans` page.
- Visit checkout with a product and a coupon in the URL like `/checkout/example.com/premium?coupon=FOOBAR`.
- Verify that checkout loads without errors and that you see the product and the coupon added to your cart.

### CODE REVIEW

**Comment by sirbrillig** [comment]
Still one failing test... trying to track it down...

**Comment by sirbrillig** [comment]
That should fix it. I just hadn't updated the tests to match the modified prop name.

**Comment by sirbrillig** [comment]
Failing e2e tests are unrelated.

**Comment by nbloomf** [comment]
This is exciting stuff!

I got stuck on step 3 of the testing instructions due to what appears to be a race condition. Here's how it went down:

- I loaded calypso, logged in as a test user, and selected an existing site with a personal plan.
- I made sure my cart was empty, and then navigated to `/checkout/$siteurl/premium`
- I was redirected back to the plans page with URL `http://calypso.localhost:3000/plans/$siteurl?site=premium`, and had a premium plan in my cart. I tried this a second time, with the same result.

I do see the analytics notices in the console, as well as this react error:

image

- Clicking on the premium plan upgrade button from the plans page did load checkout as expected. Once in checkout, I tried manually navigating to `/checkout/$siteurl/premium` and checkout loaded as expected.
- I left checkout, emptied the cart, and tried to manually load `/checkout/$siteurl/premium` again, and saw the same incorrect redirect behavior. This time, however, I did not see the analytics notices, and my cart remained empty.

**Comment by sirbrillig** [comment]
Good find! ❤️ There was indeed a race condition, and in fact probably one that already happens but has not been as dramatic as this one.

The cart manager had sent a request to update the cart with the location data, then before that returned, it sent another request to add the initial item to the cart. When the first request came back (with no products in the cart yet), it marked the cart as valid which triggered the redirect check. By the time the second request came back (with the added product), the redirect had already occurred.

I made a change so that if there is a pending request when a new one is being made, the previous one will be "cancelled" (actually we'll just ignore its response) in favor of the new request. That seems to solve the bug as you reported it, but please let me know.

**Comment by nbloomf** [comment]
Nice. This time everything worked as expected except for adding a coupon from the URL. I tried directly loading `/checkout/:siteurl/premium?coupon=FOO`, where the sandboxed coupon came from the usual place.

- If my cart was not empty, checkout loaded with the correct plan in the cart and the coupon applied as expected.
- If my cart was empty, loading that URL put a premium plan in the cart and redirected to the plans page. When I navigated to checkout using the UI, it loaded with the correct cart and applied the coupon.

**Comment by sirbrillig** [comment]
> If my cart was empty, loading that URL put a premium plan in the cart and redirected to the plans page. When I navigated to checkout using the UI, it loaded with the correct cart and applied the coupon.

I believe you, but I've been unable to reproduce this. Maybe at some point I can get the debug logs for `calypso:composite-checkout:use-cart-update-and-revalidate,calypso:composite-checkout:use-redirect-if-cart-empty,calypso:composite-checkout:use-add-products-from-url` when this happens for you. That should tell us what's going on.

**Comment by nbloomf** [comment]
It turns out I was testing a stale branch, missing 4 commits. :)

After testing the right commit, this is working as described!

**Review by nbloomf — APPROVED** [review]

**Pull request merged**
