### PR TITLE
Editor: Add drag and drop media to the HTML mode

### PR DESCRIPTION
**Pull request by Copons**
Enable drag and drop capability to the editor in HTML mode.

I've mostly used readily made code from both the **Media Library** and the **TinyMCE** drag and drop logic.

See:
- https://github.com/Automattic/wp-calypso/blob/master/client/my-sites/media-library/drop-zone.jsx
- https://github.com/Automattic/wp-calypso/blob/master/client/components/tinymce/plugins/media/drop-zone.jsx#L94-L122

## GIF

mar-01-2017 16-06-28

### CODE REVIEW

**Comment by lancewillett** [comment]
Tested in the live branch with Mac-n-Chrome, working as expected. Nice improvement!

My only nitpick is the way the `blob:` URL structure appears, and then is replaced by the real image URL once it's ready. I don't know how to improve that exactly, but I found it slightly odd to see it change after a few seconds. A loading icon or pulsing dot instead of the placeholder?

**Comment by lancewillett** [comment]
Note: the interaction around replacing the real image URL shouldn't block getting this improvement in—can be a later improvement.

**Comment by Copons** [comment]
Nice catch @lancewillett, I absolutely didn't notice that.

Though, it's the exact same thing that goes on while dropping a file in Visual mode, just there it's concealed by the fact that you don't see the underlying HTML being added to the post content.
If you try to drop a fairly heavy image in Visual mode, and immediately switch to HTML mode, you'll see the same `blob` URL during the file upload.

I'm not exactly sure how (or even if) to fix it, but I'm gonna enquire about it.

**Comment by lancewillett** [comment]
Yep, and as I said — shouldn't block this amazing fix. Thank you. ;)

**Comment by roundhill** [comment]
Works great, I tested in IE 11 since I already had it open for your other PR :)

:shipit:

**Pull request merged**
