### PR TITLE
Reformat JS files with Prettier

### PR DESCRIPTION
**Pull request by jsnajdr**
There are many files that haven't been formatted with Prettier yet, like the new monorepo packages in `packages/`, the Notifications module in `client/notifications` or the scripts in `bin/`, or Devdocs examples. These get formatted in this PR.

Some already formatted files in `client/` just got out of sync.

In `bin/`, I updated some code to use arrow function instead of the classic ones. That's to preserve one-line formatting where possible.

I plan to do an upgrade of Prettier (from 1.14.0 to 1.15.3) and would like to update the formatting of the repo using the old version, so that the formatting changes caused by the upgrade are visible.

### CODE REVIEW

**Comment by sirreal** [comment]
Would you mind dropping the changes to the i18n-calypso package? We can add it to the necessary ignore file temporarily.

I've got a large PR that handles code formatting and a lot of other updates to bring that package up to date for integration in Calypso. I'd like to avoid a painful rebase that and I'll commit to getting that finished this week.

**Review by sirreal — APPROVED** [review]
Thanks! I've added full e2e label, let's wait for that to pass then ship.

**Comment by sirreal** [comment]
Full e2e tests are failing, but I'm seeing full e2e failures pretty regularly across different branches 🙄 

Please proceed when you're satisfied the failures are unrelated.

**Comment by jsnajdr** [comment]
I checked the failing parts of the app (domain search, remove people, publish password-protected post) on calypso.live and everything looks good. Going to merge 🤞

**Pull request merged**
