### PR TITLE
Webpack: Load the commons chunk in a script tag.

### PR DESCRIPTION
**Pull request by blowery**
This gets the commons chunk down to the browser faster and should speed up page loads a bit. It also gives the commons chunk a filename so it's more obvious what it is and why it's being included.

### CODE REVIEW

**Comment by blowery** [comment]
cc @mtias @aduth @gwwar 

be sure to test this with a local fake wpcalypso (or wordpress.com) to make sure the minification bits work as expected.

**Comment by gwwar** [comment]
👍 Tested this in a 🐋  image.
wpcommons

**Comment by blowery** [comment]
@gwwar i just noticed that vendor is requested twice... appears the second comes out of cache, but really weird.

**Comment by gwwar** [comment]
@blowery weird. I checked again, and there's a single script tag in the markup. I see a double request for Chrome but not Safari or FF

**Comment by blowery** [comment]
This was a tag on from #4852

**Pull request merged**
