### PR TITLE
Fix infinite loop of state updates in InfiniteList

### PR DESCRIPTION
**Pull request by sgomes**
This likely isn't the cleanest solution, but it does the job by ensuring that the potential infinite loop is broken across different runs of the event loop.

It may introduce some frames of incorrect rendering, but I believe that's an acceptable tradeoff.

A proper fix would involve reimplementing this component with a well-defined state machine, rather than the current set of inter-dependent lifecycle and utility methods. The ideal solution would be to replace this with a well-maintained community implementation that takes into account React performance, DOM performance, library size, and flexibility, but that may be a tall order to fulfil.

#### Changes proposed in this Pull Request

* Defer potentially loop-like invocation of UI update in `componentDidUpdate` lifecycle method.

#### Testing instructions

* Go to `/me/notifications` in the live branch
* Scroll around a bunch, making sure to scroll significantly down and then back up at least once
* Ensure that the page doesn't break

### CODE REVIEW

**Comment by sgomes** [comment]
@kwight: Could you ensure that the issue you fixed in #34468 doesn't relapse with this fix?

**Review by theck13 — APPROVED** [review]
The page no longer goes blank when scrolling and I do not see errors in the console.

**Comment by kwight** [comment]
@sgomes Nope, I don't see the issue with this PR 👍

**Comment by sgomes** [comment]
> @sgomes Nope, I don't see the issue with this PR 👍

Thank you, @kwight!

**Pull request merged**
