### PR TITLE
Jetpack Manage Form: Add new "managed_sites" input

### PR DESCRIPTION
**Pull request by gogdzl**
Related to https://github.com/Automattic/jetpack-manage/issues/45

## Proposed Changes

* This PR adds new managed_sites input to the <AgencySignupForm> component, above the "Country" field.
  * Label: How many sites do you manage?
  * Options: 
    * 1-5
    * 6-20
    * 21-50
    * 51-100
    * 101-500
    * 500+
* It also updates the tracks event `calypso_partner_portal_create_partner_submit`

## Testing Instructions
  - Open the agency sign up form in staging - http://jetpack.cloud.localhost:3000/agency/signup - and with a new account.
  - There should be a new select input `How many sites do you manage?` 
  - Visit the tracks live view (or use Tracks Vigilante) and watch the calypso_partner_portal_create_partner_submit event for your submission, and check the props. There should be a new prop called `managed_sites`

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

**Review by tbradsha — CHANGES_REQUESTED** [review]
Mostly there, but currently there's no default value set despite looking like `1-5` is selected. Two potential solutions:

1. Add a "choose one" select option.
2. Set the default to `1-5`.

I'd lean toward the second option, as that means less clicks for most people.

**Review by tbradsha — APPROVED** [review]
Looks good to me!

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/9561804

Some locales (Hebrew) have been temporarily machine-translated due to translator availability. All other translations are usually ready within a few days. Untranslated and machine-translated strings will be sent for translation next Monday and are expected to be completed by the following Friday.

Hi @gogdzl, could you please edit the description of this PR and add a screenshot for our translators? Ideally it'd include all of the following strings:
- `How many sites do you manage?`
- `1-5`
- `6-20`
- `21-50`
- `51-100`
- `101-500`
- `500+`
- `Managed sites`

Thank you in advance!

**Comment by coder-karen** [comment]
It looks like a default value for state was needed under `UpdateCompanyDetailsForm` as well, as the `partner-portal/company-details` form wouldn't work properly without it. Updated here as the fix was needed in order to hide the field: https://github.com/Automattic/wp-calypso/pull/83543

Edit - changed the default to `` on that form instead and also changed the default value to '' instead of 1-5 in the CompanyDetailsForm - see conversation in that PR plus here in Slack: p1698762906700959-slack-CTXBP902X .

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/9561804).

**Pull request merged**
