### PR TITLE
NPS Survey: Hook up survey block to API (save survey answer)

### PR DESCRIPTION
**Pull request by mattsherman**
This PR hooks up the NPS survey block to the API, allowing survey answers to be saved.

*Note: NPS survey styling is being handled separately in #12613 -- the UI is expected to look ugly in this PR!.*

Test:
- To see debug messages, in browse console:
    - `localStorage.setItem('debug', 'calypso:nps-survey');`
- from `http://calypso.localhost:3000/devdocs/blocks/nps-survey`
    - Survey should submit successfully the first time you answer it (the API errors if a score has been provided in the past 4 months)
- from global notice (see #12522)
    - Survey should error (silently; it always will thank the user for submitting -- no need to trouble the user should there be a problem submitting), since the survey name is not yet whitelisted in the API endpoint
- Verify that dismissing survey without answering it calls API (look at debug messages and Redux actions/state)

For now, this is not enabled in any environments. To enable:

```
ENABLE_FEATURES=nps-survey/notice make run
```

To re-trigger the NPS survey notice, in the browser console, type:

```
dispatch( showNpsSurveyNotice() );
```

To run unit tests:

```
npm run test-client -- --grep "state nps-survey"
```

### CODE REVIEW

**Comment by mjuhasz** [comment]
This is really good job, @mattsherman 👍

A minor note: I noticed that I can dismiss the dialog by clicking on the overlay which is positive from usability point of view. When I do so, the dismissal won't be registered, that is, the API won't be called. I don't consider this a problem because clicking on a button (to submit a a score or dismiss it) is a deliberate action, while clicking somewhere randomly on the overlay just to get rid of the dialog is not necessarily an action that I want to base conclusions on.

**Comment by mattsherman** [comment]
Miki, thanks for the review!

I will rebase and address the dialog dismissal by clicking the overlay issue -- that was working (we had agreed that it should be counted the same as "I'd rather not answer), but it looks like I broke it at some point before I put the PR up for review.

Once I've done that I'll ping you so you can give it a quick final look over!

**Comment by mattsherman** [comment]
@mjuhasz I've rebased and fixed the dialog dismissal issue. If you can give it a quick look and  👍it would be much appreciated! Thanks!

**Comment by mjuhasz** [comment]
Dialog dismissal results in an API call, thank you for the improvement 👍

**Pull request merged**
