### PR TITLE
Re-enable private by default in development, test, & wpcalypso environments

### LINKED ISSUE #32671: Purchasing eCommerce plan on an unlaunched site results in site remaining private after going AT
Originally reported and discussed in p9F6qB-33v-p2

New WPCOM simple sites are now private by default, and need to be “launched” to be made public. If this isn’t done before purchasing the eCommerce plan, this causes some issues after the site goes AT automatically upon plan purchase, as the site is still marked private in the `blog_public` status after it goes AT

As mentioned in the P2 linked above, the same types of blocks/warnings that are in place for users going AT on their own should also be put in place for sites going AT automatically after eCommerce plan purchase, including a warning about launching the site first, and what features are lost when going AT.

Steps to replicate:

1. Create a new free site and make sure to leave it as private (don’t click the launch site button under Settings > Privacy)
2. Purchase the eCommerce plan on the site, check and make sure the site went AT
3. Check the site’s privacy with option get `blog_public` in CLI and it will be set to -1 which is private

Here's what I see in Calypso immediately after going AT: https://cld.wthms.co/VQROFw
Neither privacy setting, hidden or public, is selected under Privacy settings.

On any impacted sites, the issue can be resolved by setting the site to Public under Privacy Settings in Calypso, then disconnecting and reconnecting Jetpack.

### PR DESCRIPTION
**Pull request by jblz**
IMPORTANT: When this lands, update P9HQHe-k8-p2 !

This is the "main branch" to enable the Private-by-Default (PBD) feature.

Lots of things have been merged in here:
* Revert of the revert
* Wrap in a feature flag (enabled in development & wpcalypso environments)
* Add an AB test (90% selected / 10% control)
* Sites created under a Business, eCommerce(, & any other other auto-Atomic) plans will be created as public (for now -- paObgF-pN-p2 )
* Launch site / set public when upgrading to an auto-atomic plan

See p7DVsv-6YR-p2

### To Test

* Run this branch (calypso.live should work as well)
* Browse to `/start`
* Mouse over the "environment badge"
* Mouse over `ABTESTS`
* Scroll down the list of active tests until you see `privateByDefault`
* Click the radio button for `selected`
* Create a site under any segment except for business or online-store
  * It should be unlaunched ("private by default")
* Follow the test plan in #35003 to test Upgrades
* Disable the config flag `private-by-default/non-atomic-plans` & repeat -- all sites should be created as public & no new error conditions should be achievable.

Fixes #32671

### CODE REVIEW

**Comment by jblz** [comment]
These PRs are targeting this branch and are blocking this one:
- #34888
- #32671 
- 90 / 10 split test (PR incoming)

They will be merged into this PR prior to launch.

**Comment by p-jackson** [comment]
@michaeldcain Thinking about PbD and translations. Since we’re planning to ship soon should we just be planning to roll this out to English speakers? We do have a number of copy changes.
If so then I think the `privateByDefault` test (#35007) will do the trick as is. Otherwise I might need to make some changes to it.

**Comment by p-jackson** [comment]
@jblz do we need a task to update the Site Privacy section of P9HQHe-k8-p2?

**Comment by jblz** [comment]
Seeing what's up with that spec

**Comment by jblz** [comment]
updated P9HQHe-k8-p2

**Pull request merged**
