### PR TITLE
Customizer: another attempt at a native calypso customizer

### PR DESCRIPTION
**Pull request by sirbrillig**
Builds on the work from #3855 and #4156 but uses a dedicated component route at `/paladin/:site`

This is an attempt to re-create the Customizer as a native Calypso component rather than an iframe. The resulting tool should be significantly faster than the iframe version (which has the loading time of the customizer plus the loading time of the iframe) as well as much easier to modify (since it won't be conflicting with changes to the Core customizer).

Furthermore, we'll be able to use it to experiment with and improve upon the Customizer experience (eg: content editing, home page settings) at a pace which has been unavailable when working on the core Customizer. This is basically the same reason that Calypso was first introduced.

Also also, using native calypso tools we'll be able to run the Customizer easily from the desktop app as well as re-use existing Calypso components to make the experience feel more integrated.

Finally, we can add new components that can be used in other parts of Calypso to modify site settings from places other than the Customizer.

screen shot 2016-08-05 at 5 12 50 pm

Test live: https://calypso.live/?branch=try/native-customizer

### CODE REVIEW

**Comment by sirbrillig** [comment]
Rebased to bring this back up-to-date.

**Comment by sirbrillig** [comment]
Fixed the Homepage settings.

**Comment by sirbrillig** [comment]
Refactored to make `DesignToolData` a better HOC and to rebase on master.

Current problems I'm aware of:

- [ ] Due to #5922 the `.layout` has a blur when the preview is shown, blurring the `DesignMenu`
- [ ] Every character typed into `SiteTitleControl` causes the field to lose focus.
- [ ] All JSX files need to be renamed to `.jsx`
- [ ] Images in controls still don't work.
- [ ] `HomePageSettings` is rather complex and needs some work to remove its `connect` method

**Comment by sirbrillig** [comment]
I hooked the customize route up to the global preview mode so that now it will use the preview mode's `DesignPreview` component and not have to create our own.

**Comment by sirbrillig** [comment]
Notes to self:

- [ ] clicking X in DesignPreview does not trigger "back" behavior

**Comment by melchoyce** [comment]
Test live: https://calypso.live/?branch=try/native-customizer

**Comment by melchoyce** [comment]
Some testing notes:
- Can't seem to scroll in the sidebar
- Remove margin around `webPreview` and remove border-radius
- Background behind `design-menu__header` seems to be hoverable/clickable
- Some minor style tweaks I can take care of

Some ideas:
- Remove the <— Back button from the top of the sidebar and close out of the Customizer with the X in the `webPreview` component
- Move the <— Back instead below `Site` so it's closer to the panels

**Comment by folletto** [comment]
> Can't seem to scroll in the sidebar

Confirmed (Chrome).

> Remove margin around webPreview and remove border-radius

+1

> Remove the <— Back button from the top of the sidebar and close out of the Customizer with the X in the webPreview component

I agree it would be better to consolidate to a single controller to do that.

I was thinking... Wouldn't be more intuitive to remove the `X` and make `← Back` to close it (with a change of label, likely)? This mostly because we already do that in Reader, and even in the preview when it's without the sidebar, so would be consistent.

Would be nice for example to have `← Back` when one is inside one of the sections, and it turns to either `← Close` or `× Close` when one is top-level.

(aside, there's a Core discussion to do that as well, so would be consistent with Core if that lands too).

> What if we just replaced the existing sidebar with design-menu (the Customizer menu controls)? Almost like you weren't opening up a new screen?

Wouldn't that keep the masterbar visible tho, reducing immersiveness and having a double bar at the top? (that's pretty much the only scenario where I consider covering the masterbar all right).

**Comment by melchoyce** [comment]
> I agree it would be better to consolidate to a single controller to do that.

> I was thinking... Wouldn't be more intuitive to remove the X and make ← Back to close it (with a change of label, likely)? This mostly because we already do that in Reader, and even in the preview when it's without the sidebar, so would be consistent.

> Would be nice for example to have ← Back when one is inside one of the sections, and it turns to either ← Close or × Close when one is top-level.

I thought that and then I tried it out. Having "back" above the `Site` component feels really awkward and unnatural when you're trying to go back through a section — it's just so far away that it doesn't feel connected at all.

> Wouldn't that keep the masterbar visible tho, reducing immersiveness and having a double bar at the top? (that's pretty much the only scenario where I consider covering the masterbar all right).

Yes. I'm not super worried, though — we do the same with the Editor and it doesn't feel like a problem there.

**Comment by folletto** [comment]
> I thought that and then I tried it out. Having "back" above the Site component feels really awkward and unnatural when you're trying to go back through a section — it's just so far away that it doesn't feel connected at all.

Yeah, that's a really good point.

> Yes. I'm not super worried, though — we do the same with the Editor and it doesn't feel like a problem there.

The editor doesn't have a top bar tho. :)

**Comment by sirbrillig** [comment]
Moving to #7508. This PR includes all the design tools removed from that PR (HeaderImage, HomepageSettings, SiteLogo) which should hopefully be added again later.

**Pull request closed without merging**
