### PR TITLE
composite-checkout: Add full credits payment method

### LINKED ISSUE #24448: Checkout: Allow paying with credits or a card when credits available
Currently we only allow customers to pay with credits if they have enough to cover their purchase. In testing this can create complicated circumstances and gives Automatticians an unrealistic purchase testing experience—especially when the plan is renewed. 

**Currently:**
image

It would be nice if we could change the checkout screen to look something like this if you have credits available:

image

* Customers and a12s could decide how to pay
* In testing we could get a more realistic experience without having to change how many credits we have
* We could reuse the UI for selecting a multi-year subscription

### PR DESCRIPTION
**Pull request by sirbrillig**
#### Changes proposed in this Pull Request

This adds a new payment method that allows paying for an entire purchase with credits. Partial credits payments will be handled separately. This payment method will only be included if the credits total is greater than or equal to the order total.

In order to implement this, some refactoring had to be done, which makes this PR rather unfortunately large. To make this PR easier to review, I've moved all that refactoring into its own PR #38759. 

#### New credits endpoint data

Because we're going to need to display the credit amount and also compare it to the total, the current major unit of credits we get from the shopping cart is not sufficient and I added a display and integer version in D37452-code.

#### Screenshots

Screen Shot 2020-01-09 at 2 12 14 PM

#### Testing instructions

- Run calypso with `ENABLE_FEATURES=composite-checkout-wpcom npm start`.
- Sandbox the store.
- Make sure your test account has no credits (or fewer credits than a plan cost).
- Add a plan to your cart.
- Visit checkout and verify that the "Credits" method does not appear in the first step.
- Add enough credits to your test account to cover a plan.
- Visit checkout again and verify that the "Credits" method appears, is the first payment method, and that it is selected by default.
- Complete checkout with the "Credits" payment method and verify that the payment is successful. 

Fixes #24448

### CODE REVIEW

**Comment by sirbrillig** [comment]
Fixes #24448

**Comment by fditrapani** [comment]
I also just tested this sandboxed and with existing cards on file and didn't see the credits option.

**Comment by nbloomf** [comment]
Behavior tests-

No credits: Credit payment method is not available, as expected.
Partial credits: Credit payment method is not available, but credits are applied to the total, as expected.
Full credits: Credit payment method is available. Purchase was successful, subs created, credit total updated (although not by the expected amount, see below). The checkout behavior is as expected.

Some notes:
- We still ask for billing details (postal code, country, and phone #) with full credits purchases. Do we need this for taxes? Does it add friction?
- Speaking of taxes - I paid with free credits and the taxes line in checkout said $0, but it looks like tax was taken out of my credit balance. I think this must be happening on the backend.
- This is about partial credits, but when we show the negative credit amount in the review step the negative sign should be outside the dollar sign.

image

**Comment by fditrapani** [comment]
Just took this for another spin with partial credits and looks like we're almost there with it. A couple notes (which we can deal with separately):

image


- The credits shouldn't be visible in the summary step at the top.
- Like @nbloomf mentioned, the minus should be before the currency in the review step. 
- We should omit the delete button for the credit in the review step. 

> We still ask for billing details (postal code, country, and phone #) with full credits purchases. Do we need this for taxes? Does it add friction?

If we need this for calculating taxes then we should keep it in. Similarly, if we're already using credits to pay for taxes then we should continue doing that. Also, since people can pick other payment options, then we should most likely leave it in. 

Regarding friction, I wouldn't worry about it too much because 1. We might already have this info on file and 2. since they're paying with credits, there's less friction up front, so I think it's ok.

**Comment by fditrapani** [comment]
(sorry about all the extra comments) I just tested the zero credit approach and now it's not showing for me.

**Comment by sirbrillig** [comment]
> If I have zero credits, it still shows the payment method. We shouldn't show this if you have no credits.

Thanks for noticing. I fixed this (it only happens if the cart total is also $0 but should still be covered).

> Just took this for another spin with partial credits and looks like we're almost there with it. A couple notes (which we can deal with separately)

These will be taken care of in a separate PR since the partial credits system is quite different from this payment method.

> Speaking of taxes - I paid with free credits and the taxes line in checkout said $0, but it looks like tax was taken out of my credit balance. I think this must be happening on the backend.

This is a good point. I think this is something we'll need to take care of on the backend. It _might_ be because we're submitting the location information with this payment method instead of ignoring it like our current checkout does. I added a card to figure this out later.

**Comment by sirbrillig** [comment]
> Can we update the label so it reads "WordPress.com credits: {credits}" and show the WP logo as the icon. Here's the design I put together:

Added the ability to override the label and the button text.

Screen Shot 2020-01-10 at 2 29 03 PM

Screen Shot 2020-01-10 at 2 29 32 PM

**Comment by sirbrillig** [comment]
> updating the payment method summary after you pick a domain to say WordPress.com credits

So should it read "WordPress.com Credits" or "Pay using WordPress.com Credits"?

**Pull request merged**
