### PR TITLE
Business tools redesign: Update page colors

### PR DESCRIPTION
**Pull request by epeicher**
Resolves https://github.com/Automattic/dotcom-forge/issues/9658

## Proposed Changes

* Updates the background color and link navigation colors as per designs pIiTEGIxHIzKfHv1KHOUM5-fi-3130_24771

|Before | After|
|-------|------|
| CleanShot 2024-11-11 at 16 35 12@2x| CleanShot 2024-11-11 at 16 35 02@2x |

## Why are these changes being made?

* To improve the Business Services offered as described in the parent task https://github.com/Automattic/dotcom-forge/issues/9340

## Testing Instructions

* Apply this patch and navigate to the Business Tools pages in both, the site view and the multi-sites view:
  * /marketing/tools/:siteId
  * /sites/marketing/tools/:siteId
* Make sure the style of the cards matches the designs pIiTEGIxHIzKfHv1KHOUM5-fi-3130_24771

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Comment by epeicher** [comment]
Hi @fditrapani, I tagged you as a reviewer for the design changes, but feel free to ping someone else if required. This PR also contains changes for the following  PRs:
- https://github.com/Automattic/wp-calypso/pull/96195
- https://github.com/Automattic/wp-calypso/pull/96232

This is to address the design changes required as part of https://github.com/Automattic/dotcom-forge/issues/9340

Could you please review the changes and let me know if there are any issues? Thanks! 🙌

**Review by fditrapani — APPROVED** [review]
Thanks for the updates! Looks great.

**Review by gcsecsey — APPROVED** [review]
Thanks for addressing the page colors too, @epeicher! Changes LGTM and look great when testing! 🌈

**Comment by epeicher** [comment]
Hi @gcsecsey, @fditrapani, I have identified that the change in the links colors of the navigation was impacting other screens like `purchases`. Additionally, it does not seem to be consistent with other navigations, so I have changed it back to the previous colors as part of this commit [8fc546b](https://github.com/Automattic/wp-calypso/pull/96240/commits/8fc546bed71af7bf35098fc92ca6844d82c81ad4). Do you agree with this change? Or do you think we can scope the color change only to the Marketing page

|Before | After|
|-------|------|
|  CleanShot 2024-11-12 at 10 57 19@2x |   CleanShot 2024-11-12 at 11 00 13@2x     |
| CleanShot 2024-11-12 at 10 57 24@2x   |     CleanShot 2024-11-12 at 11 00 04@2x    |




<p>I personally prefer the existing <code>--color-primary</code>

 better than the <code>--wp-admin-theme-color</code> one
</p>

**Comment by gcsecsey** [comment]
> Do you agree with this change? Or do you think we can scope the color change only to the Marketing page

I also prefer the primary color that this change introduced. image I like the more professional look this color brings to the navigation.

I tested through other pages, and I didn't find any other page this change was affecting, only the Purchases (`/purchases/subscriptions/:siteId`) page. Eg. the Plans (`/plans/:siteId`) and the Stats (`/stats/day/:siteId`) pages have similar, but visually inconsistent navigation components:

Plans navigation:
image

Stats navigation:
image

**Comment by epeicher** [comment]
> I also prefer the primary color. image 

Great, I will go ahead with this color for the navigation links as part of these changes, and we can create follow-up tasks if changes are required

**Pull request merged**
