### PR TITLE
Domains: Change signup destination to `setup-site` flow if creating a new site

### PR DESCRIPTION
**Pull request by rafaelgallani**
#### Changes proposed in this Pull Request
Redirects the user to the `setup-site` signup flow after checkout if the "New site" option was selected on the "Choose how to use your domain" step.
This PR is a part of the domain-only flow redesign described in g1kxLPDmNsSHje0aA2Qjme-fi-728%3A3920.

#### Testing instructions
- Browse to `/start/domain`;
- Try to use any available domain on the search step;
- Select the "New site" option on the "Choose how to use your domain" step;
- Select any theme and plan from the next steps;
- Confirm that after checking out you'll get redirected to the `setup-site` flow (Intent capture - "Where will you start?" page)

### CODE REVIEW

**Comment by gius80** [comment]
SUPER! It was actually easier than I thought :)

There is only thing, but this is my fault, I forget to mention it in the task but we should remove the `theme` step.

**Review by leonardost — COMMENTED** [review]
The code LGTM, but I'm consistently getting a WSOD after I select "New site" in the "Choose how to use your domain" step 🤔 this doesn't happen in production. It might be something weird with my cache or environment, but I tried cleaning all application data and testing in an incognito session, but no dice 😞 also no error is shown in the console. Does it run correctly for you @rafaelgalani?

**Comment by gius80** [comment]
> The code LGTM, but I'm consistently getting a WSOD after I select "New site" in the "Choose how to use your domain" step 🤔 this doesn't happen in production. It might be something weird with my cache or environment, but I tried cleaning all application data and testing in an incognito session, but no dice 😞 also no error is shown in the console. Does it run correctly for you @rafaelgalani?

I have the same issue but should be easy fixable

_client/signup/steps/site-or-domain/index.jsx - line 204_ 

`goToStep( 'themes' );`

should be replaced with this one

`goToStep( 'plans-site-selected' );`

There is something else btw, because after that fix now is stuck on "Preparing you domain"... (I suppose because we should pass a theme?)

**Comment by rafaelgalani** [comment]
> Does it run correctly for you @rafaelgalani?

@leonardost It does - when building locally. 
I can confirm that the same happens for me when I use the live link. Huh... 🤔 I have no idea why. I'll need to further investigate this one...

**Comment by rafaelgalani** [comment]
> `goToStep( 'plans-site-selected' );`

@gius80 I think you meant `themes-site-selected` instead, right? 
In this case, the reason why it won't load is that the function used on its callback (`setThemeOnSite`), expects an already existing site - which is not our case since we're creating a new one. 
There are a few comments just above it explaining it better than I am 😸: 

https://github.com/Automattic/wp-calypso/blob/1facd78d13cd77ad5a3ab250576c2437b94de063/client/signup/config/steps-pure.js#L81-L84

**Comment by rafaelgalani** [comment]
Well... 🤔 
That's odd. This is what I get after clicking the "New site" option in the live link: 

image

And this is what I get when doing it locally:

image

It looks like the component still has the previous props - or it's not being updated/rerendered correctly. I'll try rebasing to `trunk` - thus forcing a build - and see how it goes.

**Comment by rafaelgallani** [comment]
Thanks for the input @leonardost and @gius80!

> > The code LGTM, but I'm consistently getting a WSOD after I select "New site" in the "Choose how to use your domain" step 🤔 this doesn't happen in production. It might be something weird with my cache or environment, but I tried cleaning all application data and testing in an incognito session, but no dice 😞 also no error is shown in the console. Does it run correctly for you @rafaelgalani?
> 
> I have the same issue but should be easy fixable
> 
> _client/signup/steps/site-or-domain/index.jsx - line 204_
> 
> `goToStep( 'themes' );`
> 
> should be replaced with this one
> 
> `goToStep( 'plans-site-selected' );`
> 
> There is something else btw, because after that fix now is stuck on "Preparing you domain"... (I suppose because we should pass a theme?)

@gius80 You're right, my bad. After this last commit, I forgot to change the step redirection when clicking. 
And yes! We should pass a theme - the same way as we currently do on the "Existing WordPress.com site" option (`site-picker` step):
https://github.com/Automattic/wp-calypso/blob/f77a0942fb45b5af4ef3f84351bcd6fc18e60e65/client/signup/steps/site-picker/site-picker-submit.jsx#L24-L27

**Review by gius80 — APPROVED** [review]
I tested again and everything now works as expected! Thanks, ready to ship 🚢

**Pull request merged**
