### PR TITLE
VideoPress Tailored Onboarding: Improve User Account Creation Styling

### PR DESCRIPTION
**Pull request by roundhill**
#### Proposed Changes

* Updates the user account creation screen styles to match the `is-horizontal` styles we have in the other onboarding flows:

Screenshot 2022-11-18 at 12 21 02 PM

Screenshot 2022-11-18 at 12 20 51 PM

#### Testing Instructions

* In an incognito window visit `/setup/videopress`.
* Click `Get started`.
* Verify new styling matches design and form navigation works as expected.
* Test signup up all the way through to creating a Videomaker site.

#### Pre-merge Checklist

- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

**Comment by evilluendas** [comment]
Looks good! The field itself is slightly different to the ones we show in following steps, though, for example in terms of animation or border-radius:

https://user-images.githubusercontent.com/820374/202535552-9f16e6a1-72f0-4114-a3ac-54ec459a9a03.mov

vs.

https://user-images.githubusercontent.com/820374/202535373-845b2b5a-e16f-414b-ba48-3f8781fa3df6.mov

I wonder if we could adjust the selectors so the styling from the other steps is applied here too? Things that I've noticed are the border-radius, the transition, the height (these are 40px tall vs. 44px from the others), and even the font (these use Inter, vs the others using SF/system fonts).

**Review by jgcaruso — APPROVED** [review]
Signup page displays the vertical or horizontal layout appropriately for the given page size.

| vertical | horizontal |
|---------|----------|
| Screenshot 2022-11-21 at 11 38 31 AM | Screenshot 2022-11-21 at 11 38 36 AM |


Signup flow still works as expected

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/7633819

Thank you @roundhill for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/7633819).

**Pull request merged**
