### PR TITLE
Stats: Update how SVG is included on Stats purchase page

### PR DESCRIPTION
**Pull request by grzegorz-cp**
Related to #80269

## Proposed Changes

* removing SVG from JS to a separate file to reduce JS file size

## Testing Instructions

* navigate to a live branch and go to `/stats/purchase/:siteSlug`
* verify that SVG on the right side looks the same on the live branch and in production
* verify that the `new features` icon updates properly when selecting the free plan
* verify that commercial plan has celebration SVG on top of the regular one

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

**Review by kangzj — APPROVED** [review]
It works well and looks good 👍 Nice refactoring, which would reduce size of the purchase page by ~20% 🎉 . 

One nitty pick is that in Chrome, the celebration dots show up with a latency, but I don't think it's a blocker or we need to resolve it in the near feature. It'll be good to explore if curious tho.

https://github.com/Automattic/wp-calypso/assets/1425433/a5a636e9-9ca0-4ef1-a441-14c32f772506

The text and the celebration dots are rendered in two frames as inspected from the performance tab in dev tools.

Again the observation is not a priority to resolve as it only happens in Chrome and doesn't really hurt user experience.

**Review by jsnmoon — APPROVED** [review]
Amazing what a little `<use>` tag can do. Great work!

One subtle regression I noticed (and can be addressed in a future PR) is that the box shadow appears to have been removed with this change. This is most noticeable on the bottom left corner of the card, where the shadow adds depth to distinguish the card from the background:

Before|After
-|-
SCR-20230807-lio|SCR-20230807-lif

It's subtle and only noticeable when switching between staging and the live branch.

**Comment by grzegorz-cp** [comment]
Thanks for the reviews.
@jsnmoon Can you check again if the shadow is removed? Your screenshots probably got switched because 'after' shows the drop-shadow effect.
When I tested it on the live branch the shadow looked a bit darker compared to prod but both use the same values. To change that I would have to manipulate SVG filter values.

**Comment by grzegorz-cp** [comment]
This is how the shadows look for me

| Production | Proposed PR |
| --- | --- |
| SCR-20230808-lytu | SCR-20230808-lvud |

@ederrengifo would you like me to adjust the values and make the shadow lighter?

**Comment by jsnmoon** [comment]
> Your screenshots probably got switched because 'after' shows the drop-shadow effect.

Aha, good catch.

>  @jsnmoon Can you check again if the shadow is removed?

Everything works as expected on Chrome, but the shadows are still missing in Firefox on the live branch:

> image
 
Also, I discovered an unfortunate regression in Safari where the card goes missing altogether (which renders properly on production):

> SCR-20230808-cfo

**Comment by grzegorz-cp** [comment]
I fixed the shadow in Firefox and the visibility of the main element in Safari, but Safari is still missing the shadow like Firefox before.

**Review by jsnmoon — APPROVED** [review]
Let's ship and iterate. Could you note the missing shadow bug in Safari in a new issue? 👍

**Review by kangzj — APPROVED** [review]
Great job figuring that out. Let's merge and improve. 

Filed a bug for the Safari issue: https://github.com/Automattic/wp-calypso/issues/80470

**Pull request merged**
