### PR TITLE
Show edit CSS link if FSE is active and site has CSS customization plan

### LINKED ISSUE #35451: FSE: We need a link to Custom CSS in the customizer [3]
From Josh Ruud:

We help users with custom CSS on a daily basis. While FSE will bring a lot of flexibility to customizations, it would be great for folks to be able to self-serve CSS and have an easy access link for us to help them with it.

> I want to make my site title bigger

### PR DESCRIPTION
**Pull request by noahtallen**
We want this placeholder in place so that support folks can easily direct people to edit the CSS for their site while we work on getting a full fledged CSS customizer page up for FSE that doesn't rely on the customizer.

#### Changes proposed in this Pull Request
Add a link under the themes item to edit CSS if FSE is enabled and the site plan supports it.

#### Testing instructions
1. Load this PR into your local Calypso environment. You'll need to test this on a few different sites.
2. On a site on a **free** plan with FSE enabled, make sure that there is no link other than themes in this area:
Screen Shot 2019-08-22 at 4 36 06 PM

3. On a site on a **premium or higher** plan with FSE enabled, make sure that there is a link to "Edit CSS"  under the themes option. When you click this item, it should open the customizer and **automatically open the customize CSS panel**.
Screen Shot 2019-08-22 at 4 36 34 PM
Screen Shot 2019-08-22 at 3 35 36 PM

4. On a site without FSE, make sure that there is a link to the customizer above the themes item which takes you to the customizer without opening the CSS panel.
Screen Shot 2019-08-22 at 3 33 45 PM

Fixes #35451

### CODE REVIEW

**Comment by gwwar** [comment]
Going to summon @shaunandrews @apeatling  for 👀 on the sidebar change. We'll also want to give folks an explicit heads up for sidebar changes before this is visible by users.

**Comment by shaunandrews** [comment]
I'm a little apprehensive about this change, but I think it makes a lot of sense when you consider we advertise "Custom CSS" as a feature of many of our plans. As-is I think it makes the customizer a one-use tool, which might be ok for our purposes — but I worry that people might accidentally get lost in the Customizer by clicking on the back arrow.

**Comment by noahtallen** [comment]
Definitely agree with that, Shaun! I think the goal is to integrate a full edit CSS thing into FSE in the near future, but it’s a much more complicated task than this. I think the goal would be for this to tide us over until the bigger project happens.

**Comment by apeatling** [comment]
Yes, agreed there is the potential that folks get lost in the customizer with this, however, I think it's a necessary evil until we have a custom CSS extension available.

**Comment by noahtallen** [comment]
I think since we're planning on tackling that a couple sprints out, we'd probably still need it once we do a proper edit CSS thing in FSE (since at that point, we'd get rid of this link, I'd assume).

**Comment by gwwar** [comment]
What did folks think of keeping the customizer link, but redirecting to the page editor when full site editing flows are available ([#](https://github.com/Automattic/wp-calypso/issues/35418#issuecomment-522668419)? If feels a little odd to put Edit CSS as top level, but then folks end up searching how to get back to the page editor.

**Comment by noahtallen** [comment]
That'd be simple to add here as long as I wasn't updating it in a lot of other places. Do you think it would be worth changing the `getCustomizerUrl` function to return the home page block editor URL if FSE is enabled?

**Comment by Copons** [comment]
As a stop-gap this is probably good enough, but I'm not really a fan of exposing the entire Customizer here.
There are a lot of features that wouldn't be available with FSE: maybe custom fonts and colors _could_ still work, but what about the widget areas that our themes register and that we don't use at all? Should we conditionally register them only if FSE is disabled?

**Comment by Copons** [comment]
> @Copons If you can find a way to limit the exposure to the rest of the customizer, I'm all for that.

I'm not familiar with the Customizer, but I don't think there's an easy way. 🤔 
My first thought was to hide the back button so that folks landing on the Custom CSS tab couldn't navigate back to the main menu, but then there are all the active areas in the preview (e.g. the Edit button on the site title) that would end up navigating around all the same.

**Comment by glendaviesnz** [comment]
@noahtallen @apeatling I just tested this and the flows mentioned work perfectly for me. I came across an alternative flow accidentally, and not sure if we need to worry about it or not - suspecting not at this stage:

If an FSE site does not have a static front page then the default customizer link still shows, this is because the fse detection relies on 
```
    const isActive = get( site, 'is_fse_active', false );
    return isActive && hasStaticFrontPage( state, siteId );
```
Obviously going through the standard signup flow the static front page will be true, but if the user switches to non-fse theme they could end up with a non static home page but then switch back to an fse theme - I suspect this is an edge case we can deal with later, but just checking.

**Comment by noahtallen** [comment]
Could someone summarize what the next steps are? :D Not sure what all I'm supposed to change at this point :)

**Comment by apeatling** [comment]
Yes, I’ll open a new issue. I think we can probably close this out.

**Comment by apeatling** [comment]
Actually, you may want to modify what you have, so I'll open a new issue and leave this open and you can decide what to do :)

**Comment by apeatling** [comment]
New issue: https://github.com/Automattic/wp-calypso/issues/35851

**Comment by noahtallen** [comment]
I'll close this since none of the existing work will be directly used for the new issue.

**Pull request closed without merging**
