### PR TITLE
Fix/reader discover unbound callbacks

### PR DESCRIPTION
**Pull request by jhnstn**
This removes unbound callbacks in the `DiscoverSiteAttribution` component and removes unused `DiscoverPostAttribution`.

**Testing**
1. Enable analytics logging in the dev console:  `localStorage.setItem( 'debug','calypso:analytics:*' )`
2. visit `http://calypso.localhost:3000/discover`
3. Click the title of any post in discover stream
4. On the full post view click `visit {some site}` :
screen shot 2017-05-16 at 1 55 16 pm

5 The event `calypso_reader_site_on_discover_card_clicked` should be logged to the console
6. Click back to the full post view
7. Click the follow/unfollow button for the source post:
screen shot 2017-05-16 at 1 55 16 pm
8. The events `calypso_reader_site_followed` or `calypso_reader_site_unfollowed` should fire depending on the following state of the source post

Fix for : #14133 and #14132

### CODE REVIEW

**Comment by samouri** [comment]
looking now

**Comment by samouri** [comment]
both `calypso_reader_discover_site_unfollowed` and `calypso_reader_site_unfollowed` were fired, not just one. I figure thats fine though?

I followed the super easy to understand testing instructions and everything LGTM.

**Comment by jhnstn** [comment]
thanks @samouri !

**Comment by jhnstn** [comment]
> both calypso_reader_discover_site_unfollowed and calypso_reader_site_unfollowed were fired, not just one. I figure thats fine though?

Yeah that happens when debug logging any tracks event. I'm pretty sure only one track event is sent however.

**Comment by samouri** [comment]
don't merge just yet. i'm seeing some weird behavior locally actually.  might just be a freak incident, investigating now

**Comment by jhnstn** [comment]
eek! I merged as your comment showed up. reverting

**Comment by samouri** [comment]
all is well 👍

**Comment by umurkontaci** [comment]
Thanks for getting this fixed quickly! 👍

**Pull request merged**
