### PR TITLE
Add Related Plugins page

### LINKED ISSUE #80289: Marketplace: Related Plugins page
Create a new page to display the related plugins from a given plugin.

- [x] Create a new route. Ex: `/plugins/:plugin_slug/related/:site`
- [x] Display the related plugins in this new route. The layout can be similar to the bottom part of the Category page.
- [x] Display the related plugins from #80287

CleanShot 2023-08-07 at 17 19 45@2x

Related to #63717

### PR DESCRIPTION
**Pull request by gcsecsey**
Closes #80289

## Proposed Changes

- create a new route: `/plugins/:plugin/related/:siteId`
- display related plugins on the new route, similarly to the category pages
- use the related plugins data from #80287
- reuse the `normalizePluginData` function to map fields from ES result, related diff: D121300-code

## Testing Instructions

* Apply the diff D121300-code to your sandbox
* Visit `/plugins/:plugin/related` with any plugin (eg. `woocommerce`)
* Check that the plugin cards contain all the necessary information, and clicking them redirect to the plugin pages
  CleanShot 2023-09-12 at 10 27 28@2x
* Check that the related plugins component doesn't have any regressions (on the plugin details pages)
* Check that clicking the `See all` link on the related plugins component redirect to the related plugins page
  CleanShot 2023-09-12 at 10 28 27@2x

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

**Comment by gcsecsey** [comment]
This PR currently displays a fixed number (20) of results. The WPCOM changes in D121300-code add the from parameter to the backend, which lets us paginate the results. I'm working on a revision that updates the query to be infinite, similarly to how it's implemented on the search results pages.

**Comment by gcsecsey** [comment]
> This PR currently displays a fixed number (20) of results. The WPCOM changes in D121300-code add the from parameter to the backend, which lets us paginate the results. I'm working on a revision that updates the query to be infinite, similarly to how it's implemented on the search results pages.

Having investigated this a bit, I think it'd be best tackle adding pagination in a follow-up PR. It requires changes in WPCOM (adding the total results to the response), and will further change the response schema.

**Review by WBerredo — CHANGES_REQUESTED** [review]
I was not able to use the multi-site view of this page. When trying to access this URL with no site select a see a blank screen.

---

Also there is a space between the top and the title that makes it looks a bit weird.

CleanShot 2023-09-12 at 14 22 10@2x

**Review by WBerredo — APPROVED** [review]
LGTM!

**Pull request merged**
