### PR TITLE
Github Deployments: Update the layout

### PR DESCRIPTION
**Pull request by arthur791004**
Related to https://github.com/Automattic/dotcom-forge/issues/7139

## Proposed Changes

* Update the layout of the Github Deployments card

| Before | After |
| - | - |
| image | image |
| image | image |
| image | image |

## Testing Instructions

* Go to /sites
* Select any atomic site
* Switch to the Deployments tab
* Make sure the layout of the Deployments card looks good

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Review by candy02058912 — COMMENTED** [review]
Desktop version looks good to me.

For the mobile view, could we move the "Pick your deployment mode"
to below the "Connect a repository" section?

mobile

**Comment by taipeicoder** [comment]
The back button is still inside the header when editing a connected repository:
Screenshot 2024-06-11 at 4 18 08 PM

Screenshot 2024-06-11 at 4 19 35 PM

**Comment by arthur791004** [comment]
> For the mobile view, could we move the "Pick your deployment mode" to below the "Connect a repository" section?

Addressed by https://github.com/Automattic/wp-calypso/pull/91666/commits/a65091868b6573767e7604435f9bf26b1a0a083c

> The back button is still inside the header when editing a connected repository

Addressed by https://github.com/Automattic/wp-calypso/pull/91666/commits/119e625a0b42103975b6f38c7db65d626553598a

**Comment by taipeicoder** [comment]
The back button in Deployment runs is still inside the header, you can access it via clicking the Deployed button
Screenshot 2024-06-11 at 6 32 31 PM

Screenshot 2024-06-11 at 6 32 49 PM

---

The vertically stacked UI can be hard to read, can we make the gap a bit larger?

Currently:
Screenshot 2024-06-11 at 6 31 24 PM

Suggestion:
Screenshot 2024-06-11 at 6 35 00 PM

**Review by fushar — COMMENTED** [review]
While we're here, and the Back button is extracted outside can we update it so that it uses `<HostingCard/>` component? This is one of the remaining tabs (besides Staging Sites) that still do not use it yet.

The benefit is that the styles will be automatically consistent with all tabs.

Something like:

```
<HostingCard>
  <div ...>
    <HostingCardHeading title="Connect a repository">
    ...
  </div>
  <div ...>
    <HostingCardHeading title="Pick your deployment mode">
    ...
  </div>
</HostingCard>
```

What do you think?

**Comment by taipeicoder** [comment]
This can be addressed in a follow-up PR since it's an existing production issue, the Deployments table overflows horizontally. I expected only the table itself to scroll, not the UI components above as well 😅

Screenshot 2024-06-12 at 11 47 08 AM

**Comment by arthur791004** [comment]
> The vertically stacked UI can be hard to read, can we make the gap a bit larger?

Increased to 32px by https://github.com/Automattic/wp-calypso/pull/91666/commits/5ba692347d80c21bacdf4668590587f35c58ec83. It looks weird if it's too large 😅

image

> While we're here, and the Back button is extracted outside can we update it so that it uses <HostingCard/> component? This is one of the remaining tabs (besides Staging Sites) that still do not use it yet.

Addressed it by https://github.com/Automattic/wp-calypso/pull/91666/commits/df489fc733b33f1308232fa63b9c8ce512cd30a3 🙂

**Comment by fushar** [comment]
Can we rebase this PR so that it picks up the latest styles from https://github.com/Automattic/wp-calypso/pull/91684?

> The back button in Deployment runs is still inside the header

This is still not addressed (just wanted to make sure it is not missed) 😄

**Comment by arthur791004** [comment]
> Can we rebase this PR so that it picks up the latest styles from https://github.com/Automattic/wp-calypso/pull/91684?

Done!

> The back button in Deployment runs is still inside the header

Oops...I found I misunderstood this one. Fixed by https://github.com/Automattic/wp-calypso/pull/91666/commits/a90430f881a3d1bb58fb4fb3b1ce9d199242605f

image

**Review by fushar — APPROVED** [review]
It looks good to me 👍

**Review by taipeicoder — APPROVED** [review]
Nice improvement 🎉

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/14522657

Some locales (Hebrew, Japanese) have been temporarily machine-translated due to translator availability. All other translations are usually ready within a few days. Untranslated and machine-translated strings will be sent for translation next Monday and are expected to be completed by the following Friday.

Thank you @arthur791004 for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/14522657).

**Pull request merged**
