### PR TITLE
Illustrations: Update Colours to the New Palette

### PR DESCRIPTION
**Pull request by Aurorum**
#### Changes proposed in this Pull Request

This PR proposes updating all the blue and grey shades of the illustrations to the new colour palette, added in #35949.

#### Testing instructions

In theory, this should be fairly simple change as it only touches SVGs (with two `.jsx` file exceptions - the themeheader, which was outdated, and one SVG in the .jsx file). But unfortunately, I think it's a bit more complex since I've not checked the images in context. I don't think that should be too major though as I've kept the shades consistent. Also, the SVGs would also probably need to be migrated to Webpack, but I don't intend to address that in this PR; that's probably something that should be addressed slowly through several separate PRs in the future. So basically, this is just very similar to #30248.

Here's an example.

**Before:**

Screenshot 2019-10-03 at 22 36 34

**After:**

Screenshot 2019-10-04 at 13 49 11

I reckon the best thing to do to test this PR is to just browse around. Here's where (I think) the most illustrations are located on a single page: 

Screenshot 2019-10-04 at 13 52 22

cc @porada, @sixhours, @davewhitley

### CODE REVIEW

**Comment by davewhitley** [comment]
Colors look great!

**Comment by porada** [comment]
Wow. Thanks for the contribution, @Aurorum!

Is there any chance you handled some of those SVGs automatically? I’m asking, because I think they may need some additional tweaks:

1. Since the illustrations are a part of WordPress.com’s visual identity, they should be using [WordPress Blue](https://color-studio.blog/#wordpress-blue) accents instead of Blue, just like the masterbar.
1. Gray has become darker (compared to the previous palette version) and started dominating parts of the images that were supposed to be dimmed. This one may be subjective and could also depend on the context, so I’d tackle 1️⃣ first and then move to 2️⃣ if need be.

If you happened to update those using a script, I’d love if you could also open a separate PR with it. As you probably noticed, we’ve been iterating on the palette itself, so not having to update those images manually would be a meaningful improvement to our workflow.

[🍻](https://automattic.com/work-with-us/)

**Comment by Aurorum** [comment]
> Is there any chance you handled some of those SVGs automatically?

All of them. :) Not really with a script though, I just ran the following for each of the values to update them (I found it online a while ago, it's the only thing that's ever worked for me): 

`git grep -l 'old' | xargs sed -i '' -e 's/old/new/g'
`

It's not a perfect solution, but running it twenty times with a bit of modification each time took me about an hour, so definitely not as long as having to do each one manually.

> Since the illustrations are a part of WordPress.com’s visual identity, they should be using WordPress Blue accents instead of Blue, just like the masterbar.

Updated!

**Before:**
Screenshot 2019-10-03 at 22 36 40

**After:**
Screenshot 2019-10-04 at 13 49 11

> Gray has become darker (compared to the previous palette version) and started dominating parts of the images that were supposed to be dimmed.

Hmm, true. I suppose that the easiest solution would probably be switching the values a bit, so that what's currently `studio-gray-5` in this PR is updated to become `studio-gray-0`. Would that be better?

**Comment by porada** [comment]
Thanks for the update! I’ve reviewed all the updated images and realized some of the non-ideal color combos had actually been introduced earlier, so they’re good to go for the most part.

> Update Blues and Greys to New Palette

While this PR already moves us far ahead in the right direction, I’d rather we didn’t update the illustrations selectively. I’d love if we could filter out all the non-standard color values in _all_ SVG files in the repo and update them to the most recent Color Studio values. I can help with this part and make a list if you’d prefer that.

The very first offender is the green that appears in Jetpack-related images. Those instances should be updated to [Jetpack Green](https://color-studio.blog/#jetpack-green). 🙂

**Comment by porada** [comment]
One more piece of explanation:

> (…) some of the non-ideal color combos had actually been introduced earlier, so they’re good to go for the most part.

There’s a chance that we might be tightening the illustration guidelines soon, so we’ll address any potential changes accordingly in a new PR (after this one has been merged). Even though I said _non-ideal,_ these color updates are tangibly improving the overall consistency of our system, so they’re more than welcome. 🚀

**Comment by Aurorum** [comment]
Thanks @porada, I'll update the others!

> The very first offender is the green that appears in Jetpack-related images. Those instances should be updated to Jetpack Green

Which version of Colour Studio is Jetpack Green is being used from currently? I've tried looking around, but I can't seem to track it down.

**Comment by porada** [comment]
I can see how that may be confusing. I suspect the green values used in those illustrations might not have been standardized anywhere.

If that’s okay, I’ll run a script and provide a list of color values to replace.

**Comment by Aurorum** [comment]
That'd be great! :)

**Comment by porada** [comment]
Could you try copy-pasting the `bin` script from #36591 and running in on your current branch? It has one dependency, so you may have to `npm install chroma-js`, too.

Running `./bin/audits-svg-colors.js --list` will get you the list of all colors that need to be updated. The script itself doesn’t perform any replacements yet.

**Comment by porada** [comment]
What happens if you try the following?

```
chmod +x ./bin/audit-svg-colors.js
```

**Comment by Aurorum** [comment]
Thanks @porada, the script is super helpful! I've got it working and I've added another round of colour updates. Just need to resolve the conflicts now. :)

**Comment by porada** [comment]
Thanks for another round of updates and for you patience on this.

I’m still reviewing all the changes, but here’s what I noticed so far (or missed earlier):

* The color scheme thumbnails accidentally got converted to the subset of palette colors whitelisted for in illustration use. They should be able to use a full spectrum of palette colors instead to accurately represent the schemes, so their changes should be removed. That’s a mistake on my part which I already quick-fixed in #36591. It’s a good reminder to always manually check things after running a script like that. 🙂
* Regarding the JSX updates, I’d rather we avoided using hardcoded values. Those can get easily overlooked and the script doesn’t handle those either. [Here’s an example](https://github.com/Automattic/wp-calypso/blob/master/client/blocks/login/two-factor-authentication/push-notification-illustration.jsx) of I used color in one of the existing examples. That way, they’ll never get silently outdated.

**Comment by Aurorum** [comment]
Will update this PR tomorrow to address both of those! :)

Just out of curiosity though, is there an argument against moving the SVGs in the `.jsx` files into actual `.svg` files? It does seem odd for that to be the norm for all files, except around a dozen.

**Comment by porada** [comment]
I’d say the lack of accessible file preview is the primary reason for that. But if the color schemes take off or we eventually introduce a proper dark mode, that might be the direction to take.

**Comment by Aurorum** [comment]
Sorry, just to clarify, other way round: there's about a dozen SVGs inside `.jsx` files, like [here](https://github.com/Automattic/wp-calypso/blob/8f2d0dba92eb77ac6e8f048ba9b2724196923ec8/client/signup/steps/clone-start/index.jsx#L50-L130). Any reason why not to move them into actual SVG files?

**Comment by porada** [comment]
Yep, looks like I misread your question, but I don’t have a good answer anyway. I guess that’s another area for improvement. 🙂

**Comment by Aurorum** [comment]
> Will update this PR tomorrow to address both of those! :)

Just looping back here quickly to note that I probably won't have the `.jsx` files updated today, most likely the weekend instead. Reverted the changes to the colour scheme images though.

**Comment by porada** [comment]
That’s okay. But in that case, I’d suggest we focus on SVG image files only here. Once we’re done, we can move onto another PR focusing on `jsx` updates. How does that sound? 🙂

**Comment by porada** [comment]
I can still see the color scheme thumbnails in the diff due to differences in trailing whitespace. Any chance you could also clean up the branch?

**Comment by Aurorum** [comment]
Done! :)

I've updated this PR now to only touch `.svg` files. That leaves for future PRs:

1. Migrating the SVGs to Webpack (necessary, but probably quite a slow process that will take multiple PRs)
2. Updating the SVGs inside `.jsx` files (I haven't yet investigated if it's worth moving them into a separate `.svg` file, or if there's a reason why not to)
3. Updating some of the other colours, like in `components/head`, to directly import from the palette to make future maintenance either

**Comment by porada** [comment]
I’m sorry for the lag. Looks like the comment I wrote last week didn’t get posted here for some reason, so I had to re-review the changes.

---

We’re super close to being done with this PR, but I noticed a couple of issues after the last round of updates. My suggestion is that you remove the updates to the following SVGs completely (including whitespace conversion 🙂) and I’ll fix them over at #36591 along with the script.

* The disabled credit card logos got a little quirky due to the way the SVG files are structured. The regular versions shouldn’t be colorized at all.

```
static/images/upgrades/cc-*.svg
(except for cc-cvv-back.svg, cc-cvv-front.svg, and cc-placeholder.svg) 

static/images/upgrades/emergent-paywall.svg
static/images/upgrades/netbanking.svg
static/images/upgrades/paypal-disabled.svg
```

* Plan images had already been correctly updated.

```
static/images/plans/**/*.svg
```

* The following images either received quirky updates or need more manual work.

```
static/images/google-vouchers/google-voucher.svg
static/images/jetpack/jetpack-manage.svg 
```

* These two images require a single manual substitution before they’re ready to be merged. Feel free to either reset them or perform the updates.

```
static/images/jetpack/install-wp-admin.svg
#9dd977 → #2fb41f (just the hero section which is one of the two occurrences)

static/images/people/mystery-person.svg
#bedae6 → #dcdcde
```

🤞🤞

**Comment by Aurorum** [comment]
Thanks for your patience with this! 

I've removed all updates to all those SVGs (especially big yikes at the `static/images/jetpack/jetpack-manage.svg` one 😅) except for the last two on that list, where I've made the manual changes you suggested. :)

**Comment by porada** [comment]
Perfect, thank you! All good now. Merging soon.

**Pull request merged**
