### PR TITLE
Try out webpack3 with shaking and hoisting

### PR DESCRIPTION
**Pull request by blowery**
Things that need to doing:

- [x] Bump dependency for webpack and friends
- [x] Bump dep for babel-preset-es2015 so we can use `{ useModules: false }` to let webpack deal with es6 modules and use tree shaking and scope hoisting
- [x] Add the module concat plugin to turn on scope hoisting
- [ ] Upgrade all of our modules to ES6

### CODE REVIEW

**Comment by blowery** [comment]
One complication so far: ideally we'll bump `server/config/index.js` to es6, but we can't easily do that until node supports es6 modules since it's included from the webpack configs. So we probably need a special base config module in CommonJS format that server/config pulls in via `require` and uses?

**Comment by gziolo** [comment]
@blowery, we could also start using Babel for Webpack config. We would run transpilation when generating production files so it shouldn't be a blocker to use babel-node there. Unless it performs really badly. I played with that before and it was even possible to enable Babel for webpack config directly with changing the file name. See https://github.com/webpack/webpack/issues/1403.

**Comment by blowery** [comment]
> I played with that before and it was even possible to enable Babel for webpack config directly with changing the file name. See webpack/webpack#1403.

*mindblown*

**Comment by apeatling** [comment]
@blowery What do you need help with? Is this one important to get over the line?

**Comment by blowery** [comment]
closing in favor of the work @samouri is doing

**Pull request closed without merging**
