### PR TITLE
Adjust masterbar icon differences between calypso and classic

### PR DESCRIPTION
**Pull request by xavier-lc**
Fixes https://github.com/Automattic/dotcom-forge/issues/8293

## Proposed Changes

* Adjust padding and sizing on the masterbar icons so they look the same as wp-admin does

## Testing Instructions

* Open the live preview
* Compare the masterbar icons with those on wp-admin, the size and spacing should look the same

|Before|After|
|---|---|
|image|image|

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Comment by mmtr** [comment]
Nice! The icons are now the same across Calypso and WP Admin.

I noted that the notifications icon is still different. Is this intentional?

Calypso | WP Admin
--- | ---
Screenshot 2024-07-17 at 12 50 34 | Screenshot 2024-07-17 at 12 50 29

**Comment by xavier-lc** [comment]
> I noted that the notifications icon is still different. Is this intentional?

Oops, I missed it. Addressed on https://github.com/Automattic/wp-calypso/pull/92744/commits/6a682ffa76b028b560b70bcc60c05a5bf1a960f0. Thanks!

**Comment by mmtr** [comment]
> > I noted that the notifications icon is still different. Is this intentional?
> 
> Oops, I missed it. Addressed on [6a682ff](https://github.com/Automattic/wp-calypso/commit/6a682ffa76b028b560b70bcc60c05a5bf1a960f0). Thanks!

I still see different icons 🤔

**Review by mmtr — APPROVED** [review]
LGTM 🚀

**Pull request merged**
