### PR TITLE
Add @automattic/subscriber package

### PR DESCRIPTION
**Pull request by bogiii**
#### Proposed Changes

Since [the main PR](https://github.com/Automattic/wp-calypso/pull/65878) for introducing Subscriber importer contains a lot of changes which is a bit hard to review, I've decided to divide it into smaller PRs.

- the first one is the introduction of subscriber data-store | https://github.com/Automattic/wp-calypso/pull/66932
- and this one which is `@automattic/subscriber` package, branched out from the PR above since it depends on subscriber data-store

This PR contains implementation without any integration, but besides the codebase, you can test the `Add Subscribers form` from [the main PR](https://github.com/Automattic/wp-calypso/pull/65878). The package code is the same.

#### Testing Instructions

See https://github.com/Automattic/wp-calypso/pull/65878

#### Screenshots
Screenshot 2022-08-25 at 15 31 34
Screenshot 2022-08-25 at 15 31 51
Screenshot 2022-08-25 at 15 32 08

#### Pre-merge Checklist

- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [x] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [x] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?

Related to #

### CODE REVIEW

**Comment by zaerl** [comment]
I've tested `AddSubscriberForm` through https://github.com/Automattic/wp-calypso/pull/65878/files#diff-45b3c27086d098b105fa7c0536db6a56c95df7bb2ffb9a4d0e002c857392ddf4R126 and it seems ok. Maybe we should check if `siteId` is defined otherwise we have an invalid URL with `/undefined/`. But this is outside the scope of this PR.

**Review by zaerl — APPROVED** [review]
It's ok.

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/7495325

Thank you @bogiii for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/7495325).

**Pull request merged**
