### PR TITLE
Site Migration: Key retrieval UI

### LINKED ISSUE #87393: Site Migration: Migration plugin instructions
**Note: This should be behind the `onboarding/new-migration-flow` flag.**

More context: paYKcK-41n-p2

Once plugin installation and Atomic migration is complete (see #87392), we'll want to take them to an instruction page which shows the user:

1. How to install the migration plugin on the source site.
2. What to do once the plugin is installed.
3. The migration key so it's easy to copy.

## Page Copy

We're going to need to write a decent amount of copy for this page. I've opened a Google Doc (search for 'Site Migration Instructions Copy') where we can write/discuss/edit the copy.

The goal for i1 is to just have step-by-step text instructions and maybe some links to the source and destination sites. We'll try and make things like the migration key, etc more automated as we have time.

### PR DESCRIPTION
**Pull request by markbiek**
Fixes #87393

## Proposed Changes

Updates site migration instructions for key retrieval
    
When the user first lands on the page, there is a "Get migration key" button. Clicking the button retrieves the key from the API and displays it (hidden) along with "Show key" and "Copy key" buttons.
    
In the event that there's an API error (either because of a lack of permissions or the key has already been retrieved), we show instructions and a link for manually retrieving the key instead.

## Testing Instructions

* Either checkout this branch locally or use the calypso.live url.
* Visit http://calypso.localhost:3000/start
* Go through the setup flow, picking any plan.
* On the "Goals" step, add `&flags=onboarding/new-migration-flow` to the url and refresh the page.
* Select the "Import existing content or website" goal and click "Continue"
CleanShot 2024-03-11 at 14 20 33@2x
* On the "Where will you import from?" step, enter the url of any WordPress site. You won't actually be migrating it.
* On the "What do you want to migrate?" step, select "Everything" and click "Continue".
* Upgrade your plan (or select the free trial), if necessary. This step will be skipped if you already have a Creator plan.
* After the "Processing" step completes, you should land on the "Site Migration Instructions" step.
CleanShot 2024-03-11 at 14 23 48@2x
* Click the "Get migration key" button. 
* You should see the "Copy key" UI.
CleanShot 2024-03-11 at 14 24 11@2x
* Now refresh the page (**NOTE: You will most likely need to re-add `&flags=onboarding/new-migration-flow` to the URL first).
* Click the "Get migration key" button again.
* You should see the following error text.
CleanShot 2024-03-11 at 14 25 21@2x
* Verify that the link takes you to the MigrateGuru page on the wp-admin for your site.

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Comment by andres-blanco** [comment]
@markbiek https://github.com/Automattic/jetpack/pull/36253 is already on production :)

**Comment by markbiek** [comment]
> @markbiek https://github.com/Automattic/jetpack/pull/36253 is already on production :)

Excellent! It wasn't there yet when I wrote the instructions. I'll update them 🙏

**Comment by andres-blanco** [comment]
Functionally this is working great, I have a couple of visual nits:

1. The `show key` / `hide key` text is not aligned vertically
image

2. When the error is show, we should probably highlight it in some way, probably something red would be useful. Just for the user to know that they need to take an extra action
image

**Comment by markbiek** [comment]
@andres-blanco That's good feedback, thanks! I'll get those two things sorted out this morning.

**Comment by markbiek** [comment]
@andres-blanco Both of those should be resolved now.

CleanShot 2024-03-12 at 09 06 34@2x


CleanShot 2024-03-12 at 09 03 54@2x

**Review by andres-blanco — APPROVED** [review]
LGTM!

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/11597627

Some locales (Hebrew, Japanese) have been temporarily machine-translated due to translator availability. All other translations are usually ready within a few days. Untranslated and machine-translated strings will be sent for translation next Monday and are expected to be completed by the following Friday.

Thank you @markbiek for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/11597627).

**Pull request merged**
