### PR TITLE
Tracking: fix inserter-menu issue in Atomic sites

### PR DESCRIPTION
**Pull request by retrofox**
#### Changes proposed in this Pull Request

This PR fixes an issue that occurs in Atomic sites. It's produced because of the client plugin version is `undefined` for these sites, which records the same `no-results` search term twice.

#### Testing instructions

**Confirm the issue.**

You need to sandbox `widgets.wp.com` and apply these changes to your sandbox
Also, open the client dev console and set up the debug

```
> localStorage.setItem( 'debug', 'wpcom-block-editor*' )
```

A hard refresh is needed.

In your Atomic site, start to type a term in the Inserter Menu.

Confirm that it records two `wpcom_block_picker_no_results` register for the same event.
(Disable cache for the requests)

image

Screen Shot 2020-04-17 at 11 02 08 AM

With this patch, it should be recorded once. Also, I've improved a little bit the log lines, adding the `unknown_version`

image

Next improvement is to expose the Gutenberg version also for Atomic sites.

### CODE REVIEW

**Comment by retrofox** [comment]
D42071-patch

**Comment by obenland** [comment]
Could you resolve the conflicting files?

To test it, do I just need to sandbox widgets.wp.com?

**Comment by frontdevde** [comment]
It looks like there was [some reformatting done](https://github.com/Automattic/wp-calypso/pull/41114/commits/9e605ad50224b7fe5b462d1b926fc1965706836d#diff-1a17a51df6e5ce6c61638fcd9c4f9395) to the file that's being renamed here, which likely causes the conflict.

**Comment by retrofox** [comment]
> Could you resolve the conflicting files?

I think I did it.

> To test it, do I just need to sandbox widgets.wp.com?

yes

**Comment by retrofox** [comment]
> It looks like there was [some reformatting done](https://github.com/Automattic/wp-calypso/pull/41114/commits/9e605ad50224b7fe5b462d1b926fc1965706836d#diff-1a17a51df6e5ce6c61638fcd9c4f9395) on the file that's being renamed in this PR, which likely causes the conflict here.

Thanks 👍

**Pull request merged**
