### PR TITLE
Jetpack Manage: Implement the new 'Add Payment method' page.

### PR DESCRIPTION
**Pull request by jkguidaven**
This pull request implements the new **'Add Payment Method'** form. 

Screen Shot 2024-01-11 at 4 52 20 PM

Closes https://github.com/Automattic/jetpack-genesis/issues/180

## Proposed Changes

* This pull request introduces a new component called `PaymentMethodForm` that handles the addition of payment methods. We made it a reusable component to make it easier to use in a modal later on. Please note that we copied most of the implementation from the old component.
* Update components dependent on `PaymentMethodForm` to load new strings based on the feature flag.
* Update the new page to include the new form.

## Testing Instructions
Since these changes are made specifically for agencies, you must set yourself(partner) as an agency - 2c49b-pb.

* Use the Jetpack cloud live link below and go to the new Add Payment Method page (`/partner-portal/payment-methods/add?flags=jetpack/card-addition-improvements`)
* Confirm that the form works as expected and follows the new design.

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

**Review by oikeme — COMMENTED** [review]
Functionally these changes work as expected and the code looks good to me. There's an issue with invalid errors which I don't think is related to this PR and I'll look in to this separately and open another task for a later resolution. @yashwin can you give this a look as well for a second set of eyes and approval?

**Review by yashwin — COMMENTED** [review]
Great work on this, @jkguidaven! Everything works as expected and code changes look good.

I have a few feedback. Let me know your thoughts.

1) Can we disable the `Go Back` button when the request is in progress? 

Screenshot 2024-01-12 at 11 06 55 AM

2) The Add card button looks a bit out of place. How about we keep it as below?

CC: @ilonagl 

Screenshot 2024-01-12 at 10 05 30 AM

**Comment by jkguidaven** [comment]
@oikeme @yashwin, thanks for the review. I've made some adjustments to address the PR comments. Can you have another look? 🙏

**Review by yashwin — APPROVED** [review]
Thanks for addressing my comments, @jkguidaven! Great work!

I see the Go Back button is disabled, but I can still click, and it takes me to the expected page. Looks like this is an existing issue, we can fix this later on a different PR.

**Comment by jkguidaven** [comment]
> I see the Go Back button is disabled, but I can still click, and it takes me to the expected page. Looks like this is an existing issue, we can fix this later on a different PR.

Good catch! this has been fixed.

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/10819065

Thank you @jkguidaven for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/10819065).

**Pull request merged**
