### PR TITLE
Nav redesign - add interface_setting prop to page view analytics

### PR DESCRIPTION
**Pull request by Addison-Stavlo**
Related to #  surfacing this idea in slack p1709215152834339-slack-C06DN6QQVAQ

## Proposed Changes

* Adds `global_site_view_enabled` prop to page view analytics.
* This takes format from other enhancers such as `enhanceWithSiteType` and `enhanceWithUserIsDevAccount`, and enhances analytics to include an `global_site_view_enabled` prop that will be `0` or `1` depending on whether or not the user is being shown new nav changes for the site.
* Adds this enhancer to the page view analytics.

## Testing Instructions

* Load this branch of calypso
* On a default view site (AT or simple), load a page in calypso. Verify the `global_site_view_enabled` property of the page view event is `0`.
* On a classic view AT site, load a page in calypso. Verify the `global_site_view_enabled` property is `1`.

Tracks vigilante tool helps:

Screenshot 2024-03-01 at 8 52 52 AM

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Review by taipeicoder — APPROVED** [review]
Works as intended!

| Classic | Default |
| --- | --- |
| Screenshot 2024-03-01 at 9 12 03 AM | Screenshot 2024-03-01 at 9 14 34 AM|

**Comment by Addison-Stavlo** [comment]
Thanks for looking @taipeicoder !

Im thinking I might let this sit on-hold given new information about the release and opt-in plan, so we can update the data we are checking to whatever will correspond to showing the new nav changes.

**Comment by Addison-Stavlo** [comment]
Ok, updated this to check `isGlobalSiteViewEnabled` instead since that determines if these nav changes are actually shown and includes the logic for determining the opt-in crowd, etc.

Also updated the event property to be `gloabl_site_view_enabled` (`0` or `1`).

**Review by eoigal — APPROVED** [review]
LGTM

**Pull request merged**
