### PR TITLE
Help Center: Open chat images in a new tab

### PR DESCRIPTION
**Pull request by escapemanuele**
Fixes https://github.com/Automattic/dotcom-forge/issues/10019

## Proposed Changes

Opens the images sent in the chat in a new page.

## Testing Instructions

* Open the Help Center with the ?flags=help-center-experience
* Open a chat with an Happiness Engineer and send an image from the Happiness Engineer
* The image should be clickable
* You older images should be clickable
* The images you sent in the current session are still not clickable, we'll address it in the next PR

### CODE REVIEW

**Comment by heavyweight** [comment]
https://github.com/user-attachments/assets/1397632a-8fc6-45fa-9dbf-b6584fc39834

The image is not clickable right away for me.
Also there is a crash if you send a message after that.

**Comment by agrullon95** [comment]
@escapemanuele - I'm having the issue Kosta mentioned above. I can't click on the image and it crashes after I send a message.

**Review by agrullon95 — CHANGES_REQUESTED** [review]
@escapemanuele - I'm having the issue Kosta mentioned above. I can't click on the image and it crashes after I send a message.

**Comment by escapemanuele** [comment]
Thanks, I disabled the click on the image right after sending it, since we don't have a true URL but instead a `createObjectURL`.

I'll address the crash that happens!

**Comment by AllTerrainDeveloper** [comment]
I've tested the image part and I've realised that right after uploading the image, the image is not clickable. But if you reload the conversation (F5), then it's possible to open the image. Is this desired or intended? Also, is not possible to open images that are received from the IA, is that intended? the images are almost impossible to see

image


I've been testing quite a lot the new chat and I've not seen any issue (one minor thing is just that the initial language shown for new conversation does not match the WordPress language set)

**Comment by escapemanuele** [comment]
> OK - I've seen the recently images sent for HE are for a next PR :)

Yes, the images you sent in previously conversations are also clickable. It is just that the attachment works with not showing the image from Zendesk, but creating a local URL for the file. We'll work on this to check if it is fixable.

But the main motivation for the change is because users cannot open images received by HEs, so I quickly created this :)

> one minor thing is just that the initial language shown for new conversation does not match the WordPress language set

If you can, add something to the Cft! https://vertexp2.wordpress.com/2024/11/11/call-for-testing-help-center-experience/

**Pull request merged**
