### PR TITLE
Signup: Updating padding to cater for the new, narrower arrow button and mobile widths

### PR DESCRIPTION
**Pull request by ramonjd**
## Changes proposed in this Pull Request

Copy and padding changes to accommodate narrow widths.

**Before:** 
Screen Shot 2019-04-26 at 3 20 05 pm

😱 

**After:**
Screen Shot 2019-04-26 at 3 38 07 pm

🍸 

Also creating a condition to deliver varying copy in the site vertical input for the case where we display no popular topics.

## Testing
Check the site topic and site title steps in narrow widths. Enter text, remove text.

Does everything look as it should?

### CODE REVIEW

**Comment by ramonjd** [comment]
Thanks for testing @sirreal 

> iPhone 5... Is there another way we can fix this?

We'll pass the hat around at the GM so you can upgrade. :trollface: 

> Trying to keep text under some threshold always seems problematic.

Seriously, you're right. 

We could hide the placeholder text for smaller screens, 

```
		@include breakpoint( '<480px' ) {
			&::placeholder {
				color: transparent;
			}
		}
```

but that feels like kicking the can down the road.

When the input has no focus, there's a neat way to automagically add an ellipsis –

```
		&[placeholder] {
			text-overflow: ellipsis;
		}
```

since we auto focus on the input field however, the browser displays the full string. 

One compromise might be to combine the two, that is, apply `text-overflow: ellipsis;` but hide the placeholder text when focussed:



Fairly trivial CSS changes.

Other than culling the copy right down, or using a scripted approach, I'm not sure how to cover all bases right now.

**Comment by spen** [comment]
I've had a play around with this myself and have had no luck either :/ I'm erring on the side of @ramonjd's suggestion of hiding the placeholder when it's focused, but my worry there is that, as we autofocus the input, it's not 100% clear what we're meant to be inputting.

We could just change the copy to 'Enter a topic' on smaller screens but this might not solve the problem for all locales.

**Comment by spen** [comment]
Paging @Automattic/onboarding-design - someone here might have some advice on how to work around this limitation.

**Comment by fditrapani** [comment]
Thanks for getting this PR started @ramonjd. Something I'd like to point out is that the text is getting cut off by some padding on the input that is there to account for the button when a customer starts typing. We should remove the padding when the button isn't visible. This should help us get a couple more characters in there for the placeholder copy. 

image

**Comment by shaunandrews** [comment]
> We should remove the padding when the button isn't visible. This should help us get a couple more characters in there for the placeholder copy.

^ This

> since we auto focus on the input field however, the browser displays the full string.

One thing to note, is that the auto-focus for the input field doesn't work on Mobile Safari. (Unclear about other mobile browsers).

--

Its worth noting that's there's the potential for this screen to get a slight redesign as we work towards Muriel/Material guidelines, so lets focus on small improvements for now.

**Comment by ramonjd** [comment]
> We should remove the padding when the button isn't visible. 

👍 I'll do this and get this PR merged as an 'iteration' as mentioned so we can keep working on it.

Thanks @fditrapani @sirreal @shaunandrews for the feedback!!!!

**Pull request merged**
