### PR TITLE
GitHub Deployments: provide better UX when connecting a repository (WIP)

### PR DESCRIPTION
**Pull request by mpkelly**
Related to https://github.com/Automattic/dotcom-forge/issues/5855

Screenshot 2567-03-05 at 13 59 36

## Proposed Changes

Need to discuss some of these changes with Javier and others. So far have this:

* Add a hint to deployment type. It wont be obvious what "Simple" means
* Automatically set the dest directory
* ~~If theme or plugin repo then offer to activate after first deployment~~ dropped after design feedback
* If repo contains `composer.json` but not `vendor` folder then use a Composer action in workflow when the user selects "new workflow"
* Include ignore file list on example workflows
* Some other tweaks and fixes like ignoring lint workflows and ensuring workflow script name is set 

## Testing Instructions

* Apply patch D140370-code
* Connect a repo and observe payload of `/wpcom/v2/hosting/github/repository/pre-connect-checks`

Screenshot 2567-03-01 at 18 12 57

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Comment by paulopmt1** [comment]
So far, it seems to be working as expected. Thanks for this improvement @mikeicode!
Let me know if you want a full review after it's done:

image

**Comment by mikeicode** [comment]
> Thanks for this improvement @mikeicode!

@paulopmt1  Wrong Mike :)

**Comment by zaguiini** [comment]
How do you plan to expose these things in the UI? The path, it's easy we will pre-fill it in the text input. What about the other information?

Also, should we bump the stat only after the user creates the connection? It might generate false positives.

**Comment by mpkelly** [comment]
> How do you plan to expose these things in the UI? The path, it's easy we will pre-fill it in the text input. What about the other information?

I included a screenshot to show some of the changes. I also asked Javier p1709547015185179/1709544724.536929-slack-C06D9M3CHMK. 

> Also, should we bump the stat only after the user creates the connection? It might generate false positives.

I'll take care of that before merging.

**Comment by mpkelly** [comment]
I will merge this as I want it on wpcalypso before I invite three external testers. I made some changes after discussing it with Javier. We're still not doing anything with the protected files list but will add a warning later.

> Also, should we bump the stat only after the user creates the connection? It might generate false positives.

I just made this a Tracks property of an existing event.

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/11562569

Some locales (Hebrew, Japanese) have been temporarily machine-translated due to translator availability. All other translations are usually ready within a few days. Untranslated and machine-translated strings will be sent for translation next Monday and are expected to be completed by the following Friday.

Thank you @mpkelly for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/11562569).

**Pull request merged**
