### PR TITLE
Currency Formatting: Add logic to put symbol on right

### LINKED ISSUE #38325: Ensure that currency codes can be put in a different position
The current `@automattic/format-currency` package does not support cases where the currency code is not on the left. This is a problem for i18n reasons if we need to support currencies where this occurs.

### PR DESCRIPTION
**Pull request by ChaosExAnima**
#### Changes proposed in this Pull Request

* Adds ability for `format-currency` package to put symbols on right.

#### Testing instructions

* Load a page that displays USD and check symbol is on left
* Load a page that displays EUR and check symbol is on right

Fixes #38325

### CODE REVIEW

**Comment by ChaosExAnima** [comment]
We'll definitely need something beyond EUR, but I wanted the code approved first, and worry about updating currency list in a different PR :)

**Comment by ChaosExAnima** [comment]
Also a question: I'm seeing linting fail here. Is there a special override I need to do, or is this style of docblock out of date from the accepted norm? This seems to be common among all Calypso packages.

**Comment by tyxla** [comment]
> Also a question: I'm seeing linting fail here. Is there a special override I need to do, or is this style of docblock out of date from the accepted norm? This seems to be common among all Calypso packages.

I've fixed those for you in https://github.com/Automattic/wp-calypso/pull/38458/commits/9728bfde7d5b27f2619cc737ca21d28f62daefe0. 

Basically, you were getting warnings because you're touching a file that has ESLint warnings already. This is expected, we do this intentionally to provoke anyone to fix those warnings a little by little as they iterate on the code.

There were two types of warnings, and both of them were JSdoc related:

* Capitalized type used instead of lowercase (`{Number}` instead of `{number}`)
* Missing empty line below the doc block description.

**Comment by enejb** [comment]
I am not an export here but Wikipedia seems to suggest that the way the currency is written has more to do with the language  used then the currency.

> When writing currency amounts, the location of the symbol varies by language. 
 https://en.wikipedia.org/wiki/Currency_symbol 

Could we solve this by making the string translatable instead?

**Comment by ChaosExAnima** [comment]
@enejb - That's not a bad idea! So you're saying we provide the value, decimals, symbol, etc to a string that translators can vary by locale? How do we want to handle stripping zeros, have two strings? Or keep the decimals an empty string?

**Pull request closed without merging**
