### PR TITLE
Add a readme viewer component

### PR DESCRIPTION
**Pull request by scruffian**
This moves the `ReadmeViewer` to `/components` and generalises it so it can display README.md files from anywhere in `/client`.

This also displays README.md files at the top of `/devdocs/design`, `/devdocs/blocks` and `/devdocs/selectors`. I'm not sure how helpful these are. We might want to introduce better ones...

screen shot 2018-04-24 at 12 05 16

### CODE REVIEW

**Comment by drw158** [comment]
Seems great to generalize, but not sure I like the readme at the top of the page. I think it's a bit too long, and afraid of them becoming longer. Currently, some of the links don't work.

**Comment by scruffian** [comment]
A good point. I added much shorter READMEs, which link to the longer ones, so hopefully if people want to add info they will go in the longer ones. What do you think?

**Comment by mapk** [comment]
@scruffian, looking at the condensed version, this is what I see.

screen shot 2018-05-07 at 11 48 56 am

1. I noticed an underscore at the end of the sentence. Is that on purpose?
2. The "Improve this document on Github" link is kind of floating out there as well.

**Comment by scruffian** [comment]
> I noticed an underscore at the end of the sentence. Is that on purpose?

Whoops, no that's a mistake. Fixed :)

> The "Improve this document on Github" link is kind of floating out there as well.

This is a carry-over from the other docs (https://wpcalypso.wordpress.com/devdocs/README.md), so we should be careful to make sure we don't break them. I suggest we fix that in a different PR.

**Pull request merged**
