### PR TITLE
Renamed blank-canvas-blocks to blockbase

### PR DESCRIPTION
**Pull request by MaggieCabrera**
#### Changes proposed in this Pull Request

The theme previously known as Blank Canvas Blocks has been renamed Blockbase. This PR updates the design config json to use the renamed version of the theme.

#### In Gutenboarding:
* Apply D60806-code
* Sandbox public-api.
* Visit [/new/design?flags=gutenboarding/site-editor](https://hash-90fcf479a5798ca0c774122e904b1917aaa31505.calypso.live/new/design?flags=gutenboarding/site-editor), pick the Blank Canvas design option and create a new site
* Verify that:
    * [ ] The new site is created correctly, without errors
    * [ ] The new site uses the Blank Canvas Blocks theme (and therefore, it uses FSE)
    * [ ] The homepage is prepopulated with an _empty page template_ (Note: this A/C needs revision)

Related to https://github.com/Automattic/themes/pull/3918

### CODE REVIEW

**Comment by scruffian** [comment]
Codewise this looks fine but I'm not sure how to test. Is someone from @Automattic/cylon able to look?

**Comment by Copons** [comment]
Thanks folks! The test steps added by @alshakero look good to me, and work as expected.
Code LGTM and I've also noticed that past FSE sites using BCB have been automagically converted over to Blockbase. ✨ 

---

There's one issue to report though: the design picker isn't able to load the Blockbase's demo content, and renders an error:
Screenshot 2021-05-25 at 12 32 12

Zoomed in:
Screenshot 2021-05-25 at 12 32 40

I'm fairly sure this is because there is no Blockbase starter site (see [BCB starter](https://blankcanvasblocks.wordpress.com/)), and so [the template demo API fails](https://public-api.wordpress.com/rest/v1/template/demo/blockbase/blockbase).
FYI starter sites are listed in `class-nux-starter-designs.php`, but I'm not extremely familiar with how they work (for example, the API expects both a theme and a template slug).
I think @alshakero or @apeatling might now more, though?

**Comment by MaggieCabrera** [comment]
> Thanks folks! The test steps added by @alshakero look good to me, and work as expected.
> Code LGTM and I've also noticed that past FSE sites using BCB have been automagically converted over to Blockbase. ✨
> FYI starter sites are listed in `class-nux-starter-designs.php`, but I'm not extremely familiar with how they work (for example, the API expects both a theme and a template slug).

Thanks for looking into this! @scruffian went ahead and created a patch for the starter theme: D61835-code

**Comment by Copons** [comment]
Cool, thanks! ✨ 
I think this PR can be merged regardless of the server change, as FSE themes are not exposed to users yet.

**Comment by alshakero** [comment]
Yes, I'm fairly certain that once the patch is deployed, the thumbnail will work out.

**Review by Copons — APPROVED** [review]

**Review by alshakero — APPROVED** [review]
LGTM! Tested with D61835-code.

**Comment by alshakero** [comment]
As a follow-up, we should remove backwards compat from the backend (remove black-canvas-block slug in `$starter_design_sites`), I'll do that.

**Comment by razvanpapadopol** [comment]
> As a follow-up, we should remove backwards compat from the backend (remove black-canvas-block slug in `$starter_design_sites`), I'll do that.

@alshakero, When you do that, probably fine to close also this diff with improvements: D61650-code

**Comment by alshakero** [comment]
I did that D62031-code.

**Pull request merged**
