### PR TITLE
Sites List: The Removal

### PR DESCRIPTION
**Pull request by lamosty**
This is it!

After more than 18 months of hard work, countless hours and effort, we can finally remove most of the `lib/sites-list` and `lib/site` files as they are not used anywhere anymore.

Big props to everybody who put their hands to the endeavor.

### CODE REVIEW

**Comment by ockham** [comment]
There aren't enough emoji reactions in GitHub to express my feelings.

**Comment by ockham** [comment]
Did a `grep` for `lib/site`. Looks good!

One remaining instance I found was the in `sites-list` test, https://github.com/Automattic/wp-calypso/blob/9b76083b2a8f976379c236b103f09b20f88226e6/client/lib/sites-list/test/index.js#L16-L18 which is including mocks for both `site` and `sites-list`. Should we remove those mocks and imports?

**Comment by lamosty** [comment]
> One remaining instance I found was the in sites-list test,

Oh, great point! I forgot to remove the tests for `lib/sites-list`.

**Comment by gwwar** [comment]
Finally! Site-lists has been 🔪 Thanks for the last push @jsnajdr and @lamosty !

**Comment by rralian** [comment]
lotsa deletes
One of the best and most satisfying commits ever. Congratulations @jsnajdr and @lamosty!

**Comment by lamosty** [comment]
Thanks @rralian. We wouldn't be here without you! :trollface:

**Comment by ockham** [comment]
🎉🎈:champagne:

**Pull request merged**
