### PR TITLE
Site Migration: Add migration survey

### PR DESCRIPTION
**Pull request by gabrielcaires**
Related to #95407

> [!NOTE]  
> It is waiting for the final copy definition

## Proposed Changes

* Add a generic survey component to enable the usage of any layout

Example of usage: 
```TSX
 <Survey name="survey-name">
  	<div>
  		<h1>Survey</h1>
  		<img src="https://wordpress.org/about/assets/images/wp-logo.png" alt="WordPress" />
  		<SurveyTriggerAccept>
  			<Button>Take the survey</Button>
  		</SurveyTriggerAccept>
  		<SurveyTriggerSkip>
  			<Button>Skip the survey</Button>
  		</SurveyTriggerSkip>
  	</div>
  </Survey>
  ```
* Skip the survey by one day if the user clicks on the gray overlay
* Skip the survey by one year if the user explicitly decides to skip
* If the user clicks on "Take the Survey," we will not show it again for 1 year
* Creates a cookie called `migration-survey` 
* Track events if the user skipped or accepted the survey

image

## Why are these changes being made?
As explained on #95407, we want to have the ability to show surveys on stepper flows, for now just for migration flows.

## Testing Instructions

**Scenario: Happy Path**
* Go to any of the migration flow (E.g. /setup/migration)
* Check if the survey is render as the image

**Scenario: Skip clicking on the gray layer**
* Delete the cookie (cookie name described above)
* Go again to any of the migration flow (E.g. /setup/migration)
* Check if the survey is rendered
* Click on the gray layer

**Scenario: Skip clicking on the gray layer**
* Delete the cookie (cookie name described above)
* Go again to any of the migration flow (E.g. /setup/migration)
* Check if the survey is rendered
* Click on the "Take survey" 
*  Reload the page and check if it is the survey was opened in new tab

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Comment by gabrielcaires** [comment]
It is waiting for the final copy definition.

**Comment by fditrapani** [comment]
I'm not seeing the survey prompt on my end. I'm not sure if I didn't set something up right but the copy and screenshot look good! We should be good to go with what we have in the p2 post.

**Review by fditrapani — APPROVED** [review]
My bad! I was on the wrong branch. This looks good to go on my end! 

One question, is there any chance we can animate the popup into view? It currently just appears. (We can do this as a follow up PR)

**Comment by gabrielcaires** [comment]
@fditrapani Yes, we definitely can!  
Do you think we are going to have more copy changes?

**Comment by fditrapani** [comment]
I think we're good to move forward with this. We can always push another update if something else comes up.

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/16942117

Some locales (Hebrew, Japanese) have been temporarily machine-translated due to translator availability. All other translations are usually ready within a few days. Untranslated and machine-translated strings will be sent for translation next Monday and are expected to be completed by the following Friday.

Thank you @gabrielcaires for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/16942117).

**Pull request merged**
