### PR TITLE
Data Stores: Remove unused reader store

### PR DESCRIPTION
**Pull request by tyxla**
## Proposed Changes

This PR removes the unused Reader store. It hasn't been in use since #54196 landed.

Part of #74399. A follow-up to #73890.

## Testing Instructions

* Verify that the removed store is not in use.
* All checks should be green and Calypso should build well.

## Pre-merge Checklist

- [x] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [x] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [x] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

**Review by flootr — APPROVED** [review]
LGTM 🚀

**Comment by p-jackson** [comment]
I wonder if this could be useful to keep around for the next time someone wants to gate something behind an "is a11n" flag and they're not in the Calypso client codebase. The original reason the store was added was so Gutenboarding had access to the reader team data to implement such a feature gate. But a future example might be an ETK feature. It can't import Calypso's redux store, but it can import `@automattic/data-stores`.

But maybe that's a moot point because there are no new ETK features, only Jetpack features 🤷

**Comment by tyxla** [comment]
No unused code is useful to keep IMHO 😉 We can always bring it back if necessary - work is never lost in history 😉

**Review by mashikag — APPROVED** [review]
FYI, I have the following tasks created that will be implemented within the next 2 weeks. The plan is to introduce the new queries into the reader data-store. 

- https://github.com/Automattic/wp-calypso/issues/74424
- https://github.com/Automattic/wp-calypso/issues/74422
- https://github.com/Automattic/wp-calypso/issues/74423

However, as of now I have no clear plans for introducing any new reader `redux-store` state. On the other hand, there are more queries to come in the near future, I just did not create tasks for them yet.

At the same time, I see no need for any of the store state being removed in this PR, therefore I am approving it.

**Pull request merged**
