### PR TITLE
Update support closure notice to show Thanksgiving closures

### PR DESCRIPTION
**Pull request by lamosty**
Shows a live chat closure notice from November 20, 2018 00:00 UTC till November 23, 2018 05:00 UTC. Shows a closure message on November 22, 2018 05:00 UTC.

### CODE REVIEW

**Comment by beaucollins** [comment]
And then gone again when I set my clock to past midnight.

image

Worth noting that people could change their computer's clock to get around any client side blocks we might have but I don't think that's a problem at this point.

**Comment by lamosty** [comment]
> I think it's worth keeping the general case too given that there may be cases where a user can still open a chat session depending on which flow they used to sign up or other special cases that we might not be aware of.

Wouldn't that show to users without a paid plan? Or is that okay?

**Comment by lamosty** [comment]
I've updated it for all cases.

**Comment by beaucollins** [comment]
Yeah approved. I think it's good to have the message for the tier of accounts that don't get live chat. There may be cases where their account still is allowed live chat so this will cover all of those cases.

**Pull request merged**
