### PR TITLE
Editor: Cancel pending actions when fulfilled

### PR DESCRIPTION
**Pull request by aduth**
This pull request seeks to cancel pending autosaves and raw content saves when their effects are otherwise fulfilled. For example, if the user explicitly clicks Save, or Update, or a post explicitly triggers its autosave behavior (i.e. iframe preview), then any pending autosave should be canceled. Similarly, if the user switches editor modes which immediate saves raw content, any pending raw content saves should be canceled.

This may help remedy symptoms of autosaves falsely flagging a post as dirty (#9833), such as the case described at https://github.com/Automattic/wp-calypso/issues/9833#issuecomment-327226158. While it's sensible that these pending actions be canceled to prevent unintended consequences, the autosave behavior itself should be [shortcutting itself automatically](https://github.com/Automattic/wp-calypso/blob/4db4ee78229e88d99893cdc2e71f6a88a5b17501/client/lib/posts/actions.js#L167-L169) when there are no changes to save. That it is not is itself a bug, one which I do not expect to be resolved by the changes here.

__Testing instructions:__

Ensure that unit tests pass:

```
npm run test-client client/post-editor/test/post-editor.jsx
```

Verify that autosave continues to behave as expected for drafts and published posts. Make a change and wait a few seconds. For draft posts, the "Save" button should change to "Saving..." and finally "Saved". A published post will not show this indicator, but upon refreshing the page (and dismissing prompt) you should observe that a modal appears to restore a newer revision (the autosave).

Verify that raw content saving continues to behave as expected. In a post with a title or some existing content, change the content of the post, then reverse those changes. Observe that there is no "Save" button to indicating that changes exist.

Create a post with a `code` shortcode and Publish it. Return to the posts list and edit the post. Make a small revision to the content and click Update. You should note that the preview reflects the changes, is not refreshed, and that you can navigate away (previously the preview would reload and attempting to navigate away would prompt about unsaved changes).

### CODE REVIEW

**Comment by apeatling** [comment]
@aduth Can we bring this one back to life? Is it still relevant if we get some reviews going?

**Comment by aduth** [comment]
@apeatling Yes, and yes.

**Comment by apeatling** [comment]
Pinged Lannister to add this to the upcoming review day.

**Comment by aduth** [comment]
Rebased to resolve conflicts.

**Comment by Copons** [comment]
Tested and it works as expected, which is awesome especially because I've always considered the whole autosave part quite fragile.

:shipit:

**Comment by apeatling** [comment]
@aduth LGTM

**Comment by aduth** [comment]
Note that I've been delayed in merging this because I want to spend more time looking into whether canceling the `debouncedSaveRawContent` when saving starts is actually warranted.

**Comment by apeatling** [comment]
@aduth Is this something you're going to look at imminently? I fear this PR is going to sit and go stale again.

**Comment by aduth** [comment]
Rebased and pushed without the `debouncedSaveRawContent` canceling. If it's truly the case that a save raw content is pending when a save starts, we _should_ want that to be reflected as dirtying the post. However, the expected behavior should be that an autosave or proper save should cause raw content to save immediately, thereby having the same effect of canceling the pending debounce:

_Autosave:_

https://github.com/Automattic/wp-calypso/blob/58ca01b2cbcc06bb49da7ccaa7f249ff67c31868/client/post-editor/post-editor.jsx#L594

_Save:_

https://github.com/Automattic/wp-calypso/blob/58ca01b2cbcc06bb49da7ccaa7f249ff67c31868/client/post-editor/post-editor.jsx#L700-L701

_Publish:_

https://github.com/Automattic/wp-calypso/blob/58ca01b2cbcc06bb49da7ccaa7f249ff67c31868/client/post-editor/post-editor.jsx#L868-L869

_`saveRawContent` cancels pending:_

https://github.com/Automattic/wp-calypso/blob/58ca01b2cbcc06bb49da7ccaa7f249ff67c31868/client/post-editor/post-editor.jsx#L583-L584

A bit verbose to be manually triggering the raw content save. A future refactor might consider consolidating save paths.

From what I can recall / determine, calling `saveRawContent` this way should be fine, since the PostEditStore has built in change detection:

https://github.com/Automattic/wp-calypso/blob/c21185e8acc3d5466e17a795c34af7c63ac3944c/client/lib/posts/post-edit-store.js#L176

It's also important that this raw content be kept accurate, since after the save completes, we trigger the newly received post as still using the original raw content from prior to the save:

https://github.com/Automattic/wp-calypso/blob/c21185e8acc3d5466e17a795c34af7c63ac3944c/client/lib/posts/actions.js#L385-L395

**Comment by aduth** [comment]
@Copons would you have a spare moment to sanity check my latest changes? Otherwise I can plan to merge sometime tomorrow.

**Comment by Copons** [comment]
Sorry about that @aduth! Tested again and still LGTM!

**Pull request merged**
