### PR TITLE
Extract and modularise `ui/reader` to `reader-ui`

### PR DESCRIPTION
**Pull request by sgomes**
This PR is one of many working on modularising state in Calypso. This one handles the Reader UI, which was part of the `ui` tree, but is now being extracted into a new `readerUi` top-level item. This removes Reader state from `ui`, while avoiding all of Reader being loaded on boot (which would happen if we were to move this under `reader`).

For more details on state modularisation, see the [modularised state documentation](https://github.com/Automattic/wp-calypso/blob/master/docs/modularized-state.md) and p4TIVU-9lM-p2.

Note: I added all the reviewers that GitHub suggested. Please feel free to ignore the review request or pull in someone else if you're not comfortable reviewing this PR. Thank you!

#### Changes proposed in this Pull Request

* Extract `state/ui/reader` into `state/reader-ui`.
* Extract a couple of inline selectors into a proper selector module.
* Update all code and tests accordingly

#### Testing instructions

Ensure that Reader continues to work correctly, particularly features like sidebar item expansion and card expansions.

### CODE REVIEW

**Review by unDemian — APPROVED** [review]
This is lovely and works as expected!  🔝 💯 

I was working on persisting the expanded sidebar items and I saw you added `withStorageKey` what does it do? Is the correct way of persisting a redux entity to add `hasCustomPersistence` to its reducer? Thanks

**Comment by sgomes** [comment]
> This is lovely and works as expected! 🔝 💯

Thank you, @unDemian, that's very kind of you 😊  

> I was working on persisting the expanded sidebar items and I saw you added `withStorageKey` what does it do? Is the correct way of persisting a redux entity to add `hasCustomPersistence` to its reducer? Thanks

`withStorageKey` controls where the state gets persisted to. Without it, it gets persisted to global state, under a key like `redux-state-xxxxxxxx` in `calypso_store` (in IndexedDB). That's where all of state traditionally lived, in one giant object. With `withStorageKey`, it instead gets persisted to its own key, of the format `redux-state-xxxxxxxx:readerUi`, for example. That key contains just the state pertaining to `readerUi`.

The reason for using it in this PR is that when we modularise a portion of state, we need to persist it to its own key in order to avoid inconsistencies between the data in memory and the data in persistent storage. We'd need to keep loading, merging, and saving again to avoid issues, and this way any changes are easily scoped to just that bit of the state tree, and we can more easily persist without loading all the time.

As for `withCustomPersistence`, you don't really need `withStorageKey` for that. My understanding is that `withCustomPersistence` is about controlling **what** gets serialised, whereas `withStorageKey` is about controlling **where** that serialisation ends up.

**Comment by unDemian** [comment]
> withStorageKey controls where the state gets persisted to. Without it, it gets persisted to global state, under a key like redux-state-xxxxxxxx in calypso_store (in IndexedDB). That's where all of state traditionally lived, in one giant object. With withStorageKey, it instead gets persisted to its own key, of the format redux-state-xxxxxxxx:readerUi, for example. That key contains just the state pertaining to readerUi.

I see, makes sense.

> As for withCustomPersistence, you don't really need withStorageKey for that. My understanding is that withCustomPersistence is about controlling what gets serialised, whereas withStorageKey is about controlling where that serialisation ends up.

I understand I was just curious if that is the expected way of persisting something.

thanks

**Comment by sgomes** [comment]
Going ahead and merging this. Thank you again for the review, @unDemian! 🙇

**Pull request merged**
