### PR TITLE
Update ecommerce plan features

### PR DESCRIPTION
**Pull request by niranjan-uma-shankar**
Related to pau2Xa-4W0-p2

## Proposed Changes

* This PR updates the feature list copy for the eCommerce plan in all pages that display the plans page. 

### Desktop

com1

### Mobile

Screenshot 2023-05-24 at 3 54 36 PM

## Testing Instructions

* Verify the plans step in `/start` signup flow has the updated eCommerce features as shown in the description above. a few things to check:
    - verify that the eCommerce plan tagline is updated to reflect the new copy given in pau2Xa-4W0-p2.
    - verify that the feature copy is updated in both the top-of-the-fold plans grid and in the comparison grid below-the-fold.
    - In the comparison grid below-the-fold, verify that all of the new eCommerce features under the Business plan have the text "Available with plugins" copy.
    -  Verify that the tooltip content for all these new features are updated as per the copy provided in the linked P2 post (pau2Xa-4W0-p2).
    - verify the copy in both desktop and mobile matches the screenshots above (and the copy given in the linked P2 post)
    - verify in at least one non-EN locale, in both desktop and mobile, that the new copy is translated.
* Verify the plans step in Calypso's /plans page has the updated eCommerce features as shown in the description above.

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/7987060

Hi @niranjan-uma-shankar, could you please edit the description of this PR and add a screenshot for our translators? Ideally it'd include this string: `Create a powerful online store with built-in premium extensions.`

Thank you in advance!

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/7987060).

**Review by travisw — COMMENTED** [review]
> In the comparison grid below-the-fold, verify that all of the new eCommerce features under the Business plan have the text "Available with plugins" copy.

I'm not seeing this in the comparison grid. For me it's showing the regular dashes on desktop and strike-through text on mobile. This is the case on both `/start/plans`  and `/plans`. Maybe I'm missing something, but I don't see those changes in the code either.

Screenshot 2023-05-24 at 1 20 46 PM
Screenshot 2023-05-24 at 1 20 23 PM

Other than that, the rest all tests well.

**Comment by niranjan-uma-shankar** [comment]
Thanks for catching that, the changes were in my local environment and I missed to push them. I'm going ahead with the merge since the changes are now visible.

**Pull request merged**
