### PR TITLE
Typo corrections on plugin install code and site credit block

### PR DESCRIPTION
**Pull request by arunsathiya**
#### Changes proposed in this Pull Request

Typo corrections on plugin install code and site credit block.

#### Testing instructions

NA

#### Notes

Came across them when supporting users. Feel free to merge on my behalf, thank you!

### CODE REVIEW

**Comment by noahtallen** [comment]
Thanks a ton for this!

> Came across them when supporting users

Did you see the site credit block stuff in prod or did you come across it in the codebase? (It shouldn't be loading for users yet, so I just wanted to see if we accidentally shipped part of it! 😬)

**Comment by arunsathiya** [comment]
>Did you see the site credit block stuff in prod or did you come across it in the codebase? (It shouldn't be loading for users yet, so I just wanted to see if we accidentally shipped part of it!

Good question! I think I saw this on one of my test sites on staging (or was it wpcalypso.wordpress.com? 🤔) last week, but I don't see it on staging (wordpress.com) anymore. I haven't checked wpcalypso.wordpress.com today. Pretty sure I didn't discover it on an user's site.

**Comment by arunsathiya** [comment]
@noahtallen I had a check on `wpcalypso.wordpress.com` for a simple site `gutenberg.wpcom.arunsathiya.blog` and I don't see the block anymore. At this stage, I don't remember how or where I saw the `site credit` block. Maybe I saw it on my dev (local) Calypso. The next time I see something odd, will be sure to note the reproduction steps. 👍🏽

**Comment by noahtallen** [comment]
No problem!

**Pull request merged**
