### PR TITLE
wp-babel-makepot: Handle multiple file inputs

### PR DESCRIPTION
**Pull request by yuliyan**
#### Changes proposed in this Pull Request

* Fix handling for multiple file or glob pattern inputs separate by single space character.
* Add missing unit test for filter option.

#### Testing instructions

* Check `localci-new-strings.pot` artifact from `translate` CircleCI job and confirm it contains the newly added and updated strings proposed in this PR. Note that these string updates are only used for testing and **should be dropped** before merging the PR.
* Run with multiple file inputs, e.g. `npx @automattic/wp-babel-makepot "./client/signup/steps/about/*.jsx ./client/signup/steps/domains/*.jsx ./client/signup/steps/plans/*.jsx"` and confirm `./build/bundle-strings.pot` contains the extracted strings from all source files.
* Confirm existing CLI calls are working as they were before, e.g. `yarn run translate`.

#### Merge instructions
Drop https://github.com/Automattic/wp-calypso/pull/45024/commits/e2deb30f2e4f9651636146ab4f412234604d0a09 before merging the PR.

### CODE REVIEW

**Comment by akirk** [comment]
Is the unit test supposed to test the correct behavior of the PR? It tests fine with and without the cli.js patch applied.

**Review by akirk — APPROVED** [review]
Tested and it works as described, unit tests work fine as well. The example new strings still need to be removed from the PR.

**Comment by yuliyan** [comment]
> Is the unit test supposed to test the correct behavior of the PR? It tests fine with and without the cli.js patch applied.

The test that's added to this PR is unrelated to the main problem that this PR resolves. It's been a while since I worked on this and I can't really remember, but it's likely that I'd noticed that the test was missing and just added it to to this PR.

Anyway, it's expected to work with and without the fix in `cli.js`. I've updated the description PR to mention the test update.

**Review by wp-desktop — CHANGES_REQUESTED** [review]
WordPress Desktop CI Failure for job "wp-desktop-mac".

@yuliyan please inspect this job's build steps for breaking changes at [this link](https://circleci.com/gh/Automattic/wp-calypso/900238). For temporal failures, you may try to "Rerun Workflow from Failed".

Please also ensure this branch is rebased off latest Calypso.

**Pull request merged**
