### PR TITLE
Domains Table: Fix overlapping columns when user only has domains

### PR DESCRIPTION
**Pull request by xavier-lc**
Fixes https://github.com/Automattic/dotcom-forge/issues/8434

## Proposed Changes

* Fix the CSS selector that is causing the table to look bad. Since the `grid-template-columns` has 8 values, it can only apply to 7-column + checkbox tables.

## Testing Instructions

* Use a user that has no sites but does have domains
* Open the live preview
* Go to `/sites`
* Then click on `Domains`
* Check that the table looks as usual:

|Before|After|
|---|---|
|image|image|

* With a user that has both sites and domains, confirm that there have been no regressions

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Comment by xavier-lc** [comment]
@eoigal pinging you because you introduced the CSS selector I'm adjusting on https://github.com/Automattic/wp-calypso/pull/90897. You might have more context on the table and double check whether my changes break something else.

**Review by danielbachhuber — COMMENTED** [review]
Could we drop the number from the domain column header too?

CleanShot 2024-07-29 at 07 26 13@2x

The Sites page doesn't have it, and I don't think it's necessary:

CleanShot 2024-07-29 at 07 26 40@2x

**Comment by xavier-lc** [comment]
> Could we drop the number from the domain column header too?

@danielbachhuber I guess we should remove the number when not in bulk selection mode, but keep it otherwise. Wdyt?

image
image
image

**Comment by danielbachhuber** [comment]
> I guess we should remove the number when not in bulk selection mode, but keep it otherwise. Wdyt?

@xavier-lc I'm open to this!

**Review by eoigal — APPROVED** [review]
WFM. This issue has popped up for me recently (while working on https://github.com/Automattic/wp-calypso/pull/93077)
 but I couldn't get it reproduce it consistently. It appeared to happen when navigating from the domains manage page to another calypso page and then back to domains manage page. This appears to fix it though as I haven't seen it with this PR applied.

**Comment by xavier-lc** [comment]
> Could we drop the number from the domain column header too?

@danielbachhuber Addressed on https://github.com/Automattic/wp-calypso/pull/93017/commits/893f4bfbcd0c3f1ffb96d8b26bb46599197fa778.

User can't select domains:
image

User can select domains:
image

**Pull request merged**
