### PR TITLE
Notifications - fix list item rendering

### LINKED ISSUE #46113: Notifications: List blocks are poorly rendered.
The block editor supports ordered and unordered blocks, both capable of having multiple indentation levels. Only top-level unordered lists are somewhat understandable in notifications – nothing else is.

Front-End | Notifications
--- | ---
Screen Shot 2020-10-01 at 3 57 36 PM | Screen Shot 2020-10-01 at 3 58 37 PM

### PR DESCRIPTION
**Pull request by blackjackkent**
#### Changes proposed in this Pull Request

* This PR, along with D50949-code, updates web notifications to properly render list items with appropriate list style and indentation.

#### Testing instructions

* Apply D50949-code in your sandbox and make sure the API is sandboxed.
* Apply this change to calypso, navigate to your Calypso dashboard and open a notification for a post with both ordered and unordered lists of multiple depths. Verify that all lists are displayed with correct numbering/discs and appropriate indentation.

Before:

image

After:

image

Fixes #46113

### CODE REVIEW

**Comment by kwight** [comment]
This looks great @blackjackkent , so much better! 🎉  Just wondering, is it possible to get the indent symbols closer to the editor as shown in the issue (eg. empty dot, square)? Not a blocker by any means.

I did notice a couple of minor regressions we should address before merging:

Item | Production | PR
--- | --- | ---
Block quotes | Screen Shot 2020-10-09 at 10 10 59 AM | Screen Shot 2020-10-09 at 10 12 45 AM
Code element | Screen Shot 2020-10-09 at 10 14 31 AM | Screen Shot 2020-10-09 at 10 14 22 AM

**Comment by blackjackkent** [comment]
@kwight That's weird. 🤔 I'm having trouble reproducing either of those regressions. In calypso with my branch checked out: 
image

I'll take a look at the unordered list bullet styling.

**Comment by blackjackkent** [comment]
Aha, never mind, I see the issue -- the regression was in comment notifications, not posts. On it. :)

**Comment by blackjackkent** [comment]
Per our discussion in slack -- the above regressions were specific to P2 comments; I was able to reproduce (and fix) the blockquote issue, although I could not reproduce the issue with code fences, which still appear to be rendering correctly on my branch for me.

Also added a change to reflect different list bullet styling at different indentation levels.

**Comment by kwight** [comment]
Fantastic! There's also letters and Roman numerals in ordered lists, but that can be a followup (they're much less common) 👍 

Front-End | Notification
--- | ---
Screen Shot 2020-10-09 at 12 35 09 PM | Screen Shot 2020-10-09 at 12 32 55 PM

**Review by kwight — APPROVED** [review]

**Pull request merged**
