### PR TITLE
Build: use shonkwrap to generate npm-shrinkwrap.json and update docs

### PR DESCRIPTION
**Pull request by gwwar**
This PR adds a newly generated npm-shrinkwrap.json from [shronkwrap](https://github.com/skybet/shonkwrap). The resolved/from fields have been removed where possible to allow us to use local repository settings.

## Testing Instructions 
- Run `make distclean` to delete local node_modules
- Run `npm install`
- Verify that Calypso works as expected and that tests pass.

cc @rralian @aduth @blowery

### CODE REVIEW

**Comment by aduth** [comment]
The `shonkwrap` docs are not especially reassuring :grimacing: 

>While we've used this and not had any issues, the shrinkwrap format is not currently documented or guaranteed not to change, so be careful.

**Comment by gwwar** [comment]
We could build our own tool though I'm not sure how much we'd write differently from: https://github.com/skybet/shonkwrap/blob/master/shonkwrap

**Comment by aduth** [comment]
Still not totally grasping the root of the problems, but looking at [`npm-shrinkwrap`](https://www.npmjs.com/package/npm-shrinkwrap) (as [recommended by npm team](https://github.com/npm/npm/issues/6444#issuecomment-58611066)), seems to seek to solve many of the problems we're facing (`resolved` discrepencies, post-shrinkwrap cleanup, minimal diffs, etc), and is quite popular.

**Comment by gwwar** [comment]
In our deployments, we want to use a mirror repository while not forcing folks in local envs to do so. We could have everyone point to the mirror, but I'm not sure if we'd like that.

**Comment by gwwar** [comment]
We could also ditch shrinkwrap for something like: https://github.com/mozilla/npm-lockdown

**Comment by blowery** [comment]
> We could also ditch shrinkwrap for something like: https://github.com/mozilla/npm-lockdown

+1 to that. I really like that it's tied into the package scripts.

**Comment by gwwar** [comment]
The npm-shrinkwrap.json file here need to be regenerated. I'll do that if this proposal gets the :+1:

**Comment by blowery** [comment]
I'm down with this. :ship: :speedboat: :racehorse:

**Pull request merged**
