### PR TITLE
Domains management i1: Bulk auto renew

### PR DESCRIPTION
**Pull request by p-jackson**
Related to https://github.com/Automattic/dotcom-forge/issues/3428

CleanShot 2023-08-23 at 15 09 24@2x

CleanShot 2023-08-23 at 15 09 48@2x

## Proposed Changes

* A bulk actions toolbar appears whenever a domain is selected
* Bulk auto-renew actions appear in a dropdown
* Makes network call to begin bulk action (you can view the request in the network tools, backend may not be complete)
* Adds a spacer to the top of the table where the search/filtering toolbars will eventually go

This PR doesn't add any progress, but that's coming as part of https://github.com/Automattic/dotcom-forge/issues/3419

The dropdown width changes a little bit when you go from having one domain selected to two domains selected. It happens because because text inside the dropdown changes from "... 1 domain" to "... 2 domains". I can't think of an elegant fix for this that works with translations.

## Testing Instructions

* Apply D119397-code and follow instructions to sandbox the async jobs
* Test the behaviour of selecting domains
* Feel free to click the button, although the underlying setting won't change
* Design should be pretty close to 31819-pb

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

**Comment by mpkelly** [comment]
Looks like a good start to me. I followed the test plan, and everything looks in order.

I noticed that whenever I check/uncheck a domain, the UI fires off a bunch of network requests. Try checking a domain, then view the network tab in your browser. You should see around 6 API calls. Then clear the network requests and click another checkbox, and you'll see more requests go out. 

In a later version, it would be nice to make only the domains table scrollable so the bulk controls are always in view.

**Comment by p-jackson** [comment]
>  it would be nice to make only the domains table scrollable so the bulk controls are always in view.

Yes I believe having a sticky header is part of the design. We do the same on the `/sites` page.

> You should see around 6 API calls.

Yeah 😞 things aren't super optimised yet. I don't think there's too much point yet because we're still figuring out how we'll make the network requests in such a way that we're able to sort columns. Once the network stuff is a bit more nailed down we can go through and figure out what's causing the re-fetching.

**Comment by mpkelly** [comment]
>I don't think there's too much point yet because we're still figuring out how we'll make the network requests in such a way that we're able to sort columns

Ok, I will merge this then and we can keep iterating.

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/8804405

Thank you @p-jackson for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/8804405).

**Pull request merged**
