### PR TITLE
My Sites: Remove lib/user from page.js handlers in my-sites/controller

### PR DESCRIPTION
**Pull request by blowery**
Reapplication of #27529

Testing instructions

Same as #27529, but be sure to test accessing themes logged out.

### CODE REVIEW

**Comment by blowery** [comment]
thanks @hewsut! e2e's are having some problems with media uploads. We're trying to figure it, but unrelated to this.

**Review by mhsdef — APPROVED** [review]
> e2e's are having some problems with media uploads. We're trying to figure it, but unrelated to this.

In that case, LGTM! 🚢

**Comment by alisterscott** [comment]
Unrelated to this PR the media uploading isn't working at all in Chrome on dserve - I've raised it here: https://github.com/Automattic/dserve/issues/69

So I put together a e2e PR to temporarily ignore these media tests on calypso.live so these are now passing against this PR 🎉

**Review by jsnajdr — APPROVED** [review]
Go Calypso class project, go! :+1:

**Pull request merged**
