### PR TITLE
Standardize margin for content panels and headers

### PR DESCRIPTION
**Pull request by paulopmt1**
Related to https://github.com/Automattic/dotcom-forge/issues/9946
Slack thread: p1732197974469459-slack-C04H4NY6STW

Video explaining the changes here: p1732818331404739/1732197974.469459-slack-C04H4NY6STW

## Proposed Changes

* Standardize Global navigation margin for content panels, headers and mobile navigation
* Header and content panels have inner-padding of 48px
* Mobile spacing works well on all screens

## Why are these changes being made?

* We want our users to have an unified experience through Dotcom

## Testing Instructions

Go to all these pages and ensure they follow the same spacing patterns:

* /sites
* /p2s
* /domains/manage
* /themes
* /plugins
* /plugins/manage
* /plugins/scheduled-updates

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
    - [ ] For UI changes, have we tested the change in various languages (for example, ES, PT, FR, or DE)? The length of text and words vary significantly between languages. 
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Review by lucasmendes-design — APPROVED** [review]
LGTM :)

**Review by candy02058912 — COMMENTED** [review]
We're almost there!!!! Thank you for working on this.

This is for when viewport is 600px
scheduled updates@2x

I think it's the last piece of the puzzle 🙏

**Comment by zaguiini** [comment]
Would it also be possible to standardize the title and subtitle fonts in the Scheduled Updates page in this PR? It looks completely off compared to the other pages.

image

**Comment by zaguiini** [comment]
There are some problems with the tablet version (~770px):

image

**Comment by zaguiini** [comment]
I also see some alignment issues in smaller screens now that we're removing the inline padding

image

**Comment by paulopmt1** [comment]
Thanks for following-up with it @zaguiini!

About the other alignment issues, I started a thread here to talk about it: p1732891117672139/1732197974.469459-slack-C04H4NY6STW

**Review by zaguiini — APPROVED** [review]
There are some other inconsistencies but generally it's a great improvement.

**Pull request merged**
