### PR TITLE
Vdimitrakis/selfserve 222 replace promoted to blaze

### PR DESCRIPTION
**Pull request by therocket-gr**
#### Proposed Changes

This task is to rename "Promoted Posts" to "Blaze" and replacing some strings for the Calypso interface

proposed changes are documented below:

1. In pages list

before:
Screenshot 2022-12-28 at 18 16 50

after: 
Screenshot 2022-12-28 at 18 16 22

2. in posts list

before:
Screenshot 2022-12-28 at 18 15 42

after: 
Screenshot 2022-12-28 at 18 16 12

3. in widget header bar

before:
Screenshot 2022-12-28 at 18 15 17

after: 
Screenshot 2022-12-28 at 18 14 46

4. in admin home 

before:
Screenshot 2022-12-28 at 18 10 59

after: 
Screenshot 2022-12-28 at 18 11 30

5. in admin home (features boxes)

before:
Screenshot 2022-12-28 at 18 10 48

after: 
Screenshot 2022-12-28 at 18 10 10

6. in /advertising/blog_url (in the list elements)

before:
Screenshot 2022-12-28 at 18 09 34

after: 
Screenshot 2022-12-28 at 18 09 11

changes highlighted:

Screenshot 2022-12-28 at 18 09 11

7. in /advertising/blog_url (when the site is private)

before: 
Screenshot 2023-01-03 at 12 24 52

after: 
Screenshot 2023-01-04 at 12 08 01

8. in the same page (when the site is not published)

before: 
Screenshot 2023-01-03 at 12 22 07

after:
Screenshot 2023-01-04 at 12 07 43

I am using the branch of the epic ([SELFSERVE-206) as the main branch to merge in trunk. and i am making other branches with changes so that we can review and approve those (and merge them in the epic main branch) to make it easier to review each change... when all is ok we can merge the main branch into trunk

#### Testing Instructions

I think most changes are straightforward and simple text replacements.. just checkout the branch and check that changes are ok and according to the figma files

#### Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

Related to #

### CODE REVIEW

**Review by jjolmo — APPROVED** [review]
LGTM

**Comment by therocket-gr** [comment]
I am creating a new comment with all updates from the 3rd update and iteration for this task..

1. in the pages and post list, we changed the copy and the icon as it appears below
Screenshot 2023-01-10 at 14 48 44

Screenshot 2023-01-10 at 14 45 17

2. in /advertising page we have updated some texts, the banner on top with a new illustration and the copy for the button (changed back to Promote)

Screenshot 2023-01-10 at 14 57 44

3. in quick links the icon changed to the new graphic
Screenshot 2023-01-10 at 14 48 34


4. in /home the banner was updated with new graphic

Screenshot 2023-01-10 at 14 36 54

**Review by jjolmo — APPROVED** [review]

**Comment by therocket-gr** [comment]
One more update here

1. in home the text was updated as it appears below

Screenshot 2023-01-10 at 15 32 21

2. In /advertising a new condition was added..

now if there are campaigns set for the user the subtitle will show (ss below)
Screenshot 2023-01-10 at 15 32 33

if no campaigns are found.. then the banner will appear (and subtitle stays hidden)
Screenshot 2023-01-10 at 15 33 57

**Review by jjolmo — APPROVED** [review]

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/7723416

Thank you @therocket-gr for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/7723416).

**Pull request merged**
