### PR TITLE
Add atomic hosting eligibility check to limit rollout to new sites

### PR DESCRIPTION
**Pull request by glendaviesnz**
#### Changes proposed in this Pull Request

* Adds a selector which limits atomic hosting feature to new sites

#### Testing instructions

* Checkout this PR and check an Atomic site with an ID > 168768859 and the hosting menu options should still appear
* Check again with an ID < 168768859 and their should be no hosting menu options

Implements UI part of  #37236

### CODE REVIEW

**Comment by glendaviesnz** [comment]
Just noticed that although the menu option does not appear for older sites it is still possible to go direct to the /hosting/domain url in older sites - I think the 'hosting/non-atomic-support' feature flag is taking priority in the controller on calypso.local - will look at that on Monday unless someone else wants to investigate before then.

**Comment by gwwar** [comment]
For the client logic I'd recommend splitting this out into 2-3 selectors depending on needs. This can maybe be solidified by moving more of this to the API later.

- Can the site use the feature?
- Is the site eligible for the feature?
- Can a site see the section?

**Comment by gwwar** [comment]
@glendaviesnz Took a look and I pushed a commit to the branch that should fix behavior. If we get approval on the server/client pieces, feel free to land on Monday. Don't forget to cc early testers @automattic-ian and @noteeth before doing so.

**Comment by glendaviesnz** [comment]
> Took a look and I pushed a commit to the branch that should fix behavior

Nice, that is much tidier, thanks, tests well for me.

**Comment by glendaviesnz** [comment]
Have tried multiple times to get tests to complete successfully and the one remaining failing test is related to adding new tags to a post, which is unrelated to this PR - testing adding new tags to a post locally and there don't appear to be any issues, so going to go ahead and merge this.

**Pull request merged**
