### PR TITLE
Atomic: Add blacklisted plugins from April 2019 and May 2019

### PR DESCRIPTION
**Pull request by arunsathiya**
#### Changes proposed in this Pull Request

- Add list of blocked plugins from April and May of 2019. 
- These plugins are not compatible on the Atomic environment.
- Details: p9F6qB-2I5-p2

List of plugins blocked:

- powered-cache
- broken-link-checker
- mycred
- userpro
- clearfy
- cornerstone
- facetwp-manipulator
- popup-builder
- under-construction-page
- wp-optimize-by-xtraffic
- wp-phpmyadmin-extension

#### Testing instructions

- Checkout the live branch available below
- Visit the plugins page for an Atomic site
- Search for the blocked plugins (can be seen on the `Files changed`) list of this PR
- Attempt to install it
- Note that the installation does not go through

### CODE REVIEW

**Comment by arunsathiya** [comment]
@donpark Do you suggest removing `userpro` from Calypso in that case? 

I am thinking it's fine to leave it as is, to maintain parity between the two files (Calypso and wpcomsh). 🤔

**Comment by donpark** [comment]
> @donpark Do you suggest removing `userpro` from Calypso in that case?
> 
> I am thinking it's fine to leave it as is, to maintain parity between the two files (Calypso and wpcomsh). 🤔

I agree.

**Comment by arunsathiya** [comment]
@donpark I am sorry to ask again, but I am not following your last comment. :) Are we deciding not to remove `userpro` from the Calypso file?

**Comment by donpark** [comment]
> @donpark I am sorry to ask again, but I am not following your last comment. :) Are we deciding not to remove `userpro` from the Calypso file?

Yes. Let's keep `userpro` for parity sake.

**Comment by arunsathiya** [comment]
Holding off for now. Details - p9GEWz-7C-p2

**Comment by arunsathiya** [comment]
The guild had been busy over the past few months with various other projects. Merging this for now without holding. We can revisit any necessary changes in the future. Rebased with latest master.

**Pull request merged**
