### PR TITLE
Include Powered by Titan logo on email comparison page

### PR DESCRIPTION
**Pull request by daledupreez**
#### Changes proposed in this Pull Request

* This PR adds the "Powered by Titan" logo to the email comparison page

#### Testing instructions

* Ensure you are running with the `titan/phase-2` feature flag enabled.
* Go to Manage -> Domains, and click on the "Add" button for a domain you own.
* Verify that the "Powered by Titan" logo is present and looks good.

email_comparison_powered_by_titan_i2

### CODE REVIEW

**Comment by stephanethomas** [comment]
Just passing by it would be great to add a screenshot to the description for those types of visual changes as this really helps reviewers to understand how things should actually look like 🙂.

**Comment by daledupreez** [comment]
Sorry about that! Screenshot attached.

**Review by eltongo — APPROVED** [review]
Tested both with the flag enabled and disabled -- works great :shipit:

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/5472046

Thank you @daledupreez for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/5472046).

**Pull request merged**
