### PR TITLE
CPT: Improve reliability of lists screen placeholders, requests

### PR DESCRIPTION
**Pull request by aduth**
This pull request seeks to resolve a few edge cases I had observed in switching between statuses in the [custom post types list screen](http://calypso.localhost:3000/types/post), specifically related to optimizations done by `react-virtualized` to avoid calling the `rowRenderer` or `onRowsRendered` callbacks when either the row count has not changed, or the rendered index range has not changed.

Notably, I found that issues would occur when...

1. Navigating from a filter where one post exists to one where two posts exist, then switching back to the first filter (issue is that because row count has not changed, 2 posts = 1 post + 1 placeholder in refreshing the original filter)
2. Navigating from a filter where one post exists to one where one post exists (`onRowsRendered` won't be invoked because range hasn't changed, so `this.state.requestedPages` will be reset to an empty array but the `setRequestedPages` logic won't run and the data won't be refreshed)

__Implementation notes:__

Hopefully the changes here will be seen as a simplification. Rather than try to account for placeholders in the row count, I've made it so that they are rendered separate from the list itself. This alleviates the first problem. To fix the second, I apply a `key` to the `WindowScroller` component corresponding with the serialized query. Therefore, when the query (filter) changes, a new rendered instance will be created and `onRowsRendered={ this.setRequestedPages }` will be invoked.

__Testing instructions:__

I found it easiest to test with the following distribution of posts:

Status distribution

(Two statuses where counts are the same, another where there's one more post)

Ensure that switching between filters, fresh posts are always requested, reflected by placeholders in the following configuration:

- When loading or refreshing first page of data, placeholder shown as first entry and all known posts shown below
- When more than one page exists, placeholder shown at end of list while loading next page, until all items have been exhausted

cc @timmyc 

Test live: https://calypso.live/?branch=fix/cpt-query-change-requests

### CODE REVIEW

**Comment by timmyc** [comment]
> Hopefully the changes here will be seen as a simplification.

👍  - so this does remove the rendering of the placeholder above or below that was seen before correct ( or at least I seem to remember seeing the loading indicator being shown at the top of the list at times )

**Comment by aduth** [comment]
@timmyc The current behavior should remain unaffected. Top-of-list placeholder for "fetching latest", bottom-of-list placeholder for "fetching next page".

**Comment by aduth** [comment]
Of course, I'm open to discussing whether this is too confusing. The idea was to address cases where returning to a filter where we've already requested posts would show the posts but have no indication that they were possibly stale (and that we're requesting in the background).

**Comment by mtias** [comment]
> would show the posts but have no indication that they were possibly stale (and that we're requesting in the background).

I don't think we should show this with a placeholder at the top. In the most often case it's just a repeated flash of a placeholder bumping the height. We shouldn't have to signal there's a fetch happening because we want to do many of those via polling. We just need to handle what happens when fresh data replaces old.

**Comment by aduth** [comment]
@mtias At one point, @codebykat had mentioned this as a point of confusion, as it can seem unexpectedly sudden when the posts change after a few seconds of having navigated to the page. It's a point I empathized with, hence including the placeholder as an indicator of something happening.

That said, it would simplify the implementation a bit to remove it, and I agree it could be equally confusing to have variations of placeholder positioning depending on the "type" of request being performed.

**Comment by aduth** [comment]
If height adjustment is the primary concern, maybe we could explore other options with an indicator above or adjacent to the posts list? Or an overlay to indicate that the posts might be stale? Maybe even a condition to check when the posts were last requested, and changing behavior if we don't think anything is likely to have changed?

**Comment by mtias** [comment]
I think we should focus efforts on showing when something changed. I don't care that there may be fetches happening to determine if something needs to be updated. If something is updated, we can then display something on the relevant post that changed or appeared.

**Comment by aduth** [comment]
Ok, removed first page loading indicator in 2a1c04c.

**Pull request merged**
