### PR TITLE
Store: Update/product categories data layer

### PR DESCRIPTION
**Pull request by coderkevin**
This commit changes the code from doing requests in an action thunk to
using the data-layer http mechanism.

To Test:
1. Run `npm test`
2. Run `npm start`
3. Visit the product create page and update pages and verify that the categories appear in the drop-down as they did before.

### CODE REVIEW

**Comment by coderkevin** [comment]
I thought what we agreed upon was to use the ERROR state, not necessarily what sort of event types. Let's talk about it with the team.

**Comment by justinshreve** [comment]
I moved this out of the needs review queue for now pending the update, and also wanted to make sure you saw the comment above.

**Comment by coderkevin** [comment]
This PR is on hold for a bit as the structure of this code may be changing.

**Comment by apeatling** [comment]
@coderkevin Is this still relevant or can we close?

**Comment by coderkevin** [comment]
Let's close it. Enough of the surrounding code has changed it will need to be worked on to be done.

**Pull request closed without merging**
