### PR TITLE
Move and modularise guided tour state

### PR DESCRIPTION
**Pull request by sgomes**
This PR is one of many working on modularising state in Calypso. This one handles guided tours, which until now live under `ui` but deserve their own top-level entry.

For more details on state modularisation, see the [modularised state documentation](https://github.com/Automattic/wp-calypso/blob/master/docs/modularized-state.md) and p4TIVU-9lM-p2.

Note: I added all the reviewers that GitHub suggested. Please feel free to ignore the review request or pull in someone else if you're not comfortable reviewing this PR. Thank you!

#### Changes proposed in this Pull Request

* Move guided tours state out of `ui` and into a new top level entry
* Modularise it
* Split `guided-tours/contexts` monolithic module into smaller ones.

#### Testing instructions

Guided tour state is always loaded on (logged-in) boot, and that appears to be an intentional architectural decision. However, that makes it difficult to see the state going from unloaded to loaded, as it happens without user input on boot, so it's difficult to test the automatic state loading part of the PR. That's not a big concern, however; the important thing is to ensure that nothing is getting broken.

With that in mind, in order to verify that this change works correctly, please smoke test guided tour functionality and ensure that it continues to work as before.

### CODE REVIEW

**Comment by sgomes** [comment]
Rebased to fix conflicts.

**Comment by sgomes** [comment]
@saramarcondes: I think this PR may address part of #43395. See 05c87046d9df70e0065fc80121f97b60461b4423.

**Comment by sgomes** [comment]
Rebased to fix conflicts.

**Review by wp-desktop — DISMISSED** [review]
WordPress Desktop CI Failure for job "wp-desktop-source".

@sgomes please inspect this job's build steps for breaking changes at [this link](https://circleci.com/gh/Automattic/wp-calypso/802060). For temporal failures, you may try to "Rerun Workflow from Failed".

Please also ensure this branch is rebased off latest Calypso.

**Comment by belcherj** [comment]
The above failure of the desktop tests is valid.

**Comment by sgomes** [comment]
Looks like further usage of the imports being changed has popped up since this PR was opened. Taking another pass.

**Comment by sgomes** [comment]
Actually, it was a bad merge from the earlier rebase. Fixed.

**Comment by sgomes** [comment]
Thank you for verifying the failure before I even had a chance to notice it, @belcherj! 😄

**Comment by sgomes** [comment]
Looks like everything is working correctly now, with the E2E error appearing to be transient. Any chance of a review before new conflicts pop up?

**Comment by sgomes** [comment]
Rebased again to fix new conflict.

**Review by wp-desktop — DISMISSED** [review]
WordPress Desktop CI Failure for job "wp-desktop-source".

@sgomes please inspect this job's build steps for breaking changes at [this link](https://circleci.com/gh/Automattic/wp-calypso/812956). For temporal failures, you may try to "Rerun Workflow from Failed".

Please also ensure this branch is rebased off latest Calypso.

**Comment by nsakaimbo** [comment]
Looks like a legitimate failure in the wp-desktop source build:

```
$ check-npm-client && node ${NODE_ARGS:---max_old_space_size=8192} ./node_modules/webpack/bin/webpack.js --config client/webpack.config.js --display errors-only && yarn run build-languages-if-enabled
 
ModuleNotFoundError: Module not found: Error: Can't resolve 'state/ui/guided-tours/actions' in '/home/circle
```

**Comment by sgomes** [comment]
I probably missed something in the merge conflict. Taking a look.

**Comment by sgomes** [comment]
Merge conflict properly resolved, ready for review again.

**Comment by lsinger** [comment]
@sgomes thanks for your work on this. It's been some time since I've contributed to Calypso, so I can't speak to the actual code changes. 

> Guided tour state is always loaded on (logged-in) boot, and that appears to be an intentional architectural decision

Yes, Guided Tours needs to be able to initiate a tour based on certain properties. E.g., [the media basics tour](https://github.com/Automattic/wp-calypso/blob/master/client/layout/guided-tours/tours/media-basics-tour/meta.js) should be triggered for all new users on a desktop viewport size when they visit `/media` (and they haven't seen the tour yet). 

The tours triggered by a button click in the getting started list seem to work fine. However, the media basics tour didn't trigger for me initially. It only triggered when I edited the URL to say `/media` exactly (without the added site slug) and hit enter. I'm not sure what then really triggered the tour starting -- the changed URL or simply the reload. 

In any case, a new user visiting the media library for the first time should be seeing the tour automatically trigger when visiting from a desktop-sized viewport.

**Comment by sgomes** [comment]
Hey @lsinger !

Sorry I've only been able to get back to this now, as I took a shift into other projects. Sorry about the ping, please let me know if I should be looping in someone else!

I'm not entirely clear on your comment whether there is an issue with this PR or with the media guided tour in general? In any case, I can't seem to reproduce; the media tour appears to work for me in a newly created user, both in production and on this branch.

**Comment by lsinger** [comment]
> Sorry I've only been able to get back to this now, as I took a shift into other projects. Sorry about the ping, please let me know if I should be looping in someone else!

Nobody has been working on Guided Tours for quite some time, I think, so I'm not sure. Maybe @jsnajdr? He's in the list of requested reviewers already, though. 

> I'm not entirely clear from your comment whether there is an issue with this PR or with the media guided tour in general? In any case, I can't seem to reproduce; the media tour appears to work for me in a newly created user, both in production and on this branch.

OK, good to hear -- possibly something went wrong on my side then. 👍

**Comment by sgomes** [comment]
Everything is green after a rebase.

**Comment by saramarcondes** [comment]
> please smoke test guided tour functionality and ensure that it continues to work as before

@sgomes Do you have a link for how to do activate the guided tour? I'd love to review this PR for you to get it out of your hair but I'm not familiar with the feature.

**Comment by sgomes** [comment]
> @sgomes Do you have a link for how to do activate the guided tour? I'd love to review this PR for you to get it out of your hair but I'm not familiar with the feature.

Hey Sara! That would be amazing, thank you! 😄 There are probably better ways of doing this, but the only reliable way that I know of triggering a guided tour is by creating a new account, creating a free blog on it, and then visiting `/media` on it (for the media tour; there are others, but this is the one we've been discussing).

A small popup should appear a short time after loading `/media` in those circumstances.

**Comment by lsinger** [comment]
@sarahcada @sgomes Guided Tours has a mechanism for forcing a tour to start. You need to find the tour name, which is usually in `camelCase` in the tour's configuration file. Then add a query parameter with a key of `tour` and a value of the tour name. 

E.g., when you replace `SLUG` with one of your sites's slugs here, you should be able to trigger the tour called `mediaBasicsTour`: 

`https://wordpress.com/media/SLUG?tour=mediaBasicsTour`

**Comment by sgomes** [comment]
Thank you, @lsinger, I knew there had to be a better way! 😄

**Review by sarayourfriend — APPROVED** [review]
Armed with @lsinger's helpful advice I was able to test a guided tour and it worked great. Code of course LGTM 🤠

**Comment by sgomes** [comment]
Woohoo, thank you @saramarcondes! 😄 I'll get this merged tomorrow morning my time, when things are quieter 🙂

**Pull request merged**
