### PR TITLE
Documentation: update the section of "Our Approach To Data" which talks about the `connect` function

### PR DESCRIPTION
**Pull request by andfinally**
I think it would be helpful to add some more detail to the description of this function. 

Reading the current version it wasn't immediately clear to me what the function does. The sentence that said the app component "passes the posts to the component for rendering" confused me: I wasn't sure whether it was passing the posts to the visual component or to itself. It also took me a while to understand the important point that the function adds extra props to a component.

I've added some details about what arguments are passed to `connect` in the examples, and how the function binds extra props to a component.

cc @aduth

### CODE REVIEW

**Comment by benhuberman** [comment]
Hey @andfinally -- below are some minor copy edits I'd suggest for house style consistency / clearer constructions when possible. I'll add that I'm entirely out of my depth on the content level, so focused exclusively on syntax/phrasing, etc.:

- "Below is an example of an app component **that** retrieves"
- "Both pass props to the component which respectively **provides** data and **set** the component up"  -- as long as the subject here is "the component" or the passing of props. If both arguments provide data and set the component up, etc., then "respectively" doesn't really make sense -- it suggests a differentiation, of course.
- "after we pass it **to** the `mapStateToProps` and `mapDispatchToProps` functions"

One general observation: there's a lot of passive constructions here (multiple "passed" for example) -- some of these might be required because of the technical context or might very well be standard in this use case, but I just wanted to flag this in case you see opportunities to replace some of them with active constructions -- these tend to be clearer to parse.

Let me know if you have any other questions, or if a second pass could help (in case you make additional tweaks, for example).

**Comment by andfinally** [comment]
Thanks @benhuberman, great feedback! I've tried to address your points. Turns out "which" for "that" is British - I never realised there was that difference. It's hard to avoid the passive voice in this situation, when I'm talking about function arguments, but I've hopefully improved the construction a bit.

**Comment by benhuberman** [comment]
> Turns out "which" for "that" is British
Yeah, I think UK English is more permissive when it comes to "which," which in US usage is mostly reserved to starting a new relative clause. And understood re: passive use; I assumed that several of these are just standard terms in this context.

**Comment by aduth** [comment]
(I'm unable to merge these changes until later in the day, but will plan to take care of this on your behalf)

**Comment by andfinally** [comment]
Great, thanks Andrew!

**Pull request merged**
