### PR TITLE
WooExpress Trial: Update copy for assignTrial step

### LINKED ISSUE #72168: WooExpress Flow: Update copy on processing steps
The `siteCreation` and `assignTrial` steps should have a title of

> Woo! We’re creating your store 

image

`processing` step message should stay the same.

### PR DESCRIPTION
**Pull request by sixhours**
#### Proposed Changes

* Update "Setting up your trial" to "Woo! We're creating your store" while processing
* I didn't see copy on the site creation step but let me know if I missed it :) 

**Before**
Screen Shot 2023-01-17 at 1 23 54 PM

**After**

Screen Shot 2023-01-17 at 1 18 14 PM

#### Testing Instructions

* Switch to this PR, navigate to `/setup/wooexpress`
* You should see the above copy change while your site is being created and set up

#### Pre-merge Checklist

- [x] Has the general commit checklist been followed? (PCYsg-hS-p2)
- NA [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [x] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [x] Have you checked for TypeScript, React or other console errors?
- NA Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [x] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- NA For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

Fixes #72168

### CODE REVIEW

**Comment by markbiek** [comment]
There isn't copy on the `siteCreationStep` but maybe we should add the same copy we have here.

Most people don't see the `siteCreationStep` because it processes so quickly but it _is_ possible to see it if you have a slower connection.

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/7751283

Thank you @sixhours for including a screenshot in the description! This is really helpful for our translators.

**Review by markbiek — APPROVED** [review]
LGTM!

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/7751283).

**Pull request merged**
