### PR TITLE
update domain upsell illustration and content

### PR DESCRIPTION
**Pull request by madhusudhand**
Fixes https://github.com/Automattic/dotcom-forge/issues/9772

## Proposed Changes

* Updated illustration from new designs
* Updated card description.

| Before | After |
| --- | --- |
| image | image |

## Why are these changes being made?

* To enhance wordpress.com experience.

## Testing Instructions

* Validate the new UI and description
* Validate with large custom domain name (it should show ellipsis)
* Validate with different admin color schemes.

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Comment by madhusudhand** [comment]
The illustration is aligned to bottom right corner as suggested in design.
But It has issues with smaller screens where the illustration is aliened to the bottom.

image

**Review by taipeicoder — APPROVED** [review]
LGTM 👍

**Comment by taipeicoder** [comment]
Left a non-blocking comment in pbxlJb-6BW-p2#comment-4073

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/17008447).

**Pull request merged**
