### PR TITLE
Update marketplace search by author

### PR DESCRIPTION
**Pull request by epeicher**
#### Proposed Changes

* Implement functionality to filter by Author in Marketplace search

#### Testing Instructions

- Enable the feature flag `marketplace-jetpack-plugin-search` for example adding this query parameter to the URL `flags=marketplace-jetpack-plugin-search`
- Go to `/plugins/<your site>` and click on any Plugin
- On the Plugin Details page, click on the author link under the `Developer` label
- Check the plugins listed are filtered by the search term `developer:<clicked developer>`
- Check that the results are indeed filtered by that Author

CleanShot 2022-06-22 at 11 32 41@2x

Fixes #https://github.com/Automattic/wp-calypso/issues/64801

### CODE REVIEW

**Review by WBerredo — COMMENTED** [review]
Tested it and seems to work for base cases but apparently it doesn't have the same accuracy as WP.org search.

I tested with `litespeedtech` (which I picked from a plugin page) and I didn't receive any results with ES, but I do get 2 results with the current version in prod.

| This branch (ES)  | Prod (WP.org) |
| ------------- | ------------- |
|Screen Shot 2022-06-23 at 14 05 00|Screen Shot 2022-06-23 at 14 05 19|

**Comment by WBerredo** [comment]
Another issue I'm seeing is a discrepancy between the author shown on the Plugins Browser page and the Plugin Details page. Probably it is not on the scope of this PR, but I would like to make sure we are tracking it somewhere.

| Plugins Browser  | Plugins Details |
| ------------- | ------------- |
|Screen Shot 2022-06-23 at 14 09 29|Screen Shot 2022-06-23 at 14 09 52|

**Review by gcsecsey — APPROVED** [review]
Changes LGTM, and works as described! 🎉 

I also noticed the discrepancies between the author name and the author slug that the search is based on. I think that we should investigate if we can find a more robust way of mapping the author display name to the same username, even across WP.org and WC.com.

**Comment by gcsecsey** [comment]
> Another issue I'm seeing is a discrepancy between the author shown on the Plugins Browser page and the Plugin Details page. Probably it is not on the scope of this PR, but I would like to make sure we are tracking it somewhere.

@WBerredo we've talked about this on Slack with @epeicher, I just thought to write it here as well for visibility.

The main problem with this is that the same author username is displayed differently on WP.org as well, so it is how we receive the data. (eg. [wordpress.com/plugins/pushpress](http://wordpress.com/plugins/pushpress) and https://wordpress.org/plugins/pushpress)

**In the current state**, to make the author names consistent, we could add a temporary map on the API with the common occurences (eg. `automattic`, `yoast`), that always displays the author name the same way for a given username.

**Long term**, the author names on the search and plugin details pages will be consistent, as we transition the details page to use the search API in #64891. Then, it can still be an issue that the same author is displayed with different names, so to resolve that we can still maintain the mapping on the API if needed.

**Comment by epeicher** [comment]
Thanks for your comments, I have created a follow up task 
- https://github.com/Automattic/wp-calypso/issues/64939 

that we can use to continue with the investigations and apply the required changes. 

@WBerredo are you happy if I merge these client-side changes that are nonetheless required and we use the follow-up task for updating the filtering?

**Comment by WBerredo** [comment]
> @WBerredo are you happy if I merge these client-side changes that are nonetheless required and we use the follow-up task for updating the filtering?

Yes, happy with this approach.

**Review by WBerredo — APPROVED** [review]
LGTM! 

It should be enough on Calypso's side and we can refine the search on the follow-up issues.

**Pull request merged**
