### PR TITLE
chore: update yarn to version 3.2.

### PR DESCRIPTION
**Pull request by worldomonation**
#### Proposed Changes

This PR updates `yarn` to version 3.2.

**Context**
When using `node 16.17.0` on macOS Monterey 12.6 / M1, I run into this error when attempting to install dependencies:

```
➜  ~/workspace/wp-calypso-third git:(trunk) nvm use 16.17
yarnNow using node v16.17.0 (npm v8.15.0)
yarn
➜  ~/workspace/wp-calypso-third git:(trunk) yarn
Internal Error: Unable to deserialize cloned data due to invalid or unsupported version.
    at Object.deserialize (node:v8:366:7)
```

However, if the version of `yarn` is updated to 3.2, this issue disappears completely:

```
➜  ~/workspace/wp-calypso-third git:(trunk) yarn set version 3.2
➤ YN0000: Retrieving https://repo.yarnpkg.com/3.2.3/packages/yarnpkg-cli/bin/yarn.js
➤ YN0000: Saving the new release in .yarn/releases/yarn-3.2.3.cjs
➤ YN0000: Done in 0s 909ms
➜  ~/workspace/wp-calypso-third git:(trunk) ✗ yarn
➤ YN0000: ┌ Resolution step
➤ YN0000: └ Completed in 34s 755ms
➤ YN0000: Done with warnings in 57s 198ms
```

#### Testing Instructions

Ensure the following build configurations are passing:
  - [x] Calypso E2E (desktop)
  - [x] Calypso E2E (mobile)
  - [x] Pre-Release E2E
  - [x] Unit Tests

#### Pre-merge Checklist

- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?

Related to #

### CODE REVIEW

**Comment by worldomonation** [comment]
What I'm a little confused by is how no one else has made noise about how `yarn 3.1.1` and `nodejs 16.17.0` hasn't played well together. Could it be that this is merely a problem with my own environment? I don't know and I'm open to hearing thoughts.

**Comment by noahtallen** [comment]
Yeah, not sure! I'm on M1 Pro and macOS 12.5.1 with node v16.17.0 and yarn v3.1.1 and am not experiencing issues. 

Perhaps it's the 12.6 update for macOS? It just reminded me to update today

**Comment by noahtallen** [comment]
Either way, good to upgrade :)

**Review by noahtallen — APPROVED** [review]
LGTM! Glad this was pretty straightforward. I think it'd be worth triggering the base image build after merging as well

**Pull request merged**
