### PR TITLE
Add/webpack dashboard

### PR DESCRIPTION
**Pull request by dmsnell**
Replaces #7476 

See: https://github.com/FormidableLabs/webpack-dashboard

This PR is an attempt to start using the new webpack dashboard plugin
which organizes the webpack output into a windowed console UI, showing
additional information beyond build status such as bundle and asset
sizes and also clean error messages.

The updated dashboard communicates to **webpack** via sockets and has resolved most of the issues preventing me from incorporating it earlier (stdout output).

There are two display modes: the standard mode shows bundle sizes and modules while the minified mode hides these. I have chosen the minimal mode as the default thinking it makes a better use of screen space for most development operations. For some time I tried to allow some command-line environment-variable override but I could not get this working how I wanted to in the `Makefile`

If someone with better **Make** skills than I have would like to clean this up it would help considerably. In the meantime, in order to see the more verbose output, one can simply remove the `-m` from the `Makefile` inside of the `run:` target.

Additionally we could create a second make target but that didn't seem appropriate here.

**Minimum Dashboard**
minimumdashboard

**Verbose Dashboard**
verbosedashboard

cc: @aduth @blowery @mtias

### CODE REVIEW

**Comment by ehg** [comment]
It's not clear to me why we need this, what's the rationale? :)

**Comment by aduth** [comment]
Previous PR has a bit of rationale: #7476

**Comment by dmsnell** [comment]
I have updated the description with some of the rationale from the earlier PR. @ehg the main reason I wanted this was the progress bar for status and also because it makes code errors really nice to view. 

Currently it can be a mess of scrolling but with this PR, the errors both jump out and are syntax-highlighted in the console.

**Comment by ehg** [comment]
> the main reason I wanted this was the progress bar for status and also because it makes code errors really nice to view.

Yeah, that's a good reason. I'm just worried about adding yet-another-dependency, and whether we'll have headaches with `webpack2` compat down the road.

Since this is optional now, I'd say merge it, and see if people find it useful :)

**Pull request merged**
