### PR TITLE
Checkout: Use CartMessages to display cart error messages in new checkout

### PR DESCRIPTION
**Pull request by sirbrillig**
#### Changes proposed in this Pull Request

Old checkout had a component called `CartMessages` which displays error messages returned by the `shopping-cart` endpoint. New checkout instead uses the hook `useDisplayErrors`. The important difference between these is that `CartMessages` replaces certain messages (those that contain inline HTML) with React versions.

This PR switches new checkout to use `CartMessages` instead. It preserves `useDisplayErrors` for loading errors, though.

As a side effect, this will also display any success messages from the `shopping-cart` endpoint (assuming there are no errors; I'm not sure why that's the case but it's the logic that was present in old checkout), which previously were being ignored in new checkout.

As another side effect, previously if there were multiple error messages, the notifications module would only display the last one. `CartMessages` combines messages so that the module will display all messages together.

Requires D48744-code to be merged first.

Fixes https://github.com/Automattic/wp-calypso/issues/45252

#### Screenshots

Before:

Screen Shot 2020-08-27 at 6 55 44 PM

After:

Screen Shot 2020-08-27 at 6 26 04 PM

#### Testing instructions

- Apply D48744-code.
- Add a product to your cart, load checkout, and verify that there are no error messages displayed.
- Try to purchase when purchases are blocked (for testing this, you can apply D48747-code) and verify that you see an error message with a link that works, rather than raw HTML.
- Try to cause other error messages in the cart if you can and verify that they are displayed correctly.

### CODE REVIEW

**Comment by nbloomf** [comment]
I saw a bit of odd behavior, but I'm not sure if it's due to this change. Here are the steps to reproduce:

- Enter checkout
- Apply a valid coupon, triggering the success notification
- Close the notification and click "Save Order" to continue checking out
- Change the selected payment method.

This triggered a second coupon success notification, and I was able to reproduce it twice.

IIRC the way coupon notifications are triggered might depend on some cached state in the stored cart, which might be causing this.

**Comment by nbloomf** [comment]
In the testing instructions, do you mean D48747-code?

**Comment by sirbrillig** [comment]
> In the testing instructions, do you mean D48747-code?

I meant both D48744 and D48747. The former is required for the new data from the endpoint to prevent duplicate notifications, and the latter is to add an error for testing.

**Comment by sirbrillig** [comment]
> This triggered a second coupon success notification, and I was able to reproduce it twice.

This is interesting. Are you sure you had D48744-code applied? I wasn't able to reproduce this unless I removed that patch.

**Comment by nbloomf** [comment]
I did not have D48744-code applied- that explains that :)

**Pull request merged**
