### PR TITLE
Gutenberg: Update e2e tests for v6.5.0.

### PR DESCRIPTION
**Pull request by kwight**
Update e2e tests for v6.5.0.

Our version of 6.5.0 includes cherry-picks of:
- de6df895c718e56e39f21d171207f1e64647b67f
- fa5a64edc26461288b0f1de8641aa693f4a122c4
- d9adf3b781fb7fbccc2b1c6e068adc27deb8dfac
- 20b30e044b6738b53a8262574278957ebf7465c1
- 00c6d183620e8384b856e0c48110c1df749d14c1

### CODE REVIEW

**Comment by mmtr** [comment]
Took a quick look at the failing tests today and I can confirm the Simple Payments block is currently broken on Horizon. I can insert the block, but it is not rendered on the front-end.

**Comment by kwight** [comment]
> Can revert the post to draft - [WPCOM] Calypso Gutenberg Editor: Posts (desktop) Revert a post to draft: @parallel Revert the post to draft

I can replicate the test fail with the `horizon` env, but don't understand the problem (the confirmation snackbar of reverting to draft displays as expected); applying 0b98392743435503c1c435cbb0059b9d74d069c3 by @mmtr seems to fix it though.

> Timed out waiting for element with css selector of '.jetpack-simple-payments-wrapper' to be present and displayed

There's a fix already in Gutenberg that corrects this; it needs to be patched into our 6.5 so we don't have to wait until the next release.

> no such element: Unable to locate element: {"method":"css selector","selector":".post-publish-panel__postpublish-header a"}

Tried applying 2249bcb2e3e013da1b06c7acc955a0a56515633c, but no go; will need to dig deeper.

**Comment by kwight** [comment]
@bsessions85 I'm struggling to make headway on these; would you be able to take a look for me please?

**Comment by bsessions85** [comment]
@kwight I just put in a fix for the selector for the page/post url that is now in the snackbar. The test will still fail, but it is because we're getting an alert when we try and click the link to visit the post/page after it is published. I think this is something that should be fixed because it basically tells the user that something isn't saved even though they just published.
image

**Comment by kwight** [comment]
> I think this is something that should be fixed because it basically tells the user that something isn't saved even though they just published.

Ah yes, I think this is what @mmtr was getting at with [this change](https://github.com/Automattic/wp-calypso/commit/2249bcb2e3e013da1b06c7acc955a0a56515633c#diff-77450bf032f03c9c64591ef8a0a8237eL89). The alert is caused by a bug that hasn't gotten any core attention yet. Is adding the `acceptAlertIfPresent` call good for now?

**Comment by Copons** [comment]
Is there an easy way to run these tests locally against Horizon?

Also, which specs should we test? Are `wp-calypso-gutenberg-page-editor-spec` and `wp-calypso-gutenberg-post-editor-spec` enough?

**Comment by bsessions85** [comment]
@kwight Yes, the `acceptAlertIfPresent` call will do the trick. I have committed that change now so those tests should now pass.

@Copons 
> Is there an easy way to run these tests locally against Horizon?

Yes, to run them locally, add this line to your decrypted config file:
`"calypsoBaseURL": "https://horizon.wordpress.com",`

> Also, which specs should we test? Are wp-calypso-gutenberg-page-editor-spec and wp-calypso-gutenberg-post-editor-spec enough?

Those specs should be enough. The `[Status] Needs e2e testing horizon` label will run all the tests but for Gutenberg work, those two spec files cover it all.

**Comment by kwight** [comment]
I've updated 6.5 to a custom build that should take care of the Simple Payments bug, and hide Social Links as experimental. Let's see what happens.

**Comment by kwight** [comment]
The gridicons fail in `wp-desktop` is likely due to https://github.com/Automattic/wp-calypso/pull/36204, being investigated by @sirreal .

**Comment by sirreal** [comment]
> The gridicons fail in `wp-desktop` is likely due to #36204, being investigated by @sirreal .

`wp-desktop` hasn't been building properly for a while and failures for that particular job should be safe to ignore. See https://github.com/Automattic/wp-desktop/issues/670

**Comment by kwight** [comment]
@bsessions85 any ideas on the return of these `invalid session id` problems? They seem sporadic.

**Comment by bsessions85** [comment]
@kwight I have been looking in to that and I think I have it narrowed down, but I haven't put in a fix yet. Just disregard those errors for now.

**Comment by kwight** [comment]
@bsessions85 thanks! they've disappeared again now anyways 👍

**Pull request merged**
