### PR TITLE
Token Field: First pass at isBorderless

### LINKED ISSUE #3084: Tokens: Extend token to have isBorderless prop
In [this comment](https://github.com/Automattic/wp-calypso/pull/3058#issuecomment-179957679), @rickybanister suggested:

> Can we create a 'light colored' prop for the token field? It would let you just type usernames and emails more like the original design (but with the 'x' next to them to clear)?

### PR DESCRIPTION
**Pull request by ebinnion**
Closes #3084 by adding an `isBorderless` prop to remove the background color from tokens. This is a WIP.

To test
- Checkout `update/token-field-borderless` branch
- Go to `/people/new/$site` in development
- Enter tokens. Notice the borderless style
- Go to `/post/$site` and enter tags/tokens
  - These should be unchanged

screen shot 2016-02-04 at 3 17 39 pm

cc @rickybanister for early design review

### CODE REVIEW

**Comment by ebinnion** [comment]
Updated so that the token text is `$gray-dark`.

screen shot 2016-02-04 at 4 08 24 pm

**Comment by rickybanister** [comment]
Looking good so far. I'll take it for a spin tomorrow and make sure we cover all the various hover and focuses and whatnot. We may be able to move the X closer to the text now that there isn't a 'tag' shape to help the visual.

**Comment by justinkropp** [comment]
> We may be able to move the X closer to the text now that there isn't a 'tag' shape to help the visual.

Agreed. The space between X and text now makes the X look a bit detached from the text it belongs to.

**Comment by rickybanister** [comment]
I just moved the X over a little bit and did away with a very annoying wiggle when adding the first token. The input is now exactly the same size as the token—this is more apparent with the isBorderless prop active, but still an improvement to the regular token field. 

Here it is:

screen shot 2016-02-05 at 3 29 16 pm

**Comment by roccotripaldi** [comment]
Code-wise this looks solid. Once you resolve the conflicts, I'd say ship it :shipit:

**Comment by ebinnion** [comment]
screen shot 2016-02-08 at 5 04 02 pm

Now that we have token validation as of #3096, I added some CSS that combines `isBorderless` with the validation. It'd be nice if we could find a better way of combining the two, but at least we are getting closer to what was originally mocked.

**Comment by ebinnion** [comment]
I removed the last commit which combined the `isBorderless` styles with validation. I'm going to work on those in a separate PR that way we can get this PR in.

**Pull request merged**
