### PR TITLE
Reader: Record the algorithm used for feed searches

### PR DESCRIPTION
**Pull request by blowery**
Record the algorithm used for a search and hand it back on subsequent requests for more pages.

### CODE REVIEW

**Comment by gibrown** [comment]
I added the algorithm as a top level part of the API response for feed search.

**Comment by blowery** [comment]
left to do: pick up the algorithm in the query component and pass it along via the action creator

**Comment by samouri** [comment]
What does this PR enable us to do that we couldn't do before?
Should it be a blocker for sites in search launch?

**Comment by blowery** [comment]
> What does this PR enable us to do that we couldn't do before?

Launch and use more than 1 algorithm for site results, with no need to change the client.

> Should it be a blocker for sites in search launch?

Nope.

**Comment by blowery** [comment]
Need to alter this to handle both the algorithm and switch to using page handles to page. That probably requires some hacks to how we use react-virtualized for paging to prevent it from requesting pages using offsets.

**Comment by apeatling** [comment]
@blowery Has this one still got a chance of merging?

**Comment by blowery** [comment]
@apeatling Canning this for now.

**Pull request closed without merging**
