### PR TITLE
composite-checkout: Replace TOS with CheckoutTerms

### PR DESCRIPTION
**Pull request by sirbrillig**
#### Changes proposed in this Pull Request

This PR replaces `WPTermsAndConditions` with the `CheckoutTerms` component from the regular checkout. 

Note that some of the styles are customized differently than the regular checkout; notably that the links are underlined.

**Before:**

Screen Shot 2020-03-09 at 8 31 41 PM

**After:**

Screen Shot 2020-03-09 at 8 46 54 PM

#### Testing instructions

Visit composite checkout with different combinations of products, particularly plan-only carts, domain carts, and multiple domain carts with different TLDs. Verify that the Terms of Service section looks the same as the non-composite checkout version.

### CODE REVIEW

**Comment by sirbrillig** [comment]
Wow, thanks for noticing that! I went back to using a `float` for the icon instead of flexbox and I think that's solved it:

Screen Shot 2020-03-10 at 11 20 23 AM

**Comment by fditrapani** [comment]
It felt easier to read when we were using the flex box. Rather than a float, can we absolutely position the icon and add some padding to the left side. Let me know if you need help with it.

**Comment by sirbrillig** [comment]
>  Let me know if you need help with it.

I could definitely use your CSS expertise. I tried a bunch yesterday but I couldn't figure it out. Should we just merge this now and do that separately?

**Comment by fditrapani** [comment]
I can pop in quickly and make an update.

**Pull request merged**
