### PR TITLE
Use the eslint-eslines utility instead of run-lint script

### PR DESCRIPTION
**Pull request by nosolosw**
As the number of places where run-lint script is used increases,
it is more time-consuming to port bugfixes and modifications.
By extracting its logic to an utility such as eslint-eslines,
we gain a central place to make and distribute the changes,
and also a way to document in what situations it is useful.

### CODE REVIEW

**Comment by unDemian** [comment]
@nosolosw does this still need review or is it still relevant?

**Comment by nosolosw** [comment]
@unDemian I've adapted this to the latest changes in the build process. Would you mind giving it a go?

How to test:

- pull PR
- break some eslint rule (for example, remove some spaces between parenthesis in some jsx file)
- commit the changes. Expected result is that you can't because of the changes.
- commit with `--no-verify` to ignore the git hook.
- `npm run lint:js` should report the same errors than the git hook before.
- push the changes to a new PR. Expected result is that CircleCI fails.

If all goes as described, it's working properly.

**Comment by nosolosw** [comment]
mmm, weird. This is what I'm doing:

```
git checkout -b test/add/eslint-eslines origin/add/eslint-eslines
npm run distclean
# break rule in wp-calypso/client/components/accordion/index.jsx for example
git add client/components/accordion/index.jsx
git commit -m 'test case' # it reports the errors and won't commit
git commit -m 'test case'  --no-verify # commit anyhow
npm run lint:js # it reports the errors.
git push origin test/add/eslint-eslines:test/add/eslint-eslines 
# CircleCI reports a linting error.
```

Would you mind sharing your steps, so we can find what's happening?

**Comment by nosolosw** [comment]
Just added a prevention measure: tell npm to install packages before running `lint:js` script, if they are not there.

**Comment by unDemian** [comment]
I switched to the branch, `npm install`, updated some code to fail linting, tried to commit and it worked. Updated some code again ran `npm run lint:js` which correctly threw an error. I will retry in a bit.

**Comment by unDemian** [comment]
I had the packages installed something went wrong with my git hooks, now everything seems back to normal. And this works as expected. 🚢

**Comment by nosolosw** [comment]
Thank you for testing Andrei! I'm heading for WCEU as we speak, so I plan to merge this on Monday.

**Pull request merged**
