### PR TITLE
[WIP] Updating parsing logic to account for blockquotes and horizontal rules in notifications

### LINKED ISSUE #45649: Notifications: Expand supported HTML elements.
Masterbar notifications support a very limited set of HTML tags (see `lib/class.notification-builder.phpL125`), causing block rendering to fail from missing elements. Let's expand the supported tags to include `p`, `div`, headings, `cite`, `blockquote`, and `hr` (and any other tags found lacking from blocks).

Screen Shot 2020-09-14 at 12 58 22 PM

Expanding tag support cannot cause regressions with mobile+web notifications.

See: paYKcK-FI-p2

### PR DESCRIPTION
**Pull request by blackjackkent**
#### Changes proposed in this Pull Request

* This pull request begins to address the issues in the web-based notification app, specifically the rendering of blockquotes and horizontal rules in a post detail view, by refactoring some of the formatting logic used to wrap segments of a post in `div`/`p` blocks for display.
* PR also includes some changes required to placate ESLint in the touched files.
* **WIP: Need to finalize styling choices, particularly for `cite` tag, but should be functionally testable.**

#### Testing instructions

* Apply D49621-code in your sandbox and make sure the API is sandboxed.
* Apply this change to calypso, navigate to your Calypso dashboard and open a notification for a post with a blockquote and horizontal rule in its contents. Verify that the blockquote and HR are styled distinctly from surrounding paragraphs.

image

Fixes #45649 / #45120

### CODE REVIEW

**Comment by mmtr** [comment]
> WIP: Need to finalize styling choices, particularly for cite tag, but should be functionally testable.

I think we can cover this in a follow-up as part of the "load block styles" part discussed in paYKcK-FI-p2. If we can manage to load the [styles defined for this block](https://github.com/WordPress/gutenberg/blob/master/packages/block-library/src/quote/theme.scss), we wouldn't need to set many styles in the notifications app (only if we want to modify the default style of the block to better adapt it to the notifications UI).

**Review by mmtr — COMMENTED** [review]
This is looking good, nice work @blackjackkent!

I tried with a post that contains quote and separator blocks and they look great:

Before | After
--- | ---
Screen Shot 2020-09-17 at 12 09 32 | Screen Shot 2020-09-17 at 12 09 41

However, I think this is introducing a regression and some newlines are now removed:

Before | After
--- | ---
Screen Shot 2020-09-17 at 12 12 21 | Screen Shot 2020-09-17 at 12 12 31

I find the content more readable with the extra spacing. Is there any way we can keep it?

**Comment by kwight** [comment]
Yep, `cite` and `hr` are looking good! We do have some regression with ordinary paragraphs (the same issue @mmtr mentions), which I think is caused by all content markup ending up under just one `wpnc__paragraph`:

Production | PR
--- | ---
Screen Shot 2020-09-17 at 10 34 42 AM | Screen Shot 2020-09-17 at 10 32 47 AM

**Comment by blackjackkent** [comment]
I spent a lot of time today refactoring this in a bunch of different ways but honestly the one that seems to work best is just applying a `<br />` tag in the case where the content being processed is a blank line.

```
if ( ! raw ) {
	return {
		out: out + '<br />',
		inFence,
		inList,
	};
}
```

I'm not 100% convinced this is the best solution, so I'm open to further suggestions, but it does maintain the purpose of this PR while addressing the regression @mmtr and @kwight mentioned. 🤔

**Comment by krymson24** [comment]
I tried testing this, but for some reason, notifications aren't showing up for blogs that I follow.

**Review by mmtr — COMMENTED** [review]
Tested again and noted that newlines are back, although the spacing is much higher now:

Production | This branch
--- | ---
Screen Shot 2020-09-18 at 11 07 04 | Screen Shot 2020-09-18 at 11 07 10

Seems to be caused by extra `br`s:
Screen Shot 2020-09-18 at 11 09 43

I also tested with a post that contains a variety of `blockquote`, `cite` and `hr` elements, using different blocks (Quote, Separator and HTML).

For reference, this is how the post looks in the editor and in the frontend:

Editor | Frontend
--- | ---
Screen Shot 2020-09-18 at 10 55 53 | Screen Shot 2020-09-18 at 10 56 10

And this is the before/after comparison:

Production | This branch
--- | ---
Screen Shot 2020-09-18 at 10 56 54 | Screen Shot 2020-09-18 at 11 16 23

The output is much nicer now, but I noted a couple of issues:
- Any `hr` element that precedes a `blockquote` element is rendered inside the quote, but it should be outside:
Screen Shot 2020-09-18 at 11 20 22
Screen Shot 2020-09-18 at 11 20 43

- Newlines inside `blockquote` and `cite` elements are not preserved:
Screen Shot 2020-09-18 at 11 21 26

> the `cite` is not.

@krymson24 I'm seeing the cite text ("blahblah") in your screenshot, and in my tests the `cite` markup is present as well. Can you clarify what do you mean when you say the cite is not there?

**Comment by krymson24** [comment]
@mmtr the `<cite>` text is there, but isn't the text suppose to be indented and italicized like the ones in your screenshot?

**Comment by blackjackkent** [comment]
After further investigation on this today it seems like the line breaks in blockquotes/cites are being lost on the PHP side before the data comes back from the api (those line breaks are not included in the ranges generated to indicate where the markup should be included). The issue with the positioning of the horizontal rule also seems like it comes from that part of the code as well, as the range for the `hr` and `blockquote` both have the same starting point, leading the Calypso-side parser to consider them interchangeable.

This is going to take some finagling to get right. A lot of edge cases at work here.

**Comment by mmtr** [comment]
> @mmtr the `<cite>` text is there, but isn't the text supposed to be indented and italicized like the ones in your screenshot?

@krymson24 Nope, that style is only for `blockquote` elements.

> This is going to take some finagling to get right. A lot of edge cases at work here.

@blackjackkent There is no need to solve them all here, just the ones that are affecting things that are working fine currently. To summarize, I identified 3 issues:
- **Spacing between paragraphs is higher now.** This is a regression introduced by current changes which will make some notifications to look worse than before, so I think we should fix it before landing.
- **`hr` rendered inside `blockquote`**. Fine to do in a follow-up. `hr` elements were not rendered at all previously so current changes will make things better.
- **Newlines inside `blockquote` and `cite` elements are not preserved**. Confirmed this was happening before too, so this is issue is unrelated to changes here. Fine to address it in a follow-up.

**Comment by blackjackkent** [comment]
@mmtr I'm having trouble reproducing the issue you mentioned regarding extra spacing. 🤔 This is what I'm seeing on my end:

image

image

Which I think looks about as we'd expect.

I'm doing a rebase off master and force push here on the off-chance there was something I hadn't pushed up that you weren't testing with.

**Comment by blackjackkent** [comment]
@mmtr There seemed to be a couple potential approaches for this but I think I've gone with the one that's most straightforward - I added some extra logic to skip adding the `<br>` if the following line is also an empty space. The end result here is that any number of consecutive newlines gets condensed to a single blank line, which seems preferable for an at-a-glance notification.

If we're comfortable with this, I can work on the other two issues you mentioned in a separate PR.

**Review by mmtr — APPROVED** [review]
Awesome! Tested a variety of notifications and they all looked great.

Screen Shot 2020-09-23 at 13 24 33

Screen Shot 2020-09-23 at 13 25 32

Screen Shot 2020-09-23 at 13 26 04

Screen Shot 2020-09-23 at 13 26 26

Screen Shot 2020-09-23 at 13 26 56

**Pull request merged**
