### PR TITLE
Nav sidebar: update MainDashboardButton slot usages

### PR DESCRIPTION
**Pull request by vindl**
#### Changes proposed in this Pull Request

Updates `MainDashboardButton` slot usages since it was moved from `interface` to `edit-post` package. See https://github.com/WordPress/gutenberg/pull/27213

**Note:** This shouldn't be merged to Dotcom until the corresponding Gutenberg plugin version (9.5) is deployed to production.

#### Testing instructions

- When Gutenberg 9.5 is available on Dotcom smoke test the Nav Sidebar and make sure that everything still works.

### CODE REVIEW

**Comment by vindl** [comment]
The test failures here are expected since the package changes have not been published yet.

**Comment by p-jackson** [comment]
I've just incorporated my feedback into this PR. It made more sense than leaving super specific feedback, but feel free to go ahead and change any of my changes.

In particular I've removed the unit test and replaced it with the e2e spec. Now that `MainDashboardButton` has moved from a bundled feature to one that's accessible on the `wp` global it no longer makes sense to test that the experimental feature happens to be available in the version that's in `node_modules`.

Once GB 9.5 is deployed to edge stickered sites we should be able to add the `[Status] Needs e2e Testing Gutenberg Edge` label to this PR to make sure tests pass.

**Comment by p-jackson** [comment]
Looks like GB 9.6 is deployed to edge sites now so this can be looked at again. Do you have idea about rollout plans for this @vindl? Do we need to merge this close to simultaneously with the rollout of GB 9.6?

**Comment by vindl** [comment]
> Looks like GB 9.6 is deployed to edge sites now so this can be looked at again. Do you have idea about rollout plans for this @vindl? Do we need to merge this close to simultaneously with the rollout of GB 9.6?

I assumed that we'd have to rollout simultaneously with GB 9.6, but I tested it on edge sites and it still works as expected, which would indicate that it's not necessary?

**Comment by vindl** [comment]
Closing in favor of https://github.com/Automattic/wp-calypso/pull/48729.

**Pull request closed without merging**
