### PR TITLE
Build: Move react-dom and redux-thunk into vendor, drop debug

### PR DESCRIPTION
**Pull request by blowery**
Drop debug becauase we no-op it for production and if it's in vendor, the no-op doesn't really take.

No functional changes here

### CODE REVIEW

**Comment by blowery** [comment]
cc @gwwar @aduth

**Comment by gwwar** [comment]
Any bundle size differences to look for?

**Comment by blowery** [comment]
should just be horse trading from build-production to vendor.

**Comment by gwwar** [comment]
👍  tests fine on local, docker, and desktop

**Comment by blowery** [comment]
new sizes:
```
vendor.production.js  1.76 MB
build-production.76e556718fdaed9100b8.js  3.67 MB
```

old sizes
```
vendor.production.js  1.19 MB
build-production.e6e223aa937832bffdf3.js  4.25 MB
```

**Comment by blowery** [comment]
Hrm, I didn't expect a 300kb move... react-dom and redux-thunk are both tiny.

**Comment by blowery** [comment]
ahhhh. sneaky. `react-dom` just requires `react/lib/ReactDOM` which then pulls in the planet.

**Pull request merged**
