### PR TITLE
A4A: Add a dismiss button for the Referrals guided tour.

### PR DESCRIPTION
**Pull request by jkguidaven**
| Before | After |
|--------|--------|
| Screenshot 2024-06-19 at 10 01 32 PM | Screenshot 2024-06-19 at 10 01 06 PM |

Closes https://github.com/Automattic/jetpack-genesis/issues/399

## Proposed Changes

* Add a dismiss button on the Guided Tour component. Update Referrals guided tour to use the new dismissible property.

## Testing Instructions

* Use the A4A live link and go to `/marketplace` page.
* Click the refers product tooltip to show the Guided tour. 
   Screenshot 2024-06-19 at 10 01 12 PM

* Confirm that the dismiss button is now visible.

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Review by yashwin — COMMENTED** [review]
Thanks for working on this.

The button is hardly visible here. Is it possible to change the button color?

@madebynoam: what do you think?

Screenshot 2024-06-19 at 7 39 26 PM

Also, I noticed the button is not clickable when this happens

**Comment by andrii-lysenko** [comment]
Maybe we could add `Close` button to the bottom right? Or it will be too much buttons there?

**Comment by jkguidaven** [comment]
I might have a solution. We can maybe darken the upper part of the images (like gradient) when hovered so they are more visible.

**Comment by jkguidaven** [comment]
@yashwin @madebynoam, this is what I came up with.


https://github.com/Automattic/wp-calypso/assets/56598660/4eec2593-fc89-4925-bf01-93cb3166091d

**Review by yashwin — APPROVED** [review]
Looks great!

**Comment by madebynoam** [comment]
Great points here! Thank you!
@jkguidaven That looks perfect!

**Review by madebynoam — APPROVED** [review]
Lgtm!

**Pull request merged**
