### PR TITLE
Plans: remove google analytics tests and deploy disabled page version.

### PR DESCRIPTION
**Pull request by mtias**
image

@rralian @artpi

### CODE REVIEW

**Comment by artpi** [comment]
I think that we should deploy all pending tests this week and then do **no changes** for a user for week or two.
We can work un "under the hood" improvements and designing proper funnels and then we can compare results from all the nudges in the same period.

Removing certain tests during the time others are gathering data introduces too much noise.

And, I feel that theres no harm in letting this sit for a while

**Comment by mtias** [comment]
This particular testing is flawed already with too small buckets, we need to clean things up before running the nudge or not nudge test.

**Comment by rralian** [comment]
> This particular testing is flawed already with too small buckets, we need to clean things up before running the nudge or not nudge test.

I totally agree with this. And we already have enough data to show that _any_ of the "disabled settings" variants outperform the old version significantly (that is by a wide margin and with statistical significance).

This looks good to me, 👍

**Comment by artpi** [comment]
:(

**Pull request merged**
