### PR TITLE
Editing Toolkit: Add block-editor preview button url override

### PR DESCRIPTION
**Pull request by jeyip**
## Context

**Notes:**
- We'll probably want to abstract this solution eventually because, although I haven't confirmed it, I imagine there are multiple instances of this class of custom domain mapping bug in the block-editor
- This solution **_only_** works for simple sites

Draft post previews return a 404 from within the block editor.

- The most likely culprit for this issue is https://github.com/Automattic/wp-calypso/pull/56899, which removed Calypso's implementation of the preview modal in favor of the core Gutenberg preview feature.
- We're seeing 404s because the core Gutenberg preview feature opens in a new window pointed at the simple site's mapped domain. 
- The previous implementation of the preview in a modal _did not_ open a new window and _did not_ navigate from site-slug.wordpress.com to the simple site's mapped domain
- The url pointing towards the preview, as far as I can tell, has not implemented any of the solutions discussed in p58i-2DN-p2 to circumvent third party cookie problems

## Proposed Changes

Use the the logmein query param to set cookies in a first party context for a simple site's mapped domain. PCYsg-A6p-p2

#### Verify Bug
- Open `chrome://settings/cookies?search=cookies` and verify that `Block third-party cookies in Incognito` is selected
- Open an incognito window
- Log in to WordPress.com
- Access a Simple site with a custom mapped/connected/registered domain already set as primary
- Don't access any other site settings or features
- Navigate to My Site > Posts and edit a draft post
- Verify that the preview returns a 404 ( https://custom-domain/?p={POST_ID}&preview=true in a new tab

#### Verify Fix
- Navigate to `apps/editing-toolkit`
- Check out this branch in a terminal
- Run `yarn dev --sync`
- Sandbox your sandboxed simple site's mapped domain, your sandboxed simple site's wordpress.com domain, and the public api
- Close any incognito windows and open a new one. 
- Log in to WordPress.com again
- Navigate to My Site > Posts and edit a draft post
- Verify that the preview returns the draft preview as expected

#### Verify Bug
- Open `about:preferences` and search for "cookies"
- Click on the "Strict" radio button
- Clear cache and cookies
- Log in to WordPress.com
- Access a Simple site with a custom mapped/connected/registered domain already set as primary
- Don't access any other site settings or features
- Navigate to My Site > Posts and edit a draft post
- Verify that the preview returns a 404 ( https://custom-domain/?p={POST_ID}&preview=true in a new tab

#### Verify Fix
- Navigate to `apps/editing-toolkit`
- Check out this branch in a terminal
- Run `yarn dev --sync`
- Sandbox your sandboxed simple site's mapped domain, your sandboxed simple site's wordpress.com domain, and the public api
- This might be unnecessary, but to ensure a completely reset environment, clear all cache history and cookies again
- Log in to WordPress.com
- Navigate to My Site > Posts and edit a draft post
- Verify that the preview returns the draft preview as expected

#### Verify Bug
- With default security and privacy settings, third-party cookies prevented
- Clear cache and cookies ( History > clear history... > all history in mac topbar )
- Log in to WordPress.com
- Access a Simple site with a custom mapped/connected/registered domain already set as primary
- Don't access any other site settings or features
- Navigate to My Site > Posts and edit a draft post
- Verify that the preview returns a 404 ( https://custom-domain/?p={POST_ID}&preview=true in a new tab

#### Verify Fix
- Navigate to `apps/editing-toolkit`
- Check out this branch in a terminal
- Run `yarn dev --sync`
- Sandbox your sandboxed simple site's mapped domain, your sandboxed simple site's wordpress.com domain, and the public api
- Remember to disable autoproxxy so that Safari will read your hosts file https://href.li/?PCYsg-e-p2#sandboxing-safari
- This might be unnecessary, but to ensure a completely reset environment, clear all cache history and cookies again
- Log in to WordPress.com
- Navigate to My Site > Posts and edit a draft post
- Verify that the preview returns the draft preview as expected

#### Pre-merge Checklist

- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have you sent any new strings for translation (PCYsg-1vr-p2) ASAP?

Related to https://github.com/Automattic/wp-calypso/issues/57812

### CODE REVIEW

**Review by Addison-Stavlo — COMMENTED** [review]
I tried to test but am having issues resolving the issue. What I did:

* set up a simple site with a custom domain
* opened safari with default settings
* created a draft post -> preview -> notice 404
* build/sync this wpcom-block-editor branch to my sandbox
* sandboxing public-api and widgets
* go to preview from the draft post -> still 404

but maybe im missing a step here.

**Comment by jeyip** [comment]
> but maybe im missing a step here.

@Addison-Stavlo Yeah I'm adding this to the testing notes I didn't get to last night, but, surprise surprise, Safari doesn't respect the hosts file and your sandbox _unless_ you disable AutoProxxy PCYsg-e-p2#sandboxing-safari

**Comment by Addison-Stavlo** [comment]
Ah yeah of course! `Clear cache and cookies ( History > clear history... > all history in mac topbar )` seems to do it.  After that the preview is no longer a 404. 

Im trying to remember how long it would take a user to see this change if they dont clear their cash on safari. I thought the wpcom-block-editor cache is busted instantly for simple sites and daily for atomic/jetpack, but could be mistaken since I had to manually clear it here with safari.

**Comment by jeyip** [comment]
Could someone verify whether or not this bug appears on atomic sites?

I'm having difficulty because, to verify the issue for atomic, we'd need to click on the preview link from within the calypso gutenframe. I'm, however, being consistently redirected to `/wp-admin` on atomic and am unable to test.

From my understanding though, this is a bug that's simple site specific.

**Review by Addison-Stavlo — COMMENTED** [review]
> Could someone verify whether or not this bug appears on atomic sites? ...  I'm, however, being consistently redirected to /wp-admin on atomic and am unable to test.

I tried to test atomic this morning as well and I seem to be having the same issue with the `wp-admin` redirect:

* On Safari - I am currently always getting the wp-admin redirect on atomic sites in the page/post editor. Thus cannot test the 404 issue, as we don't have this issue from the wp-admin editor.
* On Chrome & Firefox- I am staying inside the iframe. However, I cant test the 404 issue b/c I can only repro it on Safari in general.

**Comment by Addison-Stavlo** [comment]
> I tried to test atomic this morning as well and I seem to be having the same issue with the wp-admin redirect.

Ok, more info related to the above:

* On Safari - I am currently always getting the `wp-admin` redirect on atomic sites in the page/post editor. Thus cannot test the 404 issue, as we don't have this issue from the wp-admin editor.
* On Chrome & Firefox- I am staying inside the iframe. However, I cant test the 404 issue b/c I can only repro it on Safari in general.

**Comment by edanzer** [comment]
> Could someone verify whether or not this bug appears on atomic sites?

@jeyip - I just tried this, and I have the same issue with redirect to wp-admin. My understanding is that this is a universal bug for all Atomic sites at the moment. https://github.com/Automattic/wp-calypso/issues/66020

**Comment by edanzer** [comment]
@jeyip - UPDATE: I had reported this fix wasn't working for me. But I had been building/syncing wpcom-block-editor rather than ETK. After building/syncing ETK, I've confirmed both the bug and the fix working on Chrome and Safari.

**Comment by Addison-Stavlo** [comment]
> On Chrome & Firefox- I am staying inside the iframe. However, I cant test the 404 issue b/c I can only repro it on Safari in general.

Oh wait, I get booted from the Iframe here too when I disable 3rd party cookies. I wonder if disabling 3rd party cookies on atomic sites has to do with this page/post editor not staying in the iframe on atomic? 🤔 If thats the case then i suppose this bug wouldn't happen on atomic 😅 but that could explain other issues.

I saw Eric mentioned (paYE8P-1K8-p2#comment-1667) this change might be well fit to address in Gutenberg, do you think that makes sense? Maybe as a follow up to our fix here (that would then be temporary)?

**Comment by jeyip** [comment]
> I saw Eric mentioned (paYE8P-1K8-p2#comment-1667) this change might be well fit to address in Gutenberg, do you think that makes sense? Maybe as a follow up to our fix here (that would then be temporary)?

@edanzer mentioned that Gutenberg might be the right spot in our meeting this morning as well. I think it does, but I'm having a hard time envisioning what that change would look like in Gutenberg. We're using special, dotcom specific `logmein` logic to assign cookies in a first party context. What would that mechanism be in core?

I'm also wondering where we'd see similar problems on the core side of things. On dotcom, the problem manifests when we jump from a `.wordpress.com` domain to a custom domain in the preview seems, but what would an equivalent in core Gutenberg be? 🤔 

> I saw Eric mentioned (paYE8P-1K8-p2#comment-1667) this change might be well fit to address in Gutenberg, do you think that makes sense? Maybe as a follow up to our fix here (that would then be temporary)?

That makes sense to me 👍  Happy to create a follow-up issue but get a fix out there in the meantime.

**Comment by agrullon95** [comment]
### Testing results
On Chrome (simple site) the changes are working.

On Firefox and Safari (simple site), I'm unable to reproduce the issue. I get redirected to https://agrullon95.wordpress.com/wp-admin/post.php?post=137&action=edit first then get redirected to https://agrullon95.xyz/?p=137&preview=true afterward. Im not seeing the 404 page for the draft. 

Im sandboxing the custom domain, the simple site domain, and the public api but it might be another issue causing this. I'll try again tomorrow. 

On my atomic site, I have the same `/wp-admin` redirection issue everyone is seeing.

**Review by edanzer — APPROVED** [review]

**Comment by agrullon95** [comment]
I tested again on all three browsers (Chrome, Firefox, and Safari) and I was able to reach a working preview site from the site editor draft post preview link.

**Review by agrullon95 — APPROVED** [review]

**Pull request merged**
