### PR TITLE
GuidedTours: move state into own directory

### PR DESCRIPTION
**Pull request by mcsf**
Part of #4575 

_(Edit by @ehg)_

To test:
- Tours should work as per master

### CODE REVIEW

**Comment by ehg** [comment]
I've taken the liberty of moving the state myself, in 00ef7ba. Happy liberty day :)

**Comment by ehg** [comment]
Rebased, flipping to review.

**Comment by lsinger** [comment]
Confirm this works for me the same as on `master`.

**Comment by mcsf** [comment]
Changed naming schema in actions. Waiting for CI, then merging.

**Pull request merged**
