### PR TITLE
Sites dashboard preview - adopt primary wp admin button.

### PR DESCRIPTION
**Pull request by Addison-Stavlo**
Related to # https://github.com/Automattic/dotcom-forge/issues/6829 

## Proposed Changes

cc @cleacos since we are updating the a4a component.  The scope of change seems limited to the dotcom implementation.

* Updates the position and style of the WP Admin button in GSV. While this is in the `item-preview-pane-header` that is shared between a4a and dotcom, the [WP admin link was recently added](https://github.com/Automattic/wp-calypso/pull/89894) as a conditional render from the dotcom side so this should have no effect on the a4a side.
* Updates the close button style and placement IFF the WP Admin button is present. Otherwise, the old style close button with the "X" icon is used. This should ensure no changes are visible on the a4a side WRT this button either.

BEFORE

Screenshot 2024-05-01 at 11 43 56 AM

AFTER

Screenshot 2024-05-02 at 10 43 19 AM

## Testing Instructions

* Test the calypso build and verify the wp admin link is now a button in the top right, and a secondary close button is positioned to the left of it.
* Test the a4a build and verify there are no changes.

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Comment by davemart-in** [comment]
My one minor request. @Addison-Stavlo what do you think of moving the focus to the WP Admin button instead of the close button? I like that this would optionally make wp-admin 1 return key press away for folks navigating via the keyboard.

CleanShot 2024-05-02 at 10 55 32@2x

**Comment by Addison-Stavlo** [comment]
> what do you think of moving the focus to the WP Admin button instead of the close button?

It is a simple change and I just pushed it. 👍 

Technically, I wonder what is best for a11y flows with auto-focusing. IF we are going to auto-focus, it seems like we should auto-focus the FIRST navigable item in the region instead of skipping over navigable items to land on a specific button. I think that is generally the best a11y experience? In this case that would be the the site URL link and not the wp-admin or the close buttons. I don't think we need to decide that in this PR, but its a thought to consider - and a quick fix if we do end up wanting to change it.

**Comment by davemart-in** [comment]
> Technically, I wonder what is best for a11y flows with auto-focusing. IF we are going to auto-focus, it seems like we should auto-focus the FIRST navigable item in the region instead of skipping over navigable items to land on a specific button. I think that is generally the best a11y experience? In this case that would be the the site URL link and not the wp-admin or the close buttons. I don't think we need to decide that in this PR, but its a thought to consider - and a quick fix if we do end up wanting to change it.

I'd vote to ship this. Happy to create a new issue if we think the URL should be focused. But that just feels off to me.

**Review by davemart-in — APPROVED** [review]
LGTM

**Comment by cleacos** [comment]
For A4A, we are using the X icon, so this won't affect us. Anyway, I think the better solution would be to leave the close component, or the top-right area, customizable outside of the `ItemPreviewPaneHeader` component, injecting that custom top-right component for closing the Preview pane and with any additional CTA button.

I'll ask the A4A designers if this design would be okay for A4A, in case we want to add the WP-ADMIN button.

cc: @Addison-Stavlo @davemart-in

**Comment by Addison-Stavlo** [comment]
> Anyway, I think the better solution would be to leave the close component, or the top-right area, customizable outside of the ItemPreviewPaneHeader component, injecting that custom top-right component for closing the Preview pane and with any additional CTA button.

I can take a look at this if you would like. Would it then be along the lines of:
* `ItemPreviewPaneHeader` component takes an optional component prop for overriding the top-right area.
* The "X" close icon button is the default and remains in the `ItemPreviewPaneHeader` component.
* If the optional prop is present the default "x" close button is replaced with what has been passed in. We pass this in from the dotcom side, and have no need to alter any other files on a4a side.

Does that sound like what you have in mind @cleacos ?

**Comment by cleacos** [comment]
> Does that sound like what you have in mind @cleacos ?

Yes, that is @Addison-Stavlo we would pass the custom CTA elements from an upper component, in your case your `SiteDashboard` V2 implementation, to injecting the header CTAs into the `ItemPreviewPane` and then it will pass the custom component to the `ItemPreviewPaneHeader` and this will render passing into it the `itemData` prop

**Comment by Addison-Stavlo** [comment]
There was also recent discussion about going back to the "X" for dotcom as well and having the admin button still there. 😵  Might be worth holding off the abstracting until the dust settles. I think we are in another round of design tweaks so lets see where this goes 🙈

**Comment by cleacos** [comment]
👌  but the idea would be good anyway, making that area fully customizable... I'll add to my P2-post

**Pull request merged**
