### PR TITLE
Tooltip: Add showOnMobile prop to allow display on mobile devices

### LINKED ISSUE #4082: People: Component: Tooltips don't work on mobile
It was reported to me that tooltips don't work for the `/people/new/$site` route when on mobile. I remember discussing this before with @rickybanister, but I didn't create an issue and forgot. :disappointed: 

Here is where the mobile logic occurs: https://github.com/Automattic/wp-calypso/blob/master/client/components/tooltip/index.jsx#L31-L33

I'm not sure what the best approach is. Should we pass a prop in to force displaying the tooltips for our use? Or should we show inline errors just below the token field? cc @rickybanister

### PR DESCRIPTION
**Pull request by ebinnion**
Closes #4082

Fixes an issue where tooltips did not show on mobile. Previously, this may have made sense where tooltips were displayed on hover, since hover isn't supported on touch devices.

But, in invites, we display tooltips after validation, and do not require hover functionality.

cc @rickybanister and @mtias for thoughts and review.

To test:
- Checkout `update/tooltip-show-mobile` branch
- Go to `/people/new/$site` where `$site` is a WP.com site
- Attempt to invite a non-existent user. `0` should do the trick.
- Note that the tooltip shows
- Resize browser to be "mobile". Does tooltip show?
- Repeat on device. Does tooltip show?

### CODE REVIEW

**Comment by rickybanister** [comment]
I won't comment on the code, but this makes sense conceptually.

The only other question I'd have is whether it's ever possible to make a tooltip extend outside of the viewport, but I tested this out and couldn't make that happen even with a very narrow browser window. Having short error messages definitely helps ensure that.

**Comment by ebinnion** [comment]
I modified a tooltip to give it a super long message, and it appears that the tooltip can extend beyond the viewport. Perhaps we can add some styles that will force line breaks on mobile viewports and prevent the tooltip for being larger than the viewport?

**Comment by rickybanister** [comment]
I don't think it's a huge deal at the moment, let's just keep an eye out for long ones. 

The solution would be pretty ugly.

**Comment by enejb** [comment]
Code looks good on for me. I tried to find exampled of attributes that do similar things as showOnMobile but wasn't able to find any. 

:shipit:

**Pull request merged**
