### PR TITLE
Google Photos: update copy

### PR DESCRIPTION
**Pull request by johngodley**
#### Changes proposed in this Pull Request

Update all the Photos from Google copy to Google Photos. Also updates icons with the official Google Photos logo.

Changes:

1. Sharing page has a new logo, updated text, and a new screenshot:
modified

2. Media source dropdown has a new logo (both in the menu and in the selected position), as well as updated text:

dropdown

3. When viewing the media library and not currently connected there is a new logo and updated text:
 
connect

Note that `google-photos-icon.jsx` is added as a custom SVG React component so it can fit in with the rest of the SVG behaviour provided by Gridicons. While not ideal, given the deadline and upcoming media library rewrite this seems acceptable.

### Testing

You will need to apply the API patch in `D23306-code` to test this, and `public-api.wordpress.com` needs to be sandboxed.

1. Visit the Sharing page and disconnect from the existing Google Photos
2. Verify that the Google Photos display matches screenshot (1)
3. Visit the Media page and click source dropdown in top left corner. Verify that the dropdown matches screenshot (2)
4. Select Google Photos. Verify that the dropdown icon correctly shows hover states to match other items
5. Verify that screenshot (3) is shown in the media library

### CODE REVIEW

**Comment by jasmussen** [comment]
Really lovely work. I love the use of the logo and verbiage. Looking at https://developers.google.com/photos/library/guides/ux-guidelines, here are some thoughts. The most pertinent bit is really this image:

screenshot 2019-02-14 at 08 31 36

This tells me that it's okay to use the term "Google Photos", and it's okay to use the pinwheel. But it's not okay to use the _full Google Photos logo_, i.e. `[Pinwheel] Google Photos`. Assuming my interpretation is right, most of this stuff is 👍 👍

Regarding the connect button, there's this:

screenshot 2019-02-14 at 08 32 05

To the question, "if you're going to ask for access to multiple Google product APIs or if you're using Google for general sign-in purposes" — are we using only Google Photos related APIs or are we asking using additional ones?

If we're only using the Google Photos API, then it looks like we need to use this button:

https://developers.google.com/photos/images/ux-guide-connect.png

To do that, we might want to change this section:

https://user-images.githubusercontent.com/1277682/52638560-20cba800-2eca-11e9-9e8d-1ebb041166d9.png

Instead of saying "Connect", it could say "Get Started", and then take you to this page:

https://user-images.githubusercontent.com/1277682/52638674-5e303580-2eca-11e9-9cf5-a48e3772ac48.jpg

But with the aforementioned button right on that page. 

Does that make sense?

**Comment by johngodley** [comment]
It does make sense. I'm drawn to this bit of the guidelines though:

> You **can** use a Google Photos branded button

I added the emphasis to 'can', and it could be this indicates it's an entirely optional thing - you can use a branded button, but you don't have to. If you do use a branded button then it needs to adhere to the subsequent rules.

They use the same wording in the previous section:

> You can use the Google Photos branding elements in your app without pre-approval

This seems to re-enforce that using the branding is optional, and the guidelines are for when you do use them.

Of course I may be interpreting this to suit the fact that modifying the sharing page would be quite a bit of additional work!

**Comment by jasmussen** [comment]
Ah yes I see that! Very lovely. As you were then.

**Comment by johngodley** [comment]
Noting that the current changes have been approved by Google.

**Pull request merged**
