### PR TITLE
Playwright: Decouple jest from calypso-e2e package

### PR DESCRIPTION
**Pull request by dpasque**
#### Changes proposed in this Pull Request

This change decouples the `calypso-e2e` package from `jest`. 

Currently, because of the `setupHooks` function and the `jest-conditionals` file, the `calypso-e2e` package is coupled to being run with jest as the test runner. This has a few downsides.

1. Importing `@jest/globals` could cause some import problems down river. See [this comment on this PR](https://github.com/Automattic/wp-calypso/pull/57569#discussion_r741314318).
2. It makes that package more rigid, for no benefit. If other consumers want to use the `calypso-e2e` package, they must use `jest`. In the future if we want a different test runner, we will have to update the package as well.

Now, in this new mental model, `test/e2e` is responsible for creating the jest runner implementation driving the E2E tests. Any jest-specific library functions should go in `test/e2e/lib/jest`.

Also, because of this, I'm moving all the script over to TypeScript. Having type safety in the local library functions is really helpful, and the vast majority of all our specs were TypeScript anyway!

#### Testing instructions

All the TeamCity builds should pass...

- [x] PR builds
- [x] Gutenberg build
- [x] Pre-release tests

### CODE REVIEW

**Comment by scinos** [comment]
I'm ok with this change, but I think it is misleading to think `@automattic/calypso-e2e` is reusable. It is deeply ingrained in Jest and our specific needs. A few examples just browsing the code:

- It hardcodes a User Agent that only makes sense for Calypso.
- Access to env vars `GUTENBERG_EDGE` or `COBLOCKS_EDGE`, which only makes sense for us.
- Hooks depends on the logic of `test/e2e/lib/jest/environment.js`
- It has test fixtures and fake data that only make sense for our specs
- ...

IIRC, the original goal of `@automattic/calypso-e2e` was to have TypeScript support, as it was not possible (or we didn't know how) to have TypeScript in the specs. Now `@automattic/calypso-e2e` has grown and provides a set of different concerns (that arguably could be their own package) like mocks, setup code, page objects, etc.

From that point of view, I think the line between `@automattic/calypso-e2e` and `test/e2e/` is very blurry, in my opinion. 

So another approach would be to embrace it, and say that `@automattic/calypso-e2e` is everything we need, including setting up Jest and Playwright specs. Which is another way to say we merge `@automattic/calypso-e2e` and `test/e2e`.

Then we can extract small pieces as reusable packages.

**Comment by dpasque** [comment]
>From that point of view, I think the line between @automattic/calypso-e2e and test/e2e/ is very blurry, in my opinion.

> So another approach would be to embrace it, and say that @automattic/calypso-e2e is everything we need, including setting up Jest and Playwright specs. Which is another way to say we merge @automattic/calypso-e2e and test/e2e.

Yeah, that's a good point. I feel like we're kind of at a tipping point here either way, we either keep trying to pull hard dependencies out of `calypso-e2e` to make it a more re-usable package, or we do what you mentioned above, and just merge everything in `test/e2e`. I don't the current state is sustainable in the long run, because we might hit weird issues again like [the original issue that inspired this](https://github.com/Automattic/wp-calypso/pull/57569#discussion_r741314318), so I think we should pick a target end goal of those two options are starting heading in that direction.

@worldomonation @WunderBart  - thoughts?

Also, @scinos, from your recent work on the desktop e2e tests, do you see benefits in this remaining its own package?

**Comment by scinos** [comment]
My vote would be to kill `@automattic/calypso-e2e` in its current form, merge it with `test/e2e`, and then extract packages where it makes sense (eg: a package with only page objects)

> from your recent work on the desktop e2e tests, do you see benefits in this remaining its own package?

`test/e2e` is also a valid package named `wp-e2e-tests`, so there is no fundamental difference in importing some tools from `@automattic/calypso-e2e` or from `wp-e2e-tests`. That being said, at the moment it is not possible to import any of them, because they are not part of the same dependency tree (i.e desktop e2e tests don't know what `@automattic/calypso-e2e` is).

I _tried_ to import `@automattic/calypso-e2e` so I could reuse some parts of it (eg: the Login flow) but knowing that I'd need to avoid some parts like the hooks because they are too tightly coupled with the browser tests.

**Comment by worldomonation** [comment]
Ultimately the end goal we want to get to is to have `@automattic/calypso-e2e` be a reusable package for not just browser tests, but also the `globalSetup` hook in Jest and desktop e2e among others.

I will be honest and say I do not know which is better: baking in more support to `@automattic/calypso-e2e` to make it the one-stop shop for everything, or to split it in to multiple smaller packages.

My gut feeling is that smaller packages would be easier to maintain and adapt to changes; the last thing we want to do 5 years down the road is a Selenium -> Playwright migration v2 because we threw everything into one package.

**Review by scinos — APPROVED** [review]

**Comment by dpasque** [comment]
Per the discussion above, abandoning this PR in favor of a different long term plan. Let's ultimately merge things to `/test/e2e`, and extract whatever modular pieces there are

**Pull request closed without merging**
