### PR TITLE
Gutenboarding: Signup modal appears above existing page content, behaves more like a modal

### PR DESCRIPTION
**Pull request by p-jackson**
#### Changes proposed in this Pull Request

* Move signup modal code out of `onboarding-block/` and into `components/`, to drive home this is a generic modal that can appear at many places in the flow
* Opening modal no longer changes route, it should appear over whatever content the user is currently looking at
* TypeScript shenanigans to get the correct type when dispatching actions that use generator functions
* Remove the JSON dump that appeared in the modal when signup was successful

#### Testing instructions

* In incognito tab go to `/gutenboarding`
* Go through flow and click "Create my site"
* Modal opens over the page layout selector
* Esc/clicking outside/clicking cross, should close signup modal
* Clicking "Create my site" again should reopen dialog
* Esc/clicking outside, in the layout selector should still close the layout selector

### CODE REVIEW

**Comment by ramonjd** [comment]
Was testing and noticed a slight regression. 

When the modal is open, and you refresh the page, the **Create my site button** remains disabled.

Feb-19-2020 14-41-45

The [disabled state is set by looking at the value](https://github.com/Automattic/wp-calypso/blob/d4f85a4dba233077c45d135d43e91587cf507e47/client/landing/gutenboarding/components/header/index.tsx#L169) of `shouldCreate` from `ONBOARD_STORE`.

In master, the route switches from `/signup` back to `/design` when you refresh. 

I believe it works here because `shouldCreate` is being set via `onRequestClose`:

https://github.com/Automattic/wp-calypso/blob/d4f85a4/client/landing/gutenboarding/onboarding-block/signup-form/index.tsx#L56

That it's fired (when the component unmounts?) before a refresh might be a lucky coincidence :)

In this branch, I tested using `showSignupModal` for the button's disabled state value here:

https://github.com/Automattic/wp-calypso/pull/39360/files#diff-46274cafe13f7509396cedeb4d070908R169

That seems to work for now.

**Comment by p-jackson** [comment]
Thanks for trying it out! I'll have to dig into it. It's unclear to me why we should ever disable that button in the first place.

**Comment by ramonjd** [comment]
> It's unclear to me why we should ever disable that button in the first place.

Ha. Good point.

**Comment by p-jackson** [comment]
I'll land this change after #39336 done because it'll make things a little easier (might rebase this PR off that one)

**Comment by andrewserong** [comment]
@p-jackson just took this one for a spin, and ran into the same regression that Ramon mentioned in https://github.com/Automattic/wp-calypso/pull/39360#issuecomment-588026003 (open signup modal and after you reload the page the `Create my site` button is disabled). Interestingly, I'm running into a similar issue on master if instead of closing the modal, I click the back button — the modal is closed but the `Create my site` button is still disabled.

Separately, because here the modal is no longer triggered by a route change, the back button behaviour isn't quite what I expected. If you click back from the modal, it goes to the previous step (e.g. `/gutenboarding/design`) instead of closing the modal.

signup-modal-back-button-small

I like the idea of treating the signup form more like a modal, that can appear at any point in the flow without it having to be a particular step, but without having a separate route / history state change, I wasn't quite sure the best way to handle the back button behaviour 🤔

**Comment by p-jackson** [comment]
> open signup modal and after you reload the page the Create my site button is disabled

Thanks for pointing that out again @andrewserong. Things had changed on `master` about the behaviour of that button, so I'd just assumed this was fixed now.

I'm worried it'll take me away from the original point of this PR, but I have introduced the problem with this change.

> If you click back from the modal, it goes to the previous step (e.g. /gutenboarding/design) instead of closing the modal.

I don't usually expect opening a modal to change the route, so didn't even think of testing this. On the one hand I expect the modal to feel transient, so after a refresh I'd expect the modal to be closed. On the other hand, clicking back to close the modal is probably really nice on mobile phones with a dedicated back button (iPhone user here 🖐). I'm looking around for prior art now.

**Comment by p-jackson** [comment]
> open signup modal and after you reload the page the Create my site button is disabled

I've fixed this by removing `shouldCreate` from the gutenboard store, which was the flag used to disable the button. We don't need to disable the button anymore since either the modal appears (make the button unclickable) or the user is immediately sent to the "your site is being created" page (if they're logged in).

`shouldCreate` was added in #39203 in order to get unauthenticated users into frankenflow to do the signup. Now that signup is gutenboarding we don't need this, and from review comments in the PR it looks like this was always going to be temporary.

I've tested that gutenboarding still works for logged in and logged out users after this change.

> If you click back from the modal, it goes to the previous step (e.g. `/gutenboarding/design`) instead of closing the modal.

I haven't really seen any models in Gutenberg so I looked for prior art in Calypso.

The language modal in `/me/account` doesn't change the route, and disappears when the user clicks back e.g.
1) Go to `/me`
2) Click **Account Settings**
3) Click **Interface Settings**, the modal appears
4) Click browser back button
5) Dialog is closed and you are back at `/me`

All the other Calypso examples I found behaved the same, and I think this is how I expect it to work. The modal should stay open like it was with my changes.

In all the examples I found though I think the modal was just naturally disappearing because its parent was unmounted. But our modal is attached at a higher level in the hierarchy, and I didn't like the idea of adding modal handling to every view of the onboarding block.

So I've added route listening to the header that hides the modal if the route changes. I think this will work unless/until we add some button *in* the modal that changes the route. I can't imagine why we'd do that, but we'll cross that bridge if we ever come to it :)

**Comment by p-jackson** [comment]
Thanks 🎉 

> Oh, and I managed to find a modal in Gutenberg on a .org site.

Ah the elusive GB modal! I knew there must have been a `Modal` component in `@wordpress/components` for some reason.

**Pull request merged**
