### PR TITLE
Checkout: Also show delete button when order review step is inactive

### PR DESCRIPTION
**Pull request by sirbrillig**
#### Changes proposed in this Pull Request

This modifies the first step of checkout, the order review step, so that it displays the cart item delete button even when the step is not expanded.

Before:

before-delete-always

After:

after-delete-always

#### Testing instructions

First: is this a good idea? With this change, users are less likely to click the "Edit" button on the first step, and therefore less likely to see the product variant picker. That was the original reason for hiding it behind the "Edit" button. I personally think the UX benefit outweighs the cost, but it's worth considering.

- Visit checkout with a product in your cart.
- Verify that you can see the trash icon adjacent to each cart item no matter which checkout step is active.
- Verify that clicking the trash icon when the first step is not active allows removing the cart item.
- Verify that there are no visual regressions and that the padding/margins on the line items look ok.

### CODE REVIEW

**Comment by michaeldcain** [comment]
> First: is this a good idea?

Use of the in-Checkout variant picker is already pretty low. Given the number of Happiness complaints we receive regarding removing items from the cart, I think this outweighs the downside. We also have the ability to nudge variants through the Checkout sidebar, as we have in the past for different upsells.

I do however think we need to give this some design consideration. The alignment of the icon with the edit button is a little askew, and the addition of the button (and its padding) can cramp an already visually cluttered area, especially with more than one item in the cart:

Desktop | Mobile
------------ | -------------
Screen Shot 2021-05-14 at 9 36 51 AM | Screen Shot 2021-05-14 at 9 37 03 AM

I'll try to spend some time today on the css. I don't think it requires an overhaul - just some tweaks.

**Comment by sirbrillig** [comment]
Agreed. Worth noting that there are several places which adjust padding already based on `isSummary` or have `.is-summary` in their CSS which are probably to blame for the wonky alignment.

**Comment by sirbrillig** [comment]
Also: I moved the icon into an `img` tag because it was having trouble loading the same svg multiple times on the page, and I believe this is probably more efficient anyway. Unfortunately that seems to have broken the unit tests. I'll fix them when you're done with the alignment.

**Comment by sirbrillig** [comment]
> the addition of the button (and its padding) can cramp an already visually cluttered area, especially with more than one item in the cart

🤔  I wonder if it would help if we made the delete button into a text button and put it below each item at mobile width. So it would read something like:

WordPress.com Business &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; $300
Plan Subscription: $300 per year
_remove_

Alternatively we could just hide the delete button at mobile width and require pressing `edit` as we do currently, but show it at desktop width.

Neither of those really helps the desktop width view clutter, though.

**Comment by michaeldcain** [comment]
I pushed a commit to right-align the delete icon with the "edit" text. I'd like to update the mobile view for all steps, but we should do that in a follow-up PR.

Before | After
------------ | -------------
Screen Shot 2021-05-26 at 6 10 11 PM | Screen Shot 2021-05-26 at 6 09 45 PM

**Review by michaeldcain — APPROVED** [review]
This works as described and LGTM.

**Comment by michaeldcain** [comment]
Event fired when item is deleted: `calypso_checkout_composite_delete_product`

**Pull request merged**
