### PR TITLE
Signup: Fix checkout sidebar overlap

### LINKED ISSUE #900: Signup: Checkout sidebar
When signing up for a new site with a paid plan, the sidebar overlaps the checkout if your browser is around 900px wide:

screenshot 2015-11-27 16 46 30

cc @shaunandrews

### PR DESCRIPTION
**Pull request by shaunandrews**
Ensuring there’s room for the checkout sidebar. Fixes #900

### CODE REVIEW

**Comment by sirbrillig** [comment]
LGTM

**Comment by lancewillett** [comment]
Needs a merge conflict resolution...

**Comment by lancewillett** [comment]
@shaunandrews Can you re-look?

**Comment by shaunandrews** [comment]
This was fixed in https://github.com/Automattic/wp-calypso/pull/1029

**Pull request closed without merging**
