### PR TITLE
Plugins: use <AllSites> component

### PR DESCRIPTION
**Pull request by mtias**
Tweaks <AllSites> component to support multisite-networks.

image

### CODE REVIEW

**Comment by mtias** [comment]
We can force url to display if that's preferred.

**Comment by rickybanister** [comment]
I think we could limit the site icons to 4 or fewer and put the url to the right of them for this context, would that work?

**Comment by mtias** [comment]
It's limited to 10 by default, that still seems reasonable?

**Comment by rickybanister** [comment]
We can take a look at the default, but I imagine it could look pretty unaligned if your network's title is short

like

```Stuff
[][][][][][][][][][][] mylongurlissuperlong.com```

**Comment by mtias** [comment]
I think we should leave the url at the left — the url is the main site, the icons are in order + all available sub-sites.

**Comment by enejb** [comment]
We need to also update the README file for all-sites with the new props.

**Comment by enejb** [comment]
I tested it and it works as expected! Thanks for fixing it!
This is ready to ship after we update the readme.md file for all sites. 

:shipit:

**Comment by rickybanister** [comment]
I think it works well with the url to the left and site icons after that. This isn't the most common use (mu network, etc) and it's an improvement over what we had before. Let'd do it!

**Pull request merged**
