### PR TITLE
Plugin browser section header

### PR DESCRIPTION
**Pull request by johnHackworth**
Fixes https://github.com/Automattic/wp-calypso/issues/1226
Fixes https://github.com/Automattic/wp-calypso/issues/819

Plugin browser lists were not using section headers. So when we changed the global background color to the same one they were using as background, they pretty much dissapeared as a separated box:

image

This PR changes plugin-browser-list to use `Section-header`, so the header of the lists is our standard white box:

image

How to test:
=======
1. go to http://calypso.dev:3000/plugins/browse
2. Check the headers of each list is a Section Header

### CODE REVIEW

**Comment by rickybanister** [comment]
The padding to the right of 'See All' looks really large. Can we standardize that at 24px just like the left side?

Is that icon already a gridicon? If not that is fine for a different PR, but we should fix it while we're thinking about it.

**Comment by johnHackworth** [comment]
good point, @rickybanister , I didn't realize about it... now it have the standard 24px padding:

image

**Comment by rickybanister** [comment]
Looks good to go!

**Comment by enejb** [comment]
Looks great to me as well :shipit: 
Great work!

**Comment by mtias** [comment]
The space below `NEW` and `POPULAR` seems larger than the one on top of it.

**Comment by johnHackworth** [comment]
you're right @mtias ... now section-header__label should be always vertically centered:

image

**Comment by rickybanister** [comment]
Looks better.

I think the SectionHeader label 'NEW' or 'POPULAR' might be 12px—it should be 11. I guess I didn't notice before since it was always by itself, but now that it's next to the 'SEE ALL' (which is 11px) the difference seems more obvious.

I suppose we should merge this and tackle that later though.

**Comment by enejb** [comment]
I updated this to use 11px and removed a type. Which I think didn't do anything. I am a bit amazed that it sass compiled. I though that it usally throws an error.
Feel free to merge this! If you think its is good to go. :shipit:

**Comment by johnHackworth** [comment]
woah... yeah, I don't understand why the compiler was letting that one pass (¿?¿?) ..

**Pull request merged**
