### PR TITLE
`DotcomSitesDataViews`:  Show `All sites` by default on the filter

### PR DESCRIPTION
**Pull request by xavier-lc**
Related to https://github.com/Automattic/dotcom-forge/issues/6872

## Proposed Changes

* Show the `All sites` option by default on the sites dashboard filter.

## Why are these changes being made?

* This helps provide clarity at a glance as to what you're looking at, even when no filter is selected.

## Testing Instructions

* Open the live preview
* Go to `/sites`
* Check that the filter says `Status is All sites`, and that the `Reset filters` button is not visible

|Before|After|
|---|---|
|image|image|

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Comment by lucasmendes-design** [comment]
It's better than before already. Can we remove the Reset filters here? 

Screenshot 2024-06-26 at 12 58 32

**Comment by lucasmendes-design** [comment]
If not, it's LGTM. I think it's better than before at least users know that there is a filter and how to change it.

**Comment by BogdanUngureanu** [comment]
Looks good!

One question: When the user clicks "Reset filters" or "Reset status", shouldn't the option be reverted to "All sites"? Right now it removes everything.

**Comment by lucasmendes-design** [comment]
> One question: When the user clicks "Reset filters" or "Reset status", shouldn't the option be reverted to "All sites"? Right now it removes everything.

The main issue with this component is that the table's default state is "All sites". So, If users select the filter and click on "All sites," nothing will happen. The same behavior will happen if they reset filters with "All sites" selected. 

The old version fixed that by showing the status filter as default (image below). I'm trying to follow what we have before with the new component. 

Screenshot 2024-06-27 at 08 15 13

**Comment by lucasmendes-design** [comment]
Once we introduce more filters we may fix that problem.  
p1719340001649629-slack-C048CUFRGFQ

**Review by BogdanUngureanu — APPROVED** [review]

**Pull request merged**
