### PR TITLE
New Pricing Grid: Integration PR

### PR DESCRIPTION
**Pull request by niranjan-uma-shankar**
#### Proposed Changes

* This is the integration PR for the new pricing grid. The sub-PRs are listed in pdvytD-6M-p2.
* The design for the pricing grid can be found in 2e991-pb.
* The new pricing grid is launched to `en` only, in any signup flow which has a plans step. 

**Desktop**

npg

**Tablet**

Check [this](https://user-images.githubusercontent.com/1269602/210099964-b1450f58-2cea-4050-9834-3deb3450b69c.jpg).

**Mobile**
Check [this](https://user-images.githubusercontent.com/1269602/210100273-372603a3-8b4e-421c-b46e-0f2727e40ae9.png).

#### Testing Instructions

**IN EN LOCALE**

* Signup as a new user from `/start` and verify that the plans step design matches the Figma in desktop, tablet, and mobile viewport sizes. 
    * Note that the Business plan is highlighted as popular, the Enterprise price aligns with the "per month" line, and the plan tagline has a 1px bigger font than shown in Figma, as per feedback shared in p1672275676517789?thread_ts=1672225348.890109-slack-C040UAN6TPS and p1672277398019369?thread_ts=1672225348.890109-slack-C040UAN6TPS.

* Verify the UI looks okay in a few different currencies, that is, nothing breaks in the UI for USD, EUR, JPY, IDR etc.
    * In INR, MXN, and PHP currencies the legacy plans UI shows crossed-out price for the 20% discount. The new pricing grid retains that design, even though it's not explicitly discussed in Figma. 
* Verify that you see the free plan both with a free domain and a custom domain selected in the domains step.
* Verify that the Tracks events on the plans step all work appropriately. 
* Confirm that Calypso `/plans` UI is unaffected in all viewport sizes.
* Verify that the new pricing grid looks and works fine in other flows which have a plans step, such as the domain-only flow at `/start/domain/domain-only` when you select the option to create a site.
* Verify the new pricing grid works fine in the site launch flow. As an FYI, the launch flow will show the plans step only for free plan sites.

**IN NON-EN LOCALE**

* You should see the legacy plans step in all contexts and all viewport sizes.

### CODE REVIEW

**Review by southp — DISMISSED** [review]
Works as expected. LGTM 🚢

**Review by claudiucelfilip — DISMISSED** [review]
LGTM

**Comment by southp** [comment]
Since we will want to include the plan comparison table into the v1 launch, I'm reverting the launch-to-en part in https://github.com/Automattic/wp-calypso/pull/71753 so we can safely deploy this PR as the foundation for our future iterations.

**Comment by gmovr** [comment]
Rebase should solve the E2E, ref: p1672951847701069-slack-C02DQP0FP :)

**Comment by southp** [comment]
Now that the launch to en part has been reverted, I'm restating the test instructions here:

1. `/start` flow should be unaffected.
2. Go through `/start/onboarding-2023-pricing-grid` and the new pricing grid should be visible there. Since this PR is just the collection of a series of approved PR and any other fixes is preferrably done as follow-ups. It's enough to make sure it's available there.

**Review by gmovr — APPROVED** [review]
I tested this manually, and the /start flow is unaffected (showing the current plans grid). 

Going to /start/onboarding-2023-pricing-grid/ takes me to the new grid after the domains step. Choosing a plan takes me to checkout as expected. LGTM! 🚀

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/7713127

Thank you @niranjan-uma-shankar for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/7713127

Thank you @niranjan-uma-shankar for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/7713127).

**Pull request merged**
