### PR TITLE
Partner Portal: Add license listing data layer

### PR DESCRIPTION
**Pull request by atanas-dev**
Context:
* Project thread: pbtFPC-Um-p2
* i4 designs: pbtFPC-103-p2

#### Changes proposed in this Pull Request

* Add a live API-driven license listing data layer to the Partner Portal.

#### Testing instructions

* If you do not have a partner key, please contact Infinity for one or you will be unable to view the UI.
* Checkout PR locally, run `yarn && yarn start-jetpack-cloud`.
* Visit http://jetpack.cloud.localhost:3000/partner-portal and select your partner key, if prompted.
* You should be presented with a list of all of your licenses, if any. Pagination will be introduced in a separate patch.

### CODE REVIEW

**Comment by IanRamosC** [comment]
I like the data-layer approach. From the Partner Portal perspective, the code looks good and the functionality also tests well, but I'd like to have someone else with more experience on Calypso reviewing it.

**Comment by atanas-dev** [comment]
@IanRamosC Voyager replied in pbtFFM-Fx-p2

**Review by IanRamosC — APPROVED** [review]

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/5531010

Hi @atanas-dev, could you please edit the description of this PR and add a screenshot for our translators? Ideally it'd include all of the following strings:
- `No licenses found.`
- `Failed to retrieve your licenses. Please try again later.`

Thank you in advance!

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/5531010).

**Pull request merged**
