### PR TITLE
Login: Update OAuth design for mobile

### PR DESCRIPTION
**Pull request by scruffian**
This makes a few tweaks to the design of the OAuth pages for mobile, and cleans up the code, removing unused selectors.
  
#### Testing instructions
  
1. Run `git checkout update/oauth-design` and start your server
2. Check the layout of the custom OAuth pages:
http://calypso.localhost:3000/log-in?client_id=50916
http://calypso.localhost:3000/log-in?client_id=930
http://calypso.localhost:3000/log-in?client_id=973
http://calypso.localhost:3000/log-in?client_id=1854
http://calypso.localhost:3000/log-in?client_id=978
3. Also check a standard OAuth page:
http://calypso.localhost:3000/log-in?client_id=978

#### Reviews
  
- [x] Code
- [x] Product

### CODE REVIEW

**Comment by hafizrahman** [comment]
I'm getting flashes of each page's specific header/logo every time I open a page, which then disappears after a few seconds. Video here:

https://cloudup.com/cqLSJRKX314

**Comment by pento** [comment]
@hafizrahman: Could you try testing while logged out, or in an incognito window? This flow won't be visible to logged out users, once it's complete.

**Comment by pento** [comment]
The header text flicker non-dops pages is kind of annoying. It feels a little less terrible on desktop, but it's really noticeable on mobile, when the header goes from one line to three as `oauth2ClientData` finally populates. That's not caused by this PR, though, so I'm cool with us looking at it in a separate PR.

Fun side note: I ran into #17265 while testing this. 🙂

**Comment by hafizrahman** [comment]
> Could you try testing while logged out, or in an incognito window? This flow won't be visible to logged out users, once it's complete.

Ah yeah, looks fine on logged out state.

**Pull request merged**
