### PR TITLE
Components: Remove Accordion and replace it with Panel

### PR DESCRIPTION
**Pull request by tyxla**
After some recent [Calypso editor cleanup](https://github.com/Automattic/wp-calypso/pull/47095) it turns out that the Calypso `<Accordion />` component is used only at a couple of locations in the Hosting settings screen.

That makes it a good and simple enough candidate to address in our quest to make `@wordpress/components` the canonical component library throughout all our applications and interfaces.

This PR updates those accordions to use a `PanelBody` from `@wordpress/components` and removes the `<Accordion />` component completely.

It is immediately visible that the new component is more accessible and does a better job to indicate user focus.

Furthermore, the arrows of `Panel` are much more in sync with other UI elements in Calypso, like the sidebar menu accordions.

In my opinion, this is an easy win and a great example of how simple and beneficial a migration to a `@wordpress/components` component can be.

There are some design changes here, so I'd appreciate feedback from the design team.

#### Changes proposed in this Pull Request

* Components: Remove Accordion and replace it with Panel

#### Preview

Default state, collapsed - before:

Default state, collapsed - after:

Hover state, collapsed - before:

Hover state, collapsed - after:

Focused state, collapsed - before (doesn't have any focus indication):

Focused state, collapsed - after:

Default state, expanded - before:

Default state, expanded - after:

#### Testing instructions

* Go to `/hosting-config/:site` where `:site` is the slug of an Atomic site without SFTP credentials.
* Verify the SFTP credentials accordion looks and works well.
* Verify the phpmyadmin accordion looks and works well.

### CODE REVIEW

**Comment by sixhours** [comment]
👋 Yay for more WordPress components! And for all those red lines.

From the design side, I see two minor tweaks. I'd update the font weight to 600 from 500 to align with our current stylelint reqs, and I'd bump up the font size on the header from 13px to 14px, or even 16px. Quick mockups for comparison:

14px:

Screen Shot 2020-11-05 at 2 40 57 PM

16px works even better, IMO; it offers clearer hierarchy when the menu is expanded:

Screen Shot 2020-11-05 at 2 41 18 PM

I'd probably test these variations on a screen with more panels per section to get an idea of how it all looks together. I'll hack together a quick example and take some screenshots.

**Comment by sixhours** [comment]
Still pretty good with multiples:

Screen Shot 2020-11-05 at 3 00 09 PM

**Comment by kwight** [comment]
Wonderful, works well 🎉

**Comment by tyxla** [comment]
Thanks for the reviews @sixhours and @kwight! I appreciate the great feedback, @sixhours! 

>  Yay for more WordPress components! And for all those red lines.

Right? I couldn't be more excited about deleting code! 😉 

> From the design side, I see two minor tweaks. I'd update the font weight to 600 from 500 to align with our current stylelint reqs, and I'd bump up the font size on the header from 13px to 14px, or even 16px. 

Good call! I've taken both of those suggestion in consideration, and I agree 16px works better in this instance.

> Still pretty good with multiples

Thanks for testing it! TBH, I didn't assume less, as those panels are quite extensively used in Gutenberg already.

**Comment by tyxla** [comment]
This is ready for another review.

**Comment by keoshi** [comment]
@sixhours Could you expand the `What is life?` section? Pretty interested to know what it says inside. :trollface:

**Review by keoshi — APPROVED** [review]
Following the tweaks @sixhours suggested, this is looking mighty good. 🚢

**Comment by tyxla** [comment]
Thanks for taking a look, @keoshi! I'll standby for a code review before 🚢

**Review by sarayourfriend — APPROVED** [review]
Code LGTM 🚀

**Comment by tyxla** [comment]
Thank you, folks 🙌

**Pull request merged**
