### PR TITLE
Social Icons: Use camelCase SVG attributes.

### PR DESCRIPTION
**Pull request by obenland**
Avoids two “Unknown DOM property” warnings when displaying sharing
options in `my-sites/sharing`.

See
https://facebook.github.io/react/docs/tags-and-attributes.html#svg-attri
butes
See #5950.

### CODE REVIEW

**Comment by gwwar** [comment]
:shipit:

**Comment by aduth** [comment]
Is this something we need to fix at the [Automattic/social-logos repo](https://github.com/Automattic/social-logos) build step for the React component? Else we might reintroduce this when updating in the future.

**Comment by gwwar** [comment]
Thanks for the reminder @aduth. cc @obenland 

It seems pretty odd that we're pulling in dependencies like this manually. Any reason why we can't publish the actual files we want to npm?

**Comment by aduth** [comment]
@gwwar I think it would be good to spend time working to treat them as proper external dependencies. I mentioned this in CFH30 (1:10:56) and had chatted with @jasmussen about this too for Gridicons. There's a related issue there at https://github.com/Automattic/gridicons/issues/98.

**Comment by jasmussen** [comment]
Yep — there's no sinister reason for why Social Logos and Gridicons are included manually, they both came to life slightly rushed in efforts to replace noticons. Help with making it `npm` includable would be graciously accepted.

**Comment by gwwar** [comment]
@jasmussen I'll work on it during my next trash pickup unless someone beats me to it ;)

**Pull request merged**
