### PR TITLE
Framework: Update to click-outside@2

### PR DESCRIPTION
**Pull request by blowery**
Removes the transitive dep on the babel@4 runtime

Test live: https://calypso.live/?branch=update/click-outside-2

### CODE REVIEW

**Comment by blowery** [comment]
Props @TooTallNate

**Comment by gwwar** [comment]
I'm seeing a js error when opening a post in the reader:
screen shot 2016-06-16 at 2 46 42 pm

**Comment by gwwar** [comment]
Looks like the export object changed a bit. Imports should be updated to:
```javascript
import { default as clickOutside } from 'click-outside';
```

**Comment by TooTallNate** [comment]
We either need to:

 1. Update `require('click-outside')` calls to `import clickOutside from 'click-outside'`.
 1. Revert the `export default` usage from the `click-outside` module and re-publish to npm.

Probably leaning towards the later so that potential other consumers of `click-outside` aren't forced to use babel as well.

**Comment by TooTallNate** [comment]
Ok, `click-outside` v2.0.1 should be good-to-go.

**Comment by gwwar** [comment]
:shipit:

**Pull request merged**
