### PR TITLE
Jetpack SSO: Add error notice when SSO authorization fails

### LINKED ISSUE #5685: Jetpack SSO: Add error notice when authorize fails
If a user happens to leave the window open for more than 10 minutes, then the nonce will go bad. In this case, the SSO authorize will fail even though the validation succeeded. So, we should update the UI some way.

### PR DESCRIPTION
**Pull request by ebinnion**
Closes #5685 

When an error occurs after clicking the "Log in" button to authorize the SSO process, we should show the  error some sort of UI instead of just doing nothing. 

In this PR, I suggest that we show an error notice and instruct the user to log in again. When clicking the "try again" link, the user will be sent to `{$site}/wp-admin` where they can start the SSO process over.

Note: Since we pre-validate the SSO details, the chances of this being shown to users are slim. But, it could happen if a user takes longer than 10 minutes to approve the SSO process.

Note: I know there's an orphan word in this screenshot. 😞 

cc @rickybanister for design review and @lezama for code review. 

To test:

- Checkout `update/jetpack-sso-error-notice-authorize` branch
- Ensure you have latest Jetpack on your site
- Go to `{$site}/wp-admin`
- Click "Log in with WordPress.com" button
- Replace `wpcalypso.wordpress.com` with `calypso.localhost:3000` in the URL
- In the "Network" tab of Chrome, turn off Wifi
- Click the blue "Log in" button to authorize
- You should see an error
- Turn off wifi throttling
- Click the "try again" link

After screenshot:

screen shot 2016-05-31 at 5 22 49 pm

### CODE REVIEW

**Comment by rickybanister** [comment]
I think we need to address the competing calls-to-action here. If there has been an error that would prevent me from logging in, we should disable the large blue 'log in' button. 

As for the notice, can we change it to use a notice action instead?

So

`Oops, something went wrong.     [Try again]`

**Comment by ebinnion** [comment]
I pushed a few updates. I also noticed a logic error with the conditional we were using to disable the button. 😱 

Here's an updated screenshot.

screen shot 2016-05-31 at 8 50 39 pm

**Comment by lezama** [comment]
:shipit:

**Comment by rickybanister** [comment]
cleared for takeoff

**Pull request merged**
