### PR TITLE
Reader: remove reader/site-and-author-icon

### PR DESCRIPTION
**Pull request by bluefuton**
In https://github.com/Automattic/wp-calypso/pull/12459, we removed the last use of the `reader/site-and-author-icon` component in favour of the ReaderAvatar block.

This PR removes the old component from the codebase.

### To test

Load your following stream and ensure that avatars look correct.

### CODE REVIEW

**Comment by samouri** [comment]
dupe of https://github.com/Automattic/wp-calypso/pull/12525

**Comment by samouri** [comment]
reviewing this now, we can repurpose the second to be just about RelatedPostsV1

**Comment by samouri** [comment]
There are still a few references to `site-and-author-icon` in our css

**Comment by bluefuton** [comment]
> There are still a few references to site-and-author-icon in our css

I think those are from `ReaderAvatar, which applies a similarly-named class:

```'has-site-and-author-icon': hasBothIcons,```

**Comment by samouri** [comment]
Testing LGTM! 🚢

**Pull request merged**
