### PR TITLE
Self-service site restore: make wording of error message compatible with D144421

### PR DESCRIPTION
**Pull request by mpkelly**
Screenshot 2567-04-05 at 15 20 26

Related to https://github.com/Automattic/wp-calypso/pull/88898

## Proposed Changes
- In D144421-code, we will allow admins to restore sites instead of only the owner. This PR updates the frontend.

## Testing Instructions
- Apply D144421-code
- Delete a site with an editor or non-admin user
- Try and restore the site as an editor

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Comment by paulopmt1** [comment]
I couldn't access the /settings menu from the Editor user to try to delete this site. Also, after deleting it using an admin user, I didn't see it on my editor user site list, so I couldn't make that request to see the error. Am I missing something?

**Comment by vykes-mac** [comment]
@paulopmt1 I think he means delete a site that has both an Admin and a non-admin user then try and restore the site with the non-admin user.

**Comment by vykes-mac** [comment]
While testing this I discover that only the user that initiate the delete can see the blog in their deleted sites section. @mpkelly were you able to see the deleted site listed for the non-admin user? deleted sites is empty for me which make sense looking at the query that fetches the deleted blogs.

**Comment by vykes-mac** [comment]
I made the changes on the backend in this diff D144573-code and now this PR works as expected

**Review by vykes-mac — APPROVED** [review]

**Comment by mpkelly** [comment]
> While testing this I discover that only the user that initiate the delete can see the blog in their deleted sites section. @mpkelly were you able to see the deleted site listed for the non-admin user? deleted sites is empty for me which make sense looking at the query that fetches the deleted blogs.

@vykes-mac I didn't experience that. I invited an editor and they could see it. But they were blocked from deleting it.

Sounds like it's fixed now anyway.

**Pull request merged**
