### PR TITLE
Guided Tour: Support Dark Background

### LINKED ISSUE #33096: Guided Tour: Dark Background Support
Guided Tour styling needs general enhancements to support dark screens.

**Problem:**

While Guided Tour overlay is display mostly over light screens, there are some dark screens in Calypso in which Guide Tour overlays difficult to see. Some examples:

screenshot_664

screenshot_665

Placement can help some but not fully:

screenshot_666

**Suggested Solution** (there could be better, Muriel-compatible solutions)

Adding `border: 2px solid white` makes the overlay standout over dark screen:

screenshot_667
 
But that the arrow now looks like a gap. Adding similar border to two borders of the arrow and tweaking position removes the problem.

screenshot_668

Isolating Dark Mode style as optional feature to Guided Tour popup should limit the impact of this enhancement to a manageable level.

### PR DESCRIPTION
**Pull request by donpark**
#### Changes proposed in this Pull Request

- Adds optional `dark` property to `Step` class. If set, new `guided-tours__step-dark` CSS class will be added.
- Defines `guided-tours__step-dark` CSS class which places 2px solid white border around the step as well as arrows.

#### Testing instructions

1. In `client/layout/guided-tours/tours/checklist-user-avatar-tour/index.js` file, replace the start tag of the step named "crop-image" to look like this:
```
<Step name="crop-image" target="image-editor-button-done" placement="below" dark={true} arrow="top-right">
```
2. `npm start`.
3. Navigate to http://calypso.localhost:3000/me?tour=checklistUserAvatar and follow the tour steps.
4. At the "Alright! Press Change My Photo to save your changes." step, popup should have white border around it like the image below. 

screenshot_669

Fixes #33096

### CODE REVIEW

**Comment by donpark** [comment]
Dark background support added by this PR will be used to fix #33072.

**Comment by sixhours** [comment]
This works as described! 👍

**Comment by donpark** [comment]
@sixhours thx. Any idea why desktop test is failing at `fatal: Couldn't find remote ref tests/add/guided-tour-step-dark`?

is it because of `add/` branch prefix triggers rules requiring additional tests?

**Comment by donpark** [comment]
@sixhours all tests have passed after reverting. mind giving the formal ✅ ?

**Comment by sixhours** [comment]
Yay, still works! 🚢

**Pull request merged**
