### PR TITLE
Add/site icon component

### LINKED ISSUE #66289: Signup: Integrate site icon upload component
### Details

Newsletter flow on this [PR](https://github.com/Automattic/wp-calypso/pull/66217/files#diff-1a3fce74bb9259603bb8314ecd6aa0a2dcf1407fa64745db432a04ee51d7bc2e) has implemented the site icon upload component. Link-in-bio flow should use the same component.

### Checklist

_No response_

### Related

_No response_

### PR DESCRIPTION
**Pull request by renancarvalho**
#### Proposed Changes

Integrate site upload icon component, so now Link In Bio and Newsletter are using the same component for icon upload.

#### Testing Instructions

- Run `yarn start` from the calypso root folder
- Navigate to http://calypso.localhost:3000/setup/linkInBioSetup?flow=link-in-bio&siteSlug=YOUR-SITE.wordpress.com
- You should be able to upload an Icon to your link in bio setup site.

### Expected result
- You should see the image upload, similar to this:

image

* Form validation and other fields are not part of this PR.

Related to #66289
Fixes #66289

### CODE REVIEW

**Review by alshakero — APPROVED** [review]
The icon picker works and the implementation looks good.

I imagine there is a follow up PR to finish up the step.

**Comment by renancarvalho** [comment]
@alshakero , you are right on your comment, I am keeping PR's as small as I can.

more coming soon =)

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/7464769

Thank you @renancarvalho for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/7464769

Thank you @renancarvalho for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/7464769).

**Pull request merged**
