### PR TITLE
Sidebar Upsell Nudge: Improve UI 

### PR DESCRIPTION
**Pull request by rcrdortiz**
Related to:
- https://github.com/Automattic/wp-calypso/issues/94476

## Proposed Changes

* Changed the UI according to the design supplied on the parent issue.

## Why are these changes being made?

* Redesigned the upsell nudge to improve the overall UX.

## Testing Instructions

* Open the Calypso live link.
* Use a site that hasn't registered a domain within the last 7 days.
* or alternatively hack the jitm engine on wpcom to show the the jitm
* You should see the jitm with the new design.

| Before | After |
| - | - |
Screenshot 2024-12-10 at 17 43 31|Screenshot 2024-12-10 at 17 43 13

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
    - [ ] For UI changes, have we tested the change in various languages (for example, ES, PT, FR, or DE)? The length of text and words vary significantly between languages. 
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Review by dsas — COMMENTED** [review]
I think it's arguable whether this is better or not - the Add button feels a bit orphany to me:

Screenshot 2024-12-12 at 11 52 19

Maybe the button needs to be centered, or just have longer text? 🤔 


However I think it looks less good in some circumstances, for example the Free domain available version:

Screenshot 2024-12-12 at 11 49 30

**Comment by dsas** [comment]
> I think it's arguable whether this is better or not - the Add button feels a bit orphany to me:
> Screenshot 2024-12-12 at 11 52 19
> 
> Maybe the button needs to be centered, or just have longer text? 🤔

Oops that particular nudge does have longer text if I apply D168272-code, I still think it looks a bit better being centered though.

**Comment by rcrdortiz** [comment]
> > I think it's arguable whether this is better or not - the Add button feels a bit orphany to me:
> > Screenshot 2024-12-12 at 11 52 19
> > Maybe the button needs to be centered, or just have longer text? 🤔
> 
> Oops that particular nudge does have longer text if I apply [D168272-code](https://href.li/?https://code.a8c.com/D168272), I still think it looks a bit better being centered though.

Our designer mentioned moving the button to that location, I'll take his word about how it looks.

For the cases where we don't have the close button, I'm going to try to leave the button where it was before.

**Comment by mmtr** [comment]
@rcrdortiz Can you check with a designer if non-dismissible upsells with only a single line of text should look like this?

Before | After
--- | ---
Screenshot 2024-12-12 at 15 31 25 | Screenshot 2024-12-12 at 15 30 12

They look much worse to me know, but it might be just a personal preference.

**Comment by rcrdortiz** [comment]
> @rcrdortiz Can you check with a designer if non-dismissible upsells with only a single line of text should look like this?
> 
> Before	After
> Screenshot 2024-12-12 at 15 31 25	Screenshot 2024-12-12 at 15 30 12
> They look much worse to me now, but it might be just a personal preference.

I'll make it look like before in those cases.

**Comment by mmtr** [comment]
This also changes a few upsells in other pages:

Page | Before | After
--- | --- | ---
Activity log | Screenshot 2024-12-12 at 15 37 02 | Screenshot 2024-12-12 at 15 37 07
Plugins | Screenshot 2024-12-12 at 16 06 20 | Screenshot 2024-12-12 at 16 06 24

**Review by mmtr — APPROVED** [review]
Looks good!

**Pull request merged**
