### PR TITLE
Jetpack Connect: Add HotJar

### LINKED ISSUE #30498: Add hotjar tracking script to entire jetpack/connect flow
Much like we've added the hotjar tracking code to the[ plans grid within the jetpack connection flow](https://github.com/Automattic/wp-calypso/pull/30495), we need to add it to each page / step within our entire jetpack remote install flow so we can build in hotjar form analysis to see if / where customers are getting tripped up in our onboarding flows.

ref: https://wordpress.com/jetpack/connect
flow maps: p1HpG7-5XJ

cc @rickybanister @joanrho @keoshi @fditrapani

### PR DESCRIPTION
**Pull request by sirreal**
Follow-up to #30495.
Closes #30498

Adds HotJar analytics to all of the controller-level components in the Jetpack Connect flow.

Lifts the shared `plans-grid` HotJar to controller-level components (plans landing and plans) for consistency.

#### Changes proposed in this Pull Request

* Add HotJar

#### Testing instructions

1. Set debug in the console `localStorage.debug = 'calypso:analytics:hotjar'`
1. You should see related console messages in the following scenarios. Loading or not depends on the environment.

* `/jetpack/connect/plans`
* `/jetpack/new`
* `/jetpack/connect` (entry point, follow the entire flow)
* Connect a new Jetpack site starting from WP Admin

On each of the individual flow views in Calypso, refresh and verify that the same HotJar message is displayed in the console.

### CODE REVIEW

**Comment by sirreal** [comment]
There a pre-existing eslint error I'm inclined to ignore in this PR:

```
line 275, col 7, Error - Anchor used as a button. Anchors are primarily expected to navigate. Use the button element instead. Learn more: https://github.com/evcohen/eslint-plugin-jsx-a11y/blob/master/docs/rules/anchor-is-valid.md (jsx-a11y/anchor-is-valid)
```

**Comment by sirreal** [comment]
Fixing the failing snapshot tests…

**Comment by sirreal** [comment]
One bug and tests fixed, this should be ready for review and testing now 🙇

**Comment by jeffgolenski** [comment]
Ship ittttt. I'll get hotjar maps going as soon as its deployed

**Pull request merged**
