### PR TITLE
Components: Replace ScreenReaderText with core VisuallyHidden

### PR DESCRIPTION
**Pull request by sarayourfriend**
#### Changes proposed in this Pull Request

* Replaces `@automattic/component`'s `ScreenReaderText` with core's `VisuallyHidden`.

Note: I have no idea if this will work due to SSR issues in core but I thought it was worth the experiment. If it does work then I will extract this out into several smaller PRs to make it easier to review.

#### Testing instructions

* N/A

### CODE REVIEW

**Comment by sarayourfriend** [comment]
Closing as a failed experiment. SSR issues in core persist and prevent us from being able to make this change at the moment.

cc/ @tyxla

**Comment by tyxla** [comment]
@sarayourfriend perhaps this will help? https://github.com/WordPress/gutenberg/pull/29038

**Comment by tyxla** [comment]
Let's not abandon this so quickly! I'm working on some fixes, marking this as "blocked" in the meantime.

**Comment by tyxla** [comment]
I've spent some more time with this one and got it working. It needed some additional work, though - it'll still fail to build at this time. I've opened some PRs to fix that.

Those resolve various SSR errors that occur when trying to build Calypso with the `VisuallyHidden` component:

* https://github.com/WordPress/gutenberg/pull/29067
* https://github.com/WordPress/gutenberg/pull/29068
* https://github.com/WordPress/gutenberg/pull/29069
* https://github.com/WordPress/gutenberg/pull/29070

This is required to provide `process` to the browser and therefore to the `@wordpress` components in runtime:
* https://github.com/Automattic/wp-calypso/pull/50172

Finally, I've pushed some commits to
* Remove old references of `ScreenReaderText` from devdocs
* Add some missing types
* Update the TS compiler target of the components package.

Once all these are merged (and relevant dependencies are upgraded), this PR should be unblocked. Let's see what happens!

**Comment by tyxla** [comment]
Rebased to contain the change where we add the global `process` env var to the webpack build. 

This is still blocked by releases of the following `@wordpress` packages:

* `@wordpress/components`
* `@wordpress/dom-ready`
* `@wordpress/keycodes`

**Comment by sarayourfriend** [comment]
It may be worth still attempting this, but in its current state rebasing this PR will be a chore! I'll close it and let @Automattic/team-calypso-components take it from here if they want to still do this.

**Pull request closed without merging**
