### PR TITLE
Media: add external source dropdown

### PR DESCRIPTION
**Pull request by johngodley**
Adds a dropdown to the media library to toggle between the data source (currently WordPress and Google). This will affect the media modal when editing a post and also the main media page.

When viewing WordPress the standard files and buttons appear:

wp_1

On a smaller screen this reduces down to:

mobile

Clicking the dropdown shows a menu:

popover

When viewing Google the filter bar disappears and the search bar is shown full time:

gphotos

## Testing

- While editing a post click the media button. Verify that the new dropdown is shown in the top left of the media library modal
- Verify that normal WP media functions operate as expected
- Click the dropdown and change to Google Photos
- Verify that you view and copy a photo
- Switch back to WordPress media
- Exit the media library modal and open the main Media page
- Verify the dropdown is present and switches between the data sources
- Verify that you the new 'copy to library' exists when you have selected a Google Photo, and that clicking it switches to WordPress and copies the image across. This button should stick to the top of the page as you scroll down
- Go to the site settings page and click 'Change' on the site icon. Verify that the dropdown appears in the media library and operates as expected
- Verify the above when viewing in mobile/responsive mode, and that the dropdown adjusts appropriately

### CODE REVIEW

**Comment by nosolosw** [comment]
Tested this and this behavior struck me as relevant: 

- so I went to the media library, switched to google photos, and search for "Berlín"
- some pictures are shown for that search. I choose one and click "copy to media library"
- it changes to WordPress.com but the search is still "Berlín". The search terms are maintained but WordPress.com has a different opinion on what to show on "Berlín". For that reason, the WP screen shows no photos.

Shall we clear the search filter when change sources given that they behave differently?

**Comment by johngodley** [comment]
> Shall we clear the search filter when change sources given that they behave differently?

Ah, I forgot the media page changes the page URL for the search. I've updated the code to clear this whenever the search is cleared. It should still work if you search in Google Photos and then copy a found image - the timing of the actions is important otherwise the placeholder disappears.

**Comment by johngodley** [comment]
@jasmussen, pinging you for a design review. Let me know if the CSS looks sensible, and feel free to make any spacing changes you think necessary.

**Comment by jasmussen** [comment]
I'll take a look at this as soon as I can. Hopefully tomorrow.

**Comment by folletto** [comment]
Functionally seems correct, and uses some patterns we already have elsewhere. If possible I'd however try to align the patterns to the Editor, which already has that kind of UI.

Here's a i1 mockup:

media-library-library-selector

It's functionally identical, just a few tweaks if we have the time:

1. Icon size is at 24px — using `gridicon-my-sites` for the WordPress one
2. The dropdown chevron is at `18px` and swaps direction when toggled
3. Color when open is `$gray-dark`
4. Some tweaks to chevron and icon spacing
5. Square dropdown

I hope it helps :)

**Comment by johngodley** [comment]
@folletto that's great, thanks! A couple of questions before I make changes.

> The dropdown chevron is at 18px

It's currently at 20px as this matches the size of filters chevron (part of `SectionNav`) when responsive:

filters

Which size is correct?

> Square dropdown

I went with a `PopoverMenu` as the `SelectDropdown` forces the width of the whole dropdown to the widest item, whereas the Popover is just the width of the logo. Is there a component that behaves like a dropdown as shown in your image?

**Comment by folletto** [comment]
> Which size is correct?

It's probably a mismatch we need to solve higher up in the hierarchy.
Let's match them on mobile size, would that work?

> Is there a component that behaves like a dropdown as shown in your image?

...this makes me guess the Editor one isn't a component but TinyMCE right? I guess not then?

We can push it live without that styling (just the updated content) and tackle it later if it's too much trouble to have the component done now.

**Comment by jasmussen** [comment]
> ...this makes me guess the Editor one isn't a component but TinyMCE right? I guess not then?

> We can push it live without that styling (just the updated content) and tackle it later if it's too much trouble to have the component done now.

Yeah I think that dropdown is part of TinyMCE.

I agree, it'd be nice to have a unified dropdown component so it all looked the same, but it also seems like it'd be worth doing this separetely.

**Comment by johngodley** [comment]
I've updated as follows:

- Icon size is 24px
- Chevron changes direction
- `$gray-dark` used when open
- Tweaked the spacing - it should now be vertically and horizontally aligned

Things I haven't done:
- Chevron is still 20px to match the existing filter chevron. Also note that when viewed on mobile the vertical alignment is off a little, to also match the existing filter dropdown which is not vertically aligned - the original component probably needs fixing
- Still using a popover. As discussed above this can be replaced with a better component when available later
- As we're going with the popover I've left the text the same - there's a label to identify we're changing library (I think with a normal dropdown we need something to say that we're switching library). Saying that, it's an easy change to make so I can do it now and remove the label. For some context we've been asked not to use the term Google Photos, so the text would have to be something like 'WordPress library' and 'Google library' (or 'Photos from Google library', which is the term we're going with - a bit bulky in this context). We may also have additional services added in the future (Dropbox, Amazon etc) so it's possible that repeating 'library' on each one may look excessive.

Screenshots updated to reflect changes

@folletto

**Comment by folletto** [comment]
Excellent! I think it's solid, and ok on postponing the dropdown then. :)

Two finishing touches if possible, given the background you mention above:

1. I'd still go with a clean popup, no "intro" message, and these labels: "WordPress library" and "Photos from Your Google library". The reason is that intro text are often skipped anyhow, and it would make the pick specific. Given the need to avoid "Google Photos" the addition of "Your" should also avoid confusion with "Google Search".
2. If possible, I'd also introduce the icons as the item in the bar is without label, and would help with visual resonance. Might be some work, so feel free to postpone this too. It's more important to get the PR in. ;)

**Comment by johngodley** [comment]
Label removed, text changed, and icons added - it's a good improvement!

popover

**Comment by nosolosw** [comment]
Search now is cleared when changing sources. Media library, media modal, and featured image work as expected.

I ran into this problem when changing the site icon:

* go to settings
* click change site icon
* change source to google
* chose a picture, copy to library, and quickly tap continue
* the image editor for the site icon is opened but shows this error

site-icon-error

Upon the upload is finished, the image is shown in the modal, and I could edit it and successfully changed the site icon, though.

Also, JFYI, an unrelated bug that is currently present in the media library that I happened to have discovered in testing this https://github.com/Automattic/wp-calypso/issues/17240

**Comment by folletto** [comment]
> Label removed, text changed, and icons added - it's a good improvement!

Looks great! Thank you!

I also checked small screen sizes, and the text fits well, so we should be good! 👍 

---

I found a minor thing — can we avoid specifying "is-selected" in the list? I know it's semantically correct, but it creates some odd states:

screen shot 2017-08-16 at 13 53 52

**Comment by johngodley** [comment]
Added a fix for the site icon. It was trying to load the file from the external source (Google), but was blocked by lack of CORS headers. The fix involves disabling the 'continue' button until the file has copied

Removed the is-selected too.

**Comment by folletto** [comment]
Ace! I've no more feedback here! Good work 👍

**Comment by jasmussen** [comment]
+1 good work 👍 and thanks Davide for all this feedback.

**Pull request merged**
