### PR TITLE
Reader post card - move title and excerpt above images

### PR DESCRIPTION
**Pull request by Addison-Stavlo**
Related to # pe7F0s-1fb-p2 

## Proposed Changes

* Updates the reader post cards to show the title and excerpt above the image or gallery.

Before:

Screenshot 2023-09-13 at 2 27 20 PM

After:

Screenshot 2023-09-13 at 2 27 53 PM

## Testing Instructions

* Test this in the reader.
* View streams with non-compact post cards (recent, search, etc.).
* verify the title and except are above the image
* verify the various paddings/spacings make sense above and below the image.
* Smoke test other streams in the reader, compact cards, etc. to verify we havent accidently broken any styles with the titles and excerpts.

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

**Comment by Addison-Stavlo** [comment]
This is now updated to pull in the recent changes of removing the tags listing as well. Good for testing!

**Review by davemart-in — APPROVED** [review]
I made a few updates to the margin and padding. This turned into a bit more of a rabbit hole than I had originally anticipated. At some point I had to stop myself from making additional tweaks. 😅 I'm pretty  happy with where this ended up though.

**Comment by Addison-Stavlo** [comment]
@davemart-in I am seeing a couple issues after the recent padding/margin updates:

In some cases the post actions are cut-off a bit:
Screenshot 2023-09-14 at 10 51 34 AM

It also looks like some of these changes are bleeding to the compact cards (extra margin/padding above the title).
Before:
Screenshot 2023-09-14 at 10 51 57 AM

After:
Screenshot 2023-09-14 at 10 52 01 AM

**Comment by Addison-Stavlo** [comment]
@davemart-in  - I THINK the last 2 commits accomplish what you were looking for.  HOWEVER, the very top of card spacing might be a bit larger than you expected now. It was 16px and I updated it to 24 like you pointed out, but also in your mock-ups this was listed as being 23 px to update to 24, so it may be a much bigger jump than expected there.

**Comment by davemart-in** [comment]
This PR looks really sharp! Kudos! I'd say let's ship it and we can circle back to any edge cases that we might stumble upon later.

**Pull request merged**
