### PR TITLE
Update sticky state for the plans grid action buttons

### PR DESCRIPTION
**Pull request by oswian**
Related to https://github.com/Automattic/wp-calypso/issues/82853

## Proposed Changes

* For the plans grid action buttons in sticky state:
  * The button copy now uses parentheses ("Upgrade (€17)") instead of a hyphen ("Upgrade – €17")
  * The button font size is no longer reduced

| Before | After |
| -- | -- |
|CleanShot 2024-10-21 at 14 54 33@2x|CleanShot 2024-10-21 at 14 53 31@2x|

## Why are these changes being made?

* The copy "Upgrade – €17" is confusing because the '-' can be interpreted as a minus sign
* The reduced font size is unexpected as the button copy still fits using the larger/original font size

## Testing Instructions

* Visit `/plans/:site`
* Scroll down the plans grid until the upgrade buttons enter sticky state
* The button copy should uses parentheses around the amount eg. "Upgrade (€17)" instead of "Upgrade – €17"
* The button font size should not change when entering the sticky state

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Comment by oswian** [comment]
The ticket raises an additional issue, however I haven't been able to replicate:

> "When I scroll up, then on the bottom edge of the page the action buttons also become sticky (or at least get the sticky styling), but they are not really sticky, they scroll away."

I've added a [comment](https://github.com/Automattic/wp-calypso/issues/82853#issuecomment-2425526578) to the ticket. If you're able to reproduce this behaviour, let me know!

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/16934997).

**Comment by southp** [comment]
I'll need to double check on the font size behavior against some longer languages. In the meantime, I think it'd be the best if we follow what `/pricing` does for consistency:
CleanShot 2024-10-21 at 16 16 36@2x
i.e. instead of parentheses, using the dot symbol. One side advantage is that we won't need to wait for translation, since we will be simply reusing it.

**Comment by southp** [comment]
Wrapping to a new line for longer copy + currency works as expected:
CleanShot 2024-10-21 at 17 07 21@2x

One thing I'd like to mention is that we seem to wrap the line overly conservative, e.g. English + MX:
CleanShot 2024-10-21 at 17 10 52@2x
It's obvious that there is still room to fit everything into one line. However, since it's the same behavior in production, we should create a follow-up for it if we really want to address it.

**Comment by oswian** [comment]
@southp Thanks for the review!

> instead of parentheses, using the dot symbol

Good idea, updated to use the dot: [fcdffc9](https://github.com/Automattic/wp-calypso/pull/95537/commits/fcdffc99360280ad6e6ca31781ace985b414253f)

> It's obvious that there is still room to fit everything into one line. However, since it's the same behavior in production, we should create a follow-up for it if we really want to address it.

Yes you're right, there is quite a bit of room. I've created a ticket: https://github.com/Automattic/martech/issues/3504

---

I've also pushed a fix to prevent the sticky behaviour at the bottom of the screen: https://github.com/Automattic/wp-calypso/pull/95537/commits/95497180e94c5fdb66b98444e00cee6490421c14

**Comment by oswian** [comment]
Just noticed we have separate action button strings for the `/start/plans` page, so these need to be updated as well. Update pushed: https://github.com/Automattic/wp-calypso/pull/95537/commits/05b3a5d4f4e29fa097bdc95da311e7fed597b481

**Comment by southp** [comment]
Looks like some mandatory tests are somehow broken 🤔 Revisiting this PR is on my radar, so I'll be back once they are fixed :)

**Comment by oswian** [comment]
>Looks like some mandatory tests are somehow broken 🤔 Revisiting this PR is on my radar, so I'll be back once they are fixed :)

@southp A rebase seems to have resolved the build errors. Ready for another look when you get a chance 🙏

**Review by southp — APPROVED** [review]
Confirmed that the issue has been fixed on Firefox with this change. The updated strings also look good; I originally thought the strings could be reused here, but they seem to be constructed differently. I think the current way is more natural for our use cases, so let's keep them and wait for translation :)

**Comment by oswian** [comment]
@southp Thanks for the review.

> I originally thought the strings could be reused here, but they seem to be constructed differently. I think the current way is more natural for our use cases, so let's keep them and wait for translation :)

Makes sense. I'm seeing an error (related to translations) in the `ci/i18n` build step: `Unable to retrieve strings file from CI for this branch. This usually happens when the latest build failed`.

I'll try re-running the build.

**Comment by oswian** [comment]
The build is happy after a rebase. Proceeding with merge.

**Pull request merged**
