### PR TITLE
Edited list of themes available in signup flow.

### PR DESCRIPTION
**Pull request by mapk**
This PR updates the list of themes as per @johnmaeda's request in issue #18379.

### CODE REVIEW

**Comment by seear** [comment]
Might be worth updating the [_You might also like..._](https://github.com/Automattic/wp-calypso/blob/61cf7de7763470b4094c9cc49549b79cd54da0d6/client/my-sites/theme/themes-related-card/index.jsx#L28) list soon to match these signup themes.

**Comment by johnmaeda** [comment]
Thanks for this list:

getRelatedThemes() {
		let themes = new Set( [
			'twentysixteen',
			'rowling',
			'hemingway-rewritten',
			'gazette',
			'intergalactic-2',
			'isola',
			'edin',
			'sela',
			'pique',
			'harmonic',
		] );

Is there a similarity algorithm that tries to choose something from this list? Or is "related" = "random"?

**Comment by seear** [comment]
> Is there a similarity algorithm that tries to choose something from this list? Or is "related" = "random"?

Yeah, it is random. So there is possibly an opportunity here to direct people into one of the buckets blog/page/grid if we have a way to tell which would suit their needs.

If they are browsing a grid theme, we could direct them to one of our favoured grid themes, but that doesn't necessarily mean they want/need a grid theme.

**Comment by mapk** [comment]
I'll merge the PR, and look at creating another PR for the "You might also like..." list.

**Pull request merged**
