### PR TITLE
Media: Warn about Personal File Uploads in Guided Tours

### LINKED ISSUE #38974: Media Library: Informing Users that Files in the Library are Public
Many users don't realize that everything they put into the Media Library can be accessed by anyone.

I believe we should explicitly inform users that content uploaded to the Media Library is Public. There could be a short notification on top of the Media Library users could read and then close - so it won't clutter the interface.

Thank you.

#### Context / Source

Discussions with users on 1:1s, observations from tickets and chats.

#anecdote #user-report

### PR DESCRIPTION
**Pull request by Aurorum**
#### Changes proposed in this Pull Request

In #38974, it was requested that the Media section inform users about file uploads being public whilst avoiding cluttering the interface. I think Guided Tours is the best way to do this, since that way, new users quickly get the information without seeing it again. 

#### Testing instructions

Visit `/media/site?tour=mediaBasicsTour` and verify that this appears.

Screenshot 2020-01-24 at 21 58 51

I suspect this might need a copy review? (cc @michelleweber) The copy is here:

> When your site is set to public visibility, all media files can be accessed by anyone, even if you have not included them in a post.
>
> It is therefore recommended that you do not upload any personal files.

Fixes #38974

### CODE REVIEW

**Comment by michelleweber** [comment]
Hmm... yeah, I could see this being a little alarming-sounding to a user. I wonder, could this tooltip instead appear with an actual file upload details page, so it could point to the file URL and we could use that to help explain? 

If that's not possible, could we try to make it a little lighter-sounding with something like:

> FYI: All files you upload to WordPress.com get their own web address. If your site is public, any file can be technically accessed by anyone who has its address, even if you haven't included them in a post. It's unlikely, but possible.
> 
> (In other words, this probably isn't the place for personal files.)

@obi2020, would love your take on this if you have a moment.

**Comment by Aurorum** [comment]
Thanks @michelleweber! Moving the tooltip to the actual file page with the URL field is definitely possible, and I've updated it to this, and also changed the language.

Screenshot 2020-01-23 at 17 59 01

I should note that I've changed this:

> can be **technically** accessed by anyone who has its address

to this: 

> can **technically** be accessed by anyone who has its address

I fear that former unintentionally gives the impression that it's possible to use some sort of technological tool to see all such images, and I don't think that exists, though I might be wrong (it'd probably play in to the alarming tone!)

Do you think that's reasonable? :)

**Comment by michelleweber** [comment]
Entirely reasonable! I think this works really well, and I like it on this screen if you do.

**Comment by Aurorum** [comment]
Perfect! I think that having it on the URL field is a better choice too.

**Comment by Aurorum** [comment]
Just realised I can't use the reviewers feature on this PR for some reason, but it's recommending me @retrofox who have appears to have edited this file recently; cc if you're interested in this (+ @sgomes) :)

**Comment by obi2020** [comment]
If you're still open to copy feedback:

@michelleweber's edits are good. I were to refine it would be to make it a bit shorter, and easier to scan. For example,

Give it a bold or larger header that has the main message, for example: 

> - Make sure you okay with these files being public:
> - FYI: Files uploaded here or publicly available
> - Note! Your files can be accessed publicly

Followed by the explanation (which I've streamlined a bit), for example:

> All files you upload to WordPress.com get their own web address. If your site is public, anyone with this address can access the file, even if you haven't included it in a post. It's unlikely, but possible.

***

Note that I suggested removing the word "personal" because I don't know what it means or if it's relevant here. It could be misconstrued. 

Also, I really like the inclusion of "It's unlikely, but possible." Good example of adding a little ✨brand voice✨ to enhance the experience.

**Comment by Aurorum** [comment]
Yep, always happy to change the text! That sounds good, and I've updated the wording now. I opted for the `Make sure you okay with these files being public:` message as that's applicable to both private and public sites. :) 

Screenshot 2020-01-24 at 21 51 47

**Comment by Aurorum** [comment]
Actually, that's a typo I think. I'll fix that. :)

> Make sure you **are** okay with these files being public

Screenshot 2020-01-24 at 21 58 51

**Review by sixhours — APPROVED** [review]
Screen Shot 2021-05-13 at 3 23 57 PM

Looks good! 👍

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/5906281

Thank you @Aurorum for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/5906281).

**Pull request merged**
