### PR TITLE
Set Universal Text Styles more specific. Move it into .theme-jetpack-cloud

### PR DESCRIPTION
**Pull request by cleacos**
#### Changes proposed in this Pull Request

Set the Universal Text Styles introduced by Caleb more specific, so let's move it inside of `.theme-jetpack-cloud` class. Currently, they don't work well because is less specific in the inheritance of CSS.

#### Testing instructions

- Apply changes
- Now you can use the text styles `h2`, `h3` and `p` without problems

### CODE REVIEW

**Comment by enejb** [comment]
Can you provide some examples where the current styles don't work as expected?

I think it would be best if these styles were generic like they currently are. 
This makes them easier to overwrite.

**Comment by cleacos** [comment]
@enejb I was trying to use the `h2` but the CSS engine select 

`<h3>Changes in this backup</h3>`

With generic, the CSS engine decides to use this:
image

Being more specific it decides to use this, the expected style:
image

If not, we'll have to use `!important`

**Comment by enejb** [comment]
Thanks for the explanation. 

I think I understand what is going on on better now. In development the regular calypso styles overwrite our own because they happen to be included always after our rules. 

In production we the loading order is a bit different. 

I suggest that instead of prefixing the tags h2, h3 with a classname. 
We should prefix them with html 
this way we would increase the specificity just a bit more but still not make it so specific that we 
they become hard to overwrite by other classes. 

```
html h2 {
	font-size: 22px;
	font-weight: 700;
	line-height: 32px;

	@include breakpoint( '>660px' ) {
		font-size: 36px;
		line-height: 40px;
	}
}

html h3 {
	font-size: 16px;
	font-weight: 700;
	line-height: 23px;

	@include breakpoint( '>660px' ) {
		font-size: 18px;
		line-height: 23px;
	}
}

html p {
	font-size: 16px;
	line-height: 24px;

	@include breakpoint( '>660px' ) {
		font-size: 18px;
		line-height: 24px;
	}
}
```


Can you try that and see if it works for you?

**Comment by cleacos** [comment]
@enejb Yes, it works. Thanks for the explanation. I pushed a new commit https://github.com/Automattic/wp-calypso/pull/41399/commits/9974d10f48ff1a737cda299c33df26d527934de3 to be less specific

**Pull request merged**
