### PR TITLE
Update /hosting-config layout

### PR DESCRIPTION
**Pull request by candy02058912**
Related to https://github.com/Automattic/dotcom-forge/issues/9531

## Proposed Changes

1. Reorder web server settings

Moved PHP version under WordPress version

(Staging site)

| Before  | After |
| :-------------: | :-------------: |
|   | |

2. Consistent treatment for links at the end of a sentence
Remove `.` after `Learn more`

| Before  | After |
| :-------------: | :-------------: |
|   | |

## Why are these changes being made?

* Improve consistency

## Testing Instructions

* Go to `/hosting-config/:site`, note that you may see different navigation tabs on wpcalypso and dev environment, you can turn it off by adding `?flags=-untangling/hosting-menu`, this is part of pbxlJb-6ye-p2
* Check if those changes are there
* Note that not every site has the same options available (e.g. WordPress version), so remember to check between staging and atomic sites

## Pre-merge Checklist

- [x] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [x] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [x] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Review by matt-west — APPROVED** [review]
Looks good! Thanks @candy02058912

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/16993935).

**Review by wongasy — APPROVED** [review]
Changes look great!

I was able to confirm these changes in the new Settings > Caches tab via the Calypso live link:

Screen Shot 2024-11-07 at 11 03 07 AM

@matt-west Does the "Review privacy settings." stand as the odd one out? Should we also remove `.` from that link?

**Comment by matt-west** [comment]
> @matt-west Does the "Review privacy settings." stand as the odd one out? Should we also remove . from that link?

Yeah, I think we can remove the period there.

**Pull request merged**
