### PR TITLE
Fix state property name

### PR DESCRIPTION
**Pull request by brunoscopelliti**
I just noticed a mistake in this #9754 PR of mine.
The error does not seems to cause any visual regression on master, however it's important that we fix it, cause it breaks the sites-dropdown component in the contact form on the PR #9624.

### CODE REVIEW

**Comment by gwwar** [comment]
Do you mind updating the SitesDropdown readme as well

**Comment by brunoscopelliti** [comment]
Now it should be ok.

**Comment by gwwar** [comment]
Thanks @brunoscopelliti, this looks good. 👍

**Comment by gwwar** [comment]
Nice PR number btw 😄

**Pull request merged**
