### PR TITLE
CPTs: Update toggle descriptions to clarify toggle behaviour when using a theme that supports CPTs

### PR DESCRIPTION
**Pull request by coder-karen**
Related to https://github.com/Automattic/vulcan/issues/614

## Proposed Changes

* This PR adds additional text to the Testimonial toggle description, on the `wordpress.com/settings/writing/` page. 
* It also updates the cases where the Portfolio toggle description text is displayed - from just WoA, to WoA and Simple (this description was modified here: https://github.com/Automattic/wp-calypso/pull/94899)

## Why are these changes being made?

* This is designed to explain why the toggles will not have an affect on sites who use themes that support Jetpack CPTs (as this will be active regardless).

## Testing Instructions

* The best way to test would be to use the Calypso Live link provided in the generated comment below. Using that, visit the following page, replacing the container-live URL if necessary, and replacing the URL at the end with that of a WoA test site, a Simple test site, and a self-hosted test site: `https://container-naughty-hypatia.calypso.live/settings/writing/example-woa-site.com`. You should see the additional text in the following cases:
  * Portfolios toggle:
    * For WoA and Simple sites
  * Testimonial toggle: 
    * For self-hosted, WoA and Simple sites
* You should not see the additional text in the following cases:
  *  Portfolios toggle:
    * For a self-hosted site

~Note: I was unable to test the Calypso live link for a WoA site (same with wp-calypso local development, with and without changes), so I suspect since the previous PR to update the portfolio toggle text there have been some other environment changes here. As this is just a text change I should be able to test live after deployment as well, and can then follow up with another PR if needed.~

Screenshot showing additional text:

Screenshot 2024-12-13 at 15 19 16

## Pre-merge Checklist

- [x] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [x] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [x] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
    - [ ] For UI changes, have we tested the change in various languages (for example, ES, PT, FR, or DE)? The length of text and words vary significantly between languages. 
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Review by darssen — CHANGES_REQUESTED** [review]
Thanks for working on this @coder-karen!

I was able to test using https://container-blissful-mendel.calypso.live/ 

For the atomic site I checked (https://container-blissful-mendel.calypso.live/settings/writing/darssenatomic26.wpcomstaging.com), it seemed to have the same behavior as self-hosted, which means  `siteIsJetpack` is probably returning true for it too.

**Comment by coder-karen** [comment]
Thanks @darssen for testing (and adding me as an admin on your WoA test site) - I've updated the logic and can see the correct results for your test site now (and self-hosted, Simple). The new Calypso Live site for testing is now `container-naughty-hypatia.calypso.live`.

**Review by darssen — APPROVED** [review]
Works as expected. :ship:

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/17065854).

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/17065854).

**Pull request merged**
