### PR TITLE
A4A: Add base code for the Hosting tab at the Preview Pane

### PR DESCRIPTION
**Pull request by cleacos**
Resolves: https://github.com/Automattic/automattic-for-agencies-dev/issues/262

## Proposed Changes

This PR adds the new Hosting tab to the Preview Pane as a code base with a draft Hosting tab content.

The Hosting tab is behind this feature flag: `a4a/hosting-preview-pane` and active in `development` and `horizon`.

image

Also, this PR reorganizes the folder/files a bit:

- `features/hosting/overview.tsx` - This is the Hosting Overview Preview Pane with the Hosting provider, PHP/WP version. The `hosting` folder represent the Hosting family context, and here we will add the different tabs the Hosting family will have. This PR adds the first tab, the Hosting Overview content.
- `features/jetpack/jetpack-preview-pane` - This will be the Jetpack family Preview Pane. I cleaned up it and left only Jetpack features, and I removed the A4A Details tabs, moving it to the A4A Overview family.
- `features/overview/index.tsx` moved to `features/a4a/overview-preview-pane.tsx` - This is the entry point. Now, is where we build and add the feature tabs (Jetpack, Hosting, and Details) to the Preview Pane.

## Testing Instructions

- Check the code and become familiar with the feature folder structure.
- You have to see the new Hosting tab, and its content (draft content)
- Navigate through the tabs to ensure that everything is working
- The Hosting tab should have this slug/route: /sites/overview/{site_url}/hosting-overview

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Review by gogdzl — APPROVED** [review]
I took the liberty of correcting the misspelling in the folder name. It was written as 'Presseable' instead of 'Pressable'.

Other than that, this is a good starting point for the hosting tab!

LGTM!

**Review by coder-karen — APPROVED** [review]
Looks good!
Do we want to add a bordered container within the Hosting preview pane tab in this initial PR or leave that until later? Purely because all but Activity have that style and without it the text sites quite close to the left of the pane, but I know it's just (mainly) dummy data at the moment.

**Comment by cleacos** [comment]
> Do we want to add a bordered container within the Hosting preview pane tab in this initial PR or leave that until later? 

Later in this issue: [Design the Hosting component that displays the hosting-level information](https://github.com/Automattic/automattic-for-agencies-dev/issues/263)

**Comment by cleacos** [comment]
> I took the liberty of correcting the misspelling in the folder name. It was written as 'Presseable' instead of 'Pressable'.

Thank you @gogdzl!

**Pull request merged**
