### PR TITLE
Plans Page: Adds estimate for Search

### PR DESCRIPTION
**Pull request by ChaosExAnima**
#### Changes proposed in this Pull Request

* This adds a disclaimer to Jetpack Search that the number of records are an estimate only.

#### Screenshots
Screen Shot 2021-01-07 at 3 49 36 PM
Screen Shot 2021-01-07 at 3 50 59 PM

#### Testing instructions

1. View the plans page for a site with Jetpack.
2. Observe Jetpack Search card shows the estimate disclaimer with correct number of records from API.
3. Verify prices page with no site is identical to #48698.

Fixes 1164141197617539-as-1199519139839503.

### CODE REVIEW

**Review by eeeeevon13 — CHANGES_REQUESTED** [review]
Can you make the info icon flush to the top of the text to the left of it? 
And the button color looks off?

**Review by eeeeevon13 — APPROVED** [review]
Looks good

**Review by elliottprogrammer — APPROVED** [review]
Works and looks great!  Everything LGTM! 👍

Markup 2021-01-08 at 12 10 46

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/5401301

Thank you @ChaosExAnima for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/5401301).

**Pull request merged**
