### PR TITLE
Remove redundant feature flag

### PR DESCRIPTION
**Pull request by SiobhyB**
The `jetpack/app-branding` feature flag originally added in https://github.com/Automattic/wp-calypso/pull/6681 has since been set to `true` across all environments. We also don't have future plans that will make it necessary or useful to set the flag to `false`. Therefore, in the following series of PRs, all redundant code associated with the flag was removed:

* `Get Apps`: https://github.com/Automattic/wp-calypso/pull/74263
* `Customer Home`: https://github.com/Automattic/wp-calypso/pull/74290
* `Apps Badge`: https://github.com/Automattic/wp-calypso/pull/74296
* `Apps Banner`: https://github.com/Automattic/wp-calypso/pull/74284
* `Apps Promo Sidebar`: https://github.com/Automattic/wp-calypso/pull/74288

## Proposed Changes

* As all code relying on `jetpack/app-branding` has been removed, and the flag is always set to true, it can be removed.

## Testing Instructions

* Search the codebase for `jetpack/app-branding` to ensure there are no remaining references.
* Visit the areas of Calypso that mention the Jetpack mobile app to ensure there are no changes to their design or functionality. This was also covered as part of the reviews for each of the linked PRs above, and more thorough testing steps can be found in each of those individual PRs.   

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

**Comment by SiobhyB** [comment]
@dcalhoun, @jhnstn, 👋 , I'm hoping that this will be the last "clean up" PR. I wanted to request your reviews before removing the feature flag, to make sure I haven't missed anything with the previous PRs and to see if you have any concerns about removing the flag beforehand. Thanks in advance!

**Review by tyxla — APPROVED** [review]
Thank you for the wonderful cleanup, @SiobhyB 🙌 😍 

We love seeing all the red lines 🟥 Keep them coming! 😅 

🚀

**Review by dcalhoun — APPROVED** [review]
LGTM. Thank you for taking the time to clean up all this temporary code. Awesome! 👏🏻 

> Visit the areas of Calypso that mention the Jetpack mobile app to ensure there are no changes to their design or functionality.

I left a [comment capturing](https://github.com/Automattic/wp-calypso/pull/74284#issuecomment-1464025631) a couple of likely unintended design changes on the related PR. That shouldn't block this PR, though.

**Comment by SiobhyB** [comment]
@dcalhoun, thanks so much for spotting that regression, I'll go ahead to merge this PR and address that separately 🙇‍♀️

**Pull request merged**
