### PR TITLE
Upgrade Prettier fork to version 1.9.2 (try 2)

### PR DESCRIPTION
**Pull request by jsnajdr**
Second attempt at merging this. The first one was #21132 and I had to revert because Canaries failed nobody was available for help on a holiday.

@alisterscott @hoverduck would you mind running a full e2e suite on this PR before merging? This is the failed build on my previous attempt from Dec 29:

https://circleci.com/gh/Automattic/wp-e2e-tests-canary/5672

After reverting, the tests succeeded again in the very next build.

It's strange that the e2e tests would fail given that this PR is supposed to be just whitespace formatting changes and nothing else.

When the failing build was on staging, I clicked around Calypso and couldn't find anything suspicious -- everything worked.

### CODE REVIEW

**Comment by jsnajdr** [comment]
Now the `e2e-tests-for-branches` build failed: https://circleci.com/gh/Automattic/wp-e2e-tests-for-branches/1982

[WPCOM] Sign Up  (mobile, en) Sign up while purchasing premium theme @parallel @email @canary Step 1: Themes Page Can see the themes page

**Comment by gwwar** [comment]
Unit tests are also failing from ```/home/ubuntu/wp-calypso/client/my-sites/site-settings/theme-setup-dialog/index.jsx
  57:1  error  Line 57 exceeds the maximum line length of 140  max-len```

**Comment by gwwar** [comment]
@hoverduck @alisterscott it's much appreciated if we could run e2e tests against this branch. When folks are free give @jsnajdr a ping to rebase, as this one will get out of date pretty quick.

**Comment by hoverduck** [comment]
@gwwar I'm running them now

**Comment by jsnajdr** [comment]
> Unit tests are also failing from

That's a pre-existing eslint error on a line that's not even affected by this PR. Looks like some eslines bug.

**Comment by hoverduck** [comment]
The e2e tests came back clean and green.

**Comment by gwwar** [comment]
Thanks so much @hoverduck!

**Comment by gwwar** [comment]
> That's a pre-existing eslint error on a line that's not even affected by this PR.

@nosolosw any ideas here on why eslines is misbehaving?

**Comment by jsnajdr** [comment]
After a careful rebase and doing the reformat from scratch instead of rebasing the old commit, all mysterious eslint errors disappeared and all checks are green. I'm going to merge this in the next 2 hours.

**Comment by sirreal** [comment]
Thanks @jsnajdr 🎉

**Comment by nosolosw** [comment]
@gwwar @jsnajdr happy to see this solved. Next time you see `eslines` misreporting, do you mind if I ask you to create a copy PR I can play with to investigate?

**Pull request merged**
