### PR TITLE
Jetpack checklist: add introduction to .com dashboard

### PR DESCRIPTION
**Pull request by simison**
#### Changes proposed in this Pull Request

* Add introduction to WordPress.com dashboard in checklist's thank-you page.

The first step in https://github.com/Automattic/wp-calypso/issues/33285 (see https://github.com/Automattic/wp-calypso/issues/33285#issuecomment-495383451)

#### Testing instructions

- Have Jetpack sites with a free and paid plan.
- Open `calypso.localhost:3000/plans/my-plan/:site?thank-you`
- In both cases you should see this:
   
Screenshot 2019-05-24 at 09 46 28

I didn't add this for special error states now since percentages of users hitting those are low and we have better solution than this copy in the plans.
That's also why I didn't worry about having the same string twice in two different components; I've understood we might remove this with the guided tour. Happy to move it to `ThankYouCard` component tho, it's a quick change.

### CODE REVIEW

**Comment by ockham** [comment]
> That's also why I didn't worry about having the same string twice in two different components; I've understood we might remove this with the guided tour. Happy to move it to `ThankYouCard` component tho, it's a quick change.

I think I'd prefer that to avoid duplication (even if we expect it to be gone soon -- you never know :wink: ). You can probably also move the string above (`You're now ready to finish the rest of the checklist`) to that component.

**Comment by ockham** [comment]
> You can probably also move the string above (`You're now ready to finish the rest of the checklist`) to that component.

Uh, nevermind, that would also show up in the error case, right? Ignore then :grimacing:

**Comment by simison** [comment]
Might be ok to show for errors but not in "loading" state.

I'll just move it to component and add a `showCalypsoIntro` prop to control it. It's some hidden magic but there's already plenty of it so little more won't hurt. :-)

**Comment by simison** [comment]
@ockham Moved! https://github.com/Automattic/wp-calypso/pull/33300/commits/fc31778196341e63ff21be4210ff56d012ccd343

**Comment by sirreal** [comment]
Given that this is going into the post-provisioning views, we could just make a clickable link to WP Admin right in the card. Thoughts @jeffgolenski ?

At that point we should probably introduce a selector to grab the WP Admin URLs since we're doing that in several places.

**Comment by jeffgolenski** [comment]
> Given that this is going into the post-provisioning views, we could just make a clickable link to WP Admin right in the card. Thoughts @jeffgolenski ?

Do you mean adding a link to wp-admin right in this "Welcome" card as shown above? If that's what you mean, I'd like to caution against that. I want people to at least look at the checklist, and know it exists before immediately bailing back to wp-admin. If we add a link to wp-admin in this card, there's a chance a lot of people wouldn't even see the checklist. cc @simison

**Pull request merged**
