### PR TITLE
Jetpack Pro Dashboard: implement reset notification(bulk)

### PR DESCRIPTION
**Pull request by yashwin**
#### Proposed Changes

This PR implements the `Reset Notification` bulk action in the Jetpack Pro Dashboard.

#### Testing Instructions

**Prerequisites**

Since these changes are made specifically for agencies, you must set yourself(partner) as an agency - 2c49b-pb. Make sure to switch it back to the previous type.

> **_NOTE:_** The UI could be broken for the buttons, which will be fixed in a different PR.

**Instructions**

1. Run `git checkout add/implement-reset-notification-bulk` and `yarn start-jetpack-cloud`
2. Open http://jetpack.cloud.localhost:3000/, and you'll be redirected to the /dashboard.
4. Since the UI for `Reset Notification` is in progress in a different PR, we will have to manually add the component `<DashboardBulkActions>` and test it.

```
<DashboardBulkActions
	selectedSites={ [
		{ blog_id: id, url: 'test'.com },
		{ blog_id: id, url: 'test2.com' },
	] }
/>
```

5. Click `Reset Notification` and verify that the below popup is shown based on different scenarios and that notification duration is set to 5 min when saving changes

Confirmation popup(single site)

Screenshot 2023-01-09 at 5 15 59 PM

Confirmation popup(multiple site)

Screenshot 2023-01-09 at 5 16 05 PM

Success notification(single site)

Screenshot 2023-01-10 at 4 37 38 PM

Success notification(multiple site)

Screenshot 2023-01-10 at 4 38 59 PM

#### Pre-merge Checklist

- [x] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [x] Have you checked for TypeScript, React or other console errors?
- [x] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

Related to 1203448324265423-as-1203507036638764

### CODE REVIEW

**Review by madebynoam — APPROVED** [review]
Lgtm!

**Review by oikeme — APPROVED** [review]
Changes work as expected and LGTM

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/7727976

Thank you @yashwin for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/7727976).

**Pull request merged**
