### PR TITLE
Framework: Upgrade to react-redux v5, take four

### PR DESCRIPTION
**Pull request by ockham**
Don't even think about merging this 😉  before ~#11437~ #11867 is in (see https://github.com/Automattic/wp-calypso/pull/11752#issuecomment-284027478).

(Furthermore, note that we can only 5.0.2 but not to 5.0.3 because of https://github.com/Automattic/wp-calypso/issues/11726. A fix is under development in https://github.com/Automattic/wp-calypso/pull/11739.)

cc @blowery

### CODE REVIEW

**Comment by blowery** [comment]
Trying a local variant that lands this on top of #11437 ... will report back.

**Comment by blowery** [comment]
doesn't work as is. working on fixing in #11437.

**Comment by blowery** [comment]
Works now on top of the fixes in #11437. Woo!

**Comment by samouri** [comment]
I think its safe to deploy now that https://github.com/Automattic/wp-calypso/pull/11867 landed

**Comment by blowery** [comment]
rebased off a9c99004819f70a231a4013b01e14ada758f0edd, updated shrinkwrap

**Comment by mtias** [comment]
Nice work @ockham and @blowery, great to see this done.

**Pull request merged**
