### PR TITLE
Framework: update marked to 0.3.9

### PR DESCRIPTION
**Pull request by gwwar**
Marked is currently used in devdocs to help format related readmes. Code blocks should be highlighted as expected in https://github.com/Automattic/wp-calypso/pull/10359

Testing Instructions
===
### Testing

Test various syntax types, checking that A) they are highlighted and B) they are highlighted correctly (allowing for caveats mentioned in https://github.com/Automattic/wp-calypso/pull/10359 ):
- js: [ButtonGroup](http://calypso.localhost:3000/devdocs/client/components/button-group/README.md) (ignoring jsx here)
- javascript: [UrlPreview](http://calypso.localhost:3000/devdocs/client/blocks/url-preview/README.md) (ignoring jsx here)
- jsx: [EmptyContent](http://calypso.localhost:3000/devdocs/client/components/empty-content/README.md)

### CODE REVIEW

**Comment by mcsf** [comment]
This breaks HTML provided in lists, as seen in [`EmptyContent`](http://calypso.localhost:3000/devdocs/client/components/empty-content/README.md):

Before | After
-------|------
screen shot 2018-01-04 at 21 51 57 | screen shot 2018-01-04 at 21 51 59

That aside, no other changes noticed. In the screenshot, you can see that backticks in lists still generate `<code>` nodes, so my hunch is that replacing those `<strong>` tags with `**` should do it.

**Comment by gwwar** [comment]
Thanks @mcsf I've updated the readme to not use the strong tag in 2672ad2

**Comment by gwwar** [comment]
Thanks @spen @mcsf I'll go ahead and land this!

**Comment by spen** [comment]
@mcsf - I'll take a look at the issue you've pointed out now. Still, good to get the update in ASAP given the GH notification :)

**Comment by spen** [comment]
(I realise now that the fix is to just not use `<strong>`, which has already been taken care of by @gwwar :) )

**Pull request merged**
