### PR TITLE
Reader: in new full-post block, enable scroll to comments using #comments anchor

### LINKED ISSUE #7840: Reader Refresh: allow 'jump to comments' in full post using #comments anchor
As in current full post view.

### PR DESCRIPTION
**Pull request by bluefuton**
In the existing full post view, adding the `#comments` to the URL scrolls to the comments section.

This PR adds the same functionality to the new reader-full-post block.

Fixes #7840.

Test live: https://calypso.live/?branch=add/reader/new-full-post-scroll-to-comments

### CODE REVIEW

**Comment by blowery** [comment]
After much debugging, I think I found the issue. 

The `<Comments />` component returns `null` while the tree is loading, so there is no node to scroll to while comments are loading. Occasionally, it takes a while for comments to load.

We try to scroll to the comments when the props change on the Full Post component. This happens when the post loads, and then when the site info loads and again when the feed info loads. This is _not_ tied to the comment load in any way. So we get three opportunities to scroll to the comment node max, none tied to the comment node being available. 

So we need the comment node to appear in the document earlier. It should not return null while loading comments, but instead return the comment header with counts and a loading indicator. That would let us scroll down and see the comments load in.

**Comment by blowery** [comment]
a patch that sorta helps:

```
diff --git a/client/blocks/comments/post-comment-list.jsx b/client/blocks/comments/post-comment-list.jsx
index b9e9895..478cc96 100644
--- a/client/blocks/comments/post-comment-list.jsx
+++ b/client/blocks/comments/post-comment-list.jsx
@@ -168,7 +168,7 @@ class PostCommentList extends React.Component {
 
 	render() {
 		if ( ! this.props.commentsTree ) {
-			return null;
+			return <div className="comments__comment-list">{ translate( 'Loading…' ) }</div>;
 		}
 
 		const {
```

The problem now is that the scroll often ends up in the wrong place. We scroll down before images load and before the related block thunks in, so we often end up at the top of the related block, not in the actual comment section...

It's also not very pretty :)

**Comment by bluefuton** [comment]
We've added loading placeholders for the related posts block in #8334, so hopefully that should help us scroll to the right spot. We'll see!

I'm wary of putting the wrapper element in `client/blocks/comments/post-comment-list.jsx`because I'm not sure if the commentsTree can come back `null` legitimately? It certainly is happening at times (see https://github.com/Automattic/wp-calypso/issues/8171#issuecomment-250016653) but that may well be a bug.

**Comment by bluefuton** [comment]
@blowery now targeting the scroll at the wrapper. On demand scrolling from the comments button on full post works, but the position on load is still way out. Anything else we can try?

**Comment by blowery** [comment]
We could check the scroll position against the desired position when the scroll ends and do a quick window.scrollTo to get us into the new final position...

**Comment by blowery** [comment]
rebased this on top of the fixed RP placeholders. Works ... pretty well now? Probably good enough to merge. 

Comment placeholders would make it even better. But maybe a new PR for that. It's pretty involved to get in.

**Comment by jancavan** [comment]
In this example: http://calypso.dev:3000/read/blogs/99845261/posts/6802, it scrolls nicely for me if I append `#comments` to the link.

But if I load up http://calypso.dev:3000/read/blogs/99845261/posts/6802#comments directly, it doesn't scroll at all. Behaves the same way in Chrome and FF.

In Safari, loading up the link directly sometimes works, but most of the time it only scrolls to the topmost portion of it and shows the rest of the content above it:

screenshot 2016-10-03 12 40 35

**Comment by jancavan** [comment]
It still shows the rest of the content above Comments, but I don't think it's a blocker for today's planned launch:

screenshot 2016-10-03 13 35 59

**Pull request merged**
