### PR TITLE
Revert "Async load gridicons (#27158)"

### PR DESCRIPTION
**Pull request by blowery**
Reverts #27158 

cc @flootr

### CODE REVIEW

**Comment by alisterscott** [comment]
Looks good to me

screen shot 2018-10-01 at 12 31 02 pm

**Comment by blowery** [comment]
Unsure _why_ it broke so far...

**Comment by blowery** [comment]
busted because the editor is using `ReactDomServer.renderToStaticMarkup` to render those icons...

https://github.com/Automattic/wp-calypso/blob/master/client/components/tinymce/plugins/media/plugin.jsx#L455

**Comment by blowery** [comment]
Possible solution: switch those usages to use explicit imports of the gridicons in question.

**Pull request merged**
