### PR TITLE
Untangling: apply new design to Settings -> Administration -> Reset your site

### PR DESCRIPTION
**Pull request by fushar**
Fixes https://github.com/Automattic/dotcom-forge/issues/9861

## Proposed Changes

This PR applies the global design layout to the "Reset your site" flow:

image

image

image

> [!NOTE]  
> Highlights information that users should take into account, even when skimming.

This also updates the layout in production, i.e. when the flag is not enabled yet. I **think** it's fine, because the flow is isolated so overall it's still consistent on its own. I don't think it is worth it to further complicate the code to retain the old layout...

## Why are these changes being made?

pbxlJb-6ye-p2

## Testing Instructions

1. Go to `/sites`
2. Click a site
3. Go to Settings -> Administration
4. Click `Reset your site` button
5. Verify that you can complete the flow.
6. Regression: go to `/settings/general/:slug`, click Reset your site, at the bottom, and verify you can still complete the flow.

## Pre-merge Checklist

- [x] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [x] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [x] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [x] Have you checked for TypeScript, React or other console errors?
- [x] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [x] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [x] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Review by taipeicoder — APPROVED** [review]
LGTM 👍 
Some layout issues on small screens:

Screenshot 2024-11-19 at 12 15 20 PM

Screenshot 2024-11-19 at 12 15 31 PM

Also, if the site is Classic view, we still redirect them to Calypso pages. For instance:

Screenshot 2024-11-19 at 12 14 45 PM

Same for the links to posts, pages, etc. We can create an issue for this and follow it up.

**Comment by fushar** [comment]
> Also, if the site is Classic view, we still redirect them to Calypso pages.

I noticed that too, but it's existing behavior. The more I work on these pages, the more I discovered unmaintained "broken" links 😭

**Comment by fushar** [comment]
> Some layout issues on small screens:

Thanks for catching them, fixed & merging...

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/17008434

Some locales (Hebrew, Japanese) have been temporarily machine-translated due to translator availability. All other translations are usually ready within a few days. Untranslated and machine-translated strings will be sent for translation next Monday and are expected to be completed by the following Friday.

Thank you @fushar for including a screenshot in the description! This is really helpful for our translators.

**Comment by fushar** [comment]
> Also, if the site is Classic view, we still redirect them to Calypso pages. For instance:
> Same for the links to posts, pages, etc. We can create an issue for this and follow it up.

Created:

- https://github.com/Automattic/wp-calypso/issues/96531

**Review by Aurorum — COMMENTED** [review]
Hi all, just wanted to check whether it was intentional not to feature-flag this change. I've just happened to stumble across the Site Reset and Delete Site pages, and it feels very out-of-place on production right now.

Screenshot 2024-11-23 at 13 42 36

The card doesn't have sufficient width, and the button collapses onto the next line when I enter my site address. Wonder if that's a bug worth fixing? Thanks!

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/17008434).

**Comment by fushar** [comment]
@Aurorum Thanks for noticing, it's fixed here: https://github.com/Automattic/wp-calypso/pull/96711. Now the content is horizontally centered (as it was before the regression).

**Pull request merged**
