### PR TITLE
Reader: Fix excerpt cut off in More on wpcom

### PR DESCRIPTION
**Pull request by jancavan**
**Before (with image):**
screenshot 2016-09-29 11 44 59

**Before (text only):**
screenshot 2016-09-29 11 45 47

**After (with image):**
screenshot 2016-09-29 11 46 09

**After (text only):**
screenshot 2016-09-29 11 46 30

### CODE REVIEW

**Comment by fraying** [comment]
Goof catch! LGTM

**Comment by bluefuton** [comment]
@jancavan do you have an example of a post where this was broken originally? I've compared a few but they're all working on wpcalypso too.

**Comment by jancavan** [comment]
@bluefuton Only happens in "More on wpcom", between `661px` and around 690ish:

https://wordpress.com/read/feeds/12098/posts/1171071585
https://wordpress.com/read/blogs/91184769/posts/462

**Comment by samouri** [comment]
@jancavan, what do you mean when you say: 
> between `661px` and 690ish?

I wasn't able to repro :'(

**Comment by bluefuton** [comment]
Yep! Got a repro:

screen shot 2016-09-29 at 15 22 37

**Comment by bluefuton** [comment]
And is fixed in this branch. Great :)

**Pull request merged**
