### PR TITLE
Domains Management i1: Contact button opens form which can start bulk domain update

### PR DESCRIPTION
**Pull request by p-jackson**
Related to https://github.com/Automattic/dotcom-forge/issues/3433

## Proposed Changes

* Adds "Edit contact information" button to bulk actions toolbar
* Clicking button opens a contact details form with selected domains passed as query params
* The list of selected domains appears on the form so the user can remember what they're doing
* Submitting the form kicks off a bulk action
* After submitting the form the user is taken back to the domains table
* Refresh whois data when viewing domain contact details to ensure it reflects changes made by async jobs

The new page (defined in `bulk-edit-contact-info-page.tsx`) is mostly copy/pasted from `edit-contact-info-page/index.tsx`. I think   the copy/paste is appropriate because there are many parts of this page where we will want to slightly diverge from the existing contact form page I think. The actual form component itself (`<EditContactInfoFormCard>`) is shared, which is good.

I decided to pass the selected domains as an array query param. I'm not sure whether this is the best approach or not. Another idea was for the contact form to be more like a modal and not change the path, that way the selected domains would just be passed as a prop to the modal. But I decided against this because we want `<DomainsTable>` to be portable, and if someone embeds the domains table in some non-Calypso location then clicking the "Edit" button should navigate them into Calypso and they should be navigated back to their table again when done.

Things intentionally left out of this PR:
- Transfer lock toggle doesn't appear in the form when it should
- I believe we're missing some terms and conditions which sometimes appear at the bottom of the form
- Only works for the all-domains version of the table
- The "Apply contact update to My Account email" checkbox doesn't do anything and should probably be removed
- There's no breadcrumb at the top of the form page as shown in the mockups
- Different jurisdictions have different contact detail requirements. We should only be allowing bulk updates when all domains have compatible requirements. We're ignoring that for now

CleanShot 2023-09-06 at 18 26 16@2x

CleanShot 2023-09-06 at 18 24 40@2x

## Testing Instructions

- Make sure that either your sandbox has the latest code or you're not sandboxed
- `/domains/manage?flags=domains/management`
- Select domain(s)
- Click the "Edit contact information" button that appears
- Click
- The selected domains appear in the form sidebar
- Clicking cancel goes back to the domains table
- Clicking submit starts the bulk action and goes back to the domains table
- Check the domain(s) you updated, and you should see a `Spinner` saying there is an update pending 
- Next, log on to your sandbox and run `cat /tmp/php-errors` and run the command there `async-jobs/tester.php 87347463346 wpj_`
- On the front end, confirm you see a `Notice` saying the update was completed. Check the domain(s) you updated and the `Spinner` should have gone.

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

**Comment by p-jackson** [comment]
@JanaMW27 This is the form for bulk updating contact details. I'm putting a list of which domains were selected in the sidebar as a reminder/confidence booster for the user. What do you think about this?

image

**Comment by JanaMW27** [comment]
> @JanaMW27 This is the form for bulk updating contact details. I'm putting a list of which domains were selected in the sidebar as a reminder/confidence booster for the user. What do you think about this?
> 
> image

I like the concept of adding the list of emails that they are editing, but I would move it above the information section and have a limit of XX amount of domains (I would say 5-6) and a click to uncollapse the full list (if the user is editing more than 5-6 domains.

NEW

What do you think?

**Comment by zaguiini** [comment]
It would be good if we could add "Edit contact information" as a 3-dot action, so the user doesn't necessarily need to click the bulk action checkbox.

Apart from Jana's recommendation, I think the UI is in a good state.

**Comment by zaguiini** [comment]
The UI is good, but ticking a row and editing the contact information yields no effect. 🤔 I'm not sandboxed. I see the job being dispatched, but I don't see the bulk actions UI showing up saying that it's updating, and even after a few minutes, I didn't see any change.

In contrast, when editing a domain directly, I immediately see the address updated. Why is that? Are we just adding the contact form and not applying the changes?

**Comment by p-jackson** [comment]
> I don't see the bulk actions UI showing up saying that it's updating

This is PR was created before the UI which showed progress. That code will need to be rebased in.

> In contrast, when editing a domain directly, I immediately see the address updated. Why is that? Are we just adding the contact form and not applying the changes?

Oooh! Yes I think there's some caching we need to address. The old views are pulling their data from the redux store, which assumes that any edits to the contact details will have been made through the redux store as well. We need to invalidate the data in the redux store somehow.

**Comment by mpkelly** [comment]
I've just been taking a look at this. There is a problem on the backend when the async job runs. Since my refactoring, the update no longer works because I missed a step to convert the `whois` data into the internal format. I have fixed that here: D120935-code

**Comment by p-jackson** [comment]
> There is a problem on the backend when the async job runs. Since my refactoring, the update no longer works because I missed a step to convert the whois data into the internal format

@mpkelly If that change isn't enough to address the issue then I've also got this proposed change in the wings too, which refreshes the contact information every time the user looks at the whois data. Just in case an async job has made changes to whois data that redux isn't aware of.

https://github.com/Automattic/wp-calypso/pull/81499

**Comment by p-jackson** [comment]
Thanks @JanaMW27 I like your suggestions. I've moved the domain list to the top and only show the first 5 domains by default.

**Comment by p-jackson** [comment]
@mpkelly I've merged in #81499 to ensure the contact details UI reflects any changes made by async jobs. Do you think this PR is ready to go?

**Comment by mpkelly** [comment]
> @mpkelly I've merged in #81499 to ensure the contact details UI reflects any changes made by async jobs. Do you think this PR is ready to go?

@p-jackson, yeah, fine by me.

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/8929119

Thank you @p-jackson for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/8929119).

**Pull request merged**
