### PR TITLE
update Newspack Blocks to v1.74.1

### PR DESCRIPTION
**Pull request by dkoo**
## Proposed Changes

* Updates Newspack Blocks code in Editing Toolkit to [v1.74.1](https://github.com/Automattic/newspack-blocks/releases/tag/v1.74.1).

## Testing Instructions

* Test the Blog Posts and Posts Carousel blocks. No functional changes or fixes in this change.

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

**Review by lupus2k — APPROVED** [review]
All looks good, failing `newspack-blocks` tests will be fixed after deploy it (p1695155498788779/1695153083.471169-slack-CKZHG0QCR)

**Comment by dkoo** [comment]
@lupus2k if the changes look and test well to you, could you merge this for me? I don't have permissions to bypass the failing tests.

**Comment by lupus2k** [comment]
> @lupus2k if the changes look and test well to you, could you merge this for me? I don't have permissions to bypass the failing tests.

Sorry, I missed the `Unit Test` failed test; I'm looking into it.

**Comment by lupus2k** [comment]
@dkoo, I just committed an update. Let's wait for tests to pass

**Comment by dkoo** [comment]
Thanks for your help, @lupus2k!

**Pull request merged**
