### PR TITLE
Editor: Remove editor code in client/post-editor

### PR DESCRIPTION
**Pull request by allilevine**
#### Changes proposed in this Pull Request

Removes all unused files and components from the client/post-editor directory.
- Addresses "Editor code in client/post-editor (though will need to move any components, state, etc that are needed elsewhere in Calypso)" task in #41106 
- Moving any code needed elsewhere will be addressed in #46367

#### Testing instructions

* [ ] There are no errors when editing posts and pages.
* [ ] Calypso loads and builds successfully.

Test that remaining `post-editor` components are still functioning correctly:
- [ ] The [document title](https://github.com/automattic/wp-calypso/pull/39905) loads correctly in Gutenframe (e.g. when editing a post it's "Edit Post" instead of the title of the page before, like Posts).
- [ ] The Revisions dialog (div with class "editor-revisions__dialog") [loads correctly](https://wordpress.com/support/editors/page-post-revisions/#viewing-revisions) in Gutenframe.
- [ ] On /posts, clicking the three dots next to a public post and then "Share" opens a panel to share or publicize that post.
- [ ] In Site Settings > Writing > Podcasting > Set up you can add hierarchical podcast categories.
    - [ ] You can choose a podcast cover image and see a preview.
- [ ] In Site Settings > General you can set a site icon.

### CODE REVIEW

**Review by wp-desktop — DISMISSED** [review]
WordPress Desktop CI Failure for job "wp-desktop-mac".

@allilevine please inspect this job's build steps for breaking changes at [this link](https://circleci.com/gh/Automattic/wp-calypso/927575). For temporal failures, you may try to "Rerun Workflow from Failed".

Please also ensure this branch is rebased off latest Calypso.

**Comment by retrofox** [comment]
### My tests

* [x] There are no errors when editing posts and pages.
* [x] Calypso loads and builds successfully.

Test that remaining `post-editor` components are still functioning correctly:
- [x] The [document title](https://github.com/automattic/wp-calypso/pull/39905) loads correctly in Gutenframe (e.g. when editing a post it's "Edit Post" instead of the title of the page before, like Posts).




- [x] The Revisions dialog (div with class "editor-revisions__dialog") [loads correctly](https://wordpress.com/support/editors/page-post-revisions/#viewing-revisions) in Gutenframe.



- [x] On /posts, clicking the three dots next to a public post and then "Share" opens a panel to share or publicize that post.


- [x] In Site Settings > Writing > Podcasting > Set up you can add hierarchical podcast categories.


    - [x] You can choose a podcast cover image and see a preview.


- [x] In Site Settings > General you can set a site icon.

**Review by retrofox — APPROVED** [review]
I've tested the PR and couldn't find any issue in the process. LGTM. Another pair of 👀 won't hurt. :-D

**Comment by allilevine** [comment]
@kwight 👋 Can you take a look at this one and see if we've missed any potential issues? Thank you!

**Comment by pablinos** [comment]
I've tested this on a simple site and all was fine. I also tested it with a Jetpack site, and everything works apart from the podcast settings, which aren't available for Jetpack sites.

**Review by mmtr — APPROVED** [review]
LGTM :shipit: 

Screen Shot 2020-10-22 at 17 28 21


Nice ratio! 🎉

**Comment by tyxla** [comment]
Follow-up and more unused code removal in #47095, could use an eye or two if you folks have a chance.

**Pull request merged**
