### PR TITLE
Stats: Replace Yoast SEO promo with Jetpack mobile app promo

### PR DESCRIPTION
**Pull request by a8ck3n**
#### Proposed Changes

Adds the Jetpack mobile app promo and removes the Yoast SEO one.

Before:

APromoSEO

After:

APromoJetpackMobileApp

Currently just updating the Stats page. The designs call for the same promo card on the Insights and Ads pages but it looks overpowering there with the older page layout. I'm thinking we should wait until we "grid" those layouts before adding this component in.

#### Testing Instructions

1. Visit the Calypso Live link.
2. Visit the Stats page.
3. Scroll down and confirm the new promo card is present.
4. Confirm it matches screenshot.
5. Confirm it behaves appropriately on smaller screen sizes.

#### Pre-merge Checklist

- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

Related to #69230. Depends on #70058.

### CODE REVIEW

**Review by wilmersondasilva — APPROVED** [review]
LGTM!

**Comment by jsnmoon** [comment]
@keoshi & @jeffgolenski: Is there anyone we need to notify before deploying this change?

**Comment by keoshi** [comment]
@jsnmoon Thanks for the ping — we should definitely find out who's behind the original banner and inquire them on clickthrough/conversion data they might have on this before removing the banner.

From a quick git blame I found the original PR https://github.com/Automattic/wp-calypso/pull/65763 and seems like we should ping @Automattic/wpcom-marketplace for their thoughts. If Jeff doesn't get to this today, I'll do it tomorrow morning.

**Comment by jeffgolenski** [comment]
I haven't gotten into digging into the data on this yet @keoshi but @a8ck3n don't merge this just yet (sorry). I want to ensure we're not removing any upsells that drive revenue. 

Filipe, rather than replacing this Yoast banner with the mobile one. What do you say to implementing them both in the larger carousel pattern we suggested for the empty states? This way we're not regressing any potential revenue markers and we're scaling properly...

Screen Shot 2022-11-17 at 6 56 18 PM

This way we can fit both without utilizing too much real estate. We can also possibly allow folks to actively dismiss if they don't want it. I hate the idea of showing prominent CTAs if customers actively don't want them / already have them.

We're already going to display the mobile banner on multiple pages and there's also a mobile prompt that displays for mobile browsers... seems overkill. cc @jsnmoon

**Comment by keoshi** [comment]
@jeffgolenski Love that solution. We could keep Yoast visible as the first item for users that do see it and add the JP mobile app banner as the second one.

@a8ck3n How feasible is the above considering we'd reuse the [`DotPager` component](https://wpcalypso.wordpress.com/devdocs/design/dot-pager)?

**Comment by cpapazoglou** [comment]
Thanks for the ping! This Yoast promo banner has 140 clicks daily. Not a huge amount, but as you already mentioned, it seems better having a paginated promo banners block as we do in `/home`

**Comment by a8ck3n** [comment]
> How feasible is the above considering we'd reuse the [`DotPager` component](https://wpcalypso.wordpress.com/devdocs/design/dot-pager)?

Looks entirely feasible! I'll spin up a PR for this today. Or rather, I'll update this PR with the necessary changes!

**Comment by a8ck3n** [comment]
Closing this in favour of #70272.

**Pull request closed without merging**
