### PR TITLE
ci(build): Drop fallback build

### PR DESCRIPTION
**Pull request by scinos**
#### Background

See #53222
To be merged _after_ #55775 and #56029

#### Changes proposed in this Pull Request

* Drop scripts used to build the fallback build. Now only the evergreen build can be built.

#### Testing instructions

Checkout this branch and verify the usual commands in your devflow still work (`yarn start`, `yarn build`... )

### CODE REVIEW

**Review by noahtallen — APPROVED** [review]
If I'm reading this right, was the desktop previously building the fallback? I'm curious why that was, and why it's ok to change that now 🤔 

Other than that question, this looks good to me and tests well!

**Comment by scinos** [comment]
> If I'm reading this right, was the desktop previously building the fallback? I'm curious why that was

I don't know to be honest. @jsnajdr may know?

> and why it's ok to change that now 🤔

I think it is, as WP Desktop doesn't embed the app anymore, they just load wordpress.com

**Comment by jsnajdr** [comment]
> If I'm reading this right, was the desktop previously building the fallback?

It's because the desktop app was using a very old version of Electron not so long ago, before @nsakaimbo started taking care of that. And these old versions of Chrome and Node.js didn't support the latest syntax.

**Comment by noahtallen** [comment]
> If I'm reading this right, was the desktop previously building the fallback? I'm curious why that was

Another follow-up on this one. The desktop app was still using the fallback build of Calypso until #55404.

**Comment by scinos** [comment]
NOT READY TO MERGE

Until #56029 is done. We are still serving the `fallback` build

**Review by noahtallen — APPROVED** [review]

**Review by fullofcaffeine — APPROVED** [review]

**Pull request merged**
