### PR TITLE
Bootstrap localization for #5475

### PR DESCRIPTION
**Pull request by coreh**
This adds the code for bootstrapping localization for #5475. The classes are not actually instantiated, but are included so that the translation tools pick up the strings.

### CODE REVIEW

**Comment by bisko** [comment]
LGTM 👍

**Comment by aduth** [comment]
Can you point me to some resources on what these files are for; specifically, why are this duplication needed?

**Comment by coreh** [comment]
These are needed for [GlotPress](http://translate.wordpress.com/) to pick up the new strings, so that by the time we merge #5475, the new content will already be translated into the “magnificent 16” (The 16 languages we provide first-party support to.) It usually takes 2 weeks or so for the new strings to be translated, which is why we haven't merged that one yet. Once we do, I'll also include the deletion of this files as part of the Pull Request.

Normally we'd either have all the strings be in English while we wait for translations (even for the users who set their interface language to something else) or we'd put this behind a feature gate and enable it only for english users. Since this is part of NUX (New-user experience), and we're trying to make that as consistent and polished as possible, after talking to the i18n Team we decided to take this approach instead of the feature gate or the untranslated strings.

**Comment by aduth** [comment]
@coreh : In the cases where we really want to have strings already translated by the time they're pushed live, I wonder if we should just add them (again, temporarily) to the hard-coded list of strings here:

https://github.com/Automattic/wp-calypso/blob/bebfa4a/server/i18n/index.js#L104-L154

**Comment by coreh** [comment]
Oh nice, didn't know about that. Yeah that might be a better approach. Do you want me to migrate these there, and remove this file?

**Comment by aduth** [comment]
I don't anticipate that the files here will be updated in the next couple weeks, so it may not be an urgent issue to migrate them now, but probably a good idea to consider for subsequent changes, since it becomes a maintainability problem when we have duplicate versions of the same component.

**Comment by coreh** [comment]
Agreed, this would make merging changes kinda suck. From now on I'll use `/server/i18n`.

**Comment by aduth** [comment]
( /cc @rralian in case you have any other thoughts on manually adding i18n strings )

**Comment by rralian** [comment]
Yeah, I think that's a better approach than duplicating components. If we do this, I think it would be better to implement in such a way that the strings are not mixed together. The ones in `/server/i18n/index.js` are there for the purpose of priming the moment.js strings. This would be a different purpose, so it would be nice to break it out somehow.

**Pull request merged**
