### PR TITLE
External media sources: allow sources to not have date grouping

### PR DESCRIPTION
**Pull request by notnownikki**
To support the coming `pexels` data source, which does not have any
date data, this changes allows us to disable date grouping and
ordering for individual media sources. We need to do this because
the existing behaviour groups by date, then orders by ID, but
for a stock image service like Pexels, we need to consume the
data in the order it gets delivered to us, because Pexels sorts
the data itself.

If we disable date grouping and ordering for a source, the
group label will be empty. This change also stops labels
rendering if the label is empty, so we don't have redundant
grey lines when there is no grouping.

Testing:

The media library should work exactly as it did before.
If you want to see how it looks with no ordering or date grouping, you
can add `google_photos` to `sourcesWithoutDate` and `ungroupedSources`,
or take a look at this handy screenshot of it in action on the add/stock-image-search
branch!

nogrouping

### CODE REVIEW

**Comment by johngodley** [comment]
Tested with existing media sources and they continue to show the grid labels. Tested with `google_photos` added to the ungrouped sources and it doesn't show the grid labels - all looks good 👍 

Regarding the change to `sorted-grid/index.jsx` the `'' !== labelText &&` check in `renderLabels` stands out a bit.

Will there ever be an instance where we want a mixture of some labels and some not labels? If there is then maybe the rendering of the item could be moved into a `renderLabelItem` to keep the `map` a bit cleaner.

If there won't be an instance of a mixed label/non-label then is it possible to skip rendering the labels?

I'll add that I don't know how the component works so this may or may not be applicable.

I think it's ok to include pexels in the different exclusion lists, and having something there means that you can add unit tests. The change in `media/list-store.js` is something that could probably be covered by some tests, as could `client/my-sites/media-library/list.jsx`

**Comment by notnownikki** [comment]
The situation I was thinking of is where we might have paid-for images from a stock image service, which would use the label, while the regular free images wouldn't.

I'll add 'pexels' to the list and add a unit test.

**Comment by johngodley** [comment]
> The situation I was thinking of is where we might have paid-for images from a stock image service, which would use the label, while the regular free images wouldn't.

Ah, ok. I think it still looks a bit awkward having the comparison inside the `map`. Maybe they could be removed with `filter` first, or the comparison and rendering pushed to another function? Might be personal preference!

👍 on the unit tests. Hopefully without sounding like a unit test nag, could the `list-store` change could be covered too?

**Comment by notnownikki** [comment]
Sure, will add that test.

**Comment by notnownikki** [comment]
Ok, test added!

I'd rather keep the `'' !==` comparison inside the map, I'm just thinking that we might want to highlight certain images are being paid-for, so it would be easier to do it that way. Right now, we just don't return anything, but it's not impossible that it could turn into a case in a switch statement, or another lookup.

**Comment by johngodley** [comment]
> but it's not impossible that it could turn into a case in a switch statement, or another lookup

Yeah, if it's outside of the map it will be easier to compose and test things like that. I know that functionally nothing will change so 🚀 from me.

**Pull request merged**
