### PR TITLE
Improve the routing of Comments-based URLs.

### PR DESCRIPTION
**Pull request by kwight**
Continuation of #15848 , which was erroneously rebased.

**Testing**
Go to each of the following URLs and be sure you end up in the right place, with no interrupted rendering (component starts re-rendering, then a full page reload kicks in from a redirect).

|URL|Site Selector|Redirect/Destination|
|-----|:-----:|------|
|/comments | :white_check_mark: | /comments/pending/**domain**|
|/comments/**domain** || /comments/pending/**domain**|
|/comments/**status** | :white_check_mark: | /comments/**status**/**domain**|
|/comments/asdfasdf || /comments|
|/comments/**status**/asdfasdf   | :white_check_mark: | /comments/**status**/**domain**|
|/comments/asdfasdf/**domain** || /comments/pending/**domain**|
|/comments/asdfasdf/asdfasdf || /comments/pending|

### CODE REVIEW

**Comment by kwight** [comment]
Hm, I've managed to make this worse somehow; full page reloads are now triggered by changing status, which is a regression that I wasn't seeing before, but they don't seem to be caused by the redirect code in the PR. Will need to dig deeper.

**Comment by dmsnell** [comment]
@kwight could you maybe pause and help explain more exactly what problem this is solving and how exactly the PR "improves" routing? Especially in cases where we get confused by the results I like to check our assumptions against the initial problem statement and I'm not sure I gathered this from the PR description or the linked PR's description or how exactly it relates to the linked issue in the linked PR.

**Comment by kwight** [comment]
By "improves", I mean, properly covers all cases of valid and invalid URLs, as shown in the #15848 description:

|URL|Site Selector|Redirect/Destination|
|-----|:-----:|------|
|/comments | :white_check_mark: | /comments/pending/**domain**|
|/comments/**domain** || /comments/pending/**domain**|
|/comments/**status** | :white_check_mark: | /comments/**status**/**domain**|
|/comments/asdfasdf || /comments|
|/comments/**status**/asdfasdf   | :white_check_mark: | /comments/**status**/**domain**|
|/comments/asdfasdf/**domain** || /comments/pending/**domain**|
|/comments/asdfasdf/asdfasdf || /comments/pending|

Currently, an invalid status and/or site will produce a variety of errors and issues:

screen shot 2017-07-10 at 9 50 55 am
screen shot 2017-07-10 at 9 53 07 am
screen shot 2017-07-10 at 9 55 28 am
screen shot 2017-07-10 at 9 57 27 am

Fixing handling of a URL with an invalid site appended (`https://wpcalypso.wordpress.com/comments/undefined`) would have fixed the original issue reported in #15584; however that `undefined` getting added to the redirect no longer happens (I _did_ confirm it at the time), so that issue can be closed.

**Comment by kwight** [comment]
OK, got this fixed up with all expected behaviour, cleaner code, and no rendering-before-redirecting weirdness.

**Comment by dmsnell** [comment]
I'm still a bit confused at how lenient we are being here. _What_ is sending our customers to the wrong URLs? 

Also, I think we have a grand plan for a future where we will have an all-sites view, so is it premature to take that URL now?

**Comment by kwight** [comment]
While I don't know of any actual problematic links anywhere, as we saw with the (temporary) login issue, we never know when or how users end up at invalid URLs. Whether by an error on our own, or a user typo (or third-party link somewhere), as long as these variations are covered, users will end up somewhere useful (and not with broken or blank screens).

Also, I think we have a grand plan for a future where we will have an all-sites view, so is it premature to take that URL now?

The all-sites view (`/comments`) behaviour remains unchanged in this PR: a site selector will be presented, and the user is sent to `/comments/pending/(site)`.

**Comment by dmsnell** [comment]
> as long as these variations are covered, users will end up somewhere useful (and not with broken or blank screens).

my only concern is this and people repeating those links then being surprised when for some odd reason they don't work. like, better to send them to a generic comments 404 page or something and give them the chance to go to the right link - or us developers deploying the wrong link because it happens to work with this

> The all-sites view (/comments) behaviour remains unchanged in this PR: a site selector will be presented, and the user is sent to /comments/pending/(site).

I was looking specifically at `/comments/status/asdfasdf > /comments/status/domain` - it looked like it was changing the all-sites view to a domain-specific view

---

thanks for having the patience to walk me through this @kwight, by the way.

**Comment by gwwar** [comment]
👍 Nice work on getting rid of the double redirect. Almost all cases behave as expected except for `/comments/status/asdfasdf` for that case I'm seeing:

screen shot 2017-07-10 at 3 40 05 pm

**Comment by kwight** [comment]
@gwwar Oops! Well spotted – that should be fixed by e592cce.

**Comment by kwight** [comment]
> like, better to send them to a generic comments 404 page or something and give them the chance to go to the right link - or us developers deploying the wrong link because it happens to work with this

Hm, we could certainly do that too. Is that something you see as negating this PR, or something to consider on top of this PR?

> I was looking specifically at /comments/status/asdfasdf > /comments/status/domain - it looked like it was changing the all-sites view to a domain-specific view

Ah, yes, correct – again, handling what I thought of as an error since we don't have an all-sites view.

**Comment by dmsnell** [comment]
> Hm, we could certainly do that too. Is that something you see as negating this PR, or something to consider on top of this PR?

something to work in harmony with it. we recently had a problematic event if I remember where we _should_ have returned a 404 but didn't. I don't even know if it's easy to do so. Anyway, maybe @scruffian or @ockham or @ehg might remember: my memory is fuzzy

**Comment by ockham** [comment]
Actual 404ing isn't super-easy since it's a server-side only thing. Here's the [doc](https://github.com/Automattic/wp-calypso/blob/master/docs/isomorphic-routing.md#error-handling).

**Pull request merged**
