### PR TITLE
Help: Scroll to Top of the Page on Loading

### LINKED ISSUE #51912: Support: /help loads at random position when visited from Home Screen
### Steps to reproduce the behavior

1. Go to home screen
2. Click on More help
3. Support screen does not load at top of screen but in random position

#### What I expected to happen

New screen would load at top of screen.

### PR DESCRIPTION
**Pull request by Aurorum**
#### Changes proposed in this Pull Request

* Scroll to the top of the page when loading the Help section 

#### Testing instructions

* Visit the Customer Home
* Scroll down
* Click "More help" under the "Get Help" card
* Verify that when going to the Help section, the top of the page appears 

Screenshot 2021-04-13 at 21 20 46

cc @sixhours 

Fixes #51912

### CODE REVIEW

**Comment by obenland** [comment]
Do you know why it loads in the middle of the page at all?

**Comment by Aurorum** [comment]
I think it just takes the position from the previous page, but I couldn't discover why. I think it's something more broad than just the `HelpComponent` though since this happens for the `ContactComponent` too.

**Comment by sixhours** [comment]
👋 Happy Friday @Aurorum ! Is this still an issue now that you've changed the link to the Help section from My Home? I'm not seeing it on production, wondering if we should put this aside.

**Comment by Aurorum** [comment]
Hi! I think this is still an issue because `/help` is probably one of the most common links used in Calypso. Even though Customer Home was the most prevalent place it was used, this issue would still occur in other places where the link is used without this change, especially on smaller screens.

For example:


https://user-images.githubusercontent.com/43215253/118354656-fd3daf00-b563-11eb-86f1-773aec0e6c44.mov

**Comment by sixhours** [comment]
@Aurorum Aha, I see what you mean. I agree w/ Konstantin that it would be good to figure out why it's loading that way in the first place, but I think this is a solid temporary fix.

**Review by sixhours — APPROVED** [review]

**Pull request merged**
