### PR TITLE
Themes Showcase: Removed theme options from "InstallThemeButton"

### PR DESCRIPTION
**Pull request by DanielSmithMichigan**
#### Testing Instructions Simple

1. Open the /themes page on a simple site
2. Click the "Install theme" button
3. You should be brought to https://wordpress.com/themes/upload/SITE_SLUG

#### Testing Instructions Atomic

1. Open the /themes page on an atomic site
2. Click the "Install theme" button
3. You should be brought to the wp-admin version of the themes page for your site

Both of these should have created a tracks event: calypso_click_theme_upload.

### CODE REVIEW

**Comment by kwight** [comment]
@andres-blanco Do you know what this PR is for? I don't see any change in behaviour from prod, and it looks to maybe just be a clean-up PR – but there's no attached issue, nor anything I can see on our board. It _works_, just curious if you know any more background.

**Comment by andres-blanco** [comment]
@kwight Nope, this is the first time I see this. It seems to just be removing the `theme-options` dependency but I don't know why.

**Comment by kwight** [comment]
@andres-blanco OK, cool – can you give a final test yourself then, and go ahead and merge!

**Review by kwight — APPROVED** [review]
Looks to be cleanup, and I can't find anything that breaks.

**Comment by andres-blanco** [comment]
Everything works as expected on my side too. Merging

**Pull request merged**
