### PR TITLE
Reader Caterpillars: Show All Comments Button

### PR DESCRIPTION
**Pull request by samouri**
Implement Show All button as described in: https://github.com/Automattic/wp-calypso/issues/17663

### CODE REVIEW

**Comment by samouri** [comment]
I've modified the comment expansion to make it `full` instead of `excerpt`

**Comment by bluefuton** [comment]
Works great! 

In one case I did end up with an empty caterpillar after expanding with 'Show all', though:

screen shot 2017-09-05 at 18 44 41

**Comment by samouri** [comment]
@bluefuton: that falls into the bucket of not supporting pagination.  just confirmed it happens w/ any post with 50+ comments

**Comment by samouri** [comment]
found an edge case with show all where if the author names are too long it scrunches the show all button

I'd prefer we merge this as-is so its easier to iterate on styling + functionality separately

**Comment by bluefuton** [comment]
> I'd prefer we merge this as-is so its easier to iterate on styling + functionality separately

Go for it! 🚢

**Pull request merged**
