### PR TITLE
Fix: Allow atomic sites running on the latest infrastructure to be upgraded to the eCommerce plan.

### PR DESCRIPTION
**Pull request by southp**
#### Changes proposed in this Pull Request

This PR attempts to resolve the issue that an atomic v2 site can't be upgraded to the eCommerce plan. The reason is that `isAutomatedTransfer()` returns the same for both the v1 sites and the v2 sites, hence making `canUpgradeToPlan()` return `false` for the both.

With code-D27313 exposes `is_wpcom_atomic` data for indicating the v2 sites, this PR implements a new selector, `isSiteWpcomAtomic()` and update `canUpgradeToPlan()` accordingly to fix the issue.

#### Dependency
code-D27313

##### Unit test
1. `npm run test-client is-site-wpcom-atomic can-upgrade-to-plan` should pass.

##### e2e test
1. Apply D27313
1. Choose an atomic v2 site and go to http://calypso.localhost:3000/plans/. You should be able to upgrade to the eCommerce plan from there.
1. Choose an atomic v1 site and go to http://calypso.localhost:3000/plans/. You should not be able to upgrade to the eCommerce plan as always.

### CODE REVIEW

**Comment by dzver** [comment]
This raises a question about the active_promotions endpoint currently used to determine if a site should or should not see the eCommerce. I'll personally be very happy to wipe the active_promotions call.

**Comment by dzver** [comment]
I logged in as an Atomic v2 user and went to the plans page with calypso.localhost with the backend patch applied. Here is what I saw:

Screenshot 2019-04-24 at 16 08 04

I expected to see a button allowing me to upgrade. Did I understand what the changes do? DM me for details.

**Comment by southp** [comment]
Hmm, weird. I can see the button. For a newly transferred site it would need one refresh to fetch the updated site infor, though. I'll ping you for more details 🙇🏻

**Comment by southp** [comment]
The depended backend patch has been fixed. It should work fine now.

**Pull request merged**
