### PR TITLE
AT: track initiate transfer

### PR DESCRIPTION
**Pull request by jhnstn**
This adds an event to track automated transfer initialization under the event name `calypso_automated_transfer_initiate_transfer`

It also adds a `context` event property to the other transfer process events:
- `calypso_automated_transfer_initiate_succes`
- `calypso_automated_transfer_initiate_failed`
- `calypso_automated_transfer_complete`

This property is set to either `plugins` or `themes`

**Testing**
- Enable tracks logging: `localStorage.setItem( 'debug', 'calypso.analytics.tracks' )`
- Visit a plugin page on a site that is eligible for automated transfer
- The event `calypso_automated_transfer_initiate_transfer` should fire after clicking install

The same steps can be repeated with a theme upload transfer flow

Also note that the initialization events should have a `context` event property with the correct context, `plugins` or `themes`

### CODE REVIEW

**Comment by lamosty** [comment]
I'm trying to test this but am not getting the event upon visiting a plugin page on an AT eligible site:

selection_159

Am I doing something wrong?

**Comment by lamosty** [comment]
I'm not getting the event upon clicking the Install button on a plugin page:

selection_160

**Comment by lamosty** [comment]
Oh, wait, I'm actually getting `calypso_automated_transfer_initiate_transfer` which is the correct event but according to your testing instructions, I should get `calypso_automated_transfer_initiate_request`. :)

**Comment by lamosty** [comment]
Working fine for me for both plugins and themes:

selection_161

LGTM :ship:

**Comment by jhnstn** [comment]
> I'm actually getting calypso_automated_transfer_initiate_transfer which is the correct event but according to your testing instructions, I should get calypso_automated_transfer_initiate_request. :)

yeah I changed the name of the event after opening up the PR but missed the reference in the testing instructions. I just updated the test description

**Pull request merged**
