### PR TITLE
Stats: Release horizontal bar chart modules

### LINKED ISSUE #69044: Stats: Add horizontal bar chart background for stats modules
Part of the modernization project (p1HpG7-igQ-p2). Perhaps we could do this using dynamic styling?

# Development
- [x] Create a horizontal bar chart data table component
(#69117 by @grzegorz-cp)
- [x] Integrate the new component in the Traffic page
  - #69545
  - #69726 
  - #69812 
  - #69841
  - #69915
- [x] Release to production

# Designs

Image

Image

Image

### PR DESCRIPTION
**Pull request by jsnmoon**
#### Proposed Changes

image

Enables the new horizontal bar lists for all stats modules in the Traffic page.

#### Testing Instructions

* Open the Calypso live branch for this PR.
* Navigate to the Traffic Stats page and ensure all the Stats modules include horizontal bar chart backgrounds.

#### Pre-merge Checklist

- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

Fixes #69044.

### CODE REVIEW

**Review by keoshi — APPROVED** [review]
This is cool and looking so slick! Ship it 🚢 

Noting two minor things but understand this PR simply removes enables the feature, so let me know if I should move these suggestions to follow-up issues.

- [x] Border-radius: in `.horizontal-bar-list .horizontal-bar-list-item-bar:before` the `border-radius` should be set to `2px` instead of `5px`.
- [x] Items with children: the cursor doesn't change to a pointer like it does for items with direct links. Ideally they should all use `cursor: pointer` to denote the intended interaction.

**Comment by jeffgolenski** [comment]
Magical. 🚢

**Review by jeffgolenski — APPROVED** [review]

**Comment by jsnmoon** [comment]
@keoshi: Both items have been addressed!

**Comment by jsnmoon** [comment]
This PR was reverted before deployment due to list item action buttons not being visible on hover:

Before:
image

After:
image

**Comment by jeffgolenski** [comment]
> This PR was reverted before deployment due to list item action buttons not being visible on hover:

That's strange. I was seeing them when I tested.

**Comment by jsnmoon** [comment]
@jeffgolenski: I believe the changes from https://github.com/Automattic/wp-calypso/pull/69907 created a regression with this feature 🙂

**Pull request merged**
