### PR TITLE
Stats: Cache Latest Post Summary

### PR DESCRIPTION
**Pull request by youknowriad**
This would resolve this issue https://github.com/Automattic/wp-calypso/issues/2487

## Current state 

Now, the latest post summary is displayed in the `my-sites/stats/post-performance`
1- It uses the `PostListStore` to get the last published post in order to get the comments count and the likes count
2- It also uses the `PostStatsStore` to get the views count
3- Then it renders the insight card with those informations

## Approach

1- A first step here would be to use the redux QueryPosts component to replace the PostListStore : https://github.com/Automattic/wp-calypso/pull/2350

2- Then we could implement the serialise/deserialize actions in the posts reducer (like described in the calypso data guide https://github.com/Automattic/wp-calypso/blob/master/docs/our-approach-to-data.md#solution-serialize-and-deserialize-actions), this would take care of caching the results. 
Here we will have two issues : how to invalidate this query cache ? and maybe we could have a special parameter in the action to choose if we want the current query to be cached or not (to avoid side effects in other components that doesn't want to cache the query results ?)

3- Replace the PostStatsStore by a redux actions/selectors/reducers approach with a StatsQuery Component. and use the serialize/deserialize actions to cache those stats.

What do you think about this approach ?

Thanks for the feedback.

### CODE REVIEW

**Comment by youknowriad** [comment]
ping @aduth @timmyc 

Can have some feedback about the proposed approach. Thanks a lot.
And maybe some one can add the `[Type] Trial Project` and `In progress` labels. Thanks :)

**Comment by aduth** [comment]
Hey @youknowriad 😄 

I think most of what you need with the posts Redux state should already be available (specifically, querying posts given a set of parameters and caching/retrieving the result). With regards to cache invalidation, there are a few things to note:
- The way we use [query components](https://github.com/Automattic/wp-calypso/blob/master/docs/our-approach-to-data.md#query-components) makes manual cache invalidation unnecessary in most cases. We leverage the React component lifecycle to trigger a new request as soon as the query component is mounted, or after its parameters changes. This way, we still have access to the persisted state, but in the background, a request is made to fetch the most up-to-date data. See #2618 for background and the [implementation of `<QueryPosts />`](https://github.com/Automattic/wp-calypso/blob/master/client/components/data/query-posts/index.jsx) for more information.
- The persisted state for the entire application is busted [a week after being saved](https://github.com/Automattic/wp-calypso/blob/3d2c01eda9e897f7732c1418da80ea40ac879a21/client/state/initial-state.js#L23). This is pretty basic and could be enhanced in the future to be a bit smarter.
- Cache invalidation _does_ become pretty troublesome as soon as you start considering updates to state data (see #4557 for some exploration of these issues)

I'm not intimately familiar with the purpose of `PostStatsStore`, but it would seem reasonable to me to track this in global state too. I'll defer to @timmyc in case he has more light to shed on the stats approach.

**Comment by timmyc** [comment]
Looks like a good plan to me.  Some background on [posts-stats-store](https://github.com/Automattic/wp-calypso/tree/master/client/lib/post-stats) - this flux component acts as an interface to the [stats/post/$id](https://developer.wordpress.com/docs/api/1.1/get/sites/%24site/stats/post/%24post_id/) endpoint.  It was originally developed with future support for other keys besides `totalViews` in mind, but was never utilized beyond that.

It is also what powers the views stat seen in the post listing https://wordpress.com/posts/my/mysite.wordpress.com

blog_posts_ _trout_bummin_ _wordpress_com

Migrating the `totalViews` into the redux tree would be a great approach.

**Comment by youknowriad** [comment]
I'll try to split this onto multiple small merge requests, here is the first one https://github.com/Automattic/wp-calypso/pull/5025. Feedback appreciated. Thanks

**Comment by youknowriad** [comment]
I need a review on my next PR to resolve this issue https://github.com/Automattic/wp-calypso/pull/5059 thanks.

**Comment by youknowriad** [comment]
Here is the last request to resolve this issue https://github.com/Automattic/wp-calypso/pull/5163

**Comment by timmyc** [comment]
@youknowriad I just deployed #5059 to production - excellent work!

One possible follow up now would be to switch over the [remaining component](https://github.com/Automattic/wp-calypso/blob/master/client/my-sites/posts/post-total-views.jsx#L11) using `PostStatsStore` to utilize the `QueryPostsStats` instead.  And then we could remove the old flux store completely.

**Comment by youknowriad** [comment]
@timmyc great :)

here is the PR for the next step https://github.com/Automattic/wp-calypso/pull/5216 :) 
maybe we can close the initial issue ?

**Pull request closed without merging**
