### PR TITLE
Reader: Update x-post active state style

### PR DESCRIPTION
**Pull request by jancavan**
This fixes: https://github.com/Automattic/wp-calypso/issues/10668

Our x-posts active state needs to be consistent with the rest of the cards.

**Before:**
screenshot 2018-03-12 10 58 38

**After:**
screenshot 2018-03-12 11 11 49

### CODE REVIEW

**Comment by blowery** [comment]
@samouri dserve hates this branch name.. any idea why?

**Comment by samouri** [comment]
.... two slashes

**Comment by bluefuton** [comment]
Nice one @jancavan!

This works really well apart from at the smallest mobile breakpoint, where I don't see the blue highlight when navigating with <key>j</key> and <key>k</key>.

**Comment by jancavan** [comment]
> This works really well apart from at the smallest mobile breakpoint, where I don't see the blue highlight when navigating with j and k.

Good catch @bluefuton. Fixed in: https://github.com/Automattic/wp-calypso/pull/23246/commits/3eca780587ae0d66597cd0f681076720a7b5e459

**Pull request merged**
