### PR TITLE
Checkout: use fixed positioning for sidebar summary

### PR DESCRIPTION
**Pull request by michaeldcain**
On non-mobile devices, the Checkout summary is displayed in the sidebar with features, total, and savings. This PR keeps the summary on the page as the user scrolls.

fixed-sidebar

**To test:**
- add an item to your cart and visit the new Checkout flow (with `?flags=composite-checkout-force`)
- verify that when the sidebar is shown (landscape tablet and desktop devices), the summary scrolls with the page
- verify that when the sidebar is collapse (mobile devices), the summary behaves as normal

### CODE REVIEW

**Comment by fditrapani** [comment]
Very nice! It's great to see the sidebar locked in there. I'm seeing a weird regression on my wider screen, in Chrome, where the sidebar is blown out:

image

I think we might need to change the place where we're setting the width on that column.

**Comment by michaeldcain** [comment]
> I'm seeing a weird regression on my wider screen, in Chrome, where the sidebar is blown out:

@fditrapani: I'm unable to reproduce this, even on a large screen. Can you provide any more info about it?

**Comment by fditrapani** [comment]
That's weird. It might be a local thing to me. I'm checking out with the ecommerce plan on Chrome. If you all can confirm there isn't an issue with the sidebar getting really wide, I'm good to go.

**Comment by michaeldcain** [comment]
> I'm checking out with the ecommerce plan

I can reproduce with the ecommerce plan. Digging into why/how that's even possible.

**Comment by michaeldcain** [comment]
@fditrapani: should be _fixed_ with e1e704242ac5ea8cec5350fbc1f2848901346f1b :)

**Comment by fditrapani** [comment]
That did the job for me! Looks good to go!

**Pull request merged**
