### PR TITLE
Update copy for store deprecation/removal

### LINKED ISSUE #48479: Store|Woo: Use 'translate' method for strings
This is a supplement ticket for PR https://github.com/Automattic/wp-calypso/pull/48324

We intentionally removed the use of the `translate` function in the PR to avoid translators start working on it as the final copy might change. 

Use `translate` function for any strings used in the PR.

The change should be made after confirming the final copy.

### LINKED ISSUE #48685: Store|Woo: Update all store sunset copy
The finalised copy is here: https://docs.google.com/document/d/1NS_LQKBHi6s7pzAD1ezUp9dLxwKd5N9bOKZl9y_880s/edit#

### PR DESCRIPTION
**Pull request by becdetat**
Fixes #48479 
Fixes #48685

#### Sidebar menu tooltip
On the site homepage, with `?flags=woocommerce/store-deprecated` in the URL, a tooltip appears next to the "Store" item:
image

#### Notice on the store dashboard
On the store dashboard, with `?flags=woocommerce/store-deprecated` in the URL, the following notice appears:
image

With `?flags=woocommerce/store-removed` in the URL, the following notice appears instead (note the copy change) and the rest of the dashboard items are removed:
image

#### Child pages notice
Go to a child page (eg Products) with `?flags=woocommerce/store-deprecated` in the URL. The following notice should appear:
image

### CODE REVIEW

**Review by ilyasfoo — APPROVED** [review]
Changes LGTM 🚀 ! Thank you for cleaning up and making the code more succinct 👍

**Comment by elizaan36** [comment]
Looks great. One small thing on the Store dashboard notice would be to just reduce the padding between the paragraph of text and the `Go to WooCommerce Home` CTA. Looks like it's 2X the other gaps so thought I'd mention, but it's a small thing.

**Comment by becdetat** [comment]
@elizaan36 
> reduce the padding between the paragraph of text and the Go to WooCommerce Home CTA.

Sure, I'll do this in a separate PR

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/5398750

Thank you @becdetat for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/5398750).

**Pull request merged**
