### PR TITLE
Comments Redesign: Persistence and Undo

### PR DESCRIPTION
**Pull request by Copons**
Branched off #19332

This is an experimental PR to see if this approach to the Comments set status undo makes sense.

screen shot 2017-10-31 at 18 03 21

This what I said earlier:

> Internal discussion: p7jreA-1ca-p2
>
> We've been talking of dropping success notices altogether. The only thing blocking us is that the notices are currently necessary for the undos.
> 
> @vindl suggested an approach similar to the one already featured in the Posts List.
> On spam/trash (which are the "semi-destructive" actions), the comment persist and enter a "disabled" state. It gets covered by an overlay with a message such as "Comment Deleted - Undo?".
> 
> By moving the Undo into the actual comment, we'd drastically reduce all the required back and forth between `Comment` and `CommentList`.
> Basically we'd end up with just the persistence functions, which can't go anywhere else but in the `List`.
> There will be a little bit of duplication between the single and the bulk actions, but it's a fair trade-off imho.
>
> What about approve/unapprove? I'd actually suggest that we don't persist them anymore.
> We have the All list where they're shown together, and I can't see any reason why the Approved and Pending lists should behave _almost but not completely_ the same.

This PR achieves it by not touching `CommentList` once (except for the persistence functions, of course), never firing a notice, and with a massively reduced undo spaghetti-logic.
It also keeps the persistence for the approved/unapproved toggle, just to avoid messing up with the established behaviour.

### Note to @Automattic/lannister 

Please excuse the +505 -0 changes, and do not waste time reviewing the code, but instead check if the behaviour actually works for you.

### Testing instructions

Checkout this branch and run it with
`env ENABLE_FEATURES=comments/management/m3-design npm start`

### CODE REVIEW

**Comment by kwight** [comment]
Are they intended to expire or time out at all? I love how it looks, but as soon as you've done a bunch of them, I want them to go away, or refresh somehow so that my screen isn't just zombie comments. That said, I'd also not like it very much if I'm about to manage a comment, and it suddenly shifts position because of higher comments disappearing 🙃

**Comment by Copons** [comment]
@kwight I didn't even bother to explore the expiration because the same confirmation notice for Posts does not expire.
Consistency aside, we could maybe add a "dismiss" button?

**Comment by gwwar** [comment]
- Will we still have an undo action notice for batch actions?
- What behavior do we expect when we perform a single action, then go into batch mode?

**Comment by vindl** [comment]
Nice work @Copons! I still prefer this approach to notices since the undo actions are closer and visually tied to specific comment that they relate to. With it we also don't need to worry about notices piling up.

My original idea was also to expire them after some time, but I see how that can cause problems with shifting the other comments. Adding a `dismiss` button might be an acceptable solution, although it does introduce one more click to the process.

**Comment by gwwar** [comment]
cc @drw158 for thoughts

**Comment by Copons** [comment]
> - Will we still have an undo action notice for batch actions?

We don't have undo for bulk actions right now, though...

I guess bulk mode behaviour could be:

- Bulk spam and trash will **not** persist: the comments will disappear instantly and therefore there won't be any undo overlay.
- All bulk actions will trigger a notice.
- Once/if we pull off the bulk endpoint, we could add the undo to the notices.

> - What behavior do we expect when we perform a single action, then go into batch mode?

I assume this is related to spam/trash (aka the new persistent actions).

What about we keep the persisted comments in the list, but:
- disabled / not selectable
- don't count toward the selected total

(This is likely a big change, so it'd go in its own PR)

**Comment by drw158** [comment]
I'm not a fan of the notices on Posts and Pages; they aren't used anywhere else, and they aren't really standard. We should somehow use the existing notices for this.

What if, for the destructive actions, we displayed an inline notice with an undo link? So:

- user hits trash
- comment goes to trash
- inline notice w/ undo is displayed in place of the trashed comment

**Comment by gwwar** [comment]
Sounds like we can try seeing how well inline notices work with this http://calypso.localhost:3000/devdocs/design/notices. If we run into trouble we can probably also work with @folletto too if he has time.

**Comment by folletto** [comment]
Historical note: that was an old style we should remove from everywhere in Calypso. It's probably one of the first pages ever designed, and the design language at the time wasn't as developed as it is today.

_tl;dr: don't use it, and if you see it and you have time to remove it, please do._

---

I'm sure most of you already know, but just for reference and alignment, we have now a more solid approach as Dave hinted:

1. Remove the entry immediately.
2. Show a global notification (the top-right bubbles) with the confirmation of the operation and the "Undo" action (or the error). Should disappear after a fixed time (i.e. 5 seconds, but I guess we have already a default elsewhere, let's use the same).

Other pieces of the UI depend however on which section we are in. Specifically, on how destructive the action is.

For example: Posts and Pages for example we don't really delete the content but move it to a different folder "Trashed". This means we can even avoid the global alert as the post simple should show or update the Trashed tab, and the user can undo from there.

Other areas where the action is destructive with no way back, we need to keep the notification. If that becomes a problem, we should review the persistence and stacking of notifications (especially on mobile). This would be beneficial for Calypso framework as a whole. 

Back to Comments...

Similarly the comments section has "Spam" and "Trash" categories, so we should just follow the same pattern as above, but dropping the global notification (given it seems the discussion that triggered this PR experiment).

I'd add that we should probably introduce the counters for comments, and would be amazing if on Spam/Trash we would do some animation on the counter, to signify the action taken and where it moved if the user wants to undo. ;)

**Comment by Copons** [comment]
Let me try to summarize:

- Don't use the confirmation notice (as in Posts and Pages). ✅ 

- Don't use an inline notice (which would be a new pattern). ✅ 

- Don't use the global notices. ✅ 

- Add the counters near the list titles (which is WIP anyway), and possibly add an animation when a comment changes list. 🤔 
Letting aside the animation itself, what would happen when we're scrolled past the nav bar?

**Comment by folletto** [comment]
> what would happen when we're scrolled past the nav bar?

Nothing... or we can stick the nav bar, like themes. ;)

**Comment by drw158** [comment]
Animating the counters is a cool idea, but I'd like to try that later.

I would like the destructive actions to be super clear. Working on Simplenote,  I know many users have a fear of the Trash folder. They don't have any confidence in it. They expect that the items in the trash folder could be wiped at any time (many services wipe the trash after a period of time). In this case, I would treat deletion as a destructive action, even thought it isn't, for the above reason.

For now, I suggest we do global notices for spam and trash actions with undo links. I don't know if that would solve the stacking problem though, if a user trashes a lot of comments at once. This is why I think an inline solution could work, since the notices aren't absolutely positioned and therefore don't stack, they scroll.

Either way, I think Google's apps are great at notices (especially with undo). 

Let's try the global notice idea since it seems easy, and see how it feels?

**Comment by folletto** [comment]
> They don't have any confidence in it.

If this is the case, I would try to fix this tho, instead of cluttering the experience everywhere else – as this is a pattern we have in at least 3 high-usage screens. 

No?

**Comment by Copons** [comment]
I think we might end up with way too many different patterns each for a specific case.

Currently, we show up a notice for every action.
Single approve, unapprove, spam, and trash have the Undo button.
Single delete doesn't, and neither do the notice for the bulk actions.

Approving/unapproving comments when in All, Pending, and Approved lists "persist" the comments (in other words, the comment stays in the list we're currently in).
It's an expected behaviour for the All list (which shows pending and approved comments).
For Pending and Approved lists, instead might be a leftover from the days when we didn't have an All list.
Persistent comments in Pending and Approved lists will "disappear" whenever changing list or route anyway.

Does this sound complicated? Well it is!

To summarize, this is everything we currently do (mixed and matched):

- Notice with undo
- Notice without undo
- Comment remains in the list forever
- Comment remains in the list until navigating away
- Comment is removed from the list

in response to these possible actions:

- Single action non destructive (approve, unapprove, spam, trash)
- Single action destructive (delete)
- Bulk actions non destructive
- Bulk actions destructive

The more I think about this, the more I believe the better way to handle it is what you're telling me is obsolete (the posts confirmation notice). 😄 

So, I'd probably stick with an all or nothing sort of decision:
- all actions display global notices
- no actions (including delete!) display global notices

And my preference would go to the no action (and not _only_ because I'm lazy, as most of the code was done long ago!).

I mean, all in all it all comes down to the Undo button, and the fact that the notices are the only sensible place for it.
But do we really need the undo button?

Our stats say that ~1% of the `change_status` actions performed on the Calypso Comments section are undos.
But numbers aside, why would we need to undo the spam and trash actions but not, for example, the approve?
To me, making an inappropriate comment show up on the site by mistake is a much worse thing than making an appropriate comment disappear from the site.

So yeah, I don't see a good reason behind the Undo and therefore behind the notices at all.

Except... right now we don't have a search feature yet, so if I need to undo on a really old comment, I'll have to change list and manually paginate until I find that comment.

**Comment by drw158** [comment]
Frist, let's just discuss destructive actions, or more appropriately named, "easy to miss" actions. By that, I mean actions that cause the comment to disappear and could cause confusion. I consider this to be Spam and Trash. Like, Approve, Reply all have inline feedback that they were completed. No need for notices if it complicates things.

And it also helps me to back up and remember why we are doing this in the first place (I forgot!) — the notices really pile up on actions like Approve (as described in the p2 post).

Top reasons why we need notices for Spam and Trash:

- There are a lot of actions and links on /comments. Easy to make a mistake.
- Comments disappear when actions are performed. Easy make a mistake and not know what just happened.
- If you bulk edit and hit Spam or Trash, those are actions with high consequence. If you make a mistake, you would have to find where they went and undo each one manually. Right now we don't have an undo, but at least we confirm what just happened via notice.

This is why I actually like the wp-admin design:

- Inline notices for destruction actions with undo (spam/trash)
- Global notices for bulk destructive actions with undo

Undo is a major part of this, but it is secondary. If it moves things along faster, I think we could leave out the undo for now.

Also I think we need to figure out a system for this anyway, since we _definitely_ need to inform the user when they delete the comment permanently from the trash.

**Comment by drw158** [comment]
Also, I do think inline notices would be great if we could get it working. I don't think there was a decision to **not** do them in favor of global notices, we just haven't designed how they should work, so it's not a standard thing yet.

**Comment by Copons** [comment]
First thing first, let's leave `delete` out of the discussion: it's the only literally destructive action. It has and will keep having the success notice (also because, technically, its notice is triggered automatically upon completion, and Comments Management is not involved at all). 
Also imho it's the only 100% unobjectionable thing of this whole discussion. 🙂

Now, about this thing instead:

### Inline Feedback

You say that we need notices for `spam` and `trash` because they, as opposed to `approve` and `unapprove`, don't have an inline feedback.
It's a fair point, albeit slightly mistaken: if you're in the Spam or Trash list, and `approve` a comment, that comment would disappear. The persistence only happens when toggling `approved`/`unapproved` in their respective lists

Anyway, this makes me wonder: **what if we added an inline feedback to `spam` and `trash` too?**
For example, we could add a red border to spam comments, and fade out a bit the trash comments (probably not the best a11y thing ever, but you get what I mean).
Something like this:

screen shot 2017-11-07 at 11 18 04

Having a different style for each comment status (white = approved; yellow = unapproved; red = spam; gray = trash) would improve scanning the list and could be expended by **persisting comments after every action**, and not only when toggling `approved`/`unapproved` in their respective lists.

This way, we wouldn't need notices because it's immediately obvious what happened.
And we wouldn't need undo buttons because we can just change the comment status back to whatever it was before.

With this kind of inline feedback, we wouldn't need to differentiate between any actions, single and bulk, whatever.
Every button you click simply changes the color of the comment.
You can't miss it, you won't ever have the screen filled with notices, etc.

Is the color an a11y concern?
Well, we could always show the label in both collapsed and expanded views.
It would probably increase the clutter, but it would keep the user's focus as close to the mouse cursor as possible: on the comment itself.

**Comment by drw158** [comment]
Wow! Whenever I think I'm just gonna quickly reply, it turns into a long one...

> what if we added an inline feedback to spam and trash too?

That's a good idea. Ultimately, after hitting trash/spam, I think the user will want the comment gone immediately though, which I think is the disadvantage of your design. I think it will feel strange if a trashed comment hangs around.

> It's a fair point, albeit slightly mistaken: if you're in the Spam or Trash list, and approve a comment, that comment would disappear. The persistence only happens when toggling approved/unapproved in their respective lists

Oh, right I forgot about that...

I'll have to retract what I said about destructive actions:

> I mean actions that cause the comment to disappear and could cause confusion.

So I guess the question is, if both Approve and Trash both remove the comment immediately (depending on the view you are in), why have a notice for Trash, but not Approve?

This sounds hypocritical, I can't fully articulate it, but it "feels" wrong to me to not have a notice for trashing a comment. If I trash something, I want a confirmation that I trashed it. Approve, Spam, and Trash are all close together, so if I'm not paying attention, I could hit one of those buttons by mistake. I would be asking myself, "Wait, I hit Approve, right? Did I hit Trash? I don't remember." There is no way to know quickly.

**But, most people here seem to like the idea of removing all notices altogether. So, I'm ok with "starting fresh" and remove all notices. We could ship evaluate, and add notices as we need them.**

@folletto:

>Dave: Working on Simplenote, I know many users have a fear of the Trash folder. They don't have any confidence in it.

>Folletto: If this is the case, I would try to fix this tho, instead of cluttering the experience everywhere else – as this is a pattern we have in at least 3 high-usage screens. No?

I would want "Trash" to be renamed "Archive" as a quick fix, but I'm not really trying to solve this for all 3 screens, although that would be interesting. I'm just trying to make a good comment management experience. Even if it was named Archive, I would still want a notice that the comment went to Archive.

Overall, I keep thinking about the email apps I use, and I love how there is a notice for almost every action, with an undo, and it gives me a lot of confidence in the product. If the core issue here is that the notices pile up too much, then surely there's a good way to deliver helpful notices without getting rid of them altogether.

**Comment by gwwar** [comment]
Were global notices thrown out of the loop? Could folks agree to:
- removing persistence in lists (since we have the All filter)
- a global notice for single actions. (While this will be a coding challenge, I'd like us to combine notices if folks rapidly perform actions. If this is too tricky, don't let the notices stack. )
- a global notice for bulk actions. (As Dave noted, It is nice having a visual reminder of what you just did. I had to use undo a few times accidentally moderating comments on our p2).

**Comment by drw158** [comment]
I don't think global notices are out, as long as it solves the stacking problem by doing what you said:

> I'd like us to combine notices if folks rapidly perform actions. If this is too tricky, don't let the notices stack.

**Comment by Copons** [comment]
> Ultimately, after hitting trash/spam, I think the user will want the comment gone immediately though

@drw158 Good point! I didn't think of it, and it makes so much sense.

> I'd like us to combine notices if folks rapidly perform actions. If this is too tricky, don't let the notices stack.

@gwwar I think it's both a coding _and_ design challenge.
Currently notices are designed as a single message with a single optional action related to the message.
We can sort of extend the single message by appending new messages in new lines, sure.
But what about the action?

Are we going to keep one Undo button for each notice?
```
Comment approved [Undo]
Comment approved [Undo]
Comment approved [Undo]
```
Or one for every notice we currently have?
```
Comment approved [Undo all]
Comment approved
Comment approved
```

In this case we could "collapse" all notices of the same type in a single message, such as:
```
3 comments approved [Undo all]
```
but what about the fact that each notice have its own expiration of 5 seconds?
How can we sure of what we're actually undoing if the notice is changing under our mouse cursor?
E.g. after a couple of seconds that "3 approved" notice could become:
```
Comment approved [Undo all]
Comment approved

or

2 comments approved [Undo all]
```
And then 1 comment approved, etc.

At the end of the day, if we decide to proceed with the combined notices approach, at the very least it means to create a new notice component for this sole purpose.

**Comment by Copons** [comment]
Though, let's reduce the feature creep for M3 (M3.5?).
I'm going to add back the global notices we use in prod, and then we iterate on that.

**Comment by folletto** [comment]
> I'd like us to combine notices if folks rapidly perform actions. 

> I think it's both a coding and design challenge.

True.

It's however also probably the best solution, and the one that will benefit Calypso as a whole the most :)

**Comment by drw158** [comment]
@Copons Those are some big challenges, so I'd be fine with just replacing the notices for now so they don't stack (no combine notices).

**Comment by Copons** [comment]
Closing because made obsolete by #19644.

**Pull request closed without merging**
