### PR TITLE
Add Header and Footer Navbars to the Logged out plugins Page

### PR DESCRIPTION
**Pull request by dkd903**
#### Proposed Changes

More info: pau2Xa-4j7-p2

This shows the Header and Footer on the Plugins pages in the logged out view

#### Testing Instructions

* Log out
* Navigate to /plugins
* Ensure that you see the sitewide header and footer Nav bars.
* The page should be unaffected if logged in

### CODE REVIEW

**Comment by gmovr** [comment]
One quick note, it looks like this also affects the logged in /plugins page.
Screenshot 2022-08-22 at 14 37 49

It might be something in the base PR too, just wanted to raise it. 👍

**Review by tyxla — COMMENTED** [review]
Thanks for your work here.

Unfortunately, this PR introduces far too many changes and new features - have you considered splitting it into multiple PRs so they could be reviewed and tested easier and with less chance to break something?

**Review by worldomonation — COMMENTED** [review]
While changes concerning `packages/calypso-e2e` are acceptable, I'd like to echo @tyxla's comments that this PR tries to do too many things at once. It is preferable to have more smaller PRs than one big one.

References: [1](https://blog.kewah.com/2019/how-to-keep-small-pull-requests/), [2](https://itsnotbugitsfeature.com/2019/10/22/splitting-a-big-pull-request-into-smaller-review-able-ones/)

**Comment by dkd903** [comment]
Thank you - I will be addressing the Review comments soon.

**Comment by dkd903** [comment]
@claudiucelfilip  @tyxla  - I have created the two new PRs:
1. https://github.com/Automattic/wp-calypso/pull/67706
2. https://github.com/Automattic/wp-calypso/pull/67707

**Pull request closed without merging**
