### PR TITLE
Modularise products list state

### LINKED ISSUE #42470: Modularise `productsList`
The `productsList` portion of the state tree needs to be modularised. See the [modularised state documentation](https://github.com/Automattic/wp-calypso/blob/master/docs/modularized-state.md) for more details.

### PR DESCRIPTION
**Pull request by sgomes**
This PR is one of many working on modularising state in Calypso. This one handles products list state.

For more details on state modularisation, see the [modularised state documentation](https://github.com/Automattic/wp-calypso/blob/master/docs/modularized-state.md) and p4TIVU-9lM-p2.

Note: I added reviewers that GitHub suggested. Please feel free to ignore the review request or pull in someone else if you're not comfortable reviewing this PR. Thank you!

Fixes #42470.

#### Changes proposed in this Pull Request

* Modularise products list state
* Split up products list selectors into individual modules

#### Testing instructions

* Install [Redux DevTools](https://chrome.google.com/webstore/detail/redux-devtools/lmhkpmbekcpmknklioeibfkpmmfibljd?hl=en).
* Open DevTools and switch to the Redux tab.
* Open `/read` on the live branch or your local copy of this branch.
* Click `State` on the top right to ensure you see all state, and not just the diff for the last action: 
image
* Analyse the tree and note that there's no `productsList` key, even if you expand the list of keys. This indicates that the products list state hasn't been loaded yet.
* Click `My Sites` on the top bar.
* Verify that a `productsList` key is added with the products list state. This indicates that the products list state has now been loaded.
* Verify that products list-related functionality works normally. This indicates that I didn't mess up.

### CODE REVIEW

**Comment by sgomes** [comment]
Note: the linting errors are expected, since I'm modifying the root reducer, which uses linting errors to point out unmodularised state in an attempt to prevent more of it from being created.

**Comment by sgomes** [comment]
The E2E errors seems transient and unrelated, as they match other PRs.

**Review by scinos — APPROVED** [review]
* Lint errors are expected
* `productsList` state is added when expected
* Products List (tested by changing plans and adding/removing extra features) functionality seems to work.

LGTM

**Review by wp-desktop — CHANGES_REQUESTED** [review]
WordPress Desktop CI Failure for job "wp-desktop-source".

@sgomes please inspect this job's build steps for breaking changes at [this link](https://circleci.com/gh/Automattic/wp-calypso/817731). For temporal failures, you may try to "Rerun Workflow from Failed".

Please also ensure this branch is rebased off latest Calypso.

**Pull request merged**
