### PR TITLE
Stats: Subscribers: Show rates

### PR DESCRIPTION
**Pull request by lezama**
Related to https://github.com/Automattic/jetpack/issues/40538

## Proposed Changes

* Before:

Screenshot 2024-12-17 at 10 53 08 PM

* After:

Screenshot 2024-12-17 at 10 52 19 PM

## Why are these changes being made?

*

## Testing Instructions

* Check email stats at http://calypso.localhost:3000/stats/day/emails/<your_site_url>

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
    - [ ] For UI changes, have we tested the change in various languages (for example, ES, PT, FR, or DE)? The length of text and words vary significantly between languages. 
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Comment by edanzer** [comment]
I am seeing rates now, so that's working.

Something seems off on the actual percentages (though I wouldn't think that would have anything to do with this PR, as you're just rendering the provided data).

I've posted before/after screenshots below. If you just look at the first six rows....

10 opens -> 69.2%
6 opens -> 30.8%
11 opens -> 69.2%
9 opens -> 53.8%
19 opens -> 69.2%
7 opens -> 58.3%

Obviously those percentages don't line up. Maybe there's something I'm missing that affected # of emails sent for each of those. Also the last time I did anything with this test site was like 6 months ago. :)  Not sure if that would affect things.

If we think there's an issue here, I would still go ahead and merge this, and then create a separate issue to see/fix how the underlying data is being computed. 

Before:
stats numbers

After:
states percent

**Comment by lezama** [comment]
Oh, let’s debug that! Could you send me the site URL? I can take a look.

**Comment by simison** [comment]
Shall we update labels from "Opens" -> "Open rate" and "Clicks" -> "Click rate"?

**Comment by edanzer** [comment]
@lezama The site in the screenshots is ericktesting1571.wordpress.com. I'm also happy to dig into it if you like.

**Comment by lezama** [comment]
Rates are calculated using unique opens, but prior to this PR, we were displaying total opens.
So the screenshots are comparing total opens with rates calculated using unique opens, which is causing the confusion. Does that make sense?

**Pull request merged**
