### PR TITLE
Jetpack Pro Dashboard: Add a download button to licenses with downloads

### PR DESCRIPTION
**Pull request by atanas-dev**
1204137270272763-as-1204696560014071
Requires D112726-code

## Proposed Changes

* Jetpack Pro Dashboard: Add a download button to licenses with downloads (e.g. downloading a third party plugin the license is for).

## Testing Instructions

- Please follow the steps in D112726-code
- Run Jetpack Cloud - http://jetpack.cloud.localhost:3000/partner-portal/licenses
- Make sure you have a license for WooCommerce Bookings
- Expand the license details - you should see a new Download button which when clicked triggers a download for the WooCommerce Bookings plugin.

Screen Shot 2023-06-21 at 15 59 15

## Pre-merge Checklist

- [x] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [x] Have you checked for TypeScript, React or other console errors?
- [x] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

**Comment by heydemoura** [comment]
I suggest hiding the download button for licenses that are not attached.
The retrieval of the download URL depends on an activation to exist, so it would only work for WooCommerce products that have an activation.

**Review by heydemoura — CHANGES_REQUESTED** [review]
I suggest hiding the download button for licenses that are not attached.
The retrieval of the download URL depends on an activation to exist, so it would only work for WooCommerce products that have an activation.

**Comment by atanas-dev** [comment]
> The retrieval of the download URL depends on an activation to exist

The download button does download a plugin for unassigned licenses for me right now, but I've removed the button for unassigned ones anyway just in case.

**Review by heydemoura — APPROVED** [review]
LGTM

**Pull request merged**
