### PR TITLE
Missing masterbar theme colors

### PR DESCRIPTION
**Pull request by lsl**
Fixes https://github.com/Automattic/dotcom-forge/issues/8317

Follow up on https://github.com/Automattic/wp-calypso/pull/92472/ that made use of new variables available in only some color schemes (originally introduced for classic view sites only here: https://github.com/Automattic/wp-calypso/pull/90136)

## Proposed Changes

- Sets masterbar icon and highlight colors for remaining non core color themes.
- Makes use of icon / highlight colors in notification bell, cart, and help icon to fix some regressions in the light theme.

Known issues:
- Color scheme's in classic view may have similar problems
- Submenu text color seems a little off, possibly need a new variable for this, related to: 
```
--color-sidebar-submenu-background: var(--theme-submenu-background-color);
--color-sidebar-submenu-text: var(--theme-submenu-text-color);
```
I'm not sure if they're drop in's for all themes so I'd like to hold off on that for now.

## Testing

- [ ] Masterbar icons, text, highlighting, all color schemes in calypso

Before

Screenshot(215)

After

Screenshot(216)

Before

Screenshot(217)

After

Screenshot(218)

### CODE REVIEW

**Comment by fushar** [comment]
@lsl should we create an issue for this, or do want to finish this by yourself?

**Comment by lsl** [comment]
Issue here https://github.com/Automattic/dotcom-forge/issues/8317 will finish off today hopefully.

**Review by okmttdhr — APPROVED** [review]
Worked well for updated colors ✅ 

I noticed Blue color appears to be no colour when hovering, but it does not seem to be related to this change, so we may want to address it later. 
| blue | classic blue |
|--------|--------|
| Screenshot 2024-07-17 at 16 34 16 | Screenshot 2024-07-17 at 16 34 29 |

**Comment by Addison-Stavlo** [comment]
I just noticed this called out in slack p1721216090512409-slack-C03NLNTPZ2T and saw this PR to see if it was resolving it. It doesn't look like it does, but we can create a follow up as well if needed.  There seems to be some color bleed on the reader still, if we select a stream inside a submenu group (like tags, automattic, etc.) and hover it, we get the green:

Screenshot 2024-07-17 at 8 22 23 AM

**Comment by Addison-Stavlo** [comment]
> [Addison-Stavlo](https://github.com/Addison-Stavlo) restored the update/mb-theming branch [4 minutes ago](https://github.com/Automattic/wp-calypso/pull/92621#event-13537192190)

Whoops, I was pushing a commit I was going to add before shipping and that reopened the branch. No biggie, but opened it here instead https://github.com/Automattic/wp-calypso/pull/92751

**Comment by lsl** [comment]
> I noticed Blue color appears to be no colour when hovering, but it does not seem to be related to this change, so we may want to address it later.

Matching core's behavior. Didn't like it either :smile:

**Pull request merged**
