### PR TITLE
Podcasting: split into its own section

### LINKED ISSUE #79823: Move "Podcasting" settings to its own section
### Details

Currently Podcasting settings are under **Settings → Writing**.

_Podcasting_ doesn’t really fit inside _Reading_ or _Writing_, because settings include enabling new features from publisher and reader perspective.

Additioanlly, separating few sections into their own gives customer a clearer mental model, separating "blog", "podcast", and "newsletter" (see https://github.com/Automattic/wp-calypso/issues/79822)

### Checklist

- [x] Modify Podcasting settings page to be its own settings section
- https://github.com/Automattic/wp-calypso/pull/84046
- [x] Move _"Publish a podcast feed to Apple Podcasts and other podcasting services."_ copy to the top of the new settings page.
- [x] New sidebar navigation item under Settings. Note that these need updating in two places; WP-Admin (PHP) and Calypso (JS). Search for "nav unification" from field guide for docs.

Screenshot 2023-07-25 at 10 57 55

Screenshot 2023-07-25 at 10 58 18

### Related

_No response_

### PR DESCRIPTION
**Pull request by simison**
Resolves https://github.com/Automattic/wp-calypso/issues/79823

This will increase awareness about podcasting feature, and allow quicker finding instead of hunting for it from un-intuitive "writing" section.

The actual sidebar link is added in https://github.com/Automattic/jetpack/pull/32146

**BEFORE**

Accessible only under "Writing" and pressing "set up" or "manage" podcasting

Screenshot 2023-07-31 at 15 39 20

Screenshot 2023-07-31 at 15 39 15

**AFTER**

Its own clear section.

Screenshot 2023-07-31 at 15 40 20

## Proposed Changes

* Move podcasting into its own section, and doing necessarily adjustments to the header to match other settings sections.
* The small section under "Reading" is left in place for now, so that people who are used to finding it there won't get lost. I'll loop back removing it in some weeks.

## Testing Instructions

* Access `/settings/podcasting`
* Test with site without podcasting enabled, and enable using this page. Try change settings.
* If you want to try sidebar link, try together with D120989-code in your sandbox.

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

**Comment by simison** [comment]
Need to fix the new typescript issue that came up in rebase:

`
client/my-sites/site-settings/settings-podcast/main.tsx(146,7): error TS2741: Property 'handleAutosavingToggle' is missing in type '{ fields: Fields; handleToggle: (field: string) => (value: boolean) => void; handleSubmitForm: (event: FormEvent<HTMLFormElement>) => void; disabled: boolean; isSavingSettings: boolean; savedSubscriptionOptions: SubscriptionOptions | undefined; updateFields: (fields: Fields) => void; }' but required in type 'NewsletterSettingsSectionProps'.
`

**Comment by edanzer** [comment]
Everything tests as expected and code is all good except for the TS error. I tested alongside the backend diff and approved that one. 

For the TS error, I think we can resolve that by passing handleAutosavingToggle to NewsletterSettingsSection [here](https://github.com/Automattic/wp-calypso/pull/79996/files#diff-858c6188c4c35700aa81a87172cd18e55cd284284b956041113913558ea5a709R146). That method is already available via the wrapSettingsFrom HOC, passed to the ReaderSettingsSection just below in the same file, and also passed to NewsletterSettingsSection in the settings > newsletter section [here](https://github.com/Automattic/wp-calypso/blob/e22b0226f7b2585ddafbc4cfbe7988059ed54e7b/client/my-sites/site-settings/settings-newsletter/main.tsx#L69).

There's a failing unit test that looks unrelated. Just re-running.

**Review by edanzer — APPROVED** [review]
Testing as expected. I tested alongside backend diff, and also tested on Atomic with wpcomsh PR. Unit tests now passing. And I pushed a small fix for the TypeScript error.

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/8873971

Thank you @simison for including a screenshot in the description! This is really helpful for our translators.

**Pull request merged**
