### PR TITLE
Replace Sela with Dara for themes in signup

### PR DESCRIPTION
**Pull request by sixhours**

### CODE REVIEW

**Comment by sixhours** [comment]
Steps for testing: 

- Switch to this PR 
- Go to calypso.local:3000(?)/start/ 
- Click "A welcome page for my site"
- Make sure Dara shows up instead of Sela

**Comment by sixhours** [comment]
Good question! The idea is to replace older themes with newer ones to keep things fresh, so we hadn't talked about testing conversion explicitly, but I'll check with Ian.

**Comment by michaeldcain** [comment]
Not a blocker, just checking. :shipit:

**Pull request merged**
