### PR TITLE
Removing plugins tooltip

### LINKED ISSUE #32821: Plugins tooltip on dashboards with only one Atomic site is misplaced
#### Steps to reproduce
1. Log into an account with only one site which is on the Business or eCommerce plan with at least one plugin installed (when testing, you can add Hello Dolly)
2. In Calypso, scroll down to Add a Site button

#### What I expected
For the manage plugins tooltip to point to Plugins, which is now under Tools, or possibly to wp-admin (not 100% sure). Also, for the Add a Site text to not be blocked.

#### What happened instead
The plugins tooltip points to Add a Site button.

#### Browser / OS version
First noticed on Chrome Version 73.0.3683.103, other Happiness Engineers confirmed they see it as well.

#### Screenshot / Video
tooltipplugin

#### Context / Source

This was not a user report, but noticed in multiple sites while assisting users, since the nav drawer layout was changed.

### PR DESCRIPTION
**Pull request by davemart-in**
## Changes proposed

@msilbers brought up the fact that the plugins tooltip is just floating off on it's own now after the nav drawer redesign down towards the bottom of the screen:

plugins-tooltip

At first I thought about fixing the bug, but as I dug in, I discovered that this is a bit more tricky than I had anticipated. With "Plugins" now residing within the "Tools" section, and with tooltips being set at a specific pixel offset, I don't see a great solution. The tooltip would need a different pixel offset depending on whether the Tools section was collapsed or not. It would also need to adjust as the Tools section opened and closed. 

My assessment is that it's just not worth it. In this PR I simply removed the plugins tooltip.

## Linting error

In the process of removing this tooltip I ran into a linting error that is above my pay grade :-) 

```
/Users/davem/Projects/Automattic/wp-calypso/client/my-sites/plugins/plugin.jsx
50:40  error  Component should use es6 class instead of createClass  react/prefer-es6-class
```

I added `/* eslint-disable react/prefer-es6-class */` temporarily to the top of `/client/my-sites/plugins/plugin.jsx` just so that I could commit my code and get this PR up.

If someone can help me with that refactor that would be much appreciated.

## Testing instructions

1) Log into an account with only one site which is on the Business or eCommerce plan with at least one plugin installed (when testing, you can add Hello Dolly)
2) In Calypso, scroll down to Add a Site button

Fixes #32821

### CODE REVIEW

**Comment by jsnajdr** [comment]
The guided tour for the Plugins item was created as part of the "Calypsoify Plugins" project last year. My experience was that it was always somewhat broken, but never got around to fix it. Cc @retrofox and @apeatling: if the tour is removed, will we miss it?

**Comment by jsnajdr** [comment]
> If someone can help me with that refactor that would be much appreciated.

That refactor is not an easy one, just disabling the ESLint warning is OK. It will be its own PR when it happens, not a drive-by to something else.

**Comment by apeatling** [comment]
Removing it is fine, although I don't think without it, I don't think it's clear where to go after you've installed your first plugin.

**Comment by alaczek** [comment]
> without it I don't think it's clear where to go after you've installed your first plugin.
Over at Fix the flows we're currently looking closer at the plugin/theme upload flows, and this has come up in #33066.

**Comment by davemart-in** [comment]
Cool. My proposal is:

A) To merge and deploy this PR. This tooltip is clearly in the wrong spot. Fixing it would require us to refactor the tooltip library to handle different positions for open/closed menu sections.

B) Continuing to look for a solution to this problem in #33066

**Comment by apeatling** [comment]
:+1:

**Review by apeatling — APPROVED** [review]

**Pull request merged**
