### PR TITLE
Bump WordPress.com Editing Toolkit plugin to v2.0

### PR DESCRIPTION
**Pull request by Copons**
#### Changes proposed in this Pull Request

This release's changelog is:

* Rename directories from "full-site-editing*" to "editing-toolkit*" (#44501)
* Update/premium content loading assets code cleanup (#45052)
* FSE: Add Newspack assets unit tests (#43218)

### CODE REVIEW

**Comment by nsakaimbo** [comment]
👋 Hello! Just noticed that Calypso tests were not kicked off for this PR. CI job is failing with the error:

`An unexpected error occurred: "https://registry.yarnpkg.com/@automattic%2fwpcom-editing-toolkit: Not found".`

Any idea why this is? 🤔

**Comment by Copons** [comment]
@nsakaimbo 🤔 Could it be it's because the PR that changed the app name from `@automattic/full-site-editing` to `@automattic/wpcom-editing-toolkit` aren't deployed yet?

**Comment by Copons** [comment]
@nsakaimbo in case you're curious, it was because the Calypso's root package.json was referencing the app's previous major version.
It was enough to update that to `^2.0.0` to fix the issue.

**Comment by nsakaimbo** [comment]
> it was because the Calypso's root package.json was referencing the app's previous major version

ah, this is good to know for future reference, and nice work finding the root cause, @Copons!

**Comment by Copons** [comment]
It was mostly @noahtallen but I'll take the compliments! 😄

**Comment by autumnfjeld** [comment]
@noahtallen  I was curios if the top part the[ Editing Toolkit readme](https://github.com/Automattic/wp-calypso/tree/master/apps/editing-toolkit) is still valid.  For instance:


>Note: This plugin is currently being renamed from Full Site Editing Plugin to WordPress.com Editing Toolkit Plugin. In the near future, the following will be changed:

> Directories and filenames referencing "full site editing"

From my surface understanding,  I _think_ 🤔  that renaming  has been done?  Or is there still more to come?

**Comment by Copons** [comment]
> @noahtallen I was curios if the top part the[ Editing Toolkit readme](https://github.com/Automattic/wp-calypso/tree/master/apps/editing-toolkit) is still valid. For instance:
> 
> > Note: This plugin is currently being renamed from Full Site Editing Plugin to WordPress.com Editing Toolkit Plugin. In the near future, the following will be changed:
> 
> > Directories and filenames referencing "full site editing"
> 
> From my surface understanding, I _think_ 🤔 that renaming has been done? Or is there still more to come?

@autumnfjeld My bad, I didn't check think to check that readme. 🤦

**Comment by vindl** [comment]
> From my surface understanding, I think 🤔 that renaming has been done? Or is there still more to come?

The major user/dev facing changes have been completed but there are still pieces that reference `full-site-editing` like namespaces, package names, text domains etc. Here is one example of the remaining changes that still need to be merged https://github.com/Automattic/wp-calypso/pull/44552.

**Pull request merged**
