### PR TITLE
Stats: fix dashboard header/tab alignment

### PR DESCRIPTION
**Pull request by myhro**
Closes Automattic/red-team#256.

## Proposed Changes

Fix the alignment of the header and navigation tabs in the Stats dashboard on Calypso Blue.

## Why are these changes being made?

These changes are being implemented to align the header and navigation tabs with the similar design found in the WP Admin dashboard.

## Testing Instructions

- In a local or Calypso live environment, navigate to the `Stats` section in the sidebar of a given site.
  - This can also be tested using a Jurassic Ninja site, such as `/stats/day/artistic-ukulele-worm.jurassic.ninja`.
- Check the alignment of the `Traffic / Insights / Subscribers` navigation bar compared to the `Jetpack Stats` header.

| Before | After |
| --- | --- |
| image | image |

---

> [!NOTE]
> The length of the underline highlighting the active tab has been shortened slightly. This adjustment reflects the fact that the first item is no longer centered in its column. However, this behavior is consistent with what is observed in WP Admin:

| WP Admin |
| --- |
| image |

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
    - [ ] For UI changes, have we tested the change in various languages (for example, ES, PT, FR, or DE)? The length of text and words vary significantly between languages. 
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Review by Initsogar — APPROVED** [review]
Looks good to me. Tested on different resolutions and all seems good.

CleanShot 2024-11-25 at 14 13 08@2x

As mentioned in the ticket, it looks similar to wp-admin.

CleanShot 2024-11-25 at 14 14 10@2x

**Comment by myhro** [comment]
Thanks for the review, @Initsogar!

I'm holding on merging/deploying, as @kangzj [might want to test it further][1].

[1]: https://github.com/Automattic/red-team/issues/256#issuecomment-2494801090

**Review by kangzj — APPROVED** [review]
Thanks @myhro for the fix. Happy for it to ship, but it'll be even better if you could take a look at the margin of the Jetpack log0 for screen width < 600px for Odyssey Stats. Thanks again for the fix.

image

**Review by kangzj — APPROVED** [review]
LGTM! Thanks for the fix 🚀

**Pull request merged**
