### PR TITLE
Plans overhaul Phase 1: Apply latest copy and design to Plans pages

### PR DESCRIPTION
**Pull request by claudiucelfilip**
#### Changes proposed in this Pull Request
More info: pdgrnI-pJ#comment-768-p2

* adds the latest copy to the overhauled Plan grid
* enables new Plan grid for Atomic sites
* adjusts mobile layout sizes 

Planning page i1 - collapsed - final copy VERSION2

#### Testing instructions

* Go to /plans/[site]/?flags=plans/pro-plan
* The Plans grid copy should match the design from the description
* Feature tooltip popup text should match the ones from the spreadsheet: 2bf68-pb
Screenshot 2022-03-17 at 14 49 34

Screenshot 2022-03-17 at 14 50 37

* Go to /start/plans?flags=plans/pro-plan
* The Plans page should match the design from the description

Screenshot 2022-03-17 at 14 52 08
Screenshot 2022-03-17 at 14 52 23

* Go to /plans/my-plan/[site]?flags=plans/pro-plan on an Atomic site (ex. Bussiness)
* You should notice the Plan overhaul changes
Screenshot 2022-03-17 at 15 14 03

### CODE REVIEW

**Comment by claudiucelfilip** [comment]
[Apply the final copy changes for the Calypso Plans](https://trello.com/c/LZLLOYBP/17-apply-the-final-copy-changes-for-the-calypso-plans)

**Comment by claudiucelfilip** [comment]
Test comment

**Comment by southp** [comment]
Test comment 2

**Comment by dzver** [comment]
(I seem to have issues posting a comment or uploading files)

There's a small misalignment on Desktop that I see, is this on purpose?

Screenshot 2022-03-17 at 16 25 56

**Review by southp — APPROVED** [review]
It's now perfectly aligned. LGTM :)
image

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/7187250

Thank you @claudiucelfilip for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/7187250

Thank you @claudiucelfilip for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/7187250).

**Pull request merged**
