### PR TITLE
plugin-site: Correct calculate plugin manage permissions

### PR DESCRIPTION
**Pull request by mreishus**
#### Proposed Changes

* On `/plugins/woocommerce/<site>`, update the logic used to calculate which plugin actions are permitted

#### Testing Instructions

* Have a starter plan site with a marketplace addon purchased (Like Xero)
* Visit `/plugins/woocommerce/<site>`
* **Before PR: See active switch even though you're not allowed to turn it off**

**After PR: Active switch is hidden**

(It would probably be even better to have an automanaged message here, but maybe in followup?)

* **Business sites should continue to act the same**

Related to #65263

### CODE REVIEW

**Comment by mreishus** [comment]
` 		isAutoManaged: isManagedPlugin,`
This part of the logic isn't quite correct, since marketplace addons are auto managed, but don't return true here.

I could change to: `isAutoManaged: isManagedPlugin || ! canManagePlugins,`, but I'm not sure if that's right.

**Comment by obenland** [comment]
The PluginSiteJetpack component checks for [`isAutoManaged` or whether the plugin is a marketplace item](https://github.com/Automattic/wp-calypso/blob/c39c07c106ec74de2e00935a6e93231cc97fa2c7/client/my-sites/plugins/plugin-site-jetpack/index.jsx#L90-L94) to display the auto-managed text.

**Comment by mmtr** [comment]
> After PR: Active switch is hidden

Would it be possible to disable it instead so it's aligned with https://github.com/Automattic/wp-calypso/pull/65269? Or should we change https://github.com/Automattic/wp-calypso/pull/65269 instead to hide the toggles?

**Comment by mmtr** [comment]
> I could change to: isAutoManaged: isManagedPlugin || ! canManagePlugins,, but I'm not sure if that's right.

FWIW, that's what we do here:

https://github.com/Automattic/wp-calypso/blob/f0624e88fbfc63fa798c99b67da17789798049b0/client/my-sites/plugins/plugins-list/index.jsx#L572

**Review by mmtr — APPROVED** [review]
This seems to work as expected. There is room for some improvements as noted in the comments, but can be followed up later.

**Pull request merged**
