### PR TITLE
Importers: Move file upload to redux

### PR DESCRIPTION
**Pull request by spen**
#### Changes proposed in this Pull Request

This PR is an attempt to break out some of the work found in #27425 in to a more reviewable chunk.
It aims to move the importer upload state from the flow store in to our redux store.

To achieve this, I've had to make a slight compromise in how this works but the effect should still be the same as before...
Previously, when somebody started an upload, the details for that upload would be held against a fake importer id (see #27425 for details on this fake id/object). That object would later be replaced when the upload completes, along with the upload data.
These changes now assume just a single upload at any one time as we hope to get rid of the need for the fake id/object.

#### Testing the regular flow

- Start at http://calypso.localhost:3000/settings/import
- Go to the WordPress importer by clicking "Start Import"
- Upload a valid WXR file
  - If slow enough, you should see a progress bar - often the exported file is small, so you might miss this
  - If not slow enough, you'll see the progress later when we attempt to upload a large file.
  - You should see the UI progress to the map authors pane
  - After mapping authors, you should progress through the import and eventually get to the 'import complete' state
- Repeat this process for the other importers
  - Note that site importer is a little different given the url and preview steps 

#### Testing errors
- Go to the WordPress importer by clicking "Start Import"
- Upload a non WXR file, this is a good opportunity to see the progress bar, by choosing a large file - Note, we might want to consider checking for file extension to help avoid people dropping invalid files here earlier
  - Once uploaded, you should see an error as below:

screen shot 2018-10-12 at 09 38 52

### CODE REVIEW

**Comment by scruffian** [comment]
The code changes look good.

I tested this but got stuck here:
screen shot 2018-10-19 at 23 06 02

**Comment by spen** [comment]
Thanks for taking a look at this - really appreciate that @scruffian !

Looking at the report card for this test blog I can see that the state's gotten stuck between the started and running phases.

> Calypso import started | ✅
> -- | --
> WordPress import running | ❌

This seems to happen intermittently, so I'm unsure what's caused it @bisko - do you have any insight in to that?

**Comment by scruffian** [comment]
Is it possible that this PR created that issue, or is it a separate issue?

**Comment by spen** [comment]
I've definitely seen it a bunch before but I'll investigate a bit more before ruling out that this PR is adding to the issue 🤔
I've reset the importer state on that test blog, not sure if you've seen but there's a button for that right at the bottom of the report card now - in case you get stuck again :)

**Comment by scruffian** [comment]
I tested again with a different import file and everything looks good. I suggest we go ahead and merge this. 🚢

**Comment by spen** [comment]
Awesome, thanks heaps @scruffian - just rebased to incorporate the recent changes to our initial reducer (#27982) and CI checks pass :)

**Comment by creativecoder** [comment]
For what it's worth, I reviewed this as well and it worked fine for the 3 (smallish) WordPress imports I tried.

**Comment by spen** [comment]
Cheers Grant :) We figured we'd merge and just rollback / fix-up any changes if you had any comments while reviewing - just to avoid more rebasing ;) If you do have any improvement suggestions they're still more than welcome 👌

**Pull request merged**
