### PR TITLE
Extensions: WPSC - Add support for preloading / cancelling preload of the cache

### PR DESCRIPTION
**Pull request by donnapep**
This PR adds support for preloading the cache and cancelling preload of the cache on the _Preload_ tab.

### In Progress

cache-preload-progress

### Success

cache-preload-success

### Failure

cache-preload-error

### In Progress

cache-preload-cancel-progress

### Success

cache-preload-cancel-success

### Failure

cache-preload-cancel-error

### CODE REVIEW

**Comment by ockham** [comment]
Something's a bit funny here -- I can repro the statuses given by the images in the PR desc, but I think there's something wrong with the button label: after hitting the button and waiting for the success message, the label still reads 'Preload Cache Now'. If I reload the page, it changes to 'Cancel Cache Preload' (after the second or so it takes to fetch data from the network).

Is it possible that the reducer's and selector's current level of detail isn't fine-grained enough to distinguish between "network request in progress" and "preloading is currently switched on"?

**Comment by donnapep** [comment]
@ockham So I'm not sure what the best solution might be here. The API returns an `is_preloading` field that indicates whether or not a preload is currently in progress (it can take quite some time or it can be relatively quick), and this setting is used to control the visibility of those buttons.

We could change the button to show "Cancel Cache Preload" immediately after the preload button is clicked, but it's still possible that by the time the user clicks to cancel, the cache has already been preloaded and there's nothing to cancel.

We'd probably need to implement a polling mechanism, or perhaps give a rethink of the entire preload process, but I'm wary of further delaying the release of the calypsofication of WP Super Cache at this point.

**Comment by ockham** [comment]
Right, I was considering whether we should toggle the button label on change, but yeah, you're right that might blow up in terms of complexity if we want to do it right. Okay, so let's not overthink this.

I think there is one change that could make things a bit more intuitive, and that's changing the success message -- maybe my confusion stems from `Cache preload completed successfully...` being contradictory to seeing `Cancel Cache Preload` (even tho only upon reload). Plus the success msg plainly doesn't seem to be quite true 😄 -- so what about `Cache preload started successfully...`?

(LGTM otherwise)

**Comment by donnapep** [comment]
> I think there is one change that could make things a bit more intuitive, and that's changing the success message -- maybe my confusion stems from Cache preload completed successfully... being contradictory to seeing Cancel Cache Preload (even tho only upon reload). Plus the success msg plainly doesn't seem to be quite true 😄 -- so what about Cache preload started successfully...?

@ockham Ah, good point. Fixed by https://github.com/Automattic/wp-calypso/pull/14327/commits/a70114ecc10d9a4bf3e0975ac0e65d3d67902b02.

**Pull request merged**
