### PR TITLE
Stepper: Show "your plan" when back from checkout

### LINKED ISSUE #97078: Stepper: Missing indication on current plan when back from checkout
In START:

If you Domains -> Plans -> SITE CREATION -> Checkout -> Browser back to Plans

Image

(Given that you didn't proceed with the checkout, your current plan will be the FREE one)

IN STEPPER:

This doesn't happen. It should.

We don't have the correct `selectedSite` here https://github.com/Automattic/wp-calypso/blob/trunk/client/signup/steps/plans/index.jsx#L459

### PR DESCRIPTION
**Pull request by escapemanuele**
Fixes https://github.com/Automattic/wp-calypso/issues/97078

## Proposed Changes

Check the issue.

## Testing Instructions

* Go to /setup/onboarding
* Free domain -> Paid plan -> Checkout -> Browser back to Plans page
* You should see the "Your plan" badge on the free plan

### CODE REVIEW

**Review by alshakero — APPROVED** [review]
Looks great!

**Comment by alshakero** [comment]
We probably should type the state inside `useIsManagedSiteFlowProps`

**Comment by escapemanuele** [comment]
I can't seem to make this work anymore, because `getSignupCompleteFlowName()` returns undefined. I believe it must be some conflicts with [this](https://github.com/Automattic/wp-calypso/pull/97369/files#diff-1ceaa1de69b40e0a07953f76572ba4484bd63b716ce1f4ff4e01b6015d4eb5c9R81) clearing the value

**Comment by alshakero** [comment]
We can close this now. [This](https://github.com/Automattic/wp-calypso/pull/97369/files#diff-1ceaa1de69b40e0a07953f76572ba4484bd63b716ce1f4ff4e01b6015d4eb5c9R81) will take care of it.

**Pull request closed without merging**
