### PR TITLE
Editor: show busy button state while saving or publishing.

### LINKED ISSUE #12140: Editor: 'Saving' Difficult to see
#### Steps to reproduce
1. Edit a post  
2. Select Update 

#### What I expected
When I select Update to see something indicating it was updating. 

#### What happened instead
My connection was slow, it took a few seconds to update. At first, I didn't think anything happened when I selected update, so I clicked it a few more times. Then I noticed the "Saving" text. It was difficult to see the  text to the far left, in light grey. 

#### Browser / OS version
Safari Mac 10.12.03

#### Screenshot / Video
http://cld.wthms.co/njK9

#### Context / Source

I'd suggest revising the indicator that the post is saving. It's too far from where a user's attention would be when selecting Update. 

#perspective #dogfooding, #manual-testing

### PR DESCRIPTION
**Pull request by mtias**
Clarifies something is happening:

image

Fixes #12140.

### CODE REVIEW

**Comment by timmyc** [comment]
👍  this is a great addition, thanks!

**Comment by drw158** [comment]
Wouldn't it be better if the button text changed to `Saving...`?

**Comment by folletto** [comment]
That's another thing we can evaluate. I think they aren't exclusive ⭐️

**Comment by mtias** [comment]
@drw158 I tried that but it looked really annoying because the width changes and it pushes the button row. Also you would need to account for publish/publishing, save/saving, update/updating, schedule/scheduling, etc.

**Pull request merged**
