### PR TITLE
Inline help: change button hover animation from wiggle to elevation

### LINKED ISSUE #32639: Inline Help: Button animation looks broken
**Steps to reproduce**
1. Anywhere inside Calypso hover over the help icon in the bottom right corner to see the animation.

**Result**
Quick video of the issue: https://cloudup.com/c9A87aQIhcv

**What I expected**
I think we should re-think the animation here (tagging Muriel in case there are already guidelines around this). At the very least I expected the animation to be fluid, not jerky and stuck on repeat.

**Browser / OS version**
Chrome 73.0 / macOS 10.14.4 (Mojave)

### PR DESCRIPTION
**Pull request by danhauk**
#### Changes proposed in this Pull Request

* Remove wiggle animation on inline help button hover. Use an increased elevation as the hover state instead. This is similar to how Google does their hover state on the Compose button in Gmail.

**Before**
inline help before

**After**
inline help after

#### Testing instructions

* Check out this branch or use https://calypso.live/?branch=update/inline-help-button-animation
* Hover over the inline help button in the bottom right corner
* Make sure the animation is the increased elevation (shadow) instead of the wiggle

Fixes #32639

### CODE REVIEW

**Comment by danhauk** [comment]
Pinging @drw158 with regards to Muriel. Does this look ok? Should we increase the elevation even more on hover? Gmail does it less subtle than what I did:

**Comment by donpark** [comment]
On hover shadow effect seems too subtle to notice **at actual size**.
I'd like to see anything more noticeable, short of orbiting dancing unicorn that is.

**Comment by donpark** [comment]
Just tried scaling on grow hack and I think it looks nice in a _eager to please_ way. Just a random suggestion.

scale-on-hover

This involves replacing the `&:hover:not` and `@keyframe` styles with just:
```
    &:hover {
        transform: scale(1.25);
    }
```

**Comment by alaczek** [comment]
@drw158 is the solution above acceptable? If so, I can take care of deploying.

**Comment by alaczek** [comment]
LGTM!

**Pull request merged**
