### PR TITLE
Jetpack Backup: Give a checkbox to save staging credentials on the Copy to staging screen

### PR DESCRIPTION
**Pull request by rustamshaikh**
## Proposed Changes

* Give a `Save for later` checkbox on Jetpack Cloud's _Copy to Staging_ credentials screen
* Record a tracks event `calypso_jetpack_advanced_credentials_flow_credentials_save_staging` when `Save for later` checkbox is checked and the form is submitted.

| Before  | After |
| ------------- | ------------- |
| Screenshot 2023-10-20 at 6 17 40 PM  | Screenshot 2023-10-20 at 6 17 54 PM  |

| Unchecked  | Checked |
| ------------- | ------------- |
| Screenshot 2023-10-20 at 6 51 44 PM | Screenshot 2023-10-20 at 6 51 50 PM |

## Testing Instructions

- Spin up Calypso Blue and Jetpack Cloud live branches
- Visit a site's activity log and click on _Copy this site_ button
- On _Set a destination site_ screen, click on _Enter credentials for a new destination site +_ link
  
  Screenshot 2023-10-20 at 6 56 14 PM

- Ensure the form has a _Save for later_ checkbox just above _Confirm credentials_ button.
   
   Screenshot 2023-10-20 at 6 51 44 PM

- Fill in the SSH/SFTP credentials of a non-Jetpack-connected site. Before submitting check the `Save for later` checkbox, the submit button text will change to `Test and save credentials` 

  Screenshot 2023-10-20 at 6 51 50 PM
- Open Developer tools to verify the tracks event on submit, verify only if the `Save for later` checkbox is checked and the form is submitted - the tracks event `calypso_jetpack_advanced_credentials_flow_credentials_save_staging` should get recorded.
  
   Screenshot 2023-10-20 at 7 04 54 PM

- Additionally, verify if the credentials are saved with `staging-<identifier>` role in RWDB's credentials section of this Jetpack site.

@grbicsanja / @keoshi or anyone - Please check if the text for the `Save for later` checkbox/toggling of the submit button text on change of checkbox state change is acceptable or can be improved/simplified :)

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [x] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [x] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

**Comment by rustamshaikh** [comment]
Maybe the checkbox text can be improved to something clearer to the user that it is going to be saved and they won't be needed to input them again 🤔 - like `Save credentials` or `Remember credentials` - thanks @Initsogar for suggesting these

**Review by Initsogar — APPROVED** [review]
Codewise it looks great and it works as expected.

Tested adding a new JN site and marking the `Save for later` check.

It does trigger the Tracks event:

CleanShot 2023-10-20 at 09 03 30@2x

The site credentials are saved and the site now appears in the destination site list in the `Copy this site` functionality:

CleanShot 2023-10-20 at 09 05 01@2x

Before merging, I will suggest to wait for @Automattic/jetpack-design feedback regarding the `Save for later` text.

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/9429792

Some locales (Hebrew, Japanese) have been temporarily machine-translated due to translator availability. All other translations are usually ready within a few days. Untranslated and machine-translated strings will be sent for translation next Monday and are expected to be completed by the following Friday.

Thank you @rustamshaikh for including a screenshot in the description! This is really helpful for our translators.

**Comment by jeffgolenski** [comment]
@rustamshaikh Tested! The placement looks good. I'd also recommend calling it "Remember credentials." - This verbiage implies that this specific creds config can easily be accessed again. 

Perhaps we can add an info icon to the right of the label "Remember credentials [i]" - upon hover we can offer a more verbose explanation: "Save this configuration so you can easily access it the next time you copy a site to staging" or something.

**Review by keoshi — APPROVED** [review]
Looks good!

Agree with you @rustamshaikh and @jeffgolenski: "Remember credentials" seems to carry the exact meaning we're trying to convey here and leaves no room for ambiguity.

Approving the PR since that's a minor change and everything else looks good.

**Comment by Initsogar** [comment]
> Perhaps we can add an info icon to the right of the label "Remember credentials [i]" - upon hover we can offer a more verbose explanation: "Save this configuration so you can easily access it the next time you copy a site to staging" or something.

@jeffgolenski this looks like a great idea! I think we can address it in a another PR if you prefer @rustamshaikh

**Comment by rustamshaikh** [comment]
Thanks, @jeffgolenski @keoshi @Initsogar for the review and suggestions 🙌 , it seems like a good idea to me as well. I agree with @Initsogar that we can address that info popover with an icon in a separate PR but I will update the text to `Remember credentials` in this PR itself.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/9429792).

**Pull request merged**
