### PR TITLE
Use thumbs-up gridicon for Recommendations in Reader sidebar

### LINKED ISSUE #3543: Reader: use thumbs up Gridicon for Recommendations
Current: 

screen shot 2016-02-24 at 3 32 51 pm

`<Gridicon icon="thumbs-up" />`

May I add this to the UI Nits milestone? Feel free to remove if you want.

cc @blowery

### PR DESCRIPTION
**Pull request by bluefuton**
Replaces the existing inline SVG with the `thumbs-up` gridicon.

The gridicon is a bit chunkier in appearance, but I think it works.

Fixes #3543.

Before:
screen shot 2016-02-25 at 14 51 27

After:
screen shot 2016-02-25 at 14 51 21

cc @drw158

### CODE REVIEW

**Comment by blowery** [comment]
:+1: ←yet a third thumb
:ship:

**Comment by blowery** [comment]
I wonder if we should consider http://matadornetwork.com/abroad/5-common-american-gestures-that-might-insult-the-locals/ ...

**Comment by blowery** [comment]
> The “thumbs up” sign was originally thought to have come from the Roman Coliseum, where the fates of gladiators were decided. Other studies suggest they come from WWII pilots signalling each other in the air. But wherever it derives, the positive “thumbs up” in Western cultures is a big no-no in other countries, such as Greece, Italy, and some throughout the Middle East. It’s essentially the equivalent of the middle finger, which is why you should keep your thumbs safely tucked away if you aren’t sure about the custom.

from http://www.ethos3.com/2014/07/dont-give-a-thumbs-up-in-russia-and-other-hand-gesture-facts/

**Comment by bluefuton** [comment]
Merging this for now (as it doesn't change the existing thumbs up) but we should definitely give some thought to localising or replacing the icon.

**Pull request merged**
