### PR TITLE
Reader: Remove batching through batcher

### PR DESCRIPTION
**Pull request by blowery**
The /batch API is currently broken when working with VIP sites, so instead of using it, just issue API requests directly. 

This still uses the post-batcher class, as it effectively dedupes post requests and it was simpler to re-use that logic than reimplement it.

Test live: https://calypso.live/?branch=fix/reader/remove-post-batcher

### CODE REVIEW

**Comment by blowery** [comment]
To test, compare https://calypso.live/read/blogs/64146350/posts/114293?branch=fix/reader/remove-post-batcher to https://wordpress.com/read/blogs/64146350/posts/114293 

Notice the new one doesn't 404

**Comment by blowery** [comment]
cc @bluefuton

**Comment by bluefuton** [comment]
As we're not actually batching any more, how painful would it be to rename to `postFetcher` or similar? Think the current name could potentially confuse those reading the code later.

**Comment by blowery** [comment]
Renamed to post-fetcher

**Comment by blowery** [comment]
@bluefuton This one could use another look

**Comment by bluefuton** [comment]
Looks good :ship:

**Pull request merged**
