### PR TITLE
Woo: Update product create action-list

### PR DESCRIPTION
**Pull request by coderkevin**
_This PR depends on the work in #15424._

This updates the product create action-list for use with the refactored
action-list code.

To Test:

1. Run `npm test`
2. Run `npm start`
3. Visit `http://calypso.localhost:3000/store/product/<site url>`
4. Fill out name
5. Add old and new categories
6. Click Save
7. Visit wp-admin to verify that the category and product have been created correctly.

### CODE REVIEW

**Comment by kellychoffman** [comment]
The save button continued to have a 'busy' style and I never got a success message. However, the category and product both showed up in the product list when I navigated away from the page.

**Comment by coderkevin** [comment]
@kellychoffman There was an issue where the action list wasn't being cleared after a success. It's been fixed now though. Mind testing again? Thanks!

**Comment by kellychoffman** [comment]
> There was an issue where the action list wasn't being cleared after a success. It's been fixed now though. Mind testing again? Thanks!

All set! Works now!

**Comment by coderkevin** [comment]
Thanks!

**Pull request merged**
