### PR TITLE
Plans: adds wordpress ad credit to business plan

### PR DESCRIPTION
**Pull request by rralian**
This PR adds the config, test, and proposed content for the WordPress Ad Credit project. This is a very simple version of the project where users gain the capability to boost a post or page of their choosing with 100,000 advertising impressions from our WordAds network. In this initial version we are handling the request manually with an email to a specific email address (which still needs to be set up) at automattic.com.

I am running this test as a _subtest_ of the Google Vouchers test, as this program makes the most sense as an additive feature on top of that one. You can see new content on the /plans, /plans/compare, and my-plan pages. Here is all of the new content.

### /plans
plans page

### /plans/compare
plans compare

### /plans/compare info popup
plans compare info popup

### my-plan/thank-you
my -plan

### mailto-triggered-email
mailto-triggered-email

## Testing
I am interested in feedback on the implementation and the copy. Once we're happy with this approach and copy, I will request the email address to be set up, and we can launch this. But it should not be launched ahead of setting up the email address and it should not be launched ahead of the google-vouchers project.

cc @apeatling @Essayoh @egill 

Test live: https://calypso.live/?branch=add/wordads-credit-feature

### CODE REVIEW

**Comment by lamosty** [comment]
Working for me :+1:

**Comment by Essayoh** [comment]
**my-plan/thank-you**
Copy suggestion:
`
Get more visitors to your most important Posts or Pages with our WordAds Boost. We'll display an ad for your site 100,000 times (a $100 value). Contact us at wordads-credit@wordpress.com to activate!
`
Why: 
- Changed the email address to more closely match the customer's understanding of who they're working with, and to avoid confusion in ongoing email conversations.
- Cut the reference to Business since they'll only see this if they already have Business, right? 
- Opened w/ benefit (more traffic) rather than feature (100k impressions)

**mailto-triggered-email**
I think this looks fine - I can see over time including more customer input (Date, the option to make it recurring, etc) but for a quick test this will work!

**Comment by apeatling** [comment]
Agreed on the wording changes from @Essayoh. Other than that, this looks good :+1:

**Comment by rralian** [comment]
I've updated the my-plans/thank-you page with @Essayoh's suggested changes (and updated the screenshot above).

This is all hidden behind a feature-gate. So merging this won't actually launch the feature yet. Can I get a 👍  to merge this in?

**Comment by apeatling** [comment]
Go for it

**Pull request merged**
