### PR TITLE
AnchorFM: Add theme names and screenshots

### PR DESCRIPTION
**Pull request by krymson24**
#### Changes proposed in this Pull Request

- Adds two themes to the AnchorFM onboarding experience

#### Testing instructions

1. Apply this diff D54416-code
2. Checkout this branch
3. Go to http://calypso.localhost:3000/new?anchor_podcast={anchor_podcast_id}
4. Enter a podcast name
5. The available design screenshots should match the Figma designs
6. Clicking on one of the available designs should take you to a preview of those designs

#### Outstanding Items (Questions noted in the issue)

Generally unsure of the approach here so I'm welcoming feedback

- [ ] Screenshots for these themes need to be reproduced when designs are finalized
- [x] Blog sticker needs to be applied per D54416-code
- [x] Categories for these themes need to be determined

#### Screenshots
Available Design Screenshots
Screen Shot 2020-12-16 at 7 58 41 PM

Design Preview
Screen Shot 2020-12-16 at 7 58 47 PM

Fixes 372-gh-Automattic/dotcom-manage

### CODE REVIEW

**Comment by ianstewart** [comment]
Font pairings …

- Gilbert Starter: Roboto/Roboto
- Riley Starter: Raleway/Cabin

@ollierozdarz cc @rickybanister  since these pairings aren't in the list any thoughts on introducing them into Gutenboarding conditionally? Or introducing a "default" pairing button? It would open up more variety for us in Starter Designs.

**Comment by krymson24** [comment]
> since these pairings aren't in the list 

@ianstewart which list are you referring to?

**Comment by mmtr** [comment]
> @ianstewart which list are you referring to?

Maybe this one?

https://github.com/Automattic/wp-calypso/blob/0f845ca13b1ee2a762a6d495c471a2af92f64fbd/client/landing/gutenboarding/constants.ts#L27-L48

**Comment by ianstewart** [comment]
Yep. That font pairing list.

**Comment by kwight** [comment]
> Blog sticker needs to be applied per D54416-code

What blog sticker is involved here? Do we need something else in D54416-code?

**Comment by kwight** [comment]
Let's leave this PR to adding the themes, and deal with updating the font pairings separately: 382-gh-Automattic/dotcom-manage

**Comment by ianstewart** [comment]
@kwight I believe that's the patterns source site blog sticker. Applied it yesterday.

**Comment by krymson24** [comment]
> Let's leave this PR to adding the themes, and deal with updating the font pairings separately: [382-gh-Automattic/dotcom-manage](https://href.li/?382-gh-Automattic/dotcom-manage)

@kwight I presume this means remove these font pairings from this PR?

**Comment by kwight** [comment]
>  I presume this means remove these font pairings from this PR?

@krymson24 Yes please, let's have anything related to font pairings happen in a separate PR tied to 382-gh-Automattic/dotcom-manage

**Comment by krymson24** [comment]
> > I presume this means remove these font pairings from this PR?
> 
> @krymson24 Yes please, let's have anything related to font pairings happen in a separate PR tied to [382-gh-Automattic/dotcom-manage](https://href.li/?382-gh-Automattic/dotcom-manage)

Removed

@ianstewart I guess I'll need to keep this PR open until we have the finalized designs, yeah?

**Comment by kwight** [comment]
> I guess I'll need to keep this PR open until we have the finalized designs, yeah?

They should only be active for the Anchor flow, which isn't in prod yet, so I don't think we should wait (we can do any screenshot updates later if needed).

**Comment by krymson24** [comment]
> > I guess I'll need to keep this PR open until we have the finalized designs, yeah?
> 
> They should only be active for the Anchor flow, which isn't in prod yet, so I don't think we should wait (we can do any screenshot updates later if needed).

Sounds good. Then this is good as is.

**Comment by krymson24** [comment]
I updated the screenshots so that the banner at the top of the site isn't shown.

For some reason, when I run the screenshot script, the screenshots for the new themes show the error message:

`Failed to retrieve demo site content`

However when go to the link `https://public-api.wordpress.com/rest/v1/template/demo/gilbert/gilbert?font_base=Open%20Sans&font_headings=Chivo&site_title=Gilbert` on my browser, with this diff sandboxed, I'm able to see the theme.

My workaround to update the screenshots were to hardcode the URL for the respective themes.

**Comment by kwight** [comment]
Paired with D54416-code, this works great (I kept getting the original images with the banner, but restarting Calypso fixed it up). Because it's D54416-code that ensures the font previewing works, let's not merge this until that one's in.

**Comment by kwight** [comment]
> My workaround to update the screenshots were to hardcode the URL for the respective themes.

They look good – same size and quality etc, so that's fine.

Oh, I noticed we also have a version number for [cache busting](https://github.com/Automattic/wp-calypso/blob/trunk/client/landing/gutenboarding/available-designs.ts#L40), but I don't think we need to update it since we're adding new, never-before-used images.

**Review by kwight — APPROVED** [review]

**Pull request merged**
