### PR TITLE
Importer: Revert to Business Plan

### PR DESCRIPTION
**Pull request by vishnugopal**
#### Proposed Changes

See https://github.com/Automattic/wp-calypso/pull/65784 and pdgrnI-1sK-p2#comment-2605 ns for revert.

#### Testing Instructions

Make sure both the Tools > Import workflow and the onboarding import workflow show the old Business plan.

CleanShot 2022-07-21 at 11 37 03@2x
CleanShot 2022-07-21 at 11 37 58@2x

### CODE REVIEW

**Review by bogiii — APPROVED** [review]
👍

**Review by ouikhuan — APPROVED** [review]
LGTM! 🚢

**Review by jimmy319 — APPROVED** [review]
LGTM 💯

**Comment by vishnugopal** [comment]
Most of these changes have been migrated upstream, so not merging this as it makes it easier to revert to Pro (in case that ever becomes a possibility). Tested and works in production now!

**Pull request closed without merging**
