### PR TITLE
Phase Out WordPress Blue From the UI

### PR DESCRIPTION
**Pull request by porada**
This is a graceful step towards the bigger set of color changes coming to Calypso in order to bridge the visual gap between marketing pages and our product. The idea is to possibly minimize the color jumps.

### Before and After

Screen Shot

Screen Shot

### Testing Instructions

* Pull the changes:
    * `git checkout update/blue`
    * `yarn`
* Run the SVG color audit script and make sure it doesn’t report any specific paths.
    * `node bin/audit-svg-colors.js`
* Preview the images listed by the command below (previewing locally should be enough) and make sure none of them throws any errors that would prevent them from displaying.
    * `git show HEAD~1 --name-only | grep 'svg$'`
* `yarn start`
* Open Calypso and make sure the master bar has a new color.
* Make sure the color scheme picker is using the updated thumbnails for Classic Blue and Classic Bright.

### Notes

* The illustrations will have to be handled in a separate PR.

### CODE REVIEW

**Comment by davewhitley** [comment]
Design looks great 👍 

I opened the live link and the design looks good.

**Comment by porada** [comment]
Thanks, Dave!

Calypso.live doesn’t seem to be working to me properly, but I guess it’s enough to preview the change anyway.

**Comment by rickybanister** [comment]
Looks good to me. Happy to head in the right direction. 

Where else might `WordPress Blue 50` be used, anywhere hidden? @ballio2000 any use of it on the LOHP?

@gwwar @sixhours any use of it in Calypsoify or places like that?

**Comment by porada** [comment]
Speaking of Calypso, Crowdsignal seems to be also using very dark WordPress Blue for the master bar. It’s hardly distinguishable from Blue 90 and Blue 100, but I didn’t wanted to touch it yet.

https://github.com/Automattic/wp-calypso/blob/d9576cacb77e7d1040fc9cbfe7dda1ee199de843/client/layout/masterbar/crowdsignal.scss#L4-L7

Apart from the above and the SVG illustrations I mentioned earlier, Calypso doesn’t have any other WordPress Blue references (other than for the WordPress.com brand color).

**Comment by ballio2000** [comment]
@rickybanister Nope. I did use `Blue 70` #0a4b78 for some backgrounds and text accent colors.

**Comment by gwwar** [comment]
@rickybanister Calypsoify styling is pretty old. (Has old blue styling from before the color theme changes in Calypso). I'd be more in favor of completely removing the CSS updates there on wp-admin vs trying to keep it up to date.

**Comment by porada** [comment]
@rickybanister @ballio2000, I don’t think we need to phase our WordPress Blue from our landing pages right away. We should aim for a clear guideline instead (like _avoid using WordPress Blue for XYZ)._

If a landing page is important enough, it will get updated soon anyway. Some of our marketing sites are still based on the pre-Recoleta visual identity, but that’s fine because they don’t get viewed too often.

**Comment by porada** [comment]
This visual change seems to have received internal design approval, so let’s move onto the proper code review.

* Rebased to a version of the master that uses the most recent version of Color Studio.
* Updated the SVG audit script to rule out WordPress Blue from the UI images and performed the changes (including the updates to the color scheme thumbnails).
* Updated the testing instructions.

**Review by lcollette — APPROVED** [review]
Looks great to me!

**Comment by porada** [comment]
@lcollette, thanks for the review!

---

Just to clarify:

> Updated the SVG audit script to rule out WordPress Blue from the **UI images**

These don’t include our illustrations. They’ll have to be handled separately (and probably when we have a more strategic plan on our colors).

**Pull request merged**
