### PR TITLE
Style selection: Add background/color transition to style preview

### PR DESCRIPTION
**Pull request by taipeicoder**
#### Proposed Changes

This PR injects CSS to add background/color transition to the theme preview. This is done with the intention of smoothening the style switching process. See recording for a reference of the transition effect:

https://user-images.githubusercontent.com/797888/192253442-67c9ead1-4b82-488a-ad59-b1999cfda94a.mp4

#### Testing Instructions

* Head to the design picker `setup/designSetup?siteSlug=${site_slug}`
* Ensure that the style switching process has a transition like demonstrated in the recording above.
 
#### Pre-merge Checklist

- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?

### CODE REVIEW

**Comment by autumnfjeld** [comment]
Oh nice! You are already on top of this. :).  I will update my comment here: pdtkmj-Ad-p2#comment-1026

OH.....just went to look at my comment.  Pablo wasn't very clear in what he meant: pdtkmj-Ad-p2#comment-1027is unfortunate.

**Comment by taipeicoder** [comment]
> Oh nice! You are already on top of this. :). I will update my comment here: pdtkmj-Ad-p2#comment-1026
> 
> OH.....just went to look at my comment. Pablo wasn't very clear in what he meant: pdtkmj-Ad-p2#comment-1027is unfortunate.

I think he was talking about this jump of height for the preview buttons, which we already fixed. I'll follow up with Pablo for more details.

**Comment by autumnfjeld** [comment]
Cool.  At any rate, I don't think any of this is priority.   Good to draw a line and start preparing for launch.

**Review by miksansegundo — APPROVED** [review]
Looking good 👍

**Comment by fushar** [comment]
Just saw this, looks good I'm crying 😭

**Pull request merged**
