### PR TITLE
Launchpad - Update launchpad domain upsell completion

### PR DESCRIPTION
**Pull request by agrullon95**
Related to #74416

## Test / Review Estimation

Test: Medium
Review: Short

## Proposed Changes

* Adds logic to update site option `launchpad_checklist_tasks_statuses` with new value `domain_upsell_deferred: true` when the user accesses the domain upsell flow and clicks the "Choose a domain later" link on the domains page. `domain_upsell_deferred` will be used to cross off the `Choose my domain later` task on the launchpad screen.

CleanShot 2023-03-30 at 16 37 41@2x

							

## Testing Instructions

* Checkout this branch
* Create a new free flow launchpad-enabled site
* Navigate to the launchpad screen and click the "Choose a domain" task.
* Click the "Choose my domain later" link on the domain selection screen. It should be on the right side of the screen.
* Verify the "Choose a domain" task is marked as completed on the launchpad screen

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

**Comment by edanzer** [comment]
@agrullon95 - This one doesn't seem to be testing as expected. I'm loading up this branch, going to http://calypso.localhost:3000/setup/free/intro to start a free site. When I get to Launchpad, I'm clicking Choose a Domain. One the domains screen, I'm choosing 'Choose My Domain Later'. I am redirected back to Launchpad, but the Choose a Domain task is still incomplete. It is basically behaving as before - I actually double checked everything to be sure I'm running the branch. 

From what I can tell consoling some output, it seems like the new call to saveSiteSettings() should be firing, but on Launchpad, the value of launchpad_checklist_tasks_statuses is still just an empty array. There's no value for domain_upsell_deferred from what I can see.

**Review by mattwiebe — APPROVED** [review]
This tests properly in combination with the endpoint. Tested on the free flow.

**Comment by agrullon95** [comment]
@edanzer - The jetpack PR with the logic that updates the `launchpad_checklist_tasks_statuses` option has been merged. You should be able to test these changes now. You no longer need to checkout the Jetpack PR.

**Comment by jeyip** [comment]
## Testing
### Requirements
- [x] Verify the "Choose a domain" task is marked as completed on the launchpad screen

### Browsers
- [x] Chrome

**Review by jeyip — APPROVED** [review]

**Pull request merged**
