### PR TITLE
Enable mobile app banners, and update deferred deep link

### LINKED ISSUE #16380: App Prompt: Add Deep Links
This is a follow up to https://github.com/Automattic/wp-calypso/issues/15228

We should also add the following deep links for the related sections. Take care to test Chrome on the native devices. Chrome is more stringent in how deep links may be opened. 

### Deep Links

All urls should have this format:

`intent://{host}/?{param1=x&param2=y}#Intent;scheme=wordpress;package=org.wordpress.android;end`

scheme: wordpress for all
host: viewpost, viewpost, etc
params: self-explainatory

Stats
host: viewstats
param: siteId=String

Reader
host: viewpost
params: blogId=String, postId=String

Editor
host: editor
params: siteId=String, postId=String

If either of these are empty we'll just open the editor I suppose(?)

Notifications
host: viewnotifications
params: notificationId=String

cc @kwonye

### LINKED ISSUE #16469: App Prompt: Add bump stats to mirror tracks events
Bump stats make it easier to track counts over time. Let's mirror the tracks events which are currently:
```
calypso_mobile_app_banner_impression
calypso_mobile_app_banner_open
calypso_mobile_app_banner_dismiss
```

### PR DESCRIPTION
**Pull request by gwwar**
Follow up to #15228 this closes #16469 and partially implements #16380.

This component will be shown on mobile devices for Editor, Stats, and Reader pages, or on any other page provided that Notification panel is open. Our goal here is to increase the number of native app downloads.

See also #16124, for the last PR

### Testing instructions
1. Use your physical Mobile device using this calypso.live branch: https://calypso.live/?branch=enable/app-banner
2. Visit the reader, stats, editor, and notifications
3. Banners should be visible and behave as expected.

In Desktop Chrome:
1. This banner should not be visible on any page in non-mobile browsers.
2. In order to test it, you can open up DevTools in Chrome and use `Toggle device toolbar`. Along making the screen size smaller, this will also change the `userAgent` which we use to test whether the app banner should be shown. Another option would be to select the `userAgent` manually in Chrome DevTools by following option 2 of [this guide](https://www.technipages.com/google-chrome-change-user-agent-string).
3. Verify that app banner is shown on stats, reader, and editor pages. It should also be shown on any page when notification panel is open.
4. Verify that correct text and icons are shown for each page as described in https://github.com/Automattic/wp-calypso/issues/15228.
5. Verify that impression tracks event has been recorded upon banner rendering.
6. Verify that `Open in app` redirects to app store and that appropriate tracks event/stat bump is recorded.
7. Verify that `No thanks` closes the banner and that appropriate tracks event/stat bump is recorded.

**_Note:_** If you've dismissed the widget and want to bring it back for testing in current session, you can run the following line in your console: 
```javascript
dispatch( { type: 'PREFERENCES_SET', key: 'appBannerDismissTimes', value: null } );
```

### Visual changes (stats example):

stats-example

### Expected Analytics Events:
You can see this by setting `localStorage.debug = 'calypso:analytics:*'`
screen shot 2017-07-21 at 3 27 14 pm

### CODE REVIEW

**Comment by gwwar** [comment]
Tested this in Nexus 5 + iPad. 

On Nexus 5:
- On android if the wp app is uninstalled we're taken to the play store
- If it is installed, it'll open the app to whatever section you last had open

For iPad:
- In Chrome/Safari if we don't have wp installed we're taken to the App store
- if it is installed, we're taken to the app store, where we can open it from that view.

**Comment by folletto** [comment]
Tested on iPhone 6 / Safari. Works well. 

img_2270

Just two minor things.

(1) Pure Nitpick: "No Thanks" alignment

`a.app-banner__no-thanks-button` should have a `line-height: 24px` so it gets aligned with the text of the button on the side. This can be seen in Chrome simulator too, not device specific.

(2) Small issue: landscape scroll

On landscape, when the address bar shows (it's dynamic), the buttons scroll out of view.... but they can be scrolled back up. It's not nice to see, but given the amount of space, layout, and likelyhood of that to happen, I'd say we can accept this unless there are stronger views on dealing with this differently.

img_2271

**Comment by hypest** [comment]
I ran some tests with older devices. Here are the results:

| Device&Browser | Android version | app uninstalled | app installed |
| ---------------- | ----------- | -------- | ---- |
| Chrome 51.0 / Lenovo  Tab2 | v4.4.2 | ✅ | ✅  |
| Chrome / Samsung S3 | v4.1.2 | live branch doesn't finish loading | same |
| "Internet" / Samsung S3 | v4.1.2 | ✅ (performs search instead of opening listing directly) | ✅ |
| Chrome 54.0 / Samsung S4 | v5.0.1 | ✅ | ✅  |
| "Internet" 4.0 / Samsung S4 | v5.0.1 | ✅  | ✅ |
| Chrome 38.0 / Nexus 7 2012 | v5.1.1 | ✅ | ✅  |
| Chrome 55.0 / Samsung S2 Tab | v6.0 | ✅ | ✅  |
| "Internet" 4.0 / Samsung S2 Tab | v6.0 | ✅  | ✅ |
| Opera 42.7 / Samsung S7Edge | v7.0 | ✅ | ✅  |
| Chrome 59.0 / Samsung S7Edge | v7.0 | ✅ | ✅  |

**Comment by gwwar** [comment]
@folletto updated line-height in bc24b42 and added an issue for the buttons being out of view. https://github.com/Automattic/wp-calypso/issues/16556

@hypest do you think we have good enough coverage here to 🚢 ?

**Comment by nheagy** [comment]
I tested on iOS and it looks great! I was wondering about having the "Open in app" button actually open the WordPress-iOS app, which should be possible, and @kwonye mentioned it's being worked on. 💯

**Comment by kwonye** [comment]
Verified this works on both iOS and Android, @gwwar.

For iOS, has there been any progress on the "hack" to implement both the app/app store?

**Comment by hypest** [comment]
> @hypest do you think we have good enough coverage here to 🚢 ?

I think so, yeah.

Wondering though (but I will let @kwonye make the final call on this), perhaps we want to limit the support only to Android versions v4.4 and above. Not sure about the current Calypso stats but, it seems that only 5% of the Android app's users are in Android versions below 4.4. In case we're interested in putting in this threshold, the Android version can be detected in the UserAgent string.

**Comment by gwwar** [comment]
> For iOS, has there been any progress on the "hack" to implement both the app/app store?

@kwonye Were the mobile teams not working on this? As I understand it deferred deep links are not supported natively in ios.

> perhaps we want to limit the support only to Android versions v4.4 and above. 

Sure @hypest, did you happen to have a good resource for the UA strings? I can update the regex.

**Comment by gwwar** [comment]
@hypest I've updated the regex so the banner shouldn't display on Android < 4.4

**Comment by kwonye** [comment]
> @kwonye Were the mobile teams not working on this? As I understand it deferred deep links are not supported natively in ios.

What I meant was the javascript "hack" that instagram does if the app isn't installed.

**Comment by gwwar** [comment]
I wasn't able to look too deeply since my debugger kept crashing in emulation mode while trying to step through.

**Comment by hypest** [comment]
> Sure @hypest, did you happen to have a good resource for the UA strings? I can update the regex.

I would probably point you to https://developer.chrome.com/multidevice/user-agent but it seems you have it already covered with addd3f7 so, 👍

**Comment by gwwar** [comment]
Unless folks had any objections, I'll land this today. Thanks for all the reviews and very testing @hypest @kwonye @folletto @nheagy !

**Pull request merged**
