### PR TITLE
Framework: remove sitesList dependency from analytics

### PR DESCRIPTION
**Pull request by gwwar**
Currently when we fire a tracks event, properties like `blog_id` and `blog_lang` are populated using SitesList. This PR removes the SitesList dependency from the library and introduces a new middleware so analytics can have access to this data. Due to the number of events that might trigger a user/site update, I've opted to pass through dispatch to this library. This allows analytics to fire a custom event that the middleware can handle.

Let me know your thoughts on this approach.

screen shot 2017-04-13 at 3 54 36 pm

### Testing Instructions
- in console, set debug to `localstorage.debug = 'calypso:analytics:tracks'`
- navigate to http://calypso.localhost:3000 events fire normally
- Click on my-sites, you should see a in redux devtools
screen shot 2017-04-13 at 3 59 08 pm
- tracks events should have the correct super props like `blog_id` and `blog_lang`
- switch to another site
- tracks events should have the new super props like `blog_id` and `blog_lang`
- in console calling `dispatch( { type: 'ANALYTICS_SUPER_PROPS_UPDATE' } )` will trigger the new middleware.
- other events (mc/google) are recorded normally.

### CODE REVIEW

**Comment by gwwar** [comment]
Thanks for the review @mcsf. I'll try a few more libs to see what patterns come out before writing a Readme.

I'll also spin up a WIP alternative approach later that updates the tracks interface and gets rid of `ANALYTICS_SUPER_PROPS_UPDATE`. Since no one is looking at the function return result, we should be able to just update the existing [analytics middleware](https://github.com/Automattic/wp-calypso/blob/master/client/state/analytics/middleware.js#L44) to pass through the extra data, and then update the existing usages to use the `recordTracksEvent` action. It'd be a much bigger diff though since there's at least ~200 usages that call analytics directly.

**Comment by dmsnell** [comment]
@gwwar what's the point of introducing a new action type just to set the site properties in analytics? what's the value over hooking into existing actions?

although I can see how we could get a big list of actions we're listening for (a middleware file with a hundred action types and the same handler) but it also seems like by introducing a new action type we'll just be scattering the same amount of code throughout Calypso.

does that make any sense?

**Comment by gwwar** [comment]
For folks reading, conversation continues here https://github.com/Automattic/wp-calypso/pull/13118#pullrequestreview-33144519

**Comment by dmsnell** [comment]
@gwwar at some point can we revisit this? I've recently remembered it when seeing tons of dispatches and I wonder if they are really necessary.

**Comment by gwwar** [comment]
@dmsnell Yes, folks are of course welcome to refactor further. This was meant to be a short term fix for ripping out sites list with the smallest chance of regression.

See one alternative in #13118

**Pull request merged**
