### PR TITLE
Calypso Green: add links to footer menu

### PR DESCRIPTION
**Pull request by IanRamosC**
See related issue

## Proposed Changes

* This PR updates the footer in Calypso Green to include links to the Affiliates program, Webinars, and testimonials pages.

|Before|After|
| ---|---|
|image|image|

## Why are these changes being made?

* This link is missing, so we are adding it to both jetpack.com and cloud.jetpack.com

## Testing Instructions

* Open the Calypso live link
* Visit `/pricing`
* Scroll to the bottom of the page until you see the footer
* Make sure "For Affiliates" is one of the links under "Partners", and "Webinars" and "Reviews and Testimonials" under "Help"

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Review by mikestottuk — APPROVED** [review]
LGTM - I wonder if we should bypass the localisation of the URLs for things like testimonials, where the content of the page is english and just send to the English version?

Not a blocker, but maybe something to consider, or a way to improve this page so it looks less like a 404 (or be automatically machine translated like the second link)

https://jetpack.com/es/webinars/

https://jetpack-com.translate.goog/webinars/?_x_tr_sl=en&_x_tr_tl=es&_x_tr_hl=en-GB

**Review by CodeyGuyDylan — APPROVED** [review]
Mike's idea for the testimonials page sounds logical, but not a blocker and functionally it works well, LGTM

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/14113758

Some locales (Hebrew, Japanese) have been temporarily machine-translated due to translator availability. All other translations are usually ready within a few days. Untranslated and machine-translated strings will be sent for translation next Monday and are expected to be completed by the following Friday.

Thank you @IanRamosC for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/14113758).

**Pull request merged**
