### PR TITLE
Add the Pressable promotion banner under the plans grid

### PR DESCRIPTION
**Pull request by southp**
## Proposed Changes

This PR implements the Pressable promotional banner under the pricing grid. For more context, please refer to p9Jlb4-9Dn-p2#comment-9916.

In general,
* Figma: Uzd0AYiDAV4eFq1V35T9Ef-fi . See the Multi-site section.
* The banner is only shown in `/start/plans` and only for the English locale since the translation isn't completed.
* Add two tracking events: `calypso_multisite_promo_banner_impression` and `calypso_multisite_promo_banner_cta_click`. Since there is a plan to show banners of other partners, they are defined as general events with a `service` prop. 
* Clicking on the CTA will lead to the corresponding Pressable landing page with UTM arguments suggested in https://github.com/Automattic/wp-calypso/pull/84636#issuecomment-1832746596 and the follow-up: https://github.com/Automattic/wp-calypso/pull/84636#issuecomment-1833222608. 
* The right copy of the banner can also be found in https://github.com/Automattic/wp-calypso/pull/84636#issuecomment-1832746596
* The banner is loaded asynchronously so it won't impact the bundle size of where it doesn't show.

### Media

Desktop:
image

Mobile:
image

## Testing Instructions

* Visit /start/plans in a English locale, the banner should show.
* Test out different resolutions, and make sure the banner is responsive according to the design.
* Expand/collapse the feature comparison table. The banner should stay at the bottom accordingly.
* Visit other flows, e.g. `/setup/newsletter`, `/start/launch-site`, `/start/domain`. The banner shouldn't show.
* Visit /start/plans in a non-English locale, the banner shouldn't show.

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

**Comment by southp** [comment]
TODO:

- [x] Replace the Pressable icon with a higher resolution version
- [x] Better responsiveness on mobile
- [x] The hover style of the CTA button
- [x] Clarify whether it needs to be an A/B test 
- [x] The impression event
- [x] The click event
- [x] Clarify where the banner should present

**Comment by jessfrick** [comment]
Thank you all for your hard work on this. May we please update the banner text to read: 

**Agency Hosting by Pressable**
Looking to manage multiple sites with ease? Discover Pressable's powerful and intuitive platform that goes beyond traditional WordPress hosting. Ideal for agencies and web professionals.

The URL will be: `https://pressable.com/multiple-site-solution/?utm_source=wpdotcom&utm_medium=referral&utm_campaign=pricing`

**Comment by southp** [comment]
Thanks for pitching in, @jessfrick . 
Regarding the link
> https://pressable.com/multiple-site-solution/?utm_source=wpdotcom&utm_medium=referral&utm_campaign=pricing

Given that we will expose this banner in the main signup flow here and various landing pages, e.g. https://wordpress.com/pricing . May I suggest that we change the `utm_campaign` here to `calypso_signup` or something like that? It's what we did for the VIP referral link, and we can gain a finer view to where the referrals are from :)

**Comment by jessfrick** [comment]
> Given that we will expose this banner in the main signup flow here and various landing pages, e.g. https://wordpress.com/pricing . May I suggest that we change the utm_campaign here to calypso_signup or something like that? It's what we did for the VIP referral link, and we can gain a finer view to where the referrals are from :)

That works, @southp. Thank you!

**Comment by ebinnion** [comment]
@southp - Is there anything blocking us from shipping as early as Friday?

**Comment by southp** [comment]
> Is there anything blocking us from shipping as early as Friday?

@ebinnion Thanks for checking in. I think I have everything I need so I aim to wrap it up the 1st thing today :)

**Comment by southp** [comment]
Given the deadline requirement, I'll be launching it soon without a review. Any follow-up feedback will still be much appreciated :)

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/9803095

Some locales (Hebrew, Japanese) have been temporarily machine-translated due to translator availability. All other translations are usually ready within a few days. Untranslated and machine-translated strings will be sent for translation next Monday and are expected to be completed by the following Friday.

Thank you @southp for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/9803095).

**Comment by niranjan-uma-shankar** [comment]
A minor UI bug, the CTA text color changes to blue upon clicking it.


https://github.com/Automattic/wp-calypso/assets/1269602/2011bd35-926d-40bf-94bd-5e6d5d6dcb90

**Comment by vinimotaa** [comment]
Hi folks, have we done [these changes](https://dotcomdesignp2.wordpress.com/2023/11/07/multi-sites-plans-for-agencies-and-pros/#comment-10057)?

**Comment by southp** [comment]
Just to close the loop for posterity here: The requested changes are completed by https://github.com/Automattic/wp-calypso/pull/84844

**Pull request merged**
