### PR TITLE
Reader: Fix Follow count and button wrapping in full-post

### PR DESCRIPTION
**Pull request by jancavan**
This fixes: https://github.com/Automattic/wp-calypso/issues/7424

If Follow count is high:

**Before:**
screenshot 2016-08-23 13 47 30

**After:**
screenshot 2016-08-23 13 46 55

If Follow count is low, both items remain in the same line:

screenshot 2016-08-23 13 52 10

screenshot 2016-08-23 13 52 15

/cc @bluefuton @fraying 

Test live: https://calypso.live/?branch=fix/reader/follow-count-button-wrapping

### CODE REVIEW

**Comment by jancavan** [comment]
@bluefuton In https://github.com/Automattic/wp-calypso/pull/7624/commits/0a9f5ccca0bdc4d0de293fe0f2097efc4defabbd, my editor seems to have redone the tabbing. It appears to be correct though, no?

**Comment by fraying** [comment]
Nice! 👍

**Comment by bluefuton** [comment]
>  In 0a9f5cc, my editor seems to have redone the tabbing. It appears to be correct though, no?

Hmm, editor seems to have redone the indents with spaces. I'll fix now.

**Comment by bluefuton** [comment]
Looks good @jancavan! 🚢

**Pull request merged**
