### PR TITLE
Trail Map: Provision for rendering grouped features in the Features Grid

### PR DESCRIPTION
**Pull request by chriskmnds**
Related to https://github.com/Automattic/wp-calypso/issues/89682
Based on https://github.com/Automattic/wp-calypso/pull/89840

## Proposed Changes

Implements the desktop and mobile (organically) functionalities for rendering grouped features in the Features Grid when the associated props are set. 

- This should handle the core functionality, with the right order shown in the Figma mocks. 
    - Styling fixes and some data restructuring will need to be done in a separate PR (see "Next/TODO" below).
- The data changes follow a similar route to the Comparison Grid - feature groups to be defined in `calypso-products`, each referring to a list of features and the plans having their associated flat list of features derived from the existing selectors
- The properties `renderCategorisedFeatures` and `featureGroupMap` are defined to control the behavior (setting `renderCategorisedFeatures` to `false` will work exactly like before.
    - These are set according to the `useTrailMapExperiment` hook
- No changes to the comparison grid, just pulling out the `featureGroupMap`. Comparison Grid should work like before.

This PR can be merged. Ideally, we will not need to touch much else on the grid components outside of styling fixes. The rest is down to feeding the right data. See Next/TODO below.

### No categories

Screenshot 2024-04-26 at 1 41 56 PM

### With categories

Screenshot 2024-04-26 at 1 41 25 PM

### Styling fixes
- Feature group titles
- Spacing
- Not sure what else

### Data structures

We need to provide the full list of features for each plan, not just the new ones. This will need to be done on condition, since the current data flows expect that each plan carries its new/unique features. We can do this in a couple of ways. Including (others possible too): 

1. Provide the full list of features for each plan from the plans-list selectors in `calypso-products`. This could be preferred if we want to reflect reality directly at the core data layer (and we can do something like call the previous plan's selector if we want to reduce redundancy). However, we will likely need a bigger cleanup in the end when the experiment flags are removed. We will also need a **likely small** refactor (now) in `use-restructured-plan-features-for-comparison-grid` to not re-compile the lists with `...previousPlanFeatures`.
2. Create/update the logic in `use-plan-features-for-grid-plans` to recompile the features like `use-restructured-plan-features-for-comparison-grid` does. This could be the fastest, as we will likely only need to pass a prop into the hook and copy/paste the same code across. The selectors from `calypso-products` will continue to provide the new/unique features for each plan.

So on the above, we can do `2` for now if it's fastest, and do `1` in the cleanup phase. 

## Testing Instructions

- Go to `/start/plans?flags=onboarding/trail-map-feature-grid` and confirm the media above. 
    - Features should be grouped and reordered to match the designs.
    - Confirm tablet/mobile that everything functions correctly
    - Confirm the table borders top to bottom that they are correctly rendered
- Go to `/start/plans?flags=-onboarding/trail-map-feature-grid` (flag disabled) and confirm the grid renders exactly like before. 

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Comment by chriskmnds** [comment]
@southp I've marked this PR as the main branch to close https://github.com/Automattic/wp-calypso/issues/89682

I'm not sure if that's correct, there are things that will have to be done in follow-ups (like feeding the right data, or some styling fixes), but the functionality described should be covered here. Feel free to correct this as you like.

**Comment by aneeshd16** [comment]
Rebased.

**Comment by aneeshd16** [comment]
#### Update

Changes in: https://github.com/Automattic/wp-calypso/pull/89650/commits/9234092af7f3f61377d3fd63ceb69caafc40f311

* Based on @chriskmnds suggestion, I have followed the 2nd method from the "Data Structures" section.
* Introduced a new prop, `includeAllFeatures` passed to `useGridPlansForFeaturesGrid`, which passes it further down to `usePlanFeaturesForGridPlans`.
* If the value of `includeAllFeatures` is true, the previous plan features are included, very similar to how it is done in `useRestructuredPlanFeaturesForComparisonGrid`.
* TODO: Currently, the free domain feature is shown as striked-out, and needs to be fixed. I ran out of time for today. 🤷 
* TODO: Styling changes.

calypso localhost_3000_start_plans_flags=onboarding%2Ftrail-map-feature-grid intervalType=yearly

**Review by oswian — APPROVED** [review]
Tests well for me  👍

**Pull request merged**
