### PR TITLE
Store: offer return label purchase

### LINKED ISSUE #1281: Print return label
902677zd

Customer writes:

> "Would you please add an option next to "Reprint" label button so we can also print return label for customer?
> 
> All it has to do is reversing the sender and receiver address and we can easily purchase return label for customer. And after purchasing return label, automatically email the label (pdf file) to the customer when we press the Update button. This is really important feature hope you implement it ASAP."

### PR DESCRIPTION
**Pull request by dechov**
Fixes https://github.com/Automattic/woocommerce-services/issues/1281

Requires https://github.com/Automattic/woocommerce-services/pull/1330

Label event in activity log has new action available:

screen shot 2018-03-09 at 11 38 50 am

Clicking opens modal, and return label rates are retrieving... (animated placeholder)

screen shot 2018-03-09 at 11 23 12 am

...and retrieved:

screen shot 2018-03-09 at 11 23 36 am

Click to purchase:

screen shot 2018-03-09 at 11 23 43 am

...after which new label appears in activity log, and print dialog pops up as well.

screen shot 2018-03-09 at 11 38 45 am

TODO:
- [x] Download instead of printing, and adjust button text: https://github.com/Automattic/wp-calypso/pull/23375
- Fix bug when rates response shows up after modal that triggered it is closed. Not strictly specific to the new behavior — will address in https://github.com/Automattic/wp-calypso/pull/23412
- [x] Fix tests failing due to rate selector refactor
- [ ] Feature flag, if https://github.com/Automattic/woocommerce-services/pull/1330 is necessary and not yet released

### CODE REVIEW

**Comment by dechov** [comment]
Implementation note: this approach takes advantage of the minuscule surface area afforded to label returns by the EasyPost API, by erring on the side of reuse: other than an action + reducer for opening the return dialog, existing state tree functions are used, as well as the rate selector and buy & print button, each extracted from its parent component into its own (state-connected) component module. It might help to generalize some action names and such.

**Comment by dechov** [comment]
I think either a better treatment for the "Create return label" link or a bigger overhaul of the label event is needed.

The only idea that's come to mind is moving the view details, refund, reprint, and return actions into an [`<EllipsisMenu>`](https://wpcalypso.wordpress.com/devdocs/design/ellipsis-menu), which would simplify the view and also support bringing back the icons that we used to have, at a reasonable size. This would also fix [a11y-related lint errors](https://github.com/evcohen/eslint-plugin-jsx-a11y/blob/master/docs/rules/anchor-is-valid.md) triggered by the anchor tags used as buttons in this component.

(In case we do revisit this design — do we need the tracking number itself rendered here, rather than just a link to track the package?)

cc @kellychoffman

**Comment by kellychoffman** [comment]
I don't think we need to redesign this quite yet. Let's keep what you have now. The only issue I see is the end of the flow is missing. Once something purchases the return label, how do they then send it off?

**Comment by dechov** [comment]
@kellychoffman We had considered the scope of the initial spike to just be giving the merchant the ability to download the label PDF so that they can email it to the customer.

That's not ideal of course, and we were going to look into giving the merchant the ability to send the return label automatically, possibly as an attachment to an order note sent to customer. If you think something like that is critical for initial release of the feature, we'll look into emailing the PDF on the merchant's behalf first. 👍 (Also, let us know if you have other ideas.)

**Comment by kellychoffman** [comment]
> We had considered the scope of the initial spike to just be giving the merchant the ability to download the label PDF so that they can email it to the customer.

Yeah, I think thats a good MVP as long as its clear that a PDF is being downloaded upon purchase. I just didn't see that as part of this PR, it seemed to stop at Purchase.

**Comment by dechov** [comment]
@kellychoffman I didn't make it totally clear from a glance, but this PR stops at "Buy & Print", re-using exactly the same mechanism as the ordinary label purchase flow, and https://github.com/Automattic/wp-calypso/pull/23375 is an enhancement that changes "Print" to "Download". For now, maybe we should add a little text to the dialog hinting at the expected next step: sending over the label so that the customer can print it.

**Comment by kellychoffman** [comment]
Is it possible to have this PR be a full flow? IE end it at a success message that pops up that says the label was successfully downloaded. I don't think the "Download" button text should be an enhancement, it should be part of this PR if possible. I'd also add instructional text to the dialog as you mentioned.

**Comment by dechov** [comment]
Yup, the download PR is branched off of this one and is the full flow,
except that the notice says "purchased" (same reason and same code as
ordinary purchase flow) rather than "downloaded" — this one will be as well
once the other is reviewed and merged into this branch.

**Comment by dechov** [comment]
Added text to dialog:
> You can purchase a return label for this package to send to the customer, who can then print it and mail the package back. (If necessary, the paper size can be changed later.)

Now it looks like:

screen shot 2018-03-26 at 5 53 54 am

Open to copy editing and other feedback, of course.

Also, the "view details" dialog is available for return labels now — it should be identical to the label that was returned.

**Comment by kellychoffman** [comment]
> If necessary, the paper size can be changed later.

Question: When can the paper size be changed? By the customer? 

Edited the text a little: 

> Purchase a return label for this package so your customers can easily return the item(s) purchased from you. Once created, you can send the label to your customer, where they can print it out and mail the package back. If needed, the paper size can be changed later by the customer.

**Comment by dechov** [comment]
@kellychoffman Ah, no, by the merchant — I do think it would be ideal to provide the option to the customer, with a "Print" button, but it would be a bit involved, and I'm not sure quite how it would work, and anyway it's out of scope for this PR.

If the merchant wants to purchase & download a return label for the customer, they might not be totally certain what paper size the customer would prefer to use, but the merchant shouldn't need to worry about it all that much since they can grab the same label again at a different size. _That's_ what I was trying to communicate with that line, but I'm not sure it's necessary.

**Comment by kellychoffman** [comment]
Got it. Makes total sense. Yeah, I say we drop the line. 

> Purchase a return label for this package so your customers can easily return the item(s) purchased from you. Once created, you can send the label to your customer, where they can print it out and mail the package back.

**Comment by dechov** [comment]
Merged in https://github.com/Automattic/wp-calypso/pull/23375. Fixed tests and a few issues with recent changes. Ready for review!

**Comment by kwight** [comment]
Looks like this will need a rebase and fresh test runs 👍

**Comment by dechov** [comment]
Will rebase and split into multiple PRs.

**Comment by alisterscott** [comment]
This branch needs a rebase. Do we still need this PR?

**Comment by v18** [comment]
@alisterscott  hey - yeh, this PR is on the backburner, but yes we'd like to continue to implement return labels.

**Comment by millerf** [comment]
@DanReyLop @dechov Is that still an ongoing thing?

**Comment by dechov** [comment]
I don't believe so but @c-shultz to confirm

**Comment by c-shultz** [comment]
I can confirm that there's no ongoing work or plans for this at this time.

**Comment by c-shultz** [comment]
I'll go ahead and close this. We can revisit this if it becomes a priority again.

**Pull request closed without merging**
