### PR TITLE
Reader: Gallery cards should skip featured_image if it is also in content

### PR DESCRIPTION
**Pull request by samouri**
post.images is the concatenation of featured_imaged + content_images.
if the featured_image is also in the content we don't want to show it twice in the card!
we essentially have the same fix in full-post

To test:
- [x] Compare galleries with dupes before + after. An example feed that has this is: https://wordpress.com/read/feeds/34575/posts/1267951350 and the post titled: 9To5Toys Lunch Break ...
- [x] Also make sure galleries aren't losing their first image when they aren't dupes.
- [x] Also make sure that fullposts aren't all of a sudden showing dupes
 
Fixes: https://github.com/Automattic/wp-calypso/issues/10184

### CODE REVIEW

**Comment by bluefuton** [comment]
> Also make sure galleries aren't losing their first image when they aren't dupes.

I have this happening on Colossal:

http://calypso.localhost:3000/read/feeds/7035081

On wpcalypso:

screen shot 2016-12-22 at 16 48 39

On this branch:

screen shot 2016-12-22 at 16 48 44

**Comment by samouri** [comment]
@bluefuton thanks for the catch!
I'll change CANONICAL_IN_CONTENT-->FEATURED_IN_CONTENT then this should work out

**Comment by samouri** [comment]
I decided to replace the `CANONICAL_IN_CONTENT` flag with a util function called `isFeaturedImageInContent`

**Comment by bluefuton** [comment]
Much prefer the `isFeaturedImageInContent` implementation 👍

**Comment by samouri** [comment]
I have one more bug to fix here.
If the featuredImage is contained in the contents, we want to remove the content version from the gallery and not the featured image.

Namely, we need to ensure the featured image is still displayed first in the gallery

**Comment by samouri** [comment]
Ready for review! A good test site is:
- https://calypso.live/read/feeds/6705117?branch=fix/reader/gallery-content-is-featured

**Pull request merged**
