### PR TITLE
Plugin Management: plugin details page enhancements

### PR DESCRIPTION
**Pull request by yashwin**
#### Proposed Changes

This PR makes some UI enhancements to the plugin details page.

#### Testing Instructions

**Prerequisites**

Since this change is made specifically for agencies, you must set yourself(partner) as an agency - 2c49b-pb. Make sure to switch it back to the previous type.

**Instructions**

1. Run `git checkout update/plugin-details-page-enhancements` and `yarn start-jetpack-cloud-p`
2. Open http://jetpack.cloud.localhost:3001/, and you'll be redirected to the /dashboard.
3. Click on **Plugins** in the sidebar -> Click on any plugin -> Verify that the plugin details are loaded as shown below. 

Before

Screenshot 2022-09-06 at 10 59 29 AM
Screenshot 2022-09-06 at 10 59 39 AM
Screenshot 2022-09-06 at 10 59 50 AM
Screenshot 2022-09-06 at 10 59 57 AM
Screenshot 2022-09-06 at 11 00 23 AM

After

Screenshot 2022-09-06 at 11 01 58 AM
Screenshot 2022-09-06 at 11 02 06 AM
Screenshot 2022-09-06 at 11 02 13 AM
Screenshot 2022-09-06 at 11 02 18 AM
Screenshot 2022-09-06 at 11 01 36 AM

#### Pre-merge Checklist

Complete applicable items on this checklist **before** merging into the trunk. Inapplicable items can be left unchecked.

The PR author and reviewer are responsible for completing the checklist.

- [x] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes? Will be added later - 1202518759611394-as-1202627702018877
- [x] ~~Have you tested the feature in [Simple](P9HQHe-k8-p2-p2), [Atomic](P9HQHe-jW-p2-p2), and [self-hosted Jetpack sites](PCYsg-g6b-p2-p2)?~~
- [x] Have you checked for TypeScript, React, or other console errors?
- [x] Are we memoizing when appropriate (for expensive computations)? More info in [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md) and [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors)
- [x] Have we sent any new strings [for translation](PCYsg-1vr-p2-p2) ASAP?

Related to 1202518759611394-as-1202698250096175

### CODE REVIEW

**Review by grbicsanja — COMMENTED** [review]
The fonts and sizes are looking good!
A few details to improve:

- Content should have max width and be centered just like in our other pages (for large screens)
https://user-images.githubusercontent.com/90194580/188594933-d412485e-2477-4f2a-a915-4d8763cdf11c.mov
- Vertical padding needs adjusting - I added the [missing specs now to the handoff page](https://www.figma.com/file/Dpa8Q3QQFde3DNnX6HoEfP/Agency-Plugin-Management-v.2---Enhancements?node-id=3095%3A52656)
Plugin detail page

- Row specs should follow similar spacing as on the plugin page

Screenshot 2022-09-06 at 11 17 50

- On 960 and mobile, the toggles should be aligned to the right but at a maximum distance of 300px
Screenshot 2022-09-06 at 11 22 37

**Comment by grbicsanja** [comment]
Updated the alignment of the description section
Plugin detail page

**Review by vitozev — COMMENTED** [review]
When I visit http://jetpack.cloud.localhost:3000/plugins/akismet

I noticed two issues:

**The overlay element is offset a bit**

image

**The plugin details container width**

image

Do we want to expand the container so it can take the full available width?

**Comment by yashwin** [comment]
@grbicsanja & @vitozev - Thanks for the review. I have addressed all the issues reported.

**Review by vitozev — APPROVED** [review]
LGTM!

**Comment by grbicsanja** [comment]
LGTM!

**Pull request merged**
