### PR TITLE
DocumentHead: Set Meta and Link (instead of appending)

### PR DESCRIPTION
**Pull request by ockham**
Replace `addDocumentHeadMeta` and `addDocumentHeadLink` by `setDocumentHeadMeta` and `setDocumentHeadLink`, respectively.

Just adding to them (without providing a clear/reset action) is error-prone as it can lead to duplication of `meta` and `link` tags -- right now, I'm seeing this in the Page Source for wordpress.com/themes:

image

This PR purports to fix that bug.

To test:
* Logged-out, check the Page Source for `http://calypso.localhost:3000/themes`. Compare to production, and make sure that no `meta` or `link` tags were lost (try Cmd+F `og:`)
* Same for a theme sheet, e.g. `http://calypso.localhost:3000/theme/mood`
* Unfortunately, I wasn't able to repro the original bug locally (I tried reloading `/themes` both logged-in and out), so I can't demonstrate that this PR fixes it. You'll have to trust the diff (but you can at least verify that it doesn't introduce any regressions.)

### CODE REVIEW

**Comment by aduth** [comment]
Maybe there's a middle-ground where setting would override any keys previous assigned, but doesn't necessarily replace the whole set of keys?

**Comment by ockham** [comment]
> Maybe there's a middle-ground where setting would override any keys of the same name previous assigned, but doesn't necessarily replace the whole set of keys?

I considered that, but then again I thought the most realistic use case would be to always provide the entire set of `meta`s (and/or `link`s) anyway...

**Comment by seear** [comment]
> the most realistic use case would be to always provide the entire set of metas (and/or links) anyway...

Is this true of all existing uses of `<DocumentHead />`? A quick grep suggests it is mostly used for `title` outside of /themes.

**Comment by ockham** [comment]
>> the most realistic use case would be to always provide the entire set of metas (and/or links) anyway...

>Is this true of all existing uses of `<DocumentHead />`? A quick grep suggests it is mostly used for `title` outside of /themes.

Right, I meant within the context of using `DocumentHead`'s `meta` and `link` (as opposed to `title`) at all.

**Pull request merged**
