### PR TITLE
NewsletterInto: fix backgrounds

### PR DESCRIPTION
**Pull request by heavyweight**
As reported [here](https://github.com/Automattic/wp-calypso/issues/75684) the pattern used for background in the intro step was not symmetrical.

Related to #75684

## Proposed Changes
- Fix and adjust the images on desktop and mobile

## Testing Instructions
- Visit the newsletter intro step using the PR link
- Check if the alignment is fixed

### CODE REVIEW

**Review by simison — APPROVED** [review]
How come 21% more bytes?

Anyway, let's 🚢

**Comment by simison** [comment]
Actually on closer look, something is looking blurry in bigger image — look at the edges, I see pixels:

Screenshot 2023-04-27 at 12 14 05

Smaller is fine:
Screenshot 2023-04-27 at 12 14 18

**Comment by simison** [comment]
There's another PR where we could do this as well https://github.com/Automattic/wp-calypso/pull/76323

**Comment by heavyweight** [comment]
> Actually on closer look, something is looking blurry in bigger image — look at the edges, I see pixels:
> 
> Screenshot 2023-04-27 at 12 14 05
> 
> Smaller is fine: Screenshot 2023-04-27 at 12 14 18

The images in the original design were huge and even blurry a bit. The images that we ended up using were the same ones but compressed to reduce their size.

**Pull request merged**
