### PR TITLE
Autoformat `client` with `prettier`

### PR DESCRIPTION
**Pull request by dmsnell**
Uses our custom build of prettier to auto-format existing files in the `client` directory.

If we are going to use `prettier` then I vote we _use_ `prettier`. This takes all of the incidental formatting changes out of future PRs dealing with code in `client`. If we have concern for git history then we simply need to use the button in Github to go back to the previous revision - no problem. It's there anyway in any git history.

How did I do this?
```bash
./node_modules/.bin/prettier --write client/**.js
./node_modules/.bin/prettier --write client/**.jsx
```

### CODE REVIEW

**Comment by blowery** [comment]
Interesting, bunch of formatting errors from lint I wouldn't expect. Too much indentation / mixed tabs and spaces.

**Comment by blowery** [comment]
cc @samouri

**Comment by gziolo** [comment]
> Expected indentation of 4 tabs but found 3  indent

It's a known issue. It always happen when you have multiline const declarations, where one of them is object or array with nested values.

**Comment by blowery** [comment]
> I'm sure if we would use the latest standard version of prettier we would avoid those kind of issues

😈

**Comment by samouri** [comment]
There are definitely a couple small bugs left in the prettier fork like the ones @gziolo has mentioned.  Even though `calypso-prettier` is flawed, I think its _less_ flawed than us humans trying to format our code nicely :).  We've been using it for all Reader files for the past couple of months and its been a super great DevEx ( @blowery and @bluefuton  can attest to that )

> I'm sure if we would use the latest standard version of prettier we would avoid those kind of issues

The biggest benefit of moving off of our fork is that we could stay in line with all of the upgrades that have been coming out to prettier.  Even though I made the initial fork I have no intention of doing the work to keep it up to date.

The fork is based off of v1.1 instead of what is now the latest version 1.4.  They've made pretty nice upgrades in that time period like: 
- smarter line breaking in a number of cases
- better IDE integration so you can format just a set of lines and also have your cursor remain in the same place
- ability to break up strings that are too long (`max-len` lint error)

**Comment by gziolo** [comment]
I executed prettier on `client/me/purchases` some time ago. Now I use it always when working with new files or updating smaller ones. Maybe we should update all folders but `client`. They are rarely updated and it should make rebase hell easier. Unless we can automate rebasing of all open PRs.

**Comment by dmsnell** [comment]
Too much clogging on my queue. Abandoning.

**Pull request closed without merging**
