### PR TITLE
Relocate organizations lists from left nav to right sidebar

### PR DESCRIPTION
**Pull request by davemart-in**
## Description

As a part of this larger project, we're pulling the "Automattic" and "Followed P2s" drop downs from the left nav and adding them to a new right sidebar.

### Before

before

### After

CleanShot 2022-12-05 at 13 37 58

## Notes

This PR builds off of the work in [this PR](https://github.com/Automattic/wp-calypso/pull/70667). There are a couple of related todos that I've listed out as separate PR's in the [parent issue](https://github.com/Automattic/wp-calypso/issues/67164):

- Add unread count back to followed sites list and update styles to fit in container
- move "Mark all as seen" to right sidebar header under organizations

## Related

#67164, #70667

### CODE REVIEW

**Comment by ollierozdarz** [comment]
@davemart-in I wonder if we should remove the 'Following ~a8c~' and 'Following ~p2~' to just keep it consistent across the screens?

**Comment by davemart-in** [comment]
@ollierozdarz, yep! Can do.

**Comment by davemart-in** [comment]
Update: I've found a bug where organization.id is undefined that I'm working through at the moment.

**Comment by eoigal** [comment]
Do we need to include a generic site icon when no icon is found? Either way, may need to fix the spacing when this happens.

Screenshot 2022-12-08 at 21 56 54

**Review by eoigal — APPROVED** [review]
WFM - spacing issue can be fixed in follow up

**Pull request merged**
