### PR TITLE
Implement the Logged out in-page CTA section

### PR DESCRIPTION
**Pull request by claudiucelfilip**
#### Proposed Changes
More info: pdgAPm-yE#comment-639-p2
Figma file: 2ea28-pb
This implements the in-page CTA section for Logged Out Plugins section. This is visible on `/plugins`.

#### Testing Instructions

* Log out
* Go to /plugins
* The in-page CTA section should be visible
Screenshot 2023-01-13 at 16 48 34
Screenshot 2023-01-13 at 16 49 03

* Makes sure that the CTA button points to the Business plan flow and that a `calypso_plugin_in_page_cta_click` event is triggered on click,

* Log in
* Go to /plugins
* The in-page CTA section should not be visible

#### Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

Related to #

### CODE REVIEW

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/7753834

Thank you @claudiucelfilip for including a screenshot in the description! This is really helpful for our translators.

**Review by paulopmt1 — APPROVED** [review]
It's working great! Tested on: Mobile, Desktop, Firefox, Chrome, Safari, and Edge. 
Showing only on /logout sessions.

Good job @claudiucelfilip!

### Mobile

image



### Desktop 

image

**Comment by vinimotaa** [comment]
@claudiucelfilip on mobile, can we reduce the image size so it follows the alignment below?

image

**Review by lupus2k — APPROVED** [review]
All look great in several browsers/devices. Good job 🚀

**Comment by claudiucelfilip** [comment]
> on mobile, can we reduce the image size so it follows the alignment below?
> 
> image

@vinimotaa The images should now fit within the boundaries.


Screenshot 2023-01-24 at 16 01 26

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/7753834).

**Pull request merged**
