### PR TITLE
Jetpack Plans: Persist the plugins status, display message if install is interrupted

### PR DESCRIPTION
**Pull request by ryelle**
A user can close the install screen/navigate away mid-install, and the process won't continue behind the scenes. This adds a `SiteNotice` telling the user they need to continue the install, with a link to the setup page.

Since the plugin status is tracked in the redux state, we'll persist that - then we can use the `isFinished` selector to see if the site was interrupted. Once the user goes back to the page, it refreshes the plugin instructions state, and runs the rest of the install process.

This PR also fixes a few issues with loading wp.com sites, and ensuring we can update files before attempting the install.

To test:

- Visit the auto-install screen, either by buying a plan and going through the flow, or by visiting `plugins/setup/$site` for an existing JP Premium or Business plan
- Try to close the tab, or click away to the Reader
- You should get a pop-up confirmation asking if you want to leave the page
- If you do confirm and leave, you should see a notice under the site asking you to finish the installation, like so:

screen shot 2016-06-07 at 4 52 30 pm

### CODE REVIEW

**Comment by ryelle** [comment]
cc @johnHackworth @roccotripaldi now that this is ready for review

**Comment by rickybanister** [comment]
Let's add something onUnload to ask if the user is sure they want to leave since we don't want to interrupt the install. 

Calypso settings does this if you have unsaved changes.

**Comment by ryelle** [comment]
Added a confirmation step:

screen shot 2016-06-07 at 4 47 23 pm

Also going to update the original description with testing instructions.

**Comment by ryelle** [comment]
The confirmation isn't working for the "click away to Reader" test case, working on that.

**Comment by rickybanister** [comment]
Cool, this looks helpful

**Comment by johnHackworth** [comment]
this is superb! works good and the code looks great :+1:

**Pull request merged**
