### PR TITLE
Test: Single test runner - a bit of tidying for client

### PR DESCRIPTION
**Pull request by gziolo**
Task done in this ticket for the `client` tests:
* Added missed test files to single test runner - @aduth I double checked all state folders and found two orphan files, all state test files execute properly in isolation (test file doesn't depend on another test file), yay :)
* Enabled reducer tests that were skipped by Mocha - @gwwar can you confirm that we can enable those tests? They pass so I assumed they should be enabled :)
* Moved non-test files to subfolders
* Got rid of warning Failed propType: Required prop `selectedSite` was not specified in `DomainWarnings` - @umurkontaci can you verify?

### Testing

To run: `npm run test-client`.

### Still to be done in another PR

We have 3 pending tests left. They look suspicious so I didn't play with them :)

When I use dot reporter: `npm run test-client -- --reporter=dot` I can see this message 3 times:
> double callback!

I didn't dig too much, but it looks like we see errors produced by Mocha.

Server also outputs some messages, but I left that for another PR.

### Execution time

Circle CI execution time is pretty random, but this PR finished quite nicely:

screen shot 2016-03-17 at 09 46 39

### CODE REVIEW

**Comment by umurkontaci** [comment]
I can review the PR tomorrow (very late in here), but afaik double callback means we're calling `done` more than once in an async test, which could be a code smell.

**Comment by umurkontaci** [comment]
re: isolation. What do you mean by isolation? Afaik the tests don't run in isolation from each other.

**Comment by gziolo** [comment]
> I can review the PR tomorrow (very late in here), but afaik double callback means we're calling done more than once in an async test, which could be a code smell.

:+1: 

> re: isolation. What do you mean by isolation?

I should say one test file don't depend on other test files. We had such issues before ...

**Comment by umurkontaci** [comment]
> Got rid of warning Failed propType: Required prop selectedSite was not specified in DomainWarnings - @umurkontaci can you verify?
:+1: Confirming the error is gone.

> I should say one test file doesn't depend on other test files. Like test files need to be loaded in a correct order to pass :) We had such issues before ...

Ah got it. :+1: 

on re: `double callback`:
I was wrong about blaming mocha; this is caused by `superagent` and when the request callback is called more than once. I do not know why it is happening but one instance I've found this happening is `before` hook on `posts/actions`.

Also, this needs a rebase.

**Comment by gziolo** [comment]
> on re: double callback:
I was wrong about blaming mocha; this is caused by superagent and when the request callback is called more than once. I do not know why it is happening but one instance I've found this happening is before hook on posts/actions.

Looks like something we should solve with general wpcom mock helper in another PR :)

I rebased this branch.

**Comment by aduth** [comment]
All tests pass for me. With regards to `skip` flags, my assumption is that they were likely skipped because there is no true schema for those reducers yet, so while the tests pass, they're not really testing the intended behavior (e.g. loading serialized data with invalid keys). Up to @gwwar if it makes sense to keep skipped. I might argue that it's nice to keep as an indication that the functionality is yet to be implemented.

Otherwise looking good :+1:

**Comment by gziolo** [comment]
> I might argue that it's nice to keep as an indication that the functionality is yet to be implemented.

We can also use `TODO` comment to mark it :) I'm leaving it up to @gwwar. I'm fine with any solution.

**Comment by gwwar** [comment]
@gziolo Sorry, I meant to quickly reimplement persistence on those sub-trees but never got around to it. Feel free to remove any skipped tests, they'll get stale anyway.

**Comment by gwwar** [comment]
I need to narrow this down further, but the `double callback` warnings are coming from `lib/posts/test/actions`, `lib/posts/test/post-list-store` and `post-editor/test/post-editor`

**Comment by gziolo** [comment]
@gwwar If you want to work on it, feel free to take over this PR. I'm happy to review later.
Otherwise I just remove tests marked as skipped, and merge this PR tomorrow :)

**Comment by gwwar** [comment]
The double callback warnings might take a bit of time to track down. Go ahead and remove the skipped tests and :ship:

**Comment by gziolo** [comment]
@umurkontaci @gwwar: I opened [follow up issue](https://github.com/Automattic/wp-calypso/issues/4206) for double callback warning.

**Pull request merged**
