### PR TITLE
Try: Run createClass codemod

### PR DESCRIPTION
**Pull request by sirreal**
This is the result of running:

```bash
jscodeshift -t "$REACT_CODEMODS/transforms/class.js" \
	--mixin-module-name=react-addons-pure-render-mixin \
	--pure-component=true --remove-runtime-proptypes=false \
	--extensions=js,jsx \
	client/ server/
```

### CODE REVIEW

**Comment by samouri** [comment]
I believe you need: `--extensions=js,jsx`

**Comment by sirreal** [comment]
Fixed it, much better. Thanks @samouri

**Comment by ockham** [comment]
Why not just use `bin/codemods/react-create-class`? 😄

**Comment by jsnmoon** [comment]
Heh, ditto Bernie. I merged in `bin/codemods/react-create-class` after making some upstream changes :)

Also, you might want to use `--mixin-module-name="react-pure-render/mixin"` instead :P

**Comment by sirreal** [comment]
Thanks everyone. It also looks like `i18n-mixin` codemod needs to be run first.

👋 

🏃  ➡️  🐰 🕳

**Comment by ockham** [comment]
> Thanks everyone. It also looks like i18n-mixin codemod needs to be run first.

Yeah, there's sort of a preferred order for those codemods. The `i18n-mixin` one in turn doesn't work with `require()`s, so you should make sure your codebase only comes with `import`s by running the `imports` codemod first...

**Comment by ockham** [comment]
Here's an example: https://github.com/Automattic/wp-calypso/pull/17111/files#diff-c3a0904478c30d1649fbf71254cf13c5

Note that `localize` isn't being imported (right now, that file will break). The `i18n` codemod looks for an `import` statement line to append its `import { localize } from 'i18n-calypso';` line to, so if there are only `require`s, it won't do that.

**Comment by sirreal** [comment]
This exploration has served its purpose. Thanks to everyone for the feedback which helped point me in the right direction 🙂

**Pull request closed without merging**
