### PR TITLE
Framework: Add .nvmrc file

### PR DESCRIPTION
**Pull request by seear**
Add an `.nvmrc` file with the correct Node version, for use by those that want to use nvm to manage Node installs.

For example, to install the correct version of node once `nvm` has been installed:
```
cd wp-calypso
nvm use
```

### CODE REVIEW

**Comment by aduth** [comment]
Where is there an `.nvmrc` file in the project?

**Comment by seear** [comment]
> Where is there an .nvmrc file in the project?

For those that want to use one, this will ensure it does't accidentally get committed.

**Comment by blowery** [comment]
I think we should just commit one

**Comment by seear** [comment]
> I think we should just commit one

Yeah, that is the logical conclusion of this PR, really. I'll change this PR...

**Comment by seear** [comment]
closing due to lack of interest.

**Comment by ockham** [comment]
Eventually added by #5233.

**Pull request closed without merging**
