### PR TITLE
Reader: add search to Cold Start

### PR DESCRIPTION
**Pull request by bluefuton**
This PR adds the ability for a new user to search for sites by keyword whilst in the Cold Start experience.

cs-search-default1
cs-search-results1

Test live: https://calypso.live/?branch=add/reader/search-to-cold-start

### CODE REVIEW

**Comment by bluefuton** [comment]
Todo: 
- [ ] add controller methods (onQueryChange, trackScrollPage)

**Comment by jancavan** [comment]
@bluefuton Sorry I just got a ping about this today. I can work on this in a bit if you're not on it already?

**Comment by jancavan** [comment]
In https://github.com/Automattic/wp-calypso/pull/7196/commits/21f9956719e20a84b8bc62727d90ac565323c5f3:

- Fixed Follow buttons not displaying in photo cards, fixed their colors as well
- Fixed Search bar not aligning with the cards

@bluefuton when you click follow from Search, it takes you to the full-post view. Ben mentioned adding`ignore-click`, but it seems like it's already in the search component itself so not sure where else to add it.

**Comment by bluefuton** [comment]
Thanks @jancavan! It looks great.

The `ignore-click` just needed adding in a wrapper around the primary follow button, which I've done in 7ba7a18.

**Comment by bluefuton** [comment]
Search cards with primary follow button:

screen shot 2016-08-04 at 13 51 29

**Comment by gibrown** [comment]
TrainTracks events look good. Tested and clicked around and looked at various events. Nothing jumped out as being wrong.

Did a quick code review and didn't see anything very surprising, but should probably have a review by someone more versed in Calypso than me.

**Comment by jancavan** [comment]
Ok I figured it out 😄  Added the subheading above the placeholder cards in: https://github.com/Automattic/wp-calypso/pull/7196/commits/d1750429ce9883c90c5a5bd96a8bd5684540dd92

**Comment by blowery** [comment]
Looking at this one.

Did we end up wanting a transparent follow button on photo cards, or a follow button with a white background?

**Comment by blowery** [comment]
the "or browse suggestions" header sticks around when the search results are showing. Should we hide it when Search is active?

**Comment by bluefuton** [comment]
> the "or browse suggestions" header sticks around when the search results are showing. Should we hide it when Search is active?

Good spot. Just needs to be wrapped in a `hasRecommendations && ! hasSearchQuery` conditional like the main `Masonry` block.

**Comment by jancavan** [comment]
> Did we end up wanting a transparent follow button on photo cards, or a follow button with a white background?

The cards in Cold Start have a transparent button on photo cards so I made them uniform. Discussed with @fraying just now as well and he gave the 👍

**Comment by blowery** [comment]
@bluefuton fixed the extra suggestion header in https://github.com/Automattic/wp-calypso/pull/7196/commits/c0635efe8645967a376eca933552de3971dc13a4

**Comment by blowery** [comment]
I'm happy with this. We want to launch it?

**Comment by bluefuton** [comment]
@blowery just going to tweak slightly - reckon we should show that subheading even if we don't have recs yet. Commit en route.

**Comment by bluefuton** [comment]
Done!

I'm happy to 🚀 if everyone else is happy.

**Comment by blowery** [comment]
Done.

**Comment by fraying** [comment]
I made some tweaks to the top-of-page text that aren't reflected yet. Can we update?

**Pull request merged**
