### PR TITLE
Jetpack Plans: Add a success notice after finishing plugins setup

### LINKED ISSUE #5703: Jetpack Plans: No next step after finishing the plugins configuration
1. Run through the plugins install & configuration process at `/plugins/setup/$site`.
2. Stay there forever, because we don't tell you what to do next.

@rickybanister has mocked up a Notice with action: https://cloudup.com/iChwFAsBf0t, which should link to `/plans/my-plan/$site` (which needs to be updated to work for a Jetpack plan).

### PR DESCRIPTION
**Pull request by ryelle**
Fixes #5703, so you're no longer trapped in the install/setup screen.

To test:

1. Run through the plugins install & configuration process at `/plugins/setup/$site`
2. When it finishes, you should see a green success notice that links you off to Insights.

Eventually this will link off to "My Plan" (see #5892)

~~Note: currently doesn't account for errors in setup, so if any fail, the process is still "done" and we show the success. Obviously not a great scenario, but can be fixed in a follow up PR.~~

screen shot 2016-06-08 at 12 51 02 pm

cc @johnHackworth @roccotripaldi @rickybanister 

Test live: https://calypso.live/?branch=add/plugins-setup-success

### CODE REVIEW

**Comment by rickybanister** [comment]
Yup, that sounds good for the time-being. Let's get some eyeballs on the auto-install process 👀

**Comment by ryelle** [comment]
Added a check for any errors, and if so, the message will be a different `is-info` notice:

screen shot 2016-06-08 at 3 57 12 pm

**Comment by ryelle** [comment]
Posted before I finished my thought, oops. I've removed the "Continue" link here because we want users to finish installing their plugins, and "Continue" in this context sounded like "try installing again". I'm open to adding it back in, though.

**Comment by roccotripaldi** [comment]
This is awesome! LGTM

**Pull request merged**
