### PR TITLE
Reader: move post comments to Redux

### LINKED ISSUE #967: Reader: hide replies initially for threads with lots of comments
Raised by @bluefuton 

@shaunandrews suggested that we hide comments initially when loading a thread with more than around 15 comments in it. 

The user should see a link showing the number of replies (e.g. "3 replies"):

86a3c2c4-02f1-11e5-9edd-b20bbb0f1128

...along with a link in the open state to hide them again:

906503b8-02f1-11e5-8eaf-12d660359351

Originally suggested on 5842-gh-calypso-pre-oss

### PR DESCRIPTION
**Pull request by bluefuton**
This PR moves post comments in the Reader to use Redux state instead of Flux stores.

It builds on the work done by @samuelclemens in #3528.

Fixes #967 and #2839.

### CODE REVIEW

**Comment by bluefuton** [comment]
To do:
- [ ] when posting a new comment, the relative post date is a bit eager. If the comment requires moderation, the time resets from "1s ago" to "0s ago". We should probably say "just now" if it's been less than a minute. Video: https://cloudup.com/cl7dnN0kSJz

**Comment by bluefuton** [comment]
Hi @jancavan - would you mind checking this PR please and letting me know if you have any further feedback? As far as I can see, everything discussed on the original PR (#3528) has been addressed.

**Comment by blowery** [comment]
I think we should just show replies when there's less than 5. Having to click a thing to get in when there's only a couple replies is really a bummer.

**Comment by blowery** [comment]
Clicking on the Comments icon in a post card doesn't scroll you down to the comments any more

**Comment by lancewillett** [comment]
@mtias Meta-question: can `State` label be a milestone instead? Why can't we use `Framework` instead?

**Comment by jancavan** [comment]
> I think we should just show replies when there's less than 5

+1

Can "Cancel reply" be moved to the right instead of in between Reply and Like?
f875359c-ea9d-11e5-8a82-b5fc7ef4268b

The root comments are ordered chronologically (oldest -> newest), but the nested replies are in a odd order:
http://calypso.dev:3000/read/feeds/23059853/posts/922262993#comments

**Comment by bluefuton** [comment]
More todo from @jancavan:
- [ ] Fix ordering of nested replies
- [ ] Move 'cancel reply' to the right

**Comment by bluefuton** [comment]
> Clicking on the Comments icon in a post card doesn't scroll you down to the comments any more

This functionality was originally added in #2058, so worth checking there to see what the regression might be.

**Comment by bluefuton** [comment]
Nested replies are now shown in chronological order, which matches the behaviour of the existing Reader comments.

**Comment by bluefuton** [comment]
- [ ] Comment reply input doesn’t return to top level after successful comment posting

**Comment by bluefuton** [comment]
The downside of ordering the nested replies chronologically is that, when you post a new comment on a thread, it appears at the bottom. This might mean it's out of view - see https://cloudup.com/ccyrBzfU4y8

We fudge this on the existing Flux comments by always putting the new comment at the top of the replies. This often isn't its final position - it moves downwards after a reload if there's more than one reply.

Three possible solutions here:
- sort nested replies in reverse chronological order (same as top-level comments) - easiest solution
- fudge comment order so that user's reply always appears at top
- scroll to and highlight newly posted comment

Thoughts @jancavan @blowery?

**Comment by jancavan** [comment]
> sort nested replies in reverse chronological order (same as top-level comments) - easiest solution

What we're doing now - where we slide your new comment in topmost (and it just shows up at the bottom after a refresh) is actually good. Only reason I brought it up thought was I noticed that the nested replies were neither in chronological/reverse chronological order. It somehow was arbitrary, but I'm unable to reproduce the issue :/

**Comment by bluefuton** [comment]
> Only reason I brought it up thought was I noticed that the nested replies were neither in chronological/reverse chronological order.

Could it have been that the replies weren't all at the same depth, but they were flattened out by the indentation limit (so they all appeared at the same indent)? That caught me out a couple of times yesterday :)

**Comment by bluefuton** [comment]
> What we're doing now - where we slide your new comment in topmost (and it just shows up at the bottom after a refresh) is actually good

Great - happy to stick with that. I've made the change in a7bc448.

**Comment by bluefuton** [comment]
Ready for 👀  @blowery @jancavan

**Comment by jancavan** [comment]
@bluefuton the nested replies beginning 3rd level become really confusing with the blue bar. Let me play around with the styling.

**Comment by blowery** [comment]
@jancavan maybe we collapse the commenting levels based on viewport width? Desktop browsers with lots of room see the full nesting and folks on narrower viewports see less and less?

**Comment by jancavan** [comment]
> Desktop browsers with lots of room see the full nesting

I think that's a good idea to allow more nesting on desktop, but we should still set a limit. Infinite nesting doesn't really work anymore after several levels deep.

I've made changes here (https://github.com/Automattic/wp-calypso/pull/4817/commits/d21884dadc33bd1c6f66625da268e20e22747909) which helps, but could be made better if we changed the show/hide icon: https://cloudup.com/cA4DzdYEWCV

This isn't great, however, since after 3rd-level indentation, the hierarchy is still off: http://calypso.dev:3000/read/feeds/23059853/posts/939824593#comments

Another solution (but is out of scope): Just allow comments to be expandable, but not collapsible. This also allows for proper hierarchy.

screenshot 2016-04-21 11 27 00

Sidenote: I believe this is old code, but I poked at this branch and the gravatar is positioned `absolute` which shouldn't really be the case as it makes the css hard to maintain. Changing the positioning values would have to be done in many different places.

**Comment by blowery** [comment]
rebased this and force pushed it

**Comment by blowery** [comment]
Still needs to auto-expand the next level when it contains 5 or fewer replies. 
Jump to comment from the comment icon on the post card appears to be busted again.

**Comment by blowery** [comment]
Hmmm, might be on the wrong sha.

**Comment by blowery** [comment]
Force pushed again to pick up latest. 

Looks really good. Really really good.

**Comment by blowery** [comment]
This moved to #5236

**Pull request merged**
