### PR TITLE
Reader Tags: making titles capitalized + exception list

### PR DESCRIPTION
**Pull request by samouri**
Testing out a couple of ideas:
1. title-case tag titles
2. maintain a set of exceptions...how many are there?
   - WordPress
   - iPhone
   - etc...

fixes: https://github.com/Automattic/wp-calypso/issues/9781

### CODE REVIEW

**Comment by samouri** [comment]
Current exception list:
```javascript

const titleExceptions = {
	wordpress: 'WordPress',
	vaultpress: 'VaultPress',
	videopress: 'VideoPress',
	iphone: 'iPhone',
	ipad: 'iPad',
	ios: 'iOS',
	macos: 'macOS',
	tvOS: 'tvOS',
}
```

**Comment by aerych** [comment]
Is this something that could be done from the API.  The tag's `display_name` field seems very well suited for this, and it would help keep the other clients consistent with the web if we could all pull from the same field.

**Comment by samouri** [comment]
@aerych, I agree!  This would definitely be much better solved at the API level.
I'll look into it

**Comment by aerych** [comment]
Thank you @samouri !!

**Comment by samouri** [comment]
Closing because we decided that https://github.com/Automattic/wp-calypso/issues/9781 was too much a can of worms to chase at this point.

**Pull request closed without merging**
