### PR TITLE
reader streams reduxification: selectors

### PR DESCRIPTION
**Pull request by samouri**
split out from https://github.com/Automattic/wp-calypso/pull/22814

Steps taken:
1. Moved `getDistanceBetweenRecs ` from the `Stream` React Component into a util fn
2. Created a few new selectors and wrote tests for most of them. They cover similar functionality to what is currently happening within the `getStateFromStores` fn currently in the Stream component.

**to test**
The only change to live code was moving `getDistanceBetweenRecs ` function. So to test:
- [ ] run unit tests for new selectors
- [ ] make sure you still see the right number of recs in your following stream.

### CODE REVIEW

**Review by blowery — CHANGES_REQUESTED** [review]
Selectors should be broken out to `client/state/selectors/` as per our data guidelines.

**Comment by samouri** [comment]
For the record: I think the global selectors directory isn't particularly helpful and makes development more difficult by requiring us to split into significantly more files than common sense would indicate.  This is especially true for selectors with no chance of ever being reused across sections.

**Comment by blowery** [comment]
For the record, I agree.

**Review by blowery — APPROVED** [review]
Nice.

**Pull request merged**
