### PR TITLE
Scheduled Updates: implement multi-site design on single site scheduled updates

### PR DESCRIPTION
**Pull request by TimBroddin**
Related to [#90401](https://github.com/Automattic/wp-calypso/issues/90401)

## Proposed Changes

Implements the design language of the multi-site design for single site scheduled updates.

CleanShot 2024-05-08 at 15 04 46@2x
CleanShot 2024-05-08 at 15 04 57@2x
CleanShot 2024-05-08 at 15 05 07@2x
CleanShot 2024-05-08 at 15 12 03@2x
CleanShot 2024-05-08 at 15 05 26@2x

## Testing Instructions

Try this out  on Calypso Live

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Comment by JanaMW27** [comment]
This looks good to me, minus one mino thing, in Calypso we don't use Recoleta for the headlines. On site specific we should use the non-recoleta typography.
Thannkkkkuuuuuuuuu

**Review by ouikhuan — COMMENTED** [review]
- It feels like the heading in multi-site level is too large now. (compare with other A4A items like /sites) Also the text on multi-site level and site specific level is different. It shows "Update schedules" on mulitsite level and "Scheduled Updates" on site specific level.

Screen Shot 2024-05-10 at 4 13 04 PM

- Should we align the text on `New schedule` and `Add new schedule` too?
- There's no margin for the save button on the site specific level page now, could we add some margin to it?
Screen Shot 2024-05-10 at 4 18 12 PM

**Comment by TimBroddin** [comment]
> * It feels like the heading in multi-site level is too large now. (compare with other A4A items like /sites) Also the text on multi-site level and site specific level is different. It shows "Update schedules" on mulitsite level and "Scheduled Updates" on site specific level.

My preference would be to change Update schedules to Scheduled Updates on multisite then. On single-site we already show "Scheduled Updates" in the menu, and it would be a bigger change to update the menus there. Also "Scheduled Updates" does ring a little bit better in my eyes. What do you think @ouikhuan?

> Screen Shot 2024-05-10 at 4 13 04 PM
> 
> * Should we align the text on `New schedule` and `Add new schedule` too?

I'll change it to New Schedule on single site too. 

> * There's no margin for the save button on the site specific level page now, could we add some margin to it?
>   Screen Shot 2024-05-10 at 4 18 12 PM

👌

**Comment by ouikhuan** [comment]
> Also "Scheduled Updates" does ring a little bit better in my eyes. What do you think @ouikhuan?

Sounds good, thanks!

**Review by ouikhuan — APPROVED** [review]
Looks good to me, thanks for addressing the feedback!

**Pull request merged**
