### PR TITLE
Site Transfer: improve the action panel style

### PR DESCRIPTION
**Pull request by sejas**
- Related to https://github.com/Automattic/wp-calypso/pull/77216

## Proposed Changes

* Remove the overflow hidden for all the `action-panel__body`
* Add space below the form for site transfer panel

## Testing Instructions

- See testing instructions on https://github.com/Automattic/wp-calypso/pull/77216
- Test other `.action-panel__body` to confirm they still looking good. E.g. `/settings/start-over/{$siteSlug}`

## Screenshots

| **Before** | **After** |
|---|---|
| Screenshot 2023-05-24 at 12 12 22 | Screenshot 2023-05-24 at 12 11 27 |

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

**Comment by danielbachhuber** [comment]
Let's hold off on this for now. The form implementation will change in a future issue.

**Comment by sejas** [comment]
> Let's hold off on this for now. The form implementation will change in a future issue.

This PR is against your other PR.

**Comment by danielbachhuber** [comment]
> This PR is against your other PR.

I know, but the `overflow: hidden;` was added for some specific reason previously. I don't want to wade into why that was, test all uses of the component, etc.

**Comment by sejas** [comment]
> I know, but the overflow: hidden; was added for some specific reason previously. I don't want to wade into why that was, test all uses of the component, etc.

A safer approach would be to apply that CSS rule only for our Site Transfer component.

**Comment by katinthehatsite** [comment]
> A safer approach would be to apply that CSS rule only for our Site Transfer component.

@sejas if you have the time to do this before Daniel merges his PR, let's go ahead and add it just to the Site Transfer component to not affect other implementations.

If not, I think @danielbachhuber can go ahead and merge his PR without these changes since the form will need some redesign later anyways.

**Comment by danielbachhuber** [comment]
I localized the styles for now.

**Pull request merged**
