### PR TITLE
Composer: Upgrade deps for composer 2

### PR DESCRIPTION
**Pull request by sirreal**
Upgrade composer dependencies.

I have composer 2 installed, one of our composer packages is incompatible with it. Upgrade that composer package and upgrade our composer deps.

Previously, I was hitting issues with `yarn dev` from `apps/editing-toolkit-plugin`:

```
[dev:newspack-blocks               ] done
[dev:newspack-blocks               ] phpcbf: ./bin/sync-newspack-blocks.sh: line 132: ../../vendor/bin/phpcbf: No such file or directory
[dev:newspack-blocks               ] !! There was an error executing phpcbf!
```

I could not `composer install` becuase:

```
Your lock file does not contain a compatible set of packages. Please run composer update.

  Problem 1
    - dealerdirect/phpcodesniffer-composer-installer is locked to version v0.6.2 and an update of this package was not requested.
    - dealerdirect/phpcodesniffer-composer-installer v0.6.2 requires composer-plugin-api ^1.0 -> found composer-plugin-api[2.0.0] but it does not match the constraint.
```

#### Testing instructions

I'm not sure how many places use composer, but `yarn dev` under `apps/editing-toolkit-plugin` should work after this change.

### CODE REVIEW

**Comment by noahtallen** [comment]
I pushed a tiny readme change to the editing toolkit plugin. That way we can see if the CI tools which rely on this package work! If that passes, this looks great to me

**Review by noahtallen — APPROVED** [review]
LGTM :shipit:

**Comment by noahtallen** [comment]
Note: the phpunit failure is a separate issue

**Comment by ockham** [comment]
Thanks for reviewing, Noah!

> I pushed a tiny readme change to the editing toolkit plugin. That way we can see if the CI tools which rely on this package work! If that passes, this looks great to me

Shall we revert that change, or keep it? :smile:

**Comment by noahtallen** [comment]
> Shall we revert that change, or keep it? 😄

we can keep it, just a tiny grammar/style improvement 😁

**Comment by sirreal** [comment]
> Note: the phpunit failure is a separate issue

So this is safe to ignore, @noahtallen?

> > Shall we revert that change, or keep it? 😄
> 
> we can keep it, just a tiny grammar/style improvement 😁

Noting that I have no intention of releasing Editing Toolkit for this markdown change, but this should be completely safe to release with other changes.

**Comment by noahtallen** [comment]
> Noting that I have no intention of releasing Editing Toolkit for this markdown change, but this should be completely safe to release with other changes.

Absolutely, I would not have expected you to :) 

> So this is safe to ignore

Yes, it would have been. I believe the issue has been fixed over the past several days, so after a rebase I would expect it to pass now.

**Comment by sirreal** [comment]
Rebased.

> > Noting that I have no intention of releasing Editing Toolkit for this markdown change, but this should be completely safe to release with other changes.
> 
> Absolutely, I would not have expected you to :)

That was for posterity or someone handling a release, didn't intend to direct it at you 😆

**Comment by sirreal** [comment]
Attempting to fix the tests: #47766

**Comment by sirreal** [comment]
The phpunit tests are not a quick fix and are not introduced here. I'll merge.

**Comment by noahtallen** [comment]
Phpunit tests fixed in #47979

**Pull request merged**
