### PR TITLE
Build: check if Calypso is running before regenerating shrinkwrap

### PR DESCRIPTION
**Pull request by gwwar**
If Calypso is running `make shrinkwrap` may fail. This PR checks to see if Calypso is running on port 3000 before we attempt to shrinkwrap. 

## Testing Instructions
- call `make run`, wait until you can visit a page
- in another tab call `make shrinkwrap`
- the shrinkwrap should fail with a message for you to stop Calypso
- Stop Calypso
- `make shrinkwrap` should succeed

cc @aduth @rralian @lamosty

### CODE REVIEW

**Comment by aduth** [comment]
Awesome! I've been thinking about this while I was out grabbing dinner, and this seems like a clever way to capture the running process. Will take it for a spin shortly...

**Comment by aduth** [comment]
Confirmed that this is effective in stopping `shrinkwrap` if (and only if) the Calypso process is running.

I got to playing around to try to more accurately determine that it's Calypso listening on the port. This alternative at least checks that it's `node` running on port 3000:

```diff
diff --git a/Makefile b/Makefile
index 9332097..6f4e2cf 100644
--- a/Makefile
+++ b/Makefile
@@ -190,7 +190,7 @@ githooks-push:
 
 # generate a new shrinkwrap
 shrinkwrap: node-version
-       @! lsof -Pi :3000 -sTCP:LISTEN -t || ( echo "Please stop your Calypso instance running on port 3000 and try again." && exit 1 )
+       @if [ "node" = "$$(lsof -Pi :3000 -sTCP:LISTEN -t | xargs -I % ps % -o comm=)" ]; then echo "Please stop your Calypso instance running on port 3000 and try again." && exit 1; fi;
        @type shonkwrap || ( echo "Please install shonkwrap globally and try again: 'npm install -g shonkwrap'" && exit 1 )
        @rm -rf node_modules
        @rm -f npm-shrinkwrap.json
```

Either way, this is a nice improvement and I'd love to see it shipped 🚢

**Comment by lamosty** [comment]
Tested on Ubuntu 16.04 and `make shrinkwrap` is interrupted if Calypso is running :+1:.

**Comment by gwwar** [comment]
> I got to playing around to try to more accurately determine that it's Calypso listening on the port. This alternative at least checks that it's node running on port 3000

Thanks! Let's stick with the shorter one for now, and if we run into trouble with that we'll swap it out for the stricter check.

**Comment by gwwar** [comment]
Thanks for reviews @lamosty @aduth !

**Pull request merged**
