### PR TITLE
Checkout: Move analytics for redirect payment methods into payment processors

### PR DESCRIPTION
**Pull request by sirbrillig**
#### Changes proposed in this Pull Request

Because of the way in which composite checkout payment methods have evolved, all of the work, including recording analytics, has historically been inside the payment method object's submit button. Since payment method objects were originally defined inside a package outside of calypso, the `useEvents` hook was added to the package as a means to arbitrarily record analytics.

More recently, the responsibility for processing a transaction has moved to the payment processor functions. Since the payment processor functions already live inside calypso, they don't need the leaky abstraction of `useEvents` and can record analytics directly. This PR alters the redirect payment methods to move the analytics into the processor functions. Ultimately this will make the processor functions (and composite checkout as a whole) more flexible.

#### Testing instructions

To test, we should first make sure that each payment processor still works, but also that its analytics are recorded. To do this run `localStorage.setItem('debug', 'calypso:analytics')` in your browser console and reload the page before completing checkout. Verify that you see events for `calypso_checkout_form_redirect`, `calypso_checkout_form_submit`, `calypso_checkout_composite_form_submit`, and `calypso_checkout_composite_X_submit_clicked` (where `X` is the payment method id).

Since all these payment methods use the same payment processor function, they will all need to be tested in this one PR.

- WeChat: see https://github.com/Automattic/wp-calypso/pull/43765
- NetBanking: see https://github.com/Automattic/wp-calypso/pull/44952
- IdWallet: see https://github.com/Automattic/wp-calypso/pull/45257
- EbanxTef: see https://github.com/Automattic/wp-calypso/pull/44752
- Sofort: https://github.com/Automattic/wp-calypso/pull/43710
- P24: https://github.com/Automattic/wp-calypso/pull/43744
- Ideal: https://github.com/Automattic/wp-calypso/pull/43162
- Giropay: https://github.com/Automattic/wp-calypso/pull/43598
- Eps: see https://github.com/Automattic/wp-calypso/pull/43734
- BanContact: see https://github.com/Automattic/wp-calypso/pull/43651
- Alipay: see https://github.com/Automattic/wp-calypso/pull/43653
- PayPal: https://github.com/Automattic/wp-calypso/pull/46431

We also need to verify that the `calypso_checkout_composite_error` fires if there is an error in the analytics code. To test this, add something like `throw new Error('testing');` into `recordTransactionBeginAnalytics` inside the `try` block. Then try to complete any redirect payment method transaction and verify that you see `calypso_checkout_composite_error` fired.

### CODE REVIEW

**Comment by nbloomf** [comment]
For each method I checked the behavior and fired analytics events for the following scenarios: (1) analytics error, (2) payment failure, (3) payment success. (Except paypal, which doesn't simulate failures.) I saw a couple of minor unrelated issues, but the analytics part is 💯

I did notice that successful purchases redirected to the account level billing page, instead of either a thank-you page or the site level billing page.

- WeChat: ✅
- Netbanking: ✅ (tested both return and expire failures). 
- IdWallet: did not test since this is not enabled
- EbanxTEF: ✅
- Sofort: ✅ * The analytics worked as expected. However, and I'm not sure if this was a legit bug or just my sandbox being slow, the redirect after a successful purchase seemed to get stuck and not provision the purchase or generate a receipt. (This is moot because sofort is disabled for non a12s.)
- P24: ✅  Worked great except for some warnings that the p24 event names were invalid. I pushed a commit to add them to the list of exceptions.
- Ideal: ✅  Worked great except for some warnings about class names in the ideal logo SVG. I pushed a commit to fix these.
- Giropay: ✅
- EPS: ✅
- Bancontact: ✅
- Alipay: ✅
- PayPal: ✅

**Review by nbloomf — APPROVED** [review]

**Comment by sirbrillig** [comment]
Wow, you tested all of these! Amazing. Thank you. I had planned on splitting it up but this is much appreciated.

> I did notice that successful purchases redirected to the account level billing page, instead of either a thank-you page or the site level billing page.

🤔 ... Does this seem any different from production, do you think? I imagine not, in which case we might want to check to see if there are any regressions in `getThankYouPageUrl` (probably not the function itself which is pretty well covered by tests, but perhaps in the code which provides its arguments).

**Comment by nbloomf** [comment]
> Does this seem any different from production

I just verified that the same behavior happens on trunk; whatever is causing that seems to be unrelated to this PR.

**Comment by nbloomf** [comment]
Here's an extra piece of information for when we're debugging the redirect issue - while testing something unrelated I was redirected to the concierge upsell page after a paypal txn (as expected). Whatever is causing the goofy redirect seems to be neutralized if the user is in the `offer` bucket of `conciergeUpsellDial`.

**Pull request merged**
