### PR TITLE
Show happychat button only for paid jetpack users

### PR DESCRIPTION
**Pull request by unDemian**
## Summary
Currently if you select a free plan jetpack site in the help section dropdown happychat will be available. This PR updates that behavior sending only customers with a paid jetpack site selected to JPOP operators.

## Implementation
- Add `isCurrentPlanPaid` check for jetpack sites. 

## Testing steps
1. Setup 2 jetpack site in your account, one with paid plan and one with the free plan. (get some pressable ones search updateomattic for Would you like a Pressable Account?)
2. In HUD set your operator to only accept JPOP
3. Go to `help/contact` page
4. Select the free jetpack site -> Email form should be displayed
5. Select the paid jetpack site -> Happychat button should be available.

### CODE REVIEW

**Comment by dllh** [comment]
Hmm, I can't make the chat UX appear. I'm testing with a Business plan and logged into the JPOP group.

**Comment by unDemian** [comment]
> This code only adjusts the group based on free/paid, so that Free Jetpack sites will still be able to access Happychat but just in the WPCOM group. Make sure your operator is available in both the WPCOM and JPOP groups to show this.

That was the intended behavior, maybe my description was not good enough but I just wanted to fix the routing of free jetpack users to JPOP operators. If the customer has a WP.com paid account Happychat should be available.

**Comment by dllh** [comment]
> Free Jetpack sites will still be able to access Happychat but just in the WPCOM group

This shouldn't be the intended behavior. WP.com availability shouldn't be affected by this at all.

**Comment by omarjackman** [comment]
I added the `needs author reply` label because @dllh [mentioned](https://github.com/Automattic/wp-calypso/pull/15906#issuecomment-314086251) something that might change things here after @unDemian removed it 😄

**Comment by unDemian** [comment]
> This shouldn't be the intended behavior. WP.com availability shouldn't be affected by this at all.

Chat availability is not tampered at all, this PR only addresses the routing to JPOP operators.

> Free Jetpack sites will still be able to access Happychat but just in the WPCOM group

Happychat will be available only if the customer has a WP.com paid plan. If the customer has only a Jetpack free email form will be displayed.

**Comment by dllh** [comment]
I tested this a bit with a few users. I had one weird scenario in which a user who owned (but was somehow I think not a member of) a JP plan site didn't get chat when I was available only in the JP group, but I think that's a weird/edge case.

I think that to test this (and similar things) appropriately, we may need to run through a list of users something like the following, toggling group availability (no availablility, availability in both, and availability in only one group or the other) and selecting each of the site types for each user with each group availability to make sure the thing is behaving as expected. I wonder if that's something we can figure out how to write tests for, as it's pretty gnarly to test manually. I did not test all of these cases, but the several I did test, other than as noted above, worked as expected and the code looks good. 

User with only JP and no plan
User with only JP and a plan
User with JP plan and WP site (no plan)
User with JP plan and WP plan
User with only WP and no plan
User with only WP and a plan
User with WP plan and JP site (no plan)
User with WP plan and JP plan
User with WP and JP and no plan
User with AT and JP plan
User with AT and JP (no plan)
User with AT and other WP plan
User with AT and WP (no plan)

I had a moment of thinking alongside Matt that this code (even without your change) would cause non-plan users to be eligible for chat, but I believe it's the case that we never even get to this check until we've already disqualified such users. In other words, I think the API endpoint we check for overall eligibility prevents those users from having access to chat, and once we get to loading this code, we already know they're eligible and we're just deciding what group to put them in.

This actually makes me wonder if we could simplify by removing the initial `if` and just checking for Jetpack and plan (the diff's second condition) and falling back to wpcom as the default. That's not a change I'll insist on. I think that if you feel confident we're introducing no regressions here, we should :ship:, and that we should think a little bit about whether there's any way to automate testing of those scenarios, as it's only going to get more complex going forward, and unpredictability of changes was one of our big pain points when we were using a different chat service.

**Comment by unDemian** [comment]
Thank you for taking the time.

> This actually makes me wonder if we could simplify by removing the initial if and just checking for Jetpack and plan (the diff's second condition) and falling back to wpcom as the default. That's not a change I'll insist on.

The thing is that an AT site is also a jetpack site and I think it also has a paid plan so we would go back to the issue of sending AT users to JPOP operators. Even if that is not the case I would like to keep AT as a separate condition case just to be aware of the fine distinction between AT and Jetpack.

**Comment by unDemian** [comment]
>  we should think a little bit about whether there's any way to automate testing of those scenarios

I guess we could mock those sites combinations in some integration tests and check what operators group is targeted. Looking over the tests I notice that they were failing because I did not update the tests 😄

**Comment by mattwondra** [comment]
> Happychat will be available only if the customer has a WP.com paid plan. If the customer has only a Jetpack free email form will be displayed.

Ah, I apologize. I'm not really clear on the difference between "free Jetpack plan" and "free WP.com user". I created a Pressable account with a JetPack plan but no WordPress.com upgrades so I assumed this meant I should not be seeing Happychat. But it sounds like that wasn't the logic in question anyways. :+1:

**Pull request merged**
