### PR TITLE
Pages: Fix line height when wrapping lines in info div

### PR DESCRIPTION
**Pull request by mcsf**
Not observable in English, but `/pages` looks broken in other locales:

<table>
<tr><td><strong>Before</strong></td><td><strong>After</strong></td></tr>
<tr><td>
screen shot 2017-04-13 at 19 03 26
</td><td>
screen shot 2017-04-13 at 19 10 04
</td></tr>

### CODE REVIEW

**Comment by folletto** [comment]
That's a bit messed up overall:

screen shot 2017-04-13 at 19 20 02

This patch improves it a bit tho :y:

**Comment by folletto** [comment]
I did some changes:

1. Extracted BlogPostsPage's CSS to be cleanly separated from Page's (it's a separate component)
2. Now the CSS uses `flex`: avoids a whole set of alignment problems.

screen shot 2017-04-13 at 19 58 50

screen shot 2017-04-13 at 19 59 26

cap-

**Comment by marekhrabe** [comment]
I trust you both, but CircleCI is against you. 

This is the output of lint: 

```
/home/ubuntu/wp-calypso/client/my-sites/pages/blog-posts-page.jsx
  68:11  error  className should follow CSS namespace guidelines (expected pages__ prefix)  wpcalypso/jsx-classname-namespace
  68:64  error  Use localize( ReactComponent ) instead of this.translate                    wpcalypso/i18n-no-this-translate
  70:41  error  className should follow CSS namespace guidelines (expected pages__ prefix)  wpcalypso/jsx-classname-namespace
  71:10  error  className should follow CSS namespace guidelines (expected pages__ prefix)  wpcalypso/jsx-classname-namespace
  72:11  error  className should follow CSS namespace guidelines (expected pages__ prefix)  wpcalypso/jsx-classname-namespace
  73:9   error  Use localize( ReactComponent ) instead of this.translate                    wpcalypso/i18n-no-this-translate
  75:11  error  className should follow CSS namespace guidelines (expected pages__ prefix)  wpcalypso/jsx-classname-namespace
  78:10  error  Use localize( ReactComponent ) instead of this.translate                    wpcalypso/i18n-no-this-translate
  79:10  error  Use localize( ReactComponent ) instead of this.translate                    wpcalypso/i18n-no-this-translate
  85:13  error  className should follow CSS namespace guidelines (expected pages__ prefix)  wpcalypso/jsx-classname-namespace

✖ 10 problems (10 errors, 0 warnings)
```

We should address this before merging, otherwise we have a red master 🔴

**Comment by folletto** [comment]
> I trust you both, but CircleCI is against you.

The file is old. I did the changes without refactoring the entire file which would be a far more massive change. If we need to change the entire file to fix the above this PR becomes a bit of an headache. :|

Is that the only way forward?

> className should follow CSS namespace guidelines (expected pages__ prefix)

Btw, I don't get this. It _does_ start with `pages__`. Why is it reported?

**Comment by folletto** [comment]
Miguel fixed the translate one.

Meanwhile I found https://github.com/Automattic/eslint-plugin-wpcalypso/blob/master/lib/rules/jsx-classname-namespace.js#L262 — which seems not allowing for two `__` in the classname.

This seems odd, as BEM allows composition of `--` and `__`, so having two is a possible, and valid, variant.

Plan:

1. I will refactor this PR to avoid that, I don't want to keep it hanging for this reason
2. I will make a PR on https://github.com/Automattic/eslint-plugin-wpcalypso with the change

**Comment by folletto** [comment]
Ok, now CircleCI is happy. Review?

**Comment by marekhrabe** [comment]
You rock! Let's 🚢 it so the world can see it too!

**Comment by folletto** [comment]
Change of plan, after a review the BEM rule shouldn't change, and I'll move the component out so it can get proper SCSS block name.

**Comment by marekhrabe** [comment]
Change looks good to me - probably a good idea to get it its own namespace. Feel free to go for it once we are green :)

**Comment by folletto** [comment]
Ok, I had also to convert to ES6 to avoid even more linter errors, and that created a chain reaction of changes. I think I have all sorted now. 💧

**Comment by marekhrabe** [comment]
Go for it! 🚢 :shipit:😎

**Pull request merged**
