### PR TITLE
Design Picker: Enable signup/design-picker-unified flag

### PR DESCRIPTION
**Pull request by arthur791004**
#### Proposed Changes

* Enable `signup/design-picker-unified` flag to ship the UDP to production

#### Testing Instructions

* Go to `/setup`
* Select one of the following intents
  * Write & Publish
  * Promote myself or business
  * Sell online
  * Other
* Select any vertical
* When you land on the design picker, you have to see the Unified Design Picker and everything works as expected.

See pdtkmj-h8-p2 for more details

#### Pre-merge Checklist

- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?

Related to https://github.com/Automattic/wp-calypso/issues/64998

### CODE REVIEW

**Comment by bangank36** [comment]
Should we mention the Sell flow in the description? Since it still have the UDP (with no generated designs though)

**Comment by roo2** [comment]
It looks like this individual theme purchase change will need to be ported to the UDP https://github.com/Automattic/wp-calypso/pull/66279

**Comment by arthur791004** [comment]
@roo2 No, that feature has already implemented in https://github.com/Automattic/wp-calypso/pull/66187

**Comment by roo2** [comment]
oh yes, sorry I see 👍

**Review by roo2 — APPROVED** [review]
LGTM! I tested main flows, and reviewed git logs for unmerged changes

**Comment by arthur791004** [comment]
@bangank36 added!

**Comment by autumnfjeld** [comment]
From this convo, I take it translations are not ready? p1660212373791649/1660208966.414699-slack-CRWCHQGUB

@arthur791004  Just wanted to check if this PR should limit release to English only -- or if you have confirmed translations are complete.   Thank you. :)

**Comment by arthur791004** [comment]
The translations are ready! See p1660632138730939/1660208966.414699-slack-CRWCHQGUB 🎉

**Pull request merged**
