### PR TITLE
eslint: upgrade to 1.10.3

### PR DESCRIPTION
**Pull request by blowery**
Move to 1.10.3 and 3.11.3 of the react plugin

To test, run `make lint` and it doesn't break

### CODE REVIEW

**Comment by sirbrillig** [comment]
Should we fix the lint-reported errors in this PR also? 

eg: 
```
diff --git a/client/lib/preferences/test/actions.js b/client/lib/preferences/test/actions.js
index 730ffc4..55ea30a 100644
--- a/client/lib/preferences/test/actions.js
+++ b/client/lib/preferences/test/actions.js
@@ -98,7 +98,7 @@ describe( 'PreferencesActions', function() {
 			} );
 		} );
 
-		it( 'should not dispatch an empty local store', function() {
+		it( 'should not dispatch an empty local store', function( done ) {
 			store.get.restore();
 			sandbox.stub( store, 'get' ).returns( undefined );
 
```

**Comment by blowery** [comment]
> Should we fix the lint-reported errors in this PR also?

Yes, have to, as they break the build. I was just pushing this up to track the breakage. Should have marked it `In Progress`, but ... yeah.

**Comment by sirbrillig** [comment]
I fixed a pile of them. The few remaining I'm not sure about (not sure how to use `notices` correctly since the refactor and I'm guessing maybe `tinymce` is global?).

**Comment by sirbrillig** [comment]
ping @codebykat for the tinymce errors: 
/home/ubuntu/wp-calypso/client/components/tinymce/plugins/wpcom-charmap/charmap.jsx
  309:61  error  "tinymce" is not defined  no-undef

/home/ubuntu/wp-calypso/client/components/tinymce/plugins/wpcom-charmap/plugin.js
  49:2  error  "tinymce" is not defined  no-undef

**Comment by ehg** [comment]
> tinymce is global

Yep. It's attached to the `window` object when the editor is loaded/pre-loaded.

**Comment by sirbrillig** [comment]
Ping @deBhal for the translator `notices` reference:

```
/home/ubuntu/wp-calypso/client/layout/community-translator/invitation-utils.js
  166:5  error  "notices" is not defined  no-undef
```

**Comment by nylen** [comment]
Fixed up the editor charmap in c415e0f.

**Comment by nylen** [comment]
The notices fix looked simple enough too (`require( 'notices' ).error` is used in lots of places).

I think this is good to go :+1:

**Comment by sirbrillig** [comment]
:shipit:

**Pull request merged**
