### PR TITLE
Redux: remove SERVER_DESERIALIZE

### PR DESCRIPTION
**Pull request by budzanowski**
`SERVER_DESERIALIZE` after #8785 will not be needed at all. See discussion in #9788.

This needs to go after #8785. Before push to master rebase and and check that `SERVER_DESERIALIZE` is not used anymore. This will happen when following reducers will not be used anymore: `theme-details`, `themes-list`, `themes`.

Be careful.  
Question: will switching to `SERIALIZE` in `initial-state` will not cause any troubles? How data is stored locally? With change to `SERIALIZE` from `SERVER_DESERIALIZE` we will trigger action in far more place.

### CODE REVIEW

**Comment by ockham** [comment]
Rebased.

**Comment by ockham** [comment]
> Question: will switching to `SERIALIZE` in `initial-state` will not cause any troubles? How data is stored locally? With change to `SERIALIZE` from `SERVER_DESERIALIZE` we will trigger action in far more place. 

Isn't it just one more place, `state/initial-state`?

**Comment by budzanowski** [comment]
So the question is is this safe?
when we have `SERVER_DESERIALIZE` only stuff that was designed to use it( 0 cases now ) would be triggered. But now with just `DESERIALIZE` everything will be triggered.

**Comment by ockham** [comment]
To expand on my previous comment -- It's only run on `initialReduxState` there, and that currently holds only the `document-head`, `ui`, and `themes` subtrees. We know that it works for `themes`, so all we need to check is the other two.

**Comment by ockham** [comment]
Rebased.

**Comment by ockham** [comment]
Played a bit with Redux Devtools. Looking good so far, so let's 🚢 tomorrow.

---

One thing this PR unearthes is that state re-hydration (i.e. serializing on the server side, including serialized state as a JS var in the page source, deserializing in the client) possibly doesn't seem to work reliably: in Redux Devtools, the `@@INIT` state is mostly just the default initial state. E.g. only on a theme sheets is `themes.queries` pre-populated with the currently viewed theme. This is probably also the explanation for the content flash we get with offline `/design` -- `queries` is empty. 

(So this is something we'll need to investigate subsequently.)

**Comment by ockham** [comment]
^ Ct'd in #10432

**Pull request merged**
