### PR TITLE
Remove "beta testing" item from the menu for all users

### PR DESCRIPTION
**Pull request by zaguiini**
#### Changes proposed in this Pull Request

Following the discussion on #56312, we want to remove the "beta testing" item from the menu.

This is the Calypso part of it. The WPCOM part is merged and deployed, which means that we do not see `Beta testing` on `/wp-admin` anymore.

Since Jetpack is only going to be deployed on 2021-11-02, it makes sense to remove only the menu item and keep the page.

#### Testing instructions

Open a site on WP.COM and check that the "beta testing" menu is gone. Verify you can still access it via the `/beta-testing/` page on any site.

Part of #56312.

### CODE REVIEW

**Comment by Copons** [comment]
Given the ideal behaviour of the beta testing screen as described in pd2n8V-90-p2#comment-279, I think could just hide it instead of deleting it altogether.

For example, what about keeping it in `development` (local) environment only, or showing it only to a12s. 🤔 

@vindl do you have an opinion on this?
I have a tendency of hoarding old code indefinitely in case it might turn out to be useful in the future (it never happens 😄), but I guess if we want to restore the screen we could just simply revert this PR.

**Comment by vindl** [comment]
> For example, what about keeping it in development (local) environment only, or showing it only to a12s. 🤔

I don't see much use for this except to confuse people further.

> @vindl do you have an opinion on this?
I have a tendency of hoarding old code indefinitely in case it might turn out to be useful in the future (it never happens 😄), but I guess if we want to restore the screen we could just simply revert this PR.

I think it's better to delete it than to leave dead code around (potentially indefinitely). We are not sure if the work on the proper beta will be prioritized and when. In any case, we'll still have the deleted code in revision history and we can bring it back if needed.

**Comment by claudiucelfilip** [comment]
This PR, together with D68088-code, should properly remove the menu item and the page for Simple Sites. 
On Atomic sites, however, these changes won't take effect until an upcoming Jetpack release (which will include the D68088-code changes). Until then, the `Beta Testing` item will still be visible, but will now point to a missing page.

With this in mind, I'd suggest we keep the page and only remove the menu item. We can then remove the page after the Jetpack release. Or, we can set up a redirect from `/beta-testing`.

**Comment by zaguiini** [comment]
> This PR, together with D68088-code, should properly remove the menu item and the page for Simple Sites. On Atomic sites, however, these changes won't take effect until an upcoming Jetpack release (which will include the D68088-code changes). Until then, the `Beta Testing` item will still be visible, but will now point to a missing page.
> 
> With this in mind, I'd suggest we keep the page and only remove the menu item. We can then remove the page after the Jetpack release. Or, we can set up a redirect from `/beta-testing`.

Hey @claudiucelfilip,

The idea is to merge the Jetpack PR first, along with the WPCOM release, and then merge this PR at the end. Does that make sense?

**Comment by creativecoder** [comment]
@zaguiini It looks like Jetpack users won't receive the change from https://github.com/Automattic/jetpack/pull/21332 until the next release, on Nov 2nd. So they'll continue to see the Beta Testing menu item until then. If we remove the page from Calypso now, it looks like they'll see "Page not found" when they click on the link.

I think it's fine to hold on this PR until after the Jetpack release. We're mainly concerned about showing "Beta Testing" to FSE sites in the Beta (because that page doesn't mention FSE), and these sites will all be new sites initially and start off as Simple sites. If I understand these changes correctly, once D68088-code is deployed, those users won't see the Beta Testing menu item unless they transfer to Atomic, which will likely be a small number of users before Nov 2nd.

**Comment by zaguiini** [comment]
What if we rework this PR to remove only the links for it, just like the Jetpack/WPCOM, and then, once Jetpack is released, create a follow-up PR to remove the page itself? Would that make more sense, @creativecoder? Is it worth the effort?

EDIT: Grant and I agreed it's a better solution to remove the page on a follow-up PR.

**Review by claudiucelfilip — APPROVED** [review]
Can confirm menu item is no longer visible on Simple Sites and that the page still works.
LGTM🚀

**Review by vindl — APPROVED** [review]

**Pull request merged**
