### PR TITLE
NUX: Add helper text to give context for the questions in step 1

### PR DESCRIPTION
**Pull request by danhauk**
User testing revealed some questions around why we're asking the questions we ask on the first step of signup. This PR adds some context to them, and also makes it clear the site title can be changed later.

Before | After
------------ | -------------
image | screen shot 2018-07-17 at 16 42 48

#### Testing

* Checkout this branch or open the calypso.live branch
* Go to `/start` to start the new site flow
* Confirm the helper text appears as in the screenshot above

cc @ranh for a copy review

### CODE REVIEW

**Comment by jancavan** [comment]
I think maybe "anytime" should be "any time"? But I'll defer to @ranh.

**Comment by ranh** [comment]
"anytime" is acceptable, but in Calypso the standard seems to be "any time":

https://github.com/Automattic/wp-calypso/search?q=anytime&unscoped_q=anytime

https://github.com/Automattic/wp-calypso/search?q=%22any+time%22&unscoped_q=%22any+time%22

That said, it might be simpler to just say "you can change this later"

The second label is a bit confusing because "a theme designed for you" can have very different interpretations (not to mention that "theme" is a concept we made up, a new customer won't know what it means)

How about "we'll use this to personalize your site" or "we'll use this to personalize your site and experience"? This can apply to the goals field too. 

Last thing, this screen is getting really busy. It was busy before, with all the different colors and sizes and the long lines. With these captions it becomes even worse. Should we try to do something to tone it down? Like only show some of the elements on hover for example.

**Comment by danhauk** [comment]
@ranh Thanks for the feedback. I agree with your copy suggestions.

Re: the screen being busy. @jancavan talked briefly about this and came to the conclusion that showing the copy by default helps people understand at a glance what these questions are for. Without seeing it they might just decide to not even bother with the form, or worse yet, get stuck here because they don't understand why this info is needed.

That being said, I don't think we're opposed to hiding it behind an info icon. Even though it hides the copy there's at least some indication that help text is available, as opposed to showing on hover or input focus (which was my original idea).

image

**Comment by jancavan** [comment]
When they get to this form, we can also make sure that the first field is on focus, so this displays the popover by default.

Another idea is to display the helper text in the same location (under each field), but only display on focus. We might have to add more space in between each field as this might result in some elements jumping. First field should still be focused by default.

I still prefer how it is currently though. Primarily because it's much clearer and the popovers don't end up sitting on top of other elements. This might particularly be bothersome, especially on mobile.

**Comment by danhauk** [comment]
I like the idea of the helper text appearing only on focus, but it tends to look a little broken when one is only one line and the other is two lines. For example on mobile:

image

It could also drop to two lines even on desktop in other translations.

I'm inclined to push it out with the info popovers that only appear on click (not focus) as a happy medium for now. It hides the text but is still clear it's available, and only shows up intentionally. Thoughts?

**Comment by jancavan** [comment]
Yeah, you're right. There's that really large space. My personal preference is still the `FormSettingExplanation` as it's much clearer at first glance and won't be an issue on mobile.

I'm not sure where the best position is for the popovers on mobile:
screenshot 2018-07-20 14 30 22

**Comment by anneforbush** [comment]
@jancavan @danhauk I also like the info popovers. They're there if prospective users want more information and they don't take up real estate if folks don't care.

On mobile, total shot in the dark, but is it possible to position them above the question associated with the popover? So the popover for the first question would end up showing above that question and the popover for the second question would end up showing on top of the first question. Would that be confusing or obstructive?

**Comment by jancavan** [comment]
> On mobile, total shot in the dark, but is it possible to position them above the question associated with the popover? 

Yes, I think so. I was worried it'll cover the questions, but that might not be too much of an issue since they can dismiss it anyway.

**Comment by danhauk** [comment]
@anneforbush @jancavan I positioned the popover above the icon and question. There is an auto-position for mobile but it goes where there's most room, in this case it was positioning to the left and covering the actual question.

I think it works much better here, thanks for the suggestion! It only covers the previous question which you've likely already filled out. Works well on both desktop and mobile.

image

**Comment by anneforbush** [comment]
Woohoo! I think that looks better @danhauk. Thanks for exploring that!

**Comment by jancavan** [comment]
Works great, Dan! 🎉 

Small nitpick (if you aren't on this already): I think we can move the info icons down a bit, about 3px:

screenshot 2018-07-23 13 54 51

**Comment by danhauk** [comment]
Thanks, Jan. I fixed the alignment on the icon. Much better!

**Pull request merged**
