### PR TITLE
Update & deduplicate caniuse-lite and browserslist

### PR DESCRIPTION
**Pull request by sgomes**
#### Changes proposed in this Pull Request

* Update & deduplicate `caniuse-lite` and `browserslist`

#### Testing instructions

Ensure the build continues to work correctly

### CODE REVIEW

**Comment by sgomes** [comment]
E2E test failures seem unrelated and are happening in other PRs.

**Comment by sgomes** [comment]
Rebased on `trunk` and updated to the latest versions.

**Comment by sgomes** [comment]
@scinos: It might be a good idea to get this merged before the `webpack` 5 upgrade.

**Comment by sgomes** [comment]
Rebased on `trunk` and updated to latest `caniuse-lite` again.

@scinos and @Automattic/team-calypso: This one's still waiting for a review.

**Comment by scinos** [comment]
I'm sorry, I didn't realize this PR was open.

I already deduplicated browserlist in #48594 and caniuse-lite in #48757 as part of my regular deduplicate cleanup ritual. I'll rebase this PR once both deduplicate PRs are in `trunk`.

**Review by scinos — APPROVED** [review]

**Comment by sgomes** [comment]
Thank you for the review, @scinos! 👍

**Pull request merged**
