### PR TITLE
Components: Add a PlanGate component to conditionally display content

### PR DESCRIPTION
**Pull request by pablinos**
As part of the project to redesign the 'Earn' section we're developing
various generic components to help with the layout that can be reused in
other areas. This one conditionally renders one or other of its child
components based on whether the currently selected site has a feature on
its plan.

The component takes the feature name as a prop, and renders the first
child if the feature is unavailable. If the feature is present on the
plan, then the second child is rendered.

#### Testing

There is an example added to devdocs that can be seen at:

http://calypso.localhost:3000/devdocs/design/plan-gate

I'll see if I can add another where the feature is available.

### CODE REVIEW

**Comment by eliorivero** [comment]
Although it does what it's supposed to do, I'm wondering if this isn't a bit risky or if there's a way to make the component more self explainable. What about a component with a syntax like

```
<PlanGate
    feature={ FEATURE_GOOGLE_MY_BUSINESS }
    noFeature={ <Button>Upgrade to Business</Button> }
    hasFeature={ <p>You've got the Google My Business feature</p> }
    >
```

If the component only displays a button linked to a plan upgrade or a text depending if the feature is covered by the plan or not, this could even be

```
<PlanGate
    feature={ FEATURE_GOOGLE_MY_BUSINESS }
    noFeatureButtonLabel={ translate( 'Upgrade to Business' ) }
    hasFeatureConfirm={ translate( 'You've got the Google My Business feature' ) }
    >
```

and resolve the button link inside the component.

**Comment by pablinos** [comment]
Yes, I was thinking about using props like that, but thought it could get a bit confusing if the JSX of the components was complex. Looking at your suggestion though, I think the first one is fine and prevents mistakes being made with the order of components etc.

The idea was that it isn't always going to be a button, so I like the idea of having components as the props.

**Comment by jsnajdr** [comment]
Does the `PlanGate` component offer any significant improvement over a simple `if` statement or ternary condition?

```jsx
function MyPlans( { hasFeatureX } ) {
  return <div>{ hasFeatureX
    ? <WithFeature />
    : <WithoutFeature />
  }</div>
}

connect( state => ( {
  hasFeatureX: selectedSitePlanHasFeature( 'X' )
} )( MyPlans );
```

It's also possible to create a selector that returns a function, although it's a bit tricky to implement it well (I can help):
```js
connect( state => ( {
  hasFeature: selectedSitePlanHasFeature
} ) )( MyPlans );

// JSX code
hasFeature( 'X' ) ? withX : withoutX
```

Using a conditional has another benefit: the code in the other branch is not executed. Compare:
```jsx
<PlanGate
  feature={ <With foo={ expensiveCalculation() } /> }
  noFeature={ <Without bar={ expensiveMiscalculation() } /> }
/>
```
versus:
```jsx
hasFeature
  ? <With foo={ expensiveCalculation() } />
  : <Without bar={ expensiveMiscalculation() } />
```
In one case both expensive calculation always run, in the other case only the needed does.

**Comment by pablinos** [comment]
A very good point @jsnajdr! I think in trying to strip this down to make it as generic as possible, it went too far, and we've ended up with something not that useful. 

I'll do without it and use the conditional instead.

**Pull request closed without merging**
