### PR TITLE
Group common jest config in to a preset

### PR DESCRIPTION
**Pull request by scinos**
Creates a `jest` preset to have the config for all packages in a common place.

After reading Jest docs and source code, there are a few points that have influenced this decision:

- Files referenced by `project` doesn't imply any type of extension. The config on the "parent" `jest.config.js` is not propagated to files referenced by `project`. Reading config and projects is handled in https://github.com/facebook/jest/blob/master/packages/jest-config/src/index.ts#L273

- The only mechanism provided by `jest` to do extensions are `presets`. However it is only one-level: a preset can't have presets. Eg: https://github.com/facebook/jest/blob/master/packages/jest-config/src/normalize.ts#L519 is called when normalizing a config file, but `setupPreset` is not recursive.

- By default, `rootDir` is `__dirname`, no need to specify it again (https://github.com/facebook/jest/blob/master/packages/jest-config/src/readConfigFileAndSetRootDir.ts#L96)

#### Testing instructions

* Verify tests still pass

### CODE REVIEW

**Review by sirbrillig — APPROVED** [review]
I don't fully understand the implications, but I don't have any objection WRT the composite-checkout package. The tests still pass, so I'm happy. Do you also need to convert the `jest.config.js` in `packages/shopping-cart`?

**Comment by jsnajdr** [comment]
> Do you also need to convert the `jest.config.js` in `packages/shopping-cart`?

Yes, the `shopping-cart` package should also use the new preset. I pushed the change in https://github.com/Automattic/wp-calypso/pull/46953/commits/704d3768355b38a1b3ceb2825b10f2b7629ef2a6

**Review by jsnajdr — APPROVED** [review]
The new common config works for me very well! :+1:

> By default, `rootDir` is `__dirname`, no need to specify it again

I tried to get rid of `rootDir` some time ago, but failed. It was because I was trying to extend a config from another module:
```js
const commonPreset = require( '../common/jest.config.js' );
module.exports = {
  ...commonPreset,
  foo
}
```
But that didn't work and revealed a [Jest bug](https://github.com/facebook/jest/issues/8293). Extending the preset is much better!

**Comment by scinos** [comment]
Note: ICFY shows a reduction in bundle size but it is not real. It assumes this branch is targeting master, but it is not.

**Comment by jsnajdr** [comment]
> It assumes this branch is targeting master, but it is not.

That's true, ICFY always looks for a branching point from `master` and calculates the diff from there: https://github.com/Automattic/wp-calypso/blob/master/.github/workflows/icfy-stats.yml#L45

**Pull request merged**
