### PR TITLE
Build: Run SSR pragma checker plugin on server build

### PR DESCRIPTION
**Pull request by seear**
Running SSR checker on the server build instead of the client build means that any modules that are stubbed on the server are ignored, eliminating the need to place stubbed modules in the ignore list.

Test live: https://calypso.live/?branch=update/pragma-checker

### CODE REVIEW

**Comment by seear** [comment]
pinging @ehg  for review.

Heads-up @dmsnell, @southp, this means we can can forget about the `IGNORED_MODULES` list in the pragma checker now except for weird cases.

**Comment by ehg** [comment]
So this will only warn of potential ssr-breakages on restarting Calypso? Perhaps this is OK, as long as we try building the server bundle as part of the test suite.

`make test` currently does this, but it looks like the CircleCI config doesn't. What do you think about adding it there?

Also, maybe we should have more comprehensive unit tests for SSRed code, since atm we're only attempting to `renderToString`[ a small portion](https://github.com/Automattic/wp-calypso/blob/master/server/pages/test/index.js#L17).

**Comment by seear** [comment]
> So this will only warn of potential ssr-breakages on restarting Calypso?

Very good point. I wonder if we can look at server-build restarts again after #7636? 

On balance, I _think_ that removing the need to touch the ignore list is worth delaying SSR pragma errors to Circle CI. I'll add the server build to the config.

> Also, maybe we should have more comprehensive unit tests for SSRed code

#7690

**Comment by seear** [comment]
CircleCI broken build:
screen shot 2016-08-26 at 15 42 10

**Comment by ehg** [comment]
Cool. Let's merge this after a rebase and squash, but make sure to look at it affects CircleCI container usage and build time.

/cc @hoverduck as I believe you often have your eye on container usage :)

**Pull request merged**
