### PR TITLE
Add "Connect" and "Transfer" options to the "Use a domain I own" flow.

### PR DESCRIPTION
**Pull request by delputnam**
#### Changes proposed in this Pull Request

This PR adds in the second page of the "Use a domain I own" flow. So, once the user has selected a domain they want to use, we need to do an availability check on this domain to see if we're able to transfer and/or connect the domain to the user's site.

If the domain is transferable, the option to transfer the domain will be at the top of the second page and the "Select" button for this option will be the primary button.

If the domain is not transferable, then the option to connect will be at the top of the page and the "Select" button for this option will be at the top of the page.

If the domain is not able to be transferred or connected, then an error message will be shown on the first page.

The "Select" buttons on the second page are not yet active. These will be made active in a future PR. The main focus of this PR is to properly check the availability of the domain and present the correct error message or transfer/connect options.

Examples of the primary scenarios are shown in the screenshots below:

Domain is able to be connected or transferred. Site has a paid plan and a domain credit:
Screen Shot 2021-08-16 at 2 39 45 PM

Domain is able to be connected or transferred. Site with a paid plan and no credit:
Screen Shot 2021-08-16 at 2 46 09 PM

Domain is on sale and able to be connected or transferred. Site with a paid plan and no credit:
Screen Shot 2021-08-16 at 2 30 46 PM

Domain is able to be connected or transferred. Site has no paid plan:
Screen Shot 2021-08-16 at 2 47 35 PM

Domain is on sale and able to be connected or transferred. Site has no paid plan:
Screen Shot 2021-08-16 at 2 41 03 PM

Domain is able to be connected, but not transferred. Site has a paid plan:
Screen Shot 2021-08-17 at 12 29 30 PM

Domain is able to be connected, but not transferred. Site has a no paid plan:
Screen Shot 2021-08-16 at 2 56 30 PM

Domain is able to be transferred, but not connected. Site has a paid plan and no credit:
Screen Shot 2021-08-16 at 5 30 31 PM

Requested domain is not registered:
Screen Shot 2021-08-16 at 2 41 58 PM

Search query is not a valid FQDN:
Screen Shot 2021-08-16 at 2 42 07 PM

No domain entered:
Screen Shot 2021-08-16 at 2 42 14 PM

#### Testing instructions

Go to the path: `/domains/add/use-my-domain/[site slug]`

Try testing the page with each of the scenarios above.

Also try with as many of the various combinations of availability error conditions as you can.

When adding the query string `?initialQuery=[domain name to connect]`, the page should automatically check the availability and load the second page.

### CODE REVIEW

**Review by poligilad-auto — DISMISSED** [review]
Hey @delputnam, 
Looking really good.

**For the learn more links:** 
1. I noticed some help links open in the internal modal view (linked to the help FAB button) and some open direclty in the support website. Could we open our help docs in the internal modal view? This is my other pod and we'll work on improving the FAB 🙂
2. If not, can we open the links in a new tab?

**For desktop:**
1. Remove all the spacing between "Transfer/connect your domain" to the sub-title.
2. Title should be `$font-title-small`.
3. Sub-title should be `var(—color-text);`
4. The benefit list should be $font-body-small
5. For `.domain-transfer-or-connect__content .option-content` can you make the top & bottom padding 32px?

**For mobile:**
1. For `.domain-transfer-or-connect__content .option-content` can we make the left padding 0?
2. Have 8px spacing between "Transfer/connect your domain" to the sub-title.
3. Add 8px spacing between the title and the Recommended badge.
4. Make the Select buttons full width, like on the previous screen.

Other than these, I was just wondering about the wording for the "free transfer", let's see what others in the pod think.

**Comment by delputnam** [comment]
> Hey @delputnam,
> Looking really good.
> 
> **For the learn more links:**
> 
> 1. I noticed some help links open in the internal modal view (linked to the help FAB button) and some open direclty in the support website. Could we open our help docs in the internal modal view? This is my other pod and we'll work on improving the FAB 🙂
> 2. If not, can we open the links in a new tab?

 ✅  I set both of the support links and the help/contact link to all open in new tabs.

> 
> **For desktop:**
> 
> 1. Remove all the spacing between "Transfer/connect your domain" to the sub-title.

✅ , but this looked like it was supposed to be 4px on the figma design. As I'm trying to get better at this, could you let me know what I did wrong there?

Screen Shot 2021-08-18 at 1 13 24 PM

> 2. Title should be `$font-title-small`.

✅  but figma shows this as 24px. `$font-title-small` is 20px. What did I miss here?

> 3. Sub-title should be `var(—color-text);`
> 4. The benefit list should be $font-body-small
> 5. For `.domain-transfer-or-connect__content .option-content` can you make the top & bottom padding 32px?
> 
> **For mobile:**
> 
> 1. For `.domain-transfer-or-connect__content .option-content` can we make the left padding 0?
> 2. Have 8px spacing between "Transfer/connect your domain" to the sub-title.
> 3. Add 8px spacing between the title and the Recommended badge.
> 4. Make the Select buttons full width, like on the previous screen.
> 
> Other than these, I was just wondering about the wording for the "free transfer", let's see what others in the pod think.

**Comment by delputnam** [comment]
> Hey @delputnam,
> Looking really good.
> 
> **For the learn more links:**
> 
> 1. I noticed some help links open in the internal modal view (linked to the help FAB button) and some open direclty in the support website. Could we open our help docs in the internal modal view? This is my other pod and we'll work on improving the FAB 🙂
> 2. If not, can we open the links in a new tab?

 ✅  I set both of the support links and the help/contact link to all open in new tabs.

> 
> **For desktop:**
> 
> 1. Remove all the spacing between "Transfer/connect your domain" to the sub-title.
✅ , but this looked like it was supposed to be 4px on the design. As I'm trying to get better at this, could you let me know what I did wrong there?
Screen Shot 2021-08-18 at 1 13 24 PM

> 2. Title should be `$font-title-small`.
✅  but figma shows this as 24px. `$font-title-small` is 20px. What did I miss here? (Still trying to improve my ability to be more detail oriented.)
Screen Shot 2021-08-18 at 1 19 03 PM

> 3. Sub-title should be `var(—color-text);`
✅ Done. 🤦 

> 4. The benefit list should be $font-body-small
✅ Done. Missed this one. 😞 

> 5. For `.domain-transfer-or-connect__content .option-content` can you make the top & bottom padding 32px?
✅ Done. Was this a change or did I miss something else here? 😄 

> **For mobile:**
> 
> 1. For `.domain-transfer-or-connect__content .option-content` can we make the left padding 0?
✅ Oof. Missed this one too. Thanks.

> 2. Have 8px spacing between "Transfer/connect your domain" to the sub-title.
✅ 👍 

> 3. Add 8px spacing between the title and the Recommended badge.
✅ Much better.

> 4. Make the Select buttons full width, like on the previous screen.
✅ Again, I missed this. 🤦 
 
> Other than these, I was just wondering about the wording for the "free transfer", let's see what others in the pod think.
I'll write up a post with the wording and a couple of other question I had about how these pages will fit in with a couple of other flows.

**Comment by poligilad-auto** [comment]
Thanks @delputnam, amazing!

> but this looked like it was supposed to be 4px on the design. As I'm trying to get better at this, could you let me know what I did wrong there?

This is a tough one :) Some things look a bit different between Figma and the final code, because in code you have styling for many elements. I think it had some spacing between other elements that already made it look like 4px.

Only thing is that now this badge seems to be aligned to the bottom instead of the center.
image

**Comment by delputnam** [comment]
> this badge seems to be aligned to the bottom instead of the center
Good catch.
✅  Done.  (I added the top margin for mobile, but forgot to remove it for non-mobile.)

**Review by leonardost — APPROVED** [review]
Great work, LGTM! 🚀 Didn't notice anything I'd change in the code. I tested on a paid site with and without domain credits and on a free site, with a handful of domains and everything worked like a charm! 👍

The only thing I couldn't reproduce was seeing the "sale" badge, did you use the `example.blog` domain for those? This is what I see on a paid site with no available domain credits:

Screen Shot 2021-08-19 at 12 43 19

One very minor thing I was wondering is if we should show the "Recommended" badge when transferring is the only option:

Annotation on 2021-08-19 at 12-19-05

**Comment by delputnam** [comment]
> This is what I see on a paid site with no available domain credits:

Thanks for catching this. I've fixed this pricing issue. It now shows just the price without the "Renews at" language for the case you found.

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/6452144

Thank you @delputnam for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/6452144).

**Pull request merged**
