### PR TITLE
Overview: Add visits fetching states

### PR DESCRIPTION
**Pull request by zaguiini**
Part of https://github.com/Automattic/dotcom-forge/issues/9525.

## Proposed Changes

Takes into consideration the status of the Jetpack Stats module before showing the "View stats" link.

https://github.com/user-attachments/assets/5fbc218e-6e93-4f67-8831-87838c47c102

Lets the user enable the Stats module directly from the Overview page without needing to enter the Jetpack page directly.

## Testing Instructions

Visit the Blog Report Card and disable the "Site Stats" module. Go back to Calypso and click the "Enable stats" button. You should see the stats again.

To test a failure in enabling the stats, you can block the request within dev tools:

image

### CODE REVIEW

**Comment by vykes-mac** [comment]
I see a couple Todos on the issue https://github.com/Automattic/dotcom-forge/issues/9525#top, should this PR close the issue it?

**Comment by zaguiini** [comment]
Good catch @vykes-mac I totally missed that. Let me change the description.

**Review by vykes-mac — APPROVED** [review]
LGTM

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/17032657

Some locales (Hebrew, Japanese) have been temporarily machine-translated due to translator availability. All other translations are usually ready within a few days. Untranslated and machine-translated strings will be sent for translation next Monday and are expected to be completed by the following Friday.

Thank you @zaguiini for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/17032657).

**Pull request merged**
