### PR TITLE
Woo Express: Add plan feature comparison grid

### PR DESCRIPTION
**Pull request by markbiek**
Related to #75383

## Proposed Changes

This adds the "Compare plans" button at the bottom of the Woo Express `/plans` page. Clicking the button shows the expanded Woo Express feature comparison grid. The Plus plan is intentionally hidden from the comparison grid.

This is part of several PRs related to plan features and the plan comparison grid:
* #75918 (this PR) which adds all of the plan features and groups.
* #75769 which enables the plan comparison grid for Woo Express.
* #75883 which adds footnotes to the plan comparison grid.

### Collapsed `/plans` page
Collapsed

### Expanded `/plans` page
Expanded

## Testing Instructions

* Apply this patch (or use the calypso.live link).
* Visit the `/plans` page for a Trial site or a site with the Essential plan.
* Click the "Compare plans" button and verify that the expanded feature list looks like the screenshot above.

This Slack conversation (p1681499986012049-slack-C0Q664T29) has a link to a spreadsheet with all of the features.
* Verify that the correct features are listed under the correct groups.

**NOTE: This doesn't include the footnotes shown in the Figma design. Footnotes are being added in #75883**

## Pre-merge Checklist

- [x] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [x] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [x] Have you checked for TypeScript, React or other console errors?
- [x] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

**Review by sixhours — COMMENTED** [review]
Haven't dug into the code yet, but found a couple little things:

Under "Your store" the spreadsheet notes storage space but there's no mention of it in the plans grid. Guessing that is intentional?

Under "Products", Min-max quantities is listed as *not* included in the Essential plan on the spreadsheet, but is included in the Essential plan in the plans grid. 

I'm also wondering if it would be possible/make sense to split this larger PR into two -- introduce the new features without actually implementing them, then implement in a separate PR?

**Comment by markbiek** [comment]
> Under "Your store" the spreadsheet notes storage space but there's no mention of it in the plans grid. Guessing that is intentional?

Sorry, I should've been more explicit. To stay in line with how the `/plans` page currently operates, we show the storage differences above the comparison grid in the initial list of plan features.

image
image

> Under "Products", Min-max quantities is listed as not included in the Essential plan on the spreadsheet, but is included in the Essential plan in the plans grid.

That's a mistake. Good catch!

>I'm also wondering if it would be possible/make sense to split this larger PR into two -- introduce the new features without actually implementing them, then implement in a separate PR?

Yeah, that's a good idea. I've already split out the [footnote](https://github.com/Automattic/wp-calypso/pull/75883) functionality so splitting up this one more probably makes sense.

**Review by sixhours — COMMENTED** [review]
Screen Shot 2023-04-18 at 3 34 53 PM

Found what is probably a bug with the features PR while reviewing this one. :D Recurring payments is shown as not being a feature in either plan, but it should be available for both.

**Comment by markbiek** [comment]
>  Recurring payments is shown as not being a feature in either plan, but it should be available for both.

Fixed in all three PRs!

**Review by sixhours — APPROVED** [review]
:shipit:

**Pull request merged**
