### PR TITLE
A4A > Referrals: Enable Enterprise hosting for refer mode

### PR DESCRIPTION
**Pull request by yashwin**
Closes https://github.com/Automattic/automattic-for-agencies-dev/issues/1415

## Proposed Changes

This PR 
- Enables Enterprise hosting for refer mode
- Adds a subheading for Enterprise hosting when the refer mode is enabled 
- Changes the CTA text for Enterprise hosting when the refer mode is enabled 

## Why are these changes being made?

* To allow agencies to refer the Enterprise hosting.

## Testing Instructions

* Open the A4A live link
* Go to Marketplace > Toggle `Refer products` on > Verify you can see the `Enterprise` tab, and it looks as shown below. Click the `Refer client` button and verify you are redirected to https://wpvip.com/partner-application/?utm_source=partner&utm_medium=referral&utm_campaign=a4a

Screenshot 2024-11-04 at 6 29 43 PM

When the refer mode is off

Screenshot 2024-11-04 at 6 29 27 PM

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Comment by jkguidaven** [comment]
@yashwin The referrals don't seem to work if my agency account has the regular Pressable plan and was not bought from A4A.

Screenshot 2024-11-05 at 12 44 21 PM

**Comment by jkguidaven** [comment]
Ohh sorry, I thought this was for Pressable. Ignore my previous comment.

**Review by jkguidaven — APPROVED** [review]
Works great! LGTM

**Comment by rcanepa** [comment]
A non-blocking observation: I wonder if we should change the `justify-content` prop of the right box with all the brands so that the brand logos don't jump when we go from normal mode to refer mode.

https://github.com/user-attachments/assets/619dcec8-0d4e-49b9-acfb-f2a0155f301c

What do you think?

**Comment by yashwin** [comment]
Thanks for the review, James & Renzo!

> A non-blocking observation: I wonder if we should change the `justify-content` prop of the right box with all the brands so that the brand logos don't jump when we go from normal mode to refer mode.

@rcanepa: Good catch. Fixed it here: https://github.com/Automattic/wp-calypso/pull/96045/commits/a071fc29e699a473138298d2e987af46cb2f3ad9

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/16989629

Some locales (Hebrew, Japanese) have been temporarily machine-translated due to translator availability. All other translations are usually ready within a few days. Untranslated and machine-translated strings will be sent for translation next Monday and are expected to be completed by the following Friday.

Thank you @yashwin for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/16989629).

**Pull request merged**
