### PR TITLE
Domain step test: tailored placeholder text

### PR DESCRIPTION
**Pull request by niranjan-uma-shankar**
#### Changes proposed in this Pull Request

This PR builds on top of the domain-copy A/B test introduced as a feature flag in #37546.

* Placeholder text for the domain search box is tailored per the site type chosen in the signup flow.

Screenshot 2019-11-14 at 7 43 50 PM

#### Testing instructions

* Go to /start and put yourself in the variant variantShowUpdates of the domainStepCopyUpdates A/B test.
* The domain search box placeholder text should show the new copy:

If site type is "blog" : `Enter your blog's name or a few words that describe it, like "photography" or "travel"`

If site type is "business" : `Enter your business's name or a few words that describe it, like "photography" or "travel"`

If site type is "professional" : `Enter your site's name or a few words that describe it, like "photography" or "travel"`

If site type is "store" : `Enter your store's name or a few words that describe it, like "photography" or "travel"`

**Mobile View**

* Verify alignment and copy checks out in mobile views.

**Check in other domain pages**

* Login to any account, and after assigning yourself to the variant, check the launch flow for privates sites and the Add domain page. In both places, the placeholder text for the domain search box should not show the new copy(we are showing the copy only during signup).

**Verify that the A/B test is not automatically assigned**
* Go to /start and without manually assigning yourself to an A/B test, just complete the signup flow. 
* In your Browser console, type `localstorage.ABTests;`. Verify that the `domainStepCopyUpdates ` test is not present in the object. This is because we do not yet want any user getting assigned to the test till all the pieces are deployed.

### CODE REVIEW

**Comment by niranjan-uma-shankar** [comment]
The placeholder text is long for mobile views, and gets cut-off. Should we go for a shorter length text?

calypso localhost_3000_start_domains-with-preview(Pixel 2 XL)

**Comment by michelleweber** [comment]
Can we shorten just for mobile, to "Enter your site's name or a few descriptive keywords" or even "Enter your site's name or some keywords" if that's still too long?

**Comment by victorespigares** [comment]
My vote is for shortening it for both. From an experiment perspective, it's best to keep all the same, not having a version for mobile and other for desktop.

I'll throw another ball here. Given that... 

1) this step is all about searching a domain
and 2) we're repeating the same information in the subheader and in the placeholder (redundant)

...what if we go with something super simple and direct like:

`Type the domain you want here`

**Comment by michelleweber** [comment]
My hesitation with "type the domain you want here" is that that's something different that the subhead copy. We told them to tell us their title or give us some keywords, and now we're asking them for something else entirely. For that to work, the subhead would need to be something like "Know what domain you want? Great, tell us. Not sure? Give us your site title or few keywords, and we'll make some suggestions." and the prompt text something like "Enter your domain or title here."

Given that, and given the other, more significant changes already happening to the page, I'd push to go with "Enter your site's name or some keywords." and then doing another test that changes the subhead and prompt text more substantially.

**Comment by niranjan-uma-shankar** [comment]
Oops, I pushed in a change without reading @michelleweber 's comment. I'll just modify the text with whatever is the final choice and push the change again, not a big deal.

**Comment by niranjan-uma-shankar** [comment]
I'm merging this change for now to keep testing moving forward, but just to clarify, this change will not be seen by users till all other pieces are merged. So we will have time to change things later(before the A/B test is deployed).

**Pull request merged**
