### PR TITLE
Media Data-Source: Update Google Photos: Approach 1

### PR DESCRIPTION
**Pull request by mreishus**
#### See Also
* See also: Approach 2  #56287

#### Changes proposed in this Pull Request

* In the media data source dropdown, update the google photos logo
* Make the label text always display as to not break google's guidelines

#### Testing instructions

* In the sidebar, visit media
* Examine and use the source dropdown in the top left

Before:

**After (1a) icons+text:**

**Updated (1b), no icons:**

**Updated (1c), Icons in header only:**

Related to #56251

### CODE REVIEW

**Comment by mreishus** [comment]
Updated to an iconless look:

**Comment by simison** [comment]
image


How would it look for icon-less if:

- There's always the "image" icon visible in the tab area, but not in the dropdown.
- We show just "Pexels" in the header and longer "Pexels free photos" in the dropdown

**Comment by mreishus** [comment]
> How would it look for icon-less if:
> 
>     * There's always the "image" icon visible in the tab area, but not in the dropdown.
> 
>     * We show just "Pexels" in the header and longer "Pexels free photos" in the dropdown

Updated branch, I think this is what you're describing?

**Comment by mreishus** [comment]
Closing this since we decided to go w/ approach 2 for now. Can reopen and iterate on the changes if we need to revise after Google's review.

**Pull request closed without merging**
