### PR TITLE
build(webpack): Enable contenthash naming strategy for JS and CSS files

### PR DESCRIPTION
**Pull request by scinos**
#### Changes proposed in this Pull Request

* Uses `contenthash` instead of `chunkhash` for the filenames (https://webpack.js.org/blog/2020-10-10-webpack-5-release/#real-content-hash).
* Delete `ExtractManifestPlugin`. It will require some hacks to make it work with `contenthash` and it will only save ~6kb, I don't think it is worth the complexity

`contenthash` should give us better long-term caching. The downside is that the manifest is bigger now: before we were reusing the same hash for all files in the chunk (eg: `main.abcd1234.js` and `main.abcd1234.css`). This is not possible anymore with `contenthash`, therefore the manifest will contain more hashes.

This PR also removes the ExtractManifestPlugin (#42979, #44988). Making it work with `contenthash` is not trivial: when webpack renders the manifest the `contenthash` replacement map is not complete yet, and it doesn't provide a hook point to alter the manifest afterwards. 

Overall, we are shipping ~13kb of extra code in the manifest. About half of it is using a new set of hashes for CSS files, and the other half is the the replacement map for `name`. We will have two copies of the replacement for `name`, but it should be efficiently gzipped. My plan is to deploy this change and use RUM data to see if we see an improvement in caching and if the extra manifest size has a negative impact.

#### Testing instructions

* Smoke test live branches. Verify you don't get any 404 on JS or CSS files.

### CODE REVIEW

**Comment by sgomes** [comment]
From a smoke test point of view, this PR is working correctly. However, I still see different hashes between CSS and JS chunks. Is that expected?

**Comment by scinos** [comment]
@sgomes Sorry for the noise, I moved this PR to draft until I figure out the hashing problem (I get a couple of 404 when loading CSS files).

**Comment by sgomes** [comment]
> @sgomes Sorry for the noise, I moved this PR to draft until I figure out the hashing problem (I get a couple of 404 when loading CSS files).

No worries, it was interesting to check the progress anyway 🙂 Just give me a shout when you think it's ready and I'll be happy to take another look!

**Comment by scinos** [comment]
@sgomes This should be ready for review now

**Comment by sgomes** [comment]
~@scinos There don't seem to be errors anymore, but I'm still seeing different hashes between the JS and CSS files for a chunk, e.g. `entry-main.b3a24b1529bae0f5aee8.min.css` and `entry-main.2f84a8930883a32da3e0.min.js`. Is that expected?~

See below.

**Comment by sgomes** [comment]
> @scinos There don't seem to be errors anymore, but I'm still seeing different hashes between the JS and CSS files for a chunk, e.g. `entry-main.b3a24b1529bae0f5aee8.min.css` and `entry-main.2f84a8930883a32da3e0.min.js`. Is that expected?

Sorry, I just re-read the description, and it is indeed expected 👍

**Review by sgomes — APPROVED** [review]
Looks good enough to deploy and test with.

I'm curious to see if the caching improvements make up for the extra network and particularly the extra CPU costs (which scale with decoded JS bytes, not gzipped JS bytes).

**Pull request merged**
