### PR TITLE
Popover: remove the rootClassName prop

### PR DESCRIPTION
**Pull request by jsnajdr**
Removes the `rootClassName` prop from `Popover` and related components. The prop doesn't have any useful usage and it styles a wrapper `div` that will disappear after the `RootChild` component is migrated to `React.createPortal` in #32899.

Except a lot of code that drill the props from parent components to children, there was only one actual usage: adding an unused `blog-stickers__popover` CSS class to a Reader popover.

This PR also avoids passing props to `RootChild` in `Popover` that are applied to a wrapper `div`, and passes them to the actual popover's inner `div` instead.

**How to test:**
Verify that `Popover` div markup looks reasonable, and all the a11y improvements that @ItsJonQ did in #32849 continue to work.

@ItsJonQ There's one thing I don't understand: your patch from #32849 adds a `tabIndex` to a non-interactive `div` element if the `isFocusOnShow` prop is enabled. But then the `eslint-plugin-jsx-a11y` ESLint rules complain:

> [`tabIndex` should only be declared on interactive elements](https://github.com/evcohen/eslint-plugin-jsx-a11y/blob/master/docs/rules/no-noninteractive-tabindex.md)

So, who is right here? What's the point of focusing a popover element that's not interactive?

When the `tabIndex` is there, I can see that when opening a popover (during domain search), the popover button loses focus and the popover element indeed becomes the active element (`document.activeElement`). But it doesn't show a focus ring or anything like that. Is it important for assistive tech like VoiceOver?

### CODE REVIEW

**Comment by ItsJonQ** [comment]
> Is it important for assistive tech like VoiceOver?
@jsnajdr That was my goal! By focusing on the popover element, screen-readers will read the `aria-label`. Not only that, but since the popover container is focused, pressing `tab` will allow for focus to jump to child elements (if applicable).

Hope this helps!

**Comment by jsnajdr** [comment]
> By focusing on the popover element, screen-readers will read the `aria-label`. Not only that, but since the popover container is focused, pressing tab will allow for focus to jump to child elements (if applicable).

Thanks @ItsJonQ, that makes sense! I did a few little modifications in 91c2968, though:

First, to make an non-interactive `div` element focusable, `tabIndex="-1"` is a better option than current `tabIndex="0"`. [MDN says](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/tabindex):

> A negative value (usually `tabindex="-1"`) means that the element is not reachable via sequential keyboard navigation, but could be focused with Javascript or visually. It's mostly useful to create accessible widgets with JavaScript.

I verified that with `tabIndex="-1"`, the popover element is still focused and announced by VoiceOver, as before. Also, pressing <key>Tab</key> continues to focus the child form elements inside the popover. Also, the `no-noninteractive-tabindex` ESLint rule is happy now: it doesn't like `tabIndex="0"`, but is OK with `tabIndex="-1"`.

Second, do we really need the `isFocusOnShow` prop? It seems to me that it's OK to enable the focus behavior for all popovers, without needing to opt-in or opt-out. Is there any downside? I removed the prop in the same commit and just set the `tabIndex` unconditionally.

Let me know if I'm missing something 🙂

**Comment by ItsJonQ** [comment]
@jsnajdr 

> I verified that with tabIndex="-1", the popover element is still focused and announced by VoiceOver, as before.

Wonderful! 🎉 

> Second, do we really need the isFocusOnShow prop

I was very cautious when I created this PR. This was my first PR on Calypso 😊 , so I made this functionality opt-in, just in case it may break something somewhere that I wasn't aware of.

It was designed so that in the future, being now I suppose, we could remove that flag and just enable it everywhere 🙌 

Hope this helps!

**Comment by jsnajdr** [comment]
> It was designed so that in the future, being now I suppose, we could remove that flag and just enable it everywhere

Yes, I think it's safe to make the flag always on. I tested several other instances of `Popover` and the new focus behavior is a clear improvement everywhere 👍

I'll proceed to merging this PR after the Canary tests come back green.

**Pull request merged**
