### PR TITLE
A4A > Marketplace: initial implementation of the hero section on hosting page

### PR DESCRIPTION
**Pull request by yashwin**
Closes https://github.com/Automattic/jetpack-genesis/issues/449
Closes https://github.com/Automattic/jetpack-genesis/issues/446

## Proposed Changes

This PR:

- Does initial implementation of the hero section on the new hosting page including add the new tabs for different hosts
- Creates an empty component for future developments.

Note:

- The background image animation will be implemented in a different PR.
- None of the pieces here are responsive, meaning it won't look good on all the devices. This will be fixed in a different PR.

## Why are these changes being made?

* This PR creates the initial work for the upcoming tasks for the hosting page design work

## Testing Instructions

* Open the A4A live link > Go to Marketplace - Hosting and verify:

- The UI looks as shown below
- You can switch between tabs
- The URL changes when the tab is changed

Screenshot 2024-07-25 at 1 43 20 PM
Screenshot 2024-07-25 at 1 44 22 PM

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Comment by jkguidaven** [comment]
@yashwin the current hero container does not scale well with wider screens. [My PR](https://github.com/Automattic/wp-calypso/pull/92958) solved this problem by overriding the layout CSS rules. Can you check if you can apply it to this PR?

Screenshot 2024-07-25 at 6 07 20 PM

**Comment by yashwin** [comment]
> @yashwin the current hero container does not scale well with wider screens. [My PR](https://github.com/Automattic/wp-calypso/pull/92958) solved this problem by overriding the layout CSS rules. Can you check if you can apply it to this PR?

Thanks for the review, @jkguidaven! 

As mentioned in the descriptions, I haven’t tried to fix the responsiveness on this PR. I thought this would unblock a few tasks, and I can fix it in another PR. WDYT?

**Review by jkguidaven — APPROVED** [review]
As agreed, the responsiveness issue will be fix on a separate PR. LGTM 👍

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/16425272

Some locales (Hebrew, Japanese) have been temporarily machine-translated due to translator availability. All other translations are usually ready within a few days. Untranslated and machine-translated strings will be sent for translation next Monday and are expected to be completed by the following Friday.

Thank you @yashwin for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/16425272).

**Pull request merged**
