### PR TITLE
Posts Filters: add better styles for small screens

### LINKED ISSUE #16921: Posts: Controls overlap in header on small landscape viewports for multi-author sites
#### Steps to reproduce
1. View `/posts` for a multi-author site with a small viewport, such as landscape mode on an iPhone 6s

#### What I expected

The layout to adapt to my viewport, showing me things without controls being overlapped.

#### What happened instead

Controls are overlapped.

#### Browser / OS version

iPhone 6s

#### Screenshot / Video

img_5986

#### Context / Source

Found while testing other issues.

### PR DESCRIPTION
**Pull request by lancewillett**
Started with #39332 courtesy of @millerf 

**Before:**

Screenshot 2020-02-09 at 21 51 02

**After:**

Screenshot 2020-02-09 at 22 37 16

Fixes #16921

### CODE REVIEW

**Comment by millerf** [comment]
@lancewillett You should have branched out from my branch, so the commit ownership stays the same 😜

**Comment by lancewillett** [comment]
@millerf The branch source was "unknown" in this case — I got an error when trying to switch to the branch.

**Comment by millerf** [comment]
@lancewillett My bad then. Not sure what hapened...

**Comment by lancewillett** [comment]
Yeah; it was weird — `Unknown branch` error on GitHub command line when trying to start from your branch.

No worries! You still get credit as "props" and of course we appreciate all the contributions you make. **Thank you**. 🙇

**Pull request merged**
