### PR TITLE
Untangling: Add Advanced Tools -> Staging Site

### PR DESCRIPTION
**Pull request by fushar**
Fixes:

- https://github.com/Automattic/dotcom-forge/issues/9615

## Proposed Changes

This PR adds the Advanced Tools -> Staging site subtab under the `untangling/hosting-menu` flag.

### Production site

image

### Staging site

image

## Why are these changes being made?

pbxlJb-6ye-p2

## Testing Instructions

1. Go to /sites
2. Click an Atomic site
3. Go to Advanced Tools -> Staging site subtab.
4. Verify that this tool is working.
5. Repeat with a staging site.
6. Smoke-test staging site features; verify that the features are working.
7. Regression testing:
    - Go to /sites?flags=-untangling/hosting-menu
    - Click an Atomic site
    - Verify that the original Staging site tab is still working.
    - Repeat with a staging site.
    - Smoke-test staging site features; verify that the features are working.

## Pre-merge Checklist

- [x] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [x] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [x] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [x] Have you checked for TypeScript, React or other console errors?
- [x] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [x] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [x] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Comment by taipeicoder** [comment]
The full-width button looks a bit too much.

| Before | After |
| --- | --- | 
| Screenshot 2024-11-05 at 2 35 22 PM | Screenshot 2024-11-05 at 2 35 11 PM |

**Comment by fushar** [comment]
> The full-width button looks a bit too much.

Thanks, good catch, missed this while consolidating the CSS, fixed!

**Review by taipeicoder — APPROVED** [review]
LGTM! Could we open an issue to address this flash of content? I think it'd be a nice improvement we can do when we get to the polish stage.

ezgif-2-4e8db640a5

**Comment by fushar** [comment]
> Could we open an issue to address this flash of content?

It looks like an existing issue. Opened here!

- https://github.com/Automattic/wp-calypso/issues/96050

**Pull request merged**
