### PR TITLE
Update CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by zeldman**
Added two missing words to a readme that is now grammatically correct by my having done so. :)

#### Changes proposed in this Pull Request

*

#### Testing instructions

*

Fixes 

Corrected grammar in Readme file.

### CODE REVIEW

**Review by apeatling — COMMENTED** [review]
Looks good 👍

**Review by apeatling — APPROVED** [review]

**Review by allancole — APPROVED** [review]
Sometimes its the little things that matter most ;-) 

Looks good to me—ship it after the checks pass!

**Review by davemart-in — APPROVED** [review]
Woo! Nice work.

**Comment by apeatling** [comment]
@zeldman I think this is good, and you can hit the merge button 👍

**Pull request merged**
