### PR TITLE
Do NOT redirect `/plugins/manage/` multisite view and check for 'install-purchased-plugins' feature.

### PR DESCRIPTION
**Pull request by DustyReagan**
#### Proposed Changes

Redirects `/plugins/manage/{site_slug}` (If missing 'manage-plugins' or 'install-purchased-plugins') to `/plugins/{site_slug}`

Going to `/plugins/manage/` (with no site_slug) should NOT redirect you anywhere.

Show "Installed Plugins" button on all Jetpack (non-Atomic) sites OR sites with the 'manage-plugins' OR 'install-purchased-plugins' feature. Hide the button for simple and Atomic sites without the 'manage-plugins' OR 'install-purchased-plugins' feature.

installed-plugins

#### Testing Instructions

> **Note**
> Jetpack (non-Atomic) sites should always show the "Installed Plugins" & "Upload" plugin buttons and never be redirected from `/plugins/manage/{site_slug}` or `/plugins/upload/{site_slug}`

- Load this branch.

For all Simple sites and Atomic WITHOUT the 'manage-plugins' or 'install-purchased-plugins' feature (this is currently all plans below Business and Pro).
- Go to `/plugins/{site_slug}`
  - You should NOT see the "Installed Plugins" button.
- Try manually going to `/plugins/manage/{site_slug}`
  - You should be redirected to /plugins/{site_slug}
- Try manually going to `/plugins/manage/`
  - You should NOT be redirected

For Atomic sites WITH the 'manage-plugins' or 'install-purchased-plugins' feature (this is currently Business, Pro, and eCommerce plans).
* Got to `/plugins/{site_slug}`
  * You should see the "Installed Plugins"
* Try manually going to `/plugins/manage/{site_slug}`
  * You should NOT be redirected to /plugins/{site_slug}

Regression test: For plans on Simple and Atomic WITHOUT the 'upload-plugins' feature (this is currently all plans below Business and Pro).
- Go to `/plugins/{site_slug}`
  - You should NOT see the "Uploads" button.
- Try manually going to `/plugins/upload/{site_slug}`
  - You should be redirected to /plugins/{site_slug}

Regression test: For plans on Simple and Atomic WITH the 'upload-plugins' feature (this is currently Business, Pro, and eCommerce plans).
- Go to `/plugins/{site_slug}`
  - You should see the "Uploads" button.
- Try manually going to `/plugins/upload/{site_slug}`
  - You should NOT be redirected

### CODE REVIEW

**Comment by mreishus** [comment]
I think the upload button needs to account for sites that **are atomic** but **do not have the ability to upload plugins**.

I temporarily added ATOMIC and INSTALL_PURCHASED_PLUGINS features to the starter plan, then made a starter plan site and transferred it to atomic. (Directions here: 1003-gh-Automattic/wpcomsh ).

When I click the upload button for this site, I see this confusing message:


(It's confusing because nothing is actually installing)

Looking up the source, the message means it wants to start an atomic transfer, but cannot do so because it is already transferred:
https://github.com/Automattic/wp-calypso/blob/f6286a8fa1aa8bd4659803ec7999a3290f435c01/client/blocks/eligibility-warnings/hold-list.tsx#L120-L128

Not sure what it should do in this case. Maybe the button shouldn't appear or it should be grayed out? CC @obenland

**Comment by DustyReagan** [comment]
> When I click the upload button for this site, I see this confusing message

Looks like we get that message when an Atomic site has the 'atomic' feature, but not the 'upload-plugins' feature. 🤔

**Review by mmtr — COMMENTED** [review]
> - Go to /plugins/{site_slug} on a sub Business/Pro plan.
> - [...]
> - Try manually going to [...] **/plugins/manage/{site_slug}**
>   - You should be NOT be redirected.

I'm getting an inconsistent behavior here.

There is a redirection for Simple sites on lower-tier plans, which is not expected according to the testing instructions, but it looks fine to me – there is no point in showing the plugins management screen for Simple sites.

However, I'm not redirected for Atomic sites on any lower-tier plans, which seems expected, but I think we need to make a distinction here. Sites with the `install-purchased-plugins` feature shouldn't be redirected, so they can manage the Marketplace plugins. But sites without that feature, should be redirected since they cannot manage any plugin.

Furthermore, the "Browse plugins" button displayed in there, should be hidden for sites without the `install-purchased-plugins` feature.

Screen Shot 2022-06-27 at 12 52 16

> - Go to /plugins/{site_slug} on a Business/Pro or higher plan.
> - You should see the "Installed Plugins" button.

We shouldn't show that button on Simple sites, since it links to `wp-admin/plugins.php` which is blocked for Simple sites.

> - Go to /plugins/{site_slug} on a Business/Pro or higher plan.
> - [...]
> - Click on the "Upload" button.
> - You should NOT see a plan upsell message and you should see an upload box.

I think there is a regression here. Simple sites should display the Atomic eligibility transfer before they can see the upload box.

Before (prod) | After (this branch)
--- | ---
Screen Shot 2022-06-27 at 12 59 07 | Screen Shot 2022-06-27 at 12 59 13

**Comment by DustyReagan** [comment]
I initially created this PR with the aims of restoring the "Uploads" button on all plans/sites so as to expose the upsell on the uploads page. However, it seems the [<EligibilityWarnings](https://github.com/Automattic/wp-calypso/blob/78f4c49d39513187377d48db0ce35b91fc58a315/client/my-sites/plugins/plugin-upload/index.jsx#L109) component needs some non-trivial refactoring to get that working. (Symptom shown in @mreishus's [comment](https://github.com/Automattic/wp-calypso/pull/64942#issuecomment-1165818922). Issue created [here](https://github.com/Automattic/wp-calypso/issues/65013).) So, I've simplified this PR to just fixing the `/plugins/manage/` multisite redirect and taking into account the 'install-purchased-plugins' feature.

@mmtr I believe I've addressed all of the issues you mentioned in your [comment](https://github.com/Automattic/wp-calypso/pull/64942#pullrequestreview-1020006011), save for one. The "Browse Plugins" button simply links back to `/plugins/{site_slug}' which is available to all sites and plans, so I'm not sure there is a need to hide it.

**Review by obenland — APPROVED** [review]
Nice, :shipit:

**Pull request merged**
