### PR TITLE
Jetpack Manage: Implement new card design for added payment methods

### PR DESCRIPTION
**Pull request by yashwin**
Resolves https://github.com/Automattic/jetpack-genesis/issues/184

## Proposed Changes

This PR implements new card design for added payment methods

## Testing Instructions

**Prerequisites**

Since these changes are made specifically for agencies, you must set yourself(partner) as an agency - 2c49b-pb.

**Instructions**

1. Visit the Jetpack Cloud link > Click Purchases > Click Payment Methods
2. Append the URL with `?flags=jetpack/card-addition-improvements`
3. Verify that the added payment methods show the new card design as shown below on different screen sizes:

mobile (58)

mobile (59)

Screenshot 2024-01-12 at 1 08 35 PM

## Pre-merge Checklist

- [x] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [x] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

**Review by ilonagl — COMMENTED** [review]
This looks amazing! 🤩 Great work, @yashwin!

I've noticed that the right side of the card layout appears a bit chaotic. To improve this, I propose two potential solutions:

- Align the card logo and expiry text on the right side/end. This should create a more orderly and visually appealing look.
- If the first solution isn't effective, consider enlarging the card numbers so they align from the right side as well. This could improve readability and maintain a balanced design.

Please experiment with these adjustments and let me know how it goes.

Group 1 (5)

**Review by ilonagl — APPROVED** [review]
Amazing work, @yashwin! Thank you!

**Comment by yashwin** [comment]
Thanks for the review, @ilonagl!

Fixed it: 

Screenshot 2024-01-12 at 6 06 17 PM

**Review by oikeme — CHANGES_REQUESTED** [review]
@yashwin for mobile/smaller screen this looks great however I am running in to an issue on larger screens where the cardholder information and expiration is misaligned on the card. I've attached a screenshot of what I am seeing.
 
Screenshot 2024-01-14 at 4 44 19 PM

**Comment by yashwin** [comment]
Thanks for the review, @oikeme! 

> @yashwin for mobile/smaller screen this looks great however I am running in to an issue on larger screens where the cardholder information and expiration is misaligned on the card. I've attached a screenshot of what I am seeing.

I'm unable to reproduce this. Could you please tell me the screen resolutions and also attach the screenshot?

I tried this from 320px to 2560px, this looks good on all the screen sizes

Screenshot 2024-01-15 at 9 22 31 AM


Update:

I was able to reproduce this at my 90% browser size. This has been fixed now:


Screenshot 2024-01-15 at 9 35 07 AM

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/10818812

Some locales (Hebrew, Japanese) have been temporarily machine-translated due to translator availability. All other translations are usually ready within a few days. Untranslated and machine-translated strings will be sent for translation next Monday and are expected to be completed by the following Friday.

Thank you @yashwin for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/10818812).

**Pull request merged**
