### PR TITLE
Tag churn happychats with churn_chat_prompt

### PR DESCRIPTION
**Pull request by candy02058912**
#### Proposed Changes

Demo video is in Testing instruction section.

* When user opens help center through the JITM CTA button, we will set a tag in help-center store
* Send `chat.tag` event to happychat server
* Add `chat.tag` event to happychat server: https://github.com/Automattic/happychat/pull/1860

#### Testing Instructions

https://user-images.githubusercontent.com/6586048/208105339-5c8e9c32-a8be-4a2d-ae5a-5d603034b68b.mp4

Setup:

- Sandbox: remember to also sandbox widgets.wp.com
- Sandbox: Make sure you are marked as a churn user, see instructions here: D93101-code
- Local happychat-hud: [Start happychat-hud](https://github.com/Automattic/happychat-hud/blob/staging/README.md#getting-started)
- Local happychat server: [Start happychat server and connect locally](https://github.com/Automattic/happychat/pull/1860)
- Local calypso: Checkout to this branch
- Local calypso: cd into `apps/happychat`
- Local calypso: run `yarn dev --sync`

Action:
- Happychat hud: Enter your local happychat hud and be available
- Go to http://calypso.localhost:3000/home/:site
- Calypso: Click on JITM to open up help center
- Calypso: Go to Live Chat and start a chat
- Happychat hud: check that the tag is showing on the top

#### Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

Related to https://github.com/Automattic/dotcom-forge/issues/1302

### CODE REVIEW

**Review by paulopmt1 — APPROVED** [review]
Great job @candy02058912, tested and tryed to break. Everything is working as expected!

image

**Comment by klimeryk** [comment]
I've tried triggering the JITM notice, as per the instructions (set the user attribute), but cannot get it to show. I've seen it in the response for the `calypso:home:admin_notices` JITM path, but it's not being shown in the home section. Anything I'm missing?
Also, added Vertex as reviewers to put it on their radar, as they are in charge of Help Center 🙇

**Comment by paulopmt1** [comment]
> I've tried triggering the JITM notice, as per the instructions (set the user attribute), but cannot get it to show. I've seen it in the response for the `calypso:home:admin_notices` JITM path, but it's not being shown in the home section. Anything I'm missing? Also, added Vertex as reviewers to put it on their radar, as they are in charge of Help Center 🙇

Hey @klimeryk, I had this issue once. In my case was due to the dismissal of messages. Could you try cleaning your frontend `Local storage` and `Session storage`?

image

**Review by alshakero — APPROVED** [review]
Tested the entire stack 

- Happychat
- Happychat-hud
- Calypso

And I got the tag perfectly. I also started another chat normally after ending the first one, and the tag didn't appear, exactly like expected.

**Comment by candy02058912** [comment]
Rebased

**Pull request merged**
