### PR TITLE
esmodules: Update lib/media/utils

### PR DESCRIPTION
**Pull request by dmsnell**
@see: https://github.com/Automattic/wp-calypso/milestone/224

Previously we were exporting a default object of multiple methods and
importing those through the non-spec-compliant Babel destructuring
import statements.

This patch makes those methods proper named exports in the work of
turning off CommonJS compilation.

### CODE REVIEW

**Comment by johngodley** [comment]
Everything generally works although I get JS errors thrown for various media actions:

`detail-item.jsx:397 Uncaught TypeError: Cannot read property 'getMimePrefix' of undefined`

For example, click 'edit' on an image in the media library, or change media library filter, or change the media library source to Google Photos. The action continues on after the error. The errors don't occur in master.

**Comment by dmsnell** [comment]
Recreated from recent **master** - now much smaller

**Comment by dmsnell** [comment]
@johngodley would you be willing to retry your tests to see if the error is still there?

**Comment by samouri** [comment]
note: this becomes 140 lines when viewed [without whitespace](https://github.com/Automattic/wp-calypso/pull/21177/files?w=1)

**Pull request merged**
