### PR TITLE
Domain only flow: redirect when starting the flow with a bad domain name

### PR DESCRIPTION
**Pull request by yurynix**
On domain only flow, when starting the flow with a bad domain name, redirect to `/domains`

#### Testing instructions
  
1. Run `git checkout add/error-message-for-no-domain` and start your server, or open a [live branch](https://calypso.live/?branch=add/error-message-for-no-domain)
2. Open the [domain only flow](http://calypso.localhost:3000/start/domain-first?new=test) with a bad domain
3. Assert that you are redirected
4. Assert that with valid domain no error is displayed and there is no redirect
  
#### Reviews
  
- [x] Code
- [x] Product

### CODE REVIEW

**Comment by ranh** [comment]
> when starting the flow with a bad domain name, display an error message and redirect to the main flow

How about returning to the begining of the flow instead? Letting users choose a different domain, rather then defaulting them to the site flow. 

I'm also not sure a visible notice is needed here. Unless we know how users ended up with a bad domain query in the first place, the notice is not going to be very useful.

**Comment by scruffian** [comment]
The problem with keeping them in the `domain-first` flow is that there is no domain step in that flow, and adding one is problematic.

This solution looks fine to me. I propose we just go with whatever is simplest, since this is an edge case.

**Comment by Tug** [comment]
Code 👍 
Not sure about the error message (what does it mean later for the user?).

**Comment by Tug** [comment]
Product 👍

**Comment by michelleweber** [comment]
Howdy! Editor at your disposal :)

Question: What does "bad" domain name mean here? Unavailable? Too short? Includes unacceptable characters? Something else? Is "This domain is unavailable" too vague here?

""X" isn't available as a domain. Keep going with setup -- you'll be able to choose another domain later."

**Comment by drewblaisdell** [comment]
> I propose we just go with whatever is simplest, since this is an edge case.

I don't think displaying a notice is the simplest solution here. I agree with @ranh that

> Unless we know how users ended up with a bad domain query in the first place, the notice is not going to be very useful.

and that we should simply hard redirect the user to `/domains` once that route is available.

**Comment by ranh** [comment]
Thanks for the notes @michelleweber! I think we're going to remove this notice altogether though :) So clearing the copy review label.

**Comment by fabianapsimoes** [comment]
Product :+1: 

Though I think we should test this again once we have the landing page at `/domains`. I'll add a note to #1425-tr.

**Comment by Tug** [comment]
Code 👍

**Pull request merged**
