### PR TITLE
Use Node.js version of redirectLoggedIn on server

### LINKED ISSUE #46652: Log-in Link Form causes 504 while logged in
#### Steps to reproduce

1. Log in to an account
2. Visit https://wordpress.com/log-in/link

#### What I expected
To be shown the form to send a log-in link to an email address or a notification that I'm already logged in.

#### What happened instead
504 Gateway Timeout

#### Context / Source
This link is sent to users who need help recovering their account.  If they are logged into a different account at the time, they are not able to use the link given.

### PR DESCRIPTION
**Pull request by jsnajdr**
When redirecting `/log-in/link` to `/` in a logged-in session, use the Node.js/Express.js handler to do that.

The handler in `web-util` uses `page.js` to do the redirect, probably crashing the server. It can't ever work. The `page.js` router works with `window.history` etc.

**How to test:**
Unfortunately testable only with user bootstrapping. Check that `/log-in/link` in logged-in session is redirected by server.

Fixes #46652

### CODE REVIEW

**Comment by retrofox** [comment]
sorry there is something that we can do to help to test, easily 😅 ?

**Comment by jsnajdr** [comment]
> sorry there is something that we can do to help to test, easily

I don't know about an easy way to test 🙂 The server redirect needs user bootstrapping on server to work.

**Comment by jsnajdr** [comment]
@tyxla I was very curious why changing `page.redirect( '/' )` to `page( '/' )` does any difference and I figured out that it's a _page.js_ bug 🙁 

The `page( '/' )` call happens in the login entrypoint which does not have any client-side handler for `/`. Therefore, the navigation will cause a full reload. _page.js_ has a feature for that: if the route wasn't handled (no matching handlers found or they all called `next()`), it will do a `window.location = url` at the end. But this feature is unreliable and fragile. There is a check:
```js
if (current === ctx.canonicalPath) return;
```
which means that if the target URL is already the current location, nothing will happen.

But `page.redirect()` first does `window.history.pushState()`, putting the new URL in the `window.location`, and only then invokes the handler chain. The `unhandled` handler then sees that the target URL is already in `window.location` and does nothing.

`page.show()` (aliased as `page()`) does it the other way around: start the handler chain first, call `pushState()` second. That's why `page( '/' )` does the redirect.

But `page( '/' )` can be easily broken, too. Just add one noop async handler:
```js
page( '*', ( ctx, next ) => { setTimeout( next, 0 ); } );
```
and suddenly the `unhandled` handler will be called after `pushState()` even for `page( '/' )`. The bug will be back (confirmed).

That's why I changed `page( '/' )` to `window.location = '/'` in this PR.

There's one more benefit: if `/log-in/link` and `/` were in the same entrypoint, then we'd get a SSRed `/log-in/link` page and then do a client-side redirect to `/` in the browser. The SSRed `/log-in/link` UI will not be hydrated by client-side `/log-in/link` UI, but, e.g., by Reader UI. That could break the layout. React doesn't like when the server-side and client-side renders don't match. A forced full reload avoids that.

**Comment by jsnajdr** [comment]
I believe this fix is now ready for review. The patch does:
- do the server-side redirect with a server-side handler
- move `redirectLoggedIn` to a separate module (used only by `/log-in`) to avoid bundle inflation
- change `page( '/' )` to `window.location = '/'` to avoid router bugs
- move the `redirectLoggedIn` handler to the first place in the chain. It doesn't make sense to prepare UI rendering (locales, sections) only to abort it with a redirect later. Try the redirect first.

**Review by tyxla — COMMENTED** [review]
Thanks for taking the time to dig further and discover the root causes. 

Everything you explained and changed makes a lot of sense!

However, in my testing of `/log-in/link` as a logged in user, I noticed that we're still seeing the screen before the redirect. Do you know what might be going on?

**Comment by jsnajdr** [comment]
> However, in my testing of `/log-in/link` as a logged in user, I noticed that we're still seeing the screen before the redirect. Do you know what might be going on?

In development mode, without server-side user bootstrap, this is expected. The login link form was SSR-ed by the server, and only after the browser downloads the JS scripts and runs the `page( '/log-in/link', redirect, ... )` handler, does it discover that it needs to do a redirect. The client-side React rendering of the login link form should never happen, but you see the HTML sent by server.

In production mode, the redirect will be done by the server directly and you'll never see the `/log-in/link` UI.

Is that in line with what you're seeing?

**Comment by tyxla** [comment]
Yep 👍  Makes sense, then. Let's ship it and see it in action with user bootstrapping.

**Review by tyxla — APPROVED** [review]
🚢

**Pull request merged**
