### PR TITLE
Licensing Portal: Add notices about automatic billing on credit card management screens

### PR DESCRIPTION
**Pull request by atanas-dev**
PT: pdpAdu-bj-p2
Card: 1201902532330136-as-1201935935452151

#### Changes proposed in this Pull Request

* Licensing Portal: Add notices that the primary payment method will be used for automatic invoice settlement on credit card management screens.

#### Testing instructions

* Apply patch and spin up Jetpack Cloud.
* Open http://jetpack.cloud.localhost:3000/partner-portal/payment-methods/add and confirm the notice is visible as in Screenshot 1. Complete the form to create a primary payment method.
* Open http://jetpack.cloud.localhost:3000/partner-portal/payment-methods/add again, uncheck "Set as primary payment method", and confirm the notice is not visible as in Screenshot 2. Complete the form to create a secondary payment method.
* Open http://jetpack.cloud.localhost:3000/partner-portal/payment-methods, click on the delete option for your primary payment method and confirm the notice is visible as in Screenshot 3. Complete the deletion.
* Open http://jetpack.cloud.localhost:3000/partner-portal/payment-methods, click on the delete option for your new primary payment method and confirm the notice is visible as in Screenshot 4. Complete the deletion to clean up after your tests.

Screenshot 1: Add primary payment method
Screen Shot 2022-04-13 at 16 32 06

Screenshot 2: Add a secondary payment method
Screen Shot 2022-04-13 at 16 32 21

Screenshot 3: Delete the primary payment method when a secondary is available
Screen Shot 2022-04-13 at 16 32 57

Screenshot 4: Delete the primary payment method when a secondary is not available
Screen Shot 2022-04-13 at 16 30 56

### CODE REVIEW

**Comment by jessefriedman** [comment]
@atanas-dev can we change the language to "By storing your credit card you agree to have it charged automatically each month."

**Review by kallehauge — COMMENTED** [review]
> can we change the language to "By storing your credit card you agree to have it charged automatically each month."

@jessefriedman's suggestion revealed two things for me: 1) we might as well call it "credit card", but I've kept it as "payment method" for consistency. 2) we might need some more specific messaging depending on the context so I've added the following texts:

* When adding a primary payment method: `By storing your payment method as primary you agree to have it charged automatically each month.`.
* When adding a "not primary" payment method: `By storing your payment method you agree to it potentially being used for monthly invoices in the future.`
* When deleting the primary payment method and automatically assigning next payment method as primary: `Your primary payment method will be charged automatically each month.`

---

The rest of the implementation looks good to me 👍

**Comment by atanas-dev** [comment]
@jessefriedman do we have your approval on the changes André has introduced to the wording?

**Comment by jessefriedman** [comment]
**When adding a primary payment method**: By storing your primary primary payment method you agree to have it charged automatically each month.

**When adding a "not primary" payment method**: 
**Question**: What happens if the primary payment method fails? Do we automatically try the secondary payment method?  

**When deleting the primary payment method and automatically assigning next payment method as primary:** 
**Question**: When deleting your primary payment method does the backup automatically become the primary? What if you delete your primary without a backup?

**Comment by atanas-dev** [comment]
@jessefriedman 

> By storing your primary primary payment method you agree to have it charged automatically each month.

Updated - I've dropped the second "primary" though ;)

> What happens if the primary payment method fails? Do we automatically try the secondary payment method?

No, Stripe will automatically retry the same payment method using their [Smart Retries](https://stripe.com/docs/invoicing/automatic-collection#retry-schedule) schedule.

> When deleting your primary payment method does the backup automatically become the primary? What if you delete your primary without a backup?

When deleting a payment method you will be shown the secondary payment method that will be promoted to your new primary one as seen on the bottom of the delete dialog:
delete-card

> What if you delete your primary without a backup?

You will no longer be allowed to issue licenses until you add a new primary payment method (adding only a single payment method will automatically mark it as primary).

**Comment by jessefriedman** [comment]
> No, Stripe will automatically retry the same payment method using their [Smart Retries](https://stripe.com/docs/invoicing/automatic-collection#retry-schedule) schedule.

Should we even allow for a secondary payment method? If that's not a can of worms we want to open then I don't think we need a note when someone is adding a secondary payment method if the primary will remain marked as primary.  Does it get a UI flag or something to say "primary"? 

-----

**With the context of the switch shown above this makes sense to me:** 

> **When deleting the primary payment method and automatically assigning next payment method as primary:** Your primary payment method will be charged automatically each month.

**Comment by atanas-dev** [comment]
> Does it get a UI flag or something to say "primary"?

Yes, there's a label added to the list view which marks the primary payment method.

Here are all relevant states after the latest changes:
|  |  |
| - | - |
| Screen Shot 2022-04-12 at 16 26 14 | Screen Shot 2022-04-12 at 16 26 19 |
| Screen Shot 2022-04-12 at 16 27 05 | Screen Shot 2022-04-12 at 16 26 51 |

**Comment by jessefriedman** [comment]
ok great! @atanas-dev & @kallehauge how does this feel?

**When adding a primary payment method:** By storing your primary payment method you agree to have it charged automatically each month.

**When adding a "not primary" payment method:**  Don't add anything.  The customer has to do something to make it the primary and they will either be see the message above or below depending on their flow, correct? 

**When deleting the primary payment method and automatically assigning next payment method as primary:** Your new primary payment method will be charged automatically each month.

**When deleting the primary payment method and there is no backup:** Issuing new licenses will be paused until you add a new primary payment method.

**Comment by atanas-dev** [comment]
The notices look good to me - I've updated the PR accordingly.

**Review by kallehauge — APPROVED** [review]
LGTM and tests well 👍 

---

@atanas-dev would you mind updating the summary with the new screenshots when you merge it?  🙌

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/7223815

Thank you @atanas-dev for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/7223815).

**Pull request merged**
