### PR TITLE
Analytics: Correct non-compliant default import obj destructure

### PR DESCRIPTION
**Pull request by sirreal**
The lib/analytics module exports and object as default. Destructuring
this object in an import is non-compliant and creates errors as soon as
a named export is added to lib/analytics.

Correct to import the object then use destructuring assignments to
access the properties, or access them directly.

No functional changes.

See #20119. Required for #20236

## Testing
1. Look for more incorrect usage. Here's what I've used:
   ```sh
   $ ack "\}\s*from\s*["'"'"']lib/analytics/?(?:index(?:\.jsx?)?)?["'"'"']" client server
   ```
1. Visually inspect the changes for correctness.
1. Ensure there are no behavioral changes in the modified files.

### CODE REVIEW

**Comment by sirreal** [comment]
In progress… I've just detected a few more.

**Comment by ockham** [comment]
Hmm, it'd be nicer to change `lib/analytics` to export these things individually. Think that would be a lot more work?

**Comment by sirreal** [comment]
> Hmm, it'd be nicer to change lib/analytics to export these things individually. Think that would be a lot more work?

On one hand, yes that would be nice. On the other hand, that part is completely compliant, it's the _imports_ that violate compliance, so arguably where the fix should occur.

But to answer your question, my first thought was to do just what you describe. Yes, I judged that to be a lot more work and more involved.

To achieve the same functionality as this non-compliant version, all of the properties of `analytics` would need to become named exports, and `analytics` would need to continue being the default export. However, I took a look through this PR and it seems that just `{ mc, tracks, ga, pageView }` would be sufficient as named exports and save a fair amount of work. How would you feel about that?

```js
export {
  analytics as default,
  ga,
  mc,
  pageView,
  tracks,
};
```

**Comment by ockham** [comment]
> However, I took a look through this PR and it seems that just `{ mc, tracks, ga, pageView }` would be sufficient as named exports and save a fair amount of work. How would you feel about that?
>
> ```js
> export {
>   analytics as default,
>   ga,
>   mc,
>   pageView,
>   tracks,
> };
> ```

I'd ❤️ that! 😄

**Comment by sirreal** [comment]
>I'd ❤️ that! 😄

I'm sorry to say it's quite ugly and invasive 😞 
See #20247

**Comment by ockham** [comment]
> I'm sorry to say it's quite ugly and invasive 😞
> See #20247

As [noted there](https://github.com/Automattic/wp-calypso/pull/20247#issuecomment-347249734), fine to go with this PR in order to unblock #20236 IMO.

**Comment by sirreal** [comment]
#20256 is an obvious and less invasive version of #20247 🙄

**Pull request closed without merging**
