### PR TITLE
Fix/template picker overflow

### LINKED ISSUE #38884: Template preview content expanding past preview frame (and sometimes too close to the frame).
Template preview content is expanding beyond the preview frame or right up to the edge of the frame and looks either "very broken" or "broken" in Chrome on MacOS. Some examples …

Expanding beyond the template preview …

image

Too close to the edge of the preview …

image

cc @apeatling @iamtakashi @alaczek

### PR DESCRIPTION
**Pull request by noahtallen**
#### Changes proposed in this Pull Request
* Fix layout selector preview

#### Testing instructions
* Sync to wpcom, sandbox the test site and public-api, and make sure the layout preview looks correct.

Fixes #38884

### CODE REVIEW

**Comment by noahtallen** [comment]
Original PR: https://github.com/Automattic/wp-calypso/pull/39002

**Comment by ramonjd** [comment]
**Before**

Screen Shot 2020-01-28 at 6 04 28 pm

**After**
Screen Shot 2020-01-28 at 6 03 11 pm

It looks good to me. Only that now, there seems to be an excess of padding in the thumbnail elements. 

Trying to track it down, but maybe in `.template-selector-item__preview-wrap` ?

**Comment by noahtallen** [comment]
cc @apeatling, we'll merge this to master again so that we can go ahead with a plugin update asap

**Comment by apeatling** [comment]
Thank you!

**Pull request merged**
