### PR TITLE
Framework: use a single localforage config

### LINKED ISSUE #3282: sync-handler: localforage defaults should be moved out of config and into module
Currently our localforage configuration lives in our config settings (e.g., [development.json](https://github.com/Automattic/wp-calypso/blob/master/config/development.json#L156)). But this is not something that needs to be managed separately for different environments. It's more likely that if we want to change the localforage configuration, we'll want to do it along with code changes in a PR. So it would be better if the configuration just lived somewhere else in our codebase that can be required by both the sync-handler and redux persistence work.

/cc @retrofox @gwwar

### PR DESCRIPTION
**Pull request by gwwar**
This PR moves localforage defaults out of config and into `lib/localforage`. The sync handler and redux persistence now share the same browser storage. There is little chance for key collision because the reserved key for redux persistence is 'redux-state' and sync handler keys are hashed.

store

This fixes #3282. 

## Testing instructions

- In `development.json` set `persist-redux` to true
- Start Calypso
- Set localStorage.debug to 'calypso:state'
- Navigate to the posts page
- Examine local browser storage, you should see something similar to the screenshot above.
- Sync handler and the persisted redux store should behave normally and not throw errors.

cc @rralian @retrofox

### CODE REVIEW

**Comment by retrofox** [comment]
A default driver ins't set here. So following the documentation this will be our priority order. 

> By default, localForage selects backend drivers for the datastore in this order:
> - IndexedDB
> - WebSQL
> - localStorage

I think we're ok with that but I wonder if we you should set them explicitly to avoid future surprises.

**Comment by gwwar** [comment]
> A default driver isn't set here. 

:+1: I don't see the harm in explicitly setting the default order. Added in 3419fa6

**Comment by retrofox** [comment]
Tested. LGTM. :ship:

**Comment by gwwar** [comment]
Thanks! Going to squash commits.

**Pull request merged**
