### PR TITLE
Domains: Do not show domain contact info for non owners

### PR DESCRIPTION
**Pull request by eltongo**
#### Changes proposed in this Pull Request

This only allows the domain contact info to be viewed by the domain owners, and not other users of the same site.

Screenshot 2020-06-23 at 3 52 12 PM

#### Testing instructions

* For a site you are a member of, go to a registered domain you do not own
* Click on 'Update your contact information' from the navigation menu
* You should see the error shown in the screenshot above

### CODE REVIEW

**Comment by fditrapani** [comment]
> Click on 'Update your contact information' from the navigation menu

It feels wrong to show this if you can't actually do it. What if we keep this change you're making and remove the option, along with transferring, all together? The reason for keeping it is if someone were able to figure out the URL then the content wouldn't be accessible. 

I think I need to find a way to show the ownership for non-owners.

**Comment by eltongo** [comment]
Agreed. I'll remove both the transfer option and the contact info option.

**Comment by KokkieH** [comment]
We've had some confusion from HEs on this change, as it has also removed those options from the menu when we view an account via SU/SSP. In the past HEs could still navigate to those pages, for example to grab a direct link for a user, but just couldn't make any changes.

Would it be possible to retain the old behaviour for SU/SSP sessions? If it would be fairly simple to do, I think it would be helpful to HEs.

**Comment by eltongo** [comment]
@KokkieH Thanks for the feedback. I've created PR #43719 to keep displaying contact info and transfer options in the menu, regardless of permissions.

**Pull request merged**
