### PR TITLE
SectionHeader: Add Learn more support link in PeopleListSectionHeader

### LINKED ISSUE #69947: Users: Privacy Information link is broken in Followers section
### Quick summary

When you click the (i) icon in Users → Followers you'll see the link Privacy Information that points to `https://wordpress.com/people/followers/{SITENAME}#privacy` and hence leads to the same page instead of supposedly to an external support page.

### Steps to reproduce

1. On a site where you have at least one follower go to Users → Followers
2. Click the (i) icon to expand the modal window
3. Click Privacy Information

### What you expected to happen

An external support page to be opened (maybe https://wordpress.com/support/followers/ but it lacks the Privacy Information section, so maybe it should be another page)

### What actually happened

The same page reloads

### Context

Noticed while working on 5665433-zd-woothemes

### Platform (Simple, Atomic, or both?)

Simple

### Theme-specific issue?

No

### Browser, operating system and other notes

_No response_

### Reproducibility

Consistent

### Severity

Most (> 50%)

### Available workarounds?

No but the platform is still usable

### Workaround details

_No response_

### PR DESCRIPTION
**Pull request by sejas**
#### Proposed Changes

* Iteration over https://github.com/Automattic/wp-calypso/pull/71474
* Add Learn more support link in `PeopleListSectionHeader` by: 
  * Refactor `SectionHeader` by removing `popoverText` prop
  * Refactor `PeopleListSectionHeader` to pass `SupportInfo` using the label prop.
  * Add `privacyLink` false to avoid showing the privacy link on the Followers page.
  * Add Learn more `link` to https://wordpress.com/support/followers/

#### Testing Instructions

1. Visit `Users` > `Followers` and ensure the popover doesn't show "Privacy Information" link. Instead, we display a `Learn more` link.
2. Click on the link and observe a new page is open to the localized support page https://wordpress.com/support/followers/
3. Click on `Email Subscribers` and verify the Learn more link is visible and working.

#### Screenshots

**Followers**

| **Before** | **After** |
|---|---|
| Screenshot 2022-12-29 at 12 48 52 |Screenshot 2022-12-29 at 12 25 38 |

**Email Subscribers**

| **Before** | **After** |
|---|---|
| Screenshot 2022-12-29 at 12 50 51 | Screenshot 2022-12-29 at 12 25 51 |

#### Pre-merge Checklist

- [x] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [x] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [x] Have you checked for TypeScript, React or other console errors?
- [x] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [x] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

- Closes https://github.com/Automattic/wp-calypso/issues/69947

### CODE REVIEW

**Comment by mpkelly** [comment]
Tested and working. I prefer this approach over using `display: none`;

**Review by vykes-mac — APPROVED** [review]
@sejas This is a better approach than what I did,  Thank you! I will close my PR in favour of this one 👍

**Comment by sejas** [comment]
@vykes-mac , @mpkelly Thanks for reviewing.

After reading the [issue](https://github.com/Automattic/wp-calypso/issues/69947) again, I've decided to include a `Learn more` link to the support page (https://wordpress.com/support/followers/). This pattern can be found on `Settings > Writing` ([image](https://user-images.githubusercontent.com/779993/209947526-5ee24e4f-f5ca-4f27-a591-6216e8eb9f94.png)).
I'm also adding new translations to include a `.` to separate the sentences.

I've updated the screenshots showing the latest changes.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/7699058).

**Pull request merged**
