### PR TITLE
Jetpack Backup: Refactor ActionButtons, add test coverage

### PR DESCRIPTION
**Pull request by mattgawarecki**
#### Changes proposed in this Pull Request

(Includes #44648.)

* Move `ActionButtons` from `DailyBackupStatus` into its own component file.
* Add unit tests to cover `ActionButtons`.
* Rely more on selectors than passed-in properties.
* Remove unused property references from `DailyBackupStatus`.

#### Testing instructions

* Run all tests and check that they pass (especially `client/components/jetpack/daily-backup-status/test`).
* Check that the `DailyBackupStatus` card -- specifically the action buttons at the bottom -- work as they do in production. Be sure to cover all possible states, including:
  * backup and restore both being available for a given date;
  * backups being unavailable on a given date; and
  * backup available on a given date but lack of credentials for Restores.
* When checking `DailyBackupStatus`, verify that:
  * all Tracks events still trigger; and
  * all links still work.

#### Reference screenshots

Screen Shot 2020-08-04 at 15 29 57
Screen Shot 2020-08-04 at 15 30 25
Screen Shot 2020-08-04 at 15 30 46

### CODE REVIEW

**Comment by mattgawarecki** [comment]
Added a note to the PR summary: this PR includes #44648.

**Comment by rcanepa** [comment]
I forgot to mention that all tests passed.

**Comment by mattgawarecki** [comment]
Thanks! I'll look into these errors. 👍

**Comment by nsakaimbo** [comment]
👋 Friendly heads up: the type of error in the wp-desktop-source job is an intermittent out-of-memory issue that's become more frequent over the last couple of days. I just pushed a PR to mitigate this (i.e. bump the RAM available to the desktop job) in #44675 that should hopefully stabilize things. Apologies for the noise!

**Comment by mattgawarecki** [comment]
Wow, I completely flubbed/forgot the syntax for `useDispatch` before 😓 

These latest changes should help. In addition, I found that we haven't been sending Tracks events for downloads and restores all this time 😱 So this PR fixes that as well, now.

**Comment by rcanepa** [comment]
Forgot to say again that tests passed when I ran they for a second time.

**Pull request merged**
