### PR TITLE
Google Domains Owners: Add home banner

### PR DESCRIPTION
**Pull request by lupus2k**
Related to https://github.com/Automattic/dotcom-forge/issues/3473

## Proposed Changes

We add a banner on the top-carousel.

P2: p9Jlb4-8Df-p2
Figma: mbuq4o5QxohQpBU9YoexXo-fi-1542%3A28718

| Desktop | Mobile |
| --- | --- |
| image | image |

## Testing Instructions

* On your sandbox, apply this diff: D119284-code
* As an automattician
* Go to `/home` on a launched site.
* One of the banners should match the screenshot.
* Check impression track event: `calypso_customer_home_card_impression` > card: `home-task-google-domain-owners`
* Check CTA track event: `calypso_customer_home_task_start` > task: `home-task-google-domain-owners`

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

**Review by DustyReagan — APPROVED** [review]
Looks good!

I noticed two things that differ from the Figma. Can we get rid of the "2 minutes" copy at the top? And can we increase the width of the text box so we don't have that lone "out." on the third line?

banner

**Comment by lupus2k** [comment]
Hey @DustyReagan, I updated it following your suggestions + show the actions after the illustration on mobile.

**Comment by lsl** [comment]
The unittest failure is actually a typescript check, looks like this PR introduces an error somehow:

Trunk:
```
wp-calypso trunk tsc --noEmit --project client/tsconfig.json
client/my-sites/hosting/github/github-authorize-card/index.tsx:2:35 - error TS2307: Cannot find module '@automattic/request-external-access' or its corresponding type declarations.

2 import requestExternalAccess from '@automattic/request-external-access';
                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Found 1 error in client/my-sites/hosting/github/github-authorize-card/index.tsx:2
```

This PR:
```
wp-calypso add/google-domain-owners-top-banner tsc --noEmit --project client/tsconfig.json
client/my-sites/customer-home/cards/tasks/revive-auto-reverted-atomic/index.tsx:89:4 - error TS2322: Type '{ taskId: "home-task-reactivate-expired-plan" | "home-task-reactivate-atomic-transfer" | "home-task-reactivate-restore-backup"; illustration: string; title: string; description: ExistingReactNode; ... 5 more ...; isUrgent: true; } | { ...; }' is not assignable to type 'IntrinsicAttributes & LibraryManagedAttributes<ConnectedComponent<({ actionButton, actionBusy, actionOnClick, actionTarget, actionText, actionUrl, secondaryActionButton, secondaryActionBusy, secondaryActionOnClick, secondaryActionTarget, secondaryActionText, secondaryActionUrl, badgeText, completeOnStart, descriptio...'.
  Type '{ taskId: "home-task-reactivate-expired-plan" | "home-task-reactivate-atomic-transfer" | "home-task-reactivate-restore-backup"; illustration: string; title: string; description: ExistingReactNode; ... 5 more ...; isUrgent: true; }' is not assignable to type 'IntrinsicAttributes & LibraryManagedAttributes<ConnectedComponent<({ actionButton, actionBusy, actionOnClick, actionTarget, actionText, actionUrl, secondaryActionButton, secondaryActionBusy, secondaryActionOnClick, secondaryActionTarget, secondaryActionText, secondaryActionUrl, badgeText, completeOnStart, descriptio...'.
    Type '{ taskId: "home-task-reactivate-expired-plan" | "home-task-reactivate-atomic-transfer" | "home-task-reactivate-restore-backup"; illustration: string; title: string; description: ExistingReactNode; ... 5 more ...; isUrgent: true; }' is missing the following properties from type '{ title: ReactNode; description: ReactNode; scary?: boolean | undefined; isLoading?: boolean | undefined; illustration?: string | undefined; actionButton?: ReactNode; ... 26 more ...; store?: Store<...> | undefined; }': actionTarget, secondaryActionTarget, secondaryActionText, secondaryActionUrl, and 3 more.

89   <Task isUrgent { ...taskProps } taskId={ card } illustration={ disconnectedIllustration } />
      ~~~~

client/my-sites/customer-home/cards/tasks/verify-email/index.tsx:14:4 - error TS2322: Type '{ title: string; description: ExistingReactNode; actionText: string; actionOnClick: () => { type: string; showGlobalNotices: boolean; }; badgeText: string; showSkip: false; taskId: string; }' is not assignable to type 'IntrinsicAttributes & LibraryManagedAttributes<ConnectedComponent<({ actionButton, actionBusy, actionOnClick, actionTarget, actionText, actionUrl, secondaryActionButton, secondaryActionBusy, secondaryActionOnClick, secondaryActionTarget, secondaryActionText, secondaryActionUrl, badgeText, completeOnStart, descriptio...'.
  Type '{ title: string; description: ExistingReactNode; actionText: string; actionOnClick: () => { type: string; showGlobalNotices: boolean; }; badgeText: string; showSkip: false; taskId: string; }' is missing the following properties from type '{ title: ReactNode; description: ReactNode; scary?: boolean | undefined; isLoading?: boolean | undefined; illustration?: string | undefined; actionButton?: ReactNode; ... 26 more ...; store?: Store<...> | undefined; }': actionUrl, actionTarget, secondaryActionTarget, secondaryActionText, and 4 more.

14   <Task
      ~~~~

client/my-sites/hosting/github/github-authorize-card/index.tsx:2:35 - error TS2307: Cannot find module '@automattic/request-external-access' or its corresponding type declarations.

2 import requestExternalAccess from '@automattic/request-external-access';
                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Found 3 errors in 3 files.

Errors  Files
     1  client/my-sites/customer-home/cards/tasks/revive-auto-reverted-atomic/index.tsx:89
     1  client/my-sites/customer-home/cards/tasks/verify-email/index.tsx:14
     1  client/my-sites/hosting/github/github-authorize-card/index.tsx:2
wp-calypso add/google-domain-owners-top-banner git co trunk
Switched to branch 'trunk'
Your branch is up to date with 'origin/trunk'.
```

It only mentions these two `Task` card's but I suspect all would be failing the typecheck now but since only these two are `.tsx` they're the only ones raising the error.

```
     1  client/my-sites/customer-home/cards/tasks/revive-auto-reverted-atomic/index.tsx:89
     1  client/my-sites/customer-home/cards/tasks/verify-email/index.tsx:14
```

**Review by DustyReagan — APPROVED** [review]
LGTM

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/8800797

Thank you @lupus2k for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/8800797).

**Pull request merged**
