### PR TITLE
Split up lib/formatting

### PR DESCRIPTION
**Pull request by sgomes**
This PR splits up `lib/formatting` from a single monolithic file, to an index that re-exports individual functions. This allows `webpack` to tree-shake the library more effectively.

#### Changes proposed in this Pull Request

* Split up `lib/formatting`

#### Testing instructions

There are no significant code-changes, only moving things around. The unit tests and a successful build should be enough to verify that everything still works correctly.

### CODE REVIEW

**Comment by sgomes** [comment]
Looks like this change saves ~7KB (~2KB gzipped) on every entry point.

**Comment by sgomes** [comment]
Adding a few folks, in hopes of a review.

**Review by lynnbgriffith — APPROVED** [review]
🚀 Tests well!  Nice savings here!

**Comment by sgomes** [comment]
Thank you, @griffbrad! Happy to get this one merged! 😄

**Pull request merged**
