### PR TITLE
Media Library: Add Focus Styling to Images

### LINKED ISSUE #42412: No Focus Style on Media Library Images
`outline: none;` is set on all buttons, and the focus styles for the image buttons are not added back in.

#### Steps to reproduce

1. Go to the media library: https://wordpress.com/media/[subdomain].wordpress.com
2. Press `tab` until you arrive at the images
3. No focus style is present on images, so you don't know which image you're on

#### What I expected
Focus styles should be present to show where the focus is on images

#### What happened instead
There is no focus.

#### Browser / OS version
MacOS Catalina 10.15.4
Chrome 81.0.4044.138 

#### Screenshot / Video
**Showing the `activeElement` in the console is the image button**

**No focus style on the image button when it's the `activeElement`**

#### Context / Source

#manual-testing

### PR DESCRIPTION
**Pull request by Aurorum**
#### Changes proposed in this Pull Request

I thought that it'd make sense to give the images the same outline that appears when hovering over the image. If it's not clear enough, let me know and I can change it!

#### Testing instructions

Visit the Media Library (or Media Modal) and use `tab` to arrive at the images.

Screenshot 2020-05-20 at 16 50 52

cc @jeryj, @sixhours 

Fixes #42412

### CODE REVIEW

**Comment by jeryj** [comment]
Wow! Thanks for getting on this so quickly! I feel like the focus state is hard to see, especially on darker images. We'll probably need to add a different focus state. Is there another already-built focus state to draw from?

**Comment by Aurorum** [comment]
Yep, true. The outline focus is overriden by the button. That could be changed, although it looks like a box-shadow is used to prevent issues with the padding.

Perhaps just a new colour is necessary? I think that `--color-accent` would work well for most images in most schemes.

Screenshot 2020-05-20 at 18 28 43

**Comment by jeryj** [comment]
I think the thick pink focus definitely works, but I'd want feedback from design before implementing it. I think it'd be safe to reuse an existing style though, at least for now since some state would be better than no state. The focus for the tabs on pages/posts is a similar style, but blue. That may be a safer way forwards.

Pages tabs showing a solid blue focus ring on Scheduled

I've added a Design Needed label though. Hopefully someone will chime in with feedback here :)

**Comment by sixhours** [comment]
Hi from the future. 😜  I think using the accent color is a great idea, @Aurorum do you mind updating this and I'll test it/ship it?

**Comment by sixhours** [comment]
(Also works fine for me after a rebase:

```
git fetch origin
git rebase origin/trunk
git push -f
```

**Comment by Aurorum** [comment]
Hi! I merged this branch with `trunk` - is that okay?

**Pull request merged**
