### PR TITLE
Jetpack Pro Dashboard: update downtime monitoring check interval UI

### PR DESCRIPTION
**Pull request by yashwin**
Related to 1204992567518369-as-1205304913870392

## Proposed Changes

* This PR updates the monitor settings modal and dashboard UI to use the monitor `check_interval` when setting the time for downtime notifications vs a deferred time. The text has been updated from `Notify me about downtime after x minutes to `Monitor my site every x minutes` to reflect this. 

Screenshot 2023-08-23 at 8 57 55 AM

## Testing Instructions

* Ensure that you have a connected site on the dashboard available.
* Apply this PR.
* Open the monitor settings modal clicking on the clock/time icon. 
* Ensure that the text in the settings modal has been updated as described in the proposed changes. 
* Ensure that the monitor intervals 1,3,5,10,15,30 minutes and 1 hour are present.
* Save each option and ensure that the payload includes a `urls` property with the site url and check interval.
* Ensure that the response from saving the updated check interval is reflected in the `urls` property in the response.
* Verify the bulk edit and Reset Notification functionality works as expected.

## Pre-merge Checklist

- [x] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [x] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [x] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

**Review by oikeme — APPROVED** [review]
Tested and changes LGTM. We can ship this once backend changes regarding deferment are confirmed

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/8803790

Thank you @yashwin for including a screenshot in the description! This is really helpful for our translators.

**Comment by worldomonation** [comment]
@yashwin FYI, this PR causes a permafail for the Unit Tests. Please see https://teamcity.a8c.com/buildConfiguration/calypso_calypso_WebApp_Run_All_Unit_Tests/10653668?hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandBuildChangesSection=true&expandBuildProblemsSection=true&expandBuildTestsSection=true.

image

**Comment by yashwin** [comment]
@worldomonation: This was not failing when I merged. I realized it later when I raised another PR. It is fixed here: https://github.com/Automattic/wp-calypso/pull/80997

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/8803790).

**Pull request merged**
