### PR TITLE
Signup: Free trials: Only show free trials on signup in the dev environment

### LINKED ISSUE #1417: Free Trials: enable free trial signups
We need to enable free trials signups in `/plans` and in the Plan step in `/start`. The signup should allow users to get a plan trial without submitting credit card information. This trial should be set to expire 14 days after the date of signup.

### PR DESCRIPTION
**Pull request by scruffian**
This enables free trials in signup in dev.

Fixes #1417

**Testing**

1. `git checkout update/1417-free-trials-in-signup`
2. Open http://calypso.localhost:3000/start incognito
3. Assert that you are show the "Start free trial" button.

- [x] Code review
- [x] QA review

### CODE REVIEW

**Comment by spncrb** [comment]
Trial adds a year long subscription instead of just 14/17 days.

**Comment by fabianapsimoes** [comment]
A few issues related to problems in this flow, just so we make sure to close them before merging this:

- https://github.com/Automattic/wp-calypso/issues/900 - the confirmation notice overlaps with the sidebar
- #1151 - `/plans` has no indication a free trial is active 
- #1372 - it's possible to get Google Apps with a trial domain

**Comment by fabianapsimoes** [comment]
> Trial adds a year long subscription instead of just 14/17 days.

Just adding that this seems to happen in all cases of trial signup: from `/start` with a new account, from `/start` for an existing account, and from `/plans` for an existing site. We're testing this proxied and unsandboxed.

**Comment by fabianapsimoes** [comment]
We tested this a bit more:

- not proxied, not sandboxed: no free trial flow, you see the credit card form (which is expected).
- proxied, not sandboxed: free trial flow, but full subscription instead of a 14-day one.
- proxied, sandboxed: free trial flow, and a 14-day subscription (which is how it should work).

**Comment by scruffian** [comment]
This patch should fix those issues: https://mc.a8c.com/pb/10333/

**Comment by spncrb** [comment]
Works from the scruffian sandbox - :+1:

**Comment by drewblaisdell** [comment]
:+1:

**Pull request merged**
