### PR TITLE
Updating link to wpcourses.com

### PR DESCRIPTION
**Pull request by jaswrks**
#### Changes proposed in this Pull Request

See: pcTixB-15-p2

#### Testing instructions

Open https://calypso.live/help?branch=update/bloggingu-link and confirm the following:

Screen Shot on 2021-05-05 at 15:57:49

Also confirm that it links to: https://wpcourses.com/

### CODE REVIEW

**Comment by MindyPostoff** [comment]
LGTM!

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/5873028

Thank you @jaswrks for including a screenshot in the description! This is really helpful for our translators.

**Review by sixhours — APPROVED** [review]
Looks good! 👍

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/5873028).

**Pull request merged**
