### PR TITLE
Add ReaderAuthorLink and ReaderSiteStreamLink components

### PR DESCRIPTION
**Pull request by bluefuton**
`ReaderAuthorLink` and `ReaderSiteStreamLink` are new components that accept a post object and then figure out how to link to an author's site, or the feed's stream respectively.

They also record relevant stats when the link is clicked.

The old `site-link` currently exists inside `client/reader` and is removed with this PR. It's not currently in use.

### To test

Neither component is yet in use, but you can see them in action on the app components example page:

http://calypso.localhost:3000/devdocs/app-components

Test live: https://calypso.live/?branch=add/reader/author-and-site-link-components

### CODE REVIEW

**Comment by TooTallNate** [comment]
Tested on calypso.live.

The `ReaderAuthorLink` doesn't seem to do anything on the devdocs page, but I'm assuming that's due to `page.js` and that we're on the same domain already (correct me if I'm wrong here).

The `ReaderSiteStreamLink` seems to work splendidly!

**Comment by TooTallNate** [comment]
No comments/nits on the code. LGTM! 🚢

**Comment by bluefuton** [comment]
> The ReaderAuthorLink doesn't seem to do anything on the devdocs page, but I'm assuming that's due to page.js and that we're on the same domain already (correct me if I'm wrong here).

That's odd! It should open https://wpcalypso.wordpress.com/ in a new window:

https://cloudup.com/cqthbdtq4nC

Would you mind giving it another spin @TooTallNate and see if you can repro?

**Comment by blowery** [comment]
I couldn't repro the issue @TooTallNate saw. Looks good to me.

**Pull request merged**
