### PR TITLE
Performance improvements to webpack2.x configuration

### PR DESCRIPTION
**Pull request by samouri**
This PR branches off of https://github.com/Automattic/wp-calypso/pull/14786 and attempts to address the performance concerns even further.

Things to try:
- [x] turn off codesplitting for development
- [x] use happypack

cc @gwwar @ehg

### CODE REVIEW

**Comment by samouri** [comment]
Turning off code-splitting turned incremental builds from 17s --> 4s.
Using happypack left me with these speeds:
initial run: server: 30s, client: 70s
second run: server 20s, client: 50s

thats a 20s improvement in server initial run, 100s improvement for client initial run, and then a 20s improvement for client second run.

Compare results to those from: https://github.com/Automattic/wp-calypso/pull/14786#issuecomment-308179697

**Comment by samouri** [comment]
This is significantly faster in almost every way than current webpack1.x  🎉 

Does anyone see any issues with disabling code-splitting in dev?

**Comment by ehg** [comment]
> Does anyone see any issues with disabling code-splitting in dev?
Yes, it makes it harder for us to notice when it breaks when deploying — and takes us further away from a production environment. Let's examine all other ways to make our build faster.

**Comment by samouri** [comment]
> Yes, it makes it harder for us to notice when it breaks when deploying — and takes us further away from a production environment. Let's examine all other ways to make our build faster.

Part of me thinks of code-splitting as merely another optimization that isn't really necessary in dev.  it slows down initial build, second build, and incremental build.

Without code-splitting inc build is down to 1-4s, its pretty amazing.  I know personally i'll probably manually disable it on most runs of `npm start`.

For now i'll re-enable code-splitting we can discuss it more later

**Comment by ehg** [comment]
> Without code-splitting inc build is down to 1-4s, its pretty amazing. I know personally i'll probably manually disable it on most runs of npm start.

Please don't, it will bite you some day :)

**Comment by samouri** [comment]
Current speeds with code-splitting enabled again:
initial build: server 32s, client 83s,
second build: server 19s client 57s
inc: 15s

**Pull request merged**
