### PR TITLE
Stats: Release horizontal bar chart modules, take two

### LINKED ISSUE #69044: Stats: Add horizontal bar chart background for stats modules
Part of the modernization project (p1HpG7-igQ-p2). Perhaps we could do this using dynamic styling?

# Development
- [x] Create a horizontal bar chart data table component
(#69117 by @grzegorz-cp)
- [x] Integrate the new component in the Traffic page
  - #69545
  - #69726 
  - #69812 
  - #69841
  - #69915
- [x] Release to production

# Designs

Image

Image

Image

### PR DESCRIPTION
**Pull request by jsnmoon**
This reverts commit ac5971e98b0249bdb7b4b617e3b40cf65ae128ba and is another attempt of #69970.

#### Proposed Changes

image

Enables the new horizontal bar lists for all stats modules in the Traffic page.

#### Testing Instructions

* Open the Calypso live branch for this PR.
* Navigate to the Traffic Stats page and ensure all the Stats modules include horizontal bar chart backgrounds.

#### Pre-merge Checklist

- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

Fixes #69044.

### CODE REVIEW

**Review by kangzj — APPROVED** [review]
It works well for me and the changes look reasonable. Looking nice! 👍

**Comment by kangzj** [comment]
Restarted TeamCity E2E - the errors don't seem relevant to the PR tho.

**Comment by keoshi** [comment]
This looks awesome!

**Comment by keoshi** [comment]
Noticed that we're losing the ability to mark a referrer as spam:

Before | After
--|--
image | image

Wonder if we could keep this functionality, which might be important for some users, by having the ellipsis show up next to the external link icon, similar to what happens in the Posts & Pages module:

image

**Comment by jsnmoon** [comment]
> Noticed that we're losing the ability to mark a referrer as spam:
> [images]
>
> Wonder if we could keep this functionality, which might be important for some users, by having the ellipsis show up next to the external link icon, similar to what happens in the Posts & Pages module (@keoshi)

This is definitely a regression; investigating now!

**Comment by jsnmoon** [comment]
@keoshi: Spam marking functionality has been restored in 7d4102c.

**Comment by keoshi** [comment]
@jsnmoon Beautiful implementation with the modal dialog! 🌟 

image

Thank you.

**Review by keoshi — APPROVED** [review]
Design-wise this is ready for prime time!

**Comment by jsnmoon** [comment]
@danjjohnson: We expect to release this feature in the next 24 hours.

This PR enhances all existing stats modules on the Traffic page with horizontal bar chart backgrounds while preserving all existing functionality. There's a chance for regressions with this change (we caught two that halted our previous attempt to deploy this feature), so please let us know if we missed any existing functionality with this upgrade.

Before|After
--|--
image|image

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/7626800

Thank you @jsnmoon for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/7626800).

**Pull request merged**
