### PR TITLE
Signup: DSS: Keep DSS theme previews onscreen at narrow screen widths.

### LINKED ISSUE #1324: Signup: DSS: screenshots on iOS Safari cause horizontal scroll
On an iPhone 5s:

img_3469

### PR DESCRIPTION
**Pull request by kwight**
Fixes #1324.

### CODE REVIEW

**Comment by kwight** [comment]
@sirbrillig for review

**Comment by sirbrillig** [comment]
Looks good, but we should rebase it on master instead of on #1333

**Comment by kwight** [comment]
Rebased away 164d9d8d1b03f6fd4b49379a9b2b3c56d2d51cba.

**Comment by sirbrillig** [comment]
:+1:

**Pull request merged**
