### PR TITLE
Checkout: Minor copy update for BBE sidebar

### PR DESCRIPTION
**Pull request by aneeshd16**
#### Proposed Changes

Ref: p1667584601669609-slack-C02KVCAL7GX

Copy update on the sidebar on the checkout screen when the BBE product is in the cart.

#### Testing Instructions

* Go to `/start/do-it-for-me` and go through the flow steps.
* On the checkout page, confirm that in the sidebar, the last item is `Receive your finished site in 4 business days or less!`

#### Pre-merge Checklist

- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes? -NA
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)? -NA
- [x] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector] -NA(https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md) -NA
- [x] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?

Related to #

### CODE REVIEW

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/7616226

Hi @aneeshd16, could you please edit the description of this PR and add a screenshot for our translators? Ideally it'd include this string: `Receive your finished site in %d business days or less!`

Thank you in advance!

**Review by ddc22 — APPROVED** [review]
LGTM 🚢

**Comment by aneeshd16** [comment]
Merging since ES has been translated.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/7616226).

**Pull request merged**
