### PR TITLE
[Backlog] Plans: standalone custom design feature page

### PR DESCRIPTION
**Pull request by artpi**
This PR introduces feature landing page for 'custom design'
It also cherry-picks commits from #4658, will be removed once 4658 is merged.

## TODO

- Images 

## Business / Premium plan owners
zrzut ekranu 2016-04-13 o 18 02 41

CC @adambbecker @mtias @rralian @gwwar

### CODE REVIEW

**Comment by drw158** [comment]
How will they get to the page in the second screenshot? Just by typing in the URL?

**Comment by drw158** [comment]
For free plan owners:

> Get Custom Design with Premium
> Make your site unique with custom fonts, custom colors, a CSS editor, and more.

**Comment by rralian** [comment]
> How will they get to the page in the second screenshot?

@drw158 I think it makes the most sense to link users from the customizer. We can do this without a nudge component, just using the existing upgrade flow in the customizer. See the video:

https://cloudup.com/czTSlXJ6J-X

On a free plan, open the customizer, click "custom design" and then you get three new areas where you can test updates: "Colors & Backgrounds", "Fonts", and "CSS". From these sections we currently link to the `/plans` page. If we're creating a "custom design" feature page, this is a good spot for it.

I would still implement this as a 50/50 split test to see how well the feature page converts against the basic `/plans` page.

**Comment by artpi** [comment]
@drw158 
> How will they get to the page in the second screenshot? Just by typing in the URL?

Both pages from screenshots live under the same URL. Second one just detects that you have Business plan and shows something different.
It links to customizer.

**Comment by mtias** [comment]
@rralian why not link to `/plans/compare` instead with highlighted row?

**Comment by drw158** [comment]
@artpi I meant, theoretically, a person with the GA upgrade already should never see a nudge/link to this feature page, so therefore they would never access this page unless they directly typed in the URL.

Just trying to get a sense of how business users will see this page, as that will inform the design and what text will be displayed.

**Comment by adambbecker** [comment]
In terms of visuals, here are some updates for the initial page I think could work:

custom_design-feature

**Comment by rralian** [comment]
> @rralian why not link to /plans/compare instead with highlighted row?

Yeah, you're right @mtias. Maybe a 33/33/34 test would be better, trying out feature-page, plans, and plans/compare. Would be good to confirm whether our findings are consistent across nudges.

**Comment by rralian** [comment]
I'm moving this into the backlog for now, as our initial experiments with feature pages didn't show as much lift as we hoped.

**Comment by artpi** [comment]
I'm closing this for now

**Pull request closed without merging**
