### PR TITLE
Jetpack site-less Checkout: hide references to `siteless.jetpack.com` domain from Purchases section

### PR DESCRIPTION
**Pull request by rcanepa**
#### Changes proposed in this Pull Request

* Remove references to `siteless.jetpack.com` from the Purchases section that don't add useful information and might be confusing to some users.

#### Testing instructions

* Run this PR locally with `yarn start`.
* Sandbox `public-api.wordpress.com`.
* Enable `USE_STORE_SANDBOX` so you can use a fake credit card (using credits makes appear many other warnings in the Purchase section and we won't be dealing with them on this PR).
* Purchase a product and a plan.
* Visit the `/me/purchases` section.
* Make sure the purchases look like in the PR (you should not see any reference to `siteless.jetpack.com`).
* Visit the purchase records of both the product and the plan.
* Make sure the purchase records look like in the PR (you should not see any reference to `siteless.jetpack.com`).
* Go through the cancellation flow and make sure the last step looks like the capture below (no references to `siteless.jetpack.com`).

Related to 1200479326344990-as-1200641987599725

#### Demo

The images on the left correspond to how things look now in production, on the right how they look after these changes.

##### `/me/purchases`
<p align="center">
  
  
</p>

##### `/me/purchases/siteless.jetpack.com/:purchaseId` – Product view
<p align="center">
  
  
</p>

##### `/me/purchases/siteless.jetpack.com/:purchaseId` – Plan view
<p align="center">
  
  
</p>

##### `/me/purchases/siteless.jetpack.com/:purchaseId` – Cancel product modal
<p align="center">
  
  
</p>

##### `/me/purchases/siteless.jetpack.com/:purchaseId` – Cancel plan modal
<p align="center">
  
  
</p>

### CODE REVIEW

**Review by atanas-dev — COMMENTED** [review]
https://github.com/Automattic/wp-calypso/blob/update/me-purchases-references-to-siteless-jetpack/client/me/purchases/remove-purchase/index.jsx#L256 also has a reference to the domain when trying to remove a plan.
Since I see that modal in your screenshots maybe you've missed to commit that change?

Other than the above - LGTM :+1:

**Comment by rcanepa** [comment]
> https://github.com/Automattic/wp-calypso/blob/update/me-purchases-references-to-siteless-jetpack/client/me/purchases/remove-purchase/index.jsx#L256 also has a reference to the domain when trying to remove a plan.
> Since I see that modal in your screenshots maybe you've missed to commit that change?
> 
> Other than the above - LGTM 👍

Instead of patching that line, I decided to hide the button that allows users to remove or cancel a subscription. This is because I think users would rather ask for a refund than remove/cancel their subscription.

**Review by cbauerman — APPROVED** [review]
Looks good!
> I decided to hide the button that allows users to remove or cancel a subscription. This is because I think users would rather ask for a refund than remove/cancel their subscription.

I also think this knocks out 1200479326344990-as-1200631299519252

LGTM!

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/6287644

Thank you @rcanepa for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/6287644).

**Pull request merged**
