### PR TITLE
Update node to 16.13.2

### PR DESCRIPTION
**Pull request by flootr**
#### Changes proposed in this Pull Request

Update node to 16.13.2. See the [full changelog](https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V16.md#16.13.2)

### CODE REVIEW

**Comment by noahtallen** [comment]
Running the base image build here to give it a test: https://teamcity.a8c.com/buildConfiguration/calypso_BuildBaseImages/7260051?showRootCauses=false&expandBuildChangesSection=true

**Comment by noahtallen** [comment]
Might be worth double-checking the test failures

**Comment by flootr** [comment]
@noahtallen seems like tests are green now 🍏 would you mind another look?

**Review by noahtallen — APPROVED** [review]
Looks good!

✅ Yarn install works
✅ Calypso.localhost works well
✅ Building the base image works (https://teamcity.a8c.com/buildConfiguration/calypso_BuildBaseImages/7351747?showRootCauses=false&expandBuildChangesSection=true)

**Pull request merged**
