### PR TITLE
Dev Survey: Ensure Consistent Colour Scheming

### LINKED ISSUE #94014: The Developer Survey modal has the wrong colors
## Description
See context: pbxlJb-6dR-p2, 09:55.

Currently, the accent color of the Developer Survey doesn't match the accent color of the UI.
Image

The color for the following areas should be updated to `#3858E9`.
Note that the image is SVG so that could be updated as well.
Image

### PR DESCRIPTION
**Pull request by Aurorum**
Fixes #94014

## Proposed Changes

* Ensures that the colour scheming on for the Dev Survey is consistent with the rest of Calypso by using the correct colour variable. 

## Why are these changes being made?
The colours currently don't match the rest of the UI because they have been hardcoded using Core Gutenberg colours (whereas they should be using Blueberry colours). 

## Testing Instructions

Navigate to `/me/developer` and verify that the colours and buttons appear correctly. 

| Before | After |
|--------|--------|
| Screenshot 2024-09-02 at 12 33 25 | Screenshot 2024-09-02 at 12 33 12 |

cc @taipeicoder, @nightnei, @wongasy

### CODE REVIEW

**Comment by matt-west** [comment]
Thanks @Aurorum. Tested and working correctly. 👍 

@nightnei Can you review the code so we can get this fix merged.

| Before | After |
|--------|--------|
| Screenshot 2024-11-29 at 08 51 26 | Screenshot 2024-11-29 at 08 45 10 |

**Comment by taipeicoder** [comment]
@Aurorum would you mind rebasing this? Thanks!

**Comment by Aurorum** [comment]
Sure - all done!

**Review by taipeicoder — APPROVED** [review]
Looks great! Thanks @Aurorum, happy holidays.

| Before | After |
| --- | --- |
| Screenshot 2024-12-25 at 3 07 28 PM | Screenshot 2024-12-25 at 3 05 54 PM|

**Pull request merged**
