### PR TITLE
ExPlat: Update UseExperiment README

### PR DESCRIPTION
**Pull request by aaronyan**
## Proposed Changes

* Update README for `UseExperiment` to document issues with calling it from multiple places in the render tree.
* See pbmo2S-2sV-p2 for more details

I'm still growing my React skills, so I welcome any suggestions to make my explanations clearer or improve my use of terminology. Thanks for your understanding and help!

### CODE REVIEW

**Review by sirbrillig — APPROVED** [review]
Sounds fine to me! It's not a blocker, but another way to word this might be simply,

"Every component that calls `useExperiment` will return loading as true for at least one render, even if the experiment is already loaded."

**Comment by sirbrillig** [comment]
It's not a blocker, but another way to word this might be simply,

"Every component that calls `useExperiment` will return loading as true for at least one render, even if the experiment is already loaded."

**Comment by aaronyan** [comment]
Thanks so much @sirbrillig! I've adjusted to use your simplified wording.

**Review by sirbrillig — APPROVED** [review]
Love it.

**Review by jessie-ross — APPROVED** [review]

**Pull request merged**
