### PR TITLE
Activity Log: fix and test restore persistence

### PR DESCRIPTION
**Pull request by jsnajdr**
The Activity Log's `restoreProgress` reducer has a persistence bug. It's using the following wrapper combination:
```js
withSchemaValidation ( keyedReducer ( withoutPersistence ( reducer ) ) )
```
`withSchemaValidation` enables persistence and then `withoutPersistence` disables it again, resulting in no persistence.

This PR fixes that by using `withPersistence` instead, making the reducer forward-compatible with changes in #50625.

**How to test:**
1. Checkout the commit with the unit tests. Verify they fail.
2. Checkout the commit with the fix. Verify the tests start passing :+1:

### CODE REVIEW

**Review by tyxla — COMMENTED** [review]
This is looking good for the purpose of the PR! 

However, I'm not sure if it was the intended behavior 🤯  Did it mean to enable or disable persistence? I'm not 100% sure. Maybe we meant to not persist it after all?

**Comment by jsnajdr** [comment]
> However, I'm not sure if it was the intended behavior

The self-contradictory `withSchemaValidation( keyedReducer ( withoutPersistence() ) )` code is not what the original author (@sirreal) wrote. It's a result of @sgomes' codemod that removed `createReducer` and wrapped the codemodded reducers with `withoutPersistence`.

The original code is:
```js
withSchemaValidation( schema, keyedReducer( 'siteId', createReducer( { ... } ) ) )
```
Here the persistence also never worked because `createReducer` disabled it by default for reducers that don't have a `SERIALIZE` or `DESERIALIZE` handler. There's no unit test for the persistence.

@sirreal's intent certainly was to persist. The original #16092 PR talks about that.

@sirreal What was the goal of the persistence here? To continue polling for restore status even after the page is fully reloaded? That will work even without persistence because the UI will fetch rewind status from the REST API and it will contain info about a restore being in progress.

I think the persistence of `restoreProgress` could be removed without regret.

**Comment by sirreal** [comment]
The statute of limitations has expired on that work, but I'll share what I recall 🙂 

The goal was to persist the state of a restore, but especially to resume polling for in-progress deploys. As I recall, we had difficulty with stale state being persisted and/or in-progress restores not having polling resume. This would display UI that wasn't accurate and it was important that folks could come back to see information about restores they'd initiated which could take a long time to complete.

> Here the persistence also never worked because createReducer disabled it by default for reducers that don't have a SERIALIZE or DESERIALIZE handler.

I'm not convinced this is accurate. `createReducer` was wrapped in a `keyedReducer` and I believe the persistence happened at the outer level. This reducer opted-in by attaching a schema property which was handled by `combineReducers`:

https://github.com/Automattic/wp-calypso/blob/ad0f794a69a1fe7f401b040f9e71a6213636c168/client/state/activity-log/restore/reducer.js#L47-L52
https://github.com/Automattic/wp-calypso/blob/ad0f794a69a1fe7f401b040f9e71a6213636c168/client/state/activity-log/reducer.js#L10-L17
https://github.com/Automattic/wp-calypso/blob/ad0f794a69a1fe7f401b040f9e71a6213636c168/client/state/utils.js#L371-L379

This was some time ago and I haven't been working in this area for a few years. As long as the intentions above are covered (resume polling until in-progress restores are completed, resilient to page reloads) I think we're covered. Folks working around Jetpack restores should be able to help test this.

**Comment by tyxla** [comment]
cc @Automattic/yamato-backup-and-security

**Comment by jsnajdr** [comment]
> This reducer opted-in by attaching a schema property

That `schema` was attached to the result of `keyedReducer` though. So, on deserialization, schema was validated and the serialized state was passed further to the inner reducer's `DESERIALIZE` action.

But the inner `createReducer`, when called without a `schema` parameter, disabled persistence completely by defining `SERIALIZE` and `DESERIALIZE` handlers that always returned initial state. Which was `undefined` in this case. Nothing was ever serialized or deserialized.

I was unable to run the persistence tests added in this PR on that old commit (3945ee9b3f) from 2017, but by now I'm pretty sure it never worked.

> As long as the intentions above are covered (resume polling until in-progress restores are completed, resilient to page reloads)

The logic of the Restore UI is as follows:
- `<QueryRewindState siteId={ siteId } />` fetches the `RewindState` for the current site
- the `RewindState` has an optional `rewind.restoreId` field that's present when restore is in progress
- if there's a `restoreId` and the `rewind.status` is `running`, the UI will further `<QueryRewindRestoreStatus siteId={ siteId } restoreId={ restoreId } />`
- and then shows progress UI for that running restore

That will all happen even after a full reload of the page. The two `<Query*>` components will fetch the current state from the server without having to remember anything browser-side.

I'll remove the `restoreProgress` peristence and verify the above flow on a testing site.

**Comment by jsnajdr** [comment]
I confirmed today that Jetpack Restore continues to work seamlessly after the state persistence is removed. After starting a restore, I see the in-progress UI even after reloading the page:

Screenshot 2021-03-07 at 16 43 13

As expected, the React UI first loads the Rewind state (`wpcom/v2/sites/:siteId/rewind`) and after seeing a `rewind: { status: 'running', rewindId }` property there, starts polling the `rest/v1/activity-log/:siteId/rewind/:rewindId/restore-status` endpoint for updates.

The `state.activityLog` subtree is not persisted at all after this patch. There is no `redux-state:activityLog` item stored in IndexedDB.

**Review by tyxla — APPROVED** [review]
This LGTM 🚢

**Pull request merged**
