### PR TITLE
DismissibleCard: Update Gridicon import

### PR DESCRIPTION
**Pull request by spen**
#### Changes proposed in this Pull Request

* Fixes a linting rule warning rasied in #35970

### CODE REVIEW

**Comment by p-jackson** [comment]
Looks like wp-desktop failed to build. Trying a quick rebase to see if we get lucky 🤞. Otherwise it could mean that this is the first module that's had the gridicon change made that's actually used in desktop. Maybe desktop needs a webpack config update?

**Comment by p-jackson** [comment]
Nope :(

wp-desktop build has error `You may need an appropriate loader to handle this file type.` when loading `gridicons.svg`.

The svg file is being pulled into the desktop build in this import chain:
```
 @ ./calypso/client/components/gridicon/index.tsx 14:40-85
 @ ./calypso/client/blocks/dismissible-card/index.jsx
 @ ./calypso/client/components/banner/index.jsx
 @ ./calypso/client/my-sites/theme/main.jsx
 @ ./calypso/client/my-sites/theme/controller.jsx
 @ ./calypso/client/my-sites/theme/index.node.js
 @ ./calypso/client/sections.js
 @ ./calypso/server/pages/index.js
 @ ./calypso/server/boot/index.js
 @ ./desktop/server/server.js
 @ ./desktop/server/index.js
 @ ./desktop/app.js
 @ ./desktop/index.js
```

**Comment by sirreal** [comment]
Don't let the wp-desktop tests block you, it's a known issue:

https://github.com/Automattic/wp-desktop/issues/670

**Comment by p-jackson** [comment]
Fixed by #36150

**Pull request closed without merging**
