### PR TITLE
Akismet pricing: Upgrade calypso upgrade map

### PR DESCRIPTION
**Pull request by spsiddarthan**
Related to #

## Proposed Changes

* Replaced the upgrade map with the new plans. 

## Testing Instructions

- Apply the branch locally and spin yarn start OR use Live link provided below
- Enable the store sandbox. 
- Navigate to checkout/akismet/ak_pro5h_yearly and buy the yearly plan
- Navigate to /me/purchases and select the new Purchased Akismet plan. You will see the upgrade button. Clicking on it 
will take you to the checkout/akismet/ak_bus5k_yearly plan. Purchase it. 

Screenshot 2023-11-02 at 18 45 44

- Now, upgrade the business plan, which will take you to buy the ak_ep15k_yearly plan
- Purchase it and try to upgrade the ep15k plan, which will take you to the ep25k plan, and if you try to upgrade that it will you take to the https://akismet.com/enterprise/ page. 

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

**Review by CodeyGuyDylan — CHANGES_REQUESTED** [review]
I am not entirely sure why, but I am getting a cart error when trying to upgrade from Akismet 5k to Akismet 15k

image

**Comment by CodeyGuyDylan** [comment]
Apoligies, I saw that I didn't save my changes when switching to the store sandbox, I'll test again

**Review by CodeyGuyDylan — APPROVED** [review]
The code tested well once I actually used the store sandbox 😅 

I do have a question that I won't block approval for, but after these new plans are released and the old plans are marked unsellable, what will the "upgrade" button do on the old plans?

**Comment by spsiddarthan** [comment]
>I do have a question that I won't block approval for, but after these new plans are released and the old plans are marked unsellable, what will the "upgrade" button do on the old plans?

That's a good question, I will figure out an answer for that! Maybe the button shouldn't show up, but I will check it out. 

Thanks for your review, I will think about the above scenario before merging this one.

**Comment by spsiddarthan** [comment]
Yup, the upgrade button doesn't show up for the old plans. That's fine I reckon?

**Comment by jboland88** [comment]
Good question @CodeyGuyDylan - thanks for checking into it @spsiddarthan 

> Yup, the upgrade button doesn't show up for the old plans. That's fine I reckon?

Yes, having the upgrade button not show for these old plans is good 👍 I think that's the best thing to do right now.

:shipit:

**Pull request merged**
