### PR TITLE
Inline Help: Fix Focus Colours for Links

### PR DESCRIPTION
**Pull request by Aurorum**
## Proposed Changes

* Fixes the focus styles link for Inline Help.
* Most these changes are just me running the Linter. I'm not entirely familiar with this code so I'm hesitant to change it, but I don't get why the `import` at the top of the file is as it is. 

## Why are these changes being made?

The current colour contrast doesn't meet a11y standards on some schemes, and it looks strange on others. It should really be using the colour variable from the background. 

## Testing Instructions

Navigate to Me > Home and focus on a link in the "Recommended Resources" section.

| Before | After |
|--------|--------|
| Screenshot 2024-08-05 at 12 27 04 | Screenshot 2024-08-05 at 12 27 08 |

cc @arcangelini, @klimeryk

### CODE REVIEW

**Comment by escapemanuele** [comment]
Thank you @Aurorum! It looks fine to me!

I started some tests/builds, in the meanwhile I'd like to ask @lucasmendes-design for some design input here, if this is a good change (I hope to be able to provide you a live link, in the meantime check the screenshots :) )

**Comment by lucasmendes-design** [comment]
Thanks for the ping. I'm checking this out :)

**Comment by escapemanuele** [comment]
I see hover is now set like this
image

So maybe it is already fixed :)

**Comment by Aurorum** [comment]
Hi @escapemanuele, the bug here is that the wrong colour variable is being used, which means that it isn't fixed for some of the different colour schemes! The one in my screenshot is from Classic Dark, where I can see that there haven't been any changes yet.

**Review by escapemanuele — APPROVED** [review]
Thanks @Aurorum, then I believe this is good to go.
I believe I have to merge this, I'll do it later :)



@lucasmendes-design we can iterate later if you think something needs to change!

**Pull request merged**
