### PR TITLE
Remove `skipThemeSelectionModal` A/B test code.

### PR DESCRIPTION
**Pull request by mendezcode**
This PR removes the code in charge of adding the Skip Themes Selection Modal A/B test.

### CODE REVIEW

**Comment by mendezcode** [comment]
> What were the results of the test?

/cc @mapk

**Comment by mendezcode** [comment]
I still need to resolve the active tests conflict, will update in a bit.

**Comment by mapk** [comment]
I tested it locally and didn't notice any problems. Ran through the steps, skipping some, clicking 'back' and picking different themes. Everything seemed to be working correctly.

**Comment by mapk** [comment]
Ahh, as for the results of the A/B test, I'll be getting a post up soon. I'm going through the data with @fditrapani today and making a decision on how to proceed.

**Comment by alisterscott** [comment]
I saw this AB test is still in `client/lib/abtest/active-tests.js` in `master` - is there a reason why or was that a merge conflict?

**Comment by mendezcode** [comment]
@alisterscott It was because i forgot to update that file with the contents of `master`. Since it was basically a revert, I used the current version in `master` and it was okay after that.

**Pull request merged**
