### PR TITLE
Introduce TypeScript Support

### PR DESCRIPTION
**Pull request by dmsnell**
This change introduces the `awesome-typescript-loader` and dependencies
needed to write code for Calypso in TypeScript.

It does not introduce any actual TypeScript code.

It's a for-realz PR and the motivation is dealing with data models in Calypso though the benefits extend far beyond here.

## Why?

Because JavaScript cannot give us the guarantees we want with things (like what properties of the site object are being used) nor does it have a good was of providing a declarative data model (see my exploration in #14595).

TypeScript can give us this and all the benefits of static typing as well as the benefits of compiling our code.

## Why TypeScript and not Flow?

TypeScript is a compile-to-JS language while Flow is a type checker. There are strong advantages to both but my preference has been TypeScript since it's compiled and since it seems to be more conservative in its failures, as in it is more likely to fail a valid type than pass an invalid one.

TypeScript also may have the best IDE integration. Microsoft has put good effort into supporting useful autocomplete, error messages, and refactoring support. I could not find as much added benefit from Flow.

## Why TypeScript and now Elm/ReasonML?

You tell me!

## What negatives does this bring?

I'm not sure how this will impact compile time yet and it will be hard to measure since it's a gradual introduction. It's very possible that TypeScript compiles faster than our JS code merely on account of the static typing. It _is_ making type inference though so some additional delay could be expected.

TypeScript is also not JavaScript. It's very close and preserves most of the JS semantics (as a superset it kind of must) but there are new bits of syntax and style it presents that will be unfamiliar to people.

## Open Questions

TypeScript can compile to ES3, ES5, ES2015, ESNext, etc… Right now I'm having it generate ES2015 modules and preserve JSX then piping the results through Babel. The goal here is to preserve existing transforms we play out in Babel. We could just as easily skip the entire Babel chain and generate ES5 code. In my opinion this would be advantageous because it would certainly be much faster than going through Babel.

What should be written in TypeScript? Anything. Many teams have echoed a smooth transition from JS to TS. Many popular libraries already publish their type signatures and we can depend on them with a straightforward command, e.g. `npm install @types/redux`.

Is it worth it? As I've expressed quite a bit lately I think we have no choice but to start looking for a compile-to-JS language. It's my opinion that we will always be chasing browser compatibility and build performance and runtime performance with JS. TypeScript here provides marginal complexity but offers most of the desired goals. I would like to start using this in the new comments management section where we will be working with lots of data from comments and I'd like to pave the way to make that easy to optimize and hard to mess up.

### CODE REVIEW

**Comment by dmsnell** [comment]
> more build time woes

I'm not entirely sure this will be true. we have lots of potential to improve from where JS has brought us and this is one of the reasons I've been exploring this stuff.

**Comment by dmsnell** [comment]
> I want to see us focus on simplifying + speeding up our build system before we tack on more to it.

this is part of it @samouri - something like TypeScript allows us to simply bypass a big and slow part of our build process. it happens on a module-per-module basis too which means it doesn't disrupt anything.

**Comment by dmsnell** [comment]
> From my point if view we introduce a whole new language to hundreds of developers, while we can get the same semantic effect via JavaScript with some creativity.

@nb I can try :smile:

TypeScript isn't a whole new language to start with: it's built to preserve as much of JavaScript as it can. In fact though, we can't get the same effect in JavaScript. We can do far more with JavaScript because TypeScript is about forming guarantees and contracts with each other while JavaScript provides an anti-guarantee.

On the positive side:
  - TypeScript compiles to JS
    - It performs optimizations while still in TS which are unavailable once in JS
    - It can target ES3, ES5, ES2015, ESNEXT, etc… meaning we don't have to hunt down features (we currently do this with Babel) also we don't have to hunt down browser irregularities as much.
  - We can skip compilation stages that we currently have to use.
  - It provides type safety and will catch a wide array of bugs before they ship. It provides the kind of safety we need to pass around data objects in Calypso and removes all of the needless runtime type-checking we so often do (_e.g._ `site && site.options && site.options.setting`)
  - Types communicate intentionality in the code and lead to easier maintenance and refactoring. We can _know_ what code is dependent on such and such a property or value. We can _know_ when we make a change where other code would break were it to allow us to compile without fixing it. In JS we're left waiting for the bug reports to roll in.
  - Really well-regarded IDE support and integration for things like autocomplete and error reporting.
  - Incrementally deployed and sits happily right next to JS; even supports JSX. (TS is a proper superset of JS so all JS code is still valid TS)
  - Extensive community support and adoption.

On the negative side:
  - There is new syntax to learn for the type signatures.
  - One more webpack loader than we currently have
  - We have to address type-related bugs when developing instead of after shipping.

Uncertain:
  - Could be faster, could be slower. In the long run I believe it will be faster due to the fact that it's designed to be compiled and JS isn't. The compiler becomes far simpler for TS than what we have to write for equivalent JS code. That said, it could be slower since its performance type inference.

As an aside I'm not a huge fan of TypeScript. I think that abandoning JS entirely is the better path forward but that path involves a much wider language gap and larger paradigm shift (even though they are worth it). TypeScript and Flow both appeared to make up for some major shortcomings with JavaScript and I think TypeScript is a more appropriate choice for us (largely due to the fact that its compiled whereas Flow isn't). Flow annotations introduce fewer conceptual changes than TypeScript offers but it also becomes limited by that. It solves one problem while TypeScript solves several.

And how about making JS better? Well, we're always trying to make do with what we have, but JS's problems aren't superficial or syntactical. They are fundamental to the way the language works and no cleanup will fix those problems unless major breaking changes come about.

**Comment by samouri** [comment]
> We have to address type-related bugs when developing instead of after shipping.


I see you snuck that into the negative side even though its very clearly a positive 😄

**Comment by dmsnell** [comment]
> We have to address type-related bugs when developing instead of after shipping.
> I see you snuck that into the negative side even though its very clearly a positive 😄

well, I consider a positive but many don't (in honesty). why? here's how the dynamics change when we fix bugs after shipping that could have been automatically discovered before shipping:

 - the initial release delays a bit
 - the people who fix the bug are probably different people than those who program the bug
 - the time spent fixing the bug isn't attached to the time spent developing the feature

sure, overall we spend far less time on the same features when the compiler can automate bug discovery for us and recommend fixes, sure the runtime is faster and smaller because we don't need runtime type checks (the kind that litter our code), sure we end up iterating faster because we become aware of these kinds of bugs and the auto-correct helps us avoid them in the first place, but…usually it's someone else's job to fix the bugs…

**Comment by samouri** [comment]
@dmsnell: I think there may be issues combining typescript loaders with [happypack](https://github.com/amireh/happypack#does-it-work-with-typescript).  From what i've read though it _should_ be possible. 

Some questions I have now are:
- is it possible to use the ts compiler _instead of babel_ everywhere? Or is it preferable to pipe ts into babel.
- is there any sort of exit strategy possible? Lets say we decide go forward with TypeScript and a couple of teams adopt it.  1 month passes, and then we decide that while it was a good experiment, the tradeoffs aren't worth it.  Is there an easy automated way to remove all type annotations + type declarations from the code to re-javacscriptify it?

I've watched some talks + played with TypeScript a bit this week and it really does seem pretty great. IDE integration is so much better than what I was able to get working with flow back in the day.

**Comment by blowery** [comment]
tangent: https://github.com/Automattic/wp-calypso/pull/16005

Neat that it can find latent types in the existing JS and flag some errors. Also can pull type info from jsdoc, though the jsdoc has to be valid...

I'm all for adding a typed language option to Calypso. Typescript is fine by me. It would have saved my bacon a dozen times in the past month alone. 

It would definitely complicate the build. It's unclear (to me) how it will interact with scope hoisting / tree shaking. I _think_ we can just have ts output es6 modules and everything would be magic, but it requires a bunch of testing. 

But having types would be wonderful, especially with redux.

**Comment by dmsnell** [comment]
Someone please resurrect this PR at some point!

**Pull request closed without merging**
