### PR TITLE
Reader: Move to its own entry point

### PR DESCRIPTION
**Pull request by tyxla**
This PR is an experiment to move the Reader to its own entry point. Right now it doesn't do a wonderful job of reusing all the code possible between the different boot sequences, but I think this can be done in subsequent PRs if we decide to go with this approach.

#### Changes proposed in this Pull Request

* Create own boot for Reader
* Create a new entry point for the Reader
* Move out all Reader sections to the new entry point
* State: Update redux bridge when a reducer is added
* Layout: Remove link for notifications masterbar item

#### Testing instructions

* Checkout this branch and build Calypso from scratch.
* Smoke test all of Reader and verify it works well and as before.
* Verify the root route `/` works as it did before.

### CODE REVIEW

**Comment by sgomes** [comment]
The ICFY information isn't very helpful for this use-case, so I compared this PR with the branching point.

Branching point (as of this post): https://hash-34040def324f06eca0e324558ad25837cca84e75.calypso.live/read
This PR (as of this post): https://hash-349fd9a6fb812cf05d6c3a6b63abaf8154dc1bbc.calypso.live/read

It appears to result in a ~24KB saving when opening reader, which is a nice win!

However, I'm not sure if it's worth the tradeoffs in this case, namely the full load needed when navigating from Reader to e.g. My Sites. Given that Reader is the default entry point when logging in (I believe), I suspect that it's a very common route for users to go from `/log-in` to `/read` to `/stats`. There are still savings in that situation, in terms of JS bytes over the wire, but for slow CPU devices, the added bootup time is significant.

My initial inclination is to say that `/read` should probably not become its own entry point. Perhaps if further savings can be eked out?

**Comment by tyxla** [comment]
@sgomes thanks a bunch for the comparison. Yeah, so odd that ICFY isn't as helpful as usual in this case.

Anyway, I agree there are trade-offs and in the current state, we might want to keep it as-is. However, I chatted with @griffbrad about an intended change coming soon, that was going to change the default landing page for logged in users to something else (perhaps `/home/$primarySiteSlug` or something), but I'm not sure if there's a PR for that already, or even if it's still planned. 

@griffbrad do you have any more information about where that change is being discussed, and what's the progress there? Is there anything we can help with?

If that's still in the roadmap, separating the reader to its own entry point will make a lot of sense. And I agree that we could then make even more optimizations, this PR would only be a start

**Comment by sgomes** [comment]
> If that's still in the roadmap, separating the reader to its own entry point will make a lot of sense.

Yup, definitely agree with that! 👍

**Comment by tyxla** [comment]
> @griffbrad do you have any more information about where that change is being discussed, and what's the progress there? Is there anything we can help with?
> 
> If that's still in the roadmap, separating the reader to its own entry point will make a lot of sense. And I agree that we could then make even more optimizations, this PR would only be a start

This is the PR I was talking about: #39656

**Comment by tyxla** [comment]
This PR is ready for review - it has been rebased and updated to reflect the latest changes, related to introducing the root section and modularizing the posts state.

**Comment by griffbrad** [comment]
Should we hold off on this one until #39656 is merged?

**Comment by tyxla** [comment]
Sounds good 👍 Holding off until #39656 is merged.

**Comment by tyxla** [comment]
This one is ready to be reviewed now that it was rebased after https://github.com/Automattic/wp-calypso/pull/39656 landed.

**Comment by griffbrad** [comment]
@sgomes, would you be willing to take a final look at this one following the customer home changes?  From a performance standpoint, does this seem worthwhile now that Reader is not the default homepage for WP.com users?

**Comment by sgomes** [comment]
> @sgomes, would you be willing to take a final look at this one following the customer home changes? From a performance standpoint, does this seem worthwhile now that Reader is not the default homepage for WP.com users?

Sure, I'll take a look! I'll start by rebasing this.

**Comment by sgomes** [comment]
After rebasing, it appears that reader isn't working properly any more in the live branch. I may have merged conflicts incorrectly 😞

**Comment by sgomes** [comment]
Still failing, and I'm having trouble figuring out why, exactly.

**Comment by tyxla** [comment]
This is way too outdated, I'm going to close and consider exploring it again in the future.

**Pull request closed without merging**
