### PR TITLE
Fix/cleanup yarn lock

### PR DESCRIPTION
**Pull request by scinos**
#### Changes proposed in this Pull Request

* Adds CI step to Lint job to validate that `yarn.lock` does not have uncommitted changes.
* Cleans up existing uncommitted changes in `yarn.lock`
* Removed `--frozen-lockfile` since it doesn't do what we expect (yarnpkg/yarn#3313 yarnpkg/yarn#5847) to avoid any future confusion

From https://app.circleci.com/pipelines/github/Automattic/wp-calypso/58032/workflows/819cbf5a-ec40-4989-a89a-c57186712b9d/jobs/715945/steps
image

#### Testing instructions

1. Checkout the branch, delete `yarn.lock` and run `yarn`. Run this script in the console and verify it shows the error:

```
DIRTY_FILES=$(git status --porcelain 2>/dev/null)
if [[ ! -z "$DIRTY_FILES" ]]; then
  echo "Repository contains uncommitted changes: "
  echo "$DIRTY_FILES"
  echo "You may need to checkout the branch, run 'yarn' and commit those files."
fi
```

2. Revert local changes to `yarn.lock` and run the script again, you shouldn't see any error.

### CODE REVIEW

**Comment by simison** [comment]
I'm still confused (only skimmed linked issues); is there no way to prevent updates in `package.json` that are missing from lockfile or other way around?

**Comment by scinos** [comment]
> is there no way to prevent updates in package.json that are missing from lockfile or other way around?

As far as I know, there is no way to do that using yarn flags. There are a few examples on how to do it "externally" (check that `yarn.lock` has not changed) in https://github.com/yarnpkg/yarn/issues/5840

I did something similar in the CI config, now at least at test will fail if `yarn.lock` needs to be updated for any reason, for example because it no longer matches `package.json`

**Comment by sirreal** [comment]
Should we be removing `--frozen-lockfile` everywhere? It does seem like desirable behavior (if confusing):

> If you need reproducible dependencies, which is usually the case with the continuous integration systems, you should pass `--frozen-lockfile` flag.
> …
> `yarn install --frozen-lockfile`
> Don’t generate a yarn.lock lockfile and fail if an update is needed.

Do we have any theories on how we get into a state where the lockfile is out of date but not committed? I have a hard time imagining `yarn.lock` is modified locally but isn't committed.

**Comment by scinos** [comment]
IMO, the behaviour of `--frozen-lockfile` is broken, as it doesn't do what the doc says (build does not fail if an update of yarn.lock is needed). If we leave it around it can cause confusion and suggest the check for a dirty lockfile in CI is not needed.

My theories of why `yarn.lock` is not committed are:

1) People may have it in their local `.gitignore`
2) If you do `cd apps/full-site-editing && npm add ...`, `yarn.lock` is not updated at all. Although in this case you'll end up with a `package-lock.json`.
3) Maybe people are adding deps to `package.json` manually?

**Comment by scinos** [comment]
Looks like the new package was introduced in #41963

**Comment by scinos** [comment]
Extracted the commit to fix `yarn.lock` to #42041

**Comment by simison** [comment]
Incidentally, I just ended up with a change in lockfile by running `yarn dev --sync` in `apps/full-site-editing`:

image

I'd expect not to have these pop up while working.

**Comment by scinos** [comment]
@simison 

> Incidentally, I just ended up with a change in lockfile 

In this branch? I can't reproduce it in commit `1b936b2a81` (before the rebase) or `6fb03ad5b7` (after the rebase)

**Comment by simison** [comment]
> In this branch?

Sorry, I didn't specify. At https://github.com/Automattic/wp-calypso/pull/41966

Actually! I might've ran `yarn --sync` first accidentally, instead of `yarn dev --sync`.

**Comment by scinos** [comment]
> Sorry, I didn't specify. At #41966

I get the same diff in `yarn.lock`.

Looks like that branch is not updated with `master`. It is using a `yarn.lock` that is "dirty" as well :(

if `--frozen-lockfile` is the only discussion point I'll be more than happy to undo those changes and just commit the new CI step to avoid the bleeding of uncommitted `yarn.lock` files.

**Review by lynnbgriffith — APPROVED** [review]
Yeah.  Let's just drop the `--frozen-lockfile` change from this PR so we can get the CI check in place.

**Pull request merged**
