### PR TITLE
Add e2e user for site editor on gutenberg edge.

### PR DESCRIPTION
**Pull request by Addison-Stavlo**
#### Changes proposed in this Pull Request

Adds `siteEditorSimpleSiteEdgeUser` to the e2e config file.

#### Testing instructions

Decrypt the file and verify `siteEditorSimpleSiteEdgeUser` is present in the `testAccounts` object.

Related to #

### CODE REVIEW

**Comment by worldomonation** [comment]
Not a blocker but rather a question as I'm unsure: what is this user used for?

**Comment by Addison-Stavlo** [comment]
> Not a blocker but rather a question as I'm unsure: what is this user used for?

👋  @worldomonation - It will be used for site editor wpcom specs (https://github.com/Automattic/wp-calypso/blob/trunk/test/e2e/specs/specs-wpcom/wp-site-editor-spec.js & https://github.com/Automattic/wp-calypso/blob/trunk/test/e2e/specs/specs-wpcom/wp-calypso-gutenberg-site-editor-tracking-spec.js).  Currently they are only running on a non-edge site, so adding this user will allow us to update the tests to accommodate the `gutenberg-edge` flag appropriately.

**Comment by worldomonation** [comment]
> > Not a blocker but rather a question as I'm unsure: what is this user used for?
> 
> 👋 @worldomonation - It will be used for site editor wpcom specs (https://github.com/Automattic/wp-calypso/blob/trunk/test/e2e/specs/specs-wpcom/wp-site-editor-spec.js & https://github.com/Automattic/wp-calypso/blob/trunk/test/e2e/specs/specs-wpcom/wp-calypso-gutenberg-site-editor-tracking-spec.js). Currently they are only running on a non-edge site, so adding this user will allow us to update the tests to accommodate the `gutenberg-edge` flag appropriately.

Thanks! I am not quite familiar (yet) with the whole WPCOM spec side of things and all the intricacies involved there, like `edge` and things.

**Review by worldomonation — APPROVED** [review]

**Comment by Addison-Stavlo** [comment]
>  I am not quite familiar (yet) with the whole WPCOM spec side of things and all the intricacies involved there, like edge and things.

Gotcha!  You may be familiar with the `gutenberg-edge` sticker that can be present on wpcom sites that flags the editor to be loaded with the 'next' version of Gutenberg that is in the process of being released.  Having some test sites on edge, as well as e2e tests, allow us to hopefully catch any bugs or regressions that upgrading to that Gutenberg version may introduce on dotcom so that we can address them before they are live to user sites.

The site editor on dotcom started as requiring the `gutenberg-edge` sticker, so initially the tests were only running on the edge version of the Gutenberg editor.  Now that we are preparing to move this into beta, we need to make sure beta users are on the stable Gutenberg version and that we are testing the new version of Gutenberg through its release cycle to help catch any issues before they go live to that beta.

**Comment by Addison-Stavlo** [comment]
Required playwright tests don't seem happy 🤔  trying to rerun but they seem to continuously fail on different things.  First Log In, now block widgets.

Edit - Annnd now they are passing. 😆  I just had to call them out publicly.

**Pull request merged**
