### PR TITLE
Updating and testing Premium plan bump offer

### PR DESCRIPTION
**Pull request by victorespigares**
#### Changes proposed in this Pull Request

* Testing the updated Premium bump offer for qualified Personal plan customers. More info here pNEWy-cIg-p2

#### Testing instructions

* Signup for an account and purchase a Personal plan.
* Put yourself in `control` group for `showPremiumPlanBump` test:
  * After completing payment, verify you're shown the Concierge/Quick Start upsell after purchase.
* Put yourself in `variantShowPlanBump` for `showPremiumPlanBump` test:
  * After completing payment, verify that you are shown the Premium plan bump offer.

Fixes 33-gh-engagement-team

### CODE REVIEW

**Review by niranjan-uma-shankar — APPROVED** [review]
LGTM 👍

**Comment by niranjan-uma-shankar** [comment]
Not related to this PR. I noticed a couple of things in the new checkout flow:

1. @fditrapani  When the Premium product is added to the cart from the upsell offer, the old checkout shows the original price struck out, but the new checkout doesn't - in case that's something you'd like to consider for the new design.

Screenshot 2020-04-01 at 6 51 38 PM

Screenshot 2020-04-01 at 6 48 24 PM


2. This might be a bug, so cc @sirbrillig too - even though I'm assigned to the new checkout variation of the `showCompositeCheckout` AB test, the checkout page shown after clicking the signup flow upsell offer is still the old one. So, in the signup flow, I added a plan -> I got the new checkout, then I clicked Yes on the upsell offer -> now I got the old checkout page.

Checkout page after upsell:

Screenshot 2020-04-01 at 6 56 51 PM

**Comment by sirbrillig** [comment]
> even though I'm assigned to the new checkout variation of the showCompositeCheckout AB test, the checkout page shown after clicking the signup flow upsell offer is still the old one. 

Thanks for the clear report! Do you know what the URL is that the upsell offer takes you to? If it's something like `/checkout/:site/concierge-session`, then this is expected behavior. It's not ideal but it is only temporary while we continue to roll out support for additional products. If I'm wrong about the URL, it might also be expected based on what the product slug is in the cart.

**Comment by fditrapani** [comment]
> When the Premium product is added to the cart from the upsell offer, the old checkout shows the original price struck out, but the new checkout doesn't - in case that's something you'd like to consider for the new design.

Thanks for the ping @niranjan-uma-shankar! Yes, we would definitely like to include it. I've added a card to our board to make sure we cover this as we expand our coverage.

**Comment by niranjan-uma-shankar** [comment]
> Do you know what the URL is that the upsell offer takes you to? If it's something like /checkout/:site/concierge-session, then this is expected behavior. 

Cool. That's right, the URL is /checkout/concierge-session/:site/

> Also, what does the upsell link look like?

It's of [this format](https://github.com/Automattic/wp-calypso/blob/f2c9d99b07e14ea938829e9b2e5b31b6fb388a90/client/my-sites/checkout/index.js#L125).

> Yes, we would definitely like to include it. I've added a card to our board to make sure we cover this as we expand our coverage.

👍

**Review by niranjan-uma-shankar — CHANGES_REQUESTED** [review]
We need to ensure that failed payments do not lead to users getting assigned to the test. I recommend that we follow the same implementation that was previously done for the plan bump test. We need a replica of the PR https://github.com/Automattic/wp-calypso/pull/38286/files.
Create a new function `maybeShowPlanBumpOffer()` - the contents of this function needs to be the same as in https://github.com/Automattic/wp-calypso/pull/38286, most importantly we need the `stepResult` check.

The test plan in https://github.com/Automattic/wp-calypso/pull/38286 should then pass for all cases.

**Comment by victorespigares** [comment]
Closing this PR for a cleaner one tbd.

**Pull request closed without merging**
