### PR TITLE
Add Studio to Developer Features page

### PR DESCRIPTION
**Pull request by matt-west**
Fixes https://github.com/Automattic/dotcom-forge/issues/6982

## Proposed Changes

* Add Studio to the Developer Features page `/me/developer`

image

## Testing Instructions

* Run Calypso
* Open <http://calypso.localhost:3000/me/developer>
* Observe that Studio is displayed at the top alongside GitHub Deployments
* Ensure the Learn more link goes to the [Studio landing page](https://developer.wordpress.com/studio/)

## Pre-merge Checklist

- [x] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Comment by wongasy** [comment]
@michaelpick It'd be great if you could kindly review the copy before we slap on the `String Freeze` label to get the copy translated!

>**Studio by WordPress.com**
>A fast, free way to develop locally with WordPress. Share your local sites with clients or colleagues and keep your local development process smooth and simple.

**Comment by michaelpick** [comment]
Sure, @wongasy! We'll take a look ASAP.

**Comment by michaelpick** [comment]
Actually, this looks familiar @wongasy, maybe something we looked at previously in a different request! Either way, I think it works well! Happy for this to ship 🚢!

**Comment by wongasy** [comment]
@michaelpick Thanks for taking a second look :) I'll slap on the `string freeze` label :)

**Review by wongasy — APPROVED** [review]
LGTM! 

Studio card rendered as expected:

| Desktop | Mobile |
| --------- | ------- |
|Screen Shot 2024-05-29 at 8 07 45 AM|Screen Shot 2024-05-29 at 8 07 53 AM|

The learn more link takes users to the Studio landing page and triggers the expected tracks event:

Screen Shot 2024-05-29 at 8 05 23 AM

**Pull request merged**
