### PR TITLE
Framework: Some preparatory changes for the React 15 upgrade

### PR DESCRIPTION
**Pull request by ockham**
These are solely test related changes branched from #5116 that we can apply already, to keep that PR leaner.

To test -- verify that this only affects test, and that CircleCI gives us a green light :-)

/cc @gwwar @aduth

### CODE REVIEW

**Comment by gwwar** [comment]
It looks like there's a failing i18n test

**Comment by ockham** [comment]
I keep `push --force`ing the fixed commit over and over but it doesn't show up here. Weird. :-/

**Comment by gwwar** [comment]
I think github might have degraded service atm

**Comment by ockham** [comment]
Okay, the commit's here now. CircleCI still isn't, tho.

**Comment by gwwar** [comment]
👍 🚢

**Pull request merged**
