### PR TITLE
ESLint: Bulk fix `@tanstack/query/prefer-query-object-syntax` rule violations

### PR DESCRIPTION
**Pull request by tyxla**
## Proposed Changes

This PR performs a bulk update to all React Query usages in Calypso to use the query object syntax. It's worth noting that the object syntax will also be the only available option in a future major version (see [docs](https://tanstack.com/query/v4/docs/react/eslint/prefer-query-object-syntax)).

Fixes most of the existing [`@tanstack/query/prefer-query-object-syntax`](https://tanstack.com/query/v4/docs/react/eslint/prefer-query-object-syntax) ESLint errors, which aren't enabled yet, but will be once we merge #77214. This PR is a pre-requisite of #77214. Our end goal is to enable the recommended ESLint rules for TanStack Query and make sure we're following the recommended best practices.

There are a few more violations to fix, but I'd like to keep this PR "smaller", and those other ones will require bigger refactors. Okay, I agree, the PR is not that small, but at least the changes are quite straightforward.

Would be great if I can get a quick review because the PR can get stale quickly as it touches many files.

## Testing Instructions

* Smoke test everything you can in Calypso.
* Verify all checks are green.

## Pre-merge Checklist

- [x] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [x] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [x] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [x] Have you checked for TypeScript, React or other console errors?
- [x] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [x] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [x] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

**Review by sirbrillig — COMMENTED** [review]
At a quick review, `useGeoLocationQuery` and all the checkout/payment methods stuff seems to be good. We'll probably find out quickly if not.

**Review by noahtallen — APPROVED** [review]
Tough one to review thoroughly, but I smoke tested a lot of sections of Calypso and all looks good. I also reviewed a random sampling of the files and everything is looking good there too.

**Review by ivan-ottinger — APPROVED** [review]
I have tested the parts related to Subscriptions Management portal we have been working on in @Automattic/apex and all seems to be working correctly. 👍🏼👍🏼

**Comment by tyxla** [comment]
Thank you all 🙌

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/8007700

Hi @tyxla, could you please edit the description of this PR and add a screenshot for our translators? Ideally it'd include this string: `Browse through all the patterns.`

Thank you in advance!

**Review by tyxla — COMMENTED** [review]
> This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/8007700
> 
> Hi @tyxla, could you please edit the description of this PR and add a screenshot for our translators? Ideally it'd include this string: `Browse through all the patterns.`
> 
> Thank you in advance!

This looks like a false alarm, this string was already there, so it is unexpected that it was considered new. Maybe something to take a look at when you get a chance, @Automattic/i18n?

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/8007700).

**Pull request merged**
