### PR TITLE
Cancellation form: Update styling

### PR DESCRIPTION
**Pull request by BogdanUngureanu**
Related to #https://github.com/Automattic/wp-calypso/issues/93601

This PR updates the cancellation forms and the Atomic downgrade notices

## Proposed Changes

* Update the design for the Cancellation form survey
* Update the design for the Atomic downgrade
* Update the colors of various button upsells

## Why are these changes being made?

* Makes the forms more consistent with the overall design branding

## Testing Instructions

* Use the calypso live link
* Go to Purchases > Plan
* Click on the cancel subscription
* Compare it with the provided [designs](https://github.com/Automattic/wp-calypso/issues/93601#issuecomment-2358095968)
* Make sure it's fine on mobile resolutions
* The error notices behind the inputs were not added because it would have required more effort
* The disabled button was kept as it is

## Screenshots
| Before    | After |
| -------- | ------- |
| Screenshot 2024-11-01 at 15 54 46   |   Screenshot 2024-11-01 at 16 02 48 |
| Screenshot 2024-11-01 at 16 05 03  |   Screenshot 2024-11-01 at 16 03 50 |
|   Screenshot 2024-11-01 at 16 06 33  |   Screenshot 2024-11-01 at 16 07 28 |
| Screenshot 2024-11-01 at 16 10 48 | Screenshot 2024-11-01 at 16 09 53 |
## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Comment by xavier-lc** [comment]
On the `Proceed with caution` screen, the checkbox doesn't look properly aligned with the text:

image
image

**Comment by xavier-lc** [comment]
On mobile, I think there should be some margin below the `Submit and cancel plan` button:

image

**Review by xavier-lc — APPROVED** [review]
LGTM!

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/17001355

Some locales (Hebrew, Japanese) have been temporarily machine-translated due to translator availability. All other translations are usually ready within a few days. Untranslated and machine-translated strings will be sent for translation next Monday and are expected to be completed by the following Friday.

Thank you @BogdanUngureanu for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/17001355).

**Pull request merged**
