### PR TITLE
Editor: add highlight to mark current draft in Drafts.

### PR DESCRIPTION
**Pull request by mtias**
Adds a visual mark (same as used in notifications panel) to mark the draft you are currently editing in the drafts drawer.

image

### CODE REVIEW

**Comment by artpi** [comment]
```
Warning: Failed propType: Invalid prop `selectedId` of type `boolean` supplied to `Drafts`, expected `number`. Check the render method of `DraftList`.
```

**Comment by artpi** [comment]
After reload, I am unable to reproduce the error above...
Maybe someone else has the same issue?

Design is good, everything works.

:ship:

**Comment by nylen** [comment]
Fixed the `propTypes` warnings in 7a9e901.  `selectedId={ this.props.post.ID }` was passing `undefined` when editing a new post or page.  For whatever reason, React was treating this as a boolean.  Using `null` instead works fine.

Nice change, I think it is good to go now.

**Comment by mtias** [comment]
Thanks @nylen! I'm traveling today, so anyone, feel free to merge.

**Comment by artpi** [comment]
Merged!

**Pull request merged**
