### PR TITLE
Reader: Show longer excerpts for recs without images

### PR DESCRIPTION
**Pull request by jancavan**
This fixes: https://github.com/Automattic/wp-calypso/issues/13388

Updated recs in:
- Search
- Full-post
- Following stream

## Search
**Before:**
screenshot 2017-04-26 11 40 48

**After:**
screenshot 2017-04-26 11 40 04

## Full-post:
**Before:**
screenshot 2017-04-26 11 44 23

**After:**
screenshot 2017-04-26 11 44 34

**Before:**
screenshot 2017-04-26 12 12 45

**After:**
screenshot 2017-04-26 11 55 45

## Following stream:
**Before:**
screenshot 2017-04-26 11 58 36

**After:**
screenshot 2017-04-26 12 38 49

### CODE REVIEW

**Comment by fraying** [comment]
@jancavan Big improvement! Thank you! But, could you adjust the spacing so that the last line always ends in the same place? This should be doable if the headline and the body text have the same line-height (#13042). You may have to play with the height of the image and/or the magins, but it should be doable.

**Comment by jancavan** [comment]
@fraying yup, I'll look into that but will do it in a separate PR.

**Comment by samouri** [comment]
css looks reasonable.  always sad to see when numbers seem so random 🤷‍♂️

**Comment by samouri** [comment]
Visually LGTM 🚢

**Pull request merged**
