### PR TITLE
update launchpad styling

### PR DESCRIPTION
**Pull request by agrullon95**
#### Proposed Changes

* Minor changes to launchpad styling (specifically email banner, sidebar spacing/text changes). While testing "domain/plans in stepper framework" changes I noticed CSS styling that did not look consistent on mobile devices and decided to make minor changes.

Changes made to styling:  

**Email validation banner:** 

>  Mobile-specific changes:
> -  Decreased font size.
> -  Removed green checkmark icon.
> -  Close button (x icon) now moved to top of div.
> 
>  Desktop-specific changes:
> -   Decreased font size 

**Sidebar component:**

> - Overall width of component decreased.
> - Margin decreased between header (WordPress icon and flow name) and the progress bar for desktop and mobile.  
> - Decreased sidebar description font size and updated font color.
> -   Decreased sidebar URL font size and adjusted letter spacing  
> - Decreased sidebar checklist item font size
> 
>  Desktop-specific changes:
> -  Decreased sidebar component left margin
> 
> Mobile specific changes:
> -  Increased font size for mobile “title” text

#### Testing Instructions

* Checkout branch (or use calypso.live link)
* Compare to Launchpad on calpyos.live or localhost to Launchpad on Wordpress.com (You can also compare against figma design: 9wpoYJrMlYKAKUYvVBMN74-fi-1364%3A18855&t=Q1xJK4dLI6EGh4YH-0)

Link-in-bio: `/setup/link-in-bio/launchpad?siteSlug={SITE_SLUG}`
Newsletter: `/setup/newsletter/launchpad?siteSlug={SITE_SLUG}`

Before:
Screen Shot 2022-11-17 at 1 32 27 PM

image

After:
Screen Shot 2022-11-17 at 1 30 06 PM

image

#### Pre-merge Checklist

- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

Related to #

### CODE REVIEW

**Comment by Addison-Stavlo** [comment]
In the description I see before and after for mobile. The changes look like they will effect desktop view as well, could we have before/after for desktop as well for quick reference here? (I added @nuriapenya as a reviewer for thoughts as well)

So far the new style looks good to me!

**Comment by jeyip** [comment]
> Minor changes to launchpad styling (specifically email banner, sidebar spacing/text changes). 

Would you mind adding a list of what changed that we should be testing?

## Testing
### Requirements
- [x] Tasks continue to redirect properly
- [x] Go to admin button is visible on initial load of viewport and behaves as expected
- [x] Pill buttons are visible, appear to be correctly sized, and work as expected 
- [x] Copy to clipboard button appears on hover and continues to work as expected
- [x] Email validation banner links continue to work as expected and appears to be formatted correctly 

### Browsers
- [x] Edge
- [x] Firefox
- [x] Chrome 
- [x] Chrome Mobile 

> The changes look like they will effect desktop view as well, could we have before/after for desktop as well for quick reference here? (I added @nuriapenya as a reviewer for thoughts as well)

Agreed!

**Comment by jeyip** [comment]
For those curious, you can reproduce the email notification by following these instructions

- Create a new WordPress account. (You can use [Temp Email](https://temp-mail.org/en/))
- Create a new Launchpad site with the newsletter flow
- Go to http://calypso.localhost:3000/setup/newsletter/launchpad?siteSlug=YOUR_SITE_SLUG
- You should see the banner displayed on the top of the page

**Comment by edanzer** [comment]
Tested this and looks good to me. I do think the mobile styling is nicer with the changes. These changes do also affect desktop styling. I raised that separately in a slack thread (p1668717151421709-slack-CHN6J22MP). The desktop differences are very minor and not noticeable better/worse. But I wanted to confirm that we are intending to adjust the desktop styles here, vs just adjust mobile?

**Comment by sharpirate** [comment]
✔️ Tested and this looks great on mobile but I'll hold off on approving due to the pending discussion of how the changes are affecting desktop styling

**Comment by agrullon95** [comment]
I updated the PR description with a list of changes. Some CSS changes are mobile-related and some are desktop related. The mobile changes look good from everyone's responses so far, but I may have to remove the desktop changes for now depending on @nuriapenya response.

**Comment by nuriapenya** [comment]
I just tested, and everything looks good to me! The changes on the Desktop are fully aligned with the design 👌🏽 so everything is good from my side.

The only odd thing I noticed is the header logo is not the same (almost not perceivable though).

This is what I see on your PR:
Screenshot 2022-11-30 at 15 40 30

```
.launchpad__sidebar-header-flow-name {
    font-family: Recoleta,"Noto Serif",Georgia,Times New Roman,Times,serif;
    font-size: 1.125rem;
    font-style: normal;
    font-weight: 400;
    line-height: 1.3;
    margin: 0 0 100px 12px;
```

And this is what I see in the stepper flow live:
Screenshot 2022-11-30 at 15 42 21

```
.signup-header h1 {
    color: var(--color-text);
    font-family: Recoleta,"Noto Serif",Georgia,Times New Roman,Times,serif;
    font-size: 1.125rem;
    font-weight: 400;
    left: 56px;
    letter-spacing: -.4px;
    position: absolute;
    top: 20px;
```

**Comment by agrullon95** [comment]
@nuriapenya I updated the header/logo styling. Let me know if it matches the header in the other stepper flow pages better.

**Comment by edanzer** [comment]
Just re-tested this following recent changes, and on the assumption that we'll keep the updated desktop styling in place. Also test both with existing account, and with new email/account to check the email verification banner. Everything looks good!

Only exception is some e2e tests appear to be failing, which I assume will be resolved prior to merge.

**Review by edanzer — APPROVED** [review]

**Pull request merged**
