### PR TITLE
Theme Showcase: Enable flag themes/showcase-i4/cards-only for all environments

### PR DESCRIPTION
**Pull request by taipeicoder**
#### Proposed Changes

This PR enables the flag `themes/showcase-i4/cards-only` for all environments.

#### Testing Instructions

Ensure that all environment configs that contains the flag `themes/showcase-i4/cards-only` are set to true.

#### Pre-merge Checklist

- [x] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [x] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [x] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [x] Have you checked for TypeScript, React or other console errors?
- [x] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [x] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [x] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

**Comment by arthur791004** [comment]
Looks like e2e tests are broken after we enable the feature flag

**Comment by taipeicoder** [comment]
> Looks like e2e tests are broken after we enable the feature flag

After some investigation, I found out that the following [line](https://github.com/Automattic/wp-calypso/blob/trunk/packages/calypso-e2e/src/lib/pages/themes-page.ts#L64) in this [test](https://github.com/Automattic/wp-calypso/blob/trunk/test/e2e/specs/appearance/theme__details-preview-activate.ts#L58) wasn't working as expected:
```
await this.page.waitForSelector( selectors.placeholder, { state: 'hidden' } );
```

This caused the next [test](https://github.com/Automattic/wp-calypso/blob/trunk/test/e2e/specs/appearance/theme__details-preview-activate.ts#L62) to run without the search results being rendered, thus failing the test.

I changed the state from `hidden` to `detached` and the line now behaves as expected. As per Playwright's [documentation](https://playwright.dev/docs/api/class-page/#page-wait-for-selector), `hidden` should both pick up when the elements are "hidden" or have been detached from the DOM.

My theory is this: The failing E2E test are on mobile. And in the mobile view, some of the theme card placeholders are outside the viewport. And thus the line `await this.page.waitForSelector( selectors.placeholder, { state: 'hidden' } );` is returned since some of the elements are OOB, and therefore, considered to be "hidden". cc: @worldomonation

**Comment by autumnfjeld** [comment]
Nice sluething on the tests.  I was wondering why I could do the failing tests manually just fine (on desktop).

**Review by arthur791004 — APPROVED** [review]
Nice finding 👍

**Comment by autumnfjeld** [comment]
Woot Woot.   Thank you!!!  Got it in the sprint summary! pbxlJb-3mt-p2#comment-2292  😃

**Pull request merged**
