### PR TITLE
Reader full post: reformat Daily Post and Discover pullquotes for new full post view

### LINKED ISSUE #7630: Reader: pullquotes overlap author compact profile in new full post view
#### Steps to reproduce
1. Starting at URL: http://calypso.localhost:3000/read/feeds/27030/posts/1117210232

#### Screenshot / Video

screen shot 2016-08-24 at 10 00 59

I suspect this is a regression caused by #7549.

### PR DESCRIPTION
**Pull request by bluefuton**
In the current full post view, we show pullquotes in the left column on large screens (>1132px) but now we have the author profile in the left column, they sometimes overlap (see #7630).

This PR changes all Daily Post pullquotes to appear in the main body text at all screen sizes, like so:

screen shot 2016-08-29 at 15 59 21

Fixes #7630.

Test live: https://calypso.live/?branch=fix/reader/show-pullquotes-in-article

### CODE REVIEW

**Comment by fraying** [comment]
@bluefuton Is it possible to preserve the right side pullquotes at the larger breakpoints?

**Comment by fraying** [comment]
Also note: This should apply to Discover posts, too.

**Comment by bluefuton** [comment]
> Is it possible to preserve the right side pullquotes at the larger breakpoints?

Certainly is. On my monster screen it looks reasonable above 1400px width, so I've tweaked accordingly:

screen shot 2016-08-30 at 15 40 56

**Comment by bluefuton** [comment]
> Also note: This should apply to Discover posts, too.

Yep! It will do:

http://calypso.localhost:3000/read/blogs/489937/posts/244358

**Comment by fraying** [comment]
Nice work! Thank you.

**Pull request merged**
