### PR TITLE
Wires up highlighting of products

### PR DESCRIPTION
**Pull request by ChaosExAnima**
#### Changes proposed in this Pull Request

* Declares items to be highlighted and wires up the badge and ProductCard props.

#### Screenshots
Screen Shot 2020-08-17 at 3 59 59 PM

#### Testing instructions

* Enable A/B test for offer reset.
* Visit plans page on a site without Jetpack Security.
* Verify Jetpack Security matches screenshot above.
* Verify treatment does not appear after clicking on product.

**Notes**
- The way this is wired allows for a future hook to get what products have this treatment from state.
- Currently purchasing is not wired up so it's not possible to test.

Fixes 1169247016322522-as-1188453012691999.

### CODE REVIEW

**Comment by monsieur-z** [comment]
@ChaosExAnima, the only thing missing is that the highlighted card features should be expanded by default (on desktop only).

**Comment by ChaosExAnima** [comment]
@monsieur-z - Saw that. I'm confused how to modify props based on screen size, though. Can we use a CSS solution here?

**Comment by ChaosExAnima** [comment]
Hey @monsieur-z! I've pushed a fix (2ae56f012f0f24949af55553d81eb74a3173f6a0) for the expanded prop for non-mobile views, and verified the props change when the viewport changes. Can you look and verify before I merge?

**Comment by monsieur-z** [comment]
> Hey @monsieur-z! I've pushed a fix ([2ae56f0](https://github.com/Automattic/wp-calypso/commit/2ae56f012f0f24949af55553d81eb74a3173f6a0)) for the expanded prop for non-mobile views, and verified the props change when the viewport changes. Can you look and verify before I merge?

Code looks good and UI tests well, @ChaosExAnima!

**Pull request merged**
