### PR TITLE
FSE: ensure that page templates stay valid on wpcom

### LINKED ISSUE #34784: Full Site Editing: template warning on Dotcom sites
When editing the page with FSE enabled I'm seeing the following notice on Dotcom:

Screenshot 2019-07-19 at 16 32 51

This should be removed in FSE context. It seems to be coming from core's `template-validation-notice`. Not sure why it's not showing up on self hosted sites though.

Confirmed while testing D30622-code, it can be reproduced by following the steps outlined there.

### PR DESCRIPTION
**Pull request by noahtallen**
Previously, we had a hack which helped us maintain template validity in the editor. Matt and I are guessing that this worked fine for local development, but that on the sandbox, things move slowly enough that this function is called at a time when the change doesn't stick, or something isn't available.

**This is what the bug looked like. It should no longer appear.**
Screenshot 2019-07-19 at 16 32 51

### Changes proposed in this Pull Request
* Instead of maintaining validity via `domReady`, use a wp.data subscriber to maintain validity once everything is online.

_You can skip setup if you already have the sync stuff working_
### FSE Sandbox Setup:
1) You'll need to test this on your sandbox, so you'll want to make sure you have this setup ready to go: PCYsg-ly5-p2 (developing-against-wp-com-sandbox) I added a force option to my unison config which makes my own machine the source of truth and disregards any changes on the remote. This makes sure that the sandbox plugin stuff === what's in this PR.
2) You'll also need to make sure that you add the fse sticker (PCYsg-ly5-p2 activating-the-plugin-on-wordpress-com) to your sandbox site so that it activates the changes properly,

### Testing
_Make sure you can sync this PR to your sandbox before continuing ^^_
1) Create a new page in wp admin. You should be able to see FSE header/footer. Save it.
2) Now, go out of the page back to wp admin. Then, go back into the page. Previously, the error above would have appeared at the top. If you do not see the error, then this PR is working!
3) Also try editing an existing page on your sandbox from calypso. The error should not show there either.

Now, when I go back into the page editor for these existing page, it is not loading the FSE editor. (i.e. the post content is not inside a post content block and the header/footer don't show up). I believe that is unrelated and possibly just an issue with my setup.

Fixes #34784

### CODE REVIEW

**Comment by mmtr** [comment]
I actually believe the invalid template warning is being displayed for valid reasons and we should fix that instead :)

https://github.com/Automattic/wp-calypso/issues/34784#issuecomment-513402010

**Comment by gwwar** [comment]
Gotcha, @mmtr seems simple enough to update content in https://github.com/Automattic/themes/blob/904bffbea60a929cb9c027446e0b21fe1ce6af32/modern-business/inc/fse-template-data.php#L131-L135 and remove the align attributes. 

Who'd like to spin up the alternative? @noahtallen or @mmtr ?

**Comment by noahtallen** [comment]
I could definitely try that. @mmtr would we be able to ditch the entire function at that point, then?

**Comment by mmtr** [comment]
> I could definitely try that. @mmtr would we be able to ditch the entire function at that point, then?

I don't think we can because of this: https://github.com/Automattic/wp-calypso/pull/34425#issuecomment-507908128

**Comment by noahtallen** [comment]
Yep, that makes sense. So we'll still need to force validity to true with this new approach, and also add a fix for the template block alignment.

**Comment by mmtr** [comment]
> Yep, that makes sense. So we'll still need to force validity to true with this new approach, and also add a fix for the template block alignment.

I think we don't need to change the `resetTemplateValidity` function. I'm expecting the warning to don't show up after removing the attributes from the FSE template.

**Comment by noahtallen** [comment]
Isn't the existing code supposed to prevent the warning from showing up? i.e. wouldn't the existing code have suppressed any validity issue that cropped up?

I'll definitely test that, though

**Comment by mmtr** [comment]
> Isn't the existing code supposed to prevent the warning from showing up? i.e. wouldn't the existing code have suppressed any validity issue that cropped up?

Good question! But I'm not not familiar enough with the template validity checks to answer that 😅 My hypothesis is just based on some manual testing. Since the override is not permanent (I think Gutenberg could display the warning again if it detects a change not matching the template), maybe there is something triggering a check that causes the warning to show up again.

**Comment by noahtallen** [comment]
I did a quick test, and with the suppression code commented out and with the theme in an invalid state (local install), the error _does_ show up. But if I have the previous copy of the suppression code running, the error does not show up even if I start editing the page.

**Comment by mmtr** [comment]
We finally need this, since #34797 is making the warning to show up again. I think it was not being displayed in our tests before because https://github.com/Automattic/themes/pull/1103 was not merging the post content in the template, keeping the template unaltered and therefore valid.

**Pull request merged**
