### PR TITLE
Fixes an error with redux in the Blaze Dashboard app

### PR DESCRIPTION
**Pull request by sbarbosa**
## Proposed Changes

This PR fixes a redux-related error with the Blaze Dashboard app that is thrown when it starts.

Screenshot 2023-06-01 at 14 35 21

The problem was because of outdated libraries on the package.json

## Testing Instructions
1. Check out this branch locally
2. Check out this Jetpack branch: https://github.com/Automattic/jetpack/pull/30103
3. In the console, go to `apps/blaze-dashboard` and execute: 
```
yarn install
BLAZE_DASHBOARD_PACKAGE_PATH=/path/to/jetpack/projects/packages/blaze yarn dev
```
**Note:** Change the jetpack path to the correct folder installation.

4. Build the Jetpack Blaze package: `pnpm jetpack build packages/blaze`
5. Open your Jurrasic Tube tunnel and then in the browser go to the wp-admin page for your local site
**Note:** You need to enable this filter `jetpack_blaze_dashboard_enable` inside your local Wordpress installation.
You can ping me if you don't know how to do that.

6. Click on Tools->Advertising
7. Verify that the Dashboard is displayed correctly.

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

**Review by jeherve — APPROVED** [review]
This tests well for me. 👍

**Review by timur987 — APPROVED** [review]
Thanks, @sbarbosa!

The changes LGTM and the dashboard works fine.

The couple of thing I found are

1. I still have warnings (I've build an app and created a package for blaze in Jetpack), partially errors were gone, but there're still a warning: 
```Warning: ReactDOM.render is no longer supported in React 18. Use createRoot instead. Until you switch to the new API, your app will behave as if it's running React 17. Learn more: https://reactjs.org/link/switch-to-createroot```
image

2. (not relevant to this PR directly but still important in terms of project to share) Searching by title ignores the title I used as a search term 🤷 

https://github.com/Automattic/wp-calypso/assets/115007291/8261eeea-2e3a-487b-9d0f-daa21928c578

Other than that, I do not see any blockers to merge this PR.

**Comment by sbarbosa** [comment]
Thanks @timur987! 

1. I checked and we are still using React 17 in Calypso and the app. I will see if we can start using the new way to remove this warning, but I think that is inside one of the script utilities that our app uses. So it will be difficult to do that change.

2. You are right, I will need to see the REST controller on the Jetpack branch to see what the request parameters aren't being spread to the DSP call. Thanks for noticing this!

**Comment by noahtallen** [comment]
Working towards React 18 across the repo here: #77046

**Pull request merged**
