### PR TITLE
Modularise lib/domains/utils

### PR DESCRIPTION
**Pull request by sgomes**
#39313 reintroduced `moment` as a dependency for all of Calypso, after previous work making sure it wasn't needed in `/log-in`. The issue is that it was added as an import on a widely used utils file (when only one of the methods there needed it). Tree-shaking cannot remove the import in this situation, and it ends up being bundled everywhere.

To avoid situations like this, it's best to have a directory of individual utilities, rather than a single utilities file with all of them. To avoid long import paths, an index file can then be created to re-export these utilities, with a `package.json` file that indicates there are no side effects, to guarantee that webpack tree-shakes effectively.

This PR handles the modularization described above, and removes some trivial usage of `lodash`. For good measure, it also reimplements the offending method without using `moment`, with just standard JS date processing.

#### Changes proposed in this Pull Request

* Modularize `lib/domains/utils`.
* Remove some trivial usage of `lodash`.
* Reimplement `isRecentlyRegistered` without `moment`.

#### Testing instructions

Ensure that the various methods in `lib/domains/utils` continue to work correctly.

### CODE REVIEW

**Comment by sgomes** [comment]
Reimplemented `isRecentlyRegistered` without using `moment`.

**Comment by sgomes** [comment]
> This PR does not affect the size of JS and CSS bundles shipped to the user's browser.
> 
> Generated by performance advisor bot at [iscalypsofastyet.com](http://iscalypsofastyet.com).

This is most likely incorrect, and another instance of ICFY producing incorrect results.

**Review by tyxla — APPROVED** [review]
Code is looking good 👍 

It would be nice to get a ✅ from the pinged folks, just in case we're missing a use case of `registrationDate` that `Date` can't parse for some reason.

**Review by hambai — COMMENTED** [review]
There is one issue though - the date comparison should happen in UTC since the timestamp we return from the API is in UTC and I think `new Date()` returns the timestamp in the client local timezone?

**Comment by sgomes** [comment]
> There is one issue though - the date comparison should happen in UTC since the timestamp we return from the API is in UTC and I think `new Date()` returns the timestamp in the client local timezone?

Dates are hard in JS 🙂 Whether it's interpreted as a local time or a UTC time depends on the format of the string provided.

I assumed these dates would be ISO 8601 strings, since that's what's used elsewhere in the API. Is that not the case, @hambai? ISO 8601 strings are always interpreted as a UTC time by `new Date()` when the timezone isn't provided.

**Comment by sgomes** [comment]
All of this makes me thing we should just be returning Unix timestamps rather than date strings from the API 😞 Those are completely unambiguous.

**Comment by sgomes** [comment]
To avoid confusion and accelerate the deployment of this important fix, I'll go back to using `moment` in `isRecentlyRegistered`.

**Comment by sgomes** [comment]
The fix is deployed, and a 17KB (compressed) reduction in login JS confirmed.

**Comment by hambai** [comment]
Yes, you're right - we return the date in ISO8601 but there is actually a bug in there that returns a date in the wrong timezone :( We should be able to fix that on the backend and then I can also fix the utility function so it won't really need the `moment` lib.

**Pull request merged**
