### PR TITLE
Domains: Move all lib/domains tests to local single test runner

### PR DESCRIPTION
**Pull request by gziolo**
This is similar to #3773. It does exactly the same steps to speed up test execution.

This pull request seeks to eliminate subtree-specific `Makefile`s in the `client/lib/domains` directory, used always for testing, with a single test runner for the entirety of the `client/lib/domains` directory.

The changes eliminated 4 `Makefiles`.

Benefits include:

- Improved performance by decreasing number of Mocha/Babel reinitializations
- Fewer files to maintain

__Testing instructions:__

Ensure tests pass by running `make test` from the project root directory.

### CODE REVIEW

**Comment by gwwar** [comment]
:+1: Maybe add a quick usage note in the client/lib/domains/README.md and :shipit:

**Comment by blowery** [comment]
Maybe we move this to `lib` and let things start opting in there instead? too big?

**Comment by blowery** [comment]
Nah, ship it. Can address later.

**Comment by gziolo** [comment]
@gwwar: Usage note added with https://github.com/Automattic/wp-calypso/commit/7881dee8651b04a3168715a31aabcd43e7e18e1a

@blowery: I'm still not sure how to tackle it at a global level. Definitely it's going to be easier to split all work needed if we start grouping tests in subfolder that aren't on the very top level. We can always move that level up :)

Thanks for review!

**Pull request merged**
