### PR TITLE
Adds an error notice for Jetpack Backup when the automated transfer fails

### PR DESCRIPTION
**Pull request by ChaosExAnima**
#### Changes proposed in this Pull Request

* Adds an error for when the automated transfer process fails.

#### Testing instructions

* Create a site with a Business plan.
* Generate an issue, typically by a reverted transfer. See the ticket for details.
* Go to Jetpack > Backup with the feature section enabled.
* Verify that the activate button is active.
* Click the button.
* Verify an error appears as below.

#### Screenshots
Screen Shot 2020-06-19 at 4 24 20 PM

Fixes 1179060693083348-as-1181203155439417

### CODE REVIEW

**Comment by nsakaimbo** [comment]
@ChaosExAnima Just taking a minute to see why `ci/wp-desktop` is failing. Will circle back in a bit.

**Comment by nsakaimbo** [comment]
Has this branch been rebased on latest Calypso master?

Screen Shot 2020-06-22 at 12 12 32 PM

`No such file or directory ... assets-fallback.json`

I'm not sure if anything in this set of changes would cause this, though. @jsnajdr Any idea?

**Comment by ChaosExAnima** [comment]
@nsakaimbo I merged master above, that's the one that caused all these failures.

**Comment by nsakaimbo** [comment]
> I merged master above, that's the one that caused all these failures.

ah, interesting. I'm building a fresh copy of calypso master in CI right now - this will help confirm/isolate where the issue is coming from.

**Comment by nsakaimbo** [comment]
_Update_: so I can confirm that latest Calypso master (d8ce0b5) desktop e2e is building and passing just fine in Automattic/wp-desktop/pull/907. Also, there are other Calypso PRs open concurrent to this one where e2e is also passing (e.g. #43488 and #43527, so the successive `ci/wp-desktop` failures seem really strange (it looks like at least 4 successive failures, which is especially odd if this was temporal).

@ChaosExAnima It's not obvious to me what, if anything, in this PR might be causing this (on the surface the changes seem harmless). Can we please hold off on merging until someone from @Automattic/team-calypso has a chance to take a look?

**Comment by ChaosExAnima** [comment]
> Can we please hold off on merging until someone from @Automattic/team-calypso has a chance to take a look?

Sure @nsakaimbo, this is part of a higher priority project but also a small edge case. Happy to let it sit for a bit, but let's get this looked at today? :)

**Comment by ChaosExAnima** [comment]
@nsakaimbo, looks like it passed now. Good to go?

**Comment by nsakaimbo** [comment]
@ChaosExAnima Even stranger, the test suite looks like it passed on it's 6th attempt. You should be good to go ahead and land this - thanks for your patience. 

However, I'm still nervous about the specific error observed in this branch and there might be some sort of race condition in the build system that caused this? We'll need to continue to monitor/investigate as a separate issue.

_TL;DR_:
 
-`ci/wp-desktop` has failed ~5 times successively in this branch, passed on the 6th
- `ci/wp-desktop` is passing in latest Calypso master, as well as other concurrent PRs
- Latest Calypso master is also passing (see Automattic/wp-desktop#907)
- I also created a test branch in the `wp-desktop` repo using this PR branch/SHA, and it both Linux and Mac jobs passed successfully ([link](https://github.com/Automattic/wp-desktop/tree/test-jetpack-backup-branch))

**Comment by nsakaimbo** [comment]
I see what happened. There is some sort of race condition that causes a corrupted desktop source to be built ([link](https://app.circleci.com/pipelines/github/Automattic/wp-desktop/16978/workflows/173a1cb8-f16b-4935-82ef-59e7d501ed80/jobs/65459)).

Even though the `build source` step was marked as successful, it in fact failed in the `check-npm-client` step with the error:

```
$ check-npm-client && node ${NODE_ARGS:---max_old_space_size=8192} ./node_modules/webpack/bin/webpack.js --config client/webpack.config.js --display errors-only && yarn run build-languages-if-enabled
 
events.js:292
      throw er; // Unhandled 'error' event
      ^
Error: write EPIPE
 
    at ChildProcess.target._send (internal/child_process.js:806:20)
 ```

Not sure if this a `max_old_space_size` issue (i.e. we're bumping into RAM constraints again). Now that the desktop app is using a code-split Calypso, I would imagine this concern is largely alleviated? If it's a RAM resource issue, then it's some other race condition in the build system.

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/3913245

Thank you @ChaosExAnima for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/3913245).

**Pull request merged**
