### PR TITLE
Re-encrypt config file and add to TeamCity

### PR DESCRIPTION
**Pull request by noahtallen**
Here's what I did:
1. decrypted existing config file
2. generated a new 40 char password
3. used that to re-encrypt the config
4. added config key as a param to teamcity under `E2E_CONFIG_ENCRYPTION_KEY_JAN_18_22`, and then deleted the param. (So that the settings don't conflict with vcs)
5. copied the credentialsJSON thing for the key
6. Added the param to the `settings.kts` file

In theory, if e2e works with the key, this will be the new way to change keys without invalidating existing config files.

I also updated PCYsg-vnR-p2 with more detailed steps and screenshots.

### CODE REVIEW

**Comment by noahtallen** [comment]
Looks like it works!

**Comment by worldomonation** [comment]
Okay, so just go make sure I understand this correct!

1. the param name `E2E_CONFIG_ENCRYPTION_KEY` will stay consistent for the foreseeable future.
2. the value for `E2E_CONFIG_ENCRYPTION_KEY` can be swapped out by defining a new param name/value in place of `E2E_CONFIG_ENCRYPTION_KEY_JANUARY_22`.
3. it is intended for the above steps to be done through TeamCity UI.

Is my understanding correct? 

Edit: just saw reference to PCYsg-vnR-p2. Took a look at the revised page (thanks!) and it makes sense.

**Review by worldomonation — APPROVED** [review]
If it seems to work, let's try it.

**Comment by noahtallen** [comment]
1. Yes, this should always contain the key used for the build!
2. Correct, we can just swap out the value there, instead of in several files across the codebase. But one caveat is that the _existing_ key can stay in the config. You just make a new key, and then update E2E_CONFIG_ENCRYPTION_KEY to use that instead
3. Not exactly. You need to "upload" the password to teamcity by creating a param, but you need to delete the param and then make the change to the text file using the credentials JSON format you got from uploading it. So the only effect your UI change has is creating a reference to the password in the system, but it doesn't actually modify the config. then, PRs like this can update the config

**Comment by worldomonation** [comment]
@noahtallen Thanks for clarifying. 

It sounds like for my PR https://github.com/Automattic/wp-calypso/pull/59465/ that [this line](https://github.com/Automattic/wp-calypso/pull/59465/files#diff-21427bef2c0507f727b31746b85741443fd36a52cdf406d2cfb1180e3892c197R116) can stay in the current form? 

The PR was rebased on top of the recent changes, then I switched over from `CONFIG_E2E_ENCRYPTION_KEY` to `E2E_CONFIG_ENCRYPTION_KEY` in [this commit](https://github.com/Automattic/wp-calypso/pull/59465/commits/cdf1d880537b84b022b80005155897e59547daad).


Does this look right?

**Comment by noahtallen** [comment]
Yep, that should be able to stay the same from now on

**Pull request merged**
