### PR TITLE
Untangling: show site admin color when in Hosting menus

### PR DESCRIPTION
**Pull request by fushar**
Related to:

- https://github.com/Automattic/dotcom-forge/issues/6354

## Proposed Changes

This PR will show the site's admin color when we're in one of the Hosting menus. It uses the new endpoint introduced in https://github.com/Automattic/jetpack/pull/36749.

## Testing Instructions

It is important to follow everything EXACTLY.

1. Prepare an early classic Atomic site.
2. Use Jetpack Beta tester to patch https://github.com/Automattic/jetpack/pull/36749.
3. Sandbox public-api.
4. Go to your sandbox.
5. Patch D144492-code to your sandbox (`arc patch D144492`).
6. Patch https://github.com/Automattic/jetpack/pull/36749 to your sandbox (`bin/jetpack-downloader test jetpack untangling/nav-reunification-color`). If asked to checkout to trunk, type `n` to keep in the current branch. When asked to keep the current branch, type `Y`.
8. Go to your site's `/wp-admin/profile.php`.
9. Change the admin color to a color other than the one you set in `/me/account`.
10. Go to `<calypso live URL>/home/<site slug>`.
11. Verify that the color is the same as the color you set in step 8.
12. Now test with an early classic Simple site. You just need to sandbox your site (`<site>.wordpress.com`). You don't need to modify anything in your sandbox again.
13. Verify that this change does not break other sites (not early classic).

## Pre-merge Checklist

- [x] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [x] https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md for your changes?
- [x] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [x] Have you checked for TypeScript, React or other console errors?
- [x] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [x] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [x] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Review by lupus2k — APPROVED** [review]
Great instructions, everything works great :tada:

**Comment by fushar** [comment]
Feel free to merge this if we're confident. I think this PR can be merged even without the corresponding wpcom and Jetpack diffs. It will just 404 and fall back to the Calypso color scheme (as per existing behavior).

**Comment by allilevine** [comment]
@lupus2k Can you own merging this one? Is there anything we need to do first?

**Comment by lupus2k** [comment]
> @lupus2k Can you own merging this one? Is there anything we need to do first?

Sure, I'll merge it in the next hour

**Pull request merged**
