### PR TITLE
Jetpack connect: Separate from signup module

### PR DESCRIPTION
**Pull request by sirreal**
This PR moves `jetpack-connect` out of the signup module and into its own module (finally 🎉 ).

The changes are actually pretty small and straightforward after all the prepwork tracked in #12991.

To test:
* Use this branch
* Use Jetpack connect! Relevant entry points include:
  * `calypso.localhost:3000/jetpack/connect`
  * `calypso.localhost:3000/jetpack/connect/?url=:site`
  * `calypso.localhost:3000/jetpack/connect/store`
  * `calypso.localhost:3000/jetpack/connect/personal`
  * `calypso.localhost:3000/jetpack/connect/premium`
  * `calypso.localhost:3000/jetpack/connect/professional`
  * See [this file](https://github.com/Automattic/wp-calypso/blob/00e998ec01144bcc4ba1596c121f81d7f48c94a1/client/jetpack-connect/index.js) for a more complete list.
* Please pay special attention to the module level changes and raise _any_ questions as I'm not very familiar with that part of the codebase.

Fixes #14321, Supersedes #12991

### CODE REVIEW

**Comment by sirreal** [comment]
Parts of this module rely in `signup/step-header`. It should be moved out of signup and into `blocks`, beginning with #14337

**Comment by sirreal** [comment]
I don't want to lose anything relevant from #12991, but I think this is the only still-relevant conversation about the changes there:

> what jumps out immediately is that this jetpack-connect should be in blocks folder, rather than a top-level client folder. @mtias what do you think?<sup>[1]</sup>

@roccotripaldi Does this comment still stand?

[1]: https://github.com/Automattic/wp-calypso/pull/12991#issuecomment-295502829

**Comment by seear** [comment]
Aside: I'm not greatly familiar with the Jetpack connection flow, but it seems that some of these routes can certainly benefit from SSR if/when we come to look at performance.

**Comment by sirreal** [comment]
@seear Awesome, that was my thinking. I think it would be interesting to look at that after we get this module moved. 👍

**Comment by seear** [comment]
```
                                            signup.82259c515f9e618416ed.js     881 kB                               \
                        4779011046812658, 4324925900180340  [emitted]  signup
```

**Comment by roccotripaldi** [comment]
> what jumps out immediately is that this jetpack-connect should be in blocks folder, rather than a top-level client folder.

After some consideration, this does make sense as a top-level client folder.

**Comment by sirreal** [comment]
> Does this mean jetpack connect routes will have their own bundle?

That's what it should mean. Here's what I'm seeing with `make run`:

```
         signup.90f7c276585fa5b56160.js 661 kB 
jetpack-connect.aec3aa121de3e9ce84bd.js 443 kB
```

**Pull request merged**
