### PR TITLE
Migrate images in PremiumPlanDetails to be managed by webpack

### PR DESCRIPTION
**Pull request by jsnajdr**
That creates immutable names with a hash suffix for the image assets. Is a blueprint how to fix issues like #34634 or #34641. The URL will change if the source image changes.

Cc: @sirreal and @ockham who worked on the webpack file loader some time ago: opinions on the `client/assets/images` path for the webpack-managed assets? There's also an option to put the images in the same directory with the components that use them.

That doesn't work for `google-adwords.svg` though, which is used at 3 different places across the app.

**How to test:**
For a site with purchased Premium plan, go to
```
/checkout/thank-you/:site_slug/:receipt_id
```

Check that all images on the Thank You page are loaded, and verify in Devtools that the URLs are hashed:

Screenshot 2019-07-19 at 15 55 18

### CODE REVIEW

**Review by arunsathiya — COMMENTED** [review]
Code changes look good to me, and the illustrations appear as expected on Google Chrome.

Screenshot 2019-07-22 at 21 05 14

But, they do not appear on Firefox. 

Screenshot 2019-07-22 at 21 05 27

I have done basic troubleshooting to ensure that I am on latest version with extensions turned off and as such, but no luck getting them to work on Firefox.

**Comment by sixhours** [comment]
This PR is working for me; I see the correct hashed images in Firefox and Chrome.

Some images on the page are not hashed but they're not addressed in this PR so that makes sense.

**Comment by jsnajdr** [comment]
> But, they do not appear on Firefox.

I can reproduce: some images are not loaded on Firefox. No idea why. Will investigate. Thanks for catching this!

**Comment by jsnajdr** [comment]
> But, they do not appear on Firefox.

Turns out it was Adblock who blocked the image requests. Apparently the URLs match some of their rules.

I'll merge this PR now, will verify if Adblock blocks production URLs, too, and will report an issue with them if it does.

**Comment by arunsathiya** [comment]
>Turns out it was Adblock who blocked the image requests. Apparently the URLs match some of their rules.

Good find, giving it a closer look, I see the same behaviour! 👍🏽

**Pull request merged**
