### PR TITLE
Reader: add new card component for Refresh

### PR DESCRIPTION
**Pull request by jancavan**
Types of cards in Reader Refresh:

- **Card with thumbnail and excerpt:**
screenshot 2016-08-23 15 20 45

- **Photo-only card:**
screenshot 2016-08-23 15 20 48

- **Card with a photo gallery:**
screenshot 2016-08-23 15 22 42

- **Mobile:**
screenshot 2016-08-23 15 24 13

Test live: https://calypso.live/?branch=add/reader/refresh-new-card-component

### CODE REVIEW

**Comment by jancavan** [comment]
This branch has been rebased. Although not sure what happened to `style.css` for `reader-search-card`, it seemed to have reverted to the old one.

But in https://github.com/Automattic/wp-calypso/pull/7142/commits/dd0bcc52620a9f80471ecbbed2e504125d663a9d, I had updated that to match https://github.com/Automattic/wp-calypso/blob/90a8f3695c348667c9b9f114e2b6b57465c79dbe/client/blocks/reader-search-card/style.scss in https://github.com/Automattic/wp-calypso/pull/7377.

**Comment by jancavan** [comment]
**Need help with the following:**

- [ ] Content-specific breakpoints instead of browser-specific ones
- [ ] Changed page background to white. See: https://github.com/Automattic/wp-calypso/blob/05ad5cf02093d8c83e9cda29f0cc4065c92a40c1/client/blocks/reader-post-card/style.scss#L1 (But this needs to not affect all other pages that use `layout__content`

**Comment by hoverduck** [comment]
@jancavan: Our automated visual diff tests failed on the new "More in Site" / "More in WordPress.com" components on the /devdocs/blocks page, so this came to my attention.  The version that's currently live on wpcalypso has overlapping text at the mobile width.  From your screenshots here it looks like that's fixed by this PR, is that the plan?  Or should I write up an issue to track the problem as it exists now?

screen shot 2016-09-12 at 9 17 20 am

**Comment by jancavan** [comment]
@hoverduck This branch is still a WIP. The images are just mockups of what the cards are supposed to look like.

**Comment by jancavan** [comment]
Closing this. Superseded by https://github.com/Automattic/wp-calypso/pull/8463.

**Pull request closed without merging**
