### PR TITLE
Experiment: Restructure /me/security

### LINKED ISSUE #43144: Improve navigation for Security section as a result of Security Checkup
This issue stems from the discussion in #43101 around the behaviour of the nav bar due to the additional item added in that PR. The additional item makes the nav bar switch from a tab-like layout to a dropdown due to the default 720px width of the `Main` component in each of the security screens.

cc @fditrapani

#### Steps to reproduce

1. Starting at URL: `/me/security`
2. Enable the new Security Checkup feature via the `security/security-checkup` flag
3. See that the navigation shifts into a drop-down

#### What I expected
The items remain as a tab bar.

#### What happened instead
The navigation items are pushed into a dropdown component.

#dogfooding, #development

### PR DESCRIPTION
**Pull request by daledupreez**
#### Changes proposed in this Pull Request

* Push the new checklist format from #43101 to be the main nav for `/me/security`, which includes a split for actionable items versus informational ones. (Th
* To handle the above, push the change password page to `/me/security/password`.
* Restructure the individual pages under `/me/security` to use the `HeaderCake` component to provide a heading with a "Back" button to get back to the checklist at `/me/security`. (This isn't implemented for the account settings, where we change email.)

##### Open Questions
* How should we handle the password link/text until we can actually implement the infrastructure to work out when the password was last changed.

#### Testing instructions

* Navigate to the live build at https://calypso.live/?branch=try/me-security-restructure
* After you get redirected to the current UI, check that `/me/security` works as before
* Manually add `?flags=security/security-checkup` to the URL, and navigate to `/me/security/`.
* For each of the links, verify the following:
    - The link works
    - The page you navigate to includes a header with a "Back" button
    - The "Security" nav item on the left nav bar is selected for the page
    - Clicking on the "Back" button brings you back to the checklist at `/me/security` (except for the email row, as that navigates to `/me/account`)

Fixes #43144

### CODE REVIEW

**Comment by fditrapani** [comment]
This is coming along nicely! Thanks for the updates! I have some suggestions that will help simplify the screen and also line it up with how things look in Calypso:

- We don't have the new page titles in the Account section yet so it would be great to start adding them. I can see to it that we add them on the other sections.  
- It feels like there's a lot going on with the card title, main title, and sub title. I think we can reduce the copy down significantly while still conveying the same information. This is what I propose:

image

**Comment by daledupreez** [comment]
@fditrapani, would love your eyes on this from a design/UX perspective, as I won't have time to implement anything other than a stub for changing the password.

Relative to your mocks, I believe the only item that isn't the same is the Social Login icon, where we already had a slightly different icon in `material-design-icons`.

If you think this is looking OK, we may be in a position to get this out for broader testing and feedback.

**Comment by fditrapani** [comment]
The updates look good @daledupreez — nice work! 

> If you think this is looking OK, we may be in a position to get this out for broader testing and feedback.

Let's do it!

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/3907387

Hi @daledupreez, could you please edit the description of this PR and add a screenshot for our translators? Ideally it'd include all of the following strings:
- `Security Checklist`
- `You have a password configured, but can change it at any time.`

Thank you in advance!

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/3907387).

**Pull request merged**
