### PR TITLE
Posts: Update hover information on author selector

### PR DESCRIPTION
**Pull request by jeremeylduvall**
PR to address some tooltip weirdness in #6010. Currently, when you hover over the author navigation selectors on the Posts page in Calypso, you'll see hover text like `Me,[object, Object]`. This PR specifies a title attribute for the author navigation selectors so that you'll only see the desired text.

With the title attribute omitted, the nav item title field automatically picks up the inner text, which includes the desired text but also some info that determines whether or not to display the Gravatar like this:

```
{ textItem }
{ isMe && <Gravatar size={ 16 } user={ user.get() } /> }
```

We just need the `textItem` attribute in this case.

## To test
1. Load up this branch and visit the Posts page for a multi-author site on your account: https://wordpress.com/posts/site.wordpress.com
2. Hover over the "Me" and "Everyone" selectors at the top of the page. On hover, you should only see "Me" or "Everyone." If you visit this same page in WordPress.com, you'll have extra text added on to the hover tooltip.

## Screenshot

tooltip

Test live: https://calypso.live/?branch=fix/6010-posts-tooltip

### CODE REVIEW

**Comment by jordwest** [comment]
Huh, that's interesting, React must be inserting that title attribute. It doesn't seem there's any such logic in the `NavItem` component.. I wonder if it's related to the ARIA attributes.

In any case, LGTM 🚢

**Comment by jordwest** [comment]
Scratch that, it looks like the culprit is in Calypso, it's the `title` line in `client/components/segmented-control/item.jsx`:

```js
		return (
			<li className={ itemClassName }>
				<a
					href={ this.props.path }
					className="segmented-control__link"
					ref="itemLink"
					onTouchTap={ this.props.onClick }
					title={ this.props.title || this.props.children }
					role="radio"
					tabIndex={ 0 }
					aria-selected={ this.props.selected }>
					<span className="segmented-control__text">
						{ this.props.children }
					</span>
				</a>
			</li>
		);
```

From #1456:
> I wonder if we need titles at all here, considering the content is already text. Visually it seems distracting and kinda pointless to just see repetition of the same text when you hover over an item. So I'd say 🚢 this to get the production issue fixed, but we should spend a little time to look into the repercussions of removing the title attribute entirely.

I agree with @rralian here. It makes sense to remove that whole `title={ this.props.title || this.props.children }` line altogether, as this is basically the same issue as #1433/#1456 and will probably come up again somewhere else.

**Comment by jeremeylduvall** [comment]
Thanks for digging that up @jordwest. Will dig through the cases of where we're using `title` currently and look at the ramifications of potentially removing it.

**Comment by jeremeylduvall** [comment]
Took a peek at removing this @jordwest. I didn't see any major potential hiccups except for the editor hover, which displays potentially useful info (noted below). Places currently in-use:

- [wp-calypso/client/post-editor/post-editor.jsx](https://github.com/Automattic/wp-calypso/blob/09462f59f38fd45185edfc86a40bfd90af191872/client/post-editor/post-editor.jsx#L345)—The title field is used for Visual/Text editor selection ("Edit with a visual editor")
- [wp-calypso/client/my-sites/media-library/header.jsx](https://github.com/Automattic/wp-calypso/blob/02b588f897f1f3616ce562852506d4451c487093/client/my-sites/media-library/header.jsx#L189)—For the grid/list toggle when adding a media item on mobile devices (No regression)
- [wp-calypso/client/reader/following-edit/notification-settings.jsx](https://github.com/Automattic/wp-calypso/blob/12a27beda288923d5186807f1157f04389f54c06/client/reader/following-edit/notification-settings.jsx#L172)—For email frequency control on subscriptions
- [wp-calypso/client/me/help/help-contact-form/index.jsx](https://github.com/Automattic/wp-calypso/blob/63fc3f98a35ff907aa2715d31107ad254b3165e6/client/me/help/help-contact-form/index.jsx#L143)—On the Help page indicating "How can we help?" and "Mind sharing how you feel?"
- [wp-calypso/client/post-editor/media-modal/gallery/preview.jsx](https://github.com/Automattic/wp-calypso/blob/12a27beda288923d5186807f1157f04389f54c06/client/post-editor/media-modal/gallery/preview.jsx#L44)—For the "Preview" and "Edit" toggles during gallery creation within a post/page
- [wp-calypso/client/my-sites/posts/posts-navigation.jsx](https://github.com/Automattic/wp-calypso/blob/d251e90c668f2e7c94c135374c4a51515c1204d8/client/my-sites/posts/posts-navigation.jsx#L234)—As part of the `NavSegmented` author selector on the Posts list (the genesis of this PR)

The current version of the PR fixes the original issue and removes the title field. Thoughts?

**Comment by jordwest** [comment]
Nice! Thanks for finding those.

> I didn't see any major potential hiccups except for the editor hover, which displays potentially useful info (noted below).

For some reason I was thinking that the title would be implicitly sent to the `<a>` element inside `SegmentedControl` so that if a `title` prop was specified it would show. Looking again it doesn't look like that would happen (there's no `{ ...this.props }` in the `<a>` element), so we would lose that useful info. 

I think we should keep passing the title down explicitly, but remove the `this.props.children` fallback, so we'd end up with `title={ this.props.title }`. From the list of instances you've found I can't see that breaking anything.

**Comment by jeremeylduvall** [comment]
Updated to remove the fallback to `this.props.children` and updated the README as a result. Doesn't seem to have broken anything. I went through all of the spots above, and it still works properly (hover is back on the Visual/Text editor toggle and the Help options, for example).

**Comment by jordwest** [comment]
Cool, looks good to me!

**Pull request merged**
