### PR TITLE
Atomic Store: handle progress bar on Woo setup page better

### PR DESCRIPTION
**Pull request by lamosty**
In this PR, we are adding the following improvements to the Woo setup page ("Store" in sidebar) in the Atomic Store signup flow (`/start/atomic-store`):
- always show some progress, even if site is not transferring yet (better UX)
- if navigated away from the Woo setup page (to main Calypso view) and back to the page, the progress bar should show proper position according to transfer status
- stop persisting the `fetchingStatus` reducer so that we always try to fetch transfer status on full Calypso reload if a site has `has_peding_automated_transfer` site option

## Testing

Go through the Atomic Store signup flow. After clicking on the "create my store" on the checkout-thank-you page, you should be taken to the Woo setup page. Can you see a little bit of progress bar which is pulsing?

Now, try navigating away from the page while transfer is still not finished. Then, navigate back to it (either clicking on the "Store" button in sidebar or by using browser's back button). The progress bar size should respond to particular transfer status.

Try doing a full page reload on the Woo setup page. Is the progress bar on a correct place (in relation to particular transfer status)? Does it move when transfer progresses on the backend?

### CODE REVIEW

**Comment by kellychoffman** [comment]
I jumped from this screen:
screen shot 2017-10-25 at 3 45 28 pm

And then this screen flashed for a couple seconds:
screen shot 2017-10-25 at 3 45 41 pm

How can we prevent both of these screens from displaying? We only need one of them because as far as the user is concerned, they are doing the same thing.

The copy in the first screen is misleading, because the next step is adding in your location info. Can we change the copy of the first screen to say: 

*Building your store*
Give us a minute and we'll move right along.

**Comment by lamosty** [comment]
Thanks for your feedbacks!

> For example, I navigated away while progress bar was active, came back through Store sidebar button, and was shown a page with "Setup your store" button. After clicking on the button, progress bar was displayed.

This is currently expected and is out of the scope of this PR (the issue is also logged at our Trello). 
In Atomic Store, we don't show the "Set up my store" button when clicking on "Store" in the sidebar because the transfer process is happening on the background and customer clicks on "Create my store" on the checkout-thank-you page when going through the flow.

When the customer navigates away from the Woo setup page while the transfer is still happening on the backend, and then navigates back to it, we don't show the "Set up my store" button.

However, after the site transfers, it no longer has the `has_pending_at` or `signup_is_store` properties and so the Woo setup page behaves like for any standard Atomic site, thus showing the "Set up my store" after navigating to the page.

We could fix this by adding the `signup_is_store` site option even to an Atomic site. However, I think this is not really an Atomic Store issue since the same happens on a prod right now for any Atomic site using "Store".

Proper fix would be to keep track of the setup progress (installation of Woo/Woo plugins) in app state and if there's the process happening, don't show the "Set up my store" button but just continue.

Due to time constraints, we should not work on this issue right now but if people complain after opening up Atomic Store, we can work on this.

I like your other ideas @donpark but they are also out of the scope of this PR. :) Please add them to our Trello.

@kellychoffman 

> How can we prevent both of these screens from displaying? We only need one of them because as far as the user is concerned, they are doing the same thing.

> The copy in the first screen is misleading, because the next step is adding in your location info. Can we change the copy of the first screen to say:

Heh, this was changed to what the first screen says just a few days ago in #18992.

It should definitely not flash (so either the first copy or the second one shows) but we need to decide on the copy version. Can you confirm which one you prefer more?

**Comment by donpark** [comment]
@lamosty wrote:
> I like your other ideas @donpark but they are also out of the scope of this PR. :)

This is why I approved and what I meant by *will need iterative polishing*. It's easy to imagine UX flow but hard to *feel* it without actually using it. :-)

**Comment by kellychoffman** [comment]
> It should definitely not flash (so either the first copy or the second one shows) but we need to decide on the copy version. Can you confirm which one you prefer more?

Let's go with: 

**Building your store**
Give us a minute and we'll move right along.

**Pull request merged**
