### PR TITLE
Jetpack Cloud | Add Jetpack features comparison section

### PR DESCRIPTION
**Pull request by manzoorwanijk**
This PR adds a new section to Jetpack Cloud - `/features/comparison`

Discussion p2: p1HpG7-jrS-p2

#### Proposed Changes

* Create jetpack features comparison section components
* Add section to config files
* Create hooks for comparison data

#### Testing Instructions

- Do any one of these
    - Click on Jetpack Cloud live link below and wait for the redirect to complete, then go to `/features/comparison`
    - or boot up this PR 
        - Run `git fetch && git checkout add/jetpack-ft-comparison-section`
        - Run `yarn start-jetpack-cloud`
        - Goto [http://jetpack.cloud.localhost:3000/features/comparison](http://jetpack.cloud.localhost:3000/features/comparison)
- Confirm that the page exists and is not a 404.
- Confirm that the page is visible to both logged in and logged out users
- Change the language at the bottom using language switcher
- Confirm that it works for non-english languages
- Confirm that the design matches Figma both for desktop and mobile - RAs5UTOlm0w6zYP9MifV0r-fi-1%3A29

#### Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

Completes 0-as-1203485587457711/f

https://user-images.githubusercontent.com/18226415/209342717-43b043ba-88fb-4240-a187-f21ce830e9a2.mov

Screenshot 2022-12-23 at 6 48 14 PM
Screenshot 2022-12-23 at 6 48 32 PM
Screenshot 2022-12-23 at 6 48 47 PM

Screenshot 2022-12-23 at 7 00 42 PM
Screenshot 2022-12-23 at 6 58 50 PM

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - 0-as-1203449037077882

### CODE REVIEW

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/7695150

Thank you @manzoorwanijk for including a screenshot in the description! This is really helpful for our translators.

**Review by grbicsanja — APPROVED** [review]
LGTM!

**Comment by mattgawarecki** [comment]
@manzoorwanijk I ran into some odd visuals (on both calypso.live and in my local environment) that makes me think there may be a styling error somewhere in the changes this PR makes to the master bar. Check out the following screenshots from the new comparisons page, and from the pricing page on the same branch:

image
image

**Comment by mattgawarecki** [comment]
UPDATE: The issue I mentioned above seems to be Firefox-specific. Visiting on Brave shows the page normally. I had a hunch it involved the `:has` selector, which isn't supported by default, and enabling it manually solved my issue. Is there a way for us to move forward without `:has`, or would that add a significant amount of time?

**Comment by manzoorwanijk** [comment]
Thank you for catching that @mattgawarecki 

I have pushed a fix

Screenshot 2022-12-28 at 10 37 21 AM

**Comment by mattgawarecki** [comment]
The issue I reported appears to be fixed, and I wasn't able to identify any other blockers to deployment. Approved :shipit: and I'll ship this promptly as soon as the string freeze is complete.

**Review by mattgawarecki — APPROVED** [review]

**Comment by mattgawarecki** [comment]
Deploying without translations, per p1672245018661889/1671635067.918229-slack-C03V4PXKUGP and p1672247215519499/1672218240.237819-slack-C03V4PXKUGP.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/7695150).

**Pull request merged**
