### PR TITLE
Signup: decouple "shouldHideFreePlan" from site creation logic, allow skipping domain with "shouldHideFreePlan" as false

### LINKED ISSUE #67330: Keep free plan visible when the user clicks "Decide later" in domains page.

### PR DESCRIPTION
**Pull request by heavyweight**
#### Proposed Changes

* After the PR https://github.com/Automattic/wp-calypso/pull/67332 caused a regression, the changes were reverted.
* This PR adds unit tests for the function that generates the payload for new site creation.
* This function was also modified to decouple shouldHideFreePlan from the function. "shouldHideFreePlan" should be used for displaying visual changes to the user, depending whether or not we want to allow the user to skip a purchase, and should not be a part of the payload generator.
* Whenever a user select a domain free or paid, `siteUrl` is provided to the function and is more than enough for us to make the decision whether or not to use autogeneration.

#### Testing Instructions
- Checkout this branch
- Run `yarn start`
- Test on the [newsletter flow](http://calypso.localhost:3000/setup?flow=newsletter)
- And also test on the [link in bio flow](http://calypso.localhost:3000/setup?flow=link-in-bio)
- When clicking on "Decide Later" or selecting the free wordpress domain in the domains page you should see subheader with a link Screenshot 2022-09-02 at 18 08 17
- When selecting a paid domain it should NOT show a link to start with a free plan Screenshot 2022-09-02 at 18 37 50
- For tailored and normal flows test the free domain selection. Select a free wordpress domain and ensure that the domain assigned after the flow finishes is the same as the one you choose.

Related to #67330

### CODE REVIEW

**Comment by simison** [comment]
Since this is a bit tricky/complex, I wanted to add some details for testing:

> Test on the [newsletter flow](http://calypso.localhost:3000/setup?flow=newsletter)
> And also test on the [link in bio flow](http://calypso.localhost:3000/setup?flow=link-in-bio)

Important to also test:

- Free site launch flow
- Main signup flows when searching domain, and when clicking "pick domain later", when picking a paid domain, and when picking free domain.

> When clicking on "Decide Later" or selecting the free wordpress domain in the domains page you should see subheader with a link 

- For launch flow, "decide later" shouldn't be visible and free option at plans grid should be visible. (PR https://github.com/Automattic/wp-calypso/pull/66662)
- For main signup flows
    - the "decide later" should be visible and when chosen, free plan should not be visible at the plans grid.
    - when picking free domain, free option at plans is visible
    - when picking paid domain, free option at plans is not visible

**Comment by heavyweight** [comment]
Plan to extract `getNewSiteParam` outside of the index file in a follow up PR.
Didn't do it here, since it will be too noisy.

**Review by alshakero — APPROVED** [review]
Tested heavily and all works as expected.

**Review by leonardost — APPROVED** [review]
LGTM, tested main flows and seems to be working as expected. Thanks for adding these unit tests! 👍

**Pull request merged**
