### PR TITLE
Login: Support Jetpack color scheme for 2FA screens

### LINKED ISSUE #13419: WP-Admin Connect Flow: Connecting to an account with 2fa shows many unwanted links, wrong color scheme
#### Steps to reproduce the issue

1. On a disconnected Jetpack site with the wp-admin connect flow enabled
2. Click through the flow
3. If you are logged in, click "Switch account"
4. Click the "Connect with WordPress.com" button
5. Attempt to log in with a WordPress.com account that uses 2fa

#### What I expected
A Jetpack-themed 2fa confirmation screen that keeps me in the connect flow no matter what I do

#### What happened instead
A WPCOM-themed confirmation screen with lots of links out of the flow

**Screenshots**

jetpack-connect-2fa-credentials-screen

### PR DESCRIPTION
**Pull request by tyxla**
#### Changes proposed in this Pull Request

* Login: Support Jetpack color scheme for 2FA screens

#### Preview

2FA push notification screen (before):

2FA push notification screen (after):

2FA authenticator screen (before):

2FA authenticator screen (after):

Re design review: I realize these testing instructions are complex, so glancing at the screenshots should be enough for now. There are a couple of minor things like border and text colors, but we can fix these in subsequent PRs. The purpose of this PR is to reuse the same Jetpack color scheme we already have in other screens, for the 2FA screens.

#### Testing instructions
* Checkout this branch on your local Calypso.
* Start Calypso (`npm start`)
* Make sure you're logged out of WP.com.
* Go to http://calypso.localhost:3000/log-in/jetpack/
* Log in with an account that has 2FA enabled.
* Verify that the 2FA screens have the Jetpack color scheme.
* Verify you're able to complete the log in process.
* Go to http://calypso.localhost:3000/log-in/
* Verify that the 2FA screens **don't** have the Jetpack color scheme.
* Verify you're able to complete the log in process.
* Verify you're able to log in as a user that has 2FA disabled.
* Try this with the new Jetpack connect-in-place flow:
  * Start a new JN site with the latest bleeding edge Jetpack: https://jurassic.ninja/create?jetpack-beta
  * Enable the iframe constant from the constants settings page in your JN site.
  * SSH into the site using the command in the JN site admin notification.
  * Navigate to the WP installation dir by calling `cd DIR` where `DIR` is the path as specified in the JN site admin notification.
  * `vim wp-config.php`
  * `:i` to go to INSERT mode.
  * Add `define( 'CALYPSO_ENV', 'development );` somewhere where the other constants are.
  * Press `esc` key to leave INSERT mode.
  * `:w` to save.
  * `:q` to quit.
  * Make sure you're logged out of WP.com.
  * Go to `/wp-admin/admin.php?page=jetpack#/dashboard` in the JN site.
  * Connect the site for a WP.com user that has 2FA enabled.
  * Verify you can see the Jetpack color scheme for the 2FA screens, so they're consistent with the login screen.

Fixes https://github.com/Automattic/jetpack/issues/13419

### CODE REVIEW

**Comment by keoshi** [comment]
I haven't tested this PR yet, but from looking at your screens it seems the link above `Get Help` has a lighter bottom border? I'll take a closer look soon.

**Comment by tyxla** [comment]
> I haven't tested this PR yet, but from looking at your screens it seems the link above `Get Help` has a lighter bottom border? I'll take a closer look soon.

True! Just posting part of my PR description here in case it got lost between the screenshots:

> Re design review: I realize these testing instructions are complex, so glancing at the screenshots should be enough for now. There are a couple of minor things like border and text colors, but we can fix these in subsequent PRs. The purpose of this PR is to reuse the same Jetpack color scheme we already have in other screens, for the 2FA screens.

I'm going to be addressing those separately, they're not strictly related with this PR.

**Comment by keoshi** [comment]
🤦‍♂ Ignore me, Marin. haha

**Comment by tyxla** [comment]
> 🤦‍♂ Ignore me, Marin. haha

Nono, I appreciate your comment, as I might have missed these details easily 😉

**Review by roccotripaldi — APPROVED** [review]
This works well, and the code seems reasonable.

**Comment by roccotripaldi** [comment]
Note, while testing this, I discovered a related issue.

https://github.com/Automattic/wp-calypso/issues/36341

We can address it in an other PR.

**Comment by tyxla** [comment]
Thanks, folks! Going to merge, mostly to make design review easier. Will be taking care of the small details in separate PRs.

**Pull request merged**
