### PR TITLE
Add timeline component - take 2

### PR DESCRIPTION
**Pull request by tyxla**
Take 2 of #38278 - take 1 was reverted.

### CODE REVIEW

**Comment by tyxla** [comment]
@delputnam after #38308 we have to import certain components from `@automattic/components`:

* Button
* Card
* ProgressBar
* Ribbon
* ScreenReaderText

That should fix the problem. You can read p4TIVU-9ks-p2 for more details.

**Comment by delputnam** [comment]
Thanks for the fix @tyxla  and sorry for the mistake.

**Comment by tyxla** [comment]
No worries at all @delputnam, no harm done. Let me know if I can assist with anything 😉

**Comment by delputnam** [comment]
@tyxla I've fixed the offending imports in c980c24.  Did you see anything else that needs attention?

**Comment by tyxla** [comment]
@delputnam things are looking good! Feel free to 🚢 it at your convenience. Thanks!

**Pull request merged**
