### PR TITLE
[Revert the revert][Odie] Apply new help center redesign for Wapuu"

### PR DESCRIPTION
**Pull request by AllTerrainDeveloper**
Reverts Automattic/wp-calypso#83368

There seems to be an issue registering the HelpCenter data stores, [the data stores are being init'd with empty values for the client and secret id](https://github.com/Automattic/wp-calypso/pull/83372/files#diff-51867ba647ba693b7b9d0caa0bff6b21ff050010d0cdcbe5955eac2c4dac2cbc). This has been a bit thought to discover, pinging @alshakero @worldomonation @zaguiini as adding here the fix that will likely fix the e2e tests.

### Original Pull Request:
Related to: https://github.com/Automattic/ai-services/issues/555

This set of changes are intended to implement @mattrwalker changes for the Help Center integration with Odie. This is still a work in progress chain of Pull Requests, follow up pull requests will follow.

## Proposed Changes

- Added avatars for the conversation
- Moved the Odie code in Help-Center content to its own component
- Added new look and feel for the chat messages
- Added new look and feel for the input messages
- Added new button to jump to the most recent messages
- Added EllipsisMenu in the header with options (new chat, send transcript)
- Added new way of displaying the feedback for each message
- Cleaned **A LOT** of unused code
- Added some translations

## Testing Instructions

The way to test this is basically append to the URL the flag wapuu, eg: `http://...?flags=wapuu`

1. Click on the ? icon in the master bar, located in the top right corner.
2. Click on Still need help?
3. A new and fancy chat should open
4. Test the behaviour of the following things
    - Jump to Recent button, works as desired (it appears when we are not in the bottom of the conversation, it takes you to the bottom of the conversation when clicked
    - Minimise icon will hide everything and nothing will remain visible (a part for the minimised Help Center bar) 
    - Typing long texts will move the Jump To Recent button upper (just type a few `shift-enter` characters)
5. The Send message feature is out of scope for this pull request, that's a follow up
6. Clear conversation and send transcript will be also a follow up pull request

See video for easier verification:
https://github.com/Automattic/wp-calypso/assets/5689927/b839f9a1-7fd7-4e16-b380-02062ab3b96e

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

**Review by paulopmt1 — COMMENTED** [review]
The flow http://calypso.localhost:3000/setup/videopress is working as expected, thanks for fixing it @AllTerrainDeveloper!

**Comment by worldomonation** [comment]
Ran the Pre-Release Tests build against this branch (PCYsg-JGn-p2). 

Tests passed as expected 🎉 
image

**Review by worldomonation — APPROVED** [review]

**Comment by worldomonation** [comment]
The only one suggestion I may make, is in the future consider if it's possible to break the PR up into smaller pieces that can stand on its own. Smaller PRs lead to higher code quality because it's easier to keep track of everything in a smaller PR. 

[Small Pull Requests: 6 reasons why they are the best choice](https://blog.codacy.com/small-pull-requests)

**Comment by AllTerrainDeveloper** [comment]
> The only one suggestion I may make, is in the future consider if it's possible to break the PR up into smaller pieces that can stand on its own. Smaller PRs lead to higher code quality because it's easier to keep track of everything in a smaller PR.
> 
> [Small Pull Requests: 6 reasons why they are the best choice](https://blog.codacy.com/small-pull-requests)

I fully agree with you, but sometimes it's hard to do so due to work accumulating, and cascade pull request are also a bit painful.

Anyway, I fully agree with you, I'll do my best next time

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/9499342

Some locales (Japanese) have been temporarily machine-translated due to translator availability. All other translations are usually ready within a few days. Untranslated and machine-translated strings will be sent for translation next Monday and are expected to be completed by the following Friday.

Hi @AllTerrainDeveloper, could you please edit the description of this PR and add a screenshot for our translators? Ideally it'd include all of the following strings:
- `Start a New Chat`
- `Send Transcript to Email`
- `User profile display picture`
- `%(botName)s profile picture`
- `Loading state, awaiting response from %(botName)s`
- `Icon to expand or collapse %(botName)s messages`
- `Arrow icon`
- `Sources:`
- `Jump to recent`
- `Ask your question`

Thank you in advance!

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/9499342).

**Pull request merged**
