### PR TITLE
Framework: Introduce utility to check if we are in development env

### PR DESCRIPTION
**Pull request by gziolo**
We want to make it easier to fork Calypso and use as a base for another application. To make it possible we need to have a way to add config files that are regonized by Calypso as development env. This PR tackles this use case. When you create new config file which ends with `development`, example: `mc-development.json` it should work the same way as it currently does for `development.json` file.

### Testing
* Run `npm run test-server` to make sure new unit tests pass.
* Run `make run` - it should work as before.
* Copy `development.json` and name it `whatever-development.json`, run `CALYPSO_ENV=whatever-development make run` - it should work exactly the same as development.
* Run any other env to make sure it still works as before.

/cc @janm6k @mtias @nb

### CODE REVIEW

**Comment by mtias** [comment]
Does it make more sense to use a suffix convention or create another config attribute like `development: true`?

**Comment by mtias** [comment]
@gziolo I think some of the Jetpack (cc @roccotripaldi) wanted to make some changes to the way we determine the environment since wpcalypso is considered production. Perhaps in this case `"env": "development"` is ok, and we have another attribute like (host) to target?

**Comment by gziolo** [comment]
I now see that we have `env: "development"` set for `development.json` and `test.json` config files. Which means we could base this check only on this setting. I would still keep utility method to make it easy to update in the future.

**Comment by gziolo** [comment]
@mtias I applied some more changes what about now?

/cc @rralian FYI: this is one of the changes required to use fork of Calypso with newly created config file behaving like `development.json`.

**Comment by gziolo** [comment]
I come up with a different solution which requires only one line change. I'll open follow up PR soon.

**Pull request closed without merging**
