### PR TITLE
Framework: protect-form needs to check previous before using it

### PR DESCRIPTION
**Pull request by blowery**
### Repro
1. Load the reader
2. Hit the new page icon in the masterbar
3. Enter a bit of text, and _then hit back before autosaving_
4. Get the 'save changes' prompt. **Hit Cancel**. 
5. protect-form explodes trying to set page to the previous url, which isn't available. Notice error in console

### With Patch
no :boom: just leaves you alone

### Movie
https://cloudup.com/ceGtKpD4z5G

tune is https://open.spotify.com/track/5K37bWvP5ycFokOEDemJvW

### CODE REVIEW

**Comment by aduth** [comment]
Hmm, while it resolve the error, this still isn't quite right. After canceling the prompt, the URL remains "/" (the back path) until the next autosave, instead of resetting to the editor path. It seems like we'd need some fallback using `nextPath` (doesn't exist) or `window.history.forward()` (many many dialogs when I tried this in my testing).

**Comment by blowery** [comment]
yeah, noticing that myself now. hrmmmmmm.

**Comment by blowery** [comment]
the problem is that we're updating the URL _before_ we pop the dialog...

**Comment by blowery** [comment]
```
// warn against navigating from changed, unsaved forms
	page( '*', require( 'lib/mixins/protect-form' ).checkFormHandler );
```

probably needs to be an exit handler.

**Comment by aduth** [comment]
>probably needs to be an exit handler.

Sounds right to me.

**Comment by blowery** [comment]
> Sounds right to me.

Hrm. exit routes run _after_ the url has changed.

**Comment by blowery** [comment]
> Hrm. exit routes run after the url has changed.

Ah, no, that's wrong. But they can't prevent the current navigation from happening by not calling `next`

**Comment by blowery** [comment]
@aduth worth a look again i think

**Comment by aduth** [comment]
This looks good and works well from my testing :+1:

**Pull request merged**
