### PR TITLE
Plans: Setup A/B test for upgrade pricing display

### PR DESCRIPTION
**Pull request by taggon**
This PR will update the plans page to reduce the confusion about the pricing of the plans. The changes introduce new credit summary. See p9jf6J-b5-p2 for more detail.

## How to test

1. Set `upgradePricingDisplay` test to `modified`.
1-1. You can set the test by running the following script in browser console.
```
localStorage.setItem( 'ABTests', '{"upgradePricingDisplay_20180213": "modified"}' );
```
2. Pick a WP.com site and go to the plans page.
3. You should be able to see the credit summary as follows:
taggon_on_wordpress_ _wordpress_com
4. Move to the plans page of a Jetpack connected site and check if it looks like the followings:
taggon_at_pressable_ _wordpress_com 2
taggon_at_pressable_ _wordpress_com

Here are some details for testing:

* The price label in the plan features header should display the original one, not the discount price.
* Current plan should not have the "Credit available" label.
* Jetpack pricing can be different based on the site.
* The plan title just below the "Credit summary" should not display capitalized "Plan". It should be lowercased "plan".
* The current Jetpack plan should show the discount price in the header and should not display the summary section.

### CODE REVIEW

**Comment by donlair** [comment]
Couple things jump out at me:

1) The language in the banner should be "You have $XX in upgrade credits available! Apply the value of your current plan towards an upgrade before your credits expire!"

2) This should not have slash at the top, it should have the full value and "credits available" label. I thought we were talking about something else on slack earlier, sorry about the confusion.

For Jetpack, what do the screens look like if the the user has Plan credits available?

This is my first time loading a test environment at A8C. Is there a way to force myself into a test cell so I can see the test version? I'm getting the control experience right now.

**Comment by fditrapani** [comment]
Thanks for putting this together @taggon. There's only one thing otherwise it looks good to me. I noticed we still had the little "i" next to `/month, billed annually`. We can remove it from our variant as they don't really make sense.

image


@donlair you should be able to change your test cell by using the toggle in the bottom right. 
cell

**Comment by fditrapani** [comment]
Another thing on Jetpack. I noticed the discount shows on your current plan:
image

**Comment by rachelmcr** [comment]
@taggon This test seems to be working incorrectly for Jetpack sites on the Free plan. I'm seeing this message on the Plans page:

> You have £50.00 in upgrade credits available! Apply the value of your current plan towards an upgrade before your credits expire!

I see the expected yearly v. monthly discount pricing for the plans, but I shouldn't have any amount of "upgrade credits" since I'm on the Free plan.

screenshot 2018-02-26 12 59 57

Let me know if you'd like me to open this as a separate issue.

**Comment by taggon** [comment]
@rachelmcr Thanks for reporting this. Technically it is not a bug but looks like the test confuse you with the incorrect language. I will have discussions on this with @donlair and fix it. Again, thanks!

**Comment by donlair** [comment]
Thanks Rachel @rachelmcr! As @taggon mentioned, this is working as expected. We discussed this with the Jetpack team ([here](https://jpopgrowth.wordpress.com/2018/02/13/updating-the-plans-page-for-jetpack/#comment-7880)) and we decided to keep the language consistent between WP.com and Jetpack, even though it isn't a perfect fit for Jetpack.

Longer-term, we'll need to make some tech changes to distinguish between term-driven discounts and upgrade credits. For now, they're both rolled into a single line item called "upgrade credits".

**Pull request merged**
