### PR TITLE
Advanced SEO: Update Sharing Preview Button

### PR DESCRIPTION
**Pull request by roundhill**
It was decided that the 'Sharing' icon didn't make much sense for the social preview:

screen shot 2016-08-15 at 4 18 38 pm

This PR changes the icon to be 4 `SocialLogo` items close together to represent each menu on the left that you see when on the social preview pane:

screen shot 2016-08-15 at 4 24 02 pm

It also adds a new `google` icon type and corresponding SVG.

cc @apeatling @dmsnell @vindl @rodrigoi 

Test live: https://calypso.live/?branch=update/advanced-seo-toolbar-icon

### CODE REVIEW

**Comment by dmsnell** [comment]
@roundhill is this what we decided to replace the sharing button with? It doesn't look like it belongs with the other icons and in my opinion is a bit busy.

**Comment by roundhill** [comment]
> @roundhill is this what we decided to replace the sharing button with? It doesn't look like it belongs with the other icons and in my opinion is a bit busy.

Yes, which is why I made the PR... totes open to other ideas though!

**Comment by dmsnell** [comment]
I think that a text label was brought up at one point.

**Comment by folletto** [comment]
> It doesn't look like it belongs with the other icons and in my opinion is a bit busy.

Agreed. Up there we can have either an icon or icon+label. So I think the two options are:

1. New icon
2. Add label

I'd personally go for a new icon because it's something that a user can just discover by clicking, so it's ok if it's a bit hidden, but otherwise a label could work too if we feel it needs more visibility than the responsive icons.

**Comment by roundhill** [comment]
I agree that it does look out of place. Here's some more ideas. Does anyone like any combination of the text or icons you see here?

screen shot 2016-08-16 at 9 33 17 am
screen shot 2016-08-16 at 9 26 46 am
screen shot 2016-08-16 at 9 27 20 am
screen shot 2016-08-16 at 9 28 10 am
screen shot 2016-08-16 at 9 28 43 am

**Comment by folletto** [comment]
"SEO" seems fitting: even if not entirely semantically accurate, it resonates with the plan offering (and would solve many translation issues). Social preview seems good as well, even if far longer.

I think it needs an icon ad-hoc.

**Comment by roundhill** [comment]
> I think it needs an icon ad-hoc.

Do you mean a custom icon? If so, any ideas on what it could look like? Best I can think of is a globe, or a magnifying glass, or a globe with a magnifying glass ;)

**Comment by folletto** [comment]
Super quick mocks, but could be something like:

screen shot 2016-08-16 at 18 07 46

Which as mentioned might work well and not require a label at all. :)

**Comment by apeatling** [comment]
What about something like this, that reflects more of a card preview?

screen shot 2016-08-16 at 10 22 27

**Comment by dmsnell** [comment]
> What about something like this, that reflects more of a card preview?

I miss my old Speak & Spell…

**Comment by folletto** [comment]
> What about something like this, that reflects more of a card preview

Yes, that direction could work too. 
Let's just avoid the "credit card" look (also, just one color). :D

**Comment by apeatling** [comment]
screen shot 2016-08-16 at 10 48 19

**Comment by apeatling** [comment]
Slightly thicker might fit with the other icons better?

screen shot 2016-08-16 at 10 49 11

**Comment by roundhill** [comment]
> Slightly thicker might fit with the other icons better?

It does fit better, but the Reader card has a thin border so I kind of like that better.

**Comment by folletto** [comment]
Please note that it has to match [Gridicons](https://github.com/Automattic/gridicons)' guidelines (line weight, rounded corners, ...).

I'd open an issue on Gridicons issue board and iterate there.

**Comment by roundhill** [comment]
I think we're on the right track with the `Card`. Good idea @apeatling!

**Comment by dmsnell** [comment]
Although I like the icon in design, I don't see a strong relationship between it and the previews. In general, I guess this is a fairly abstract thin to try and visualize in an icon. Some testing here might be useful (qualitatively) to figure out which of an array of icon ideas people associate with previewing their shared content.

**Comment by roundhill** [comment]
> Although I like the icon in design, I don't see a strong relationship between it and the previews

I think it associates fairly well, as it looks like the cards you see in most of the previews (except for Google).

**Comment by vindl** [comment]
> Best I can think of is a globe, or a magnifying glass, or a globe with a magnifying glass ;)

We are already using the globe icon in sidebar for domains, but I like the idea:

**Comment by roundhill** [comment]
https://github.com/Automattic/gridicons/issues/181 could take a while, so for now we are going to go with the globe icon.

I still left the new google logo in this PR so we can still use it in the `VerticalMenu` item.

@dmsnell care to take a look?

**Comment by dmsnell** [comment]
looks good to me @roundhill

**Comment by apeatling** [comment]
@folletto Opened here https://github.com/Automattic/gridicons/issues/181

**Comment by roundhill** [comment]
Merging for now, we can iterate on the icon in a future PR!

**Comment by melchoyce** [comment]
Hey — just saw this in the wild and was completely baffled by the globe icon. I had to ask someone what it did (because I was afraid if I clicked it, it might do something I didn't want). There's no alt text or anything on hover to tell you what it is. Looking back on the conversation, I'd +1 including a label. @apeatling's icon suggestion is a little better, but a label is still much more clear. 

Also not totally sure it should be directly next to the device icons — those physically change the size of the modal. The display previews don't change the modal, they change what you're previewing itself. Maybe a divider would help separate it from the others?

**Comment by rickybanister** [comment]
I thought @apeatling's icon was more about the post/page template or something. Of all the options, it feels like the sharing icon was at least related to the function of the button (as it relates to the sharing section in Calypso). But I agree with @melchoyce that each should get a nice tooltip treatment to help explain them.

**Comment by apeatling** [comment]
@roundhill -- let's add an SEO label for now since it will clear up some confusion. We can keep iterating on the icon and style after launch.

**Comment by apeatling** [comment]
It wouldn't hurt to add the divider Mel mentioned too.

**Comment by roundhill** [comment]
Divider + `SEO` label to come in another PR soon then!

**Pull request merged**
