### PR TITLE
Repeat Visitor: add additional block keywords

### PR DESCRIPTION
**Pull request by bluefuton**
#### Changes proposed in this Pull Request

Based on feedback in our internal call for testing (p1HpG7-6k7-p2), this PR adds additional keywords to help new users discover the Repeat Visitor block.

#### Testing instructions

Spin up a [Jurassic Ninja instance](https://jurassic.ninja/create/?gutenpack&calypsobranch=update/repeat-visitor-keywords).

Connect Jetpack to your WPCOM account.

Navigate to Settings->Jetpack Constants, check JETPACK_BETA_BLOCKS, and Save.

Navigate to the post editor and click + to add a new block. Try searching for a block with the following terms and make sure that Repeat Visitor is suggested:
* visitor
* hidden
* conditional

### CODE REVIEW

**Comment by bluefuton** [comment]
This relies on https://github.com/mukeshpanchal27/gutenberg/commit/d8be247e36e09c249f3933b6dccf453133f0543b which was committed today but has not been released yet. It removes the previous 3-keyword restriction on block keywords:

screen shot 2019-02-27 at 14 42 53

**Comment by bluefuton** [comment]
> This is good to go whenever appropriate.

Thanks! Exceeding 3 keyword limit actually prevents the block from showing up at all :/ So I'll hold off shipping it until that's resolved.

**Comment by bluefuton** [comment]
@beaulebens also suggested "return" as a keyword during testing: p8oabR-lg-p2

**Comment by simison** [comment]
https://github.com/WordPress/gutenberg/pull/13848 only removes the error stopping the block from functioning, but the limit still holds. Gutenberg will ignore more than 3 keywords and there are no plans to remove that limitation.

**Comment by bluefuton** [comment]
Thanks for clarifying, @simison. I'll close this one.

**Pull request closed without merging**
