### PR TITLE
Jetpack Connect: Add site card

### LINKED ISSUE #4963: Jetpack Connect: Show blogname on authorization screen
We should show the blogname on the Jetpack Connect authorization screen to provide a more personalized UI - Illustrated here:
1086a8d2-016e-11e6-9a35-6ceed04c3daa-1

https://github.com/Automattic/jetpack/pull/3717 - adds `blogname` to the connection url

### LINKED ISSUE #5237: Jetpack Connect: Authorization screen uses domain name instead of site URL
### Steps to reproduce:

1. Create a site in a subdirectory of a domain, e.g. mysite.com/blog/
2. To access that site, you need to go to mysite.com/blog/ . mysite.com may not be a WordPress site at all.
3. Go through the connection process
4. After installing Jetpack, you are redirected to https://wordpress.com/jetpack/connect/authorize to authorize the connection.
5. The connection screen lists the domain name, and not the site URL:

screen shot 2016-05-05 at 3 35 47 pm

### PR DESCRIPTION
**Pull request by roccotripaldi**
Adds a site card to the authorization form based on [Ricky Bannister's mocks](https://github.com/Automattic/wp-calypso/issues/4963).

I could not use the Site component directly because it relies on the selected site within the site's list. Since the site we are connecting is not yet part of the site's list, I simply created a sub-component within AuthorizeForm that uses the same mark up as the Site component.

Fixes #5237 
Fixes #4963

To test:
- run the latest master of Jetpack on your unconnected Jetpack site
- set a site icon on your Jetpack site
- running this branch locally, go to calypso.localhost:3000/jetpack/connect
- connect your jetpack site
- your authorization screen should look like this:
screen shot 2016-05-29 at 1 54 05 pm

cc: @johnHackworth @rickybanister

### CODE REVIEW

**Comment by mtias** [comment]
@roccotripaldi did you try passing a `site` object as a prop with the same structure to `my-sites/site`?

**Comment by johnHackworth** [comment]
this is great rocco!!

We have a little bug related with encoding, though:

image


encoding, grrr /me shakes fist

**Comment by johnHackworth** [comment]
Added some decodeEntities magic:

image

**Comment by rickybanister** [comment]
Didn't we use `Site` for invites, as in 'you've been invited to [ ] Site' ?

In that case the site would not have been part of your sites list yet, right? How did that work?

**Comment by roccotripaldi** [comment]
> In that case the site would not have been part of your sites list yet, right? How did that work?
@rickybanister, i think the suggestion from @mtias will allow us to use `Site`. Working on that now.

**Comment by roccotripaldi** [comment]
I switched over to the `Site` component per @mtias . Now we have this:

screen shot 2016-06-01 at 9 34 55 am

**Comment by rickybanister** [comment]
Awesome. Looks like we have some double padding/margin going on there though.

**Comment by mtias** [comment]
Great. It'd be nice to drop the protocol to match `site.domain`.

**Comment by johnHackworth** [comment]
works great!! But yeah, I also see the double padding issue @rickybanister is mentioning

**Comment by roccotripaldi** [comment]
Thanks guys. Removed protocol and extra padding:

Here's the logged out and logged in view:

screen shot 2016-06-02 at 10 33 34 am


screen shot 2016-06-02 at 10 35 02 am

**Comment by rickybanister** [comment]
Looks awesome! Ready to go.

@ebinnion here's what we were talking about yesterday regarding SSO ^

**Comment by johnHackworth** [comment]
Works great ! :+1:  :ship:

**Comment by mtias** [comment]
Thanks for all the changes :)

**Pull request merged**
