### PR TITLE
Theme Showcase: Update WordPress.com Experts nudge to use UpsellNudge

### PR DESCRIPTION
**Pull request by sixhours**
#### Changes proposed in this Pull Request

* Following a long and tedious journey from #54140, #54522, and #54608, this updates the WordPress.com Experts nudge to use the UpsellNudge component

**Before**

Screen Shot 2021-07-13 at 1 32 53 PM

**After**

Simple/Atomic

Screen Shot 2021-07-13 at 1 32 17 PM

Jetpack

Screen Shot 2021-07-13 at 1 32 36 PM

#### Testing instructions

* Switch to this PR, navigate to `/themes`
* Make sure clicking on the banner/button takes you to the "Built by WordPress.com" site: https://wordpress.com/built-by-wordpress-com/
* Make sure Tracks events fire as expected (impression, click, dismiss)

Related to #54087

### CODE REVIEW

**Comment by mreishus** [comment]
I used to see the nudge after switching to the all tab, but now I'm not seeing it anymore. Also seeing the same thing on the calypso live link.


Edit: I believe it's redux mapstatetoprops had `isBannerVisible` removed, but the render function is still checking for it.

**Comment by sixhours** [comment]
> I used to see the nudge after switching to the all tab, but now I'm not seeing it anymore. Also seeing the same thing on the calypso live link.

Hmm, did you dismiss it at some point to check Tracks events? You may need to reset the dismiss flag in your preferences...

Screen Shot 2021-07-16 at 10 08 09 AM

**Comment by mreishus** [comment]
I still see the banner on the trunk branch, but not this one. I also tried resetting all preferences that begin with `dismissible-` and that didn't work either. I believe it's being caused by [this code](https://github.com/Automattic/wp-calypso/blob/ce1c223008b17fdaef20c7a94afbe80bedf13109/client/blocks/upwork-banner/index.jsx#L33-L35) checking `isBannerVisible`, where mapStateToProps is no longer passing that prop:

**Comment by sixhours** [comment]
> I believe it's being caused by this code checking isBannerVisible, where mapStateToProps is no longer passing that prop:

Aha, I need to remove that check, because I'm letting the UpsellNudge component handle the banner's dismissal state now; prior to this it had its own state for isBannerVisible. Looks like I had removed it in #54140 but forgot to do so here.

**Review by mreishus — APPROVED** [review]
:+1: Working for me now

**Comment by tyxla** [comment]
Further cleaning up an unused selector in #60123.

**Pull request merged**
