### PR TITLE
BBE: Update the page picker step for the store flow

### PR DESCRIPTION
**Pull request by aneeshd16**
#### Proposed Changes

PT: pdh1Xd-1Cz-p2

Parent PR: https://github.com/Automattic/wp-calypso/pull/71626

This PR introduces a few changes to the page picker step for the store flow:
* Adds a new page "Shop". This page is available only in the store flow and will be required by default. It cannot be unselected.
* Introduces a new translation context for the page picker step. This allows us to show different descriptions for pages depending on the flow.
* Swaps the order of the "Services" & "FAQ" pages.
* Hides the "Pricing" page.
* Adds the Popular badge to the "Testimonials" page.
* Changes the copy of the subheader.
* Modifies the DIFM cart to accommodate the Business plan, which is required for BBE with the store flow. (The backend changes have already been shipped)

#### Testing Instructions

* Go to `/start/do-it-for-me-store`.
* Select "New Site" and go through the flow steps till you reach the page picker step.
* Confirm that the "Shop" page is visible and cannot be unselected.
image

* Confirm that the description for the Shop page matches the screenshot.
image

* Confirm that the description for the Home page matches the screenshot.
image

* Confirm that the subheader copy matches the screenshot.
image

* Confirm that the FAQ page is in the third row and that there is a Popular badge on the "Testimonials" page.
image

* Confirm that the Business plan is visible in the mini-cart and that the totals add up.
image

#### Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

Fixes Automattic/martech#1375

### CODE REVIEW

**Review by southp — APPROVED** [review]
Works as described. LGTM 🚢 

Though one thing I'd encourage you to tinker on is how we move away from those `isStoreFlow` conditions spreaded among multiple components. It's intuitive and works at the beginning, but tend to become a maintenance headache later when more and more variations introduced. There are multiple ways to solve this.
For example, this is one of the scenarios that class inheritance of OOP is designed to solve: extract the common behavior into the base class, and implement the variations in the subclasses. We can also think of extracting those data into a certain data type and fill them in depending on whether it's the store flow or not and feed them into the underlying components from the parent components; that way there would be only one `isStoreFlow` conditional statement somewhere in the parent component. etc. etc.

I'll defer to your best judgement on this. For now, this PR is already a solid step forward :)

**Comment by aneeshd16** [comment]
Thanks for the review!

> Though one thing I'd encourage you to tinker on is how we move away from those isStoreFlow conditions spreaded among multiple components. 

I agree with your assessment here. The solution I had in mind was to identify where the behaviour of this component changes and replace the conditionals with props that would be passed to the component. There are a few places where this would be tricky and might involve a big refactor, for example: controlling the order of pages shown or the badges shown on pages. The props based approach seems reasonable, but I'll wait for thoughts on this  approach in this post: pdDR7T-vO-p2.

One definite change that can be done here is instead of passing `isStoreFlow` to `useCartForDIFM`, we can pass `activePlanScheme`. I'll do this in a follow up PR!

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/7726493

Thank you @aneeshd16 for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/7726493).

**Pull request merged**
