### PR TITLE
Test: Add in a run-test script that you can pass a file to

### PR DESCRIPTION
**Pull request by blowery**
Little helper for the time being. grep is a pain sometimes.

### CODE REVIEW

**Comment by blowery** [comment]
cc @gziolo 

I think we'd can this eventually, but I had a bunch of folks ask me how to pass a file to the new runner today. 

Could also teach the test- grep magic to turn - into a space. So `make test-foo-bar` should turn into `--grep "foo bar"`

**Comment by blowery** [comment]
I didn't put this in `bin` because it needs to have the test;client node path. server would need it's own variant that sets test;server;client. :/

**Comment by gziolo** [comment]
I made some experiments using `package.json` and `npm run` approach. Please check #4038. It allows us to get rid of `client/Makefile` and we don't need to create `client/run-test`. I added there also several other improvements.

**Comment by aduth** [comment]
>I think we'd can this eventually, but I had a bunch of folks ask me how to pass a file to the new runner today.

In the end, what do we think would be the ideal workflow for running a single test file?

**Comment by blowery** [comment]
Closing in favor of #4038

**Comment by blowery** [comment]
> In the end, what do we think would be the ideal workflow for running a single test file?

`npm test -- that/file` would be best and idiomatic

I could like with `npm run test-client that/file.js`

**Pull request closed without merging**
