### PR TITLE
Enable My Home for all roles

### LINKED ISSUE #19506: Users without manage_options capability don't have a Dashboard/My home link in wp-admin navigation
#### Steps to reproduce the issue

1. Make sure you login with a user role that doesn't have manage_options role (e.g. Author)
2. After login, you'll be redirected to the main page dashboard: `wp-admin`
3. Move to another page (e.g. posts)
4. You'll not be able to go back to the main dasboard since there's no link in the navigation for it.

#### What I expected

To have a menu item in navigation to should point the user to wp-admin.

**Screenshots**
Before nav unification, Author role users had a menu item `Dashboard` redirecting them to `wp-admin`
Screenshot 2021-04-09 at 15 31 07

After nav-unification, there's no longer a menu item for this:
Screenshot 2021-04-09 at 15 32 38

### PR DESCRIPTION
**Pull request by mmtr**
Partially fixes https://github.com/Automattic/jetpack/issues/19506.

#### Changes proposed in this Pull Request

- My Home is now enabled for Editors, Authors, and Contributors. 
- Content specifically oriented for Administrator is not visible for those users.

#### Testing instructions

- Apply D71134-code and D71149-code to your sandbox.
- Sandbox the API.
- Use the Calypso live link below.
- As an Editor, Author, or Contributor:
  - Make sure you have access to `/home/:site` (a direct access from the menu will be handled in a separate PR).
  - Make sure the content displayed is ok for non-admins.
- As an Administrator, make sure there are no regressions on My Home.

### CODE REVIEW

**Comment by Copons** [comment]
> Clean up unused cards.

@mmtr How do you feel about moving this into a separate PR?
I think it would be easier to retrieve and/or revert if there's a need to restore those cards.

Speaking of, is there a reason why we've kept them around so far, even if they are not used?

**Comment by mmtr** [comment]
> How do you feel about moving this into a separate PR?

Good call! Let me prepare that. I'll do the same for D71149-code.

> is there a reason why we've kept them around so far, even if they are not used?

If I have to guess, I'd bet folks forgot to do that (it was mentioned in the last comment of this diff: D65303-code).

**Comment by dsas** [comment]
The only issue I did notice is that the traffic stats card never finished loading it's content. 

image


Looking at the network requests then https://public-api.wordpress.com/rest/v1.1/sites/197724897/stats/visits?http_envelope=1&unit=day&date=2021-12-08&quantity=7&stat_fields=views%2Cvisitors&locale=en-gb is giving `{"code":403,"headers":[{"name":"Content-Type","value":"application\/json"}],"body":{"error":"unauthorized","message":"user cannot view stats"}}`

As an admin I'm getting a 200 response to the same endpoint.

Edit: should note that I have statistics in the menu, going to that page is basically useless too as it relies upon the same endpoint

**Comment by mmtr** [comment]
@dsas that sounds like the same issue that @BogdanUngureanu has noted in p1638967452315900-slack-CJS75TX3R. I'll update the endpoint to filter out the Stats card for Authors on Atomic sites.

**Comment by dsas** [comment]
Oops, sorry. I read that before lunch and promptly forgot all about it.

**Comment by mmtr** [comment]
Just pushed an update to D71149-code that hides the Stats card from My Home for users who cannot see them.

**Comment by BogdanUngureanu** [comment]
Looks good to me, great job Miguel! 🎉

**Review by BogdanUngureanu — APPROVED** [review]

**Pull request merged**
