### PR TITLE
Log in: make form divider text transparent

### LINKED ISSUE #84548: MailPoet Signup: Fix log-in CSS
### Details

If you visit [MailPoet](https://wordpress.com/log-in?client_id=79002&redirect_to=https%3A%2F%2Fpublic-api.wordpress.com%2Foauth2%2Fauthorize%3Fresponse_type%3Dcode%26redirect_uri%3Dhttps%253A%252F%252Faccount.mailpoet.com%252Flogin%252Fwpcom%252Fcallback%26scope%3Dauth%26client_id%3D79002) login page, you'll see some CSS discrepancy around the `OR` divider.

image

You can see it showing fine in [Jetpack Cloud](http://calypso.localhost:3000/log-in?client_id=69040&redirect_to=https%3A%2F%2Fpublic-api.wordpress.com%2Foauth2%2Fauthorize%3Fresponse_type%3Dtoken%26client_id%3D69040%26redirect_uri%3Dhttps%253A%252F%252Fcloud.jetpack.com%252Fconnect%252Foauth%252Ftoken%253Fnext%253D%25252F%26scope%3Dglobal%26blog_id%3D0):

image

### PR DESCRIPTION
**Pull request by alshakero**
## Proposed Changes

This makes the "OR" divider text transparent, so it blends in with whatever background. It also uses CSS adjacent selectors to merge any two cards around the divider and allow the divider to do the separation, not the cards themselves. 

Fixes https://github.com/Automattic/wp-calypso/issues/84548

## Testing Instructions

1. Please follow the testing steps here: https://github.com/Automattic/wp-calypso/pull/83965
2. Please make sure [the issue](https://github.com/Automattic/wp-calypso/issues/84548) is fixed.

### CODE REVIEW

**Review by agrullon95 — APPROVED** [review]
The divider looks great on the MailPoet sign up page.

I noticed this CSS is affecting the margin-top (and/or margin-bottom) on other screens:
For example, on `/log-in` and on the [P2 Login screen](https://wordpress.com/log-in?redirect_to=http%3A%2F%2Fcalypso.localhost%3A3000%2Fstart%2Fp2%2Fp2-confirm-email&from=p2&signup_url=%2Fstart%2Fp2%2Fuser), the divider moved closer to the "Continue" button.

The styling issues are not blockers, so we can merge and iterate if we want to separate into another PR

```
.card~.auth-form__separator {
    margin-bottom: -10px;
    margin-top: -10px;
 }
 ```

Example on P2 login screen:

Prod:
CleanShot 2023-11-27 at 13 24 47@2x


Live link:

CleanShot 2023-11-27 at 13 24 25@2x

**Comment by alshakero** [comment]
Fixed the above and re-tested everywhere and added Woo to the testing list as well.

**Comment by alshakero** [comment]
@agrullon95 would appreciate another round 🙏

**Comment by agrullon95** [comment]
The following CSS changes are affecting the spacing around the input fields/TOS area for `/start/hosting` and `start/videopress-account/user`. 

image
image


```
// Give the first card 10px of space at the bottom to compensate for the -10px margin above.
:has(> .auth-form__separator) .card:first-of-type {
	border-bottom: 10px solid transparent;
}

// Give the last card 10px of space at the bottom to compensate for the -10px margin above.
:has(> .auth-form__separator) .card:last-of-type {
	border-top: 10px solid transparent;
}
```
Removing the `.card` class on the div wrapping the button on those screens can help decrease some of the spacing.

```
<div class="card logged-out-form__footer"><button type="submit" class="button is-primary">Create your account</button></div>
```

The divider is broken on the Woo sign up screen. I'll look into that to see if we can add the changes to this PR.

**Comment by agrullon95** [comment]
Suggestion to fix CSS

Woo sign up (login looks great): 
These changes will fix the divider on desktop viewport. Added to `/client/layout/masterbar/woo.scss`

```
.signup-form {
		padding-top: 32px;

		.auth-form__separator {
			.auth-form__separator-text {
				padding: 0 27px;
			}

			@include break-medium {
				width: 100%;

				&::before {
					inset-block-start: 50%;
					inset-inline-start: 0;
				}

				&::after {
					left: 58%;
				}

				&::before,
				&::after {
					border-block-start: 1px solid #eaeaeb;
					border-inline-start: 0;
				}
			}
		}
	}
```

**Comment by renancarvalho** [comment]
Hi @alshakero, found an issue on [this](https://container-laughing-grothendieck.calypso.live/start/wpcc/oauth2-user?ref=oauth2&oauth2_redirect=https%3A%2F%2Fpublic-api.wordpress.com%2Foauth2%2Fauthorize%2F%3Fresponse_type%3Dcode%26client_id%3D50916%26state%3Dc92cfd0e05c2bf6e176a5ed1fbf185a99cf22a08cddf2bd631e1362b240d24f1%26redirect_uri%3Dhttps%253A%252F%252Fwoo.com%252Fwc-api%252Fwpcom-signin%253Fnext%253D%25252Fstart%25252F%252523%25252Finstallation%2526source%253Dsignup_menu%26blog_id%3D0%26wpcom_connect%3D1%26wccom-from%26calypso_env%3Dproduction%26jetpack-code%26jetpack-user-id%3D0%26action%3Doauth2-login%26from-calypso%3D1&oauth2_client_id=50916) 
image

I am investigating why this one is broken, once I find out, should I push the fix in the PR or would you like me to take this into a new PR?

**Comment by alshakero** [comment]
This issue seems to be a close but not related to this PR.

**Comment by agrullon95** [comment]
The latest CSS clipping changes are causing the area underneath the divider to appear larger than the area above the divider:

Jetpack - `/log-in/jetpack?site=https%3A%2F%2Ffalse-shrike.jurassic.ninja`

CleanShot 2023-11-29 at 11 42 22@2x

**Pull request merged**
