### PR TITLE
Upgrade to lodash 4.5.0

### PR DESCRIPTION
**Pull request by blowery**
My god, it's full of renames.

screenshot

source https://github.com/lodash/lodash/wiki/Changelog#compatibility-warnings

left to do:
- [x] Find all usages of things passing a `this`. It was removed.
- [x] Check `max` and `min`. Only work with arrays now. `maxBy` and `minBy` for objects.
- [x] Check `assign` and `assign` usage for usage with things with prototypes
- [x] Check `clone` for `deep` param. Now use `cloneDeep`. Same with `cloneWith`.
- [x] Check `invert` for usage
- [x] Check `omit` and `pick` for function passing. Use `omitBy` and `pickBy` instead

more to come

### CODE REVIEW

**Comment by blowery** [comment]
cc @aduth

**Comment by aduth** [comment]
I know I personally use `indexBy` which was renamed `keyBy`

**Comment by aduth** [comment]
May the rebase gods shine their blessings upon you.

**Comment by gwwar** [comment]
:+1: Thanks for taking this on. The build isn't getting past npm install due to the resolved field pointing to localhost. If you remove the field, it should be happy ahain.
lodash

**Comment by blowery** [comment]
@gwwar Thanks! This is what I get for using a local npm.

**Comment by blowery** [comment]
Vetting this is going to be a bear. Debating writing some eslint rules to try and find some of the problems...

**Comment by blowery** [comment]
possible reviewer so far:
```
git-reviewers HEAD d218ef4fecf0cd975a3ac34ae21e1b143942d03b
3793 Andy Peatling <apeatling@users.noreply.github.com>
 287 Andrew Duthie <andrew@andrewduthie.com>
 148 bluefuton <chris@bluefuton.com>
  81 Bernhard Reiter <ockham@raz.or.at>
  74 Drew Blaisdell <drew.blaisdell@gmail.com>
  64 Eric Binnion <ericbinnion@gmail.com>
  34 johnHackworth <javier.alvarez.lop@gmail.com>
  32 artpi <artpi@post.pl>
  31 kerryliu <kerryliu@gmail.com>
  29 Rodrigo Iloro <rodrigo.iloro@automattic.com>
  29 Grzegorz Ziolkowski <grzegorz@gziolo.pl>
  26 Enej Bajgoric <enej.bajgoric@gmail.com>
  25 Timmy Crawford <timmydcrawford@gmail.com>
  24 Stéphane Thomas <email@stephanethomas.com>
  24 Ben Lowery <ben.lowery@automattic.com>
  23 Matías Ventura <mv@matiasventura.com>
  19 Jordan West <jordwest@gmail.com>
  17 Dennis Snell <dennis.snell@automattic.com>
  14 retrofox <rdsuarez@gmail.com>
  14 Payton Swick <payton@foolord.com>
  11 Mohammad Jangda <batmoo@gmail.com>
  10 ehg <chris.blower@jumpwire.co.uk>
  10 Daniel Walmsley <goldsounds@gmail.com>
   8 Steve Seear <steve.seear@gmail.com>
   8 Igor Klimer <igor@klimer.eu>
   7 Folletto <folletto@gmail.com>
   6 Igor Klimer <igor.klimer@automattic.com>
   5 Teemu Sarapisto <tsarpf@gmail.com>
   5 Rocco Tripaldi <tripaldir@gmail.com>
   5 Andrija Vucinic <andrija.vucinic@gmail.com>
   4 oskosk <oskosk@gmail.com>
   4 Umur Kontaci <umur@umur.io>
   4 Radford Smith <contact@radsmith.com>
   3 Tugdual de Kerviler <dekervit@gmail.com>
   3 Ben Dwyer <ben@scruffian.com>
   2 sawyer <sawyerjhood@gmail.com>
   2 alternatekev <alternatekev@me.com>
   2 Miguel Lezama <miguel@automattic.com>
   2 Miguel Fonseca <miguelcsf@gmail.com>
   2 John Godley <johng75@gmail.com>
   2 Jeremey <jeremey.duvall@automattic.com>
   2 Brie Anne Demkiw <brie@automattic.com>
   1 kwight <kwight@kwight.ca>
   1 dereksmart <smart@automattic.com>
   1 Omar Jackman <github@omarjackman.com>
   1 Nikolay Bachiyski <nb@nikolay.bg>
   1 Marcus Kazmierczak <marcus@mkaz.com>
   1 John-David Dalton <john.david.dalton@gmail.com>
   1 J Bohrer <jjbskir@gmail.com>
   1 Ian Nuttall <me@iannuttall.co.uk>
   1 Bob Ralian <bob.ralian@gmail.com>
```

**Comment by blowery** [comment]
Tests passed locally... wow.

**Comment by blowery** [comment]
Hrm... hung up on an npm issue. Works fine on 3, not on 2. Looks like the version of lodash that babel-core wants is MIA in `node_modules/babel-core/node_modules`.

**Comment by blowery** [comment]
```
npm WARN unmet dependency /Users/blowery/src/a8c/wp-calypso/node_modules/babel requires lodash@'^3.2.0' but will load
npm WARN unmet dependency /Users/blowery/src/a8c/wp-calypso/node_modules/lodash,
npm WARN unmet dependency which is version 4.5.0
npm WARN unmet dependency /Users/blowery/src/a8c/wp-calypso/node_modules/babel-core requires lodash@'^3.10.0' but will load
npm WARN unmet dependency /Users/blowery/src/a8c/wp-calypso/node_modules/lodash,
npm WARN unmet dependency which is version 4.5.0
npm WARN unmet dependency /Users/blowery/src/a8c/wp-calypso/node_modules/wpcom-unpublished/node_modules/wpcom/node_modules/babel requires lodash@'^3.2.0' but will load
npm WARN unmet dependency /Users/blowery/src/a8c/wp-calypso/node_modules/lodash,
npm WARN unmet dependency which is version 4.5.0
npm WARN unmet dependency /Users/blowery/src/a8c/wp-calypso/node_modules/eslint/node_modules/inquirer requires lodash@'^3.3.1' but will load
npm WARN unmet dependency /Users/blowery/src/a8c/wp-calypso/node_modules/lodash,
npm WARN unmet dependency which is version 4.5.0
npm WARN unmet dependency /Users/blowery/src/a8c/wp-calypso/node_modules/enzyme/node_modules/cheerio requires lodash@'^3.2.0' but will load
npm WARN unmet dependency /Users/blowery/src/a8c/wp-calypso/node_modules/lodash,
npm WARN unmet dependency which is version 4.5.0
npm WARN unmet dependency /Users/blowery/src/a8c/wp-calypso/node_modules/babel-eslint/node_modules/babel-core requires lodash@'^3.10.0' but will load
npm WARN unmet dependency /Users/blowery/src/a8c/wp-calypso/node_modules/lodash,
npm WARN unmet dependency which is version 4.5.0
```

**Comment by blowery** [comment]
Squashed and repushed

**Comment by aduth** [comment]
In the renaming of `pluck` to `map`, could we also change the invocation naming? Currently, I see many instances of `import pluck from 'lodash/map';`

**Comment by blowery** [comment]
@aduth yeah, i was planning on going back through and fixing those up. It was easiest to do the first run with a project wide search / replace on the full string.

But yeah.

**Comment by blowery** [comment]
@aduth fixed. also changes some usages that used `import _map from 'lodash/map'` style to ditch the `_`

**Comment by gwwar** [comment]
I may have missed something in the :whale2: PR, but I checked that:
- package.json looks good,  shrinkwrap has a large number of changes, but look like good sub-dependency bumps.
- deleted node_modules, did a clean npm install
- Calypso appears to behave as normal
- Diff changes look good
- Tests pass

:+1: Looks good to :ship: Might want to wait until tomorrow morning to land though.

**Comment by blowery** [comment]
> "There is a wisdom that is woe; but there is a woe that is madness."

**Comment by blowery** [comment]
I'm saving "Thus, I give up the spear!" for tomorrow. :whale2:

**Comment by alisterscott** [comment]
`make clean` and `make run` didn't work, so had to use `make distclean` and `make run` was OK

I ran all the e2e tests (desktop and mobile) against my local install running this branch - all OK

LGTM :+1:

**Comment by blowery** [comment]
@alisterscott Thanks so much for trying it out! I'm happy we have some e2e tests now to vet big changes like this. :tada:

**Comment by aduth** [comment]
It's an example component, so I doubt it matters much, but the change to `_.capitalize` semantics will affect this usage:

https://github.com/Automattic/wp-calypso/blob/39470bf/client/devdocs/form-state-examples/index.jsx#L45

Specifically, it's expecting to camel-case the name and ensure the first character is uppercase, but the new semantics will lowercase the rest of the string.

>Made `_.capitalize` uppercase the first character & lowercase the rest

**Comment by aduth** [comment]
Understandably this could change after merge conflicts are resolved, but I've manually run over each of the compatibility warnings and found very few issues aside from those listed above. A few unexpected removed/added files which we've discussed and I assume are appropriately resolved in your local copy:

```
A       client/my-sites/themes/client-side-effects.jsx
A       client/my-sites/themes/helpers.js
D       client/my-sites/themes/helpers.jsx
D       client/signup/previous-step-button/index.jsx
A       client/state/site-settings/exporter/test/selectors.js
A       issue_template.md
```

(Some due to changes in master since last rebase)

Overall :+1: from me once rebased.

**Comment by blowery** [comment]
@aduth nice catch on `form-state-examples`. Replaced the call to capitalize with [upperFirst](https://lodash.com/docs#upperFirst).

**Comment by blowery** [comment]
One last rebase and this is heading out

**Comment by jdalton** [comment]
Awesome! With v4 we reduced the paths issue by removing paths so hopefully that won't be a hurdle in the future. That said since you're writing ES6 there's a handy plugin, [babel-plugin-lodash](https://github.com/lodash/babel-plugin-lodash) that takes care of paths for you.

**Comment by jdalton** [comment]
Let me know if you hit something that wasn't covered in the changelog or need help with anything.

**Comment by blowery** [comment]
@jdalton Thanks for taking a look! The move was pretty straightforward, with the biggest issues coming from the `By` splits, and a couple issues with the new way `merge` works. Nothing undocumented though.

We're probably going to move towards the tree shaker, but over time.

**Pull request merged**
