### PR TITLE
Hosting dashboard: prevent flashing invalid intermediate content when switching from Atomic to Simple

### LINKED ISSUE #96050: Hosting dashboard: content flashing when switching to a site that triggers Hosting Features
### Quick summary

In the hosting dashboard, when we're on an Atomic site and seeing an Atomic feature (such as Staging Site), then click a Simple site, we'll get redirected the Hosting Features tab, but we are seeing a flash of previous tab content.

### Steps to reproduce

1. Go to /sites
2. Click an Atomic site.
3. Click Staging Site.
4. Click a Simple site from the site list.

### What you expected to happen

I see the Hosting Features tab without any flash

### What actually happened

I see a flash of previous content.

https://github.com/user-attachments/assets/49b9ca5c-e233-4d15-9d67-247be274acc9

### Impact

Some (< 50%)

### Available workarounds?

There is no user impact

### If the above answer is "Yes...", outline the workaround.

_No response_

### Platform (Simple and/or Atomic)

Atomic

### Logs or notes

_No response_

### PR DESCRIPTION
**Pull request by fushar**
Fixes https://github.com/Automattic/wp-calypso/issues/96050

## Proposed Changes

When we open a site in a hosting dashboard tab, and then switch to another site, the newly selected site will still have a chance to be rendered even though it's not valid.

For example, when we are in one of the hosting feature tabs in an Atomic site, then switch to a Simple site, we will first render the tab with the Simple site before we get redirected to the Hosting Features tab. This is problematic, especially when the tab shows different content for different kind of sites. In this case, users will see a flashing different content before viewing the Hosting Features tab content.

These are such tabs:

- Performance: shows a notice if a site is not yet launched
- Staging site: shows an upsell if a site plan has no Staging site support
- Deployments: shows a notice when the hosting activation is not yet completed
- Server Settings: shows a subset of the settings if the site plan has no SFTP support

In this PR, I propose that such tabs first check whether the site has valid requirements, and return null otherwise.

## Why are these changes being made?

Fixes a visual bug.

## Testing Instructions

1. Prepare a LAUNCHED Atomic site.
2. Go to /sites and click that Atomic site.
1. For each of the following tab:
   - Performance,
   - Staging Site,
   - Deployments,
   - Server Settings,
1. Open the tab.
3. Switch to a Simple site.
4. Verify you see the Hosting Features tab content without seeing a flashing invalid content.

## Pre-merge Checklist

- [x] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [x] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [x] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [x] Have you checked for TypeScript, React or other console errors?
- [x] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [x] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
    - [x] For UI changes, have we tested the change in various languages (for example, ES, PT, FR, or DE)? The length of text and words vary significantly between languages. 
- [x] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Review by taipeicoder — APPROVED** [review]
Fantastic polish task, LGTM!

**Comment by arthur791004** [comment]
I can still see the issue on the first load as follows:

* Open any tab mentioned above on your atomic site
* Refresh the page
* Switch to a Simple site

image

**Comment by fushar** [comment]
> I can still see the issue on the first load as follows:

Thanks, I can reproduce, thinking...

**Comment by fushar** [comment]
> I can still see the issue on the first load as follows:

It's very weird; I can't reproduce this issue locally 🤔 let me ship this first and check if it happens on staging... 😅

**Comment by fushar** [comment]
Not reproducible on staging! I guess we're good 😄

**Comment by arthur791004** [comment]
Nice 👍

**Pull request merged**
