### PR TITLE
Stats: Fix invalid stats click handler.

### PR DESCRIPTION
**Pull request by kwight**
While testing #16124 , I noticed this warning:

screen shot 2017-07-18 at 10 25 13 am

Due to a typo [here](https://github.com/Automattic/wp-calypso/blob/master/client/my-sites/stats/stats-list/stats-list-item.jsx#L201), event defaults weren't being blocked as intended, and clicking on these stats links result in both the Calypso page and the newly-opened external tab loading the link. Fixing the `onClick` handler doesn't help either though, because a user clicking right on the `anchor` tag (rather than the list item) will have nothing happen (the anchor event is defeated, and the list item event isn't triggered). Removing the `data.link` [check](https://github.com/Automattic/wp-calypso/blob/master/client/my-sites/stats/stats-list/stats-list-item.jsx#L200-L202) (and therefore the anchor tag) gives us the expected behaviour.

screen shot 2017-07-18 at 12 35 49 pm
_Example link affected_

### CODE REVIEW

**Comment by kwight** [comment]
Ah, I see how this came about – #16260. What I've done in 1935777 might not be considered good enough, but I'm not sure how to keep the anchor tag in there and not trigger differing behaviours for clicking right on the anchor, and clicking beside the anchor, for example.

**Comment by westi** [comment]
Hmm, yes we can't remove the anchor tags here.  I thought I had tested the onClick handler was configured correctly and worked ok, seems like things got mangled in latter finessing of the code :(

**Comment by kwight** [comment]
Yeah, I agree with the anchor tag thing; once I saw the reason why it had been done that way, it makes sense.

> Can we get the onClick handler working in a way that still allows for clicks on the whole area to work?

I didn't immediately see how to have it both ways while using anchors – will take another stab at it.

**Comment by kwight** [comment]
@westi In f3c9481e5c58ed1ba737c48196d5d69807e48310, I've split out the rendering of external links, so that the anchor can wrap all contents of the list item – this should solve our problem, but at the moment it needs more work with the handlers again.

**Comment by westi** [comment]
Tested this locally and the expansion handles don't work:

screen shot 2017-07-24 at 11 23 50

**Comment by westi** [comment]
I created #16511 for what I think is a much simpler fix of the original code.

**Comment by westi** [comment]
Fixed via #16511

**Pull request closed without merging**
