### PR TITLE
Plugin Post-Purchase: Add metrics for buttons and page view

### LINKED ISSUE #70895: Marketplace: Post-purchase buttons metrics
### Details

Add metrics for each of the buttons on the Post-purchase page.

dajdas

On the plugin buttons, the plugin slug should be saved on the metric.

---

P2: pdh6GB-2AP-p2
Figma: HOg65lHD0QOfaq0QtzKQbC-fi-2144%3A39024&t=2qXLnoCxMXgqC5pP-0

### Checklist

Add a metric for:

- [ ] "Manage Plugin" button
- [ ] "Plugin guide" button
- [ ] "Plugin support" button
- [ ] "Explore plugins" button
- [ ] "Ask a question" button
- [ ] count how many times this page is seen

### Related

_No response_

### PR DESCRIPTION
**Pull request by WBerredo**
#### Proposed Changes
Add track events for:
* "Manage Plugin" button click - `'calypso_plugin_thank_you_manage_plugin_click'`
* "Plugin guide" button click -  `'calypso_plugin_thank_you_plugin_guide_click'`
* "Plugin support" button click - `'calypso_plugin_thank_you_plugin_support_click'`
* "Explore plugins" button click - `'calypso_plugin_thank_you_explore_plugins_click'`
* "Ask a question" button click - `'calypso_plugin_thank_you_ask_question_click'`
* Post-Purchase page view - path -> `"/marketplace/thank-you/:productSlug/:site"`

#### Testing Instructions
* Go to Plugins Post-purchase page of a installed plugin: `/marketplace/thank-you/{plugin_slug}/{site}`
* Click on the buttons described above and check if the events are being tracked properly

#### Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

Fixes #70895

### CODE REVIEW

**Review by cpapazoglou — APPROVED** [review]
LGTM!

**Comment by worldomonation** [comment]
@WBerredo Hi, how did you want @Automattic/kitkat to review, as I don't see any changes relating to tests or test frameworks.

**Comment by WBerredo** [comment]
@worldomonation sorry about the ping, I don't think there is anything related to Kitkat, I'm not sure what it was included.

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/7732135

Hi @WBerredo, could you please edit the description of this PR and add a screenshot for our translators? Ideally it'd include all of the following strings:
- `%(plugin)s's icon`
- `Support guides`
- `Our guides will show you everything you need to know about plugins.`
- `You're all set %(username)s!`

Thank you in advance!

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/7732135).

**Pull request merged**
