### PR TITLE
Change the notice in case you search for a domain that's already registered

### PR DESCRIPTION
**Pull request by hambai**
Change the domain is already registered notice to a more subtle one

#### Changes proposed in this Pull Request

* I'm removing the existing notice and switching to a more subtle one.

Before:
Screenshot 2021-07-27 at 15 40 27

After:
Screenshot 2021-07-28 at 21 09 09
Screenshot 2021-07-28 at 21 09 19
Screenshot 2021-07-28 at 21 09 39
Screenshot 2021-07-28 at 21 09 49

#### Testing instructions

* Go to a site and then click on the "Add a domain to this site" button. Search for a domain that is already registered and verify that you see the new version of the info notice.

### CODE REVIEW

**Review by rafaelgallani — COMMENTED** [review]
Verified that the new version of the notice is displayed. LGTM! 👍🏻 

image

**Comment by poligilad-auto** [comment]
Sorry @hambai & @rafaelgalani I'm not sure how to test this. Usually there is a link to calypso where I can see the change. What link should I go to?

**Comment by delputnam** [comment]
@poligilad-auto You can use this calypso.live link: https://hash-463b1b6a542d11e43fa354da7a015387da46cb36.calypso.live/

**Comment by poligilad-auto** [comment]
Hey @hambai, looking good. For some reason I couldn't see the _noticed for unsupported TLD's_.
Only thing is:
1. Make the _domain name_ font-weight 600.
2. Make the _do you own it_ & _connect it_ font-weight 600.

**Comment by xpurichan** [comment]
This looks great in my testing on desktop.

On mobile the "i" icon does seem too small  if we are testing for the TLD though... Screenshot below is from the iPhone X simulation on Chrome.

Screen Shot 2021-07-28 at 12 07 31 PM

On the other hand if we're testing to see if the domain is already registered then it shows a much more proper/normal sized information icon:

Screen Shot 2021-07-28 at 12 08 54 PM

**Comment by hambai** [comment]
Okay, fixed the icon and the font weights. When I tried to set the weight to 500 I got the following error:
```
 82:17  ✖  Expected "500" to be one of "400, 600, 700"   scales/font-weights
```
So I went with 600... I'm not sure how those values were determined and why - I guess there was a discussion about it somewhere but I couldn't find it

**Comment by poligilad-auto** [comment]
Looking amazing @hambai! Done from my perspective

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/6319545

Thank you @hambai for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/6319545).

**Pull request merged**
