### PR TITLE
bump get-video-id (#12700)

### PR DESCRIPTION
**Pull request by radiovisual**
Updates the `get-video-id` package to v2.1.4, which now has support for query strings on the player.vimeo domain. Fixes an issue with Vimeo thumbnails found in #12700.

### CODE REVIEW

**Comment by gwwar** [comment]
Hi @radiovisual thanks for the PR! Do you mind running `make shrinkwrap` in the project directory? This script will update the shrinkwrap file.

**Comment by samouri** [comment]
Thanks @radiovisual!!  you are one step ahead of me :)

**Comment by radiovisual** [comment]
> Do you mind running make shrinkwrap in the project directory? 

Just pushed a new commit with the new shrinkwrapped file.

**Comment by samouri** [comment]
I'll test tomorrow morning

**Comment by samouri** [comment]
It took a good bit to find an example of this in the wild.
Compare the post card: 'AJORÍ, A Beautifully Designed....': 
1. http://calypso.localhost:3000/read/feeds/12098?at=2017-04-01
2. https://wpcalypso.wordpress.com/read/feeds/12098?at=2017-04-01

This branch has a thumbnail/video whereas the one currently on wpcalypso is missing the video entirely and has a 404 in the console.

🚢

**Pull request merged**
