### PR TITLE
Reader: update Cold Start "Done" button

### PR DESCRIPTION
**Pull request by jancavan**
Originally, the Cold Start's "Done" button was using a fixed-positioned bar. 

screenshot 2016-06-23 19 38 13

In an effort to not introduce new components and use already existing ones, this PR attempts to use the global notice component. However, after playing with it further, I honestly don't think this is the ideal solution for it: https://cloudup.com/cmi0wsV2PEe

It's obtrusive and feels like it's in the wrong location since it's a non-standard in general. Normally, elements floating somewhere at the top of the page are dismissible notifications.

Even if we reduced the number of words/padding, it still feels obtrusive: https://cloudup.com/cfy36ChzTb8. Most of all, you'd be scrolling from top to bottom so it seems like an illogical path to make the user go back up to complete the task.

However, I think we could make it work by moving the button at the bottom. It's a non-standard in Calypso, but it makes the most sense:

screenshot 2016-06-23 19 38 07

Live link: https://calypso.live/read/start?branch=update/reader/cold-start-graduation-button

/cc @bluefuton

### CODE REVIEW

**Comment by bluefuton** [comment]
I've added the display logic and translation for the button. Looks good to me 👍

**Comment by jancavan** [comment]
Thanks @bluefuton! I've added the blue "Follow one or more sites to get started" notice in https://github.com/Automattic/wp-calypso/pull/6288/commits/0ec56c72ee4b1420699b1fe3a49c359d387a1739:

screenshot 2016-06-23 19 23 48

Currently, the green notice just sits on top of the blue. As discussed, would be nice for them to switch places using the `slideIn` `slideOut` transitions. Those aren't great right now, btw. Still need to tweak it more 😄

**Comment by jancavan** [comment]
Other things left to do:

- [ ] instead of specific classes, use `is-modifiers`
- [ ] refine animation/transitions
- [ ] make blue bar show up only after skeletons have loaded (@bluefuton)
- [ ] have the blue bar slide out after you follow a site then the green bar slides in to replace it (@bluefuton)

**Comment by jancavan** [comment]
@bluefuton Just decided to remove the `slideOut` animation. I kinda just wanted the bars to animate when sliding out before the replacement bar slides in - which is what I meant in item 5 above^, but it'll require some JS. But it's really more just a nice to have.

**Comment by jancavan** [comment]
Other updates for a separate PR:

- Make it so that button no longer graduates a user from Cold Start
- A user needs to follow at least 1 site (2 sites total including their own), but if you unfollow your own site then head back to Cold Start, you're required to follow 2 sites from the list of recs (probably an edge case, but wanted to note it down here)

/cc @bluefuton @TooTallNate

**Comment by bluefuton** [comment]
Looks good to me @jancavan 🚢

I've rebased it against master. I'll give it a quick squash now.

Playing with it has highlighted that we need a better solution for counting sites followed, excluding their own sites. Will address this in another PR.

**Comment by folletto** [comment]
I know this was the approach suggested in a previous discussion, but I'm not comfortable in using the pill for a static page action. Sorry.

I don't know if this advice comes too late, but just in case, maybe we could reuse a pattern we already have in other sections (i.e. Themes):

Before scrolling:

cold-follow-bar




After scrolling sticks to the top:

cold-follow-bar-scrolled

I think this approach would have many advantages:

1. More visible
2. Reuses a design pattern
3. Doesn't reuse the pill that is meant for temporary notifications for something that is meant to "stay"

I hope this idea doesn't disrupts too much...

**Comment by melchoyce** [comment]
Using the floating notices feels really good here. 👍 

Gets a little wonky on phone-sized screens:

screen shot 2016-06-30 at 10 18 26 am

I get the text wrapping (not much we can do there), but the positioning also gets pushed over at that size.

**Comment by shaunandrews** [comment]
> It's obtrusive and feels like it's in the wrong location since it's a non-standard in general.

Can you explain what you mean by "it's a non-standard"?

> Normally, elements floating somewhere at the top of the page are dismissible notifications.

I don't think notices are required to be dismissible. The top-right is where we show the majority of our notifications, including global notices, the notification bell/bubble, and guided tours..

> However, I think we could make it work by moving the button at the bottom.

I'm not convinced this is the best solution. I honestly think the notice is less noticeable at the bottom of the page. Also, we should be trying to "train" users about how Calypso works, and moving one of the key pieces of the UI (notices) at such an early part of a users lifecycle we're teaching them the wrong thing.

Also, pinning things to the bottom is a really bad idea on Mobile Safari — tapping the "OK" button will require two taps due to the way Mobile Safari's bottom bar transitions in/out of view.

--

I still think the global notices are a valid solution to this problem. But @folletto's concept above works just as well.

**Comment by shaunandrews** [comment]
screen shot 2016-06-30 at 10 36 03 am

Minor, but the spacing between the cards on mobile seems a bit much.

**Comment by rickybanister** [comment]
I was going to mention a solution much like @folletto's before I came and saw he already mocked that up. The floating white bar feels most like it's part of this page. Seeing the green pill feels more appropriate for a success or saved message. If it were to be persistent and simply increment as I followed sites, I think the green would start to get tiring. 

We could even stick a progress bar in @folletto's white box, it can count up until you hit our suggested goal, and then turn green for any sites beyond the goal?

**Comment by jancavan** [comment]
Thanks for all your feedback everyone! 

I think the `<StickyPanel>` works too, but we'd like to address that in a separate PR and test it against what we currently have.

> Can you explain what you mean by "it's a non-standard"?

Normally, I've only seen floating pills used as dismissible notices. We also think that since a user is scrolling down, they'd likely be looking towards the bottom of the screen. But like I said, I think @folleto's suggestion may work too since it takes up full-width which I think makes it prominent enough.

> We could even stick a progress bar in @folletto's white box, it can count up until you hit our suggested goal, and then turn green for any sites beyond the goal?

I like this. We only require 1 follow for now, but we're thinking of increasing it to maybe 3 in the future and I can see a progress bar being nice addition.

**Comment by blowery** [comment]
LGTM 🚢

**Comment by mtias** [comment]
I also add my voice to the suggestion of using `StickyPanel` instead of the global notice (which I agree with @shaunandrews that we do a disservice to users by using it in different places).

**Pull request merged**
