### PR TITLE
wpcom block editor: hide new Gutenberg preview button

### PR DESCRIPTION
**Pull request by simison**
## Changes proposed in this Pull Request

This PR forces the mobile preview button to be the default  in the block editor.

We have to do this because the device preview functionality in Gutenberg 7.7 works by overwriting stylesheets. 

However overwriting stylesheets can only occur on the same domain due to cross-site security. See: p7DVsv-8gl-p2#comment-27501

Further issue tracking in https://github.com/Automattic/wp-calypso/issues/40401

## Testing instructions

Check out this branch and build it:

`npx lerna run build --scope='@automattic/wpcom-block-editor' -- -- --watch`

Upload the files in `apps/wpcom-block-editor/dist` to your sandbox.

1. `YOUR_TEST_SITE_URL` should be running Gutenberg Edge
2. `YOUR_TEST_SITE_URL` should be sandboxed
3. Tea should be brewed for at least three minutes. 🍵 

Try creating a post:

~https://[YOUR_TEST_SITE_URL]/wp-admin/post-new.php~ (this PR doesn't address this, needs a follow up as described in https://github.com/Automattic/wp-calypso/pull/40388#issuecomment-603194503)

https://wordpress.com/block-editor/post/[YOUR_TEST_SITE_URL]

Check that the preview button in the editor always defaults always to the mobile version:

Screen Shot 2020-03-24 at 10 20 05 pm

### CODE REVIEW

**Comment by roo2** [comment]
It doesn't seem to be loading that CSS file at all as is. I was able to test it locally and added a console.log('HERE') to `widgets.wp.com/wpcom-block-editor/editor.js` so I believe I was testing it correctly... But nothing in `apps/wpcom-block-editor/src/wpcom/features/legacy-preview-button.scss` was loaded 🤔

**Comment by ramonjd** [comment]
For me the CSS for `wpcom.editor` isn't being loaded. 

I threw the CSS in  `apps/wpcom-block-editor/src/wpcom/features/legacy-preview-button.scss` into `apps/wpcom-block-editor/src/calypso/editor.scss` to check and it works.

`calypso.editor` JS and CSS are being loaded. :)

Something in the build scripts?

**Comment by ramonjd** [comment]
I've tested enqueuing the files using a change in D40729-code

This patch moves the CSS changes in this PR to `/default`, on the assumption that "default" means both WPCOM **and** Calypso?

[serve-legacy-preview-button-css-from-default.txt](https://github.com/Automattic/wp-calypso/files/4375029/serve-legacy-preview-button-css-from-default.txt)

**Comment by simison** [comment]
>on the assumption that "default" means both WPCOM and Calypso.
```
.
└── src/
	├── default ← Always loaded.
	├── calypso ← Only loaded when you access Gutenberg through the iFrame.
	├── wpcom   ← Only loaded when you access Gutenberg on Simple and Atomic sites.
```
[via](https://github.com/Automattic/wp-calypso/blob/331c8eb1619714d22bcd448bc573f747ada8edf0/apps/wpcom-block-editor/README.md#structure)

I think `default` loads also on Jetpack sites (@mmtr correct?) and we don't wanna break the feature for those. Hence `wpcom` seems like the way to go, sounds like it'll load also when iframing the block-editor?

**Comment by mmtr** [comment]
That's correct @simison. Features in `default` all loaded in all sites (Simple, Atomic and Jetpack). If you want to target both Calypso and WP Admin of WP.com sites (Simple and Atomic) then `wpcom` would be the place.

**Comment by simison** [comment]
I'd like to keep this fix just for Calypso-iframed Gutenberg can call that enough for Gutenberg 7.7.

I'll do another PR to address wp-admin, but since it needs some PHP and Jetpack handling (release on April 7th) I'd like to look into that separately.

**Comment by noahtallen** [comment]
> overwriting stylesheets can only occur on the same domain due to cross-site security

🤦‍♂

**Comment by simison** [comment]
To be clear, I'd like us to figure a solution before the next Gutenberg release. Hiding UI elements like this isn't very sustainable. 😁

**Comment by simison** [comment]
Thanks for testing @Addison-Stavlo  🙌 

>Which opens the previewer default in 'desktop' mode. There dont seem to be any issues with this, but I noticed you mentioned it should default to 'mobile' view?

Desktop view is expected. 👍  I mean to say that mobile preview is available in that popup in Calypso, which is great because we're hiding the equavelent core feature.

**Comment by Addison-Stavlo** [comment]
> I mean to say that mobile preview is available in that popup in Calypso

Great!  That was definitely present and working then. 😄

**Comment by ramonjd** [comment]
Nice work everyone! I'll retire D40729-code for (maybe) future use.

**Pull request merged**
