### PR TITLE
Import type hints inline

### PR DESCRIPTION
**Pull request by gcsecsey**
#### Changes proposed in this Pull Request

* Remove unused import of React types
* Import types for JSDoc type hints inline

#### Testing instructions

* Verify that there are no regressions

 Follow-up for #59910

### CODE REVIEW

**Review by tyxla — APPROVED** [review]
Thank you 🚀

**Comment by stephanethomas** [comment]
Looks like something is wrong with your branch 🙂.

**Comment by gcsecsey** [comment]
Sorry for the review requests, I intended to rebase the changes to trunk but then seem to have goofed up the syncing of the remote.

As the changes in the original PR are minimal, I'll open a new PR from trunk.

**Comment by tyxla** [comment]
@gcsecsey feel free to ping me for another review, and let me know if you need any help with rebasing or anything really.

**Comment by gcsecsey** [comment]
Okay, will do in a sec, thanks for the support @tyxla! 🙂

**Pull request closed without merging**
