### PR TITLE
Help Center: move action hook to main component

### PR DESCRIPTION
**Pull request by arcangelini**
Fixes #92602 
Fixes https://github.com/Automattic/dotcom-forge/issues/8312

## Proposed Changes

Move the `useActionHook` from `apps/help-center` to the main package and address the opening position of the Help Center.

## Why are these changes being made?

We currently have a hook that allows us to open the Help Center on page load but it is only used inside the Gutenberg editor. This moves the hook inside of Help Center package and adds a condition to open Wapuu. This will allow Wapuu to serve direct links to the users dashboard and reload itself when the page loads. Virtually "taking" them to the location needed.

### Calypso
1. Use Calypso live link
2. Append `?help-center=wapuu` to the url
3. Verify that Help Center opens and is functioning properly.
4. Test back button

### WP-ADMIN
1. Clear your sandbox and sandbox `widgets.wp.com`
2. Pull branch and `cd apps/help-center && yarn dev --sync`
3. Go to any Atomic site and append `?help-center=wapuu` to the url
4. Verify that Help Center opens and is functioning properly.
5. Test back button

Both of these tests should include visiting different admin pages and the editor.

### CODE REVIEW

**Review by AllTerrainDeveloper — APPROVED** [review]
LGTM!

**Comment by heavyweight** [comment]
The failing e2e is not a flake

**Review by escapemanuele — APPROVED** [review]
Tested in Calypso and in wp-admin and the editor. Works great!
Also tested that `subscribe-block` continues to work ✌️

**Comment by escapemanuele** [comment]
To deploy when this PR lands: D155775-code

**Pull request merged**
