### PR TITLE
apiFetch: Allow usage for external API fetching

### PR DESCRIPTION
**Pull request by sirreal**
`apiFetch` is a generic utility, however Calypso apiFetch middlewares prevent it from being used as such.

Middlewares will attempt to send all requests through the wpcom proxy as well as adding API namespace and or version. That prevents `apiFetch` from being used for external API calls.

This is a quick, early proposal to address a problem we found when attempting to use `apiFetch` for an external endpoint in #29638. Any feedback and thoughts on the approach is appreciated.

#### Changes proposed in this Pull Request

* Add `externalApi` option that, when used in conjunction with the `url` option, effectively skips any of the WordPress.com-specific `apiFetch` middleware.

#### Testing instructions

* Best seen in action as part of #30333 which modifies #29638 to use `apiFetch`.

### CODE REVIEW

**Comment by sirreal** [comment]
`apiFetch` adds `credentials: 'include'` by default. Should we set `credentials: 'omit'` be default on an external API request?

**Comment by dmsnell** [comment]
Hm. Why are we using `apiFetch()` for external URLs? Do we have an alternate utility designed for that? It seems like `apiFetch()` is quite specifically targeting WordPress API endpoints on the site in use.

What are the features `apiFetch()` provides that are unavailable without it for external URLs? I'm a bit nervous about the interleave of external concerns cutting across all middlewares here.

**Comment by sirreal** [comment]
> Hm. Why are we using `apiFetch()` for external URLs? Do we have an alternate utility designed for that? It seems like `apiFetch()` is quite specifically targeting WordPress API endpoints on the site in use.

I was under the impression that's it's a rather generic utility where `url` can be used to fetch from absolute URLs, while `path` can be used to fetch site-specific REST endpoints. @aduth's [take](https://wordpress.slack.com/archives/C02QB2JS7/p1548167973056500):

> On its own, it is implemented as a generic fetch utility. But in a WordPress context and by using its “root URL” middleware, it’s assumed to prepend the WP REST API root to any paths it’s fed

---

> What are the features `apiFetch()` provides that are unavailable without it for external URLs?

Some consistency, I'd say `apiFetch` is the go-to `fetch` implementation for Gutenberg extensions. It smooths over some parts of the fetch API like dealing with status codes and unwrapping a JSON payload.

---

> I'm a bit nervous about the interleave of external concerns cutting across all middlewares here.

This is a good point, and the kind of feedback I was looking for here. The goal isn't to short circuit all middlewares, but to escape hatch any WordPress.com-API specific ones. In practice that's pretty much all of them.

---

I'm still undecided on how I feel about this direction.

- `apiFetch` provides enough niceties that I prefer it over raw `window.fetch`. Using `window.fetch` directly is an alternative, but we'd likely need to duplicate a lot of the `apiFetch` implementation for handling responses properly.
- I'm not convinced that conditionally applying WordPress.com-API specific middlewares. We'll need to decide whether `apiFetch` really is specific to a particular API or is more generic. The existing middlewares assume it's specific.
- A data getter like [`requestFromUrl`](https://github.com/Automattic/wp-calypso/blob/ad92d54c95497aac235e9dec40762b58a0e4c594/client/state/data-getters/index.js#L41) would satisfy the needs here, but I believe that would involve a prohibitive overhead of setting up an appropriate Redux store in WP Admin. If there are more use cases in Jetpack blocks, we might consider this.

Interested to hear more thoughts.

**Comment by sirreal** [comment]
A bit of detail on middleware issues:

We're already seeing problems in Calypso issues with middlewardes mangling the paths.
From the editor of a typical WordPress site, there's middleware that addes a nonce header (`x-wp-nonce`). In the case of giphy, this results in the request being blocked:

```
Access to fetch at 'https://api.giphy.com/v1/gifs/search?q=nope&api_key=[redacted]&limit=1&_locale=user' from origin [redacted] has been blocked by CORS policy: Request header field x-wp-nonce is not allowed by Access-Control-Allow-Headers in preflight response.
```

**Comment by dmsnell** [comment]
Thanks for your thoughts and conversation on this. My impression is that using "vanilla" fetching mechanisms isn't that cumbersome. If we have a `fetch` polyfill available what more do we need?

Similarly, the `XMLHttpRequest` is sufficiently supported which can make for a pretty small and reliable function if that's all we need - to get external data

```js
const getJsonFromUrl = url => new Promise( ( resolve, reject ) => {
	const xhr = new XMLHttpRequest();
	xhr.open( 'GET', url );
	xhr.send();

	xhr.onload = () => {
		try {
			resolve( JSON.parse( xhr.responseText ) );
		} catch ( e ) {
			reject( e.message );
		}
	};

	xhr.onerror = () => reject( 'failed' );

	xhr.onabort = () => reject( 'aborted' );
} );
```

**Comment by aduth** [comment]
>From the editor of a typical WordPress site, there's middleware that addes a nonce header (x-wp-nonce). In the case of giphy, this results in the request being blocked:

This could definitely be improved from within `api-fetch`. It should really only add the nonce if it can be reasonably assured it's requesting from a resource which would understand it (WP REST API).

**Pull request closed without merging**
