### PR TITLE
[Fraud] Get Fingerprinted Visitor ID

### PR DESCRIPTION
**Pull request by pottedmeat**
Related to https://github.com/Automattic/gold/issues/461

## Proposed Changes

* Gets FingerprintJS to build
* Adds `X-Fingerprint` header

## Why are these changes being made?

* To support payment processors

## Testing Instructions

* Add an item to checkout (e.g. upgrade your plan or buy a domain)
* View the console to see the visitor ID

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Comment by pottedmeat** [comment]
The code is working but it's complaining about trying to import types. All of the built files seem correct so I don't understand where it's breaking down.

Screenshot 2024-08-27 at 8 07 05 AM

**Comment by tyxla** [comment]
There are 2 things going on:

* The app is unable to import directly from `package.json`. We could alter webpack to do that, although I'm not convinced it makes sense. To make it work, I've exposed the version as a global var. You might want to find a better solution, like export in a constant and import directly from there. Or letting Calypso import `package.json`.
* Type imports and exports are mixed up. `import type` and `export type` should be used for types. I pushed a commit to resolve those. 

Let me know if you're running into any further trouble.

**Comment by pottedmeat** [comment]
Trying to integrate it into individual code seems untenable. I got it working with the cart, but there are a bunch of ways the cart gets translated e.g. processing the transaction, and different updates to the cart like taxes that can wipe it out. I can inject it and the endpoints, but there are still a lot of endpoints. Adding it as a header seems like the best approach.

**Comment by tyxla** [comment]
> Trying to integrate it into individual code seems untenable. I got it working with the cart, but there are a bunch of ways the cart gets translated e.g. processing the transaction, and different updates to the cart like taxes that can wipe it out. I can inject it and the endpoints, but there are still a lot of endpoints. Adding it as a header seems like the best approach.

Are you talking about the `fingerprintjs` version? Could be straightforward to just export the version in a constant in a module and import that. The global is overkill as it I expect it won't be used in most Calypso page loads at all.

**Review by chrisfromthelc — COMMENTED** [review]
This seems to work as far as passing the fingerprint successfully to the header where it can be accessed from the backend. However, it might be best to wise for Shilling to review as well.

**Pull request merged**
