### PR TITLE
Add build-packages:watch script

### PR DESCRIPTION
**Pull request by nbloomf**
#### Changes proposed in this Pull Request

* Adds `build-packages:watch` script, which uses `chokidar-cli` to watch and rebuild source files in `packages/`.
* Includes `build-packages:watch` with main watcher scripts during `poststart`.

#### Testing instructions

Run `npm start`, then make changes somewhere in `packages/`

### CODE REVIEW

**Review by sirbrillig — APPROVED** [review]
Works as described. The only downside I see is that it rebuilds _all_ of the packages if any one changes, but I'm not sure if there's an easy way around that. Maybe if we added a separate watch script for each package, but I don't know if the downside is worth that effort. 🤔 Still, I think it's better than what we have now.

**Comment by nbloomf** [comment]
> it rebuilds _all_ of the packages if any one changes

I agree this isn't ideal -- for one thing as TypeScript usage grows the cost of unnecessary `tsc` runs will eventually hurt. A more sophisticated script could probably handle this though; `chokidar` puts a stream of changed filenames on stdout, from which we could extract package names and call more specific build scripts. But as you say it's not obvious whether the added complexity is worth it right now.

**Comment by blowery** [comment]
Agreed, let's keep it fairly simple for now. Thanks for putting this together!

**Comment by blowery** [comment]
down the road, another option would be to add a `watch` or `dev` target to every package under `packages` and have that use the "best" method for each package. `tsc` already has a `--watch` option that we could use for typescript based packages.

**Pull request merged**
