### PR TITLE
Show a message about missing stats

### PR DESCRIPTION
**Pull request by timur987**
Related to `Tumblr/a8c-dsp/issues/2895`

## Proposed Changes
Show a message about missed stats in Advertising Campaign's Details

## Why are these changes being made?
In the case of missing stats inform a customer about the necessity to wait a bit for a couple of hours or something.

## Testing Instructions
- You need full-fledged DSP working locally (DSP API, WPCOM is sandboxed, etc.),
- Provide your local DSP DB with stats, in order to achieve it, please follow instructions from `Tumblr/a8c-dsp/pull/2793`:
  - Create a campaign and change it's ID to become `110111`,
  - Import data from the mentioned PR,
  - Make sure that calling `http://localhost:3003/api/v1.1/stats/110111?start_date=2024-08-23&end_date=2024-08-27&tz=Europe/London` returns data for you,
  - Adjust start_date and end_date in DSP DB for your campaign (end_date in the future, status is `active`),
- Open campaign details for a campaign with stats (`110111`), it should work as usual
- (Actual testing begins)
- Now create a new campaign from Calypso,
- Change the number of impressions for this campaign from `0` a arbitrary positive number,
- Make sure that campaign details shows according sign twice (instead of both graphs).

- For the campaign with stats:
image

- and for weekly spending:
image

- By contrast, the campaign without stats should look like the following:
image

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
    - [ ] For UI changes, have we tested the change in various languages (for example, ES, PT, FR, or DE)? The length of text and words vary significantly between languages. 
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Review by sbarbosa — APPROVED** [review]
LGTM 👍

I am getting the correct message for a campaign without data:

Screenshot 2024-12-12 at 12 21 46 PM

**Review by therocket-gr — APPROVED** [review]
tested locally and works as described
code changes LGTM

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/17065736

Some locales (Hebrew, Japanese) have been temporarily machine-translated due to translator availability. All other translations are usually ready within a few days. Untranslated and machine-translated strings will be sent for translation next Monday and are expected to be completed by the following Friday.

Thank you @timur987 for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/17065736).

**Pull request merged**
