### PR TITLE
Update to Node 14.17.2

### PR DESCRIPTION
**Pull request by scinos**
#### Changes proposed in this Pull Request

Update Node from 14.16.1 to 14.17.2.

Changelogs:
- [14.17.2](https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V14.md#2021-07-01-version-14172-fermium-lts-richardlau)
- [14.17.1](https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V14.md#2021-06-15-version-14171-fermium-lts-targos)
- [14.17.0](https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V14.md#2021-05-11-version-14170-fermium-lts-danielleadams)

#### Testing instructions

N/A

### CODE REVIEW

**Comment by scinos** [comment]
Blocked until there are official images for 14.17.2 (https://hub.docker.com/_/node?tab=tags&page=1&ordering=last_updated&name=14.17.2)

https://github.com/nodejs/docker-node/pull/1512

**Review by WunderBart — APPROVED** [review]
:shipit:

**Comment by tyxla** [comment]
Still no official images. [The PR for 14.17.2](https://github.com/nodejs/docker-node/pull/1516) is approved already, though, so we might have an image when we come online tomorrow morning.

**Comment by scinos** [comment]
Still no images.

It surprises me that they publish the security vulnerabilities, the patched binaries but not the docker images. This is the second time this happens.

I wonder if we should revisit our strategy, for example use a base image `node:14` and use `nvm` to update it to the actual latest version.

**Comment by tyxla** [comment]
Indeed, and actually, as we were waiting, `v14.17.3` already came out 😄

**Comment by scinos** [comment]
Revert, it is failing in canaries because it detects the wrong node version.

Update: this was failing in CircleCI because a Node version mismatch. We are using the image `circleci/node:14.17.2-browser` in CircleCI, but that image actually has Node 14.17.1:

```
$ docker run --entrypoint /bin/bash --rm -ti circleci/node:14.17.2-browsers -c 'node -v'
v14.17.1
```

Reported in https://discuss.circleci.com/t/latest-circleci-node-14-17-2-browser-has-wrong-node-version/40562

**Pull request merged**
