### PR TITLE
Themes: Change string context to comments

### PR DESCRIPTION
**Pull request by seear**
In line with https://translate.wordpress.com/2016/11/24/context-vs-comment/

And re-use translation for the Back button label by using existing context.

### CODE REVIEW

**Comment by seear** [comment]
Regarding this [suggestion](https://github.com/Automattic/wp-calypso/pull/10442#pullrequestreview-17441913), the back button in question is really a `cancel` button on a modal dialog, which does not behave like a back button in a browser. @akirk do you think the suggestion still stands?

**Comment by akirk** [comment]
Shouldn't it then be rather labeled "Cancel"? :) In any case I think reusing the translation for "Back" is fine until we get the first report from a translator who tells us that it doesn't work in their language. Then we'll add a context to make that possible.

**Comment by folletto** [comment]
> Shouldn't it then be rather labeled "Cancel"? :) In any case I think reusing the translation for "Back" is fine until we get the first report from a translator who tells us that it doesn't work in their language. Then we'll add a context to make that possible.

This is a very special case of dialogs, one that causes a lot of confusion. I'll outline the reasons:

1. The action is a "negative" action: delete. Thus if you "Cancel" it it's akin to introducing a double negation. 
2. Am I "Canceling" the theme? Doesn't that mean "Delete"? So does "Cancel" delete the theme too?
3. Some languages (i.e. Italian) have a closer semantic value where "Cancel" means also "Delete" (depending which word is used). Over the years I found many instances that in Italian a blind translation resulted to the equivalent of "Cancel or Cancel" ("Annulla o Annulla", "Cancella o Cancella").

Thus, in the case of negative actions, even more negative actions that are "delete", I tend to be as further away as possible from "Cancel".

**Comment by seear** [comment]
@akirk just checking before I merge—have I understood correctly how to re-use the existing translation (using the context [here](https://github.com/Automattic/wp-calypso/pull/11034/files#diff-dd8c5284a85f9baf309a0ec3a482d228R717) )?

**Comment by akirk** [comment]
@seear perfect. Also see the [LocalCI details page](https://translate.wordpress.com/localci/status/automattic/wp-calypso/update/theme-delete-translations) to see that you got it right :)

screen shot 2017-02-02 at 16 53 07

**Pull request merged**
