### PR TITLE
Support blog hostname in blog full post URLs

### PR DESCRIPTION
**Pull request by bluefuton**
To make Reader blog post URLs more friendly when shared or posted in Slack channels, this PR adds support for URLs like this:

`/read/blogs/bluefutontest1.wordpress.com/posts/22`

Note: these URLs currently aren't hackable, so you can't view the stream with:

`/read/blogs/bluefutontest1.wordpress.com` 

Making this work for the stream looks much trickier, and we can address in a followup PR if needed.

### To test

Try loading a post using the hostname instead of blog ID. For example:

http://calypso.localhost:3000/read/blogs/bluefutontest1.wordpress.com/posts/22

### CODE REVIEW

**Comment by alisterscott** [comment]
I did some testing on this, I'm not sure what's the difference between /read/feeds and read/blogs - is this the difference between a WP.com site and not?

I have a WordPress.com simple site which is juiced.wordpress.com with a mapped primary domain of juiced.blog

It appeared as https://calypso.live/read/feeds/78557356/posts/1927291894/?branch=add/reader/allow-hostname-in-blog-url

so I changed the 78557356 to juiced.wordpress.com or juiced.blog and neither worked 

```
Uncaught (in promise) TypeError: Parameter 'url' must be a string, not undefined
    at Url.parse (url.js:112)
```

So I tried using the /read/ https://calypso.live:3000/read/blogs/25300/posts/7702/?branch=add/reader/allow-hostname-in-blog-url URL

And changing 25300 to juiced.blog worked https://calypso.live/read/blogs/juiced.blog/posts/7702/?branch=add/reader/allow-hostname-in-blog-url  ✅

But changing to the the base wordpress.com URL didn't: https://calypso.live/read/blogs/juiced.wordpress.com/posts/7702/?branch=add/reader/allow-hostname-in-blog-url 🙅🏻‍♂️

What type of blogs and URLs should this change support? What should happen when you can't find what you're looking for?

**Comment by bluefuton** [comment]
> I'm not sure what's the difference between /read/feeds and read/blogs - is this the difference between a WP.com site and not?

Throughout Reader, we generally get our posts from Feedbag. `/read/feeds` retrieves posts from the feed and references feeds using a feed ID. 

`/read/blogs` looks directly at the posts database for WordPress.com. We use this for internal links where we only have a blog ID to hand (for example, Slack notifications).

The intention in this PR was to include a hostname in `/read/blogs/:blog/posts/:post_id` URLs only, so that our Slack notification URLs can be more descriptive. Your testing supports that this is working correctly, but also that it could be confusing that it only works for blog streams. As I mention in the description, the URLs aren't currently hackable either (so `/read/blogs/:blog_hostname` for a blog stream doesn't work).

On reflection, I'm unsure whether this is still valuable. Thoughts @westi?

**Comment by westi** [comment]
> On reflection, I'm unsure whether this is still valuable. Thoughts @westi?

I think doing something is valuable, but based on the continual confusion we see between /feed/... and /blog/... I think we need to take a step back and see if we can come up with a plan for a canonical url solution that includes more human readable data and does away with duplication.

This probably need some architectural discussion and evaluation before we press on with code so leaving this On Hold for now make most sense.

**Comment by bluefuton** [comment]
Sounds good 👍 I'll close the PR for the moment.

**Pull request closed without merging**
