### PR TITLE
PostList: Reduxify

### PR DESCRIPTION
**Pull request by ockham**
Pretty straightforward, with one caveat: Previously, `PostListFetcher` would provide us with a `postImages` prop fetched from `PostContentImagesStore`, while  `QueryPosts` doesn't. Fortunately, individual `post` objects have `canonical_image` and `featured_image` attrs which we can use to synthesize that `postImages` object.

To test: Verify `/posts` still works as before (single-page and multi-page mode, queries, etc).

(Rebased after merging #18113 as this was also plagued by https://github.com/Automattic/wp-calypso/pull/18034#issuecomment-329375959)

### CODE REVIEW

**Comment by ockham** [comment]
> 2. Images are missing from some posts. That will happen for posts that have images in the content, but don't have a featured image set. Seems like `PostListFetcher` used `PostContentImagesStore`, which would fetch the first image from the content and use it for a featured image (if there is none). We'll probably want to keep that behavior. Perhaps we're missing some of the previously used posts normalization functionality in our posts selectors? I remember there was some normalization magic around content_media and content_images that we'll want to mirror for the Redux version.

Good spot. I did some digging -- the `getSitePostsForQueryIgnoringPage` calls the same normalization function (`normalizePostForDisplay`) that the old posts store uses. `normalizePostForDisplay` then calls `pickCanonicalImage`, which will look for `post.content_images`.

Now here's the tricky part: we don't have `post.content_images` in Redux. The old posts store uses a function called [`detectMedia`](https://github.com/Automattic/wp-calypso/blob/988fcc839de51290238ba60cc1ff1abe58e620d5/client/lib/post-normalizer/rule-content-detect-media.js#L127-L159) to populate the `content_images` (and `content_media` attributes). And _that_ function expects a DOM element tree to traverse in order to check for `img` and `embed` tags 😖

**Comment by ockham** [comment]
There's some prior art for using all that normalization stuff in Reader, see https://github.com/Automattic/wp-calypso/blob/988fcc839de51290238ba60cc1ff1abe58e620d5/client/state/reader/posts/normalization-rules.js#L130

I wonder how much we could/should carry over, or just re-use...

**Comment by ockham** [comment]
The images issue (item 2 on your list) should be fixed now (per dec248a).

**Comment by ockham** [comment]
> 3. Searching for something that brings a "nothing found" page will display a wrong "You haven't published any posts yet." message. In production it displays a "No posts match your search for ...." message. This is yet another case that indicates we're unwillingly changing something in the posts query.
> 
> 4. Filtering by a post status when there are no posts with that status will display a wrong "You haven't published any posts yet." message. In production it displays an adequate message, related with that post status (like "You don't have any posts in your trash folder." for "trash" status for example). This is yet another case that indicates we're unwillingly changing something in the posts query.

Should be fixed now (2793db3). I was missing some props :man_facepalming:

**Comment by ockham** [comment]
> Should be fixed now (2793db3). I was missing some props :man_facepalming:

FWIW, these are the crucial lines: https://github.com/Automattic/wp-calypso/commit/2793db3e4d0cc39ce144162c9ebf49da4850f54e#diff-835f6d26c8989d298d4f3668fff86d79R177 and https://github.com/Automattic/wp-calypso/commit/2793db3e4d0cc39ce144162c9ebf49da4850f54e#diff-835f6d26c8989d298d4f3668fff86d79R91

**Comment by ockham** [comment]
> 1. I'm seeing a different list of posts in /posts and /posts/my. Seems like the posts list in this branch displays some more posts than the other one for some reason - some of the posts are not being displayed in production, and I'm not sure why. This probably indicates we're unintentionally changing something in the `query`.

I can't repro this -- ideally, it was accidentally fixed by 2793db3. Can you try again?

**Comment by tyxla** [comment]
> I wonder how much we could/should carry over, or just re-use...

All of it? :wink:

**Comment by ockham** [comment]
Thanks for tracking down those differences!

> Here are some differences I've noticed while quickly comparing to production after the latest changes in the branch:

> * Search parameter is not passed to the query args if it is not specified (happens in all queries that are not the search one).
> * Author parameter is not passed to the query args if it is not specified (happens when filtering by post status in a single site view).

Hmm. It shouldn't make a difference if we pass an empty query arg, or none at all, no? If it does, I'd argue we should fix the endpoint.

> * Number is not specified. It seems to be `20` in the `/me/posts` endpoint anyway, so this should be fine.
> * Sorting criteria is missing (`order_by` and `order`). From what I've observed, `order` should always be `DESC`, but `order` can vary. For example, when viewing published posts, they are sorted by `date`, while if viewing drafts, they are sorted by `modified`.

Ah right, that's this line: https://github.com/Automattic/wp-calypso/blob/62931097727905071bf4d815506fd7095dfb5217/client/lib/posts/post-list-store.js#L90-L92 I'll need to do something similar to the Redux action, I guess.

> * I've also noticed `site_visibility => visible` is passed in production, while it's missing for this branch. I'd say this is a nice improvement when for viewing everyone's posts (/posts, /posts/drafts and vice versa), but I think this doesn't make sense for viewing user's own posts (/posts/my and vice versa). I'd expect to be able to see posts from all of my sites when viewing my own posts.

👍

**Comment by ockham** [comment]
Okay, I'll start by comparing API replies for the queries sent by this branch vs production.

This branch (single site, My posts):

```
/sites/example.wordpress.com/posts?http_envelope=1&page=1&number=20&author=<me>&search=&status=publish%2Cprivate&type=post
```

Production:

```
/sites/example.wordpress.com/posts?http_envelope=1&status=publish%2Cprivate&author=<me>&type=post&site_visibility=visible&meta=counts&modified_after=2017-06-13T19%3A48%3A33%2B02%3A00&after=2015-06-29T21%3A45%3A00%2B02%3A00
```

This production query returns no results, because of the `after` qarg. I think `post-list-store` does that as some sort of optimization: https://github.com/Automattic/wp-calypso/blob/9bb87d7c544dc1abae727df56ce732566ab95295/client/lib/posts/post-list-store.js#L397

I'll check if posts are already somewhere in localStorage, or wherever that `_activeList` var is coming from...

**Comment by ockham** [comment]
Production, after clearing localStorage and session storage:

```
/sites/example.wordpress.com/posts?http_envelope=1&status=publish%2Cprivate&order_by=date&order=DESC&author=<me>&type=post&site_visibility=visible&meta=counts
```

**Comment by ockham** [comment]
@tyxla I've added code to set `site_visibility` and `order_by` like in production. Judging from return values, `DESC` seems to be the default `order`.

Among those, `site_visibility` is the only candidate that -- by not being set -- could've let more posts though on this branch than on production. OTOH, I wonder if the `after` and `modified_after` args (see https://github.com/Automattic/wp-calypso/pull/18038#issuecomment-334142779) are possibly hiding _too much_ on production (they're an optimization after all).

I'm still having a hard time repro'ing different lists -- maybe you can pin-point some example posts that we can use to diagnose by what criterion they're being filtered in production... :slightly_smiling_face:

**Comment by ockham** [comment]
Thanks a lot @tyxla!

**Pull request merged**
