### PR TITLE
Reader: Tweaks to spacing in streams

### PR DESCRIPTION
**Pull request by blowery**
Shrink the title to 25px
Give the features some room when they go above the title

### CODE REVIEW

**Comment by blowery** [comment]
Fixes #8992

**Comment by blowery** [comment]
cc @jancavan

**Comment by blowery** [comment]
_2__following_ _reader_ _wordpress_com

**Comment by fraying** [comment]
25px looks better. 👍

**Comment by jancavan** [comment]
I realized Merriweather uses 700 as bold, not 600 so updated it in: https://github.com/Automattic/wp-calypso/pull/9009/commits/cef2f43eb68ca210ab9d979c22a0008b5ca84fd4

**Comment by blowery** [comment]
Thanks @jancavan!

**Comment by jancavan** [comment]
LGTM :shipit:

**Comment by blowery** [comment]
Fixes #9015 too

**Comment by blowery** [comment]
before
following_ _reader_ _wordpress_com

after
following_ _reader_ _wordpress_com

**Comment by blowery** [comment]
## one card
before
_1__following_ _reader_ _wordpress_com

after
following_ _reader_ _wordpress_com

**Comment by fraying** [comment]
Much better! Thanks!

**Pull request merged**
