### PR TITLE
Command Palette: Add a switch site command

### LINKED ISSUE #88229: Feature Request: Add "switch site" to the command palette
### What

Offer a new "switch site" command to the Calypso command palette

### Why

It will make life more convenient for users managing multiple sites.

### How

There are some good ideas here: p9Jlb4-b8X-p2#comment-10963, essentially:

 * In Calypso: prompt for the site as part of the command or rely on the target page having a site switcher.
 * In wp-admin: go to a new calypso page which will display a site selector and then redirect to the provided relative url. This avoids the security constraints about wp-admin knowing about other sites the user may access.

Things to watch out for:
 1. Not all sites will have all pages, i.e. the user might be on a Woo page but the target site might not have Woo installed.
 2. Similarly the user might not have the same permissions on every site that they have access to

Related:
 * pfsHM7-Bd-p2
 * paYJgx-4AA-p2#comment-4823
 * p1709724682782009-slack-C04DZ8M0GHW

### PR DESCRIPTION
**Pull request by dsas**
Fixes https://github.com/Automattic/wp-calypso/issues/88229
Requires https://github.com/Automattic/wp-calypso/pull/88954

## Proposed Changes

This command makes it faster for users with many sites to move between them, and allow them to repeat actions across several sites without leaving the keyboard.

The behavior of the command is a bit different depending on the environment:

- Calypso (site-specific context): will attempt to switch to the same page but for the site selected. Users on wordpress.com/themes/mygroovydomain.com that use the command to switch to example.com will land on wordpress.com/themes/example.com.
- Calypso (global context, e.g. /read): will switch to the dashboard for the selected site.
- WP Admin: will redirect the user to wordpress.com/switch-site?route=??? where route will be the path & search from the current URL. /switch-site is a new page added in https://github.com/Automattic/wp-calypso/pull/88954

#### Remaining work
- [x] Before this is merged we need to have systems add a routing rule for `/switch-site`: pMz3w-jGH-p2

### Issues & potential issues
There are no permissions etc checks. The switch lists all sites and assumes that if the user doesn't have access to the given page for the selected site that the page will handle that nicely enough. I think this is fine as those cases are likely to be rare and the command palette isn't used much, we can always come back to it later if it is proved to be a problem.

## Testing Instructions

**Calypso**

1. Use the calypso live link below
2. Go to /read
3. Invoke the cmd palette 
4. Use switch site
5. You should be prompted to choose a site using the command palette
6. Selecting a site should take you to that site's dashboard
7. Navigate to some calypso page
8. Repeat steps 3-5
9. You should be returned to the same page but with a different site selected

https://github.com/Automattic/wp-calypso/assets/93301/4c98ccd8-45ea-45ce-bd4e-c898f37e1095

**WP Admin**

1. Apply this to sandbox via yarn dev --sync from apps/apps/command-palette-wp-admin or use the install-plugin.sh command that will get generated below
2. Sandbox widgets.wp.com
3. Go to /wp-admin on a test site
4. Press ⌘+k to open the palette
5. Type switch site to find the command and run it
6. You should get redirected to wordpress.com/switch-site?route=%2Fwp-admin
7. Edit the url to replace "wordpress.com" with your test environment - either a calypso.live url from below or calypso.localhost:3000 if testing locally.
8. You should see a list of your sites
9. Choose a site
10. You should get sent to the wp-admin page that you were on before but on the selected site

https://github.com/Automattic/wp-calypso/assets/93301/2f773d76-3db9-45a7-b58c-159ab494c09d

### CODE REVIEW

**Comment by javierarce** [comment]
This works great except for one minor issue: if I am on Site A and invoke the switch command, the list of sites includes Site A (selecting it, by the way, doesn't do anything). This also means that if I only have one site, I'll still see the option to switch with the site I'm currently in, which obviouslly doesn't make sense. So I think we should remove the current site from the list. 

Regarding the message we should display in that case, I think we could follow the same idea as the empty message:

Screenshot 2024-03-29 at 16 28 19

To maintain the behavior of other items, which is to display a message instead of disabling or hiding the option, if the user only has one site and is currently viewing it, perhaps we could say this: `You don't have other sites to switch to.`

**Comment by mmtr** [comment]
After unifying the commands in https://github.com/Automattic/wp-calypso/pull/89040, we cannot really add the command first to Calypso and then to WP Admin, it needs to be done at the same time. I'll re-work these PRs.

**Comment by dsas** [comment]
LGTM 👍

**Comment by mmtr** [comment]
> Before this is merged we need to have systems add a routing rule for `/switch-site`

Just posted a systems request: pMz3w-jGH-p2. Let's wait for the routing to be updated before merging this.

**Pull request merged**
