### PR TITLE
Help Center: Hide placeholder message if waiting for AI response

### PR DESCRIPTION
**Pull request by agrullon95**
Fixes: https://github.com/Automattic/dotcom-forge/issues/9776

## Proposed Changes

* Disables input field and changes placeholder text to `Just a moment...` when waiting for AI response

image

## Why are these changes being made?

* Hide input field placeholder while AI is responding.

## Testing Instructions

* Checkout branch or use live link
* Navigate to `/home?flags=help-center-experience` and open the Help Center
* Open a chat with AI and send a message.
* Verify the text input field placeholder changes to `Just a moment...` while the AI/Wapuu thinking icon is appearing (while waiting for AI response)

### CODE REVIEW

**Comment by escapemanuele** [comment]
Thanks Anthony!

Let's also keep pdDR7T-1X1-p2#comment-2420 in mind before proceding

**Comment by escapemanuele** [comment]
@agrullon95 let's implement https://github.com/Automattic/dotcom-forge/issues/9776#issuecomment-2471380342

**Comment by escapemanuele** [comment]
I thought I disabled the button while waiting, or when the input field was empty, could you check what's wrong?

image

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/17002103

Some locales (Hebrew, Japanese) have been temporarily machine-translated due to translator availability. All other translations are usually ready within a few days. Untranslated and machine-translated strings will be sent for translation next Monday and are expected to be completed by the following Friday.

Hi @agrullon95, could you please edit the description of this PR and add a screenshot for our translators? Ideally it'd include this string: `Just a moment…`

Thank you in advance!

**Comment by agrullon95** [comment]
@escapemanuele - I'm not sure what happened there, but I updated the PR to handle that scenario. The input field and send button should now be disabled when waiting for AI response.

**Review by escapemanuele — APPROVED** [review]
Perfect 👌

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/17002103).

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/17002103).

**Pull request merged**
