### PR TITLE
Reader: goodbye FeedPostStore

### PR DESCRIPTION
**Pull request by samouri**
part of the reader reduxification effort https://github.com/Automattic/wp-calypso/issues/10984.

Now that 99% of the functionality from `FeedPostStore` has been moved to redux, this PR attempts to delete the unused code and port over that last 1%  -- I'm looking at you `markSeen`!

**To Test**
- open a stream, click a post, searching for a post. click recs and combined cards.
- open up RelatedPosts and click into more RPs.  Especially for sites like Time and Uproxx
- use the `at` link and click an update pill. then click a gap
- ensure `markSeen` is still working. look for the `reader_pageview` stat

### CODE REVIEW

**Comment by dmsnell** [comment]
http://iscalypsofastyet.com/branch?branch=update/reader/byebye-feedpoststore

```
Delta:
chunk                                        stat_size           parsed_size           gzip_size
async-load-blocks-reader-full-post             -3237 B  (-3.7%)      -1048 B  (-2.2%)     -321 B  (-2.6%)
async-load-components-web-preview-component    -7097 B  (-1.7%)      -4000 B  (-1.8%)    -1167 B  (-2.2%)
async-load-reader-site-stream                     +0 B                  +0 B                +0 B
build                                           +388 B  (+0.0%)       +202 B  (+0.0%)      +43 B  (+0.0%)
devdocs                                       -10344 B  (-0.3%)      -5052 B  (-0.2%)    -1456 B  (-0.3%)
manifest                                          +0 B                  +0 B                +4 B  (+0.1%)
reader                                         -6957 B  (-1.2%)      -3634 B  (-1.1%)    -1009 B  (-1.4%)
```

**Comment by samouri** [comment]
rebased!

**Comment by bluefuton** [comment]
> use the at link and click an update pill. then click a gap

@samouri what should the `markSeen` behaviour be here? I'm not seeing any page view events fire when clicking an update pill, unless I open a full post.

Are there any other spots I need to check? I notice that the like button and photo card expansions both fire a page view.

**Comment by samouri** [comment]
> @samouri what should the markSeen behaviour be here? I'm not seeing any page view events fire when clicking an update pill, unless I open a full post.

each of the testing instructions are testing completely separate things! `markSeen` shouldn't be called when the update pill is called.  AFAIK, `markSeen` should only be called when:

1. post opened to full-post page
2. discover post challenge is opened in editor 
3. post is liked
4. photo/video post is expanded

**Pull request merged**
