### PR TITLE
Checkout: Do not redirect to setup after purchase

### PR DESCRIPTION
**Pull request by ebinnion**
#### Proposed Changes

* Do not redirect to setup on upgrade since sites should have already been setup.

This minimizes an issue that we're seeing in production. See Slack: p1658416912566239-slack-C02FMH4G8

#### Testing Instructions

* On an existing site, upgrade to premium
* After checkout, on upgrade sell nudge, do not upgrade for plugins
* Verify that you land on home

#### Pre-merge Checklist

- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in [Simple](P9HQHe-k8-p2-p2), [Atomic](P9HQHe-jW-p2-p2), and [self-hosted Jetpack sites](PCYsg-g6b-p2-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Are we memoizing when appropriate (for expensive computations)? More info in [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md) and [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors)
- [ ] Have we sent any new strings [for translation](PCYsg-1vr-p2-p2) ASAP?

### CODE REVIEW

**Comment by sixhours** [comment]
Confirmed you're redirected to the home screen after upsell nudge at checkout!

**Review by taipeicoder — APPROVED** [review]
Tested and works as intended. Was redirected to the dashboard after declining.

**Comment by simison** [comment]
Looking at the code quickly now, we'll still need to continue bringing customers to onboarding flows instead of My home for _new_ sites. Otherwise all they ever see is domains + plans. This My home URL change is good for existing sites and fixes the issue.

I believe in [original PR](https://github.com/Automattic/wp-calypso/pull/65773) they were redirected to some kind of "than you page". It looked very dated, but probably still more relevant than My home.

@Automattic/ganon is probably next one online, could you help with the change here? Thank you!

- **New sites:** Plans → Checkout → Upsell → Continue site setup onboarding. (Intent of the original PR)
- **Existing sites doing plan upgrade:** Checkout → Upsell → Thank you page (URL from previous PR).
- **Existing sites launching a site upgrade:** Plans → Checkout → Upsell → I believe we normally redirect to My home? 

Not sure if this impacts site launch flow but good to test.

**Comment by sirbrillig** [comment]
> I believe in https://github.com/Automattic/wp-calypso/pull/65773 they were redirected to some kind of "than you page". It looked very dated, but probably still more relevant than My home.

Yeah, I think [this function](https://github.com/Automattic/wp-calypso/blob/7fb312bfaf41249904aaf9244525f7bff0ff7301/client/my-sites/checkout/upsell-nudge/index.jsx#L354) was already set up to return the appropriate post-checkout URL for this page. It calls the post-checkout URL function `getThankYouUrl()` which responds to many different scenarios and is covered by unit tests. Maybe that function just needs its arguments updated to support whatever https://github.com/Automattic/wp-calypso/pull/65773 was supposed to do.

**Pull request merged**
