### PR TITLE
Stats: Remove pulsing dot animation from date picker

### PR DESCRIPTION
**Pull request by mcsf**
The animation, which was hinging on `box-shadow`, was a very expensive one: on my 2015 MBP, `/stats/day/:blogId` was idling at ~30–35% CPU. This PR brings that number down to ~3%.

Although this is a design change, it was discussed on Slack that this is a non-standard animation which should be removed anyway. The _last updated_ mention will still appear, informing the user who has stayed more than a few seconds on the page that it will update itself.

screen shot 2017-07-03 at 15 02 29

For the record, I considered not removing the animation altogether and instead applying the following:

```diff
diff --git a/client/my-sites/stats/stats-date-picker/style.scss b/client/my-sites/stats/stats-date-picker/style.scss
index b6b22dbff..1eb9c4f1e 100644
--- a/client/my-sites/stats/stats-date-picker/style.scss
+++ b/client/my-sites/stats/stats-date-picker/style.scss
@@ -20,14 +20,14 @@
 			border: none;
 			box-shadow: 0 0 0 0 rgba( 168, 190, 206, 0.7 );
 			border-radius: 100%;
-			animation: stats-dot-pulse 1.25s infinite cubic-bezier( 0.66, 0, 0, 1 );
+			animation: stats-dot-pulse 2.5s infinite cubic-bezier( 0.66, 0, 0, 1 );
 			vertical-align: middle;
 		}
 	}
 
 	@keyframes stats-dot-pulse {
 		to {
-			box-shadow: 0 0 0 5px rgba( 90, 153, 220, 0 );
+			opacity: 0;
 		}
 	}
 }
```

which also yielded a big improvement, yet CPU was still in the ~5–7% range.

### CODE REVIEW

**Comment by folletto** [comment]
I would have edged in keeping it, as it's a useful information, but I'm ok if the assessment led the team to a different conclusion.

Would be possible however to keep the tooltip on maybe a `(i)` icon? Otherwise there's no way to tell something is happening (most of the services that state a time require a reload).

**Comment by mcsf** [comment]
> Would be possible however to keep the tooltip on maybe a (i) icon? Otherwise there's no way to tell something is happening (most of the services that state a time require a reload).

I can give that a go and see what it looks like.

**Comment by mcsf** [comment]
@folletto:

screen shot 2017-07-03 at 15 43 21

**Comment by folletto** [comment]
I think that can work 👍

**Comment by mtias** [comment]
Nice cleanup, thanks!

**Comment by lancewillett** [comment]
Nice work @mcsf and Team Samus — love seeing these performance wins for a better experience.

**Pull request merged**
