### PR TITLE
Jetpack Backup: Add Retry button for warnings

### PR DESCRIPTION
**Pull request by jwebbdev**
#### Changes proposed in this Pull Request

* Adds retry button and functionality for use when a site has a successful backup with warnings
* A link is introduced to support documentation, but the documentation doesn't exist yet, so it's linked to general Jetpack Backup docs.  The link will be updated with an anchor to the appropriate area once added.

#### Testing instructions

* Warning functionality isn't live yet, so warnings will have to be artificially inserted into a site's activity log to test
* This can be done by adding warnings to the activity log output of a backup from a Jetpack Backup sandbox
* Instructions for introducing warnings to a backup in a sandbox can be found in patch D80570
* If you don't have access to a Backup sandbox, let a Backup dev know what site you'd like to test on
* If D80889 still needs to land, you'll have to pull it and point your public-api at a wpcom sandbox for the Retry end point to work.

Screen Shot 2022-05-16 at 3 01 31 PM

### CODE REVIEW

**Review by mavegaf — APPROVED** [review]
Looks goods. Should we disable the "Retry" button to prevent clicking it multiple times?
Screen Shot 2022-05-16 at 20 53 22
-------------------
Screen Shot 2022-05-16 at 20 59 13

**Comment by jwebbdev** [comment]
> Should we disable the "Retry" button to prevent clicking it multiple times?

Yeah, I'll look into that.

**Comment by grbicsanja** [comment]
Looking great!
A few notes:
- 'Retry queued' copy for disabled CTA
- Restore button should be styled as secondary (when enabled)

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/7314375

Thank you @jwebbdev for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/7314375).

**Pull request merged**
