### PR TITLE
Adds missing dependencies to wpcom-block-editor

### PR DESCRIPTION
**Pull request by scinos**
### Problem

`@yarnpkg/doctor` found a bunch of undeclared dependencies and missing peer dependencies:

```
➤ YN0000: ┌ /Users/sergio/src/automattic/wp-calypso2/apps/wpcom-block-editor/package.json
➤ YN0000: │ User scripts prefixed with "pre" or "post" (like "prebuild") will not be called in sequence anymore; prefer calling prologues and epilogues explicitly
➤ YN0000: │ /Users/sergio/src/automattic/wp-calypso2/apps/wpcom-block-editor/webpack.config.js:10:43: Undeclared dependency on @wordpress/dependency-extraction-webpack-plugin
➤ YN0000: │ /Users/sergio/src/automattic/wp-calypso2/apps/wpcom-block-editor/webpack.config.js:11:30: Undeclared dependency on @automattic/calypso-build
➤ YN0000: │ /Users/sergio/src/automattic/wp-calypso2/apps/wpcom-block-editor/bin/npm-run-build.js:10:16: Undeclared dependency on npm-run-all
➤ YN0000: │ /Users/sergio/src/automattic/wp-calypso2/apps/wpcom-block-editor/src/utils.js:5:1: Undeclared dependency on @wordpress/data
➤ YN0000: │ /Users/sergio/src/automattic/wp-calypso2/apps/wpcom-block-editor/src/wpcom/editor.js:7:1: Undeclared dependency on @wordpress/plugins
➤ YN0000: │ /Users/sergio/src/automattic/wp-calypso2/apps/wpcom-block-editor/src/default/features/rich-text.js:7:1: Undeclared dependency on @wordpress/compose
➤ YN0000: │ /Users/sergio/src/automattic/wp-calypso2/apps/wpcom-block-editor/src/default/features/rich-text.js:8:1: Undeclared dependency on @wordpress/data
➤ YN0000: │ /Users/sergio/src/automattic/wp-calypso2/apps/wpcom-block-editor/src/default/features/rich-text.js:9:1: Undeclared dependency on @wordpress/editor
➤ YN0000: │ /Users/sergio/src/automattic/wp-calypso2/apps/wpcom-block-editor/src/default/features/rich-text.js:10:1: Undeclared dependency on @wordpress/rich-text
➤ YN0000: │ /Users/sergio/src/automattic/wp-calypso2/apps/wpcom-block-editor/src/default/features/rich-text.js:11:1: Undeclared dependency on lodash
➤ YN0000: │ /Users/sergio/src/automattic/wp-calypso2/apps/wpcom-block-editor/src/default/features/switch-to-classic.js:7:1: Undeclared dependency on jquery
➤ YN0000: │ /Users/sergio/src/automattic/wp-calypso2/apps/wpcom-block-editor/src/calypso/features/iframe-bridge-server.js:7:1: Undeclared dependency on jquery
➤ YN0000: │ /Users/sergio/src/automattic/wp-calypso2/apps/wpcom-block-editor/src/calypso/features/iframe-bridge-server.js:8:1: Undeclared dependency on lodash
➤ YN0000: │ /Users/sergio/src/automattic/wp-calypso2/apps/wpcom-block-editor/src/calypso/features/iframe-bridge-server.js:9:1: Undeclared dependency on @wordpress/data
➤ YN0000: │ /Users/sergio/src/automattic/wp-calypso2/apps/wpcom-block-editor/src/calypso/features/iframe-bridge-server.js:10:1: Undeclared dependency on @wordpress/blocks
➤ YN0000: │ /Users/sergio/src/automattic/wp-calypso2/apps/wpcom-block-editor/src/calypso/features/iframe-bridge-server.js:11:1: Undeclared dependency on @wordpress/hooks
➤ YN0000: │ /Users/sergio/src/automattic/wp-calypso2/apps/wpcom-block-editor/src/calypso/features/iframe-bridge-server.js:12:1: Undeclared dependency on @wordpress/url
➤ YN0000: │ /Users/sergio/src/automattic/wp-calypso2/apps/wpcom-block-editor/src/calypso/features/iframe-bridge-server.js:13:1: Undeclared dependency on @wordpress/plugins
➤ YN0000: │ /Users/sergio/src/automattic/wp-calypso2/apps/wpcom-block-editor/src/calypso/features/iframe-bridge-server.js:15:1: Undeclared dependency on @wordpress/components
➤ YN0000: │ /Users/sergio/src/automattic/wp-calypso2/apps/wpcom-block-editor/src/calypso/features/iframe-bridge-server.js:16:1: Undeclared dependency on @wordpress/icons
➤ YN0000: │ /Users/sergio/src/automattic/wp-calypso2/apps/wpcom-block-editor/src/calypso/features/iframe-bridge-server.js:17:1: Undeclared dependency on react
➤ YN0000: │ /Users/sergio/src/automattic/wp-calypso2/apps/wpcom-block-editor/src/calypso/features/iframe-bridge-server.js:18:1: Undeclared dependency on tinymce
➤ YN0000: │ /Users/sergio/src/automattic/wp-calypso2/apps/wpcom-block-editor/src/calypso/features/tinymce.js:6:1: Undeclared dependency on tinymce
➤ YN0000: │ /Users/sergio/src/automattic/wp-calypso2/apps/wpcom-block-editor/src/wpcom/features/convert-to-blocks-button.js:11:1: Undeclared dependency on @wordpress/hooks
➤ YN0000: │ /Users/sergio/src/automattic/wp-calypso2/apps/wpcom-block-editor/src/wpcom/features/convert-to-blocks-button.js:12:1: Undeclared dependency on @wordpress/block-editor
➤ YN0000: │ /Users/sergio/src/automattic/wp-calypso2/apps/wpcom-block-editor/src/wpcom/features/convert-to-blocks-button.js:13:1: Undeclared dependency on @wordpress/components
➤ YN0000: │ /Users/sergio/src/automattic/wp-calypso2/apps/wpcom-block-editor/src/wpcom/features/convert-to-blocks-button.js:14:1: Undeclared dependency on @wordpress/i18n
➤ YN0000: │ /Users/sergio/src/automattic/wp-calypso2/apps/wpcom-block-editor/src/wpcom/features/convert-to-blocks-button.js:15:1: Undeclared dependency on @wordpress/compose
➤ YN0000: │ /Users/sergio/src/automattic/wp-calypso2/apps/wpcom-block-editor/src/wpcom/features/convert-to-blocks-button.js:16:1: Undeclared dependency on @wordpress/data
➤ YN0000: │ /Users/sergio/src/automattic/wp-calypso2/apps/wpcom-block-editor/src/wpcom/features/convert-to-blocks-button.js:17:1: Undeclared dependency on @wordpress/blocks
➤ YN0000: │ /Users/sergio/src/automattic/wp-calypso2/apps/wpcom-block-editor/src/wpcom/features/deprecate-coblocks-buttons.js:6:1: Undeclared dependency on @wordpress/blocks
➤ YN0000: │ /Users/sergio/src/automattic/wp-calypso2/apps/wpcom-block-editor/src/wpcom/features/deprecate-coblocks-buttons.js:7:1: Undeclared dependency on @wordpress/dom-ready
➤ YN0000: │ /Users/sergio/src/automattic/wp-calypso2/apps/wpcom-block-editor/src/wpcom/features/fix-block-invalidation-errors.js:6:1: Undeclared dependency on @wordpress/data
➤ YN0000: │ /Users/sergio/src/automattic/wp-calypso2/apps/wpcom-block-editor/src/wpcom/features/fix-block-invalidation-errors.js:7:1: Undeclared dependency on @wordpress/blocks
➤ YN0000: │ /Users/sergio/src/automattic/wp-calypso2/apps/wpcom-block-editor/src/wpcom/features/images.js:5:1: Undeclared dependency on @wordpress/i18n
➤ YN0000: │ /Users/sergio/src/automattic/wp-calypso2/apps/wpcom-block-editor/src/wpcom/features/reorder-block-categories.js:5:1: Undeclared dependency on @wordpress/blocks
➤ YN0000: │ /Users/sergio/src/automattic/wp-calypso2/apps/wpcom-block-editor/src/wpcom/features/reorder-block-categories.js:6:1: Undeclared dependency on @wordpress/dom-ready
➤ YN0000: │ /Users/sergio/src/automattic/wp-calypso2/apps/wpcom-block-editor/src/wpcom/features/tracking.js:5:1: Undeclared dependency on @wordpress/data
➤ YN0000: │ /Users/sergio/src/automattic/wp-calypso2/apps/wpcom-block-editor/src/wpcom/features/tracking.js:6:1: Undeclared dependency on @wordpress/plugins
➤ YN0000: │ /Users/sergio/src/automattic/wp-calypso2/apps/wpcom-block-editor/src/wpcom/features/tracking.js:7:1: Undeclared dependency on @wordpress/hooks
➤ YN0000: │ /Users/sergio/src/automattic/wp-calypso2/apps/wpcom-block-editor/src/wpcom/features/tracking.js:8:1: Undeclared dependency on lodash
➤ YN0000: │ /Users/sergio/src/automattic/wp-calypso2/apps/wpcom-block-editor/src/wpcom/features/use-classic-block-guide.js:5:1: Undeclared dependency on @wordpress/element
➤ YN0000: │ /Users/sergio/src/automattic/wp-calypso2/apps/wpcom-block-editor/src/wpcom/features/use-classic-block-guide.js:6:1: Undeclared dependency on @wordpress/components
➤ YN0000: │ /Users/sergio/src/automattic/wp-calypso2/apps/wpcom-block-editor/src/wpcom/features/use-classic-block-guide.js:7:1: Undeclared dependency on @wordpress/data
➤ YN0000: │ /Users/sergio/src/automattic/wp-calypso2/apps/wpcom-block-editor/src/wpcom/features/use-classic-block-guide.js:9:1: Undeclared dependency on @wordpress/i18n
➤ YN0000: │ /Users/sergio/src/automattic/wp-calypso2/apps/wpcom-block-editor/src/wpcom/features/use-classic-block-guide.js:10:1: Undeclared dependency on @wordpress/plugins
➤ YN0000: │ /Users/sergio/src/automattic/wp-calypso2/apps/wpcom-block-editor/src/wpcom/features/tracking/track-record-event.js:5:1: Undeclared dependency on lodash
➤ YN0000: │ /Users/sergio/src/automattic/wp-calypso2/apps/wpcom-block-editor/src/wpcom/features/tracking/wpcom-inserter-inline-search-term.js:6:1: Undeclared dependency on lodash
➤ YN0000: │ /Users/sergio/src/automattic/wp-calypso2/apps/wpcom-block-editor/src/wpcom/features/tracking/wpcom-inserter-inline-search-term.js:11:1: Undeclared dependency on @wordpress/data
➤ YN0000: │ /Users/sergio/src/automattic/wp-calypso2/apps/wpcom-block-editor/src/wpcom/features/tracking/wpcom-inserter-menu-search-term.js:5:1: Undeclared dependency on lodash
➤ YN0000: │ /Users/sergio/src/automattic/wp-calypso2/apps/wpcom-block-editor/src/wpcom/features/tracking/wpcom-inserter-menu-search-term.js:10:1: Undeclared dependency on @wordpress/element
➤ YN0000: │ /Users/sergio/src/automattic/wp-calypso2/apps/wpcom-block-editor/src/wpcom/features/tracking/wpcom-inserter-menu-search-term.js:11:1: Undeclared dependency on @wordpress/data
➤ YN0000: │ /Users/sergio/src/automattic/wp-calypso2/apps/wpcom-block-editor/src/wpcom/features/tracking/wpcom-inserter-menu-search-term.js:12:1: Undeclared dependency on @wordpress/block-editor
➤ YN0000: └ Completed in 1.18s
```

### Changes

This PR adds those dependencies to `./apps/wpcom-block-editor/package.json`. The version ranges have been copied from `./package.json` to make sure nothing changes.

### Testing instructions

Verify files have not actually changed:
* Checkout master, run `yarn; cd apps/wpcom-block-editor; yarn build:prod` and copy the folder `apps/wpcom-block-editor/dist` somewhere (eg: to `$HOME/dist-master`)
* Checkout this branch and repeat the same steps. The folder can be copied to `$HOME/dist-branch`
* Compare the generated files in both `dist` folders. You can use this command (assuming the folders are named `dist-master` and `dist-branch` and they live in the same directory): `for file in dist-master/*; do diff $file ${file/dist-master/dist-branch}; done`. The should be no differences.

Verify there are no more missing packages:
* Run `npx @yarnpkg/doctor` inside `./apps/wpcom-block-editor`. All warnings about missing dependencies should be gone now.

### CODE REVIEW

**Comment by scinos** [comment]
@mmtr I added you as reviewers based on GitHub suggestions. Please let me know if you think someone else should review this change.

**Comment by mmtr** [comment]
Thanks @scinos! I verified there are no differences when compared to the build generated in master, and `@yarnpkg/doctor` no longer complains about missing deps.

Does this mean we can remove now all [`eslint-disable import/no-extraneous-dependencies` usages](https://github.com/search?q=no-extraneous-dependencies+repo%3AAutomattic%2Fwp-calypso+path%3Aapps%2Fwpcom-block-editor&type=Code&ref=advsearch&l=&l=)?

I'd also like to have a confidence check from @jsnajdr here, since the deps were initially declared and then removed in https://github.com/Automattic/wp-calypso/pull/35729 because they are actually externalized and not installed.

**Comment by scinos** [comment]
> Does this mean we can remove now all eslint-disable import/no-extraneous-dependencies usages?

Yes, we should be able to remove those. I was thinking on doing a second pass cleaning up `.eslintrc` files, but I can do the same in this PR

Personally I do think we should declare all dependencies, even if they are replaced by something else at build time. It doesn't add any significant overhead, it doesn't change the output and makes everything work better with static analysis and IDE integrations.

Happy to wait for @jsnajdr anyway, but he is on parental leave for a few weeks.

**Comment by mmtr** [comment]
> I was thinking on doing a second pass cleaning up .eslintrc files, but I can do the same in this PR

Either is fine to me 👍 

> Personally I do think we should declare all dependencies, even if they are replaced by something else at build time. It doesn't add any significant overhead, it doesn't change the output and makes everything work better with static analysis and IDE integrations.

Thanks for clarifying. Provided this doesn't affect the builds and it helps with the eslint warnings, I'd say let's go ahead. We can always revert it if we receive feedback about keeping the current approach.

**Review by mmtr — APPROVED** [review]

**Pull request merged**
