### PR TITLE
Reader: update Cold Start intro copy

### PR DESCRIPTION
**Pull request by jancavan**
**Before:**
screenshot 2016-08-04 13 14 15

**After:**
screenshot 2016-08-04 13 18 20

/cc @fraying 

Test live: https://calypso.live/?branch=update/reader/cold-start-intro-copy

### CODE REVIEW

**Comment by blowery** [comment]
code LGTM

**Comment by fraying** [comment]
👍

**Comment by fraying** [comment]
Did this go out?

**Comment by jancavan** [comment]
@fraying Yes, this has been merged.

**Pull request merged**
