### PR TITLE
i18n: Unifying languages

### PR DESCRIPTION
**Pull request by yuliyan**
#### Changes proposed in this Pull Request

* Add notice in language picker modal when non-magnificent locale is selected
* Replace hard coded languages data with `languages-meta.json` downloaded from i18n-deploy
* Add setting for using default locale as fallback for languages with incomplete translations.

image

#### Testing instructions

* Boot Calypso (`yarn start`)
* Confirm that `languages-meta.json` is downloaded successfully in `client/languages/`. Make sure it's downloading the JSON file from D46739-code.
* Go to [Account Settings](http://calypso.localhost:3000/me/account), select non-magnificent language (e.g. Croatian) and confirm that language notice is being rendered.
* Update interface language and enable `Display interface in Engllish` option. Confirm interface renders in English after saving the settings.

#### Related
D45711-code
D46739-code

### CODE REVIEW

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/4190686

Thank you @yuliyan for including a screenshot in the description! This is really helpful for our translators.

**Comment by sgomes** [comment]
@yuliyan: This PR appears to now make `client/lib/i18n-utils/test/utils.js` fail after a `yarn start`:

```sh
$ yarn start
[...]
$ yarn test-client lib/i18n-utils/test/utils.js
 FAIL  client/lib/i18n-utils/test/utils.js
  ● utils › #isLocaleVariant › should detect a locale variant

    expect(received).toEqual(expected) // deep equality

    Expected: true
    Received: false
```

**Comment by yuliyan** [comment]
> @yuliyan: This PR appears to now make `client/lib/i18n-utils/test/utils.js` fail after a `yarn start`:
> 
> ```shell
> $ yarn start
> [...]
> $ yarn test-client lib/i18n-utils/test/utils.js
>  FAIL  client/lib/i18n-utils/test/utils.js
>   ● utils › #isLocaleVariant › should detect a locale variant
> 
>     expect(received).toEqual(expected) // deep equality
> 
>     Expected: true
>     Received: false
> ```

Could you give me more details on how to reproduce the failing tests? Just tried locally, but the tests are passing. Also checked the [CircleCI test-client job](https://app.circleci.com/pipelines/github/Automattic/wp-calypso/69508/workflows/3f37b96c-f293-4950-9a0b-1ad25bd943c4/jobs/839423) and tests seem to have passed there as well.

**Comment by sgomes** [comment]
Just following the sequence of commands I posted above is enough for me. That is, if `languages-meta.json` is missing, the test works correctly. However, if the file is present because I ran a `yarn start` first, then the test fails.

This appears to be because the `de_formal` locale (which is the one being tested by the unit test) has different configuration between `languages-meta.json` and `fallback-languages-meta.json`.

**Comment by yuliyan** [comment]
> @yuliyan Just following the sequence of commands I posted above is enough for me. That is, if `languages-meta.json` is missing, the test works correctly. However, if the file is present because I ran a `yarn start` first, then the test fails. I assume it passes on CI because it doesn't run a `yarn start` first there.
> 
> This appears to be because the `de_formal` locale (which is the one being tested by the unit test) has different configuration between `languages-meta.json` and `fallback-languages-meta.json`.

Sorry, I missed the `yarn start` from your initial message. Now managed to reproduce it and `languages-meta.json` is indeed missing the `parentLangSlug` property.

It will be fixed with D47620-code.

**Comment by sgomes** [comment]
Sweet, thanks @yuliyan! 🙂

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/4190686).

**Pull request merged**
