### PR TITLE
Janitorial: Refactor build-languages script(s)

### PR DESCRIPTION
**Pull request by alshakero**
## Proposed Changes

This deduplicates the `build-languages.js` script that was duplicated in 3 places with virtually no differences into a single script runnable as a command. My rationale in doing this is that I need to replicate this file once more for `verbum-block-editor` and felt uneasy about having 4 copies of the same script. So I made this easy-to-review PR as a first step.

## Testing Instructions

1. **Don't check out this branch and stay on trunk**.
2. Go to `apps/command-palette-wp-admin`. 
3. Run `yarn build && yarn translate`. 
4. Run `ls -l` in `apps/command-palette-wp-admin/dist/languages`. Save the output to a text file somewhere.

Repeat the same operation exactly for `apps/blaze-dashboard` and `apps/odyssey-stats`.

Now, checkout this branch and:

1. Run `yarn` to update `calypso-build` script. If the build gets stuck, delete `packages/components/dist` folder.
2. Repeat the instructions ablove.
3. The output of the `ls -l` command should not change between trunk and here, besides the modification date.

### CODE REVIEW

**Review by heavyweight — APPROVED** [review]
Followed the testing steps and verified that we get the same output

**Comment by escapemanuele** [comment]
Great!  Should we remove the script from `command-palette-wp-admin` as well?

**Comment by alshakero** [comment]
It was removed, but GH [thinks it was renamed](https://github.com/Automattic/wp-calypso/pull/90415/files#diff-a6c8580899190a7180a05826308ef3a6179150a54c37626113543672e14eb240).

**Review by dsas — COMMENTED** [review]
For odyssey stats I get an error when running yarn translate:

```
Building languages...
node:internal/modules/cjs/loader:1048
  const err = new Error(message);
              ^

Error: Cannot find module '.././dist/chunks-map.json'
Require stack:
- /Users/dsas/Code/wp-calypso/apps/odyssey-stats/bin/build-languages.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1048:15)
    at Module._load (node:internal/modules/cjs/loader:901:27)
    at Module.require (node:internal/modules/cjs/loader:1115:19)
    at require (node:internal/modules/helpers:130:18)
    at buildLanguages (/Users/dsas/Code/wp-calypso/apps/odyssey-stats/bin/build-languages.js:161:21)
    at run (/Users/dsas/Code/wp-calypso/apps/odyssey-stats/bin/build-languages.js:223:2) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/dsas/Code/wp-calypso/apps/odyssey-stats/bin/build-languages.js'
  ]
}

Node.js v20.8.1
```

**Comment by alshakero** [comment]
@dsas, you have to run `yarn build` first. I know it's not pleasant, but it's like that on trunk and I didn't want to complicate the PR. 

**Edit: in fact, running `yarn build` alone is sufficient.**

**Comment by heavyweight** [comment]
> For odyssey stats I get an error when running yarn translate:
> 
> ```
> Building languages...
> node:internal/modules/cjs/loader:1048
>   const err = new Error(message);
>               ^
> 
> Error: Cannot find module '.././dist/chunks-map.json'
> Require stack:
> - /Users/dsas/Code/wp-calypso/apps/odyssey-stats/bin/build-languages.js
>     at Module._resolveFilename (node:internal/modules/cjs/loader:1048:15)
>     at Module._load (node:internal/modules/cjs/loader:901:27)
>     at Module.require (node:internal/modules/cjs/loader:1115:19)
>     at require (node:internal/modules/helpers:130:18)
>     at buildLanguages (/Users/dsas/Code/wp-calypso/apps/odyssey-stats/bin/build-languages.js:161:21)
>     at run (/Users/dsas/Code/wp-calypso/apps/odyssey-stats/bin/build-languages.js:223:2) {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: [
>     '/Users/dsas/Code/wp-calypso/apps/odyssey-stats/bin/build-languages.js'
>   ]
> }
> 
> Node.js v20.8.1
> ```

I had the same
Can you try `yarn dev` before `yarn build`

**Review by yuliyan — APPROVED** [review]
Nice cleanup! LGTM 🚀

I wonder if it'd be possible to also use the same script for building Calypso's translation files.

**Review by dsas — COMMENTED** [review]
I still can't build odyssey stats, but that's looking like it might be a me problem. 

Blaze and the command palette both create the same files all with the same number of bytes though 👍

**Comment by alshakero** [comment]
> I wonder if it'd be possible to also use the same script for building Calypso's translation files.

It should be, and tried it for a bit last night. But it seems to have slightly different logic that I didn't want to mess with it considering my shallow understanding.

It would be great if you can give it a spin.

**Pull request merged**
