### PR TITLE
Performance Profiler: Make CrUX details responsive

### PR DESCRIPTION
**Pull request by epeicher**
Resolves https://github.com/Automattic/dotcom-forge/issues/8911

## Proposed Changes

* In the CrUX details section, wrap the components when there is no free space
* Make the chart responsive to different sizes of screens

> [!NOTE]  
> This PR is based on the changes done in https://github.com/Automattic/wp-calypso/pull/93994

### Recording of changes
https://github.com/user-attachments/assets/263a880c-79d6-4b46-96c5-7e92e6372748

## Why are these changes being made?

* To make responsive the CrUX details section

## Testing Instructions

* Navigate to the Speed Test tool
* Resize the browser window to different sizes
* Make sure the behavior of the CrUX range chart and history chart works as expected. They should wrap for small screens
* Make sure the size of the charts adapt to the screen width.

**Note:** The history chart does not seem to resize correctly when dynamically resizing to small screens. This should be further investigated. 

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Review by gavande1 — APPROVED** [review]
Looks amazing! Thanks for working on this.

**Review by WBerredo — APPROVED** [review]
LGTM!

> Note: The history chart does not seem to resize correctly when dynamically resizing to small screens. This should be further investigated.

Fixe this at https://github.com/Automattic/wp-calypso/pull/94031/commits/75c8b1222ebab7e56d78e1db77b0bd0ac7d2a906

**Comment by gavande1** [comment]
@WBerredo @epeicher, I just noticed this change caused issues with the tooltip. The tooltip is no longer rendering on screen. Could you please check?

**Comment by epeicher** [comment]
> @WBerredo @epeicher, I just noticed this change caused issues with the tooltip. The tooltip is no longer rendering on screen. Could you please check?

Hi @gavande1, thanks for reporting this and finding the cause. I have implemented a fix here https://github.com/Automattic/wp-calypso/pull/94127

**Pull request merged**
