### PR TITLE
Stats: Fix Date Picker moment

### PR DESCRIPTION
**Pull request by timmyc**
This is a follow-up branch to #12437 - with an alternate, more appropriate fix to ensure dates are properly localized in `StatsDatePicker`

__To Test__
- Set your interface language to something other than English.
- Open a site stats page
- Verify the date in the "Stats for XXXXX" text is localized

/cc @stephanethomas

### CODE REVIEW

**Comment by stephanethomas** [comment]
Looks good and works fine.

I've added a commit to address the points I mentioned in https://github.com/Automattic/wp-calypso/pull/12437#issuecomment-289384488. If you're cool with those changes, then let's ship it.

**Comment by stephanethomas** [comment]
It looks like we have a few linting issues to address here:

```
/var/sources/client/my-sites/stats/controller.jsx
   12:1  error  'lib/sites-list' import is restricted from being used      no-restricted-imports
  222:8  error  'momentSiteZone' is never reassigned. Use 'const' instead  prefer-const

/var/sources/client/my-sites/stats/stats-date-picker/index.jsx
  131:12  error  className should follow CSS namespace guidelines (expected stats-date-picker__ prefix)  wpcalypso/jsx-classname-namespace
  132:13  error  className should follow CSS namespace guidelines (expected stats-date-picker__ prefix)  wpcalypso/jsx-classname-namespace
  144:13  error  className should follow CSS namespace guidelines (expected stats-date-picker__ prefix)  wpcalypso/jsx-classname-namespace

✖ 5 problems (5 errors, 0 warnings)
```

The second one is of my making :).

**Comment by timmyc** [comment]
There is still quite a bit of cleanup to be done throughout stats to bring it up to current linting standards.  I can try to fix up the class names in the date picker - the sites-list, that might be a can of worms on this PR.

**Comment by stephanethomas** [comment]
@timmyc I rebased against `master` and corrected the linting error of my making.

It would be great to merge that pull request :).

**Comment by timmyc** [comment]
I found another issue while testing this out just now, visiting http://calypso.localhost:3000/stats/day ( no site selected ) results in an error

stats_ _trout_bummin_ _wordpress_com

**Comment by timmyc** [comment]
@stephanethomas one more change added in 4eebd51 - if you could test it out once more that would be great.

**Comment by stephanethomas** [comment]
I tested it and it works fine 👍.

**Pull request merged**
