### PR TITLE
Monthly plan upsell: Update translation formats

### PR DESCRIPTION
**Pull request by candy02058912**
Fixes https://github.com/Automattic/dotcom-forge/issues/2194

## Proposed Changes

image

* Fixed translation format so they value in `args` will be rendered

## Testing Instructions

Before

before

After
after

### CODE REVIEW

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/7952307

Thank you @candy02058912 for including a screenshot in the description! This is really helpful for our translators.

**Review by paulopmt1 — APPROVED** [review]
LGTM, thanks for fixing it @candy02058912!

**Review by lupus2k — APPROVED** [review]
LGTM!

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/7952307).

**Pull request merged**
