### PR TITLE
CurrentSite: get visible site count from user object

### PR DESCRIPTION
**Pull request by lamosty**
Currently, we are getting the visible sites count from the site items themselves. However, for that to work, they need to be already fetched. I think the correct way is to get the option from the user object which is loaded very early. This might also help if we decide to prefetch some sites before all sites are loaded.

## Testing

Site selector in sidebar should work as before. Try clearing local state and reloading the page.

Note: in 4f201df, I also removed some unnecessary space which I think is not needed anymore. It was added in #1609, but I can't repro the original bug.

### CODE REVIEW

**Comment by jsnajdr** [comment]
Are the counts always the same? I think you had some mismatches in your profile, where some sites were flagged as `inactive`. They were counted into the `user.site_count`, but were not part of the site list.

Is it possible that visible site count is similarly affected?

**Comment by lamosty** [comment]
> Is it possible that visible site count is similarly affected?

Yeah, you are right. Visible sites have the same properties, they can be active or inactive and we only fetch active ones while `visible_site_count` includes also inactive ones.

I'll close this one.

**Comment by jsnajdr** [comment]
@lamosty I think we should fix the backend endpoints in such a way that the site counts on the user object and the site list returnes from `sites` endpoint are always in sync. Then we can revisit this PR.

There are [places in Calypso](https://github.com/Automattic/wp-calypso/blob/master/client/my-sites/controller.js#L401) that use a `user.site_count === sites.length` check (or a similar one with visible sites) to figure out if the site list is up to date. That code is currently buggy.

I saw that "Finishing set up…" [notice](https://github.com/Automattic/wp-calypso/blob/master/client/my-sites/controller.js#L402) earlier today when playing with my local Calypso and testing the site selection logic.

**Comment by lamosty** [comment]
The thing is that we [explicitly fetch](https://github.com/Automattic/wp-calypso/blob/master/client/state/sites/actions.js#L87) only `active` sites while the site count from the `/me` endpoint works with all sites as expected. I think if we wanted to sync this, we should introduce a new parameter to the `/me` endpoint which would say "active sites only" or something. What if consumers of `/me` endpoint are relying on the fact that the counts include all the sites? We can't just change it.

**Comment by lamosty** [comment]
> There are places in Calypso that use a user.site_count === sites.length check (or a similar one with visible sites) to figure out if the site list is up to date. That code is currently buggy.

Yeah, I see. That should be definitely fixed.

**Pull request closed without merging**
