### PR TITLE
Remove the sell options step from site setup flow

### LINKED ISSUE #96566: Remove the sell flow
See parent issue.

This task will remove the sell flow. 

Image

### PR DESCRIPTION
**Pull request by p-jackson**
Fixes #96566

## Proposed Changes

* Removes the `options` step from the sell flow
* Keeps a 10% holdout (via the `calypso_onboarding_goals_holdout_20241126` experiment) on the old experience.

**The Regular Experience**

https://github.com/user-attachments/assets/aad555c2-dc3d-4236-9468-6a2f32e87800

**The Holdout Experience**

https://github.com/user-attachments/assets/f3b47db0-135c-43d9-867b-38168241e03a

## Why are these changes being made?

We are moving onboarding customisation our of the flow and into the launchpad. See p58i-irT-p2

## Testing Instructions

* Assign yourself to `control` or `holdout` group in explat 22115-explat-experiment
* Create a new site starting at `/start`
* Confirm back/forward navigation works throughout the flow
* Confirm that the "Give your site a name" task in the launchpad is correctly ticked
   * If you get the default experience it's always unchecked
      * Until you set it yourself
   * If you are in the holdout it's only checked if you complete the `options` step

The plan you test with shouldn't matter. If you test with a premium plan then BigSky might have appeared as an option after submitting the goals step. However since [the "sell" goals make you ineligible for BigSky](https://github.com/Automattic/wp-calypso/blob/4d865e5bb668b6919e8b62078d368e036038dd31/client/landing/stepper/hooks/use-is-site-big-sky-eligible.ts#L20-L21), it's not something that's testable.

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
    - [ ] For UI changes, have we tested the change in various languages (for example, ES, PT, FR, or DE)? The length of text and words vary significantly between languages. 
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Review by zaguiini — APPROVED** [review]
Works well.

**Comment by autumnfjeld** [comment]
We are waiting for review from @isatuncman-auto  to verify correct setup for the 10% holdout setup p1732594420795799-slack-C07H21B2W59

**Comment by aaronyan** [comment]
It looks like the previews use `treatment` in the current new goals experiment (22097-explat-experiment).

@p-jackson, will this change have the same effect for users in `control` for experiment 22097? I want to make sure this long-term holdout doesn't bias the currently running experiment.

**Comment by p-jackson** [comment]
> @p-jackson, will this change have the same effect for users in control for experiment 22097? I want to make sure this long-term holdout doesn't bias the currently running experiment.

The plan is to "finalize the current goals step test" at the same time that this new holdout rolls out.
p1732142110882399/1731454668.413339-slack-C07H21B2W59

**Review by necronet — APPROVED** [review]
ExPlat: Approved

**Comment by p-jackson** [comment]
> The plan is to "finalize the current goals step test" at the same time that this new holdout rolls out.

@aaronyan, just a follow up that @isatuncman-auto said it could actually be useful to leave `calypso_onboarding_goals_step_added_goals` running for a bit. (But it's up to Quake if it starts getting in our way). So we'll leave it running for a bit.

**Comment by p-jackson** [comment]
Launching pfYzsZ-F4-p2

**Comment by p-jackson** [comment]
For some reason CI didn't catch that this broke tests (since the default path removes steps that were under E2E tests). Fixing here https://github.com/Automattic/wp-calypso/pull/96858

**Pull request merged**
