### PR TITLE
Assembler - Remove hook to prefetch large images in patterns

### PR DESCRIPTION
**Pull request by miksansegundo**
Related to #75054

## Proposed Changes

* Removed the hook to prefetch large images

### Note about pattern rendering performance

In previous assembler versions, large images were a bottleneck for the pattern rendering because all patterns render at the same time but now the rendering is more optimized, only rendering 6-8 patterns initially per category, and patterns don't use the same mountains image repeatedly but a collection of ~20 images.

I'm not sure it makes sense to prefetch 20 images in the current assembler version. Should we pre-fetch only the large ones or the most repeated ones? What do you think @Automattic/lego?

I guess we'll have to test that to compare. I started creating the PR to prefetch 20 images and realized that maybe it doesn't make sense so I decided to remove the hook and then if we notice performance issues with the new patterns/images add it back. 

### About optimizing image size in patterns

Some patterns still use large images. Here is the list sorted by size:

Screenshot 2566-09-08 at 19 12 53

I think is a good idea to optimize the size of all heavy images with `ffmpeg` as @okmttdhr did last time for the patterns using mountains in `dotcompatterns`.

## Testing Instructions

* Access the assembler and verify it works as expected.

## Pre-merge Checklist

- [x] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [x] https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md for your changes?
- [x] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [x] Have you checked for TypeScript, React or other console errors?
- [x] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [x] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [x] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

**Review by arthur791004 — APPROVED** [review]
👍

**Review by fushar — APPROVED** [review]
Thanks for noticing this!

> Should we pre-fetch only the large ones or the most repeated ones

I skimmed through the images in the default set if initial 6-8 patterns in each category, and I don't think I see any image that's repeated more than 2-3 times, so I'm not sure if prefetching actually matters here.

> I think is a good idea to optimize the size of all heavy images with ffmpeg as @okmttdhr did last time for the patterns using mountains in dotcompatterns.

YESS, more than ~ 200kb for images which are meant to be replaced by the user anyway sounds too heavy; we need to account for users in low-speed internet area 😭

**Comment by miksansegundo** [comment]
Okay, I'll merge and then optimize the images using ffmpeg compression.

**Comment by miksansegundo** [comment]
I decided to create a follow-up issue https://github.com/Automattic/wp-calypso/issues/81579 and will leave the image optimization for later because the image sizes in patterns in `Assembler_priority` (the only patterns visible initially if a user doesn't click `Show more patterns`) are already below 200kb.

Image

**Pull request merged**
