### PR TITLE
Framework: Upgrade to react-redux v5, take 3

### PR DESCRIPTION
**Pull request by ockham**
Reverts Automattic/wp-calypso#10389

Third time's a charm :crossed_fingers:

### CODE REVIEW

**Comment by samouri** [comment]
Did we figure out why take two didn't work? What caused the `Uncaught TypeError: ReactDefaultInjection.inject is not a function` ?

**Comment by ockham** [comment]
We haven't yet. It wasn't limited to `ReactDefaultInjection`; there were some other unspecific errors (something like `cache.get() not found`), too (and which also happened with take one), which lead us to believe there might be an issue with the minifier.

Note that similar issues prompted us to [revert](https://github.com/Automattic/wp-calypso/pull/10414) #10409, though I think we were at least able to catch those errors at the `staging` level (as opposed to take two of this PR, which worked in `staging` but broke `production`).

**Comment by ockham** [comment]
Note -- we can only update to 5.0.2 for now but not 5.0.3 which is blocked by https://github.com/Automattic/wp-calypso/issues/11726.

**Comment by blowery** [comment]
best branch name ever btw

**Comment by blowery** [comment]
Confirmed the vendor hash changes on this branch vs the master commit it's based upon. So we should be breaking the hash when deployed to production.

Trying a test where I build the previous version in Docker, run it in a browser, then build this branch in docker and run that, without clearing browser cache.

**Comment by blowery** [comment]
Tested out fine.

**Comment by ockham** [comment]
Giving this another try 💣💥

**Pull request merged**
