### PR TITLE
Global sidebar mobile - add site card to top bar

### PR DESCRIPTION
**Pull request by Addison-Stavlo**
Related to # https://github.com/Automattic/dotcom-forge/issues/5752

## Proposed Changes

* Shows the site card in the global sites topbar for mobile
* removes the site card from the sidebar in this case and adds a "my home" link
* updates global masterbar header to be the same color as global sidebar.
* TODO - support the site badges in the card in this new location. Either in this PR or follow up...

Before:
Screenshot 2024-02-26 at 2 11 37 PM

After:
Screenshot 2024-02-26 at 1 25 14 PM

## Testing Instructions

* Run this branch of calypso.
* Visit global site view for an atomic site.
* Use a viewport width thinner than 782px.
* Verify the top bar is the same color as the global sidebar
* verify the top bar now contains the Site card in place of the "W" logo.
* verify this loads my home when clicked.
* open the sidebar, verify there is no site card. Verify there is a "my home" menu item.
* visit global site view in desktop width, there should be no "my home" item and the site card should be there.
* visit global view in mobile width, verify the "W" logo is still in the top bar.

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Comment by davemart-in** [comment]
Couple of minor things:

- [x] When you click the notifications link in the mobile top bar, it expands the notifications. If you click it again, it should hide notifications, but currently there is a flash and the notifications panel stays open.
- [x] Notice how there is more padding above the site card than below? Can we vertically center the site card so that it shows the same padding above and below?

CleanShot 2024-02-24 at 09 03 10@2x

**Comment by Addison-Stavlo** [comment]
> When you click the notifications link in the mobile top bar,

Thats not something new from this PR, but noted. We will want to fix it.

**Comment by Addison-Stavlo** [comment]
This is ready for another look (cc @davemart-in). Both items mentioned before should be resolved now. I have also update the badges to fit here:

Screenshot 2024-02-26 at 1 29 13 PM


mastebar-badges

**Review by davemart-in — APPROVED** [review]
Looking great!

**Pull request merged**
