### PR TITLE
Theme Sheets: added "hiding" class to hide content with a highly specific CSS class.

### PR DESCRIPTION
**Pull request by folletto**
This PR adds a single CSS rule to allow specific parts of the Theme Showcase sheet contents to be hidden.

### Why?

The old showcases don't have any notion about the screenshots of the current theme sheet, so the way to include them was to simply include the main screenshot in `the_content` body.
The new Calypso theme showcase sheets instead read the screenshots field from the API itself, and show it in a dedicated UI.
Adding the `<p class="theme__sheet-content-presentation-image">` paragraph to wrap that first image in `the_content` allows a flexible way to remove the image when we thing it's not needed, while also **keeping backward compatibility**.

_Note: the screenshot in the right column in Calypso is where we can then enhance the UI: longer screenshots, multiple screenshots, etc._

### How to test?

1. Open one of the themes that have already had the tag added (see list in the first comment below) with the code from this PR
2. Notice that the first image disappeared.
3. Check the old showcases https://theme.wordpress.com and https://wordpress.com/themes for the same theme and ensure the screenshot is still present, with no other visual issue.

Does this approach work? (apart from having to edit ~400 themes)

---

Before:

screen shot 2016-07-18 at 16 38 21

After:

screen shot 2016-07-18 at 16 38 57

### Notes

* WordPress has [wpautop()](https://codex.wordpress.org/Function_Reference/wpautop) function that adds the `p`s if missing. 
* `wpautop()` doesn't wrap if `p` is already present.

Test live: https://calypso.live/?branch=try/themes/sheet-hide-first-content-image

/cc @ianstewart

### CODE REVIEW

**Comment by folletto** [comment]
### How to update a theme with the CSS class?

1. Open the theme profile in the admin
2. Locate the initial screenshot, if it's same or similar to the one on the right in Calypso.
3. Add the class `theme__sheet-content-presentation-image` to the `p` containing that `img`, or add the entire `p` if not present.

### Themes already converted

* TwentyTen
* Rebalance

**Comment by omarjackman** [comment]
I tested this and it works well but my gut tells me that this class name should be renamed to something like `theme__sheet-content-hidden-presentation-image` to indicate that its being hidden in calypso. That then assumes that calypso is a special consumer of that wpcom api endpoint and its probably not a good idea to assume that. I'm just throwing this suggestion out there to create some buzz and maybe someone else might be able to offer up more concrete advice.

Another suggestion is to squash those two commits into one. The formatting fix isn't really necessary for the history.

**Comment by folletto** [comment]
Thanks for feedback! :)

And good questions!

> to indicate that its being hidden in calypso

I thought about this. My first name was even more explicit using `calypso-hidden`. But as you said, I didn't want to create a "special case". That's why I opted for a name that is sematic, identifying the scope of that image in all the showcases, but thus also allowing Calypso to target it.

I expect that at some point once we retire the old showcases we will simply remove that image altogether from the content body.

Makes sense?

> Another suggestion is to squash those two commits into one

Yep, I'll do before merging. 👍

**Comment by folletto** [comment]
Summary of the discussions I had so far:

1. It's not seen as a big change code-wise.
2. It's intensive in terms of editing all the theme descriptions.
3. It's the safest and most incremental approach (we can do very little, or cover every theme).
4. It's semantic and has no impact on the other showcases.
5. Potentially will make a future automated script to remove the first image in the content easier to write.

For these reasons, I'll merge this PR.

**Pull request merged**
