### PR TITLE
DO NOT MERGE: Trial for browserlists

### PR DESCRIPTION
**Pull request by blowery**
Just a check for `try/unify-browserlists`

### CODE REVIEW

**Comment by blowery** [comment]
Wow. 568kb to load reader, vs 619kb on master. Nice 51k savings.

**Comment by blowery** [comment]
cc @sgomes

**Comment by sgomes** [comment]
These are some really nice numbers! Thanks for the test, @blowery! Looks like it will be worth the effort to find a way of serving a modern build to modern browsers :)

**Comment by blowery** [comment]
Closing the trial

**Pull request closed without merging**
