### PR TITLE
Reader: release following intro banner to everyone

### PR DESCRIPTION
**Pull request by bluefuton**
Releases the Reader Following Intro banner for new users on all environments 🎉 

982adcc0-34d7-11e7-917e-41c614a9266d

### CODE REVIEW

**Comment by fraying** [comment]
Is this ready to go?

Has it been translated or will it only appear for En users?

Is it instrumented for stats? We'll want to know how often it's seen, dismissed (close link) clicked, and how often the Manage link is clicked. We'll also want to know if the users who act on it go on to be more engaged later. cc @aaronyan

**Comment by aaronyan** [comment]
LGTM! Tested on calypso.live and we're tracking the following:

**Comment by blowery** [comment]
Appears that it has been translated, at least for German and French. Any other important langs to check for launch?

**Comment by bluefuton** [comment]
> Appears that it has been translated, at least for German and French. Any other important langs to check for launch?

Yep. The component has existed in the codebase with the current wording for a while, so the main langs should be ready.

Stats were added in https://github.com/Automattic/wp-calypso/pull/13812. We have impressions, and clicks of the close button. We don't have one for the manage link, but I can add that now.

**Comment by aaronyan** [comment]
### Current stats:

Tested on calypso.live and we're currently tracking the following:
- **Intro is loaded:** `calypso_reader_following_intro_render`
- **Intro is clicked:** `calypso_page_view` with path=/following/manage
- **Site search is performed:** `calypso_page_view` with URL=https://calypso.live/following/manage?q=test
- **Site search result is followed:** `calypso_reader_site_followed` with URL=https://calypso.live/following/manage?q=test

### Suggested stats:

**Intro is Clicked:**
It would be nice to have an specific tracks event like `calypso_reader_following_intro_clicked`. Right now, there is no way to tell the difference between a user clicking the Intro link and them visiting /manage on their own volition.

**Site search is performed:**
I think each of the site results should have their own railcar. When a search is performed, the railcar will load the `calypso_traintracks_render` event with the search query and site result meta data.

**Site search result is followed:**
We could then watch if the user follows the site result with the railcar. If a follow occurs, the railcar would trigger a `calypso_traintracks_interact` event with `action=site_followed`.

**Comment by bluefuton** [comment]
Bienvenuto!

screen shot 2017-05-10 at 18 00 42

**Comment by aaronyan** [comment]
> Stats were added in #13812.

Awesome, thanks @bluefuton! Do we have stats for the Search on Manage site results in another PR?

**Comment by bluefuton** [comment]
> Do we have stats for the Search on Manage site results in another PR?

It's not really in the scope of Following Intro (just covers the banner), but your suggestions make very good sense 👍

**Comment by aaronyan** [comment]
Sounds good. It's nice to keep the scope bounded.

> Intro is Clicked:
It would be nice to have an specific tracks event like calypso_reader_following_intro_clicked. Right now, there is no way to tell the difference between a user clicking the Intro link and them visiting /manage on their own volition.

Can we add this stat to this PR? Or shall it be a separate one?

**Comment by bluefuton** [comment]
> Can we add this stat to this PR? 

Yep! Only a tiny change, so I've added it in: d55a691.

**Comment by aaronyan** [comment]
Awesome. Thank you @bluefuton!

**Comment by samouri** [comment]
Code LGTM. 🎉

**Comment by samouri** [comment]
I made a new account and everything worked as expected for me!

**Pull request merged**
