### PR TITLE
Editor: Block saving until TinyMCE initializes

### PR DESCRIPTION
**Pull request by aduth**
This pull request seeks to resolve an issue where if the user is able to press publish/update after a post has loaded but before TinyMCE finishes initializing, the post will be saved with empty content.

__Testing instructions:__

This is easiest to test with some sort of network throttling. If using Chrome, the Network tab [includes a throttling dropdown](https://developers.google.com/web/tools/chrome-devtools/profile/network-performance/network-conditions?hl=en#emulate-network-connectivity) to emulate a slower network connection.

Verify that Publish/Update remains disabled until after TinyMCE finishes initializing. Importantly, ensure that publish is available for new posts with some content and existing posts after both the post has loaded and TinyMCE has initialized, and in both of these scenarios when transitioning from a previous editor session (via the drafts drawer or masterbar new post button).

1. Navigate to the [post editor](http://calypso.localhost:3000/post)
2. Select a site, if prompted
3. Enter a title
4. Note that if TinyMCE has initialized (which at this point, it likely has), the Publish button is available
5. Save the draft or publish the post
6. Refresh the page with throttling applied
7. Note that while the post loads, the Publish/Update button is disabled, and that it continues to be disabled after the post has loaded but TinyMCE has not yet initialized
8. Note that the Publish/Update button is enabled after both of these conditions are satisfied

Ref: p4TIVU-3GA-p2, cc @alisterscott 

Test live: https://calypso.live/?branch=fix/editor-block-save-while-loading

### CODE REVIEW

**Comment by michaeldcain** [comment]
Tested - works as expected. LGTM.

**Comment by alisterscott** [comment]
Thanks for this. I tested this also, works well when throttled. Also I tested it generally in Firefox, IE11 and iOS and couldn't see any issues. 👍

**Comment by nylen** [comment]
Code looks good to me, though I think `getDefaultState` might be better called `getNewPostState` or something similar, to make the difference between that and `getInitialState` more clear.

No need to hold up merging for that, though - this fixes a potentially ugly bug for users.

**Comment by aduth** [comment]
@nylen : Yes, I agree it's not very clear. Looking closer, I think it's probably more reliable / accurate to set the uninitialized state in the `<PostEditor />` `componentWillMount`, since the issue arises as an effect of TinyMCE's need to [initialize after having been mounted](https://github.com/Automattic/wp-calypso/blob/e7f7b00903c72d915c337cd2026340a6436b997d/client/components/tinymce/index.jsx#L202-L310). This also avoids the need for a separate state getter.

Updated in 50a846e.

**Comment by nylen** [comment]
Looks good & works well 👍

**Pull request merged**
