### PR TITLE
Frictionless email subscriptions: Remove custom signup flow

### PR DESCRIPTION
**Pull request by oswian**
Related to https://github.com/Automattic/martech/issues/3390

## Proposed Changes

Removes the custom signup flow `/start/email-subscription` that is no longer used.

## Why are these changes being made?

For v2 of frictionless email subscriptions (pdvytD-Pp-p2), we are making use of the existing flow `/log-in/link/use` and no longer need the custom flow `/start/email-subscription` that was created for v1.

## Testing Instructions

No functional changes. @jeyip If there's anything you would recommend testing, please let me know 🙏 

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Comment by oswian** [comment]
Hey @jeyip! As the author of the v1 flow I'd like to get your expert 👀's on this cleanup -- anything I've missed?

**Comment by jeyip** [comment]
This is wonderful 🎉

**Review by jeyip — COMMENTED** [review]
Just taking a brief look and it seems like you covered the big things 🙂 :

- Handled steps-pure
- Handled flows-pure
- Removed the subscribe-email step
- Removed instances of relevant constants

I've got my focus elsewhere trying to wrangle some projects before deadlines, but I can do a formal review later this week if you'd like more confidence. In the meantime, I'd also recommend a few things ( which I assume you've already done :D )
- quick search for the `email-subscription` and `subscribe-email` slugs
- cross-checking changes made in the original PR
- testing the actual `/start/email-subscription` URL

If this is especially urgent lemme know and I can try to fit it in sooner

**Comment by oswian** [comment]
@jeyip Thanks for taking a look!

> - quick search for the email-subscription and subscribe-email slugs
> - cross-checking changes made in the original PR
> - testing the actual /start/email-subscription URL

👍 Yes all good on these checks.

**Pull request merged**
