### PR TITLE
Staging Sites: Handle lock expiration

### PR DESCRIPTION
**Pull request by kozer**
Related to https://github.com/Automattic/dotcom-forge/issues/5801

## Proposed Changes

This PR handles the lock expiration in the UI.

## Testing Instructions
1. Create a site and make it atomic.
3. Apply diff: D139827-code
4. Return early in `wp-content/mu-plugins/site-staging/class.site-staging.php` after line 155 `self::add_staging_site_creation_lock( $blog_id );` to trigger the error
5. Press the Create a staging site button.
6. Ensure that `/lock` endpoint should get polled, and it'll end up sending a nonnull response
7. After 20 seconds ensure that the response of lock is `null` and the UI shows again the Create staging site button.

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Comment by wojtekn** [comment]
With that change in place, UI gets unlocked after 60 seconds so I can trigger adding the staging site again.

However, it shows a "Staging site added." success message at the top right corner. Can we change it to "Could not add staging site. Please try again"?

Also, after lock is reset, browser keeps making requests to lock endpoint, receiving:

```
{"body":null,"status":204,"headers":[]}
```

Could we stop making those requests when lock is removed?

**Comment by kozer** [comment]
@wojtekn , I updated the PR. Right now, the lock endpoint is not getting polled, and the error message is correctly displayed.

Can you verify that this is the case?

**Comment by wojtekn** [comment]
@kozer thanks, I see it's not getting polled after Calypso concluded with the success or error result.

We are still polling `/wpcom/v2/sites/206672177/atomic/transfers/latest?_envelope=1` all the time, but it seems to be unrelated to this change.

I still notice unexpected behavior when I'm adding a staging site. The new staging site box appears for short time and then progress bar continues working until site is finally added:

https://github.com/Automattic/wp-calypso/assets/727413/1f102744-49e3-4b90-8d9c-910858ed4100

I can't observe it on staging/production.

**Comment by katinthehatsite** [comment]
When I test according to the test steps, I do see the correct error message on my end and the button becomes available again. For this step:

> Ensure that /lock endpoint is called, and the response is not null

What I see that the first time, when it is called, it is `null` intially but then it changes on the second request. Is that what you are expecting?

Screenshot 2024-03-01 at 11 14 03 AM

**Comment by kozer** [comment]
@wojtekn , this should not happening anymore. Please take a look.

> What I see that the first time, when it is called, it is null intially but then it changes on the second request. Is that what you are expecting?

@katinthehatsite I noticed that as well. I updated the description to reflect that: "The `/lock` endpoint should get polled, and it'll end up sending a non null response"
This is because, when we call `addStagingSite`, the lock is getting created, but in the future. This is why the enpoint doesn't return a non null value initially.

**Review by wojtekn — APPROVED** [review]

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/11519354

Some locales (Hebrew, Japanese) have been temporarily machine-translated due to translator availability. All other translations are usually ready within a few days. Untranslated and machine-translated strings will be sent for translation next Monday and are expected to be completed by the following Friday.

Hi @kozer, could you please edit the description of this PR and add a screenshot for our translators? Ideally it'd include this string: `Could not add staging site. Please try again.`

Thank you in advance!

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/11519354).

**Pull request merged**
