### PR TITLE
Reader Recent Feed Overhaul: Add screen reader navigation

### PR DESCRIPTION
**Pull request by allilevine**
Related to https://github.com/Automattic/loop/issues/229

## Proposed Changes

* Focus the post column when a post is selected.
* Change the back button to be visible to screen readers on wide screen resolutions.
* Focus the item in the posts list when the back button is clicked.

https://github.com/user-attachments/assets/cd59fd77-d0d3-454b-a919-d4e624adda82

Screen Shot 2024-12-04 at 4 35 27 PM

## Why are these changes being made?

* pe7F0s-2iv-p2

## Testing Instructions

* Turn on a screen reader. On a Mac: press Cmd + F5, then open Safari.
* Go to /read?flags=reader/recent-feed-overhaul
* Navigate through the middle column of posts and check that you can select a post by pressing enter or following the screen reader's directions.
* When you select a post, it should be focused in the right column.
* When you start tabbing or navigating in the right column, the first element should be a button with label "Return to the list of posts."
* Press enter or follow the screen reader's directions to click the button.
* The item in the posts list should be focused again.
* Regression test that the Back button is still visible on mobile and takes you back to the posts list. 
* Regression test that the Back button is still visible and takes you back to the posts list in the current stream view (/read without the feature flag).

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
    - [ ] For UI changes, have we tested the change in various languages (for example, ES, PT, FR, or DE)? The length of text and words vary significantly between languages. 
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Comment by mehmoodak** [comment]
Thanks for working on this. I have tested these changes and have following feedback:

1. It seems that the shortcut to toggle the Screen Reader on MacOS is actually `CMD + F5`. It would be helpful to correct this typo in the "Testing Instructions" section.

2. After testing these changes on both Firefox and Brave, I found that neither browser announced the newly introduced shortcuts as expected when using a screen reader.

3. I discovered that pressing `Alt + L` on post content toggles liking or unliking the post.

4. I have also tested the keyboard navigation on `trunk` and I think we can fix these navigation issues without relying on additional shortcuts.

    a. Selecting posts from list view via `Enter` works as intended and doesn't require any changes.
    
    b. To navigate back to the list view, we could introduce a hidden button called "Return to List" in post content, which would become the first element focused during keyboard navigation.

**Comment by mehmoodak** [comment]
> The issue I'm seeing is, how do you switch focus to the post once it's selected?

Via JS `.focus()` method.

```javascript
document.querySelector('article.reader-full-post__story').focus(); 
```

**Comment by allilevine** [comment]
> > The issue I'm seeing is, how do you switch focus to the post once it's selected?
> 
> Via JS `.focus()` method.
> 
> ```js
> document.querySelector('article.reader-full-post__story').focus(); 
> ```

I find it strange to make that decision for the user, but I guess in this context (the post has been selected) it could make sense. I'll try it out.

**Comment by allilevine** [comment]
@mehmoodak I pushed up the new approach. Feel free to modify it while I'm AFK.

**Review by eoigal — COMMENTED** [review]
This isn't working as I'd expect. When I select the post, it seems to highlight a button that's not visible and it doesn't appear to do anything if I press enter, if I tab to next option I will be returned to list of posts in middle column.

https://github.com/user-attachments/assets/48781059-7f06-4d83-83ae-4b08692c84ae

**Comment by allilevine** [comment]
> This isn't working as I'd expect. When I select the post, it seems to highlight a button that's not visible and it doesn't appear to do anything if I press enter, if I tab to next option I will be returned to list of posts in middle column.

@eoigal The invisible button is part of the approach -- it can't be seen when you're not using a screen reader, but it's available for the screen reader to click. Enter should work though. Are you testing in Safari? Does Control + Option + Space click the button?

**Comment by allilevine** [comment]
I asked for more feedback here: p4vt7e-j1-p2

**Comment by holdercp** [comment]
Made a quick vid showing some of the issues I experienced with VoiceOver on MacOS.

https://github.com/user-attachments/assets/47691bf8-18d4-4e83-b2b1-c451c417d495

**Comment by allilevine** [comment]
> Made a quick vid showing some of the issues I experienced with VoiceOver on MacOS.

@holdercp Thanks for testing! We're using the List view now, which renders a `ul` and `li` children:

Screen Shot 2024-12-02 at 3 32 59 PM

Do you see the same issue when using a screen reader with the DataViews examples? https://wordpress.github.io/gutenberg/?path=/docs/dataviews-dataviews--docs

Otherwise I can open an issue to work on the list screen reader navigation.

For the de-selected item, looks like there was an existing `setSelectedItem( null );` in the `onClose` function, before this PR. That's because we hide the selected item on the mobile view, so that the list is visible. I added a check so that we only remove the selection on mobile.

Let me know if I missed any other issues you mentioned!

**Comment by holdercp** [comment]
@allilevine
1. The setting the selected post to `null` on close has been fixed.
2. There are still issues with the screen reader and general keyboard navigation.

Thanks for linking to the storybook for the DataViews. I was able to confirm that the screen reader experience has issues when the _list_ view is used. The table view works as expected (using the SR navigation keys worked liked I would expect and I was able to visit each row). Using regular keyboard navigation (<Tab> then <Arrow> for nav, <Enter> and <Space> for selection), however, does seem to work correctly for table and list views.

In our case, regular keyboard navigation _doesn't_ work so I think we're either configuring something incorrectly or we're just using DataViews in a way that was not intended. I see that the Storybook examples have separate actions vs. the whole item being the action, which might be related.

Here's a vid showcasing what I'm seeing:

https://github.com/user-attachments/assets/d88d563e-d943-4736-b999-e36a1add91d5

**Comment by dcalhoun** [comment]
I also wanted to share a few content hierarchy suggestions that might improve content navigation for users relying upon screen readers (SR). Much like most accessibility design, this is all very subjective, so feel free to disregard. I included a screenshot below to provide additional context. 

<details><summary>Suggestsions screenshot</summary>
<p>

reader-content-hierarchy-suggestions

</p>
</details> 

* Avoid wrapping the "Recent" heading and sibling navigation in nested "banner" elements. This is confusing and increases the number of steps for navigating down into this grouped element. 
* Consider marking the post list as a role "navigation" or "aside" to simplify moving SR focus to the element, much like the far left side bar is marked as "navigation."
* We should fix whatever element structure is preventing moving focus to the "main" element with a SR. When I attempt to do so, focus is moved the "share" UI that is affixed to the bottom of the screen. 

If case it is helpful, I'll share that I navigated using VoiceOver in a few different ways: 

- <kbd>Option</kbd>+<kbd>Control</kbd>+<kbd>Shift</kbd>+<kbd>[Up|Right|Down|Left]</kbd> will navigate between/into/out of content "groups." 
- <kbd>Option</kbd>+<kbd>Control</kbd>+<kbd>[Up|Right|Down|Left]</kbd> will navigate between individual content elements, depending on the context and settings. 
- <kbd>Option</kbd>+<kbd>Control</kbd>+<kbd>Space</kbd> will "activate" the selected element, triggering the relevant event handler.

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/17046532

Some locales (Hebrew, Japanese) have been temporarily machine-translated due to translator availability. All other translations are usually ready within a few days. Untranslated and machine-translated strings will be sent for translation next Monday and are expected to be completed by the following Friday.

Hi @allilevine, could you please edit the description of this PR and add a screenshot for our translators? Ideally it'd include this string: `Return to the list of posts.`

Thank you in advance!

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/17046532).

**Pull request merged**
