### PR TITLE
A/B Tests: Load assignments from API (take 2)

### LINKED ISSUE #20097: ABTests: load existing variations from the backend into the state
When we run an AB Test, we save logged-in users assigned variation to the backend (user attribute), and in localStorage (using `store.set`).

If that same user is evaluated for the test again, but with a clean localStorage (say, new browser on another device, or just localStorage turned off), we randomly set their variation, and save it again.

This obviously can mess with the test results and leads to non-uniform experience for the users.

#15169 introduced a method to assign variations by user IDs, but it's not the default, and it would still be safer to load existing variations from the backend (cc @aaronyan)

We should load all the current user test variations before assigning them.
The data should probably be included in the user bootstrap load so that it doesn't delay any tests.

cc @sirino

### PR DESCRIPTION
**Pull request by jsnmoon**
Take 2 of #21709, fixes #20097.

This change fetches the user's assigned A/B test variations stored as user attributes from the wpcom REST API. In addition to changes introduced by #21709, this PR also [properly sets `this.data` in `lib/user/user.js` during instantiation of the User object](https://github.com/Automattic/wp-calypso/pull/22149/commits/bed557e5a515c009a66dd3af80380f3a046525ca). Not setting `this.data` in the initialization caused outages on `/log-in` and `/start` for logged-out users as well as canary test failures.

#### Testing instructions

1. Check out locally (`fix/load-ab-variations-take-2`) and start your server.
2. Set your localStorage debug flag to `calypso:user` like so:  
```javascript
localStorage.debug = 'calypso:user';
```
3. Open the [homepage](http://calypso.localhost:3000/) while logged in.
4. Verify that you see the following debug lines in your console:
```
calypso:user Initializing User
calypso:user User bootstrap disabled, checking localStorage
calypso:user Getting user from api
calypso:user User successfully retrieved
```

5. Ensure that localStorage has been populated with expected values. With my user, it looks like the following: (Please note that A/B test variation assignments will vary per user)

``` javascript
> localStorage.ABTests
"{"skipThemesSelectionModal_20170904":"show"}"

> JSON.parse(localStorage.wpcom_user).abtests
{ skipThemesSelectionModal_20170904: "show" }
```

6. Repeat step 3 logged out and ensure that the pages render properly. Also ensure that the [login](http://calypso.localhost:3000/log-in) and [start](http://calypso.localhost:3000/start) pages render properly.

7. If you'd like, you can also spin up a docker image of this change `npm run build-docker; and npm run docker;` and repeat the above steps. Doing so would enable you to test this change in a production-like setting and yield the following debug lines in your console:
```
calypso:user Initializing User
calypso:user Bootstrapping user data: { ... }
```

### CODE REVIEW

**Comment by jsnmoon** [comment]
Marked for review to trigger canary tests. Please hold off on reviewing the changes.

**Comment by brbrr** [comment]
I've tested on Chrome/Safari on Mac OS & MSEdge on Win10.
Everything was fine, user and its AB tests were successfully fetched from API. While logged in I see exact same debug messages.

While logged out I see these (tested on `/`, `/start`, `/log-in`):
```
calypso:user Initializing User +0ms
browser.js:112 calypso:user User bootstrap disabled, checking localStorage: +22ms false
browser.js:112 calypso:user Getting user from api +0ms
browser.js:112 calypso:user The user is not logged in. +2s
```
Which seems expected output. 

Though, I was a bit confused with step 6: should I re-try all steps from (3-5) or just visit mentioned pages and check debug output? Or should I test login and signup flows?

I've tested both login and signup flows - all looks good 👍

**Comment by designsimply** [comment]
I tested locally as a regular test user unproxied and I see something similar to @brbrr where it mentions the user bootstrap is disabled:

```
calypso:user Initializing User
calypso:user User bootstrap disabled, checking localStorage
calypso:user Getting user from api
calypso:user User successfully retrieved
```

`localStorage.ABTests;` output looks like this in the console:

```
"\"abtest_unlimitedThemeNudge_20171016\":\"hide\",\"abtest_promoteYearlyJetpackPlanSavings_20180124\":\"original\"}" 
```

screen shot 2018-02-06 at tue feb 6 10 14 53 am
<sup>Seen at http://calypso.localhost:3000/ using in the console of Firefox 58.0.1 on macOS 10.13.3.</sup>

Viewing http://calypso.localhost:3000/log-in while logged out had several console warnings that seem to mostly have to do with loading the local site via http:

screen shot 2018-02-06 at tue feb 6 10 18 10 am
<sup>Seen at http://calypso.localhost:3000/log-in using Firefox 58.0.1 on macOS 10.13.3.</sup>

http://calypso.localhost:3000/start looked fine.

**Comment by abidhahmed** [comment]
I've tested on calypso.live while logged in/out on all 3 pages (`/`, `start`, `log-in`) and see the expected debug log.

Tested on Chrome 64/Firefox 58.

**Comment by rachelmcr** [comment]
I tested locally while logged in, both proxied/a8c user and unproxied/non-a8c user, and I got unexpected results when I went through the `/start` page while logged in.

When I started on the logged-in homepage, I saw this output:

```
calypso:user Initializing User +0ms
calypso:user User bootstrap disabled, checking localStorage: +17ms 
calypso:user Getting user from api +2ms
calypso:user User successfully retrieved +3s
```

I then checked `localStorage.ABTests` and saw the expected values, for example:

```
"{"abtest_unlimitedThemeNudge_20171016":"hide","abtest_checklistThankYouForFreeUser_20171204":"show"}"
```

I then visited `/start` (still logged in) and created a new site. At the end of the site creation flow, I saw this output:

```
calypso:user Getting user from api +43s
calypso:user User successfully retrieved +782ms
```

When I checked `localStorage.ABTests` again, I saw a new value appended to the end that didn't look correctly formatted (no `abtest_` at the beginning):

```
"{"abtest_unlimitedThemeNudge_20171016":"hide","abtest_checklistThankYouForFreeUser_20171204":"show","checklistThankYouForFreeUser_20171204":"show"}"
```

I also now see an unexpected `abtest_` at the bottom of my user's list of WP.com A/B Test Allocations on my user report card, which seems likely related.

**Comment by jsnmoon** [comment]
@brbrr, @designsimply, @abidhahmed, and @rachelmcr:

Thank you very much for testing! I've updated testing instructions to clarify, but no further testing seems necessary at this point. FWIW: It's very reasonable for each of us to have different A/B test variation assignments, so the findings look very reasonable. 

> When I checked localStorage.ABTests again, I saw a new value appended to the end that didn't look correctly formatted (no abtest_ at the beginning)
> I also now see an unexpected abtest_ at the bottom of my user's list of WP.com A/B Test Allocations on my user report card, which seems likely related.

It looks like I introduced a bug with the backend portion of this feature release; A/B test names stored in localStorage should not have `abtest_` prepended to the key names. I will hold off on releasing this feature until a backend fix is in place.

🙇

**Comment by jsnmoon** [comment]
Update: A backend fix has been released to production last night. I have updated the testing instructions for your reviewing convenience.

Backend fix: `D9990-code`.

**Comment by aaronyan** [comment]
Works wonderfully @jsnmoon! I've tested as a logged in user, observed the `user` being successfully retrieved from the API, and the AB tests were assigned the same variation every time I deleted `localStorage.wpcom_user` and `localStorage.ABTests`. Great job on this!

I've looked through your code, and it looks good to me! But I would double check with a Calypso veteran just to make sure.

**Comment by seear** [comment]
Tested locally with docker. I see the abtest data in the bootstrapped user object:
screen shot 2018-02-08 at 20 37 42


And routes /log-in and /start are fine both logged-in and logged-out.

Nice work 👍

**Comment by alisterscott** [comment]
I know this is merged, but I have a question about how this works.

If I set these locally using the wpcalypso icon in calypso, or just using direct `window.localStorage.setItem()` statements in the browser console, should these be set against the user? 

We do this in our e2e tests, but these aren't being persisted and immediately overwritten by the API on page refresh. Is this expected behaviour?

**Pull request merged**
