### PR TITLE
Plans: Migrate images to webpack

### LINKED ISSUE #34634: Plans: Icons still using incorrect color
#### Steps to reproduce
Starting at URL: https://wpcalypso.wordpress.com/plans/my-plan/[site]

#### What I expected
To not be seeing any icons with green in them. I think we updated them before, but I couldn't find the PR for it.

#### What happened instead
Icons still using green

#### Browser / OS version
Mac OS Mojave 10.14.2
Google Chrome Version 75.0.3770.100

#### Screenshot / Video
Screenshot 2019-07-12 13 15 26

### PR DESCRIPTION
**Pull request by sixhours**
#### Changes proposed in this Pull Request

* Migrates all Plans-page related images to webpack to fix #34634 and #34641 
* Some of these images are used in other areas of Calypso, so I've migrated those instances as well.
* Hashed images in the source look like this:

Screen Shot 2019-07-25 at 3 24 20 PM

#### Testing instructions

* Switch to this PR. Check the source of all illustrations on the following sections to ensure they've been migrated properly; they'll have a hash at the end of the URL like the one in the screenshot above:

* Plans page (`/my-plan`) for all WP.com plan types (Blogger, Personal, Premium, Business, eCommerce)
* Jetpack Plans page (`/my-plan`) for all Jetpack plan types (Personal, Premium, Professional)
* Checkout thank-you screen for all WP.com and Jetpack plan types
* "Use your own domain" images under `/domains/add` and in signup under `/start/domains`
* Jetpack Activity Log - image in the intro banner at the top of the page

### CODE REVIEW

**Comment by arunsathiya** [comment]
I am traveling without access to a computer at the moment and, I am AFK until the 6th of August. I will excuse myself as a reviewer here, but best trying to get more eyes on this PR before pushing it out.

**Comment by lcollette** [comment]
I've not found any broken images and all images appear hashed.

**Comment by donpark** [comment]
Let's merge this and deal with blindspots if any later.

**Comment by stephanethomas** [comment]
@sixhours: it looks like this change prevents some images from loading in non-production environments. For example, [this one](https://wordpress.com/calypso/images/illustrations/custom-domain.svg) would lead to a `Page not found` in staging whereas it displays well in production. Could you look into that when you get the chance?

**Comment by sixhours** [comment]
> @sixhours: it looks like this change prevents some images from loading in non-production environments. For example, this one (used here) would lead to a Page not found in staging whereas it displays well in production. Could you look into that when you get the chance?

Hmm, it looks like that image was migrated, so the email management screen is referencing a path that no longer exists. I tried to search for any instances of images that were moved during this migration to update them all, but it's inevitable some would get missed in a PR this size. Nice find! 😅 

#36000 should fix it up!

**Pull request merged**
