### PR TITLE
Add missing features to the new Jetpack plans

### PR DESCRIPTION
**Pull request by monsieur-z**
### Changes proposed in this Pull Request

In this PR, we've made sure that new Jetpack plans included legacy plans features that were still relevant.

### Implementation notes

- I've tried to match the table of features mentioned in the testing instructions below
- I didn't include features that are available for all plans

### Testing instructions

- Get the list features that's linked in the _Project Quick References_ card
- Check that the added features make sense

### CODE REVIEW

**Review by elliottprogrammer — APPROVED** [review]
Yep, the features make sense with regard to the features list. 👍 
LGTM!

**Comment by rcanepa** [comment]
@monsieur-z, the list of features seems to be correct but I wonder if `getHiddenFeatures` is the right place for them. Legacy plans seem to include them in a different key called `getPlanCompareFeatures`. To give you an example, here is Jetpack Premium's `getPlanCompareFeatures`: https://github.com/Automattic/wp-calypso/blob/236926e752a13c741e427f0aafab9f4dcbac9796/client/lib/plans/plans-list.js#L892-L909.

And these are its hidden features (`getHiddenFeatures`):
https://github.com/Automattic/wp-calypso/blob/236926e752a13c741e427f0aafab9f4dcbac9796/client/lib/plans/plans-list.js#L929-L936

**Comment by monsieur-z** [comment]
> @monsieur-z, the list of features seems to be correct but I wonder if `getHiddenFeatures` is the right place for them. Legacy plans seem to include them in a different key called `getPlanCompareFeatures`.

@rcanepa, features returned by `getPlanCompareFeatures` are used to populate the plans table in the legacy page. You can see in the definition of `planHasFeature` that the check is done with `getHiddenFeatures` as well, which is what interests us here.

**Comment by rcanepa** [comment]
> > @monsieur-z, the list of features seems to be correct but I wonder if `getHiddenFeatures` is the right place for them. Legacy plans seem to include them in a different key called `getPlanCompareFeatures`.
> 
> @rcanepa, features returned by `getPlanCompareFeatures` are used to populate the plans table in the legacy page. You can see in the definition of `planHasFeature` that the check is done with `getHiddenFeatures` as well, which is what interests us here.

Great! Thanks for explaining it.

**Pull request merged**
