### PR TITLE
Add/cover pullquote block e2e tests

### PR DESCRIPTION
**Pull request by dpasque**
#### Changes proposed in this Pull Request

Adds some E2E coverage for Pullquote and Cover blocks in the editor. Cases focus on taking the blocks through preview and publish, and various methods of data population and transformation.

New specs:
- `specs-gutenberg/blocks/wp-gutenberg-cover-block-spec.js`
- `specs-gutenberg/blocks/wp-gutenberg-pullquote-block-spec.js`

Sample output of the new scripts:

    [WPCOM] Calypso Gutenberg Editor: Pullquote Block (mobile)

    Full workflow to preview and publish post with Pullquote @parallel
    Logging in as e2eflowtestinggutenbergsimple
      ✓ Can log in (28547ms)
      ✓ Can add pullquote to post (4195ms)
      ✓ Can add quote text to pullquote (2661ms)
      ✓ Can add citation text to pullquote (606ms)
      ✓ Can see quote and citation in preview (5420ms)
      ✓ Can close post preview (2278ms)
      ✓ Can see quote and citation in published post (6275ms)

    Block transforms to and from Pullquote
    Logging in as e2eflowtestinggutenbergsimple
      ✓ Can log in (29206ms)
      ✓ Can add text to Paragraph (2623ms)
      ✓ Can transform Paragraph to Pullquote (3576ms)
      ✓ Transformed Pullquote has the text as its quote text (40ms)
      ✓ Can add citation to new transformed Pullquote (473ms)
      ✓ Can transform the Pullquote back into Paragraph block(s) (3644ms)
      ✓ Both the quote and citation text are kept across transform (77ms)

    14 passing (2m)

    [WPCOM] Calypso Gutenberg Editor: Cover Block (desktop)

    Full workflow to preview and publish post with Cover @parallel
    Logging in as e2eflowtestinggutenbergsimple
      ✓ Can log in (27390ms)
      ✓ Can add Cover to post (4429ms)
      ✓ Can upload an image to the Cover (4526ms)
      ✓ Can add title text to Cover image (752ms)
      ✓ Can see image and title text in preview (8232ms)
      ✓ Can close post preview (2306ms)
      ✓ Can see image and title text in published post (6740ms)

    Other ways to set Cover background @parallel
    Logging in as e2eflowtestinggutenbergsimple
      ✓ Can log in (29399ms)
      ✓ Can add Cover to post (4343ms)
      ✓ Can use initial swatches buttons to set a background color (611ms)
      ✓ Can use Add Media toolbar button to launch Media Library (1430ms)
      ✓ Can use Media Library to insert background image (6836ms)

    12 passing (2m)

#### Testing instructions

Run the specs:

- [ ] `BROWSERSIZE=desktop node_modules/.bin/mocha specs-gutenberg/blocks/wp-gutenberg-cover-block-spec.js`
- [ ] `BROWSERSIZE=desktop node_modules/.bin/mocha specs-gutenberg/blocks/wp-gutenberg-pullquote-block-spec.js`
- [ ] `BROWSERSIZE=mobile node_modules/.bin/mocha specs-gutenberg/blocks/wp-gutenberg-cover-block-spec.js`
- [ ] `BROWSERSIZE=mobile node_modules/.bin/mocha specs-gutenberg/blocks/wp-gutenberg-pullquote-block-spec.js`

##### Questions / Looking for feedback

To manage the scope of the PR, I tended towards being cautious towards refactoring other shared library code. Let me know if you think it would be worth going after those refactors a bit more aggressively in this PR. Namely, I'm 👀 at the existing `image-block-component.js`, which I pulled a lot of the shared functionality out into `media-block-flows.js`, but didn't cutover at the moment.  

Speaking of which, pulling out the shared media block behavior to a separate flows class seemed the best option because the inheritance tree was already getting pretty long on the block components, but I waffled back and forth a lot on what was the best way to do that. So let me know if the current implementation feels clunky or doesn't seem like it will grow well!

### CODE REVIEW

**Comment by dpasque** [comment]
cc @worldomonation

**Comment by dpasque** [comment]
Ready for review!

**Comment by worldomonation** [comment]
Hi @dpasque 👋 

I have triggered the entire suite of unit tests from our end.
Running your tests locally, it worked well and as expected. Good work!

I particularly like that you took the initiative to refactor existing code.
Furthermore, excellent that you included docstrings on all functions and within code blocks where you felt they were warranted. It helped me understand some clever workarounds you have implemented (eg. `focusBlock`).

Overall, looks great and thanks for posting the PR!

**Comment by worldomonation** [comment]
One extra question - I'd like to know if your any of your automated tests and/or the process of automating the cases turned up a bug that you had not found previously?

Not a trick question, its more of a curiosity of mine.

**Comment by dpasque** [comment]
> One extra question - I'd like to know if your any of your automated tests and/or the process of automating the cases turned up a bug that you had not found previously?
> 
> Not a trick question, its more of a curiosity of mine.

Great question! I too think this is a really interesting point of reflection when working on adding automated cases.  

Nothing this time, although I definitely learned more about the rules governing the DOM of the editor, and some of its idiosyncrasies (I'm thinking mostly of the trick of getting the toolbar to appear without relying on a certain amount of mouse movement).  

I think a big reason why no new bugs came out of the test implementation process was because I had already hit all those workflows pretty hard in exploratory testing. I think it would be an interesting comparison to take two blocks I hadn't worked with before in exploratory testing and added E2E coverage for them, and see what bugs came out of that process!

**Comment by worldomonation** [comment]
This was a trial project, not intended for actual merge. Let's close this for now, but the approaches used here by @dpasque can be applied to the ongoing Playwright project when tests are developed for these blocks 👍

**Pull request closed without merging**
