### PR TITLE
VideoPress Intent: record waitlist in Crowdsignal

### PR DESCRIPTION
**Pull request by jgcaruso**
Related to # https://github.com/Automattic/greenhouse/issues/1834

## Proposed Changes

* add a POST request to crowdsignal to record email addresses in a survey
* add a success message after email is submitted
* add validation to the email field

| email field | success message |
| - | - |
| SCR-20230830-iuap | SCR-20230830-iuny |

## Testing Instructions

* `yarn && yarn start`
* `/setup/videopress`
* Open the Channels or "upload a Video" items
* enter an invalid email, try to submit. You shall be stopped
* enter a valid email, try to submit. You should see a "thank you" message
* Check the survey results to see that your valid email was recorded
* close the modal or refresh the page, reopen the same item, the waitlist should still show the "thank you" message
* open the other Item, the waitlist shouldn't show the "thank you" message because it has not been submitted yet (unless you already did previously)

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

**Review by thedebian — CHANGES_REQUESTED** [review]
I think there's a couple more things to add:

Blocker :
* if I enter my email and then close the modal, I see the waitlist field again, we should either store the state of the waitlist in the session or bubble up the state so we only see the email field (on any of the modals) if we didn't submit our email

Nice to have:
* The "Join the waitlist" button can probably have a cursor: pointer, and might be disabled/grayed out when we can't submit 
* The "thank you" message might be transformed to a confirmation message like "Thanks for joining the waitlist! We'll keep you updated."

**Review by pgk — APPROVED** [review]
Worked well!

> if I enter my email and then close the modal, I see the waitlist field again, we should either store the state of the waitlist in the session or bubble up the state so we only see the email field (on any of the modals) if we didn't submit our email

I am ok with adressing that separately

**Comment by jgcaruso** [comment]
> * The "Join the waitlist" button can probably have a cursor: pointer, and might be disabled/grayed out when we can't submit

The pointer is there when the input is valid, its missing only when invalid because the button is disabled. We tried the styling the button as "grayed out" when it was disabled but it made the field look less enticing. If it stays yellow it "pops" more. Unless we don't want it to be a main call to action I think it should stay yellow.

> * The "thank you" message might be transformed to a confirmation message like "Thanks for joining the waitlist! We'll keep you updated."

Yeah the message can probably be better, I'll update it.

**Comment by jgcaruso** [comment]
> Worked well!
> 
> > if I enter my email and then close the modal, I see the waitlist field again, we should either store the state of the waitlist in the session or bubble up the state so we only see the email field (on any of the modals) if we didn't submit our email
> 
> I am ok with adressing that separately

It was a quick change so I went ahead and did it. I'm storing separate session items for each source.

**Review by thedebian — APPROVED** [review]
👨‍🍳 💋

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/8834212

Thank you @jgcaruso for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/8834212).

**Pull request merged**
