### PR TITLE
If connecting via WooCommerce Services, pre-select the free Jetpack plan

### PR DESCRIPTION
**Pull request by nabsul**
If the Jetpack connect query string contains `from: woocommerce-services`, we want to auto select the free plan and take the user back to their self-hosted site as soon as they authorize.

While I was browsing the code I saw a few instance of the function `redirectWithoutLocaleifLoggedIn`. This looks like a typo to me so I went ahead and fixed it.

Note: Right now the plans page is still shown for a brief moment before redirecting to wp-admin. I think it would be nicer if it just immediately went to wp-admin without first showing this page. However, since this might affect other flows, I decided not to make this change.

To Test:
- Install Jetpack, WooCommerce and WooCommerce services
- Disconnect Jetpack
- Try connecting it from the Jetpack dashboard: It should ask you to select a plan
- Try connecting from the WCS banner (shown on the plugins page for example): It should skip the plans page

### CODE REVIEW

**Comment by v18** [comment]
Works as expected for me 🎉

> I think it would be nicer if it just immediately went to wp-admin without first showing this page.
> However, since this might affect other flows, I decided not to make this change.

I suggest that we look into the other flows to make sure they wouldn't break, and take the user directly to wp-admin without showing the plans page, as you suggested.

Right now, it's unclear that the user should wait on the plans page for it to redirect automatically, and it would be a better experience to completely eliminate the plans page instead of only pre-selecting a plan. When I was running through it the first time, I thought I had to select a plan and had time to click on the button.

**Comment by nabsul** [comment]
> I suggest that we look into the other flows to make sure they wouldn't break, and take the user directly to wp-admin without showing the plans page, as you suggested.

I agree, there's probably an easy win for this.

The cleanest solution would be to make this change for all `JETPACK_CONNECT_SELECT_PLAN_IN_ADVANCE` events. 

@johnHackworth @lezama Do you see any harm in skipping that momentary view of the plans screen if one is already pre-selected?

**Comment by nabsul** [comment]
@v18 (and/or @jeffstieler ) I think I've run out of time to get skipping the plans page working. I've tried editing `jetpack-connect/auth-logged-in-form.jsx::render()` and `jetpack-connect/plans.jsx`. These two still seem like the right places to make the changes, but the changes I tried caused massive errors.

I will pass the torch onto @v18 :-)

**Comment by v18** [comment]
Baton received, @nabsul 🥇

**Comment by lezama** [comment]
also let's ping @ebinnion :)

**Comment by ebinnion** [comment]
I've dealt with this for the SSO flow, where we auto-authorize users after they SSO for the first time.

Here is an example of how I did it:

https://github.com/Automattic/wp-calypso/blob/master/client/jetpack-connect/auth-logged-in-form.jsx#L107

At the time, one extra conditional seemed ok. But, if we continue to add to this, we may want to abstract it.

**Comment by sirreal** [comment]
Really good [input and questions](https://github.com/Automattic/wp-calypso/pull/15741#pullrequestreview-48541421) from @tyxla 👏 

A note, we could quickly push through the typo fixes (thank you!) if they were handled in a separate PR. That would also allow us to review and study the "meat" of this PR more quickly and simply.

**Comment by richardmuscat** [comment]
@tyxla / @sirreal / @v18 / @nabsul -- rather than remove the plans selection can we instead customize in a way that says "Do you have a backup of your super important ecommerce site? No? Bad webmaster. Buy a plan at a special discount for Woo customers!"

Also, do you currently check for whether the site _already_ has a paid plan? In that case we wouldn't want to show it at all.

**Comment by v18** [comment]
@richardmuscat yes, I think it would also be our preference in the long-term to customize the plans page. We haven't gone down that route _yet_ for a couple of reasons:
1. The Woo-related plans aren't yet in place (we know they're coming though)
2. Dev time - it'll take longer to customize than it would to remove.

I'll look into customizing the page as a 2nd step. Would that work for you?

> Also, do you currently check for whether the site already has a paid plan? In that case we wouldn't want to show it at all.

I'm not 100% sure about this, but I _think_ yes.

> A note, we could quickly push through the typo fixes (thank you!) if they were handled in a separate PR. That would also allow us to review and study the "meat" of this PR more quickly and simply.

Agreed, can remove.

> Can we create a separate action creator for the JETPACK_CONNECT_SELECT_PLAN_IN_ADVANCE action? It could be used in selectPlanInAdvance as well. It's generally better to have action creators when a certain action is manually created in more than one location. It could use some tests, too 😉 .

Thanks for the tip, @tyxla! I will look into it. Not until next week at the very earliest though :)

> When making changes to the plan pre-selection, it would make sense to test any flow that uses this functionality already

You got it 👍

**Comment by richardmuscat** [comment]
@v18 -- I hear you but if we don't do something right away we tend to forget and I don't really want to hide the plans selection screen. 

I'm thinking something super simple like what we've done in the past for Akismet where we literally just change the headline text to something that fits the context.

@tyxla / @sirreal -- it shouldn't be too hard to do that right?

**Comment by v18** [comment]
>I hear you but if we don't do something right away we tend to forget and I don't really want to hide the plans selection screen.

Sure, I'll look into it to see how quickly it can get done.

Aren't the Woo-related plans coming out soon, @richardmuscat? That would serve as a good reminder to put the plans page back in.

**Comment by avivapinchas** [comment]
We should hide the plans page. Smart ways to upsell / promote Jetpack are on our roadmap, just having the plans page here adds a barrier for customers in the middle of doing a complex task. They're likely to be more annoyed than anything else. Even if it sells more Jetpack plans, it's not a good user experience, and I think we can find other, smarter ways to upsell.

**Comment by olaolusoga** [comment]
Agree with hiding the plans page. Like @avivapinchas  mentioned, more thought out upsells that are contextual to Woo + Jetpack is on the roadmap, so it will not be forgotten. Jetpack has it's growth plans, but we also have ours on Woo, and that is increasing adoption of WooCommerce Services via a seamless setup/NUX process. The plans step disrupts that NUX, and adds an unnecessary layer that isn't applicable at that point of the users journey. We need the plans page removed and **free** auto selected, so we can get the user to the end goal (the whole reason they downloaded the plugin) of purchasing labels, which from a business/financial perspective is one of the recurring revenue models we are aiming to grow via WCS in Woo. @v18 @richardmuscat

**Comment by richardmuscat** [comment]
@v18 / @avivapinchas / @olaolusoga -- I understand that showing plans is a "lesser user experience" but that's always the case. The ideal user experience is getting everything for free :)

This is a prime opportunity to raise awareness of Jetpack's paid plans to an audience that's potentially a really great target.

It's true it adds a barrier but its a low one for someone choosing the free option. Smart ways to upsell tend to be always down the line on automattic's roadmap :) and I'd rather have a dumb way to start than nothing please.

**Comment by olaolusoga** [comment]
> The ideal user experience is getting everything for free 

I disagree. The ideal UX would acknowledge a persons mental model during each point of their journey, and then serve contextual offers at key moments of need. This would make the experience (and offer) more rich, personal, and valuable.

A person who's going through the setup of WooCommerce, and then WCS has one thing in mind: get their store going, and start selling. Not select a backup plan, and spam filter for a store "I" haven't created yet... And if they're existing users with a store already created, we need to think of a more fluid way of selling to them.

I do agree that it is a low barrier, and it's better to start with that than nothing at all, but once again, looking at it from a users perspective, aside from needing Jetpack for the WooCommerce services offerings, the plans are not relevant for me(the user) at that point.

Replacing the title and copy feels like a band aid, not a solid solution.

We're aiming for the same end, A8C growth. The Woo strategy for now is removing barriers (low one: plans page) to increase WCS use, which at scale impacts A8C growth positively. 

Jetpack is starting to become a core for most products now, so ignoring plans/offers would be a mistake. Again, it is something we have on the roadmap, so for the interim :), it'd be great to move forward with removing the plans page till we have a solid plan to offer people that is contextually relevant. 

PS. let's not use this as an opportunity to force upsell, because we're able to "get" more people to install Jetpack via other means (WCS).

@richardmuscat

**Comment by richardmuscat** [comment]
Ok, it looks like you folks are almost as hard-headed as me :)

We can debate whether we're forcing people into an upsell back and forth for a while (I don't think so) and whether a band-aid is better than an open wound (I think so) but how about this: let's run a split test.

It should be pretty easy to set this up -- both @sirreal and @johnHackworth have experience of doing this on Jetpack NUX -- and we can measure the number of completed WCS connections with and without plans and then we can have a discussion with data in hand.

**Comment by johnHackworth** [comment]
yeah, the test should be pretty easy to setup ... I can handle it, if y'all agree that's a good option

**Comment by v18** [comment]
Next step: I'll work on removing the plans page using the suggestions made above.

**Comment by richardmuscat** [comment]
@v18 do you mean the split test approach?

**Comment by v18** [comment]
@richardmuscat yes, split test between (1) no plans page & (2) original plans page. I'll work on removing it, and later ask for feedback/help about setting it up as an A/B.

**Comment by toddwilkens** [comment]
@v18 @avivapinchas @olaolusaga @richardmuscat sorry to be replying to this a bit late...missed it in the midst of meetup travel and other things. 

This plans page needs to be removed asap. Whether the friction it adds is small or large, it clearly adds some. The primary goal of this flow is to get users signed up and set up with the shipping service. The biggest goal for woo in q2, directly from matt, was to increase adoption of our shipping service. We need to nail that goal first before exploring any secondary goals (JP upsell, etc). 

We will definitely a/b test things around plan pages as well as other ways to promote JP...we have a number of good ideas that are much more likely to work better. We can discuss in detail at the JPOP/Woo meetup in AMS later this month.

**Comment by richardmuscat** [comment]
@toddwilkens what's the objection to running with the split test though? if it has no negative effect its win-win, if it does we kill it.

**Comment by toddwilkens** [comment]
@richardmuscat sorry for the delayed reply. Traveling for meetup and AFK. There's no problem with an A/B test at all. I just want to make sure we start from the default/control position that there is no plans page (and to get to that default position ASAP). Then we can plan an A/B test.

However, I will tell you that given a lot of other reasoning from @avivapinchas @olaolusoga etc., there are likely much better ways to upsell JP rather than this flow especially because the context for it is one where they are highly unlikely to be interested in anything JP plans have to offer (i.e they are trying to set up WooCommerce and Shipping). So, I want to make sure we start from the simpler default position...and to plan to explore and test many other ways to bring the value of JP plans to Woo users at potentially more effective times.

**Comment by apeatling** [comment]
@richardmuscat, @nabsul, @v18  We seem to have stalled here, did we do a split test? If so can we either merge this or close it depending on the result?

**Comment by v18** [comment]
@apeatling this PR can be closed, since the resolution (remove plans page for Woo customers connecting to JP) was done in https://github.com/Automattic/wp-calypso/pull/16238

**Pull request closed without merging**
