### PR TITLE
Temporarily turning off Premium plan bump AB tests and reenabling Concierge sessions

### PR DESCRIPTION
**Pull request by victorespigares**
#### Changes proposed in this Pull Request

* Temporarily turning off both Premium plan bump AB tests (https://github.com/Automattic/wp-calypso/pull/35134) till we fix the flow redirection. Check pa1C6h-z7-p2 for more context.

Also reenabling Concierge sessions turned off in https://github.com/Automattic/wp-calypso/pull/36035/

#### Testing instructions

* Buy a Personal plan without a domain. After paying, you should get the Concierge/Quick Start offer.
* For a new site, buy a Personal plan with a domain. After paying, you should get the GSuite offer.

### CODE REVIEW

**Comment by travisw** [comment]
Strange, I'm getting a js error and the upsell page isn't loading. It redirects the the correct URL, but doesn't load properly.

Screen Shot 2019-09-25 at 10 54 37 AM

I'm not sure if this is something with my environment. I'm also having issues loading the checkout page on wordpress.com.

**Comment by travisw** [comment]
Otherwise the code looks fine.
I'm seeing the same behavior on the master branch, so I assume it's unrelated to this PR.

Maybe someone else from @Automattic/marketing-dev can test this in the meantime.

**Comment by travisw** [comment]
I'm not sure what that failed test is all about, probably unrelated? It looks like something about an svg file.

**Comment by dzver** [comment]
The code looks good but I was unable to confirm that it works. I created several users and I see CORS errors. The signup doesn't complete.

**Pull request merged**
