### PR TITLE
No sites message: consolidate layout

### PR DESCRIPTION
**Pull request by zaguiini**
Related to https://github.com/Automattic/dotcom-forge/issues/3667#issuecomment-1709574320.

## Proposed Changes

Consolidates the designs between the `/sites` empty state component and the one from `/stats/day`, which is quite old.

| Before | After |
| -------|------|
| image | image |

## Testing Instructions

Browse `/stats/day` in an account with no sites. You can also verify it shows the new designs in these places with occurrences:

image

### CODE REVIEW

**Comment by simison** [comment]
Worth also redirecting these people to empty /sites view directly? More comprehensive next steps on that page for folks without sites (imports, domains, etc).

**Comment by zaguiini** [comment]
@simison @wojtekn this is done is another PR: https://github.com/Automattic/wp-calypso/pull/82216

**Comment by vindl** [comment]
> Worth also redirecting these people to empty /sites view directly?

Agreed. 👍 In follow-up tasks, we can look at the broader experience for users with 0 sites. If they navigate to all domains, they have multisite links for posts, pages, plugins, etc. in the sidebar, which are not particularly useful for them.

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/9053577

Thank you @zaguiini for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/9053577).

**Pull request merged**
