### PR TITLE
Subscription manager: Make action bar behave better on mobile

### LINKED ISSUE #77229: Subscription Management: Fix filter & sort dropdown layout on mobile view
The filter & sort dropdown layout needs tweaking on mobile view.

_Originally posted by @yansern in https://github.com/Automattic/wp-calypso/issues/75930#issuecomment-1558448370_

### PR DESCRIPTION
**Pull request by TimBroddin**
Closes #77229

## Proposed Changes

* Adds better mobile styling for the action bar (search + filter + sort) in the new subscription manager

### Before
https://github.com/Automattic/wp-calypso/assets/528287/9d145856-e10e-47dd-8d60-e0b3a6589bec 

### After 
https://github.com/Automattic/wp-calypso/assets/528287/fcf663d6-e75a-467f-8a3b-11bfa1f5c592

The code does away with most of the media queries, and instead just uses standard flexbox styling together with `flex-wrap`

## Testing Instructions

- Apply this PR
- Add `return next();` on line 833 of `client/server/pages/index.js`
- Restart Calypso
- Visit `http://calypso.localhost:3000/subscriptions/comments` & `http://calypso.localhost:3000/subscriptions/sites` and ensure the styles render fine on all screen sizes

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

**Comment by yansern** [comment]
Hmm... I wish when the sort dropdown goes to the next line, the search input expands and fills the entire area, so that the placeholder text is not clipped.

I have a feeling the search input & filter dropdown needs to be its own div container to make this work, but what does your flex-fu tells you? :)

**Comment by TimBroddin** [comment]
That's actually what I did, before landing on this :-D  I'll give it another go!

**Comment by TimBroddin** [comment]
I updated this PR: 

https://github.com/Automattic/wp-calypso/assets/528287/f82834ac-83ee-45eb-b8bd-00e4417e7e77

**Review by yansern — APPROVED** [review]
Tested on calypso live. Works well.

**Pull request merged**
