### PR TITLE
Components: increasing contrast in SectionHeader

### PR DESCRIPTION
**Pull request by drw158**
This updates a few components to use the $gray-text variable for text, which is the mimmim contrast needed to pass WCAG 2.0 AA tests on a white background.

affects:
- section header 
- header cake

The buttons will be using $gray-text once #11327 is shipped. Then, all text in the header will be the same color.

You may notice that the header title is actually 2% lighter after this change. That's because it was using `darken($gray, 20%)` which is darker than `gray-text`. Updating all text to use `$gray-text` will make all the text colors in the header consistent.

Before:
screen shot 2017-02-10 at 2 48 29 pm
screen shot 2017-02-10 at 2 49 15 pm

After:
screen shot 2017-02-10 at 2 48 36 pm
screen shot 2017-02-10 at 2 49 00 pm

### CODE REVIEW

**Comment by folletto** [comment]
This is full, proper text. Can we just use `$gray-dark` there? 
I don't think there's any need to use the lighter tone.

I'd also do the right chevron darker, as it's a strong signifier the block has an action.

**Comment by Copons** [comment]
Codewise 👍 , but presumably will need to be changed after @folletto's grey changes (e.g. replacing `$gray-text` with `$gray-text-min`).

**Comment by drw158** [comment]
@folletto Here's with $gray-dark for the text. Changing the action buttons in the section header would require overriding the default compact borderless button color. Do you think it's fine just to leave the borderless button color the same?

screen shot 2017-02-13 at 12 37 39 pm
screen shot 2017-02-13 at 12 37 30 pm

**Comment by folletto** [comment]
> Do you think it's fine just to leave the borderless button color the same?

Yep, I think it's fine. :)

**Pull request merged**
