### PR TITLE
FSE: Add block pattern infrastructure

### PR DESCRIPTION
**Pull request by obenland**
#### Changes proposed in this Pull Request

* Adds an FSE module to distribute block patterns.
* Adds three block patterns as examples.

#### Testing instructions

* Make sure to have the latest version of Gutenberg built.
* Apply this PR.
* Load the Editor and switch to "Block Patterns" in the toolbar.
* Insert a block pattern.

### TODO
- [ ] Decide where to host images used in block patterns. headstartdata? As part of the plugin? Use [Core's images](https://core.trac.wordpress.org/ticket/49580)?
- [ ] Decide whether we need to support json files, given that we probably want to always localize pattern titles?
- [x] See how to best distribute translations. Not sure of the `full-site-editing` text domain even works?

### CODE REVIEW

**Comment by davemart-in** [comment]
@obenland should https://calypso.live/?branch=add/fse-block-patterns work in testing this? I tried it, but don't see the patterns button in the editor.

**Comment by obenland** [comment]
FSE is using wp-calypso as a development environment only, it's not integrated with it.
With the docs in PCYsg-ly5-p2#wpcom-sandbox you can stream these changes from your local Calypso checkout to your sandbox and can test it that way

**Comment by mtias** [comment]
Core images are super limiting.

**Comment by lancewillett** [comment]
> Core images are super limiting.

Just to expand on this for clarity, what do you mean?

1. **Product quality** — The image quality in the core image collection is poor. We should find a better source of high-quality images and host them in the plugin.
2. **Technical** — The mechanism of hosting images on the w.org CDN is a limiting factor for performance, maintainability, other.
3. Other?

With clarity on this, contributors like me can take clear next actions to help.

**Comment by ianstewart** [comment]
@obenland do we want tracks events for the todo list?

**Comment by obenland** [comment]
It depends on what you want to track. I assume which pattern was inserted? Anything else?

**Comment by ianstewart** [comment]
Can we track any other engagement with the patterns? Deletion and editing?

**Comment by mtias** [comment]
@lancewillett the first! The ones that can be hosted / bundled there might be a more restrictive set than what could be used here. (I believe Unsplash was being used fine for WP.com.)

**Comment by mtias** [comment]
> Can we track any other engagement with the patterns? Deletion and editing?

I don't think you can easily track this since patterns become just regular blocks once inserted. I'd only count insertion.

**Comment by obenland** [comment]
The patterns inserter [surfaces the inserted blocks and a success notice](https://github.com/WordPress/gutenberg/blob/7d590e1bd59059f72e6f9163b331e02909111fcd/packages/block-editor/src/components/block-patterns/index.js#L52-L63), so to track patterns the best we could do would be to track success notices and then filter those? It wouldn't be very high quality data however. It would not account for translations and contain the entire notice text.

**Comment by amamujee** [comment]
Can we follow a pattern from inserted to its final outcome - e.g. inserted, deleted, modified, launched with our current logging @obenland ?

**Comment by obenland** [comment]
Gutenberg is not built with tracking in mind, so we're rather limited in the ways we can track things. 

These are the events we're currently tracking:
- undo
- redo
- moveBlocksUp
- moveBlocksDown
- removeBlocks
- removeBlock
- moveBlockToPosition
- deleteBlock
- insertBlock
- insertBlocks
- replaceBlock
- replaceBlocks
- replaceInnerBlocks
- createErrorNotice

We _could_ track block modifications, I'm just not sure how useful that'll be. From what I was able to find out it looks like it fires for every keystroke when typing text, not just once after a block was updated.

**Comment by obenland** [comment]
@ianstewart @iamtakashi When you get a chance, could you add the `gutenberg-edge` sticker to one of your test sites, apply D40292-code to your sandboxes, and test this PR on the site with the sticker? (and maybe on one without to verify nothing breaks :))
I'd also be interested in which other patterns you think we should ship with initially

**Comment by ianstewart** [comment]
> I'd also be interested in which other patterns you think we should ship with initially

We've started tracking that at …

https://github.com/Automattic/blockpatterns/issues?q=is%3Aissue+is%3Aopen+label%3A%22ready+to+ship%22

… with the Ready to Ship label in that repo.

**Comment by obenland** [comment]
Where should pattern images live? On headstartdata?

**Comment by ianstewart** [comment]
Where do our Page Layouts images live now?

**Comment by obenland** [comment]
They live on a8ctm1, together with their templates. The preview screenshots for the template selector live on headstartdata

**Comment by ianstewart** [comment]
Would it be simplest to create a site for dotcom block patterns? Exporting JSON from there, using it as a place to store images, and using it as a master site for "ready to ship" Patterns?

**Comment by obenland** [comment]
Simplest is this PR. We could absolutely re-create the page layout setup for patterns, but it would include headstart handling translations and them having to be deployed etc.

**Comment by iamtakashi** [comment]
I've applied `D40292-code` on my sandbox. Although this isn't exhaustive, I've noticed a few things.

I assumed the use of a core image is temporary until we decide the location, but the pattern looks... different :) A comparison:





--

Also, the preview doesn't seem to represent the pattern well. The width of the content looks a lot narrower. This is probably something we need to discuss in the upstream, But I wanted to mention this here as well.

Screenshot 2020-03-19 at 11 52 15

**Comment by obenland** [comment]
@ianstewart @iamtakashi I updated and added [all patterns that are ready to ship](https://github.com/Automattic/blockpatterns/labels/ready%20to%20ship).

These are the adjustments I made:
- Replaced all html entities with their hex code
- Removed all image id references to avoid unsuccessful API lookups
- Unfolded all HTML for easier debugging later on (except coblocks gallery which breaks doing that)

Remaining blocker:
- [ ] Decide where to host images used in block patterns.

**Comment by obenland** [comment]
After a discussion with @iamtakashi and @ianstewart in p1584641583330800-dotcom-view-design-slack, we decided to create a dedicated pattern site for patterns and images to live. This will also allow us to switch to using json files easily, if we decide to do so at a later point in time.

**Comment by iamtakashi** [comment]
@obenland Thanks for moving forward with a dedicated site approach. I am glad the process of adding and updating patterns is going to be easy. I appreciate it :bowing:

In the meantime, if I want to update some of the patterns that have already been added, what is the best way to do that? It's not urgent or anything, but I want to fix something in a pattern before the UI becomes available.

**Comment by marekhrabe** [comment]
Following up with some internal conversations, it seems to be decided to use bNZNv-p2 to store both patterns and their assets for hot-linking. What the procedure to sync into here? 

@iamtakashi Any updates on your required changes to patterns? Should I look for them somewhere in the dedicated site? I think we might need to act more quickly on this, as the Gutenberg update is coming to dotcom soon.

**Comment by iamtakashi** [comment]
@iamtakashi Any updates on your required changes to patterns?

I was waiting for the instruction to update patterns :) Having them in the dedicated site would be the best now? If so I can move all the patterns to the site that are ready to ship this afternoon.

**Comment by simison** [comment]
Related https://github.com/WordPress/gutenberg/pull/21074

**Comment by marekhrabe** [comment]
> Having them in the dedicated site would be the best now? If so I can move all the patterns to the site that are ready to ship this afternoon.

From conversations I've been able to locate, the dedicated site seems like a way to go now. I or @obenland can port those patterns once ready over there. Some manual conversion work seems to be needed there from my understanding of the code

**Comment by iamtakashi** [comment]
Ok, I've added all the ready-to-ship patterns (11 patterns) to the master site now.

**Comment by obenland** [comment]
@iamtakashi I added all remaining patterns except "Subscription". The jetpack subscription block kept breaking in preview and on insert, so we'll have to revisit that one.

**Comment by iamtakashi** [comment]
@obenland Weird. Can you open an issue with what you saw? It's probably worth to report here as the block seems to be worked on soon. https://github.com/Automattic/jetpack/issues/15076

**Comment by ianstewart** [comment]
The "Call to Action" pattern looks a bit janky right now.

image

The preview is janky independent of the theme but I'm not sure at the moment if it needs a fix in Gutenberg or if it's on our end. If it's not a simple fix can we just remove it for now?

**Comment by ianstewart** [comment]
> to track patterns the best we could do would be to track success notices and then filter those? It wouldn't be very high quality data however. It would not account for translations and contain the entire notice text.

Until we have a better version of tracking would it be worthwhile/complicated to track this for EN only?

**Comment by obenland** [comment]
It wouldn't be complicated, I'm just not sure how usable that data will be. It would track the pattern title, so patterns like "Call For Action" would not be distinguishable.

**Pull request merged**
