### PR TITLE
Frictionless Email Subscriptions: Enable email subscription flow in production

### PR DESCRIPTION
**Pull request by jeyip**
Related to https://github.com/Automattic/martech/issues/3098

## Proposed Changes

* Shows email subscription flow in production by toggling config flag

## Why are these changes being made?

* The feature is ready to release to a general audience

## Testing Instructions

* N/A, typically with feature flags, we can assume that they're functioning as expected and will display in production

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Review by oswian — APPROVED** [review]
Looks good to me ✨

**Comment by oswian** [comment]
I think we're good-to-go here @jeyip 

:shipit:

**Comment by jeyip** [comment]
I published the heads up post pau2Xa-6dt-p2 and will enable this in production around 10AM PST Monday 🙂

**Comment by oswian** [comment]
@jeyip Sounds great! 🎉

**Pull request merged**
