### PR TITLE
composite-checkout: Replace coupon display with "Total savings"

### PR DESCRIPTION
**Pull request by sirbrillig**
#### Changes proposed in this Pull Request

This modifies the review step in composite checkout to display "Total savings" (with a sublabel of any coupon code) instead of "Coupon". This is because the amount displayed by that line item is actually the total savings from all discounts, not just coupons.

Since savings may exist without a coupon, this also displays the "Total savings" line item any time there's a discount in the cart.

Finally, it corrects some inconsistencies about when we display "billed annually" for a line item. The logic there was unclear previously and likely had bugs.

**NOTE** This exposes some bugs around how the total savings is calculated and rendered. These bugs will need to be fixed on the server, probably before we merge this PR. D44528-code 
 and D44573-code should fix those issues.

#### Screenshots

Before:
before

After:

after

#### Testing instructions

- Visit composite checkout with a plan in the cart; verify that you see the price with no savings line item displayed.
- Add a domain to your cart as well as a plan; verify that you see the savings line item include the total saved for the bundled domain.
- Add a coupon to your cart; verify that you see the savings from the coupon displayed in the savings line item as well as the coupon code itself.

### CODE REVIEW

**Comment by fditrapani** [comment]
I tried this out with a free site and it worked as described!

**Comment by sirbrillig** [comment]
Rebased after https://github.com/Automattic/wp-calypso/pull/43067

**Comment by nbloomf** [comment]
I tested this together with D44528-code. Seems to work as described. I tested (1) new plan purchase, (2) claiming a domain credit, (3) upgrade with prorated credit, and (4) combining proration with a coupon. All the arithmetic worked out as expected.

I don't know how to adequately test the gsuite price break, since IIRC that only applies on the production API.

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/3785011

Thank you @sirbrillig for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/3785011).

**Pull request merged**
