### PR TITLE
Gutenboarding: Fix domain picker button toggle behaviour

### PR DESCRIPTION
**Pull request by andrewserong**
It looks like the domain picker refactor in https://github.com/Automattic/wp-calypso/pull/42657/ stopped the focus event from the popover from being passed up to the domain picker button, so if you clicked the domain button picker button while the domain popover was visible, it'd close and then re-open the domain picker.

This change adds in a container div to the button, along with a ref, and a `handlePopoverFocusOutside` function that checks to see if the `containerRef` contains the currently active element before allowing the focus outside to toggle the button. This is a workaround for Firefox and Safari's `button` focus support ([more info here](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button#Clicking_and_focus)), and this approach mirrors how the [WordPress `DropDown` component](https://github.com/wordpress/gutenberg/blob/master/packages/components/src/dropdown/index.js#L60) deals with toggling behaviour and clicking outside.

#### Changes proposed in this Pull Request

* Add a container div to the domain-picker-button (required to get focus behaviour working cross-browser)
* Add a `closeIfFocusOutside` function to deal with the PopOver's onFocus behaviour — this checks that the active element is within the container, and if it isn't, then allows the toggle to proceed.

domain-picker-button-toggle-small

#### Testing instructions

* Go to `/new` and enter a site title
* When the domain picker button appears, click it to open the domain picker popover.
* Click it again and it should hide without immediately reopening again
* Check across Safari, FF, Chrome and Edge
* Ensure that the `recordCloseModal` Tracks event still fires when you close the popover with this button (`DomainPickerPopover`)

Fixes #

### CODE REVIEW

**Comment by andrewserong** [comment]
Just noticed this needs a rebase, and maybe a slight rethink to fix it up after the other refactor was merged in. I'll take another look tomorrow :)

**Comment by simison** [comment]
We'll actually go ahead this week and hide the header toggle.

I agree this is a bug though so if you get this sorted out with small effort, it's fine to merge.

The dropdown possibly does a return later in form-or-another so would still be useful.

**Comment by razvanpapadopol** [comment]
> We'll actually go ahead this week and hide the header toggle.

Even more, Popover will probably go away in https://github.com/Automattic/wp-calypso/pull/43136 but we'll have the PRs (both this with the fix and the one with removal) to help bringing it back in the future if needed.

**Comment by andrewserong** [comment]
Thanks @razvanpapadopol and @simison — I've done a light refactor here, as I ran into cross browser issues, and it turns out the [WordPress DropDown component](https://github.com/wordpress/gutenberg/blob/master/packages/components/src/dropdown/index.js#L60) has a neat solution for it that I've re-used here.

If this all looks good, I'm happy for us to merge it in, but also happy if you want to skip it since the Popover will be going away in https://github.com/Automattic/wp-calypso/pull/43136 — at the very least, it was a useful little exercise to work out how to get the toggle button to behave correctly for if and when we need to do this again.

**Comment by andrewserong** [comment]
Closing this now instead of merging, to prevent conflicts with #43136, since that looks pretty close to landing.

**Pull request closed without merging**
