### PR TITLE
Update/ use blog id in api requests for posts and pages

### LINKED ISSUE #6779: Jetpack: can't access sites where URL matches an old mapped WordPress.com site
I believe this is a fairly recent issue, the following used to work, at least up until a week ago:
#### Steps to reproduce
1. Start by creating a WordPress.com site.
2. Add a domain mapping to that site, to map it to a domain you already own.
3. You can now access this site's settings in Calypso using the new mapped URL in the Calypso URL.
4. Change the domain's NS records to point the domain to a new hosting provider.
5. Create a new site on that host, and install WordPress.
6. Install and activate Jetpack.
7. Up until very recently, you were then able to access that site's settings in Calypso using the site URL in the Calypso URL.
8. Right now, however, that site URL loads the old WordPress.com site settings.

A good example is blog ID `94957111`, that now loads settings from `33644320`.

### PR DESCRIPTION
**Pull request by enejb**
Replaces https://github.com/Automattic/wp-calypso/pull/13670 also Fixes #6779

This PR updates instanced of siteID to siteId to remove confusion as to what the different value is for. 
This makes sure that we are always using the site_id in the api calls when interacting with the api.
Checks that siteId is always passed as a number. 
Make sure that the initial load of posts view for a single and multisite view is as expected. 

**To test:**
Load the posts and pages view with an empty cache on for a single site as well as all sites views.

Do you get the expected results (loading states) and not see any js errors.

### CODE REVIEW

**Comment by designsimply** [comment]
I did a quick check on the following routes and didn't see any js errors or blockers:

* http://calypso.localhost:3000/posts
*  http://calypso.localhost:3000/pages
* http://calypso.localhost:3000/pages/design5279.wordpress.com
* http://calypso.localhost:3000/posts/design5279.wordpress.com

image
<sup>Seen at http://calypso.localhost:3000/posts/design5279.wordpress.com using Firefox 53.0.3 on Mac OS X 10.12.5 logged in as design5279 unproxied.</sup>

**Comment by jblz** [comment]
@tyxla -- I think that type error is happening on master, I just repro'd on stage.  I'll investigate.

**Comment by tyxla** [comment]
I confirm that the issue was fixed by #14728.

**Comment by lezama** [comment]
@tyxla, @jblz, @mcsf!

@enejb si on leave for the next 2 months, do you think you could decide if this is good to go and merge?

I have played with this branch and it doesn't seem to break anything for my user, but I am a little bit outdated about the latest site-list changes, so I am not confident enough to make the decision.

**Comment by tyxla** [comment]
It doesn't break anything for me, too, but I'm not sure to what extent it's able to actually fix #6779. Perhaps we should get some more folks to test it?

**Comment by tyxla** [comment]
I'll go ahead and merge this one together with #14685.

**Pull request merged**
