### PR TITLE
Remove an old A/B test

### PR DESCRIPTION
**Pull request by dzver**
This test was ended and the code not cleaned so that we can analyze the results by cohorts. Analyzing by cohorts doesn't require the code to remain on production and also it's been awhile.

This code assigns people to a variation, sends events, and adds user attributes, for no clear reason.

#### Changes proposed in this Pull Request

Remove dead code

#### Testing instructions

Sign up with a new user and site. Make sure that you see the domain selection step. Try buying a test domain.

Fixes #

### CODE REVIEW

**Comment by p-jackson** [comment]
Tested all the flows and they are all showing the domain step as expected.

LGTM

**Comment by p-jackson** [comment]
This is good to go after a rebase.

**Comment by p-jackson** [comment]
Hi @dzver looks like that latest push added `pluginFeaturedTitle` to `active-tests.js` which doesn't seem related to this PR. Was that intentional or did I miss something perhaps? 🤔

**Comment by dzver** [comment]
Thanks for catching this, not sure where was I looking.

**Pull request merged**
