### PR TITLE
Add Free txt to Theme Sheet picker button for free themes.

### PR DESCRIPTION
**Pull request by budzanowski**
This is a PR addressing issue #6326 .

Test live: https://calypso.live/?branch=fix/missing-free-txt-on-theme-sheet-button

### CODE REVIEW

**Comment by seear** [comment]
The code changes are good 👍

**Comment by folletto** [comment]
Design wise it's ok — let's merge — also because it fixes a problem we have, so let's push this live.

---

On a sidenote, I'd like for @melchoyce to check the label we are introducing:

rd3436a94v

The label is a bit too long, might be a problem on certain languages and on mobile. Any idea there?

**Comment by melchoyce** [comment]
Some ideas:
- Pick this
- Pick design
- Select design
- Use design

Could also replace `purchased` with some sort of icon?

**Comment by folletto** [comment]
I like the idea of using an icon. Would keep the clarity of "Pick this design" but at the same time shorten it effectively. Maybe the `✓` icon?

Also, mentioning the icon made me think that "Purchased" might not work very well either on "Plans", since it's not _really_ purchased, more "available for a while for free in the plan".

**Comment by melchoyce** [comment]
Thinking a bit more, do we need an indication that you own/can use a theme? Or is it more important to mark when you _don't?_ Do you think folks will get confused if we don't label a theme as purchased?

**Comment by folletto** [comment]
Now that you point it out, no. 
It might be entirely better to not put any label if it's either "Purchased" or the plan allows it.

So:

* Purchased → (no label)
* Free → "Free"
* Not purchased → $price
* Plan → no labels anywhere

Makes sense?

**Comment by melchoyce** [comment]
👍

**Pull request merged**
