### PR TITLE
Jetpack auth button

### PR DESCRIPTION
**Pull request by johnHackworth**
closes https://github.com/Automattic/wp-calypso/issues/6399

We need to get ready for the main jetpack authorization flow to be redirected to the new JPC auth screen. This PR adds the changes we need to ask for authorization once they land in the auth screen, before doing the proper auth dance from calypso. It also makes sure that you get redirected back to your wp-admin if you started there and you choose the free jetpack plan.

image

Video of the process (a little slow, my sandbox is not being very fast today):
https://cloudup.com/cqIiXoBnx4Q

How to test
========
1. You need a jetpack sandbox running an unconnected >= 4.1 jetpack and pointing to your .com sandbox
2. Modify your .com sandbox so it redirects the jetpack auth requests to calypso no matter what (ask me or @roccotripaldi on slack how to do it)
3. Clear the indexedDb on your browser
4. Go to your site and connect jetpack. You should see the approve button once you land in calypso. After clicking on it, it should authorize your site and you should land at the plans selection screen
5. Click on the free plan button. You should be taken back to your wp-admin

ping @roccotripaldi  for testing and @richardmuscat & @rickybanister for UX 

Test live: https://calypso.live/?branch=add/jetpack-confirmation-button

### CODE REVIEW

**Comment by rickybanister** [comment]
The 'cancel' link should actually be ' ⬅️ Return to %site name% ' like we've done elsewhere around wp.com

**Comment by roccotripaldi** [comment]
Code looks good. Gonna test it out now.
Sorry for deleting `isCalypsoStartedConnection` - i thought we wouldn't need it anymore. Thanks for bringing it back.

**Comment by roccotripaldi** [comment]
Works well! After the glitch this weekend, I wanted to test this with SSO, but I'm struggling to figure that out. I'm cc'ing @ebinnion so he can give me a quick tutorial when he's online.

**Comment by ebinnion** [comment]
I just tested out the SSO flow and can confirm that I was auto-authorized after clicking the "Log in" button and then redirected to wp-admin after the authorization completed. 👍

**Comment by johnHackworth** [comment]
@rickybanister I changed the text and removed the "external link" icon (because we talked time ago that it doesn't make any sense here)

image


@roccotripaldi  @ebinnion @rickybanister  is this ok to merge then?

**Comment by roccotripaldi** [comment]
LGTM! 🚢

**Comment by rickybanister** [comment]
Looks good. Can we get the left-arrow gridicon in there like this:

screen shot 2016-07-12 at 11 38 30 am

I think that makes it more clear you're canceling. Also consistency.

**Comment by roccotripaldi** [comment]
Added the left arrow:

screen shot 2016-07-12 at 12 02 20 pm

**Pull request merged**
