### PR TITLE
Hosting Command Palette: Replace arrow down with the download icon for importing site to WordPress command

### PR DESCRIPTION
**Pull request by katinthehatsite**
Related to https://github.com/Automattic/wp-calypso/issues/84870

## Proposed Changes

*  This PR replaces the icon for the `Import site to WordPress.com` command and changes it from `arrowDown` to `download` icon as suggested https://github.com/Automattic/wp-calypso/issues/84870#issuecomment-1840931284

## Testing Instructions

* Navigate to Calypso Live Link
* Press `cmd + k` on macOS or `ctrl + k` on Windows to open the command palette
* Search for the `Import site to WordPress.com` command
* Confirm that the icon for the command is `download`

Screenshot 2023-12-11 at 12 06 04 PM

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

**Comment by danielbachhuber** [comment]
@katinthehatsite I was following this:

CleanShot 2023-12-05 at 07 27 40@2x

I don't love either icon, though. @javierarce Is there another you'd suggest?

**Comment by katinthehatsite** [comment]
@danielbachhuber - yeah, I am about to replace that one too in a separate PR 😅 

Happy to wait though if Javier would like another icon instead.

**Review by sejas — APPROVED** [review]
Works as expected thank you Kat!

The command `Import site to WordPress.com` has the upload icon, which matches with other import commands.

https://github.com/Automattic/wp-calypso/assets/779993/c530a32c-8053-45be-a779-9e9a19186f40

**Comment by sejas** [comment]
@javierarce , can you confirm that the icon under the button `Add new site > Import an existing site ` on `/sites` should also be the `upload` icon?

**Comment by wojtekn** [comment]
@danielbachhuber @katinthehatsite I like the new icon more. I think it's better as it shows an arrow in relation to the object, a box in this case. However, I think that arrow should be pointed down for the import action:

- down: import, download
- up: export, upload

**Comment by javierarce** [comment]
> However, I think that arrow should be pointed down for the import action:

I think the down arrow is used to indicate export or download because it's associated with taking it from the cloud to your computer. And import generally uses the up arrow because you send it to the cloud.

@danielbachhuber I don't like the arrow I proposed either, but that's the one used by Gutenberg and I think we should use that. And I'm afraid we don't have anything better. 

For reference, here's what we have in the WordPress Design Library.

image

**Comment by wojtekn** [comment]
> I think the down arrow is used to indicate export or download because it's associated with taking it from the cloud to your computer. And import generally uses the up arrow because you send it to the cloud.

When I search for "import icon" in Google Images I can't find any single occurrence of an arrow pointing up, so I think users may be accustomed to that approach.

**Comment by sejas** [comment]
I agree that the direction should be up. We already use it in othe places of wpcom , for example `https://wordpress.com/import/$siteSlug -> Blogger`

Screenshot 2023-12-05 at 16 20 14

**Comment by wojtekn** [comment]
> I agree that the direction should be up. We already use it in other places of wpcom , for example https://wordpress.com/import/$siteSlug -> Blogger

@sejas I agree with the icon usage in the example you shared, too - it's an arrow up that illustrates the "upload" action.

**Comment by javierarce** [comment]
After discussing with other designers, we’ve decided to use the download icon for the 'Import' function, as @wojtekn suggested. The direction is not as important as the fact that the arrow in that icon points towards the enclosure.

**Comment by katinthehatsite** [comment]
@sejas @javierarce - I updated the icon from `arrowDown` to `download` icon. Let me know if you are good for me to proceed and merge.

**Review by wojtekn — APPROVED** [review]
Code change looks good, works as expected.

**Review by sejas — APPROVED** [review]
Glad that we agreed on an icon 💪 .

Should we also update `Import content to the site...`? 🤔 . For me it's ok to have opposite directions.

- Assuming we will use the same icon on https://github.com/Automattic/wp-calypso/pull/84877

Working as expected! Thanks @katinthehatsite !

https://github.com/Automattic/wp-calypso/assets/779993/372d6ea1-a93d-4156-8580-e87c5c217083

**Comment by katinthehatsite** [comment]
@sejas I was thinking that too. Otherwise, it looks inconsistent when you type the word import and get two same looking icons with arrows pointing two different ways.

I will make an adjustment

**Comment by katinthehatsite** [comment]
@sejas  I updated the icon on `Import content to the site` command as well to be consistent with importing a site command:

Screenshot 2023-12-11 at 1 30 38 PM

**Comment by sejas** [comment]
@simison, we are updating the icon for `Import site to WordPress.com` and for consistency also for `Import content to the site`. Is it ok on your side?
If not, we can change it only for `Import site to WordPress.com` and discuss the other command in a different issue/PR.

Here some reasons behind the decision:

https://github.com/Automattic/wp-calypso/pull/84873#issuecomment-1845739196
> After discussing with other designers, we’ve decided to use the download icon for the 'Import' function, as @wojtekn suggested. The direction is not as important as the fact that the arrow in that icon points towards the enclosure.

Screenshot 2023-12-11 at 13 14 03

https://wordpress.org/plugins/wordpress-importer/

**Comment by simison** [comment]
Sure 👍  Thanks for heads ups.

**Pull request merged**
