### PR TITLE
Plugin details: Add a notice for free plugins on the logged out experience

### PR DESCRIPTION
**Pull request by WBerredo**
#### Proposed Changes

Add the text `on Business plan` for logged-out users on the Plugin Details page. 

#### Testing Instructions

* Go to a Free plugin details page (ex: `/plugins/mailpoet`). You can use an incognito window for that.
* Check if the text `on Business plan` is shown next to the `Free` text.

| Before  | After |
| ------------- | ------------- |
|Screen Shot 2022-11-03 at 10 55 11|Screen Shot 2022-11-04 at 08 19 39|

#### Pre-merge Checklist

- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?

Related to #69410

### CODE REVIEW

**Review by epeicher — APPROVED** [review]
I have tested and it works as advertised. LGTM!

One nitpick comment is about the separation between the price/Free text and the `span` small text. The Figma design shows 8 pixels so we can increase a bit [this padding here](https://github.com/Automattic/wp-calypso/pull/69754/files#diff-8ca59f5d58c55c0a3ebba7081cd74ea721777cf0615145166285c4e8b6a25c0cR43) which also affects the price to make it more similar to the design. I have checked this design f84fqtCG4pCnCh2Hq0But5-fi-5508%3A46123

What do you think? 

CleanShot 2022-11-04 at 07 57 26@2x

**Comment by WBerredo** [comment]
@epeicher Thanks for checking it, I have updated it here: https://github.com/Automattic/wp-calypso/pull/69754/commits/4b5b470d06fcd45e9fc06adeafbb64a4bbbebd20

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/7611884

Thank you @WBerredo for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/7611884).

**Pull request merged**
