### PR TITLE
Hosting Metrics: First pass at 'Cache hit/miss ratio' and 'PHP vs. static' pie charts

### PR DESCRIPTION
**Pull request by danielbachhuber**
See https://github.com/Automattic/dotcom-forge/issues/3276

## Proposed Changes

First pass at adding 'Cache hit/miss ratio' and 'PHP vs. static' pie charts:

image

However, the first isn't displaying in the picture because of p1691106078444819-slack-C7YPW6K40

## Testing Instructions

1. Navigate to `/site-monitoring/<site>`
2. See how the pie charts look.

### CODE REVIEW

**Review by sejas — APPROVED** [review]
@danielbachhuber, great start.

@katinthehatsite, and I have reviewed it together and we made some changes:
- Use the right colors for PHP pie chart https://github.com/Automattic/wp-calypso/pull/80180/commits/6887bbfc57fd0575ca45c2e8e9497600382fe2c1
- Fix the legend for hosting metrics pie charts to display only the percentage https://github.com/Automattic/wp-calypso/pull/80180/commits/532021493f5aab30880f5dfbc8105c7c6b6a4db8
- Add space between charts in the page https://github.com/Automattic/wp-calypso/pull/80180/commits/3852cd6ceb10cf45f193ef71841586996484bdad

The most significant differences with the design are:
- The chart should be a donut chart instead of a pie chart.
- The first `cache hit/miss` is not working due to the backend response. And probably the colors are off.
- There is no tooltip ℹ️ on the chart title.

**Review by katinthehatsite — APPROVED** [review]
What Antonio said :)

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/8683953

Thank you @danielbachhuber for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/8683953).

**Pull request merged**
