### PR TITLE
Checkout: Revert using Google Places API for smoother checkout

### PR DESCRIPTION
**Pull request by klimeryk**
Reverts #34940

We did not see a compeling change in conversion, so let's revert for now.

#### Testing instructions

Try adding a domain to your site (signup or existing one, either way is the same). During checkout, you'll be prompted to enter your contact details.

Make sure that there are no regressions in the domain contact info form - try inputting some invalid data, etc. There should be no locations suggestions from Google, of course.

Test different countries:

 - no country - no address fields, can't submit
 - UK, EU and US countries (other countries default to US) have different layouts for the address fields, so check them all out as well

Screenshot 2019-10-16 at 15 52 30

Screenshot 2019-10-16 at 15 52 22

### CODE REVIEW

**Comment by daledupreez** [comment]
@klimeryk and @Automattic/cobalt, this doesn't look like a 1-1 revert of the original PR. What is the rationale for that...? I am still looking at the functionality.

**Comment by klimeryk** [comment]
Sorry, I mentioned this in the P2 comment, seems I forgot to include it here:

> I’ve left the general improvements to related components as-is and the rest of the code should be easily re-usable from the revert.

In other words, the other improvements are "good to have"s (and some bugfixes too), so no need to revert them. The component is unused anyway, IIRC.

Also, no need to resolve merge conflicts - that's the PR author's responsibility. And in case they are working on the PR, just creates unnecessary work for them (merge commits to integrate their work, etc.). If you are blocked by merge conflicts for the code review, just ping the author of the PR and move on to the next PR :)

**Comment by daledupreez** [comment]
Sorry about the make-work -- in this case, I knew you were AFK. Looking at the actual PR now.

**Comment by eltongo** [comment]
LGTM!

**Pull request merged**
