### PR TITLE
Launchpad :: add newsletter steps (stripe/paid subscriptions)

### PR DESCRIPTION
**Pull request by n3f**
Related to #72651, P2: p81Rsd-1dU-p2

## Proposed Changes

* Add stripe account connected step to newsletter flow.
* Add paid newsletter plan to newsletter flow.

## Screenshot
See "Connect Stripe account" and "Create a paid newsletter".

## Testing Instructions

* Checkout this branch
* Sandbox public-api.wordpress.com & store: PCYsg-IA-p2.
* Start a new newsletter site from - http://calypso.localhost:3000/setup/newsletter/intro
* Checkout
* Verify that the steps now include connecting a stripe account and creating a paid plan.
* Following those steps should mark off the corresponding options.
* Returning from the stripe flow kicks you onto wordpress.com.  You will have to mangle the URL to return to your localhost environment -- which won't happen once this PR is merged. (i.e. `http://calypso.localhost:3000/earn/payments/${siteSlug}?stripe_connect_success=launchpad`).  Verify that the url param is correct.

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [x] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [x] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

**Comment by agrullon95** [comment]
I successfully connected a stripe account to my newsletter site, added a paid newsletter payment plan option to my site, and confirmed that the checklists were marked as completed on the launchpad screen.

**A couple of questions and observations:**

@n3f - Can you add any relevant P2s or threads to provide more context around these changes?

I noticed the `stripe_account_connected` and `stripe_connected` checklist tasks are updated on the backend. Is there supposed to be a difference between these values?

When navigating to either `connect a stripe account` or `Create a paid newsletter`, it might be a bit confusing for users to understand how to get back to the launchpad screen. The user can end up on the "checkout thank you" page or the `/earn/...` page, but they might not understand what to do next to get back to the launchpad screen.


## Tests

- [x] Confirm newsletter site launchpad checklist displays `Connect Stripe account` and `Create a paid Newsletter` tasks
- [x] Confirm `Connect Stripe account` task redirects to `/earn/payments-plans/{siteSlug` if user hasn't connected stripe to site
- [x] Confirm `Connect Stripe account` task is marked as completed after user completes Stripe connection form
- [x] Confirm `Create a paid newsletter` redirects to `/earn/payments-plans/${ siteSlug }#add-newsletter-payment-plan`.
- [x] Confirm `Create a paid newsletter` task is marked as completed after the user adds a payment plan option for their newsletter site.

**Comment by n3f** [comment]
> I noticed the `stripe_account_connected` and `stripe_connected` checklist tasks are updated on the backend. Is there supposed to be a difference between these values?

Oops 🤦‍♂️ .  Fixed this.

> Can you add any relevant P2s or threads to provide more context around these changes?

Other than the issue linked here there isn't anything, I'm writing up a p2 today though.

**Review by artpi — COMMENTED** [review]
Nice! This works well!

The only piece of feedback I have is that the "Connect Stripe Account" should lead here:
Zrzut ekranu 2023-03-28 o 16 22 46


Currenly it leads straight to Stripe and it has following problems:
- When on the free plan, you can connect Stripe even though we disallow it
- It drops you straight to Stripe without really explaining what Stripe IS and why you need it.

By going to this interstitial page, we will be able to explain and gate etc.

**Comment by artpi** [comment]
Also after this change let's rebase so I can accept :)

**Comment by n3f** [comment]
@artpi , that actually really simplifies the PR.  In fact if I had known that this PR would have taken much less time. 😆, 😢.

> Also after this change let's rebase so I can accept :)

Did that too!

**Review by artpi — APPROVED** [review]
This is great, let's ship it!

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/7901484

Thank you @n3f for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/7901484).

**Pull request merged**
