### PR TITLE
Start replacing 'url' and 'qs' with standard APIs.

### PR DESCRIPTION
**Pull request by sgomes**
We currently make use of `node`'s deprecated `'url'` API in Calypso client, imported as a browserified module. We also make use of a 3rd party `'qs'` library to parse and format URL query strings.

This PR starts the process of replacing them both (in client code) with native functionality provided by `URL` and `URLSearchParams`.

It uses polyfills for browsers that don't include native support, and since modern browsers don't need these polyfills, they're explicitly excluded from the `evergreen` build. No server-side polyfills are needed, as `node` already includes this functionality natively in the minimum supported version for Calypso (`^10.15.2`).

In addition, the PR tweaks `lib/build-url` (one of the example usages) to use a more semantic name for its single export, preparing it also for future extension.

**Note:** this PR will make the `fallback` build grow by about 4.7KB, which is the size of the polyfills being added. Once every usage of `'url'` and `'qs'` is removed, however, we should recoup those bytes and more over. The `evergreen` build should not change in size significantly until every usage of `'url'` and `'qs'` is removed, at which point it will also shrink.

#### Changes proposed in this Pull Request

* Add `@webcomponents/url` and `@ungap/url-search-params` polyfills. Can be replaced by `CoreJS` polyfills once we upgrade to `CoreJS` 3.
* Replace some example usage of `'url'` and `'qs'`.
* Rename default export in `lib/build-url` to a more semantic named export: `buildRelativeSearchUrl`.

#### Testing instructions

* Open Reader
* Choose a post and click on the share icon
* Choose Twitter
* Ensure that the tweet contents in the popup window are auto-filled with the title and URL

The changes are similar for Facebook but are harder to test, as it requires logging in. You could also just analyse the URL in the popup window and ensure it includes the right query string (made harder by the fact that it's behind a login URL).

`lib/build-url` already includes some extensive unit tests, so it shouldn't need any manual testing.

### CODE REVIEW

**Comment by sgomes** [comment]
Testing in IE11 revealed an issue; only `URL` is added to window, and not `URLSearchParams`. Investigating.

**Comment by sgomes** [comment]
Ready for review!

**Comment by sgomes** [comment]
**Note:** the performance advisor bot numbers appear to be wrong, as it indicates e.g. that the size of `entry-main` has gone down by 4776 Bytes (see http://iscalypsofastyet.com/branch?branch=update/start-replacing-node-url-and-qs), but that does not appear to be the case when consulting the live branch.

**Comment by sgomes** [comment]
Rebased on master to pick up recent changes to `package.json`.

**Review by bluefuton — APPROVED** [review]
Code looks good and Reader Share works as expected. 🚢

**Comment by sgomes** [comment]
Thank you for the review, @bluefuton! I'll wait until Monday to merge in case anything breaks 🙂

**Pull request merged**
