### PR TITLE
NPM dependencies: update `core-bundle-js` and import Iterator helper polyfills

### PR DESCRIPTION
**Pull request by ramonjd**
Related to https://github.com/WordPress/gutenberg/pull/64123

## Proposed Changes

Following a [tip](https://github.com/WordPress/gutenberg/pull/64123#issuecomment-2259946774) from @jsnajdr 

I'm not sure if this is needed - I haven't been around this repo for a while.

This PR:

- updates the core-js-bundle npm package to the latest version
- imports proposed Iterator helper polyfills into `browser.js`

## Why are these changes being made?

So that [Iterator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Iterator) methods are available for use in the Calypso code base.

These methods, for example [Iterator.prototype.find()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Iterator/find) are experimental and don't yet have wide browser support.

For example, Gutenberg was using `Iterator.prototype.find()`, which [broke functionality in the site editor](https://github.com/WordPress/gutenberg/pull/64123). 

Gutenberg and Core relies on widely supported standards with little polyfilling, but it doesn't mean Calypso has to 😄 

## Testing Instructions

Pretty crude, but I've just been checking to see if an Iterator method works in Chrome, Firefox and Safari, e.g., pasting some iterators in a component and checking the output at http://calypso.localhost:3000/log-in

```diff
diff --git a/client/blocks/login/index.jsx b/client/blocks/login/index.jsx
index d76f8d1718..7038e261cb 100644
--- a/client/blocks/login/index.jsx
+++ b/client/blocks/login/index.jsx
@@ -140,6 +140,12 @@ class Login extends Component {
 		}
 
 		window.scrollTo( 0, 0 );
+
+		const myMap = new Map( [
+			[1, "one"],
+			[2, "two"],
+			[3, "three"],
+		] ).values().find( ( [ num, label ] ) => console.log( `${ num } is ${ label }` ) );
 	}
 
 	componentDidUpdate( prevProps ) {
```

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Review by jsnajdr — COMMENTED** [review]
It would be nice if Calypso started to actually use an iterator helper in the code, in the same PR. Otherwise we are just adding something that we don't use, and nobody knows it's possible to use.

We'll need to upgrade more packages than just `core-js-bundle`. The `core-js` dependency in `packages/calypso-polyfills/package.json` seems to be the most important one.

And `core-js-compat` should also be upgraded, but it's a transitive dependency of `@babel/preset-env`.

There should be changes in `package-lock.json` if the PR really upgrades something.

**Comment by tyxla** [comment]
I agree with Jarda on whether and when the polyfill would be necessary. 

Also, you'll have to run a fresh `yarn install` and commit the `yarn.lock` changes associated with the proposed package update.

**Review by tyxla — COMMENTED** [review]
I agree with Jarda on whether and when the polyfill would be necessary. 

Also, you'll have to run a fresh `yarn install` and commit the `yarn.lock` changes associated with the proposed package update.

**Comment by ramonjd** [comment]
Thanks for the feedback folks. 🙇🏻 

I just YOLOed this PR - happy to close and leave it for another time when folks have more need/time.

**Pull request closed without merging**
