### PR TITLE
Themes: theme search suggestion welcome style alternative

### PR DESCRIPTION
**Pull request by folletto**
This is a try for an alternate styling for the suggestion box to make it more aligned to the Calypso patterns and the "underline" look.

Current: 

screen shot 2017-03-15 at 19 14 49

Initial version of this PR (now changed, see comments below):

screen shot 2017-03-15 at 19 10 03

Current version:

screen shot 2017-03-16 at 12 57 46

Here's an alternate idea for styling the welcome screen.

This approach doesn't wrap, so will need an adjustment (rows) on mobile (not yet in the PR).

### To test

1. Open `/design`.
2. Try searching free text, and using autocomplete.
3. Try clicking/tapping to see if you can add filters without using the keyboard.

### CODE REVIEW

**Comment by folletto** [comment]
Alt-2 styling:

screen shot 2017-03-15 at 19 41 13

**Comment by drw158** [comment]
I kinda like how the monochrome styling has no underline for the inactive buttons. For some reason, having an underline for all the "tabs" makes them less clickable and I'm not sure what they are. I like the colors though!

I don't mind the button style before, and makes me think of tags. Seems more clickable to me.

**Comment by folletto** [comment]
> I like the colors though!

Haha yeah, I think they added some positive touches to the overall UI, but I'm ok in starting with monochrome, we can always add them later. 

For future reference, the mixin for that is also rather simple:

```
@mixin themes-magic-search__token-colors( $name, $color ) {
	.themes-magic-search-card__welcome-taxonomy-type-#{$name} {
		color: $color;
		border-color: $color;

		&:hover {
			box-shadow: 0 2px 0 0 $color;
		}
	}

	.themes-magic-search-card__token-type-#{$name} {
		.themes-magic-search-card__token-taxonomy,
		.themes-magic-search-card__token-separator,
		.themes-magic-search-card__token-filter {
			border-color: $color;
		}
	}
}

@include themes-magic-search__token-colors( 'color', #005082 );
```

> Maybe make column a lighter text color? Not sure.

I tried before to do a lighted text color, but unfortunately the mechanism used behind the scenes to do the "styling" of the tokens has quite some limitation (the kind of limitations that make you "WHAT IS THIS, IT'S 2017 FFS!!!") and makes it very quirky to color parts of the texts. :( 

We can try later other ways to add styling, but currently this seems the sharpest way to do it.

**Comment by folletto** [comment]
Tested on: Chrome, Safari, Firefox, Edge, IE11 + Safari iOS.

**Comment by folletto** [comment]
Current on mobile:

screen shot 2017-03-16 at 12 58 22

**Comment by folletto** [comment]
Thanks @budzanowski and @ockham for the help in sorting out this messy rebase. 💯

**Comment by folletto** [comment]
Re-Tested on: Chrome, Safari, Firefox, Edge, IE11.

**Pull request merged**
