### PR TITLE
Update Babel to 7.9.0 and dedupe moment-timezone

### PR DESCRIPTION
**Pull request by sgomes**
This PR replaces #41100, now that the `@wordpress/*` duplicate issue has been fixed.

It updates Babel to support the new `import type` and `export type` typescript syntax. All Babel packages (and some dependencies) were updated to ensure consistency between them.

It also fixes a duplicate with `moment-timezone`.

#### Changes proposed in this Pull Request

* Update Babel versions to support the new `import type` and `export type` typescript syntax
* Dedupe `moment-timezone`

#### Testing instructions

Ensure that the builds continue to work normally, by checking if the live branch gets built normally and the E2E tests don't fail.

### CODE REVIEW

**Comment by sgomes** [comment]
Note: the size increases aren't as bad as the matticbot comment above makes it appear. The second table on this page illustrates things more clearly: http://iscalypsofastyet.com/branch?branch=update/babel-to-core-7.9.0

Overall we see a 19KB (compressed) increase across the sum of all chunk sizes, which is quite reasonable, considering most users will only load a small portion of these as they navigate through the application.

**Comment by sgomes** [comment]
The `wp-desktop` test appears to be failing due to an unrelated issue.

**Comment by sgomes** [comment]
Updated the PR to handled deduping post-`yarn`.

**Comment by scinos** [comment]
Great job deduplicating so many duplicated packages!

**Comment by sgomes** [comment]
Looks like a build error slipped through. Investigating.

**Comment by sgomes** [comment]
Build error fixed.

**Comment by sgomes** [comment]
For a bit more background on the build error: `@babel/core` and `@babel/runtime` need to be kept in sync, otherwise the former will generate code that doesn't have the necessary runtime helpers in the latter.

**Review by scinos — APPROVED** [review]

**Comment by sgomes** [comment]
Thank you for the review, @scinos! 👍

**Pull request merged**
