### PR TITLE
Fixes the Blaze Dashboad app in older versions of Jetpack

### PR DESCRIPTION
**Pull request by sbarbosa**
This PR fixes the Blaze Dashboard - Campaign details page for sites using older Jetpack/Blaze Ads plugins versions.

## Proposed Changes

* Add a check for the jetpack version and hide the new stats section of the campaign details page if the version is not supported.

## Why are these changes being made?

The latest changes to the  blaze dashboard added a new endpoint inside the Jetpack blaze module, but olders version of Jetpack doesn't have that endpoint and will fail to fetch the data. 

The main objective of this PR is to hide the stats section if we detect an unsupported version of Jetpack/Blaze Ads plugin.

## Testing Instructions

* Test in the Live preview and verify that you correctly see the new Stats section in the Campaign details page
Screenshot 2024-12-13 at 3 40 26 PM

Now, you will need to have a sandbox to test the following part.
* On a console, connect to your sandbox to activate the connection
* On a different console, navigate to `wp-calypso/apps/blaze-dashboard` and execute `yarn dev --sync`
* Move all the traffic from `widgets.wp.com` to your sandbox
* Now, test any Jetpack site with an older Jetpack version (14.0 and bellow). You shouldn't see the new section with the graphs on the campaign details page
* Run the same test, but now only with the Blaze Ads plugin (0.5.2 and bellow). As before, the new stats endpoint should be hidden.
* If you test with newer versions of the plugins (Jetpack and/or Blaze Ads), the section should be displayed.

**Note:** If you don't have a Jetpack site with a completed campaign, you could do one of the following:
a) Tunnel your local DSP server and manually create/activate a campaign for that site with stats
b) Add the following changes to the file `client/my-sites/promote-post-i2/components/campaign-item-details/index.tsx` test the change with console.log:
```
const areStatsEnabled = useJetpackBlazeVersionCheck( siteId, '14.1', '0.5.3' );
console.log(` Stats Enabled: ${ areStatsEnabled } `);
```

With this, you should be able to see in the console if the version check was successful. If you want to verify if the stats endpoint will work on that setup, you could for the last parameter to true in this call:
```
const campaignStatsQuery = useCampaignChartStatsQuery(
	siteId,
	campaignId,
	chartParams,
	!! impressions_total
	true // !! impressions_total && areStatsEnabled
);
```

With this, you should see a call in the network tab, and verify if you correctly get a response code different than 404 (we get 404 when Jetpack doesn't support the endpoint).

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
    - [ ] For UI changes, have we tested the change in various languages (for example, ES, PT, FR, or DE)? The length of text and words vary significantly between languages. 
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Comment by therocket-gr** [comment]
seems to be not working ok to me.. in localhost I am debugging 
added those consoles

`console.log("siteJetpackVersion")
console.log(siteJetpackVersion)
console.log("blazeAdsVersion")
console.log(blazeAdsVersion)`

and I see that both come as 0 so the stats wont show

**Comment by sbarbosa** [comment]
Thanks @therocket-gr ! 
I was able to reproduce it with a specific site that is running in simple architecture. Those sites probably don't load the jetpack version in the store. 

I will need to find a way to differentiate them. Thanks for the info and test!

**Review by timur987 — APPROVED** [review]
Thanks @sbarbosa!

Code looks great and works as advertised.
I checked that the jetpack version is detected correctly and that the stats are hidden whenever I change minimal version to become "14.3".

**Review by therocket-gr — APPROVED** [review]
with the latest commit i can see it working fine. 
tested in localhost and  in jetpack site and it worked ok in both 
code changes LGTM

**Pull request merged**
