### PR TITLE
Tracking: Adds a new bing tracking code for jetpack

### PR DESCRIPTION
**Pull request by johnHackworth**
This PR adds a different bing track code for jetpack plans purchases. I'm not 100% sure about it working as I expect (and it's hard to test without testing in production), so I would love some review from someone with experience in the matter ( @drewblaisdell  ? ).

### CODE REVIEW

**Comment by drewblaisdell** [comment]
The testing instructions in [this PR](https://github.com/Automattic/wp-calypso/pull/3057) should give you more information about how to test this functionality.

For my own understanding: what is the goal of this change?

**Comment by johnHackworth** [comment]
oh, thank you @drewblaisdell  !

yeah,  I need to add more context in the description of this PR ...  pretty much: We need to use a different bing tracking codes for users purchasing .com plans and users purchasing jetpack plans. It's related to the ads we are running and being able to check how they convert.

**Comment by drewblaisdell** [comment]
Thanks for the info.

I'm unfamiliar with whether this is possible with UET (it does support custom events), but I think ideally we would be able to include some custom purchase information (e.g. an `isJetpackPlan` flag) along with the `purchase` event we [push onto `window.uetq`](https://github.com/Automattic/wp-calypso/pull/8178/files#diff-ad25580e9b44243a1f0a477cb0b717c8R328), then use whatever tools Bing provides to segment the data based on this flag. This would prevent us from initializing `UET`/polluting the global namespace twice, or suddenly depriving the current Bing account of Jetpack plan data.

**Comment by johnHackworth** [comment]
That's a good point... let me expose it in the jpop-ads slack and see if a param would be enough and we could use the same tracking code

**Comment by johnHackworth** [comment]
ok, after talking about it, this has been VERY simplified. We are going to just use an event label in bing tracking and that's it.

@drewblaisdell  can you take a quick look again, since you know the background of this PR ?

**Comment by tyxla** [comment]
LGTM :shipit:

**Pull request merged**
