### PR TITLE
Reader: Fix indentation on reader-post-card

### PR DESCRIPTION
**Pull request by blowery**
No functional changes. Just whitespace.

### CODE REVIEW

**Comment by blowery** [comment]
cc @dmsnell

**Comment by fraying** [comment]
@blowery whitespace where?

**Comment by dmsnell** [comment]
LGTM! :shipit:

**Comment by blowery** [comment]
@fraying in the code itself

**Comment by fraying** [comment]
@blowery Oh! That kinda whitespace. Nevermind. 😁

**Pull request merged**
