### PR TITLE
Components: Use the actual main element for the main component

### PR DESCRIPTION
**Pull request by krainboltgreene**

### CODE REVIEW

**Comment by lancewillett** [comment]
Thanks for suggesting this — do you have more comments on why you think it's a good idea?

Are there CSS changes needed if any rules are based on `div` existing?

**Comment by krainboltgreene** [comment]
> CSS changes

Possibly, I just started looking at the project.

> think it's a good idea

`<div>` isn't semantic and the description of this component is almost exactly the description of the `<main>` semantic usecase.

**Comment by rralian** [comment]
@krainboltgreene Thanks for the PR! It looks like this branch needs to be rebased to pick up the recent change to use `classNames` instead of `react/lib/joinClasses` (6e73d41396202d8bc3c947765e926402350c16dc). Do you mind rebasing?

`<main>` isn't yet supported in IE11 and opera mini. http://caniuse.com/#feat=html5semantic But considering we're keeping the styles here, I think it should be fine. I need to set up virtualbox to do a little quick testing though. In the meantime, @mtias, any concerns?

**Comment by adambbecker** [comment]
We could probably start using the `main` element, however we should also add it to the [block display section](https://github.com/Automattic/wp-calypso/blob/master/assets/stylesheets/shared/_reset.scss#L28-L39) in `assets/stylesheets/shared/_reset.scss` because IE does not include native [support](http://caniuse.com/#feat=html5semantic) for it (as of now).

**Comment by krainboltgreene** [comment]
Gotcha I'll rebase, thanks for the update!

**Comment by mtias** [comment]
Yeah, this would make sense — we are already mapping the ARIA role with `role="main"`, which would still be needed until we are confident browsers support the html5 variant. What's the landscape on browser support for `<main>`? Only IE has issues?

**Comment by krainboltgreene** [comment]
Updated with rebase from master.

**Comment by krainboltgreene** [comment]
Just something I want to be clear on, now it outputs:

``` html
<main class="main" role="main">
   ...
</main>
```

**Comment by gwwar** [comment]
:+1: Checked this in Win10 IE11/edge, and OSX Chrome/FF and it looks OK. 

As @adambbecker suggested, it wouldn't hurt to add `main` to _reset.scss so we can provide fallbacks for browsers that don't support this yet.

**Comment by gwwar** [comment]
@krainboltgreene could you add in `main` to the _reset.scss [block display section](https://github.com/Automattic/wp-calypso/blob/master/assets/stylesheets/shared/_reset.scss#L28-L39)? I'll merge this in after that's done. :)

**Comment by krainboltgreene** [comment]
Sure! I do that after work.

On Tue, Dec 1, 2015 at 11:16 AM, Kerry Liu <notifications@github.com> wrote:

> @krainboltgreene <https://github.com/krainboltgreene> could you add in
> main to the _reset.scss block display section
> <https://github.com/Automattic/wp-calypso/blob/master/assets/stylesheets/shared/_reset.scss#L28-L39>?
> I'll merge this in after that's done. :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Automattic/wp-calypso/pull/809#issuecomment-161067023>
> .
>



-- 
Kurtis Rainbolt-Greene, Hacker
Software Developer
1631 8th St.
New Orleans, LA
70115

**Comment by adambbecker** [comment]
Since it's been a little while over here, I've continued this over in #1607, added the reset stylesheet fix, and rebased it with the latest from master. We'll continue over there.

**Pull request closed without merging**
