### PR TITLE
Reader: remove old post component

### PR DESCRIPTION
**Pull request by samouri**
What I did:
```bash
git rm client/reader/stream/post.jsx
git mv client/reader/stream/refresh-post.jsx  client/reader/stream/post.jsx
```
- Sadly GH doesn't display this prettily.
- Also removed all traces of feature-flags from `stream.jsx`.

To Test
------
Browse through some of your streams and make sure posts look refreshed, x-posts as well.

### CODE REVIEW

**Comment by blowery** [comment]
Nice! Could you also post a comparison of the production bundle sizes before and after this change? Curious to keep a running tally of how many kb we drop as we remove things. /cc @bluefuton

**Comment by blowery** [comment]
To get prod bundles, just run `CALYPSO_ENV=production make build-production` on each branch.

Bonus points for coming up with a thing to diff and highlite changes. :D

**Comment by samouri** [comment]
@blowery I was thinking the same thing.
I think it would be best if we do one comparison when we are done with the initial delete-craze.

**Comment by blowery** [comment]
One at the end would be tougher, because some of these bits get promoted to either the main build layer or the commons chunk, since they're used a lot of places. Other stuff will happen by the time we finish all the work, so it won't be a true representation of what changed.

**Comment by bluefuton** [comment]
>Nice! Could you also post a comparison of the production bundle sizes before and after this change? 

Yep, sounds like a good plan 👍

**Comment by samouri** [comment]
I was having merge-conflict issues that I was having trouble resolving so I essentially redid this commit. Same procedure as outlined above

**Pull request merged**
