### PR TITLE
Gutenboarding: [WIP] add username field to editor onboarding

### PR DESCRIPTION
**Pull request by p-jackson**
#### Changes proposed in this Pull Request

Attempt at adding username form to block editor onboarding.
pbAok1-ww-p2#comment-1074

The welcome guide doesn't have any extension points, so this PR plans to show a modal with the username controls first, and then open the welcome guide after it's closed.

It also gives the user something to look at for the last little bit of the page loading.

* Add a `?is-gutenboarding-new-user` param to the calypso block editor
* If flag is present then a dialog is shown before the welcome guide opens (the dialog should have username controls in it)
* When dialog is closed the welcome guide should appear if it was going to before we interrupted it.

TODO:
* The `?is-gutenboarding-new-user` param should only be appended for users who have just used the signup form.
* Add controls to the username dialog.
* Try and match the size/style of the username modal with the welcome guide so it's less jarring when it switches.

#### Testing instructions

* `wpcom-block-editor` dev workflow: PCYsg-l4k-p2, or even p1585878454409400-slack-CNMU1UHHB
* Sandbox a site, public-api, and widgets.wp.com
* Edit a post on the sandboxed site using the calypso block editor
* Append the `?is-gutenboarding-new-user` query param and refresh
* Double check that you're using `calypso.localhost:3000` and that `widgets.wp.com` is truely sandboxed.
* I found I needed to build the editor with the `NODE_ENV=production` environment variable, because the editor was loading the minified code.

### CODE REVIEW

**Comment by p-jackson** [comment]
Demo of what works so far: https://d.pr/v/vmYnJS

**Comment by simison** [comment]
We have our custom welcome guide instead of core one — that should make things easier? 🤔 
It's here: https://github.com/Automattic/wp-calypso/tree/master/apps/full-site-editing/full-site-editing-plugin/wpcom-block-editor-nux

**Comment by p-jackson** [comment]
Thanks @simison! I think this would definitely be a better way forward! Deving in FSE is probably easier too :)

**Comment by ramonjd** [comment]
@p-jackson is this one still relevant or can we add it to the backlog for now?

**Pull request closed without merging**
