### PR TITLE
ThemesList: Fix shouldComponentUpdate() method

### PR DESCRIPTION
**Pull request by ockham**
How did this even not break? :facepalm:

To test -- verify that the showcase still works.

### CODE REVIEW

**Comment by gwwar** [comment]
Weird, in this expression js will return the rightmost.
```
( 1, 2, 3 )
// returns 3
```

So no js error is thrown, but truthyness depends on `this.props.getButtonOption` which may lead to unnecessary rerenders

**Comment by gwwar** [comment]
Branch looks good to me 👍

**Comment by ockham** [comment]
> Weird, in this expression js will return the rightmost.

I need to re-watch https://www.destroyallsoftware.com/talks/wat to see if that's covered there... :-/

Thanks for reviewing!

**Comment by ockham** [comment]
Ugh, I forgot that this is a function prop, with which `isEqual()` doesn't work. So I'll actually have to resort to `===` for now... :-/

**Comment by gwwar** [comment]
Nice catch that it was a function :shipit:

**Pull request merged**
