### PR TITLE
Consolidate happychat state shape

### PR DESCRIPTION
**Pull request by nosolosw**
This PR centralizes happychat state under a unique key, so it's easier to extract and adapt for other use cases in next steps.

Note that to make easier the revision and the changes more evident this PR doesn't rename things (selectors, actions, etc) and each commit is a consecutive step that might be worth reviewing separately. Note as well that this also fixes a bug (169b6c2) in persisting state and removes an action (d226074) that wasn't being used anywhere.

The proposed state shape for happychat is:

  - chat
    - lastActivityTimestamp
    - message
    - status
    - timeline
  - connection
    - error
    - isAvailable
    - status
  - ui
    - isMinimizing
    - lostFocusAt
    - open
  - user
    - geoLocation
    - _(upon extraction, we shall have the locale and groups keys under user as well)_

## Test

Run `npm run test-client happychat`
Manually start a Happychat session with an operator and test randomly.

### CODE REVIEW

**Comment by nosolosw** [comment]
cc @unDemian @omarjackman this was the PR I mentioned in https://github.com/Automattic/wp-calypso/pull/18519. I'd like this to be merged after that one, so it would need to be rebased. I haven't done yet so it's easier to review the changes introduced. Would you have the time for reviewing this as well?

**Comment by nosolosw** [comment]
This has been rebased with master, including the changes in https://github.com/Automattic/wp-calypso/pull/18519 so it's ready for reviewing.

**Comment by omarjackman** [comment]
@nosolosw this PR is massive. Is there any way we can break this into smaller testable PRs that incrementally reshapes the state tree?

**Comment by nosolosw** [comment]
Will create separate PR for each state key, will ping you on those Omar.

**Pull request closed without merging**
