### PR TITLE
FSE: Open WP.com block editor when editing template parts

### LINKED ISSUE #34074: Full Site Editing: override Edit button link for Gutenframe [3]
Currently, the Edit button link that appears on hover will work fine in wp-admin context, but we need to make it work with Gutenframe too. That means overriding the default link that it produces to equivalent `/block-editor` path in Calypso and opening it in `parent` window.

---
**Update**

Reopening this issue since Edit button behavior is not handled properly. For example, if I'm editing the page at `/block-editor/page/{test-site}/30` and click on Edit for Header (ID: 21), after showing the Header editing view the route remains unchanged, instead of being updated to `/block-editor/page/{test-site}/21`.

This leads to some weird behavior: refreshing the header page will show the previous page view. By clicking back a couple of times, you get to see Calypso in an iframe - at this stage you can even switch the site and navigate to a different section entirely, but the above route still sticks.

Noticed this while trying to track down https://github.com/Automattic/wp-calypso/issues/34713.

### PR DESCRIPTION
**Pull request by mmtr**
#### Changes proposed in this Pull Request

Ensures the WordPress.com block editor is opened after clicking on the Edit buttons of the template parts displayed when editing a full site page.

#### Testing instructions

* Update your sandbox with the latest changes of the FSE plugin and Modern Business theme following instructions at D30622.
* Generate a new build of the `wpcom-block-editor` app and upload it your sandbox site following instructions at PCYsg-l4k-p2.
* Sandbox the API and `widgets.cdn.com`.
* Open an existing page (`/block-editor/page/:sandboxSite/:pageId`).
* You should see the FSE header and footer on the block editor.
* Try editing either the header or the footer template part.
* Make sure the template part is opened on the block editor (the URL should be `/block-editor/edit/wp_template_part/:sandboxSite/:templatePartId?fse_parent_post=:pageId`).
* Click on the close button.
* Make sure the block editor loads the previous page.
* Start creating now a new page (`/block-editor/page/:site/`).
* Try editing either the header or the footer template part without saving any change.
* Make sure the template part is opened on the block editor (the URL should be `/block-editor/edit/wp_template_part/:site/:templatePartId`).
* Click on the close button.
* Make sure the block editor loads a new page.
* Try editing either the header or the footer template part after adding and saving some changes.
* Make sure the template part is opened on the block editor (the URL should be `/block-editor/edit/wp_template_part/:site/:templatePartId?fse_parent_post=:pageId`)
* Click on the close button.
* Make sure the block editor loads the previously created page.

Fixes #34074

### CODE REVIEW

**Comment by mmtr** [comment]
> * Start creating now a new page (/block-editor/page/:site/).
> * Try editing either the header or the footer template part without saving any change.
> * Make sure the template part is opened on the block editor (the URL should be /block-editor/edit/wp_template_part/:site/:templatePartId).

This is not working properly yet. We should display only one warning to let the users know the unsaved changes will be lost, but we currently display 2 warnings. 

The first one is produced by `markChanged` ([#](https://github.com/Automattic/wp-calypso/pull/34766/files#diff-59c0336bfc8e2c9de7a26194d97da7eaR422)), which is the one we want to show. The second one is produced within the iframe by Gutenberg (via the [`UnsavedChangesWarning` component](https://github.com/WordPress/gutenberg/blob/c323235c21d240c900ae95360206837a9936a4fa/packages/editor/src/components/unsaved-changes-warning/index.js)) and I don't know why is displayed here, given that this warning doesn't show up when closing the editor, previewing the content or going to the customizer.

I believe this issue might be related: https://github.com/Automattic/wp-calypso/issues/34751.

Will keep investigating.

**Comment by mmtr** [comment]
After overriding the `href` and `target` attributes of the edit links (57394a1), these links should behave exactly like the close button. However, I'm still getting two warnings when clicking on the edit links, but just one on the close button.

I ran out of ideas that might explain what is causing this, so I'd appreciate any insight here. I'll continue checking tomorrow though, maybe things will be clearer after a full rest 🙂.

**Comment by jeraldjuice** [comment]
> After overriding the href and target attributes of the edit links (57394a1), these links should behave exactly like the close button. However, I'm still getting two warnings when clicking on the edit links, but just one on the close button.

Going to see if I can finish this up for Miguel today 👍

**Comment by mmtr** [comment]
> However, I'm still getting two warnings when clicking on the edit links, but just one on the close button.

I'm starting to think that it might be related to the fact that even the URL changes (from `/block-editor/page` to `/block-editor/edit/wp_template_part`), Calypso still renders the same component (both URLs use the same controller), so maybe the `protectForm` HOC is not working properly.

That's not the case when closing the editor, since the URL changes to the list of pages which renders a completely different component.

I'll try performing a full server navigation rather than using a client navigation with `navigate` in order to force a fresh rendering that might solve the problem.

**Comment by mmtr** [comment]
> I'll try performing a full server navigation rather than using a client navigation with navigate in order to force a fresh rendering that might solve the problem.

Done in 5e25c66 and it seems to work, so this is ready for a full review now 🙂.

**Pull request merged**
