### PR TITLE
Update/hide plan in signup

### PR DESCRIPTION
**Pull request by fditrapani**
The activation and affiliate teams are looking for a way to hide the free plan in signup. This PR introduces a a query string parameter that hides the free plan (`?plans=true`). Rather than create a whole new flow that does the same thing and needs to be maintained, I thought the query string approach would be less burdensome in the future if there were updates that needed to be made. 

## Testing

First test the signup flow and make sure the free plan shows when you pick a .wordpress subdomain. Then:

- Visit `/start?plans=true`
- proceed to the plans step by picking a .wordpress subdomain
- The free plan should not display

@markryall can you take a look?

### CODE REVIEW

**Comment by MicBosi** [comment]
Looks good to me but I'd like to have the seal of approval of someone who's more versed in Calypso than me :)

**Comment by travisw** [comment]
What do you think about using a parameter name that's a little more specific and it's use more obvious.
To me `plans=true` doesn't make me think that the free plan would be hidden. Maybe something like `hide-free-plan=1` or `hide-plan=free`, etc.

**Comment by fditrapani** [comment]
Good point @travisw. I dwelled on this for a while too. I didn't want it to be too obvious so that people can enable the free plan and get around it but wanted it to be related. I'm still open to other suggestions if you or anyone else has any.

**Comment by travisw** [comment]
Ah good point @fditrapani, it shouldn't be obvious.
I just realized that a more reliable way to do this that's mostly invisible to the user would be to just check for the `wp-affiliate-tracker` cookie. If it exists then the user came from an affiliate link. This also lets us handle the case where a user clicked the link, then left and later came back to wordpress.com. In that case there won't be a URL parameter to rely on but the cookie will be there.

**Comment by fditrapani** [comment]
that's a great idea @travisw. I can see both approaches being handy. This one in particular would be great for Affiliates because then they don't need to add the param to the URL. Do you want to take a stab at setting up the cookie approach you mentioned?

**Pull request merged**
