### PR TITLE
Migration Flow: call Guides endpoint on step change

### PR DESCRIPTION
**Pull request by sam8lim**
## Proposed Changes

Calls the `triggerGuidesForStep` function on step change in the Migration flow.

## Testing Instructions

- Go to  `/setup/site-migration`
- You may be redirected to start/domains. Select "Choose domain later"
- Go through the flow to select Free plan
- When you get to "What are your goals?" 
- Open the browser network log.
- Select "Import Existing Content or Website"
- When you get to `setup/site-migration` confirm that a network request is sent to `guides/trigger` endpoint.

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Comment by bubel** [comment]
I cannot access `/setup/site-migration` as outlined in the test plan. If I access that URL as a logged-in user, it redirects me to `/start/domains`, and I do not see any network request prior to that redirect action. If I access that URL in an incognito window, it pushes me to `start/account/` and, once an account is created, I then land on `/start/domains`. 

What part am I missing?

**Comment by sam8lim** [comment]
> I cannot access `/setup/site-migration` as outlined in the test plan. If I access that URL as a logged-in user, it redirects me to `/start/domains`, and I do not see any network request prior to that redirect action. If I access that URL in an incognito window, it pushes me to `start/account/` and, once an account is created, I then land on `/start/domains`.
> 
> What part am I missing?


Correct, it redirects you to start/domains. Select "Choose domain later"
- Select a free plan
- Open the browser network log.
- When you get to the page: "What are your goals?", select "Import Existing Content or Website"
- Now you are in `setup/site-migration` confirm that a network request is sent to `guides/trigger` endpoint.

**Comment by bubel** [comment]
OK - for posterity, can we update the test plan, please, to help anyone else coming along to test?

**Review by bubel — APPROVED** [review]
This LGTM.

Screenshot 2024-05-16 at 8 26 35 AM

**Comment by bubel** [comment]
@sam8lim you may want to check this PR, as it now includes 23 commits with 56 files changed.

**Comment by gmovr** [comment]
There's one more failing test in TC for the hosted site migration flow. So both: `client/landing/stepper/declarative-flow/test/site-migration-flow.tsx` and `client/landing/stepper/declarative-flow/test/hosted-site-migration-flow.tsx`.

An easier way to get them to pass would be to add this to the files, since the Guides part probably has tests covering it already. 

```diff
diff --git a/client/landing/stepper/declarative-flow/test/hosted-site-migration-flow.tsx b/client/landing/stepper/declarative-flow/test/hosted-site-migration-flow.tsx
index e878aea135..b94fda73d4 100644
--- a/client/landing/stepper/declarative-flow/test/hosted-site-migration-flow.tsx
+++ b/client/landing/stepper/declarative-flow/test/hosted-site-migration-flow.tsx
@@ -40,6 +40,7 @@ describe( 'Hosted site Migration Flow', () => {
 		const testSettingsEndpoint = '/rest/v1.4/sites/example.wordpress.com/settings';
 		nock( apiBaseUrl ).get( testSettingsEndpoint ).reply( 200, {} );
 		nock( apiBaseUrl ).post( testSettingsEndpoint ).reply( 200, {} );
+		nock( apiBaseUrl ).post( '/wpcom/v2/guides/trigger').reply( 200, {} );
 	} );
 
 	afterEach( () => {
diff --git a/client/landing/stepper/declarative-flow/test/site-migration-flow.tsx b/client/landing/stepper/declarative-flow/test/site-migration-flow.tsx
index a5eb4ae497..9a154afd53 100644
--- a/client/landing/stepper/declarative-flow/test/site-migration-flow.tsx
+++ b/client/landing/stepper/declarative-flow/test/site-migration-flow.tsx
@@ -41,6 +41,7 @@ describe( 'Site Migration Flow', () => {
 		const testSettingsEndpoint = '/rest/v1.4/sites/example.wordpress.com/settings';
 		nock( apiBaseUrl ).get( testSettingsEndpoint ).reply( 200, {} );
 		nock( apiBaseUrl ).post( testSettingsEndpoint ).reply( 200, {} );
+		nock( apiBaseUrl ).post( '/wpcom/v2/guides/trigger').reply( 200, {} );
 	} );
 
 	afterEach( () => {

```

I think that should make the build pass. :)

**Pull request merged**
