### PR TITLE
FSE: Update Newspack to 1.7.0

### PR DESCRIPTION
**Pull request by obenland**
#### Changes proposed in this Pull Request

* Updates newspack-blocks to 1.7.0.

#### Testing instructions

* Load posts without newspack blocks and make sure there are no scripts loaded in the front-end
* On posts that contain newspack blocks, make sure they still work as expected

### CODE REVIEW

**Comment by josephscott** [comment]
@obenland does the lock file need to be included in this too?

**Comment by sgomes** [comment]
I pushed the lockfile update to this PR as a separate commit. That should keep `yarn` and the lint checks happy 👍

**Comment by sgomes** [comment]
The `wp-desktop` failure is expected and covered in #42898.

**Comment by sgomes** [comment]
The E2E failures are unrelated.

**Review by frontdevde — APPROVED** [review]
In functional testing this is working as expected as per testing instructions. Code wise this LGTM as well for the newspack-blocks version bump. 

(As stated above failing tests appear to be unrelated to changes in this PR.)

**Pull request merged**
