### PR TITLE
Checkout: Thank You: Update HEs that appear in `HappinessSupport`

### LINKED ISSUE #3932: DevDocs: HappinessSupport Component example displays with 'greyed' out sub-components
#### Steps to reproduce
1. Starting at URL: [App Components](https://wpcalypso.wordpress.com/devdocs/app-components)
2. Scroll down to the `HappinessSupport` component

#### What I expected
To see text, icons or images on the HappinessSupport component.

#### What happened instead
Just saw a 'greyed' out view of the component outline.
image

Additionally, if you select the area with your mouse, it will unveil the text expected to be displayed on the component e.g.,
happinnesssupport

#### Browser / OS version
Chrome, Mac OS X

cc: @stephanethomas

### PR DESCRIPTION
**Pull request by drewblaisdell**
We need to update these per pb6Nl-aSM-p2.

Also fixes #3932 and #3943.

screen shot 2016-03-24 at 2 03 18 pm

**Testing**
*In DevDocs*
- Visit `/devdocs/app-components/happiness-support`
- Assert that you see either Paolo or Erica's avatar/name on the right.
- Refresh the page and repeat until you've seen both avatars/names.

*On the thank you page (.com)*
- Visit `/plans/:site` and add a plan to your cart (where `:site` is a .com site).
- Proceed to checkout and purchase the plan.
- Assert that the `HappinessSupport` section on the thank you page shows placeholders until the receipt loads.
- Assert that the 'Ask a question' button links to https://wordpress.com/help/contact

*On the thank you page (Jetpack)*
- Visit `/plans/:site` and add a plan to your cart (where `:site` is a Jetpack site).
- Proceed to checkout and purchase the plan.
- Assert that the `HappinessSupport` section on the thank you page shows placeholders until the receipt loads.
- Assert that the 'Ask a question' button links to https://jetpack.me/support/

*On the thank you page (generic)*
- Visit `/checkout/:site/thank-you`
- Assert that `HappinessSupport` is displayed immediately without placeholders.

- [x] Code review
- [x] Product review

### CODE REVIEW

**Comment by scruffian** [comment]
@drewblaisdell - the changes look good. I added a commit to make the `isJetpack` property required, so that we don't get stuck in a placeholder state forever.

**Comment by stephanethomas** [comment]
I assume that you're also trying to fix https://github.com/Automattic/wp-calypso/issues/3932 and https://github.com/Automattic/wp-calypso/issues/3943 here.

Apart from fixing the developer documentation, that also means we want to remove placeholders from this component. However there are two things we forgot to address here. The first one is that we should remove the [`is-placeholder` class](https://github.com/Automattic/wp-calypso/blob/c6d36093d943c4b6ceffa7aa07bd4206ed42de37/client/components/happiness-support/index.jsx#L73) in the `render()` method, and update the [stylesheet](https://github.com/Automattic/wp-calypso/blob/c6d36093d943c4b6ceffa7aa07bd4206ed42de37/client/components/happiness-support/style.scss#L1) accordingly.

The second one is that we should update the `CheckoutThankYou` component to ensure a [boolean value](https://github.com/Automattic/wp-calypso/blob/c6d36093d943c4b6ceffa7aa07bd4206ed42de37/client/my-sites/upgrades/checkout-thank-you/index.jsx#L159) is always provided (right now it can pass `null` in certain conditions).

By the way, testing the generic `Thank You` page should probably be added to the testing instructions.

**Comment by mtias** [comment]
Should this be displayed inside a Card in devdocs?

**Comment by drewblaisdell** [comment]
> I assume that you're also trying to fix #3932 and #3943 here.
> Apart from fixing the developer documentation, that also means we want to remove placeholders from this component.

@stephanethomas Thanks for pointing that out, I wasn't aware of either issue. 

Based on @fabianapsimoes's comment [here](https://github.com/Automattic/wp-calypso/issues/3943#issuecomment-200811562), I think we should keep the placeholders. Please correct me if I'm wrong about this. I'll update the commit with the other changes.

> Should this be displayed inside a Card in devdocs?

@mtias Good idea - I'll make this change as well.

**Comment by drewblaisdell** [comment]
I:

- Added a commit to ensure that we only ever pass a boolean to `isJetpack`.
- Added a commit to wrap `HappinessSupport` in `Card` in devdocs.
- Updated the testing instructions.

**Comment by spncrb** [comment]
Product LGTM :+1: and now I have a JetPack testing site...

**Comment by Tug** [comment]
Code LGTM :+1:

**Comment by drewblaisdell** [comment]
Per a conversation with @spncrb elsewhere, I opened an issue to switch to using relative paths for the support link: https://github.com/Automattic/wp-calypso/issues/4320

**Pull request merged**
