### PR TITLE
Jetpack Plugins: Use pluralization in button text to fix i18n

### PR DESCRIPTION
**Pull request by rcoll**
Use plugralization instead of what was done in https://github.com/Automattic/wp-calypso/pull/8114

### CODE REVIEW

**Comment by yoavf** [comment]
This is better, but since not all languages follow the ` n=1 | n>1` rule for pluralization, the singular version should also include the `%(numUpdates)d` placehodler.
To use a specific text when `this.props.pluginUpdateCount ==1` you can add a condition and use a separate `translate()` call (without pluralization).

**Comment by rcoll** [comment]
Thanks @yoavf, that makes sense and I've updated to use a placeholder in the singular value as well. Thanks again for all your help here, I've learned a lot!

**Comment by psealock** [comment]
Thanks for the clarification @yoavf. LGTM

**Comment by lancewillett** [comment]
Hi @rcoll ready to merge or needs more review?

(This came up in a search for pull requests pending without an update in last 2 months.)

**Comment by rickybanister** [comment]
Thanks for checking on these @lancewillett. I'm going to get them wrangled, updated, and merged if possible.

**Comment by enejb** [comment]
:shipit: Looks good to me!

**Pull request merged**
