### PR TITLE
Reader: Full Post: Prefer the blavatar, then feed icon, then gravatar

### PR DESCRIPTION
**Pull request by blowery**
This only applies for the refresh. 

The full post view shows an icon in the sidebar, which currently is always the gravatar. However, many sites don't have good gravatars, especially higher traffic sites, like VIPs. Instead, try to show the blavatar instead, followed by the feed icon, followed by the gravatar.

Test live: https://calypso.live/?branch=update/reader-refresh/full-post-icon-selection

### CODE REVIEW

**Comment by blowery** [comment]
Fixes #7420

**Comment by blowery** [comment]
I left the blavs and feed icons un-circled, as it looks really odd most of the time. These things are generally site logos, not faces, so the circle ends up cutting off parts of the logo. Give it a shot and see how it feels.

**Comment by fraying** [comment]
Yeah, I was concerned about the circles, too. On the one hand, it will be weird if that element is not consistent. On the other, blavatars aren't usually in circles. So, it's a pickle.

My assumption was that we'd just encircle them all for consistency. But I agree we should test it and see how it feels.

**Comment by rickybanister** [comment]
We've long used squares for 'sites' and circles for avatars or 'heads'.

I don't think we should move away from that pattern here.

**Comment by fraying** [comment]
@rickybanister We're aware.

**Comment by rickybanister** [comment]
I'm not sure I understand—are you still advocating for circling the blavatars?

**Comment by fraying** [comment]
Let’s discuss this elsewhere.

**Comment by fraying** [comment]
Dearest designers: This does not need a design review yet! This is hidden behind a feature flag. We're testing here because it's the only way to see what happens with real data.

**Comment by blowery** [comment]
closing this off because we're going a different route

**Pull request closed without merging**
