### PR TITLE
DevDocs: Hide the code for devdocs playground components by default

### PR DESCRIPTION
**Pull request by scruffian**
For some components the code section is very long (like buttons). This hides the code behind a "Show Code" button:

screen shot 2018-04-25 at 10 48 30

screen shot 2018-04-25 at 10 48 37

To test go to /devdocs/action-card

### CODE REVIEW

**Comment by sixhours** [comment]
I think this looks good as a first iteration.

The current link/button doesn't stand out from the surroundings; it's easy to miss. I wonder if making it an actual button would give it some presence?

I'd also like to see a way to close the code block once opened (what if I click it by accident?)

But those are more enhancements than blockers, IMO.

**Comment by drw158** [comment]
Agreed with Caroline on it not being a blocker. I would prefer if the code block showed a few lines of code then, displayed a collapse/expand button.

**Comment by mapk** [comment]
After reviewing this, I agree as well that a toggle could be an enhancement, but not a blocker right now. Let's merge it.

**Comment by scruffian** [comment]
I have updated this to add a show/hide button for longer code blocks.

**Pull request merged**
