### PR TITLE
#353 prevented sidebar and master bar from displaying when printing a page.

### PR DESCRIPTION
**Pull request by nunohora**
This is a fix for bug #353 and it prevents the sidebar and top navbar (masterbar) from displaying on media print.

This is my first pull request for this project so please correct me in anything I did wrong :)

### CODE REVIEW

**Comment by dmsnell** [comment]
Works like a charm for me @nunohora :smile:

I'm going to let one of our designs such as @mtias or @folletto or @drw158 look this over, but if we don't hear from them soon we'll just merge it!

Thanks for your contribution 🤗

**Comment by nunohora** [comment]
@dmsnell no worries, glad to help!

**Comment by folletto** [comment]
Looks good! And great idea overall. :) 

Just two things:

1. Can you add a screenshot of the outcome for a couple sample pages, before and after? It's very useful not just for quick reviews, but also to have historical reference. :)
2. Can you elaborate the need of `!important`, compared to a solution that doesn't require it?

**Comment by nunohora** [comment]
Hi @folletto.

Here's the requested screenshots for a couple of pages before and after the change.

Followed sites before
screen shot 2016-10-11 at 00 48 06

Followed sites after
screen shot 2016-10-11 at 00 55 26

Recommendations before
screen shot 2016-10-11 at 00 49 41

Recommendations after
screen shot 2016-10-11 at 00 55 16

Regarding the use of !important, it seems that it's not required anymore! I know the use of !important is an anti-pattern and should be avoided. I fixed this issue a couple of months ago so I don't remember exactly why I decided to use it. I've updated my branch with the removal of this condition. Thanks!

**Comment by mtias** [comment]
This looks like a great first step to me. Thanks!

**Comment by dmsnell** [comment]
@mtias do you think this is ready to merge then?

**Comment by mtias** [comment]
🚢

**Pull request merged**
