### PR TITLE
renamed 'CheckoutSteps' to 'CheckoutStepGroup' - issue #45002

### LINKED ISSUE #45002: composite-checkout: Rename `CheckoutSteps` to `CheckoutStepGroup`
`CheckoutSteps` is not a very good name because it's too close to `CheckoutStep`. In addition, we already have a lot of wrappers in the composite-checkout package and they need to have distinct and semantic names to help distinguish each one's purpose.

### PR DESCRIPTION
**Pull request by marsonya**
#### Changes proposed in this Pull Request

Fixes #45002

Issue Subject: composite-checkout: Rename `CheckoutSteps` to `CheckoutStepGroup`
Issue Description: CheckoutSteps is not a very good name because it's too close to CheckoutStep. In addition, we already have a lot of wrappers in the composite-checkout package and they need to have distinct and semantic names to help distinguish each one's purpose.

I have renamed `CheckoutSteps` to `CheckoutStepGroup` all over the project

#### Testing instructions

*

Fixes #
I have renamed `CheckoutSteps` to `CheckoutStepGroup` all over the project

### CODE REVIEW

**Review by nbloomf — APPROVED** [review]
This is a nice improvement. Thanks!

**Comment by sirbrillig** [comment]
Nearly ready to merge, but there's one place Prettier wasn't run and it's causing an error on the linter:

The file `packages/composite-checkout/test/checkout.js`:

```
Replace `{·stepObjectsWithStepNumber.map(·createStepFromStepObject·)·}` with `⏎↹↹↹↹↹{·stepObjectsWithStepNumber.map(·createStepFromStepObject·)·}⏎↹↹↹↹`
line 662, col 24, Error - Replace `{&#183;stepObjectsWithStepNumber.map(&#183;createStepFromStepObject&#183;)&#183;}` with `&#9166;&#8633;&#8633;&#8633;&#8633;&#8633;{&#183;stepObjectsWithStepNumber.map(&#183;createStepFromStepObject&#183;)&#183;}&#9166;&#8633;&#8633;&#8633;&#8633;` (prettier/prettier)
```

**Review by sirbrillig — CHANGES_REQUESTED** [review]
Just making it clear that the linting errors need to be fixed.

**Comment by sirbrillig** [comment]
I think this may be abandoned, but I'll ping one more time, because I think it's great work! @marsonya, could you rebase this and fix the linting errors?

**Pull request closed without merging**
