### PR TITLE
Allow for serving development fallback builds

### PR DESCRIPTION
**Pull request by sgomes**
`npm run start` is a convenient way of getting a development build of Calypso that watches changes and builds on the fly as they happen. Since most development work takes place in modern browsers, the build target for `npm run start` is 'evergreen'; that is, our set of supported evergreen browsers.

However, it's sometimes useful to be able to spin up a development server targeting older browsers, to e.g. track down a bug. This PR makes it easy to do that, by running `npm run start-fallback` or alternatively `DEV_TARGET=fallback npm run start`.

Note that this PR focuses on `npm run server`, and doesn't add support for `DEV_TARGET` to any other tasks.

#### Changes proposed in this Pull Request

* Add new `DEV_TARGET` environment variable, to specify which target to build for, when in development. When missing, `'evergreen'` is assumed.
* Update build files and server code to handle new environment variable.

#### Testing instructions

To test fallback build:

* `npm run clean`
* `npm run start-fallback`
* Open `calypso.localhost:3000` and ensure that JS files are coming from `/calypso/fallback/`. Open one of them and ensure that there is no ES2015+ syntax. Try searching for e.g. `const ` (don't forget the space), and ensure that there are no instances of it outside of comments.

To test that the default is still an evergreen build:

* `npm run clean`
* `npm run start`
* Open `calypso.localhost:3000` and ensure that JS files are coming from `/calypso/evergreen/`. Open one of them and ensure that there is some ES2015+ syntax. Try searching for e.g. `const ` (don't forget the space), and ensure that there are some instances of it outside of comments.

### CODE REVIEW

**Comment by noahtallen** [comment]
I tested this PR locally, running the commands and opening them in IE11 (I was using windows subsystem for linux to run everything). 

✅ The files are loaded from calypso/fallback when I run `npm run start-fallback`

However, I still see errors in the console which prevent me from running the dev build in ie11:
1. `Script1003: Expected ':' in vendors~entry-domains-landing~entry-gutenboarding~entry-login~entry-main.js (3274,1)`
2. `Script438: Object doesn't support property or method 'AppBoot' in calypso.localhost:3000 (25,530)`

I know those existed before this branch, but I was wondering if this is supposed to fix that :)

**Comment by noahtallen** [comment]
basically, `AppBoot` is just not defined on the global window object in IE11. I have no clue why 🤷‍♂

**Comment by p-jackson** [comment]
> basically, AppBoot is just not defined on the global window object in IE11

I think this means an exception was thrown which means the line that does `window.AppBoot = ...` never runs.

**Review by p-jackson — CHANGES_REQUESTED** [review]
I was mis-reading the error message; it's that a colon is _expected_.

The code is loading from `/calypso/fallback` but there's still modern JavaScript in there:

```javascript
module.exports = {
  iconsThatNeedOffset,
  iconsThatNeedOffsetX,
  iconsThatNeedOffsetY,
};
```

This is using the shorthand object notation.

**Comment by noahtallen** [comment]
> it's that a colon is expected
 
Ahhh I was also misreading that. Nice catch btw! That would definitely cause an issue with testing in ie

**Comment by yansern** [comment]
Ran a quick test. Fallback scripts are now served but scripts are still not ES5 on IE11, hence unable to execute. 

If you look inside our babel config, it doesn't actually target ES2015.

And if you look inside webpack config, minifier does not run during development mode. TerserJS's `ecma` option by default transpile to ecma version 5.

So I believe the transpilation is being done by TerserJS, and it is not being done during development mode for fallback scripts.

So there are 2 ways to fix this, either:
- fix babel config by targeting ES5 when fallback browser is detected from browserslist
- or enable minification (not really, just enabling TerserJS without actually minifying, more like beautifying into ES5).

**Comment by sgomes** [comment]
Thank you for the investigation, everyone! Yes, it does look like not all the same steps are applied on a development build, great catch!

I'll see if I can get that working there too.

**Comment by sgomes** [comment]
I looked into it, and the issue is unrelated to this PR (I'll fix it separately).

To explain, we normally don't expect node modules to contain ES2015+ code. For those that do contain it, we have a whitelist in `calypso-build`, that tells us they need to be transpiled. `gridicons`, which is where the above code originates from, isn't on that list and needs to be added to it.

It isn't clear to me why this hasn't been a problem in production before, but my guess is that Terser ends up "accidentally" transpiling that code while making it smaller, resulting in an ES5 output. Since dev builds don't run Terser that doesn't happen here, and hence the issue.

I've experimentally verified that adding `gridicons` to the whitelist solves the issue, and I'm able to use Calypso in IE11 after that fix.

**Comment by sgomes** [comment]
Rebased on master to pick up the fix in #40895. If you delete any local branches of this PR you might have and pull in the latest version, you should be able to get a working Calypso in IE11 with `npm run start-fallback`!

**Review by noahtallen — APPROVED** [review]
Thank you for resolving that issue! <3 This works perfectly for me now. IE11 boots calypso correctly using the fallback build, and I can even add `debugger` statements now. This is a great improvement for IE11 debugging. _Now to actually start debugging........._

**Review by p-jackson — APPROVED** [review]
Works great!

Also tested that the fallback version works in FF, which it does (as expected)
Also tested that `npm start` still works as expected.

🎺 

I kicked off the failing tests again.

**Comment by sgomes** [comment]
The E2E failures seem unrelated, so I'm going to go ahead and merge this one. Thanks, everyone!

**Pull request merged**
