### PR TITLE
Reader: show single site blocked message for site and feed streams

### PR DESCRIPTION
**Pull request by bluefuton**
Fixes https://github.com/Automattic/wp-calypso/issues/3669.

Currently, when a site is blocked, all post cards for that site turn into a 'blocked' card. This works reasonably well on mixed streams with content from lots of sites, but it's a pretty poor experience on site and feed streams, which end up looking like this:

34960462-c2660cfc-f9ef-11e7-8071-9bb64cb634f6

This PR changes it to look like this:

screen shot 2018-03-08 at 14 28 38

### Notes

I originally tried a hybrid of feed header and blocked message, but it didn't look great.

The illustration seemed the most neutral of those available - what do you think @jancavan?

When loading the site or feed stream afresh, you may see a flash of the site's posts while we're waiting for the API response. We can partially address this in the future by not returning posts for sites the user has blocked, but ideally we'd sync site blocks in the same way we currently do for follows. This would mean a new endpoint to return current site blocks.

### To test

Try blocking a feed like http://calypso.localhost:3000/read/feeds/59175237 and make sure the blocked message appears as above.

The corresponding site stream for the feed should also show the blocked message: http://calypso.localhost:3000/read/blogs/122301668.

### CODE REVIEW

**Comment by westi** [comment]
This seems like a good solution to me.

**Comment by jancavan** [comment]
> When loading the site or feed stream afresh, you may see a flash of the site's posts while we're waiting for the API response.

Yeah, I noticed this happening too.

> If you'd like to see posts from TIME again, use Unblock.

What about...

"Unblock this site if you'd like to see posts from TIME again."

>The illustration seemed the most neutral of those available

I think we can use this (but sized smaller):
screenshot 2018-03-08 14 09 40

Something that better communicates that "something is wrong" vs making it look similar to the rest of our empty states.

**Comment by bluefuton** [comment]
Excellent suggestions @jancavan. I'll make the updates now.

**Comment by bluefuton** [comment]
Updated version:

screen shot 2018-03-09 at 13 50 50

**Comment by bluefuton** [comment]
Actually - I'll remove the duplicate of "this site" so the second line says:

"Unblock it if you'd like to see posts from x again."

**Comment by westi** [comment]
Functionally this is fine.

But I see this image when booting calypso.live?

screen shot 2018-03-09 at 15 56 56

**Comment by bluefuton** [comment]
@westi doesn't sound like calypso.live has picked up the last two commits. I know there were some problems with dserve on Friday. Does it work locally?

**Comment by jancavan** [comment]
> Does it work locally?

Yes, this is what I did.

**Comment by jancavan** [comment]
@bluefuton @westi What do you think about adding back the site stream info? This way, it'd be easier to determine what site has been blocked should users decide to unblock it:

(These are very quick mockups so the block copy isn't accurate.)

No avatar:
screenshot 2018-03-12 11 42 48

Has avatar:
screenshot 2018-03-12 11 43 30

It kinda looks awkward if they have an avatar because it competes with the illustration below it, but it's not bad, or we could just get rid of the illustration entirely:

No avatar:
screenshot 2018-03-12 11 50 20

Has avatar:
screenshot 2018-03-12 11 49 48

I got this idea from an old discussion as to what the expectation would be when blocking a site:

> 1. blocked sites don’t get recommended to me
> 2. blocked sites don’t appear in search results
> 3. blocked sites don’t appear on tag pages
> 4. If I go to a blocked site view, I can see the site name and header info, but no posts would appear, instead I’d get a “you’re blocking this, undo?” message.

**Pull request merged**
