### PR TITLE
Refactor theme install action.

### PR DESCRIPTION
**Pull request by budzanowski**
### Info

Installing a theme that had a parent theme required also installation of that parent theme.
Code for that was working but was using promises in non optimal way.

### Testing
Verify that on Jetpack site themes that have parent themes still install successfully.
Example themes with parents Goran( Edin ) or Sidekick( Superhero )

### CODE REVIEW

**Comment by ockham** [comment]
Thinking some more about this, are we actually guaranteeing that both the child and parent are installed before attempting to activate the child?

Parent theme install is only attempted after child install ([ref](https://github.com/Automattic/wp-calypso/blob/50c221f6efb388d3a1371ec3d7b9b4596a4ea97e/client/state/themes/actions.js#L497)), so that's fine. But is it possible that we should `return` that `dispatch` so that [this `.then()`](https://github.com/Automattic/wp-calypso/blob/50c221f6efb388d3a1371ec3d7b9b4596a4ea97e/client/state/themes/actions.js#L609) is only called afterwards? (I'm honestly not sure.)

**Comment by seear** [comment]
> But is it possible that we should return that dispatch so that this .then() is only called afterwards?

@ockham Yeah, I pondered this very question in the PR where we moved the parent install, and concluded that `return` would only make a difference to the control flow if there was something after the `return` statement in the block, which there isn't.

**Comment by seear** [comment]
> Yeah, I pondered this very question in the PR where we moved the parent install, and concluded that return would only make a difference to the control flow if there was something after the return statement in the block, which there isn't.

However :) , looking at the code again, I think my conclusion was wrong. We need to return the parent install promise, otherwise the activate code is only waiting on the first install.

**Comment by ockham** [comment]
> However :) , looking at the code again, I think my conclusion was wrong. We need to return the parent install promise, otherwise the activate code is only waiting on the first install.

Yeah, looking at https://github.com/reactjs/redux/issues/1676#issuecomment-215413478, I was coming to the same conclusion 😄 

@budzanowski Wanna add that `return` as part of this PR?

**Comment by budzanowski** [comment]
I was thinking about it when working on this :) And concluded that we do not need this.
For activation to succeed we only need to have child theme installed. We need both parent and child so the child can actually work. But as it turned out child will be still active if parent is not present. Active but broken. The only real waiting required is between installs as it turned out ( from observation ) that having two installs too close to each other can cause the second install to fail with unknown reason. So having chain of actions `install child -> activate child -> install parent` is absolutely fine.

**Pull request merged**
