### PR TITLE
Update instructions to unlock domains in Squarespace

### PR DESCRIPTION
**Pull request by leonardost**
## Proposed Changes

Update Google Domains transfer instructions to Squarespace.

## Why are these changes being made?

All Google Domains that remained with Google were transferred to Squarespace. The Google Domains interface isn't accessible anymore, so we need to update our domain transfer instructions to use Squarespace.

## Testing Instructions

Visit `/setup/google-transfer/` and ensure the design changes added in p5VYbhFP6gBHwY1ACQK14d-fi match the content of this PR.

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Review by delputnam — APPROVED** [review]
This looks correct to me now.

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/16421629

Some locales (Hebrew, Japanese) have been temporarily machine-translated due to translator availability. All other translations are usually ready within a few days. Untranslated and machine-translated strings will be sent for translation next Monday and are expected to be completed by the following Friday.

Hi @leonardost, could you please edit the description of this PR and add a screenshot for our translators? Ideally it'd include all of the following strings:
- `Once you've opened your domain's settings, ensure that your domain is unlocked.`
- `Request your transfer code. You'll find this at the bottom of your domain's settings page. Squarespace will email you the code (may take several hours) for you to copy to your clipboard.`
- `Transfer code`
- `Enter your domain names and transfer codes below.`
- `Transfer your Squarespace domains`

Thank you in advance!

**Comment by paulbonahora** [comment]
Thank you so much for this! 

As noted [here](https://a8c.slack.com/archives/C014TPFLP4Z/p1721895467699139?thread_ts=1721844043.088869&cid=C014TPFLP4Z), could we please replace the screenshot on Step 2 for the one below?

Screenshot 2024-07-25 at 10 13 29

Quick context: the image that I uploaded on the Figma file said `bonahora.com` (my test domain) but it was only overlayed with a manual text on Figma with `mydomain.com` (but the actual file had my domain). The image now reflects `mydomain.com` in the actual screenshot. Thank you!

**Comment by rafaelgallani** [comment]
@paulbonahora Ramy (@ramynasr) handled this one in #92976. Thanks!

**Comment by paulbonahora** [comment]
Thank you all for pushing this forward!

**Pull request merged**
