### PR TITLE
Untangling: add upsell to Advanced Tools and Settings subtabs

### PR DESCRIPTION
**Pull request by fushar**
Fixes https://github.com/Automattic/dotcom-forge/issues/9928

## Proposed Changes

This PR adds subtab upsells to:

- Advanced Tools -> {Staging Site, SFTP, Database}
- Settings -> Web server

## Why are these changes being made?

pbxlJb-6ye-p2

### FREE SITE

1. Open /sites
2. Click a Free site
3. Go to Settings -> Web server, verify you see the upsell:

image

4. Verify you can go through the upsell flow.

### ECOMMERCE TRIAL SITE

1. Sign up for an ecommerce trial site at https://wordpress.com/ecommerce/.
1. Open /sites
2. Click the new site
3. For each {Advanced Tools -> Staging site, Advanced Tools -> SFTP, Advanced Tools -> Database, Settings -> Web Server}:
    - Verify you can see the upsell.
    - Verify the Upgrade button link is correct (compare with the Web server above) (so that you don't have to go through the whole flow)

## Pre-merge Checklist

- [x] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [x] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [x] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [x] Have you checked for TypeScript, React or other console errors?
- [x] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [x] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
    - [x] For UI changes, have we tested the change in various languages (for example, ES, PT, FR, or DE)? The length of text and words vary significantly between languages. 
- [x] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Comment by taipeicoder** [comment]
There seems to be an issue for eCommerce trial sites, where the upsell banner links to /sites/tools. The problem is that the eCommerce doesn't display the Advanced Tools as a tab upsell.

Screenshot 2024-11-27 at 9 29 24 AM

**Comment by fushar** [comment]
> There seems to be an issue for eCommerce trial sites, where the upsell banner links to /sites/tools. The problem is that the eCommerce doesn't display the Advanced Tools as a tab upsell.

@taipeicoder Nice catch, I've fixed that!

**Review by taipeicoder — APPROVED** [review]
LGTM 👍

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/17027530

Some locales (Hebrew, Japanese) have been temporarily machine-translated due to translator availability. All other translations are usually ready within a few days. Untranslated and machine-translated strings will be sent for translation next Monday and are expected to be completed by the following Friday.

Thank you @fushar for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/17027530).

**Pull request merged**
