### PR TITLE
Gutenboarding launch flow: add final step summary

### LINKED ISSUE #44450: Gutenboarding: add free summary to launch flow
At the end of free launch flow (without a paid plan selected), show a summary with a design similar to composite checkout:
image

**Requirements**
- _Edit_ / _Change_ links should open the relevant step from the launch flow.
- When some of the launch steps are not completed, display an unchecked state of the corresponding items and order them at the bottom of the list.

Context and more details: pcbO8q-4l-p2

### PR DESCRIPTION
**Pull request by razvanpapadopol**
#### Changes proposed in this Pull Request
* Add summary to final step of the launch flow
* Link to each of the previous step from summary items
* Show completion status of each step
* Enable _Launch_ button only if all steps are completed 

#### Testing instructions
* Create a site using `/new` flow.
* Sandbox the site.
* Click _Complete Setup_ in editor,
* Check the last step in the sidebar with various combinations of completed steps,

#### Screenshots
* **No step completed (disabled sidebar button)**
Screenshot 2020-08-11 at 13 41 48

* **Without a selected plan**
Screenshot 2020-08-11 at 13 42 45

* **Without site name**
Screenshot 2020-08-11 at 13 44 04

* **All steps completed (Custom domain and paid plan)**
Screenshot 2020-08-11 at 13 31 27

* **All steps completed (sub-domain and Free plan)**
Screenshot 2020-08-11 at 13 31 38

Fixes #44450

### CODE REVIEW

**Comment by simison** [comment]
Heads up to @Automattic/shilling team that we're exporting some componentry from composite-checkout. Hope you don't mind;

This is a temporary step to align visuals in launch summary with the actual checkout, which we will integrate soon to this flow (I'll talk more about that project separately).

If you'd prefer to not allow exporting these components, we can come back and revert this change, and just duplicate these at our end. Let us know!

**Comment by simison** [comment]
We should pull this domain from domain recommendations:

Screenshot 2020-08-11 at 13 51 59

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/4220469

Thank you @razvanpapadopol for including a screenshot in the description! This is really helpful for our translators.

**Comment by sirbrillig** [comment]
> If you'd prefer to not allow exporting these components, we can come back and revert this change, and just duplicate these at our end. Let us know!

Thank you for the heads-up! I am totally ok with adding the new exports, but please add them to the README in the package!

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/4220469).

**Comment by sirbrillig** [comment]
FYI, to close the loop: I've added the missing docs for exporting those components in https://github.com/Automattic/wp-calypso/pull/46169 and also renamed the components to something more readable.

**Pull request merged**
