### PR TITLE
Jetpack Plans: Add Easy Site Migration to Jetpack Personal Plan feature listing.

### PR DESCRIPTION
**Pull request by oskosk**
#### Chages introduced by this PR

Adds the **Easy Site Migration** item to the list of Jetpack Personal Plan features. 

#### Testing instructions

1. Visit `http://calypso.localhost:3000/plans/{site-slug}` where site is a Jetpack site's slug.
1. Confirm you see `Easy Site Migration` listed among the Jetpack Personal Plan features (Both monthly and yearly).

### CODE REVIEW

**Comment by enejb** [comment]
:shipit: Works as expected!

**Comment by lamosty** [comment]
Working fine!

However, I noticed that it's not aligned nicely:

selection_235

Maybe we could switch some features so that the Easy Site Migration feature is on the same line across all the plans.

What do you think?

**Comment by retrofox** [comment]
yup, I wonder if there is a possibility to reduce the text there since we can explain this feature via the Popover. 

image

image

**Comment by lamosty** [comment]
> yup, I wonder if there is a possibility to reduce the text there since we can explain this feature via the Popover.

Note: the issue I posted and the issue @retrofox posted are two separate ones. :)

**Comment by oskosk** [comment]
Thanks @lamosty . I've added a commit rearranging the placement of the Easy Site Migration Item to be just after Spam Protection in the three plans. Looking like this now:

image

**Comment by lamosty** [comment]
> I've added a commit rearranging the placement of the Easy Site Migration Item to be just after Spam Protection in the three plans. Looking like this now:

Perfect.

I think the PR is ready for :shipit:. If we decide to fix the issue @retrofox mentioned, I think we should do it in another PR as it's not related to this one.

**Pull request merged**
