### PR TITLE
Jetpack Plans Page: Align Features Toggle

### PR DESCRIPTION
**Pull request by cbauerman**
#### Changes proposed in this Pull Request

* Update alternative Jetpack Plans page to better align the features expansions

Untitled 4

#### Testing instructions

1. Check the `Show/Hide Features` toggle at various screen widths. Make sure the toggles are never misaligned in a row.

### CODE REVIEW

**Review by rcanepa — APPROVED** [review]
LGTM. It works nicely!

**Comment by keoshi** [comment]
This is looking good, but I generally worry about setting a `min-height` on elements that don't need it. Suggested a different approach on 1196341175636977-as-1198178683923489, which should always work no matter what content the cards might eventually contain.

Would love to hear your thoughts on this:

```
.jetpack-product-card-alt {
  display: flex;
  flex-direction: column;
}

(.foldable-card element that holds the show/hide features element; needs an extra class) {
  margin-top: auto;
}
```

**Comment by cbauerman** [comment]
> This is looking good, but I generally worry about setting a `min-height` on elements that don't need it. Suggested a different approach on 1196341175636977-as-1198178683923489, which should always work no matter what content the cards might eventually contain.
> 
> Would love to hear your thoughts on this:
> 
> ```
> .jetpack-product-card-alt {
>   display: flex;
>   flex-direction: column;
> }
> 
> (.foldable-card element that holds the show/hide features element; needs an extra class) {
>   margin-top: auto;
> }
> ```

I spent quite a while trying to get the `flex` approach to work correctly. With giving the `FoldableCard` auto top margins it creates a situation when long features are expanded like this:
Screen Shot 2020-10-12 at 10 15 30 AM

I believe the root of the problem is that there is not a widely supported css mechanism for coordinating rendering across the elements in the row. The `min-height` is a hack that will not work perfectly every time ( there may be languages where the translated copy is even longer, for example ) but is was the only way where I could keep the toggles in the red circle of the screenshot.

**Comment by cbauerman** [comment]
> This is looking good, but I generally worry about setting a `min-height` on elements that don't need it. Suggested a different approach on 1196341175636977-as-1198178683923489, which should always work no matter what content the cards might eventually contain.
> 
> Would love to hear your thoughts on this:
> 
> ```
> .jetpack-product-card-alt {
>   display: flex;
>   flex-direction: column;
> }
> 
> (.foldable-card element that holds the show/hide features element; needs an extra class) {
>   margin-top: auto;
> }
> ```

I spent quite a while trying to get the `flex` approach to work correctly. With giving the `FoldableCard` auto top margins it creates a situation when long features are expanded like this:
Screen Shot 2020-10-12 at 10 15 30 AM

I believe the root of the problem is that there is not a widely supported css mechanism for coordinating rendering across the elements in the row. The `min-height` is a hack that will not work perfectly every time ( there may be languages where the translated copy is even longer, for example ) but I am not sure what other options we have in this case.

**Comment by keoshi** [comment]
@cbauerman Yeah, I noticed that behavior afterwards. My suggestion might make more sense when combined with this PR: https://github.com/Automattic/wp-calypso/pull/46404

**Comment by keoshi** [comment]
@cbauerman Never mind, just noticed that creates a different issue. We might need all of these changes (min-height, flex-direction, margin-top) to make it work as expected.

**Comment by eeeeevon13** [comment]
Alignment looks good to me, but we don't want to extend or open any of the top row items that a user did not click on.  I believe there is an asana card for this

confusing
If it's terribly difficult to only open one at a time, then it would be much better to open all of the

**Review by wp-desktop — CHANGES_REQUESTED** [review]
WordPress Desktop CI Failure for job "wp-desktop-mac".

@cbauerman please inspect this job's build steps for breaking changes at [this link](https://circleci.com/gh/Automattic/wp-calypso/923638). For temporal failures, you may try to "Rerun Workflow from Failed".

Please also ensure this branch is rebased off latest Calypso.

**Pull request merged**
