### PR TITLE
Framework: Upgrade React to 15.3.0

### PR DESCRIPTION
**Pull request by aduth**
This pull request seeks to bump the minor version of React to its latest version, from 15.1.0 to 15.3.0.

- [15.2.0 changelog](https://github.com/facebook/react/blob/master/CHANGELOG.md#1520-july-1-2016)
- [15.3.0 changelog](https://github.com/facebook/react/blob/master/CHANGELOG.md#1530-july-29-2016)

While there are a number of general fixes, I'm most allured by the promise for more _speeeeed_ (https://github.com/facebook/react/pull/7005). Well, potential speed anyways.

__Testing instructions:__

Verify that there are no regressions in using the application from the upgrade. Examine changes included in the upgrade changelog and test against suspected use-cases that may be affected.

Your console will become very noisy as a result of this particular change:

>Add warning for unknown properties on DOM elements.

I imagine many of these warnings are a result of applying a blanket spread of `this.props` to a DOM element. It's probably a good thing that we seek to clean these up, as I might imagine they have the potential to lead to some unexpected circumstances. In any case, it is what it is. ¯\\\_(ツ)\_/¯

Test live: https://calypso.live/?branch=update/react-15-2

### CODE REVIEW

**Comment by aduth** [comment]
Rebased to resolve merge conflicts, upgraded to 15.2.1.

Apparently React 15.3.0 is expected very soon, see https://github.com/facebook/react/issues/7220.

**Comment by aduth** [comment]
Rebased again to upgrade to 15.3.0 this time.

**Comment by ehg** [comment]
I ran the e2e tests on this, while eating dinner, and they passed. Also checked SSR was working for `/theme/x`. Will continue to have a play.

With regard to the props warnings, I'll put together a list of components that generated the warnings when hit by e2e tests.

**Comment by ehg** [comment]
> I'll put together a list of components that generated the warnings when hit by e2e tests.

Maybe this is correct, and there's not _that_ many components to fix :)
```bash
$ pcregrep -M 'Found console error.*\n.*in.*created' unknownprops | sort -u | uniq
    in a (created by Button)
    in a (created by Card)
    in button (created by Button)
    in div (created by Content)
    in div (created by EditorAuthor)
    in div (created by ReactTransitionGroup)
    in input (created by FormTextInput)
    in select (created by FormSelect)
```

**Comment by aduth** [comment]
Looks like a shorter list than I'd expected 😆 

In any case, these are development warnings, and I'm fairly certain (though should confirm) they're not present in production environments. I don't really think we need necessarily address them in this pull request, as I'm sure people will (hopefully) be motivated to fix them over time to silence their consoles. What do you think?

**Comment by ehg** [comment]
> Looks like a shorter list than I'd expected 😆

I have no doubt that it's inaccurate ;)

> I don't really think we need necessarily address them in this pull request, as I'm sure people will (hopefully) be motivated to fix them over time to silence their consoles. What do you think?

I agree. I don't think these errors should block this PR.

Anyway, I've been through the `CHANGELOG`, and tried to break things. Can't find anything wrong so far. So I'd give this a 👍

**Comment by aduth** [comment]
Thanks for the review @ehg !

**Pull request merged**
