### PR TITLE
Remove list view on hover background color overrides

### PR DESCRIPTION
**Pull request by lsl**
Related to #

## Proposed Changes

* Remove on hover color overrides for list view to match the site list behavior table view

## Testing Instructions

* /sites
* Click into a site overview
* Confirm background color on hover h

Before

https://github.com/user-attachments/assets/21d1137b-9c26-4711-8294-747ae6744c79

After

https://github.com/user-attachments/assets/5c0949dd-c8dd-41d1-9ad4-a62f2ab58bb8

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
    - [ ] For UI changes, have we tested the change in various languages (for example, ES, PT, FR, or DE)? The length of text and words vary significantly between languages. 
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Review by okmttdhr — APPROVED** [review]
LGTM ✅

**Comment by okmttdhr** [comment]
I'm starting to feel that we could remove the selected color as well, given that other pages using DataViews do not override it. Having this override only in the Sites Dashboard seems suboptimal.

**Comment by lsl** [comment]
We're matching core but the colors are off, test page 1 is selected, about page on hover

Screenshot_2024-11-29_13-36-13

**Comment by lsl** [comment]
Or was that color difference the thing you're referencing?

**Comment by okmttdhr** [comment]
I'm not sure what you mean by 'colors are off,' but we do have selected color overrides in place, which would make it differ from Core!

**Comment by lsl** [comment]
> colors are off,

Blue is a bit lighter in core, I think we're matching now. (you removed the overrides)

**Pull request merged**
