### PR TITLE
Stats: Refactor component StatsViews and its styles

### PR DESCRIPTION
**Pull request by dognose24**
#### Proposed Changes

* Delete the unused component `StatsViews`.
* Refactor remaining `StatsViewsMonths` styles into existing shared styles.

#### Testing Instructions

* Spin up this change with the Calypso Live link.
* Navigate to the Stats `Insights` page.
* Ensure the All-time insights table styles work as previously.
* Navigate to the Stats `Post Detail` page with the feature flag `/stats/post/${post-id}/${site-id}?flags=stats/enhance-post-detail`.
* Ensure the All-time Insights table styles work as previously.

#### Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [x] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

Related to #71762

### CODE REVIEW

**Review by wilmersondasilva — APPROVED** [review]
The components looked and worked as previously.  👍 

One tiny detail that I noticed, though, and it was already happening before, was that the `border-radius` on this component is smaller on the right side. On the left, we have `border-radius: 4px`, and on the right `border-radius: 2px`. I think it would be worth creating a follow-up issue to fix it.

image

**Review by a8ck3n — APPROVED** [review]
This looks pretty sharp! Do we want to add the Jetpack Colophon along the bottom of this page, possibly in a follow up PR?

JetpackColophon

**Comment by dognose24** [comment]
> was that the border-radius on this component is smaller on the right side

Nice catch! Fixed it in [8b39cf1](https://github.com/Automattic/wp-calypso/pull/72082/commits/8b39cf1b94703c62461b79efae78b3058e597a9c).

> Do we want to add the Jetpack Colophon along the bottom of this page, possibly in a follow up PR?

Yes. Let's tackle it in the follow-up PR.

**Comment by wilmersondasilva** [comment]
> Nice catch! Fixed it in [8b39cf1](https://github.com/Automattic/wp-calypso/pull/72082/commits/8b39cf1b94703c62461b79efae78b3058e597a9c).
> 

It looks great, @dognose24! Thanks for fixing it!

**Review by wilmersondasilva — APPROVED** [review]

**Pull request merged**
