### PR TITLE
Reader site titles: get rid of "Site Title"

### PR DESCRIPTION
**Pull request by samouri**
(Site Title) is ugly.  Lets fallback to the url in the case where the user never changed from the default

To test:
- look at this url before and after: http://calypso.localhost:3000/read/search?isSuggestion=1&q=autoblog618&show=Sites

you should see "Site Title" before, url after

### CODE REVIEW

**Comment by fraying** [comment]
Before:

screen shot 2017-06-30 at 1 25 16 pm

After:

screen shot 2017-06-30 at 1 25 26 pm

Which is good! But it should still be limited to 1 line.

**Comment by bluefuton** [comment]
@samouri should we also change this in the post card while we're at it?

screen shot 2017-07-01 at 15 30 16

**Comment by fraying** [comment]
@bluefuton Oh my yes. Good catch. Yes please. (cc @samouri)

**Comment by samouri** [comment]
> @samouri should we also change this in the post card while we're at it?

a few extra characters :). Yay for reusing the same function.

**Comment by jancavan** [comment]
screenshot 2017-07-05 10 38 10

The blue URLs should probably not wrap. I'll create a separate PR for it.

**Pull request merged**
