### PR TITLE
Add messaging to login via QR Code 

### PR DESCRIPTION
**Pull request by zwarm**
#### Proposed Changes

This change adds a static notice message to the "Login via the mobile app" page to alert users that the feature is not available if they have enabled 2FA on their account. 

NOTE: This PR was originally #68917, but I had some github issues and did not want to screw things up, so I closed that one and created this one.

This new message may still need translation. The string translation was done as part of the original PR, but I am adding the label here because I'd don't know if that carries over. @enejb - do you know if this was correct? I think it's okay - all green from CI

Screen Shot 2022-12-05 at 11 23 09 AM

FYI: @paulforgione 

#### Testing Instructions
Navigate to the log in page
Click on "Login via the mobile app"
✅ Verify that the notify message "Login via the mobile app is not available if you've enabled two-step authentication on your account" is shown

#### Pre-merge Checklist
- [X] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [X] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [X] Have you checked for TypeScript, React or other console errors?
- [X] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [x] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [X] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

**Comment by worldomonation** [comment]
@zwarm I wrote an article on how to avoid the "review bomb" which may be helpful to avoid #68917: p7H4VZ-3Oh-p2#comment-10717

**Comment by zwarm** [comment]
> I wrote an article on how to avoid the "review bomb"  

Thank you @worldomonation ... yeah, that was me "rebase > thought all was good > commit > push > not good and directed to pull > pulled > tried to push again > asked to merge > resolved conflicts > pushed" 💣 . Since I'm a one-off calypso dev, I didn't want to screw anything up and my changes were small, it was easier to start a new branch. But now I have a path to follow in the future. Thank you 🙇

**Comment by enejb** [comment]
@zwarm I think we should bump the contrast of the text. Currenty I think it is too low. 

Lets use `var(--color-neutral-50)` instead of `var(--color-neutral-20)`! 
other then then that I think the changes look great! Nice work! 

With the neutral-50. 
Screenshot 2022-12-05 at 1 17 58 PM

**Comment by zwarm** [comment]
@enejb - Had to also darken the bold part, but I think it looks good now. :) wdyt?
Screen Shot 2022-12-06 at 7 32 12 AM

**Review by enejb — APPROVED** [review]
The change looks good to me. Nice work!

**Pull request merged**
