### PR TITLE
Add Jetpack logo as icon for plans.

### PR DESCRIPTION
**Pull request by mtias**
image

### CODE REVIEW

**Comment by rickybanister** [comment]
I think this is a nice small step toward positioning Jetpack as the premium layer on top of everything. Let's see how it goes.

**Comment by tyxla** [comment]
Beautiful ❤️

**Comment by drw158** [comment]
We should probably alter the svg so that it falls in line with the Gridicon guidelines. Really this just means making the circle smaller — right now the Jetpack circle is bigger than the other icons that are circular.

If this stays, which it probably will, we should do what we did with the My Sites W icon and customize it as well as include it in Gridicons.

**Comment by apeatling** [comment]
This doesn't make much sense to me right now, if we had shared Jetpack and WordPress.com plans, then maybe.

**Comment by mtias** [comment]
@apeatling all the plan tiers in WP.com are powered by Jetpack features on top of WordPress, that's  the main spirit of it.

**Comment by apeatling** [comment]
Right, I understand that, but I don't think our users will at this point. Maybe in the future when we push the Jetpack brand more.

**Pull request merged**
