### PR TITLE
Activity Logs: Activate/Deactivate actions and http handlers

### PR DESCRIPTION
**Pull request by seear**
Adds rewind activate/deactivate actions and http middleware.

Part of splitting PR #10862 into merge-size chunks. Follows on from rewind status actions in #14660.

This PR sticks closely to the original #10862, keeping the `_SUCCESS` and `_FAILURE` actions so that we can show UI feedback on the toggle button whilst the requests are in-flight.

**To Test**
* PR contains unit tests
* Real network requests can be fired using following console commands:
```
dispatch( { type: 'REWIND_ACTIVATE_REQUEST', siteId: '{site}' } )
dispatch( { type: 'REWIND_DEACTIVATE_REQUEST', siteId: '{site}' } )
```
*Expected Results*
* Use a jetpack site with vaultpress for successful responses. Note that the `use_rewind` field in the status response should toggle on and off after activate/deactivate. To get the status, use:
```dispatch( { type: 'REWIND_STATUS_REQUEST', siteId: '{site}' } )```
* When using a non-vaultpress site, an error notice should display on activate/deactivate
screen shot 2017-06-06 at 11 53 25

### CODE REVIEW

**Comment by seear** [comment]
> I'm not seeing network requests fired in my console, any idea why?

Are you looking in the _Network_ tab?

**Comment by sirreal** [comment]
> Are you looking in the Network tab?

Yep, strange 🤔

**Comment by dereksmart** [comment]
Works great! 🚢

**Comment by seear** [comment]
Some ongoing discussion about w

**Comment by seear** [comment]
Still some discussion on whether the `REQUEST`, `SUCCESS`, `FAILURE` pattern is right here. A good case can be made for a simpler `ACTIVATE`, `ACTIVATION_ERROR` pair. It seems that the whole activation/deactivation piece here is temporary until rewind is an always-on feature. Let's go with what we have here for now.

**Comment by sirreal** [comment]
Linking to the discussion referenced: p1496755949461272-slack-calypso-framework

**Pull request merged**
