### PR TITLE
Reader: Fix the double images that appear in gizmodo's feed

### PR DESCRIPTION
**Pull request by blowery**
Ideally we'd do this on ingest, but we cannot right now. Patching this on the client until we can.

### CODE REVIEW

**Comment by blowery** [comment]
before
you_can_thank_twitter_for_trump__according_to_salesforce_ceo_ _gizmodo_ _reader_ _wordpress_com

after
you_can_thank_twitter_for_trump__according_to_salesforce_ceo_ _gizmodo_ _reader_ _wordpress_com

**Comment by blowery** [comment]
Fixes #9371

**Comment by fraying** [comment]
LGTM! Thank you.

**Comment by samouri** [comment]
I think that this breaks posts with only a single image.
e.g. https://wpcalypso.wordpress.com/read/feeds/19797/posts/1224078233

**Pull request merged**
