### PR TITLE
PostNorm: Make images safe before we choose a first pass canonical.

### PR DESCRIPTION
**Pull request by blowery**
This fixes picking a canonical image that cannot be made safe. This was causing permanent loading placeholders for some users.

### CODE REVIEW

**Comment by blowery** [comment]
@rralian this will affect the post lists too...

**Comment by blowery** [comment]
The problem here is that we were picking a canonical image before making the featured_image and featured_media properties safe for consumption. Since we altered photon to return null when it cannot make an image safe (basically it's from a non photon / wpcom host and it contains a querystring), making the images safe _after_ picking a canonical resulted in the canonical's uri sometime turning null. We would later use that null as if it were a string and the interpreter would explode.

This changes the order, making image properties safe before we try to choose a canonical.

**Comment by blowery** [comment]
To test, try http://wordpress.com/read/blog/feed/12098, you should see an error in the console and placeholders forever. Then try http://calypso.localhost:3000/read/blog/feed/12098 with this PR and it should work.

**Comment by mtias** [comment]
This should affect `/posts` and the drafts panel in the post editor, but it makes sense.

**Comment by blowery** [comment]
Hrm, needs more work. We need to limit the size of the canonical. It's pulling full size images now if the feature ends up coming from attachments.

**Comment by blowery** [comment]
OK, all better. Images are now resized, and held to a bigger dimension if a high dpi screen is used.

**Comment by gwwar** [comment]
:shipit: Tested on FF, Chrome, Safari, IE 11, Edge

**Pull request merged**
