### PR TITLE
Posts: comment moderation tools and filters prevent loading comments for all users on Reader

### LINKED ISSUE #12540: Reader: comments aren't showing for readers
Comments aren't showing on Reader posts for readers who don't belong to the site.

It looks like this is a regression from #12295 

#### Steps to reproduce
1. Open this WordPress.com blog post as a non-a8c account (https://wordpress.com/read/feeds/24643651/posts/1390350957)
2. Click the comments icom

#### What I expected

To see comments and be able to add comment

#### What happened instead

Cannot see nor add comments

#### Browser / OS version

Safari/Firefox/Chrome OSX

#### Screenshot / Video

comments

#### Context / Source
#dogfooding

### PR DESCRIPTION
**Pull request by rodrigoi**
This reverts commit 3e30a33926bd653d75396a9a348462ab99da4d34.

Retrieve comments action now defaults status to `approved` so comments show on the reader when the user is not the owner of the blog. Implemented on 25ba5aa9eac3dd71a68798348d5da4fbd003778b.

Fixes #12540.

### CODE REVIEW

**Comment by rodrigoi** [comment]
@alisterscott this PR includes a revert to add the filters and moderation tools again, plus a fix for the bug on commit 25ba5aa9eac3dd71a68798348d5da4fbd003778b.

Thanks for catching this 😄

**Comment by blowery** [comment]
@rodrigoi I'm getting an error when clicking on the filters: `_this.props.onFilterChange is not a function`

**Comment by alisterscott** [comment]
I don't really understand why these buttons are appearing in comments in The Reader, especially on sites where I don't have any relationship to (I simply follow):

screen shot 2017-03-29 at 4 22 58 pm

Are we expecting to see these at all in The Reader? @blowery

**Comment by alisterscott** [comment]
I'm also seeing the same console errors as @blowery above

`TypeError: _this.props.onFilterChange is not a function. (In '_this.props.onFilterChange(commentsFilter)', '_this.props.onFilterChange' is undefined)`

**Comment by alisterscott** [comment]
Clicking "Approve" or "Trash" on a comment in the `posts` list closes the comments section unexpectedly, which results in an interrupted flow if I am trying to manage a few different comments (approve, trash etc.)

approve comment

**Comment by alisterscott** [comment]
@roundhill @drw158 @folletto Would you mind taking a look at this since you were reviewers on the original PR (#12295)?

**Comment by folletto** [comment]
> I think this needs to be separated from Reader comments

I agree with this. The Reader experience should be "clean", no admin there. I understand it might be more efficient to show the controls for your "own" posts, but I'd start with a clean separation.

**Comment by rodrigoi** [comment]
@alisterscott @blowery @raoulwegat @folletto: Sorry if I wasn't clear when explaining the purpose of this PR. The intention is to restore the comment features so work can continue, and fix #12540 (for which only https://github.com/Automattic/wp-calypso/pull/12295 needed to be reverted) or any other errors found in environments other than `development`.
This was also available on `wpcalypso`, but I just removed the feature from that environment to make it extra clear.

All this is very much a work in progress, hidden from users by two feature flags, and the reported problems are either covered by an existent PR (https://github.com/Automattic/wp-calypso/pull/12516) or by future work.
Those two original PRs were merged in order to keep changes as small as possible.

Let me recap the changes made here:
* 25ba5aa9eac3dd71a68798348d5da4fbd003778b: fixes #12540 
* 88ddc728d89d050ab6661c346cd8c4464fefccbf: removes feature flag from 'wpcalypso'
* 232deb148b6e67c6f101fa27e82a94328326c0f9: add extra redundancy on the post comments action creator to prevent any filter other than `approved`. Post Comment state management is been refactored to remove Immutable.js.

cc: @roundhill @drw158

**Comment by folletto** [comment]
I'd rather not have it at first, and enable later if needed, but that's my take. 

I'm totally fine if you prefer enabling it only on posts where the user has actual moderation power, and don't show anything otherwise. 👍

**Comment by blowery** [comment]
> I don't really understand why these buttons are appearing in comments in The Reader, especially on sites where I don't have any relationship to (I simply follow)

Are you proxied?

**Comment by blowery** [comment]
> Moderation controls and filtering will only be available on "your" posts. Does that address the concern?

Folks that are proxied may seem to own more posts than they might expect.

**Comment by fraying** [comment]
Hi! Re: Comment Mod Tools showing up in Reader. My 2c is that, ultimately, they should. But, how, exactly, we need to figure out. 

For example, we currently show an "Edit" link on the Fullpost page (next to Comment and Like) if the user is the owner, which opens the post in the Editor. So the "Approve / Trash / Spam" links below comments would fit in quite well and be of great use to site owners. But I think it'd be important to alter the design of unapproved comments slightly, so the user understands at a glance which comments are public to everyone and which they're only seeing because they're the owner. (Keep in mind that, up until this point, any comment seen in Reader has been a _public_ comment, so that'll be the user's expectation.)

I'm a little more dubious about including the "All / Approved / Pending / Spam / Trash" selector at the top of the comments in Reader. It seems like a lot of interface and that kind of heavy lifting is probably better done elsewhere. At the very least, the selector shouldn't appear if there are zero comments.

Clearly there are a lot of questions about how this new functionality fits in to Reader, and I don't want to slow y'all down. So it might be a good idea to just leave Reader out right now while y'all work out the kinks, and then circle back to Reader afterward. You're the ones doing the work – it's up to you.

**Comment by drw158** [comment]
Sorry for being unclear in this project. Also sorry for not pinging you directly @fraying in order to keep you updated!

Our plan was to:

- only show moderation UI for posts that you control 
- don't show controls if there are no comments
- incorporate a design for unapproved comments (yellow background)

But because of the iterative approach we are taking, I can see how seeing this new incomplete feature  in `wpcalypso` could be startling. Looks like @rodrigoi has removed it from that environment for now 👍

You make a good point here:

> I'm a little more dubious about including the "All / Approved / Pending / Spam / Trash" selector at the top of the comments in Reader.

I think perhaps we could try another design in which only a few selectors are shown here in the segmented control. Maybe just Approved and Pending. Users can then do further filter and moderation in a dedicated interface.

**Comment by fraying** [comment]
No worries at all, @drw158! This is just part of the joy of shared components. :-)

I think leaving Reader out for now is the right call. That'll give you the space you need to work. Please ping us when you're ready and then we can tackle bringing this new functionality into Reader in a way that budgets for local user expectations.

Ever forward!

**Comment by roundhill** [comment]
25ba5aa looks fine, this was the only change @rodrigoi?

**Comment by alisterscott** [comment]
Sorry, I understand the intention now is to simply fix #12540 and other issues with comments in the reader will be addressed in #12516 

I disabled the feature toggle (like it is in production) and all comments look fine in the reader, so LGTM 👍

**Comment by rodrigoi** [comment]
Thanks everybody for the patience, and for catching the bug in the first place 😉 .

**Pull request merged**
