### PR TITLE
Site Settings: Disable After the Deadline when in Dev mode

### PR DESCRIPTION
**Pull request by tyxla**
This PR will disable the "After the Deadline" settings if the current Jetpack site is in development mode. Related with #11386.

Preview when disabled & collapsed:

Preview when disabled & expanded:

To test:

* Checkout this branch
* Select one of your Jetpack sites and enable dev mode by adding this to your wp-config.php: `define( 'JETPACK_DEV_DEBUG', true );`
* Verify the "After the Deadline" settings in the Writing tab are disabled and can't be toggled.
* Disable the Dev mode by deleting the line we just added to wp-config.php.
* Verify the "After the Deadline" settings are now enabled and can be toggled.

/cc @rickybanister @MichaelArestad because I have the feeling that we need do something more in addition to just disabling the fields in that case (as also mentioned here: https://github.com/Automattic/wp-calypso/pull/11386#issuecomment-284359883).

### CODE REVIEW

**Comment by oskosk** [comment]
Works as expected! :shipit:

**Comment by tyxla** [comment]
This one could use a quick design review, @MichaelArestad - we've merged the rest of the dev mode disabling PRs.

**Comment by rickybanister** [comment]
The disabled status seems right. I imagine in another PR we'll want to change over to the collapsible card from the simple link accordion. I'll huddle with @MichaelArestad to get you an illustration of that (there are already some examples in Jetpack)

**Comment by tyxla** [comment]
> I imagine in another PR we'll want to change over to the collapsible card from the simple link accordion. I'll huddle with @MichaelArestad to get you an illustration of that (there are already some examples in Jetpack)

@rickybanister ah, that would be great, thanks! Merging this one then.

**Pull request merged**
