### PR TITLE
Domains: Add error message for recently mapped domains

### PR DESCRIPTION
**Pull request by matthusby**
Needs patch: D2202-code

Test live: https://calypso.live/?branch=add/error-message-for-recently-mapped-domain

### CODE REVIEW

**Comment by mtias** [comment]
Could you add a screenshot of how the error looks in place, please?

**Comment by matthusby** [comment]
screen shot 2016-07-07 at 10 37 36 am

**Comment by klimeryk** [comment]
Thanks for tackling this 👍 
The code looks good (as much as there is ;)), but I wanted to suggest two things:

* Please (Pretty please! WIth 🍒on top!) put a comma at the end of the notice (it's a pet peeve of mine 😅) - it will be consistent with the rest of the notices the user might encounter there.
* More importantly - IMHO, this error message is ambiguous - what does it mean "currently"? The user might start to wonder - when will it be available for mapping? Can he/she do anything to speed that process up? Etc. This could lead to new tickets for support, instead of eliminating them :/ Maybe we have some support docs that we could link to? Or show the number of days this domain will be unavailable for mapping, etc.?

**Comment by matthusby** [comment]
@klimeryk My plan was to leave this as simple as possible to start with, and add support docs etc if users are having questions about it.  My guess is that this case won't come up much.

**Comment by klimeryk** [comment]
Fair enough :)
:shipit: !

**Pull request merged**
