### PR TITLE
Plugins: Reduxify plugins browser

### PR DESCRIPTION
**Pull request by tyxla**
#### Changes proposed in this Pull Request

This PR updates the plugins browser to use Redux instead of the legacy `wporg-data` store. It also fixes a discrepancy in the wporg category list reducer, where items could be duplicated when the same request is performed again and again. It cleans up and fixes tests, and last but not least, **removes the last of the plugins flux stores** 🥳 

This PR is part of #24180 and while it mostly resolves it, I'll keep the issue open because there is a bit more polishing to be done to finalize this task.

#### Testing instructions

* Go to `/plugins` and verify all the WP.org plugins lists work the same way as they do in production. Those include:
  * Categories - New, Popular, Featured
  * Search - clicking on Enhancement, Security, Appearance, etc. or a manual search in the search form
  * Pagination on categories (infinite scroll)
  * Anything else you can think of on these.

#### Note

I've removed some WP.com site plugins functionality because we only display plugins for Jetpack sites and not for WP.com simple sites anymore.

### CODE REVIEW

**Comment by sarayourfriend** [comment]
> I've removed some WP.com site plugins functionality because we only display plugins for Jetpack sites and not for WP.com simple sites anymore.

@tyxla Do we still display plugins for Jetpack sites since Nav Unification? I'm unable to navigate to the calypso plugins via the sidebar anymore (even when I'm definitely in Calypso) 🙁 I just get popped into `wp-admin`

**Comment by tyxla** [comment]
> @tyxla Do we still display plugins for Jetpack sites since Nav Unification? I'm unable to navigate to the calypso plugins via the sidebar anymore (even when I'm definitely in Calypso) 🙁 I just get popped into `wp-admin`

We currently don't but this is a bug with the nav unification project, as [reported here](https://github.com/Automattic/wp-calypso/issues/49120). That is exactly why I specifically suggested going directly to /plugins instead of clicking a nav menu item 😀

Let me know if that makes sense.

**Review by sarayourfriend — APPROVED** [review]
Tested well, LGTM!

**Review by flootr — COMMENTED** [review]
~~Pagination doesn't seem to work for me (compare screencast), I don't see a request in the _Network_ tab either. It's working in prod for those list.~~ Reproducible on prod, too. So not related to your PR.

**Review by flootr — APPROVED** [review]
works well, thank you 👍🏻

**Comment by tyxla** [comment]
> ~Pagination doesn't seem to work for me (compare screencast), I don't see a request in the _Network_ tab either. It's working in prod for those list.~ Reproducible on prod, too. So not related to your PR.

As discussed via Slack, this is reproducible in situations where the window is larger and the infinite scroll gets more difficult to trigger. I'll make sure to dedicate some time and test that thoroughly and see under what circumstances it happens, and how we can improve it.

**Comment by tyxla** [comment]
Thank you both for the reviews 🙌

**Pull request merged**
