### PR TITLE
Add happychat client npm package to mobile chat page

### PR DESCRIPTION
**Pull request by unDemian**
**Built on top of https://github.com/Automattic/wp-calypso/pull/23842**
## Summary
This PR uses the in-development `happychat-client` npm package to replace the happychat entry point used for mobile user at the route `me/chat`

**This will not be merged until we publish the npm package**

## Testing
0. Make sure you use the same npm version for both projects
1. Switch happychat-client branch to `add/layout-option` https://github.com/Automattic/happychat-client/pull/196
2. `npm link` in happychat-client
3. `npm link happychat-client` in calypso
4. Run `npm run dev:npm` in happychat-client and leave it running
5. Start calypso
6. Access `/me/chat` chat should be loaded and it should work properly

### CODE REVIEW

**Comment by kwight** [comment]
For those testing, it looks like `happychat-client` needs Node 6.11.5, while Calypso needs Node 8.11.0 to get everything to start. You don't need the `happychat` repo or Redis running at all.

Following the instructions, I have a chat interface of sorts showing up in `/me/chat`, with some content from previous testing, but I'm not sure what to expect of the interface (mine is all unstyled):

screen shot 2018-04-17 at 12 44 20 pm

**Comment by unDemian** [comment]
Thanks for taking the time.

> Following the instructions, I have a chat interface of sorts showing up in /me/chat, with some content from previous testing, but I'm not sure what to expect of the interface (mine is all unstyled):

The styles are served by the happychat-client development process, in order to have it working you should run `npm run dev:npm` (step 4 in description) in the happychat-client and let it running so the http server that serves the styles is running. I updated the description to include that.

**Comment by unDemian** [comment]
Sorry for the late response, I was afk, the Happychat Client Calypso integration was put on hold as our team has other high priority work scheduled. We will most likely come back to this after the GM. So let's keep the PRs around. Thanks

**Comment by alisterscott** [comment]
Closing due to inactivity. Please reopen if necessary.

**Pull request closed without merging**
