### PR TITLE
Extensions: WPJM - Add pages to Redux state

### PR DESCRIPTION
**Pull request by donnapep**
This PR includes state changes to manage `pages` state. This data is fetched from the WP REST API and is used to populate the dropdowns on the upcoming _Pages_ tab. The state tree is as per the below:

wpjm-state-tree

This PR also standardizes on using _REQUEST_ instead of _FETCH_ actions and updates all affected files.

## Testing

Nothing to really test beyond running unit tests until the UI is in place.

### CODE REVIEW

**Comment by donnapep** [comment]
@ockham Do you think it would make sense to put WP REST API data fetching directly into Calypso's own data layer? It's conceivable, likely even, that someone else (perhaps us) will need to fetch pages in this manner again.

**Comment by ockham** [comment]
> @ockham Do you think it would make sense to put WP REST API data fetching directly into Calypso's own data layer? It's conceivable, likely even, that someone else (perhaps us) will need to fetch pages in this manner again.

Yeah, absolutely. IMO, fetching pages (and storing them in Redux state) is so generic that it shouldn't be handled by WPJM at all. I think we should consider things like that the same way we think of e.g. generic components -- staple dependencies that Calypso provides its extensions with.

> I'm just not sure how that would work, as the state would live outside of the `extensions` subtree. Thoughts?

IIRC, a lot of posts and pages related stuff predates our use of Redux, which is why there is e.g. [`lib/posts`](https://github.com/Automattic/wp-calypso/tree/master/client/lib/posts) which seems to be Flux-based. However, there's pretty good Redux infrastructure that was built for CPTs in `state/posts`, and that seems to be handling posts as well (telling from a quick glance at Redux DevTools in production).

As for pages, they seem to rely on the [`PostListFetcher`](https://github.com/Automattic/wp-calypso/blob/master/client/components/post-list-fetcher/index.jsx) component, which also predates Redux.

So in order to leverage existing infrastructure and minimize duplication, I'd be most inclined to try and see if we can re-use the CPT Redux stuff for pages, and either store pages alongside every other post type in `posts`, or in a new `pages` subtree. Might be worth a quick discussion in the framework channel BTW.

**Comment by ockham** [comment]
For starters, I'd say try using [`<QueryPosts siteId={ 1234567 } query={ { type: 'page' } } />`](https://github.com/Automattic/wp-calypso/tree/master/client/components/data/query-posts) (or `{ type: pages }`, not sure) and see if that puts pages data into the `posts` Redux subtree (`posts.queries[ siteId ].data.items` to be specific).

**Comment by ockham** [comment]
Played a bit with `QueryPosts`, and seems to work fine with pages. Some possibly interesting code in a9bfdc14dc49b28803235a29b6cbd273489c4814 (e.g. selectors).

**Comment by donnapep** [comment]
> For starters, I'd say try using <QueryPosts siteId={ 1234567 } query={ { type: 'page' } } /> (or { type: pages }, not sure) and see if that puts pages data into the posts Redux subtree (posts.queries[ siteId ].data.items to be specific).

Oh, well, that was kind of dumb of me. I'm not sure why I had it in my head that I had to use the WP REST API and not the WP.com REST API.

**Comment by ockham** [comment]
> I'm not sure why I had it in my head that I had to use the WP REST API and not the WP.com REST API.

Probably since we're working with JP/self-hosted sites here :slightly_smiling_face:

**Pull request closed without merging**
