### PR TITLE
Add site title guided tour

### PR DESCRIPTION
**Pull request by markryall**
This PR reintroduces a simplified version of the site title guided tour for use with the checklist.

# Testing

* Create a new site
* Visit the `/checklist/<site>` page
* Click on the 'Do It' button for the site title task
* Verify that the following steps appear in the tour:

site-title-tour

This tour should appear every time you click the task regardless of whether it has been completed

### CODE REVIEW

**Comment by mcsf** [comment]
Per Slack, here are some thoughts on triggering this tour via action dispatching—a mechanism more apt than URL query arguments if a user is already in Calypso.

## A new action type for semantical goodness

If you look at `state/ui/guided-tours/selectors`, you can trace the logic from the bottom selector to figure out how tours are selected. In a gist:

```
eligibleTour = ongoingTour || requestedTour || triggeredTour ( || <nothing> )
```

The semantics here are:
- _eligible_: Whichever tour was singled out to start/continue showing to the user.
- _ongoing_: Any tour that is currently being shown.
- _requested_: Requested with explicit knowledge of what Guided Tours are. Right now, the only request mechanism is query arguments, and this is useful for documentation and support staff who can encode a GT request in a link that they offer the user.
- _triggered_: Determined from the user's interactions throughout Calypso. Examples: accessing a section that is new; frustrated clicks across sections suggesting a user is having trouble looking for the tool they need; not having a site title set yet.

From the semantics, it would seem like the place to fit explicit requests would be in `findRequestedTour`. Let's explore that selector, then. Picking a tour from URL query arguments can take precedence over dispatch-based requests, so we leave that first part untouched. After the last `return`, however:

```diff
 const findRequestedTour = state => {
-	const requestedTour = getTourFromQuery( state );
+	let requestedTour = getTourFromQuery( state );
 	if ( requestedTour && ! hasJustSeenTour( state, requestedTour ) ) {
 		return requestedTour;
 	}
+	requestedTour = ( findLast( getActionLog( state ), { type: GUIDED_TOUR_REQUEST } ) || {} ).tour;
+	if ( requestedTour && ! hasJustSeenTour( state, requestedTour ) ) {
+		return requestedTour;
+	}
 };
```

Obviously, things can be better refactored up here, but this is the gist. You'd need a basic action creator that dispatches the new `GUIDED_TOUR_REQUEST` type:

```js
requestGuidedTour = tour => ( { type: GUIDED_TOUR_REQUEST, tour } )
```

## Next, please

Looking at `state/ui/guided-tours/actions`, we see we have two main action creators, `quitGuidedTour` and `nextGuidedTourStep`. Both hinge on the `GUIDED_TOUR_UPDATE` action type, which is the interest of two reducers, `state/ui/guided-tours/reducer`, but also `state/ui/action-log/reducer`. (The latter is the most interesting for us, as working with an action-queue-based model has proven resilient.)

Could we conceive _starting_ a tour as _moving forward inside a tour from step `null` to step `'init'`_? We can probably get away with it:

```js
requestGuidedTour = tour => ( { type: GUIDED_TOUR_UPDATE, tour, stepName: 'init' } )

// which can be refactored into

export function requestGuidedTour( tour ) {
  return nextGuidedTourStep( { tour, stepName: 'init' } );
}
```

* * *

The latter approach is much simpler to implement, as it reuses all the existing pieces, at the cost of worsened application semantics. I'll leave you to think this over and discuss it with @lsinger, @marekhrabe and I.

**Comment by dzver** [comment]
The PR seems to need some extra CSS work. The Guided Tour is visible on /checklist somewhere at the bottom.

**Comment by fditrapani** [comment]
@markryall I went in and made some style updates so it's looking real good now!

We can leave this for another PR but there's a delay associated with the tours which feels long especially if we're triggering these. Do you know if we could add a different class name [here](https://github.com/Automattic/wp-calypso/blob/master/client/layout/guided-tours/config-elements/step.js#L262) when the task is being triggered?

**Comment by markryall** [comment]
hey @lsinger, @marekhrabe and @mcsf - can you take a look at the current state of this PR?

This is a slightly peculiar use case for guided tours so there are some less than ideal implementation details in this PR.   I'm happy to go with what we have so far and iterate later unless there we can come up with some better ideas to deal with the following:

# triggering tours

I went with @mcsf's second option for triggering the tours - I can see the first option a is a little clearer but didn't think the additional complexity seemed worthwhile.

# ensuring onboarding checklist tours are never triggered automatically

Because we only ever want to programmatically launch the onboarding checklist tours, I've set the path to a route that will never exist so the tour never shows automatically - perhaps using a function that always returns false in the when condition would be less obscure.

# menu items to return to the checklist

No existing tours return to anywhere in particular - when the tour finishes you just end up wherever the tour has taken you.  There is the LinkQuit component but the tour needs to be able to return to a route that is specific to the current site. Hence the SiteLink component.  Clearly these guided tours for the checklist are inextricably tied to the checklist and won't be usuable on their own - perhaps I should just replace SiteLink with a ChecklistQuit component?

# skipping the dealy at the start of the tour

@fditrapani has asked whether we could speed up the appearance of the first step of the tour by skipping the animation.  One option is to skip to a subsequent step instead of init.  Another is to add an option to tours to opt out of the initial animation?

**Comment by lsinger** [comment]
I went through this — great work! 

A few notes:

- I get a warning in the console when running the tour: "Failed prop type: SiteLink: prop type `isButton` is invalid; it must be a function, usually from the `prop-types` package, but received `undefined`."
- the checklist item for personalization isn't shown as completed upon completion of the tour
- I think the second approach mentioned by @mcsf and chosen by your is perfectly reasonable — it's not a mis-use of semantics, it's just a specific and valid interpretation
- to ensure the tour is never triggered automatically it would be great if you could do what you suggest — add a trigger condition to the tour's `when` prop that is never true. you could, for example, name it `neverTriggerAutomatically` (or, ideally, something similarly descriptive but nicer to read) and make it just return false. 
- I like the use of `SiteLink` actually because it's great to use as an example for similar but different future uses not tied to the checklist. I also think that the intent is pretty clear. 
- the slide-in animation for the `init` step is on the CSS class `guided-tours__step-first` — you could add specific CSS to the `init` step removing that, e.g. `animation: none` ([see the docs here](https://github.com/Automattic/wp-calypso/blob/master/client/layout/guided-tours/docs/TUTORIAL.md#custom-styles))

Please do let me know when you need someone to have another look. I'm excited to see the checklist and its associated tours come together!

**Comment by fditrapani** [comment]
Thanks @lsinger. I got the isButton error fixed up. Apparently `PropType.boolean` should be `PropType.bool`. Makes total sense 👎

**Comment by fditrapani** [comment]
Got that animation delay updated too thanks to @lsinger

**Pull request merged**
