### PR TITLE
Checkout: Show inline Stripe form validation errors

### PR DESCRIPTION
**Pull request by sirbrillig**
#### Changes proposed in this Pull Request

In #34469 we added Stripe Elements form fields to the checkout form in some cases. These fields are rendered, controlled, and validated by Stripe or the local Stripe library and so we cannot run our standard validation system on their values. When we currently receive a validation error for one of these fields, it is treated as an unknown processing error and is displayed in the global notices.

This change looks for specific validation errors and displays them inline next to the Stripe form fields instead, matching the behavior of the non-Stripe fields as much as possible.

Note that it will only show an error for one field at a time, because that's what is returned from the Stripe library. So if three fields are invalid, they will all turn red (that's part of the Stripe library) but only one message will be displayed, on the first invalid field.

Before:
global-card-incomplete

After:
inline-card-incomplete

#### Testing instructions

1. Sandbox the store.
2. Visit the checkout form for a product (be sure that you see placeholder _numbers_, not dots, in the credit card field; see screenshot above).
3. Fill in the cardholder name, country, and postal code fields, leaving the card number, expiry, and cvc fields blank.
4. Click the "Pay" button.
5. Verify that you see a validation error immediately beneath the invalid form fields.
6. Repeat steps 3-5 with some fields empty and others filled.
7. Repeat steps 3-5 with some fields containing invalid data and others containing valid data (rather than just being empty).

### CODE REVIEW

**Comment by fditrapani** [comment]
Thanks for putting this together @sirbrillig! From a visual perspective we're super close! Since the error is being rendered inside the label, it was coming out bold. I pushed an update that fixed that. 

This could be left for another PR but another thing I noticed is that when I submit the form, only a couple errors show at a time. Initially it shows 3 errors when you have nothing filled out and then when you fill those fields it shows one at a time. I would expect to see all the errors at the same time so I can fix them all in one go.

**Comment by sirbrillig** [comment]
> Thanks for putting this together @sirbrillig! From a visual perspective we're super close! Since the error is being rendered inside the label, it was coming out bold. I pushed an update that fixed that.

Thanks! We could render it outside of the label if that's helpful. I didn't even think about the placement. But maybe with the font adjustment it's good now?

> This could be left for another PR but another thing I noticed is that when I submit the form, only a couple errors show at a time. Initially it shows 3 errors when you have nothing filled out and then when you fill those fields it shows one at a time. I would expect to see all the errors at the same time so I can fix them all in one go.

Sadly, we don't control which errors we get. The Stripe library seems to only send back one validation error at a time (although it's annoying because clearly it knows the other fields are invalid since it marks them as red).

**Comment by sirbrillig** [comment]
This might be relevant: https://github.com/stripe/react-stripe-elements/issues/283

I'll do a quick look to see if there's another way to get validation errors.

**Comment by fditrapani** [comment]
> Thanks! We could render it outside of the label if that's helpful. I didn't even think about the placement. But maybe with the font adjustment it's good now?

No problem. Yeah, this is good for now. Inspecting the code, I see that we're placing both the field and the error in the label. If possible, we should take the field and error out of the label for more semantic/valid html markup.

**Comment by fditrapani** [comment]
> Sadly, we don't control which errors we get. The Stripe library seems to only send back one validation error at a time (although it's annoying because clearly it knows the other fields are invalid since it marks them as red).

Yeah, it is weird that the fields get marked with a class but the error doesn't come along with it.

**Comment by sirbrillig** [comment]
> Inspecting the code, I see that we're placing both the field and the error in the label. If possible, we should take the field and error out of the label for more semantic/valid html markup.

TIL that [you can nest elements inside a label](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/label) to avoid needing a `for` property:

> Alternatively, you can nest the <input> directly inside the <label>, in which case the for and id attributes are not needed because the association is implicit:

That said, I can't recall why we did that with the labels here (it may have been copied from somewhere else in calypso or in the stripe docs). In fact, our other form fields use a custom component, `FormLabel`, and it's separate from the input fields. I'll see if I can use that here.

**Comment by sirbrillig** [comment]
I figured out how to pick up validation errors directly from the form fields themselves so it's possible to see multiple validation errors at once (and before you click the "Pay" button).

Screen Shot 2019-07-19 at 3 21 35 PM

As for the labels, as discussed in Slack, it's probably a good idea to leave the components inside the labels since the input fields are actually inside iframes. This is the recommendation of the stripe docs.

**Pull request merged**
