### PR TITLE
Reader: Remembered Posts

### PR DESCRIPTION
**Pull request by akirk**
This PR tracks the progress of adding remembered posts to the reader.

Test live: https://calypso.live/?branch=add/remembered-posts

### CODE REVIEW

**Comment by blowery** [comment]
Nice @akirk, excited to see this in Calypso!

Like likes, this is only going to work for posts that have a site_ID and ID and are not external. You might peek at `shouldShowLikes` in `reader/like-helper` for the basic logic.

**Comment by blowery** [comment]
How are you planning on flagging a post as remembered? Fetch all remembered posts and do a set check? Add a new property to post objects coming from /read/* endpoints?

**Comment by lancewillett** [comment]
Hi @akirk Can you update this one when you get a chance? Needs more work still?

**Comment by akirk** [comment]
Yes, it needs more work, which I'll do at the next Hack Day.

**Comment by akirk** [comment]
@blowery thanks for the pointers. I'll probably fetch the whole list and mark them through that.

**Comment by lancewillett** [comment]
Closing for now, no activity in a few months. Feel free to re-open later if work continues on it.

**Pull request closed without merging**
