### PR TITLE
Extensions: Adding WP Job Manager extension base

### PR DESCRIPTION
**Pull request by dbtlr**
This PR adds a placeholder section for WP Job Manager

### CODE REVIEW

**Comment by justinshreve** [comment]
On our PR for WooCommerce, we used `/store` as the URL instead of the slug. That might be something we want to do for this and Sensi as well. The 'wp-' part of the URL looks especially odd as a path running on WordPress.com.

**Comment by dbtlr** [comment]
@justinshreve This was considered, but since this is under the extensions base, we thought it would be good to keep it named as the plugin is named, to avoid further confusion and conflicts.

**Comment by dbtlr** [comment]
@mtias Just like in #11708 I saw you wake a look at #11681 and this one is basically the same. can I get a thumbs up?

**Comment by mtias** [comment]
Looks good, yes. Woo is the odd one out for now in terms of URL allocation.

**Comment by donnapep** [comment]
@dbtlr Would you like me to merge this one?

**Pull request merged**
