### PR TITLE
Reader: remove unused reader/post-images component

### PR DESCRIPTION
**Pull request by bluefuton**
This PR removes the old `reader/post-images` component. It has been superceded by the gallery post card. It is no longer used in the Reader.

### To test

Check a stream http://calypso.localhost:3000/read/blogs/122463145 for good measure.

### CODE REVIEW

**Comment by samouri** [comment]
does `assets/stylesheets/shared/functions/_z-index.scss` still have one more reference at line 124?
`reader-post-images__full-list`

**Comment by blowery** [comment]
one in z-indexes too:

```
assets/stylesheets/shared/functions/_z-index.scss
124:		'.reader-post-images__full-list': 200,
```

**Comment by bluefuton** [comment]
Good spot on the z-index reference, both!

**Comment by samouri** [comment]
tested functionality and all LGTM

**Pull request merged**
