### PR TITLE
Checkout: A/B Test Automatically Displaying Coupon Input

### LINKED ISSUE #31322: UX: Coupon code link visibility
The link to enter a coupon code is difficult to locate because of its size and location. Currently, to enter a code, you must click a link here:

screen shot on 2019-03-08 at 09-37-54

Because it looks like a link and not a spot to put a code, I think it often gets missed.

After the link is clicked, a box appears where the code can be entered:

screen shot on 2019-03-08 at 11-47-11

It may be better to adjust that so that the location to enter the code is active by default, as this is becoming fairly common in sites accepting coupons now. 

#### Context / Source

Came up in 10004251-hc where user described it as `almost invisible and very small`.

### PR DESCRIPTION
**Pull request by Aurorum**
#### Changes proposed in this Pull Request

Currently when a user enters the Checkout, they need to click "_Have a coupon code_?". This is causing issues regarding users missing this and requesting refunds, as mentioned in the original issue. As such, this PR proposes immediately displaying the coupon input.

#### Testing instructions

Switch to the `autodisplay` test

Nothing should really change except from the "Have a coupon code?" link being removed. Coupons should still be accepted and rejected the same way, and the input should still move to the bottom of the screen on mobile.

Screenshot 2019-07-26 at 09 56 23

The only other change is that there is no longer an autofocus set for the input, since the link has been removed.

Also verify that for the other `manualdisplay` test, everything is the same. 

cc @samouri, @adamziel, @dzver 

Fixes #31322

### CODE REVIEW

**Comment by fditrapani** [comment]
This is probably a change we're going to want to A/B test to measure the impact it would have on signup. Do you need help setting up the a/b test for it?

**Comment by Aurorum** [comment]
Thanks @fditrapani! I've never set up an A/B test before so I'm not sure if I've done it correctly, but I've had an attempt. Let me know if I've gone wrong! :)

**Comment by fditrapani** [comment]
The test works great! Thanks for adding it @Aurorum. 

We currently have another test running in our cart that we need to wait for before we can merge this. In the mean time, I'll get some other developers to review this PR from a code perspective.

cc @sirbrillig @prettyboymp can you all take a look at this PR?

**Comment by fditrapani** [comment]
Just wanted to share an update that we're about two-three weeks out from being able to test this. I will keep my eyes on the other tests and merge this one when we're ready.

thanks for your work on this @aurorum

**Comment by fditrapani** [comment]
My apologies for taking so long to come around on this but we're in the process of getting a new checkout ready to test and so we won't be testing this here any longer. Thanks again for contributing @Aurorum!

**Comment by Aurorum** [comment]
No worries, thanks @fditrapani! :)

**Pull request closed without merging**
