### PR TITLE
WPCOM SSH: Copy tweaks

### PR DESCRIPTION
**Pull request by danielbachhuber**
## Proposed Changes

Tweaks to copy associated with `/me/security/ssh-key`:

image

image

image

image

image

## Testing Instructions

1. Navigate to `/me/security/ssh-key`.
2. Verify it's possible to successfully add a SSH key.

### CODE REVIEW

**Review by vykes-mac — APPROVED** [review]
This change seem reasonable and test well as decribed.

**Comment by danielbachhuber** [comment]
@zaguiini Just a FYI on the tweaks I made ^

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/7575080

Thank you @danielbachhuber for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/7575080).

**Pull request merged**
