### PR TITLE
Plan Overhaul revert: Do not offer Starter plan to install premium plugins

### PR DESCRIPTION
**Pull request by mmtr**
#### Proposed Changes

- Stop offering the Starter plan to install premium plugins.
- Sites without the `INSTALL_PURCHASED_PLUGINS` feature (Free, Personal, Premium) will be asked to upgrade to Business before installing premium plugins.
- Sites with the `INSTALL_PURCHASED_PLUGINS` feature (Starter, Pro, Business, eCommerce) will continue to be able to install premium plugins.

#### Testing Instructions

- Use the Calypso live link below
- Switch to site with a Free / Personal / Premium plan
- Go to Plugins
- Select any premium plugin
- Make sure you're asked to upgrade to the Business plan
- Proceed with the purchase
- Make sure your site is transferred to Atomic and the premium plugin has been activated
- Repeat with a site on a Personal or Premium plan
- Switch to site with a Starter / Pro / Business / eCommerce plan
- Go to Plugins
- Select any premium plugin
- Make sure you're NOT asked to upgrade
- Proceed with the purchase
- If your site wasn't Atomic already, make sure it has been transferred to Atomic
- Make sure the premium plugin has been activated

#### Pre-merge Checklist

Complete applicable items on this checklist **before** merging into trunk. Inapplicable items can be left unchecked.

Both the PR author and reviewer are responsible for ensuring the checklist is completed.

- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in [Simple](P9HQHe-k8-p2-p2), [Atomic](P9HQHe-jW-p2-p2), and [self-hosted Jetpack sites](PCYsg-g6b-p2-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Are we memoizing when appropriate (for expensive computations)? More info in [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md) and [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors)
- [ ] Have we sent any new strings [for translation](PCYsg-1vr-p2-p2) ASAP?

Related to

### CODE REVIEW

**Comment by mmtr** [comment]
This effectively reverts https://github.com/Automattic/wp-calypso/pull/64940, so these changes might need to be added back once we roll out premium plugins to the Personal / Premium plans (cc @cpapazoglou )

**Review by gmovr — APPROVED** [review]
Not too familiar with this code, but I did some manual testing - and changes look good to me!


Free site
- Installed WooCommerce shipping tracking
- Asked to upgrade to Business
- Site moved to atomic + plugin installed

Personal site
- Installed WooCommerce shipping tracking
- Asked to upgrade to Business
- Site moved to atomic + plugin installed


Starter
- Installed Sensei Pro
- Not asked to upgrade, but got the notification that it will change to wpstaging (atomic).
- After checkout the plugin is installed and working
- Installed another plugin for good measure afterwards

**Comment by mmtr** [comment]
Not sure if I should ignore the E2E failure. @gmovr do you know if it is expected?

**Comment by gmovr** [comment]
@mmtr Shouldn't be - but I started a re-run of the build now.

**Comment by mmtr** [comment]
It fails consistently on every run while trying to access the My Plan page, but that's totally unrelated to these changes 🤔

**Comment by gmovr** [comment]
Yes, we had it a few times in the base PR/integration branch. It's a timeout - but then re-running the build fixes it. 

It shouldn't be related to anything changed here though AFAIK. So we should we good (it gets merged into the other branch first, and not trunk).

**Pull request merged**
