### PR TITLE
Update texts for LiB and newsletter flows

### PR DESCRIPTION
**Pull request by renancarvalho**
## Proposed Changes

Add correct texts for Lib and Newsletter flows according to the new design.

NewsLetter:

image
image
image
image

Link In Bio:
image
image
image
image

## Testing Instructions

- Checkout this branch
- Run yarn start
- Visit the [newsletter setup](http://calypso.localhost:3000/setup/newsletterSetup?flow=newsletter) and compare the text with the designs for the site icon
- Visit the [link in bio setup](http://calypso.localhost:3000/setup/linkInBioSetup?flow=link-in-bio) and compare the text with the designs for the site icon
- Make sure that the "Replace" text is underlined after a image has been uploaded

### CODE REVIEW

**Review by alshakero — APPROVED** [review]
Brilliant. Let's merge this ASAP to enqueue the translations.

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/7492210

Thank you @renancarvalho for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/7492210

Thank you @renancarvalho for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/7492210).

**Pull request merged**
