### PR TITLE
Signup: Move the user step to the end of flows

### PR DESCRIPTION
**Pull request by taggon**
#### Changes proposed in this Pull Request

* The user steps move back to the end of signup flows.

#### Testing instructions

* Ensure that you're logged out.
* User signup step should the last step when you start from the following entry points.
    * `/start`
    * `/start/business`
    * `/start/premium`
    * `/start/presonal`
    * `/start/free`
    * `/start/blog`
    * `/start/website`

Related #28488, #28487, #28485, #28425

The corresponding [e2e testing updates](https://github.com/Automattic/wp-e2e-tests/pull/1800) should be reviewed too.

### CODE REVIEW

**Comment by ramonjd** [comment]
I went through each route and could create a site, but should there be a way to login? I can only signup for each flow.

screen shot 2019-02-12 at 11 46 39 am

**Comment by southp** [comment]
> I went through each route and could create a site, but should there be a way to login? I can only signup for each flow.

From the code, it looks intentional: https://github.com/Automattic/wp-calypso/blob/master/client/blocks/signup-form/index.jsx#L684 . 

However, since `<SignupForm/>` lives in `/client/blocks/` as a reusable component, I personally don't think it's an ideal way to implement that logic. e.g. I believe that's why `<InviteAcceptLoggedOut/>` has duplicated the same footer component here to override it: https://github.com/Automattic/wp-calypso/blob/master/client/my-sites/invites/invite-accept-logged-out/index.jsx#L107 .

**Comment by southp** [comment]
@taggon The test plan works for me. I also tested the site creation for an existing users through both the main flow and the onboarding flow and the both works. To complete this flow update, let's update the `lastModified` properties and this should good to go.

**Comment by taggon** [comment]
Looks like we no longer need this PR.

**Pull request closed without merging**
