### PR TITLE
Show store link in sidenav by default if user has a business plan

### LINKED ISSUE #33341: Plans: Show Store sidebar item for Business sites if they selected "Online store" segment during signup
As brought up in p58i-7Pk-p2, customers on Business plan have the ability to create a store, but this option is only surfaced after a customer installs a plugin, or a theme. At that point a Store menu item will appear in the nav drawer. Showing the Store menu item immediately after upgrading (and perhaps including it in plan features on `plans/my-plan`, and "thank you" post-purchase pages) would drive more people to use it, and show the unique value of Business plan. 

In the post an idea came up as well, to show the Store item on all plans (similar to how custom CSS option is in the Customizer in all plans), with prompt to upgrade to Business for customers on lower plans.

#### What I expected
For the Store menu item to be immediately available in the nav drawer. What happens after customer clicks still needs figuring out. If we can't step around the requirement to install plugin/theme first, we could at least show a message to that effect. 
I also expected a card on the plan features page/ post-upgrade "thank you" page, that advertises Store feature.

### PR DESCRIPTION
**Pull request by jffng**
#### Changes proposed in this Pull Request

The current approach uses the `canCurrentUserUseStore` reducer to determine whether to show the store link in the sidenav. This PR changes the logic to check whether the user has a business or eCommerce plan instead.  

#### Testing instructions

* Sign up for a business plan
* Verify that the store sidenav link shows up
* Go through the store setup process
* Switch to a non-business / non-ecommerce plan and verify that the store sidenav link is hidden

Fixes #33341

### CODE REVIEW

**Comment by jffng** [comment]
Continuing work on this PR per comments in #33341.

**Comment by jffng** [comment]
Tagging @sixhours for a review.

**Review by sixhours — COMMENTED** [review]
This works a charm for me! Looks like some of the related tests may need to be updated to work with these changes before it can ship.

**Comment by jffng** [comment]
Brought the branch up-to-date cc @lcollette

**Comment by davemart-in** [comment]
I applied this branch locally, then created a new business plan site. After checkout I was redirected here: https://cl.ly/e5017653d7c2 Is this where I should see the Store link?

**Comment by jffng** [comment]
Thanks @davemart-in. The feeling I have reminds me of [the scene in Independence Day](https://vlipsy.com/vlip/independence-day-has-the-target-been-destroyed-negative-target-remains-tPBS9ajz) when they think they can just shoot some missiles at the mothership and they get all excited, only to find out it didn't work and have their hopes dashed. 

Anyhow, I'm trying another bandaid. The problem is that even though the site is technically on the business plan, no plugins have been installed yet and thus it isn't Jetpack enabled. 

My solution is to check for that error state and show users a different error message, with a link to install WooCommerce:

**Pt I:** 
_user tries to set up store_

Screen Shot 2019-07-12 at 11 30 13 AM

**Pt II:** 
_if no plugins are installed / AT hasn't been initiated, user is shown this error message_

Screen Shot 2019-07-12 at 11 30 25 AM

**Pt III:** 
_user is dropped into the woocommerce plugins page_

Screen Shot 2019-07-12 at 11 30 34 AM

There are a few issues with this approach:
- It's technically not true that the user needs to install WooCommerce. It can be any plugin or theme, but IMO this is the most logical message to show the user in this context
- If the user is an admin but not owner, then they can't install a plugin anyways, but they would be able to see the store sidenav link
- It's bad UX, putting the burden on the user to do this work, but I don't know what else to do in the meantime given the technical limitations. 

cc @davipontesblog

**Comment by davemart-in** [comment]
@jffng yep, I like this as a good fall back plan. Ideally we'd be able to figure this out and prevent the user from having to do anything. You and I just chatted via Slack about potentially finding a way to install a simple plugin behind the scenes whenever someone signs up for a business plan, just to kick off everything for the user without them having to do anything. That would be the ideal solution in my mind.

**Comment by jffng** [comment]
Pushed a commit that implements the solution suggested above.

**Review by lcollette — APPROVED** [review]

**Review by donpark — APPROVED** [review]
LGTM

**Comment by jffng** [comment]
@Automattic/team-calypso any idea why the wp-desktop build might be failing? The error seems unrelated to my PR.

**Comment by sixhours** [comment]
@jffng I've run into this one recently, too. It does appear to be unrelated, so you're probably safe to merge without worry, but you can also ask in #e2e-testing-discuss to get eyes on it sooner. :)

**Comment by jffng** [comment]
Ah yes, I see an issue open here: https://github.com/Automattic/wp-desktop/issues/670

Thanks @sixhours!

**Pull request merged**
