### PR TITLE
Themes: Add renderToString() test for theme info page

### LINKED ISSUE #7690: Themes: Add renderToString() tests for theme sheets
Add a test, like this one for the [logged-out layout](https://github.com/Automattic/wp-calypso/blob/master/server/pages/test/index.js#L17), for [theme sheets](https://github.com/Automattic/wp-calypso/blob/master/client/my-sites/theme/main.jsx). This should catch any changes that cause the `renderToString()` call on the theme sheets to break before they hit production.

### PR DESCRIPTION
**Pull request by seear**
Fixes #7690

### CODE REVIEW

**Comment by seear** [comment]
@ockham: ready for review :)

**Comment by ockham** [comment]
On first running this, I got a mocha timeout, advising to use `done()` in the test...

**Comment by ockham** [comment]
Do we want to also check the rendered result? Literally checking the markup is probably to fragile, but I've grown fond of enzyme's `shallow` lately. See [e.g.](https://github.com/Automattic/wp-calypso/pull/8459/files#diff-2b22ac8c507f39b39d77d8ce630ae8e2R24)

**Comment by ockham** [comment]
> I've grown fond of enzyme's `shallow` lately

(especially that you can really just check for presence of child React components, such as [here](https://github.com/Automattic/wp-calypso/pull/8459/files#diff-2b22ac8c507f39b39d77d8ce630ae8e2R101). Seems much easier than with React's own TestUtils before.)

**Comment by seear** [comment]
> On first running this, I got a mocha timeout, advising to use done() in the test...

Seems like `done()` is to let mocha know it needs to wait for some async part to be called, so it knows to fail a test that times out.

Not sure that is appropriate here?

**Comment by ockham** [comment]
Tricky. I'm just worried it will fail on other branches and confuse CircleCI later. FWIW, it happened in the `before all` hook.

**Comment by seear** [comment]
> Tricky. I'm just worried it will fail on other branches and confuse CircleCI later. FWIW, it happened in the before all hook.

I think this is the timeout working as intended? We would need to prevent the thing that is timing out from happening, probably by mocking something I've missed.

**Comment by seear** [comment]
Ah, I think it is the compilation of `client/my-sites/theme/main.jsx` that is taking the time. Not much we can do about this. Perhaps a longer timeout.

**Comment by seear** [comment]
> Do we want to also check the rendered result? Literally checking the markup is probably to fragile, but I've grown fond of enzyme's shallow lately. See e.g.

Gone for very simple checks for css classes in the markup. These should change very rarely.

**Comment by ockham** [comment]
:shipit:

**Pull request merged**
