### PR TITLE
Plans: Update customer-type-toggle styling

### PR DESCRIPTION
**Pull request by shaunandrews**
This PR removes the custom styling of the segment control uses to toggle between plan types. The current "button-like, but not-button-like" styling doesn't fit with out current patterns and is hard to use in signup.

Before Signup:
image

Before Signed In:
image

After Signup:
image

After Signed In:
image

### CODE REVIEW

**Comment by shaunandrews** [comment]
> My comment is that it's not clear to me which tab is selected vs not

Agreed. The segmented controller doesn't work well with less than 3 options. I'll try a few things to help make it more obvious.

**Comment by shaunandrews** [comment]
Updated the PR description with a new screenshot. Here's a take that adds a pointer arrow to the selected item, an underline to the unselected item, and a box-shadow to the container element.

image

**Comment by shaunandrews** [comment]
Just pushed some tweaks for smaller breakpoints. I don't love it — its not obvious at all which one is selected.

image

**Comment by ramonjd** [comment]
> I don't love it — its not obvious at all which one is selected.

Could add some visual indicator, like an arrow maybe?

Screen Shot 2019-03-28 at 12 21 31 pm

**Pull request merged**
