### PR TITLE
Site Settings: Specify Jetpack Connection Owner

### LINKED ISSUE #25812: Site Settings: Change message wording to specify usernames
Change the "Somebody else owns this site's connection..." and "Somebody else is the plan purchaser.." message wording on /settings/manage-connection/SITEURL to specify the Site Owner and Plan Purchaser **usernames** to help clarify roles and points of contact.

**Before**
screen shot 2018-06-28 at 1 30 56 pm

**After** 
screen shot 2018-06-28 at 1 35 56 pm

See: p6TEKc-29d-p2 #comment-5042 and p1HpG7-5iF-p2 #comment-26656

### PR DESCRIPTION
**Pull request by Aurorum**
Requires Automattic/jetpack#16327

#### Changes proposed in this Pull Request

This changes the wording of "Someone else" to a specific username in Site Settings. Although I have no strong views on the language of `master` either, as this PR involves touching those selectors, I've updated them as part of #43303 too.  

#### Testing instructions

Apply the changes on the Jetpack side and visit `/settings/manage-connection/site` from an account which doesn't own the connection.

**Before:**

Screenshot 2020-06-30 at 10 49 51

**After:**

_When not as owner:_

Screenshot 2020-06-30 at 10 36 55

_When as owner (no changes):_
Screenshot 2020-06-30 at 10 37 00

cc @joanrho, @ockham 

Fixes #25812

### CODE REVIEW

**Comment by saramarcondes** [comment]
@Aurorum Thanks for this PR. Is there anything I can do to help get the tests passing so we can merge it?

**Comment by Aurorum** [comment]
Thanks @saramarcondes! I spent a while looking at the tests a while back and I was baffled on why they were failing. I can take another look soon, but if you have any ideas on what's breaking them, I'd be grateful if you could let me know! :)

**Comment by saramarcondes** [comment]
@Aurorum This was a tricky one but I figured it out!

Changing the test to the following works:

```js
test( 'should dispatch success and receive actions when request successfully completes', async () => {
	await requestJetpackUserConnectionData( siteId )( spy );

	expect( spy ).to.have.been.calledWith( {
		type: JETPACK_USER_CONNECTION_DATA_RECEIVE,
		siteId,
		data: {
			currentUser: data,
		},
	} );

	expect( spy ).to.have.been.calledWith( {
		type: JETPACK_USER_CONNECTION_DATA_REQUEST_SUCCESS,
		siteId,
	} );
} );
```

The actual change here is for the `*_RECEIVE` action assertion, because you changed the response to no longer extract out `currentUser` and to just always return the full data object, it wasn't matching up because it was comparing `data` to `{ currentUser: data }`.

I figured this out by converting just that test to a `jest` test which gave a much clearer failure:

```
  ● actions › #requestJetpackUserConnectionData() › success › should dispatch success and receive actions when request successfully completes

    expect(jest.fn()).toHaveBeenCalledWith(...expected)

    Expected: {"data": {"gravatar": "<img />", "isConnected": true, "isMaster": true, "permissions": {"edit_posts": true}, "username": "automattic", "wpcomUser": {"ID": 12345678, "login": "automattic"}}, "siteId": 12345678, "type": "JETPACK_USER_CONNECTION_DATA_RECEIVE"}
    Received
           1
              Object {
            -   "data": Object {
            -     "gravatar": "<img />",
            -     "isConnected": true,
            -     "isMaster": true,
            -     "permissions": Object {
            -       "edit_posts": true,
            -     },
            -     "username": "automattic",
            -     "wpcomUser": Object {
            -       "ID": 12345678,
            -       "login": "automattic",
            -     },
            -   },
                "siteId": 12345678,
            -   "type": "JETPACK_USER_CONNECTION_DATA_RECEIVE",
            +   "type": "JETPACK_USER_CONNECTION_DATA_REQUEST",
              },
           2
              Object {
                "data": Object {
            +     "currentUser": Object {
                    "gravatar": "<img />",
                    "isConnected": true,
                    "isMaster": true,
                    "permissions": Object {
                      "edit_posts": true,
                    },
                    "username": "automattic",
                    "wpcomUser": Object {
                      "ID": 12345678,
                      "login": "automattic",
            +       },
                  },
                },
                "siteId": 12345678,
                "type": "JETPACK_USER_CONNECTION_DATA_RECEIVE",
              },
           3
              Object {
            -   "data": Object {
            -     "gravatar": "<img />",
            -     "isConnected": true,
            -     "isMaster": true,
            -     "permissions": Object {
            -       "edit_posts": true,
            -     },
            -     "username": "automattic",
            -     "wpcomUser": Object {
            -       "ID": 12345678,
            -       "login": "automattic",
            -     },
            -   },
                "siteId": 12345678,
            -   "type": "JETPACK_USER_CONNECTION_DATA_RECEIVE",
            +   "type": "JETPACK_USER_CONNECTION_DATA_REQUEST_SUCCESS",
              },

    Number of calls: 3

      148 |                             await requestJetpackUserConnectionData( siteId )( dispatch );
      149 | 
    > 150 |                             expect( dispatch ).toHaveBeenCalledWith( {
          |                                                ^
      151 |                                     type: JETPACK_USER_CONNECTION_DATA_RECEIVE,
      152 |                                     siteId,
      153 |                                     data,

      at _callee$ (state/jetpack/connection/test/actions.js:150:24)
      at tryCatch (../node_modules/regenerator-runtime/runtime.js:45:40)
      at Generator.invoke [as _invoke] (../node_modules/regenerator-runtime/runtime.js:274:22)
      at Generator.prototype.<computed> [as next] (../node_modules/regenerator-runtime/runtime.js:97:21)
      at asyncGeneratorStep (../node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
      at _next (../node_modules/@babel/runtime/helpers/asyncToGenerator.js:25:9)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 8 skipped, 9 total
```

Which is easier to see with the colors from the diff where the problem is:

Colored diff of above test failure

Unfortunately the sinon adapter for chai just fell short here 😞 Hopefully this makes sense!

**Comment by Aurorum** [comment]
Thanks so much @saramarcondes - that fixes it! This should be ready for review now. :)

**Comment by saramarcondes** [comment]
Great! Unless someone gets to this before me I'll merge this on Tuesday!

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/4186914

Thank you @Aurorum for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/4186914).

**Pull request merged**
