### PR TITLE
Only omit year from post date when published within a year

### LINKED ISSUE #42196: Posts list: date doesn't show year even when relevant
#### Steps to reproduce

1. Starting at URL: https://wordpress.com/posts/my (on a site with posts dating back several years)
2. Look at the date shown for older posts.

#### What I expected

For posts earlier than 2020, I expected to see a date like "May 4, 2019, at 7:29 PM"

#### What happened instead

No year is listed, so I see "May 4, at 7:29 PM" - making it look like a recent post.

#### Context / Source

I realise I can hover over the date for a tooltip, but that's a #paintpoint when scanning the list looking for a particular year.

Abbreviating the date to a more friendly format is totally fine for recent posts, but I'd expect to see the year shown for anything in a prior calendar year (and perhaps also anything more than about 6 months old).

### PR DESCRIPTION
**Pull request by stacimc**
#### Changes proposed in this Pull Request

On the Posts page, we previously were only displaying the year in a post's displayed timestamp if the post was scheduled to be published more than a year in the future.

This PR changes this so that the year will always display unless the post's (or page's) publish date is within today's calendar year. This includes published posts and posts that are scheduled to be published. Concretely this results in two changes from what's happening today:

* Posts or pages scheduled to be published within 365 days of today, but not in this calendar year, will now include the year in the display date
  * _Example, today is 05-10-20, a post scheduled for 01-10-21 will display the year_
* Posts or pages that were published earlier than this calendar year will display the year
  * _Example, today is 05-10-20, a post published 25-12-19 will display the year_

**This changes the timestamp display text in the following places:**
- on the Posts page, both when `showPublishedStatus` is true and when it is not.
- on the Pages page

#### Testing instructions

_Posts_
Starting at URL: https://wordpress.com/posts/my
- [ ] A post published earlier this year: the year **SHOULD NOT** be displayed
- [ ] A post published the previous year: the year **SHOULD** be displayed
- [ ] A post scheduled to be published later this year: the year **SHOULD NOT** be displayed
- [ ] A post scheduled to be published next year: the year **SHOULD** be displayed

_Pages_
Starting at URL: https://wordpress.com/pages/my
- [ ] A page published earlier this year: the year **SHOULD NOT** be displayed
- [ ] A page published the previous year: the year **SHOULD** be displayed
- [ ] A page scheduled to be published later this year: the year **SHOULD NOT** be displayed
- [ ] A page scheduled to be published next year: the year **SHOULD** be displayed

_In the screenshot below, the first post was published Sep 22, 2020, so the year does not display_
Screen Shot 2020-10-05 at 1 55 36 PM

_In the screenshot below, the first post is scheduled for October 22, 2020, so the year does not display_
Screen Shot 2020-10-05 at 5 17 25 PM

Fixes #42196

### CODE REVIEW

**Comment by glendaviesnz** [comment]
This works for posts/pages 1 year +/- from current date, but I wonder if it is less confusing to go with the approach mentioned in the issue and show the year if the published date is outside the current calendar year? otherwise a post from Nov last year doesn't have year, but one from June does:

Screen Shot 2020-10-06 at 11 52 37 AM

**Comment by stacimc** [comment]
> This works for posts/pages 1 year +/- from current date, but I wonder if it is less confusing to go with the approach mentioned in the issue and show the year if the published date is outside the current calendar year? otherwise a post from Nov last year doesn't have year, but one from June does

@glendaviesnz I agree that scenario is a bit confusing. I think the current situation with posts scheduled one year in the future, but outside of the current calendar year, is also a bit confusing (although maybe a little less so). Ie:

Right now if today is October 5th 2020 and you schedule posts for October 10 2020 and for October 4th 2021, the year will not be displayed for either.

I'd prefer removing the year only when it's in the same calendar year, past or future.

**Comment by glendaviesnz** [comment]
> I'd prefer removing the year only when it's in the same calendar year, past or future. Thoughts?

I agree that the least confusing option is to only remove the year if the date is within the same calendar year, with both past and future dates

**Review by glendaviesnz — APPROVED** [review]
This tested correctly for me with Post and Page listing pages past and scheduled.

**Pull request merged**
