### PR TITLE
Update dependencies for React 16 compat

### PR DESCRIPTION
**Pull request by samouri**
update deps for [react 16](https://github.com/Automattic/wp-calypso/pull/19083):
1. qrcode.react
3. react-day-picker

To Test
----
- [x] date-picker: test scheduling a post. anything else?
- [x] qrcode.react: disable/enable 2fa. esp. on mobile using qr codes

### CODE REVIEW

**Comment by samouri** [comment]
> react-element-to-jsx-string

this appears like its actually a dep of a dep. removing from this pr.

**Comment by samouri** [comment]
@akirk or @ebinnion: any chance one of you two could test qr code functionality in this branch?

**Comment by samouri** [comment]
@retrofox: do you know of any special testing instructions I should consider for `react-day-picker`?

**Comment by retrofox** [comment]
> @retrofox: do you know of any special testing instructions I should consider for react-day-picker?

I would only test the complete functioning of the calendar and some components that depend on this.

* http://calypso.localhost:3000/devdocs/design/date-picker
* http://calypso.localhost:3000/devdocs/blocks/post-schedule

I could take a look as well.

**Comment by samouri** [comment]
> I could take a look as well.


That would be great! Thank you ⭐️

**Comment by retrofox** [comment]
I've tested the functionality and everything seems ok. I've created a new post and confirmed the post date. 👍 LGTM.

**Comment by samouri** [comment]
Thanks @retrofox for testing out the date-picker functionality! Now just need to finish testing qrcode behavior and then this should be good to go

**Comment by ebinnion** [comment]
I tested the 2fa via app flow and it worked as expected. 👍

**Comment by ockham** [comment]
@ebinnion Just to confirm -- so the QR code stuff is still in use? Asking because I was't sure if maybe it was on an unreachable code branch. (If it is, I'd love to axe the dependency so we don't have to do the same dance once React 17 is out.)

**Comment by retrofox** [comment]
> so the QR code stuff is still in use?

Just FYI recently I had to do the 2 step verification process and I realized me that we aren't showing the QR code for this. :-(

**Comment by ebinnion** [comment]
Yes. It's used for 2fa when you set it up via the app.

**Comment by retrofox** [comment]
oh, do you know why it isn't used in the web app?

**Comment by ebinnion** [comment]
It is:

image 2017-10-31 12-08-16

**Pull request merged**
