### PR TITLE
PostTypeList: Enlarge and wrap post titles

### PR DESCRIPTION
**Pull request by nylen**
This PR allows post titles using `PostTypeList` to vary in height and increases their font size.

The initial logic to vary heights by post item was introduced in #17196.  This PR will add another case where post item heights can vary.

At the moment this is not working perfectly:  some multi-line titles that are not _very much_ longer than one line are not correctly measured, even after `requestAnimationFrame`, and the way the variable-height logic is implemented means that post items will change in height after an initial render at the default height.  To get around these issues we may ultimately have to remove `ReactVirtualized` as discussed for example [here](https://github.com/Automattic/wp-calypso/pull/17196#issuecomment-324141510).

### Screenshot

2017-08-25t17 11 04-0500

### To test

- Run Calypso with `ENABLE_FEATURES=posts/post-type-list npm start`
- View the list of posts at `/posts` or `/posts/:site`
- Verify that post titles appear using a larger font size and long titles are wrapped across multiple lines on `/posts`, `/pages`, and `/types/:cpt/:site` (e.g. `jetpack-testimonial`).
- Verify that titles re-wrap and post items resize appropriately with changing window size
- Verify that other uses of `PostTypeList` (drafts lists to the right side of `/posts` with and without the `posts/post-type-list` feature flag) are unaffected by this PR.

### CODE REVIEW

**Comment by nylen** [comment]
This seems to be working well in Chrome, but it doesn't always update in Firefox.

Still, I'd like to go ahead and request review now:  Am I missing any obvious improvements that could make this work better?  Does it generally test well for others?

I wanted to add a window `resize` listener at the `PostTypeList` level rather than the `PostItem` level, because if there is one listener per `PostItem` then that is a lot of callbacks, all with separate `throttle` timeouts, and these listeners will be added and removed as `ReactVirtualized` mounts and unmounts items due to page scrolling.

All of this requires a way to update each `PostItem` when the window resize callback is triggered.  I tried a couple of other methods of storing references to active `PostItem` elements so that I could call the `handleHeightChange` method, but I couldn't get it working because what we render as a `PostItem` is actually [wrapped by both `connect` and `localize`](https://github.com/Automattic/wp-calypso/blob/64cb6a562e2336df03deedc3426a8fbdf546233d/client/blocks/post-item/index.jsx#L217-L235).  This solution felt fragile and very un-React-like, so I decided to add a `windowWidth` state value / property that forces a re-render of each `PostItem` when the window is resized.

**Comment by mjuhasz** [comment]
I've been testing this in Safari and Chrome for a while, and it works as it should.

> Verify that post titles appear using a larger font size and long titles are wrapped across multiple lines on /posts, /pages, and /types/:cpt/:site (e.g. jetpack-testimonial).

Page list looks the same as before (hierarchical, homepage and blog page marked when necessary, title font 15px vs. 20px for large titles for posts/custom post types) - that's correct behavior since we do not want to change the (hierarchical) page list representation, right?

The code is as good as gets I guess with the restrictions we have. It feels complicated and things like `setTimeout` make me worried but rather than nitpicking in this PR I'd be curious whether/how removing React Virtualized would simplify it. Given that the PR works as it should, it is behind a feature flag, and experimenting with a different architecture is in our short-term plans, I'm fine with the PR 👍

**Comment by nylen** [comment]
I agree, let's merge this and continue to explore options in separate PRs.  Thanks for the review!

**Comment by nylen** [comment]
> Page list looks the same as before

Correct, this is a [different set of components](https://github.com/Automattic/wp-calypso/blob/d624916eeca373fe6f47a1ea84a5eb1c637b4185/client/my-sites/pages/page-list.jsx#L268-L273).

This PR should not change existing uses of `PostTypeList` / `PostItem` either, unless the new `wrapTitles` / `largeTitles` properties are used.

**Pull request merged**
