### PR TITLE
A4A: Update Pressable logos.

### PR DESCRIPTION
**Pull request by jkguidaven**
Pressable has launched its new logo, and this PR updates any Pressable logo reference in A4A to use the new one.

Closes https://github.com/Automattic/automattic-for-agencies-dev/issues/844

## Proposed Changes

* Replace the Pressable logo images to use the new one. Fix a couple of broken UI after replacing the newer and bigger images.

## Why are these changes being made?

* We need to match the Pressable logo to have consistent branding.

## Testing Instructions

* Use the A4A live link below and test all A4A pages that have the Pressable logo on them and confirm it isn't broken.

| Area | Before | After |
|--------|--------|--------|
| `/overview` | Screenshot 2024-07-25 at 12 07 42 AM | Screenshot 2024-07-25 at 12 07 49 AM |
| `/marketplace/hosting?flags=-a4a-hosting-page-redesign` | Screenshot 2024-07-25 at 12 10 38 AM | Screenshot 2024-07-25 at 12 10 05 AM |
| `/sites/overview/{PRESSABLE_SITE}/hosting-overview` | Screenshot 2024-07-25 at 12 17 47 AM | Screenshot 2024-07-25 at 12 20 53 AM | 
| `/marketplace/hosting/pressable` | Screenshot 2024-07-25 at 12 11 39 AM | Screenshot 2024-07-25 at 12 11 45 AM | 
| `/migrations` | Screenshot 2024-07-25 at 12 13 16 AM | Screenshot 2024-07-25 at 12 13 03 AM | 
| `/partner-directory/dashboard` | Screenshot 2024-07-25 at 12 16 20 AM | Screenshot 2024-07-25 at 12 15 05 AM | 
| `/referrals/faq` | Screenshot 2024-07-25 at 12 20 07 AM | Screenshot 2024-07-25 at 12 19 52 AM | 
| `/referrals/dashboard` | Screenshot 2024-07-25 at 12 23 16 AM | Screenshot 2024-07-25 at 12 22 27 AM | 

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Review by jeffgolenski — APPROVED** [review]
You went above and beyond James, thank you. Feel free to ship

**Review by yashwin — COMMENTED** [review]
Overall, it looks great.

I found some issues on the Migrations screen on smaller screens, the icons are hardly visible:

Screenshot 2024-07-25 at 3 53 33 PM
Screenshot 2024-07-25 at 3 53 51 PM

**Comment by jkguidaven** [comment]
@yashwin, I could not reproduce the issue. Where did you test the PR? I tried both Horizon and Dev, but I don't see that small logo 🤔

**Comment by jkguidaven** [comment]
> Overall, it looks great.
> 
> I found some issues on the Migrations screen on smaller screens, the icons are hardly visible:
> 
> Screenshot 2024-07-25 at 3 53 33 PM Screenshot 2024-07-25 at 3 53 51 PM

Thanks for the review and catching the bug. I made changes to fix the bug. Can you have another look?

**Review by yashwin — APPROVED** [review]
LGTM!

Thanks for fixing the issue!

**Pull request merged**
