### PR TITLE
Stats: Apply extended quantity to the last tier

### PR DESCRIPTION
**Pull request by grzegorz-cp**
Related to #85109

## Proposed Changes

* Restore the slider view for a single tier by hiding the slider and only showing the price and quantity labels
* Fix the default slider quantity when not interacting with the slider (previously, lack of interaction could result in the quantity set to 0)
* Applying double quantity for the last tier instead of `null` when redirecting to checkout

## Testing Instructions

* create a testing blog and navigate to a live branch with `stats/tier-upgrade-slider` feature flag
* purchase final commercial tier
* navigate to the purchase page again
* verify that the slider is not visible, but the labels with the price and quantity are visible
* purchase the final tier
* quantity is set to `2 000 000` and you might see it in the URL, but I'm investigating why it doesn't apply the proper limit after purchase 

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

**Review by dognose24 — COMMENTED** [review]
Do I need to apply D129634-code for testing? I applied D129634-code and purchased the last tier, `2M+`. I can still see the pricing slider when visiting the commercial purchase again.

#### It means I am on the highest tier already
截圖 2023-12-19 下午1 10 43

#### The pricing slider still shows as previously
截圖 2023-12-19 下午1 17 24

**Comment by grzegorz-cp** [comment]
@dognose24, yes, you need D129634. Can you test on a clean JN?

**Comment by dognose24** [comment]
> Can you test on a clean JN?

Yes, I tested again with a new JN site. I followed steps 1 to 3, and the tier slider still shows. I purchased the last tier again, and the checkout page shows I already got the highest quantity, as https://github.com/Automattic/wp-calypso/pull/85444#pullrequestreview-1788116347. 🤔

截圖 2023-12-20 下午11 12 31

**Review by dognose24 — APPROVED** [review]
This PR makes the highest tier (`2M+`) purchasable, which is the primary concern of https://github.com/Automattic/wp-calypso/issues/85109.

> Restore the slider view for a single tier by hiding the slider and only showing the price and quantity labels

We can follow up on hiding the tier slider when users already get the highest one.

**Pull request merged**
