### PR TITLE
Editor: Improve toolbar pinning by removing hard-coded thresholds

### LINKED ISSUE #337: Editor: TinyMCE pinned toolbar improvements
There are some potential improvements to be made regarding the inner workings of how the tinyMCE toolbar transitions from being static to becoming pinned at the top of the page.

* [ ] Move pinned func. to a TinyMCE plugin
* [ ] Throttle `window.onscroll`
* [ ] Parameterize/calculate the top offsets (46 = master bar height, 139 = master bar height + toolbar height)

raised by aduth adambbecker

### LINKED ISSUE #4792: Editor: Toolbar pinning issues when featured image is present
1. Open the editor
2. Create or edit a post with a featured image
3. Scroll up and down and observe the following issues with the toolbar:
    - Visual and HTML tabs overlap the toolbar when it is pinned
    - Toolbar does not un-pin when it should

featured-image-toolbar-pinning

### PR DESCRIPTION
**Pull request by aduth**
Fixes #337
Fixes #4792

This pull request seeks to improve the behavior of editor toolbar pinning by removing reliance on hard-coded offset thresholds. Further, it removes a complex pinning flow for applying an unnecessary modifier class to the editor header, and may improve performance by throttling the bound scroll event. Finally, the pinning logic has been extracted from the `<TinyMCE />` component and implemented as a standalone plugin.

Notably, this resolves an issue where the pinning behavior of the toolbar would not behave as expected when a featured image was assigned to the post.

Before|After
---|---
before|after

__Testing instructions:__

Verify that toolbar is pinned as expected whilst you scroll the editor page. Toolbar pinning is only available for larger viewports, and mobile usage should remain unaffected.

1. Navigate to the [post editor](http://calypso.localhost:3000/post)
2. Select a site, if prompted
3. Enter enough content (e.g. [Lorem ipsum](http://lipsum.com/feed)) or shrink the vertical height of your browser for scroll to appear
4. Note that when the master bar reaches the top edge of the editor, the toolbar becomes pinned (or unpinned while scrolling upwards)

Try a variety of more complex cases:
- Viewport resizing
- Toggling between HTML and Visual modes
- Featured image assigned

### CODE REVIEW

**Comment by mtias** [comment]
Finally!

**Comment by nylen** [comment]
We need to remove the `is-pinned` class if the toolbar is pinned and we change to a small viewport.  Otherwise we end up with something like this:

image

Similarly, we may need to remove the `is-pinned` class when changing back to a larger viewport:

image

Steps to reproduce the 2nd bug:

- Pin the toolbar
- Resize the window to a viewport small enough that pinning is disabled
- Scroll up to the top of the page
- Resize the window back to a large viewport where pinning is possible again.

**Comment by nylen** [comment]
I was also able to trigger toolbar pinning on a small viewport:

image

I think this is because of the interaction of `throttle` and the `resize` event - the following sequence of events would leave the pinning enabled:

- Window is resized from e.g. 800px to 700px; `maybeBindScroll` is called
- Window is resized from e.g. 700px to 600px; `maybeBindScroll` is not called due to `throttle`

**Comment by nylen** [comment]
Fixed the above issues in 0df287b.  Maybe there is a better way of doing it?

**Comment by nylen** [comment]
I had thought that `throttledFunction.flush()` would always invoke the function.  However, from reading through the lodash code, [this is not the case](https://github.com/lodash/lodash/blob/4.5.0/lodash.js#L8723-L8729).  Updated accordingly in c0da2c2.

**Comment by aduth** [comment]
Good catch @nylen . In looking it over, I think the only change we needed to make from the original code was to unpin the toolbar (reset to default) when unbinding the scroll handler. I'm not sure we need to do anything around invoking the unthrottled function on resize, since `_.throttle` [calls on the trailing end of the delay by default](https://lodash.com/docs#throttle). That said, it wasn't entirely clear to me the steps to recreate the issue, so please give it another go and let me know if it's covered by the updates in c125829.

One case not captured here is "re-pinning" the toolbar if necessary when resizing from small to large viewport, at least until the next scroll. This feels very edge-y, though we may be able to account for it by calling `pinToolbarOnScroll` in the truthy condition after scroll is bound.

I may be hyper-sensitive about performance in thinking that we should be avoiding `isWithinBreakpoint` from the scroll handler or unthrottled resize event 😆  Looking at its implementation, [I suspect it's not very slow](https://github.com/Automattic/wp-calypso/blob/2c85df9b4188f699b6a45b69dee6b65184bf46f8/client/lib/viewport/index.js#L32-L53), but could do for some optimizations (e.g. not creating an object of functions every time its invoked).

**Comment by nylen** [comment]
Okay, this looks pretty good, thanks for cleaning up my terrible code 😩 

> One case not captured here is "re-pinning" the toolbar if necessary when resizing from small to large viewport, at least until the next scroll.

I think it would be good to go ahead and get this case right while we are looking at it here.

> 1. unpin the toolbar (reset to default) when unbinding the scroll handler
> 2. calling `pinToolbarOnScroll` in the truthy condition after scroll is bound

Since we're already doing (1) I think it makes sense to do (2) as well.

> I may be hyper-sensitive about performance in thinking that we should be avoiding `isWithinBreakpoint` from the scroll handler or unthrottled resize event

I'd agree with that :) Throttling the scroll handler makes sense, but during resize, the vast majority of computation is going to be due to repainting - I bet creating an object and checking `window.innerWidth` is almost entirely negligible in comparison.

**Comment by aduth** [comment]
>thanks for cleaning up my terrible code

Not terrible by any means. Would likely be the right choice had `throttle` not triggered on the tail-end of the delay.

>I think it would be good to go ahead and get this case right while we are looking at it here.

Yeah, as I was writing my comment I had a feeling I should have gone ahead with the reverse case, especially since it's a one-liner. The rebased 421c802 now triggers a pinning update when the event is both bound and unbound.

As noted in the comment, I had discovered an alternate solution could be to simply change the styling effects of `is-pinned` to be within a media query, so we wouldn't need to add or remove the class. But the advantage of keeping it this way is we don't need to worry about keeping the breakpoint in sync if we decide to change it in the future (in plugin script only vs. in script and in stylesheet).

Lastly, I did some final testing across all browsers and discovered that `window.scrollY` is not supported in IE11. In 4a17ec6 I changed it to use `window.pageYOffset` instead, which is an [alias for `window.scrollY` and better supported](https://developer.mozilla.org/en-US/docs/Web/API/Window/scrollY#Notes).

**Pull request merged**
