### PR TITLE
Implement Unlimited Premium Themes in Premium Plan.

### PR DESCRIPTION
**Pull request by mendezcode**
This PR removes Premium Squared code, including A/B Tests and unit tests, and introduces the functionality to make available the Unlimited Premium Themes upgrade into the Premium Plan.

### CODE REVIEW

**Comment by seear** [comment]
@mendezcode just a thought, we are doing two things here: 1) removing premium squared, and 2) adding unlimited premium themes. Do these two things need to happen at the same time, or could we split into two PRs to make testing and reviewing easier?

**Comment by seear** [comment]
Should we be removing the `abtest` arg from the plan calls now it is no longer required?
[Here](https://github.com/Automattic/wp-calypso/blob/83a6b84a15d651e4740b0bb57d2ba5d14dff67be/client/my-sites/plan-features/index.jsx#L467), [here](https://github.com/Automattic/wp-calypso/blob/83a6b84a15d651e4740b0bb57d2ba5d14dff67be/client/lib/plans/index.js#L180), and [here](https://github.com/Automattic/wp-calypso/blob/83a6b84a15d651e4740b0bb57d2ba5d14dff67be/client/lib/plans/index.js#L182).

**Comment by mendezcode** [comment]
> Do these two things need to happen at the same time, or could we split into two PRs to make testing and reviewing easier?

@seear They need to be removed together, because we can't have both Premium Squared and Unlimited Premium Themes at the same time. The former includes a subset of the premium themes (WooThemes + Automattic), and the latter includes all premium themes.

> Should we be removing the abtest arg from the plan calls now it is no longer required?

I have not touched the code in the locations you mention. I don't think this code seems related to Premium Squared though.

**Comment by seear** [comment]
> I would recommend to keep the abtest arg for the future though, in any case we need to A/B test something inside the Plans Features list.

Yep, that's fine.

**Pull request merged**
