### PR TITLE
Add "Launch site" button to site preview screen

### PR DESCRIPTION
**Pull request by pkuliga**
Related to p1724614480485499-slack-C029GN3KD

### The problem

I found it too complicated to actually launch a site after creating a Dotcom account and skip the onboarding flow by going straight to the Dashboard. You need to click the Home icon to see the site preview, then click the "Visit site" button, and finally "Launch site". This PR allows the user to launch the site from the preview screen, which makes it a bit easier to find.

#### Before

Screenshot 2024-08-25 at 16 28 23

Screenshot 2024-08-25 at 16 54 26

#### After

Screenshot 2024-08-25 at 16 28 27

Screenshot 2024-08-25 at 16 54 30
<br><br>

It doesn't introduce any change for already launched sites.

## Why are these changes being made?

To help people with launching their sites by making the "Launch site" button easier to find.

## Testing Instructions

1. Create a Dotcom account
2. Choose a domain
3. Skip the onboarding flow by clicking the "Skip to dashboard" link
4. Click the area with "Coming Soon" button in top-left corner
5. Click the "Launch site" button and make sure it works as expected

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Comment by davemart-in** [comment]
Just noting that there is also this button on the front0-end of your site:

CleanShot 2024-09-06 at 07 21 44@2x

Don't think that blocks this PR. I just wanted to call that out.

**Comment by pkuliga** [comment]
@davemart-in Yes I finally figured it out but still, it needs three clicks to Launch a site (open the preview -> click Visit site -> click Launch). This PR simplifies it to two 😄

**Comment by fditrapani** [comment]
hey @pkuliga. Thanks for making this update. 

I notice in some cases, we also show an edit button:

image

The spacing between all three buttons is not consistent. Can you update it so that we have the same spacing. Preferably, the spacing between the edit site and visit site buttons.

**Review by fditrapani — APPROVED** [review]
Nice! thanks for the update. Looks good to me!

**Comment by pkuliga** [comment]
Thanks! Let's try it! 🚀

**Pull request merged**
