### PR TITLE
Reader: Pass a content_width to the API

### PR DESCRIPTION
**Pull request by blowery**
Helps tiled galleries render correctly. This pretty much assumes that folks don't resize their browser window.

~~more info coming shortly.~~

todo:
- [x] how can we centralize making up the content_width prop?
- [x] should we take into account our breakpoints?

### CODE REVIEW

**Comment by samouri** [comment]
@blowery: what is the current problem with tiled galleries + their width that this is meant to solve?

**Comment by blowery** [comment]
@samouri we size them on the server, not the client, and the server assumes a content width of 720px. This allows us to tell the server what content width to use.

See http://calypso.localhost:3000/read/feeds/25801/posts/1050231304 for examples. Reload it at different browser widths.

**Comment by bluefuton** [comment]
Use of `document` is causing a few tests to bail.

**Comment by blowery** [comment]
Rejiggered this severely to inject the param at the API layer.

**Comment by fraying** [comment]
NICE 👍

**Comment by bluefuton** [comment]
> more info coming shortly.

Anything else we need to know before 👀 ?

**Comment by samouri** [comment]
I reloaded with myriad widths but I couldn't tell any difference between this and master.
In both the pictures get cutoff when i start out at a small width (no resizing after load):
cutoff image

**Comment by blowery** [comment]
@samouri checking, that doesn't sound right

**Comment by blowery** [comment]
@samouri good catch, missed the param to `readFeedPost`. Fixed in e80276ecf

**Comment by bluefuton** [comment]
Works great 👍 

I think we should add a style to drop the bottom margin in `div.tiled-gallery` (margin for `div` was recently added in https://github.com/Automattic/wp-calypso/pull/9894) to prevent gaps:

screen shot 2016-12-14 at 12 08 51

**Comment by samouri** [comment]
@blowery you fixed it! This LGTM now.

**Comment by blowery** [comment]
> I think we should add a style to drop the bottom margin in div.tiled-gallery (margin for div was recently added in #9894) to prevent gaps:

@bluefuton or maybe scope that div selector to divs that are direct descendants of story-content?

**Comment by blowery** [comment]
added the scope in https://github.com/Automattic/wp-calypso/pull/9948/commits/c769ffa86a2808a36d214ef74300c7a1f2bfe74b

**Comment by blowery** [comment]
Did a bit more jiggery-pokery to make these look more like photo cards. 

apex_park_ _cuteness__in_all_its_versatility_ _reader_ _wordpress_com

**Comment by fraying** [comment]
@blowery Can we use the same fade as in the main stream photo cards? This one looks ... different. 

cc @jancavan

**Comment by blowery** [comment]
@fraying it's the same fade, though it may be condensed. the height on the cards is fixed, where here it adapts to the height of the content.

**Comment by blowery** [comment]
what's the issue? too dark at the bottom?

**Comment by fraying** [comment]
@blowery Yeah, too dark on the bottom.

**Comment by blowery** [comment]
apex_park_ _cuteness__in_all_its_versatility_ _reader_ _wordpress_com

**Comment by blowery** [comment]
@fraying tweaked

**Comment by fraying** [comment]
@blowery Better! Gracias.

**Pull request merged**
