### PR TITLE
Gutenframe: turn on the feature flag for wpcalypso

### PR DESCRIPTION
**Pull request by rodrigoi**
#### Changes proposed in this Pull Request

Turns on the `calypsoify/iframe` feature flag for `wpcalypso`.

#### Testing instructions

Not much to test here 🤷‍♂️ .

### CODE REVIEW

**Comment by mmtr** [comment]
Is this a duplicate of https://github.com/Automattic/wp-calypso/pull/30529?

**Comment by vindl** [comment]
> Is this a duplicate of #30529?

It seems so. Both are still blocked by e2e tests anyway, unless there have been some updates on that front.

**Comment by mmtr** [comment]
> Both are still blocked by e2e tests anyway, unless there have been some updates on that front.

The updated E2E tests are ready (https://github.com/Automattic/wp-e2e-tests/pull/1797#issuecomment-467485829) but they have to be merged just before enabling the flag on wpcalypso. Otherwise (if e2e tests are merged before that) they will fail since they will find a Gutenlypso environment.

In summary, the checklist would be something like:
- Merge and land any remaining Gutenframe blocker.
- Rebase #30529 with master.
- Launch locally the e2e tests available in https://github.com/Automattic/wp-e2e-tests/pull/1797 against a local Calypso running #30529.
- If they pass, merge https://github.com/Automattic/wp-e2e-tests/pull/1797
- Relaunch the E2E build in #30529.
- If the build pass, merge #30529.

**Comment by rodrigoi** [comment]
Closing in favor of #30529

**Pull request closed without merging**
