### PR TITLE
Eslint: Remove eslines

### PR DESCRIPTION
**Pull request by sirreal**
#24504 has been moving slowly, but we have folks working on files all the time. Let's adjust lint rules to urge folks to chip-in. When you work on a file, fix it!

- Remove the eslint-eslines and eslines dependencies.
- Pre-commit and CircleCI linting based on changed files.

What do y'all think?

## Testing
- Check out these examples:
  Failing lint: https://circleci.com/gh/Automattic/wp-calypso/107367
  Passing lint: https://circleci.com/gh/Automattic/wp-calypso/107386

### CODE REVIEW

**Comment by flootr** [comment]
What do you think about using [okonet/lint-staged](https://github.com/okonet/lint-staged) to save time maintaining our custom hook?

**Comment by sirreal** [comment]
@flootr Can that handle what we're trying to do here? It could make sense for the pre-commit hook, but on CircleCI [we check files that have changes since branching from `master`](https://github.com/Automattic/wp-calypso/blob/ae023f141f89ecebe5a0e6563f3980932bff7671/.circleci/config.yml#L165-L169). Do you know whether there's a solution for that?

**Comment by blowery** [comment]
So this lints the entire file when it changes, not just the changed lines?

**Comment by sirreal** [comment]
> So this lints the entire file when it changes, not just the changed lines?

Yep! Folks would be responsible for getting lint passing on any files they touch.

**Comment by sirreal** [comment]
> I suppose cases like that could be `eslint-ignore`-d though and revisited later.

Yep, there are fixes that aren't trivial. In those cases, I think the approach you suggest is appropriate. We've effectively been ignoring eslint violations for a while, let's make that explicit.

Hopefully folks will be on board with putting forth a small effort when possible and don't ignore by default, but we'll have to see how this plays out 🙂

**Comment by sirreal** [comment]
Rebased, this should be ready.

**Review by ockham — APPROVED** [review]
LGTM. Rebase, reshrinkwrap & :ship:

**Comment by sirreal** [comment]
Rebased and ready for review!

**Review by blowery — APPROVED** [review]
🚢 :shipit:

**Pull request merged**
