### PR TITLE
WordPressLogo viewbox clipping

### PR DESCRIPTION
**Pull request by lsl**
#### Proposed Changes

* Updates the `viewBox` for `WordPressLogo` to fit the entire logo.
* This logo is used in the /start header it is separate from the `<Girdicon icon="my-sites"/>` used elsewhere.

#### Testing Instructions

* Compare http://calypso.localhost:3000/start/user and https://wordpress.com/start/user
* The logo should not be clipped

#### Before
Screenshot 2022-06-10 at 16-07-25 Create a site — WordPress com

#### After
Screenshot 2022-06-10 at 16-15-45 Create a site — WordPress com

Related to #

### CODE REVIEW

**Review by paulopmt1 — APPROVED** [review]
Small details like this make the difference, good job @lsl!

**Comment by mtias** [comment]
@lsl @paulopmt1 this is isn't the best way to address this since the rounding value for the width is going to be ever so slightly off, possibly causing blurring at different sizes.

I'm also not seeing any clipping issue with the original view box:

image

This is also used in more places. The problem in `/start` is that it's adding `stroke` through CSS, and should be fixed there.

**Comment by lsl** [comment]
Thanks @mtias, I think I tried that back in June but ran into the issue of it "not looking bold enough" (to match the normal my-sites version of the same logo). But I can see the blurring you're talking about over in the screenshots on https://github.com/Automattic/wp-calypso/pull/66288 so lets just swap to that instead!

**Comment by mtias** [comment]
Thanks! If there's a need for a bolder look from design, it seems we should just create a separate svg for that context.

**Pull request merged**
