### PR TITLE
Jetpack Pro Dashboard: Add WC Extensions copy

### PR DESCRIPTION
**Pull request by heydemoura**
Related to #

## Proposed Changes

* Adding copy according to pdpAdu-1mQ-p2

## Testing Instructions

- With an agency account enabled with the testing billing scheme
- Go to http://jetpack.cloud.localhost:3000/partner-portal/issue-license
- Click on the info icon on the products list for a non-Jetpack product or plan

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

**Review by rcoll — APPROVED** [review]
Seems fine, and everything works appropriately. Need to take care of the failing unit test before shipping, but otherwise this LGTM.

**Review by atanas-dev — APPROVED** [review]
I didn't test this extensively but it looks good.

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/8671786

Hi @heydemoura, could you please edit the description of this PR and add a screenshot for our translators? Ideally it'd include all of the following strings:
- `Offer personalized product bundles, bulk discount packages, and assembled products.`
- `Offer add-ons like gift wrapping, special messages, or other special options for your products.`
- `Minimum and maximum quantity rules for products, orders, and categories.`
- `Powerful marketing automation for WooCommerce - grow your store and make more money.`
- `Flexible online booking system - book classes, schedule appointments, or reserve items`
- `Support for one-on-one appointments or multi-person events`
- `The ability to offer special pricing for groups, days, or individuals`
- `Support for all timezones`
- `The ability to require confirmations or offer free cancellations`
- `Reminder notifications`
- `Sync with Google Calendar`
- `Support for add-ons to customize the experience`
- `Free Trials & Sign-Up Fees`
- `Subscriber Account Management`
- `Synchronized Payments`
- `Upgrades/Downgrades`
- `Flexible Product Options`
- `Subscription Coupons`
- `Customer Emails`
- `Create bulk discount packages`
- `Offer personalized boxes`
- `Create assembled products`
- `Recommend add-ons and essentials`
- `Offer more engaging upsells`
- `Image-based selections - customers can see what they’re getting before they buy.`
- `Flat fees - charge customers a flat fee regardless of how many products they ordered.`
- `Percentage fees - charge a fee for the add-on based on a percent of the total price.`
- `Text input - Let your customers enter custom text to create a custom t-shirt, add a monogram or personalize a card.`
- `Dropdown - customers can choose between a few pre-defined options with a drop-down field for your add-on.`
- `Checkboxes - make customization as easy and satisfying as checking a checkbox.`
- `Custom price - let your customers name their price, perfect for tips, donations, and gratuity.`
- `The ability to set quantity rules for products, orders, and categories.`
- `Follow-up Emails – Automatically email customers who buy specific products, ask for a review, or suggest other products they might like.`
- `Abandoned Cart – Remind customers who left items in their cart using emails at set intervals.`
- `Win Back Inactive Customers – Target inactive customers with email marketing campaigns. Include special offers and recommendations.`
- `SMS Notifications – Send SMS notifications to customers or admins for any of AutomateWoo’s wide range of triggers.`
- `Review Rewards – Encourage more product reviews by offering discounts. Limit the discount based on number of reviews posted and the rating given.`
- `Wishlist Marketing – Send timed wishlist reminder emails and notify when a wished product goes on sale. Integrates with WooCommerce Wishlists or YITH Wishlists.`
- `Card Expiry Notifications – Notify customers before a saved credit or debit card expires. This can reduce failed payments and churn when selling subscriptions.`
- `Personalized Coupons – Generate dynamically customized coupons for customers to raise purchase rates.`
- `Subscriptions Automation – Action WooCommerce Subscription events such as status changes, failed payments, and renewal reminders.`
- `Bookings Automations – Send emails on WooCommerce Bookings events such as booking confirmation or completion.`
- `Automatic VIP – Reward your best customers with VIP status based on different spending requirements.`
- `Let your customers book reservations, appointments, or rentals independently – no phone calls are required.`
- `Offer discounts for groups or people booking multiple slots, show lower prices for early birds, higher prices on weekends, or special prices for kids.`
- `Your customers see availability in their time zone`
- `Reduce no-shows with reminder notifications`
- `An intelligent booking system to avoid double-bookings`
- `Boost your bookings with a range of add-ons`
- `Multiple billing schedules available to suit your store’s needs`
- `Integration with over 25 payment gateways for automatic recurring payments`
- `Supports manual renewal payments through any WooCommerce payment gateway, along with automatic email invoices and receipts`
- `Supports automatic rebilling on failed subscription payments`
- `Give subscribers the ability to manage their own plan`
- `Built-in renewal notifications and automatic emails`
- `Detailed reports allow you to keep track of recurring revenue, the number of active subscribers, and more`
- `Sell more by creating discounted bundles or personalized boxes`
- `Create product offerings made from multiple inventory-managed parts.`
- `Boost your average order value by adding recommendations to popular products, and use discounts to maximize their impact.`
- `You can offer special options to your customers.`
- `Enable your customers to personalize products while they are shopping on your online store`
- `Specify minimum and maximum quantity limits per product/variation or order.`
- `Require specific products, or product categories, to be purchased in predefined quantity multiples.`
- `Prevent overstocking or stockouts, maintain optimal inventory levels, and reduce storage costs.`
- `Effortless setup and management right from your WordPress backend`
- `Send targeted, multi-step campaigns and offer customer incentives`
- `Measure the success of your campaigns`
- `Unlimited email sends`
- `AutomateWoo is 100% extendable`
- `Multilingual support. AutomateWoo has support for the popular WPML plugin`
- `AutomateWoo integrates with your favorite plugins and services`

Thank you in advance!

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/8671786).

**Pull request merged**
