### PR TITLE
Hosting Metrics: Add tooltip to line chart

### PR DESCRIPTION
**Pull request by sejas**
- Related to https://github.com/Automattic/dotcom-forge/issues/3436

## Proposed Changes

* Add tooltips to line charts
* Add also the time slot highlight.
* Avoid zooming in the chart with the cursor.

## Testing Instructions

* Navigate to `/site-monitoring/${siteSlug}` on an atomic site
* Move the mouse over the first line chart
* Observe the new tooltips

## Screenshots
Screenshot 2023-08-17 at 15 02 22
Screenshot 2023-08-17 at 15 02 40
Screenshot 2023-08-17 at 15 02 53

## Screencast

https://github.com/Automattic/wp-calypso/assets/779993/198b30d2-c811-415f-bbb7-1765ab5d988a

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

**Comment by javierarce** [comment]
This looks fantastic, great work!

Regarding the toolips, we should add a space between the colon and the quantity.
Screenshot 2023-08-17 at 15 25 53

Also, in that screenshot, I got 0.22 requests and I've noticed that on the response stats for my blog I also get decimal points. Does it make sense?

Finally, in the "Server performance" tooltip we should remove the number of requests that appear in the footer, since we already indicate that in the legend.

Screenshot 2023-08-17 at 15 25 28

**Review by katinthehatsite — APPROVED** [review]
It worked as expected for me - I just found a few small things that were a bit strange from the user experience:

I think you mentioned on Slack that we might need to change requests per minute to requests per second and I agree because at the moment it looks weird when you have a line going up on the graph but it does not indicate anything on the tooltip:

Screenshot 2023-08-17 at 3 27 23 PM

Another thing was that it is not clear what the measurements mean in the second and third line charts (that's the feedback probably not specific only to tooltip but it also affects a tooltip a bit). For example for 200 requests, it says `2.07` - is that 2.07 requests in that period? I am guessing so but it is a bit weird that it is 2.07 and not 2 or 3 if it shows the number of requests - does it make sense?

Screenshot 2023-08-17 at 3 28 05 PM


Other than that, it looks great! So much work - well done!!!

**Comment by javierarce** [comment]
A nice to have for mobile/tablets: would it be possible to show the tooltip when the user drags their finger? On the iPad (I'm using Safari) the tooltip only appears the first time I touch the screen and not while I'm dragging. It's not a show stopper, but it would be great to replicate the hover effect we get on desktop.

**Comment by katinthehatsite** [comment]
I also noticed a small issue on mobile devices where the tooltip seems to be cut off a bit:
Screenshot 2023-08-17 at 3 34 54 PM

**Comment by danielbachhuber** [comment]
@sejas Feel free to fix whatever you think is necessary to land this, and then we can create follow-up issues for polish.

**Comment by sejas** [comment]
@javierarce , @katinthehatsite , thanks for the review 🙌 .
I added space after the semicolon, removed the requests from the footer in the first chart and currently I'm displaying decimals in all the charts.

I'll deploy it now.

> @javierarce: Regarding the toolips, we should add a space between the colon and the quantity.

Done! https://github.com/Automattic/wp-calypso/pull/80712/commits/9b0fbe13293d3162a69e623fc35ccadfaed1e2e2

> @javierarce: Finally, in the "Server performance" tooltip we should remove the number of requests that appear in the footer, since we already indicate that in the legend.

Done! https://github.com/Automattic/wp-calypso/pull/80712/commits/17ee7e99c58a995a80103b33d9916f1af3fc3810

> @katinthehatsite: I think you mentioned on Slack that we might need to change requests per minute to requests per second and I agree because at the moment it looks weird when you have a line going up on the graph but it does not indicate anything on the tooltip:
> @javierarce: Also, in that screenshot, I got 0.22 requests and I've noticed that on the response stats for my blog I also get decimal points. Does it make sense?

- I started a PR converting requests per second instead of per minute, we will need to revisit that we are showing the data accurate https://github.com/Automattic/wp-calypso/pull/80755
The API returns decimals because it adds the requests in "batches/slots"


> @javierarce: A nice to have for mobile/tablets: would it be possible to show the tooltip when the user drags their finger? On the iPad (I'm using Safari) the tooltip only appears the first time I touch the screen and not while I'm dragging. It's not a show stopper, but it would be great to replicate the hover effect we get on desktop.

I'll take a look in the next days, but it seems hard to do it.


> @katinthehatsite: I also noticed a small issue on mobile devices where the tooltip seems to be cut off a bit:

I'll try to fix it as a follow-up.


> @katinthehatsite: Another thing was that it is not clear what the measurements mean in the second and third line charts (that's the feedback probably not specific only to tooltip but it also affects a tooltip a bit). For example for 200 requests, it says 2.07 - is that 2.07 requests in that period? I am guessing so but it is a bit weird that it is 2.07 and not 2 or 3 if it shows the number of requests - does it make sense?

Currently it is requests per minute. We can add that information in the chart description when we convert the requests per second.

```
Unsuccessful HTTP responses
Requests *per second* that encountered errors or issues during processing
```

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/8720808

Thank you @sejas for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/8720808).

**Pull request merged**
