### PR TITLE
Signup: Roll out the G Suite upsell to all users.

### PR DESCRIPTION
**Pull request by taggon**
As the modified version wins [the A/B test](https://github.com/Automattic/wp-calypso/pull/21068), this PR will roll out the winner to all users.

## Test plan

Follow [the instruction](https://github.com/Automattic/wp-calypso/pull/19134) except for the first step. You don't need to activate any tests.

cc @fditrapani

### CODE REVIEW

**Comment by fditrapani** [comment]
@klimeryk could you also take a look at this PR when you have some time?

**Comment by klimeryk** [comment]
I've also encountered the double upsell (before and after the purchase), so I'll hold on with a full review/thorough testing until it's fixed.

**Comment by taggon** [comment]
@fditrapani The first issue you mentioned will be handled in #22087. I will rebase this PR once it's merged.

**Comment by taggon** [comment]
@fditrapani What do you think about @klimeryk 's suggestion? I will merge this PR soon as it is approved but we can handle the UX issue in another PR if you think we should.

**Comment by fditrapani** [comment]
Yeah, some good suggestions from @klimeryk — thanks!

> But if you chose to just buy the domain, it did not show the upsell (not before or after checkout). Not a blocker, but feels like a missed opportunity, since G Suite should be supported on those domains as well :) (of course, you can buy it afterwards)

Makes sense, let's get this added.

> I'd also like to note that I was frustrated as a user when I clicked the Add Email option and then there was no way of changing my mind:

Let's go with this recommendation too. Google asked us to do it that way, but I doubt it's an effective tactic.

**Pull request merged**
