### PR TITLE
Sites Management Page: Add <HighlightMatches> component for rendering string matches

### PR DESCRIPTION
**Pull request by p-jackson**
**This is really a word in progress, but I just wondered if people thought it was worth pursuing so I'm putting it up for review**

#### Proposed Changes

Highlighting the elements on the page that caused it to be included in the search results

CleanShot 2022-07-29 at 17 28 44@2x

*

#### Testing Instructions

*

#### Pre-merge Checklist

- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?

Related to #

### CODE REVIEW

**Comment by sejas** [comment]
@p-jackson, I like the idea of seeing the string matches.
It helps me to focus on the keywords and to understand what part of my string matches.
It helps especially if you have multiple domains.

**Comment by danielbachhuber** [comment]
> This is really a word in progress, but I just wondered if people thought it was worth pursuing so I'm putting it up for review

I'm personally indifferent — could be helpful, could be visual overhead. I'd be curious to get a broader design opinion on it (do we do this anywhere else? should a decision live in a style guide? does core do this?)

**Comment by wojtekn** [comment]
This looks interesting and cool at first, but I'm not sure if it's good for Sites Management Page UX: is the data we are searching through that complex? is the user searching through tens/hundreds/thousands of sites? does it make sense to show all occurrences of "s" when I search for "s"? 

There are places in which it's helpful for me: when I look for exact string occurrence by using the "Find in Files" feature in the IDE or when I try to navigate through complex UI like Preferences in PhpStorm.

**Comment by p-jackson** [comment]
It's a nice debugging tool for figuring out why the fuzzy search doesn't feel right to me (#66248)
But I think it also adds quite a bit of complexity to the implementation e.g. our site hooks can't just return a list of sites, they have to return a list of sites _and_ a bunch of meta data about substring ranges and where they come from.

I'll close this PR. The code will be here if we ever want to refer to it.

**Pull request closed without merging**
