### PR TITLE
Marketing: Add logos, fix image alignment and button sizes

### PR DESCRIPTION
**Pull request by jancavan**
#### Changes proposed in this Pull Request

- Use brand logos instead of illustrations
- Increase size of illustration in SEO card
- Align images to top of card
- Use `compact` button for secondary CTAs

**Before:**
Screenshot 2019-05-07 15 56 09

**After:**
Screenshot 2019-05-09 13 54 09

#### Testing instructions

1. Go to `http://calypso.localhost:3000/marketing/tools/[site]`
2. Double check if updates mentioned above are reflected

### CODE REVIEW

**Comment by jancavan** [comment]
> the images look a little small before they are hidden at 1040px.

@cbauerman Yes, this is fine. I think 1000px+ is a bit soon to start dropping images, then it just starts to look like a wall full of text.

That said, I brought the images back in the **secondary** cards, but omitted them as soon as it hits `<480px`.

Screenshot 2019-05-08 14 25 00

**Comment by stephanethomas** [comment]
There is an issue with the `Google My Business` button that is larger than other secondary ones:

screenshot

That's because the `MarketingToolsFeatureButtonWithPlanGate` should be updated.

> I brought the images back in the secondary cards, but omitted them as soon as it hits <480px.

As you can see in the screenshot above I don't see those illustrations when the viewport is narrow. Did I miss something?

**Comment by jancavan** [comment]
@stephanethomas I forgot to push my changes out 🤦‍♀ Should be good now.

**Comment by jancavan** [comment]
> That's because the MarketingToolsFeatureButtonWithPlanGate should be updated.

I had updated that in previous changeset: https://github.com/Automattic/wp-calypso/pull/32876/commits/0e272f2825f57b4cda8bb864f9dc619c9734880f#diff-db5de8c849a73908abd90b2592b976bc

And this is what I see:

Screenshot 2019-05-09 08 15 48

Are there other places I should update it? @stephanethomas

**Comment by jancavan** [comment]
> Are there other places I should update it?

@stephanethomas Actually, nvm I found them and did the updates in this changeset: https://github.com/Automattic/wp-calypso/pull/32876/commits/01c74fb623e93586858b36d484403cc9d38f8692

Not connected to GMB:
Screenshot 2019-05-09 08 22 52

Connected to GMB:
Screenshot 2019-05-09 08 23 00

Gated:
Screenshot 2019-05-09 08 25 10

**Comment by jancavan** [comment]
In: https://github.com/Automattic/wp-calypso/pull/32876/commits/f87b5aa3dc5841048a4a68850ea396c82f15d41a, I replaced the illustrations with each third-party service's corresponding logo.

After getting feedback, we agreed that it made sense to use logos to leverage brand equity and provide users a sense of familiarity if they see some of these services.

Screenshot 2019-05-09 13 54 09

**Comment by jancavan** [comment]
Note that the logos for Google Ads and Sharing are also in this commit: https://github.com/Automattic/wp-calypso/commit/f87b5aa3dc5841048a4a68850ea396c82f15d41a even though cards for them have not been added yet.

Google Ads: https://github.com/Automattic/wp-calypso/commit/f87b5aa3dc5841048a4a68850ea396c82f15d41a#diff-ca20b230777befd009709730b2ac44c0

Sharing: https://github.com/Automattic/wp-calypso/commit/f87b5aa3dc5841048a4a68850ea396c82f15d41a

**Comment by stephanethomas** [comment]
Excellent, this is ready to ship.

**Pull request merged**
