### PR TITLE
Removes plugins AB test and enables sidebar item for all sites.

### PR DESCRIPTION
**Pull request by roundhill**
🚀 Plugins!

@dmsnell care to take a look?

### CODE REVIEW

**Comment by dmsnell** [comment]
@roundhill we should probably remove the config flag from `development` and `wpcalypso` and `horizon` as well

**Comment by dmsnell** [comment]
@roundhill I went ahead and removed a few more references, but you should double-check me since I pulled out another full test

**Comment by roundhill** [comment]
Good call @dmsnell. I also see it in `stage.json`, should it be removed from there too?

**Comment by aduth** [comment]
This introduced a file which doesn't appear to be used:

```
client/components/tinymce/plugins/wpcom-view/views/generic-shortcodes/index.jsx
```

**Pull request merged**
