### PR TITLE
Image editor: fix cancel using esc button shouldn't close the "whole"…

### LINKED ISSUE #8084: Image Editor: Cancel shouldn't close the modal
#### Steps to reproduce
1. Create/Edit a post
2. Add a media
3. Start to edit image meta data (bottom left button)
4. Start to edit the image (top right button)
5. Press `ESC` button

#### What I expected

Get the previous screen. Something like the following:

#### What happened instead

The modal was closed.

image

### PR DESCRIPTION
**Pull request by ivantedja**
Took the idea from [this code](https://github.com/Automattic/wp-calypso/blob/master/client/components/dialog/dialog-base.jsx#L19)

@retrofox  please help to review it 😄 

Closes #8084

### CODE REVIEW

**Comment by retrofox** [comment]
Hi @ivantedja I wonder if we could get rid of the mixin. I'm aware that we're using a lot of mixins in our code but I try to avoid it when I do a new improvement.
About this: [Mixins Considered Harmful](https://facebook.github.io/react/blog/2016/07/13/mixins-considered-harmful.html)

**Comment by ivantedja** [comment]
Hi @retrofox , the problem is, the first modal is triggered by [dialog-base.jsx](https://github.com/Automattic/wp-calypso/blob/master/client/components/dialog/dialog-base.jsx#L19). The `closeOnEsc` mixin will create a stack of components that will be closed by ESC button. My changes was calling `closeOnEsc` mixin to add another stack (MediaModalImageEditor) so that it is stacked properly. I understand that this changes make it farther from "no mixin" 😢  but right now I don't find any clean way other than that as the 1st modal has been observed to be closed once ESC button is pressed.

`closeOnEsc` mixin seems similar with [this](https://facebook.github.io/react/blog/2016/07/13/mixins-considered-harmful.html#subscriptions-and-side-effects). But it looks pretty daunting.

What do you think?

**Comment by gwwar** [comment]
Howdy @ivantedja, thanks for the contribution! 

I took a look of usage in the code and it seems like we are using this mixin all over the place without a good alternative, so your approach is completely valid here.

We'll eventually write up a few PRs to perhaps port the mixin to a higher order component, but that seems super out of scope for this issue. 😄 We'll be taking another 👀 and hopefully will merge this in soon.

**Comment by retrofox** [comment]
Hi Ivan, I think we should go ahead with your PR by at the moment.
Let's kick "avoiding mixins" for a near future. I'm sorry to create obstacles here.
Thank you. LGTM. 🚢

**Comment by retrofox** [comment]
close-image-editor-canvas-4

Tested and it works like expected.

**Comment by artpi** [comment]
Tested it too. Thanks @ivantedja !

**Comment by ivantedja** [comment]
Thanks @retrofox @gwwar @artpi ! I would love to see how you guys porting the mixins, I'm sure I'm gonna learn a lot!

Wow, a lot of cats btw 😸

**Comment by spen** [comment]
Hi!
For anybody interested, I've working on porting the `closeOnEsc` mix-in to a HoC.
It doesn't port cleanly, so there is a change in implementation... Here's the PR #10268 , at present it's just a draft and shows 2 different potential solutions.

Sorry no cats! :(

**Pull request merged**
