### PR TITLE
E2E: set up users on Simple+Free and Simple+Personal plans.

### PR DESCRIPTION
**Pull request by worldomonation**
#### Changes proposed in this Pull Request

This PR adds new users to the config file:
- simpleSiteFreePlanUser (simple site, free plan)
- simpleSitePersonalPlanUser (simple site, personal plan)

Details:
The failure noted in https://github.com/Automattic/wp-calypso/issues/57660 has been observed intermittently for the user `gutenbergSimpleSiteUser`, and this has increased noise in the test results. While it appears the Blogger Experience Pod is taking a look at the issue via https://github.com/Automattic/wp-calypso/issues/57702, the pending 'public' release of Playwright E2E adds time pressure to eliminate as much noise from tests as possible.

The solution here is to discontinue the use of `gutenbergSimpleSiteUser` where possible. 

This PR is the first step towards that direction and sets up the new types of users as noted above.
The intention is for E2E test accounts to be more granular (within reason) and separated by feature type.

If this PR is accepted, the e2e specs themselves will be moved off `gutenbergSimpleSiteUser` in a subsequent PR.

#### Testing instructions

- [x] normal tests
  - [x] mobile
  - [x] desktop

Related to https://github.com/Automattic/wp-calypso/issues/57660

### CODE REVIEW

**Comment by dpasque** [comment]
>The failure noted in #57660 has been observed intermittently for the user gutenbergSimpleSiteUser, and this has increased noise in the test results.

Could you explain that a little more in the context of this change? Was the result of that investigation that the state tracking for the welcome tour for that specific user seems to be busted in some way?


I like the idea of having a free & personal plan test user, but I wanted to double check that we wanted to use them as a replacement for the `gutenbergSimpleSiteUser`. My understanding of the `gutenbergSimpleSiteUser` was that they were closely coupled with the `gutenbergSimpleSiteEdgeUser` to be used side by side to test Gutenberg upgrades. I wonder if we should try to preserve that kind of a relationship, where we have a user dedicated to Gutenberg upgrades who is kept closely in parallel with the edge user, all apart from the Gutenberg-edge sticker. @fullofcaffeine - do you have anything to add here?

That said, I do think removing `gutenbergSimpleSiteUser` from anywhere that is _not_ directly doing Gutenberg upgrade testing would be a good idea!

One final question... How does this intersect with `gutenbergSimpleSiteFreePlanUser`? I don't think they are currently used in any tests, it sounds like maybe we don't need them anymore, and can just use this new free user anytime we need a free plan user?

**Comment by worldomonation** [comment]
Good questions and you've hit on some of the points I've struggled with myself on coming up with this alternative.

> > The failure noted in #57660 has been observed intermittently for the user gutenbergSimpleSiteUser, and this has increased noise in the test results.
> 
> Could you explain that a little more in the context of this change? Was the result of that investigation that the state tracking for the welcome tour for that specific user seems to be busted in some way?

I suspect there is something wrong with this specific user, as the failure in the `Start new post` step has only ever been observed with the `gutenbergSimpleSiteUser` user. 

This user is used for `Editor: Basic Post Flow` and `Media: Upload` among others. My observation has been that steps that involve starting a new post with this user tend to fail together (but not always).

The counterpoint to this observation is that specs such as `Likes: Comment` and `Likes: Post` which _also_ use the problematic user has **never** failed at the `Start new post` step. 

> I like the idea of having a free & personal plan test user, but I wanted to double check that we wanted to use them as a replacement for the `gutenbergSimpleSiteUser`. My understanding of the `gutenbergSimpleSiteUser` was that they were closely coupled with the `gutenbergSimpleSiteEdgeUser` to be used side by side to test Gutenberg upgrades. I wonder if we should try to preserve that kind of a relationship, where we have a user dedicated to Gutenberg upgrades who is kept closely in parallel with the edge user, all apart from the Gutenberg-edge sticker.

I agree and note that my proposal is not to remove `gutenbergSimpleSiteUser` from the list of available users, but rather to discontinue using this user for all sorts of tests that do not involve the need to verify the stability of current Gutenberg install. 

> That said, I do think removing `gutenbergSimpleSiteUser` from anywhere that is _not_ directly doing Gutenberg upgrade testing would be a good idea!

Fully agreed here - the intention is to have a separate account for testing things like Likes, Media upload or anything else that doesn't involve Gutenberg editor.

> One final question... How does this intersect with `gutenbergSimpleSiteFreePlanUser`? I don't think they are currently used in any tests, it sounds like maybe we don't need them anymore, and can just use this new free user anytime we need a free plan user?

The change here involved creating a new set of user for the Simple + Personal part, but the Simple + Free user was repurposed (and renamed) from existing `gutenbergSimpleSiteFreePlanUser`.

**Comment by worldomonation** [comment]
This change won't fully resolve the issues we're seeing in #57660 though, since `Editor: Basic Post Flow` runs as part of the Pre-Release Tests. This user (`gutenbergSimpleSiteUser`) has resulted in intermittent failures there, with the most recent being TeamCity ID 6974976 which ran on November 12.

We can always put this change on hold to observe how `gutenbergSimpleSiteUser` behaves, but in the context of stamping out flakiness prior to canary changes going live, we do need to ensure that there is a workaround so Editor test doesn't continue to fail.

**Comment by dpasque** [comment]
>Fully agreed here - the intention is to have a separate account for testing things like Likes, Media upload or anything else that doesn't involve Gutenberg editor.

Excellent that all sounds great to me!

>This change won't fully resolve the issues we're seeing in #57660 though, since Editor: Basic Post Flow runs as part of the Pre-Release Tests.

Actually, I think we could also make an exception for that test because it is used in so many places to have the non-edge user be one of these new users! There's so much other Gutenberg testing in the other Gutenberg specs that I feel confident they would catch any errors that were unique to the `gutenbergSimpleSiteUser `.

>the Simple + Free user was repurposed (and renamed) from existing gutenbergSimpleSiteFreePlanUser.

Ack, missed that, sorry!

Thank you for all the thorough answers!! I feel great about this!

**Review by dpasque — APPROVED** [review]
🚀

**Comment by worldomonation** [comment]
> > This change won't fully resolve the issues we're seeing in #57660 though, since Editor: Basic Post Flow runs as part of the Pre-Release Tests.
> 
> Actually, I think we could also make an exception for that test because it is used in so many places to have the non-edge user be one of these new users! There's so much other Gutenberg testing in the other Gutenberg specs that I feel confident they would catch any errors that were unique to the `gutenbergSimpleSiteUser `.
> 

Sounds good, I will file a new PR after this switching over many of the `gutenbergSimpleSiteUser` to the new users.

> > the Simple + Free user was repurposed (and renamed) from existing gutenbergSimpleSiteFreePlanUser.
> 
> Ack, missed that, sorry!

I actually didn't write that anywhere - sorry I that's on me.

**Pull request merged**
