### PR TITLE
Query manager: Unify schemas (take 2)

### PR DESCRIPTION
**Pull request by sirreal**
Second attempt at #23361

Build fails because `deep-freeze` is a `devDependency`. Who knew? 😅 

Reverts Automattic/wp-calypso#23592

### CODE REVIEW

**Comment by sirreal** [comment]
Manual deep-froze… not thrilled with the readability but it's effective.

**Comment by ockham** [comment]
The nested `Object.freeze()`s are kinda... ugly 😅 What about promoting `deep-freeze` to a normal `dependency` instead?

**Comment by sirreal** [comment]
The module is really small, I'll get some ICFY stats to compare.

**Comment by sirreal** [comment]
```
Commit: 0b388e439daa15e955617589ce1866cd871d21b3
Author: sirreal
At: 2018-03-23T13:54:12Z
Message: Manual deep-freeze :/
Delta:
chunk     stat_size           parsed_size           gzip_size
build        -347 B  (-0.0%)       -331 B  (-0.0%)      +42 B  (+0.0%)
manifest       +0 B                  +0 B                +2 B  (+0.1%)
```

**Comment by sirreal** [comment]
🤦‍♂️ I introduced several typos in 0b388e4, I'll clean those up after we get size stats.

**Comment by sirreal** [comment]
😕 final stats here:

```
Commit: 6d65f077edd4641d73a59a3205689e0e4c1107db
Author: sirreal
At: 2018-03-23T20:32:02Z
Message: Update deps
Delta:
chunk  stat_size           parsed_size           gzip_size
build     -297 B  (-0.0%)       -313 B  (-0.0%)      +88 B  (+0.0%)
```

Seems reasonable

**Comment by sirreal** [comment]
> What about promoting deep-freeze to a normal dependency instead?

I've gone back and forth and I think I'd rather avoid introducing a new dep just for this. It's trivial to just introduce a new dependency, but quite difficult to rip it out. And when folks are dedicating significant time to removing deps that aren't critically important to shave bytes off the build size… just seems counterproductive to introduce `deep-freeze` here.

Any objections to shipping with all the `Object.freeze`es?

**Comment by ockham** [comment]
> Any objections to shipping with all the `Object.freeze`es?

I’d honestly rather go with `deep-freeze`. Calypso is pulling in dependencies left and right for worse reasons than this. IMO, what you're saying about the dependency:

> It's trivial to just introduce a new dependency, but quite difficult to rip it out.

could also be said about those nested `Object.freeze`s. Totally worth those few bytes 😁

**Comment by sirreal** [comment]
Fair enough. Went with `deep-freeze` approach again. I'll give this a spin, wait for CI, then this should be good to go. Thanks @ockham

**Pull request merged**
