### PR TITLE
Reader: move post comments to Redux, try 2

### PR DESCRIPTION
**Pull request by blowery**
Reverts Automattic/wp-calypso#5235

A second attempt at landing reduxed comments. Need to fix comments in my sites before landing this.

cc @mtias @bluefuton

### CODE REVIEW

**Comment by blowery** [comment]
One fun thing I noticed: since we're auto expanding comments, the initialSize isn't really respected. It's correct for the top level, but doesn't take into account expansion.

**Comment by blowery** [comment]
current look

screen shot 2016-05-05 at 4 12 29 pm

**Comment by blowery** [comment]
@mtias noticed a fun bug in my sites with this. If you open a comments section for a post with a lot of comments, then scroll down (assuming there are more posts past the expanded one), the comment list will disappear. Appears this happens because the infinite list decides to page in new results and re-renders the component. The state item that expanded the comments gets lost and the comments collapse.

We probably either need a new store to stash the expanded state in, or a bit in the redux ui tree?

**Comment by blowery** [comment]
@mtias happens in prod too. hrm.

**Comment by jancavan** [comment]
Updated to just use text instead of a button. Also removed the icon since it doesn't really add much value.

screenshot 2016-05-05 14 33 20

@blowery I think we should load 30 initial, 30 after. 5 seems small for an extra click.

**Comment by jancavan** [comment]
A different number still flashes upon clicking the "View earlier comments link". Ideally, it should just show the number it's going to resolve to. It's not terrible, just not ideal. 

https://cloudup.com/cLni7Z1pl2H

Re: https://github.com/Automattic/wp-calypso/pull/4817#issuecomment-212884517

Sorry, my bad. It works good with nested comments, but not the ones in the root. Possible solutions:

- Revert to appending new comments to the bottom, but this creates an issue in long nested comments where you don't see your comment after hitting enter (we could have the new comment flash to address this).
- Append new comment to the bottom of list, but in root only (drawback: creates inconsistency with nested comments behavior).

**Comment by blowery** [comment]
> A different number still flashes upon clicking the "View earlier comments link". Ideally, it should just show the number it's going to resolve to. It's not terrible, just not ideal.

Yeah... I think I may have a way around that.

**Comment by blowery** [comment]
> Sorry, my bad. It works good with nested comments, but not the ones in the root. Possible solutions:
> - Revert to appending new comments to the bottom, but this creates an issue in long nested comments where you don't see your comment after hitting enter (we could have the new comment flash to address this).
> - Append new comment to the bottom of list, but in root only (drawback: creates inconsistency with nested comments behavior).

@bluefuton any thought on how nasty the first option might be?

**Comment by bluefuton** [comment]
> Revert to appending new comments to the bottom, but this creates an issue in long nested comments where you don't see your comment after hitting enter (we could have the new comment flash to address this).
> @bluefuton any thought on how nasty the first option might be?

It's doable, but not particularly easy. We'd have to scroll them to the correct place and highlight the new comment. Potential complications around handling posting errors/editing comment in My Sites perhaps?

"Append new comment to the bottom of list, but in root only" is much easier. It's sorted the opposite way chronologically to nested comments, so it's perhaps a little odd for the latest comment to go at the bottom, but we currently ignore the chronological sort when appending a new comment to the top in nested comments anyway.

**Comment by blowery** [comment]
> "Append new comment to the bottom of list, but in root only" sounds easier.

OK. I think that makes sense, since the comment box for the root is at the bottom already.

**Comment by jancavan** [comment]
> It's sorted the opposite way chronologically to nested comments, so it's perhaps a little odd for the latest comment to go at the bottom

We order both root and nested comments chronologically. The only difference is, in nested comments, we slide the new comment at the top and it gets moved down the bottom after a refresh. That's fine. It''s more important for users to receive validation that their comment indeed got posted vs what timestamp it has against all the other comments.

**Comment by blowery** [comment]
Made it sort root level comments in https://github.com/Automattic/wp-calypso/pull/5236/commits/64bba33ad62666256690d2961668a525e32f8780, should be done afaict.

**Comment by jancavan** [comment]
Reverted the text. I think we need to say "**Showing** x of y". Updated here: https://github.com/Automattic/wp-calypso/pull/5236/commits/f146aaa0e62bad5bc96cd4bda443aad40ea6d5bf

screenshot 2016-05-06 11 58 27

Looking at it more, it's confusing if it only says (25 of 100):

screenshot 2016-05-06 12 01 28

I don't know if 25 means I'm seeing 25 or I'm about to load 25 since it's attached to the action. If we'd like to drop the word "showing", we would need to separate the count from the link itself.

But this works great 👍  🎉

**Pull request merged**
