### PR TITLE
Jetpack Sync: Display an error notice when requesting sync fails

### PR DESCRIPTION
**Pull request by ebinnion**
Before this PR, we have zero error handling for sync status. This PR adds an error notice when requesting a full sync fails. 

If an error message is returned from the API, we display that message in the error notice. Otherwise, we display a generic error message.

To test

- Checkout `update/jetpack-sync-error-on-request` branch
- Go to `/settings/general/$site` where `$site` is on the latest `master` of Jetpack
- After the page loads, verify that the bluish status notice looks OK
- Now, go to "Network Conditions" in the console, and turn off WIFI for the page
- Click "Perform full sync"
- Ensure that error notice is displayed
- Return wifi to normal
- Click "Perform full sync" again
- Ensure that the UI recovers and sync goes through

cc @lezama @enejb for code review. cc @rickybanister for design review.

After screenshots:

screen shot 2016-07-14 at 2 30 09 pm
screen shot 2016-07-14 at 2 30 24 pm
screen shot 2016-07-14 at 2 30 36 pm

Test live: https://calypso.live/?branch=update/jetpack-sync-error-on-request

### CODE REVIEW

**Comment by rickybanister** [comment]
That error doesn't really tell them much about why it failed. Do we know any information about the failure?

I also think we could probably switch from 'try again later' to a notice action saying 'try again' that is the same as clicking the 'perform full sync' button, just to give them something to click.

**Comment by ebinnion** [comment]
> Do we know any information about the failure?

Maybe. :) When making an API request while offline, there is no message. Which is why we have the generic error message as a fallback.

That being said, there are some errors that can be returned from the API, but I don't think any will apply to this. For example, we only allow admins to begin a sync. But, Calypso disables the settings UI for non-admins as is.

So, this is a bit edge case, but I think the biggest issue will be network conditions. Perhaps we can combine the offline check to disable the UI with this error notice to get something a bit better though. I've got an idea. Let me take a pass ;)

**Comment by ebinnion** [comment]
I updated the PR so that we use a `NoticeAction` for the "Try again" link. I also made a change so the reducer so that we don't get rid of the request error when making a new request. This fixes an issue where the UI could flicker while waiting for the next request to come in.

**Comment by enejb** [comment]
Shouldn't we have 2 errors. One for scheduling the full sync and the other for when we don't get back the sync status.

They are a bit different. Maybe we can try to get the status from the site a few times and if we don't get the status on the 3rd try tell the user that the site is not responsive.

Another thing that would be nice to add. It could be done in a different PR is Tracks events.

**Comment by ebinnion** [comment]
My intention was to address those in separate PRs. One to address the sync status errors and one for analytics.

**Comment by enejb** [comment]
Then I think this is ready to merge :shipit:

**Comment by ebinnion** [comment]
I created a separate issue to handle a potential design issue where we should make the error messages more friendly. I'm going to go ahead and merge this for now. I can address any other feedback in separate PRs.

**Pull request merged**
