### PR TITLE
Update clickable banner to be more obviously clickable

### PR DESCRIPTION
**Pull request by fditrapani**
#### Changes proposed in this Pull Request

When you visit the plugins screen, it's not obvious that the upgrade banner is clickable. This PR updates the banner so that people know they can click it. I also updated the location you're sent to on the plugin page so that it matches what we're doing on the plugins page which is send you right to the cart with the plan in there.

**Before**
image

**After**
image

#### Testing instructions

**For plugins**
* Visit `/plugins/{site-slug}` for a site that is on any plan lower than business.
* Click on the banner to make sure it takes you to the cart with the business plan.

**For a single plugin**
* Visit `/plugins/{site-slug}` for a site that is on any plan lower than business.
* Click on any plugin
* Click on the banner to make sure it takes you to the cart with the business plan.

### CODE REVIEW

**Comment by jaswrks** [comment]
LGTM 🚢

**Comment by fditrapani** [comment]
> At least one of them was added in #26868 by @adamziel so perhaps he should review this.

@adamziel do you mind taking a quick look at this PR?

**Comment by adamziel** [comment]
If you remove `disableHref` prop then you'll have both `href="/plans"` and `onClick` handler redirecting to checkout. In my tests, after clicking the banner I can see the plans page for about 1-2 seconds, and then the checkout page. You should either leave the `disableHref` in place, or replace it with `href` prop with checkout as a destination.

**Comment by fditrapani** [comment]
Thanks for the background @adamziel. I have updated the code by removing the onClick event and passing an href instead. Can you take a look and let me know how it works for you now?

**Pull request merged**
