### PR TITLE
Split the posts-pages section into two

### PR DESCRIPTION
**Pull request by jsnajdr**
ICFY results:

```
chunk                                                                  stat_size             parsed_size             gzip_size
account~ads~async-load-design~...~posts-pages                           -35157 B  (deleted)     -20513 B  (deleted)    -4751 B  (deleted)
account~ads~async-load-design~...~posts~pages                           +35157 B      (new)     +20513 B      (new)    +4751 B      (new)
async-load-components-web-preview-component~posts-custom~posts-pages    -32004 B  (deleted)     -16813 B  (deleted)    -4246 B  (deleted)
async-load-components-web-preview-component~posts~posts-custom          +32004 B      (new)     +16813 B      (new)    +4246 B      (new)
posts-custom~posts-pages                                               -293919 B  (deleted)    -133484 B  (deleted)   -28461 B  (deleted)
posts~posts-custom                                                     +293919 B      (new)    +133484 B      (new)   +28461 B      (new)
posts-pages                                                             -88602 B  (deleted)     -43929 B  (deleted)   -11401 B  (deleted)
pages                                                                  +101992 B      (new)     +52817 B      (new)   +13002 B      (new)
posts                                                                   +14457 B      (new)      +7263 B      (new)    +2704 B      (new)
```

Summary:
- loading just `posts` needs 36.7kB less parsed code: difference between `posts-pages` and `posts`, shared chunks remain the same
- loading just `pages` needs 141.4kB less parsed code: `pages` is bigger than `posts-pages`, but we save on 2 shared chunks that are needed only by `posts`
- loading `posts` and then `pages` needs 16.2kB more parsed code: duplication overhead of (`posts` + `pages` - `posts-pages`)

### CODE REVIEW

**Comment by blowery** [comment]
@jsnajdr do you still want to pursue this?

**Comment by jsnajdr** [comment]
It makes the initial load faster most of the time... And manually squashing multiple sections into one module is no longer needed since webpack started automatically creating shared chunks. Let's keep it open.

**Comment by jsnajdr** [comment]
Decided to revive this ancient PR and finally merge it. Simply gives both `pages` and `posts` its own section name and lets webpack do its shared chunk optimization automatically.

**Things to test:**
- hovering over "Posts" and "Pages" sidebar items preloads the right chunks
- the inline help button in the corner shows the right contextual links (related to Posts and Pages)

@blowery can you have a look?

**Review by blowery — APPROVED** [review]
LGTM

**Pull request merged**
