### PR TITLE
accessible-focus: Extract into package, re-write in TypeScript, test, and handle deprecated APIs

### PR DESCRIPTION
**Pull request by sarayourfriend**
#### Changes proposed in this Pull Request

* Extract `accessible-focus` into a package
* Rewrite it in TypeScript
* Add tests
* Handle deprecated APIs

#### Testing instructions

* Open the app and navigate using the keyboard. Ensure that the `accessible-focus` classname is added to body.
* Open the app and navigate using your mouse. Ensure the classname is not added.
* Ensure the classname is removed when you switch to mouse navigation.

### CODE REVIEW

**Review by tyxla — COMMENTED** [review]
I wonder if this is something that makes sense to directly be contributed to Gutenberg and reused from there. @diegohaz do you think this could be useful there?

**Comment by diegohaz** [comment]
@tyxla Yeah! I think it could be a good addition to the `@wordpress/a11y` package. I don't know what other people will think, but it's worth making a pull request there.

**Review by diegohaz — APPROVED** [review]
I've tested the site with keyboard and mouse and it's working as expected (the class name is being added/removed). The only issue (that I guess isn't really a responsibility of this PR) is that sometimes it's very hard to identify where the focus is because the focus ring is very subtle and inconsistent among elements.

**Comment by sarayourfriend** [comment]
Thanks @diegohaz, I'll see about adding a note in the next core-js talk to guage interest!

**Pull request merged**
