### PR TITLE
Reader: Add ability to sort search results by date

### PR DESCRIPTION
**Pull request by blowery**
Allows a user to choose relevance- or date-based sorting for search results on Reader Search.

2eae4c10-0f10-11e7-885b-3aa78cad65ea

### CODE REVIEW

**Comment by fraying** [comment]
Very nice! And fast! 👏 Bravo!

Possible to match the colors in the design?

search-sort-2

**Comment by fraying** [comment]
Interaction Question:

If I do a search, change to Date sort, and then change the search term manually (click in the box, delete the term, add a new term) ... the sort stays set to Date.

But if I do a search, change to Date sort, and then click one of the suggested searches ... the sort reverts to Relevance. 

So, question: Is it possible to leave the sort independent of the term? In other words, can we make it so that if you click a suggestion, the sorting doesn't change from wherever you had it?

**Comment by fraying** [comment]
Update: Colors are now perfect!

**Comment by blowery** [comment]
> So, question: Is it possible to leave the sort independent of the term? In other words, can we make it so that if you click a suggestion, the sorting doesn't change from wherever you had it?

Done.

**Comment by bluefuton** [comment]
UI todo:
- ensure it still looks ok when terms are translated
- figure out how we want to handle search text that flows under the sort buttons
- figure out how to handle RTL folks

**Comment by bluefuton** [comment]
Tested in Chrome and IE. Works a treat!

I'd be happy to merge this, get it on wpcalypso and do any final UI tinkering in a followup PR 👍

**Pull request merged**
