### PR TITLE
Swap the old green for blue in illustrations used on the Plan page.

### LINKED ISSUE #32522: Post Checkout/Plans: Cards using green color in illustrations
Screen_Shot_2019-03-07_at_11 58 22_AM

This site is a Simple site and for some reason, it's using Jetpack image. Notice the green. 

Let's replace it with something that better represents priority support.

### PR DESCRIPTION
**Pull request by alaczek**
On Plans page there's a mismatch of icons - some using the new official blues, some using the old green. In this commit I'm swapping the colors, while leaving the original icons intact.

#### Testing instructions
1. Navigate to https://wordpress.com/plans/my-plan/{site}
2. Make sure none of the icons in feature cards are using green in them.
3. Check on sites with different level plans, including Jetpack sites with a plan (Personal, Premium, Professional)

**Example of a Premium plan site**

Before
dotcom_premium

After
dotcom_premium_after

Fixes #32522

### CODE REVIEW

**Comment by alaczek** [comment]
Now that I think about it, I should probably remove the old `jetpack-` illustrations, if they are not being used anywhere anymore.

**Comment by sixhours** [comment]
The Advanced Customization block image isn't appearing for me; I'm getting a 404:

Screen Shot 2019-05-22 at 10 30 39 AM

Otherwise these look great!

**Comment by sixhours** [comment]
e2e test failure appears unrelated to this PR; I think we can safely ignore it.

**Comment by alaczek** [comment]
Good catch on the missing illustration!

**Comment by sixhours** [comment]
It's working! Hurrah! Ship this puppy. :)

**Pull request merged**
