### PR TITLE
FSE: Update calypso-build to latest 4.2.1

### PR DESCRIPTION
**Pull request by sirreal**
Update FSE calypso-build to latest version. Required for #37031.

## Testing
- Make sure the FSE build and output continues to work as expected.

### CODE REVIEW

**Comment by sirreal** [comment]
Needs another publish of calypso-build. `4.2.0` is broken.

**Comment by sirreal** [comment]
Tests are passing, this seems to be working and would remove a blocker for the Node v12 upgrade.

**Comment by gwwar** [comment]
Dist artifacts in https://circleci.com/gh/Automattic/wp-calypso/474712#artifacts/containers/0 look okay at a glance. I'll take a quick spin on the sandbox.

**Comment by sirreal** [comment]
Thanks for help testing! 🙇

**Pull request merged**
