### PR TITLE
StickyPanel: refactoring, improvements, janitorial

### PR DESCRIPTION
**Pull request by retrofox**
-------
Issues: #12045

--------

sticky-panel

### CODE REVIEW

**Comment by iamtakashi** [comment]
Nice! No more jump! But I can see a gap between the sticky panel and the master bar.

**Comment by iamtakashi** [comment]
Just noticed the gap could be an expected behaviour for medium size screen. This is also happening Themes.

image

**Comment by lancewillett** [comment]
Does this need more testing or review?

**Comment by retrofox** [comment]
@lancewillett I'll update/test tomorrow and also asking for a new review. AFAIK this patch is pretty close to merged.

**Comment by alisterscott** [comment]
Closing as this PR is stale - please reopen if necessary

**Pull request closed without merging**
