### PR TITLE
Inline Help: clean up Tracks events payloads

### PR DESCRIPTION
**Pull request by lsinger**
This PR updates the Tracks events' payloads in Inline Help to use snake_case to conform with the Tracks naming conventions. 

To test:
- Use Inline Help (open / close, search, follow a search result); monitor the Tracks events that get sent and their properties to see whether they match naming conventions now.

### CODE REVIEW

**Comment by nylen** [comment]
Do we lose old data values by making this change (not really lost, but effectively they won't be seen/queried if we change the name)?  Does that matter?

**Comment by lsinger** [comment]
@nylen we're not changing the name of the events, and the payload we're not using yet (because it doesn't follow the naming conventions it might even be rejected — not super sure about that). In any case — we've been sending these events for about a week now and this fixes what could be said is a bug in them. We'll throw the old data away, basically.

**Comment by nylen** [comment]
Okay.  Last question:  I think `currentUrl: window.location.href` was removed because it can be obtained another way, based on data that is always sent to Tracks normally?

**Comment by lsinger** [comment]
@nylen that's right — Tracks includes it as part of the default payload as `_dl`.

**Pull request merged**
