### PR TITLE
Step 1 - Remove Block Patterns Registration from ETK - Remove require_once code

### PR DESCRIPTION
**Pull request by miksansegundo**
Related to https://github.com/Automattic/wp-calypso/pull/84256

## Proposed Changes

* Remove `require_once` code leaving the files

This PR is step 1, and https://github.com/Automattic/wp-calypso/pull/84256 is step 2.

When testing https://github.com/Automattic/wp-calypso/pull/84256 in my sandbox (running `install-plugin.sh editing-toolkit update/remove-block-patterns`), I got the following message:

```
** WARNING **
It is not safe to deploy the removal of a file (block-patterns/class-block-patterns-from-api.php) along with the removal of the require_once() for this file.
Please undo the file removal and deploying it separately. Alternatively, you can create a new diff to remove the require_once() function and deploy that first.

                        require_once __DIR__ . '/block-patterns/class-block-patterns-from-api.php';
``` 

**Note: This PR can only be merged after https://github.com/Automattic/jetpack/pull/34162 is released.**

## Testing Instructions

* Sandbox the public API
* Apply the code in your sandbox by running `install-plugin.sh editing-toolkit update/remove-block-patterns-require`
* Verify that when you access a simple site you don't see the pattern category "Intro" in the editor pattern inserter

## Pre-merge Checklist

- [x] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [x] https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md for your changes?
- [x] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [x] Have you checked for TypeScript, React or other console errors?
- [x] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [x] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [x] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

**Review by okmttdhr — APPROVED** [review]
Thank you for your good catch ✨

**Comment by fushar** [comment]
> Note: This PR must be merged hours after https://github.com/Automattic/jetpack/pull/34162 is released.

As a reviewer which didn't take part in the original hackday, I don't quite understand this. What happens when the above Jetpack PR is released but this has not been merged yet? Will something break? Could you clarify what "hours" means here 😄

**Comment by miksansegundo** [comment]
@fushar that note only means that because this PR removes the code that registers Dotcom patterns, it can only be merged after https://github.com/Automattic/jetpack/pull/34162 is released because we have migrated the code there.

**Comment by fushar** [comment]
@miksansegundo Ah sorry, I mean I was specifically referring to the "hours" part. After the Jetpack PR release, there will be a little time window where this PR is still not deployed. We will be registering the patterns twice then (?), will that be a problem?

**Comment by fushar** [comment]
I just saw https://github.com/Automattic/jetpack/pull/34162#pullrequestreview-1747394116:

> Test 2.2 - Apply this PR and deactivating the ETK plugin to verify that Dotcom patterns are registered from jetpack-mu-wpcom
> Test 2.3 - Apply this PR and deleting the ETK plugin to verify that Dotcom patterns are registered from jetpack-mu-wpcom

Answered my own question, all is good 😄

**Comment by okmttdhr** [comment]
>Note: This PR can only be merged after https://github.com/Automattic/jetpack/pull/34162 is released.

I believe this has been shipped already, as I confirmed Patterns are loaded on an Atomic site without ETK 🙂 Could you double-check? (not urgent at all!) @miksansegundo

**Comment by miksansegundo** [comment]
I think we still have to wait a bit more because after disabling the ETK on my atomic sire, I can only see core patterns (73), and when I activate the release candidate 2.0.4 I see all Dotcom patterns (382).

|Current Jetpack|Release Candidate Version 2.0.4|
|--|--|
|73 Patterns|382 Patterns|
|Screenshot 2566-12-07 at 19 40 25|Screenshot 2566-12-07 at 19 45 24|

**Comment by okmttdhr** [comment]
Sorry, my bad… Thanks for checking!

**Comment by miksansegundo** [comment]
> I believe this has been shipped already, as I confirmed Patterns are loaded on an Atomic site without ETK 🙂 Could you double-check?

@okmttdhr you were right!

My test failed because I tested on a site that had this config `define( 'JETPACK_MU_WPCOM_LOAD_VIA_BETA_PLUGIN', true );` 🙈

I tested again without that and it worked fine on Atomic with the ETK plugin deactivated:

Screenshot 2566-12-22 at 19 10 32

**Pull request merged**
