### PR TITLE
chore: Delete rule `wpcalypso/import-docblock`

### PR DESCRIPTION
**Pull request by scinos**
#### Changes proposed in this Pull Request

* Deletes the rule `wpcalypso/import-docblock`. This rule has been superseded by #54448
* Deletes script used to migrate to `import/order`

#### Testing instructions

N/A

### CODE REVIEW

**Comment by jsnajdr** [comment]
There are projects that continue to use the `import/docblock` rule, like Jetpack, and it should still be available in the `eslint-plugin-wpcalypso` package. Let's only remove all references in the Calypso project itself, and remove it from the recommended/default config.

**Comment by scinos** [comment]
> There are projects that continue to use the import/docblock rule, like Jetpack, and it should still be available in the eslint-plugin-wpcalypso package. Let's only remove all references in the Calypso project itself, and remove it from the recommended/default config.

I'd say those projects should migrate to the most advanced rule `@wordpress/dependency-group`.

Edit: I changed CHANGELOG to add a recommendation to migrate to `@wordpress/dependency-group`

**Review by jsnajdr — APPROVED** [review]
> I'd say those projects should migrate to the most advanced rule `@wordpress/dependency-group`.

OK, that should be an easy migration to do. Thanks for adding the changelog entry :+1:

**Comment by scinos** [comment]
I tried to update Jetpack to use `@wordpress/dependency-group` and it won't be a drop-in replacement.

For example, imports from `@wordpress/*` are under `External dependencies` when using Calypso's `wpcalypso/import-docblock`, but they should be under `WordPress dependencies` when using `@wordpress/dependency-group`. Another example is that `wpcalypso/import-docblock` ignores CJS modules, but `@wordpress/dependency-group` doesn't.

Overall, changing this rule will make Jetpack go from `1303 problems (9 errors, 1294 warnings)` to `1813 problems (519 errors, 1294 warnings)`. ESLint claims all those new errors are auto-fixable, but I haven't tested it.

That being said, I still deleting this rule is the right move. It feel wrong to have a rule in `eslint-plugin-calypso` that Calypso doesn't use, that has known bugs (see p4TIVU-9Hd-p2) and limitations (like ignoring CJS modules), and when `@wordpress/dependency-group` is more suited to maintain the Wordpress code style.

Pinging @Automattic/jetpack-crew. I'm happy to assist with the migration to `@wordpress/dependency-group` or even `import/order` (if you want to follow Calypso style)

**Comment by anomiex** [comment]
> Pinging @Automattic/jetpack-crew. I'm happy to assist with the migration to `@wordpress/dependency-group` or even `import/order` (if you want to follow Calypso style)

Any help is appreciated. I'm happy to review a giant PR that fixes all the ordering everywhere all at once.

I don't have much of an opinion on `@wordpress/dependency-group` versus `import/order`. The latter seems a bit cleaner to me based on the descriptions in p4TIVU-9Hd-p2, but I'm not one who frequently works on the JS.

**Comment by kraftbj** [comment]
On the Jetpack side, we have eslint-required. We should run the update against that only first IMO.

**Pull request merged**
