### PR TITLE
ci(e2e): Flatten `describe` blocks

### PR DESCRIPTION
**Pull request by scinos**
#### Background

In #52914 we split files containing multiple `@parallel` blocks. In #52658 we moved from `mocha-steps` to use `--bail` instead.

Those two changes made many `describe` blocks redundant (eg: a single `describe` block nested inside another `describe` block)

#### Changes proposed in this Pull Request

* Flatten the hierarchy of `describe` blocks.

I recommend to review this PR with white-space disabled.

#### Testing instructions

* Verify e2e tests pass
* Verify the number of tests is the same as `trunk`.

### CODE REVIEW

**Review by worldomonation — APPROVED** [review]
I see no issues with this.

I will put up a PR that will toggle the `max-top-level-describe` rule to an error to be merged after this PR.

**Comment by WunderBart** [comment]
@scinos @worldomonation what do you think about using the `__` in the filenames to indicate sub-suites? IMO it makes it a bit easier to follow:

- `wp-plan-purchase-comparing-spec.js` -> `wp-plan-purchase__comparing-spec.js`
- `wp-plan-purchase-renew-spec.js` -> `wp-plan-purchase__renew-spec.js `
- `wp-plan-purchase-upgrade-spec.js` -> `wp-plan-purchase__upgrade-spec.js `
- `wp-plan-purchase-viewing-spec.js` -> `wp-plan-purchase__viewing-spec.js `
- etc.

It's similar to how fixtures are named in GB: https://github.com/WordPress/gutenberg/tree/trunk/packages/e2e-tests/fixtures/blocks

**Comment by worldomonation** [comment]
> what do you think about using the __ in the filenames to indicate sub-suites?

@WunderBart I admit I have not seen this convention before. In tests I've worked with in the past, they usually used the same notation throughout the file name (ie. like currently).

With that said, I think it's worth trying out what you suggest.

**Comment by scinos** [comment]
File names updated.

Eventually I'd like to get rid of the `-spec` prefix (I need to review the `magellan-*.json` files to delete those that are not needed and make sure everything is referenced by path, and not by `**/*-spec.js`)

**Pull request merged**
