### PR TITLE
Guided onboarding: align intents with existing intent system and skip goals in site-setup

### PR DESCRIPTION
**Pull request by alshakero**
Fixes: 7381-gh-Automattic/dotcom-forge

~~Requires: D151653-code~~ Landed.

## Proposed Changes

This creates a new Stepper variant flow of `site-setup` called `site-setup-wg` that doesn't have the goals step, then redirects the users who went through Guided onboarding and declared their goals already towards it. 

## Why are these changes being made?
It doesn't make sense to re-ask people about their goals.

## Testing Instructions

1. Go to /start/guided.
3. Answer the survey and finish the flow.
4. You should land at `site-setup-wg` flow.
5. Finish the flow and take note of the site.
6. All should work.

#### Verify intent and goals are set
1. Go to https://YOUR_NEW_SITE/wp-admin/options.php
2. Verify the intent and goals are set.

### CODE REVIEW

**Comment by escapemanuele** [comment]
Thanks @alshakero!

Do you believe we should get rid of the 'intent' step as well?

image

**Comment by wongasy** [comment]
>but after that we're seeing the intent step.
Should we skip this too?
@escapemanuele Sorry I missed the ping! Yes, it makes sense to skip that screen as well. Since they repeat what we asked earlier in the segmentation questions.

**Comment by escapemanuele** [comment]
Thank you @wongasy, Omar is already working on making the site-setup flow use the intent from our new survey ✌️

**Review by agrullon95 — APPROVED** [review]
Tests well. Lets merge and iterate on the `site-setup-wg-flow` for any additional changes.

**Pull request merged**
