### PR TITLE
Comment: fix path for single comment page views

### PR DESCRIPTION
**Pull request by vindl**
While inspecting some of the other page view issues I noticed a minor issue with the way we are recording single comment page views. This PR adds the `:comment_id` variable to the existing `/comment/:site` path.

1. Set `localStorage.setItem( 'debug', 'calypso:analytics:tracks' )` in the browser console to enable the debug.
2. Navigate to `/comments/{site}` and open some comment in detail view.
3. Verify that `/comment/:site/:comment_id` page view is recorded.

### CODE REVIEW

**Comment by vindl** [comment]
> Is there a specific reason to go with :comment_id instead?

Nope, I just wasn't aware of the existing convention. :)

**Comment by Copons** [comment]
@vindl Just as a reminder: we might need to also update `/comments/:status/*` into `/comments/${ status }/*`.
Feel free to update this PR, since it would probably only add 1 LOC 🙂

**Comment by Copons** [comment]
LGTM feel free to :shipit: whenever CircleCI comes full circle!

**Comment by vindl** [comment]
> Just as a reminder: we might need to also update /comments/:status/* into /comments/${ status }/*.

Updated in cbbb4356463ab4f9ba60eada14f040d3d0c6b9dd.

**Comment by lsinger** [comment]
I reverted a PR using the GitHub UI. It listed two unrelated commits as well, this one among them. When I inspected those, they were empty. Seemed like an ignorable glitch.

**Pull request merged**
