### PR TITLE
Use babel class-properties transformation to easily bind methods

### PR DESCRIPTION
**Pull request by brunoscopelliti**
Hi there,

I was going around through the repo, to gather information for another pull request on which I'm working, and I noticed the way this component is binding its methods.

We're already using babel's class-properties transformation in other places; the code should be easier to read now.

What do you think?

cc. @bluefuton

### CODE REVIEW

**Comment by blowery** [comment]
Thanks for the PR! LGTM.

**Comment by blowery** [comment]
I'll merge this tomorrow, unless someone else beats me to it.

**Comment by bluefuton** [comment]
Thanks for the contribution @brunoscopelliti! 🚢 now.

**Comment by brunoscopelliti** [comment]
Hi guys,

I think I made an error with this PR.
I should have checked better what the class-properties transformation does under the hood.
I am sorry.

I didn't realize class-properties initializers are not defined on the prototype of the class. 
From babel's [docs](https://github.com/babel/babel/tree/master/packages/babel-plugin-transform-class-properties):

```js
  class Bork {
    boundFunction = () => {
    }
  }

  console.log(myBork.prototype.boundFunction);
  // > undefined
```

That is transpiled to [REPL](https://babeljs.io/repl/#?babili=false&evaluate=true&lineWrap=false&presets=stage-0&code=%20%20class%20Bork%20%7B%0A%20%20%20%20boundFunction%20%3D%20()%20%3D%3E%20%7B%0A%20%20%20%20%7D%0A%20%20%7D%0A%0A%20%20console.log(myBork.prototype.boundFunction)%3B).

This makes things harder when it comes to unit testing, because we lose the ability to spy/stub methods on the prototype... and spying/stubbing the instance method does not work.
For example:

```js
  it( 'should call myMethod when it is clicked', function() {
    const component = shallow( <MyComponent /> );
    const myMethodSpy = sinon.spy( component.instance(), 'myMethod' );

    component.simulate( 'click' );

    // myMethod is executed, but ...
    sinon.assert.calledOnce( myMethodSpy ); // throws!
  } );
```

**Comment by blowery** [comment]
@brunoscopelliti no worries, I don't think this broke any existing tests. 

if you come up with a way to mock out the click handler, do let us know. :)

**Comment by blowery** [comment]
As an alternative, you could mock out whatever the click handler calls instead of mocking the click handler itself...

**Comment by brunoscopelliti** [comment]
Ok, I'll try to investigate further how enzyme works under the hood.
I am not particularly optimist there's way around this... but at least I'll learn something :)

>you could mock out whatever the click handler calls instead of mocking the click handler itself...

Thanks for the advice!

**Comment by brunoscopelliti** [comment]
If anyone else is interested, I've just made a [sandbox repo](https://github.com/brunoscopelliti/enzyme-sandbox), that permits to easily debug a component unit test in the browser.

**Comment by brunoscopelliti** [comment]
Hey @blowery 
I've found that someone else had the same issue before, airbnb/enzyme#586.
It seems that in order to have the spy fired, we've to execute a `forceUpdate`.

```js
  it( 'should call myMethod when it is clicked', function() {
    const component = shallow( <MyComponent /> );
    const instance = component.instance();
    const myMethodSpy = sinon.spy( instance, 'myMethod' );

    // this makes the tricks
    instance.forceUpdate();
    
    component.simulate( 'click' );
    sinon.assert.calledOnce( myMethodSpy ); // it works now!
  } );
```

However this seems a little hack-ish to me :)
I've also found another thread airbnb/enzyme#697, in which Jordan Harband recommends to [spy methods defined on the prototype](https://github.com/airbnb/enzyme/issues/697#issuecomment-261659043).

**Pull request merged**
