### PR TITLE
Simple Payments: confirm simple-payment button delete action

### PR DESCRIPTION
**Pull request by donpark**
Guards against unintentional deletion of simple-payments button with a simple delete dialog.

Test Plan:

1. Open Simple Payments Button List with at least one Payment Button.
2. Open a List Item's action popup and Select Trash action.

> screenshot_303

3. Confirmation dialog asking "Are you sure you want to permanently delete this payment button?" should be displayed.

> screenshot_305

4. Check that clicking Cancel leaves the button as-is.
5. Check that clicking Delete removes the button.

### CODE REVIEW

**Comment by lamosty** [comment]
I'm not sure it's the best to use the browser's native alert/confirmation dialog. /cc @iamtakashi for design thoughts.

**Comment by iamtakashi** [comment]
Please use the Calypso dialog like what we see when you try deleting an image from the media library modal (not the section).

screen shot 2017-08-09 at 15 06 26

In terms of the copy, is this the behaviour that we all agreed?

**Comment by donpark** [comment]
Yeah. Went with `confirm` initially due to lack of info Calypso's built-in confirmation UI facility and nested dialog unknowns. Will revisit.

> In terms of the copy, is this the behaviour that we all agreed?

Don't know. It was on TODO so I assumed it was. Maybe we need  a TODISCUSS pile.

**Comment by donpark** [comment]
What got left out of the merge:

1. Button text is OK instead of Delete.
2. `is-scary` is not used.

Another PR will address these shortcomings.

**Comment by iamtakashi** [comment]
@donpark I'm still not getting a clear definite answer what would happen if one delete a button, so please keep the copy the minimum for now.

> Are you sure you want to permanently delete this item?

**Comment by donpark** [comment]
@iamtakashi OK. I'll ping you when I start addressing the parts I missed. thx

**Pull request merged**
