### PR TITLE
Plugins: Don't show empty info card for custom plugins

### PR DESCRIPTION
**Pull request by seear**
Removes an empty 'information' card for plugins that are not in the .org repo. This is in preparation for showing some actual information in that position for uploaded plugins.

**Before**

screen shot 2017-07-25 at 20 52 22

**After**

screen shot 2017-07-25 at 20 51 11

Note that this PR removes a blanket css rule that zeroed margins for any card in plugin meta. This has some knock on effects, of which it is hard to unpick whether they were intentional to start with or not:

**Before**
screen shot 2017-07-26 at 12 40 15

**After**
screen shot 2017-07-26 at 12 39 56

**Before**
screen shot 2017-07-26 at 12 47 04

**After**
screen shot 2017-07-26 at 12 46 44

The after shots with the default card margins look at least as good as before in my opinion, but I would welcome some design input here, and I may have missed some cases.

**To Test**
* Check out this branch or use the calpyso.live link
* Go to plugins, pick a plugin, compare the displayed plugin page with master
* In particular, try with a custom plugin not available on .org, for example:
[mellow-brolly.zip](https://github.com/Automattic/wp-calypso/files/1176481/mellow-brolly.zip)
(You can upload this by going to /plugins/upload/{jetpack_site} in dev, or using wp-admin)

### CODE REVIEW

**Comment by folletto** [comment]
> The after shots with the default card margins look at least as good as before in my opinion, but I would welcome some design input here, and I may have missed some cases.

My take is that the after versions follow more closely Calypso design patterns, and as such get my 👍 

I'd even add that the first one (with just ← back and the plugin card) should have a padding between the header cake and the card.

There might be a reason however for that, so maybe the original designer(s) might have a different take here.

**Comment by donnapep** [comment]
There's another use case here for Calypso extensions. This is what I'm seeing in the live branch:

wpsc-after

This is what it looked like before on `wpcalypso`:

wpsc-before

**Comment by seear** [comment]
> There's another use case here for Calypso extensions...

Thank you @donnapep, I'll fix this so it stays as before.

**Comment by seear** [comment]
@donnapep seem ok to you now after ead5c5f?

**Pull request merged**
