### PR TITLE
Build: Remove quasi-dependency on semver package

### PR DESCRIPTION
**Pull request by nylen**
This code (the `make node-version` step that verifies the Node.js version) has been discussed a few times recently, for example https://github.com/Automattic/wp-calypso/pull/2124#discussion_r54125894 and #3877.

This PR intends to supersede #3877 by removing the makefile hacks around semver and adding a fairly simple version comparison routine in the script where it needs to be, along with some tests.

One of the goals of this check is to run very quickly before `npm install`, since installing all of our dependencies takes a while and we want to be able to give an early warning if installing all of that stuff would be a waste of time.  This is the reason for not adding semver to `devDependencies`.

We also discussed running `npm install semver` before the check-version script, but we were concerned that doing this additional install on the side would cause issues with the shrinkwrapping process.

Note that the `check-node-version` script cannot use babel features like ES6 imports, so it seemed wise to impose the same constraint on the test suite for the version compare code.

cc @TooTallNate @blowery @aduth @Pomax

### CODE REVIEW

**Comment by TooTallNate** [comment]
Probably better than the Makefile hack :+1:

Though, I think having `semver` in the package.json file, and then relying on the `node_modules/semver` rule for the `check-node-version` check would eliminate the need for the additional tests, and extra Makefile, etc.

**Comment by nylen** [comment]
Yeah, that would be a way to further cut down on complexity, perhaps at the cost of a bit of speed, maybe it is worth it though because this is still a bit ugly.

**Comment by TooTallNate** [comment]
It shouldn't take _too_ much extra time since the `node_modules/semver` rule should only install that single module, as opposed to a regular `npm install` installing everything.

**Comment by Pomax** [comment]
Curious: why pass over [the solution I filed a PR for](https://github.com/Automattic/wp-calypso/pull/3635) about two weeks ago now? It turns most of the task that *can* be easily run as npm scripts, into npm scripts, including the pre-install semver check.

**Comment by nylen** [comment]
@Pomax I left some comments on that PR.  Others may disagree, all I can do is give my opinion.

Closing this, @TooTallNate I went with your suggestions in #4002 instead.  Looks much cleaner (and the shrinkwrapping process went fine, I just had to learn how to do it first :smile:)

**Pull request closed without merging**
