### PR TITLE
Adding support for Discover's fullbleed class.

### PR DESCRIPTION
**Pull request by kjellr**
When Discover editors apply a `fullbleed` class to images on discover.wordpress.com, we extend the images outside the boundaries of the text column. We’d like to bring this behavior to the Reader as well. 

Extends the width by 175px in each direction, aligning with the Discover sidenotes from PR #2729. Larger viewports only: no change to screens under 1132px.

Examples:
Article: https://discover.wordpress.com/2015/12/28/rob-turpin-interview/
Reader: http://calypso.localhost:3000/read/post/id/53424024/1661
example1

 
Article: https://discover.wordpress.com/2016/01/21/fennabee/
Reader: http://calypso.localhost:3000/read/post/id/53424024/9037
example2

### CODE REVIEW

**Comment by kjellr** [comment]
@bluefuton It looks like we cap the size of images at 1440px wide ( `?w=1440&quality=80&strip=info` ) inside the full-post views: any chance we could bump that up to 2164px for Discover images/captions with a `fullbleed` class? That'd keep these ones nicely retinafied. :)

**Comment by blowery** [comment]
@kjellr we can probably do that. nice work!

**Comment by blowery** [comment]
There we go, that should do it. https://github.com/Automattic/wp-calypso/commit/37052c352f97bf5adc322f8c571479cdaa291a88

**Comment by kjellr** [comment]
Awesome, thanks @blowery! Tested it out on a couple additional posts and it looks great!

**Pull request merged**
