### PR TITLE
Remove unused WpcomFAQ component

### PR DESCRIPTION
**Pull request by aneeshd16**
Related to https://github.com/Automattic/wp-calypso/pull/78262#issuecomment-1593092943

## Proposed Changes

* Removes the WpcomFAQ component as it is not reachable by any code path anymore.

## Testing Instructions

* Do a code search and confirm that this is indeed dead code. 
* Although E2E tests should take care of this, spot check a few flows: `/start`, `/plans/<site slug>`, `/setup/newsletter/plans`.

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

**Comment by klimeryk** [comment]
Thanks for confirming that it's not used, @aneeshd16! I can adjust my changes in #78262 to remove the FAQ component. Especially since, there's much more code to be removed than what is proposed in this PR. The whole `showFAQ` prop can be removed. If `showFAQ` is indeed always false, than the whole `mayRenderFAQ` should be removed.

**Comment by klimeryk** [comment]
I've updated https://github.com/Automattic/wp-calypso/pull/78262 to remove this code and clean up other related parts. I'd love a review, if you could today 🙏

**Comment by aneeshd16** [comment]
You're right! I got side-tracked by this [line](https://github.com/Automattic/wp-calypso/blob/347076414b15a54e6797e78c2e2eea6b1ef5a583/client/signup/steps/plans/index.jsx#L155), so I thought it might be in use somewhere. But as you pointed out, this prop is [overridden](https://github.com/Automattic/wp-calypso/blob/19cb5620bf00a53430f88c0a701d873a0b08b6b4/client/my-sites/plans-features-main/index.jsx#L602) in the same component where it is used, and there is no possibility of `mayRenderFAQ` returning anything other than void. All of that can be safely removed. 

Since https://github.com/Automattic/wp-calypso/pull/78262 takes care of this refactor, I am closing this PR.

**Comment by aneeshd16** [comment]
> I've updated https://github.com/Automattic/wp-calypso/pull/78262 to remove this code and clean up other related parts. I'd love a review, if you could today 🙏

@klimeryk, I'm out of time, and I won't be able to review this today. 🙂  I have tagged my team for review, and if nobody gets to it, I'll have a look at it tomorrow. If it's urgent, please ping us in our team channel, and someone would be able to help soon!

**Pull request closed without merging**
