### PR TITLE
Purchases: Extract CreditCardPage component

### PR DESCRIPTION
**Pull request by gziolo**
This PR extracts a new `<CreditCardPage />` component to make smoother code reuse for new feature for Connect for WooCommerce. Check #6971 for more details.

As part of this refactoring all Eslint warning were removed.
I also got rid of `isMounted` deprecated React method call. See https://facebook.github.io/react/blog/2015/12/16/ismounted-antipattern.html and https://github.com/facebook/react/issues/3417 for more details.

I recommend checking individual commits when reviewing code. I mostly moved code around, which created quite a big diff. That's why I wanted to have this PR reviewed before I continue with more aggressive refactorings.

### Testing.
1. Go to Manage Purchases page (http://calypso.localhost:3000/purchases).
2. Select a purchase paid with credit card.
3. Click on Edit Payment Method link.
4. You should see loading placeholder when page is loading (you can refresh a page if you missed loading step).
5. When page is loaded you should see a form with a cardholder name provided.
6. Play with the form to make sure it works as before.
7. You can also try to click back button while validation is pending to make sure `isMounted` change is working properly. There should be no warnings on JS console complaining about incorrect`setState` usage.
8. Go back to Manage Purchases page.
9. Pick a purchase paid with credits.
10. Click on Add Payment Method link.
11. You should see loading placeholder when page is loading (you can refresh a page if you missed loading step).
12. When page is loaded you should see a form with no fields filled in.
13. Play with the form to make sure it works as before.

Test live: https://calypso.live/?branch=update/manage-credit-card

### CODE REVIEW

**Comment by stephanethomas** [comment]
The code looks good. However when I start the server I get the following error:

```
{
  "formatted": "Error: File to import not found or unreadable: me/purchases/components/credit-card-form/style\n       Parent style sheet: /var/sources/assets/stylesheets/_components.scss\n        on line 182 of assets/stylesheets/_components.scss\n>> @import 'me/purchases/components/credit-card-form/style';\n   ^\n",
  "message": "File to import not found or unreadable: me/purchases/components/credit-card-form/style\nParent style sheet: /var/sources/assets/stylesheets/_components.scss",
  "column": 1,
  "line": 182,
  "file": "/var/sources/assets/stylesheets/_components.scss",
  "status": 1
}
```

I bet it's because the credit card form was moved in the wrong directory :).

**Comment by gziolo** [comment]
I already fixed that, thanks for looking at this PR @stephanethomas  👍

**Comment by stephanethomas** [comment]
I've tested it and it works fine. This is good to go!

**Pull request merged**
