### PR TITLE
Modularise login state

### PR DESCRIPTION
**Pull request by sgomes**
This PR is one of many working on modularising state in Calypso. This one handles login.

For mode details on state modularisation, see #39261 and p4TIVU-9lM-p2.

After this PR, the `login` reducer should no longer be loaded as part of the critical path on most routes, as it moves away from the `entry-main` chunk. It's a small saving (~ 1.5KB compressed), but the goal of state modularisation is to produce cumulative effects over many PRs.

#### Changes proposed in this Pull Request

* Modularise login state
* Split login actions into individual modules
* Rework dependencies between login actions and login-related `http-data` modules

#### Testing instructions

* Install [Redux DevTools](https://chrome.google.com/webstore/detail/redux-devtools/lmhkpmbekcpmknklioeibfkpmmfibljd?hl=en).
* Open DevTools and switch to the Redux tab.
* Open `/read` with a full page refresh.
* Click `State` on the top right of the Redux tab in DevTools to ensure you see all state, and not just the diff for the last action: 
image
* Analyse the tree and note that there's no `login` key, even if you expand the list of keys. This indicates that the login state hasn't been loaded yet.
* Click the user avatar on the masterbar, followed by `Security` on the sidebar.
* Verify that a `login` key is added with the login state. This indicates that the login state has now been loaded.
* Verify that login works normally, including 2FA functionality. This indicates that I didn't mess up.

### CODE REVIEW

**Comment by sgomes** [comment]
Moving status to "In Progress" while I investigate a bug.

**Comment by sgomes** [comment]
Unclear if this is a bug, or simply the functionality not working correctly outside of production due to security concerns.

**Comment by sgomes** [comment]
I could find no evidence of a bug, but I was unable to test the Security tab in `/me` correctly outside of production. Setting to `Needs Review` and hoping someone will know how to test this.

**Comment by griffbrad** [comment]
@sgomes have you had any luck testing the Security tab locally with the proxy setup we discussed?

**Comment by sgomes** [comment]
> @sgomes have you had any luck testing the Security tab locally with the proxy setup we discussed?

I'm afraid I haven't had an opportunity yet.

**Comment by sgomes** [comment]
@griffbrad I'm going to opt out of trying the proxy setup you mentioned, as I can bring myself to modify root certificates in my local machine, even if for just a bit 😬 

Would it be OK to test this portion of the functionality in staging, after temporarily pausing the deploy queue? I've reviewed all I could, and I don't anticipate any problems with the "Security" section, considering how previous state modularisation PRs always went smoothly in client-side functionality.

**Review by lynnbgriffith — APPROVED** [review]
👍🏻 That seems like a reasonable approach to me.  Feel free to ping me if you need to get quick eyes on a revert.

**Comment by sgomes** [comment]
Thank you, @griffbrad! 👍 I'll leave this for a safer time on Monday, then.

**Comment by sgomes** [comment]
Everything seems to be working correctly after testing in staging 👍

**Pull request merged**
