### PR TITLE
need to add these configs or else we get errors in the environments

### PR DESCRIPTION
**Pull request by rralian**
/cc @aduth @gwwar @retrofox

### CODE REVIEW

**Comment by aduth** [comment]
Will the presence of these configuration values cause the feature to become enabled in non-development environments?

**Comment by rralian** [comment]
no... the feature is determined by `"sync-handler": true`

**Comment by aduth** [comment]
Confirm loads locally under `CALYPSO_ENV=stage make run` :+1:

**Comment by gwwar** [comment]
@rralian What about the config/desktop-mac-app-store.json?

**Comment by rralian** [comment]
yep, you're right... I missed that one.

**Pull request merged**
