### PR TITLE
Checkout: Centralize logic that determines which contact form to use

### PR DESCRIPTION
**Pull request by sirbrillig**
#### Changes proposed in this Pull Request

This converts the `WPContactForm` and its dependent components into TypeScript, and fixes some bugs along the way.

Notably, the use of booleans to determine if we should display the domains contact form, the G Suite contact form, or the tax contact form has caused numerous bugs. This PR creates a single function, `getContactDetailsType` which will examine the current cart and return a string that identifies which contact details form should be displayed. This centralizes the logic and makes it easier to prevent edge cases where the wrong form is displayed.

The intentional behavior changes caused by this are highlighted in the testing instructions below.

Domain contact form:

Screen Shot 2020-11-04 at 6 23 36 PM

Taxes contact form:

Screen Shot 2020-11-04 at 6 26 19 PM

G Suite contact form:

Screen Shot 2020-11-04 at 6 31 15 PM

Fixes https://github.com/Automattic/wp-calypso/issues/45301 
Fixes https://github.com/Automattic/wp-calypso/issues/45786

#### Testing instructions

1. Visit checkout with just a plan in the cart. Verify that you see the tax contact form (just postal code and country).
1. Visit checkout with just a plan in the cart and enough credits to fully cover the purchase. Verify that you see no contact form. **This is new behavior**
1. Visit checkout with just a plan in the cart and a 100% discount coupon. Verify that you see no contact form.
1. Visit checkout with a domain registration and a plan in the cart. Verify that you see the domain contact form (name, address, etc.)
1. Visit checkout with a domain registration and a plan in the cart and enough credits to fully cover the purchase. Verify that you see the domain contact form (name, address, etc.)
1. Visit checkout with a domain registration and a plan in the cart and a 100% discount coupon. Verify that you see the domain contact form (name, address, etc.)
1. Visit checkout with just a domain transfer in the cart. Verify that you see the domain contact form (name, address, etc.)
1. Visit checkout with just a domain mapping in the cart. Verify that you see the domain contact form (name, address, etc.)
1. Visit checkout with a domain registration and a new G Suite subscription in the cart. Verify that you see the domain contact form (name, address, etc.)
1. Visit checkout with just a new G Suite subscription in the cart. Verify that you see the G Suite contact form (name, alternate email address, postal code and country).
1. Visit checkout with extra G Suite licenses in the cart. Verify that you see the tax contact form (just postal code and country). **This is new behavior**

### CODE REVIEW

**Comment by stephanethomas** [comment]
Thanks for working on this Payton! I had a quick look to the code, and didn't notice anything suspicious. I've tested use cases #9 and #10 (for G Suite) with great success. However, I couldn't see the tax contact form in use case #11:

Production | Pull Request
------ | -----
before | after

Maybe that's because I was using credits?

**Comment by stephanethomas** [comment]
> Maybe that's because I was using credits?

Confirmed. I had another look to the code, and saw the logic in the `getContactDetailsType()` method. I then removed credits, and was able to get the form this time. Just note that the `Country` field doesn't have the same height than the other one:

screenshot

**Comment by klimeryk** [comment]
Tested for regressions from domains perspective - tried a few flows, including domain-only and ccTLDs. It's hard to cover all the possible cases, but seems that all is working without regressions 👍

> Visit checkout with just a domain mapping in the cart. Verify that you see the domain contact form (name, address, etc.)

This seems to be an error in the testing instructions - we should not (and we do not) collect contact information in this case.

------

While testing, I've also noticed an odd behaviour for the .fr TLD. We show some additional fields for this ccTLD and it seems that it's overly eager to re-validate the whole shopping cart. This seems to cause quite a lot of necessary API requests as well as make the whole experience slower for the user:

Screen Recording 2020-11-05 at 16 32 21 2020-11-05 16_33_40

I've confirmed this is happening on production as well, so it's definitely something to look into as a follow-up PR, not a blocker here.

**Comment by sirbrillig** [comment]
> Just note that the Country field doesn't have the same height than the other one:

Thanks! Interesting that I don't see that behavior. Maybe we have different browsers or different font-sizes. I created an issue for that here: https://github.com/Automattic/wp-calypso/issues/47158

> Visit checkout with just a domain mapping in the cart. ... This seems to be an error in the testing instructions - we should not (and we do not) collect contact information in this case.

Yes, you're correct. Thanks for noticing! 

> While testing, I've also noticed an odd behaviour for the .fr TLD. We show some additional fields for this ccTLD and it seems that it's overly eager to re-validate the whole shopping cart. This seems to cause quite a lot of necessary API requests as well as make the whole experience slower for the user:

I created an issue for this here: https://github.com/Automattic/wp-calypso/issues/47159 Thank you again!

**Pull request merged**
