### PR TITLE
Drafts Popover: Design refresh and adding to Editor

### PR DESCRIPTION
**Pull request by shaunandrews**
Reworking the design/layout of the drafts popover.

- ~The excerpt still transitions in, but no longer replaces the title.~ Scratch that, I've ditched the excerpt altogether. The original animation I had was more annoying than helpful, often causing me to accidentally click on the wrong draft as they changed sizes.
- Added the last modified date (TimeSince) to the list.
- I’ve lowered the number of drafts to show (We now show up to 5 drafts)
- Added a new header card with a label, and a button to add a new draft.
- I've removed the site title/blavatar.
- Featured images now appear on the right, avoiding the ragged left edge which previously made it hard to scan.
- Updated the footer (See All) button to always be visible, even if the list happens to scroll.
- Also rejiggered the way the scrollable list works.

screen shot 2017-12-19 at 4 11 19 pm

~This also adds a similar component for the drafts popover in the editor~ Scratch that — the drafts picker in the editor worked just fine, but exposes an existing issue with the Close button. I've removed the drafts picker for now, and once we fix the Close button we can bring it back.

--

For reference, here's how the popover looks today (not available within the editor):

screen shot 2017-12-19 at 4 16 01 pm

### CODE REVIEW

**Comment by shaunandrews** [comment]
This PR also explores adding the drafts button back in the editor. When you switch to the editor, you'll see the draft count animate into place. And it mostly works, even if it looks a bit kooky right now. However, there is a bug with the Close button still acting like a back button.

If you open the editor, then use the draft popover to switch to a different draft — then click the Close button. Instead of closing the editor, the URL is updated to your first post, but nothing changes. Super broken, and a blocker to this popover being in the editor. (I wonder, is this a new bug, or has it always been there?)

**Comment by shaunandrews** [comment]
screen shot 2017-12-08 at 12 46 06 pm

I forgot about multi-author sites.

**Comment by frontdevde** [comment]
Cool stuff! 👍

Minor thing regarding `draft/style.scss`: There's quite a bit of absolute positioning going on. This can easily lead to cross-browser rendering issues (we've faced this recently on revisions). I'd recommend using flexbox for the layout portion in favor of `position: absolute`. That also makes it easier to add robust responsive behavior or refactor.

**Comment by drw158** [comment]
The animations are really nice.

If I only have one word of text in the post content, there is an extra empty line:
screen shot 2017-12-12 at 1 32 50 pm

Maybe, after clicking an image, in should expand beyond the fixed width:
screen shot 2017-12-12 at 1 34 23 pm

Not sure what I think about the hover interaction. I think it should at least be faster. Maybe a click to expand solution would work better. I found myself waiting and hovering over post titles to see it expand, but after a couple seconds, I realized that there is no post content, so it's not going to expand.

**Comment by shaunandrews** [comment]
@drw158 — Thanks for the feedback. I've updated the PR to make the drafts picker much simpler overall.

**Comment by drw158** [comment]
The design is a big 👍 from me. I think the changes are excellent.

**Comment by alisterscott** [comment]
what's the difference between "New Draft" and just clicking "Write"? Isn't this duplicating the same thing?

**Comment by shaunandrews** [comment]
> what's the difference between "New Draft" and just clicking "Write"? Isn't this duplicating the same thing?

They do exactly the same thing, you're right. The original intention behind adding the "New Draft" button was for the editor's context — right now there's no way to start a new post from within the editor. And, my intentions here were originally to add this popover to the editor — and thats still going to happen, just not right now (there's a bug).

However, I found I really liked the "New Draft" button in all contexts. As @ianstewart said, "I feel like I wanna make more drafts now." It may feel repetitive, but I'd like to keep it for now and see what happens.

**Comment by lsinger** [comment]
LGTM. Let's ship this.

**Pull request merged**
