### PR TITLE
Menus: fix randomly closing item edit view

### PR DESCRIPTION
**Pull request by seear**
Observing `sites` in menus/main.jsx forces a re-render whenever `sites` changes.
When this happens, the edit-tracking `lock` object is created anew, causing any currently
open item edit box to close.

This change removes the use of the lock lib entirely, using state to track
the currently edited item.

**To Reproduce**
1) Go to https://wordpress.com/menus and select a site
2) Click on the edit icon of an existing menu item
screen shot 2015-12-03 at 12 44 43
3) The edit view will open for the item
4) Wait a while, and the edit view will close on its own

**To Test**
With this PR, all menus behaviour should be the same, except for the edit view closing on its own

### CODE REVIEW

**Comment by ehg** [comment]
The code LGTM, and I've tested moving/saving/adding/editing. All works. Perhaps we should loop @mcsf in to have a quick look?

**Comment by mcsf** [comment]
This looks good so far. Killing `Lock` feels good. :)

My only remark would be that we're using the term `editItem` in the incoming changes, while the thing actually stored is just the ID.

**Comment by seear** [comment]
> My only remark would be that we're using the term editItem in the incoming changes, while the thing actually stored is just the ID.

Yeah, good point. Fixed in d95056c

**Comment by lancewillett** [comment]
Thanks for fixing this! Was annoying me earlier this week and I came to report it to find a merged PR. Boom. :100:

**Pull request merged**
