### PR TITLE
[e2e] Add tests for launching a site

### LINKED ISSUE #40135: My Home: Add canary E2E test for launching a site
We should add a Canary test to verify that we can launch a new free site without purchasing a domain starting from My Home.

See PCYsg-o8X-p2 for quick start instructions if folks haven't added E2Es before. Or DM/comment for help.

### PR DESCRIPTION
**Pull request by razvanpapadopol**
#### Changes proposed in this Pull Request
* Add an e2e test to verify that we can launch a site for free starting from My Home.
* Add a test to verify that accounts with multiple sites can switch to a new site and launch it.
* Add `LaunchSiteFlow` to lib.
* Add `CreateSiteFlow` to lib.
* Add an extra step to existing canary signup test to cover launch flow.

#### Testing instructions
* New test should pass
* Canary signup test should pass

Fixes #40135

### CODE REVIEW

**Comment by Stojdza** [comment]
@razvanpapadopol, according to https://github.com/Automattic/wp-calypso/issues/40135, did you want to add some of the new tests to canaries?

**Comment by razvanpapadopol** [comment]
> @razvanpapadopol, according to #40135, did you want to add some of the new tests to canaries?

In my opinion this would be mostly redundant, covering a large part of the flow tested already by the signup tests. What do you think about adding [this step](https://github.com/Automattic/wp-calypso/pull/42513/files#diff-8377db5bd639fb90e16d31de8f350bb1R57-R59) to an existing canary signup test?

**Comment by Stojdza** [comment]
Full e2e suite is running two times every day. If you think it's enough for testing `launch` flow then I would skip adding it to canaries. If `launch` is important and prone to changes, then feel free to add it to signup canary.

**Comment by sirreal** [comment]
Running this against PRs (with needs review label) and on scheduled runs seems good for now. Adding and removing it from canaries is pretty trivial, right?

@gwwar any reason you wanted this specifically for canaries? https://github.com/Automattic/wp-calypso/issues/40135

**Comment by Stojdza** [comment]
> Adding and removing it from canaries is pretty trivial, right?

Yup. Just mark test with `@canary` tag. For example:

`describe( 'Launch a free site @canary', function ()`

**Comment by razvanpapadopol** [comment]
Yes, but that will add the whole test preparation and cleanup as well to canaries (create account, create site, delete account) so I suggested instead to just add a single step to the complete signup flow that we already have:
```
step( 'Can launch a site', async function () {
    return await new LaunchSiteFlow( driver ).launchFreeSite();
} );
```
here: https://github.com/Automattic/wp-calypso/blob/master/test/e2e/specs/wp-signup-spec.js#L488

**Comment by gwwar** [comment]
> @gwwar any reason you wanted this specifically for canaries? 

Because it broke before :D

**Comment by razvanpapadopol** [comment]
@Stojdza Added the extra step to canary signup in 1a1587c7f6043a65b2c0a5017becc987a05f26e1

Is there anything I can do about the remaining failing e2e tests? (Rebased and re-run tests a couple of times).

**Comment by Stojdza** [comment]
@razvanpapadopol I tried failed tests locally, against WP.com and live branch, and they passed. You're good to go 👍

**Review by Stojdza — APPROVED** [review]
🚀

**Pull request merged**
