### PR TITLE
Signup: replace `welcome/next/` with NUX Trampoline

### PR DESCRIPTION
**Pull request by michaeldcain**
In #1446, we tested the NUX Trampoline for non-purchasing new signups against the `welcome/next/` screen. After taking a look at internal metrics, we found the following:

- **Retention**: 1- and 2-week user retention increased 35.5% and 17% respectively with the NUX Trampoline.
- **Purchasing Conversions**: remained relatively unchanged.
- **Site Customization**: dropped 14.5% with the NUX Trampoline. Given the de-emphasis of site customization between the designs, this was expected.
- **Post/Page Publishing**: increased 3.3% with the NUX Trampoline.
- **Theme Switching**: remained relatively unchanged.

With those results, we'd like to replace the `welcome/next/` checkout destination in Signup with an experience that takes the non-purchasing new user to the front end of their website with the Trampoline active. The Trampoline only runs once per each new user and has already been activated for new users on dotcom.

### CODE REVIEW

**Comment by michaeldcain** [comment]
To test:

- Run through Signup as a new user
- Don't select any plans
- Signup should finish on the homepage of your new site, with the Trampoline showing

**Comment by kwight** [comment]
LGTM :+1: 

Tested the default flow with no upgrades, with a domain upgrade, and with a plan upgrade, all worked as expected.

**Comment by davemart-in** [comment]
> we'd like to replace the welcome/next/ checkout destination in Signup with an experience that takes the non-purchasing new user to the front end of their website with the Trampoline active

Woot! Nice work y'all!

**Pull request merged**
