### PR TITLE
Onboarding Checklist: Pull out all config flags & make changes needed to work in the Desktop env

### PR DESCRIPTION
**Pull request by jblz**
The top-level config flag wasn't enabled in horizon.  Remedying that in #34446, but this goes further to pull the flags out of all environments since it's enabled nearly everywhere anyway.

Interestingly, the `onboarding-checklist` flag is [currently disabled](https://github.com/Automattic/wp-calypso/blob/ad190268ff0c526773ee0b7c5d3a6805b861d6b3/config/test.json#L75) in the test environment.  I'm not sure if this is intentional and what issues it will cause to enable it there.

Enabling `onboarding-checklist/phase2` in the desktop app exposed an issue where the checklist page failed to load in the app. This PR also addresses this issue.

#### Changes proposed in this Pull Request

* rm the flags in config files
* rm the `config.isEnabled` checks
* work around checklist loading issue by ensuring response is unpacked from http envelope

#### Testing instructions

* Creating a new site on this branch lands the user on the checklist page, and the checklist works
* Once merged to master, creating a new site on `horizon` lands the user on the checklist page, and the checklist works
* Building wp-desktop with this branch, creating a new site lands the user on the checklist page, and the checklist works (see below)

#### Test this branch in wp-desktop

* Stop any running instances of calypso (to free the network port)
* Clone https://github.com/Automattic/wp-desktop/ & check out `develop`
* [Set up your secrets](https://github.com/Automattic/wp-desktop/blob/develop/docs/secrets.md)
* cd into the `calypso` subdirectory in the wp-desktop dir
* `git checkout remove/onboarding-checklist-flags` (this branch)
* cd back to the top level wp-desktop dir
  * `make dev-server`
* Once the above is ready, in another terminal, cd to the top level wp-desktop dir
  * `make dev`
* You should see calypso inside an electron wrapper

##### Test an existing site in the desktop app

* Open the dev tools (View|Developer Tools)
* Enter this in the console: `document.location = '/checklist/yourwpcomtestsiteslug';`
* You should see the checklist, items should be populated, items should be completable in the same manner on desktop as on the production web

##### Test a new site in the desktop app

* Switch site | Add new site
* Create a shiny new...
* Complete the flow
* You should see the checklist, items should be populated, items should be completable in the same manner on desktop as on the production web

Fix for Automattic/wp-desktop#641 -- once the submodule is bumped

### CODE REVIEW

**Comment by jblz** [comment]
@michaeldcain @fditrapani @ramonjd @adamziel -- Does anyone know any reason to not enable this in destkop, etc.?

**Comment by ramonjd** [comment]
> Does anyone know any reason to not enable this in destkop, etc.?

**Comment by fditrapani** [comment]
> Does anyone know any reason to not enable this in desktop

Nothing comes to mind for me.

**Comment by p-jackson** [comment]
@jblz I tried this branch on Desktop and the checklist never finishes loading. Desktop might be missing the secret sauce needed to support these config changes.

image

I have a hunch it might be related to the `onboarding-checklist/phase2`, but I'm confirming that now

**Comment by p-jackson** [comment]
Looks related #641

**Comment by jblz** [comment]
Thanks for testing & for the link to that issue, @p-jackson.  I'll give it a run to see if we can't brew up a fix for desktop in one go here.

**Comment by p-jackson** [comment]
Self assigning to see if I can make any progres while @jblz is afk

**Comment by p-jackson** [comment]
Changing the `http` action parameters for the checklist actions seems to have fixed the issue with the checklist page not loading.

The request for checklist data would ask for the http_envelop, but the desktop code that handled the response wouldn't unwrap the envelop. It interpreted the params being passed to `http` to mean that there _wasn't_ an envelop. Changing to `apiVersion` instead of `apiNamespace`, and removing the explicit `http_envelop` query param, jostled the logic a bit so each network stack does what it thinks is appropriate.

On web `wpcom` uses `wpcom-proxy-request` to make requests, and on desktop it uses `wpcom-xhr-request`. Which is why there's a difference in behaviour.

Tested in desktop and web, proxied and unproxied.

What's fishy about the change I've made is that the [docs for `http`](https://github.com/Automattic/wp-calypso/blob/master/client/state/data-layer/wpcom-http/actions.js#L12) say that `apiNamespace` should be prefered over `apiVersion`. Maybe it's just a bug in `wpcom-xhr-request`. Any thoughts @jblz ?

**Comment by p-jackson** [comment]
Where not out of the woods yet. I've discovered another bug where you can't exit the page editor using the back button in the top-left corner. No errors in the console, the button's just unresponsive.

Affects web and desktop.

I'll rebase first and then wee what's going on.

**Comment by p-jackson** [comment]
Looks like rebasing fixed it 🤞 So must have been fixed on `master`.
We'll see how this test runs go.

**Comment by jblz** [comment]
>  apiNamespace should be prefered over apiVersion.

@p-jackson Ya, it's strange that changing to `apiVersion` would "fix" this...
Did you try just omitting the envelope query arg to see what would happen?

> Maybe it's just a bug in wpcom-xhr-request.

It's possible.  I noticed that it defaults `processResponseInEnvelopeMode` to true here:
https://github.com/Automattic/wpcom-xhr-request/blob/b6e3ec5e61efe5dfd1f9476828991b5329eab2f8/index.js#L26

...& sets a variable of the same name in a different scope here:
https://github.com/Automattic/wpcom-xhr-request/blob/b6e3ec5e61efe5dfd1f9476828991b5329eab2f8/index.js#L43

**Comment by p-jackson** [comment]
> Did you try just omitting the envelope query arg to see what would happen?

Yeah this worked fine for desktop, but on web it would send a `_envelope` query param and the checklist failed to load.

The code `wpcom-proxy-request` uses for dealing with `apiVersion` vs `apiNamespace` is here: 22129-pb

Actually you can see that it's already a bit mixed up on `master`. When requesting the checklist data the request includes both the `_envelope` _and_ `http_envelop` query parameters! It does give the impression that data layer actions shouldn't need to specify any envelope behaviour though, and that lower levels should figure out the best way to send the request.

> it defaults `processResponseInEnvelopeMode` to true ... & sets a variable of the same name in a different scope

Tracing through the code I think `processResponseInEnvelopeMode` is being set correctly.

The only thing I can think of changing in `wpcom-xhr-request` might be changing this line so it checks whether the namespace starts with `"/rest"`?
https://github.com/Automattic/wpcom-xhr-request/blob/b6e3ec5e61efe5dfd1f9476828991b5329eab2f8/index.js#L117

But I'm thinking that the change I've got in this PR might be the easiest way forward now, and I could follow up with someone about the comment about `apiNamespace` being the preferred option.

@jblz

**Comment by jblz** [comment]
As mentioned in Slack, we probably do want to keep using `apiNamespace` & it seems taking out the `http_envelope` query arg breaks the response handling (Someone smarter than me is going to have to explain how these lib internals work!)

Let's see if we can work around it with something like this: https://gist.github.com/jblz/63ce4207172f41fa94a186044a409863

**Comment by p-jackson** [comment]
Ok, I think this is good to go now. I've followed the suggestion @jblz's gist and ensuring that API responses have been unpacked by doing it on our side.

Updated PR description and testing instructions to reflect that this affects wp-desktop.

Some e2es are failing but as mentioned above this is unrelated to this PR. I've run the failing tests locally and they pass.

**Comment by jblz** [comment]
Sweet!  This is working well for me on both the desktop app and the web.

I was able to view and complete checklist items in the desktop app.

It makes me wonder what other data layer responses aren't handled appropriately in the desktop app.

**Pull request merged**
