### PR TITLE
Invites: Timing improvements for notices and placeholders when accepting an invite

### PR DESCRIPTION
**Pull request by ebinnion**
When accepting an invite, there are a couple of places where we show a placeholder improperly or a notice a bit too soon. This PR aims to fix that.

### CODE REVIEW

**Comment by ebinnion** [comment]
Note: We may have some conflicts with #2499 since we're now passing the invite to `invite-accept-logged-in` as a single prop instead of spreading it. Just something to keep in mind for whichever PR goes in second.

**Comment by ebinnion** [comment]
I'm still not 100% sure why, but the logged in accept notice kept appearing on the invite page instead of the redirect page. The only way I could figure out how to fix it was to also use the `localStorage` flag for logged in invites.

@lezama - What do you think?

**Comment by ebinnion** [comment]
This LGTM now. Go team :100: :smile: 

If you're fine with the PR as is, feel free to ship.

**Comment by lezama** [comment]
yay!

**Pull request merged**
