### PR TITLE
Media: Show Storage Count to 2 Decimal Places When <1% 

### LINKED ISSUE #83556: [Enhancement]: Calypso Media Usage - Improve how we display % storage used for low-media sites
### What

In the WordPress.com Media Library, show either decimal points or an indication that some media storage is used, just less than 1%. 

### Why

Right now, sites show `0% of XX GB used` when they have used less than (I am guessing) 1% of their disk space quota.  With AT sites with larger media quotas, it might stay at 0% for a while, if they're optimizing images properly.

This can lead to confusion, or appear to be a bug.  Example: https://github.com/Automattic/wp-calypso/issues/83516

### How

Option 1 - more decimal places:

- Add decimal places in the WordPress.com Media library to show more detailed media usage, like `0.01% of XX GB used.`

Option 2 - show "<1%" until 1% is met/passed

- Alternatively, we could also just show something like `< 1% of XX GB used`.

### PR DESCRIPTION
**Pull request by Aurorum**
Fixes #83556

## Proposed Changes

* Shows the Media storage count to 2 decimal places instead of as an integer. 

The idea - in theory anyway - is that this will stop users contacting Support concerned about a 'bug' of their storage count not working; in practice, their storage capacity is just so great that it still rounds to 0%. 

I don't mind restricting this to sites with less than 1% of storage, but I didn't see the harm in including this for all sites. 

## Testing Instructions

A code review is probably sufficient to be honest, but you can see this in the Media Library. The 0% issue is most notable on a site with a lot of storage and a fair amount of files, causing users to be confused about the storage limit breaking.

Screenshot 2024-01-08 at 23 26 18

cc @paulopmt1 @lupus2k: looks like you touched this last - would you mind giving it a quick spin if you have a second? Thanks!

### CODE REVIEW

**Comment by paulopmt1** [comment]
I remember we intentionally rounded those numbers in the past (4225-gh-Automattic/dotcom-forge#issuecomment-1771983829). @obenland, would you recall if that was also to avoid support?

If you decide to move that forward @Aurorum, please also check the native version of it to ensure it works the same way: 4225-gh-Automattic/dotcom-forge#issuecomment-1766931148

**Comment by Aurorum** [comment]
Thanks! I'm afraid that's a private repo so I can't see what it refers to, but I think this rounding would only be for the display anyway?

**Comment by paulopmt1** [comment]
> Thanks! I'm afraid that's a private repo so I can't see what it refers to, but I think this rounding would only be for the display anyway?

That's correct, the rounding was only for displaying it to the user.

**Comment by obenland** [comment]
> this will stop users contacting Support concerned about a 'bug' of their storage count not working

Is that something that happens on a wider scale? If not, let's leave it as is and keep it visually simpler.

**Comment by Aurorum** [comment]
@obenland I've see it pop up myself in Support every now and then, but cc @cuemarie who made the original issue for details.

I've switched it so that it's only 2 decimal points under 1% though. I think that achieves best of both worlds?

**Comment by cuemarie** [comment]
> I've switched it so that it's only 2 decimal points under 1% though. I think that achieves best of both worlds?

Apologies for my delay @Aurorum – I think this makes perfect sense!  The only time I run into this in chat is when there is less than 1% usage, as customers think there's a bug because their usage then says 0%, so I think this would sufficiently address that.

**Review by paulopmt1 — APPROVED** [review]
It's working as expected! Nice work @Aurorum!

| Less than 1%: | More than 1% |
|--------|--------|
| image | image |
| image | image |

**Comment by paulopmt1** [comment]
Thanks so much for your contribution @Aurorum!

**Pull request merged**
