### PR TITLE
Select section patterns for the Pattern Assembler MVP

### PR DESCRIPTION
**Pull request by miksansegundo**
#### Proposed Changes

* Update the list of IDs and names of the section patterns

#### Testing Instructions

* Create a new site, don't choose any goal, and a vertical, in the design picker step scroll down to click on the Blank canvas CTA
* Click on `Add a first section`
* Check that we display the sections listed in this [comment](https://github.com/Automattic/wp-calypso/issues/66789#issuecomment-1255670983)

#### Pre-merge Checklist

- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [X] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?

Related to [#66789](https://github.com/Automattic/wp-calypso/issues/66789)

### CODE REVIEW

**Comment by taipeicoder** [comment]
A couple of notes:

1. Pattern ID 7153 (Media and text with image on the left) seems to be missing.
2. Some patterns don't have images, is that expected? cc: @alaczek @autumnfjeld

**Comment by miksansegundo** [comment]
Thanks @taipeicoder! I missed that pattern.

The patterns "without images" have image placeholders because they are wireframe patterns.

**Review by taipeicoder — APPROVED** [review]
👍

**Comment by autumnfjeld** [comment]
I'm a little late to the discussion, but using wireframe patterns which by design don't have images. :)
p1664256309093529-slack-CRWCHQGUB

**Pull request merged**
