### PR TITLE
Override the backlink on the Live Preview

### PR DESCRIPTION
**Pull request by okmttdhr**
Related to 
https://github.com/Automattic/wp-calypso/issues/80595
https://github.com/WordPress/gutenberg/pull/54174

## Proposed Changes

Override the Back on the Live Preview with the `'core/edit-site'` store. This PR solves https://github.com/Automattic/wp-calypso/issues/80595 and works after https://github.com/WordPress/gutenberg/pull/54174.

## Testing Instructions

*

## Pre-merge Checklist

- [x] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [x] https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md for your changes?
- [x] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [x] Have you checked for TypeScript, React or other console errors?
- [x] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [x] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [x] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

**Comment by arthur791004** [comment]
We have to do it on Jetpack. See the [site_editor_dashboard_link](https://github.com/Automattic/jetpack/blob/319ce4e1b9974cc487dd2b90da555ec7ed802091/projects/plugins/jetpack/modules/masterbar/admin-menu/class-admin-menu.php#L86) function and the `block_editor_settings_all` filter on [atomic](https://github.com/Automattic/jetpack/blob/319ce4e1b9974cc487dd2b90da555ec7ed802091/projects/plugins/jetpack/modules/masterbar/admin-menu/class-atomic-admin-menu.php#L32) and [wpcom](https://github.com/Automattic/jetpack/blob/319ce4e1b9974cc487dd2b90da555ec7ed802091/projects/plugins/jetpack/modules/masterbar/admin-menu/class-wpcom-admin-menu.php#L38)

**Comment by okmttdhr** [comment]
@arthur791004 
I'm a little confused because there are a few places in wpcom-block-editor where we're making changes to `__experimentalDashboardLink`.
https://github.com/Automattic/wp-calypso/blob/288df6b4729eb82e37824b397c452634a2e5842f/apps/wpcom-block-editor/src/calypso/features/iframe-bridge-server.js#L1027
https://github.com/Automattic/wp-calypso/blob/288df6b4729eb82e37824b397c452634a2e5842f/apps/wpcom-block-editor/src/wpcom/features/site-editor-env-consistency.js#L20

Maybe we should move these into Jetpack?

**Comment by arthur791004** [comment]
> [wp-calypso/apps/wpcom-block-editor/src/calypso/features/iframe-bridge-server.js](https://github.com/Automattic/wp-calypso/blob/288df6b4729eb82e37824b397c452634a2e5842f/apps/wpcom-block-editor/src/calypso/features/iframe-bridge-server.js#L1027)

I guess we might not need this for the site editor since we have un-iframed the site editor. But maybe page/post editor still relies on it.

> [wp-calypso/apps/wpcom-block-editor/src/wpcom/features/site-editor-env-consistency.js](https://github.com/Automattic/wp-calypso/blob/288df6b4729eb82e37824b397c452634a2e5842f/apps/wpcom-block-editor/src/wpcom/features/site-editor-env-consistency.js#L20)

This one seems for dev/test env to keep the consistency of the origin. I think Jetpack doesn't know that so we might still need to override the Back URL on the Live Preview 🤔 But the goal of this is to replace the origin instead of the destination.

**Comment by okmttdhr** [comment]
> [wp-calypso/apps/wpcom-block-editor/src/calypso/features/iframe-bridge-server.js](https://github.com/Automattic/wp-calypso/blob/288df6b4729eb82e37824b397c452634a2e5842f/apps/wpcom-block-editor/src/calypso/features/iframe-bridge-server.js#L1027)
I guess we might not need this for the site editor since we have un-iframed the site editor. But maybe page/post editor still relies on it.

> [wp-calypso/apps/wpcom-block-editor/src/wpcom/features/site-editor-env-consistency.js](https://github.com/Automattic/wp-calypso/blob/288df6b4729eb82e37824b397c452634a2e5842f/apps/wpcom-block-editor/src/wpcom/features/site-editor-env-consistency.js#L20)
This one seems for dev/test env to keep the consistency of the origin. I think Jetpack doesn't know that so we might still need to override the Back URL on the Live Preview 🤔 But the goal of this is to replace the origin instead of the destination.

Thanks for your explanation, @arthur791004  👍 

Let's move this PR (and `site-editor-env-consistency` as well, in my opinion) into Jetpack!

**Comment by okmttdhr** [comment]
I've thought about this again, and I don't think the backlink for Live Preview should be changed in Jetpack (or in `jetpack/modules/masterbar/admin-menu
/class-admin-menu.php` at least), because, looking at [this comment](https://github.com/Automattic/jetpack/blob/319ce4e1b9974cc487dd2b90da555ec7ed802091/projects/plugins/jetpack/modules/masterbar/admin-menu/class-admin-menu.php#L80-L81), the backlink in the Site Editor does not belong to the admin menu. 

And I use `__experimentalThemePreviewBackLink` instead of `__experimentalDashboardLink` as described in https://github.com/WordPress/gutenberg/pull/54174, so the changes only affect the Site Editor, not the admin menu. 

I had thought about implementing it in `jetpack-mu-wpcom`, but in that case, it would be better to migrate [site-editor-env-consistency.js](https://github.com/Automattic/wp-calypso/blob/288df6b4729eb82e37824b397c452634a2e5842f/apps/wpcom-block-editor/src/wpcom/features/site-editor-env-consistency.js#L20) along with it for coherence. 

Any thoughts, @arthur791004?

**Comment by arthur791004** [comment]
> because, looking at [this comment](https://github.com/Automattic/jetpack/blob/319ce4e1b9974cc487dd2b90da555ec7ed802091/projects/plugins/jetpack/modules/masterbar/admin-menu/class-admin-menu.php#L80-L81), the backlink in the Site Editor does not belong to the admin menu.

I think the important part is `it belongs here because it's part of changing wp-admin links to their wp.com equivalents.` The Site Editor is part of the wp-admin since the URL is `/wp-admin/site-editor.php`, and that settings are only used by the Site Editor as well (`$settings`, `block_editor_settings_all`)

> it would be better to migrate [site-editor-env-consistency.js](https://github.com/Automattic/wp-calypso/blob/288df6b4729eb82e37824b397c452634a2e5842f/apps/wpcom-block-editor/src/wpcom/features/site-editor-env-consistency.js#L20) along with it for coherence.

I think this is only for the consistency of the origin instead of the link. The better way might be to migrate them to `jetpack-mu-wpcom` as you mentioned 🙂

We have to avoid adding more and more features to wpcom-block-editor or ETK plugin since we have the plan to migrate them to Jetpack. See p9oQ9f-Ht-p2 and p58i-dox-p2

**Comment by okmttdhr** [comment]
Thanks for your comment again, @arthur791004, and that all makes sense to me.

- I'll raise a PR to `plugins/jetpack`.
- And it'd be nice if I can move [site-editor-env-consistency.js](https://github.com/Automattic/wp-calypso/blob/288df6b4729eb82e37824b397c452634a2e5842f/apps/wpcom-block-editor/src/wpcom/features/site-editor-env-consistency.js#L20) into `packages/jetpack-mu-wpcom`.
- After looking at p9oQ9f-Ht-p2, I started to feel tracking implementation (e.g. https://github.com/Automattic/wp-calypso/pull/80953) should be migrated into Jetpack as well.

**Pull request closed without merging**
