### PR TITLE
Migrate my-sites/sidebar/style

### LINKED ISSUE #33806: CSS: Migrate my-sites/sidebar/style
Migrate my-sites/sidebar/style

### PR DESCRIPTION
**Pull request by Stojdza**
#### Changes proposed in this Pull Request

* CSS: Migrate `my-sites/sidebar/style`

#### Testing instructions

* Navigate to "My Sites". Look at the sidebar. Does it look good? Is it the same as production? 

Fixes #33806

Refs #27515

### CODE REVIEW

**Comment by jsnajdr** [comment]
In the `my-sites/sidebar/style.scss` file:
- the `top` style for `sidebar__menu-link-secondary-text` can be removed. This element has only one usage today, and that's the name of the plan (e.g., Business). It's already vertically centered thanks to the flex layout of the Sidebar Menu component. The `top` style only un-centers it slightly.
- the `manage_menu__plugins-extra-icon` style is no longer used at all.

**Comment by jsnajdr** [comment]
Another obsolete style is the `background: none` for `li.stats a::after`. It disables the `long-content-fade` overlay on the right edge of the menu item. It was useful when the StatsSparkline was an absolutely-positioned element that "floated" above the menu item. Now, in the new sidebar, the sparkline is a separate box in a flex layout. No more overlap with the `long-content-fade`.

The only remaining useful styles in this file are the ones that style the `.stats__sparkline`.

**Comment by Stojdza** [comment]
Thanks for the details! Done.

**Review by blowery — APPROVED** [review]
👍 LGTM

**Pull request merged**
