### PR TITLE
Update WoA cancellation warning copy

### PR DESCRIPTION
**Pull request by DustyReagan**
#### Proposed Changes

* Updated WoA cancellation warning copy to let the customer know we will set their site to private.
* A couple grammatical edits.

Before | After
--|--
before-update  | after-editorial

#### Testing Instructions

Sandbox this PR and cancel a test site that is on the Atomic platform. Before completing the cancellation process, you will be presented with the warning above. Confirm it is the updated copy, grammatically correct, and delivers the message.

Related to #57278

### CODE REVIEW

**Comment by obenland** [comment]
@Automattic/editorial Could I ask for your review of these wording changes?

**Comment by SeywardDarby** [comment]
image

**Review by obenland — APPROVED** [review]
:shipit:

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/7387418

Thank you @DustyReagan for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/7387418).

**Pull request merged**
