### PR TITLE
Gutenboarding: stop existing users A/B test

### PR DESCRIPTION
**Pull request by razvanpapadopol**
#### Changes proposed in this Pull Request
* stop existingUsersGutenbergOnboard test
* cleanup Gutenboarding test code from abtest config and signup controller 

#### Testing instructions
* Go to https://calypso.live/?branch=update/remove-gutenboarding-abtest
* Open console and run `localStorage.setItem( 'ABTests', '{"existingUsersGutenbergOnboard_20200911":"gutenberg"}' )`
* Go to `/start` => no redirect should happen

### CODE REVIEW

**Comment by yansern** [comment]
Checked out and tested locally. It works. 👍

**Review by yansern — APPROVED** [review]

**Comment by simison** [comment]
The `removeWhiteBackground()` logic might not be needed anymore either?

**Comment by razvanpapadopol** [comment]
We still have the [new-launch flow](https://github.com/Automattic/wp-calypso/pull/45800/files#diff-46ce4cd8580489aebbb3447a87c3cb57R84) that is using white background so it would be best to finish cleanup when we remove also that flow.

**Comment by simison** [comment]
> so it would be best to finish cleanup when we remove also that flow.

Oh I thought it's there just to work through the transformation across `/start` → `/new` to avoid flash of blue, and we thus wouldn't need it anymore. I'm not super familiar with internals of the redirect tho. :-)

**Comment by razvanpapadopol** [comment]
> > so it would be best to finish cleanup when we remove also that flow.
> 
> Oh I thought it's there just to work through the transformation across `/start` → `/new` to avoid flash of blue, and we thus wouldn't need it anymore. I'm not super familiar with internals of the redirect tho. :-)

The conditional for `new-launch` was indeed [added when we fixed a redirect bug](https://github.com/Automattic/wp-calypso/pull/42068/files#diff-46ce4cd8580489aebbb3447a87c3cb57R53). But it wasn't really necessary since `new-launch` [is adding also it's own class](https://github.com/Automattic/wp-calypso/blob/master/client/layout/index.jsx#L161-L163).

So it's fine to remove now the `removeWhiteBackground` method from signup controller and leave the `is-white-signup` custom CSS [used just by reskinned flow](https://github.com/Automattic/wp-calypso/blob/master/client/signup/main.jsx#L640-L646).

**Comment by simison** [comment]
Let's hold off merging for little longer.

**Comment by razvanpapadopol** [comment]
Done in https://github.com/Automattic/wp-calypso/pull/48052

**Pull request closed without merging**
