### PR TITLE
WooCommerce Signup: Add Responsiveness

### LINKED ISSUE #31048: WooCommerce Signup: Not Responsive
#### Steps to reproduce
1. Starting at URL: https://woocommerce.com
2. Click "Get started" on a mobile 

#### What I expected

A nice, responsive page. 

#### What happened instead

screenshot_20190226-175041

#### Context / Source

Discovered whilst working on #31047.

### PR DESCRIPTION
**Pull request by torres126**
#### Changes proposed in this Pull Request

The intention of this PR is to make the WooCommerce connect screen on mobile devices, well, something more than what it currently is...which is a bit of a mess. 

I'm not too certain about the specific design sought, so I've tried to keep it simple and what looks best to me. This ultimately is just intended to be an improvement from current. 

#### Testing instructions

Try the flow when clicking "Get started" on woocommerce.com. Does it look good, at least better than current, on mobile devices? Does the code look good? Unfortunately, word break also causes issues breaking the URL so avoiding that in favour of font size. 

**Current:**

dgfdfgfdfdg

**Proposed:**

fsdsfdffsdsfd

Fixes #31048

### CODE REVIEW

**Comment by torres126** [comment]
Not quite certain whom to ping on this. cc @ice9js, @scruffian, @danhauk

**Comment by torres126** [comment]
Couple more pings just in case anyone has some time to review: @shaunandrews, @stephanethomas

**Comment by torres126** [comment]
Just pinging the rest of those who've touched this file in case anyone has time to review: cc @Tug, @flootr, @jsnmoon

**Comment by danhauk** [comment]
Code LGTM. Tested the WooCommerce, Crowdsignal, and Akismet oauth flows and all seems good. 

Pinging a few WooCommerce designers to do a final sign-off on the design here. @josemarques  @jameskoster

**Comment by danhauk** [comment]
Approving to avoid holding this up any longer. It works and looks good. We can make any changes to the design in another PR if necessary.

Thanks for doing this @torres126! And sorry for the delay in reviewing.

**Pull request merged**
