### PR TITLE
Activity log: remove filterbar icon

### PR DESCRIPTION
**Pull request by keoshi**
This PR removes the icon from the filterbar in Activity.

### Before

image

image

### After

image

image

### How to test

- Run locally or fire up https://calypso.live/?branch=remove/activity-log-filterbar-icon
- Go to Activity.
- Ensure the icon is gone and that the label works fine.

### CODE REVIEW

**Comment by keoshi** [comment]
@enejb mind reviewing so we can merge this little one?

**Comment by enejb** [comment]
Sure this was next on my list. It needs a rebase. There are some css syles that will probably need to get removed.

**Comment by keoshi** [comment]
Good catch, hadn't seen that. Conflicts resolved.

**Comment by enejb** [comment]
I think the filter icon is still there.

**Comment by enejb** [comment]
Never mind it is gone :)

**Pull request merged**
