### PR TITLE
Themes: Adding alert on themes that need to be updated

### LINKED ISSUE #62822: Themes: Update notification is not actionable unless in WP Admin view
### Quick summary

If there is a theme update, Theme menu item on the left sidebar will show a related notification like ⓵

Screenshot 2022-04-15 at 16 14 10

It's not clear how to clear that notification from Themes section unless you switch to the Classic (WP Admin) view

https://user-images.githubusercontent.com/39308239/163576242-86e6d7c3-bfa9-488d-bb47-355efe72c1b9.mov

 

### Steps to reproduce

1. On AT site install an outdated theme (for example Storefront https://downloads.wordpress.org/theme/storefront.4.0.0.zip)
2. Visit https://wordpress.com/themes and see the update notification like ⓵ on the left

### What you expected to happen

See which theme needs to be updated

### What actually happened

I don't see which theme needs to be updated

### Context

_No response_

### Simple, Atomic or both?

Atomic

### Theme-specific issue?

No

### Browser, operating system and other notes

macOS Monterrey 12.3 with Google Chrome Version 100.0.4896.127 (Official Build) (x86_64)

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Workaround details

- Switch to [WP Admin Dashboard](https://wordpress.com/en/support/dashboard/) view
- Visit My Home > Updates at `SITE_URL/wp-admin/update-core.php`

### PR DESCRIPTION
**Pull request by valterlorran**
#### Changes proposed in this Pull Request

* Adds an alert in the outdated themes to allow the users to update it. The number in the badge in the sidebar menu would inform the number of Themes that need to be updated, but the user could not take action to update it.

#### Testing instructions

* Go to the `Themes` under `Appearance`.
* Click on `Install Theme` and upload an outdated theme, for example, https://downloads.wordpress.org/theme/storefront.4.0.0.zip
* Then, you should see a badge with a number in the `Themes` menu.
* Go to the `Themes` page again and select the `My Themes` tab, which should also contain the badge with the number.
* You'll see the outdated themes with alerts, indicating that they need to be updated.
* Click on the button `Update Theme`, and the numbers in the badges should decrease or disappear in case no theme requires an update

Closes #62822

### CODE REVIEW

**Comment by valterlorran** [comment]
Hey @SaxonF, do you have any thoughts about the design that we are implementing?

**Comment by markbiek** [comment]
Functionality works as expected. Just waiting on design feedback before approving.

**Review by markbiek — APPROVED** [review]
LGTM (pending any design tweaks)

**Comment by SaxonF** [comment]
Sorry I missed this! Looks great y'all! We are working on a redesign of the themes showcase so will make sure this is covered as well

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/7331304

Thank you @valterlorran for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/7331304).

**Pull request merged**
