### PR TITLE
Rating: Change from noticon to gridicon

### PR DESCRIPTION
**Pull request by raoulwegat**
This replaces Noticons with Gridicons, by overlaying solid stars on outline stars, with a mask, to create half stars. See initial discussion here: https://github.com/Automattic/gridicons/pull/249 and CSS proptotype here: https://codepen.io/raoulwegat/pen/yzBqEm

**Before**
screen shot 2017-09-17 at 4 47 17 pm

**After**
screen shot 2017-09-17 at 4 47 29 pm

Note: Size difference is due to Gridicons requiring multiples of 24px (After is 48px), whereas original Rating was set to 50px.

**Testing Instructions**

1. Open http://calypso.localhost:3000/devdocs/design/rating
2. Edit `docs/example.jsx` to test any rating from 10 to 100 with intervals of 10 (eg. 10, 20, 30...). Save & reload.

**Notes**

[Masking](https://github.com/Automattic/wp-calypso/pull/18103/files#diff-2a7f489faff42c576293644df618e498R94) is using done [`clip-path`](https://developer.mozilla.org/en-US/docs/Web/CSS/clip-path) for [supporting browsers](http://caniuse.com/#feat=css-clip-path), except IE and Edge who don't support the property. Fallback (for IE/Edge) is provided by the [`clip`](https://developer.mozilla.org/en-US/docs/Web/CSS/clip) property that is still present in all browsers even though it has been deprecated.

Tested in Windows 10 IE11/Edge/Chrome/Firefox, macOS Sierra Safari/Chrome/Firefox, iOS 9 & 10 Safari, Android 5, 6 & 8 Chrome.

### CODE REVIEW

**Comment by folletto** [comment]
Sharp! 👍

**Comment by aidvu** [comment]
I'll check later today. 1 flight left before I get home. :)

**Comment by aidvu** [comment]
Code LGTM. If you're ok with my changes @raoulwegat, feel free to deploy. :)

Updated the CSS for plugins page (Jetpack site):
plugins

**Comment by raoulwegat** [comment]
Adjusted sizes in plugin broswer.

**Before**

screen shot 2017-09-28 at 2 10 32 pm
15px

**After**
screen shot 2017-09-28 at 2 10 15 pm
12px (Gridicons only available in 12, 18, 24, 36, 48, 54, 72px sizes).

**Pull request merged**
