### PR TITLE
Add 16px of top margin to full-post featured image

### LINKED ISSUE #6517: Reader: add margin between full-post header and featured image
It seems that the full-post header and the featured-image are quite close together and could use some extra margin.

#### Steps to reproduce
1. Starting at URL: https://wordpress.com/read/blogs/79615376/posts/2940
2. Notice the (small) empty space between the featured-image and the post header (where the "Follow" button resides

#### What I expected
I expected that visual space to be larger, perhaps comparable to the space between the featured-image and the post title.

#### What happened instead
The empty space is rather small, making the "Follow" button look too close to the feature image.

#### Browser / OS version
Opera 38.0.2220.31 stable on Mac OS X 10.11.5 64-bit

#### Screenshot / Video
https://cloudup.com/cZgQJ2CJMWn

#### Context / Source

#dogfooding

### PR DESCRIPTION
**Pull request by hypest**
Fixes #6517 by adding some top-margin to the Reader's full-post featured-image so it better separates itself from the post header.

@shaunandrews , would you mind reviewing this? Thanks!

Test live: https://calypso.live/?branch=fix/6517-featured-image-add-top-margin

### CODE REVIEW

**Comment by bluefuton** [comment]
cc @jancavan

**Comment by folletto** [comment]
Could you add a before/after screenshot, please? :)

**Comment by hypest** [comment]
Hey @folletto , sure. Here they are:
Before: https://cloudup.com/ixHxjnUOh7C
After: https://cloudup.com/c9Lj2JrCykr

**Comment by jancavan** [comment]
Thanks @hypest!

I think `24px` is a bit much especially on mobile. Updated it to `18px` in: https://github.com/Automattic/wp-calypso/pull/6518/commits/3bd8938f6f51a57c16107eb4a42de110b583c277

At `24px`:
screenshot 2016-07-05 08 22 03

At `18px`:
screenshot 2016-07-05 08 21 35

I think this is good to go 🚢

**Pull request merged**
