### PR TITLE
Add Ons: Migrate useAddOnFeatureSlugs to data store

### PR DESCRIPTION
**Pull request by jeyip**
Related to https://github.com/Automattic/wp-calypso/issues/81374 and https://github.com/Automattic/martech/issues/2023

This PR is part of the migration of the add-ons data layer into an npm package. We're doing so to align with the 2023 plans pricing page refactor, which aims to migrate the plans-grid into a reusable package ( which will be shared in environments inside and outside Calypso )

## Proposed Changes

* Migrates the useAddOnFeatureSlugs hook into the data-stores npm package

## Testing Instructions

**/add-ons**
* Create a site through `/start`
* Navigate to `/add-ons/{SITE_SLUG}`
* Verify that what is displayed in this feature branch matches what is displayed in production
* Verify that the add-on CTA buttons continue to work as expected

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

**Review by ddc22 — COMMENTED** [review]
@jeyip I wonder if data-store is the correct place for this logic to live. The general idea of data stores is for it to be a redux store slice. 

This actually more related to product resolution logic. Do you think it makes more sense to move this into `@automattic/calypso-products`

**Comment by jeyip** [comment]
> @jeyip I wonder if data-store is the correct place for this logic to live. The general idea of data stores is for it to be a redux store slice.

Interesting 🤔 My understanding was that _any_ data layer for add-on upgrades could live in this package. Taking a closer look at the [README.md](https://github.com/Automattic/wp-calypso/blob/trunk/packages/data-stores/README.md), it seems to align with what you're saying about redux store slices. I am, however, seeing examples that have similar intentions as I do ( [example 1]( https://github.com/Automattic/wp-calypso/tree/b4486c2015619fd21564e3888c35c5ad2a31cc1b/packages/data-stores/src/starter-designs-queries ), [ example 2 ]( https://github.com/Automattic/wp-calypso/tree/b4486c2015619fd21564e3888c35c5ad2a31cc1b/packages/data-stores/src/queries ), [ example 3 ]( https://github.com/Automattic/wp-calypso/tree/b4486c2015619fd21564e3888c35c5ad2a31cc1b/packages/data-stores/src/contextual-help ) ) that don't leverage a redux store.

> Do you think it makes more sense to move this into @automattic/calypso-products

I know that @chriskmnds talked about wanting to move away from usage of @calypso-products for anything plans related pdvytD-bG-p2

"We could soon have zero dependencies on this and a complete replacement i.e. the plans data store becomes the single source of truth for plan-specific metadata. Plan tag lines, descriptions, and anything statically defined can be served from the API and consolidated at the plans store (as is [done already](https://href.li/?https://github.com/Automattic/wp-calypso/blob/trunk/packages/data-stores/src/plans/resolvers.ts#L163-L177), just the data is a bit out of date)."

With that being said, the add-ons data layer _is_ independent of the plans grid so I don't think his sentiments apply here. And, although I _think_ it would be more intuitive to search for the add-ons data layer in @automattic/data-stores, I'm not entirely certain, so it's probably worthwhile to touch base with team calypso or another team? Wondering how you feel about that @jdc91?

**Comment by ddc22** [comment]
Wow it's just strange to see ( [example 1](https://github.com/Automattic/wp-calypso/tree/b4486c2015619fd21564e3888c35c5ad2a31cc1b/packages/data-stores/src/starter-designs-queries), [example 2 ](https://github.com/Automattic/wp-calypso/tree/b4486c2015619fd21564e3888c35c5ad2a31cc1b/packages/data-stores/src/queries), [example 3 ](https://github.com/Automattic/wp-calypso/blob/b4486c2015619fd21564e3888c35c5ad2a31cc1b/packages/data-stores/src/contextual-help/admin-sections.ts)). Because the first thought that comes to my mind when I think `data-store` is some redux based data slice. But well since we already have a precedence maybe we should also think about updating the data store docs to indicate this (unrelated to this PR). Wonder if the `data-store` will be misused to just dump all data transformations , or maybe that is the idea 🤔.

I will revert to your best judgment here since you are more aware of the add-ons context. If you think we can iterate on this later let me know. Other than that code wise the change looks good to me. Happy to do some testing if you want to go ahead with this version.

**Comment by jeyip** [comment]
> I will revert to your best judgment here since you are more aware of the add-ons context. If you think we can iterate on this later let me know. Other than that code wise the change looks good to me. Happy to do some testing if you want to go ahead with this version.

I believe it's okay to move forward with testing this PR -- we can change direction pretty easily if it turns out that `data-stores` isn't the right move ( copy logic into new package and update import references )

In the meantime, I posed a question in slack to see if we can't get more insight p1699561741945029-slack-C7YPUHBB2 

_Edit:_

Looks like we got a response p1699565114982959/1699561741.945029-slack-C7YPUHBB2. It's a suggestion to ignore the language about the redux implementation ( perhaps we can update the README to reflect this now too )

**Review by southp — APPROVED** [review]
It works as described and LGTM :)

**Comment by southp** [comment]
Deploying this on behalf of Jeremy since he is AFK :)

**Pull request merged**
