### PR TITLE
Calypso build: Transpile TypeScript

### PR DESCRIPTION
**Pull request by sirreal**
Ensure TypeScript files in packages are transpiled.

## Testing
- Verify 57d0a40362780238a84b3431bd7008ae07e1708b is OK. Try [Calypso-live](https://hash-57d0a40362780238a84b3431bd7008ae07e1708b.calypso.live). That includes packages with TypeScript UI components.
- Verify that .ts and .tsx files in packages are transpiled.

### CODE REVIEW

**Review by ockham — APPROVED** [review]
Seems good. Should this get a Changelog entry?

**Comment by beaucollins** [comment]
This appears to now include the `index.js` correctly in the builds. Bonus points now if it can put the corresponding Typescript declaration next to the transpiled code.

**Comment by beaucollins** [comment]
I tried using `tsc` to generate the declaration for the file:

```
npx tsc --jsx react --declaration packages/calypso-ui/src/progress-bar/index.tsx 
node_modules/@types/react-redux/index.d.ts:103:79 - error TS2694: Namespace '"wp-calypso/node_modules/hoist-non-react-statics/index"' has no exported member 'NonReactStatics'.

103 > = ComponentClass<JSX.LibraryManagedAttributes<C, P>> & hoistNonReactStatics.NonReactStatics<C> & {
                                                                                  ~~~~~~~~~~~~~~~


Found 1 error.
```

My first search for this error lead me here: https://github.com/ant-design/ant-design/issues/16396#issuecomment-488633240

I haven't yet confirmed if that solves my problem as well.

**Comment by sirreal** [comment]
> I tried using `tsc` to generate the declaration for the file:
> 
> ```
> node_modules/@types/react-redux/index.d.ts:103:79 - error TS2694: Namespace '"wp-calypso/node_modules/hoist-non-react-statics/index"' has no exported member 'NonReactStatics'.
> 
> Found 1 error.
> ```
> 
> My first search for this error lead me here: [ant-design/ant-design#16396 (comment)](https://github.com/ant-design/ant-design/issues/16396#issuecomment-488633240)
> 
> I haven't yet confirmed if that solves my problem as well.

I think we're seeing this issue:
https://github.com/DefinitelyTyped/DefinitelyTyped/issues/33690

With more information in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/33919

It seems like we'll need to play with dependencies `@types/hoist-non-react-statics` and `@types/react-redux`.

**Comment by sirreal** [comment]
> Bonus points now if it can put the corresponding Typescript declaration next to the transpiled code.

The changes in this PR unblock TypeScript work by applying our existing transpile to TypeScript files. This seems to be the simplest change 🙁 

I agree that compiling with babel and discarding type information is not ideal. I suggest that we use `tsc` directly to compile packages of mixed TypeScript and JavaScript. This will preserve the type information and will also encourage us to adhere to a well-defined language spec. I've started to explore that approach in https://github.com/Automattic/wp-calypso/pull/36186

> It seems like we'll need to play with dependencies `@types/hoist-non-react-statics` and `@types/react-redux`.

If we move back to `@types/react-redux@5`, which corresponds to the version of `react-redux` we're using, the issue seems to be fixed. aebf545d68dc1d0b72a69d0d0f2a9510d1922d89 (from #36186) does that.

We should look at updating to latest type definitions in #32129 which upgrades `react-redux`.

**Comment by sirreal** [comment]
This can proceed independently of https://github.com/Automattic/wp-calypso/pull/36186.

**Pull request merged**
