### PR TITLE
Performance Profiler: Use an accordion for small screens in CrUX section

### PR DESCRIPTION
**Pull request by epeicher**
Resolves https://github.com/Automattic/dotcom-forge/issues/8911

## Proposed Changes

* Extract the `CoreWebVitalsDetails` to its own component so it can be reused in both, big and small (i.e. `Mobile`) screens
* Use `FoldableCard` component for small screens

https://github.com/user-attachments/assets/d47dd685-c936-4570-8b15-5529c867544f

## Why are these changes being made?

* For small screens, the current tab component do not fit so, foldable cards have been used according to the design

## Testing Instructions

* Navigate to the Speed Test tool with a result
* Resize the screen and check that the CrUX section changes from a Tab component to an Accordion component for small screens
* Check the behavior of the Accordion component works as expected
* Check the style of the headers of the Accordion matches Figma Iix1FFHIQdfECIXn5JKT5s-fi-4356_19874
* Check this related PR still works as expected https://github.com/Automattic/wp-calypso/pull/93997

**Note**: The responsive functionality of the content of the card will be handled as part of https://github.com/Automattic/wp-calypso/pull/94031

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Review by gavande1 — CHANGES_REQUESTED** [review]
Great work Roberto! Really loved it. Thanks!

The Wait time tab shown when it should not be shown. Can you take a look at it? We should show wait time only when INP scores are not available. 

CleanShot 2024-08-30 at 06 21 30@2x

**Comment by WBerredo** [comment]
> The Wait time tab shown when it should not be shown. Can you take a look at it? We should show wait time only when INP scores are not available. https://github.com/Automattic/wp-calypso/pull/93994/commits/faf8bd671d53adbaeabd5080db45f54b26339686

I've added the conditions already present on the desktop view:
* Remove tabs without data
* Only display TBT if INP is not available

| Full report  | without INP |
| ------------- | ------------- |
|CleanShot 2024-08-30 at 11 01 34@2x|CleanShot 2024-08-30 at 11 04 14@2x|

**Review by WBerredo — APPROVED** [review]
LGTM after the changes to hide/display sections.

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/16716888

Some locales (Hebrew, Japanese) have been temporarily machine-translated due to translator availability. All other translations are usually ready within a few days. Untranslated and machine-translated strings will be sent for translation next Monday and are expected to be completed by the following Friday.

Hi @epeicher, could you please edit the description of this PR and add a screenshot for our translators? Ideally it'd include all of the following strings:
- `%(displayName)s has improved over the past %(weeksToShow)d weeks`
- `%(displayName)s has declined over the past %(weeksToShow)d weeks`

Thank you in advance!

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/16716888).

**Pull request merged**
