### PR TITLE
Fix reader style issues

### PR DESCRIPTION
**Pull request by eoigal**
Fix Reader styling issues raised from internal CFT.

- [x] Gallery updates
image

- [x] Image with tags updates
CleanShot 2022-09-26 at 15 23 52@2x

- [x] Image without tags updates
CleanShot 2022-09-26 at 15 24 30@2x

- [x] Multiple image updates
CleanShot 2022-09-26 at 15 25 12@2x

- [x] No image updates
CleanShot 2022-09-26 at 15 25 38@2x

- [x] Follow page updates
CleanShot 2022-09-26 at 15 27 15@2x

- [x] Fix alignment for i _A8c only_
CleanShot 2022-09-26 at 15 42 36@2x

- [x] Update following icon everywhere
image

- [x] Update follow conversation icon
image

- [x] Fix following icon being bigger on the single post page
CleanShot 2022-09-26 at 15 41 22@2x

- [x]  Fix video card width/alignment
Screen Shot 2022-09-26 at 3 54 30 pm

- [x] Fix x-post alignment brought up by @jordesign 

## Remaining issues for @eoigal 

- [x] Need a default avatar when one isn't present
CleanShot 2022-09-26 at 15 42 12@2x

- [x] More menu updates
CleanShot 2022-09-26 at 15 26 11@2x

- [x] Update all icons to be 20 x 20

- [x] Fix [green square following icon](https://github.com/Automattic/wp-calypso/pull/68209#issuecomment-1257369307)

- [x] Share menu updates
CleanShot 2022-09-26 at 15 26 39@2x

## Remaining issues for @davemart-in 

- [x] Number of icon issues on single post page
image

- [x] Check out Facebook SVG
- [x] Swap conversation icon back out for follow conversation
- [x] Fix [two minor issues on conversations page](https://github.com/Automattic/wp-calypso/pull/68209#issuecomment-1257845699)
- [x] Fix [accessibility issues brought up here](https://github.com/Automattic/wp-calypso/pull/68209#issuecomment-1257839161)
- [x] Fix [like icon on post details page](https://github.com/Automattic/wp-calypso/pull/68209#issuecomment-1257831592)
- [x] Fix [like menu and icon styling](https://github.com/Automattic/wp-calypso/pull/68209#issuecomment-1257409868)
- [x] Fix [following hover/focus state styles](https://github.com/Automattic/wp-calypso/pull/68209#issuecomment-1257408442)
- [x] Fix [line clamping in FireFox](https://github.com/Automattic/wp-calypso/pull/68209#issuecomment-1257366889) 

- [x] Four image formatting on mobile web
image

- [x] Lack of full-screen layout on mobile web
image

- [x] Fix recommended post styles
image

On the reader post view I found a few issues:
- [x] the text indicator next to the "like" button is not quite vertically aligned
- [x] the "follow conversation" button has duplicate icons
- [x] the "suggested posts" section breaks out of the page/post container and goes right to the edge of the screen
Screen Shot 2022-09-28 at 3 32 25 pm

- [x] On the `/following/manage` page some padding is missing around the search box and page title
- [x] On the `/following/manage` page the follow icon is filled in all green when in the _followed_ state
Screen Shot 2022-09-28 at 3 57 09 pm

- [x] Need to make post actions on the full post page more consistent - from [here](http://calypso.localhost:3000/read/feeds/108002187/posts/4243841857)
Screenshot 2022-09-28 at 12 57 06

### Remaining issues for @roo2 

- [x] on the `/read/conversations` tab, icons in comments section are misaligned Screen Shot 2022-09-29 at 10 38 43 am. This is also visible on the comment section of the reader post view.
- [x] Active state for like icon and like counter are slightly different colors https://github.com/Automattic/wp-calypso/pull/68209#issuecomment-1261578430
- [x] Expanding "more" tags causes hamburger menu icon to be pushed outside of it's proper alignment https://github.com/Automattic/wp-calypso/pull/68209#issuecomment-1260408292 https://user-images.githubusercontent.com/22446385/192913542-b32d43f2-db3d-46a1-976b-1fe227870785.mov
- [x] On the tags page, there are two icons for "follow tag"
Screen Shot 2022-09-29 at 10 50 21 am
 https://github.com/Automattic/wp-calypso/pull/68209#issuecomment-1260408292

- [x] On the reader post details view comment section, the "follow conversation" icon is misaligned
Screen Shot 2022-09-29 at 10 57 04 am

- [ ] _Minor issue_ on the `/following/manage` screen, when opening the hamburger menu, the focus state box overflows from the menu 
Screen Shot 2022-09-29 at 11 14 22 am

### CODE REVIEW

**Comment by roo2** [comment]
There's an issue in Firefox with long text not being cut off, it looks like it's due to `-webkit-line-clamp` not being supported in FF.

Not neccessarily related to this pr, but still :) 
Screen Shot 2022-09-26 at 11 42 17 am

**Comment by roo2** [comment]
It looks like the ***following*** icon is still just a green square, is this already fixed somewhere else?

Again, not necessarily related to this PR!
Screen Shot 2022-09-26 at 11 47 34 am

**Comment by roo2** [comment]
Another issue that might or might not be related to this PR: 

the HR in the menu appears to not be shown.

Also as you mentioned in slack, the focus/hover state of the follow option seems to be not readable, Ollie recomended using white text in this state p1664152645001779/1663882982.218719-slack-C03NLNTPZ2T. It's affecting both following and not-following states


https://user-images.githubusercontent.com/22446385/192185039-98adb6ef-ab9b-4a00-a4a0-2a09b3e3184d.mov

**Comment by roo2** [comment]
Just a minor thing on the hover states for the follow/share icons, the text color is blue but the button goes green. Also, I think if any part of the text/button is hovered over, then both should go into the hover state. But as it's implemented now, either the text or the button will get the hover state but not both cc @ollierozdarz 

https://user-images.githubusercontent.com/22446385/192185454-34b3c07e-e73a-46a8-85f4-14f2b31c58b7.mov

**Comment by ollierozdarz** [comment]
> Just a minor thing on the hover states for the follow/share icons, the text color is blue but the button goes green. Also, I think if any part of the text/button is hovered over, then both should go into the hover state. But as it's implemented now, either the text or the button will get the hover state but not both cc @ollierozdarz
> 
>  Screen.Recording.2022-09-26.at.12.57.58.pm.mov

100%. We should aim for the hover to be consistent. Why are the links and hover Green? 🙂 Is it some to do with a themeing?

**Comment by roo2** [comment]
It looks like the favourite icon is broken on the post details page e.g. https://container-gracious-franklin.calypso.live/read/blogs/70056069/posts/2882

This is in FF, in chrome it doesn't seem to appear at all!

Screen Shot 2022-09-26 at 8 33 15 pm

**Comment by roo2** [comment]
More minor issues unrelated to this PR:

when tabbing through in chrome I noticed two issues:

* The "+x tags" button has no focus state
* The image (and next/prev image controls) are not tab-accessible

https://user-images.githubusercontent.com/22446385/192257248-49be85f0-b678-4f50-9645-832e0bcb4b7a.mov

**Comment by roo2** [comment]
On the `/read/conversations` tab there are two things, the hamburger menu is not right aligned properly (I assume it should be aligned with the right of the image) and the favourite icon is a little misaligned vertically.

This is a public conversation I'm not sure why I blanked it out 😂 

Screen Shot 2022-09-26 at 8 44 26 pm

**Comment by davemart-in** [comment]
> There's an issue in Firefox with long text not being cut off, it looks like it's due to `-webkit-line-clamp` not being supported in FF.
> 
> Not neccessarily related to this pr, but still :) Screen Shot 2022-09-26 at 11 42 17 am

@roo2 what version of FireFox are you using? I am unable to replicate this with FF 105.0.1 (64-bit).

**Comment by roo2** [comment]
> @roo2 what version of FireFox are you using? I am unable to replicate this with FF 105.0.1 (64-bit).

@davemart-in Mine is `104.0.1`, let's update it and see what happens with that issue

EDIT: I updated to 105.0.1 and still seeing the issue

**Comment by roo2** [comment]
@davemart-in I'm still seeing the issue on FF 105.0.1, do you see it on this feed? https://container-strange-mendeleev.calypso.live/read/feeds/77222666

**Comment by davemart-in** [comment]
> The image (and next/prev image controls) are not tab-accessible

Note: This is one that I was unable to figure out how to do.

**Comment by davemart-in** [comment]
> @davemart-in I'm still seeing the issue on FF 105.0.1, do you see it on this feed? https://container-strange-mendeleev.calypso.live/read/feeds/77222666

That was indeed helpful. Thanks @roo2! That should be fixed now.

**Comment by roo2** [comment]
Nice work on all of the fixes so far!

One thing is I think the four image layout isn't always coming across well depending on the shape of the images.

It's happening when we have some images that are taller than they are wide, you can see it on this feed `/read/feeds/77222666`

Screen Shot 2022-09-28 at 10 01 28 am

I think we want them to always cover the full space like this:
Screen Shot 2022-09-28 at 10 06 04 am

**Comment by davemart-in** [comment]
Thanks @roo2! I think I fixed it in: https://github.com/Automattic/wp-calypso/pull/68209/commits/bd624e7c5a392fbe21826492eb19aa545d392e4a

**Comment by roo2** [comment]
another very small thing, when a post has been liked, the star is green but the number indicator next to it is still blue. It's a little hard to tell here without looking closely ;) I remember we talked about something like this before, I think it was all supposed to be one color, but not sure if it was to be green or blue?
Screen Shot 2022-09-28 at 3 04 13 pm

**Comment by roo2** [comment]
The `/activities/likes` page seems to have two issues:

1) There are two follow indicators, I think only one is necessary
2) In Firefox, the share icon disappears when moused over (chrome is fine)

https://user-images.githubusercontent.com/22446385/192694141-fc2c7f0b-434f-4b15-8327-be6178e979da.mov

**Comment by roo2** [comment]
On the "tags" page e.g. `/tag/interview` I found two things:

1) The icons seem to be duplicated near the "following tag" button
2) When expanding the tags, the hamburger menu can get pushed out of alignment

https://user-images.githubusercontent.com/22446385/192695311-74547ebe-a5f3-4e69-93df-03a50d6755f3.mov

**Comment by roo2** [comment]
On the reader post view I found a few issues:
1) the text indicator next to the "like" button is not quite vertically aligned
2) the "follow conversation" button has duplicate icons
3) the "suggested posts" section breaks out of the page/post container and goes right to the edge of the screen
Screen Shot 2022-09-28 at 3 32 25 pm

**Comment by roo2** [comment]
Also on the post view, there are a few errors in mobile

1) The icons in the header are too small and spaced out poorly
2) There is a gap in the header (existing issue)
3) The follow conversation icon is duplicated
4) The star icon is poorly aligned
Screen Shot 2022-09-28 at 3 41 10 pm

For contrast here's the current state:
Screen Shot 2022-09-28 at 3 44 30 pm

**Comment by roo2** [comment]
@davemart-in, related to the four image issue that you fixed, there seems to be something similar happening for two image layouts in some cases, the feed `/read/feeds/101831245` has many examples of two image layouts where the images are not extending all the way over the available area
Screen Shot 2022-09-28 at 3 52 16 pm

**Comment by roo2** [comment]
on the `/following/manage` page I found _the following_
1) some padding is missing around the search box and page title
2) The follow icon is filled in all green when in the _followed_ state

Screen Shot 2022-09-28 at 3 57 09 pm

**Comment by eoigal** [comment]
> another very small thing, when a post has been liked, the star is green but the number indicator next to it is still blue. It's a little hard to tell here without looking closely ;) I remember we talked about something like this before, I think it was all supposed to be one color, but not sure if it was to be green or blue? Screen Shot 2022-09-28 at 3 04 13 pm

Can't replicate this. This is what I see.
Screenshot 2022-09-28 at 09 45 10

 Any tips on replicating?

**Comment by eoigal** [comment]
Need to make post actions on the full post page more consistent - from [here](http://calypso.localhost:3000/read/feeds/108002187/posts/4243841857)
Screenshot 2022-09-28 at 12 57 06

**Comment by roo2** [comment]
OOPS didn't post this one yesterday!

On the search page, before a query has been entered, there is a strange behavior:
`/read/search?q=`
1) it looks like fixed widths haven't been set and every post is a different width
2) after scrolling about half way down the page, the follow icon turns fully green 🤡

https://user-images.githubusercontent.com/22446385/192700507-4b50da73-cc26-4ba4-9790-a2f9f151147b.mov

EDIT: but it's been fixed already 😅

**Comment by roo2** [comment]
> > another very small thing, when a post has been liked, the star is green but the number indicator next to it is still blue. It's a little hard to tell here without looking closely ;) I remember we talked about something like this before, I think it was all supposed to be one color, but not sure if it was to be green or blue? Screen Shot 2022-09-28 at 3 04 13 pm
> 
> Can't replicate this. This is what I see. Screenshot 2022-09-28 at 09 45 10
> 
> Any tips on replicating?

For me it seems to happen on every feed screen I tested `/read` `/read/list/erupenkman40a8ccom/test-list` for example. I'm testing in chrome 106.0.5249.61


https://user-images.githubusercontent.com/22446385/192907704-3d5b5a6f-6262-4901-8c35-1b6f3a77e23c.mov

**Comment by roo2** [comment]
I've gone through, retested and added outstanding issues I could find as checklist items in the description

**Comment by creativecoder** [comment]
To connect the dots from slack, the varying icon color is because of the inline stroke value here:
https://github.com/Automattic/wp-calypso/blob/5796544cc4d61f79304555bf716738380f58f84e/client/reader/components/icons/like-icon.jsx#L23

It looks like the current like icon uses `--color-primary` for the color (rather than `--color-link`). I'm not sure if best practice here is to set this inline or use css.

**Comment by roo2** [comment]
I worked on css for those tricky like buttons today. Where I got to is that the comment like buttons in the post view and the `/read/conversations` tab both use the old like animation, the Like buttons in the reader cards and post sidebar on the other hand use the new simpler animation.
It's still pretty messy, but that's where I got to today!

https://user-images.githubusercontent.com/22446385/193212349-a9c95975-72eb-431a-b02f-ba775fb16378.mov

**Comment by roo2** [comment]
On the issue with the hamburger menu jumping out of the container when the full tag list is expanded:

I couldn't get it working with the horizontal scrolling approach, but I got this working which I think is a bit simpler, it just expands the height of the tag list and wraps onto multiple lines if necessary.

https://user-images.githubusercontent.com/22446385/193723688-5c5bb2b0-1b5d-433b-83ae-f172d9db4279.mov

**Comment by roo2** [comment]
@eoigal The issue I found on the manage subscriptions page was caused by adding width:100% in https://github.com/Automattic/wp-calypso/commit/2a5a4f11bf27328df53a09be35c10ad0b305d42e#diff-17908cc9fc7fcbe3b00523d0235bc12eb0c75acfc4e7ad4fe211cbaf520cf5a2R23. I retested the hamburger menus on the post lists and they seem to be working as expected, but I'm not sure if `width:100%` was needed for anything else.

**Comment by roo2** [comment]
Ok, the only issue I'm aware of still outstanding is that the stars on the comment section are the old style, wheras everywhere else they are the new style. I personally think we could go live with that as it is.

https://user-images.githubusercontent.com/22446385/193212349-a9c95975-72eb-431a-b02f-ba775fb16378.mov

**Comment by eoigal** [comment]
I've updated this PR to use the new reader star icon in comments section as it was still using the gridicons like icon. 
Also tidied up the hover/active states for this icon and also in the full post below;

Screenshot 2022-10-04 at 11 30 57
Screenshot 2022-10-04 at 11 30 50
Screenshot 2022-10-04 at 11 30 46

**Pull request merged**
