### PR TITLE
Draft: display "author" gravatar if it's a multiauthor blog.

### PR DESCRIPTION
**Pull request by mtias**
image

If site is multiauthor, and user selects the "Everyone" filter in posts view, render a gravatar next to the draft title.

Test live: https://calypso.live/?branch=add/author-to-multiauthor-sites-drafts

### CODE REVIEW

**Comment by aduth** [comment]
I see the Gravatar even on a single user site.

single-user

**Comment by mtias** [comment]
@aduth should be fixed.

**Comment by aduth** [comment]
For my Jetpack site, the Gravatar's indefinitely show as loading. Can you reproduce?

author

**Comment by mtias** [comment]
I can't, that's strange.

**Comment by aduth** [comment]
@mtias Seems to be a very edge-case where `author` on a post is null. In general we don't handle this well (e.g. [schema invalidation on `null` author](https://github.com/Automattic/wp-calypso/blob/2243fef6570bed6bc7689f666c1c1e4e9d31cde8/client/state/posts/schema.js#L12)). Sounds like an issue that shouldn't be occurring from our REST API, perhaps with authors being deleted on the Jetpack site (speculating). In any case, might want to be overly cautious? Or allow it to be painful to force ourselves to fix the root cause 😉

**Comment by aduth** [comment]
In any case, confirmed that this worked for two of my non-Jetpack test sites, one multi-author (Gravatar only shown on Everyone filter) and one single-author (Gravatar not shown). 👍

**Comment by mtias** [comment]
Thanks for looking, let's see what we can do about that null thing later.

**Pull request merged**
