### PR TITLE
Pre-commit gridicons check

### PR DESCRIPTION
**Pull request by johnHackworth**
My hack day project: A script that gets executed in the pre-commit, checks if there's any gridicon in the commited files, and rejects it if it's using a non-standard size.

image

How to test:
=========
1. Create a test branch 
2. Modify any file to include a gridicon with a non standard size (neither 12, 18, 24, 36, 48, 54 or 72px)
3. Try to commit the change... you should not be allowed to do it and you should see an error similar to the upper screenshot (if you are doing it by command line)

ping @alternatekev @MichaelArestad @rickybanister

### CODE REVIEW

**Comment by jasmussen** [comment]
Yay! Thank you for doing this. Our icons will look prettier for it.

**Comment by rickybanister** [comment]
Awesome @johnHackworth!

**Comment by folletto** [comment]
> rejects it if it's using a non-standard size.

I don't think it should reject, tbh. Warning, yes. Rejection, no.

**Comment by jasmussen** [comment]
> I don't think it should reject, tbh. Warning, yes. Rejection, no.

I kind of think it *should* reject. Not only that, but warn if using 18px, that that's only a last resort size. Any reason why the check should be lenient here? I know I'm ... hmm... "pixel damaged goods" :D — but this rejection sounds like just what the doctor ordered, as far as crisp icons go.

**Comment by rickybanister** [comment]
Woudn't it be just like our tests? If a test fails you can only push by adding `--no-verify` ? Wouldn't that be the way to go?

**Comment by folletto** [comment]
Awareness is good, blind rejection isn't in my view. I totally see instances where we _choose_ to do different sizes, for any reason, and this will just frustrate that.

Seeing a warning its enough to fix the _"ah, right, I forgot"_ part, with no frustration added.

**Comment by rickybanister** [comment]
To be clear, I feel most of the `16px` gridicon sizes aren't due to need, but simply mistakes. The failure would make the person think before committing. Also we may want to suggest/require any non-standard sizes to have a helpful comment in the code explaining why it needed to be that size.

**Comment by johnHackworth** [comment]
What do you all think about using an explicit prop when using a non
standard size? Something like `<gridicon size={ 19} noStandard>` . that way
we could tell both to our automatic tools and to other contributors that
odd size is not an error but something done on purpoise

To be clear, I feel most of the 16px gridicon sizes aren't due to need, but
simply mistakes. The failure would make the person think before committing.
Also we may want to suggest/require any non-standard sizes to have a
helpful comment in the code explaining why it needed to be that size.

—
Reply to this email directly or view it on GitHub
<https://github.com/Automattic/wp-calypso/pull/1412#issuecomment-163324108>.

**Comment by alternatekev** [comment]
My guess is most of the 16px Gridicons are simply Noticons replacements since that’s the size we used there. I committed and removed some `Gridicon`-level enforcement of the icon grids. It was deemed a little too strict and that it clamped down on something that people may want to sanely override (like you're saying). 

Would the prop work in such a way as to throw an error in the tools if it doesn’t exist? That could be a good way to get the icons moved over so I’d be good with that.

**Comment by kellychoffman** [comment]
Thanks for doing this!

**Comment by johnHackworth** [comment]
@alternatekev @folletto @jasmussen @rickybanister 

My idea would be something like this:
`<Gridicon size={ 12 }>` -> no warning, no error (standard size)

`<Gridicon size={ 13 }>` -> error, rejected commit

`<Gridicon size={ 13 } nonStandard>` -> no error, no warning (non-standard, but marked as such)

`<Gridicon size={ 12 } nonStandard>` -> no error, but a warning ("standard size marked as nonStandard... are you sure?")

That way, there would be a way saying "yeah, I know I shouldn't be using this size here, but it's on purpose". Ideally, any instance of 'nonStandandard' should be accompanied with a comment telling why we need that odd size there.

(by the way, "nonStandard" as prop name sounds awful... if someone can figure a better name, I would be glad to change it for something else :D)

**Comment by folletto** [comment]
> (by the way, "nonStandard" as prop name sounds awful... if someone can figure a better name, I would be glad to change it for something else :D)

....`!important`? :D

The outline above sounds good to me. The important bit is not to add a frustration when our objective is to fix obvious and banal oversights. That solution does that. ;)

**Comment by johnHackworth** [comment]
I've implemented the `nonStandard` prop:

Now it works like this. In this example, I'm trying to commit a file with this four Gridicons:
```
				<Gridicon size={ 12 } icon="external" />
				<Gridicon nonStandard size={ 14 } icon="external" />
				<Gridicon size={ 14 } icon="external" />
				<Gridicon nonStandard size={ 12 } icon="external" />
```
And the result:

image

One fail (size 14, without 'nonStandard') and one warning (size 12 with 'nonStandard')

**Comment by aduth** [comment]
Cool idea :smile: One problem with the approach is that it doesn't account for line breaks. For example, the following will pass validation:

```jsx
return (
	<Gridicon
		size={ 15 }
		className="foo__icon" />
);
```

Proper code analysis isn't easy and may very well be outside the scope of what you're trying to achieve here. If that's a road you want to go down, consider passing the code through [`babel.transform`](https://babeljs.io/docs/usage/api/#babel-transform-code-options-), validating against the [AST](https://en.wikipedia.org/wiki/Abstract_syntax_tree) result.

**Comment by johnHackworth** [comment]
ouch, you're right, @aduth !!

Well, this PR should only be considered a first approach, of course... At least we would be handling the one-line scenarios :dancer: 

I'll take a look to `babel.transform` and see how we can improve this in future PRs :)

**Comment by johnHackworth** [comment]
After @aduth comments, I've changed the way I parse the files to support multiline gridicons & (another failing case) multiple gridicons in the same file. It's not yet anywhere related to a proper code analysis tool, but improves the first version :)

Now, with this test case:
```
				<Gridicon size={ 12 } icon="external" />
				<Gridicon nonStandard size={ 14 } icon="external" />
				<Gridicon size={ 14 } icon="external" />
				<Gridicon nonStandard size={ 12 } icon="external" />
				<Gridicon
					nonStandard
					size={ 33 }
					icon="external" />
				<Gridicon
					size={ 33 }
					icon="external" />
				<Gridicon size={ 18 } icon="external" /><Gridicon size={ 9 } icon="external" />
```
You get this result:
image



image

**Comment by alternatekev** [comment]
@johnHackworth The `nonStandard` prop is referring to size, so perhaps we do something with `nonStandardSize` ? I can't really think of anything better.

**Comment by johnHackworth** [comment]
@alternatekev that's a pretty good point, yeah... I'll change it to make clear that it references only the size

**Comment by enejb** [comment]
I think this is a great improvement. Thanks for doing this! 
It worked as described and as expected for me! :shipit:

**Pull request merged**
