### PR TITLE
Add INSTALL_PURCHASED_PLUGINS feature

### PR DESCRIPTION
**Pull request by mreishus**
#### Proposed Changes

* Buying marketplace plugins is now gated behind the new `INSTALL_PURCHASED_PLUGINS` feature, instead of `INSTALL_PLUGINS`.
  * The backend has already been updated to provide `INSTALL_PURCHASED_PLUGINS` to the business, ecommerce, and pro plans.

#### Testing Instructions

* Visit `/plugins/<site>` on a variety of simple sites: Pro, Business, Ecommerce, Starter, Free.
  * The Pro, Business and Ecommerce plans should be able to buy and install plugins.
  * Starter and Free should not.
  * **Behavior should be the same as production.**

Related to D82978-code
Related to https://github.com/Automattic/wp-calypso/issues/58998

### CODE REVIEW

**Comment by obenland** [comment]
To enable Atomic we might have to add the feature to plans in `calypso-products` as well, like [here](https://github.com/Automattic/wp-calypso/blob/trunk/packages/calypso-products/src/plans-list.tsx#L488).

**Comment by mreishus** [comment]
Does this help or does it make things more confusing?

[add/install-purchased-plugins 701c0acb3f] Rename FEATURE_INSTALL_PURCHASED_PLUGINS -> WPCOM_FEATURES_INSTALL_PURCHASED_PLUGINS

Technically it follows our guidelines, but it ends up with us having these two constants: `FEATURE_INSTALL_PLUGINS` and `WPCOM_FEATURES_INSTALL_PURCHASED_PLUGINS`

**Comment by obenland** [comment]
I think that's fine

**Comment by obenland** [comment]
We'd still need to add the ATOMIC feature to the starter plan in Calypso, too, no?

**Comment by mreishus** [comment]
Hm, yes. Should we split this PR into two steps [Add INSTALL_PURCHASED_PLUGINS, then add it to starter] also?

That would mean evaluating this one such that the non-starter plans continue to work the same

**Comment by obenland** [comment]
yes I think that makes sense

**Comment by mreishus** [comment]
The e2e test is failing on the 'my plans' tab, which looks pretty suspicious. Trying to see if I can recreate it.

**Comment by obenland** [comment]
This looks like it needs to be updated too:
* https://github.com/Automattic/wp-calypso/blob/623ed046383c6f2cac99aa446cd3214223f53bd4/client/my-sites/plugins/plugin-install-button/index.jsx#L319
* https://github.com/Automattic/wp-calypso/blob/c3bf92be6ca13cf261e82da21a9b5a8a5537d618/client/state/marketplace/selectors.ts#L21 (incl function docs)

**Review by obenland — APPROVED** [review]
Let's get this in!

**Pull request merged**
