### PR TITLE
Checkout: Replace "Total savings" with "Coupon" and "Credits" (4)

### LINKED ISSUE #43168: Checkout: "Total savings" should not have a delete button unless a coupon is in the cart
Originally reported in https://github.com/Automattic/wp-calypso/pull/43126#pullrequestreview-428338755

### LINKED ISSUE #43353: Composite checkout: Incorrect display when paying with credits
### Steps to reproduce

Add some credits to your account (enough to cover a full purchase) and then go to checkout.  You get this:

full-credits

This is confusing to begin with (since it's not clear what the savings represent) but as the screenshot shows, they also show up as savings **even when you choose to pay with an actual payment method (e.g., a credit card) rather than with credits.**

Not shown in the screenshot, but if you edit the order you can also try to remove the savings via the trash icon and (not surprisingly) it doesn't work.

Meanwhile, the same thing for partial credits looks like this:

partial-credits

The numbers are correct this time, but again, there's no indication that the savings are due to credits. If you edit the order, the information about credits being used does show up there, though.

#### What I expected

1. Some kind of indication that the savings were due to WordPress.com credits (similar to how it shows you an indication when your savings are due to a coupon).
2. The savings go away if I'm not actually paying by credits.
3. No trash icon next to the credits when editing the order (if they're not actually removable).

### PR DESCRIPTION
**Pull request by sirbrillig**
#### Changes proposed in this Pull Request

This modifies the review step in new checkout so that rather than the "Total savings" line item (which is confusing since it represents so many different things), we re-add a "Coupon" line item, which now has a correct amount thanks to D45080-code, and add a "Credits" line item for any credits the account has.

new-coupon-item

This is one step toward the changes described in https://github.com/Automattic/wp-calypso/issues/43353 although there are more tasks to be done.

Fixes https://github.com/Automattic/wp-calypso/issues/43168 
Fixes https://github.com/Automattic/wp-calypso/issues/43353

#### Testing instructions

1. Use an account that already has a plan.
1. Add an upgraded plan to your cart and visit checkout. This will create a non-coupon discount for the cart item (a proration).
1. Verify that the coupon is not displayed.
1. Verify that the credits are not displayed.
1. Add a few credits to your account and reload.
1. Verify that the credits are displayed.
1. Add a coupon to your cart.
1. Verify that the coupon is displayed and shows only the discount caused by the coupon, not the proration, and not the credits.

### CODE REVIEW

**Comment by sirbrillig** [comment]
I ran into some issues when there are no credits. Fixing...

**Comment by michaeldcain** [comment]
@sirbrillig: should this include the change that leaves "Total Savings" in the sidebar, or is that being taken care of in a different PR? /cc @fditrapani

**Comment by michaeldcain** [comment]
Nevermind, I think this is a step in the plan you [laid out here](https://github.com/Automattic/wp-calypso/issues/43353#issuecomment-645628020).

**Comment by sirbrillig** [comment]
Yeah, it requires that we make the total savings value correct first, and there's some [tricky edge cases](https://github.com/Automattic/wp-calypso/issues/43353) around what happens at 100% credits. The card is [here](https://github.com/Automattic/wp-calypso/projects/89#card-40287445).

**Comment by sirbrillig** [comment]
Two things that need to be fixed here:

- [ ] The "WordPress.com Credits" pseudo-line-item that is added by the server when you have partial credits is a duplicate of the "Credits" line item we add here, so we need to strip the server generated one out.
- [ ] The full credits payment method label and payment button displays the total amount of credits, which, currently in this PR, is prefixed by a minus sign. We need to display the positive amount.

**Comment by michaeldcain** [comment]
This is close. The coupon/total savings and partial credits with/without coupon parts work as expected, but I think when full credits are available, we should either be hiding the new credit line item or setting it to be equal to the amount of credits that will be used:

Partial Credit | Full Credit
------------ | -------------
partial-credits | full-credits

**Comment by michaeldcain** [comment]
> setting it to be equal to the amount of credits that will be used

My thinking here is that the line items (including credits) in the review step are cart purchase-specific, and the credits in payment methods are more wallet-specific. Regardless, I think hiding the line item in this case will be the easier route.

**Comment by sirbrillig** [comment]
> My thinking here is that the line items (including credits) in the review step are cart purchase-specific, and the credits in payment methods are more wallet-specific. Regardless, I think hiding the line item in this case will be the easier route.

I see what you're saying, but this is a little tricky because we have this feature (not present in old checkout) that lets you chose a different payment method when you have full credits available.

To be honest, I think that feature is causing way more problems than it's solving. The original feature request was just to allow it for a12s anyway, so I'm going to disable that option instead, mirroring old checkout. I think we should re-enable it, but only once we've given it some attention and fixed some of the edge cases that it can cause.

**Comment by sirbrillig** [comment]
@michaeldcain how does that look now?

**Review by michaeldcain — APPROVED** [review]
Works as described - LGTM.

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/3932059

Thank you @sirbrillig for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/3932059).

**Pull request merged**
