### PR TITLE
Experiment: Extract signup as separate entrypoint

### PR DESCRIPTION
**Pull request by jsnajdr**
Signup is very different from the rest of Calypso. It has a different layout (no masterbar) and works only with a very limited set of data (mainly the Signup stores). Navigation from Signup to another part of Calypso is always a full page reload, because it involves an optional WP.com login step.

This PR creates a separate landing page for signup, with a hand-picked Redux store and custom `Layout` component. I was able to create a new site using it. Let's see what e2e tests tell us.

**Open problems:**
Redux state is not persisted yet and page reload therefore doesn't resume the signup flow. Because the reducer is very different, it makes sense to persist it to a different IndexedDB database (`calypso-signup` instead of `calypso`) or a different database key (`redux-state-signup-${userId}` instead of `redux-state-${userId}`).

A few other parts of Calypso use the Signup reducer. Namely, Jetpack Connect uses it to store and retrieve the site topic and site title (see #32020 by @tyxla).

### CODE REVIEW

**Comment by sgomes** [comment]
Very interesting experiment, thank you @jsnajdr ! I'm eagerly keeping my eyes on this one 😁 

I'm curious as to why the `signup` section picks up close to the entire size of the `build` chunk, at the moment. From what you described of the experiment, it shouldn't pick up anything close to that, right?

**Comment by spen** [comment]
Awesome! Thanks for this @jsnajdr! I'm at a meet-up for the rest of the week so can't promise an immediate review, but this sounds like it'll have a great impact so it's top of my list!

**Comment by spen** [comment]
[Experiment: Extract signup as separate entrypoint](https://trello.com/c/JeHSS5VH/159-experiment-extract-signup-as-separate-entrypoint)

**Comment by jsnajdr** [comment]
I pushed an useful patch that gives the webpack entrypoints better names:
- `build` -> `entry-main`
- `signup` -> `entry-signup`
- `domainsLanding` -> `entry-domains-landing`

That will become more helpful as we add more entrypoints.

> I'm curious as to why the signup section picks up close to the entire size of the build chunk, at the moment. From what you described of the experiment, it shouldn't pick up anything close to that, right?

@sgomes After the entrypoint rename, the ICFY comment is easier to read. Before this PR, you needed to load the `build` and `signup` chunk groups to render Signup. That's 1647 + 200 = 1867 parsed kilobytes of JS. Now you need just the single `entry-signup` chunk group. That's just 1158 parsed kileobytes. Decrease of 710 kB.

The `build` chunk itself (renamed to `entry-main` lost just 20 kB. That's the `signup` reducer.

> I'm at a meet-up for the rest of the week so can't promise an immediate review, but this sounds like it'll have a great impact so it's top of my list!

@spen I'm glad you like it :) It's still a very rough work in progress and it will take some time to fix all e2e tests and open issues and make it reviewable and mergeable. No need to hurry.
I think that with some Cart Store module reorg, we can make `entry-signup` even smaller.

**Comment by sirreal** [comment]
@jsnajdr I believe this was superseded by other work and is no longer relevant. Can this be closed?

**Comment by jsnajdr** [comment]
@sirreal Yes, I don't think I'll ever finish and merge this. Some of the fixes (in sticky panel or the `handleRenewNowClick` move) still look like worthy PRs. I'll try to merge them separately and then close this one.

**Comment by jsnajdr** [comment]
Soo, the `handleRenewNowClick` fix is no longer interesting -- the relevant code has been rewritten in the meantime. And the `StickyPanel` fix is proposed separately in #48046.

Thanks @sirreal for your work on triaging and cleaning up old PRs.

**Pull request closed without merging**
