### PR TITLE
People: filtering users by role (reimplementation)

### PR DESCRIPTION
**Pull request by markryall**
This is a replacement for #8746 (which should be considered a spike implementation for the purpose of exploring different design options and obtaining feedback).

I now plan to reimplement the feature from scratch adding test coverage around the people feature and avoiding some of the complexity in components introduced by the initial implementation.

Here are the aspects of the initial implementation that I think are reasonable (and i'd start with again):

* make the change to the `client/lib/mixins/url-search` mixin to allow an optional base url to be used instead of window.location.href (perhaps this should be a separate PR).
* add the generic `/people/team/role/:role` and `/people/team/role/:role/:site_id` routes (binding to the existing people controller).

Here are some things I will do differently:

* Create a new component for RoleSelect dropdown navigation (instead of just adding completel new behaviour to the existing component).
* Create some helper functions for the complicated branching logic to determine display results and text in `client/my-sites/people/team-list/team.jsx`.

### CODE REVIEW

**Comment by mtias** [comment]
@ebinnion who would be best from the people that worked on this to help get it merged?

**Comment by ebinnion** [comment]
This PR is just a development config flag, so I'm fine merging. Are there PRs for the other refactoring?

**Comment by mtias** [comment]
Yes, sorry, I thought I was commenting on the original PR. @markryall did you get around to submitting other PRs for #8746?

**Comment by markryall** [comment]
Hi @mtias @ebinnion !

I'm about to get back onto completing #9266 and subsequent similar PRs.

This one could be merged I guess as a very modest first merge to master :) It'd be hard to come up with a smaller PR than this.

**Pull request merged**
