### PR TITLE
Paid Stats: Add expandable feature list to upsell

### PR DESCRIPTION
**Pull request by jwebbdev**
Related to https://github.com/Automattic/jetpack-roadmap/issues/2056

## Proposed Changes

* Update design of Upsell to match new design
* Update the feature line for Stats at checkout
* Fix stats chart lines when navigating from home to stats

image

## Testing Instructions

* Navigate to a free site created after Dec 11 in the live branch
* Compare the Upsell to the video in the comments below
* Check that checkout features properly display 'Detailed traffic stats beyond the last 7 days and site insights'
* Check that stats chart is not break out of it's boundaries when navigating from Home to Stats page.

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
    - [ ] For UI changes, have we tested the change in various languages (for example, ES, PT, FR, or DE)? The length of text and words vary significantly between languages. 
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Comment by ederrengifo** [comment]
Details about this adjustments in this [Figma file](https://www.figma.com/design/b6zzlsVOeDRw4Z2pd8NIDJ/Stats%3A-Upgrade-hook-for-WordPress.com?node-id=4757-6901). Here a quick preview of the ideal expandable interactions ([Prototype](https://www.figma.com/proto/b6zzlsVOeDRw4Z2pd8NIDJ/Stats%3A-Upgrade-hook-for-WordPress.com?page-id=4757%3A6901&node-id=4757-6902&node-type=canvas&viewport=-786%2C496%2C0.34&t=fupDedm2zhd6zHXe-9&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=4757%3A6902&show-proto-sidebar=1))

https://github.com/user-attachments/assets/0ca89f8c-a9cc-4c57-9b63-e3f5a9210e39

Updated images attached:
[images-stats-update.zip](https://github.com/user-attachments/files/18102737/images-stats-update.zip)

I think this only should work for desktop, we can simplify it for mobile and show a static image. Let me know if this works!

**Review by Initsogar — APPROVED** [review]
Looks good to me 👍🏽

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/17060272

Some locales (Hebrew, Japanese) have been temporarily machine-translated due to translator availability. All other translations are usually ready within a few days. Untranslated and machine-translated strings will be sent for translation next Monday and are expected to be completed by the following Friday.

Thank you @jwebbdev for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/17060272).

**Pull request merged**
