### PR TITLE
Progress Bar: Update pulsing styles

### PR DESCRIPTION
**Pull request by ebinnion**
In #7258, we added an `isPulsing` property that adds an animation to the blue progress bar while performing an action. This is especially useful for actions that may take several minutes (like syncing a site).

This PR aims to update those styles. Here is a demo.

progress_bar_pulsing

I still need to track down an issue with how the styles look when little progress has been made. The ribbons appear too close together.

screen shot 2016-08-09 at 9 43 20 pm

To test:

- Checkout `update/progress-bar-pulse-styles` branch
- Go to `/settings/general/$site` where `$site` is on the latest `branch-4.2`
- Click "Perform full sync" button

cc @rickybanister @folletto 

Also, @folletto, I wasn't sure how to match the color in your [codepen](http://codepen.io/folletto/full/grBPoW/), so I went with `darken( $blue-wordpress, 5% )`. I can update this if it's something different.

Test live: https://calypso.live/?branch=update/progress-bar-pulse-styles

### CODE REVIEW

**Comment by rickybanister** [comment]
I suppose ideally we 'crop' the ribbon with a container instead of squishing it at small widths.

As for color, perhaps we can take a hint from the masterbar's colors. The hover state is `lighten( $blue-wordpress, 5% )`

**Comment by folletto** [comment]
Ah yes, sorry. I did `%` to test but I didn't revert to `px` later. :(
Here's the [updated codepen](http://codepen.io/folletto/pen/grBPoW), with changed units and animation duration.

For the colors I used a darkened `$blue-wordpress`, but we can also use the masterbar one as Rick suggested:

* `$blue-wordpress`
* `lighten( $blue-wordpress, 5% )`

**Comment by ebinnion** [comment]
Thanks @folletto for the assist! PR has been updated.

progress-bar-demo

**Comment by rickybanister** [comment]
That's beautiful! Ship it.

**Comment by mtias** [comment]
@ebinnion can we add this state as an example to devdocs?

**Comment by ebinnion** [comment]
@mtias Done. #7584

**Pull request merged**
