### PR TITLE
Signup: Use inline SVGs for the design step to improve loading time.

### PR DESCRIPTION
**Pull request by kwight**

### CODE REVIEW

**Comment by kwight** [comment]
cc/ @shaunandrews @melchoyce @ehg

**Comment by melchoyce** [comment]
Looks nice and crisp on my laptop. Still works well responsively. There's some extra space on the bottom, though, between the SVG and the label: 

screen shot 2016-06-02 at 3 17 02 pm

Can't figure out where it's coming from.

**Comment by kwight** [comment]
@melchoyce Oh, well spotted! Fixed in ca5f344cdca81fe2a21f71dedf8ef469fb1a2826.

**Comment by melchoyce** [comment]
👍

**Pull request merged**
