### PR TITLE
Docs: Remove exception for array and object key spacing

### PR DESCRIPTION
**Pull request by aduth**
This pull request seeks to remove an exception detailed in our JavaScript coding standards which allows for exceptions in our array and object spacing guideline when using numbers or string literals.

>For consistency with our PHP standards, do not include a space around string literals or integers used as key values in array notation

I propose we remove this exception for the following reasons:

- It's noted the exception is for consistency with the WordPress coding standards, but we have already diverged from this standards with our [spacing guidelines on function arguments](https://github.com/Automattic/wp-calypso/blob/master/docs/coding-guidelines/javascript.md#arrays-and-function-calls) (ref: 1683-gh-calypso-pre-oss)
- By their nature, any exception to a rule is a barrier in that they prescribe additional burdens of knowledge
- We can more easily leverage existing ESLint rules that do not support differentiating on the type of array or object key
- Exempting on string/integers is completely arbitrary (though I welcome dissenting arguments)

Not only does this pull request remove the rule from our documentation, but it also enables related rules in our ESLint configuration:

- [`computed-property-spacing`](http://eslint.org/docs/rules/computed-property-spacing)
- [`object-curly-spacing`](http://eslint.org/docs/rules/object-curly-spacing)
- [`array-bracket-spacing`](http://eslint.org/docs/rules/array-bracket-spacing)

### CODE REVIEW

**Comment by stephanethomas** [comment]
I like that a lot. First because I never remember when we should add spaces or not. And second because I'll finally be able to format code correctly with WebStorm.

**Comment by nb** [comment]
👍

**Comment by nylen** [comment]
I think the reasoning for the original rule is something like "the index into this array is a simple expression that doesn't take much brainpower to evaluate, so it doesn't need its own spacing".

Still, being consistent and being able to use automated tools makes even more sense to me 👍

**Comment by aduth** [comment]
Thanks for the comments. Seems to be unanimously favored, so moving ahead with merge.

**Pull request merged**
