### PR TITLE
Jetpack Connect: add a separate notice for WP.com sites purchasing Search

### PR DESCRIPTION
**Pull request by AnnaMag**
Atm, Search is a Jetpack product, but it will become available for WP.com sites in the future. 

#### Changes proposed in this Pull Request

* Here,  we add a notice when users arrive at the connection step following Search purchase flow and input their WP.com site address. 

#### Testing instructions

* start at the url input form of the JPC flow: `/jetpack/connect/jetpack_search`  (try with parameters e.g. being redirected from the LP `?cta_id=landing-page-search-primary-cta&cta_from=upgrade_search`
* input a WP.com site
* verify that the notice appears:

wpcomsearch

### CODE REVIEW

**Comment by kristastevens** [comment]
Hello! Here are some small copy suggestions to avoid a little repetition in the headline of the notice and the body copy. 

I suggest changing the headline to read:

> We're setting up Jetpack

Which tees up the next line (minor mods here:)

> We're installing the Jetpack plugin so that WordPress.com can communicate with your self-hosted WordPress site. 

I'd suggest one minor change to the dismissible notice: 

> Good news! Jetpack's Search feature is coming soon to WordPress.com sites.

**Comment by AnnaMag** [comment]
Thank you! Applied the changes to the dismissible notice (the remaining ones change JPC itself, which is beyond the scope of this PR).

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/3361892

Thank you @AnnaMag for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/3361892).

**Pull request merged**
