### PR TITLE
Style selection: Hide legacy designs that are variations of another design

### PR DESCRIPTION
**Pull request by fushar**
#### Proposed Changes

This PR hides "legacy" designs that are variations of another design, when the `signup/design-picker-style-selection` flag is enabled. This is because such designs are achievable by selecting the correct style variation from the "parent" design.

Currently, such designs are only Twenty Twenty Two "variation" designs.

#### Testing Instructions

* Go to http://calypso.localhost:3000/setup/designSetup?siteSlug=<your site slug>
* Advance until the design picker step
* Verify that you don't see Twenty Twenty Two variations.

#### Pre-merge Checklist

- [x] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [x] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?

Related to #67137

### CODE REVIEW

**Comment by taipeicoder** [comment]
Should we also hide Quadrat and Geologist variations?
Also, I noticed that Quadrat and Geologist base themes are not present in the design picker, curious to know why is that, and  how can we show them.

**Comment by fushar** [comment]
Yeah, ideally we have Quadrat and Geologist "base" themes with style variations. Not sure why, maybe they are not ready? In any case, the code will handle this automatically; no changes required on this PR.

**Comment by arthur791004** [comment]
> I noticed that Quadrat and Geologist base themes are not present in the design picker

I thought the reason is we only query the first 50 themes, so these two are not present. We need to increase the number of themes because we might have more and more themes with `auto-loading-homepage,full-site-editing` tags

**Comment by arthur791004** [comment]
BTW, I saw something like this

image

Is it correct? It looks different from the preview of style variations and I think the text color should look the same 🤔

image

**Comment by fushar** [comment]
> I thought the reason is we only query the first 50 themes, so these two are not present.

OH MY GOD!! Nice finding!! Let me increase the limit on wpcom 😂 Thanks!

**Review by taipeicoder — APPROVED** [review]
Works as intended! I appreciate that it didn't add much code to the unified design picker component 🥲

**Comment by taipeicoder** [comment]
> BTW, I saw something like this
> 
> image
> 
> Is it correct? It looks different from the preview of style variations and I think the text color should look the same 🤔
> 
> image

I'll create a follow-up PR to fix this 🙏

**Comment by autumnfjeld** [comment]
> I thought the reason is we only query the first 50 themes, 

@fushar Could you P2 a summary of this conversation in createp2 ?   tag simison, ianstewart, & matias, cross post to themedevp2 and dotcom, and  ganon and post the P2 link in #themes.   

This is quite an important thing: the decision to show what themes appear in the onboarding Design Picker and we should discuss with theme peeps. :).  

Include these things in the P2:
* let everyone know we've discovered the limit was 50 and now  you've set it to 100.   
* As a consequence of this limit, base themes Quadrat and Geologist base themes WERE NOT not present in the design picker and thus tracks data for these themes do not exist 
  * given that I see there are now 57 themes in the DP, there were 7 themes that were not showing to users.  Are we able to identify these 7 and include these in the P2? 
* state what all the rules are for showing a theme in the Design Picker:
  * 100 limit
  * showing themes with [`featured` tag](https://github.com/Automattic/wp-calypso/blob/trunk/packages/design-picker/src/components/index.tsx#L348) 
      * or wait it is these tags: `auto-loading-homepage` , `full-site-editing` (as @arthur791004  said [above](https://github.com/Automattic/wp-calypso/pull/67722#issuecomment-1246233528) 
  * anything other rules 
* bonus points if you want to link to code for each of the rules (your choice to do that extra work)
* link to this PR
* your own opinions if you have them 😃 
*

I am guessing people will have opinions, and I don't think we don't want to show 100 themes, but we probably want to make sure we are showing the BEST of 50 or 60 or some number.

Side note:  I just counted the number of themes in the DP and it is 57.

**Comment by autumnfjeld** [comment]
What the heck does `auto-loading-homepage` mean?!? 🤣

**Pull request merged**
