### PR TITLE
Add Event Countdown and Timeline blocks

### PR DESCRIPTION
**Pull request by mkaz**
#### Changes proposed in this Pull Request

Adds two additional blocks to FSE plugin. These are being included here for distribution purposes and will move to Jetpack when ready the proper block categorization exists there. See https://github.com/Automattic/jetpack/pull/14104

Note: Do not deploy to WPCOM without disabling existing blocks there first, same diff commit would be ideal.

#### Testing instructions

* Build Full Site Editing Plugin
* Check you can add Event Countdown block
* Check you can add Timeline block

### CODE REVIEW

**Comment by Copons** [comment]
Excuse me @mkaz, could you please explain the reasoning behind adding these blocks into FSE?
They don't seem related to site building at all...

**Comment by Addison-Stavlo** [comment]
Nice Blocks!  

Screen Shot 2019-12-02 at 4 38 07 PM

I noticed in the editor, that the countdown block has the ability for us to change width settings such as selecting "wide width" and "full width".  

Screen Shot 2019-12-02 at 4 45 51 PM

But it does not seem that the timeline block has this setting and is restricted to one width.

Screen Shot 2019-12-02 at 4 49 02 PM

Is wide/full-width support something the timeline block should have?

**Comment by mkaz** [comment]
@Addison-Stavlo Thank you for your interest in the blocks. You're right, this first release of Timeline does not have a wider width, that is a good suggestion. We have a couple of additional planned features for it, so we can add it to our list. Thanks again.

**Comment by noahtallen** [comment]
> Note: Do not deploy to WPCOM without disabling existing blocks there first, same diff commit would be ideal.

I wonder if there is a way code could be merged _ahead_ of the release in order to check if the new files exist, and if so, to avoid loading the old ones? Otherwise, I'm afraid it could be overlooked in the release, since it wouldn't be a typical update and someone could forget.

**Comment by mkaz** [comment]
@noahtallen - Good point, for a Jetpack deploy doing something similar, we altered the diff to handle removing the existing blocks in one change. 

Since that might not be available in this process, I added a block registration check in this plugin and the existing plugins on WPCOM (D36395). This should mitigate the issue with having to coordinate the addition and removal.

**Comment by apeatling** [comment]
@vindl @noahtallen This one is hanging around, are we getting these blocks in?

**Comment by noahtallen** [comment]
Yes, apologies that we have been slacking in review!

@mkaz I'm curious, will development of this feature continue to happen inside of the FSE plugin or are you copying the code from a different repository?

If development happens inside the FSE plugin, it might be useful to add the npm scripts if there are any so that it's all in one place. Most of the features use the same build script, but add their own bits to package.json. It should be easy to set up based on existing code, but we do need to document it a bit more.

**Comment by mkaz** [comment]
@noahtallen No, I think long term goal would to move these blocks and development to Jetpack once their experimental blocks setup is in place. This is an interim move to get it in place for Atomic sites.

**Comment by noahtallen** [comment]
> This is an interim move to get it in place for Atomic sites

:/ Huh. I guess I don't really understand why we don't go for Jetpack immediately, then? FSE probably has a worse dev process than Jetpack (admittedly, I've not done Jetpack development), which is to say that as you've noticed, it doesn't really handle quick deployments very well. And if the block exists once in post content, it has to be available forever -- so it's not really throwaway code or anything.

Anyways, I'll give this a look so we can get the process going.

BTW, sorry again that the process sucks. I feel very deeply the want to just ship things smoothly without process getting in our way. (P2 will hopefully go out tomorrow :))

**Comment by mkaz** [comment]
@noahtallen great, thanks! how should we proceed for a merge and deployment?

**Comment by simison** [comment]
I see there's built JS & CSS code in this PR; is there a plan to get rid of that and add a build step like with other files in FSE plugin?

Additionally, built files are not minified — are you syncing them as-is to production?

**Pull request merged**
