### PR TITLE
Add new Earn features under the Free plan

### PR DESCRIPTION
**Pull request by niranjan-uma-shankar**
Related to pdgrnI-2xq-p2#comment-4128 and code-D115905.

## Proposed Changes

* Add "Payment button" feature under the Free plan.
* Add "Pay with PayPal" feature in the comparison grid only (it is available on Premium plan and upwards).

Screenshot 2023-07-13 at 3 50 41 PM

Screenshot 2023-07-13 at 3 51 00 PM

## Testing Instructions

* Enter the signup flow at `/start`, and in `/start/plans` verify that the features mentioned in the description are visible, both in the main grid and the comparison grid.
* Feature should be visible in both monthly and annual tabs. 
* Tooltip content should be visible in both main grid and comparison grid.
* Non-en will show untranslated content, `String freeze` label is added.
* Verify both desktop and mobile viewports.
* Verify changes are visible in signup flow plans step and in Calypso /plans page.
## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/8544646

Thank you @niranjan-uma-shankar for including a screenshot in the description! This is really helpful for our translators.

**Review by travisw — APPROVED** [review]
Changes look good and test well. 👍 

One strange thing I noticed, and I'm not sure if it's a nuance of a dev environment or what, but when running this branch locally I see the "4K Videos with VideoPress" feature as not being included in any plan, which is different from how it shows on production.

**Branch**
Screenshot 2023-07-19 at 10 04 36 AM

**Production**
Screenshot 2023-07-19 at 10 04 24 AM

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/8544646

Thank you @niranjan-uma-shankar for including a screenshot in the description! This is really helpful for our translators.

**Comment by niranjan-uma-shankar** [comment]
> locally I see the "4K Videos with VideoPress" feature as not being included in any plan,

That was a bug I introduced, thanks for catching that. I fixed it in the latest commit.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/8544646).

**Pull request merged**
