### PR TITLE
Open site assembler after selecting a virtual theme in the design picker

### LINKED ISSUE #76098: Virtual themes: Show Pattern Assembler in design picker
In https://github.com/Automattic/wp-calypso/issues/75332 we linked selecting a virtual theme in the design picker to the Pattern Assembler.

The flow looks like this

select from grid | Preview | Go to PA
-------|-------------------|----------
Image | Image | Image

We could open up the PA right in the preview:

select from grid | PA Preview
-----------------|----------------
Image | Image

We should change the "Use our library of styles and patterns..." wording to something more appropriate when the assembler is used in this way. Maybe something like the old virtual theme sidebar text.

Somewhat related: pekYwv-Zx-p2#comment-795

### PR DESCRIPTION
**Pull request by mmtr**
Fixes https://github.com/Automattic/wp-calypso/issues/76098

## Proposed Changes

Simplifies the selection of virtual themes in the design picker by omitting the design preview step and opening directly the site assembler.

**Before**

Step 1: Design picker | Step 2: Design preview | Step 3: Site assembler
--- | --- | ---
Screenshot 2023-05-08 at 15 12 22 | Screenshot 2023-05-08 at 15 12 32 | Screenshot 2023-05-08 at 15 12 40

**After**

Step 1: Design picker | Step 2: Site assembler
--- | ---
Screenshot 2023-05-08 at 15 08 13 | Screenshot 2023-05-08 at 15 08 24

## Testing Instructions

- Use the Calypso live link below.
- Go to `/start`.
- Follow the onboarding flow until you reach the "Pick a design" step.
- Select a virtual theme.
- Make sure the site assembler is opened. 
- Click on "Continue".
- Once in the launchpad, click on the "Select a design" task
- Select a regular theme now.
- Make sure you land on the design preview screen.
- Click on "Continue".
- Make sure it's activated as expected.
- Use the "Select a design" task again in the launchpad.
- Select a virtual theme now.
- Make sure it's activated without going through the site assembler (not sure if this is expected, but it's the current behavior in production as of https://github.com/Automattic/wp-calypso/pull/76813).

### CODE REVIEW

**Review by dsas — APPROVED** [review]
Works nicely for me

**Comment by dsas** [comment]
Note that the testing instructions didn't work though, I had to go via /start. Using the second step in the instructions didn't work - I was redirected back to the launchpad when selecting a theme (i.e. https://github.com/Automattic/wp-calypso/issues/76530 is triggered slightly differently)

**Comment by dsas** [comment]
Moved back to In progress because there's now some conflicts to resolve

**Review by dsas — APPROVED** [review]

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/7989699

Thank you @mmtr for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/7989699).

**Pull request merged**
