### PR TITLE
Switch %heading @extend to be a mixin

### PR DESCRIPTION
**Pull request by MichaelArestad**
No visual changes. To test, check out the media library or stats section titles.

### CODE REVIEW

**Comment by obenland** [comment]
Nice one @MichaelArestad

**Comment by MichaelArestad** [comment]
Rebased and merging when checks are complete.

**Comment by aduth** [comment]
What was the reason / background for this change? As I understand placeholders vs. mixins, including a mixin will result in duplicate code:

>The best advice would be: if you need variables, use a mixin. Otherwise, extend a placeholder. _[...]_ the way Sass handles mixins makes them very inconvenient when you don’t use them with contextual variables. To put it simply: Sass will duplicate the output of the mixin every time you use it, resulting not only in duplicated CSS but also a bigger stylesheet.

https://www.sitepoint.com/sass-mixin-placeholder/

**Comment by MichaelArestad** [comment]
@aduthtl;dr @extends are pretty much always problematic. Regarding duplicate code: when we serve our files compressed, there's no meaningful difference in size(gzip).

Hugo, the author of the above article) later wrote this on the topic. https://www.sitepoint.com/avoid-sass-extend/

**Comment by aduth** [comment]
Thanks for the link. Wish there was a reference to that in the original article.

I guess the main argument is that the location of a grouped set of placeholder styles is not in a predictable order when considering the selector in which it is extended? Versus mixins which are always inserted at the exact point they're included (acknowledging that this means they may be repeated throughout the generated stylesheet).

The gzip repetition point is neat and not one I would have given much thought to:

>Gzip is based on DEFLATE and LZ77; quickly put, the more a string is repeated, the better it is for compression. When putting this in context, it means that the difference is likely to be inexistant once Gzip has rolled over the whole thing.

Anyways, learned something new. Thanks for the background 👍

**Pull request merged**
