### PR TITLE
G Suite: Rename product selector and add more granular ones

### PR DESCRIPTION
**Pull request by stephanethomas**
This pull request renames the `isGoogleApps()` selector to `isGSuiteOrExtraLicenseOrGoogleWorkspace()`. It also introduces the following selectors:

* `isGoogleWorkspace()`
* `isGSuite()`
* `isGSuiteOrExtraLicense()`
* `isGSuiteOrGoogleWorkspace()`

The goals of those changes are to:

* Remove occurrences of 'GoogleApps' - which was how Google Workspace was named several years ago
* Provide a set of selectors that are more explicit and granular
* Allow us to apply specific logic only to Google Workspace products in the future
* Make it clear when we deal with the product for an extra G Suite license

To clarify the last point, the product `71` should indeed only be used when purchasing additional licenses. Otherwise, it shouldn't be surfaced in most pages and logic (e.g. one should not be able to renew nor cancel such product).

### CODE REVIEW

**Review by sirbrillig — APPROVED** [review]
I haven't tested all the things this touches, as it's quite a lot, but the code looks safe and several of these changes are covered by tests so I'm fairly confident that this is ok.

**Comment by sirbrillig** [comment]
Worth mentioning that the style errors are all instances of `'@automattic/calypso-config' should be listed in the project's dependencies. Run 'npm i -S @automattic/calypso-config' to add it (import/no-extraneous-dependencies)` which is probably a side-effect of https://github.com/Automattic/wp-calypso/pull/49322 

Screen Shot 2021-01-28 at 3 13 17 PM

It's not a blocker for this PR, so I think you can ignore those failures.

**Comment by stephanethomas** [comment]
This was closed inadvertently.

**Comment by stephanethomas** [comment]
Thanks for the review @sirbrillig, I really appreciate 🙇‍♂️.

**Pull request merged**
