### PR TITLE
Framework: Start catching js errors in production

### PR DESCRIPTION
**Pull request by scruffian**
Once the error catching thing has been running OK in staging we should push it out to production so it's actually useful :)

### CODE REVIEW

**Comment by stephanethomas** [comment]
Code looks good.

**Comment by lamosty** [comment]
Should this work in development mode? I'm testing this and getting not found error.

**Comment by scruffian** [comment]
@lamosty - good catch, thanks. We don't want to load this file in development :)

**Comment by blowery** [comment]
:+1: now that dev is excluded. :)

**Pull request merged**
