### PR TITLE
Domain Purchase Flow: Email solution comparison link opens externally

### LINKED ISSUE #95812: Email: Comparison link should open in new tab
### Quick summary

The link to the page comparing email options should open in a new tab and have an external link icon.

Image

### Steps to reproduce

1. Go to WP Admin for a site.
2. Go to Hosting ➡️ Domains
3. Add new domain
4. Select a domain

### What you expected to happen

The link should open a new tab and display the external link icon.

### What actually happened

Page opens in the current tab.

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### If the above answer is "Yes...", outline the workaround.

_No response_

### Platform (Simple and/or Atomic)

_No response_

### Logs or notes

_No response_

### PR DESCRIPTION
**Pull request by p-jackson**
Fixes #95812

## Proposed Changes

* Use `<ExternalLink>` to open the detailed email provider comparison in a new tab
   * But only when the user is in a domain purchase flow.

**Adding a new domain**
CleanShot 2024-10-30 at 10 23 35@2x

**Adding email to existing domain** (i.e. no change)
CleanShot 2024-10-30 at 10 23 42@2x

## Why are these changes being made?

We don't usually open Calypso links in a new tab, but an exception is warranted here. When the user is purchasing a domain they're in the middle of a purchase flow, and we would prefer to keep them in that flow.

The same comparison link exists at `/email/{{ site slug }}` when the site already has a custom domain. In this case the user isn't in the middle of a flow, and so the exception doesn't hold in this situation. So it hasn't been updated to an external link here.

## Testing Instructions

* **The domain purchase flow**
   * `/domains/manage/{{ site slug }}`
   * Click **Add new domain**
   * Search and select any old domain
   * On the **Add a professional email address...** screen confirm the **see how they compare** link opens in a new tab
   * Confirm it has the external link icon
* **The existing domain screen**
   * Test a site that has an existing custom domain
   * `/email/{{ site slug }}`
   * Confirm the **See how they compare** link opens in the same tab

## Pre-merge Checklist

- [x] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] ~[Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?~
- [x] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [x] Have you checked for TypeScript, React or other console errors?
- [ ] ~Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)~
- [ ] ~Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?~
- [ ] ~For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?~

### CODE REVIEW

**Review by zaerl — APPROVED** [review]
LGTM. Great work.

**Review by fredrikekelund — COMMENTED** [review]
The fact that clicking `Select` on the comparison page takes you back to the purchase flow makes for an odd experience, IMO. 

I agree that it's slightly jarring how the comparison page doesn't appear to be part of the domain purchase flow, but I'm not entirely convinced that this solves the root of that problem… Have we considered a style variation of the comparison page with the same header as the domain purchase flow, @p-jackson?

**Review by paulopmt1 — APPROVED** [review]
It's working as expected!

> they're in the middle of a purchase flow, and we would prefer to keep them in that flow

Thanks for the extra context, I was looking for this answer when reviewing it and it helped a lot!

**Comment by p-jackson** [comment]
> The fact that clicking `Select` on the comparison page takes you back to the purchase flow makes for an odd experience, IMO.

I think we should pause merging this PR until we figure out whether this is actually an improvement to the flow. See https://github.com/Automattic/wp-calypso/issues/95812#issuecomment-2448857297

**Comment by p-jackson** [comment]
Closing in favour of https://github.com/Automattic/wp-calypso/issues/95864

**Pull request closed without merging**
