### PR TITLE
Theme Showcase: Refactor translatable title and description with hooks

### PR DESCRIPTION
**Pull request by yuliyan**
Related to 478-gh-Automattic/i18n-issues#issuecomment-1678568668

## Proposed Changes

* Refactor theme showcase title and description logged-in and logged-out content to use custom hooks so that the component is properly subscribed to i18n changes and updates when the i18n data changes.

## Testing Instructions

* Code review.
* Use calypso.live build.
* Go to `/[locale]/themes` logged-out, where `[locale]` is a locale slug for any Mag-16 language.
* Confirm title and meta tags are rendered translated into the specified language.
* Go to `/themes` logged-in.
* Confirm title and description are translated in your account language.
* Unit tests for logged-in title and description pass - `yarn test-client client/my-sites/themes/test/use-theme-showcase-*`.

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

**Comment by dlind1** [comment]
The tests pass and the code looks good from what I could see.
On logged-out pages the og:title/description is translated on calypso.live, for logged-in on calypso.live there are no og:title/description fields, the categories appear untranslated and the translations for theme descriptions displayed on hover are also not loading for me.

Screenshot 2023-08-16 at 00 59 18

**Comment by yuliyan** [comment]
Thank you for the testing, @dlind1!

> for logged-in on calypso.live there are no og:title/description fields

- That's expected because the meta tags are only server rendered, and the logged in themes section is being client rendered. However, the document title and the section title and subtitle/description components should be translated.

---

> the categories appear untranslated

- Seems to be unrelated to the changes introduced in this PR and can be reproduced on other calypso.live builds, so it's likely related to the environment.

---

> the translations for theme descriptions displayed on hover are also not loading for me.

- Unrelated to the PR changes - the problem is also present on production. See 293-gh-Automattic/i18n-issues.

**Review by Copons — APPROVED** [review]
This is an amazing change @yuliyan, thank you!

I have tested both the logged-in and -out Theme Showcase, and they work as expected. Translations are loaded anywhere relevant.

Also, kudos for expanding the existing tests and adding more contextual translation comments where appropriate.

I'm not exactly a fan of having multiple components in the same file, but it's not a blocker, and the new `ThemeShowcaseHeader` is a great help for a possible upcoming refactor of the whole Showcase as functional component.

**Comment by Copons** [comment]
> the categories appear untranslated and the translations for theme descriptions displayed on hover are also not loading for me.

I've noticed the same, but it's definitely unrelated to this PR.
I've managed to get them translated by clearing the IndexedDB, so translations for the menu are working, just very heavily cached. 🤔

**Comment by yuliyan** [comment]
@Copons, thank you for the review!

> I'm not exactly a fan of having multiple components in the same file, but it's not a blocker, and the new ThemeShowcaseHeader is a great help for a possible upcoming refactor of the whole Showcase as functional component.

I agree - there wasn't really any reason to be within the same file, so I've moved it into its own.

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/8800921

Hi @yuliyan, could you please edit the description of this PR and add a screenshot for our translators? Ideally it'd include all of the following strings:
- `Browse all premium themes for WordPress.com. Available on all Premium, Business, and Commerce plans. Activate the one that's right for you.`
- `Enhance your blog with the perfect premium theme. Available on all Premium, Business, and Commerce plans. Activate the one that's right for you.`
- `Enhance your business website with the perfect premium theme. Available on all Premium, Business, and Commerce plans. Activate the one that's right for you.`
- `Enhance your portfolio website with the perfect premium theme. Available on all Premium, Business, and Commerce plans. Activate the one that's right for you.`
- `Enhance your online store with the perfect premium theme. Available on all Premium, Business, and Commerce plans. Activate the one that's right for you.`
- `Enhance your About Me website with the perfect premium theme. Available on all Premium, Business, and Commerce plans. Activate the one that's right for you.`
- `Enhance your link in bio website with the perfect premium theme. Available on all Premium, Business, and Commerce plans. Activate the one that's right for you.`
- `Enhance your newsletter with the perfect premium theme. Available on all Premium, Business, and Commerce plans. Activate the one that's right for you.`

Thank you in advance!

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/8800921).

**Pull request merged**
