### PR TITLE
Editing Toolkit: Update to 2.8.5

### PR DESCRIPTION
**Pull request by p-jackson**
#### Changes proposed in this Pull Request

* Version bump and changelog

#### [Changes to Editing Toolkit since 2.8.4](https://github.com/Automattic/wp-calypso/commits/master/apps/editing-toolkit):

- [x] Gutenboarding: plans grid requests data in the correct locale (#47227)
- [x] [eslint] Adds rule `one-var` and autofixes all related errors (#47310)
- [x] Gutenboarding i18n: i18n for domain picker in the launch flow (#47178)
- [x] Add block preview for Premium Content block (#47200)
- [x] Provide block context to the payments button. (#47245) 
- ~~[ ] Persistent Launch Button: enable in all environments (#46817)~~ (was just a code comment change)
- [x] Coming Soon page: disable head/footer scripts, cookie banner and Gravatar scripts (#47400)
- [x] consolidate the places we've defined get_iso_639_locale() and reuse it for coming soon (#47307)
- [x] Coming Soon: Set the headers to prevent caching for the different browsers (#47450)

#### Testing instructions

1. Load the diff (D52773-code) on your sandbox and confirm that the above changes work correctly
2. Test that the new version of the plugin doesn't break Atomic sites by following the instructions in the "Atomic Testing" section at PCYsg-ly5-p2.

### CODE REVIEW

**Comment by p-jackson** [comment]
Known issue with the php unit tests. They pass when run locally though.

**Comment by autumnfjeld** [comment]
I'll start on testing this. :)

**Review by autumnfjeld — APPROVED** [review]
@p-jackson Per Atomic testing instructions I have checked that the Editor loads with this ETK build, both with and without Gutenberg plugin.  Success! ✅

**Comment by andrewserong** [comment]
@p-jackson @apeatling while testing this release I can see a visual issue with the Payments block, which I think is related to https://github.com/Automattic/wp-calypso/pull/47245 (probably not caused by the PR, but _revealed_ by it, if that makes sense!)

With this release patched there's a stray `0` character beneath the block:

image

Without this release patched, it renders a Subscribe block:

image

Does this happen for anyone else? (Tested on a simple site on the Free plan)

**Comment by autumnfjeld** [comment]
I will keep updating this as I get through all the checks for sandboxed site:
✅  means successfully tested

Gutenboarding: plans grid requests data in the correct locale (#47227)
    - ✅   View the plans grid in gutenboarding: it should be translated and the prices should be in your selected currency
    -  ✅ View the plans grid in the launch flow: it should be translated and the prices should be in your selected currency (my currency is USD, which is just $ no letters like AUD$)
    -  ✅ Open gutenboarding in incognito tab: the currency in the plans grid should be a decent guess given your IP

**Comment by autumnfjeld** [comment]
TEST FOR: Add block preview for Premium Content block (#47200)

For Business Plan Site:
- ✅ Make sure that the block renders correctly in the post body
- ✅  Verify that the "Subscribe" button for the block in the post body is a jetpack/recurring-payments block (you should be able to see this as data-type on the div in the browser inspector)
- ⛔ Open the block list in the side panel and hover over the 'Premium Content' block in the search results --> See screenshot "No preview available"
Screen Shot 2020-11-16 at 16 41 28

- ✅  Verify that the block preview displays correctly --> See screenshot below
Screen Shot 2020-11-16 at 16 50 26




For Free Site:
Block did not render (or preview?) correctly:
Screen Shot 2020-11-16 at 16 51 40

**Comment by andrewserong** [comment]
@autumnfjeld looks like the `Read more about Payments...` message will be removed in @apeatling's Jetpack PR https://github.com/Automattic/jetpack/pull/17696 — the PR's merged, but I assume it hasn't been deployed to simple sites yet.

Update on my testing of the Premium Content block: it's working much like in Autumn's screenshots for me now, turns out I had an issue in my sandbox with my test site, so now testing on a fresh Free site it's looking a fair bit better. There _is_ still the stray zero character rendering during the loading state, but it's appearing both with and without sandboxing this version change, so appears to be unrelated to the recent PRs:

stray-zero-character-small

**Comment by apeatling** [comment]
Starting a review of our PRs in here this morning :+1:

**Comment by apeatling** [comment]
Just confirming that this issue is fixed by https://github.com/Automattic/jetpack/pull/17696:

Screen Shot 2020-11-16 at 9 39 15 AM

I will look at merging that change on dotcom early today because it's a rough visual issue and I'd prefer not to wait on the Jetpack release.

**Comment by apeatling** [comment]
I could not reproduce the block preview missing on search, this appeared fine for me:

Screen Shot 2020-11-16 at 9 41 11 AM

**Comment by apeatling** [comment]
> Add block preview for Premium Content block (#47200)
> Provide block context to the payments button. (#47245)

Both of these change test fine for me on simple and atomic. :+1:

**Comment by jeyip** [comment]
> Known issue with the php unit tests running in CI. They pass when run locally.
If anyone is curious, here's the issue for the failing PHP unit spec https://github.com/Automattic/wp-calypso/issues/47255. It's on our radar 👍

**Comment by jeyip** [comment]
Created a diff to remove the outdated ET build D52840-code whenever this update is merged

**Comment by p-jackson** [comment]
Rebased to include #47450

**Comment by jeyip** [comment]
TEST FOR: use get_iso_639_locale() for coming soon page links (#47307)

- ✅ Simple site login link on a coming soon page works (EN, ES)
- ✅ Atomic site login link on a coming soon page works (EN, ES)

**Comment by sirreal** [comment]
Deployed in r216900-wpcom

**Pull request merged**
