### PR TITLE
Jetpack Connect: Stop overwriting section name to hide sidebar

### PR DESCRIPTION
**Pull request by sirreal**
This PR removes a section name overwrite in the Jetpack Connect controller. The purpose is to hide the sidebar, but it also has the unintended side-effect of changing the section name.

Section names should be defined in [`wordpress-com.js`](https://github.com/Automattic/wp-calypso/blob/3c3cfe42da0b1ae1fd0b2e66ee3663eb0fdec33d/client/wordpress-com.js):
https://github.com/Automattic/wp-calypso/blob/3c3cfe42da0b1ae1fd0b2e66ee3663eb0fdec33d/client/wordpress-com.js#L154-L160

Part of #22218 

## Testing
1. Look for usage of the [section name](https://github.com/Automattic/wp-calypso/search?q=jetpackConnect)
1. Verify that and sectionName usage is now `jetpack-connect` as defined in `wordpress-com.js`.
1. Verify HappyChat within the Jetpack Connection flow is correctly sent to JPOP group (Please avoid this in production: PCYsg-b99-p2)
   1. Log in
   1. Ensure you're accepting chats for the JPOP group
   1. Toggling your availability should determine whether you see chat options during the connection flow

### CODE REVIEW

**Comment by nosolosw** [comment]
Hey @sirreal I've got my brainpower focused for a release planned for tomorrow. Would it be ok if I look at this as soon as that is done? I'm not very familiar with the Jetpack flow and would take me a while to understand how to test it.

**Comment by tyxla** [comment]
@nosolosw don't worry, I'll help with review/testing - I am able to get the HC staging HUD running, so it shouldn't be a big deal.

**Comment by brbrr** [comment]
E2E tests updated: https://github.com/Automattic/wp-e2e-tests/pull/939

**Comment by ockham** [comment]
Thanks a lot @sirreal!

**Pull request merged**
