### PR TITLE
Remove Automattic/manage code owner

### PR DESCRIPTION
**Pull request by creativecoder**
#### Proposed Changes

* Remove @Automattic/manage from CODEOWNERS, as it's no longer an active group

#### Testing Instructions

n/a

#### Pre-merge Checklist

n/a

### CODE REVIEW

**Comment by creativecoder** [comment]
@sixhours , Looks like you are the only one left in the Automattic/manage (and Automattic/dotcom-manage-design) Github groups. Okay to remove that group from the CODEOWNERS file?

**Comment by creativecoder** [comment]
Also, is there an alternative owner anyone would recommend for Customer Home?

**Comment by sixhours** [comment]
Huh, weird. No objections to removing the group :D

**Comment by creativecoder** [comment]
Thanks @sixhours ! I've removed the Manage team as a code owner by merging this PR.

I'm not able to delete the Github groups, but I think you should be able to since you are listed as a maintainer of both groups:

- https://github.com/orgs/Automattic/teams/manage/members
- https://github.com/orgs/Automattic/teams/dotcom-manage-design/members

**Pull request merged**
