### PR TITLE
Framework: Extract auto from `lib/react-test-env-setup/index.js` into `test/setup-dom-env`

### PR DESCRIPTION
**Pull request by gziolo**
Part of #3822.

Related discussion: https://github.com/Automattic/wp-calypso/pull/3797/files#r55208177.

This PR extract `auto` method from `lib/react-test-env-setup/index.js` and moves to `client/test/helpers/setup-dom-env.js`. This change tries to provide better name for `auto` test helper.

It also tries to promote `client/test/helpers/` folder as place for common test utils.

There are no changes to test on app side.

To execute tests from CLI:
1. Go to `client` folder.
2. Execute `make test` command.

### CODE REVIEW

**Comment by blowery** [comment]
Do we want to standardize on a `useXXX` style for the helpers? Like

```
useMockery();
useFakeDom();
useQuickMocks();
// etc 
```

?

**Comment by aduth** [comment]
Mentioned elsewhere, but it would be nice if each helper had its own README.md, which would be simple enough if placed in their own folders:

```text
helpers
└── use-fake-dom/
    ├── index.js
    └── README.md
```

**Comment by blowery** [comment]
oh, btw, I moved all the test helper stuff to `test/test`, a peer of `client` and `server`

**Comment by blowery** [comment]
> Mentioned elsewhere, but it would be nice if each helper had its own README.md, which would be simple enough if placed in their own folders

#3894

**Comment by gziolo** [comment]
> Do we want to standardize on a useXXX style for the helpers?

Sounds good :)

> oh, btw, I moved all the test helper stuff to test/test, a peer of client and server. So this should probably go in test/test/helpers

I'm going to rebase and fix that, thanks!

**Comment by gziolo** [comment]
All issues addressed.

**Comment by blowery** [comment]
Looks good :ship:

**Pull request merged**
