### PR TITLE
Store Stats: Add Net Sales as nested value

### PR DESCRIPTION
**Pull request by psealock**
Nest Net Sales and create a tooltip to add discoverability.

### Before
* No nested Net Sales
* No tooltip

### After
screen shot 2017-10-27 at 1 48 40 pm

### Other Change
* Rename `sinceFormat` to `shortFormat` as its more applicable to various uses.

Fixes https://github.com/Automattic/wp-calypso/issues/17163

### CODE REVIEW

**Comment by greenafrican** [comment]
Looking good! Once it is ready, we can remove the Net Sale tab and add Net Sales to the key.

**Comment by psealock** [comment]
### Update
* Net Sales tab removed
* Tabs now occupy 33% on non-mobile
* Gross Sales tab label is now just "Sales"
* Net Sales added to legend only when "Sales" selected
* Hidden the ability to toggle Net Sales on/off. It seemed like an irrelevant feature

screen shot 2017-11-16 at 4 16 10 pm

cc @greenafrican

**Comment by timmyc** [comment]
Doing a sweep of open Needs Review Store PR's. Anything I can help with here - is this still something we would like to get in?

**Comment by psealock** [comment]
Thanks @timmyc! @greenafrican, do we still like these changes? If so, here are updated testing instructions.

### Testing
1. `https://calypso.live/store/stats/orders/day/<my-cool-site>?branch=try/store-stats-nested-net-sales`
2. See tooltip on the main chart with appropriate data displayed
3. When on the Gross Sales tab, Net Sales are nested and the tooltip should reflect both data sets
4. Ensure the legend is appropriate
5. Take a look at each tab and make sure the right data is in the tooltip and the legend is correct.
6. Make sure the periods are correctly displayed with what on the x-axis on the tooltip for weeks, months, etc. Note: Weeks are noted by the end date
7. Adjust screen width to make sure no media queries are reacting properly

**Comment by allendav** [comment]
Hmmm. I was expecting to see refunds reflected in the net sales, but do not.

I created two orders. One for 1 product costing $1000 and a second order for quantity 2 of a $100 product.

I refunded one of the $100 products.

When I look in stats, I see gross == net == $1200, even after a hard refresh. I expected to see net of $1100.

Thoughts?

**Comment by psealock** [comment]
Great find @allendav. I can reproduce what you found and will write it up as a separate issue

**Comment by psealock** [comment]
@greenafrican Going to merge this one tomorrow unless you have any objections/comments

**Pull request merged**
