### PR TITLE
Substack importer: update "all set" copy for content

### LINKED ISSUE #96112: Substack importer: simplify copy to translate plurals easier in "all set" for content -message
The copy of this "all set" text depends on a number of posts, pages and attachments, and each combination (zero, singular plural) needs its own variation. Copy is great, but the amount of text to translate and code complexity is a bit much for something this trivial.

See [code](https://github.com/Automattic/wp-calypso/blob/efd179982934223ca4797cc2df23700a3223d7d2/client/my-sites/importer/newsletter/content-upload/author-mapping-pane.jsx#L15-L74)
Slack convo p1728553977305199-slack-C052XEUUBL4

Image

Couple options:

- Keep the complexity.
- Use format like:
    ```
    All set! We’ve found:
    %d post, - with plural %d posts,
    %d page, - with plural %d pages,
    %d media - with plural %d media
    ```
- Use format like:
    ```
    All set! We’ve found:
    Posts			%d
    Pages			%d
    Media items		%d
    ```

Here's a visual:

Image

Or with zero sums:

Image

This would be straightforward as we could use the same component as for the summary page:

Image

### PR DESCRIPTION
**Pull request by simison**
Resolves https://github.com/Automattic/wp-calypso/issues/96112

## Proposed Changes

* Update "all set" to be such that it's easier to translate. Visual copied from summary page, added in https://github.com/Automattic/wp-calypso/pull/96014 .

Before
Screenshot 2024-11-06 at 18 15 03

After
Screenshot 2024-11-13 at 15 35 07

## Why are these changes being made?

*

## Testing Instructions

*

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Comment by crisbusquets** [comment]
I like the solution. I've modified the font and icon colors and adjusted the spacing between the text and numbers.

I see we're reusing this from the new summary page, but in this case, because we have fewer elements and shorter text, the extended spacing doesn’t work.

Figma: ZdugJ99VXJszZRSBfMNre4-fi-5338_35231

Screenshot 2024-11-06 at 19 42 12

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/17001859

Some locales (Hebrew, Japanese) have been temporarily machine-translated due to translator availability. All other translations are usually ready within a few days. Untranslated and machine-translated strings will be sent for translation next Monday and are expected to be completed by the following Friday.

Thank you @simison for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/17001859).

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/17001859).

**Pull request merged**
