### PR TITLE
Fix: Swap HTTP pipeline chains (fix stupid)

### PR DESCRIPTION
**Pull request by dmsnell**
Early on I renamed the terms but forgot to swap these processors. Who
knows why it hasn't blown up in production `¯\_(ツ)_/¯`

### CODE REVIEW

**Comment by samouri** [comment]
> Who knows why it hasn't blown up in production ¯\_(ツ)_/

i'd like to know. researching

**Comment by samouri** [comment]
Figured it out.  There is only a single active processor right now: the deduper.

Within the deduper there are a two bits in particular that allowed this to survive:
1. [Inbound to Calypso: no-op if not in queue ](https://github.com/Automattic/wp-calypso/blob/master/client/state/data-layer/wpcom-http/pipeline/remove-duplicate-gets/index.js#L124).  I actually asked in review "but how could we ever get into this state?".  Turns out reversing the processors was one way :).  It is simultaneously the thing that saved the data-layer but also is the only reason the data-layer didn't fail fast. If we remove the check, it could help us catch bugs quicker.  On the other hand, we'd be removing the bug-safeguard. I think the best move forward for this processor in particular would be to log error messages in the console. 
2. [Outbound to wpcom: no-op if not get request](https://github.com/Automattic/wp-calypso/blob/master/client/state/data-layer/wpcom-http/pipeline/remove-duplicate-gets/index.js#L89) . This one is simpler and totally the right thing to do.  the deduper wasn't finding any nextRequest and so was no-opping early when it realized it wasn't a GET request. Utilizing the safe lodash `get` method was helpful here. no action items necessary.

**Comment by gwwar** [comment]
Thanks for 🔍  @samouri

**Comment by samouri** [comment]
Just because, I did #1 locally to see if this actually fixed the dedupe handler.  Turned out no requests were being deduped even with this fixed!

Examining the requestMap everything looked correct, but for some reason the `action` inside of the InboundProcessor was missing `apiVersion` so `buildKey` would build a key that didn't match.  After much too long debugging and ruling everything out, I had isolated it to a single line that was removing apiVersion from query: [wpcom client](https://github.com/Automattic/wp-calypso/blob/master/client/state/data-layer/wpcom-http/index.js#L55).  It looks like `wpcom` is mutating the query given to it and removing apiVersion (kind of makes sense considering it isn't really a true query arg).  This would not have been an issue if wpcom made its own copy of the arg or if the data-layer hands wpcom a `{ ...query }`.

I think we should apply this fix in this PR as well

**Comment by gwwar** [comment]
Great find @samouri. Perhaps we should also add an integration test, as well?

**Comment by dmsnell** [comment]
Nice @samouri! Gotta love mutation

**Comment by blowery** [comment]
Great find @samouri! We should probably update wpcom to not mutate the query it's handed.

**Pull request merged**
