### PR TITLE
Checkout: Use dropdown for wpcom variant picker and remove first step edit

### PR DESCRIPTION
**Pull request by sirbrillig**
#### Proposed Changes

Some products have term variants (monthly, yearly, biennial) which are displayed in the first step during checkout. Because these take up a large amount of vertical height (particularly when there are multiple products in the cart), they were originally placed behind an "Edit" button for that step along with other cart-changing behavior like product removal buttons. (Worth noting that the first step isn't part of the actual array of checkout steps; it is a manually managed step that requires a lot of machinery to operate.)

Over time, the cart-changing behavior has been moved so that it's accessible outside of the "Edit" mode on the first step. Right now the only remaining difference between the step's active and inactive modes is the variant picker.

Not that long ago, the Jetpack checkout was modified to replace their variant picker with a drop-down to take up less vertical space; this allowed it to be displayed in the step's inactive mode and allowed removing the "Edit" mode entirely.

In this diff, we modify the wpcom version of checkout to do the same thing. Removing the "Edit" mode will save a considerable amount of code and should decrease the complexity for users.

The major downside of this change is that the user cannot see all the variations at once, and only sees the savings percentage when a variant is selected, but the major upside is that the user can see the variant picker without having to click "Edit".

#### Screenshots

Before:

Screen Shot 2022-07-07 at 12 31 10 PM

Screen Shot 2022-07-07 at 12 31 17 PM

After:

Screen Shot 2022-07-07 at 12 32 20 PM

#### Testing Instructions

- Add a wpcom product to your cart that has term variants. For now you may need to use legacy plans because there are no variants for the Starter or Pro plans yet. You can add a legacy product to your cart by URL. For example, visit `/checkout/premium` to add a Premium plan to your cart.
- Verify that you see the term variant picker for the plan without having to change any modes.
- Verify that there is no "Edit" button on the first step.

### CODE REVIEW

**Comment by DavidRothstein** [comment]
To me the "Save 42%" is pretty confusing with this design... Save 42% compared to what? :smile: 

Also, I think this has the potential to change the mix of variants that people buy during signup?  It may not matter that much right at this moment, but it will soon (for example, https://github.com/Automattic/wp-calypso/pull/65126).  It may be a good idea to wait for that, then consider this change as an A/B test to understand the effect?

**Comment by chrisfromthelc** [comment]
> To me the "Save 42%" is pretty confusing with this design... Save 42% compared to what?

I haven't fully tested this yet, but I agree that this is unclear. Perhaps we should extrapolate out the monthly cost to show what it will cost over a year since the other two are shown in years as well.

**Review by chrisfromthelc — COMMENTED** [review]
I don't know if this is intentional, but the "Save XX%" is missing in the dropdown, but shows upon selection.

Screen Shot 2022-07-11 at 10 19 33 AM

When editing the current version, it shows all the discounts.
Screen Shot 2022-07-11 at 10 21 29 AM

**Comment by sirbrillig** [comment]
> I don't know if this is intentional, but the "Save XX%" is missing in the dropdown, but shows upon selection.

I've assumed that it is intentional since that's how it works for the Jetpack products. My guess was that the reason is that "Save XX%" is confusing, and this way it only says what you'll save once you've selected a variant, but I don't actually know. We should probably check with the team who designed it. @cbauerman do you know if this design choice was intentional?

If we wanted to add the savings to each item in the menu here, it probably wouldn't be too hard, but such a change could also be put into its own PR.

Also worth mentioning is that since the old view was behind the "Edit" button, this PR should increase the visibility of the savings displayed just by virtue of being visible immediately, so I see it as a net win.

**Comment by sirbrillig** [comment]
🤔  It looks like the decision to [show the discount and savings](https://github.com/Automattic/wp-calypso/blob/c661309f24edd441eb4a1cef3aa0658e9dad4ee2/client/my-sites/checkout/composite-checkout/components/item-variation-picker/variant-price.tsx#L76) actually stems from [when the variants are created](https://github.com/Automattic/wp-calypso/blob/c661309f24edd441eb4a1cef3aa0658e9dad4ee2/client/my-sites/checkout/composite-checkout/hooks/product-variants.tsx#L102-L104) where the price is [compared](https://github.com/Automattic/wp-calypso/blob/c661309f24edd441eb4a1cef3aa0658e9dad4ee2/client/my-sites/checkout/composite-checkout/hooks/product-variants.tsx#L144) to the the other variants. I'll take a look to see why those are not being included for the variants inside the dropdown. It's possible that this wasn't intentional after all.

**Comment by sirbrillig** [comment]
Ah, I figured it out. The discount is displayed by the `ItemVariantPrice` component but that component is only used for the [selected option](https://github.com/Automattic/wp-calypso/blob/c661309f24edd441eb4a1cef3aa0658e9dad4ee2/client/my-sites/checkout/composite-checkout/components/item-variation-picker/item-variation-dropdown.tsx#L215), not [the option list](https://github.com/Automattic/wp-calypso/blob/c661309f24edd441eb4a1cef3aa0658e9dad4ee2/client/my-sites/checkout/composite-checkout/components/item-variation-picker/item-variation-dropdown.tsx#L225).

Here's what it looks like if I use `ItemVariantPrice` in the list directly. It probably needs some styling, but it's not bad.

Screen Shot 2022-07-13 at 8 31 51 PM

**Comment by sirbrillig** [comment]
@michaeldcain I pushed the changes to use the variant component for the options. I believe you had some ideas for styles?

**Review by michaeldcain — APPROVED** [review]
@sirbrillig: Your changes LGTM and work well for both WPcom and Jetpack. I added selected and hover styles for the option list and removed some interpolated styles that weren't working correctly. If the style changes work for you, I think this is good to merge.

Screen Shot 2022-07-24 at 11 41 31 AM

**Review by michaeldcain — APPROVED** [review]

**Pull request merged**
