### PR TITLE
Plans Redesign: Update plans wording and targeting.

### PR DESCRIPTION
**Pull request by apeatling**
Update the wording for plans to more accurately reflect the latest features. Target each plan with a persona/user type.

Before:

screen shot 2016-07-13 at 10 29 56 am

After:

screen shot 2016-07-13 at 10 28 39 am

Test live: https://calypso.live/?branch=update/plans-descriptions

### CODE REVIEW

**Comment by rralian** [comment]
The personal description uses sentences, whereas the other descriptions just show sentence fragments that list features. So it reads inconsistently.

> Advanced design customization tools including CSS editing, lots of space for audio and video, and run your own advertising.

Also, the premium description sounds like all of the items are being included under the category of "advanced design and customization tools". And it's a list of items, except for the last thing, which is grammatically a command, so it reads kinda funny. I would change it to:

> Advanced design tools, CSS editing, lots of space for audio and video, and the ability to monetize your site with ads.

**Comment by apeatling** [comment]
@bob How about this? 

> Best for Personal Use:
> Give your website a boost with your own custom domain name and free of any WordPress.com advertising. Get access to high quality email and live chat support.

> Best for Entrepreneurs & Freelancers:
> Build a unique website design with advanced customization tools, CSS editing, lots of space for audio and video, plus the ability to monetize your site with ads.

> Best for Small Business:
> Power your business website with unlimited premium and business theme templates, Google Analytics support, unlimited storage, and the ability to remove WordPress.com branding.

**Comment by rralian** [comment]
> @rralian How about this?

Digit. I think this is getting really clear. Couple tiny suggestions (_feel free to tell me to pound sand_):

Give your website a boost with your own custom domain name, ~~and free of~~ and remove any WordPress.com advertising. Get access to high quality email and live chat support.

Build a unique website ~~design with advanced customization tools~~ with advanced design tools, CSS editing, lots of space for audio and video, ~~plus~~ and the ability to monetize your website with ads.

**Comment by apeatling** [comment]
@rralian Thanks, updated. Good to merge?

**Comment by rralian** [comment]
👍

**Comment by rralian** [comment]
@apeatling I think the wording is good, but it looks like this is impacting the current plans pages, not just the redesign.

plans page

**Comment by apeatling** [comment]
Closing this because something went wrong with the rebase, will open a new PR.

**Pull request closed without merging**
