### PR TITLE
Updated blaze logo at marketing/traffic

### PR DESCRIPTION
**Pull request by kisankumavat85**
## Before

Screenshot 2023-01-29 230526

## After

Screenshot_20230129_230624

*

#### Testing Instructions

*

#### Pre-merge Checklist

- [x] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [x] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [x] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [x] Have you checked for TypeScript, React or other console errors?
- [x] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [x] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [x] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

Related to #72732

### CODE REVIEW

**Review by paulopmt1 — COMMENTED** [review]
Hey @kisankumavat85, thanks for contributing to Calypso! I see this is your first time here, I'm glad you want to help us improve the WordPress ecosystem.

Although your change fixes the problem, with this current strategy, if we decide to change the logo again, we would need to change it both  `client/assets/images/illustrations/blaze-drop-down.svg` and `client/assets/images/customer-home/illustration--blaze.svg` files.

Can we implement a different approach that would make maintenance easier in the future?

**Comment by therocket-gr** [comment]
Hi.. i think that we already have this svg included in the repo @paulopmt1  @allilevine 

i cant find any visual difference between the files.. maybe i am wrong  

(the location of the file is here: https://wordpress.com/calypso/images/illustration--blaze-ff6cf83b4d50076dea2e.svg )


Screenshot 2023-02-19 at 23 21 40

**Comment by paulopmt1** [comment]
> Hi.. i think that we already have this svg included in the repo @paulopmt1 @allilevine
> 
> i cant find any visual difference between the files.. maybe i am wrong
> 
> (the location of the file is here: https://wordpress.com/calypso/images/illustration--blaze-ff6cf83b4d50076dea2e.svg )
> 
> Screenshot 2023-02-19 at 23 21 40

Thanks for the information @therocket-gr, yeah, they're the same. @kisankumavat85, please let me know if you plan to continue your changes.

**Comment by paulopmt1** [comment]
As we had no feedback, we're closing this PR [and solving it here](https://github.com/Automattic/wp-calypso/pull/74376). I hope we see you again @kisankumavat85 and thanks for your contribution!

**Pull request closed without merging**
