### PR TITLE
Make the Thanks modal more informative during theme switch.

### PR DESCRIPTION
**Pull request by kwight**
The Thanks modal is rather uninformative during theme switch, possibly causing user confusion as to what's going on.

screen shot 2016-11-01 at 2 57 08 pm

We can replace the puling dot with informative text, and pulse the Visit Site button with Changing Theme text instead, like signup during site creation.

screen shot 2016-11-01 at 3 03 57 pm

### CODE REVIEW

**Comment by folletto** [comment]
> We can replace the puling dot with informative text

If we really thing this screen requires a message, I'd rather keep the pulsating dot, adding the text only when the operation is taking a while, for example:

* Pulsating dot up to 5 seconds
* Pulsating dot and text afterward

pulsating-dot-message

However...

> possibly causing user confusion as to what's going on.

I'm not sure on this assumption. Loading animations are normally widely recognized as a wait indicator. Do we have evidence of this confusion? I'd try to not add further text unless it's necessary. We already use loading indicators like this all over Calypso (i.e. skeleton loaders).

**Comment by kwight** [comment]
> Do we have evidence of this confusion?

Anecdotal, two of four internal testers commented on it: p6jOYE-Ev-p2. I'm fine keeping it as-is, and we can see if launching Headstarted theme switches results in any user feedback?

cc/ @melchoyce

**Comment by melchoyce** [comment]
Sorry, I think I miscommunicated in the p2 thread — I was expecting the pulsating dot to remain, and the "Setting up" message to appear inside the disabled primary button, which would animate similar to the NUX button: https://cloudup.com/ctZGtbXMpQm

**Comment by kwight** [comment]
As a compromise (and to avoid two things pulsing in the same dialog box), how about we change just the pending state text? It's more informative, with a minimum of changes.

screen shot 2016-11-02 at 12 03 18 pm

**Comment by melchoyce** [comment]
Sure 👍

**Comment by folletto** [comment]
> I was expecting the pulsating dot to remain, and the "Setting up" message to appear inside the disabled primary button

> As a compromise (and to avoid two things pulsing in the same dialog box), how about we change just the pending state text? It's more informative, with a minimum of changes.

I find this an excellent solution. 👍

**Comment by sirbrillig** [comment]
LGTM

**Comment by ockham** [comment]
Minor after-the-fact nitpick (sorry!) related to wording -- in the showcase, we don't really ever refer to theme "switching" but rather to theme "activation". Should we change the pending state wording to "Activating theme..."?

**Pull request merged**
