### PR TITLE
Rollout plans redesign to all locales, desktop viewports only

### PR DESCRIPTION
**Pull request by niranjan-uma-shankar**
#### Changes proposed in this Pull Request

* This is the global rollout PR for the new designs on the signup plans step. For context, read more on the experiment post pbxNRc-Hv-p2.
* Since the experiment was run for desktop viewports only, this PR launches the updated designs for desktop only. Mobile web will continue to retain its current design. 
* Most of the changes in the PR are towards removing unnecessary code. The `<PlanFeaturesComparison>` component introduced as part of this test is going to be used in signup flows only, so unlike the control version component `<PlanFeatures>` component, this new component does not have to worry about maintaining views for the Calypso /plans page. 

#### Testing instructions

* Go through the signup `onboarding` flow and confirm that the plans step matches one on one with the designs posted in the experiment post pbxNRc-Hv-p2. Try with both a free subdomain selection and custom domain selection(the first bullet point in the feature list will display the domain name for custom domains).
* For good measure, open production URL https://wordpress.com, assign yourself to treatment for this experiment from Abacus(experiment slug is `signup_plans_step_redesign_v1`, and verify that this PR's plans step page matches with treatment in production.
* Run through the site launch flow and confirm that the updated plans step UI is seen there
* Run through the signup flow in non-EN and confirm that translations are in place
* Run through the Add new site flow in non-EN and confirm that the treatment UI is present there.
* Verify that Tracks event are fired when selecting a paid plan or free plan.
* Confirm no changes to mobile web and that it's same as production

### CODE REVIEW

**Review by dzver — APPROVED** [review]
This is a massive change, and although I followed the test plan and tried a few things that were not on the test plan, I'm not sure I covered everything.

Screenshot 2021-04-12 at 15 20 35

LGTM

**Comment by niranjan-uma-shankar** [comment]
Thanks so much for the review. As you're aware, the plans components are shared between signup flow and Calypso's /plans page, so they contain a lot of logic that needs to serve both scenarios. In this case, for the new UI I retained only that code which is needed in a signup context and removed everything else, so the change ended up being pretty big. I'm just noting it here for the record in case someone else comes across this PR.

@dzver I have a question - in your screenshot, the select CTA button is orange in color but it's supposed to be in pink. I'm wondering how so. Is it because you chose a different color scheme in wpcom settings?

**Comment by dzver** [comment]
Yes, I changed the color scheme to make sure nothing breaks with the new one. It doesn't break - only a couple of colors here and there come from the color scheme. Perhaps in some future rework, we could also match the background.

**Comment by niranjan-uma-shankar** [comment]
I made a change to also show the discounted pricing in INR, PHP, MXN:

Screenshot 2021-04-13 at 10 56 46 AM

**Pull request merged**
