### PR TITLE
Subscription Management: Add wpcom header for the external  path

### LINKED ISSUE #74071: `/subscriptions`: Add wpcom header to the  page
## Design
inDLaEQV8jJ21O4WXawIsJ-fi-712%3A29015

### Desktop Version
Screen Shot 2023-03-04 at 09 16 09

### Mobile Version
Screen Shot 2023-03-04 at 09 16 16

## Acceptance Criteria
- The header should contain:
  1. WPCOM logo
  2. "Log in" button
  3. "Get Started" button 
- The mobile version of the header should instead display the hamburger icon as per the design 

## Dev Notes
I have not seen an exact implementation of the "master" header bar in Calypso. Similar one but with more menus exists for:
https://wordpress.com/plugins/ and https://wordpress.com/themes/

To add the "masterbar" from the above examples we would need to add `'subscriptions'` to [the array defined within the following condition in logged.out.jsx at line 108](https://github.com/Automattic/wp-calypso/blob/2909f576b4e5836d5eed35232b723a3333b6bd34/client/layout/logged-out.jsx#L108):
```
} else if ( [ 'plugins', 'themes', 'theme' ].includes( sectionName ) ) {
```

### PR DESCRIPTION
**Pull request by mashikag**
Fixes #74071

## Proposed Changes

* Render the `UniversalNavbarHeader` for the logged-out layout of the `subscriptions` section
* Introduce an optional `variant` prop for the `UniversalNavbarHeader` component
  *  with the current allowed values of `default` and `minimal`
  * `default` - should display as it used to before the `variant` prop was introduced
  * `minimal` - should display the WordPress.com logo on the left hand side of the bar, and "Log In" as well as "Get Started" buttons on the right hand side of the bar

## Testing Instructions

* Open incgonito window (ensure you are logged out of wpcom)
* Go to http://calypso.localhost:3000/subscriptions

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

Screen Shot 2023-03-08 at 12 15 38
Screen Shot 2023-03-08 at 12 15 50

### CODE REVIEW

**Comment by mashikag** [comment]
Screen Shot 2023-03-07 at 15 56 21


@yansern @phcp what are the plans for the header while we have the interim portal in? As mentioned during the weekly leaving the encircled in red menu items would take some load off the re-skinned portal work.  Is it ok if we go ahead like this for now? We can then create a task to remove those menu items once we will drop the interim portal?

**Comment by yansern** [comment]
> @yansern @phcp what are the plans for the header while we have the interim portal in? 

We'll follow the figma design, which is not to show the menu items. And we'll also bring this up as a topic for tomorrow's design sync for further discussion (on things related to external vs. wpcom users and the Log In / Get Started button). (going to cc @saygun anyway now.)

In the meantime, you both @mashikag @phcp can spike different ends on how to hide the menu items, as both Calypso Portal and Interim Portal are touching different codebases, Calypso Portal with Universal Header, Interim Portal with either Landpack or H4.

>  Is it ok if we go ahead like this for now? 

Yes, this will make the PR go out faster.

> We can then create a task to remove those menu items once we will drop the interim portal?

Nope, as mentioned above Paulo will try it on his end, and you will try it on your end, different codebases so there's no overlap.

That said, lower priority on Calypso Portal as I understand you have a zillion other things to take care of, higher priority for Reskinned Portal because it will be shipped next week so knowing what are the technical challenges ahead of time will be ace. https://github.com/Automattic/wp-calypso/issues/74112

**Comment by mashikag** [comment]
> > We can then create a task to remove those menu items once we will drop the interim portal?
> 
> Nope, as mentioned above Paulo will try it on his end, and you will try it on your end, different codebases so there's no overlap.

I included the change to not display the rest of the menu items, as per design.

It is worth to mention that the designs do not include as to what should be displayed when the "hamburger" icon is clicked on the mobile view of the header. With the current implementation it will look as following:
Screen Shot 2023-03-07 at 16 37 21

**Review by yansern — APPROVED** [review]
Thanks for introducing the `variant` prop for `UniversalNavbarHeader`.

Add `calypso?flags=subscription-management` when testing on Calypso Live.

Tested and works.
image

**Comment by yansern** [comment]
Also checked `/plugins` and `/themes` as logged-out user and there are no regressions.

**Pull request merged**
