### PR TITLE
State: Remove site receive effects on site updates

### PR DESCRIPTION
**Pull request by tyxla**
Unfortunately, `/me/sites` breaks the WP version in `.updates` for Jetpack sites - it rounds `4.7.3` to `4`. There might be other inconsistencies too, so this PR removes the receive/update effects of `/me/sites` on the sites updates reducer. We can always get it back if we wish.

This will allow us to keep the site updates endpoint as the single source of truth.

To test: 
* Checkout this branch
* Verify all site updates reducer tests pass:

```
npm run test-client client/state/sites/updates/test/reducer.js
```

### CODE REVIEW

**Comment by tyxla** [comment]
After digging a little into it today this appears to be a sync issue and I'd love to dig further, but maybe another time.

**Comment by mtias** [comment]
Sounds good.

**Comment by enejb** [comment]
@tyxla Can you explain the issue a bit more that this is trying to solve? More curious then anything.

**Comment by tyxla** [comment]
Thanks for asking @enejb!

In Calypso currently we have 2 good ways to fetch available updates for a Jetpack site: through the site updates endpoint, and through `/me/sites`. 

* The site updates endpoint returns everything as expected.
* `/me/sites` nicely returns `updates` for Jetpack sites, however the `wp_update_version` is incorrectly casted to an integer. It has to be `'4.7.3'`, but instead it's `4`.

I haven't spent too much time debugging it, but it appears that in the WP site the updates are being returned properly by `get_preferred_from_update_core`, so it appears the issue is occurring at sync. I intended to debug properly and finding the issue, rather than merging this one. Got any ideas what might be causing this?

**Comment by tyxla** [comment]
@enejb needed just a couple of minutes to fix this in the sync code - see r154914-wpcom.

Closing this one as it's no longer necessary. Thanks for the reviews anyway!

**Pull request closed without merging**
