### PR TITLE
Stats: Add list quick action to view generated URL on UTM modal

### PR DESCRIPTION
**Pull request by dhasilva**
Related to https://github.com/Automattic/red-team/issues/263
Closes https://github.com/Automattic/red-team/issues/263

## Proposed Changes

* Adds a quick action to open the UTM URL modal with pre-filled data so the user can copy the generated URL again or modify it as necessary
* Modified the UTM modal to allow initial data

## Why are these changes being made?

* UX improvements

## Testing Instructions

* Go to the UTM card with some visits data
* If you don't have any, generate a UTM URL with the modal tool, visit it, wait around 5 minutes and refresh
* Click on a UTM data combination to open the top posts list
* Check that on the post entry there is a new quick action to view it in the URL builder:

* Click it and check that the available data is pre-loaded on the modal (in this case, only source and medium):

Screenshot from 2024-11-20 19-43-35

* Change the UTM data filter to another combination, like "Campaign / Source / Medium" or just "Medium" and click on the action link again
* Check that only the selected data is pre-loaded

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Review by annacmc — COMMENTED** [review]
This looks great, I think it's an excellent addition. 

I tested it out with my real blog (and a real UTM string I created using the builder, to show clicks from my Instagram profile) and noticed that the campaign field isn't pulling through to pre-fill. The rest of the data is correct though. 

image
image

So I created a new one and tried again. Still, neither pre-fill the campaign field.

**Comment by dhasilva** [comment]
> So I created a new one and tried again. Still, neither pre-fill the campaign field.

Hey there, Anna :wave:

Did you select "Campaign / Source / Medium"? By default it is only "Source / Medium", so we don't have the value for the campaign there.

I tried again here and this is what I got:

Screenshot from 2024-11-21 11-48-46
Screenshot from 2024-11-21 11-49-09

In this case, campaign is not there as it is not selected in the filter, that is expected behavior.

Screenshot from 2024-11-21 11-49-29
Screenshot from 2024-11-21 11-49-43

In this case we have the value for the campaign ("promotion", I should have used another value as that is the same one as the placeholder :sweat_smile:), so it is added to the modal.

**Review by CGastrell — APPROVED** [review]
LGTM! Worked well on my tests. @annacmc I also found this behavior to be a bit confusing, but then I also realized, if the counts are NOT being grouped by campaign (as in the second screenshot shared by @dhasilva ) then campaign field could have more than 1 value, something we could not parse coherently for the UTM form.

Idea: maybe when parsing a link on the UTM form, do not show inputs/fields that are not being used to group the results?

**Review by kangzj — APPROVED** [review]
Looks good and works well!

One thing I noticed is that the naming isn't particularly consistent for the builder. In some places it's called URL Builder, and some others UTM Builder. We might want to decide on a name that goes everywhere, including the code, titles and label I guess.

Thanks for the great work! Very neat! 👍

**Comment by dhasilva** [comment]
That kinda confused me sometimes, @kangzj. "Should I call it URL builder as it builds a URL? UTM builder as that is the name of the modal? Or UTM URL builder to be more specific? :thinking:"

It is a good idea to standardize it, yes.

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/17011647

Some locales (Hebrew, Japanese) have been temporarily machine-translated due to translator availability. All other translations are usually ready within a few days. Untranslated and machine-translated strings will be sent for translation next Monday and are expected to be completed by the following Friday.

Thank you @dhasilva for including a screenshot in the description! This is really helpful for our translators.

**Comment by annacmc** [comment]
@dhasilva  you're totally right, that's exactly what was happening. It makes sense why, but is also confusing I think from a user perspective initially. 

> Idea: maybe when parsing a link on the UTM form, do not show inputs/fields that are not being used to group the results?

@CGastrell I think this is a great idea and we should consider something like this.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/17011647).

**Pull request merged**
