### PR TITLE
Emails: Cleanup unused GSuite new users code

### PR DESCRIPTION
**Pull request by tyxla**
#### Proposed Changes

#65088, #65180, and #67420 remove a bunch of legacy code related to GSuite usages. This PR is a follow-up that removes the unused collection of GSuite new user creation and validation helper functions. I'm refactoring the only usage, which happens to be a duplication of a type that exists in the `@automattic/shopping-cart` package.

#### Testing Instructions

Verify the removed code is not in use. Matticbot should report no bundle size changes.

### CODE REVIEW

**Review by noahtallen — APPROVED** [review]
Confirmed that `new-users` does not appear anywhere else in the repo 👍

**Comment by wongasy** [comment]
The change looks good, but I'm going to ask @olaseni to double check, since he worked on the unified email forms.

**Review by olaseni — APPROVED** [review]
This looks good. Google Workspace purchase works fine. Thanks for the cleanup.

**Comment by tyxla** [comment]
Thank you all for taking a look 🙌

**Pull request merged**
