### PR TITLE
Add WordPress.com > Site Tools page and Other tools section

### PR DESCRIPTION
**Pull request by candy02058912**
Fixes https://github.com/Automattic/dotcom-forge/issues/5486

## Proposed Changes
We'll eventually move items under Settings that are not wp-admin core to WordPress.com > Site tools

other tools

## Testing Instructions

* Go to /settings/site-tools/:site

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

**Comment by taipeicoder** [comment]
The approach LGTM! As we move settings to this page, we need to be mindful of making them:

1. Modular - In case we need to move them to a different page.
2. Reusable - So that the same component is used between the existing Calypso pages and the new page.

**Comment by candy02058912** [comment]
> The approach LGTM! As we move settings to this page, we need to be mindful of making them:
> 
> 1. Modular - In case we need to move them to a different page.
> 2. Reusable - So that the same component is used between the existing Calypso pages and the new page.

Same thoughts here! Let's merge this one in to get started. As the settings we're moving are not new features, we can merge and continue to iterate.

**Review by taipeicoder — APPROVED** [review]
LGTM 👍 
The Back button in Transfer/Reset/Delete your site are hard-coded to `/settings/general/${site_slug}` but that's something we can address later on, since this page is not public discoverable yet.

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/11276520

Some locales (Hebrew, Japanese) have been temporarily machine-translated due to translator availability. All other translations are usually ready within a few days. Untranslated and machine-translated strings will be sent for translation next Monday and are expected to be completed by the following Friday.

Thank you @candy02058912 for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/11276520).

**Pull request merged**
