### PR TITLE
Performance Profiler: Add an example email report to the banner

### PR DESCRIPTION
**Pull request by epeicher**
Resolves https://github.com/Automattic/dotcom-forge/issues/9151

|Logged-in | Logged-out|
|-------|------|
|CleanShot 2024-09-16 at 18 00 21@2x| CleanShot 2024-09-16 at 18 00 13@2x|

## Proposed Changes

* Adds an example email report to the newsletter banner

## Why are these changes being made?

* To show the user what to expect when subscribing to the report

## Testing Instructions

* Apply this patch
* Open the profiler tool and run a test
* Check the newsletter banner contains an image as per Figma
* For small screens, the text should wrap as suggested here p1726564500775119/1726496035.364039-slack-C07AV9N4Y1H
* Check in Mobile view, the banner image is not displayed

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Review by gavande1 — COMMENTED** [review]
Thanks for working on this Roberto! 

I think the image needs to hidden on when viewing on smaller screen. 

CleanShot 2024-09-18 at 12 19 36@2x

**Comment by epeicher** [comment]
> I think the image needs to hidden on when viewing on smaller screen.

@gavande1 That was discussed here p1726564500775119/1726496035.364039-slack-C07AV9N4Y1H as indicated in the [testing instructions](https://github.com/Automattic/wp-calypso/pull/94585#issue-2528889705). @matt-west suggested hiding the image in `mobile` viewport, but we can hide them in other smaller screens if needed, please advise.

**Review by gavande1 — APPROVED** [review]
I think we can deploy current version and iterate if needed. LGTM 👍

**Comment by matt-west** [comment]
The screenshot is super-blurry for me in Safari. Can you try a PNG rather than the SVG.

Screenshot 2024-09-18 at 09 21 41

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/16852257

Some locales (Hebrew, Japanese) have been temporarily machine-translated due to translator availability. All other translations are usually ready within a few days. Untranslated and machine-translated strings will be sent for translation next Monday and are expected to be completed by the following Friday.

Thank you @epeicher for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/16852257).

**Pull request merged**
