### PR TITLE
Pricing page rework: Create section and heading for most popular items

### PR DESCRIPTION
**Pull request by manzoorwanijk**
#### Proposed Changes

* Create `MostPopular` component to display both the most popular products as well as bundles.

#### Testing Instructions

* Boot up this PR 
    * Run `git fetch && git checkout add/jp-pricing-rework/most-popular-section`
    * Run `yarn start-jetpack-cloud`
    * Goto [http://jetpack.cloud.localhost:3000/pricing?flags=jetpack/pricing-page-rework-v1](http://jetpack.cloud.localhost:3000/pricing?flags=jetpack/pricing-page-rework-v1)
* Or click on Jetpack Cloud live link below
    * Goto `/pricing?flags=jetpack/pricing-page-rework-v1`
* Confirm that you see the most popular items section for both products as well as bundles.
* Confirm that the design matches the Figma design
* Confirm that it looks good on both Desktop and Mobile

#### Pre-merge Checklist

- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?

Completes 1202796695664022-as-1202796695664099/f
Figma: m0y1jHTuDpvMPkFsOJBoNP-fi-3711%3A119683

Screenshot 2022-08-25 at 5 57 14 PM

Screenshot 2022-08-25 at 5 57 35 PM

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - 0-as-1202796695664099
  - 0-as-1202796695664120

### CODE REVIEW

**Comment by jkguidaven** [comment]
@manzoorwanijk  The code LGTM 💯 ..

Just minor change to the font size. The Figma says it should be 24px.

**Comment by manzoorwanijk** [comment]
> Just minor change to the font size. The Figma says it should be 24px.

Thank you for pointing that out @jkguidaven. We usually set `font-size` in `em` or `rem` and it's pre-defined for the codebase. So, as long as the look matches Figma, it's fine to use the existing CSS rules.

**Comment by jkguidaven** [comment]
Ahh I see. thanks for explaining it @manzoorwanijk 👍

**Review by jkguidaven — APPROVED** [review]

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/7496693

Thank you @manzoorwanijk for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/7496693).

**Pull request merged**
