### PR TITLE
Stats: Adjust the Stats purchase page layout on mobile

### PR DESCRIPTION
**Pull request by dognose24**
Related to #84885

## Proposed Changes

* Make the purchase page layout more responsive to the window size.
* Adjust the font size on a smaller screen.

截圖 2024-04-04 上午12 30 31
截圖 2024-04-04 上午12 30 38

## Testing Instructions

* Spin this change up with the Calypso Live branch.
* Navigate to the Stats **personal / commercial** purchase page: `/stats/purchase/{site-slug}?productType=personal(commercial)`.
* Resize the browser window to any width.
* Ensure the page layout is responsive and works well for mobile viewports.

|Full size|>= 960px|>= 782px|> 600px|<= 600px|
|-|-|-|-|-|
|full_size|width_961|width_782|width_780|width_453|

|Full size|>= 960px|>= 782px|> 600px|<= 600px|
|-|-|-|-|-|
|截圖 2024-04-04 上午12 21 05|截圖 2024-04-04 上午12 21 48|截圖 2024-04-04 上午12 22 09|截圖 2024-04-04 上午12 22 23|截圖 2024-04-04 上午12 22 40|

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Review by ederrengifo — CHANGES_REQUESTED** [review]
This looks great! The only change I would suggest is to put the actions items full-width and vertically aligned for mobile views since it's a common good practice. Is it possible?
Screenshot 2024-04-03 at 12 29 49

**Comment by dognose24** [comment]
> put the actions items full-width and vertically aligned for mobile views

Addressed the full-width action buttons on mobile for all sites in https://github.com/Automattic/wp-calypso/pull/89124/commits/3e28e48ac178268603ee01d0f92c0d7c9bb45d4a.

**Review by ederrengifo — APPROVED** [review]
LGTM

**Review by kangzj — APPROVED** [review]
Thank you so much for tackling this! I love it! ❤️ 

Two things I noticed:

1. The commercial purchase button doesn't take up the whole width for narrower screen

image

2. I don't know whether this is intended, that the disputation section now takes up the whole width:

image

Happy to ship and iterate!

**Comment by kangzj** [comment]
I would love to see this before rolling out https://github.com/Automattic/wp-calypso/pull/89181, so I'm merging it 😄

**Comment by dognose24** [comment]
@kangzj Thanks for the feedback!

> The commercial purchase button doesn't take up the whole width for narrower screen

That was intended because I feel like making the button full-width on a tablet device would be too much so I only adjust the button for `width <= 600px`.

> the disputation section now takes up the whole width

Is there any concern about taking the full width for the disputation section? I feel like the layout would be nice since the content has been aligned left. 🙂

**Pull request merged**
