### PR TITLE
Remove the legacy lib/perfmon module obsoleted by RUM

### PR DESCRIPTION
**Pull request by jsnajdr**
There is a legacy `lib/perfmon` library that sends page load timings to statsd/Grafana. It has been used only on the Stats page. As it has been completely superseded by the RUM tracking in `lib/performance-tracking`, it's time to remove it.

### CODE REVIEW

**Review by sgomes — APPROVED** [review]
LGTM, code-wise. Do we have any way of confirming there is currently no-one relying on this?

**Comment by jsnajdr** [comment]
> Do we have any way of confirming there is currently no-one relying on this?

The Grafana dashboards still exist but I don't think anyone looks at these now when we have RUM data that are much better.

**Comment by sonthipongmoojun** [comment]
> There is a legacy `lib/perfmon` library that sends page load timings to statsd/Grafana. It has been used only on the Stats page. As it has been completely superseded by the RUM tracking in `lib/performance-tracking`, it's time to remove it.

**Comment by sonthipongmoojun** [comment]
> There is a legacy `lib/perfmon` library that sends page load timings to statsd/Grafana. It has been used only on the Stats page. As it has been completely superseded by the RUM tracking in `lib/performance-tracking`, it's time to remove it.

**Pull request merged**
