### PR TITLE
Add email stats for devices & clients

### PR DESCRIPTION
**Pull request by TimBroddin**
#### Proposed Changes

This PR adds the data logic & UI for the devices & clients panels in email open stats.

In detail, it:

* Adds the Redux logic (routing/transforming the incoming data from the API to the store)
* Adds the UI for the panel
* Adds a grid layout for email open stats
* Adds titles to the panels
* Does a bit of cleanup:
  - Use `<StatsEmailModule>` directly, instead of creating a separate proxy component for every stat type
  - Remove the preview code from the `<StatsEmailOpenDetail>` module

#### Testing Instructions

* Visit `/stats/email/open/<site>/day/<postid>?flags=newsletter/stats`. You can add the startDate parameter, to load the stats for a specific date.
* Ensure the cards are rendered:

CleanShot 2023-01-04 at 14 28 47@2x

#### Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

Related to #

### CODE REVIEW

**Review by JuanLucha — APPROVED** [review]
Very nice job! 🏅

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/7710323

Thank you @TimBroddin for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/7710323

Thank you @TimBroddin for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/7710323).

**Pull request merged**
