### PR TITLE
Checkout: Show recent renewals during checkout

### PR DESCRIPTION
**Pull request by sirbrillig**
This adds a new component called RecentRenewals to the checkout page, just above the terms of service, which lists all recent renewals and their expiration dates. This is intended to help prevent people from accidentally renewing a product that was just renewed recently.

Requires D21954-code to be applied.

recentrenewals

## Testing

Visit http://calypso.localhost:3000/checkout for a renewal, and be sure you see a list of recently renewed products.

## To do

- [x] Some products don't have a name for some reason.
- [ ] It takes a long time to fetch the data from the server (maybe this won't be as long in production?).
- [x] Should we filter out some products (eg: domain mapping/privacy for a domain that's also listed)?
- [x] We need to add this component to the other forms, more than just Credit and CreditCard.
- [x] We should show the actual domain, if present, rather than the `.wordpress.com` version.
- [ ] Make sure this only shows on renewals and not on other kinds of checkout?

### CODE REVIEW

**Comment by nbloomf** [comment]
Filtering out mapping makes sense - with the domains plans change it's not really an independent product anymore, since it's always attached to either a domain or a plan.

As for privacy, it may make sense to filter it too, although I'm less sure of that.

**Comment by nbloomf** [comment]
Also I think the actual domain name is available as either `meta` or `blogname` (in the examples I'm using, it appears in both, although using meta seems risky)

**Comment by sirbrillig** [comment]
I filtered out anything without a name, which conveniently gets rid of mapping and privacy. Hopefully if either of those is independent, it will come with a name included.

**Comment by nbloomf** [comment]
lgtm

**Pull request merged**
