### PR TITLE
DevDocs / State: Add DevDocs screen for searching state selectors

### PR DESCRIPTION
**Pull request by aduth**
Related: #5954

This pull request seeks to add a new screen to the [DevDocs section](https://wpcalypso.wordpress.com/devdocs) to enable a developer to search for available selectors. Search is fuzzy, enabling generic searches like "getSite" to return the `getSelectedSite` selector, but in less precedence than the `getSite` selector.

Search View | Single View
---|---
Search|Detail

__Implementation Notes:__

Fuzzy searching uses [Fuse.js](http://fusejs.io). The DevDocs section already uses another similar library [Lunr.js](http://lunrjs.com) for full text search, though this library does not have great support for fuzzy searching, and it was important for me to support.

The selector parsing is cached, though not to the filesystem as in the case of document searching. Any request to any section of DevDocs will start "priming" the selector cache and this cache will be used for the remainder of the server process.

Included are several examples of selectors that will be removed prior to merging. See #5954.

__Testing Instructions:__

1. Navigate to [DevDocs State Selectors](http://calypso.localhost:3000/devdocs/selectors)
2. Note that all selectors from the `client/state/selectors` are visible with description
3. Enter a search term
4. Note that fuzzy results are shown in order of matching precedence
5. Click a result
6. Note that selector is shown with arguments are return type
7. Click Back
8. Note that you're returned to search results

__Open Questions / Ideas:__

- If we were to parse the file using a proper JavaScript parser, we could interpret arguments even for selectors without good JSDoc, though I argue it's better to encourage good documentation by using them as a prerequisite for arguments displaying
- Search only applies to selector name and description, though we could also apply this to parameters or return types (e.g. search all selectors that accept `siteId` as a parameter)
- What other [JSDoc tags](http://usejsdoc.org) would be useful to include aside from `@param` and `@return`? Another good option may be `@see` for external resources.

cc @withinboredom

### CODE REVIEW

**Comment by mtias** [comment]
@aduth pushed some style tweaks:

image

**Comment by nb** [comment]
One functional request: could we add the filename of the selector? It helps a ton with the `import` statement.

**Comment by aduth** [comment]
>One functional request: could we add the filename of the selector?

This is intended to be part of the migration toward global selectors (#5954), at which point importing the selector will always follow the pattern of:

```js
import { getWonderfulThing } from 'state/selectors';
```

**Comment by aduth** [comment]
Pushed a rebase to resolve conflicts. I'm planning to take a closer look to ensure that there won't be a worrying impact of storing the Fuse instance in memory (particularly that it isn't run in production).

@mtias : A few comments on your design revisions:

The padding looks a tiny bit off on the bottom when there's no DocBlock to be inferred from a selector (guessing this was increased to account for arguments/returns headers):

image

The font choice of monospace for the argument description seems inconsistent with the return value description. In [your screenshot](https://cloud.githubusercontent.com/assets/548849/20967346/50b1ed64-bc7f-11e6-8d87-7dc24527bb48.png) I would expect "Site object" (return value) and "Global state tree" (argument) to receive the same text treatment.

**Comment by aduth** [comment]
DevDocs will never be loaded in production [thanks to this condition](https://github.com/Automattic/wp-calypso/blob/ab958f34212ae05502325b61b1f13266f48d7e79/server/boot/index.js#L62).

Pushed two more commits:

- 5af48ef  avoids an error which occurs when the selectors directory does not exist (since we'll have none to start with after dropping 70dd703)
- 5befd12 shows Drake for empty results ([screenshot](https://cloud.githubusercontent.com/assets/1779930/21018416/c6d26634-bd3a-11e6-8732-8d1462521170.png))

**Pull request merged**
