### PR TITLE
Logged Out Theme Showcase: Add new categories to SEO map

### PR DESCRIPTION
**Pull request by rcrdortiz**
Related to https://github.com/Automattic/dotcom-forge/issues/3311

## Proposed Changes

* Added the new Categories to the SEO map that we've added to the Logged Out Theme Showcase.

| Before | After |
|--------|--------|
|Captura de Pantalla 2023-08-15 a las 14 09 53|Captura de Pantalla 2023-08-15 a las 14 10 04| 

## Testing Instructions

* While logged-out, visit `/themes`.
  * If you are running Calypso locally, ensure [the SSR is in debug mode](https://github.com/Automattic/wp-calypso/blob/trunk/docs/server-side-rendering.md#debugging).
* Change subjects and pricing filters.
* Check the page's heading and sub-heading, and ensure the copy matches the hardcoded list provided in https://docs.google.com/spreadsheets/d/1dulcaxW-zORE7RvDMZEUHt86AFvf9hzgtHXYpUUHMRY/edit?usp=sharing.
* Inspect the page source, and ensure the `<title>` and `<meta name="description">` tags too match the hardcoded list.
* Open `/themes` while logged-in.
* Ensure the header looks like this and does not changes depending on the filters.
  Screenshot 2023-07-25 at 18 48 45

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

**Review by mmtr — COMMENTED** [review]
Most of the changes look good to me. I'm not sure about these – they read a bit awkward to me:

- your coming soon website
- your community and non-profit website
- your authors and writers website

Maybe it's just me although I don't have any better alternative. Perhaps @sailerbe can double check?

**Comment by sailerbe** [comment]
@mmtr I agree these read a bit awkward. I'll rewrite those three (and will check to see if there are others we should consider rewriting as well) and will share updated versions of the copy here. I should be able to do this today or tomorrow.

**Comment by rcrdortiz** [comment]
Yeah, some look a bit off. I'll leave this on hold until we get @sailerbe's copy changes.

**Comment by Copons** [comment]
@rcrdortiz just a note that the SEO map is moving soon to another file to fix an i18n bug: https://github.com/Automattic/wp-calypso/pull/80617

After the merge-that-and-rebase-this dance, it should be a simple matter of copy-pasting these changes to the new file.

**Comment by sailerbe** [comment]
@mmtr How do these changes sound:

- Find the perfect theme for your website that's under construction.
- Find the perfect theme for your non-profit or community organization's website.
- Find the perfect theme for your author website.

**Comment by rcrdortiz** [comment]
> @mmtr How do these changes sound:
> 
> * Find the perfect theme for your website that's under construction.
> * Find the perfect theme for your non-profit or community organization's website.
> * Find the perfect theme for your author website.

Hey @sailerbe! Most of them sound fine except for the first and last ones. `Find the perfect theme for your author website`. The category name includes both `author` and `writer` while the description just includes `author` this might be a bit confusing for our users.

On the other hand, the `coming-soon` category doesn't necessarily have to be for a site that's under construction, these types of sites are frequently used for product launches where you want to capture leads or get customers to subscribe to a newsletter before you actually launch a product (testing market fit of a new product before actually launching it).

**Comment by mmtr** [comment]
@rcrdortiz I think author and writer can be used interchangeably.

I agree with with the "under construction" concern though. Maybe this is less confusing?

- Find the perfect theme for your coming soon landing page.

Also, do we need to change the titles? This is how they look currently:
- Coming Soon WordPress Themes
- Community & Non-Profit WordPress Themes
- Authors & Writers WordPress Themes

**Comment by sailerbe** [comment]
@mmtr @rcrdortiz Noted on all of the above. I also noticed that none of the new categories that have been added have bespoke title tags. For convenience, I put together updated header copy and title tags into this spreadsheet:

[](https://docs.google.com/spreadsheets/d/1t2IVBcCSEuEn9Oq76fI8YoHUGgrCY3g0Bdy9Lckpssk/edit#gid=0
)

Let me know if you have any further changes, or if anything still isn't sounding quite right.

**Comment by mmtr** [comment]
Thanks @sailerbe. I pushed your suggestions in the last commit except for one bit. You suggested "Choose from free and premium options" but that's not part of the current SEO content for other categories, since we say "Browse high-quality, professionally-designed options" instead. Are you sure you want us to diverge from that?

I created this other spreadsheet where you can easily check the content of all existing and new categories: https://docs.google.com/spreadsheets/d/1dulcaxW-zORE7RvDMZEUHt86AFvf9hzgtHXYpUUHMRY/edit?usp=sharing

New categories are highlighted with green, and those with a darker green are "hidden" categories (we hide categories with less than 3 themes so the URLs don't work yet, but they'll show up as soon as theme developers launch more themes).

**Comment by sailerbe** [comment]
@mmtr Ah, that is a good catch. What you have in this spreadsheet looks good on my end. Looking forward to seeing these improvements shipped!

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/8794969

Thank you @rcrdortiz for including a screenshot in the description! This is really helpful for our translators.

**Comment by emilyaudela** [comment]
HI there! We noticed that several strings refer to the Ecommerce plan. I might be wrong, but hasn't the name of the plan changed to the Commerce plan? (See wordpress.com/pricing). Just want to make sure we are being consistent with the translations. Maybe we are using "Ecommerce" for SEO purposes?

 cc: @sailerbe

**Comment by sailerbe** [comment]
@emilyaudela Ah, that is a good catch as well. We should say Commerce. @mmtr I've updated the spreadsheet to reflect this correction as well.

**Comment by mmtr** [comment]
Thanks! Renamed all instances of "Ecommerce" to "Commerce" if the last commit.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/8794969).

**Pull request merged**
