### PR TITLE
Sidebar: Switching the customize and theme links around in the sidebar.

### PR DESCRIPTION
**Pull request by shaunandrews**
Context: let's switch the Customize and Themes buttons in the sidebar.

(From Lance: This was planned for a future navigation rework, but we'd like to pull this one change out sooner and do it now.)

Here's the before:
screen shot 2018-05-01 at 9 55 09 am

And here's the after:
screen shot 2018-05-01 at 9 54 58 am

### CODE REVIEW

**Comment by lancewillett** [comment]
@Automattic/delta-samus will pick this one up — thanks for the quick PR.

**Comment by lancewillett** [comment]
I did a test using the Live Branch environment in Mac-n-Chrome with a test account. Both links work well.

I think we still need to adjust or adapt the Tracks events, then it should be 👍 .

**Comment by frontdevde** [comment]
screen shot 2018-05-01 at 16 48 52

^ On Atomic/Jetpack sites the external link icon now overlaps the text.

**Comment by lancewillett** [comment]
Context: simply switch the two buttons. That's it, plain and simple.

**Comment by lancewillett** [comment]
When I tested with a few Jetpack (non-Atomic) sites, I didn't see the external icon.

**Comment by lancewillett** [comment]
Thank you @jblz Let's fix that in a 2nd PR.

**Comment by frontdevde** [comment]
I hid the icon in a follow up commit. I think this works for now to get this merged. Checking production it looks like that's what we've been doing so far anyways.

**Comment by lancewillett** [comment]
Thanks for the quick work, team!

**Comment by frontdevde** [comment]
Sure! 💪🚀Should be live in production now 👍

**Comment by lancewillett** [comment]
Good point from @shaunandrews — we'll want to make the same change on the front-end Masterbar.

1. WP.com (backend in PHP)
2. Jetpack (in the plugin, in PHP)

**Comment by jblz** [comment]
@lancewillett WP.com change is in D12648-code

RE: Jetpack, the arrangement is a bit different, so not sure what we want to do there.

From a frontend page, `Customize` is top-level on the bar & `Themes` is buried under a dropdown. It looks like:
screen shot 2018-05-01 at 5 07 43 pm

In wp-admin, they're both items underneath `Appearance` like this:
screen shot 2018-05-01 at 5 06 46 pm

...& drilled-in:

screen shot 2018-05-01 at 5 10 54 pm

**Comment by jblz** [comment]
Oh, whoops -- I forgot about the option to enable the WP.com toolbar on Jetpack.

screen shot 2018-05-01 at 5 15 28 pm

Will work on a PR for it.

**Comment by jblz** [comment]
Jetpack change proposed here: https://github.com/Automattic/jetpack/pull/9460

**Comment by alisterscott** [comment]
Should we have this for the "all sites" sidebar also, it seems a bit clunky to have a main menu item immediately then show a site picker:

themes all sites

**Comment by ockham** [comment]
FWIW, this was A/B tested ages ago (#4745) but reverted at the time (#5609). Curious why it was decided to implement this change after all?

(https://github.com/Automattic/wp-calypso/pull/24587#issuecomment-385824796 is a major drawback IMO.)

**Comment by lancewillett** [comment]
Hi Bernie, the context is in the original message ^ — it's part of a planned iteration and requested by Matt M to do it now instead of waiting.

**Pull request merged**
