### PR TITLE
Reader full post: remove from section CSS and import style.scss in component instead

### PR DESCRIPTION
**Pull request by bluefuton**
Now that we can build CSS assets with Webpack (#26820), this PR switches Reader's full post styles to be loaded by the component rather than via the `reader-full-post` section.

#### Testing instructions

Load some Reader full posts and ensure that the styles are applied correctly. A good test post is:

http://calypso.localhost:3000/read/feeds/58215415/posts/1926776088

### CODE REVIEW

**Comment by westi** [comment]
LGTM

**Comment by jsnajdr** [comment]
There's one little gotcha: the styles will be available when importing the main component:
```js
import FullPost from 'blocks/reader-full-post';
```

But what if some section imports just the header?
```js
import FullPostHeader from 'blocks/reader-full-post/header';
```

Then there are no styles for `reader-full-post__header`! It turns out that devdocs do exactly this and the example for the header component is broken:

https://hash-1d17e84edb171730dfe3829a7f12848c3b80409c.calypso.live/devdocs/blocks/reader-full-post-header

**Comment by bluefuton** [comment]
Thanks for the heads up @jsnajdr! 

Is it best to break the header styles out into their own stylesheet then?

Sidenote: ReaderFullPostHeader probably doesn't need to be in Devdocs as its not readily reusable :)

**Comment by jsnajdr** [comment]
@bluefuton If the header component devdocs example doesn't make any sense, then we can remove it and then your `style.scss` patch is correct -- the only thing people ever import is `blocks/reader-full-post` and all submodules are private.

If you want to keep the devdocs example for any reason, then header styles should have their own stylesheet -- they can be loaded independently from the rest.

I'm not familiar enough with Reader to decide what's the best solution.

**Comment by bluefuton** [comment]
Thanks @jsnajdr. I'm not sure there's much value in having a Devdocs example just for the header, so I've removed it.

**Review by jsnajdr — APPROVED** [review]
Thanks for the devdocs update, the patch is ready to :ship: now :+1:

**Pull request merged**
