### PR TITLE
Site Migration: Add test helper to render steps

### PR DESCRIPTION
**Pull request by gabrielcaires**
Related to #87643 

## Proposed Changes

* Add initial tests to the site migration plugin install step
* Add a utility to test to simplify the rendering of the test
## How it works?

The goal is to have a reliable, fast, and flexible test suite where we can quickly introduce new changes based on the project evolution without running manual tests on every PR.

To reach this goal, we need to follow some principles:

- Render the component in a way that most closely resembles browser rendering.
- Intercept the API requests at the lowest level possible to ensure we pass the required parameters and handle the endpoint answer.  Nock is the tool we have now to do it.
- Simulate the user behavior as closely as possible when the user finishes interacting with the component. In this case, I am using navigation. submit` to identify if the user can finish the step.

## Testing instructions

**Scenario 1:** 
We accidentally introduced a change that breaks our API calls

- Go to the file https://github.com/Automattic/wp-calypso/blob/30c79fb8a40784b88fc7c81084f6ea9fa91cd14e/client/landing/stepper/declarative-flow/internals/steps-repository/site-migration-plugin-install/index.tsx?plain=1#L39 and remove the line we are using to call the endpoint ``/sites/${ siteId }/plugins/migrate-guru%2fmigrateguru`,`
- Run the test suite and check if the test suite provides feedback about it.

**Scenario 2:**
Update the code without affecting the tests

- Reset the Scenario 1 changes.
- Wrap the component `h1` https://github.com/Automattic/wp-calypso/blob/30c79fb8a40784b88fc7c81084f6ea9fa91cd14e/client/landing/stepper/declarative-flow/internals/steps-repository/site-migration-plugin-install/index.tsx?plain=1#L68C7-L68C58 with a div `<div><h1....></h1><div>
- Run the tests and check if they are green.

### CODE REVIEW

**Comment by markbiek** [comment]
> Just to break the tests modifying the URL (optional)

@gabrielcaires I'm not sure I fully understand what to do here. Can you provide more detail/context on the testing instructions?

**Comment by gabrielcaires** [comment]
> > Just to break the tests modifying the URL (optional)
> 
> @gabrielcaires I'm not sure I fully understand what to do here. Can you provide more detail/context on the testing instructions?

Since it is a PR that is introducing tests,  the only suggestion I could think of is to introduce a change in the target code to see if the test is breaking. But it is pretty optional.

**Comment by markbiek** [comment]
> > > Just to break the tests modifying the URL (optional)
> > 
> > 
> > @gabrielcaires I'm not sure I fully understand what to do here. Can you provide more detail/context on the testing instructions?
> 
> Since it is a PR that is introducing tests, the only suggestion I could think of is to introduce a change in the target code to see if the test is breaking. But it is pretty optional.

It would be helpful if you provided an example 😄

**Comment by gabrielcaires** [comment]
@markbiek 
I updated the PR description describing the overall approach and with 2 test scenarios.

**Review by markbiek — APPROVED** [review]
LGTM!

**Pull request merged**
