### PR TITLE
Multi-Domain: Added experiment to multi-domain flow

### PR DESCRIPTION
**Pull request by paulopmt1**
Related to 4293-gh-Automattic/dotcom-forge

## Proposed Changes

* Connected Multi-Domain flow to the experiment stead of config flag

## Testing Instructions

* Apply this diff: D126351-code
* Open this experiment on Abacus: `calypso_onboarding_domains_multi_domain_selection`
* Follow this guide (pb5gDS-2nD-p2#manually-assigning-a-user-to-an-experiment) to manually test the experiment
* Ensure you get the production interface if you have the `control` flag, and the Multi-Domain interface if you are at the `treatment` group

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

**Review by DustyReagan — COMMENTED** [review]
I noticed one more `shouldUseMultipleDomainsInCart` call that needs the `currentUser` passed to it [here](https://github.com/Automattic/wp-calypso/blob/88085514970ddddc9733ab505efd79436abbc4f1/client/components/domains/domain-registration-suggestion/index.jsx#L199).

Otherwise, it looks good and tests well!

**Comment by candy02058912** [comment]
Rebasing to pass the Code style checks

**Review by lupus2k — APPROVED** [review]
LGTM 🎉

**Review by DustyReagan — APPROVED** [review]
Looks good and tests well!

**Pull request merged**
