### PR TITLE
Update "cross-env" to the latest version, which includes a fix for commands in Windows with undefined env variables

### LINKED ISSUE #16452: npm start, Error: Cannot find module '%NODE_ARGS%'
**Platform**: Windows
**Node**: 6.11.1
**npm**: 3.10.10

        Asset     Size  Chunks                    Chunk Names
    bundle.js  4.22 MB       0  [emitted]  [big]  main
bundle.js.map  5.39 MB       0  [emitted]         main
  [15] ./server/config/index.js 858 bytes {0} [built]
 [639] ./package.json 11.7 kB {0} [built]
 [640] ./index.js 1.54 kB {0} [built]
 [641] ./server/boot/index.js 1.98 kB {0} [built]
 [642] ./server/build/index.js 1.48 kB {0} [built]
 [644] ./server/config/parser.js 1.79 kB {0} [built]
 [645] ./client/lib/create-config/index.js 2.65 kB {0} [built]
 [647] ./server/pages/index.js 13.9 kB {0} [built]
[1209] ./server/isomorphic-routing/index.js 3.67 kB {0} [built]
[1764] ./server/pages/analytics.js 1.63 kB {0} [built]
[1767] ./server/user-bootstrap/index.js 1.4 kB {0} [built]
[1770] ./server/bundler/index.js 2.97 kB {0} [built]
[1776] ./server/devdocs/index.js 8.3 kB {0} [built]
[1790] ./server/api/index.js 457 bytes {0} [built]
[1791] ./server/api/oauth.js 2.7 kB {0} [built]
    + 1780 hidden modules
Time: 41s 87.520ms
openssl config failed: error:02001003:system library:fopen:No such process
openssl config failed: error:02001003:system library:fopen:No such process
openssl config failed: error:02001003:system library:fopen:No such process
openssl config failed: error:02001003:system library:fopen:No such process
module.js:471
    throw err;
    ^

**Error: Cannot find module 'C:\Apps\blogs-calypso\%NODE_ARGS%'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:504:3
events.js:160
      throw er; // Unhandled 'error' event
      ^**

Looks like it is because of "docs" files.
What could be the issue?

Thanks,
Bala

### PR DESCRIPTION
**Pull request by DanReyLop**
Fixes #16452
Closes #19084

The latest version of `cross-env` (`5.1.1`) includes a fix to #16452.
The fix is: https://github.com/kentcdodds/cross-env/pull/149
Now the behaviour of commands like `cross-env node $UNDEFINED_VAR index.js` is expanding the variable
to the empty string, both in Windows and in UNIX.

To get the new version of `cross-env` working, I had to change all `cross-env` commands to `cross-env-shell`,
as this was a breaking change on `cross-env@5`.

**To test**: run `npm start` on a Windows `cmd.exe` shell, check that it works.

cc/ @Viper007Bond @withinboredom

### CODE REVIEW

**Comment by afilp** [comment]
@DanReyLop Can you please resolve the conflict and let this be merged? It is great that you solved the problem!

**Comment by DanReyLop** [comment]
I've just fixed the conflict, but I need a reviewer to approve this change. @sirreal @gwwar ? I just need someone to double-check it works in UNIX (there's no reason why it shouldn't), I've tried `npm start` in Windows and it works as expected.

For reference, in `cross-env 5.0.0` there was a breaking change, to get the old `cross-env` behaviour we need to use instead `cross-env-shell`, that's the only change in this PR apart from bumping the version.

**Comment by Viper007Bond** [comment]
Tested in both in `cmd.exe` and WSL (Ubuntu) and it works great! 👍

**Comment by afilp** [comment]
Great! Thank you again.

**Pull request merged**
