### PR TITLE
Help Center: Handle closed chats

### PR DESCRIPTION
**Pull request by heavyweight**
Screenshot 2024-11-18 at 11 37 43

Fixes https://github.com/Automattic/dotcom-forge/issues/9775

Related patch:
D166397-code

## Proposed Changes

* Add footer for closed conversations

## Why are these changes being made?

* Closed interactions should be marked and treated differently

## Testing Instructions

* Checkout the related patch
* Checkout this PR
* Using the `help-center-experience` flag open the support history
* Start a chat with support
* Find the relevant ticket in staging, and mark it as solved
* Open the support history again and locate and open the chat
* The footer for closed interactions should display
* Clicking on the button should create a new chat

### CODE REVIEW

**Comment by escapemanuele** [comment]
What a great PR!

I'm testing things, meanwhile I spotted a weird hover state on the button

image

**Review by escapemanuele — APPROVED** [review]
Looks great @heavyweight

**Comment by renancarvalho** [comment]
Nice PR @heavyweight 
I have spotted the same as Emanuele, plus I noticed the rating message automatically sent, is it intended
image

**Comment by heavyweight** [comment]
> Nice PR @heavyweight I have spotted the same as Emanuele, plus I noticed the rating message automatically sent, is it intended image

This looks like an automation running on staging. We could take a look at it at a later stage.

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/17013051

Some locales (Hebrew, Japanese) have been temporarily machine-translated due to translator availability. All other translations are usually ready within a few days. Untranslated and machine-translated strings will be sent for translation next Monday and are expected to be completed by the following Friday.

Thank you @heavyweight for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/17013051).

**Pull request merged**
