### PR TITLE
Purchases: display correct renewal date for Jetpack plans

### PR DESCRIPTION
**Pull request by vindl**
Closes https://github.com/Automattic/wp-calypso/issues/13307

Unlike Dotcom plans which auto renew one month before the subscription expires, Jetpack plans renew on the expiration date. In order to avoid confusion display the correct date in purchases section.

### Testing instructions
- Please follow the instructions available in https://github.com/Automattic/wp-calypso/issues/13307

### CODE REVIEW

**Comment by vindl** [comment]
Hi @janm6k, I attempted to lessen confusion for the customers here based on your comment in pNPgK-2uc-p2. Let me know if the approach makes sense.

**Comment by janm6k** [comment]
If API returns field for renew date, and it is wrong, I think we should fix it in the API rather than building logic to fix the problem on frontend.

**Comment by vindl** [comment]
> If API returns field for renew date, and it is wrong, I think we should fix it in the API rather than building logic to fix the problem on frontend.

@janm6k Makes sense. Is renewal date calculation documented somewhere - I'd just like to verify what date should be returned here and why is it different for Jetpack plans?

**Comment by janm6k** [comment]
Replied on the p2 post.

**Comment by vindl** [comment]
> Replied on the p2 post.

Thanks! Closing this for now. I'll continue the discussion in the post and investigate the API side of things.

**Pull request closed without merging**
