### PR TITLE
Fix/jetpack plugins remove component

### PR DESCRIPTION
**Pull request by johnHackworth**
This PR removes the component "plugin-card-header", who by know were pretty much doing nothing but adding a <div>. 

It also updates `/client/my-sites/plugins/plugin-sections` to ES6 (because I couldn't commit the changes if I didn't do it before :D )

User-wise, there should be no visible change.

Before:
image

After:
image

How to test
=========
Go to any plugin (you need to have at least a jetpack site connected to your account) and check the sections header is still there. For example, http://calypso.localhost:3000/plugins/jetpack

### CODE REVIEW

**Comment by johnHackworth** [comment]
ping @enejb  @ryelle  @rickybanister

**Comment by rickybanister** [comment]
No visual change should have happened so it looks good to me. Really happy to see lines of code removed from /plugins.

**Comment by ryelle** [comment]
Looks good 🚢

**Comment by tyxla** [comment]
Nice cleanup! 💛

**Pull request merged**
