### PR TITLE
Show a banner on the plans page when the free-to-paid-sidebar nudge is clicked

### PR DESCRIPTION
**Pull request by travisw**
A test to show a banner on the plans page when the free-to-paid-sidebar nudge is clicked

The PR depends on https://github.com/Automattic/wp-calypso/pull/26025 to first be merged.

------------

**Test Plan**

* Make sure https://github.com/Automattic/wp-calypso/pull/26025 has been merged.

* Visit http://calypso.localhost:3000/stats/day and choose one of your **free** sites.

* In the side bar you should see the "_Free domain with plan_" nudge.
screen shot 2018-07-13 at 9 58 15 am

* Click the nudge.

* When you're taken to the plans page you should either see a banner or not, depending on your ab test assignment.

screen shot 2018-07-13 at 9 53 31 am

Change your assignment, refresh, and try again to make sure both variations work.

screen shot 2018-07-13 at 9 53 15 am

### CODE REVIEW

**Comment by markryall** [comment]
This looks good but only after a rebase from master

**Comment by adamziel** [comment]
@travisw The URL included the `?discount=free_domain` bit, but the notice didn't show:

zrzut ekranu 2018-07-17 o 13 32 39

**Comment by adamziel** [comment]
A possible reason could be that `free_domain` is not returned by `https://public-api.wordpress.com/rest/v1.1/me/active-promotions?http_envelope=1`, maybe we should hardcode it in the selector function?

**Comment by travisw** [comment]
hmm, I don't think that rebase went right...

**Comment by travisw** [comment]
Created a new PR here: https://github.com/Automattic/wp-calypso/pull/26127

**Pull request closed without merging**
