### PR TITLE
Copy Site: Update design for Copying Progress step

### PR DESCRIPTION
**Pull request by sejas**
#### Proposed Changes

Redesign the Copying Progress step:
* Accept props in `ProcessingStep`
* Pass Title and Subtitle from the step builder
 
I didn't add the `< Back to sites` button.

#### Testing Instructions

* Go to `/sites`
* Click on the action menu on a business site
* Click on Copy Site
* After purchasing the plan, Observe the new Processing copy screen.

#### Screenshots

Screenshot 2023-01-18 at 20 43 30

#### Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

- Closes https://github.com/Automattic/dotcom-forge/issues/1480

### CODE REVIEW

**Comment by danielbachhuber** [comment]
> I didn't add the `< Back to sites` button.

@sejas I'm not actually convinced this screen should have a 'Back' button:
* 'Back' almost implies you can exit out of the process.
* Logically, 'Back' should take you to the checkout.
* If we send the user to the Sites page, there's the chance they could experience some funkiness as the site copy undergoes transformations.

Maybe we should update the message to "This may take a few minutes. Feel free to close this window and we will email you when the process is complete"?

@javierarce What do you think?

**Comment by sejas** [comment]
I agree. The back button can also guide the user to the `simple` site while it migrates to atomic, which can lead to some edge cases for a few minutes.

**Comment by sejas** [comment]
> Maybe we should update the message to "This may take a few minutes. Feel free to close this window and we will email you when the process is complete"?

I prefer the current message: `This may take a few minutes. We’ll notify you by email when it’s done.`. It actually doesn't take that long, and the user can access will be redirected to the site to start creating/developing.

**Comment by danielbachhuber** [comment]
> It actually doesn't take that long

@sejas Have you tried with a 5 GB site yet? 😁

**Comment by sejas** [comment]
> @sejas Have you tried with a 5 GB site yet? 😁

Updated the text and the screenshot 👍 .
https://github.com/Automattic/wp-calypso/pull/72287/commits/83bf4edfc0e7803557b553d3d6e11b3d6e7a3e29

**Review by danielbachhuber — APPROVED** [review]
Looks great, @sejas ! Landing it so I can include it in my weekly update 😁

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/7756359

Thank you @sejas for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/7756359

Thank you @sejas for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/7756359).

**Pull request merged**
