### PR TITLE
apply codemod: commonjs-exports

### PR DESCRIPTION
**Pull request by samouri**
this codemod is necessary along the path towards [enabling tree shaking](https://github.com/Automattic/wp-calypso/pull/16057).

How to generate this pr:
```
1. ./bin/codemods/run.js commonjs-exports client
2. git commit -anm "apply codemod: commonjs-export to /client"
3. git checkout origin/master \
    client/lib/i18n-utils/browser.js \
    client/lib/i18n-utils/node.js \
    client/extensions/index.js \
    client/lib/create-config/index.js \
    client/sections.js \
    client/wordpress-com.js
4. git commit -am "revert files that server needs"
5. npm run reformat-files
6. git commit -nam "prettier: reformat files"
```

### CODE REVIEW

**Comment by samouri** [comment]
changes look very harmless

**Comment by samouri** [comment]
CircleCI failed for lint reasons and 99.9% of the errors are:
```
React.createClass is deprecated since React 15.5.0, use the npm module create-react-class instead  react/no-deprecated
```

That error is okay to merge with

**Comment by blowery** [comment]
did prettier not get run on these? they're all missing spaces in parens...

**Comment by ockham** [comment]
Tests quite well. Maybe give it the usual e2e treatment (courtesy of Flow Patrol) before merging 😄

**Comment by hoverduck** [comment]
e2e tests came back clean :+1:

**Comment by samouri** [comment]
Thanks @hoverduck!
I'll recreate this PR and 🚢

**Comment by samouri** [comment]
@blowery: i've added `reformat-files` as a new step.

**Pull request merged**
