### PR TITLE
Update/simplify inline imports

### PR DESCRIPTION
**Pull request by dmsnell**
Alternative to #32969

Refactors the `inline-imports` Babel transform so that we no longer recurse from `ImportDeclaration`s to the `Identifier` referencing an action type.

We do this refactor by relying on the `scope` and `bindings` that Babel's API provides. These scopes contain the linked references to which the identifiers point. We can directly grab the action-type import and then do our local string replacement from this direct information.

With this I'm hoping that our TypeScript transform will run before the `inline-imports` because now the `inline-imports` transform is no longer taking precedent at the top of the program with the import declaration visitor.

---

Will come back for a better summary/description if the tests pass.

### CODE REVIEW

**Comment by sirreal** [comment]
I don't believe this is behaving as expected. I've done some testing with limited test cases.

Create a couple of files:

```ts
// simple.ts
import { ACCOUNT_CLOSE } from 'state/action-types';

export const accountCloseActionCreator = () => ( {
	type: ACCOUNT_CLOSE,
} );
```

```ts
// complex.ts
import { ACCOUNT_CLOSE, ACCOUNT_CLOSE_SUCCESS } from 'state/action-types';
import * as actionTypes from 'state/action-types';
import { ActionCreator, Action } from 'redux';

export const accountCloseActionCreator: ActionCreator< Action< typeof ACCOUNT_CLOSE > > = () => ( {
        type: ACCOUNT_CLOSE,
} );

export const accountCloseSuccessActionCreator: ActionCreator<
        Action< typeof ACCOUNT_CLOSE_SUCCESS >
> = () => ( {
        type: actionTypes.ACCOUNT_CLOSE_SUCCESS,
} );

export const httpDataTickActionCreator: ActionCreator<
        Action< typeof actionTypes.HTTP_DATA_TICK >
> = () => ( {
        type: actionTypes.HTTP_DATA_TICK,
} );
```
---
**Simple**

```sh
node ./node_modules/.bin/babel --presets=@babel/preset-typescript --plugins=./inline-imports.js simple.ts
```

Expected output (https://github.com/Automattic/wp-calypso/pull/32969):

```js
// simple.ts
export const accountCloseActionCreator = () => ({
  type: "ACCOUNT_CLOSE"
});
```

This branch:
```js
// simple.ts
import { ACCOUNT_CLOSE } from 'state/action-types';
export const accountCloseActionCreator = () => ({
  type: ACCOUNT_CLOSE
});
```


---
**Complex**

_`import * as` is not properly handled on either branch_

```sh
node ./node_modules/.bin/babel --presets=@babel/preset-typescript --plugins=./inline-imports.js complex.ts
```

Expected output (https://github.com/Automattic/wp-calypso/pull/32969):

_Note that the `import * as` case is not handled correctly_

```js
// complex.ts
export const accountCloseActionCreator = () => ({
  type: "ACCOUNT_CLOSE"
});
export const accountCloseSuccessActionCreator = () => ({
  type: actionTypes.ACCOUNT_CLOSE_SUCCESS
});
export const httpDataTickActionCreator = () => ({
  type: actionTypes.HTTP_DATA_TICK
});

```

Actual output (this branch):

```js
// complex.ts
import { ACCOUNT_CLOSE } from 'state/action-types';
import * as actionTypes from 'state/action-types';
export const accountCloseActionCreator = () => ({
  type: ACCOUNT_CLOSE
});
export const accountCloseSuccessActionCreator = () => ({
  type: actionTypes.ACCOUNT_CLOSE_SUCCESS
});
export const httpDataTickActionCreator = () => ({
  type: actionTypes.HTTP_DATA_TICK
});
```

**Comment by dmsnell** [comment]
Thanks for spotting that flaw @sirreal 

```js
import * as actionTypes from 'state/action-types';
```

Thankfully we have no cases of this in Calypso so nothing should break with this change.

I'm fairly confident that it fails regardless before _and_ after this change though for the `import *` construct, as it was never designed with that in mind and I'm not sure there's a reasonable way to perform this transformation from Babel, as it would have to know semantic information from the remote module.

@jsnajdr proposed a `webpack` plugin to do just that - constant-folding - but that's not in my scope for this change.

How do you feel about the change apart from expanding the scope of the `inline-imports` transform? I couldn't tell from what you wrote if you think it's best not to merge this until that new use-case is handled or if you are comfortable merging this for now as an incremental improvement?

**Comment by sirreal** [comment]
Sorry for being unclear. I agree that don't need to cover the `import * as` in this change, that was not handled before and is not a regression here.

The simple case doesn't perform as expected for me on this branch.

Input:

```ts
// simple.ts
import { ACCOUNT_CLOSE } from 'state/action-types';

export const accountCloseActionCreator = () => ( {
	type: ACCOUNT_CLOSE,
} );
```

Output:

```js
// simple.ts
import { ACCOUNT_CLOSE } from 'state/action-types';
export const accountCloseActionCreator = () => ({
  type: ACCOUNT_CLOSE
});
```

Are you able to reproduce this or am I doing something wrong in my testing?

**Comment by dmsnell** [comment]
> The simple case doesn't perform as expected for me on this branch.

You have discovered that I cannot read, as I missed that in your earlier comment

**Comment by dmsnell** [comment]
Closing in favor of #33256

**Pull request closed without merging**
