### PR TITLE
Plans 2023: Stop propagating selectedSiteSlug through props

### PR DESCRIPTION
**Pull request by chriskmnds**
Partly addresses https://github.com/Automattic/wp-calypso/issues/78994

## Proposed Changes

Stops propagating `selectedSiteSlug` through props as not needed outside of computing `manageRef` in the main index file.

## Testing Instructions

* code review
* just general sanity checks on `/plans/[ site ]` and `/start/plans`

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

**Review by jeyip — COMMENTED** [review]
This looks reasonable to me. I did a quick search and confirmed what has been said in the PR description. I only saw usage in the top level plans-grid component 👍 

Doing a quick smoke test

**Comment by jeyip** [comment]
## Testing
### Requirements

For each of the flows listed below:
- Verified header price and billing timeframe price with production
- Verified pricing for monthly and yearly pricing
- Ensured that a plan could be purchased
- Looked at pro rated pricing on the /plans page
- Spot checked the spotlight plan on the /plans page

Flows:
- [x] /start
- [x] /setup/newsletter
- [x] /setup/wooexpress
- [x] /start/p2 
- [x] /plans

### Browsers
- [x] Chrome

**Review by jeyip — APPROVED** [review]

**Comment by jeyip** [comment]
Failing e2e specs look unrelated to this PR. Rerunning them.

**Comment by chriskmnds** [comment]
Thanks!

**Pull request merged**
