### PR TITLE
composite-checkout: Allow `isCompleteCallback` to be async

### PR DESCRIPTION
**Pull request by sirbrillig**
There are three related changes in this PR. 

#### Allow isCompleteCallback to be async

First, it modifies the `isCompleteCallback` property of Step Objects and Payment Method Objects to optionally return a Promise. If a Promise is returned, the step will be marked complete or incomplete when the Promise resolves, rather than immediately. This allows for asynchronous validation which will be helpful when using the server-side validation introduced in #38729 but it does create one complication; we don't want to trigger async validation on every render, which is how the completion function is triggered now. That could be very expensive if the validation is a server call.

#### Always enable Continue buttons

This leads to the second change, which has been a UX goal in itself. Currently the "Continue" button on each step is disabled while the step is incomplete. This isn't ideal since the disabled state doesn't give any information about what's wrong if `isCompleteCallback` returns false. In this PR we modify the button so that it's always enabled, but only goes to the next step if the callback returns true. To do this we move calling the callback until the button is pressed which resolves the issue of async validation mentioned above. 

This change also help simplify some areas of the code because we now store the complete status of a step as component state rather than part of the annotated step objects. Previously in order to make sure the `isCompleteCallback` had the most recently updated data we had to force re-renders on every data change to force it to be called. Now the re-render happens automatically when the state changes.

Note that if the step is incomplete and the Continue button is pressed, it will appear that nothing happens; it is up to the `isCompleteCallback` to display appropriate validation errors. This gives the callback complete control over how best to display validation errors (notifications, displaying things inline, etc.) but is not ideal because it's too easy to _not_ notify the user; suggestions are welcome about better ways to handle the situation.

#### Removing paymentData

This PR removes passing both `paymentData` and `activeStep` as arguments to `isCompleteCallback` and `isEditableCallback`. Those arguments were mostly unused and complicated both the implementation and the documentation of those functions.

Since we no longer have `paymentData` we also remove the `usePaymentData` hook which was introduced as a simple way to store arbitrary data in payment methods and step objects. However, in practice it is far too inflexible to use for real data. Removing it should help to make it clear that the data layer of your custom components doesn't matter as far as this API is concerned (although `useRegisterStore` remains and option).

#### Testing instructions

- Run calypso with `ENABLE_FEATURES=composite-checkout-wpcom npm start`.
- Add a product to your cart and visit checkout.
- Make sure all steps display correctly.
- Make sure "Continue" button on each step is always enabled.
- Make sure pressing "Continue" button if step is incomplete does not move to the next step.
- Make sure pressing "Continue" button if step is incomplete displays some form of validation error.
- Make sure submit payment button is disabled until the final step.
- Make sure submit payment button is enabled on final step.

### CODE REVIEW

**Comment by fditrapani** [comment]
I tested this on Caypso.live and came across the following issues:

Everything was marked complete even though I had just started:
image

I can press continue before entering all the required information. On the payment step, no validation errors were shown and on the contact info step, the step submits with no data. 

image

I can confirm that the submit payment button is disabled until the final step and that it only activates when you get into the review step but this happens even if I submitted no data in the second step.

**Comment by sirbrillig** [comment]
Thanks for the feedback! I forgot that the checkmarks are controlled by the callback as well; I think I'll change them so that they just display a check if we've passed a step.

> I can press continue before entering all the required information. On the payment step, no validation errors were shown and on the contact info step, the step submits with no data.

This is partially a known issue; the domains form does not display validation errors yet, and also it performs its validation on field blur, so you will probably find that the continue button appears to do nothing if you click on it after blurring the first field and waiting a few seconds. This is bad UX, for sure, which is the point of this PR. With this change we can run validation on clicking Continue instead of on blur.

It's probably worth getting that working as part of this PR if we can. However, I'm not sure how to do that. I left a TODO in this PR (see 
2ef5b05) but I couldn't figure out a way to activate the validator. @nbloomf you may have more luck.

**Comment by sirbrillig** [comment]
@fditrapani 

> Everything was marked complete even though I had just started:

This should be fixed now.

> I can press continue before entering all the required information.

Try it without a domain. We can add the domain version later since it's not trivial.

**Comment by fditrapani** [comment]
Nice work! The continue button works as expected for the payment method. It's still not triggering any errors on the billing information step though. I can submit it without filling in any information.

**Comment by sirbrillig** [comment]
Dang, you're right. 😩 It's sort of the same problem as the domain form. The complete callback can't force the form to validate because it's just a function and doesn't have access to the store. There's got to be a content-agnostic way to make arbitrary data available to the complete callback.

In the demo it works because the store is registered in the same scope where the steps are created so we can access the store directly in the callback. I think the whole concept of the `isCompletCallback` is flawed. Let me think about this a bit more.

**Comment by sirbrillig** [comment]
I think I fixed the issue with the complete callback not working for the (non-domain) contact fields. Remaining issue:

The step seems to be considered "complete" if only one of the two fields is filled. I'm pretty sure this is because we get the state using the `useSelect` hook to be passed to the callback's closure, but the callback and its new validation happen synchronously. We need to fetch the latest data live instead of waiting for a re-render.

**Comment by fditrapani** [comment]
It's getting close. I confirmed that only one field needs to be completed for it to continue and also that I'm not seeing any error messages if I press continue and nothing is completed. I'm also able to add an invalid postal code.

**Comment by sirbrillig** [comment]
Thanks for re-checking! 

> I'm not seeing any error messages if I press continue and nothing is completed

Oh? Dang, I thought that part was fixed. When you press continue before completing anything, does it not say "This field is required" under each field?

> I'm also able to add an invalid postal code.

This is true currently and will be true after this diff. We do not have any postal code validation system in place for the non-domains form. Validation will still be done on the server, I think (although right now we may not be correctly sending tax information), so that should be taken care of when you press "Pay".

**Comment by fditrapani** [comment]
> When you press continue before completing anything, does it not say "This field is required" under each field?

No, I'm not seeing anything.

> This is true currently and will be true after this diff. We do not have any postal code validation system in place for the non-domains form. Validation will still be done on the server, I think (although right now we may not be correctly sending tax information), so that should be taken care of when you press "Pay".

Sounds good!

**Comment by sirbrillig** [comment]
This approach wasn't working super well and is superseded by #39636

**Pull request closed without merging**
