### PR TITLE
Invites: Add locale support for logged out invites

### LINKED ISSUE #2845: People: Language on accept invite screen doesn't match the invited user's language when logged out
I tested inviting a user with Spanish as their interface language:
- The invitation email was sent in Spanish (as expected)
- If I am already logged in as the invited user, the accept invite screen appears in Spanish (as expected)
- However, if I am logged out, the accept invite screen appears in English. (I confirmed that many of the strings that appeared in English are already translated and deployed in Spanish.) 

Ideally, the accept invite screen should always match the UI language of the invited user.

Steps to reproduce:

1. In a test account, go to https://wordpress.com/me/account and set the Interface Language to Spanish.
2. In your account, invite the test account to be a member of your site
3. Open the invitation email and copy the invitation link
4. In a logged-out browser window, visit the invitation link

Result: The accept invite screen (inviting you to sign up or log in to accept the invitation) is in English instead of Spanish, even though the invited user's interface language is Spanish.

You can also test this after setting your browser language to Spanish, and the logged-out accept invite screen still appears in English (with no option to switch to Spanish). We should at the very least detect the browser language and show an option to switch to Spanish, as we do in the signup flow at https://wordpress.com/start:

screen shot 2016-01-27 at 6 53 51 pm

### PR DESCRIPTION
**Pull request by ebinnion**
Fixes #2845 by adding locale support for logged out invites.

To test:
- Checkout `add/invites-locale-support` branch
- Create an invite on a WP.com site at `$site/wp-admin/users.php?page=wpcom-invite-users`
  - Note: To get the correct invitation link, you will need to mark site as a test blog. Ping me for help if necessary.
- In the invitation link, replace `wordpress.com` with `calypso.localhost:3000`
- While logged out, add `/es` (or any other language slug)
  - You should be shown an interface in Spanish (or you chosen language), along with a notice to switch back to another language.
- While logged in, add `/es` (or another language slug) to the end of the URL
  - The language slug should automatically be removed and you should see the interface in whatever language is set for your user

Ping @scruffian @drewblaisdell for thoughts on implementation.
Ping @lezama for code review and @rickybanister for design review.

Note: I added some utilities to `i18n-utils` that we could begin using in `signup/utils.js`. But, I believe that to be out of the scope of this PR.

logged-out-locale-mobile
logged-out-locale

### CODE REVIEW

**Comment by rickybanister** [comment]
Design seems fine—is there any value or need to have a language picker here instead of the link to English? 

Should that link be in Spanish if the locale is set to Spanish?

**Comment by ebinnion** [comment]
> is there any value or need to have a language picker here instead of the link to English?

For what it's worth, the switch to english functionality is not hard-coded in. I'm not 100% sure how it's generated, but based on the code in [locale-suggestions/index.jsx](https://github.com/Automattic/wp-calypso/blob/master/client/signup/locale-suggestions/index.jsx#L90-L101), I believe that users with other locales will see different suggestions.

Since the nux group laid the foundation here, we could coordinate with them and see if it would make sense to use the language picker here instead of a single prompt?

> Should that link be in Spanish if the locale is set to Spanish?

I think it makes the most sense to keep the prompt and link in the language that would be switched to, similar to how each language in the language selector (/me/account) is listed in its own language. Ex. español instead of spanih.

**Comment by rickybanister** [comment]
That all makes sense—I suppose if you couldn't read any of the page a message in your language would be a welcomed sight. 

Muchas gracias Eric!

**Comment by roccotripaldi** [comment]
This is quite awesome! Code looks good and works as described. Thanks for doing this.

**Pull request merged**
