### PR TITLE
Signup: Headstart: Disable the Headstart flow in production.

### PR DESCRIPTION
**Pull request by kwight**
This is temporary while preparing for its launch this week.

### CODE REVIEW

**Comment by kwight** [comment]
@sirbrillig @michaeldcain for review.

**Comment by sirbrillig** [comment]
Looks good. 

We could also do this via a config variable, [enabled by default](https://github.com/Automattic/wp-calypso/blob/master/config/_shared.json) but [disabled in production](https://github.com/Automattic/wp-calypso/blob/master/config/production.json). 

I guess since this is just temporary then maybe it doesn't matter, so I'd say use whichever feels better to you.

**Comment by kwight** [comment]
I was originally going to do it that way, but since it's for just a couple of days, I figured why muck with more files than I have to.

**Comment by sirbrillig** [comment]
Sounds good!

**Pull request merged**
