### PR TITLE
Adding Cloudflare cards.

### PR DESCRIPTION
**Pull request by donlair**
This PR adds Cloudflare cards to:
* The Stats page.
* The primary section of My Home (companion WPcom patch D55161-code)
* And the Settings > Performance page

Remaining to-dos:
* Plug in actual links
* Finalize illustrations

#### Testing instructions
* Checkout this PR
* Apply D55161 to your sandbox
* Sandbox WPcom api calls
* Navigate to My Home and cycle through the Task cards until you see and click the link
* Navigate to the Stats page and click the link
* Navigate to Settings > Performance and click the link
* Verify copy and layout for all cards

Fixes #

### CODE REVIEW

**Comment by donlair** [comment]
@blackjackkent can you take a look at the click tracking implementation on the Stats card? I still haven't really grokked how redux/dispatch/tracking works, doubly so with class components. I'd appreciate any tips you can give there!

**Comment by donlair** [comment]
@blackjackkent re: my comment about the Stats card above, I changed the approach to use an imported function component instead of the class component, and I think the tracking works now. I'm still iffy on how the tracking works, so you should take a close look at that to make sure I did it right!

**Review by blackjackkent — APPROVED** [review]
Looks good! Thanks for addressing the feature flag aspect. :)

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/5472711

Hi @donlair, could you please edit the description of this PR and add a screenshot for our translators? Ideally it'd include all of the following strings:
- `Protect and accelerate your site with Cloudflare CDN`
- `Optimize and secure your content to create a faster experience for your users regardless of their device or location.`
- `Cloudflare CDN`
- `Use the Cloudflare global server network to optimize your site content and create a faster experience for your users regardless of their device or location.`
- `Gain deeper insights with Cloudflare Analytics`
- `Cloudflare Analytics empowers you with deep insights and intelligene to protect and accelerate your site.`

Thank you in advance!

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/5472711).

**Pull request merged**
