### PR TITLE
Site Settings: Fix `prop 'siteId' is marked as required` warning

### PR DESCRIPTION
**Pull request by danielbachhuber**
Discovered in https://github.com/Automattic/wp-calypso/pull/75496

## Proposed Changes

Fixes a `Failed prop type: The prop 'siteId' is marked as required in 'QueryJetpackconnection', but its value is null'` warning in the tests by passing `selectedSiteId` into the initial state.

CleanShot 2023-04-25 at 06 42 08@2x

## Testing Instructions

Tests should pass.

### CODE REVIEW

**Review by sejas — COMMENTED** [review]
@danielbachhuber , I'm still seeing an error. Is that expected?

## Before (2 warnings)
```
❯ yarn test-client -- client/my-sites/site-settings/test/form-general.jsx                                                       14:17:35
 PASS  client/my-sites/site-settings/test/form-general.jsx (5.039 s)
  ● Console

    console.error
      Warning: Failed prop type: The prop `siteId` is marked as required in `QuerySiteSettings`, but its value is `undefined`.
          at QuerySiteSettings (/Users/wp-calypso/client/components/data/query-site-settings/index.js:13:31)
          at SiteSettingsFormGeneral (/Users/wp-calypso/client/my-sites/site-settings/form-general.jsx:65:56)
          at Provider (/Users/wp-calypso/node_modules/react-redux/lib/components/Provider.js:21:20)
          at QueryClientProvider (/Users/wp-calypso/node_modules/@tanstack/react-query/build/lib/QueryClientProvider.js:65:3)
          at Wrapper (/Users/wp-calypso/client/test-helpers/testing-library/index.js:26:22)

      786 |             return (
      787 |                     <div className={ classNames( classes ) }>
    > 788 |                             { site && <QuerySiteSettings siteId={ site.ID } /> }
          |                                       ^
      789 |
      790 |                             <SettingsSectionHeader
      791 |                                     data-tip-target="settings-site-profile-save"

      at printWarning (../node_modules/react/cjs/react-jsx-runtime.development.js:117:30)
      at error (../node_modules/react/cjs/react-jsx-runtime.development.js:93:5)
      at checkPropTypes (../node_modules/react/cjs/react-jsx-runtime.development.js:620:11)
      at validatePropTypes (../node_modules/react/cjs/react-jsx-runtime.development.js:1072:7)
      at jsxWithValidation (../node_modules/react/cjs/react-jsx-runtime.development.js:1192:7)
      at Object.jsxWithValidationDynamic [as jsx] (../node_modules/react/cjs/react-jsx-runtime.development.js:1209:12)
      at jsx (../node_modules/@emotion/react/jsx-runtime/dist/emotion-react-jsx-runtime.cjs.dev.js:19:28)
      at SiteSettingsFormGeneral.render (my-sites/site-settings/form-general.jsx:788:15)

    console.error
      Warning: Failed prop type: The prop `siteId` is marked as required in `QueryJetpackConnection`, but its value is `null`.
          at QueryJetpackConnection (/Users/wp-calypso/client/components/data/query-jetpack-connection/index.jsx:13:36)
          at Masterbar (/Users/wp-calypso/client/my-sites/site-settings/masterbar.jsx:15:2)
          at /Users/wp-calypso/packages/i18n-calypso/src/localize.js:20:16
          at ConnectFunction (/Users/wp-calypso/node_modules/react-redux/lib/components/connectAdvanced.js:235:41)
          at div
          at SiteSettingsFormGeneral (/Users/wp-calypso/client/my-sites/site-settings/form-general.jsx:65:56)
          at Provider (/Users/wp-calypso/node_modules/react-redux/lib/components/Provider.js:21:20)
          at QueryClientProvider (/Users/wp-calypso/node_modules/@tanstack/react-query/build/lib/QueryClientProvider.js:65:3)
          at Wrapper (/Users/wp-calypso/client/test-helpers/testing-library/index.js:26:22)

      21 |      return (
      22 |              <div>
    > 23 |                      <QueryJetpackConnection siteId={ selectedSiteId } />
         |                      ^
      24 |
      25 |                      <SettingsSectionHeader title={ translate( 'WordPress.com toolbar' ) } />
      26 |                      <Card className="masterbar__card site-settings__security-settings">

      at printWarning (../node_modules/react/cjs/react-jsx-runtime.development.js:117:30)
      at error (../node_modules/react/cjs/react-jsx-runtime.development.js:93:5)
      at checkPropTypes (../node_modules/react/cjs/react-jsx-runtime.development.js:620:11)
      at validatePropTypes (../node_modules/react/cjs/react-jsx-runtime.development.js:1072:7)
      at jsxWithValidation (../node_modules/react/cjs/react-jsx-runtime.development.js:1192:7)
      at Object.jsxWithValidationDynamic [as jsx] (../node_modules/react/cjs/react-jsx-runtime.development.js:1209:12)
      at jsx (../node_modules/@emotion/react/jsx-runtime/dist/emotion-react-jsx-runtime.cjs.dev.js:19:28)
      at Masterbar (my-sites/site-settings/masterbar.jsx:23:4)


Test Suites: 1 passed, 1 total
Tests:       36 passed, 36 total
Snapshots:   0 total
Time:        5.26 s
Ran all test suites matching /client\/my-sites\/site-settings\/test\/form-general.jsx/i.
```

## After (1 warning)
```
❯ yarn test-client -- client/my-sites/site-settings/test/form-general.jsx                           8s 14:18:17
 PASS  client/my-sites/site-settings/test/form-general.jsx
  ● Console

    console.error
      Warning: Failed prop type: The prop `siteId` is marked as required in `QuerySiteSettings`, but its value is `undefined`.
          at QuerySiteSettings (/Users/wp-calypso/client/components/data/query-site-settings/index.js:13:31)
          at SiteSettingsFormGeneral (/Users/wp-calypso/client/my-sites/site-settings/form-general.jsx:65:56)
          at Provider (/Users/wp-calypso/node_modules/react-redux/lib/components/Provider.js:21:20)
          at QueryClientProvider (/Users/wp-calypso/node_modules/react-query/lib/react/QueryClientProvider.js:45:21)
          at Wrapper (/Users/wp-calypso/client/test-helpers/testing-library/index.js:26:22)

      767 |             return (
      768 |                     <div className={ classNames( classes ) }>
    > 769 |                             { site && <QuerySiteSettings siteId={ site.ID } /> }
          |                                       ^
      770 |
      771 |                             <SettingsSectionHeader
      772 |                                     data-tip-target="settings-site-profile-save"

      at printWarning (../node_modules/react/cjs/react-jsx-runtime.development.js:117:30)
      at error (../node_modules/react/cjs/react-jsx-runtime.development.js:93:5)
      at checkPropTypes (../node_modules/react/cjs/react-jsx-runtime.development.js:620:11)
      at validatePropTypes (../node_modules/react/cjs/react-jsx-runtime.development.js:1072:7)
      at jsxWithValidation (../node_modules/react/cjs/react-jsx-runtime.development.js:1192:7)
      at Object.jsxWithValidationDynamic [as jsx] (../node_modules/react/cjs/react-jsx-runtime.development.js:1209:12)
      at jsx (../node_modules/@emotion/react/jsx-runtime/dist/emotion-react-jsx-runtime.cjs.dev.js:19:28)
      at SiteSettingsFormGeneral.render (my-sites/site-settings/form-general.jsx:769:15)


Test Suites: 1 passed, 1 total
Tests:       32 passed, 32 total
Snapshots:   0 total
Time:        5.031 s, estimated 6 s
Ran all test suites matching /client\/my-sites\/site-settings\/test\/form-general.jsx/i.
```

**Comment by danielbachhuber** [comment]
@sejas That's a separate error...

**Comment by danielbachhuber** [comment]
@sejas If you're fine with the overall approach, I'll address the other error in this PR too.

**Review by wojtekn — APPROVED** [review]
It works for me, however, as @sejas mentioned above, it makes sense to fix both occurrences of the error.

**Review by sejas — APPROVED** [review]
Thanks for finding and fixing this warning.
It fixes one of two warnings.

` <QueryJetpackConnection siteId={ selectedSiteId } />` -> fixed
`<QuerySiteSettings siteId={ site.ID } />` -> displays a warning.

**Comment by danielbachhuber** [comment]
Fixed up the other warnings with 2a5992ef65d95a8b5d1461195d5c083e0a74f014 and cba8227f7ec8b19900ce5358c076161ee90d0a0b

**Pull request merged**
