### PR TITLE
Build: use printf instead of echo for portability reasons

### PR DESCRIPTION
**Pull request by klimeryk**
There are many flavours of `echo` and it's not guaranteed, for example, that the escape characters will be handled the same. On my Linux box, the escape characters are printed as-is, without triggering the intended color change in the terminal.
`printf` on the other hand is guaranteed to always interpret the escape characters. The only "major" caveat is that `printf` does not automatically add a newline - which is, of course, easily fixed.

Related discussion on [StackOverflow](http://stackoverflow.com/a/4436050/181497).

Some visuals (because why not?) on how it looks with `echo` from GNU coreutils on my Linux desktop.

Before (`echo` from GNU `coreutils`):
2015-12-17-023937_763x286_scrot
After (`printf`):
2015-12-17-023959_746x287_scrot

Before (`echo` from GNU `coreutils`):
2015-12-17-024952_700x220_scrot
After (`printf`):
2015-12-17-025028_628x275_scrot

In the process, I've (hopefully) improved the output abit (as in, slightly less unnecessary newlines are produced):

Before (OSX):
screen shot 2015-12-17 at 03 16 37
After (OSX):
screen shot 2015-12-17 at 03 17 01

(that last line says "COMMIT SUCCEEDED", but due to my terminal colours, it's not that readable... nothing to do with the script/PR, though)

### CODE REVIEW

**Comment by sirbrillig** [comment]
This seems like a good idea! I didn't know about the different implementations of `echo`. Apart from having to remember newlines, is there any other downside do using `printf`? (I can't think of any, but putting it out there.)

cc: @bazza @folletto @blowery as you might have thoughts

**Comment by klimeryk** [comment]
Yup, didn't know about it either, so my first version of this just used `echo -e`. Which worked flawlessly on my Linux desktop - but when I tested it on OSX, it just stupidly printed `-e` as part of the output. So I dug deeper and came to this version.

A good write-up on `echo` vs `printf` can be found [here](http://unix.stackexchange.com/a/65819/5095) (should be trustworthy, since it's from the same guy that found the "Shell Shock" bug ;)). TL;DR: when substituting `echo` with `printf` you only have to remember about newlines and that the first argument to `printf` is the format, so shouldn't contain variables/uncontrolled data.

**Comment by folletto** [comment]
> it just stupidly printed -e as part of the output. So I dug deeper and came to this version.

From the source you link, that seems to be a POSIX requirement. :)

> This seems like a good idea! 

Agreed. +1 for me.

**Comment by klimeryk** [comment]
> From the source you link, that seems to be a POSIX requirement. :)

Ha, quite true! I must admit that I glossed that over, assuming that `echo` does not adhere to any standard. And the next line says:

> Those specifications don't really come to the rescue here given that many implementations are not compliant.

So bottom line that I think we can all agree on is that `echo` (from a portability standpoint) is a mess :confounded: Not that `echo` should _always_ be avoided, but I'm glad I know the caveats now :)

BTW, I rebased the branch so that it's up to date with `master` and is using NodeJS 4 :)

**Comment by artpi** [comment]
Seems to work fine!

**Comment by sirbrillig** [comment]
Figured it's better to get this merged sooner rather than later to prevent more `echo`s showing up.

**Pull request merged**
