### PR TITLE
Reader: Localize logged out tag and discover pages

### PR DESCRIPTION
**Pull request by roo2**
project thread pe7F0s-148-p2

Applies i18n to logged out /tag and /discover pages.

### Existing issues

Note that on both pages, the first 7 posts are requested *before* the language is set, and therefore are in english. This is due to the language being set asynchronously, I will fix this in antother PR https://github.com/Automattic/wp-calypso/blob/trunk/client/lib/i18n-utils/switch-locale.js#L435

### Testing instructions 
Sansbox public-api and apply D118322-code for the tag pages
With a logged out session:
try `/fr/discover` discover page should be localized.
try `/fr/tag/art` art page should be localized.
invalid languages should redirect to the english page e.g. `/zz/tag/art` -> `/tag/art`
The language selector in the footer should switch the language.

### CODE REVIEW

**Comment by Addison-Stavlo** [comment]
👋  I noticed the expected masterbar wasn't showing up here (a result of the `currentRoute.startsWith` type checks you noted before). I pushed a fix for that, and also enabled the `/discover` and `/read/search` links at the top of it to add the locale as well ([b9d754e](https://github.com/Automattic/wp-calypso/pull/80302/commits/b9d754e50b140c39d22a3ed63951d3663a98ac42)).  I also added an i18n util for `addLocaleToPathLocaleInFront` (we had remove for in front but not add 🤷‍♀️ ) and added a quick unit test ([a6e94f9](https://github.com/Automattic/wp-calypso/pull/80302/commits/a6e94f9527684f79f8087cc74b91176b73098fd1))

For these new changes I pushed id test the masterbar links at the top, and also smoke test the language switcher in the bottom right of the footer.

Beyond that, this looks good and tests well for me. It seems we haven't enabled `/tags` for locales yet, should we do that separately?

**Review by Addison-Stavlo — APPROVED** [review]

**Comment by roo2** [comment]
Awesome! thank you @Addison-Stavlo! 

> It seems we haven't enabled /tags for locales yet, should we do that separately?

I don't know if this is even on the cards, just because those links are all hand selected for English, we would have to hand select them for other languages too or be stuck with the English ones.

**Comment by roo2** [comment]
hey @Addison-Stavlo sorry, I think I lost your commit, I rebased off trunk and `git push --force-with-lease` but didn't notice your commit was missing until after I pushed 😬 do you think you can push the commit again?

**Comment by Addison-Stavlo** [comment]
> do you think you can push the commit again?

Pushed, and made things up to date with trunk.

> just because those links are all hand selected for English, we would have to hand select them for other languages too or be stuck with the English ones.

I assumed we would use the same tags/links, but just translate their names/words displayed on the page? Either way we can worry about that separately.

**Pull request merged**
