### PR TITLE
Update/Design: Fix spacing between site-settings footer credit explanation and button

### LINKED ISSUE #14412: Site Settings: Footer Credit link to Customizer doesn't have enough space
When looking at https://wordpress.com/settings/general/SITE_URL, I get this:

screen shot 2017-05-24 at 1 53 35 pm

The space between the text and the button that links to the Customizer seems like it's not enough.

### PR DESCRIPTION
**Pull request by jonchurch**
closes #14412

When on page [ https://wordpress.com/settings/general/SITE_URL]( https://wordpress.com/settings/general/) the edit credit button is very close to the explanation text.

Add `margin-left: 12px` to the footer credit update button in site settings. I picked 12 px because on my browser that was the max before turning the explanation text into a two-liner. Please let me know if this is preserved on your browsers, or if more space is preferred over keeping the flow of the text.

Gives some breathing room between text and button
Here is the before margin-left:

before image

And the after:

after image

cc @lsinger 

p.s. Thank you calypso team for the First Timer label! This got me up to speed on the CONTRIBUTING.md and I feel ready to get involved.

### CODE REVIEW

**Comment by drw158** [comment]
That's great. It's been bugging me for a while. I might put a `nbsp` before the last word just so we don't get a single word on the second line. We also have a prevent widow function I believe.

 Different translations will probably go to 2 lines anyway, so it would be good to optimize for that.

**Comment by folletto** [comment]
Good change!

I'd even do `24px`... :D

**Comment by designsimply** [comment]
@jonchurch would you like to do 24px or stick with 12px for this pull request?

**Comment by jonchurch** [comment]
Viewed on a different screen, the explanation flows to another line even at 12px. I picked 12px before because on my screen it did not flow to a second line.

New Changes:
* Going with 24px since this is flowing regardless
* Import `preventWidows` to `site-settings/form-general`
* Wrapping the translated explanation in `preventWidows()`, flowing the last two words so we aren't left with a single word on a new line. as per @drw158's suggestions (thanks!)

**Comment by gwwar** [comment]
@jonchurch that does seem like a lot. @folletto or @drw158 any ideas on why there's a 1.5em margin-bottom there? I'd be fine with maybe even removing all of that. 

Code changes look good here. I can help land when folks are ready.

**Comment by drw158** [comment]
I know there is a 1.5em margin on all `p` globally. You'll have to override that. Overriding with a `0` margin would probably look good. Looks great!

**Comment by gwwar** [comment]
@jonchurch let me know if you'd like to add `p` override, or if you'd like to 🚢 as is.

**Comment by jonchurch** [comment]
@drw158 @gwwar Added `margin: 0` via selecting the p descendant with
`site-settings__footer-credit-explanation p`

Let me know if this should be done by adding a class to the p element in the component!

**Here's the result:**

screen shot 2017-06-18 at 1 23 59 pm

**Comment by folletto** [comment]
> I picked 12px before because on my screen it did not flow to a second line. 

For the future: this isn't a good criteria, as screen sizes, translations, etc, imply the length will always be "off" any pre-selected reference. ;)

> Let me know if this should be done by adding a class to the p element in the component!

I guess opinions might vary here, but I personally think this is a good approach. 👍

**Comment by gwwar** [comment]
Thanks @folletto. If you're ready @jonchurch let me know and I can :shipit:

**Comment by jonchurch** [comment]
@gwwar :shipit:

**Pull request merged**
