### PR TITLE
Store Order: Clean up table view on smaller screens

### LINKED ISSUE #17910: Store: Order Details Table on Mobile Cramped Columns
screenshot_20170906-212534_png__1080x1920_

While viewing an order detail page on my Nexus5 last night I noticed a few visual oddities that I thought should be logged as an issue:

- The details table Product column gets quite cramped on smaller viewports which results in a _very tall_ Product name cell. Not sure what we can do to remedy this, a scrolling table akin to the order list isn't the best experience either but perhaps we can get creative with limiting the size of the quantity column or something.
- Button padding. This one is odd as it only happened on the mobile chrome browser... I tried to recreate using devtools emulation on mac/chrome and it looked fine. The "Save Order" and "Submit Refund" buttons appear to have more bottom padding

### PR DESCRIPTION
**Pull request by ryelle**
Fixes #17910 - improves the layout of the order details page on small screens. This updates the line items so that the product name spans the full width, any coupons applied also span the full width of the screen, and the payment & fulfillment buttons wrap to a new line. The "activity log" & address sections work without any adjustments.

| Before | After |
| --- | --- |
| screen shot 2018-02-16 at 16 51 48 | order |

**To test**

On a screen or browser smaller than 660px wide…

- View a single order on your store: `/store/order/:site/:id`
- Make sure the product details look ok 👍 
- See #22541 for header & actions improvements

This doesn't help the create or edit screen, or refunds, or the shipping label modal, this is just for the single order view.

### CODE REVIEW

**Comment by shaunandrews** [comment]
The layout is much better. The "Cost" heading does look a little out of place. Maybe just ditch it? Also, do we need to repeat the price if the quantity is 1?

However, the layout on the FEE row looks off now — it looks better before. Can we have it both ways?

**Comment by shaunandrews** [comment]
Oh, and maybe the quantity and total should align themselves to the top of their cell?

**Comment by ryelle** [comment]
Quantity & total are aligned to the top, the product title is full-width – it's just that those are shorter products. This is a longer example:

screen shot 2018-02-16 at 5 03 22 pm

**Comment by shaunandrews** [comment]
Ah, I see now. I think its overall a better layout that what you have currently.

**Comment by kellychoffman** [comment]
> Obviously that's quite a bit more work but I think it would be a significant improvement.

Agree but its outside the scope of this PR and should be added as a separate issue.

**Pull request merged**
