### PR TITLE
JPC: Clean redux state after the flow is completed

### PR DESCRIPTION
**Pull request by johnHackworth**
This PR adds a new action to empty the JPC redux subtree after a flow is completed. Until now, we were storing all kind of connection-related data that in a ver few cases created some problems with future connections down the line. Now we are cleaning all those not-needed-anymore subtrees once the user finish the flow.

How to test
=========
0. You need an unconnected site
1. Start from calypso.localhost:3000/jetpack/connect and connect your site (also you could start from wp-admin, but you would need to hack your wp.com sandbox or your jetpack plugin to make it work with your local calypso)
2. Connect the site. Once you pass the plans page (both purchasing a plan or not), the `jetpactConnect` redux subtrees should be empty

@roccotripaldi  @tyxla

### CODE REVIEW

**Comment by roccotripaldi** [comment]
Nice! Reviewing now, perhaps this will help with #9201

**Comment by roccotripaldi** [comment]
Works well. Where are we at with plans first flows? How can i test this PR for that situation?

**Comment by tyxla** [comment]
It would probably be best if we land the plans-first PR (#8920) first - as @roccotripaldi indicated it would be useful to test with that flow as well.

**Comment by johnHackworth** [comment]
This became ultra-dumb after merging other PRs... the only change is that we also clean the flow data after redirecting back to wp-admin

**Comment by oskosk** [comment]
LGTM

**Pull request merged**
