### PR TITLE
Editor Deprecation: Remove deprecation group state

### PR DESCRIPTION
**Pull request by pablinos**
#### Changes proposed in this Pull Request

Now that the editor is deprecated for all we can remove the logic that checks if the current user is in the deprecation group, as well as the dialog we were displaying in the Calypso editor to encourage people to opt into the block editor.

#### Testing instructions

* Apply D49622-code and sandbox the API
* Run `delete_user_attribute( YOUR_USER_ID, 'editor_deprecation_group')`  in wpsh
* With this PR check that you can't load the Calypso editor, regardless of the editor preference setting for your site
* Also check that you don't encounter any errors either in Calypso or `wp-admin`, when creating and editing posts

### CODE REVIEW

**Review by allilevine — APPROVED** [review]
I tested this PR by applying D49622-code and sandboxing the API, deleting the `editor_deprecation_group` attribute for my test user, and then pulling down this branch and running Calypso locally. I also switched the test user's editor preference from Gutenberg to Classic. I couldn't find any way to access the Calypso editor, and I didn't encounter any errors in Calypso or `wp-admin`.

**Comment by allilevine** [comment]
> I tested this PR by applying [D49622-code](https://href.li/?D49622-code) and sandboxing the API, deleting the `editor_deprecation_group` attribute for my test user, and then pulling down this branch and running Calypso locally. I also switched the test user's editor preference from Gutenberg to Classic. I couldn't find any way to access the Calypso editor, and I didn't encounter any errors in Calypso or `wp-admin`.

Just to clarify: when the editor preference is Classic, the iframed classic editor still loads in wp-admin.

**Review by allilevine — CHANGES_REQUESTED** [review]
I re-tested and got a console error, though it may be because I didn't test this flow the first time vs. related to the rebase:
```
Uncaught Error: Given action "EDITOR_DEPRECATION_GROUP_SET", reducer "inEditorDeprecationGroup" returned undefined. To ignore an action, you must explicitly return the previous state. If you want this reducer to hold no value, you can return null instead of undefined.
```
Steps to reproduce:
1. Apply the patch and sandbox the API
2. Clear deprecation group attribute for user
3. View a post and click "Edit" in the bottom right Actionbar.
4. Open the console on the edit page.

**Comment by pablinos** [comment]
I couldn't reproduce this, but it did make me notice that I hadn't removed the now unused action types. The `inEditorDeprecationGroup` reducer shouldn't exist anymore, so perhaps something didn't get rebuilt as the file was removed. 

Any chance you could give it another test?

**Review by allilevine — APPROVED** [review]
> I couldn't reproduce this, but it did make me notice that I hadn't removed the now unused action types. The inEditorDeprecationGroup reducer shouldn't exist anymore, so perhaps something didn't get rebuilt as the file was removed.
> 
> Any chance you could give it another test?

Sorry I think I was seeing the console error because viewing the site and clicking "Edit" took me out of Calypso (and to an interface without the PR changes, but with the sandboxed API change). Hopefully it will correct itself when the changes are live.

**Pull request merged**
