### PR TITLE
Domains: Update transfer precheck per GDPR

### PR DESCRIPTION
**Pull request by aidvu**
- Remove e-mail/privacy precheck section
- Update the EPP code section to accept a code
- Validate code before adding to cart

Testing instruction:
- Calypso -> Add -> Use a Domain I Own
- Try a locked domain
- Make sure it shows proper message
- Unlock
- Recheck lock
- Get to EPP code input
- Input invalid EPP code
- No go
- Input valid EPP code
- Add product to cart
- Checkout
- Make sure the domain went straight to `pending_registry` status

Dependency: D13671-code

### CODE REVIEW

**Comment by aidvu** [comment]
Grrr... will fix.

**Comment by KokkieH** [comment]
Should this copy still appear in the Auth Code section of the flow?

> We'll send you an email with a link to enter it and officially okay the transfer.

Internal documentation and the transfer flow charts indicate we don't send any emails to confirm the auth code in the standard flow.

**Comment by KokkieH** [comment]
And if I type in an invalid auth code it now silently fails without any error messaging like in the screen shot @hambai posted.

**Comment by aidvu** [comment]
@KokkieH because of the back-end dependency, probably.

Good catch on the copy. 😱

**Comment by aidvu** [comment]
@hambai we should probably update the copy per @KokkieH.

**Comment by hambai** [comment]
Ah yeah - didn't read the scrollback 👍 I'll fix that if you don't mind

**Comment by aidvu** [comment]
I'm AFK (obviously? eh? 😆), so feel free to!

**Pull request merged**
