### PR TITLE
i18n: Localize links in Jetpack app promo sections

### PR DESCRIPTION
**Pull request by yuliyan**
Related to:
* 555-gh-Automattic/i18n-issues
* D101286-code

## Proposed Changes

* Localize link and QR code for Jetpack app in Full Width App Promo component.
* Localize link for Jetpack app in my sites customer home card.

CleanShot 2023-02-14 at 14 28 47

CleanShot 2023-02-14 at 14 34 58

## Testing Instructions

* Boot Calypso locally or use calypso.live image.
* Change UI to any of the Mag-16 languages.
* Navigate to `/home/`
* Confirm `Get the Jetpack app` links to `apps.wordpress.com/[locale]/get/`.
* Navigate to `/stats/day/[site]`
* Confirm `wp.com/app` and QR code link to `apps.wordpress.com/[locale]/get/`.

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

**Review by SiobhyB — CHANGES_REQUESTED** [review]
Thank you for addressing this, @yuliyan!

I tested the changes after setting my account's primary language to French. The updated link is correctly updated to `apps.wordpress.com/fr/get/?campaign=campaign_name`. However, this redirects to `apps.wordpress.com/mobile` and not to the localized URL at `apps.wordpress.com/fr/mobile`.

I did some digging into the `/get` redirect (it was first introduced in p77Llu-9V4-p2) and don't know if it has ever correctly redirected to localized pages. I wonder whether this may need to be something that's fixed with Systems, but wanted to make sure to share here first.

As the changes in this PR update the URLs themselves, I'm happy to approve if you have ideas/plans to fix the redirect afterwards. Let me know!

**Comment by yuliyan** [comment]
@SiobhyB, You are right - the `/get` pages currently are not redirecting correctly. I've already addressed this issue in D101286-code. I'm sorry about not including it in the PR description initially.

**Review by SiobhyB — APPROVED** [review]
Ah, perfect, thanks for confirming @yuliyan! LGTM in that case 🚢

**Review by jornp — APPROVED** [review]
The link at /home/:

image

The link at /stats/:

image

The QR code also points to the localized URL.

LGTM! 🚀

**Pull request merged**
