### PR TITLE
Plans comparison page - updated for Newsletter and Earn features

### PR DESCRIPTION
**Pull request by mikestottuk**
## Proposed Changes

* Adds a new Earn section
* Re-orders where some features were listed, Subscriptions (Design) -> Newsletter (Growth)
* Adds Transaction fees to the Earn area
* Adds AI and Blaze to the Growth section

### Before
before

### After
features-after

## Testing Instructions

* Page is visible here: http://jetpack.cloud.localhost:3000/features/comparison
* Test the Newsletter feature link goes to -> https://jetpack.com/newsletter/ 
* That the Paid Newsletter link goes to -> https://jetpack.com/support/paid-newsletters/
* That the Transaction Fees goes to -> https://jetpack.com/support/jetpack-earn-transaction-fees/

### CODE REVIEW

**Review by jboland88 — COMMENTED** [review]
This LGTM and tests well, however, it appears that one of the tests is failing because of a missing `localizeUrl`.  It looks like the error is on line 22 - maybe the `mobile_app` link?

**Review by CodeyGuyDylan — APPROVED** [review]
This LGTM

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/8801436

Thank you @mikestottuk for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/8801436).

**Pull request merged**
