### PR TITLE
Help: Prevent double click when starting a chat

### PR DESCRIPTION
**Pull request by omarjackman**
This pull request attempts to fix an issue that has been unreproducible but happens frequently. The issue is that sometimes Happiness Engineers will observe the same initial repeated message and notifications from a user. This could possibly happen with double clicking if there is some kind of network delay between the client and Olark. I've added some double click prevention logic to the contact form to prevent this behavior in that case.

#### How to test
*Note this is not easily reproducible without introducing artificial network delays*
1. Navigate to http://calypso.localhost:3000/help/contact
2. Enter text to start a chat.
3. Click "Chat with us"
4. If there is no delay the chat should be started instantly. If there is then proceed to next step.
5. Notice that the main button is now disabled with a new label "Starting chat"
6. The chat should begin after the delay.

I was able to test this by creating an artificial delay with `setTimeout` wrapped around the logic that starts the chat.

screen shot 2016-01-22 at 1 05 52 am

### CODE REVIEW

**Comment by dllh** [comment]
I haven't tested yet, but the code seems reasonable. Would the issue this fixes potentially result in many repetitions of the notifications or just as many as there are clicks? How confident are we that this is the cause of the issue that was reported?

**Comment by omarjackman** [comment]
@dllh

>Would the issue this fixes potentially result in many repetitions of the notifications or just as many as there are clicks?

Its not tied to the number of clicks. Reproducing this isn't so straight forward as I think olark has duplicate message handling in place already. I tested this with an artificial delay of 5 seconds and quadruple clicked within that time frame. I ended up with the message and notifications coming in only one extra time. 

See 
screen shot 2016-01-25 at 7 32 31 pm

> How confident are we that this is the cause of the issue that was reported?

I'm not 100% confident because I've never personally encountered a delay that would allow this to happen. This is my best guess at whats causing it and I'm plugging the hole.

**Comment by jordwest** [comment]
Even if this is not the cause of the issue, in terms of user feedback I think it's a good move to disable the button while the action is in progress.

I'm just wondering what might happen in a case where some kind of error occurs and `onChatStarted` is never called? How would `isSubmitting` get reset so the button was enabled again?

**Comment by omarjackman** [comment]
> I'm just wondering what might happen in a case where some kind of error occurs and `onChatStarted` is never called? How would `isSubmitting` get reset so the button was enabled again?

@jordwest 

Olark doesn't throw any errors that I'm aware of so I think the two possible safeguards here are
1. Use a timer to unset `isSubmitting` after `n` seconds. 
2. Listen for an error like `window.addEventListener( 'error', () => this.handleChatError() )` while submitting.

What do you think?

**Comment by jordwest** [comment]
Just took a look at the Olark docs and also couldn't see any mention of error handling. I'm leaning toward the timer idea, since it effectively just throttles the send button. If it turns out that after the timer expires the request *did* actually go through and start a chat, I assume a second attempt will just be sent to the operator twice in the same conversation?

**Comment by omarjackman** [comment]
> I assume a second attempt will just be sent to the operator twice in the same conversation?

yup, I'd just need to make sure that the timeout is larger than the timeframe of the original issue

**Comment by omarjackman** [comment]
I no longer think this is a good solution for the issue outlined in the description of this pull request

**Pull request closed without merging**
