### PR TITLE
Reverting #40162 while we sort out issues with code splitting on desktop

### PR DESCRIPTION
**Pull request by lynnbgriffith**
#### Changes proposed in this Pull Request

* #40162 caused issues with the desktop build.  (See issue #40789 for more details)

#### Testing instructions

Ensure Calypso builds and code splitting still works.

### CODE REVIEW

**Comment by nsakaimbo** [comment]
Currently testing this revert in wp-desktop - will update when CI is complete (Circle queues seem pretty busy at the moment with many jobs marked as "pending").

`https://github.com/Automattic/wp-desktop/tree/test-calypso-code-split-revert`

I also realized the `ci/wp-desktop` job is marked as passing even though the the entirety of the canary workflow is still pending. (i.e. at this stage the canary job has only built the Calypso source for the desktop, but the end-to-end-tests have not been executed yet). @bsessions85 any insights here?

**Comment by bsessions85** [comment]
@nsakaimbo I didn't set them up originally but it sounds like the idea was have it run the desktop unit tests(which I am not sure it is even doing now?). I am open to running it for everything but it would cause us to use more CircleCI resources for each PR.

**Review by nsakaimbo — APPROVED** [review]
LGTM - confirmed desktop builds and runs fine with these changes in:

`https://app.circleci.com/pipelines/github/Automattic/wp-desktop?branch=test-calypso-code-split-revert`

Feel free to merge when the other pending CI jobs are complete.

**Update**: Looks like the `ci/wp-e2e-tests-full-desktop` and `ci/wp-e2e-tests-full-mobile` jobs were "canceled" - not sure if that's expected? All other jobs seemed to have ran fine.

Screen Shot 2020-04-08 at 4 47 11 PM

**Comment by nsakaimbo** [comment]
>  it sounds like the idea was have it run the desktop unit tests(which I am not sure it is even doing now?). I am open to running it for everything but it would cause us to use more CircleCI resources for each PR.

@bsessions85 Yeah it seems this is by design - the canary job waits for the build to complete, but not for an end-to-end test run. In which case runtime errors like this can slip through the cracks. I think this is deserving of a bigger conversation with Team Calypso to see if blocking on the desktop end-to-end tests might be reasonable, or alternatives to catching these sorts of things sooner rather than later.

**Pull request merged**
