### PR TITLE
Purchases: Display fullscreen pre-cancellation form for everyone

### PR DESCRIPTION
**Pull request by mmtr**
### Changes proposed in this Pull Request

This PR follows up #55891 and ends the fullscreen pre-cancellation form experiment, since it has been completed successfully. Now all users cancelling/removing a plan will get the redesigned pre-cancellation form.

#### Plan removal (WordPress.com)
Screen Shot 2021-09-13 at 16 23 01

- Use the Calypso live link below.
- Switch to a WP.com Simple site without plan.
- Go to Upgrades > Plans.
- Purchase a paid plan with credits.
- Go to Upgrades > Purchases.
- Try removing the plan you just bought. 
- Make sure you get the redesigned pre-cancellation form.
- Make sure you can remove the plan successfully.

#### Plan removal (Jetpack)
Screen Shot 2021-09-13 at 16 25 31

- Use the Calypso live link below.
- Switch to a Jetpack site without plan.
- Go to Upgrades > Plans.
- Purchase a paid plan with credits.
- Go to Upgrades > Purchases.
- Try removing the plan you just bought. 
- Make sure you get the same pre-cancellation form as in prod.
- Make sure you can remove the plan successfully.

#### Domain removal
Screen Shot 2021-09-13 at 16 27 58

- Use the Calypso live link below.
- Switch to a WP.com site without plan.
- Go to Upgrades > Plans.
- Purchase a domain with credits.
- Go to Upgrades > Purchases.
- Try removing the domain you just bought. 
- Make sure you get the same pre-cancellation form as in prod.
- Make sure you can remove the domain successfully.

#### Feature Subscription removal
Screen Shot 2021-09-13 at 16 29 33

- Use the Calypso live link below.
- Switch to a WP.com site.
- Go to Setting > Performance.
- Purchase a Jetpack Search subscription with credits.
- Go to Upgrades > Purchases.
- Try removing the subscription you just bought. 
- Make sure you get the same pre-cancellation form as in prod.
- Make sure you can remove the subscription successfully.

#### Plan cancellation (WordPress.com)
Screen Shot 2021-09-13 at 16 33 25

- Use the Calypso live link below.
- Switch to a WP.com Simple site without plan.
- Go to Upgrades > Plans.
- Purchase a paid plan with a credit card (you can use the sandbox store: PCYsg-lW4-p2#sandbox-method).
- Go to Upgrades > Purchases.
- Try cancelling the plan you just bought. 
- Make sure you get the redesigned pre-cancellation form.
- Make sure you can cancel the plan successfully.

#### Plan cancellation (Jetpack)
Screen Shot 2021-09-14 at 15 36 30

- Use the Calypso live link below.
- Switch to a Jetpack site without plan.
- Go to Upgrades > Plans.
- Purchase a paid plan with a credit card (you can use the sandbox store: PCYsg-lW4-p2#sandbox-method).
- Go to Upgrades > Purchases.
- Try cancelling the plan you just bought. 
- Make sure you get the same pre-cancellation form as in prod.
- Make sure you can cancel the plan successfully.

#### Domain cancellation
Screen Shot 2021-09-13 at 16 36 41

- Use the Calypso live link below.
- Switch to a WP.com site without plan.
- Go to Upgrades > Plans.
- Purchase a domain with a credit card (you can use the sandbox store: PCYsg-lW4-p2#sandbox-method).
- Go to Upgrades > Purchases.
- Try cancelling the domain you just bought. 
- Make sure you get the same pre-cancellation form as in prod.
- Make sure you can cancel the domain successfully.

#### Feature Subscription cancellation
Screen Shot 2021-09-13 at 16 37 23

- Use the Calypso live link below.
- Switch to a WP.com site.
- Go to Setting > Performance.
- Purchase a Jetpack Search subscription with a credit card (you can use the sandbox store: PCYsg-lW4-p2#sandbox-method)..
- Go to Upgrades > Purchases.
- Try cancelling the subscription you just bought. 
- Make sure you get the same pre-cancellation form as in prod.
- Make sure you can cancel the subscription successfully.

#### Happychat
- Connect to the staging Happychat HUD (PCYsg-b99-p2).
- Follow instructions above to cancel/remove a WP.com plan.
- Make sure you see the "Need help? Chat with us" button when you're marked as available in the HUD.
- Make sure you don't see the "Need help? Chat with us" button when you're marked as unavailable in the HUD, or when you're not connected to the the HUD.

#### Upsells
- Follow instructions above to cancel/remove a WP.com plan.
- Make sure you get the upsell below when removing/cancelling a Business plan and after selecting "I couldn't install a plugin/theme I wanted". 
  - Screen Shot 2021-09-01 at 11 25 44
- Make sure you get the upsell below when removing/cancelling a Premium plan and after selecting "I couldn't install a plugin/theme I wanted".
  - Screen Shot 2021-09-01 at 11 24 53
- Make sure you get the upsell below when **cancelling** a Premium plan and after selecting "I couldn't install a plugin/theme I wanted".
  - Screen Shot 2021-09-01 at 11 30 45

### CODE REVIEW

**Comment by dsas** [comment]
🐞 - I've noticed the top of the pre-cancellation dialog, when **removing only** that always uses the name of the primary site, not the site that is having something cancelled. The right thing does get cancelled but the name displayed while doing so is wrong. I'm pretty sure this was working on the last PR. See https://d.pr/v/qVsD7n for a video. It looks like this site slug should come from the selectedSite prop but I can't see how that's changed in this PR.

### Plan removal (WordPress.com) ✅ 
got the new pre-cancellation form
### Plan removal (Jetpack) - ✅ 
no change - the same cancellation form as is in prod
### Domain removal ✅ 
no change - the same cancellation form as is in prod
### Feature Subscription removal - ✅❓ 
no change - the same cancellation form as is in prod, which I expected but the testing instructions disagree - https://d.pr/v/eTfN2b **I'm assuming the test instructions are incorrect**
### Plan cancellation (WordPress.com) ✅ 
got the new pre-cancellation form
### Plan cancellation (Jetpack) ✅ ❓
Got the new cancellation form. Why is this different to a removal?
### Domain cancellation ❌❓ 
If I just cancel the domain via /me/purchases then I get no survey. If I cancel the plan that grants me the free domain, I do get a survey.


### Feature Subscription cancellation ✅❓ 
no change - the same cancellation form as is in prod, which I expected but the testing instructions disagree https://d.pr/i/7XR7GN **I'm assuming the test instructions are incorrect**
### Happychat ✅ 
Appeared when I was available, and didn't appear when I was not.
### Upsells
 * remove/cancel business plan with "I couldn't install plugin" - ❌ no upsell on removing or cancelling
 * remove/cancel premium plan with "I couldn't install a plugin/theme I wanted" - 
❌ no upsell on removing or cancelling, see https://d.pr/v/qVsD7n
 * cancel premium plan with "The plan was too expensive" - ❌ no upsell on cancelling

**Comment by mmtr** [comment]
Thanks for the thorough testing, @dsas!

> when removing only that always uses the name of the primary site

Let me investigate that! I wonder if these changes are related: https://github.com/Automattic/wp-calypso/pull/55992

> ### Feature Subscription removal - ✅❓
> ### Feature Subscription cancellation - ✅❓

Sorry, bad testing instructions as you pointed out 😅 

> ### Plan cancellation (Jetpack) ✅ ❓
> Got the new cancellation form. Why is this different to a removal?

For some reason, the separate form specific to Jetpack was included only in the removal flows: https://github.com/Automattic/wp-calypso/pull/54669. Not sure if the cancellation flows were intentionally left out (cc @IanRamosC, @jboland88), but this PR is updating the flows that were using the old survey which right now are WordPress.com plan cancellations, WordPress.com plan removals, and Jetpack plan cancellations.

> ### Domain cancellation ❌❓
> If I just cancel the domain via /me/purchases then I get no survey.

That's expected. You should get the same flow you currently get in prod.

> ### Upsells
Likely a bug on my end, let me take a look.

**Comment by mmtr** [comment]
> Not sure if the cancellation flows [for Jetpack products] were intentionally left out

Also asked here: p1631606938143800-slack-C01264051NE

**Comment by mmtr** [comment]
Just pushed a bunch of commits addressing the received feedback, so this should be ready for another review!

> when removing only that always uses the name of the primary site

Fixed in https://github.com/Automattic/wp-calypso/commit/3fdd8e583c2cbcb2665590cb1832be9650ca66fb

> Upsells

Fixed in https://github.com/Automattic/wp-calypso/commit/2b51f6c6756e397afce8235f9b8a5afb78f7e193

> Not sure if the cancellation flows [for Jetpack products] were intentionally left out

Seems it was not intentional, and they were missed. @simonktnga8c from the Jetpack Marketing team has asked to keep the existing cancellation form and they'll work on switching it to the specific Jetpack dialog, so in https://github.com/Automattic/wp-calypso/commit/7f31978818f105ab30b96b00ca02492cb92b321c I excluded Jetpack products from getting the new redesigned pre-cancellation form.

**Comment by dsas** [comment]
Removing now always displays the correct site name ✅
When removing a premium plan due to not being able to install a plug-in, I get the business upsell ✅
When removing a premium plan due to plan being too expensive, I don't get an upsell ✅
When cancelling a premium plan due to not being able to install a plug-in, I get the business upsell ✅
When cancelling a premium plan due to plan being too expensive i do get an upsell ✅


Happy chat: it appears when there are operators, haven't yet tried without operators.

**Comment by BogdanUngureanu** [comment]
Followed the testing instructions and couldn't find any issues! 🚢 

> Happy chat: it appears when there are operators, haven't yet tried without operators.

Probably because I was on staging hud.

**Comment by DavidRothstein** [comment]
I did some brief testing of a few different scenarios and the cancellations all seemed to work correctly.  (I did not do a full code review.)

One thing I noticed, though, is that WordPress.com already has a lot of different cancellation surveys with different styles, and this adds yet another.  With this pull request, the same user can now see very different survey styles for the exact same subscription, depending on whether they are cancelling it or removing it, etc.  Hopefully there's a plan to clean that up somewhere.

**Comment by mmtr** [comment]
Thanks everyone for your feedback! @dsas @BogdanUngureanu, are you planning to do more testing or did you miss to approve this PR?

> With this pull request, the same user can now see very different survey styles for the exact same subscription, depending on whether they are cancelling it or removing it, etc. 

Not sure that has been introduced by this PR. AFAIK, there are differences between the cancellation and removal flows only on Jetpack products (Jetpack plans, Jetpack Search, etc) and domains, but that's already the case in production.

This PR only modifies the flow for WP.com plans, and both the cancellation and the removal should get the same survey with the same styles.

**Review by BogdanUngureanu — APPROVED** [review]

**Comment by dsas** [comment]
> did you miss to approve this PR?

Sorry, I was kind of confused about workflow, I wasn't sure if we were all supposed to hit approve, or if the last person should

**Comment by mmtr** [comment]
> Sorry, I was kind of confused about workflow, I wasn't sure if we were all supposed to hit approve, or if the last person should

We usually only need one person approving. It's fine to have more than one reviewer, but the first one who is happy with the changes usually hits the approval button.

**Comment by michaeldcain** [comment]
> Not sure that has been introduced by this PR.

@mmtr this PR does add a new design without removing any of the old ones (there is now an additional difference between Jetpack Plan removal and WPcom Plan removal, and an even greater difference between WPcom Plan removal and domain removal than before), but I think that's beside the point. I don't believe David was blocking this PR, he was just asking if your pod has any plans to consolidate some of the various differences between these flows in the future - even if it's only the WPcom-specific ones. 

This new blank canvas design looks great, but if we don't commit to updating the other flows, the product will only feel more disjointed going forward. It doesn't necessarily matter where the difference was introduced, only that we try to make the product better going forward.

Are there any plans to port the domain removal message or the WPcom feature subscription cancellation to the blank canvas design?

**Comment by mmtr** [comment]
Thanks @michaeldcain for the extra context, apologies if I sounded too defensive!

I agree that ideally we should consolidate all the WP.com cancellation flows to use the new design. Actually I did try that at the beginning, but our pod only investigated the plans specific ones as part of the design exploration that resulted in the final i1 design (pdgTfM-3T-p2). It wasn't trivial for me to adapt the cancellation flows to the new design (it certainly needs more explorations from the design team), so I decided to reduce the scope and focus only on plans which is what our pod needs to achieve our goal of automating the Atomic reverts.

> this PR does add a new design without removing any of the old ones

It removes this one at least: 


Although Jetpack plans cancellations still use it (which is why I couldn't completely remove the code and had to bring it back in https://github.com/Automattic/wp-calypso/commit/1772e87efbff3e6d8a5480bf7d6161460a5eb481), that's due to an unintentional mistake, and the Jetpack Marketing team is planning to stop its usage (p1631621900150600/1631606938.143800-slack-C01264051NE).

> Are there any plans to port the domain removal message or the WPcom feature subscription cancellation to the blank canvas design?

Not in the short team. I'm planning to publish a next steps post once our pod wraps up the automated Atomic revert project, and will mention the need of consolidating the cancellation flows as something that should be considered for planning in the backlog of a team. If for any reason that task doesn't get any attention, I'd be happy to work on that as part of my 20% time or in a HACK day project.

**Comment by michaeldcain** [comment]
> Although Jetpack plans cancellations still use it (which is why I couldn't completely remove the code and had to bring it back in 1772e87), that's due to an unintentional mistake, and the Jetpack Marketing team is planning to stop its usage

I saw that you tracked that down and reported it to them - thanks for taking that extra effort. We missed the Jetpack updates in their entirety when they were made, or I probably would've posted the same comment about consistency there :).

> I'm planning to publish a next steps post once our pod wraps up the automated Atomic revert project, and will mention the need of consolidating the cancellation flows as something that should be considered for planning in the backlog of a team.

Awesome, thanks for following-up with that.

> If for any reason that task doesn't get any attention, I'd be happy to work on that as part of my 20% time or in a HACK day project.

I don't think you necessarily have to take this on yourself, but if it doesn't get picked up by the pod, can y'all make a Calypso issue to track it and ping Shilling? We can add it to our backlog and try to mix it into any future cancellation flow updates - I just don't want it to get lost in the pod shuffle.

Thanks again for following up on the discussion (and also for just adding a better-designed survey in the first place)!

**Comment by DavidRothstein** [comment]
Sorry for the confusion - I could have sworn that when I tested this pull request, the cancel-vs.-remove flows for WordPress.com plans were using different styles, but when I try it now that's not the case.  I may have been confusing the WordPress.com and Jetpack flows somehow.

That said, there are still some inconsistencies introduced here for WordPress.com (including on the same subscription), just not the main one I was thinking of :smile:  This is the survey when disabling auto-renew, for a WordPress.com plan (or anything else):

disable-auto-renew

It's a different survey, of course, but stylistically it's the same as the old plan cancellation survey (that was removed in this pull request), not the new survey.  So ideally it would be updated to the new visual style at some point.

Same thing for the survey used when cancelling/removing a non-plan purchase on WordPress.com (although I realize you deliberately only looked at plans in this pull request):

wpcom-product

Also, for Jetpack, this part:

>the Jetpack Marketing team has asked to keep the existing cancellation form and they'll work on switching it to the specific Jetpack dialog

I can see how they will do that for the cancel/refund scenario, but that's not the only place the existing cancellation form is used.  It's also used during the first step of cancelling/removing a non-refundable subscription:

https://user-images.githubusercontent.com/235183/133851867-4e941ed8-8e50-423b-8f05-5a56cb1c626c.mp4

In that case, it can't be replaced with the same survey that they already use in the second step (and it wouldn't make sense to, since the product isn't being removed yet) so unless they're planning to design a whole new survey, which is doesn't sound like, I think replacing it with the new survey style you introduced here would be the best long term option?

Anyway, thanks for working on this!

**Comment by DavidRothstein** [comment]
>In that case, it can't be replaced with the same survey that they already use in the second step (and it wouldn't make sense to, since the product isn't being removed yet) so unless they're planning to design a whole new survey, which is doesn't sound like, I think replacing it with the new survey style you introduced here would be the best long term option?

Unless the plan is to replace it with the **very** last screen shown in that video only ("Before you go, help us improve Jetpack").  I guess it's possible to use that screen without the "Are you sure you want to cancel?" screen that appears before it during the removal step, and that would probably work for the cancellation step.  So maybe that's what they can do eventually instead.

**Comment by mmtr** [comment]
> can y'all make a Calypso issue to track it and ping Shilling?

Nice idea, I went ahead and created one in https://github.com/Automattic/wp-calypso/issues/56393.

> disabling auto-renew
> cancelling/removing a non-plan purchase on WordPress.com

Good catches! I agree we should consolidate this flow as well under the new design, so I added them to https://github.com/Automattic/wp-calypso/issues/56393.

> I can see how they will do that for the cancel/refund scenario, but that's not the only place the existing cancellation form is used. It's also used during the first step of cancelling/removing a non-refundable subscription:

Asked them in p1632137293169200/1631606938.143800-slack-C01264051NE, I think they want all the Jetpack products to use the same dialog, so if needed I guess they'll introduce any variant to the existing dialog to denote the subscription won't be removed and will be kept active.

**Pull request merged**
