### PR TITLE
Jetpack Description: update with Site Accelerator / Activity Log

### PR DESCRIPTION
**Pull request by jeherve**
@see p6TEKc-2mI-p2

#### Changes proposed in this Pull Request

* Update the Jetpack Essentials Features description with info about the Site Accelerator (#27944) and the activity log.

image

#### Testing instructions

* Fire up this PR.
* Head to http://calypso.localhost:3000/plans/
* Make sure the copy is correct.

### CODE REVIEW

**Comment by keoshi** [comment]
I now realize that the new plan tables on logged out wordpress.com are already using this description, but I'm still not sure if we should be changing the text on this PR or the other way around. Is there a discussion about this on a P2?

**Comment by jeherve** [comment]
>  Is there a discussion about this on a P2?

Yes, see the link in the PR description above.

p6TEKc-2mI-p2

**Comment by keoshi** [comment]
Sorry, missed that (new computer, didn't have the TM script installed). Will bring up that point in that thread.

**Comment by keoshi** [comment]
Updated the PR with the latest copy revision. @see p6TEKc-2mI-p2 #comment-5355

This is ready for a review, @joanrho

**Pull request merged**
