### PR TITLE
Emails: Update Google Workspace learning center link

### PR DESCRIPTION
**Pull request by AllTerrainDeveloper**
#### Changes proposed in this Pull Request

The link provided at the end of the process to buy a Google Workspace, was outdated. This pull request updates the link
image

- [x] Checked with a real WordPress purchase.

#### Testing instructions

1. Proceed with a Google Workspace purchase
2. check the link in the button: "Learn more about Google Workspace"

Expected value
https://support.google.com/a/users#topic=9393003

Related to 1200182182542585-as-1200414925548945

### CODE REVIEW

**Comment by stephanethomas** [comment]
> Expected value
> https://support.google.com/a/users#topic=9393003

Well, it seems that this link is redirecting to https://support.google.com/a/users#topic=9917952 now 😒. Looking at the url of the `Help Center` tab in the `Google Workspace Learning Center`, we could probably use https://support.google.com/a/users though: that way we have a true permalink, which is also a bit less cryptic.

**Comment by AllTerrainDeveloper** [comment]
> > Expected value
> > https://support.google.com/a/users#topic=9393003
> 
> Well, it seems that this link is redirecting to https://support.google.com/a/users#topic=9917952 now 😒. Looking at the url of the `Help Center` tab in the `Google Workspace Learning Center`, we could probably use https://support.google.com/a/users though: that way we have a true permalink, which is also a bit less cryptic.

Nice catch. I´ve used your solution.

**Comment by olaseni** [comment]
> > Well, it seems that this link is redirecting to https://support.google.com/a/users#topic=9917952 now 😒. Looking at the url of the `Help Center` tab in the `Google Workspace Learning Center`, we could probably use https://support.google.com/a/users though: that way we have a true permalink, which is also a bit less cryptic.

Hey @stephanethomas what about `https://workspace.google.com/learning-center/`. It also redirects to the link at `https://support.google.com/a/users` but I'll be more confident to use that just in case Google decides to change the destination in the future.

**Comment by olaseni** [comment]
> 
> Related to [Asana Ticket](1200182182542585-as-1200414925548945)

Hey @AllTerrainDeveloper, we shouldn't show urls to internal resources here since PRs on this repo are world viewable. Could you take a look at this field guide on how to code internal urls: PCYsg-5Xx-p2 ?

That image in the PR summary also clearly shows your official email address. You should change it, as you don't want your address to get spammed. We often use more generic, non-PII specimens on Github.

**Comment by AllTerrainDeveloper** [comment]
> > Related to [Asana Ticket](1200182182542585-as-1200414925548945)
> 
> Hey @AllTerrainDeveloper, we shouldn't show urls to internal resources here since PRs on this repo are world viewable. Could you take a look at this field guide on how to code internal urls: PCYsg-5Xx-p2 ?
> 
> That image in the PR summary also clearly shows your official email address. You should change it, as you don't want your address to get spammed. We often use more generic, non-PII specimens on Github.

Thank you @olaseni !

**Review by stephanethomas — APPROVED** [review]
The change looks good to me.

**Pull request merged**
