### PR TITLE
Remove Posts Flux stores

### PR DESCRIPTION
**Pull request by jsnajdr**
This PR removes all Posts Flux stores except the `PostEditStore` which is still used.

Here is a step-by-step guide on how to reason about these removals:

1. The only Post Flux actions that are still used are `edit`, `startEditingNew`, `startEditingExisting`, `autosave`, `saveEdited`, `update/deleteMetadata`, `block/unblockSave`, `edit/resetRawContent`. All others can be removed, especially those that depend on the `post-list-store-factory` import.

2. After these actions are removed, the `post-list-store-factory`, `post-list-store` and `post-list-cache-store` modules can be removed, too.

3. The only usage of the `posts-store` module is figuring out the `original` field in the `saveEdited` and `receiveUpdate` actions. This field is not used in the `PostEditStore` dispatcher and there is no other store remaining that dispatches these actions. Therefore, `posts-store` can be removed.

4. The `fetchCounts` action is not used at all and wasn't used before this patch.

How it affects chunk sizes:
```
chunk                                       stat_size           parsed_size           gzip_size
async-load-design-blocks                     -28818 B  (-1.0%)     -10544 B  (-0.6%)    -3194 B  (-0.9%)
async-load-layout-masterbar-drafts-popover       +0 B                  +0 B                -1 B  (-0.0%)
build                                           +20 B  (+0.0%)      -1191 B  (-0.1%)     -177 B  (-0.0%)
manifest                                         +0 B                  +0 B                -1 B  (-0.0%)
post-editor                                  -28818 B  (-1.2%)     -10544 B  (-1.0%)    -3223 B  (-1.3%)
posts-custom                                 -28818 B  (-8.0%)     -10544 B  (-5.8%)    -3335 B  (-8.3%)
posts-pages                                  -28818 B  (-6.3%)     -10544 B  (-4.6%)    -3196 B  (-6.2%)
reader                                           +0 B                  +0 B                -1 B  (-0.0%)
```

### CODE REVIEW

**Review by samouri — APPROVED** [review]

**Comment by samouri** [comment]
I did some grepping around and confirmed that everything deleted was unused. I love all the red!

**Comment by gwwar** [comment]
Most of the tests passed in the full suite https://circleci.com/gh/Automattic/wp-e2e-tests-for-branches/3780 🎉

```
(37 / 37) <-- Worker 3 FAIL  [WPCOM] Invites:  (mobile) Inviting New User as an Editor: @parallel @jetpack @chrome  
(37 / 37) <-- Worker 1 FAIL  [WPCOM] Invites:  (mobile) Inviting New User as an Contributor, then change them to Author: @parallel @jetpack @chrome  
```
cc @Automattic/flowpatrol are the mobile invite tests sometimes flakey?

**Comment by bsessions85** [comment]
@gwwar  I re-ran the tests and those tests passed and a different on failed. We've been having stability issues lately so I'd say you're good to go here.

**Comment by gwwar** [comment]
Awesome thanks @bsessions85 !

**Review by gwwar — APPROVED** [review]
Great work ✨!

**Comment by jsnajdr** [comment]
OK, I'll merge and watch the tests closely. If the failures turn out to be permanent, let's revert.

**Pull request merged**
