### PR TITLE
E2E: Fix flaky Magic Link spec

### PR DESCRIPTION
**Pull request by WunderBart**
#### Changes proposed in this pull request
- Fix [flaky spec](https://app.circleci.com/pipelines/github/Automattic/wp-e2e-tests-for-branches/61296/workflows/19a2f0e9-60f8-4184-8cb7-28ea6b3fd3e6/jobs/148291/tests#failed-test-0), where the magic link button is clicked but the user is not taken to the magic link page.

#### The issue
Recently, the [magic link spec](https://github.com/Automattic/wp-calypso/commit/46d39bf16dd05b621e2c891c7bec41d1fff108bc) became [flaky again](https://github.com/Automattic/wp-calypso/pull/46506#issuecomment-796927648). It's most probably due to changes made in https://github.com/Automattic/wp-calypso/pull/50448, where the actual link was turned into a button element. It's flaky because when the page loads, the content is either static or [disabled due to pending auth requests](https://github.com/Automattic/wp-calypso/commit/c3d246fcd55363960e7955ba109f2c0517cdcb1d) for a little while (depending on connection), during which the button's onClick callback is not available. It was working for the anchor element as its `href` was a [direct URL to the magic link page](https://github.com/Automattic/wp-calypso/pull/50448/files#diff-21c2c5acd2fead7015afc57ba54574caf4a5f46599669a18d438f003ebbd0a58L235). 

To reproduce the failing scenario you'll need to
- log out from .com,
- open the [login page](https://wordpress.com/log-in),
- set `Slow 3g` throttle in Chrome's DevTools' Network tab,
- click and hold the refresh button until you see the refresh menu
- select the `Empty cache and hard reload` option
- notice how the form is disabled initially, and start clicking the `Email me a magic link` button - nothing should happen
- keep clicking and once the form becomes enabled, the button becomes intractable as well.

Here's the demo video:

https://user-images.githubusercontent.com/1451471/110943155-2ad76380-833b-11eb-8bac-141d61833d42.mov

#### The solution
As you can see in the video above, a good indicator of when the content becomes interactable is the moment the login form becomes enabled. So, a solution to this issue is simply [waiting for one of its elements to become _not disabled_](https://github.com/Automattic/wp-calypso/pull/50999/files#diff-96349e79581672f9877ed4893835d124a03d69e91f44b90252338a1c43b2b5afR103-R112). Once it's passed that step, the magic email **button** can be safely clicked. 

#### Post-factum thoughts
While this trick fixes the spec, it actually reveals a problem within the magic link button implementation. If the button was hidden or disabled until it's actually interactable, this spec wouldn't become flaky at all. This is not a big deal as the button is not interactable only for a short while (depending on the cache and connection speed). Having said that, I think a proper solution would be fixing the button instead in another PR. What do you think, folks? Any chance you could help with that, @monsieur-z?

### CODE REVIEW

**Review by worldomonation — APPROVED** [review]
Nice solution plus you were able to remove the extra sleep 👍

**Comment by monsieur-z** [comment]
> Any chance you could help with that, @monsieur-z?

Switching back to an `a` tag seems like the best solution indeed. It's semantically more correct, and provides a more accessible experience. I've managed to find a workaround for the initial issue in this PR: #51045.

**Comment by WunderBart** [comment]
> > Any chance you could help with that, @monsieur-z?
> 
> Switching back to an `a` tag seems like the best solution indeed. It's semantically more correct, and provides a more accessible experience. I've managed to find a workaround for the initial issue in this PR: #51045.

Agree, `a` seems a much better solution. Thanks for creating the PR, @monsieur-z!

**Comment by WunderBart** [comment]
For some reason, this spec is still flaky, even after the https://github.com/Automattic/wp-calypso/pull/51045 fix ([example](https://app.circleci.com/pipelines/github/Automattic/wp-e2e-tests-for-branches/63826/workflows/7c63a56e-61e4-4738-8ef1-fc3bdd678fea/jobs/153328)). The magic link seems to not be interactable before the form is. Going to merge this one if it passes the current job. cc @monsieur-z

**Pull request merged**
