### PR TITLE
Domains: Do not try to cancel transfer if domain is not pending transfer

### PR DESCRIPTION
**Pull request by aidvu**
When a domain is not pending transfer, we would try to cancel the transfer through the API, which would result in an error.

### CODE REVIEW

**Comment by klimeryk** [comment]
So in that situation, how would you re-lock the domain?

**Comment by aidvu** [comment]
I now see that it isn't just a `cancel transfer` call, but a few more actions. Will add a different button for relock/reenable privacy.

**Comment by aidvu** [comment]
Will squash after review.

**Comment by klimeryk** [comment]
Sweet - this has been bugging me too :) :shipit:

**Pull request merged**
