### PR TITLE
Me: Add setting to disable gravatar

### PR DESCRIPTION
**Pull request by roundhill**
#### Changes proposed in this Pull Request

* This is a continuation of #31624, in simplified form. On the profile settings we now offer a toggle for a user to disable their gravatar profile and associated images from appearing:

Screen Shot 2021-04-09 at 12 34 58 PM

#### Testing instructions

**This requires changes to the wp.com api and gravatar to work**, see D59876-code and D59883-code for further instructions. Once that is set up, you can:

 * Head over to `/me`
 * Enable the hidden profile toggle and click save.
 * Head over to gravatar.com, your profile and avatar images should be disabled.
 * Turn the toggle off again.
 * Refresh gravatar, and your profile should be enabled.

@catscheer I added you here so you can have a look at the copy and general functionality!

### CODE REVIEW

**Comment by catscheer** [comment]
@roundhill quick question. Will this "hide" toggle still function the way Kuba's "disable" setting previously did and delete everything after being disabled for 30 days? If so we should probably warn users about that.

**Comment by roundhill** [comment]
> @roundhill quick question. Will this "hide" toggle still function the way Kuba's "disable" setting previously did and delete everything after being disabled for 30 days? If so we should probably warn users about that.

No, this will only disable the profile. If the user wants to delete it, they can still do that on Gravatar.com

**Comment by catscheer** [comment]
@roundhill but it hides it everywhere right? So the image wouldn't display on any site?

**Comment by roundhill** [comment]
> @roundhill but it hides it everywhere right? So the image wouldn't display on any site?

Yes, that's right. The gravatar image will no longer load, and neither will the profile page (like at https://gravatar.com/danroundhill)

**Comment by catscheer** [comment]
Perfect. So based on that I think the written description here is very clear. It states exactly what it does, neither over or under promising. The only thing I'd suggest would be adding a sentence that says something like, "Gravatar profiles can be deleted on gravatar.com" with a link off to the deletion page. That way a user who wants to completely delete their Gravatar knows where to go.

**Review by jgcaruso — APPROVED** [review]
Code looks good and it tested really well!

Just from a user perspective, not knowing exactly how long I will have to wait for the images to disappear felt a little like it didn't work. I know we have no control over how long other sites or servers may cache the images for, but if we can have something a little more concrete around when it will disappear from Gravatar.com that might at least give the user some more confidence that it worked.

Also, instantly hiding it from the `/me` page based on that flag might also be a bit more confidence inspiring. At least so there is some visual indication that something happened, other than the popup message that the save worked.

**Comment by roundhill** [comment]
> The only thing I'd suggest would be adding a sentence that says something like, "Gravatar profiles can be deleted on gravatar.com" with a link off to the deletion page

Thanks @catscheer, here's how it looks now:

Screen Shot 2021-04-19 at 9 31 30 AM

**Comment by catscheer** [comment]
Love it.

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/5881944

Thank you @roundhill for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/5881944).

**Pull request merged**
