### PR TITLE
Sibyl: track contact after clicking on question

### PR DESCRIPTION
**Pull request by notnownikki**
We want to track if a user still contacts support after
clicking a question that Sibyl suggested.

Testing:

1) Fill out the contact form, using the word 'quirkafleeg'
2) Click the "How do I perform a quirkafleeg" question
3) Submit the form
4) Check that the 'calypso_sibyl_support_after_question_click' event was tracked
5) Delete the contents of the contact form
6) Enter something about domains
7) Do not click any of the questions
8) Submit the form
9) Check that the 'calypso_sibyl_support_after_question_click' event was not tracked

### CODE REVIEW

**Comment by johngodley** [comment]
I don't know how to check if the event was tracked so added some console output to the tracking function.

If I enter a subject and immediately enter the content, then click an answer and then click submit, the event is fired.

If I enter a subject, click an answer, enter the content, and click submit the event is not fired.

**Comment by jsnmoon** [comment]
I ran into some issues:

1. Right clicking to open the `How do I perform a quirkafleeg?` link in a new tab does not set HelpContactForm's `state.sibylClicked` to true. (Left clicking the HelpResult works as expected, though. Left clicking correctly toggles the state and fires the `calypso_sibyl_question_click` event. )

2. I don't see the `calypso_sibyl_support_after_question_click` event firing when submitting the form with `state.sibylClicked === true`.

**Comment by notnownikki** [comment]
@jsnmoon 

> Right clicking to open the How do I perform a quirkafleeg? link in a new tab does not set HelpContactForm's state.sibylClicked to true.

Yeah, I was willing to live with this because there's no way of knowing if the user actually followed the link after right clicking. They might open in a new tab, inspect the element, copy the link and paste it somewhere, print the page... so this is a compromise we're aware of.

> I don't see the calypso_sibyl_support_after_question_click event firing when submitting the form with state.sibylClicked === true.

I can't replicate this one. The code is literally:

```
		if ( this.state.sibylClicked ) {
			// track that the user had clicked a Sibyl result, but still contacted support
			this.props.trackSupportAfterSibylClick();
			this.setState( { sibylClicked: false } );
		}

```

...so if that `if` statement isn't working as expected when `this.state.sibylClicked` is `true` I'm not sure what to suggest. Can you `console.log` the state at that point? I'm wondering if your test modified the redux state instead of the component's state.

**Comment by notnownikki** [comment]
@johngodley 

> If I enter a subject, click an answer, enter the content, and click submit the event is not fired.

Yeah, we only want to track the flow of "message -> question click -> support" because that is the strongest suggestion that the user found a question relevant to their message, clicked it, and decided to contact support anyway without modifying their message.

**Comment by notnownikki** [comment]
@johngodley actually, you've made me think more about this and we shouldn't reset on message modification. If we track that initial click, then we do need to log that the click still resulted in a support message. Will fix.

**Comment by notnownikki** [comment]
@johngodley ok, thought this through again!

We didn't want to log the situation where a user enters a message, clicks a question, then changes their message, gets a new set of questions and DOESN'T click them, and goes on to support.

I've modified this so that `sibylClicked` is only reset to `false` when the user modifies their message, if the set of returned questions changes in response to their modification.

**Comment by johngodley** [comment]
Changes work for me and take care of the instance I had above which is where a subject is entered without message content, an answer is clicked, and then some message content is entered after.

:shipit: from me, pending if @jsnmoon has resolved the issue

**Comment by jsnmoon** [comment]
Ah, it might've been my Redux Devtools malfunctioning. I can confirm that the `calypso_sibyl_support_after_question_click` event is being fired correctly.

Looks good! 🚢

**Pull request merged**
