### PR TITLE
Storybook: Include missing typography file to fix storybook in root

### PR DESCRIPTION
**Pull request by wojtekn**
Related to p1684837680214529-slack-C04GESRBWKW

## Proposed Changes

In this PR, I propose to fix the error that pops out when I start the root storybook and prevents me from using it. I fix it by adding an import for file that defines typography variables.

## Testing Instructions

1. Build or run storybook in root:

```
yarn storybook:build
```

```
yarn storybook:start
```

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

**Review by sejas — APPROVED** [review]
This PR fixes the issue and I was able to launch storybook by running `yarn storybook:start`.

I don't fully understand why it's needed to add this import in each `.scss` file using variables if we already import it in the `index.scss` of the storybook root

https://github.com/Automattic/wp-calypso/blob/325d4441248784953ec72ebb8881b43d89126d28/.storybook/index.scss#L4

**Comment by wojtekn** [comment]
> I don't fully understand why it's needed to add this import in each .scss file using variables if we already import it in the index.scss of the storybook root

@okmttdhr should we keep adding those imports in affected components, or should we try fixing it globally? I found https://github.com/storybookjs/storybook/issues/6364, but I was not really sure how to apply those recommendations in our storybook configuration.

**Comment by okmttdhr** [comment]
> > I don't fully understand why it's needed to add this import in each .scss file using variables if we already import it in the index.scss of the storybook root
> 
> @okmttdhr should we keep adding those imports in affected components, or should we try fixing it globally? I found [storybookjs/storybook#6364](https://github.com/storybookjs/storybook/issues/6364), but I was not really sure how to apply those recommendations in our storybook configuration.

I'm not quite sure, but each `.scss` file seems to be built separately?
So it can't reference scss variables in `.storybook/index.scss` when it builds a story.

I believe there will be a way to prevent it by changing the webpack config for Storybook.

**Comment by wojtekn** [comment]
> I believe there will be a way to prevent it by changing the webpack config for Storybook.

@okmttdhr I think there are, I saw a few ways proposed in the linked ticket, but I couldn't make those working. I didn't spend too much time on that, though.

I will merge this one as is for now to let us use storybook in the root.

**Pull request merged**
