### PR TITLE
Sites Dashboard: Update action's `isEligible` checks to exclude Jetpack/P2 sites from the action options

### PR DESCRIPTION
**Pull request by lsl**
Fixes https://github.com/Automattic/dotcom-forge/issues/9971

## Proposed Changes

The Jetpack action items were lost when merging https://github.com/Automattic/wp-calypso/pull/94238/files?w=1#diff-173bec7d847197dc6a90c47661016102ba95728dab618e17b774c11c7ed1994cL550-L565, this PR adds these actions and the migration related ones back into the list. It also hides the wpcom site actions that aren't relevant to Jetpack/p2 sites.

## Testing Instructions

* [x] non-Atomic Jetpack sites
	* [x] Create a site with jurassic
	* [x] Connect your WP.com account through Jetpack
	* [x] Observe your site is listed on /sites
	* [x] Observe 'Jetpack Cloud', 'Billing', 'Support', 'Migrate to WordPress.com' actions are shown.
	* Screenshot 2024-11-28 at 9 46 21
* [x] non-Atomic sites added via A4A plugin 
	* [x] Go to https://agencies.automattic.com/sites
	* [x] Click "Add sites" > "Via the Automattic plugin" and enter your site's URL
	* [x] Install and activate A4A plugin on your site 
	* [x] Connect your site
	* [x] Observe your site is listed on https://wordpress.com/sites
	* [x] Observe 'Migrate to WordPress.com' actions are shown. 
	* Screenshot 2024-11-28 at 9 58 28
	* I was unsure how to create a _Jetpack disconnected_ non-Atomic site. The original code and the comment suggests _[Sites connected through A4A plugin are listed on wordpress.com/sites even when Jetpack is deactivated](https://github.com/Automattic/wp-calypso/blob/50ee79856956e06976f0e3d56b7948355af727c3/client/sites-dashboard/utils.ts#L57)_, but when you connect a site through A4A plugin, Jetpack gets connected automatically. If you disconnect Jetapck afterward, the site no longer appear on wp.com/sites anymore. 
* [x] P2 sites
	* [x] Observe some actions are hidden (See `sites-dataviews-actions.test.ts`).
* [x] Observe no regressions for Simple sites and Atomic sites

### CODE REVIEW

**Comment by lsl** [comment]
> I was unsure how to create a Jetpack disconnected non-Atomic site. The original code and the comment suggests [Sites connected through A4A plugin are listed on wordpress.com/sites even when Jetpack is deactivated](https://github.com/Automattic/wp-calypso/blob/50ee79856956e06976f0e3d56b7948355af727c3/client/sites-dashboard/utils.ts#L57), but when you connect a site through A4A plugin, Jetpack gets connected automatically. If you disconnect Jetapck afterward, the site no longer appear on wp.com/sites anymore.

This required creating the site via pressable and deactivating Jetpack + Jetpack protect while still having the A4A client plugin installed (the a4a client plugin maintains a Jetpack connection irrc). 

All the hosting options are hidden, only open/wpadmin/move links are present:

Screenshot(138)
Screenshot 2024-11-28 at 15-31-41 Plugins ‹ My WordPress Site — WordPress

**Comment by lsl** [comment]
P2:
Screenshot(140)

Self hosted JP:
Screenshot(139)

Simple sites:
Screenshot(142)

Atomic:
Screenshot(143)

Staging:
Screenshot(144)

**Comment by fushar** [comment]
> Observe no regressions for Simple sites and Atomic sites

Simple sites are now missing the `Plugins` menu item. Not sure if this is expected or not 🤔

**Comment by okmttdhr** [comment]
> > Observe no regressions for Simple sites and Atomic sites
> 
> Simple sites are now missing the `Plugins` menu item. Not sure if this is expected or not 🤔

Thanks for checking! This should be a regression 😕: https://github.com/Automattic/wp-calypso/pull/96803/files#diff-89dc39cfbeaf58153c499e1c077f3b51708ce576f99692456272e1dd164ec559L304-L310.

**Review by okmttdhr — APPROVED** [review]
LGTM 🚀

**Pull request merged**
