### PR TITLE
Happychat: Refactor to use middleware (attempt 2)

### PR DESCRIPTION
**Pull request by jordwest**
**This is now replaced with #12218. See Automattic/happychat#275**

Depends on #11821 

This PR has minimal functional changes and is mostly a refactor.

If a chat was active in the last 10 minutes and an operator is still available, the Happychat icon will now be shown in the bottom left of the sidebar after boot. We can bump the timeout higher once we're confident that the service can handle a higher number of connections.

This was originally #11381 but had to be reverted in #11561. Commit e38a250 fixes the issue that made the revert necessary.

### Testing instructions

1. Run automated tests with `npm run test-client client/state/happychat`
1. Confirm that chat works as usual
1. Reload Calypso, confirm that Calypso automatically reconnects to Happychat (the transcript is not yet shown).
1. Wait at least 10 minutes after sending a message, then refresh Calypso again. Confirm that Calypso does not automatically connect to Happychat, until you visit /help/contact.

### CODE REVIEW

**Comment by jordwest** [comment]
This is now rebased on top of (and depends on) #11821 to give the user messaging if they try to start a chat from the sidebar icon and no operators are available. Without the notices, the chat appears to be connected but messages are never replied to.

**Comment by jordwest** [comment]
@beaucollins Since you're familiar with the original incarnation of this, would you mind taking a look at this second attempt? Most of my additions are in 88a25b5

**Comment by beaucollins** [comment]
Should the chat button in the sidebar still show after 10 minutes. It did in my testing although it did not connect to the websocket until I pressed it.

**Comment by jordwest** [comment]
Hmm, good point, for now that button should probably only show if happychat is available/recently used. This PR needs to be rebased to incorporate the recent changes in `master`, so I'm going to mark this as in progress and look at that then.

**Pull request closed without merging**
