### PR TITLE
Store Promotions: Add appliesTo component

### PR DESCRIPTION
**Pull request by coderkevin**
This adds a tree selector component for "Applies To" on the form for
promotion editing. It allows selection of all products, product
categories, or individual products.

To Test:
1. `npm start`
2. Visit `http://calypso.localhost:3000/store/promotion/<site url>`
3. Observe "Applies To" selector, it should load with products and product categories.
4. Click a product, observe it being selected.
5. Click that product's category, observe all products selected.
6. Click the first product again, observe that it does not unselect because its category is selected.
7. Click the product category again, all should be unselected now.
8. Attempt above sequence (4-7) with the "All" selection.
9. If a product has more than one category, it should always show as selected/unselected in both places.

### CODE REVIEW

**Comment by justinshreve** [comment]
I'm getting an extra checkbox in front of one of my categories

screen shot 2017-10-17 at 10 39 23 am

`Accessories`, `Hoodies`, `this is a brand new category` and `test` are all categories.

`T-Shirt #3` is inside the `test` category `this is a brand new category` but NOT the `hoodies` category.

`test` is NOT a subcategory of hoodies.

The highlighted blue checkbox is the one that actually selects the category and product. The other checkbox is extra, and checks, but doesn't do anything else.

**Comment by kellychoffman** [comment]
For Product Categories, can you re-use the filterable list that shows when adding a new category in the editor? This should help us get to a good place styling wise.

screen shot 2017-10-17 at 3 12 08 pm

**Comment by justinshreve** [comment]
Posting this so it doesn't get lost in scrollback: p1508270022000354-slack-store-on-wpcom

**Comment by kellychoffman** [comment]
I also think we need to keep the All Products, Categories, Products dropdown so that the user can filter up front. It will also make the list less overwelming. 

All Products: No list
Categories: Filterable list displaying only categories
Products: Filterable list displaying only products (ideally with thumbnails)

**Comment by coderkevin** [comment]
This PR is on hold pending the resolution of the rest of the Promotions code.

**Comment by coderkevin** [comment]
This has been implemented a different way.

**Pull request closed without merging**
