### PR TITLE
Performance Profiler: Add filtering to the recommendations section

### PR DESCRIPTION
**Pull request by WBerredo**
Fixes https://github.com/Automattic/dotcom-forge/issues/9049

## Proposed Changes

Add a dropdown with options to filter the recommendations by metric.

CleanShot 2024-09-11 at 09 51 29@2x

## Why are these changes being made?

Fixes https://github.com/Automattic/dotcom-forge/issues/9049

## Testing Instructions
* Go to `speed-test-tool?url=https%3A%2F%2Fwordpress.com%2F&hash=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6NzQ2N30.LOelpUBxFDxMytpSYeB3EBNdBnHeYTvonyZ6zE7aqSM`
* Check if the dropdown is displayed on the Recommendations section
* Click in the list and see if the filtering is done.

### CODE REVIEW

**Review by epeicher — COMMENTED** [review]
I have tested the functionality, and it works great. I can see the filtered results when changing the dropdown, or selecting All. 

Regarding styles, are we going to create a follow-up task to match the design in Figma? We can add some padding, I have tried, but the caret needs some update 
CleanShot 2024-09-11 at 11 21 18@2x

Additionally, as a potential follow-up task. Do you think we should add a placeholder when filtering and there are no results? At the beginning I thought it was not working fine

**Comment by epeicher** [comment]
I have added the changes in my review in this commit [9eb951c](https://github.com/Automattic/wp-calypso/pull/94388/commits/9eb951c987b990d11c1a7ad6665bb7548f9ef73e) as a suggestion, but feel free to update it if required.

**Comment by matt-west** [comment]
> Regarding styles, are we going to create a follow-up task to match the design in Figma? We can add some padding, I have tried, but the caret needs some update

@WBerredo reached out via Slack for clarification on the styles.

> Do you think we should add a placeholder when filtering and there are no results? At the beginning I thought it was not working fine

The text below the header should change to reflect that no recommendations are available.

image

**Comment by WBerredo** [comment]
@epeicher @matt-west I've updated the dropdown to use the `SelectDropdown` component.

CleanShot 2024-09-11 at 09 51 29@2x

**Review by epeicher — APPROVED** [review]
I have tested it after the latest changes, and it works great! I have added margin bottom to the insights title in [9edc21f](https://github.com/Automattic/wp-calypso/pull/94388/commits/9edc21f932db8a4e825f5a3e49c19977b489a6b1). 

Also, I like very much how you [added the options](https://github.com/Automattic/wp-calypso/pull/94388/files#diff-13aa4d51c6803a2d48c1582d6cce03c6b8cca1a79384eb4247feaf2d45b161e4R61) to the dropdown ⭐ 

|No filter | Filter with no values|
|-------|------|
| CleanShot 2024-09-11 at 15 34 42@2x| CleanShot 2024-09-11 at 15 34 30@2x |

**Comment by matt-west** [comment]
@WBerredo Can you please override the highlight color to use WP Blue 50 (`#3858E9`). We’re trying to eliminate use of the old pink.

**Review by epeicher — APPROVED** [review]
I have tested the latest changes, and they work as advertised. LGTM!

|All recommendations | One metric|
|-------|------|
| CleanShot 2024-09-11 at 18 25 54@2x| CleanShot 2024-09-11 at 18 39 49@2x |

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/16701939

Some locales (Hebrew, Japanese) have been temporarily machine-translated due to translator availability. All other translations are usually ready within a few days. Untranslated and machine-translated strings will be sent for translation next Monday and are expected to be completed by the following Friday.

Thank you @WBerredo for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/16701939).

**Pull request merged**
