### PR TITLE
client: autoformat all files with calypso-prettier

### PR DESCRIPTION
**Pull request by samouri**
Inspired by: https://github.com/Automattic/wp-calypso/pull/14801, argued for in https://github.com/Automattic/wp-calypso/issues/12260#issuecomment-332293613

>Uses our custom build of prettier to auto-format existing files in the `client` directory.

> If we are going to use `prettier` then I vote we _use_ `prettier`. This takes all of the incidental formatting changes out of future PRs dealing with code in `client`. If we have concern for git history then we simply need to use the button in Github to go back to the previous revision - no problem. It's there anyway in any git history.

Generated by running
```
./node_modules/.bin/prettier --write client/**/*.js
./node_modules/.bin/prettier --write client/**/*.jsx
```

### CODE REVIEW

**Comment by hoverduck** [comment]
I ran the e2e tests against the branch and didn't come across any problems.

**Comment by sirreal** [comment]
🎉

**Comment by aduth** [comment]
Our selectors DevDocs parsing is pretty naive, and changes here to include `@format` in the "External dependencies" block is now causing it to be considered as the documentation for a selector.

https://github.com/Automattic/wp-calypso/blob/master/client/state/selectors/get-site-url.js
https://wpcalypso.wordpress.com/devdocs/selectors

We could improve selector file parsing (as previously attempted in #10487), but begs the question if we really want the `@format` annotation to be merged into our dependencies DocBlocks.

**Comment by samouri** [comment]
> We could improve selector file parsing (as previously attempted in #10487)
> but begs the question if we really want the format annotation to be merged into our dependencies DocBlocks.

I don't think the two items are mutually exclusive.  As to the latter, I've written a codemod that can split up the format docblock and the dependencies docblock.  Right now the functionality is part of [sort-imports](https://github.com/Automattic/wp-calypso/blob/master/bin/codemods/src/sort-imports.js) but if we want we can isolate the feature

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/2900697

Hi @samouri, could you please edit the description of this PR and add a screenshot for our translators? Ideally it'd include all of the following strings:
- `Front Page, Archive Pages, and Search Results`
- `Action required: Please contact your domain registrar to point {{strong}}%(domainName)s's{{/strong}} name server records to WordPress.com.`
- `Sharing posts to your Facebook page.`
- `We normally reply within 24-48 hours but are experiencing longer delays right now. We appreciate your patience and will respond as soon as we can.`
- `Footer credit`
- `Change your site's appearance in a few clicks, with an expanded selection of fonts and colors.`

Thank you in advance!

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/2900697).

**Pull request merged**
