### PR TITLE
Framework/CPT: Track current page title in Redux state

### PR DESCRIPTION
**Pull request by aduth**
This pull request seeks to implement new state behaviors and bindings for tracking the current page title in the global application state. Specifically, it includes a new action and reducer pair, a `<QueryTitle />` query component for assigning title, and bindings necessary to interoperate with the existing Flux-based [`screen-title` store](https://github.com/Automattic/wp-calypso/tree/master/client/lib/screen-title).

__Background:__

Custom post type labels can be localized. The localized label should be used in the `<title>` element of the page. The labels are accessed on the post types tracked in global application state. Rather than subscribe to state from the controller, it seems more reasonable to adopt our newer [query component pattern](https://github.com/Automattic/wp-calypso/blob/master/docs/our-approach-to-data.md#query-components) in assigning title to state via a rendered component at the top of the section render hierarchy.

__Implementation notes:__

Since many sections continue to rely on the `screen-title` Flux store, the title tracked in state may become inaccurate as the user navigates through the application, even with these changes. For example, after navigating from Types listing to stats, `state.ui.title` will continue to be assigned as "Custom Post Type". This issue will be alleviated if more sections adopt the Redux state approach introduced here.

__Testing instructions:__

Ensure that the title is updated correctly when navigating to the Custom Post Types route for a site. You must navigate to the URL directly in your development environment, as there are no navigable links yet available.

1. Navigate to [Calypso custom post types listing](http://calypso.localhost:3000/types/jetpack-portfolio) (e.g. portfolio)
2. Select a site
3. Note that the tab title reflects both "Custom Post Types" and the title of the selected site
4. Click Switch Sites in the sidebar navigation
5. Select a site
6. Note that the tab title reflects both "Custom Post Types" and the title of the selected site
7. Navigate to another page in Calypso
8. Note that the tab title reflects the section you chose

### CODE REVIEW

**Comment by mcsf** [comment]
At this moment I don't have the means to do a proper review and QA, but this is looking good!

I think I understand the reason (consistency with `QueryPosts`?), but isn't `QueryTitle` a confusing name? Also, any thoughts on extending this to metadata important for SEO (`meta`, `description`), as is currently done via Helmet in Themes?

**Comment by aduth** [comment]
>I think I understand the reason (consistency with `QueryPosts`?), but isn't `QueryTitle` a confusing name?

Yeah, consistency was the key motivation for the naming, since the idea would be that any component which exists specifically for what we describe as being a "query" component should be named as such. (cc @mtias)

>Also, any thoughts on extending this to metadata important for SEO (`meta`, `description`), as is currently done via Helmet in Themes?

I could see this being reasonable, sure. Since an update to state still requires a backing implementation to put that effect on the page, I could imagine an alternative server-side implementation for writing the `<title>` and `<meta>` attributes to the page. At this point, not sure whether it's premature for us to consider the effect this would have on how we structure the Redux state or name the query component which manages the behavior.

/cc @joseph-work

**Comment by mtias** [comment]
I think this one is a clear exception since it doesn't query anything, it just sets information. `SetDocumentTitle`?

**Comment by aduth** [comment]
>I think this one is a clear exception

"Clear" might be a stretch :grinning: But yes, it feels a bit awkward, and I think your naming is better.

Upon more thought, I do like the idea of using our Redux state in place of `<Helmet />` on the server-side, for consistency with our title manipulation needs in the browser. As such, might make sense to make both the component and state a bit more generic. How about `<SetDocument title="Home" meta={ /* ... */ } />` for the component and `state.document.title`, `state.document.meta`, etc. for state?

**Comment by mtias** [comment]
That looks good to me :)

**Comment by joseph-work** [comment]
Having all head title, seo-meta related stuff in one `document` object makes in my opinion more sense than having it scattered in different sections. Currently having only a `screen-title` for setting the title seems useless in that context.

I'm definitely for putting it all in one state and just getting it from there.

**Comment by aduth** [comment]
Closing in favor of #4090 and #4396.

**Pull request closed without merging**
