### PR TITLE
WIP: Update project status and task blocks

### PR DESCRIPTION
**Pull request by dmsnell**
Fixing some things
Adjusting for more semantic HTML
Providing fallback in the absence of view-side styles

## Things
 - round percentages, 5.33333333% is more accurate than any project status measurement and it looks ugly
 - change block content attribute to `string` instead of `array` to fix issue when splitting blocks. previously it was turning the raw HTML from the RichText into an entity-encoded string representing the text form of the HTML, exposing the tags and losing the formatting
 - create a save function for project-status that prints basic information from the edit-time updates
 - standardize three Emoji for new/pending/done: ⭕️/🔄/✅. I chose these to be quickly identifiable at a glance as well as carry some notion of completion. previously we had a mix of an SVG and other styles
 - stop using `checked` as it was a byproduct of `status` and led to incorrect display for pending states.
 - you can now click from "done" to "new." previously you could only toggle between "pending" and "done"
 - report how many tasks are in-progress rather than how many tasks are not completed. previously we showed (total tasks / # completed / # not completed) which was redundant

## Page render before

[nothing]

## Page render after

Screen Shot 2020-04-07 at 3 10 11 AM

## Editor before
Screen Shot 2020-04-07 at 3 12 03 AM

## Editor after
Screen Shot 2020-04-07 at 3 10 53 AM

### Editor
Screen Shot 2020-04-07 at 3 18 46 AM

### Rendered page
Screen Shot 2020-04-07 at 3 20 54 AM

### Editor
Screen Shot 2020-04-07 at 3 23 25 AM

### Rendered page
Screen Shot 2020-04-07 at 3 23 33 AM

### CODE REVIEW

**Comment by mtias** [comment]
The `save` is great, but let's keep `edit` as it was :)

**Comment by dmsnell** [comment]
> let's keep edit as it was :)

Any reason why? The `edit` function was buggy and didn't correspond to what the blocks were supposed to do. Can you list out what you don't want to keep? (there are two blocks in here as well, there's the Task block and also the Project Status block)

**Comment by mtias** [comment]
Sure!

- No emojis in `edit`.
- The custom checkbox.
- The "in progress" instead of an emoji.

**Comment by dmsnell** [comment]
> Sure!
> 
> * No emojis in `edit`.
> * The custom checkbox.
> * The "in progress" instead of an emoji.

Thanks for the feedback. I'll try and make the changes when I come back though if you are interested in the feedback I changed to the Emoji because the labels were just too hard to glance at and perceive.

There's no way to remove the "custom checkbox" though because what existed before was stranger still and surely not what we want in there. It was a tri-state component in the editor but a two-state component on page render.

In the editor it's a styled button that may have an SVG overlay on it for "done" or may have button text for "in progress."

On the page render it's Emoji.

---

Would you find it okay to replace all the glyphs with colored labels? I think that would be closer to the usability of the tri-state Emoji I found. Important to me at least when using these kinds of task lists is being able to see visually lined-up things of the same width but with different color and ideally different shapes.

At least if we replaced all the custom checkbox with a straight-forward label it would still be efficient to communicate.

**Comment by dmsnell** [comment]
Replaced by #44186

**Review by wp-desktop — CHANGES_REQUESTED** [review]
WordPress Desktop CI Failure for job "wp-desktop-mac".

@dmsnell please inspect this job's build steps for breaking changes at [this link](https://circleci.com/gh/Automattic/wp-calypso/906706). For temporal failures, you may try to "Rerun Workflow from Failed".

Please also ensure this branch is rebased off latest Calypso.

**Comment by dmsnell** [comment]
@wp-desktop you failed to understand that I closed this PR and deleted the branch. keep trying.

**Pull request closed without merging**
