### PR TITLE
Add viewport and viewport-react packages.

### PR DESCRIPTION
**Pull request by sgomes**
They contain the functionality extracted from `lib/viewport`, which is also removed as part of this change.

Note that the linter will complain about some files. These complaints have to do with existing issues there, as the files had the import statements updated with no further changes.

#### Changes proposed in this Pull Request

* Add `@automattic/viewport` and `@automattic/viewport-react` to the monorepo, extracted from `lib/viewport`.
* Remove `lib/viewport`.
* Update everything to use the new packages.
* Minor lint fixes to existing tests in library.

#### Testing instructions

Ensure that existing viewport functionality continues to work. This is widely used across Calypso, so any breakage should be fairly obvious.

### CODE REVIEW

**Review by jeherve — APPROVED** [review]
This looks good to me. 👍

**Comment by sgomes** [comment]
Thank you for the review, @jeherve! 👍

**Review by tyxla — COMMENTED** [review]
Thanks @sgomes 🙌This is looking great!

A bit late to the party, but I was wondering if those errors that packages have to be added as dependencies were false alerts?

**Comment by sgomes** [comment]
> A bit late to the party, but I was wondering if those errors that packages have to be added as dependencies were false alerts?

The errors only apply to the tests. This means that ordinarily I'd add them as `devDependencies`, but since I've been told that `devDependencies` in packages are problematic in our monorepo setup, I decided to leave them out. Happy to add them in if you think that's best.

**Comment by tyxla** [comment]
No need to change that, this confirms my expectations. Thanks 👍

**Pull request merged**
