### PR TITLE
Importer: Enable importing Medium export files

### PR DESCRIPTION
**Pull request by dmsnell**
- Renames Medium import type to match expected value in API
 - Removes Medium type from disabled list
 - Gives preliminary descriptive text for upload

**Still Needs**

 - [ ] Medium icon (Gridicon for Medium?)
 - [ ] Descriptive text

### CODE REVIEW

**Comment by dmsnell** [comment]
@drw158 I'm not sure what to do about the Gridicons right now. We switched over to using them, which is great, but unlike the older noticons, there is no icon for Medium or Ghost or Squarespace. Should we extend the Gridicons and add these in?

**Comment by drw158** [comment]
We have a new icon set for logos: https://github.com/Automattic/social-logos

You can find the component in the Calypso UI docs. A Medium icon just got added; there is no Ghost icon. There is also a WordPress icon, so we should use the one from Social Logos. Also, we should use the Social Logos icon set for all of these logos as we add them to the Importer. Thanks Dennis!

**Comment by drw158** [comment]
I think the descriptive text you have in there right now is great.

**Comment by dmsnell** [comment]
Abandoning branch because we do not have the resources at the moment to make the Medium importer work well on the server-side.

**Pull request closed without merging**
