### PR TITLE
Untangling: Apply new card design in Settings -> Site

### PR DESCRIPTION
**Pull request by fushar**
Related to:

- p9Jlb4-eSF-p2#comment-14121
- pfsHM7-1qC-p2#comment-1846

## Proposed Changes

This PR applies the new card design in Settings -> Site. Additionally, it merges back the Agency setting to the former.

It's not possible to do it without a refactor, so here it goes... 🥹 

## Why are these changes being made?

pbxlJb-6ye-p2

## Testing Instructions

> [!TIP]
> Please follow the testing instructions EXACTLY.

### Regular site

1. Create a new Free site.
2. Verify you see the following `Launch site` setting:

|/sites/settings/site/:slug|/settings/general/:slug|
|-|-|
|image|image|

3. Verify that you can launch the site via `/sites/settings/site/:slug`.
4. Now create another site, and verify that you can still launch it via `/settings/general/:slug`.
    - This time, launch it and pick a BUSINESS plan.
6. After it is launched, verify you see the following `Privacy` settings:

|/sites/settings/site/:slug|/settings/general/:slug|
|-|-|
|image|image|

7. Play around with the above settings in both pages; verify the settings can be updated.
8. Verify you see the following `Accept gift` setting:

|/sites/settings/site/:slug|/settings/general/:slug|
|-|-|
|image|image|

9. Play around with the above settings in both pages; verify the settings can be updated.

10. Go back to your FREE site.
11. Change the theme to a Classic theme (e.g.: Twenty Thirteen).
12. Verify you see the following `Footer credit` setting:

|/sites/settings/site/:slug|/settings/general/:slug|
|-|-|
|image|image|

13. Play around with the above settings in both pages; verify the links work.

### 100-year plan site

14. Go to your user's Store Admin.
15. In the `Add subscription:` block, add a `WordPress.com 100-year plan` to any of your site.
16. Verify you see the following `Control your legacy` setting:

|/sites/settings/site/:slug|/settings/general/:slug|
|-|-|
|image|image|

17. Play around with the above settings in both pages; verify the settings can be updated.

### A4A site

18. Create a new A4A site by following p1731423589870299/1731418263.670169-slack-C0347E545HR.
19. Verify you see the following settings:

|/sites/settings/site/:slug|/settings/general/:slug|
|-|-|
|image|image

20. Verify the `Refer to client` links work, and you can launch the site.
21. After the site is launched, verify you see the following Agency settings:

|/sites/settings/site/:slug|/settings/general/:slug|
|-|-|
|image|image|

22. Verify the settings can be updated.

### Jetpack site

23. Create a new Jurassic Ninja site.
24. Connect to your WordPress.com account.
25. Verify you see the following settings:

|/sites/settings/site/:slug|/settings/general/:slug|
|-|-|
|image|image|

(Note that it's expected that you can't enable the toolbar setting)

### REGRESSION TEST

1. In `/settings/general/:slug`, verify you can still update the site name etc, and admin interface style.

## Pre-merge Checklist

- [x] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [x] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [x] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [x] Have you checked for TypeScript, React or other console errors?
- [x] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [x] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [x] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Comment by fushar** [comment]
It seems for Jetpack sites, we need to type direct link to `/sites/settings/site/:slug` in the browser, because when we click on a row, we get redirected to the dashboard immediately 🤔 will create a follow-up issue for this.

**Comment by taipeicoder** [comment]
@fushar not related to this PR, but I noticed that the Footer card sometimes it shows up and disappears. 

https://github.com/user-attachments/assets/a91e7b04-3f75-45f6-af7b-4f1cdb2fc45d

**Comment by fushar** [comment]
> @fushar not related to this PR, but I noticed that the Footer card sometimes it shows up and disappears.

@taipeicoder Nice catch! Well, it's somewhat related to this PR, because technically this PR is the one that enables switching between sites while rendering the Footer Credit 😆 

Fixed it by not showing the Footer Credit until it has finished fetching the current active theme of the site.

**Review by taipeicoder — APPROVED** [review]
LGTM 👍

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/17008332

Some locales (Hebrew, Japanese) have been temporarily machine-translated due to translator availability. All other translations are usually ready within a few days. Untranslated and machine-translated strings will be sent for translation next Monday and are expected to be completed by the following Friday.

Thank you @fushar for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/17008332).

**Pull request merged**
