### PR TITLE
Add/prevent blocked users to blaze

### PR DESCRIPTION
**Pull request by ernestoSk13**
Related to #

This PR adds a functionality to the blaze dashboard so that if a user that has a blocked payment tries to promote, the UI will not let them continue.

Screenshot 2024-03-05 at 17 40 39
Screenshot 2024-03-11 at 13 19 19

NOTE: This PR depends on the revision sent for WPCom where we are checking if the user has a blocked purchase status or not.

## Testing Instructions
[Demo of how to test blocked purchase user](https://www.loom.com/share/51105feb65514995aab60a4ab6a7131f)

- [ ] Additionally go to Campaigns, click on the details button of any past campaign and you should see the 'Promote Again' button disabled.

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Comment by therocket-gr** [comment]
there are some issues with the styles/placement of the notice

attaching some ss below

Screenshot 2024-03-08 at 11 11 27

Screenshot 2024-03-08 at 11 11 44

it seems to be ending at the right side of the page
there is a left-margin set (which is not right) the container should get max-width and inherit the width we set in the content (check the styles of the promote-post-i2__search-bar-wrapper container) 

i would also think it would be better to have a display: flex in the notice__content container so that the text aligns vertically to the icon (this is a minor fix, not blocking)

before
Screenshot 2024-03-08 at 11 12 32

after
Screenshot 2024-03-08 at 11 12 28

**Comment by ernestoSk13** [comment]
hi @therocket-gr  I've fixed the UI for this :) it should be centered and with a better width

**Comment by ernestoSk13** [comment]
I have fixed the UI with the Notice @therocket-gr  :) it should look better in different screen widths

**Review by sbarbosa — COMMENTED** [review]
The code looks good. We need to apply the same disable logic to the Promote again button that is located in the details page.

Screenshot 2024-03-08 at 15 38 39

**Review by sbarbosa — APPROVED** [review]
LGTM 👍

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/11592909

Some locales (Hebrew, Japanese) have been temporarily machine-translated due to translator availability. All other translations are usually ready within a few days. Untranslated and machine-translated strings will be sent for translation next Monday and are expected to be completed by the following Friday.

Thank you @ernestoSk13 for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/11592909).

**Pull request merged**
