### PR TITLE
Purchases: Make Jetpack Search Free removable

### PR DESCRIPTION
**Pull request by jsnmoon**
#### Proposed Changes

- Codifies the new free tier of Jetpack Search into the Calypso codebase ("Jetpack Search Free").
- Enable removing Jetpack Search Free from the purchase management page.

See:
- p1664891351913239-slack-C0117V2PCAE
- pcNPJE-145-p2#comment-1770.

#### Testing Instructions

Testing this feature requires purchasing a Jetpack Search Free subscription for a site. Here's how you can spin up a test Jetpack site and purchase a subscription:

* Use [this link to spin up a Jurassic Ninja **without the Jetpack plugin** but **with the Jetpack Beta plugin**](https://href.li/?https://jurassic.ninja/create/?nojetpack&jetpack-beta).
* Navigate to the Jetpack Beta tab on your JN site and enable the Jetpack Search plugin at "bleeding edge".
* Navigate to the Jetpack Search dashboard on your JN site: `/wp-admin/admin.php?page=jetpack-search&new_pricing_202208=1`. Note the special query string value used to enable the new free tier experience.
* Click on "Start for free" and complete the connection & checkout process. Once this is complete, you should be redirected to the Search dashboard.

Testing changes from this PR:
* Navigate to your test site's `/purchases/subscriptions/` on Calypso.
* Select the Jetpack Search Free subscription.
* Ensure that a "Remove subscription" button appears at the bottom of the page.
* Ensure that the said button works as expected.

image

#### Pre-merge Checklist

- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [x] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [x] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?

### CODE REVIEW

**Comment by jsnmoon** [comment]
This is failing unit tests due to type enforcement on the `calypso-products` package. I'm working on rectifying the issue but would like input on whether my overall approach is correct.

(I'd also welcome any guidance on how best to address the type enforcement check!)

**Comment by sirbrillig** [comment]
Yeah, that one is hard to read. For the record, the type error is 

```
packages/calypso-products/src/products-list.ts:68:14 - error TS2741: Property 'jetpack_search_free' is missing in type '{ jetpack_backup_daily: { product_name: React.ReactChild; product_slug: "jetpack_backup_daily"; type: "jetpack_backup_daily"; term: "TERM_ANNUALLY"; bill_period: 365; categories: "jetpack_security_category"[]; getFeatures: () => string[]; getProductId: () => number; getStoreSlug: () => "jetpack_backup_daily"; }; ......' but required in type 'Record<"jetpack_boost_yearly" | "jetpack_boost_monthly" | "jetpack_backup_t1_yearly" | "jetpack_backup_t1_monthly" | "jetpack_backup_t2_yearly" | "jetpack_backup_t2_monthly" | ... 16 more ... | "jetpack_backup_realtime_monthly", Product>'.

68 export const JETPACK_SITE_PRODUCTS_WITH_FEATURES: Record<

```

The error is happening because `JETPACK_SITE_PRODUCTS_WITH_FEATURES` claims to have a record for every Jetpack product. You've just added a new Jetpack product, but you did not add an entry to `JETPACK_SITE_PRODUCTS_WITH_FEATURES`, which goes against what the types say.

I don't fully know all that `JETPACK_SITE_PRODUCTS_WITH_FEATURES` does, but it has a lot of important fields like `bill_period`, `getFeatures`, and `getProductId`. Could you add an entry for `PRODUCT_JETPACK_SEARCH_FREE` there?

**Review by mattgawarecki — APPROVED** [review]
I briefly looked through the code changes and tested the Jetpack Cloud experience via Calypso Live. Everything looked and worked reasonably for me. I'm happy shipping this as soon as tests are passing, but I want to point out a little rough edge we can fix in a separate PR. As shown in these image, the cancellation/retention dialog has some awkward text flow and mentions "0 days remaining"/"Plan was too expensive," which don't really make a whole lot of sense:

image

image

**Comment by JessBoctor** [comment]
I did a functional review of this, and it worked for me: 

GH68860-Review-JetpackSearchFree

Something to think about with the introduction of tiered pricing options; the `Renews On: Never expires` language doesn't really apply here. It may be confusing to customers when we ask them to upgrade a subscription that never expires. It may help to address the fact that their subscription is only free `Up to 10,000 records and 50 visitors per month` somewhere on this page.

**Review by kangzj — APPROVED** [review]
It works as described. Thanks for fixing this! 👍

**Pull request merged**
