### PR TITLE
Site Settings: Display global error/success notices when deleting a site

### LINKED ISSUE #158: Settings: delete-site-notices are not getting displayed
There should be feedback that is displayed to the user when they delete a site and are redirected to the all-sites stats page. That stopped working a while ago because the component listening for these actions is no longer contained in the page due to some other changes. This should probably get reworked in general.

### PR DESCRIPTION
**Pull request by drewblaisdell**
Fixes #158 by showing the following notice when users try to delete a site with active purchases.

screen shot 2016-02-05 at 11 25 17

Pinging @mikeshelton1503 for a design review.

**Testing**
- Visit `/settings/delete-site/:site` for a site with active subscriptions.
- Attempt to delete the site.
- Assert that you see the error notice above.
- Visit `/settings/delete-site/:site` for a site without active subscriptions.
- Attempt to delete the site.
- Assert that you see a success message when the site is deleted.

- [x] Product review
- [x] Code review

### CODE REVIEW

**Comment by rickybanister** [comment]
It was never really intended to have the dismiss button to the right of the notice-action. 

Can't this be an inline notice, or a modal dialog?

**Comment by mikeshelton1503** [comment]
I am planning to spend time next week on fixing "long notices" and situations like this. However I'll go ahead and post thoughts here so we can get this done today.

I agree with Rick that dismiss button doesn't work well on the right. How about making the dismiss action a text link instead and shortening the copy:

image

**Comment by rickybanister** [comment]
I might be confused still, but I don't think you need a 'dismiss' link at all since you can't proceed with deletion without first removing your upgrades. 

Will this notice follow you around everywhere or only be displayed on the delete page? If it is only displayed when viewing the deletion options I think it's fine to remove the dismiss link as navigating away from there implies you got cold feet and are cancelling your deletion.

**Comment by danhauk** [comment]
I think the inline "Dismiss" link works better than the gridicon on the right side of the notification. However, my first thoughts tend to agree with @rickybanister that we should think about whether the dismiss link is really necessary in this case. 

The use case for this notice is pretty limited and I would personally rather see it simplified with just one action.

But +100 to shorter copy.

**Comment by scruffian** [comment]
@mikeshelton1503 - how's this?

screen shot 2016-02-05 at 17 12 52

**Comment by mikeshelton1503** [comment]
Ok chatting with @rickybanister and @scruffian I understand this case a little better now and have a revised proposal :)

So users with active Purchases will only reach the Delete page if the click "Delete Site" from wp-admin (we are redirecting to Calypso to fix a separate issue), so we're talking about a smaller percentage of users. Otherwise, within Calypso a user will still be shown the modal window on the Settings page when they click "Delete Site" there.

So for this case, let's instead disable the "Delete Site" button and show the notice inline. There's no need in showing an action the user can't actually perform. We should go ahead and inform of what needs to happen in order to delete via an inline notice.

@scruffian pointed out to me that even with that solution in case of error and we mistakenly show the "Delete Site" button we should still show this notice. So :+1: to [this](https://github.com/Automattic/wp-calypso/pull/3076#issuecomment-180447103). We can open a separate PR to handle the inline notice and button disabling.

**Comment by scruffian** [comment]
Code looks good :+1:

**Comment by scruffian** [comment]
>  let's instead disable the "Delete Site" button and show the notice inline. There's no need in showing an action the user can't actually perform. We should go ahead and inform of what needs to happen in order to delete via an inline notice.

I created a new issue for this : #3117.

**Comment by rralian** [comment]
@drewblaisdell @scruffian I don't think this addresses #158, or at least not terribly well. That issue was about showing the success message after deleting a site. Because deleting a site necessarily redirects you to a page other than the settings page of your deleted site, it would be best to show the success message on that redirected page. You are currently showing the success message on the settings page for a split-second before redirecting to stats, which isn't really long enough for people to read it or feel assured of their action.

**Comment by rickybanister** [comment]
If a user deletes their only site where are they directed?

**Comment by adambbecker** [comment]
@rickybanister: Yeah I was thinking about that as well. I think we could do something like this:

delete_start-over

Obviously those bottom cards could be expanded upon, but for now probably just the top card could do the trick. What do you think?

**Comment by mikeshelton1503** [comment]
>  I don't think this addresses #158, or at least not terribly well. 

I agree with @rralian that this didn't address #158 Sorry I should have noticed this. It fixed an issue just not that one.

> If a user deletes their only site where are they directed?

I tested this and was shown this:

image

However I'll note that after I clicked Delete I saw a success notice that said my site was being deleted and the Delete Site button was disabled but after waiting a few minutes I never got redirected anywhere. Only when I refreshed the page did I see the above screen.

I like @adambbecker's suggestion for what to show there if no site's exist on the account after deletion. I create a new issue for that since it's a separate issue: #3126

**Comment by rickybanister** [comment]
Yeah, @adambbecker that would be pretty great. I think the two cards (create a site and follow people) could probably be the same size if you do the same sort of treatment to each for the illustration. But that's a nice idea. 

We could use a url like /start/fresh or something. I think nux uses '/start' right?

**Pull request merged**
