### PR TITLE
Add WP Admin link to plugin detail

### LINKED ISSUE #12141: Plugins: Add wp-admin link for plugins that don't have any action links
https://github.com/Automattic/wp-calypso/pull/11718 has been helpful for getting users to the plugin settings in wp-admin for plugins that provide action links. Many plugins don't use action links, however and may do something else like add a menu item to the sidebar. For these plugins that have no action links, let's inject an action link that will take them to wp-admin for the site.

Concept (cc @drw158 was this what you were thinking?):
screen shot 2017-03-14 at 2 54 36 pm

### PR DESCRIPTION
**Pull request by roundhill**
Adds a default `WP Admin` link button to a plugin if it didn't provide any action links.

Fixes #12141 

screen shot 2017-03-15 at 9 39 40 am

### CODE REVIEW

**Comment by rralian** [comment]
@roundhill Can you tell me an example of a plugin that has an actionLink set? I'm only seeing plugins with this wp-admin link, and I want to compare the difference.

One issue, we're showing this wp-admin link on the plugins details page for all plugins whether they've been installed or not. We should only show this on installed plugins.

**Comment by roundhill** [comment]
> One issue, we're showing this wp-admin link on the plugins details page for all plugins whether they've been installed or not. We should only show this on installed plugins.

Yeah, good catch. I will change it to only show when the plugin is installed and activated to match the behavior of the action links.

**Comment by roundhill** [comment]
> I will change it to only show when the plugin is installed and activated to match the behavior of the action links.

Done in 4e696c0

**Comment by rralian** [comment]
Confirmed and looks good to me! :shipit:

**Pull request merged**
