### PR TITLE
Checkout: Remove sidebar AB test code

### PR DESCRIPTION
**Pull request by jjchrisdiehl**
Now that the "Included with your Purchase" and "Upsell Nudge" a/b tests have completed, this PR removes their associated explat code.

Related to #84891 and #84890 

## Proposed Changes

* This PR will remove the experiment hook files along with the calling code throughout checkout

## Testing Instructions

* Add products to your cart and go to Checkout - including a one year plan
* Ensure that the 'Included with your purchase' featured list and the Two Year Plan upsell nudge both appear in the checkout sidebar
* This should work regardless of which a/b group you have been assigned in the past, since the explat code would be removed and no longer care for these group assignments

### CODE REVIEW

**Review by sirbrillig — COMMENTED** [review]
I think you might not have gotten all the places that use these hooks. I see a lot of build failures.

**Comment by jjchrisdiehl** [comment]
> I think you might not have gotten all the places that use these hooks. I see a lot of build failures.

You're right, it looks like a number of changes did not get added to the commit. Fixing this now 👍

**Comment by jjchrisdiehl** [comment]
Just waiting on tests to pass. Side note, should I really be removing the hook files altogether? I suppose what if we wanted to test this again at some point in the future?

**Comment by sirbrillig** [comment]
> should I really be removing the hook files altogether? I suppose what if we wanted to test this again at some point in the future?

Yes, I think so. If we want to get this back, the code is all in git. There's rarely any reason to keep around things that aren't in-use.

**Review by sirbrillig — APPROVED** [review]
Looks good! Thanks!

**Pull request merged**
