### PR TITLE
Reader: remove Cold Start - attempt 2

### PR DESCRIPTION
**Pull request by bluefuton**
Reverts Automattic/wp-calypso#10974.

An unforeseen side effect of the original PR was that feed-stream-store is now in multiple chunks.

@blowery says "since it’s a “singleton” we now have 5 copies of it"

This PR can be landed again once we have a resolution for that issue.

### CODE REVIEW

**Comment by bluefuton** [comment]
@blowery what adjustments do we need to make to prevent the same bundle problems happening next time around? 

I know that "move the store to Redux" is a solid answer but wondering if there are any other workarounds :)

**Comment by blowery** [comment]
There's no great solution unfortunately.

We could use `require.include` in the boot chunk, which would move the feed-post and feed-stream stores to the build chunk. The issue there is that only webpack supports `require.include`, node does not, so we're have to use something like the `asyncRequire` babel transform to wrap it. 

We could pull in the feed-post-store and feed-stream-store async, using asyncRequire. That would isolate them into their own chunk, but it'll make using them more complicated. 

We could bundle all of the Reader back into one chunk, instead of splitting it up. We might then be able to load various components async, but we'd have to pull in feed-post-store and feed-stream-store in the main controller or index and pass them in as props to Stream. Right now Stream pulls feed-post-store directly, so asyncRequire will duplicate it.

We could alter the build system to teach it to build a common chunk per section group. That would likely require a deep understanding of the CommonsChunkPlugin or a new webpack plugin to do the work.

**Comment by samouri** [comment]
@blowery: what is the downside of having Reader be one chunk?

**Comment by blowery** [comment]
@samouri it just gets big. to see, change the `name` property on all the reader chunks in the section definition to `reader`.

**Comment by blowery** [comment]
@samouri we should actually do that and quantify what "big" means. I think I took a poke at it, and the only reason I didn't pull the trigger was asyncifying wemoji, which is giant.

**Comment by bluefuton** [comment]
As we're retaining some of the Cold Start functionality for #11282, I'll open a new PR which just removes the parts we no longer need.

**Pull request closed without merging**
