### PR TITLE
Happychat: Handle socket disconnection

### LINKED ISSUE #12183: Happychat: shows no indication there is a problem when the happychat connection goes down
#### Steps to reproduce
1. Starting at URL: http://calypso.localhost:3000/help/contact
2. Open a chat with happychat
3. Turn off network connection

#### What I expected

Feedback of some kind that something was wrong with my chat.

#### What happened instead

It appeared as though nothing was wrong until I tried to type a message and it just disappeared.

### PR DESCRIPTION
**Pull request by jordwest**
Closes #12183

This adds event handlers and reducers for handling the socket getting disconnected, to present a message to the user. Before this change, messages sent when disconnected were being sent nowhere with no information to users.

A disconnection notice was implemented in #11821, but the Redux store was not updated in response to disconnection so the notice wasn't shown.

 - [x] Handle disconnection event from socket.io
 - [x] Add reducer to change the status to `disconnected` in the Redux store
 - [x] Rewire the logic for deciding whether the Happychat window is shown. Currently, `isConnected` is used to determine whether to show the window. This is a problem because when the disconnection occurs, the window just disappears. We also need to make sure that the window and sidebar icon aren't shown before the first connection, however.
 - [x] Show timeline when disconnected

### How to test

1. Start up a local happychat service, point Calypso to it.
1. Start a chat
1. Kill the local happychat service.
1. The disconnected notice should appear in chat:
    screen shot 2017-03-24 at 12 59 21 pm
1. It will soon switch to:
    screen shot 2017-03-24 at 12 56 07 pm
1. Restart the local happychat service
1. The notice should disappear, and you can continue chatting as usual

### CODE REVIEW

**Comment by beaucollins** [comment]
Works as expected in testing.

Experience is much better than the existing one, however the existing messages in the timeline go away while disconnected which felt odd.

In my testing the Socket.IO connection did a good job of reconnecting when I bring the chat server back up.

**Comment by beaucollins** [comment]
It would be useful to add a state for the timeline that allows for showing the existing messages while also showing an indicator that the chat is not connected.

**Comment by jordwest** [comment]
I worked on keeping the timeline around today, but there's a lot of logic in there relying on the connection state that needs to be pulled out and replaced with something else. It might be worth doing that in a separate PR, as it's probably not as important as getting this one out.

**Comment by jordwest** [comment]
I've made the changes to keep the timeline around while disconnected, this is ready for another review.

**Comment by mattwondra** [comment]
Looks like this PR will have some conflicts with https://github.com/Automattic/wp-calypso/pull/12180 when it lands (both create similar constants for example). Since #12180 is close to shipping, I'll rebase this against `master` once it lands early next week.

**Comment by nosolosw** [comment]
Tested this by: 

- kill the HC server. I was connected to a full localhost env as operator (staging branch). The notices (steps 4 and 5 were shown as expected). Messages sent by the customer at this point weren't shown in the timeline. After bootint the HC server again, messages weren't sent through, but the connection between operator and customer was re-established and I could happychat again.

- turning off internet connection. I needed to do this by using staging as operator, otherwise SocketIO keeps the connection and the messages go through anyway. The disconnected notice didn't appear (step 4) but the reconnecting (step 5) did. The messages in the customer side weren't shown in the timeline. When turning on connection again, messages weren't sent through, but the connection between operator and customer was re-established and I could happychat again. Worth mentioning that the same connection was used for operator and customer, in case that adds some noise to the mix.

Not sure if this PR aimed to solve both client disconnection and server disconnection, so I'm marking this as "needs author reply".

**Comment by dllh** [comment]
@mattwondra can you take this one over?

**Comment by mattwondra** [comment]
Ok, so after some careful study here it looks like from an event-firing perspective, it looks exactly the same when the disconnect is caused by the HC server going down vs the user's network going down. A `disconnect` event is fired followed pretty much immediately by a `reconnecting` event (and then reconnect errors/retries until a connection is re-established).

The big difference is that when the server goes down this happens immediately. But when the user's network goes down, we need to wait for the next server `ping` event (every 25ish seconds) plus the `pingTimeout` (60ish seconds) for the `disconnect` event to fire. I might recommend that we bring these values down, because otherwise a user with network issues will be firing messages into the void for up to a minute and a half before being told anything's wrong. This change must happen on the Socket server, so it can't go into this PR.

I'm going to spend time tomorrow re-working some of the messaging and dispatched events here. Right now the `reconnecting` event makes the screen say "Connecting you with a Happiness Engineer..." and for both server issue and user network issue it should probably actually say something more like "Connection lost, attempting to reconnect...". When the reconnection is successful a `connect` event will fire and bring the "Connecting you..." message back.

**Comment by mattwondra** [comment]
I'm going to close this PR — it's been re-done in https://github.com/Automattic/wp-calypso/pull/12706 and https://github.com/Automattic/wp-calypso/pull/12754

**Pull request closed without merging**
