### PR TITLE
Nav Unification Announcement: Update Images

### LINKED ISSUE #49771: Nav Unification: Customer modal is using incorrect images
**What**
For the nav unification customer modal, we are using the incorrect images. Please find the correct ones here: [IMG.zip](https://github.com/Automattic/wp-calypso/files/5932960/IMG.zip)

**Acceptance criteria**
* Should the user visit Calypso and see the customer modal. They should see the images in the attached [IMG.zip](https://github.com/Automattic/wp-calypso/files/5932960/IMG.zip) file.

### PR DESCRIPTION
**Pull request by Aurorum**
#### Changes proposed in this Pull Request

* Updates the images on the Nav Unification Announcement 
* Migrates those images so they display the updated one beyond the Dev environment (see #36850) - this would also allow the images to be updated easily once more in the future should that be desired 
* Also wraps one of the lines in a translatable string (not sure if it was intentional to leave it though - let me know if I should reverse it!)

#### Testing instructions

Verify that the images on the modal are accurate on both mobile and desktop. 

| Desktop  | Mobile |
| ------------- | ------------- |
| Screenshot 2021-02-08 at 14 33 25 | Screenshot 2021-02-08 at 14 34 54 |
| Screenshot 2021-02-08 at 14 33 29 | Screenshot 2021-02-08 at 14 34 57 |
| Screenshot 2021-02-08 at 14 33 34 | Screenshot 2021-02-08 at 14 35 01  |

cc @tjcafferkey, @mmtr, @cpapazoglou 

Fixes #49771

### CODE REVIEW

**Review by tjcafferkey — CHANGES_REQUESTED** [review]
Firstly, thank you so much @Aurorum for picking this up it's super helpful. Not to mention the update to migrating images to Webpack change you've implemented, and compressing the images. Great work!

The only issue I can find here is on mobile (iPhone X dimensions), the first and last images don't sit flush with the bottom of the image container (See screenshots below)

I think if we added the below to [here](https://github.com/Automattic/wp-calypso/blob/trunk/client/blocks/nav-unification-modal/style.scss#L162-L195) then it would solve that issue. What do you think?

```scss
.nav-unification-modal__picture {
    &--bottom-right,
    &--center {
        img {
            @media ( max-width: $modal-breakpoint ) {
                position: absolute;
                bottom: 0;
            }
        }
    }
}
```

**Screenshots**
Screenshot 2021-02-09 at 10 09 08
Screenshot 2021-02-09 at 10 09 15

**Comment by Aurorum** [comment]
Thank you! I've made that change, although it's probably worth noting that pushes the image down a bit - I'm not sure if that'll be a problem.

| Before  | After |
| ------------- | ------------- |
| Screenshot 2021-02-09 at 10 52 59 | Screenshot 2021-02-09 at 10 52 53 |

**Comment by tjcafferkey** [comment]
Ah yes, good spot on that @Aurorum. Sorry, I think this will be the last amend but what do you think to the following change to those styles we just added:

```scss
img {
    @media ( max-width: 500px ) {
        // The top of the image should be visible on this breakpoint and below so we can remove the minus bottom.
        bottom: 0;
    }

    @media ( max-width: $modal-breakpoint ) {
        position: absolute;
        // This is to ensure the top of the image is visible between breakpoints $modal-breakpoint and 500px (above).
        bottom: -50px;
    }
}
```

**Comment by Aurorum** [comment]
That seems to trim the images a little early on smaller screens though, which I'm guessing isn't intentional? I've added a commit which I think (and hope!) balances things so that the images are always displayed properly - does that work okay? :)

**Review by tjcafferkey — APPROVED** [review]
@Aurorum amazing job, that works great. Thank you for your help with this it's hugely appreciated 🎉

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/5506928

Thank you @Aurorum for including a screenshot in the description! This is really helpful for our translators.

**Comment by stephanethomas** [comment]
@tjcafferkey, @Aurorum: it looks like those image files have wrong permissions:

```
-rwxrwxr-x 1 vagrant vagrant 13249 2021-02-10 17:10 unify-nav-desktop-1.jpg
-rwxrwxr-x 1 vagrant vagrant  8856 2021-02-10 17:10 unify-nav-desktop-2.jpg
-rwxrwxr-x 1 vagrant vagrant 19021 2021-02-10 17:10 unify-nav-desktop-3.jpg
-rwxrwxr-x 1 vagrant vagrant 13331 2021-02-10 17:10 unify-nav-mobile-1.jpg
-rwxrwxr-x 1 vagrant vagrant  9160 2021-02-10 17:10 unify-nav-mobile-2.jpg
-rwxrwxr-x 1 vagrant vagrant 16168 2021-02-10 17:10 unify-nav-mobile-3.jpg
````

Could you fix that when you get the chance? Thanks!

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/5506928).

**Pull request merged**
