### PR TITLE
Reader: Fix emoji support is missing

### PR DESCRIPTION
**Pull request by dongseok0**
Added smiley stylesheet.
https://github.com/Automattic/wp-calypso/issues/710

### CODE REVIEW

**Comment by shaunandrews** [comment]
Nice. This fixes emoji in Reader, but not in the `/posts/` screen:

screen shot 2015-12-18 at 4 07 28 pm

**Comment by dongseok0** [comment]
Yeah, they are just plain text in Posts screen not like Reader. Maybe need to make another issue for Posts?

**Comment by lancewillett** [comment]
I think it's fine to get this in for just Reader, and make a different issue for Posts.

**Comment by shaunandrews** [comment]
> I think it's fine to get this in for just Reader, and make a different issue for Posts.

Agreed. :+1:

**Pull request merged**
