### PR TITLE
Zendesk Widget: Pass site ID to when submitting user fields

### PR DESCRIPTION
**Pull request by alshakero**
Fixes 8128-gh-Automattic/dotcom-forge

## Proposed Changes

Pass the site ID, when available, as part of `update-user-fields` request. This allows the `Plan_For_Support` class to fall back to the site when the user doesn't have any plans. 

## Why are these changes being made?
To allow paid site admins who don't own sites of their own to access priority support. 

## Testing Instructions

1. Create a free user and invite them to a paid site you own.
4. Refresh the page in the free user's window.
5. Start a chat session. 
6. The plan should be the site's plan. 

### Import everything flow
1. Go to /setup/import-focused/importerWordpress?siteSlug=YOUR_SITE&from=https%3A%2F%2Ffriendly-clam.jurassic.ninja%2F&option=everything&forceError=1
2. Click Contact support. 
3. Chat should open just fine.

### Domain only flow
1. Go to /setup/domain-transfer/intro.
2. Click "Need help? Contact us". Chat should start without issues.

### Precancelation chat
1. Cancel a paid plan
2. In "Share your feedback" screen, click the top right button, "Need help? Contact us". 
3. Chat should start alright.

### CODE REVIEW

**Comment by heavyweight** [comment]
Great work on this.
I can't seem to get around this error though:
```
    "body": {
        "code": "no_zendesk_user_id",
        "message": "No Zendesk user ID found.",
        "data": {
            "status": 404
        }
    },
```
I thought it was because of `+` in the email but tried with another one now and still same result.

**Comment by alshakero** [comment]
It happened to me once during development then disappeared :(

**Review by escapemanuele — COMMENTED** [review]
### Testing

`messaging_site_id` correctly passed. I did receive a `message: "No Zendesk user ID found."` though.

### Regression testing
- **Import everything flow** ✅  `messaging_site_id` correctly passed
- **Domain only flow** `messaging_site_id : null`
- **Precancelation chat** ✅  `messaging_site_id` correctly passed

**Review by escapemanuele — APPROVED** [review]
Since seeing the site id passed in the `update-user-fields` request is what we want, this PR succeeds in that! 👍

**Pull request merged**
