### PR TITLE
A4A: Sites dashboard multiscreen size compatibility

### PR DESCRIPTION
**Pull request by gogdzl**
Related to https://github.com/Automattic/automattic-for-agencies-dev/issues/115

## Proposed Changes

* This PR improves the compatibility with smaller resolutions as proposed in https://github.com/Automattic/automattic-for-agencies-dev/issues/115
* As a side effect, this PR also fixes some scrolling issues with all resolutions

## Testing Instructions

* **As a general guideline, ensure that everything appears visually appealing and provides a pleasant user experience.**

Small screens:
* Go to `http://agencies.localhost:3000/sites`
* Adjust your browser to use a mobile view (F12 -> Select a small resolution)
* In trunk you should see:
image

* In `update/a4a/115-sites-dashboard-multiscreen-size-compatibility` you should see :
image

* When visiting other pages, the page's top margin should be fixed (e.g.  `http://agencies.localhost:3000/overview`)
* Trunk:
image

* In `update/a4a/115-sites-dashboard-multiscreen-size-compatibility` you should see :
image

Action buttons:
* Trunk:
image

* In `update/a4a/115-sites-dashboard-multiscreen-size-compatibility` you should see :
image

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Comment by cleacos** [comment]
I've been testing this PR. **It works pretty well on mobile screens.** 👌 

**Issues I've found so far:**

- **The sites list buttons:**

image

vs the current one in staging:

image

- **The height size in screens below 960px:**

image

- Padding:

image

**Comment by cleacos** [comment]
It has a small conflict.

**Comment by cleacos** [comment]
image

- **Could we reduce the size to match the one we already have in staging and the Figma file?**

image

- **Figma:**

image

- **The scrolling issue** I highlighted is still there. On staging is working well.

**Note:** We can address the padding issue with the table view in small/medium screens in a follow-up GH issue. The issue is present on staging.

**Comment by gogdzl** [comment]
> Could we reduce the size to match the one we already have in staging and the Figma file?

This component is shared, I got it from the Overview page. I will try to change its style using CSS.

**Review by coder-karen — APPROVED** [review]
This looks beautiful!

My mobile view doesn't match the screenshots exactly but I suspect that's because bulk selection is not there anymore.

I've read through the relevant Slack channel and double checked Figma designs (i1 that I can access) and everything appears to match there too.

**Pull request merged**
