### PR TITLE
Hosting Overview Refinements: Drop `data-scroll-id` in favor of refs

### PR DESCRIPTION
**Pull request by fredrikekelund**
## Proposed Changes

Follow-up to #93223 and #93419.

This PR moves the logic for automatically scrolling to the WP / PHP version selectors from the topmost `Hosting` component down to `WebServerSettingsCard`. The benefit is that we don't need to rely on `setInterval` (an imprecise method), but we can use React refs.

## Testing Instructions

1. Navigate to `/sites?flags=hosting-overview-refinements`
2. Click on an Atomic site
3. Click on the WordPress version number in the header
4. Ensure that the page automatically scrolls down to the WP version picker after a second or two
5. Navigate back in your browser
6. Repeat the process for the PHP version picker

### CODE REVIEW

**Review by chad1008 — COMMENTED** [review]
Can you elaborate a little on the thought process behind `hasScrolledOnce`? In testing it successfully prevents the autoscroll behavior from triggering more than once, but I wondered why we were going that way, as it changes existing (albeit unlaunched) behavior a bit.

Currently, if you start on any of the Hosting Overview tabs and click a version number, you'll go to the Server Setting tab and after a brief pause smoothly scroll to the wp/php info. If you click on one of the version numbers again (either right away, or perhaps after scrolling a bit) you'll remain on Server Settings, and once again scroll to the selected data. If you leave Server Settings (let's say you visit the Monitoring tab) and click one of the version numbers, you are taken back to Server Settings and auto scrolled again. The auto scroll always works, basically.

With this PR applied, I get only one scroll. That means after my initial autoscroll to the wp/php version info, if I click on either version number again it jumps me to the top of the Server Settings tab. If I leave Server Settings and click a version number, I'll go back to the correct tab again, but no autoscroll. For me, this leaves me feeling like the links are breaking after their first use. I can see that it's intentional, but it doesn't feel that way, especially if I put myself in the shoes of a user.

For the fun/curiosity of it, I also tested without the early return if `hasScrolledOnce.current` is true, and that allows multiple auto scrolls if you leave Server Settings between each one:
- Start on Overview
- Click the WP version link
- Enjoy your auto scroll journey
- Click to Monitoring (or any other tab)
- Click a version number
- Autoscroll again
- Click a version number (without leaving the tab this time)
- You're jumped to the top of the page

**Comment by fredrikekelund** [comment]
Good catch, @chad1008! 👍 I've tweaked the approach and added a global `click` listener that also makes the scroll work on the `hosting-config` page. I tried using the `hashchange` event first but found I couldn't prevent the browser's native "scroll to anchor" functionality that way, which made the experience glitchier.

**Comment by nightnei** [comment]
@fredrikekelund Now we don't have any response when we click on WP/PHP version being on the "Server Settings" page already.
I intentionally implement the effect of scrolling before, after Angela's comment - p1723170990128299-slack-C06ELHR6L9J.
`Bug: When the “Server Settings” tab is active, clicking on the WP / PHP versions doesn’t do anything...`. So we need to return that behaviour or at least implement some UI response on clicks in this case.

**Comment by nightnei** [comment]
I see now - it works well when the height is small, but it's literally unreal case, since in 99.9% height of the screen is big. So we need to implement some UI response when the height is big, ATM we don't have any effect.
https://github.com/user-attachments/assets/96ccde13-9ed8-4cd8-b796-e83743cad1c8

**Comment by fredrikekelund** [comment]
The `scrollIntoView` behavior is the same with this PR as it was before, but I take your point, @nightnei, that it would be easier to notice the control if something happened when it's clicked. 

I took a stab at making the label and control/text flash in a different color when the link is clicked. Let me know what you think.

**Review by nightnei — APPROVED** [review]
The behaviour before was thsi one:
https://github.com/user-attachments/assets/5f8aee16-df43-43cf-b483-0a4d67dac270

But I like proposed option with highlighting, it's much better 👍
The code LGTM and works as expected 👍

**Pull request merged**
