### PR TITLE
Modularise oauth2 clients state

### LINKED ISSUE #42464: Modularise `oauth2Clients`
The `oauth2Clients` portion of the state tree needs to be modularised. See the [modularised state documentation](https://github.com/Automattic/wp-calypso/blob/master/docs/modularized-state.md) for more details.

### PR DESCRIPTION
**Pull request by sgomes**
This PR is one of many working on modularising state in Calypso. This one handles the OAuth2 clients state.

For more details on state modularisation, see the [modularised state documentation](https://github.com/Automattic/wp-calypso/blob/master/docs/modularized-state.md) and p4TIVU-9lM-p2.

Note: I added all the reviewers that GitHub suggested. Please feel free to ignore the review request or pull in someone else if you're not comfortable reviewing this PR. Thank you!

Fixes #42464.

#### Changes proposed in this Pull Request

* Modularise OAuth2 clients state.
* Move `ui/oauth2-clients` under `oauth2-clients` (as `oauth2-clients/ui`), since there's no point in keeping them separate.
* Rearrange the `oauth2Clients` state subtree a bit to accomplish this, updating all selectors accordingly.

#### Testing instructions

I'm not entirely sure what the best way of testing this is, other than deploying to staging and testing there 😕 Any ideas?

The unit tests should provide some measure of confidence, otherwise.

### CODE REVIEW

**Comment by sgomes** [comment]
Note: the linting errors are expected, since I'm modifying the root reducer, which uses linting errors to point out unmodularised state in an attempt to prevent more of it from being created.

**Comment by stephanethomas** [comment]
> I'm not entirely sure what the best way of testing this is, other than deploying to staging and testing there 😕 Any ideas?

The testing instructions from https://github.com/Automattic/wp-calypso/pull/35413 or https://github.com/Automattic/wp-calypso/pull/20502 should give you some hints regarding how to test those changes locally 🙂.

**Comment by sgomes** [comment]
Thank you, @stephanethomas! Logging into woocommerce following the instructions in #35413 appears to be working correctly in my testing 👍

**Comment by sgomes** [comment]
Rebased on base branch.

**Comment by sgomes** [comment]
Hey folks, any chance of a review here?

**Comment by saramarcondes** [comment]
Code changes LGTM.

> I'm not entirely sure what the best way of testing this is, other than deploying to staging and testing there 😕 Any ideas?

Also not sure about this but deploying to staging to test and going 🔴 seems fine if calypso.live isn't sufficient.

**Comment by saramarcondes** [comment]
RE linting errors @sgomes is there any chance we can just put `/* eslint-disable no-restricted-imports */` at the top of that module throwing so many errors at the moment?

**Comment by sgomes** [comment]
> RE linting errors @sgomes is there any chance we can just put `/* eslint-disable no-restricted-imports */` at the top of that module throwing so many errors at the moment?

The linting errors in this case are there intentionally, as a way of avoiding new unmodularised state being added to the root reducer.

The idea is that we consider unmodularised state to be deprecated, and we don't want any more of it being added. So, to ensure that doesn't happen, I added an eslint comment to the top of the root reducer (`state/reducer.js`) to actually **add** these errors, marking all existing usage (and any new usage) as errors.

These state modularisation PRs then go in and remove these errors one by one. However, `eslint` isn't smart enough to realise that we're removing an error while intentionally leaving others for later, so it complains about all the errors we left there.

This is the best mechanism I can think of for quickly and easily informing folks that new state should be modularised, and new unmodularised state should be avoided, but I'm happy to consider alternatives!

**Review by sarayourfriend — APPROVED** [review]
Sorry, meant to approve yesterday 🤠

**Comment by sgomes** [comment]
> Sorry, meant to approve yesterday 🤠

No worries, thank you, @saramarcondes! 🙂 I'll leave this one for tomorrow, as I start my day during a time when the queue is much less busy, and it seems more prudent to handle it then 😄

**Pull request merged**
