### PR TITLE
Reader: Update Back button to match Refresh mockup

### PR DESCRIPTION
**Pull request by jancavan**
The "Back" button should look like this in wider viewports:

screenshot 2016-11-22 16 28 58

### CODE REVIEW

**Comment by jancavan** [comment]
I've positioned the Back button relatively to achieve the same layout as the mockup. However, since the Back button and FeedHeader are two separate entities, it adds a ton of white space to Site Streams with a Back button. Example: http://calypso.dev:3000/read/feeds/23059853

But it looks perfectly fine in Site Streams without a Back button: http://calypso.dev:3000/discover

Any suggestions on how to go about this? /cc @blowery @bluefuton

**Comment by fraying** [comment]
Ah, yeah. Just to confirm, Site Streams with a Back button should have way less whitespace up there.

This is what I see now

screen shot 2016-11-22 at 4 58 08 pm

But should be more like:

screen shot 2016-11-22 at 4 59 45 pm

@jancavan Note also that the back link needs to scoot to the left by ~27px to align with the left side of the column.

**Comment by jancavan** [comment]
In https://github.com/Automattic/wp-calypso/pull/9594/commits/3edc3f40faae0283a95e97f12878c5b563df3e5b and ----:

Made alignment updates to the Site Stream with/without the Back button. 

However, I had to scope it to `.is-site-stream` for the Back button in the Tags Stream to not get affected by this change:

Can anyone help me get `.is-site-stream` to consistently show up?

**With Back button** (after discussing with @fraying, we decided to drop the Follower count from this particular view):

screenshot 2016-12-02 13 33 43

screenshot 2016-12-02 14 05 25

screenshot 2016-12-02 14 07 44

The border previously added to the first card in the Site Stream also gets omitted without the class `.is-site-stream`:

screenshot 2016-12-02 14 17 33

**Without Back button:**

screenshot 2016-12-02 14 11 30

screenshot 2016-12-02 14 12 30

screenshot 2016-12-02 14 16 46

**Comment by bluefuton** [comment]
Position looks good, but seems to be overlapping with the site link. For example, on http://calypso.localhost:3000/read/feeds/8901148, clicking the back button takes me to the RSS feed:

screen shot 2016-12-06 at 12 46 24

**Comment by jancavan** [comment]
@bluefuton The Follower count/button no longer overlap with `site__content`, however, it still overlaps with the Back button. It's because all these 3 elements are sitting on top of each other. Would it be possible to just move the Back button inside `reader-feed-header`?

**Comment by bluefuton** [comment]
@jancavan Good plan. I've moved the back button inside feed header (for Refresh only) in 6ebb76e.

**Comment by fraying** [comment]
Woo hoo! Nice work, Jan. LGTM

**Comment by jancavan** [comment]
Tested in pre-Refresh - Back button and Site Stream header are unaffected by these changes.

**Pull request merged**
