### PR TITLE
Reader: fix new full post header spacing issues

### LINKED ISSUE #7417: Fullpost: Main Column: Spacing Issues
When the sidebar is present, the top of the headline should line up with the top of the gravatar, and the top of the content should line up with the bottom of the gravatar. Or as close as we can get it, at least.

Design:
screen shot 2016-08-11 at 2 21 38 pm

Current site:
screen shot 2016-08-11 at 2 23 48 pm

So it looks like, on the current site, the post title needs to move up 5px, and the content needs to move up 28px.

### PR DESCRIPTION
**Pull request by bluefuton**
Fixes @fraying's spacing concerns from #7417 - see the original issue for details.

- [x] Line up top of title with top of gravatar
- [x] Line up top of content with bottom of gravatar where possible

Fixes #7417.

Test live: https://calypso.live/?branch=fix/reader/full-post-header-spacing-issues

### CODE REVIEW

**Comment by bluefuton** [comment]
@fraying I found that content already starts parallel with the bottom of the gravatar where possible (i.e. if main post title is one line only), but in the example you gave, a 24px margin was being applied to the first image shown in the post. I've added a rule to target the first image and scrap the top margin.

screen shot 2016-08-19 at 15 08 40

Hopefully that should do it!

**Comment by fraying** [comment]
Well done, sir!

**Comment by jancavan** [comment]
LGTM 🚢

**Comment by bluefuton** [comment]
Sorry @jancavan, just realised I didn't push the second commit. On it's way...

**Comment by bluefuton** [comment]
Margin removal for first image is in 3d5baf8.

A good one to test:

http://calypso.localhost:3000/read/blogs/69282927/posts/13725

**Comment by jancavan** [comment]
@bluefuton I don't think we need to nest this so I updated it in: https://github.com/Automattic/wp-calypso/pull/7549/commits/584d350dff166f6a1183ea0e628689bbac25ac09

Other than that, looks good to me :shipit:

**Pull request merged**
