### PR TITLE
SMP: refactor mshot hook to use response status instead of loading image dimensions

### PR DESCRIPTION
**Pull request by sejas**
#### Proposed Changes

* Define the mshot isLoading state by fetching the status and image headers instead of using the image resolutions.

Image resolutions was good enough until we added responsive images.

#### Testing Instructions

* Go to `/site`
* Filter by public sites
* Select grid to view the site thumbnails bigger with responsive size.
* Observe the thumbnails are loaded correctly
* Reduce the window size to try the responsive images
* Refresh the page
* Observe the thumbnails are loaded correctly
* Open a new tab, and create a new post on a simple site
* Go back to the previous tab `/sites`  and check the thumbnail is updated.

#### Pre-merge Checklist

- [x] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [x] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [x] Have you checked for TypeScript, React or other console errors?
- [x] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?

Related to #

### CODE REVIEW

**Comment by wojtekn** [comment]
I've tested different flows related to thumbnails, and it seems working fine now. 

To give more background on the issue, we can't use `naturalWidth` property to reliably check image size, thus we can't distinguish real thumbnails from the placeholder by checking the image size.

More details on the nature of the issue: https://discourse.wicg.io/t/getting-original-size-of-image-synchronously-naturalwidth-height-can-t-be-used-for-this-anymore/1782

And: p1663108720688009-slack-C0347E545HR

I observed the flickering issue, but it looks unrelated to changes from this branch, and we have it tracked under another ticket https://github.com/Automattic/wp-calypso/issues/67750.

**Review by vykes-mac — COMMENTED** [review]
This works well and I like this solution, There's a `apiFetch from '@wordpress/api-fetch';`, I see this is used alot of places in the codebase, I wonder if it make more sense to use it rather than the js `fetch` api?

**Comment by sejas** [comment]
> This works well and I like this solution, There's a `apiFetch from '@wordpress/api-fetch';`, I see this is used alot of places in the codebase, I wonder if it make more sense to use it rather than the js `fetch` api?

@vykes-mac I think it's better to not use `wordpress/api-fetch` for this use case.
My reasoning is that the wp api fetch is mostly designed to consume the WP org REST API, it adds the user authentication automatically which we don't need in this case, and it uses `window.fetch` under the hood, so we can keep our request lighter using directly the native fetch.
Mshots is not a WP API , and we are requesting only the headers of the images.

Source: https://developer.wordpress.org/block-editor/reference-guides/packages/packages-api-fetch/
> Utility to make WordPress REST API requests. It’s a wrapper around window.fetch.

**Review by vykes-mac — APPROVED** [review]
looks good!

**Pull request merged**
