### PR TITLE
Marketplace: Update copies and styles in Reviews modal

### PR DESCRIPTION
**Pull request by epeicher**
Related to https://github.com/Automattic/dotcom-forge/issues/4925

|Before | After|
|-------|------|
|      CleanShot 2023-12-18 at 19 05 46@2x      |        CleanShot 2023-12-18 at 19 03 12@2x      |
|   CleanShot 2023-12-18 at 19 06 03@2x       |        CleanShot 2023-12-18 at 19 03 24@2x        |

## Proposed Changes

* Update the title in the Add Review form to combine the previous two headings into one
* Update the copy and the styles of the success modal to be more similar to the design f84fqtCG4pCnCh2Hq0But5-fi-6859%3A34949. Please note that it is not identical as this component is not the definitive one.

## Testing Instructions

* On a development environment, navigate to a theme, e.g. `/themes/fewer/:siteId`
* Click on Add Review
* Make sure the text in the header reads as suggested in the parent task https://github.com/Automattic/dotcom-forge/issues/4925 "Add New Review for `:ThemeName`"
* Create the review
* Make sure the success card contains the suggestions in the parent task and the style is similar to the design f84fqtCG4pCnCh2Hq0But5-fi-6859%3A34949

## Pre-merge Checklist

- [x] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [x] https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [x] Have you checked for TypeScript, React or other console errors?
- [x] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [x] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

**Review by WBerredo — APPROVED** [review]
LGTMQ

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/10341096

Some locales (Hebrew, Japanese) have been temporarily machine-translated due to translator availability. All other translations are usually ready within a few days. Untranslated and machine-translated strings will be sent for translation next Monday and are expected to be completed by the following Friday.

Thank you @epeicher for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/10341096

Some locales (Hebrew, Japanese) have been temporarily machine-translated due to translator availability. All other translations are usually ready within a few days. Untranslated and machine-translated strings will be sent for translation next Monday and are expected to be completed by the following Friday.

Thank you @epeicher for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/10341096).

**Pull request merged**
