### PR TITLE
Me: add site blocks listing

### PR DESCRIPTION
**Pull request by bluefuton**
Although it is currently possible to block specific sites in Reader so they're not shown or recommended to you any more, there's nowhere in the UI to see a complete listing of your current blocks, or remove them. These have been missing features for some time now, and it's time to fill in the gaps.

This PR adds a simple list of your current site blocks to /me.

It relies on a new v2 endpoint `/me/blocks/sites`.

screen shot 2018-09-20 at 17 07 47

#### Testing instructions

Have a look at:

http://calypso.localhost:3000/me/site-blocks.

### CODE REVIEW

**Comment by bluefuton** [comment]
Todo: 
- [ ] add action + tests
- [ ] add infinite list
- [ ] add data layer tests
- [ ] add query component
- [ ] add selector
- [ ] `connect` up the component

**Comment by bluefuton** [comment]
https://github.com/Automattic/wp-calypso/pull/27392 provides the data layer and Redux plumbing for this PR, and must be landed first.

**Comment by bluefuton** [comment]
Still todo:
- [ ] pagination / fetch next page
- [ ] format list

**Comment by bluefuton** [comment]
For review, I've left the pagination set at '2 per page' so you can see the magical loading in action.

The PR has ended up being fairly chunky, but a good portion of it is tests :)

**Comment by blowery** [comment]
Nice work! The list appears and seems to work fine.

I think we might be able to drop the inflight reducer and selectors and just rely on `isFetching => currentPage !== lastPage`?

**Comment by bluefuton** [comment]
Thanks for looking @blowery!

> I think we might be able to drop the inflight reducer and selectors and just rely on isFetching => currentPage !== lastPage?

That's what I started out with, but the infinite list doesn't ever call `fetchNextPage`:

screen shot 2018-10-19 at 11 51 08

**Pull request merged**
