### PR TITLE
Signup: Adding site style to the business site segment flow

### PR DESCRIPTION
**Pull request by ramonjd**
## Changes proposed in this Pull Request

Break out the 🍾 This PR adds the **site style step** to the business onboarding flow.

~~⚠️ #32135 should be merged first.~~ ✅ 

Apr-23-2019 12-40-00

## Testing instructions

1. With **Business** as your site segment, continue through the flow to http://calypso.localhost:3000/start/onboarding-for-business/site-style-with-preview
2. Select a site style. The site preview should update according to the selected style.
3. Check the step window in various screen widths. The buttons should resize accordingly.
4. Create a site. Your chosen site style should determine the site's ultimate theme.

### CODE REVIEW

**Comment by jblz** [comment]
Although the style step is 😍, I would have expected the flow to have `site-information-title-with-preview` before `site-style-with-preview` so the latter is that much more impactful (it has the customer's name instead of a placeholder).

onboarding-title-before-style

Here's a link to try it out: https://hash-4f725764a81948bb9a8fdbca8e89d84900f5b01c.calypso.live/start/onboarding

An argument for keeping the style step earlier in the flow is: it's really low friction, so should perform better toward the top of the funnel, but showing the title in the style step seems worth to the overall experience to me.

---

Aside: I'm curious how it would perform having the two inputs (title & style) on the same step, but that's an exploration for another day :)

**Comment by ramonjd** [comment]
> I would have expected the flow to have site-information-title-with-preview before site-style-with-preview so the latter is that much more impactful (it has the customer's name instead of a placeholder).

Good point @jblz Not hard to switch around. 

It was defined back in Nov. 2018 (`p5XAZ9-1ZX-p2`), but I'm not sure if there have been any further ruminations on the topic.

Any opinions @shaunandrews or @fditrapani ?

Cheers!

**Comment by shaunandrews** [comment]
@jblz has the right idea here. The style step should come **after** the title step.

**Comment by michaeldcain** [comment]
@jblz: I went ahead and made the step switch. This is ready for re-review.

**Pull request merged**
