### PR TITLE
Remove "Advanced design customization" feature from Personal plan

### PR DESCRIPTION
**Pull request by mmtr**
Part of https://github.com/Automattic/dotcom-forge/issues/1244

#### Proposed Changes

We've decided to limit Global Styles on Premium plans and above (see paYJgx-2B7-p2#comment-2977), so this PR removes the "Advanced design customization" feature from the list of features included by the Personal plan in the wordpress.com/plans page.

It also removes the "CSS customization" feature from all plans, since it is no longer needed now that all plans that includes the "Advanced design customization" feature also include the ability to change the CSS.

Before | After
--- | ---
Screenshot 2022-12-06 at 15 40 21 | Screenshot 2022-12-06 at 15 57 40

#### Testing Instructions

- Use the Calypso live link below
- Go to "Upgrades > Plans"
- Make sure the "Advanced design customization" feature is not included in the Personal plan
- Make sure the "CSS customization" feature is not included in any plan
- Make sure the "Advanced design customization" feature for the Premium plan and above mentions the ability to change the CSS

### CODE REVIEW

**Review by dsas — APPROVED** [review]
LGTM.

Just for the record, the /pricing page will be updated as part of https://github.com/Automattic/dotcom-forge/issues/1244

**Review by Copons — DISMISSED** [review]
@mmtr I agree in theory with removing the CSS item, but in the interest of not embarking on another lengthy marketing & translation adventure, let's please keep both items and their existing descriptions. 😅 

We can iterate on it, but better to not risk blocking the whole project for longer than strictly needed.

**Review by niranjan-uma-shankar — APPROVED** [review]
LGTM from Autobots side.

**Comment by mmtr** [comment]
> I agree in theory with removing the CSS item, but in the interest of not embarking on another lengthy marketing & translation adventure

@Copons I don't think this needs any discussion with marketers and translators 🙂 

This PR is essentially going back to the state we had before https://github.com/Automattic/wp-calypso/pull/69205 was merged (where we didn't have any CSS item), and additionally removes the design customization feature from the Personal plan.

So I think a more fair before/after comparison would be this one:

Before (< Oct 25) | After (this PR lands)
--- | ---
Screen Shot 2022-10-11 at 15 26 02 | Screenshot 2022-12-06 at 15 57 40

We're reusing existing copy, so translations should be already in place.

However, I'm happy to disagree and commit if you still think we should keep the CSS item.

**Comment by Copons** [comment]
@mmtr if we can be 100000% sure the translation is still there, then go for it. 👍

**Comment by mmtr** [comment]
It is! This PR doesn't add any new string. See https://translate.wordpress.com/projects/wpcom/-all-translated/259585/

**Pull request merged**
