### PR TITLE
Sidebar: Restart plans 'upgrade' button a/b test

### PR DESCRIPTION
**Pull request by drewblaisdell**
@scruffian wants to restart this test with a new date.

**Testing**
With a newly created account, you can test both variations with the following instructions:

`original`:
- Run `localStorage.setItem( 'ABTests', '{"plansUpgradeButton_20160128":"original"}' );` in the console.
- Visit `/stats/year/:site` (or any 'My Sites' route) for a site with the free plan.
- Assert that you see the 'Free' label next to 'Plans' in the sidebar.

`original`:
- Run `localStorage.setItem( 'ABTests', '{"plansUpgradeButton_20160128":"button"}' );` in the console.
- Visit `/stats/year/:site` (or any 'My Sites' route) for a site with the free plan.
- Assert that you see the 'Upgrade' button next to 'Plans' in the sidebar.

### CODE REVIEW

**Comment by scruffian** [comment]
The results of this test were so interesting I'd rather run it for another week with a new timestamp.

**Comment by fabianapsimoes** [comment]
cc @lucasartoni

**Comment by scruffian** [comment]
We talked about this in zoom. Let's do a new test.

**Comment by drewblaisdell** [comment]
I updated the PR to simply change the date of the test, and added new testing instructions.

**Comment by fabianapsimoes** [comment]
@drewblaisdell I've updated the testing instructions, since they still had the wrong date.

:+1:

**Comment by scruffian** [comment]
I also added a commit to update the button text.

**Pull request merged**
