### PR TITLE
Performance Profiler: animate loading screen tips

### PR DESCRIPTION
**Pull request by gcsecsey**
Closes https://github.com/Automattic/dotcom-forge/issues/9108

## Proposed Changes

* Animate loading screen tips

## Why are these changes being made?

https://github.com/Automattic/dotcom-forge/issues/9108

## Testing Instructions

* Go to `/speed-test` and start a new test
* Check that the tips on the loading screen are animated when replaced

https://github.com/user-attachments/assets/afb87d8a-fe95-4c3e-9812-8ecfe3fc84c6

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Review by WBerredo — APPROVED** [review]
Really nice effect, looks great!

**Comment by WBerredo** [comment]
I've merged to fix the issue with both e2e tests.

**Comment by epeicher** [comment]
Thanks, @gcsecsey! I love the animation 🙌. Also, looping in @matt-west for review, in case there are any follow-up design tweaks to consider for the loading screen

**Comment by matt-west** [comment]
@gcsecsey Could we fade in/out the text when changing tips, but keep the container in the same place. It feels a bit jarring that it flys across the screen.

**Pull request merged**
