### PR TITLE
Comments: Add an Undo for bulk actions.

### PR DESCRIPTION
**Pull request by kwight**
When performing a bulk action on comments, this PR will offer an Undo in the notice.

### CODE REVIEW

**Comment by kwight** [comment]
@Copons would you mind taking a look at this? This undo is happening correctly, but I can't tell why an extra render seems to be happening when undoing a move to Trash or Spam (a non-persisted move). Persisted seems to work fine.

**Comment by Copons** [comment]
Ah yup. It's something we already stumbled upon in the past, and here it pops up again.

The **Tree** logic works like this:
- Obtain all the IDs from the server.
- Client-side, filter and paginate them into a subset .
- Render a `CommentDetail` for each ID of the subset.
- Inside `CommentDetail` there is a `QueryComment` component that requests the fresh comment data every time something changes (e.g. when the comment is rendered).

For this reason there is a sort of race condition going on with Undo on non-persisting comments.
This would be a kinda accurate timeline of what happens:

- Open the `spam` list.
- Set a `spam` comment as `approved`.
- A request is sent to the server to update the comment status to `approved`.
- The reducer updates the comment status to `approved`.
- The comment disappears from the `spam` list.
- The server responds with the new comment status: `approved`.
- The comment is now officially `approved`.
- Let's undo it!
- A request is sent to the server to update the comment status to `spam`.
- The reducer updates the comment status to `spam`.
- The comment reappears in the `spam` list.
- The `QueryComment` component requests a fresh version of the comment, which still has status `approved`.
- The reducer updates the comment status to `approved`.
- The comment disappears from the `spam` list.
- The server responds with the new comment status: `spam`.
- The comment is now officially `spam`... but in the wrong list.

For this reason we added a flag called `lastUndo` in the `CommentList`.

Every time there is an Undo action, [we set `lastUndo` to the undone comment ID](https://github.com/Automattic/wp-calypso/blob/master/client/my-sites/comments/comment-list/index.jsx#L229-L233).

```es6
setCommentStatus = ( /* ... */ ) => {
	// ...
	if ( isUndo ) {
		this.setState( { lastUndo: commentId } );
	} else {
		this.setState( { lastUndo: null } );
	}
	// ...
}
```

Then, [if the comment has just been undone](https://github.com/Automattic/wp-calypso/blob/master/client/my-sites/comments/comment-list/index.jsx#L146):

```es6
hasCommentJustMovedBackToCurrentStatus = commentId => this.state.lastUndo === commentId;
```

...we [tell `CommentDetail to not refresh the comment data](https://github.com/Automattic/wp-calypso/blob/master/client/my-sites/comments/comment-list/index.jsx#L475).

```es6
<CommentDetail
	// ...
	refreshCommentData={
		! isJetpack &&
		! this.hasCommentJustMovedBackToCurrentStatus( commentId )
	}
	// ...
/>
```

In other word, we [don't render `QueryComment`](https://github.com/Automattic/wp-calypso/blob/master/client/blocks/comment-detail/index.jsx#L259-L261) and just rely on the info in the Redux state (which is totally accurate, btw).

```es6
// blocks/comment-detail/index.jsx

{ this.props.refreshCommentData &&
	<QueryComment commentId={ commentId } siteId={ siteId } />
}
```

---

If you noticed, there is a `refreshCommentData = ! isJetpack`.
This is because Jetpack uses the Comment List endpoint, which requests a bunch of comments in their entirety, and therefore doesn't need to request each comment one by one as it is the case for the Tree.
In fact, if you try this branch on a JP site, it totally works!

**Comment by Copons** [comment]
Now, how to fix this?

IIRC at the beginning, `lastUndo` was indeed an array. Why did we change it to a single value. Was it because we didn't plan to have bulk undo anymore? Honestly can't remember.

What I remember is that unfortunately undo is not as simple, because of the fact that some status changes have a side effect: the damn Like.

So, not only we'd need to make `lastUndo` an array again (MLAA, in presidential terms), but also take into consideration how non-"Approve" actions also remove the Like, which then should be re-added on undo.

**Comment by kwight** [comment]
The better option is no bulk undos; closing this, since we've discussed removing undos and positive notifications across comments.

**Pull request closed without merging**
