### PR TITLE
CPT: Prompt and permanently delete trashed posts

### PR DESCRIPTION
**Pull request by aduth**
This pull request seeks to enable permanently deleting trashed posts. If a post is already trashed, the trash button should permanently delete the post. The user will be prompted to confirm this action before issuing the request.

__Implementation notes:__

I opted against property-specific selectors in f4951c41010c2ffab2c89ea96f5e6fb55c76f31b, since we can achieve most of the items below in our `getNormalizedPost` selector.

~~The individual property selectors may seem a bit excessive, and could be tedious to implement for every property. However, the one's included highlight a few benefits:~~

- ~~Consistency with naming conventions ([reference](https://github.com/Automattic/wp-calypso/blob/master/docs/coding-guidelines/javascript.md#naming-conventions))~~
- ~~Opportunity to customize logic, similar to [where we accept options for generating URLs of media items](https://github.com/Automattic/wp-calypso/blob/master/client/lib/media/utils.js#L31-L72)~~
- ~~Avoids need to test for presence of `post` before accessing nested properties~~
- ~~Avoids tying our components to shape of state structure if we refactor post object~~

Related discussion: https://github.com/Automattic/wp-calypso/pull/6082/files#r67393626

__Testing instructions:__

Ensure Mocha tests pass:

```
npm run test-client client/state/posts
```

Verify that when trashing a post from the [custom post type list screen](http://calypso.localhost:3000/types/post), that...
 - If the post is not yet trashed, the post is immediately removed and sent to trash (no prompt)
 - If the post is already trashed, you are prompted to permanently delete the post and only if you accept this prompt is the post removed (deleted)

Test live: https://calypso.live/?branch=update/cpt-permanent-delete

### CODE REVIEW

**Comment by nylen** [comment]
This is working well for me, and the code looks good.

Pre-existing issue, but on Jetpack sites the counts section is blank because the `post-counts` endpoint loads from WPCOM only and CPTs registered on the Jetpack site are not recognized.

**Comment by aduth** [comment]
Thanks @nylen . Do the statuses show in the filter bar at least? Or does nothing show at all?

**Comment by aduth** [comment]
Added a note in the original comment about deciding against property-specific selectors:

>I opted against property-specific selectors in f4951c41010c2ffab2c89ea96f5e6fb55c76f31b, since we can achieve most of the items below in our `getNormalizedPost` selector.

**Comment by nylen** [comment]
The filter bar is always blank on my test site:

image

"No posts found" is as expected given the current state of my site.

Sort of related to #4793.

**Comment by aduth** [comment]
Kinda surprised that published and drafts don't show at all. I thought I'd forced them to always show. In any case, I suppose we should ignore the "if zero count, then hide" logic for Jetpack sites?

**Comment by nylen** [comment]
Sounds reasonable to me.

**Pull request merged**
