### PR TITLE
Security: fix jetpack-credentials in small screens

### PR DESCRIPTION
**Pull request by simison**
Fixes visual issues in the security settings page for Jetpack credentials section.

Text would previously overflow in small screens.

# Screenshots

### 320x Before:
image

### 320x After:
image

(I'll address that broken too narrow notice in a more generic PR.)

### 480x Before:
image

### 480x After:
image

### 680x Before:
(680 looks more narrow than 480x because sidebar is now visible) 

image

### 680x After:
image

### 1024x Before:
image

### 1024x After:
image

# Testing
- Connect Jetpack site and see `http://calypso.localhost:3000/settings/security/:YOURSITE`
- Test in different browsers and screen sizes

### CODE REVIEW

**Comment by mattmiklic** [comment]
I think you want a design review from @MichaelArestad or someone else on the Jetpack design team for this one; I'm only working on the native app versions of this screen.

**Comment by simison** [comment]
@mattmiklic Sorry buddy, I still keep mixing up everyone. :-)

**Comment by mattmiklic** [comment]
No problem! :)

**Comment by eliorivero** [comment]
While I reproduced the issues:

captura de pantalla 2018-03-22 a la s 16 59 34
captura de pantalla 2018-03-22 a la s 16 59 43
captura de pantalla 2018-03-22 a la s 17 00 13

and I see the dropped `d` fixed in 320:

captura de pantalla 2018-03-22 a la s 17 01 41

the line of text is still dropping to a new line, even in large screen sizes

captura de pantalla 2018-03-22 a la s 17 01 58

captura de pantalla 2018-03-22 a la s 17 02 40

**Comment by simison** [comment]
@eliorivero we're definitely looking at different things. :-)

You're looking at the section for autoconfigured sites: 
https://github.com/Automattic/wp-calypso/blob/80095a0fd42a8591113d1cfffde6d22743053fa8/client/my-sites/site-settings/jetpack-credentials/credentials-configured/index.jsx#L67-L80

I was modifying the section where you need to manually enter your creds:
https://github.com/Automattic/wp-calypso/blob/80095a0fd42a8591113d1cfffde6d22743053fa8/client/my-sites/site-settings/jetpack-credentials/credentials-configured/index.jsx#L82-L112

I updated both sections to use `.credentials-configured__header` that I now renamed to `.credentials-configured__info` — thoughts?

Suppose it's expected to have text blue on all screen sizes?

Lemme know if I should remove "connected" heading also for the other section (and maybe change text blue there, too?)

### Screenshots

#### 320x
image

#### 480x
image

#### 680x
image

#### 1024x
image

**Comment by eliorivero** [comment]
> Suppose it's expected to have text blue on all screen sizes?

Yup, awesome now.

> Lemme know if I should remove "connected" heading also for the other section (and maybe change text blue there, too?)

I think it would be safe to remove it and make both cards similar (apart from the chevron that should still point down in the card that expands to fill in the creds). That would also simplify code a bit. What do you think @MichaelArestad?

This works fine and is good to be merged now 🐑 

captura de pantalla 2018-03-26 a la s 18 09 38
captura de pantalla 2018-03-26 a la s 18 09 59
captura de pantalla 2018-03-26 a la s 18 10 26
captura de pantalla 2018-03-26 a la s 18 12 07

**Comment by simison** [comment]
> > Lemme know if I should remove "connected" heading also for the other section (and maybe change text blue there, too?)

> I think it would be safe to remove it and make both cards similar (apart from the chevron that should still point down in the card that expands to fill in the creds). That would also simplify code a bit. 

:thumbsup: Yep! I'll leave that for a separate PR. Feel free to comment in this thread, though.

**Comment by MichaelArestad** [comment]
@eliorivero @simison oh yeah. Let's remove the redundant connected compact notice thing. Good catch!

**Pull request merged**
