### PR TITLE
Comments: move into blocks

### PR DESCRIPTION
**Pull request by bluefuton**
In #7423, @fraying requested a bunch of improvements to full post comments.

As groundwork for this, I've duplicated the `reader/comments` components into the new `blocks` directory and resolved any linting/style/CSS errors along the way.

### To test

Check that there are no functional or visual regressions in the comments section on full post view. 

The new comments components are enabled in the new Reader full post view (only in use on development and calypso.live).

Existing:
https://wpcalypso.wordpress.com/read/feeds/40474296/posts/999143144

Shiny new:
http://calypso.localhost:3000/read/feeds/40474296/posts/999143144

Test live: https://calypso.live/?branch=update/reader/comment-layout

### CODE REVIEW

**Comment by bluefuton** [comment]
@yurynix as the original author of this code, could I trouble you for a quick review please? :)

There aren't many alterations to what you originally produced - it just has a new home in `blocks/`.

**Comment by blowery** [comment]
Might need to pick up #7262

**Comment by bluefuton** [comment]
> Might need to pick up #7262 

Good shout. Added in 6b3b9e2.

**Comment by blowery** [comment]
LGTM 🚢

**Comment by yurynix** [comment]
I'll take a look on Sunday, sorry for the delay.

**Comment by yurynix** [comment]
I've checked it out today, it seems there weren't many code changes, unless I missed something =)
Also played with it a bit, seems to work good 👍 :shipit:

**Comment by bluefuton** [comment]
Thanks for taking the time @yurynix, much appreciated :)

**Comment by nb** [comment]
@bluefuton, @yurynix, @blowery do we need both these component and the ones living in `client/reader/comments`? They look almost the same.

**Comment by bluefuton** [comment]
Hey @nb - the intention here was to create the block and then remove `reader/comments` completely in a followup PR. However, `my-sites/posts/post.jsx` still uses the old component so we'll need to switch that over first. I'll create an issue for that.

**Comment by nb** [comment]
Thanks, @bluefuton.

**Pull request merged**
