### PR TITLE
Component: HappinessSupport: Show an illustration instead of Gravatar.

### PR DESCRIPTION
**Pull request by taggon**
## How to test

You should find the new HE illustration in the following two pages:
- Thank you screen
 1. Complete to purchase a paid plan subscription.
 2. There should be the new HE illustration at the bottom of the thank you page.
- Current plan screen of a site on any paid plan.
 1. Open Plan page for your website not on a paid plan.
 2. The Happiness Support card should show the new illustration.

Demo: https://cloudup.com/cvhvaiElt2S

This PR is a part of #14863 which is going to be dropped soon.

cc @cristelrossignol @markryall @fditrapani

### CODE REVIEW

**Comment by fditrapani** [comment]
@taggon Looks like there is a test failure.

**Comment by taggon** [comment]
@fditrapani It's because the e2e test attempts to find `<Gravatar />` element that was removed from this commit. Should I update the test too?

**Comment by fditrapani** [comment]
Yeah, we'll probably need to update the test too. @markryall helped me out with that for a another PR I worked on.

**Comment by cristelrossignol** [comment]
Thank you screen: Failure for me too (https://cloudup.com/c4nOAatcyxz)

Current plan screen of a site on any paid plan: Works perfectly! (https://cloudup.com/ca8up0MlC23)

**Comment by taggon** [comment]
@fditrapani Found out it's not about the e2e test. The errors happened in files I didn't touch in this PR.

**Pull request merged**
