### PR TITLE
Remove `moment` dependency from 2fa.

### PR DESCRIPTION
**Pull request by sgomes**
Replace current time in illustration with a hardcoded string.

#### Changes proposed in this Pull Request

* Replace current time in illustration with a hardcoded string.

#### Testing instructions

I'm not entirely sure how to test this in-place. However, we're just replacing some string formatting with a hardcoded string.

### CODE REVIEW

**Comment by blowery** [comment]
This "appears" in a very specific circumstance. You must:
1) Turn on 2FA for an account
2) Log into that account on a native mobile app (I tested with Android)
3) Log into that account using this branch
4) We will send a push notification to your mobile app asking if you want to log in
5) While we wait for the notification to be acted upon, we show WaitingTwoFactorNotificationApproval

However, the time is _hidden_ on that screen and serves no real purpose. I think we could drop it entirely.

Screen Shot 2019-10-08 at 11 36 25 AM

**Comment by sgomes** [comment]
> However, the time is _hidden_ on that screen and serves no real purpose. I think we could drop it entirely.

Thanks for looking into this, @blowery! I played around with the component some more, and it appears that this is an animation, and the time is actually visible to start with:

image

The notification rectangle then slides from the top, resulting in your screenshot. So the time is shown, albeit for a fraction of a second.

With that in mind, I'd keep the string, but I don't really think it's super-important to have the right time there. I'm happy to leave the code as-is, or to replace it with a hardcoded string, depending on what you prefer.

**Comment by blowery** [comment]
> With that in mind, I'd keep the string, but I don't really think it's super-important to have the right time there. I'm happy to leave the code as-is, or to replace it with a hardcoded string, depending on what you prefer.

I think I'd just use a hard coded string. Maybe the time of the first WordPress release? `10:07`

**Review by blowery — APPROVED** [review]
GTG whichever way you decide

**Comment by sgomes** [comment]
> I think I'd just use a hard coded string. Maybe the time of the first WordPress release? `10:07`

Sounds good to me! Done. 👍

**Comment by porada** [comment]
I’m sad to see us remove tiny design details like this one. Like-minded people appreciate them.

> With that in mind, I'd keep the string, but I don't really think it's super-important to have the right time there.

I used the current time to indicate that the push notification is about to arrive _now_ and not at any specific time (and the reason I went with `moment` is because we already depended on it). If we’re shaving off bytes, I’d rather we didn’t show time at all instead of using `10:07`. That would have the least chance of confusing anybody.

**Comment by sgomes** [comment]
> I’m sad to see us remove tiny design details like this one. Like-minded people appreciate them.
> 
> > With that in mind, I'd keep the string, but I don't really think it's super-important to have the right time there.
> 
> I used the current time to indicate that the push notification is about to arrive _now_ and not at any specific time (and the reason I went with `moment` is because we already depended on it). If we’re shaving off bytes, I’d rather we didn’t show time at all instead of using `10:07`. That would have the least chance of confusing anybody.

@porada The first commit in this PR did actually implement the whole thing without `moment`, so if you feel it's important, I'd be more than happy to create a new PR reinstating that code. 👍

**Comment by porada** [comment]
@sgomes Thanks, I’d love that. 🙂

**Comment by jsnajdr** [comment]
> The first commit in this PR did actually implement the whole thing without `moment`

Can the time formatted be also localized without `moment`. I share the sad feelings with @porada and would love to help reintroduce that sweet feature 🙂

**Comment by sgomes** [comment]
> (and the reason I went with `moment` is because we already depended on it)

To give you some context, the reason why I wanted to drop `moment` here is that Calypso is no longer a monolithic application, as it perhaps was in the beginning. Many of the optimisations that have been worked on over the past while have to do with restricting libraries and portions of Calypso code to where they're really needed, instead of having everything available everywhere. That helps us progressively load the application as the user navigates it, rather than loading the whole of Calypso no matter what page the user is viewing.

After some recent changes, the login page is in a unique position to be able to drop some of these dependencies, and we're very close to being able to drop `moment` from it altogether 🙂

**Comment by sgomes** [comment]
> Can the time formatted be also localized without `moment`. I share the sad feelings with @porada and would love to help reintroduce that sweet feature 🙂

If we're trying to do the same that was there before, there's no need for localisation, as we were doing a fixed timestamp.

If, however, we feel that a localised time would make this even better, I'm also happy to work on that 🙂 Not all browsers have the same localisation support, but I could cook up something that would have the fixed format fallback if need be.

**Pull request merged**
