### PR TITLE
[TEST][IGNORE] testing desktop canary bridge

### PR DESCRIPTION
**Pull request by nsakaimbo**
### Description

Testing -- ignore.

### CODE REVIEW

**Comment by nsakaimbo** [comment]
Closing test PR.

**Comment by bsessions85** [comment]
Re-opening for some tests

**Review by bsessions85 — CHANGES_REQUESTED** [review]
WordPress Desktop CI Failure (ci/wp-desktop): Please review this PR for breaking changes.

**Review by bsessions85 — DISMISSED** [review]
WordPress Desktop CI Failure (ci/wp-desktop): Please review this PR for breaking changes.

**Review by wp-desktop — DISMISSED** [review]
WordPress Desktop CI Failure (ci/wp-desktop): Please re-try this workflow ("Rerun Workflow from Failed") and/or review this PR for breaking changes.

**Review by nsakaimbotestuser — CHANGES_REQUESTED** [review]
WordPress Desktop CI Failure (ci/wp-desktop): Please re-try this workflow ("Rerun Workflow from Failed") and/or review this PR for breaking changes.

**Review by wp-desktop — DISMISSED** [review]
WordPress Desktop CI Failure (ci/wp-desktop): Please re-try this workflow ("Rerun Workflow from Failed") and/or review this PR for breaking changes.

**Review by wp-desktop — DISMISSED** [review]
WordPress Desktop CI Failure (ci/wp-desktop): @nsakaimbo please re-try this workflow ("Rerun Workflow from Failed") and/or review this PR for breaking changes.

**Review by wp-desktop — DISMISSED** [review]
WordPress Desktop CI Failure (ci/wp-desktop): please re-try this workflow ("Rerun Workflow from Failed") and/or review this PR for breaking changes. Please also ensure this branch is rebased off the latest Calypso master.

**Review by wp-desktop — DISMISSED** [review]
WordPress Desktop CI Failure (ci/wp-desktop): @nsakaimbo please re-try this workflow ("Rerun Workflow from Failed") and/or review this PR for breaking changes. Please also ensure this branch is rebased off the latest Calypso master.

**Pull request closed without merging**
