### PR TITLE
FSE: bump plugin version to 1.0

### PR DESCRIPTION
**Pull request by vindl**
#### Changes proposed in this Pull Request

Updates FSE plugin version to 1.0.

#### Testing instructions

1. Use the generated diff to test the latests updates from changelog on you sandbox.
2. Use the generated archive to test on Atomic sites.

### CODE REVIEW

**Comment by obenland** [comment]
> bump plugin version to 1.0

😱

**Comment by noahtallen** [comment]
a few folks have been asking me about this bugfix: https://github.com/Automattic/newspack-blocks/pull/407

If newspack releases an update monday, it'd be nice to get that into the sync.

**Comment by vindl** [comment]
> a few folks have been asking me about this bugfix: Automattic/newspack-blocks#407
> If newspack releases an update monday, it'd be nice to get that into the sync.

I'm fine with that. 👍

**Comment by noahtallen** [comment]
here's another: https://github.com/Automattic/wp-calypso/pull/40489

**Comment by frontdevde** [comment]
> here's another: #40489

Just noting that https://github.com/Automattic/wp-calypso/pull/40489 has just been merged.

**Comment by noahtallen** [comment]
As far as I can tell, everything else is working correctly:
- dotcom-fse
- homepage title mod
- blog posts update
- blog posts text domain fix

https://github.com/Automattic/wp-calypso/commits/master/apps/full-site-editing

**Comment by noahtallen** [comment]
Though global styles works on Atomic (yay), it seems as some of the previews (like heading) are broken. This could be related to that PR as well

Screen Shot 2020-03-31 at 5 34 29 PM

**Comment by nosolosw** [comment]
@noahtallen tested current FSE `master` in both local & atomic sites, using the Maywood theme and it works fine, including previews. Going to do a quick test in dotcom.

**Comment by nosolosw** [comment]
I can repro in dotcom, and got some leads that may be helpful to debug:

- https://github.com/Automattic/wp-calypso/pull/40489 changes where the styles for the editor are stored => previously there were added to the `editor-styles-wrapper` node, now they get appended as a style node at the body.
- for some reason, the style node at dotcom isn't appended after the rest of the style nodes, it gets prepended instead. See:

Screenshot from 2020-04-01 09-54-26

The selected style node in the image above is the one added by the Global Styles editor's component. It should be appended **after** all the other nodes (especially after the other expanded style node, which is the one generated in the server by Global Styles, and has the user choices stored in the database).

Unfortunately, off the top of my head, I can't say why this is happening. Perhaps someone more experienced in how the iframed gutenberg works in dotcom can shed some light on this?

I'd be happy to help to debug this but I won't be available to do so until probably Friday. If @frontdevde or anybody else can't come to this first, I guess it's safe to revert https://github.com/Automattic/wp-calypso/pull/40489 as it fixes an issue with block previews that, even it's a bug that needs fixing, doesn't prevent Global Styles from working.

**Comment by damiannep** [comment]
Following to inform user in 2827929-zen when issue resolved.

**Comment by noahtallen** [comment]
my best guess is that now the call happens outside of `subscribe`, which means that it might happen some ticks earlier than it did before. Maybe the fix is to append the style element inside the subscribe call again?

**Comment by noahtallen** [comment]
I will try that real quick

**Comment by noahtallen** [comment]
@nosolosw this fixes the issue: https://github.com/Automattic/wp-calypso/pull/40690

**Comment by vindl** [comment]
> Following to inform user in 2827929-zen when issue resolved.

@damiannep the PR that's causing the issue reported here is not live in production yet. It will land together with the fix, so the user might be experiencing some other related issue?

**Comment by noahtallen** [comment]
reminder to test glolbal styles on Atomic sites with and without the gutenberg plugin active

**Comment by arunsathiya** [comment]
@damiannep Your user has been informed, it was the same issue. 👍🏽

**Pull request merged**
