### PR TITLE
Pre-populate Add G Suite fields for first user

### PR DESCRIPTION
**Pull request by belcherj**
#### Changes proposed in this Pull Request

* Pre populates the email, first name, and last name fields of the first user since we already have something the will work for most users.

#### Testing instructions

Testing New Domain Flow:

Test Flow:
* Goto Reader, refresh page
* Goto a site
* Goto Domains
* Click "Add a domain"
* Choose any domain
* Click "Yes, add email"
* Observe that you can see the G Suite user fields filed in with your details
* Ensure add another user works
* Ensure that you can click to the next screen

Before:
screen shot 2018-12-14 at 1 42 03 pm

After:
screen shot 2018-12-14 at 3 39 54 pm

Testing Existing Domain adding Email

Test Flow:
* Goto Reader, refresh page
* Goto a site with domain but no G Suite
* Goto Domains
* Goto email tab
* Click `Add G Suite` button
* Observe name is populated

Before:
screen shot 2018-12-18 at 10 46 44 am

After:
screen shot 2018-12-18 at 10 46 11 am

Do Variants for both flows:

Variant 1
* Goto your user profile
* Change your name
* Do test flow
* Observe that name doesn't change until you refresh ( user settings are not updated in Redux state )
* Observe that name is populated correctly on refresh

Variant 2
* Goto your user profile
* Remove your name
* Refresh ( user settings are not updated in Redux state )
* Do test flow
* Observe that name is not repopulated as it doesn't exist

Note:  Names can contain invalid characters but the error handling on the form picks that up.

### CODE REVIEW

**Comment by belcherj** [comment]
There seems to be a problem with this PR.  Not sure what the issue is but more testing is required.

**Comment by belcherj** [comment]
I have tested this on my dev build and on the live link with an existing user and a brand new test user.

**Comment by gravityrail** [comment]
For some reason the fields were blank for my user (goldsounds) no matter what I tried - new setup, adding to existing domain from checklist, from domain tab, etc. :/

**Comment by belcherj** [comment]
Give it another try.  I added the query component to make sure it requests the data.

**Comment by gravityrail** [comment]
I had a hot-reload problem. All works for me now. Thanks!!

**Pull request merged**
