### PR TITLE
Add fill and outline style to premium content login button

### LINKED ISSUE #44333: Premium Content: Button styling options
Comparing Premium Content functionality to Buttons block I found some missing styling options:
 * no block styles ( Buttons block offers two - fill, outline).
 * there are differences between Subscribe and Log in button. Subscribe button doesn’t have a border-radius option or the text formatting options.

#### Steps to reproduce

1. Add a Premium Content block to a post or a page.
2. Customize Subscribe and Log in buttons.
3. Note the differences in styling options available between both buttons.
4. Add a Buttons block below. Note the additional block style options in the sidebar:

image

Log in button settings:
image

Subscribe button settings:
image

#### What I expected
Both Subscrbe and Log in buttons should offer the same styling options. Ideally, we would have parity with Buttons block in regards to styling options.

### PR DESCRIPTION
**Pull request by glendaviesnz**
#### Changes proposed in this Pull Request

* Adds Fill and Outline styling options to the Premium Content Login button so match the styling on other buttons

Fixes #44333

#### Testing instructions

* Add a Premium content block to a post/page and save
* Apply this PR and reload the page and ensure the block style loads ok
* Check that the login button now has open to set style to Fill & Outline
* Make sure both styles can be save ok and display correctly in Editor and front end

Screen Shot 2020-10-07 at 3 35 34 PM

### CODE REVIEW

**Review by apeatling — APPROVED** [review]
Works well 👍

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/4886358).

**Comment by noahtallen** [comment]
I tested this with the "Mayland" theme active, and I think something is odd with the styles. "Outline" doesn't display the outline until I hover it in the editor.

**Comment by noahtallen** [comment]
Note: the outline style issue appears to be an issue for all block buttons in varia child themes, so probably unrelated to this change. :) I created a tracking issue here: https://github.com/Automattic/themes/issues/2582

**Pull request merged**
