### PR TITLE
My Plan: reorder plan feature cards to highlight focus on security and performance

### LINKED ISSUE #31357: [Shortcopy] Calypso Plan > My Plan: prioritize Security and Performance feature cards
Refocusing Jetpack around Security and Performance.

Design TBD

### PR DESCRIPTION
**Pull request by keoshi**
#### Changes proposed in this Pull Request

* My Plan: reorder plan feature cards to highlight focus on security and performance
* Fixes #31357 

#### Testing instructions

1. Create a [new Jurassic Ninja site](https://jurassic.ninja/create/?shortlived).
1. Start the connection and select the Free plan.
1. Spin up this PR or use the calypso.live link below.
1. Go to `/plans/my-plan/SITE_URL`.
1. Make sure everything looks good and works on that page.
1. Repeat steps 5 and 6 for all plans: Personal, Premium, Professional.

#### Free plan: Before

image
image

#### Free plan: After

image
image

#### Personal plan: Before

image

#### Personal plan: After

image

#### Premium plan: Before

image

#### Premium plan: After

image

#### Professional plan: Before

image

#### Professional plan: After

image

### CODE REVIEW

**Comment by keoshi** [comment]
Woohoo, thanks for the super quick and thorough review, @eliorivero !

I've pushed a fix for the vertical spacing issue on https://github.com/Automattic/wp-calypso/pull/31749/commits/71fcc487aac6f0a5c85f6d7551cdd8e6c1b191c3

Re: task list: I think it appears on dev because @tyxla is currently working on it — please, correct me if I'm wrong, Marin.

**Comment by tyxla** [comment]
> Re: task list: I think it appears on dev because @tyxla is currently working on it — please, correct me if I'm wrong, Marin.

👍 Yeah, this is part of the security checklist project we're working on right now, and this is visible on dev and wpcalypso environments. More context: p5XAZ9-2c7-p2

**Comment by keoshi** [comment]
Thanks for bringing that up, @tyxla. I saw it too, but it's tricky because of our fixed breakpoints that don't take into consideration the sidebar.

For now, I just bumped the minimum required screen size to show the button on the right; does this look better?

image

**Comment by tyxla** [comment]
Looks great @keoshi! Thank you!

**Comment by jeffgolenski** [comment]
@keoshi Just tested it. All looks good except on the phone, there's a weird margin issue under the plan icon. How about we just hide the plan icon for small mobile screens? It's really just decoration at this point.

Screen Shot 2019-03-26 at 1 56 33 PM

**Comment by keoshi** [comment]
Good catch, Jeff! I've pushed a change on https://github.com/Automattic/wp-calypso/pull/31749/commits/43ab83213e1a78c4b395afe000cab565cfd088d4 to hide the icon on small screens.

Here's how it looks now on a Pixel 2 XL:

image

**Comment by jeffgolenski** [comment]
@keoshi noooiiiiceeeee

**Pull request merged**
