### PR TITLE
Login: update SMS to text message in copy

### LINKED ISSUE #15473: Login: replace "SMS" with "text message"
The term "SMS" is used in a few Calypso strings (and elsewhere in WordPress.com), in reference to account access codes sent via SMS text message. 

However, "SMS" is not a common term in top English-speaking locales. The phrase "text message" is probably going to work much better for English readers.

For example, according to Wikipedia:

> It may simply be referred to as a "text" in North America, the United Kingdom, Australia, New Zealand and the Philippines, an "SMS" in most of mainland Europe, or an "MMS" or "SMS" in the Middle East, Africa, and Asia

For the default en_US locale (as in, the locale we use for the original strings), I suggest we replace the use of "SMS" with "text message". 

It's worth noting that we are not using the term "SMS" consistently. We also already use "text message" in different places. For this reason, I don't think we have to worry too much about doing a big copy review or anything. It would be enough to just change this gradually as we go.

For example, in [recovery-phone-validation-notice.jsx](https://github.com/Automattic/wp-calypso/blob/master/client/me/security-account-recovery/recovery-phone-validation-notice.jsx):

Before:

> Please validate your recovery SMS number. Check your phone for a validation code.

After:

> Please validate your recovery phone number. Check for a text message with a validation code.

Before:

> Enter the code you receive via SMS:

After:

> Enter the code from the text message:

### PR DESCRIPTION
**Pull request by fabianapsimoes**
This pull request fixes #15473 by replacing occurrences of "SMS" in the login flow with "text message".
  
#### Testing instructions
  
1. Run `git checkout update/sms-to-text-message-copy` and start your server
2. Try to log in using an account that has 2FA enabled via an authenticator app
3. Click "Code via text message"
4. Do not enter the code you received, instead click "Your Authenticator app"
5. Click "Code via text message" again. 
6. You should see the following error: "You can only request a code via text message once per minute. Please wait and try again."
  
#### Additional notes
  
There are still occurrences of "SMS" under `https://wordpress.com/me/security/two-step` (cc @ebinnion) and under the new Account Recovery flow that is still under construction (@southp). These should be addressed at some point, considering the input from @ranh and @benhuberman in the original issue.

Additionally, all functions and variables still use "SMS", being inconsistent with the user-facing terminology.
  
#### Reviews
  
- [x] Code
- [x] Product

### CODE REVIEW

**Comment by stephanethomas** [comment]
The code looks good.

**Comment by southp** [comment]
Thanks for the heads up. I've added it to my list :)

**Comment by stephanethomas** [comment]
During testing I found out that global notices are never displayed because of how [this condition](https://github.com/Automattic/wp-calypso/blob/c968da96895e10c59b3f6e3482f9d0a122442bac/client/blocks/login/index.jsx#L95-L98) is constructed: `error` evaluates most of the time to `false`, which prevents the notice from appearing. I've refactored the code that handles errors, and fixed that problem.

This pull request needs another round of review.

**Comment by hafizrahman** [comment]
Product LGTM

**Comment by yurynix** [comment]
Code looks 👍  Nice refactor @stephanethomas :shipit:

**Pull request merged**
