### PR TITLE
Launchpad: Improve focus style for accessibility

### LINKED ISSUE #87469: Launchpad: Improve focus state on the checklist items
### Details
To meet the focus accessible requirements and other interface elements we need to improve the Launchpad checklist item focus state to follow similar behavior we have on other UI elements.

You can find more context about the focus state on:
* [Explanation about the focus state](https://www.w3.org/TR/WCAG22/#focus-appearance)
* https://www.tempertemper.net/blog/focus-appearance-explained

## Current State
https://github.com/Automattic/wp-calypso/assets/38718/752aaa3a-bb29-4c2a-8d56-14688bfb918c

## Expected State
https://github.com/Automattic/wp-calypso/assets/38718/98d0455d-21b2-4d4d-adbc-5dbf45ea3de7

### Checklist

_No response_

### Related

_No response_

### PR DESCRIPTION
**Pull request by gabrielcaires**
Related to #87469 

## Proposed Changes

* Improve the focus state to follow accessibility requirements

### Customer Home
https://github.com/Automattic/wp-calypso/assets/38718/d2f302e3-2d5c-453f-9d78-8b91ee734240

### Tailored Onboarding
https://github.com/Automattic/wp-calypso/assets/38718/00c8af09-cdbb-44c4-a12d-5b68313a5199

## Testing Instructions
* Go to the customer's home and use the tab to navigate between the buttons
* Go to any onboarding flow, go to the launchpad page and use the tab to navigate between the buttons

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Comment by valterlorran** [comment]
I think we should ask @nuriapenya to chime in on this. I just wanted to check if she has any thoughts regarding these changes.

**Comment by markbiek** [comment]
Agreed that @nuriapenya should weigh in.

My first thought is this looks very cramped on the left side.
CleanShot 2024-02-16 at 13 24 18

**Comment by gabrielcaires** [comment]
> Agreed that @nuriapenya should weigh in.
> 
> My first thought is this looks very cramped on the left side.
@markbiek  @valterlorran 

I agree it seems weird but it is the standard way to do it when we are dealing with a list of links, as you can see on google:

image


However, I added a tiny space between the border and the content. It causes a little jump. I am not sure if it is good or bad for accessibility issues, no other styles provoke content "jumping", so I have mixed feelings about it.


https://github.com/Automattic/wp-calypso/assets/38718/4fa7a219-ba11-49c1-96e6-574ac5b3dc93

**Comment by daledupreez** [comment]
> However, I added a tiny space between the border and the content. It causes a little jump. I am not sure if it is good or bad for accessibility issues, no other styles provoke content "jumping", so I have mixed feelings about it.

Weird jumps => definitely not good!

Can we add a `:not(:focus)` selector that adds the same effective padding for the non-focused case? This might avoid the visible jump.

**Comment by markbiek** [comment]
I wanted to share this article about accessible focus indicators from an accessibility author that I really love: https://www.sarasoueidan.com/blog/focus-indicators/

A lot of the article is more specific to buttons but there's also good information about lists and other things.

She has one interesting suggestion for focus indicators on the kind of list we're talking about in this PR:

image

I'll defer to design's judgement but this might be another way to do it.

**Comment by gabrielcaires** [comment]
> Can we add a `:not(:focus)` selector that adds the same effective padding for the non-focused case? This might avoid the visible jump.

I was trying to avoid it to not miss the left alignment but it seems [optically aligned](https://liferay.design/articles/best-practices/measured-vs-optical-alignment/) and I think it is better than jump as you can see here.

Updated version here:

https://github.com/Automattic/wp-calypso/assets/38718/8fb1e429-d3f4-4a40-bc4d-c42e38510534


@markbiek  I liked the approach, but my concern is we already have another list on the same screen but I would like to have more design inputs @nuriapenya 

https://github.com/Automattic/wp-calypso/assets/38718/98d0455d-21b2-4d4d-adbc-5dbf45ea3de7

**Review by daledupreez — APPROVED** [review]
The changes look good to me and test well. Given that @nuriapenya is going to be AFK until next week, I think we should ship this now and iterate based on her feedback when she gets back in.

**Pull request merged**
