### PR TITLE
Update logged out masterbar styles

### PR DESCRIPTION
**Pull request by Addison-Stavlo**
Related to #

## Proposed Changes

* Updates logged out masterbar styles per suggestions on pe7F0s-Zq-p2 

Im uncertain about the locale handling added here currently, it doesn't seem like logged out reader pages work with non-en locales so maybe we want to hide these for the non-default locale for the time being?

## Testing Instructions

*

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

**Comment by davemart-in** [comment]
> Im uncertain about the locale handling added here currently, it doesn't seem like logged out reader pages work with non-en locales so maybe we want to hide these for the non-default locale for the time being?

@roo2 brought up a similar concern on the team call Yesterday. I'd say let's handle translations for the new discover page and the tags pages both in a separate project. I'll create a separate Project Thread for this.

**Review by davemart-in — APPROVED** [review]
I made a few minor updates. LGTM!

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/8552320

Hi @Addison-Stavlo, could you please edit the description of this PR and add a screenshot for our translators? Ideally it'd include all of the following strings:
- `Popular Tags`
- `Search`

Thank you in advance!

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/8552320).

**Pull request merged**
