### PR TITLE
Add Tracks events to searches in the block picker

### PR DESCRIPTION
**Pull request by scruffian**
This sends events to Tracks when users perform searches in the block selector in Gutenberg.

#### Changes proposed in this Pull Request

* Sends two new events to Tracks. One for every search that is performed in the block picker and another for when the search doesn't return any results. I thought it was best to create two events as its hard to filter an event by two properties in Tracks.

This is part of paAmJe-lV-p2

#### Testing instructions
- Get this code running on your sandbox (see field guide)
- Go to the block editor
- Turn on debugging by running this in your browser console: `localStorage.setItem('wpcom-block-editor:analytics:tracks');`
-Do some searches and check that they are logged in your console. You should see two events when there are no results.

### CODE REVIEW

**Comment by kwight** [comment]
I think we should be able to use existing Tracks libraries, instead of adding a new one. Jetpack has access to https://github.com/Automattic/jetpack/blob/master/_inc/lib/tracks/tracks-callables.js, while all Simple sites should have Tracks loaded in the client for all `wp-admin` page loads (of which I'm assuming the block editor counts, see PCYsg-4KT-p2).

We could add the Jetpack/Atomic handling to `apps/wpcom-block-editor`, but the Simple site handling could just go in `admin-plugins` (or, both could be in `apps/wpcom-block-editor` as a big `if/else` type block, but then both platforms will be loading code for both platforms – albeit not very much code).

**Comment by dmsnell** [comment]
As I was reviewing `lib/analytics` to see better understand the obstacles to reusing that existing code vs. duplicating it I came across our privacy logic for things like GDPR, opt-out, and personally-identifiable information. Are we able to deploy these changes without violating the law? Are we asserting that privacy matters will have been dealt with by the time we load the editor? Will we prevent editing posts if we have Jetpack installed but a customer hasn't opted-in to our tracking?

**Comment by jsnajdr** [comment]
Merging after consulting with @kwight 🚢

**Comment by scruffian** [comment]
Thanks for merging. This was nice to come back to!

**Comment by vindl** [comment]
Just a note that this was deployed on Dotcom yesterday as part of D28968-code.

**Pull request merged**
