### PR TITLE
Update: Replace site.user_can_manage with site.capabilities && site.capabilities.manage_options

### PR DESCRIPTION
**Pull request by enejb**
We are planning to remove user_can_manage from the endpoint.

To test:
??
Run the API test. Browse though the the admin and try to see if anything is broken. 

cc: @lezama and @mtias

### CODE REVIEW

**Comment by mtias** [comment]
Nice, thanks for this. I'll let @lezama give it a go ;)

**Comment by lezama** [comment]
Thanks Enej! :+1: 

We could use the `userCan` helper( https://github.com/Automattic/wp-calypso/blob/master/client/lib/site/utils.js#L7 ) to avoid the all those `site.capabilities && site.capabilities.manage_options`

**Comment by mtias** [comment]
> We could use the userCan

Good call.

**Comment by enejb** [comment]
Just updated the code to use userCan. Thanks for the suggestion!

**Comment by lezama** [comment]
LGTM after rebase :+1:

**Pull request merged**
