### PR TITLE
Center migration overview and hosting features component

### PR DESCRIPTION
**Pull request by andres-blanco**
## Proposed Changes

Horizontally center migration and hosting features overview components on `/sites`. This two screens doesn't look good when left aligned.

**Before**
image

**After**
image

## Why are these changes being made?

The migration overview and the hosting features components rendered in /sites where not centered on big screens. This kind of card layout looks weird if left aligned.

## Testing Instructions

* Apply the change or navigate to the Calypso Live link below
* Go to `/sites` 
* Select a site that's on a free plan
* Verify the hosting features component looks centered on big screens
* For the migration overview follow instructions in [this PR](https://github.com/Automattic/wp-calypso/pull/95963) since the feature is not live yet

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Comment by andres-blanco** [comment]
@nightnei you might want to take a look at this change since you seem to have worked plenty on the HostingFeatures componen

**Review by nightnei — CHANGES_REQUESTED** [review]
@andres-blanco first of all - thanks for the ping.

Such fix looks like workaround, since we are patching default styles, but, max-width is set not in the default styles. So we should adjust the place [where we set limit](https://github.com/Automattic/wp-calypso/blob/trunk/client/sites/components/dotcom-style.scss#L385) of the `max-width: 1400px`.

```

diff --git a/client/a8c-for-agencies/components/items-dashboard/item-preview-pane/item-preview-pane-content/style.scss b/client/a8c-for-agencies/components/items-dashboard/item-preview-pane/item-preview-pane-content/style.scss
index f64d812d5c1..6c128d268eb 100644
--- a/client/a8c-for-agencies/components/items-dashboard/item-preview-pane/item-preview-pane-content/style.scss
+++ b/client/a8c-for-agencies/components/items-dashboard/item-preview-pane/item-preview-pane-content/style.scss
@@ -6,8 +6,4 @@
        overflow-y: auto;
        overflow-x: hidden;
        display: flex;
-
-       &:has( .migration-overview, .hosting-features ) {
-               justify-content: center;
-       }
 }
diff --git a/client/sites/components/dotcom-style.scss b/client/sites/components/dotcom-style.scss
index dfeb1b33d30..ba88dd41ef8 100644
--- a/client/sites/components/dotcom-style.scss
+++ b/client/sites/components/dotcom-style.scss
@@ -414,10 +414,7 @@
                }

                > * {
-                       margin-top: 0;
-                       margin-left: 0;
-                       margin-right: 0;
-                       margin-bottom: auto;
+                       margin: 0 auto auto;
                        padding-top: 0;
                        padding-left: 0;
                        padding-right: 0;
```

@fushar I see that you added max-width to the `.item-preview__content > *`. So I have two questions:
1) Are you ok with adding `margin-left/right: auto`? I think it should makes sense, since if we have it, it means that any block inside of `.item-preview__content` will have the limit of width and as a result with any child block we already have the issue described in this PR.
2) I wonder, we already have `margin-bottom: auto;`, why do we need it? I don't see any styles which could lead to have `auto` for `margin-bottom`. Looks total yredundant.

**Review by fushar — COMMENTED** [review]
Thanks for the ping. The max width (and left-alignment) of the tabs is intentional. See @lucasmendes-design comment here:

https://github.com/Automattic/dotcom-forge/issues/6828#issuecomment-2086983773

This is to prevent "layout jumps" when switching tabs. @lucasmendes-design might have any opinion on this change in this PR?

> I wonder, we already have margin-bottom: auto;, why do we need it? 

I totally forgot 🤦 it was carried over from A4A code, so *maybe* it was just a copy-paste.

**Comment by nightnei** [comment]
@fushar oh, I see, it seems we should close this PR, thanks for the answers and for pinging @lucasmendes-design

**Comment by andres-blanco** [comment]
@nightnei I would like to hear @lucasmendes-design feedback before closing this PR. While the solution proposed might not be the best, I still feel there's an issue with the look of the content of `/sites` when it uses a card layout.

**Comment by lucasmendes-design** [comment]
Correct me if I’m wrong, but I believe the common pattern we’re following is to left-align all content within the tabs. I get that this specific page has a more centralized layout, so left-aligning may feel a bit off. My bad on this design choice 🙃 sorry about that. That said, I’d keep it left-aligned for consistency. We'll be revisiting all empty states soon, so we’ll have a chance to design something that fits even better.

**Comment by andres-blanco** [comment]
Thanks for the extra context Lucas. 
Closing this because left alignment is a [design choice](https://github.com/Automattic/wp-calypso/pull/96252#issuecomment-2477012208).

**Comment by lucasmendes-design** [comment]
I'm pinging @matt-west in case you want to double-check and propose changes here :)

**Pull request closed without merging**
