### PR TITLE
Playwright: incorporate coupon test path into Plans: Purchase spec.

### PR DESCRIPTION
**Pull request by worldomonation**
#### Changes proposed in this Pull Request

This PR integrates the coupon test path exercised by Selenium suite's `wp-plans__viewing` spec into `Signup: Paid` spec.

Furthermore, this PR removes migrated tests.

Key changes:
- integrate the coupon test path into the `Signup: Paid` spec.
- remove specs from Selenium suite, including `wp-plans__viewing` where the test path above originates.

#### Testing instructions

- [x] tests
  - [x] mobile
  - [x] desktop

### CODE REVIEW

**Comment by worldomonation** [comment]
Selenium failure are due to removal of many tests in this PR; TeamCity marks a test as failed if a push results in less tests passing, under a certain threshold.

**Review by dpasque — APPROVED** [review]
I think the changes here look good, approving!

Wanted to throw out a question though (that I realize may be unhelpful at this point) - do we need the coupon tests both here _and_ in the paid signup specs? 

I kinda feel like we should have just one place that tests coupons, and that should have all the flows we wanted to do. That would keep the specs more simple and focused, and avoid any over testing. We could make that one place one of the existing places we have, or we could break that out into its own spec.

We definitely don't have to do that now, just wanted to throw that out there!

**Comment by worldomonation** [comment]
@dpasque 
> - do we need the coupon tests both here and in the paid signup specs?

It's a good question for sure :) I think it's necessary to have it in both, because this path also tests the removal of coupons from the cart item - which the other one does not do.

Now an argument can be made to apply then remove the coupon code in the `Signup: Paid` spec too, and that would be simpler and less overtesting. I will have to think about that.

Edit: I've moved the coupon code removal testing to `Signup: Paid` suite.

**Comment by worldomonation** [comment]
I'm going to go ahead and merge this for now, and if the location of the coupon application/removal needs to be modified we can do that later down the line.

**Pull request merged**
