### PR TITLE
Third-Party Premium Themes: Adding marketplace theme products

### PR DESCRIPTION
**Pull request by valterlorran**
#### Proposed Changes

Context: paYKcK-2ke-p2

D91040-code

* Add the `marketplaceThemeProduct` function to generate a marketplace product to be added to the card.

#### Testing Instructions

This function is not being used yet.

Related to #69468 #69480 #69616

### CODE REVIEW

**Review by sirbrillig — APPROVED** [review]
Looks good from a Payments perspective!

**Comment by mreishus** [comment]
Does this mean we'll have to a keep a list of marketplace themes in calypso in sync with what's in the payments database?
https://github.com/Automattic/wp-calypso/blob/9b422778b1e8402f06612b3b5efe549c59fe4b8e/packages/calypso-products/src/constants/marketplace-themes.ts#L3

**Comment by valterlorran** [comment]
> Does this mean we'll have to a keep a list of marketplace themes in calypso in sync with what's in the payments database?

Yes, I completely lost the context of this, but tomorrow I'll try to find the conversation we discussed.

**Comment by valterlorran** [comment]
@mreishus I couldn't find much information about it. But my understanding is that this information does not come from the backend, and we need it hardcoded to make validations on the front end.

p1667213438908009/1667213191.654849-slack-C0Q664T29

**Comment by DavidRothstein** [comment]
I'm not sure why a separate hardcoded list would be needed in Calypso -- aren't there supposed to be ways to identify these via the API data from the server (for example, the product type would be `marketplace_theme`, or at least that's what was proposed in D91040-code)?

**Comment by valterlorran** [comment]
@DavidRothstein @mreishus I talked with Dale, and you are right. I removed the constants and the code that was going to use it. I only left a function we'll still need to allow us to add the marketplace products to the cart.

**Review by mreishus — APPROVED** [review]
Function does what it says on the box - Turn a product slug into a MinimalRequestCartProduct

**Pull request merged**
