### PR TITLE
Updates Scan page wording for states

### PR DESCRIPTION
**Pull request by ChaosExAnima**
#### Changes proposed in this Pull Request

* Adds better text for the `provisioning` state.
* Removes `unavailable` state as the `ScanUpsell` component covers it.

#### Testing instructions

* On a site with Scan, alter the scan state to be `provisioning`.

#### Screenshot
Screen Shot 2020-05-11 at 12 18 25 PM

Fixes 1151678672052943-as-1175196271951194.

### CODE REVIEW

**Comment by enejb** [comment]
This looks good to me. Lets ship it!

**Comment by michelleweber** [comment]
I don't understand what this copy is trying to communicate, and I think it creates more questions than it resolves at the moment. Let's change that! Questions to try and clarify:

- Does "we're taking a first look" mean "we're starting the first scan," or something else?

- Does "the results will be with you soon" mean "the results of whatever this first look is doing will be ready soon" or "the first scan will be done soon"?

- What are these results? Where will these results be available? On this page? Will I get an email?

**Comment by ChaosExAnima** [comment]
@michelleweber - Thank you for those great questions!
> Does "we're taking a first look" mean "we're starting the first scan," or something else?

It means Jetpack Scan is getting ready to take the first scan of a site.

> Does "the results will be with you soon" mean "the results of whatever this first look is doing will be ready soon" or "the first scan will be done soon"?

It means that the setup finishes soon, and then the site will be scanned. If there is an issue, we will email you. @enejb, do you know if the first successful scan triggers an email as well?

> What are these results? Where will these results be available? On this page? Will I get an email?

If there's a threat (hack, security issue, etc.), it will update here as well as send you an email. If there's no threat, it will show here. Regardless, no user action needs to happen.

**Comment by enejb** [comment]
> It means that the setup finishes soon, and then the site will be scanned. If there is an issue, we will email you. @enejb, do you know if the first successful scan triggers an email as well?

It should but we are not there yet.

**Comment by michelleweber** [comment]
Super helpful, thanks. I'm thinking something like:

Preparing to scan
Welcome to Jetpack Scan! We're scoping out your site, getting set up to take the first full scan. We'll let you know if we spot any security issues, and then your first scan will start.

**Comment by ChaosExAnima** [comment]
@michelleweber - Can I propose something like:
> Welcome to Jetpack Scan! We're scoping out your site, getting set up to take the first scan. We'll let you know if we spot any security issues!

We let users know if there are security issues _after_ the first scan, not before.

**Comment by michelleweber** [comment]
> It means that the setup finishes soon, and then the site will be scanned. If there is an issue, we will email you.

What kind of issues would we see at this point?

And now that I'm asking -- does the actual scan start automatically when this pre-scan is done? That'd be nice to add.

**Comment by ChaosExAnima** [comment]
> What kind of issues would we see at this point?

We'd see issues as in security threats such as vulnerable plugins or suspicious code. We'd also notify if the system couldn't set things up like the site is down.

> And now that I'm asking -- does the actual scan start automatically when this pre-scan is done? That'd be nice to add.

Yes, we'd do an initial scan automatically.

**Comment by michelleweber** [comment]
Thoughts?:

Preparing to scan

Welcome to Jetpack Scan! We're scoping out your site, setting up to do a full scan. We'll let you know if we spot any issues that might impact a scan, then start your first full scan will start.

**Comment by ChaosExAnima** [comment]
Alrighty! I've updated the wording and can now merge once tests pass. Thanks all!

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/3626605

Thank you @ChaosExAnima for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/3626605).

**Pull request merged**
