### PR TITLE
Support Chat: Make it visible when customizer is open

### PR DESCRIPTION
**Pull request by jasmussen**
This PR makes the support chat visible when the customizer is open. Both in docked sidebar, and panel mode.

Screenshots:

screen shot 2016-10-24 at 19 19 55

screen shot 2016-10-24 at 19 19 59

To test:

- Open support chat
- Open the customizer
- Verify the chat is still there

### CODE REVIEW

**Comment by kriskarkoski** [comment]
Is there a concern about the double-sidebar showing the site preview more narrow than it should be? Should we always force it to show in the corner-panel mode in the Customizer?

**Comment by jasmussen** [comment]
> Is there a concern about the double-sidebar showing the site preview more narrow than it should be? Should we always force it to show in the corner-panel mode in the Customizer?

We could force it to be panel only mode, technically. But I think the value of not switching around the layout of the chat (potentially making you lose your place) outweighs the need for space for the customizer. Besides it's mitigated by our themes being responsive.

**Comment by kriskarkoski** [comment]
> Besides it's mitigated by our themes being responsive.

While the theme will still look okay, it may not look identical to how it would without the chat panel open. We allow the Customizer to be collapsed to get around this so you can preview your site in the same dimensions as the window you're working in, but without a collapse option this wouldn't be possible with Happychat while a user is chatting with us. Not a blocker for beta imo, but maybe something we can improve down the road.

**Comment by johngodley** [comment]
Verified the chat is still visible when the customizer is opened 👍

**Pull request merged**
