### PR TITLE
Reader: Move to the analytics middleware for analytics

### PR DESCRIPTION
**Pull request by blowery**
The goal is to get over to the redux middleware based analytics stuff and off our hand rolled analytics calls. This PR is a spike towards porting reader/analytics over to something that uses and enhances the analytics middleware.

### CODE REVIEW

**Comment by apeatling** [comment]
@bluefuton Could you review this one so we can merge?

**Comment by bluefuton** [comment]
@blowery I notice this was never marked Needs Review - can you remember what was left to do?

**Comment by blowery** [comment]
@bluefuton move everything over I think. And validate that this port was still in sync with `reader/stats`.

**Comment by blowery** [comment]
This still needs to happen, but it's a pretty big project.

**Comment by apeatling** [comment]
@blowery I'm going to close this, but please feel free to reopen once you have made any further updates.

**Pull request closed without merging**
