### PR TITLE
Marketplace: Add Education Footer Bottom Part

### PR DESCRIPTION
**Pull request by Rolilink**
#### Changes proposed in this Pull Request
* Adds Education Footer Bottom Part

#### Testing Instructions
* Navigate to `http://calypso.localhost:3000/plugins/:siteId`
* Scroll down to the bottom
* Footer bottom part should appear with the right content.

#### Screenshots
| Mobile | Desktop |
|--------|-------|
|Screen Shot 2022-03-15 at 11 31 05 PM|Screen Shot 2022-03-15 at 11 30 49 PM|

Related to #61491

### CODE REVIEW

**Comment by Rolilink** [comment]
Blocked waiting for content @SaxonF

**Comment by SaxonF** [comment]
A pass at copy 
image

background colour is `gray.100`

**Review by lsl — APPROVED** [review]
:shipit:

**Review by lsl — APPROVED** [review]

**Comment by vinimotaa** [comment]
Hi @Rolilink, thanks for sharing this!

There's only this details I could see that the paddings are not following the [Design](https://www.figma.com/file/f84fqtCG4pCnCh2Hq0But5/?node-id=590%3A11994) work.

Bellow is an illustration of the padding values we have to fix. After that, it seems all good to me!

image

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/7184216

Thank you @Rolilink for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/7184216).

**Pull request merged**
