### PR TITLE
Color Schemes: Add Powder Snow color scheme

### PR DESCRIPTION
**Pull request by sixhours**
#### Changes proposed in this Pull Request

* Adds a new color scheme to the admin, "Powder Snow".

screen shot 2019-02-01 at 9 55 00 am

#### Testing instructions

* Switch to this PR
* Navigate to `/me/account` and switch color scheme to "Powder Snow"
* Check throughout Calypso for contrast issues and other visual bugs

### CODE REVIEW

**Comment by drw158** [comment]
Unfortunately, we have a lot of variables in the schemes that are duplicated. For example, the warning, error, and success colors are the same across schemes, but they are still defined in each scheme.

**Comment by torres126** [comment]
> Unfortunately, we have a lot of variables in the schemes that are duplicated

Started something in #30535 to address that. :+1:

**Comment by torres126** [comment]
I had a poke round calypso.live and no visual issues stuck out at me! For what it's worth tho, the stats map doesn't seem to work (using Chrome, but an outdated version so maybe it's just me, it works for the other schemes) 

gsfdsdgfdfgsgdf

**Comment by torres126** [comment]
On the topic of stats, the visitors bar does feel much more tricky to see in contrast to the views bar compared to master unless each individual one is focused on. Not sure if that's something which can be handled here though. 

afdsadfsafdsadfs

Contrast: 1.4:1 (https://webaim.org/resources/contrastchecker/?fcolor=3D4145&bcolor=50575D) 

That's the worst I can see and I think and it's a fairly minor issue. :)

**Comment by sixhours** [comment]
@torres126 Thank you for the review!!

> I had a poke round calypso.live and no visual issues stuck out at me! For what it's worth tho, the stats map doesn't seem to work (using Chrome, but an outdated version so maybe it's just me, it works for the other schemes)

It seems to be working for me, but maybe something I updated recently fixed it:

screen shot 2019-02-12 at 2 37 42 pm

> On the topic of stats, the visitors bar does feel much more tricky to see in contrast to the views bar compared to other schemes unless each individual one is focused on. Not sure if that's something which can be handled here though.

This is a really good point, and the result of me trying to be clever with color definitions. 😬 I fixed it in the last commit, and the contrast is much better now.

**Comment by torres126** [comment]
Magic! :o

Map seems to work now and everything looks much better! 

screenshot_20190212-194408

**Comment by drw158** [comment]
This color scheme looks great, and I think it's very faithful to the original Powder Snow design.

Obviously, there are concerns about having black as the color for so many UI elements, but that is the aesthetic nature of this scheme and a choice made by the customer.

I noticed that --color-link did not change with this scheme, and I think it should for all schemes. Notice how it's using the blue from Classic Bright.

screen shot 2019-02-19 at 4 33 14 pm

I don't know if this is a problem, but I noticed that the hex fallback is a different color than the css custom prop. Isn't it suppose to be the same color?

screen shot 2019-02-19 at 4 35 21 pm
screen shot 2019-02-19 at 4 35 43 pm

Don't know what is generating the spark line, but it looks like it is using an old blue.

screen shot 2019-02-19 at 4 37 24 pm

**Comment by sixhours** [comment]
> I don't know if this is a problem, but I noticed that the hex fallback is a different color than the css custom prop. Isn't it suppose to be the same color?

Hmm...I would think so, but I'm not seeing how the fallbacks are being handled. @blowery or @flootr , do you have any ideas?

> Don't know what is generating the spark line, but it looks like it is using an old blue.

I'm unable to see a spark line for any of my sites; is there a specific set of requirements to get it to show?

**Comment by torres126** [comment]
> I'm unable to see a spark line for any of my sites; is there a specific set of requirements to get it to show?

It doesn't appear on the Stats page itself, if you switch to something like the Activity Log, then it appears. 

screenshot_20190221-221703

> Isn't it suppose to be the same color?

I _think_ that the fallbacks are for older browsers and IE11 since it doesn't support variables, and therefore are the Classic Bright ones as that's the only scheme supported. My memory might be wrong on that though, so probably good to confirm.

**Comment by sixhours** [comment]
> Edit: never mind, I just realised I'm not sure if the spark line is the stats bar

The spark line is the stats bar! And it looks like an image: 

https://github.com/Automattic/wp-calypso/blob/59bdfeeb97eda4266ad39410cb0a074d2c88dbc8/client/blocks/stats-sparkline/index.jsx#L37

Not sure how we can change the color; we could add a background for contrast, but ideally we could configure the color to change with the sidebar background.

**Comment by drw158** [comment]
> I _think_ that the fallbacks are for older browsers and IE11 since it doesn't support variables, and therefore are the Classic Bright ones as that's the only scheme supported. My memory might be wrong on that though, so probably good to confirm.

This sounds probable, but the colors I found were neutral, and they don't change across schemes, so I'm wondering why they'd be different.

**Pull request merged**
