### PR TITLE
Framework: Try using requestIdleCallback to schedule serialization during downtimes

### PR DESCRIPTION
**Pull request by blowery**
Just an experiment for now.

### CODE REVIEW

**Comment by blowery** [comment]
Failing the build because of the `console.time` stuff I added. Feel free to try it out and see what kind of timings you get.

**Comment by blowery** [comment]
closing for now. went with increasing the throttle to 1 minute for now instead.

**Comment by aduth** [comment]
Did you mean to close this @blowery (it's still open)? If it had better browser support, this seems like it would be a good option, but Chrome-only is a bit unfortunate.

**Comment by blowery** [comment]
Yup, meant to close it. Thanks for reminding me. :)

We might still want to explore it. It did make the app feel a bit snappier.

**Pull request closed without merging**
