### PR TITLE
Add domains table header sorting

### PR DESCRIPTION
**Pull request by hambai**
In the redesigned domain list we'll allow customers to sort the list by clicking on the table header (or with a select box in mobile view).

NOTE: This is not the final PR because I need to see how the domain item redesign is rendering the domain status in order to make the sorting behave properly. However this PR should be good enough for usability and design review.

#### Changes proposed in this Pull Request

* Update the header component to render the header columns and an arrow next to the active sort key
* Show select box on mobile with all the available sort options
* Implement sorting mechanics ( see #57387 )

Here's how the header looks on desktop and mobile:

header-demo

Screenshot 2021-10-26 at 14 36 57

#### Testing instructions

* Spin up this branch and verify that you see the domains list table header. The header labels should be clickable. The default sort order is by Status but currently ony sorting by Domain ascending/descending works.

### CODE REVIEW

**Comment by poligilad-auto** [comment]
Hey @hambai, looking cool!
Some comments:
1. I imagined it behaving like this on desktop:
Domains-manage
When hovering above a column that is sortable, we would see the arrow pointing down in color var(--color-neutral-10);
When clicking to apply the sort the arrow will change to color var(--color-neutral-50);
So the applied sort icon will be color var(--color-neutral-50);

2. Also I see that all the columns are sortable. @kelliepeterson did we say that we would have sorting for 'domain', 'status' and 'registered until', or should we have sort options for all? 

3. The drop down option on mobile seems 'cut-off' at the end. It just ends in some strange white space.
image

4. Regarding the icon for the drop down in mobile & the arrow icon for desktop: I want us to start using the [same icons](https://www.figma.com/file/e4tLacmlPuZV47l7901FEs/?node-id=8%3A13) as in Gutenberg. I left a similar comment in @leonardost's [PR](https://github.com/Automattic/wp-calypso/pull/57082). I see that he was able to add the Gutenberg icons in [another PR](https://github.com/Automattic/wp-calypso/pull/57126). Should be using this icon:

image

5. Another thing, I was thinking we should hide the sorting options until the user has at least 2 domains, especially for mobile. As it really doesn't do anything. @kelliepeterson?

**Comment by hambai** [comment]
Ah, thank you for commenting on this @poligilad-auto. 

1. Sure we can do that. Actually I created this PR so that we can discusss all those details because there are multipe ways to make this sorting work. I'll update this PR so 
2. We've actually discussed that with @delputnam and @leonardost last Friday and I believe we came to the conclusion that it makes sense to allow sorting by **Domain** (ascending or descending), **Status** (only descending - so domains that need attention are shown at the top. we'll introduce some weight for each status and if there are multiple domains in the same status we'll sort alphabetically) and **Registered until** (only ascending - so the ones that expire soon are at the top). The rest of the columns don't seem to be that useful for sorting. We also discussed that it makes sense that the default sorting should be by the **Status** column. How does all of this sound @poligilad-auto ?
3. Sure, I'll fix it
4. Yeah... I couldn't find this icon in the gutenber icons though - https://gutenberg-icons.tungdu.com/ is what I'm looking at, and I was gonna ask you about it.
5. We've discussed that too and it definitely makes sense to hide the dropdown on mobile if there's only one domain - we'll make it work

**Comment by delputnam** [comment]
> 4\. I couldn't find this icon in the gutenber icons
@hambai I think it's the sort content material icon: https://fonts.google.com/icons?selected=Material%20Icons%3Asort%3A

**Comment by hambai** [comment]
> > 4. I couldn't find this icon in the gutenber icons
> > @hambai I think it's the sort content material icon: https://fonts.google.com/icons?selected=Material%20Icons%3Asort%3A

No wonder I couldn't find that one in the gutenberg icons :D

**Comment by poligilad-auto** [comment]
Thanks @hambai.
2. Sounds perfect to me 👌
4. Silly me.. @delputnam is right, we use Material icons when there are no appropriate Gutenberg ones and I forgot that's one of them.

**Review by leonardost — APPROVED** [review]
This looks really great to me! Tested and it works nicely 👍 

I guess the only thing remaining is to make the mouse cursor `pointer` when passing over the headers.

One other minor thing that I thought was defining constants `ORDER_ASCENDING = 1` and `ORDER_DESCENDING = -1`, but that's very minor.

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/6919036

Thank you @hambai for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/6919036).

**Pull request merged**
