### PR TITLE
WordAds: Point Jetpack and Atomic users to Jetpack settings rather than Marketing.

### LINKED ISSUE #49144: Nav Unification: Atomic - WordAds Unification/WordAds ad placement links need updating.
This is for Atomic sites only.

### Steps to reproduce the behavior

1. Go to Tools - Earn - View Ad Dashboard - Settings - Manage Ad Placements:
image

2. It will take you to Tools - Marketing - Traffic, which gives only two options for adjusting ad placements:
image

3. On Atomic, though, actual ad placement settings are in a different spot. There's a weird workflow on this one, since if you're starting on a Calypso page, these settings will be hidden. To view that, click on Jetpack first, and you'll only have access to Activity Log and Backup.
image

4. Actual Atomic WordAds settings though, are located under Plugins (to get to WP-Admin) - Jetpack - Settings - Traffic:
image

#### What I expected to happen
We need to somehow unify ad options on Atomic. On simple sites, all of the options are under Tools - Earn - View Ad Dashboard - Settings. On Atomic, they're under WP-Admin - Jetpack - Settings - Traffic.

#### What actually happened
A few things:

1. The ad placements options link under Calypso by default is limited, and doesn't include the full suite of customization.
2. Jetpack settings are hidden by default in the OG Calypso menu, and you need to click on Plugins to activate them.
3. The link on Atomic under Tools - Earn - View Ad Dashboard - Settings - Manage Ad Placements needs to go to the Jetpack view (Atomic only), under Plugins (to get to WP-Admin) - Jetpack - Settings - Traffic, OR
4. (3 above, or) The ad placements settings under  Jetpack - Settings - Traffic need to be relocated into Calypso, under  Tools - Earn - View Ad Dashboard - Settings (like on Simple).

### Context
This has been a longstanding issue made worse/more apparent by nav unification, since Jetpack settings are now hidden by default.

Original P2: p9tZKH-7Y-p2

#### Browser / OS version
All.
#### Is this specific to the applied theme? Which one?
All.
#### Does this happen on simple or atomic sites or both?
Atomic.
#### Is there any console output or error text?
No.
#### Level of impact (Does it block purchases? Does it affect more than just one site?)
It affects all WordAds users.

### PR DESCRIPTION
**Pull request by sixhours**
#### Changes proposed in this Pull Request

* Remove JetpackAds settings under Marketing -> Traffic; in my searches this component was only used once and only on this page, so I've removed the component as well.
* Redirect Jetpack and Atomic users to the Jetpack Ads settings when viewing the Ads Settings dashboard.

#### Testing instructions

Switch to this PR and test this flow on the following types of sites:

* WP.com Premium Simple
* WP.com Business Non-atomic
* WP.com Business Atomic
* Jetpack Security Daily

You're looking for changes to how we navigate to WordAds settings:

* Starting at `/earn`, set up a WordAds account for your site.
* If on a WP.com Premium Simple or WP.com Business Non-Atomic site, ads settings will remain under `/earn/ads-settings`

Screen Shot 2021-04-05 at 12 16 39 PM

* If on a WP.com Business Atomic or Jetpack Security Daily site, you'll see a "Manage ad placements" link under Settings:

Screen Shot 2021-04-05 at 12 17 23 PM

* If you click on "Manage ad placements", you should be directed to the Jetpack Traffic Settings under `{site}/wp-admin` for WP.com Business Atomic and Jetpack Security Daily sites:

Screen Shot 2021-04-05 at 12 15 23 PM

Fixes #49144

### CODE REVIEW

**Comment by kwight** [comment]
> This begs the question, should we just redirect all Jetpack users to the Jetpack Ads settings in /wp-admin rather than only Atomic folks? 🤔 It seems a little silly to differentiate when the Jetpack settings are much more robust.

This seems to make sense when you explain it like that – @obenland @jeherve do you have any ideas of why this _wouldn't_ be a good idea?..

**Comment by sixhours** [comment]
Another (much more involved) option is to introduce full parity between the Jetpack Ads settings and the Marketing/Tools Ads settings, but I'm not sure that's what we're going for as a fix.

**Review by kwight — APPROVED** [review]
All instructions checked out, makes sense, and code looks good. Let's wait and see what others say, but this is ready to merge as-is.

**Comment by jeherve** [comment]
cc @dbspringer who knows WordAds better than anyone and who can weigh in on this. :)

**Comment by dbspringer** [comment]
I'm going to direct this to @cphilleo since he's taken over after I switched to the Hiring team.

**Comment by cphilleo** [comment]
> Another (much more involved) option is to introduce full parity between the Jetpack Ads settings and the Marketing/Tools Ads settings, but I'm not sure that's what we're going for as a fix.

This has been the plan from the Ads team side, but lack of resources has pushed it off. In retrospect, it makes more sense to me to just drop the Marketing->Traffic->Ads settings page completely — as it's redundant and has less features than Jetpack Ads settings. It will be one less thing to maintain.

> This begs the question, should we just redirect all Jetpack users to the Jetpack Ads settings in /wp-admin rather than only Atomic folks? 🤔 It seems a little silly to differentiate when the Jetpack settings are much more robust.

I think this is the best option. Redirect all Jetpack users to the Jetpack Ads settings.

**Comment by kwight** [comment]
Adding a JN site to AdWords still has me on this settings page, which is what I shouldn't see, correct? Does it need to redirect or something, and get the confirmation on the wp-admin side? I don't even know if that's possible. 🤔 

Screen Shot 2021-04-09 at 7 33 53 AM

**Comment by sixhours** [comment]
> Adding a JN site to AdWords still has me on this settings page, which is what I shouldn't see, correct? Does it need to redirect or something, and get the confirmation on the wp-admin side? I don't even know if that's possible. 🤔

That's weird, I'm seeing the Manage Ad Placements link instead of the settings, as expected, on my JN site:

Screen Shot 2021-04-09 at 11 04 40 AM

What flow did you use to get that screen? I did Tools -> Earn -> Clicked Earn ad revenue -> Clicked signup -> Was brought to the above screen. Wonder if there's another path I'm missing.

**Comment by mreishus** [comment]
I tried with a JN site and I'm not seeing what @kwight is seeing. Notably, my site never had Nav Unification menus, only calypso-style menus, but I'm seeing them in Kirk's screenshot. That might be the source of the difference?


It my debugging, it's failing [the check that disables nav unification for all Jetpack sites](https://github.com/Automattic/wp-calypso/blob/6f96ecd660e97e3028b205b4fb5b3974a4a7cf07/client/state/selectors/is-nav-unification-enabled.js#L28-L32). (But this may be removed in a future version of nav unification).

I also tested on calypso.live instead of localhost calypso and saw the same thing (Calypso style menus instead of Nav unification menus)

**Comment by kwight** [comment]
I tried it again today with a fresh JN site – no Nav Unification menus, and the correct "Manage Ad Placements" link showed up. I think we're good.

**Review by kwight — APPROVED** [review]

**Pull request merged**
