### PR TITLE
Add/Login via the mobile app 2FA notice

### PR DESCRIPTION
**Pull request by zwarm**
#### Proposed Changes

This change adds a static notice message to the "Login via the mobile app" page to alert users that the feature is not available if they have enabled 2FA on their account. This new message needs translation.

Screen Shot 2022-10-11 at 11 18 40 AM

#### Testing Instructions
Navigate to the log in page
Click on "Login via the mobile app"
✅ Verify that the notify message "Login via the mobile app is not available if you've enabled two-step authentication on your account" is shown

#### Pre-merge Checklist
- [x] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes? N/A
- [x] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [x] Have you checked for TypeScript, React or other console errors?
- [x] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [x] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?

### CODE REVIEW

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/7575284

Thank you @zwarm for including a screenshot in the description! This is really helpful for our translators.

**Review by momo-ozawa — APPROVED** [review]
LGTM, but I'll defer to @gmovr for guidance on the pre-merge checklist / deploying. Thanks!

**Comment by zwarm** [comment]
@gmovr - Thanks again for lending a hand with the review. I'm 🤞 that all is good.
How long does it usually take for a string to be 100% translated and do we wait until it is before merging/deploying?

**Comment by gmovr** [comment]
> @gmovr - Thanks again for lending a hand with the review. I'm 🤞 that all is good. How long does it usually take for a string to be 100% translated and do we wait until it is before merging/deploying?

Hey! We need to wait for all strings to be translated prior to merging. If we merge it now, we'd show untranslated strings to certain users. 

I believe translations go out on Mondays, and they're back within 7-10 days. You can check the status by clicking "Details" in the "ci/i18n" check. Once translations are in, that check will pass. 

When the strings are in (I see you've had it reviewed by another team member), you can go ahead and deploy it per the FG article, by squash-mergin to trunk and following the guide here: PCYsg-5XR-p2. Feel free to reach out (or post in the `#calypso` channel) when you're ready to deploy, and we (or another engineer) can wrangle it together. :)

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/7575284).

**Comment by zwarm** [comment]
@gmovr - 👋 Maybe you can help one more time ... the Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/7575284)., but CI/i8N says 94%. I'm going to assume I need to wait for 100%, correct? And I do need to kick off CI again? And when do I remove the "string freeze" label? Thanks

**Comment by enejb** [comment]
I think it would have been good to get this check over by designers before we merge it. cc: @shaunandrews 

I am not sure that the h4 element is the correct one to use for this notice.
Also I am not 100% sure that using the red icon is the way to go here since it draws too much attention 🤔 

If we do go with that this wording might be good to include the icon in the translation so that the icon can appear in the correct place since LTR languages might want to place it in a different spot then the current location. 

You can see the translation here. 
https://translate.wordpress.com/projects/wpcom/-all-translated/848480/

but I am not sure why we don't see them appear when viewing the page now. 

Such as when I visit https://container-angry-tu.calypso.live/log-in/qr/de

**Comment by shaunandrews** [comment]
@paulforgione Maybe you can pick this up?

**Comment by paulforgione** [comment]
Hey @zwarm – sorry I missed this the first time around, and thanks for the reminder when we were in person!

I think this looks pretty good, I just have a few _minor_ tweaks I'd like to suggest:
MVP
If we want to ship ASAP with minimal tweaks, I would suggest:
- using `--color-warning` (studio-yellow-50) rather than red for the icon, since this is something that _may_ concern the user, not an error state _yet_.
- changing the icon out from the filled exclamation icon to the stroked `i` icon

These changes do tone down the contrast for users, but we want to balance making sure users who are stuck on this screen will notice the message if they're having difficulty logging in.

I came up with a second version using a filled background and the same colors. I feel this helps communicate that this is separate from the login instructions above, without stealing the users attention:
V2

Let me know if the simpler approach will cause any issues in implementation, or if you'd like to discuss the 2nd proposed solution!

**Comment by zwarm** [comment]
@paulforgione - Thanks for the look around and suggestions. I'll implement the second version with the filled background. 🙇

**Comment by zwarm** [comment]
I have no idea what I did, but there are 1000+ commits added from a failed rebase + merge. I am abandoning this PR so I don't introduce something terrible and will open a new PR.

**Pull request closed without merging**
