### PR TITLE
Webpack: Use a root instead of a module directory for client

### PR DESCRIPTION
**Pull request by blowery**
This shaves about 10s off of the initial build on my laptop. See https://github.com/webpack/webpack/issues/1574#issuecomment-157520561 for details on why this might help.

### CODE REVIEW

**Comment by scruffian** [comment]
This reduces the build from 121 seconds to 85 :+1:

**Comment by umurkontaci** [comment]
Docs says that we can also use an `array` for the value of `root` prop. Does `root: [ path.resolve( __dirname, 'client' ), path.resolve( __dirname, 'node_modules' ) ],` make it faster?

Also, CI has failed.

**Comment by blowery** [comment]
> Also, CI has failed.

yeah, just a timeout.

**Comment by blowery** [comment]
for the record, here's what i see between master and this branch:

```
master:
87852ms
90561ms
87710ms

with-root:
74007ms
77070ms
73130ms
```

**Comment by blowery** [comment]
> Docs says that we can also use an array for the value of root prop. Does root: [ path.resolve( __dirname, 'client' ), path.resolve( __dirname, 'node_modules' ) ], make it faster?

Yeah, but that's not what appears to be typical usage... The default for modulesDirectories is `node_modules`... 

Trying it anyway :)

**Comment by blowery** [comment]
Hrm. 

```
with-root-and-node-modules-in-root:
88203ms
87731ms
95266ms
```

Weird.

**Comment by blowery** [comment]
Chatted with the desktop folks and this checked out there too. Landing it.

**Comment by umurkontaci** [comment]
:+1: Maybe if the default value of `modulesDirectories` was `[node_modules]`, it was passing some folders twice? Anyway, I think it's a quick & big win; so yay!

**Pull request merged**
