### PR TITLE
Rewind Credentials: Shuffle props around

### PR DESCRIPTION
**Pull request by dmsnell**
This is part of a mini-project to untangle data flows within the
Activity Log and Rewind system so that each component operates more
independently of its parents and can be worked on in isolation.

Many of the props and callbacks relevant to Jetpack Rewind credentials
get passed down through multiple chains of React component props. In
this patch we're disconnecting some of those parent-child relationships.

This is preparatory work further to deprecate and eventually remove code
dependent on the older and also-deprecated Rewind APIs, preferring
instead to move to the specified and centralized "state machine" API

**There should be no visual changes in this PR from master**

**Testing**

Since this patch impacts Jetpack Rewind credentials, navigate to
**My Sites** > **Settings** > **Security** for a site with a Jetpack
connection and also one which can activate **Rewind**. Try activating
auto-credentials and revoke credentials, try adding custom credentials.
Make sure everything works as expected.

### CODE REVIEW

**Comment by enejb** [comment]
When I am on testing this PR I ended up with a white screen. 
To replicate it go to 
Settings -> Click on Add site credentials. 
Then Click on "ok I understand."

the error that I see in the console is 
```
The above error occurred in the <SetupForm> component:
    in SetupForm (created by Connect(SetupForm))
    in Connect(SetupForm) (created by CredentialsSetupFlow)
    in div (created by CredentialsSetupFlow)
    in CredentialsSetupFlow (created by Localized(CredentialsSetupFlow))
    in Localized(CredentialsSetupFlow) (created by Connect(Localized(CredentialsSetupFlow)))
    in Connect(Localized(CredentialsSetupFlow)) (created by Backups)
    in div (created by Backups)
    in Backups (created by Localized(Backups))
    in Localized(Backups) (created by Connect(Localized(Backups)))
    in Connect(Localized(Backups)) (created by SiteSettingsSecurity)
    in main (created by Main)
    in Main (created by SiteSettingsSecurity)
    in SiteSettingsSecurity (created by Localized(SiteSettingsSecurity))
    in Localized(SiteSettingsSecurity) (created by Connect(Localized(SiteSettingsSecurity)))
    in Connect(Localized(SiteSettingsSecurity))
    in div (created by Layout)
    in div (created by Layout)
    in div (created by Layout)
    in Layout (created by Connect(Layout))
    in Connect(Layout) (created by ReduxWrappedLayout)
    in Provider (created by ReduxWrappedLayout)
    in ReduxWrappedLayout

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://fb.me/react-error-boundaries to learn more about error boundaries.
index.jsx:97:4
TypeError: undefined has no properties
[Learn More]
```

**Comment by dmsnell** [comment]
Thanks @enejb! I found and fixed that bug in 3d9221e61e

It didn't appear in my tests because I failed to test the case where we can't auto-configure the site. Good spotting!

**Comment by enejb** [comment]
So for my AT site I can see this now 
screen_shot_2018-01-16_at_10_41_06_am

In current master this is what I see. 
screen shot 2018-01-16 at 10 44 51 am

Other then that I think it worked well. One thing that I haven't tested is configuring an SSH of FTP connection.

**Comment by dmsnell** [comment]
This got too expansive and the bugs you noticed @enejb I think are hard to reason about. I'm going to close this and create other PRs to make smaller steps.

**Pull request closed without merging**
