### PR TITLE
Plans 2023: Add Donations and Tips feature to grids

### PR DESCRIPTION
**Pull request by jeyip**
Related to https://github.com/Automattic/martech/issues/1744

## Proposed Changes

* Add the Donations and Tips feature
* Add tooltip text on hover `Allow your audience to support your work easily with donations and tips.`

## Testing Instructions

1. Check out this branch and run `yarn` and `yarn start` if needed. 
2. Navigate to the 2023 pricing grid in onboarding http://calypso.localhost:3000/start/plans
3. Verify that the `Donations and tips` line item is shown in the feature grid under the Free plan column. Verify that the feature tooltip is still rendered on hover
4. Verify that that the Donations and Tip line item is categorized under `Growth and Monetization Tools` in the comparison grid. Verify that the feature tooltip is rendered on hover and that there is a check mark for every column.
5. Navigate to the 2023 pricing grid in the plans page http://calypso.localhost:3000/plans/{SITE_SLUG}
6. Repeat step 3 and 4

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

**Comment by jeyip** [comment]
**Note:**

Currently in the process of updating the plans comparison grid

**Comment by lucasmendes-design** [comment]
All good to me :) Thanks

**Review by aneeshd16 — APPROVED** [review]
LGTM! Let's send this for translation. :shipit:

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/8041603

Thank you @jeyip for including a screenshot in the description! This is really helpful for our translators.

**Comment by lucasmendes-design** [comment]
All good to me. Thanks 😃

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/8041603).

**Pull request merged**
