### PR TITLE
Update text colors to a darker tone of gray for accessibility purposes.

### LINKED ISSUE #58279: Plugin Details: Label color is hard to read
### Details

The gray labels are pretty hard to read given the font size and color. They’re [even failing WCAG AA](https://href.li/?https://webaim.org/resources/contrastchecker/?fcolor=787C82&bcolor=FFFFFF). Could they be darkened up a bit to make that easier?

image

### Checklist

- [ ] (my proposal) Let's replace all instances of `var(--studio-gray-40)` and `var(--studio-gray-50)` with `var(--studio-gray-60)`

cc: @SaxonF 

### Related

pdh6GB-6h-p2#comment-315

### PR DESCRIPTION
**Pull request by WBerredo**
#### Changes proposed in this Pull Request

* Update light text colors on the Plugin Details page to a darker tone of gray (Gray 60) for accessibility purposes.

#### Testing instructions

* Go to `/plugins` page
* Select a plugin
* Check if the texts on the page offer enough contrast with the background

Screen Shot 2021-11-29 at 05 47 36
---

Fixes #58279

### CODE REVIEW

**Comment by gavande1** [comment]
Thanks, @WBerredo for working on this. I think that the color of the title and value looks similar after using `--color-neutral-60`. They looked almost the same to me. 

I would recommend using `--studio-gray-90` (preferred) or `--studio-gray-80` for the values so that they look different.

PR Changes              |  Proposed
:-------------------------:|:-------------------------:
  |   

@cpapazoglou Do you have any different opinions on it?

**Comment by cpapazoglou** [comment]
I don't have any personal preference here, I would delegate the decision to @SaxonF

**Comment by SaxonF** [comment]
Looks good to me! Would be nice to eventually standardise on a metadata pattern like this

**Review by cpapazoglou — APPROVED** [review]
LGTM!

**Pull request merged**
