### PR TITLE
Update socket.io and socket.io-client to 2.1.1

### PR DESCRIPTION
**Pull request by mhsdef**
This change brings us to the latest version. Per `audit`, it also closes up some stuff nicely:

`found 75 vulnerabilities (28 low, 33 moderate, 14 high)`
`~/c/wp-calypso (update/socket.io-to-2.1.1)> npm install socket.io-client@2.1.1 --save`
`found 68 vulnerabilities (25 low, 32 moderate, 11 high)`
`~/c/wp-calypso (update/socket.io-to-2.1.1)> npm install socket.io@2.1.1 --save`
`found 53 vulnerabilities (17 low, 31 moderate, 5 high)`

### CODE REVIEW

**Comment by hewsut** [comment]
***Note: We need to merge the Happychat serverside part of this before we merge this PR.***

**Comment by blowery** [comment]
Yesssssssss! Thanks for taking this on!

**Comment by hewsut** [comment]
I'm working through the HC side in parallel. ETA on stuff over there...hopefully today. Once that lands we can put this one through if it looks good.

**Review by beaucollins — APPROVED** [review]
I was able to chat fine via HUD staging.

**Comment by blowery** [comment]
Woohoo! Thanks!

**Pull request merged**
