### PR TITLE
Hide mobile app banner if ToS update banner is shown

### PR DESCRIPTION
**Pull request by mmtr**
#### Changes proposed in this Pull Request

Follows up #39297 

The ToS update banner is displayed in the same position as the mobile app banner. Since the ToS update has higher priority, we repress all other non-essential sticky banners like the "open in app" one if the ToS update banner needs to be displayed.

Before | After
--- | ---
Screenshot 2020-02-07 at 12 07 18 | Screenshot 2020-02-07 at 12 15 54

#### Testing instructions

* Make sure you don't have ToS marked as accepted. See D38262-code for instructions on how to reset ToS acceptance.
* If you've dismissed the mobile app banner in the past, bring it back by running the following line in your browser console:
```js
dispatch( { type: 'PREFERENCES_SET', key: 'appBannerDismissTimes', value: null } );
````

* Toggle the device toolbar in your browser devtools and select "Responsive". Adjust the width to less than 300px.
Screenshot 2020-02-07 at 12 24 12
Screenshot 2020-02-07 at 12 24 30

* Open the network conditions tab (it is under the "more tools" option) and select an iOS or Android user agent.
Screenshot 2020-02-07 at 12 26 46

* Load the reader in Calypso and note how the mobile app banner is behind the ToS update banner and slightly visible on the top.
* Switch to this branch and reload the reader.
* Make sure the mobile app banner is not displayed.
* Accept the ToS.
* Make sure the mobile app banner is displayed now.

### CODE REVIEW

**Comment by nsakaimbo** [comment]
@mmtr Seems there's an issue building with wp-desktop:

```
Wrote CSS to /home/circleci/wp-desktop/calypso/public/editor.css
Wrote CSS to /home/circleci/wp-desktop/calypso/public/directly.css
events.js:200
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at ChildProcess.target._send (internal/child_process.js:806:20)
    at ChildProcess.target.send (internal/child_process.js:676:19)
    at ChildProcessWorker.send (/home/circleci/wp-desktop/calypso/node_modules/jest-worker/build/workers/ChildProcessWorker.js:286:17)
    at WorkerPool.send (/home/circleci/wp-desktop/calypso/node_modules/jest-worker/build/WorkerPool.js:32:34)
    at Farm._process (/home/circleci/wp-desktop/calypso/node_modules/jest-worker/build/Farm.js:129:10)
```

([link](https://circleci.com/gh/Automattic/wp-desktop/53403))

Any idea what's driving the error?

**Comment by kwight** [comment]
@nsakaimbo Doesn't look related, but I rebased to see if it helps at all.

**Comment by nsakaimbo** [comment]
@kwight @mmtr Yep - just checked and the error is a result of an earlier merge to master (i.e. not this PR). Opened issue #39323.

**Comment by kwight** [comment]
@nsakaimbo maybe it was related to the Node 12.15.0 update? Suspicious timing.

**Comment by nsakaimbo** [comment]
@kwight Yeah it's really odd. I tried building in a separate branch with a more recent SHA and it seemed to work. (Side note: I could be imagining things but I _think_ the build is a little slower now with 12.15.0.)

I'm closing the issue for now but will continue to monitor. Hoping it somehow resolved itself and that it's not some sort of race condition.

**Comment by mmtr** [comment]
The error is back after a new rebase. I have no idea what's causing it, it doesn't seem related to these changes.

**Comment by mmtr** [comment]
> The error is back after a new rebase. I have no idea what's causing it, it doesn't seem related to these changes.

I tried using `globalThis` rather than `window` in my last commit and the build is passing now.

**Comment by mmtr** [comment]
> Here is how your PR affects size of JS and CSS bundles shipped to the user's browser

Hm, this doesn't seem correct. @Automattic/team-calypso is this data accurate? If so, where are this bundles size changes coming from? I don't think changes on this PR can affect so drastically.

**Comment by mmtr** [comment]
> Hm, this doesn't seem correct. @Automattic/team-calypso is this data accurate? If so, where are this bundles size changes coming from? I don't think changes on this PR can affect so drastically.

Seems this is caused by a [wrong `icfy-stats` build](https://circleci.com/gh/Automattic/wp-calypso/596287) and we can ignore this report. See p1581500549303300-slack-calypso.

**Pull request merged**
