### PR TITLE
Don't send the payload to request privacy and unlocking.

### PR DESCRIPTION
**Pull request by delputnam**
Sometimes the `unlock` and `disable_privacy` options in the payload can be out of sync with the actual state of the domain at the registrar. We will now always check these states on the back end when this endpoint is called, so there is no longer any need to send them in the payload.

This PR is dependent on D12287-code.

Testing instructions in the diff.

### CODE REVIEW

**Comment by delputnam** [comment]
@klimeryk So, those are updated in the reducer when the action is called and are used to determine which of those components should be shown (locked or unlocked). They are used to manage the internal state of the application, so I thought we should leave them there. ...or am I thinking about this wrong?

**Comment by klimeryk** [comment]
Bah, my bad, you're right 🤦‍♂️ Though, from my experience that data is stale and confusing. But that's a different issue. Thanks for verifying this and sorry for the noise.

**Comment by aidvu** [comment]
I believe he meant the `unlock/disablePrivacy` vars we pass to the `options`, since you removed them now?

**Comment by delputnam** [comment]
@aidvu I removed the `unlock/disable_privacy` vars that we send from `undocumented`. But I think that @klimeryk was referring to the corresponding variables in that `options` object that are filled with the state of the domain when `fetchWapiDomainInfo` is called. These are used to determine which component (locked or unlocked) to show when you go to the transfer out screen.

**Pull request merged**
