### PR TITLE
Explore: Use CSS loaders in webpack

### PR DESCRIPTION
**Pull request by dmsnell**
See #26308 - this should coordinate with the work that @blowery is doing

> **Current status:** playing around, not ready for real review

Previously we have been building CSS as a separate process to
our app build - we call `node-sass` and `rtlcss` and friends
through our build scripts.

This means that our CSS is unaware of the app's dependency graph
and we are stuck with pre-defined bundles.

We would like to be able to build CSS modularly so that we can
load more granular chunks as they are needed by the app, so that
`webpack` can manage the loading and dependencies.

This PR is an exploration/spike to figure out what pain-points
we will hit in making this work.

### CODE REVIEW

**Comment by blowery** [comment]
@dmsnell I'm dropping the CSS loader work in #26308 so we can focus on it here.

I think we need to change how we build the script tags for chunk assets to look for css modules now too... That's like the css-inserted-as-script weirdness I was seeing yesterday.

**Comment by dmsnell** [comment]
@blowery I'd like to explore making _all_ imports have explicit paths too - not sure how you feel. for _styles_ it seems especially important so that we don't end up trying to treat JS as CSS/SASS, but at the same token, what do we really gain by turning `components/button/index.jsx` into `components/button`?

do you think there's a reason not to codemod everything to explicit paths?

**Comment by blowery** [comment]
> do you think there's a reason not to codemod everything to explicit paths?

it's just not how most js projects work. I never see full paths on other projects. It's always minus the extension.

**Comment by dmsnell** [comment]
> it's just not how most js projects work. I never see full paths on other projects. It's always minus the extension.

I _think_ that "how most js projects work" is that they are broken 🙃 

also, because I think we have to pull in a famous name to raise a point about JS I will call on Ryan Dahl's sixth regret about node's design: `require("module") without the extension ".js"`

so I jest some here but I guess what I'm really asking is not whether this is idiomatic of the node world (because that's clear) but whether you think there are benefits that outweigh breaking from that norm.

already we find code with a mixture of import suffixes because of things like `.scss` and `.svg` and all. also, do you think it's adding that much developer burden to have import paths point to something that really exists vs something that exists in the abstract only?

why?

just for the process of making this transition easier, of avoiding having to do things like rename files or add to the path in order to prevent the overlap of JS and SCSS causing confusion.

**Comment by jsnajdr** [comment]
> do you think there's a reason not to codemod everything to explicit paths?

Please don't do this without a really strong reason. What are the other options to solve the problem of "accidental import of JS file by importing `a/b/c` inside a SCSS file"? And is it really a problem? Doesn't the build immediately crash when reading a JS file accidentally instead of SCSS? If not, is there a way to make it crash?

**Comment by dmsnell** [comment]
> Doesn't the build immediately crash when reading a JS file accidentally instead of SCSS? If not, is there a way to make it crash?

yeah the build fails which is the problem. it pops up when we have `index.js` and `index.scss` in the same directory and then the CSS loaders for some reason pick `index.js` because we import `index` and not `index.scss`.

> without a really strong reason

do we even have a really strong reason to butcher the import paths? or is it just "because that's what all the cool kids do"?

**Comment by blowery** [comment]
The current SASS / JS overlap issue is covered in https://github.com/webpack-contrib/sass-loader/issues/556

I'm fine with importing sass with an extension.

**Comment by jsnajdr** [comment]
> do we even have a really strong reason to butcher the import paths?

I'm not a language designer, but here's a pattern I see across many programming languages: the "thing" that is being imported is not a file, but something more generic, a "package" or "module". Even the good old C++ prefers `#include <vector>` these days and omits the `*.h` extension.

The "symbolic" module name is an encapsulation mechanism -- it hides the internal implementation. The module can be JavaScript, WebAssembly binary or any other language. That fact is not revealed in the module name. Only the exported bindings do matter.

Distinguishing between a symbolic module name and a filesystem path also gives the language compiler/linker/bundler some space to provide a resolution mechanism: aliasing modules, mocking them, providing different assets for various platforms and module formats (Node, browser, CommonJS, ES, ...)

Many JS modules are not files, but rather directories. And there is an `index.*` file to load. Rewriting all imports to:
```js
import from 'components/button/index.js';
```
completely misses the point why `index.*` files exist in the first place. The `index` was never intented to be visible by the external observer. It's a convention to resolve a directory name to a file name. There's almost 30 years of precedent about that.

Ryan Dahl's Deno can import only files and dismisses _package.json_ as "unnecessary abstraction", but I don't expect that idea to get any traction at all. Encapsulated modules and package managers are extremely useful and can't be just removed without any replacement.

The above applies to executable code. Assets like stylesheets, images or documents seem to be different. The file format does matter and the 1:1 correspondence between import statements and filesystem seems to work well.

**Comment by dmsnell** [comment]
@jsnajdr @blowery how do we feel then about making all CSS imports explicit paths?

> the "thing" that is being imported is not a file, but something more generic, a "package" or "module"

yeah I get this idea, though our situation in Javascript is inherently more complicated with the advent of the loaders. we don't have well-defined meaning for modules. we can load _anything_ and it works through magical transformations to end up as JS. if we wrote `require( 'cow' )` it might actually load from a [REST API interface](https://textart.io/api/cowsay) to the `cowsay` program.

my argument is that it would be more obvious what were happening if this were an explicit path or URI

```js
require( 'cowsay://random' );
```

for files the filesystem path is an obvious default case.

for Javascript files I also think it's a reasonable admission to say they don't need an extension but still it's shifting burden from the computer to the developer when trying to understand what's going on.

```
\__thing
     \__index.js
     \__index.jsx
     \__index.scss
```

without scanning through our `webpack.config.js` can you say which file will be included when we `require( 'thing' )`?

it was actually `index.scss` that led me to raise this issue since `index.jsx` was being mistakenly imported instead of the CSS files.

> Many JS modules are not files, but rather directories

is this right? isn't the module still `index.js` or `index.jsx` or `index.json` (according to our current webpack config)?

> Distinguishing between a symbolic module name and a filesystem path

we're not doing this though - we're still resolving specifically to a file - we're just hiding the mechanics of that resolution and it leads to some fuzzy problems. for example, I'm constantly confused when I see `require( 'config' )` because it _could_ be coming from `server/config` or from `client/config` but that isn't clear until the runtime which one it is.

---

if this were all by-design I think it would make more sense but it seems like this pattern is the result of habit and style more than design. at this point I think the discussion needs to focus mostly on the question "should we make our CSS imports explicit with extensions" so we don't get bogged down in the philosophy - I just wanted to share my response :smile:

**Comment by jsnajdr** [comment]
> how do we feel then about making all CSS imports explicit paths?

If we don't arrive at some very different conclusion in this rich debate, the option I like the most at the moment is to
- import executable code as "symbolic" module paths: `components/button`
- import assets as explicit paths with no extensions resolution: `components/button/style.scss`. All parts of this string are mandatory

**Comment by dmsnell** [comment]
Can we abandon this PR and move the relevant changes to a new one? I just tried rebasing but it was too difficult for me to quickly resolve the conflicts.

**Comment by blowery** [comment]
yup, closing

**Pull request closed without merging**
