### PR TITLE
Remove Simple Classic experiment

### PR DESCRIPTION
**Pull request by taipeicoder**
## Proposed Changes

This PR removes the Simple Classic experiment in order to make it available for all Simple site users.

## Why are these changes being made?

Simple Classic experiment has concluded, and we decided to roll out the feature to all users. See pfsHM7-1lN-p2. 

## Testing Instructions

* Head to /settings/general/{SITE}.
* Ensure that the Admin interface style setting is available and works as intended.
* Alternatively, assign yourself to the control group and ensure that the Admin interface style setting is still available. 

## Pre-merge Checklist

- [x] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [x] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [x] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [x] Have you checked for TypeScript, React or other console errors?
- [x] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [x] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [x] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Comment by fushar** [comment]
Am I dreaming.... 😂 

@taipeicoder , I've been prioritizing Simple Classic profile bugfixing to anticipate this moment. Could I get your eye to test this diff as well? D157779-code 🙏

**Review by fushar — COMMENTED** [review]
We need to remove this gate as well:

https://github.com/Automattic/jetpack/blob/429aba0617ef6c67c33d3500e42a1ad3843df16a/projects/packages/jetpack-mu-wpcom/src/features/wpcom-admin-interface/wpcom-admin-interface.php#L38-L39

Currently, the option is not shown if we use the Classic view on Settings -> General page (via the switcher at the top-right).

**Review by fushar — APPROVED** [review]
Other than that, on Calypso side, this looks good!

**Review by arthur791004 — APPROVED** [review]
The code looks good and works as expected on my side!

**Comment by taipeicoder** [comment]
> We need to remove this gate as well:
> 
> https://github.com/Automattic/jetpack/blob/429aba0617ef6c67c33d3500e42a1ad3843df16a/projects/packages/jetpack-mu-wpcom/src/features/wpcom-admin-interface/wpcom-admin-interface.php#L38-L39
> 
> Currently, the option is not shown if we use the Classic view on Settings -> General page (via the switcher at the top-right).

Nice catch! https://github.com/Automattic/jetpack/pull/38774 addresses this issue.

**Pull request merged**
