### PR TITLE
Gutenberg: Relax classname namespace rules for extensions

### PR DESCRIPTION
**Pull request by tyxla**
Currently, when developing blocks for Gutenberg in Calypso, we often have to disable our `wpcalypso/jsx-classname-namespace` eslint rule so we can use a more specific classname namespace. 

So this PR suggests that we automatically disable this rule for all of the Gutenberg extensions we build from Calypso. It also cleans up any of those eslint inline overrides that we already had in place.

Would be a good follow-up to introduce a rule for our Gutenberg extensions, and apply it for them in Calypso.

To test:
* Checkout this branch.
* Add an inconsistent classname in an extension and run `eslint` to verify it doesn't return an error.
* Add any other change that would cause an eslint error (like an undefined var usage or an unused var) and run `eslint`, then verify it's still reported.

### CODE REVIEW

**Comment by simison** [comment]
Instead of disabling this completely, should we introduce customized naming conventions instead?

BTW we might want to extend this to `client/gutenberg/editor`

**Comment by simison** [comment]
Adding to above comment that we should not need to use Gutenberg/core class-names and we we have to, it's a signal that something needs to be changed at upstream.

That said, we should still lax classname rules inside these blocks since we might need to organise files differently than we otherwise would for regular Calypso components.

[Here's the plugin file](https://github.com/Automattic/eslint-plugin-wpcalypso/blob/6344223859bcbdead239d67e3a5f517016e8c451/lib/rules/jsx-classname-namespace.js) producing this rule for Calypso.

**Comment by tyxla** [comment]
Thanks, folks. 

I'm going to merge this, but will open an issue so we can track the necessity of a custom ESLint rule.

**Comment by tyxla** [comment]
Opened an issue for the custom ESLint rule #27211

**Pull request merged**
