### PR TITLE
ci: Drop slack notifications from magellan reporter

### PR DESCRIPTION
**Pull request by scinos**
#### Changes proposed in this Pull Request

Remove slack notifications from magellan-reporter. This can be handled by TeamCity now.

#### Testing instructions

* Verify Selenium e2e tests still pass
* Verify screenshots are still recorded and exposed as artifacts.

### CODE REVIEW

**Comment by noahtallen** [comment]
> Verify screenshots are still recorded and exposed as artifacts.

I don't see any screenshots in the e2e archives. There are a bunch of logfiles though. I'm guessing that's expected when tests pass?

**Comment by worldomonation** [comment]
> > Verify screenshots are still recorded and exposed as artifacts.
> 
> I don't see any screenshots in the e2e archives. There are a bunch of logfiles though. I'm guessing that's expected when tests pass?

Yes, when tests pass only the log files are uploaded.

**Review by worldomonation — APPROVED** [review]

**Comment by scinos** [comment]
This is ready for a re-review.

I undid some of the changes, turns out this reporter was also responsible of copying the screenshots to the place TeamCity expects to find them. To prove it work I introduced a forced error and screenshots artifacts are captured (https://teamcity.a8c.com/buildConfiguration/calypso_Calypso_E2E_Selenium_desktop/6781813?buildTab=overview)

**Review by noahtallen — APPROVED** [review]
Code changes make sense to me :+1:

**Pull request merged**
