### PR TITLE
Reader: Fix more card inconsistencies

### PR DESCRIPTION
**Pull request by jancavan**
We still found some spacing inconsistencies in cards and this PR fixes those.

However, the `.has-thumbnail` class still exists in excerpt/text-only cards so spacing issues for those won't be fixed until we land https://github.com/Automattic/wp-calypso/pull/9149 (but properties for those are already in place).

I've re-checked each and every type of card to make sure their spacing remains consistent.

## Default card:

default-1
deafult-2
default-3

## Excerpt/text card (the `.has-thumbnail` class has to be removed from this card for its correct properties to be applied):

excerpt-1
excerpt-2
excerpt-3

## Photo card:

photo-1
photo-2
photo-3

## Gallery card:

gallery-1
gallery-2
gallery-3

## Video card:

video-1
video-2
video-3

## Video card (playing):

videop-1
videop-2
videop-3

/cc @fraying 

Related: https://github.com/Automattic/wp-calypso/pull/9163

### CODE REVIEW

**Comment by fraying** [comment]
Lookin good! (Except for the Text cards, but I know that's waiting on #9149)

**Comment by samouri** [comment]
`has-thumbnail` should be gone now for text-only cards.
proof: proof

**Comment by bluefuton** [comment]
@samouri I'm still seeing `has-thumbnail` on some text-only cards. For example:

http://calypso.localhost:3000/read/feeds/8901148

screen shot 2016-11-14 at 12 29 39

**Comment by samouri** [comment]
@bluefuton that's because this hasn't been rebased yet :)

**Comment by blowery** [comment]
rebased

**Comment by jancavan** [comment]
`has-thumbail` is now gone for excerpt-only cards and spacing has been corrected:

excerptb-1
excerptb-2
excerptb-3

**Comment by fraying** [comment]
Woo hoo! LGTM

**Pull request merged**
