### PR TITLE
Rewind: Change some labels in clone-credentials step of site cloning flow

### PR DESCRIPTION
**Pull request by rcoll**
Fixes https://github.com/Automattic/wp-calypso/issues/25329

To ensure that it's clear what the user is supposed to enter in the clone-credentials step, we need the ability to change the labels in the credentials form based on context.

This PR updates the host and path fields like so:

screen shot 2018-06-07 at 1 23 38 pm

**Testing**

Step through the site cloning flow until you reach the credentials form. Ensure the labels are reflected as seen in the screenshot above, and no other components are altered.

### CODE REVIEW

**Comment by eliorivero** [comment]
Labels are updated correctly, great work!
We should hold on for a bit on this until @benhuberman provides some definitive decision on the strings and which copy we should use.

**Comment by eliorivero** [comment]
You know, I think we can drop this as long as the path entered in thje Server Address is what user entered in the previous step. That alone covers things and will be prominently seen by users and they will realize which server it's referring to.

**Comment by benhuberman** [comment]
I [commented here](https://github.com/Automattic/wp-calypso/issues/25329#issuecomment-395556847) re: adding language around "destination server." Happy to take another look if you sense that isn't enough and we need tweaks to individual labels.

**Comment by eliorivero** [comment]
Thanks for the copy @benhuberman! 

@rcoll copy to introduce as recommended by Ben is at https://github.com/Automattic/wp-calypso/issues/25329#issuecomment-395556847

**Comment by rcoll** [comment]
Copy updated in https://github.com/Automattic/wp-calypso/pull/25375/commits/29df5a3624eb8678162ec523447d015a55aad79d

@benhuberman @eliorivero can you make sure this is how you intend? Thanks!

**Comment by eliorivero** [comment]
Great work Rich 🐑 

captura de pantalla 2018-06-11 a la s 13 49 23

**Pull request merged**
