### PR TITLE
Update node to 10.4.1

### PR DESCRIPTION
**Pull request by alisterscott**
This PR updates Calypso to node v10.4.1. This brings us to the [latest of the main line](https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V10.md#10.4.1).

### Local Dev
- Switch to node version 10.4.1 (npm 6.1.0)
- `npm run distclean`
- `npm start`
- No functional changes to Calypso
### Local Docker Image
- Follow image instructions at: PCYsg-5XR-p2 or
- Setup docker locally and add the following host entry:
  ```
  127.0.0.1 wpcalypso.wordpress.com
  ```
- `npm run build-docker`
- `npm run docker`

### Desktop
TBD

### CODE REVIEW

**Comment by alisterscott** [comment]
It looks like circleCI doesn't have 10.4.1 images yet to run the builds 👎

**Comment by alisterscott** [comment]
@gwwar / @blowery  with wp-desktop I can no longer find the version specified in the package.json: https://github.com/Automattic/wp-desktop/blob/develop/package.json

Any ideas on what we need to do for that?

**Comment by sirreal** [comment]
The engines key was recently removed by https://github.com/Automattic/wp-desktop/pull/454

The idea is that wp-desktop should roll with wp-calypso Node versions, without requiring duplicate changes in the wp-desktop repo. Should be all set for wp-desktop 👍

**Comment by gwwar** [comment]
Code changes here look good 👍 We can 🚢 this after circle-ci adds a docker image and e2e tests are green. https://circleci.com/docs/2.0/circleci-images/

**Comment by blowery** [comment]
CircleCI has images. Rerunning tests.

**Review by blowery — COMMENTED** [review]
LGTM

**Pull request merged**
