### PR TITLE
Domains: Contact Info: Privacy Protection State

### LINKED ISSUE #2909: Domains: Privacy Protection State in Contacts and Privacy
While reviewing #2899 @klimeryk noticed that the same behaviour of showing the privacy status on if you have purchased one (but disabled). We should fix it so it shows disabled when it is disabled.

### PR DESCRIPTION
**Pull request by umurkontaci**
Fixes #2909.

This fixes showing the wrong state for Privacy Protection in Contacts & Privacy Page. (See #2899 #2133 for context -- tl;dr: We have 3 states for Privacy Protection: on, off, disabled for transfer). I've added a copy for the message if the users land to this page while their Privacy Protection is disabled, but that shouldn't happen very often, as we don't link to this page when it's disabled. Though they still land here through bookmarks or browser history. 

#### The looks:
image
(Link goes to the transfer page)

/cc: @ranh for copy, @klimeryk for code

### CODE REVIEW

**Comment by klimeryk** [comment]
Works as advertised! :grinning: 
I like the refactor too :+1: The only gripe I have with the code (apart from the unused function) is that it's not clear (at least to me) what's the difference between `hasPrivacyProtection` and `privateDomain`. I had to refer to #2133 to get an idea what these are.
It might be beyond the scope of this PR, but I believe that changing these properties' names to something more meaningful would prevent issues like this (checking one flag instead of both) in the future. We are already changing the names of properties in [`lib/domains/assembler.js`](https://github.com/Automattic/wp-calypso/blob/master/client/lib/domains/assembler.js#L22-L42), so might as well change it to something more meaningful. Maybe `isPrivacyProtectionPurchased` and `isPrivacyProtectionEnabled`? `privateDomain` just sounds so cryptic.

**Comment by ranh** [comment]
@umurkontaci, I suggest perhaps:

> Privacy protection is temporarily disabled for this domain while the registration is being transferred. Your contact information [...]

**Comment by umurkontaci** [comment]
> The only gripe I have with the code (apart from the unused function) is that it's not clear (at least to me) what's the difference between hasPrivacyProtection and privateDomain. I had to refer to #2133 to get an idea what these are.

I agree that the names of the properties are not very clear. However I'm not a big fan of changing the names of the properties to something else at the assembler as I think it removes the mental link and then one has to go through the assembler the find out the mapping.

**Comment by umurkontaci** [comment]
@ranh Privacy protection is temporarily disabled for this domain while the registration is being transferred. Your contact information [...]

I've changed it to "Privacy protection is temporarily disabled for this domain while the domain is being transferred. Your contact information [...]" since we've using "Domain Transfer" everywhere else.

**Comment by umurkontaci** [comment]
@klimeryk After the refactor, this function is no longer used and can be removed.

Fixed.

PS: Could you comment on files changed part instead of individual commits?

**Comment by klimeryk** [comment]
:ship: 

> PS: Could you comment on files changed part instead of individual commits?

My bad, I was browsing the whole file and commented there by mistake. Will keep this in mind in the future

**Pull request merged**
