### PR TITLE
Atomic Downgrade: Adjust "Proceed with caution" wording

### LINKED ISSUE #56989: Atomic Downgrade: Adjust "Proceed with caution" wording
Most of the common feedback we've received so far is the confusion that the downgrade process can cause to users since our effort of not over communicating results in a lack of clear expectations. 

To improve this, let's adjust a little bit the wording in the "Proceed with caution" step while also adding extra info in a tooltip so we don't initially overwhelm users:

> After deactivating your plan, we will return your site back to the point when you first installed your first plugin or custom theme or activated hosting features on `TRANSFER_DATE`. Your posts, pages and media will be preserved. ℹ️ 

When users click on ℹ️ , we display a tooltip with the following info:

> We automatically moved your site to a separate platform on `TRANSFER_DATE` in order to support the usage of plugins, custom themes, and hosting features. These features will no longer be supported if you deactivate your plan, so we’ll move your site back to its original platform. All the posts, pages and media added while on this platform will be preserved (with the exception of the content generated by plugins or custom themes).

Let's also change the wording around backups to remove the false expectation that it can be easily restored:

> To make sure you have everything after you cancel or if you’d like to migrate, you can download a backup.

### PR DESCRIPTION
**Pull request by mmtr**
Fixes https://github.com/Automattic/wp-calypso/issues/56989

#### Changes proposed in this Pull Request

Changes the copy displayed on the "Proceed with caution" step prior cancelling a plan from an Atomic site, so users have a better idea of what's going to happen.

Screen Shot 2021-10-14 at 16 42 53

#### Testing instructions

- Use the Calypso live link below and append `?flags=atomic/automated-revert` at the end of the URL.
- Switch to an Atomic site.
- Go to Upgrades > Purchases.
- Start the plan deactivation flow.
- Make sure the "Proceed with caution" contains the updated wording.
- Make sure there is a tooltip which displays extra detailed information.
- Make sure the atomic transfer date is correct and it's displayed in the expected format according to your locale.

### CODE REVIEW

**Comment by dsas** [comment]
This looks good, the only nitpick I would make is that in the tooltip it talks about the original platform, and the next sentence says 'this platform', so it could be read as if it's talking about the original platform, when it means the 'separate platform'

image

**Comment by dsas** [comment]
Maybe "All the posts, pages and media added before and after `TRANSFER_DATE` will be preserved" would be clearer and more user-friendly?

**Comment by mmtr** [comment]
> Maybe "All the posts, pages and media added before and after `TRANSFER_DATE` will be preserved" would be clearer and more user-friendly?

Good suggestion! Changed in https://github.com/Automattic/wp-calypso/pull/56999/commits/16f0585e9dccefff689b635bbc8137932cdd2248

**Comment by BogdanUngureanu** [comment]
Made several tests on different resolutions and LGTM! 🚢  🥳

**Review by BogdanUngureanu — APPROVED** [review]

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/6811987

Thank you @mmtr for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/6811987).

**Pull request merged**
