### PR TITLE
Update/jetpack cloud mobile view

### PR DESCRIPTION
**Pull request by enejb**
#### Changes proposed in this Pull Request

Update the pages across jetpack cloud to be more like calypso. 
This PR adds a document title, Main component and SidebarNavigation for each Page in Jetpack Cloud. 

Some things are not yet translated. I think that could betackeld in a different PR. 

It solves the current non mobile navgation in the same way as calypso. 

Before:
Screen Shot 2020-03-19 at 11 51 00 AM

After:
Screen Shot 2020-03-19 at 11 47 20 AM

#### Testing instructions
* Load up Jetpack Cloud. 
* Does it work as expected.

### CODE REVIEW

**Comment by folletto** [comment]
> It solves the current non mobile navigation in the same way as calypso.

I think this is a solid approach ;)

**Comment by folletto** [comment]
Given there's currently no mobile navigation, and the code is ready — let's push this live. 👍

**Comment by keoshi** [comment]
@folletto There are still design tweaks that need to happen here; will push them out shortly.

**Comment by folletto** [comment]
> There are still design tweaks that need to happen here; will push them out shortly.

Can we do this in a separate PR?

**Comment by keoshi** [comment]
@enejb This should be ready to go design-wise.

> Can we do this in a separate PR?

@folletto Can't see why we shouldn't make these changes as early as possible.

> Given there's currently no mobile navigation

What do you mean? We do have a mobile navigation in place:

image

**Comment by folletto** [comment]
> Can't see why we shouldn't make these changes as early as possible.

Because time. A large PR like this might be holding up everyone else's work. Small PRs also have a benefit of:
1. Being easier to review
2. Being easier to track in the future
3. Being easier to revert

In general, let's try to have smaller PRs and quick reviews than larger PRs that do multiple changes.

> What do you mean? We do have a mobile navigation in place:

From the "Before" screenshot above, there's no way to get back from a page. I confirmed also in browser:

Screenshot 2020-03-19 at 15 51 07

**Comment by enejb** [comment]
Thanks for the fixes @keoshi!

**Comment by keoshi** [comment]
> I confirmed also in browser:

It seems like you're looking at https://cloud.jetpack.com/, not the changes on this PR. I'm confused.

**Comment by folletto** [comment]
> It seems like you're looking at https://cloud.jetpack.com/, not the changes on this PR. I'm confused.

That's what I was saying: ship this PR since it adds the navigation as we don't have one yet added ;)

**Pull request merged**
