### PR TITLE
My Home: Render and stack all dot-paged cards to minimize jumping controls.

### LINKED ISSUE #41203: My Home: Dot-paged cards jump and flash.
This is an issue to hold the followup items from the merge of #41184, via @sixhours :

> * There's a weird flash the first time I switch between the pages, shown in this video: https://cloudup.com/ctxPpQSDtng
> * The size difference between the images for the block editor and the photo library make the transition between the pages feel jarring (even without the flashing weirdness).

### PR DESCRIPTION
**Pull request by kwight**
This is a potential followup to #41184 , that added a paged education card. Feedback in that PR was clicking on the controls caused the controls to jump, due to the different sized cards switching view (each rendered with its own fresh controls).

Rather than having the controls trigger a re-render of the whole component while skipping the non-active page, this PR nests all of the pages into one div, with a persistent set of controls. The content is stacked, so that the biggest page, whether visible or not, takes up the maximum height within the pager, guaranteeing the controls don't jump when switching content. Because the full pager is only rendered once, we don't have the "[weird flash](https://github.com/Automattic/wp-calypso/pull/41184#issuecomment-614904834)" pointed out by @sixhours .

Apr-17-2020 14-10-09

Fixes #41203

### CODE REVIEW

**Comment by kwight** [comment]
@mmtr If this makes any sense to you, please do build upon it; I conveniently had to stop at the part where I would need to figure out how hooks work  🙃 .

**Comment by gwwar** [comment]
Some other options to explore too:
- Use a background image instead of an img src tag (for a stable element size)
- Drop images from the compact view (we already do this for mobile)
- Maybe explore and play with some newer browser features like lazyload and preload

**Comment by mmtr** [comment]
> @mmtr If this makes any sense to you, please do build upon it; I conveniently had to stop at the part where I would need to figure out how hooks work 🙃 .

I think this is actually a very good idea 😄 . I pushed a commit that tries a slightly different approach (using flexbox rather than grid) but based on the same principle. I also added a transition animation.

Apr-17-2020 14-10-09

I also applied it to the `DotPager` component, so it works out of the box for anything using it and not only in the educational cards.

**Comment by kwight** [comment]
Fantastic @mmtr , I ❤️it!

**Pull request merged**
