### PR TITLE
Checkout: add popover info for the pan number field

### PR DESCRIPTION
**Pull request by yoavf**
#### Changes proposed in this Pull Request

We're required to ask our customers for their PAN numbers when paying with local payment methods in India (soon launching, NetBanking).  This adds a tooltip popover to explain the requirement and to let customers know that the PAN number isn't required when paying with a credit card.

Screen Shot 2019-07-01 at 14 59 51

#### Testing instructions

To enable "Net Banking", you'll want your backend to have store sandbox enabled. 
Then, visit the checkout form to see the Ne Banking tab available.

### CODE REVIEW

**Comment by yoavf** [comment]
@kanishkdudeja - I'd love your opinion on the text itself as well.

**Comment by michelleweber** [comment]
Can we lighten up the whole thing? I'm thinking:

_To pay with Net Banking, please enter your PAN number.  (If you're paying with a credit card that can be used internationally, you can skip this step.)_

That feels like it communicates the key things that need to be communicated here, but is it not enough detail?

**Comment by yoavf** [comment]
@michelleweber Thanks! It does communicate the alternative very well, but I think I was hoping to justify the "why" we're asking for the PAN number (we're required to), since it's not very common and might raise some questions from our users.

**Comment by michelleweber** [comment]
In that case, I might just say "Paying with Net Banking requires a PAN number." For any more detail that that in a tooltip like this, I'd do a "Learn more" link to the info.

**Comment by yoavf** [comment]
Thanks @michelleweber - that's great. We'll add the link once I've created the documentation.

**Pull request merged**
