### PR TITLE
General: Updated Jade dependency to 1.11.0

### PR DESCRIPTION
**Pull request by montogeek**
Hi!

Early today I noticed some warnings about deprecated dependencies when installing the project for the first time. I asked https://github.com/Automattic/wp-calypso/issues/123#issuecomment-175253636 if there is any plan to upgrade them. @ockham told me to go ahead and do it, so here is.

Basically I updated `jade` dependency to the latest stable version, it removed the deprecated warnings, I manually tested that all four Jade files loaded correctly.

Thanks

### CODE REVIEW

**Comment by ockham** [comment]
Thank you for your contribution!

Please note that the Jade [commit](https://github.com/pugjs/jade/commit/29784fd1ec6043397f4b43d45b4ee9e25177b940) we were pinning in `package.json` is actually newer than 1.11.0, and apparently [there won't be any more point releases](https://github.com/pugjs/jade/issues/2170) in the `1.*` series.

Instead, we will need to upgrade to [~~Jade~~ Pug](https://github.com/pugjs/jade/issues/2184) 2.0 (which according to that issue hasn't been released yet apparently :-| )

**Comment by montogeek** [comment]
I understand, so, we need to wait until they release a stable version of Pug?

**Comment by ockham** [comment]
Seems like it :-( as https://github.com/pugjs/jade/issues/2184 says

> pug 0.10.x will be used for experimental releases of pug 2.0.0 until it is stabilised.

I don't think we want an experimental pug release in production for Calypso.

(Apologies if I misdirected you, I haven't been quite keeping up with Jade's development lately either.)

**Comment by montogeek** [comment]
Not, it's ok, once a stable version is released, we can work on it :)

**Pull request closed without merging**
