### PR TITLE
Colour Scheming: Expose Muriel Colours

### PR DESCRIPTION
**Pull request by torres126**
#### Changes proposed in this Pull Request

Follow up to #31170:

> We've thought about exposing all of the muriel colors as color variables...

@blowery, @flootr, is this what you're referring to?

### CODE REVIEW

**Comment by blowery** [comment]
Yup! Thanks!

**Comment by blowery** [comment]
We are moving this file in https://github.com/Automattic/wp-calypso/pull/30933, so we'll probably want to hold off until that lands.

**Comment by sirreal** [comment]
#30933 has landed, this needs a rebase

**Comment by torres126** [comment]
Is it ok if I just file a separate PR? I think that'll be easier (don't think I can rebase this one).

#31246

**Pull request closed without merging**
