### PR TITLE
Add monorepo dependencies to tsconfig.json for Composite Checkout package

### PR DESCRIPTION
**Pull request by razvanpapadopol**
Similar to #47140

#### Changes proposed in this Pull Request

* List monorepo dependencies as references in the `tsconfig.json` file of `@automattic/composite-checkout` package.

#### Testing instructions

* In the project's root folder, run this command. It should run without errors:

`yarn clean:packages; ./node_modules/.bin/tsc --build packages/composite-checkout`

### CODE REVIEW

**Review by ciampo — APPROVED** [review]
Tested successfully, LGTM

**Review by sirbrillig — APPROVED** [review]
Looks fine to me although it would help if I understood what this did. Sorry for my lack of TS knowledge! Neither the description here nor the referenced PR seems to explain it. I guess the idea is to have the TS compiler use the monorepo versions of packages rather than its own node_modules?

**Comment by ciampo** [comment]
> Looks fine to me although it would help if I understood what this did. Sorry for my lack of TS knowledge! Neither the description here nor the referenced PR seems to explain it. I guess the idea is to have the TS compiler use the monorepo versions of packages rather than its own node_modules?

I think so. cc'ing TypeScript Master @sirreal for confirmation

**Review by sirreal — APPROVED** [review]

**Comment by sirreal** [comment]
>  I guess the idea is to have the TS compiler use the monorepo versions of packages rather than its own node_modules?

This is to make `tsc` aware of the dependency graph. It won't allow circular dependencies and it will ensure dependencies are built before dependents. It will also take care of rebuilding dependencies as necessary (really nice with `tsc --build --watch`).

There are cases it will work because dependencies just happen to be built before dependents, but it's fragile.

Details in [the docs](https://www.typescriptlang.org/docs/handbook/project-references.html).

**Comment by sirbrillig** [comment]
Thank you for the explanation!

**Pull request merged**
