### PR TITLE
Framework: remove <Flag> component

### PR DESCRIPTION
**Pull request by mtias**
This removes the `<Flag>` component in favour of `<Notice isCompact>`.

----

### Test

This should cover all existing use cases of Flag. cc @scruffian @breezyskies 

This is the one I could spot myself:

image

May need some tweaks for the line.

### CODE REVIEW

**Comment by breezyskies** [comment]
Overall, this looks good. Noticed this one seems to be missing the icon (should be `lock`): 

screen_shot_2015-12-16_at_8_24_53_am

**Comment by mtias** [comment]
The TLDs look like this:

image

**Comment by breezyskies** [comment]
:+1: Privacy protection icon looks good now.

**Comment by mtias** [comment]
Awesome, thanks for looking.

**Comment by gziolo** [comment]
@breezyskies: `onClick` doesn't work for privacy protection `None` icon, should we bring back this behavior or remove callback:

```js
<Notice
	isCompact
	status="is-warning"
	icon="notice"
	onClick={ this.goToPrivacyProtection }>
	{ this.translate( 'None', {
		context: 'An icon label when Privacy Protection is disabled.'
	} ) }
</Notice>
```

@mtias: would it be ok to add `onClick` handler to `Notice` component or should we wrap it with another element?

**Comment by mtias** [comment]
I think it should be wrapped, since `Notice` is neither a button nor a link in itself.

**Comment by breezyskies** [comment]
> I think it should be wrapped, since Notice is neither a button nor a link in itself.

Opened a PR for this in https://github.com/Automattic/wp-calypso/pull/1740.

**Pull request merged**
