### PR TITLE
Domains: remove the analytics mixin

### PR DESCRIPTION
**Pull request by jsnajdr**
This PR finishes the removal of `lib/analytics/mixin` from Domains and migrates several `createReactClass` usages to modern (OK, not so modern any more 🤣) ES6 classes.

The `navigationClick` event was used exactly once, so I inlined the code into the `WpcomDomain` component.

The `paymentSettingsClick` event was used at multiple places, so I extracted it to a helper module `payment-settings-analytics`. There was also recent code by @aidvu that implemented a Redux action for these analytics, so I unified all these usages into one convention.

I also fixed an inconsistency when reporting `section` property of events like `calypso_domain_management_edit_payment_settings_click`. Sometimes we sent `domain.type` there, sometimes we sent `snakeCase( getDomainTypeText( domain ) )`. The following screenshot from our Tracks UI shows the inconsistency:

Screenshot 2019-11-18 at 14 52 57

The all-upper-case names are from `domain.type`, the snake-lower-case ones are from `snakeClase( getDomainTypeText )`.

From now, everything will be `domain.type`, i.e., uppercase.

### CODE REVIEW

**Comment by aidvu** [comment]
LGTM. Code works, tho we should rerun tests and rebase.

I didn't figure out how to test the Google Analytics actions. I can see the Redux action fired `ANALYTICS_MULTI_TRACK` with the correct data, but have no idea how the actual tracking happens.

**Comment by aidvu** [comment]
Yeah, would defo be a good idea to check if GA is actually working. :)

**Comment by jsnajdr** [comment]
@aidvu I usually test analytics by setting
```js
localStorage.debug = 'calypso:analytics:*';
```
and then verifying the console messages. When clicking on the "Payment Settings" button in this branch, I get:

Screenshot 2019-11-20 at 11 22 16

and that seems right (both GA and Tracks).

I rebased and re-ran the tests. Mobile e2e are green, Desktop e2e are failing exclusively in Gutenberg integration -- not related to this PR.

**Comment by aidvu** [comment]
Nice. Thanks @jsnajdr. Totally missed https://github.com/Automattic/wp-calypso/blob/368a74dabd8d189e2a40b068538c027e9fbe4749/client/lib/analytics/ad-tracking.js#L1726.

Mind rebasing/rerunning before someone else merges something, and deploy it when tests pass again. :(

**Review by aidvu — APPROVED** [review]
lgtm

**Pull request merged**
