### PR TITLE
Framework: Upgrade to Webpack 4  (take two)

### PR DESCRIPTION
**Pull request by samouri**
Reverts Automattic/wp-calypso#24006

**What broke?**
Support User support.

**Testing instructions**
- build docker locally and run it.
- use the support-user tool and the wpcalypso environment.
- check other server rendered pages and ensure they don't rely on function names in the same way

### CODE REVIEW

**Comment by samouri** [comment]
In our webpack 3 code, the js code used by the server isn't uglified.
in webpack 4 it is, therefore relying upon exact function name to be in sync between the two when using `fn.toString()` stopped holding.

the webpack 3 source for `support-user` looked like this:
```js
function supportUserFn()
   ....
}

<script> { supportUserFn.toString() }   supportUserFn() </script>
```

in webpack 4 that became:
```js
// uglified
function(){
...
}
<script> { supportUserFn.toString() }  supportUserFn()  </script>
```

**Comment by samouri** [comment]
**to test**:
- build docker locally and run it.
- use the support-user tool and the wpcalypso environment.

**Comment by blowery** [comment]
Support user tested out for me with a local docker build.

**Review by blowery — APPROVED** [review]
LGTM

**Comment by apeatling** [comment]
🎉

**Pull request merged**
