### PR TITLE
Plans: enable domain to personal plan nudge on domains page

### PR DESCRIPTION
**Pull request by gwwar**
This PR enables the following nudge on the domains page. Clicking on the upgrade button will take you to the checkout page with a Personal plan in cart:

screen shot 2016-10-10 at 3 41 45 pm

## Testing Instructions

- Navigate to calypso.localhost:3000/domains
- Select a wpcom site with: (a free plan + a paid domain )
- Set the abtest value of 'domainToPersonalPlanNudge' to 'nudge'
- The nudge should render
- Clicking on upgrade should take us to checkout
- Clicking the 'x' dismiss should make this item never appear again

### CODE REVIEW

**Comment by lamosty** [comment]
Nice work!

Got a few things:

1. Do we want the nudge to display above the navigation or below?

   selection_178

   I would save below the navigation as user context might be lost ("where am I?", "where is the navigation?", etc). /cc @folletto 

2. After clicking on the 'x' dismiss button on the nudge, the nudge disappears. However, after full-reload, it appears again.

**Comment by lamosty** [comment]
@gwwar: Was the previous mobile design ugly?

selection_179

Now the design looks like this:

selection_180

selection_181

It is missing the discount amount, original price and the "for a one year subscription" is too crammed with the upgrade button.

I'd prefer not to do any mobile tweaks until we get some designer feedback. /cc @adambbecker please.

**Comment by lamosty** [comment]
> After clicking on the 'x' dismiss button on the nudge, the nudge disappears. However, after full-reload, it appears again.

Doesn't show any more. Dunno why it showed for the first time after clicking the 'x' btn. Maybe I didn't click it good enough? :D

**Comment by lamosty** [comment]
@gwwar: I fixed the failing tests. The problem is that in the `domain-management/list/test`, we don't have access to Redux state. When `DomainList` is unit tested, it uses `DomainList` [component](https://github.com/Automattic/wp-calypso/blob/master/client/my-sites/upgrades/domain-management/list/index.jsx#L40) which is **not** connected to Redux store and so the tests don't fail on not having the Redux state.

However, when rendering the `DomainToPlanNudge` component inside `DomainList`, we didn't have any mechanism of using the not connected `DomainToPlanNudge` and so the unit tests failed on `DomainToPlanNudge`'s `connect` not having access to Redux state.

I fixed this in 94a3555 by checking whether `DomainList` is rendered in unit tests and if yes, not rendering `DomainToPlanNudge` in `DomainList`. I think that even if we decided to unit test `DomainToPlanNudge`, we should do that separately and not as part of `DomainList` unit tests.

What do you think?

**Comment by gwwar** [comment]
> @gwwar: Was the previous mobile design ugly?

A bit yes 😄 we should avoid breaking to two lines. I'll of course defer to @adambbecker on any styling changes

**Comment by drw158** [comment]
Just some feedback. I don't think I was around for this new nudge, so I'm sure of the background, but overall seems very big. If we need a nudge bigger than the regular one, then I think there's probably some middle ground. Maybe a slightly expanded regular nudge. Possibly, only include info relevant to the context (domains) and provide a link if they want to see what more the plan has to offer. Also, the text should be blue unless it is a link. I'll leave it up to Adam.

**Comment by gwwar** [comment]
@drw158 there's some more history in #7329

**Comment by adambbecker** [comment]
@gwwar, @lamosty: Added some small space (`<480px, 660-750px`) rendering tweaks via 2624d32. Here's what they look like:

screen shot 2016-10-11 at 3 08 26 pm

---

@drw158: Yeah, I totally agree. Not a big fan of these large nudges either, but luckily this is placed behind a test so we'll see soon enough if others agree as well from the data.

**Comment by gwwar** [comment]
Thanks for the fixes @lamosty and @adambbecker. @drw158 we'll be running thisfor 3 weeks or so see p3fqKv-3LH-p2, so we'll have some additional data soon to help direct us.

**Comment by gwwar** [comment]
> I fixed this in 94a3555 by checking whether DomainList is rendered in unit tests and if yes, not rendering DomainToPlanNudge in DomainList

I took a second look, and was able to fix this by mocking out the nudge component to point to an EmptyComponent instance in b727c43

**Comment by lamosty** [comment]
> I took a second look, and was able to fix this by mocking out the nudge component to point to an EmptyComponent instance in b727c43

Oh, this is great! I need to learn more about mocking comopnents. :)

**Comment by folletto** [comment]
> Not a big fan of these large nudges either, but luckily this is placed behind a test so we'll see soon enough if others agree as well from the data.

Just a note: the data would validate the hypothesis of a banner existing, not the specific design, which I agree should be made leaner. :)

**Pull request merged**
