### PR TITLE
update: Remove border radius from search input

### PR DESCRIPTION
**Pull request by kozer**
#### Proposed Changes

Due to some recent changes, the search input field styling on the site switcher is now broken:

before1

This pr updates this input field to its previous state.

before2

##### Before

- Visit `wordpress.com/home/<your-site>`
- On the top left of the sidebar, click on "Switch Site"
- Write anything in the input field that appears.
- Confirm that the input field is now appearing as shown in the following screenshot:

before-test

##### After

- Locally, visit `/home/<your-site>`
- On the top left of the sidebar, click on "Switch Site"
- Write anything in the input field that appears.
- Confirm that the input field is now appearing as shown in the following screenshot:

after-test

#### Pre-merge Checklist

- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [X] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?

Related to #68842

### CODE REVIEW

**Review by vykes-mac — APPROVED** [review]
Tested on major browsers and also tested other places the `search` component is used to see if any display artifact is introduced. It works as expected!

**Comment by danielbachhuber** [comment]
@kozer Out of curiosity, how was the break introduced?

**Comment by zaguiini** [comment]
It does fix the problem, but we're now seeing square borders on the input, while we have rounded borders in the outline...  That's rather inconsistent: 
image

**Comment by danielbachhuber** [comment]
> Out of curiosity, how was the break introduced?

It looks like the break was introduced in https://github.com/Automattic/wp-calypso/commit/016a4472f075f11ee32f7876842a513fd0a3147e#diff-9633630a973ef617934564839bb766c1c44f6b3bb7e7f95b120ce077f0420db6R29-R156 and https://github.com/Automattic/wp-calypso/pull/66650/files#diff-9633630a973ef617934564839bb766c1c44f6b3bb7e7f95b120ce077f0420db6R12-R59

I've reverted the changes with d4682d0fe98718183cd394c37e6a6a61ba926477 and the search input now appears as expected:

image

**Comment by danielbachhuber** [comment]
> I've reverted the changes with [d4682d0](https://github.com/Automattic/wp-calypso/commit/d4682d0fe98718183cd394c37e6a6a61ba926477) and the search input now appears as expected:

Created #68850 for follow-up.

**Pull request merged**
