### PR TITLE
Reader: utilize vimeo cdn for thumbnails

### PR DESCRIPTION
**Pull request by samouri**
background from https://github.com/Automattic/wp-calypso/issues/12088#issuecomment-286269239:
> I don't think this is for all vimeo videos and I also don't think this is technically related to combined cards.
If you go to the stream for laughingsquid, the thumbnail/video card is missing there as well.
When digging into the issue, it looks like the way that we normally glean the thumbnail url does not always work but I'm not sure why yet. We usually look for a json file located here: https://vimeo.com/api/v2/video/{videoId}.json
In this case it is: https://vimeo.com/api/v2/video/614847322.json which returns a 500 (could vimeo be having issues?). Other urls are still working like this vim video: https://vimeo.com/api/v2/video/6999927.json.
I may have found a better solution though, going straight to vimeo's cdn like so:
templateUrl: https://i.vimeocdn.com/video/{ id }.webp
https://i.vimeocdn.com/video/6999927.webp

fix for https://github.com/Automattic/wp-calypso/issues/12088

### CODE REVIEW

**Comment by bluefuton** [comment]
Much simpler 🎉

**Comment by bluefuton** [comment]
Hmm - I've found a case where this doesn't appear to give us a thumbnail for the video in question. Check out the first post here:

http://calypso.localhost:3000/read/feeds/59317198

The video is:

https://vimeo.com/48236494

...and the thumb is:

https://i.vimeocdn.com/video/48236494.jpg?w=1000

Before (wpcalypso):

screen shot 2017-03-14 at 14 47 47

After (this branch):

screen shot 2017-03-14 at 14 47 28

**Comment by samouri** [comment]
Hmm, seems like the correct thumb there is: https://i.vimeocdn.com/video/334113730.jpg,  I'll close this for now because I don't know of a method for figuring out the right cdn link

**Comment by samouri** [comment]
I did just find a non-deprecated api: https://vimeo.com/api/oembed.json?url=https%3A//vimeo.com/48236494 hmm

**Pull request closed without merging**
