### PR TITLE
BBE: add 5 new page types

### PR DESCRIPTION
**Pull request by aneeshd16**
Fixes https://github.com/Automattic/martech/issues/2139

## Proposed Changes

Adds 5 new pages to the BBE page picker step, with its associated strings and images.

- Careers
- Events
- Donate
- Newsletter
- Case Studies

### Screenshots

image

| Page | Page Picker step | Website Content Step |
|--------|--------|--------|
| Careers | image | image |
| Events | image | image |
| Donate | image | image |
| Newsletter | image | image |
| Case Studies | image | image |

## Testing Instructions

* Go to `/start/do-it-for-me` and proceed through the flow steps till you reach the page picker step.
* Confirm that the new pages mentioned above are visible and that the title, description and thumbnail match the screenshots.
* Select the new pages and complete the purchase.
* On the website content submission form, confirm that the description for the "Donate" and "Newsletters" page is different from the one on the page picker step and that it matches the screenshots.

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

**Comment by mikeicode** [comment]
I tested on simple and AT, works well. I didn't find any issues.

**Review by southp — APPROVED** [review]
Since @mikeicode already did the test, I mainly focused on code review and a few rounds of manual testing to make sure there is no obvious breakage. It works well and code LGTM 🚢

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/9408949

Some locales (Hebrew) have been temporarily machine-translated due to translator availability. All other translations are usually ready within a few days. Untranslated and machine-translated strings will be sent for translation next Monday and are expected to be completed by the following Friday.

Thank you @aneeshd16 for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/9408949).

**Pull request merged**
