### PR TITLE
Don't allow /en in the login URL

### LINKED ISSUE #14965: Login: English version can be accessed from two different urls
Raised by @stephanethomas in #14806:

> It's possible to access http://calypso.localhost:3000/log-in/en. I was expected to be redirected to http://calypso.localhost:3000/log-in in that case. We're duplicating content and entry points here, and that's something we should fix, although it doesn't have to be in this pull request.

I tried to fix this issue from the Locale Suggestions box, but then I broke `/start` pages and probably a couple of other pages, so I removed this fix from the original PR.

Steps to reproduce:
* Open http://calypso.localhost:3000/log-in
* Switch to a different locale
* Switch back to `en` locale
* You will see English translation, but different url. This is an issue on the Login page, because we have 2 different urls that produce the same HTML (we server render this page).

### PR DESCRIPTION
**Pull request by pento**
This pull request fixes #14965 by redirecting the URL to the base log-in URL, when `/en` is encountered.

#### Testing instructions

1. Run `git checkout fix/14965-english-locale-url` and start your server, or open a [live branch](https://calypso.live/?branch=fix/14965-english-locale-url)
2. Open the [`Log In` page](http://calypso.localhost:3000/log-in)
3. Check that the [en locale](http://calypso.localhost:3000/log-in/en) redirects correctly
4. Check that loading a [non-en locale](http://calypso.localhost:3000/log-in/fr) works correctly
5. While on the non-en locale, click the "Also available in English" link in the locale switcher, check that it redirects correctly

#### Reviews

- [x] Code
- [x] Product

### CODE REVIEW

**Comment by pento** [comment]
This does result in the `/en` URL being visible in the browser while Calypso loads, and it's not a canonical redirect - is there somewhere we can redirect earlier than this?

**Comment by scruffian** [comment]
I think there is more complexity here which we haven't considered. If I visit `/log-in` when I am already logged in, we should show the page in the interface language I have selected, rather than defaulting to English. This doesn't happen right now.

**Comment by pento** [comment]
Visiting `/log-in` while logged in works, but is unsupported behaviour - there are masses of bugs, particularly with how it overrides the SSR version. Is there a particular use case for visiting it while logged in?

**Comment by scruffian** [comment]
> Is there a particular use case for visiting it while logged in?

I believe so, but I can't remember what now. @stephanethomas pointed it out originally...

**Comment by stephanethomas** [comment]
> Is there a particular use case for visiting it while logged in?

Yes, that's when you want to log into a different account. See https://github.com/Automattic/wp-calypso/issues/14163 for more information.

**Comment by stephanethomas** [comment]
I left a suggestion but otherwise the code looks good and works fine, except for the case mentioned by Ben.

**Comment by scruffian** [comment]
Maybe we should merge this and deal with my issue in another PR

**Comment by pento** [comment]
Right, I see.

We should definitely do that in a different PR, this one will drag on forever if we try to do both.

**Comment by stephanethomas** [comment]
I've fixed the test that was failing, and rebased.

**Pull request merged**
