### PR TITLE
People: Implement notices for sending invitations

### LINKED ISSUE #2848: People: Trigger notices when sending invites succeeds/fails
We will need to show some sort of UI after sending an invite, which will likely be a notice. There is, however, some chat about new smaller notices that auto disappear. I'm not sure if these have, or are, being worked on. But, it might make sense to look into that.

### PR DESCRIPTION
**Pull request by ebinnion**
Closes #2848

<strike>This PR currently doesn't work, but is meant to add notices that fire after sending invitations.</strike>

To test:
- Checkout `update/people-invites-notices` branch
- Go to `/people/new/$site`
- Fill in form and send invites
- Do you see a success notice? 
- In Chrome emulator, turn off wifi and then submit form.
- Do you see an error notice?

### CODE REVIEW

**Comment by lezama** [comment]
@ebinnion, I added two commits :)

**Comment by ebinnion** [comment]
Huzzah! This works :) Thanks for the help @lezama!

I added one more commit that removes the `if ( error.message )` conditional. I went ahead and removed this since we're currently not using `error.message` anyways.

Eventually, we may want to use the error messages returned from the API, but since we validate before allowing the form to submit, I'd prefer that we just have a shorter message.

**Comment by roccotripaldi** [comment]
Code looks good, and works as described. 
One minor question: Should we clear the form after a successful send?

Ship it if you disagree, or feel that is an issue for an other PR.

**Comment by ebinnion** [comment]
I do agree with you. I'm going to address that in #3441. Thanks for the review!

**Pull request merged**
