### PR TITLE
Fix/select theme type

### PR DESCRIPTION
**Pull request by Stojdza**
#### Changes proposed in this Pull Request

Test `Sign up while purchasing premium theme in AUD currency @parallel @email` [was failing](https://circleci.com/gh/Automattic/wp-calypso/445264) occasionally because _Premium_ button wasn't acctualy clicked (button is loaded, but still not clickable) when test tries to filter premium themes:

Screen Shot 2019-10-04 at 16 00 41

The test doesn't fail on this step, because in this step it selects first theme from the list, doesn't matter is it premium theme or not, and continues further. After successful signup, the test expects to see the checkout page, and instead onboarding checklist is shown (because free theme was selected).

~~This PR changes the selector for _Premium_ and _Free_ buttons.~~ This PR changes the starting URL for premium theme purchase. I tested locally and on CircleCI numerous times and didn't see this error again.

@bsessions85 I also had two more possibilities on my mind how to solve this:
1. In [this line](https://github.com/Automattic/wp-calypso/blob/master/test/e2e/specs/wp-signup-spec.js#L1253) instead of opening `/themes` page to open `/themes/premium` (or `/themes/free` in other tests) page and skip [this](https://github.com/Automattic/wp-calypso/blob/master/test/e2e/specs/wp-signup-spec.js#L1256) step. 
2. To update how we wait for themes to load. [waitUntilThemesLoaded()](https://github.com/Automattic/wp-calypso/blob/master/test/e2e/lib/pages/themes-page.js#L49) -  this method waits for themes to load, but there is no difference is it waiting for free or premium themes. Since I couldn't find anything which is unique for premium or free themes list, I was thinking to check themes counter:

Screen Shot 2019-10-04 at 16 13 24

For example: get count -> select Premium themes -> get new count and check is it smaller than the first one. 

#### Testing instructions

Make sure that test `Sign up while purchasing premium theme in AUD currency @parallel @email` is passing locally and in CircleCI.

### CODE REVIEW

**Comment by bsessions85** [comment]
> 1. In this line instead of opening /themes page to open /themes/premium (or /themes/free in other tests) page and skip this step.
>2. To update how we wait for themes to load. waitUntilThemesLoaded() - this method waits for themes to load, but there is no difference is it waiting for free or premium themes. Since I couldn't find anything which is unique for premium or free themes list, I was thinking to check themes counter:

Yeah, I think either one would work. For number two you could change the name to something like waitUntilThemesUpdate or something so that there isn't confusion about what it does.

**Comment by bsessions85** [comment]
The error did happen again on the build, but it passed on re-run. Go ahead and try one of the other two approaches, maybe number two first, and see if that helps. 
https://circleci.com/gh/Automattic/wp-e2e-tests-for-branches/23555#artifacts/containers/0

**Comment by Stojdza** [comment]
@bsessions85 I added option no.2. What do you think? I'll run tests a couple of times in CircleCI

**Comment by Stojdza** [comment]
Choosing a premium theme is [still failing](https://circleci.com/gh/Automattic/wp-e2e-tests-for-branches/23560#artifacts/containers/0), so I'll go with an option no.1. This should work, since it opens `/themes/premium` directly - we skip clicking on _Premium_ button, but we still testing those buttons by clicking _Free_ themes button in other tests.

**Review by bsessions85 — APPROVED** [review]
Looks good!

**Pull request merged**
