### PR TITLE
Update Full Width Mobile Promo Card

### LINKED ISSUE #72596: [Enhancement]: Update to Mobile Promo Card on stats page
### Quick summary

We're looking to make some changes to [the `<MobilePromoCard />` component](https://github.com/Automattic/wp-calypso/blob/trunk/packages/components/src/mobile-promo-card/index.tsx). The changes we're looking to make involve the following:

* Update the font so that it matches the other cards in the stats page's carousel.
* Use the [`<AnimatedIcon />`](https://github.com/Automattic/wp-calypso/tree/trunk/client/components/animated-icon) for the Jetpack app's icon, this is used for other mobile app promos within Calypso (see https://wordpress.com/me/get-apps for an example).
* Direct users to apps.wordpress.com (instead of jetpack.com/app) in order to download the Jetpack app.

Current screenshot:

Screenshot 2023-01-25 at 19 37 38

### Steps to reproduce

1. Navigate to _My Sites_ → _Stats_ in WordPress.com.
2. Scroll to the carousel at the bottom of the page.
3. Scroll through each of the carousel's cards until you reach the mobile promo.

### What you expected to happen

Each card in the carousel should use the same font. In addition, the mobile promo should be consistent with other mobile promos used throughout Calypso (including the animated icon and links to apps.wordpress.com).

### What actually happened

There are some inconsistencies that can be found in the mobile promo, including a different font.

### Browser

Google Chrome/Chromium

### Context

_No response_

### Platform (Simple, Atomic, or both?)

Simple, Atomic, Self-hosted

### Other notes

_No response_

### Reproducibility

Consistent

### Severity

None

### Available workarounds?

None

### Workaround details

_No response_

### PR DESCRIPTION
**Pull request by SiobhyB**
Fixes https://github.com/Automattic/wp-calypso/issues/72596, please also note some of the discussions amongst developers and designers in that issue's comments.

> **Note**
> Although this PR includes ~20 changed files, the majority are relatively simple changes resulting from renaming components and moving files to different directories.

#### Proposed Changes

This PR makes some back-end and front-end tweaks to the mobile promo currently found at the bottom of the Stats page in Calypso. 

These tweaks can be grouped into the following three categories, with the purpose being to make the component easier to discover/use for developers and to bring some of the styling in alignment with other mobile promos:

<details>
 <summary>Renaming and moving components for clarity ⤵️</summary>

* The `<AppPromo>` component has been renamed to `<AppPromoSidebar  />`.
* The `<MobilePromoCard>` component has been renamed to `<AppPromoFullWidth />`.
* The [`<AnimatedIcon />`](https://github.com/Automattic/wp-calypso/tree/trunk/client/components/animated-icon) component has been moved from `client/components` to `packages/components`. This is so that it can be used with `<AppPromoFullWidth />` (which exists under the `packages` directory). To accommodate this, all of the component's existing imports and dependencies (`lottie` and `jest-canvas-mock`) have been updated to reflect its new location.
</details>

<details>
 <summary>Changes to AppPromoFullWidth component ⤵️</summary>

* The font has been updated to match the other promo cards on the Stats page. More specifically, the declaration of the font's family has been removed so that it defaults to `inherit` and the colour has been changed to `var(--studio-gray-50)`.
* The component's link has been updated from `jetpack.com/app` to `apps.wordpress.com`.
* The styling of the component's link has been slightly tweaked, to match the hover colour and underline style used for other mobile promos in Calypso.
* The QR code has been updated so that it redirects to the app stores if the user scans it with an Android or iOS device.
</details>

#### Testing Instructions

* Navigate to _My Site_ → _Stats_, scroll to the bottom of the page, and verify that the full width app promo looks as expected:
  * Scan the QR code and verify that the link directs to the play store for the device you're using.
* Verify that there are no unforeseen regressions in the sidebar app promo:
  * Navigate to the Reader in an account where you haven't dismissed the sidebar app promo. (You can manually change `shouldRenderAppPromo` to `true` [here](https://github.com/Automattic/wp-calypso/blob/dded2cf2a4d3d3770818998875bd4c3616bd93f7/client/reader/sidebar/promo.jsx#L17) if testing locally.)

#### Screenshots

**Before:**

Screenshot 2023-01-27 at 15 18 41

**After:**

Screenshot 2023-01-30 at 11 31 44

#### Reverted changes 

The following changes were reverted in https://github.com/Automattic/wp-calypso/pull/72560/commits/5c2d0053260c6698896e379f5226f434f296aed0 following [this feedback](https://github.com/Automattic/wp-calypso/pull/72560#pullrequestreview-1273650573). Keeping a record here for posterity.

<details>
 <summary>Changes to AnimatedIcon component ⤵️</summary>

* An optional `playUponViewportEntry` prop has been added to allow the possibility of the animation playing each time it become visible in the browser's viewport. This is necessary for use on the Stats page, where the animated icon is only visible after scrolling to the bottom of the page (and therefore easy to miss). I opted to make this an optional prop, as it's unlikely we'll _always_ want an animation to re-play when scrolling past it. 
*  It's now also possible to pass a json object to the component's `icon` prop. Previously, it was only possible to pass the icon's path as a string, but it's more straightforward to pass a json object from the `packages` directory. 
</details>

**Video:**

https://user-images.githubusercontent.com/2998162/215121362-2642be03-9c8d-4942-95cd-107b5ced5490.mov

#### Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

**Review by jsnmoon — CHANGES_REQUESTED** [review]
As much as it pains me to write this, the new animation appears to increase the stats bundle size by **22%** (+49289 B). This is in direct conflict with our current project goals (pejTkB-bb-p2#goals) and is hard to justify for animated icons.

Is there any way to mitigate this bundle size bloat?

It might be helpful here to split the animated icon changes into a separate PR so we can review and ship everything else contained in this PR.

**Comment by kangzj** [comment]
@jsnmoon Just a note here, as per the design for Odyssey #71820, the section is replaced with the following. That said, we should be able to strip it all? 

image

**Review by a8ck3n — COMMENTED** [review]
In my testing, this new QR code doesn't work when the user already has the Jetpack app installed. Instead of going to a web page or the App Store, the link is directed to the installed mobile app without any context, which is maybe a bit confusing.

Maybe a follow-up issue for the mobile app might be to exclude this URL from it's Universal Links implementation?

Not a blocker by any means. Just highlighting what feels like a confusing flow.

**Review by a8ck3n — APPROVED** [review]
Excluding my previous comment, this tests well for me.

As a follow-up, could you possibly update the Woo QR code as well, just to keep the appearance of the two images consistent?

I'd also be curious to know what tool you used to generate the codes.

**Comment by SiobhyB** [comment]
Thanks both!

@jsnmoon, it looks like my reply to your comment wasn't sent, sorry! I appreciate you pointing out the performance issues and absolutely agree that it's hard to justify the animated component in this case, especially given your team's priorities/goals. I believe we've optimised the component as much as we can in previous PRs, but can also put this on my todo list to investigate further at a later stage. For now, I agree it's best to keep the animations out of this PR. 👍 

@a8ck3n, thank you for the quick review 🙇‍♀️ the QR code was taken from the designs for other app-related Calypso components, so wasn't created by me. I agree that the flow is a little confusing when the app is already installed and will add that on my list of things to look into, thanks again!

**Pull request merged**
