### PR TITLE
Odie: Fix spacing and improve translations of disclaimers in user messages

### PR DESCRIPTION
**Pull request by stephanethomas**
This pull request fixes the following minor display issues in the disclaimers shown at the bottom of a message generated by an AI bot (just before the `Related Guides` section), when requesting help from the Support Assistant:
* Missing white space
* External arrow outside of sentence (after the dot)
* Missing trailing dot

#### Help center experience enabled

Before | After
------ | -----
image | image

#### Help center experience disabled

Before | After
------ | -----
image |  image

This pull request also concatenates those strings together, an approach usually recommended as it provides more context to translators.

#### Testing instructions

1. Run `git checkout fix/odie-user-message-disclaimers` and start your server, or access a [live branch](https://github.com/Automattic/wp-calypso/pull/96505#issuecomment-2483713297)
2. Click the question mark icon at the top of any page
3. Click the `Still need help?` button at the bottom of the modal box
4. Ask something, e.g. `how to change header on one page only ?`
5. Assert that the disclaimer is shown correctly now:
> Generated by WordPress.com's Support AI. AI-generated responses may contain inaccurate information. Learn more ↗.
6. Add `?flags=help-center-experience` at the end of the url, and hit <kbd>enter</kbd>
7. Repeat the same step, and assert that the disclaimer is shown correctly this time:
> Powered by Support AI. Some responses may be inaccurate. Learn more ↗.

### CODE REVIEW

**Review by AllTerrainDeveloper — APPROVED** [review]
LGTM!
I've even tested that the link appears correctly with different captions length.
image

But, I am wondering now if its also good to add a track events to the External Link, as the previous one has (Direct Escalation Link: `chat_message_direct_escalation_link_click`). @sirino What do you think? Also, is still a good task to getting use to the Help Center Wapuu experience.

Not saying it has to be done in this PR, it does not matter either in this or in the next.

**Comment by stephanethomas** [comment]
In the spirit of moving forward, I'm going to merge this pull request, but I'm happy to update that code to add Tracks events in another one if that's needed.

**Comment by stephanethomas** [comment]
Actually, I'm going to wait until the strings have been translated.

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/17009735

Some locales (Hebrew, Japanese) have been temporarily machine-translated due to translator availability. All other translations are usually ready within a few days. Untranslated and machine-translated strings will be sent for translation next Monday and are expected to be completed by the following Friday.

Thank you @stephanethomas for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/17009735).

**Pull request merged**
