### PR TITLE
Include description in suggestions.

### PR DESCRIPTION
**Pull request by budzanowski**
### Info 
This implements: #13004 

In some cases the descriptions looks nice:
image

In some cases it does not: 
image

In some cases there is nothing at all:
image

This will require also mobile view design - where there is no space for the description.

### CODE REVIEW

**Comment by folletto** [comment]
Pushed some changes:

1. Restyled the description, tweaked the font sizes for suggestions now that they are capitalized.
2. Color of description field present (missing `$`)
3. Remove the prefix `-`: this is the kind of thing that often is better be handled in CSS (`:before`) or just skipped relying on other visual distinctive factors as I did here.
4. Refactored a bit the CSS to be clearer about highlights and description. Introduced `flex`.
5. Made the description node to be visible only if not empty.
 
screen shot 2017-05-12 at 13 16 54

**Comment by kathrynwp** [comment]
I'm working on some of the wording issues now after discussion with @folletto – will update here when done.

In the meantime, just noticed that the descenders are getting cut off on smaller screens:

front page post form wordpress themes wordpress com

Screenshot from Firefox 53.0.2.

**Comment by folletto** [comment]
Ok, descenders are fixed ✅ 
Tested in Chrome, Safari, Firefox, Edge, IE11.

(There's still a slight height variation between browsers, but if I fix in one gets moved in the other, so I'll leave that for later).

**Comment by kathrynwp** [comment]
Here's what I've done for now:

- Checked all **Feature** descriptions and adjusted as needed – shortened, removed links, etc.
- Adjusted current **Subject** descriptions where possible – for some reason @folletto & I can't yet determine, the "Business" taxonomy is uneditable, so leaving alone for now.

**Next steps:**

- Descriptions are now in good enough shape to go live whenever you're ready. 
- I will fill in rest of blanks with Editorial's help and also have them look at the current ones now that they're going to be more visible to the public.

**Pull request merged**
