### PR TITLE
Reader: update post action icons

### PR DESCRIPTION
**Pull request by eoigal**
This first PR to change icons on Reader

Ref: pe7F0s-2gw-p2

## Proposed Changes

* Updates Post actions icons, Share, Repost, Comment & Like.

## Before
Screenshot 2024-10-30 at 17 38 42

## After
Screenshot 2024-10-30 at 17 38 25

## Why are these changes being made?

*

## Testing Instructions

* Go to calypso.live `/read` and confirm the post action icons render ok

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Comment by davemart-in** [comment]
Everything looks functionally okay to me. @crisbusquets mind reviewing this from the design side of things? Line widths for the repost icon feel a tad light compared to the others, but I'm not sure there's much we can do there.

**Comment by crisbusquets** [comment]
Thanks for the ping, @davemart-in !

In my initial PR I used the Core icon for `share`, which in my opinion is the one we should use:

Screenshot 2024-10-30 at 17 38 58

**Comment by davemart-in** [comment]
> In my initial PR I used the Core icon for share, which in my opinion is the one we should use

Oh, cool. I think that update helps the repost icon feel less out of place 

CleanShot 2024-10-30 at 14 27 19@2x

**Review by davemart-in — APPROVED** [review]
Changes look good to me!

**Pull request merged**
