### PR TITLE
Stats: Update Post Detail view components directories

### PR DESCRIPTION
**Pull request by alternatekev**
This PR moves
- `post.jsx`
- `module-post-months.jsx`
- `module-post-weeks.jsx`

into a `stats/post-detail` directory and changes the names a little:
- `post.jsx` is now `post-detail/index.jsx`
- `module-post-months.jsx` is now `detail-months.jsx`
- `module-post-weeks.jsx` is now `detail-weeks.jsx`

__To Test__
- Open up a stats page for a time period ( month/week/day )
- Click on a post in the "Post & Pages" component
- Verify the subsequent post detail page looks the same as it does on production

### CODE REVIEW

**Comment by timmyc** [comment]
I think we should do the following instead:

`post.jsx` -> `stats-post-detail/index.jsx`
`module-post-months.jsx` -> `stats-detail-months/index.jsx`
`module-post-weeks.jsx` -> `stats-detail-weeks/index.jsx`

There will likely be some duplicate scss between these components, but it will be nice to stick with structure/naming we have done so far in the other PRs

**Comment by alternatekev** [comment]
@timmyc I went ahead and made those updates if you could give it another once-over.

**Comment by timmyc** [comment]
@alternatekev I did some further fixing/cleanup in all of the files touched.  This could use some more live testing at this point.

**Comment by alternatekev** [comment]
:+1: Works as expected.

**Pull request merged**
