### PR TITLE
Copy Site: add celebratory banner 'NOTICE_CELEBRATE_SITE_COPY' to home

### PR DESCRIPTION
**Pull request by sejas**
#### Proposed Changes

* Display a new celebratory banner after copying a site and landing on `/home/{SITE_ID}`

#### Testing Instructions

* Apply D99397-code to your sandbox.
- Go to /sites.
- Open the actions menu on a business site.
- Click on Copy Site.
- Follow the normal copy site process through the checkout.
- When you land on the site home after finishing the copy site process, observe the new notice in the UI.
- Click on `Show site setup`
- Observe the site setup.

#### Screencast

https://user-images.githubusercontent.com/779993/214860128-e73ae138-0f18-4ace-bc79-6a3e81c17d66.mp4

#### Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

Related to:
- D99397-code
- Closes: https://github.com/Automattic/dotcom-forge/issues/1545

### CODE REVIEW

**Review by kozer — APPROVED** [review]

**Review by danielbachhuber — APPROVED** [review]
Looks great 👍 I made a minor text tweak.

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/7776345

Hi @sejas, could you please edit the description of this PR and add a screenshot for our translators? Ideally it'd include all of the following strings:
- `Now it’s your turn to make it unique. Don't worry, we'll guide you through setting up and launching this site.`
- `Your copy is ready!`

Thank you in advance!

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/7776345

Hi @sejas, could you please edit the description of this PR and add a screenshot for our translators? Ideally it'd include this string: `Now it’s time to choose a name and customize a few settings to make it unique.`

Thank you in advance!

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/7776345).

**Pull request merged**
