### PR TITLE
Fix state not being up to date in domains step

### LINKED ISSUE #94432: Stepper: Not reaching checkout
### Details

Follow the video to reproduce the issue:

It should happen when selecting a custom domain and then premium plan

https://github.com/user-attachments/assets/1baf713f-3231-49cd-92fe-bdb4826ffd67

### Checklist

_No response_

### Related

_No response_

### PR DESCRIPTION
**Pull request by renancarvalho**
Related to https://github.com/Automattic/wp-calypso/issues/94432
Fixes #94432

## Proposed Changes

* Domain's step is submitting empty data and therefore breaking the checkout, this PR addresses it. Like in [Plans step ](https://github.com/Automattic/wp-calypso/blob/trunk/client/landing/stepper/declarative-flow/internals/steps-repository/unified-plans/index.tsx#L68), we had to handle state changes a bit differently. This PR does the same for Domains.

## Why are these changes being made?

* Checkout was not working for new users because domains step was submitting empty data
* for new users. Check the video in the [issue.](https://github.com/Automattic/wp-calypso/issues/94432)

## Testing Instructions

* Using incognito, navigate to {live-link}/setup/onboarding
* Create a new user with email
* Pick a paid domain 
* Select a paid plan
* Checkout should work fine
* Finalize the purchase and make sure everything you selected is indeed purchased.
* Check free plans and free domains
* Check own domain
* Check choose domain later
* Check free plan together with paid plan

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Review by agrullon95 — APPROVED** [review]
Use my domain is not working but that is expected until we merge: https://github.com/Automattic/wp-calypso/pull/94314

The rest of the flows mentioned in the testing instructions are working well for me. I'm able to reach the checkout screen with the correct cart items. I didn't test purchasing the cart items, so we should double-check that.

**Comment by renancarvalho** [comment]
@heavyweight would you be interested in taking a look at this PR?

**Comment by renancarvalho** [comment]
Good work @agrullon95 Navigation using the back button seems fine 👍 

Just noted:

On live link -> /start it looks broken

image

Also, the translations are not correct 

Stepper
image

Start in production
image

**Review by heavyweight — APPROVED** [review]
This fixes the issue 👍
Tested and didn't find any issues.
Can anyone retest? Since this PR changed a bit

**Pull request merged**
