### PR TITLE
Fix post editor function binding

### PR DESCRIPTION
**Pull request by gyoshev**
Addresses function binding in `render`, as mentioned in #3883. Also fixes lint warnings in post-editor.jsx.

### CODE REVIEW

**Comment by aduth** [comment]
Hey @gyoshev , thanks for these changes! They look and work great. I'm sorry to nitpick, but one small revision I'd like to see is renaming `switchEditorDesignMode` to either `switchEditorVisualMode` or `switchEditorTinyMceMode`. "Visual" and "TinyMCE" are already used in the code and UI to indicate this tab, but we're not using "Design" anywhere. I worry adding a third descriptor may confuse developers maintaining this code in the future.

**Comment by gyoshev** [comment]
Thanks, @aduth! I switched it to `Visual`.

**Comment by aduth** [comment]
@gyoshev , your latest changes look great! I'm marking this as Ready to Merge and will plan to merge the changes Monday morning.

In the meantime, or at least as future reference, if you have a moment to squash/fixup your last commit and force-push to the branch, we typically include this in our workflow in order to keep commit history clean.

https://github.com/Automattic/wp-calypso/blob/7e73206/.github/CONTRIBUTING.md#lifecycle-of-a-pull-request

Thanks again!

**Comment by gyoshev** [comment]
Thanks, @aduth ! I squashed the rename, but kept the lint warnings in a separate commit. The branch has been rebased over the latest `master`.

**Pull request merged**
