### PR TITLE
Fixing minor UI issues with buttons

### PR DESCRIPTION
**Pull request by ernestoSk13**
Related to #

## Proposed Changes

* In this PR I'm adding a few UI improvements that are valid for Woo Blaze and Jetpack Blaze

## Testing Instructions

- [ ] First, use Woo Blaze or Jetpack Blaze and go to the Advertising posts lists. Make sure that the buttons do not have a weird gray shadow
Screenshot 2024-03-01 at 16 17 40
Screenshot 2024-03-01 at 16 17 52

- [ ] Go to woo blaze, pick a campaign, go to the campaign details page and verify that the "Promote Button" is growing correctly when changing to a mobile view.
Screenshot 2024-03-01 at 16 18 11

- [ ] Go to a Jetpack Blaze campaign details page and verify that the preview button matches with the Jetpack primary (green) 
Screenshot 2024-03-01 at 16 18 31

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Review by sbarbosa — COMMENTED** [review]
The changes look good @ernestoSk13 . 

I checked and I think we also need to fix the Details button that appears in the campaign list page. The display is correct, but the hover style is not.

**For jetpack**, the correct hover for he button is an underline, like this:
Screenshot 2024-03-04 at 15 33 36

In campaign details, it looks like this:
Screenshot 2024-03-04 at 15 33 42
It appear to have a grey color for the text and some shadows. I remember we had to do an specific override in Jetpack Blaze to get the hover behaviour for the promote page, I think you can do something similar with this button.


**For WooCommerce**: The post page looks like this:
Screenshot 2024-03-04 at 15 33 58

And in the campaign list page, it appears that a border is added:
Screenshot 2024-03-04 at 15 34 04

**Comment by ernestoSk13** [comment]
hi @sbarbosa  I have fixed this wrong behavior in my latest commit :)

**Comment by ernestoSk13** [comment]
hi @sbarbosa  I have also fixed the issue with the buttons background :)

**Comment by sbarbosa** [comment]
Hi @ernestoSk13 , I tested this again in Woo Blaze and Jetpack Blaze, but there are still some details. Let me share them with you:

1- For Woo Blaze, the background of the buttons didn't work and still appears as gray, and when you hover the promote button, it appear to change colors (that doesn't happens in the details button).
Screenshot 2024-03-05 at 14 03 34
Screenshot 2024-03-05 at 14 03 57
Screenshot 2024-03-05 at 14 03 28

2- This happens for all of them (jetpack, WPCOM and Woo). The contact support button in the details page, when it start appearing at the bottom, it appears with different styles than in mobile. It like it gains a border when you shrink the screen
Woo or WPCOM shows the correct background but only in one of the views:
Screenshot 2024-03-05 at 14 04 35
Screenshot 2024-03-05 at 14 04 51
Screenshot 2024-03-05 at 14 06 30
Screenshot 2024-03-05 at 14 06 37


3- The cancel button doesn't look good in any of the views. In some it appear to be shorter than it should:
Screenshot 2024-03-05 at 14 04 28
Screenshot 2024-03-05 at 14 06 25

**Comment by ernestoSk13** [comment]
hi @sbarbosa  hopefully this last commit will be the good one :) I have solved the mentioned issues

**Review by sbarbosa — COMMENTED** [review]
Hi @ernestoSk13. I ran another test and the cancel button still has some design problems.

**In Woo:**
Screenshot 2024-03-07 at 10 17 24
Screenshot 2024-03-07 at 10 17 31

In Jetpack:
Screenshot 2024-03-07 at 10 18 27
Screenshot 2024-03-07 at 10 18 34
Screenshot 2024-03-07 at 10 18 44

**Review by sbarbosa — APPROVED** [review]
Thanks for the changes @ernestoSk13. It looks great!

**Pull request merged**
