### PR TITLE
Guided tours: add an one-step guided tour for the activity log

### LINKED ISSUE #26421: Activity Log: Add Welcome Banner
p9rlnk-p5-p2

### PR DESCRIPTION
**Pull request by roccotripaldi**
This PR will introduce a simply, one-step guided tour for the activity log.

It fixes #26421 by introducing the activity log with a fun, easily dismissible tour dialogue.

## For Jetpack sites:

screen shot 2018-08-08 at 12 27 55 pm

## For wordpress.com sites:

screen shot 2018-08-08 at 12 27 38 pm

To test:

1.  Visit https://calypso.live/?branch=fix/26421-activity-log-guided-tour
2. Ensure the tour popups appear in `stats/activity` for free sites

### CODE REVIEW

**Comment by michelleweber** [comment]
Wee edit:

Keep tabs on all your site's activity -- plugin and theme updates, user logins, setting modifications, and more.

**Comment by roccotripaldi** [comment]
Thanks @michelleweber - copy and screenshots updated.

**Comment by roccotripaldi** [comment]
@MichaelArestad - this PR has 2 different tours, one for Jetpack sites, and one for .com sites.
This causes some strangeness when switching between a Jetpack site and .com in the site picker.

Would you be ok with having one tour with more generic copy that can apply to both types of sites?

**Comment by enejb** [comment]
I tested this and the tour did popup for the free site as expected. Once I clicked "Got it, thanks" button. It goes away on all the free sites. 

When I was testing it across the different screen widths. The guided tour banner was not always properly aligned. 
See:

screen shot 2018-08-08 at 11 10 08 am
screen shot 2018-08-08 at 11 09 57 am

**Comment by MichaelArestad** [comment]
@enejb when you tested it on various screen widths, were you loading the view at that width or resizing it after it had loaded?

**Comment by enejb** [comment]
Also I think we should make the (Learn More) link the colour white for more contrast. At least that is what I saw when I was looking at the tour link in the current editor.

**Comment by enejb** [comment]
I tested it both ways and it produced the same result. I didn't test it yet
with a real device

**Comment by MichaelArestad** [comment]
RE: Learn more, we could even make that a secondary button (already baked into the component).

@sirreal looks like the guided tour bubble is even having positioning issues on a predictable element/layout.

**Comment by sirreal** [comment]
> @sirreal looks like the guided tour bubble is even having positioning issues on a predictable element/layout.

Yep, we've seen that although haven't taken measures to address them yet:
- https://github.com/Automattic/wp-calypso/issues/25933
- https://github.com/Automattic/wp-calypso/issues/25932

cc: @jsnajdr

**Comment by MichaelArestad** [comment]
Well I think we can launch as is with the premise that the Guided Tours need fixing.

**Comment by roccotripaldi** [comment]
Is it possible to have different targets for different devices?
Or to hide altogether on small screens?

**Comment by joanrho** [comment]
Thanks @roccotripaldi! Can you please change the double en-dash `--` in the copy to an em-dash `—`? Other than that, LGTM!

screen shot 2018-08-08 at 3 26 45 pm

**Comment by sirreal** [comment]
> Is it possible to have different targets for different devices?
> Or to hide altogether on small screens?

@roccotripaldi Some tours are doing that already: https://github.com/Automattic/wp-calypso/blob/master/client/my-sites/checklist/onboardingChecklist.js#L138-L140

Ideally, we'd invest the time to provide a strong guided tour experience mobile 😉 

Related: p1533742580000542-slack-calypso-guided-tours

**Pull request merged**
