### PR TITLE
Plans Step: TS and function form

### PR DESCRIPTION
**Pull request by chriskmnds**
Related to #

## Proposed Changes

- Transforms the Plans step from the Start framework into TS and function form.
- Files for serving plans-step in both Start and Stepper are now migrated to `stepper/../unified-plans/` and imported from there (and re-exported from Start for other steps). So that's the new home, including styles & tests.
  - Some cleanup will need to happen once Start is fully deprecated/removed - essentially removing the respective `AsyncLoad` and whatever properties are associated. 
  - The previous Plans step in Stepper can similarly be removed in place of this "unified" one. This can happen before Start removal to get everything (the other Stepper flows) aligned over the same step component. We can rename "unified-plans" to just "plans" then.
- Updated tests:
  - kept a bare-bones high-level suite for the plans step (which can be extended further, if need be)
  - adopted the remaining tests from Start on the `buildUpgradeHandler` step action directly

## Why are these changes being made?

This step has been imported and used in Stepper, which is a fully typed system. The code remained in its arcane form, potentially causing unnoticed inconsistencies in behavior/tracking/etc. A quick surface look points to a few properties wrapped from the old signup (Start) not passed from Stepper.

## Testing Instructions

* Need general sanity checks on the Plans step in onboarding flows: 
  * `/start/plans`
  * `/start/onboarding-pm/plans`
  * `/setup/onboarding/plans`
* Confirm buttons work, purchasing a plan
* General sanity check of respective flows overall as the plans step contains back button logic, etc. So back/forth to domains & checkout, etc.

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
    - [ ] For UI changes, have we tested the change in various languages (for example, ES, PT, FR, or DE)? The length of text and words vary significantly between languages. 
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Comment by escapemanuele** [comment]
Sure thing @chriskmnds, thanks for moving through all the difficulties ✌️

**Comment by chriskmnds** [comment]
@escapemanuele I'm weirdly surprised this actually works so far already 😮 

TODO:

- [ ] Migrate the step code and styles under `client/landing/stepper/declarative-flow/internals/steps-repository/unified-plans`
- [ ] Import and use in Start instead
- [ ] Test test test

**Comment by chriskmnds** [comment]
We are ready to review and test @escapemanuele ! 

cc @Automattic/martech-decepticons if you'd like to pitch in with a review 🙏

**Comment by agrullon95** [comment]
@chriskmnds - Thanks for handling this refactor.
I tested the flows you provided in the testing instructions to create free + paid plans sites and everything is working well.
I'm going to test again tomorrow to see If I notice any issues.

**Review by agrullon95 — APPROVED** [review]
I tested again and I found one difference on the plans page:
It is reloading the Plans component when I use the dropdown to change the plan interval.
Everything else is working well and is identical.

https://github.com/user-attachments/assets/aefae6cb-a3f1-4c4e-b665-220b3615ec60

**Comment by alshakero** [comment]
Thoroghouly tested /setup and looks good. Now regression-testing /start.

**Review by alshakero — APPROVED** [review]
Tested /setup and /start thoroughly on desktop and mobile and everything seems to work.

**Comment by jeyip** [comment]
## Testing
### Requirements

For each of the flows listed below:
- Verified header price and billing timeframe price with production
- Verified pricing for monthly and yearly pricing
- Ensured that a plan could be purchased
- Spot checked desktop and mobile
- Looked at pro rated pricing on the /plans page
- Spot checked the spotlight plan on the /plans page
- Back button behaves as expected

Flows:
- [ ] /start
- [ ] /start/onboarding-pm
- [ ] /setup/onboarding/plans
- [ ] /plans

### Browsers
- [x] Chrome

**Review by jeyip — APPROVED** [review]
I haven't looked at the code, but this PR smoke tests well for the critical pieces of functionality that I've touched 👍

**Comment by alshakero** [comment]
Man, that testing is way generous. Thank you so much!

**Comment by chriskmnds** [comment]
> Man, that testing is way generous. Thank you so much!

Yeah, @jeyip 's testing is at another level! I always enjoy seeing these review comments. It's like you know peace of mind is coming 😁 

Thank you both for taking over here! ❤️

**Pull request merged**
