### PR TITLE
SSO: Add placeholders for site name

### LINKED ISSUE #5686: Jetpack SSO: Add placeholders while validating SSO
Before we validate the SSO site ID and nonce, we don't have any site specific information. In the current design, that means that there are weird spots like this:

screen shot 2016-05-30 at 10 11 21 pm

### PR DESCRIPTION
**Pull request by ebinnion**
Closes #5686.

This adds placeholders while we are making the SSO validation request.

cc @rickybanister for design review and @lezama for code review.

To test:

- Checkout latest Jetpack master
- Checkout `update/jetpack-sso-site-name-placeholders`
- Go to `$site/wp-admin`
- Click "Log in with WordPress.com button"
- Make sure you see placeholders and that placeholders go away

### After
Note: Video is slowed to 25% of normal speed.

sso_placeholders
[Higher resolution video](https://cloudup.com/cPfdQHFMUTL)

### CODE REVIEW

**Comment by rickybanister** [comment]
@ebinnion this is great, but I think in my comment on the issue I suggested making the entire subheading, not just the site name a placeholder.

Now that I think about it, it would feel much more elegant to simply make the text transparent until it loads instead of pulsing. The site card already gives the indication of loading.

Can we just set the alpha or opacity to `0` until we get the data?

**Comment by ebinnion** [comment]
@rickybanister For making the text transparent, does that include the text in the card and the site link in the footer as well?

**Comment by rickybanister** [comment]
Yes, the transparent text should still take up space, leaving the overall layout of the page fairly normal, and when we get data the text will appear. Magic.

**Comment by ebinnion** [comment]
@rickybanister – I pushed an update that I believe addresses your feedback.

sso_placeholders_update
[Higher resolution video](https://cloudup.com/chGwlIS63J1)

**Comment by rickybanister** [comment]
Perfect! Thanks so much @ebinnion

**Comment by lezama** [comment]
Sir, :shipit: sir

**Pull request merged**
