### PR TITLE
All Sites: update icon composition

### PR DESCRIPTION
**Pull request by mtias**
Trying:

image

cc @jasmussen @folletto

### CODE REVIEW

**Comment by mtias** [comment]
A bolder option for reference:

image

**Comment by mtias** [comment]
In the context of site picker, it aligns with the search box margins:

image

**Comment by jasmussen** [comment]
I like the bold option, but the less bold option is clear and easy to read too. Thumbs up for either of those options.

**Comment by mtias** [comment]
Dropping one more that just leans on the circle / square distinction:

image

**Comment by folletto** [comment]
I'll feedback from three different perspectives:

1. I feel the compound version gives a better idea that it's a "collection of items" at a glance
2. the edge-to-edge look is nice in the selected state, but it's odd in the list
3. using the avatar seems to me simplifying a lot the look, and the circle-square differentiation is starker

I'd probably edge toward preferring the circle avatar. In that case however I'd tweak the hover state a bit to make sure the counter always shows up. ;)

**Comment by rickybanister** [comment]
I think I prefer option number 1. 

From my time in HG and from support rotation stuff I seem to remember many people had the same image for their site icon and avatar—this to me rules out the circle avatar to represent 'all _my_ sites' because someone might only have their primary site and one other. Let's stick with a composite.

**Comment by folletto** [comment]
Good point :+1:

**Comment by mtias** [comment]
Merging this.

**Pull request merged**
