### PR TITLE
Update/decouple upload button from themes list

### PR DESCRIPTION
**Pull request by budzanowski**
### Information
Upload was previously part of larger component named `ThemeUploadCard` that was then used inside themes list. This was working fine in general. Big challenge of two lists design is managing dual `Sorry no themes found` screen. Proposed solutions will create scenarios when `ThemesUploadCard` is not shown - and the Upload button would be missing. We want this button to be always visible for sites for which it makes sense. The solution to this is to decouple `Upload` button from `ThemesUploadCard` and add it to the `ThemeShowcase` component. This also fixes problem of for which list to show the button. That was managed by props and now it does not even need managing. 

Additionally after removing Upload button the `ThemesUploadCard` name did not reflect that this component is right now basically a header for themes list. Its name was changed to match new status.
As a bonus it was also refactored to ES6 JS.

Intentions where to not change anything in how component looks. Unfortunately one change needed to be done. Now `Upload` button is always visible and newer is a placeholder( loading state). This change is a consequence of moving `Upload` button outside `ThemesList` where it no longer has access to themes query state and number. 

Additional change in this PR is that `ThemesList` header( label + counter ) are now also visible in production - it is no longer tied to new upload functionality so it can go live.

### Testing
Open `/desing` of various sites:
- logged out: no Upload button, proper list header
- multi-site: no Upload button, proper list header
- single-site: Upload button, proper list header + button leads to upload page
- single-site jetpack: two list have proper headers, only top list has button + button works

### CODE REVIEW

**Comment by folletto** [comment]
Interesting approach, I didn't expect to work with just `float`. Nice one. :) 

Tested in Chrome:

1. .com Site → Themes — ✅ 
2. Jetpack Site → Themes (top only) — ✅ 
3. All Sites → Themes (no button) — ✅ 
4. Logged Out → Themes (no button) — ✅ 
5. Mobile — ✅ 

Just one thing, the alignment is slightly off, it should be vertically centered (same space above and below). A `margin-top: 5px;` or something like that should do it:

screen shot 2017-02-15 at 14 09 54


---

As an aside... now that we have the site picker, we could in theory also show the button on All Sites. What do you think?

**Comment by seear** [comment]
> we could in theory also show the button on All Sites. 

Yeah, I think so.

Could be a separate PR, or do it in this one, either way is fine.

**Comment by budzanowski** [comment]
I agree that we should connect site picker. But in another PR - I need to learn how the process actually works :) 
As for alignment I have added additional breakpoint to CSS to match other things that are happening during window size change.

**Comment by folletto** [comment]
> I agree that we should connect site picker. But in another PR - I need to learn how the process actually works :)

I didn't mean that. It can be just a link to the page: the site picker will simply show up! :)

**Comment by folletto** [comment]
screen shot 2017-02-16 at 10 56 44

Tested on Chrome, Safari, Firefox — design wise 👍

**Pull request merged**
