### PR TITLE
Reader: fix export/import dropdown alignment & update icons

### PR DESCRIPTION
**Pull request by simison**
## Proposed Changes

- Change from Gridicons to core icons
- Undo all the custom CSS and props managing icons; it was complex and wasn't used for anything

Before
image

image

After

Screenshot 2024-08-08 at 13 42 04

Screenshot 2024-08-08 at 13 39 08

## Why are these changes being made?

*

## Testing Instructions

* Visit /read/subscriptions and see the import/export dropdown

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Comment by simison** [comment]
Still some text alignment weirdness going on here: 

image

**Review by pkuliga — APPROVED** [review]
Thanks!

**Comment by simison** [comment]
Removed also `hasTranslation`checks which were a year old from https://github.com/Automattic/wp-calypso/pull/79373

**Comment by simison** [comment]
Went ahead and removed the Gridicons, custom props, custom icons, and bunch of CSS from here. Just pulling from core icons and passing to `icon` prop is way simpler.

**Comment by pkuliga** [comment]
Nice cleanup! 💪

**Pull request merged**
