### PR TITLE
Gutenboarding: Add preview to font selection page in mobile view (drop-down variant)

### LINKED ISSUE #40900: Gutenboarding: mobile style picker (add preview)
In [Gutenboarding](https://wpcalypso.wordpress.com/new), the style picker should look like this on mobile (with preview included):

style-picker-with-preview

### PR DESCRIPTION
**Pull request by andrewserong**
This PR is a variant on PR #41732 where we added a preview to the mobile view of the Style step in Gutenboarding. In this variant, instead of listing all the buttons below the preview, we list a drop-down button _above_ the preview.

Because we need to display correctly rendered font pairs in the drop-down, I couldn't use the native `select` element or the pre-existing WordPress components for `SelectControl` or `Panel`/`PanelBody`. Instead, I've gone with a simple approach of a button that displays the selected fonts, and when you click it, we display the set of font buttons styled to look more like they're in a drop down list (similar to the domain categories drop down). Selecting a font then closes the drop down.

#### Changes proposed in this Pull Request

* Add preview to style step.
* Add drop-down button on mobile to show/hide the font selection buttons, and style them to look like the drop-down used in domain categories.
* Add fixed footer bottom-bar-mobile component.

##### Screenshot

style-preview-dropdown-try-2-small

#### Testing instructions

* Go to /new and complete the steps until you get to the Style step.
* Test in a variety of viewport sizes
* Make sure the desktop viewport layout is unaffected by this PR
* Test on a real device, how does it feel to use?

Fixes #40900 
Related to PR #41732

### CODE REVIEW

**Comment by p-jackson** [comment]
I was wondering if the font preview in the control would be an issue :/

Personally I'm finding the borders still being around each font button a little confusing. The domain category drop down is similar to what we want I think, with a border around all the options.

Screenshot 2020-05-07 at 4 25 16 PM


Thing is it's a custom control that isn't easily reusable. And this change is nice and quick ...

[I think we might be able to get most of the way there with only a few extra rules](https://gist.github.com/p-jackson/d29489689b19f89e1285dff23d8b01d8). There's some `!important` overrides that need to be dealt with though to get the selected item styling working 😬 

To me it also feels like the dropdown should auto close when a selection is made, but I get how a user might be able to scroll their phone so both are visible at the same time, and clicking through all the options and previewing would work.

**Comment by andrewserong** [comment]
Oh, great suggestions, thanks @p-jackson (and for providing the example diff)! I'll have a play and see if we can get it to be more cleanly like the domain category dropdown.

**Comment by andrewserong** [comment]
I've updated this PR so that it's looking more like the drop down used in the domain categories (thanks @p-jackson!): 

style-preview-dropdown-try-2-small

**Comment by andrewserong** [comment]
Great, thanks @dubielzyk! I'll merge this in and close out the other PR.

**Pull request merged**
