### PR TITLE
Add ActivityLogBanner component to show progress/status of restores

### PR DESCRIPTION
**Pull request by dereksmart**
Will close out #14664

In progress until it's styled.  

This adds a component to show the status a Rewind restore.  

To Test: 
Since it's not yet connected to any real state, you can test the component UI by changing the default props and viewing in `/stats/activity/:site_id`

### CODE REVIEW

**Comment by sirreal** [comment]
My initial impression is that there are really two unique components here that don't really share data or structure. I'll work on a proposal that addresses this.

**Comment by dereksmart** [comment]
@sirreal I was thinking the same

**Comment by sirreal** [comment]
☝️ Check out an alternate take in #14715

**Comment by dereksmart** [comment]
Replaced by #14715

**Pull request closed without merging**
