### PR TITLE
Plans: Update active plan icon

### PR DESCRIPTION
**Pull request by mikeshelton1503**
We created a new version of the plans icons (added color) when we created the free trials. To keep things consistent we decided it would be best to also use that same icon to indicate the current plan (for non-trials).

**Before:**
image

**After:**
image

I also made this change for the Jetpack plans as well, although I wasn't sure if I should or if maybe they should be different colors. cc @justinkropp

### CODE REVIEW

**Comment by stephanethomas** [comment]
We should **really** use CSS to tweak these icons instead of introducing [new files](https://github.com/Automattic/wp-calypso/tree/add/feature-plan-icon/public/images/plans) whenever we need a new variation - especially since we're focusing on performance these days.

**Comment by mtias** [comment]
Also, instead of adding an extra request just create sub-components that render the svgs inline.

**Comment by mikeshelton1503** [comment]
> We should really use CSS to tweak these icons instead of introducing new files whenever we need a new variation - especially since we're focusing on performance these days.

You're right. I know we discussed doing this, have you made any progress on that? If not I can give it a shot.

>Also, instead of adding an extra request just create sub-components that render the svgs inline.

:+1: I might need help with that but I'll let you know!

**Comment by mtias** [comment]
Sure thing! There's a few examples in the code: https://github.com/Automattic/wp-calypso/blob/master/client/my-sites/site-settings/start-over/index.jsx#L51

**Comment by lancewillett** [comment]
Hi @mikeshelton1503 — OK to close this one (it looks inactive)?

**Comment by mikeshelton1503** [comment]
This one fell by the wayside and it now no longer necessary given changes to the plans page that have already happened and will be happening. Closing.

Thanks for the nudge @lancewillett

**Pull request closed without merging**
