### PR TITLE
Reader: Fix j and k keyboard shortcuts for next and previous in refreshed streams

### LINKED ISSUE #9074: Selected card state for keyboard shortcuts
In the current Reader a "selected" card looks like this. (Note the blue border.) This is used for navigating by keyboard (j/k).

screen shot 2016-11-01 at 3 31 35 pm

If we want to enable keyboard navigation in the refreshed Reader, we'll need a design to show a "selected" card. So I propose this:

sream-card-selected2

sream-card-selected

Notes: The color is standard WordPress blue (#0087be). The border is exactly 20px around the entire card. This means the grey lines above and below the post turn blue (or are covered by the new border). 

The box also extends 20px to the left and right of the card. (I tried simply turning the lines above and below the card blue, but don't think it's enough to show that post has been selected.)

I realize this may complicate the CSS, but hopefully it's doable? Thoughts, @blowery & @jancavan?

### PR DESCRIPTION
**Pull request by blowery**
Teach the refresh cards about the is-selected prop and add new styles to indicate the selected post.

Fixes #9074

### CODE REVIEW

**Comment by blowery** [comment]
keyboard shortcuts

**Comment by blowery** [comment]
@fraying @jancavan It's not quite the treatment that was outlined in #9074, but it's much less disruptive to the overall layout to use a pseudo-element to the side of the actual content.

If we really want to make the surrounding box work, we can, it'll just require rejiggering a good part of the current card layout. This at least gives us a starting point.

**Comment by blowery** [comment]
@fraying @jancavan going to land this so that it works. If we want to revisit the marker in another PR, we certainly can.

**Comment by jancavan** [comment]
> If we really want to make the surrounding box work, we can, it'll just require rejiggering a good part of the current card layout.

Yeah, I imagined that.

I personally still prefer the border around the card since it's more obvious it's selected, but revisiting sounds good 👍

**Comment by fraying** [comment]
Agreed. Totally cool with this as an interim solution.

**Pull request merged**
