### PR TITLE
Tiled galleries: Disable captions

### PR DESCRIPTION
**Pull request by sirreal**
Captions in Tiled Galleries closely match core gallery captions. They are functional, but present many challenges such as #29706 

Disable captions for now by commenting them out.

Via p1545949443175900-slack-jetpack-gutenberg

#### Changes proposed in this Pull Request

* Disable captions

#### Testing instructions

* Verify that captions are not rendered.
* Verify that you can create a block from this branch, then load it with no parse/validation errors on a branch with captions (current master).

### CODE REVIEW

**Comment by sirreal** [comment]
Not that this invalidates existing blocks with captions. I do not expect restoring captions in the future to invalidate posts without captions.

**Comment by simison** [comment]
More `captionSelected` code to be commented out here:

https://github.com/Automattic/wp-calypso/blob/c9255b690530a5729d3a31f01764a79755093432/client/gutenberg/extensions/tiled-gallery/gallery-image/edit.js#L47-L51

**Comment by MichaelArestad** [comment]
This works for me

**Comment by ockham** [comment]
Going to rebase

**Comment by ockham** [comment]
> More `captionSelected` code to be commented out here:
> 
> https://github.com/Automattic/wp-calypso/blob/c9255b690530a5729d3a31f01764a79755093432/client/gutenberg/extensions/tiled-gallery/gallery-image/edit.js#L47-L51

2053b4795f

**Comment by ockham** [comment]
I'll merge on behalf of @sirreal and @simison

**Comment by sirreal** [comment]
Thanks for bringing this home, folks 👍

**Pull request merged**
