### PR TITLE
Activity Log: illustration and message for initial sync

### LINKED ISSUE #18803: Empty content state for initial sync
Let's keep the empty content state pretty simple for now. Folks are unlikely to see this anyway. It should use the EmptyContent component and look like this:

image

Here is the necessary SVG: https://cloudup.com/c-IL1cJp8il

### PR DESCRIPTION
**Pull request by eliorivero**
Fixes #18803

captura de pantalla 2017-10-19 a la s 19 00 26

### CODE REVIEW

**Comment by MichaelArestad** [comment]
Nice! Thanks for getting this in! It was a pain to test, but got it done.

I pushed a change to use the EmptyContent component's title and text. This will make it remain consistent with other EmptyContent implementations and, should EmtpyContent be updated, it will remain consistent. I would love that `<br>` back in there, but I couldn't figure out how and can live without it.

image

**Comment by eliorivero** [comment]
Nice. I didn't use the title in EmptyContent because it wasn't similar to the original mockup but I very much prefer to use it. I'll look into adding the `br`.

**Comment by eliorivero** [comment]
Done!

captura de pantalla 2017-10-20 a la s 15 28 43

**Comment by MichaelArestad** [comment]
@eliorivero nice! Thanks!

**Comment by dmsnell** [comment]
Evidence is mounting that we have separate components here…

 - A _page_ or _section_ component which renders headers and footers
 - One of several main content components based on the state of rewind and activity
    - Syncing for the first time
    - Loading activity for month
    - No activity for month
    - Stream of activity for month

**Comment by eliorivero** [comment]
Can we please stick to the PR scope?

**Pull request merged**
