### PR TITLE
Remove Jetpack Starter from pricing page

### PR DESCRIPTION
**Pull request by CodeyGuyDylan**
## Proposed Changes

* Remove Jetpack Starter pricing card from the pricing page
* Remove some backend logic related to Jetpack Starter
* Remove Starter from the comparison page

P2: pbNhbs-7hz-p2

## Testing Instructions

1. Use the Calypso Green live branch
2. Go to `/pricing`
3. Make sure Jetpack Starter does not show up
image
4. Go to `/features/comparison` and make sure Starter does not show up here as well
image
5. Make sure the title and subtitle have been updated to only include bundles
image
6. If you do not already have a Jetpack Starter subscription, go to https://wordpress.com/checkout/jetpack/jetpack_starter_yearly and purchase one. Then go to `/me/purchases` and make sure the plan loads correctly here
image
image

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

**Review by IanRamosC — APPROVED** [review]
The proposed changes work as expected.
I left a comment here pbNhbs-7hz-p2#comment-16530 about the comparison page, that also included Backup (before we had Starter), and would be good to wait and see if add that again, or just leave the current bundles (Free, Security, and Complete).
Other than that, it looks good.

**Comment by CodeyGuyDylan** [comment]
> I left a comment here pbNhbs-7hz-p2#comment-16530 about the comparison page, that also included Backup (before we had Starter), and would be good to wait and see if add that again, or just leave the current bundles (Free, Security, and Complete).

Rob said here: pbNhbs-7hz-p2#comment-16507 to just leave it as the 3 columns for now 😄

**Comment by CodeyGuyDylan** [comment]
I also see that Rob replied to your comment, I'll go ahead and update the title in this PR

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/8353910

Thank you @CodeyGuyDylan for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/8353910).

**Comment by niranjan-uma-shankar** [comment]
@Automattic/jetpack-martech This PR seems to have removed the WPCOM legacy Starter plan from the "My Plans" page. We're restoring it in https://github.com/Automattic/wp-calypso/pull/91604. Just an FYI, in case you want to look at removing something else in that file for the Jetpack Starter.

**Comment by IanRamosC** [comment]
> @Automattic/jetpack-martech This PR seems to have removed the WPCOM legacy Starter plan from the "My Plans" page. We're restoring it in #91604. Just an FYI, in case you want to look at removing something else in that file for the Jetpack Starter.


Ooops. 😅 Thanks for fixing that and for the new method name, @niranjan-uma-shankar. 🙇🏾‍♂️

**Pull request merged**
