### PR TITLE
Jetpack Onboarding: Add new illustrations

### PR DESCRIPTION
**Pull request by tyxla**
This PR introduces the new illustrations that will be used in the Jetpack Onboarding flows. Borrowed from #17094, but moved to separate svg assets, cleaned up and optimized.

The following illustrations are being introduced:

**Site Type - Personal:**

**Site Type - Business**

**Contact Us**

**Home Page - Static**

**Home Page - News(blog)**

To test:
* Load each of those in an SVG viewer or your browser.
* Verify they look as expected.
* Verify they're optimal for production.

### CODE REVIEW

**Comment by tyxla** [comment]
@MichaelArestad let me know if there's anything I've missed, as I borrowed those out of #17094 rather than exporting them from the source files.

**Comment by drw158** [comment]
The second illustration does not adhere to our contrast guidelines

screen shot 2017-12-01 at 9 35 29 am

**Comment by MichaelArestad** [comment]
@tyxla to fix the pie chart contrast, just make that path's fill white (#ffffff)

**Comment by MichaelArestad** [comment]
And I think you might be better off making them from optimized source files. I'll see if I can dig them up. Those weren't in great condition last I checked.

**Comment by tyxla** [comment]
I've updated the illustrations (kudos to @MichaelArestad for providing them). Let me know if that looks good now @drw158, thanks.

**Comment by drw158** [comment]
If the pie if white now, it’s a 👍 from me

**Comment by tyxla** [comment]
Yeah, it's white (kudos to @MichaelArestad for that). Thanks @drw158!

**Pull request merged**
