### PR TITLE
Jetpack Cloud: update button styles

### PR DESCRIPTION
**Pull request by IanRamosC**
#### Changes proposed in this Pull Request

Note: This PR updates only a few colors in the `_jetpack-cloud.scss` to update the buttons and button-based components and to avoid changing the design of unrelated components (such as links, cards, etc) unexpectedly, but a thorough test is appreciated.

- Updates the colors in `_jetpack-cloud.scss`
- Updated the buttons styles in `client/jetpack-cloud/style.scss`

Context: dRt1pX85T68o5UNYK6AZro-fi-88%3A0 and p6TEKc-51M-p2

#### Testing instructions

- Check out this PR and run `yarn start-jetpack-cloud`.
- Go to http://jetpack.cloud.localhost:3000/
- Check the usage of the buttons and the screenshots below

#### Screenshots

These screenshots cover pretty much every possible button in Calypso.

Before | After
--|--
image|image

### CODE REVIEW

**Review by keoshi — CHANGES_REQUESTED** [review]
Thanks for kicking this off, @IanRamosC — really appreciate it.

Two tiny things that need some tweaking:
- All buttons should be using the Semibold variant, which is weight `500`.  [Reference in Figma](https://www.figma.com/file/dRt1pX85T68o5UNYK6AZro/?node-id=88%3A0).
- In at least one occasion, we were using the primary color as a status indicator (green), which is no longer true. This indicator appears at the top-right corner on `Settings → Remote server credentials`; see below:

image

Would be cool if we can incorporate these changes, at least the first one. Let me know if you want me to create a PR for the status indicator.

**Comment by IanRamosC** [comment]
Thanks for reviewing it, @keoshi! Comments have been addressed. Also, I've updated the description to include a before and after with all the buttons available per Andrei's request.
This is the updated status indicator:
image

**Comment by keoshi** [comment]
Thanks for doing that, Ian!

However...we're having second thoughts about black CTAs.

Several of us feel like we're losing the focus of the actions by turning everything monochrome all of a sudden. Even though we've been working on mocks with this new style, it was your PR that brought up these discussions once again, so I thank you for doing this anyhow!

Since you're worked on this with @Luchadores let's Andrei weigh in and see where we land.

**Comment by Luchadores** [comment]
Hey Ian, thanks for the nice listing of all the UI buttons. As Filipe said, we decided to switch the main CTA color. 
Main CTA will change to Jetpack Green 50 and have the hover of Jetpack Green 60. The rest remains unchanged. 

Here is i4 in Figma with the main CTA color: JVpmiQH74FKEIrPLjqv8p7-fi-1262%3A12746

Screenshot:
image

The rest looks fine to us, well done, and thank you for all your effort! 🙌

**Comment by Luchadores** [comment]
Looking great, Ian! Thank you 🙌

**Review by Luchadores — APPROVED** [review]
This is looking great. Thank you, Ian!

**Pull request merged**
