### PR TITLE
A/B Test: Recommend shortest domain name.

### PR DESCRIPTION
**Pull request by delputnam**
This is for an A/B test where we will recommend the shortest domain name instead of the highest ranking domain name.

More info available in: p8kIbR-ag-p2

To test, build locally and run several searches with each variation of the test. When the `shortest` variation is selected, the domain name with the shortest string before the TLD is the one that should have the recommended flag next to it.

### CODE REVIEW

**Comment by delputnam** [comment]
[Recommend Shortest Domain Test](https://trello.com/c/U28buboa/34-recommend-shortest-domain-test)

**Comment by alisterscott** [comment]
I ran through some scenarios and this works well in my testing. Does it only take into account the domain name length not the TLD total? See cookies below.

Some examples I did:

Search Term | Previous Recommendation | Length | New Recommendation | Length | Shorter ? |
------------ | --------------------------|---------|-----------------------|---------|-|
watermelon | giantwatermelon.blog | 15 + 4 = 19 | mywatermelon.blog | 12 + 4 = 16 | ✅ |
cookies | cookies.tech | 7 + 4 = 11 | sweets.online | 6 + 6 = 12 | ❓ |
juiced | juiced.website | 6 + 7 = 13 | juiced.club | 6 + 4 = 10 | ✅ |

Some general observations not specific to this PR/test:

1. Recommended results don't stand out enough IMO against NEW results which use the same colour/style
2. It would be best, IMO, to show recommended always at the top. On mobile for example the recommended result for cookies needs to be scrolled to:

cookies now

**Comment by delputnam** [comment]
Thanks for the testing and the thoughts, @alisterscott! Much appreciated!

For this specific test, we decided to change as little as possible in order to make sure the test is valid. So, we're not changing the order of the suggested domain names (yet). Subsequent tests may change other variables (such as color, wording, or the order of the suggestions).

Also, you are right about not including the TLD in the length count. We are only checking "domain name with the shortest string before the TLD." This is because there are often several TLDs available for the same domain name and we want to recommend the highest ranking TLD for the given domain name.

**Comment by klimeryk** [comment]
You mention this for the `shortest` variation:

> In this test variation, we will put the “Recommend” flag next to the highest ranking domain with the shortest length (not including the TLD). The “Best Alternative” flag will then be placed next to the next highest ranking available domain (“Exact Matches” first, then “Suggestions”.)

However, from my testing it looks like the `Best Alternative` is placed on the next shortest suggestion:
screen shot 2017-09-21 at 18 17 27
I'd expect the `Best Alternative` flag to be applied to the first exact match (`somesuperwebsite.blog`), instead of the next shortest one (`somesuper.site`). Or am I misunderstanding the test?

**Comment by delputnam** [comment]
The key to understanding how this test is meant to work is the (probably poorly phrased):

> shortest length (not including the TLD)

Note the phrase _not including the TLD_.

So, if there are multiple domains available that differ in only TLD, we want the highest ranking TLD to win because we wouldn't want something like `joespizza.limo` to win over something that makes more contextual sense like `joespizza.restaurant`.

There are definitely edge cases like the example of the `website` TLD vs the `site` TLD. In your example, I suspect that since the query contained the keyword `website`, the algorithm ranked that TLD higher than the TLD of `site` which can have a similar meaning.

For this test, I am trusting the suggestions algorithm to help us make good recommendations and give the highest rank to the TLD that makes the most sense. There is definitely room for improvement of the algorithm and I'm open to other suggestions to help make these recommendations better too. So, I'm not trying to shoot down the potential issue you bring up, but explain the thought process of how this was meant to work.

**Pull request merged**
