### PR TITLE
Themes: Remove Flux stores

### PR DESCRIPTION
**Pull request by ockham**
To test:

* Make sure the Themes showcase (`calypso.localhost:3000/design`) works as before.
* Run `make test` inside `shared/lib/themes`

Changes:

* `reducers/themes-last-query`: Remove Flux dispatcher `waitFor`
* `reducers/themes-list`: Use `isJetpack()` from selectors instead of
  `ThemeLastQueryStore`'s
* Kill `shared/lib/themes/stores`
* Remove obsolete helper functions from reducers, now that they are in `selectors/`
* Default-export reducers, don't export initialStates anymore
* Update README.md
* Rewrite tests in `shared/lib/themes` to directly test reducers instead of stores
  Note that in test/themes-list-store, the Jetpack test is removed since filtering
	is no longer done in the reducer but in the themes-list-fetcher data component
  (using the getFilteredThemes()) now.

### CODE REVIEW

**Comment by ockham** [comment]
Note from the latest commit:

> Remove ThemesListStore, update tests
Had to remove the Jetpack test since filtering is no longer done in
the reducer but in the themes-list-fetcher data component (using the
getFilteredThemes() selector) now.

**Comment by mcsf** [comment]
Code-wise, looks good!

**Comment by mcsf** [comment]
Feels good to slash code. :shipit:

**Comment by ockham** [comment]
Thanks!

**Pull request merged**
