### PR TITLE
Update blocked plugins that break on Atomic and violate ToS

### PR DESCRIPTION
**Pull request by Nic-Sevic**
Update blocked plugins to include additional plugins that break on Atomic, violate ToS, and do not need outreach.
Based on p9F6qB-78n-p2

#### Proposed Changes

adds the following plugins to the incompatibility list:
vamtam-offline-jetpack
plugin-detective
wp-hide-security-enhancer
redis-cache
wp-phpmyadmin-extension
antihacker
deactivate-xml-rpc-service
disable-xml-rpc
disable-xml-rpc-api
disable-xml-rpc-fully
disable-xml-rpc-unset-x-pingback
manage-xml-rpc
sg-security
simple-xml-rpc-disabler
stopbadbots
wee-remove-xmlrpc-methods
wp-hide-security-enhancer

#### Pre-merge Checklist

- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have you sent any new strings for translation (PCYsg-1vr-p2) ASAP?

Related to #

### CODE REVIEW

**Comment by JoshuaGoode** [comment]
@Nic-Sevic, when you get time, let's get this updated to match what is in wpcomsh now. 

Then, ping me and we can get things merged.

**Comment by JoshuaGoode** [comment]
Noting that this is the Calypso side of blocked plugin updates that have already been approved and merged into wpcomsh: 1055-gh-Automattic/wpcomsh

This won't take much to review, approve, and merge -- but might be a good time to check and see if we can consult with a Dotcom team like @Automattic/build for these and more technical updates in the future.  

Perhaps @danielbachhuber  or someone can work with @Automattic/reactor on reviewing, approving, and merging the team's PRs.

**Comment by danielbachhuber** [comment]
@JoshuaGoode Sure, I'd be happy to help. Let me know how I can best contribute!

**Comment by JoshuaGoode** [comment]
Cool! @danielbachhuber So, in this case, can you work with @Nic-Sevic on getting this approved and merged?

**Comment by danielbachhuber** [comment]
> So, in this case, can you work with @Nic-Sevic on getting this approved and merged?

@JoshuaGoode Yep!

@Nic-Sevic Overall, the pull request seems reasonable. How should I go about evaluating the changes? Is there any user-facing impact I can observe?

**Comment by Nic-Sevic** [comment]
Hey @danielbachhuber 👋 thanks for looking at this.
The only thing that should change with this is that for the plugins added to the list the ability to install from calypso is blocked and a notice is placed on the card, like so:
2022-09-13 at 09 59
It's also getting the unsuccessful check regarding e2e tests but I'm not sure exactly how to resolve those as I don't have teamcity access to see the details.

**Review by danielbachhuber — APPROVED** [review]
@Nic-Sevic Works as expected ✅ Thanks for the explanation!

In the future, if you'd like @Automattic/build to apply these changes for you, feel free to:
1. Create a new GitHub issue with the changes you'd like.
2. Add the `Build Maintenance` label.
3. Assign to the `Forge Build Group` project (as I've done with this PR).

**Review by JoshuaGoode — APPROVED** [review]

**Pull request merged**
