### PR TITLE
Transaction fee: Update copy on comparison grid

### PR DESCRIPTION
**Pull request by niranjan-uma-shankar**
Related to #

## Proposed Changes

* This updates the copy for the transaction fee on the price comparison grid. Conversation in pau2Xa-598#comment-14306.

#### BEFORE
Screenshot 2023-10-13 at 6 13 23 PM

#### AFTER

**Desktop**

Screenshot 2023-10-13 at 7 17 11 PM

**Mobile**

Screenshot 2023-10-13 at 7 17 11 PM

## Testing Instructions

* Navigate to `/start/plans` and verify that in the plans comparison grid that the copy for the transaction fee matches what's shown in the screenshots above. Verify in both desktop and mobile.
* Verify translations exist in non-EN
Screenshot 2023-10-30 at 11 12 54 AM

### CODE REVIEW

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/9329923

Some locales (Hebrew, Japanese) have been temporarily machine-translated due to translator availability. All other translations are usually ready within a few days. Untranslated and machine-translated strings will be sent for translation next Monday and are expected to be completed by the following Friday.

Thank you @niranjan-uma-shankar for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/9329923

Thank you @niranjan-uma-shankar for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/9329923).

**Review by claudiucelfilip — APPROVED** [review]
LGTM

**Pull request merged**
