### PR TITLE
people(viewers): migrate to `react-query`

### PR DESCRIPTION
**Pull request by flootr**
~~This PR is branched upon #50262 to make it easier to review. It should be rebased on `trunk` as #50262 gets in.~~

#### Changes proposed in this Pull Request

* Create `useViewers` and `useRemoveViewer` custom hooks based on `react-query`
* Use those hooks in `/people/viewers`

#### Testing instructions

Note: Viewers are only visible in the UI for pages which are private. You can access the viewers tab, however, by going to the `/people/viewers/:site` route even it it's not private.  Depending on what sites you have available it may make sense to look for a site with many viewers. 

1. Open a site with viewers on `/people/viewers/:site`
2. Make sure data shows up. Scroll down and look closely at the Network tab in your browser devtools. Is paginated data being fetched correctly?
3. Switch your active site. Are the page params reset correctly when fetching viewers for the site you switched to?
4. Now go back or try removing a viewer for the currently active site. Is the network request successful and the user removed from the list?

### CODE REVIEW

**Comment by flootr** [comment]
> Caution: This PR affects files in the Editing Toolkit Plugin on WordPress.com
> Please ensure your changes work on WordPress.com before merging.

This was related to an invalid rebase I did when I opened this PR. Should be resolved.

**Review by sarayourfriend — APPROVED** [review]
Tests great, LGTM. I can't comment on the react-query stuff but your test instructions work fine for me.

**Comment by flootr** [comment]
@sarayourfriend I added two commits: one for error handling in case fetching viewers fails ([see earlier behaviour](https://github.com/Automattic/wp-calypso/blob/trunk/client/my-sites/people/people-notices/index.jsx#L141)) and in the second one I moved all params to the `removeViewer` call rather than the hook initialization which aligns it with the [previously used action creator](https://github.com/Automattic/wp-calypso/blob/trunk/client/state/viewers/actions.js#L34). Hope those are fine ✌🏻

**Review by sarayourfriend — APPROVED** [review]
LGTM! Nice additions/refactors.

**Review by tyxla — APPROVED** [review]
This is working well for me 👍  And what a great cleanup!

**Pull request merged**
