### PR TITLE
Plans: A/B test displaying a feature list vs. description in `Plan`

### LINKED ISSUE #2752: Plans: A/B Test to show list of features vs. description text
Update the Plans page to show a list of features for each plan instead of the current description text.

**Hypothesis:** Showing a feature list clarifies what each plan includes, increasing confidence in purchasing and increasing conversion rate.

### Control

image

### PR DESCRIPTION
**Pull request by drewblaisdell**
Fixes #2752.

screen shot 2016-01-29 at 3 36 55 pm

**Testing**
*With a description*
- Visit http://calypso.localhost:3000/start in a new browsing session.
- Run `localStorage.setItem( 'ABTests', '{"plansFeatureList_20040201":"description"}' );` in your browser.
- Proceed through signup to the `plans` step.
- Assert that you see a sentence as the description for each plan.
- Assert that you see the same description on `/plans/:site` after signing up.

*With a list of features*
- Visit http://calypso.localhost:3000/start in a new browsing session.
- Run `localStorage.setItem( 'ABTests', '{"plansFeatureList_20040201":"list"}' );` in your browser.
- Proceed through signup to the `plans` step.
- Assert that you see a list of features (like in the screenshot above) for each plan.
- Assert that you see the same list of features on `/plans/:site` after signing up.

- [x] Product review
- [x] Code review

cc @danhauk

### CODE REVIEW

**Comment by breezyskies** [comment]
Looks good! A couple nitpicks:

1) On the `/plans` page for logged in users, the "never expires" and space below looks off. I'd just hide this entirely so it looks like the signup version:
screen shot 2016-01-29 at 4 20 57 pm

2) I'd bump the top / bottom padding on the features up to 5px.

**Comment by drewblaisdell** [comment]
@breezyskies Thanks for the feedback. I updated the commit with those changes.

**Comment by breezyskies** [comment]
Looks good. :+1:

**Comment by scruffian** [comment]
Code :+1:

**Comment by drewblaisdell** [comment]
cc @lucasartoni to make sure that it's cool to run this concurrently with the `periodLabelFree` test.

**Pull request merged**
