### PR TITLE
Reader: Reimplement keyboard shortcuts - take 2

### PR DESCRIPTION
**Pull request by tyxla**
#### Changes proposed in this Pull Request

This PR aims to reintroduce a simpler version of the keyboard shortcuts that were supported in Reader and were removed in #60501. See https://github.com/Automattic/wp-calypso/pull/60501#issuecomment-1028083347 and https://github.com/Automattic/wp-calypso/pull/60501#issuecomment-1028593376 for the motivation.

The PR is essentially reverting parts of #60501 that were related to the Reader, but also update the keyboard shortcut handling to happen directly in the components, rather than using the legacy removed keyboard shortcuts module.

**This is a take 2 of #60812, which was reverted because of a bug (#61063). As a fix, we're disabling the keyboard shortcuts when triggered inside any kind of input field.**

#### Testing instructions

* Keep an eye on the console for errors while testing this.
* Go to `/read`
* Test the following keyboard shortcuts and verify they work well:
  * `j` - move selection down
  * `k` - move selection up
  * `Enter/Return` - open the full post view for the selected post
  * `v` - open the selected post in a new tab
  * `l` (lowercase L) - toggle like/unlike the selected post
  * `.` - go to top - works only if you have new updates in the stream.
* Open a selected post in a full post view
* Test the following keyboard shortcuts and verify they work well:
  * `Esc` - close full post view
  * `l` (lowercase L) - toggle like/unlike the post
  * `j` - previous post
  * `k` - next post
* Start writing a comment in a post that has comments enabled.
* Verify that the shortcuts don't work while the comment field is focused.

### CODE REVIEW

**Review by sirbrillig — APPROVED** [review]
I don't know if I trust my own review this time 😅 but in my testing the shortcuts work great and when typing in a comment field, they do not appear to operate.

**Review by pento — COMMENTED** [review]
I've tested this PR with all of the input fields I could find, they all seem to work correctly, the keyboard shortcuts aren't triggered when the input has focus.

I did find one issue should be fixed, however: the keyboard shortcuts shouldn't trigger when the notifications panel is open. `j`/`k` are particularly noticeable, I'm not sure if there are others that are shared.

I also noticed a couple of minor clashes with standard browser keyboard navigation, but I don't think these are blockers, more something to note for follow-up PRs:

When tabbing through tab-able elements in the reader list view, those elements can only be triggered by pressing `space`, pressing `enter` opens the currently selected post. However, the equivalent elements can be triggered with `space` or `enter` in the single post view. I noticed this with the Comment and Like buttons, but there may be others.

The currently tabbed element has no relation to the current post in the reader list view. This has two noticeable effects:
- After using `j` to move down a few posts, the tabbed element is now several posts behind, you have to press `tab` a bunch to catch up.
- When you open a single post from the reader list view, then close that post again, the currently tabbed element is reset to the start of the page, but the current post stays as it was prior to it being opened.

As I mentioned, I don't think these tabbing issues are blockers, primarily because standard keyboard navigation is not really usable in the reader anyway, these should really be fixed as part of a broader effort to improve keyboard navigation.

**Comment by tyxla** [comment]
Thanks for the great review @pento - super helpful 🙌 

> I did find one issue should be fixed, however: the keyboard shortcuts shouldn't trigger when the notifications panel is open. j/k are particularly noticeable, I'm not sure if there are others that are shared.

Great catch. I've fixed this in https://github.com/Automattic/wp-calypso/pull/61112/commits/503dd56d2ac931983b46c13f2875550a733d6f7a

> I also noticed a couple of minor clashes with standard browser keyboard navigation, but I don't think these are blockers, more something to note for follow-up PRs:

Please correct me if I'm wrong, but I think these were there before. I'd be willing to open an issue and maybe we can address those in the near future.

That being said, this one is ready for another review!

**Comment by sirbrillig** [comment]
Still works well for me, but I'll bow to @pento's thoroughness. 🙇

**Review by pento — APPROVED** [review]
> > I also noticed a couple of minor clashes with standard browser keyboard navigation, but I don't think these are blockers, more something to note for follow-up PRs:
> 
> Please correct me if I'm wrong, but I think these were there before. I'd be willing to open an issue and maybe we can address those in the near future.

Yah, quite possibly. I was just noting it for future reference, it certainly doesn't need to be fixed in this PR. 🙂

I've been running it through it's paces some more, and haven't run into any other troubles. Let's get it shipped! 🎉

**Comment by tyxla** [comment]
Failing e2e tests are not related (they're failing on every branch), so shipping.

Thanks everyone 🙌

**Comment by tyxla** [comment]
@pento I've opened #61318 with your ideas to improve the keyboard navigation of the Reader and a11y in general. We definitely don't want those ideas to be lost in time 😉 

Thanks again!

**Pull request merged**
