### PR TITLE
AnchorFM: Customize Login Text

### PR DESCRIPTION
**Pull request by krymson24**
#### Changes proposed in this Pull Request

Customizes the login text for the AnchorFM onboarding flow

Note: I created a HOC because `Login` is a Class Component, so I couldn't use the `useIsAnchorFm` hook. When trying to use the `useIsAnchorFm` hook in my HOC, Calypso gave me an error (`window.AppBoot is not a function` ) in which I could not decipher the root cause. Perhaps it's because the URL is encoded? Ideally, I could remove all the duplicative code and just use the hook instead.

#### Testing instructions

1. Checkout this branch or use Calypso Live
2. Go to http://calypso.localhost:3000/new?anchor_podcast={anchor_podcast_id}
3. Click "Login"
4. The login subtitle should contain AnchorFM specific text. 

#### Screenshots
Screen Shot 2021-01-13 at 10 46 55 PM

Fixes 358-gh-Automattic/dotcom-manage

### CODE REVIEW

**Review by blackjackkent — APPROVED** [review]
This looks good to me! I'm not sure what's up with the `appBoot` error you mentioned when trying to use the hook, but I did a quick off-the-cuff search and it looks like the same error has been mentioned in the context of previous PRs in this repo; possibly one of them might have a similar enough context to explain what was going on for you. (Not sure it's super critical for getting this feature out, though.)

**Comment by kwight** [comment]
Hm, this feels like a heavy-handed approach to me – instead, can we add an `isAnchorFmSignup` value to `Login`'s existing `mapStateToProps` function, like `wccomFrom` [here](https://github.com/Automattic/wp-calypso/blob/trunk/client/blocks/login/index.jsx#L528)? It would avoid adding the new complexity of the HOC (I'm thinking of the next dev that needs to customize the same text for some other project).

**Comment by krymson24** [comment]
@kwight good point -- and I don't like the additional complexity I've introduced.

Currently `wccomFrom` is `undefined` per below (because the URL does not contain that param)
Screen Shot 2021-01-18 at 8 36 48 PM

We could certainly add an `anchor_podcast` parameter to our login link, and use the approach you're suggesting render dynamic text. However, this introduces this `anchor_podcast` value in two places -- the additional param and in the `redirect_to`
              
Screen Shot 2021-01-18 at 8 27 19 PM

Another option is to `getCurrentQueryArguments` for the `redirect_to`, and then parse the URL for the `anchor_podcast`. However, doing so introduces much of the similar logic that I've introduced in the HOC.

What do you prefer?

**Comment by kwight** [comment]
@krymson24 Oh I see, right 🙃 

> Another option is to getCurrentQueryArguments for the redirect_to, and then parse the URL for the anchor_podcast.

This sounds best to me – true, you'll be needing to add a bunch of URL surgery for the `mapStateToProps`, but it still avoids the HOC and wrapping.

**Comment by mreishus** [comment]
I think (educated guess) the hook is failing because it also looks in `react-router's` "location state", by using `useLocation()`. Gutenboarding renders everything inside a `<BrowserRouter>` ([here](https://github.com/Automattic/wp-calypso/blob/4f797ceb21b820d2cbb341b89705a811e09857e5/client/landing/gutenboarding/index.tsx#L84)), which provides this functionality, but I wouldn't be surprised if `/log-in` is completely outside of that, meaning that `react-router` isn't available, and any calls or references to `useLocation()` cause strange errors.

**Comment by krymson24** [comment]
> but I wouldn't be surprised if `/log-in` is completely outside of that, meaning that `react-router` isn't available, and any calls or references to `useLocation()` cause strange errors.

This was my intuition as well.

**Comment by krymson24** [comment]
> @krymson24 Oh I see, right 🙃
> 
> > Another option is to getCurrentQueryArguments for the redirect_to, and then parse the URL for the anchor_podcast.
> 
> This sounds best to me – true, you'll be needing to add a bunch of URL surgery for the `mapStateToProps`, but it still avoids the HOC and wrapping.

Done!

**Comment by sixhours** [comment]
👋 Was just testing this and I'm not able to get from `/new?anchor_podcast=something` to the Anchor.fm signup flow to see the changes. What am I missing?

**Comment by kwight** [comment]
> What am I missing?

@sixhours Good question, I would expect https://hash-a89b57d7cb388576256eae731ea3bf7de699d00e.calypso.live/new?anchor_podcast=22b6608 to show the "My podcast is called..." text (and be pre-populated). Hm, and https://wordpress.com/new?anchor_podcast=22b6608&flags=anchor-fm-dev shows the login modal when I'm already logged in. I'm not sure what's happening here.

**Comment by mreishus** [comment]
Locally (on commit e9dfd7f0b4 from 2021-01-22) , that url is working for me while already logged in.  I would assume there's not a regression, but rather our feature flag override isn't working properly or some other issue only happening on calypso live.


Edit: I also tested on the latest commit on this branch, 4f797ceb21b8 from 2021-01-13 and it is working for me locally, too.

**Comment by sixhours** [comment]
> I would assume there's not a regression, but rather our feature flag override isn't working properly or some other issue only happening on calypso live.

Ahah, just booted it up locally and it works for me there. You're probably right, something wonky with calypso.live!

Screen Shot 2021-01-22 at 2 54 43 PM

**Comment by blackjackkent** [comment]
> Ahah, just booted it up locally and it works for me there. You're probably right, something wonky with calypso.live!

I could be wrong but it looks like calypso.live uses the `wpcalypso.json` config rather than the `development.json` config, and the `anchor-fm-dev` flag is disabled in that environment currently.

**Review by kwight — APPROVED** [review]
Looks good, we can tweak later if need be 👍

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/5472792

Thank you @krymson24 for including a screenshot in the description! This is really helpful for our translators.

**Comment by mreishus** [comment]
I'm seeing this crash when visiting a url like:

```
http://calypso.localhost:3000/post/bravenotperfectwithreshmasaujaniXXXXXX.word press.com?anchor_podcast=22b6608
(remove space between "word" and "press")
```

or: 
```
http://calypso.localhost:3000/post/bravenotperfectwithreshmasaujaniXXXXXX.word press.com?anchor_podcast=22b6608&anchor_episode=e324a06c-3148-43a4-85d8-34c0d8222138&spotify_show_url=https://open.spotify.com/show/6HTZdaDHjqXKDE4acYffoD?si=EVfDYETjQCu7pasVG5D73Q
(remove space between "word" and "press")
```

Created issue 442-gh-Automattic/dotcom-manage

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/5472792).

**Pull request merged**
