### PR TITLE
Activity Log: Remove Guided Tour & Add Subheading

### LINKED ISSUE #40684: Activity: Confusing (guided tour) tooltip
#### Steps to reproduce

1. Starting at URL: https://wordpress.com/activity-log/[site]
2. Click on Activity under Tools
3. There's a dark tooltip that shows up tell you what this page is about

Screen Shot 2020-04-01 at 4 06 14 PM

#### What I expected

For anything descriptive about this page to go on the banner. 

In this case:

1. There are two ways we are describing what this page is all about - first is on the banner and second, on the dark tooltip.

2. It's quite obtrusive. I click on Activity and this tooltip shows up all of a sudden.

In general, the purpose of a tooltip like that is to draw a user's attention to something on the page. In this case, I already clicked Activity, but it's trying to draw my attention like I never clicked on it.

I think both should be omitted; there should be a regular heading/subheading on this page similar to My Home:

Screen Shot 2020-04-01 at 4 13 33 PM

#### Browser / OS version

Mac OS Mojave 10.14.6
Chrome Version 80.0.3987.149 (Official Build) (64-bit)

cc @Automattic/jetpack @Automattic/jetpack-design

### PR DESCRIPTION
**Pull request by Aurorum**
#### Changes proposed in this Pull Request

- Removes the Activity Log guided tour
- Adds a `subHeaderText` to the Activity Log

#### Testing instructions

In order to check that the Guided Tours have gone, you can visit these links:
Jetpack site - `/activity-log/site?tour=activityLogJetpackIntroTour`
WPcom site - `/activity-log/site?tour=activityLogWpcomIntroTour
`
This would usually trigger a Guided Tour, but verify it doesn't anymore. The sub header text should also be present. It uses the same wording as the tour for i18n benefits, but let me know if it should be changed! :) 

Screenshot 2020-04-02 at 08 55 13

cc @jancavan, @roccotripaldi, @sgomes

Fixes #40684

### CODE REVIEW

**Comment by gwwar** [comment]
Adding copy review label for the new subheader 👍

**Review by gwwar — APPROVED** [review]
This tests well for me @Aurorum, with an excellent line count ratio ✨ . I'll leave this open for another day or so unless folks had additional feedback.

**Comment by kristastevens** [comment]
> Adding copy review label for the new subheader 👍

Looks good, @gwwar! Thanks for the ping.

**Review by jancavan — APPROVED** [review]

**Comment by gwwar** [comment]
Thanks @Aurorum ! 💖

**Pull request merged**
