### PR TITLE
Jetpack Settings: Introduce dev mode notice for settings

### PR DESCRIPTION
**Pull request by tyxla**
Some modules are unavailable in Jetpack when the site is in development mode, and this is by design. We're supposed to disable the cards that manage those modules if the site is in dev mode. This PR introduces a notice for development mode in Calypso settings, similar to the one from https://github.com/Automattic/jetpack/pull/6180.

This notice will be displayed if the site is a Jetpack site and in development mode by either constant, filter or enforced by the URL (localhost).

This PR will also go together with additional PRs that will handle disabling each of the modules if the site is in development mode:

* After the Deadline: #11779 
* Post by Email: #11781
* Photon: #11783
* Subscriptions: #11784

To test:
* Checkout this branch
* Enable dev mode by either using:
  * The `jetpack_development_mode` filter
  * The `JETPACK_DEV_DEBUG` constant
* Verify the notice is shown above the section navigation, as shown on the screenshot.
* Disable dev mode and refresh Calypso.
* Verify the notice no longer shows.
* Verify WordPress.com sites are not affected at all.

### CODE REVIEW

**Comment by tyxla** [comment]
Furthermore, we might want to be specific about why a module is disabled in  the module card itself? Currently in that case we display a "Unavailable in Dev Mode"  message in the Jetpack Settings in wp-admin, right where the module toggle should be. Thoughts on this one, @rickybanister @MichaelArestad?

**Comment by oskosk** [comment]
Works as expected. LGTM. Labeling as ready to merge.

**Comment by tyxla** [comment]
Removing the `Ready to Merge` label, as we're still waiting for an initial feedback from the design team. I really doubt it will not require any changes before merging 😃

**Comment by MichaelArestad** [comment]
Can we simplify it to be the same as the one in Jetpack? (no status and maybe less specific copy if the link explains it)

image

**Comment by tyxla** [comment]
@MichaelArestad the one you've shown is a different one - it displays when you're developing on Jetpack, but not necessarily with development mode on. The one we're replicating in Calypso is this one:



So, still, it would be great if you can provide a detailed feedback about:
* The copy/content of the proposed notice.
* The look of the notice (used component, colors, etc).

Thanks in advance.

**Comment by MichaelArestad** [comment]
Looks like no prop isn't right. Maybe it's `is-basic`. It should be the gray one.

Copy:

"Some features are disabled because your site is in Development mode. <action>Learn More</action>"

Where action: is the button that attaches to notices. It should take the user to a support doc on the debug constant.

**Comment by tyxla** [comment]
@MichaelArestad I've updated the dev mode notice to what you suggested, please feel free to review again. Here is how the notice looks now:



@oskosk can you please review it again? I've updated the code quite a bit (it's much simpler now).

**Comment by MichaelArestad** [comment]
@tyxla thanks! LGTM!

**Comment by oskosk** [comment]
🚢

**Comment by rickybanister** [comment]
A small nitpick—there's no reason why 'Development' would be capitalized, but not 'mode'. Can we standardize that? Since 'Development Mode' sounds like a proper noun—a thing we invented, it could be all capitalized, or we could informalize it and make it all lower case. Either way is fine.

**Comment by MichaelArestad** [comment]
Let's lowercase it.

**Comment by tyxla** [comment]
Addressing the lowercasing suggestion in #12007.

**Pull request merged**
