### PR TITLE
P2+: enable in production

### PR DESCRIPTION
**Pull request by lamosty**
In this PR, we enable the P2+ paid plan in production!

## Testing

Code review. You can also test the P2+ itself by creating a new P2 site from https://wordpress.com/p2/ and buying P2+.

### CODE REVIEW

**Comment by evilluendas** [comment]
I mentioned this on Slack but I'm going to post it here too so we don't forget 😬

Let's remove the "Unlimited free viewers" item in the P2+ list of features, ok? We're not totally sure about it since it can be very confusing when compared with the "Unlimited users" item on the free plan, so let's remove it until we find the correct wording.

image

**Comment by lamosty** [comment]
> Let's remove the "Unlimited free viewers" item in the P2+ list of features, ok?

Ok 😅

**Review by annemirasol — APPROVED** [review]
LGTM! Was able to upgrade my P2 to P2+ outside of staging, too.

**Review by lezama — APPROVED** [review]
let's go live!

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/5393632

Hi @lamosty, could you please edit the description of this PR and add a screenshot for our translators? Ideally it'd include this string: `Priority customer support`

Thank you in advance!

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/5393632).

**Pull request merged**
