### PR TITLE
Upgrade wordpress monorepo

### PR DESCRIPTION
**Pull request by noahtallen**
#### Proposed Changes
Upgrade WordPress monorepo to the latest version:

- Add the `upgrade-interactive` yarn plugin. (This accounts for 541 lines of the diff -- so we're really only adding around 300 lines in this PR, not 800.)
- Ran that to upgrade every WordPress and @types/wordpress package.
- Fixed peer dependency resolutions in yarnrc.yml.
- Deduped dependencies.
- TBD to fix errors that arise

#### Testing Instructions
1. Smoke test calypso.live, especially any WordPress components. Test components in devdocs as well.
2. Verify local yarn install and yarn build continue to work as expected.
3. Smoke test ETK.

### CODE REVIEW

**Review by worldomonation — APPROVED** [review]
Well, you've met your LoC quota for the week!

In all seriousness, approving to unblock once all tasks pass reliably _and_ staging has no issues.

**Comment by noahtallen** [comment]
Thanks! Unfortunately, looks like we'll need to do some refactoring of our data stores to get typescript to compile.

Edit: more on the wp/data issue here if anyone has advice: p1666742659923809-slack-C45SNKV4Z

**Review by yuliyan — COMMENTED** [review]
Tested `@wordpress/i18n` and `@wordpress/react-i18n` and didn't see any problems.

**Comment by noahtallen** [comment]
#73890 superseded this

**Pull request closed without merging**
