### PR TITLE
Editor: add Insert Content to the HTML toolbar

### PR DESCRIPTION
**Pull request by Copons**
Add the Insert Content dropdown and modals to the HTML toolbar.

The split button and the dropdown look the same as their Visual toolbar equivalent but don't share any code. Any addition or modification done to one will need an update to the other.

The media and Contact Form modals, on the other hand, are exactly the same used for the Visual toolbar.
As long as their onInsert methods return a string (HTML or shortcode or whatever really) they should work ok.

One quirk about the Contact Form is that it actually returns an object that must be [serialized](https://github.com/Automattic/wp-calypso/blob/master/client/components/tinymce/plugins/contact-form/plugin.jsx#L60) before entering the text area. It's needed for both visual and HTML toolbars, though, so again, should anything change there, the HTML toolbar needs to be updated tool.

One design quirk is that the caret used here is not the same used in the Visual toolbar.
Here is a proper Gridicon, while the TinyMCE button uses a CSS content.
It's possible to notice the difference when switching between the two modes, since one is a little bit bolder than the other.

## Task List

- [x] Media Modal
- [x] Contact Form Modal
- [x] Same UI as Visual mode

### CODE REVIEW

**Comment by drw158** [comment]
Design looks good

**Comment by folletto** [comment]
Visual reference:

screen shot 2017-02-08 at 16 22 05

Design: 👍

**Comment by roundhill** [comment]
Probably for a different PR, but I noticed that undo doesn't work as expected if you insert a tag:

1. Type something and highlight it
2. Click the bold button
3. Do a cmd+z to undo

I expected the tags to go away, but it instead will undo the action before the tags were inserted.

**Comment by roundhill** [comment]
@rodrigoi would you mind reviewing the contact form bits in this PR? Seems to work fine for me.

**Comment by Copons** [comment]
@roundhill the undo/redo doesn't work in WP Admin either. I haven't looked into it, to be fair, but maybe I could see if there's an easy implementation.

**Pull request merged**
