### PR TITLE
Renaming Pages and move it to the top.

### PR DESCRIPTION
**Pull request by shaunandrews**
Renaming Pages to Site Pages and moving it above Blog Posts in the publish menu.

Before:
screen shot 2017-08-08 at 3 41 22 pm

After:
screen shot 2017-08-08 at 3 41 16 pm

### CODE REVIEW

**Comment by folletto** [comment]
* Position: I think it works. Probably better for a large segment of our users.
* Label: not convinced as I prefer single words, but I'm not against it either.

That said, while I can infer the rationale, I think it's important to explain it clearly: why this change?

**Comment by mcsf** [comment]
Code-wise, this gets my 👍 . I'll let y'all discuss the design implications 😄 . Personally, I'm good to ship this and see where it leads us.

**Comment by lsinger** [comment]
Without knowing @shaunandrews's exact rationale, I'd assume the following to be true:

- "posts" and "pages" are not descriptive enough / too generic for most people. "blog posts" and "site pages" add information / context that most people don't have. We can always claim that "people can deduce that context here, they're here to make a website!" but I think there's a valid case to be made to make it easier / reduce cognitive load to increase the "conversion rate" / ration of people who "get it" ever so slightly. 
- The order represents how "normal people" probably understand things. You have a website. It has pages. Oh, and you can have this special thing called a "blog" that has "blog posts". The blog as a feature of the site. 

I agree with @mcsf in that I'd be interested to see where it leads us. Are clicks on these menu items sufficiently instrumented, I wonder? Maybe it would make sense to make this an A/B test.

**Comment by folletto** [comment]
Rationale there would be my guess too, so I agree. :) 

> Are clicks on these menu items sufficiently instrumented, I wonder?

I'd say no: one group would see a "new item" in the list, another wouldn't. At the same time new users would just try out everything I guess, so not meaningful either. Probably meaningful is some ratio of "time spent on page" after the click, but feels flimsy too...

**Comment by folletto** [comment]
Aside: I wonder if could make sense to change the icon to a hierarchy icon...

**Comment by shaunandrews** [comment]
What @lsinger said.

> I wonder if could make sense to change the icon to a hierarchy icon...

@folletto What hierarchy icon?

**Comment by folletto** [comment]
> What hierarchy icon?

We don't have one for this, I'm just wondering if it would be more effective to show "Pages" as the site hierarchy, so we could make a new one ad-hoc :)

**Comment by lancewillett** [comment]
Project note: we should also update the WP.com "front-end" navigation which is used for both WP.com and Jetpack sites to match the new terminology. Hat tip: @folletto 

Here's a quick visual record from lance.blog

Front-end, logged-in
screen shot 2017-08-15 at 10 30 06

Calypso
screen shot 2017-08-15 at 10 30 13

**Comment by carinapilar** [comment]
I didn't find a P2 post about this, so I'm not sure if this is the right place to leave user's feedback, if not, please, let me know. :)

I got a user on live chat today (578925-hc) that ended up creating pages, instead of posts, because of this change. So the pages were automatically added on the site's menu and he didn't know how to fix all that. He said the following:

> yes I know, but someone inverted the buttons to create pages and articles, that are on the left side when I create them

> thank you, please when you do changes on the blog, please tell us

**Comment by lancewillett** [comment]
A matching change for the WP.com front-end navigation: D6871-code.

**Pull request merged**
