### PR TITLE
Fix signup flows with a login step

### PR DESCRIPTION
**Pull request by sgomes**
Signup state requires a special case, where state gets loaded from the logged-out persisted state when the logged-in one is empty. This is done to enable signup flows where the user starts out logged out, but logs in as part of the process.

When signup state was modularised, this special handling remained in the portion of code that handles legacy state, rather than being moved to the portion that handles modularised state. This caused the previously mentioned flows to break.

This PR fixes that.

#### Changes proposed in this Pull Request

* Move signup special case from legacy state handling to modularised state handling

#### Testing instructions

IMPORTANT NOTE: Do not test this in development. Development has a 25% chance of clearing persisted state as a way of detecting some classes of bugs, a feature which interferes with the normal behaviour of this flow. Please use the live branch instead.

* Start as a logged-out user
* Go to `/start/p2/p2-site`
* Fill in the form
* Click "Continue"
* Click "Already have a WordPress.com account?"
* Log in
* Verify that you are redirected to a congratulation page, rather than the initial form.

### CODE REVIEW

**Comment by sgomes** [comment]
Forgot to update the unit tests. Fixing.

**Comment by lamosty** [comment]
Thanks for fixing this!

I'm just testing it (in dev mode but running calypso with `ENABLE_FEATURES=no-force-sympathy yarn start`) and after logging in, I'm shown the "hooray!" screen as expected. However, the flow gets stuck on that screen while to finish the flow successfully, it should redirect me to the newly created P2 site. Can you repro or am I doing something wrong?

**Comment by sgomes** [comment]
> I'm just testing it (in dev mode but running calypso with `ENABLE_FEATURES=no-force-sympathy yarn start`) and after logging in, I'm shown the "hooray!" screen as expected. However, the flow gets stuck on that screen while to finish the flow successfully, it should redirect me to the newly created P2 site. Can you repro or am I doing something wrong?

Yes, I had noticed that earlier. I assumed that the step took a while because of background work and never waited around too long, but it sounds like it's never moving forward. I'll take a look to see if I can figure out whether it's related to this fix.

**Comment by sgomes** [comment]
I've taken a long look at this, but I wasn't able to find the issue causing the redirect not to happen at the end of the flow. `signup/main.jsx` is a complex component that I'm still trying to grok.

I'll take a closer look tomorrow, but in the meantime perhaps someone more familiar with the signup flow might be able to help?

**Comment by sgomes** [comment]
It might be interesting to check if this issue also applies to non-P2 signups. I suspect that's the case.

**Comment by sgomes** [comment]
The issue appears to be unrelated to the fix in this PR. I'll keep looking, but I suggest we move ahead with this fix, since it will at least complete the blog creation process, even if the user doesn't get redirected.

**Comment by sgomes** [comment]
The problem with not redirecting at the end of the flow appears to be a logic bug somewhere in `lib/signup/flow-controller.ts`. The signup state appears to get reset with a `SIGNUP_COMPLETE_RESET` action before the signup process has a chance to complete. I don't feel confident enough in the signup internals to attempt to track down and fix this bug.

It's probably best to deal with this PR as-is, and then have someone with more knowledge of the signup process look at the remaining issue.

**Comment by lamosty** [comment]
Agreed, it feels like there's some missing code to make it all work (for example, we need to remove `user` step from `progress` tree once you log in which happens for new user creation but not here). 

Feel free to merge and I'll take it from here. :)

**Comment by sgomes** [comment]
Thank you for the review, @lamosty! 👍

**Pull request merged**
