### PR TITLE
Fix bug where we were trying to access property of null plan object

### PR DESCRIPTION
**Pull request by dmsnell**
See #7291 for bug introduction

cc: @aduth

Test live: https://calypso.live/?branch=fix/seo-plans-null

### CODE REVIEW

**Comment by nylen** [comment]
LGTM

**Comment by aduth** [comment]
LGTM as least as far as avoiding calling property on `null` selected site 👍

**Comment by nylen** [comment]
yes, for later on I don't think WebPreview should be aware of whether a site has a business plan, this check and/or the SEO-specific logic should live in a separate component.

**Comment by dmsnell** [comment]
@nylen for what it's worth, the web preview somehow must know because it should only show the SEO previews for business/enterprise sites

definitely open to suggestions, though I don't feel it worth it to clone the entire web preview just to separate this logic

**Comment by nylen** [comment]
Maybe have WebPreview accept a prop that can optionally be a child component shown at the right place?

**Comment by dmsnell** [comment]
@nylen I will explore this idea. My gut impression is that it will require so much hackiness that it won't be better than what we currently have, but I will try.

**Pull request merged**
