### PR TITLE
Reader: Allow the user to specify a search algorithm

### PR DESCRIPTION
**Pull request by blowery**
Just add a algorithm=foo to the querystring when you first load calypso and all "search" requests will use that algorithm.

Works for post search, feed search, related posts, recommended sites.

### CODE REVIEW

**Comment by gibrown** [comment]
This looks like it is working for me.

**Comment by apeatling** [comment]
@blowery & @bluefuton can we merge this?

**Comment by blowery** [comment]
looking to see how much rebase surgery we have to do

**Comment by apeatling** [comment]
@blowery I'm going to close this, but please feel free to reopen once you have rebased or made any further updates.

**Pull request closed without merging**
