### PR TITLE
force eslint dependency escope to 3.3.0 and add shrinkwrap file

### PR DESCRIPTION
**Pull request by gwwar**
Works around build breakage introduced in: https://github.com/babel/babel-eslint/issues/243

When adding new packages, you'll need to shrinkwrap dependencies. You may find using a command line tool to do this helpful:

https://github.com/goodeggs/clingwrap

### CODE REVIEW

**Comment by blowery** [comment]
WFM. We should add a bit to the readme on how to re-shrinkwrap things as needed, but that can be another PR.

**Comment by gwwar** [comment]
@blowery Yup I'll be writing a P2 and updating the readme on updating packages today.

**Comment by artpi** [comment]
:sheep: :ship:

**Comment by artpi** [comment]
@blowery : I was just writing that comment :) totally agree!

@gwwar : You're awesome!

**Comment by hzoo** [comment]
Published a fix.

`npm view babel-eslint dist-tags`

`{ latest: '4.1.7', next: '5.0.0-beta9' }`

**Comment by gwwar** [comment]
Thanks for the update @hzoo!

**Pull request merged**
