### PR TITLE
Happychat: clean up CSS for the floating and docked styles

### PR DESCRIPTION
**Pull request by jsnajdr**
This PR cleans up the CSS styles for Happychat, which has two display options -- floating for narrow (<1040px) views:

Screenshot 2021-09-03 at 12 37 11

and docked (sidebar) for wide views:

Screenshot 2021-09-03 at 12 37 36

First, I'm removing `.layout.has-chat` prefix from the `.happychat__*` rules. They should work even when the UI is not rendered inside a `.layout.has-chat` element, like when Happychat is (in the future) used as an embedded widget.

The only places where `.layout.has-chat` is needed are ones where we modify the style of the layout itself, like when making space for the docked chat. For that purpose, I'm renaming the class name to `.layout.has-docked-chat` because it doesn't apply to floating chat windows.

Second, I'm reorganizing the styles to cleanly implement the two display options:
- floating is the default option, styled with rules with no media query
- docked is wrapped inside a media query for a wider-than-1040px viewport and inside a `.layout.has-docked-chat` selector. 

Fourth, if there are section-specific style patches, I'm consolidating them all to `client/layout/style.scss` where they are all under one common `.layout.has-docked-chat` selector.

Finally, I'm removing Reader style customizations (`.reader-post-card__post` et al) implemented in #8865 because they no longer work today. Instead, the UI breaks when you toggle Happychat back and forth:

Screen Capture on 2021-09-02 at 13-52-40

I'm also removing a customization for Jetpack Connect Plans (`/jetpack/connect/store`) because the docked chat never appears there, because the page doesn't have a sidebar.

**How to test:**
Test chat on various Calypso pages and screen sizes and confirm that they look good everywhere.

### CODE REVIEW

**Comment by jasmussen** [comment]
It's been a while since I worked on this, so I'm not the best to review at a code level, so would defer to other reviewers. 

But more high level, these changes look good to me, thanks for tackling it. 

The challenge as you know with media queries is that they look at the full width of the viewport. For interfaces that rely on this, they might not be able to accommodate the width of the docked chat, assuming they have the full width available when they might not. The fact that you appear to have succeeded regardless in making the docked version work across the board is impressive! Nevertheless, it would be good to test this query on all sections of the interface to make sure nothing breaks as a result.

**Comment by jsnajdr** [comment]
> The challenge as you know with media queries is that they look at the full width of the viewport. For interfaces that rely on this, they might not be able to accommodate the width of the docked chat, assuming they have the full width available when they might not.

To clarify what kind of issue exactly can be caused by the docked chat: the chat becomes docked when the viewport is at least 1040px wide, like on this screenshot from Reader:

Screenshot 2021-09-03 at 14 34 42

But because the chat is 270px wide, the real remaining width of the UI is only 770px. Breakpoints for `<770px` should be triggered, but they are not.

For example, the "145 followers" label should be hidden on this screenshot, because it has a `display: none` style triggered by a `<960px` breakpoint. All such breakpoints that are between 770px and 1040px are evaluated incorrectly.

**Comment by jasmussen** [comment]
> But because the chat is 270px wide, the real remaining width of the UI is only 770px. Breakpoints for <770px should be triggered, but they are not.

That's a good example, yes. 

The sad part about that is that the only way to be sure a docked interface like that would ever work perfectly in all cases, would require a refactor to use element queries, or intrinsic responsiveness such as that provided by CSS grid and otherwise. In absence of that, the best solution might be to embrace the chat-bubble version across the board, and put the majority of effort into ensuring interacting with it is as good as it can be.

**Comment by jsnajdr** [comment]
> In absence of that, the best solution might be to embrace the chat-bubble version across the board, and put the majority of effort into ensuring interacting with it is as good as it can be.

I pushed a commit (2952ff6) where I'm disabling the docked chat. The chat UI is now always floating, looking like this:

Screenshot 2021-09-07 at 9 33 01

Compared to a docked chat, the floating version has two downsides:
1. The chat window always covers a part of the UI underneath it. It can be uncovered only by minimizing the chat window. The docked version doesn't obstruct anything.
2. The height of the chat window is small -- the "conversation" element has `max-height: 220px` -- and can't be resized. On the other hand, the docked version always expands to the full height of the viewport.

These issues could be solved by making the chat window resizable and movable.

Hi @mattwondra :wave: What do you think about making the Happychat window to always float and disabling the docked version? Is it an improvement, or a regression?

**Comment by jasmussen** [comment]
Just to clarify, I'm not suggesting that the bottom right collapsible chat window is a better interface than the docked sidebar. Only that investing in improving that chat window might be a better long term effort than handling the potential complexity of making the docked sidebar work with Calypso-specific breakpoints. A better chat window would also benefit the portable version of Happychat, since it could run in arbitrary media query based environments.

**Comment by jsnajdr** [comment]
I'd also prefer the docked version if we could guarantee that the main UI accommodates it responsibly and is aware that its viewport width is smaller than before. But when embedding the Happychat widget in wp-admin, I'm not sure we can guarantee that. The floating version is a tradeoff that prefers consistency across all WordPress.com screens.

**Comment by mattwondra** [comment]
@jsnajdr Are you aware that there's a pod working on this problem already? See p9Jlb4-2Vw-p2

I'd make sure whatever you're changing here aligns with the goal of that pod. Beyond that I'd ask the experts — Happiness Engineers — what they think of this change. They are best equipped to understand how this will impact the customer support experience. Here's my best guesses though:

> The chat window always covers a part of the UI underneath it.

This is already a major problem for the areas in Calypso where the chat UI is floating. Customers frequently miss page elements HEs tell them to use, because they're hidden behind the chat itself. Doubling down on this would make the problem worse, and in new areas of the Calypso interface. So there's a big tradeoff to be considered here.

> The height of the chat window is small

This is also one of the most frequent frustrations HEs report about the customer experience. The floating window is already so tiny that customers frequently need to scroll back and forth to follow longer instructions or review steps HEs talked about. This leads to longer chat durations and occasionally customers getting lost in where they are and ghosting. If you move this direction I'd recommend at least exploring making the floating panel taller. (Yes, this goes against the previous point by making the floating chat cover even MORE of the Calypso UI — that's tradeoffs for ya!)

**Comment by jsnajdr** [comment]
Thanks @mattwondra for the short introduction to the docked/floating tradeoffs. And I wasn't aware of the Help Center project.

For this PR, I'm giving up any ambition to change the UI -- it's just a cleanup of the styles:
- removing redundant ones
- making the basic floating layout work even without a parent `.layout.has-chat` element
- moving the docked/floating decision to JS code: instead of having CSS complex selectors with `:not( .is-section-reader )` etc., there is a code in `client/layout` that adds or removes a `.layout.has-docked-chat` CSS class on the root layout element

To test, just verify that the chat is displayed as previously:
- always floating in Reader and Theme sections, and in all sections that don't have a sidebar (Signup, Editor, Jetpack Connect, ...)
- docked in all other view if the viewport is wider than 1040px

**Review by flootr — APPROVED** [review]
I gotta admit it's been a while since I tested Happychat. To me it seems like HC looks as expected 👍🏻

**Pull request merged**
