### PR TITLE
Reader CombinedCards and Recs: increase font-weight of byline

### PR DESCRIPTION
**Pull request by samouri**
Addresses https://github.com/Automattic/wp-calypso/issues/17992

### CODE REVIEW

**Comment by fraying** [comment]
LGTM! 🚢

**Comment by samouri** [comment]
sorry for the slow turnaround, forgot about this guy.
I've added the font-weight increase to recs.

**Comment by samouri** [comment]
New combined card:
screen shot 2017-09-20 at 6 01 05 pm

new recs:
screen shot 2017-09-20 at 6 00 59 pm

**Comment by fraying** [comment]
👍 Thanks! LGTM

**Pull request merged**
