### PR TITLE
Add new WordPress logo

### PR DESCRIPTION
**Pull request by fditrapani**
We've updated the WordPress.com logo on our marketing site. This PR adds the new WordPress.com logo to the signup, themes, and login screens. The change will only be visible on desktop screens. The WordPress icon will remain as is for mobile screens.

## Before
image

## After: Signup
image

## After: Login
image

## After: Themes
image

## Mobile
image

## Testing
* Visit `/start` and check desktop and mobile views to ensure the logo is showing correctly for each version
* Then Visit `/log-in` and check desktop and mobile views to ensure the logo is showing correctly for each version

@taggon can you please take a look?

cc @MicBosi

### CODE REVIEW

**Comment by ballio2000** [comment]
Hello, this looks good to me! One minor suggestion for the /themes page is that to nudge the "THEMES" title down 1 px so that the baseline lines up with the WordPress.com wordmark.

**Comment by fditrapani** [comment]
Thanks for the fresh eyes @ballio2000. That alignment has been driving me wild. The logo sits on a half pixel and so whether I go one pixel up or down it looks slightly off. This morning, the extra pixel you suggested looks good. I've updated the screenshot above.

**Comment by folletto** [comment]
Heya! Design wise looks good to me. 👍  

Code wise, it follows what we were doing, so good there too...

But, given the SVG seem to me to be meant to be reusable, maybe it's worth to split it in a separate component (or just separate SVG, but that would add delays in load that we don't want)?

Maybe having a very simple component that just returns the logo would be useful and more reusable?

> That alignment has been driving me wild. The logo sits on a half pixel and so whether I go one pixel up or down it looks slightly off.

Can't we update the logo size if it's a problem?

**Comment by fditrapani** [comment]
Good call on the updates @folletto. I've gone ahead and made the changes.

**Comment by drw158** [comment]
if the original vectors are altered, make sure it's somehow labeled for small uses only

**Comment by folletto** [comment]
> if the original vectors are altered, make sure it's somehow labeled for small uses only

I was referring exclusively to height — but good clarification, I could have been read differently!

**Comment by folletto** [comment]
The component change is very _classy_ 👍

**Comment by fditrapani** [comment]
Thanks @folletto 🚀

**Pull request merged**
