### PR TITLE
Fix this.getInitialState is not a function err in DropZone component

### LINKED ISSUE #7353: this.getInitialState is not a function
This is error from found through Calypso remote Error logging. We have approx. 2169 of these errors per 24h

### Error message
`this.getInitialState is not a function`

### Paths

- /post/:siteId
- /page/:siteId

### Browsers

- chrome
- firefox

### Stack trace

> 	[{"url":"https:\/\/wordpress.com\/calypso\/post-editor.7c780cf9b5890899ab78.min.js","func":"DropZone.resetDragState","args":[],"line":24,"column":2511,"context":"[\"if(color){this._color=color;this.getEl(\\\"preview\\\").style.backgroundColor=color;return this}return this._color},resetColor:function(){this._color=null;this.getEl(\\\"preview\\\").style.backgroundColor=null;return this},renderHtml:function(){var self=this,id="}]

### Kibana issues
a6e34328614867dfaf08fa28aa1f497d-logstash

### PR DESCRIPTION
**Pull request by lamosty**
Fixes #7353. During [refactoring](https://github.com/Automattic/wp-calypso/pull/5383) the DropZone component, `getInitialState` method was removed. However, its call in `resetDragState` method was not removed which causes 2169 errors in 24 hour period (thanks @artpi for your work on JS error logging!).

In this PR, I propose a simple fix in which we reset state in `resetDragState` more verbosely by enumerating specific props and their initial values instead of calling some method. Props @aduth for this solution and help.

I also reuse the `resetDragState` method in `onDrop` event handler as the resetting functionality was unnecessarily duplicated there.

## Testing Instructions

To be honest, I couldn't reproduce the issue the "normal" way. I couldn't get the [mouseup event](https://github.com/Automattic/wp-calypso/blob/master/client/components/drop-zone/index.jsx#L43-L43) triggered by using Calypso (maybe you could, [here are some steps](https://github.com/Automattic/wp-calypso/pull/550#issuecomment-159694352)).

Fortunately, we can create and fire events manually through Dev Console. So, firstly, let's reproduce the bug and then see if it's fixed:

1. Checkout `master` branch and open `client/components/drop-zone/index.jsx` in your favorite editor;
2. Comment/delete [these lines](https://github.com/Automattic/wp-calypso/blob/master/client/components/drop-zone/index.jsx#L62-L64) (they prevent us from seeing the error with the manual event firing);
3. Load Calypso Media Library or just create a new post;
3. Open Dev Tools and copy paste the following code in the Console tab:

```js
var event = document.createEvent("HTMLEvents");

event.initEvent("mouseup", true, true);

window.dispatchEvent(event);
```
4. Notice the `this.getInitialState is not a function` error;
5. Checkout this branch and do the same;
6. Is there still an error?

cc @aduth @ockham @gwwar @timmyc @artpi 

Test live: https://calypso.live/?branch=fix/drop-zone-reset-drag-state

### CODE REVIEW

**Comment by gwwar** [comment]
👍 Code makes sense and tests well. :shipit: Nice find from @artpi's js error logging

**Comment by lamosty** [comment]
Thanks for the review!

**Comment by artpi** [comment]
Splendid! I am excited to get JS-Error logging back and running to see if the error is gone :)

**Comment by lamosty** [comment]
> I am excited to get JS-Error logging back and running to see if the error is gone

Me too! The thing is, there can be some other very rare errors we overlooked in this part of codebase. The JS error logging utility is really helpful.

**Pull request merged**
