### PR TITLE
Jetpack Connect: Jetpack log in

### PR DESCRIPTION
**Pull request by sirreal**
This PR adds special handling for a new login route at `/log-in/jetpack`.

- Links in the masterbar from within Jetpack Connect should now use the `/log-in/jetpack` route
- Links in the masterbar from `/log-in/jetpack` point to Jetpack Connect path
- Footer links from Jetpack Connect signup (`/jetpack/connect/authorize` when logged out) use the `/log-in/jetpack` route
- Email is preserved when moving between signup (`/jetpack/connect/authorize`) <-> login (`/log-in/jetpack`)
- Locales are preserved moving between forms
- Login form is styled when feature is enabled (development env)

See p1HpG7-4Qr-p2

✅ Related patch D10062-code is deployed.

Supersedes #21901 

## Known issues

If you toggle back and forth between login/Jetpack Connect signup via the masterbar, sometimes the redirection is wrong and the masterbar signup points to `/start` 😕 

It seems to occur when navigating back and forth too fast, I haven't found a solution yet but will look more soon. You can see the issue at the end of the gif

## Screens

jpc

## Testing

Try these flows starting with both default `en` locale, and changing the test site URL before starting. D10100-code will be merged soon, but for now you'll land on an unlocalized login page when starting connection from WP Admin. Just append the desired locale like `/log-in/jetpack/es`. From there, the locale should be maintained when moving around.

1. Get a new site with Jetpack installed and activated
1. Ensure you're logged out of WordPress.com
1. Ensure the site user's email is associated with a WordPress.com email
1. Ensure moving with masterbar links stays within the flow
1. Ensure email is maintained when moving between login and Jetpack Connect
1. Try to "escape" these flows (see p1HpG7-4P7-p2)
1. Change the login page `redirect_to` to something else (not a `/jetpack/connect/authorize` url) and ensure that the default signup url is used (`/start`).

### CODE REVIEW

**Comment by sirreal** [comment]
Failing test 😖 
https://github.com/Automattic/wp-calypso/blob/b20e6670bb0f272a74e87ed14774c039a4e1dfc7/client/layout/test/index.js#L13-L31

**Comment by sirreal** [comment]
The test failure can easily be fixed by adding the `store` via context or just using a `Provider`. The test quality suffers a bit, but the intent is preserved (and perhaps improved).

**Comment by seear** [comment]
> If you toggle back and forth between login/Jetpack Connect signup via the masterbar, sometimes the redirection is wrong and the masterbar signup points to /start

It always seems to happen on the toggle _after_ this warning has appeared in the console:

screen shot 2018-02-14 at 16 54 54

**Comment by sirreal** [comment]
I'm breaking this into smaller and more focues PRs.

**Pull request closed without merging**
