### PR TITLE
Split `lib/media/utils`

### PR DESCRIPTION
**Pull request by sgomes**
This `utils` module is a large monolith that becomes hard to tree-shake; instead, it's best to split it into individual modules and re-export those in an index file. For more background, see p4TIVU-9mu-p2.

#### Changes proposed in this Pull Request

* Split `lib/media/utils` into individual modules with an index

#### Testing instructions

There are no actual code changes, only moving things around, so the unit tests and a build without errors should be enough to validate the PR.

### CODE REVIEW

**Comment by sgomes** [comment]
The results definitely seemed good enough to warrant this PR, so I removed the draft status.

Please take a look! Thanks!

**Comment by sgomes** [comment]
The full E2E tests appear to be failing with an unrelated issue.

**Comment by sgomes** [comment]
To clarify the results, since ICFY totals are still wrong:

- The critical path grows only by about 50 bytes gzipped
- The manifest gets a bit smaller
- Most sections become ~5KB gzipped smaller, some others ~2KB smaller, and only the editors get a bit larger (500B-900B gzipped)
- Several async chunks become ~5KB gzipped smaller too, with two growing a bit in size (1.5KB, 2KB)

**Review by sarayourfriend — APPROVED** [review]
LGTM! I prefer these smaller, one-function modules anyway 😁 It's great that it aligns with perf goals.

**Comment by sgomes** [comment]
> LGTM! I prefer these smaller, one-function modules anyway 😁

Yes! Small modules are so much neater 😄 

Thank you for the speedy review, @saramarcondes! 🙇

**Pull request merged**
