### PR TITLE
Use correct asset.php file for Webpack dependency extraction

### LINKED ISSUE #36206: Full Site Editing: Update scripts dependencies for Gutenberg 6.5
As reported in p7H4VZ-2jE-p2, a breaking change on how the scripts dependencies are generated has been merged in Gutenberg 6.5: https://github.com/WordPress/gutenberg/pull/17298.

We should be ready to update this part of the FSE class as suggested in the P2:

https://github.com/Automattic/wp-calypso/blob/00ac5a72fd3c3bb12f35c305fbb296da30978e97/apps/full-site-editing/full-site-editing-plugin/full-site-editing/class-full-site-editing.php#L161-L173

### PR DESCRIPTION
**Pull request by noahtallen**
We first thought it was assets.php (plural) which is not the case.

#### Changes proposed in this Pull Request

* Use `.asset.php` instead of `.assets.php`

#### Testing instructions
* Build Full Site Editing and actually run it on a site to verify that no warnings or errors are generated.

Fixes #36206

### CODE REVIEW

**Comment by noahtallen** [comment]
I verified this is working on my wpcom sandbox. Before this change, both FSE and the post lists block threw errors into the debug log. After this change, those errors no longer appear.

**Review by sirreal — APPROVED** [review]
Looks like that's the right suffix, thanks for the fix 👍 

https://github.com/WordPress/gutenberg/blob/f38e17805d32eb181aebde69e12eddc8c7d2fbca/packages/dependency-extraction-webpack-plugin/index.js#L133

**Comment by Copons** [comment]
Thanks @noahtallen!
It was totally my fault that I didn't catch the issue 😞

**Comment by noahtallen** [comment]
it's fine! I would have expected the bug to show up in the build process as well :)

**Pull request merged**
