### PR TITLE
Framework: Use Prettier

### PR DESCRIPTION
**Pull request by samouri**
Background information for this PR, as well as voting on whether or not you support it, is available here: https://github.com/Automattic/wp-calypso/issues/12260.

This PR seeks to figure out the details.
I've taken guidance from gh-notifications-client /tree/master/bin

Implementation notes:
1. Added a precommit hook that prettifies newly added/modified files
2. Added a eslint style configuration remover.
3. Ran prettify (cmd provided below)

Commands I ran:
```
./node_modules/.bin/prettier --write --print-width=100 --single-quote --tab-width=4 --trailing-comma=es5 "{test,server,client}/**/*.jsx"
./node_modules/.bin/prettier --write --print-width=100 --single-quote --tab-width=4 --trailing-comma=es5 "{test,server,client}/**/*.js"
./node_modules/.bin/prettier --write --print-width=100 --single-quote --tab-width=4 --trailing-comma=es5 "*.js"
```

### CODE REVIEW

**Comment by samouri** [comment]
Interesting how many more linebreaks `prettier` uses than we were doing.  In that sense its actually more liberal about whitespace

**Comment by gziolo** [comment]
So we have 300K+ lines in Calypso, and it will increase the number by 7-8%. Interesting.

**Comment by dmsnell** [comment]
@samouri if we do this, we should probably look at having some "bot" user do the change so it doesn't royally mess with your user stats…

**Comment by gziolo** [comment]
If we introduce `prettier` we should also mitigate issues with formatting when using `codemods`. See related discussion: https://github.com/Automattic/wp-calypso/pull/12521#discussion_r108099789/.

**Comment by blowery** [comment]
related https://github.com/prettier/prettier-atom/issues/133

**Comment by samouri** [comment]
closing because I don't plan on pushing this forward in the same capacity anymore. see https://github.com/Automattic/wp-calypso/pull/14010

**Comment by dmsnell** [comment]
geez @samouri - the least you could have done is rebase it :wink:

**Pull request closed without merging**
