### PR TITLE
SDK: Add Jetpack markdown block

### PR DESCRIPTION
**Pull request by tyxla**
This PR adds the Jetpack **Markdown** block to the set of Gutenberg extensions, based on the previous work done by @Ferdev in: https://github.com/Automattic/jetpack/pull/9705.

The code hasn't been edited at this time - the idea is to be able to build it in Calypso and use it directly in Jetpack as a Gutenberg block.

To test:
* Build the block:
    ```
    ./bin/sdk-cli.js build-block --editor-script ./client/gutenberg/extensions/markdown/jetpack-markdown-block.js
    ```
* Copy the built file from: `client/gutenberg/extensions/markdown/build/blocks-markdown.js` to Jetpack's folder - `modules/markdown/block.js`
* Checkout `try/markdown-gutenberg-block-externally-built` branch in your Jetpack installation (see https://github.com/Automattic/jetpack/pull/9954).
* Insert "Markdown" block in Gutenberg and watch out for errors.

### CODE REVIEW

**Comment by tyxla** [comment]
This is ready for review, but it's probably a good idea to apply some linting ignore rules and fix whatever is possible - can do that tomorrow.

**Comment by dmsnell** [comment]
I think `gutenberg/extensions/markdown-block` might have a warrant as a name over `markdown` since `markdown` might easily become a term of great overlap, if that makes sense.

these aren't strong feelings of mine, just thinking about how complex the whole markdown issue is and that makes me think we might reasonable have multiple markdown pieces in the puzzle

**Comment by dmsnell** [comment]
> What's the difference between this block and the Tiled Gallery block?

Probably it has more to do with the fact that `Tiled Gallery` is a noun while `Markdown` in this case is an adjective. `markdown-paragraph` is misleading because multiple paragraphs can theoretically exist inside of the block; `markdown-area` could work; `markdown-document`; `markdown-thing` ???

`markdown-block` seemed to make sense but possibly what actually triggered my senses is the need to have a noun.

> stack this one under /jetpack, or to keep it in the root

there's no clear need to group extensions at this point. let's leave it in the root

> whether we're planning to make blocks embeddable in multiple environments, or whether each of them will be dedicated to a single environment.

we're safe to assume that what we write here should work in any of our products. I _think_ you mean Calypso vs. Jetpack when you speak of environments but maybe I'm missing something.

**Comment by tyxla** [comment]
To test this on dotcom sites, have a look at D16768-code.

**Pull request merged**
