### PR TITLE
A4A > Marketplace: Hosting page UI enhancements

### PR DESCRIPTION
**Pull request by yashwin**
Closes https://github.com/Automattic/jetpack-genesis/issues/464
Closes https://github.com/Automattic/jetpack-genesis/issues/460

## Proposed Changes

This PR:

- Makes some text changes to match the design
- Does some UI enhancements to fix some design issues and match the design.
- Does some fixes to the mobile view by making the font size smaller.

NOTE: 

- Changes to Refer Mode will be done in another PR
- Final Testimonials will be updated in another PR

## Why are these changes being made?

* These changes are being made to match the hosting page design.

## Testing Instructions

* Open the A4A live link
* Verify the UI looks good on all the screen sizes and matches the design: 3JELpER0gWwwI1BMrTyGE0-fi-6836_71380

screencapture-agencies-localhost-3000-marketplace-hosting-2024-08-02-09_35_57
screencapture-agencies-localhost-3000-marketplace-hosting-2024-08-02-09_36_21
screencapture-agencies-localhost-3000-marketplace-hosting-2024-08-01-12_09_34

iPhone-12-PRO-agencies localhost (2)
iPhone-12-PRO-agencies localhost (4)

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Comment by jkguidaven** [comment]
Everything looks good, and the changes make sense to me. 

I noticed some discrepancies in the mobile view compared to the Figma design. We are displaying **'Hosting Marketplace'** instead of just **'Hosting'**, which takes up extra space. I'm okay if we also fix the production version to use Hosting here as it takes fewer space.

Screenshot 2024-08-01 at 3 06 14 PM

**Comment by yashwin** [comment]
> Everything looks good, and the changes make sense to me.
> 
> I noticed some discrepancies in the mobile view compared to the Figma design. We are displaying **'Hosting Marketplace'** instead of just **'Hosting'**, which takes up extra space. I'm okay if we also fix the production version to use Hosting here as it takes fewer space.
> 
> Screenshot 2024-08-01 at 3 06 14 PM

Thanks for the review, @jkguidaven!

Agree, I have updated it now: https://github.com/Automattic/wp-calypso/pull/93176/commits/ae884e8a49ca3b5d2b4e72b3cf35fcc1d828f138

**Review by jkguidaven — APPROVED** [review]
Thanks for addressing my comment. LGTM now 👍

**Comment by madebynoam** [comment]
Addign my notes as I go:
If they own zero sites, we shouldn't show the 0:
image

**Comment by madebynoam** [comment]
Does the slider for WordPress.com work for you? I can't seem to move it?

**Comment by madebynoam** [comment]
@yashwin these two quotes for Pressable are good to go with:
3JELpER0gWwwI1BMrTyGE0-fi-6836_78993

CC @jeffgolenski

**Comment by madebynoam** [comment]
For the WordPress quote, let's go with the one we have, and add the second one when it comes in:
3JELpER0gWwwI1BMrTyGE0-fi-6836_73461

CC @jeffgolenski

**Comment by madebynoam** [comment]
For Pressable they actually get Jetpack Complete. I've done a pass at the updated copy here:
3JELpER0gWwwI1BMrTyGE0-fi-6836_78395

@yashwin @jeffgolenski

**Comment by madebynoam** [comment]
"Pressable plan names are confusing and should change (e.g., WP 3 plan is for 10 sites). For the A4A dash, we can remove the plan names altogether, or do what WordPress does where every plan name is just “WordPress.com.”
pfunGA-2mi-p2#comment-4236

@yashwin is this possible, or do we need to do work on the Backend for this.

Instead of WP 1, WP2, Etc
It will always be Pressable for the plan name.

CC @jeffgolenski

**Comment by yashwin** [comment]
Thanks for the review, @madebynoam!

I have addressed all your comments & made the changes: https://github.com/Automattic/wp-calypso/pull/93176/commits/4782f1339fcbdb3b1ddacf7dbe771a9dda77a4a8. I have also updated the screenshots in the description. 

> Does the slider for WordPress.com work for you? I can't seem to move it?

I see we have made it read-only. Could you please clarify, @jkguidaven?

**Comment by jkguidaven** [comment]
> I see we have made it read-only. Could you please clarify, @jkguidaven?

@yashwin, @madebynoam, the slider has been converted to read-only. The Figma design doesn't seem to highlight which slider value can be selected when there is already existing sites, so I had assumed it was purely presentational and only shows how many sites the agency owns. Is this not the case?

**Comment by yashwin** [comment]
> > I see we have made it read-only. Could you please clarify, @jkguidaven?
> 
> @yashwin, @madebynoam, the slider has been converted to read-only. The Figma design doesn't seem to highlight which slider value can be selected when existing sites exist, so I assumed it was purely visual and only shows how many sites the agency owns. Is this not the case?

I see. Let's wait for @madebynoam on this 👍 Thanks!

**Review by madebynoam — APPROVED** [review]
Setting this to approved, @yashwin. Let's just make sure the slider is fixed.

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/16457994

Some locales (Hebrew, Japanese) have been temporarily machine-translated due to translator availability. All other translations are usually ready within a few days. Untranslated and machine-translated strings will be sent for translation next Monday and are expected to be completed by the following Friday.

Thank you @yashwin for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/16457994).

**Pull request merged**
