### PR TITLE
Signup: Remove unused FSE Beta assignment code

### PR DESCRIPTION
**Pull request by creativecoder**
#### Changes proposed in this Pull Request

Now that all new sites created have FSE features turned on, we no longer need any code related to beta assignment by user id. This change removes that code (that was added in https://github.com/Automattic/wp-calypso/pull/60330)

It appears that the user id sign up dependency introduced in https://github.com/Automattic/wp-calypso/pull/60330 may cause issues with mobile signup flows. This removal should resolve that problem (see p1644013502153649-slack-CFFF01Q4V)

#### Testing instructions

* There shouldn't be any change noticed in this PR. Make sure the new user signup and `site-setup` flow works as expected.

### CODE REVIEW

**Review by p-jackson — APPROVED** [review]
Looks good 👍 

There's a bit of a PR timing issue. #60940 is also adding some code to add `user_id` as a signup dependency. If this PR merges first then #60940 should stop adding `user_id`. If this PR merges second then it should also remove the new `user_id` reference added by #60940.

https://github.com/Automattic/wp-calypso/pull/60940/files#diff-23bfc82578c492af54a8e45009abf3961e8e8669d1febb805c0bc7b589c46d54R128

CC @enejb

**Review by p-jackson — CHANGES_REQUESTED** [review]
#60940 merged first 🐎 

This PR should remove this line too:

https://github.com/Automattic/wp-calypso/blob/ad5405ffeb368943205429975c11307ad38ac422/client/blocks/signup-form/passwordless.jsx#L128

**Comment by creativecoder** [comment]
Thanks @p-jackson ! Should be all set now.

**Review by p-jackson — APPROVED** [review]
Passwordless and passwordful flows working 👍

**Pull request merged**
