### PR TITLE
Reader: Fix busted empty state recs in Search

### PR DESCRIPTION
**Pull request by jancavan**
This fixes: https://github.com/Automattic/wp-calypso/issues/9730

**Before:**
screenshot 2016-12-06 15 56 45

**After:**
screenshot 2016-12-06 15 57 58

Dropped down to a single column for really narrow widths as mentioned in: https://github.com/Automattic/wp-calypso/issues/9730#issuecomment-263989324

There's going to be some spacing issues similar to https://github.com/Automattic/wp-calypso/issues/9739, but I'll fix those separately. This PR is solely for fixing some overlapping/misalignment due to breakpoints.

### CODE REVIEW

**Comment by samouri** [comment]
First off -- this is so much better!

Question though: is the change from 2-column --> 1 col --> 2 col --> 1 col intentional?

Starting from a large desktop size and decreasing the width, we eventually reach 1 col, then the sidebar disappears and we are back to 2 col for 100 pixels or so.

**Comment by jancavan** [comment]
> Question though: is the change from 2-column --> 1 col --> 2 col --> 1 col intentional?

@samouri Yes. Originally, <730px had 2-columns which made the cards too narrow. It's being changed to a single column now. I do think, however, that once we drop the sidebar, 2-columns make sense at a certain breakpoint. Otherwise, it'd look like this:

screenshot 2016-12-06 19 01 10

Our Related Posts also behave similarly.

**Comment by samouri** [comment]
Thanks for the answer @jancavan, makes sense to me!

**Comment by bluefuton** [comment]
@jancavan I'm getting a block of whitespace at the top of rec on the single column layout (<730px) when the rec doesn't have an image:

screen shot 2016-12-08 at 10 27 28
screen shot 2016-12-08 at 10 29 15

**Comment by jancavan** [comment]
Nice, good catch @bluefuton! Fixed in: https://github.com/Automattic/wp-calypso/pull/9837/commits/3b50db2f6718269362efe50f12f4c3b0cd2593a3

**Before:**
screenshot-2016-12-08-09 58 41

**After:**
screenshot-2016-12-08-09 58 56

**Comment by fraying** [comment]
Anyone else seeing this? (I'm in Safari.)

screen shot 2016-12-08 at 10 29 30 am

**Comment by blowery** [comment]
@fraying seeing it too. It's only in the breakpoint with a single column and the sidebar.

**Comment by jancavan** [comment]
> Anyone else seeing this? (I'm in Safari.)

Fixed in: https://github.com/Automattic/wp-calypso/pull/9837/commits/b9c057eeb03dd6df9c6a0fbc99f5d87582c479a0

**Before:**
screenshot 2016-12-08 11 25 12

**After:**
screenshot 2016-12-08 11 25 18

@blowery Is this the best way of appending this class? https://github.com/Automattic/wp-calypso/pull/9837/commits/b9c057eeb03dd6df9c6a0fbc99f5d87582c479a0#diff-e6b36abe5c53b8f8009a62958e11c066R97

This is to eliminate some of the extra space in narrow breakpoints for those without excerpts.

**Before:**
screenshot 2016-12-08 11 58 06

**After:**
screenshot 2016-12-08 11 59 10

**Comment by fraying** [comment]
Fixed! Woo hoo! 🎉

**Comment by bluefuton** [comment]
> Is this the best way of appending this class? 

Looks good to me 👍

**Pull request merged**
