### PR TITLE
Assembler: framer-motion-reorder-list

### PR DESCRIPTION
**Pull request by taipeicoder**
Related to #

## Proposed Changes

*

## Testing Instructions

*

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

**Comment by taipeicoder** [comment]
I tried to use [LazyMotion](https://www.framer.com/motion/lazy-motion/) as an attempt to reduce bundle size, but it doesn't seem to play well with [Reorder](https://www.framer.com/motion/reorder/). As an alternative, I've opted for creating a new package `framer-motion-reorder-list` so that it can be loaded async via `<AsyncLoad />`.

**Comment by taipeicoder** [comment]
Using the [Reorder](https://www.framer.com/motion/reorder/) component is causing a transition issue for every re-render... this is a minimal reproduction on the Goals screen:

https://github.com/Automattic/wp-calypso/assets/797888/2ed20bb6-5d1b-43cf-8153-d97542b2ee0d

**Comment by taipeicoder** [comment]
This issue isn't specific to Reorder, using a LayoutGroup or event the `layout` prop will cause the same issue 🙁. Might be related how the Stepper is structured. I tried the same code in the Theme Showcase and it didn't have this issue.

The problem: Somehow framer-motion is using the viewport to calculate position. Using something like `layoutRoot` should solve the issue but it doesn't.

**Comment by taipeicoder** [comment]
I found a workaround using `style={{ originX: '0px', originY: '0px' }}`. Will try this tomorrow.

**Comment by arthur791004** [comment]
There are lots of places that may return a new value on every rendering, e.g.: `useSteps`, `useStepNavigation`, etc 😓

**Comment by taipeicoder** [comment]
> I found a workaround using `style={{ originX: '0px', originY: '0px' }}`. Will try this tomorrow.

This worked, breakthrough! 
There are still some positioning issues, though.

https://github.com/Automattic/wp-calypso/assets/797888/c51a1ee6-7fcc-4cdc-9113-8f3e24486289

**Comment by taipeicoder** [comment]
Turned out that the positioning issue was caused by `style={{ originX: '0px', originY: '0px' }}`... I'll try to manually calculate those values tomorrow.

**Comment by taipeicoder** [comment]
After some more investigation, this might to be related to `react-router-dom` and how it's using `display:none` when mounting a step, causing issues in the position calculation.

See: https://github.com/remix-run/react-router/discussions/8008

**Comment by taipeicoder** [comment]
After another day of investigation, the problem seems to be that react-router is causing framer-motion to calculate positioning incorrectly. For the sake of time boxing this, I'll move this to the icebox and start looking into react-draggable, which is not ideal since it doesn't come with all the transition goodies that framer-motion has. I'll keep this PR open in case there's better support in the future for either libraries to work together.

**Comment by taipeicoder** [comment]
See in the developer tool console how the bounding box of the large preview pattern list suddenly loses all dimensions while dragging:


https://github.com/Automattic/wp-calypso/assets/797888/f3bbc056-6d72-4d3d-b6ed-8d116d4a1f04

**Comment by arthur791004** [comment]
Looks like there are still several [issues](https://github.com/framer/motion/issues?q=is%3Aissue+reorder+is%3Aopen) related to `Reorder` 🤦‍♂️

**Comment by taipeicoder** [comment]
Follow up PR https://github.com/Automattic/wp-calypso/pull/86442

**Pull request closed without merging**
