### PR TITLE
Add marketplace CTA on /marketing/tools

### PR DESCRIPTION
**Pull request by lupus2k**
#### Changes proposed in this Pull Request

Adjust CTA on /marketing/tools to focus on premium plugins, and link to the Marketplace.

#### Testing instructions

* Go to /marketing/tools and see if matches the design and text

#### Screenshots
image

Related to #62308

### CODE REVIEW

**Review by Rolilink — DISMISSED** [review]
cta needs to link to the marketplace

**Comment by lupus2k** [comment]
> cta needs to link to the marketplace

Fixed!

**Review by lsl — APPROVED** [review]

**Comment by lsl** [comment]
Looks good, lets wait for translation to come through, not sure how much benefit there is deploying this early.

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/7230444

Thank you @lupus2k for including a screenshot in the description! This is really helpful for our translators.

**Comment by Rolilink** [comment]
> Looks good, lets wait for translation to come through, not sure how much benefit there is deploying this early.

There is any alternative to merge this and show them to the user when the translations come through ? maybe using some feature flag? just thinking out loud.

**Comment by lsl** [comment]
> There is any alternative to merge this and show them to the user when the translations come through ? maybe using some feature flag? just thinking out loud.

There is a [hasTranslate](https://github.com/Automattic/wp-calypso/blob/7dfafccf2c723707cbf5819cd7fc2d8bb3703784/packages/i18n-calypso/README.md?plain=1#L218-L228) method in i18n-calypso but it's [usage](https://github.com/Automattic/wp-calypso/blob/0d7e7fbafd83c44a0c732c9dc627c195ac448885/client/components/domains/reskin-side-explainer/index.jsx#L18-L25) is quite clunky and nobody ever cleans them up so I don't really suggest it.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/7230444).

**Pull request merged**
