### PR TITLE
Pricing 2023 : Add all tooltips and fix a few errors in text

### PR DESCRIPTION
**Pull request by ddc22**
#### Proposed Changes

* Adds all the tooltips for the new plans layout

image

#### Testing Instructions
* Go to /start/plans?flags=onboarding/2023-pricing-grid
* Make sure the tooltip popover works by hovering over all the features in the plans details and comparison grids.
* Makes sure the tooltips match the spec

#### Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

Fixes Automattic/martech#1460

### CODE REVIEW

**Comment by claudiucelfilip** [comment]
@jdc91 I went through all the features and spotted a few inconsistencies in the tooltip or the feature name compared to the design:
Screenshot 2023-02-01 at 10 12 02
Screenshot 2023-02-01 at 10 06 51
Screenshot 2023-02-01 at 10 04 13
Screenshot 2023-02-01 at 10 02 40
Screenshot 2023-02-01 at 10 02 05

**Comment by ddc22** [comment]
Thanks for the feedback @claudiucelfilip I have fixed the issues, Can you have another look :).

**Comment by claudiucelfilip** [comment]
> Thanks for the feedback @claudiucelfilip I have fixed the issues, Can you have another look :).

@jdc91 Thanks for addressing the inconsistencies! Can confirm that they're resolved now.

There's a last-minute addition, though: Contact Forms needs the Jetpack logo. 
It also looks like it's unsupported by all plans.
Screenshot 2023-02-01 at 15 41 28

**Review by claudiucelfilip — APPROVED** [review]

**Comment by ddc22** [comment]
@claudiucelfilip Thanks for the approval this issue is tracked in
Automattic/martech#1464

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/7787683

Thank you @jdc91 for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/7787683).

**Pull request merged**
