### PR TITLE
Post/Page List: add section headers with 'add new' buttons

### PR DESCRIPTION
**Pull request by michaeldcain**
As part of the upcoming sidebar changes, this adds a section header to the top of the page, posts, and custom post type lists with a button to 'Add New {Post Label}'.

**Changes:**

post-list
page-list-hierarchical
page-list-chronological

**To test:**

- visit `/pages/`
- verify that the section header is shown above the page list, with an 'Add New Page' button that links to the correct editor for a new page
- visit `/posts/`
- verify that the section header is shown above the post list, with an 'Add New Post' button that links to the correct editor for a new post
- enable a custom post type (portfolio or testimonial) in Settings > Writing > Content Types
- visit the custom post type list from the sidebar
- verify that the section header is shown above the post type list, with an 'Add New {Post Type}' button that links to the correct editor for a new post of that type

### CODE REVIEW

**Comment by shaunandrews** [comment]
I think this is fine as-is, but think maybe we could bring the section title up and put the button near that. Here's a few variations:

image

image

**Comment by kellychoffman** [comment]
:shipit:

**Comment by drw158** [comment]
Not a blocker, but I noticed that the Block CPT has a lowercase label, and the other post types have uppercase labels

Screen Shot 2019-03-26 at 2 51 19 PM

Screen Shot 2019-03-26 at 2 52 57 PM

It would be great to do something more holistic like what Shaun suggested in later iterations.

**Comment by michaeldcain** [comment]
> Not a blocker, but I noticed that the Block CPT has a lowercase label, and the other post types have uppercase labels

@drw158: that string comes from the server with its capitalization. I can force capitalization with CSS, but can't force it to match the "Add new block" capitalization… although the add new block capitalization looks incorrect.

[Add New Post](https://github.com/WordPress/WordPress/blob/master/wp-includes/post.php#L1624)
[Add New Block](https://github.com/WordPress/WordPress/blob/master/wp-includes/post.php#L264)

**Comment by michaeldcain** [comment]
@drw158 where is that "add block" button?

**Comment by drw158** [comment]
@michaeldcain I see it on an Atomic site, with the Gutenberg plugin installed. Probably an edge case.

Screen Shot 2019-03-27 at 9 21 22 AM

**Comment by michaeldcain** [comment]
> I see it on an Atomic site, with the Gutenberg plugin installed. Probably an edge case.

@drw158: I tracked down the string in the backend, I'll follow up with a different diff for that.

> I think this is fine as-is, but think maybe we could bring the section title up and put the button near that.

@shaunandrews: I'll open a different PR with that change to start a new discussion. I don't want to block this one with the sidebar edits coming

**Pull request merged**
