### PR TITLE
Domains: Group mapping and transfers together to reduce confusion

### PR DESCRIPTION
**Pull request by klimeryk**
#### Changes proposed in this Pull Request

When a domain is pending transfer (pending_registry), we automatically add a domain mapping to ensure the domain starts working with the WPCOM site ASAP. However, that leads to a confusing UX:
Screenshot 2020-09-30 at 16 48 12

It's also causing an unnecessary alert in the sidebar:
Screenshot 2020-09-30 at 16 48 26

In this PR, I'm trying to get rid of the extra mapping row and instead let the transfer one take over some of its functions. Most importantly: setting the DNS records.

#### Testing instructions

This patch requires backend changes: D50440-code.

Find a domain pending transfer (see the backend patch for details). Make sure you only see the transfer domain in Calypso:
Screenshot 2020-09-30 at 16 45 39

There should be no alerts (unless related to the transfer-in).

When viewing details of the transfer-in, you should have the option to manage DNS records:
Screenshot 2020-09-30 at 16 46 53

This should give them a clear idea where to migrate their existing DNS records so that they are ready to change nameservers when the transfer is complete. Or, if they changed the nameservers before transfer-in, they can easily manage DNS records (without having to look for that option in the domain mapping).

If the domain is pointing to our servers, there should also be the usual information about SSL ceritifcate.

### CODE REVIEW

**Comment by fditrapani** [comment]
I tried to test this locally but couldn't get it to work on my end. I managed to query the database for some transferring domains and then SU-ed into their sites to see the updates but I kept seeing the mapped domain. 

Everything looks good from the screenshot you shared except for two things:
- The `Transfer` label in the domain manager isn't very clear or descriptive. Can we can change it from `Transfer` to `Transferring Domain` or `Domain Transfer`?
- It looks like there's some extra space after the paragraph. Looking at your code, it looks like it might be unrelated to this PR?

**Review by hambai — APPROVED** [review]
Tested this and it looks good. I wonder about something else - if the transfer has started and the nameservers are not pointed at us maybe we should not show the DNS management button at all? Because at that point technically they can't change the DNS records. But we can fix in a follow up PR

**Comment by klimeryk** [comment]
> if the transfer has started and the nameservers are not pointed at us maybe we should not show the DNS management button at all? Because at that point technically they can't change the DNS records.

Actually, we _do_ want them to edit DNS records in that case. We want users to be able to set up the DNS records _before_ they make the switch to our nameservers - to minimize downtime. Otherwise, they have to switch nameservers to ours and _then_ quickly update DNS records.

As seen on the screenshot, there's a _hint_ that the domain is pointing to an external service:

Screenshot 2020-09-30 at 16 46 53

But I agree that it might be still confusing and we might need to iterate. Maybe at some point we introduce a kind of compromise, where we show the UI for updating the nameservers (like we do for registered domains), but with the explicit caveat that these nameservers will be set on successful transfer-in. So that users can "prepare"/"stage" the correct nameservers/DNS records once the transfer is complete.

**Comment by klimeryk** [comment]
>     * The `Transfer` label in the domain manager isn't very clear or descriptive. Can we can change it from `Transfer` to `Transferring Domain` or `Domain Transfer`?

Good idea - I've renamed it in https://github.com/Automattic/wp-calypso/pull/46056/commits/9be9af525a76883f5144012830d2fed1dbd925ee to `Domain Transfer`. It's a central place for that string, so it's re-used in a few places. For example, in the heading where it says `Transfer Settings`. It will now be `Domain Transfer Settings`.

I've also noticed that I think those are not translated: https://github.com/Automattic/wp-calypso/blob/9be9af525a76883f5144012830d2fed1dbd925ee/client/lib/domains/get-domain-type-text.js But that's a separate issue cc @hambai.

> It looks like there's some extra space after the paragraph. Looking at your code, it looks like it might be unrelated to this PR?

Yup, that's been there before the PR.

**Comment by fditrapani** [comment]
> Good idea - I've renamed it in 9be9af5 to Domain Transfer. It's a central place for that string, so it's re-used in a few places. For example, in the heading where it says Transfer Settings. It will now be Domain Transfer Settings.

Awesome. Thanks for updating that. I think that works well as a replacement in other places too. 

> Yup, that's been there before the PR.

Cool, no problem. For another PR :D

**Pull request merged**
