### PR TITLE
Checkout: Update business plan theme upload feature copy

### PR DESCRIPTION
**Pull request by tyxla**
This PR updates the copy of the theme upload feature in the checkout "Thank You" page after a  business plan purchase. Suggested by @michelleweber in https://github.com/Automattic/wp-calypso/pull/17245#issuecomment-322860269.

Before:

After:

To test:
* Checkout this branch
* Purchase a Business plan for one of your .com sites.
* Verify you can see the updated theme upload feature in the thank you page, and it looks well, as shown on the screenshot.

### CODE REVIEW

**Comment by ockham** [comment]
Not sure the 'Give one a try!' text was meant to be the button caption by @michelleweber?

**Comment by tyxla** [comment]
I'm not sure either, let's wait for her feedback. If it was meant to be part of the description, I'll apply this to #17270 as well.

**Comment by michelleweber** [comment]
@ockham is right on, it's meant to be part of the description.

**Comment by tyxla** [comment]
Thanks folks! I've updated the copy again, feel free to have a new look:

**Pull request merged**
