### PR TITLE
[Fraud] Get Fingerprinted Visitor ID

### PR DESCRIPTION
**Pull request by pottedmeat**
Related to https://github.com/Automattic/gold/issues/461

## Proposed Changes

* Gets FingerprintJS to build
* Adds `X-Fingerprint` header

## Why are these changes being made?

* To support payment processors

## Testing Instructions

* Requires D160917-code
* Should be tested from supported cross domains e.g. agencies.automattic.com
* Add an item to checkout (e.g. upgrade your plan or buy a domain)
* View the console to see the visitor ID

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Comment by rcanepa** [comment]
@pottedmeat, I tested these changes in combination with [D160917-code](https://href.li/?https://code.a8c.com/D160917) and confirmed that there is still more work to do on the backend side (see D160917#3005290-code). Otherwise, A4A and Jetpack cloud will break.

**Comment by pottedmeat** [comment]
The backend patch adds support for both REST APIs now. You should be able to patch and verify. But just to be extra safe, the Calypso patch limits the header to only `/me/transactions` for now.

**Comment by rcanepa** [comment]
> The backend patch adds support for both REST APIs now. You should be able to patch and verify. But just to be extra safe, the Calypso patch limits the header to only `/me/transactions` for now.

I confirm that the backend changes successfully add support for both REST APIs.

> But just to be extra safe, the Calypso patch limits the header to only `/me/transactions` for now.

FWIW, I also tested the case without this limit and both A4A and Jetpack Manage apps worked as expected.

**Review by chrisfromthelc — APPROVED** [review]
This looks to work as expected with the new back end changes.

**Review by rcanepa — APPROVED** [review]
LGTM!

**Pull request merged**
