### PR TITLE
Signup: Headstart: Pass the current locale to Headstart.

### LINKED ISSUE #3704: Signup: Headstart: pass the current signup language to Headstart.
Headstart will be rolled out to signup starting with English signups only, while we prepare translations for all Headstart content. We need to be able to pass the signup language to Headstart from signup, so that Headstart knows whether to run or not (and down the road, which language to use for Headstart content).

### PR DESCRIPTION
**Pull request by kwight**
This will be used server-side to create content in the same language as that used during signup. Fixes #3704 .

### CODE REVIEW

**Comment by kwight** [comment]
@sirbrillig for review

**Comment by kwight** [comment]
This is on hold until we start supporting additional languages.

**Comment by kwight** [comment]
@sirbrillig we can review and merge this any time.

**Comment by sirbrillig** [comment]
:ship:

**Pull request merged**
