### PR TITLE
Fix localStorage-bypass to work in Firefox

### PR DESCRIPTION
**Pull request by brandonpayton**
Today, to avoid conflicts when supporting multiple users in separate windows, our localStorage bypass tries to create properties on window.localStorage to shadow methods like setItem and getItem, but that doesn't work in Firefox. The assignments are silently ineffective. This is [according to spec](https://github.com/whatwg/html/issues/183#issuecomment-1429446050) because [the Storage interface](https://html.spec.whatwg.org/multipage/webstorage.html#the-storage-interface) is not tagged with [OverrideBuiltins](https://heycam.github.io/webidl/#OverrideBuiltins).

This is needed by #30157 which supports Firefox.

#### Changes proposed in this Pull Request

Instead of trying to add properties on localStorage that shadow Storage methods, redefine `window.localStorage` to refer to an object that implements the same interface we rely upon. Note: Neither the current bypass nor this update fully implement the Storage interface which supports getting and setting props directly on `localStorage` (e.g., `localStorage['prop1'] = value`). For that, we'd need a different implementation that uses Proxy.

#### Testing instructions

* Open a tab for one supported user.
* Open a tab for a different supported user.
* Open the dev tools console for each.
* Run `localStorage.setItem( 'test-key', 'test-value' )` under one tab.
* Switch to console in the other tab, call `localStorage.getItem( 'test-key' )`, and verify it returns `null`.
* Some keys are still allowed to be set on real `localStorage`. One of those keys is 'debug'. Run `localStorage.setItem( 'debug', 'somevalue' )`, switch to the other tab, and verify that `localStorage.getItem( 'debug' )` returns 'somevalue'. Then call `localStorage.removeItem( 'debug' ) to clean up after this test.

### CODE REVIEW

**Comment by jsnajdr** [comment]
There is also the `lib/local-storage` module that provides a memory-based polyfill for `window.localStorage` in case the `setItem` and `getItem` methods don't work. That can happen in private mode, especially in Safari.

https://github.com/Automattic/wp-calypso/blob/master/client/lib/local-storage/index.js#L44-L57

It also assigns to the `localStorage` property values. Can we fix that, too? Let's also test in Safari (we might need an older version rather than the latest).

**Comment by brandonpayton** [comment]
> There is also the `lib/local-storage` module that provides a memory-based polyfill for `window.localStorage` in case the `setItem` and `getItem` methods don't work. That can happen in private mode, especially in Safari.

Thanks for taking a look and mentioning that, @jsnajdr! Is there a reason we shouldn't consolidate to a single localStorage override?

Sure, I should be able to test on older Safari versions through Browserstack.

**Comment by brandonpayton** [comment]
OK, I'll fix lib/local-storage and test in an older version of Safari.

By the way, I'd be willing to do the unification and did not mean to imply you should do the work :)

Thanks!

**Comment by brandonpayton** [comment]
After we spoke today, I worked on unifying the localStorage overrides. It turned out a bit more complicated than I'd hoped. That said, it may be alright and is probably better in one place than in two.

I was able to test defining the localStorage property and defining properties on localStorage in older versions of Safari, but I wasn't able to load the development build in Browserstack Safari versions**. Those versions don't allow redefining the localStorage property but do allow redefining all but their `length` property. It turns out that our lib/local-storage `length` override doesn't work (it just fails silently). In my testing in Safari versions 6-12 (the latest), it's not possible to redefine `localStorage.length`.

In Safari 10-12, it becomes possible to redefine window.localStorage, so we can avoid the problem redefining `localStorage.length` and simply provide our own localStorage object.

This updates the localStorage bypass to first try to redefine `window.localStorage`. If that throws an error, the module tries to override by replacing localStorage methods, which works in Safari 6-9 with the exception of the `length` property.

Unfortunately, while I could test Safari versions in Browserstack, I wasn't able to get Calypso to load beyond the login screen there. I had the same trouble with a build from master too, so I don't think it's related to these changes. Please feel free to take a look at this, but I can troubleshoot testing in the morning.

Thanks!

** Safari 6-9 seemed to encounter an error related to creating the redux store and showed an uninitialized UI. Safari 10-12 showed a login screen but looped the login.

**Comment by jsnajdr** [comment]
Howdy @brandonpayton! The cleanup looks nice :+1: In Calypso, the only methods we use are `setItem` and `getItem`, so we don't need to worry about `length` and others.

Our polyfills also never supported the named property setters and getters:
```js
localStorage.foo = 'foo';
expect( localStorage.getItem( 'foo' ) ).toEqual( 'foo' );
localStorage.setItem( 'bar', 'bar' );
expect( localStorage.bar ).toEqual( 'bar' );
```
And it apparently never caused any issues.

**Comment by brandonpayton** [comment]
Thanks for taking a look, @jsnajdr. I wasn't able to get Calypso loading fully via Browserstack in old Safari versions, but I was able to add `debugger` statements to the lib/local-storage-polyfill module before and after applying the bypass. That allowed me to examine and test the `localStorage` methods so that I am sufficiently comfortable with this change.

**Comment by brandonpayton** [comment]
Adding the Needs Review label to trigger e2e canary tests

**Comment by brandonpayton** [comment]
This passed e2e canary tests and appears ready to merge. I'm out of time today but plan to merge in the morning.

**Pull request merged**
