### PR TITLE
config: alphabetize feature flags

### PR DESCRIPTION
**Pull request by rralian**
This is a lower-priority cleanup PR. There are a ton of them, and they're not in any sensible order. That makes them harder to find and would make it pretty easy to accidentally set a feature in two spots.

I did this by copying the feature object into a javascript console.

set features

And then copying the output of that variable (because the console auto-alphabetizes attributes)

alphabetized in console

And then I copied those lines into an editor and did a regex search/replace to get them into a usable format (quotes around attribute name and comma at the end).

replace: `^([^:]+)([^\n]+)` with `"$1"$2,`

## Testing
I realize this is a difficult PR to review visually, because it would be easy to miss an omission or change in the diff. Probably the best way to make sure I didn't do something crazy is to count the lines removed and added for each file (keeping in mind I am also removing blank lines). Also ensure the final output file looks correct for each features object, with all attribute names quoted, commas at the end of each line except the last attribute, and feature names alphabetized.

### CODE REVIEW

**Comment by nylen** [comment]
I like this :+1:

I wrote a quick script to test it, and everything looks good:  https://gist.github.com/nylen/51f212025af7e7b76953

```
OK: horizon.json
OK: wpcalypso.json
OK: desktop.json
OK: development.json
OK: production.json
OK: stage.json
OK: desktop-mac-app-store.json
```

As a bonus of having an automated test, if you want to wait until after #876 lands, you can re-do the test pretty easily.

**Comment by nylen** [comment]
Also - might be a good idea to add a note to `config/README.md` to keep the config keys sorted when adding new items.

**Comment by rralian** [comment]
Thanks @nylen, good point on the docs... added.

**Comment by rralian** [comment]
rebasing and will run that test again... thanks for making that, btw.

**Pull request merged**
