### PR TITLE
Site Migration: Migration Instructions screen improvements

### PR DESCRIPTION
**Pull request by gabrielcaires**
Related to the comments on the PR  #88813

## Proposed Changes

**Copy Improvements**
* Copy changes and instructions and sub title. 
* Remove <em> from the migrate guru the input names
* Add `'` on the migrate guru input names
* Improve copy (see the screenshots above with the updated version)

**Tech Improvements**
* Type on the hook filename use-site-migraiton-key -> use-site-migration-key`
*  Remove the usage of `&` on the CSS files
* Wrong site type on test files.

## Testing Instructions
**SHORT VERSION:**
1. Enable the feature toggle
2. Access `/setup/site-migration/site-migration-instructions?from=[JN site]&siteSlug=[YOUR_WORDPRESS.COM site created by previous migrations]`
3. Jump to the steps 10, 11 and 12.

**LONG VERSION:**
1. Go to the `/start` URL using the calypso.live instructions
2. Follow the flow until see the "Goals" page
4. Open the browser Web developer tools and copy and paste the following code `sessionStorage.setItem('flags', "onboarding/new-migration-flow")`
5. Type Enter
6. Reload the goals page
7. Select "Import or migrate content"
8. "Where will you import from?" set `https://test-vanilla-wp.godaddy.test-wpcom-migrations.net/`
9. Select "Everything (requires a Creator Plan)" on "What do you want to migrate?"
10. When you arrive at the "Ready to migrate your site?" follow the instructions using the page links and copying the migration key. **Screenshot 1**
11. After following the instructions, refresh the page AFTER 1 minute to see a screen variation. **Screenshot 2**
12. Check again the instructions for the new version, using the links.

### Screenshots 

**Success to get the migration key**
image

**Fail to get the migration key**
image

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Comment by gabrielcaires** [comment]
@javierarce  The copy changes and the quote changes are here.

**Comment by sixhours** [comment]
Screenshot 2024-03-27 at 11 17 05 AM

In testing, I found both of the above links are broken -- they point to a relative path on the `calypso.live` link rather than the user's sites:

`https://container-fervent-fermi.calypso.live/wp-admin/plugin-install.php?s=%2522migrate%2520guru%2522&tab=search&type=term`

`https://container-fervent-fermi.calypso.live/wp-admin/admin.php?page=migrateguru`

I do see the `siteSlug` in the query param for this screen so we have at least one of those, but it's not coming through in the instructions.

**Comment by daledupreez** [comment]
@sixhours, I found incorrect links when the `from` URL parameter didn't include a full, encoded URL, i.e. the URL was `https://some.site.example.com/` and then URL-encoded.

**Comment by gabrielcaires** [comment]
> @sixhours, I found incorrect links when the `from` URL parameter didn't include a full, encoded URL, i.e. the URL was `https://some.site.example.com/` and then URL-encoded.

@daledupreez  @sixhours  Yes, both links require to have `from` param set on the  URL.

The siteSlug is only used on the last link on the fallback screen (screenshot 2).

**Comment by gabrielcaires** [comment]
I wrongly merged this PR, so I reverted and I am going to open a new one. 
New PR is here Site  #89006

**Pull request merged**
