### PR TITLE
Framework: Fix wrong file permissions

### PR DESCRIPTION
**Pull request by stephanethomas**
This pull request fixes wrong file permissions for the sake of consistency as well as to reduce synchronization issues that sometimes happen when Calypso runs inside a container such as [Calypso Bootstrap](https://github.com/Automattic/wp-calypso-bootstrap). These changes only target files starting with a [shebang](https://en.wikipedia.org/wiki/Shebang_(Unix)) as well as a few images:

##### Executable files

```
mkdir temp
git clone git@github.com:Automattic/wp-calypso.git
cd wp-calypso
find ./bin -printf "%m %M %p\n" | sort

664 -rw-rw-r-- ./bin/analyze-css.js
664 -rw-rw-r-- ./bin/codemods/README.md
664 -rw-rw-r-- ./bin/codemods/src/assign-component-to-displayname-variable.js
664 -rw-rw-r-- ./bin/codemods/src/combine-reducer-with-persistence.js
664 -rw-rw-r-- ./bin/codemods/src/combine-state-utils-imports.js
664 -rw-rw-r-- ./bin/codemods/src/config.js
664 -rw-rw-r-- ./bin/codemods/src/i18n-mixin-to-localize.js
664 -rw-rw-r-- ./bin/codemods/src/merge-lodash-imports.js
664 -rw-rw-r-- ./bin/codemods/src/modular-lodash-no-more.js
664 -rw-rw-r-- ./bin/codemods/src/modular-lodash-requires-no-more.js
664 -rw-rw-r-- ./bin/codemods/src/remove-linked-state-mixin.js
664 -rw-rw-r-- ./bin/codemods/src/rename-combine-reducers.js
664 -rw-rw-r-- ./bin/codemods/src/single-tree-rendering.js
664 -rw-rw-r-- ./bin/codemods/src/sort-imports.js
664 -rw-rw-r-- ./bin/eslint-branch.js
664 -rw-rw-r-- ./bin/get-circle-string-artifact-url
664 -rw-rw-r-- ./bin/install-if-deps-outdated.js
664 -rw-rw-r-- ./bin/install-if-no-packages.js
664 -rw-rw-r-- ./bin/integration/get-circle-string-artifact-url.js
664 -rw-rw-r-- ./bin/pre-commit-hook.js
664 -rw-rw-r-- ./bin/pre-push-hook.js
664 -rw-rw-r-- ./bin/process-extensions-scss.js
664 -rw-rw-r-- ./bin/reformat-files.js
664 -rw-rw-r-- ./bin/rm.js
664 -rw-rw-r-- ./bin/trim-shrinkwrap.js
664 -rw-rw-r-- ./bin/utils/should-format.js
664 -rw-rw-r-- ./bin/welcome.js
775 drwxrwxr-x ./bin
775 drwxrwxr-x ./bin/codemods
775 drwxrwxr-x ./bin/codemods/src
775 drwxrwxr-x ./bin/integration
775 drwxrwxr-x ./bin/utils
775 -rwxrwxr-x ./bin/build-metadata.js
775 -rwxrwxr-x ./bin/codemods/run.js
775 -rwxrwxr-x ./bin/run-integration
775 -rwxrwxr-x ./bin/runmods.sh
775 -rwxrwxr-x ./bin/update-dependency

chmod a+x ./bin/analyze-css.js
chmod a+x ./bin/eslint-branch.js
chmod a+x ./bin/get-circle-string-artifact-url
chmod a+x ./bin/install-if-deps-outdated.js
chmod a+x ./bin/pre-commit-hook.js
chmod a+x ./bin/pre-push-hook.js
chmod a+x ./bin/process-extensions-scss.js
chmod a+x ./bin/rm.js
chmod a+x ./bin/trim-shrinkwrap.js
chmod a+x ./bin/welcome.js

find ./bin -printf "%m %M %p\n" | sort

664 -rw-rw-r-- ./bin/codemods/README.md
664 -rw-rw-r-- ./bin/codemods/src/assign-component-to-displayname-variable.js
664 -rw-rw-r-- ./bin/codemods/src/combine-reducer-with-persistence.js
664 -rw-rw-r-- ./bin/codemods/src/combine-state-utils-imports.js
664 -rw-rw-r-- ./bin/codemods/src/config.js
664 -rw-rw-r-- ./bin/codemods/src/i18n-mixin-to-localize.js
664 -rw-rw-r-- ./bin/codemods/src/merge-lodash-imports.js
664 -rw-rw-r-- ./bin/codemods/src/modular-lodash-no-more.js
664 -rw-rw-r-- ./bin/codemods/src/modular-lodash-requires-no-more.js
664 -rw-rw-r-- ./bin/codemods/src/remove-linked-state-mixin.js
664 -rw-rw-r-- ./bin/codemods/src/rename-combine-reducers.js
664 -rw-rw-r-- ./bin/codemods/src/single-tree-rendering.js
664 -rw-rw-r-- ./bin/codemods/src/sort-imports.js
664 -rw-rw-r-- ./bin/install-if-no-packages.js
664 -rw-rw-r-- ./bin/integration/get-circle-string-artifact-url.js
664 -rw-rw-r-- ./bin/reformat-files.js
664 -rw-rw-r-- ./bin/utils/should-format.js
775 drwxrwxr-x ./bin
775 drwxrwxr-x ./bin/codemods
775 drwxrwxr-x ./bin/codemods/src
775 drwxrwxr-x ./bin/integration
775 drwxrwxr-x ./bin/utils
775 -rwxrwxr-x ./bin/analyze-css.js
775 -rwxrwxr-x ./bin/build-metadata.js
775 -rwxrwxr-x ./bin/codemods/run.js
775 -rwxrwxr-x ./bin/eslint-branch.js
775 -rwxrwxr-x ./bin/get-circle-string-artifact-url
775 -rwxrwxr-x ./bin/install-if-deps-outdated.js
775 -rwxrwxr-x ./bin/pre-commit-hook.js
775 -rwxrwxr-x ./bin/pre-push-hook.js
775 -rwxrwxr-x ./bin/process-extensions-scss.js
775 -rwxrwxr-x ./bin/rm.js
775 -rwxrwxr-x ./bin/run-integration
775 -rwxrwxr-x ./bin/runmods.sh
775 -rwxrwxr-x ./bin/trim-shrinkwrap.js
775 -rwxrwxr-x ./bin/update-dependency
775 -rwxrwxr-x ./bin/welcome.js
```

##### Image files

```
find ./public/images/stats/tasks -printf "%m %M %p\n" | sort

664 -rw-rw-r-- ./public/images/stats/tasks/ready-to-share.svg
775 drwxrwxr-x ./public/images/stats/tasks
775 -rwxrwxr-x ./public/images/stats/tasks/about.svg
775 -rwxrwxr-x ./public/images/stats/tasks/contact.svg
775 -rwxrwxr-x ./public/images/stats/tasks/create-tagline.svg
775 -rwxrwxr-x ./public/images/stats/tasks/domains.svg
775 -rwxrwxr-x ./public/images/stats/tasks/first-post.svg
775 -rwxrwxr-x ./public/images/stats/tasks/personalize-your-site.svg
775 -rwxrwxr-x ./public/images/stats/tasks/social-links.svg
775 -rwxrwxr-x ./public/images/stats/tasks/upload-icon.svg
775 -rwxrwxr-x ./public/images/stats/tasks/upload-profile-picture.svg

chmod a-x ./public/images/stats/tasks/about.svg
chmod a-x ./public/images/stats/tasks/contact.svg
chmod a-x ./public/images/stats/tasks/create-tagline.svg
chmod a-x ./public/images/stats/tasks/domains.svg
chmod a-x ./public/images/stats/tasks/first-post.svg
chmod a-x ./public/images/stats/tasks/personalize-your-site.svg
chmod a-x ./public/images/stats/tasks/social-links.svg
chmod a-x ./public/images/stats/tasks/upload-icon.svg
chmod a-x ./public/images/stats/tasks/upload-profile-picture.svg

find ./public/images/stats/tasks -printf "%m %M %p\n" | sort

664 -rw-rw-r-- ./public/images/stats/tasks/about.svg
664 -rw-rw-r-- ./public/images/stats/tasks/contact.svg
664 -rw-rw-r-- ./public/images/stats/tasks/create-tagline.svg
664 -rw-rw-r-- ./public/images/stats/tasks/domains.svg
664 -rw-rw-r-- ./public/images/stats/tasks/first-post.svg
664 -rw-rw-r-- ./public/images/stats/tasks/personalize-your-site.svg
664 -rw-rw-r-- ./public/images/stats/tasks/ready-to-share.svg
664 -rw-rw-r-- ./public/images/stats/tasks/social-links.svg
664 -rw-rw-r-- ./public/images/stats/tasks/upload-icon.svg
664 -rw-rw-r-- ./public/images/stats/tasks/upload-profile-picture.svg
775 drwxrwxr-x ./public/images/stats/tasks
```

#### Testing instructions

1. Run `git checkout fix/file-permissions` and start your server
2. Assert that the server start without errors, or warnings (apart the usual ones)
3. Assert that the [`Reader` page](http://calypso.localhost:3000/) and other pages work as before

### CODE REVIEW

**Comment by hafizrahman** [comment]
Didn't see any obvious breakages with this change.

**Comment by Tug** [comment]
Why 775 instead of 755? It should not matter much as a git repository is not shared with multiple users by default unless you change the `core.sharedRepository` config.
It should probably be 755 for consistency though

**Comment by stephanethomas** [comment]
I've rebased, and updated this pull request to fix permissions for a set of new images.

> Why 775 instead of 755?

I set permissions to be consistent with other files. I believe file masking may be at work here though, and what appears to be `775` in my environment was recorded as `755` by GitHub - see changes in the [`Files changed` tab](https://github.com/Automattic/wp-calypso/pull/19664/files).

**Comment by Tug** [comment]
🚢

**Pull request merged**
