### PR TITLE
Blogger Flow: Update copy on starting-point screen

### PR DESCRIPTION
**Pull request by roo2**
Update copy in accordance with https://github.com/Automattic/wp-calypso/issues/57582

**Before:**
"Nice job! Lastly, pick a starting point."
**After:**
"Nice job! Now it’s time to get creative."
**Screenshots**
Screen Shot 2021-11-03 at 9 29 31 am
Screen Shot 2021-11-03 at 9 29 19 am
Screen Shot 2021-11-03 at 9 29 04 am

### CODE REVIEW

**Comment by roo2** [comment]
I asked autumn to confirm it's ok without the explicit text wrapping on the different screens https://github.com/Automattic/wp-calypso/issues/57582#issuecomment-958417415

**Review by arthur791004 — APPROVED** [review]
As https://github.com/Automattic/wp-calypso/issues/57582#issuecomment-961417142 mentioned, we can come back to deal with the line break.

**Comment by roo2** [comment]
Added the break after "it's" as suggested here https://github.com/Automattic/wp-calypso/issues/57582#issuecomment-958426304

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/6962735

Thank you @roo2 for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/6962735).

**Pull request merged**
