### PR TITLE
Reader: taking a stab at feed searching

### PR DESCRIPTION
**Pull request by samouri**
thank you to prior art located at: https://github.com/Automattic/wp-calypso/pull/7795

This PR creates a placeholder test UI to call the new WPCOM API for feed search and followed search.

TODO:
- [ ] put behind feature flag
- [ ] unit tests for redux actions & reducer
- [ ] make look more like mock
- [ ] move subscriptions store to redux?
- [x] update api to have a better response
- [ ] denormalize feed-search so that it only contains ids and the search adds feeds to `feeds` store

mock:
manage-refresh-0-default

### CODE REVIEW

**Comment by gibrown** [comment]
Some funniness with the search 'ny':

https://cloudup.com/cbFYVgm0eHm

Also some display problems with ampersands are visible here.

**Comment by gibrown** [comment]
Would help for testing to add a follow count for each result and a clickable link to the feed.

**Comment by samouri** [comment]
Thanks for checking it out @gibrown!
> Would help for testing to add a follow count for each result and a clickable link to the feed.
great idea! I'll try to make those changes -- albeit may not get to it until after reduxifications

**Comment by gibrown** [comment]
Yep that's fine. Just thought I would put in some thoughts as I had them and started circling back to this project.

**Comment by samouri** [comment]
unpunting and picking back up!

**Comment by samouri** [comment]
I'm going to reimplement the feesearching in the data-layer now

**Comment by samouri** [comment]
Closing now that almost all of the code has been rewritten and the project is being tracked in this issue: https://github.com/Automattic/wp-calypso/issues/11549

**Pull request closed without merging**
