### PR TITLE
Stats: Flesh out highlight card components

### PR DESCRIPTION
**Pull request by jsnmoon**
Related to #93973. I apologize for the large LOC; ~half of it is from Storybook additions/edits.

## Proposed Changes

Before|After
-|-
image|image
image|image

- Adds tooltip functionality to `<CountCard>`.
- Replaced usage of `<CountComparisonCard>` with `<CountCard>` where no comparisons were taking place.
- Refactored number formatting manipulation into a dedicated library module.
- Standardized percentage formatting using `Intl.NumberFormat`.
- Updated stories for each highlight card component, which unfortunately bloated the LOC for this PR.

## Why are these changes being made?

These changes make it more obvious when CountCards and CountComparisonCards should be used. If we want to showcase a single value, CountCards should be used; if we want to visualize how a value has changed over time, it should be CountComparisonCards.

These changes also standardize how we perform international number formatting in highlight card components.

## Testing Instructions

* Open the live branch for this change and ensure that the highlight cards render and behave as expected on the following pages for **desktop and mobile viewports**:
    * Traffic dashboard (`/stats/day/example.com`).
    * Insights dashboard (`/stats/insights/example.com`).
    * Subscribers dashboard (`/stats/subscribers/example.com`).
* Open Storybook and ensure that each highlight card component is easily explorable.

## Pre-merge Checklist

- [x] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [x] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [x] Have you checked for TypeScript, React or other console errors?
- [x] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [x] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [x] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Comment by kangzj** [comment]
Thanks for centralizing the formatting logic and creating all the stories @jsnmoon. We really appreciate it!

All look good, except that it broke the highlight cards on the Ads page:

Screenshot 2024-09-05 at 9 38 38 AM

**Comment by jsnmoon** [comment]
Good catch. Fixed!

image

**Review by kangzj — APPROVED** [review]
Thanks for fixing this @jsnmoon ! Works well and looks good!

So nice to have the refactoring and the few new stories!

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/16650308

Some locales (Hebrew, Japanese) have been temporarily machine-translated due to translator availability. All other translations are usually ready within a few days. Untranslated and machine-translated strings will be sent for translation next Monday and are expected to be completed by the following Friday.

Thank you @jsnmoon for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/16650308).

**Pull request merged**
