### PR TITLE
Signup: Remove all verticals theme A/B test.

### PR DESCRIPTION
**Pull request by alaczek**
The test was enabled in #5962, and should be removed by July 15, 2016.

cc @kwight 

Test live: https://calypso.live/?branch=remove/vertical-themes-test

### CODE REVIEW

**Comment by kwight** [comment]
The themes lib code should mostly stay; just remove the pieces that are test-specific (like `abtest()` and its imports). We want to keep the functionality like `getUnusedThemes()`.

**Comment by alaczek** [comment]
I went over and tested the changes, but we're still gonna need a review before merging, right @kwight?

**Comment by sirbrillig** [comment]
LGTM

**Comment by sirbrillig** [comment]
Probably should rebase to squash these two commits, though!

**Comment by sirbrillig** [comment]
g2g

**Pull request merged**
