### PR TITLE
Welcome Tour: Add keyboard navigation via left/right arrow keys & Esc

### LINKED ISSUE #55634: Editor Welcome Tour: Enhance keyboard navigation via arrow keys and Esc
### What
We want to make the Welcome Tour more accessible by allowing navigation via left/right keyboard keys and minimizing via Esc. We are improving navigation via tab and space/enter keys in a separate issue. This is in addition.

### Why

Navigating the tour contents feels cumbersome and can be enhanced by allowing navigation via arrow keys and closing/minimizing via Esc.

### How

A few details after some initial explorations:

- If the tour is focused, then navigation happens within the tour and nothing else reacts to keyboard events.
- It might be the case that certain things will close when we focus the tour (like block inserters, as [noted already in the code](https://github.com/Automattic/wp-calypso/blob/trunk/apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nux/src/welcome-tour/tour-launch.js#L75-L79)), but we can outline those in an issue and attempt to address them as potential “core” issues if they are in fact issues.
- If the tour loses focus, then obviously no logic within the tour should react to keyboard events. The editor takes precedence.

### Checklist

- [ ] Navigation between slides is possible with the keyboard left/right arrow keys
- [ ] Minimize it using ESC key

### PR DESCRIPTION
**Pull request by chriskmnds**
#### Changes proposed in this Pull Request

Enables navigation in the Welcome Tour via left/right keys, and closing on Esc. Addresses #55634

Specs as in the issue:

- If the welcome tour is focused either by clicking on tabbing into it:
    - left/right arrow keys progress the slides
    - Esc minimizes the tour
- Certain elements in the editor may close when they lose focus e.g. block inserter dropdowns. This is noted in the issue and we may attempt to address as potential “core” issues instead.
- If the tour loses focus, then no navigation happens via keyboard events. The editor takes precedence and the tour remains open.

Kapture 2021-09-09 at 15 16 17

#### Testing instructions

* Go to the editor, open the sidebar, and from there click on "Welcome Guide".
* Click or tab into the panel that opens to move the focus to it (anywhere should work).
* You can now navigate the slides using the left/right arrow keys and minimize using the Esc key.
* Expanding the tour again should enable navigation without additional clicking.

#### Known issues

* When initially opening the Welcome Guide via the sidebar OR by reloading the page with the tour open, the tour does not receive focus, hence it does not respond to keydown events. You will need to click or tab into anywhere in the tour to enable navigation via the keyboard. This is addressed in a separate issue: #55635
* The awkward navigation via tabbing + space/enter keys is noted/addressed in another issue: #56054

Fixes #55634

Props to @razvanpapadopol for the work/discussion/testing in the background!

### CODE REVIEW

**Comment by chriskmnds** [comment]
@poligilad-auto @razvanpapadopol Should the Esc key close the tour instead? 🤔 

But I guess we can merge whatever functionality we have here and do follow-ups, so we all get a chance to review live.

**Comment by poligilad-auto** [comment]
Hey @chriskmnds @razvanpapadopol how about if when you are focused on the tour the _minimize_ and _close_ button remain open and then you can tab between all the interactive elements on the page?

I was just trying out how to close our "notice" component and that's how it works there, I just tab to it and press enter.

https://user-images.githubusercontent.com/83961704/132814651-22376e73-3593-4371-a635-03c3325f9410.mov

**Comment by chriskmnds** [comment]
> how about if when you are focused on the tour the minimize and close button remain open and then you can tab between all the interactive elements on the page?

Thanks @poligilad-auto ! That makes sense. We deployed a fix recently that I think works like you describe. So when you "tab" into the tour, the controls are visible and can walk through them via the tab key. See gif below - is this more or less what you are referring to? We plan to optimize that a bit too in a [follow up](https://github.com/Automattic/wp-calypso/issues/56054). :-)

Kapture 2021-09-10 at 12 26 30

**Comment by poligilad-auto** [comment]
> So when you "tab" into the tour, the controls are visible and can walk through them via the tab key. See gif below - is this more or less what you are referring to? 

Yes! Perfect @chriskmnds 

> Should the Esc key close the tour instead? 🤔

So this would be an extra functionality? I would say yes, if we have other places that behave that way. Maybe we have some modal views that we can check?

**Comment by chriskmnds** [comment]
> So this would be an extra functionality? I would say yes, if we have other places that behave that way. Maybe we have some modal views that we can check?

I think in general Esc "closes things out" (?). That's what happens with the help modal and the sidebar in the editor too. The tour currently does not react to Esc (nor close nor minimize). With this PR Esc will **minimize** the tour.

The only problem I see with closing the tour on Esc is it gives a quick "opt out" path, and then it may be hard to get back into the tour with the activator hidden inside the sidebar. So minimizing kinda makes sense here to avoid losing it alltogether? 

We could also explore a "minimize the tour on Esc" (as in this PR) and "close the tour on Esc when minimized" (in a follow up). The downside with that is we would introduce a bit of inconsistency in how Esc reacts in this context. Another option would be to map another key for minimizing the tour (if we want keyboard access for that) - feels a bit bloated maybe.

^ sorry if confusing. We can merge and do all of these in a follow once you get a chance to play with it on your end.

**Comment by poligilad-auto** [comment]
Thanks for explaining @chriskmnds. Clear now.
Based on your input above, I think it's fine to use Esc to minimize for now. I'll check out how it works once it's live.

**Review by poligilad-auto — APPROVED** [review]

**Comment by chriskmnds** [comment]
> Based on your input above, I think it's fine to use Esc to minimize for now. I'll check out how it works once it's live.

Perfect. I'll ping you when deployed and you can test away when around. then we can do follow-ups from there :-)

**Pull request merged**
