### PR TITLE
Help Center: move odie logic into component

### PR DESCRIPTION
**Pull request by arcangelini**
## Proposed Changes

* Move all Odie logic into `<HelpCenterOdie />`
* Rename all `elegible` to `eligible`

## Why are these changes being made?

The main routing component for the Help Center `HelpCenterContent` contains a significant amount of logic and functions that are only used to connect with Odie. There is currently already a Help Center component to display the Odie client. As the Help Center continues to grow I feel it may be best to keep logic organized to prevent technical debt and preserve readability.

## Testing Instructions

1. Open Calypso live link
2. Open Help Center and go to Wapuu.
3. Check for regressions.

### CODE REVIEW

**Review by renancarvalho — APPROVED** [review]
Tested and works fine!
Thank you for organizing it a bit more 👍 

🚢

**Comment by AllTerrainDeveloper** [comment]
I would recommend do a testing around the double renders. Last issue was around the widget being rendered sometimes and depending on browser/device to being render indefinitely causing the user to not being able to reach either the chat or user support.

I'm AFK but please be mindful with rendering issues. 

Assert that the auto scroll behaviour keeps working nicely (mostly smooth scroll without any quick stop/resume, which is the most visible thing when we have many renders in place because if it renders while auto scrolling we can see it that glitch)

**Comment by arcangelini** [comment]
Thanks for peeking while on your AFK @AllTerrainDeveloper 🌟🌟🌟🌟🌟 

There aren't any changes to the logic I just moved where it is placed so hopefully there aren't any issues. I will double and triple check Wapuu just to be safe though 😄 . Let me know if you would prefer us wait to merge until you are back 👍

**Comment by AllTerrainDeveloper** [comment]
I trust your testing and criteria 🙂 feel free to merge once you think it's ready

**Comment by arcangelini** [comment]
Gave it another round of testing in Calypso and WP-ADMIN as a paid and free user and everything seems to work properly. I am going to send it. If anything seems to be off, let me know and I will fix it 🪖

**Pull request merged**
