### PR TITLE
Hosting Trial Requiring CC: Add checkout step to hosting trial

### PR DESCRIPTION
**Pull request by vykes-mac**
Related to https://github.com/Automattic/dotcom-forge/issues/6577

## Proposed Changes

This PR adds checkout step to the hosting trial flow. 

**Note**
Migrations trial is not yet included

* Adds checkout page
* Remove automatic atomic transfer for trial sites.

image

## Testing Instructions

Pre-requisites
Apply diff D145625-code ( this remove the "assignment payment later" option)
Apply diff D145807-code ( set trial expiration, update user attribute, verify email)
Also use store sandbox and test cards that can be found PCYsg-IA-p2 

* go to `/setup/new-hosted-site`
* verify select Free Trial will take you to checkout page and requires credit card to proceed
* Enter test credit card and proceed to checkout
* Verify site is created with the Creator Trial for 7 days

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Review by p-jackson — COMMENTED** [review]
`transferring-hosted-site-flow.ts` is also referenced in `registered-flows.ts` so that needs to be removed too.

I know it's not in review yet but I thought I'd give it a wee try. The plans step failed to load for me.

> Remove automatic atomic transfer for trial sites.

I'd expect that this still happens. The code on the backend that does the transfer would still detect that the hosting plan has been activated and initiate the transfer.
Does that mean we still want to show the loading screen until atomic transfer completes? It's just that it would need to navigate to it as the post-checkout screen.

**Comment by vykes-mac** [comment]
> The plans step failed to load for me.

This is probably because `transferring-hosted-site-flow.ts` wasn't removed from `registered-flows.ts`

> I'd expect that this still happens. The code on the backend that does the transfer would still detect that the hosting plan has been activated and initiate the transfer.

The transfer happens when the checkout completes. What I mean here is to remove the hook we added that transfer to atomic, this was necessary because we had removed the checkout step.

**Review by p-jackson — COMMENTED** [review]
I haven't tested with the D145807-code yet, but the PR is looking good to me now 👍

Once I made it through checkout the site was using the correct plan and I'd been transferred to atomic as expected. (I couldn't install a plugin, but I believe that's because I used the store sandbox and fake credit card, which the atomic site isn't aware of and refused the plugin install)

I'll test again tomorrow using D145807-code.

@vykes-mac just double check my reasoning: once D145625-code and D145807-code are deployed we'll be good to merge this PR? It's not a problem that the migration trial doesn't require the credit card for now?

**Review by paulopmt1 — COMMENTED** [review]
It's working as expected @vykes-mac! When starting a trial, I was redirected to the checkout and couldn't advance without adding a credit card.

Questions:

- Is it expected to create a simple site even before completing the checkout process?
- Should we also remove [TRANSFERRING_HOSTED_SITE_FLOW](https://github.com/Automattic/wp-calypso/blob/add/include-checkout-step-hosting-trial/packages/onboarding/src/utils/flows.ts#L7) and [isTransferringHostedSiteCreationFlow](https://github.com/Automattic/wp-calypso/blob/add/include-checkout-step-hosting-trial/packages/onboarding/src/utils/flows.ts#L93) usages?

**Comment by vykes-mac** [comment]
Thanks @paulopmt1 

> Is it expected to create a simple site even before completing the checkout process?

Yeah that's the normal process even without the trial flow. A simple site is created before and that site is added to the checkout step

> Should we also remove [TRANSFERRING_HOSTED_SITE_FLOW](https://github.com/Automattic/wp-calypso/blob/add/include-checkout-step-hosting-trial/packages/onboarding/src/utils/flows.ts#L7) and [isTransferringHostedSiteCreationFlow](https://github.com/Automattic/wp-calypso/blob/add/include-checkout-step-hosting-trial/packages/onboarding/src/utils/flows.ts#L93) usages?

Yeah these should be removed

**Comment by vykes-mac** [comment]
@p-jackson 

> @vykes-mac just double check my reasoning: once [D145625-code](https://href.li/?https://code.a8c.com/D145625) and [D145807-code](https://href.li/?https://code.a8c.com/D145807) are deployed we'll be good to merge this PR? It's not a problem that the migration trial doesn't require the credit card for now?

Migrations get's way less traffic than hosting. I think we can merge this then adopt the changes to the migrations trials

**Comment by vykes-mac** [comment]
@p-jackson I've tested this with a real card and everything seem to work. Give it a another shot and see, If all looks well we can deploy diffs and merge

**Comment by mpkelly** [comment]
I tested the following successfully at `/setup/new-hosted-site`:

- Must confirm email to proceed
- Only one trial per account
- Must provide a credit card to complete checkout
- Can buy a full Creator plan instead of a trial
- Empty cart with trial and try again with a second site - still forces credit card

I thought I had found an issue but remembered I need to use `--nobranch` 😊 . 

Maybe we should mention that the user will never be billed somewhere on the flow?

**Comment by p-jackson** [comment]
> Maybe we should mention that the user will never be billed somewhere on the flow?

@mpkelly I've added another issue to make sure we discuss that. https://github.com/Automattic/dotcom-forge/issues/6637

**Review by p-jackson — APPROVED** [review]

**Comment by p-jackson** [comment]
I've reinstate the `transferring-hosted-site` flow. Removing the flow was an unnecessary change to the entrepreneur behaviour.
Because the atomic transfer begins as soon as checkout is complete, it's best to show a loading indicator while this happens rather than going straight to the dashboard. Some screens (e.g. Hosting Config) don't work properly until transfer is complete.

**Pull request merged**
