### PR TITLE
Post Editor: HTML editor dialogs height fix

### LINKED ISSUE #16324: Different dialog layout for link
Link editation dialog layout is different when switched into HTML mode (buttons are not fixed to bottom)
Lowering height of `.post-selector__results` would be sufficient.

#### What I expected
screen shot 2017-07-18 at 13 30 08

#### What happened instead
screen shot 2017-07-18 at 13 30 28

#### Browser / OS version
Google Chrome 59.0.3071.115

#### Screenshot / Video
https://youtu.be/RN93u531FOc

#### Context / Source
#user-report

### PR DESCRIPTION
**Pull request by Avizc**
Fix #16324
Remove height-related visual inconsistencies on editor dialogs between Visual and HTML mode.

---

This is currently in-progress for issue #16324 Different dialog layout for link. I believe the height being set to 24vh of post-selector__results will fix the issue as that's the height set for the Visual Editor. However I am having issues with npm start so this is still in-progress until I can test it out to make sure.

This is my first time doing this so I hope this is the correct way to do this! I'm hoping once I get the height done to fix the rest of the modal since the proportions are all different from the Visual Editor.

### CODE REVIEW

**Comment by Avizc** [comment]
Oh golly ahhh it works! So sorry it took me a while, for some reason I was having issues getting the localhost up with npm start. Uninstalled, reinstalled, and everything and it finally magically worked! Though of course once I shut down the server and tried to reopen it later it didn't work uh...

That said here is the screenshot showing that it works!

Alt text

Here it is without the fix on the live site right now:

Alt text

Looks like someone already fixed the sizing issue on the sides. Huzzah!

**Comment by mikaelz** [comment]
Works for me.
ss_2017-07-23-18-24-40

**Comment by Copons** [comment]
Hi @Avizc!
Author of the HTML Toolbar chiming in: awesome job catching this issue! 🙂 

I gave a quick look at the differences between the Visual and HTML versions of the dialog, and I realized that, when developing, I've totally failed to notice a lot of quirks.

Your `height: 24vh;` is one of those, but there are at least two other things that I believe would fit right into your PR, all being somewhat related to the height, if you don't mind updating it.

1. The dialog container has an unnecessary vertical scrollbar.
It should be enough to remove:
`.editor-html-toolbar__dialog { overflow-y: auto; }`
But, of course, please give it a proper test on (very) small window sizes.

2. This is not really a bug, as much as an inconsistency. Visual-side, `.form-fieldset`s have a `margin-bottom: 8px`, while HTML-side they keep their original `margin-bottom: 20px`.
Considering the function of the dialog, I'd rather go with the smallest one, e.g.:
`.editor-html-toolbar__dialog .form-fieldset { margin-bottom: 8px; }`

I know there are other differences going on, and maybe I missed some that could be relevant to this PR.
Please feel free to add them in. 🙂

**Comment by Avizc** [comment]
Oh gosh whoa, hi @Copons! That's really darling oh gosh, thank you so much for the feedback!

I did see quite a few other differences and I realised a huge part of that is that the HTML-side has the `.dialog__content` and `.dialog__action-buttons` in the React Modal with` .editor-html-toolbar__dialog{overflow-y:auto }` but the Visual-side doesn't have that `overflow-y` at all.

If I remove it it causes a slew of new issues for smaller screens where I'm sure with a media-query that could be maybe fixed to re-include that back in? I also did check out what happens on the Visual-side too at that size and it's the same issue essentially. I wasn't sure if that was in the scope of this PR so I left it alone for now at least!

Removing the `overflow-y` on the `editor-html-tool` has its pros and cons and I wasn't sure which was better because the Visual-side is broken on this size window because there's no over-flow in any shape or form. Here it was with the `overflow-y` on the HTML-side:

With overflow-y

And how it looked without it:

Removing overflow-y

I made it a separate commit in case it's better with it than without!

Updated the `.form-fieldset` with the margin to be consistent with the Visual-side at least huzzah. Do you have any suggestions on what to do from here? This is still my first time doing this so I'm really excited!

**Comment by Copons** [comment]
@Avizc Thanks for the update, it looks so much better now! 🙂 

> If I remove it it causes a slew of new issues for smaller screens where I'm sure with a media-query that could be maybe fixed to re-include that back in?

Can I ask you what issues are you seeing?
I gave your changes a quick test and it seemed to be working well.

I also tracked back to the reason for the `overflow-y`, and if I'm not mistaken, it was because, previously, the bottom buttons bar scrolled along the rest of the dialog (while now it's fixed there, and only the content of the dialog is scrollable).
Your second screenshot looks like the old behaviour, and it's possible that the fix was introduced after you opened this PR.

This is how I see the dialog on small heights (with your changes applied):
screen shot 2017-08-31 at 09 32 51

As you can see, the scrollbar stops above the buttons bar, which is fixed at the bottom.

If you don't mind, you could try applying these changes to a fresh copy of Calypso and check if you still see issues.

Thanks again for the update!

**Comment by Avizc** [comment]
@Copons Oh gosh thank you so much for the feedback eep!

> Can I ask you what issues are you seeing?
> I gave your changes a quick test and it seemed to be working well.

This is a bit odd for me but I'm not able to re-create the odd thing I saw happen yesterday. If I see it again I'll bring it up in an issue and see what I can do after but otherwise oh golly things aren't broken anymore.

> If you don't mind, you could try applying these changes to a fresh copy of Calypso and check if you still see issues.

That was definitely a mistake I made in testing it out, my changes are working now oh gosh.

Thank you for following up with me and verifying my changes, too!

**Comment by Copons** [comment]
Then LGTM and I'll ship it asap!

Really appreciate the fix! 🙂

**Pull request merged**
