### PR TITLE
Staging Sites: Display a module when viewing from the Staging Site

### PR DESCRIPTION
**Pull request by danielbachhuber**
Fixes https://github.com/Automattic/dotcom-forge/issues/1929

## Proposed Changes

Adds a module to 'Hosting Configuration to link the user back to their production site:

image

## Testing Instructions

1. Create a new Business site and take it Atomic.
2. Navigate to 'Hosting Configuration' and verify the normal 'Staging site' module appears as expected.
3. Create a staging site.
4. Navigate to 'Hosting Configuration' for the staging site.
5. Verify this new module appears as expected.

### CODE REVIEW

**Comment by danielbachhuber** [comment]
@Automattic/yolo I'd love to hear your thoughts on what additional refactoring might be worthwhile on this PR.

**Comment by javierarce** [comment]
"Your staging site's production site is available at" is a bit convoluted, I'd simply say "The production site is available at:" 

image

**Comment by danielbachhuber** [comment]
> "Your staging site's production site is available at" is a bit convoluted, I'd simply say "The production site is available at:"

@javierarce Thanks! Updated with e63f8521683a2822010489c7fdb0f12b46df1224

**Review by wojtekn — APPROVED** [review]
I think this looks good and works well. 

I've noticed one thing related to navigation - when I click "Manage production site", it loads the Hosting Configuration view for a production site, and after one or two seconds, it redirects to production Home.

It looks like this behavior is not introduced in this PR, but is probably something internal to Calypso. It would make sense to tackle it under a separate ticket, though. Or maybe, as a quick fix, we could navigate to Hosting Configuration on the related production/staging site?

**Comment by danielbachhuber** [comment]
@wojtekn Great suggestion! Opened a pull request: https://github.com/Automattic/wp-calypso/pull/75580

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/7920572

Thank you @danielbachhuber for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/7920572).

**Pull request merged**
