### PR TITLE
Reader: Delete Flux Implementation of Streams

### PR DESCRIPTION
**Pull request by samouri**
Deletes dead flux code following reduxification in https://github.com/Automattic/wp-calypso/pull/22814  

`( ͡° ͜ʖ ͡°)`

### CODE REVIEW

**Review by blowery — APPROVED** [review]
LGTM. Appears to all be dead code.

**Comment by bluefuton** [comment]
Two thousand lines! Nice. 🎉

**Comment by samouri** [comment]
ICFY confirms: http://iscalypsofastyet.com/branch?branch=delete/reader-flux-streams
```
Commit: a6cca68fe3095258d29e3eed461934a2986f80b8
Author: samouri
At: 2018-05-10T17:03:26Z
Message: Reader: Delete Flux Implementation of Streams
Delta:
no changes in production JS
```

**Comment by apeatling** [comment]
🎉

**Pull request merged**
