### PR TITLE
Anchor: Remove feature flag

### PR DESCRIPTION
**Pull request by andres-blanco**
Removes anchor feature flag. Should be merged after https://github.com/Automattic/wp-calypso/pull/77406.

## Testing Instructions

* Verify the flag is not used anywhere.

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

**Review by nelsonec87 — CHANGES_REQUESTED** [review]
It seems it is still used here: `client/landing/stepper/declarative-flow/internals/steps-repository/error-step/index.tsx:44`

**Review by nelsonec87 — CHANGES_REQUESTED** [review]
It seems it is still used here: `client/landing/stepper/declarative-flow/internals/steps-repository/error-step/index.tsx:44`

**Comment by andres-blanco** [comment]
> It seems it is still used here: `client/landing/stepper/declarative-flow/internals/steps-repository/error-step/index.tsx:44`

Yeah! It's removed in [this PR](https://github.com/Automattic/wp-calypso/pull/77406/files#diff-8df48fe5039ed2c91c808b49e44862374217477c489dd2e3f2211f135310c830L43) that should be merged before this one.

**Review by nelsonec87 — APPROVED** [review]
LGTM!

**Pull request merged**
