### PR TITLE
Adds a delayed-dispatch middleware to declaratively delay actions

### PR DESCRIPTION
**Pull request by dmsnell**
While working on the data layer I came across the need to delay the
dispatch of actions while automatically retrying failed network
requests (#14031). This made it hard to test because of the use of `setTimeout()`
in the network layer. The solution of course is more middleware; this
middleware is designed to take an action and a delay and then wait to
dispatch that action until the delay (in ms) has passed.

This enables testing of deferred actions.

Of course, I could have used fake timers in the tests for the network retry policy, but in this case those tests would be probabilistic since the delay in that code is random. By returning descriptions of the delays, however, I can test that the middleware does what it's supposed to do without needing to fake/mock the random delay for a retry.

### CODE REVIEW

**Comment by blowery** [comment]
How would you see canceling a delayed action?

**Comment by dmsnell** [comment]
> How would you see canceling a delayed action?

@blowery refresh the browser… in other words, with no different semantics than we currently have available via `setTimeout`

if we needed to do this we could add it in. would you see any reason to?

**Comment by blowery** [comment]
>  in other words, with no different semantics than we currently have available via setTimeout

setTimeout has a partner in clearTimeout, so this is only half the battle.

I'd see using it when I delay an action and then determine that that action is no longer necessary. Maybe a component unmounts, or the network comes back online.

**Comment by dmsnell** [comment]
> I'd see using it when I delay an action and then determine that that action is no longer necessary. Maybe a component unmounts, or the network comes back online.

@blowery how would you feel about deferring this to a time when we actually need it? how would you feel is a good way to go about it?

with Redux actions we're decoupling the deferred action so it's not like we're imperatively setting timeouts. would we envision dispatching a "CANCEL_ACTION" action? that doesn't make much sense to me and it doesn't feel clean.

in the examples you gave I see _when_ we might cancel but not _why_. a view over our existing code shows that most of our `clearTimeout()`s feel like UI local-state code and not global Redux-type actions.

**Comment by samouri** [comment]
@beaucollins might have some [feelings](https://github.com/beaucollins/redux-delayed-dispatch) on this ;)

**Comment by beaucollins** [comment]
I'm not sure if beaucollins/redux-delayed-dispatch solves your problem but it's been working for us well in both automattic/happychat and automattic/happychat-hud.

**Comment by dmsnell** [comment]
I could envision just importing @beaucollins' npm module. also I could add the clearing to this one, but something seems strange to me about dispatching an action also to cancel a deferred action.

any thoughts on moving forward with this? I would really like to have something for testing purposes because it's darn hard testing #14031 without it. example: the randomness in the deferral means I can't test the sequence of two or more retry attempts with certainty

**Comment by blowery** [comment]
+1 to just pulling in beau's lib

**Comment by dmsnell** [comment]
Closing in favor of the existing solution.

**Pull request closed without merging**
