### PR TITLE
Jetpack: When taking the checklist tour, pages don't scroll to show the help tooltips

### PR DESCRIPTION
**Pull request by monsieur-z**
#### Changes proposed in this Pull Request

In the _Plan > My Plan_ page, clicking any item in the _My Checklist_ pane will bring you to the corresponding settings page, but without scrolling to the tour help tooltip. If the tooltip appears below the screen fold line, it leaves users confused about what they should do.

#### Implementation notes

Note that this fix should solve the issue, though the guided tour (or at least the `Step` component) requires more attention, particularly to update its lifecycle.

I first tried to use `lib/scroll-into-view` (a wrapper for `Element.scrollIntoView` and `Element.scrollIntoViewIfNeeded`) as suggested in the code comments. It didn't work out as we'd need to apply it on the card/tooltip directly, which isn't in the flow layout (it's `fixed` positioned).

Here are the 3 parts of the actual fix:
- The init step in `JetpackSignInTour` required the `shouldScrollTo` prop to be passed.
- Even with the prop on, a condition in `UNSAFE_componentWillReceiveProps` prevented the scrolling from occuring. The code is now explicitly checking if the component has scrolled.
- Some properties accessed in `scrollIntoView` in `positioning.ts` weren't defined when the container happened to be the window.

#### Links

Fixes 1164141197617539-as-1165056995892059.

#### Issues

By testing, you might notice a couple of already existing issues:
* Once in the settings page, hitting the back button of the browser will bring you back to _My Plan_, and still show the card/tooltip. #42845
* Depending on the section, a minor scroll jump can happen.
* Not a bug per se: cards don't seem to be shown under a certain viewport width.

#### Testing instructions

* Make sure you have a Jetpack plan
* Make sure you haven't taken the tour yet
* Go to _Plan > My Plan_ page and check the _My Checklist_ section
* Click on the _Try it_ button in the Sign in section
Screen Shot 2020-05-26 at 9 15 29 AM

* You're redirected to the corresponding settings page, and shouldn't need to scroll down to see the tooltip (your viewport height shouldn't exceed 800px or so, in order for the scrolling to occur).
Screen Shot 2020-05-26 at 9 17 54 AM

### CODE REVIEW

**Comment by simison** [comment]
I tried to get something like this work here but didn't succeed: https://github.com/Automattic/wp-calypso/pull/33506 — hope it gives some pointers! Note the two undocumented features I added to docs.

**Comment by simison** [comment]
PS. Note that you can open Draft PRs in Github and save some CI cycles. ;-) https://github.blog/2019-02-14-introducing-draft-pull-requests/

**Comment by monsieur-z** [comment]
> #33506

Thanks! I'll take a look.

**Review by ChaosExAnima — COMMENTED** [review]
I'm still seeing an issue here. I tried to do the Site Accelerator tour, and it scrolled me too far down:

Screen Shot 2020-05-26 at 3 35 14 PM

**Comment by monsieur-z** [comment]
> I'm still seeing an issue here. I tried to do the Site Accelerator tour, and it scrolled me too far down:
> 
> Screen Shot 2020-05-26 at 3 35 14 PM

I haven't been able to reproduce what you're seeing. Which browser and resolution did you use @ChaosExAnima?

**Comment by ChaosExAnima** [comment]
@monsieur-z - I'm using Brave version 1.9.72 (Chromium: 81.0.4044.138) with my dev tools setting the screen size to 1024x600.

**Comment by monsieur-z** [comment]
Thanks for the additional testing @ChaosExAnima. This resolution revealed a missing condition.

It seems to scroll appropriately, though the little jump is a bit annoying. I believe it’s better than what’s on prod now, but the tour definitely requires further attention to be seamless.

**Comment by ChaosExAnima** [comment]
So it works now, but I am seeing some oddness still:
 
Screen Shot 2020-05-29 at 3 27 21 PM

Also noticed this, but I think it's unrelated to this PR:

Screen Shot 2020-05-29 at 3 27 04 PM

**Comment by monsieur-z** [comment]
What's your take on this PR @Automattic/team-calypso?

**Comment by mattgawarecki** [comment]
@jsnajdr I rolled a 1d7 on the members of @Automattic/team-calypso who aren't away on leave, and you were the lucky one :-) Do you all want to review this PR, or is it good to go without?

**Review by jsnajdr — APPROVED** [review]
Looks good :+1: 🙂

**Pull request merged**
