### PR TITLE
Theme Showcase: Remove dark upsell banner styles on theme showcase

### PR DESCRIPTION
**Pull request by sixhours**
#### Changes proposed in this Pull Request

This is more a suggestion I'm proposing than a done deal, so please speak up if you don't agree.

* Use a light color scheme to match other upsell nudges in the main content area of Calypso. The audit Jan worked on shows this is the only upsell that uses a dark color scheme.
* Also use a light color scheme on the single theme page upsell, and prevent widows on the button and copy for a cleaner look.

**Before**

Screen Shot 2020-03-20 at 9 52 40 AM
Screen Shot 2020-03-20 at 10 03 36 AM

**After**

Screen Shot 2020-03-20 at 9 58 04 AM
Screen Shot 2020-03-20 at 9 48 38 AM

#### Testing instructions

* Switch to this PR
* Navigate to `/themes` when logged in, with a site on a Free plan
* You'll see an upsell nudge when you click the Advanced Themes button at the bottom
* Click on one of the premium themes in the showcase; you'll see another upsell nudge at the top of the screen.

### CODE REVIEW

**Comment by sixhours** [comment]
Yes, it would be good to get another designer's take on this before I ship it. @jancavan thoughts?

**Comment by sixhours** [comment]
Also /cc @danhauk or @lcollette for thoughts :)

**Comment by danhauk** [comment]
The white looks good. What do you think about removing the `>` on the right side of the banner? It's a bit of a confusing pattern there to see a button next to a chevron. I'm not sure if clicking the whole card will take me to a different place than the button.

**Comment by sixhours** [comment]
That's a really good idea, I hadn't even noticed it but now that you mention it, it looks weird. 😬

**Comment by sixhours** [comment]
After thinking about it, I removed the CTA -- According to the audit, we don't use those most of the time for upsell nudges unless they're in the sidebar. The results:

Screen Shot 2020-03-23 at 4 15 58 PM

Screen Shot 2020-03-23 at 4 15 37 PM

**Comment by danhauk** [comment]
LGTM! Nice job referencing the audit and working to standardize the pattern.

**Pull request merged**
