### PR TITLE
newsletter flow: Use webp images

### PR DESCRIPTION
**Pull request by mreishus**
## Proposed Changes

* For the /setup/newsletter flow, convert pngs to webp, then change css to preferentially load the webps if supported
* We noticed downloading the almost 1MB newsletter-intro-bottom took up a large amount of time on the webpagetest for the newsletter flow
* I used `cwebp -q 85 $file -o $output` to convert
* ~~I did use fallback to png if webp is not supported - not sure if this is necessary?~~
  * https://caniuse.com/webp
  * https://caniuse.com/css-featurequeries  
  

| Filename                                  | Original Size (KB) | WebP Size (KB) | Reduction |
| ---------------------------------------- | ------------------ | -------------- | --------- |
| newsletter-intro-bottom-mobile.png       | 321.9              | 27.0          | 91%       |
| newsletter-intro-bottom.png              | 951.2              | 65.2          | 93%       |
| newsletter-processing-left-desktop.png   | 389.8              | 33.0          | 92%       |
| newsletter-processing-left.png           | 150.9              | 34.1          | 77%       |
| newsletter-processing-right-desktop.png  | 628.1              | 54.6          | 91%       |
| newsletter-processing-right.png          | 232.1              | 55.2          | 76%       |

## Testing Instructions

* Visit /setup/newsletter, make a site, and check that the images look OK and the webp versions are getting loaded

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

**Comment by simison** [comment]
Thank you! Great update. While adding new file formats, can you ensure the tip of "V" is spot on in the middle? See issue https://github.com/Automattic/wp-calypso/issues/75684

**Comment by mreishus** [comment]
Ah, okay - let me put this on hold and do this after #75684 / #76126 is completed; to ease the coordination and to make sure I don't inadvertently revert any changes.

**Comment by heavyweight** [comment]
@mreishus I just merged the related PR

After a rebase the command will need to be run again on:
- client/assets/images/onboarding/newsletter-intro-bottom.png
- client/assets/images/onboarding/newsletter-intro-bottom-mobile.png

**Comment by mreishus** [comment]
:heavy_check_mark: Refreshed with the latest images:

| Filename                                  | Original Size (KB) | WebP Size (KB) | Reduction |
| ---------------------------------------- | ------------------ | -------------- | --------- |
| newsletter-intro-bottom-mobile.png       | 321.9              | 27.0          | 91%       |
| newsletter-intro-bottom.png              | 951.2              | 65.2          | 93%       |
| newsletter-processing-left-desktop.png   | 389.8              | 33.0          | 92%       |
| newsletter-processing-left.png           | 150.9              | 34.1          | 77%       |
| newsletter-processing-right-desktop.png  | 628.1              | 54.6          | 91%       |
| newsletter-processing-right.png          | 232.1              | 55.2          | 76%       |

I used this script:
```
#!/bin/bash

for file in newsletter*png; do
  output="${file%.png}.webp"
  cwebp -q 85 "$file" -o "$output"
  echo "Converted $file to $output"
done
```

I've also removed the fallback images and CSS for simplicity's sake. [Browser support for webp](https://caniuse.com/webp) is very strong.

**Review by simison — APPROVED** [review]
Thank you for this!

Tested well on Firefox & Chrome, mobile & desktop resolutions worked as expected.

**Pull request merged**
