### PR TITLE
Framework: Replace i18nlint with custom ESLint rules

### PR DESCRIPTION
**Pull request by aduth**
Related: Automattic/eslint-plugin-wpcalypso#3

This pull request seeks to remove all traces of the the existing `server/i18nlint` tool, instead replacing it with custom ESLint rules.

As noted in the related pull request, benefits include:
- Simplifies linting
- Faster `pre-commit` checks, since `i18nlint` is no longer a separate script to run against each file
- CircleCI build failures on i18n lint errors
- More visibility to errors, including inline warning display when using ESLint editor plugin
- Autofix! Implemented for `i18n-ellipsis` rule

__Testing instructions:__

Verify that `make lint` passes.

/cc @gziolo , @deBhal , @blowery

### CODE REVIEW

**Comment by gziolo** [comment]
How do I use autofix feature? :D

**Comment by aduth** [comment]
>How do I use autofix feature? :D

Depending on how you call ESLint, you can pass the `--fix` command argument, e.g.

```bash
eslint client/path/to/broken/file.jsx --fix
```

**Comment by aduth** [comment]
Pushed 535cf2e and 0062cbb to remove two packages which were only depended upon directly by `i18nlint`: `source-map` and `babel-core`

**Comment by gziolo** [comment]
Just for the record. As we discussed on Slack. ESLint doesn't show errors for `this.translate` or `i18n.translate`.

**Comment by aduth** [comment]
@gziolo : Updated to a fixed version of `eslint-plugin-wpcalypso` (v1.1.3), and downgraded severity to warning, since there are a handful of existing cases which need to updated. Didn't want to include those changes here, but might be good for a follow-up pull request.

Since warnings are not reflected in output of `npm run lint`*, you'll need to manually change the severity from `1` to `2` for each of the `i18n` rules for the errors to be shown in the script output.

_*_ Because there are an astonishing 7232 warnings!

**Comment by blowery** [comment]
> * Because there are an astonishing 7232 warnings!

How many can `--fix` fix? :D

**Comment by aduth** [comment]
>How many can `--fix` fix? :wink: 

Probably some fixes not available in our defined version of ESLint, but the rules listed here with a wrench adjacent are fixable:

http://eslint.org/docs/rules/

**Comment by gziolo** [comment]
`make run` is broken because of removed babel-core dependency:

> ERROR in ./server/user-bootstrap/shared-utils.js
Module not found: Error: Cannot resolve module 'babel-runtime/helpers/interop-export-wildcard' in /Users/gziolo/PhpstormProjects/wp-calypso/server/user-bootstrap
resolve module babel-runtime/helpers/interop-export-wildcard in /Users/gziolo/PhpstormProjects/wp-calypso/server/user-bootstrap

**Comment by gziolo** [comment]
I tested all rules. All of them work according to the specification. Also `--fix` flag works properly. It looks like we only need to resolve `make run` issue :)

We can add more logic in another PR related to placeholders. The following code passes checks at the moment:
```js
translate( ' %(unknown)s ', {
	args: {
		name: 'World'
	}
}
```
There are 3 more checks possible here:
- we don't check if all placeholders are specified in `args` property
- we don't check if there are obsolete placeholders in `args` property
- we could trim translate string before applying `wpcalypso/i18n-no-placeholders-only` rule

**Comment by aduth** [comment]
@gziolo : I backed out the removal of `babel-core`. I assume this was an issue of it being a peer dependency of other dependencies. I did a quick scan of the modules directory for `source-map` peer dependencies (the other module removed here), and could not find any.

I like the idea of those rule enhancements. I'll plan to create issues in the `eslint-plugin-wpcalypso` repository later today.

**Comment by gziolo** [comment]
> I like the idea of those rule enhancements. I'll plan to create issues in the eslint-plugin-wpcalypso repository later today.

Please create also issue which prevents `.skip` and `.only` in Mocha tests. I pushed branch with `.only` modification :P Fortunately it was discovered during review ;)

**Comment by gziolo** [comment]
It works now properly :shipit:

**Comment by blowery** [comment]
I think I just busted this with https://github.com/Automattic/wp-calypso/pull/3856. I can rebase and fix.

**Comment by blowery** [comment]
Rebased and force pushed to pick up changes in #3856

**Comment by blowery** [comment]
screenshot

:two_hearts:

**Comment by aduth** [comment]
>Please create also issue which prevents `.skip` and `.only` in Mocha tests. I pushed branch with `.only` modification :P

You're not the only one to fall victim to this :wink: https://github.com/Automattic/wp-calypso/pull/3575#discussion_r54196387

**Comment by aduth** [comment]
Tracking ESLint rule enhancement for ensuring number of placeholders match arguments at Automattic/eslint-plugin-wpcalypso#4 .

**Pull request merged**
