### PR TITLE
Starter Page Templates: fix preview style override specificity

### LINKED ISSUE #38884: Template preview content expanding past preview frame (and sometimes too close to the frame).
Template preview content is expanding beyond the preview frame or right up to the edge of the frame and looks either "very broken" or "broken" in Chrome on MacOS. Some examples …

Expanding beyond the template preview …

image

Too close to the edge of the preview …

image

cc @apeatling @iamtakashi @alaczek

### PR DESCRIPTION
**Pull request by michaeldcain**
The `.editor-styles-wrapper` gets applied to the `.block-editor-block-preview__container` element, not to one of its children, thus style overrides in the template picker's preview are not being picked up. Along with a few previous overrides, this corrects the negative margins of `align:full` blocks and fixes #38884 

Screen Shot 2020-01-21 at 1 08 18 PM

**To test:**
- create a new page on a site with a template-first theme
- select a page template with an `align:full` block (i.e. Barnsbury, Menu, Contact)
- verify that the preview does not overflow the preview container on the left or right

### CODE REVIEW

**Comment by ianstewart** [comment]
Preview previews as expected with Maywood on Calypso live. 🚀

**Comment by apeatling** [comment]
Working well for me!

**Comment by apeatling** [comment]
@michaeldcain You can merge this fix

**Comment by apeatling** [comment]
Fixed conflicts.

**Comment by apeatling** [comment]
Failing test is unrelated.

**Comment by noahtallen** [comment]
I restored the branch and will create a new PR for this

**Pull request merged**
