### PR TITLE
Signup: Improve the `developers` signup flow for simplicity and speed.

### PR DESCRIPTION
**Pull request by kwight**

### CODE REVIEW

**Comment by bisko** [comment]
LGTM! :shipit:

**Comment by mtias** [comment]
What si the purpose of this change?

**Comment by folletto** [comment]
Visual record:

Before (`site` step): 
screen shot 2016-06-14 at 13 09 04

After (`domains` step):
screen shot 2016-06-14 at 13 08 59

**Comment by kwight** [comment]
@mtias the `site` step was superseded by the `domains` step back in August 2015 for the production flows.

I did just find #513 though, which is when the `developer` flow was added. Emphasis was on the smoothest, quickest experience for getting a developer registered. The `domains` step is good for this, since it autosuggests available domains – but bad because it offers a ton of upsell domains with a heavy API call. Maybe something in the middle makes more sense for this flow?

I also noticed that #513 decided that the `themes` step would be dropped, but that never happened. I can see two additional things happening for this PR:

 - [ ] Adapt `DomainSearchResults` to be just the `wordpress.com` autosuggested available domain.
 - [ ] Remove the `themes` step, and ensure that the site gets headstarted (Twenty Sixteen would be the default theme used).

@mtias sound like a plan?

**Comment by folletto** [comment]
I wouldn't include "domains" at all, or any payment, in this flow.  The `developers` flow is triggered from the "Register" button when a user runs Calypso locally first time. It would be a bad thing imho to try to do upsell to a developer trying to play with our codebase and see "Buy Domain" in the flow: _"Hey, come and play with our open source codebase... and drop some cash here please!"_

+1000 in removing Themes. We just have to pick a default theme that we feel it's a good starting theme for a Calypso dev. :)

**Comment by kwight** [comment]
@folletto I think we're saying the same thing. The developer should register a `wordpress.com` site (to expose the site management elements in Calypso), so the `domains` step is useful; but have nothing but the wordpress.com autosuggest in this flow's use of the component, so there's no upsell junk:

screen shot 2016-06-14 at 8 40 32 am

I guess this would also mean hiding the initial Drake screen too.

**Comment by folletto** [comment]
Ah ok! If we can remove from the same step all the upsell too, we can do that. I thought it was just easier to keep the old step — but the outcome is the same, so it's good. :) 

> I guess this would also mean hiding the initial Drake screen too.

Yes, I actually think that that screen should be removed regardless. :P

**Comment by mtias** [comment]
Nice, that sounds like a plan to me. (And yes, the goal is to have the quickest way to get going with using calypso and the API.) Thanks for looking at it :)

**Comment by lancewillett** [comment]
Closing as older and possibly abandoned. Feel free to re-open if still valid and in-progress.

**Comment by kwight** [comment]
Due to my own branch juggling clownshow, this is continued in #8935 .

**Pull request closed without merging**
