### PR TITLE
Masterbar: replace 'Edit Profile' and 'My Account' with 'My Profile'

### PR DESCRIPTION
**Pull request by fushar**
Related to:

- https://github.com/Automattic/wp-calypso/issues/95055
- https://github.com/Automattic/wp-calypso/issues/94470

Jetpack counterpart:

- https://github.com/Automattic/jetpack/pull/39600

## Proposed Changes

This PR modifies the following submenus in the `Howdy, {display menu}` menu in the admin bar:

- Point the `Edit Profile` submenu to `/me` always (and rename it to `My Profile` to match the page name).
- Remove the `My Account` submenu.

|Before|After|
|-|-|
|image|image|

~~In return, this PR proposes to add a link back to wp-admin's `profile.php` for the current site as follows:~~

EDIT: We decided not to include the following in this PR.

image

## Why are these changes being made?

The `profile.php` wp-admin page that the `Edit Profile` currently points to, contains mostly links back to Calypso. The most useful fields (display names, language, email) can only be done at user level in Calypso. So, to reduce jumps between Calypso <> wp-admin interface, this PR proposes that the submenu should point to Calypso.

## Testing Instructions

1. Go to `/home/:site`
1. Click the Howdy menu; verify it points to `/me`.
1. Click the Howdy -> My Profile submenu; verify it points to `/me`.
2. In `/me`, verify you can see the notice and it goes to the site's `profile.php` when clicked.

## Pre-merge Checklist

- [x] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [x] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [x] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [x] Have you checked for TypeScript, React or other console errors?
- [x] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [x] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [x] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Comment by taipeicoder** [comment]
With the removal of the "My Account" submenu, there is a visual imbalance between the top and bottom spacing of the menu. In addition, the "Log Out" is not aligned with the rest of the text (I think this is an existing bug). Could we improve these, or should we leave them as-is in favor of aligning with core? 

SCR-20241003-oquq

**Comment by fushar** [comment]
@taipeicoder yeah, this is an existing bug. In addition, we're also missing the username below the display name in Calypso. I think we can address all these bugs in a follow up PR 🙏

**Comment by fushar** [comment]
Also, we might soon be replacing the design of this Howdy menu on global masterbar completely with @lucasmendes-design's new design which puts it at the bottom left? Not really sure about that.

**Review by taipeicoder — APPROVED** [review]
LGTM, let's get some design input before merging this one!

**Comment by fushar** [comment]
> With the removal of the "My Account" submenu, there is a visual imbalance between the top and bottom spacing of the menu.

> In addition, the "Log Out" is not aligned with the rest of the text

> In addition, we're also missing the username below the display name in Calypso.

@taipeicoder I decided to fix the above in this PR, and revert the banner for now!

**Review by taipeicoder — APPROVED** [review]
LGTM 👍

**Pull request merged**
