### PR TITLE
Adds Attar, Hari, Marl, Winkel, and Dorna themes to /new flow

### PR DESCRIPTION
**Pull request by creativecoder**
#### Changes proposed in this Pull Request

* Adds Attar, Hari, Marl, Winkel, and Dorna themes to /new flow

#### Testing instructions

* Go to /new and proceed to the design picker step
* See that the Attar, Hari, Marl, Winkel, and Dorna themes are present

### CODE REVIEW

**Comment by jeyip** [comment]
## Testing
### Requirements
- [x] Can create a site with Dorna, edit the site in the full site editor, and see everything rendered in the frontend
- [x] Can create a site with Marl, edit the site in the full site editor, and see everything rendered in the frontend
- [x] Can create a site with Attar, edit the site in the full site editor, and see everything rendered in the frontend
- [x] Can create a site with Winkel, edit the site in the full site editor, and see everything rendered in the frontend
- [x] Can create a site with Hari, edit the site in the full site editor, and see everything rendered in the frontend

### Browsers
- [x] Chrome

### Follow-ups
- Dorna design picker preview hero image width doesn't match the image width in starter content. The hero image probably just needs a "Wide Width" designation.

Screen Shot 2022-03-02 at 1 55 54 PM

Screen Shot 2022-03-02 at 1 58 01 PM

**Review by jeyip — APPROVED** [review]
> Dorna design picker preview hero image width doesn't match the image width in starter content. The hero image probably just needs a "Wide Width" designation.

Lemme know if you see the same thing @creativecoder and I can make an issue for us. Otherwise everything else lgtm 🚀

**Comment by creativecoder** [comment]
@jeyip I do see the same for Dorna in the design picker preview, good catch!

The demo site does not show the issue (PdKsXk-2-p2), so I'm thinking it might be an old or malformed mshot preview... I'll try queuing a new preview and see if that helps.

**Comment by jeyip** [comment]
> The demo site does not show the issue (PdKsXk-2-p2), so I'm thinking it might be an old or malformed mshot preview... I'll try queuing a new preview and see if that helps.

Awesome! For anyone else that's curious, we can queue a new mshots preview by following these instructions PCYsg-sb-p2

**Comment by creativecoder** [comment]
It's definitely not an mshots issue... this looks to be a tangled in a few different things: a public-api theme switching issue as well some issue loading styles in the preview.

I was able to simulate a fix for the theme switch by manually clearing Gutenberg's json cache (`WP_Theme_JSON_Resolver_Gutenberg::clean_cached_data()`), but that actually makes it worse, because there appear to be some missing styles:

https://public-api.wordpress.com/rest/v1.1/template/demo/pub/dorna/dorna

image

And here's part of a diff of the demo site html compared to the public-api generated preview, notice the missing styles

image

**Comment by creativecoder** [comment]
I created this issue with my findings https://github.com/Automattic/wp-calypso/issues/61661

**Pull request merged**
