### PR TITLE
Increment diff api version to pick up new endpoint with FSE compatiblity

### PR DESCRIPTION
**Pull request by glendaviesnz**
**N.B.** This patch is needed for testing D31750-code and #35647 but should not be merged until both of these patches have been landed first

#### Changes proposed in this Pull Request

* Increment the diff endpoint version to utilise change implemented in  D31750-code

#### Testing instructions

* see #35647

Part of fix for #35483

### CODE REVIEW

**Comment by gwwar** [comment]
For landing it'd be waiting on plugin sync, making sure backend patches are applied, then finally any client changes.

**Comment by noahtallen** [comment]
Good catch! No, I had not tested on normal posts. Thanks for the reminder :)

**Comment by vindl** [comment]
Went through the testing instructions and everything works as expected. Nice work @glendaviesnz!

**Comment by gwwar** [comment]
I also verified the normal case in the block editor without FSE flows

**Pull request merged**
