### PR TITLE
Open button list if there are existing buttons

### PR DESCRIPTION
**Pull request by donpark**
setting activeTab to 'list' if paymentButtons is not empty.

### CODE REVIEW

**Comment by donpark** [comment]
Seems this patch works only right after initial load or refresh but not after. Need better understanding of the flow.

**Comment by donpark** [comment]
Missing control flow was `editPaymentButton` which seems intended to be used only for editing an existing payment button but is being called whenever `Add Payment Button` menu item is selected.

Fix was to check if it's an edit or not then use `form` tab if it is, otherwise use default activeTab selection logic which is now in `defaultActiveTab` method.

**Comment by jsnajdr** [comment]
@donpark This improvement was already implemented in #16783 and was merged today.

`editPaymentButton` method, as its name suggests, should only start editing a button by displaying the form. If we want to switch to the list at some point, that logic should be somewhere else.

Also, it's important to handle the situation where the list is not yet loaded and the count of existing buttons is unknown (`paymentButtons === null`). In that case, we don't want to show the form right away, but rather wait until the list has finished loading.

If you're interested, please have a look how the state of the component is being set up in the constructor, when the modal is first opened, and also in `componentWillReceiveProps`, during state transitions of an already rendered component.

I'd like to convert this modal's state management to a Redux reducer at some point -- I expect the logic to become simpler then.

**Comment by donpark** [comment]
>@donpark This improvement was already implemented in #16783 and was merged today.

Good. Would be nice to see Trello timely updated next time.

>`editPaymentButton` method, as its name suggests, should only start editing a button by displaying the form. If we want to switch to the list at some point, that logic should be somewhere else.

As I mentioned, `editPaymentButton` was being called every time the dialog showed, not just when editing a button, indicating a bug elsewhere.

**Comment by donpark** [comment]
Closing because same change is implemented in #16783.

**Pull request closed without merging**
