### PR TITLE
Build: Make JavaScript parseable by tsc

### PR DESCRIPTION
**Pull request by sirreal**
Our JavaScript flavor is not compatible with the TypeScript compiler (https://github.com/Microsoft/TypeScript/issues/4813)

I believe that is hindering TypeScript's ability to do its job of providing insight and type safety to our code base.

Remove imcompatible and proposal stage babel transforms and replace the syntax with TypeScript compatible equivalents.

```js
export nameForDefault from 'some-module';
// becomes
export { default as nameForDefault } from 'some-module';

// and

export * as someExportedName from 'some-module';
// becomes
import * as someExportedName from 'some-module';
export { someExportedName };
```

I'd suggest that these proposals offer limited value compared to the tradeoff of hindering TypeScript.

```sh
# before
$ tsc # 💥a bunch of syntax errors
# after…
$ tsc # 👏A bunch of type errors ✨ 
```

[Adds an "optional" (cannot fail) job to the CircleCI workflow that runs `tsc` on Calypso.](https://circleci.com/gh/Automattic/wp-calypso/280114)

#### Testing instructions

* `tsc` on master 💥 
* `tsc` on this branch shows reasonable type errors because the codebase can be parsed

### CODE REVIEW

**Comment by sirreal** [comment]
This would be a breaking change for `calypso-build`.

**Review by dmsnell — APPROVED** [review]
Thanks so much @sirreal for adding this. I love how we can see the errors and at some point I'm envisioning auto-reporting similar to the wonderful work that @jsnajdr did for ICFY.

Also, props for removing a couple of Babel transforms - that's simple!

**Comment by sgomes** [comment]
cc @jsnajdr and @blowery, as we'd discussed the stage 1 `export Foo from './foo'` syntax recently.

**Review by sgomes — APPROVED** [review]
LGTM. I'm in favour of removing stage 1 syntax, particularly when it adds so little, like in this case.

I'm a little worried that TypeScript will start dictating which syntax features we can and cannot use in JS, though, but the language seems to move fast enough that I think we can expect most of what we want to be supported.

**Comment by jsnajdr** [comment]
> I'm a little worried that TypeScript will start dictating which syntax features we can and cannot use in JS, though

It makes me somewhat sad, too. 😿 But the net profit seems be in very positive numbers anyway.

**Comment by dmsnell** [comment]
> I'm a little worried that TypeScript will start dictating which syntax features we can and cannot use in JS, though

@sgomes I'm personally more worried from our own history that Babel will dictate it. Our use of non-spec import and export statements prevented us for a long time from turning off CommonJS. It turned into a seven-month-long project to update the import/export statements and then once we were done we instantly shaved off about 80KB from the build bundles.

My point is that I'm more worried by the allure that Babel offers of using syntax before it's standardized because it's easy or convenient and at least TypeScript puts some reasonable brakes on the rate of disruption 😄 

🤷‍♂

**Pull request merged**
