### PR TITLE
Domain transfer: Fix CTA button color

### PR DESCRIPTION
**Pull request by renancarvalho**
## Proposed Changes

Fix the button color and unify the same style on buttons no step 1 and 2.
Context p9Jlb4-8kT-p2#comment-8667

image

## Testing Instructions

- Pull and run this branch or use live link
- Navigate to `/setup/domain-transfer` and check if the buttons match the [design](mbuq4o5QxohQpBU9YoexXo-fi-719_21329)

### CODE REVIEW

**Review by escapemanuele — APPROVED** [review]
Working great!

**Review by agrullon95 — APPROVED** [review]
Tested and working well. The buttons on both screens are matching.

**Comment by mtias** [comment]
This is not great. We should be using the `variant="primary"` and ensuring that renders as needed for these contexts. Can we revert?

**Comment by alshakero** [comment]
@mtias I agree, sending a follow up shortly.

**Comment by alshakero** [comment]
@mtias is [this](https://github.com/Automattic/wp-calypso/pull/79708) better? I'm not sure about the disabled state.

**Pull request merged**
