### PR TITLE
Paid stats: Update Upsell to match design

### PR DESCRIPTION
**Pull request by jwebbdev**
Related to https://github.com/Automattic/red-team/issues/304

## Proposed Changes

* Add Lock Icon
* Updated copy
* Adjusts width / spacing to more closely match line breaks
* Remove NavigationPeriod arrows when viewing Upsell state

Didn't remove the arrows for the non-new date filtering.  Just toggling off `showArrows` looks bad and wasn't sure fixing it up was necessary with the upcoming changes.

## Why are these changes being made?

Latest Design:
Screenshot 2024-12-05 at 2 09 15 PM

Screenshot 2024-12-05 at 2 07 36 PM

Updates here:
Screenshot 2024-12-05 at 6 12 33 PM

Screenshot 2024-12-05 at 6 12 47 PM

## Testing Instructions

* Open a calypso live branch and navigate to a free site's stats
* Compare the Upsell element to the Design above
* Ensure the Navigation period elements are hidden for new date filtering on upsell screen (may need to use the ?flags=stats/new-date-filtering)

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
    - [ ] For UI changes, have we tested the change in various languages (for example, ES, PT, FR, or DE)? The length of text and words vary significantly between languages. 
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Comment by ederrengifo** [comment]
Thank you @jwebbdev ! A have two minor comments:
- Could we apply consistent spacing among the elements from the left side?
- I think the image gets distorted when reducing the browser width, could we avoid that?

Screenshot 2024-12-05 at 15 27 26

**Comment by ederrengifo** [comment]
We can use these assets at 2x for the images to solve the image quality issue, and remove the `align-self: stretch` property so the image doesn't get distorted by the container height

insights-upsell-img2x
traffic-upsell-img2x

**Review by Initsogar — APPROVED** [review]
Looks good!

I just noticed that we have some issues with borders that don’t look right. You can try addressing it in this PR if you’d like.

CleanShot 2024-12-05 at 18 37 48@2x

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/17048911).

**Pull request merged**
