### PR TITLE
Plans 2023 : Add all features to comparison grid

### PR DESCRIPTION
**Pull request by ddc22**
#### Proposed Changes
- Adds all the features related to the comparison grid table

image

#### Testing Instructions
- Go to 
    - `/start/onboarding-2023-pricing-grid/plans?intervalType=yearly`
    - `/start/onboarding-2023-pricing-grid/plans?intervalType=monthly`
- Make sure the above grid s are visible on the respective URL

#### Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

Fixes Automattic/martech#1419

### CODE REVIEW

**Comment by claudiucelfilip** [comment]
I think this looks good to iterate upon.

There are some features inconsistency with the Figma design:
* General Features
  * Install plugins & themes is missing
  * Plugin auto-updates is missing 
* Security and Safety
  * BruteProtect is different
* Innovative Technologies is missing
* Marketing, growth and monetization tools
  * Unlimited shares in social media is twice

**Comment by ddc22** [comment]
@claudiucelfilip I the latest change should fix all problems. Can you have another look?
(BruteForce should not be an issue since I am essentially reusing a feature from above)

**Review by claudiucelfilip — APPROVED** [review]
Works well.
Approving, but there's a small conflict to be resolved before merging.

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/7766163

Thank you @jdc91 for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/7766163).

**Pull request merged**
