### PR TITLE
Subscribers: Paid subscribers content importer UI fixes

### PR DESCRIPTION
**Pull request by pkuliga**
Related to https://github.com/Automattic/wp-calypso/issues/93150

## Proposed Changes

It:
- adds "external" icon for "Export content" and "Export subscribers" links
- hides the upload description
- hides duplicated action buttons
- fixes action buttons spacing for "Content", "Subscribers" and "Paid Subscribers" step

| Before | After |
|--------|--------|
| Screenshot 2024-08-09 at 16 27 32 | Screenshot 2024-08-09 at 16 26 42 |

## Why are these changes being made?

To make content importer UI look closer to the designs.

## Testing Instructions

1. Go to `/import/newsletter/substack/{blogHostname}`
2. Type the Substack blog URL into the input and click "Continue"
3. Make sure the "Content" step looks as expected
4. Go to Tools -> Import -> Substack and make sure it doesn't introduce any regression to the existing importer

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Comment by enejb** [comment]
Nice work. 
Can we get the continue button to work again? (This can also be done in a different PR. ) 

Should we be using the Button from the wordpress/components? 

In my editor the calypso one says its deprecated? See https://github.com/Automattic/wp-calypso/blob/trunk/packages/components/src/button/index.tsx#L108

**Review by enejb — APPROVED** [review]
Nice clean up! 

I tested different imports and the worked as before for me.

**Comment by pkuliga** [comment]
> Can we get the continue button to work again? (This can also be done in a different PR. )

Not sure what you mean by that. Did I break something?

> Should we be using the Button from the wordpress/components?
> In my editor the calypso one says its deprecated? See https://github.com/Automattic/wp-calypso/blob/trunk/packages/components/src/button/index.tsx#L108

Noticed this as well but let's leave it as it is for now since we have other things to do with higher priority.

**Comment by enejb** [comment]
Screenshot_2024-08-09_at_9_15_50 AM

I think in a new PR we can make the Continue button work like the previous Upload button that is no longer there. :)

**Pull request merged**
