### PR TITLE
Site Migration: Add option to submit the URL input with Enter key

### PR DESCRIPTION
**Pull request by bisko**
#### Changes proposed in this Pull Request

* This PR adds the option to submit the URL input field with the Enter key. Previously we were only able to do that with the Continue button

#### Testing instructions

* Checkout branch or use Calypso.live link
* Go to Migration
* Enter URL
* Press enter
* The form should procceed

### CODE REVIEW

**Comment by andfinally** [comment]
The flow doesn't behave as I'd expect when I try this with my Jetpack site. Pressing enter does submit the form, which is great! But a console log line in the `then` handler of the request outputs an error, and the network tab shows no response from the endpoint. The URL changes to `http://calypso.localhost:3000/migrate/gntest0012home.wpcomstaging.com?sites-block__faux-site-selector-url-input=[ MY JETPACK SITE ]` and the UI goes into the loading view before returning to the "What WordPress site do you want to import?" form.

This is a bit strange, because I'm sandboxed, and I can currently get a good response from the endpoint in the WordPress.com console.

**Comment by bisko** [comment]
I just realized that the `onSubmit` event doesn't have `preventDefault()` called and the form actually submits the page 😳

Should work after fixing that.

**Comment by bisko** [comment]
@andfinally it should be fixed now! Thanks for catching it! For some reason it was working well when I tested, but when looking further it was failing on the first try, but was working on subsequent submits.

**Comment by andfinally** [comment]
Thanks, works nicely now! I had to rebase and rebuild my node modules to fix some errors I was seeing from other components – I've pushed the rebase on to this branch.

**Pull request merged**
