### PR TITLE
Help Center: add drag icon to header

### PR DESCRIPTION
**Pull request by arcangelini**
Issue was listed [here](https://docs.google.com/spreadsheets/d/1URiJTt4CC5bC_7-m3UolwrhcJP9ZbaLB7uC-AWC5DaI/edit?gid=1972884515#gid=1972884515&range=41:41)

## Proposed Changes

Add drag icon and refactor header component.

## Why are these changes being made?

It is still a bit unclear that the Help Center can be dragged around. This icon should help indicate that the box itself is able to be dragged. While adding another piece to the header that was conditional based on `isMinimized` it made the component a little complicated this led me to create two separate contents. One for minimized and another for open.

| Before | After |
| - | - |
| Markup 2024-07-15 at 21 44 39 | Markup 2024-07-15 at 21 43 54 |
| Markup 2024-07-15 at 21 44 12 | Markup 2024-07-15 at 21 44 12 |

## Testing Instructions

Open Calypso Live Link
Open Help Center to make sure it looks ok.
This is a simple style change so there shouldn't be any differences across locations.

### CODE REVIEW

**Comment by lucasmendes-design** [comment]
Hi there, a great improvement to the Help Center :) 

Can we make the icon less prominent? We can reduce the size and change the color. 

Figma file: ueOTNFNQ4pttm4F2qgbjeG-fi-401_31139

image

**Comment by arcangelini** [comment]
On it! Thanks @lucasmendes-design

**Comment by arcangelini** [comment]
Updated

Markup 2024-07-17 at 16 06 48

**Review by escapemanuele — APPROVED** [review]
Great! LGTM.

@lucasmendes-design if you have other things you wanna change, we can tackle them in a following PR!

**Comment by lucasmendes-design** [comment]
LGTM! Thanks folks.

**Pull request merged**
