### PR TITLE
Jetpack Pro Dashboard: Implement clock icon that shows the current monitor notification schedule for a site

### PR DESCRIPTION
**Pull request by yashwin**
#### Proposed Changes

This PR implements a clock icon that shows the current monitor notification schedule for a site

#### Testing Instructions

**Prerequisites**

Since these changes are made specifically for agencies, you must set yourself(partner) as an agency - 2c49b-pb. Make sure to switch it back to the previous type.

> **_NOTE:_** Changing the monitor status will not update the status immediately; we will have to debug this - 1203448324265423-as-1203576555374768

**Instructions**

1. Run `git checkout add/show-monitor-current-notification-schedule` and `yarn start-jetpack-cloud`
2. Open http://jetpack.cloud.localhost:3000/, and you'll be redirected to the /dashboard.
3. Enable the monitor for any site by clicking the toggle on the monitor column. 
4. Please note the monitor will not be enabled immediately; you might have to wait for some time until it is enabled. 
5. Once it is enabled, verify that the default time of 5m is shown next to the toggle, along with a clock icon.
6. Verify it looks fine on all the screen sizes using the dev tool. 

Monitor schedule(5 minute)

Screenshot 2022-12-19 at 11 54 02 AM

Monitor schedule(1 hour)

Screenshot 2022-12-19 at 11 52 58 AM

Mobile view

Screenshot 2022-12-19 at 12 26 24 PM

#### Pre-merge Checklist

- [x] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [x] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

Related to 1203448324265423-as-1203507036638725

### CODE REVIEW

**Review by vitozev — APPROVED** [review]
LGTM! The changes are working as expected and look good on different device sizes.

I have one UX question, though:

image

Currently, if you click on the `5m` that would trigger the toggle, is that expected?

**Comment by yashwin** [comment]
> Currently, if you click on the `5m` that would trigger the toggle, is that expected?

Thanks for the review on this, @vitozev. The current schedule(5m, 1hr) is a label for the toggle. So, clicking on the schedule is also triggering the toggle. But, this will be replaced with a button to open the notification modal here - https://github.com/Automattic/wp-calypso/pull/71373

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/7687431

Thank you @yashwin for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/7687431).

**Pull request merged**
