### PR TITLE
Social Login: refactor login buttons

### PR DESCRIPTION
**Pull request by arcangelini**
Related to pdDR7T-1Lq-p2

## Proposed Changes

There are a few changes that are being done:

1. Login links (magic login link and qr code link) are extracted to their own self-sustaining components. They should only need the login link.
2. Break down the `SocialAuthenticationForm` and move directly with `Social Signup/Login Form`
3. Relocated and consolidated relevant CSS.

## Why are these changes being made?

The overall goal is to achieve a "last used" login method. Given the current state of the login links this would not be easy or clean. To make this possible I thought it would be best to first consolidate all the login options into one location rather than 3.

Next PR will involve moving the logic for the social buttons (github, apple, and google) into the respecting buttons. This will allow the buttons to be used more universally without duplicating onClick handles and other logic.

## Testing Instructions

1. Use the live link.
2. Visit `/log-in`. Test desktop and mobile.
3. Visit `/log-in/es` and live link version. Test desktop and mobile.
4. Visit `wordpress.com/start/hosting` and live link version. Test desktop and mobile. They should be identical.
5. Visit `wordpress.com/start/hosting/de` and live link version. Test desktop and mobile. They should be identical.
6. Visit `wordpress.com/start` and live link version. Test desktop and mobile. They should be identical.
7. Visit `wordpress.com/start/de` and live link version. Test desktop and mobile. They should be identical.
8. Visit `wordpress.com/start/videopress-account/user` and live link version. Test desktop and mobile.
9. **P2**: [Signup](https://wordpress.com/start/p2/user) and [Login](https://wordpress.com/log-in?redirect_to=http%3A%2F%2Fcalypso.localhost%3A3000%2Fstart%2Fp2%2Fp2-confirm-email&from=p2&signup_url=%2Fstart%2Fp2%2Fuser)  and live link version. Test desktop and mobile.
10. **Jetpack**: [Link](http://wordpress.com/log-in/jetpack?site=https%3A%2F%2Ffalse-shrike.jurassic.ninja)  and live link version. Test desktop and mobile.
11. **Crowdsignal**: [Signup](https://wordpress.com/start/crowdsignal/oauth2-name?oauth2_client_id=978&oauth2_redirect=https%3A%2F%2Fpublic-api.wordpress.com%2Foauth2%2Fauthorize%3Fclient_id%3D978%26response_type%3Dcode%26blog_id%3D0%26state%3D51d5e1b0d7358dee3de65c45f4b4dc37a3d6e37dab8d6047545f636c2659d104%26redirect_uri%3Dhttps%253A%252F%252Fapp.crowdsignal.com%252Fconnect%253Fsource%253Dlogin%2526action%253Drequest_access_token%26wpcom_connect%3D1) and [Login](http://wordpress.com/log-in?client_id=978&redirect_to=https%3A%2F%2Fpublic-api.wordpress.com%2Foauth2%2Fauthorize%3Fclient_id%3D978%26response_type%3Dcode%26blog_id%3D0%26state%3D51d5e1b0d7358dee3de65c45f4b4dc37a3d6e37dab8d6047545f636c2659d104%26redirect_uri%3Dhttps%253A%252F%252Fapp.crowdsignal.com%252Fconnect%253Fsource%253Dlogin%2526action%253Drequest_access_token%26wpcom_connect%3D1) and live link version. Test desktop and mobile.
12. **Jetpack Cloud**: [Signup](https://wordpress.com/start/wpcc/oauth2-user?oauth2_client_id=69040&oauth2_redirect=https%3A%2F%2Fpublic-api.wordpress.com%2Foauth2%2Fauthorize%3Fresponse_type%3Dtoken%26client_id%3D69040%26redirect_uri%3Dhttps%253A%252F%252Fcloud.jetpack.com%252Fconnect%252Foauth%252Ftoken%253Fnext%253D%25252F%26scope%3Dglobal%26blog_id%3D0) and [Login](http://wordpress.com/log-in?client_id=69040&redirect_to=https%3A%2F%2Fpublic-api.wordpress.com%2Foauth2%2Fauthorize%3Fresponse_type%3Dtoken%26client_id%3D69040%26redirect_uri%3Dhttps%253A%252F%252Fcloud.jetpack.com%252Fconnect%252Foauth%252Ftoken%253Fnext%253D%25252F%26scope%3Dglobal%26blog_id%3D0) 
13. **Woo**: [Signup](https://wordpress.com/start/wpcc/oauth2-user?ref=oauth2&oauth2_redirect=https%3A%2F%2Fpublic-api.wordpress.com%2Foauth2%2Fauthorize%2F%3Fresponse_type%3Dcode%26client_id%3D50916%26state%3Dc92cfd0e05c2bf6e176a5ed1fbf185a99cf22a08cddf2bd631e1362b240d24f1%26redirect_uri%3Dhttps%253A%252F%252Fwoo.com%252Fwc-api%252Fwpcom-signin%253Fnext%253D%25252Fstart%25252F%252523%25252Finstallation%2526source%253Dsignup_menu%26blog_id%3D0%26wpcom_connect%3D1%26wccom-from%26calypso_env%3Dproduction%26jetpack-code%26jetpack-user-id%3D0%26action%3Doauth2-login%26from-calypso%3D1&oauth2_client_id=50916) and [Login](https://wordpress.com/log-in?redirect_to=https%3A%2F%2Fpublic-api.wordpress.com%2Foauth2%2Fauthorize%2F%3Fresponse_type%3Dcode%26client_id%3D50916%26state%3Dc92cfd0e05c2bf6e176a5ed1fbf185a99cf22a08cddf2bd631e1362b240d24f1%26redirect_uri%3Dhttps%253A%252F%252Fwoo.com%252Fwc-api%252Fwpcom-signin%253Fnext%253D%25252Fstart%25252F%252523%25252Finstallation%2526source%253Dsignup_menu%26blog_id%3D0%26wpcom_connect%3D1%26wccom-from%26calypso_env%3Dproduction%26jetpack-code%26jetpack-user-id%3D0%26action%3Doauth2-login%26from-calypso%3D1&client_id=50916&signup_url=%2Fstart%2Fwpcc%2Foauth2-user%3Fref%3Doauth2%26oauth2_redirect%3Dhttps%253A%252F%252Fpublic-api.wordpress.com%252Foauth2%252Fauthorize%252F%253Fresponse_type%253Dcode%2526client_id%253D50916%2526state%253Dc92cfd0e05c2bf6e176a5ed1fbf185a99cf22a08cddf2bd631e1362b240d24f1%2526redirect_uri%253Dhttps%25253A%25252F%25252Fwoo.com%25252Fwc-api%25252Fwpcom-signin%25253Fnext%25253D%2525252Fstart%2525252F%25252523%2525252Finstallation%252526source%25253Dsignup_menu%2526blog_id%253D0%2526wpcom_connect%253D1%2526wccom-from%2526calypso_env%253Dproduction%2526jetpack-code%2526jetpack-user-id%253D0%2526action%253Doauth2-login%2526from-calypso%253D1%26oauth2_client_id%3D50916)
14. MailPoet: [link](https://wordpress.com/log-in?client_id=79002&redirect_to=https%3A%2F%2Fpublic-api.wordpress.com%2Foauth2%2Fauthorize%3Fresponse_type%3Dcode%26redirect_uri%3Dhttps%253A%252F%252Faccount.mailpoet.com%252Flogin%252Fwpcom%252Fcallback%26scope%3Dauth%26client_id%3D79002)

### CODE REVIEW

**Comment by heavyweight** [comment]
Noticing this spacing difference on the videopress flow

https://github.com/user-attachments/assets/bf81c21d-546e-4215-9855-dabe355b2c94
https://github.com/user-attachments/assets/b9e69275-5aab-4197-94d4-df59932d9f01

**Comment by renancarvalho** [comment]
Found some inconsistencies on these pages. The same happens on mobile.

**P2 link — login buttons style difference.**

Local:
image

Prod:
image


**Jetpack and Jetpack Cloud**

Local:
image

Prod:

image

**Crowdsignal — Small button difference**

Local:
image


Prod:
image


**Woo LOGIN**

Local:

image


Prod:
image


**Mail poet**

Local:
image

Prod:
image

**Review by renancarvalho — COMMENTED** [review]
“Code wise” it is going in a good direction 👍

Just found some inconsistencies on the social buttons, probably missing styles here and there.

Good job 👍

**Comment by arcangelini** [comment]
OK I updated the CSS to fix the following LOGINS in desktop. I will take a look at the mobile to see whats missing tomorrow morning.

## WPCOM Login
https://github.com/user-attachments/assets/6f3e6683-520d-4d71-8848-c5c5cdd705ff

## P2
https://github.com/user-attachments/assets/c27f475e-182c-4926-8184-5fdf1bcc2114

## Jetpack
https://github.com/user-attachments/assets/3b6b7517-d841-4fba-9e1c-a91b6c09a81f

## Jetpack Cloud
https://github.com/user-attachments/assets/de514a88-cf19-4131-b3fb-85d16bf9821f

## Crowdsignal
https://github.com/user-attachments/assets/0b94e370-f7ad-4da3-bee5-d693e95820a7

## WooCommerce
https://github.com/user-attachments/assets/8c416f3c-4985-40fe-9270-12cc501b5589

## Mailpoet
https://github.com/user-attachments/assets/47f3107c-4fbd-4e27-a380-33ae8b6c9492

**Review by renancarvalho — APPROVED** [review]
Tested all the written pages, I have tested using mocked wordpress.com `yarn start-mock-wordpress-com` and did not find any issues.

Good job!

**Pull request merged**
