### PR TITLE
Jetpack Connect: Hook new site type and topic steps

### PR DESCRIPTION
**Pull request by tyxla**
This PR hooks together the new site type (segment) and site topic (vertical) steps.

#### Changes proposed in this Pull Request

* Hooks up the new site type and site topic steps in the JPC flows, between the authorization step and the plans selection step.
* Adds an exception for users without `manage_options` capabilities - they wouldn't see the new steps, as they could not do anything for them.

#### Testing instructions

* Spin this branch up locally.
* Create a new JN site with the latest bleeding edge Jetpack.
* Copy the URL of the connection button in wp-admin and add `&calypso_env=development` to it.
* Open the URL.
* After authorization, verify it leads you to the site type/segment step.
* After site type step, verify it leads you to the site topic/vertical step.
* After site vertical step, verify you're directed to the plans page.
* Try starting a connection from `/jetpack/new` or `/jetpack/connect` too.
* Verify you also get the site type and site topic steps in between the auth and plans pages.
* Try connecting an author user.
* Verify you DON'T see the site type and site vertical steps.

DO NOT MERGE: we need to test this thoroughly first.

### CODE REVIEW

**Comment by joanrho** [comment]
@tyxla just tested locally and the steps worked great, but I was unable to find this step:

>Look for the following options, and verify they are there:
>* `site_segment` - should contain your site type selection.
>* `site_vertical` - should contain your site topic selection.

When I opened that page, those options didn't exist. Sent you a screenshot in Slack.

**Comment by tyxla** [comment]
Thanks for testing, folks!

@joanrho nothing to worry about - the options you were looking for are way to the bottom, you should scroll quite a bit to see them 😉 the ones in your screenshot are `_site_transient` ones, not `site_` ones (the leading underscore keeps those that don’t interest us at the top).

**Comment by tyxla** [comment]
This is now ready for review.

**Comment by johnHackworth** [comment]
This works like a charm :+1:

**Pull request merged**
