### PR TITLE
Site Settings: add card to manage holiday snow settings

### PR DESCRIPTION
**Pull request by jeherve**
## Proposed Changes

This PR brings a new card to site settings in Calypso, allowing one to toggle Holiday snow on and off on their site.

image

Screenshot 2024-12-06 at 14 47 24

## Why are these changes being made?

See https://github.com/Automattic/dotcom-forge/issues/10082

## Testing Instructions

This can only be tested if you've added the functionality to your site, via this Jetpack PR:
https://github.com/Automattic/jetpack/pull/40478

When testing, you'll want to test both `/sites/settings/site/yoursite` and `settings/general/yoursite`, for a WordPress.com Simple and a WoA site.

1. Load `http://calypso.localhost:3000/settings/general/yoursite.wordpress.com?flags=-untangling/hosting-menu` for a WordPress.com site
2. Load `http://calypso.localhost:3000/sites/settings/site/yoursite.wordpress.com` for the same site

=> You should see the cards shown on the screenshots above.

## Pre-merge Checklist

- [x] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [x] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [x] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
    - [ ] For UI changes, have we tested the change in various languages (for example, ES, PT, FR, or DE)? The length of text and words vary significantly between languages. 
- [x] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Review by oskosk — APPROVED** [review]
Works great!

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/17050304

Some locales (Hebrew, Japanese) have been temporarily machine-translated due to translator availability. All other translations are usually ready within a few days. Untranslated and machine-translated strings will be sent for translation next Monday and are expected to be completed by the following Friday.

Thank you @jeherve for including a screenshot in the description! This is really helpful for our translators.

**Comment by simison** [comment]
You should add some check to hide it from P2s:

Screenshot 2024-12-06 at 22 13 05

Kinda sad that this didn't work for a P2, tho! 😅

**Comment by jeherve** [comment]
> You should add some check to hide it from P2s:

Yeah, that's a good point. Done in #97238

> Kinda sad that this didn't work for a P2, tho! 😅

:) It would have been nice indeed, but it would require some changes to the Snowstorm library we use to support p2's custom frontend.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/17050304).

**Pull request merged**
