### PR TITLE
package.json: Bump `notifications-panel` to v2.1.8

### PR DESCRIPTION
**Pull request by Copons**
This PR bumps the Notifications module to v2.1.8, which adds the Edit Comment button on comment notifications.

Testing instructions

- Load this branch and run `npm install`.
- Make sure that comments notifications now have these actions available (provided the user has enough capabilities):

screen shot 2018-01-30 at 18 52 12

### CODE REVIEW

**Comment by kwight** [comment]
I'm not sure this works, or I'm testing incorrectly. The Edit icons show up and seem to have the right links, but they redirect to the `comments/all/:site` view for both JP and dotcom sites 😐

Can anyone else replicate?

**Comment by rodrigoi** [comment]
@kwight can replicate. For some reason it's bouncing on the _Edit_ action.

mar-13-2018 20-50-45

will look closely...

**Comment by rodrigoi** [comment]
Created a little PR to fix the problem: https://github.com/Automattic/wp-calypso/pull/23288

I've created a new PR to keep this as just a version change in case we need a revert (and because it looks good on my stats page), but if you feel it's not necessary, just make the change here.

I have to confess I only debugged the WordPress.com Masterbar changes. Never looked really closely at Calypso's.

**Comment by Copons** [comment]
> Created a little PR to fix the problem: #23288

Woah, I am not sure how that could have happened.
I mean, I've been testing this for weeks now, and I've clicked on that button countless times and I've never noticed that. 🤦‍♂️

**Comment by vindl** [comment]
Apart from the issue reported above I also noticed this while testing:



For some reason `svg` element contains Cart title, which is sometimes shown on hover (alternating with `Edit comment`).

**Comment by Copons** [comment]
> For some reason `svg` element contains Cart title, which is sometimes shown on hover (alternating with `Edit comment`).

Good catch, dammit.
This is my fault on the notification panel (see https://github.com/Automattic/notifications-panel/blob/master/src/templates/gridicons.jsx#L271) caused by a copypaste fixed in a commit accidentally dropped during [a rebase that reverted some unnecessary changes](https://github.com/Automattic/notifications-panel/pull/222#issuecomment-371887640).

**Comment by Copons** [comment]
@vindl icon title issue tackled here: https://github.com/Automattic/notifications-panel/pull/240

**Pull request merged**
