### PR TITLE
Offer Reset: configure product cards when products are owned or included as a plan feature

### PR DESCRIPTION
**Pull request by rcanepa**
#### Changes proposed in this Pull Request

* Make product cards looks as per design when products are owned or included as a plan feature. Specifically, the badge label should be either "Included in your plan" or "You own this", and the CTA should move users to the purchases page (in both cases).

#### Testing instructions

* Run this PR with Offer Reset AB experiment enabled.
* Go to the Plans page.
* Purchase Jetpack Security Daily.
* Go to the Plans page.
* Verify that Jetpack Backup Daily, Jetpack Scan Daily, and Jetpack Anti-spam products are tagged with the "Included in your plan" badge, and that CTAs point to the me/purchases page.
* Repeat this process with other plans and make sure that product cards reflect the real relationship their have with the site purchases.

Fixes 1169247016322522-as-1189986731974009

##### Owning Jetpack Security Daily
Security Daily

##### Owning Jetpack Security Real-time
Security RT

##### Owning Jetpack Backup Daily
Backup Daily

### CODE REVIEW

**Comment by monsieur-z** [comment]
It tested well for Jetpack Security Daily and Real-time. Not for Jetpack Complete (see capture). Is this behaviour intended for Complete as well?
Screen Shot 2020-08-24 at 11 45 48 AM
Screen Shot 2020-08-24 at 11 45 57 AM

**Comment by rcanepa** [comment]
> It tested well for Jetpack Security Daily and Real-time. Not for Jetpack Complete (see capture). Is this behaviour intended for Complete as well?

@monsieur-z, definitely it's not expected. I think the problem might be in the features arrays of Jetpack Complete in not including all versions of Scan/Backup. Fixing... 🙂

**Comment by monsieur-z** [comment]
Nevermind! I didn't properly pull the branch.

**Comment by rcanepa** [comment]
> Nevermind! I didn't properly pull the branch.

Phew... You scared me 🙂

**Pull request merged**
