### PR TITLE
Correcting the feature list of the new plans page.

### PR DESCRIPTION
**Pull request by southp**
Related to Automattic/martech#1535

## Proposed Changes

This PR updates the feature list of the new plans grid according to Automattic/martech#1535. Citing below for easier reference:

* Unrestricted bandwidth currently applies to all our plans.
* ~The performance boosters lists applies to all our plans.~ The performance boosters applies to all our plans, except for the burst and CPUs as explained in pdgrnI-24M#comment-3414 
* Also true for “automatic datacenter fail-over”.
* Multi-site management is a feature of all our plans; same with “automated WordPress updates”.
* “DDOS mitigation” and “managed malware protection” are also present in all our plans, even if the malware one is less relevant on managed simple.
* Change “Advanced commerce solutions” to just “Commerce solutions”
* Let’s remove the “avant-garde design tools”.

Update on Feb. 21st: Per request of pdgrnI-24M#comment-3414, the upper plans table remains unchanged while we elaborate included features more in the plan comparison table below. 

## Testing Instructions

Access the new plans page at `/start/plans`, checking:

1. Whether the feature listed for each plan remains the same, except that "avant-garde design" has been removed. (updated per https://github.com/Automattic/wp-calypso/pull/73533/commits/d2511e138c62e8937bd1d17ebefef742c58f1125)
image

2. Whether the feature are correctly checked for each plan in the plans comparison table below.
image
3. There should no longer be "avant-garde design tools"

4. "Advanced commerce solutions" should now be "Commerce solutions"

image

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/7825568

Thank you @southp for including a screenshot in the description! This is really helpful for our translators.

**Review by ddc22 — APPROVED** [review]
LGTM :shipit:

**Comment by southp** [comment]
Thanks for fixing the type and making the code better, @jdc91 :)

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/7825568

Thank you @southp for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/7825568).

**Pull request merged**
