### PR TITLE
Sync: Remove interval pooling instead fire an action if required every time the props change.

### PR DESCRIPTION
**Pull request by enejb**
But not too often, but every 5 seconds.
screen shot 2016-07-28 at 14 20 52

###to test:
- Go to jetpack sites setting, then hit the full sync to trigger one. 
- In the network traffic notice that the request for sync status api don't over lap and only 1 is sent at a time. 

cc: @lezama, @gravityrail 

Test live: https://calypso.live/?branch=update/full-sync-status-on-change

### CODE REVIEW

**Comment by ebinnion** [comment]
This solution is very close to how I first implemented polling for sync status, so in general, I like the idea. 😄 

That being said, if the issue is overlapping requests, perhaps we could just change the amount of time between polled requests? This also came up in our team chat yesterday, where @gravityrail mentioned that we should only poll once every 20 seconds if I recall correctly?

**Comment by enejb** [comment]
This PR tried to be a bit smarter about the whole approach. In the sense that it would only ever fire a request that also has a delay if the previous one comes back with a result. Instead of just firing requests at the jetpack site at in interval. 

I guess if you have multiple browser windows open or multiple users trying to request the same data the issue that we bombard the the site with status requests still exists.

**Comment by ebinnion** [comment]
As a note, I increased the polling to 10 seconds in #7254. 

@gravityrail and I were talking earlier about perhaps returning the sync status from WPCOM, which should mitigate any concerns with overwhelming the Jetpack site.

**Comment by enejb** [comment]
@ebinnion increasing the polling time doesn't fix the issue since sometimes the request to get back the sync status takes longer then 10 seconds. 

PR tries to fix that by only scheduling a request after a request comes back from the Jetpack site. 

Currently this happens. 
screen shot 2016-08-03 at 12 29 57

**Comment by ebinnion** [comment]
`~19s` for a request. 😱 

Yea, I get your point. But, perhaps we can find a way to solve this in the `Interval` component so others could use it? I can take a look.

**Comment by lezama** [comment]
> ~19s for a request. 😱

We should investigate what's the bottle neck there

**Comment by lancewillett** [comment]
Noting this pull is a bit stale (2 months old) — anything needed to merge it in?

> We should investigate what's the bottle neck there

Is this tracked in a new GH issue or task?

**Comment by enejb** [comment]
Sorry, I think this can be closed. @ebinnion decided we should go with a different approach.

**Pull request closed without merging**
