### PR TITLE
[Odie] New odie package

### PR DESCRIPTION
**Pull request by AllTerrainDeveloper**
## Proposed Changes

It's been long time with some "junk" in Calypso, mainly for an experiment we did months ago, and our delays on "cleaning" the code. There are some changes that involves domains and emails, hence the reviewers added (automagically)

All the changes here are towards the creation of an "universal" package to be used anywhere. Within calypso, and not so far in time, out of it.

## Testing Instructions

The changes are involving changes in the plans sections, as well as domains and emails. Testing main functionality there is crucial. 

1. Change DNS settings
2. Add a new Mailbox
3. Remove a mailxbox
4. Go to plans and reach the bottom of the page via scroll.
5. Talk with Wapuu (it should be open for everybody, if not, add flags=wapuu to the url)

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

**Comment by alshakero** [comment]
Can't tell you how much I appreciate this!

**Review by gravityrail — APPROVED** [review]
Looks good to me. Made a couple of small fixes and updated from trunk.

**Comment by gravityrail** [comment]
I believe that the errors we're getting for Unit Tests are because we introduced a new package, and they might go away once we merge, but I don't like the idea of doing that while everyone's out.

@benzhu56 - want to take a shot?

**Comment by alshakero** [comment]
Hi! This type error is probably due to the missing reference in tsconfig of the Help Center. 

You have to add the path of the tsconfig file of the newly added package [here](https://github.com/Automattic/wp-calypso/blob/add/comment-editor/packages/help-center/tsconfig.json#L13-L18). 

**Edit**: I did that, all green now ✅

**Comment by AllTerrainDeveloper** [comment]
@alshakero always delivers 🙌

**Review by marco-altran — APPROVED** [review]
Tested and couldn't find any bugs.

**Pull request merged**
