### PR TITLE
Sites: Display site actions as EllipsisMenu

### LINKED ISSUE #7332: Sites: Display inline site editing options as EllipsisMenu
The `<Site />` component displays an ellipsis button which, when clicked, reveals a few editing options for the site:

Site options

These options include:
- Edit icon (links to wp-admin)
- Site settings (links to site settings)

For consistency of the ellipsis menu behavior, we should make use of the [`<EllipsisMenu />` component](https://github.com/Automattic/wp-calypso/tree/master/client/components/ellipsis-menu) for displaying these options.

### PR DESCRIPTION
**Pull request by aduth**
Closes #7332
Part of [Site Icon milestone](https://github.com/Automattic/wp-calypso/milestone/119)

This pull request seeks to display the `<Site />` component actions using an [`<EllipsisMenu />` component](https://github.com/Automattic/wp-calypso/tree/master/client/components/ellipsis-menu) instead of as an editable variant of the component. The goal with this change is to bring consistency of expectations with the ellipsis menu behavior in the application, and to open possibility of additional action options to be added.

Before|After
---|---
before|after

__Implementation notes:__

- Previously, `<PopoverMenu />` would override the `onClick` of a menu item child with a new function by binding it with the popover's close handler as the first argument. This seemed unexpected and was changed in 2d2295f to ensure both close handlers are called with the same argument (i.e. `event`). cc @mattsherman re: 3048-gh-calypso-pre-oss
- I discovered a `<ReaderPreview />` component which [renders with the assumption that `<Site />` component classes are already defined](https://github.com/Automattic/wp-calypso/blob/fb942c0e70821f5133aefe6791911b578db5c761/client/components/seo/reader-preview/index.js#L30-L40) (specifically the `.has-edit-capabilities` modifier class), instead of using the `<Site />` component itself. I'm fairly certain this will break with these changes, but I don't believe `<ReaderPreview />` should be rendering this way anyways. cc @roundhill re: #7338 

__Testing instructions:__

Verify that there is no regressions in the display and usage of the `<Site />` component, especially:
- Different contexts (there are no actions to be displayed in the site selector context)
- With and without indicator present (e.g. Jetpack plugin update available)
- Jetpack Site Icon link should navigate to the Customize screen on the Jetpack site, while WordPress.com sites should navigate to `options-general.php` in wp-admin

/cc @mtias @hugobaeta 

Test live: https://calypso.live/?branch=update/site-ellipsis-menu

### CODE REVIEW

**Comment by mtias** [comment]
The main thing here is what to do if "Site Settings" are removed as per https://github.com/Automattic/wp-calypso/pull/6379

**Comment by aduth** [comment]
>The main thing here is what to do if "Site Settings" are removed as per #6379

Hmm, would be strange to have an ellipsis menu for a single item in that case. Would we want to consider removing the icon editing and moving that into a settings screen?

cc @rickybanister @meremagee from reference pull request

**Comment by mtias** [comment]
The toggle menu was envisioned to work for icon and starring a site as a system. Alas, the starring functionality was since removed. For the icon, I think it's important to be able to change as "in place" as possible. But perhaps it's an action that occurs when hovering the icon. (Though that may conflict with the view site hover action.)

Given the affordance of the popover menu, perhaps we can move the preview/view site there as well (though, again, that increases the main action to two clicks) which would be decent for mobile.

**Comment by rickybanister** [comment]
I'd leave the whole site card as a link to visit the site. I think that's been a nice improvement to that area. 

The edit icon link makes sense in the ellipsis menu (in order to use the ellipsis menu in its native state), but linking away to edit the icon seems so silly when we have a media modal. The uploading and editing could all happen without leaving the current context. I realize there's more work to get in before that's possible, but I'd rather shoot for the ideal here. 

In the early sketches @mtias and I did for this, we'd hoped to allow editing the icon without leaving the area—I believe we switched from an edit toggle to the ellipsis because inline editing wasn't possible. 

All of that is a long way of saying this: what if we ditch the redundant settings link, leave some form of external edit icon link for now, but make it our bee's wax to change the ellipsis icon to an edit icon (gear or pencil or otherwise) that allows toggles the site card into an 'edit mode' with the dotted border on the icon and an upload link next to it.

**Comment by aduth** [comment]
>[...] linking away to edit the icon seems so silly when we have a media modal. The uploading and editing could all happen without leaving the current context. I realize there's more work to get in before that's possible, but I'd rather shoot for the ideal here.

As noted in the original comment, this pull request is part of our team's current effort to bring this experience to Calypso ([see milestone](https://github.com/Automattic/wp-calypso/milestone/119)).

Refs: p5j4vm-1l5-p2, p5j4vm-1jO-p2

**Comment by rickybanister** [comment]
Sorry @aduth, yes, that makes perfect sense. 

I suppose I'm just advocating that instead of an ellipsis, we switch to an edit icon which triggers the toggle to 'edit mode' as it is now, with editing happening in place. 

Apologies for jumping in mid-stream with gobbledygook.

**Comment by roundhill** [comment]
> I'm fairly certain this will break with these changes, but I don't believe <ReaderPreview /> should be rendering this way anyways.

Feel free to break it and I can fix it, we haven't launched the feature yet.

**Comment by hugobaeta** [comment]
@rickybanister I suggested the ellipse menu here for a simple reason: consistency. In post/page/cpt list views, we use ellipsis to expand on the actions a user can take. The first item on said list is always the primary action when the user clicks/taps the card/section. In the posts/pages/cpts list that action is "Edit Post/Page/CPT". In this case it would be "View/Preview site", and the section option would be "Edit Site Icon". 

I believe the users gains a lot when encountering a UI that is familiar and consistent in its UX. That said, this is a slightly different context than the Posts/Pages/CPTs lists, so I could be persuaded to think differently :)

**Comment by hugobaeta** [comment]
@aduth To reiterate what I said in the previous post, relating to this specific PR, I think it needs a little tweaking. Specifically adding "View Site" as the first item in the ellipses menu.

**Comment by rickybanister** [comment]
@hugobaeta well, I guess I'm confused by what editing 'in place' means here then. Using the ellipsis menu to trigger a localized 'edit mode' seems weird to me—especially since there will only be one option in the menu for the foreseeable future. 

Your second 'view site' comment came in while I was typing this—I'd rather keep the whole card clickable as a visit action, since it's been that way a while and seems to be working.

**Comment by hugobaeta** [comment]
> I'd rather keep the whole card clickable as a visit action

@rickybanister It was my understanding that we had the "Edit Icon" thing in there to push users to edit the site icon if it isn't set. If this could happen on initial site setup, then I agree that this whole area should just be a "View Site" link (removing the ellipsis menu entirely).

**Comment by rickybanister** [comment]
Yes, I'm in agreement, but my previous comment mentioned replacing the ellipsis menu with an direct edit icon for mid-stream site icon editing. That would keep the visit action on the card, but add the ability to toggle edit mode with no ellipsis, no pop up menu.

**Comment by hugobaeta** [comment]
> replacing the ellipsis menu with an direct edit icon for mid-stream site icon editing

For such a small area, I think having one "explicit" icon/action in there, and one "implicit" for the rest of the card, there's the risk of the user not understanding that the card is split. It's such a small area, I believe this would't make things clearer. Besides, what icon would represent that?

I guess what I'm saying is: we either remove all actions but one - the primary "Visit site" - or if we need multiple actions we should follow the ellipsis menu pattern (with the first item being the same primary action as you have on the rest of the card). Does that make sense?

**Comment by folletto** [comment]
> I suggested the ellipse menu here for a simple reason: consistency. In post/page/cpt list views, we use ellipsis to expand on the actions a user can take.

+1 

> I'd rather keep the whole card clickable as a visit action, since it's been that way a while and seems to be working.

+1

> The main thing here is what to do if "Site Settings" are removed as per #6379

I would say that ••• routes around that issue. We might still consider it, but it becomes less of a problem, being folded inside the popup menu.

Also, I think it's a sensible idea to always add inside these kinds of ••• menus also the primary action, not just more. I know it's not perfectly matching the original idea behind Android's "•••" as an "overflow" menu, but I still think it gives some order in having it there too.

So I'd propose:

> View $sitename
> Edit Icon
> Settings

And keeping the card click as the site click, as it is now.

Ideally in the future we can review this as a single action (so, maybe back to a cog?) that triggers an on-screen (overlay dialog?) edit mode including icon, title, url — all the bits visible from there.

**Comment by rickybanister** [comment]
@folletto I get your point, but you're proposing having two, not just one, redundant link in the ellipsis. Don't you think that will obscure the primary action—'Edit Icon'—which currently doesn't live anywhere else? 

It could also discourage people from realizing that the whole card is a link to view the site. 

I sort of feel like we're over-complicating things here. I know we have the ellipsis pattern and we should use it where it makes sense, but here doesn't seem to be one of those places. The only reason there is a settings link inside the current site card is that we removed the 'starred sites' functionality and felt like sticking something else there. Shortcuts and added functionality are nice, but we're sort of muddying up the experience, especially for brand new users. 

To take a step back here—we are about to add the Gravatar API functionality we need to allow users to swap their avatar right from the /me sidebar. Can we think of a better way to indicate that an image is editable for BOTH the site icon and the gravatar that's tightly in-context (meaning it doesn't require clicking on a nearby ellipsis menu to find the action)?

**Comment by folletto** [comment]
Well my suggestion was actually to simplify things (three items are very easily glanceable), and to get this in regardless, so we can have this change live quickly (resolving the doubt of the other thread) — because I think it makes sense.

Then sure, we can complicate things and redesign that bit, which is what I was hinting in the last paragraph. 

But I think it's a separate discussion. I'd push this live.

**Comment by hugobaeta** [comment]
Just to be clear, this PR doesn't entirely reflect what I had mocked up (adding it here for reference):

ideal-site-icon-popover

**Comment by shaunandrews** [comment]
So maybe instead of having a useless ellipsis and popover (no matter how it behaves) we just eliminate it.

Make the whole card open preview, and thats all it does.

Then, once site icon settings are in Calypso, they'll have a permanent home in /Settings. And we can call out the new setting (for those who don't have an icon) in a few ways:

- Using the site card banner, which currently is used for the "Free domain available" thing.
- Incorporate it into a Guided Tour for new users.
- An email sent users without a site icon XX days after signing up.
- As part of signup.
- As part of a guided onboarding process post-signup (this doesn't exists)

**Comment by rickybanister** [comment]
@shaunandrews I think that's a wonderful way to focus the site card. We tried to make it do too much before it was ready and ultimately it became muddy and confusing. 

Having it only represent a small version of your site and a gateway to the frontend would be much better. The site icon interface belongs in settings as you say, where it lives alongside the site title and tagline. I really like the compact notice banner idea as well—making it target sites that don't have a site icon will also reduce clutter as well. 

I also liked your alternate design for the signup step 1 which incorporated the site icon/title/tagline stuff nicely.

**Comment by hugobaeta** [comment]
> Make the whole card open preview, and thats all it does.

I was gonna make a summary with two options to move forward, with this being one of them, but it seems like we might be in agreement that removing the ellipsis completely is the way to go.

@aduth I guess we need to update this PR to remove the ellipsis menu entirely, keeping the site card primary action as it is (preview site), and move the Site Icon stuff to Settings (I'm thinking on the "General" tab, on the "Site Profile" section). I'm preparing a mockup for that, let me know where it will be the right place to discuss that.

**Comment by aduth** [comment]
>I'm preparing a mockup for that, let me know where it will be the right place to discuss that.

We can create a separate issue for adding this functionality to the site settings screen and add the concept / discussion there.

**Comment by folletto** [comment]
> I was gonna make a summary with two options to move forward, with this being one of them, but it seems like we might be in agreement that removing the ellipsis completely is the way to go.

It seems a good way right now.

It's also fairly simple to re-introduce the ellipsis at any point if we _really_ need it. :)

**Comment by rickybanister** [comment]
👍

**Comment by lancewillett** [comment]
Hi folks, is this one still moving ahead?

> We can create a separate issue for adding this functionality to the site settings screen and add the concept / discussion there.

Can we merge the bits that aren't part of the separate discussion? And work on that later.

**Comment by aduth** [comment]
We've already started on the path of adding site icon to settings screen in #8235.

This pull request would eventually be changed to removing all of the controls and have it act as a link as described in https://github.com/Automattic/wp-calypso/pull/7616#issuecomment-242500515, but I think we'd be better off creating a new pull request at the point when we're ready to do that*.

_*_ Which perhaps could be sooner than later, if we want to show the site settings field for all environments and link to wp-admin for those where the feature flag is disabled.

**Comment by aduth** [comment]
>_*_ Which perhaps could be sooner than later, if we want to show the site settings field for all environments and link to wp-admin for those where the feature flag is disabled.

Pull request at #8924

**Pull request closed without merging**
