### PR TITLE
Store: Settings: Display: Notices: Add read-only view of settings

### PR DESCRIPTION
**Pull request by allendav**
Ready to test

Partially addresses #20623 

To test:
* Navigate to http://calypso.localhost:3000/store/settings/display/{DOMAIN}
* You should see (static) content similar to the following
* Make sure the navigation and placeholdering works too
* You can change the text in the editor and see changes in the preview
* Responsive design too for narrow devices
* This is read-only - next PR connects redux and saving

screen shot 2017-12-13 at 11 15 45 am

screen shot 2017-12-13 at 11 15 21 am

### CODE REVIEW

**Comment by kellychoffman** [comment]
Nice! Made a couple styling and copy tweaks. 

Can a store owner change the background and text color of the notice?

**Comment by drw158** [comment]
Just a couple of suggestions.
- Link color should use wp.com color.
- The preview image is very heavy and the notice is not that noticeable. I would lighten the grays, especially the big squares below the notice.
- The checkbox should be probably be a toggle like Related Posts?

screen shot 2017-12-14 at 9 38 05 am

**Comment by allendav** [comment]
> Can a store owner change the background and text color of the notice?

Not via this interface. It is driven by the theme, and possibly customizer?

**Comment by allendav** [comment]
Parking this for the moment until January when I can look at this again with a Customizer context.

**Comment by jameskoster** [comment]
> The checkbox should be probably be a toggle like Related Posts?

@drw158 have we ever written any guidelines with regards to checkbox vs toggle usage?

**Comment by drw158** [comment]
@jameskoster I don't think we've written anything.

**Comment by apeatling** [comment]
@allendav Can we merge this? If not let's close it.

**Comment by timmyc** [comment]
Even though core has moved this functionality to the customizer - there still might be value for exposing it within the store settings as we have done here. Since the code is done, do you think we should consider merging it @kellychoffman ?

**Comment by justinshreve** [comment]
> Since the code is done, do you think we should consider merging it

Looks like this only displays the setting and there is no code for saving yet.

**Comment by allendav** [comment]
Closing without merge - can be resurrected later if desired

**Pull request closed without merging**
