### PR TITLE
Site Profiler: add navigation menu

### PR DESCRIPTION
**Pull request by gcsecsey**
Closes https://github.com/Automattic/dotcom-forge/issues/7301

## Proposed Changes

* add nav menu component
* connect nav menu to existing component refs

## Why are these changes being made?

* Site profiler UI updates

## Testing Instructions

For WPCOM sites:
- Go to the `/site-profiler` and enter a site URl
- Scroll down below the basic metrics, and check that the nav menu is rendered similarly to the Figma designs
- Click on the menu items and check that the correct component is scrolled into view
- Check the same with a mobile viewport, in this case the menu is scrollable to the side

For non-WPCOM sites:
- Repeat the steps above
- When the nav menu is shown, check that the CTA is rendered similarly to the Figma designs
- Check that the CTA redirects to the correct URL with the domain prefilled

Desktop view:

https://github.com/Automattic/wp-calypso/assets/11555574/84021e3e-8f82-494a-90f8-b109c8368e13

Mobile view:

https://github.com/Automattic/wp-calypso/assets/11555574/39433ba2-28b0-4ae9-9fcb-7144fc92341f

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Review by WBerredo — CHANGES_REQUESTED** [review]
There are a couple of changes needed:

* when the site is non-WP the security section [is hidden](https://github.com/Automattic/wp-calypso/blob/c58fc96db2283924a54e5247d5cab039a62d4590/client/site-profiler/components/security-section/index.tsx#L62-L65) but the security item still displayed on the menu

CleanShot 2024-06-04 at 13 57 23@2x

* The menu should stick to the top of the page when the user scrolled by it being always visible, at this moment, the section that is currently visible should be marked as active on the menu, similar to what was implemented [here](https://github.com/Automattic/wp-calypso/blob/c58fc96db2283924a54e5247d5cab039a62d4590/client/site-profiler/components/metrics-menu/index.tsx#L65-L81). (this can be implemented in a follow-up)

**Comment by gcsecsey** [comment]
> There are a couple of changes needed:
> 
> * when the site is non-WP the security section [is hidden](https://github.com/Automattic/wp-calypso/blob/c58fc96db2283924a54e5247d5cab039a62d4590/client/site-profiler/components/security-section/index.tsx#L62-L65) but the security item still displayed on the menu
> 
> CleanShot 2024-06-04 at 13 57 23@2x
> 
> * The menu should stick to the top of the page when the user scrolled by it being always visible, at this moment, the section that is currently visible should be marked as active on the menu, similar to what was implemented [here](https://github.com/Automattic/wp-calypso/blob/c58fc96db2283924a54e5247d5cab039a62d4590/client/site-profiler/components/metrics-menu/index.tsx#L65-L81). (this can be implemented in a follow-up)

@WBerredo I addressed these issues and updated the videos in the description. One issue I found while testing is that when scrolling to a ref, the menu covers the element we're scrolling to. I couldn't fix this by altering the margins or the position of the menu. I think we'd need to alter the offset we're scrolling to somehow, but I couldn't find an easy way to do it. Do you perhaps have an idea?

CleanShot 2024-06-05 at 17 51 44@2x

**Comment by WBerredo** [comment]
Thanks for addressing the issues, it looks much better now.

I've faced an issue of the menu not sticking on the mobile view:

CleanShot 2024-06-05 at 15 06 05

I've used the `StickyPanel` component to fix  to make it stick and it worked fine on the mobile view.

---

>One issue I found while testing is that when scrolling to a ref, the menu covers the element we're scrolling to. I couldn't fix this by altering the margins or the position of the menu. I think we'd need to alter the offset we're scrolling to somehow, but I couldn't find an easy way to do it. Do you perhaps have an idea?



For this I've created a method called `calculateMetricsSectionScrollOffset` that uses the menu height to offset, it probably just needs an update of this height to works well. [code](https://github.com/Automattic/wp-calypso/blob/trunk/client/site-profiler/utils/calculate-metrics-section-scroll-offset.ts#L1-L19)

**Comment by WBerredo** [comment]
I've implemented my suggestions on https://github.com/Automattic/wp-calypso/pull/91534.
Feel free to merge this inside your branch or even use just the part you want.

The only thing I think still missing is to scroll the menu horizontally to always show the visible section. Currently the item shows as active but the user has to scroll by themselves to see this.

**Comment by gcsecsey** [comment]
> I've implemented my suggestions on #91534. Feel free to merge this inside your branch or even use just the part you want.
> 
> The only thing I think still missing is to scroll the menu horizontally to always show the visible section. Currently the item shows as active but the user has to scroll by themselves to see this.

Thanks for creating that patch. I tested it and it worked great, so I merged the PR to this branch. 🙌

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/14138095

Some locales (Hebrew, Japanese) have been temporarily machine-translated due to translator availability. All other translations are usually ready within a few days. Untranslated and machine-translated strings will be sent for translation next Monday and are expected to be completed by the following Friday.

Hi @gcsecsey, could you please edit the description of this PR and add a screenshot for our translators? Ideally it'd include this string: `Request migration - It’s free`

Thank you in advance!

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/14138095).

**Pull request merged**
