### PR TITLE
[WIP] Add/gutenberg e2e

### PR DESCRIPTION
**Pull request by JavonDavis**
#### Changes proposed in this Pull Request

This is still definitely a WIP but I wanted to get some eyes on this early before I continue on other test files. 

* Executing Gutenberg e2e tests against dot com

#### Testing instructions

I can only vouch for the new-post test right now since I haven't started checking through the others but it should 

* npm install
* JEST_PUPPETEER_CONFIG=test/client/puppeteer.config.js PUPPETEER_HEADLESS=[true|false] WP_BASE_URL=<WP dot com site base url> WP_USERNAME=<username> WP_PASSWORD=<password> node_modules/.bin/jest -c=test/client/jest.config.js client/gutenberg/test/specs/new-post.test.js --env=jest-environment-puppeteer

#### Updates

So far I've made 2 major changes:

* Updates to the utils to log in through dotcom vs wp-admin
* Updated new-post test as needed to pass against a dotcom site. 

Original new-post test: https://github.com/WordPress/gutenberg/blob/master/test/e2e/specs/new-post.test.js
Since doing this the Gutenberg repo has broken up utils into separate files: https://github.com/WordPress/gutenberg/tree/master/test/e2e/support/utils

Still thinking through best ways to automatically sync up with the work on the Gutenberg repo even if it's just a script for cloning/file copying + file overriding.

### CODE REVIEW

**Comment by alisterscott** [comment]
> Still thinking through best ways to automatically sync up with the work on the Gutenberg repo even if it's just a script for cloning/file copying + file overriding.

You should try using a git submodule - we do that for the wrapper apps

**Comment by gwwar** [comment]
Nice start! ✨ Feel free to keep things on the messier side if needed while we feel out the problem space.

> You should try using a git submodule - we do that for the wrapper apps

Development-wise, this would be kind of confusing to have the full Gutenberg submodule only for e2e tests, after all the trouble of adding npm modules for core WordPress packages.

A submodule would be completely fine in a different repository.

If we'd like to keep the code here we could script the checkout/overrides in the short-term,. Or maybe if it makes sense we can help abstract out the tests further and publish these as a package with help from @gziolo and other folks. For example adding in login adapters/making selectors less wp-admin dependent.

**Comment by gziolo** [comment]
> If we'd like to keep the code here we could script the checkout/overrides in the short-term,. Or maybe if it makes sense we can help abstract out the tests further and publish these as a package with help from @gziolo and other folks. For example adding in login adapters/making selectors less wp-admin dependent.

We need to share as much code as possible with WordPress core, so we definitely have shared interests :)

I like that you started with copying the existing test suite. I see immediate areas where we could expose functionalities using npm:
- Jest configuration
- puppeteer config
- all test utils
- all test plugins
- test assets
- we could expose the script which runs e2e tests so you didn't have to maintain all required dependencies for test utils 

I assume that you want to have a full control over tests maintained in Calypso so I think the best way to move forward is to convert more chunks of code into reusable utils. I think it would be beneficial to Gutenberg, too. It would help to keep tests short and easier to read.

**Comment by gwwar** [comment]
@JavonDavis @gziolo @alisterscott As @Copons noted in another thread, I think it'd probably be better if we kept these separate from wp-calypso for now, if only to give us a bit of flexibility as we adapt these tests to many environments. The end goal will be as much code reuse as possible and contributions back to core, but we may need to add some bridge adapter code in the meantime.

It'd be really fantastic to get this running not only against /gutenberg in Calypso for example in CircleCI, but also optionally in Team City for our internal wp-admin deploys.

For folks reading see also https://github.com/Copons/gutenlypso-e2e and p7jreA-1WU-p2

**Pull request closed without merging**
