### PR TITLE
Try/functional open menu manage section if domains or email tabs are selected

### LINKED ISSUE #39934: Sidebar: Expand Highlighted Section
The Plan and Domains Tab have shared subsections. When MyPlan/Plans is selected, Plan is highlighted, but when email or domains is selected, the Manage > Domains tab is highlighted. However if the Manage grouping is collapsed, it may appear that no section is highlighted leaving customers with no orientation.

At a minimum let's make sure that any sidebar groups are expanded when we are on that section. I think it's a little strange that we have a subsection that navigates to a different sidebar item, but I'll defer to design on thinking through that.

Screen Shot 2020-03-06 at 9 08 03 AM

Mar-06-2020 09-22-36

### PR DESCRIPTION
**Pull request by millerf**
#### Changes proposed in this Pull Request

*  Functional version of modified version of SidebarItem (changes made in https://github.com/Automattic/wp-calypso/pull/39949)

#### Testing instructions

* Same as https://github.com/Automattic/wp-calypso/pull/39949

Fixes #39934
@gwwar

### CODE REVIEW

**Comment by millerf** [comment]
My first component built with hooks so happy to get some feedback.

**Review by mmtr — APPROVED** [review]
Good job @millerf! And congrats for opening the PR #40000 in Calypso 🙂.

Refactor here looks OK to me, didn't find regression and the `useEffect` hook is a nice addition 👍  

This should be ready to go once after a rebase with master to solve the conflicts.

**Comment by millerf** [comment]
> Good job @millerf! And congrats for opening the PR #40000 in Calypso 🙂.
🥳🎊🤣

> This should be ready to go once after a rebase with master to solve the conflicts.
The conflict is the PR you just merged :)

**Comment by millerf** [comment]
@mmtr it is rebased on `master`. 

We can close PR #40000 ! 🎊

**Comment by gwwar** [comment]
Nice work @millerf ! I can help land this for you.

**Pull request merged**
