### PR TITLE
Editor: Allow multiple contact form destination e-mails to be separated with a comma *plus* any whitespace

### LINKED ISSUE #4119: Editor: Contact Form: Allow trailing/leading spaces for comma separated email addresses
#### Steps to reproduce
1. Starting at URL: Editor with new contact form
2. Add or edit a contact form
3. Choose 'Settings'
4. Enter an email with a leading or trailing space ' joe@joe.com' or two etc. 'bob@bob.com, jean@jean.com'

#### What I expected

These should be ok as the system should remove the leading/trailing spaces, it is typically to enter a space after a comma

#### What happened instead

Error message displayed stating emails are invalid

#### Browser / OS version

Chrome OSX 10.10.2

#### Screenshot / Video

screen shot 2016-03-17 at 2 15 13 pm

### PR DESCRIPTION
**Pull request by DanReyLop**
Fixes #4119 
cc @rodrigoi 

When adding a contact form to a post, in the "settings" dialog, you can enter multiple e-mail addresses separated by a comma.
Before:
`aaa@aaa.com,bbb@bbb.com` (correct)
`aaa@aaa.com , bbb@bbb.com` (detected as incorrect, note the only change is whitespace, should be correct)

Now the leading and trailing whitespace of every e-mail address is removed before validating it.

### CODE REVIEW

**Comment by rodrigoi** [comment]
I'd rather avoid modifying the input on `validateSettingsToEmail`. Instead, we can do something like `				onKeyPress={ event => event.charCode === 32 && event.preventDefault() }` on the `FormTextInput`. That also has the desired side effect of providing the user some feedback when using the field. And if the user changes the destination emails on the _Text_ view of the editor, the form is correctly marked as invalid if the user chooses to use the dialog again.

**Comment by DanReyLop** [comment]
I have to disagree in this one. The API accepts whitespace between the emails (I've tested manually editing the shortcode), so I think it is the validator's responsibility to mark `"aaa@aaa.com  ,  bbb@bbb.com"` as a valid list of e-mails.

Preventing the user to enter certain characters feels hacky to me, specially since it's not enough to intercept `onKeyPress`, because the user can also paste text, for example.

PS: I'd rather not lose much more of our time discussing over a one-line fix. If you still think correcting the user input is the better solution, I'll implement it :)

**Comment by rodrigoi** [comment]
The copy/paste scenario is really compelling. Let's `trim` the input on the validator.
What would make a nice addition to this fix are some unit tests for `validateSettingsToEmail` and `validateFormFields`. How do you feel about adding them?

**Comment by DanReyLop** [comment]
Sure thing, I've just updated the PR with the tests :)

**Comment by rodrigoi** [comment]
@DanReyLop this looks great! One final thing: single test runner. You'll need to add these new tests to the single test runner configuration. Here are the docs: https://github.com/Automattic/wp-calypso/edit/master/test/README.md
Ping me if you have questions :wink:

**Comment by DanReyLop** [comment]
Done. I've removed the Makefile, with the tests added to `tests.json` it's no longer necessary, right?

**Comment by rodrigoi** [comment]
Awesome! :shipit:

**Pull request merged**
