### PR TITLE
Editor: Remove toolbar left and right borders when floating

### PR DESCRIPTION
**Pull request by sendilkumarn**
screen shot 2016-03-29 at 2 19 40 pm

### CODE REVIEW

**Comment by lancewillett** [comment]
Hi there, thanks for the pull request. Can you point to "why" behind it? What's the change for, why is it needed, etc. If it's a visual change, before & after screenshots are essential — preferably desktop and small screens.

CSS code style note: when using units with 0 (zero), you don't need the unit type — `s/0px/0/`.

**Comment by nylen** [comment]
This is intended to fix #4173.

However, this uses spaces for indentation instead of tabs :(

**Comment by sendilkumarn** [comment]
screen shot 2016-04-01 at 11 16 35 pm

**Comment by sendilkumarn** [comment]
@nylen

**Comment by nylen** [comment]
Looks good, thanks for contributing.  This is now live on WordPress.com!  (Build failure was unrelated.)

**Pull request merged**
