### PR TITLE
WebPreview: add prop to allow space for a sidebar

### PR DESCRIPTION
**Pull request by sirbrillig**
Adds `hasSidebar` prop to `WebPreview`, which adjusts the position of the preview over a bit to make space for a sidebar. 

This is extracted from #7477 and #7508, the latter of which actually adds a sidebar.

### Testing

There's no way to trigger this directly right now, but you can edit the source to do it manually.

First, make sure regular previews still work: click the site preview button in the my-sites view and make sure the site preview shows up correctly.

screen_shot_2016-08-16_at_4_32_06_pm

Second, edit the source of [DesignPreview](https://github.com/Automattic/wp-calypso/blob/master/client/my-sites/design-preview/index.js) and in the `render` method, add `hasSidebar={true}`.

Repeat the first test above and be sure that the preview is shifted to the right a bit.

Test live: https://calypso.live/?branch=add/web-preview-sidebar-space

### CODE REVIEW

**Comment by sirbrillig** [comment]
Ping @kwight for review

**Comment by kwight** [comment]
Works great, but how is it supposed to behave on smaller screens? This is what I currently get:

screen shot 2016-08-24 at 9 48 04 am

**Comment by sirbrillig** [comment]
@kwight that's a very good point. I altered the CSS so that the sidebar space only appears when there's enough room for it (same breakpoint used by the my-sites sidebar).

The other effect of this is that we're going to need a new layoutFocus for the preview sidebar so it can be made visible at small widths. This is a bigger task as it also requires adding a new navigation component to the preview that shows/hides the preview sidebar. I'd kind of like to add that here for completeness, but since there's no sidebar to show yet, it seems out of scope. 

OTOH I could add a placeholder sidebar in this PR, and then add the navigation and layoutFocus to go along with it. Maybe that would be more complete?

What do you think?

**Comment by kwight** [comment]
> OTOH I could add a placeholder sidebar in this PR, and then add the navigation and layoutFocus to go along with it. Maybe that would be more complete?

I think this is the way to go; it'll make more sense to anyone seeing it, and it won't stop us from getting this stuff merged.

**Comment by sirbrillig** [comment]
I think I'll just let this be part of #7508 where there's a sidebar.

**Pull request closed without merging**
