### PR TITLE
Reader: make photo zoom a secondary action on photo cards

### LINKED ISSUE #20478: Reader: Add enlarge and shrink icons to photo card
Issue pointed out by @shaunandrews:

> You can enlarge an image in the followed sites stream, but you can’t shrink it back — instead clicking it a second time opens the full post. 

### Suggested solution:

Clicking on a photo card takes you to fullpost instead of enlarging the image. We should then add an icon (lens with a plus sign) on top of the image as a way to enlarge it:

screenshot 2017-12-04 11 30 01

The icon then changes to a lens with a minus sign and clicking on it shrinks the image back to its default size:

screenshot 2017-12-04 11 26 05

- I think on mobile, the icon(s) should always be present, but should only show on hover on desktop.
- We currently don't have such icons on the Gridicons set. Will need to create them.
- It’d be cool if I could enlarge any/all images in a stream — not just “image-only” posts.

### PR DESCRIPTION
**Pull request by bluefuton**
Reader photo cards currently zoom the photo on first interaction, and click through to the full post once expanded.

We've never been quite happy with this experience, and this PR makes the following changes:
- [x] change the primary action to viewing full post
- [x] removes the old zoom hover styles
- [x] adds new zoom in/zoom out icons at the top right of the card

Fixes #20478.

cc @jancavan 

screen shot 2017-12-05 at 19 07 15

### CODE REVIEW

**Comment by jancavan** [comment]
Thanks @bluefuton! I'm in the process of creating those icons.

**Comment by jancavan** [comment]
PR submitted for Zoom in/out icons: https://github.com/Automattic/gridicons/pull/263

**Comment by jancavan** [comment]
Zoom in/out icons have been added in: https://github.com/Automattic/gridicons/pull/268

**Comment by bluefuton** [comment]
Rebased to pick up the new gridicons 👍

**Comment by bluefuton** [comment]
@jancavan I have the icons added and the expand/shrink working :) Would you mind working your CSS magic to overlay the icons at the top right?

expand_shrink

**Comment by jancavan** [comment]
Sure @bluefuton.

**Comment by jancavan** [comment]
@bluefuton As mentioned, I don't think the zoom icons are going to work since expanded photos don't always take up the entire column width I realized (sorry!) :/ We should still retain the toggle behavior, but without the icons. I'll move the title outside of the card as a way to get to fullpost. If there isn't a title, the comment button can be used as a way to get to fullpost.

**Comment by jancavan** [comment]
In https://github.com/Automattic/wp-calypso/pull/20523/commits/49eaef1932331ebbc8dca0c9130a1188b36d13ff, I removed the zoom icons and moved the title outside of the photo card.

**Before:**
screenshot 2017-12-26 15 50 21

**After:**
screenshot 2017-12-26 15 45 46

**Comment by jancavan** [comment]
To make it clearer, the next steps should be: to remove the zoom icons and make the photo expand/shrink just by clicking on the photo itself. The post title needs to be moved outside of the photo as a way to get to fullpost (this is already done in https://github.com/Automattic/wp-calypso/commit/49eaef1932331ebbc8dca0c9130a1188b36d13ff).

In edge cases where there isn't a post title, users can get to fullpost via the Comment button.

/cc @samouri @bluefuton

**Comment by samouri** [comment]
@jancavan: I just implemented _2_: "Make the photo expand/shrink just by clicking on the photo itself."

Back up for testing!

**Comment by jancavan** [comment]
@samouri When a photo is expanded, I'm sometimes seeing it overlap with Site Results:

screenshot 2017-12-28 10 37 29

Although I'm seeing a similar issue on staging, but it happens sooner.

I'm also seeing the action buttons overlap with the post title when photo is expanded.
screenshot 2017-12-28 10 38 55

**Comment by samouri** [comment]
I can repro that as well.
Looks like the `widthDivRef` got garbled when the component was split out.

**Comment by samouri** [comment]
Title placement issue fixed in https://github.com/Automattic/wp-calypso/pull/20523/commits/1106a00e8302ade79a74eeadf37e6fcd7a8f7114

**Comment by jancavan** [comment]
@samouri I can confirm that alignment has been fixed, thanks! Design-wise, this looks good to me.

**Comment by blowery** [comment]
>In edge cases where there isn't a post title, users can get to fullpost via the Comment button.

@jancavan We also hide that button if comments are not open and there are zero comments on the post.

**Comment by jancavan** [comment]
A couple more issues:

1. The rest of the photo card's clickable area should link to fullpost (I reverted to an old changeset so this may be my fault, sorry!)
2. My cursor seems to lose focus on this page. To repro:

- Type in a Search term.
- Try clicking on a photo and it doesn't work. I have to click elsewhere once and then click on the photo (or any link on the page) to get it to work (happens on staging too).

**Comment by jancavan** [comment]
Any updates on this? Correct me if I'm wrong, but I think very tall photos that don't take up the entire column width aren't too common so I think this can be a good potential solution: https://github.com/Automattic/wp-calypso/pull/20523#issuecomment-354636919

Thoughts?

**Comment by bluefuton** [comment]
Accessibility-wise, do we end up with enough contrast when the white zoom icon overlays the gradient?

screen shot 2018-01-18 at 08 49 10

**Comment by bluefuton** [comment]
> The rest of the photo card's clickable area should link to fullpost

I think that's happening because the `reader-post-card__photo-expand-controls` element is covering most of the card:

screen shot 2018-01-18 at 15 41 55

**Comment by jancavan** [comment]
I moved the post title outside of the photo card in: https://github.com/Automattic/wp-calypso/pull/20523/commits/52286329c12441eb0bf4d0da0c56d2854aac118a

I think to make this work:

- [ ] 1. Use zoom icons to expand/shrink a photo.
- [ ] 2. To get to fullpost, click on post title or comment button.
- [ ] 3. The rest of the photo card should be a clickable area that jumps to fullpost. This is so that you can still get to fullpost if the post title/comment button do not exist.

> Accessibility-wise, do we end up with enough contrast when the white zoom icon overlays the gradient?

Good point @bluefuton. I think this is better than what we currently have which is not just an accessibility issue, but a usability issue in its entirety. From what I see, really tall photos aren't too common, but that said, users can still get to fullpost with (2) and (3) above.

**Comment by bluefuton** [comment]
> The rest of the photo card should be a clickable area that jumps to fullpost. 

@jancavan definitely looks like this is caused by the `.reader-post-card__photo-expand-controls` being 100% width a covering the card. Is there an alternative way we can position the gradient?

**Comment by jancavan** [comment]
Hmm, I was trying to figure this out, but yeah, it's tricky. I tried to do a `::before` for `reader-post-card__photo`, but realized it won't work because then the overlay is dependent on the photo's width 🤔

**Comment by jancavan** [comment]
> Is there an alternative way we can position the gradient?

It's clickable now. Fixed in: https://github.com/Automattic/wp-calypso/pull/20523/commits/4927b279fa41ea770591549210fad52041a809ea

@bluefuton I'm seeing overlapping between the photo card title and action buttons when expanded:

screenshot 2018-01-22 20 21 40

I think it's being caused by the fixed height `reader-post-card__photo`'s container `div`:

screenshot 2018-01-22 20 18 31

**Comment by bluefuton** [comment]
That's not ideal :(

screen shot 2018-01-24 at 14 43 16

Can you remember how the height is calculated here @samouri?

**Comment by samouri** [comment]
Its the same issue as: https://github.com/Automattic/wp-calypso/commit/1106a00e8302ade79a74eeadf37e6fcd7a8f7114. 

I don't think we were gaining anything from the styles though so I've removed the div entirely

**Comment by jancavan** [comment]
Overlapping has been fixed, thanks @samouri.

@bluefuton In the Search results, I've to click twice on any link to get them to work. Any idea why?

**Comment by samouri** [comment]
dserve link: https://dserve.a8c.com/?branch=update/reader/photo-card-actions

**Comment by jancavan** [comment]
> In the Search results, I've to click twice on any link to get them to work. Any idea why?

Hmm, actually, it's just the zoom icons that I have to click twice.

To repro:

1. Go to Search
2. Type something in the Search bar
3. Find a photo card and click on the zoom icon (you have to click twice to get it to work.)

Video: https://cloudup.com/chDoQDVP_EY

**Comment by blowery** [comment]
Weird. I can repro. Hovering over the icon for a bit eventually gets it to change, as does scrubbing across it.

Feels like a Chrome bug. Maybe related to how we lay out search results with flexbox? I can't repro in the following stream.

**Comment by bluefuton** [comment]
I think we've done some useful exploration here. I suggest we close this one for now - I will try and rescue some of the individual improvements and create a few smaller PRs.

**Pull request closed without merging**
