### PR TITLE
Bug Fix:  Scroll to top of page when link is clicked

### PR DESCRIPTION
**Pull request by Dillweed5446**
cc: @fditrapani 

#### Changes proposed in this Pull Request
Added onUpdate function to be executed when a link to view a component within <Collection/> is clicked (onClick).  Specifically, the issue pointed out that the <Popover/> component link would render at the bottom of the documentation page.  I noticed that the same thing happened with other components within the <Collection/> parent, so I added a function that would cause the links to render at the top of the documentation page.
*

#### Testing instructions
Go to : https://wpcalypso.wordpress.com/devdocs/design , scroll down to <Popover/> to view Popover docs (or any other link on the bottom half of the page).  The documentation for Popover should be scrolled to the top of the page after following the link.

*

Fixes #
Added onUpdate function to scroll to the top of the newly rendered webpage.  Added onClick event listener to handle onUpdate function.

### CODE REVIEW

**Comment by fditrapani** [comment]
@Dillweed5446 I'm still seeing the same behaviour for long pages. I reached out to some folks to see if we could get you some help with your setup. Is there anything I can do to help with debugging this issue?

**Comment by Dillweed5446** [comment]
I think the main thing that will help me is to be able to run the development environment on my computer.  Once I can do that, I can do more trial and error to fix the bug.  Thank you!

**Comment by fditrapani** [comment]
I'll do my best to try get you some help. I'm unfortunately not very good with this infrastructure type of stuff.

**Comment by Dillweed5446** [comment]
Submitted fix under a new commit.  See #44330

**Pull request closed without merging**
