### PR TITLE
Add WP Super Cache extension

### PR DESCRIPTION
**Pull request by donnapep**
This PR adds a placeholder section for WP Super Cache.

### CODE REVIEW

**Comment by mtias** [comment]
Good to see this.

**Comment by dbtlr** [comment]
I was just adding this too :)

**Comment by donnapep** [comment]
@mtias Is this one OK to merge?

**Comment by mtias** [comment]
Yes, sorry, go ahead. We may want to add an "/extensions/wp-super-cache" namespace to the url looking forwards.

**Pull request merged**
