### PR TITLE
Stats: Fix redirection of the invalid site for the post details page

### PR DESCRIPTION
**Pull request by dognose24**
Related to #70749

## Proposed Changes

* Remove the appended site fragment for redirection to the default Stats page.

## Testing Instructions

* Spin up this change with the Calypso Live link.
* Navigate to the Stats `Post Detail` page with an `invalid` site (`/stats/post/${post-id}/${invalid-site-slug}`).
* Ensure the redirection navigates to the main site's `Traffic` page (`/stats/day/${site-slug}`) or the `Overview` page (`/stats/day`) if you own multiple blogs.
* Ensure the URL is not appended with the wrong site query string.

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

**Review by jsnmoon — APPROVED** [review]
Works as described!

**Review by grzegorz-cp — APPROVED** [review]
👍

**Review by kangzj — APPROVED** [review]
Works as described

**Comment by kangzj** [comment]
> Ensure the redirection navigates to the main site's Traffic page (/stats/day/${site-slug}) 

<strike>Unfortunately it failed my test. I followed the instructions. It redirects to `/stats/day/{post-id}` which wouldn't exist either, and then redirects to `/stats/day`. Or am I missing anything?</strike>

**Review by kangzj — APPROVED** [review]
Works as described 👍

**Pull request merged**
