### PR TITLE
Share styles across SSH card components.

### LINKED ISSUE #69248: WPCOM SSH: Abstract SSH key card to a common component
We currently display a SSH key card twice:

image

image

It would be nice if these used the same underlying component.

One thing worth noting: the first card has Redux state passed into it (https://github.com/Automattic/wp-calypso/pull/69220/commits/6fb9b7f9305a2d0add6363fde45ed6b7b643aa6a) because `user_login` isn't present in the API response. We should add `user_login` to the API response so we don't have to be dependent on Redux state.

**Done is:**
* [ ] The SSH key card is abstracted to a common component and reused in both contexts.

### PR DESCRIPTION
**Pull request by mpkelly**
Fixes https://github.com/Automattic/wp-calypso/issues/69248

#### Proposed Changes

* Make both SSH cards use a common suite of styled-components

image

image

#### Testing Instructions

* Do a before/after test in the two locations this component is used:
   - `/hosting-config/:site`
   - `/me/security/ssh-key`

#### Pre-merge Checklist

- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?

Related to #

### CODE REVIEW

**Review by zaguiini — APPROVED** [review]
👍 

Do we need to use compound components here? Isn't it possible to just use render props or accept React nodes from the props? I think that with that level of flexibility we might just forget to update both places...

**Comment by danielbachhuber** [comment]
Landing this so we can use it in https://github.com/Automattic/wp-calypso/pull/69826

> Do we need to use compound components here? Isn't it possible to just use render props or accept React nodes from the props? I think that with that level of flexibility we might just forget to update both places...

@zaguiini Can you expand? I'm curious what the difference is...

**Comment by danielbachhuber** [comment]
> Landing this so we can use it in https://github.com/Automattic/wp-calypso/pull/69826

Blocked by the E2E tests right now... p1668429238282719-slack-C1A1EKDGQ

**Comment by mpkelly** [comment]
> 👍
> 
> Do we need to use compound components here? Isn't it possible to just use render props or accept React nodes from the props? I think that with that level of flexibility we might just forget to update both places...

Good observation 👍 My first attempt used a single component, and then I realised the button flags were different and decided to use compound components to avoid too many props. If we need to make more changes, keeping the structure in sync should be easy.

**Pull request merged**
