### PR TITLE
Async load logged-in layout and masterbar

### PR DESCRIPTION
**Pull request by Tug**
This PR is an experiment to see how we could lighten the main calypso bundle for logged out users mainly.

WIP.

### CODE REVIEW

**Comment by yurynix** [comment]
Related: #21393 #21328

**Comment by dmsnell** [comment]
We should also add into our evaluation of this the increased latency we introduce to logged-in views since this will introduce a serial dependency that doesn't currently exist: the initial bundle loads, then after transferring and parsing and executing, it sends out the request for the layout, then it transfers and parses and executes and finally the page becomes usable.

**Comment by jsnajdr** [comment]
> this will introduce a serial dependency that doesn't currently exist

Yes, that's true: if naively implemented, splitting the logged-in layout will make the initial load slower.

But it can be mitigated by careful implementation: the server knows that the user is logged in when generating the `index.html` page and can ship the appropriate chunk immediately as a script tag. It already ships the chunk for the initial section. If you open `wordpress.com/stats`, you'll get the `stats` chunk in `index.html`. If you open `wordpress.com`, you'll get the `reader`.

**Comment by Tug** [comment]
Agreed, we need a good amount of testing before going on with a solution like this one.
FYI, this was mostly attempted as a "lighter" alternative to https://github.com/Automattic/wp-calypso/pull/21328.

**Pull request closed without merging**
