### PR TITLE
Reader: connect the SiteStream and FeedStream

### PR DESCRIPTION
**Pull request by samouri**
Connect the site stream and feed stream to Redux.

#### Was it okay to remove checkForRedirect?
answer: No.  We need `checkForRedirect`.  Sometimes if someone somehow gets to a route like /blogs/blogid/post/postId and we _know_ that the feed is more reliable than the site, we will want to redirect them.  This is especially true for some vip jetpack sites.  

There is a field called `prefer_feed` that sites have.  It only exists as a property when it is true.

#### What is has_featured for?  I deleted a whole bit about featured feeds but probably need to put those back in

has_featured was a property we were using to say that it had a "featured posts" section at the top like Discover.  Since this is only true for Discover I special cased the whole thing anyway.  No need to generalize there.

### To test

Play with the site-stream- specifically going to /blog/ and /feed/ addresses, e.g.:

http://calypso.localhost:3000/read/blogs/122463145

http://calypso.localhost:3000/read/feeds/15197253

### CODE REVIEW

**Comment by samouri** [comment]
Answers to questions: 
1. need to add prefer_feed to the reducer so we can listen to that here
2. has_featured is only for discover.  so lets special case it.

**Comment by samouri** [comment]
squashed and rebased

**Comment by blowery** [comment]
Seeing a few odd `0`s at http://calypso.localhost:3000/read/feeds/23244865

Likely `&&` shortcuts returning the first value, which is `0`.

**Comment by blowery** [comment]
stories_from_slate_ _reader_ _wordpress_com

**Comment by samouri** [comment]
Nice catch @blowery!  TIL we get a blog_ID 0 for feeds that don't have associated sites!

**Comment by blowery** [comment]
> TIL we get a blog_ID 0 for feeds that don't have associated sites!

Yeah, a good candidate for normalization in the data layer...

**Comment by samouri** [comment]
@blowery, or better yet at the api layer...

**Comment by bluefuton** [comment]
@samouri I've cleaned up the description a bit but not sure the questions/answers all line up - would you mind writing a quick summary?

**Comment by blowery** [comment]
> @blowery, or better yet in the actual api..

yeah, but that would be a new version of the site and feed endpoints as we're changing the semantics. Not a terrible idea though.

**Comment by samouri** [comment]
While `getReaderSiteId` is definitely something that should exist in a data-normalization layer somewhere, I'm worried about it ballooning and potentially breaking expected behavior elsewhere.  As this PR is already a net of ~300 LoC I think it could be best to move in a future PR (adding it to the data-layer + its unit tests seem like a good solo pr)

**Pull request merged**
