### PR TITLE
Reader: Fix Combined Cards content exceeding container

### PR DESCRIPTION
**Pull request by jancavan**
Fixes: https://github.com/Automattic/wp-calypso/issues/15184

Example: https://wpcalypso.wordpress.com/read/search?q=Coachit&focus=1&sort=date

**Before:**
screenshot 2017-06-16 10 03 16

screenshot 2017-06-16 10 03 33

**After:**
screenshot 2017-06-16 10 03 21

screenshot 2017-06-16 10 03 37

### CODE REVIEW

**Comment by samouri** [comment]
👀

**Comment by samouri** [comment]
👀  again

**Comment by samouri** [comment]
Nice @jancavan! This fixes the extending issue.  One problem I'm still seeing is:
1. I'm noticing that if a combined card is the first result it doesn't have the padding-top it needs.  The first post _and_ the cc header are both not visible because of it.  Feel free to solve in a separate pr if you prefer.

**Comment by jancavan** [comment]
> I'm noticing that if a combined card is the first result it doesn't have the padding-top it needs. The first post and the cc header are both not visible because of it.

@samouri is it CC in the Search results or the Following stream? Do you have a screenshot?

**Comment by samouri** [comment]
@jancavan, I was going to post a screenshot but it looks like you already posted one in https://github.com/Automattic/wp-calypso/pull/15208#issue-236540812.  The first image in the **After** section. Its clear from the scrollbars that it is at the top but the CC header is missing

**Comment by jancavan** [comment]
@samouri Good catch, for some reason I forgot they had that. I'll fix in another PR.

**Pull request merged**
