### PR TITLE
Customize Auth flow for Blaze Pro

### PR DESCRIPTION
**Pull request by timur987**
Related to A8C-DSP's issue `1439`.

## Proposed Changes
* Adjust common styles for the case of BlazePro (base on WooCommerce's Auth flow implementation).

## Why are these changes being made?
* We need to customize WPCOM Authentication flow for BlazePro (in the same way it's implemented for WooCommerce)

Designs in [Figma](https://www.figma.com/design/0YQJMNMOVVOMqzCWufls0l/BlazePro-(Self-Served-for-Advertisers)?node-id=7096-11442&t=jNKJPuFzcHDxg3TE-0).

## Testing Instructions
Despite the PR `1520` from A8C-DSP repo is the starting point for running Blaze Pro, we can test changes in Calypso with the use of the following script that generates links for Login and Sign Up (it should be run with `node`).

```js
function generateState() {
  const crypto = require('crypto');
  const hmac = crypto.createHmac('sha256', 'secret' );
  const data = hmac.update(new Date().getTime().toString());
  const state = data.digest('hex');
  return state;
}

const redirectUri = 'http://blaze.pro:3005/auth/connected&blog_id=0&wpcom_connect=1&calypso_env=development&scope=global&from-calypso=1';
const getLoginLink = () =>
	`https://public-api.wordpress.com/oauth2/authorize?response_type=code&client_id=92099&state=${generateState()}&redirect_uri=${encodeURIComponent(redirectUri)}`;

const signInLink = `http://calypso.localhost:3000/log-in?client_id=92099&redirect_to=${encodeURIComponent(getLoginLink())}`;

const signUpLink = `http://calypso.localhost:3000/start/wpcc/oauth2-user?oauth2_client_id=92099&oauth2_redirect=${encodeURIComponent(getLoginLink())}`;

console.log('Login URL:');
console.log(signInLink);
console.log('');
console.log('Sign Up URL:');
console.log(signUpLink);
```

**Caveat 1**: I noticed that for Google Chrome uses "DNS over HTTPS", so for me it's impossible to use it for sandboxing. So, I used Firefox for testing.

**Caveat 2**: I was not able to have authentication to be working locally. I assume that as long as it will be merged it should work properly due to having `wordpress.com` instead of `calypso.localhost:3000`.

### Login Flow
- Sandbox WPCOM,
- Apply D149804-code,
- Use the script to generate a URL,
- Run Calypso locally,
- Open a URL in your browser (like `https://public-api.wordpress.com/oauth2/authorize?response_type=code&client_id=92099&...`),
- Ensure you see Login page similar to image below:

image

- Use your WPCOM credentials to continue
- Due to inability to authenticate locally, as a sign of being authenticated in WPCOM we should see a screen of already authenticated on WPCOM's side:

image

Short demo:

https://github.com/Automattic/wp-calypso/assets/115007291/76bcb0d0-553e-411f-b8df-beb5ad3c26c7

### Sign Up Flow
(Continue testing)
- Clear browser cookies,
- Adjust code ([source](https://github.com/Automattic/wp-calypso/blob/trunk/client/signup/main.jsx#L841)) in `client/signup/main.jsx:850` in order to show Processing Screen from:
```js
{ this.state.shouldShowLoadingScreen ? (
```

to:

```js
{ true || this.state.shouldShowLoadingScreen ? (
```

- Get a URL for Sign Up from the script,
- Open a URL in your browser (like `http://calypso.localhost:3000/start/wpcc/oauth2-user?oauth2_client_id=92099&...`),

processing-screen

- Remove code adjustment you've done before
- Refresh the page and make sure you see Sign Up form

image

Short demo:

https://github.com/Automattic/wp-calypso/assets/115007291/a9ea1d2f-85ec-4ff7-8f5d-fa0c58f6a0a3

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Review by therocket-gr — APPROVED** [review]
tested locally
works as described. code changes LGTM

**Review by chihsuan — COMMENTED** [review]
Hey @timur987, thanks for adding us as reviewers! Nice work here. 👍 

First, I think code overall looks good and I confirmed that WooCommerce flow styles are applied correctly. However, I have a few comments:

1. I see a couple of UI issues. The UI is not fully consistent with the designs. For example, the font size of footer text is a bit bigger than in the designs and padding between the heading and subheading is smaller. I'd suggest to make sure that the UI is consistent with the designs. But I'll leave it up to you to decide if you want to make these changes or not.

Screenshot 2024-05-27 at 12 24 39


2. The title flashing on the screen for a second before the page is fully loaded. I think there might some heading mismatch in the code.


https://github.com/Automattic/wp-calypso/assets/4344253/8698f5e1-3bd4-4352-9013-60595dc3f6e9



3. When I clicked on `Log in here` link, I was redirected to a blank page. I think it should redirect to the login page. 

https://github.com/Automattic/wp-calypso/assets/4344253/3037817c-4ba8-4f33-80a6-c179969a665b


4. I tried to sign up with an new email, but I got an error `
Invalid OAuth2 redirect url`.

Screenshot 2024-05-27 at 12 31 07

5. 2FA screens are WP.com branded. Looks like design is missing for these screens. 

Screenshot 2024-05-27 at 12 33 48

6. We're using passwordless signup for WooCommerce. I'd suggest to use the same for BlazePro as well. 

Screenshot 2024-05-27 at 12 57 40

> Due to inability to authenticate locally, as a sign of being authenticated in WPCOM we should see a screen of already authenticated on WPCOM's side:



> Caveat 1: I noticed that for Google Chrome uses "DNS over HTTPS", so for me it's impossible to use it for sandboxing. So, I used Firefox for testing.

> Caveat 2: I was not able to have authentication to be working locally. I assume that as long as it will be merged it should work properly due to having wordpress.com instead of calypso.localhost:3000.

To test sign/login flow locally, you can set up a local wordpress.com or wpcalypso.wordpress.com environment by following the instructions in this field guide (PCYsg-5YE-p2 > Running Calypso locally under wordpress.com or wpcalypso.wordpress.com)

My team also created some scripts that use docker to set up a local environment. It's in a private repo. If you want, I can share it with you.

**Comment by timur987** [comment]
Thanks for such a thorough review @chihsuan!

I addressed your comments (118c6bac2cb042cf353d433897f94f5935bec5ca) and will refer to them in order not to miss anything.

### UI Issues

> 1. I see a couple of UI issues. The UI is not fully consistent with the designs. For example, the font size of footer text is a bit bigger than in the designs and padding between the heading and subheading is smaller. I'd suggest to make sure that the UI is consistent with the designs.

Thanks for matching the design. I changed icon to be 32x32px, adjusted padding between the heading and subheading. The only issue I can't find the way to overcome is to use fonts as in design. In particular, Calypso asks to use `rem` as a unit an has limited set of allowed values (style lint [settings](https://github.com/Automattic/wp-calypso/blob/trunk/.stylelintrc#L38-L39)). For this case I needed to use `18px` which is `1.125rem` but Calypso allows only either `1rem` or `1.25rem`, so I decided that bigger is better. Maybe I'm wrong. Will ask our designer, @bartoszbak.

### Title flashing

> 2. The title flashing on the screen for a second before the page is fully loaded. I think there might some heading mismatch in the code.

Indeed there was the discrepancy between the OAuth App name in Calypso's code and in WPCOM Apps. Fixed by changing name in App's settings ([here](https://developer.wordpress.com/apps/92099/settings/)).

### URL issues

The following two (3 and 4) are similar:

> 3. When I clicked on Log in here link, I was redirected to a blank page. I think it should redirect to the login page.
> 4. I tried to sign up with an new email, but I got an error  Invalid OAuth2 redirect url.

Sorry for that. I made a mistake (that caused improper URI encoding of redirect URLs) in script for link generation in testing instructions. Updated the script, so now it should work properly.

### 2FA

> 5. 2FA screens are WP.com branded. Looks like design is missing for these screens.

Thanks for pointing me, indeed. Addresses it as well.

https://github.com/Automattic/wp-calypso/assets/115007291/536adc53-09de-446a-880a-8d1c5dfd1851

### Passwordless signup

> 6. We're using passwordless signup for WooCommerce. I'd suggest to use the same for BlazePro as well.

Thanks for letting me know. I'll discuss this opportunity with my team.

### Local setup

> To test sign/login flow locally, you can set up a local wordpress.com or wpcalypso.wordpress.com environment by following the instructions in this field guide (PCYsg-5YE-p2 > Running Calypso locally under wordpress.com or wpcalypso.wordpress.com)

> My team also created some scripts that use docker to set up a local environment. It's in a private repo. If you want, I can share it with you.

Thanks for letting me know. I thing for now the right front-end design is what we need. I think that in case of issues I'll definitely ask you for access to the mentioned private repo.

**Comment by chihsuan** [comment]
@timur987 Thanks for addressing feedback.

> For this case I needed to use `18px` which is `1.125rem` but Calypso allows only either `1rem` or `1.25rem`, so I decided that bigger is better. Maybe I'm wrong. Will ask our designer,

You can use `rem(18px)` to get `1.125rem` in Calypso. It's a helper function that converts pixels to rems and not limited by stylelint settings. 

> 2FA
> Thanks for pointing me, indeed. Addresses it as well.

I noticed that on the video recording, when you hovered over the button, the background color changed to WP blue. I think it would be great to fix that.

**Review by chihsuan — APPROVED** [review]
I tested again and functionality works as expected. 👍 

Just left a few comments for UI improvements. Since this doesn't affect the WooCommerce flows and Blaze Pro is not public yet, I'm going to approve this PR and let your team decide on the final design. 🙂

**Comment by timur987** [comment]
I have several attempts to deliver this PR but it failed Pre-release tests. Here's the last PR I tried to deliver to production: https://github.com/Automattic/wp-calypso/pull/91304.

**Pull request merged**
