### PR TITLE
Theme Showcase: Add tracking events to the auto-loading homepage modal

### PR DESCRIPTION
**Pull request by sixhours**
#### Changes proposed in this Pull Request

* Add Tracks events to the actions on the Theme Showcase's auto-loading homepage modal. It looks like this:

Screen Shot 2021-05-18 at 11 59 47 AM

**Example Tracks event logs**

Dismiss
Screen Shot 2021-05-19 at 1 52 41 PM

Activate
Screen Shot 2021-05-19 at 1 52 58 PM

View
Screen Shot 2021-05-19 at 1 52 28 PM

#### Testing instructions

* Switch to this PR and navigate to `/themes/[site]` on a simple site
* Click on a Recommended theme and "Activate"
* Check the Tracks events in MC (there will be several minutes' lag); alternatively, log them to your browser console with `localStorage.debug="calypso:analytics*"`
* You should see a Tracks event fire upon opening the modal - `calypso_theme_autoloading_homepage_modal_view` with prop theme id `theme: theme-name`
* You should see a Tracks event fire when you dismiss the modal (click outside it) - `calypso_theme_autoloading_homepage_modal_dismiss` with prop `action: 'escape'` and theme id `theme: theme-name`
* You should see a Tracks event fire when clicking "Keep current theme" - `calypso_theme_autoloading_homepage_modal_dismiss` with prop `action: 'button'` and theme id `theme: theme-name`
* You should also see a Tracks event fire when you choose to activate the theme, with props for the theme switched to and whether you chose to keep the current homepage or not - `calypso_theme_autoloading_homepage_modal_activate_click` with props `theme: 'theme-name'` and `keep_current_homepage: true/false`

Related to #52926

### CODE REVIEW

**Comment by ianstewart** [comment]
I have a couple questions for the dismiss. Are we recording both ways of dismissing — keep my current theme button, clicking outside the modal — and are we recording the current (active) theme somewhere as prop for those events?

**Comment by mreishus** [comment]
Tested all scenarios, events are working well, not all theme information is there though:

* :heavy_check_mark: Modal displayed
  * both new and old theme are not in the event
* :heavy_check_mark: Activate and use homepage
  * event includes new theme name
  * old theme name is not included (not sure if easily accessible)
* :heavy_check_mark: Activate and don't use homepage
  * event includes new theme name
  * old theme name is not included
* :heavy_check_mark: Keep button
  * both new and old theme are not in the event
* :heavy_check_mark: Click outside modal
  * both new and old theme are not in the event

**Comment by kwight** [comment]
Sweet! I've got some of the same feedback as @mreishus : 

* I'd expect the theme to be recorded for dismissals too.
* I'd expect both the "click outside modal" and "keep theme" actions to be the same Tracks event (they're the same user action, just done two different ways), with a prop of `escape` (click outside) or `button`.

I'm not so worried about recording previous/new themes on these events, there's a `calypso_themeshowcase_theme_activate` event that fires with that info already.

**Comment by sixhours** [comment]
👍 I'll update this to make the dismissal event one event with props rather than two separate events. 

> I'd expect the theme to be recorded for dismissals too.

~~@kwight Do you mean the site's currently active theme, or the theme referenced in the modal?~~

Clarified on a call, he meant the theme referenced in the modal, so I've made that change.

**Comment by kwight** [comment]
Fantastic 👍

**Review by kwight — APPROVED** [review]

**Pull request merged**
