### PR TITLE
Stats: Release the new annual highlights section

### PR DESCRIPTION
**Pull request by jsnmoon**
Note: Consider waiting for [these strings to be fully translated](https://translate.wordpress.com/deliverables/overview/7610530/) before release.

#### Proposed Changes

image

* Adds a new annual highlights section at the top of the Insights page.
* Hides the existing "Annual site stats" module at the bottom left of the Insights page.

#### Testing Instructions

* Spin up this change in a live branch.
* Navigate to Stats -> Insights.
* Ensure you see the new annual highlights section.

#### Pre-merge Checklist

- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?

Related to #69227

### CODE REVIEW

**Review by dognose24 — APPROVED** [review]
LGTM!

**Comment by jsnmoon** [comment]
Note that a lot of the changes applied to the highlight cards in https://github.com/Automattic/wp-calypso/pull/69862 will carry over to this PR 🙂

**Comment by jsnmoon** [comment]
@keoshi & @jeffgolenski, could you give this one a look soon? Thanks! 🙏

**Comment by keoshi** [comment]
Apologies for the delay on this one, @jsnmoon — it must have fallen through the cracks.

Two notes:

- [ ] Some of the the data points aren't showing up. I wonder if the dash signifying null is displayed instead of zeros?

This is happening on a site where I haven't posted anything this year. Let me know if you want to be added so you can test it for yourself.

image

- [ ] In tablet/phablet sizes, the cards appear cut off and not flush to the browser window.

image

**Comment by jsnmoon** [comment]
> Some of the the data points aren't showing up. I wonder if the dash signifying null is displayed instead of zeros? [...] This is happening on a site where I haven't posted anything this year. 
> 
> Let me know if you want to be added so you can test it for yourself. (@keoshi)

Yes, please! Could you also check whether the original "Annual site stats" module further down the insights page works for your site on production? The new annual highlights should use the same data as the older section.

image

>  In tablet/phablet sizes, the cards appear cut off and not flush to the browser window.

The fix for this is, unfortunately, more involved than I'd like for this PR (we'd need to address [this](https://github.com/Automattic/wp-calypso/blob/dea365b99f707a95052d8e0e25b045b79ff238bf/client/my-sites/sidebar/style.scss#L677)). Let's punt this out of the PR for now.

**Comment by keoshi** [comment]
@jsnmoon Added you to the site, but no data is visible on that module:

image

Again, I assume this is happening because I haven't posted this year (zero Posts and Words) or had any Likes or Comments. What I'm trying to understand is if these should all show up as `—` or `0`, or if it's a data issue on this particular site. What do you think?

> Let's punt this out of the PR for now.

Sounds good. :)

Thank you!

**Comment by jsnmoon** [comment]
> What I'm trying to understand is if these should all show up as `—` or `0`, or if it's a data issue on this particular site. What do you think?

I think it makes sense to use emdash to signify data unavailability and to use `0` when the metric is 0. Unfortunately, we have a data unavailability issue here 🙂 —  the insights endpoint intentionally omits annual summary data for years with inactivity. 

For now, let's display `0` when they meet these criteria:
- Insights endpoint returns a well-formatted array of `years` data.
- Current year is missing from the well-formatted `years` array.

(Aside: This is a pre-existing problem 😉)

**Comment by keoshi** [comment]
> Unfortunately, we have a data unavailability issue here

Got it, thanks for clarifying and apologies for the added distraction. 😅

> For now, let's display `0` when they meet these criteria:
>
> - Insights endpoint returns a well-formatted array of `years` data.
> - Current year is missing from the well-formatted `years` array.

Thank you once again, Jason!

**Review by wilmersondasilva — APPROVED** [review]
LGTM

**Comment by jsnmoon** [comment]
@danjjohnson: We expect to release this feature in the next 24 hours.

This PR moves the annual site stats to the top of the Stats Insights page while preserving all existing functionality.

Before | After
--|--
image|image

**Review by keoshi — APPROVED** [review]
LGTM!

**Comment by jeffgolenski** [comment]
Also LGTM!

**Review by jeffgolenski — APPROVED** [review]

**Pull request merged**
