### PR TITLE
Packages: Fix ignore in calypso-color-schemes

### PR DESCRIPTION
**Pull request by sirreal**
Gitignore was causing required `__color-studio` directory to be removed from the package. Add empty .npmignore so that `.gitignore` is not used.

`@automattic/calypso-color-schemes@1.0.0-alpha.0` has a broken sass file due to missing directory.

### CODE REVIEW

**Comment by ockham** [comment]
Maybe add a comment in `.npmignore` to explain why we need it so people aren't tempted to remove it?

**Comment by sirreal** [comment]
Added a comment about why the npmignore is required.

**Comment by simison** [comment]
Should this mechanism be mentioned in monorepo docs?

**Comment by sirreal** [comment]
> Should this mechanism be mentioned in monorepo docs?

I don't think that's necessary. This is standard npm and we don't want to start reproducing their documentation.

**Pull request merged**
