### PR TITLE
Settings: simplify language picker component

### LINKED ISSUE #41938: Settings: simplify language picker component
The language picker in the general settings screen is a custom dropdown:

Screen Shot 2020-05-07 at 9 53 35 AM

It has the word 'CHANGE' inside the box indicating it can be clicked, but this doesn't seem necessary. We can make it look exactly like the timezone picker just below.

Something like this:

image

### PR DESCRIPTION
**Pull request by ncardeli**
The language picker used in the general settings and account settings screens is a custom dropdown. It has the word 'CHANGE' inside the box indicating it can be clicked, but as discussed in #41938 this doesn't seem necessary.
As proposed by @rickybanister we can make it look exactly like a standard dropdown, like the timezone picker just below in the general settings screen, for visual consistency.

#### Changes proposed in this Pull Request

* Matched the style of the language picker custom drop down to the style of standard drop downs (select elements), including focused and hovered states.
* The language code and subcode are now shown in one single line, instead of two lines, to allow the custom drop down to match the height of standard drop downs.
* Added a fade for long content

##### Before (general settings)
imagen

##### After (general settings)
imagen

##### Before (account settings)
imagen

##### After (account settings)
imagen

##### Before (language code and subcode - two lines)
imagen

##### After (language code and subcode - one line)
imagen

#### Testing instructions

* In the sidebar, go to Manage > Settings
* Verify that the language picker visually matches the timezone dropdown bellow (size, colors and fonts).
* Pass the mouse over the language picker
* Verify that the chevron's color gets darkened as the one inside the timezone dropdown does when hovered
* Using the keyboard, set the focus on the language picker
* Verify that the language picker gets highlighted as the timezone dropdown does when focused
* Click on the language picker and select "Español de México" from the popup
* Verify that the text inside the language picker is now "ES MX | Español de México"

Fixes #41938 

cc: @jsnajdr

### CODE REVIEW

**Comment by rickybanister** [comment]
Looks perfect, thanks @ncardeli!

**Comment by gwwar** [comment]
Did you want to help land this one @rickybanister if tests are green?

**Comment by rickybanister** [comment]
@gwwar I'm afraid my local environment is a bit borked currently. But if tests pass we can definitely merge.

**Comment by gwwar** [comment]
Note that the desktop failure looks like a circle hiccup with authentication on OSS PRs. Changes here should be pretty safe.

**Comment by mmtr** [comment]
Thanks @ncardeli! This indeed implements what was suggested in https://github.com/Automattic/wp-calypso/issues/41938, but I'm not sure if changes here will actually cause an inconsistency issue rather than addressing it.

> As proposed by @rickybanister we can make it look exactly like a standard dropdown, like the timezone picker just below in the general settings screen, for visual consistency.

I know this was briefly discussed in the original issue, but if we're aiming for consistency, shouldn't we also change what a user sees when clicking so it displays an actual dropdown rather than a dialog? Otherwise, the timezone picker will open dropdown and the language picker a dialog, but both pickers will look visually the same with that chevron, setting a wrong expectation that a dropdown will be opened in both.

As I see it, we don't have any inconsistency in production right now. We have two pickers that are visually different because they behave differently, with a dialog that is better suited for languages and a regular dropdown for the timezones.

Anyway, I'm not a designer, so it's entirely possible I'm wrong 🙂 

cc @Automattic/dotcom-manage-design for feedback.

**Comment by sixhours** [comment]
I get what @mmtr is saying; the down chevron usually implies something will open downward or drop down. I wonder if a right chevron would imply something is opening rather than dropping down? Or if we made it look more like a split button/button set, such that clicking on it opens the modal? I can work up some quick mocks to show what I'm thinking in a few.

**Comment by sixhours** [comment]
Something like this, maybe:

Screen Shot 2020-08-06 at 11 36 36 AM

That said, I think this PR is already an improvement despite the inconsistency, so I don't think it should be a blocker. :)

**Comment by rickybanister** [comment]
I'm ok with that suggestion @sixhours. 

There was a mention somewhere to eventually adopt the core gutenberg language picker innards eventually, so doing whatever is lightweight for now makes the most sense. 

Let's remove the chevron and get this merged.

**Comment by ncardeli** [comment]
Great feedback @mmtr, thank you.
Also, thank you @sixhours and @rickybanister for considering @mmtr's feedback and offering a new alternative.
I will we working on this new design later today 👍

**Comment by ncardeli** [comment]
I removed the chevron and now it looks like this:

##### Account settings
imagen

####  General settings
imagen

What do you think @rickybanister @sixhours?

**Comment by sixhours** [comment]
This looks good to me from a design perspective! 👍

**Comment by ncardeli** [comment]
Thanks @sixhours!
Should I ping anybody else to get this merged?

**Comment by sixhours** [comment]
Oh looks like we already got approval from dev, so we should be good to land this! I will plan on doing so first thing tomorrow (pretty close to the end of my day here).

**Pull request merged**
