### PR TITLE
Subscribers Page: add subscribers feature

### LINKED ISSUE #78363: Subscribers Page: Add ability to Add Subscribers.
1. Add a button called "Add Subscribers" on the top bar.
2. When clicked, it should show the same form as seen on the existing Add Subscribers page either **on a new page** OR **on a popup modal**, whichever works faster for you.
3. For the `upload a CSV file` text, ignore it as this will be addressed in [a separate issue](https://github.com/Automattic/wp-calypso/issues/78365). 

image

image

### PR DESCRIPTION
**Pull request by JuanLucha**
Closes https://github.com/Automattic/wp-calypso/issues/78363

## Proposed Changes

This PR adds the Add Subscribers button in the top right corner of the Subscribers Page. Clicking on that button will show a popup to enable the user to introduce subscriber emails.

## Testing Instructions

1. Apply this PR and start the application.
2. go to `http://calypso.localhost:3000/subscribers/{the-domain-of-your-site}`. You should see the Add Subscribers button:

3. Click the button. You should see the form to enter new subscriber emails.

4. Enter some subscriber emails and click the "Add subscribers" button in the form. You should see a confirmation toaster.

**Note:** The operation is asynchronous, so we cannot update the view now.

### CODE REVIEW

**Review by phcp — COMMENTED** [review]
Great job @JuanLucha! Code looks good and it's working as expected. Just noticed that the button style is different from the design on Figma (h8tMpJlCqNFemEerU9owHI-fi-1880_61261) and that the modal is displaying an extra title "Let’s add your first subscribers".

**Comment by TimBroddin** [comment]
I tested and it works great. However, in the design the button is blue, and here it's the pink/reddish.

I've taken a look at the [Calypso components](https://wpcalypso.wordpress.com/devdocs/design/button), and blue isn't an option. Because I knew I had seen a blue button somewhere I did some digging and we have one in the [subscription portal](https://github.com/Automattic/wp-calypso/blob/2e69b9dbb8c9a772016d04075edef80021fb1022/client/landing/subscriptions/components/user-settings/user-settings.tsx#L85-L86). But if we want to use more blue buttons, we might want to sync with @crisbusquets and make this a "style" of the <Button /> component we can control with a prop.

**Comment by yansern** [comment]
We'll leave the button's primary color agnostic as we should be inheriting it from the user's preferred color scheme as configurable in https://wordpress.com/me/account.

**Comment by JuanLucha** [comment]
@TimBroddin , what @yansern says is true: the button is "primary" color, so it depends on the color the user selects.

**Comment by TimBroddin** [comment]
> @TimBroddin , what @yansern says is true: the button is "primary" color, so it depends on the color the user selects.

I agree, but in no color theme is this the type of blue that is in the design ☹️

**Comment by provenself** [comment]
Hi! Two questions/suggestions from a copy standpoint:

1. Do we need the plus sign on the `Add Subscribers` button? My current Calypso view button doesn't have it, and it looks cleaner (IMO).
Screen Shot 2023-06-20 at 8 06 12 AM

2. Per [@phcp's comment](https://github.com/Automattic/wp-calypso/pull/78403#pullrequestreview-1486867937) about the modal copy, it does seem a little repetitive: the phrase "Add subscribers" appears on both the eyebrow and the button. Also, unless that modal will appear only for a user to input subscribers for the very first time, we may want to remove the word "first." A possible fix could be:

246886918-01e65e0d-b6ca-4de3-8a3a-b79c435b97cb (1)


Happy to discuss other options as well! And apologies if all of this has already been discussed and agreed upon.

**Review by phcp — APPROVED** [review]
PR looks good and works as expected, for me it's good to go. But feel free to continue the discussion on [@provenself's comment](https://github.com/Automattic/wp-calypso/pull/78403#issuecomment-1599007141) and implement possible changes on this PR or on a new one.

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/8059510

Thank you @JuanLucha for including a screenshot in the description! This is really helpful for our translators.

**Comment by crisbusquets** [comment]
I know this is merged, but I'm back from AFK today 🙏🏼

> We'll leave the button's primary color agnostic as we should be inheriting it from the user's preferred color scheme.

+1 @yansern. The button color should follow the user's preferred color scheme. Apologies for the confusion with the blue I used.

> Per https://github.com/Automattic/wp-calypso/pull/78403#pullrequestreview-1486867937 about the modal copy, it does seem a little repetitive: the phrase "Add subscribers" appears on both the eyebrow and the button. Also, unless that modal will appear only for a user to input subscribers for the very first time, we may want to remove the word "first." A possible fix could be:

@provenself I'm working on the modal. We have lots of different modals and we (the design team) are trying to find the right one to use. cc/ @yansern

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/8059510).

**Pull request merged**
