### PR TITLE
Codemods: sort imports

### PR DESCRIPTION
**Pull request by samouri**
While [running a codemod](https://github.com/Automattic/wp-calypso/pull/18069) to convert all of our `React.PropTypes` to be from `prop-types` I noticed that our custom external/internal blocks are being mangled.

This PR introduces a new codemod that sorts the import declarations into internal/external groupings.  My hope is that this can make using codemods easier

It can turn something like:
```js
import React from 'react';
import classnames from 'classnames';
import page from 'page';
/** @format */
/**
 * External Dependencies */
import PropTypes from 'prop-types';
import qs from 'qs';
import { get, defer } from 'lodash';

/**
 * Internal dependencies
 */
import { getCurrentUser } from 'state/current-user/select'
import Gridicon from 'gridicons';
```

Into: 

```js
/** @format */
/**
 * External dependencies
 */
import React from 'react';
import classnames from 'classnames';
import page from 'page';
import PropTypes from 'prop-types';
import qs from 'qs';
import { get, defer } from 'lodash';
import Gridicon from 'gridicons';

/**
 * Internal dependencies
 */
import { getCurrentUser } from 'state/current-user/select';
```

cc @gziolo who was the first one i've heard to have this idea

### CODE REVIEW

**Comment by samouri** [comment]
Open Question: does anybody know how to make jscodeshift wrap lines?

**Comment by samouri** [comment]
Heres a sample of this codemod in action: https://github.com/Automattic/wp-calypso/pull/18071

**Comment by samouri** [comment]
ToDo:
- [ ] remove excess extra lines that have appeared. not sure whats causing this considering i created a function to strip them
- [ ] sort the rows.

**Comment by samouri** [comment]
> remove excess extra lines that have appeared. not sure whats causing this considering i created a function to strip them

I'm not sure if this is possible. I think it has something to do with how `recast` attaches newlines to blocks.  The issue fixes itself when this codemod is run twice.  It will probably require a lot more work to work out, and it could be worth merging even before then if we deem this useful enough as-is.

**Comment by dmsnell** [comment]
> remove excess extra lines that have appeared. not sure whats causing this considering i created a function to strip them

@samouri we've all dealt with this and yeah it's from `recast`. My approach to resolve it was just manually going through and removing them by hand. For my workflow it was easy. Pro-tip: if you are using PhpStorm/WebStorm you can compare your current branch against **master** and have it open all changed files. Should be quick to scan the top of them and close after necessary edits.

**Comment by samouri** [comment]
@dmsnell what I find strangest is that running this script twice _does_ work. Its painless when compared to manually editing files.  I've added in a note to the codemod explaining that it works best when run twice.

I personally think this is ready for merging. Gave it a pretty good banging with [this pr](https://github.com/Automattic/wp-calypso/pull/18130) that was merged with no issue.

**Comment by samouri** [comment]
had a very easy time successfully using this with: https://github.com/Automattic/wp-calypso/pull/18130.

**Comment by gziolo** [comment]
I'm super excited seeing this PR open. Prettier FTW :)

**Comment by gziolo** [comment]
> what I find strangest is that running this script twice does work. Its painless when compared to manually editing files. I've added in a note to the codemod explaining that it works best when run twice.

Have you tried adding `eslint --fix` call instead of calling script twice? It would have to run on the file that just got modified. This is what I did when I was using codemods with WordPress/Gutenberg codebase :)

**Comment by samouri** [comment]
Thanks for the review @jsnmoon! I'll try to address the first two points, but I've totally given up on the third.

For `@formatted` files you can run prettier to fix it, for everything else we are SOL.

**Pull request merged**
