### PR TITLE
Media Modal: Tone Down Accent Colours

### LINKED ISSUE #30026: Color Schemes: too much accent color (i.e., pink) in the media modal
When selecting multiple images in Media Modal, e.g., for a Tiled Gallery block, there is a lot of accented (pink) UI elements there:

screenshot 2019-01-09 at 13 56 00

The primary call to action there is "Insert", which fully deserves the color, but I'm not so sure about the "Edit" button and the selection markers.

### PR DESCRIPTION
**Pull request by Aurorum**
#### Changes proposed in this Pull Request

This aligns the Media Library/Modal with @drw158's points here: https://github.com/Automattic/wp-calypso/issues/30026#issuecomment-453194803

#### Testing instructions

Visit your Media Library and verify that the "Add New" button is primary, but the edit button is not. Start writing a post and open your Media Library (using an image-type block if writing in Gutenberg) and verify that "Add New" is not primary, but "Insert" is. 

Screenshot 2019-06-10 at 17 15 09

cc @jsnajdr, @flootr 

Fixes #30026

### CODE REVIEW

**Comment by Aurorum** [comment]
I think the easier, better way to do this is to use `getSectionName` instead of `getCurrentRoute`, so I've updated the PR to do that.

**Comment by Aurorum** [comment]
Conflicts resolved :)

**Comment by sixhours** [comment]
@Aurorum I still think this is a good idea, but it needs a more extensive rebase before I can test it. Let me know if you wanted to give that a go. :)

**Comment by Aurorum** [comment]
Thanks @sixhours! I've updated the PR, but I'm not sure if it's still possible to test that the Media Modal in the Post Editor doesn't use the primary button, since I think that the Classic Editor has been retired now. The change should still take effect in the Media Library though.

**Comment by sixhours** [comment]
This is working well! I noticed the Media Library in the post editor does not get quite the same treatment, though the Edit buttons are different:

**Trunk**

Screen Shot 2021-05-14 at 9 57 07 AM

**This PR**

Screen Shot 2021-05-14 at 10 24 40 AM

I'm open to leaving that to a separate PR if it would be easier, your call!

**Review by sixhours — APPROVED** [review]

**Comment by Aurorum** [comment]
I can't really remember if it was intentional, but the original issue in https://github.com/Automattic/wp-calypso/issues/30026#issuecomment-453194803 says this:

> make Edit a default button on both screens
> Add New is primary (pink) in the media lib, but default in the modal

As such, I think that's meant to be the case? Let me know if the direction has changed since then though.

**Comment by sixhours** [comment]
Ohhhh yep, I see that now. I think that makes sense. Shipping this! 🚢

**Pull request merged**
