### PR TITLE
Design Picker: Track the selection of the categories

### PR DESCRIPTION
**Pull request by arthur791004**
Related to pbxlJb-6Hz-p2

## Proposed Changes

* Use the query string parameter for the selected categories
* Track the `Free only` toggle
* Track the selection of categories
* Add the common properies to the event of the big sky button

**Filters**

| Select | Deselect |
| - | - |
| image | image |
| image | image |

**Free Only Filter**

| Select | Deselect |
| - | - |
| image | image |

## Why are these changes being made?

* We want to track the behavior of the category selection

## Testing Instructions

* Create a new site
* On the Goals screen, select any goals
* On the Design Picker screen
  * Select any features
  * Select any subjects
  * Toggle the free-only filter
  * Ensure the track event is sent with the correct properties

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
    - [ ] For UI changes, have we tested the change in various languages (for example, ES, PT, FR, or DE)? The length of text and words vary significantly between languages. 
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Comment by taipeicoder** [comment]
Seems that the `is_filter_included_with_plan_enabled` property is not tracking with the correct value:

https://github.com/user-attachments/assets/ae8113c3-5763-4292-bc01-4ace680c3767

**Comment by arthur791004** [comment]
> Seems that the is_filter_included_with_plan_enabled property is not tracking with the correct value:

I was unsure what's the correct value. The property, `is_filter_included_with_plan_enabled`, is one of the common properties, so I thought it should be the value when the click happened rather than the value after the click. What do you think?

**Comment by taipeicoder** [comment]
> > Seems that the is_filter_included_with_plan_enabled property is not tracking with the correct value:
> 
> I was unsure what's the correct value. The property, `is_filter_included_with_plan_enabled`, is one of the common properties, so I thought it should be the value when the click happened rather than the value after the click. What do you think?

Hmm good point, might be a bit odd that if I wanted to track users that have enabled the toggle, I'd have to use `is_filter_included_with_plan_enabled` = false 😅

**Comment by arthur791004** [comment]
You can use `calypso_design_picker_select_filter` with the `filter_type: included_with_plan` 😆

**Comment by taipeicoder** [comment]
Could you confirm if the `preselected_filters` prop works as intended? I'm seeing empty on my end but I was expecting blog and newsletter 😕

https://github.com/user-attachments/assets/2a82bf06-a7e6-4cc8-8468-4c2f7e940092

**Comment by arthur791004** [comment]
> Could you confirm if the preselected_filters prop works as intended? I'm seeing empty on my end but I was expecting blog and newsletter 😕

It works on my side. Could you help to check again? There may be some problems earlier 🤔

image

**Comment by arthur791004** [comment]
> Could you confirm if the preselected_filters prop works as intended? I'm seeing empty on my end but I was expecting blog and newsletter 😕

Confirmed. The issue happened only when categories were not loaded. Fixed it by [a7a6b14](https://github.com/Automattic/wp-calypso/pull/97161/commits/a7a6b14cbd5ba898a562994ddca225bcd7658dd3)

**Review by fushar — COMMENTED** [review]
Quick question, should we also rename the tracked values `feature:` and `subject:` to `type:` and `topic:` as per https://github.com/Automattic/wp-calypso/pull/97224? Or are those just client-side labeling?

(Just verifying if we won't get confused down the line.)

**Comment by fushar** [comment]
> Quick question, should we also rename the tracked values `feature:` and `subject:` to `type:` and `topic:` as per #97224? Or are those just client-side labeling?

Nevermind, not sure if it's a good idea because the taxonomy itself is still called Theme Feature and Theme Subject in the "backend".

**Comment by taipeicoder** [comment]
There are all theme subjects when it comes to taxonomy. The differentiation is only on the client-side 🙈
Makes sense to me to update them to type/topic instead of feature/subject

**Comment by fushar** [comment]
> There are all theme subjects when it comes to taxonomy. The differentiation is only on the client-side 🙈

The more I know... 😄

**Comment by arthur791004** [comment]
I'd prefer to keep it for now and see the final copy before the release 😆

**Comment by taipeicoder** [comment]
Another thing I noticed is that if no goals are selected, the preselected filter is "Blog" but the event props preselected_filters is empty.

**Comment by arthur791004** [comment]
> Another thing I noticed is that if no goals are selected, the preselected filter is "Blog" but the event props preselected_filters is empty.

Let's fix it via https://github.com/Automattic/dotcom-forge/issues/10101. Does it make senses?

**Comment by taipeicoder** [comment]
Sounds good 👍

**Review by taipeicoder — APPROVED** [review]

**Pull request merged**
