### PR TITLE
Site Settings: Show Site Icon setting even when feature disabled

### PR DESCRIPTION
**Pull request by aduth**
Related: #8235
Related: #7616 

This pull request seeks to display the site icon setting on the site settings screen in all environments.

Site Icon

The behavior of the button varies depending on the feature flag setting for the environment. If the work-in-progress Site Icon feature is disabled (all environments except development), then the button will lead to either the `options-general.php` wp-admin screen for WordPress.com sites, or the Customizer screen for Jetpack sites. This is consistent with the behavior of the edit icon link in the `<Site />` component.

**Testing instructions:**

Verify that the behavior of the button matches expectations for the feature flag setting and depending on whether the site is hosted on WordPress.com or running Jetpack. Because the site icon feature is enabled in development, you may need to restart your running Calypso process with `DISABLE_FEATURES=manage/site-settings/site-icon` to verify the behavior.
1. Navigate to the [site settings screen](http://calypso.localhost:3000/settings/general)
2. Select a site, if prompted
3. Note that the Site Icon setting is displayed
4. Click "Change site icon"
5. Note that...
   - If the feature flag is enabled, nothing happens
   - If the feature flag is disabled, you are redirected to the wp-admin settings screen
6. If redirected in step 5, note that...
   - You are directed to the general options screen for WordPress.com sites (Blavatar)
   - You are directed to the customizer for Jetpack sites, focused to site identity

**Caveats:**

The "return" URL behavior does not work in development because [only WordPress.com is whitelisted as a valid return host](https://github.com/Automattic/jetpack/blob/0ef64c0e8f05a57363c10723ba2b7b906e5c9834/modules/manage.php#L25-L32).

cc @bluefuton re: #7680 . Included in the changes here, I added behavior to check for the presence of a `target` prop on `<Button />` to include the referrer blocking `rel` attributes.

### CODE REVIEW

**Comment by rickybanister** [comment]
Why is the site icon round?

**Comment by aduth** [comment]
Because my site icon is round 😄  Seeing that @mtias mentioned this at https://github.com/Automattic/wp-calypso/pull/8235#issuecomment-251479918 as well, maybe I should change it to avoid confusion 😉

**Comment by rickybanister** [comment]
haha, you got me!

**Comment by aduth** [comment]
Pushed rebase to resolve conflicts.

cc @youknowriad @timmyc for review

**Comment by aduth** [comment]
Heh, failing test goes to show value of added `<Button />` tests (#8742, cc @nitrajka), as I didn't account for duplication of `rel`. Fix coming soon.

**Comment by youknowriad** [comment]
I took this for a spin. It's working well for WP.com website but for jetpack sites, I'm not focused on the "site identity" panel. Not sure if it's related to my Jetpack site or the generated link (I'm on the last version of WP.org and Jetpack)

**Comment by aduth** [comment]
@youknowriad : Does the autofocus work when editing the icon via the existing method, which is to click the ellipsis on the sidebar site card and then the "Edit Icon" link?

Perhaps could be related to escaping of the URL argument, though it works fine in my own testing. Which browser are you using?

Also pushed a rebase to resolve a merge conflict.

**Comment by youknowriad** [comment]
@aduth Yes, it's not working either from the "Edit Icon" link so that's probably related to my website. The code looks 👍 

So for me, it's ok to merge

**Pull request merged**
