### PR TITLE
Purchases: Clarify "Cancel" Copy

### LINKED ISSUE #91760: Purchases > Remove Plan: switch "Cancel" copy to something clearer
### What

In cancelations where we don't show the exit survey, users will see this pop-up:

CleanShot 2024-06-13 at 15 39 15@2x

"Cancel" and "Remove plan" seem to be same action from a user perspective, but they lead to different results. 

### Why

It's confusing and might come across as dark pattern.

### How

Change "Cancel" copy to "Keep the plan"

### PR DESCRIPTION
**Pull request by Aurorum**
Fixes #91760 

## Proposed Changes

* Changes "Cancel" to "Keep plan". 
* Also updates the string to be lower case - I think that all buttons should be (#38231), and I can see that the translation for it already [exists](https://github.com/Automattic/wp-calypso/blob/a900a7934a2be3ef5fe8d78a007e702b820dac38/client/components/marketing-survey/cancel-purchase-form/index.jsx#L646) and is used elsewhere (but let me know if it's intentional!) 

## Why are these changes being made?
See #91760 - the worry is that "Cancel" could be confused as "Cancel [plan]", as opposed to cancelling the action of the dialog. 

## Testing Instructions

Should be just a quick string change for which a code check is sufficient, but you can see this in Calypso by attempting to cancel a plan under Me > Purchases with either WordAds or a custom domain. 

Screenshot 2024-06-26 at 10 15 41

cc @michaeldcain

### CODE REVIEW

**Comment by inaikem** [comment]
@bluefuton 👋 Any suggestions on how we can unblock this PR and get it merged? PAs encountered the issue in the wild today and we'd love to see it fixed. Thanks!

Cc: @supernovia

**Comment by bluefuton** [comment]
Good call @inaikem, and thanks @Aurorum for the fix 🙌   I'll add the 'string freeze' label to ensure the new strings are translated before we ship the changes.

**Comment by bluefuton** [comment]
@Aurorum sorry to ask, but would you remind rebasing the PR for us please? I suspect the code style tests won't pass until we're on the latest `trunk`.

**Comment by Aurorum** [comment]
Of course, no worries - all done!

**Pull request merged**
