### PR TITLE
Hide sidebar when Calypso is viewed from WC apps

### LINKED ISSUE #53982: Hide the navigation sidebar when viewing content from mobile apps
What
Hide the navigation sidebar when the page is viewed from WP or Woo mobile apps, by the sidebar I mean this div: `<div id="secondary" class="layout__secondary" role="navigation">` https://d.pr/i/75tGGU

Why
Similar to the app bar that has been hidden after https://github.com/Automattic/wp-calypso/pull/31830, we would love to avoid allowing users to navigate to pages that are unrelated to the page being requested by the app.

### PR DESCRIPTION
**Pull request by guarani**
#### Changes proposed in this Pull Request

* Using the `isWcMobileApp` utility method introduced in https://github.com/Automattic/wp-calypso/pull/54181, hide the sidebar if Calypso is accessed from the WooCommerce app (WPiOS or WCAndroid).

| Before | After |
| - | - |
| Before: the sidebar is shown | After: the sidebar is hidden |

**Note: This PR depends on https://github.com/Automattic/wp-calypso/pull/54181 which should be merged first.**

#### Testing instructions

* Checkout this branch and run the app locally: `yarn && yarn start`
* Open any Calypso page at http://calypso.localhost:3000 in the browser
* Verify the sidebar is visible as usual
* Change the user agent to that of WCiOS: `Mozilla/5.0 (iPhone; CPU iPhone OS 12_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/16B91 wc-ios/12.1`
* Reload the page and verify that the sidebar is hidden
* Change the user agent to that of WCAndroid: `Mozilla/5.0 (iPhone; CPU iPhone OS 12_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/16B91 wc-android/12.1`
* Reload the page and verify that the sidebar is still hidden

Tip: To change the user agent in Chrome, see below screenshots (taken from https://github.com/Automattic/wp-calypso/pull/31830):

55129228-ab562700-5159-11e9-9a75-d05cfe97b65e
55129288-df314c80-5159-11e9-8278-f14471c9eb2f

Fixes https://github.com/Automattic/wp-calypso/issues/53982

### CODE REVIEW

**Comment by guarani** [comment]
@hichamboushaba, looking at the screenshot above, hiding the sidebar removed some padding from above the heading "Purchases":

Screen Shot 2021-06-30 at 17 00 32

I'm not sure how easy this is to fix, is this something that needs to be addressed?

**Comment by hichamboushaba** [comment]
> I'm not sure how easy this is to fix, is this something that needs to be addressed?

@guarani I don't think it's an issue.

~~I'm just wondering why when using `wp-android` as user agent, the padding is kept, and shouldn't we follow the same logic for hiding the master as when `isWpMobileApp` is true? I'm not familiar with the code, so maybe it won't be that easy, in this case, please don't spend too much time on it 🙂~~

Please ignore the above comment, I need to take more coffee I think 😄, as I was testing in production which hasn't those changes.

**Comment by guarani** [comment]
> Please ignore the above comment, I need to take more coffee I think 😄, as I was testing in production which hasn't those changes.

No worries 😄 

> @guarani I don't think it's an issue.

Ok 👍

**Review by nsakaimbo — APPROVED** [review]
Works as expected - thanks for providing the detailed testing instructions! Also nice work including some unit tests. 👍

**Comment by guarani** [comment]
Thanks again @nsakaimbo!

**Pull request merged**
