### PR TITLE
Reader: add post duration to combined card

### PR DESCRIPTION
**Pull request by bluefuton**
As described in https://github.com/Automattic/wp-calypso/issues/11973, this PR adds post timespan/duration to the combined card:

screen shot 2017-03-10 at 12 09 20

It uses Moment's duration `humanize()`, so the unit should change depending upon the duration. In most cases it'll say "x posts in x minutes".

https://momentjs.com/docs/#/durations/humanize/

Fixes #11793.

### To test

Load your Reader following stream at http://calypso.localhost:3000/, look for a combined card and check that the duration shown looks reasonable.

### CODE REVIEW

**Comment by mtias** [comment]
What is the "in 14 minutes" alluding to here? Is that reading time or that they were published within 14 minutes of each other?

**Comment by bluefuton** [comment]
@mtias - it's the latter ("that they were published within 14 minutes of each other"). We're bundling up consecutive posts and want to give an impression of the time period the posts were published in. 

Is there a clearer wording we could use?

**Comment by bluefuton** [comment]
For context, here's a full combined card:

screen shot 2017-03-10 at 12 33 59

**Comment by mtias** [comment]
Oh, I definitely didn't make that connection at first. Wouldn't something like `2 posts in the last hour` convey the same?

**Comment by blowery** [comment]
Maybe `2 posts over 14 minutes`?

**Comment by bluefuton** [comment]
> Wouldn't something like `2 posts in the last hour` convey the same?

That's definitely clearer, but depending on where you are in the stream, it may not be true :)

If you scroll down a few pages, the newest post in the combined card might be 7 hours old, for example (so I don't think we can use `the last hour`).

**Comment by mtias** [comment]
Do you need any text for that line if the individual posts have their time clearly stated? :)

**Comment by fraying** [comment]
Yes, we need the text. This is a new feature and this helps explain why the posts look different than other posts.

**Comment by shaunandrews** [comment]
e2ea471a-058d-11e7-8725-942151bd7c27

I don't get it. It says "2 posts in 14 minutes," but both posts then say they were published an hour ago?

> This is a new feature and this helps explain why the posts look different than other posts.

I'm not sure it does explain why they look different, it just makes me more confused. Maybe if it said something like "2 posts from this site" it would clear things up more. Adding the time, which raises more questions than is answers, doesn't do much to explain the differences.

**Comment by fraying** [comment]
> It says "2 posts in 14 minutes," but both posts then say they were published an hour ago?

That is a bug. It should say "2 posts in 1 hour." @bluefuton?

The "from this site" part is implied from the fact that both posts are under the site name and avatar in the header.

We're going to issue a call for testing on this on Monday. Let's get it implemented and working and then put it in front of people and collect the feedback. Ok?

**Comment by fraying** [comment]
After discussion with the team, we decided to drop the "in X time" line for now.

**Pull request closed without merging**
