### PR TITLE
Plugins: Update price text to use translate method

### PR DESCRIPTION
**Pull request by WBerredo**
## Proposed Changes

Wrap the price and periodicity into a translate method for better i18n and remove the additional blank space.

 
CleanShot 2023-10-31 at 12 07 05@2x

## Testing Instructions

* Go to the `/plugins` page 
* Check if the prices on the card are displayed the same way as in production.

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

**Review by gavande1 — APPROVED** [review]
LGTM 👍

**Comment by gcsecsey** [comment]
When merging this PR, the CI showed the translation as green, and I don't remember seeing the coverage. If checking now, it shows 94% completion:
CleanShot 2023-11-22 at 15 29 43@2x

The Albanian translation is still missing the price placeholder, and currently only displays "pricing": https://translate.wordpress.com/localci/status/automattic/wp-calypso/update/plugin-card-price-i18n

CleanShot 2023-11-22 at 15 32 26@2x

@dlind1 could you please help with how can we resolve this? Can we update the translation template perhaps to match other languages? Thanks!

**Comment by dlind1** [comment]
@gcsecsey I've updated the Albanian translation, so it should be good now.

**Comment by gcsecsey** [comment]
Thanks a lot @dlind1! 🎉

**Pull request merged**
