### PR TITLE
ToS: Add 'b' tag to instances of productName

### PR DESCRIPTION
**Pull request by jjchrisdiehl**
As noted in https://github.com/Automattic/wp-calypso/issues/95867#issuecomment-2450194400, this change wraps ~any instances~ just the one instance of `productName` suggested by @sirbrillig with a `<b>` tag to bold the product name in our Terms of Service.

~This PR relies on feedback from our i18n team as we hope to avoid retranslating all of these strings.~ i18n said the strings are close enough that Glotpress will pass this change automatically once String Freeze completes.

**Just waiting on the string translation process to be finished, updated @dlind1 in Slack thread below**

Slack p1730851881703629-slack-i18n

Related to #95867 

## Testing Instructions

- Add different products to your cart and go to Checkout
- Scroll down to the Terms of Service section and check that any instance of a product name is bolded

### CODE REVIEW

**Comment by jjchrisdiehl** [comment]
@matt-west I updated two more places that use the `productName` variable alongside the one @sirbrillig mentioned - would these changes suffice?

**Comment by matt-west** [comment]
@jjchrisdiehl I think the first instance of the product name is sufficient. The goal is just to emphasise which product that paragraph refers to, but I don’t think we need to bold all instances of the product name.

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/16996140

Some locales (Hebrew, Japanese) have been temporarily machine-translated due to translator availability. All other translations are usually ready within a few days. Untranslated and machine-translated strings will be sent for translation next Monday and are expected to be completed by the following Friday.

Hi @jjchrisdiehl, could you please edit the description of this PR and add a screenshot for our translators? Ideally it'd include this string: `The promotional period for your {{b}}%(productName)s{{/b}} subscription lasts from %(startDate)s to %(endDate)s.`

Thank you in advance!

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/16996140).

**Pull request merged**
