### PR TITLE
Design first flow: Skip design setup if there's a preselected free theme with style variation

### LINKED ISSUE #83077: Design-first Flow: Skip the design picker step when a free theme has already been pre-selected
## Description

See pbxlJb-4IQ-p2#comment-3145. The design-first flow has a flow where user lands in the design picker with the theme preview opened. This is redundant if the user has already selected a theme from the LoTS. There is no need to show the theme preview again.

Note that currently, the design picker offers colors+fonts styles whereas the LoTS does not.

## Acceptance Criteria

- [x] Define the criteria in which the design-first flow should skip the design picker step.
- [ ] Skip the design picker step when the criteria are fulfilled.

### PR DESCRIPTION
**Pull request by taipeicoder**
## Proposed Changes

This PR updates the design-first flow so that the design picker step is bypassed when the user has preselected a free theme with style variation. As a result, the user will land directly in the Launchpad.

## Testing Instructions

* Head to the logged-out theme showcase.
* Select the category Blog (required).
* Find a free theme and select one of its style variations.
* Select the Pick this Design option.
* Ensure that after the account screen, the user lands directly on the Launchpad instead of the Design Picker.

## Pre-merge Checklist

- [x] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [x] https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md for your changes?
- [x] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [x] Have you checked for TypeScript, React or other console errors?
- [x] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [x] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [x] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

**Comment by miksansegundo** [comment]
We have to add the param `&style_variation` also in the link of the "Pick this design" button shown at the top of the demo site preview:


Screenshot 2566-10-19 at 12 22 10

**Review by miksansegundo — COMMENTED** [review]
It works as expected 👍 when using these buttons: 
  
Screenshot 2566-10-19 at 12 33 56
Screenshot 2566-10-19 at 12 33 45

I found that the chosen style variation is not carried over when selecting a theme that is not in the Blog category. It doesn't look related to this PR.

The bug is caused by using the param `&style` rather than `&style_variation`.

https://github.com/Automattic/wp-calypso/assets/1881481/f681c5d2-a25a-4288-b28c-0124fc9504d9

**Comment by taipeicoder** [comment]
> We have to add the param `&style_variation` also in the link of the "Pick this design" button shown at the top of the demo site preview:
> 
> Screenshot 2566-10-19 at 12 22 10

Good catch 🙂, fixed!

**Comment by taipeicoder** [comment]
> The bug is caused by using the param `&style` rather than `&style_variation`.

I'll follow up on this in another PR, thanks for the thorough testing 🙂

**Review by miksansegundo — APPROVED** [review]
🚀

**Pull request merged**
