### PR TITLE
Plugin Details: Add Pricing info

### LINKED ISSUE #57760: Plugin Details: Add Pricing info
SS 2021-11-08 at 17 24 26

### PR DESCRIPTION
**Pull request by gcsecsey**
#### Changes proposed in this Pull Request

* adds a headless component to fetch product price
* display prices on plugin pages depending on the billing period selected
* allows for buying a plugin with a plan if site is on lower plan.

#### Testing instructions

|Before | After|
|-------|------|
|SS 2021-12-15 at 21 33 22|SS 2021-12-15 at 21 33 00|

**Scenario 1 - billing period selector**
- visit a paid plugin
- period selector should appear
- price should change on period change
- visit a free plugin, period selector should not appear

**Scenario 2 - CTA - low plan (free, personal, premium)**
- visit a paid plugin
- CTA should read "Pay and install" 
- clicking the button should redirect to checkout with the plugin product and business plan. Billing periods depend on your selection
- visit a free plugin
- CTA should read "Upgrade and install" 
- clicking the button should redirect to checkout with a yearly business plan.

**Scenario 3 - CTA - high plan (business, ecom)**
- visit a paid plugin
- CTA should read "Pay and install" 
- clicking the button should redirect to checkout with the plugin product. Billing periods depend on your selection
- visit a free plugin
- CTA should read "Install and activate" 
- clicking the button should redirect plugin installation page.
- 

Fixes #57760

### CODE REVIEW

**Review by gavande1 — APPROVED** [review]
I have tested all scenarios. It works as described. LGTM 🚀

**Comment by gcsecsey** [comment]
Added #59291 to follow up on placeholders.

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/7044705

Thank you @gcsecsey for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/7044705).

**Pull request merged**
