### PR TITLE
JpoSiteType - refactored styles. Removed unused code.

### PR DESCRIPTION
**Pull request by MichaelArestad**
There was a bit of unused code I removed. I also added classes where necessary and targeted classes as much as possible with the except being `svg`. I will do a second PR to fix up the SVGs that will fix that.

Things look slightly different than before. I switched to the font sizes and colors we have standardized since the original site type switcher was coded up.

#### Before
image
image
image
image
image
image

#### After
image
image
image
image
image
image

### CODE REVIEW

**Comment by apeatling** [comment]
@MichaelArestad These are huge PRs, is it possible to split these kind of changes into smaller PRs in the future? I suspect it is one of the reasons this is still sitting around.

**Comment by apeatling** [comment]
Okay, I see what's happening here, you're merging PRs into a branch, not master. I haven't seen that anywhere else in the project, what's the reason for doing it this way?

**Comment by ashleighaxios** [comment]
That's how I was asked to merge early on in this project. Might be a developer preference?

**Comment by MichaelArestad** [comment]
> Okay, I see what's happening here, you're merging PRs into a branch, not master. I haven't seen that anywhere else in the project, what's the reason for doing it this way?

I suspect it was done this way because that is how larger changes like this are worked with plugins like Jetpack. This way it doesn't hold up releases. However, as you know, with Calypso we don't need to do that.

**Comment by apeatling** [comment]
Okay, thanks for the context. I think with Calypso you can just merge to master and use flags to contain it until you're ready to release.

**Comment by tyxla** [comment]
This one's no longer relevant, closing.

**Pull request closed without merging**
