### PR TITLE
Domains: Clean up spacing on mobile

### PR DESCRIPTION
**Pull request by sixhours**
The "Already own a domain" column needs a bit of breathing room on small screens. I've given it 1em right padding to help with that.

### CODE REVIEW

**Comment by sixhours** [comment]
Whoops, this included more commits than I intended...will fix!

**Comment by jsnmoon** [comment]
Oh my gosh, 9 commits for adding a single `padding-right` 😆

**Comment by jsnmoon** [comment]
@sixhours Did you mean to commit [changes to `client/state/data-layer/wpcom/theme-filters/index.js`](https://github.com/Automattic/wp-calypso/commit/25d20b7378b8178b49a191376d48aa572aae7296#diff-6e5e24f6b9422a24278b410438b5687f)?

**Comment by sixhours** [comment]
I did not...I thought only this file was changed as part of this commit? https://github.com/Automattic/wp-calypso/pull/25204/files

**Comment by jsnmoon** [comment]
It looks like it undid a recent change introduced in #25125. I'll give the author a ping.

**Comment by sixhours** [comment]
Eurgh. Maybe ping the person who reviewed the commit? I double-checked the file changes above before I merged, so I don't know why that was in there.

(Next time I mess up a PR I'll just scrap it and start fresh rather than trying to revert within the PR.)

**Comment by jsnmoon** [comment]
We've all experienced git tragedies in the past ;)

**Pull request merged**
