### PR TITLE
composite-checkout: Enable apple pay

### PR DESCRIPTION
**Pull request by sirbrillig**
#### Changes proposed in this Pull Request

Apple Pay has been prepared for a while, but this PR hooks it up to the transactions endpoint so that it can complete purchases.

#### Testing instructions

- Using Mac OS Safari, visit WordPress.com and log in. This is required because once we proxy, you will not be able to log in.
- Sandbox the store.
- Run calypso with `ENABLE_FEATURES=composite-checkout-wpcom npm start`.
- Enable Charles proxy to spoof WordPress.com. This is required because Apple Pay will only work on SSL and on a production domain. The details of how to do this are beyond the scope of this PR. Contact me if you have any issues.
- Using Mac OS Safari, reload WordPress.com and be sure you see the "dev" badge in the lower-right.
- Add a plan to your cart and visit checkout.
- Select "Apple Pay" from the available payment methods.
- Complete the form and press "Pay".
- You must use a real Apple Pay card. But as long as the store is sandboxed, you won't actually be charged.
- Complete the Apple Pay sheet that appears.
- Verify that the payment was successful and that the plan was added to your site.

### CODE REVIEW

**Comment by fditrapani** [comment]
The apple pay option is showing for me but after a couple seconds the button changes and says the payment type is not supported.

image

I confirmed that I was sandboxed and still get the same behaviour.

**Comment by sirbrillig** [comment]
Hm... This can happen if you're visiting http://calypso.localhost instead of https://wordpress.com. Are you sure you're on the latter?

**Comment by fditrapani** [comment]
I was doing it on Calypso.live to avoid all the charles stuffs :D. I'll try setting things up locally and see if it changes.

**Comment by sirbrillig** [comment]
Yeah, I think calypso.live does not have apple pay registered for that domain. :-/

**Comment by fditrapani** [comment]
I got Charles up and ran into the same issue. If we can't find other folks to test, we can merge this, test in production, and make changes at that point.

**Comment by sirbrillig** [comment]
Ok. This works for me so I'm going to merge it and we can troubleshoot any issues in "production" (not actually launched yet). Thanks for trying!

**Pull request merged**
