### PR TITLE
update changes with follow Configuring ESLint

### PR DESCRIPTION
**Pull request by Umangvaghela**
update changes with follow Configuring ESLint:

Reference Link:

**https://eslint.org/docs/user-guide/configuring**

**https://eslint.org/docs/rules/quotes.html**

### CODE REVIEW

**Comment by Umangvaghela** [comment]
Hello @alisterscott 

When you get a chance so review it and if something is missing  in this so give suggestions.

Thanks

**Comment by Umangvaghela** [comment]
@alisterscott  

can you review this PR when you get a time?

Thanks

**Comment by ockham** [comment]
Thanks for your contribution! Could you provide a little more rationale for these changes?

AFAICS, this PR mostly changes the styling of the `.eslintrc.js` file, e.g. by adding single quotes around object keys -- which isn't something that we generally enforce. Other than that, it drops some Jest related configuration, which I'm pretty sure isn't something that we want to do.

**Comment by ockham** [comment]
As discussed on core Slack (and the reasons outlined above), I'm closing this PR.

**Pull request closed without merging**
