### PR TITLE
Pricing page rework: Add features list for Security and Complete bundles

### PR DESCRIPTION
**Pull request by manzoorwanijk**
#### Proposed Changes

* Add features list for Security and Complete bundles
* Fixes the mobile breakpoint. Slack discussion: p1662027454376939-slack-C03RCHNVC0H
* Fixes some stylelints in related `.scss` files

#### Testing Instructions

1. Do any one of these
    * Click on Jetpack Cloud live link below and wait for the redirect to complete, then goto `/pricing?flags=jetpack/pricing-page-rework-v1`
    * or boot up this PR 
        * Run `git fetch && git checkout add/jp-pricing-rework/featured-product-cards`
        * Run `yarn start-jetpack-cloud`
        * Goto [http://jetpack.cloud.localhost:3000/pricing?flags=jetpack/pricing-page-rework-v1](http://jetpack.cloud.localhost:3000/pricing?flags=jetpack/pricing-page-rework-v1)
2. Confirm that featured and simple product cards work fine for both Products and Bundles
3. Confirm that you see the list of features under Security and Complete featured cards
4. Confirm that the data is correct with regards to what is included in which plan
5. Check with smaller screens (<480px)
6. Confirm that you see the foldable "View all features" cards
7. Confirm that the design matches what is defined in Figma

#### Pre-merge Checklist

- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?

Completes: 1202796695664022-as-1202796695664129/f

Screenshot 2022-09-01 at 6 38 30 PM
Screenshot 2022-09-01 at 6 38 46 PM
Screenshot 2022-09-01 at 6 39 04 PM
Screenshot 2022-09-01 at 6 39 13 PM

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - 0-as-1202796695664129

### CODE REVIEW

**Review by andrii-lysenko — APPROVED** [review]
It looks good codewise and works as described. I do see only the issue you pointed out on certain display scale (I assume it's because of the difference in length of inner text). You theoretically could try solve that using a table to have both items look the same, but maybe there are some other ways. I'm ok solving this separately.

I would also suggest waiting a review from design team, but it could be done in complex later.

**Review by elliottprogrammer — APPROVED** [review]
Such nice work @manzoorwanijk!
Looks great to me! 👍

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/7507195

Thank you @manzoorwanijk for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/7507195).

**Pull request merged**
