### PR TITLE
Global Styles: Fix unlock message and upgrade badge logic for GS variations

### PR DESCRIPTION
**Pull request by abotic**
# Fix unlock message and upgrade badge logic for GS variations

Related to:
- https://github.com/Automattic/dotcom-forge/issues/9676
- https://github.com/Automattic/wp-calypso/pull/96617#pullrequestreview-2451132354

## Proposed Changes
- Updated the logic for showing unlock message and upgrade badge based on global styles feature flag state
- Fixed when upgrade badge and message appear for Personal plan users based on feature availability

## Why are these changes being made?
When the global styles feature flag is enabled for Personal plan, users with Personal plan were still seeing the upgrade message and badge for style variations. This fix ensures that the unlock message and upgrade badge are only shown when actually needed based on the user's plan and feature flag state.

## Testing Instructions
1. Open the Calypso live link
2. Navigate to Appearance -> Themes
3. Test with different plan levels and theme tiers per table

| **Theme Type** | **Plan Level** | **Expected Behavior**                               |
|----------------|----------------|---------------------------------------------------|
| Free           | Free           | Show "Upgrade" badge         |
| Free           | Personal       | Show "Included in your plan" message, no badge    |
| Free           | Premium+       | Show "Included in your plan" message, no badge    |
| Personal       | Free           | No message, no badge                              |
| Personal       | Personal       | Show "Included in your plan" message, no badge    |
| Personal       | Premium+       | Show "Included in your plan" message, no badge    |
| Premium        | Free           | No message, no badge     |
| Premium        | Personal       | Show "Included in your plan" message, no badge    |
| Premium        | Premium+       | Show "Included in your plan" message, no badge    |

Examples with different combinations:
Free plan with free theme  | Free plan with personal theme
-------|------
image | image

Personal plan with free theme  | Personal plan with personal+ theme
-------|------
image | image

(Premium and Business logic behaves same as Personal)

## Pre-merge Checklist
- [x] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [x] Have you written new tests for your changes?
- [x] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [x] Have you checked for TypeScript, React or other console errors?
- [x] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [x] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [x] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Comment by rcrdortiz** [comment]
I see the incorrect version when checking a Personal theme on a site on the Free plan. There should be no difference in the theme

https://github.com/user-attachments/assets/410c396b-2fca-4724-9571-c572c312a7e7

 detail page between a Personal and Premium theme when on a site that has a free plan.

**Review by rcrdortiz — CHANGES_REQUESTED** [review]
When on a free plan, the themes detail page for a Personal and Premium theme should look the same and require upgrading through the main CTA button.

**Comment by abotic** [comment]
> When on a free plan, the themes detail page for a Personal and Premium theme should look the same and require upgrading through the main CTA button.

Thanks for taking a look @rcrdortiz ,

I've changed the logic behind free tier including overall user experience for theme upgrading.
Updated the initial PR description with details and instructions.

**Review by rcrdortiz — APPROVED** [review]
Thanks for addressing the feedback, it works great now! 🚢

**Pull request merged**
