### PR TITLE
Update/remove monthly plan pricing test

### PR DESCRIPTION
**Pull request by lucasartoni**
removes test as https://github.com/Automattic/wp-calypso/pull/2456

### CODE REVIEW

**Comment by breezyskies** [comment]
Tested and works as expected, but needs a dev review since this touches a lot of plans code.

**Comment by lucasartoni** [comment]
hey @klimeryk can you help me with the review of this? :)

**Comment by klimeryk** [comment]
@lucasartoni: thanks for the ping. I went ahead and fixed up the code a little. There were some changes in the `client/components/plans/plan-price/index.jsx` file since this test was added, so just reverting the changes is not enough, because we'd lose some of the new modifications (and introduce some unused variables, etc). Including the improved (through A/B testing, I suppose :)) copy for the discounted price (`due today when you upgrade`).
I've rebase the commits and the code should be fine now - if you (or Brie) could test again that'd be great :)

**Comment by lucasartoni** [comment]
@apeatling should I put this on hold, after the recent discussions regarding deploying the variation instead of reverting to yearly prices only?

**Comment by apeatling** [comment]
@lucasartoni Yes please, let's leave it so we can switch it on.

**Comment by klimeryk** [comment]
@lucasartoni - in this case maybe it's worth closing this PR? We can keep the branch for the time being, in case we wanted to revert the changes in the end.

**Pull request closed without merging**
