### PR TITLE
Full Site Editing: render template parts on all site's pages

### PR DESCRIPTION
**Pull request by vindl**
#### Changes proposed in this Pull Request

paAmJe-AI-p2

This removes our page hijacking and delegates header and footer override
functionality to themes, which allows us to override those section for
all of site's pages, not just static ones.

It also removes template data population from the plugin, and delegates
that responsibility to themes. The added benefit of this is that this data
population will work seamlessly on Dotcom too, avoiding the need to rely
on Headstart to provide it during site creation.

#### Testing instructions

1. This PR depends on the following Modern Business update: https://github.com/Automattic/themes/pull/1062
2. Assuming you'll be using local Gutenberg Docker dev environment, you'll need to map both the plugin and the theme folder in volumes (replace with your actual paths to Calypso and Themes repo):
      - `.../wp-calypso/apps/full-site-editing/full-site-editing-plugin:/var/www/html/wp-content/plugins/full-site-editing-plugin`
      - `.../themes/modern-business:/var/www/html/wp-content/themes/modern-business`
3. Restart your Docker containers for the above changes to take effect.
4. Delete all of the previously created Template and Template Parts CPT posts.
5. Activate Modern Business theme and verify that it has populated the template data correctly.
6. Check that everything works as expected while rending and editing some sample page.
7. Verify that header and footer are also rendered on dynamic pages.
8. Switch to Twenty Nineteen.
9. Since this theme doesn't support FSE, you should see the default header and footer, and no ability to edit them in the Editor.
10. Switch back to Modern Business.
11. Disable Full Site Editing plugin.
12. Verify that the theme still works fine without it. It should fall back to Twenty Nineteen defaults, and FSE functionality will no longer be available while editing.

Effectively, the themes now declare FSE support by inserting the appropriate FSE template data. If everything works out correctly, you should see the following entries for Template and Template Parts.

Screenshot 2019-07-14 at 12 17 27
Screenshot 2019-07-14 at 12 17 50

One thing that has changed compared to previous version is that we are now saving theme specific taxonomy terms. This enables us to have template entries for multiple themes, and have the correct ones pulled in for currently active theme. For example, we could have `elegant-business-header` and `elegant-business-footer` alongside the ones listed above.

This also makes the theme switching flow a little more predictable. Let's say the user activates Modern Business and makes some custom modifications to its header that fit just this theme. After that, they switch to Elegant Business (similarly enhanced for FSE) and it will be provisioned with its default header. I think this is important because old theme's header (with potential custom user modifications) will likely not be suitable structurally or visually for a different theme. If they decide to revert back to Modern Business, they'll get its header again with any custom modifications that they have previously made for it. This seems like a better experience overall than just reverting to Modern Business default header (although we could easily implement that too).

Fixes https://github.com/Automattic/wp-calypso/issues/34560

### CODE REVIEW

**Comment by jeraldjuice** [comment]
I really like this. Kudos for a very clever solution! This also just naturally fixes some of the problems with the original Headstart direction (changing data on theme switch, etc).

In broad terms, I think that we can dry this out a bit more. It would be more ideal to have themes responsible for as little as possible (so, in this case, as close to just the content definition as possible). Would it make sense to move [the functionality surrounding the `after_switch_theme` action](modern-business/inc/fse-template-data.php) back into the FSE plugin, then pass the default template/template part content through a filter(s) which can be overridden by individual themes? (ie, rough example - the modern business theme could just add `get_footer_content`, `get_header_content`, and `get_template_content` to those filters) 

^ I don't have the whole idea fleshed out in my mind, and this would require some creativity to get right and generalize properly (seeing as, in the future, we will probably have more FSE blocks than just header/footer). But, for now, we could probably implement this by just throwing those three actions into filters.

The FSE plugin could also handle adding the `template_part_type` taxonomy named after the theme, as well, based on the name of the theme available in the `after_switch_theme` hook.

I'd like to hear your thoughts. :)

**Comment by vindl** [comment]
Thanks for the feedback @jeraldjuice! That part was bothering me too - namely that we'll have to duplicate this functionality (same code) across all of the themes that want to support FSE in this way. I didn't want to spend more time factoring that out, until we can all agree if we are going to pursue this approach going forward.

> Would it make sense to move the functionality surrounding the after_switch_theme action back into the FSE plugin, then pass the default template/template part content through a filter(s) which can be overridden by individual themes?

I thought about that for a bit, but I'm not sure if it's the best way forward. One thing that I like about current approach is that we can activate the theme prior to FSE plugin being installed and activated, and if we decide to do so later the required data would be already present.. If we made themes dependent on FSE plugin being active for template data population, that would no longer be the case.

So with current setup we can toggle the theme and plugin in any other, and everything should still works as expected.

Probably the best place for these common template functionality would be Gutenberg and ultimately core - that way both the FSE plugin and FSE-supporting themes could rely on it without present duplication.

**Comment by vindl** [comment]
> Probably the best place for this shared template functionality to live would be Gutenberg and ultimately core - that way both the FSE plugin and FSE-supporting themes could rely on it without code duplication.

Another idea that was recently brought up is to just move this code to parent theme so all child themes can reuse it (props @apeatling). This sounds like the best and fastest option to me.

**Comment by shaunandrews** [comment]
After a little trial and error I managed to get this running on my local dev install, however something is wrong.

- The blocks in the content area are offset to the left, breaking the layout and causing some blocks to render off screen.
- The order of the icons in the top bar is wrong, with the add and back buttons reversed.
- The header/footer blocks aren't rendering. The header block in particular mentions something about "support for the "core/group" block".

image

**Comment by vindl** [comment]
@shaunandrews I think you might be running old version of Gutenberg locally - after pulling in from latest master you should rebuild the assets (`npm run build`).

**Comment by shaunandrews** [comment]
> I think you might be running old version of Gutenberg locally

Ah ha, I totally was. I'm still trying to get my head around all the various repos and build environments related to this project. Updating to the latest Gute seemed to fix the rendering issues for the header, but I still see the content mis-alignment for the Portfolio page template.

image

Notice how the block is rendering off screen.

**Comment by noahtallen** [comment]
@shaunandrews There is an existing issue here: #34558 that may be causing that. It's been messing up the width of content in editor. I remember someone testing one of the theme updates and reporting a similar thing for that template

**Comment by noahtallen** [comment]
I tested a bunch of stuff with this PR, and I'm seeing

- ✅Activate Modern Business theme and verify that it has populated the template data correctly.
- ✅Check that everything works as expected while rending and editing some sample page.
- ✅Verify that header and footer are also rendered on dynamic pages. **(looks good on blog posts, 404, and search)**
- ❓Since 2019 doesn't support FSE, you should see the default header and footer, and no ability to edit them in the Editor. **I don't see the header/footer on the page editor, but I still see the ability to edit them in the template/template part editor.**
- ✅Verify that modern business still works fine without FSE. It should fall back to Twenty Nineteen defaults, and FSE functionality will no longer be available while editing.

**Comment by noahtallen** [comment]
If I have FSE deactivated and modern business activated and then switch to the master branch to continue development on something else, I get this error when reactivating FSE: `Fatal error: Cannot declare class A8C_WP_Template_Data_Inserter, because the name is already in use in /var/www/html/wp-content/plugins/full-site-editing-plugin/full-site-editing/utils/class-a8c-wp-template-data-inserter.php on line 11`. I'm guessing this isn't really a bug since it's just conflicting with the new theme definition.

**Comment by gwwar** [comment]
Reserving this comment for more gifs/screens:

Example of FSE header/footer on a dynamic page (recent posts).
dynamic_posts_page

**Comment by mmtr** [comment]
I also tested this on a WP.com Simple Site and can confirm that the FSE data is now automatically populated when switching to the theme 😃 

I'd say we should go ahead with this approach! 🎉 I really love how this delegates the template definitions to the themes.

> Since 2019 doesn't support FSE, you should see the default header and footer, and no ability to edit them in the Editor. **I don't see the header/footer on the page editor, but I still see the ability to edit them in the template/template part editor.**

I think that's the expected behavior @noahtallen 🙂.

**Comment by vindl** [comment]
>  I don't see the header/footer on the page editor, but I still see the ability to edit them in the template/template part editor.

@noahtallen as @mmtr noted this is expected. We will be hiding these sections as soon as we have automatic data population available on Dotcom, so this flow wouldn't be reachable anymore.

**Comment by vindl** [comment]
> If I have FSE deactivated and modern business activated and then switch to the master branch to continue development on something else, I get this error when reactivating FSE: Fatal error: Cannot declare class A8C_WP_Template_Data_Inserter, because the name is already in use in /var/www/html/wp-content/plugins/full-site-editing-plugin/full-site-editing/utils/class-a8c-wp-template-data-inserter.php on line 11. I'm guessing this isn't really a bug since it's just conflicting with the new theme definition.

@noahtallen That's right, master will revert to "old" approach so we'll have both the plugin and the theme trying to declare that class. Once we merge this to master it won't be the problem anymore.

**Comment by noahtallen** [comment]
Nice! Thanks for the clarification!

**Pull request merged**
