### PR TITLE
Signup: Remove the survey step from the get-dot-blog flow

### PR DESCRIPTION
**Pull request by scruffian**
This pull request removes the survey step from the get-dot-blog signup flow. Fixes https://github.com/Automattic/wp-calypso/issues/9020.
   
#### Testing instructions
  
1. Run `git checkout update/get-dot-blog-flow` and start your server, or open a [live branch](https://delphin.live/?branch=update/get-dot-blog-flow)
2. Open the [`Get.blog signup` page](http://calypso.localhost:3000/start/get-dot-blog?domain=scruffiantest.net)
3. Check that you see the theme step, not the survey step.
    
#### Reviews
  
- [x] Code
- [x] Product
   
@Automattic/sdev-feed

### CODE REVIEW

**Comment by gziolo** [comment]
Should we also remove this line https://github.com/Automattic/wp-calypso/blob/74090aeafc6302e1e7fdfb9a0a4cf09a25d8cd36/client/signup/config/step-components.js#L25 and related component?

**Comment by scruffian** [comment]
Good catch @gziolo, updated.

**Comment by gziolo** [comment]
Code looks good 👍

**Comment by gziolo** [comment]
I see errors on JS console when testing under FF, macOS:

screen shot 2016-11-15 at 12 26 08

**Comment by scruffian** [comment]
@gziolo, sorry, you also need to pass the domain to the signup flow. I have updated the testing instructions

**Comment by gziolo** [comment]
Works as advertised with updated testing instructions :)

**Pull request merged**
