### PR TITLE
A4A > Agency Tier: Implement download tier badges

### PR DESCRIPTION
**Pull request by yashwin**
Closes https://github.com/Automattic/automattic-for-agencies-dev/issues/1296

## Proposed Changes

This PR implements download tier badges functionality. 

NOTE: we might have to update the logo

## Why are these changes being made?

* To allow agencies to download their tier badges for all the directories (WordPress.com, WooCommerce, Jetpack & Pressable)

## Testing Instructions

* Open the A4A live link
* Add all four directories to the Partner Directory (/partner-directory/agency-expertise). You don't have to accept it. We are currently not filtering it. This will be done in another PR to make the testing easy. 
* Update your agency tier to **Emerging Partner** using the MC tool > Go to the Agency Tier page & verify the download badges button is not visible on the top right corner of the page.

* Change the agency tier to **Agency Partner** > Refresh the UI and verify the screen looks as shown below. Click the `Download your badges` button > Verify all the directory badges are visible for Agency Partner > Click on all the buttons for individual directories > Verify the zip file gets downloaded > Unzip the file and verify that the files are correct. 

Screenshot 2024-10-23 at 1 51 37 PM

Screenshot 2024-10-23 at 1 51 49 PM

* Change the agency tier to **Pro Agency Partner** > Refresh the UI and verify the screen looks as shown below. Click the `Download your badges` button > Verify all the directory badges are visible for Pro Agency Partner > Click on all the buttons for individual directories > Verify the zip file gets downloaded > Unzip the file and verify that the files are correct. 

Screenshot 2024-10-23 at 1 23 06 PM

* Verify it looks good on all the screen sizes:

iPad-Mini-agencies localhost (1)

iPad-Mini-agencies localhost

iPhone-12-PRO-agencies localhost (9)

iPhone-12-PRO-agencies localhost (10)

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Review by madebynoam — APPROVED** [review]
Looking good, @yashwin!
Just a few small notes:
- On .agency-tier-download-badges-modal__list can we make:
- padding-block-start: 8px; gap: 4px;
- On .agency-tier-download-badges-modal__list a.components-button: 
Can we set it as :
padding: 24px 16px;
gap: 8px;
margin-left: -16px;

So it would look like this:
image

**Comment by yashwin** [comment]
> Looking good, @yashwin! Just a few small notes:

Thanks for the review, @madebynoam!

I have made the changes and also updated the logo:

Screenshot 2024-10-23 at 4 17 33 PM

**Review by tiagonoronha — APPROVED** [review]
Works & looks great! 👍

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/16942455

Some locales (Hebrew, Japanese) have been temporarily machine-translated due to translator availability. All other translations are usually ready within a few days. Untranslated and machine-translated strings will be sent for translation next Monday and are expected to be completed by the following Friday.

Thank you @yashwin for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/16942455).

**Pull request merged**
