### PR TITLE
Stats: Ensure Sparkline Appears when Selected

### LINKED ISSUE #34218: Suggestion: Add hourly stats widget to dashboard sidebar when Stats is selected
It's not immediately apparent where to find the hourly stats widget in the Calypso dashboard. Clicking on the site name near the site switcher reveals it. It may be worthwhile making it visible when clicking on the _Stats_ menu item.

#### Steps to reproduce
1. Starting at URL: https://wordpress.com
2. Open the WordPress.com dashboard for the site.
3. When you click on _Stats_, the hourly stats graph isn't visible.
4. When you click on the site name near the site switcher, the hourly stats graph appears.

Here's a demonstration:

hourly_stats_sidebar

#### What I expected

Arguably, have the hourly stats widget appear when I click on _Stats_ (even if this is in addition to the current trigger/location).

#### What happened instead

It's not immediately apparent how to find the hourly stats widget.

#### Browser / OS version

Not relevant.

#### Context / Source

This was a #user-report in 3710879-hc

### PR DESCRIPTION
**Pull request by Aurorum**
#### Changes proposed in this Pull Request

Ensures the sparkline is visible even when selected in stats.

Also, I'm realising the the 100 value I used for the brightness in #32815 is definitely not ideal, especially when there's a lot of views...it's hard to distinguish between the bars, so I've reduced that to 2.

cc @pauljacobson, @blowery, @flootr, @drw158 

#### Testing instructions

Regardless of colour schemes, ensure the sparkline appears and is visible.

Screenshot 2019-06-24 at 17 18 26

Here was the value with 100 btw, it feels a bit odd.

Screenshot 2019-06-24 at 17 22 44

Fixes #34218

### CODE REVIEW

**Comment by drw158** [comment]
I actually think the solid white version is better. I don't think it's useful to distinguish between extremely small and thin individual lines. I don't use the spark line though.

**Comment by Aurorum** [comment]
Switched back to 100 :+1:

**Comment by lancewillett** [comment]
Needs rebase, and happy to push it from there. 👍

**Comment by Aurorum** [comment]
Done! :)

**Pull request merged**
