### PR TITLE
BBE : WebsiteContent : Several Copy changes

### PR DESCRIPTION
**Pull request by ddc22**
#### Proposed Changes

* Copy changes

### Updates to left sidebar text on website content form

image

#### Modal Changes

image

#### Submit Content Section change

image

#### Testing Instructions
- Go to `/start/do-it-for-me` 
- Go through the flow and complete purchas
- Make sure above changes are visible in the website-content page

#### Pre-merge Checklist

- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?

Fixes Automattic/martech#1144
Fixes Automattic/martech#1145
Fixes Automattic/martech#1223

### CODE REVIEW

**Review by aneeshd16 — COMMENTED** [review]
The changes to the left sidebar and modal look good.

I noticed an issue when testing the feedback section. The entire form switches to the right when the feedback section is expanded. This does not happen in prod right now.

https://user-images.githubusercontent.com/5436027/198263939-6c142e22-cff8-47f0-897a-bd7c061bc8fb.mp4

**Comment by ddc22** [comment]
@aneeshd16 I added a minimum width to the section to fix this.

**Review by aneeshd16 — APPROVED** [review]
LGTM!

The modal width looks a bit large to me. What do you think about reducing the width?
image

**Comment by ddc22** [comment]
Modal, fixed with a max width 
Screenshot 2022-10-28 at 11 03 44 AM

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/7598983

Thank you @jdc91 for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/7598983).

**Pull request merged**
