### PR TITLE
Devdocs: Add Code Playground - Preview of all components. 

### PR DESCRIPTION
**Pull request by enejb**
A new take on #8284 and #23446

screen shot 2018-04-05 at 11 21 37 pm

cc: @MichaelArestad

### CODE REVIEW

**Comment by enejb** [comment]
Adding some sort of inline component playground. 
screen shot 2018-04-10 at 6 54 11 pm

**Comment by scruffian** [comment]
This is looking good to me. I think we should merge it and continue iterating in another PR.

**Comment by MichaelArestad** [comment]
Same. The playground itself is a huge first step.

**Comment by MichaelArestad** [comment]
This is so cool

**Pull request merged**
