### PR TITLE
Jetpack Connect: Remove unused remnants of old plans code

### PR DESCRIPTION
**Pull request by tyxla**
In #47466 we removed a bunch of pre-offer-reset code that was now unused. This PR removes some more of the unused code, mainly related to the old plans pages and components. 

#### Changes proposed in this Pull Request

* Jetpack Connect: Remove unused remnants of old plans code

#### Testing instructions

* Verify nothing we're removing here is actually being used.

### CODE REVIEW

**Review by wp-desktop — DISMISSED** [review]
WordPress Desktop CI Failure for job "wp-desktop-mac".

@tyxla please inspect this job's build steps for breaking changes at [this link](https://circleci.com/gh/Automattic/wp-calypso/955343). For temporal failures, you may try to "Rerun Workflow from Failed".

Please also ensure this branch is rebased off latest Calypso.

**Review by monsieur-z — APPROVED** [review]
Everything looks good to me! There's some overlap with #47474, which explains the conflicts.

**Comment by tyxla** [comment]
> Everything looks good to me! There's some overlap with #47474, which explains the conflicts.

Oh, I totally missed that PR. Glad to see you were already on top of it 🙌  Nice work, too!

I've rebased so this PR removes the **very little** that wasn't covered in the above PR.

@monsieur-z feel free to take another look when you get a chance.

**Comment by monsieur-z** [comment]
> Oh, I totally missed that PR. Glad to see you were already on top of it 🙌 Nice work, too!
> 
> I've rebased so this PR removes the **very little** that wasn't covered in the above PR.
> 
> @monsieur-z feel free to take another look when you get a chance.

Looks like we had the same idea at the same time :) Thanks for completing the work!

**Review by monsieur-z — APPROVED** [review]

**Pull request merged**
