### PR TITLE
Update .editorconfig to show tabs as two spaces

### PR DESCRIPTION
**Pull request by blowery**
This is more like most JS out there and changes how GitHub displays code. See https://github.com/isaacs/github/issues/170#issuecomment-150489692

Refs #558

### CODE REVIEW

**Comment by rralian** [comment]
Well I recently switched to Atom and I can confirm that Atom still honors my personal settings over the repo config.

**Comment by blowery** [comment]
> Well I recently switched to Atom and I can confirm that Atom still honors my personal settings over the repo config.

Yup, same here, with the `editorconfig` plugin enabled too

**Comment by rralian** [comment]
ST3 appears to override my personal settings with this config though. :-(

**Comment by nylen** [comment]
I strongly prefer 4 spaces.  So do others in Slack.  Here is an alternative solution - a browser extension that works with no code changes and won't override personal settings: https://github.com/sindresorhus/github-tab-size

From https://github.com/isaacs/github/issues/170#issuecomment-150492300.

**Comment by aduth** [comment]
:-1: to this change, I personally prefer 4 spaces and use Sublime Text 3, where this configuration would override my personal preferences. I'd prefer a solution that would only affect GitHub previews.

**Comment by chuckreynolds** [comment]
:+1: to  tab = 4 spaces

**Comment by blowery** [comment]
I'm closing this PR as it ends up affecting personal dev environments, which is unacceptable. Extensions can serve the same purpose and limit the scope to github.

**Pull request closed without merging**
