### PR TITLE
Stats: Use Jetpack's support form for disputes

### PR DESCRIPTION
**Pull request by jsnmoon**
WARNING: This change requires D138592-code for Jetpack.com Support Form Prepopulation.

## Proposed Changes

* For Jetpack sites: Changes the commercial status dispute flow from direct emails to Jetpack.com's customer support form.

## Testing Instructions

* Open the Stats purchase page for a commercially classified site (`/stats/purchase/siteId`).
* Ensure that clicking on this opens a tab to the Jetpack.com's support form:
image

* Ensure that the Jetpack.com support form is prepopulated with the appropriate subject, site selection, and message body:

image

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Review by dognose24 — COMMENTED** [review]
Thanks for the improvement, @jsnmoon! Unfortunately, the pre-filled form does not work for my case, even though the subject and message parameters have been appended to the URL. 🤔

截圖 2024-02-18 下午11 54 18

On the other hand, the support form only shows when the user already has a login session to jetpack.com before the redirection.

截圖 2024-02-18 下午11 46 03

**Comment by kangzj** [comment]
It works as described for me with `D138592` applied to a8c themes and jetpack.com sandboxed; however, users wouldn't be able to see the form if they are not logged in which is expected.

> Have a paid product and seeing this note? Be sure to [log into your WordPress.com account](https://wordpress.com/wp-login.php) that you used to purchase the product!

I'm seeing this note on the page if user is not logged in. The dispute ticket is a pre-sales support request. Should we tweak the copy on the support page? I don't know how many of them actually chose PWYW or Free. I only looked into a couple of resolved tickets, the users mostly either chose the free product or haven't done anything yet.

cc @foleynotrose @jos22

**Comment by kangzj** [comment]
Shipped to Odyssey `D138675-code`

**Comment by dognose24** [comment]
> It works as described for me with D138592 applied to a8c themes and jetpack.com sandboxed

Ah, I missed the requirement. It works after applying the Diff. 👍🏼

**Pull request merged**
