### PR TITLE
Improve addQueryArgs

### PR DESCRIPTION
**Pull request by sgomes**
This PR reinstates the work in #37606. After that PR was initially posted, it was suggested that Calypso make use of `@wordpress/url`. However, it turned out that Calypso and Gutenberg have different requirements for query args, and thus can't share the same library without introducing a mandatory, permanent dependency on `qs`.

As such, this PR returns to the initial approach of improving `addQueryArgs` in Calypso.

#### Changes proposed in this Pull Request

* Move `addQueryArgs` to `lib/url`
* Reimplement it using native `URL` functionality
* Add a bunch more tests to cover all URL types

#### Testing instructions

The unit tests should provide some measure of comfort, complemented by the E2E tests.

### CODE REVIEW

**Comment by sgomes** [comment]
Rebased on master to pick up node 12 changes.

**Comment by sgomes** [comment]
Rebased on master.

**Comment by sgomes** [comment]
Rebased on master.

**Review by sirreal — APPROVED** [review]
I've visually reviewed and the changes make sense. The test suite seems to include the previous tests and additional cases.

Thanks!

**Comment by sgomes** [comment]
> I've visually reviewed and the changes make sense. The test suite seems to include the previous tests and additional cases.
> 
> Thanks!

Thank you for the review, @sirreal! 👍

**Pull request merged**
