### PR TITLE
Marketplace: Add category to Plugin page title

### LINKED ISSUE #76010: Marketplace: Each plugin category page should have a distinct page title
Based on the convo in pdh6GB-2M1-p2#comment-3501 when visiting a Plugin category, for example `Bookings` the page title in `<head>` should change to `Booking Plugins for WordPress`.

Image

### PR DESCRIPTION
**Pull request by epeicher**
Fixes https://github.com/Automattic/wp-calypso/issues/76010

## Proposed Changes

* Adds the category to the `document.title` in Plugins screen when there is a category selected

|Before | After|
|-------|------|
|CleanShot 2023-04-28 at 13 16 42@2x | CleanShot 2023-04-28 at 12 33 30@2x |

## Testing Instructions

* Apply this patch
* Navigate to `/plugins` page and select different categories
* Hover over the Tab to see the title of the page
* Confirm it contains the selected category
* Confirm that this works for both logged-in pages and logged-out pages. To test logged-out pages, the browser can be used in Incognito mode.

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [x] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

**Comment by epeicher** [comment]
Additional context can be found here: pdh6GB-2M1-p2#comment-3591

**Review by WBerredo — COMMENTED** [review]
When no category is selected, we see the title as "Plugins Plugins"

CleanShot 2023-04-28 at 14 50 43@2x

---

PS: I was not sure if the PR was already ready for review, left a review anyway

**Comment by epeicher** [comment]
> When no category is selected, we see the title as "Plugins Plugins"
> 
> CleanShot 2023-04-28 at 14 50 43@2x
> 
> PS: I was not sure if the PR was already ready for review, left a review anyway

Thanks for adding the comment! It was not ready yet, but something to address anyway, so 👍

**Review by WBerredo — CHANGES_REQUESTED** [review]
I found an issue when we searched and a category was already selected.

We this happens we don't take into account the category anymore and you can see no category is selected and instead of the category name we display "Search Results".

But the title doesn't change after the search and still displaying the last selected category.


CleanShot 2023-05-02 at 11 25 36@2x

**Comment by epeicher** [comment]
> I found an issue when we searched and a category was already selected.

@WBerredo  Well spotted! I have addressed that issue in 35e35dd

**Review by WBerredo — APPROVED** [review]
LGTM!

PS: The e2e tests are still failing but it doesn't seem related to this change.

**Comment by epeicher** [comment]
> PS: The e2e tests are still failing but it doesn't seem related to this change.

Yes, it seems unrelated but I will try again before deploying

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/7964319

Thank you @epeicher for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/7964319).

**Pull request merged**
