### PR TITLE
Activity log: Expand day when header clicked

### LINKED ISSUE #16104: Activity Log: click day/event block to expand
In order to make the UI more functional, what do you think about making the entire day and event blocks/cards clickable to expand their content?

Right now, they open only if the chevron area is clicked, which is the card default behavior.

image

What are your thoughts on this?

### PR DESCRIPTION
**Pull request by sirreal**
Fixes #16104 

To test:
* https://calypso.live/stats/activity?branch=update/activitylog-day-clickableheader
* Click on a day item to see it expand or collapse

### CODE REVIEW

**Comment by keoshi** [comment]
Works great _but_:

- When the “Rewind to this day” button is clicked, the block changes state (expands and collapses, depending on the previous state).
- Would love to see the same thing on the event blocks too.

🙌 Thanks for doing this!

**Comment by keoshi** [comment]
al-buttons

**Comment by sirreal** [comment]
> When the “Rewind to this day” button is clicked, the block changes state (expands or collapses, depending on the previous state).

Thanks for catching that. Should be fixed now.

> Would love to see the same thing on the event blocks too.

Sure thing! The dropdown dropdown ellipsis menus need a bit of work first to avoid the same problem you saw spotted here, so I'll probably handle that separately.

**Comment by keoshi** [comment]
@sirreal sorry about the ping, just noticed the vertical line near the chevron are is now gone. Is it because we changed it to a `clickableHeader`?

Before:
image


After:
image

Can't understand what specifically is the distinction between all of these: https://wpcalypso.wordpress.com/devdocs/design/foldable-card — let me know and I'll open a new ticket.

**Comment by sirreal** [comment]
I think it's the `summary` property on `FoldableCard`, which is where the button is. When we have no button, there's no summary, and the line is hidden. Whatever is happening is baked into the `FoldableCard` component.

**Comment by sirreal** [comment]
@keoshi Do you think we should propose a change to `FoldableCard` to always include the vertical separator?

**Comment by keoshi** [comment]
@sirreal Either that or have a param that forces the vertical separator, say `verticalSeparator = true`?

**Comment by keoshi** [comment]
I'm slightly wary of changing the `FoldableCard` base looks, especially when we allow the entire card to be clicked so the chevron isn't even that unique when it comes to interaction. But I feel it warrants that tiny visual change. What are your thoughts @jeffgolenski ? Am I being too nitpicky with this?

**Comment by jeffgolenski** [comment]
@keoshi I don't think we need to change the appearance of the foldable card, here. 

So basically in all our mockups we've included that vertical line near the chevron, but currently the foldable card doesn't have that gray vertical line, correct?

I think we've been looking at it so close for so long that it looks weird that it doesn't match our mocks exactly. I'd say let's just keep the same foldablecard styles and we'll see how we feel after using it for a week or two.

**Comment by keoshi** [comment]
@jeffgolenski The `FoldableCard` does have the vertical line, but only if there's a summary on that card, meaning there are elements on the card aligned to the right close to the chevron area.

Sounds good to me!

**Comment by keoshi** [comment]
> The dropdown dropdown ellipsis menus need a bit of work first to avoid the same problem you saw spotted here, so I'll probably handle that separately.

@sirreal Are we ready to add this functionality to the event block? Was it related to https://github.com/Automattic/wp-calypso/pull/16225 ?

**Comment by sirreal** [comment]
@keoshi I opened #16196 to track this specifically. I haven't started on it yet but it's one of the next things I plan to work on.

**Comment by keoshi** [comment]
> opened #16196 to track this specifically

Oops, sorry — hadn't seen that one. Thank you!

**Pull request merged**
