### PR TITLE
FSE: Avoid breaking sites even if Jetpack is unavailable

### LINKED ISSUE #79956: ETK: Disabling Jetpack plugin crash wp-admin.
### Quick summary

I have created a WoA site, and the current ETK version is  3.72793.
Deactivating Jetpack using `wp`, makes wp-admin to crash.

### Steps to reproduce

1. Check ETK is enabled
etk_enabled
2. Disable Jetpack plugin
disable-jetpack
3, Ensure that `/wp-admin` is crashing
fatal_error

( A note here is that this specific site, due to tests, had Jetpack tokens deleted, and thus, the Jetpack connection was not working. I deleted the tokens using: `wp option delete jetpack_private_options` ) 

### What you expected to happen

The `/wp-admin` shouldn't crash.

### What actually happened

The `/wp-admin` crashed

### Impact

All

### Available workarounds?

No and the platform is unusable

### Platform (Simple and/or Atomic)

Atomic

### Logs or notes

```
[28-Jul-2023 06:34:34 UTC] PHP Notice:  Function WP_Scripts::localize was called <strong>incorrectly</strong>. The <code>$l10n</code> parameter must be an array. To pass arbitrary data to scripts, use the <code>wp_add_inline_script()</code> function instead. Please see <a href="https://wordpress.org/documentation/article/debugging-in-wordpress/">Debugging in WordPress</a> for more information. (This message was added in version 5.7.0.) in /wordpress/core/6.2.2/wp-includes/functions.php on line 5865
[28-Jul-2023 06:34:34 UTC] PHP Fatal error:  Uncaught Error: Class "Jetpack_Options" not found in /wordpress/plugins/full-site-editing/3.72793/help-center/class-help-center.php:139
Stack trace:
#0 /wordpress/plugins/full-site-editing/3.72793/help-center/class-help-center.php(120): A8C\FSE\Help_Center->get_current_site()
#1 /wordpress/plugins/full-site-editing/3.72793/help-center/class-help-center.php(306): A8C\FSE\Help_Center->enqueue_script()
#2 /wordpress/core/6.2.2/wp-includes/class-wp-hook.php(308): A8C\FSE\Help_Center->enqueue_wp_admin_scripts('plugins.php')
#3 /wordpress/core/6.2.2/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters(NULL, Array)
#4 /wordpress/core/6.2.2/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#5 /wordpress/core/6.2.2/wp-admin/admin-header.php(118): do_action('admin_enqueue_s...', 'plugins.php')
#6 /wordpress/core/6.2.2/wp-admin/plugins.php(605): require_once('/wordpress/core...')
#7 {main}
  thrown in /wordpress/plugins/full-site-editing/3.72793/help-center/class-help-center.php on line 139

```

### PR DESCRIPTION
**Pull request by obenland**
Fixes #79956, #77573.

Related to #

## Proposed Changes

* Does not load Help Center if not on WPCOM and Jetpack is not active.
* Bails Help Center early if `wpcom_get_site_purchases()` is not available to avoid breaking sites where the function is not available.
* Replaces a reference of Jetpack_Options with a direct options call to avoid breaking sites where the class is not available.
* Updates plugin readme to better reflect the experimental nature of the plugin.

## Testing Instructions

* Follow the instructions under "ETK and Atomic Sites" (PCYsg-ly5-p2) to download the zip build of ETK
* Upload the plugin on a self-hosted site and activate—it should not fatal.
* Upload the plugin on a WoA site and deactivate Jetpack through `_cli`. The site should not fatal.

## Pre-merge Checklist

- [x] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md for your changes?
- [x] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

**Comment by arcangelini** [comment]
Thanks for catching this @obenland 

One thing that is complicated is that all of the endpoints in Help Center are reliant upon Jetpack. They specifically use the `wpcom_json_api_request_as_user()` method. For that reason it may actually be best to not load Help Center if Jetpack is not active. I can add that to the PR and take it from here.

**Comment by arcangelini** [comment]
I added a check for `is_plugin_active( 'jetpack/jetpack.php' )` if ETK is not WPCOM.

Tested in AT and self-hosted site with Jetpack enabled and disabled. No more errors from ETK/HelpCenter.

**Review by arcangelini — APPROVED** [review]
Tested in AT and self-hosted site.
With and without Jetpack.
Code executes properly and logs show no errors.

**Comment by arcangelini** [comment]
Deployed ETK fully

**Comment by obenland** [comment]
Thank you!

**Pull request merged**
