### PR TITLE
Performance Profiler: Remove unused components removed in #95108

### PR DESCRIPTION
**Pull request by p-jackson**
Related to https://github.com/Automattic/wp-calypso/pull/95108

## Proposed Changes

A follow up to https://github.com/Automattic/wp-calypso/pull/95108 which removes the V1 components in favour of the V2 components. This PR removes the now unused components and CSS.

Note that that `<SiteProfilerV2>` component still exists because it's still possible to access the old component depending on the feature flags.

Refactors like this can be hard to read, so I've broken the PR up into more readable commits. This is the main one: https://github.com/Automattic/wp-calypso/commit/6782fd6a937d84ae12a03d1b874996d84d2ac594

Changes:
* Delete old `CoreWebVitalsAccordion`, `CoreWebVitalsDetails`, and `MetricTabBar` components and rename their `V2` variants
* Tidy CSS class names
* Remove the `<MetricScale>` component which is no longer referenced
* Fix a typo in the `metricsThresholds` utility

## Why are these changes being made?

It's better to tidy up dead CSS sooner rather than later.

## Testing Instructions

There should be no changes, a pure refactor.

* Test logged in view at `http://calypso.localhost:3000/sites/performance/philipmjackson76.wpcomstaging.com?filter=all`
* Test logged out view at `http://calypso.localhost:3000/speed-test-tool?url=https://philipmjackson76.wpcomstaging.com`

Compare with Figma Iix1FFHIQdfECIXn5JKT5s-fi-5426_141260

## Screenshots

**Desktop logged in**
desktop logged in Sites _ My WordPress Site _ WordPress_com

**Mobile logged in**
mobile logged in Sites _ My WordPress Site _ WordPress_com

**Desktop logged out**
desktop logged out Speed Test _ WordPress_com

**Mobile logged out**
mobile logged out Speed Test _ WordPress_com

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Review by epeicher — APPROVED** [review]
Thanks for these changes @p-jackson, I have tested them visually and I have not found any regression. Also going through the changes, I have not identified any issues inspecting them visually and using the linters. So this Looks Good To Me :shipit: 

Some screenshots comparing production and dev:

||This branch(left) Production (right) | 
|-------|-------|
|Desktop 1|   CleanShot 2024-10-08 at 12 59 02@2x  |           
|Desktop 2|   CleanShot 2024-10-08 at 12 59 20@2x     |             
|Desktop 3|  CleanShot 2024-10-08 at 12 59 34@2x  |             

||This branch | Production | 
|-------|-------|-------|
|Mobile|    CleanShot 2024-10-08 at 13 07 38@2x  |    CleanShot 2024-10-08 at 13 06 59@2x   |

**Comment by epeicher** [comment]
Unrelated to these changes, I have noticed that there is some padding for small screens (less than 781px). 
CleanShot 2024-10-08 at 13 27 55@2x

@p-jackson, @matt-west, do you think we should remove it?

**Comment by matt-west** [comment]
@epeicher Yep, that padding shouldn't be there.

**Comment by epeicher** [comment]
> Unrelated to these changes, I have noticed that there is some padding for small screens (less than 781px).

I have created this task, but I have found that it does not reproduce it consistently, so I have added Low priority:
- https://github.com/Automattic/dotcom-forge/issues/9342

**Pull request merged**
