### PR TITLE
Signup: Domains: don't run availability checks on .wordpress.com domains

### PR DESCRIPTION
**Pull request by dzver**
To test:
1. Go to domains/add or /start, register domain step
2. Search for something01934.wordpress.com
3. It should not trigger an availability check and errors (something01934.wordpress.com is not a valid domain)

### CODE REVIEW

**Comment by stephanethomas** [comment]
This indeed fixes the signup but it also changes search on the `Domains` page since it disables the error message for `*.wordpress.com`:

screenshot

This message is still displayed for any other invalid domain:

screenshot

I think we should only update the signup and make sure this error message is not displayed since users should be able to register `*.wordpress.com` domains as their free addresses.

**Comment by dzver** [comment]
Yes, indeed, that's what I wanted to happen.

People can get confused and type *.wordpress.com in the domain search context as well, no need to display a red error message.

**Comment by stephanethomas** [comment]
I have mixed feelings about this. The context is a bit different with the `Domains` page. Users are looking to register a custom domain - not to create a new blog. I feel like it makes sense to display this error message in that case. Let's see what @mikeshelton1503 or @breezyskies think of that.

**Comment by mikeshelton1503** [comment]
@velesin and I chatted and I agree that the error message doesn't actually offer much help to a user who enters an invalid domain format. The user learns the same thing by not seeing their domain in the result. The expectation of a search box is that it will return results that are valid, which it does and it's not an "error" when it doesn't return exactly what you entered.

The bigger issue, which is beyond the scope of this PR, is that the domain input needs to be clearer about what should be entered. Also perhaps we can add in some kind of feedback for the user after they search to help them better their results if they have trouble finding what they are looking for. I'll create a separate issue for that.

**Pull request merged**
