### PR TITLE
Introduce Horizontal Scrolling in Sites Dashboard

### PR DESCRIPTION
**Pull request by okmttdhr**
Related to https://github.com/Automattic/dotcom-forge/issues/9694

## Proposed Changes

This PR introduces Horizontal Scrolling in the Sites Dashboard. 

before

https://github.com/user-attachments/assets/60d64241-2ce0-4d47-991f-69dbff8b618c

after

https://github.com/user-attachments/assets/1e255f92-fb71-480b-9685-383953fcc4a4

### Other Notes
- In the mobile view (<960), only the Site Title and Actions are displayed, as seen [here](https://github.com/Automattic/wp-calypso/blob/e12b9c111e396bdfb4ad81bbfabdfe2e785436e0/client/sites/components/sites-dashboard.tsx#L147-L148). This is the same behavior as the current production. I would consider this a valid customization rather than an "override" since it [utilizes](https://github.com/okmttdhr/gutenberg/blob/4651b8235d5220f02b1133266995f32c34fc9122/packages/dataviews/src/dataviews-layouts/index.ts#L85) Core's props.
- Related PRs
	- https://github.com/Automattic/wp-calypso/pull/90842
	- https://github.com/Automattic/wp-calypso/pull/90787
	- https://github.com/Automattic/wp-calypso/pull/90420/
	- https://github.com/Automattic/wp-calypso/pull/90211/

## Why are these changes being made?

To remove unnecessary overrides and align with Core: pbxlJb-6A9-p2#comment-4026, pbxlJb-6DF-p2

## Testing Instructions

* Go to `/sites`.
* Try to break the Site Dashboard's DataView with desktop/mobile views and short/long texts.

## Pre-merge Checklist

- [x] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [x] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [x] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [x] Have you checked for TypeScript, React or other console errors?
- [x] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [x] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [x] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Review by fushar — APPROVED** [review]
Functionality-wise, it works as described and the code changes make sense 👍

**Review by matt-west — APPROVED** [review]
Looks good @okmttdhr!

There’s a slightly awkward width where the table overflows when only the site and actions columns are shown. Maybe we should collapse the left-navigation to just show the icons to avoid this. That feedback isn't relevant to this PR though. 

Screenshot 2024-11-11 at 11 31 09

**Comment by lucasmendes-design** [comment]
> Maybe we should collapse the left-navigation to just show the icons to avoid this. That feedback isn't relevant to this PR though.

+1.

**Review by lucasmendes-design — APPROVED** [review]

**Comment by okmttdhr** [comment]
> There’s a slightly awkward width where the table overflows when only the site and actions columns are shown. Maybe we should collapse the left-navigation to just show the icons to avoid this. That feedback isn't relevant to this PR though.

Thanks for the reviews and feedback! I filed this as a follow-up issue 👍 https://github.com/Automattic/dotcom-forge/issues/9771

**Comment by oandregal** [comment]
I love that we are adding features by removing code :)

Screenshot 2024-11-14 at 13 28 35

**Pull request merged**
