### PR TITLE
Stats: Make UTM Builder modal more accessible

### PR DESCRIPTION
**Pull request by dhasilva**
Related to #https://github.com/Automattic/red-team/issues/77
Closes #https://github.com/Automattic/red-team/issues/77

## Proposed Changes

* Links the form fields to the sidebar descriptions via `aria-describedby` for screenreaders
* Adds a visually hidden entry for the URL with an example
* Makes the EmptyStateAction component keyboard-friendly by allowing focus on tab, changing the border color on focus and allowing trigger on Enter and Space keydown events

## Why are these changes being made?

* A11y improvements

## Testing Instructions

* Navigate to the UTM URL builder modal using only your keyboard
* Activate a screen reader if not done already
* Check that when focusing a field, its description and example from the right side of the modal are spoken
* Check that the first field, the URL, also has a spoken description, but it is not visible

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Review by CGastrell — APPROVED** [review]
LGTM! :shipit:

**Review by kangzj — APPROVED** [review]
Thanks for working on this! Looks great to me 👍

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/17009246

Some locales (Hebrew, Japanese) have been temporarily machine-translated due to translator availability. All other translations are usually ready within a few days. Untranslated and machine-translated strings will be sent for translation next Monday and are expected to be completed by the following Friday.

Hi @dhasilva, could you please edit the description of this PR and add a screenshot for our translators? Ideally it'd include all of the following strings:
- `The full URL of the site or post you want to track.`
- `Example: https://www.my-site.com/2024/11/18/my-post`

Thank you in advance!

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/17009246).

**Pull request merged**
