### PR TITLE
FSE: Match block spacing between page and template editing

### LINKED ISSUE #35257: FSE: Header block spacing is inconsistent
When editing on a page the header block spacing looks like this:

Screen Shot 2019-08-08 at 2 31 53 PM

When I click through and edit the header, the block spacing looks like this:

Screen Shot 2019-08-08 at 2 32 00 PM

Both of these views should have consistent spacing between blocks.

### PR DESCRIPTION
**Pull request by glendaviesnz**
#### Changes proposed in this Pull Request

* Modify the margins of the template blocks in page and template edit views

#### Testing instructions

* Checkout this patch to your FSE test enviroment
* Edit a page and compare the spacing of the header template block in the page edit view with the spacing when editing the header template. The spacing between blocks in both should match. 

**before**

before

**after**

after

Fixes #35257

### CODE REVIEW

**Comment by glendaviesnz** [comment]
@apeatling This is a bit of a compromise. I suspect that the narrower spacing in the page edit view is closer to what we are wanting - but to match this in the template edit view requires setting the block margins to 0px, which causes some nasty UI issues with overlapping blocks and difficulty in selecting blocks to edit as seen below. 

This patch essentially takes the block margins down to the minimum possible without causing overlap/selection issues, and then matches the spacing in the page edit view to this.

overlap-issue

**Comment by glendaviesnz** [comment]
@apeatling Have added a second commit which matches the template edit view with the narrower spacing of the page view, and avoids the block overlap/selection issues by adjusting the margins on hover/selection. 

on-hover

**Comment by Copons** [comment]
I'd rather go with the first approach (e6a734e), which doesn't require an additional workaround that could eventually become hard to maintain.

Also, the largest line spacing is more similar to how the front-end renders it, according to https://github.com/Automattic/wp-calypso/issues/35257#issuecomment-519710024.

**Comment by apeatling** [comment]
Thanks Glen, the second approach is good but I agree may be hard to maintain. The first approach is worrying because the block UI is interfering with the blocks themselves, I need to try this.

**Comment by apeatling** [comment]
I only seem to be able to test the second approach, and I don't think we should move ahead with that.

I think the best approach here is to provide enough space for the block UI between blocks in the header, and then match that between the page edit view, and the header edit view. This will be different to the front end, but that is okay for now.

**Comment by glendaviesnz** [comment]
> The first approach is worrying because the block UI is interfering with the blocks themselves, I need to try this.

@apeatling I have reverted back to the first option. You shouldn't see the block UI interfering with the blocks in this one - the gif with this happening is in a version I didn't commit which wound the template editing block margins right back to 0px to match the header in the page view. The current approach is the one that makes some adjustment on both sides.

**Comment by apeatling** [comment]
Thanks, let me retest :+1:

**Comment by apeatling** [comment]
Looks great :+1:

**Pull request merged**
