### PR TITLE
App Banner: Remove Unnecessary Logic for Activity Log

### PR DESCRIPTION
**Pull request by Aurorum**
#### Changes proposed in this Pull Request

In #26286, @roccotripaldi added a bit of code to prevent the Activity Log display the App Banner. It was necessary then, but it's no longer necessary as the Activity Log has been moved out of stats in #26941. :)

#### Testing instructions

Visit the Activity Log and verify the app banner doesn't appear, but confirm it does in Stats. Information on how to trigger the banner: #16124

Screenshot 2019-07-10 at 22 25 53

Noticed whilst creating #34582

### CODE REVIEW

**Review by roccotripaldi — APPROVED** [review]
Thanks for catching this! Merging shortly...

**Comment by arunsathiya** [comment]
@roccotripaldi Just to check, are we still merging this one?

**Comment by Aurorum** [comment]
Branch is up to date (though I don't think that matters too much here) :)

**Comment by Aurorum** [comment]
This should still be an easy merge, I think.

**Review by sixhours — APPROVED** [review]
LGTM!

**Comment by sixhours** [comment]
@Aurorum Can you try a rebase against trunk / force push? That should resolve the "Protect Trunk Branch" check and let me run the other unit tests. Thank you!

**Comment by Aurorum** [comment]
Done - thanks again for revisiting these @sixhours! :)

**Pull request merged**
