### PR TITLE
Email stats: hide when post was not sent

### LINKED ISSUE #40724: Stats: hide email stats when post wasn't sent as an email
We already hide emails from the list when they weren't sent as an email, but keep showing the tabs if people open the page e.g. via "posts" list directly:

Image

Let's hide the tabs when post wasn't sent as an email:

Image

Alternatively we could keep showing tabs, but indicate somehow that the post wasn't sent as an emai

### PR DESCRIPTION
**Pull request by simison**
Resolves https://github.com/Automattic/jetpack/issues/40724

Depends on https://github.com/Automattic/jetpack/pull/40723 merged and deployed to WP.com.

## Proposed Changes

* Hide email open/click tabs for individual post stats when post wasn't even sent as email.

This is different from Newsletters being disabled for the site entirely; I'll do a follow up PR to hide tabs in that case, too.

Alternatively we could keep showing tabs, but indicate somehow that the post wasn't sent as an email.

Post that wasn't sent as an email

Screenshot 2024-12-23 at 14 08 13

Post that was sent as an email

Screenshot 2024-12-23 at 14 08 38

## Why are these changes being made?

*

## Testing Instructions

* Apply [PR](https://github.com/Automattic/jetpack/pull/40723) at your sandbox
* Create a new post and set "post only" from "newsletter" sidebar (icon in the header) and another post with "email and post" option
* Open stats individual posts view in Calypso at /stats/post/[POST ID]/[SITE ID]
* See how tabs  are hidden for "post only" version

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
    - [ ] For UI changes, have we tested the change in various languages (for example, ES, PT, FR, or DE)? The length of text and words vary significantly between languages. 
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Comment by crisbusquets** [comment]
It works for me!
But I wonder if this could be an entry point for the Newsletter feature 🤔 What do you think, @davemart-in ?

**Comment by simison** [comment]
> But I wonder if this could be an entry point for the Newsletter feature 

This in case they're already using newsletters, but decided to publish individual post as blog post only and skip the email.

What you're referring would be scenario where we hide the tabs when the enire Subscriptions/Newsletters feature is disabled (not possible on simple sites, but on Jetpack sites). In that case I'd lean on still hiding these tabs specifically to stay a bit more logical/consistent with hiding them when post wasn't sent anyway.

**Review by lezama — APPROVED** [review]
code makes sense!

**Comment by simison** [comment]
I'll merge this already; the backend change isn't deployed yet but this is backwards compatible, the tabs just stay visible:

image

**Pull request merged**
