### PR TITLE
Help Center: localize queries

### PR DESCRIPTION
**Pull request by heavyweight**
This PR localizes the queries we use for searching help center articles.
Based on the route where the customer is, we use the appropriate query to show relevant articles when the help center is opened.

For example in italian locale if we open the help center when we are on the plans page we see empty suggestions:
Screenshot 2024-08-21 at 19 54 01
This is because we are searching through the italian support page with query `upgrade plan`.
In this case the search should be with translated query `piano di aggiornamento`. 
It should bring up result is if the customer searches this query in his locale:
Screenshot 2024-08-21 at 19 54 33

Fixed https://github.com/Automattic/dotcom-forge/issues/8844

## Proposed Changes

* Translate queries mapped to routes

## Why are these changes being made?

* In locales other than english we were using english queries to search

## Testing Instructions
- Use PR link
- Switch to locale other than english
- Navigate to routes that are targeted in the `route-to-query-mapping`
- Verify that translated query is used when searching for articles

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/16561535

Some locales (Hebrew, Japanese) have been temporarily machine-translated due to translator availability. All other translations are usually ready within a few days. Untranslated and machine-translated strings will be sent for translation next Monday and are expected to be completed by the following Friday.

Hi @heavyweight, could you please edit the description of this PR and add a screenshot for our translators? Ideally it'd include all of the following strings:
- `statistics`
- `add-ons`
- `backup`
- `themes`
- `manage plugins`
- `plugins`
- `upgrade plan`
- `manage emails`
- `drafted post`
- `scheduled post`
- `drafted pages`
- `scheduled pages`
- `subscription purchases`
- `payment methods`
- `billing history`
- `purchases`
- `privacy`
- `account settings`
- `wordpress apps`
- `my profile`
- `general settings`
- `performance settings`
- `site categories`
- `post tag`
- `podcasting`
- `hosting configuration`
- `media settings`
- `testimonials`
- `feedback form`
- `new post`
- `site spam`
- `crowdsignal`
- `debug bar extender`
- `my sites`
- `conversations`
- `manage subscriptions`
- `reader list`
- `discover blogs`
- `tags`
- `manage sites`
- `marketing tools`
- `connections`
- `social share`
- `business tools`
- `monetize`
- `advertising`
- `import`
- `export`

Thank you in advance!

**Comment by renancarvalho** [comment]
In production, I have changed my preferences to Italian, and I do see suggestions in the Plans page. 🤔 
Basically wordpress.com and live link are the same for me.

**Comment by escapemanuele** [comment]
@renancarvalho you're right, it's because in the search call I still see the query being sent in English 🤔

**Comment by heavyweight** [comment]
This was a placeholder PR for getting the strings translated.
Now it should be good for testing

**Review by escapemanuele — APPROVED** [review]
Looks like a great improvement, bravo! 👏

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/16561535).

**Pull request merged**
