### PR TITLE
Fix typo in logo attribute name

### PR DESCRIPTION
**Pull request by mpkelly**
with a custom icon and not the default globe.**

Open full-site editing e.g. **Dashboard** > **Appearance** > **Editor**. Then click the Help icon in the top right
image
Next, click "Still need help" at the bottom. On the next tab, choose "Email". You should then see your current site. This change corrects a typo on the attribute of the site icon image shown. (I uploaded this blue WP logo; the default is grey)

image

If you inspect the DOM for this element, you should see `aria-hidden` and not `area-hidden` as before. 

Before:

image

It should be enough to review the change. @alshakero will also take a look (thanks!).

### CODE REVIEW

**Review by daledupreez — APPROVED** [review]
This looks good to me!

My one suggestion is to clearly document in the PR how to see this element in action.

I haven't been able to verify that the custom logo works, as I am not sure how to set a site up correctly, but this is a sufficiently small change that I think it's OK to ship. (I did verify the logic still works for the case where `logo?.url` is not present.)

**Comment by mpkelly** [comment]
More details added, @daledupreez. I am unsure how to test this change, though, as changing the code and rebuilding the code in the Calypso mono repo didn't work. At runtime, the Help Centre is pulled in using an iframe. I have asked @alshakero for some help here.

**Comment by daledupreez** [comment]
OK, I was able to get this tested via a somewhat unexpected channel.

### Background: ETK as a vehicle for the Help Center

Part of the trouble with testing this is that while the _code_ for the Help Center lives under `packages/`, the actual vehicle for getting that code loaded depends on where the relevant code is getting loaded. This meant that our client-side tests weren't picking up the modified code, mostly because when we load the Help Center from within the site editor, we're actually loading the scripts from the server via the Editing Tool Kit (ETK) plugin, and we're not pulling the scripts in from the local build of Calypso.

### Testing using a sandboxed system with updated ETK files

After working through some hiccups (which would have been simpler if I had found the docs on this page PCYsg-ly5-p2), I got my system set up to sync the updated ETK build to my development sandbox, and ensured that system was used as my backend. With that in place, the updated code was used, and the correct `aria-hidden` attribute was added.

@mpkelly, as a general FYI, once we get this merged, we're going to need to work through the deployment steps here: PCYsg-mMA-p2

#### Screenshots

Screenshot 2022-07-19 at 14 10 10
Screenshot 2022-07-19 at 14 10 54

### ETK questions

This is most likely for @noahtallen -- are you aware of why this update to `packages/site-picker` was not picked up by our automation as something that would require a new ETK build? I expected a message to be added to the PR, but never saw one.

**Comment by noahtallen** [comment]
> This is most likely for @noahtallen -- are you aware of why this update to packages/site-picker was not picked up by our automation as something that would require a new ETK build? I expected a message to be added to the PR, but never saw one.

Great question! Inspecting [the log](https://teamcity.a8c.com/buildConfiguration/calypso_WPComPlugins_EditorToolKit/8214199?hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandBuildChangesSection=true&showLog=8214199_1094_876&logView=flowAware) for the ETK build, it says that it couldn't find the PR. What I'm guessing happened is that the branch and commits were pushed to GitHub some time before the PR was created. The TeamCity workflows are all triggered based on commit push, so that is when the build was triggered. At that time, since the PR didn't exist, it couldn't find anything to comment on. There's no way to redo the logic when the PR is created without re-running all of the other steps that already completed.

Honestly, we don't run into this issue frequently because PRs are often created by the time the commit's build is finished. Or, any number of subsequent commits to the branch after the PR was created would allow the comment to get posted.

Though this isn't important for the workflow (the comment only serves as a reminder), if you did want to verify, you could rebase on trunk and I would expect the comment to show up.

Looking at the TeamCity build, it does correctly detect that it is a "release build." So you'll have no trouble deploying the change after merging:

Screen Shot 2022-07-19 at 12 54 07 PM


You can also use `install-plugin.sh etk fix/site-logo-alt-text` on your sandbox to quickly test the release there!

**Comment by mpkelly** [comment]
Sorry, all, for the pings - I merged instead of rebased.

**Comment by daledupreez** [comment]
As a follow-up, I also tested on a WordPress.com Simple site by running `install-plugin.sh etk fix/site-logo-alt-text` in my developer sandbox, and then accessing the Help Centre.

We also paired on testing on an Atomic site, which made us realise we needed a rebase. We also discovered that Atomic sites don't get to see the site picker at all! 🙃

**Pull request merged**
