### PR TITLE
composite-checkout: Add credit card payment method to handle Stripe/Ebanx/dLocal

### PR DESCRIPTION
**Pull request by sirbrillig**
#### Changes proposed in this Pull Request

This PR creates a new composite checkout payment method in Calypso which takes the place of the "stripe" credit card payment method bundled with the `composite-checkout` package. The difference is that this payment method includes an optional contact details form that appears if the user unchecks a checkbox that reads "Credit card address is the same as contact details". 

Notably, Brazil and India have a special contact form that is required for those countries, and they also replace the credit card fields themselves since, for those countries, the "Credit card" payment method should use Ebanx and dLocal, respectively, instead of Stripe.

Payment method processing for this new method will be changed in https://github.com/Automattic/wp-calypso/pull/44119

This is part of https://github.com/Automattic/wp-calypso/issues/43812

#### Screenshots

Screen Shot 2020-07-09 at 6 38 51 PM

#### Testing instructions

Even though this replaces the credit card payment method entirely, the behavior should be the same for most users unless Ebanx is available (which should never happen currently since the `CheckoutSystemDecider` blocks Brazillian country codes and I think that we only allow Ebanx if the country code is Brazil).

Therefore, the main testing is just to be sure that paying with a new credit card works the same way as it did previously.

### CODE REVIEW

**Comment by sirbrillig** [comment]
The plan is to keep this UI in its current location, but to only show the checkbox at all if the EBANX payment method is available.

**Comment by nbloomf** [comment]
Results of my testing for specific payment flows. The only buggy one was 3DS+success.

- **Non-3DS, payment failure:** Used a stripe test card triggering a generic decline. Saw the "transaction declined" calypso notification and the form reentered its active state. No unexpected errors or warnings.
- **Non-3DS, payment success:** Used a good stripe test card. Payment succeeded and I was redirected to the quickstart session upsell page as expected. Receipt generated. I do see a "cannot update during an existing state transition" warning, but this appears to be coming from inside the quickstart page.
- **3DS, payment failure:** Used a stripe 3ds-required test card triggering a generic decline. Saw the "transaction declined" calypso notification and the form reentered its active state. No unexpected errors or warnings.
- **3DS, payment success:** I saw similar buggy behavior as in #44119. The 3ds modal displayed as expected. After accepting, the address bar shows `/checkout/offer-quickstart-session/pending/$id/$siteurl`, but rendered on the page is what I can only describe as "wonky checkout". It's stuck in the disabled state and has a white bar in the left like the rest of calypso. The receipt did generate correctly, so I think this is just an issue with the redirect. Here is a screenshot:

Screen Shot 2020-07-29 at 3 02 20 PM

I noticed a couple of things that I think are unrelated and/or already exist.
- If I entered a cardholder name, then deleted it, but filled in the other card fields, clicking on the pay button does nothing. There is an error message on the name field but no notification about missing data or autoscroll to the problem field. Since this is a stripe field I'm not sure what we can do about it.
- The stripe fields remain editable when the rest of the form is in a disabled state. Probably not a huge problem, but inconsistent.

**Comment by nbloomf** [comment]
I tried the 3DS-success case on master and saw the same bug- looks like this is an unrelated regression.

**Comment by sirbrillig** [comment]
> If I entered a cardholder name, then deleted it, but filled in the other card fields, clicking on the pay button does nothing. There is an error message on the name field but no notification about missing data or autoscroll to the problem field. Since this is a stripe field I'm not sure what we can do about it.

The cardholder name field is not a Stripe field. It's our own. We should definitely display an error notification. I'll see if I can add that.

> The stripe fields remain editable when the rest of the form is in a disabled state. Probably not a huge problem, but inconsistent.

Yeah, I noticed that recently too. I think I can fix that too.

> I tried the 3DS-success case on master and saw the same bug- looks like this is an unrelated regression.

Ugh. Thanks for noticing! I see that you've filed this in https://github.com/Automattic/wp-calypso/issues/44541 so we can handle it there.

**Comment by sirbrillig** [comment]
> If I entered a cardholder name, then deleted it, but filled in the other card fields, clicking on the pay button does nothing. There is an error message on the name field but no notification about missing data or autoscroll to the problem field. Since this is a stripe field I'm not sure what we can do about it.

I investigated this some more. It would be nice to display a notice, but I think this is the same situation with the other card fields and I think it's the same as the current fields in production. Was anything about this behavior new, that you can tell?

**Comment by nbloomf** [comment]
> Was anything about this behavior new, that you can tell?

(caveat- I am writing this from memory) I think the main difference is that with composite checkout it's possible that this field will have scrolled out of view by the time the user is clicking the submit button, especially with the extra fields for ebanx. So the behavior is the same, but the context of the behavior is different.

I do think this is an improvement we can make later though- functionally this is great.

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/4163508

Thank you @sirbrillig for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/4163508).

**Pull request merged**
