### PR TITLE
Fix first click does not work when linking existing wpcom account to social

### PR DESCRIPTION
**Pull request by Tug**
This PR updates the login screen to fetch the account type immediately when user is trying to connect to an existing wpcom account with a social (apple, google) account. Doing so will make sure the account type is loaded when [user submits the form](https://github.com/Automattic/wp-calypso/blob/master/client/blocks/login/login-form.jsx#L219).

#### Testing instructions

- Checkout this PR locally and boot http://calypso.localhost:3000/log-in
- Connect with google or apple using an email for which you already have a wpcom account
- You should see the connect screen "We found a WordPress.com account with the email address .... Log in to this account to connect it ..."
- Enter your password and click Log In
- It should log you in immediately

Fixes https://github.com/Automattic/wp-calypso/issues/35904

### CODE REVIEW

**Comment by rachelmcr** [comment]
@tug I tried to test this branch but when I run `npm start` (even on a fresh clone of the repo) it's failing with `SyntaxError: Unexpected token <`. Are you seeing that now or is something odd happening on my end?

**Comment by Tug** [comment]
@rachelmcr I haven't seen this error 🤔 Where exactly is this failing?

Maybe try `nvm install` to make sure you have the proper node version.

**Comment by Tug** [comment]
Note: Login e2e tests are failing, will need to investigate

**Comment by rachelmcr** [comment]
I confirmed I have the proper node version.

It seems to be an issue with gridicons. Everything runs fine up until here, with this failure/stack trace:

```
> run-p -s start-build-if-web start-build-if-desktop

/Users/rachel/Documents/a8c/Calypso/wp-calypso/node_modules/gridicons/svg-sprite/gridicons.svg:1
<svg viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><symbol viewBox="0 0 24 24" id="gridicons-add-image"><g><path d="M23 4v2h-3v3h-2V6h-3V4h3V1h2v3h3zm-8.5 7c.828 0 1.5-.672 1.5-1.5S15.328 8 14.5 8 13 8.672 13 9.5s.672 1.5 1.5 1.5zm3.5 3.234l-.513-.57c-.794-.885-2.18-.885-2.976 0l-.655.73L9 9l-3 3.333V6h7V4H6c-1.105 0-2 .895-2 2v12c0 1.105.895 2 2 2h12c1.105 0 2-.895 2-2v-7h-2v3.234z"/></g></symbol><symbol viewBox="0 0 24 24" id="gridicons-add-outline"><g><path d="M12 4c4.41 0 8 3.59 8 8s-3.59 8-8 8-8-3.59-8-8 3.59-8 8-8m0-2C6.477 2 2 6.477 2 12s4.477 10 10 10 10-4.477 10-10S17.523 2 12 2zm5 9h-4V7h-2v4H7v2h4v4h2v-4h4v-2z"/></g></symbol><symbol viewBox="0 0 24 24" id="gridicons-add"><g><path d="M12 2C6.477 2 2 6.477 2 12s4.477 10 10 10 10-4.477 10-10S17.523 2 12 2zm5 11h-4v4h-2v-4H7v-2h4V7h2v4h4v2z"/></g></symbol><symbol viewBox="0 0 24 24" id="gridicons-align-center"><g><path d="M4 19h16v-2H4v2zm13-6H7v

SyntaxError: Unexpected token <
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.gridicons/svg-sprite/gridicons.svg (/Users/rachel/Documents/a8c/Calypso/wp-calypso/build/webpack:/external "gridicons/svg-sprite/gridicons.svg":1:1)
    at __webpack_require__ (/Users/rachel/Documents/a8c/Calypso/wp-calypso/build/webpack:/webpack/bootstrap:19:1)
    at Object../client/components/gridicon/index.tsx (/Users/rachel/Documents/a8c/Calypso/wp-calypso/build/webpack:/client/components/gridicon/index.tsx:11:1)
    at __webpack_require__ (/Users/rachel/Documents/a8c/Calypso/wp-calypso/build/webpack:/webpack/bootstrap:19:1)
    at Object../client/blocks/login/login-form.jsx (/Users/rachel/Documents/a8c/Calypso/wp-calypso/build/webpack:/client/blocks/login/login-form.jsx:14:1)
    at __webpack_require__ (/Users/rachel/Documents/a8c/Calypso/wp-calypso/build/webpack:/webpack/bootstrap:19:1)
    at Object../client/blocks/login/index.jsx (/Users/rachel/Documents/a8c/Calypso/wp-calypso/build/webpack:/client/blocks/login/index.jsx:42:1)
    at __webpack_require__ (/Users/rachel/Documents/a8c/Calypso/wp-calypso/build/webpack:/webpack/bootstrap:19:1)
    at Object../client/login/wp-login/index.jsx (/Users/rachel/Documents/a8c/Calypso/wp-calypso/build/webpack:/client/login/wp-login/index.jsx:24:1)
```

**Comment by Tug** [comment]
@rachelmcr Thanks a lot for the extra information. Indeed the branch wasn't compiling, sorry about that. I've reverted the problematic changes (commit prehooks was returning an error on that line so I thought this change would fix it but it looks like it did not) it should work now.

**Pull request merged**
