### PR TITLE
SEO Tools: Show notice when module is inactive

### PR DESCRIPTION
**Pull request by vindl**
Shows notice in case SEO Tools module is not active in Jetpack, instead of hiding SEO related sections.

modulemsg

### CODE REVIEW

**Comment by vindl** [comment]
cc @jeherve @roundhill

**Comment by roundhill** [comment]
Code looks good here, I'm also wondering we we could do the same thing as I suggested in #9305 with a link out to the Jetpack settings.

**Comment by vindl** [comment]
@roundhill I've added an `Activate Now` button that's linked to the appropriate Jetpack's dashboard page.

**Comment by roundhill** [comment]
How about we sync up how the copy reads for both messages, so here we could change it to:

`SEO Tools are disabled in Jetpack`

If you're cool with that, go ahead and :shipit:

**Comment by vindl** [comment]
@roundhill Messages synced.

**Pull request merged**
