### PR TITLE
Add Privacy Policy Banner notification

### PR DESCRIPTION
**Pull request by retrofox**
This PR is for testing purpose ...
----------------------

... and its changes shouldn't straight be merged from here. Instead, there is a list of PRs to be reviewed/merged/deployed.

Pull requests

- [x] PrivacyPolicy-TOS: Implement reduxification https://github.com/Automattic/wp-calypso/pull/18975
- [x] PrivacyPolicy-TOS: data-layer https://github.com/Automattic/wp-calypso/pull/18972
- [x] PrivacyPolicy-TOS: add state selector https://github.com/Automattic/wp-calypso/pull/18977
- [x] PrivacyPolicy-TOS: add add query component https://github.com/Automattic/wp-calypso/pull/18978
- [x] PrivacyPolicy-TOS: add PrivacyPolicyBanner component https://github.com/Automattic/wp-calypso/pull/18979
- [x] PrivacyPolicy-TOS: handle new users https://github.com/Automattic/wp-calypso/pull/19629

### CODE REVIEW

**Comment by gwwar** [comment]
cc @Automattic/lannister if y'all are looking for more things to review, @retrofox would appreciate 👀  on the linked reviews in the Summary. (Not this mega-PR which is all of them together).

**Comment by retrofox** [comment]
Yup, the idea is that we should test/review/update these PRs one by one, from the top to bottom. The last one #18979 is useful to understand the whole goal of this implementation.

**Comment by apeatling** [comment]
@retrofox Are you still waiting on this? It would be great to get this merged.

**Comment by retrofox** [comment]
> @retrofox Are you still waiting on this? It would be great to get this merged so we can call it shipped in our update.

Adding small changes, Andy.

**Comment by retrofox** [comment]
Closing is the best option here. Thanks @dmsnell!

**Pull request closed without merging**
