### PR TITLE
Adds undeclared dependencies

### PR DESCRIPTION
**Pull request by scinos**
#### Changes proposed in this Pull Request

Adds undeclared dependencies to package.json.

These dependencies were been flagged by `@yarnpkg/doctor`:

```
➤ YN0000: │ /Users/sergio/src/automattic/wp-calypso/bin/build-metadata.js:2:17: Undeclared dependency on request
➤ YN0000: │ /Users/sergio/src/automattic/wp-calypso/bin/generate-devdocs-search-index.js:13:14: Undeclared dependency on lunr
➤ YN0000: │ /Users/sergio/src/automattic/wp-calypso/bin/generate-gutenboarding-design-thumbnails.js:27:24: Undeclared dependency on capture-website
➤ YN0000: │ /Users/sergio/src/automattic/wp-calypso/bin/generate-gutenboarding-design-thumbnails.js:29:15: Undeclared dependency on sharp
➤ YN0000: │ /Users/sergio/src/automattic/wp-calypso/test/test/helpers/use-nock/index.js:4:1: Undeclared dependency on debug
```

#### Testing instructions

* Run `node ./bin/build-metadata.js` and check it still works. (It generates a file in`./client/components/phone-input/data.js`, and after reformatting it with prettier, it shows lots of changes, but unrelated to having a explicit dependency on `request`).

* Delete `./client/server/devdocs/search-index.js`, run `yarn build-devdocs:search-index` and verify the file is re-created without changes.

* Follow the instructions inside `./bin/generate-gutenboarding-design-thumbnails.js`. Then run `node ./bin/generate-gutenboarding-design-thumbnails.js` and check it generates the files without errors

* Run `DEBUG="calypso:*" yarn test-client client/extensions/woocommerce/state/data-layer/request/test/index.js` and check you get a few `calypso:test:use-nock` lines in the output

#### Questions

* What is `./client/components/phone-input/data.js`? Should we re-generate it? cc @umurkontaci

### CODE REVIEW

**Comment by simison** [comment]
> bin/generate-gutenboarding-design-thumbnails.js:27:24: Undeclared dependency on capture-website
> bin/generate-gutenboarding-design-thumbnails.js:29:15: Undeclared dependency on sharp

For background: I left these deps on purpose out since the script is meant to be pretty temporary and I didn't want to add a penalty of downloading Puppeteer (a bit bigger dependency) for everyone.

Totally ok for me to have them in `package.json` if you don't mind. :-) We'll clean them out a little later (maybe within a month or so).

**Comment by scinos** [comment]
@simison Thanks for looking up for other devs :)

My reasoning for having them in `package.json` for a few reasons:
* Don't risk `capture-website` or `sharp` changing versions and introducing API changes that break our script
* Make static analysis tools like `@yarnpkg/doctor` happy.

I did a quick test with a fresh project and adding those two as dependencies. `yarn` installs them in 11.53 with a cold cache, 9.29s from a warm cache. After installing, the size if `node_modules` is 327Mb.

For reference, our repo installs in 166s/107s and `node_modules` is 1.5Gb.

**Comment by simison** [comment]
Cool, so maybe [`PUPPETEER_SKIP_CHROMIUM_DOWNLOAD` in here](https://github.com/Automattic/wp-calypso/blob/24aac4c888ae136e27ff3090e363ffa2e1b74a29/package.json#L132) still takes effect and doesn't include hundreds of megs of browser?

**Review by simison — APPROVED** [review]
✅ for `bin/generate-gutenboarding-design-thumbnails.js`

I haven't test-run this but I'd consider CI showing up green enough.

**Pull request merged**
