### PR TITLE
Checkout: PayPal not working for logged-out Jetpack purchases

### PR DESCRIPTION
**Pull request by DavidRothstein**
#### Changes proposed in this Pull Request

The ability to make Jetpack purchases for logged-out users was launched a couple weeks ago.  However, PayPal purchases for logged-out users have been broken in that flow since launch.  Users just get an error message if they try to click the "PayPal" button:

Screenshot from 2021-08-11 14-54-41

The problem is that the new user account needs to be created and the new user needs to be logged in **before** starting the PayPal purchase, but nothing does that currently.

The bug appears to be easily fixable just by making some of the same changes that https://github.com/Automattic/wp-calypso/pull/51953 and https://github.com/Automattic/wp-calypso/pull/53894 made to the code for submitting non-PayPal transactions.

#### Testing instructions

The easiest way to test logged-out Jetpack purchases is to start at https://cloud.jetpack.com/pricing as a logged-out user.  Then once you select a product and go into checkout, change `wordpress.com` in the URL in your browser to `calypso.localhost:3000` so you can test this pull request.  Choosing PayPal as the payment method should allow you to proceed and be redirected to the PayPal site, and if you're testing in store sandbox mode (available to Automatticians) you should be able to go all the way through and make a fake PayPal purchase and have your subscription successfully provisioned as well.

I also tested:
- Same as above, but for an already-logged-in user (make sure there are no regressions)
- PayPal purchase for an already-connected Jetpack site (make sure there are no regressions)
- PayPal purchase for a `wordpress.com` site (make sure there are no regressions)

I also tried to test the non-Jetpack registrationless checkout flow, which I don't believe is shown to users anymore (but still seems to be accessible at http://calypso.localhost:3000/start/onboarding-registrationless).  However, this flow was broken for both credit card and PayPal purchases before and after this pull request.  This pull request did seem to have the effect of making the error shown for a PayPal purchase be the same as the error shown for a credit card purchase, though.

### CODE REVIEW

**Review by sirbrillig — APPROVED** [review]
Tested and it works as described! I'm able to hit the PayPal site after clicking to complete the purchase rather than receiving an error. Thanks for noticing this!

**Comment by rcanepa** [comment]
I'm probably doing something wrong, but after I confirm the purchase on the PayPal site, I see this:

image

I'm using Chrome in incognito mode and trying with my real credit card and a fake one using my sandbox. In every case, a WP.com was created.

**Comment by sirbrillig** [comment]
🤔  That's interesting. I didn't actually try completing a payment in my test. That error message implies that the wp.com log-in cookie is not set before redirecting to PayPal so that when you return, it doesn't know who to assign the purchase to. That's a very bad bug because I think it means that the user would have paid but the product would not be provisioned (I bet if you check, you'll see that PayPal charged you for those purchases).

**Comment by rcanepa** [comment]
> That's a very bad bug because I think it means that the user would have paid but the product would not be provisioned (I bet if you check, you'll see that PayPal charged you for those purchases).

Surprisingly, I was not charged for those purchases, which makes me think that something else is going on. I'll do some additional testing.

**Comment by rcanepa** [comment]
I know what's going on. I saw that error because third-party cookies are disabled by default in incognito mode and without them, the wp.com log-in cookie is never set. The same happened when I tested this on Safari, which also has third-party cookies disabled by default.

After enabling third-party cookies in incognito mode, everything worked as expected. Sorry for the confusion.

**Review by rcanepa — APPROVED** [review]
LGTM. These changes definitely enable logged-out users to do PayPal purchases.

**Pull request merged**
