### PR TITLE
Jetpack section: remove Scan promo card from Backup's Business upsell page

### PR DESCRIPTION
**Pull request by rcanepa**
#### Changes proposed in this Pull Request

* The Business plan upsell page in Jetpack > Backup shows a promo card for Scan. We no longer need to show that card.

#### Testing instructions

* Prerequisite: Simple site with a Free plan and Simple site with a Personal or Premium plan.
* Run this PR with the `jetpack/features-section` enabled.
* Select your Simple site with a Free plan.
* Go to the Jetpack > Backup section (url: `http://calypso.localhost:3000/backup/[site]`).
* Verify that you see only the Activity Log promo card at the bottom.
* Select your Simple site with a Personal or Premium plan (stay in the same page).
* Verify that there aren't promo cards at the bottom.

Fixes 1179060693083348-as-1180644091306255

##### Free plan
image

##### Personal/Premium plan
image

### CODE REVIEW

**Comment by ChaosExAnima** [comment]
Got the card off-center on desktop. Is that still expected?

Screen Shot 2020-06-19 at 2 40 14 PM

**Comment by rcanepa** [comment]
> Got the card off-center on desktop. Is that still expected?
> 
> Screen Shot 2020-06-19 at 2 40 14 PM

@keoshi, what is expected in this case? This is how the screen behaves in different screen widths.
Kapture 2020-06-19 at 15 50 12

The current behavior is how the `<PromoSection />` component works by default. Should we adapt it when inside the new Jetpack section?

**Comment by ChaosExAnima** [comment]
@rcanepa - I feel that having it be full width when it's just one card makes sense?

**Comment by rcanepa** [comment]
> @rcanepa - I feel that having it be full width when it's just one card makes sense?

Now a promo inside a `<PromoSection />` can fill up the whole width of the section if there is no other card. If there are more, each one is going to take up to `50% - 1em`.

One promo:
Kapture 2020-06-19 at 16 59 55

Two promos:
Kapture 2020-06-19 at 17 06 20

**Comment by keoshi** [comment]
Yes, @rcanepa ! That looks excellent.

**Pull request merged**
