### PR TITLE
Calypso: isolate Reader

### PR DESCRIPTION
**Pull request by samouri**
This is an experiment to see how small `build` can get if we split everything out.
The gameplan is roughly to delete everything unrelated to Reader.

### CODE REVIEW

**Comment by samouri** [comment]
**progress so far**
screen shot 2018-03-21 at 4 39 32 pm

**Comment by samouri** [comment]
@Automattic/team-calypso: Can y'all take a look at this branch and see if theres anything  I missed out on?

Without too much effort I was able to get `build` down to 175 kBGz which is 50% of what its currently at.  I was hoping to be closer to 80% so as-is this isn't great.

After all of the obvious removals, we can more clearly see that there are many small things in the ~4KbGz that we can get rid of.  The most prominent of those are:
1. `url` nodejs lib. we can replace this with just the couple function we need from it. saves 4kb
2. `tracekit`:  `catch-js-errors`uses this in one place, can we async load? We should async load anything stats and reporting related. No reason they should be on the critical render path.
3. `async`: this is a 4kBGz lib we are using 2 functions from in 6 places.  We can replace eachSeries and .parallel with Promise behavior.
4. `react-modal`: we can make a local version of modal `lib/modal` that async-loads react-modal and all of the contents of it since we never start a page with a modal.  This clear at least 5 more kb.
5. another 15 or so would come out if we split the reader components that the state tree drags in into its own bundle
6. flux. only 1kb, but... ;)

**Comment by jsnajdr** [comment]
> url nodejs lib. we can replace this with just the couple function we need from it. saves 4kb

Startup idea:
1. Create polyfills for Node modules like `url` or `path` that are ES6 compatible, publish them and make them the default in Webpack. If you're using just 2 functions out of N, the rest will be tree-shaken away.
2. tbd
3. Profit!

> async: this is a 4kBGz lib we are using 2 functions from in 6 places. We can replace eachSeries and .parallel with Promise behavior.

With this library, we are like 20 versions and 3 years behind the latest thing. Also, there is a variant called `async-es`. Again, tree shaking FTW.

I had a very quick glance at the latest version of async some time ago and I got the impression that it can be useful for Promise-only based programming (no callbacks). That's all I remember :smile:

**Comment by jsnajdr** [comment]
I was able to remove a few more things and the size is now 136kBGz, i.e., 39kBGz less.

I removed:
- Ad Tracking code that depends on `plans/constants`. That can be async loaded if necessary.
- OAuth middleware that checks validity of the OAuth token and redirects to login if needed. OAuth is used by WPDesktop, browser version uses the wpcom proxy and cookies.
- `wpcom-xhr-request` -- used only by WPDesktop/OAuth
- DesignPreview component -- used only by abandoned "Paladin" project
- SitesListNotices -- notices store used to show notices about connecting and disconnecting sites
- the "My Sites" item from the masterbar

Current status:
screen shot 2018-03-23 at 16 17 52

Further opportunities:
- move `localforage` and `react-modal` to `vendor`. It's a good place for them and at least they will be cached better if we can't slim them down.
- consider replacing `is-my-json-valid` with another JSON Schema validation library. We explored this with @lamosty some time ago. `is-my-json-valid` is not small (it includes also `is-property`, which is one huge regexp that enumerates all valid Unicode letters) and not exactly fast either. At least not in our use case, where most validations are run just once and there's no opportunity to amortize the initial compile cost.
- `wpcom-undocumented` is big and not modular. Move the functionality to data layer and distribute to chunks that needs it.
- Node polyfills continue to show as pretty large boxes. `url` and `utils`.

**Comment by blowery** [comment]
* can we ditch localForage entirely and use IDB directly?
* can we async load react-modal? we're not showing modals on boot.
* can we tree shake wpcom-undocumented?
* url parsing: try out https://www.npmjs.com/package/fast-url-parser? use the native URL class in browsers that support it?

**Comment by blowery** [comment]
what's tracekit?

**Comment by blowery** [comment]
photon is bundling it's own debug...?

**Comment by blowery** [comment]
aahhhhhhh

```
wp-calypso@0.17.0 /Users/blowery/src/a8c/wp-calypso
├─┬ babel-core@6.25.0
│ ├─┬ babel-traverse@6.26.0
│ │ └── debug@2.6.9 
│ └── debug@2.2.0  deduped
├─┬ body-parser@1.17.2
│ └── debug@2.6.7 
├── debug@2.2.0 
├─┬ eslint@3.8.1
│ └── debug@2.2.0  deduped
├─┬ eslint-plugin-import@2.9.0
│ ├── debug@2.6.9 
│ ├─┬ eslint-import-resolver-node@0.3.2
│ │ └── debug@2.6.9 
│ └─┬ eslint-module-utils@2.1.1
│   └── debug@2.6.9 
├─┬ express@4.13.3
│ ├── debug@2.2.0  deduped
│ ├─┬ finalhandler@0.4.0
│ │ └── debug@2.2.0  deduped
│ ├─┬ send@0.13.0
│ │ └── debug@2.2.0  deduped
│ └─┬ serve-static@1.10.3
│   └─┬ send@0.13.2
│     └── debug@2.2.0  deduped
├─┬ fsevents@1.1.3
│ └─┬ node-pre-gyp@0.6.39
│   └─┬ tar-pack@3.4.0
│     └── debug@2.6.8 
├─┬ i18n-calypso@1.8.4
│ └── debug@2.2.0  deduped
├─┬ jest@22.0.3
│ └─┬ jest-cli@22.4.3
│   ├─┬ istanbul-api@1.3.1
│   │ └─┬ istanbul-lib-source-maps@1.2.4
│   │   └── debug@3.1.0 
│   ├─┬ istanbul-lib-source-maps@1.2.3
│   │ └── debug@3.1.0 
│   ├─┬ jest-haste-map@22.4.3
│   │ └─┬ sane@2.5.0
│   │   └─┬ micromatch@3.1.10
│   │     └─┬ extglob@2.0.4
│   │       └─┬ expand-brackets@2.1.4
│   │         └── debug@2.6.9 
│   └─┬ jest-runtime@22.4.3
│     └─┬ babel-plugin-istanbul@4.1.5
│       └─┬ test-exclude@4.2.1
│         └─┬ micromatch@3.1.10
│           └─┬ extglob@2.0.4
│             └─┬ expand-brackets@2.1.4
│               └── debug@2.6.9 
├─┬ jscodeshift@0.3.30
│ └─┬ babel-core@5.8.38
│   └── debug@2.2.0  deduped
├─┬ nock@8.0.0
│ └── debug@2.2.0  deduped
├─┬ photon@2.0.1
│ └── debug@3.1.0 
├─┬ react-codemod@4.0.0 (github:reactjs/react-codemod#549dc17530770c4a91bfe3a64c25b420311d568d)
│ └─┬ eslint@2.13.1
│   └── debug@2.2.0  deduped
├─┬ socket.io@1.4.5
│ ├── debug@2.2.0  deduped
│ ├─┬ engine.io@1.6.8
│ │ └── debug@2.2.0  deduped
│ ├─┬ socket.io-adapter@0.4.0
│ │ ├── debug@2.2.0  deduped
│ │ └─┬ socket.io-parser@2.2.2
│ │   └── debug@0.7.4 
│ └─┬ socket.io-parser@2.2.6
│   └── debug@2.2.0  deduped
├─┬ socket.io-client@1.4.5
│ ├── debug@2.2.0  deduped
│ └─┬ engine.io-client@1.6.8
│   └── debug@2.2.0  deduped
├─┬ superagent@2.1.0
│ └── debug@2.2.0  deduped
├─┬ webpack@3.10.0
│ └─┬ watchpack@1.5.0
│   └─┬ chokidar@2.0.2
│     ├─┬ anymatch@2.0.0
│     │ └─┬ micromatch@3.1.10
│     │   └─┬ extglob@2.0.4
│     │     └─┬ expand-brackets@2.1.4
│     │       └── debug@2.6.9 
│     └─┬ braces@2.3.1
│       └─┬ snapdragon@0.8.2
│         └── debug@2.2.0  deduped
├─┬ webpack-bundle-analyzer@2.9.2
│ └─┬ express@4.16.3
│   ├─┬ body-parser@1.18.2
│   │ └── debug@2.6.9  deduped
│   ├── debug@2.6.9 
│   ├─┬ finalhandler@1.1.1
│   │ └── debug@2.6.9  deduped
│   └─┬ send@0.16.2
│     └── debug@2.6.9  deduped
├─┬ wpcom@5.4.1
│ ├── debug@2.2.0  deduped
│ └─┬ wpcom-xhr-request@1.0.0
│   └── debug@2.2.0  deduped
├─┬ wpcom-oauth@0.3.3
│ ├── debug@2.2.0  deduped
│ └─┬ superagent@0.17.0
│   └── debug@0.7.4 
├─┬ wpcom-proxy-request@5.0.0
│ └── debug@2.2.0  deduped
└─┬ wpcom-xhr-request@1.1.1
  └── debug@2.2.0  deduped
```

**Comment by jsnajdr** [comment]
> can we ditch localForage entirely and use IDB directly?

There might be compat issues on Safari, where Indexed DB support is a fairly recent thing -- since version 10. It's OK if we support only "last 2 major releases", but it's close.

Also IE11 supports only a limited subset of the full spec. But we don't do any complex stuff with IDB, so the limited support is likely to be sufficient.

As the IndexedDB API is one of the less user-friendly ones, we should consider using a wrapper library like [Dexie](http://dexie.org/) anyway.

@tofumatt, the author of localforage, now works with us, so let's ask him for his opinion.

**Comment by jsnajdr** [comment]
> can we async load react-modal? we're not showing modals on boot.

It's fairly easy to move `react-modal` away from the `build` chunk. The reason it's there is that it's used by several little modals that are used directly by the `Layout` component:
- `NpsSurveyNotice`
- `TranslatorLauncher`
- `KeyboardShortcutsMenu`
If we async-load these three components (at the moment when they're really rendered), `react-modal` will no longer be bundled in `build`.

But it comes with a downside -- when it's no longer in `build`, `react-modal` will get duplicated in 30+ other chunks that use it. It's 22kB parsed and 5kB gzipped. It'd be interesting to see what Webpack 4 does about this.

At this moment, i think it's a very good idea to move `localforage` and `react-modal` to `vendor`.

**Comment by tofumatt** [comment]
> can we ditch localForage entirely and use IDB directly?

I would not recommend this. The API is quite verbose and unfriendly: it was explicitly designed to be a low-level API used to write higher-level APIs like Dexie and localForage.

We're working to reduce localForage's footprint in future releases. A fair bit of the size is a Promise polyfill which we can totally ditch but keep around to avoid breaking changes. There's a lot of stuff I want to do in future versions 😄

If you want to go IndexedDB-only you could as the data we're storing in calypso is quite basic and the use-case is basic, so many of the edge-case issues with Edge and Safari `< 10.1` we won't hit... but it's true that Safari `10 < 10.1` ships with a very buggy IndexedDB implementation.

I would recommend Dexie over raw IDB anyday. But if we're sticking with key/value type stores and are already using localForage I'd say it's less config and is a bit more backend-agnostic. The size can be addressed and it's probably easier for me to spend a few days cutting a new, lean release (there are a *lot* of low-hanging fruits there) than us migrating database APIs. 😄

**Comment by jsnajdr** [comment]
> can we force everyone to use one version of debug?

The `npm list` tree shows a similar issue with the `babylon` parser and many other Babel components.

Updating the `i18n-calypso` package and its dependencies (`interpolate-components`, `xgettext-js`) will help us deduplicate a few cases like this. And get rid of the `react-addon-create-fragment` package, which is obsolete with the latest React.

**Comment by blowery** [comment]
on url parsing, i wonder how many cases could be handled by https://github.com/Automattic/wp-calypso/pull/23603/files#diff-c53045a53396a0cbca6557fd62e56fc3

doesn't solve building. unsure how it deals with punycode and other esoterica.

**Comment by samouri** [comment]
after our latest improvements and webpack 4, the picture much better.
Down to 104 kbgz. The `vendors~build` bundle is more than twice the size now at 260 kbgz.

Some thoughts on whats left (I recommend running analyze-bundles locally):
- why does `build` have both logged out and logged in experiences in it. i would think we can start with the needed one and then load the other as it becomes needed.
- there is still ~20kbgz from Reader that we could have gotten rid of if Reader were split. so we can pretend the result is really 80.
- why is `localforage` is build when it also appears in vendors?
- why is there still code for `notices`? ideally we could async load all notices code
- why do we need all of `plans` and `product-values`.

**Comment by samouri** [comment]
I'm getting ready to close out the "testing the hypothesis" branch.
ICFY: http://iscalypsofastyet.com/chunkgroups?branch=try/split-everything-test

looks like we were able to shave ~200kb of app code which brought us from ~680kbgz to ~480kbgz for loading Reader. 

`vendors~build` is then the _by far_ biggest chunk weighing in at ~280 kbgz. There are some low-hanging fruit there like async loading parts of `moment`, and `react-modal`, etc.

Closing this for now since I think we learned everything we can from the experiment

**Pull request closed without merging**
