### PR TITLE
Post-migration purchase experience: Add "View sites dashboard" button to migration message screen

### LINKED ISSUE #95404: Post-purchase Migration Experience: Update "We'll take it from here!" step of migration flow
Update the last step of the DIFM flow to send people to the Sites dashboard to monitor the progress of their migration. Clicking the button should take the user to their Sites dashboard (https://wordpress.com/sites).

Figma - nOWSHCjXMpB5sXHthTVdvK-fi-3919_14181

Image

### PR DESCRIPTION
**Pull request by sixhours**
Fixes #95404

## Proposed Changes

* Add a "View Sites dashboard" button at the bottom of the migration message screen during onboarding.
* Update copy for the timing.
* Remove the explore and learn action cards.

Screenshot 2024-10-28 at 3 42 25 PM

## Why are these changes being made?

* Switch to this PR
* Navigate to `/setup/site-migration/migrateMessage?siteId=12345&siteSlug=yourtestsite.wordpress.com&preventTicketCreation=true`
* Note the presence of the button at the bottom of the page
* Clicking the button should take you to `/sites`
* Upon clicking the button, you should see a Tracks event fire in Tracks Vigilante or the console (run `localStorage.debug="calypso:analytics*"` in the console and refresh the page):

Screenshot 2024-10-28 at 1 25 56 PM

## Testing Instructions

*

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/16950038

Some locales (Hebrew, Japanese) have been temporarily machine-translated due to translator availability. All other translations are usually ready within a few days. Untranslated and machine-translated strings will be sent for translation next Monday and are expected to be completed by the following Friday.

Thank you @sixhours for including a screenshot in the description! This is really helpful for our translators.

**Review by fditrapani — APPROVED** [review]
Just tested this out and looks great on my end! Thanks for the updates!

**Review by daledupreez — APPROVED** [review]
Based on inspection, these changes LGTM, and I see that @fditrapani already checked the visuals/behaviour last week.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/16950038).

**Pull request merged**
