### PR TITLE
Add mark as seen tracks

### PR DESCRIPTION
**Pull request by unDemian**
#### Changes proposed in this Pull Request

* Add tracks for mark as seen actions

#### Testing instructions

Code review only.

### CODE REVIEW

**Review by annemirasol — APPROVED** [review]
LGTM!

**Review by bluefuton — CHANGES_REQUESTED** [review]
@unDemian please could we use `recordReaderTracksEvent` action instead? It works the same way as `recordTracksEvent` but adds the user's subscription count to the event props.

`import { recordReaderTracksEvent } from 'calypso/state/reader/analytics/actions';`

See https://github.com/Automattic/wp-calypso/pull/47818 for context.

**Comment by unDemian** [comment]
> @unDemian please could we use recordReaderTracksEvent action instead? It works the same way as recordTracksEvent but adds the user's subscription count to the event props.

Sure thing, thanks for the headsup.

**Comment by unDemian** [comment]
Updated.

**Pull request merged**
