### PR TITLE
Plugins: Updating Jetpack explanatory text

### PR DESCRIPTION
**Pull request by drw158**
This new text better explains what Jetpack is and what it does for the user.

Before:

screen shot 2016-11-23 at 4 50 19 pm

After:

screen shot 2017-02-06 at 2 52 49 pm

### CODE REVIEW

**Comment by obenland** [comment]
IANCP (I am no copy person), but the sentence now had double the "power" (powerful, all of the power). Would the first sentence of its description be helpful here?

> Jetpack simplifies managing WordPress sites by giving you visitor stats, security services, speeding up images, and helping you get more traffic.

**Comment by drw158** [comment]
I don't feel too strongly about it, I just copied the text from a snippet on the Jetpack marketing site.

**Comment by lancewillett** [comment]
What about:

> Whatever sort of site you’re running, Jetpack keeps your site secure and helps you increase traffic.

From https://jetpack.com/

CC @jessefriedman

**Comment by drw158** [comment]
Thanks for reminding me about this. I went ahead and changed it to 

> Jetpack simplifies managing WordPress sites by giving you visitor stats, security services, speeding up images, and helping you get more traffic.

**Pull request merged**
