### PR TITLE
Fix: Deselect Reader menu dropdown sections in navigation

### LINKED ISSUE #50705: Reader: Dropdown Sections should not appear as selected
### Steps to reproduce the behavior

1. Go to `https://wordpress.com/read/conversations`
2. Click on "Lists"

#### What I expected to happen
List section should open without being selected

#### What actually happened
Lists sections opened but it was also selected

Also, refreshing that page should show as selected only the currently open item (in that case only Conversations).

### Context
This reproduces only with nav-unification enabled

props: @davemart-in

### PR DESCRIPTION
**Pull request by BogdanUngureanu**
#### Changes proposed in this Pull Request

Deselect the "Followed Sites", "Lists" and "Tags" dropdown sections. Also, to reduce scope, the styles applied in this PR only affect the Reader navigation. 

#### Testing instructions

* Go to `/read/conversations` using the generated Calypso live link from the comment below
* Click on "Lists", "Followed Sites" and "Tags"
* The  dropdown sections should not be selected
navigation

Fixes #50705

### CODE REVIEW

**Review by mmtr — CHANGES_REQUESTED** [review]
Pretty close, @BogdanUngureanu!

I confirmed the items are not highlighted when expanding a section, but we should highlight them when a submenu is selected.

See for instance how the "Users" menu gets highlighted in "My Sites" after clicking on "Users > All people":

Screen Shot 2021-03-12 at 11 04 12


However, if I do something similar in Reader like clicking on "Lists > Create new list", the Lists menu doesn't get highlighted:

Screen Shot 2021-03-12 at 11 04 21

**Comment by BogdanUngureanu** [comment]
Hey @mmtr, I've updated the PR based on your feedback, the menus are behaving like you suggested. 

However, there are 2 things I should mention: 
1) The foldable behaviour for a selected dropdown is still there even though that's not obvious for a user.
If we want to have the selected menus consistent with the ones like "Users", I think we could disable the folding only for the one that's selected. I'm not sure about this because it would mean changing the current behaviour we have now.

2) When a selected expandable menu is folded, then the selected background is removed.
I think the selected background should be kept, however if we do that a user might not be aware that a folded menu can be expanded. 

Also, if we decide that selected menus should not be folded, it would also handle the 2) remark.

**Comment by mmtr** [comment]
> The foldable behaviour for a selected dropdown is still there even though that's not obvious for a user.
If we want to have the selected menus consistent with the ones like "Users", I think we could disable the folding only for the one that's selected.

This looks reasonable to me. Let's make sure that all sections currently expanded are automatically collapsed when a new one is expanded. For you reference, this is where we handle that for the "My Sites" menu: https://github.com/Automattic/wp-calypso/blob/a831964008cd1f902909f6411eb158dee1852cd2/client/my-sites/sidebar-unified/item.jsx#L41-L44

> I'm not sure about this because it would mean changing the current behaviour we have now.

Very valid concern! It'd be fine as long as we only change that when nav unification is enabled. If nav unification is disabled, we should keep the current behavior.

> When a selected expandable menu is folded, then the selected background is removed. I think the selected background should be kept

I agree, the selected background should indicate which section is currently visible in the screen, so it should change only when a user navigates to a different screen.

> however if we do that a user might not be aware that a folded menu can be expanded.

It should be ok since all these menus have an arrow icon on the right to denote they can be expanded.

**Comment by mmtr** [comment]
On a second thought, please ignore my previous comment. While that's nice to have, it's out of the scope of this PR and can followed up later. Let's keep this PR on fixing only the multiple selected menus.

**Review by mmtr — APPROVED** [review]
This tests well for me 👍

**Comment by mmtr** [comment]
@BogdanUngureanu can you rebase your branch before merging to see if that make the CI builds to pass? Current failures look like they are unrelated, but it's the first time I've seen them, so maybe it was a temporary thing that has been already fixed in `trunk`.

**Pull request merged**
