### PR TITLE
Stepper Onboarding: Fix duplicate calypso_signup_start event

### LINKED ISSUE #95125: calypso_signup_start fires when clicking on Use My Domain
### Details

Context: https://github.com/Automattic/wp-calypso/issues/95106 2

Upon clicking “Use my own domain” option at the Domain Selection step in the Stepper flow, calypso_signup_start event fires but it shouldn’t. This does not happen in the Classic flow.

See the discussion in the linked issue, this should be investigated.

### Checklist

_No response_

### Related

_No response_

### PR DESCRIPTION
**Pull request by agrullon95**
Fixes: https://github.com/Automattic/wp-calypso/issues/95125

## Proposed Changes

* Updates the navigation logic related to `use-my-domain` step.

## Why are these changes being made?

* This fixes the duplicate `calypso_signup_start` event issue. The event duplicated because query params were mistakenly deleted within the onboarding flow. For example, if you load the onboarding flow with `ref` query param, you will notice that the `calypso_signup_start` event is fired and the param will be removed from the URL. When you navigate to another step, the event fires again because the `ref` has changed (in this case its removed).

## Testing Instructions

* Checkout branch or use the live link.
* Navigate to `/setup/onboarding?ref=agTest`.
* Open the Chrome dev tools `Network` tab and filter by `calypso_signup_start`. You may have to refresh the page with the dev tools open to see the event.
* Verify the `ref` param is not removed from the URL when you land on the domains step.
* Click on the `Use a domain I own` link.
* Verify the `calypso_signup_start` event is NOT triggered again. Continue through the flow until checkout to verify you don't see the event triggered again.
* **Testing functionality** - Go back and forth through `domains` -> `use-my-domains` -> `plans` -> checkout to ensure the functionality is still working correctly. Test the browser back button and stepper back button.

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Comment by skim1220** [comment]
@agrullon95 , I just ran a quick test, and `calypso_signup_start` event no longer fires at the domain step. Everything looks good to me! 👍

**Comment by renancarvalho** [comment]
@agrullon95 while navigating on domains and plans, it works really well. Once navigated to checkout and then navigated back, I saw the event being logged again. This is probably because /checkout is not part of stepper if I am not mistaken.

I am not sure if this PR is addressing that as well. Is it?

**Comment by agrullon95** [comment]
@renancarvalho - Yes, the event logged in because the `/checkout` is not part of stepper and we're "loading" stepper when we navigate back.

This PR does not address that.

**Comment by renancarvalho** [comment]
Think this PR is good to go then 👍

**Comment by renancarvalho** [comment]
Pushed a small refactoring on the functions, made them easier to read :)

**Review by renancarvalho — APPROVED** [review]

**Pull request merged**
