### PR TITLE
Sites Management Page: Create a blur background based on site icon for sites thumbnail

### LINKED ISSUE #65942: Sites Management Dashboard: Implement solution to determine thumbnail background color for private and coming soon sites.
Depends on: https://github.com/Automattic/wp-calypso/issues/65170

Implement some utility that will return an appropriate color for thumbnail backgorund for private and coming soon sites.

Done is:
- background color reflects the theme primary color.
- background color reflects the primary color in provided image eg. site icon if theme color not present or theme primary is back or white.

### PR DESCRIPTION
**Pull request by vykes-mac**
#### Proposed Changes

* Currently we are fetching dominant color from the site icon and using it as background color for sites thumbnail. This cause CORS issues when trying to fetch external sites icon. This PR instead solve the issue using a large enough blur of the site icon to get the average color as the backgroud.

#### Testing Instructions

- Go to /sites-dashboard
- Verify background color for sites thumbnail reflects the site icon (both list and tile view)
image

*

#### Pre-merge Checklist

- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?

Related to #

### CODE REVIEW

**Review by sejas — CHANGES_REQUESTED** [review]
@vykes-mac , should we remove `fast-average-color` form `packages/components/package.json` ?

This solution is really smart 💡 . Congrats for thinking out of the box! 💪 
It looks better with the blur than using a plain color.

## This is how it looks 

### Rows



Screenshot 2022-08-10 at 12 35 10
Screenshot 2022-08-10 at 12 35 21
Screenshot 2022-08-10 at 12 36 44


### Tile
Screenshot 2022-08-10 at 12 34 46

Screenshot 2022-08-10 at 12 36 00

Screenshot 2022-08-10 at 12 34 32

**Comment by vykes-mac** [comment]
@sejas Thank you! Yes i need to remove the package from the .json file

**Comment by zaguiini** [comment]
> @sejas Thank you! Yes i need to remove the package from the .json file

I think you also need to run `yarn install` to remove the entry from `yarn.lock`. That's my guess as to why there are so many checks failing.

**Review by zaguiini — APPROVED** [review]
:shipit:

**Review by danielbachhuber — APPROVED** [review]
🔥 Such an awesome solution!

**Pull request merged**
