### PR TITLE
composite-checkout: Add p24 payment method

### PR DESCRIPTION
**Pull request by sirbrillig**
#### Changes proposed in this Pull Request

This adds the p24 payment method to composite checkout.

#### Screenshots

Old checkout:

Screen Shot 2020-06-26 at 5 25 30 PM

New checkout (closed):

Screen Shot 2020-06-26 at 5 47 46 PM

New checkout (open):

Screen Shot 2020-06-26 at 5 59 24 PM

#### Testing instructions

- Apply D45583-code to force payment method to be available.
- Sandbox the store.
- Change your user's currency to `PLN`.
- Add a plan to your cart and visit checkout. 
- Add `?flags=composite-checkout-force` to the query string in the URL and reload the page because currently it is disabled for international currencies.
- Verify that "P24" is an option displayed in the final payment step.
- Verify that you cannot pay if the "Name" field is empty.
- Fill out the fields and submit the payment.
- Verify that you are redirected to a Stripe test page.
- Click to accept the payment and verify that the payment completes successfully and that the plan is purchased.

### CODE REVIEW

**Comment by fditrapani** [comment]
I updated the logo to use SVG markup and removed the additional style markup. 

image

Is p24 the right label or is that a placeholder for now?

**Comment by sirbrillig** [comment]
Thank you!

> Is p24 the right label or is that a placeholder for now?

That's a good question, and I'm not sure of the answer. In old checkout, there was no text; it was just the icon. It looks like some places it is referred to as "P24", but maybe it's better if we use [the full name](https://www.przelewy24.pl/eng/) "Przelewy24". I'll change that.

**Comment by fditrapani** [comment]
Cool, yeah I think using the full name is a good call.

**Comment by nbloomf** [comment]
Works for me! I did have to manually set my geo on the backend to PL to trigger this, despite using a VPN, because of some weirdness with my a8c proxy and sandbox.

image

**Pull request merged**
