### PR TITLE
Fixes webview integration with the Jetpack mobile app

### PR DESCRIPTION
**Pull request by sbarbosa**
Related to SELFSERVE-519

## Proposed Changes

This PR make sure that the webview loaded by the Jetpack mobile App doesn't contain any invalid section or links.

The proposed changes are:
* Hide the new header buttons and subtitles in mobile Jetpack
* Hide the Support button in the campaign details page
* Added a margin-top to the search component

Like in the previous version, I continue to hide the navigation bar.

## Testing Instructions

You need to test this in a browser with a specific user agent. In Chrome for example, in the device dimension dropdown, select Edit and then Add Custom.

Add this in the `User agent string` field: 
`Mozilla/5.0 (iPhone; CPU iPhone OS 12_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/16B91 wp-iphone/12.1`

* Load the live preview and navigate to Tools->Advertising
* In the URL, activate the feature flag `promote-post/redesign-i2` and refresh the page.
* Verify that the WebView version of the Posts page is displayed
**Note:** No header or navigation, and without the `View` link in the posts.

Screenshot 2023-06-12 at 16 06 48

* Exit the mobile view mode and refresh the page
* Go to the Campaigns page and then select a campaign from the list to see the detail
* Go to mobile mode again, in the URL, activate the feature flag `promote-post/redesign-i2` and refresh the page
* Verify that the Campaign details page is displaying the WebView version of the page
**Note:** No header (only the Back button), and without the `Contact Support` link in the page.

Screenshot 2023-06-12 at 16 32 41

Screenshot 2023-06-12 at 16 06 39

## Pre-merge Checklist

- [x] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [x] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [x] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

**Review by timur987 — COMMENTED** [review]
Thanks, @sbarbosa!

Overall changes LGTM but I've found that the filter next to the search bar is positioned a bit higher than the search bar (it's relevant to both posts and campaigns):

Campaigns:
Screenshot 2023-06-13 at 20 24 45

Posts:
Screenshot 2023-06-13 at 20 29 19

For mobile view, "Posts" column name should be on the same level as Sort order dropdown:
Screenshot 2023-06-13 at 20 30 28

For mobile Campaigns, I can't simulate that I have campaigns (as I usually do sandboxing public-api.wordpress.com), so I can't see the list of Campaigns, but I've found that mobile view shows the rest of columns (all columns excluding the "Campaign" column, that should be hidden for mobile view):

Screenshot 2023-06-13 at 20 32 27

**Comment by sbarbosa** [comment]
Thanks for the review @timur987 ! I will check what you mentioned.
One thing to notice is that you need to load the page on a movie device screen with a specific user agent. When you use that user agent, there are section of the page that are hidden (header and menu for example).

I will take a look at the thing you mentioned regarding the alignment issue, maybe some of the hidden components are getting in the way. WIll post new images after I fix this.

**Comment by timur987** [comment]
> One thing to notice is that you need to load the page on a movie device screen with a specific user agent. When you use that user agent, there are section of the page that are hidden (header and menu for example).

Yep, I used Firefox with overridden User Agent string as you've mention in testing instructions. It seems better now (I mean, the "Post" and "Recently Updated" signs are inline:
Screenshot 2023-06-13 at 21 41 44

On desktop it still has improper alignment for the same elements:
Screenshot 2023-06-13 at 21 44 18

**Comment by sbarbosa** [comment]
Ok @timur987, I think I got it now. I changed the approach to using padding instead of margin (it was simpler this way, the margin is already being overridden in a media query).

Now the alignment should be correct for mobile & desktop. I couldn't reproduce your last point (related to the columns being displayed). Maybe it got fixed with the merge with trunk (I think this PR did have your last PR with the responsive view for that page).

Screenshot 2023-06-13 at 16 07 43


Screenshot 2023-06-13 at 16 07 57

**Review by timur987 — APPROVED** [review]
Thanks, @sbarbosa!

The latest padding changes did the trick and it looks great for both

campaigns

image

and posts 

image

**Pull request merged**
