### PR TITLE
Checkout: update initial view of review step

### PR DESCRIPTION
**Pull request by michaeldcain**
In #42678, the "Order Review" step was pulled out of the step flow for Checkout and made persistent. This PR introduces a default summary view of that step to make the already-completed information easier to scan.

**Summary mode (default):**
summary

**Edit mode:**
edit

As part of the PR, I needed to make the following changes to the composite checkout package:
- I attempted to decouple step flow control from the `CheckoutStepBody` wherever possible. `CheckoutStep(s)` act as a wrapper for `CheckoutStepBody` and handle mechanics of progressing through steps.
- I introduced an `areStepsActive` prop to `CheckoutSteps` to allow for the entire set of steps to be inactive when another element of Checkout is focused.

**To Test:**
- Add an item to your cart and visit Checkout with `?flags=composite-checkout-force`
- Verify that the "Your Order" section renders in a summary mode, without a tax line item, remove buttons, or plan variations
- Click "Edit" on "Your Order"
- Verify that the section renders in an edit mode, with all items returned as before and an additional "save order" button.
- Verify that the other Checkout steps are rendered, collapsed and inactive.
- Verify that clicking "save order" returns the section to summary mode.
- Commence jerk testing the rest of Signup. Add and remove items, progress through steps, edit 
and complete steps, return to edit your order, make sure that Checkout progress is maintained… your journey awaits.

### CODE REVIEW

**Comment by sirbrillig** [comment]
One thing I noticed:

- Click "Edit" on the review order step.
- While that step is active, click "Edit" on the contact info step.
- Nothing appears to happen.

**Comment by fditrapani** [comment]
Looking good! I made some minor edits to the font sizes and spacing around the coupon. I can also confirm the issue with the Edit that Payton mentioned.

**Comment by michaeldcain** [comment]
Thanks for catching the editing issue - it's much more apparent now that the contact details step might be marked as complete when the cart loads.

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/3750387

Thank you @michaeldcain for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/3750387).

**Pull request merged**
