### PR TITLE
Signup: Change business site to Radcliffe 2

### PR DESCRIPTION
**Pull request by ramonjd**
For the site goal of 'promote', we've changed the theme from `pub/dara` to to `pub/radcliffe-2` for new site creations.

## Testing
1. Head to `/start` to create site 
2. Under **What’s the primary goal you have for your site?** select **Promote your business, skills, organization, or events** and continue with site creation

screen shot 2018-10-19 at 1 27 06 pm

### Expectations
The default, installed theme should be _Radcliffe 2_.

screen shot 2018-10-19 at 1 15 35 pm

screen shot 2018-10-19 at 1 15 48 pm

screen shot 2018-10-19 at 1 16 01 pm

### CODE REVIEW

**Comment by ramonjd** [comment]
[Signup: Change business site to Radcliffe 2](https://trello.com/c/PYoI4F6O/159-change-business-site-to-radcliffe-2)

**Comment by ramonjd** [comment]
@michaeldcain The site type is `page`. Should the installed theme offer a default banner image?

**Comment by michaeldcain** [comment]
> @michaeldcain The site type is `page`. Should the installed theme offer a default banner image? Thanks!

@ramonjd It looks like the Headstart annotation for the theme has been stripped back. I'll let @fditrapani weigh in on what he'd like the final site to look like as a default (before any Signup inputs), but this is all that's required on the Calypso side.

LGTM, but let's hold for design feedback.

**Comment by michaeldcain** [comment]
Toggled labels to re-run tests.

**Comment by ramonjd** [comment]
> to re-run tests.

Noticed a few other recent PRs have the same e2e test failing. (Trying to find `#main` in the iframe when previewing a post in the editor)

**Pull request merged**
