### PR TITLE
Posts & Editor: show post format if non-standard

### LINKED ISSUE #240: Posts: list of posts doesn't show post format
Currently the list of posts doesn't distinguish post formats, and it's quite hard to read:

We should display the post format info somewhere. A very quick win could be just an icon on the right here:

image

### PR DESCRIPTION
**Pull request by mcsf**
Fixes #240 

Per discussion in #240, only show the format if it isn't set to the default (`standard`):

- In Posts (`/posts`):

post-format-in-posts

- In Editor (`/post`):

post-format-in-editor

### CODE REVIEW

**Comment by lancewillett** [comment]
_Yes! This is so cool. Spot-on, Miguel.

Testing in macOS with Chrome and Safari, looking great.

screen shot 2017-07-24 at 16 15 41
screen shot 2017-07-24 at 16 16 04
screen shot 2017-07-24 at 16 16 22
screen shot 2017-07-24 at 16 17 17
screen shot 2017-07-24 at 16 17 25
screen shot 2017-07-24 at 16 17 36
screen shot 2017-07-24 at 16 17 45
screen shot 2017-07-24 at 16 21 25


Also verified the icons are working on mobile (small screen) view, Chrome on Nexus 6P.





An on iOS with iPad Pro in landscape mode:

img_0042
img_0043
img_0044
img_0045
img_0046_

**Comment by folletto** [comment]
Heya! I'm not sure how close is the redesigned list (I hope... very close) so maybe this comment can be discarded to focus on that but otherwise...

Can we fix the alignment when the icon is present and multiline?

screen shot 2017-07-25 at 11 04 07

**Comment by mcsf** [comment]
> I'm not sure how close is the redesigned list

You'll have to ask master @shaunandrews.

> Can we fix the alignment when the icon is present and multiline?

Good point.

**Comment by drw158** [comment]
Nice one.

I strongly disagree with the icon being shown in the editor, because it clutters the screen with non-essential info. Seems a bit sloppy. Also, the post format is already shown in the sidebar.

screen shot 2017-07-25 at 9 36 24 am

Seems to be from this [suggestion](https://github.com/Automattic/wp-calypso/issues/240#issuecomment-278469173). @mtias any thoughts on this?

**Comment by mcsf** [comment]
Correct, it came from that suggestion. Not a big fan myself, but I figured it was easier/faster to implement according to the suggestion, leaving room for undos, rather than going back and forth with ideas. Feel totally free to revert. :)

**Pull request merged**
