### PR TITLE
Make placement of JITMs to be more specific

### LINKED ISSUE #30491: Jetpack JITMs: make placement more specific
Currently we are displaying JITMs in Calypso at section level ( see ` get_jitm( )` function in core). 
That in turn means we cannot enable them for only specific routes in a section, e.g. `/settings/security` - they would be shown in every route under that section.

In order to enhance targeting capabilities of JITMs, we should extend the code to e.g. handle extra parameters or process the routes differently, allowing more granularity and customization on a per route basis.

/cc @jessefriedman, @tyxla

### PR DESCRIPTION
**Pull request by ChaosExAnima**
#### Changes proposed in this Pull Request

This PR makes the message path used for JITMs be more specific, to allow targeting of specific paths in the interface.

Also see: 1153012803416853-as-1157265372777921

#### Testing instructions

* Create a JITM targeting `plugins-upload`.
* On Calypso, navigate to plugins -> install.
* Verify test JITM appears.

Fixes #30491

### CODE REVIEW

**Comment by enejb** [comment]
I took a look at this PR and notice that we now send `my-sites/themes` instead of `themes`. 
I think if we want to be more granular it might be best to use `this.props.currentRoute` instead.

**Comment by ChaosExAnima** [comment]
Hey @enejb, this PR isn't quite ready. I'm going to be switching from relying on something like what I'm doing here to another approach that allows more flexibility.

**Comment by enejb** [comment]
I tested this and it worked really well! Nicely done. 
After deploying this we might have to revisit some of the jitm that we currently have since the slugs paths might have changed and need to be fixed up. 

Since now we are sending a different path in some cases.

**Review by enejb — APPROVED** [review]

**Comment by ChaosExAnima** [comment]
@enejb - See my comment on the linked ticket above, there's only one that I could see that may be in conflict.

**Pull request merged**
