### PR TITLE
Seller Experience: Add context to Woo landing page translations

### PR DESCRIPTION
**Pull request by markbiek**
#### Changes proposed in this Pull Request

Per https://github.com/Automattic/wp-calypso/pull/61700#issuecomment-1061857285, added context to one of our translation strings.

image

### CODE REVIEW

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/7172240

Thank you @markbiek for including a screenshot in the description! This is really helpful for our translators.

**Comment by blackjackkent** [comment]
Nice! You'll want to update the usages of these strings from #61713 to reflect these contexts as well. :)

**Review by blackjackkent — CHANGES_REQUESTED** [review]
Nice! You'll want to update the usages of these strings from https://github.com/Automattic/wp-calypso/pull/61713 to reflect these contexts as well. :)

**Comment by markbiek** [comment]
> Nice! You'll want to update the usages of these strings from #61713 to reflect these contexts as well. :)

Ah! Didn't realize that needed to be done everywhere, I thought it was just for the translators.

Thank you!

**Comment by markbiek** [comment]
@blackjackkent Updated!

**Comment by kwight** [comment]
Looks good; just be sure to get that last test to pass before merging (I've re-run it).

**Review by kwight — APPROVED** [review]

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/7172240).

**Pull request merged**
