### PR TITLE
WP.com block editor: Exclude features from Jetpack sites

### LINKED ISSUE #34476: wpcom-block-editor plugin: disable additional features for Jetpack sites
We currently build 2 bundles of the [`wpcom-block-editor`](https://github.com/Automattic/wp-calypso/tree/ff19e2ba59962f7f678802cf4f61538ee5e14278/apps/wpcom-block-editor) app:
- [`common`](https://github.com/Automattic/wp-calypso/tree/ff19e2ba59962f7f678802cf4f61538ee5e14278/apps/wpcom-block-editor/src/common): loaded by the block editor in any env (Simple, Atomic and Jetpack sites, both iframed and not iframed).
- [`calypso`](https://github.com/Automattic/wp-calypso/tree/ff19e2ba59962f7f678802cf4f61538ee5e14278/apps/wpcom-block-editor/src/calypso): loaded by the iframed block editor in Calypso.

However, there are features in the `common` bundle that shouldn't be exposed to Jetpack sites, since they are intended specifically for WP.com users. Particularly, we don't have to disable the NUX tour nor unregister the experimental blocks on Jetpack sites.

One possible solution is to split the `common` bundle into 2 different ones.

1st bundle (it can remains as `common` and loaded in any environment - iframed and not iframed):

- Rich text (justify / underline).
- Switch to classic.
- Tracking.

2nd bundle (it can be called `wpcom`, to be loaded in Simple and Atomic sites only - iframed and not iframed):

- Disable NUX tour.
- Unregister experimental blocks.

cc @Automattic/jetpack-crew

### PR DESCRIPTION
**Pull request by mmtr**
#### Changes proposed in this Pull Request

We shouldn't expose all the common features from `wpcom-block-editor` to Jetpack sites, since some of them are intended specifically for WP.com users such as:
- Disable NUX tour.
- Unregister experimental blocks.
- Reorder CoBlocks blocks.

This PR seeks to fix that by splitting the `common` features into 2 new bundles:
- `default`: loaded on all sites. 
- `wpcom`: loaded only on WP.com sites.

The `common` bundle is no longer maintained and it is replaced by the `default` bundle. Note that the `common` build needs to keep being served on `widgets.wp.com` since it will be still used by Jetpack and Atomic sites running Jetpack 8.0 or earlier.

#### Testing instructions

- Apply D36841-code and sandbox `widgets.wp.com` for adding the new bundles to your sandbox:
- Prepare a Simple, a Jetpack and an Atomic test site:
  - Simple: Apply D36377-code and sandbox any WP.com simple site.
  - Jetpack: Spin up a new [JN site running jetpack#14230](https://jurassic.ninja/create/?jetpack-beta&branch=update/wpcom-block-editor-exclude-features-jetpack).
  - Atomic: Install the Jetpack beta plugin and switch the Jetpack branch to `update/wpcom-block-editor-exclude-features-jetpack`.
- Make sure the features are enabled/disabled according to the following table:

<table>
  <tr>
    <th>Feature</th>
    <th>Editor</th>
    <th>Simple site</th>
    <th>Atomic site</th>
    <th>Jetpack site</th>
  </tr>
  <tr>
    <td rowspan="2">
      <a href="./src/default/features/rich-text.js"><code>rich-text</code></a>:
      Extensions for the Rich Text toolbar with the Calypso buttons missing on Core (i.e. underline, justify).
    </td>
    <td>WP Admin</td>
    <td>✅</td>
    <td>✅</td>
    <td>✅</td>
  </tr>
  <tr>
    <td>Calypso</td>
    <td>✅</td>
    <td>✅</td>
    <td>✅</td>
  </tr>
  <tr>
    <td rowspan="2">
      <a href="./src/default/features/switch-to-classic.js"><code>switch-to-classic</code></a>:
      Appends a button to the "More tools" menu for switching to the classic editor.
    </td>
    <td>WP Admin</td>
    <td>✅</td>
    <td>❌</td>
    <td>❌</td>
  </tr>
  <tr>
    <td>Calypso</td>
    <td>✅</td>
    <td>✅</td>
    <td>✅</td>
  </tr>
  <tr>
    <td rowspan="2">
      <a href="./src/wpcom/features/fix-block-invalidation-errors.js"><code>fix-block-invalidation-errors</code></a>:
      Performs block attempt block recovery on editor load if validation errors are detected.
    </td>
    <td>WP Admin</td>
    <td>✅</td>
    <td>✅</td>
    <td>❌</td>
  </tr>
  <tr>
    <td>Calypso</td>
    <td>✅</td>
    <td>✅</td>
    <td>❌</td>
  </tr>
  <tr>
    <td rowspan="2">
      <a href="./src/wpcom/features/reorder-block-categories.js"><code>reorder-block-categories</code></a>:
      Moves Jetpack and CoBlocks Block Categories below Core Categories.
    </td>
    <td>WP Admin</td>
    <td>✅</td>
    <td>✅</td>
    <td>❌</td>
  </tr>
  <tr>
    <td>Calypso</td>
    <td>✅</td>
    <td>✅</td>
    <td>❌</td>
  </tr>
  <tr>
    <td rowspan="2">
      <a href="./src/wpcom/features/tracking.js"><code>tracking</code></a>:
      Adds analytics around specific user actions.
    </td>
    <td>WP Admin</td>
    <td>✅</td>
    <td>✅</td>
    <td>❌</td>
  </tr>
  <tr>
    <td>Calypso</td>
    <td>✅</td>
    <td>✅</td>
    <td>❌</td>
  </tr>
  <tr>
    <td rowspan="2">
      <a href="./src/calypso/features/iframe-bridge-server.js"><code>iframe-bridge-server</code></a>:
      Server-side handlers of the different communication channels we establish with the client-side when Calypso loads the iframed block editor. See <a href="../../client/gutenberg/editor/calypsoify-iframe.tsx"><code>calypsoify-iframe.jsx</code></a>.
    </td>
    <td>WP Admin</td>
    <td>❌</td>
    <td>❌</td>
    <td>❌</td>
  </tr>
  <tr>
    <td>Calypso</td>
    <td>✅</td>
    <td>✅</td>
    <td>✅</td>
  </tr>
  <tr>
    <td rowspan="2">
      <a href="./src/calypso/features/tinymce.js"><code>tinymce</code></a>:
      Tiny MCE plugin that overrides the core media modal used on classic blocks with the Calypso media modal.
    </td>
    <td>WP Admin</td>
    <td>❌</td>
    <td>❌</td>
    <td>❌</td>
  </tr>
  <tr>
    <td>Calypso</td>
    <td>✅</td>
    <td>✅</td>
    <td>✅</td>
  </tr>
</table>

Fixes #34476

### CODE REVIEW

**Comment by kwight** [comment]
Shouldn't `switch-to-classic` be in `wpcom` instead of `common`?

**Comment by mmtr** [comment]
> Shouldn't `switch-to-classic` be in `wpcom` instead of `common`?

We want to show the "Switch to classic" button on Calypso for Jetpack sites as well, so we need to keep it in the shared utilities. It's true we don't want to show it on the WP Admin block editor, but we can control that with [`wpcomGutenberg.switchToClassic.isVisible`](https://github.com/Automattic/wp-calypso/blob/46a9eafeda1d2d74871b527b25765fd7a9f7ae1e/apps/wpcom-block-editor/src/common/switch-to-classic.js#L9).

**Comment by simison** [comment]
>but we can control that with `wpcomGutenberg.switchToClassic.isVisible`.

Should things in `common` bundle be a little bit more defensive about objects or CSS selectors potentially not existing?

If I understood correct, `common` runs also self-hosted Jetpack sites? We don't really control what version of Gutenberg is running there or what other oddities are going on.

**Comment by mmtr** [comment]
> Should things in `common` bundle be a little bit more defensive about objects or CSS selectors potentially not existing?
> 
> So e.g.; `lodash.get( window, [ 'wpcomGutenberg', 'switchToClassic', 'isVisible' ], false )`

Yup, nice catch. I opted for the optional chaining `?.` (which is available in Calypso and thus correctly polyfilled in the generated builds) in 0f7e5a0.
 
> If I understood correct, `common` runs also self-hosted Jetpack sites? We don't really control what version of Gutenberg is running there or what other oddities are going on.

Correct. That's the reason why we still use `@wordpress/editor` instead of `@wordpress/block-editor`. We made sure that all the features are backwards compatible.

**Comment by simison** [comment]
>Correct. That's the reason why we still use @wordpress/editor instead of @wordpress/block-editor. We made sure that all the features are backwards compatible.

Latest Jetpack version supports new enough WP core to use `@wordpress/block-editor` — is there any mechanism in this setup to differentiate between Jetpack versions, or do you just run the latest from CDN for all possible Jetpack versions? If latter, you might be stuck with backwards compatibility support for quite some time...

**Comment by mmtr** [comment]
> do you just run the latest from CDN for all possible Jetpack versions? you might be stuck with backwards compatibility support for quite some time...

Unfortunately, this is the case. I think we could have versioned builds and then update the `wpcom-block-editor` module in Jetpack to use a specific version. Anyway, current features are relatively simple and we didn't need to add so much backwards compatibility support.

**Comment by kwight** [comment]
> We want to show the "Switch to classic" button on Calypso for Jetpack sites as well, so we need to keep it in the shared utilities.

Oh, right – "classic", meaning, the Calypso editor 🙃 Yeesh.

**Comment by gwwar** [comment]
Verified Simple Site Behavior, no regressions found so far
Screen Shot 2019-12-16 at 10 27 09 AM
Screen Shot 2019-12-16 at 10 25 20 AM
Screen Shot 2019-12-16 at 10 24 21 AM
Screen Shot 2019-12-16 at 10 24 06 AM
Screen Shot 2019-12-16 at 10 23 30 AM

**Comment by gwwar** [comment]
Having switch to classic appear in the iframe for WordPress.com but not in wp-admin for Atomic seems a little odd. Non-blocking, as we can follow up with that.

**Comment by gwwar** [comment]
✅ Atomic features appear to work well

**Comment by gwwar** [comment]
✅ Also smoketested Jetpack standalone: no tracking, Calypso media integration, rich text integration

**Comment by gwwar** [comment]
Note that it may also make sense to group needed changes for https://github.com/Automattic/jetpack/pull/14233

I'd prefer if we had a systematic way of splitting out CSS vs a manual one off, as we're likely going to miss this in the future.

**Comment by mmtr** [comment]
> I'd prefer if we had a systematic way of splitting out CSS vs a manual one off, as we're likely going to miss this in the future.

Even with different dist files (which I agree is a good idea), Automattic/jetpack#14233 would still needed since the goal there is to avoid an extra network request (see p1576247513008200-slack-perfops).

Anyway, I think we can improve our build script in order to automatically open diffs and PRs that updates those inline styles if they are modified in the `wpcom-block-editor` Calypso app.

**Comment by mmtr** [comment]
> Are the filenames here too generic? We likely have a high chance of asset name collision. Folks in the future might have trouble tracing this back

Bundles are all served under the `widget.wp.com/wpcom-block-editor` path (i.e. https://widgets.wp.com/wpcom-block-editor/default.js), so that should guard against name collisions since the app cannot have two bundles with the same name.

**Comment by mmtr** [comment]
Alright, I performed a bunch of changes:
- Added the full feature table to the readme.
- Split bundles into `editor` and `view` modes (first will be loaded only on editor, latter on both editor and frontend).
- Remove no longer needed features:
  - Disable NUX: we're enabling it again in https://github.com/Automattic/wp-calypso/pull/38369
  - Unregister experimental blocks: they are unregistered by default now on Gutenberg, and experiments cannot be turned on on Simple/Atomic sites.
- Created new diff that adds the new assets to `widgets.wp.com` (D36841-code).
- Updated D36377-code and https://github.com/Automattic/jetpack/pull/14230 for loading new assets.
- https://github.com/Automattic/jetpack/pull/14230 for adding inline the default styles (copied changes from https://github.com/Automattic/jetpack/pull/14233).

**Comment by gwwar** [comment]
✅Smoke Tested Simple /block-editor
✅Smoke Tested Simple /wp-admin

**Pull request merged**
