### PR TITLE
Get rid of old plans code

### LINKED ISSUE #7056: Plans: refactor to remove old plans design
We've tested a new design for the `/plans/:site` and `/start/plans` pages and it's been successful, so it's time to remove the old code. #7054 is of course a prerequisite before starting this.

Before we can rip out the old code however, we need to enable this feature for all environments, including [desktop.json](https://github.com/Automattic/wp-calypso/blob/master/config/desktop.json) and [desktop-mac-app-store.json](https://github.com/Automattic/wp-calypso/blob/master/config/desktop-mac-app-store.json). This would also need to be coordinated with launching the personal plan to those environments as well because the plans page was designed to include the personal plan. I'm not sure if there are still any reasons we can't just do that. @rodrigoi may have some good background info here.

This task is for both the code cleanup and coordinating to make sure we can safely launch in these environments.

### PR DESCRIPTION
**Pull request by lamosty**
Fixes #7056.

## Testing Instructions

1. Run Calypso with `make run`;
2. Make sure `/plans`, `/plans/compare` work (with `/plans/compare` redirecting to `/plans`);
3. Also, make sure that the NUX (signup) flow works, esp. the plans step.
4. Is there something I forgot to remove?

## Questions

2. Should we rename `PlanFeatures` to `Plans`? E.g. instead of `plansFeaturesList`, `PlanFeaturesMain` have just `Plans` like it was before we started working on plan features?

@gwwar @rralian @mtias @artpi.

Test live: https://calypso.live/?branch=remove/old-plans-code

### CODE REVIEW

**Comment by mtias** [comment]
How does this work with Jetpack plans? Did we already update the design there to follow? cc @rickybanister @johnHackworth

**Comment by lamosty** [comment]
@mtias Do you mean the connected Jetpack-powered WP site plans? If yes, it works quite nicely:

selection_026

**Comment by mtias** [comment]
Nice!

**Comment by gwwar** [comment]
@lamosty you missed a few references in the _components.scss. You should see the issue If you clear your cache, and run `make run`.

**Comment by lamosty** [comment]
> @lamosty you missed a few references in the _components.scss. You should see the issue If you clear your cache, and run make run.

Thanks for pointing that out! Fixed.

**Comment by rralian** [comment]
This is my favorite kind of PR. It's so rare that we make our app and code simpler. ❤️ 

screen shot 2016-08-05 at 1 45 17 pm

**Comment by gwwar** [comment]
Don't forget to retest your flows 😄  There's a js error preventing `/plans` from loading.

**Comment by lamosty** [comment]
> Don't forget to retest your flows :smile: There's a js error preventing /plans from loading.

Sorry, I thought everything's fine.. Retested the flows and I had to remove/adjust a few more things. `/plans` and NUX signup works normally now. However, as this is a big change, it would be best to run the e2e tests I suppose. What's the best way to do that? Just checkout the e2e repo and run it locally?

Thanks!

**Comment by gwwar** [comment]
> Just checkout the e2e repo and run it locally?

It'd be a good idea to do so. If you ask nicely, @hoverduck might help too 😄

**Comment by hoverduck** [comment]
Only if you ask nicely :wink:

I'm happy to kick off a run myself if you want me to, but if you've got the time to get it set up to run yourself it's always helpful for us to get feedback on how explanatory the README file is.

https://github.com/Automattic/wp-e2e-tests

**Comment by gwwar** [comment]
@lamosty, I retested and this looks good in the main flows 👍 Let's 🚢 after we get a green e2e run.

**Comment by lamosty** [comment]
Thanks for the review! I'm gonna set up the e2e tests myself as @hoverduck suggested and merge if I get a green light.

**Comment by artpi** [comment]
Tested, WFM.
This makes me excited!

**Comment by hoverduck** [comment]
e2e tests are clean!  Took a while because I had to incorporate a couple changes unrelated to this PR.

**Comment by gwwar** [comment]
Let's 🚢 !

**Comment by mtias** [comment]
Nice!

**Pull request merged**
