### PR TITLE
Use platform.js for Google sign-in.

### PR DESCRIPTION
**Pull request by sgomes**
Not only is this the recommended way of loading Google's auth API, it loads less JS than the current `api.js` alternative (53KB vs 103KB, compressed).

See https://developers.google.com/identity/sign-in/web/

#### Changes proposed in this Pull Request

* Replace usage of Google's `api.js` with `platform.js` in `GoogleLoginButton`.

#### Testing instructions

Ensure that Google sign-in functionality still works normally.

**Note**: If I added you as a reviewer and you're not familiar with this code, sorry about that, I'm just going by GitHub recommendations! If that's the case, please feel free to remove yourself or ignore the PR. And if you can point me to a better reviewer, please do! 🙂

### CODE REVIEW

**Comment by sgomes** [comment]
Some screenshots.

Before:

image


After:

image

**Comment by sgomes** [comment]
The E2E tests seem to be failing due to transient failures and unrelated issues 😕

**Review by jsnajdr — APPROVED** [review]
Code looks good and works well. Thanks! :+1:

**Comment by sgomes** [comment]
> Code looks good and works well. Thanks! 👍

Thanks for the review, @jsnajdr ! 🙂

**Comment by stephanethomas** [comment]
We've got a regression in production @sgomes, and @Tug [seems to think](https://github.com/Automattic/wp-calypso/pull/35592#issuecomment-524853356) it comes from those changes. The `Continue with Google` button indeed stays disabled in the following case:

1. Open the [`Login` page](https://wordpress.com/log-in)
2. Click the `Sign Up` link in the top right corner
3. Notice that the `Continue with Google` button is disabled
4. Notice the following error in the browser's console:
```
message: "gapi.auth2 has been initialized with different options. Consider calling gapi.auth2.getAuthInstance() instead of gapi.auth2.init()."
stack: "gapi.auth2.ExternallyVisibleError: gapi.auth2 has been initialized with different options. Consider calling gapi.auth2.getAuthInstance() instead of gapi.auth2.init().↵ 
```

Could you have a look please?

**Comment by sgomes** [comment]
> We've got a regression in production @sgomes, and @Tug [seems to think](https://github.com/Automattic/wp-calypso/pull/35592#issuecomment-524853356) it comes from those changes. The `Continue with Google` button indeed stays disabled in the following case:
> 
> 1. Open the [`Login` page](https://wordpress.com/log-in)
> 2. Click the `Sign Up` link in the top right corner
> 3. Notice that the `Continue with Google` button is disabled
> 4. Notice the following error in the browser's console:
> 
> ```
> message: "gapi.auth2 has been initialized with different options. Consider calling gapi.auth2.getAuthInstance() instead of gapi.auth2.init()."
> stack: "gapi.auth2.ExternallyVisibleError: gapi.auth2 has been initialized with different options. Consider calling gapi.auth2.getAuthInstance() instead of gapi.auth2.init().↵ 
> ```
> 
> Could you have a look please?

Taking a look now 👍

**Comment by sgomes** [comment]
> We've got a regression in production @sgomes, and @Tug [seems to think](https://github.com/Automattic/wp-calypso/pull/35592#issuecomment-524853356) it comes from those changes. The `Continue with Google` button indeed stays disabled in the following case:
> 
> 1. Open the [`Login` page](https://wordpress.com/log-in)
> 2. Click the `Sign Up` link in the top right corner
> 3. Notice that the `Continue with Google` button is disabled
> 4. Notice the following error in the browser's console:
> 
> ```
> message: "gapi.auth2 has been initialized with different options. Consider calling gapi.auth2.getAuthInstance() instead of gapi.auth2.init()."
> stack: "gapi.auth2.ExternallyVisibleError: gapi.auth2 has been initialized with different options. Consider calling gapi.auth2.getAuthInstance() instead of gapi.auth2.init().↵ 
> ```
> 
> Could you have a look please?

I can't seem to reproduce this issue; that error message never pops up for me. Is there any special condition needed to trigger it? I've tried with two different accounts and also logged-out.

**Comment by sgomes** [comment]
> We've got a regression in production @sgomes, and @Tug [seems to think](https://github.com/Automattic/wp-calypso/pull/35592#issuecomment-524853356) it comes from those changes. The `Continue with Google` button indeed stays disabled in the following case:
> 
> 1. Open the [`Login` page](https://wordpress.com/log-in)
> 2. Click the `Sign Up` link in the top right corner
> 3. Notice that the `Continue with Google` button is disabled
> 4. Notice the following error in the browser's console:
> 
> ```
> message: "gapi.auth2 has been initialized with different options. Consider calling gapi.auth2.getAuthInstance() instead of gapi.auth2.init()."
> stack: "gapi.auth2.ExternallyVisibleError: gapi.auth2 has been initialized with different options. Consider calling gapi.auth2.getAuthInstance() instead of gapi.auth2.init().↵ 
> ```
> 
> Could you have a look please?

Just a reminder that there is a fix for this waiting for a review for a while in #35936.

**Pull request merged**
