### PR TITLE
SEO: Update title format to match new API format

### PR DESCRIPTION
**Pull request by dmsnell**
**Needs to coordinate with server API changes in D2523!**

Previously we had build the mapping/normalization between the Calypso
way of storing title mappings with the original version of that used by
the server in the API.

The API format changed and this patch updates Calypso to map to and from
the new formats.

There are no visual changes to this PR.

**Testing**

Navigate to **My Sites** > **Settings** > **SEO** on a site with at least the business plan or higher and try to change around the title formats. After saving and reloading the values should reflect what you updated.

cc: @roundhill @vindl (@gwwar the tests for the mapping have been added here)

Test live: https://calypso.live/settings/seo/?branch=update/title-format-api-mapping

### CODE REVIEW

**Comment by roundhill** [comment]
When I save the form, all spaces are getting stripped out:

screen shot 2016-09-05 at 3 58 40 pm

**Comment by dmsnell** [comment]
> When I save the form, all spaces are getting stripped out

@vindl does anything in the API patch obviously explain this? I have tests in here that show that it shouldn't mangle any spaces… maybe I missed something?

**Comment by vindl** [comment]
@dmsnell @roundhill: `sanitize_text_field` was stripping all of the extra whitespace (leading whitespace included). I've removed it from the diff, and I think we should be safe without it, since we are escaping the title before output.

**Comment by roundhill** [comment]
> I've removed it from the diff

Confirmed fixes, thanks @vindl

**Comment by roundhill** [comment]
:shipit:

**Pull request merged**
