### PR TITLE
A4A: Update a few copies related to Agency Tier and benefits.

### PR DESCRIPTION
**Pull request by jkguidaven**
This PR revises several copies regarding the Agency Tier and its benefits. These are the final copies before the release.

Closes https://github.com/Automattic/automattic-for-agencies-dev/issues/1457

## Proposed Changes
See the following copies that have been updated:

| Description | Before | After |
|--------|--------|--------|
| The Agency Tier card on the overview page has been updated. The title has been changed to **'Your Progress'**, and **'Tier'** in the explore link is now capitalized. | Screenshot 2024-11-12 at 5 33 07 PM | Screenshot 2024-11-12 at 5 32 50 PM |
| We have revised the card text for **'No tier'**.  | Screenshot 2024-11-12 at 5 36 51 PM | Screenshot 2024-11-12 at 5 37 01 PM |
| We have revised the pop-up message for **'Emerging Partner'**. | Screenshot 2024-11-12 at 5 41 52 PM | Screenshot 2024-11-12 at 5 41 30 PM |
| We have revised the pop-up message for **'Agency Partner'**.  | Screenshot 2024-11-12 at 5 44 33 PM | Screenshot 2024-11-12 at 5 44 49 PM |
| We have revised the pop-up message for **'Pro Partner'**. | Screenshot 2024-11-12 at 5 47 39 PM | Screenshot 2024-11-12 at 5 47 47 PM | 
| We have revised the headings on the **Agency Tier and benefits** page. | Screenshot 2024-11-12 at 5 50 58 PM | Screenshot 2024-11-12 at 5 51 06 PM | 
| We have updated the cards on the **Agency Tier and benefits** page.  | Screenshot 2024-11-12 at 5 53 03 PM | Screenshot 2024-11-12 at 5 53 35 PM | 
| We have revised the card text for **'No tier'** on the **Agency Tier and benefits** page.   | Screenshot 2024-11-12 at 5 55 42 PM | Screenshot 2024-11-12 at 5 55 51 PM | 
| Add a **'beta'** tag to the Agency Tier sidebar menu item. | Screenshot 2024-11-12 at 6 58 12 PM | Screenshot 2024-11-12 at 6 58 05 PM |

## Why are these changes being made?

* This is part of the Agency Tiering project.

## Testing Instructions

* Refer to the testing items above.
* Use the MC tool to update your agency tier to a different one and test various scenarios.
* Make sure you also reset the `a4a-agency-tier-celebration-modal-dismissed-type` preference to test the pop-up modal again.

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Comment by simonktnga8c** [comment]
Great work @jkguidaven 👏 thanks for such a quick turnaround!

**Review by yashwin — COMMENTED** [review]
Thanks for working on this!

I think while copying the text, it got copied as Right Single Quotation Mark ( ’ ) instead of The Apostrophe ( ' ) at multiple places here: 

Screenshot 2024-11-13 at 9 29 52 AM

The Apostrophe ( ' ):

Screenshot 2024-11-13 at 9 54 38 AM

Right Single Quotation Mark ( ’ ):

Screenshot 2024-11-13 at 9 54 47 AM

**Comment by jkguidaven** [comment]
> Thanks for working on this!
> 
> I think while copying the text, it got copied as Right Single Quotation Mark ( ’ ) instead of The Apostrophe ( ' ) at multiple places here:
> 
> Screenshot 2024-11-13 at 9 29 52 AM
> The Apostrophe ( ' ):
> 
> Screenshot 2024-11-13 at 9 54 38 AM
> Right Single Quotation Mark ( ’ ):
> 
> Screenshot 2024-11-13 at 9 54 47 AM

Good catch! this has been fixed! thanks for the review 👍

**Review by yashwin — APPROVED** [review]
Thanks for addressing my comment!

LGTM!

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/17001623

Some locales (Hebrew, Japanese) have been temporarily machine-translated due to translator availability. All other translations are usually ready within a few days. Untranslated and machine-translated strings will be sent for translation next Monday and are expected to be completed by the following Friday.

Thank you @jkguidaven for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/17001623).

**Pull request merged**
