### PR TITLE
Editor: Only diff revisions with feature flag active

### LINKED ISSUE #19745: Calypso/Editor: Freeze almost immediately after loading a page
A user has reported that opening a moderately long page in the Calypso editor results in the page freezing for long enough to trigger the Wait/Kill dialog.

I was able to reproduce by SU-ing in and opening the page in the editor. The page loads promptly, but almost imediately afterwards the page locks up for a long time, maybe 30-40 seconds and the user reports 60-90 on slower hardware.

#### Steps to reproduce
1. Private user data makes it inappropriate to add much more detail here, but details about the specific site and page are in ticket 790919-zd-woothemes but the short version is:
1. Site Pages > <Problematic Page>
2. Try scrolling down the page, observe the long freeze

#### Browser / OS version
Chrome / Windows 10 & OSX 10.12.6

#### Context / Source
The user reports that they've been using this page at about this size for the last year, so it looks like this might be a performance regression. It also makes me wonder if the freeze might be related to the long history rather than the long page.

I'm not sure if it's a delay or the scrolling that triggers the freeze. The issue is somewhat intermittent, and I reloaded with an empty cache to get it to happen a second time, and then unsuccesfully tried to reproduce against a development build after that.

I ran performance profiling the second time, and confirmed that Calypso is spending all that time in scripts. After comparing the minimized code with an unminified version, I'm pretty confident it's spending the 90% of the time in `clonePath()` in `diff.js`

Related: #19446

### PR DESCRIPTION
**Pull request by marekhrabe**
We have all the functionality for new Revisions UI behind the feature flag except one place, we didn't think of and this exact place was causing troubles in production lately. 

This PR is a hotfix that will hide the diffing logic behind the flag. 

Before testing: 
- this PR cannot be tested on calypso.live because it runs in development mode
- you can test this on a calypso.localhost if you disable `post-editor/revisions` feature flag in `config/development.json` and rebuild everything

To test:
- make a post/page with 10000 words and save it
- Reload the editor page after saving and try to interact with the editor (clicking buttons, selecting text)
- Without this PR (for example, testing directly on WordPress.com), you should experience total unresponsiveness of the UI for up to a minute. No buttons would work, no hover states, clicking does nothing
- With this PR, the lag should be gone

Fixes #19745

### CODE REVIEW

**Comment by sirreal** [comment]
> this PR cannot be tested on calypso.live because it runs in development mode

You should be able to with something like the following:

https://calypso.live/?branch=fix/revision-diffing-only-with-flag&flags=-post-editor/revisions

**Comment by marekhrabe** [comment]
@sirreal I forgot about that query argument — it does the job!

**Comment by Copons** [comment]
Tested both on live with the query arg and locally with the flag disabled: no lag anymore!
LGTM! 🚢

**Comment by marekhrabe** [comment]
Thank you both <3

**Pull request merged**
