### PR TITLE
Design Picker: Upgrade Modal to support Marketplace Themes

### PR DESCRIPTION
**Pull request by WBerredo**
Fixes https://github.com/Automattic/dotcom-forge/issues/2956

## Proposed Changes

Update the Upgrade Modal on Design Picker to support Marketplace Themes. Styles on: RcxiuWYjZGkFRdlWL7L02m-fi-754:221984#540834845

| Desktop  | Mobile |
| ------------- | ------------- |
|CleanShot 2023-08-31 at 12 51 41@2x|CleanShot 2023-08-31 at 12 52 06@2x|

## Testing Instructions

* Apply the diff D118900-code to your sandbox and direct requests to the sandbox
* Go to the Design Picker page with a Marketplace theme selected `/setup/update-design/designSetup?siteSlug=:site&theme=:theme_slug`. Theme slugs such as `makoney` and `olsen-fse` can be used.
* Click on `Unlock Theme`
* You should see the modal with the updated layout.
* Test this flow with a site without plans and a site with a business plan
* On the Business plan site, you shouldn't see the business plan described on the modal

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

**Comment by mmtr** [comment]
@WBerredo @lucasmendes-design @vinimotaa @Copons I think this might conflict with the modals proposed in https://github.com/Automattic/wp-calypso/issues/78694#issuecomment-1688440177:

image


It's not exactly the same flow (the linked issue is about the Theme Showcase, this PR is about the Design Picker) but I think we ultimately want to use the same modal.

We probably need to have a design alignment here.

**Comment by BogdanUngureanu** [comment]
@mmtr I think the modal from this PR is clearer, I guess; but I agree we should align first. :) 

As for the modal, I did some tests and while it looks amazing on desktop, I think it needs a bit more polishing on mobile resolutions. For example, for most viewports the CTA buttons are not visible on the screen, the user needs to scroll to see them.

https://github.com/Automattic/wp-calypso/assets/995955/19709658-7f63-49a4-8835-787bb5d6e214

**Comment by lucasmendes-design** [comment]
Nice! I like to show the price of the business plan + theme subscription. I just think we need to clarify the message a bit more to say that this is an annual price. Plus, the theme features list is outdated, in the latest iteration we just removed the theme features and included more plan features. There is more value that way. 


Btw, the modal that you shared @mmtr is without the domain change :) Let's share the right one to avoid confusion.

image


> As for the modal, I did some tests and while it looks amazing on desktop, I think it needs a bit more polishing on mobile resolutions. For example, for most viewports the CTA buttons are not visible on the screen, the user needs to scroll to see them.

Agreed. The scroll inside the modal looks strange.

**Comment by lucasmendes-design** [comment]
>  I think the modal from this PR is clearer

+1.

**Comment by lucasmendes-design** [comment]
I'll align with @vinimotaa

**Comment by Copons** [comment]
I'm good with the modal proposed here. 👍 

As long as the flow is consistent across all theme types, I have no strong opinions on which modal we should use.

The flow would be:

1. Theme
   * The modal in this PR should be here.
3. Upgrade plan and/or subscribe to theme
4. Congrats page
5. Activate theme (and transfer to Atomic if needed)

**Comment by WBerredo** [comment]
I've used the modal described here ZmojXjw1Qzzn3UquGzI0C8-fi-13%3A1376, but I see now it might be outdated.

Comparing the versions, I found the table-like version in this PR easier to understand what the user will have to pay, more than the text version. This also makes the displaying of the needed products(plan + theme, only theme, only plan) a case of show/hiding information instead of changing texts.

**Comment by WBerredo** [comment]
That said, I agree we must have a single source of truth, and I wouldn't use `client/landing/stepper/declarative-flow/internals/steps-repository/design-setup/upgrade-modal.tsx` as this place. 

For future work, I think we must focus on creating this modal as a separate component, and then use it on the Design Picker.

**Comment by Copons** [comment]
> That said, I agree we must have a single source of truth, and I wouldn't use `client/landing/stepper/declarative-flow/internals/steps-repository/design-setup/upgrade-modal.tsx` as this place.
> 
> For future work, I think we must focus on creating this modal as a separate component, and then use it on the Design Picker.

@WBerredo we are tracking the work for new theme-related modals in these 2 PRs:

* https://github.com/Automattic/wp-calypso/issues/81088
* https://github.com/Automattic/wp-calypso/issues/81089

I wouldn't block existing work, but as you said, in the future all these modals should be unified, composable, and reusable.

**Review by epeicher — APPROVED** [review]
I have tested it using different plans and they all works as expected. LGTM!

| Free / Premium | Business / eCommerce|
|-------|------|
|    CleanShot 2023-08-29 at 13 34 16@2x  |  CleanShot 2023-08-29 at 13 34 32@2x|

**Comment by lucasmendes-design** [comment]
Hi @WBerredo, as we talked earlier. Here are some suggestions and directions. Let me know your thoughts :) 

- Let's remove this image. The image isn't adding any value and we will also have more vertical space. So, for small screens, this is beneficial.  
image

- About the scroll inside the modal, I was analyzing different modals across the product and all work the same way. So, for now, let's keep this without any changes. 

- Remove the theme features. It's also not adding value for users. IMO it's better to highlight the plan's features like 4K videos, storage, support, free domain, etc. 

- For mobile, we can hide the feature list. So, we can keep this simple and small. 

- Figma file for mobile and desktop ( RcxiuWYjZGkFRdlWL7L02m-fi-754:221984#540834845 ). 

image

**Comment by WBerredo** [comment]
@lucasmendes-design this layout seems great, I'll work on it during the day and let you know the outcome.

**Comment by WBerredo** [comment]
The updated version following the figma is available now, with two differences:
* The CTA shows `Continue` instead of `Upgrade and subscribe` for the case where the user is already on Business plan
* Already created features were added instead of creating new ones.

In case any of those are blocking, let's discuss new solutions.

**Comment by epeicher** [comment]
The new design looks great to me! I have found these minor differences with the design, I don't think any of them are blockers but noting them down here for visibility:

||Figma | Implementation|
|-------|-------|------|
|Margin bottom in subtitle|CleanShot 2023-08-31 at 13 19 33@2x|CleanShot 2023-08-31 at 13 20 33@2x|
|font of price|CleanShot 2023-08-31 at 13 24 22@2x| CleanShot 2023-08-31 at 13 26 14@2x |
|gap between buttons|CleanShot 2023-08-31 at 13 27 35@2x|CleanShot 2023-08-31 at 13 29 06@2x|
|I have measured and the gap between list items is `12px` but the Figma design seems to have more padding between list items | CleanShot 2023-08-31 at 13 31 04@2x |CleanShot 2023-08-31 at 13 40 52@2x|

But as commented, all of them are nitpicks so I would just change them if they are straightforward and low impact. Otherwise, I will ship it as is 🚢

**Review by epeicher — APPROVED** [review]
I have tested all the plans, and it works as advertised. Changes Look Good to Me! I have left some minor comments https://github.com/Automattic/wp-calypso/pull/81087#issuecomment-1700900707 but they are all pretty minor in my opinion, so I would only action them if they are low effort and impact.

**Comment by WBerredo** [comment]
Thanks for pointing out those differences @epeicher, I haven't updated the Plan features related because its already used on this same modal for other cases, so I decided to keep it the same way for the sake of consistency.

**Review by epeicher — APPROVED** [review]
Thanks for the latest additions! I have given another round of testing and it works as expected, and the design is even closer to the Figma in all the details I have checked. :shipit:

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/8840934

Thank you @WBerredo for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/8840934).

**Pull request merged**
