### PR TITLE
Adds a test on the free Plan price label

### PR DESCRIPTION
**Pull request by lucasartoni**

### CODE REVIEW

**Comment by lucasartoni** [comment]
screen shot 2016-02-02 at 12 07 25
"for life" is the current label, and original variation
localStorage.setItem('ABTests','{"periodLabelFree_20160202":"forLife"}')

screen shot 2016-02-02 at 12 07 12
"with some advertising" is the proposed variation
localStorage.setItem('ABTests','{"periodLabelFree_20160202":"withAdv"}')

**Comment by lucasartoni** [comment]
cc @breezyskies

**Comment by lucasartoni** [comment]
screen shot 2016-02-02 at 12 16 51
screen shot 2016-02-02 at 12 16 37

The variation applies to all instances of "for life", for instance on the plans comparison page too.

**Comment by mikeshelton1503** [comment]
LGTM :+1:

**Pull request merged**
