### PR TITLE
Theme Showcase: Update WordPress.com Experts nudge, take 2

### PR DESCRIPTION
**Pull request by sixhours**
#### Changes proposed in this Pull Request

* Following up on #54140, let's try this again :)
* Use UpsellNudge component rather than a custom solution for the WordPress.com Experts upsell
* Add an icon to help better catch the eye

**Before**

Screen Shot 2021-07-13 at 1 32 53 PM

**After**

Simple/Atomic

Screen Shot 2021-07-13 at 1 32 17 PM

Jetpack

Screen Shot 2021-07-13 at 1 32 36 PM

#### Testing instructions

* Switch to this PR, navigate to `/themes`
* Make sure clicking on the banner/button takes you to the "Built by WordPress.com" site: https://wordpress.com/built-by-wordpress-com/ (for some reason last time, this worked locally, but not in production - need to test it on calypso.live)
* Make sure Tracks events fire as expected (impression, click, dismiss)

Related to #54087

### CODE REVIEW

**Comment by sixhours** [comment]
Double-checked and this appears to be working on calypso.live - clicking on the CTA redirects us to the correct URL. Not sure how else we can test the click through behavior without deploying this.

**Review by mreishus — APPROVED** [review]
This is working for me on both local and calypso live, and the tracks events look to be firing

**Comment by sixhours** [comment]
I'll plan to ship this tomorrow, and watch it closely to make sure the button behaves as expected on production. 🤞

**Comment by sixhours** [comment]
Deployed this and then promptly reverted; the button doesn't work on production. Grabbed a quick video of the issue while on staging:


https://user-images.githubusercontent.com/2124984/125796454-3b6c450c-9f50-43b9-bccb-9277143cb77e.mov

You can see how clicking the button causes the browser's URL to change to the correct address, but you're never brought to that address.

I checked the console and there's an uncaught error, maybe related? Hard to say, it seems to point to the REST proxy API:

Screen Shot 2021-07-15 at 9 28 54 AM

**Pull request merged**
