### PR TITLE
Checkout: Return to domain status page from empty cart when removing renewal

### PR DESCRIPTION
**Pull request by eltongo**
#### Changes proposed in this Pull Request

When renewing a domain from it's status card, and not from the purchases page, if the user then removes the renewal from the cart, we return the user to the domain's status page/card, instead of the purchase page.

I've deliberately kept the code simple, which means this might not work correctly if there are several items in the cart.

#### Testing instructions

- Select a site on which you have a registered domain
- Go to Manage -> Domains, and select the registered domain to view it's status page/card
- Click the renew button, you will be redirected to the cart
- Remove the renewal from the cart
- Verify that you are redirected to the domain's status card, and not its purchase page

Also verify that when going to /me/purchases, choosing a domain registration, and clicking Renew Now, after removing the item from the cart, you get redirected to the purchase page instead.

### CODE REVIEW

**Comment by fditrapani** [comment]
Nice! I tried this on Calypso.live but kept getting taken back to the plans screen. I saw a quick flash of the settings page come up but then it was gone and I was on the plans screen.

**Comment by eltongo** [comment]
> Nice! I tried this on Calypso.live but kept getting taken back to the plans screen. I saw a quick flash of the settings page come up but then it was gone and I was on the plans screen.

Hmm yeah. It works on Firefox, but on Chrome it acts weird. I'll look into it some more.

**Comment by eltongo** [comment]
Alright, now it should work™ 🤞 

It turns out it wasn't working correctly in Firefox either, but the issue wasn't being manifested as obviously as in Chrome. Firefox would have the plans URL in the address bar, but stay in the domain settings page 🤷‍♂️

**Comment by fditrapani** [comment]
Very nice! works like a charm!

**Pull request merged**
