### PR TITLE
Upgrade to node 8.11.0

### PR DESCRIPTION
**Pull request by blowery**
Moves us to node 8.11.0, the latest 8 line LTS release. NPM remains at 5.6.0.

## Local Dev

1.  Switch to node version 8.11.0 (npm 5.6.0)
2. npm run distclean
3. npm start

No functional changes to Calypso

## Local Docker Image
1. Follow image instructions at: PCYsg-5XR-p2 or
2. Setup docker locally and add the following host entry: `127.0.0.1 wpcalypso.wordpress.com`
3. npm run build-docker
4. npm run docker

## Desktop
1. Clone the wp-desktop project
2. Follow install instructions
3. In the calypso submodule checkout this branch
4. Desktop behaves normally

### CODE REVIEW

**Comment by blowery** [comment]
Won't work _just yet_ because the Node 8.11.0 docker image isn't out yet.

**Comment by gwwar** [comment]
Thanks for spinning this one up! It's also helpful to regenerate the shrinkwrap too on minor bumps. Do you mind adding testing instructions to the summary @blowery you can probably copy pasta from the last one: https://github.com/Automattic/wp-calypso/pull/22236

**Comment by gwwar** [comment]
We likely also need a Desktop PR spun up in parallel, since they're pinning to an exact Node version.

> You can get the canary to pass if you create a branch of an identical name in wp-desktop, update the calypso branch to point at yours and then remove/add the needs review label. The canary should then re-run using your wp-desktop branch instead of develop!

https://github.com/Automattic/wp-calypso/pull/22236#issuecomment-364205185

**Comment by blowery** [comment]
Desktop PR at https://github.com/Automattic/wp-desktop/pull/430

**Comment by alisterscott** [comment]
Calypso.live isn't building this, is this because of:

> Won't work just yet because the Node 8.11.0 docker image isn't out yet.

**Comment by samouri** [comment]
@alisterscott: Docker image has been released. I reset the branch by adding `&reset=1`. calypso.live looks like its pulled down the new base image and I think its working now.  Thanks for the heads up

**Review by gwwar — APPROVED** [review]
✨ full tests passed. Don't forget to give folks a heads up before you land. We'll also want to merge the desktop PR.

**Comment by nylen** [comment]
@blowery @gwwar it looks like there is still another thing to update here - https://github.com/Automattic/wp-calypso/blob/a34f9c98086001052016f664eccd3a6d7d76a0dc/.circleci/config.yml#L7.  I think there is a guide where this step could be added, but I am not sure where it is so I'm commenting here.

Pointed out by @kwight in Slack.

**Comment by gwwar** [comment]
Nice catch. It's the 2.0 config.

@dmsnell are we running the 2.0 config now? Can we remove the 1.0 config?

**Comment by dmsnell** [comment]
2.0 has been going for a while and seems to be stable. We can remove 1.0 confirms and scripts

**Pull request merged**
