### PR TITLE
JPO: introduce Connect form as an onboarding flow step

### PR DESCRIPTION
**Pull request by eliorivero**
This introduces Connect as a step in the flow, right before the JPO summary.
Clicking Complete Onboarding takes the user to the usual My Plans page.

### CODE REVIEW

**Comment by eliorivero** [comment]
To complete this you have to build Calypso locally and start in your Jetpack site and use https://github.com/Automattic/jetpack/pull/7468, following the instructions there that I'm copying and adapting here:

1. build this branch locally
2. in your Jetpack site (your dot org sandbox), switch to the branch `update/start-jpoalypso`
3. do `wp jetpack options update onboarding 1`
4. in the sandbox, go to WP Admin > Jetpack dashboard, and click the button to connect to start the flow

This is required for this so it carries all the connection URL parameters from the Jetpack site to the connect form.

**Comment by rcoll** [comment]
One observation is that the connect step is a bit larger than it should be. We'll definitely need some design input on this, but this can be merged as is. Thanks!

**Comment by ashleighaxios** [comment]
I'm still not able to see this step. @eliorivero @rcoll What's going on with that?

**Comment by eliorivero** [comment]
Use the feature branch, this one was already merged
https://github.com/Automattic/wp-calypso/pull/17094

I previously left you instructions here https://github.com/Automattic/wp-calypso/pull/17417#issuecomment-323998149 same ones apply for feature branch

**Comment by ashleighaxios** [comment]
I was looking at the feature branch. Please also post screenshots of work to help me & @rickybanister give more immediate design feedback.

**Pull request merged**
