### PR TITLE
Purchases: Stop description text from jumping on page transition.

### LINKED ISSUE #40100: Purchases: Purchase description text jumps on clicking for details.
[Reported](https://github.com/Automattic/wp-calypso/pull/40068#issuecomment-597832933) by @gwwar in #40068 :

Why does copy jump to the next line when we click on View Plan Features?

Page Load
Screen Shot 2020-03-11 at 12 45 56 PM

After Click
Screen Shot 2020-03-11 at 12 45 36 PM

#### To Replicate

* Find a plan purchase under `/me/purchases`.
* Click the View Plan Features link, and see the description text jump as the page transitions.
* Click the browser Back button, and notice the bolded description title is now on its own line.

### PR DESCRIPTION
**Pull request by kwight**
When clicking the View Plan Features link on `/me/purchases`, the incoming stylesheet can make the plan description title jump as it becomes `display: block` from its browser default of `inline`. By setting an explicit style for the title on the Manage Purchase page, we can avoid the visual glitch.

Screen Shot 2020-03-12 at 11 18 32 AM

#### Testing instructions

* Find a plan purchase under `/me/purchases`.
* Click the View Plan Features link, and verify the plan description content doesn't jump from the title becoming `display: block`.
* Click the browser Back button, and verify the description title is still inline.

Fixes #40100

### CODE REVIEW

**Comment by jancavan** [comment]
Thanks for the fix, @kwight! Not related to text jumping, but doesn't the text need to be in sentence-case? eg - "small business" vs "Small Business"?

**Comment by kwight** [comment]
> doesn't the text need to be in sentence-case? eg - "small business" vs "Small Business"?

@jancavan Hm, good question, no idea. I know we were discussing that with respect to buttons, and I'd agreee it would look better here too – @Automattic/editorial ?

**Comment by jancavan** [comment]
I found it on p2-p9Jlb4-1ly. Could be handled in a separate PR.

**Comment by kwight** [comment]
> Could be handled in a separate PR

Will do – turns out there's a bunch of them in [here](https://github.com/Automattic/wp-calypso/blob/master/client/lib/plans/plans-list.js#L31). https://github.com/Automattic/wp-calypso/issues/40107

**Comment by michelleweber** [comment]
Yes to lowercase letters there. "Small Business" isn't a proper noun/title, no need to capitalize it.

(And yes to sentence case on all buttons! Including the "Renew now" in the corner of this screen. :) )

**Comment by danhauk** [comment]
@michelleweber Sentence casing buttons! #39692

**Pull request merged**
