### PR TITLE
Plans: show monthly pricing on all environments

### PR DESCRIPTION
**Pull request by gwwar**
This PR turns on the display of monthly plan pricing. This is a follow up to #4724

screen shot 2016-04-13 at 3 58 30 pm
screen shot 2016-04-14 at 2 39 01 pm
screen shot 2016-04-14 at 2 39 13 pm

cc @rralian @retrofox @artpi @drw158

### CODE REVIEW

**Comment by retrofox** [comment]
Maybe I'm making a dummy question but why we are keeping this key in config?

**Comment by gwwar** [comment]
Makes it easy to turn off if it doesn't do well

**Comment by artpi** [comment]
Well, I'd like to say code looks ok..

I assume there were ABtests and they say this is the way to go?

I have no moral dilemma activating it, so 👍 and 🐑 🚢  from me.
We should probably update our hardcoded stuff, because there we say "per year", but I see no big harm seeing a notice that says 99/year and then being pleasantly surprised by 8.25/year. So much win!

**Comment by rralian** [comment]
Let's turn this on and see how it goes.

**Pull request merged**
