### PR TITLE
Framework: update `wpcom-unpublished` to `1.0.7`

### PR DESCRIPTION
**Pull request by retrofox**
We've released [`wpcom-unpublished@1.0.7`](https://github.com/Automattic/wpcom-unpublished/blob/master/History.md#107--2015-11-26) and [`wpcom@4.8.2`](https://github.com/Automattic/wpcom.js/blob/master/History.md#482--2015-11-26).

There are a lot of improvements from `1.0.5` to `1.0.7`. The most importantes changes:

* Replace builder system `Browserify` by `Webpack`
* Support `Promises`

```es6
import wpcomFactory from 'wpcom-unpublished';

wpcomFactory()
    .site( '<site-id>' )
    .postsList( { number: 8 } )
        then( list => { ... } )
        catch( error => { ... } );
```

* add `runtime` in the compiling process (babel) to ensure cross-browser support (IE).

### How to test

```cli
> make clean
> make install
> make run
```

* Open the browser pointing to `http://calypso.localhost:3000/`
* If it's possible test the app under IE

### CODE REVIEW

**Comment by lancewillett** [comment]
Do you think we could standardize on `example.wordpress.com` everywhere instead of things like `your-blog.wordpress.com`?

**Comment by retrofox** [comment]
@lancewillett :+1:

**Comment by retrofox** [comment]
Actually I'm not sure if we should tie the blog instance with the `wordpress.com` domain. Many times I've talked with other developers and in general they think that the WordPress REST-API and specifically wpcom.js only work for sites installed in `wordpress.com`.

```js
import wpcomFactory from 'wpcom-unpublished';

wpcomFactory()
    .site( '<site-id>' )
    .postsList( { number: 8 } )
```

What do you think `<site-id>` ?

**Comment by lancewillett** [comment]
> What do you think <site-id> ?

Great idea.

**Comment by gwwar** [comment]
:+1: tested on OSX Chrome/FF, Win10 IE Edge/11

**Pull request merged**
