### PR TITLE
Tiled gallery: Improve loading visuals

### LINKED ISSUE #28908: Tiled gallery block: improve "loading state" styles
When converting a classic gallery block to tiled gallery block, there's a loading animation happening:

screenshot 2018-11-28 at 12 25 18

screenshot 2018-11-28 at 12 25 23

Instad of spinners, we could show gray pulsating tile:

image

There might be other situations when these loading animations are shown, too.

### PR DESCRIPTION
**Pull request by sirreal**
Resolved #28908

- Adds a pulsing placeholder background to tiled gallery images in the editor
- Adds a background to images in the frontend

This makes it clear that an image will be displayed and where as it loads.

## Testing instructions

Throttle your network so that placeholders remain visible for longer.

* Test with different gallery styles
* Test frontend and backend

Do the placeholders look good in the editor? They're based on the Calypso pulsing placeholders.
Is the gray background for images on the frontend an improvement?

### Editor

editor

### Frontend

frontend

<small>(Images are not dimensioned properly until the resize script starts. This is the current behavior and not a regression)</small>

### CODE REVIEW

**Comment by thomasguillot** [comment]
For the front-end, rather than using a plain grey colour, I'd switch to a subtle rgba colour (e.g. `rgba(0, 0, 0, 0.1)`) to make sure it doesn't clash too much with sites using a background colour other than white.

**Comment by sirreal** [comment]
> For the front-end, rather than using a plain grey colour, I'd switch to a subtle rgba colour (e.g. `rgba(0, 0, 0, 0.1)`) to make sure it doesn't clash too much with sites using a background colour other than white.

I've just applied that change @thomasguillot

**Comment by sirreal** [comment]
Updated frontend screenshot:

screen shot 2019-02-13 at 16 04 04

**Comment by sirreal** [comment]
I dropped some CSS removal that did turn out to be required. This should be ready to go.

**Pull request merged**
