### PR TITLE
Reader: Match Daily Post button with Following

### PR DESCRIPTION
**Pull request by jancavan**
This fixes: https://github.com/Automattic/wp-calypso/issues/16810

Updated in stream and fullpost.

**Before:**
screenshot 2017-08-02 12 28 26
screenshot 2017-08-02 12 28 34

**After:**
screenshot 2017-08-02 12 28 04
screenshot 2017-08-02 12 28 14

### CODE REVIEW

**Comment by fraying** [comment]
Very nice. @jancavan LGTM! 👍

**Comment by bluefuton** [comment]
Nice @jancavan!

I checked and the daily post button block is only used in Reader. Shall we change the styles for the block itself instead (`blocks/daily-post-button`), so it always looks like this wherever it is rendered?

**Comment by fraying** [comment]
@bluefuton Where else is it used? This change is primarily about making Reader consistent.

**Comment by bluefuton** [comment]
@fraying as I mentioned, the daily post button block is only used in Reader (just full post and post card) and not anywhere else in Calypso.

My feedback is just about CSS organisation: there's no point us keeping the block's underlying styles around if they're not used anywhere. @jancavan's new styles should be the default styles for the block I think.

**Comment by fraying** [comment]
@bluefuton Oh, I getcha! Good call.

**Comment by jancavan** [comment]
Thanks @bluefuton. That's what I wasn't sure about :)

Moved styles to DailyPost block instead: https://github.com/Automattic/wp-calypso/pull/16850/commits/5db1cf9eea571db5b3427910d4a6891c3e118552

**Comment by bluefuton** [comment]
I also noticed that the DailyPostButton renders inside an `li` by default, but we always use a span in practice. I'll update `span` to be the default now.

screen shot 2017-08-04 at 15 36 52

**Pull request merged**
