### PR TITLE
Framework: Add generic reducer for CRUD stores

### PR DESCRIPTION
**Pull request by jsnajdr**
Work in progress, some documentation coming soon.

### CODE REVIEW

**Comment by apeatling** [comment]
@jsnajdr Still worth keeping this one open?

**Comment by jsnajdr** [comment]
> Still worth keeping this one open?

@apeatling Yes, it's a low-priority experiment that I want to keep open. I rebased it against the latest master and resolved the conflicts. It's in a fresh state now :)

**Comment by dmsnell** [comment]
I like this and I think it's a good partner to #19060 as a way of comparing alternative implementations for what I think is the same general notion. Thanks for posting this!

**Comment by apeatling** [comment]
@jsnajdr Chatted to you in person, and you're going to look at this and re-open it again soon. :)

**Pull request closed without merging**
