### PR TITLE
Launchpad: Renamed keep-building tasklist

### PR DESCRIPTION
**Pull request by nelsonec87**
Related to https://github.com/Automattic/jetpack/pull/31905

DO NOT MERGE THIS PR until https://github.com/Automattic/jetpack/pull/31905 has been shipped to both WordPress.com Simple and Atomic sites.

## Proposed Changes

* This PR renames the `keep-building` tasklist to `intent-write`, to follow the pattern.

## Testing Instructions

**Test on a WP.com Simple site:**

* Apply D116143-code to the sandbox
* Apply https://github.com/Automattic/jetpack/pull/31905 to the sandbox
* Ensure you're working from this diff, either from calypso.live or locally
* Create a new site (`/start`) with `build` intent by selecting "Promote myself or business" during onboarding.
* Launch the site
* Make sure the Launchpad in Customer Home still shows and works:
image

**Test on an Atomic site:**

* Apply D116143-code to the sandbox
* Create a new site on the Business plan from `/start` with the Build intent and launch it.
* Install and activate a free plugin to transfer the site to Atomic infrastructure.
* SSH into your Atomic site and add `define( 'JETPACK_MU_WPCOM_LOAD_VIA_BETA_PLUGIN', true );` to your Atomic site's `wp-config.php`
* Apply https://github.com/Automattic/jetpack/pull/31905 to your Atomic site via the [Jetpack Beta plugin](https://jetpack.com/download-jetpack-beta/); in the plugin management screen, go to WordPress.com Features and search for this branch, then activate it.
* Ensure you're browsing the UI with this diff, either from calypso.live or locally.
* Visit `/home/yoursiteslug` and you should still see the Build checklist; you should be able to complete the checklist tasks.

### CODE REVIEW

**Comment by sixhours** [comment]
Haven't had a chance to code review these changes yet, but the Build Launchpad still works:

Screenshot 2023-07-18 at 10 29 58 AM

In terms of landing these, is there anything we need to be aware of in terms of waiting for Jetpack to sync to Atomic?

**Comment by sixhours** [comment]
> In terms of landing these, is there anything we need to be aware of in terms of waiting for Jetpack to sync to Atomic?

The more I think about it, the more I wonder if it's possible to rename all these variables without breaking things (even just for a few minutes), especially for Atomic sites. As I see it, the land order looks something like this:

1) [We ship the Jetpack change](https://github.com/Automattic/jetpack/pull/31905) - it goes to WordPress.com Simple relatively quickly (within a few minutes provided we ask for a sync ASAP) and Atomic sites as soon as we prepare the jetpack-mu-wpcom release (time-consuming, very manual process) and ask for it to be synced.
2) We ship the back-end change at D116143-code (it currently fails TC tests because it's missing the Jetpack change) to activate the new card in My Home (but if the front end hasn't shipped, it doesn't show anything, because it can't find the card reference).
3) We ship the front-end change (this PR) to show the newly named component/card.

I see a lot of room for error in between all these steps since we can't guarantee they all land at the same time. And if the Jetpack change fails for whatever reason we have to go through a lengthy revert process. 😬 

Would it make more sense to create a copy of the task list using the new name, but don't delete/rename the old one? That way it's still available in the event the older version of jetpack-mu-wpcom on Atomic sites goes looking for it. We could do the same for the card name to avoid front-end breakage on Simple sites as well.

Am I being paranoid? 😆

**Comment by markbiek** [comment]
> Would it make more sense to create a copy of the task list using the new name, but don't delete/rename the old one? That way it's still available in the event the older version of jetpack-mu-wpcom on Atomic sites goes looking for it. We could do the same for the card name to avoid front-end breakage on Simple sites as well.

@sixhours I don't think you're being paranoid. I think that creating a copy of the task list so both names are out there seems like the safest. We just have to remember to remove the old one once everything has been deployed everywhere.

**Review by markbiek — APPROVED** [review]
Working as expected on Simple and Atomic!

**Pull request merged**
