### PR TITLE
Reader: Add stats tracking with Tracks

### LINKED ISSUE #1216: Reader: Add tracking with Tracks
Match what we're doing in the native apps.

- [x] `reader_article_commented_on`
- [x] `reader_article_liked`
- [x] `reader_article_unliked`
- [x] `reader_article_opened`
- [x] `reader_blog_preview`
- [x] `reader_discover_viewed`
- [x] `reader_infinite_scroll_performed`
- [x] `reader_list_loaded`
- [x] `reader_reader_tag_followed`
- [x] `reader_reader_tag_unfollowed`
- [x] `reader_site_followed`
- [x] `reader_site_unfollowed`
- [x] `reader_tag_loaded`
- [x] `reader_tag_preview`

### PR DESCRIPTION
**Pull request by blowery**
Adds in Tracks tracks, matching what we do in the native apps.

Fixes #1216 

cc @robfelty @meremagee

### CODE REVIEW

**Comment by bluefuton** [comment]
Confirming the following events are being fired correctly: 
- [ ] calypso_reader_article_commented_on
- [ ] calypso_reader_infinite_scroll_performed
- [ ] calypso_reader_blog_preview
- [ ] calypso_reader_tag_loaded
- [ ] calypso_reader_list_loaded
- [ ] calypso_reader_discover_viewed
- [ ] calypso_reader_article_opened
- [ ] calypso_reader_article_liked / calypso_reader_article_unliked
- [ ] calypso_reader_reader_list_followed / calypso_reader_reader_list_unfollowed
- [ ] calypso_reader_reader_tag_followed / calypso_reader_reader_tag_unfollowed

**Comment by robfelty** [comment]
Great progress!

I looked at the first one:
https://mc.a8c.com/tracks/live/?eventname=calypso_reader_article_commented_on&user=

and it is not clear to me that we are recording which article a user commented on, which is something I think we should include.

Same comment applies to calypso_reader_article_opened (and probably the others too) - We should probably include the blog_id and post_id of the article.

Also, how is the siteidlabel being set? For stuff like posts, we currently have either 'wpcom' or 'jetpack'. For commenting on an article from the reader, should the siteidlabel always be 'wpcom'? Or should it correspond to the status of the article being commented on (an article hosted on wpcom, a jetpack site, or maybe even a non-jetpack site). I'm not even sure that is possible, but it could be an interesting thing to look at overall reader usage.

**Comment by blowery** [comment]
> Also, how is the siteidlabel being set? 

No idea. I think it's done inside the guts of the tracks client. We're not setting it explicitly. We just pass an event name and a set of props, which appear in event props.

**Comment by blowery** [comment]
> I looked at the first one and it is not clear to me that we are recording which article a user commented on, which is something I think we should include.

I think it could be useful too, but the native apps are not currently passing it. Should we just pass it as blog_ID (or blogID or blogId or ... )?

**Comment by blowery** [comment]
I'm going to land this for now so we have at least parity. Additional props can come in another PR.

**Pull request merged**
