### PR TITLE
Introduce planFeatures abtest, enable for dev and wpcalypso

### LINKED ISSUE #6502: Plans Redesign: add abtest
This task should be done after all other plan redesign issues have been completed. Remove the `manage/plan-features` feature flag and add a 50/50 abtest in its place.

### PR DESCRIPTION
**Pull request by lamosty**
This is it. Fixes #6502.

Do not merge until @apeatling && @rralian && @gwwar && @artpi say so (objections of others are welcome, too).

## Testing Instructions

1. Run Calypso normally with `make run`;
2. Put yourself in the `planFeatures` abtest of `show` variation;
3. Go to `/plans`, `/plans/compare`, `/start/test-plans`, `/plans/my-plan` and see if everything works correctly + shows something different than on wp.com;

Test live: https://calypso.live/?branch=add/plans-redesign-abtest

### CODE REVIEW

**Comment by rralian** [comment]
Can you add testing instructions? I noticed that the plans are too tight to the section nav on the plans page. I wouldn't imagine this has anything to do with the abtest code here, but we should address that before we implement this.

plans page

I also think we should separate the code for enabling this in production from the code here. Maybe just enable it in development and wpcalypso so we can give a heads-up post to happiness and let them try it out first before we launch it to everyone.

**Comment by lamosty** [comment]
> I noticed that the plans are too tight to the section nav on the plans page. I wouldn't imagine this has anything to do with the abtest code here, but we should address that before we implement this.

Could you create an issue for that, please?

> I also think we should separate the code for enabling this in production from the code here. Maybe just enable it in development and wpcalypso so we can give a heads-up post to happiness and let them try it out first before we launch it to everyone.

Will do.

**Comment by gwwar** [comment]
With the abtest enabled, navigate to http://calypso.localhost:3000/plans/compare/:mysite:

You'll be redirected to http://calypso.localhost:3000/plans without the site slug

**Comment by gwwar** [comment]
On /start/plans, the compare plans link is still shown.
screen shot 2016-07-14 at 12 05 08 pm

We should also wait for the results of @rralian's showFreePlanLink test, and update with a skip for now link if it's successful.

**Comment by gwwar** [comment]
We'll want to hold off until #6800, #6801, #6782 are fixed, and #6772 lands

**Comment by artpi** [comment]
I removed @lamosty fix for #6800 (because some sources have changed ) from this PR and put one in:
https://github.com/Automattic/wp-calypso/pull/6893

**Comment by apeatling** [comment]
#6750 also needs to merge before this can go.

**Comment by rralian** [comment]
Picking this up, rebasing, testing. I've kept a local copy of the pre-rebase version in case I screw things up.

**Comment by apeatling** [comment]
#6903 needs merging before this.

**Comment by rralian** [comment]
> #6903 needs merging before this.

@apeatling actually it doesn't. The title of this PR was not updated (I just did so), but it only enables the test in dev and wpcalypso. It doesn't launch the test to real users. Pairing this with #6904 will make this redesign much easier to test without having to use the ENABLE_FEATURES hack when you start up calypso.

**Comment by apeatling** [comment]
Okay, thanks for the clarification, in that case no reason why we can't merge this before.

**Comment by rralian** [comment]
This has been rebased and should be safe to merge. You can now manually trigger one of the `planFeatures` test variants using the debug-badge. But this only enables the feature in development and wpcalypso. So now we can avoid having to start calypso with ENABLE_FEATURES.

**Comment by retrofox** [comment]
image

image

I tested switching testings-plans and everything LGTM.

**Comment by rralian** [comment]
Thanks @retrofox! Rebasing one more time and will merge if all is good and circleci is happy.

**Pull request merged**
