### PR TITLE
Framework: Fix errors on transition from themes to signup (take 2)

### PR DESCRIPTION
**Pull request by seear**
Reverts Automattic/wp-calypso#4862

*Original PR description from #4820:*

Used to be #4467 so a lot of the review comments are there.

Addresses #3549

Because the signup pages use the logged-in Layout component, and logged-out theme showcase uses the lighter-weight logged-out layout, transitioning from logged-out showcase to the signup does not work properly as the signup components are rendered into the wrong layout component:

screen shot 2016-04-15 at 17 04 09

This PR adds the capability to render a complete logged-in layout (signup uses the logged-in layout), and changes all the signup routes to use the isomorphic router and render a complete tree, meaning that on transition from logged-out showcase to signup, a correct layout is rendered.

**To Test**
1) Check that the following routes are all working as before:
`/start*`
`/log-in*`
`/phone*`
`/jetpack`
(Jetpack testing instructions detailed in #4155)

2) Showcase --> signup flow
* Go to http://calypso.localhost:3000/design, logged-out
* Click on the ... button for a theme and click _Choose this design_
* The signup page should appear, and work, without errors in the console
* the _back_ button should return to /design, without errors

3) Maybe necessary to check that signup still works properly in the desktop app?

4) *(New)* Check that the following flow works: In 'My Sites', open the site picker. Choose 'Add New WordPress' (at the very bottom).

### CODE REVIEW

**Comment by seear** [comment]
@ockham: 221cb1a uses a classname on the Layout div to see what layout technique was previously in play, and will do the necessary unmounts when transitioning between techniques.

It also keeps track of all registered routes in the isorouter so as not to unmount unnecessarily.

**Comment by ockham** [comment]
Two questions:

1. How come you decided against the `page.exit()` approach you mentioned on Slack?
2. Do we even still need (all of) d8696e1? I'm still all for a `makeLayout` function, but maybe we should keep things granular...

**Comment by seear** [comment]
Yes, pertinent questions :)

> How come you decided against the page.exit() approach you mentioned on Slack?

This is similar to the fix I had in mind for `page.exit()`. The advantage of doing the unmount on entrance instead of exit is that we know which route is coming up, so we never need to do an unnecessary unmount.

> Do we even still need (all of) d8696e1? I'm still all for a makeLayout function, but maybe we should keep things granular...

The only part of d896e1 that we need is actually the `makeLayout` so we can re-layout after unmounting the single tree. I'll do a PR that is just the parts we need and see how it looks.

**Comment by seear** [comment]
>  I'll do a PR that is just the parts we need and see how it looks.

see #4992

**Comment by seear** [comment]
Closed in favour of simpler, less-risky #4992

**Pull request closed without merging**
