### PR TITLE
Desktop App: Improve app preferences experience

### PR DESCRIPTION
**Pull request by spen**
#### _No need to review the code at this stage, high level reviews only please :)_

app-preferences

### Motivation
I recently changed to using the Beta version of the desktop app, in doing so I had to go to the `WordPress.com > preferences` menu and noticed that the menu was sub-par for a number of reasons (design, experience, accessibility, etc.).
Compare this to other modern desktop apps (Spotify being an obvious choice) and it's plain to see that there is room for improvement.
More details can be found here: https://github.com/Automattic/wp-desktop/issues/333

As a bit of side project while AFK I decided to put together a 'prototype' of how this could look and how it could work, this PR is the starting point of the Calypso-side work needed to see a better experience when clicking the 'preferences' item in the desktop app menu.

### Testing

- Open the desktop app as it is and look at the prefences menu (`WordPress.com > preferences`)
- Go to: https://calypso.live/me/app-preferences?branch=try/desktop-improve-app-preferences-experience
- notice that nothing actually works yet!
- Take a look around, do you prefer seeing these options within Calypso's UI?
- Are there improvements to be made? (I'm sure there are!) Let me know.

#### Confusing settings?

I think the current options could be a little confusing regardless of whether they appear in the app or a separate menu, but more so when bringing in this set of desktop specific options in to the app UI (versus the seemingly separate 'native' ui that we have currently). 
For instance, we have a menu titled 'notifications', but we also have a sub-section in the app preferences for 'notifications'.
Embarking on the set of changes that I'm proposing might be a good opportunity to solidify this, but how? Do we remove the 'notifications' sub-section in app-preferences and expect folk to navigate to the existing settings page intuitively? Perhaps adding any extra desktop-specific settings to that page conditionally?

#### This PR is far from a complete set of changes

The purpose of this PR is to gather high-level opinions and conversation - it is a long way from being mergeable.

Things that are missing:
- Attention to styling details - some elements might not be spaced properly etc.
- Checking that env is desktop - we wouldn't want to include this menu if it were not applicable, eventually we would be looking to see that the feature-flag is true and that we are building the desktop client.
- State & persistence - currently the options do nothing, once I know that this is something that we agree we should build out I'll hook up the form fields to act as the current menu does, persisting the preferences and putting them in to action.

### CODE REVIEW

**Comment by folletto** [comment]
Full screenshot for future reference:

screen shot 2017-09-22 at 12 30 29

---

> Take a look around, do you prefer seeing these options within Calypso's UI?

This is a good question. To be honest, being a desktop app, I prefer having the settings in a system-level kind of window...

...but also, if that doesn't happen, I don't have any issue ;)
And it would give us more flexibility. :)

I think the design above while not ideal, it's a good start. Can we maybe implement auto-save instead of the explicit "Save Settings"?

Also, maybe it's worth not showing it inside "Me" section, but in a page with no sidebar?

**Comment by spen** [comment]
> I prefer having the settings in a system-level kind of window

This is kind of what we have right now, which looks like this:
original-prefs

This does come with some issues (beyond just my opinion of it being a sub-par experience).
I think the main one is that we don't have access to translations, at least not in the way it's currently implemented (as [an HTML file](https://github.com/Automattic/wp-desktop/blob/develop/public_desktop/preferences.html)).
Other issues that I see relate to maintainability - we couldn't really test that this works beyond manual testing and any required future changes would be difficult for a dev who doesn't know where this file lives.

> Can we maybe implement auto-save instead of the explicit "Save Settings"?

For sure! This is what I'd prefer to end up with and better mirrors how the current preferences work.
I also started to feel as though a whole card per set of options was overkill, seeing as there's currently only 1 option per set in most cases. One card might suffice?

**Comment by spen** [comment]
Just a note:
CircleCI is complaining about the `this.translate` ESlint violation in `me/sidebar/index.jsx`.
If these changes do get formalised and go through I'll first open a separate PR to address the use of `this.translate` in that file, so as to keep each change-set on target.

**Comment by folletto** [comment]
> This is kind of what we have right now, which looks like this [...]

Yep that's what I meant. Currently it "fits" the environment. It's ok if we want to switch away — the issues you mention are an extra good reason to do it.

> I also started to feel as though a whole card per set of options was overkill, seeing as there's currently only 1 option per set in most cases. One card might suffice?

I feel multiple cards are good, because they help grouping visually in logical units.
The section might need some polish in terms of visual design, but the current approach it's already functional and clean enough if we want to go ahead and give it a try. :)

**Comment by drw158** [comment]
I sort of like this idea. In general, Calypso is lacking in terms of looking like a native app. I do like the pattern of showing the settings inside of the main window, like Slack and Spotify.

**Comment by apeatling** [comment]
@spen Are we in a position for this to get merged? I do like the idea of this one.

**Comment by spen** [comment]
Thanks for the nudge @apeatling, this'll need a bit more work before being merge-ready. I'm very keen to finish it up when I get the time to do so :)

**Comment by alisterscott** [comment]
This PR needs a rebase - is it still needed?

**Comment by spen** [comment]
@alisterscott We would still benefit from brushing this up, it's just more a case of setting aside time to neaten it up. I'd be happy to close the PR and keep a note of it myself so I can get it to a mergeable state once I find the time to do so :)

**Pull request closed without merging**
