### PR TITLE
Removed sites-list from daily-post-button.

### PR DESCRIPTION
**Pull request by jorgefilipecosta**
To test:
1-	Go to the reader and open daily post blog http://calypso.localhost:3000/read/feeds/27030
2-	Press the daily post button
3-	If the user contains just one visible site, the editor opens to post on that site. If the user has more than one visible site, a site selector appears, choose a site and the editor opens to post on that site.

After being in the editor going back works fine if you press daily post button outside a post (in the post list) but crashes if you press the button inside a post. I discovered this bug while testing and checked it has an already existing problem, so I created an issue for that problem: https://github.com/Automattic/wp-calypso/issues/15371

Please be aware that the button receives a site prop but that site it receives is not the currently selected site of the user. The site that it receives, is the site of the post the user is seeing in the reader. The component just uses site prop to mark the post as read when the user presses the button.

Some notes to reviewers:
In the tests, in order to import the component, I used a required I thought about changing it to an import but I checked other tests for blocks and most of them used a require so for consistency I did the same.

The tests, test the component used by connect and don’t test the connect functions (mapStateToProps), as in the other test case we have. I think that’s not a problem because the code there uses mostly selectors (that are/should already be tested).

In my refactoring, I tried to keep the old test logic to the maximum, in order to focus on the main objective, remove sites-list. So maybe the tests are not totally well fitted to the new interface as if they were created with the new interface in mind.

### CODE REVIEW

**Comment by tyxla** [comment]
Perhaps it would be nice if we could get some reader folks to review this one: @blowery @bluefuton @samouri

**Comment by samouri** [comment]
I personally know very little about Sites-List deprecation.  Not sure if others on Reader have more experience here.

Code looks sensical to me!

**Comment by sirreal** [comment]
> Work in progress the component is completed but the tests need to be updated because they are using a site-list mock.

Is this part of the description up to date?

**Comment by jorgefilipecosta** [comment]
```
Work in progress the component is completed but the tests need to be updated because they are using a site-list mock.
Is this part of the description up to date?
```
No it was not up to date,  I removed this part from the description.

Thank you @tyxla , @sirreal , @samouri for reviewing this change.

I will put this one as ready to merge, if someone has some time to do the merge that would be perfect :)

**Comment by bluefuton** [comment]
Thank you for the contribution @jorgefilipecosta!

I've given it a final test and will 🚢  for you now.

**Comment by jorgefilipecosta** [comment]
@bluefuton Thank you for giving it a final test and merging it :)

**Pull request merged**
