### PR TITLE
Components: Cleanup showLinkIndicator prop from Card

### PR DESCRIPTION
**Pull request by tyxla**
This PR removes the newly introduced `showLinkIndicator` prop and fixes the chevron display in clickable cards to only be displayed when we have a `href`, but not when we just have an `onClick`.   This reverts some of what we did in #19272 and #19333 and fixes a bug that was found and reported by @rachelmcr (thanks!) here: #19272 (comment). 

This is an alternative (and a better one) to #19384.

To test:
* Checkout this branch.
* Go to http://calypso.localhost:3000/devdocs/design/banner
* Verify you don't see any unnecessary chevrons in the banners.
* Verify the banners with a `href` have a chevron.
* Go to http://calypso.localhost:3000/devdocs/blocks
* Verify there are no chevrons in any of the reader post cards.
* Go to http://calypso.localhost:3000/settings/manage-connection/:site, where `:site` is a Jetpack site.
* Verify the Disconnect link has a chevron.

### CODE REVIEW

**Comment by ockham** [comment]
Adding some rationale: I think the chevron kinda maps to what `href` does — take you to a different URL (which `onClick` normally doesn't, that's more for analytics, or in-page actions like showing a dialog). The exception to that rule would be legacy `href="#"` workarounds (that used to force the chevron to be displayed, and necessitated `event.preventDefault` in `onClick`), as well as `page()` calls in `onClick`.

I'd consider both band-aid fixes and workarounds, so for any instances that still show the chevron although they shouldn't (or the other way round), I'd try and remove those legacy workarounds. (I'd argue that `showLinkIndicator` would be a band-aid on top of a band-aid. 😁 )

**Comment by ockham** [comment]
Hmm, if I `grep showLinkIndicator`, I see there's still a bunch of them in `client/components/card/test/__snapshots__/index.js.snap`.

**Comment by tyxla** [comment]
Did you pull the latest branch? I updated the snapshots after I opened the PR.

**Comment by rachelmcr** [comment]
That rationale makes sense to me and this fix works in my testing — I checked the pages listed in the testing steps and did a quick scan through the rest of Calypso, and everything looked ok on my end.

**Comment by tyxla** [comment]
Thank you folks 🙇

**Comment by bluefuton** [comment]
Thanks @tyxla!

**Pull request merged**
