### PR TITLE
Preview: remove unused code

### PR DESCRIPTION
**Pull request by ianstewart**
Removing what appears to be unused preview code for the site card component.

To test: 

- Attempt to open preview with View Site in My Site/s menu
- Click on other sidebar items and make sure highlighting still works in the menu
- Click the site card and make sure nothing happens

Props @lsinger

### CODE REVIEW

**Comment by lsinger** [comment]
Thanks @marekhrabe! My gut tells me it's time to remove this, but pinging @shaunandrews to see whether he agrees. @shaunandrews, we can get right of the old site preview, right? The "site card"-based one. And go ahead with the "View Site" menu item.

**Comment by shaunandrews** [comment]
> we can get right of the old site preview, right?

Yes.

**Comment by marekhrabe** [comment]
So it's official, there are more things to delete now! Are you up for the challenge, @ianstewart? :) 

- remove `standalone-site-preview` from all configs
- go over all occurrences of `standalone-site-preview` in code and keep only code that gets run when the feature flag evaluated to true

**Comment by gwwar** [comment]
@ianstewart still looking at this one?

**Comment by lsinger** [comment]
@gwwar yes, I'm looking to nudge @ianstewart through shipping the PR.

**Comment by ianstewart** [comment]
@marekhrabe pushed some changes above that we (me and @lsinger)  _think_ takes care of everything related to preview related to the Site Card component.

**Comment by marekhrabe** [comment]
I triggered one final Canary test on this branch. Feel free to merge once green!

**Pull request merged**
