### PR TITLE
Hide Store tab on Desktop

### PR DESCRIPTION
**Pull request by psealock**
### Problem
Desktop does not yet have Store on Calypso extension enabled. Until that happens, the "Store" tab on Stats page results in an error.

screen shot 2017-11-13 at 10 12 45 am

### Fix 
Hide the tab on Desktop environment, but leave it enabled in development, stage, and production.

### Test
1. Navigate Calypso to a Site with jetpack and woocommerce enabled
2. See the "Store" tab rendered

screen shot 2017-11-13 at 9 44 27 am

3. Fire up `release/3.1.0` branch of wp-desktop
4. Using the same site, see the "Store" tab render

screen shot 2017-11-13 at 9 50 27 am

5. Checkout the matching release of calypso and cherry pick these changes
```
cd calypso
git fetch origin release/desktop/3.1.0
git checkout -b release/desktop/3.1.0
git git cherry-pick 5104f5c1cfae7978b3e0eb803999c28957cefbb7
```
6. See that the "Store" tab does not render. (NOTE: I'm getting an error on `make run`, will update when solved)

cc @justinshreve

### CODE REVIEW

**Comment by justinshreve** [comment]
The change here looks fine to stop the tab from showing.

> Desktop does not yet have Store on Calypso extension enabled. Until that happens, the "Store" tab on Stats page results in an error.

Do you know what prevents it from working? I didn't think it would currently have anything that ties it to Store since the stats page already works on normal WooCommerce Jetpack sites.

**Comment by psealock** [comment]
These properties are `undefined` in `config/desktop.json`, preventing Store from working. 

https://github.com/Automattic/wp-calypso/blob/8abd57fe22b0a778f21d8ea41967fb17d6e478d6/config/production.json#L128-L142

**Comment by justinshreve** [comment]
I meant: What prevents the stats page from working without Store? As in, what would stop us from showing the store stats page in desktop if we still had the actual Store management experience disabled for now? I was thinking they could be enabled independently since Store Stats works for Jetpack sites.

**Comment by psealock** [comment]
Ah ok I understand, good question.

The entire extension is turned for Desktop off via the extension's package.json
https://github.com/Automattic/wp-calypso/blob/73be58b265d201566017de220060e315f098def7/client/extensions/woocommerce/package.json#L6

If we want to show the store stats page in desktop and have the actual Store management experience disabled, we could include `desktop` in the above array, while keeping all the feature flags `woocommerce/extension-*` disabled.

Sounds like a good idea.

**Pull request merged**
