### PR TITLE
Unify name for the Monitor

### PR DESCRIPTION
**Pull request by simison**
Resolves partly https://github.com/Automattic/jetpack/issues/9086

We've been using these terms all over the place:
- Jetpack Monitor
- Uptime Monitor
- Downtime Monitor

This change will unify language to use "Downtime Monitor".

Similar change in Jetpack: https://github.com/Automattic/jetpack/pull/9084

"Downtime Monitor" term is already used all over [Jetpack plans page](https://jetpack.com/pricing/) and [feature intro page](https://jetpack.com/features/security/downtime-monitoring/).

"Read more" link in Calypso settings brings users to [Monitor's support page](https://jetpack.com/support/monitor/) which still needs updating. 

## Before
image

## After
image

(Extra toggle is visible only via localhost)

## Testing

- With Jetpack connected site, open `https://wordpress.com/settings/security/YOURSITE`
- I'm not sure how to test the change in plans copy, ideas?

### CODE REVIEW

**Comment by rickybanister** [comment]
This is awesome, thanks @simison!

One tiny nitpick, in the tooltip copy can it say 'Learn more about downtime monitoring' instead of 'Monitor'. We have been trying to get away with 'branding' features as proper nouns a bit and I think that would help. 

Thanks so much for jumping in here.

**Comment by simison** [comment]
>in the tooltip copy can it say 'Learn more about downtime monitoring' instead of 'Monitor'. 

Sure! Updated the "after"-screenshot above.

The tooltip is now two-liner — I tested shortening it further but:
image

**Comment by rickybanister** [comment]
Excellent!

**Comment by benhuberman** [comment]
Looks good to me. And yay, @rickybanister, for moving away from branding All The Things.

**Comment by beaulebens** [comment]
I went ahead and updated the support page to use this language.

**Pull request merged**
