### PR TITLE
wp-calypso: remove codemods from the repo

### PR DESCRIPTION
**Pull request by samouri**
Now that the [react 16 upgrade](https://github.com/Automattic/wp-calypso/projects/49) is over, and especially now that we have a dedicated [calypso-codemods repo](https://github.com/Automattic/calypso-codemods), lets delete the traces of codemods from `wp-calypso`!

### CODE REVIEW

**Comment by jsnmoon** [comment]
I'm in favor of removing these from Calypso. Have all the relevant codemods been migrated to Automattic/calypso-codemods?

**Comment by samouri** [comment]
I did a sanity check with ICFY:  
```
Commit: 334a4e4c5ac2e128b7a0ab1663ef3d4f388af73c
Author: samouri
At: 2018-03-02T22:11:59Z
Message: shrinkwrap
Delta:
no changes in production JS
```

**Comment by samouri** [comment]
> I'm in favor of removing these from wp-calypso. Have all the relevant codemods been migrated to Automattic/calypso-codemods?

I think so but I'll double check.  I know theres a new codemod being introduced by @jsnajdr right now in https://github.com/Automattic/wp-calypso/pull/22862 which of course isn't included

**Comment by jsnajdr** [comment]
@blowery I rebased this one onto the latest master and will merge later today. It obsoletes #25757.

I'd still like to arrive at some easy-to-use codemod script (https://github.com/Automattic/wp-calypso/pull/25757#issuecomment-400479345), but that's for another PR. I don't want to block other ones indefinitely.

**Pull request merged**
