### PR TITLE
Gutenboarding: Change section uri component

### PR DESCRIPTION
**Pull request by sirreal**
#### Changes proposed in this Pull Request

Change the section base of `/gutenboarding` to be something else!

3fe4f84 makes it so [`/party-time-best-onboard-yay`](https://calypso.live/party-time-best-onboard-yay?branch=gutenboarding/not-gutenboarding) should replace the base name with a single change.

Using a single JSON file should make this easily modifiable across webpack/sections/entrypoints/everywhere without having much impact on the bundle size 🤞

Another alternative may be to add a constant via webpack define plugin.

TODO
- [x] Change the basename to its final form

#### Testing instructions

* [`/new`](https://calypso.live/new?branch=gutenboarding/not-gutenboarding) works!
* [`/log-in/new`](https://calypso.live/new?branch=gutenboarding/not-gutenboarding) works (logged in and logged out)!
* [`/gutenboarding`](https://calypso.live/new?branch=gutenboarding/not-gutenboarding) redirects to `/new` 💡 
* Try login, signup, the entire flow.

### CODE REVIEW

**Comment by simison** [comment]
Let's also redirect `/gutenboarding` → new path for now since we've scattered the link all over P2s. It'll load Calypso in between but it doesn't matter much here.

**Comment by sirreal** [comment]
There should be a failing snapshot test here, that confirms the snapshot is working as expected.

**Comment by ramonjd** [comment]
Over at pbAok1-vY-p2#comment-1155 we suggested changing the section name from `/gutenboarding` to `/new`.

There's a `?new` parameter [we attach to a post-login redirect to create a site](https://github.com/Automattic/wp-calypso/blob/master/client/landing/gutenboarding/components/signup-form/index.tsx#L108).

Just raising it in case it we prefer to avoid ambiguous terms: `/new/create-site?new`

 Having said all this, `/party-time-best-onboard-yay` is a contender in my book.

**Comment by simison** [comment]
Javi was asking somewhere if this really needs a constant since it’s likely not going to change once done. I guess comparison would be any other flow, which we don't define via constants either?

**Review by ockham — APPROVED** [review]
Working well, and looking good! :tada: 

I like the Webpack define constant plugin alternative, but it's nothing we should explore before the CfT.

**Comment by sirreal** [comment]
In the long term, these can _just be strings_ like all the other sections.

Using a dedicated JSON file should help us transition away: Remove the file and fix the errors.

I think we can keep this for a little while just in case 🙂

**Comment by sirreal** [comment]
IE test failure is surprising…

**Comment by sirreal** [comment]
Rebased in hopes e2e is fixed 🤞

**Comment by sirreal** [comment]
The same ie e2e canaries seem to be failing on all new branches:

- https://github.com/Automattic/wp-calypso/pull/40807
- https://github.com/Automattic/wp-calypso/pull/40842
- https://github.com/Automattic/wp-calypso/pull/40841

**Comment by sirreal** [comment]
The e2e failure is a known issue failing all PRs. Proceeding with this.

**Pull request merged**
