### PR TITLE
Performance Profiler: Center screenshot only in mobile view

### PR DESCRIPTION
**Pull request by epeicher**
## Proposed Changes

* Update the media query to center the screenshot only in `mobile` view.
* For viewports greater than mobile, the screenshot will be left-aligned when it wraps to next line

Further context: p1726494298986469/1726494143.357009-slack-C02JPCHEKDY

#### Mobile tab

https://github.com/user-attachments/assets/f9f0dbd5-8caf-40c5-816b-407bf7660d5c

#### Desktop tab

https://github.com/user-attachments/assets/4def9bb0-2b35-43b4-852c-fa0dec28dad5

## Why are these changes being made?

* To fix some issues with the current view

## Testing Instructions

* Open the Performance Tool and resize the screen
* Check that when the screenshot wraps to the next line, it aligns correctly to the left.
* Check when reaching the mobile view, it centers
* Check it approximately matches suggestions in [this comment](https://github.com/Automattic/wp-calypso/pull/94551#issuecomment-2355011832)

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Comment by WBerredo** [comment]
Is there a way to get the same behavior for the desktop tab?

CleanShot 2024-09-13 at 12 51 58@2x

**Comment by epeicher** [comment]
> Is there a way to get the same behavior for the desktop tab?

Yes, passing the selected tab to the component, and adding specific classes for `desktop` or `mobile`. 
Alternatively, using a break-point larger will help, but there will be a scenario where the `Mobile` tab will center their components before wrapping
|Increasing the breakpoint to `1024px` |
|-------|
| CleanShot 2024-09-13 at 17 59 04@2x|

**Comment by cpapazoglou** [comment]
This adds padding to the whole section which doesn't seem nice. We need a better solution.

CleanShot 2024-09-13 at 19 01 14

**Comment by cpapazoglou** [comment]
It seems the whole section needs more thought, since longer sentences will push the screenshot to the next row. I believe that setting a specific space for desktop breakpoints eg 70% left, 30% right and changing those t wrap in non desktop breakpoints can produce better and more consistent results.

CleanShot 2024-09-13 at 19 05 59

**Comment by epeicher** [comment]
Hi @cpapazoglou, I have updated the breakpoint to center items only in mobile view as suggested here p1726494298986469/1726494143.357009-slack-C02JPCHEKDY. Please let me know if you find any issues.

**Comment by cpapazoglou** [comment]
It looks better. Unrelated with this PR but couldn't resist mentioning it, the image in desktop wraps in the next line https://container-great-beaver.calypso.live/speed-test-tool?url=https%3A%2F%2Fblecyclingclub.gr%2F&hash=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpZCI6NzYyN30.c_2UVEdG6YgpH38xg-d6ZHMfvE8bDCbtpqejXNnSN-o&tab=desktop&filter=all 

CleanShot 2024-09-16 at 17 43 34

**Comment by epeicher** [comment]
> the image in desktop wraps in the next line

@cpapazoglou , could you expand on it? I am not sure what you mean, sorry if it is obvious 😅

**Comment by epeicher** [comment]
I have defined a `flex-basis` space on the left of `710px`. On the right, I have defined `300px` only for Desktop screenshots because when the image wraps to the next line for Mobile screenshots, they need to align correctly to the left.

These are the different behaviors and alignments:

|Alignment of Desktop screenshot | Screenshot without wrapping text|
|-------|------|
|  CleanShot 2024-09-17 at 09 52 41@2x| CleanShot 2024-09-17 at 10 15 03@2x|


##### Responsive behaviour of the Desktop screenshot

https://github.com/user-attachments/assets/dbf00d90-489a-4071-9407-c422aa74bb93

##### Responsive behaviour of the Mobile screenshot

https://github.com/user-attachments/assets/0a6befe9-6e5b-44c9-9f20-e71ef83d15fb


@cpapazoglou , @matt-west, please review it and let me know if you have any other suggestions.

**Review by cpapazoglou — APPROVED** [review]
Thanks for iterating on it! LGTM

**Comment by matt-west** [comment]
We should allow the performance score bar to scale in order to preserve the two-column layout for longer. It's okay if the text wraps. We can apply `text-wrap: balance;` to avoid widows.

image

**Comment by epeicher** [comment]
Latest changes include: 
- Allow the performance score bar to scale in order to preserve the two-column layout for longer. 
- Add `text-wrap: balance` to the text at the bottom. 
- Split the text next to the chip based on the link

The responsive behavior videos have been [updated in the Description](https://github.com/Automattic/wp-calypso/pull/94551#issue-2525060733) for both `Mobile` and `Desktop` tabs.

**Review by gavande1 — APPROVED** [review]
Thank you! LGTM 👍

**Pull request merged**
