### PR TITLE
Check if Simple flow before creating new homepage

### LINKED ISSUE #61215: Seller experience: The simple flow pattern is applied to the homepage even when choosing Woo.
If a user selects the "more power" (Woo) option, and bails before doing anything else, they still get their homepage updated to the "start simple" commerce pattern. This should only happen if the user explicitly selects the "start simple" option.

### PR DESCRIPTION
**Pull request by nelsonec87**
#### Changes proposed in this Pull Request

* Added store type choice information to the dispatch call and a check before creating a new homepage.

#### Testing instructions

* Switch to this PR, navigate to `/start`
* Create a new free site
* Choose Sell at the intent step
* Choose the Simple option => it should create a new homepage with the payment block
* Create a new free site
* This time choose the More Power option => it should _not_ create a new homepage

Fixes #61215

### CODE REVIEW

**Comment by andres-blanco** [comment]
This is working OK! Try re-triggering the CI jobs to see if the E2E Tests pass

**Comment by nelsonec87** [comment]
> This is working OK! Try re-triggering the CI jobs to see if the E2E Tests pass

Just re-triggering didn't work, but getting new stuff from trunk did the trick :)

**Review by andres-blanco — APPROVED** [review]
Retested on calypso.live and everything works as expected!

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/7152200

Hi @nelsonec87, could you please edit the description of this PR and add a screenshot for our translators? Ideally it'd include this string: `Available now!`

Thank you in advance!

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/7152200).

**Pull request merged**
