### PR TITLE
Editing Toolkit: Fix IE11 syntax error, new dependencies to transpile

### PR DESCRIPTION
**Pull request by david-szabo97**
#### Changes proposed in this Pull Request
These dependencies aren't being transpiled which causes `syntax error` in IE 11. This PR adds both dependencies to the list of modules that should be transpiled.

* `dom7` (https://github.com/nolimits4web/dom7/issues/21)
* `swiper` (https://github.com/nolimits4web/swiper/issues/3285)

#### Testing instructions
Testing locally
* run `yarn dev`
* cd to `wp-calypso/apps/editing-toolkit`
* run `yarn wp-env start`
* You should be able to access a WordPress instance at `localhost:4013`
* Verify block editor works in IE11 and no errors in the console

### CODE REVIEW

**Comment by simison** [comment]
Where's the `swiper` dependency coming from? 🤔  Newspack?

I see it in deps but not used anywhere: https://github.com/Automattic/wp-calypso/search?q=swiper&unscoped_q=swiper

**Comment by david-szabo97** [comment]
@simison Looks like it's used by Jetpack 
https://github.com/Automattic/jetpack/blob/3b5cf194ac4e43c57f07784d6f0171802314d3d9/extensions/blocks/slideshow/slideshow.js

Now I'm even more confused 🤔 Probably we can remove the swiper dependency from Editing Toolkit but we still need to keep the swiper in the transpile list since Jetpack is depending on it.

**Comment by ockham** [comment]
> @simison Looks like it's used by Jetpack
> https://github.com/Automattic/jetpack/blob/3b5cf194ac4e43c57f07784d6f0171802314d3d9/extensions/blocks/slideshow/slideshow.js

Yep, used by the Slideshow block in JP.
 
> Now I'm even more confused  Probably we can remove the swiper dependency from Editing Toolkit but we still need to keep the swiper in the transpile list since Jetpack is depending on it.
> 
> EDIT: Newspack is also using Swiper.

Probably also in a Slideshow block (which is likely based on the JP one).

Newspack blocks are included in the Editing Toolkit, aren't they? So the swiper dependency likely needs to stay.

**Comment by simison** [comment]
Gotcha, so to summarize:

- Swiper dep needs to be in transpilation list for both jetpack and newspack.

- Swiper dep ended up in package.json in calypso originally due newspeak.

Since we these have Newspack as an actual dependency in calypso packpge.json (it used not to be), we should inherit their deps and not need to manually keep them up to date here. Hence Swiper can be removed in package.json

**Review by simison — APPROVED** [review]
👍 

Looks good and CI turning green should be enough test for this.

**Pull request merged**
