### PR TITLE
Upgrade Prettier to v1.18.2 of the WP fork

### PR DESCRIPTION
**Pull request by jsnajdr**
Two significant changes:

Formatting template literals doesn't do line breaks that don't look good, it rather prefers the line to go over the maximum length.

No longer this:
```js
`This is a string with ${
  first.param
} and ${
  second.param
}`
```

But do this:
```js
`This is a string with ${ first.param } and ${ second.param }`
```

The second change is a lot of spacing bugfixes in TypeScript, at places where square brackets are involved (indexed access, tuples, ...). These are bugfixes in the fork rather than the upstream, adding spaces where appropriate:
```ts
interface QueryArgs {
  [ key: string ]: Primitive;
}

function Component( props: Draggable[ 'props' ] ) {}

const installerPositionalArguments: [ 'akismet', 'vaultpress' ] = [ 'akismet', 'vaultpress' ];
```

### CODE REVIEW

**Comment by sirreal** [comment]
> ```ts
> function Component( props: Draggable[ 'props' ] ) {}
> ```

We inherit this from the WordPress PHP coding standards, [which are funny about this point:](https://make.wordpress.org/core/handbook/best-practices/coding-standards/php/#space-usage)

```php
$x = $foo['bar']; // correct
$x = $foo[ 'bar' ]; // incorrect

$x = $foo[0]; // correct
$x = $foo[ 0 ]; // incorrect

$x = $foo[ $bar ]; // correct
$x = $foo[$bar]; // incorrect
```

Noting this as a peculiar decision I don't understand the reasoning for, which we could chose to follow or not. As far as I'm concerned, if we want space inside bracket/brace/paren delimiters, we might as well keep it in all of theme.

**Review by sirreal — APPROVED** [review]
Thanks for the update 👍

**Comment by jsnajdr** [comment]
> We inherit this from the WordPress PHP coding standards

That's suprising news for me, as Calypso and Gutenberg have always put spaces inside square brackets, no matter what exactly is inside.

This update doesn't affect JavaScript code -- it's formatted the same way as it's been for the last two years. It's only the TypeScript type definition syntax that's now formatted consistently.

**Comment by xknown** [comment]
@jsnajdr I think this change breaks this command https://github.com/Automattic/wp-calypso/blob/14643a83387b2aefc7b5d913ec0b3f4d3b248d03/package.json#L254, `node_modules/.bin/prettier` doesn't longer exist.

**Comment by sirreal** [comment]
> `node_modules/.bin/prettier` doesn't longer exist.

Good spot, [this change](https://github.com/Automattic/wp-prettier/commit/48711a04b03b0ec8539f5f5573fd3a9cc164a621) makes it register the bin as `node_modules/.bin/wp-prettier` now 😞

**Comment by jsnajdr** [comment]
I'm working on forcing the binary name to `prettier`. PR coming soon.

**Comment by jsnajdr** [comment]
@xknown @sirreal Fixed in #36258, where the `wp-prettier` tarball is updated. Its `package.json` used to specify:
```
{
  "bin": "./bin-prettier.js"
}
```
and I fixed the issue by changing it to:
```
{
  "bin": {
    "prettier": "./bin-prettier.js"
  }
}
```

That makes it clear what the binary name is, and prevents defaulting it to the package name (`wp-prettier`).

I plan to publish the fork to NPM as `wp-prettier` today, and specify it in Calypso's `package.json` as an alias:
```
"devDependencies": {
  "prettier": "npm:wp-prettier@1.18.2"
}
```
That will make the fork available under the name `prettier` inside the project: both `require( 'prettier' )` and `node_modules/.bin/prettier` will point to the fork, as expected.

I didn't catch the bug in the original PR because my local `node_modules` was polluted: there were both the `node_modules/prettier` and `node_modules/wp-prettier` directories. Recreating it from scratch fixed that and now I can easily reproduce.

**Pull request merged**
