### PR TITLE
Included hostname in boot message.

### LINKED ISSUE #467: Onboarding: No indication of URL in the console until you first try loading Calypso in the browser
Once I have built Calypso, until I try loading it in the browser the only indication I get in the console is:

`wp-calypso booted in 680ms - port: 3000`'

It doesn't tell me what URL to go to. Unless I know that, I wouldn't have any idea unless I read the readme, and we know a lot of people won't be doing that.

Of course once I load it, because I know the URL it shows it in the console:

`Compiling assets... Wait until you see READY! and then try http://calypso.localhost:3000/ again.`

this information needs to be shown sooner, without the need to try it in the browser first. /cc @nb

### PR DESCRIPTION
**Pull request by nobuti**
This PR fixes #467.

### CODE REVIEW

**Comment by nobuti** [comment]
cc @apeatling

**Comment by mtias** [comment]
cc @nb and @folletto

**Comment by sirbrillig** [comment]
Tested (Mac OS, node v5.1.1) and works for me!

**Comment by sirbrillig** [comment]
Thanks, @nobuti! :tada:

**Pull request merged**
