### PR TITLE
Site Settings: add blog posts per page setting

### PR DESCRIPTION
**Pull request by jonathansadowski**
This PR adds a setting to adjust the `posts_per_page` option to the "Site Profile" section of a site's "General" settings.

image

The setting only shows up when the API returns the current settings.

To test:

* Visit the settings page for your site, and make sure that the setting does not appear when the API response lacks the current value.
* Apply D5487-code
* Reload the page and make sure that the setting appears at the bottom of the "Site Profile" section.
* Adjust and save the value, and make sure it matches the setting you see in wp-admin.

### CODE REVIEW

**Comment by mattsherman** [comment]
I tested this. It persists the setting correctly in the normal case, with the following edge cases:

- Negative numbers are allowed in the field (the absolute value of the number is stored on the server)
- Numbers higher than the max of 150 are allowed (150 is stored on the server)
- Zero is allowed (1 is stored on the server)
- Blank is allowed (1 is stored on the server)

When you reload the page after making a change, whatever value you entered in is shown, as opposed to what was actually persisted (see cases above). Eventually the value shown is updated. This can be confusing.

In addition, the field is in the Site Profile section. However, we had said in planning that we would put this in-between Privacy and Footer Credit. I'm not opposed to the new location necessarily if we agree.

**Comment by jonathansadowski** [comment]
Thanks for the review. I've updated a bug that was causing 3 of the 4 edge cases you pointed out. I'm looking into the maximum.

**Comment by gracie** [comment]
The other setting in that section is `For each article in a feed, show` `full text` `summary`.

Do we have plans either way with this setting? It's kind of cool because, unlike excerpts and the more tag, it allows the full text to appear on the main post feed but only sends excerpts to email notifications.

**Comment by jonathansadowski** [comment]
> Do we have plans either way with this setting? 

Thanks for asking @gracie. No plans either way right now, but not ruling it out in the future.

**Comment by jonathansadowski** [comment]
> Numbers higher than the max of 150 are allowed (150 is stored on the server)

This is a limit that is currently specific to WPCOM (p195om-1bH-p2). The API doesn't indicate that the value is altered, which would require a change to the code linked in the referenced post. Given that attempting to display more than 150 posts per page is already pretty edge-case, and that it's WPCOM-specific and won't affect Jetpack or the other exceptions listed in the code referenced from that thread, I'd consider that a separate concern.

> In addition, the field is in the Site Profile section. However, we had said in planning that we would put this in-between Privacy and Footer Credit. I'm not opposed to the new location necessarily if we agree.

As discussed in p1494270813832647-slack-C14763C07, we're going to leave the setting in the "Site Profile" section for now, as it'd look weird in its own section. In the future, as more settings are added, we can decide whether or not the settings should be moved or regrouped.

**Comment by rickybanister** [comment]
This setting doesn't appear to fit within the greater context of the General tab—also there is no general tab in Jetpack settings. 

If I help wrangle a suitable location, do you think it's possible to move this over to /writing?

**Comment by jonathansadowski** [comment]
Thanks @rickybanister. Our team's main focus is currently to launch hierarchical pages, and as such we don't have any time to further iterate on the posts per page setting. With the API changes in place for WPCOM (r155891-wpcom) and the PR prepped for Jetpack (https://github.com/Automattic/jetpack/pull/7154), we welcome further iterations on this setting.

**Comment by lancewillett** [comment]
@rickybanister Moving it would be great, feel free to do so as you see fit.

**Pull request merged**
