### PR TITLE
Fix site topic step for `/start/premium|business|personal` routes

### PR DESCRIPTION
**Pull request by p-jackson**
#34163 broke these routes. The site topic step displays an empty
screen. This is a hack to get the pages showing.

### CODE REVIEW

**Review by niranjan-uma-shankar — APPROVED** [review]
Thanks for the fix! LGTM 🚢

**Review by andrewserong — APPROVED** [review]
Works for me, too! Thanks for the quick fix!

**Comment by ramonjd** [comment]
LGTM too. So many kudos to all who tested and helped!

**Comment by p-jackson** [comment]
I've fixed the e2e tests in signup that were failing due to this PR but still failing in another area that's unrelated. I'm going to merge this as I've seen subsequent tests give failures in different areas.

**Pull request merged**
