### PR TITLE
Post Revisions: Increase the max # of characters to diff

### PR DESCRIPTION
**Pull request by jblz**
This bumps the cutoff from 20000 to 50000.  Meaning:

We will now compute and display differences between revisions totaling 2.5 times more data (between the two titles and raw content).

This should (hopefully) cover most usage while still preventing giant posts from hanging the client.

## To Test

* Progressively create a post (or page) with a lot of content (around 25000 characters long)
* Save / Update often
* Diffs should be calculated and displayed in a performant fashion up until the post reaches ~ 25k chars (as computed by `String.prototype.length`)
  * After that, it should fall back to just showing the title & content of the specified revision.

### CODE REVIEW

**Comment by frontdevde** [comment]
Is the new limit of `50000` based on a specific device? Wondering if it'd make sense to test on a lower end Android device to find out the highest reasonable upper limit.

**Comment by jblz** [comment]
> Is the new limit of 50000 based on a specific device?

No.

> Wondering if it'd make sense to test on a lower end Android device to find out the highest reasonable upper limit.

I think so!

**Comment by jblz** [comment]
Unfortunately, the 50k limit performs pretty poorly on the Galaxy Nexus :(

Setup:
* I created a post with ~ 24k chars & made a few successive changes.
* Using a custom branch (https://calypso.live/post/?branch=try/show-ground-control-landscape
) which
* made the `History` button show up at this viewport size
* set the char limit to 50k (by virtue of being pointed at the other branch)

It took about 4-5 mins before it rendered & blocked the UI 😭

**Comment by jblz** [comment]
I'm going to go ahead and merge this d/t #20133

**Pull request merged**
