### PR TITLE
Update Jetpack biennial upsell

### PR DESCRIPTION
**Pull request by robertsreberski**
Related to https://github.com/Automattic/jetpack-marketing/issues/497

This PR will also resolve maintenance issue https://github.com/Automattic/jetpack-marketing/issues/479

## Proposed Changes

We're updating the biennial upsell of Jetpack products in Checkout to be more straightforward in presenting the benefits to customers about subscribing for two years directly.

Before:
CleanShot 2024-01-24 at 16 12 18@2x

After:
CleanShot 2024-01-24 at 16 11 08@2x

## Testing Instructions

* Use Calypso Live or checkout the PR locally
* Go to /checkout/jetpack/jetpack_complete
* Play with different use cases: incognito, with a12n account and credits applied, with tax region (e.g. Spain and ZIP 28004), with coupon (https://github.com/Automattic/jetpack-marketing/issues/497#issuecomment-1908338859).
* Check also /checkout/jetpack/jetpack_social_advanced_yearly that is a special case of free trial instead of intro offer. it should look like below:
CleanShot 2024-01-24 at 16 16 40@2x

### CODE REVIEW

**Review by elliottprogrammer — CHANGES_REQUESTED** [review]
All seems to be working good for all Jetpack products, however I'm seeing an issue with Akismet products:

The "Plan subscription" price appears to be incorrect, whereas it's displaying the multi-year discounted price (yearly price x 2 minus 10%), instead of simply the undiscounted 2 year price (yearly price x 2).

Go to:
`/checkout/akismet/ak_pro5h_yearly:-q-1`
OR:
`/checkout/akismet/ak_bus5k_yearly`

See screenshots:

Akismet Pro 500/mo
Markup 2024-01-25 at 16 18 45

.

Akismet Business 5k/mo
Markup 2024-01-25 at 16 16 23

**Comment by robertsreberski** [comment]
@elliottprogrammer thanks for spotting that! indeed, I've updated the equation to calculate the original price the same way as in dropdown (yearly price * 2)

**Review by elliottprogrammer — APPROVED** [review]
Awesome, Looks good now!  Tested, works good, as expected. Code looks all good.
LGTM! 👍

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/11037563

Some locales (Hebrew, Japanese) have been temporarily machine-translated due to translator availability. All other translations are usually ready within a few days. Untranslated and machine-translated strings will be sent for translation next Monday and are expected to be completed by the following Friday.

Thank you @robertsreberski for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/11037563).

**Pull request merged**
