### PR TITLE
Dependencies: Replace json-strable-stringify with fast-…

### PR DESCRIPTION
**Pull request by sirreal**
#### Changes proposed in this Pull Request

Replace json-stable-stringify package. This should be a drop-in replacement which claims to benchmark faster (I don't believe that's particularly relevant) but is a smaller bundle by removing [`jsonify`](https://www.npmjs.com/package/jsonify) dependency.

`fast-json-stable-stringify` is a fork that is more widely used, smaller, and has seen more recent maintenance.

`json-stable-stringify`:

- https://bundlephobia.com/result?p=json-stable-stringify
- https://www.npmjs.com/package/json-stable-stringify

`fast-json-stable-stringify`:

- https://bundlephobia.com/result?p=fast-json-stable-stringify
- https://www.npmjs.com/package/fast-json-stable-stringify

#### Testing instructions

* Everything works great 🤞

### CODE REVIEW

**Review by blowery — APPROVED** [review]
LGTM assuming tests pass

**Comment by sirreal** [comment]
FYI @sgomes

**Comment by sgomes** [comment]
1.4KB removed from every entrypoint with no change in functionality. Nice work, @sirreal! 🙂

**Comment by blowery** [comment]
All those lint errors... 🌧

**Comment by sirreal** [comment]
Lint errors are pretty trivial to fix: #37508

**Comment by sirreal** [comment]
Rebased to fix conflict.

**Comment by sirreal** [comment]
Rebased after #37508 fixed lint errors, I'll merge when tests pass.

**Pull request merged**
