### PR TITLE
Themes: Use photon on screenshots

### PR DESCRIPTION
**Pull request by sirreal**
We were loading huge images in the theme view. Reduce the size by using Photon.
Also adds `srcset` with 2x images.

This should be viable for `wporg` themes as well, but the the screenshot urls that appear fine in state are having `?ver=…` appended to them, it's unclear why. In this case the non-photon url is used as a fallback..

Related: #19893 #20009

## Before

Note the mismatch native/actual sizes:

before

Note the bad query (`?w=2880?w=680`)
before-html

## After
after-html
after

## Testing
1. Test logged-in and logged-out
1. Test WordPress.com and Jetpack sites
1. On a single theme page (`/theme/THEME_SLUG/MAYBE_JETPACK_SITE_SLUG`), verify everything works and displays correctly and there are no errors or warnings on the console.

### CODE REVIEW

**Comment by sirreal** [comment]
CI is lint error, not introduced by this PR.

**Comment by seear** [comment]
> any idea what's going on here?

Got an example? I see it working ok for .org themes:

screen shot 2018-03-23 at 13 34 01

**Comment by ockham** [comment]
> CI is lint error, not introduced by this PR.
> 
> That said, we could probably fix that without much trouble.

Yeah, maybe add

```jsx
alt={ i18n.translate( 'Screenshot of the %(themeName)s theme', {
	args: { themeName },
} ) }
```

while we're here?

**Comment by ockham** [comment]
>> This should be viable for wporg themes as well, but the the screenshot urls that appear fine in state are having `?ver=…` appended to them, it's unclear why
>
> @seear @ockham and idea what's going on here?

Probably for themes that are on versions past v1?

**Comment by ockham** [comment]
> Probably for themes that are on versions past v1?

Yeah, looks like. Able to repro e.g. with [Palm Beach](https://wordpress.org/themes/palm-beach/), which is on 1.3.2.

**Comment by ockham** [comment]
Can we parse and re-add the `ver=...` (or any qargs, for that matter)?

**Comment by ockham** [comment]
(As in, have photon pass it through to the original image location?)

**Comment by sirreal** [comment]
🤔 the plot thickens.

Here's what I saw:

Data _in the API response_ from `sites/SITE/themes`:
```
screenshot: "//i1.wp.com/SITE/wp-content/themes/rindby/screenshot.png"
```

Check it in state:

```js
state.themes.queries[ state.ui.selectedSiteId ].data.items.rindby.screenshot
// "//i1.wp.com/jonsurrell.mystagingwebsite.com/wp-content/themes/rindby/screenshot.png"
```

But what's going on here??????

```patch
diff --git a/client/my-sites/theme/main.jsx b/client/my-sites/theme/main.jsx
index d1fa5bc977..85a5dd0576 100644
--- a/client/my-sites/theme/main.jsx
+++ b/client/my-sites/theme/main.jsx
@@ -235,6 +235,7 @@ class ThemeSheet extends React.Component {
 		const { demo_uri, retired, isActive, isWpcomTheme } = this.props;
 		const screenshotFull = isWpcomTheme ? this.getFullLengthScreenshot() : this.props.screenshot;
 		const width = 735;
+		console.log( screenshotFull );
 		// Photon may return null, allow fallbacks
 		const photonSrc = screenshotFull && photon( screenshotFull, { width } );
 		const img = screenshotFull && (
```

Logs:

```
//i1.wp.com/jonsurrell.mystagingwebsite.com/wp-content/themes/rindby/screenshot.png (2x)
//ts.w.org/wp-content/themes/rindby/screenshot.png?ver=2.0.0 (LOTSAx)
```

Initially it's fine, then it gets replaced 🤔 

---

Oh, that `ts.w.org` looks interesting. Here's a wporg reponse (https://api.wordpress.org/themes/info/…):

```
screenshot: "//ts.w.org/wp-content/themes/rindby/screenshot.png?ver=2.0.0"
```

🤔 😕 🤔 

https://ts.w.org/wp-content/themes/rindby/screenshot.png
https://ts.w.org/wp-content/themes/rindby/screenshot.png?ver=2.0.0

Looks like the same image. That's annoying. I wonder if other themes are like that or if `?ver=x` actually changes the response…

That's annoying because Photon, the lib at least, will not handle [URLs with query params](https://github.com/Automattic/photon.js/blob/8cb033a8cc0082475018db066c33e1f687b5acf7/index.js#L64-L67).

Seems fine with [Photon](https://developer.wordpress.com/docs/photon/):

http://i0.wp.com/ts.w.org/wp-content/themes/rindby/screenshot.png?ver=2.0.0
http://i0.wp.com/ts.w.org/wp-content/themes/rindby/screenshot.png?ver=2.0.0&w=40
http://i0.wp.com/ts.w.org/wp-content/themes/rindby/screenshot.png?w=40

**Comment by sirreal** [comment]
> Can we parse and re-add the ver=... (or any qargs, for that matter)?
> (As in, have photon pass it through to the original image location?)

Works fine in my case. I believe Photon just drops the unrecognized args. I don't believe it passes any along.

Trying something like this fails:

http://i0.wp.com/ts.w.org/wp-content/themes/rindby/screenshot.png%3Fver=2.0.0?w=200

```
We cannot complete this request, remote data could not be fetched
```

**Comment by ockham** [comment]
> https://ts.w.org/wp-content/themes/rindby/screenshot.png
> https://ts.w.org/wp-content/themes/rindby/screenshot.png?ver=2.0.0

> Looks like the same image. That's annoying. I wonder if other themes are like that or if `?ver=x` actually changes the response…

My hunch is that maybe the API _supports_ different screenshots for different versions (which IMO makes sense), but few theme authors bother to upload a new screenshot for their latest version.

**Comment by ockham** [comment]
> Logs:
>
> ```
> //i1.wp.com/jonsurrell.mystagingwebsite.com/wp-content/themes/rindby/screenshot.png (2x)
> //ts.w.org/wp-content/themes/rindby/screenshot.png?ver=2.0.0 (LOTSAx)
> ```

Yeah, we purposefully fetch information from WP.org to fill in some of the gaps that a theme's `style.css` on a self-hosted site typically doesn't contain. Working around this gracefully in order to possibly enable photon could turn out a bit hairy, which is why I'd suggest to merge this PR as-is, and possibly investigate the JP/WP.org case separately.

**Comment by sirreal** [comment]
> I think the JP/WP.org `?ver=...` case is edge enough that we can merge this as is, and maybe iterate.

👍 Thanks, I agree and think we're OK to ship this.

The Photon usage is an improvement, but should fallback correctly (the photon lib returns `null` and that should be handled well).

**Pull request merged**
