### PR TITLE
Allow upgrade to business/e-commerce for atomic sites on the free plan

### LINKED ISSUE #25470: Plan upgrades not available for atomic sites where the Business plan expired
**Context:**

This was originally opened and discussed within the atomic repository here:

- 242-gh-atomic
- 478-gh-atomic
- 213-gh-atomic

After some discussion we decided to re-open it as a Calypso issue, as doesn't affect the atomic setup or infrastructure at all, but is a gap in the interface.

**Issue**:

At the moment, if an atomic site has its Business subscription expired, a new subscription cannot be purchased from the Calypso interface at http://wordpress.com/plans or at http://wordpress.com/pricing, leaving the customer with an Atomic site on a free plan and inability to install more plugins or themes, or get any benefits from the Business plan, for example access to live chat support, as their plan is effectively Free. 

They should be able to renew their plan from their Calypso interface, however there is one caveat: Customers would only be able to renew the plan as a Business (not Personal, or Premium) as explained in detail by @rralian here: 242-atomic/-#issuecomment-305918157 

However, this will not be an actual problem as at the moment customers need to contact support anyway to perform a downgrade from Business-Atomic to any other setup. Which means that enabling the possibility to renew to Business-only would reduce the friction they're suffering now, and they could contact support directly if they prefer to cancel/downgrade/etc, ... instead of being left in a grey zone where they can keep installing plugins/themes on their site but they don't have a Business plan anymore, no access to support, etc, ...

I took the freedom of marking this as High priority, as we are seeing more and more cases as the yearly renewals started to hit a few months ago, and this will only increase every day.

### PR DESCRIPTION
**Pull request by yoavf**
#### Changes proposed in this Pull Request

Add an exception to the `canUpgradeToPlan()` selector to make sure that atomic sites with expired subscriptions can re-purchase the business plan.

#### Testing instructions

* Test that you can upgrade from the plans page for an atomic site with no business subscription (remove manually from SA if necessary).

Fixes #25470

### CODE REVIEW

**Comment by yoavf** [comment]
@adamziel will sites on the ecommerce plan return true for `isSiteAutomatedTransfer()`? 
If so, it's likely that they'll need that exception as well

**Comment by yoavf** [comment]
cc @sararosso - This is meant to fix the issue of current Atomic customers who let their plan expire, and aren't able to repurchase their plan. E-commerce is likely going to be affected by the same issue. Will it be possible for expired e-commerce users to get back on the business plan?

**Comment by sararosso** [comment]
> cc @sararosso - This is meant to fix the issue of current Atomic customers who let their business plan expire, and aren't able to repurchase it. E-commerce is likely going to be affected by the same issue. Will it be possible for expired e-commerce users to get back on the business plan?

eComm plans are on a completely new infrastructure so the process and situation are going to be a bit different. Cc'ing @jhnstn about this but it's probably best not to hold up this PR.

**Comment by jhnstn** [comment]
> @adamziel will sites on the ecommerce plan return true for `isSiteAutomatedTransfer()`?
> If so, it's likely that they'll need that exception as well

Yup, `isSiteAutomatedTransfer` will return true for eCommerce sites.

> Will it be possible for expired e-commerce users to get back on the business plan?

There are some open tasks around deactivating eCommerce plans which we will should have addressed by the time the first eCommerce plans expire 🤞 
But in general a customer should be able to purchase a business plan after their eCommerce plan expires.

**Comment by yoavf** [comment]
Updated to also apply to the eCommerce plans

**Pull request merged**
