### PR TITLE
Fix spacing around domain transfer lock icon

### PR DESCRIPTION
**Pull request by wojtekn**
Related to https://github.com/Automattic/dotcom-forge/issues/9789

## Proposed Changes

I propose to fix the spacing around the domain transfer lock icon on the manage domain page and in the transfer form.

## Why are these changes being made?

The spacing between the icon and text is incorrect.

## Testing Instructions

1. Open Calypso locally or use a Calypso Live link
2. Navigate to the `/domains/manage` page
3. Locate a domain and click it
4. Confirm that spacing is fixed

|**Before**|**After**|
|---|---|
| Screenshot 2024-12-02 at 17 43 22 | Screenshot 2024-12-02 at 17 42 23 |

| **Before** | **After** |
|---|---|
| Screenshot 2024-12-02 at 17 43 30 | Screenshot 2024-12-02 at 17 42 33 |

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
 - [ ] For UI changes, have we tested the change in various languages (for example, ES, PT, FR, or DE)? The length of text and words vary significantly between languages. 
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Review by fredrikekelund — APPROVED** [review]
Works as expected 👍 I would take the opportunity to also remove the `viewBox` attribute on this line, though. The icon will align better with the baseline of the text if we do that.
https://github.com/Automattic/wp-calypso/blob/4dc9d32e75650724848582a8b98dc74a1e756724/client/my-sites/domains/domain-management/components/domain/domain-info-card/transfer/index.tsx#L43

Same thing here (we could also change the `size` attribute to `16`)
https://github.com/Automattic/wp-calypso/blob/cd54f07dc15c6bbc6be645f2672fccf25abf5b97/client/my-sites/domains/domain-management/transfer/transfer-page/index.tsx#L275

**Comment by wojtekn** [comment]
@fredrikekelund, thanks for the suggestion. I tried that, but the icon became distorted. I changed the size and viewPort for one of the icons to make them consistent, though.

**Comment by fredrikekelund** [comment]
> I tried that, but the icon became distorted

I also tested it and didn't notice any distortion 🤔 Did you see that with both icons or just one?

cc @matt-west for any design advice

**Comment by matt-west** [comment]
This looks good to me. 👍

**Pull request merged**
