### PR TITLE
Disconnect Survey: Add 'Troubleshooting' option

### PR DESCRIPTION
**Pull request by ockham**
Add the `This is temporary -- I'm troubleshooting a problem` option. Supersedes (part of) #17962. Also mentioned here: p7rd6c-12Q-p2#comment-1736

image

**Question:** Upon disconnection, this will submit the survey with `response` set to `troubleshooting`. @bubel Is that okay, do we have precedent for different wording here, or do we rather not submit the survey at all?

To test:
* Start at `/settings/disconnect-site/:site`, verify that the option is available.
* Click on the option. You're taken to the confirmation page.
* Switch to your browser console's network tab, and clear it.
* Confirm the disconnect.
* In the browser console, watch out for the request to the `survey` endpoint. Verify the request contains `survey_responses[why-cancel][response]: troubleshooting` (should be at the very bottom).

### CODE REVIEW

**Comment by seear** [comment]
> This is temporary -- I'm troubleshooting a problem

This reads to me a bit like the actual option is temporary and we will be removing it at some point. A couple of possible alternatives:
* _I'll be reconnecting my site after troubleshooting_
* _Troubleshooting_

**Comment by bubel** [comment]
This LGTM. Tests fine.

> do we have precedent for different wording here, or do we rather not submit the survey at all?

I think "I'm troubleshooting a problem." is fine. And we definitely want to still submit the survey, because understanding how many folks are disconnecting for this reason will be important.

**Comment by ockham** [comment]
>> This is temporary -- I'm troubleshooting a problem

> This reads to me a bit like the actual option is temporary and we will be removing it at some point. 

Good point.

> A couple of possible alternatives:
> * _I'll be reconnecting my site after troubleshooting_
> * _Troubleshooting_

Changed to _Troubleshooting -- I'll be reconnecting afterwards_, since I thought that _I'll be reconnecting my site after troubleshooting_ didn't emphasize the _troubleshooting_ part enough by putting it last, and _Troubleshooting_ alone didn't convey that the disconnect is supposed to be temporary.

Happy to iterate. Maybe we should ask Editorial for a Copy Review once this thing is up for testing.

**Comment by designsimply** [comment]
<blockquote>Start at /settings/disconnect-site/:site, verify that the option is available.</blockquote>

Apologies if it's a basic question: how do I get to this screen by navigating from My Sites (while using WPDesktop, for example)?

**Comment by ockham** [comment]
> <blockquote>Start at /settings/disconnect-site/:site, verify that the option is available.</blockquote>

> Apologies if it's a basic question: how do I get to this screen by navigating from My Sites (while using WPDesktop, for example)?

Legit question 😄 

My Sites > Settings > Manage Connection > Disconnect from WP.com

**Pull request merged**
