### PR TITLE
Fix/Editor overflow and background scroll for modals

### LINKED ISSUE #27806: Adding media using the "add" button on the toolbar causes the editor to jump to the top of the page
**Steps to reproduce**
Starting at URL: https://wordpress.com/post 
Add content to a new post. Make sure it's enough content so the first line scrolls off the top of the screen.

Click "add" button, click "media", select an image, and click "insert".

**What I expected**
For the post editor to stay where it was (where I added the media).

**What happened instead**
The editor jumped to the top of the post, and I had to scroll down to get back to where I added the media.

**Browser / OS version**
I have tested and replicated this in Chrome on Mac High Sierra 10.13.6

**Screenshot / Video**
http://cld.wthms.co/uoYpGK

**Context / Source**
#user-report
User reported in 1487169-zen 

Bug sounds extremely similar to this open issue: #27226

### PR DESCRIPTION
**Pull request by pandah3**
#### Changes proposed in this Pull Request

*Fixes editor overflow so that when media or hyperlink is added while user is creating a post, the page stays where the user inserted the link, rather than jumping to the top of the page. Also prevents the background body from scrolling when a modal is clicked.

An earlier proposed fix to the editor overflow was to delete a block of code that would directly break PR #26577 (which added the specified block of code to prevent background scrolling when a modal is triggered).

This should fix both the page jumping and background scrolling when a modal is clicked.

#### Testing instructions

*Add content to a new post. Make sure it's enough content so the first line scrolls off the top of the screen.

Click "add" button, click "media", select an image, and click "insert".

After image (or hyperlink) is inserted, page jumps back to the top of the page, rather than staying at the inserted media location.

Bug fixed; page stays at current user location after inserting media
Also, background body doesn't scroll when the modal dialog is popped up.

*Fixes #27806 , #27226, PR #26577

### CODE REVIEW

**Comment by jameskoster** [comment]
I'm still able to scroll the background 🤔 

scroll

**Comment by pandah3** [comment]
Thanks for the feedback!
Hmm which browser are you using?

Seems to still be working on my end (using Google Chrome):
editor test

**Comment by jameskoster** [comment]
It's working fine now, I guess my css was cached.

**Comment by pandah3** [comment]
Awesome, thanks.

**Comment by mmtr** [comment]
It seems that we both have been working on fixing the same issue, but I didn't noticed this PR until now. That caused my PR #29832 to be merged first. I'm sorry about that because your solution was also a valid one!

In fact, you're using the same approach I took at the beginning (a317984) so, as @Copons noted (https://github.com/Automattic/wp-calypso/pull/29832#issuecomment-450737171), that doesn't prevent the reflow caused by the content obtaining or losing the scrollbar.

Which is why I decided to implement a more targeted fix by applying `overflow: visible` to the HTML document only when the dialog is open.

**Comment by Copons** [comment]
Closing this because #29832 got here first.

@pandah3, thank you very much for the contribution! 🙇

**Pull request closed without merging**
