### PR TITLE
Stats: Restore legend to subscriber section

### PR DESCRIPTION
**Pull request by jsnmoon**
Related to #75245

## Proposed Changes

image

* Adds a dynamic chart legend in lieu of tooltips, which were determined to be nontrivial to implement.
* This dynamic legend can be used to selectively render data when multiple series are being rendered. See this [official demo](https://leeoniya.github.io/uPlot/bench/uPlot.html) where you can deselect series from the bottom legend.

## Testing Instructions

* Spin up the live branch for this PR.
* Navigate to the traffic stats page at `/stats/subscribers/:siteSlug` with the query string `?flags=stats/subscribers-section`.
* Ensure that the new chart renders at the bottom of the screen.
* Try resizing the window. Ensure that the chart resizes as expected.

### CODE REVIEW

**Comment by jsnmoon** [comment]
@ilonagl and @keoshi: I discovered implementing tooltips into our new charting library would be a bigger undertaking than we initially expected. While we work on sorting out the tooltip functionality, I'd like to figure out a way for us to leverage the existing legend functionality built into this new charting library:

image

What aesthetic tweaks would you recommend for this legend? I wrapped it with the card borders, but I feel like more could be done.

You should be able to [directly preview these changes at this link](https://container-great-murdock.calypso.live/stats/subscribers/jetpack.com?flags=stats/subscribers-section). If not, you can try `https://container-great-murdock.calypso.live/stats/subscribers/example.com?flags=stats/subscribers-section` replacing `example.com` with a site of your own.

P.S. These legends let us selectively render series when visualizing multi-series line charts in the future.

**Comment by keoshi** [comment]
Hey @jsnmoon — thanks for the ping, my friend!

@ilonagl and I discussed a few options just now and wanted to share our thoughts:

Because the data on this legend changes as people browse different dates with their cursor, it has a unique behavior when compared to other legends we already implemented. In other words, while other legends are static in nature, this one is interactive and gives additional context, thus requiring a more prominent placement in our opinion.

Our recommendation would be to place the legend at the top on the opposing side of the title. We also propose doing these small changes to the elements in the legend:

- Simplifying the timestamp to `Month, Year` which matches the chart axis information.
- Changing the first label from `Time:` to `Date:`.
- Makinging the blue element a circle instead of a square.
- Changing the second label from `Value:` to `Subscribers:`.

Here's how that would look like:

image

How does this sound?

**Comment by jsnmoon** [comment]
@keoshi & @ilonagl: Those changes sound good! I'll ping you two once I've made some progress implementing those changes.

**Comment by jsnmoon** [comment]
All design suggestions have been implemented:

image

**Review by grzegorz-cp — APPROVED** [review]
Awesome!

**Review by keoshi — DISMISSED** [review]
Everything behaves as expected but I noticed some things we should fix before merging:

- [x] First label is being cut off
The very first label on the X axis is being cut off both on desktop and mobile. On desktop it seems to be caused by the `overflow: clip` set on the canvas (?), and on mobile because of its position.

Desktop | Mobile
--|--
image | image

- [x] Position of legend on mobile
The legend on mobile could be improved by moving it below the title and taking the entire available width.

Before | After
--|--
image | image

Thank you!

**Comment by jsnmoon** [comment]
@keoshi: Both items have been fixed! The clipping likely occurred because the charting library renders everything onto a canvas. I've enabled automatic padding generation for the chart, which has fixed the issue.

image

**Review by a8ck3n — APPROVED** [review]
Code looks great and everything tests well for me, including the latest feedback from design peeps.

**Review by keoshi — APPROVED** [review]
Looks great, thanks as always for addressing our nitpicks! 😃

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/7924246

Thank you @jsnmoon for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/7924246).

**Pull request merged**
