### PR TITLE
Pre-populate Add G Suite fields for first user

### PR DESCRIPTION
**Pull request by belcherj**
#### Changes proposed in this Pull Request

* Pre populates the email, first name, and last name fields of the first user since we already have something the will work for most users.

#### Testing instructions

Testing New Domain Flow:

Test Flow:
* Goto Reader, refresh page
* Goto a site
* Goto Domains
* Click "Add a domain"
* Choose any domain
* Click "Yes, add email"
* Observe that you can see the G Suite user fields filed in with your details
* Ensure add another user works
* Ensure that you can click to the next screen

Before:
screen shot 2018-12-14 at 1 42 03 pm

After:
screen shot 2018-12-14 at 3 39 54 pm

Testing Existing Domain adding Email

Test Flow:
* Goto Reader, refresh page
* Goto a site with domain but no G Suite
* Goto Domains
* Goto email tab
* Click `Add G Suite` button
* Observe name is populated

Before:
screen shot 2018-12-18 at 10 46 44 am

After:
screen shot 2018-12-18 at 10 46 11 am

Do Variants for both flows:

Variant 1
* Goto your user profile
* Change your name
* Do test flow
* Observe that name doesn't change until you refresh ( user settings are not updated in Redux state )
* Observe that name is populated correctly on refresh

Variant 2
* Goto your user profile
* Remove your name
* Refresh ( user settings are not updated in Redux state )
* Do test flow
* Observe that name is not repopulated as it doesn't exist

Note:  Names can contain invalid characters but the error handling on the form picks that up.

### CODE REVIEW

**Comment by Lochlaer** [comment]
Looks really good! Thank you for setting this up!

**Comment by belcherj** [comment]
@gravityrail could we do that in another pr? I also don't like how the form is not lined up with the copy above it.

**Comment by gravityrail** [comment]
> @gravityrail could we do that in another pr? I also don't like how the form is not lined up with the copy above it.

Yep, let's do a separate design tweak PR.

**Comment by belcherj** [comment]
Added pre-population of the the G Suite form to new domain G Suite purchase.

**Comment by gravityrail** [comment]
I get an error trying to add G Suite to an existing site with an existing domain, kelleamiller.com, at URL http://calypso.localhost:3000/domains/manage/kelleamiller.com/add-google-apps/kelleamiller.com

error

**Comment by belcherj** [comment]
Change made to protect against this.

**Comment by gravityrail** [comment]
The changes protect against the error, but they still don't populate the field when it should be populated.

The following screenshots show the form fields during the signup flow CTA vs the domains CTA.

This is the same user, screenshots taken 2 mins apart. What is interesting, is that if I navigated straight from the setup flow (having skipped the autofilled GSuite step) and then go straight into Domains -> mydomain.com -> Email and set up G Suite, then the fields are populated.

However, reloading the page and navigating to set up G Suite again shows empty fields.

So clearly this is information that is being populated transiently during the setup flow and then not loaded when you're just browsing your site. Perhaps it has been preserved from the domain sign up step.

**Comment by klimeryk** [comment]
Looks like this broke the form:
```
vendors~build.d7ea041b2080d467e226.min.js:79 Uncaught TypeError: Cannot read property 'concat' of null
```

Go to Domains -> Add, select any domain and then try to click `Add Another User`
Nothing will happen and the above warning will be in the console.

**Pull request merged**
