### PR TITLE
Framework: Add .prettierignore to exclude README.md files

### PR DESCRIPTION
**Pull request by ockham**
This allows me to 'Format Files on Save' in Atom without messing up README files.

To test:
* Enable formatting on files on save in your editor.
* Verify that on `master`, this will mess up `README.md`s upon saving.
* Verify that on this branch, it won't. Also verify that `.js` files continue to be prettified on save.

### CODE REVIEW

**Comment by flootr** [comment]
Are there maybe any more files we don't want to format with prettier and which should be ignored as well? For example a `package.json`?

**Comment by ockham** [comment]
> Are there maybe any more files we don't want to format with prettier and which should be ignored as well? For example a `package.json`?

Or `.json`s, more generally, yeah. I gave adding `*.json` a quick try and didn't seem to get it to work tho. On second try, it seems to work now. Then again, maybe we can get `prettier` to actually work with `*.json` files? I think I'll merge as-is and experiment some more with `.json`s.

**Comment by jsnajdr** [comment]
> I think I'll merge as-is and experiment some more with .jsons.

@ockham Maybe you'll discover some issues caused by the Calypso fork. Let me know please if you see anything suspicious that vanilla Prettier handles well.

**Comment by ockham** [comment]
@jsnajdr Will do! However, it looks like `prettier` just isn't meant for `.json` files anyway, see #22907, and the issue referenced there.

**Comment by jsnajdr** [comment]
> looks like prettier just isn't meant for .json files anyway

Oh, I didn't know that. Quite surprising. But it's true than `JSON.stringify` does the formatting job perfectly well. It would be nice if plugins like `prettier-atom` did that when I hit the formatting shortcut.

**Pull request merged**
