### PR TITLE
Language picker: Use localized language names for search and tooltips

### PR DESCRIPTION
**Pull request by ramonjd**
This PR continues on from #13788

In the Language Picker at present, the user can only search for language names by their own languages and scripts, which means that if one wishes to switch to Japanese on a Latin alphabet (or derivative of such) keyboard, one must find a way to type 日本語. 

This PR enables searching (assuming the user's local is set to Italian) by: 

1. language autonym (e.g., _Deutsch_)
2. language code (de).
3. localized name (e.g., _Tedesco_)
4. English name (_German_).

**Search bar is now visible**: we've also made a slight UI modification in that the search bar is now visible and focussed when the modal opens.

## Screenshot: searching for Spanish

search-language-picker

## Testing
The features introduced by this PR rely on a new API endpoint, but the Language Picker itself will still work without it. 

1. Apply` D9282-code` to your sandbox.
2. Navigate to `/me/account`
3. Open the Language Picker and search for '_Japanese_'
4. Clear the search, and then search for the language slug: '_ja_'
5. Try changing your locale to _German_/_Italian_/_Spanish_ and search for _japanisch_/_giapponese_/_japonés_

### Expectations
In steps 4-6 you should see in the results: 日本語

## Considerations for further work
We are checking if any of the possible language name variations _includes_ the search string. That means that a search string of _in_ will match _Čeština_. Searching by `_.startsWith` might be better, but we would have to cater for languages names with multiple words such as _Traditional Chinese_.

### CODE REVIEW

**Comment by folletto** [comment]
The feature ROCKS.

Design wise however it's odd how the search field is now half-open. Can we keep the existing pattern of the search icon in the corner that opens covering all the filters?

**Comment by akirk** [comment]
> Design wise however it's odd how the search field is now half-open. Can we keep the existing pattern of the search icon in the corner that opens covering all the filters?

It's hard, though, to put a focus in a field when it's invisible, which is what makes the search work. Would a vertical line to the left of the search icon work? Or another idea: flip search and tabs?

**Comment by folletto** [comment]
It doesn't have to be focused. We can just capture keyboard events and open the search when a keypress is detected.

**Comment by akirk** [comment]
I've talked to @ramonjd about this before and he said that it actually wasn't that easy for reasons of state and I assume race conditions between having the field focused and back-feeding the already entered keys.

If it continues to show that this is true, is any of the design options I suggested a feasible one?

**Comment by folletto** [comment]
In that case I simply won't auto-focus. 

The above breaks a standard Calypso pattern and we shouldn't do it unless we have a better solution.

**Comment by akirk** [comment]
I think we have an unfortunate situation here that we've replaced a select dropdown that allows to click and type with something that doesn't work that way.

What about this suggestion: The search input field has a (almost) zero width when autofocussed and expands upon entered text or click on the search icon.

**Comment by folletto** [comment]
Sure, doesn't work that way because ideally the option is instantly shown in the list below: one doesn't have to search.

TBH I wouldn't introduce hacks. I understand the issue, but I'd rather implement the interception and opening on the component rather than hack the component as any future change might break it. That said, that's a technical decision, so I'd defer to you all.

**Comment by ramonjd** [comment]
Thanks @folletto and @akirk

> We can just capture keyboard events and open the search when a keypress in a specific range is detected.

I had a play around with this idea, and I thought it would be the obvious choice in terms of UX. 

Capturing key presses on the document is the easy part. As @akirk mentioned, we'll have to do some extra work/investigation around managing focus and ensuring that key press values made when the search box is closed are cached and passed onto the search component. The search component itself may need a small tweak (to allow consuming components to focus onto), which hence will require more testing to check for side-effects.

It's just chunky enough to make me think it might be out of scope for this PR. 

> I'd rather implement the interception and opening on the component rather than hack the component as any future change might break it. 

I can roll back this change, and then create another enhancement PR to experiment further with this (?).

Until then, perhaps #20815 (grouping languages by territory) will help mitigate the frustration caused by having to click on search.

**Comment by folletto** [comment]
Yep, let's experiment separately, thanks! :) 

> Until then, perhaps #20815 (grouping languages by territory) will help mitigate the frustration caused by having to click on search.

Yep. Even more, I'd expect the majority of use cases to be covered by the suggested languages from the browser. No need to search or filter further. :)

**Comment by ramonjd** [comment]
Reverted changed to the search box, and added a feature flag that prevents the HTTP call to the not-yet-deployed endpoint.

When running locally, please add the flag param:

/me/account?flags=i18n/language-names

**Comment by akirk** [comment]
Tested with the server side API and works fine 👍  I need some more time to review the code.

**Comment by ramonjd** [comment]
> Tested with the server side API and works fine 👍 I need some more time to review the code.

Thanks @akirk 

I've migrated over to v2 in `D9282-code` - will definitely appreciate your assistance on that one :)

**Comment by akirk** [comment]
Tested again with the new API and it works nicely as well. One thing that's still a little irritating to me: searching in the current UI language works (for example `Schweizerdeutsch`) but the local language name is being displayed, thus it's hard to know why it was a match. Could we display the localized name maybe in grey and smaller letters next to the local name?

**Comment by folletto** [comment]
> Could we display the localized name maybe in grey and smaller letters next to the local name?

Yes! 
...but can we do it in a separate PR so we ship this asap as it's already an improvement? :D

**Pull request merged**
