### PR TITLE
Home: Reorganize components in locations and cards

### PR DESCRIPTION
**Pull request by mmtr**
#### Changes proposed in this Pull Request

As part of the ongoing work seeking to speed up creation of My Home views after site setup, this PR:
* Reorganizes the components rendered in My Home in 2 main folders: one for the layout locations (notices, upsells, primary and secondary) and another one for all the cards (which are self-organized in card types: education, features, notices, primary).
* Moves the existing locations and cards which have been moved to their own components (namely the notices location and the celebrate, free photo library, go mobile, stats and quick links cards) into the new folders.
* Moves the primary location and the site setup checklist to their own components.

Screen Shot 2020-03-23 at 16 17 51

Rest of the locations and cards will be covered in a follow-up PR in order to keep this one small.

#### Testing instructions

- Visit "My Home".
- Make sure there are no regressions. In particular:
  - Established sites keep getting the quick links.
  - Unestablished sited keep getting the checklist.
  - There are no styling changes in the celebrate, free photo library, go mobile and stats cards.

### CODE REVIEW

**Review by gwwar — APPROVED** [review]
Nice refactor @mmtr 

Giving tentative approval here.

I think we accidentally dropped some styling for the site setup list. Once you have that tidied, feel free to :shipit: and we can fix anything else as a follow up. This will conflict with other PRs, so good to get this out of the way

Screen Shot 2020-03-24 at 2 13 52 PM

**Comment by mmtr** [comment]
Good catch @gwwar! Fixed in 09cf29a.

**Comment by mmtr** [comment]
Seems that failing tests are related to Gutenberg 7.7.1 update.

**Comment by gwwar** [comment]
Nice! Landing this one for you @mmtr !

**Pull request merged**
