### PR TITLE
Documentation: Add a code of conduct

### PR DESCRIPTION
**Pull request by codebykat**
When Swift was open-sourced, I noticed they include a <a href="https://swift.org/community/#code-of-conduct">quite nice Code of Conduct</a> for open source projects, adapted from <a href="http://contributor-covenant.org/">contributor-covenant.org</a>.

"Whoa!" I said to myself, "Calypso needs one of these awesome things!"

I do want to note that there's a similar WordPress community document being worked on <a href="https://meta.trac.wordpress.org/ticket/957">here</a>, but it's still in flux. I'd be open to using that (or some variant of it) once it's done, but I wanted to get the ball rolling on this! I think it's important to have it out there sooner rather than later.

Please weigh in with any thoughts and suggestions!

### CODE REVIEW

**Comment by aduth** [comment]
I like it!

If I were to nitpick, I'd prefer that the file name not include spaces and either be `CODE_OF_CONDUCT.md` or `CODE-OF-CONDUCT.md`.

**Comment by codebykat** [comment]
Renamed :)

**Comment by aduth** [comment]
Looks good to me :+1: I'll leave it to your discretion whether it warrants more eyes, though I have a hard time seeing why this would be objectionable to include.

**Comment by kellychoffman** [comment]
:+1: Nice.

**Comment by kwight** [comment]
This is great!

Is there a better email for inquiries than `help@wordpress.com`? I guess I wonder if we risk things languishing there, or not getting addressed in a timely manner.

**Comment by sirbrillig** [comment]
Looks awesome! :heart: I echo Kirk's comment about `help@wordpress.com`, but maybe that does go to a useful place?

**Comment by codebykat** [comment]
I thought about that too. It goes to Kayako and is the email we generally give out to folks who need private email support. I'm open to suggestions if anyone knows of a better one.

**Comment by rralian** [comment]
Seems good to me, but then again, IANAL. /cc @pesieminski

**Comment by ebinnion** [comment]
:+1: from me.

**Comment by pesieminski** [comment]
Yeah, cool idea. Really good to have for the community. 

I think the email address is probably fine - as long as the H/Es who oversee the queues know that messages re: Calypso might be in the mix. An easy thing to make known - maybe if we just also ask emailers to put something in the subject line, so it tips us off?

**Comment by johnHackworth** [comment]
hey, this has been in "almost ready to merge" for a month! :)

**Comment by ebinnion** [comment]
Adding a little blurb that suggests adding "Code of Conduct" to the subject line. If y'all are fine with it, let's :ship:.

**Comment by johnHackworth** [comment]
why is this breaking the tests?

**Comment by johnHackworth** [comment]
ooops, @ebinnion , I just rebased your commit out of existence ... sorry! >_<

**Comment by ebinnion** [comment]
Added the commit back.

**Comment by ebinnion** [comment]
This has several thumbs up. I'm going to go ahead and :ship:. We can iterate if need be.

**Comment by pesieminski** [comment]
What was the final resolution on where the emails go? And who reads them?

**Comment by ebinnion** [comment]
I don't believe there was a final resolution. I opted to asked community members to add "Code of Conduct" to the subject to help differentiate these messages in the queue.

We are currently discussing whether these should end up in the developer queue instead.

**Comment by georgestephanis** [comment]
:hamster:

**Comment by amandarush** [comment]
I think this is excellent, and thanks for adding it!

**Comment by mor10** [comment]
@codebykat Just letting you know the Swift CoC and Contributor Covenant CoC have been added to the reference documents in the referenced community CoC project.

**Pull request merged**
