### PR TITLE
Remove "Profile Links" from /me

### PR DESCRIPTION
**Pull request by okmttdhr**
Related to https://github.com/Automattic/wp-calypso/issues/94473

## Proposed Changes

This PR removes "Profile Links" from /me.

| before | after |
|--------|--------|
| Screenshot 2024-12-04 at 17 10 35 | Screenshot 2024-12-04 at 17 10 46 | 

## Why are these changes being made?

https://github.com/Automattic/wp-calypso/issues/94473#issuecomment-2516434484

## Testing Instructions

* Go to /me
* Observe no "Profile Links"
* Go to https://gravatar.com/profile/links
* Observe your links exist there if you configured them before

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
    - [ ] For UI changes, have we tested the change in various languages (for example, ES, PT, FR, or DE)? The length of text and words vary significantly between languages. 
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Review by madhusudhand — COMMENTED** [review]
I think the components `profile-links-add-other` and `profile-links-add-wordpress` can also be removed.
They are the components behind `+ Add` button and not being used anywhere (I did a quick search, please verify again).

**Comment by wojtekn** [comment]
@madhusudhand good catch, I searched for those and found no usage. We can remove those two, too.

**Review by wojtekn — APPROVED** [review]
It works correctly for me. I can't see profile links in my WPcom profile anymore, but can see and manage them on Gravatar.

**Review by fditrapani — APPROVED** [review]
Looks great @okmttdhr! Can you make sure to update the support docs after you merge this PR: https://wordpress.com/support/manage-my-profile/

**Comment by okmttdhr** [comment]
> Looks great @okmttdhr! Can you make sure to update the support docs after you merge this PR: [wordpress.com/support/manage-my-profile](https://wordpress.com/support/manage-my-profile/)

Created a request here: https://github.com/Automattic/en.support-docs-content/issues/3002 :)

**Pull request merged**
