### PR TITLE
Jetpack Plans: remove color overrides on WordPress.com

### PR DESCRIPTION
**Pull request by rcanepa**
#### Changes proposed in this Pull Request

Fixes 1164141197617539-as-1199641948041429

* Remove color overrides on WordPress.com without affecting Jetpack cloud.

#### Testing instructions

Prerequisite: a Jetpack site.

* Run this PR locally and start both Calypsos. You can also test it from the live URL but you will only be able to test Calypso Blue.
* On Calypso Blue, visit the `/plans/:site` replacing `:site` with your Jetpack site URL.
* Verify that the primary and other colors of the selected color scheme are honored.
* Change your user's color scheme and repeat the verification. Do the same with multiple color schemes.
* On Calypso Green, visit the `/pricing`.
* Verify that colors haven't changed at all and that the page looks exactly the same as in production.

#### Demo – Calypso Green
jetpack cloud localhost_3001_pricing

#### Aquatic
calypso localhost_3000_plans_inquisitive-ray jurassic ninja_site=rcdev sa ngrok io

#### Classic Blue
calypso localhost_3000_plans_inquisitive-ray jurassic ninja_site=rcdev sa ngrok io

#### Classic Bright
calypso localhost_3000_plans_inquisitive-ray jurassic ninja_site=rcdev sa ngrok io

#### Classic Dark
calypso localhost_3000_plans_inquisitive-ray jurassic ninja_site=rcdev sa ngrok io

#### Coffee
calypso localhost_3000_plans_inquisitive-ray jurassic ninja_site=rcdev sa ngrok io copy

### Contrast
calypso localhost_3000_plans_inquisitive-ray jurassic ninja_site=rcdev sa ngrok io

#### Midnight
calypso localhost_3000_plans_inquisitive-ray jurassic ninja_site=rcdev sa ngrok io

#### Sakura
calypso localhost_3000_plans_inquisitive-ray jurassic ninja_site=rcdev sa ngrok io

### CODE REVIEW

**Review by scottsweb — APPROVED** [review]
This tests well for me and can be shipped when you are ready. 

One possible enhancement is that we update the featured purple box to use the other main colour in each theme too, here are some examples:

Screenshot 2020-12-28 at 10 10 36
Screenshot 2020-12-28 at 10 11 38
Screenshot 2020-12-28 at 10 12 36

I will defer to @eeeeevon13 / @keoshi for final input on that though.

**Comment by rcanepa** [comment]
@scottsweb, I made the change you suggested because I think it looks much better when we use the primary color to highlight the featured card. I updated the screenshots accordingly.

**Comment by scottsweb** [comment]
Nice! looks good to me. The only one that looks like it might be different is the brown variation, which is using both the same colour for the buttons and feature box, I haven't tested it so it could just be a screenshot thing:

103226568-2dfdae80-490b-11eb-95d8-9b72af11b0af

**Comment by rcanepa** [comment]
> Nice! looks good to me. The only one that looks like it might be different is the brown variation, which is using both the same colour for the buttons and feature box, I haven't tested it so it could just be a screenshot thing:

Good catch, @scottsweb! I noticed that this occurs in other themes as well (e.g. Sunrise), and the issue is that on those themes the variables `--color-accent` and `--primary-color` share the same color.

**Comment by scottsweb** [comment]
I think we are probably good to go then. Thanks for your work on this.

**Pull request merged**
