### PR TITLE
Migration trial: Improve "Hosting Configuration" page

### PR DESCRIPTION
**Pull request by bogiii**
Closes https://github.com/Automattic/dotcom-forge/issues/3528

## Proposed Changes

* Hosting configuration page:
  * Show the "Upgrade plan" banner for Migration trial plan sites
  * Hide disabled features cards for Migration trial plan sites

## Testing Instructions

* Open a site with a Migration Trial plan
* Go to `Settings -> Hosting configuration` page
* Check if there is an "Upgrade plan" banner (see screenshot)
* Check if the "Upgrade plan" button leads to the plans page
* Check if the bottom of the page is without disabled features card

Screenshot 2023-08-21 at 00 19 59

Screenshot 2023-08-21 at 00 24 41

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

**Comment by javierarce** [comment]
This works fine on desktop, but on mobile looks wrong. I'll provide a design to improve this.

image

**Comment by javierarce** [comment]
I left a proposal here: nRzixgCz1TsnOLPiKr4awj-fi-1070_7133

- Added a 16px padding around the cards to match the one in the header.
- The font-size of the trial card is now 16px and the color gray-80.
- The internal padding of the trial card should be 24px to match the other boxes

image

**Comment by bogiii** [comment]
Hey @javierarce,

Thanks for catching and reporting the issue on the mobile screen.

I've fixed the issue by adjusting the Trial banner to follow the same behavior as the cards below the Trial. I did not apply a part of your proposal, for adding margins on the other cards since the other Settings pages are the same as this one, avoiding the next level of inconsistencies.

**How it looks now:**
Screenshot 2023-08-21 at 13 06 39

**Performance Settings page:**
Screenshot 2023-08-21 at 13 08 21

**Review by zaerl — APPROVED** [review]
LGTM.

**Comment by javierarce** [comment]
> I've fixed the issue by adjusting the Trial banner to follow the same behavior as the cards below the Trial. I did not apply a part of your proposal, for adding margins on the other cards since the other Settings pages are the same as this one, avoiding the next level of inconsistencies.

Oh, that makes sense, I'll take note of this problem.

I noticed that the changes I mentioned above are only applied to mobile. Sorry if I wasn't clear with my previous message, but the font size, color, and padding should be applied to desktop too to match the other cards.

I've also noticed there's a big right padding that squeezes the content in smaller screens. I think we could remove it.

Screenshot 2023-08-21 at 15 06 57

**Pull request merged**
