### PR TITLE
Reader: Fix outdated icon for manage subscriptions

### PR DESCRIPTION
**Pull request by crisbusquets**
## Proposed Changes
Update the `Manage subscription` icon to match the others and match with Jetpack Cloud > Subscribers.

Before | After
------------- | -------------
Screenshot 2024-05-24 at 16 52 28 | Screenshot 2024-05-24 at 16 52 15

## Testing Instructions

* Switch to this branch and navigate to /read

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Comment by davemart-in** [comment]
Yes! Thank you for coming up with a solution for this @crisbusquets!

This is probably just my eyes playing an optical illusion on me, but does this icon look a little off balance compared to the others? I'm not sure it actually is, but if I nudge it to the left 1px and up 1px it somehow looks more balanced to me. 

https://github.com/Automattic/wp-calypso/assets/5634774/23c546d1-c3a1-4242-8bfe-5b88e31b8196

Curious to hear your thoughts.

**Comment by crisbusquets** [comment]
> Yes! Thank you for coming up with a solution for this @crisbusquets!
> 
> This is probably just my eyes playing an optical illusion on me, but does this icon look a little off balance compared to the others? I'm not sure it actually is, but if I nudge it to the left 1px and up 1px it somehow looks more balanced to me.
> 
>  CleanShot.2024-05-24.at.11.29.05.mp4 
> Curious to hear your thoughts.

Thanks, @davemart-in !
It seems to be the icon itself (svg), which isn't properly aligned/formatted.
I'll take a look.

Screenshot 2024-05-27 at 09 11 15

**Comment by crisbusquets** [comment]
@davemart-in it should be fixed in the last commit:

| First commit | Now |
| :---: | :---: |
| 333633616-6cd7cb49-9424-4c97-b724-eb618f2ca55c | Screenshot 2024-05-27 at 11 01 54 |


## States
https://github.com/Automattic/wp-calypso/assets/25607244/04a9c2fe-e363-4db1-833b-43d3ae486ede

**Review by davemart-in — APPROVED** [review]
LGTM!

**Pull request merged**
