### PR TITLE
Use new GitHub template for Happiness Bug Report 

### PR DESCRIPTION
**Pull request by worldomonation**
#### Changes proposed in this Pull Request

This PR proposes to move the issue template for Happiness Bug Report to use GitHub issue forms.

Key changes:
- require certain fields in order to submit an issue report (eg. browser, OS, steps to reproduce).
- standardizing on options for some fields (eg. severity)

#### Testing instructions

Please review the template at [this link](https://github.com/Automattic/wp-calypso/blob/add/github-issue-templates-bug-report/.github/ISSUE_TEMPLATE/happiness-bug-report.yml).

### CODE REVIEW

**Comment by kwight** [comment]
@davipontesblog I'm good with all of this; any issues on your part?

**Comment by davipontesblog** [comment]
> @davipontesblog I'm good with all of this; any issues on your part?

Good with me! Let's just make sure the Bugomattic button directs here please and that this template also includes all the current labels the current template does, and the HE triaging project board automation.

**Comment by worldomonation** [comment]
> > @davipontesblog I'm good with all of this; any issues on your part?
> 
> Good with me! Let's just make sure the Bugomattic button directs here please and that this template also includes all the current labels the current template does, and the HE triaging project board automation.

Thanks for your feedback, I appreciate it!

> Let's just make sure the Bugomattic button directs here please 

This is a drop-in replacement for the existing form, so it should redirect here no problem. I will check that is the case after merging.

> this template also includes all the current labels the current template does

Good call, I will make sure to include the labels by default.

> HE triaging project board automation.

I will add them in!

**Comment by worldomonation** [comment]
Labels assigned by default:
- User Report
- [Type] Bug 

It appears that GitHub forms is unable to add a default project or milestone at this time. I've attempted to submit a feature request/feedback on this, but the feedback link https://github.blog/changelog/2021-06-23-issues-forms-beta-for-public-repositories/ on their [announcement](https://github.blog/changelog/2021-06-23-issues-forms-beta-for-public-repositories/) is a dead link. I've submitted a bug report to GitHub for this.

**Review by dpasque — APPROVED** [review]
LGTM!

**Pull request merged**
