### PR TITLE
Stats: remove noticon from empty state

### PR DESCRIPTION
**Pull request by drw158**
This removes the noticons being used in Stats by using a standard Notice component.

It affects 2 notices, one found on the main stats bar graph, and the other on the "Most popular day and hour" card on the Insights page.

To test:

- Pick a site with no activity
- Go to /stats and see the new notice on the bar graph
- Go to /stats/insights and see the new notice on the "Most popular day and hour" card.

Cc @shaunandrews 

Before

screen shot 2018-03-08 at 6 45 20 pm
screen shot 2018-03-08 at 4 46 04 pm

After

screen shot 2018-03-08 at 4 59 09 pm
screen shot 2018-03-08 at 4 59 00 pm

### CODE REVIEW

**Comment by Copons** [comment]
This LGTM except for the most popular box.
It looks a bit off to me because of the content behind the notice which may show up on the sides.

screen shot 2018-03-08 at 4 59 00 pm

What if we didn't render the `most-popular__item` content _at all_, and then adjust the `most-popular__wrapper` height to fit the notice?

E.g.

```jsx
{
<div className="most-popular__item">
	{ ! percent && ! requesting &&
		<span className="most-popular__label">{ translate( 'Most popular day' ) }</span>
		<span className="most-popular__day">{ day }</span>
		<span className="most-popular__percentage">
			{ translate( '%(percent)d%% of views', {
				args: { percent: percent || 0 },
				context: 'Stats: Percentage of views',
			} ) }
		</span>
	}
</div>
}
```

```sass
.most-popular.stats-module.is-empty .most-popular__wrapper,
.most-popular.stats-module.is-loading .most-popular__wrapper {
	height: 60px; // example;
}

.most-popular__empty {
	top: 5px; // example
}
```

screen shot 2018-03-09 at 15 25 19

**Comment by shaunandrews** [comment]
Nice. 👍

**Comment by drw158** [comment]
@Copons  I'll go ahead and merge, I couldn't get it to work. We can follow up with another PR though!

By the way, I tried to use your code, but I got an error saying that adject elements need to be wrapped.

**Comment by Copons** [comment]
> By the way, I tried to use your code, but I got an error saying that adject elements need to be wrapped.

@drw158 Ouch, the error is correct! 🙂
I only did a quick test via dev console, and I wrote the example without considering that.

I'll follow up with a quick fix asap!

**Pull request merged**
