### PR TITLE
Move gridicons and social-logos to vendor chunk

### PR DESCRIPTION
**Pull request by stephanethomas**
This pull request seeks to improve performance by moving two modules that rarely changes out of the `build` chunk, and into the `vendor` chunk. That way, we will only send the `gridicons` and `social-logos` modules to the browser when the latter is invalidated, which should happen way less often than the former.

###### `build.js` chunk
* Before: 2823KB
* After: 2695KB

###### `vendor.js` chunk
* Before: 833KB
* After: 962KB

Said differently, this moves 128924 bytes from `build.js` to `vendor.js`.

#### Testing instructions

1. Run `git checkout update/vendor-chunk` and start your server, or open a [live branch](https://calypso.live/?branch=update/vendor-chunk)
2. Open the [`Home` page](http://calypso.localhost:3000/)
3. Check that everything works as before

#### Additional notes

It was mentioned internally that we may want to lazy load those modules. I'm not entirely sure how we could achieve that with `<AsyncLoad />` given the [number of places](https://github.com/Automattic/wp-calypso/search?l=JSX&q=Gridicon&type=&utf8=%E2%9C%93) we use the `<Gridicon />` component.

#### Reviews

- [x] Code
- [ ] Product

### CODE REVIEW

**Comment by jsnajdr** [comment]
This looks like a very nice improvement 🙂 Thanks @stephanethomas!

Gridicons are ubiquitous everywhere in Calypso and it wouldn't make sense to async load something that's almost certain to be loaded anyway.

Social Icons are used at fewer places and it would be interesting to figure out why exactly they are part of the `build` chunk. Maybe it's because `client/components/vertical-menu`? It should be possible to load `social-logos` only in the few feature chunks that need them (Publicize, Sharing, Import, ...).

Async loading of React components like these could be tough and it's possible that the necessary overhead would actually increase the chunk size.

@blowery suggested in #18606 to load the `sanitize-html` library asynchronously. That's a much easier endeavor, because the sanitization happens only when processing responses to HTTP requests. Something that's async already, and adding one more async step is fairly trivial.

**Comment by blowery** [comment]
> Gridicons are ubiquitous everywhere in Calypso and it wouldn't make sense to async load something that's almost certain to be loaded anyway.

I _strongly_ disagree. Gridicons are images. Browsers have never blocked rendering of the page while waiting for images to download.

The point here is about reducing the size of the initial bundle that's required to render the first real paint. There's no reason that Gridicons or Social Logos need to be in the initial bundle and block the initial paint.

**Comment by blowery** [comment]
That said, this PR is totally worthwhile and I'm happy it was done! But we need to change our thinking. Right now we're horse-trading things from build into vendor. While this does help with cachablility and _may_ help with overall load perf (it depends on how big the client's pipe is and where network saturation happens), we need to start removing things entirely from the load path if we want to see real improvements in load time.

**Comment by blowery** [comment]
> I'm not entirely sure how we could achieve that with <AsyncLoad /> given the number of places we use the <Gridicon /> component.

My plan there was to introduce a shim component (likely `components/gridicons`) which loads `gridicons` async and codemod usage over to it. 

Something like
```
class AsyncGridicons extends Component {
    render() {
      const { placeholder = null, ...props } = this.props;
      return <AsyncLoad require="gridicons" placeholder={ placeholder } {...props}  />;
    }
}
```

If we wanted to deal in black magic, we might be able to use webpack to alias over to the async version.

**Comment by jsnajdr** [comment]
> I strongly disagree. Gridicons are images. Browsers have never blocked rendering of the page while waiting for images to download.

That would be true if Gridicons were `` elements that load the SVG as an external image asset. But they are not. The SVG is there as JSX markup that gets transpiled into JavaScript code. Or do I misundestand your point?

The same technique is used in `social-icons`. It's unfortunate -- I think it's very inefficient and most SVGs should exist as static assets in `public/images` -- but it's the status quo right now.

I don't know if there is some way to do SVG sprites -- i.e., download one SVG file with all gridicons as image asset and use it like ``.

**Comment by jsnajdr** [comment]
> The point here is about reducing the size of the initial bundle that's required to render the first real paint.

So, with async gridicons, the initial paint would happen faster, but all gridicons would be empty placeholders? And then, after the gridicons code is async loaded, the placeholders would be replaced with the real icons?

**Comment by Tug** [comment]
Concerning this PR, I think it's a quick win so we should merge it. I updated the status given that @jsnajdr already approved it, but I do not intend to end the discussion in any way.

Gridicons are indeed used all over the place so I think it makes sense to have it in vendors for now. I agree the current status of `gridicons` (with svg as jsx) isn't great so we should plan on fixing it as well. Async loading Gridicons sounds like a good thing, but maybe rethinking the way this library is integrated would be even better. 

> I don't know if there is some way to do SVG sprites -- i.e., download one SVG file with all gridicons as image asset and use it like .

Probably not this way but surely we can group all definitions into one big svg file, load it into the page and then use those from our `gridicons` react components.
It seems to be already available from `gridicons` actually https://github.com/Automattic/gridicons/tree/master/svg-sprite we should just use it from react :)

**Comment by blowery** [comment]
Sorry for the slow reply.. :)  

> That would be true if Gridicons were  elements that load the SVG as an external image asset. But they are not. The SVG is there as JSX markup that gets transpiled into JavaScript code. Or do I misundestand your point?

Sorry, wasn't really clear. My point was that gridicons are semantically images, not literal img tags. We can lazy-load them just like images normally do in the browser. 

> So, with async gridicons, the initial paint would happen faster, but all gridicons would be empty placeholders? And then, after the gridicons code is async loaded, the placeholders would be replaced with the real icons?

Yeah, exactly. I also agree that doing svg-as-jsx is less than ideal, but moving these things to async chunks would at least get us into the same general place as using img tags with svg contents.

**Pull request merged**
