### PR TITLE
Build: Fix inline-imports transform for TypeScript

### PR DESCRIPTION
**Pull request by sirreal**
`typeof Identifier` TypeScript type queries were being erroneously
handled by the inline-imports transform.

The wrong babel type (stringLiteral) was being inserted into the type
query, which was failing.

Replace the entire TypeQuery with
`TSLiteralType( StringLiteral( actionType ) )`.

[Check the AST:](https://astexplorer.net/#/gist/2c01aaadea7a6686b44bd4026ee8e696/e255c501819caf2b187dd7ef284dbfa9a38e062b)

```js
// ## Partial AST
//
//              TypeQuery = `typeof ${ exprName }`
//                  |
//                  |    Identifier
//                  |        |
//                  V        V
const y: Action< typeof HTTP_DATA > = { type: "HTTP_DATA"}  

// 💥 Bad rewrite, didn't want a StringLiteral there
//
//                  🤔
//               Start TypeQuery…
//                  |
//                  |        🤦
//                  |    StringLiteral
//                  |        |
//                  |        |
//                  V        V
const x: Action< typeof "HTTP_DATA" > = { type: "HTTP_DATA"}

// 👍 Good rewrite, entire TypeQuery replaced by literal
//
//          LiteralType( StringLiteral( "HTTP_DATA" ) )
//                    |
//                    V
const x: Action< "HTTP_DATA" > = { type: "HTTP_DATA"}
```

Cherry picked from #32940 where failing tests highlighted the problem.

#### Testing instructions

* #32940 [failed](https://circleci.com/gh/Automattic/wp-calypso/284534) before the cherry-picked commit, [passes after](https://circleci.com/gh/Automattic/wp-calypso/284574).

### CODE REVIEW

**Comment by dmsnell** [comment]
I'm confused on why the tests are failing. Before the inline-imports transform runs TypeScript should see the import statement, no?

**Comment by sirreal** [comment]
I've reworked this change and updated the description.

> I'm confused on why the tests are failing. Before the inline-imports transform runs TypeScript should see the import statement, no?

I don't know whether or not this ever reaches TypeScript or exactly how the stack of babel plugins, presets, etc. works. I do know that babel was encountering the `Identifier` as the RHS of the `typeof ${exprName}` in the `TSTypeQuery` where replacing the `Identifier` with a `StringLiteral` was invalid.

By replacing the entire `TSTypeQuery` with a `TypeLiteral( StringLiteral( value ) )`, the replacement is applied in a valid way.

**Comment by dmsnell** [comment]
> I don't know whether or not this ever reaches TypeScript or exactly how the stack of babel plugins, presets, etc. works. I do know that babel was encountering the Identifier as the RHS of the typeof ${exprName} in the TSTypeQuery where replacing the Identifier with a StringLiteral was invalid.

@sirreal based on what you are saying it sounds like our TypeScript babel transform isn't running before the inline imports runs. Maybe we can fix the root cause by reordering the transform sequence?

**Comment by sirreal** [comment]
I'm happy to table this while we look for a solution that addresses the root of the problem rather than covering up the symptoms.

This issue is a blocker for #32940, but none of that work is high priority so I don't mind putting it until we're able to implement a fix or decide this workaround is sufficient for now.

**Comment by dmsnell** [comment]
> I'm happy to table this while we look for a solution that addresses the root of the problem

that sounds like a good idea to me. the changes here cross multiple independent layers of abstraction/code and I'm nervous that we'll be setting up a trap for ourselves in the future.

maybe in a week from now we can reconsider merging if we haven't made any progress on a deeper fix. if we do, let's add a big explanation indicating why this is happening (Babel ordering and TypeScript not running in time) and a note that it should be removed if possible.

**Comment by sirreal** [comment]
I was looking into alternatives to the changes implemented in this PR and after rethinking it, I'm not convinced the approach here should be a considered a workaround.

`inline-imports` replaces imported string constants with literal strings:

```js
// state/action-types
export const AN_ACTION = 'AN_ACTION';

// some-file:
import { AN_ACTION } from 'state/action-types';
function anActionCreator() { return { type: AN_ACTION }; }

// some-file is transformed to:
function anActionCreator() { return { type: "AN_ACTION" }; }
```

Why should extending this to valid TypeScript constructs be considered a workaround?

```ts
// some-file:
import { AN_ACTION } from 'state/action-types';
import { Action } from 'redux';
function anActionCreator(): Action<typeof AN_ACTION> { return { type: AN_ACTION }; }

// some-file is transformed to:
import { Action } from 'redux';
function anActionCreator(): Action<"AN_ACTION"> { return { type: "AN_ACTION" }; }
```

The same way imported string constant identifiers can be replaced with a string literal, the typeof string constants can be replaced with the string constant type literal. Making this babel transform work in more contexts and resilient to different orderings of plugins and presets seems like it may be a better solution than reworking the ordering of plugins in Calypso which, as we've seen, we don't have strong guarantees about.

@dmsnell do you still feel that an approach like this is not a good solution?

**Comment by dmsnell** [comment]
> Making this babel transform work in more contexts and resilient to different orderings of plugins and presets seems like it may be a better solution than reworking the ordering of plugins in Calypso which, as we've seen, we don't have strong guarantees about.

This is a strong point @sirreal and I don't know if I can object to it; something _feels_ wrong here to me and I don't think we would have used this justification at the get-go, that it's a strong but _convenient_ explanation for the change in hindsight.

Are we sure we won't run into other issues with our transforms? I guess we won't because inline imports are unique and specific - which makes me think it's not that important to generalize this script or make it resilient - we don't need it to be.

I think what still makes me feel like this is a workaround is that our problem is that the model we want and think we have is broken. TypeScript is supposed to strip away type annotations before anything else happens and everything else should stay the same. On this specific issue I'm pretty sure that the problem is exposing itself is specifically because of the way I wrote the inline imports - and that way isn't essential.

Maybe give me a few more days to try and get to the inline-imports refactor and if I don't then merge this?

**Comment by jsnajdr** [comment]
Drive-by comment: an alternative way how to implement the inline imports would be a webpack plugin. 

It would optimize the dependency graph by recognizing if the exported binding is a string or a number (i.e., something that can have duplicate instances that are still `===` to each other) and then eliminate the import/export by inlining it.

There is existing code in webpack that, i.e., eliminates exports when `sideEffects: false` flag is present, and it's conceptually not very different.

**Comment by jsnajdr** [comment]
In #33256, I implemented a webpack plugin that does the constant inlining during the bundling step. And removed the `inline-imports` transpilation. Will that solve the TypeScript issues?

The webpack plugin can look at the actual exported values and doesn't need the name and value to be the same strings.

**Pull request closed without merging**
