### PR TITLE
Signup: Add Homepage layout step to default signup flow

### PR DESCRIPTION
**Pull request by alaczek**
Work in progress. Based on positive results of #4536

### CODE REVIEW

**Comment by alaczek** [comment]
cc @kwight

**Comment by kwight** [comment]
This will need a `rebase` to pull in the changes of #5581 , and then the `design-type` step should also be added to the `domains-with-premium` flow, which is essentially the current "default" flow.

**Comment by kwight** [comment]
Yes, looking at this again, you're right, it can go in the `desktop` and `app` flows as well. So the list is:
* `main`
* `website`
* `blog`
* `domains-with-premium`
* `desktop`
* `app`

And then just remove `layout`, which was our test flow for Triforce.

**Comment by bisko** [comment]
There are two more flows which should get this, as they are landing pages from the homepage:
`delta-blog`
`delta-site`

After the changes to the `domains-with-premium` are merged in the main code (it currently relies on an AB test), these flows would come back as landing pages and we would want them to have the `design-type` step in them.

I think a general rule would be to add the `design-type` step after `survey` in all the flows. 

There are a few flows that still don't have the `survey` step and we are checking out if they should have it.

**Comment by kwight** [comment]
> After the changes to the domains-with-premium are merged in the main code (it currently relies on an AB test)

Cool, thanks @bisko . Any idea when those changes will be made? Or can we remove using AB tests as the filter, and just use [the code from the AB test module](https://github.com/Automattic/wp-calypso/blob/5db429b4d849cfe592a404d2656dcdf49c3fd481/client/lib/abtest/index.js#L168) that does the filtering we need? This would avoid adding new "default" steps to all flows except the default flow, and then having to change it all again after the `domains-with-premium` changes are merged. Let me know if I can help at all!

**Comment by bisko** [comment]
As per [this comment](https://github.com/Automattic/wp-calypso/pull/5421#issuecomment-222215861) by @umurkontaci the ABTest reliance should be removed in the next two weeks or sooner.

Relying on the ABTests to serve a default flow/feature is not the best way to do it, but when you have a feature like the one they are testing ( `plansOnly` or `domainsWithPlans` ) and you want to be able to quickly toggle it `on` or `off` until it gets accepted, this is a good way to do it. 

I think it would be best to cater to all the flows that have the steps, because there are always some flows that have custom steps in them and it will be a bit of an overhead in the code to make a system that will guess which step is not a default and to replace/insert/remove steps :) 

For example there are a few flows that require just a user step ( Jetpack signups and Reader/Discover registrations).

For now ( _until a better way to configure and manage the steps in the flows comes up_ ) let's keep all the steps that start at the `survey` step up to date. These should be the flows that most closely follow the default flow.

**Comment by umurkontaci** [comment]
I'm removing domains-with-premium flow in a few hours so you'll be able to use your flows again; will ping you in the PR @bisko

**Comment by kwight** [comment]
This'll do it; @michaeldcain for a final check?

**Comment by michaeldcain** [comment]
:shipit:

**Pull request merged**
