### PR TITLE
[e2e] Highlight elements during test execution

### PR DESCRIPTION
**Pull request by Stojdza**
#### Changes proposed in this Pull Request

Highlight elements ( for clicks and text typing ) during test execution. This is something which we had before [#](https://github.com/Automattic/wp-e2e-tests/pull/190) [#](https://github.com/Automattic/wp-e2e-tests/pull/182), but it was [removed](https://github.com/Automattic/wp-e2e-tests/pull/1246) and it was turned off by default. Now it's turned on by default for all test runs. 

For now, [IE canaries look good](https://450637-45936895-gh.circle-artifacts.com/0/tmp/artifacts/screenshots/screenshots/FAILED-EN-DESKTOP-can-see-the--site-title--page--and-enter-the-site-title-1570541202329.png). If we see any problem there we can easily turn this off for IE.

For canaries highlighting elements is enabled through setting up env var in [CircleCI config](https://github.com/Automattic/wp-calypso/blob/160d9423cc24e93b630dfc65b76376791049cc13/.circleci/config.yml#L156). 
For full suite against live branches, env var is set [here](https://circleci.com/gh/Automattic/wp-e2e-tests-for-branches/edit#env-vars).

#### Testing instructions

* Make sure that all tests are passing in CircleCI, full suite and canaries.
* If some test fail, take a look at the video of the test execution. Are the elements highlighted?
* Run any test locally. Are the elements highlighted?

### CODE REVIEW

**Comment by bsessions85** [comment]
@Stojdza - For highlighting, check out the old e2e repo. We used to have it and the config value is still in there, but I no longer see the method that did it.

**Comment by Stojdza** [comment]
Thanks @bsessions85, I didn't know about this. So, it was added in these two PRs - https://github.com/Automattic/wp-e2e-tests/pull/190 and https://github.com/Automattic/wp-e2e-tests/pull/182. The method was removed later as a part of [_Disable promise manager_](https://github.com/Automattic/wp-e2e-tests/pull/1246), but I cannot see the reason why. 

Have you been using it at all? Was it useful? I think it can be very helpful when looking at videos of failing tests. cc @hoverduck

**Comment by bsessions85** [comment]
I haven't used it before, but it could be useful. I think we should add it back and make it something that we can easily by turned on and off as needed. I believe IE has an issue with it, so we'll want to disable it for the ie canaries.

**Comment by hoverduck** [comment]
:+1:  I always liked having that flag on when watching the tests run locally, I'm sure it'll be helpful in video replays too

**Comment by Stojdza** [comment]
> I believe IE has an issue with it, so we'll want to disable it for the ie canaries.

@bsessions85 Do you think we should put that flag in CircleCI env vars or in our config?

**Comment by bsessions85** [comment]
@Stojdza I would add it to the CircleCI config in wp-calypso

**Comment by Stojdza** [comment]
I fixed selector which apparently didn't work well with highlight script command 😬 New selector should work the same as the previous one - select first theme from the list. 

This PR is ready for review now.

**Review by bsessions85 — APPROVED** [review]
Looks good. Thanks! 🚢

**Pull request merged**
