### PR TITLE
Try: Upgrade @wordpress packages to pre-React 18

### PR DESCRIPTION
**Pull request by tyxla**
This PR aims to upgrade the `@wordpress` packages to versions before upgrading to React 18.

Still in progress and very far from ready. 

DO NOT MERGE.

### CODE REVIEW

**Comment by noahtallen** [comment]
Ah, I remember starting to look at some of these. I think the big change is that `@wordpress/data` now bundles its own types. As a result, we can remove `@types/wordpress__data`, but this also means we have to rework how we define types for some of our data stores.

Essentially, the issue `Cannot redeclare block-scoped variable 'select'.` happens because we use `declare module '@wordpress/data'` to provide our own types for data stores currently (along with `registerStore`). But `registerStore` has been deprecated now in favor of `register`, which I think allows types to work successfully without declaring the module ourselves.

Once I tried switching from `registerStore` to `register`, I recall an issue with the persistence plugin, which was never updated to handle the newer API

At that point, I had some other priorities so I didn't get a chance to follow-up.

**Comment by tyxla** [comment]
Yup 👍 What you said, essentially. I'm happy to give it a try and see where it goes. Will ping you when I get it closer 😉

**Comment by tyxla** [comment]
This got way messier than I was hoping it to be. I'm going to close it and retry another time. Maybe we should do it in smaller chunks of versions and not with such a huge leap forward.

**Comment by arthur791004** [comment]
Okay! I'll continue on https://github.com/Automattic/wp-calypso/pull/73078 to see how it works 🙂

**Comment by tyxla** [comment]
Thanks, @arthur791004. I've also left some thoughts in https://github.com/Automattic/wp-calypso/pull/73629#issuecomment-1443124320 in case that helps your scenario.

**Comment by tyxla** [comment]
I've started work on a second take in #73890 and will be working on it this week.

**Pull request closed without merging**
