### PR TITLE
Purchases: Make domain cancel and refund form work properly

### PR DESCRIPTION
**Pull request by gziolo**
Fixes error found in #465.

This change makes domain cancellation working properly.

### Testing
Apply patch `fe3b-pb`.
1. Go to http://calypso.localhost:3000/purchases.
2. Find domain purchase which is cancelable (within 48h period from purchase date).
3. Click `Cancel and Refund` link.
4. You should see cancellation flow going smoothly, including cancel information and cancel confirmation page (form).

/cc @fabianapsimoes, @scruffian 

### Review
* [x] Code review
* [x] QA review

### CODE REVIEW

**Comment by scruffian** [comment]
LGTM :+1:

**Comment by scruffian** [comment]
@rads mentioned that this will revert a fix he made for discrepancies in auto-renew date on Manage and Confirm Cancel page. He's investigating...

**Comment by fabianapsimoes** [comment]
I was able to cancel a domain past the refund window, but not newly registered ones. This is the error I'm getting:

`There was a problem canceling this purchase. Please try again later or contact support.`

screenshot-calypso localhost 3000 2015-11-24 14-20-03

**Comment by fabianapsimoes** [comment]
> There was a problem canceling this purchase. Please try again later or contact support.

In p1448371575000454-slack-upgrades, @rads mentioned this error might be caused by the user not typing a cancellation reason in the form. If that's the case, we need to improve the error message to include proper directions to users.

**Comment by fabianapsimoes** [comment]
I also noticed nothing happens if you select "I mispelled the domain".

**Comment by rads** [comment]
The server-side patch isn't actually related to this problem so we can leave it out. The client-side fix is still necessary though.

The error that @fabianapsimoes was getting was due to a blank cancellation reason field. It wasn't obvious that this was happening because we were displaying a generic error message for every case. I added a commit to display the specific error from the endpoint instead which will make it more clear what is going on.

This is ready for another review.

**Comment by fabianapsimoes** [comment]
Just noting here we decided to make the cancellation reason field optional -- though that's a change for a separate PR. See https://github.com/Automattic/wp-calypso/issues/629 and p1448371976000470-slack-upgrades.

**Comment by fabianapsimoes** [comment]
Looks good! Thanks, Rads.

> I also noticed nothing happens if you select "I mispelled the domain".

This is still an issue.

**Comment by rads** [comment]
@fabianapsimoes: I fixed the issue with the "I misspelled the domain" option with another commit to this PR. It also requires the server-side patch at `fe49-pb`.

**Comment by rads** [comment]
I was wrong about @gziolo's patch; it does seem to be necessary after all. However with the current patch it will break an older issue with the auto-renew date, so I've updated it in `fe5b-pb` to work in both cases.

**Comment by gziolo** [comment]
@rads: Thanks a lot for driving this one. I see the patch now and understand why it was needed. :+1:

**Comment by rads** [comment]
Here is a final, combined patch that includes all the changes I made: `fe5d-pb`.

**Comment by fabianapsimoes** [comment]
Yay! The form is loading now :tada: 

A few notes:

- If I select "The service isn't what I expected" / "I meant to get a free blog" / "Something not listed here", the Cancel Domain button is enabled right away. It should only be enabled once the user has checked "I understand that canceling means that I may lose this domain forever".

- If I start the cancellation flow for a domain pending cancellation confirmation via email, I'll get this error: `This upgrade cannot be cancelled`. We should improve this error message. Maybe this is related to a bug @rads mentioned, where it's not possible to cancel domain you've tried to cancel before (p1448380185000537-slack-upgrades).

Would you rather address these in separate PRs?

**Comment by fabianapsimoes** [comment]
> Maybe this is related to a bug @rads mentioned, where it's not possible to cancel domain you've tried to cancel before (p1448380185000537-slack-upgrades).

FYI, turns out this is a non-issue. We haven't been able to reproduce it with the fixes in fe5b-pb (p1448453713000606-slack-upgrades).

**Comment by gziolo** [comment]
Backend patch looks good to me. 

Can we fix 2 mentioned issues in another PR? It's better to have imperfect flow than completely broken :)

**Comment by fabianapsimoes** [comment]
Sounds good to me. Move those to https://github.com/Automattic/wp-calypso/issues/726 and https://github.com/Automattic/wp-calypso/issues/728.

**Comment by gziolo** [comment]
REST API patch `fe5b-pb` deployed.

**Pull request merged**
