### PR TITLE
Tidy up Image/Video embeds in Reader Streams

### PR DESCRIPTION
**Pull request by eoigal**
The image and video dimensions in the Reader streams seems a bit broken in places.

This is a follow up to https://github.com/Automattic/wp-calypso/pull/85371 which introduced support for the pocket casts embed.

This PR will try to fix the following issues;
- [x] Video embed dimensions not expanding properly after clicked - they should take up entire width and hide excerpt if necessary
- [x] Refactor the featured image code to be more readable - it has grown wild with the latest iterations
- [x] Image or video embeds will be consistent across all Reader streams
- [x] Pocket casts embed (or any embed) that can fit the container width

### Changes
* This updates the compact post to use the full width when expanding a video/pocket casts embed
* The feature image component is refactored to make it easier to understand what container dimensions and subsequent styling an image or video embed should have
* This passes the `isCompactPost` and `hasExcerpt` properties to some components that were missing them, which meant the featured asset wasn't been rendered consistently

See pe7F0s-1si-p2 for more details

### Testing
* Apply patch and go to a test stream with various types of post types - `read/feeds/7025646` is a good example
* Confirm the images and video render and behave as expected on Reader

### CODE REVIEW

**Comment by roo2** [comment]
It looks like this has had a side effect on the read/search page http://calypso.localhost:3000/read/search?q=Pocket+Casts+embed, the embed was previously full width 

Screen Shot 2023-12-20 at 5 32 24 pm

**Comment by roo2** [comment]
I also came across something on the search page which seems to make an existing bug slightly worse to do with posts with multiple featured images. Notice how the like button is already starting to overflow from the card on both before and after. This is on screens ~1024px wide.

Before:
Screen Shot 2023-12-20 at 5 37 52 pm

After:

Screen Shot 2023-12-20 at 5 37 27 pm

**Comment by roo2** [comment]
Also on the post details page:
Before:
Screen Shot 2023-12-20 at 5 41 19 pm
After:
Screen Shot 2023-12-20 at 5 41 29 pm

**Comment by roo2** [comment]
Also tested the "List" page which I think has the same cards as the search page http://calypso.localhost:3000/read/list/erupenkman40a8ccom/test

**Comment by eoigal** [comment]
Sorry @roo2 - this PR isn't near ready for review yet! Thanks for looking though 😄

**Review by davemart-in — APPROVED** [review]
Looking solid. Tested the feed you recommended, then ventured out to all of the other feeds. No errors. Didn't see any visual inconsistencies. This fixes a number of issues. Nicely done!

**Pull request merged**
