### PR TITLE
Checkout: add support link to summary

### PR DESCRIPTION
**Pull request by michaeldcain**
This adds a link to the Checkout Summary that triggers the inline help popover, where there are quick links to plan and purchase support, and the ability to contact support directly.

checkout-inline-help

**To Test:**
- visit Checkout
- click the "Ask a Happiness Engineer" link in the sidebar
- verify that the inline help popover opens
- verify that the inline help links are plan- and purchase-related
- verify that clicking outside of the popover will close the popover
- verify that Checkout steps complete as expected

### CODE REVIEW

**Comment by fditrapani** [comment]
Thanks for putting this together. I tested this with a paid and free site while logged into my account and saw the chat window. The chat seemed to persist beyond checkout on my free site which I don't know if it's related or not. 

When I tried to create a new free site and opened the chat, I got the forum post which wouldn't be super helpful for people in the moment. I reached out to Happiness and they were fine with us turning chat on for Free users in checkout (p8hgly-2ll-p2#comment-4423) as long as we monitor the impact. This might be something we tackle separately in another PR or monitor the impact with paid users first. For now, should we hide the prompt for free users?

image

**Comment by michaeldcain** [comment]
> When I tried to create a new free site and opened the chat, I got the forum post which wouldn't be super helpful for people in the moment… For now, should we hide the prompt for free users?

I think the help links could still be helpful. Should we instead change the "Questions? Ask a Happiness Engineer" text for free users? Maybe "Questions? Read more about plans and purchases."?

**Comment by fditrapani** [comment]
Yeah, I think that would work great. Nice idea! Can we add tracking if people are clicking on this with free vs. paid accounts?

**Comment by fditrapani** [comment]
Not sure if this is ready for testing yet but I took it for a quick try and noticed the copy wasn't loading correctly for a paid plan:

image

It updates after you toggle. 

Side note: what's going on with those credits :D

**Comment by sirbrillig** [comment]
> Side note: what's going on with those credits :D

😬 😬 😬

**Comment by niranjan-uma-shankar** [comment]
Clicking a help link in the popover opens it in the same tab, so ends up taking the user away from the checkout page. Do you think it's better to keep them on the checkout page and have these links open in a new tab?

supportlinks

**Pull request merged**
