### PR TITLE
Bulk Domain Transfer Flow - Flow redesign

### PR DESCRIPTION
**Pull request by agrullon95**
This PR addresses styling and functionality of the new Bulk domain flow

Check the designs: cv3VCaN0E2Iw5OTBJQjrad-fi-56%3A15252

CleanShot 2023-07-03 at 09 50 00@2x

CleanShot 2023-07-03 at 09 50 30@2x

## Testing Instructions

1. Live link and visit ` /setup/bulk-domain-transfer/intro`
2. Check the page

### CODE REVIEW

**Review by escapemanuele — APPROVED** [review]
I think this addresses a lot and improves the flow greatly. Let's ship this and work on improvements in following PRs 👍

**Comment by renancarvalho** [comment]
Looks good to me 👍 
Good plan @escapemanuele

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/8088422

Thank you @agrullon95 for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/8088422

Thank you @agrullon95 for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/8088422

Thank you @agrullon95 for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/8088422).

**Pull request merged**
