### PR TITLE
Stats: Add UTM builder

### PR DESCRIPTION
**Pull request by grzegorz-cp**
Related to https://github.com/Automattic/jetpack-roadmap/issues/1473

## Proposed Changes

* creating a UTM builder for URLs
* adding a feature flag for the builder
* creating a new button component capturing the logic of Calypso and Jetpack buttons
* adding new empty card trigger element for the builder

## Testing Instructions

* open the live branch
* apply `stats/utm-builder` feature flag
* go to the stats page with an empty UTM module
* click on the builder button and test it

SCR-20240606-mksq

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Review by kangzj — APPROVED** [review]
It works well and looks great! I'm happy for it to merge as is behind the feature flag 🚢 

I do have several feedback, which could be addressed in follow up PRs.

### 1. Support URL with params

image

 
We probably want to decode the URL and add UTM params. Also, please note the `&` in UTM medium input, which should be encoded - all params should be encoded to make sure the URL works well.

### 2. Cursor type for the button

image

When my cursor hovers on the button text, the cursor became a `caret`, where I'd expect an arrow. I also noticed the trigger is different than what's in the design, where it's a text link.

### 3. URL validation

It'll be good to add URL validation for the URL field and shows error if it's not valid; however this is a nice to have. It would reduce the chance of a broken URL, especially when they have to provide it to advertisers.


Great work @grzegorz-cp thanks for building the tool! Very impressive 👍

**Comment by grzegorz-cp** [comment]
Thanks for the feedback @kangzj. I added encoding for the values and updated the hover cursor.
The trigger is different because the designs were created before the design of our following project, which converts it to a button. I used that one, so we don't have to change it in the coming weeks.

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/14187488

Some locales (Hebrew, Japanese) have been temporarily machine-translated due to translator availability. All other translations are usually ready within a few days. Untranslated and machine-translated strings will be sent for translation next Monday and are expected to be completed by the following Friday.

Thank you @grzegorz-cp for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/14187488).

**Pull request merged**
