### PR TITLE
Client: Massive Codemod

### PR DESCRIPTION
**Pull request by samouri**
This PR represents an effort to run a series of codemods en-masse on the entire `client` directory.

Codemods and their order:

1. commonjs-imports-hoist
2. commonjs-imports
3. i18n-mixin-to-localize
4. react-create-class

Method used to generate this PR:
1. run: `find client/**/*.js | xargs -n 1 -P 10 ./bin/codemods/run.js commonjs-imports-hoist,commonjs-imports,i18n-mixin-to-localize,react-create-class`. Using the stock `run.js` on directories seems to skip swaths of files.
2. hand-edits/reverts as explained below in https://github.com/Automattic/wp-calypso/pull/18250#issuecomment-334311370

### CODE REVIEW

**Comment by sirreal** [comment]
I've noticed some strange things. Why doesn't this file appear to be codemodded?

https://github.com/Automattic/wp-calypso/blob/3ec2d221c696d276c69dfc6567aae2018f3bae4a/client/my-sites/importer/importer-header.jsx

Notice `React.createClass` (it _should_ correctly handle `pureRenderMixin`.

Notice `this.translate` usage 😱

**Comment by samouri** [comment]
@sirreal: when testing this out I was overeager and reverted more files than needed to be in https://github.com/Automattic/wp-calypso/pull/18250/commits/3ec2d221c696d276c69dfc6567aae2018f3bae4a.

I plan on doing a better dry-run of this soon

**Comment by samouri** [comment]
status update from today

Command ran: `./bin/codemods/run.js commonjs-imports-hoist,commonjs-imports,i18n-mixin,react-create-class,react-prop-types client`

I saw two kinds of errors during build. The first was within client that are depended on within `server` and therefore cannot use `import`.  The second was duped imports caused by codemodding. 

Files that cannot have `import` within them and need to be reverted after running:
1. `client/extensions/index.js`
2.  `client/sections.js`

Files that need to be pre-emptively fixed for duplicate import reasons:
1. `client/state/automated-transfer/middleware.js`
2. `client/my-sites/domains/controller.jsx`
3. `client/my-sites/checkout/controller.jsx`
4. `client/my-sites/stats/controller.jsx`

**Comment by sirreal** [comment]
Shall we close this one as a different approach has been taken?

**Comment by samouri** [comment]
definitely

**Pull request closed without merging**
