### PR TITLE
Paid stats: Update upsell with new features and images

### PR DESCRIPTION
**Pull request by jwebbdev**
Related to #

## Proposed Changes

* Update upsell image
* Add Personal Plan link
* Update feature items

## Why are these changes being made?

* p1HpG7-vbh-p2

Design:
Screenshot 2024-12-06 at 2 46 21 PM

This PR:
Screenshot 2024-12-06 at 3 12 40 PM
Screenshot 2024-12-06 at 3 12 36 PM

## Testing Instructions

* Open the Calypso live branch
* Navigate to a Free site with stats upsell
* Compare the Upsell to the design above

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
    - [ ] For UI changes, have we tested the change in various languages (for example, ES, PT, FR, or DE)? The length of text and words vary significantly between languages. 
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Comment by ederrengifo** [comment]
Updated images:

[images.zip](https://github.com/user-attachments/files/18042994/images.zip)

**Comment by ederrengifo** [comment]
LGTM!

**Review by Initsogar — APPROVED** [review]
Looks good!

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/17050623

Some locales (Hebrew, Japanese) have been temporarily machine-translated due to translator availability. All other translations are usually ready within a few days. Untranslated and machine-translated strings will be sent for translation next Monday and are expected to be completed by the following Friday.

Thank you @jwebbdev for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/17050623).

**Pull request merged**
