### PR TITLE
Features list: Fix text under /start/plans page

### PR DESCRIPTION
**Pull request by kozer**
**Proposed Changes**

Change text under `/start/plans` in order to reflect what exists
under `/pricing` page.

For reference, here is the page under `/pricing`, and the change we need to change under `/start/plans` page:

Screenshot_2022-09-20_at_12 57 38_PM

Done is:

- [x] The copy is consistent with the logged-out views.
- [x] The new features are listed on the /plans page during singup.

#### Testing Instructions

How to test:
- Visit `wordpress.com/start/plans`. Feature text under `Business` and `eCommerse` plans is: `SFTP (SSH File Transfer Protocol) and Database Access`. This step is about about checking **current behavior that is not desired**
-  Visit `/start/plans` locally. Please mention that we should select a domain after navigating to this page. Feature text under `Business` and `eCommerse` plans is: `SFTP, SSH, WP-CLI, and Database access`

In order to provide as much help as possible here are some _before_ and _after_ screenshots:

`/start/plans` was _before_ the fix:

Screenshot 2022-09-23 at 11 28 40

And _after_ the fix:

after

#### Pre-merge Checklist

- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [x] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?

Related to #68193

### CODE REVIEW

**Review by wojtekn — APPROVED** [review]
The change looks good, and works as expected.

**Review by sejas — APPROVED** [review]
Looking great 👍 !!

**Comment by p-jackson** [comment]
Could this be a good PR for the `[String Freeze]` label? pxLjZ-5DT-p2 This PR might be a regression for non-English speakers until translations are complete.

I could be wrong though. This string is mostly a bunch of well known acronyms, so it will probably be understood by technical-minded folks regardless of their language. Just thought it was worth considering.

**Comment by wojtekn** [comment]
@p-jackson, we are adding a string that is already used in another place so I thought it would catch the existing translation. I've checked the translation database, and [it looks like it is translated](https://translate.wordpress.com/projects/wpcom/-all-translated/846283/).

However, I've checked my local Calypso using another language and I still see the English phrase. Will it be caught at some point? Or should we still add the [String Freeze] label to handle it?

**Comment by p-jackson** [comment]
Oh didn't realise it was already used elsewhere! You may need to update your sandbox to get the latest translations. Ignore me, doesn't sound like `[String freeze]` is appropriate in this case 🖖

**Pull request merged**
