### PR TITLE
Gutenberg: Enable Jetpack Gutenframe in the desktop app

### LINKED ISSUE #32048: Gutenframe: Verify editing flows on the desktop app.
We'll need to verify that editing flows all work as expected when working with Atomic and Jetpack sites within the WordPress.com Desktop app.

Background: p3fqKv-6Hh-p2.

### PR DESCRIPTION
**Pull request by mmtr**
#### Changes proposed in this Pull Request

This PR enables Gutenframe for Jetpack/Atomic sites in the desktop app by removing the `jetpack/gutenframe` feature toggle (since all environments will have it enabled now).

In order to keep the user in the app, it also fallbacks to the classic editor when the site is not eligible for Gutenframe (i.e. because a denied plugin is active) rather than opening WP Admin in the browser. This was previously controlled by the `calypsoify/gutenberg` feature flag which has been renamed to `gutenberg/redirect` in order to align the name with the value of the selected editor.

#### Testing instructions

This needs to be tested on the desktop app, so make sure you have the dev environment [installed and running](https://github.com/Automattic/wp-desktop/blob/468ecd4d68cdafbc2935facfcd15953f46db98ce/docs/install.md) (more info about how to set up the secrets at paaHJt-7y-p2).

- In the desktop repo, point the calypso submodule to this branch: `cd calypso && git fetch && git checkout update/32048-gutenframe-enable-desktop && cd ..`.
- Generate  a new build: `make build`.
- Open the built app in the `release/<YOUR_OS>` folder (i.e. `release/mac/WordPress.com.app`).
- Switch to an Atomic site.
- Start creating a post.
- Make sure the block editor is loaded in the desktop app.
- Install a denied plugin (see PCYsg-lOu-p2 for information about how to get the current list of denied plugins).
- Close the desktop app and open it again, so the cache is cleared and the new installed plugin is considered when determining which editor should be loaded.
- Create a new post again.
- Verify the Calypso classic editor is loaded now in the desktop app:
Screen Shot 2019-07-24 at 08 16 27

Fixes #32048

### CODE REVIEW

**Comment by mmtr** [comment]
> **After enabling a forbidden plugin:**
> Screen Shot 2019-07-23 at 3 57 21 PM
> 

This is weird. What you see in the screenshot is the WP Admin classic editor, but you should see the Calypso classic editor (I should have made this clearer on the testing instructions, sorry!):

Screen Shot 2019-07-24 at 08 16 27

Actually, I don't know how have you been able to get a WP Admin route on the desktop app, since it seems that we always want to open these URLs on the browser ([#](https://github.com/Automattic/wp-desktop/blob/e5300c0bc3327f103d185dc0fe558f85e013735f/desktop/window-handlers/external-links/index.js#L68-L81)).

Did you reopened the app after installing the plugin?

**Comment by noahtallen** [comment]
I did this:
1. I tried to install the plugin from the plugins page in the desktop app, but got an error
2. I went to the plugins page in my browser and installed & activated the plugin there
3. I went back to the desktop app which was still open
4. I went back to the posts page and opened (I think) the same post and saw that screenshot

However, now that I opened and closed the app, I'm seeing this, which is correct. But also it's prompting us to switch to the block editor! Should we disable that tooltip if we have a forbidden plugin installed?
Screen Shot 2019-07-23 at 4 25 41 PM

Sorry for forgetting the open/close step! Perhaps it went to the classic editor because the plugin I installed was related to page building?

**Comment by mmtr** [comment]
> However, now that I opened and closed the app, I'm seeing this, which is correct.

Awesome! Note that this extra step is needed due to the issue noted in https://github.com/Automattic/wp-calypso/issues/33074.

> But also it's prompting us to switch to the block editor! Should we disable that tooltip if we have a forbidden plugin installed?

Definitely! But given this problem is currently present in master too and not only in the desktop app (an AT site can currently switch to the block editor from the sidebar even if they have a denied plugin), I think we can fix in a separate PR. I've created https://github.com/Automattic/wp-calypso/issues/34856 for that.

**Comment by noahtallen** [comment]
Fantastic!

**Pull request merged**
