### PR TITLE
Domain management: Email: Provide missing 'context-all-domain-management' class

### PR DESCRIPTION
**Pull request by bogiii**
Related to #

## Proposed Changes

* Provide missing `content-all-domain-management` class

## Why are these changes being made?

* Support All domain management context

## Testing Instructions

* Go to `/domains/manage?flags=calypso/all-domain-management`
* Select a domain
* Check the loading state placeholder
* Select a domain with no access permission
* Check if the no-access state

| Before | After |
|--------|--------|
| Screenshot 2024-12-16 at 16 22 07 | Screenshot 2024-12-16 at 16 29 26 |
| Screenshot 2024-12-16 at 16 54 58 | Screenshot 2024-12-16 at 16 56 23 | 

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
    - [ ] For UI changes, have we tested the change in various languages (for example, ES, PT, FR, or DE)? The length of text and words vary significantly between languages. 
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Review by Imran92 — COMMENTED** [review]
Looks good to me overall 🚀 Can you kindly explain a bit more about this part?

> Select a domain with no access permission 

Thanks!

**Comment by Imran92** [comment]
> I manually forced to render that component and discovered a missing style in an all-domain-management context.

Ah that makes sense. I was struggling with finding a no-access site following the instructions as I couldn't find any in the domains list. So, just to clear my understanding, we'll need to force in the code to see this state for testing purpose, right?

**Comment by bogiii** [comment]
> we'll need to force in the code to see this state for testing purpose, right?

That's right. I needed to be more precise in the instructions. Sorry about that.
If you want to force it, remove the IF statement.

**Review by Imran92 — APPROVED** [review]
LGTM!

However, I saw this issue in mobile view -

image

But I think this will be fixed when this ticket is done - https://github.com/Automattic/wp-calypso/issues/97538

So I'm approving it

**Pull request merged**
