### PR TITLE
Global Styles on Personal: Update upsells and modals

### PR DESCRIPTION
**Pull request by rcrdortiz**
Related to:
- https://github.com/Automattic/dotcom-forge/issues/9520

## Proposed Changes

* Updated launchpad upsell to reference the Personal plan when the feature is active.
* Updated Privacy Settings upsell to reference the Personal plan when the feature is active.
* Updated Global Styles try before you buy modal to reference the Personal plan and its features when the feature flag is active.
* Updated Theme Badges to show the required plan as Personal when the feature flag is active.

## Why are these changes being made?

* We want to change the Global Styles feature from being gated to the Premium plan to being behind the Personal plan.

## Testing Instructions

* Use the Calypso live link.
* Enable the feature flag with `?flags=global-styles/on-personal-plan`
* Create a site using the free plan.
* Go through all the Calypso screens/pages where a modal or upsell is shown.
* All the messages and modal should reference the Personal plan, and its features (when applicable), and should proceed to checking out the Personal plan when clicking on the Update CTA.
* Disable the flag and make sure all the texts reference the Premium plan and its features, and that there are no regressions.

Having the correct plan is out of scope, we're just checking the messaging. In order to see the correct plan we need to have the BE feature flag code merged, this does not impact the changes made in this PR.

The site editor and non-Calypso screens, modals, and notices are out of scope.

Screenshot 2024-11-05 at 12 25 14
Screenshot 2024-11-05 at 12 53 18
Screenshot 2024-11-05 at 12 55 43

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Review by dsas — COMMENTED** [review]
## Design picker
✅ The grid works correctly
Screenshot 2024-11-05 at 14 26 50


❗The details page doesn't work properly. The continue modal correctly says personal plan, but the text in the background says Premium plan
Screenshot 2024-11-05 at 14 28 26.

❗For some reason, using "Decide Later', or closing the dialog doesn't let you proceed. It dismisses the dialog, and clicking again on Continue just shows the dialog again.

✅ The checkout from the upgrade modal uses the personal plan.

**Review by dsas — COMMENTED** [review]
## Theme Showcase

✅ The theme grid is correct
Screenshot 2024-11-05 at 14 40 15

❗ The theme details says Premium plan
Screenshot 2024-11-05 at 14 41 11

✅ The modal is correct
Screenshot 2024-11-05 at 14 43 02

❗Though pressing upgrade adds the Premium plan to the checkout

**Review by dsas — COMMENTED** [review]
## Privacy settings
✅  Correctly says Personal plan
Screenshot 2024-11-05 at 14 50 33

✅ Pressing Upgrade goes to the /plans page with the Personal plan highlighted

**Review by dsas — COMMENTED** [review]
## Launchpad
✅ Text makes no reference to plan
Screenshot 2024-11-05 at 14 57 25

✅ The Upgrade link goes to /plans with the Personal plan highlighted

**Comment by rcrdortiz** [comment]
> ## Design picker
> ✅ The grid works correctly Screenshot 2024-11-05 at 14 26 50
> 
> ❗The details page doesn't work properly. The continue modal correctly says personal plan, but the text in the background says Premium plan Screenshot 2024-11-05 at 14 28 26.
> 
> ❗For some reason, using "Decide Later', or closing the dialog doesn't let you proceed. It dismisses the dialog, and clicking again on Continue just shows the dialog again.
> 
> ✅ The checkout from the upgrade modal uses the personal plan.

Fixed. With respect to the `Decide Later` thingy, does it happen in prod? It seems to be working for me locally.

**Comment by rcrdortiz** [comment]
> ## Theme Showcase
> ✅ The theme grid is correct Screenshot 2024-11-05 at 14 40 15
> 
> ❗ The theme details says Premium plan Screenshot 2024-11-05 at 14 41 11
> 
> ✅ The modal is correct Screenshot 2024-11-05 at 14 43 02
> 
> ❗Though pressing upgrade adds the Premium plan to the checkout

Fixed

**Comment by dsas** [comment]
> Fixed. With respect to the Decide Later thingy, does it happen in prod? It seems to be working for me locally.

Can't reproduce now 😕 in prod or on the PR.

> ❗Though pressing upgrade adds the Premium plan to the checkout

This [the theme showcase upgrade modal] still is adding the Premium plan to the checkout for me.

**Comment by rcrdortiz** [comment]
> > Fixed. With respect to the Decide Later thingy, does it happen in prod? It seems to be working for me locally.
> 
> Can't reproduce now 😕 in prod or on the PR.
> 
> > ❗Though pressing upgrade adds the Premium plan to the checkout
> 
> This [the theme showcase upgrade modal] still is adding the Premium plan to the checkout for me.
> 
> All of the other things I tested before work.

Maybe you have something cached? It's working for me (unless we arent' speaking about the same thing):

https://github.com/user-attachments/assets/f0f1decf-fb7c-4b60-bfad-f61dc676154a

**Comment by dsas** [comment]
> > This [the theme showcase upgrade modal] still is adding the Premium plan to the checkout for me.
> Maybe you have something cached? It's working for me (unless we arent' speaking about the same thing):
> works-for-me.mp4

That video isn't working for me 😕 I think this probably needs updating: https://github.com/Automattic/wp-calypso/blob/c8236124a845c15f34989e64e8a70330c48cf41c/client/my-sites/theme/main.jsx#L1280


https://github.com/user-attachments/assets/3bce875b-a9b8-4a43-9da8-9a21e5812ec2

**Comment by rcrdortiz** [comment]
> > > This [the theme showcase upgrade modal] still is adding the Premium plan to the checkout for me.
> > > Maybe you have something cached? It's working for me (unless we arent' speaking about the same thing):
> > > works-for-me.mp4
> 
> That video isn't working for me 😕 I think this probably needs updating:
> 
> https://github.com/Automattic/wp-calypso/blob/c8236124a845c15f34989e64e8a70330c48cf41c/client/my-sites/theme/main.jsx#L1280
> 
>  Screen.Recording.2024-11-05.at.16.57.50.mov

That line of code is already updated since my last commit

**Review by dsas — APPROVED** [review]
> That line of code is already updated since my last commit, maybe you're using an old container?

Unsure what I did, because the other changes I checked were there. I've tested again though, and it is indeed working. Sorry for the confusion

**Comment by rcrdortiz** [comment]
> > That line of code is already updated since my last commit, maybe you're using an old container?
> 
> Unsure what I did, because the other changes I checked were there. I've tested again though, and it is indeed working. Sorry for the confusion

No problem, glad we got it sorted out 😄

**Pull request merged**
