### PR TITLE
Gutenboarding: Update template files with new starter design exports

### PR DESCRIPTION
**Pull request by ramonjd**
## Changes proposed in this Pull Request

This PR adds generated template files to the templates folder, and one preview file for barnsbury

This PR also removes the `author` field from all the templates.

## Testing instructions

We're adding static files only.

The `author` field was never used.

### CODE REVIEW

**Comment by simison** [comment]
I think we can remove the `author` field, it's not used anywhere and contains private info.

Let's test these via calypso-live-sites before deploying. @johnHackworth can elaborate how. :-)

To generate new previews, we need to change the script to point to those live-sites, and then run the script here https://github.com/Automattic/wp-calypso/blob/master/bin/generate-gutenboarding-design-thumbnails.js

**Comment by ramonjd** [comment]
> I think we can remove the author field, it's not used anywhere and contains private info.

Excellent thanks. I'll remove the unneeded info.

> To generate new previews, we need to change the script to point to those live-sites, and then run the script here https://github.com/Automattic/wp-calypso/blob/master/bin/generate-gutenboarding-design-thumbnails.js

Nice. I'll also remove my paltry screenshot :)

**Comment by simison** [comment]
We could include these already in `client/landing/gutenboarding/available-designs.ts` but behind a feature flag so that we can deploy these and have them show up only in local development and/or staging.

**Comment by ramonjd** [comment]
> We could include these already in client/landing/gutenboarding/available-designs.ts but behind a feature flag so that we can deploy these and have them show up only in local development and/or staging.

Good idea. I'll throw it in https://github.com/Automattic/wp-calypso/pull/42354

**Comment by simison** [comment]
Calypso live tempalte testing instructions at D41281-code

**Comment by ramonjd** [comment]
Checked the templates using instructions in D41281-code
Removing the author field had no effect :-D

**Pull request merged**
