### PR TITLE
Purchases: change wording for Edit Payment Method in unsubscribed purchases

### LINKED ISSUE #5153: Purchases: change wording for Edit Payment Method in unsubscribed purchases.
With D1694-code, we no longer display payment method information for unsubscribed purchases (see p2MSmN-4Pu-p2). To complement this change, we should update the Edit Payment Method option, and make it Add Payment Method instead. The option should still read Edit for subscribed purchases.

cc @gziolo @janm6k

### PR DESCRIPTION
**Pull request by janm6k**
Fixes #5153.

To test, check that purchase details page shows "Add Payment Method" instead of "Edit Payment Method" for subscription with auto renew turned off.

### CODE REVIEW

**Comment by gziolo** [comment]
We probably should also do the similar trick on `Edit Payment Method` page. I haven't tested it, but I'm taking a stab in the dark :)

**Comment by gziolo** [comment]
Code looks good, but I haven't tested.

**Comment by fabianapsimoes** [comment]
> We probably should also do the similar trick on Edit Payment Method page. 

Yep, we should make sure `/purchase/:site/:purchase` matches `/purchase/:site/:purchase/payment/edit`. The latter still says Edit Card Details.

**Comment by janm6k** [comment]
> We probably should also do the similar trick on Edit Payment Method page. I haven't tested it, but I'm taking a stab in the dark :)

Good point. I have updated the title to "Add Card Details" for cancelled purchases.
It still shows "Edit Card Details" while the page is loading, and it changes only after it is fully rendered. No idea how to fix that.

**Comment by fabianapsimoes** [comment]
> It still shows "Edit Card Details" while the page is loading, and it changes only after it is fully rendered. No idea how to fix that.

Would it be possible to make Add Card Details the default while the page is loading? I think that works better for unsubscribed purchases than Edit Card Details, while still making sense to subscribed purchases.

**Comment by janm6k** [comment]
> Would it be possible to make Add Card Details the default while the page is loading?

Yes. Good idea!

**Comment by janm6k** [comment]
Now it shows "Add Card Details" while edit card details page content is loading.

**Comment by fabianapsimoes** [comment]
Awesome! Looks good to me :ok_hand:

**Comment by gziolo** [comment]
Code looks good :shipit:

**Pull request merged**
