### PR TITLE
Theme Showcase: Label dotorg themes with the Community badge

### PR DESCRIPTION
**Pull request by taipeicoder**
## Proposed Changes

This PR fixes an issue in the Theme Showcase where dotorg themes were incorrectly labeled as "Free". This PR adds the badge "Community" for dotorg themes.

Screenshot 2023-04-12 at 6 06 52 PM

## Testing Instructions

* Head to the Theme Showcase.
* Search for a dotorg theme, such as Astra.
* Ensure that the theme has the badge "Community", and that the tooltip is displayed as shown in the screenshot.

## Pre-merge Checklist

- [x] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [x] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [x] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [x] Have you checked for TypeScript, React or other console errors?
- [x] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [x] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [x] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/7920998

Thank you @taipeicoder for including a screenshot in the description! This is really helpful for our translators.

**Review by okmttdhr — APPROVED** [review]

**Comment by okmttdhr** [comment]
Tested and worked as expected 👍

**Comment by arthur791004** [comment]
Not a blocker, but I'd prefer to have different styles for the community badge (e.g. icon & background color) if possible 😆

**Review by arthur791004 — APPROVED** [review]
👍

**Comment by taipeicoder** [comment]
> Not a blocker, but I'd prefer to have different styles for the community badge (e.g. icon & background color) if possible 😆

@ianstewart @davewhitley any ideas?

**Comment by davewhitley** [comment]
We don't need the star because that signifies an upgrade/upsell on WordPress.com. It would be nice to have a generic "default" color for these badges, which we don't have I suppose.

I'd do a gray-on-gray color for this.

Screen Shot 2023-04-17 at 2 52 38 PM

Screen Shot 2023-04-17 at 2 54 23 PM

See "info badge".

Edit: the themes require a Business plan, but I don't want to communicate that these themes are paid/premium themes by putting an icon next to them. The ability to install them is just a side effect of having the Business plan, and the theme itself is not an upgrade necessarily.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/7920998).

**Comment by taipeicoder** [comment]
> We don't need the star because that signifies an upgrade/upsell on WordPress.com. It would be nice to have a generic "default" color for these badges, which we don't have I suppose.
> 
> I'd do a gray-on-gray color for this.
> 
> Screen Shot 2023-04-17 at 2 52 38 PM
> 
> Screen Shot 2023-04-17 at 2 54 23 PM
> 
> See "info badge".
> 
> Edit: the themes require a Business plan, but I don't want to communicate that these themes are paid/premium themes by putting an icon next to them. The ability to install them is just a side effect of having the Business plan, and the theme itself is not an upgrade necessarily.

Followed up in https://github.com/Automattic/wp-calypso/pull/75992

**Pull request merged**
