### PR TITLE
WP Job Manager Extension: update data layer handlers to dispatchRequestEx

### PR DESCRIPTION
**Pull request by jsnajdr**
Another step in #25121.

#### Testing instructions

Disable `calypsoify/plugins` and install WP Job Manager to your Atomic/Jetpack site. Go to the plugin settings page. Check that everything works there (setup, pages, job listings...)

I personally didn't manage to make the plugin work. Even after installing the plugin, when Calypso is sending requests to the "Jetpack proxy" endpoint:
- URL: `/rest/v1.1/jetpack-blogs/139083458/rest-api/`
- `path` param:  `/wpjm/v1/settings`

I always get a 404 (enveloped) with error: `rest_no_route`.

Maybe someone else knows how to fix that? Maybe @donnapep? Was the extension even ever finished?

### CODE REVIEW

**Comment by sirreal** [comment]
I see the same behavior as @jsnajdr, the behavior appears to be the same on wpcalypso and this branch.

**Comment by donnapep** [comment]
I think perhaps it may be better to disable WPJM in Calypso altogether for now. The REST API was only ever available behind a WPJM flag, and in the next release we're planning to [deprecate the current REST API implementation and switch to using Core's](https://github.com/Automattic/WP-Job-Manager/pull/1628). That means that the settings endpoint will be non-existent until we do additional work to add it back in later.

**Comment by jsnajdr** [comment]
> I think perhaps it may be better to disable WPJM in Calypso altogether for now.

It's currently enabled only in the `development` and `wpcalypso` environments anyway. We can leave that as it is.

It's a dormant code that's affected by various API migrations we do and is not otherwise used or worked on.

> The REST API was only ever available behind a WPJM flag, and in the next release we're planning to deprecate the current REST API implementation

Hmmm, what are good testing steps then? Let's just check that the REST request are being issued and that they fail :smile:

**Comment by donnapep** [comment]
> Hmmm, what are good testing steps then? Let's just check that the REST request are being issued and that they fail 😄

How about we just remove it altogether?

**Comment by jsnajdr** [comment]
> How about we just remove it altogether?

#29263 :cry:

**Comment by jsnajdr** [comment]
Closing in favor of #29263 that removed the affected wp-job-manager extension altogether.

**Pull request closed without merging**
