### PR TITLE
Newsletter: add paid subscribers to free plans grid

### PR DESCRIPTION
**Pull request by simison**
This might need a bit more thought to ensure plans stay more balanced.

## Proposed Changes

* Adds paid subscriber feature on free to plans grid at Newsletter onboarding

image

## Testing Instructions

* `/setup/newsletter` and see plans grid

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

**Review by lezama — APPROVED** [review]

**Comment by lezama** [comment]
We should remove it from personal

**Comment by simison** [comment]
Need to rebase / re-test because I think someone already added this. Not sure if that was just generic plans or also newsletter plans.

**Comment by edanzer** [comment]
**Rebase**. I rebased and there is a change. We are adding two features: FEATURE_PREMIUM_CONTENT_JP and FEATURE_PAID_SUBSCRIBERS_JP. 

For the former, the description was updated from `Premium Content Gating` (which shows in the screenshot above) to `Add paid subscriptions and gated content`. So if we add both features, we end up with `Add paid subscriptions and gated content` and `Paid subscribers`, which seems redundant. Interestingly, we are actually showing both in production right now, so the feature list for Personal looks like below. I think we should probably just use one of these, so question is which do we want? 

Screenshot on 2023-06-13 at 19-41-41


**Remove from Personal**. In the meantime, I also agree with @lezama that if we're adding this to the free plan, we should remove it from Personal. So I've gone ahead and removed both of these features from Personal now.

**Re run tests**. Finally, tests were failing, but those have passed after rebasing and re-running the tests a couple times.

**Comment by edanzer** [comment]
For the sake of just moving this small issue to completion, I've decided to stick with the existing feature description before this PR, which is "Add paid subscriptions and gated content", and just remove "Paid subscribers" as redundant. The existing one covers gated content as well. So we're just moving this feature to the free plan. As this is a small PR, I'm just going to merge this when tests pass.

**Review by edanzer — APPROVED** [review]

**Pull request merged**
