### PR TITLE
Signup: Add a user testimonial to specific pages in signup

### PR DESCRIPTION
**Pull request by sixhours**
WIP, please do not merge. Continuation of work done in #27862 

#### Changes proposed in this Pull Request

* Adds a user testimonial to specific pages in signup.
* Testimonial becomes a new component included in the StepWrapper component.

#### Testing instructions

* Switch to this PR
* Check About and User login pages for testimonial at the bottom.

### CODE REVIEW

**Comment by sixhours** [comment]
The testimonial feels a bit tacked onto the end of the page with the one-column layout. I think this needs some design love.

**Comment by sixhours** [comment]
Explored some very basic alternatives:

screen shot 2018-10-30 at 3 31 47 pm

screen shot 2018-10-30 at 3 15 20 pm

screen shot 2018-10-30 at 3 49 12 pm

**Comment by fditrapani** [comment]
Thanks for starting this and sharing some additional explorations. I agree that it feels a bit tacked on and it also commands a lot of my attention — more than it probably should. I wonder if reducing it's prominence, with a smaller typeface and more space maybe, will help with it fitting in better. 

I personally like the second layout in your explorations from the screenshot but find it hard to fully jump onboard with it without seeing it in the context of the full page.

**Comment by sixhours** [comment]
Ah, yeah, I'm viewing on a 13" screen. Here's a stitched together preview (pardon the cropped shape in the bg for the purposes of a quick mock-up):

voila_capture 2018-10-31_3-39-32_pm

But that's something to think about as well; testimonials won't be easily viewable on a shorter screen because they're buried at the bottom.

**Comment by iamtakashi** [comment]
image

The vertical space between the progress indicator and the header seems a little excessive to me. I think it could just be the half of what we have now. It won't save much to bring the testimonial higher on the page, but I thought I'd mention since it looked a little odd to me.

I also think the colour of the testimonial text should be a little darker to have a better contrast between the text and the background. The choice of the colour might be intentional to not to draw too much attention, but I'd try a darker colour with a smaller font size.

**Comment by fditrapani** [comment]
Thanks for sharing the updated screenshot @sixhours and thanks for the feedback @iamtakashi. The new shot really showed me how forced the testimonial looks. It adds yet another thing to the page and makes it feel really busy. I apologize for all the updates but I think we're going to have to go back to the drawing board on this one. 

One suggestion could be to explore what this might look like on the [account signup page](https://dribbble.com/shots/3829284-Dipnet-login-page) only.

**Pull request closed without merging**
