### PR TITLE
Framework: Fix retries when chunks fail to load

### PR DESCRIPTION
**Pull request by blowery**
This fixes how we detect chunk load failure and reload the page. When we moved to more than one chunk necessary to load the page, we also switched which branch we took inside the webpack loader. This prevented our Error object from being passed through, so we never saw errors.

This switches to using a window level global that both the loader and the plugin agree on. A bit gross, but it does work.

### CODE REVIEW

**Comment by blowery** [comment]
cc @mtias @gwwar

**Comment by blowery** [comment]
To test, load up a reader page, then disable the network in the dev tools. Then try to load the editor. You should see the app try to reload the page instead of dying with a bunch of JS errors.

**Comment by gwwar** [comment]
Verified the issue in prod, and the fix. 🚢

**Comment by mtias** [comment]
Is the root of the problem the nameless commons chunk introduced in #4852?

**Comment by blowery** [comment]
> Is the root of the problem the nameless commons chunk introduced in #4852?

Sort of. The problem is not the lack of a name, but that introducing a second chunk makes webpack take a different branch when loading chunks. The new branch calls the loaded callback differently than the only-one-chunk branch, so our loader hack to pass along an error argument as the second arg no longer works

**Comment by mtias** [comment]
Thanks for taking a look at this.

**Pull request merged**
