### PR TITLE
Add/comingsoon v2 calypso

### PR DESCRIPTION
**Pull request by lsl**
#### Changes proposed in this Pull Request

* Calypso part of #45167 / #45581 

#### Testing instructions

*

Fixes #

### CODE REVIEW

**Comment by ramonjd** [comment]
@roo2 made an additional commit in the test PR: https://github.com/Automattic/wp-calypso/pull/45167/commits/71ea337f1fa99ab9b702c36edb87b8a3387d2ad5

I was going to reinstate it tonight, but decided to wait until we talk about whether we need to completely feature flag v2

**Comment by lsl** [comment]
Fixed some broken tests then fixed a couple of logic errors moving from v1 to v2. 

I think I have this right but definitely need some eyes on it, was testing the difference between what happens when loading settings on wpcom vs calypso and swapping between the two to see the difference. I applied the filters in #45604 to my 0-sandbox.php for testing without needing anything from #45581.

I'm glad we've split these / kept them separate now as I think it would have confused things a fair bit.

... Just watching the full test suite run, looks like some integration tests need updating after the UI change:
```
SiteSettingsFormGeneral Privacy picker - simple sites Coming soon option should be selectable
--
SiteSettingsFormGeneral Privacy picker - simple sites Hidden checkbox should be possible to unselect
SiteSettingsFormGeneral Privacy picker - simple sites Hidden option should be selectable
SiteSettingsFormGeneral Privacy picker - simple sites Private option should be selectable
SiteSettingsFormGeneral Privacy picker - simple sites Public option should be selectable
SiteSettingsFormGeneral Privacy picker - simple sites Selecting Hidden should switch radio to Public
SiteSettingsFormGeneral Privacy picker - simple sites Should have 4 visibility options
```

**Comment by lsl** [comment]
Testing D49571-code got myself into a WSOD on wpcom (live) using a test account. Suspect my testing here caused got the settings into an incompatible format. (calypso.localhost worked fine) See slack for user info if you want to have a look.

I think if we want to feature flag this we may need to support both old and new settings at the same time. Feature flag would just control which settings UI is displayed. Thoughts?

**Comment by lsl** [comment]
Bit of a WIP state, trying to get tests to pass before adding v1 support back in behind a feature flag. (I have a hunch its going to be easier to add v1 support to v2 than the otherway around)

Phil's `Visibility` enum from #45428 is helping a lot here.

**Pull request closed without merging**
