### PR TITLE
Media: Provide Link to Supported Files After Failed Upload

### LINKED ISSUE #1636: Editor: failed file upload doesn't tell you which file types are allowed
Raised by @apeatling 

Tried to upload a file, I see this error message. Which file types are actually supported? I would have no idea where to look. What if they were listed in the message?

screen shot 2015-09-25 at 12 26 21 pm

### PR DESCRIPTION
**Pull request by Aurorum**
#### Changes proposed in this Pull Request

When an unsupported file is uploaded, this PR will provide a link to the support document where the list of unaccepted file types can be found: https://en.support.wordpress.com/accepted-filetypes/

#### Testing instructions

Visit the Media Modal (or Media Library) when writing a post in the Classic Editor and drag an unsupported file, such as a `swf` file, in an attempt to upload it.

**Before:**
Screenshot 2020-02-09 at 13 24 14

**After:**
Screenshot 2020-02-09 at 13 23 52

To ensure that the other notices aren't affected by this change, you can insert an image with a URL (but enter a URL that isn't valid).
Screenshot 2020-02-09 at 13 29 30

Fixes #1636

### CODE REVIEW

**Comment by bluefuton** [comment]
Hi @Aurorum! This looks like a useful addition. Would you mind giving it a rebase for us please?

**Comment by Aurorum** [comment]
I've resolved the conflicts, thanks for re-visiting these @bluefuton! :)

**Review by bluefuton — APPROVED** [review]
Tests out well 🚢

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/5554417

Thank you @Aurorum for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/5554417).

**Pull request merged**
