### PR TITLE
CommentsButton: move to "blocks" directory.

### PR DESCRIPTION
**Pull request by mtias**

### CODE REVIEW

**Comment by blowery** [comment]
Blocks? What are blocks? Did I miss a p2 post?

**Comment by blowery** [comment]
> Blocks? What are blocks? Did I miss a p2 post?

Found the README.

**Comment by aduth** [comment]
>Did I miss a p2 post?

Probably a good candidate for one.

**Comment by aduth** [comment]
LGTM 👍

**Pull request merged**
