### PR TITLE
FSE: add colorized output to Jest unit tests output via lerna

### PR DESCRIPTION
**Pull request by getdave**
Previously test output was not colorized. This made it much more difficult to decypher test output and distinguish from normal lerna output. 

Adding the [`--colors` flag to Jest](https://jestjs.io/docs/en/cli#--colors) fixes this.

> Forces test results output highlighting even if stdout is not a TTY.

#### Changes proposed in this Pull Request

Added colorized output when running FSE unit tests via `lerna`.

#### Testing instructions

Before checking-out  this PR branch:

* Run the FSE test suite - `npx lerna run test:js:watch --scope='@automattic/full-site-editing' --stream`
* See output is not colorized:

Screen Shot 2020-03-02 at 10 06 25

After checking-out  this PR branch:

* Run the FSE test suite - `npx lerna run test:js:watch --scope='@automattic/full-site-editing' --stream`
* See output **_is_** now colorized:

Screen Shot 2020-03-02 at 10 04 17

🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉🎉

### CODE REVIEW

**Comment by getdave** [comment]
> it's possible setting the flag passing three double-dashes as an argument of the script:

Thanks for noting this.

I'd like the colors provided _by default_, so I'm inclined to include them in the npm script rather than require people to know about the `--colors` flag.

**Comment by gziolo** [comment]
> > it's possible setting the flag passing three double-dashes as an argument of the script:
> 
> Thanks for noting this.
> 
> I'd like the colors provided _by default_, so I'm inclined to include them in the npm script rather than require people to know about the `--colors` flag.

Yes, I was wondering whether it would be the best way to proceed. Do you know why it isn't the default setting? It would be great to learn it first.

**Comment by getdave** [comment]
> Do you know why it isn't the default setting? It would be great to learn it first.

@gziolo I actually have no idea sorry. 

Here's [the commit that added it to Jest](https://github.com/facebook/jest/commit/f7975c661c06c5b1bf9c503d525a44a6cff4e22f).

I guess it was added later and is only needed when the output is not a TeleTypeWriter. 

I keep seeing references (which I can't now seem to find!) to it being needed because color codes need to be escaped for non-TTY stout.

**Comment by marekhrabe** [comment]
I would guess that's a default for many cli tools. I know I had to manually enable colors for tools I use often (git, some diffing utils etc…)

**Comment by noahtallen** [comment]
Thank you so much! Love this.

**Pull request merged**
