### PR TITLE
Media: Replace usages of flux add and addExternal media with thunks

### PR DESCRIPTION
**Pull request by saramarcondes**
#### Changes proposed in this Pull Request

* Replace all remaining usages of `MediaActions.add` with `addMedia`
* Simplify the API for `addMedia` and `addExternalMedia` by unifying the parameter order with `uploadMedia` and also by removing `serially` wrapper.

#### Testing instructions

* Upload a single and multiple images in the following areas using both drag and drop and the file selector dialogue:
    * Media library (also upload an image via URL here)
    * WooCommerce product image
* Test adding images from an external source such as Google Photos or Pexels still works (multiple and single)

Addresses part of https://github.com/Automattic/wp-calypso/issues/43661

### CODE REVIEW

**Comment by saramarcondes** [comment]
@flootr Whenever you have a chance, could you take a look at this PR and specifically the woocommerce changes? I can't figure out what I'm doing wrong to make it not work, but when I upload an image I see the preview fine during the upload, but after it finishes it doesn't show the image. If I save and reload the image is there, so there's just a disconnect somewhere and I'm stumped as to what it could be. Comparing the flux version and the redux thunk version side by side I _think_ I'm doing the same thing, but at this point a second set of eyes might just be the trick.

**Comment by flootr** [comment]
> specifically the woocommerce changes

If I compare the WooCommerce product image uploader side by side on your branch and master it looks almost identical. It's true the image disappears after it got uploaded, but it's right there shortly after. Here's what I see:

#### on this branch

cookies-dev

#### on master

cookies-master

The image I used is ~90kb.

**Comment by saramarcondes** [comment]
> Here's what I see:

Interesting! Thanks for trying it out... for me I see the same thing except the image never reappears 😖 This will take some poking and prodding to sort out it seems.

**Comment by saramarcondes** [comment]
Discovered the issue was with blocking trackers on that page. Opened an issue here to investigate further: https://github.com/Automattic/wp-calypso/issues/43915

**Comment by saramarcondes** [comment]
@flootr This PR got really big, any suggestions for ways to split it that would make it easier for you to review or do you think it'll be okay?

**Comment by saramarcondes** [comment]
@flootr This is strange! I actually caught that regression when I was testing it and had fixed it. It's what ultimately prompted me to create `createTransientMediaItems` and remove `serially` because `serially` prevented the ability to actually dispatch all those actions at once without further complicating things.

Were you testing in calypso.live or locally? I wonder if either was out of sync with origin?

**Comment by flootr** [comment]
> Were you testing in calypso.live or locally? I wonder if either was out of sync with origin?

Oh well, I can't reproduce it anymore neither on calypso.live nor locally. Seems like I was in fact not in sync with the current state. Sorry! 🚢

**Pull request merged**
