### PR TITLE
A4A > Marketplace: Fix the hosting card overlap issues

### PR DESCRIPTION
**Pull request by yashwin**
Resolves https://github.com/Automattic/automattic-for-agencies-dev/issues/729

## Proposed Changes

This PR fixes the hosting card overlap issues.

## Testing Instructions

- Open A4A live link
- Visit the Marketplace > Verify the hosting cards don't overlap at 1280px when the agency has a non-A4A pressable license, and the button text is changed to `Manage in Pressable`

Screenshot 2024-07-02 at 9 23 33 AM

- When there are no active plans:

Screenshot 2024-07-02 at 9 25 13 AM

## Pre-merge Checklist

- [x] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [x] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Comment by cleacos** [comment]
I cannot see the Pressable card...

**Comment by jeffgolenski** [comment]
Thanks @yashwin! As suggested let's also remove the word "plans" from both of those CTAS. They should read "Explore WordPress.com" and "Explore Pressable" where applicable.

**Comment by yashwin** [comment]
> I cannot see the Pressable card...

@cleacos: Could you please share the full screenshot? I hope you are not trying it on `Refer products` mode

> As suggested let's also remove the word "plans" from both of those CTAS. They should read "Explore WordPress.com" and "Explore Pressable" where applicable.

Thanks for the confirmation, @jeffgolenski! I have made the adjustments.

**Review by jeffgolenski — APPROVED** [review]
Looks good to me, my friend. Ship it!

**Review by jkguidaven — APPROVED** [review]
LGTM

**Pull request merged**
