### PR TITLE
Add block version of Blank Canvas to FSE design picker

### PR DESCRIPTION
**Pull request by zaguiini**
#### Changes proposed in this Pull Request

* Update `available-designs-config.json` to include blank canvas block theme.
* Blank Canvas is a selectable theme in the /new FSE beta onboarding design picker

#### Blockers

- ✅  No `headstart` necessary
- ✅  No demo URL necessary
- ✅  Network-activated

#### Screenshots

Screen Shot 2021-12-06 at 17 50 33

#### Testing instructions

* Apply branch to local calypso dev environment
* Visit http://calypso.localhost:3000/new/beta
* Enroll in the FSE beta
* Pick a free test domain
* Verify that `Blank Canvas` is a selectable theme
* Create a site with `Blank Canvas` enabled and smoke test the theme

Related to #58663.

### CODE REVIEW

**Comment by jeyip** [comment]
## Smoke Testing Theme
### Requirements

Tested both the editor + frontend

Default Content
- [x] No broken blocks on initial load 

Block Patterns
- [x] "Gallery with description and a button" pattern looks like its preview
- [x] "Link in Bio" pattern looks like its preview
- [x] "Talk to the host" pattern looks like its preview

Global Styles
- [x] Typography font size, line height, and font weight changes behave as expected
- [x] Background color, text color, and link colors changes behave as expected
- [x] Per block global styles (typography + colors) for the Post title block behave as expected

Block Settings
- [x] Typography font size, line height, and font weight block settings changes behave as expected
- [x] Background color, text color, and link color block settings changes behave as expected

**Comment by jeyip** [comment]
A few things to note:

- The blank canvas theme displays in the design picker as expected. We discussed renaming the theme though p1639501720216300/1639501360.215400-slack-CHN6J22MP. I'm unsure if we should wait to release this PR or if it's a non-issue.
- It appears as if this theme isn't network activated yet, so we'll probably want to do that as well.
- I think we may want to wait until this PR is merged before displaying block themes to users https://github.com/Automattic/wp-calypso/pull/58932. It enables the site editor for block themes by default since block themes don't have access to a functional customizer.

Otherwise, everything else lgtm!

**Review by jeyip — APPROVED** [review]

**Comment by creativecoder** [comment]
This is blocked until the new version of Blank Canvas is fully launched (theme slug finalized, theme network activated, previous version deprecated, etc.).

**Comment by zaguiini** [comment]
~Still not network activated~ Finally!

More discussion on p1641331738434800/1641330580.431200-slack-CHN6J22MP.

**Review by vindl — APPROVED** [review]
LGTM! :shipit:

**Pull request merged**
