### PR TITLE
Reader: Fix Photo Card titles getting cut off

### PR DESCRIPTION
**Pull request by jancavan**
**Before:**
screenshot 2017-04-06 20 01 20

**After:**
screenshot 2017-04-06 20 05 24

### CODE REVIEW

**Comment by bluefuton** [comment]
@jancavan the descenders are getting very slightly cropped (check out the 'g'):

screen shot 2017-04-07 at 09 07 27

I'll try bumping up the height 1px and reduce margin-bottom by 1px.

**Comment by bluefuton** [comment]
You can test on 'Postcards from the Reader':

http://calypso.localhost:3000/read/feeds/59317198

**Comment by samouri** [comment]
This PR also makes the title + the action bar both move down a few pixels.
Doesn't look worse IMO.

👍

**Comment by jancavan** [comment]
Fixed spacing inconsistencies in https://github.com/Automattic/wp-calypso/pull/12891/commits/2462fd4b2da2f6e1b3409e14a1b754fc60cfb134:

screenshot 2017-04-07 10 02 06

**Comment by fraying** [comment]
Looking good! But in Safari, Photo Cards are going too wide. (Note the right edge.)

screen shot 2017-04-07 at 10 27 29 am

**Comment by jancavan** [comment]
In https://github.com/Automattic/wp-calypso/pull/12891/commits/31c349a2a524bb319638a1da0bdcb5bdba401fc3, fixed photo card that are too wide in Safari.

**Chrome:**
screenshot 2017-04-11 17 12 43

**Safari:**
screenshot 2017-04-11 17 12 58

**Pull request merged**
