### PR TITLE
Jetpack-plans: Use a single instructions file

### PR DESCRIPTION
**Pull request by johnHackworth**
(Warning: Please notice that this PR is not done against Master, but against add/jetpack-plugin-provisioning. It's just a mean to propose & discuss some changes with @ryelle without adding a commit in her original PR (https://github.com/Automattic/wp-calypso/pull/2244) )

This PR removes all the single .com plugins dedicated instructions components and add adds a method to `plan-setup/instructions` that render the instructions of the plugin received as parameter. The available plugin list is maintained in a file which export an array with each plugin info.

I'm assuming that the final version of the instructions of each plugin are going to be quite similar so we could reuse the code ... if that is not going to be case, please, ignore this PR :)

### CODE REVIEW

**Comment by ryelle** [comment]
Sure, this works. I was assuming we'd write specific instructions here, but linking off to en.support makes more sense after all, so the format should be the same for all services.

**Comment by johnHackworth** [comment]
@ryelle Well, even if we write specific instructions, as long as every plugin's instructions follow the same pattern, we could do it this way ... and then, if any of the intructions require anything that makes it more complicated, then we could extract it to its own component ,,,

**Comment by ryelle** [comment]
Totally, but it was more that after I thought about it, it'll be easier for everyone to edit the support docs if it's not a PR into calypso.

**Comment by johnHackworth** [comment]
oh, great! I wasn't getting what you were saying, but yeah, you're 100% right! so.. let's add this to the other PR?

**Comment by ryelle** [comment]
sounds good!

**Comment by johnHackworth** [comment]
Great, let me see if I can just merge it from here or I need to cherry-pick the commit :)

**Pull request merged**
