### PR TITLE
WebPreview: fix placing in smaller viewports.

### LINKED ISSUE #568: Editor: Preview on smaller screens not responsive
Noticed this happening on iPhone 6+, but also occurs when browser size is >760px wide. 

It always shows the desktop view, even if the theme is responsive. 

img_1338

### PR DESCRIPTION
**Pull request by mtias**
Fixes #568.

See #3901.

### CODE REVIEW

**Comment by aduth** [comment]
Hmm 5f3d3dd5a597fd5dadf011b441dcd4e68ebe1070

**Comment by aduth** [comment]
I can't seem to reproduce this issue described at #568 on my own site.

**Comment by aduth** [comment]
For me, this regresses to the behavior fixed by #3350. :-1:

**Comment by aduth** [comment]
It seems the behavior on iOS is different than my Chrome desktop browser with at shrunken viewports, as the latter case does appear to be resolved by these changes.

**Comment by mtias** [comment]
Mmm, that's annoying.

**Pull request closed without merging**
