### PR TITLE
Guided Tours: Add Simple Payments Email Tour

### LINKED ISSUE #24594: Simple Payments: Guided Tour
## Scenario

A user receives an email suggesting they can earn money with their WP site.
They're intrigued by the opportunity but they don't know where to start, so they click on the email's CTA button (#24589) and start the Simple Payments Guided Tour (p9Jlb4-6x-p2).

cc @jancavan 

## Steps

- The user lands on `/stats/day/{site}?tour={simplePaymentsTourName}`. The `tour` query parameter triggers the `simplePaymentsTourName` tour.
- The tour's first step prompts the user to start by creating a new page. Clicking on Add (page) will open the Page Editor.

- The Page Editor displays the second step of the tour, tied to the toolbar's Add (+) button, and prompting to open the Add menu and select the Payment Button item.

- The user follows the instructions: clicks on the Add (+) button and then on the Payment Button item. Then they fill the SP form and insert it into the page.

## Notes

To conform to other tours (e.g. `?tour=main`) and to improve the users involvement, we should probably invite them to click on the actual UI instead of using the "Continue" button.

It was decided to remove the [last step of the tour](https://user-images.githubusercontent.com/2070010/39478640-4d922772-4d63-11e8-8d35-5994ae30ad8b.png) for the following reasons:
- It's technically pesky: we'd need to create a new reducer that keeps track of the visibility of the Simple Payments dialog in order to hide the second step when opening it and to show the third and last step when closing it.
- It doesn't add any additional details on top of what the user can already see in their editor (the actual payment button).
- It covers part of the editor (including the payment button), which results in a poor UX.

### PR DESCRIPTION
**Pull request by Copons**
Close #24594

Add a new Simple Payments tour that is supposed to be triggered by a direct link (`/?tour=simplePaymentsEmailTour`) from the Simple Payments email.

## Testing Instructions

- Open `/stats/day/{site}` and make sure it doesn't open the `simplePaymentsEmailTour` guided tour.
- Open `/stats/day/{site}?tour=simplePaymentsEmailTour`.
- Make sure the first step of the tour is displayed correctly, and it points to the Add Page sidebar button.
- Add a new page, which will open the Editor.
- Make sure the second and last step of the tour is displayed correctly, and it points to the Add Content toolbar button.

### CODE REVIEW

**Comment by gwwar** [comment]
The tour works as advertised, but it looks like there's 2 other simple payment tours. One in examples and another that appears to be in use. 

@lsinger what is the suggested maintenance approach here? We want to run another email campaign with a tour. Should we reuse the old tour, as the query param will force the tour to start?

**Comment by gwwar** [comment]
@jancavan, @apeatling and I noted that we can probably drop the step 3, where we note that you added a payment button, since the user can see that in the editor directly.

Step 2 is a little awkward too in that the tour needs to be dismissed manually, but I feel tempted to click on the add dropdown first. If that's the case, the tour sits underneath the dropdown. We probably don't need to address this here, since I think it's a tour quirk, but wanted to note it.

screen shot 2018-05-02 at 7 24 34 pm

**Comment by lsinger** [comment]
@gwwar I'd tend to do a new tour, since none of the previous ones were used for an email campaign. Content-wise they might be similar or even the same, but there's value in keeping intentions separate, too, in my opinion.

**Comment by gwwar** [comment]
39476466-4f4c7628-4d5c-11e8-8dac-aca5043806b2

In step 1, we have a continue button here which isn't quite right for this case since, the next step is to click on add vs showing the next tip on the same page. I think we need to remove the continue button (what the branch has currently) and add a call to action, probably an explicit sentence to click on the Page add button. We can see a similar pattern in other main tours. 

After this is done I believe we can 🚢. @lsinger is it enough here to guard the display of this tour with a `noop` for the when value?

cc @jancavan

**Comment by jancavan** [comment]
Sorry for chiming in late, I was in user interviews. Looks good when testing the steps mentioned in the description. A couple comments: 

1. This is minor, but I see a tooltip that flashes on the left-hand corner immediately after adding a Page.
2. If I add a Post instead, the tooltip in the first step is displayed on the upper left:

screen shot 2018-05-03 at 12 41 34 pm

I think this might be the exact same tooltip that flashes in (1).

Same thing happens if I head over to the Reader:

screen shot 2018-05-03 at 12 48 04 pm


Also, If I navigate to the Customizer, the first tooltip is still floating on the page:

screen shot 2018-05-03 at 12 45 49 pm

**Comment by gwwar** [comment]
@lsinger are the ^^ known issues with guided tours, or do we have anything else we should configure?

**Comment by Copons** [comment]
I think I should limit that step to only the paths with the sidebar visible (e.g. `/pages`, but not `/page`, etc.).

**Pull request merged**
