### PR TITLE
Site Selector: Implemented separate highlighting and selection

### PR DESCRIPTION
**Pull request by marekhrabe**
This changes a behavior of #5808 to separate site selection and keyboard highlight.

I've introduced a new property for `<Site>` and `<AllSites>` - `isHighlighted`, which should look exactly like a mouse hover in terms of styling. 

Honestly, I really dislike this change. Selected and highlighted site states together seem confusing to me. I can see two other ways we can explore, to make this better:

1. we can disable auto-highlight of the first site when you open selector (eg. you need to press <kbd>Down</kbd> to highlight first site)
2. we can set highlighted state to selected site (if available), so we always start with just one "blue" site

Test live: https://calypso.live/?branch=add/site-selector-keyboard-accessibility-highlight-1

### CODE REVIEW

**Comment by marekhrabe** [comment]
| Before | After | 
| --------- | ------ |
| before | after |

**Comment by marekhrabe** [comment]
Third way to change this: 
- remove `isSelected` styling (dark blue), which is only used in Switch Site, and just set the selected site there as initially highlighted. that means that you will know what is selected, but there wouldn't be two types of selection styles anymore after some interactions

**Comment by kellychoffman** [comment]
Cool. The only issue I have is with the combination of the `gray` against the `blue-medium`. It seems to clash a bit. What about `blue-light`?

screen shot 2016-06-13 at 4 41 18 pm

**Comment by kellychoffman** [comment]
> Selected and highlighted site states together seem confusing to me. 

Another option would be: instead of a background color change, add a border.

**Comment by folletto** [comment]
@kellychoffman the blue is aligned with the same pattern we're using elsewhere (see the site popover when one clicks New Post on the masterbar). 

If we want to update it, we should do it separately from this PR that is meant to solve the issue of focus being treated differently between hover and keyboard navigation, in a way that reviews our hover/focus and selected states across Calypso and not just this specific instance (see [here](https://github.com/Automattic/wp-calypso/pull/5808#issuecomment-225600238)).

@marekhrabe this is transversal to #5808 right? I'm asking just to be sure that the initial highlight will disappear once we merge both. :)

**Comment by folletto** [comment]
Tested on Chrome, Firefox, Safari: 👍 

If code is good we can proceed for me.

**Comment by marekhrabe** [comment]
> I'm asking just to be sure that the initial highlight will disappear once we merge both. :)

I made it disappear here d507be9be5cd3cbc5d6149e412087fd92076afaf! :)

I also fixed some styling regressions (new post dropdown had some errors) and as we united all hover/highlight/selected blue colors across all usages of SiteSelector, I was able to remove some specific overrides in favor of SiteSelector's global styles. 

@folletto Can you please do one more pass here if initial highlight works as expected for you? If it does, I will go ahead and merge this into our main PR #5808. Code review of this will be done over there after we finish all remaining tasks.

**Comment by folletto** [comment]
cap-

Perfect. Starting not highlighted and overriding the selected item works well: 👍

**Pull request merged**
