### PR TITLE
Editor: Remove more unused post editor code

### PR DESCRIPTION
**Pull request by tyxla**
In #46331 we removed a bunch of unused legacy post editor code. 

This PR follows up by removing even more of it that becomes obvious when we move an independent component somewhere else.

#### Changes proposed in this Pull Request

* Move `PublicizeMessage` to its own component directory in `components`.
* Remove unused `displayMessageHeading` prop from `PublicizeMessage` - we're removing the only code that actually uses that prop's default value.
* Fix `PublicizeMessage`'s class names to be compliant with our ESLint rules
* Remove editor drawer, editor sharing, editor fieldset, editor term selector, and unused related components.

#### Testing instructions

* Go to `/posts/:site` where `:site` is a public site with posts and at least one Publicize connection, click the ellipsis on the right of a post, and click "Share".
* Verify the publicize message box looks and works as it did before.
* Verify none of the code we're removing is used.
* All tests should pass

### CODE REVIEW

**Review by sarayourfriend — APPROVED** [review]
LGTM

**Review by allilevine — APPROVED** [review]
Thank you for tackling this cleanup work! 🙌 This PR also checks off moving `PublicizeMessage` in #46367

I tested on a public simple site connected to Twitter and the publicize post box looks the same before and after:

Before
Screen Shot 2020-11-04 at 11 50 49 AM

After
Screen Shot 2020-11-04 at 11 53 18 AM

**Comment by tyxla** [comment]
> Thank you for tackling this cleanup work! 🙌 This PR also checks off moving `PublicizeMessage` in #46367

Glad to help! And wow, it's great to see such a tidy and well-documented cleanup effort 👏  Keep up the great work!

**Comment by tyxla** [comment]
I'm following up with the big shovel in #47236.

**Pull request merged**
