### PR TITLE
Jetpack Manage: Pricing page -adding a more about link leading to a LicenseLightbox

### PR DESCRIPTION
**Pull request by coder-karen**
Related to https://github.com/Automattic/jetpack-manage/issues/258

## Proposed Changes

* This PR adds a 'More about' link to all product cards on the Manage Pricing page. 
* When clicked, this opens a LicenseLightbox for each product, with the correct price showing.
* Clicking on the 'Select License' link should lead to the issue license page, opening the 'Review License' lightbox for the relevant product.

Additional note: I spent some time looking into how to prevent the duplication between files but did not come up with anything helpful up until this point. I'm opening this up for review with that in mind, and open to suggestions.

## Testing Instructions

* To test, check out this branch. 
* Visit `http://jetpack.cloud.localhost:3000/manage/pricing`, and click on the 'More about' link for any product. Try for bundles as well (you'll need to manually add a bundleSize in `/manage/pricing/license-products-list/all-license-items.tsx` and `/manage/pricing/license-products-list/most-popular-plans.tsx` in that case).
* In all cases, the lightbox should open and show the correct amount.
* Clicking on 'Select License' should take you to the issue license page, opening the 'Review License' lightbox for the relevant product (barring issues related to initial load being investigated separately - you may need to refresh the page to confirm the lightbox will show on the issue licenses page).

Screenshot 2024-01-31 at 20 37 29

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

**Review by cleacos — CHANGES_REQUESTED** [review]
The Lightbox is shown when I click on Learn more, but in the console a get this error:

image

And when I try to click on the "Select License", it doesn't work and I get this error

image

**Comment by coder-karen** [comment]
Thank you, @cleacos 

> The Lightbox is shown when I click on Learn more, but in the console a get this error:

I'm guessing you were testing a card that normally has variants, such as Security or VaultPress Backup? That should be the only card that gets that error. Related to the console error when selecting a variant: 
https://github.com/Automattic/jetpack-manage/issues/265

> And when I try to click on the "Select License", it doesn't work and I get this error

Thanks for pointing that out. What happened was that I merged changes from this PR - https://github.com/Automattic/wp-calypso/pull/87044 - before pushing, and that PR changed the Get button functionality (moved it into it's own file). For me testing locally I didn't initially see any issues after fixing the merge conflicts. I see them all this morning. I've had to revert part of the change from that PR (which really was just trying to prevent duplication - I've moved the functionality back to the card files themselves). The issue only affected this PR as it was trying to call that component conditionally.

**Review by cleacos — CHANGES_REQUESTED** [review]
> I'm guessing you were testing a card that normally has variants, such as Security and VaultPress Backup

Yes, it only happens with Security and VaultPress Backup.

The Lightbox and the link work well without the other error I saw yesterday, but now I see this new error after clicking on `Select License`, and it takes me to the `/partner-portal/issue-license?product_slug=****`:

image

Same error if I click directly on `Get`

**Comment by coder-karen** [comment]
Thanks for testing again!

> Yes, it only happens with Security and VaultPress Backup.

Great, that makes sense then - we should fix it when looking at those console errors in the mentioned issue (or remove the dispatch).

> Same error if I click directly on Get

That console error is something I noticed on the issue license page itself, it happens even when visiting directly (not related to this project :) ) . Logged here: https://github.com/Automattic/jetpack-manage/issues/232

**Review by cleacos — APPROVED** [review]
Aside of the console error not related with this project, I tested it on Horizon and it worked as expected.

As usual, I found another console error navigating erratically using the Back/Forward buttons on my browser:
 
image

Other than that, It worked as expected! LGTM!

**Pull request merged**
