### PR TITLE
Hosting metrics: Requests per minute unification for line chart

### PR DESCRIPTION
**Pull request by sejas**
- Related to https://github.com/Automattic/wp-calypso/pull/80712#pullrequestreview-1582638191
- Alternative of https://github.com/Automattic/wp-calypso/pull/80755

## Proposed Changes

* Use the same formula for all the line charts. The result from the API * 60 and do not use the `_meta.dimension`.
* The last HTTP status code charts will display tiny decimal numbers.
* Update the HTTP status code chart descriptions to say `requests per minute`.

CleanShot 2023-08-18 at 08 28 34@2x

**Context**

The API returns each data point (`value`) in requests per second, and also a general time resolution.
The time resolutions are:
| **Time picker** | **Resolution in seconds** |
|---|---|
| 6 hours | 240 |
| 24 hours | 900 |
| 3 days | 3600 |
| 7 days | 7200 |

I can see these different formulas:
- `value * resolution` : actual number of requests during the resolution (time window)
- `value * resolution / 60` : requests per minute during the resolution (time window)
- `value * 60`: requests in one single minute

This PR implements the last one. Number of requests in one single minute.

## Testing Instructions

* Navigate to `/site-monitoring/${siteSlug}`
* Observe the line charts display the label `Requests per minute` and the values are correct.

## Screenshots
Screenshot 2023-08-18 at 16 24 27

Screenshot 2023-08-18 at 16 24 40

Screenshot 2023-08-18 at 16 25 17

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

**Review by danielbachhuber — CHANGES_REQUESTED** [review]
> The result from the API * 60 and do not use the `_meta.dimension`.

Can you explain this further?

**Comment by sejas** [comment]
> > The result from the API * 60 and do not use the `_meta.dimension`.
> 
> Can you explain this further?

Because Kat implemented the query for the first line chart, and I implemented the query for the HTTP status code charts, we ended up with two different algorithms.

This PR changes my algorithm (HTTP Status code charts) to use the same formula used in the first one.

The formula displays the value from the API (requests per second) * 60 to convert the value into requests per minute, and it doesn't take into account the `_meta.resolution`, which is the time slot that the API uses to group the requests.

I'm unsure whether this is the right formula to express the data, but it makes it more consistent across the line charts.
Changing the number doesn't affect the chart's shape, just the numbers on the scale.

**Comment by sejas** [comment]
Maybe we don't want to use the same "scale/unit" in all the charts.

**Review by danielbachhuber — APPROVED** [review]
Thanks for the detailed explanation, @sejas.

These changes look good on my end. I updated the PR description to include a screenshot.

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/8729978

Thank you @sejas for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/8729978).

**Pull request merged**
