### PR TITLE
Checkout: remove the transactionStepsMixin and update the SecurePaymentForm component

### PR DESCRIPTION
**Pull request by yoavf**
#### Changes proposed in this Pull Request

* use es6 class instead of createClass
* Include all code from the transactionStepsMixin directly in secure-payment-form
* cleanup

#### Testing instructions
This is just a refactor, but let's test all the things.

- [x] Test new card payment (success/failure)
- [x] Test existing stored card payment 
- [x] Test ebanx card payment
- [x] Test ebanx stored card payment
- [x] Test paypal payment
- [x] Test stripe redirect payments (ideal/bancontact...)
- [x] Test wechat payment
- [x] Test emergent paywall payment
- [x] Test ebanx redirect payment
- [x] Test wpcom credits payment
- [x] Test domain only purchase using budle credit
- [x] Test different subscription length
- [x] Test checkout loading when user has stored cards
- [x] Test checkout loading when user does not have stored cards

### CODE REVIEW

**Comment by yoavf** [comment]
Tested all the above, all looks good. Saw a warning about newCardDetails, but it's unrelated - opening a seperate PR.

**Comment by Hywan** [comment]
LGTM to me regarding the code, didn't test yet. Thanks for the cleanup!

**Comment by yoavf** [comment]
Thanks @Hywan  and @lsl 
I'll fix the e2e test looking for the `.secure-payment-form` class and then I'll merge.

**Comment by alisterscott** [comment]
e2e tests updated and all passing so this should be good to go 🚢

**Pull request merged**
