### PR TITLE
composite-checkout: Change step titles when step is complete

### PR DESCRIPTION
**Pull request by sirbrillig**
#### Changes proposed in this Pull Request

The `useActiveStep` custom React hook provides a component (within a step) with access to the currently active step object. There are also additional dynamic properties added to that object: the step's visible number and its index in the step array. This change adds a third dynamic property: the result of calling `isCompleteCallback` for that step. In addition, this change documents these dynamic properties and adds tests to prove they exist.

This PR also adds a new public API hook called `useIsStepComplete()` which will return true if the current step (not necessarily the active step) is complete as defined by that step's `isCompleteCallback` function.

Finally, this PR uses `useIsStepComplete` in the default payment method step and the Calypso contact step to change the step's title based on the completion status of the step.

#### Testing instructions

1. Run calypso with `ENABLE_FEATURES=composite-checkout-wpcom npm start`.
1. Add a plan to your cart and visit checkout.
1. Verify that the initial title of the payment method step is "Pick a payment method" and that of the contact step is "Enter your contact information".
1. Pick a payment method and press "Continue" to move on to the contact step.
1. Verify that the title of the payment method step is now "Payment method", and the contact step title is unchanged.
1. Press the "edit" button on the payment method step to jump back there.
1. Verify that the title of the payment method step is "Pick a payment method" and that of the contact step is "Enter your contact information".
1. Press "Continue" to move on to the contact step.
1. Fill out the contact step and click "Continue" to move on to the final step.
1. Verify that the title of the payment method step is "Payment method" and that of the contact step is "Contact information".
1. Press the "edit" button on the contact info step to jump back there.
1. Verify that the title of the payment method step is "Payment method" and that of the contact step is "Enter your contact information".

### CODE REVIEW

**Comment by sirbrillig** [comment]
I think that this is a good idea but that what we actually need to change the title in the contact form is the `isComplete` status of the _current_ step, not the active one. I'll see what I can do.

**Comment by sirbrillig** [comment]
> The title should only read "Enter your contact information" if there's a domain in the cart.

If there's not a domain in the cart, what should the title of the second step be?

**Comment by sirbrillig** [comment]
Oh, you're saying that there should be three titles?

1. If there's a domain and the step is not complete, "Enter your contact information"
2. If there's no domain and the step is not complete, "Enter your billing information"
3. If the step is complete, "Contact information"

Or should there be more?

**Comment by fditrapani** [comment]
Right, you almost got it. There's one more. 

1. If there's a domain and the step is not complete, "Enter your contact information"
2. If there's a domain and the step is complete, "Contact information"

3. If there's no domain and the step is not complete, "Enter your billing information"
4. If there's no domain and the step is complete, "Billing information"

**Comment by sirbrillig** [comment]
Thanks. Got it! Try it now.

**Pull request merged**
