### PR TITLE
BackupBrowser: Add file previews

### PR DESCRIPTION
**Pull request by Initsogar**
## Proposed Changes

* Allow file previews for `text`, `code`, `audio`, `image` and `video` files. Refer to [this list](https://github.com/Automattic/wp-calypso/blob/751c0cfef75805287aafd55672f2cd2af7c730d4/client/my-sites/backup/backup-contents-page/file-browser/util.ts#L11) for the extensions mapped for each type.
* Map `*.webp` and `*.svg` files as images in the backup browser. Doing this, we will be able to display file previews for these types.
* Hide sensitive files preview. In another PR we will enable the option with a warning prompt. Discussion in p1689015874978679-slack-C059R8T8Q15.
* This PR is not including style formatting for code files.
* Previews are not available for files with 0 bytes

## Demo
https://github.com/Automattic/wp-calypso/assets/1488641/711ce71a-880f-44e6-bf33-1bce376c6485

## Screenshots

| File type | Screenshot |
|---|---|
| Image | image |
| Audio | image |
| Video | image |
| Text | image |
| Code | image |

## Testing Instructions
* Start a Jetpack Cloud or Calypso Live branch
* Select one of your sites with a Jetpack VaultPress Backup plan.
* Navigate to VaultPress Backup page
* Pick one date with a backup available (use the calendar and click on any date marked with a dot).
* Browse files and click on any image, video, audio, text, or code file. It should expand the file info with a `Download file` button and also the file preview.

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

**Comment by jwebbdev** [comment]
0 bytes (empty) text files don't render a size and fail to load a preview

Screenshot 2023-07-10 at 6 29 36 PM

**Comment by jwebbdev** [comment]
We may want to use a fixed width when previewing files.  The design shows examples of images that seem to exist in a fixed with File info panel.  If the panel overflows then horizontal scroll of the entire browser is enabled.

Screenshot 2023-07-10 at 6 30 27 PM

Horizontal scroll might also be useful in some cases.  The design seems to have horizontal scrolls on the text previews.
Screenshot 2023-07-10 at 6 31 39 PM

**Comment by Initsogar** [comment]
@jwebbdev Thanks for your comments! Just made some adjustments:
- Files with 0 bytes are now displaying `Size: 0.0 B`.
- Previews are not displayed for files with 0 bytes.
- Text files lines are no longer wrapped to the current width. It now supports horizontal scroll.
- Text files previews are no longer adjusted to its content width, but its container for better flexibility. I think it may be worth revisiting the previews' width to find an option that could fit perfectly for every type of media preview.

**Review by jwebbdev — APPROVED** [review]
Nice, looks good!

**Pull request merged**
