### PR TITLE
SPT: Fix Safari Overlapping Layout Issue

### PR DESCRIPTION
**Pull request by jeryj**
Safari has a severe overlapping layout issue in iframe previews: https://github.com/Automattic/wp-calypso/issues/39874

This PR adds a small CSS override to fix layout previews in Safari.

### Testing Instructions
- Open Safari
- Set-up your FSE dev environment
- Got go Page -> Add New
- Select the effected layouts, such as Menu, Dalton Homepage, 2020 Homepage, etc.
- Test these layouts in Chrome, Firefox to make sure there isn't a regression

### Before
Screen Shot 2020-03-09 at 2 46 10 PM
Screen Shot 2020-03-09 at 2 46 35 PM
Screen Shot 2020-03-09 at 2 46 21 PM

### After
Screen Shot 2020-03-09 at 3 39 01 PM
Screen Shot 2020-03-09 at 3 39 23 PM
Screen Shot 2020-03-09 at 3 39 36 PM

### CODE REVIEW

**Comment by jeryj** [comment]
It's not totally clear to me _why_ this fixes it:

```
.wp-block-columns > .block-editor-inner-blocks > .block-editor-block-list__layout > [data-type='core/column'] {
    flex-direction: row;
}
```

It's not an issue in the Editor view. 

Alternatively, while in the dev tools in Safari, you can comment out the `flex: 1;` to make the style for `[data-type='core/column']` become `flex: 1 1 auto;`. 

Screen Shot 2020-03-09 at 2 31 27 PM

This fixes the layout, but using this CSS as an override in our iframe CSS _does not fix it_ even though it should be identical to this (which, again, does not work for some reason):

```
.wp-block-columns > .block-editor-inner-blocks > .block-editor-block-list__layout > [data-type='core/column'] {
    flex: 1 1 auto;
}
```

It's quite odd, which makes me think it's a Safari bug, but I'm having a hard time isolating it to confirm.

**Comment by jeryj** [comment]
I've isolated the issue and update the PR to fix what seems to be the exact Safari bug. The bug is that  Safari is not calculating a height for elements when:

1. Parent is set to `flex-direction: column;`
2. Child is set to `flex-basis: 0;`

You can see this in an isolated test case on this codepen: https://codepen.io/jeryj/pen/NWqXerm View this in Chrome and Safari to see how the layout is overlapping in Safari and renders correctly in Chrome.

If you change the child to `flex-basis: auto;` Safari renders correctly.

**Comment by retrofox** [comment]
Excellent work, Jerry

**Comment by simison** [comment]
Does this need follow up in core columns block?

**Comment by jeryj** [comment]
It only appears to be a layout issue when using the iframe preview in SPT. The editor view was fine. So I guess no follow-up is needed in core columns block?

**Pull request merged**
