### PR TITLE
UI: Use the hasSidebar property to drive the sidebar instead of section.secondary

### PR DESCRIPTION
**Pull request by blowery**
This allows components to fire a  action to hide the sidebar and put the apporpriate class on the Layout component

Test live: https://calypso.live/?branch=fix/ui/use-has-no-sidebar

### CODE REVIEW

**Comment by blowery** [comment]
cc @mtias @bluefuton

**Comment by bluefuton** [comment]
Looks good. 

Can we add a test for the selector?

**Comment by blowery** [comment]
@bluefuton test added. wow, that seems weird.

**Comment by bluefuton** [comment]
Rebased and fixed conflicts.

**Comment by bluefuton** [comment]
Looks good to me 🚢

**Comment by mcsf** [comment]
Out of curiosity, could you provide context/motivation for this change?

**Comment by bluefuton** [comment]
@mcsf the goal is for us to remove the sidebar from `#secondary` in Reader Full Post View. Here's some background from @blowery:

> This is usually done by adding a new section to the section config, but sections are dictated by a prefix. In our case, full posts live at a url that has dynamic components and the base prefix is a real page. That is, /read/feeds/1234 is a feed listing (which may have a sidebar, but is looking like it may not) and /read/feeds/1234/posts/5678 is the full post view. We can’t really use a prefix of /read/feeds/ because the section would apply for both the feed view and the full post view.

**Comment by mcsf** [comment]
Aha, I see, thanks for that.

> This is usually done by adding a new section to the section config, but sections are dictated by a prefix.

One exception to this is the logged-out theme showcase (compare logged-out `/design` with its logged-in counterpart), where we drop the sidebar. Could the architecture there inform the Reader's? cc @ockham @seear

**Comment by seear** [comment]
> One exception to this is the logged-out theme showcase (compare logged-out /design with its logged-in counterpart), where we drop the sidebar. Could the architecture there inform the Reader's? 

We cheat a bit with this, because we know that there is never a sidebar in logged-out mode:
https://github.com/Automattic/wp-calypso/blob/4c4d3d133cf8b22f4def007efb2c1df41c5a9f3c/client/layout/logged-out.jsx#L25

**Pull request merged**
