### PR TITLE
Remove e2e tests for post visibility 

### PR DESCRIPTION
**Pull request by olaseni**
Fixes failing e2e tests that arose as a result of the post visibility component that was removed in this [PR](https://github.com/WordPress/gutenberg/pull/60456) ( [commit](https://github.com/WordPress/gutenberg/commit/50f5c74ecbd267a701704d607f70385255a72033) ).

### CODE REVIEW

**Comment by olaseni** [comment]
Pinging @ntsekouras because you put out the origin PR. Would it be appropriate to remove this test? Are there plans to migrate them instead since as mentioned [here](https://github.com/WordPress/gutenberg/pull/60456#issuecomment-2036926482), the UI is being moved elsewhere.

**Comment by ntsekouras** [comment]
>Pinging @ntsekouras because you put out the origin PR. Would it be appropriate to remove this test? Are there plans to migrate them instead since as mentioned https://github.com/WordPress/gutenberg/pull/60456#issuecomment-2036926482, the UI is being moved elsewhere.

Now we are using the new Post Status dialog to explicitly handle the post status. So you could either remove these tests or update them to test whatever, but using the the new component. For example in order to set a password, you can do it through the Post Status component.

**Review by stephanethomas — APPROVED** [review]
Looks good to me. I'm going to approve that pull request - I'll let you decide if it's better to remove those tests rather than updating them as Nik mentioned it.

**Comment by olaseni** [comment]
There old UI is so far off from the new UI that the effort it takes to have tests that work across both versions is considerable. I'm going to go ahead with my initial decision to remove the tests and them introduce them after the upgrade.

**Pull request merged**
