### PR TITLE
 TinyMCE: Load skin files from a new, versioned URL structure

### PR DESCRIPTION
**Pull request by nylen**
This PR seeks to load TinyMCE "skin" files from a different URL than the main WP.com version.  This will isolate Calypso TinyMCE upgrades from core merges on WP.com.

Later on, we can revisit the way these files are served to make this a bit easier, but for now, this approach won't change the profile of network requests from Calypso, and there is documentation for future users.

See also: p7DVsv-4CT-p2

## To test

Verify that the editor is not loading any TinyMCE-related files from unversioned  WP.com-global files like `//s1.wp.com/wp-includes/js/...`:

2018-05-09t22 34 12-0500

Verify that the editor still works and appears correctly styled.

Verify that the same approach works in the TinyMCE fields for the WooCommerce extension.

### CODE REVIEW

**Comment by pento** [comment]
This approach works for me: we do the same thing with twemoji assets, Calypso and wp-admin can run different versions, because the files are stored in versioned locations.

It seems like `wp-content.css` is still being loaded from the unversioned location: this is a core file, so you probably want to version it, too. I guess it's [defined here](https://github.com/Automattic/wp-calypso/blob/b38bc504e7633fe81264f1a720f89d4c240512d4/server/pages/index.js#L42), but I've forgotten exactly how Calypso works, so will defer to those more experienced than I. 🙂

**Comment by nylen** [comment]
> It seems like `wp-content.css` is still being loaded from the unversioned location

I think this one is OK.  We're loading it from `/calypso/tinymce/skins/wordpress/wp-content.css` which lives in the Calypso repo (`public/tinymce/skins/wordpress/wp-content.css`).  So core merges won't clobber this version of the file.  Also, it does look like there have been some Calypso-specific changes here [in the past](https://github.com/Automattic/wp-calypso/commits/24deaec774a8203d1c849b200466aa0abf12527e/public/tinymce/skins/wordpress/wp-content.css), which we wouldn't want to overwrite anyway.

**Comment by azaozz** [comment]
This sounds good, my only "nitpick" would be that if there is already `/calypso/tinymce/skins/...` (which is an external / non-standard location according to TinyMCE), why creating another external / non-standard one at `//s1.wp.com/wp-content/tinymce-assets/...`. That would make updating it even harder :) 

TinyMCE is a "package" by itself and loads some of its assets automatically from a "base" directory. Most of that automatic loading can be turned off or customized. Thinking it makes sense to have one place (perhaps `/calypso/tinymce/...`) where all TinyMCE assets are kept. Would make it easier to maintain and debug :)

**Comment by nylen** [comment]
Yes, I agree we should load all of these assets from the same place (and the `/calypso/...` location has the additional benefit of being within the Calypso repository).

I didn't do that here in order to keep the profile of network requests the same for these assets, in terms of what is served from the CDN and what is served from `wordpress.com/calypso/`.  I think this is a good follow-up step once we confirm that it's OK to push these requests onto `/calypso/` instead.

**Comment by gwwar** [comment]
Thanks for taking this one on @nylen !

**Comment by nylen** [comment]
Per systems, we are good to make this URL change.  We can also get rid of the TinyMCE version in the URL since we will be updating these assets directly within Calypso.

I should be able to do this within a few days, or I'm happy to review if someone wants to beat me to it.

**Pull request merged**
