### PR TITLE
Recent Feed Overhaul - Handful of CSS tweaks

### PR DESCRIPTION
**Pull request by davemart-in**
## Description

I did one final review this morning and cleaned up 3 minor CSS issues. Head to `/read?flags=reader/recent-feed-overhaul`, then review:

### 1) Ghost SVG

When you pull up the full-page post and scroll to the bottom, if you're following the blog, you'll see an empty spot where the plus symbol should be:

**Before**
svg-before

**After**
svg-after

### 2) Two column alignment

When you pull up the two column view, the second column is currently breaking out of the default layout width:

**Before**
alignment-before

**After**
alignment-after

### 3) On mobile, the layout icons should be right aligned

**Before**
icons-before

**After**
icons-after

### CODE REVIEW

**Review by eoigal — COMMENTED** [review]
I'm seeing this in the 2 column (without the onboarding) - just checking if that's correct? I think the layout selection should be right aligned.
Screenshot 2024-12-10 at 11 07 45

**Comment by artemiomorales** [comment]
> I'm seeing this in the 2 column (without the onboarding) - just checking if that's correct? I think the layout selection should be right aligned.

I'm unable to replicate this. Looks good to me!

**Comment by artemiomorales** [comment]
Sorry, just realized the icons align to the left in Firefox:

Screenshot 2024-12-10 at 12 28 55

**Review by eoigal — APPROVED** [review]
WFM

**Pull request merged**
