### PR TITLE
Update domain upsell copy

### LINKED ISSUE #72660: My home domain upsell: Change copy
See pebzTe-xR-p2#comment-1166

New copy is: 

> Stake your claim on your corner of the web with a site address that’s easy to find, share, and follow.

> BUTTON: Buy this domain

Acceptance criteria:
- [ ] Implement new copy and CTA text.
- [ ] Apply string freeze label.

### PR DESCRIPTION
**Pull request by DustyReagan**
#### Proposed Changes

* Update domain upsell copy.

Before | After
--|--
before | after

#### Testing Instructions

* Load this PR
* Confirm new copy is correct
* Apply string freeze tag

#### Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

Related to #

### CODE REVIEW

**Review by lupus2k — APPROVED** [review]
Looks like it's suggested on the comment: pebzTe-xR-p2#comment-1166

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/7783535

Thank you @DustyReagan for including a screenshot in the description! This is really helpful for our translators.

**Review by candy02058912 — APPROVED** [review]
Double checked! LGTM! Reran e2e and it's passing now.

**Comment by candy02058912** [comment]
btw did anything change with the "String Freeze" label? It used to mark the check as unpassed when translations aren't complete yet, but now even with incomplete translations it's marked as passed.

**Comment by DustyReagan** [comment]
> btw did anything change with the "String Freeze" label? It used to mark the check as unpassed when translations aren't complete yet, but now even with incomplete translations it's marked as passed.

I saw that! Now it's back to not passing again. I have no idea. 🤷‍♂️

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/7783535).

**Pull request merged**
