### PR TITLE
Enable overriding backend A/B variations in non-production environments

### PR DESCRIPTION
**Pull request by jsnmoon**
This change fixes A/B Test Helper component's functionality by preserving localStorage data for A/B tests when the `dev/test-helper` flag is enabled. 

(This flag is enabled only for development and wpcalypso environments.)

#### Testing instructions

1) Spin up this branch locally and start your server.
2) Locate the A/B test helper and manually select a variation for any of the A/B tests.
a_b_test_helper
3) Ensure that your selected variation from (2) has persisted following the page refresh caused by the variation selection.

### CODE REVIEW

**Comment by alisterscott** [comment]
Works well - thanks for this change 👍 

We do run our automated e2e tests in production though - is there any way to allow this in production environments also - without removing the reason for the original change in persisting these settings?

I guess it's pretty unlikely a customer would modify their own localstorage in the browser to change their test groups, or is this broader in that a new session would randomly assign local groups and override what is on the server?

**Comment by jsnmoon** [comment]
> [...] is this broader in that a new session would randomly assign local groups and override what is on the server?

You nailed it. We fetch assigned variations from the backend to avoid erroneously re-assigning users to a different variation. This can occur whenever the user's localStorage is cleared (e.g. upon browser cache clear, different computer or browser, etc). 

> We do run our automated e2e tests in production though - is there any way to allow this in production environments also - without removing the reason for the original change in persisting these settings?

I have two ideas:

1) Is there an easy way to tell if the code is being executed in an e2e context (e.g. by reading a localStorage value or a feature flag)? In that case, we could insert logic that detects the e2e context and adjust the behavior accordingly. 

2) Would it be possible to set the user attribute of the test user in the backend? If not, would it be possible to mock out the API response? This approach would enable us to ship the client code without having to add special handling for the testing code. This would eventually mean less code (and smaller bundle sizes) down the line for the user.

What do you think of the above ideas? Also, could you provide examples of e2e tests running on production that necessitates manually adjusting the A/B test assignment via localStorage modifications?

**Comment by alisterscott** [comment]
Thanks for your response @jsnmoon 

> Is there an easy way to tell if the code is being executed in an e2e context (e.g. by reading a localStorage value or a feature flag)? In that case, we could insert logic that detects the e2e context and adjust the behavior accordingly.

We use a custom user agent that contains the string wp-e2e-tests which we use in tracks and all analytics to ignore anything being done by our tests.

> Would it be possible to set the user attribute of the test user in the backend? 

I think so, it's just more when a new test is introduced this becomes a manual task we need to do - but doable

> Also, could you provide examples of e2e tests running on production that necessitates manually adjusting the A/B test assignment via localStorage modifications?

There's currently no active AB tests which modify the behaviour for existing users. But we've had them in the past. An example was a domain suggestions AB test which showed different domains results depending on which group you were in. So we have automated tests that use the domains screen for an existing user to add a new domain, and if the results are different then our tests get confused. So in this case we used localstorage to always set a group (typically the control) to give us consistent results.

As I said, we don't currently have active AB tests that change behaviour for existing users, but these could be introduced at any point.

Thanks

**Comment by jsnmoon** [comment]
Hi @alisterscott, thank you for the context.

I added two commits to this PR that enables E2E test environment detection by checking the user agent. If the reviewers deem this approach sound, I recommend going forward with this change.

However, if the reviewers deem these additions unfit, I recommend setting the test user's assigned A/B variations in the backend instead for E2E tests going forward.

**Comment by alisterscott** [comment]
Thanks @jsnmoon for the update

I tested this and it worked well. I disabled the dev/test helper locally and I was still able to override the flags only when running as the e2e test user agent, but not with other as expected ✅ 

I was still able to use the dev/test helper also when enabled ✅

Thanks again

**Comment by markryall** [comment]
My vote is to stick with the user agent approach that you've added here.  Requiring the e2e tests to have access to the backend sounds enormously complicated and a security nightmare.

Any chance we could merge at least the change for local development and wpcalypso?  It is currently quite difficult to test any PR that relates to an a/b test.

**Comment by jsnmoon** [comment]
I'll go ahead with the current approach using UA detection. For any reviewers who disagree with this approach, please speak up here and we can address any concerns in a future PR.

**Pull request merged**
