### PR TITLE
Signup: Simplify `site-topic` step

### PR DESCRIPTION
**Pull request by shaunandrews**
Trying out some of the ideas from the prototype to see how things feel:

slice 4

@Automattic/onboarding-design @Automattic/onboarding-dev

### CODE REVIEW

**Comment by fditrapani** [comment]
I like where this is heading. It gives us so much more real estate to show more website preview.

**Comment by scruffian** [comment]
> +15 −33 
Always good to have less lines than you started with 👏

**Comment by southp** [comment]
I'm falling in ❤️ of the simplicity here.

**Comment by sixhours** [comment]
This looks so much cleaner!

**Comment by bsessions85** [comment]
This change broke one of the e2e tests that have been added( by @taggon ) to ensure that the new onboarding flow works properly. I have fixed it for this change, but just wanted to mention here that there are e2e tests for this flow now and changing things(like css) can break them, so please be aware.

**Pull request merged**
