### PR TITLE
Build: update to Node 6.10.2

### PR DESCRIPTION
**Pull request by gwwar**
This PR updates Calypso to node v6.10.2. Changes include some performance improvements for `querystring` and other APIs and bugfixes. This brings us to the [latest of the LTS line](https://nodejs.org/en/blog/release/v6.10.2/). Changes here look rather safe, so I'll try landing this tomorrow unless we find blockers.

### Local Dev
- Switch to node version 6.10.2 (npm 3.10.10)
- `make distclean`
- `make run`
- No functional changes to Calypso
### Local Docker Image
- Follow image instructions at: PCYsg-5XR-p2
### Desktop
- Clone the wp-desktop project
- Follow install instructions
- In the calypso submodule checkout this branch
- Desktop behaves normally

### CODE REVIEW

**Comment by gwwar** [comment]
Thanks @dmsnell! I also tested on local/docker and things look good. Desktop dev didn't look happy, but it looks like Desktop is broken with Calypso master again

**Comment by samouri** [comment]
This may be unrelated, but in this branch I've been having trouble running `make run`.

```

/bin/sh: wp-calypso/node_modules/.bin/webpack: No such file or directory
make: *** [build-server] Error 127
```

**Comment by gwwar** [comment]
@samouri `make run` looked OK after an `npm install`. I rebased with master and couldn't repro again after another distclean. Not sure if it's transient or it was fixed elsewhere on a clean install. Do you mind seeing if you can trigger that again?

**Comment by gwwar** [comment]
Retested on local/docker for 6.10.2

**Comment by samouri** [comment]
@gwwar, I forgot to report back that it worked after an npm install!

**Pull request merged**
