### PR TITLE
Update/move cart to sticky when scroll use clip

### PR DESCRIPTION
**Pull request by andrii-lysenko**
#### Proposed Changes

This is a Second draft On Sticky Header. As another version in comparison to #71470. 
Note, properly visible only on desktop (screen >900px wide)

#### Testing Instructions

*

#### Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

Related to #

### CODE REVIEW

**Comment by elliottprogrammer** [comment]
Thanks for working on this and experimenting with various approaches @andrii-lysenko!

Personally, I like this approach so far Andrii! 🙂  Now we just need the cart to show up in the "14 day money back guarantee." banner, right at the moment the banner becomes sticky. Could you try to add that to this PR next? so then we can test/experience the full effect?

**Comment by andrii-lysenko** [comment]
Thanks @elliottprogrammer, I've forgotten about that. I've added Cart to to a banner in the latest commit. We would still want to iterate on the final look, though, don't wan't to spend much time if we would decide to go with some other approach.

**Comment by elliottprogrammer** [comment]
> Thanks @elliottprogrammer, I've forgotten about that. I've added Cart to to a banner in the latest commit. We would still want to iterate on the final look, though, don't wan't to spend much time if we would decide to go with some other approach.

Awesome @andrii-lysenko, thanks for adding in the final action/behavior of moving the cart to the "14 day money back guarantee." banner, right at the moment the banner becomes sticky.  This keeps the shopping cart visible to the user at all times while scrolling up and/or down the page. Personally, I love it, I think it is the best solution so far, at least for the initial MVP iteration.

I agree we would likely want to refine the final look & alignment of the cart so that the cart remains in the same horizontal position when it moves from the top masterbar to the "14 day money back guarantee." banner (or some solution to that effect so the eyes don't need to jump/search for the cart that is now aligned in a different position (horizontally left or right)).

----

Yes, let's get @Automattic/jetpack-design  to take a look, (@ederrengifo - (Design Lead) and iLona - (Design support) to hear their thoughts and feedback about this. 🙂

- As far as the top nav masterbar & "14 day money back guarantee." banner sticky behavior, and moving the cart to the banner which is currently sticky/fixed to the top. Does this solve the problem of keeping the cart visible at all times?
- As for design, how can we improve overall usability, gracefulness, alignment, and/or appearance, eliminating/preventing any user confusion with always knowing where the shopping cart is located?  Any fine-tuning design improvements you suggest?

**Comment by ederrengifo** [comment]
LGTM! 👍

**Pull request merged**
