### PR TITLE
Full Site Editing Design Picker: Enable Russell theme

### PR DESCRIPTION
**Pull request by jeyip**
#### Changes proposed in this Pull Request

* Update `available-designs-config.json` to include new Russell block theme.
* Russell is a selectable theme in the `/new` FSE beta onboarding design picker

#### Screenshots
Screen Shot 2021-11-30 at 5 20 56 PM

#### Testing instructions

* Apply branch to local calypso dev environment
* Visit http://calypso.localhost:3000/new/beta
* Enroll in the FSE beta
* Pick a free test domain
* Verify that Russell is a selectable theme
* Create a site with Russell enabled and smoke test the theme

Related to # https://github.com/Automattic/wp-calypso/issues/58663

### CODE REVIEW

**Comment by jeyip** [comment]
Note:

Let's hold off on merging this until block errors with Russell have been fixed. https://github.com/Automattic/wp-calypso/issues/58663#issuecomment-984161386 and https://github.com/Automattic/wp-calypso/issues/58787

**Comment by creativecoder** [comment]
I'm no longer seeing the Gutenberg related block validation error with the Russell homepage that I did before (https://github.com/Automattic/wp-calypso/issues/58787#issuecomment-987019223). Do you @jeyip ?

If not, I think we can go ahead and merge this!

**Review by creativecoder — APPROVED** [review]

**Comment by jeyip** [comment]
> I'm no longer seeing the Gutenberg related block validation error with the Russell homepage that I did before (#58787 (comment)). Do you @jeyip ?

I'll double-check this and merge it before EOD 👍

**Comment by jeyip** [comment]
> If not, I think we can go ahead and merge this!

Confirmed that I don't see block validation errors anymore described in https://github.com/Automattic/wp-calypso/issues/58787#issuecomment-987019223.

🚢

**Comment by jeyip** [comment]
> If not, I think we can go ahead and merge this!

Confirmed that I don't see block validation errors anymore described in https://github.com/Automattic/wp-calypso/issues/58787#issuecomment-987019223.

🚢

**Pull request merged**
