### PR TITLE
Plans: Enable WordAds for all

### PR DESCRIPTION
**Pull request by artpi**
This stops wordads instant activation test and enables the feature for all users.

### Testing

1. Build with just regular make run
2. Go to /plans, see description mentioning WordAds
3. Go to /plans/compare, see wordads feature
4. Build with `ENABLE_FEATURES=manage/plan-features make run` to see redesigned plans page
5. Go to http://calypso.localhost:3000/plans/ to see if WordAds is in new table
6. You need premium / business site
7. Go to https://wordpress.com/plans/my-plan/your-site
8. You should see "Monetize your site". Click it, go there :)

CC @lamosty @rralian @gwwar 

Test live: https://calypso.live/?branch=update/wordads-for-all

### CODE REVIEW

**Comment by lamosty** [comment]
This works for the redesigned plans as they take data from the plan constants but doesn't work for the old/current plans implementation. You'll probably need to modify the plans features API endpoint.

Otherwise, looking fine :+1:.

**Comment by gwwar** [comment]
@artpi could you add some testing instructions for what we should expect? Are we enabling this for Premium and Business plans only?

**Comment by artpi** [comment]
> could you add some testing instructions for what we should expect? 

Added, sorry.

> Are we enabling this for Premium and Business plans only?

Yes :)

**Comment by artpi** [comment]
Rebased, dont be afraid of 👍

**Comment by rralian** [comment]
@artpi When I test this branch along with the API patch I see two issues;
1. We lose the info popup next to the feature name on the plans/compare page.
2. The feature is in the wrong order and appears below "Premium Themes", which is a weird presentation because we go from premium and business feature to business-only features, back to premium and business feature again.

**Comment by artpi** [comment]
@rralian Refactored, went back to handling this frontend-only.

**Comment by rralian** [comment]
> @rralian Refactored, went back to handling this frontend-only.

This looks and works well for me as long as I _do not_ apply D2261-code, which I believe is the intent now. I've tested `/plans`, `/plans/compare`, and `/start/plans` in both the old version and the new version (as appropriate) and it all looks good. I'm going to merge it.

**Comment by artpi** [comment]
Splendid, thanks @rralian !

**Pull request merged**
