### PR TITLE
Fix back link in user security page

### PR DESCRIPTION
**Pull request by madhusudhand**
Fixes: https://github.com/Automattic/dotcom-forge/issues/10004

## Proposed Changes

* Fixes back link in user security page when visited from Advanced Tools (UHM enabled)
* Updates the source param of security page
* Updates back link text based on the source url

image

## Testing Instructions

* Visit `/sites/tools/sftp-ssh/:site`
* Click on `Add an SSH Key`
* It should take you to user security page.
* Back link and text should be updated pointing to Advanced Tools page, and clicking on which should land user in the previous page.

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
    - [ ] For UI changes, have we tested the change in various languages (for example, ES, PT, FR, or DE)? The length of text and words vary significantly between languages. 
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Review by fushar — COMMENTED** [review]
Hmm, currently the existing `Back to Hosting Configuration` text is also inaccurate as it has been replaced by `Server Settings`.

`Back to Advanced Tools` also sounds a bit weird because it's the tab name, not the subtab. I'd propose to just simply use `Back` for all scenarios. What do you think? cc: @taipeicoder

**Comment by taipeicoder** [comment]
Yes, let's just use `Back`.

**Comment by madhusudhand** [comment]
> Back to Advanced Tools also sounds a bit weird because it's the tab name, not the subtab

Makes sense. Updated the button text to `Back` for all scenarios. 82b5a867640234a58aee979fb90cb7c02923384f

**Review by fushar — APPROVED** [review]
Works as intended 👍

**Pull request merged**
