### PR TITLE
Bump `@wordpress/interface` and other monorepo packages for Gutenberg 13.3.0 compat

### LINKED ISSUE #63944: [Gutenberg 13.3.0-rc.1] FSE: The Site Editor does not load
### Quick summary

During our team testing, we found that the site editor does not load while using an FSE-compatible theme. 

Markup 2022-05-24 at 12 37 01

- Self-hosted sites are working normally.
- Non-a11n accounts are also impacted.  

**Error in Console**

```
??-eJytVNGSmzAM/KEal…Pzt5fTL+tvH9w=:1028 Uncaught TypeError: (0 , c.dispatch)(...).setDefaultComplementaryArea is not a function
    at fo (??-eJytVNGSmzAM/KEal…TL+tvH9w=:1028:1510)
    at Module.Eo (??-eJytVNGSmzAM/KEal…TL+tvH9w=:1028:2321)
    at HTMLDocument.<anonymous> (VM1642 themes.php:16355:17)
fo	@	??-eJytVNGSmzAM/KEal…Pzt5fTL+tvH9w=:1028
Eo	@	??-eJytVNGSmzAM/KEal…Pzt5fTL+tvH9w=:1028
(anonymous)	@	VM1642 themes.php:16355
```

### Steps to reproduce

1. Activate an FSE compatible theme: https://wordpress.com/themes/filter/full-site-editing
2. Open the site editor.
3. The site editor does not load.

### What you expected to happen

The site editor to load.

### What actually happened

The site editor did not load.

### Context

During team testing of Gutenberg.

### Simple, Atomic or both?

_No response_

### Theme-specific issue?

_No response_

### Browser, operating system and other notes

Chrome

### Reproducibility

_No response_

### Severity

_No response_

### Available workarounds?

_No response_

### Workaround details

_No response_

### PR DESCRIPTION
**Pull request by mattwiebe**
#### Changes proposed in this Pull Request

* Bump `@wordpress/interface` and other monorepo packages to the latest versions

Original discussion: p1653583842699789-slack-CBTN58FTJ

This one's tricky because `@wordpress/interface` isn't separately packaged in a way that lets us override a Core version. Instead, it's inlined by webpack rather than transformed into consuming a WP script by the dependency extraction plugin. Phew.

WordPress/gutenberg/pull/40923 introduced the new stuff, but Help Center is still packaging an older, outdated version, which then tramples the `core/interface` redux store namespace and lacks the new functions, which are called in the `edit-site` packages.

#### Testing instructions

On a sandboxed site with the `gutenberg-edge` sticker, build and run this version of ETK, and try to load the Site Editor.

Before you would see an error on a call to `setDefaultComplementaryArea` and a WSOD in the Site Editor.

Fixes #63944

### CODE REVIEW

**Comment by Addison-Stavlo** [comment]
Gave this a test run and it solves the WSOD on my end. Smoke testing everything seems good!

I would like to see another review / smoke test though since we are upgrading so many packages here.

**Review by Addison-Stavlo — COMMENTED** [review]
Gave this a test run and it solves the WSOD on my end. Smoke testing everything seems good!

I would like to see another review / smoke test though since we are upgrading so many packages here.

**Comment by fullofcaffeine** [comment]
Thanks for the help testing, @Addison-Stavlo!

I also spent some time this morning testing this with @brookewp and the web app seems to work fine. However, we did see some issues on the `/devdocs` page. More specifically, there's an uncaught exception (more on that below) that originates from `react-with-styles-interface-css` `6.0.0`, which is a transitive dependency to `react-dates` `21.8.0`, which itself is a dependency to the new version of `@wordpress/components` (`19.11.0`).

The error is the following:

```
Uncaught TypeError: _interopRequireDefault is not a function
```
In `../node_modules/@babel/runtime/helpers/esm/interopRequireDefault.js`. It returns the module object with a `default` property pointing to the actual function, but the consumer code tries to call the object:


```js
// react-with-styles-interface-css/dist/index.js

var _interopRequireDefault = __webpack_require__("../node_modules/@babel/runtime/helpers/esm/interopRequireDefault.js");

// _interopRequireDefaultg is not a function, but an object with a shape like: `Object { default: Getter, … }`. 
// The `default` getter points to the actual function that should be called. We could force-fix it by calling 
// `_interopRequireDefault.default` below, but obviously not a suitable fix as this is a third-party transitive dependency and the file is generated by WebPack.

// Errors here because `_interopRequireDefault` is not a function. 
var _arrayPrototype = _interopRequireDefault(__webpack_require__("../node_modules/array.prototype.flat/index.js"));
```

It appears as if the first require is wrong. I think the __interopRequireDefault should be inlined AFAIU, so that it can be used to get the default export?

The same generated file on `trunk` inlines the definition for the `_interopRequireDefault` function in the same `index.js` file instead of requiring it:

```js
// react-with-styles-interface-css/dist/index.js

(...)

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { 'default': obj }; }

(...)
```

Which works fine.

---

This seems to be something that can be fixed at the Webpack level, though I'm not entirely sure yet. This also doesn't seem to be a hard blocker for releasing GB 13.3.0 as the web app seems to be working fine, but of course, it'd be best to get to the bottom of this issue and come up with a fix first. I'll spend some additional time on that today.

cc @noahtallen and @Automattic/team-calypso-frameworks here as well to see if you have any additional ideas.

**Comment by fullofcaffeine** [comment]
I've spent most of my time today trying to get to the bottom of this. Kudos to @noahtallen for helping as well. I couldn't yet find a workaround, but I might be onto something as I found out it might be related to a new version of the `react-dates` package that is required by the some (or most?) of the new WP packages (see [the message above ](https://github.com/Automattic/wp-calypso/pull/64093#issuecomment-1139972282) for more details).

To verify this:

1. Checkout this branch and apply the following diff:

```
diff --git a/package.json b/package.json
index 641d7058f7..52d4831add 100644
--- a/package.json
+++ b/package.json
@@ -278,6 +278,7 @@
                "yargs": "^17.0.1"
        },
        "resolutions": {
+               "react-dates": "17.1.1",
                "@automattic/newspack-blocks/swiper@4.5.1": "patch:swiper@4.5.1#.patches/swiper@4.5.1.diff",
                "@automattic/newspack-blocks/prettier": "npm:wp-prettier@2.6.2-beta-1",
                "@types/react": "^17.0.39",
```

This will force `react-dates` to the previous working version.

2. Run `yarn && yarn start`. Wait for assets to be compiled.
3. Access `http://calypso.localhost:3000/devdocs/wordpress-components-gallery`, it should render without any JS errors. If you revert the changes, you'll see the error described in the message above.

So at least it seems we managed to narrow it down to a single package? Hopefully! 🤞🏻  I'll proceed to investigate what in `react-dates` version `21.8.0` might be causing the issue. If you have any thoughts, let me know! 

Also, cc'ing @jsnajdr to see if you have any thoughts about this as well! 🙇🏻

**Comment by fullofcaffeine** [comment]
I narrowed the issue down to this PR from `react-with-styles-and-interface-css`: https://github.com/airbnb/react-with-styles-interface-css/pull/23. This changeset is included in version `6.0.0` that's a direct dependency of the new `react-dates` (`21.8.0`) that's installed as part of this mass update `@wordpress` of dependencies. 

The culprit seems to be the babel update in the aforementioned PR. It generates a `require` for importing `babel`'s `_interopRequireDefault` function in its `dist/`, like this:

```js
var _interopRequireDefault = require("@babel/runtime/helpers/interopRequireDefault");  
```

This is what triggers the error in the Calypso `/devdocs/wordpress-components-gallery` page:

```
Uncaught (in promise) TypeError: _interopRequireDefault is not a function
    <anonymous> app:///../node_modules/react-with-styles-interface-css/dist/index.js:10
    js http://calypso.localhost:3000/calypso/evergreen/vendors-node_modules_wordpress_components_build-module_card_card-divider_component_js-node_mo-041708.js:1771
(...)
```

See [why](https://github.com/Automattic/wp-calypso/pull/64093#issuecomment-1139972282).

**It's probably due to some incompatibility with Calypso's Webpack configuration, I assume, but I couldn't pinpoint what, yet. This is what I'll try to find out next cc @noahtallen if you have any ideas!**

Before that PR in `react-with-styles-interface-css`, the same function was inlined, like this:

```js
function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { 'default': obj }; }    
```

You can verify that with the following steps:

1. Clone `git@github.com:airbnb/react-with-styles-interface-css.git` and `cd` into the newly-created directory;
2. git-checkout the `interface-v4.0.2` branch. This is the version Calypso's `trunk` uses;
3. Install `babel-cli` globally -- the `build` task in that branch will fail to find the `babel` binary if you don't do this: `npm uninstall -g babel-cli`;
4. Install packages and build: `npm install && npm run build`;
5. Relative to the same dir, open `packages/interface/dist/index.js` in you favorite editor and verify that the `_interopRequireDefault` is defined there, in the same file;
6. Now switch over to the `master` branch;
7. Run `find . -name 'node_modules' -type d -prune -print -exec rm -rf '{}' \; && npm install && npm run build` for a clean install and build;
8. Relative to the same dir, open `packages/interface/dist/index.js` in your favorite editor and verify that the `_interopRequireDefault` is now `required` from an external js file.

**UPDATE:** It's important to note, that `dist/index.js` file is further processed by the Webpack in Calypso, and the `require` is turned into a `__webpack_require__`.  it's possible Calypso's Webpack configuration needs to be updated to support properly importing this module. Remember, the function is actually there, but it's in a `default` property in the returned object, see [#](https://github.com/Automattic/wp-calypso/pull/64093#issuecomment-1139972282).

**Comment by fullofcaffeine** [comment]
> The culprit seems to be the babel update in the aforementioned PR. It generates a require for importing babel's _interopRequireDefault function in its dist/, like this:

I've further researched this and what I mentioned above It's not really the culprit, but a symptom of a change in babel. I've found that same change in dozens of other packages, too. The culprit seems to be the fact that those packages were built with a more recent version of babel that requires the `interop` function like that. 

I did find a hacky workaround - to use the yarn [patch protocol](https://yarnpkg.com/features/protocols#patch) to change the require line from:

```js
var _interopRequireDefault = require("@babel/runtime/helpers/interopRequireDefault");  
```

To:

```js
var _interopRequireDefault = require("@babel/runtime/helpers/interopRequireDefault").default;
```

This works. However, we'd have to patch dozens of different packages (mostly the new `@wordpress` packages versions and some transient dependencies, but still a lot!) so it wouldn't scale. Still, this at least explains how this could be solved. I still don't know if we should tweak the Webpack or Babel configuration to solve this, yet. I'll continue the investigation tomorrow.

**Comment by fullofcaffeine** [comment]
Oh, I see what might be wrong. Webpack is changing the require param to require the ESM version of the module for some reason:

```js
var _interopRequireDefault = __webpack_require__("../node_modules/@babel/runtime/helpers/esm/interopRequireDefault.js");
```

We should get the CJS version instead, that correctly exports it in a compatible way:

```js
module.exports = _interopRequireDefault, module.exports.__esModule = true, module.exports["default"] = module.exports; 
```  

I still don't know where in Webpack configuration is the issue, though. I'll keep looking.

**Comment by fullofcaffeine** [comment]
Seems it's related to the conditional exports and Webpack. It seems to be something similar to what was reported in this issue: https://github.com/iamkun/dayjs/issues/492.

**Comment by noahtallen** [comment]
> This is what I'll try to find out next cc @noahtallen if you have any ideas!

I unfortunately don't have any immediate ideas!

Since this is blocking Gutenberg release, my thought process is:
- utilize `resolutions` to pin the working version of the package for now so that we can ship. (After testing it still works correctly of course!)
- p2 about the problem to see if others have more ideas about how to solve the root problem.

**Comment by fullofcaffeine** [comment]
I've pinned `react-dates` to `17.1.1`, which solves the issue on the `/devdocs/wordpress-components-gallery` page. Interestingly enough, as I mentioned [here](https://github.com/Automattic/wp-calypso/pull/64093#issuecomment-1141562073), I'm still seeing a lot of packages that `require` the `interopRequireDefault` function, you can verify that by going to the `node_modules` dir in the root of Calypso and running: `ag '_interopRequireDefault = require\("@babel\/'` (I'm using `ag silversearcher`, which I find easier/better than grep).

However, for`@wordpress/components` bundling in Calypso, this doesn't seem to be a problem, as Webpack seems to pick up the source from `build_module` instead of `build` directory, and then the generated modules don't use `interopRequireDefault`. For some reason, it broke with the `react-dates` `21.8.0` transient dependencies, more specifically the `react-with-styles-interface-css` `6.0.0`, which is a dependency of the new `react-dates`, as I explained in a previous message:

> I narrowed the issue down to this PR from `react-with-styles-and-interface-css`: https://github.com/airbnb/react-with-styles-interface-css/pull/23. This changeset is included in version 6.0.0 that's a direct dependency of the new `react-dates` `21.8.0` that's installed as part of this mass update `@wordpress` of dependencies.

Unfortunately, I couldn't pinpoint the root of the issue. It seems to be due to some unintended interaction with conditional exports. My hunch is that the Webpack+babel setup for Calypso can't handle packages that are pre-compiled with a more recent version of Babel that export the `interopRequireDefault` function from an ES module and `require` it from a CJS module. It appears that it was working before for `react-with-styles-interface-css` because it was built with a previous version of Babel that inlined the same function instead, as I explained in a previous comments above.

**Review by noahtallen — APPROVED** [review]
This is testing well for me! (Smoke tested WordPress components, Calypso, and ETK)

**Comment by fullofcaffeine** [comment]
Thanks for testing, Noah! 

This should unblock the release of GB 13.3.0 :) -- the pin of `react-dates` to version 17.1.1 is not ideal, but I couldn't find another workaround for now. Would to know if anyone else has any clues as to what might be the root issue here. cc @Automattic/team-calypso-frameworks @Automattic/team-calypso-components 

@mirka Also cc'ing you since I know you've recently worked on a Babel plugin and might have it fresh in your mind and maybe has some insights to share :) 

Thanks! 🙇🏻

**Comment by ciampo** [comment]
@noisysocks may help with making sure that the version of `react-dates` is good for this PR :)

**Comment by noahtallen** [comment]
I can't recall a lot of the original issue, but do we think the `react-dates` resolution could be removed at this point?

**Comment by ciampo** [comment]
`react-dates` was removed as a dependency of the components package in https://github.com/WordPress/gutenberg/pull/43005 — I don't think that package is used anywhere else in Gutenberg?

It also looks like we're still listing `@types/react-dates` as a dev dependency, I think we should be able to remove that one too.

**Comment by noahtallen** [comment]
Great! I'll make sure that's updated in #77046

**Comment by noisysocks** [comment]
Yes I think `react-dates` was only used by `@wordpress/components` and that I removed that dependency in https://github.com/WordPress/gutenberg/pull/43005.

**Pull request merged**
