### PR TITLE
Notifications: Version bump to 1.2.3

### PR DESCRIPTION
**Pull request by dmsnell**
- Fixes a translation issue in the filter bar
 - Includes more support for deep-linking

**Testing**

Open in the live branch or in local dev and make sure notifications don't blow up.
Make sure to test clicking on links for sites, posts, and comments.

**Notes**

It seems like the unread filter is still not translating properly but I don't think that should
stand in the way of merging this PR.

### CODE REVIEW

**Comment by dmsnell** [comment]
@akirk I'm not sure why the `Unread` filter is special. In the code it appears to be written the same way as the others. Now is the time I would appreciate some help in debugging :smile:

**Comment by gwwar** [comment]
Are we missing translations for that?

**Comment by akirk** [comment]
Our problem seems to be that we load two translation files, for example https://widgets.wp.com/languages/calypso/de.json and https://widgets.wp.com/languages/notifications/de.json but i18n-calypso's setLocale doesn't support merging two files. It kind of works because we have an overlap in translations in Calypso, that's why we're seeing partial translation. The easiest fix will be to merge the notifications json with the calypso json server-side when deploying translations. I'll do that.

**Comment by akirk** [comment]
I have done this for `de` now and it shows that it's working. We'll deploy other locales over time, so we can merge this.

**Comment by dmsnell** [comment]
@akirk is it as simple as "we don't have those translations available" ?

**Comment by akirk** [comment]
@dmsnell yes, in the sense of "not in the json".  We have the translations in GlotPress, so upon the next deploy of a language we'll now include them also in the Calypso json. It would make sense to stop loading the notifications language file when loaded in Calypso as we currently simply dismiss all its translations.

**Pull request merged**
