### PR TITLE
Marketplace: Update cats

### PR DESCRIPTION
**Pull request by lsl**
#### Proposed Changes

* Updates category composition based on p2 discussion pdh6GB-1kr-p2#comment-2208

#### Testing Instructions

* Check the updated categories include the new tags in their search requests
* Check the category name and ordering is updated

#### Pre-merge Checklist

- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in [Simple](P9HQHe-k8-p2-p2), [Atomic](P9HQHe-jW-p2-p2), and [self-hosted Jetpack sites](PCYsg-g6b-p2-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Are we memoizing when appropriate (for expensive computations)? More info in [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md) and [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors)
- [ ] Have we sent any new strings [for translation](PCYsg-1vr-p2-p2) ASAP?

Screen Shot 2022-07-21 at 10 29 39 AM

Related to https://github.com/Automattic/wp-calypso/issues/65219

### CODE REVIEW

**Review by Rolilink — APPROVED** [review]
LGTM

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/7452017

Thank you @lsl for including a screenshot in the description! This is really helpful for our translators.

**Comment by allilevine** [comment]
@Rolilink @lsl Looks like we had a miscommunication about [waiting for translations on this one.](https://github.com/Automattic/wp-calypso/issues/65219#issuecomment-1191064254) Anything we can do to improve that handoff? We should aim to check this off before merging, but it is new:
> Have we sent any new strings [for translation](https://github.com/Automattic/wp-calypso/pull/PCYsg-1vr-p2-p2) ASAP?

**Comment by lsl** [comment]
> Anything we can do to improve that handoff?

I should have posted on the PR instead of the issue :thinking:

Not the worst outcome ever. Only [three new strings](https://translate.wordpress.com/deliverables/overview/7452017/) and a couple of locales are already translated. Leaving as is, I think removing would drop the translations potentially.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/7452017).

**Pull request merged**
