### PR TITLE
Signup: Headstart: Restore users to the Headstart AB test.

### PR DESCRIPTION
**Pull request by kwight**

### CODE REVIEW

**Comment by kwight** [comment]
@sirbrillig for review

**Comment by sirbrillig** [comment]
looks good.

**Comment by kwight** [comment]
This doesn't always redirect as expected, potentially leaving a user in a non-Headstart flow while assigned the `headstart` variation in the test.

**Comment by sirbrillig** [comment]
#3216 should theoretically fix this

**Comment by kwight** [comment]
Will be handled in #3233 after a rebase and #3216 is merged.

**Pull request closed without merging**
