### PR TITLE
Unset font-weight on domains and plans screens

### PR DESCRIPTION
**Pull request by lsl**
Related to https://github.com/Automattic/wp-calypso/pull/97589

## Proposed Changes

* Removes 500 font weight from buttons on the domains and plans steps to match buttons elsewhere across dotcom

## Testing Instructions

| Plans Before | After |
| --- | --- |
| Screenshot 2024-12-19 at 12-40-26 Create a site — WordPress com | Screenshot(189) |

| Domains Before | After |
| --- | --- |
|Screenshot 2024-12-19 at 12-40-17 Create a site — WordPress com | Screenshot(187) |

Also check https://wordpress.com/domains/add/:site and https://wordpress.com/plans/:site screens for regressions.

### CODE REVIEW

**Review by southp — APPROVED** [review]
Works as described and LGTM :) 
I checked the consistency by referring to similar places elsewhere like `/overview`. However, it would be the best if we have a design guideline documentation to refer for cases like this. @lsl Do you know if we have any?

**Review by arthur791004 — APPROVED** [review]
Looks good to me 👍

**Comment by lsl** [comment]
> However, it would be the best if we have a design guideline documentation to refer for cases like this. @lsl Do you know if we have any?

[Dev docs](https://wpcalypso.wordpress.com/devdocs) and the [Gutenberg storybook](https://wordpress.github.io/gutenberg/?path=/docs/components-button--docs#stories) are the reference implementations we should be following in general.

For the plans buttons specifically it's possible they should be `font-weight: 500` as a special case but I'm not really sure. I've merged this as is for now but it's a quick change and can revert the plans button changes later if necessary, deferring to @nuriapenya to make that call.

**Comment by nuriapenya** [comment]
Hey @lsl! Yeah, I agree that consistency across all the buttons is the way to go. LGTM! I will pass this info to the rest of the designers though, to ensure I am not missing some context, but it should be fine.

**Pull request merged**
