### PR TITLE
A4A: Intercept Activity Log links and redirect it to the Preview Pane

### PR DESCRIPTION
**Pull request by cleacos**
Resolve: https://github.com/Automattic/automattic-for-agencies-dev/issues/226

## Proposed Changes

This PR intercepts this route `/activity-log/:site`, and it'll redirect it to `/sites/overview/:site/jetpack_activity`

image

**Important Note:** It's working as expected, it intercepts the link and redirect to the correct route, but because of this known issue [The Scan route to /jetpack_scan/history doesn't work on initial state](https://github.com/Automattic/automattic-for-agencies-dev/issues/227) with the initial state, our code is removing the `jetpack_activity` part.

Once it's resolved, it will work well. 

## Testing Instructions

- Check the code
- Localize a site that has the submenu with the View Activity menu. In trunk, you will get a not found page, in this branch, you will redirected to the route `/sites/overview/:site/jetpack_activity` (you will see it for a second), and then it won't open the correct tab (the known issue that will be addressed in another PR)

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Review by coder-karen — COMMENTED** [review]
For my WordPress.com sites, I'm redirected to `https://wordpress.com/activity-log/siteurl.com` instead. Do we still want that behaviour here?

**Comment by cleacos** [comment]
> For my WordPress.com sites, I'm redirected to https://wordpress.com/activity-log/siteurl.com instead. Do we still want that behaviour here?

I'd say yes, the same thing we have for the Boost column, if you click there for WPCOM sites, it takes you to WPCOM

Does that link to WPCOM work for you?

**Comment by coder-karen** [comment]
> Does that link to WPCOM work for you?

It does. But it takes me to their activity log, and we have one that 'works' for WPcom sites in the preview pane in A4A as well, so we're sending them away from our dashboard when we may not need to. Though the WordPress.com option has a more comprehensive activity log - the actions are all visible and work. For now anyway.

**Comment by cleacos** [comment]
+ It's exactly the same behaviour we have at Jetpack Manage, when we click on that submenu. @coder-karen

**Comment by coder-karen** [comment]
True! But we didn't have a preview pane with Activity log to send them to there, now we have one ready to show in A4A. It almost seems pointless having it if we direct them away, but allow them to view the feed if they open the preview pane. It's slightly confusing, but there must have been a reason we sent them to WordPress.com from the dashboard before instead of allowing them to go to the activity feed in JP Manage, which was somehow hidden for WPcom sites. Maybe we leave it and it's something for a later follow up?

**Review by coder-karen — APPROVED** [review]
This LGTM! Given what we talked about with Activity log paths for WPcom sites, this seems the best option at the moment for those sites to (no change - still going to WPcom).

**Pull request merged**
