### PR TITLE
Golden Token: create constants and a plan description for it

### PR DESCRIPTION
**Pull request by rcanepa**
## Proposed Changes

* Add constants and a plan description to Calypso so the app properly supports the plan. Without this, users won't be able to use either Backup or Scan from Calypso, and some UI will represent the plan incompletely.

## Testing Instructions

**Prerequisites:**
* Create a Jetpack site.
* Provision the site with a Golden Token.

**Instructions:**
* Download this PR.
* Run `yarn start`.
* Visit http://calypso.localhost:3000/backup/[site] and verify you the service is working on your site.
* Visit http://calypso.localhost:3000/scan/[site] and verify you the service is working on your site.
* Visit http://calypso.localhost:3000/activity-log/[site] and verify you can use the Activity Log.
* Vitis http://calypso.localhost:3000/my-plan/[site] and verify you see the correct icon for the plan.

## Demo
**My Plan**
image

**Backup**
image

**Scan**
image

**Plans**
image

**My purchases**
image

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [x] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [x] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

**Comment by mattgawarecki** [comment]
After attaching a Golden Token license to `preliminary-mite.jurassic.ninja`, I looked at all the listed pages using the Calypso Live links in this PR's discussion thread. While the My Plan ~~and Activity Log~~ pages appear to load correctly, I'm still seeing upsell messages for both Backup and Scan. *(UPDATE: Activity Log retention is supposed to be 1 year, not 30 days.)*

image

image image image

Inspecting further by looking at API responses, I see:

- the `/rewind/policies` endpoint returns a 30-day Activity Log retention period and 10GB of Backup storage.

However:

- the `/rewind` endpoint returns a response with `"state": "unavailable"` and `"reason": "missing_plan"`; and
- the `/scan` endpoint returns a response with `"state": "unavailable"` and `"reason": "No site found."`

---

@rcanepa From the evidence I just stated, it seems like maybe there's a disconnect on the server side about the capabilities of sites with a Golden Token. Is there perhaps a code change there I'm not aware of that's necessary for testing?

**Comment by rcanepa** [comment]
@mattgawarecki, I wonder if something was being worked on on the backend side at the time you tested this because I'm not able to replicate the issues you describe. Can I ask you to do a fresh test again? Let me know if you need help with provisioning a Golden Token from MC.

**Comment by mattgawarecki** [comment]
It appears I went through an unsupported flow by directly adding a Golden Token subscription through our internal Store admin panel. Using the MC did the trick, and now everything tests correctly with Backup and Scan.

Though, I still want to note that the `/rewind/policies` endpoint shows me a retention limit of 30 days and a storage limit of 10GB, and it's reflected likewise in the UI. Is this correct?

image

**Review by mattgawarecki — APPROVED** [review]

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/7893065

Thank you @rcanepa for including a screenshot in the description! This is really helpful for our translators.

**Comment by rcanepa** [comment]
> Though, I still want to note that the `/rewind/policies` endpoint shows me a retention limit of 30 days and a storage limit of 10GB, and it's reflected likewise in the UI. Is this correct?

Yes, this is correct. @singerb confirmed this is intentional.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/7893065).

**Pull request merged**
