### PR TITLE
Make the plan selector grid work on mobile devices

### PR DESCRIPTION
**Pull request by roo2**
### Changes proposed in this Pull Request
This supports mobile devices and desktop.
Laptop size is slightly squashed because of the 5 plans now available

* Style changes to support mobile devices

Mobile
Screen Shot 2020-05-11 at 4 01 16 PM

 
Desktop
Screen Shot 2020-05-11 at 4 02 18 PM

Laptop
Screen Shot 2020-05-11 at 4 01 58 PM

#### Testing instructions
* ensure that the `gutenboarding/plans-grid` feature flag is turned on. Currently it is off for staging/prod
* open `/new` 
* In the top right corner of the page click *Free Plan*

### CODE REVIEW

**Comment by roo2** [comment]
I've updated the mobile/tablet design, the horizontal scrollbar stays for ipads as well and then on laptops it is a bit tight but I think acceptable.

**Comment by yansern** [comment]
I've updated this with edge-to-edge panning. 

image

image

**Comment by dubielzyk** [comment]
Can we make the plans width 90% of the viewport width? I'm peaking the next plans 32px into the view to indicate horizontal scrolling.

**Comment by yansern** [comment]
> There's now a grid visible on desktop view too. Let's leave that just for mobile.

Okay done.

**Pull request merged**
