### PR TITLE
Colour Scheming: Try Adding Jetpack Button (WIP) 

### PR DESCRIPTION
**Pull request by torres126**
#### Changes proposed in this Pull Request

See [#30232 (comment)](https://github.com/Automattic/wp-calypso/pull/30232#pullrequestreview-195546327).

#### Testing instructions

WIP, this might not work (in which case I'll probably just end up closing this) but may as well have a go. :) 

(cc @flootr)

### CODE REVIEW

**Comment by simison** [comment]
Feels like `isJetpack` isn't really the type of generic thing that should be in primitive button component. 🤔 

Another way to put it:

How would you implement this if we would import the button component from some UI framework library?

**Comment by drw158** [comment]
Thanks for working on this @torres126. I agree this shouldn't be in the component itself. Could it just be an `is-jetpack` css that we can apply to the button?

**Comment by flootr** [comment]
> Could it just be an is-jetpack css that we can apply to the button?

I think that's the way how it works now but we repeat those stylings (I think it's at least three times) - that's why I suggested centralizing it to reduce the amount of overrides.

**Comment by simison** [comment]
> > Could it just be an is-jetpack css that we can apply to the button?
>
>I think that's the way how it works now but we repeat those stylings (I think it's at least three times) - that's why I suggested centralizing it to reduce the amount of overrides.

Some alternative ideas:

- `JetpackButton` component that has the `Button` component in it
- More generic `JetpackStyles` HOC wrapper component that could be applied to any other component, changing their colours

**Comment by torres126** [comment]
Either way, I think it's worth closing this PR since this approach seems not to be the one being adopted, correct?

**Comment by torres126** [comment]
Closing, feel free to ping if this is the desired approach in the future.

**Pull request closed without merging**
