### PR TITLE
Split `client/lib/analytics/utils` into multiple modules.

### PR DESCRIPTION
**Pull request by sgomes**
Instead of one monolithic file that can't easily be tree-shaken, this change splits `client/lib/analytics/utils` into individual modules.

This will not have any immediate impact (in fact, it slightly increases the overall build size by around 300 bytes [compressed], due to the extra module plumbing needed), but should come into play with e.g. #33642. 

#### Changes proposed in this Pull Request

* Split `client/lib/analytics/utils` into individual modules for each exported unit.

#### Testing instructions

No specific testing instructions. This PR shouldn't change any behaviour, only move some code around. E2E tests should help ensure sanity.

### CODE REVIEW

**Comment by sgomes** [comment]
Rebased on master.

**Comment by sgomes** [comment]
Removed `Needs e2e Testing` flag, as it's causing a lot of false failures.

**Comment by sgomes** [comment]
Rebased on master to pick up changes from #34991.

**Comment by sgomes** [comment]
Hey folks! Any chance of a review? This is a fairly straightforward janitorial PR.

**Review by jsnajdr — APPROVED** [review]
Looks good, thanks for working on this!

**Comment by sgomes** [comment]
Woohoo, thank you for the review, @jsnajdr ! 😄

**Pull request merged**
