### PR TITLE
Onboarding: Remove the onboarding specific check for subheader

### PR DESCRIPTION
**Pull request by spen**
#### Changes proposed in this Pull Request

As a follow up to #33312, this PR removes the extra checks that I put in place to make sure we were in an onboarding flow - the same copy can be used in the same domains step in other flows without issue, so long as we don't bash transfer/mapping check already in place.

This fork in the flow, the "Already own a domain?" is one we should take care to keep in mind - I know I personally wouldn't have checked it if it weren't for spotting it in the code.
We might wish to give segment specific copy here, too.

Related to that - I noticed that the file where the segment specific properties and copy live, `lib/signup/site-type.js` doesn't feel like it's named correctly, given the responsibilities it now has.
When we come to clean up some code, renaming and reorganising this area might be a good candidate for janitorial work :)

#### Testing instructions

Go through the onboarding flow: http://calypso.localhost:3000/start/onboarding
Make sure the right copy is shown on the domains step, as mentioned here: #33312

Then, test the "Already own a domain?" fork by clicking that link... The header/subheader copy should remain as before until you click one of the 2 options... after that you should see copy like so: "'Use a domain you already own with your new WordPress.com site.'"

As you can see, the trouble here is that this copy isn't specific to the flow ("your new WordPress.com blog" would be better fitting.

I'm happy to fix that up as part of this PR - what do you think @fditrapani, @adamziel? Shall I just follow the same pattern? I think it's only the blog segment that would need a copy update here.

### CODE REVIEW

**Comment by ramonjd** [comment]
> Can you create an issue and add it to the backlog of our board?

https://github.com/Automattic/zelda-private/issues/48

**Comment by Stojdza** [comment]
@spen After this PR was merged, e2e test `Sign up for free subdomain site` started to fail. You can find one of the examples [here](https://circleci.com/gh/Automattic/wp-calypso/308473).

Here is the video when I ran test locally:
signup

Usually, the test is starting from url:
_/onboarding/user?vertical=art_ -> _/start/onboarding/site-title_ -> _/start/onboarding/domains_

When it fails, it goes like this:
_/onboarding/user?vertical=art_ -> _/start/**onboarding-blog**/site-title_ and then blue screen appears and nothing happens. I suppose this is not correct flow?

I've temporarily disabled the test https://github.com/Automattic/wp-calypso/pull/33517

**Comment by spen** [comment]
Thanks heaps for the save @Stojdza ! I'm looking in to this now :)

**Comment by Stojdza** [comment]
No problem @spen!

 Would you mind to enable the test along with the fix? Just remove `.skip` from [here](https://github.com/Automattic/wp-calypso/pull/33517/files).

**Comment by spen** [comment]
Sure thing, I'm really confused by this all though, so I'm not sure of the best route. I'm considering just rolling back this PR.

**Comment by ramonjd** [comment]
> Sure thing, I'm really confused by this all though, so I'm not sure of the best route. I'm considering just rolling back this PR.

Hi @spen 

As far as my knowledge goes, I see two options here:

1. If we wish to reinstate the test straight away, then we rename the flow in the e2e test from `onboarding` to `onboarding-for-blog`
2. We wait it out until we have preview working for blog (should be soon) whereby we can rid ourselves of `onboarding-for-blog` altogether and default to `onboarding` for the blog flow. We'll be able to switch the e2e back on without any changes.

**Pull request merged**
