### PR TITLE
A4A: Implement the 'Add site via A4A plugin' modal.

### PR DESCRIPTION
**Pull request by jkguidaven**
This pull request implements the **'Add site via A4A plugin'** modal in the Site selector dropdown menu. **Note: The pull request implements the modal based on the i1 design, which will likely change in i2.**

Screenshot 2024-07-02 at 8 56 39 PM

Closes https://github.com/Automattic/automattic-for-agencies-dev/issues/680

## Proposed Changes

* Implement the `A4AConnectionModal` component.

## Testing Instructions

* Use the A4A live link and go to `/overview` page.
* Click the 'Add site' dropdown menu.
* Click the 'Via A4A' option.
* Confirm the A4A modal appears.
* Confirm the links and copies are correct.

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Review by andrii-lysenko — APPROVED** [review]
Looks great and works as described 👍 

I wonder though if it make sense to rename the `Learn More` link into something else, clarifying that you can download plugin up there yourself...

**Comment by jkguidaven** [comment]
> Looks great and works as described 👍
> 
> I wonder though if it make sense to rename the `Learn More` link into something else, clarifying that you can download plugin up there yourself...

I believe that the **'Learn more'** link is meant to offer more information about the plugin rather than about the downloading process, especially because there is already a direct download link available next to it.

This design will probably change in i2, so we can discuss this further when the design is updated. Thanks for bringing up the question! 👍

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/16012771

Some locales (Hebrew, Japanese) have been temporarily machine-translated due to translator availability. All other translations are usually ready within a few days. Untranslated and machine-translated strings will be sent for translation next Monday and are expected to be completed by the following Friday.

Thank you @jkguidaven for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/16012771).

**Pull request merged**
