### PR TITLE
Updates to make e2e tests more stable

### PR DESCRIPTION
**Pull request by bsessions85**
#### Changes proposed in this Pull Request

* This PR waits for the Nux notice to appear and dismisses it if it does. Before it was checking too quickly and then not dismissing when it showed up. I also added a step to ensure not logged in if the login steps try to retry.  I am hoping this helps with some of the hanging

#### Testing instructions
* Ensure e2e tests pass

### CODE REVIEW

**Comment by Stojdza** [comment]
Looks good and it runs well locally. I also tried several runs on CircleCI to see is there any inconsistency and saw few failures [#](https://circleci.com/gh/Automattic/wp-e2e-tests-for-branches/15984#tests/containers/0) [#](https://circleci.com/gh/Automattic/wp-e2e-tests-for-branches/15988) [#](https://circleci.com/gh/Automattic/wp-e2e-tests-for-branches/15989) Are these same failures related to Gutenberg as before?

**Comment by bsessions85** [comment]
@Stojdza  Yes, they do appear to be the same! I'll dig in some more

**Comment by bsessions85** [comment]
@Stojdza I think I got it this time. There are still some issues with logging in sometimes, but I think the issue with the nux notice being in the way is gone now

**Review by Stojdza — APPROVED** [review]
Looks great, thanks! 👍

**Pull request merged**
