### PR TITLE
Sharing: prevent notice for non-admins

### PR DESCRIPTION
**Pull request by jkudish**
Currently non-admins (specifically authors and editors) receive the following notice when visiting `/sharing`:

screenshot from 2015-12-15 16-11-53

We only need site settings for buttons, not for connections. So this PR seeks to move the call to fetch the site settings to the buttons controller. This prevents the unnecessary notice for non-admins.

cc @aduth for review

### CODE REVIEW

**Comment by aduth** [comment]
The connections page needs to have access to site settings for Eventbrite:

https://github.com/Automattic/wp-calypso/blob/eb9131a3987939fdc87f5abf3d70df3daab477be/client/my-sites/sharing/connections/services/eventbrite.js#L17-L27

I think what we need to do is perform `fetchSettings` and show the Eventbrite connection option only if `site.user_can_manage` is `true`.

**Comment by jkudish** [comment]
Ah good point, missed the EB part of this. Any idea how to make the request without showing the notice and without doing a huge refactor of how the `Site` object currently works.

**Comment by aduth** [comment]
@jkudish - I pushed revisions to exclude the Eventbrite service from the Connections screen if the user cannot manage site settings: 6a09680

**Comment by jkudish** [comment]
Noting that with #1700 applied, I am getting this warning on the post editor as well (with an a user who's an author). That was without this PR applied. Going to check the combination of both shortly.

**Comment by jkudish** [comment]
With this and #1700 both applied, as an `author` on a Jetpack site:

* I can fully manage my connections w/out a notice :+1: :
* I still get a notice in the Post Editor :-1: 

screenshot from 2015-12-16 13-56-17

**Comment by jkudish** [comment]
Testing as an `Editor` on JP Site, I get the following warning in the console:

```
Warning: Failed propType: Invalid prop `label` supplied to `SharingServiceExample`. Check the render method of `SharingServiceExamples`.
```

**Comment by jkudish** [comment]
Testing as a `Contributor` on a JP site. I wouldn't expect the `/sharing` page to load at all, but it does. However, it doesn't appear in the sidebar, and I cannot actually add connections:

screenshot from 2015-12-16 14-03-47

I think we just need to add an error message/block the page from loading services when `! current_user_can( 'publish_posts' )`

**Comment by jkudish** [comment]
As an `Author` on a WP.com site, I still see Eventbrite on the connections page. However, it correctly doesn't let me add the connection:

screenshot from 2015-12-16 14-08-04

Confirming that as an Administrator I can still manage everything as expected, however.

**Comment by aduth** [comment]
>I still get a notice in the Post Editor :-1:

Let's address this separately.

>Testing as an `Editor` on a JP Site, I get the following warning in the console:

This is also true in master, so let's similarly address separately.

>Testing as a `Contributor` on a JP site. I wouldn't expect the `/sharing` page to load at all, but it does. However, it doesn't appear in the sidebar, and I cannot actually add connections:

This is partially covered by #429, but I think we can do a bit more here with the filtering of eligible services since we're already making changes anyways. I'll look to update shortly.

>As an `Author` on a WP.com site, I still see Eventbrite on the connections page. However, it correctly doesn't let me add the connection:

This sounds like a bug. I'll take a look.

**Comment by aduth** [comment]
>As an `Author` on a WP.com site, I still see Eventbrite on the connections page. However, it correctly doesn't let me add the connection:

Can you double-check this? I'm unable to reproduce, and have found sometimes in testing my extra accounts I accidentally test against WordPress.com instead of calypso.localhost .

**Comment by aduth** [comment]
Now hiding Publicize services for contributors in 4ac7b95.

**Comment by aduth** [comment]
Rebased and squashed a few commits. I decided to go ahead and fix #1750 here since it was a very simple fix. See 77cf51a (and [docs on `PropTypes.node`](https://facebook.github.io/react/docs/reusable-components.html#prop-validation)).

**Comment by jkudish** [comment]
Re-tested this PR with the latest code and all the different combinations of WP.com/Jetpack site + different permissions. It now works exactly as expected everywhere. Thanks for pushing through on this.

Reviewed the code too, LGTM :ship: 

I think it'd be good to update the REST API's `/meta/external-services` endpoint to return `required_capability` so that we don't have to hardcode these values in Calypso. Of course, this would be addressed separately.

**Comment by aduth** [comment]
>I think it'd be good to update the REST API's `/meta/external-services` endpoint to return `required_capability` so that we don't have to hardcode these values in Calypso. Of course, this would be addressed separately.

Yeah, that sounds like a good idea.

**Pull request merged**
