### PR TITLE
Advanced SEO: Preview Upgrade Nudge

### PR DESCRIPTION
**Pull request by rodrigoi**
Adds an upgrade nudge on the share preview window.

Test live: https://calypso.live/?branch=add/advanced-seo-nudges

### CODE REVIEW

**Comment by rodrigoi** [comment]
@apeatling @roundhill, let the design review begin!

See it live here: https://calypso.live/?branch=add/advanced-seo-nudges

upgrade nudge

**Comment by roundhill** [comment]
I like how it looks overall, but thinking of a few improvements:

* Add an upgrade button at the top, like we discussed in Slack.
* Maybe we could have a bulleted list of Advanced SEO features, in place of the screenshot or make the screenshot smaller?

The list could be something like:
 * **Custom Meta Descriptions:** Add a custom post description to improve its performance on search engines and social media.
 * **Custom Title Formats:** Help improve your site's search page ranking by customizing how your content's titles appear on your site.
* ** Search and Social Previews: ** Use the preview tool to see how your post will look on search engines and social media.

**Comment by apeatling** [comment]
I think something like this is more informative and sells the feature better, open to other ideas though.

screen shot 2016-08-18 at 11 16 26

**Comment by apeatling** [comment]
Also, we can't use that previews screenshot, it is not current.

**Comment by roundhill** [comment]
> Also, we can't use that previews screenshot, it is not current.

@rodrigoi I'll get you an updated screenshot.

**Comment by roundhill** [comment]
Here's a screenshot:

screen shot 2016-08-18 at 12 51 34 pm

**Comment by roundhill** [comment]
Looking good. Seems like a lot of code for a nudge! But the design is fairly advanced.

**Comment by roundhill** [comment]
:shipit:

**Comment by sendhil** [comment]
@rodrigoi @roundhill I believe this PR is breaking the desktop app:
screen shot 2016-08-31 at 7 22 21 pm

I reverted this PR in the desktop branch(https://github.com/Automattic/wp-calypso/commit/e83958aff54df8ff186bd6f829742ebae654cbbe) and everything seems ok. I'm not entirely sure what in the PR is blowing stuff up as I need to transition to something else but would you mind pushing a fix and pinging me so I can include this with the Desktop version?

**Comment by roundhill** [comment]
Thanks for the heads up @sendhil, we are taking a look.

**Pull request merged**
