### PR TITLE
update pricing page for recommendations

### PR DESCRIPTION
**Pull request by TheSteveK**
#### Proposed Changes

(note this is a buddy session PR for @elliottprogrammer )

* Under certain circumstances, there is a plan recommendation section that previously displayed on the old pricing grid page that should also display on the new pricing page.  See 1202858161751496-as-1203255562458193 
* This PR adds the component to the new pricing page when the URL contains the compare_plans query string is present.
* The component itself will need to be updated in a separate PR to update the offerings it shows

Screen Shot 2022-10-28 at 8 25 15 AM

#### Testing Instructions

* apply the patch and visit the following URL (substitute :site for a valid Jetpack site URL), verify the plan recommendation section shows up.  http://calypso.localhost:3000/plans/:site?compare_plans=jetpack_personal%2Cjetpack_backup_daily%2Cjetpack_anti_spam&view=bundles

#### Pre-merge Checklist

- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?

Related to #

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1203255562458193

### CODE REVIEW

**Comment by manzoorwanijk** [comment]
Testing instructions say, "apply the patch". Which patch to apply? Does it mean to checkout this PR?

**Review by manzoorwanijk — APPROVED** [review]
Works as expected 🚀 

Screenshot 2022-10-31 at 9 55 43 AM

**Comment by elliottprogrammer** [comment]
Re: @manzoorwanijk's comment: 
> Testing instructions say, "apply the patch". Which patch to apply? Does it mean to checkout this PR?

@TheSteveK, Manzoor has a good point here, when creating PR's, Origin team has moved toward doing our best to be very descriptive in our PR descriptions and _especially_ in the  testing instructions, so to make it easy as possible for _anyone_ (non-engineers-> such as Designers, HE's , division stakeholders, or just any non-engineers in general) to be able to test our PR's if possible. I know this can't Always be accomplished 100% of the time, but we still need to try to do the best we can in this respect. This is just **very small nitpick feedback** that I'll explain further and show you some examples in our next onboarding 1:1. 😉 👍

**Comment by TheSteveK** [comment]
Noted, thanks for the feedback.  Coming from my old team we used the phrase apply the patch pretty liberally.  Yes, in this case it means checkout and build this PR.

**Review by elliottprogrammer — APPROVED** [review]
This is functioning well now and looks all good.
LGTM!  Nice work! 👍

**Pull request merged**
