### PR TITLE
Migrate checklist banner styles

### PR DESCRIPTION
**Pull request by blowery**
#### Changes proposed in this Pull Request

* Migrate the checklist banner styles to the new CSS pipeline.
* No visual changes.

#### Testing instructions

* Verify that the checklist banner looks just the same.

### CODE REVIEW

**Review by flootr — COMMENTED** [review]
There seems to be a slight visual difference compared to the current master for the "Completed" label:

master:
Screenshot 2019-04-17 at 09 38 23

this branch:
Screenshot 2019-04-17 at 09 38 41

**Comment by blowery** [comment]
@flootr nice catch! I'll check it out.

**Comment by blowery** [comment]
@flootr this actually seems to reflect the intent of the code... Gauge was migrated to the new CSS pipeline a while ago and started winning the specificity battle as it was now loaded after checklist's overrides. 

@taggon is this how the gauge is supposed to look, with a lowercase metric?

**Comment by blowery** [comment]
Here's the original PR https://github.com/Automattic/wp-calypso/pull/20086

And the metric was indeed lowercase.

Pushed a commit in https://github.com/Automattic/wp-calypso/pull/32334/commits/9701bb3d5d44397cf7add8fd3d1df3faa2ea5b56 to force the specificity win.

**Comment by blowery** [comment]
Throwing a Needs Design Review on this one to help sort out how it _should_ look.

**Comment by shaunandrews** [comment]
Never been a fan of forced uppercase, it breaks the letter-shapes and makes it much harder to read. I'd say move forward with the lowercase.

**Review by shaunandrews — APPROVED** [review]

**Comment by blowery** [comment]
thanks @shaunandrews!

**Pull request merged**
