### PR TITLE
Signup: Refactor signup_domain_origin

### PR DESCRIPTION
**Pull request by sharpirate**
Fixes 113-gh-Automattic/growth-foundations

### Summary
The logic for tracking the domain origin prop for the `calypso_signup_complete` event was implemented in this PR: [Signup: Add Domain Origin Prop to Tracks Event](https://github.com/Automattic/wp-calypso/pull/78085) which wasn't following best code practices because it used `localStorage` for tracking the data. This PR utilizes the dependency store of the signup framework to track that data across the steps.

#### Prerequisites
1. Checkout this branch
2. Run `yarn` and `yarn start`
3. Open [Tracks Vigilante](https://github.com/Automattic/tracks-chrome-extension) so you can monitor tracks events

#### Onboarding Flow
1. Go to http://calypso.localhost:3000/start
1.1. Click on **Choose my domain later** in the sidebar. Continue through the flow until you see the `calypso_signup_complete` event fire in tracks vigilante. Confirm the even has the following property:
`signup_domain_origin: 'choose-later'`
1.2. Click on **Use a domain I own** in the sidebar. Continue through the flow until you see the `calypso_signup_complete` event fire in tracks vigilante. Confirm the even has the following property:
`signup_domain_origin: 'use-your-domain'`
1.3. Select the free .wordpress.com domain. Continue through the flow until you see the `calypso_signup_complete` event fire in tracks vigilante. Confirm the even has the following property:
`signup_domain_origin: 'free'`
1.4. Select the one of the custom suggested domains. Continue through the flow until you see the `calypso_signup_complete` event fire in tracks vigilante. Confirm the even has the following property:
`signup_domain_origin: 'custom'`
1.5. If for some reason the domain origin hasn't been set, the value of the `signup_domain_origin` should be `not-set`

#### Launch Site Flow
1. Go to http://calypso.localhost:3000/start and go through the flow.
2. On the Goals page select **Sell online** so you can get a non-Launchpad enabled site and continue through the flow until you are redirected to `http://calypso.localhost:3000/home/YOUR_SITE`.
3. Go to the settings page `http://calypso.localhost:3000/settings/general/YOUR_SITE` and click on **Launch site**.
4. You will get redirected to `http://calypso.localhost:3000/start/launch-site/domains-launch?siteSlug=YOUR_SITE`.
5. Select a domain from the domain suggestions and confirm you are able to go through the flow and there are no type errors in the console.
6. Upon completing the flow you should see the corresponding `signup_domain_origin` recorded  in Tracks Vigilante

#### With Theme Flow
1. Go to https://wordpress.com/themes while logged out and pick a Premium theme
2. Copy the link of the **Pick this design** button, it should look sth like this `https://wordpress.com/start/with-theme?ref=calypshowcase&theme=luminance&theme_type=free`
3. Manually replace the `https://wordpress.com/` part with `http://calypso.localhost:3000/` and visit the link.
4. Select a domain from the domain suggestions and confirm you are able to go through the flow and there are no type errors in the console.
5. Upon completing the flow you should see the corresponding `signup_domain_origin` recorded  in Tracks Vigilante

#### With Theme Assembler Flow
1. Go to http://calypso.localhost:3000/start/with-theme-assembler
2. Select a domain from the domain suggestions and confirm you are able to go through the flow and there are no type errors in the console.
3. Upon completing the flow you should see the corresponding `signup_domain_origin` recorded  in Tracks Vigilante

#### Domain Only Flow
1. Go to http://calypso.localhost:3000/start/domain
2. Select a domain from the domain suggestions and confirm you are able to go through the flow and there are no type errors in the console.
3. Upon completing the flow you should see the corresponding `signup_domain_origin` recorded  in Tracks Vigilante

#### Mailbox Domain Flow
1. Go to http://calypso.localhost:3000/start/onboarding-with-email
2. Select a domain from the domain suggestions and confirm you are able to go through the flow and there are no type errors in the console.
3. Upon completing the flow you should see the corresponding `signup_domain_origin` recorded  in Tracks Vigilante

### CODE REVIEW

**Comment by ddc22** [comment]
@Sharpirate All of the following steps would break due to the same error of not providing a dependency.
Can you fix them and check any flows that use those steps as well?

image

**Comment by sharpirate** [comment]
Adding @Automattic/martech-decepticons  as reviewers since this is the third attempt at merging this functionality due to unexpected errors on prod we faced before so I would greatly appreciate as many 👀 on this as possible

**Comment by ddc22** [comment]
@niranjan-uma-shankar this change has been a bit tough to merge since we seem to miss critical paths. Could you maybe have a look at testing these changes if time permits?

**Review by ddc22 — COMMENTED** [review]
Thanks for the thorough test plan @Sharpirate it was really helpful!
Everything works well but on the `With Theme Flow` I got `not-set` even when I opted to connect a domain. But everything else works well as explained.

Can you please reach out to one more person directly to get this PR tested and approved so that we can ship with confidence?

**Comment by sharpirate** [comment]
Thanks for taking a look @jdc91!

> Everything works well but on the With Theme Flow I got not-set even when I opted to connect a domain. But everything else works well as explained.

That's weird, on my end the **With Theme Flow** works as expected:

https://github.com/Automattic/wp-calypso/assets/20927667/3544457c-b811-418b-be2f-6bad428a2d7b

Curious to see if anyone else is able to repro the issue when other folks are able to take a look

**Review by ddc22 — APPROVED** [review]
I am going to approve this since I did another run through and everything seem to be working well.
@Sharpirate Once you ping this go back to the thread and just sound of a warning that the change is merged and that you are on alert for any issues. Remember to merge this at your start of the day :)

**Pull request merged**
