### PR TITLE
Plugins: Update the ratings visualization on the cards

### LINKED ISSUE #70906: Plugin Cards: Update the ratings visualization
### Details

Update the rating visualization to match the new design:

Screen Shot 2022-12-07 at 17 25 39

---

P2: pdh6GB-2wk-p2
Figma: f84fqtCG4pCnCh2Hq0But5-fi-1164%3A15550&t=EJIUUCRcliC5mkM0-1the

### Checklist

_No response_

### Related

_No response_

### PR DESCRIPTION
**Pull request by WBerredo**
#### Proposed Changes

Update the ratings display on the Plugins Browser cards.

#### Testing Instructions
* Go to `/plugins`
* Check the ratings on the plugins that contains ratings
* Search for something and check if the .org plugins have ratings

| Before  | After |
| ------------- | ------------- |
|CleanShot 2023-01-20 at 13 07 32@2x|CleanShot 2023-01-20 at 13 12 13@2x|

#### Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

Fixes #70906

### CODE REVIEW

**Review by gavande1 — CHANGES_REQUESTED** [review]
Thank you for working on this. For some cards, it's working perfectly fine. Like the one below.
Screenshot 2023-01-23 at 10 45 18 AM

However, there is a problem with the number formatting on some cards. 

Screenshot 2023-01-23 at 10 40 09 AM

Also, I noticed strange behavior with rating numbers. It gets bigger with each refresh of the page. 

Screenshot 2023-01-23 at 10 40 43 AM
Screenshot 2023-01-23 at 10 41 05 AM

**Review by gcsecsey — CHANGES_REQUESTED** [review]
I've run into the same issue as Rahul, on the featured section, the ratings increase on page load:
CleanShot 2023-01-23 at 12 27 14@2x

However, on the cards where it is working, it looks good to me design-wise:
CleanShot 2023-01-23 at 12 25 55@2x

**Comment by gcsecsey** [comment]
I've done some very similar changes when working on #72441, I think not mapping the ratings here will solve this issue too:
https://github.com/Automattic/wp-calypso/blob/79789bd0474855748ea07a84adfa700e32131d46/client/my-sites/plugins/use-plugins/index.ts#L110-L118

**Comment by WBerredo** [comment]
Thanks for the suggestion @gcsecsey, it worked after removing the mapping.

**Review by gcsecsey — APPROVED** [review]
I've tested the current version again, it works great! The changes also LGTM 🎉

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/7769950

Thank you @WBerredo for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/7769950).

**Pull request merged**
