### PR TITLE
Quick Switch: Remove modal announcement

### LINKED ISSUE #55690: Quick Switch: Remove modal announcement
### Steps to reproduce the behavior

- Go to a Calypso screen that has the Screen Options component rendered on it
- See the Quick Switch announcement modal:

Screen Shot 2021-07-22 at 15 03 00

#### What I expected to happen

No modal should appear, as per p1629828083285000/1629827998.284600-slack-C01VDMPHG69

#### What actually happened

The modal appears.

### Context

p1629828083285000/1629827998.284600-slack-C01VDMPHG69

### PR DESCRIPTION
**Pull request by allilevine**
#### Changes proposed in this Pull Request

* Reverts https://github.com/Automattic/wp-calypso/pull/54687
* Some of the spec files no longer exist.

#### Testing instructions

* Change your `nav-unification-quick-switch-modal` preference to `0` via the staging badge in the bottom right.
* Before applying these changes, check that the quick switch modal appears on a page that can switch, like the Posts page:

Screen Shot 2021-07-22 at 15 03 00

* After applying these changes, check that the modal does not appear.

Fixes https://github.com/Automattic/wp-calypso/issues/55690

### CODE REVIEW

**Comment by allilevine** [comment]
@tjcafferkey @mmtr Please review and merge this revert if everything looks good. See p1629827998284600-slack-C01VDMPHG69 Thanks!

**Comment by worldomonation** [comment]
> Some of the spec files no longer exist.

Yeah, sorry about that - I've deleted most of the specs that were involved in the original PR as they had been migrated to the Playwright E2E suite in subsequent PRs.

**Review by worldomonation — APPROVED** [review]
Looks to be good from the Quality Squad side of things, as long as required tasks pass.

**Comment by tjcafferkey** [comment]
We can also remove the image `client/assets/images/nav-unification-announcement/quick-switch-feature-no-text.png`. May as well remove it's parent directory seeing as it's the only image in there as well.

Other than that, works well for me 👍🏻

**Comment by allilevine** [comment]
> We can also remove the image `client/assets/images/nav-unification-announcement/quick-switch-feature-no-text.png`. May as well remove it's parent directory seeing as it's the only image in there as well.

@tjcafferkey Thanks! I made the change: https://github.com/Automattic/wp-calypso/pull/55692/commits/caa60d5bc4bbd56f77203c9399e0ab5a98c59bce

**Review by tjcafferkey — APPROVED** [review]
LGTM 👍🏻 😄

**Pull request merged**
