### PR TITLE
Store: Remove geo location testing for store nux

### LINKED ISSUE #21300: Store: Turn off Pressable NUX for non-US non-CA stores
i.e. we no longer want the `isCountryAllowed` logic [here](https://github.com/Automattic/wp-calypso/blob/3aa03a378448cd44d8ae28e2bcde7693d92edf00/client/signup/steps/design-type-with-atomic-store/index.jsx#L106)

Requires #21297 to go in first

### PR DESCRIPTION
**Pull request by allendav**
Opens up store NUX flow for all stores regardless of location

Fixes #21300 

To test:
* Open an incognito window to http://calypso.localhost:3000/start
* In What would you like to name your site? enter a name, e.g. allendav201701110908
* Select "Sell products or collect payments" as your only goal
* Hit Continue
* Choose any store theme
* You don't have to continue at this point - you're good to go

### CODE REVIEW

**Comment by allendav** [comment]
@lamosty wrote:

> Is Woo ready for everybody? Are we really doing this? :)

WooCommerce has been multi-country ready longer than we have :P - and yes!

> Should we also update the segmented-store-nux flow? Ie. client/signup/steps/about/index.jsx

How does a user get into that flow?

**Comment by lamosty** [comment]
Cool!

> How does a user get into that flow?

Not sure right now, cc @fditrapani who worked on it.

From me, this is LGTM :shipit:

**Comment by fditrapani** [comment]
> Should we also update the segmented-store-nux flow? Ie. client/signup/steps/about/index.jsx
> How does a user get into that flow?

This is the new first step for our signup flow. It's currently still being translated so it's only showing to English visitors. The translations should be ready within the next week though so we'll be updating all the flows to include this step rather than the design type step.

**Comment by allendav** [comment]
> Should we also update the segmented-store-nux flow? Ie. client/signup/steps/about/index.jsx
How does a user get into that flow?

> This is the new first step for our signup flow. It's currently still being translated so it's only showing to English visitors. The translations should be ready within the next week though so we'll be updating all the flows to include this step rather than the design type step.

OK, I'm going to merge this now then and open a separate issue asap for the segmented-store-nux flow? Ie. client/signup/steps/about/index.jsx

**Comment by fditrapani** [comment]
> OK, I'm going to merge this now then and open a separate issue asap for the segmented-store-nux flow? Ie. client/signup/steps/about/index.jsx

Sounds good, no problem :)

**Pull request merged**
