### PR TITLE
Partner Portal: Update partner portal layout to follow the Pro Dashboard spacing.

### PR DESCRIPTION
**Pull request by jkguidaven**
Jetpack Cloud has some inconsistency in the layout spacing, making the experience a bit disconnected. This is a step to make the Jetpack Cloud experience follow consistent layout spacing.

Related to 1202619025189113-as-1204969880105860

Note that this task is a follow up task to 1202619025189113-as-1204839784815643

## Proposed Changes

The PR updates the Partner portal-related screens to follow the layout spacing used in the Pro Dashboard. I added official layout component for the Partner portal to reduce boilerplate codes and at the same time enforce consistent spacing. 

**Before**
Screen Shot 2023-07-06 at 3 25 10 PM

**After**
Screen Shot 2023-07-06 at 3 25 47 PM

## Testing Instructions

Since these changes are made specifically for agencies, you must set yourself(partner) as an agency - 2c49b-pb. Make sure to switch it back to the previous type.

* Use the Jetpack cloud live link below and test the following screens

| Screen  | URL |
| ------------- | ------------- |
| Billing  | /partner-portal/billing  |
| Issue License  | /partner-portal/issue-license  |
| Assign License  | /partner-portal/assign-license  |
| Payment Methods | /partner-portal/payment-methods |
| Invoices | /partner-portal/invoices |
| Prices | /partner-portal/prices |

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - 0-as-1204969880105860

### CODE REVIEW

**Review by yashwin — COMMENTED** [review]
Thanks for working on this! 

I see some difference in padding between Dashboard & the Licensing pages(except the Licenses page that was changed here - https://github.com/Automattic/wp-calypso/pull/78799)

https://github.com/Automattic/wp-calypso/assets/10586875/eca74307-46b0-443a-bda7-07f4636cdf70

I also notice there is some difference in top padding on smaller screens.


https://github.com/Automattic/wp-calypso/assets/10586875/25f9593b-3134-410d-a114-5048dfebc1f8

**Comment by jkguidaven** [comment]
> Thanks for working on this!
> 
> I see some difference in padding between Dashboard & the Licensing pages(except the Licenses page that was changed here - #78799)
> 
>  Screen.Recording.2023-07-06.at.1.59.45.PM.mov 
> I also notice there is some difference in top padding on smaller screens.
> 
>  Screen.Recording.2023-07-06.at.2.03.20.PM.mov

Good catch. I have fixed the inconsistency on the top margin. I also updated the behavior on the Dashboard's header so it doesn't change padding when on smaller screens.

**Comment by yashwin** [comment]
@jkguidaven Thanks for addressing my comments. However, I still see the first issue reported earlier.

The left padding between Dashboard & the Licensing pages(except the Licenses page that was changed here - https://github.com/Automattic/wp-calypso/pull/78799)

https://github.com/Automattic/wp-calypso/assets/10586875/ee2c4cfe-69ee-4e29-afca-07772ed9b876

**Comment by atanas-dev** [comment]
LGTM in general, but there are 2 pages that I'd argue are better left as they were:
- http://jetpack.cloud.localhost:3000/partner-portal/payment-methods/add
- http://jetpack.cloud.localhost:3000/partner-portal/company-details

Both of these are (unsurprisingly) forms that do not really look good when widened.

Also, is the Licenses page not included because it's still not full width for me:
jetpack cloud localhost_3000_partner-portal_licenses (1)
I see there's a separate patch that was merged - maybe this one needs to be rebased?

**Comment by jkguidaven** [comment]
Thanks for reviewing my PR @yashwin and @atanas-dev.  It turns out the Dashboard has a width limit of 1500px. So my initial full-width solution was a mistake and only worked for some screen sizes.

@atanas-dev, the Licenses page is actually the correct one. Since you are using a wider screen, It did not span to full width, which is the expected behavior.

> 
> but there are 2 pages that I'd argue are better left as they were:
> 
> http://jetpack.cloud.localhost:3000/partner-portal/payment-methods/add
> http://jetpack.cloud.localhost:3000/partner-portal/company-details

Thanks for pointing this out. I see what you mean, and I agree. 👍 


#78799 has the correct spacing, and I have revised my solution and derived it from there. Additionally, I decided to create an official Layout component to reduce some of the boilerplate codes and enforce standard layout spacing.

Can you have another look at my PR? 🙏

**Review by atanas-dev — APPROVED** [review]
LGTM - thanks for cleaning up a bunch of duplicated CSS!

**Review by yashwin — APPROVED** [review]
LGTM now 🚀 Thanks for working on this. Great job, @jkguidaven!

**Pull request merged**
