### PR TITLE
A4A > Agency Tier: Update the no tier and emerging partner UI

### PR DESCRIPTION
**Pull request by yashwin**
Closes https://github.com/Automattic/automattic-for-agencies-dev/issues/1361
Closes https://github.com/Automattic/automattic-for-agencies-dev/issues/1363

## Proposed Changes

This PR updates:

- No tier changes to the overview page and the agency tier page
- Copy changes for emerging partners.

NOTE: Verify all the pages look good on all the screen sizes.

## Testing Instructions

* Remove your agency tier if it is already set from the MC tool > Go to the Overview page using the A4A live link > Verify that the widget is displayed on the top right as shown below:

Screenshot 2024-10-25 at 11 49 14 AM

* Go to the agency tier page > Verify that the badge is displayed for no tier as shown below:

Screenshot 2024-10-25 at 11 52 10 AM

* Update your agency tier to **Emerging Partner** using the MC tool > Verify that the widget on the overview page and the badge on the agency tier page are displayed as shown below:

Screenshot 2024-10-25 at 11 52 59 AM

Screenshot 2024-10-25 at 11 53 07 AM

* Change the agency tier to **Agency Partner** > Refresh the UI and verify that the widget on the overview page and the badge on the agency tier page look good.

* Change the agency tier to **Pro Agency Partner** > Refresh the UI and verify that the widget on the overview page and the badge on the agency tier page look good.

## Pre-merge Checklist

- [x] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [x] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Review by tiagonoronha — APPROVED** [review]
LGTM 👍

**Review by madebynoam — APPROVED** [review]
Looks great, @yashwin!

Can you add text-wrap:pretty to the card text? :) 

image

**Comment by yashwin** [comment]
Thanks for the review, @tiagonoronha & @madebynoam!

> Looks great, @yashwin!
> Can you add text-wrap:pretty to the card text? :)

@madebynoam: I have [fixed](https://github.com/Automattic/wp-calypso/pull/95706/commits/e1806438c9d0eb05b19cc8fe167565846417305d) the runt using the `preventWidows` method we have. The problem with `text-wrap: pretty` is that not all [browsers support](https://developer.mozilla.org/en-US/docs/Web/CSS/text-wrap#browser_compatibility) it.

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/16944874

Some locales (Hebrew, Japanese) have been temporarily machine-translated due to translator availability. All other translations are usually ready within a few days. Untranslated and machine-translated strings will be sent for translation next Monday and are expected to be completed by the following Friday.

Thank you @yashwin for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/16944874).

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/16944874).

**Pull request merged**
