### PR TITLE
Update wpcom.js version

### PR DESCRIPTION
**Pull request by timmyc**
Bumping the `wpcom` version to `4.9.5`

### CODE REVIEW

**Comment by retrofox** [comment]
Testing, testing, testing ...

**Comment by timmyc** [comment]
Thanks @retrofox

**Comment by retrofox** [comment]
LGTM.
Testing the app adding/editing/removing data, login/logout, etc.

**Comment by timmyc** [comment]
More changes coming to wpcom.js, closing this in-lieu of a new PR being created by @retrofox

**Pull request closed without merging**
