### PR TITLE
Login: Update route to use `/me/login`

### PR DESCRIPTION
**Pull request by drewblaisdell**
This is necessary to prevent conflicts with `/login`, which points to the old login page.

**Testing**
- Visit `/`.
- Click the login button.
- Assert that you are taken to `/me/login?redirect_to=…`.
- Assert that you can log in as before.

- [ ] Code
- [ ] Product

### CODE REVIEW

**Comment by stephanethomas** [comment]
I've just fixed the following error that was triggered when starting the server:

```
{
  "formatted": "Error: File to import not found or unreadable: login/wp-login/style\n       Parent style sheet: /var/sources/assets/stylesheets/_components.scss\n        on line 21 of assets/stylesheets/_components.scss\n>> @import 'login/wp-login/style';\n   ^\n",
  "message": "File to import not found or unreadable: login/wp-login/style\nParent style sheet: /var/sources/assets/stylesheets/_components.scss",
  "column": 1,
  "line": 21,
  "file": "/var/sources/assets/stylesheets/_components.scss",
  "status": 1
}
```

**Comment by stephanethomas** [comment]
The code looks good. I'm not convinced that we should move the login code under `/client/me` though. We decided to move the new `Login` page to https://wordpress.com/me/login instead of https://wordpress.com/login to avoid making a system request, and to be able to run both the old and the new `Login` pages side by side. From my understanding, we will remove the former at some point, and move the latter back to https://wordpress.com/login.

**Comment by stephanethomas** [comment]
The `Login` page is no longer rendered server-side, something that you can check with Javascript disabled:

screenshot

**Comment by gziolo** [comment]
Let me fix SSR :)

**Comment by stephanethomas** [comment]
I've added a commit that fix server-side rendering. This is good for review.

**Comment by stephanethomas** [comment]
I just spotted another problem. If you start from http://calypso.localhost:3000/ (which will redirect you to http://calypso.localhost:3000/devdocs/start) or http://calypso.localhost:3000/start and click the `Log In` link in the top bar you are redirected on the new `Login` page. However, it's possible to still see part of the content of the previous page at the bottom:

screenshot

**Comment by gziolo** [comment]
Let's close it and open another PR with `/log-in` as discussed on Slack to avoid more hidden 🐛  :)

**Pull request closed without merging**
