### PR TITLE
wp-admin Command Palette: Add "Send feedback" command

### LINKED ISSUE #87940: wp-admin Command Palette: "Send feedback"
Follow-up of https://github.com/Automattic/wp-calypso/pull/87901.

The ["Send feedback" command ](https://github.com/Automattic/wp-calypso/blob/48bbe440e5bb7a6411c78ced61e82032e45a96a7/client/sites-dashboard/components/wpcom-smp-commands.tsx#L1318-L1326)is missing in WP Admin.

### PR DESCRIPTION
**Pull request by mmtr**
Fixes https://github.com/Automattic/wp-calypso/issues/87940

## Proposed Changes

Adds the "Send feedback" command to the wp-admin command palette.

Screenshot 2024-02-28 at 17 37 23

## Testing Instructions

- Apply the latest version of https://github.com/Automattic/jetpack/pull/35635 to your test site
- Run `install-plugin.sh command-palette add/command-palette-wp-admin-send-feedback` in your sandbox
- Sandbox `widgets.wp.com`
- Visit the WP Admin of your test site
- Open the command palette
- Search the "Send feedback" command
- Make sure it shows up
- Execute it
- Make sure it opens the contact form of the help center

### CODE REVIEW

**Review by dsas — APPROVED** [review]
WFM. Unit test failure looks unrelated.

**Comment by mmtr** [comment]
> Unit test failure looks unrelated.

Was actually related! I think I fixed it on my last commit

**Comment by rcrdortiz** [comment]
I thought this had to be done using the `@automattic/help-center` package for some reason. Good to know it isn't the case.

**Comment by mmtr** [comment]
> I thought this had to be done using the `@automattic/help-center` package for some reason. 

That would have been preferable, to be honest.

I looked into what's available in that package to see if there was any way to globally manipulate the internal state of the help center, but there isn't. It just exports the mechanisms needed to create a help center instance, but once you do that, there is no way to interact with its internal state from outside.

**Pull request merged**
