### PR TITLE
Sites Dashboard: update the results number on each tab

### LINKED ISSUE #65169: Sites Management Dashboard: add search and tab filtering of the sites list
Depends on: https://github.com/Automattic/wp-calypso/issues/65166

Implement the Search functionality and Tab filtering for the sites list.

Screenshot 2022-07-02 at 00 04 01

Done is:
- [x] Search component is added to the page.
- [x] Inputting text in it filters the site list based on the site titles and domains.
- [x] Clicking on tabs filter the list based on the site status (launching, private, coming soon).
- [x] The implementation relies on core components where possible or introduces the new ones in Calypso `/packages/components`.

Open question:
- should the site count in tabs be updated to reflect the number of search results in each category?

### PR DESCRIPTION
**Pull request by sejas**
#### Proposed Changes

* After searching, update the number inside the tabs badge.

We need to filter all sites with the text query and then split the sites into the different statuses.

#### Testing Instructions

* Go to /sites-dashboard
* Insert a text to search
* Observe the number is correctly updated in each tab.

#### Screencast

https://user-images.githubusercontent.com/779993/180218027-7faa48c7-ed48-437f-9c17-4d2570fc1ae2.mp4

#### Pre-merge Checklist

- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [x] Have you tested the feature in [Simple](P9HQHe-k8-p2-p2), [Atomic](P9HQHe-jW-p2-p2), and [self-hosted Jetpack sites](PCYsg-g6b-p2-p2)?
- [x] Have you checked for TypeScript, React or other console errors?
- [x] Are we memoizing when appropriate (for expensive computations)? More info in [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md) and [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors)
- [ ] Have we sent any new strings [for translation](PCYsg-1vr-p2-p2) ASAP?

Solves #65606

Closes https://github.com/Automattic/wp-calypso/issues/65169.

### CODE REVIEW

**Comment by zaguiini** [comment]
That works. However, that brings me a design question: does it make sense to show all results, regardless of the active tab?

What I'm trying to convey here:

Say the user is browsing the `Coming Soon` tab and enters a search query. They think that the site they're looking for is listed as coming soon, but it's actually private. Right now, they'll need to move their mouse over the tab and click it so they can see the site they're looking after.

For me, that's not ideal. It's slow as you'll need to put your hands on the mouse, move it to the tab and then click to see a site. Searching should be quick. How about we approach this differently:

When there is a search query, hide or fade out the tabs (that's optional) and display several tables with the category (private, coming soon) as a heading so they could see all sites for that query in the same view?

Something like that:

image

**Comment by sejas** [comment]
Very interesting approach. Looking forward to seeing different opinions.
I prefer how it's working now. From my point of view, the user will search in the `All` tab in most cases, and all the results will appear there.
With the current solution, the user could narrow the search by filtering by one specific state.
We could change the copy when the user is in a different tab, and there are no results.

**Review by danielbachhuber — APPROVED** [review]
👍 I think what you've implemented is a positive addition to the code base.

Looks like there might be a CI failure to fix before merging...

**Review by zaguiini — APPROVED** [review]
This is a good step forward, even if we decide to change it in the future. Approved 👍

**Review by wojtekn — APPROVED** [review]

**Comment by sejas** [comment]
Merging and deploying this PR until we have a different direction. p1658412546182749-slack-C0347E545HR

**Pull request merged**
