### PR TITLE
 MiniSitePreview:  Style improvements

### PR DESCRIPTION
**Pull request by spen**
This PR seeks to re-apply the improvements originally made in https://github.com/Automattic/wp-calypso/pull/26866/commits/48d1e796ab3a51affaad25082d355e5e740b19ec as well as making sure that the overlay fade doesn't extend out of the site preview component.

I had to revert this commits parent PR, as I had accidentally left in another commit that was no longer appropriate.

#### Testing the `width` rule
Everything should look as before in http://calypso.localhost:3000/settings/import > site-importer.
You can check that the style is still applied as expected by inspecting the mini-site-preview element directly.

#### Testing the overlay
Inspect element on the site preview - look for the `:after` in the `mini-site-preview__image` div.
Where as before it overflowed, it should now be properly contained.

### CODE REVIEW

**Comment by andfinally** [comment]
I'm finding the overlay is 1px too short, for some reason, so a sliver of the pic underneath shows through - see the blue line at the bottom here. It's fixed when I set the bottom of the `::after` element to `bottom: -1px`. Maybe the gradient isn't starting right at the bottom?

image

**Comment by spen** [comment]
Interestingly, I already have a fix for this 😄It's just not in this change-set...
The solution is pretty much exactly as you mention too - `bottom: -1px;` with `overflow: hidden` on the parent :)

I'll add it here now as we'll benefit from it outside of the feature I'm currently working on.

**Comment by spen** [comment]
> I'm finding the overlay is 1px too short

This should be covered (heh) in https://github.com/Automattic/wp-calypso/pull/27243/commits/d05e482834a12188c8d34c10d2207f4f0daff18f

**Comment by andfinally** [comment]
Actually... that `-1px`'s bugging me a bit. It seems this is a [Chrome bug](https://stackoverflow.com/a/43675915/678834), and you can get around it by adding `no-repeat` to the background rule. I wonder if that would be a cleaner fix.

**Comment by spen** [comment]
Good find! I've added that and rebased it in. I kept the overflow rule as it still makes sense and makes sure the border still shows at the bottom. Thanks for the suggestion :)

**Comment by andfinally** [comment]
Smashing! LGTM!

**Pull request merged**
