### PR TITLE
Checkout: Thank you: Change directory names of header and footer

### PR DESCRIPTION
**Pull request by scruffian**
Rename the header and footer directories to adhere to the component naming guidelines.

This was raised by @mtias in https://github.com/Automattic/wp-calypso/pull/3606#discussion_r54288997.

FWIW, I think this demonstrates a short-coming in the component naming guidelines, since these directory names are a bit verbose. The alternative is to create these as a subcomponents, but this would make the `style.scss` file long.

An alternative could be to put the subcomponent CSS in a different file, named according to the subcomponent file name (e.g. footer.scss, header.scss).

Thoughts?

### CODE REVIEW

**Comment by stephanethomas** [comment]
You forgot to update the `_components.scss` file ;).

**Comment by mtias** [comment]
@scruffian I am not entirely aware of the nature of the thank you component, but from what I see it doesn't seem like you'd be reusing `checkout-thank-you-footer` anywhere else so it should probably just be a subcomponent like `checkout-thank-you/footer.jsx`.

I don't think `style.scss` would be too long if you do that, specially as it gets cleaned up further (like <a href="https://github.com/Automattic/wp-calypso/blob/master/client/my-sites/upgrades/checkout-thank-you/style.scss#L100-L150">moving all this to gridicons</a>).

**Comment by stephanethomas** [comment]
Class names should be updated in [`footer.jsx`](https://github.com/Automattic/wp-calypso/blob/fix/director-names-in-checkout-thank-you/client/my-sites/upgrades/checkout-thank-you/footer.jsx#L52) as well.

**Comment by drewblaisdell** [comment]
This looks good to me. I agree that `style.scss` is not too long, and I'm not even sure that the length of that file is pertinent if we alphabetize the selectors - this way, subcomponent classes will always be grouped together.

**Comment by drewblaisdell** [comment]
There are no visual changes here, and I tested to make sure that this doesn't change checkout. This is ready to merge now.

**Pull request merged**
