### PR TITLE
Bump WordPress.com Editing Toolkit plugin to v2.4

### PR DESCRIPTION
**Pull request by p-jackson**
#### Changes included in this release

* https://github.com/Automattic/wp-calypso/pull/45492 (added to notes)
* https://github.com/Automattic/wp-calypso/pull/45499 (added to notes)
* https://github.com/Automattic/wp-calypso/pull/45571
* https://github.com/Automattic/wp-calypso/pull/45604
* https://github.com/Automattic/wp-calypso/pull/45651
* https://github.com/Automattic/wp-calypso/pull/45634
* https://github.com/Automattic/wp-calypso/pull/45682 (added to notes)
* https://github.com/Automattic/wp-calypso/pull/45656 (added to notes)

#### Testing instructions

* Apply generated diff to sandbox
* Test changes listed in release notes are present
* Install build on an atomic site
* Test that editor works on atomic with and without gutenberg plugin enabled

### CODE REVIEW

**Review by alshakero — APPROVED** [review]
Reviewed and tested. LGTM!

**Comment by apeatling** [comment]
@p-jackson Is it possible to include this small change in the release also? https://github.com/Automattic/wp-calypso/pull/45682

**Comment by p-jackson** [comment]
> @p-jackson Is it possible to include this small change in the release also? #45682

No problem rebasing now!

**Comment by apeatling** [comment]
@p-jackson I've spotted an error with the patterns tab in the main inserter, it appears to be blank. :/

**Comment by p-jackson** [comment]
Hmmm didn't notice that myself. I'll retest once the patch updates.

**Comment by apeatling** [comment]
@p-jackson False alarm, it's related to a Gutenberg branch I was using, not these changes. :+1:

**Comment by p-jackson** [comment]
The sass build is broken, looks like build error was introduced by #45490. Fix here: #45688

**Pull request merged**
