### PR TITLE
DevDocs: Display the README.md below the component

### PR DESCRIPTION
**Pull request by samouri**
A continuation of an unmerged OSS contribution: https://github.com/Automattic/wp-calypso/pull/16778.

Hopefully can get this over the finish line if I didn't butcher the merge conflicts too bad.

### CODE REVIEW

**Comment by samouri** [comment]
I've fixed all the merge conflicts.
@folletto: could I trouble you to give the functionality a once-over?

If everything looks good I'll aim to merge midweek

**Comment by bluefuton** [comment]
Props to @caydijay for the original PR 👍

**Comment by folletto** [comment]
Ok I tested opening a couple of components in DevDocs and checked the readme was at the bottom correctly, and the block folded.

Design wise 👍 

Can I however suggest a small change in the foldable block part? Having "Readme.md" always visible, and to the left:

screen shot 2017-12-18 at 20 54 21

screen shot 2017-12-18 at 20 54 29

Thanks!

**Comment by samouri** [comment]
@folletto: good idea! the default styling is a bit bigger than the mock you made:
 
screen shot 2017-12-18 at 3 17 02 pm


I'll ship this all tomorrow

**Comment by folletto** [comment]
Yeh sorry, I forgot to specify: it was `14px` and `$gray-text-min`!

**Comment by samouri** [comment]
Thanks for the details! I'll add it to the css ❤️

**Comment by samouri** [comment]
I'm currently having trouble clicking into components from within the devdocs. it somehow ends up redirecting to themes pages.  I've only been able to repro in development mode.

I have a feeling this is broken on master.  researching...

**Pull request merged**
