### PR TITLE
Build: Turn on mangling with Uglify, Take 2

### PR DESCRIPTION
**Pull request by blowery**
Reverts Automattic/wp-calypso#11005

Attempt number two at turning mangling on. The first try didn't seem to result in mangled variable names in production. Further investigation required.

Originally https://github.com/Automattic/wp-calypso/pull/10978

The alternative is https://github.com/Automattic/wp-calypso/pull/10634

----

This turns on uglify's mangling, which can significantly reduce bundle sizes.

To test, spin up a docker instance with a production install and use Calypso.

```
docker build -t wp-calypso .
# go get a coffee. yikes.
sudo vim /etc/hosts # add an entry for 127.0.0.1 wpcalypso.wordpress.com
docker run -it --name wp-calypso --rm -p 80:3000 -e NODE_ENV='production' -e CALYPSO_ENV='wpcalypso' wp-calypso
open http://wpcalypso.wordpress.com
verify that the JS bundles have been mangled. 
  - function parameters should be single characters.
  - nested function should have very short names
```

You'll need to make sure you're not proxying to hit the pretend wpcalypso.wordpress.com

Size changes:
```
130K accept-invite.js						130K accept-invite.js
102K accept-invite.min.js				      |	66K accept-invite.min.js
241K account.js							241K account.js
179K account.min.js					      |	114K account.min.js
67K ads.js							67K ads.js
51K ads.min.js						      |	36K ads.min.js
236K async-load-components-post-schedule.js			236K async-load-components-post-schedule.js
159K async-load-components-post-schedule.min.js		      |	103K async-load-components-post-schedule.min.js
187K async-load-featured-image.js				187K async-load-featured-image.js
122K async-load-featured-image.min.js			      |	74K async-load-featured-image.min.js
87K async-load-my-sites-drafts-draft-list.js			87K async-load-my-sites-drafts-draft-list.js
60K async-load-my-sites-drafts-draft-list.min.js	      |	35K async-load-my-sites-drafts-draft-list.min.js
12K async-load-post-editor-drafts-button.js			12K async-load-post-editor-drafts-button.js
7K async-load-post-editor-drafts-button.min.js		      |	3K async-load-post-editor-drafts-button.min.js
126K async-load-post-editor-editor-author.js			126K async-load-post-editor-editor-author.js
88K async-load-post-editor-editor-author.min.js		      |	51K async-load-post-editor-editor-author.min.js
66K async-load-post-editor-editor-discussion.js			66K async-load-post-editor-editor-discussion.js
45K async-load-post-editor-editor-discussion.min.js	      |	24K async-load-post-editor-editor-discussion.min.js
75K async-load-post-editor-editor-location.js			75K async-load-post-editor-editor-location.js
51K async-load-post-editor-editor-location.min.js	      |	28K async-load-post-editor-editor-location.min.js
74K async-load-post-editor-editor-post-formats-accordion.js	74K async-load-post-editor-editor-post-formats-accordion.js
51K async-load-post-editor-editor-post-formats-accordion.min. |	26K async-load-post-editor-editor-post-formats-accordion.min.
70K async-load-post-editor-editor-seo-accordion.js		70K async-load-post-editor-editor-seo-accordion.js
48K async-load-post-editor-editor-seo-accordion.min.js	      |	25K async-load-post-editor-editor-seo-accordion.min.js
113K async-load-post-editor-editor-sharing-accordion.js		113K async-load-post-editor-editor-sharing-accordion.js
80K async-load-post-editor-editor-sharing-accordion.min.js    |	45K async-load-post-editor-editor-sharing-accordion.min.js
572K async-load-post-editor-media-modal.js			572K async-load-post-editor-media-modal.js
394K async-load-post-editor-media-modal.min.js		      |	245K async-load-post-editor-media-modal.min.js
3M build-production.js						3M build-production.js
2M build-production.min.js				      |	1M build-production.min.js
717K commons.js							717K commons.js
525K commons.min.js					      |	309K commons.min.js
49K customize.js						49K customize.js
32K customize.min.js					      |	20K customize.min.js
3K discover.js							3K discover.js
2K discover.min.js					      |	1K discover.min.js
168K happychat.js						168K happychat.js
129K happychat.min.js					      |	84K happychat.min.js
308K help.js							308K help.js
235K help.min.js					      |	150K help.min.js
11K mailing-lists.js						11K mailing-lists.js
8K mailing-lists.min.js					      |	5K mailing-lists.min.js
8K manifest.js							8K manifest.js
6K manifest.min.js					      |	5K manifest.min.js
166K me.js							166K me.js
127K me.min.js						      |	83K me.min.js
277K media.js							277K media.js
205K media.min.js					      |	129K media.min.js
363K menus.js							363K menus.js
240K menus.min.js					      |	149K menus.min.js
277K notification-settings.js					277K notification-settings.js
215K notification-settings.min.js			      |	146K notification-settings.min.js
3K paladin.js							3K paladin.js
2K paladin.min.js					      |	1K paladin.min.js
230K people.js							230K people.js
181K people.min.js					      |	113K people.min.js
256K plans.js							256K plans.js
198K plans.min.js					      |	122K plans.min.js
649K plugins.js							649K plugins.js
495K plugins.min.js					      |	342K plugins.min.js
2M post-editor.js						2M post-editor.js
1M post-editor.min.js						1M post-editor.min.js
182K posts-custom.js						182K posts-custom.js
124K posts-custom.min.js				      |	68K posts-custom.min.js
374K posts-pages.js						374K posts-pages.js
266K posts-pages.min.js					      |	166K posts-pages.min.js
448K purchases.js						448K purchases.js
352K purchases.min.js					      |	226K purchases.min.js
5K reader-activities.js						5K reader-activities.js
4K reader-activities.min.js				      |	2K reader-activities.min.js
100K reader-following.js					100K reader-following.js
75K reader-following.min.js				      |	48K reader-following.min.js
18K reader-list.js						18K reader-list.js
15K reader-list.min.js					      |	9K reader-list.min.js
26K reader-post-recomendations.js				26K reader-post-recomendations.js
21K reader-post-recomendations.min.js			      |	12K reader-post-recomendations.min.js
21K reader-search.js						21K reader-search.js
16K reader-search.min.js				      |	9K reader-search.min.js
187K reader-start.js						187K reader-start.js
103K reader-start.min.js				      |	63K reader-start.min.js
229K reader-tags.js						229K reader-tags.js
149K reader-tags.min.js					      |	139K reader-tags.min.js
174K reader.js							174K reader.js
125K reader.min.js					      |	78K reader.min.js
450K security.js						450K security.js
338K security.min.js					      |	237K security.min.js
503K settings-seo.js						503K settings-seo.js
277K settings-seo.min.js				      |	154K settings-seo.min.js
846K settings.js						846K settings.js
620K settings.min.js					      |	371K settings.min.js
244K sharing.js							244K sharing.js
177K sharing.min.js					      |	116K sharing.min.js
679K signup.js							679K signup.js
540K signup.min.js					      |	359K signup.min.js
468K stats.js							468K stats.js
345K stats.min.js					      |	213K stats.min.js
154K theme.js							154K theme.js
110K theme.min.js					      |	66K theme.min.js
278K themes.js							278K themes.js
208K themes.min.js					      |	124K themes.min.js
1M upgrades.js							1M upgrades.js
844K upgrades.min.js					      |	570K upgrades.min.js
1M vendor.production.js						1M vendor.production.js
985K vendor.production.min.js				      |	641K vendor.production.min.js
```

### CODE REVIEW

**Comment by blowery** [comment]
The problem we had with the first go round was that the hashes didn't change between the unminified build and the minified build. This was because webpack is generating the hashes and has no idea that the minification is happening after the chunks are generated.

To fix this short term, I changed the minified suffix to `.m` instead of `.min` to cache bust the URL.

**Comment by samouri** [comment]
> To fix this short term, I changed the minified suffix to .m instead of .min to cache bust the URL.

whats long term?

**Comment by blowery** [comment]
> whats long term?

Teaching Webpack to minify things, which would let the hash change. But it means getting rid of the .min / .m files altogether.

See https://github.com/Automattic/wp-calypso/pull/10634

**Comment by gwwar** [comment]
Verified that there are short names in the .m files. I am seeing the following errors while clicking around:

screen shot 2017-01-27 at 2 54 00 pm

Also have we checked if this works with the Desktop build?

**Comment by blowery** [comment]
Poking at it @gwwar. Excellent catch!

**Comment by blowery** [comment]
Hmmmm. 

I can't repro that @gwwar. What steps did you take? 

I cleared cache and hard reloaded `/` to get the Reader, then went through My Sites, all items in the sidebar, all items in Settings, opened the editor, expanded all sidebar items, opened Me, clicked through all sidebar items. 

Just did it all again starting at the stats landing page. 

I have not checked to see how this affects the desktop build.

**Comment by blowery** [comment]
Checked the Desktop build. Have to update a couple spots in the Makefile to reflect the new filenames, but works otherwise.

**Comment by gwwar** [comment]
I cleared out my old images and retested. Seems like I can't repro anymore. Were you planning on fixing Desktop in the PR or a follow up?

**Comment by blowery** [comment]
@gwwar Thanks for checking it out!. The desktop fix has to be a follow up, as it's the Desktop `makefile` that has to be updated.

**Comment by gwwar** [comment]
👍 Feel free to 🚢 then, but let's follow up quickly on the Desktop repo.

**Pull request merged**
