### PR TITLE
Desktop App: Update app icons

### LINKED ISSUE #92825: Desktop App: Update app icon
From: p58i-hGx-p2

### Details

The app icon used for the WordPress.com desktop app is outdated. These should be updated to use out latest brand language.

**Current icons**

| Mac | Linux | Windows |
|--------|--------|--------|
| image | image | icon | 

### Checklist

- [x] Mac app icon updated.
- [x] Windows app icon updated.
- [x] Linux app icon updated.

### Related

_No response_

### PR DESCRIPTION
**Pull request by matt-west**
Fixes #92825

## Proposed Changes

* Update the Windows, Linux, and MacOS app icons

### MacOS
| Before | After |
|--------|--------|
| image | image |

### Windows
| Before | After |
|--------|--------|
| image | image |

### Linux
| Before | After |
|--------|--------|
| image | image |

## Why are these changes being made?

* To bring the icons inline with the latest WordPress.com branding.

## Testing Instructions

* From the `desktop` directory, run `yarn run build-desktop`
* Go to the `desktop/release` folder and check that the built app files use the correct icons.

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Comment by matt-west** [comment]
@wojtekn Would you be able to help test this change? I don't have access to a Windows or Linux machine.

**Comment by wojtekn** [comment]
@matt-west it works well for me on macOS. I'm checking how can I get Windows binary built to test it there.

@kozer would you mind testing it on Linux?

**Review by wojtekn — APPROVED** [review]

**Review by kozer — APPROVED** [review]
Tested it and works as expected
2024-07-22T13:32:37,071750141+03:00

**Comment by matt-west** [comment]
@wojtekn @kozer Thanks for reviewing!

**Comment by wojtekn** [comment]
It looks as expected in the window title and the taskbar:

Zrzut ekranu 2024-07-22 131949
Zrzut ekranu 2024-07-22 132001

It seems to use negative colors in system tray:

Zrzut ekranu 2024-07-22 132607

**Comment by matt-west** [comment]
> It seems to use negative colors in system tray

Thanks! I'll update those icons too.

**Comment by matt-west** [comment]
@wojtekn Can you please test the tray icons again. I’ve updated the existing icons and added support for Windows 11.

**Comment by wojtekn** [comment]
@matt-west it's fixed now:

Zrzut ekranu 2024-07-30 092717

**Comment by wojtekn** [comment]
I'm merging those changes despite the falling Linux builds. The failure is unrelated to this issue as it fails on yarn install.

**Pull request merged**
