### PR TITLE
Components: Remove loading.gif in favor of Spinner component

### PR DESCRIPTION
**Pull request by aduth**
This pull request seeks to remove all remaining references of `loading.gif` from Calypso:

There were only two remaining usages, which have been updated to use the [`<Spinner /> component`](https://github.com/Automattic/wp-calypso/tree/master/client/components/spinner) instead.

Changes also include some refactoring to `<Spinner />`, particularly to ensure that it's rendered as a pure component, which may improve performance slightly (particularly for media uploading where many spinners may exist simultaneously).

__Testing instructions:__

Verify that there are no regressions in display of loading indicator for affected stats placeholders and Customize loading indicator.

1. Navigate to [Stats insights](http://calypso.localhost:3000/stats/insights)
2. Select a site, if prompted
3. Note that under "Latest Post Summary", while post is loading, a centered spinner is shown
4. Click Customize in the sidebar
5. Note that the "Loading customizer" text includes a centered spinner above

/cc @timmyc re: removed `is-spinner` class selector in stats styles (couldn't find any references to justify distinction between `is-spinner` and `is-void`).

Test live: https://calypso.live/?branch=remove/spinner-gif

### CODE REVIEW

**Comment by timmyc** [comment]
Code looks good and tests out well.  FWIW the loading indicator is used throughout all stats modules.

LGTM but hoping @jancavan or another designer can take a look and give it the final design OK

**Comment by jancavan** [comment]
Is the new spinner supposed to look like this?

screenshot 2016-06-24 15 47 39

**Comment by aduth** [comment]
@jancavan Yep, that's the one. We can adjust the size if desired.

**Comment by jancavan** [comment]
Looks good on their other cards, but it's not centered on the graph card:

screenshot 2016-06-27 10 46 50

**Comment by aduth** [comment]
Nice catch @jancavan . Looks like it was the float in the legend that was causing the placeholder to take up less space (perhaps in issue in master too?). Adding a `clear: both;` to the `stats-module__placeholder` class seems to fix it up.

image

**Pull request merged**
