### PR TITLE
Update/remove sitelist usage from checkout

### PR DESCRIPTION
**Pull request by spen**
#### note:
Reapplying changes made in #9429. #9429 was reverted after some build issues with another PR that was landed shortly before (see [this comment](https://github.com/Automattic/wp-calypso/pull/9429#issuecomment-264275996) for more detail).

## Aims
As part of #8726, this PR removes reference to 'lib/sites-list' from the upgrades/checkout component.

## Test Plan

- Navigate to [plans](http://calypso.localhost:3000/plans) and select a site.
- Choose an upgrade... this should take you to the checkout page.
- Check that this page has not changed functionally.
    - it should be visually identical before & after this patch

cc: @gwwar

### CODE REVIEW

**Comment by spen** [comment]
Unfortunately I'm struggling to find the cause of the CircleCI failure :/
https://circleci.com/gh/Automattic/wp-calypso/31538#tests/containers/1 doesn't seem to give much of use, at least not that I can see or understand :(
Tests all pass on my machine ( apart from the one I've addressed @ #8462 ).
I'm stumped and would really appreciate some pointers on how to fix this!

**Comment by gwwar** [comment]
I think the build was killed earlier, rerunning it looks fine.

**Comment by gwwar** [comment]
Thanks @spen  I'll try to land this next week

**Comment by spen** [comment]
Thanks @gwwar glad the CircleCI ran clean after all :D had me worried!

**Comment by gwwar** [comment]
Alright retested with a local branch rebased with master. 👍 Going to try landing this again.

**Comment by spen** [comment]
Awesome thanks heaps @gwwar :D
I'm going to jump on another from #8726 after checking up on the current state of my other open PRs. Let me know if any of them are of higher priority, otherwise I'll pick up one at random :)

**Pull request merged**
