### PR TITLE
Use shared duration translation

### PR DESCRIPTION
**Pull request by sirreal**
Use shared duration translations introduced in #25987

One translation covers them all!

cc: @taggon @ockham 

## Testing

Open the Store checklist and verify that the durations are displayed correctly.

### CODE REVIEW

**Comment by sirreal** [comment]
I'm confused by the [string freeze report](https://translate.wordpress.com/localci/status/automattic/wp-calypso/update/checklist-woo-translations). @Automattic/i18n is this normal?

The strings that are actually updated in this PR are already translated.

Untouched strings from files in this PR appear as new and untranslated strings.

This should be fine to merge before the rest of the strings are translated because that's how production is currently.

**Comment by ramonjd** [comment]
> Untouched strings from files in this PR appear as new and untranslated strings.

I'm going to go out on the proverbial limb, and claim that it's an unintended consequence of adding the [previous line](https://github.com/Automattic/gp-localci-client/blob/master/generate-new-strings-pot.sh#L101) to the change list.

So [this command](https://github.com/Automattic/gp-localci-client/blob/master/generate-new-strings-pot.sh#L96) fetches the following line numbers: `92, 104, 116, 128, 142`, which looks legit according to this PR's diff.

But when we _"Also add previous line, for cases where 'translate' is on one line, and the actual string on the next"_, the previous lines – `91, 103, 115, 127` – come for free!

https://99604-45936895-gh.circle-artifacts.com/5/tmp/artifacts/translate/localci-new-strings.pot

@akirk to confirm... :)

**Comment by sirreal** [comment]
Thanks @ramonjd, that helps to understand why they're being flagged as new. I'd also like to understand why they're untranslated. They appear to have been in production for [4 months or more](https://github.com/Automattic/wp-calypso/commit/588594e30b7e4cad7387b77910d50d7a5780b9de). Is that common and expected?

**Comment by deBhal** [comment]
>  I'd also like to understand why they're untranslated. They appear to have been in production for 4 months or more.

Yes, this is expected - We don't include extensions in the weekly kit, at least not yet. See https://github.com/Automattic/wp-calypso/issues/12935 ( Your use of string freeze here seems like a strong vote for changing that :) ).

Extension strings usually end up in separate projects ( https://translate.wordpress.com/projects/wpcom/calypso-extensions/woocommerce/ ), and it looks like `localci` is not aware of that, which is what made the warnings so confusing - we've had the strings in the `wpcom/calypso-extensions/woocommerce` project for months, but `localci` has only just added them to the `wpcom` project because it saw them in the diff.

**Comment by sirreal** [comment]
Thanks for helping me understand what's happening with translations here, everyone 🙇

**Comment by sirreal** [comment]
More details on translations here: pxLjZ-4Nm-p2

**Pull request merged**
