### PR TITLE
Profile: Add UI frame to /help

### PR DESCRIPTION
**Pull request by taipeicoder**
Fixes https://github.com/Automattic/dotcom-forge/issues/7563

## Proposed Changes

This PR adds the UI frame to /help to be consistent to the rest of the pages in Profile.

| Before | After |
| --- | --- |
| Screenshot 2024-06-03 at 5 32 14 PM |  Screenshot 2024-06-03 at 5 32 26 PM |

## Why are these changes being made?

Consistency!

## Testing Instructions

* Head to `/help`.
* Ensure that the UI frame is consistent with the rest of the pages in Profile.

## Pre-merge Checklist

- [x] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [x] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [x] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [x] Have you checked for TypeScript, React or other console errors?
- [x] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [x] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [x] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Review by davemart-in — APPROVED** [review]
I didn't even know this page existed! :-) Where do we link to it?

Regardless, this LGTM!

**Comment by taipeicoder** [comment]
I discovered the page by working on bringing the support card to the Overview tab (TIL too):
 
Screenshot 2024-06-03 at 9 50 37 PM

After checking Calypso, turns out that [many other parts](https://github.com/search?q=repo%3AAutomattic%2Fwp-calypso%20%2Fhelp%2Fcontact&type=code) also take users to that page 🙂

**Comment by Addison-Stavlo** [comment]
Nice find!

Outside of this PR, I wonder if we should add this as a menu item in the /me sidebar? 🤷‍♀️

**Review by Addison-Stavlo — APPROVED** [review]
Looks great to me! Il send it.

**Pull request merged**
