### PR TITLE
Theme Showcase: custom responsive breakpoint for theme sheets

### PR DESCRIPTION
**Pull request by folletto**
This PR addressed some concerns about too narrow columns. See #5472.

The breakpoint is moved now to `900px`. The reason for `900px` instead of the suggested `1024px` is because 1024px is the size of portrait tablets, so makes sense there to still use the two columns view.

Screenshot, `900px`, partially scrolled:

screen shot 2016-05-25 at 19 25 46

/cc @kathrynwp to see if this works. :)

### CODE REVIEW

**Comment by folletto** [comment]
Full height screenshot, `900px`:

pageshot of mood theme wordpress com 2016-05-03-1930

Full height screenshot, `901px`:

pageshot of mood theme wordpress com 2016-05-03-1931

**Comment by kathrynwp** [comment]
It looks **much** better! @sixhours - what do you think?

**Comment by sixhours** [comment]
Looking much better. :)

**Comment by seear** [comment]
@folletto: you think the predefined `960px` breakpoint is too wide for the single column layout?

**Comment by folletto** [comment]
> you think the predefined 960px breakpoint is too wide for the single column layout?

...

_* facepalm *_

I switched to pixels to find a good place, I found it... and yeah, it's close enough to just use the standard one. :D 

Updated. :)

**Comment by ockham** [comment]
LGTM!

**Comment by ockham** [comment]
(You should probably squash before merging, tho :-) )

**Pull request merged**
