### PR TITLE
BackupRetention: Add purchase storage and update retention flow

### PR DESCRIPTION
**Pull request by Initsogar**
Currently, as implemented in #73415, if a desired retention option requires additional storage, we have a `Purchase button` that redirects the customer to the checkout page. After purchasing the add-on storage, they are redirected back to the setting page and now that they don't require additional storage, they need to click on `Update setting`.

The idea is to allow customers to update their retention period after a successful add-on storage purchase without the need of clicking again on another button.

## Proposed Changes

* Add flow to update the retention setting automatically after being redirected due to a successful add-on storage purchase.
  * If the desired retention requires more storage (because the expected storage is above our bigger add-on offer), the retention will not be updated automatically. They will need to buy the necessary add-ons first.
* Add new query argument `storage_purchase` that will be used when redirected from the checkout page after a successful add-on storage purchase.

## Demo

https://user-images.githubusercontent.com/1488641/222046167-82803595-d6ee-43a0-8407-e5762d29ac43.mp4
 
## Screenshots

| Before | After |
|---|---|
| image | image |

### Unit testing

You can run the unit tests by running `yarn run test-client client/components/backup-retention-management`.

### Acceptance test

Unfortunately, this one cannot be tested using Jetpack Cloud live branch, due to some restrictions redirecting back from checkout page to calypso.live domain.

* Checkout `add/backup-retention-purchase-update-flow` branch locally.
* Run `ENABLE_FEATURES=no-force-sympathy yarn start-jetpack-cloud`. This is to prevent state to being randomly cleared out when redirected back from checkout. More details on what sympathy means [here](https://github.com/Automattic/wp-calypso/pull/14121).
* Navigate to Settings and wait for the new setting to load.
* Ensure the `Update settings` button is disabled when the current plan is selected if that plan doesn't require an storage upgrade.
* Click an option that requires an upgrade and validate:
  * It should display a message similar to:
    image
  *  Ensure the CTA button is renamed to `Purchase and update`
  * Click on the CTA. It should redirect you to the checkout page and add the product to the cart.
  * Remove all items from the checkout cart.
    * It should redirected back to the setting page with the `retention=NUMBER` query argument.
    * The radio button with that option should be selected by default.
  * Now, try again, clicking on the CTA to redirect you back to the checkout page.
  * Purchase the add-on with credits and ensure that after purchasing, it should redirect you to the setting page.
    * The URL should have a `retention=NUMBER&storage_purchased=1` query arguments, and the radio button with that option should be selected by default.
    * You should see the CTA button is disabled and after a bit you should receive the success notice and the `Current plan` indicator should be switched to the selected option.
    * image

## Pre-merge Checklist

- [x] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [x] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [x] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [x] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [x] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/7835971

Thank you @Initsogar for including a screenshot in the description! This is really helpful for our translators.

**Review by mavegaf — APPROVED** [review]
Tested the flow. The setting is updated after returning from a successful purchase

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/7835971

Thank you @Initsogar for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/7835971).

**Pull request merged**
