### PR TITLE
Themes: Add title to logged-out Masterbar

### PR DESCRIPTION
**Pull request by seear**
Addresses #2567

Work in progress based on #4931. Starts at 0dd5db8

screen shot 2016-04-26 at 17 40 48
screen shot 2016-04-26 at 17 41 19

This is nice and simple — the `title` prop is set in `sections.js`. I18n could be a problem, though it might be that we want 'Themes' to be 'Themes' in any language, similar to 'WordPress.com'.

### CODE REVIEW

**Comment by folletto** [comment]
> it might be that we want 'Themes' to be 'Themes' in any language, similar to 'WordPress.com'.

Yes. :) 
We can review this decision later, but at this stage we can keep it, since it's not even a regression. :)

**Comment by seear** [comment]
@folletto: could you give this a final styling tweak? Seems to me that the title could be closer to the logo (at any width).

**Comment by ockham** [comment]
> it might be that we want 'Themes' to be 'Themes' in any language, similar to 'WordPress.com'.

Just adding here that IMO this won't collide with i18n -- if we decide to internationalize section titles, we can either not wrap `'Themes'` in a `translate` call, or add a translation comment to ask translators to translate it to `'Themes'`.

**Comment by folletto** [comment]
* Fixed spacing of the logo + title.
* Removed `is-loggedOut` since it’s not used.
* Fixed mouse cursor icon visibility if href isn’t present.
* Made the gridicon padding selector more accurate.
* Removed visible `hover` state for logo + title.

Tested in Chrome, Firefox, Safari, Edge, IE11.

screen shot 2016-04-29 at 17 40 08

screen shot 2016-04-29 at 17 41 18



I also made sure it's "ready" for adding new menu items in the future (no code added, and the dropdown-conversion code at mobile sizes has to be added before it could work):

screen shot 2016-04-29 at 17 11 39

**Comment by seear** [comment]
This is looking good, I'm going to merge 👍

**Pull request merged**
