### PR TITLE
Checkout: Change stale cart notice text

### LINKED ISSUE #19789: Improve "Your site deserves a boost" notice to communicate better about cart abandonment
This was reported originally here: 793125-zen and solved via slack p1510728111000122-slack-tickets. The user has purchased a plan and domain but receives that message, doesn't understand why if already purchased the products and don't realize that are some products on the cart waiting for the checkout process to be completed, or removed completely.

#### Steps to reproduce
1. Starting at URL: http://wordpress.com/
2. Start to purchase any product, like a domain or a plan, but do not complete the checkout
3. Wait 10 minutes
4. Check the message on your dashboard: "Your site deserves a boost - Complete your purchase"

screen shot 2017-11-15 at 13 31 04

This comes from https://github.com/Automattic/wp-calypso/blob/8abd57fe22b0a778f21d8ea41967fb17d6e478d6/client/my-sites/current-site/index.jsx#L66 , were after 10 minutes with an item on the cart but without the checkout process being completed, the message is prompted.

Maybe we should rephrase the sentence in order to make more clear that they have products on the cart?

cc: @nielslange

### PR DESCRIPTION
**Pull request by millerf**
Replace “Your site deserves a boost!” with “You cart is awaiting for
payment”

Fix #19789
cc @iamgabrielma

### CODE REVIEW

**Comment by benhuberman** [comment]
I like the current copy for its warmer / friendlier tone and would prefer to keep it. The problem described in the original issue seems to be more around the persistence of the notice even after a purchase has been made; this strikes me as something that calls for a change in the way these are shown/timed, rather than a language tweak -- mentioning the cart explicitly here would still be confusing for someone who'd already purchased a product.

**Comment by millerf** [comment]
@benhuberman I read the issue again, and it does state the problem comes from the purchase not being finalised...

The "Your site deserves a boost!" was totally misleading for me, but I agree it needs to keep the friendly tone.

**Comment by iamgabrielma** [comment]
> The problem described in the original issue seems to be more around the persistence of the notice even after a purchase has been made; this strikes me as something that calls for a change in the way these are shown/timed, rather than a language tweak

@benhuberman  To clarify the issue is about the message and not about the persistence of the notice (this works alright afaik). This is just because the notice shows when a user has added a product to their cart but they don't finish the purchase.

In that particular case, user purchases product A successfully, but also added product B to the cart and this purchase was not finished. Their confusion is "Why I receive this message if I already purchased product A?", and they don't realize/see that product B is still in the cart and the purchase was never made, so they may dismiss the notice and forget about the purchase or think this has been successfully purchase when it was not.

Making the "You still have products in your cart that you must purchase" message clearer or maybe removing the "dismiss" button and changing it for a "redirect to cart" link to either complete the purchase or dismiss it could be a good solution here UX-wise.

**Comment by benhuberman** [comment]
No objections on my end, @millerf, but I'd like to leave this decision to the team who'd actually need to implement these changes.

**Comment by travisw** [comment]
Thanks for the ping @benhuberman and sorry about the late reply.
I've brought this up on the original thread here: p8Eqe3-2Y-p2

If we do change it to something similar to what's proposed I think the grammar would need to be fixed.

> You cart is awaiting for payment

I think it should either be

> ...awaiting payment

or

> ...waiting for payment

**Comment by Copons** [comment]
Hi @millerf!
Thank you for pushing this change.
I just gave another nudge to the marketing folks in order to bring this PR to a conclusion. 🙂

Please notice that the new phrasing might need to be updated to end with a period or an exclamation point. No need to change it now, let's wait for a green light first.

**Comment by millerf** [comment]
@Copons No worries, thanks for the update!

**Comment by Copons** [comment]
All right @millerf, we've decided to do an A/B test on this change.
Since you raised this issue, I can guide you through how to update this PR, instead of creating a new one in my name and losing your authorship.

Luckily, it's all quite straightforward! 🙂 

1) Add the test to the [active tests list](https://github.com/Automattic/wp-calypso/blob/master/client/lib/abtest/active-tests.js#L111) (update the `datestamp` to the date you're pushing this change):

```js
staleCartNotice: {
	datestamp: '20180426',
	variations: {
		siteDeservesBoost: 50,
		cartAwaitingPayment: 50,
	},
	defaultVariation: 'siteDeservesBoost',
},
```

2) Import the `abtest` utility in the internal dependencies block of the [file we're working on](https://github.com/Automattic/wp-calypso/blob/master/client/my-sites/current-site/index.jsx#L31):

```es6
import { abtest } from 'lib/abtest';
```

3) [Use it](https://github.com/Automattic/wp-calypso/blob/master/client/my-sites/current-site/index.jsx#L68) to serve the original string to 50% of our users, and your updated string to the other 50%:

```es6
this.props.infoNotice(
	'siteDeservesBoost' === abtest( 'staleCartNotice' )
		? this.props.translate( 'Your site deserves a boost!' )
		: this.props.translate( 'Your cart is awaiting payment.' ),
	{
		/ * ... * /
	}
);
```

Once this is ready, I'll also update the infrastructure behind it to support this test.
Then we're going to merge it, and keep the test running for a while (2 weeks or 1 month); then we'll look at the analytics and keep the string that performed better.

Let me know if you have any doubts or questions about it! 🙂

**Comment by millerf** [comment]
@Copons , thanks for the 'tutorial'.
I am pretty busy today so I am not sure  I will be able to do anything.

But regarding 'authorship', since I only changed a string, I don't see any problem if you want to recreate a new branch, a new PR or just push on that branch 😁

**Comment by Copons** [comment]
> I am pretty busy today so I am not sure I will be able to do anything.

No worries, there's no rush. 🙂

**Comment by millerf** [comment]
Hi @Copons,

I've finally got some free time to do that. Thanks for the tutorial, it made it a breeze to do it.

**Comment by Copons** [comment]
@millerf Thanks for following through with this!
Changes look good to me, I'll merge this after I complete some behind the scenes work required for all A/B tests. 🎉

**Comment by millerf** [comment]
@Copons no worries.

I would be happy to know what you are doing 'behind the scenes'. I guess preparing some analytics, right?

**Comment by Copons** [comment]
@millerf Exactly!
I'm adding the new test to our E2E tests so that they don't accidentally blow up.
Then I'm also adding a new event tracking to the notice, in order to analyze the correct flow (e.g. view the stale cart notice -> click on the notice -> proceed to checkout).
And finally, as you guessed, I'm going to prep the hypothesis behind the test to make our data team's life easier.

I've probably underestimated this effort, because adding a new event tracking means that we don't yet have the correct baseline rate value for the hypothesis, so it might take me more than just today to actually merge this. 🙂

**Comment by millerf** [comment]
Nice!

Thanks a lot. Not a big contribution anyway :)

Have a some nice holidays!

**Pull request merged**
