### PR TITLE
Videopress Onboarding: confirm email step

### PR DESCRIPTION
**Pull request by pgk**
### Proposed Changes
*  Create the comfirm email screen of the flow: the signup screen.

Screenshot 2022-07-25 at 2 01 22 PM

### Testing Instructions

* Start your local dev and navigate to http://calypso.localhost:3000/start/videopress
* You are redirected to http://calypso.localhost:3000/start/videopress/user
* fill email details and click 'Create your account'.
* You are then in http://calypso.localhost:3000/start/videopress/videopress-confirm-email
* You will need to refresh your page for the view to render. This is a known thing.
* looks like the pic above

### CODE REVIEW

**Comment by roundhill** [comment]
Hmm I always get a black black page, even after refreshing multiple times. This is in an incognito Chrome browser window.

**Comment by evilluendas** [comment]
Looks great! A couple of small details:

- The wpcom logo in the footer is dark, so it can't be seen over black background. Would it be possible to make it white? I believe we can just use `w-logo-white.png`.
- The footer itself would look nicer if it's aligned to the bottom of the window if the content of the page is shorter than the viewport. What I'd do is to add `display: flex;` and `flex-direction: column;` to `.videopress-step-wrapper__middle`, and then add `flex: 1;` to `.step-wrapper`.
- `.videopress-step-wrapper__middle` has `height: 100vh;`, but there's a 70px white topbar so it creates some unnecessary scroll. I think I'd try replacing the height for `height: calc(100vh - 70px);` although I haven't checked if that'd work on mobile!
- I'm not sure about the "Step 2 of 2" on the topbar, it may be misleading given that there'll be more steps afterwards. Should we just remove it?
- The hover color for links is a bit hard to read, as it's pretty dark. I think I'd keep `var(--videopress-color-link);` for hover too, at least for now.

This is how it'd look like with these changes:

image

**Comment by pgk** [comment]
> Looks great! A couple of small details:
> 
>     * The wpcom logo in the footer is dark, so it can't be seen over black background. Would it be possible to make it white? I believe we can just use `w-logo-white.png`.
> 
Adressing this in https://github.com/Automattic/wp-calypso/pull/66016 since it is more related to the overall styling of the step wrapper.

**Comment by pgk** [comment]
> Looks great! A couple of small details:

Actually most of those are step wrapper - related, so I will be amending that pr I created for fixing the logo to include all the wrapper - related stuff

**Comment by pgk** [comment]
Not sure if we need this pr anymore, closing for now.

**Pull request closed without merging**
