### PR TITLE
Reader: Rework empty content placeholders to link to search

### PR DESCRIPTION
**Pull request by blowery**
Recommendations is going away, so link to search instead.

### CODE REVIEW

**Comment by blowery** [comment]
following
following_ _reader_ _wordpress_com

following edit
manage_followed_sites_ _reader_ _wordpress_com

empty feed
krista_stevens_ _reader_ _wordpress_com

**Comment by blowery** [comment]
404 feed
loading_feed_ _reader_ _wordpress_com

**Comment by fraying** [comment]
Nice work, @blowery!

Nitpick: Could we make that last screen white? Just for consistency?

**Comment by fraying** [comment]
@blowery Also, on the 404, let's prioritize "Find Sites to Follow" (ie, make it blue and first).

**Comment by blowery** [comment]
loading_feed_ _reader_ _wordpress_com

**Comment by fraying** [comment]
@blowery Nice! (Is that scrolled up a bit? Or is there that little space between drake and the masterbar?)

**Comment by blowery** [comment]
nah, switching to the Main that has the white bg dropped the space. Working on adding it back.

**Pull request merged**
