### PR TITLE
Update Connect Domain screens to allow for Domain Connect

### PR DESCRIPTION
**Pull request by hambai**
We want to use [Domain Connect](https://github.com/Domain-Connect/spec) for domains that support it and it would be best if we implement that in the "Connect domain" flow.

## Proposed Changes

* I've added new flow for Domain Connect with 2 steps - DC_START and DC_VERIFYING
* Stop using query param `step` for internal links - it would be more consistent to determine the last `connection_mode` from the mappingSetupInfo API result
* Inroduce loading placeholders while the `mappingSetupInfo` loads
* New START screen for Domain Connect that would redirect the customer to the Domain Connect signed URL
* Updated the links at the bottom (ConnectDomainStepSwitchSetupInfoLink) to show the new flow (simple) when Domain Connect is available
* Updated the backend to return two new properties in the `mappingSetupInfo` API that will contain hte connection_mode and the Domain Connect apply URL and also allow the `return_url` param to be encoded - D101993-code

### If Domain Connect is available you'll see this screen
Screenshot 2023-02-28 at 21 44 37

### When you click on Start seetup you'll be sent to the DNS Provider
Once you log in you'll see this (or similar - that part depends on the DNS Provider):
Screenshot 2023-02-28 at 21 47 25

### If you click on Connect you should get redirected back to this
Screenshot 2023-02-28 at 21 43 55

### If you click on Cancel you'll get here
Screenshot 2023-02-28 at 21 42 08

### If there's an error you'll see this
Screenshot 2023-02-28 at 21 43 02

## Testing Instructions
* Apply D101993-code and then build Calypso with this PR applied
* Make sure that mapping a domain that does not support Domain Connect still works as before (there is suggested and advanced flows)
* Then try to map a domain that supports Domain Connect - the initial step should now render the new START component
* The button in that component should show the DNS provider Domain Connect flow where you should be able to apply the provided template records with a single click
* Make sure you can click on the links to switch between the different flows (simple, manual, advanced)
* See what happens when you successfully apply the records at the DNS provider
* NOTE: you'll always be redirected back to wordpress.com. To test the flows properly just replace https://wordpress.com/ with http://calypso.localhost:3000/ but keep the rest of the URL

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

**Comment by hambai** [comment]
Stuff to discuss:
* How should it work when you click on "cancel" in the partner site?
* How should it work when you click on "add records" in the partner site?
* What should we show if you exit the flow and click on the status text button again?
* Should we even allow for "< back" in the verifying screen?

**Review by delputnam — APPROVED** [review]
This looks good and works well for me. 👍

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/7846292

Thank you @hambai for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/7846292).

**Pull request merged**
