### PR TITLE
Post-migration purchase experience: Add "View Sites dashboard" button to migration started page

### LINKED ISSUE #95565: Post-purchase Migration Experience: Add button on the "Migration Started" step to navigate to the sites dashboard
## Description

Add a new button to the "Migration started" step to navigate to the sites dashboard.

Figma: QnzGpMHVpKuf0ZeRQVcxiL-fi-8161_1788
More context: p9Jlb4-ep1-p2#comment-13903

Image

### PR DESCRIPTION
**Pull request by sixhours**
Fixes #95565

## Proposed Changes

* Add a "View Sites dashboard" button to the Migration started page in the signup flow.
* Update the subtitle copy.
* De-emphasize the A4A button.

Screenshot 2024-10-28 at 1 55 03 PM

## Why are these changes being made?

* p9Jlb4-ep1-p2#comment-13903

## Testing Instructions

* Switch to this PR
* Navigate to `/setup/site-migration/site-migration-started?siteSlug=yourtestsite.wordpress.com`
* Note the presence of the button and the copy updates; check for visual errors
* Ensure clicking on the button takes you to `/sites` (the Sites dashboard)
* Upon clicking the button, you should see a Tracks event fire in Tracks Vigilante or the console (run `localStorage.debug="calypso:analytics*"` in the console and refresh the page):

Screenshot 2024-10-28 at 12 09 36 PM

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Comment by fditrapani** [comment]
Thanks for taking care of this update @sixhours. Can we update the subtitle copy to match what's in the comment you mentioned. The button in it's current state lacks some context. 

Here's the copy: 
> Your migration process has started. We’ll email you when the process is finished. You can track of the progress from your sites dashboard.

And here's a reference
image

Also note that I deprioritized the button in the A4A feature.

**Comment by sixhours** [comment]
@fditrapani Ahh, apologies! The original issue only mentioned adding the button. I will update to better match the full screenshot. 👍

**Comment by sixhours** [comment]
> You can track of the progress from your sites dashboard.

@fditrapani I'm updating this to "You can keep track of the progress from your sites dashboard." but let me know if it should be something else!

**Comment by fditrapani** [comment]
That's right. I didn't even read my old copy :D Just make sure to capitalize the Sites dashboard like the button and then I think we're good!

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/16949940

Some locales (Hebrew, Japanese) have been temporarily machine-translated due to translator availability. All other translations are usually ready within a few days. Untranslated and machine-translated strings will be sent for translation next Monday and are expected to be completed by the following Friday.

Thank you @sixhours for including a screenshot in the description! This is really helpful for our translators.

**Review by gabrielcaires — COMMENTED** [review]
LGTM

**Review by gabrielcaires — APPROVED** [review]

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/16949940).

**Pull request merged**
