### PR TITLE
Devdocs: fix display of plan items.

### PR DESCRIPTION
**Pull request by mtias**
Before:
image

After:
image

cc @gwwar @lamosty 

Test live: https://calypso.live/?branch=fix/plans-in-devdocs

### CODE REVIEW

**Comment by lamosty** [comment]
Nice work but do we really want this? I have split window (smaller) and this is how it looks for me: 
selection_021

I think having each plan on a new line/underneath the other ones is a good thing. That way, we can see the whole component, how it behaves when it has enough space, etc. And besides, we are not using the `PlansFeaturesMain` in this PR so we don't preserve the same design/looks as on the `/plans` page.

**Comment by mtias** [comment]
It makes the devdocs page almost unusable.

**Comment by mtias** [comment]
We could remove them from devdocs as well.

**Comment by lamosty** [comment]
I agree. We needed them when working on it, but now it's a bit useless and takes too much space.

**Comment by gwwar** [comment]
I'd be fine removing the example from the docs page.

**Comment by lamosty** [comment]
Closing in favor of #6533.

**Pull request closed without merging**
