### PR TITLE
Add a phone number field to the concierge booking form

### PR DESCRIPTION
**Pull request by scruffian**
#### Changes proposed in this Pull Request

* This adds a phone number field to the concierge booking form. The number is sent to the HE, and a SMS is sent to the user reminding them of their booking slot. It needs D21440-code in order to work.

#### Testing instructions

* Open this branch on a site with a business plan:
http://calypso.localhost:3000/me/concierge/[site]/book
* Apply this patch to your sandbox: D21440-code
* Enter your details including your phone number
* Schedule a session
* Confirm that you receive an SMS confirming your appointment.

TODO - in the future we should add reminders closer to the time of the call, and also use a phone input field so that its easier for users to enter their country code.

### CODE REVIEW

**Comment by gracie** [comment]
Let's add this copy to the text, so people know we aren't calling them:

> As a note, we will not call you. Instead, check your email for the link to join our screenshare. 

Thanks!

**Comment by scruffian** [comment]
> As a note, we will not call you. Instead, check your email for the link to join our screenshare.

Thanks, I updated the PR based on your suggestion.

**Comment by sixhours** [comment]
I'm unable to see the schedule on `calypso.localhost:3000`; I get the following error: 
Screen Shot 2019-04-16 at 11 01 52 AM

The master branch works fine, so I think something in this PR isn't working.

Using this URL with a new Business plan: `http://calypso.localhost:3000/me/concierge/ineedabusinessplanok.wordpress.com/book`

(I also sandboxed the new URL `ineedabusinessplanok.wordpress.com` in case it made a difference.)

**Comment by scruffian** [comment]
@sixhours I rebased this, and now it seems to be working. Would you mind giving it another spin?

**Comment by sixhours** [comment]
Tried again, but now I can't get the concierge form to load locally or on WP.com proper (so it's probably not this PR); it's stuck loading:

Screen Shot 2019-04-25 at 11 28 49 AM

I feel like I must be missing something obvious. :)

**Comment by sixhours** [comment]
TIL: Make sure you've logged into `/me` with your 2FA credentials or some things won't work. :)

**Comment by sixhours** [comment]
To follow up, I got the form working -- yay! -- but the text message never got through, so something isn't working on that end.

**Comment by scruffian** [comment]
@sixhours sorry about that, looks like this was added to Redux since I made the PR. I added another commit which adds the phone number to the reducer, so this should work again - it did for me at least!

**Comment by sixhours** [comment]
Yay, it worked! 🙌

**Pull request merged**
