### PR TITLE
Framework: color definitions cleanup

### PR DESCRIPTION
**Pull request by mtias**
Groundwork for flexible color schemes. There should be no visual changes besides some subtle color shifts.

Test live: https://calypso.live/?branch=add/color-scheme-cleanup

### CODE REVIEW

**Comment by rickybanister** [comment]
Making all the sidebar and masterbar colors more relative to each other seems like a nice change, regardless of color scheming.

**Comment by drw158** [comment]
Interesting, I think this looks good. Here is a screenshot of one of the differences, before and after

screen shot 2016-06-17 at 3 39 34 pm

Personally I like the color as it was before. Maybe if you darkened up the new color a bit.

**Comment by mtias** [comment]
@drw158 this is a bit more darkened:

image

Would that work? Otherwise we can create a color var for it and assign it dark blue by default.

**Comment by drw158** [comment]
That screenshot looks good to me

**Comment by mtias** [comment]
Thanks for looking!

**Pull request merged**
