### PR TITLE
Stats: Add tier quantity information to checkout

### PR DESCRIPTION
**Pull request by grzegorz-cp**
Related to #85326 (based on #84837)

## Proposed Changes

* Add a condition to `getLabel` to display additional information for Jetpack Stats tiered plans, making it clear to the user which plan they are purchasing.

## Testing Instructions

* Checkout the branch and make sure you sandbox the store and have `D129634` diff applied
* Go to `/checkout/<blog_slug>/jetpack_stats_yearly` and confirm nothing changes
* Visit `/checkout/<blog_slug>/jetpack_stats_yearly:-q-<your quantity>` and confirm the number of requests is part of the product title
* Purchase the plan using a test card or credits
* Go to `/me/purchases`, and click to see the new purchase
* Confirm that you see the purchased quantity in the title

After the update:
SCR-20231219-kuqt

SCR-20231219-kvdw

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

**Review by dognose24 — APPROVED** [review]
Works as described! As an improvement, could we format the number to `250,000` for better recognition since we have more number digits for the name than Jetpack AI?

**Comment by dognose24** [comment]
We may also need to follow up on the [quantity limitation issue](https://github.com/Automattic/wp-calypso/pull/84837#pullrequestreview-1768422767) on the backend as the based PR for arbitrary numbers on the checkout page.

截圖 2023-12-19 上午11 09 15

截圖 2023-12-19 上午11 12 57

**Comment by a8ck3n** [comment]
This is nice!

Another suggestion for improvement would be to address the double parenthetical on the Checkout page:

> Jetpack Stats (Commercial license) (250000 views per month)

It looks like the first parenthetical is part of the product name so maybe we could update the format to something like this:

> Jetpack Stats (Commercial license) — 250,000 views per month

OR if we go with shortened numbers, maybe:

> Jetpack Stats (Commercial license), 250k views per month

I think either option makes for a less awkward display there.

**Review by sirbrillig — COMMENTED** [review]
No objections from me. Thanks!

**Comment by grzegorz-cp** [comment]
I added formatting to the quantity and replaced the parenthesis with a hyphen.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/10376268).

**Comment by kangzj** [comment]
Thanks for working on this! 👍

**Pull request merged**
