### PR TITLE
Subscriptions management: Enhance subscriptions tab switcher mobile UX

### LINKED ISSUE #76576: Subscription management flows over on mobile
### Quick summary

Subscription management page flows over on mobile screens

### Steps to reproduce

On mobile device...
1. Subscribe to a blog
2. Get subscription confirmation email
    
    

3. Clicking confirm, see how the following page overflows

    
 
    

### What you expected to happen

Smoother experience on mobile.

### What actually happened

Broken mobile visuals.

### Impact

All

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

_No response_

### Logs or notes

@Automattic/apex could you take a look at this while you're working on these interfaces? Thanks!

### PR DESCRIPTION
**Pull request by mashikag**
Resolves https://github.com/Automattic/wp-calypso/issues/76576

<p align="center">
  <table>
    <tr>
      <td>
        After
        <p align="center"><em>Before (scrolled to the right)</em></p>
      </td>
    </tr>
    <tr>
      <td>
        After
        <p align="center"><em>After</em></p>
      </td>
      <td>
        After (with dropdown open)
        <p align="center"><em>After (with dropdown open)</em></p>
      </td>
    </tr>
  </table>
</p>

## Proposed Changes

* Revert to using the native mobile behavior of the `SectionNavItem` component, i.e. to use a select-dropdown for tab selection in mobile view

## Testing Instructions

1. Check out the PR.
2. Navigate to `client/server/pages/index.js` and temporarily add `return next();` to the line `833`:

Markup on 2023-04-28 at 17:50:44

3. Build the app.
4. Log in to a test WordPress.com account that has some Sites subscriptions.
5. Navigate to http://calypso.localhost:3000/subscriptions/sites with a web view of horizontal resolution lower than `480px`.
6. You should now see the select-dropdown instead of tabs row. Ensure that scaling back to a resolution with width greater than 480px displays the tabs row in full. 

_Credits to @ivan-ottinger for the above testing instructions 🙇_ 

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

**Comment by mashikag** [comment]
@saygunnyc, for your awareness, we are going to merge this in now to enhance the mobile UX, but an iteration on this is probably needed. 😁 

cc @simison

**Comment by saygunnyc** [comment]
Oh, I see, does this now follow an existing approach? _– The dropdown_

**Comment by simison** [comment]
@saygunnyc see https://github.com/Automattic/wp-calypso/issues/76576#issuecomment-1534886717

**Comment by JuanLucha** [comment]
Mm... Something is a bit odd. This is what I see:
Screenshot 2023-05-15 at 17 27 54
Screenshot 2023-05-15 at 17 28 08

I usually use Firefox Developer Edition, but I tried with regular Firefox and got this too.

**Review by JuanLucha — CHANGES_REQUESTED** [review]
We need to fix this before merging: https://github.com/Automattic/wp-calypso/pull/76727#issuecomment-1548084494

**Review by JuanLucha — APPROVED** [review]

**Pull request merged**
