### PR TITLE
Reader: Fix all eslint warnings in client/reader

### PR DESCRIPTION
**Pull request by blowery**
Should be no functional changes.

Test live: https://calypso.live/?branch=fix/reader/lint-warnings

### CODE REVIEW

**Comment by blowery** [comment]
cc @aduth

**Comment by aduth** [comment]
Did you want to tackle the non-`--fix`-able ones in a separate pull request and get these in first?

**Comment by blowery** [comment]
@aduth yeah was thinking that might be best. most of the non --fix ones are a bit more involved

**Comment by aduth** [comment]
LGTM 👍

**Pull request merged**
