### PR TITLE
Plan: Update CTAs visual style on the plan management page

### PR DESCRIPTION
**Pull request by taggon**
#### Proposed Changes

* This PR changes the CTAs visual style on the plan management page. ref: pebzTe-cs-p2

#### Testing Instructions

* Go to a site on a paid plan.
* Choose `Upgrades > Plans` on the left sidebar and click `Manage plan` on the main panel.
* The CTAs below the plan details card should look as follows:
  screenshot-2022-09-05-at-15 33 30

#### Pre-merge Checklist

- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [x] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [x] Have you checked for TypeScript, React or other console errors?
- [x] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [x] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?

Related to #

### CODE REVIEW

**Comment by JanaMW27** [comment]
Reviewed and it looks good! 👍

**Comment by DavidRothstein** [comment]
I tried purchasing a subscription and going to the purchase management page and saw this:

cancel-subscription-and-refund

It looks odd to not have an icon here when all the other ones do, and the sentence case is inconsistent (i.e. it should presumably be "Cancel subscription and refund" to match the others).  If you're going to add icons and switch to sentence case, I think you need to do it everywhere -- there are actually lots of examples like this (the above is just one), for example "Cancel Domain" when cancelling a domain has the same problem, and there are many more.

I also noticed that for a subscription outside the refund window, I see this (again, another example with problems like the above):

cancel-subscription-auto-renew-on

But more important, if I go through and click "Cancel Subscription" in the above to (disable auto-renew), I now wind up on this screen, with yet **another** "Cancel Subscription" link:

cancel-subscription-auto-renew-off

But this time the "Cancel Subscription" link has a completely different meaning (it actually removes the subscription).  I think that would be extremely confusing to the user.

**Comment by JanaMW27** [comment]
All cases with a cancelation button should follow the above design. The bin icon + the Cancel label, all in red.

**Comment by michaeldcain** [comment]
@JanaMW27: what are your thoughts on @DavidRothstein's comment above?

> if I go through and click "Cancel Subscription" in the above to (disable auto-renew), I now wind up on this screen, with yet another "Cancel Subscription" link:
> 
> But this time the "Cancel Subscription" link has a completely different meaning (it actually removes the subscription). I think that would be extremely confusing to the user.

I'm in agreement that having the same wording for two separate actions is very confusing (to the point that there will likely be users that click it again because they think the app didn't work correctly).

**Comment by JanaMW27** [comment]
I am currently working on changing the labels for this and improving the overall UX flow.
For now, let's have:
Cancel plan and refund (for user within refund window) In red and with the bin icon
Cancel plan (for a user outside the refund window) In red and with the bin icon
Remove plan (for a user with auto-renew off) In red and with the bin icon
I think this will work in the meantime.

**Comment by taggon** [comment]
Rebased.

**Comment by taggon** [comment]
Purchase_Settings_‹_Business_Monthly_—_WordPress_com

@JanaMW27 For expired purchases, the page shows `Pick another plan` instead of `Upgrade plan` but the upload icon doesn't fit the description. Could you give me another icon name for `Pick another plan`?

**Comment by JanaMW27** [comment]
Can we use this one?
view_carousel_24px_outlined

**Comment by taggon** [comment]
Purchase_Settings_—_WordPress_com

@JanaMW27 done. :)

**Comment by taggon** [comment]
All labels and icons are updated as per @JanaMW27 's suggestions.

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/7528985

Thank you @taggon for including a screenshot in the description! This is really helpful for our translators.

**Comment by JanaMW27** [comment]
Thank you! Could I ask for a piece of feedback that came in yesterday? The cancel and remove labels, and the icon can they be the same color as the other buttons, rather than red?

**Comment by taggon** [comment]
> The cancel and remove labels, and the icon can they be the same color as the other buttons, rather than red?

Purchase_Settings_‹_Premium_Monthly_—_WordPress_com

@JanaMW27 already done.

**Comment by JanaMW27** [comment]
Perfect! thank you!

**Comment by michaeldcain** [comment]
@taggon: this feels really close. I tested the flows @DavidRothstein pointed out above, and they seem to be addressed. I did notice that after cancelling a domain, the button now says "Remove subscription". It should probably say "Remove domain" to follow the previous buttons.

Screen Shot 2022-09-16 at 2 08 26 PM

I also tested add-ons and one-time purchases (like single premium themes and quick start sessions). They both look good.

It looks to me like the only remaining product that needs updating (aside from the domains remove button) are Earn purchases, which [use a different card](https://github.com/Automattic/wp-calypso/blob/5b5309029c97db4f76f6e0bc4c399c73d4eb68f2/client/me/memberships/subscription.jsx#L136-L145). There's a FG page that covers testing these purchases (PCYsg-lW4-p2).

Screen Shot 2022-09-16 at 2 21 01 PM

**Comment by taggon** [comment]
> the button now says "Remove subscription". It should probably say "Remove domain" to follow the previous buttons.

@michaeldcain Thanks for pointing it out. :) With the latest commit, the button says "Remove domain" if the purchase is a domain registration. The remove button of the Earn purchases should be handled in a follow-up PR to keep this PR focused on the plan management page. I'll create a new PR for that soon.
Purchase_Settings_—_WordPress_com

**Review by michaeldcain — APPROVED** [review]
This looks good to me. Thanks for following up on the Earn issue in a separate PR.

**Comment by taggon** [comment]
Rebased

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/7528985).

**Comment by DavidRothstein** [comment]
Created a followup issue for some small inconsistencies here, including the Earn issue mentioned above (which I don't think has a pull request yet): https://github.com/Automattic/wp-calypso/issues/68921

**Pull request merged**
