### PR TITLE
Framework: Adding 3 new gridicons: status, add image, thumbs up

### PR DESCRIPTION
**Pull request by drw158**
- Status
- Add Image
- Thumbs up

screen shot 2015-12-21 at 9 54 56 am

### CODE REVIEW

**Comment by alternatekev** [comment]
Question about the add-image and smiley face: should they be shifted at 18px to align to the 1.5px grid because of their strokes? cc @jasmussen

**Comment by jasmussen** [comment]
> Question about the add-image and smiley face: should they be shifted at 18px to align to the 1.5px grid because of their strokes?

Looks to me like the smiley and thumbs do need it. 

With the offsetfix:

with

Without the offsetfix:

without

Incidentally I'm working on improving the offsetfix further, and looking into a better way to find out whether the offsetfix can help things at 18 and 36.

**Comment by drw158** [comment]
Can we merge this and add these icons to the offset list later, or does that need to be done now?

**Comment by jasmussen** [comment]
> Can we merge this and add these icons to the offset list later, or does that need to be done now?

Works for me, I'm working on some offsetfix things anyway and can just add these to the array in my PR.

**Comment by drw158** [comment]
Great, thanks Joen. Since there are no issues, I'll go ahead and merge.

**Pull request merged**
