### PR TITLE
Reader: Remove ReaderMain, .is-reader-page

### PR DESCRIPTION
**Pull request by blowery**
These were left over from the reader refresh and can now be removed.

One quirk currently, the white background for reader pages appears as a narrow strip at the top of the viewport during the shell load. Need to figure out how to address that.

### CODE REVIEW

**Comment by blowery** [comment]
wordpress_com

**Comment by blowery** [comment]
Some issues with the gray showing through too when the reader content isn't at least as tall as the page. I'm pretty sure this is why we went with overriding the color at the body level, rather than from `.layout`.

**Comment by blowery** [comment]
cc @fraying @raoulwegat

**Comment by raoulwegat** [comment]
Just a note re #783c0e7, it's not possible to remove the space because it controls the top position of `.layout__primary`, but you can color it in.

**Comment by fraying** [comment]
When I visit https://calypso.live/?branch=update/reader/drop-reader-main I see this:

screen shot 2017-03-28 at 10 05 31 am

Which isn't right ... right?

**Comment by blowery** [comment]
@fraying yeah, https://github.com/Automattic/wp-calypso/pull/12518/commits/783c0e7147873290870ac050b137b61c4c37f95b broke it /cc @raoulwegat

**Comment by blowery** [comment]
This PR isn't going anywhere useful anyway. Closing for now.

**Comment by raoulwegat** [comment]
@blowery My bad. I didn't test a full page load.

**Pull request closed without merging**
