### PR TITLE
show hidden sites after display is rendered

### PR DESCRIPTION
**Pull request by vykes-mac**
#### Proposed Changes

* Fix hidden sites being displayed before sites data is rendered (_This occurs because the sites data is available before the display mode and the sites table is rendered after the display mode is set_)
Screenshot 2022-08-24 at 2 07 11 PM

#### Testing Instructions

* Go to `/sites-dashboard`
* Hidden sites rendered after sites are rendered

#### Pre-merge Checklist

- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?

Related to #

### CODE REVIEW

**Comment by vykes-mac** [comment]
Haven't created an issue yet, awaiting feedback.

**Comment by danielbachhuber** [comment]
@vykes-mac Great minds think alike! https://github.com/Automattic/wp-calypso/issues/66898#issuecomment-1226252319

**Comment by vykes-mac** [comment]
@danielbachhuber haha I guess we choose whichever PR.

**Comment by p-jackson** [comment]
Fixed in #66942

**Pull request closed without merging**
