### PR TITLE
Hosting Config: Describe premium features in the upsell nudge

### PR DESCRIPTION
**Pull request by p-jackson**
#### Proposed Changes

Users in the `treatment` cohort of the `calypso_hosting_configuration_upsell_list_features` experiment see an updated upsell nudge on the `/hosting-config` page.

CleanShot 2023-01-09 at 18 47 15@2x

* Uses `<Experiment>` component to switch between the two banner variations (read more pbxNRc-2f8-p2)
* Displays spinner if experiment cohort is still being loaded/assigned
* Custom icon for each feature we're listing: pdKhl6-1th-p2#comment-1839
* Columns resize and wrap as the screen width changes
* CTA links to the checkout, just like the previous nudge
* Banner uses the same tracks events so that the experiment tools can make the comparison

#### Implementation Discussion

The `<UpsellBanner>` and `<Banner>` components feel like god-classes. They have a lot of properties to toggle between all their different modes. Ideally these components would be more composable rather than have lots of modes e.g rather than exposing a `primaryButton` prop it would allow users to provide their own button.

Rather than adding yet more flags to the shared components I've been able to achieve most of the re-styling in CSS. However the CSS selectors need to be very specific (especially overloading specific media queries) which is not ideal. I suppose it's arguable which is better for long-term maintainability: god-components vs. fragile CSS overrides. I'd be interested in your thoughts.

#### Out of scope for this PR

This PR doesn't:
- represent the final copy. We'll have time to adjust that.
- include the price as scene in the figma design. I'll do that in a follow up PR.

#### Testing Instructions

* Go to experiment page 20995-explat-experiment
* Add the `treatment` bookmarklet to your bookmark bar
* Click bookmarklet and add your user to the `treatment` cohort (tutorial video p1673249013170409/1673241333.083479-slack-C04H4NY6STW)
* `calypso.localhost:3000/hosting-config` in a site with no business plan
* You should see the new nudge
* Test being in the other cohort too to confirm nothing has changed.

#### Pre-merge Checklist

- [x] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] ~[Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?~
- [x] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [x] Have you checked for TypeScript, React or other console errors?
- [ ] ~Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)~
- [ ] ~Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?~
- [ ] ~For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?~

Related to #71598

### CODE REVIEW

**Comment by mpkelly** [comment]
The code is nice and clean, as is the UI! I couldn't test it, though (I sent a message on Slack). My only comment is about the icons - ideally, we'd have one of each, but some of the icons used on the banner are slightly different to those used on the hosting features. 

Regarding CSS specificity: very specific CSS is a good thing in this code base IMO. 😄 

A nice start to 2023, @p-jackson!

**Comment by p-jackson** [comment]
> My only comment is about the icons - ideally, we'd have one of each, but some of the icons used on the banner are slightly different to those used on the hosting features.

Yeah good point I hadn't noticed that. The problem is that the cards don't line up 1-to-1 with features. The credentials card at the top is needed to use SFTP, SSH or CLI; so which icon should it match with?

CleanShot 2023-01-10 at 12 56 13@2x

And sometimes the card refers to SSH and sometimes it doesn't.

CleanShot 2023-01-10 at 12 57 09@2x

So it's not just a matter of lining them up.

Since the first card is the only situation when this clash of icons is apparent (since the overlay fades out the rest of the cards) I think I can just come up with a fix for this one. Since it's the credentials card I'll try using a key icon or something.

**Comment by p-jackson** [comment]
This PR changes the icon to a key https://github.com/Automattic/wp-calypso/pull/71828

**Comment by mpkelly** [comment]
Looks good to me and can be merged. If I were being _ultra_ picky I would say some icons could be flipped in RTL mode:

image

Using `transform: scale(-1, 1);`

image

(I am curious to know how the PHP would even look to a person that reads RTL). 

I tested with Firefox and Chrome on mobile, tablet and desktop. 

You should consider updating the Calypso examples to include a banner in this style. It was updated in https://github.com/Automattic/wp-calypso/issues/71597 but only to show simple list items. I am a big fan of rich content like this and think we should promote it.

**Review by mpkelly — APPROVED** [review]

**Comment by p-jackson** [comment]
Thanks for testing RTL!
English words and letters don't get mirror flipped when written in Arabic, so I don't think it makes sense to flip that icon (we're moving to a Database icon anyway). The CLI icon is interesting though! I'm googling-image-searching for what localised terminals look like.

**Comment by p-jackson** [comment]
I was able to see what the standard terminal application looks like in RTL

CleanShot 2023-01-12 at 11 30 36@2x

The prompt still renders LTR, so I don't think the icon needs to change.

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/7727672

Thank you @p-jackson for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/7727672).

**Pull request merged**
