### PR TITLE
Update theme sheet caption styles

### PR DESCRIPTION
**Pull request by kjellr**
On theme detail pages, we often include images with white backgrounds. Without boundaries to the images, I find it’s hard to figure out what’s content and what’s an image sometimes.

This PR adds a light gray background  and stroke around the images to combat that. 

**Testing:**

Visit a few theme detail sheets, like 
- http://calypso.localhost:3000/theme/altofocus/
- http://calypso.localhost:3000/theme/small-business/
- http://calypso.localhost:3000/theme/intergalactic-2/

**Before/After GIFs:**

example-01

example-02

### CODE REVIEW

**Comment by mapk** [comment]
Excellent idea here @kjellr! I know I've gotten lost between an image and the actual text on occasion due to the lack of separation. I think your approach is a good solution using common styles that are already enforced.

Here's another idea I had as well. I'm trying to break out of the boxed-in column.
screen shot 2018-02-06 at 11 30 25 am

**Comment by kjellr** [comment]
> Here's another idea I had as well. I'm trying to break out of the boxed-in column.

I tried about something like that too:

screen shot 2018-02-06 at 3 12 27 pm

I think any of these options work. My only reservation about breaking out of the box is that it can get a little too flashy when we have a bunch of images in a row (which happens quite frequently). It adds a bit of unneeded complexity to the page.

**Comment by kjellr** [comment]
Updated screenshots, as of ebe47aa

screen shot 2018-02-06 at 3 26 56 pm

screen shot 2018-02-06 at 3 27 21 pm

**Comment by davidakennedy** [comment]
This change looks good! It will definitely help frame the images better for customers. :shipit:

**Comment by mapk** [comment]
@kjellr Let's stick with your original concept of a simple outline and caption background and merge this PR. Great work! 🚢

**Comment by kjellr** [comment]
Thanks, all! I backpedaled and made one last tiny adjustment. 😄 

After sitting with this for a couple hours, I think [the original stoke color](https://github.com/Automattic/wp-calypso/pull/22183#issue-294886610) is a bit more effective than the second color I tried. The lighter border seems just a little too subtle in the [updated screen shots](https://github.com/Automattic/wp-calypso/pull/22183#issuecomment-363554813). 

I went ahead and reverted back to the original one, and also updated [the color we'd been previously using](https://github.com/Automattic/wp-calypso/pull/22183#issuecomment-363545326) for center-aligned images so its consistent. 

A _really_ minor adjustment overall, but I figured I'd rather make this change just once. 😄 

@mapk, sound good on your end?

**Pull request merged**
