### PR TITLE
Media: Google Photos - WIP

### PR DESCRIPTION
**Pull request by johngodley**
WIP for Google Photos

- [x] ~~~#13711 - add service~~~
- [x] ~~~https://github.com/Automattic/wp-calypso/pull/14420 - media library display type~~~
- [x] ~~~#14756 - add endpoints~~~
- [x] ~~~#14909 - refactor media upload~~~
- [x] ~~~https://github.com/Automattic/wp-calypso/pull/14453 thumbnail tests~~~
- [x] ~~~#14798 - media library thumbnail display type~~~
- [x] ~~~#15102 - fetch external media~~~
- [x] ~~~Style the unconnected service message - see 15107~~~
- [x] ~~~#15096 - add external uploader~~~
- [x] ~~~#14998 - add media library data source~~~
- [x] ~~~Add post editor menu dropdown for google photos~~~
- [x] ~~~#15428 - add change source action~~~
- [x] ~~~#15436 - add Google Photos to post editor dropdown~~~
- [x] #15435 - copy external media
- [x] ~~~#15107 - show unconnected message~~~
- [ ] - make available to production!

Warning: this PR will frequently have its history changed

### CODE REVIEW

**Comment by jasmussen** [comment]
On the toggle between the two, let's just use a plain dropdown, as you suggest, even if it's an extra click. This is by far the easiest to understand for users. Mockup:

screen shot 2017-06-20 at 11 13 07

Going to take a stab at the styling issues.

**Comment by jasmussen** [comment]
Realized that our tabs collapse into a dropdown when responsive:

screen shot 2017-06-20 at 11 21 49

So we should have TWO dropdowns: 1 for just the services, and then the tabs on the right can collapse into their own dropdown on responsive.

**Comment by jasmussen** [comment]
Another thing —  if search only searches your WordPress.com media, we should not show the search button when you switch to Photos from Google.

**Comment by johngodley** [comment]
> Another thing — if search only searches your WordPress.com media, we should not show the search button when you switch to Photos from Google.

The search should work for Google Photos too

**Comment by jasmussen** [comment]
The tabs on the media library haven't proven themselves as a good interface. Let's consider a different appraoch:

screen shot 2017-06-21 at 11 59 27

Separate media insertion button in the dropdown...

screen shot 2017-06-21 at 12 00 44

... opens a separate media menu.

This also ties into the work we are doing on the editor, where we are levelling the playing field for inserting items:

screen shot 2017-06-21 at 12 07 03

**Comment by johngodley** [comment]
All merged, closing

**Pull request closed without merging**
