### PR TITLE
Add enhanced ownership settings

### PR DESCRIPTION
**Pull request by allilevine**
Related to https://github.com/Automattic/dotcom-forge/issues/3655 and https://github.com/Automattic/dotcom-forge/issues/3657

Based on https://github.com/Automattic/jetpack/pull/33081
## Proposed Changes

* Add enhanced ownership settings section when locked mode and legacy contact features are available.

### To do:
- [x] Make toggle and input functional.
- [x] Get copy review.

Screen Shot 2023-09-12 at 3 26 05 PM

## Testing Instructions

* Sandbox public-api and a test site on Simple.
* Apply this Jetpack PR to your sandbox, using https://github.com/Automattic/jetpack/pull/33081#issuecomment-1719703029.
* Add a 100-year plan in your Store Admin to your test site.
* Go to /settings/general in Default mode.
* Check the Lock Mode option and Save Changes.
* Populate the Legacy Contact input field and Save Changes.
* Check the blog RC to make sure audit log entries appear as expected.
* Visit /wp-admin/options-general.php on your test site and scroll to the end of the page.
* The values you set in Calypso should show up there. They should also update when you change them from Calypso.

## Pre-merge Checklist

- [x] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [x] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [x] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [x] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

**Comment by obenland** [comment]
@allilevine When locked mode gets toggled we need to refresh admin-menu because the capabilities change and with the available menu items.

**Comment by obenland** [comment]
Does the ci/i18n job fail because I applied the String Freeze label? If so, I'll remove :) 
We can ship this without translations in place as the feature checks keeps it from being visible to customers (these features are only available on the 100-year plan).

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/8968087

Thank you @allilevine for including a screenshot in the description! This is really helpful for our translators.

**Comment by allilevine** [comment]
> Does the ci/i18n job fail because I applied the String Freeze label? If so, I'll remove :) We can ship this without translations in place as the feature checks keeps it from being visible to customers (these features are only available on the 100-year plan).

@obenland Yes, though I'm not seeing it now. Sounds good!

**Review by candy02058912 — APPROVED** [review]
Tested and the Lock and Contacts are in sync with `/wp-admin/options-general.php` when changed from calypso. (simple sites)

**Review by lupus2k — APPROVED** [review]
All works great 🎉

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/8968087

Thank you @allilevine for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/8968087).

**Pull request merged**
