### PR TITLE
Importers Flux store: remove api actions

### PR DESCRIPTION
**Pull request by jsnajdr**
We don't need no `apiStart`, `apiSuccess` and `apiFailure` actions. Receiving the importer state update and marking the state as hydrated is sufficiently covered by the `IMPORTS_IMPORT_RECEIVE` action. This PR removes them.

I had to be careful about implementing the `IMPORTS_IMPORT_RECEIVE` action reducer correctly. It needs to:
- always mark the state as hydrated no matter what the successful response contains, like empty state or a defunct state that should be ignored.
- not update importer state if it's locked, but still mark as hydrated in that case
- not try to convert empty state (`[]`) with `fromApi`. That function assumes some properties always exist and that assumption is right for non-empty states

In the `fetchImporterState` handler, I removed the
```js
castArray( data ).forEach( ( importerData ) => {
  receiveImporterStatus( fromApi( importerData ) );
} );
```
code and changed it to simply:
```js
receiveImporterStatus( data );
```
There is always only one importer status returned, it's never an array of multiple ones. The empty array response (`[]`) is a quirk of the PHP REST implementation, which returns an empty PHP array (`return array()`) which is then serialized into empty array rather than empty object.

The `castArray` call just causes that `receiveImporterStatus` is not called for the response 🙂 And it's also the reason why the `isHydrated` reducer had to react to `IMPORTS_FETCH_COMPLETED` action, too. Now it has to react only to `IMPORTS_IMPORT_RECEIVE`.

**How to test:**
I added a new unit test for the locked case, so running the unit tests is one way to test this.

Other than that, verify that the list of importers is correctly displayed at `/import/:site`, first as inactive, then as active after REST response confirms there is no active running import.

Also verify that if an import is running in the background, it's status is correctly loaded and displayed on the `/import/:site` page reload.

### CODE REVIEW

**Comment by flootr** [comment]
> Other than that, verify that the list of importers is correctly displayed at /import/:site, first as inactive, then as active after REST response confirms there is no active running import.

I think I found a scenario, where the list doesn't change to active when it should. This, so far, only happens for one of the sites I've tested and it only happens when I didn't switch from another site where it works and/or on reload.

Screenshot 2020-12-15 at 09 22 30

This is the API response from `/imports`:

Screenshot 2020-12-15 at 09 26 59

**Comment by jsnajdr** [comment]
> This is the API response from `/imports`:

@flootr Good catch! The gotcha is that the import status is `importExpired`. And that constant is not supported by the `fromApi` mapping and the response processing likely crashes.

We discussed this issue with @tyxla in the main PR: https://github.com/Automattic/wp-calypso/pull/48213#discussion_r540970735

Seems I'll have to fix it somehow in this PR.

**Comment by jsnajdr** [comment]
@flootr I added handling of `importExpired` as another two commits to this PR. They add a unit test, and then define the `appStates.EXPIRED` state and ignore such importers when receiving importer status. The result should be that if the server sends an `importExpired` importer, its status is not shown and a list of importers to start is offered.

Why did this PR uncover the `importExpired` bug? Before this PR, the `fetchImporterState` response was handled with:
```js
.then( data => {
  apiSuccess();
  receiveImporterStatus( fromApi( data ) );
} ).catch( apiFailure );
```
First, the `apiSuccess` action marked the state as hydrated, then `receiveImporterStatus` threw an exception, and it was swallowed by `apiFailure`. The result was that state got hydrated, and it was empty. That's the desired result.

After this PR, we call only `receiveImporterStatus`, which both marks the state as hydrated and receives the importer state. This action now failed as a whole, and the state wasn't marked as hydrated. That's why the disabled importer list (with a "loading from server..." meaning) was shown forever.

**Review by flootr — APPROVED** [review]
Thanks @jsnajdr for the detailed elaboration 👍🏻  I can confirm this now works as laid out in the testing instructions!

**Review by tyxla — COMMENTED** [review]
I'm late to the party, but thanks Jarda and Markus, this looks great!

**Pull request merged**
