### PR TITLE
Domain management: Email: Create context menu component

### LINKED ISSUE #97284: Add updated context menu to mailbox list items
Currently, when go to the "Manage all Mailboxes" option -

Image

We're taken to this page

Image

We plan to move the options above to the context menu of the mailboxes list container.

Image

- [x] Create the context menu
- [x] Add the context menu to the mailbox list container component
- [x] The items point to the same links as before

### PR DESCRIPTION
**Pull request by bogiii**
Closes https://github.com/Automattic/wp-calypso/issues/97284

## Proposed Changes

* Creates context menu component
* Updates Header component to support the context menu
* Integrates context menu

## Why are these changes being made?

* Domain Management Revamp

## Testing Instructions

* Go to `/domains/manage?flags=calypso/all-domain-management`
* Ensure you have WP (titan) and Google domain created
* Select WP domain and select Email tab
* Check the context menu options, check if the links property works
Screenshot 2024-12-24 at 00 17 28

* Select google domain
* Check the context menu options, check if the links property works
Screenshot 2024-12-24 at 00 17 09

| Current options | and links |
|--------|--------|
|  |  | 

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
    - [ ] For UI changes, have we tested the change in various languages (for example, ES, PT, FR, or DE)? The length of text and words vary significantly between languages. 
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Review by merkushin — COMMENTED** [review]
Tested with Titan only at the moment. Asked Bogdan on how to test with Google in private messages.

One question here: is this email list component used only in our new UI?

**Comment by bogiii** [comment]
> One question here: is this email list component used only in our new UI?

No, it is used in both contexts. That's why I introduced the `showContextMenu` flag, which is turned on only for the domain context.

**Review by merkushin — APPROVED** [review]
Eventually, tested with Google 😅 

Looks good and works as expected.

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/17080426

Some locales (Hebrew, Japanese) have been temporarily machine-translated due to translator availability. All other translations are usually ready within a few days. Untranslated and machine-translated strings will be sent for translation next Monday and are expected to be completed by the following Friday.

Thank you @bogiii for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/17080426).

**Pull request merged**
