### PR TITLE
Add Jetpack connect screen loading screens and minor UI update

### PR DESCRIPTION
**Pull request by chihsuan**
Related to https://github.com/Automattic/wp-calypso/issues/78267

## Proposed Changes

- Vertically center profile logo according to some texts Y5pUYSJPsGEud1vknUZhi8-fi-1911_36557

Screenshot 2023-06-27 at 14 11 47

- Implement loading screens in Jetpack connect Y5pUYSJPsGEud1vknUZhi8-fi-1911_36598

https://github.com/Automattic/wp-calypso/assets/4344253/6493f179-68ef-41f7-b688-904127c173a8

## Testing Instructions

**Logged-in users**

1. Set up [woocommerce-start-dev-env](https://github.com/woocommerce/woocommerce-start-dev-env)
2. Create a JN site and use the [latest woocommerce nightly build](https://github.com/woocommerce/woocommerce/releases/tag/nightly)
3. Go to Core Profiler flow 
4. Install plugins and confirm you're redirected to Jetpack connection page
5. Observe that it centers the profile icon with the first 2 lines only (Y5pUYSJPsGEud1vknUZhi8-fi-1911%3A36569)
6. Click on `Connect your account` button
7. It should show the loading screens and redirect you back to WooCommerce Home

**New users**

1. Set up [woocommerce-start-dev-env](https://github.com/woocommerce/woocommerce-start-dev-env)
2. Create a JN site and use the [latest woocommerce nightly build](https://github.com/woocommerce/woocommerce/releases/tag/nightly)
3. Go to /wp-admin/users.php
4. Create a new user with a new email that you will use to sign up later and assign the `Administrator` role to it
5. Open an incognito window
6. Go to your JN site and sign in with the user account you just created
7. Go to Core Profiler flow 
8. Install plugins and confirm you're redirected to Jetpack connection signup page
9. Fill out the signup form
10. Click on `Create an account` button
11. It should show the loading screens and redirect you back to WooCommerce Home

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

**Review by moon0326 — APPROVED** [review]
Nice work! LGTM and tested well 👍 🚀

**Comment by rjchow** [comment]
I'm seeing this with a logged in user after rebasing to latest trunk: 

image

Not really sure why the store card is missing?

**Comment by chihsuan** [comment]
> I'm seeing this with a logged in user after rebasing to latest trunk:
> 
> image
> 
> Not really sure why the store card is missing?

@rjchow Could you please confirm the "jpVersion" in your URL parameters?  I guess `jpVersion` param is missing. 


@ilyasfoo also encountered that issue, but I was not able to reproduce it. See:  https://github.com/Automattic/wp-calypso/issues/78615

**Review by ilyasfoo — APPROVED** [review]
Opening up a modal to show the loading is a creative solution, good thinking @chihsuan!

One thing however, I don't know if there are any instances where the connect would error, and now it might not be shown since modal is covering it. Is that a possibility we should consider?

Also, it seems no actual progress is being passed to  `WooLoader`. I may not understand the loading process 100%, but should we use actual loading instead of timer and intervals?

Anyway, this PR is tested well. Everything else can be addressed as a follow-up if necessary! 🚢 

> Could you please confirm the "jpVersion" in your URL parameters? I guess jpVersion param is missing.

@chihsuan This time around I wasn't able to reproduce it. My [URL](https://jetpack.wordpress.com/jetpack.authorize/1/?response_type=code&client_id=220674939&redirect_uri=https%3A%2F%2Fformidable-reindeer.jurassic.ninja%2Fwp-admin%2Fadmin.php%3Fhandler%3Djetpack-connection-webhooks%26action%3Dauthorize%26_wpnonce%3D969c2c1a33%26redirect%3Dhttps%253A%252F%252Fformidable-reindeer.jurassic.ninja%252Fwp-admin%252Fadmin.php%253Fpage%253Dwc-admin&state=1&scope=administrator%3A4107c7f44877319157c21d3d8bae6003&user_email=ilyas.foo%40automattic.com&user_login=demo&is_active&jp_version=12.2.1&auth_type=calypso&secret=wkHwdNWDywUmZh6TwpqNcuaYH1EzXiPs&blogname=Formidable+Reindeer&site_url=https%3A%2F%2Fformidable-reindeer.jurassic.ninja&home_url=https%3A%2F%2Fformidable-reindeer.jurassic.ninja&site_icon&site_lang=en_US&site_created=2023-06-28+12%3A41%3A30&allow_site_connection=1&_as=wp-cli&from=woocommerce-core-profiler&calypso_env=production) has `jp_version=12.2.1`. 

Edit: I was able to reproduce it again by deactivating Jetpack plugin before going through the core profiler. Probably not something we should address in this PR though.

image

**Comment by chihsuan** [comment]
Thanks for the review! @ilyasfoo

> One thing however, I don't know if there are any instances where the connect would error, and now it might not be shown since modal is covering it. Is that a possibility we should consider?

Actually, error will be shown because we only render the modal when `isAuthorizing` or `authorizeSuccess`. 🙂 

> Also, it seems no actual progress is being passed to WooLoader. I may not understand the loading process 100%, but should we use actual loading instead of timer and intervals?

Yes, I agree with you! It's not the best approach for now. I think we should rethink the design of the component. We can work on that when creating a reusable component.


> Edit: I was able to reproduce it again by deactivating Jetpack plugin before going through the core profiler. Probably not something we should address in this PR though.

Thanks, I was able to reproduce it this time. I think JP connect package doesn't set the `jp_version` value. However, I think we can skip that check for core profiler flow. Will work on that.

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/8069144

Thank you @chihsuan for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/8069144).

**Pull request merged**
