### PR TITLE
Update help center handling of external links

### LINKED ISSUE #64676: HelpCenter: make all article links open in new tab
### Details

Some of the buttons inside the articles open a new support article on the same page (external support page). Instead, we need to either:

1. Open them in the help center instead. (if we do this, I'm wondering what would happen with the "back" button. Assuming we would just go back to the initial "Help" screen as this is the simplest)
2. Open them in a new tab.

### Checklist

_No response_

### Related

_No response_

### PR DESCRIPTION
**Pull request by heavyweight**
Links from support articles that we show in the help center were opened on the same page.
This PR introduces a click handler which prevents the default behavior for links and opens them in a new tab.

#### Proposed Changes

* Parse article content links to open them in new tab

#### Testing Instructions
1. Navigate to the new help center
2. Open an Article. Example `What are "Blocks"?`
3. Click on some of the article's external links
4. Confirm that the links are opened in a new tab

Related to #64676

### CODE REVIEW

**Review by escapemanuele — DISMISSED** [review]
Thanks for working on this; it is indeed working in sending users to a new tab.

For now I'd say to ship this, in the future we'll investigate on ways to open the external articles inside the help center!

**Comment by heavyweight** [comment]
We were using a component for the articles that I didn't want to touch.
We can build upon @arcangelini work to post-process the content before displaying it https://github.com/Automattic/wp-calypso/pull/65329/files#diff-14bee4076e4a8d9372a8688206ea94f095828c552802a410d00b1c6d3623693eR16

**Review by escapemanuele — CHANGES_REQUESTED** [review]
Thanks @heavyweight  for working on this!

I think that internal links shouldn't be opened in a new tab tho!
https://user-images.githubusercontent.com/52076348/179230225-1ee06643-4ecb-466d-819c-27934fd5e1af.mp4

**Comment by renancarvalho** [comment]
Hi, @escapemanuele 

I have a new commit that should fix the external links / anchor issues.
Basically I have changed the selector to target only `<a>` with 'http/https' (this is why the * on the selector) on the href content. [Commit](https://github.com/Automattic/wp-calypso/pull/65231/commits/70f91c089e6c0a2b0afa8243a6f73f47174b6e0f)

**Review by escapemanuele — APPROVED** [review]
Wonderful, it all works and the experience is much better 🎸 🚀

**Pull request merged**
