### PR TITLE
Sidebar: Increase contrast of icons, labels, and buttons

### PR DESCRIPTION
**Pull request by shaunandrews**
sidebar color tweaks

### CODE REVIEW

**Comment by lsinger** [comment]
Code looks good to me. 👍

**Comment by folletto** [comment]
Design looks good! 👍 

Extra: I wonder what you think about the color mismatch on hover between icon and text that is there already in production. Worth fixing in this PR? Worth fixing at all?

screen shot 2018-02-14 at 10 58 17

**Comment by lsinger** [comment]
> color mismatch on hover between icon and text

Great catch! Let's address this in a separate PR.

**Comment by lsinger** [comment]
Talked to @shaunandrews — the difference between icons and text is on purpose. Leaving as is.

**Comment by kwight** [comment]
Reverting in https://github.com/Automattic/wp-calypso/pull/22464.

**Pull request merged**
