### PR TITLE
Jetpack Cloud Cart Integration - Update Cart styles to match the design

### PR DESCRIPTION
**Pull request by vikneshwar**
#### Proposed Changes
- Add a New Cart Icon component to override the default icon provided by masterbar
- Add a New Count component that renders the count next to the cart icon
- Fix styles inside the cart popover to match the design

#### Testing Instructions
*Note: [Figma Design](i45eiTwhKnMEnDtn86U6IR-fi-2993%3A32699&t=CdumeBBITUkseOx8-0)* 

* Make sure you are logged-in to WordPress.com 
* click on Jetpack Cloud live link below
* or boot up this PR 
    * Run `git fetch && git checkout fix/style-for-cloud-cart`
    * Run `yarn start-jetpack-cloud`
    * Goto http://jetpack.cloud.localhost:3000
* you will be presented with a landing page, asking you to select a site, choose any site from the list
* Once selected, you will be redirected to `/backup/:site-slug` page by default, replace `backup` with `pricing` and you should land in pricing page
* Now append this query string (`?flags=jetpack/pricing-page-cart`) to the end of URL to enable the cart and reload the page
* Make sure the cart shows up in the header
* Switch to Products section and confirm the following
    * Confirm that the cart icon in the header matches the design
    * Cart count should be hidden when there is no item in the cart
    * Now add any products to the cart
    * Click on the cart icon to open the cart popover and confirm that it matches the cart design
    * Also confirm that the cart count is updated to match the total items in the cart
    * Switch to mobile view and make sure it matches the design
    

#### Before
Screenshot 2022-12-16 at 2 56 45 PM

#### After
Screenshot 2022-12-16 at 2 55 50 PM

#### Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

Related to #

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - 0-as-1203534015891189
  - 0-as-1203534015891169

### CODE REVIEW

**Comment by keoshi** [comment]
I tried to test this by spinning up Jetpack Cloud live and going to `/pricing`, which led me to: https://container-nifty-kalam.calypso.live/pricing — cannot see the new elements and all the primary buttons lead me to the checkout directly.

Is there anything else we should be doing here, @vikneshwar? Maybe appending a flag to the URL? Could it be that the live link generator isn't spinning up this PR correctly?

Thank you!

**Comment by elliottprogrammer** [comment]
> Is there anything else we should be doing here, @vikneshwar? Maybe appending a flag to the URL? Could it be that the live link generator isn't spinning up this PR correctly?

@keoshi , Yes, I see the problem..  The feature-flag for the Calypso/Jetpack Cloud "live links" environment is **not on** by default. I'm not actually sure which one of those 2 files controls the "live link" environment (`jetpack-cloud-horizon.json`, or `wpcalypso.json`).

But in the meantime, yes, you could add `&flags=jetpack/pricing-page-cart` to the URL, and that should work. 👍

**Comment by keoshi** [comment]
Thank you @elliottprogrammer — still not seeing what I'm supposed to. This is the latest URL I was using: https://container-distracted-snyder.calypso.live/pricing?view=products&flags=jetpack/pricing-page-cart

**Comment by elliottprogrammer** [comment]
> Thank you @elliottprogrammer — still not seeing what I'm supposed to. This is the latest URL I was using: https://container-distracted-snyder.calypso.live/pricing?view=products&flags=jetpack/pricing-page-cart

Ahh, I see, also you need to have a site selected... This MVP version of this project ( p1HpG7-jvZ-p2 ) only shows the shopping cart to users that are logged-in **and** have a site selected (It's the flow coming from the plugin Jetpack dashboard, clicking on the "Plans" link/tab). Anyway, @vikneshwar please make sure your testing instructions work and are documented properly. You'll need to make corrections to this PR's instructions, as you can see.

@keoshi , my apologies. So in this case the site needs to be in the url also (site has been selected).  It will look like this: `https://container-name.calypso.live/pricing/{site_slug}/?view=products&flags=jetpack/pricing-page-cart` (note this `{site_slug}` in the url).

Easiest way to do this is to:
1. Make sure you're logged-in to wordpress.com
1. Click the cloud "live link" above: _Jetpack Cloud live_ (**direct link**)
1. You should see a site selection page, asking you to select a site. (You might first get a dialog asking you to Authorize/accept connection with wordpress.com, authorize it, of course). Select any Jetpack site you own.
1. Once you've selected a site, you'll be directed to the Backup page by default. Your url "path" should look like this: ` /backup/{site_slug}`.
1. Now, in the url, just replace `backup` with `pricing` instead.  Looking like this: `/pricing/{site_slug}` , and press enter.
1. Next, select "Products" from the "Products/Bundles" toggle button.
1. And finally, add/append the feature-flag to your url. Looking like this: `/pricing/{site_slug}?view=products&flags=jetpack/pricing-page-cart`
1. And follow the remainder of instructions.

**Comment by vikneshwar** [comment]
@keoshi @elliottprogrammer Apologise for not providing proper testing instructions there, I wrote those steps with some assumptions in mind, which I realised I shouldn't, I will make sure to provide proper testing instructions going forward.

**Review by elliottprogrammer — COMMENTED** [review]
The styles all appear good to me and match the figma design.

Just one issue: When the cart is empty, the red circle showing the product count (0) is still showing.  In the figma design, an empty cart does not have any red circle with "0" products.

Markup 2022-12-16 at 16 12 08

**Comment by vikneshwar** [comment]
@elliottprogrammer thanks for testing it. I have fixed the issue and also updated the styles for mobile view.

**Comment by ederrengifo** [comment]
Great job! A couple of comments:

- [x] The empty state for the cart doesn't match [the designs](https://www.figma.com/file/i45eiTwhKnMEnDtn86U6IR/Pricing-page%3A-Buy-multiple-products?node-id=2996%3A35132&t=ZTFpp8dLEnLkIQ5V-1). There are two things we proposed that I think are important for this use case: 1) We can provide instructions about how the cart works, and 2) It doesn't make much sense to include a checkout action when the cart is empty

Screen Shot 2022-12-19 at 10 01 16

- [x] Also, this empty state is displayed at the side in the mobile version

Screen Shot 2022-12-19 at 10 02 01

- [x] Also, in the mobile version, I noticed the cart uses all the screens. The position is fine, but we should use only what the content requires, so it can be clearer that it's a pop-up they can close and continue buying more things.

Screen Shot 2022-12-19 at 10 02 24

- [ ] One small thing, can we do something to avoid this button text in two lines?

Screen Shot 2022-12-19 at 10 02 15

cc @elliottprogrammer  @ilonagl

**Review by andrii-lysenko — APPROVED** [review]
It looks good to me codewise and works as expected. As long as the Design team is happy I think it can be shipped.

Great job!

**Comment by vikneshwar** [comment]
@ederrengifo I have updated the right design for Empty Cart. I have also added a bit of `box-shadow` to the cart container in mobile view, making it easy for the user to differentiate it as a popover. Regarding the Button text wrap, I will handle it as a separate PR once I am back from AFK. 

CC: @andrii-lysenko @elliottprogrammer

**Review by ederrengifo — APPROVED** [review]
LGTM! Thank you for all the adjustments!

**Pull request merged**
