### PR TITLE
Registrationless checkout: Handle page reload scenarios

### PR DESCRIPTION
**Pull request by niranjan-uma-shankar**
#### Changes proposed in this Pull Request

**This is one among a set of stacked PRs that implements userless checkout A/B test. For more reading on the userless
checkout project, read pau2Xa-1hW-p2.**

This PR implements the following:
* Implements routing updates so that the following scenarios are supported:
    - Log in to an existing account via the signup email validation link will save the cart from localstorage and render it.
    - If there's a payment error after account creation, then reloading the page will load the saved cart from localstorage.

#### Testing instructions

**NOTE: Depends on D45659-code, so please apply this first.**

**Scenario 1 - Log in to an existing account (that has only one site)**
* Navigate to http://calypso.localhost:3000/, set your locale/geo to EN-US, and assign yourself to variantUserless of userlessCheckout test and control of newSiteGutenbergOnboarding test.
* Begin at /start, select a paid plan and proceed to checkout
* In the email field in the Billing Info or Contact Info section, enter an email address that is tied to an existing wpcom account. * Clicking the "Continue" button will show an error - "Choose a different email address. This one is not available. If this is you log in now.". Click the "login in" link, and log in to an existing account.

Screenshot_2020-07-21_at_12_06_53_AM

* Confirm that the checkout page opens with the selected items in cart. Reload the checkout page and confirm that the items stay in cart.
* Clicking the X button in the masterbar should take you to /plans page:

Screenshot 2020-07-21 at 12 10 40 AM

**Scenario 2 - Log in to an existing account (that has more than one site)**
* Repeat the steps in Scenario 1, but log in to an account that has more than one site.
* After log in, you should see a site picker:
Screenshot 2020-07-21 at 12 07 15 AM
* Select any one site and verify that the checkout page opens with your selected items in cart. Reload the checkout page  and confirm that the items stay in cart.

**Scenario 3 - Continue transaction after log in on a site having a higher plan**

* Add a Personal plan to cart and proceed to checkout. 
* Enter an email that is tied to an existing wpcom account. Click "log in" on the email field validation message.
* Log in to an existing wpcom account that is on a Business plan.
* You should now see the checkout page render with the Personal plan in cart. If you try to complete the payment, you should get an error.

**Scenario 4 - Cancel PayPal transaction should open checkout page with items in cart**
* Go to /start/onboarding-new, add a plan to cart and proceed to the checkout page.
* Click on pay by PayPal and wait to get redirected to paypal.com
* Cancel the transaction on PayPal page to be taken back to WP.com.
* Verify that the checkout page opens, logged in to the account that was created with the email given in the checkout page, and with your selected items in cart.

**Scenario 5 - Reload page after payment error**
* Go to /start/onboarding-new, add a plan to cart and proceed to the checkout page.
* Pay by credit card by using a dummy credit card, to simulate a payment error(Use [this tool](https://saijogeorge.com/dummy-credit-card-generator/) to generate a dummy credit card number).
* You should be getting a "Transaction declined" message. 
* Reload the checkout page, and verify that you see the logged in checkout page with your selected items in cart.

**Scenario 6 - Purchase ecommerce plan**
* Go to /start and purchase an ecommerce plan.
* Verify that the purchase completes successfully, and that you are redirected to the Thank You page, and that Store is setup.

### CODE REVIEW

**Comment by DavidRothstein** [comment]
I did some testing with this pull request (since it seems to contain all the others) and I'm leaving all my comments here for simplicity, even though some of them may technically belong on the others.

Overall it seemed to work well and pretty smoothly.  Nice job!

1. I did not have much luck getting things to work after logging in as an existing user mid-checkout.  Typically what I saw was that the cart didn't seem to transfer to the logged-in user at all (I got redirected to the checkout URL after login, but then it just redirected me again to the plans page).  This happened both with a user who had multiple existing sites, and a user who had only one existing site.  Before that, in earlier testing, I was seeing different behavior though: The cart did persist, but not fully (it seemed to transfer my plan but not my domain).  Not sure what is going on -- let me know if you can't reproduce this, and I guess I can try to dig further and see if I can come up with exact steps.  But overall it seemed like something wasn't working there.

2. I was a little surprised that when logging in as an existing user, I only had the option to make the in-progress purchase on one of my existing sites (rather than also getting the option to create a new site).  This works especially badly if the user you're logging in as doesn't have any sites yet :)

3. http://calypso.localhost:3000/start/onboarding-new/domains has a "Back to My Sites" link at the top of the page, which doesn't make sense here.

4. There are some differences between the checkout experience in control and variant -- some look like bugs and some I'm not sure.  The variant is missing the close button and "Secure checkout" message at the top, has a confusing "Site: no-user" message, and is missing the help icon at the bottom (but has the reCAPTCHA notice in its place).  See screenshots below.

   **Control**
   control

   **Variant**
   variant

5. Clicking on the "Questions? Read more about plans and purchases" link in the sidebar doesn't do anything.  It's supposed to open up the help icon, so I guess this is related to the help icon being missing as noted in the above bullet point.

6. If you go to remove an item from the cart, you get a message whose text refers to your existing site, even though you don't have a site yet.  The screenshot below shows one example, but there are others depending on exactly what you're removing.  I guess this is confusing in the current checkout too (since people might not fully understand that they have a site at this point), but at least in that case they actually do.

   removing-plan

7. When entering an invalid coupon, I get a message saying "The FAKECOUPON123 coupon was successfully applied to your shopping cart", even though nothing was applied.  This doesn't happen in the control.

8. If you attempt to pay with an invalid credit card, then immediately try to pay with PayPal after the rejection, you get a "The requested shopping cart has no products for purchase" error message.  I'm guessing this has to do with something not being transferred correctly after the user account is created and the user is logged in.  This doesn't happen in the control.  This is probably a somewhat common scenario (user has a problem paying with their card so they try another payment method instead).

9. Enhancement: Ideally these users would be created as passwordless users on the server (the type who, when logging in later, automatically get sent a one-time login link to their email address as soon as they type in their email address on the login form).  Right now when they log in later we are showing them the password field by default, even though they don't actually have a password to type in.

10. Enhancement: It would be nice if we validated the email address (and told the user if it belonged to an existing account) as soon as they type it in.  (That's the way it works at https://wordpress.com/start/user currently.)  Right now, it's a bit annoying that you don't get that message until you've finished typing in all the domain contact details and submitted that section of the checkout form, especially since it's my understanding that the contact details won't transfer after login.  Also, when I did submit, it was a little unexpected to see a "We could not validate your contact information" error message at the top of the screen, when the only actual "error" was that I entered an existing email address and needed to log in.

**Comment by niranjan-uma-shankar** [comment]
Thanks for reviewing @DavidRothstein !

> I did not have much luck getting things to work after logging in as an existing user mid-checkout.

Woops, I had missed to push one of my local commits. This should be fixed in this PR.

> I was a little surprised that when logging in as an existing user, I only had the option to make the in-progress purchase on one of my existing sites (rather than also getting the option to create a new site). This works especially badly if the user you're logging in as doesn't have any sites yet :)

Good catch. I have fixed the case of logging in as a user who has no sites yet in a separate PR https://github.com/Automattic/wp-calypso/pull/44475. Regarding option to create a new site, that seems a bit complicated - do you have thoughts on where we can present the option to create a new site? If the user has more than one site, then the option to create new site could be in the site picker, but if they have one or no site yet, then how do we present this option? Do you think many users would run into this and maybe we can get away without implementing for an A/B test?

> has a "Back to My Sites" link at the top of the page

I pushed a fix for this in https://github.com/Automattic/wp-calypso/pull/44206

> The variant is missing the close button and "Secure checkout" message at the top

Fixed it in the PR https://github.com/Automattic/wp-calypso/pull/44456

> has a confusing "Site: no-user" message

Pushed a fix in https://github.com/Automattic/wp-calypso/pull/44209#issuecomment-665041825

> is missing the help icon at the bottom (but has the reCAPTCHA notice in its place)
Fixed in https://github.com/Automattic/wp-calypso/pull/44477. 

> Clicking on the "Questions? Read more about plans and purchases" link in the sidebar doesn't do anything.

Fixed in https://github.com/Automattic/wp-calypso/pull/44477. 

> When entering an invalid coupon, I get a message saying "The FAKECOUPON123 coupon was successfully applied to your shopping cart", even though nothing was applied. 

This is a bit strange. I see this success message only when a .live domain is one if the items in cart, otherwise a fake coupon does not get applied. E.g a plan + cctld domain, or just a plan in cart shows an error with a fake coupon. I need to dig into this. 

> If you attempt to pay with an invalid credit card, then immediately try to pay with PayPal after the rejection, you get a "The requested shopping cart has no products for purchase" error message

As you said, this is related to your first point and is now fixed in this PR.

> Right now when they log in later we are showing them the password field by default, even though they don't actually have a password to type in.

I'm not able to repro this. After purchasing a paid plan via this flow, if I sign out and log in once again, then I get the magic link sent to my email. Could you please let me know what steps you took to see this error?


I have two more pending things to look at - points 6 & 10 - which I will get to tomorrow :)

**Comment by niranjan-uma-shankar** [comment]
> When entering an invalid coupon, I get a message saying "The FAKECOUPON123 coupon was successfully applied to your shopping cart", even though nothing was applied.

Quoting my reply:

> This is a bit strange. I see this success message only when a .live domain is one if the items in cart, otherwise a fake coupon does not get applied. E.g a plan + cctld domain, or just a plan in cart shows an error with a fake coupon. I need to dig into this.

I found the same behaviour on wordpress.com pointing to my sandbox with no patches applied. So, at wordpress.com/start, if I select a .live domain, then in the checkout page, a fake coupon gets applied. I don't see this behaviour on production so looks like it's specific to sandbox environment. I infer from this that the issue is not introduced by my PR, so not looking into it further.

**Comment by nsakaimbo** [comment]
wp-desktop-source failure looks like a temporal outage of the yarn API:

`error An unexpected error occurred: "https://registry.yarnpkg.com/jest-diff/-/jest-diff-25.5.0.tgz: Request failed \"503 Service Unavailable\"".`

**Comment by niranjan-uma-shankar** [comment]
> Enhancement: It would be nice if we validated the email address (and told the user if it belonged to an existing account) as soon as they type it in. 

I agree this would be a nice enhancement but I'm siding towards not prioritizing it for this A/B test. If the test wins, then definitely :). Do let me know if you are okay with it.

**Comment by niranjan-uma-shankar** [comment]
> wp-desktop-source failure looks like a temporal outage of the yarn API:

Thanks for confirming that @nsakaimbo .

**Comment by DavidRothstein** [comment]
I did a bit more testing and it looks like most of the issues are fixed - nice!

>If the user has more than one site, then the option to create new site could be in the site picker, but if they have one or no site yet, then how do we present this option? Do you think many users would run into this and maybe we can get away without implementing for an A/B test?

It looks like you already solved the "no site" case in the other PR (by automatically putting them into checkout to create a new site) so that one is good.  For one or more, I think ideally we'd show them a site picker always, and the create site option would be in it along with whichever site or sites they do have.  But I agree we can probably get away with skipping this for an A/B test.  Existing users logging in via this flow will probably be pretty common, but I guess the most likely scenario is trying to buy a plan or domain on their existing site, and that is already covered.

>>Right now when they log in later we are showing them the password field by default, even though they don't actually have a password to type in.
>
>I'm not able to repro this.

You're right, I'm no longer able to reproduce this either.  Not sure what happened.

>I found the same behaviour on wordpress.com pointing to my sandbox with no patches applied. So, at wordpress.com/start, if I select a .live domain, then in the checkout page, I'm able to apply a fake coupon. I don't see this behaviour on production so looks like it's specific to sandbox environment.

Huh, yes - I can confirm that it seems to be specific to `.live` domain purchases in the sandbox environment.  I'm guessing it's because there's some long-running testing code to add a special one-year discount to `.live` domains in the sandbox environment, and that must be conflicting with the regular coupons.

For what it's worth, G Suite has at times in the recent past used the same one-year discount code in production (although not currently) so I wonder if the same bug with invalid coupons would apply in production for that.... But it's not easy to reproduce right now.  cc @sirbrillig though, if interested.

>>Enhancement: It would be nice if we validated the email address (and told the user if it belonged to an existing account) as soon as they type it in.
>
>I agree this would be a nice enhancement but I'm siding towards not prioritizing it for this A/B test. If the test wins, then definitely :). Do let me know if you are okay with it.

Agreed, sounds good.

**Comment by DavidRothstein** [comment]
FYI, while testing this on the latest branch that you mentioned (https://github.com/Automattic/wp-calypso/pull/44477) I saw an issue where I was unable to complete a purchase as an existing user.

If you go through checkout as an existing user and try to purchase, you get this red error message on the screen:

>Cannot destructure property 'createUserAndSiteBeforeTransaction' of 'transactionOptions' as it is undefined.

I realize it's probably not that PR that's causing it, but since I'm not sure offhand which one of the stacked PRs is, I'm just mentioning it here :)

**Comment by niranjan-uma-shankar** [comment]
> FYI, while testing this on the latest branch that you mentioned (#44477) I saw an issue where I was unable to complete a purchase as an existing user.

Fixed. It came out of a refactor in one of the earlier PRs yesterday - it happened if the site you're logging into has a saved card.

**Pull request merged**
