### PR TITLE
[WIP] Sites List: add Jetpack notifications notice 

### PR DESCRIPTION
**Pull request by retrofox**
### This PR depends on #8157

This PR suggests adding a `<Notice />` component when the current site has Jetpack updates. The idea is to improve the information that we are offering to the user.
Thus if we have only one update let's show just a single link trying to reduce the steps to updates the site. But on the other hand, if there are many updates let's show these ones through a `<Popover />` component anchored to the `<Notice />`.

This feature is conditioned to the `gm2016/jetpack-plugin-updates-trashpickup` flag. So to enable Jetpack notifications to make sure to run calypso enabling it;

``` cli
> ENABLE_FEATURES=gm2016/jetpack-plugin-updates-trashpickup make run
```

image

image

Clearly, it's in `WIP` state and needs a design review. cc @rickybanister.

~~Also, this one depends on other PRs: #8125 #8126~~

To test you'll need a connected Jetpack site with out of date core / themes / plugins. The WP Rollback plugin is helpful for testing.

### CODE REVIEW

**Comment by retrofox** [comment]
Issues

- [ ] Direct message for only one update
- [ ] Update WP core
- [ ] Hide update circle when the Notice is shown
- [ ] Create and conditionate these features to `gm2016/jetpack-plugin-updates-trashpickup` flag.

**Comment by rickybanister** [comment]
Updated design:

screen shot 2016-09-20 at 10 23 18 am

**Comment by lancewillett** [comment]
Re-ping @retrofox 

(This came up in a search for pull requests pending without an update in last 2 months.)

**Comment by rickybanister** [comment]
Thanks for checking on these @lancewillett. I'm going to get them wrangled, updated, and merged if possible.

**Comment by alisterscott** [comment]
Closing as this PR is stale - please reopen if necessary

**Pull request closed without merging**
