### PR TITLE
Design Choices: Update illustrations

### PR DESCRIPTION
**Pull request by arthur791004**
Related to https://github.com/Automattic/wp-calypso/issues/86035

## Proposed Changes

* Update illustrations and reduce the size of images

### Screenshots
| Before | After |
| - | - |
| image | image |

### Sizes

**Before**

image 

**After**

image

## Testing Instructions

* Go to /setup?siteSlug=your_site
* Continue
* Make sure the Design Choices step looks as expected

## Pre-merge Checklist

- [x] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [x] https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md for your changes?
- [x] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [x] Have you checked for TypeScript, React or other console errors?
- [x] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [x] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [x] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

**Comment by matt-west** [comment]
There was a stroke around shot of the Yuga theme which is causing it to have a soft edge and look a bit fuzzy. I’ve removed this now. Can you please update the image using this design: Tv3pYqA3EcRfiXC31IxrXE-fi-3607_5661

**Review by taipeicoder — APPROVED** [review]
👍 
Screenshot 2024-01-11 at 5 43 57 PM

**Comment by arthur791004** [comment]
> There was a stroke around shot of the Yuga theme which is causing it to have a soft edge and look a bit fuzzy. I’ve removed this now. Can you please update the image using this design: Tv3pYqA3EcRfiXC31IxrXE-fi-3607_5661

Updated 🙂

**Comment by matt-west** [comment]
Thanks @arthur791004. 

@autumnfjeld asked for another pass on this (Tv3pYqA3EcRfiXC31IxrXE-fi-3231:4183#663982404). Awaiting feedback on the latest iteration.

**Pull request merged**
