### PR TITLE
Update/reader card excerpt

### PR DESCRIPTION
**Pull request by davemart-in**
## Proposed Changes

Update line clamping for Reader cards excerpt content.

### Before

CleanShot 2022-09-01 at 12 30 22@2x

### After

CleanShot 2022-09-01 at 12 30 46

## Testing Instructions

- Pull up the reader main feed
- Review that line truncation consistently happens after 2 lines.

## Steps I took in this update

- Remove `isDiscover` conditional in ReaderExcerpt component
- Remove `long-content-fade` css include (since it's not really doing anything
- Use san serif font for excerpt
- Default to `post.content_no_html` for excerpt text (as p tags will break up the content in inconsistent ways otherwise)
- Remove max-height CSS restriction (which makes line clamping much harder to deal with)
- Remove manually added "..." from `post.short_excerpt`
- Add line clamp CSS to `.reader-post-card.card .reader-excerpt` (2 lines max)
- Remove outdated line clamp CSS from `.reader-related-card__excerpt`
- Add new line clamp CSS to `.reader-related-card__excerpt` (2 lines max)

Related to #66619 & #66650

### CODE REVIEW

**Comment by jordesign** [comment]
Looks good to me! 

Only comment/question would be whether we need to allow more than 2 lines of excerpt on smaller screen sizes? 
It feels a little cramped/short on content when there is a single image - but this may be resolved once the media files are appearing full width across the top anyway?

Screen Shot 2022-09-02 at 6 41 36 am

**Comment by davemart-in** [comment]
@jordesign yep, we should get about twice that content once the images/videos are full width. Here's a preview of what it will look like:

CleanShot 2022-09-02 at 08 00 54@2x

This code change should adapt and maintain just 2 lines of code with an ellipsis at the end once that happens.

**Review by eoigal — APPROVED** [review]
LGTM

**Comment by davemart-in** [comment]
Merged into #66650

**Pull request closed without merging**
