### PR TITLE
Gutenberg: Placeholder PR for testing 6.8.0 on Horizon.

### PR DESCRIPTION
**Pull request by kwight**
For e2e testing – **DO NOT MERGE**.

### CODE REVIEW

**Comment by kwight** [comment]
Re-run tests for 6.8.0-rc.1, now on Horizon.

**Comment by mmtr** [comment]
Rebased the branch to solve the `session not created: This version of ChromeDriver only supports Chrome version 76` errors.

**Comment by mmtr** [comment]
Re-triggering tests after updating Horizon to 6.8.0 final

**Comment by mmtr** [comment]
Failing tests seems to be unrelated to Gutenberg 6.8.0

**Comment by kwight** [comment]
6.8.0 final is now in production.

**Pull request closed without merging**
