### PR TITLE
Untangling: Add Settings -> Caches subtab

### PR DESCRIPTION
**Pull request by fushar**
Fixes:

- https://github.com/Automattic/dotcom-forge/issues/9616

## Proposed Changes

This PR adds the Settings -> Caches under the `untangling/hosting-menu` flag.

image

The setting comes from Server Settings -> Performance Optimization card.

## Why are these changes being made?

pbxlJb-6ye-p2

## Testing Instructions

1. Go to /sites
2. Click an Atomic site
3. Go to Settings -> Caches subtab.
    - Verify that this setting is working.
5. Click a Simple site from the site list
    - Verify that this setting is not available.
7. Regression testing:
    - Go to Server Settings
    - Verify that the original Performance Optimization card is still working.

## Pre-merge Checklist

- [x] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [x] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [x] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [x] Have you checked for TypeScript, React or other console errors?
- [x] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [x] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [x] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Review by taipeicoder — APPROVED** [review]
LGTM!

There's a minor issue where if,
 
I'm on an Atomic site
Screenshot 2024-11-07 at 12 07 56 PM

Then I switch to a Simple site, I stay in the Cache tab
Screenshot 2024-11-07 at 12 08 02 PM

Then I switch to the Administration tab, and the Cache tab disappears
Screenshot 2024-11-07 at 12 08 12 PM

Non-blocking and we can address this in the future.

**Comment by fushar** [comment]
> Then I switch to a Simple site, I stay in the Cache tab
> Then I switch to the Administration tab, and the Cache tab disappears

It's the current behavior. We currently prefer showing a tab even though it's not supported, to avoid surprises. We should discuss whether to show the unsupported tab (maybe we upsell), or to redirect to /overview.

I'll discuss with Lucas later after we've moved all the subtabs.

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/16991264

Some locales (Hebrew, Japanese) have been temporarily machine-translated due to translator availability. All other translations are usually ready within a few days. Untranslated and machine-translated strings will be sent for translation next Monday and are expected to be completed by the following Friday.

Thank you @fushar for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/16991264).

**Pull request merged**
