### PR TITLE
A4A: Add the 'Growth Accelerator' card on the Overview sidebar.

### PR DESCRIPTION
**Pull request by jkguidaven**
This pull request involves the implementation of the Growth Accelerator card, which will be added to the Overview sidebar page. This new feature aims to provide users with a tool to boost their growth and productivity within the application.

Screenshot 2024-10-08 at 7 13 30 PM

Related to https://github.com/Automattic/automattic-for-agencies-dev/issues/1082

## Proposed Changes
* Implement the OverviewSidebarGrowthAccelerator card and add it to the Overview sidebar.
* Make the new card dismissible based on the `a4a_growth_accelerator_dismissed` preference.
## Why are these changes being made?

* This allows the users to schedule a 'Growth accelerator' session with our support team speeding up the process.
## Testing Instructions

* Use the A4A live link and go to the `/overview` page.
* Confirm that you see the 'Growth Accelerator' card.
* Confirm that the CTA button redirects to the correct link.
* Confirm that Clicking the 'Not interested' button dismisses the card.

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Comment by jeffgolenski** [comment]
Thanks James!

Just noting that @madebynoam is going to take a pass at making it a little more visually interesting. 

In terms of logic, please make the following changes:

- [ ] Remove background color behind "I'm not interested" on hover

p1728404940985929-slack-C07J433JXAT

- [ ] Change "I'm not interested" to "dismiss."  pfunGA-35w-p2#comment-5678, let's keep this cta visible until the user manually dismisses it. Otherwise we'd have to build in some complex logic.

**Review by jeffgolenski — CHANGES_REQUESTED** [review]
Few functionality changes mentioned in the convo. Note, Noam will be advancing the design a little bit visually, but the function won't change.

**Comment by jkguidaven** [comment]
> Thanks James!
> 
> Just noting that @madebynoam is going to take a pass at making it a little more visually interesting.
> 
> In terms of logic, please make the following changes:
> 
> * [ ]  Remove background color behind "I'm not interested" on hover
> 
> CleanShot 2024-10-08 at 12 52 00
> 
> * [ ]  Change "I'm not interested" to "dismiss."  per your feedback here: pfunGA-35w-p2#comment-5678, let's keep this cta visible until the user manually dismisses it. Otherwise we'd have to build in some complex logic.

Thanks for the review, @jeffgolenski. I added some changes to address your feedback.

> Few functionality changes mentioned in the convo. Note, Noam will be advancing the design a little bit visually, but the function won't change.

Is this something we will tackle as well in this PR, or can we do a follow-up to update the visuals?

**Review by simonktnga8c — APPROVED** [review]
Looks great! Works as expected, thanks!

**Review by cleacos — APPROVED** [review]
The code looks good.

**Comment by jeffgolenski** [comment]
@jkguidaven A follow up PR is fine! Let's ship and move on!

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/16899371

Some locales (Hebrew, Japanese) have been temporarily machine-translated due to translator availability. All other translations are usually ready within a few days. Untranslated and machine-translated strings will be sent for translation next Monday and are expected to be completed by the following Friday.

Thank you @jkguidaven for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/16899371).

**Pull request merged**
