### PR TITLE
Framework: Minify CSS

### LINKED ISSUE #20472: Framework: Minify CSS
We are not minifying bundle CSS, we should be doing this.

### PR DESCRIPTION
**Pull request by lamosty**
Fixes #20472.

I found out that we can just add `--output-style compressed` to the `node-sass` module and it will produce minified CSS. I compared it with https://csscompressor.net/ and the produced minified CSS file was around the same size (we also run it through `postcss` which adds a bit more code).

## Savings

- `style.css` went from 1.4 MB to 1.1 MB which is about 22% improvement;
- `directly.css`: 26 KB -> 22 KB;
- `post-editor.css`: 148 KB -> 122 KB;
- `signup.css`: 42 KB -> 33 KB;
- `site-settings.css`: 46 KB -> 38 KB;

I'm not minifying `style-debug.css` since that's running only in dev environment.

## Testing

I think we should test by running Calypso in a different environment than dev and then browse through it, if it behaves normally:

```
ENV=wpcalypso npm start
```

### CODE REVIEW

**Comment by stephanethomas** [comment]
Do we want to do the same for stylesheets from [extensions](https://github.com/Automattic/wp-calypso/blob/0704a4d145f7438ae7645a7876c724285253e0c0/bin/process-extensions-scss.js#L37-L43)?

**Comment by lamosty** [comment]
> Do we want to do the same for stylesheets from extensions?

Great point! Added in b8ea805. Woo went down to 187 KB from 234 KB. Woo!

**Comment by gwwar** [comment]
Also verified that we can still make hotloaded CSS changes in dev.

**Comment by gwwar** [comment]
A follow up issue may be to cache the google api font values, so we can minify it ourselves. 

eg we see requests like, that return unminified CSS
https://fonts.googleapis.com/css?family=Noto+Serif:400,400i,700,700i&subset=cyrillic,cyrillic-ext,greek,greek-ext,latin-ext,vietnamese

**Comment by apeatling** [comment]
@lamosty Great work! When this is merged, could you follow up with a final calculation for total reduction in the gzipped CSS size? Thanks.

**Comment by DanReyLop** [comment]
@lamosty I suggest taking a look at `cssnano`, which is a PostCSS module: http://cssnano.co/

Should be easy to add. In any case, compressing the CSS files should be the last step in their processing, running `autoprefixer` and other `postcss` transforms on them after they are compressed seems suboptimal (altough probably won't make a huuuge difference).

So, the ideal order of operations should be: `node-sass x.scss && autoprefixer && other_postcss_transforms && cssnano` (since `cssnano` is also a `postcss` transform it can be combined with the othera and that would make the process faster too).

**Comment by lamosty** [comment]
@apeatling:
> Now this is merged, could you follow up with a final calculation for total reduction in the gzipped CSS size? Thanks.

I'm trying to get the gzipped CSS sizes before the reduction but I'm unable to do so. Problem is that even if I run Calypso in Docker, the gzipping doesn't happen. We probably do that only on WP.com backends. I also tried using `calypso.live` with some branch that was created earlier than this but it serves the debug version of CSS and not gzipped as well.

I can tell you that now, the main gzipped `style.css` file on prod has 168 KB.

@DanReyLop:
> I suggest taking a look at cssnano, which is a PostCSS module: http://cssnano.co/

Thanks for the suggestion. I installed `cssnano` locally and did some experiments. The final size of CSS files were almost exactly the same as when using `node-sass`. It's probably due to the fact that even if we run `autoprefixer` or other postcss modifications on the minified CSS file, they have the same AST and so don't unminify the file after the transformations.

It would be quite straightforward to add `cssnano` to our `package.json` file but doing it for the Calypso extensions (like Woo) would be probably a bit more complicated. 

Is it worth the effort re-doing CSS minification or can we just keep it like it was done last week for now?

**Comment by DanReyLop** [comment]
> It's probably due to the fact that even if we run autoprefixer or other postcss modifications on the minified CSS file, they have the same AST and so don't unminify the file after the transformations.

Makes sense, good to know that a `postcss` transformation doesn't "unminify" minified CSS :)

> Is it worth the effort re-doing CSS minification or can we just keep it like it was done last week for now?

If the result is almost the same, then no, it's not worth the effort for now. Thanks for taking a look :)

**Pull request merged**
