### PR TITLE
Site Dashboard: Removing SitePreviewPaneTabs and replacing with SectionNav and NavTabs

### PR DESCRIPTION
**Pull request by coder-karen**
Related to https://github.com/Automattic/automattic-for-agencies-dev/issues/52

## Proposed Changes

* This PR removes the SitePreviewPaneTabs and replaces them with SectionNav and NavTabs components. This is to meet design requests.
* This PR also modifies the style of the navigation dropdowns for smaller screens to match design specs.
* This PR includes a fix for mobile displays as well where the sites overview section was dsiplaying when it shouldn't.

Additional Figma file reference for mobile views: J7ZbWnnIYpC2THVlktTM23-fi-4717_218380

## Testing Instructions

For the below testing steps, make sure to run `yarn start-a8c-for-agencies` locally and then visit `http://agencies.localhost:3000/sites`.

* In testing, the site preview pane navigation should match what it was before.
* However there is one change, and that is that on mobile screens the navigation becomes a dropdown. This matches previous design specs, available from the Figma link above.

**Screenshots**

Dropdown navigation in preview pane:

Screenshot 2024-03-19 at 18 25 02

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Review by cleacos — COMMENTED** [review]
image

The search box lost the padding. Trunk:

image

**Comment by cleacos** [comment]
Also I see the normal navbar in the side-by-side:

image

**Comment by cleacos** [comment]
In medium screen size, I see the tab selector:

image

image


It should be activated in mobile screen.

**Comment by cleacos** [comment]
See the space between the selectable tabs and the content on small screens:

image

**Comment by coder-karen** [comment]
Thanks @cleacos , I'm hoping the last commit caught these remaining issues. Let me know if you still see them. As we discussed, we can create an issue for the SectionNav appearing on smaller screens when it shouldn't (appears related to the Preview Pane and how it appears - clicking between sites and tabs immediately fixes the issue).
Edit - issue here: https://github.com/Automattic/automattic-for-agencies-dev/issues/118

**Comment by cleacos** [comment]
> As we discussed, we can create an issue for the SectionNav appearing on smaller screens when it shouldn't (appears related to the Preview Pane and how it appears - clicking between sites and tabs immediately fixes the issue).
> Edit - issue here: https://github.com/Automattic/automattic-for-agencies-dev/issues/118

Thank you!

**Comment by cleacos** [comment]
It works for me, except for the known issue with the SectionNav and its code to determine if it renders the mobile view (dropdown menu) or the tabs bar.

**Comment by cleacos** [comment]
The issue with the SectionNav is a bit random... not easy to replicate and to fix, since the`NavTabs` calculate the`window.innerWidth` size to decide if it displays the dropdown menu or the normal tabs bar.

**Review by cleacos — APPROVED** [review]
LGTM!

Let's address the issue with the NavSection in the follow-up PR

**Pull request merged**
