### PR TITLE
Nav Redesign i2: Link style consistency

### PR DESCRIPTION
**Pull request by taipeicoder**
Fixes https://github.com/Automattic/dotcom-forge/issues/7136

## Proposed Changes

As described in https://github.com/Automattic/dotcom-forge/issues/7136#issuecomment-2118131281, this PR updates the links in /sites, /domains, /read, and /profile by making links without underline and blueberry colored.

## Why are these changes being made?

Consistency amongst global pages.

## Testing Instructions

* Head to /sites, /domains, /read, /profile.
* Ensure that links don't have text underline and have the color blueberry. 

## Pre-merge Checklist

- [x] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [x] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [x] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [x] Have you checked for TypeScript, React or other console errors?
- [x] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [x] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [x] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Review by dsas — COMMENTED** [review]
I think there are a couple more changes (missing underlines) needed on the hosting config tab.

Screenshot 2024-05-15 at 10 42 20

**Comment by taipeicoder** [comment]
> I think there are a couple more changes (missing underlines) needed on the hosting config tab.
> 
> Screenshot 2024-05-15 at 10 42 20

Nice, added to the list in the issue description!

**Review by dsas — COMMENTED** [review]
I found some more, sorry! If you expand the "What is SFTP", "What is SSH" and "What is phpMyAdmin" sections of Hosting Config they contain links to support docs and are all missing underlines.

**Comment by lucasmendes-design** [comment]
I'm in sync with the design team to check the correct link style. I'll get back to this!

**Comment by taipeicoder** [comment]
@lucasmendes-design @davemart-in I've updated the links in /sites, /domains, /profile, and /reader. Most of them are straightforward, but the following needs some input:

`/me/purchases/`
| Current | What it would look like |
| --- | --- |
| Untitled 2 | Untitled |

`/tag/:tag`
| Current | What it would look like |
| --- | --- |
| Screenshot 2024-05-21 at 2 31 07 PM| Screenshot 2024-05-21 at 2 13 06 PM|

`/hosting/:site`
| Current | What it would look like |
| --- | --- |
|Screenshot 2024-05-21 at 2 14 20 PM|  Screenshot 2024-05-21 at 2 14 37 PM|

`/sites`
| Current | What it would look like |
| --- | --- |
| Screenshot 2024-05-21 at 2 14 11 PM|Screenshot 2024-05-21 at 2 15 46 PM|

**Comment by davemart-in** [comment]
Yeah, this was what I was worried about if we weren't explicit about which links should be updated. Thanks for taking a pass at this and for calling all of these out @taipeicoder for further review! 

I'll let @lucasmendes-design weigh in with his thoughts on each of these.

**Comment by lucasmendes-design** [comment]
Hi folks, sorry that I couldn't share these things yesterday. 

`/me/purchases/` - I'm fine with this one.

`/tag/:tag` - Also fine. This is very similar to /support

`/hosting/:site` - We already have the icon so we don't need the blueberry color here. But we can keep the blueberry color on hover. 

`/sites` - Same as above. Let's remove the blueberry color and keep it only on hover.

**Pull request merged**
