### PR TITLE
Use fetch for maybeRefreshCountryCodeCookieGdpr.

### PR DESCRIPTION
**Pull request by sgomes**
`maybeRefreshCountryCodeCookieGdpr` was using `superagent`, a 3rd party NPM package for handling asynchronous requests. This PR reimplements its functionality using the native `fetch`.

This is part of an effort to remove `superagent` from client code altogether, and replace it with native `fetch` functionality. This will eventually lead to being able to drop that dependency from the client-side bundle, thus improving loading performance.

#### Changes proposed in this Pull Request

* Rewrite `maybeRefreshCountryCodeCookieGdpr` using `fetch`.

#### Testing instructions

* Ensure that the `country_code` cookie continues being correctly updated.

### CODE REVIEW

**Comment by sgomes** [comment]
Hey @MicBosi, any chance of a quick look at this? Let me know if I should be adding someone else instead!

**Comment by sgomes** [comment]
Added remaining recommended reviewers.

**Comment by sgomes** [comment]
Rebased on master.

**Review by jaswrks — APPROVED** [review]
Tests well, thanks!

- Trackers still working.
- Cookie banner still working.
- `country_code` cookie still being set.

LGTM 🚢

**Comment by sgomes** [comment]
Thanks for the review, @jaswrks ! 🙂

**Comment by MicBosi** [comment]
Thanks @sgomes and @jaswrks for the review. 

Looks great! I always wondered what the best way of doing those type of requests is, I'm glad we are officially moving away from `superagent`, although it's a nice little library, having a native solution sounds like the better way.

Sorry for not replying in time, your ping got lost in the sea of notifications. I've updated my filters to better capture when my name is explicitly mentioned.

**Pull request merged**
