### PR TITLE
Store: Use Checklist component for dashboard.

### LINKED ISSUE #18825: Store: Incorrect styling of Dashboard checkmarks in Safari
From the Store Dashboard in Safari (10.1.1):

Black checkmark circles on Dashboard

Looks like the [following rule](https://github.com/Automattic/wp-calypso/pull/17317/files#diff-147e46b60c9879428873057a18248220R100) is taking precedence over the `$alert-green` due to its greater specificity:
```scss
	.dashboard__setup-task-status:not(.dashboard__setup-task-status .gridicon){
		background-color: black;
		color: black;
	}
```

My thought is: if the intent is to make it `black` except if it contains a `.gridicon`, that's not possible to encode in CSS as such I don't think, but as written it basically means "status div that isn't also a gridicon that's the child of another status div". We can revise this rule and/or tweak the specificity so that the green shows up.

### LINKED ISSUE #21322: Store - update set up checklist to use Checklist component
Not a high priority item right now, but something we should do at some point is update our Store setup checklist to use the [Checklist Calypso component](https://wpcalypso.wordpress.com/devdocs/design/checklist).

### PR DESCRIPTION
**Pull request by timmyc**
This branch closes #21322 and also fixes #18825 by removing the existing dashboard checklist component, and replaces it with the `<Checklist />` component instead: 

__Before__
dash-before

__After__
dashboard-setup

Some of the noticeable changes of using the `<Checklist />` component is as you finish items in the checklist, they move to the top of the list, instead of staying in their original spot. Also the 'DO IT' button is kind of _interesting_. We could consider updating the base component to allow for a custom button text:

in-progress

__To Test__
The easiest way to test out the setup checklist is to use the REST API console [https://developer.wordpress.com/docs/api/console/](https://developer.wordpress.com/docs/api/console/) to reset the preferences to the initial install state using the `/sites/$site/calypso-preferences/woocommerce` endpoint. A fresh install has values that look like so:

new-site-settings

Once you have reset your settings, you can then interact with the setup checklist and verify it works as expected.

### CODE REVIEW

**Comment by jameskoster** [comment]
> Also the 'DO IT' button is kind of interesting.

_Interesting_ indeed haha :D 

I think the steps moving upon completion is fine, but yeah, that button text needs attention.

**Comment by ryelle** [comment]
@timmyc Are you planning on fixing the accessibility of the core Checklist component, or would you want me to take a look at that? A quick look shows some poor contrast with the light grey text (and even less contrast in the completed actions), and unclear focus states. You could try out [the new Accessibility Checklist](https://github.com/Automattic/wp-calypso/blob/5a56447bc185862e5ca85930f884703c6b57af48/docs/accessibility-checklist.md) before we properly merge it 🙂

**Comment by timmyc** [comment]
> Are you planning on fixing the accessibility of the core Checklist component

@ryelle I totally forgot about that bit of the task. Since it appears we need a new prop in the task to allow us to modify the default "DO IT" button text, maybe we can get a PR going to add that in and address the accessibility issues too. Are you keen to work on that? If not I'll roll with it, but sounds like you have a good understanding of what needs to be fixed in that regard.

**Comment by ryelle** [comment]
Sure, I can work on that this afternoon. Just to be clear: a _new_ PR to add a prop for the button text, and fix the accessibility things?

**Comment by timmyc** [comment]
@ryelle yeah I think a separate PR would be better. I can wait on that and rebase this one once it lands.

**Comment by timmyc** [comment]
Thanks to @ryelle we can now have custom button text, and better a11y! Here is an updated screenshot:

new-buttons

@kellychoffman any changes to the button text - or time/minute estimates?

**Comment by kellychoffman** [comment]
Very nice! Do we have the ability to make the buttons `Primary`?

**Comment by timmyc** [comment]
@kellychoffman I added primary button support to the checklist in c76199a

primary-buttons

@justinshreve I could not re-create the issue myself:

dashboard-skip

**Comment by kellychoffman** [comment]
There's some funky things happening at the bottom of the checklist card. I think deleting the top border on the `setup__footer` should fix it. Otherwise, let's :shipit:. 

screen shot 2018-03-13 at 1 05 04 pm

**Pull request merged**
