### PR TITLE
Comments: Add a Pagination component

### LINKED ISSUE #15016: Comments: add simple paging
We should implement simple paging for comment moderation prev/next, from newest to oldest. Currently, we only load a small set of comments when visiting this section.

cc @drw158 if you had anything more specific in mind

### PR DESCRIPTION
**Pull request by Copons**
Closes #15016

Add a [`Pagination` component](https://github.com/Automattic/wp-calypso/tree/master/client/my-sites/stats/pagination) to the Comment Management.

The current comments per page value is `20` (the default in wp-admin).

I've decided to use the ready made `Pagination` component instead of going custom with `SegmentedControl` because after trying it, it actually looks better than I expected.
If we want to change its design, I'd say it's better to change the style instead of writing from scratch a component that already exists.

The gif is 1 comment per page for demo purposes only.

jul-03-2017 18-14-28

### CODE REVIEW

**Comment by drw158** [comment]
Hm how do you test? I'm not seeing it on the live branch.

**Comment by gwwar** [comment]
@Copons do you mind adding a temporary commit, so @drw158 can see this in action. Maybe like 3 comments per page?

**Comment by Copons** [comment]
@gwwar @drw158 Ouch I didn't realize it was untestable - even though I've mostly tested with 1 comments per page myself! :D
Lowered to 2 per page, should be enough.

**Comment by gwwar** [comment]
UI wise I'm liking it 👍 . @Copons @drw158 how do you feel about exposing the page as a parameter, so this is bookmarkable?

**Comment by drw158** [comment]
Looks good, I think the design is fine for now. Addressing the design will require consideration of Stats as well. This should be a generic component in devdocs though!

Bulk edit seems to work as expected aside from:

- When I select multiple comments across many pages, and then Approve with bulk edit, I get the "No comments" message even though I didn't approve all of them. If I change filters and come back, the view is displayed correctly.
- Weird issue that is not really a bug, but when you select multiple comment across many pages, the top checkbox is empty, even though comments are selected on the page. Not sure what what would be the expected behavior here.

screen shot 2017-07-03 at 4 43 25 pm

**Comment by Copons** [comment]
Back into WIP status, I didn't consider the bulk part. :/

**Comment by Copons** [comment]
@drw158 That behaviour was unintended, caused by me not wiring up the pagination with the navigation component too.
I believe that users should **not** be allowed to select comments across multiple pages.

Let's see for example how Gmail handles it.
You can select comments across multiple pages, but when you perform an action, it's applied **only to the selected comments in the current page**. Then, when you navigate to another page containing selected comments, you'll see those comments still selected.
In a sense, it's more a system that remembers selected comments, than a multipage bulk action.

This in my opinion is a confusing behaviour, some sort of middle ground that would inevitably make someone unhappy.
Conversely, it's much more clear, transparent and obvious to the user to **automatically deselect all comments upon page change**.

**Comment by Copons** [comment]
@mtias The main reason here is that comments have bulk actions, and they don't work well with infinite lists.

Off the top of my head:
- Infinite lists literally can't have a "select all" button.
- Doing an action on _many_ selected items could be extremely bad performance-wise (like, easily killing the remote site).
- Also, Comments Management is a _management_ section, and paginated lists are more "predictable" than infinite ones.

**Comment by gwwar** [comment]
>  I wonder about when it's appropriate to use this compared to relying on infinite lists.

+1 to @Copons notes.

Personally I think, infinite lists are great for consuming content, not managing it. I run into trouble with the post list too, since if I want to look for an old post I'm forced to use search instead of being able to quickly page through items.

**Pull request merged**
