### PR TITLE
Global plugins marketplace - fix layout breakage due to pugins browser container and section component.

### PR DESCRIPTION
**Pull request by Addison-Stavlo**
Related to # Automattic/dotcom-forge#8272

## Proposed Changes

* Removes these`::before` pseudo element styles from the `.plugins-browser__main-container` and `<Section>` component used by the Marketplace Footer while at the global level.
    * The former is removed by changing the SCSS selector from `&::before` to  `.theme-default:not(.is-global) &::before`.
    * The latter style is applied via emotion/styled, which doesn't seem to support parent element selector chains like the above example. So here I have had to add an extra property to the section component and its styled component. The `hideBackgroundElement` prop ensures we do not apply the pseudo styles, and we apply this at the `MarketplaceFooter` component level based on the `getShouldShowGlobalSidebar` selector.

BEFORE - content frame loses top padding and gains bottom padding once loading into the plugin (and back at the main list as well)

global-plugin-layout-break

AFTER - content frame is stable.

global-plugins-good

NOTES

1. It looks like these pseudo elements were used to apply background colors to these sections, outside of the margins they are constrained to. This absolute positioning seems to break the layout of the global frame. They are not applying any background in the global area currently either. We can just remove them from there.
2. Im not thrilled about needing to add extra props here. I would like to just restrict via parent selectors like in the SCSS file, but the styled components do not seem to support this? I may be missing a way to do this from the styled component instead.
3. Im not 100% sure why this absolute positioning breaks the vertical layout of the content frame. But it clearly seems to be the culprit.

## Why are these changes being made?

* There is a bug at the global plugins marketplace where the layout breaks when going back and forth between the plugins list and individual plugins pages. This seems to be due to the absolutely positioned pseudo elements. This seems to happen only after the first render as it does not appear on load, but once these elements are later added or removed from the layout.

## Testing Instructions

* Go to the global view
* Select plugins
* Click into a plugin (I am using yoast as seen in the video above)
    * I noticed in testing this not all individual plugin pages seem to cause this. So on production, find a plugin such that when you click into it the above layout breakage is observed. Use this plugin in testing this PR.
* Verify the layout is not broken.
* Go back to the main plugins broswer. Verify the layout is still not broken.
* Visit the plugins page while logged out. Verify there are no changes from production.
* Visit the individual site level plugins page (the site sidebar visible at my home -> plugins). Verify there are no changes from production.

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Comment by Addison-Stavlo** [comment]
> NOTES
> *  I am not sure why we have these pseudo elements in the first place. They seem to be used to apply background colors? Although I may be missing something else they are intended for as it seems we would just handle that from the main elements and their margin/padding.
> * Im not thrilled about needing to add extra props here. I would like to just restrict via parent selectors like in the SCSS file, but the styled components do not seem to support this? I may be missing a way to do this from the styled component instead.
> * Im not 100% sure what about these absolutely position pseudo elements causes this. But removing them both clearly resolves the issue.

Looking at the git blame, I see @lupus2k worked around both of these pseudo element styles in the past. In case you happen to remember any context from a couple years ago, or have better ideas for resolving this.

**Comment by lupus2k** [comment]
> Looking at the git blame, I see @lupus2k worked around both of these pseudo element styles in the past. In case you happen to remember any context from a couple years ago, or have better ideas for resolving this.

Wow, that was almost two years ago...
We used to have a bottom boxes with colors in `/plugins/SITE`

If I think quickly without going into details I would tell you that this code is not necessary but if you want I can take a look to be sure.

| 2022 | now |
| image | image |

**Comment by Addison-Stavlo** [comment]
The one from the styled Section component seems to be applying the gray background across that "You pick the plugin..." section. (this still seems to exist when logged-out or when at the site level plugins marketplace).

**Review by allilevine — APPROVED** [review]
I tested the different plugin views, browsers, screen sizes, RTL. This fixes the issue and I don't see new issues that are related. I also pinged @cpapazoglou for a review.

**Review by DustyReagan — APPROVED** [review]
It tests well for me! It fixes the issue, and I didn't find any regressions.

**Comment by Addison-Stavlo** [comment]
Thanks for looking and testing all! Since this resolves the issue and should be safe/compatible elsewhere, Im going to ship it now.

>  I also pinged @cpapazoglou for a review.

But happy to adapt things later as well!

**Comment by Addison-Stavlo** [comment]
Note - we found that there are other issues on the logged out and site level plugins pages based on these pseudo elements that this PR removed but only from the global level.

https://github.com/Automattic/wp-calypso/pull/93425 is starting to look at removing those pseudo elements altogether, and thus undoing some of the changes (extra prop) added here.

**Pull request merged**
