### PR TITLE
A4A > Migration:s Add modal for schedule a Pressable demo

### PR DESCRIPTION
**Pull request by cleacos**
Resolves: https://github.com/Automattic/automattic-for-agencies-dev/issues/1266

## Proposed Changes

This PR adds a modal to schedule a Pressable demo. Currently, we send the user to [this Pressable page](https://pressable.com/request-demo/) with a embed iframe to schedule the demo.

**Card with the Pressable demo information**
image

**Modal to schedule the Pressable demo**
image

## Why are these changes being made?

*

## Testing Instructions

- Check the code
- Launch a live site in Horizon with the link bellow
- Go to the Migrations section: `/migrations/overview`
- Click on `Schedule a demo`
- The modal will be opened with the Pressable schedule content (it's an iframe)
   - In trunk, it goes to [this Pressable page where the iframe is](https://pressable.com/request-demo/).

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
    - [ ] For UI changes, have we tested the change in various languages (for example, ES, PT, FR, or DE)? The length of text and words vary significantly between languages. 
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Comment by simonktnga8c** [comment]
Very nice @cleacos! Can you make sure to update the Marketplace > Hosting > Pressable page to use this modal also? Thanks!

**Comment by cleacos** [comment]
Yes sure, I'll add to that section too

**Review by jkguidaven — APPROVED** [review]
Works great!

I do have an issue, though, with the embedded page set to a different locale, and I don't know if we can specify the locale through the URL on meet.hubspot.com to ensure we sync the locale in the A4A page.

The comment above is non-blocker, but it would be nice to address it to have a more polished experience.

**Comment by cleacos** [comment]
> with the embedded page set to a different locale

Yes, the same for me. But I have all my systems, including Chrome, in English as primary, and I still see it in Spanish. I don't sure why it's still sending the request with es-ES as Accept-Language.

I can't find anything on Hubspot to configure it. We could build a quick proxy for it, which would allow us to manage the HTTP header, but I don't think it's worth it. What do you think @simonktnga8c? (see my screenshot from the description)

**Pull request closed without merging**
