### PR TITLE
Checkout: Add Google Pay payment method

### PR DESCRIPTION
**Pull request by sirbrillig**
#### Changes proposed in this Pull Request

This will add a new payment method for Google Pay to checkout (when available).

Screen Shot 2021-05-06 at 7 29 43 PM

Screen Shot 2021-04-28 at 6 20 42 PM

Fixes 154-gh-Automattic/payments-shilling 

Currently, this is behind a feature flag which is only enabled on non-production environments.

#### Testing instructions

You can test this using the calypso.live branch (see comments below) without any additional work, but if you are running calypso on localhost, follow these steps first:

- Install [localtunnel](https://github.com/localtunnel/localtunnel) on your computer, probably with `npm install -g localtunnel`
- Apply D60830-code to allow using localtunnel and sandbox the API.
- Make sure calypso is running on calypso.localhost:3000
- Run `lt -p 3000 -h https://a8c-localtunnel.cyou` in the wp-calypso repository.
- You should get an https URL printed to the console. Open that URL in Google Chrome and use it for the below testing steps.

To test the payment method, you'll need to be using Google Chrome and already have a wallet with at least one active card stored in Google Pay. If you meet that criteria, you may proceed with the following instructions. Otherwise you will not see "Google Pay" as an option.

If your API is sandboxed, you can use a real credit card and will not be charged for the transaction because Stripe is operating in test mode.

- Add a product to your cart and visit checkout.
- Verify that "Google Pay" is one of the options in the list.
- Click "Google Pay", and then click the submit button at the bottom of checkout to confirm the payment.
- Verify that you see the Google Pay sheet appear in your browser and that the price there matches the price in checkout.
- Click to confirm the purchase.
- Verify that the purchase is successful and that you are redirected away from checkout to a thank-you page or with a thank-you notification as normal.

### CODE REVIEW

**Comment by sirbrillig** [comment]
I extracted all the refactoring into its own PR https://github.com/Automattic/wp-calypso/pull/52627

**Comment by sirbrillig** [comment]
This was working before, but now it's getting 401 errors from Google and I'm not sure why. Moving back to in-progress.

**Comment by sirbrillig** [comment]
Ok, this appears to work on localhost, but not calypso.live where all connections to `play.google.com` servers return a 401 error. Hopefully it will work in wpcalypso and horizon once merged.

**Comment by michaeldcain** [comment]
I pushed some changes to add the Google Pay icon to the payment method label and use the same svg to build a custom button.

Screen Shot 2021-05-11 at 3 12 42 PM
Screen Shot 2021-05-11 at 3 39 18 PM
Screen Shot 2021-05-11 at 3 42 34 PM

**Review by michaeldcain — APPROVED** [review]
This works well for me. @sirbrillig since it's behind a feature flag, I think we're good to merge it unless you see an issue with my commits.

**Comment by sirbrillig** [comment]
Rebasing due to e2e test changes.

**Comment by sirbrillig** [comment]
Nice! I tweaked the button a little bit but it looks and works great. Thanks for the updates! 👍

**Pull request merged**
