### PR TITLE
Checkout: Use shopping cart items to provide product variants

### PR DESCRIPTION
**Pull request by sirbrillig**
#### Proposed Changes

When viewing checkout, some products have billing term variants available (eg: for a Personal plan you can choose between 1 month, 1 year, or 2 years). These variants are fetched with a complicated combination of data by the `useGetProductVariants()` hook. The hook uses the product slug and quantity from the shopping cart, fetches plan and product data from two other endpoints, then combines that with hard-coded product data in calypso. The process of doing this has several downsides, notably that its prices can be wrong (https://github.com/Automattic/wp-calypso/issues/69964 and https://github.com/Automattic/wp-calypso/issues/55019) and that it requires quite a lot of frontend machinery to recreate data the backend already has.

In D93550-code, we amend the shopping-cart endpoint to include product variant data for each cart item. This PR uses that data to greatly simplify `useGetProductVariants()` so that it no longer needs the product, plan, or hard-coded information. In addition, many of the product variant guards (like not being allowed to purchase plan upgrades that are term downgrades) are no longer required as they will now be handled by the endpoint.

If it works correctly, this PR should not affect the behavior of calypso at all.

#### Screenshots

Screenshot 2022-11-26 at 1 00 44 AM

Screenshot 2022-11-26 at 1 00 56 AM

Screenshot 2022-11-26 at 1 06 58 AM

#### Testing Instructions

To test this properly we'll need to load the shopping cart with various types of products with and without this PR to verify that the product variants are unchanged. 

Some situations to check, comparing each one against the variant picker in production:

- WordPress.com plans with and without discounts.
- Jetpack bundles with and without discounts.
- Jetpack products that have a quantity set.

### CODE REVIEW

**Comment by sirbrillig** [comment]
Rebased after https://github.com/Automattic/wp-calypso/pull/70315 moved things around.

**Comment by spraveenitpro** [comment]
## Functional Testing:

<details>
<summary>Jetpack  Backup</summary>


</details>

<details>
<summary>Jetpack scan daily</summary>


</details>

<details>
<summary>WordPress.com personal plan</summary>


</details>

**Review by michaeldcain — CHANGES_REQUESTED** [review]
When eligible for a pro-rated price while upgrading from one plan to another (e.g. Premium -> Business), the variant picker (and sidebar nudge) now shows the discounted price instead of the original, which creates an issue when calculating the savings of the higher variants:

| Production     | PR |
| ----------- | ----------- |
| Screen Shot 2022-12-13 at 11 45 45 AM | Screen Shot 2022-12-13 at 11 39 17 AM |

**Comment by sirbrillig** [comment]
That's a very interesting find. I am a little torn about what to do about it because arguably, the new behavior is more accurate: it shows what you will actually pay inside the variant picker (and the percentages that are based on those prices). This is already what we do for introductory offers and sale discounts. 

I agree that showing a 1% discount is much less appealing than a 16% discount, even if it's correct, but what's the right solution? What discounts should we apply to variants and what discounts should we not apply? 🤔 

There's a lot of places that override product prices. I think that the ones that apply to upgrade variants are:

- coupons.
- sale coupons.
- prorated upgrade discount.
- prorated quantity discount.
- first-year promotional discount (hard-coded; different from introductory offers).

(The rest have to do with email products, domain products, shipping labels, and other things that don't have variants.)

**Comment by sirbrillig** [comment]
While we could debate a lot about what discounts to apply to variants, the goal of this PR is not to change any logic but only to move that logic to the server. Therefore, I've created D95413-code to remove the upsell discounts from variants in the cart. How does that look, @michaeldcain?

**Review by michaeldcain — APPROVED** [review]
Code-wise this looks good to me and works as expected when comparing to production. Nice work!

**Pull request merged**
