### PR TITLE
Site Settings: standardized heading font styles

### PR DESCRIPTION
**Pull request by rickybanister**
Across the General, Import, and Export settings we had three or four different heading styles for h1, some other things for h2, and different sizes for descriptive text.

I made them all the same as the site deletion stuff.

**Before:**
screen shot 2016-04-19 at 4 02 05 pm
screen shot 2016-04-19 at 4 02 17 pm
screen shot 2016-04-19 at 4 03 14 pm

**After:**
screen shot 2016-04-19 at 4 02 05 pm
screen shot 2016-04-19 at 4 07 14 pm
screen shot 2016-04-19 at 4 07 22 pm

### CODE REVIEW

**Comment by drw158** [comment]
Do you think the margin is too big below h1s on single card elements (like the site deletion card).

07110880-0649-11e6-9a86-646da3b70307

**Comment by rickybanister** [comment]
@drw158 maybe, it's 16px currently, I'm fine to make a change as long as we make it everywhere.

Should we have default h1 styles?

**Comment by drw158** [comment]
I don't think we need default h1 styles right now.

**Comment by rickybanister** [comment]
I discussed yesterday and today with @mtias some thoughts for creating components to add default typographic styles to commonly used semantic text elements. 

We will look into creating things like `cardHeading` or `cardParagraph`.

That said, I think we can leave the bottom-margin here alone for now and determine a nice standard for the components, then start swapping vanilla `h1`s with the components to fix the margin issue.

**Comment by mtias** [comment]
👍

**Pull request merged**
