### PR TITLE
Menus: refactor of 'create page while menu'

### PR DESCRIPTION
**Pull request by artpi**
Refactors #4034 and #4937 trying to keep Menus code as tidy as possible.

## Testing instructions

- Go to menus
- Create new nested Menu Item
- Choose `Create a new page for this menu item` as the item
- Save

CC @mcsf @rralian

### CODE REVIEW

**Comment by mcsf** [comment]
Thanks for keeping me in the loop. I'll try to follow this and review soon.

**Comment by mcsf** [comment]
@artpi, pushed a few changes

**Comment by mcsf** [comment]
ping @artpi

**Comment by artpi** [comment]
I see @mcsf that you merged your commit as a part of some other PR. Sorry it took me so long to get to merging this. I want to merge this asap.

**Comment by mcsf** [comment]
> I see @mcsf that you merged your commit as a part of some other PR

Nope, likely a weird rebase or something took the commit away. The same thing just happened to me locally, after which I manually cherry-picked.

**Comment by artpi** [comment]
Ok, I reverted my weird commit for lodash and all your changes are present @mcsf . I will merge this in ~ 2hrs

**Comment by mcsf** [comment]
> Ok, I reverted my weird commit for lodash and all your changes are present

Cool, I took out those two commits via interactive rebase for you. :)

**Pull request merged**
