### PR TITLE
Pattern Library: Increase `viewportWidth` in list view

### PR DESCRIPTION
**Pull request by fredrikekelund**
Fixes https://github.com/Automattic/dotcom-forge/issues/6550

## Proposed Changes

In the pattern library, pattern previews in the list view have a width of 1205px at most. We recently discussed whether we should increase the viewport width inside the preview (i.e., zoom out the previews slightly). I think this is a good idea. The list view is our "full-scale preview," but 1205px is quite a narrow width compared to most computer screens, so using a slightly wider viewport seems reasonable.

## Testing Instructions

1. Navigate to `/patterns/about`
2. Ensure that the pattern previews look decent
3. Ensure that resizing still works

### CODE REVIEW

**Comment by fredrikekelund** [comment]
@matt-west I tagged you for review to get your input on what you think about the updated viewport size. Use the Calypso Live preview link to take a look when you have a moment

**Review by matt-west — APPROVED** [review]
Looks good to me! Thanks @fredrikekelund

**Review by nightnei — APPROVED** [review]
At a glance `viewportWidth` logic was looking a bit complicated, but after some time of taking a look at the code - I see, makes sense 👍

The code LGTM and works as expected 👍

Only one thing which came to my mind, in the future we could consider making some personal sizes for `category-gallery`, for example, IMO - if we set some smaller width for `header` - it looks much more attractive. But it's not critical, just an idea for discussion in the future. For example the header is `600` on the next screenshot:
Screenshot 2024-04-15 at 10 32 06

**Comment by fredrikekelund** [comment]
> in the future we could consider making some personal sizes for category-gallery

We can experiment with that! I agree about leaving it for a future PR, though

**Pull request merged**
