### PR TITLE
Build: Turn on mangling with Uglify

### PR DESCRIPTION
**Pull request by blowery**
This turns on uglify's mangling, which can significantly reduce bundle sizes.

To test, spin up a docker instance with a production install and use Calypso.

```
docker build -t wp-calypso .
# go get a coffee. yikes.
sudo vim /etc/hosts # add an entry for 127.0.0.1 wpcalypso.wordpress.com
docker run -it --name wp-calypso --rm -p 80:3000 -e NODE_ENV='production' -e CALYPSO_ENV='wpcalypso' wp-calypso
open http://wpcalypso.wordpress.com
```

You'll need to make sure you're not proxying to hit the pretend wpcalypso.wordpress.com

Size changes:
```
130K accept-invite.js						130K accept-invite.js
102K accept-invite.min.js				      |	66K accept-invite.min.js
241K account.js							241K account.js
179K account.min.js					      |	114K account.min.js
67K ads.js							67K ads.js
51K ads.min.js						      |	36K ads.min.js
236K async-load-components-post-schedule.js			236K async-load-components-post-schedule.js
159K async-load-components-post-schedule.min.js		      |	103K async-load-components-post-schedule.min.js
187K async-load-featured-image.js				187K async-load-featured-image.js
122K async-load-featured-image.min.js			      |	74K async-load-featured-image.min.js
87K async-load-my-sites-drafts-draft-list.js			87K async-load-my-sites-drafts-draft-list.js
60K async-load-my-sites-drafts-draft-list.min.js	      |	35K async-load-my-sites-drafts-draft-list.min.js
12K async-load-post-editor-drafts-button.js			12K async-load-post-editor-drafts-button.js
7K async-load-post-editor-drafts-button.min.js		      |	3K async-load-post-editor-drafts-button.min.js
126K async-load-post-editor-editor-author.js			126K async-load-post-editor-editor-author.js
88K async-load-post-editor-editor-author.min.js		      |	51K async-load-post-editor-editor-author.min.js
66K async-load-post-editor-editor-discussion.js			66K async-load-post-editor-editor-discussion.js
45K async-load-post-editor-editor-discussion.min.js	      |	24K async-load-post-editor-editor-discussion.min.js
75K async-load-post-editor-editor-location.js			75K async-load-post-editor-editor-location.js
51K async-load-post-editor-editor-location.min.js	      |	28K async-load-post-editor-editor-location.min.js
74K async-load-post-editor-editor-post-formats-accordion.js	74K async-load-post-editor-editor-post-formats-accordion.js
51K async-load-post-editor-editor-post-formats-accordion.min. |	26K async-load-post-editor-editor-post-formats-accordion.min.
70K async-load-post-editor-editor-seo-accordion.js		70K async-load-post-editor-editor-seo-accordion.js
48K async-load-post-editor-editor-seo-accordion.min.js	      |	25K async-load-post-editor-editor-seo-accordion.min.js
113K async-load-post-editor-editor-sharing-accordion.js		113K async-load-post-editor-editor-sharing-accordion.js
80K async-load-post-editor-editor-sharing-accordion.min.js    |	45K async-load-post-editor-editor-sharing-accordion.min.js
572K async-load-post-editor-media-modal.js			572K async-load-post-editor-media-modal.js
394K async-load-post-editor-media-modal.min.js		      |	245K async-load-post-editor-media-modal.min.js
3M build-production.js						3M build-production.js
2M build-production.min.js				      |	1M build-production.min.js
717K commons.js							717K commons.js
525K commons.min.js					      |	309K commons.min.js
49K customize.js						49K customize.js
32K customize.min.js					      |	20K customize.min.js
3K discover.js							3K discover.js
2K discover.min.js					      |	1K discover.min.js
168K happychat.js						168K happychat.js
129K happychat.min.js					      |	84K happychat.min.js
308K help.js							308K help.js
235K help.min.js					      |	150K help.min.js
11K mailing-lists.js						11K mailing-lists.js
8K mailing-lists.min.js					      |	5K mailing-lists.min.js
8K manifest.js							8K manifest.js
6K manifest.min.js					      |	5K manifest.min.js
166K me.js							166K me.js
127K me.min.js						      |	83K me.min.js
277K media.js							277K media.js
205K media.min.js					      |	129K media.min.js
363K menus.js							363K menus.js
240K menus.min.js					      |	149K menus.min.js
277K notification-settings.js					277K notification-settings.js
215K notification-settings.min.js			      |	146K notification-settings.min.js
3K paladin.js							3K paladin.js
2K paladin.min.js					      |	1K paladin.min.js
230K people.js							230K people.js
181K people.min.js					      |	113K people.min.js
256K plans.js							256K plans.js
198K plans.min.js					      |	122K plans.min.js
649K plugins.js							649K plugins.js
495K plugins.min.js					      |	342K plugins.min.js
2M post-editor.js						2M post-editor.js
1M post-editor.min.js						1M post-editor.min.js
182K posts-custom.js						182K posts-custom.js
124K posts-custom.min.js				      |	68K posts-custom.min.js
374K posts-pages.js						374K posts-pages.js
266K posts-pages.min.js					      |	166K posts-pages.min.js
448K purchases.js						448K purchases.js
352K purchases.min.js					      |	226K purchases.min.js
5K reader-activities.js						5K reader-activities.js
4K reader-activities.min.js				      |	2K reader-activities.min.js
100K reader-following.js					100K reader-following.js
75K reader-following.min.js				      |	48K reader-following.min.js
18K reader-list.js						18K reader-list.js
15K reader-list.min.js					      |	9K reader-list.min.js
26K reader-post-recomendations.js				26K reader-post-recomendations.js
21K reader-post-recomendations.min.js			      |	12K reader-post-recomendations.min.js
21K reader-search.js						21K reader-search.js
16K reader-search.min.js				      |	9K reader-search.min.js
187K reader-start.js						187K reader-start.js
103K reader-start.min.js				      |	63K reader-start.min.js
229K reader-tags.js						229K reader-tags.js
149K reader-tags.min.js					      |	139K reader-tags.min.js
174K reader.js							174K reader.js
125K reader.min.js					      |	78K reader.min.js
450K security.js						450K security.js
338K security.min.js					      |	237K security.min.js
503K settings-seo.js						503K settings-seo.js
277K settings-seo.min.js				      |	154K settings-seo.min.js
846K settings.js						846K settings.js
620K settings.min.js					      |	371K settings.min.js
244K sharing.js							244K sharing.js
177K sharing.min.js					      |	116K sharing.min.js
679K signup.js							679K signup.js
540K signup.min.js					      |	359K signup.min.js
468K stats.js							468K stats.js
345K stats.min.js					      |	213K stats.min.js
154K theme.js							154K theme.js
110K theme.min.js					      |	66K theme.min.js
278K themes.js							278K themes.js
208K themes.min.js					      |	124K themes.min.js
1M upgrades.js							1M upgrades.js
844K upgrades.min.js					      |	570K upgrades.min.js
1M vendor.production.js						1M vendor.production.js
985K vendor.production.min.js				      |	641K vendor.production.min.js
```

### CODE REVIEW

**Comment by blowery** [comment]
Hrm, hung the docker process when trying to uglify. Investigating.

**Comment by lancewillett** [comment]
Yeah, I saw this in the build script on the live branch:

```
/bin/sh: /home/ubuntu/data/gh-wp-calypso/branches/try/build/mangling/node_modules/.bin/webpack: No such file or directory
Makefile:168: recipe for target 'build-server' failed
make: *** [build-server] Error 127
```

**Comment by blowery** [comment]
@lancewillett that should be unrelated to this... weird.

**Comment by samouri** [comment]
testing this out now... 🔍

**Comment by alisterscott** [comment]
I got this running locally using Docker and encountered three issues when running the e2e tests:

1. The accept-invite screen was blank (no console errors) 
accept invite
2. Domains page search results during signup (/start) was blank (no console errors) 
domains
3. Customizer was really slow, slow enough to not be able to run the e2e tests - I'm not sure whether this is something to do with iFraming the hosted site

I am not sure if these are issues running with host files etc. or whether they are specific to this PR.

I'm on Australian weekend now, but @hoverduck should be able to assist re-running the tests Friday US time

**Comment by blowery** [comment]
Thanks @alisterscott! I have a hunch those are busted on master too. Getting the e2e tests set up on my end to verify.

/cc @hoverduck

**Comment by blowery** [comment]
Confirmed we see the same failures in the e2e tests against master. I think this is good to land.

**Pull request merged**
