### PR TITLE
DIFM Page Picker: remove cart

### PR DESCRIPTION
**Pull request by aneeshd16**
Related to #

## Proposed Changes

* This PR removes cart actions from the page picker step. Now, for both new and existing sites, the cart shown on the front end will have statically calculated values. This removes the need for a network request and eliminates the chances of a cart error on this step. If there are any errors in the cart, those will now show up on the checkout page, where they are handled better.

## Testing Instructions

**DIFM flow, new site**
* Go to `/start/do-it-for-me`.
* Choose "new site" and go through the flow steps till you reach the page picker step.
* Confirm that the values in the cart are shown correctly.

**DIFM flow, existing site, free plan**
* Go to `/start/do-it-for-me`.
* Choose "existing site" and select a site on the free plan. Follow the flow steps until you reach the page picker step.
* Confirm that the plan **is present** and the values in the cart are shown correctly.

**DIFM flow, existing site, Starter(Personal) plan**
* Go to `/start/do-it-for-me`.
* Choose "existing site" and select a site on the Starter plan. Follow the flow steps until you reach the page picker step.
* Confirm that the plan **is present** and the values in the cart are shown correctly.

**DIFM flow, existing site, Explorer or higher plans**
* Go to `/start/do-it-for-me`.
* Choose "existing site" and select a site on an Explorer or higher plan. Follow the flow steps until you reach the page picker step.
* Confirm that the plan **is not present** and the values in the cart are shown correctly.

**DIFM store flow, existing site, free plan**
* Go to `/start/do-it-for-me-store`.
* Choose "existing site" and select a site on a free plan. Follow the flow steps until you reach the page picker step.
* Confirm that the plan **is present** and the values in the cart are shown correctly.

**DIFM store flow, existing site, Starter/Explorer plan**
* Go to `/start/do-it-for-me-store`.
* Choose "existing site" and select a site on a Starter/Explorer plan. Follow the flow steps until you reach the page picker step.
* Confirm that the plan **is present** and the values in the cart are shown correctly.

**DIFM store flow, existing site, Creator or higher plans**
* Go to `/start/do-it-for-me-store`.
* Choose "existing site" and select a site on a Creator or higher plan. Follow the flow steps until you reach the page picker step.
* Confirm that the plan **is not present** and the values in the cart are shown correctly.

**Post-onboarding flow, free plan**
* Go to `/setup/site-setup/difmStartingPoint?siteSlug=<site slug>` for a site on the free plan.
* Follow the flow steps until you reach the page picker step.
* Confirm that the plan **is present** and the values in the cart are shown correctly.

**Post-onboarding flow, Starter plan**
* Go to `/setup/site-setup/difmStartingPoint?siteSlug=<site slug>` for a site on the Starter plan.
* Follow the flow steps until you reach the page picker step.
* Confirm that the plan **is present** and the values in the cart are shown correctly.

**Post-onboarding flow, Starter plan**
* Go to `/setup/site-setup/difmStartingPoint?siteSlug=<site slug>` for a site on an Explorer or higher plan. Follow the flow steps until you reach the page picker step.
* Confirm that the plan **is not present** and the values in the cart are shown correctly.

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Comment by mikeicode** [comment]
@aneeshd16 I tested all of the above.

**Passed:**

- DIFM flow, new site
- DIFM flow, existing site, free plan
- DIFM flow, existing site, Explorer or higher plans
- DIFM store flow, existing site, free plan
- DIFM store flow, existing site, Creator or higher plans
- Post-onboarding flow, free plan
- Post-onboarding flow, Explorer plan

**Failed:**

The following showed the required plan (Explorer or Creator) in the cart at the full price, instead of showing the discounted upgrade price.

- DIFM flow, existing site, Starter(Personal) plan
    - Starter: https://mikeicode06.wordpress.com
- DIFM store flow, existing site, Starter/Explorer plan
    - Starter: https://teststarter6.wordpress.com
    - Explorer: https://mikeicode118.wordpress.com
- Post-onboarding flow, Starter plan
    - Starter: https://teststarter2.wordpress.com

**Comment by ddc22** [comment]
I think one of the main reasons we went with using the shopping cart is
that we could leverage the centralized management of the shopping cart
logic whenever the user adds it to the shopping cart.

If we want to depart from that we could probably fully clean up any
involvement of the shopping cart and add a disclaimer that the final price
will be calculated at checkout.

**Comment by aneeshd16** [comment]
Thanks for testing this @mikeicode!

> The following showed the required plan (Explorer or Creator) in the cart at the full price, instead of showing the discounted upgrade price.

This was an intentional change. We can show the discounted price here, but that would mean introducing another network request to fetch the current plan for the site and also duplicating backend logic for determining the plan term (1y/2y/3y) based on the current plan. Also, with this new upcoming change (pdh1Xd-2Cc-p2), we might not need this line item at all.

> If we want to depart from that we could probably fully clean up any
involvement of the shopping cart and add a disclaimer that the final price
will be calculated at checkout.

Hi @ddc22! Yes, that is exactly what this PR does. And we already have a disclaimer in place. :)
image

**Comment by mikeicode** [comment]
@aneeshd16 

> Also, with this new upcoming change (pdh1Xd-2Cc-p2), we might not need this line item at all.

That change would only affect new sites, with a new Explorer plan being added. It wouldn't affect existing sites upgrading from Starter to Explorer, or from Explorer to Creator for a store build.

Based on yearly pans, the sidebar cart would show a price that is $48 too high for sites upgrading from Starter to Explorer, and $96 too high for Explorer to Creator.

Can we add an extra asterisk next to the plan cost for existing sites?

Screen Shot on 2024-03-27 at 10:15:13

**Comment by aneeshd16** [comment]
@mikeicode, done, added via https://github.com/Automattic/wp-calypso/pull/88767/commits/bae89e4b3349fd92c02f92bf5947bfea867f0de8!

image

**Pull request merged**
