### PR TITLE
Domain management: Match forward email list screen design

### LINKED ISSUE #97234: Show Emails page tab when users have set the Forward Emails
When the users have one or more Email Addresses set as forward emails, the following screen should be shown

Image

### PR DESCRIPTION
**Pull request by bogiii**
Closes https://github.com/Automattic/wp-calypso/issues/97234

## Proposed Changes

* Creates `EmailForwardHeader` component
* Refactor the `EmailPlanMailboxesList` to support two different contexts in a more structured way

## Why are these changes being made?

* Domain management revamp project

## Testing Instructions

* Go to `/domains/manage?flags=calypso/all-domain-management`
* Create or select domain
* Add one or more forwarded emails
* Check the Email forwarding list screen and compare it with Figma; link will be `domains/manage/all/email/{DOMAIN}/{DOMAIN}`
* Check the current flow and check if there is any regression

**The new UI**
Screenshot 2024-12-20 at 12 18 57

Screenshot 2024-12-20 at 12 19 15

**The existing UI**
Screenshot 2024-12-20 at 12 18 17

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
    - [ ] For UI changes, have we tested the change in various languages (for example, ES, PT, FR, or DE)? The length of text and words vary significantly between languages. 
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Review by Imran92 — COMMENTED** [review]
Good job! The table looks good when the emails are added.

An issue I've noticed is, when emails are waiting to be approved, the list items look broken

**All Emails waiting for approval**
Screenshot 2024-12-19 at 3 12 16 PM


**One of the Emails waiting for approval**
Screenshot 2024-12-19 at 3 12 53 PM

**Comment by bogiii** [comment]
Hey @Imran92,

I've handled the "email verification" use case; it is ready for re-review.

**Review by Imran92 — APPROVED** [review]
LGTM.

Just wanted to note that I've noticed two padding issues where the padding doesn't look symmetrical-

Screenshot 2024-12-21 at 12 43 54 AM
Screenshot 2024-12-21 at 12 44 36 AM

**Comment by bogiii** [comment]
The paddings match the Figma design, so the heading and the last row have differences.

Thanks for the review. @Imran92

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/17076231

Some locales (Hebrew, Japanese) have been temporarily machine-translated due to translator availability. All other translations are usually ready within a few days. Untranslated and machine-translated strings will be sent for translation next Monday and are expected to be completed by the following Friday.

Thank you @bogiii for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/17076231).

**Pull request merged**
