### PR TITLE
Help Center: Move directly to a package

### PR DESCRIPTION
**Pull request by alshakero**
## Summary

1. This PR adds Directly to the support options. We have moved the directly code into the help-center package.
2. Moves Spinner from calypso/components to packages/components.
3. Uses the new package in the help center.

## Testing
1. Apply D81418-code to get Directly eligibility for every user.
2. Pull the branch and run `cd apps/editing-toolkit/ && yarn dev --sync`
3. Go check the HelpCenter contact form and it should automatically go to Directly.

### Regression testing - important
1. Using a free user (user without any purchases) visit http://calypso.localhost:3000/help/contact.
2. Type something and send the question.
4. Directly popup should appear.

Related to #63655

### CODE REVIEW

**Comment by AllTerrainDeveloper** [comment]
Email related code (Letero owned code) seems good to me :)

**Review by escapemanuele — APPROVED** [review]
That's really impressive 🚀

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/7333249

Hi @alshakero, could you please edit the description of this PR and add a screenshot for our translators? Ideally it'd include all of the following strings:
- `Start live chat with an expert`
- `These are others, like yourself, who have been selected because of their WordPress.com knowledge to help answer questions.`
- `An expert user will be with you right away`
- `Ask an expert`
- `Connecting you to an expert`

Thank you in advance!

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/7333249).

**Pull request merged**
