### PR TITLE
Stats: Update module-followers to component directory

### PR DESCRIPTION
**Pull request by alternatekev**
This PR moves the `module-followers.jsx` and `module-followers-page.jsx` to `stats-followers/index.jsx` and `stats-followers/followers-page.jsx`, respectively. No SCSS is involved.

### CODE REVIEW

**Comment by timmyc** [comment]
@alternatekev why is the insights file modified in this branch?

**Comment by alternatekev** [comment]
@timmyc  Shouldn't be. I may have been testing something. Will fix.

**Comment by dmsnell** [comment]
looks like the `follows.jsx` may have been accidentally included as well

**Comment by alternatekev** [comment]
Closing this and moving the changed files to a new PR.

**Pull request closed without merging**
