### PR TITLE
GitHub deployments: rework new workflow wizard

### PR DESCRIPTION
**Pull request by mpkelly**
Closes https://github.com/Automattic/dotcom-forge/issues/5954

Screenshot 2567-03-11 at 14 19 51

## Proposed Changes

* Don't let users edit the default workflow file name. This simplifies validation.
* Restyle the workflow preview UI to match Figma.
* If a file exists from a previous setup, just overwrite it.
* Don't verify the standard workflow. It's ours, so we know it works.

## Testing Instructions

* Apply patch D141423-code
* Go to set up a new workflow
    * Try with a repo with no workflows
    * Try with a repo with a workflow other than ours and confirm it can be used
    * Try with a repo that already has a `wpcom.yml` file. Confirm it can be reused or overwritten

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Comment by javierarce** [comment]
Design-wise this looks better now, but I found an issue. After I successfully installed the custom workflow for the first time, the form got stuck on the installation part, and I wasn't able to validate it:

https://github.com/Automattic/wp-calypso/assets/4933/f2a66e9c-9e91-4801-84aa-1b61b8310a21

**Comment by mpkelly** [comment]
Hi @javierarce, that's because a backend patch is needed that removes a validation check. I tested the same scenario with my sandbox, and it works. I will merge this and the backend patch and you can check it when you're back online. 

[screen-capture (25).webm](https://github.com/Automattic/wp-calypso/assets/6851384/54b5273e-4a3a-4d54-b3cc-c24a3eca4bf7)

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/11594114

Some locales (Hebrew, Japanese) have been temporarily machine-translated due to translator availability. All other translations are usually ready within a few days. Untranslated and machine-translated strings will be sent for translation next Monday and are expected to be completed by the following Friday.

Thank you @mpkelly for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/11594114).

**Pull request merged**
