### PR TITLE
Add support for 100y plan

### PR DESCRIPTION
**Pull request by gmovr**
Related to #

## Proposed Changes

* Adds terms and plan checks for the 100 year plan and 100 year terms in calypso-products
* TBD, various UI/checkout fixes, and UI fixes for calypso when the current site has this plan.

## Testing Instructions

* Can be tested with D119186-code, but this will need an update to handle the terms correctly.
* For calypso products, unit tests.
* TBD.

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

**Review by dzver — COMMENTED** [review]
The checkout doesn't work for me - I think we need to add custom code to getComponentAndPrimaryPurchaseAndDomain to make it resolve as Business for now, and we can iterate and make it a separate screen later.

**Comment by gmovr** [comment]
> The checkout doesn't work for me - I think we need to add custom code to getComponentAndPrimaryPurchaseAndDomain to make it resolve as Business for now, and we can iterate and make it a separate screen later.

Thanks for testing. I'll fix that.

Will also untangle some of the naming.

**Comment by dzver** [comment]
I no longer see a js error but the plan name doesn't load with the latest PR and backend diff.

Screenshot 2023-08-22 at 22 24 33

**Review by dzver — APPROVED** [review]
LGTM

I documented some missing bits as https://github.com/Automattic/martech/issues/2093. We may find some more changes like this but this works fine.

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/8802009

Hi @gmovr, could you please edit the description of this PR and add a screenshot for our translators? Ideally it'd include all of the following strings:
- `Features included in your 100-Year Plan`
- `Hundred year subscription`
- `Best for long-term thinkers`

Thank you in advance!

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/8802009).

**Pull request merged**
