### PR TITLE
Bundled Plugins: Add redirect to bundle plugin flow from the themes/thanks-modal

### PR DESCRIPTION
**Pull request by mreishus**
#### Proposed Changes

* In the Theme Showcase, after switching to a theme with a bundled software set, the thanks modal will send your browser to `/setup/?siteSlug=${ siteSlug }&flow=plugin-bundle`, to allow you to set up your store and possibly atomic transfer.

#### Testing Instructions

* Be in an environment where `'themes/plugin-bundling'` is on (like calypso localhost)
* Visit the theme showcase `http://calypso.localhost:3000/themes/YOURSITE`
* Change themes to baxter (which currently has a bundled software set)
* You should be redirected to the plugin bundle flow by the thank you modal

#### Followups

* Detect if someone has already set up a store. Imagine if I go 2020 theme -> Baxter -> set up store -> 2020 theme -> Baxter. I probably shouldn't go through the stepper plugin-bundle flow again.
* Permissions. What if someone doesn't have a business plan and somehow gets here? Ideally it shouldn't happen, but it should be planned for. Maybe it's the stepper detecting eligibility and kicking you out.

### CODE REVIEW

**Comment by mreishus** [comment]
There doesn't seem to be a way to write to the stepper store from outside stepper. If I `import { SITE_STORE } from 'calypso/landing/stepper/stores'` in `client/my-sites/themes/thanks-modal.jsx`, calypso fails to boot with this error in the console:

```
/dev/wp-calypso/node_modules/progress-event/index.js:26
'function' === typeof document.createEvent ? function ProgressEvent (type, props) {
                      ^
ReferenceError: document is not defined
    at Object.<anonymous> (/dev/wp-calypso/node_modules/progress-event/index.js:26:23)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
    at Module.load (node:internal/modules/cjs/loader:1004:32)
    at Function.Module._load (node:internal/modules/cjs/loader:839:12)
    at Module.require (node:internal/modules/cjs/loader:1028:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object../client/my-sites/themes/thanks-modal.jsx (/dev/wp-calypso/build/webpack:/wp-calypso/external commonjs "progress-event":1:35)
    at __webpack_require__ (/dev/wp-calypso/build/webpack:/wp-calypso/webpack/bootstrap:19:1)
    at Object../client/my-sites/themes/index.node.js (/dev/wp-calypso/build/server.js:28792:20)
```

**Comment by mreishus** [comment]
I'm deleting this file, but it's here if we need it:
`client/state/themes/selectors/get-theme-software-sets.js`
```js
import { isEnabled } from '@automattic/calypso-config';
import { getTheme } from 'calypso/state/themes/selectors/get-theme';

import 'calypso/state/themes/init';

export function getThemeSoftwareSets( state, themeId ) {
	if ( ! isEnabled( 'themes/plugin-bundling' ) ) {
		return [];
	}
	const theme = getTheme( state, 'wpcom', themeId );
	const theme_software_set = theme?.taxonomies?.theme_software_set;
	return theme_software_set || [];
}

```

**Comment by mreishus** [comment]
I tried to use `page(dest)` instead of `window.location.replace( dest );`, but it doesn't seem to work.

**Review by nelsonec87 — APPROVED** [review]
LGTM!
I've tested it and I was redirected to `/setup/goals?siteSlug=<slug>&flow=plugin-bundle`

**Comment by mreishus** [comment]
Verified the redirect does not happen when the `themes/plugin-bundling` flag is off.

**Pull request merged**
