### PR TITLE
Reader: add email settings to feed header

### PR DESCRIPTION
**Pull request by bluefuton**
Adds the new `reader-email-settings` block to the Reader feed header, as requested in https://github.com/Automattic/wp-calypso/issues/15457.

Fixes https://github.com/Automattic/wp-calypso/issues/15457.

### Todo
- [x] Only show when following site
- [x] Finalise appearance

### CODE REVIEW

**Comment by bluefuton** [comment]
@jancavan for a first pass, I've hidden the label on <660px:

screen shot 2017-07-14 at 17 36 54

Here's a full width version:

screen shot 2017-07-14 at 17 36 21

...but it wraps at some intermediate sizes, particularly when there's a large follower count:

screen shot 2017-07-14 at 17 37 08

Do you think we should keep the Following and Settings buttons in that spot?

**Comment by fraying** [comment]
In #15457 I suggested stacking them like so:

screen shot 2017-07-14 at 9 50 23 am

This keeps the order consistent with other occurrences (like on Manage).

**Comment by jancavan** [comment]
> Do you think we should keep the Following and Settings buttons in that spot?

Yup, we'll stack them in wider screens. In narrow screens, they'll probably need to be side by side and moved right under the follower count.

**Comment by jancavan** [comment]
I realized we actually hide the follow count when there is a "Back" button (once it hits 960px), I believe primarily because of space constraints so I also just dropped this for when there isn't a "Back" button.

**With "Back" button:**
screenshot 2017-07-17 21 15 20
screenshot 2017-07-17 21 15 29

**Without "Back" button:**
screenshot 2017-07-17 21 14 39
screenshot 2017-07-17 21 14 31

I think we should show the follower count on mobile (quick mockup below) because isn't it more important than the "Back" button?

screenshot 2017-07-17 21 30 46

**Comment by bluefuton** [comment]
I've given it a final spin in the always joyous IE11, and all looks good.

screen shot 2017-07-18 at 20 15 50

**Comment by fraying** [comment]
Nice work, y'all! 👍

**Comment by samouri** [comment]
Code LGTM. Testing now

**Comment by lancewillett** [comment]
This is neat — I've used it 3-4 times now, and it saved time and clicks around to find the setting in Manage.

**Pull request merged**
