### PR TITLE
Build: Use calypso-build to build Notifications.

### PR DESCRIPTION
**Pull request by ockham**
#### Changes proposed in this Pull Request

* Replace `bin/sdk/notifications.js` with `client/notifications/webpack.config.js`, based on `@automattic/calypso-build/webpack.config.js`

#### Testing instructions

```
NODE_ENV=production npm run build-notifications --output-path=/some/path
```

**Furthermore, follow testing instructions found at PCYsg-elI-p2**

#### Note

The CSS files produced by this are now named `build.min.css` (and `build.min.rtl.css`) -- as opposed to `build.css`/`build.css.rtl`, as they were previously named. This is due to #32194 (which infers CSS chunk filenames from JS ones), but shouldn't matter much.

#### Possible follow-up PR

Move `client/notifications/` to `apps/notifications/`, add a `package.json` there (akin to `o2-blocks`). Need to make sure it still works when used as part of Calypso!

---

For those joining us only now: the rationale for this PR is found in pafL3P-oe-p2:

> <h3>Problem: ‘Old’ Calypso SDK obfuscates use of webpack configs</h3>
>
> One of the findings from the Jetpack blocks move was that the existing <a href="https://github.com/Automattic/wp-calypso/blob/924fb2c55b1237d13efacc5248bbc55bb6a0c910/bin/sdk-cli.js">Calypso SDK script</a> (and related <a href="https://github.com/Automattic/wp-calypso/tree/924fb2c55b1237d13efacc5248bbc55bb6a0c910/bin/sdk">target-specific configs</a>) really just solves two problems:
>
> <ol>
> <li>It provides some CLI tooling</li>
> <li>It extends a baseline `webpack.config.js`</li>
> </ol>
> 
> However, this makes it somewhat obscure to tap into that mechanism to pin-point where and how the underlying <code>webpack.config.js</code> is extended.
> 
> <h3>Solution: Ditch our homegrown CLI tooling, embrace Webpack’s</h3>
>
> For Jetpack, @jonsurrell was able to elegantly get rid of that extra layer by simply leveraging Webpack’s own CLI (which provides basic functionality such as a configurable output dir or watch mode for free). We should do the same for our remaining SDK targets in Calypso, i.e. turn each of the target configs in <code>bin/sdk</code> into a <code>webpack.config.js</code> that extends <code>@automattic/calypso-build</code>’s, and co-locate them with the code they’re used for.

### CODE REVIEW

**Review by mmtr — APPROVED** [review]
LGTM! 👍

**Review by simison — APPROVED** [review]
Hurrah! :tada:

image

**Comment by simison** [comment]
FYI @Automattic/lannister this might need follow up to update docs somewhere if the SDK command was mentioned there directly.

**Comment by ockham** [comment]
> FYI @Automattic/lannister this might need follow up to update docs somewhere if the SDK command was mentioned there directly.

FWIW, no mention in PCYsg-elI-p2.

**Comment by simison** [comment]
I also checked that [`client/notifications/README.md`](https://github.com/Automattic/wp-calypso/blob/3641edd4a6400e3c8d6ee4896fa76b9cfa14c50b/client/notifications/README.md) didn't mention build instructions. :thumbsup:

**Pull request merged**
