### PR TITLE
Show Google Plus Deprication Message

### PR DESCRIPTION
**Pull request by belcherj**
#### Changes proposed in this Pull Request

* Disable adding new Google Plus connections by removing button
* Include a link (URL TBD) explaining why this functionality has been removed

#### Testing instructions

* Goto: http://calypso.localhost:3000/sharing/{DOMAINSLUG}
* Observe that you can now longer connect to Google Plus
* Sharing via existing Google Plus connections should still work

Non-connected account:
screen shot 2018-12-13 at 1 53 29 pm

Connected Account:
screen shot 2018-12-13 at 1 19 08 pm

### CODE REVIEW

**Comment by codebykat** [comment]
Cool! The main functionality tests fine to me. A few comments...

* Looks like there are some Mailchimp changes in the commit as well -- is that intended or did they sneak in from a different change?

* If I have a G+ account currently connected, I still see the option to connect a different account in the dropdown:

screen shot 2018-12-12 at 12 20 39 pm

* There's no way to disconnect that existing connection now

**Comment by belcherj** [comment]
The MailChimp changes occurred because I wanted to abstract out part of the isMailchimpService function.  That function doesn't take any params or use arguments in any way so I removed them from those function calls.  Probably best to revert those changes.

**Comment by gravityrail** [comment]
Note that this should **not** be merged until the final support URL has been created.

In addition the support URL should be part of the wordpress.com support pages for WPCOM sites, and the Jetpack support pages for Jetpack sites (sorry!)

**Comment by blowery** [comment]
Just echoing Kat's comments, we should still be able to disconnect an existing connection. I would imagine that would be a pretty common request since we're removing it. 

Maybe the `Connect to a different account` could become the `Disconnect` button?

**Comment by belcherj** [comment]
> Maybe the Connect to a different account button could become the Disconnect button?

Was hoping to do this cleanly but it seems that will be difficult to do without a bunch of small temporary patches.  Will dive in deeper to figure out an easier way.

**Comment by belcherj** [comment]
@gravityrail suggestions addressed!

**Comment by gravityrail** [comment]
You missed one ;)

> We should show a disabled button with the word "Unavailable", rather than removing the "Connect" button entirely. This makes it look deliberate, rather than a bug.

See screenshot:

connect-button-enabled

**Comment by belcherj** [comment]
Fixed.

**Pull request merged**
