### PR TITLE
Update Form Select arrow icon

### LINKED ISSUE #88203: Update arrow icon in the default select component
Currently, we have two different dropdown components that allow users to select elements or trigger actions:

- One is called `SelectDropdown` and is a custom element that can display icons, badges, and custom menus.
- The other is the default HTML select element with a custom arrow icon.

Both components serve a similar function and should look identical. The most glaring issue is the different designs of the arrows. The HTML select element uses an arrow barely perceptible in the default state, and a thick line that doesn't match the visual langue of other elements in Calypso.

To make the styles more cohesive, I propose using the arrow from the `SelectDropdown` component in the HTML select element. We can address other issues in the future, but fixing this detail right now will get us to a better place.

| Before | After |
|--------|-------|
|image |image|

### PR DESCRIPTION
**Pull request by matt-west**
Fixes #88203

## Proposed Changes

* Update dropdown icon used in form select to be consistent with the `SelectDropdown` component.
* Removed hover and focus state arrows. The icon color should remain consistent throughout these states.

| Before | After |
|--------|--------|
| Screenshot 2024-03-06 at 10 14 15 | Screenshot 2024-03-06 at 10 13 26 |

## Testing Instructions

* Run Calypso using `yarn start`
* Navigate to: http://calypso.localhost:3000/devdocs/design/form-fields
* Observe that the icon in the Form Select now matches the one used in the `SelectDropdown` component

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Review by javierarce — APPROVED** [review]
Nice! LGTM!

**Review by tyxla — COMMENTED** [review]
Looks good from my perspective!

Do we want a @Automattic/dotcom-design approval just in case?

**Comment by matt-west** [comment]
Thanks @tyxla! @javierarce has reviewed on behalf of Dotcom design.

**Comment by tyxla** [comment]
In that case 🚀

**Pull request merged**
