### PR TITLE
Jetpack connect: Use shared access error for SSO

### PR DESCRIPTION
**Pull request by sirreal**
- Remove some JPC-specific Happychat events. They can use global Happychat events.
   Some events are used in funnels, I'll 🔴 them and provide suggestions.
- Parameterize `NoDirectAccess` component.
- Update `JetpackSso` to use shared `NoDirectAccess` component.

The SSO error will now include the same support link provided by at `/jetpack/connect/authorize`

The only functional change is to dispatch fewer (redundant) events. I'll provide instructions to update anything using these events:
- `calypso_jpc_authorize_chat_initiated`
- `calypso_jpc_chat_initiated`
- `calypso_jpc_noqueryarguments_chat_initiated`
- `calypso_jpc_planslanding_chat_initiated`
- `calypso_jpc_plans_chat_initiated`
- `calypso_jpc_sso_chat_initiated`

These events should all be replaceable (and more reliable) with the general chat start event: `calypso_happychat_start`

## Testing

Confirm these messages work as before:

- https://calypso.live/jetpack/sso?branch=update/jpc-sso-shared-error
- https://calypso.live/jetpack/connect/authorize?branch=update/jpc-sso-shared-error

### CODE REVIEW

**Comment by sirreal** [comment]
Rebased (Node 10) and ready for review

**Comment by alisterscott** [comment]
It looks like this one needs rebasing and an author reply

**Comment by tyxla** [comment]
Jon is currently AFK, and this PR is currently a low priority one, considering our present focuses. Anyway, this is still a good idea, as it'll help clean up some unnecessary tracks events.

**Comment by alisterscott** [comment]
Closing due to inactivity. Please reopen if necessary.

**Comment by aaronyan** [comment]
Is there an eventprop that differentiates between the types of chats started (Jetpack vs WPcom)? If not, can we add one? :)

**Comment by sirreal** [comment]
> Is there an eventprop that differentiates between the types of chats started (Jetpack vs WPcom)? If not, can we add one? :)

@aaronyan There may be a prop you can use to determine whether the currently selected site is Jetpack  or not, or by looking at a site plan ID, or something like that.

I don't know much about specific props on this event. Maybe someone at @Automattic/lighthouse could help with that.

**Comment by mattwondra** [comment]
I don't think Lighthouse did any work that intersect with this PR. The Jetpack-specific integrations were done by @Automattic/luna.

> I don't know much about specific props on this event. Maybe someone at @Automattic/lighthouse could help with that.

If you're talking about the `calypso_happychat_start` event, you created that in https://github.com/Automattic/wp-calypso/pull/23438. As far as I can tell there's no eventprops being sent in right now, but I don't see any reason why you couldn't.

**Comment by sirreal** [comment]
> If you're talking about the `calypso_happychat_start` event, you created that in #23438. As far as I can tell there's no eventprops being sent in right now, but I don't see any reason why you couldn't.

So I did! Thanks for reminding me 🙃 

@aaronyan In summary: you might have enough info in the global event props, no additional event are added to the `calypso_happychat_start` event. We could likely figure out a way to add what you need if possible. I don't have a lot of time right now to dedicate to these efforts, so please feel free to take over this PR or do as you see fit. If there are specific things I can help with, please ping me 👍

**Comment by millerf** [comment]
@sirreal Is it worth taking this one over and finishing it?

**Comment by sirreal** [comment]
I'm abandoning this.

**Pull request closed without merging**
