### PR TITLE
Help Center: styling fixes and refactor

### LINKED ISSUE #93561: Help Center (module) CSS is loaded on site frontend on WordPress.com
### Quick summary

Hello guys,

We recently noticed that the `https://widgets.wp.com/help-center/help-center-wp-admin.css?ver=db43fb906617f7ff786e` file is loaded on the front end of the site causing conflicts with the theme variables in the Blocksy theme.

I suspect this CSS is needed for this module:
CleanShot 2024-08-15 at 19 05 18

The file rewrites some variables that are defined by the theme, specifically as you can see in the screenshot:
- `--theme-text-color`
- `--theme-icon-color`

I understand that this is the naming convention you use in Calypso but at the same time it is not correct to apply them on the front end of the site.

Maybe you need to scope somehow those variables more specifically?

### Steps to reproduce

1. Start with a site that has a Business plan
2. Install & activate Blocksy theme
3. Install and activate the Blocksy Companion plugin
4. Open "Customizer", make a small change and hit the "Publish" button
5. Close the "Customizer" and open the frontend
6. You will see that some parts with text are white

### What you expected to happen

I expect the `help-center-wp-admin.css` won't override the theme colors.

### What actually happened

All the text is white because `help-center-wp-admin.css` is overriding it.

### Impact

All

### Available workarounds?

No but the platform is still usable

### If the above answer is "Yes...", outline the workaround.

_No response_

### Platform (Simple and/or Atomic)

_No response_

### Logs or notes

_No response_

### PR DESCRIPTION
**Pull request by arcangelini**
## Proposed Changes

1. Remove unused styles (there was a lot)
2. Moved all styles to component stylesheets. Created new sheets where needed.
3. Adjusted classnames and HTML structure for consistency in stylings.
4. Created a new BackButtonHeader component to have consistency across routes.

Also addresses the following issues from the recent walkthrough:

* The external icon in an article is not aligned to the X icon.
* “Help Center”, “Back” and the article text are not aligned.
* Drag icon and “<” are not aligned in an article.

**As a result of the fixes there are some small noticeable differences between production**

* The padding on the article pages
* The padding on the back-button-header

## Why are these changes being made?

| Before | After |
| - | - |
| Screen Shot 2024-08-21 at 18 05 11 | Screen Shot 2024-08-21 at 18 04 58 |
| Screen Shot 2024-08-21 at 18 04 22 | Screen Shot 2024-08-21 at 18 04 44 |

Help Center has been around for over two years now. I remember when it was so little that I could hold it in my hand. Those days are gone and now we have a ruthless teenager that refuses to clean their room. To prevent the Help Center from growing up and being a giant mess we need to adjust how we manage the styles. This PR aims to do just that.

This basic refactor that moves all the styles into the matching stylesheet for each component. There are a few tweaks that needed to happen as well to address how things are structured and styled. There are a lot of files change but its all CSS minus a couple small changes in components. The testing shouldn't be very challenging as its all style related.

## Testing Instructions

Using the live link we need to test all routes and compare to production.
Test in mobile and minimized.

### CODE REVIEW

**Comment by agrullon95** [comment]
Wapuu `Contact our support team` styling issue:

https://github.com/user-attachments/assets/d3f30311-2cf0-481a-a1fe-acc749e11115

**Comment by agrullon95** [comment]
Resource hover styling issue:
When tabbing over a resource, the text color changes to white which is not easy to read.

CleanShot 2024-08-26 at 12 12 31@2x

**Review by heavyweight — APPROVED** [review]
Looks great!!

**Review by agrullon95 — APPROVED** [review]
Everything looks great. I cant find any new issues.

I found an existing issue (same in prod) with the Wapuu modal (clicking on the expand button):

CleanShot 2024-08-27 at 12 08 17@2x

We can squeeze that in if you have a fix or follow up.

**Comment by arcangelini** [comment]
> I found an existing issue with the Wapuu modal (clicking on the expand button):

Oh! I never knew this was a thing haha. I can add a couple lines to clean it up. Thanks @agrullon95

**Comment by arcangelini** [comment]
Hey @AllTerrainDeveloper I added some fixes to the Wapuu fullscreen. There are some small CSS fixes and I hid the button on mobile since it is not needed.

| Before | After |
| - | - |
| Screen Shot 2024-08-27 at 23 00 23 | Screen Shot 2024-08-27 at 22 59 12 |
| Screen Shot 2024-08-27 at 23 00 48 | Screen Shot 2024-08-27 at 22 59 44 |

**Comment by AllTerrainDeveloper** [comment]
The code to do a screenshot resides in packages/odie-client/src/context/useScreenshot.ts

It's using JavaScript API
https://developer.mozilla.org/en-US/docs/Web/API/Screen_Capture_API/Using_Screen_Capture

Sadly, that API allows to RECORD the screen, but not to do a (Weird). So The code basically records a quick video, then print a frame in a HTML in memory canvas, and lately, extract the data as base64 encoded data.

I hope there're will be soon a way less convoluted way of creating a Screenshot, because it has no sense to me to don't be able to have a quick screenshot

**Pull request merged**
