### PR TITLE
Avoid null site access when navigating from site settings to /sites

### PR DESCRIPTION
**Pull request by lsl**
Related to #

## Proposed Changes

* Prevents the site settings page from accessing the site object during a re-render after the selected site has been cleared.

Screenshot 2024-11-29 at 15-33-54 General Settings — WordPress com

## Testing Instructions

* Visit site settings: http://calypso.localhost:3000/settings/general/
* Click the "W" to go to /sites
* Observe no calypso crash, or in production, the need to click again / see a ?retry=1 param.

### CODE REVIEW

**Review by fushar — COMMENTED** [review]
I can't seem to repro this in production 🤔 is there any surefire reproduction steps?

**Comment by lsl** [comment]
Production seems to have some kind of handling / work around where it adds a '?retry=1' param. I didn't look into what was doing it or why but it seems to mask the issue.

**Review by fushar — APPROVED** [review]
I see, I can repro this on development 🤦 the fix make sense!

**Review by arthur791004 — APPROVED** [review]
👍

**Pull request merged**
