### PR TITLE
Framework: Display the name of the current branch with the environment badge

### PR DESCRIPTION
**Pull request by Tug**
The idea is that it is useful to be remembered of the current branch when you are testing.

This is what it looks like:

cloudup-08a1b31a-7023-4396-a76d-864ef226fa22

Branch name is not displayed when:
- Git is not available
- The project is not a git repository
- The current branch is master

Also, this is going to be really useful for [a multiple versions application](https://github.com/Automattic/calypso-live-branches) of calypso.

### CODE REVIEW

**Comment by Tug** [comment]
cc @lancewillett, @mtias

**Comment by lancewillett** [comment]
Quick notes from testing the branch in Firefox, local install of latest master: I switch to this branch, but the badge didn't update. :(

screen shot 2015-12-14 at 12 47 21

**Comment by lancewillett** [comment]
OK — after a new `make run` it's showing up! Nice.

screen shot 2015-12-14 at 12 50 10

**Comment by Tug** [comment]
Yeah, it could be made dynamic I suppose.

**Comment by Tug** [comment]
Let's wait for https://github.com/Automattic/wp-calypso/pull/1322 to be merged and review this change again!

**Comment by mtias** [comment]
@Tug this seems like a nice improvement. I don't think we need to wait on the design update to get it in, though :)

**Comment by Tug** [comment]
Ok :) let's merge it then?

**Comment by lancewillett** [comment]
:ship:

**Comment by mtias** [comment]
:+1:

**Pull request merged**
