### PR TITLE
Add light color scheme from wp-admin

### PR DESCRIPTION
**Pull request by mreishus**
One part of #47036

#### Changes proposed in this Pull Request

* Add light color scheme

#### Testing instructions

* Visit /me/account
* Choose light and save

To see the wp-admin color scheme, create an atomic site, then visit /wp-admin/profile.php, choose color scheme and save.

Calypso:

Wp-Admin

#### Notes

This seems to be quite an odd scheme - almost an inverted scheme when it comes to the sidebar.

### CODE REVIEW

**Review by cpapazoglou — APPROVED** [review]
Thanks @mreishus!

LGTM!

**Comment by mreishus** [comment]
In submenus, the selected item is broken in calypso w/ nav unification.

**Comment by mreishus** [comment]
Hovering on top level menus is wrong color

**Comment by mreishus** [comment]
> After this commit is applied: _Fix for nav unification submenu [319cd03](https://github.com/Automattic/wp-calypso/commit/319cd038909c35fe3172623948bfa0ae39a16a79)_
> In submenus, the selected item is broken in calypso w/ nav unification.
> 
> 

Half of fix is in this PR: #47291

**Comment by mreishus** [comment]
Fixed
[add/color-scheme-light 46231e1aa7] Fix submenu selected text color

**Pull request merged**
