### PR TITLE
Gutenberg 7.7.1: Trigger E2E tests

### PR DESCRIPTION
**Pull request by andrewserong**
E2E integration tests against Gutenberg Edge.

Fixes in https://github.com/Automattic/wp-calypso/pull/40239

### CODE REVIEW

**Comment by ramonjd** [comment]
Re-triggering the tests to run against the recently launched 7.6.0-rc.1

See: https://github.com/Automattic/wp-calypso/issues/39689

**Comment by ramonjd** [comment]
Two bugs so far :

## TimeoutError: Timed out waiting for element with css selector of '.dashicons-no-alt' to be clickable

https://app.circleci.com/jobs/github/Automattic/wp-e2e-tests-for-branches/50326

Because of this change

https://github.com/WordPress/gutenberg/pull/19959/files#diff-b1dcc68a57b0f94413a4e191bc161f8dR82

## TimeoutError: Timed out waiting for element with css selector of '.editor-post-preview' to be clickable

https://app.circleci.com/jobs/github/Automattic/wp-e2e-tests-for-branches/50326

Because of this change

https://github.com/WordPress/gutenberg/pull/19082/files#diff-f46eebd6e860a1b5b5f823f6de751a55R188

**Comment by ramonjd** [comment]
Going to trigger to run 7.7.1 

See: https://github.com/Automattic/wp-calypso/issues/40078

**Comment by noahtallen** [comment]
closed in favor of #40451

**Pull request closed without merging**
