### PR TITLE
Jetpack Connect: Only auto-auth connections started by button-click

### PR DESCRIPTION
**Pull request by seear**
Previously it was possible to bypass the TOS and 'Approve' button in the jetpack connect process by arriving directly at a URL such as `wordpress.com/jetpack/connect?url=some-dotorg-site`.

Found during a SIRT review of the remote-install feature in p7rd6c-1dS-p2, although this problem pre-dates that feature.

Change the auto-approve logic so that only a button-click in Calypso (which acknowledges TOS) will cause the 'Approve' button to be skipped at the Authorize step.

Changes:
* Move the `persistSession` call from the action to the onClick handlers, so only a click saves a calypso session
* Move `cleanUrl()` to utils to make it available to jetpack-new-site component, so that session url can be sanitized
* Remove special handling for mobile apps (which should not auto-auth) now that arriving with `?url` query does not auto-authorize :party:

## Testing
Spin up a new jurassic.ninja site for each test.

#### Test 1: direct URL
* Arrive directly at https://calypso.live/jetpack/connect?url={jurassic-ninja-site}&branch=update/jetpack-connect-auto-auth
* Expected: You **should have to** click the _Approve_ button to complete the site connection

#### Test 2: mobile app flow
* Arrive directly at https://calypso.live/jetpack/connect?url={jurassic-ninja-site}&branch=update/jetpack-connect-auto-auth&mobile_redirect=wordpress://jetpack-connection
* Expected: You **should have to** click the _Approve_ button to complete the site connection

#### Test 3: Calypso new site page
* Calypso new site page: Go to https://calypso.live/jetpack/new?branch=update/jetpack-connect-auto-auth, and enter the site URL.
* Expected: You **should not have to** click the _Approve_ button to complete the site connection

#### Test 4: /jetpack/connect
* Go to https://calypso.live/jetpack/connect?branch=update/jetpack-connect-auto-auth, and enter the site URL.
* Expected: You **should not have to** click the _Approve_ button to complete the site connection

#### Summary
* The connection process should involve **one button click**. No more, no less.

### CODE REVIEW

**Comment by sirreal** [comment]
Testing some of these on calypso.live is a bit pesky. Pay attention to the URL because you'll be dropped back on `wpcalypso.wordpress.com`.

**Comment by sirreal** [comment]
In progress…

✅ Test 1: direct URL
⚪️ Test 2: mobile app flow
⚪️ Test 3: Calypso new site page
⚪️ Test 4: /jetpack/connect

**Comment by sirreal** [comment]
It's also a good idea to find the mobile cookie and clear it between tests 🙂

**Comment by sirreal** [comment]
> I think this went OK, but please verify @seear. The mobile flow hangs at "Finishing Up!" That's to be expected, right? It's where the mobile flow takes over again? The site was correctly connected.

Please just confirm this before shipping @seear

**Comment by seear** [comment]
Thanks for review @tyxla 

> Also, I think there were some external cases (in jetpack.com or some of the other related sites)

Seems the worst that can happen here is that customers will be presented with the _Approve_ button, so I'll go ahead and merge to get bypass closed off, and we can deal with any future issues if they arise.

**Pull request merged**
