### PR TITLE
Adds theme selection task to site checklist

### PR DESCRIPTION
**Pull request by aneeshd16**
#### Changes proposed in this Pull Request

* Adds a new site checklist task - "Choose a theme".

#### Testing instructions

* Please see D55847-code for testing instructions and details.
Screenshot:
image

### CODE REVIEW

**Comment by dzver** [comment]
LGTM but the backend diff has a few open questions so this needs to wait a bit.

**Review by dzver — APPROVED** [review]
LGTM

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/5485842

Thank you @aneeshd16 for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/5485842).

**Pull request merged**
