### PR TITLE
Reader: Update serif fonts by 1px

### PR DESCRIPTION
**Pull request by jancavan**
This fixes: https://github.com/Automattic/wp-calypso/issues/12683

### CODE REVIEW

**Comment by fraying** [comment]
Thanks, @jancavan 

I think you missed a couple spots:

1. Excerpt text in Combined Cards.
2. Body text on Fullpost.

That said, I'm not sure this is necessary. What do you think, @jancavan?

**Comment by jancavan** [comment]
> Excerpt text in Combined Cards.

I think the current size is good. Regular cards have a `16px` excerpt and a `19px` heading. Combined Cards are have a `14px` excerpt and `17px` heading, so now all headings are 3 pixels larger than their excerpts.

> Body text on Fullpost.
> Comment text on Fullpost.

Done.

**Comment by fraying** [comment]
@jancavan I still think the excerpt text in Combined Cards needs to increase by 1px. They look even weirder now that everything else is bigger.

**Comment by jancavan** [comment]
@fraying Addressed that in this PR: https://github.com/Automattic/wp-calypso/pull/12912

**Comment by fraying** [comment]
@jancavan Thanks so much.

**Pull request merged**
