### PR TITLE
FSE: sync-bash script agonistic from running-command.

### PR DESCRIPTION
**Pull request by retrofox**
#### Changes proposed in this Pull Request

Initially, the bash script was implemented to be executed via `npm`. Now, it's being executed via `yarn`.The way to get command variables isn't working with `yarn`, for instance

```
> yarn run sync:newspack-blocks --branch=master
```

`--branch` and `master` aren't properly gotten.

This PR attempts that the bash script is agnostic of the running-command, at least in terms of getting arguments.

#### Testing instructions

Sync the newspack-blocks using the following commands:

```
> yarn run sync:newspack-blocks --branch=master
```

```
> yarn run sync:newspack-blocks --release=v1.3.0
```

```
> yarn run sync:newspack-blocks --nodemodules
```

### CODE REVIEW

**Comment by obenland** [comment]
It still doesn't seem to work for me, this is my output:
```
$ yarn run sync:newspack-blocks --release=v1.3.0
yarn run v1.22.4
$ check-npm-client && ./bin/sync-newspack-blocks.sh --release=v1.3.0
Syncing files to FSE…
Updated Newspack version ''
Sync done.
```

`$MODE` seems to always be set to `npm`

**Comment by obenland** [comment]
I tested it with `--release`, `--branch`, and `--nodemodules`. The first two worked as expected, `--nodemodules` unfortunately didn't.

**Comment by marekhrabe** [comment]
Yeah, the block of code with the last mode was skipped in this implementation.

**Comment by retrofox** [comment]
I've added the `--nodemodules ` MODE. Thanks for the review.

**Comment by marekhrabe** [comment]
Your update to the script works well for me. I've noticed we need 2 updates in package.json, in order to have this fully functioning. 

We have moved from npm to yarn but there are still two occurrences of `npm run` in our package.json scripts and one of them is for this sync process. It will need to be updated in order to succeed on the CI.

**Comment by marekhrabe** [comment]
You can see the error by running `yarn run prepare`, before you replace npm with yarn.

**Pull request merged**
