### PR TITLE
Support label fix

### LINKED ISSUE #44287: Contact Support: Duplicated form labels for "How can we help?"
Screen Shot 2020-07-20 at 2 31 43 PM

#### Steps to reproduce

1. Starting at URL: `/help/contact`
2. The first and last fields have the same label, "How can we help?"

#### What I expected

Thinking in terms of a descriptive form field label for accessibility purposes, the label should briefly describe what we want the user to put in that field. Something like "Tell us more about the problem" or "Describe the issue" for the textarea input would prevent duplicated copy and give more context for the content of that field.

### PR DESCRIPTION
**Pull request by Dillweed5446**
cc: @sixhours

Changes proposed in this Pull Request

Change wording on support contact form to avoid duplicate wording. "How can we help?" was used twice.
*
Testing instructions

    Starting at URL: /help/contact
    Final field now says "Tell us more about the problem" instead of "How can we help?"

Before:
image

After:
image

Fixes #44287

### CODE REVIEW

**Comment by Dillweed5446** [comment]
@sixhours - I tried to revert the original PR but it didn't have any effect.  I'm sure I did something wrong.  In the end, I just closed the PR and created a new one from another branch.  Thanks for reviewing my changes!

**Comment by sixhours** [comment]
Pinging @zdenys and @davipontesblog as a couple of the more active Calypso HEs I know; does this change to the contact form label make sense? Anyone else I should ping in Happiness since this influences how folks contact us? :)

**Comment by sixhours** [comment]
Also good to note that the inline help button contact form is impacted by this change as well: 

Screen Shot 2020-07-23 at 2 19 29 PM

**Comment by zdenys** [comment]
Thanks for the ping 😊  Avoiding the duplicate makes sense to me, but I would avoid the word `problem`. For the majority of users, it may be the case, but some users may contact us for other reasons and `How can we help?` sounds more encompassing. `Problem` sounds negative. Not sure what would be the best alternative at the moment. Maybe `situation` or `case`? Editorial could chime in or someone else from Happiness.

**Comment by davipontesblog** [comment]
> Thanks for the ping 😊 Avoiding the duplicate makes sense to me, but I would avoid the word `problem`. For the majority of users, it may be the case, but some users may contact us for other reasons and `How can we help?` sounds more encompassing. `Problem` sounds negative. Not sure what would be the best alternative at the moment. Maybe `situation` or `case`? Editorial could chime in or someone else from Happiness. So I asked in [p1595530273273800-slack-CB0B2G43X](https://href.li/?https://a8c.slack.com/archives/CB0B2G43X/p1595530273273800)

I agree with @zdenys  and thanks @sixhours for pinging us here! I think we should avoid "problem" here, as we invite users to chat with us anytime, not only when they have problems. I second Denys's comments!

**Comment by benhuberman** [comment]
I second @zdenys re: avoiding "problem" if we can here -- the options we give at the top of the form include "Help getting started" and "I have a suggestion," and neither of these necessarily means there's a problem. 

An alternative option would be to keep the second instance of "How can we help?" at the bottom of the form, but change the first instance into something like this:

> You're reaching out to...

Followed by three slightly modified phrasings of the current options:
> Get started

> Report something isn't working

> Make a suggestion

@sixhours does this work for you? I can also continue to refine any of these options if the general direction makes sense.

**Comment by zdenys** [comment]
Posted at p7DVsv-90P-p2 for more discussion.

**Comment by Dillweed5446** [comment]
These changes sound good.  I'm not sure how to access the discussion channel posted above (if even possible for a non-Automattic employee).  I'll gladly integrate any changes and recommit once I find out what the preferred wording would be.

**Comment by akirk** [comment]
I don't see anything blocking from an i18n perspective, just please update the screenshot when before making the PR as ready for translation.

**Comment by Dillweed5446** [comment]
Ok, I updated the form to reflect the suggestions made by @benhuberman, and added a new screenshot to the original commit message as recommended by @akirk.  I'll keep an eye out for any other recommendations.  Thanks to everybody for all of their input!

**Pull request merged**
