### PR TITLE
Disable image editor on image being uploaded + add util isItemBeingUploaded fn

### LINKED ISSUE #8452: Image Editor: disable image editing of image being currently uploaded
After clicking "Done" on image editor, the edited image is being uploaded to our servers. However, users can still go to the currently uploaded image detail view and/or edit the image while it is being uploaded. This causes the following error:

selection_020

A solution to this is to disable image editing of the image which is currently being uploaded:

selection_021

Or disable the whole image detail view:

selection_019

/cc @gwwar @retrofox @artpi

### PR DESCRIPTION
**Pull request by lamosty**
Fixes #8452. After editing an image, it is being uploaded to our servers. However, users are still able to preview and modify meta properties of this image. In the PR, we add `disabled` attr to Edit Image btn while the image is being uploaded. We remove the attr after uploading is finished.

We also add a utility function for checking whether a media item is being uploaded. Tests are included as well.

## Testing

1. Open image editor on some image;
2. Click on "Done" so that the image is saved and being uploaded;
3. Click Edit on the image which is currently being uploaded;
4. Is the Edit Image button disabled? Does its `disabled` state changes to normal after the image is uploaded?

## Screenshot

selection_027

/cc @gwwar @artpi 

## Additional issue

In our team hangout, we thought that you can edit meta data of the image which is currently being uploaded. While that's true, after the image is uploaded, the meta is discarded and replaced with empty one. Q: should we still pursue the above approach of disabling image editor in currently uploaded image? If yes, before enabling image editor on prod, we need to have the issue fixed.

### CODE REVIEW

**Comment by retrofox** [comment]
> While that's true, after the image is uploaded, the meta is discarded and replaced with empty one.

I wonder why it happens because is something to fix.

> Q: should we still pursue the above approach of disabling image editor in currently uploaded image?

I do not agree with this approach. We are implementing a limitation instead of getting a real solution to the problem which is, IMHO,:

1) Do not clean data once the image has been uploaded.
2) Allow edit metadata beyond that the image is still loading.

**Comment by lamosty** [comment]
> I do not agree with this approach. We are implementing a limitation instead of getting a real solution to the problem which is, IMHO,: [...]

Sorry, I might have used wrong words when describing the question. In this PR, I'm **not** cleaning any data or disallowing limiting metadata. I'm simply adding `disabled` attribute on the "Edit Image" button while the image is being uploaded because until it's not fully uploaded, we can't get its URL and therefore can't edit it.

The question I was asking was that: wouldn't it be faster to simply disallow editing anything on the image which is currently being uploaded? That way, we wouldn't have to fix anything before releasing image editor. If, on the other hand, we go with the approach in this PR, we first need to also fix the problem in which metadata are wiped after image gets uploaded before we can enable the image editor on production. It's a blocker.

**Comment by retrofox** [comment]
> I'm not cleaning any data or disallowing editing metadata.

I didn't say that. I only add a different approach like a solution to this issue.

> I'm simply adding disabled attribute on the "Edit Image" button while the image is being uploaded because until it's not fully uploaded, we can't get its URL and therefore can't edit it.

~~You don't need the `URL` to update the metadata, right?~~

Sorry, finally I got it. Technically now we aren't editing the image. What we are really doing is adding a new image and for this reason we need the `ID` to edit the metadata. Am I right?

**Comment by gwwar** [comment]
Ah ic, so I think I understand what you're describing:

1. Set network tab to throttle to a slower network speed
2. Upload a larger size image
3. Click Edit
4. Update some metadata like title, description, caption
5. Restore network speeds
6. When file is fully uploaded, updated fields are cleared

cc @aduth is this a regression or expected behavior

**Comment by gwwar** [comment]
I repro'd the above issue in prod. Let's solve that in another PR. 

👍 Thanks for keeping the janitorial commit separate. Code looks good and tests well. Let's 🚢

**Comment by lamosty** [comment]
Thanks for the reviews @gwwar and @retrofox!

> I repro'd the above issue in prod. Let's solve that in another PR.

Yep, it's a current issue, not something I introduced here. :) I need to be more descriptive next time!

**Pull request merged**
