### PR TITLE
Page: Add hierarchical ordering to listing

### PR DESCRIPTION
**Pull request by unDemian**
I added hierarchical support for pages. In order for this to work `D3508-code` has to be merged on the API side. Client side sorting and time markers were disabled for pages. 
This is my first Calypso PR please feel free to guide me if I missed something :)

Example
screen shot 2017-01-08 at 11 16 47 pm

Updates
* Add field `hierarchical` to API request
* Disable client side sorting of pages
* Disable time markers used for chronological ordering
* Add indentation for children pages similar to taxonomies

Thanks

### CODE REVIEW

**Comment by aduth** [comment]
Thanks for working on this. If I were to give some high-level feedback, I think we should focus on the components used on the custom post types list screen. I don't think we'll want to keep the existing posts and pages screens around for much longer, with blockers being customization of the rendered post item and hierarchical rendering.

To see what I mean, here's an example of the CPT components rendering pages for a site: https://wordpress.com/types/page

This page isn't normally accessible from the sidebar, but the last path segment can support any post type. It's currently used in production for all post types except posts and pages.

The relevant components for these can be found at:

- https://github.com/Automattic/wp-calypso/tree/master/client/my-sites/types
- https://github.com/Automattic/wp-calypso/tree/master/client/my-sites/post-type-list (docs are out-of-date, no longer WIP)

**Comment by unDemian** [comment]
Thank you for the feedback. I was not aware of those components. I updated the PR to reflect the support for hierarchical ordering for these components too.

screen shot 2017-01-09 at 11 44 00 pm

I am not sure if this is the correct abstraction level for this setting. Please advise.
Thanks

**Comment by lancewillett** [comment]
See also https://github.com/Automattic/wp-calypso/issues/3906

**Comment by jonathansadowski** [comment]
Thanks for giving this a go @unDemian. We opted to launch hierarchies in #13871 using an approach that wouldn't require any server-side code changes. As this PR is now out of date, I'm going to close it.

**Pull request closed without merging**
