### PR TITLE
Domains: fix contact form i18n

### PR DESCRIPTION
**Pull request by yoavf**
Two strings aren't currently translated in that screen:
- The title, because it uses a dynamic context, which i18n-calypso cannot parse (so the string exists in the language file without a context)
- The "Registering for a company..." - because the context is skipped due to a bug in i18n-calypso. See https://github.com/Automattic/i18n-calypso/pull/37

see #13854

In both cases, the context is not very helpful, so we can just drop it.

Testing: switch to French, make sure the strings are translated, like this:
screen shot 2017-05-11 at 13 02 43

### CODE REVIEW

**Comment by klimeryk** [comment]
Thanks for catching these! The first one is my fault, actually - I knew that dynamic strings would not work (obviously), but I did not realize the same applies to the options (which kinda makes sense, in hindsight).

I'm not happy with the usage of the `i18n` library, though. I understand that the linter was not happy with `this.translate`, but I thought that the proper way was to convert he component to a class and use `localize`? (and in result, `this.props.translate`)

**Comment by yoavf** [comment]
> I'm not happy with the usage of the i18n library, though. I understand that the linter was not happy with this.translate, but I thought that the proper way was to convert the component to a class and use localize? (and in result, this.props.translate)

The linter is happy with [both](https://github.com/Automattic/eslint-plugin-wpcalypso/blob/master/docs/rules/i18n-no-this-translate.md) - I just implemented the quickest solution.

**Comment by yoavf** [comment]
There, I fixed it ;)

**Comment by yoavf** [comment]
Actually, nope. Now it's broken :(

**Pull request merged**
