### PR TITLE
Framework: Redirect old /menus routes to /customize/menus

### LINKED ISSUE #12980: Menus: `/menus` route is still directly accessible.
Calypso Menus have been disabled in that the Menus link in the sidebar will now direct the user to the Customizer since #12967  . However, the `/menus` route is still directly accessible by URL. 

My first thought was to just remove the section, which gives a 404, but @sirbrillig pointed out that a redirect would be better. I then considered using `page.redirect()` in `my-sites/menus/index.js`, but ultimately we don't want that section and code to be there at all. Additionally, it's not a simple redirect; it will depend on whether or not the site is a [Jetpack site or not](https://github.com/Automattic/wp-calypso/blob/2013d21b29264416405c2b9b0d1a0a70e2f7b61f/client/my-sites/sidebar/sidebar.jsx#L226).

@ockham any suggestions how best to proceed?

### PR DESCRIPTION
**Pull request by ockham**
Fixes #12980. Simpler approach than #12998.

This consists of two parts:
* A 'dumb' server side redirect that takes every user from `/menus/:site?` to `/customize/menus/:site`
* A 'smart' client side redirect, see commit description:

> This is for redirects from the old `/menus` section. When a user points their browser to `/menus/myjetpacksite.com`, the server redirects them to `/customize/menus/myjetpacksite.com`. We then check if the given site is a Jetpack site. If it is, we can't use the WP.com customizer. Instead, we redirect them to their self-hosted site's own customizer.
> The `getMenusUrl()` selector we're using is also used by the sidebar -- this way, we ensure that we always mirror its behavior. It also covers other edge cases, such as a user with unverified e-mail.

(We can't do this 'smart' redirect on the server side, since we need information about a user's sites, which isn't available there AFAIK.)

To test:
* Land on http://calypso.localhost:3000/menus and http://calypso.localhost:3000/menus/<yoursite>
* Verify that you're being redirected to http://calypso.localhost:3000/customize/menus and http://calypso.localhost:3000/cusotmize/menus/<yoursite>, respectively
* Use a JP site for <yoursite>. Verify you're redirected to that site's customizer.
* With a user with unverified email, check that you're redirected to `/customize/<yoursite>` (no `/menus` route fragment)

### CODE REVIEW

**Comment by kwight** [comment]
A `/menus` redirect actually has [three possible results](https://github.com/Automattic/wp-calypso/blob/master/client/my-sites/sidebar/sidebar.jsx#L226): `/customize/menus` (normal dotcom), `<site>/wp-admin/customize.php?autofocus[panel]=nav_menus` (Jetpack), and `/customize` (dotcom without verified email).

**Comment by ockham** [comment]
> A `/menus` redirect actually has [three possible results](https://github.com/Automattic/wp-calypso/blob/master/client/my-sites/sidebar/sidebar.jsx#L226): `/customize/menus` (normal dotcom), `<site>/wp-admin/customize.php?autofocus[panel]=nav_menus` (Jetpack)

Looking at some [code](https://github.com/Automattic/wp-calypso/blob/03999d15a97fcd54f9a3ee39ad6feff927bbb58b/client/my-sites/customize/panels.js#L12), seems to me that `customize/menus` really embeds pretty much the same URL format as the direct JP links. Think the regular customizer links could work with that OOTB?

**Comment by ockham** [comment]
Hmm no, that doesn't work.

**Comment by ockham** [comment]
Blocked by https://github.com/Automattic/wp-calypso/pull/13101 (so we don't duplicate all that code).

**Pull request merged**
