### PR TITLE
Pattern Assembler: Update styles on the main screen

### PR DESCRIPTION
**Pull request by arthur791004**
#### Proposed Changes

* Update the copy of the description
* Update the styles of the main screen

| Before | After |
| - | - |
| image | image |
| image | image |

Hover styles like any other link. 

image

#### Testing Instructions

* Go to`/setup/site-setup?siteSlug=<your_site>`
* Continue until you land on the Design Picker
* Click the "start designing" button at the end of the Design Picker
* Verify whether the new styles look good

#### Pre-merge Checklist

- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

Related to https://github.com/Automattic/dotcom-forge/issues/1251

### CODE REVIEW

**Comment by taipeicoder** [comment]
I noticed that there's a gap where the + button and text hover effect kicks in, but the mouse cursor stays in default and clicking does nothing. 

https://user-images.githubusercontent.com/797888/203493356-8aaf07b2-34f0-48cf-a14c-4bcc201256a8.mp4

**Comment by taipeicoder** [comment]
Users might get confused as to why they cannot move the pattern up. Can we perhaps add a visual indicator (thicker line?) to differentiate header, section, and footer? cc: @SaxonF  
Screen Shot 2022-11-23 at 3 39 19 PM

**Comment by arthur791004** [comment]
> Users might get confused as to why they cannot move the pattern up.

Agreed and that's why we have the icon in the previous version...

**Comment by arthur791004** [comment]
> I noticed that there's a gap where the + button and text hover effect kicks in, but the mouse cursor stays in default and clicking does nothing.

Fixed!

**Comment by taipeicoder** [comment]
I wonder if we should also update these copy for consistency. Otherwise, the changes look good to me! I'll leave it up to you to decide to change them or not 🙂
Screen Shot 2022-11-23 at 4 47 27 PM
Screen Shot 2022-11-23 at 4 47 34 PM

**Review by taipeicoder — APPROVED** [review]

**Comment by arthur791004** [comment]
> I wonder if we should also update these copy for consistency.

Oh yes, we should!

**Comment by fushar** [comment]
I think we need to avoid the term "sections" because it is not a WP concept (stealing the argument from @miksansegundo). Maybe `Add patterns` instead?

I'm scared now as we have conflicting opinions in this implementation phase 😂

**Comment by autumnfjeld** [comment]
> I wonder if we should also update these copy for consistency. 

I think "Choose a header" makes sense on this page.  User sees them and is actually choosing (making choices).

**Comment by SaxonF** [comment]
Just to move this forward to CfT.

1. We should work on using category names for patterns. This shouldn't block CfT.
2. "Add sections" is fine for now

> Agreed and that's why we have the icon in the previous version..

Ok so this may be annoying, but just to get this out, lets re-add the icons but use the Gutenberg group icon instead for now. That should at least help with the "icon looking like drag" issue and is at least consistent with the layers panel in the editor.

**Comment by arthur791004** [comment]
> I think "Choose a header" makes sense on this page. User sees them and is actually choosing (making choices).

@autumnfjeld I'm okay with both. As the "Add a header" is consistent with the main screen, let's leave it as it is and move forward to the CfT. What do you think?

**Comment by fushar** [comment]
I (very) slightly prefer `Add a header` because the header itself is actually optional (no need to actually "choose" a header) 😄

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/7636554

Thank you @arthur791004 for including a screenshot in the description! This is really helpful for our translators.

**Comment by autumnfjeld** [comment]
I'm fine with all the decisions above.   So no action needed, 
Just a semantic comment: 

> I (very) slightly prefer Add a header because the header itself is actually optional (no need to actually "choose" a header) 😄

@fushar I meant that "Choose a header" makes sense when user is looking at a list of headers in the pattern panel. They are choosing from a list.   So the idea is the user is already in there, and might make a choice.   In this the case "Add"  or "Choose" both imply we want to the user to do something--these are both instructional verbs.  (The user has no idea about things being optional or not, we haven't said anywhere that something is optional or required. Each user will have their own interpretation of what they "should" or "need" or "want" to do.)

Add a header makes sense on the "list panel", the "Design your home" panel.   (We need a better name than "list panel", its not descriptive)

**Comment by autumnfjeld** [comment]
> Users might get confused as to why they cannot move the pattern up. Can we perhaps add a visual indicator (thicker line?)

I agree with you @taipeicoder , the icon doesn't speak to me about differentiation between these patterns.  Especially in a view like this.  No action to take, I'm just chiming in that I think a thicker line might be nice. Could be done in the future. cc: @SaxonF  
image

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/7636554).

**Pull request merged**
