### PR TITLE
Layout Component: Convert to ES6 class

### LINKED ISSUE #27338: Modernize the Masterbar and Layout component code
The `Layout` and `Masterbar` components (`client/layout/...`) contain some legacy code that can be removed or modernized. The instructions that follow will lead to a series of very nice cleanup PRs -- can be a project for a small team.

**1. Remove the `sites` prop**
The `newestSite` method is not used anywhere. The `Masterbar` component doesn't need a `sites` prop. All occurences of `this.props.sites` can therefore be removed.

**2. Stop passing `user` prop to `Layout`**
Remove the legacy `import userFactory from 'lib/user'` from `client/controller/index.web.js` and stop passing the created `user` object as a prop to `Layout`. All places that use the `user` prop should get the information from Redux.

Also, the `getCurrentUser` selector can be replaced by `isUserLoggedIn` one, which better explains what we are trying to check.

Of course, `Layout` and `MasterbarLoggedIn` should stop using the `user` prop first:
- the `renderMasterbar` method uses `user` to determine if user is logged in and render logged out master if she's not. Is this code even needed? The `Layout` component is already guaranteed to be rendered only for logged-in users. Or is it not? Verify and remove.
- the `user` info for `Gravatar` in masterbar should be retrieved from Redux
- if the `Notifications` component needs to see the `has_unseen_notes` property of user, it should retrieve that info from Redux in its own `connect` call. Can it safely use the `hasUnseenNotifications` selector? That selector seems to do more than just read `has_unseen_notes`. Consult with notifications experts.

After all usages of `user` are removed, `Layout` can stop using the `observe` mixin and can be codemodded to ES6 class :tada:

### PR DESCRIPTION
**Pull request by brbrr**
#### Changes proposed in this Pull Request

* get rid of not needed `user` mixin
* convert `Layout` createReactClass to ES6 class

#### Testing instructions

* No visual changes. Make sure that E2E tests passed
* Sanity check random logged-in pages 

Fixes #27338

### CODE REVIEW

**Comment by jsnajdr** [comment]
@brbrr Is this PR ready for review or do you plan to do more work here? The branch contains several other commits from unrelated PRs including some merges... That's confusing.

**Comment by brbrr** [comment]
@jsnajdr this PR actually ready for review, but it looks like I mixed something up when I rebased the branch to include the revert commit https://github.com/Automattic/wp-calypso/pull/27619. Sorry for the confusion. Should I try to fix that somehow?

**Comment by jsnajdr** [comment]
> Should I try to fix that somehow?

Yes please, rebase (`rebase -i` provides tools to remove, reorder and squash existing commits) the branch so that it contains only the relevant commits. Right now, it contains changes that certainly shouldn't be merged.

**Review by jsnajdr — APPROVED** [review]
Looks really nice after the rebase :+1: :ship:

**Pull request merged**
