### PR TITLE
Reader: add animation for inline recommendations

### PR DESCRIPTION
**Pull request by jancavan**
We styled Cold Start's UI in: https://github.com/Automattic/wp-calypso/pull/5264

In this PR, we'd like to add animation for when new recommendation cards get appended inline within your current recommendations.

/cc @bluefuton

### CODE REVIEW

**Comment by jancavan** [comment]
@mtias in https://github.com/Automattic/wp-calypso/pull/5538/commits/cb3e83b3c7b3e8bd23466a102940975748501681, I've fixed the CSS issues mentioned in https://github.com/Automattic/wp-calypso/pull/5264/files#diff-cdafeea075be2f2d9c934a9a1d215cceR15

**Comment by jancavan** [comment]
Note: In https://github.com/Automattic/wp-calypso/pull/5538/commits/1a4e022e372b5d996302c90ddc98fe07794146df#diff-680a8b9b8cda813cf5a407a9bbca0bf6R34, this line solves the issue where some elements that are positioned absolute (in this particular case, the Follow/Following SVG icons) in the second column do not show up when using `column-count`.

Apparently, this is a known issue: https://bugs.chromium.org/p/chromium/issues/detail?id=84030

**Comment by bluefuton** [comment]
:shipit: 

We have a little glitch with link colours in the post preview h1, but we can tidy that up in a later PR.

**Comment by mtias** [comment]
Thanks! There's a few issues with the classnames / component names remaining to clean up later (in general within Reader) but this fixes the bugs :)

**Pull request merged**
