### PR TITLE
Improve `url` deprecation information

### PR DESCRIPTION
**Pull request by sgomes**
#### Changes proposed in this Pull Request

- Improve the eslint error message
- Add a README to `lib/url` with more information

#### Testing instructions

Documentation / linter config changes only.

### CODE REVIEW

**Review by sirbrillig — APPROVED** [review]
Looks much improved! Thank you!

**Comment by sgomes** [comment]
Thank you for the review, @sirbrillig! 👍

**Review by wp-desktop — CHANGES_REQUESTED** [review]
WordPress Desktop CI Failure for job "wp-desktop-source".

@sgomes please inspect this job's build steps for breaking changes at [this link](https://circleci.com/gh/Automattic/wp-calypso/818430). For temporal failures, you may try to "Rerun Workflow from Failed".

Please also ensure this branch is rebased off latest Calypso.

**Comment by sgomes** [comment]
The above message appears to be because `wp-desktop` tests didn't complete before this PR was merged. This PR contains documentation / linter config changes only, so no E2E testing is needed.

**Pull request merged**
