### PR TITLE
Navigation: add sidebar drafts count and link

### PR DESCRIPTION
**Pull request by mtias**
This uses `DraftsCount` button in the publish section of the My Sites sidebar to directly link people to the drafts area.

It's enabled behind a feature flag so we can determine whether the lack of text is confusing or not.

image

Alternative option:

image

### CODE REVIEW

**Comment by drw158** [comment]
Does this make sense all items that go under Publish, like CPTs and possibly a separate Media item in the future? Will the link go to Post drafts?

Might be sort of strange, but what if this Drafts count takes the place of the Posts "Add" button? If there are no drafts, then the Add button would be displayed.

**Comment by mtias** [comment]
@drw158 hey, yes, explored a few concepts like: 

image

But didn't felt great.

Interesting about replacing the "add" button. Though it seems we sacrifice too much. Also a bit concerned with mistaking it as the total number of posts.

**Comment by folletto** [comment]
> Does this make sense all items that go under Publish, like CPTs and possibly a separate Media item in the future? Will the link go to Post drafts?

I agree on your perspective. We (well, Matias mostly) iterated a lot on that bit, and we found that from an architecture perspective makes sense to be on the side of Add, but on the other hand it's super confusing (posts counts?). At the top there might make more sense... and might enable in the future a unified draft page, which might be like the "workspace" of all the publishable content. :)

**Comment by drw158** [comment]
I like the idea. I don't think I would've guessed what the number means without the label. Maybe it's something that the user will need to learn, then eventually take away the label. I'd be interested in hearing horizon feedback on this. 

I think the most common convention is to have a separate Drafts sidebar item with a counter on the right, similar to an email client, but I know we don't want to add anymore items.

**Comment by mtias** [comment]
Orange is an interesting thought to explore. (Mind this is on hover.)

**Comment by mtias** [comment]
Going to merge so we can get a sense for it.

**Pull request merged**
