### PR TITLE
SiteSelector: Redirect to slug-based paths instead of siteId-based paths

### PR DESCRIPTION
**Pull request by oskosk**
Currently, the site selector is redirecting to paths using the numeric siteId. 

**Before**

before

**After**

after

#### Testing instructions

1. Visit `/settings` or `/sites` without a site slug to get the site selector.
1. Click any of your sites
1. Confirm that you're redirected to an URL that has the slug on it instead of the site id.

### CODE REVIEW

**Comment by oskosk** [comment]
@mcsf I pinged you because I think the changes introduced in #14028 made the site selector behave like this and don't really know if this was intended or not.

**Comment by mcsf** [comment]
Please don't merge 😅 see #14024.

**Comment by oskosk** [comment]
@mcsf Alright, but what's the bottom line there. The three PRs mentioned there are already merged and one of them introduced this behaviour.

**Comment by mcsf** [comment]
@oskosk I'm finishing up a fix which I'll push to this branch

**Comment by oskosk** [comment]
Ah got it!

**Comment by oskosk** [comment]
Awesome @mcsf . Thanks!

**Comment by mcsf** [comment]
@oskosk: pushed; let me know if it's a satisfactory fix.

Sorry about the terse comment asking not to merge. I wanted to be quick to prevent merging before providing more details. The proper answer is that I've been working on eliminating existing occurrences + preventing new ones (by creating a new ESLint rule) of the anti-pattern of creating functions in `mapStateToProps`, especially functions bound to `state`. In this particular PR, I wanted to avoid:

```js
export default connect(
	( state ) => {
		return {
			selectedSite: getSelectedSite( state ),
			sites: getSites( state ),
			getSiteSlug: siteId => getSiteSlug( state, siteId )
		};
	}
)( Sites );
```

**Comment by oskosk** [comment]
Totally understandable @mcsf . Thank you for that work there.

**Comment by oskosk** [comment]
@mcsf works awesomely. Shall I merge ?

**Comment by mcsf** [comment]
LGTM :)

**Pull request merged**
