### PR TITLE
Revisions #1: State > Users: Add `USERS_REQUEST` action w/ data-layer support

### PR DESCRIPTION
**Pull request by bperson**
This is the first chunk coming from my WIP PR to introduce post revisions in calypso: #13367 

In the REST API v2, most ressources ( posts, revisions, etc... ) return an author ID, instead of an hydrated ressource with more information ( display name, username ... ). This PR introduces the `USERS_REQUEST` action, and the necessary code in the data layer to trigger an API v2 request. It then normalises the API response into something similar to what's returned from the API v1 and loads it under the `users` key in Redux.

In the case of post revisions this gets called after we load a set of revisions, a list of all authors ID is created and used to dispatch a `USERS_REQUEST` action to request it, before displaying it in the revisions list ( see #13367 for more context )

This code is currently not used by any part of Calypso, to test it you can either run the unit tests, or trigger a `USERS_REQUEST` manually from the console:

`window.dispatch( { type: 'USERS_REQUEST', siteId: <sideID>, ids: [ <userID> ] } );`

### CODE REVIEW

**Comment by seear** [comment]
Code looks good and tests well for me.

Question—will this ever need to handle a paging scenario, where the number of users requested is more than received in the first set of results? In my testing I get max 10 results back.

**Comment by bperson** [comment]
Just a head's up that yesterday's update should work fine but it contains a workaround for pagination (marked with a FIXME): we try to fetch a new page if the one we just received is full (number of items received == number of items per page).

@nylen was kind enough to add the pagination headers to the whitelisted list of headers used in `wpcom-proxy-request`'s iframe on WP.com. Now there are a couple of PRs to bubble up those headers: first in [wpcom.js](https://github.com/Automattic/wpcom.js/pull/213) and then in the [data-layer](https://github.com/Automattic/wp-calypso/blob/master/client/state/data-layer/wpcom-http/index.js#L57).

I don't know whether we should wait for the effort to have proper access to the pagination headers, or whether we should merge this with the current FIXME comment. In the meantime, I will create the other PRs coming out of #13367

**Comment by nylen** [comment]
`wpcom` version 5.4.0 has been released with this change (assuming that I did the build process correctly).

> I don't know whether we should wait for the effort to have proper access to the pagination headers

Seems OK to me to wait, unless:

1. the PR still works well as currently written (for example, what happens if there are exactly 10 users?  there will be an extra network request; will this break anything?)
2. we think it will take a while to get the data-layer changes in

**Comment by nylen** [comment]
Oh, also, the `wpcom.js` change that adds headers could break something if there is Calypso code currently expecting headers, which will behave differently when it suddenly receives them.  This seems very unlikely, but it's probably worth running the e2e test suite against the PR that upgrades `wpcom.js` in any case.

**Comment by bperson** [comment]
> wpcom version 5.4.0 has been released with this change (assuming that I did the build process correctly).

hehe, it's been done correctly :) , #14157 bundles the shrinkmap update + the data layer updates.

> the PR still works well as currently written (for example, what happens if there are exactly 10 users? there will be an extra network request; will this break anything?)

Not optimal + I don't find the assumption that a pagination system gets us "full" pages to be extremely safe. ( I haven't dug in WP REST API codebase but I've seen pagination systems out there with an extra filtering step after getting paginated data from a database where you could end up with "not full" pages in the middle of the dataset, I hope WP isn't doing it though :D )

> Oh, also, the wpcom.js change that adds headers could break something if there is Calypso code currently expecting headers, which will behave differently when it suddenly receives them. This seems very unlikely, but it's probably worth running the e2e test suite against the PR that upgrades wpcom.js in any case.

Yup, I minimised the amount of changes introduced - at least in the data layer - in #14157 so we should be safe in there. But for any code that isn't using the data layer, this is a very real possibility :)

**Comment by nylen** [comment]
> I hope WP isn't doing it though :D

:grimacing:

I don't see anything like this in the users endpoint code ([#](https://core.trac.wordpress.org/browser/tags/4.7.5/src/wp-includes/rest-api/endpoints/class-wp-rest-users-controller.php#L276), [#](https://core.trac.wordpress.org/browser/tags/4.7.5/src/wp-includes/class-wp-user-query.php#L592)) but for posts this is definitely possible:  [#](https://core.trac.wordpress.org/browser/tags/4.7.5/src/wp-includes/rest-api/endpoints/class-wp-rest-posts-controller.php?marks=307-309#L296)

**Comment by bperson** [comment]
Since #14157 got merged and this one rebased on the latest master, this is "free" to be merged. Any last minute review @nylen @seear @youknowriad ?

Merging this one will unblock #14241

**Comment by seear** [comment]
@bperson when I dispatch a request from the console for a site with a lot of users, I see the first page come back, then no further network requests:

`window.dispatch( { type: 'USERS_REQUEST', siteId: 89813773 } );`

screen shot 2017-05-25 at 14 23 51

Should I be seeing the further requests?

This also begs a further question—would we ever really want to make, for example, 48 requests to fetch all these users?

**Comment by seear** [comment]
>  I see the first page come back, then no further network requests

My mistake, I didn't have the latest commit. Testing again...

**Comment by seear** [comment]
Ok, I see the full 48 responses now :)

So, my second question stands—are we comfortable with potentially having this much network traffic triggered automatically?

**Comment by bperson** [comment]
> My mistake, I didn't have the latest commit. Testing again...
yep I ended up push-forcing a lot :/ 

> So, my second question stands—are we comfortable with potentially having this much network traffic triggered automatically?
For its current use case - revisions -, I would be confortable with it. We'll be limited by the number of unique authors that edited the same post: https://github.com/Automattic/wp-calypso/pull/14241/files#diff-f6f865948e5e106b927667c32c51bde5R87

Considering the [core revisions API doesn't have pagination](https://core.trac.wordpress.org/ticket/40510), I'm pretty sure we will get garbage from the revisions API (timeout?) OR nuke the browser with too much data from that response before we hit a case where the number of unique authors that edited the same post gets unreasonably large.
If we want to be ultra safe, we could only request users from "visible" revisions but it would be even better to introduce that notion of "visible" revisions once we're able to lazy-load revisions from the API imho.

**Pull request merged**
