### PR TITLE
Reader: Fix in-stream recs broken in narrow widths

### PR DESCRIPTION
**Pull request by jancavan**
This fixes: https://github.com/Automattic/wp-calypso/issues/9690

Basically redid all of the styling that was already in place for in-stream recs so I'm going to need to back and fix spacing issues that were supposedly already addressed in: https://github.com/Automattic/wp-calypso/pull/9490#issuecomment-262664725. I'll take care of those in a separate PR.

**Before:**
screenshot 2016-11-29 12 23 51

**After:**
screenshot 2016-11-29 12 23 01

### CODE REVIEW

**Comment by jancavan** [comment]
@fraying I noticed some in-stream recs that have no excerpts which don't look great. I think we may have removed them in RPs (or at least deprioritized them)?

screenshot 2016-11-29 12 30 18

**Comment by fraying** [comment]
@jancavan: @aaronyan and I discussed this (recs w/o excerpts). It's on @gibrown's list.

**Comment by gibrown** [comment]
@fraying can recs with no text just be shown as a larger image similar to the full image cards?

**Comment by fraying** [comment]
@gibrown As an interim duct-tape thing until we can filter out excerptless recs, or as a permanent solution?

**Comment by gibrown** [comment]
@fraying as a permanent solution there are certainly cases where recommending image or video only sites is the best thing to recommend.

**Comment by fraying** [comment]
@gibrown It's a good potential solution down the line, but there are lots of issues around to consider. Removing excerptless recs is a better solution in the short term.

**Pull request merged**
