### PR TITLE
Playwright: The great Selenium deletion.

### PR DESCRIPTION
**Pull request by dpasque**
#### Changes proposed in this Pull Request

By Jove, it's finally here!! 😍 

With no more scripts or dependencies on mocha and selenium in our E2E tests, we can finally deprecate and delete all the old code related to the old framework!

This PR removes...

- Any remaining Selenium specs
- All of the old library code under `lib`
- Unneeded mocha/magellan configurations
- Old scripts that aren't used in CI anymore
- A giant clean-up of the packages in the e2e `package.json`

It does not...
- Change/clean-up the encrypted config structure. This will come in a future dedicated PR.

#### Testing instructions

- [x] Everything must still pass in all CI forms!

Related to #

### CODE REVIEW

**Comment by noahtallen** [comment]
I _love_ to see this change! BTW, do we still need the [`magellan-mocha-plugin`](https://github.com/Automattic/wp-calypso/blob/ad0c88e2c183fa5ef9ed6275fd0734331045e7f4/packages/magellan-mocha-plugin/) and [`mocha-debug-reporter`](https://github.com/Automattic/wp-calypso/blob/de6144be27aefaeabe7593e7aac0682f557afa8b/packages/mocha-debug-reporter/)?

**Comment by dpasque** [comment]
>BTW, do we still need the [magellan-mocha-plugin](https://github.com/Automattic/wp-calypso/blob/ad0c88e2c183fa5ef9ed6275fd0734331045e7f4/packages/magellan-mocha-plugin/) and [mocha-debug-reporter](https://github.com/Automattic/wp-calypso/blob/de6144be27aefaeabe7593e7aac0682f557afa8b/packages/mocha-debug-reporter/)?

@noahtallen  I was wondering the same thing! At first, I balked a bit at pulling them as they were their own packages, and I didn't know a lot about their history. That said, from the dependency tree, they seemed to be _only_ be used by the old selenium E2E tests, so I think they're probably safe to remove.

@bsessions85 @worldomonation Do you know if there's any reason to keep these packages around if we have removed the other Selenium stuff? I just want to make sure there's not any hidden assumptions I might be missing!

For now I can delete them, but will do it in its own commit so it's easy to roll back before merge.

**Comment by noahtallen** [comment]
I just checked, and they do _not_ appear to be published to npm. To me, that indicates that if they are no longer used elsewhere in Calypso, they can be removed :)

I imagine they were added as packages to improve modularity more than anything :)

**Comment by worldomonation** [comment]
@dpasque @noahtallen IIRC the Magellan packages are maintained by us since upstream is now deprecated. It is likely safe to remove.

**Review by worldomonation — APPROVED** [review]

**Pull request merged**
