### PR TITLE
Add/domains prototype

### PR DESCRIPTION
**Pull request by scruffian**
THIS IS NOT PRODUCTION CODE

This is just a prototype to play with some ideas for how /domains could work. These ideas are subject to change. The technical solutions aren't well thought through or final.

Technical considerations for the final implementation
- Split to bundle at /domains so that the logged out bundle is smaller
- Make the site-selected signup flow work and disable the blog option
- Save the domain in the site title

### How to review the flows
Kudos to @drewblaisdell for instruction, this seems to be generally how you test this:

1. Visit [/start/domain-first](http://calypso.localhost:3000/start/domain-first) while logged out.
2. Select a domain.
3. Complete signup for a new account.
4. Purchase the domain.
5. You should be redirected to /domains/manage/:site. You're in the My Site section of Calypso, but there are no links on the sidebar except to the sitepicker.
6. Clicking Set Up Site takes you to a special signup flow to set up your site (i.e. turn it from a domain-only site into a normal site). As far as I can tell, this flow does not work yet.

Questions etc belong on P2...

### CODE REVIEW

**Comment by drewblaisdell** [comment]
The structure of Calypso is a little strange with "domain-only sites", as the user finds their domain under `My Site`.

I spent a little time thinking about what would happen if we added a third option to the header, `Domains`, that appeared only for users with a domain-only site.

**Pros**
- Less confusing for users with a domain-only site - they manage domains under `Domains` instead of `My Site[s]`.
- We wouldn't need to update (and thus, increase the complexity of) the `my-sites` code, as we wouldn't be sharing the same routes. Another benefit here is that we wouldn't need to reuse the sitepicker, and could create something simple and domain-specific.
- We could update the domain management components such that they could be mounted and reused under `Domains`
- We could hide the user's auto-generated subdomain from the URL (as we would be creating a new route under domains).

**Cons**
- Domain management becomes confusing for users with both a site with a domain and a domain-only site. The confusions seems to come from a problem that we're creating with `/domains`: domains are now both top-level objects (like sites) and subordinate to sites. We'd need to either:
   - Require all users manage their domains under the top-level `Domains` section. This is a little confusing, as not all of these domains would be associated with a site, and would be a big change for existing users.
   - Allow users to manage domains in two different places: domain-only sites through the top-level `Domains` section and domains that are attached to existing sites through domain management under `My Sites`.

My initial reaction to that con is that it is probably too big to worry about the benefits here, but I thought I'd mention this to see if you/others have thought about this.

**Comment by gziolo** [comment]
> The structure of Calypso is a little strange with "domain-only sites", as the user finds their domain under My Site.
> 
> I spent a little time thinking about what would happen if we added a third option to the header, Domains, that appeared only for users with a domain-only site.

This was also my concern from the beginning. I mentioned that when talking with @fabianapsimoes and @scruffian. I fully support the idea of having another option in the header. My reasoning is supported by the fact that we are targeting also new users with this new feature. If I visited WordPress.com for the first time and I have just bought a domain, I would be very confused to see only My Sites link in the header. My expectation would to have link to the list of domains in the first place, as from my perspective I haven't got any sites created yet.

> Allow users to manage domains in two different places: domain-only sites through the top-level Domains section and domains that are attached to existing sites through domain management under My Sites.

You can always leave the part that allows to change primary domain for the site as it is and move all other screens related to domain management to the new My Domains section. We already had a chat with @scruffian about the concept of new page which lists all domains. It would allow to introduce also bulk actions on domains.

**Comment by scruffian** [comment]
My main concern with having /domains as a top level menu item is that the average user doesn't know what a "domain" is and how that is separate to a "site" (based on _some_ research - we could do more to validate/disprove this).

There are some other concerns to take into account, in addition to those mentioned by @drewblaisdell:
- This would constitute a total overhaul of the information architecture for Calypso, which hasn't changed for at least a couple of years. It would be a huge task to tackle this, and the many discussions that would arise from this.
- It would make the navigation too big to fit on a mobile device

**Comment by scruffian** [comment]
cc @breezyskies @ranh @danhauk who also considered this question...

**Comment by ranh** [comment]
> I spent a little time thinking about what would happen if we added a third option to the header, Domains, that appeared only for users with a domain-only site.
>
> [...]
>
> My initial reaction to that con is that it is probably too big to worry about the benefits here, but I thought I'd mention this to see if you/others have thought about this.

We discussed this option, but abandoned it for the reason you mention. Whether the idea has merit or not, it doesn't seem feasible given the scope of the project. 

Apart from @scruffian's comment above, some of the reasoning for using My Sites is discussed in p6qnuF-3KY-p2 and p6qnuF-3SA-p2.

> We already had a chat with @scruffian about the concept of having a new page which lists all domains

This can be done with Domains under All My Sites.

**Comment by gziolo** [comment]
In my opinion this PR could be merged into the master after some testing and polishing. We also would have to make site name selection invisible to the user, probably generate it for the user behind the scenes.

There is also one minor issue when you enter WordPress.com with all cached cleared and you click `My Sites`. In that case you still see default view for stats until you get redirected to the Domains page.

**Comment by drewblaisdell** [comment]
@scruffian Any reason in particular that you closed this? :)

I'm going to restore it because this has been linked to internally recently by a few people (including you) so I'm guessing that this was an accident. Apologies if I'm wrong about that.

**Comment by Tug** [comment]
Nice prototype @scruffian, I agree with @gziolo, we could put everything behind a feature wall and merge it ;)

Other than that, any reason why you used an extension for some part of the code?
Given that we will need to modify a lot of code in calypso I don't think an extension is adapted for this case and I suggest we try without it in our actual implementation.

**Comment by Tug** [comment]
I have removed unused parts from the PR (didn't delete the commits), it should be slightly easier to work on it and review the code now.

If we want this merge (and I think we should) I think we should:
- Extract CSS as js objects into `.scss` files to follow calypso conventions
- Add feature flags to hide those modifications on production
- Add some checks for `is_domain_only`
- Squash everything
- Review the code like a normal PR

In this PR or a follow up one we might want to:
- Set the site name to the domain name selected by the user
- Hide any occurence of `.wordpress.com` domain (making the domain primary is not enough, the user might not even have completed the registration flow).
- Refactor the code a bit (extract svg into their own components, reformat strings, extract prices from translated strings...)

**Comment by gziolo** [comment]
I'm on board with @Tug's proposal. Actually he covered all aspects we discussed on Slack 👍 

We could introduce 2 flags actually. One for checkout flow changes and another one for domain to plan upgrade.

**Pull request closed without merging**
