### PR TITLE
Plans grid design changes

### PR DESCRIPTION
**Pull request by alshakero**
#### Changes proposed in this Pull Request

1. Shows the selected domain in the plans' grid.
2. Matches the design of the plans' grid with the spec 1:1.

#### Testing instructions

1. Navigate to [/new](https://hash-100cb81cfcdb272ce27471683a4e15ef45c78625.calypso.live/new).
2. Compare the design with the proposed designs in pbAok1-11X-p2.

##### Desktop
calypso localhost_3000_new

##### Mobile
calypso localhost_3000_new(iPhone X)

### CODE REVIEW

**Comment by simison** [comment]
@olaolusoga @dubielzyk should we show anything specific when paid domain wasn't chosen earlier in the flow?

**Comment by dubielzyk** [comment]
If you hold of 14 hours I'll have a post that outline all the changes and states.

**Comment by dubielzyk** [comment]
I've added the extra changes [here](https://github.com/Automattic/wp-calypso/issues/43228).

I'm okay with these being handled separately though. Up to you 😃 Awesome work so far!

**Comment by olaolusoga** [comment]
Small adjustment. For the plans grid, Can we flush all the columns. Seeing the live build, the premium column feels awkward. Here's a screenshot of what it should look like:

Plans (paid plan, domain chosen)

**Pull request merged**
