### PR TITLE
Framework: Emit a system event when webpack is done building the client

### PR DESCRIPTION
**Pull request by Tug**
This is an experiment for calypso-live-branches to be able to tell when the app is built and ready to receive e2e tests!

### Testing
- Load https://calypso.live/?branch=add/boot-ready-on-build
- Check the status of https://calypso.live/?branch=add/boot-ready-on-build&status=1 
- Push a commit to this branch which changes something (a new empty line is enough) to the server in one of those paths https://github.com/Automattic/calypso-live-branches/blob/master/calypso.json#L16
- Check the status of the branch by polling https://calypso.live/?branch=add/boot-ready-on-build&status=1 
```bash
while true; do curl "https://calypso.live/?branch=add/boot-ready-on-build&status=1"; echo ""; sleep 2; done
```
- The app should restart in less than a minute, check the status, it should update to 'BOOTING', 'ready', then 'compiler done' because we have modified a server file.
- Remove your commit for this branch.

You can also test updating the client:

- Update a file in `client` with a valid change
- Check the status of the branch by polling https://calypso.live/?branch=add/boot-ready-on-build&status=1
- Push your change to this branch
- It should change to 'compiler compiling' (or 'compiler invalid') for a few seconds then come back to 'ready'.
- Remove your commit from this branch

### Reviews
- [x] Code
- [x] Product

### CODE REVIEW

**Comment by fabianapsimoes** [comment]
I tested this and it seems to work well. Might be good to have a @hoverduck test it as well, as he's been using Live Branches more often.

Product :+1:

**Comment by hoverduck** [comment]
I had a couple problems...listing them in separate comments for readability.

I see that package.json is one of the files listed in the `watchPath`, so I added an empty line to that.  Does that really triggers a new build though, since it doesn't change the actual value of the JS object?  Regardless, when I did that I didn't see anything change with the status...until I tried to load the branch by itself (without the `status=1` flag).  At that point I got the following error message, after which the branch booted and I observed all the status changes as expected.  This happened both when I added and removed the empty line.

```
Error: Worker died
   at Hub.cancelRequests (/home/ubuntu/calypso-live-branches/node_modules/cluster-hub/lib/Hub.js:293:38)
   at EventEmitter.<anonymous> (/home/ubuntu/calypso-live-branches/node_modules/cluster-hub/lib/Hub.js:59:17)
   at emitThree (events.js:110:13)
   at EventEmitter.emit (events.js:188:7)
   at ChildProcess.<anonymous> (cluster.js:361:15)
   at ChildProcess.g (events.js:273:16)
   at emitTwo (events.js:100:13)
   at ChildProcess.emit (events.js:185:7)
   at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
```

**Comment by hoverduck** [comment]
I also tried adding an empty line to index.js.  When I added the empty line I didn't see any change to status for a minute or so (how often does it check for changes?).  Then it rebooted, but when I saw the `ready` status I tried refreshing the page and still got the `Booting branch` message.  I refreshed a couple times, and then saw that the status had returned to `BOOTING`.  I assume it just failed the first boot and restarted?  There was something interesting in the output on the page, but I didn't capture it...and when I tried to redo the test by removing the empty line I got the same behavior as my previous comment (`Error: Worker died`)

**Comment by Tug** [comment]
> I see that package.json is one of the files listed in the watchPath, so I added an empty line to that. Does that really triggers a new build though, since it doesn't change the actual value of the JS object? 
...

Indeed, adding a new commit does not trigger anything until we try to actually load the page, sorry for the confusion here.
Ok so you almost successfully reproduced the 'BOOTING', 'UP' and 'ready' sequence. There is still that "Worker died" error that should not show up (the fact that the worker dies is normal I think but the booting page should be displayed in place of the error message though)
I would have to double check but I think the 'compiling' status is only visible if at least one web client has loaded the app (and is connected through websocket to webpack-dev-server).

> I also tried adding an empty line to index.js. When I added the empty line I didn't see any change to status for a minute or so (how often does it check for changes?). 

About that, yes branches all check their current state with a local mirror repository which is synchronized with github every minute. (I'm not sure what github allows in this case).

> Then it rebooted, but when I saw the ready status I tried refreshing the page and still got the Booting branch message. I refreshed a couple times, and then saw that the status had returned to BOOTING.

I'm not sure how to explain the fact that it rebooted twice. I'm going to try to reproduce this first.

**Comment by Tug** [comment]
Thanks @fabianapsimoes and @hoverduck for taking the time to review this.

I just did a few changes on calypso.live:
- Fixed the detection of a change in a branch (it wasn't working when we were deleting a comment) https://github.com/Automattic/calypso-live-branches/commit/ebedd4641ddba5fda5389f6a36877f96fa69f11e
- We now check if the branch is up to date when doing a status request https://github.com/Automattic/calypso-live-branches/commit/032be3437b5345fff6200bbb49c899128fdfe8e6
- We now serve the booting page when the branch has to update (instead of waiting for it to finish rebooting) https://github.com/Automattic/calypso-live-branches/commit/0325ea819b461241488f04d3b8d0c6991a1a1649
- Removed the sloppy timeout handler and decided to just retry once on failure https://github.com/Automattic/calypso-live-branches/commit/b949be8044112e7cea29d955a060c76ff035f106 We'll see how it goes

I have updated the instructions of this PR and I think it's ready for another round, it should be working in most cases (I can't guarantee there won't be "Worker died" or "502 Gateway error").

Moreover, I have updated the commit of this branch so we don't mix compiler events with `ready` which is already used for the desktop app I believe. So `compiler done` now means the app is ready.

**Comment by Tug** [comment]
Yep, could work! I think we should keep the mirror repository approach for now otherwise it's going to be very slow to check for changes (and it might fail more often).

How about I add the commit hash to the status response:
```js
{ branch: 'BRANCH', status: 'compiler done', commit: 'e532405cffe1eea50216ec086a459820741a274e' }
```
Then you could retry up until you have the expected commit id?

**Comment by hoverduck** [comment]
> How about I add the commit hash to the status response

Excellent!

**Comment by Tug** [comment]
Added in last version https://github.com/Automattic/calypso-live-branches/commit/c82239d62fce9c7db057edec49ac1092275d1662 ;)

**Comment by fabianapsimoes** [comment]
@hoverduck can you check the Product box in the description, if you think is OK to merge from your perspective? Then we're just pending a code review.

**Comment by drewblaisdell** [comment]
The live branch works fine for me, but I get an error when I try to run this locally:

```
/Users/drewblaisdell/Desktop/a8c/wp-calypso/build/webpack:/index.js:35
        process.send( { boot: 'ready' } );
         ^
TypeError: process.send is not a function
    at Server.<anonymous> (/Users/drewblaisdell/Desktop/a8c/wp-calypso/build/webpack:/index.js:35:10)
    at Server.g (events.js:273:16)
    at emitNone (events.js:80:13)
    at Server.emit (events.js:179:7)
    at emitListeningNT (net.js:1256:10)
    at _combinedTickCallback (internal/process/next_tick.js:71:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
    at Function.Module.runMain (module.js:449:11)
    at startup (node.js:146:18)
    at node.js:404:3
make: *** [run] Error 1
```

It looks like we'll need to either only emit these events on `calypso.live`, or mock `process.send` if it doesn't exist.

**Comment by Tug** [comment]
Oh you're right Drew, only `ChildProcess` instances have a `send` method, huge mistake from my part. I need to fix that!
I wonder why I'm not seeing this error on my side though!

**Comment by Tug** [comment]
Ready for review! 
@drewblaisdell if you could check bak on it ;)

**Comment by drewblaisdell** [comment]
:+1:

**Pull request merged**
