### PR TITLE
ui.queryArguments: update state less aggressively

### PR DESCRIPTION
**Pull request by mcsf**
To implement once #6417 is merged.

Every time `ROUTE_SET` is dispatched, the `ui.queryArguments.current` branch updates itself regardless of whether there is any change in the query data. This potentially leads to unnecessary renders in the view layer or recalculations in memoized selectors.

Test live: https://calypso.live/?branch=update/ui-query-arguments-overwrites

### CODE REVIEW

**Comment by lsinger** [comment]
Are we certain that we won't ever need the timestamp when querying these events?

**Comment by mcsf** [comment]
> Are we certain that we won't ever need the timestamp when querying these events?

Are you referring to the test in `isEqualQuery`, or to the fact that this excludes any `timestamp=foo` query argument? For the former: with this change, we assert that we don't care about the last time a `ROUTE_SET` action was dispatch, but only the last time _different_ arguments were provided in a `ROUTE_SET`. For the latter: we could also rename this special value `timestamp` to `_timestamp`.

**Comment by ehg** [comment]
>  or to the fact that this excludes any timestamp=foo query argument? 

Ooh, that passed me right by. `_timestamp` sounds sensible, and could save someone a headache later :)

**Comment by lsinger** [comment]
I meant the former ... but thinking about it again I realize that it will definitely update when a different route is visited. So I'm good on that front. 

Good call with making an actual timestamp argument problematic -- rename to _timestamp sounds sensible!

**Comment by mcsf** [comment]
I've underscore-prefixed `timestamp` in b344826. It's probably easier to make this change now rather than later. I notice that it can be confusing to read `_timestamp` (from `ui.queryArguments.*`) alongside `timestamp` (from `preferences`'s `guided-tours-history`), but it's probably a lesser evil?

**Comment by ehg** [comment]
LGTM

**Comment by mcsf** [comment]
Forgot to squash. D'oh.

**Pull request merged**
