### PR TITLE
Manage all domains: Remove footer upsell carousel

### PR DESCRIPTION
**Pull request by allilevine**
Fixes https://github.com/Automattic/dotcom-forge/issues/3009

## Proposed Changes

* Reverts https://github.com/Automattic/wp-calypso/pull/60882 except for the general carousel improvement.
* See the issue for more info.

## Testing Instructions

1. You need a domain-only subscription to test this PR
2. Build this branch locally or open the live Calypso link
3. Navigate to to /manage/domains
4. Verify that the carousel does not show

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

**Review by ebinnion — DISMISSED** [review]

**Comment by ebinnion** [comment]
When I rebased against trunk to try to address conflicts, I noticed some issues with the layout of the manage all domains button at the end of the list of domains for a single site.

Screenshot 2023-07-16 at 3 48 39 PM

**Review by ebinnion — APPROVED** [review]
I rebased, addressed the conflict, and then addressed the issue with the broken layout that I point out in a previous comment. This should be good to go now.

**Comment by karenroldan** [comment]
**issue (blocking):** The unit tests failed because the './types' module, used in 'domain-only-upsell-carousel.tsx', can't be found.

I tested the changes using the Calypso link and I no longer see the carousel. 👍🏻

**Comment by allilevine** [comment]
> issue (blocking): The unit tests failed because the './types' module, used in 'domain-only-upsell-carousel.tsx', can't be found.

@karenroldan @ebinnion It needed another rebase to remove the file requiring those types. Would you mind re-testing? 🙏 

I also tagged @Automattic/martech-decepticons for review since it looks like you're working in this same area.

**Comment by ebinnion** [comment]
Tested with Calypso.live and it seems fine.

**Review by karenroldan — APPROVED** [review]
Thanks for the update. LGTM! 🚀

**Pull request merged**
