### PR TITLE
Help Center: apply styling changes

### LINKED ISSUE #62690: Help Center: Design TODOs
Here's a list of improvements for the Help Center:

Check the task if it has been implemented, or insert [👀  username] if you're working on that.

- [x] [👀  [escapemanuele](https://github.com/Automattic/wp-calypso/pull/62699)] Width of the container: How is the size determined? I see it’s relative to screen size now. I was thinking it could be 410px, like the width of the notification side panel. Seems to be a good size.
- [x] [👀  [escapemanuele](https://github.com/Automattic/wp-calypso/pull/62699)] Height of the container: How is this determined? I was thinking ~800px. We can also determine this once we have all the content in there.
- [x] Different mouse pointer on hovering the help center header: could we have a different pointer on hover to indicate that the help center is moveable? Check out the example from Google:
image
- [x] Size of “x” and “-” buttons: I think these can be a lot smaller, like in the designs. I was aiming for having it the same as the size of the close button in the editor side panels.
- [x] “Help center” header:
Title: font size should be 14px. Again this is similar to the editor side panels.
Padding: padding-left should be 16px.
- [x] Content: padding should be 16px on all sides.
- [x] Footer: padding should be 16px on all sides.
- [x] Minimized help center: Regarding the position from the bottom right, is there a way that just for the editor we could have it higher? So it is x distance from the white editor footer? As we always see this bottom white footer. The same way as we are placing it x distance from the editor top nav bar.
- [x] Mobile:
Padding: all padding should be the same as desktop. 16px on all sides.
Footer: should be sticky to the bottom.

### PR DESCRIPTION
**Pull request by arcangelini**
## Changes proposed in this Pull Request

Apply changes suggested by design team to the Help Center package.

## Testing instructions

1. Pull branch and run `yarn workspace @automattic/help-center run storybook`
2. Verify the changes listed in this task #62690 are applied.
3. `yarn dev --sync` from `apps/editing-toolkit`

Closes #62690

### CODE REVIEW

**Review by escapemanuele — APPROVED** [review]
Great work! LGTM

**Comment by poligilad-auto** [comment]
Looking great @arcangelini! 😀
Have to say, adding the "draggable" mouse pointer really helps show that it's draggable.

A few last small things:

- Let's make the padding of the header 8px on the right, that way the icons align better to the edge:

image

- The minimize icon "-" looks too big in comparison to the "X". Maybe we can try and make it smaller within the button? Maybe 20px? WDYT?

- Can you make the pink spacing here on the bottom of the minimized help center the same as the right pink spacing?
image

- Need to remove the "SmallcloseSmall" text in the black hover.
image

**Comment by arcangelini** [comment]
@poligilad-auto all these changes have been made 👍 

As for the minimize icon, this is not accepting the size prop because of a bug. I have another PR to hopefully address that. In the mean time I had to use `transform: scale()` to adjust the size of it. AND while I am bringing that up, there are some really weird styling overwrites for the text in the header. No matter what I did the font was defaulting to `13px`. Only way around this was inlining the font styling.

**Comment by poligilad-auto** [comment]
> As for the minimize icon, this is not accepting the size prop because of a bug. I have another PR to hopefully address that. In the mean time I had to use transform: scale() to adjust the size of it. AND while I am bringing that up, there are some really weird styling overwrites for the text in the header. No matter what I did the font was defaulting to 13px. Only way around this was inlining the font styling.

That's really weird. Is this Gutenberg related? Thanks for addressing all of these, it's really looking great.

**Pull request merged**
