### PR TITLE
Jetpack connect: Add TOS link

### PR DESCRIPTION
**Pull request by johnHackworth**
Fixes https://github.com/Automattic/wp-calypso/issues/5174

This PR adds a ToS link to the first step of jetpack connect:
image

How to test
=========
1. Go to http://calypso.dev:3000/jetpack/connect
2. Check the link is there and it works :D

### CODE REVIEW

**Comment by drw158** [comment]
I think this is probably more direct:

> By connecting your site you agree to the fascinating [Terms of Service](#).

I formatted the link and tweaked the copy a bit to be like the iOS app.

Overall, it might be too cheeky, but we do use it in our apps. I wish it could be less verbose, like "You agree to the Terms of Service", but I don't know if that'd work.

LGTM

**Comment by johnHackworth** [comment]
:+1: that sounds better, @drw158 , thanks!

**Comment by rickybanister** [comment]
I mentioned this elsewhere, but the tos link should be above the button and in the same gray background color as the sign up form.

**Comment by johnHackworth** [comment]
@rickybanister I changed the style to use the same gray-box style than on the signup:

image

I'm not sure of what to do with those paddings in the TOS links, though

**Comment by rickybanister** [comment]
TOS link margins have been fixed up.

**Comment by johnHackworth** [comment]
ok, ready to go then!

**Pull request merged**
