### PR TITLE
Try out Enzyme for component testing

### PR DESCRIPTION
**Pull request by jstrutz**
Evaluating the usage of [Enzyme](http://airbnb.io/enzyme) for testing of React components, in lieu of React's TestUtils.

### CODE REVIEW

**Comment by jstrutz** [comment]
_Here are a few of my initial impressions on Enzyme, and its potential for Calypso_

#### Why Enzyme?

Enzyme seeks to make testing React components easier, both with more rendering options, and with convenience functions that reduce render tree boilerplate and improve test readability.

#### Benefits
- For deeply-nested interfaces, the Enzyme's [shallow rendering functionality](http://airbnb.io/enzyme/docs/api/shallow.html) clarifies the "component under test", by ensuring you're not making assertions about inner components

- `chai-enzyme` provides some nice expect matchers, which both make for descriptive expectations:

  `expect( wrapper ).to.have.className( 'accordion' )`

  as well as more informative failures:

  ```
   Accordion should render as expected with a title and content:
   AssertionError: expected <Accordion /> to have a 'accordion' class, but it has 'somethingelse'

   HTML:

   <div class="somethingelse">
     <header class="accordion__header">
       <button type="button" class="accordion__toggle"><span class="accordion__title">Section</span>
       </button>
     </header>
     <div class="accordion__content">
       <div class="accordion__content-wrap">Content</div>
     </div>
   </div>

  ```

- Shallow rendering may speed up tests (just a suspicion)

#### Caveats
- Doesn't currently support "complex" css selectors, like: `.accordion__header:not( .has-icon ):not( .has-subtitle )`, but this behavior can be replicated by chaining enzyme selectors: `wrapper.find( '.accordion__header' ).not( '.has-icon' ).not( '.has-subtitle' ) )`, or chai assertions
- `chai-enzyme` depends on `chai@3.x`, however we're using `chai@2.0` at the moment; I updated chai in this branch, but haven't confirmed that the upgrade hasn't broken anything
- The difference between Enzyme's [multiple rendering methods](http://airbnb.io/enzyme/#basic-usage) (`shallow`, `mount`, and `render`) adds additional complexity for the test author

#### Example diff

See https://github.com/Automattic/wp-calypso/commit/a35a190f587c38f609cf3b5bbd316496d04c1afe#diff-58adcb29cce4a8a51929aa4658b84fdd for an example of two sets of tests for a single component - one using React TestUtils, and one using Enzyme.


#### For Calypso

Calypso already has some very disciplined separation of components.  However, existing component tests have a considerable amount of mocking, which I believe becomes largely unnecessary when using Enzyme's shallow renderer.

Presently, many Calypso components lack tests.  Enzyme may sufficiently improve the test-writing experience, such that contributors are willing to write tests for seemingly trivial components.

**Comment by nb** [comment]
I really like that it removes the need of some of the mocking we’re doing in tests.

**Comment by jstrutz** [comment]
@nb Yeah, I agree.  Since shallow rendering clarifies the line between components, it underscores the awkwardness of the mocks.  I "enzyme-ified" the `EditorDiscussion` component, to illustrate a bit of Enzyme's usage in a higher-level (non-leaf) component.  Three mocks are still needed:
- The mock for `components/info-popover` is necessary because it has ComponentJS-based dependencies, which won't load "as-is"
- The `edit` flux action generator in `lib/posts/actions` is mocked so we can `spy` on its call
- We mock actions in `lib/posts/stats` to noops, to work around their implicit dependencies on `window.ga` and `window.mc`

While the example of `EditorDiscussion` doesn't spare us from mocks, each of those mocks are artifacts of other decisions made in the codebase, and not essential -- they could be removed with some refactoring.

**Comment by jstrutz** [comment]
Also of interest: [the simulated `change` event](https://github.com/Automattic/wp-calypso/commit/6cce401de847d36792ba6d6e6e2ac47150665254#diff-d58966dae3302f8030fbd0dc9fbdbb3bR146) is fired on a shallowly-rendered `FormCheckbox` , rather than a DOM event.

**Comment by lancewillett** [comment]
Closing this one as no movement in several months — feel free to re-open if it's actionable and can be pushed in.

**Pull request closed without merging**
