### PR TITLE
Gutenberg: consolidate Calypsoify and Gutenlypso feature flags

### PR DESCRIPTION
**Pull request by vindl**
#### Changes proposed in this Pull Request

This PR changes turns off Calypsoify redirects when `gutenberg` flag is on.

After the release of Calypsoify for Atomic sites this flag will need to stay enabled in production. However, when both `gutenberg` and `calypsoify/gutenberg` feature flags are enabled, we default to Calypsoify flows, which will interfere with our Gutenlypso launch attempt.

Since `calypsoify/gutenberg` is now enabled in (almost) all environments, I considered removing it altogether, but I think there is still some value in keeping it. We might not want to enable it still in Desktop environment until some issues with it are resolved. It also nice to keep it in an unlikely case that we need to quickly turn it off in the future.

#### Testing instructions

1. Navigate to http://calypso.localhost:3000/posts of a Simple site that has opted in to Gutenberg.
2. Verify that editing or creating new post will open Gutenlypso.
3. Navigate to http://calypso.localhost:3000/posts of an Atomic site that has opted in to Gutenberg.
4. Verify that editing or creating new posts will redirect you to Calypsoify.
5. Jetpack and VIP sites should still take you to Classic editor.
6. Sites that haven't opted in should open the Classic editor in all cases (Simple, Atomic etc.).

Fixes https://github.com/Automattic/wp-calypso/issues/29277

### CODE REVIEW

**Comment by vindl** [comment]
Not sure why the e2e test are failing here: https://github.com/Automattic/wp-e2e-tests/blob/de9038f946d76bf632c16fbb6de01267970d7459/lib/gutenberg/gutenberg-editor-component.js#L13

**Comment by alisterscott** [comment]
> Not sure why the e2e test are failing here: 

It's showing the classic editor when using the new post button when it expects the wp-admin gutenberg editor

**Comment by alisterscott** [comment]
It doesn't remember that I've opted into G and shows the classic editor anyway

Steps to reproduce

1. Use https://calypso.live/?branch=remove/calypsoify-feature-flag
2. Use new post button in toolbar and select site previously opted in
3. Classic editor shows 👎

**Comment by vindl** [comment]
Thanks @alisterscott! Should be fixed in 0cf00c01f495d64676ac79f2de4b28341a4e800c.

e2e tests saving the day! I think I pretty much covered all of the other flows, but there is no way I'd remember to test for this one otherwise. :)

**Comment by alisterscott** [comment]
Thanks @vindl - tests well now - all the e2e tests should pass now

**Pull request merged**
