### PR TITLE
Testing: Remove obsolete useI18n test helper

### LINKED ISSUE #5818: Testing: Remove obsolete useI18n test helper
Part of #4915.

Once #5477 gets merged we won't need i18n test helper anymore. We should remove all useI18n test helper calls and make sure all existing tests pass as before. We most likely will have to reset configuration for one of the tests that changes default settings for i18n.

### PR DESCRIPTION
**Pull request by Tug**
Fixes #5818

After moving `lib/mixin/i18n` to an external repository, we don't need the i18n test helper anymore.
This PR removes `useI18n` test helper calls.

## Testing Instructions
Check that all the tests still pass: `make test`

Test live: https://calypso.live/?branch=update/remove-use-i18n

### CODE REVIEW

**Comment by drewblaisdell** [comment]
The code looks good, this only touch tests (which pass), and I checked to make sure there are no lingering `useI18n` calls. :+1:

**Comment by gziolo** [comment]
@Tug Many thanks for taking care of this one 💯

**Comment by aduth** [comment]
Very nice :smil

**Pull request merged**
