### PR TITLE
Remove the Free Plans Domain Upsell

### PR DESCRIPTION
**Pull request by dzver**
#### Changes proposed in this Pull Request

Remove the Domain Upsell from the launch-site flow

The upsell moved some important stats in the right direction but a subsequent analysis revealed that it moved other stats in the opposite direction so the overall impact is questionable.

Check the latest comments on pcvIcj-2A-p2 for details on the rationale behind this change.

This is the step being removed:

Screenshot 2021-02-18 at 16 44 44

#### Testing instructions

1. Create a new user and site with the /start/user flow. It should work
2. From /home click the Launch button
3. Select a free .wordpress.com domain and a free plan
4. The site should be launched, no step 4 offering a domain without a plan should be visible

See the original #47963. This is not a revert because there were other changes between the free experiment and now.

### CODE REVIEW

**Comment by razvanpapadopol** [comment]
We could probably clean up also related code from e2e tests: https://github.com/Automattic/wp-calypso/blob/trunk/test/e2e/lib/flows/launch-site-flow.js#L29-L37

**Review by aneeshd16 — COMMENTED** [review]
Comparing with the original PR #47963, we can perhaps remove `selected_domain_upsell_item` from here:
https://github.com/Automattic/wp-calypso/blob/abd47c61baa6a306aa06befece6e9be56b94eb9c/client/state/signup/progress/actions.js#L59

Also, we can delete `client/signup/steps/domain-upsell/index.jsx` and `client/signup/steps/domain-upsell/style.scss` since they are no longer used.

**Review by aneeshd16 — APPROVED** [review]
Re-tested, LGTM!

**Comment by simison** [comment]
Hi! I added this to the signup pod's tracking board so that we'll ensure this gets in. Happy if you folks can merge on Monday tho. Thank you! cc @razvanpapadopol

**Review by alshakero — APPROVED** [review]
Reviewed and tested once more. LGTM.

I'll deploy it as well.

**Pull request merged**
