### PR TITLE
Disable agency dashboard down time email recipient setting

### PR DESCRIPTION
**Pull request by oikeme**
Disable the agency dashboard notification email recipient settings to make the value read only

#### Proposed Changes

* This PR sets the value of the users email for monitor notifications to be disabled. 

#### Testing Instructions

* Run `git checkout update/disable-agency-dashboard-notification-email`
* Run `yarn-start-jetpack-cloud`
* Visit the dashboard at http://jetpack.cloud.localhost:3000/dashboard
* Click on the clock icon and ensure that if the user has email notifications turned on the value cannot be changed and is disabled.
* 
Screenshot 2023-01-12 at 7 18 00 AM

#### Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

Related to #

### CODE REVIEW

**Review by yashwin — COMMENTED** [review]
LGTM. But I have a small concern with how it looks when it Is disabled.

1) Can we add `isBorderless` key to the `TokenField`?
2) I think we have to remove/rephrase the line - `Receive email notifications with one or more recipients.`
3) How about we remove the `X` button next to the email, which might confuse the user as it does nothing.

I tried doing the above, and this is how it looks.

Screenshot 2023-01-11 at 1 24 59 PM


Any thoughts here, @madebynoam?

**Comment by madebynoam** [comment]
> LGTM. But I have a small concern with how it looks when it Is disabled.
> 
> 1. Can we add `isBorderless` key to the `TokenField`?
> 2. I think we have to remove/rephrase the line - `Receive email notifications with one or more recipients.`
> 3. How about we remove the `X` button next to the email, which might confuse the user as it does nothing.
> 
> I tried doing the above, and this is how it looks.
> 
> Screenshot 2023-01-11 at 1 24 59 PM
> 
> Any thoughts here, @madebynoam?

I agree with @yashwin. His recommendation looks good to me. We'll probably also want the cursor on the disabled text field to be the regular pointer (vs. the text one).

**Review by yashwin — APPROVED** [review]
LGTM. Thanks for making these changes. 

It would be great if we could add a screenshot for this change.

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/7728472

Thank you @oikeme for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/7728472).

**Pull request merged**
