### PR TITLE
Reader: Add app promo to the reader stream

### PR DESCRIPTION
**Pull request by enejb**
Related to https://github.com/Automattic/wp-calypso/pull/83330

## Proposed Changes
This PR adds the AppPromo to the reader Steam. 

See
Screenshot 2023-11-10 at 11 27 18 AM
Screenshot 2023-11-10 at 11 29 10 AM

## Testing Instructions

Logged out and logged in visit the reader. Notice the new App Promo. 
Resize it. Does it look as expected?

Request the page as a iPhone user Does it look as expected? 
Request the page as an Android user does it look as expected?

## Pre-merge Checklist

- [x] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [x] https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md for your changes?
- [x] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [x] Have you checked for TypeScript, React or other console errors?
- [x] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [x] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ x] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or

 use (p4TIVU-ajp-p2)?

### CODE REVIEW

**Comment by osullivanchris** [comment]
Here's a mock on desktop and mobile. Roughly following the styles we've been using for other promots.

Screenshot 2023-11-10 at 16 17 54


eYeHXEMDbnFptE40xUqZ2T-fi-1426_20588

Also did a quick variation where its on the same background as the reader cards. No border, white fill, subtle shadow. Maybe not right to confuse it with content though.

Screenshot 2023-11-10 at 16 18 02

**Review by roo2 — COMMENTED** [review]
Just to confirm this should be on all of the streams including the feed for an individual site, discover, tags, search etc and even Likes, Conversations pages as well? I think it should be limited to only certain streams

**Comment by eoigal** [comment]
This isn't working for me on Calypso live, I get the following:

Screenshot 2023-11-27 at 18 28 53

**Comment by eoigal** [comment]
I agree with Eru, I think we should only show this in the Discover stream and track if anyone is using it before rolling it out on all streams.

**Comment by enejb** [comment]
Thanks for the feedback. @roo2  and @eoigal I am now only displaying the app promo when we have isDiscoverStream set to true. 

We can see what the conversion of this app promo is and see if it does anything. Do you think it is ready to land? 

I am not sure why the doesn't show up as expected in the calypso live link. 

This is what I see in local development. 

Screenshot 2023-11-27 at 6 07 55 PM

**Comment by eoigal** [comment]
I think there are still some styles missing - seeing this locally;

Screenshot 2023-11-30 at 12 04 22

**Review by Addison-Stavlo — COMMENTED** [review]
For me the styles look good when logged out, at various screen widths.

When logged in, however, the styles are broken as pointed out above AND when we go to smaller screen widths the promo seems to disappear entirely.

**Comment by enejb** [comment]
@Addison-Stavlo and @eoigal the issue should be fixed now. 
I updated the app-promo-sidebar component so that the classes don't crash any more.

See
Screenshot 2023-11-30 at 10 23 08 AM

**Comment by Addison-Stavlo** [comment]
The styles for the card in the stream look good to me now!  It looks like there may be some unit test failures to resolve.

**Review by Addison-Stavlo — APPROVED** [review]
Looks good to me!

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/9798202

Some locales (Japanese) have been temporarily machine-translated due to translator availability. All other translations are usually ready within a few days. Untranslated and machine-translated strings will be sent for translation next Monday and are expected to be completed by the following Friday.

Thank you @enejb for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/9798202).

**Pull request merged**
