### PR TITLE
Checkout: Enable the bank account redirect payment method for Brazil

### PR DESCRIPTION
**Pull request by yoavf**
### Purpose
This enables a redirect payment method called TEF in Brazil. It works similarly to other redirect type payment methods.
Most parts of this code have already been reviewed:
c98b393 is a merge of #24240.
ef57dc4 is a merge of #24517

Left to review: 
- ac260117848f8cc97f21f74f01936102e8ee2784
- c72cfd8ac770c86cdffc6eb4abaf643189e36d4c
- 290b68446b3d42863cde41db45d41d57729478ca

### Testing:
- You'll need to have a Brazillian IP address or tweak `getCurrentUserPaymentMethods` by hardcoding `BR` as the `countryCode` for `paymentMethods.byCountry[ countryCode ] ||`.
- When visiting checkout, you should be able to choose TEF as your payment method:  screen shot 2018-04-25 at 14 54 38
- Fill in the form - most fields will accept any values, but for the taxpayer indentification number, use the CPF numbers available [here](https://developers.ebanx.com/guides/going-live/fake-customer-data/fake-brazilian-customer-data/). You can choose any bank you want.
- You'll be redirected (in store-sandbox mode) to a fake authorization page, where you can authorize or cancel the payment. If you authorize the payment, you will be taken to a "pending transaction page". Wait long enough (~10 minutes) and the transaction will be completed and you'll be redirected to the thank-you page.

### Dependencies:
- [x] ~#24240~ (merged)
- [x] ~#24294~ (merged)
- [x] ~#24517~ (merged)
- [x] #24726

### CODE REVIEW

**Comment by ramonjd** [comment]
@yoavf Hope you don't mind,  so I could work on this locally I added a small commit, the main one of which is updating the expected [payment class name](https://github.com/Automattic/wp-calypso/pull/23830/files#diff-5f9b5f654df0d1076ef22cec728a9451R162) that we get from the backend. Let me know if that's okay, or the original name is right.

Also, for the TEF Brazil fields I'll create a new branch based on this one since it could be 'chunky'.

Am I okay to rebase this branch before I use it as the base for the new one?

**Comment by yoavf** [comment]
Sure, go ahead - no problem

**Comment by yoavf** [comment]
I'm going to merge #23824 shortly and will rebase this after that.

**Comment by yoavf** [comment]
Changed the base to show this depends on #24294

**Comment by ramonjd** [comment]
Trying to test this, everything works until I submit the payment form:

The post to `/rest/v1.1/me/transactions?http_envelope=1&locale=de_formal` with field data:

```
{
    ...
    payment: {
        address_1: "Rua E",
        address_2: "",
        cancel_url: "http://calypso.localhost:3000/checkout/dumtree.wordpress.com",
        city: "Maracanaú",
        document: "853.513.468-93",
        name: "Ana Santos Araujo",
        payment_method: "WPCOM_Billing_Ebanx_Redirect_Tef",
        phone_number: "02284-7035",
        postal_code: "61919-230",
        state: "CE",
        street_number: "1040",
        success_url :"http://calypso.localhost:3000/checkout/thank-you/dumtree.wordpress.com/:receiptId",
        tef_bank :"bancodobrasil",
  }
}
```
Returns a 400.

`{"code":400,"headers":[{"name":"Content-Type","value":"application\/json"}],"body":{"error":"payment-failure","message":"Es ist ein unerwarteter Fehler aufgetreten. Versuche es sp\u00e4ter erneut."}}`

Is there something I missed?

Also, it requires the change I made in #24480

**Comment by yoavf** [comment]
@ramonjd Apparently your email is associated with MX payments at EBANX, not BR. You can use another account to test, or replace the email address in `Set_Ebanx_Redirect_Checkout::make_external_code` on the wpcom side

**Comment by ramonjd** [comment]
@yoavf 

> Apparently your email is associated with MX payments at EBANX, not BR.

Argh, you've only mentioned that a dozen times. 😀 My bad. Cheers. I'll test again.

**Comment by yoavf** [comment]
We're missing the CPF masking - pretty critical to make sure it works properly

**Comment by ramonjd** [comment]
I'm doing some testing and am getting very slow processing times. Getting this response to 3 minutes before redirect:

screen shot 2018-05-15 at 11 46 31 am

Not sure if it's just me :) But it works in the end.

**Comment by yoavf** [comment]
> I'm doing some testing and am getting very slow processing times. Getting this response to 3-5 minutes before a redirect:

Hrm , this is a response to a request that should only happen after a redirect back. I'll test again

**Comment by ramonjd** [comment]
> Getting this response to 3-5 minutes before a redirect:
Sorry, I wasn't clear. Before a redirect to 'Thank you' and while on the processing page.

**Pull request merged**
