### PR TITLE
Plugin Upload: Vertically center plugin upload button icon

### PR DESCRIPTION
**Pull request by tyxla**
As suggested by @seear in https://github.com/Automattic/wp-calypso/pull/17535#issuecomment-325625403 it would be nice if we could align the icon vertically in the plugin upload button. This is what this PR suggests.

Before:

After:

To test:
* Checkout this branch.
* Go to `/plugins/:site` where `:site` is a Jetpack site.
* Verify the icon looks like on the "After" screenshot.

### CODE REVIEW

**Comment by folletto** [comment]
Thanks! :y:

**Comment by rickybanister** [comment]
Why does this icon need custom positioning? Is it misaligned on the gridicons grid? 

It looks better after this PR, but just curious if it should be adjusted in the svg upstream?

**Comment by folletto** [comment]
AH YES!

I thought #16371 was merged, but apparently it wasn't. @tyxla can you check if that PR also fixes this?

**Comment by rickybanister** [comment]
That PR doesn't seem to touch the vertical alignment at all, why do you think it would fix this?

**Comment by folletto** [comment]
You're right, it's not that one. I was sure there was one that dealt with vertical alignment somewhere... oh well. 

Still, I agree, that's shouldn't be a local change.

I checked also Themes, and the icon there has been tweaked too with a `top: 6px`, so we probably need to review all of them. :|

Yet it seems ok on DevDocs? I'm not sure what's going on...
https://wpcalypso.wordpress.com/devdocs/design/buttons

**Comment by tyxla** [comment]
Well, @folletto @rickybanister it seems the icon itself is not well aligned vertically. We can update that in Gridicons and fix all usages in Calypso, but I'm not sure if we wouldn't break other projects that depend on Gridicons. That's why I'm suggesting the `top` solution as a quick fix. Let me know if you're good with it.

**Comment by rickybanister** [comment]
It doesn't even bother me that much in it's off-center position. It's a floating cloud, after-all.

I'm fine with moving it just for this instance, or not moving it. Auditing all it's positions would be somewhat tricky.

**Comment by folletto** [comment]
Thanks for all the pointers. I took some time to dive deeper in what's going on here, and here's the idea.

1. Fix `.button.is-compact.gridicon` with `top: 5px` as it seems better with all the icons, regardless.
2. That's all. I think as Rick said the "floating" effect is a byproduct of the cloud being a bit higher as an icon, and the CSS being off by 1px, and it's ok. If we want to change the baseline alignment, we can change Gridicons — which is not a problem, that's why we have it centralized.

Here's how they look if we fix the icon on all `.button.is-compact.gridicon` with `5px`:

screen shot 2017-08-31 at 11 27 22

screen shot 2017-08-31 at 11 27 41

Which seems a better fix for me: general, avoids overrides, and if there are overrides we can remove them later with no problem.

---

If we agree, I'd change this PR to do these two things:

1. Fix it globally at `5px`
2. Remove the adjustment on `.themes__upload-button.is-compact .gridicon`

**Comment by rickybanister** [comment]
Works for me—also worth remembering, the icon was originally positioned when we had ALL CAPS buttons, the lower case has added descenders which probably makes the icons look high.

**Comment by tyxla** [comment]
Great idea folks. I've updated the PR to reflect the suggested changes, here are some updated previews:

**Theme upload compact button**


**Plugin upload compact button**


**Devdocs compact buttons**

**Comment by tyxla** [comment]
@folletto @rickybanister this one is ready for another design review

**Comment by folletto** [comment]
AWESOME.

Design wise: 👍

**Comment by folletto** [comment]
Code wise: 👍

**Pull request merged**
