### PR TITLE
WordAds Stats: fix broken links in Odyssey

### PR DESCRIPTION
**Pull request by kangzj**
#### Proposed Changes

Restores clicking behaviours on the Ads page:

* Restore information icon clicking
* Bars clicking
* Tabs clicking

We should avoid use `window.location` object directly for Stats, as in Odyssey the paths are actually hashes. We should use `context.path`, `context.query` and `context.pathname` instead, which are injected by `page.js`.

#### Testing Instructions

* Verify Odyssey with Option 1 in `PejTkB-3E-p2`
* Enable WordAds - `/wp-admin/admin.php?page=jetpack#/traffic?term=wordads`
* Open `/wp-admin/admin.php?page=stats&flags=stats%2Fads-page`
* Ensure Ads page generally works
* Ensure the click actions for bars, tabs and information icon works
* Open live branch link
* Enusre Ads page work for WPCOM

image

#### Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [x] Have you checked for TypeScript, React or other console errors?
- [x] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-ajp-p2)?

### CODE REVIEW

**Comment by wilmersondasilva** [comment]
I tried to test this one, but unfortunately, I couldn't make the `Ads` page works properly. The code looks fine though!

**Review by wilmersondasilva — APPROVED** [review]
I was able to make it work now.

I tested both on Odyssey and on WPCOM and it's working as expected. 👍

**Comment by wilmersondasilva** [comment]
While testing this I found a weird behavior in the Charts of the Ads page in the Odyssey Stats. This was already happening before this PR though. Is there already an issue for tackling this behavior or should I create a new one?

It doesn't happen on WPCOM.

https://user-images.githubusercontent.com/6406071/214555284-9d138ac0-2285-4d26-acfc-e8da113c95e4.mov

**Review by jsnmoon — CHANGES_REQUESTED** [review]
Clicking on the info icon in the Totals table redirects me to the traffic page, which isn't a desired behavior.



Also, the new highlight section of the ads page was missing (though that's unrelated to this PR).

**Comment by kangzj** [comment]
Hey @jsnmoon Thanks for the review 👍 

it works okay for me. Could you please pull the new changes, try to rebuild Odyssey and try again - the totals section should be replaced by the highlights after the merge.

image

Thanks

**Review by jsnmoon — APPROVED** [review]
I rebuilt the assets using the latest checkout, and everything appears to work as expected 👍

**Pull request merged**
