### PR TITLE
Reader: Make blockquotes the same size as the rest of the content

### PR DESCRIPTION
**Pull request by kellychoffman**
This is a thing thats bugged me for a while. The `blockquote` style is so much bigger than the rest of the content. It can be a bit jarring. 

This PR makes it the same size. 

Before:
screen shot 2016-06-13 at 1 31 46 pm
screen shot 2016-06-13 at 1 32 46 pm

After:

screen shot 2016-06-13 at 1 32 01 pm

screen shot 2016-06-13 at 1 32 23 pm
(Kottke uses them a lot and he's at the top of my feed.)

Better? Worse? Leave it alone?

Test live: https://calypso.live/?branch=try/reader-blockquotes-smaller

### CODE REVIEW

**Comment by rickybanister** [comment]
Yeah, I can't really think of a precedent anywhere that would have a block quote be larger than the surrounding text. Same size feels just fine. There's enough color difference to set them apart.

**Comment by jancavan** [comment]
I like the same size text 👍  Not sure if the color difference is enough distinction though. I think for designers, yes, but probably not for everyone else. 

What do you think about adding a border on the left? I think those are pretty standard and works well.

**Comment by kellychoffman** [comment]
I thought about a border. Was trying to stay away from "over styling it" if there is such a thing. 

Do you think the indentation is enough? We could maybe increase it?

**Comment by jancavan** [comment]
> We could maybe increase it?

I think that could work. I was also thinking of italicizing it, but noticed that on Kottke's post, there's some italicized words within the blockquote.

Kinda still leaning towards the border though 😉

**Comment by kellychoffman** [comment]
Okay, I've come around to the border idea after seeing a post that was _only_ a blockquote. There was no way to tell it was. 

Blockquote only:
screen shot 2016-06-14 at 2 48 19 pm
In the feed:
screen shot 2016-06-14 at 2 49 53 pm
Within "normal" post content:
screen shot 2016-06-14 at 2 51 23 pm

**Comment by rickybanister** [comment]
> 👍

**Comment by jancavan** [comment]
Thanks for fixing this @kellychoffman, looks great 👏  🚢

**Comment by bluefuton** [comment]
Cheers @kellychoffman! 👍

**Pull request merged**
