### PR TITLE
Update toolkit plugin to v2.7

### PR DESCRIPTION
**Pull request by noahtallen**
#### Changes proposed in this Pull Request
Update toolkit plugin to v2.7.

Includes these changes (see https://github.com/Automattic/wp-calypso/commits/master/apps/editing-toolkit)
* ~Begin loading patterns from an API. (https://github.com/Automattic/wp-calypso/pull/45926)~ (reverted)
* New checkout style. (https://github.com/Automattic/wp-calypso/pull/46169)
* Improve styles of premium content login button. (https://github.com/Automattic/wp-calypso/pull/46227)
* Add new coming soon page pattern. (https://github.com/Automattic/wp-calypso/pull/46179)
* Improve styles of recurring payments block. (https://github.com/Automattic/wp-calypso/pull/46125)
* Add extra space to the first block when the page title is hidden. (https://github.com/Automattic/wp-calypso/pull/46003)
* Update the category of the premium content block. (https://github.com/Automattic/wp-calypso/pull/45978)

cc @roo2 @arcangelini @krymson24

#### Testing instructions
- Ensure the above PRs work on both simple and atomic sites.

### CODE REVIEW

**Comment by glendaviesnz** [comment]
@noahtallen what is the normal process if we get another change backed up behind an editing toolkit update? eg. we have another [Newspack block update](https://github.com/Automattic/newspack-blocks/issues/488#issuecomment-700986630) to bring in - is it easier to just merge this first and then create another PR to bring that in?

**Comment by noahtallen** [comment]
Nope, I think we can go ahead and bring that update into this PR, given it's mainly about updating newspack anyways! I haven't had time to test this yet, so anyone can feel free to incorporate, test and ship this along with that update :)

**Review by arcangelini — DISMISSED** [review]
Tested, looks good to me. Thanks @noahtallen

**Review by noahtallen — COMMENTED** [review]
**The teamcity unit tests in D50376-code are consistently indicating an issue in the wpcom blog posts rest API controller, so we cannot move forward with this until that's fixed.**

**Comment by glendaviesnz** [comment]
@arcangelini looks like the broken tests may be related to https://github.com/Automattic/newspack-blocks/commit/dd69bc2939f5200b9fa94a66d60af666f70f13bf, committing some of this out got rid of at least 3 of the failing tests

**Comment by arcangelini** [comment]
Oof, ok I am pinging @laurelfulford because it looks like she worked on that PR. Hopefully this isn't caused by the one line of code I added `min-width: 0;` hahaha.

**Comment by laurelfulford** [comment]
Thanks for the ping on this! I'm far from an expert on Teamcity tests, but I did some digging: 

Two of the errors look like they have to do with the rest fields that have been added since the last update to the Newspack Blocks -- the tests don't expect them to be there.`test_get_item_schema()` needs to be updated to account for 2 more fields, and `test_get_post_edit_context_properties()` needs to be updated to include the names of the fields, `newspack_blocks_post_format`, and `newspack_post_sponsors`. Here's an example from a past update: 208502-wpcom. 

The date errors I'm less sure about -- did they stop happening when the Newspack Blocks update was removed, too?

**Comment by noahtallen** [comment]
For the time being, I will have to [revert the newspack update](https://github.com/Automattic/wp-calypso/pull/46287). We need to create a new PR which updates newspack, and make sure that we merge updates to the WordPress.com unit tests at the same time as we deploy the WordPress.com code which includes the newspack update.

I'm reverting because I'm unsure how long it will take to sort out the tests, and there a lot of unreleased fixes to the editing toolkit plugin.

**Comment by jeffersonrabb** [comment]
> For the time being, I will have to revert the newspack update. We need to create a new PR which updates newspack, and make sure that we merge updates to the WordPress.com unit tests at the same time as we deploy the WordPress.com code which includes the newspack update.

Hi @noahtallen I'm looking into updating those tests but it will be a little while, so reverting is a good strategy for now.

**Review by noahtallen — COMMENTED** [review]
Everything is testing well for me on both simple and atomic sites, so I think this is ready to go 👍

**Review by apeatling — DISMISSED** [review]

**Comment by noahtallen** [comment]
**NOTE: avoid deploying again until performance issues are addressed.**

**Comment by noahtallen** [comment]
superseded by #46444

**Pull request closed without merging**
