### PR TITLE
Performance: Tweak some descriptions based on feedback

### PR DESCRIPTION
**Pull request by danielbachhuber**
From pdKhl6-2mb-p2#comment-3549

## Proposed Changes

Tweaks some descriptions based on feedback:

image

## Testing Instructions

1. Navigate to the Performance page.
2. Verify the descriptions appear as expected.

### CODE REVIEW

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/8602626

Thank you @danielbachhuber for including a screenshot in the description! This is really helpful for our translators.

**Comment by Poliuk** [comment]
LGTM!

**Review by jeherve — APPROVED** [review]

**Review by sejas — COMMENTED** [review]
It works as expected 👍 

| **Before** | **After** |
|---|---|
| Screenshot 2023-07-24 at 09 53 13 | Screenshot 2023-07-24 at 09 52 52 |

**Review by sejas — APPROVED** [review]

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/8602626).

**Pull request merged**
