### PR TITLE
Gutenberg: PR for e2e testing of Gutenberg v6.3.0 RC1 on Horizon.

### PR DESCRIPTION
**Pull request by kwight**
This PR is for running e2e tests on Horizon to test Gutenberg v6.3.0 RC1, and making any required test fixes.

### CODE REVIEW

**Comment by kwight** [comment]
Failures:
Screen Shot 2019-08-13 at 2 18 40 PM
Screen Shot 2019-08-13 at 2 19 00 PM

**Comment by kwight** [comment]
`Timed out waiting for element with css selector of '.jetpack-simple-payments-wrapper' to be present and displayed` coincides with feedback from p7DVsv-783-p2, and doesn't need adjustment here (likely a regression in Gutenberg core).

**Comment by kwight** [comment]
Not sure about `.components-snackbar__content a`; I have no problem producing it when manually updating a post.

**Comment by kwight** [comment]
Latest results are based on running e2e tests after updating Horizon to the official 6.3.0 release from today.

Screen Shot 2019-08-14 at 3 35 44 PM
Screen Shot 2019-08-14 at 3 36 50 PM

`Timed out waiting for element with css selector of 'input.components-form-token-field__input' to be present and displayed`: I don't have any problem manually accomplishing this task; the markup seems correct.

**Comment by mmtr** [comment]
I can reproduce the failure of the "Schedule Basic Public Post" test in a self-hosted site as well, when using Gutenberg 6.3.0:

Aug-15-2019 11-15-40

The issue is not reproducible on 6.2.0, so seems to be a regression. I filed an issue on the Gutenberg repo: https://github.com/WordPress/gutenberg/issues/17042

**Comment by mmtr** [comment]
> Not sure about `.components-snackbar__content a`; I have no problem producing it when manually updating a post.

It might be caused by the snackbars being placed behind the inline help:

Screen Shot 2019-08-15 at 14 15 32

**Comment by mmtr** [comment]
> > Not sure about `.components-snackbar__content a`; I have no problem producing it when manually updating a post.
> 
> It might be caused by the snackbars being placed behind the inline help

I verified the notices are also a bit misplaced when using the plugin on a self-hosted site, so it looks like another regression introduced by Gutenberg 6.3.0: https://github.com/WordPress/gutenberg/issues/17045

Anyway, even with 6.2.0 the inline help hides part of the notices content, but it is visible enough to pass the E2E test.

Screen Shot 2019-08-15 at 15 42 11

Maybe we could adjust the position of the notices with an override in Gutenframe and make them totally visible, so we don't depend on a fix by Core.

**Comment by kwight** [comment]
We have enough regression issues that we've decided to wait for 6.4.0 (see paYKcK-bO-p2).

**Pull request closed without merging**
