### PR TITLE
Social Previews: update Facebook preview to reflect current look

### PR DESCRIPTION
**Pull request by frontdevde**
This PR aims to bring the Facebook Preview of Social Previews in line with the current look of Facebook's preview.

The related issue is https://github.com/Automattic/wp-calypso/issues/44799

## Screenshots

**Website - Facebook Sharing Debugger**

Screenshot 2020-08-19 at 16 29 17

**Website - Facebook Social Preview**

|Before|After|
|-|-|
| Screenshot 2020-08-19 at 16 31 48 | Screenshot 2020-08-19 at 16 29 26 |

---

**Article - Facebook Sharing Debugger**

Screenshot 2020-08-19 at 16 29 20

**Article - Facebook Social Preview**

|Before|After|
|-|-|
| Screenshot 2020-08-19 at 16 32 00 |Screenshot 2020-08-19 at 16 29 23 |

## Changes proposed in this Pull Request

This PR introduces the following changes to the Facebook Preview:

1. Changes to both the `website` and `article` previews:
- Move URL to the top
- Add background and border
- Ensure text content stays within body boundaries
- Add ellipsis to long URLs
- Change description color
- Remove box shadow around preview area
- Update title font size, line height and font family
- Update URL & description font size and line height

2. Changes the `website` preview
- Center text content when site tagline is short
- Ensure title wraps for very long words

3. Changes the `article` preview
- Clamp description after one line

## Testing instructions

For both previews:

- check out branch and `yarn start`

For Website preview:
- Navigate to http://calypso.localhost:3000/view and pick a site
- once loaded, switch to the "Search & Social" Facebook preview and check changes described above

For Article preview:
- Navigate to a post or page with adequate content and select Preview
- once loaded, switch to the "Search & Social" Facebook preview and check changes described above

### CODE REVIEW

**Comment by obenland** [comment]
Not sure how pedantic we need to be here, but I noticed the website preview looks slightly different in the debugger than it does in Calypso:

The bottom border seems to be cut off for the image placeholder. 
Screen Shot 2020-08-19 at 3 27 02 PM

In general, borders and border colors seem to be handled a little differently (eg. no borders left & right):
Calypso | Facebook
-- | --
image | image

**Comment by frontdevde** [comment]
> The bottom border seems to be cut off for the image placeholder.

Will adjust the box-sizing accordingly. 👌


> In general, borders and border colors seem to be handled a little differently (eg. no borders left & right):

In the Facebook Sharing debugger the left and right border are missing because they are not part of the shared content but the Facebook UI for a post. When a website gets posted to your feed, it will thus have borders. 

I'd argue our goal should be to reflect the final result when a user shares to their feed rather than the Sharing debugger. With that in mind, I'd definitely vote for keeping the border on the edge of the content.

Screenshot 2020-08-20 at 10 34 00

**Comment by frontdevde** [comment]
Updated the image placeholder's border and background:

Screenshot 2020-08-20 at 10 42 49

**Review by marekhrabe — APPROVED** [review]
Nice to see it refreshed!

**Review by marekhrabe — APPROVED** [review]

**Pull request merged**
