### PR TITLE
Remove center justification on panel content

### PR DESCRIPTION
**Pull request by lsl**
Related to #

## Proposed Changes

Pulling page content left due to the addition of a new sidebar navigation component within the content.

Before

Screenshot 2024-10-30 at 15-54-11 Sites ‹ Site Title — WordPress com
Screenshot 2024-10-30 at 15-53-57 Sites ‹ Site Title — WordPress com

After

Screenshot 2024-10-30 at 15-53-44 Sites ‹ Site Title — WordPress com
Screenshot 2024-10-30 at 15-53-32 Sites ‹ Site Title — WordPress com

A4A Before
Screenshot 2024-10-31 at 09-29-06 Boost — Automattic For Agencies

A4A After
Screenshot 2024-10-31 at 09-28-47 Boost — Automattic For Agencies

### CODE REVIEW

**Review by arthur791004 — COMMENTED** [review]
LGTM 👍 But I'm not sure whether it makes sense to a4a?

**Review by fushar — COMMENTED** [review]
Interesting... I wonder if it's a recent regression? Based on @lucasmendes-design's [design](https://github.com/Automattic/dotcom-forge/issues/6828#issuecomment-2086983773) earlier this year, it says:

> SET MAX-WIDTH
> All contents inside the tabs (Overview, PHP logs, etc) should have the same max-width. More than that, we can left-align.

So this PR's behavior should've been the correct one 🤔

**Comment by fushar** [comment]
Yeah, I'm also not sure whether we should make the change in a4a code; the lines between us is a bit blurry now 😄

**Review by okmttdhr — APPROVED** [review]
Given the design in Ashar's comment: https://github.com/Automattic/wp-calypso/pull/95852#pullrequestreview-2403653484, I believe we can just remove this (worth doing heads-up?). I don't think we want to add any more divergence from A4A.

**Comment by lsl** [comment]
Asked in #a4a-dev. I think this is better on a4a as well but there are other pages around calypso / a4a that aren't left aligned so it might not make sense for consistency reasons.

**Pull request merged**
