### PR TITLE
GitHub deployments: make more stuff work on Deployments page; start on Deployment runs (WIP)

### PR DESCRIPTION
**Pull request by mpkelly**
Related to https://github.com/Automattic/dotcom-forge/issues/5587
Related to https://github.com/Automattic/dotcom-forge/issues/5332

Screenshot 2567-02-19 at 17 45 03

Screenshot 2567-02-21 at 16 04 27

Screenshot 2567-02-21 at 16 04 13

## Proposed Changes

* Deployments page is almost done now: sorting working; menu done; duration updated; commit message working, except for the manual deployments which Jeroen is aware of
* I've tidied up sorting
* Introduced some components so we can compose tables easily
* Started on the Deployment Runs Dialog, which might change to a page (see p1708314648768049-slack-C06D9M3CHMK)

## Testing Instructions

*

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Comment by zaguiini** [comment]
Love this! Can we split it into multiple PRs? It's a monster to review now, and the concerns look very mixed.

Can we display something if there are no deployment runs for a deployment?

image

Does it make sense to remove the duration column and add it alongside each deployment run in the deployment run list?

I'd like to poll the deployments every 10 seconds, so that the user doesn't need to refresh the page to see action. We could reduce this to 5 seconds in case a manual deployment was triggered from within the UI.

Can we also apply a white background? The gray one looks 🤮

**Comment by mpkelly** [comment]
> Can we also apply a white background? The gray one looks 🤮

I didn't change anything but it is white now. It's using `PageShell` which should make the background white. 

>Can we split it into multiple PRs? It's a monster to review now, and the concerns look very mixed.

How about merging it and then doing a review of every screen in a separate task? I feel like we've fired in a lot of code over the last few weeks and need to review everything. 

I will add the polling and empty state views now. I asked Javier about the duration column AkPDFrEtrfwxjLrVZzjRaj-fi-4603:92545#709212611. 

@zaguiini

**Comment by javierarce** [comment]
> Does it make sense to remove the duration column and add it alongside each deployment run in the deployment run list?

I wouldn't take it out. Having a duration column that auto-increments when the deployment is happening is important, becouse it signals there's a build process in progress.

**Comment by zaguiini** [comment]
>How about merging it and then doing a review of every screen in a separate task? I feel like we've fired in a lot of code over the last few weeks and need to review everything.

👍 

>becouse it signals there's a build process in progress.

Isn't that the role of the "status" column?

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/11392085

Some locales (Hebrew, Japanese) have been temporarily machine-translated due to translator availability. All other translations are usually ready within a few days. Untranslated and machine-translated strings will be sent for translation next Monday and are expected to be completed by the following Friday.

Thank you @mpkelly for including a screenshot in the description! This is really helpful for our translators.

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/11392085).

**Pull request merged**
