### PR TITLE
Update FSE plugin to version to 1.13

### PR DESCRIPTION
**Pull request by deBhal**
#### Changes proposed in this Pull Request

Version bump and changelog.

#### Testing instructions

This deploy includes quite a number of PRs, so I'm going to ask as many authors as possible to quickly re-test their changes against the release candidate to make sure there are no surprising interactions.

The detailed instructions are in the field-guide here: 
- (wpcom) https://wp.me/PCYsg-ly5/#viewing-the-fse-features
- (atomic) https://wp.me/PCYsg-ly5/#atomic-testing

But if you just need the short version:
* Apply code-D46328
* Test on a sandboxed simple-site with appropriate FSE-plugin flags
* Test on an atomic site with and without Gutenberg enabled

Here's the rc plugin link for your convenience [fse-build-archive](https://github.com/Automattic/wp-calypso/suites/939857407/artifacts/11616059) (2.23 MB) (updated to include fix by @akirk)

Please also add any comment you'd like included in changelog here, and I'll add them in before I merge

#### Changelog entries

* Change the category of FSE blocks from legacy to the updated ones (https://github.com/Automattic/wp-calypso/issues/43198).
* Add a helper function that can be used to assign categories with older fallbacks.
* Add support for TypeScript tests.
* Update visual style of navigation sidebar.
* Fix navigation sidebar dismiss button in IE.

#### PRs to test

- https://github.com/Automattic/wp-calypso/pull/43935 @razvanpapadopol
  - [x] wpcom
  - [x] AT
- https://github.com/Automattic/wp-calypso/pull/43983 @razvanpapadopol
  - [x] wpcom
  - [x] AT
- https://github.com/Automattic/wp-calypso/pull/44087 @yansern / @razvanpapadopol
  - [x] wpcom
  - [x] AT
- https://github.com/Automattic/wp-calypso/pull/43993 @saramarcondes
  - [x] wpcom
  - [x] AT
- https://github.com/Automattic/wp-calypso/pull/41474 @jasmussen / @georgeh
  - [x] wpcom
  - [x] AT
- https://github.com/Automattic/wp-calypso/pull/44021 @andrewserong
  - [x] wpcom
  - [x] AT
- https://github.com/Automattic/wp-calypso/pull/43906 @p-jackson
  - [x] wpcom
  - [x] AT
- https://github.com/Automattic/wp-calypso/pull/44092 @p-jackson
  - [x] wpcom
  - [x] AT
- https://github.com/Automattic/wp-calypso/pull/44199 @ramon / @p-jackson
  - [x] wpcom
  - [x] AT
- https://github.com/Automattic/wp-calypso/pull/44196 @ramonjd 
  - [x] wpcom
  - [x] AT
- https://github.com/Automattic/wp-calypso/pull/44077 @yansern 
  - [x] wpcom
  - [x] AT
- https://github.com/Automattic/wp-calypso/pull/43670 @fullofcaffeine 
  - [x] wpcom
  - [x] AT
- https://github.com/Automattic/wp-calypso/pull/44127 @p-jackson 
  - [x] wpcom
  - [x] AT
- https://github.com/Automattic/wp-calypso/pull/44243 @kwight
  - [x] wpcom
  - [x] AT
- https://github.com/Automattic/wp-calypso/pull/44191 @gwwar
  - [x] wpcom
  - [x] AT

#### Final pre-release checks

- [x] Confirm `phpcbf` fixes occur in the Github action build log (Should be in Build FSE plugin/Build packages
Update_FSE_plugin_to_version_to_1_13_by_deBhal_·_Pull_Request__44125_·_Automattic_wp-calypso

### CODE REVIEW

**Comment by deBhal** [comment]
https://github.com/Automattic/wp-calypso/pull/43670 is merged and https://github.com/Automattic/wp-calypso/pull/44191 fixes https://github.com/Automattic/wp-calypso/issues/44160, so we're clear to go ahead now.

**Comment by akirk** [comment]
@deBhal I have added a commit to this PR that should fixes the error:
```
@automattic/full-site-editing: ./bin/sync-newspack-blocks.sh: line 132: ../../vendor/bin/phpcbf: No such file or directory
@automattic/full-site-editing: phpcbf: !! There was an error executing phpcbf
```
I last fixed this here: https://github.com/Automattic/wp-calypso/pull/43857/commits/0cfd9a36cc55dd23bf35b454deebe754973d69cb but it looks like in recent builds the "Build packages" step was skipped in favor of "Build dependencies" ([Checks log 1.11.0](https://github.com/Automattic/wp-calypso/pull/43857/checks?check_run_id=829700065) vs [Checks log 1.12.0](https://github.com/Automattic/wp-calypso/pull/43903/checks?check_run_id=840181692)), I am observing the same in this PR.

This caused the textdomains not to be fixed as anticipated, so I hope to have fixed this again and for a longer period :)

**Comment by noahtallen** [comment]
>  so I hope to have fixed this again and for a longer period :)

🤦 Sorry that we didn't catch this again. Would it be helpful to add a unit test for this so PRs fail when the textdomain in newspack blocks does not get updated?

**Comment by kwight** [comment]
@deBhal Serenity's pieces are good to go; we've got some additional followup, but nothing that results in fatals or should hold up pushing out this version. 👍

**Comment by akirk** [comment]
@noahtallen How would you approach this? We are talking about files that are not committed, just shipped in the ZIP file, plus I'm not sure we can be certain about which files exist, newspack blocks could change their file layout.

**Comment by deBhal** [comment]
@akirk: I created https://github.com/Automattic/wp-calypso/issues/44296 with a simple suggestion for fixing the textdomain issue

**Comment by saramarcondes** [comment]
Hi @deBhal. My changes are just to CircleCI so can be ✅; no actual changes to the plugin.

**Comment by noahtallen** [comment]
> We are talking about files that are not committed, just shipped in the ZIP file

True... though they should still exist in the local filesystem for any test purposes, so long as we are testing against a "built" version of the plugin! Some ideas...

1. move the check to the build step, and then allow the build step to fail if the textdomain was not translated
2. just test against a fairly stable file, like `class-newspack-blocks.php` (though I guess that could change to not have any translated strings in it 🤔 )
3. Add a special lint-check in GitHub CI which runs phpcs on `full-site-editing-plugin/newspack-blocks-synced-newspack-blocks` using the build artifact, and only fails if the textdomain rule fails

**Comment by fullofcaffeine** [comment]
Tested on an FSE-enabled simple site and it looks good. Took into account the changes from Serenity.

In AT sites I couldn't fully test it though. There appears to be a bug preventing FSE from enabling on AT sites, see: https://github.com/Automattic/wp-calypso/issues/41825. Discussion: p1595373248144700-slack-cylon.

**Comment by deBhal** [comment]
@fullofcaffeine: I forced the dotcom-fse on on my ephemeral site (see  #41825) and tested this release + dotcom-fse (these names are so confusing :/) with and without gutenberg enabled, and it all looks good, so I'm going to go ahead and tick that off:

Add_New_Page_‹_My_WordPress_Site_—_WordPress

**Comment by georgeh** [comment]
The Timeline block changes look good on wpcom simple and Atomic

**Comment by deBhal** [comment]
Ok, last check is in.

Those signup timeout failures in the e2e tests are known, and not related to this diff, so we're going ahead.

**Comment by sirreal** [comment]
👋  I've just landed https://github.com/Automattic/wp-calypso/pull/44357, can I pull it in here?

**Comment by sirreal** [comment]
I've rebased to pull in https://github.com/Automattic/wp-calypso/pull/44357.

**Comment by deBhal** [comment]
> I've rebased to pull in #44357.

Ok, I'm going to trust you know what you're doing, and just do an additional smoke test.

**Pull request merged**
