### PR TITLE
Revert Popover refactoring

### PR DESCRIPTION
**Pull request by aidvu**
This reverts commit c307d7db704a2e0633de2d5d0af0c6066afada0d.

#### Changes proposed in this Pull Request

* Revert Popover refactoring, broke Chat.

#### Testing instructions

- Visit Calypso
- Click on the question mark (Chrome/Safari)
- Try to start a chat

Before:
- Window disappears

After revert:
- Chat is up

### CODE REVIEW

**Comment by gwwar** [comment]
Lint errors look harmless 👍

**Comment by beaucollins** [comment]
I am able to connect to production happychat chats with this revert in place.

**Review by beaucollins — APPROVED** [review]

**Comment by lancewillett** [comment]
Note for later: after we find out what went wrong — let's P2 a short report so that we share any lessons learned.

**Comment by lancewillett** [comment]
Props @aidvu and @beaucollins 🥇

**Comment by beaucollins** [comment]
This was the line that was throwing the client error:

https://github.com/Automattic/wp-calypso/blob/57261aa3f0b3398e720a6ae91a6c03b88028e62c/client/components/popover/index.jsx#L314

`domContainer` was `null` and `.clientHeight` raised a `null` access error here

https://github.com/Automattic/wp-calypso/blob/57261aa3f0b3398e720a6ae91a6c03b88028e62c/client/components/popover/util.js#L78

**Pull request merged**
