### PR TITLE
Changed the command palette icon to the one provided by design

### PR DESCRIPTION
**Pull request by rcrdortiz**
Related to
- https://github.com/Automattic/wp-calypso/issues/89578
- https://github.com/Automattic/wp-calypso/issues/90930
## Proposed Changes

* Changed the icon from a magnifying glass to the one provided by design.
* Changed the tooltip.

## Why are these changes being made?

* The magnifying glass icon doesn't have the expected engagement since users do not associate it with the command palette, by changing the icon we want to increase the engagement.

## Testing Instructions

* Open the Calypso live link
* visit `/sites`
* You should see that the icon corresponds with the new icon instead of the magnifying glass.
* The tooltip should have the updated text corresponding with the new icon.

Before:
Screenshot 2024-05-22 at 15 53 34

After:
Screenshot 2024-05-22 at 15 53 18

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Comment by mmtr** [comment]
Looks great! However, the tooltip message seems to be based on the previous search icon. Should we change it to something else like "Open command palette"?

**Comment by rcrdortiz** [comment]
> Looks great! However, the tooltip message seems to be based on the previous search icon. Should we change it to something else like "Open command palette"?
> 
> Screenshot 2024-05-22 at 16 12 28

Yeah, I was working on that just now, that's why I removed the `Needs review` label from the PR.

**Review by mmtr — APPROVED** [review]
¡Perfecto!

**Comment by mmtr** [comment]
Actually, a minor thing. Seems that the icon is not using the same color as the other icons.
Screenshot 2024-05-22 at 17 20 51
Screenshot 2024-05-22 at 17 20 36

The notifications and help icons are using `#2c3338` but the command palette uses `#1E1E1E`

**Comment by rcrdortiz** [comment]
> Actually, a minor thing. Seems that the icon is not using the same color as the other icons.
> 
> Command palette icon: Screenshot 2024-05-22 at 17 20 51
> 
> Notifications icon: Screenshot 2024-05-22 at 17 20 36
> 
> The notifications and help icons are using `#2c3338` but the command palette uses `#1E1E1E` which is a bit darker.

I copied the SVG from the icon library Figma file. I'll change the color so that all the icons share the same color.

**Comment by rcrdortiz** [comment]
@mmtr Changed the color.

**Comment by mmtr** [comment]
> @mmtr Changed the color.

Thanks! Pushed another commit to rely on the CSS variable instead of hardcoding the color.

**Comment by mmtr** [comment]
Just realized that we have a different icon for mobile viewports in the header that needs to be replaced too:

Screenshot 2024-05-22 at 17 43 14

**Comment by rcrdortiz** [comment]
> Just realized that we have a different icon for mobile viewports in the header that needs to be replaced too:
> 
> Screenshot 2024-05-22 at 17 43 14

Fixed, there were two different implementations that didn't share a common button. I've created a button component that we can re-use from other components to avoid needing to update n icons if it ever changes.

**Pull request merged**
