### PR TITLE
Add/launchpad site preview integration

### PR DESCRIPTION
**Pull request by agrullon95**
#### Proposed Changes

This PR adds the initial component for the Launchpad site preview.
I added a separate component for the site preview itself and updated the existing launchpad styling.

image

#### Testing Instructions

- Check out this PR
- Run yarn and yarn start 
- Open http://calypso.localhost:3000/setup/launchpad?flow=newsletters&siteSlug={siteSlugHere}
- Make sure you enter a valid site slug in the URL or the site preview will not load
- Confirm that site preview component renders like the screenshot above.

#### Pre-merge Checklist

- [ ] [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?

Related to #66131

### CODE REVIEW

**Comment by edanzer** [comment]
Tested and this looks good. I've approved the PR. I tested the following: 
- Review the code itself. Seems straightforward and clean. 
- Tested the Launchpad UI in Chrome, Firefox, and Safari.
- Tested switching between device sizes in all browsers.
- Not sure if it matters, but I tested adding both a Simple site url and Atomic site url as the preview URL. Both seem to work. 

Small notes that don't raise concerns:
- If you resize your browser screen to a small size, the toolbar icons disappear. I assume that's built into the WebPreview component, based on the notion that you can't effectively a preview a full website size version of your website when using a phone or small mobile device. 
- If you load the Launchpad without a siteSlug parameter, you'll just get the "loading..." text inside the preview. I would think we'd avoid this since we control the stepper flow, and it seems like an OK fallback if the parameter is missing in any case. [http://calypso.localhost:3000/setup/launchpad?flow=newsletters](http://calypso.localhost:3000/setup/launchpad?flow=newsletters)
- Interestingly, if you enter any url that doesn't belong to a simple or atomic site, the entire page redirects. For example, try http://calypso.localhost:3000/setup/launchpad?flow=newsletters&siteSlug=wordpress.com.

**Review by edanzer — APPROVED** [review]

**Comment by edanzer** [comment]
One other small note: Not sure how/if we want to eventually manage the height of the iframe for the preview. But for me - on a 14 inch Macbook Pro, the iframe is not that heigh, and so only shows the top section of the previewed site. At the same time, it's heigh enough that I have to scroll just a bit to see the bottom.

**Comment by agrullon95** [comment]
Thanks for the review and the concerns you raised.

>If you resize your browser screen to a small size, the toolbar icons disappear. I assume that's built into the WebPreview component...

Correct, this is built into the WebPreview component. If the viewport is 'mobile', it hides the toolbar component with the device switcher. 

>If you load the Launchpad without a siteSlug parameter, you'll just get the "loading..." text inside the preview.

I set this as a temporary placeholder if the siteSlug wasn't included. We eventually want to add a better fallback in case users navigate to the launchpad without the siteSlug. We will be avoiding this issue with the stepper flow since we will always provide the siteSlug query argument.

> One other small note: Not sure how/if we want to eventually manage the height of the iframe for the preview

I had the same thoughts. My initial thoughts are that we should manage the height. We could do something similar to the designSetup step WebPreview implementation. The iframe is always 48px above the bottom of the page and it expands/shrinks as I change the height of the browser.

@nuriapenya 
What do you think about the implementation I mentioned above?
You can view this designSetup WebPreview: https://wordpress.com/setup/designSetup?siteSlug={siteSlug}

Also, do you have an example of how we expect the site preview to look on a desktop/tablet device with different use cases/sites? Are we were expecting the site preview to fit within the frame without any scrolling? I know our current use cases (Newsletter, Link in Bio, podcast, etc.) seem to result in simple and small sites, so its possible they will fit within the iframe, but I'm curious to hear if I'm missing anything.

**Comment by nuriapenya** [comment]
Cool stuff @agrullon95! It's great to start seeing things live! ✨

> We could do something similar to the designSetup step WebPreview implementation.

Exactly, that will work. We could leave the same space, for now, 48px. The one thing to consider is that we will go for a Sidebar layout - And in this sense, the left column needs to have a fixed width. But for the preview, as you mentioned above, it will expand/shrink with the browser.

Something like this:


https://user-images.githubusercontent.com/7931304/183945191-dc8f30ca-288d-4c66-8949-28b7cfad2ee0.mov

> Also, do you have an example of how we expect the site preview to look on a desktop/tablet device with different use cases/sites? 

I'm currently working on that, and hopefully, I will be P2 ing all these details tomorrow 🙏🏽

**Pull request merged**
