### PR TITLE
Stepper: only preload steps after having site data

### PR DESCRIPTION
**Pull request by sgomes**
The Stepper framework currently preloads all steps in a flow as a React effect. This means that they effectively get preloaded after the first `FlowRenderer` render.

For several scenarios this is fine, as the first render already includes meaningful information that the user can analyse, which effectively makes this idle time where the browser can be busy preloading things.

However, for the very common scenario that the step depends on a selected site's data, the first render can be missing said data, with an API call needed first. In that scenario, the framework renders a blank "W" page and starts fetching, parsing, compiling, and initialising all the future steps while waiting for that API response. This means that the CPU can be busy when the response arrives, thereby delaying the first meaningful render (of something other than the "W" background).

This PR changes that, by waiting for site data on steps that depend on it, before starting the preload.

## Proposed Changes

* Wait for site data before speculatively preloading future steps

## Why are these changes being made?

* To guarantee that the current step loads as quickly as possible on CPU-constrained devices, particularly if there are resource-heavy steps at the end of a flow (e.g. block / site editing steps)

## Testing Instructions

* Open DevTools
* Optionally throttle your network
* Load the "Goals" step in the `site-setup` flow for one of your sites: `/setup/site-setup/goals?siteSlug=<SITE_SLUG>&siteId=<SITE_ID>`
* Ensure that the downloads for future steps only start after the checkboxes show on screen
* Smoke test other steps and flows as much as you'd like, to ensure that this change doesn't unintentionally break anything

## Pre-merge Checklist

- [X] Has the general commit checklist been followed? (PCYsg-hS-p2)
- N/A [Have you written new tests](https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md) for your changes?
- N/A Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [X] Have you checked for TypeScript, React or other console errors?
- N/A Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- N/A Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- N/A For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Comment by alshakero** [comment]
Thank you so much for this. I think this works great for site-setup, but many flows don't use `siteSlug` and it will never be truthy for them. Like link-in-bio, newsletter, and many others. And I feel these flows that don't require the slug are more important because it means it's the first time ever the user is dealing with WordPress.com

**Comment by sgomes** [comment]
> many flows don't use `siteSlug` and it will never be truthy for them. Like link-in-bio, newsletter, and many others. And I feel these flows that don't require the slug are more important because it means it's the first time ever the user is dealing with WordPress.com

I think I may have been less than clear, but the goal is only to wait for site data where it is indeed used:

```js
if ( siteSlugOrId && ! selectedSite ) {
  return;
}
```

Or did I miss some edge case here?

**Comment by alshakero** [comment]
Oh my bad totally. I misread the code thinking it required the slug and the site! This is a great quick solution.

**Review by alshakero — APPROVED** [review]
It definitely works, and the steps are pre-loaded, no fading W. I verified that loading the steps chunks was starting after the site is fetched. Thanks again!

**Comment by sgomes** [comment]
Thank you for the super quick review, @alshakero! 🙌

I'll merge this tomorrow morning my time, so I know I'll be around if something goes awry 🙂

**Pull request merged**
