### PR TITLE
Reader: Add an icon to the Visit and Share links on cards.

### LINKED ISSUE #2623: Reader: Add new window indicator to visit link
The "Visit" link needs an arrow, or some indication that it's going to open a new window:

screen shot 2016-01-20 at 11 10 14 am

### PR DESCRIPTION
**Pull request by blowery**
The Visit icon indicates that the click will take the user offsite.
The Share icon is because it looked lonely without it.

Also moved the click handler on the Share button up to the container, which matches where we apply the highlight and the pointer. No more just missing the click and moving to full post instead of the Sharing menu.

Last, stopped using onTouchTap, in favor of onClick, because onTouchTap doesn't seem capable of actually canceling an event properly, as least not in a manner that the card's click handler can understand and ignore.

Fixes #2623 

before
screenshot

after
screenshot

### CODE REVIEW

**Comment by shaunandrews** [comment]
What do you think about using a smaller icon after the label, like we do in full post:

screen shot 2016-01-20 at 4 34 55 pm

**Comment by blowery** [comment]
I kinda like having all the icons on the left and the same size

**Comment by shaunandrews** [comment]
I think it makes sense to keep the big icons for primary actions (likes, comments, and reblogs). I think it looks fine placing the external icon after the label, which matches it's use elsewhere in Calypso:

screen shot 2016-01-21 at 10 56 26 am

If we do want to promote Share to a primary action, we could move it to the right and give it an icon:

screen shot 2016-01-21 at 10 57 07 am

**Comment by blowery** [comment]
I like the second one! That works.

**Comment by shaunandrews** [comment]
Updated to match the mockup above:

screen shot 2016-01-21 at 3 05 39 pm

While I was in there, I updated the icons to use the new `SocialLogo` component:

screen shot 2016-01-21 at 3 05 47 pm

**Comment by blowery** [comment]
Cool that fixes #2508 too!

**Comment by blowery** [comment]
Awesome, this looks great. Shipping.

**Pull request merged**
