### PR TITLE
A4A: Update Product listing to follow design specs.

### PR DESCRIPTION
**Pull request by jkguidaven**
This pull request aligns the A4A Marketplace design specs with the current product listing. Existing components were tweaked to match the latest design.

https://github.com/Automattic/wp-calypso/assets/56598660/a37f6753-cfab-4df7-9d41-cfcf4eb9fe9f

Closes https://github.com/Automattic/jetpack-genesis/issues/285

## Proposed Changes

* Jetpack Manage's `LicenseProductCard` and `LicenseMultiProductCard` components have been ported and updated to use a button instead of a checkbox to represent the selection state, following the design specification.
* The IssueLicense component was renamed to the ProductsOverview component. Sub-components and CSS classes were also updated accordingly to match the new component name.
* Product listing sections have been updated; `<hr/>` removed, Product Icons (Jetpack & Woo) added to title.

## Testing Instructions

* Switch branch: `git checkout update/a4a/marketplace-product-card-design`.
* Start the server by running `yarn start-a8c-for-agencies`.
* Use the live link and go to`/marketplace`
* Confirm that the product overview page has been updated correctly based on the new design.
* **Note that the volume pricing has not been included in this PR and will be addressed in a separate PR.**

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Comment by madebynoam** [comment]
Hey @jkguidaven! @keoshi is at a workshop this week. I can go ahead and review it. Overall, this lgtm!

**Comment by jkguidaven** [comment]
Thanks @madebynoam that would be great 🙏

**Review by madebynoam — APPROVED** [review]
Design lgtm!

**Review by yashwin — APPROVED** [review]
It works as expected, and the code changes look good!

Good job on this, @jkguidaven!

**Pull request merged**
