### PR TITLE
Desktop App: Enable Gutenberg feature flags

### LINKED ISSUE #32048: Gutenframe: Verify editing flows on the desktop app.
We'll need to verify that editing flows all work as expected when working with Atomic and Jetpack sites within the WordPress.com Desktop app.

Background: p3fqKv-6Hh-p2.

### PR DESCRIPTION
**Pull request by codebykat**
#### Changes proposed in this Pull Request

This enables the `jetpack/gutenframe` and `calypsoify/gutenberg` feature flags in `desktop.json` and `desktop-development.json` in order to support editing flows with the block editor for Jetpack and Atomic sites.

#### Testing instructions

This needs to be tested on the desktop app, so make sure you have the dev environment [installed and running](https://github.com/Automattic/wp-desktop/blob/b729377828ec53f4469ed27a15c1fbc6e9b3a1cf/docs/install.md) (more info about how to set up the secrets in paaHJt-7y-p2).

* In the desktop repo, point the calypso submodule to this branch: `cd calypso && git fetch && git checkout update/enable-gutenframe-desktop-app`.
* <del>Create a build: `make build`.</del>
* <del>Open the built app in the `release` folder.</del>
* Check out the `develop` branch in `wp-desktop`.
* In one tab, run `make dev-server` within the `wp-desktop` folder.
* Once that completes, run `make dev` in a second tab. This should open a dev version of the app.
* Switch to a Jetpack or Atomic site test site running the Jetpack plugin version 7.3.
* Make sure that Gutenberg works like in the production environment for Simple sites:
  * Check opt-in and opt-out flows (making sure that the opt-out flow redirects to the classic editor which is opened inside the desktop app).
  * Try publishing a new post.
  * Test the Gutenframe integration (media modal, revisions, move to trash, etc).
  * Confirm that the back to the posts button redirects to the lists of posts page and it is opened inside the desktop app.
  * Try editing an existing post.
* Switch to a Jetpack or Atomic site test site running a version of the Jetpack plugin older than 7.3.
* Make sure that Calypso uses Calypsoify flows now and the block editor is opened in a new tab of your browser.

Fixes #32048

### CODE REVIEW

**Comment by mmtr** [comment]
I'm also getting the same error you were seeing yesterday @codebykat:

```
Error: ENOENT: no such file or directory, open 'calypso/server/bundler/assets-evergreen.json'
    at Object.fs.openSync (fs.js:584:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:173:20)
    at Object.fs.readFileSync (fs.js:491:33)
    at Object.fs.readFileSync (ELECTRON_ASAR.js:505:29)
    at Y (/Users/mmtr/dev/wp-desktop/release/mac/WordPress.com.app/Contents/Resources/app/build/desktop.js:510:10112)
    at Q (/Users/mmtr/dev/wp-desktop/release/mac/WordPress.com.app/Contents/Resources/app/build/desktop.js:510:10895)
    at X (/Users/mmtr/dev/wp-desktop/release/mac/WordPress.com.app/Contents/Resources/app/build/desktop.js:510:16751)
    at Layer.handle_error (/Users/mmtr/dev/wp-desktop/release/mac/WordPress.com.app/Contents/Resources/app/node_modules/express/lib/router/layer.js:71:5)
    at trim_prefix (/Users/mmtr/dev/wp-desktop/release/mac/WordPress.com.app/Contents/Resources/app/node_modules/express/lib/router/index.js:315:13)
    at /Users/mmtr/dev/wp-desktop/release/mac/WordPress.com.app/Contents/Resources/app/node_modules/express/lib/router/index.js:284:7
```

Not sure if we have to build the desktop app using a different command now. Maybe we should also [check here](https://github.com/Automattic/wp-calypso/blob/4479631cb241355d04cdd0f6ec139feb38a978c3/webpack.config.js#L45) for the `desktop-development` environment? I think that's the environment we define on the desktop app when running `make build` ([#](https://github.com/Automattic/wp-desktop/blob/1e72dc2c01ac69381d2308e427db86b298cb8203/Makefile#L50)).

Pinging @sgomes since he seems to have been working on the evergreen target build.

**Comment by sgomes** [comment]
@mmtr: This could definitely be related to my changes in #32253, where I tried to move the desktop build to using fallback instead of evergreen. There may be something I missed there, and it looks like it might have been the `desktop-development` environment, which I wasn't aware of. I'll continue discussion in @blowery's #32738

**Comment by kwight** [comment]
@codebykat @mmtr Do I understand correctly that this is dependent on #32738 first?..

**Comment by mmtr** [comment]
That's right @kwight. Builds are currently broken for the desktop app, and we're using #32738 to fix them.

**Comment by mmtr** [comment]
https://github.com/Automattic/wp-desktop/pull/599 might also unblock this.

**Comment by codebykat** [comment]
I've rebased this but I'm still having trouble getting the build to complete.

`make dev-server` just used up all the memory 😱 

Screen Shot 2019-06-04 at 11 19 58 AM

**Comment by codebykat** [comment]
Here's what I got after trying to `make dev-server` on `master`:

```WARNING in ./calypso/node_modules/browserslist/node.js
116:18-66 Critical dependency: the request of a dependency is an expression
 @ ./calypso/node_modules/browserslist/node.js
 @ ./calypso/node_modules/browserslist/index.js
 @ ./calypso/node_modules/browserslist-useragent/lib/index.js
 @ ./calypso/server/pages/index.js
 @ ./calypso/server/boot/index.js
 @ ./desktop/server/server.js
 @ ./desktop/server/index.js
 @ ./desktop/app.js
 @ ./desktop/index.js

WARNING in ./calypso/node_modules/encoding/lib/iconv-loader.js
9:12-34 Critical dependency: the request of a dependency is an expression
 @ ./calypso/node_modules/encoding/lib/iconv-loader.js
 @ ./calypso/node_modules/encoding/lib/encoding.js
 @ ./node_modules/electron-fetch/lib/index.es.js
 @ ./desktop/app-handlers/updater/manual-updater/index.js
 @ ./desktop/app-handlers/updater/index.js
 @ ./desktop/app.js
 @ ./desktop/index.js

WARNING in configuration
The 'mode' option has not been set, webpack will fallback to 'production' for this value. Set 'mode' option to 'development' or 'production' to enable defaults for each environment.
You can also set it to 'none' to disable any default behavior. Learn more: https://webpack.js.org/concepts/mode/

ERROR in ./calypso/client/components/infinite-scroll/index.js
Module not found: Error: Can't resolve 'lib/after-layout-flush' in '/Users/kat/code/wp-desktop/calypso/client/components/infinite-scroll'
 @ ./calypso/client/components/infinite-scroll/index.js 14:47-80
 @ ./calypso/client/components/themes-list/index.jsx
 @ ./calypso/client/my-sites/themes/themes-selection.jsx
 @ ./calypso/client/my-sites/themes/single-site-jetpack.jsx
 @ ./calypso/client/my-sites/themes/single-site.jsx
 @ ./calypso/client/my-sites/themes/controller.jsx
 @ ./calypso/client/my-sites/themes/index.node.js
 @ ./calypso/client/sections.js
 @ ./calypso/server/pages/index.js
 @ ./calypso/server/boot/index.js
 @ ./desktop/server/server.js
 @ ./desktop/server/index.js
 @ ./desktop/app.js
 @ ./desktop/index.js

ERROR in ./calypso/client/components/section-nav/tabs.jsx
Module not found: Error: Can't resolve 'lib/after-layout-flush' in '/Users/kat/code/wp-desktop/calypso/client/components/section-nav'
 @ ./calypso/client/components/section-nav/tabs.jsx 24:47-80
 @ ./calypso/client/my-sites/theme/main.jsx
 @ ./calypso/client/my-sites/theme/controller.jsx
 @ ./calypso/client/my-sites/theme/index.node.js
 @ ./calypso/client/sections.js
 @ ./calypso/server/pages/index.js
 @ ./calypso/server/boot/index.js
 @ ./desktop/server/server.js
 @ ./desktop/server/index.js
 @ ./desktop/app.js
 @ ./desktop/index.js

ERROR in ./calypso/client/components/sticky-panel/index.jsx
Module not found: Error: Can't resolve 'lib/after-layout-flush' in '/Users/kat/code/wp-desktop/calypso/client/components/sticky-panel'
 @ ./calypso/client/components/sticky-panel/index.jsx 22:47-80
 @ ./calypso/client/my-sites/themes/themes-magic-search-card/index.jsx
 @ ./calypso/client/my-sites/themes/theme-showcase.jsx
 @ ./calypso/client/my-sites/themes/logged-out.jsx
 @ ./calypso/client/my-sites/themes/controller.jsx
 @ ./calypso/client/my-sites/themes/index.node.js
 @ ./calypso/client/sections.js
 @ ./calypso/server/pages/index.js
 @ ./calypso/server/boot/index.js
 @ ./desktop/server/server.js
 @ ./desktop/server/index.js
 @ ./desktop/app.js
 @ ./desktop/index.js
make: *** [build-desktop] Error 2```

**Comment by mmtr** [comment]
Closing this in favor of https://github.com/Automattic/wp-calypso/pull/34833

**Pull request closed without merging**
