### PR TITLE
Jetpack Error UX: Show error banner in Plugins showcase

### PR DESCRIPTION
**Pull request by danielbachhuber**
See https://github.com/Automattic/dotcom-forge/issues/3394

## Proposed Changes

Shows an error notice on the Plugins showcase when Jetpack is unable to connect to the site:

image

Triggering logic was introduced in https://github.com/Automattic/wp-calypso/pull/79965

## Testing Instructions

1. Create a new Business site and take it Atomic.
2. Add some PHP code to `~/htdocs/wp-content/mu-plugins/local.php` that causes a fatal error.
3. Navigate to Plugins in Calypso.
4. Verify the notice appears as expected.
5. Fix your fatal error.
6. Reload the Plugins view.
7. Verify the notice no longer appears.

Flagging @Automattic/bespin  and @Automattic/explorers  for review in case there are other aspects that need to be tested/considered.

### CODE REVIEW

**Review by wojtekn — APPROVED** [review]
@danielbachhuber looks good to me and works well.

I noticed that unit tests are failing, so I dug into this. I fixed the state selector to ensure it doesn't fail if state ket doesn't exist and adjusted the existing Jetpack connection test after replacing the existing component with our new one.

**Review by cpapazoglou — APPROVED** [review]
LGTM! Thanks for the changes.

Just noting that `JetpackDisconnectedNotice` had a similar role. Curious why we didn't refactor `JetpackDisconnectedNotice` in the first place.

**Comment by wojtekn** [comment]
> Just noting that JetpackDisconnectedNotice had a similar role. Curious why we didn't refactor JetpackDisconnectedNotice in the first place.

We are implementing the more comprehensive solution as a part of pesfPa-hO-p2.

@cpapazoglou @danielbachhuber as with this PR the `JetpackDisconnectedNotice` component is not used anymore, should we remove it?

**Comment by cpapazoglou** [comment]
> > Just noting that JetpackDisconnectedNotice had a similar role. Curious why we didn't refactor JetpackDisconnectedNotice in the first place.
> 
> We are implementing the more comprehensive solution as a part of pesfPa-hO-p2.
> 
> @cpapazoglou @danielbachhuber as with this PR the `JetpackDisconnectedNotice` component is not used anymore, should we remove it?

Yes, that would be great.

**Comment by danielbachhuber** [comment]
> I noticed that unit tests are failing, so I dug into this. I fixed the state selector to ensure it doesn't fail if state ket doesn't exist and adjusted the existing Jetpack connection test after replacing the existing component with our new one.

@wojtekn Thanks!

> as with this PR the `JetpackDisconnectedNotice` component is not used anymore, should we remove it?

@cpapazoglou Yep, I'll do so in a follow-up PR.

**Comment by danielbachhuber** [comment]
> Yep, I'll do so in a follow-up PR.

https://github.com/Automattic/wp-calypso/pull/80402

**Pull request merged**
