### PR TITLE
Sites Management Page: Visually distinguish 'redirect' sites

### LINKED ISSUE #66746: Sites Management Page: Visually distinguish redirect sites
From pdtkmj-nh-p2#comment-582

The Site Selector calls out 'Redirect' sites:

image

However, the Sites Management Page does not:

image

**Done is:**
* Redirect sites are visually distinguished in Tile view and Grid view. Implementation TBD.

### PR DESCRIPTION
**Pull request by danielbachhuber**
Fixes #66746

## Proposed Changes

Visually distinguishes 'redirect' sites in the List view and Grid view, and uses `site.options.unmapped_url` instead of `site.URL` for redirect sites:

image

image

## Testing Instructions

1. Create a new Free site.
2. Add the Site Redirect Add-On to the new Free site: https://wordpress.com/domains/add/site-redirect/
3. Navigate to `/sites-dashboard`.
4. Verify the Free site with redirect appears as expected in both List view and Grid view.

### CODE REVIEW

**Comment by zaguiini** [comment]
Works well 👍 

One thing I noticed is that the site switcher displays both the site status pill and the redirect pill:

image

While the SMD only displays the redirect status:

image

But I don't think it's incorrect. The site status doesn't matter if it's a redirect because the redirect takes effect immediately, so it has precedence over the status. Is that correct?

If not (meaning we want to have parity), one thing we could do is to add a pill to the right of the site URL and maintain the status in its column.

**Comment by danielbachhuber** [comment]
> The site status doesn't matter if it's a redirect because the redirect takes effect immediately, so it has precedence over the status. Is that correct?

Correct. Good thing we're refactoring the Site Switcher soon!

**Review by zaguiini — APPROVED** [review]
Great work 👍

**Review by sejas — APPROVED** [review]
Code looks good.
Tested and working as described.

I've found that the redirect shows a wrong empty state:

Screenshot 2022-08-19 at 20 18 47


However, we can fix this in another PR.

https://github.com/Automattic/wp-calypso/blob/839c330c9059dc0bbde7940a52536b7d2aa2b95f/client/sites-dashboard/components/no-sites-message.tsx#L104-L105

**Comment by danielbachhuber** [comment]
> I've found that the redirect shows a wrong empty state:

@sejas Great catch! Updated with 5d81f98823

image

**Review by zaguiini — APPROVED** [review]
Great that we have the "no redirect sites" state now 👍

**Comment by a8ci18n** [comment]
This Pull Request is now available for translation here: https://translate.wordpress.com/deliverables/7483033

Thank you @danielbachhuber for including a screenshot in the description! This is really helpful for our translators.

**Comment by p-jackson** [comment]
Thanks for the quick fix!

I took a look at the ellipsis menu actions for redirects, and although they work, they're perhaps not that relevant for a site redirect. Something for i2 I think.

`Status` isn't necessarily the greatest grouping to put `Redirect` under. I think of `Status` as short for `Launch status`, and `Redirect` isn't anything to do with that. But on the other hand `Status` is a made-up concept just for this dashboard, so we can sort of use it for whatever we want.

I thought about maybe hiding the `Redirect` from the dropdown unless the user actually has a redirect site. But maybe it's good advertising.

CC @SaxonF just making sure he's aware of the changes.

**Comment by SaxonF** [comment]
This is a good first pass, nice work @danielbachhuber !

**Comment by danielbachhuber** [comment]
> Thanks for the quick fix!

@p-jackson You're welcome!

> `Status` isn't necessarily the greatest grouping to put `Redirect` under. I think of `Status` as short for `Launch status`, and `Redirect` isn't anything to do with that. But on the other hand `Status` is a made-up concept just for this dashboard, so we can sort of use it for whatever we want.

Yeah, it's not a perfect abstraction. However, if `Status` represents the "state" of a site, then I think `Redirect` exists at the same level as `Public`, `Private`, and `Coming Soon`. Or, put another way, a `Redirect` will always redirect a user's site, so it doesn't matter if it's public or private.

> I thought about maybe hiding the `Redirect` from the dropdown unless the user actually has a redirect site. But maybe it's good advertising.

I'd lean towards hiding from the dropdown unless there's at least one, too. Our Sites Management Page will become rapidly complex unless we actively keep the UI clear.

**Comment by p-jackson** [comment]
> Or, put another way, a `Redirect` will always redirect a user's site, so it doesn't matter if it's public or private.

That's true. Putting `Redirect` in the column is better than something like `N/A`!

**Comment by a8ci18n** [comment]
Translation for this Pull Request [has now been finished](https://translate.wordpress.com/deliverables/overview/7483033).

**Pull request merged**
