### PR TITLE
Framework: Upgrade webpack and uglify

### PR DESCRIPTION
**Pull request by blowery**
Cold start is hitting an issue in Safari only where a selector is doing impossible things. We can only repro it on a prod, minified build. Trying a newer webpack (and maybe uglify? unclear how it gets picked up as webpack has it's own dep)

Test live: https://calypso.live/?branch=update/framework/uglify

### CODE REVIEW

**Comment by blowery** [comment]
To be clear, I have no idea if this fixes any issues. It's here solely for testing.

**Comment by blowery** [comment]
cc @fraying @jancavan

**Comment by fraying** [comment]
This ... https://calypso.live/recommendations/start/?branch=update/framework/uglify ... works for me.

**Comment by jancavan** [comment]
So far I can now see the post previews.

**Comment by blowery** [comment]
I have a hunch it dies on the day-over-day turnover. Let's wait a day and try it tomorrow and see how things look...

**Comment by jancavan** [comment]
It's still working fine for me.

**Pull request merged**
