### PR TITLE
Fix: Calypso Page/Posts screen on Atomic sites reverts to old design

### LINKED ISSUE #49486: Clicking All Posts goes to WP-Admin posts instead of Calypso posts page
### Steps to reproduce the behavior

1. On Atomic site, start writing a new post
2. Click the "W" on the top 
3. Click "< All Posts"
4. You're taken to Wp-admin posts page, not the calypso posts page

#### What I expected to happen
I expected to see Calypso posts page

#### What actually happened
I saw the wp-admin posts page

### Context
I was doing testing 

#### Browser / OS version
Chrome 88 MacOS

#### Is this specific to the applied theme? Which one?
no

#### Does this happen on simple or atomic sites or both?
Simple

#### Is there any console output or error text?
no

#### Level of impact (Does it block purchases? Does it affect more than just one site?)
minor

#### Screenshot / Video: If applicable, add screenshots to help explain your problem.
See Video on my comment on pciE2j-bv-p2 (to be posted)
Screen Shot 2021-01-29 at 1 20 17 PM

### LINKED ISSUE #69908: Calypso Page screen on Atomic sites reverts to old design
### Quick summary

On an Atomic site, if you go to edit a page, then return to the "Pages" screen in My Site menu, the design of the Pages screen (listing all available pages) reverts to some sort of old design. Reloading the page refreshes the screen and the design goes back to the "normal" design we're used to.

https://user-images.githubusercontent.com/37377834/200963965-cb044ab1-85aa-4507-83ba-c9b9cadba560.mov

### Steps to reproduce

1. Open an Atomic site
2. Go to My Site > Pages
3. On a page line item, click the 3-dots-menu and select Edit
4. When the Editor screen loads, click the W in the top left to open the menu, then select "< All Pages"
5. You'll be taken back to the Pages screen in My Site, except the design of the screen is now an older design
6. Selecting "Pages" from the left sidebar reloads the screen and the design updates to the "proper" screen

### What you expected to happen

The design for the Pages screen should stay a consistent design. The modern design.

### What actually happened

The Pages screen loads some sort of retro design which can be corrected upon reload.

### Context

I was able to trigger this multiple times on two different Atomic sites. This did not happen when I tried it on a Free test site.

### Platform (Simple, Atomic, or both?)

Atomic

### Theme-specific issue?

I tried on two different Atomic sites with different themes installed.

### Browser, operating system and other notes

Chrome Version 107.0.5304.87 (Official Build) (arm64)

### Reproducibility

_No response_

### Severity

_No response_

### Available workarounds?

_No response_

### Workaround details

_No response_

### PR DESCRIPTION
**Pull request by jeroenpf**
Closes https://github.com/Automattic/wp-calypso/issues/69908
Closes https://github.com/Automattic/wp-calypso/issues/49486

## Proposed Changes

This PR fixes the redirect to `wp-admin` after the users clicks on `All pages` or `All posts` when exiting a post or page editor when a) the default interface is enabled and b) the condition `is_jetpack_site_eligible_for_gutenframe` returns `false` on an Atomic site.

## Testing Instructions

**Before testing an actual issue, we would need to have the following setup**:

* Create an Atomic site (you can use WoA site)
* Install an Elementor plugin on an Atomic site (you can search for it from `Plugins` > `Add New Plugin`: https://wordpress.com/plugins/{yourAtomicSite)
* Activate Elementor plugin 
* Navigate to `Settings > Hosting Configuration`
* Set the `Admin interface style` on an Atomic site to `Default style`
* Navigate to `Plugins > Installed plugins` and disable `WordPress.com Editing Toolkit` plugin on your Atomic site
* Navigate to [Build Calypso Apps (WPCom Plugins) ](https://teamcity.a8c.com/buildConfiguration/calypso_calypso_WPComPlugins_Build_Plugins/12299310?buildTab=artifacts)and download a .zip file for the `Editing Toolkit` plugin (available under the `Artifacts` tab):

Screenshot 2024-04-12 at 3 48 34 PM

* Navigate to  `Plugins` > `Add New Plugin` on your Atomic siteL https://wordpress.com/plugins/{yourAtomicSite)
* Install the .zip file of the [editing-toolkit.zip](https://teamcity.a8c.com/repository/download/calypso_calypso_WPComPlugins_Build_Plugins/12299310:id/editing-toolkit.zip) that you just downloaded

**Testing an actual issue**:

* Once the steps above are completed, you are ready to test the issue
* Navigate to `Posts` page on your Atomic site: `https://wordpress.com/posts/{yourAtomicSite}`
* Open a post to edit (it does not matter which one, could be any post)
* Click on the WordPress icon in the top left corner to open sidebar navigate
* Click on `All Posts` button
* Confirm that you are brought back to Calypso URL and you see the default interface and not `wp-admin` interface

Screenshot 2024-04-12 at 3 55 08 PM

* Repeat the same steps for the `Pages`: `https://wordpress.com/pages/{yourAtomicSite}`
* Confirm that you are succesfully brought to Calypso URL 

**Testing that other flows work as expected **:

**Case 1: Disable Elementor + Default admin interface**:

* Deactivate Elementor plugin
* Navigate to `Settings > Hosting Configuration`
* Set the `Admin interface style` on an Atomic site to `Default style`
* Navigate to `Posts` page on your Atomic site: `https://wordpress.com/posts/{yourAtomicSite}`
* Open a post to edit (it does not matter which one, could be any post)
* Click on the WordPress icon in the top left corner to open sidebar navigate
* Click on `All Posts` button
* Confirm that you are brought back to Calypso URL and you see the default interface and not `wp-admin` interface

**Case 2: Disable Elementor + Classic admin interface**

* Deactivate Elementor plugin
* Navigate to `Settings > Hosting Configuration`
* Set the `Admin interface style` on an Atomic site to `Classic style`
* Navigate to `Posts` page on your Atomic site (this should now be showing you wp-admin interface)
* Open a post to edit (it does not matter which one, could be any post)
* Click on the WordPress icon in the top left corner to open sidebar navigate
* Click on `All Posts`/`View Posts` button
* Confirm that you are brought back to `wp-admin` interface

**Case 3: Enable Elementor + Classic admin interface**

* Activate Elementor plugin
* Navigate to `Settings > Hosting Configuration`
* Set the `Admin interface style` on an Atomic site to `Classic style`
* Navigate to `Posts` page on your Atomic site (this should now be showing you wp-admin interface)
* Open a post to edit (it does not matter which one, could be any post)
* Click on the WordPress icon in the top left corner to open sidebar navigate
* Click on `All Posts`/`View Posts` button
* Confirm that you are brought back to `wp-admin` interface

## Pre-merge Checklist

- [ ] Has the general commit checklist been followed? (PCYsg-hS-p2)
- [ ] https://wpcalypso.wordpress.com/devdocs/docs/testing/index.md for your changes?
- [ ] Have you tested the feature in Simple (P9HQHe-k8-p2), Atomic (P9HQHe-jW-p2), and self-hosted Jetpack sites (PCYsg-g6b-p2)?
- [ ] Have you checked for TypeScript, React or other console errors?
- [ ] Have you used memoizing on expensive computations? More info in [Memoizing with create-selector](https://github.com/Automattic/wp-calypso/blob/trunk/packages/state-utils/src/create-selector/README.md) and [Using memoizing selectors](https://react-redux.js.org/api/hooks#using-memoizing-selectors) and [Our Approach to Data](https://github.com/Automattic/wp-calypso/blob/trunk/docs/our-approach-to-data.md)
- [ ] Have we added the "[Status] String Freeze" label as soon as any new strings were ready for translation (p4TIVU-5Jq-p2)?
- [ ] For changes affecting Jetpack: Have we added the "[Status] Needs Privacy Updates" label if this pull request changes what data or activity we track or use (p4TIVU-aUh-p2)?

### CODE REVIEW

**Review by sejas — APPROVED** [review]
I confirm it works as expected.

I checked latest builds here:
https://teamcity.a8c.com/buildConfiguration/calypso_calypso_WPComPlugins_Build_Plugins?branch=test%2Ffix-for-all-posts-button&buildTypeTab=overview&mode=builds

Installed elementor and ETK in my atomic site and tried all the flows.

Great work! @jeroenpf and @katinthehatsite 

I noticed that some unit tests are failing.

**Comment by katinthehatsite** [comment]
Thanks for the review @sejas !

The unit tests seem to be not related, I will try to merge the trunk and see if it gets resolved.

**Comment by katinthehatsite** [comment]
Part of the issue was resolved but I noticed that there is a failing type check:

```
[08:00:48 ](https://teamcity.a8c.com/buildConfiguration/calypso_calypso_WebApp_Run_All_Unit_Tests/12397461?expandBuildDeploymentsSection=false&hideTestsFromDependencies=false&hideProblemsFromDependencies=false&expandBuildChangesSection=true&expandBuildProblemsSection=true&showLog=12397461_676_676&logFilter=debug&logView=flowAware)       Output for type_check_etk
[08:00:48 ](https://teamcity.a8c.com/buildConfiguration/calypso_calypso_WebApp_Run_All_Unit_Tests/12397461?expandBuildDeploymentsSection=false&hideTestsFromDependencies=false&hideProblemsFromDependencies=false&expandBuildChangesSection=true&expandBuildProblemsSection=true&showLog=12397461_677_677&logFilter=debug&logView=flowAware)    If no output is shown, look for it under the test section for this task.
[08:00:48 ](https://teamcity.a8c.com/buildConfiguration/calypso_calypso_WebApp_Run_All_Unit_Tests/12397461?expandBuildDeploymentsSection=false&hideTestsFromDependencies=false&hideProblemsFromDependencies=false&expandBuildChangesSection=true&expandBuildProblemsSection=true&showLog=12397461_678_678&logFilter=debug&logView=flowAware)    ....STDOUT....
[08:00:48 ](https://teamcity.a8c.com/buildConfiguration/calypso_calypso_WebApp_Run_All_Unit_Tests/12397461?expandBuildDeploymentsSection=false&hideTestsFromDependencies=false&hideProblemsFromDependencies=false&expandBuildChangesSection=true&expandBuildProblemsSection=true&showLog=12397461_679_679&logFilter=debug&logView=flowAware)    apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nux/src/welcome-tour/tour-launch.tsx(75,50): error TS2339: Property 'isGutenboarding' does not exist on type 'CalypsoifyGutenberg'.
[08:00:48 ](https://teamcity.a8c.com/buildConfiguration/calypso_calypso_WebApp_Run_All_Unit_Tests/12397461?expandBuildDeploymentsSection=false&hideTestsFromDependencies=false&hideProblemsFromDependencies=false&expandBuildChangesSection=true&expandBuildProblemsSection=true&showLog=12397461_680_680&logFilter=debug&logView=flowAware)    apps/editing-toolkit/editing-toolkit-plugin/wpcom-block-editor-nux/src/welcome-tour/tour-launch.tsx(101,54): error TS2339: Property 'isGutenboarding' does not exist on type 'CalypsoifyGutenberg'.
[08:00:48 ](https://teamcity.a8c.com/buildConfiguration/calypso_calypso_WebApp_Run_All_Unit_Tests/12397461?expandBuildDeploymentsSection=false&hideTestsFromDependencies=false&hideProblemsFromDependencies=false&expandBuildChangesSection=true&expandBuildProblemsSection=true&showLog=12397461_681_681&logFilter=debug&logView=flowAware)    
[08:00:48 ](https://teamcity.a8c.com/buildConfiguration/calypso_calypso_WebApp_Run_All_Unit_Tests/12397461?expandBuildDeploymentsSection=false&hideTestsFromDependencies=false&hideProblemsFromDependencies=false&expandBuildChangesSection=true&expandBuildProblemsSection=true&showLog=12397461_684_684&logFilter=debug&logView=flowAware)       Tests for type_check_etk
```

I will check further what is happening there 👀

**Comment by katinthehatsite** [comment]
Unit tests pass now 🥳

I am going to test the whole flow once again to make sure nothing broke and merge after 😅

**Pull request merged**
